ARTS: abs_species_tags.cc File Reference
abs_species_tags.cc File Reference
Stuff related to absorption species tags.
#include "abs_species_tags.h"
#include <cfloat>
#include <map>
#include "absorption.h"
#include "arts.h"
#include "auto_md.h"
#include "global_data.h"
Functions
ostream & operator<< (ostream &os, const SpeciesTag &ot)
Output operator for SpeciesTag.
String get_tag_group_name (const ArrayOfSpeciesTag &tg)
Return the name of a tag group as a string.
String get_species_name (const ArrayOfSpeciesTag &tg)
Return the species of a tag group as a string.
Index find_first_species_tg (const ArrayOfArrayOfSpeciesTag &tgs, const Index &spec)
Find first occurrence of species in tag groups.
Index find_next_species_tg (const ArrayOfArrayOfSpeciesTag &tgs, const Index &spec, const Index &start)
Find next occurrence of species in tag groups.
void array_species_tag_from_string (ArrayOfSpeciesTag &tags, const String &names)
Converts a String to ArrayOfSpeciesTag.
void check_abs_species (const ArrayOfArrayOfSpeciesTag &abs_species)
Check the correctness of abs_species.
bool is_zeeman (const ArrayOfSpeciesTag &tg)
Is this a Zeeman tag group?
void get_tag_group_index_for_tag_group (Index &tags1_index, const ArrayOfArrayOfSpeciesTag &tags1, const ArrayOfSpeciesTag &tag2)
Returns the index of the tag group tg2 within the array of tag groups tgs1.
Index find_first_species_tg (const ArrayOfArrayOfSpeciesTag &list_of_tags, const SpeciesTag &tag)
Return the position in the list of tags that contain tag.
Detailed Description
Stuff related to absorption species tags.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue May 31 17:18:22 2005
This file contains functions related to SpeciesTags. It is better to separate this from the other absorption functions, since this part was actually improved in arts-1-1 and should be kept, whereas most other absorption stuff is back-ported from arts-1-0.
Definition in file abs_species_tags.cc.
Function Documentation
array_species_tag_from_string()
void array_species_tag_from_string (ArrayOfSpeciesTag & tags, const String & names)
Converts a String to ArrayOfSpeciesTag.
This function is used when preparing strings read from e.g. control files to be stored as SpeciesTag in abs_species.
Note: This is originally a part of abs_speciesSet.
Parameters
tags Array of SpeciesTag.
names String with species.
Author
Mattias Ekstroem
Date
2004-09-30
Definition at line 553 of file abs_species_tags.cc.
References ARTS_USER_ERROR_IF, go_on, Array< base >::nelem(), my_basic_string< charT >::npos, SpeciesTag::Species(), Species, SpeciesTag::Type(), Type, SpeciesTag::TYPE_PLAIN, and SpeciesTag::TYPE_ZEEMAN.
Referenced by abs_speciesAdd(), abs_speciesAdd2(), abs_speciesSet(), is_special_vmr(), jacobianAddAbsSpecies(), species_match(), and x2artsAtmAndSurf().
check_abs_species()
void check_abs_species (const ArrayOfArrayOfSpeciesTag & abs_species)
Check the correctness of abs_species.
Checks on the correctness of the tags will be performed, e.g. free_electrons and particles species are only allowed once in abs_species.
Parameters
tags Array of Array of SpeciesTag.
Author
Oliver Lemke
Date
2013-04-23
Definition at line 614 of file abs_species_tags.cc.
References ARTS_USER_ERROR_IF, Array< base >::nelem(), Absorption::nelem(), Type, SpeciesTag::TYPE_FREE_ELECTRONS, SpeciesTag::TYPE_HITRAN_XSEC, and SpeciesTag::TYPE_PARTICLES.
Referenced by abs_speciesAdd(), abs_speciesAdd2(), and abs_speciesSet().
find_first_species_tg() [1/2]
Index find_first_species_tg (const ArrayOfArrayOfSpeciesTag & list_of_tags, const SpeciesTag & tag)
Return the position in the list of tags that contain tag.
If there is no tag in the list of tags, then return -1
Parameters
[in] list_of_tags A list of several tags
[in] tag A single tag that might be in one of the listed tags
Returns
Position in list or -1
Definition at line 708 of file abs_species_tags.cc.
References Array< base >::nelem().
find_first_species_tg() [2/2]
Index find_first_species_tg (const ArrayOfArrayOfSpeciesTag & tgs, const Index & spec)
Find first occurrence of species in tag groups.
The species to look for must be specified by its species index, not by the name. Use the helper function to get the species index from the species name if necessary.
See also
species_index_from_species_name.
Parameters
tgs The species tags to search in.
spec The species index of the species to look for.
Returns
The index of spec in tgs, -1 if not found.
Author
Stefan Buehler
Date
2003-01-13
Definition at line 499 of file abs_species_tags.cc.
References find_next_species_tg().
Referenced by abs_lookupSetup(), abs_lookupSetupBatch(), abs_xsec_agenda_checkedCalc(), abs_xsec_per_speciesAddCIA(), GasAbsLookup::Extract(), refr_index_airMicrowavesEarth(), and set_vmr_from_first_species().
find_next_species_tg()
Index find_next_species_tg (const ArrayOfArrayOfSpeciesTag & tgs, const Index & spec, const Index & start)
Find next occurrence of species in tag groups.
The species to look for must be specified by its species index, not by the name. Use the helper function to get the species index from the species name if necessary.
See also
species_index_from_species_name.
Parameters
tgs The species tags to search in.
spec The species index of the species to look for.
start The index position at which to start the search (0 would be the very beginning).
Returns
The index of spec in tgs, -1 if not found.
Author
Stefan Buehler
Date
2007-11-16
Definition at line 522 of file abs_species_tags.cc.
References Array< base >::nelem(), Species, and Zeeman::start().
Referenced by choose_abs_nls(), and find_first_species_tg().
get_species_name()
String get_species_name (const ArrayOfSpeciesTag & tg)
Return the species of a tag group as a string.
A tag group consists of several elementary SpeciesTags, which must all belong to the same molecular species. This function returns a string with the name of the species. This is nice for informational output messages, for example in the absorption routines.
E.g., if the tag group is: "H2O-161, H2O-181", then the function will return "H2O".
It also does a safety check that really all tags belong to the same species.
Parameters
tg The tag group in question.
Returns
The name of the species, as it should be used in gridded atmospheric fields, for example.
Author
Stefan Buehler
Date
2009-06-11
Definition at line 467 of file abs_species_tags.cc.
References ARTS_USER_ERROR_IF, get_tag_group_name(), Array< base >::nelem(), Species, and species_name_from_species_index().
Referenced by abs_lookupSetupBatch(), and propmat_clearsky_fieldCalc().
get_tag_group_index_for_tag_group()
void get_tag_group_index_for_tag_group (Index & tags1_index, const ArrayOfArrayOfSpeciesTag & tags1, const ArrayOfSpeciesTag & tag2)
Returns the index of the tag group tg2 within the array of tag groups tgs1.
Slightly modified copy of get_tagindex_for_Strings.
Exceptions
runtime_error Could not find tg2 in tgs1.
Return values
tgs1_index Index in tgs1 for tg2
Parameters
tgs1 The tags groups to search in.
tg2 The tag group for which the index shall be found.
Author
Patrick Eriksson, Axel von Engeln, and Stefan Buehler
Date
2001-01-31
Definition at line 681 of file abs_species_tags.cc.
References ARTS_USER_ERROR_IF, and Array< base >::nelem().
get_tag_group_name()
String get_tag_group_name (const ArrayOfSpeciesTag & tg)
Return the name of a tag group as a string.
A tag group consists of several elementary SpeciesTags. This function returns a String with the name of the entire tag group. This is nice for informational output messages, for example in the absorption routines.
Parameters
tg The tag group in question.
Returns
The full name of the tag group, as it could occur in the controlfile.
Author
Stefan Buehler
Date
2001-03-13
Definition at line 434 of file abs_species_tags.cc.
References Array< base >::nelem().
Referenced by GasAbsLookup::Adapt(), and get_species_name().
is_zeeman()
bool is_zeeman (const ArrayOfSpeciesTag & tg)
Is this a Zeeman tag group?
It is not enough to just look at the first tag to find out if this is a Zeeman tag group, since there could be some predefined absorption or CIA tag first.
Returns
true if this is a Zeeman tag group, otherwise false.
Parameters
tg The tag group to check
Author
Stefan Buehler
Date
2013-01-15
Definition at line 663 of file abs_species_tags.cc.
References Array< base >::nelem(), Type, and SpeciesTag::TYPE_ZEEMAN.
Referenced by abs_xsec_per_speciesAddLines(), and zeeman_on_the_fly().
operator<<()
ostream& operator<< (ostream & os, const SpeciesTag & ot)
Output operator for SpeciesTag.
Author
Stefan Buehler
Definition at line 417 of file abs_species_tags.cc.
References SpeciesTag::Name().