ARTS: absorptionlines.h File Reference
absorptionlines.h File Reference
Contains the absorption namespace.
#include <vector>
#include "bifstream.h"
#include "bofstream.h"
#include "enums.h"
#include "lineshapemodel.h"
#include "matpack.h"
#include "quantum.h"
#include "zeemandata.h"
Classes
class Absorption::SingleLine
Computations and data for a single absorption line.
struct Absorption::SingleLineExternal
Single line reading output.
class Absorption::Lines
Namespaces
Absorption
Namespace to contain things required for absorption calculations.
Typedefs
typedef Absorption::SingleLine AbsorptionSingleLine
typedef Absorption::Lines AbsorptionLines
typedef Array< AbsorptionLines > ArrayOfAbsorptionLines
typedef Array< ArrayOfAbsorptionLines > ArrayOfArrayOfAbsorptionLines
using AbsorptionNormalizationType = Absorption::NormalizationType
using AbsorptionPopulationType = Absorption::PopulationType
using AbsorptionMirroringType = Absorption::MirroringType
using AbsorptionCutoffType = Absorption::CutoffType
Functions
Absorption::ENUMCLASS (MirroringType, char, None, Lorentz, SameAsLineShape, Manual) const expr std
Describes the type of mirroring line effects.
Absorption::ENUMCLASS (PopulationType, char, LTE, NLTE, VibTemps, ByHITRANRosenkranzRelmat, ByHITRANFullRelmat, ByMakarovFullRelmat, ByRovibLinearDipoleLineMixing) const expr std
Describes the type of population level counter.
constexpr bool Absorption::relaxationtype_relmat (PopulationType in) noexcept
Absorption::ENUMCLASS (CutoffType, char, None, ByLine) String cutofftype2metadatastring(CutoffType in
Describes the type of cutoff calculations.
std::ostream & Absorption::operator<< (std::ostream &, const SingleLine &)
std::istream & Absorption::operator>> (std::istream &, SingleLine &)
std::ostream & Absorption::operator<< (std::ostream &, const Lines &)
std::istream & Absorption::operator>> (std::istream &, Lines &)
SingleLineExternal Absorption::ReadFromArtscat3Stream (istream &is)
Read from ARTSCAT-3.
SingleLineExternal Absorption::ReadFromArtscat4Stream (istream &is)
Read from ARTSCAT-4.
SingleLineExternal Absorption::ReadFromArtscat5Stream (istream &is)
Read from ARTSCAT-5.
SingleLineExternal Absorption::ReadFromLBLRTMStream (istream &is)
Read from LBLRTM.
SingleLineExternal Absorption::ReadFromHitran2012Stream (istream &is)
Read from newer HITRAN.
SingleLineExternal Absorption::ReadFromHitran2004Stream (istream &is)
Read from newer HITRAN.
SingleLineExternal Absorption::ReadFromHitranOnlineStream (istream &is)
Read from HITRAN online.
SingleLineExternal Absorption::ReadFromHitran2001Stream (istream &is)
Read from HITRAN before 2004.
SingleLineExternal Absorption::ReadFromJplStream (istream &is)
Read from JPL.
std::vector< Lines > Absorption::split_list_of_external_lines (std::vector< SingleLineExternal > &external_lines, const std::vector< QuantumNumberType > &localquantas={}, const std::vector< QuantumNumberType > &globalquantas={})
Splits a list of lines into proper Lines.
Lines Absorption::createEmptyCopy (const Lines &al) noexcept
Creates a copy of the input lines structure.
Index Absorption::nelem (const Lines &l)
Number of lines.
Index Absorption::nelem (const Array< Lines > &l)
Number of lines in list.
Index Absorption::nelem (const Array< Array< Lines >> &l)
Number of lines in lists.
Numeric Absorption::reduced_rovibrational_dipole (Rational Jf, Rational Ji, Rational lf, Rational li, Rational k=Rational(1))
Compute the reduced rovibrational dipole moment.
Numeric Absorption::reduced_magnetic_quadrapole (Rational Jf, Rational Ji, Rational N)
Compute the reduced magnetic quadrapole moment.
Absorption::ENUMCLASS (QuantumIdentifierLineTargetType, char, None, Species, Isotopologue, Band, Line, Level) struct QuantumIdentifierLineTarget
Keep track of the target type and position in Lines of a Jacobian Target.
std::ostream & operator<< (std::ostream &, const ArrayOfAbsorptionLines &)
std::ostream & operator<< (std::ostream &, const ArrayOfArrayOfAbsorptionLines &)
Variables
Numeric Absorption::cutoff
Detailed Description
Contains the absorption namespace.
Author
Richard Larsson
Date
2019-09-07
Contains the absorption lines implementation
This namespace contains classes to deal with absorption lines
Definition in file absorptionlines.h.
Typedef Documentation
AbsorptionCutoffType
using AbsorptionCutoffType = Absorption::CutoffType
Definition at line 1588 of file absorptionlines.h.
AbsorptionLines
typedef Absorption::Lines AbsorptionLines
Definition at line 1577 of file absorptionlines.h.
AbsorptionMirroringType
using AbsorptionMirroringType = Absorption::MirroringType
Definition at line 1587 of file absorptionlines.h.
AbsorptionNormalizationType
using AbsorptionNormalizationType = Absorption::NormalizationType
Definition at line 1585 of file absorptionlines.h.
AbsorptionPopulationType
using AbsorptionPopulationType = Absorption::PopulationType
Definition at line 1586 of file absorptionlines.h.
AbsorptionSingleLine
typedef Absorption::SingleLine AbsorptionSingleLine
Definition at line 1576 of file absorptionlines.h.
ArrayOfAbsorptionLines
typedef Array<AbsorptionLines> ArrayOfAbsorptionLines
Definition at line 1578 of file absorptionlines.h.
ArrayOfArrayOfAbsorptionLines
typedef Array<ArrayOfAbsorptionLines> ArrayOfArrayOfAbsorptionLines
Definition at line 1579 of file absorptionlines.h.
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const ArrayOfAbsorptionLines & aol)
Definition at line 2197 of file absorptionlines.cc.
References Interpolation::l().
Referenced by Species::ENUMCLASS().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfAbsorptionLines & aol)
Definition at line 2204 of file absorptionlines.cc.
References Interpolation::l().