ARTS: absorptionlines.cc File Reference
absorptionlines.cc File Reference
Contains the absorption namespace.
#include "absorptionlines.h"
#include "absorption.h"
#include "constants.h"
#include "file.h"
#include "hitran_species.h"
#include "jpl_species.h"
#include "quantum_parser_hitran.h"
Namespaces
Absorption
Namespace to contain things required for absorption calculations.
Functions
std::vector< std::array< String, 2 > > split_quantum_numbers_from_hitran_online (String &qns)
std::ostream & operator<< (std::ostream &os, const ArrayOfAbsorptionLines &aol)
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfAbsorptionLines &aol)
String Absorption::cutofftype2metadatastring (CutoffType in, Numeric cutoff)
Detailed Description
Contains the absorption namespace.
Author
Richard Larsson
Date
2019-09-07
Contains the absorption lines implementation
This namespace contains classes to deal with absorption lines
Definition in file absorptionlines.cc.
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const ArrayOfAbsorptionLines & aol)
Definition at line 2197 of file absorptionlines.cc.
References Interpolation::l().
Referenced by Species::ENUMCLASS().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfAbsorptionLines & aol)
Definition at line 2204 of file absorptionlines.cc.
References Interpolation::l().
split_quantum_numbers_from_hitran_online()
std::vector<std::array<String, 2> > split_quantum_numbers_from_hitran_online (String & qns)
Definition at line 1167 of file absorptionlines.cc.
References Raw::Average::var().