ARTS: agenda_record.cc File Reference
agenda_record.cc File Reference
Implementation of agendas.
#include "agenda_record.h"
#include <iostream>
#include <map>
#include "messages.h"
#include "workspace_ng.h"
#include "wsv_aux.h"
Namespaces
global_data
Functions
void define_agenda_map ()
bool check_agenda_data ()
Check that agendas.cc and workspace.cc are consistent.
ostream & operator<< (ostream &os, const AgRecord &agr)
Output operator for AgRecord.
ostream & operator<< (ostream &os, const WsvRecord &wr)
Output operator for WsvRecord.
void write_agenda_wrapper_header (ofstream &ofs, const AgRecord &agr, bool is_agenda_array)
Write a agenda wrapper header.
Variables
map< String, Index > global_data::AgendaMap
The map associated with agenda_data.
const Array< AgRecord > global_data::agenda_data
The lookup information for the agendas.
const ArrayOfString global_data::wsv_group_names
The names associated with Wsv groups as Strings.
Detailed Description
Implementation of agendas.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Thu Mar 14 08:49:33 2002
Definition in file agenda_record.cc.
Function Documentation
check_agenda_data()
bool check_agenda_data ()
Check that agendas.cc and workspace.cc are consistent.
This functions makes sure, that there is a matching entry in both lookup tables for each agenda.
If the function returns at all, it will return true. The return value is only there so that we can put the function call in an assert statement.
Returns
Always true.
Definition at line 115 of file agenda_record.cc.
References global_data::agenda_data, global_data::AgendaMap, and DEBUG_ONLY.
Referenced by InteractiveWorkspace::initialize(), and main().
define_agenda_map()
void define_agenda_map ()
Definition at line 95 of file agenda_record.cc.
References global_data::agenda_data, and global_data::AgendaMap.
Referenced by InteractiveWorkspace::initialize(), and main().
operator<<() [1/2]
ostream& operator<< (ostream & os, const AgRecord & agr)
Output operator for AgRecord.
Parameters
os Output stream.
agr Agenda record.
Returns
Output stream.
Definition at line 177 of file agenda_record.cc.
References AgRecord::Description(), AgRecord::In(), AgRecord::Name(), Absorption::nelem(), AgRecord::Out(), and Workspace::wsv_data.
operator<<() [2/2]
ostream& operator<< (ostream & os, const WsvRecord & wr)
Output operator for WsvRecord.
This has to be here rather than with workspace.cc or workspace_aux.cc, because it uses agenda_data and AgendaMap.
Parameters
os Output stream.
wr Workspace variable record.
Returns
Output stream.
Definition at line 229 of file agenda_record.cc.
References global_data::agenda_data, global_data::AgendaMap, WsvRecord::Description(), get_wsv_group_id(), WsvRecord::Group(), WsvRecord::Name(), and global_data::wsv_group_names.
write_agenda_wrapper_header()
void write_agenda_wrapper_header (ofstream & ofs, const AgRecord & agr, bool is_agenda_array)
Write a agenda wrapper header.
Parameters
ofs The stream to write to.
agr Agenda record.
Definition at line 270 of file agenda_record.cc.
References AgRecord::In(), AgRecord::Name(), AgRecord::Out(), Workspace::wsv_data, and global_data::wsv_group_names.
Referenced by main().