ARTS: agenda_record.h File Reference
agenda_record.h File Reference
Declarations for AgRecord, storing lookup information for one agenda.
#include <iostream>
#include "arts.h"
#include "mystring.h"
Classes
class AgRecord
Lookup information for one agenda.
Functions
void define_agenda_data ()
void define_agenda_map ()
bool check_agenda_data ()
Check that agendas.cc and workspace.cc are consistent.
void write_agenda_wrapper_header (ofstream &ofs, const AgRecord &agr, bool is_agenda_array)
Write a agenda wrapper header.
ostream & operator<< (ostream &os, const AgRecord &agr)
Output operator for AgRecord.
Detailed Description
Declarations for AgRecord, storing lookup information for one agenda.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Thu Mar 14 08:49:33 2002
Definition in file agenda_record.h.
Function Documentation
check_agenda_data()
bool check_agenda_data ()
Check that agendas.cc and workspace.cc are consistent.
This functions makes sure, that there is a matching entry in both lookup tables for each agenda.
If the function returns at all, it will return true. The return value is only there so that we can put the function call in an assert statement.
Returns
Always true.
Definition at line 115 of file agenda_record.cc.
References global_data::agenda_data, global_data::AgendaMap, and DEBUG_ONLY.
Referenced by InteractiveWorkspace::initialize(), and main().
define_agenda_data()
void define_agenda_data ()
Definition at line 44 of file agendas.cc.
References global_data::agenda_data, DESCRIPTION, INPUT, NAME, and OUTPUT.
Referenced by InteractiveWorkspace::initialize(), and main().
define_agenda_map()
void define_agenda_map ()
Definition at line 95 of file agenda_record.cc.
References global_data::agenda_data, and global_data::AgendaMap.
Referenced by InteractiveWorkspace::initialize(), and main().
operator<<()
ostream& operator<< (ostream & os, const AgRecord & agr)
Output operator for AgRecord.
Parameters
os Output stream.
agr Agenda record.
Returns
Output stream.
Definition at line 177 of file agenda_record.cc.
References AgRecord::Description(), AgRecord::In(), AgRecord::Name(), Absorption::nelem(), AgRecord::Out(), and Workspace::wsv_data.
write_agenda_wrapper_header()
void write_agenda_wrapper_header (ofstream & ofs, const AgRecord & agr, bool is_agenda_array)
Write a agenda wrapper header.
Parameters
ofs The stream to write to.
agr Agenda record.
Definition at line 270 of file agenda_record.cc.
References AgRecord::In(), AgRecord::Name(), AgRecord::Out(), Workspace::wsv_data, and global_data::wsv_group_names.
Referenced by main().