ARTS: agendas.cc File Reference
agendas.cc File Reference
Initialize lookup data for agendas.
#include "agenda_record.h"
Namespaces
global_data
Macros
#define NAME(x) x
#define DESCRIPTION(x) x
#define OUTPUT(...) { __VA_ARGS__ }
#define INPUT(...) { __VA_ARGS__ }
Functions
void define_agenda_data ()
Detailed Description
Initialize lookup data for agendas.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Thu Mar 14 08:49:33 2002
The lookup data mainly contains information on the required output and input.
Definition in file agendas.cc.
Macro Definition Documentation
DESCRIPTION
#define DESCRIPTION (x) x
Definition at line 33 of file agendas.cc.
INPUT
#define INPUT (...) { __VA_ARGS__ }
Definition at line 36 of file agendas.cc.
NAME
#define NAME (x) x
Definition at line 32 of file agendas.cc.
OUTPUT
#define OUTPUT (...) { __VA_ARGS__ }
Definition at line 34 of file agendas.cc.
Function Documentation
define_agenda_data()
void define_agenda_data ()
Definition at line 44 of file agendas.cc.
References global_data::agenda_data, DESCRIPTION, INPUT, NAME, and OUTPUT.
Referenced by ARTS::init(), InteractiveWorkspace::initialize(), and main().