var annotated_dup =
[
    [ "Absorption", "namespaceAbsorption.html", [
      [ "LineMixing", "namespaceAbsorption_1_1LineMixing.html", [
        [ "RosenkranzAdaptation", "structAbsorption_1_1LineMixing_1_1RosenkranzAdaptation.html", "structAbsorption_1_1LineMixing_1_1RosenkranzAdaptation" ],
        [ "EquivalentLines", "structAbsorption_1_1LineMixing_1_1EquivalentLines.html", "structAbsorption_1_1LineMixing_1_1EquivalentLines" ],
        [ "PopulationAndDipole", "structAbsorption_1_1LineMixing_1_1PopulationAndDipole.html", "structAbsorption_1_1LineMixing_1_1PopulationAndDipole" ]
      ] ],
      [ "SingleLine", "classAbsorption_1_1SingleLine.html", "classAbsorption_1_1SingleLine" ],
      [ "SingleLineExternal", "structAbsorption_1_1SingleLineExternal.html", "structAbsorption_1_1SingleLineExternal" ],
      [ "Lines", "classAbsorption_1_1Lines.html", "classAbsorption_1_1Lines" ]
    ] ],
    [ "Interpolation", "namespaceInterpolation.html", [
      [ "Grid", "classInterpolation_1_1Grid.html", "classInterpolation_1_1Grid" ],
      [ "FixedGrid", "classInterpolation_1_1FixedGrid.html", "classInterpolation_1_1FixedGrid" ],
      [ "Lagrange", "structInterpolation_1_1Lagrange.html", "structInterpolation_1_1Lagrange" ],
      [ "FixedLagrange", "structInterpolation_1_1FixedLagrange.html", "structInterpolation_1_1FixedLagrange" ]
    ] ],
    [ "Jacobian", "namespaceJacobian.html", [
      [ "Target", "classJacobian_1_1Target.html", "classJacobian_1_1Target" ]
    ] ],
    [ "lapack_help", "namespacelapack__help.html", [
      [ "Inverse", "structlapack__help_1_1Inverse.html", "structlapack__help_1_1Inverse" ]
    ] ],
    [ "Linefunctions", "namespaceLinefunctions.html", [
      [ "InternalData", "classLinefunctions_1_1InternalData.html", "classLinefunctions_1_1InternalData" ]
    ] ],
    [ "LineShape", "namespaceLineShape.html", [
      [ "ModelParameters", "structLineShape_1_1ModelParameters.html", "structLineShape_1_1ModelParameters" ],
      [ "SingleSpeciesModel", "classLineShape_1_1SingleSpeciesModel.html", "classLineShape_1_1SingleSpeciesModel" ],
      [ "Model", "classLineShape_1_1Model.html", "classLineShape_1_1Model" ]
    ] ],
    [ "lm_hitran_2017", "namespacelm__hitran__2017.html", [
      [ "CommonBlock", "structlm__hitran__2017_1_1CommonBlock.html", "structlm__hitran__2017_1_1CommonBlock" ],
      [ "ConvTPOut", "structlm__hitran__2017_1_1ConvTPOut.html", "structlm__hitran__2017_1_1ConvTPOut" ]
    ] ],
    [ "Minimize", "namespaceMinimize.html", [
      [ "T4", "structMinimize_1_1T4.html", "structMinimize_1_1T4" ],
      [ "DPL", "structMinimize_1_1DPL.html", "structMinimize_1_1DPL" ]
    ] ],
    [ "oem", "namespaceoem.html", [
      [ "NormalizingSolver", "classoem_1_1NormalizingSolver.html", "classoem_1_1NormalizingSolver" ],
      [ "OptimizerLog", "structoem_1_1OptimizerLog.html", null ],
      [ "OptimizerLog< invlib::LevenbergMarquardt< RealType, DampingMatrix, Solver > >", "structoem_1_1OptimizerLog_3_01invlib_1_1LevenbergMarquardt_3_01RealType_00_01DampingMatrix_00_01Solver_01_4_01_4.html", null ],
      [ "OptimizerLog< invlib::GaussNewton< RealType, Solver > >", "structoem_1_1OptimizerLog_3_01invlib_1_1GaussNewton_3_01RealType_00_01Solver_01_4_01_4.html", null ],
      [ "ArtsLog", "classoem_1_1ArtsLog.html", "classoem_1_1ArtsLog" ],
      [ "AgendaWrapper", "classoem_1_1AgendaWrapper.html", "classoem_1_1AgendaWrapper" ],
      [ "AgendaWrapperMPI", "classoem_1_1AgendaWrapperMPI.html", "classoem_1_1AgendaWrapperMPI" ]
    ] ],
    [ "Zeeman", "namespaceZeeman.html", [
      [ "SplittingData", "structZeeman_1_1SplittingData.html", "structZeeman_1_1SplittingData" ],
      [ "Model", "classZeeman_1_1Model.html", "classZeeman_1_1Model" ],
      [ "PolarizationVector", "classZeeman_1_1PolarizationVector.html", "classZeeman_1_1PolarizationVector" ],
      [ "AllPolarizationVectors", "structZeeman_1_1AllPolarizationVectors.html", "structZeeman_1_1AllPolarizationVectors" ],
      [ "Derived", "structZeeman_1_1Derived.html", "structZeeman_1_1Derived" ]
    ] ],
    [ "Agenda", "classAgenda.html", "classAgenda" ],
    [ "AgendaData", "structAgendaData.html", "structAgendaData" ],
    [ "AgRecord", "classAgRecord.html", "classAgRecord" ],
    [ "alist", "structalist.html", "structalist" ],
    [ "Any", "classAny.html", null ],
    [ "Array", "classArray.html", "classArray" ],
    [ "ArtsOut", "classArtsOut.html", "classArtsOut" ],
    [ "ArtsOut0", "classArtsOut0.html", "classArtsOut0" ],
    [ "ArtsOut1", "classArtsOut1.html", "classArtsOut1" ],
    [ "ArtsOut2", "classArtsOut2.html", "classArtsOut2" ],
    [ "ArtsOut3", "classArtsOut3.html", "classArtsOut3" ],
    [ "ArtsParser", "classArtsParser.html", "classArtsParser" ],
    [ "ArtsXMLTag", "classArtsXMLTag.html", "classArtsXMLTag" ],
    [ "bifstream", "classbifstream.html", "classbifstream" ],
    [ "binio", "classbinio.html", "classbinio" ],
    [ "binistream", "classbinistream.html", "classbinistream" ],
    [ "binostream", "classbinostream.html", "classbinostream" ],
    [ "binstream", "classbinstream.html", "classbinstream" ],
    [ "Block", "classBlock.html", "classBlock" ],
    [ "bofstream", "classbofstream.html", "classbofstream" ],
    [ "Callback", "classCallback.html", "classCallback" ],
    [ "CIARecord", "classCIARecord.html", "classCIARecord" ],
    [ "cilist", "structcilist.html", "structcilist" ],
    [ "cllist", "structcllist.html", "structcllist" ],
    [ "CmpArrayOfNumeric", "classCmpArrayOfNumeric.html", "classCmpArrayOfNumeric" ],
    [ "complex_t", "structcomplex__t.html", "structcomplex__t" ],
    [ "ComplexIterator1D", "classComplexIterator1D.html", "classComplexIterator1D" ],
    [ "ComplexIterator2D", "classComplexIterator2D.html", "classComplexIterator2D" ],
    [ "ComplexMatrix", "classComplexMatrix.html", "classComplexMatrix" ],
    [ "ComplexMatrixView", "classComplexMatrixView.html", "classComplexMatrixView" ],
    [ "ComplexVector", "classComplexVector.html", "classComplexVector" ],
    [ "ComplexVectorView", "classComplexVectorView.html", "classComplexVectorView" ],
    [ "ConstComplexIterator1D", "classConstComplexIterator1D.html", "classConstComplexIterator1D" ],
    [ "ConstComplexIterator2D", "classConstComplexIterator2D.html", "classConstComplexIterator2D" ],
    [ "ConstComplexMatrixView", "classConstComplexMatrixView.html", "classConstComplexMatrixView" ],
    [ "ConstComplexVectorView", "classConstComplexVectorView.html", "classConstComplexVectorView" ],
    [ "ConstIterator1D", "classConstIterator1D.html", "classConstIterator1D" ],
    [ "ConstIterator2D", "classConstIterator2D.html", "classConstIterator2D" ],
    [ "ConstIterator3D", "classConstIterator3D.html", "classConstIterator3D" ],
    [ "ConstIterator4D", "classConstIterator4D.html", "classConstIterator4D" ],
    [ "ConstIterator5D", "classConstIterator5D.html", "classConstIterator5D" ],
    [ "ConstIterator6D", "classConstIterator6D.html", "classConstIterator6D" ],
    [ "ConstIterator7D", "classConstIterator7D.html", "classConstIterator7D" ],
    [ "ConstMatrixView", "classConstMatrixView.html", "classConstMatrixView" ],
    [ "consts_1_", "structconsts__1__.html", "structconsts__1__" ],
    [ "ConstTensor3View", "classConstTensor3View.html", "classConstTensor3View" ],
    [ "ConstTensor4View", "classConstTensor4View.html", "classConstTensor4View" ],
    [ "ConstTensor5View", "classConstTensor5View.html", "classConstTensor5View" ],
    [ "ConstTensor6View", "classConstTensor6View.html", "classConstTensor6View" ],
    [ "ConstTensor7View", "classConstTensor7View.html", "classConstTensor7View" ],
    [ "ConstVectorView", "classConstVectorView.html", "classConstVectorView" ],
    [ "CovarianceMatrix", "classCovarianceMatrix.html", "classCovarianceMatrix" ],
    [ "CovarianceMatrixBlockStruct", "structCovarianceMatrixBlockStruct.html", "structCovarianceMatrixBlockStruct" ],
    [ "double_imanip", "classdouble__imanip.html", "classdouble__imanip" ],
    [ "double_istream", "classdouble__istream.html", "classdouble__istream" ],
    [ "doublecomplex", "structdoublecomplex.html", "structdoublecomplex" ],
    [ "energ_1_", "structenerg__1__.html", "structenerg__1__" ],
    [ "EnergyLevelMap", "classEnergyLevelMap.html", "classEnergyLevelMap" ],
    [ "Eot", "classEot.html", "classEot" ],
    [ "fh2oa_1_", "structfh2oa__1__.html", "structfh2oa__1__" ],
    [ "fh2ob_1_", "structfh2ob__1__.html", "structfh2ob__1__" ],
    [ "fh2ob_2_", "structfh2ob__2__.html", "structfh2ob__2__" ],
    [ "Field3D", "classField3D.html", "classField3D" ],
    [ "GasAbsLookup", "classGasAbsLookup.html", "classGasAbsLookup" ],
    [ "GriddedField", "classGriddedField.html", "classGriddedField" ],
    [ "GriddedField1", "classGriddedField1.html", "classGriddedField1" ],
    [ "GriddedField2", "classGriddedField2.html", "classGriddedField2" ],
    [ "GriddedField3", "classGriddedField3.html", "classGriddedField3" ],
    [ "GriddedField4", "classGriddedField4.html", "classGriddedField4" ],
    [ "GriddedField5", "classGriddedField5.html", "classGriddedField5" ],
    [ "GriddedField6", "classGriddedField6.html", "classGriddedField6" ],
    [ "GridPos", "structGridPos.html", "structGridPos" ],
    [ "Group", "structGroup.html", "structGroup" ],
    [ "gsl_integration_glfixed_table", "structgsl__integration__glfixed__table.html", "structgsl__integration__glfixed__table" ],
    [ "gsl_poly_complex_workspace", "structgsl__poly__complex__workspace.html", "structgsl__poly__complex__workspace" ],
    [ "gsl_rng", "structgsl__rng.html", "structgsl__rng" ],
    [ "gsl_rng_type", "structgsl__rng__type.html", "structgsl__rng__type" ],
    [ "gzstreambase", "classgzstreambase.html", "classgzstreambase" ],
    [ "gzstreambuf", "classgzstreambuf.html", "classgzstreambuf" ],
    [ "HitranRelaxationMatrixData", "structHitranRelaxationMatrixData.html", "structHitranRelaxationMatrixData" ],
    [ "icilist", "structicilist.html", "structicilist" ],
    [ "igzstream", "classigzstream.html", "classigzstream" ],
    [ "IllegalLinebreak", "classIllegalLinebreak.html", "classIllegalLinebreak" ],
    [ "IndexComp", "classIndexComp.html", "classIndexComp" ],
    [ "inlist", "structinlist.html", "structinlist" ],
    [ "InteractiveWorkspace", "classInteractiveWorkspace.html", "classInteractiveWorkspace" ],
    [ "IsotopologueRecord", "classIsotopologueRecord.html", "classIsotopologueRecord" ],
    [ "Iterator1D", "classIterator1D.html", "classIterator1D" ],
    [ "Iterator2D", "classIterator2D.html", "classIterator2D" ],
    [ "Iterator3D", "classIterator3D.html", "classIterator3D" ],
    [ "Iterator4D", "classIterator4D.html", "classIterator4D" ],
    [ "Iterator5D", "classIterator5D.html", "classIterator5D" ],
    [ "Iterator6D", "classIterator6D.html", "classIterator6D" ],
    [ "Iterator7D", "classIterator7D.html", "classIterator7D" ],
    [ "jacobianVMRcheck", "structjacobianVMRcheck.html", "structjacobianVMRcheck" ],
    [ "Joker", "classJoker.html", null ],
    [ "LazyScale", "classLazyScale.html", "classLazyScale" ],
    [ "like_1_", "structlike__1__.html", "structlike__1__" ],
    [ "LinearModel", "classLinearModel.html", "classLinearModel" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "MatrixView", "classMatrixView.html", "classMatrixView" ],
    [ "MCAntenna", "classMCAntenna.html", "classMCAntenna" ],
    [ "MdRecord", "classMdRecord.html", "classMdRecord" ],
    [ "Method", "structMethod.html", "structMethod" ],
    [ "MethodStruct", "structMethodStruct.html", "structMethodStruct" ],
    [ "MockData", "structMockData.html", "structMockData" ],
    [ "MRecord", "classMRecord.html", "classMRecord" ],
    [ "mt_state_t", "structmt__state__t.html", "structmt__state__t" ],
    [ "Multitype", "unionMultitype.html", "unionMultitype" ],
    [ "my_basic_string", "classmy__basic__string.html", "classmy__basic__string" ],
    [ "n2part_1_", "structn2part__1__.html", "structn2part__1__" ],
    [ "n2part_2_", "structn2part__2__.html", "structn2part__2__" ],
    [ "Namelist", "structNamelist.html", "structNamelist" ],
    [ "NameMaps", "structNameMaps.html", "structNameMaps" ],
    [ "ogzstream", "classogzstream.html", "classogzstream" ],
    [ "olist", "structolist.html", "structolist" ],
    [ "option", "structoption.html", "structoption" ],
    [ "Output2", "structOutput2.html", "structOutput2" ],
    [ "Output4", "structOutput4.html", "structOutput4" ],
    [ "Parameters", "classParameters.html", "classParameters" ],
    [ "ParseError", "classParseError.html", "classParseError" ],
    [ "Ppath", "structPpath.html", "structPpath" ],
    [ "PropagationMatrix", "classPropagationMatrix.html", "classPropagationMatrix" ],
    [ "QuadraticModel", "classQuadraticModel.html", "classQuadraticModel" ],
    [ "QuantumFieldDescription", "classQuantumFieldDescription.html", "classQuantumFieldDescription" ],
    [ "QuantumIdentifier", "classQuantumIdentifier.html", "classQuantumIdentifier" ],
    [ "QuantumNumbers", "classQuantumNumbers.html", "classQuantumNumbers" ],
    [ "QuantumParserHITRAN2004", "classQuantumParserHITRAN2004.html", "classQuantumParserHITRAN2004" ],
    [ "RadiationVector", "classRadiationVector.html", "classRadiationVector" ],
    [ "Rand", "classRand.html", "classRand" ],
    [ "Rand< Index >", "classRand_3_01Index_01_4.html", "classRand_3_01Index_01_4" ],
    [ "Range", "classRange.html", "classRange" ],
    [ "Rational", "classRational.html", "classRational" ],
    [ "RetrievalQuantity", "classRetrievalQuantity.html", "classRetrievalQuantity" ],
    [ "Rng", "classRng.html", "classRng" ],
    [ "runtime_error_not_found", "classruntime__error__not__found.html", "classruntime__error__not__found" ],
    [ "runtime_error_not_unique", "classruntime__error__not__unique.html", "classruntime__error__not__unique" ],
    [ "s260a_1_", "structs260a__1__.html", "structs260a__1__" ],
    [ "s260b_1_", "structs260b__1__.html", "structs260b__1__" ],
    [ "s260b_2_", "structs260b__2__.html", "structs260b__2__" ],
    [ "s_app3a_", "structs__app3a__.html", "structs__app3a__" ],
    [ "s_app3b_", "structs__app3b__.html", "structs__app3b__" ],
    [ "s_bbb_", "structs__bbb__.html", "structs__bbb__" ],
    [ "s_bbc_", "structs__bbc__.html", "structs__bbc__" ],
    [ "s_bf_", "structs__bf__.html", "structs__bf__" ],
    [ "s_blockin_", "structs__blockin__.html", "structs__blockin__" ],
    [ "s_bou43_", "structs__bou43__.html", "structs__bou43__" ],
    [ "s_consts_", "structs__consts__.html", "structs__consts__" ],
    [ "s_dimer_", "structs__dimer__.html", "structs__dimer__" ],
    [ "s_energe_", "structs__energe__.html", "structs__energe__" ],
    [ "s_fh2oa_", "structs__fh2oa__.html", "structs__fh2oa__" ],
    [ "s_fh2ob_", "structs__fh2ob__.html", "structs__fh2ob__" ],
    [ "s_k1k0_", "structs__k1k0__.html", "structs__k1k0__" ],
    [ "s_like_", "structs__like__.html", "structs__like__" ],
    [ "s_n2part_", "structs__n2part__.html", "structs__n2part__" ],
    [ "s_rsilo_", "structs__rsilo__.html", "structs__rsilo__" ],
    [ "s_s260a_", "structs__s260a__.html", "structs__s260a__" ],
    [ "s_s260b_", "structs__s260b__.html", "structs__s260b__" ],
    [ "s_sh2oa_", "structs__sh2oa__.html", "structs__sh2oa__" ],
    [ "s_sh2ob_", "structs__sh2ob__.html", "structs__sh2ob__" ],
    [ "ScatteringMetaData", "structScatteringMetaData.html", "structScatteringMetaData" ],
    [ "sh2oa_1_", "structsh2oa__1__.html", "structsh2oa__1__" ],
    [ "sh2ob_1_", "structsh2ob__1__.html", "structsh2ob__1__" ],
    [ "sh2ob_2_", "structsh2ob__2__.html", "structsh2ob__2__" ],
    [ "SingleScatteringData", "structSingleScatteringData.html", "structSingleScatteringData" ],
    [ "SLIData2", "classSLIData2.html", "classSLIData2" ],
    [ "SourceText", "classSourceText.html", "classSourceText" ],
    [ "Sparse", "classSparse.html", "classSparse" ],
    [ "SpeciesAuxData", "classSpeciesAuxData.html", "classSpeciesAuxData" ],
    [ "SpeciesData", "structSpeciesData.html", "structSpeciesData" ],
    [ "SpeciesRecord", "classSpeciesRecord.html", "classSpeciesRecord" ],
    [ "SpeciesTag", "classSpeciesTag.html", "classSpeciesTag" ],
    [ "SpecIsoMap", "classSpecIsoMap.html", "classSpecIsoMap" ],
    [ "StokesVector", "classStokesVector.html", "classStokesVector" ],
    [ "TelsemAtlas", "classTelsemAtlas.html", "classTelsemAtlas" ],
    [ "Tensor3", "classTensor3.html", "classTensor3" ],
    [ "Tensor3View", "classTensor3View.html", "classTensor3View" ],
    [ "Tensor4", "classTensor4.html", "classTensor4" ],
    [ "Tensor4View", "classTensor4View.html", "classTensor4View" ],
    [ "Tensor5", "classTensor5.html", "classTensor5" ],
    [ "Tensor5View", "classTensor5View.html", "classTensor5View" ],
    [ "Tensor6", "classTensor6.html", "classTensor6" ],
    [ "Tensor6View", "classTensor6View.html", "classTensor6View" ],
    [ "Tensor7", "classTensor7.html", "classTensor7" ],
    [ "Tensor7View", "classTensor7View.html", "classTensor7View" ],
    [ "TessemNN", "structTessemNN.html", "structTessemNN" ],
    [ "Time", "classTime.html", "classTime" ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "Timings", "classTimings.html", "classTimings" ],
    [ "TokVal", "classTokVal.html", "classTokVal" ],
    [ "TransmissionMatrix", "classTransmissionMatrix.html", "classTransmissionMatrix" ],
    [ "u_bba_", "unionu__bba__.html", "unionu__bba__" ],
    [ "u_bbbb_", "unionu__bbbb__.html", "unionu__bbbb__" ],
    [ "u_bl3_", "unionu__bl3__.html", "unionu__bl3__" ],
    [ "UnexpectedChar", "classUnexpectedChar.html", "classUnexpectedChar" ],
    [ "UnknownMethod", "classUnknownMethod.html", "classUnknownMethod" ],
    [ "UnknownWsv", "classUnknownWsv.html", "classUnknownWsv" ],
    [ "Vardesc", "structVardesc.html", "structVardesc" ],
    [ "VariableStruct", "structVariableStruct.html", "structVariableStruct" ],
    [ "VariableValueStruct", "structVariableValueStruct.html", "structVariableValueStruct" ],
    [ "Vector", "classVector.html", "classVector" ],
    [ "VectorView", "classVectorView.html", "classVectorView" ],
    [ "Verbosity", "classVerbosity.html", "classVerbosity" ],
    [ "VersionStruct", "structVersionStruct.html", "structVersionStruct" ],
    [ "Workspace", "classWorkspace.html", "classWorkspace" ],
    [ "WorkspaceMemoryHandler", "classWorkspaceMemoryHandler.html", "classWorkspaceMemoryHandler" ],
    [ "WrongWsvGroup", "classWrongWsvGroup.html", "classWrongWsvGroup" ],
    [ "WsvAlreadyExists", "classWsvAlreadyExists.html", "classWsvAlreadyExists" ],
    [ "WsvRecord", "classWsvRecord.html", "classWsvRecord" ],
    [ "XMLAttribute", "classXMLAttribute.html", "classXMLAttribute" ],
    [ "XsecRecord", "classXsecRecord.html", "classXsecRecord" ]
];