ARTS: array.h File Reference
array.h File Reference
This file contains the definition of Array.
#include <climits>
#include <iomanip>
#include <iostream>
#include <array>
#include <vector>
#include "matpack.h"
Classes
class Array< base >
This can be used to make arrays out of anything.
class CmpArrayOfNumeric
Helper comparison class to sort an array or vector based on an ArrayOfNumeric.
Typedefs
typedef Array< Index > ArrayOfIndex
An array of Index.
typedef Array< ArrayOfIndex > ArrayOfArrayOfIndex
typedef Array< Numeric > ArrayOfNumeric
An array of Numeric.
typedef Array< Vector > ArrayOfVector
An array of vectors.
typedef Array< ArrayOfVector > ArrayOfArrayOfVector
typedef Array< Matrix > ArrayOfMatrix
An array of matrices.
typedef Array< ArrayOfMatrix > ArrayOfArrayOfMatrix
typedef Array< Sparse > ArrayOfSparse
An array of sparse matrices.
typedef Array< Tensor3 > ArrayOfTensor3
An array of Tensor3.
typedef Array< ArrayOfTensor3 > ArrayOfArrayOfTensor3
typedef Array< Tensor4 > ArrayOfTensor4
An array of Tensor4.
typedef Array< ArrayOfTensor4 > ArrayOfArrayOfTensor4
typedef Array< Tensor5 > ArrayOfTensor5
An array of Tensor5.
typedef Array< ArrayOfTensor5 > ArrayOfArrayOfTensor5
typedef Array< Tensor6 > ArrayOfTensor6
An array of Tensor6.
typedef Array< ArrayOfTensor6 > ArrayOfArrayOfTensor6
typedef Array< Tensor7 > ArrayOfTensor7
An array of Tensor7.
typedef Array< ArrayOfTensor7 > ArrayOfArrayOfTensor7
Functions
template<class base >
std::ostream & operator<< (std::ostream &os, const Array< base > &v)
Output operator.
template<class base >
base max (const Array< base > &x)
Max function.
template<class base >
base min (const Array< base > &x)
Min function.
template<class base >
Index find_first (const Array< base > &x, const base &w)
Find first occurance.
template<class base >
void find_all (ArrayOfIndex &pos, const Array< base > &x, const base &w)
Find all occurances.
template<class base >
Index TotalNumberOfElements (const Array< Array< base > > &aa)
Determine total number of elements in an ArrayOfArray.
template<class base >
Index FlattenedIndex (const Array< Array< base > > &aa, Index outer, Index inner=0)
Determine the index of an element in a flattened version of the array.
template<typename T , typename ... Ts>
constexpr std::array< T, 1+sizeof...(Ts)> stdarrayify (const T &first, const Ts &... the_rest)
Make a std::array of a list of variables (must be 1-long at least)
Detailed Description
This file contains the definition of Array.
Author
Stefan Buehler
Date
2001-09-05
Definition in file array.h.
Typedef Documentation
ArrayOfArrayOfIndex
typedef Array<ArrayOfIndex> ArrayOfArrayOfIndex
Definition at line 44 of file array.h.
ArrayOfArrayOfMatrix
typedef Array<ArrayOfMatrix> ArrayOfArrayOfMatrix
Definition at line 67 of file array.h.
ArrayOfArrayOfTensor3
typedef Array<ArrayOfTensor3> ArrayOfArrayOfTensor3
Definition at line 75 of file array.h.
ArrayOfArrayOfTensor4
typedef Array<ArrayOfTensor4> ArrayOfArrayOfTensor4
Definition at line 80 of file array.h.
ArrayOfArrayOfTensor5
typedef Array<ArrayOfTensor5> ArrayOfArrayOfTensor5
Definition at line 85 of file array.h.
ArrayOfArrayOfTensor6
typedef Array<ArrayOfTensor6> ArrayOfArrayOfTensor6
Definition at line 90 of file array.h.
ArrayOfArrayOfTensor7
typedef Array<ArrayOfTensor7> ArrayOfArrayOfTensor7
Definition at line 95 of file array.h.
ArrayOfArrayOfVector
typedef Array<ArrayOfVector> ArrayOfArrayOfVector
Definition at line 62 of file array.h.
ArrayOfIndex
typedef Array<Index> ArrayOfIndex
An array of Index.
Definition at line 42 of file array.h.
ArrayOfMatrix
typedef Array<Matrix> ArrayOfMatrix
An array of matrices.
Definition at line 65 of file array.h.
ArrayOfNumeric
typedef Array<Numeric> ArrayOfNumeric
An array of Numeric.
Definition at line 47 of file array.h.
ArrayOfSparse
typedef Array<Sparse> ArrayOfSparse
An array of sparse matrices.
Definition at line 70 of file array.h.
ArrayOfTensor3
typedef Array<Tensor3> ArrayOfTensor3
An array of Tensor3.
Definition at line 73 of file array.h.
ArrayOfTensor4
typedef Array<Tensor4> ArrayOfTensor4
An array of Tensor4.
Definition at line 78 of file array.h.
ArrayOfTensor5
typedef Array<Tensor5> ArrayOfTensor5
An array of Tensor5.
Definition at line 83 of file array.h.
ArrayOfTensor6
typedef Array<Tensor6> ArrayOfTensor6
An array of Tensor6.
Definition at line 88 of file array.h.
ArrayOfTensor7
typedef Array<Tensor7> ArrayOfTensor7
An array of Tensor7.
Definition at line 93 of file array.h.
ArrayOfVector
typedef Array<Vector> ArrayOfVector
An array of vectors.
Definition at line 60 of file array.h.
Function Documentation
find_all()
template<class base > void find_all (ArrayOfIndex & pos, const Array< base > & x, const base & w)
Find all occurances.
This calculates an array of indices of all occurances of w in array x.
An empty output array means that no occurance was found.
Return values
pos Array with positions of w in the array.
Parameters
x The array to search.
w The value to look for.
Author
Stefan Buehler
Date
2002-11-28
Definition at line 314 of file array.h.
References w(), and ARTS::Var::x().
Referenced by chk_contains().
find_first()
template<class base > Index find_first (const Array< base > & x, const base & w)
Find first occurance.
This returns the index of the first occurance of w in array x.
A return value of -1 indicates that no matching element was found.
Returns
The index of the thing we looked for.
Parameters
x The array to search.
w The value to look for.
Author
Stefan Buehler
Date
2002-11-28
Definition at line 292 of file array.h.
References w(), and ARTS::Var::x().
Referenced by get_pointers_for_scat_species(), particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), pnd_fieldCalcFromParticleBulkProps(), SpeciesTag::SpeciesTag(), SurfaceBlackbody(), SurfaceFastem(), SurfaceFlatScalarReflectivity(), SurfaceTessem(), and xml_read_from_stream().
FlattenedIndex()
template<class base > Index FlattenedIndex (const Array< Array< base > > & aa, Index outer, Index inner = 0)
Determine the index of an element in a flattened version of the array.
Definition at line 354 of file array.h.
References ARTS_ASSERT, N, and Array< base >::nelem().
Referenced by ScatSpeciesMerge().
max()
template<class base > base max (const Array< base > & x) inline
Max function.
Definition at line 247 of file array.h.
References ARTS::Var::x().
min()
template<class base > base min (const Array< base > & x) inline
Min function.
Definition at line 263 of file array.h.
References ARTS::Var::x().
operator<<()
template<class base > std::ostream& operator<< (std::ostream & os, const Array< base > & v) inline
Output operator.
Definition at line 229 of file array.h.
References Zeeman::end(), and v.
stdarrayify()
template<typename T , typename ... Ts> constexpr std::array<T, 1 + sizeof...(Ts)> stdarrayify (const T & first, const Ts &... the_rest) constexpr
Make a std::array of a list of variables (must be 1-long at least)
Definition at line 374 of file array.h.
Referenced by lm_hitran_2017::qt_co2(), lm_hitran_2017::read(), SpeciesTag::validIndexForType(), EnergyLevelMap::validIndexForType(), and MCAntenna::validType().
TotalNumberOfElements()
template<class base > Index TotalNumberOfElements (const Array< Array< base > > & aa)
Determine total number of elements in an ArrayOfArray.
Definition at line 343 of file array.h.
Referenced by cloudbox_checkedCalc(), DoitScatteringDataPrepare(), get_stepwise_scattersky_source(), iyRadarSingleScat(), opt_prop_NScatElems(), opt_prop_ScatSpecBulk(), opt_prop_sptFromData(), opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), particle_massesFromMetaData(), particle_massesFromMetaDataSingleCategory(), pha_mat_NScatElems(), pha_mat_ScatSpecBulk(), pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), pnd_fieldZero(), propmat_clearskyAddParticles(), Sample_los(), ScatElementsSelect(), and ybatchMetProfiles().