ARTS: arts_api_classes.cc File Reference
arts_api_classes.cc File Reference
This file contains all declarations of the ARTS C API class interface.
#include "arts_api_classes.h"
#include "absorption.h"
#include "absorptionlines.h"
#include "covariance_matrix.h"
#include "energylevelmap.h"
#include "global_data.h"
#include "lineshapemodel.h"
#include "quantum.h"
#include "supergeneric.h"
#include "xml_io.h"
#include "zeemandata.h"
Macros
#define BasicInterfaceCAPI(TYPE)
#define GetterSetterCAPI(TYPE, VALUE, BASETYPE)
#define EnumGetterSetterCAPI(TYPE, VALUE, ENUM)
#define StringEnumGetterSetterCAPI(TYPE, ELEM)
#define VoidGetterCAPI(TYPE, VALUE)
#define VoidStructGetterCAPI(TYPE, VALUE)
#define BasicInputOutputCAPI(TYPE)
#define VoidArrayCAPI(TYPE)
#define VoidArrayElemCAPI(TYPE, ELEM)
Functions
BasicInterfaceCAPI (Index) BasicInputOutputCAPI(Index) Index getIndex(void *data)
void setIndex (void *data, Index newval)
VoidArrayCAPI (ArrayOfIndex) BasicInterfaceCAPI(ArrayOfIndex) BasicInputOutputCAPI(ArrayOfIndex) VoidArrayCAPI(ArrayOfArrayOfIndex) BasicInterfaceCAPI(ArrayOfArrayOfIndex) BasicInputOutputCAPI(ArrayOfArrayOfIndex) BasicInterfaceCAPI(Numeric) BasicInputOutputCAPI(Numeric) VoidArrayCAPI(ArrayOfNumeric) BasicInterfaceCAPI(ArrayOfNumeric) Index xmlreadArrayOfNumeric(void *
char *Index xmlsaveArrayOfNumeric (void *, char *, Index, Index)
Numeric getNumeric (void *data)
void setNumeric (void *data, Numeric newval)
BasicInterfaceCAPI (ZeemanModel) GetterSetterCAPI(ZeemanModel
Numeric GetterSetterCAPI (ZeemanModel, gl, Numeric) BasicInterfaceCAPI(Rational) BasicInputOutputCAPI(Rational) GetterSetterCAPI(Rational
Numeric Index GetterSetterCAPI (Rational, Denom, Index) void simplifyRational(void *data)
BasicInterfaceCAPI (LineShapeTemperatureModel) void *getLineShapeTemperatureModelString(void *data)
int setLineShapeTemperatureModelString (void *data, char *val)
BasicInterfaceCAPI (LineShapeModelParameters) VoidStructGetterCAPI(LineShapeModelParameters
type VoidStructGetterCAPI (LineShapeModelParameters, X0) VoidStructGetterCAPI(LineShapeModelParameters
type X1 VoidStructGetterCAPI (LineShapeModelParameters, X2) VoidStructGetterCAPI(LineShapeModelParameters
type X1 X3 BasicInterfaceCAPI (LineShapeSingleSpeciesModel) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 VoidGetterCAPI (LineShapeSingleSpeciesModel, D0) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 VoidGetterCAPI (LineShapeSingleSpeciesModel, D2) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC VoidGetterCAPI (LineShapeSingleSpeciesModel, ETA) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC Y VoidGetterCAPI (LineShapeSingleSpeciesModel, G) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC Y DV BasicInterfaceCAPI (LineShapeType) void *getLineShapeTypeString(void *data)
int setLineShapeTypeString (void *data, char *val)
BasicInterfaceCAPI (LineShapeModel) VoidArrayCAPI(LineShapeModel) BasicInterfaceCAPI(AbsorptionSingleLine) GetterSetterCAPI(AbsorptionSingleLine
Numeric GetterSetterCAPI (AbsorptionSingleLine, I0, Numeric) GetterSetterCAPI(AbsorptionSingleLine
Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine, g_low, Numeric) GetterSetterCAPI(AbsorptionSingleLine
Numeric Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine, A, Numeric) VoidGetterCAPI(AbsorptionSingleLine
Numeric Numeric Numeric Zeeman VoidGetterCAPI (AbsorptionSingleLine, LineShape) VoidArrayElemCAPI(AbsorptionSingleLine
Numeric Numeric Numeric Zeeman LowerQuantumNumbers VoidArrayElemCAPI (AbsorptionSingleLine, UpperQuantumNumbers) BasicInterfaceCAPI(QuantumNumberType) void *getQuantumNumberTypeString(void *data)
int setQuantumNumberTypeString (void *data, char *val)
BasicInterfaceCAPI (QuantumNumbers) void *getelemQuantumNumbers(Index i
Index sizeQuantumNumbers ()
Index string2quantumnumbersindex (char *str)
void * getQuantumNumbersString (void *data)
void * createSpecies ()
void deleteSpecies (void *data)
void printSpecies (void *data)
int setSpeciesLongName (void *data, char *spec)
int setSpeciesShortName (void *data, char *spec)
void * getSpeciesLongName (void *data)
void * getSpeciesShortName (void *data)
VoidArrayCAPI (ArrayOfSpecies) Index xmlreadArrayOfSpecies(void *
char *Index xmlsaveArrayOfSpecies (void *, char *, Index, Index)
BasicInterfaceCAPI (ArrayOfSpecies) BasicInterfaceCAPI(SpeciesIsotopeRecord) Index getIndexSpeciesIsotopeRecordFromNames(char *spec
void * getIsotnameSpeciesIsotopeRecord (void *)
Index getIndexSpeciesIsotopeRecordFromData (void *data)
Index nelemSpeciesIsotopeRecordDefined ()
int setSpeciesIsotopeRecordToIndex (void *data, Index i)
void * getSpeciesSpeciesIsotopeRecord (void *data)
Numeric getMassSpeciesIsotopeRecord (void *data)
Index getGSpeciesIsotopeRecord (void *data)
BasicInterfaceCAPI (SpeciesIsotopologueRatios) BasicInputOutputCAPI(SpeciesIsotopologueRatios) Numeric *getdataSpeciesIsotopologueRatios(void *data)
BasicInterfaceCAPI (QuantumIdentifierType) void *getQuantumIdentifierTypeString(void *data)
int setQuantumIdentifierTypeString (void *data, char *val)
BasicInterfaceCAPI (QuantumIdentifier) BasicInputOutputCAPI(QuantumIdentifier) VoidStructGetterCAPI(QuantumIdentifier
type VoidStructGetterCAPI (QuantumIdentifier, spec_ind) VoidStructGetterCAPI(QuantumIdentifier
type upp VoidStructGetterCAPI (QuantumIdentifier, low) Index fromstringQuantumIdentifier(void *data
BasicInterfaceCAPI (ArrayOfQuantumIdentifier) BasicInputOutputCAPI(ArrayOfQuantumIdentifier) VoidArrayCAPI(ArrayOfQuantumIdentifier) BasicInterfaceCAPI(SpeciesTagType) void *getSpeciesTagTypeString(void *data)
int setSpeciesTagTypeString (void *data, char *val)
BasicInterfaceCAPI (SpeciesTag) BasicInputOutputCAPI(SpeciesTag) VoidStructGetterCAPI(SpeciesTag
spec_ind VoidStructGetterCAPI (SpeciesTag, lower_freq) VoidStructGetterCAPI(SpeciesTag
spec_ind upper_freq VoidStructGetterCAPI (SpeciesTag, type) VoidStructGetterCAPI(SpeciesTag
spec_ind upper_freq cia_2nd_species VoidStructGetterCAPI (SpeciesTag, cia_dataset_index) VoidArrayCAPI(ArrayOfSpeciesTag) BasicInterfaceCAPI(ArrayOfSpeciesTag) BasicInputOutputCAPI(ArrayOfSpeciesTag) VoidArrayCAPI(ArrayOfArrayOfSpeciesTag) BasicInterfaceCAPI(ArrayOfArrayOfSpeciesTag) BasicInputOutputCAPI(ArrayOfArrayOfSpeciesTag) void *getNameSpeciesTag(void *data)
Index setSpeciesTag (void *data, char *newdata)
BasicInterfaceCAPI (AbsorptionNormalizationType) void *getAbsorptionNormalizationTypeString(void *data)
int setAbsorptionNormalizationTypeString (void *data, char *val)
BasicInterfaceCAPI (AbsorptionPopulationType) void *getAbsorptionPopulationTypeString(void *data)
int setAbsorptionPopulationTypeString (void *data, char *val)
BasicInterfaceCAPI (AbsorptionMirroringType) void *getAbsorptionMirroringTypeString(void *data)
int setAbsorptionMirroringTypeString (void *data, char *val)
BasicInterfaceCAPI (AbsorptionCutoffType) void *getAbsorptionCutoffTypeString(void *data)
int setAbsorptionCutoffTypeString (void *data, char *val)
BasicInterfaceCAPI (AbsorptionLines) BasicInputOutputCAPI(AbsorptionLines) GetterSetterCAPI(AbsorptionLines
bool GetterSetterCAPI (AbsorptionLines, Bath, bool) VoidGetterCAPI(AbsorptionLines
bool Cutoff VoidGetterCAPI (AbsorptionLines, LineShapeType) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring VoidGetterCAPI (AbsorptionLines, Population) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization GetterSetterCAPI (AbsorptionLines, T0, Numeric) GetterSetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric GetterSetterCAPI (AbsorptionLines, LinemixingLimit, Numeric) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric QuantumIdentity VoidGetterCAPI (AbsorptionLines, BroadeningSpecies) VoidArrayElemCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric QuantumIdentity AllLines VoidArrayCAPI (ArrayOfAbsorptionLines) BasicInterfaceCAPI(ArrayOfAbsorptionLines) BasicInputOutputCAPI(ArrayOfAbsorptionLines) VoidArrayCAPI(ArrayOfArrayOfAbsorptionLines) BasicInterfaceCAPI(ArrayOfArrayOfAbsorptionLines) BasicInputOutputCAPI(ArrayOfArrayOfAbsorptionLines) Index sizeLocalQuantaAbsorptionLines(void *data)
void resizeLocalQuantaAbsorptionLines (Index n, void *data)
Index getLocalQuantaAbsorptionLines (Index i, void *data)
void setLocalQuantaAbsorptionLines (Index i, void *data, Index newval)
void printmetaAbsorptionLines (void *data)
Index isAbsorptionLinesOK (void *data)
void * getSpeciesNameAbsorptionLines (void *data)
BasicInterfaceCAPI (EnergyLevelMap) BasicInputOutputCAPI(EnergyLevelMap) EnumGetterSetterCAPI(EnergyLevelMap
EnergyLevelMapType VoidGetterCAPI (EnergyLevelMap, Levels) VoidGetterCAPI(EnergyLevelMap
EnergyLevelMapType Energies VoidGetterCAPI (EnergyLevelMap, Data) bool getOKEnergyLevelMap(void *data)
BasicInterfaceCAPI (Vector) BasicInputOutputCAPI(Vector) VoidArrayCAPI(ArrayOfVector) BasicInterfaceCAPI(ArrayOfVector) BasicInputOutputCAPI(ArrayOfVector) VoidArrayCAPI(ArrayOfArrayOfVector) BasicInterfaceCAPI(ArrayOfArrayOfVector) BasicInputOutputCAPI(ArrayOfArrayOfVector) void resizeVector(Index n
Index nelemVector (void *data)
Numeric * getDataVector (void *data)
BasicInterfaceCAPI (Matrix) BasicInputOutputCAPI(Matrix) VoidArrayCAPI(ArrayOfMatrix) BasicInterfaceCAPI(ArrayOfMatrix) BasicInputOutputCAPI(ArrayOfMatrix) VoidArrayCAPI(ArrayOfArrayOfMatrix) BasicInterfaceCAPI(ArrayOfArrayOfMatrix) BasicInputOutputCAPI(ArrayOfArrayOfMatrix) void resizeMatrix(Index nrows
Index rowsMatrix (void *data)
Index colsMatrix (void *data)
Numeric * getDataMatrix (void *data)
BasicInterfaceCAPI (Tensor3) BasicInputOutputCAPI(Tensor3) VoidArrayCAPI(ArrayOfTensor3) BasicInterfaceCAPI(ArrayOfTensor3) BasicInputOutputCAPI(ArrayOfTensor3) VoidArrayCAPI(ArrayOfArrayOfTensor3) BasicInterfaceCAPI(ArrayOfArrayOfTensor3) BasicInputOutputCAPI(ArrayOfArrayOfTensor3) void resizeTensor3(Index npages
Index pagesTensor3 (void *data)
Index rowsTensor3 (void *data)
Index colsTensor3 (void *data)
Numeric * getDataTensor3 (void *data)
BasicInterfaceCAPI (Tensor4) BasicInputOutputCAPI(Tensor4) VoidArrayCAPI(ArrayOfTensor4) BasicInterfaceCAPI(ArrayOfTensor4) BasicInputOutputCAPI(ArrayOfTensor4) void resizeTensor4(Index nbooks
Index booksTensor4 (void *data)
Index pagesTensor4 (void *data)
Index rowsTensor4 (void *data)
Index colsTensor4 (void *data)
Numeric * getDataTensor4 (void *data)
BasicInterfaceCAPI (Tensor5) BasicInputOutputCAPI(Tensor5) VoidArrayCAPI(ArrayOfTensor5) BasicInterfaceCAPI(ArrayOfTensor5) BasicInputOutputCAPI(ArrayOfTensor5) void resizeTensor5(Index nshelves
Index shelvesTensor5 (void *data)
Index booksTensor5 (void *data)
Index pagesTensor5 (void *data)
Index rowsTensor5 (void *data)
Index colsTensor5 (void *data)
Numeric * getDataTensor5 (void *data)
BasicInterfaceCAPI (Tensor6) BasicInputOutputCAPI(Tensor6) VoidArrayCAPI(ArrayOfTensor6) BasicInterfaceCAPI(ArrayOfTensor6) BasicInputOutputCAPI(ArrayOfTensor6) VoidArrayCAPI(ArrayOfArrayOfTensor6) BasicInterfaceCAPI(ArrayOfArrayOfTensor6) BasicInputOutputCAPI(ArrayOfArrayOfTensor6) void resizeTensor6(Index nvitrines
Index vitrinesTensor6 (void *data)
Index shelvesTensor6 (void *data)
Index booksTensor6 (void *data)
Index pagesTensor6 (void *data)
Index rowsTensor6 (void *data)
Index colsTensor6 (void *data)
Numeric * getDataTensor6 (void *data)
BasicInterfaceCAPI (Tensor7) BasicInputOutputCAPI(Tensor7) VoidArrayCAPI(ArrayOfTensor7) BasicInterfaceCAPI(ArrayOfTensor7) BasicInputOutputCAPI(ArrayOfTensor7) void resizeTensor7(Index nlibraries
Index librariesTensor7 (void *data)
Index vitrinesTensor7 (void *data)
Index shelvesTensor7 (void *data)
Index booksTensor7 (void *data)
Index pagesTensor7 (void *data)
Index rowsTensor7 (void *data)
Index colsTensor7 (void *data)
Numeric * getDataTensor7 (void *data)
BasicInterfaceCAPI (PropagationMatrix) BasicInputOutputCAPI(PropagationMatrix) VoidGetterCAPI(PropagationMatrix
Data VoidArrayCAPI (ArrayOfPropagationMatrix) BasicInterfaceCAPI(ArrayOfPropagationMatrix) BasicInputOutputCAPI(ArrayOfPropagationMatrix) VoidArrayCAPI(ArrayOfArrayOfPropagationMatrix) BasicInterfaceCAPI(ArrayOfArrayOfPropagationMatrix) BasicInputOutputCAPI(ArrayOfArrayOfPropagationMatrix) Index stokesPropagationMatrix(void *data)
Index frequenciesPropagationMatrix (void *data)
Index zenithsPropagationMatrix (void *data)
Index azimuthsPropagationMatrix (void *data)
Index setPropagationMatrix (void *data, Index f, Index s, Index z, Index a, Numeric v)
bool getOKPropagationMatrix (void *data)
BasicInterfaceCAPI (StokesVector) BasicInputOutputCAPI(StokesVector) VoidGetterCAPI(StokesVector
Data VoidArrayCAPI (ArrayOfStokesVector) BasicInterfaceCAPI(ArrayOfStokesVector) BasicInputOutputCAPI(ArrayOfStokesVector) VoidArrayCAPI(ArrayOfArrayOfStokesVector) BasicInterfaceCAPI(ArrayOfArrayOfStokesVector) BasicInputOutputCAPI(ArrayOfArrayOfStokesVector) Index stokesStokesVector(void *data)
Index frequenciesStokesVector (void *data)
Index zenithsStokesVector (void *data)
Index azimuthsStokesVector (void *data)
Index setStokesVector (void *data, Index f, Index s, Index z, Index a, Numeric v)
bool getOKStokesVector (void *data)
BasicInterfaceCAPI (String) BasicInputOutputCAPI(String) VoidArrayCAPI(ArrayOfString) BasicInterfaceCAPI(ArrayOfString) BasicInputOutputCAPI(ArrayOfString) VoidArrayCAPI(ArrayOfArrayOfString) BasicInterfaceCAPI(ArrayOfArrayOfString) BasicInputOutputCAPI(ArrayOfArrayOfString) void setString(void *data
char * getString (void *data)
BasicInterfaceCAPI (GridPos) BasicInputOutputCAPI(GridPos) VoidStructGetterCAPI(GridPos
idx VoidStructGetterCAPI (GridPos, fd) VoidArrayCAPI(ArrayOfGridPos) BasicInterfaceCAPI(ArrayOfGridPos) BasicInputOutputCAPI(ArrayOfGridPos) BasicInterfaceCAPI(LagrangeInterpolation) VoidStructGetterCAPI(LagrangeInterpolation
idx pos VoidStructGetterCAPI (LagrangeInterpolation, lx) VoidStructGetterCAPI(LagrangeInterpolation
idx pos dlx VoidArrayCAPI (ArrayOfLagrangeInterpolation) BasicInterfaceCAPI(ArrayOfLagrangeInterpolation) Index xmlreadArrayOfLagrangeInterpolation(void *
idx pos dlx char *Index xmlsaveArrayOfLagrangeInterpolation (void *, char *, Index, Index)
void * createPpath ()
void deletePpath (void *data)
void printPpath (void *)
BasicInputOutputCAPI (Ppath) VoidStructGetterCAPI(Ppath
dim VoidStructGetterCAPI (Ppath, np) VoidStructGetterCAPI(Ppath
dim constant VoidStructGetterCAPI (Ppath, background) VoidStructGetterCAPI(Ppath
dim constant start_pos VoidStructGetterCAPI (Ppath, start_los) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep VoidStructGetterCAPI (Ppath, pos) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los VoidStructGetterCAPI (Ppath, r) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los lstep VoidStructGetterCAPI (Ppath, end_pos) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los lstep end_los VoidStructGetterCAPI (Ppath, end_lstep) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los lstep end_los nreal VoidStructGetterCAPI (Ppath, ngroup) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los lstep end_los nreal gp_p VoidStructGetterCAPI (Ppath, gp_lat) VoidStructGetterCAPI(Ppath
dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon VoidArrayCAPI (ArrayOfPpath) void *createArrayOfPpath()
void deleteArrayOfPpath (void *data)
void printArrayOfPpath (void *)
BasicInputOutputCAPI (ArrayOfPpath) BasicInterfaceCAPI(TransmissionMatrix) BasicInputOutputCAPI(TransmissionMatrix) VoidArrayCAPI(ArrayOfTransmissionMatrix) BasicInterfaceCAPI(ArrayOfTransmissionMatrix) BasicInputOutputCAPI(ArrayOfTransmissionMatrix) VoidArrayCAPI(ArrayOfArrayOfTransmissionMatrix) BasicInterfaceCAPI(ArrayOfArrayOfTransmissionMatrix) BasicInputOutputCAPI(ArrayOfArrayOfTransmissionMatrix) Numeric *getMat1TransmissionMatrix(Index i
Numeric * getMat2TransmissionMatrix (Index i, void *data)
Numeric * getMat3TransmissionMatrix (Index i, void *data)
Numeric * getMat4TransmissionMatrix (Index i, void *data)
void setTransmissionMatrix (void *data, Index stokes, Index freqs)
Index getStokesDimTransmissionMatrix (void *data)
Index getFrequenciesTransmissionMatrix (void *data)
BasicInterfaceCAPI (RadiationVector) BasicInputOutputCAPI(RadiationVector) VoidArrayCAPI(ArrayOfRadiationVector) BasicInterfaceCAPI(ArrayOfRadiationVector) BasicInputOutputCAPI(ArrayOfRadiationVector) VoidArrayCAPI(ArrayOfArrayOfRadiationVector) BasicInterfaceCAPI(ArrayOfArrayOfRadiationVector) BasicInputOutputCAPI(ArrayOfArrayOfRadiationVector) Numeric *getVec1RadiationVector(Index i
Numeric * getVec2RadiationVector (Index i, void *data)
Numeric * getVec3RadiationVector (Index i, void *data)
Numeric * getVec4RadiationVector (Index i, void *data)
void setRadiationVector (void *data, Index stokes, Index freqs)
Index getStokesDimRadiationVector (void *data)
Index getFrequenciesRadiationVector (void *data)
BasicInterfaceCAPI (GriddedField1) BasicInputOutputCAPI(GriddedField1) VoidArrayCAPI(ArrayOfGriddedField1) BasicInterfaceCAPI(ArrayOfGriddedField1) BasicInputOutputCAPI(ArrayOfGriddedField1) VoidArrayCAPI(ArrayOfArrayOfGriddedField1) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField1) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField1) Index get_dimGriddedField1(void *data)
Index get_grid_typeIndexGriddedField1 (Index i, void *data)
Index get_grid_sizeGriddedField1 (Index i, void *data)
char * get_nameGriddedField1 (void *data)
void set_nameGriddedField1 (void *data, char *newdata)
char * get_grid_nameGriddedField1 (Index i, void *data)
void set_grid_nameGriddedField1 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField1 (Index i, void *data)
void * get_string_gridGriddedField1 (Index i, void *data)
void set_gridGriddedField1 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField1 (void *data)
bool checksizeGriddedField1 (void *data)
BasicInterfaceCAPI (GriddedField2) BasicInputOutputCAPI(GriddedField2) VoidArrayCAPI(ArrayOfGriddedField2) BasicInterfaceCAPI(ArrayOfGriddedField2) BasicInputOutputCAPI(ArrayOfGriddedField2) VoidArrayCAPI(ArrayOfArrayOfGriddedField2) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField2) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField2) Index get_dimGriddedField2(void *data)
Index get_grid_typeIndexGriddedField2 (Index i, void *data)
Index get_grid_sizeGriddedField2 (Index i, void *data)
char * get_nameGriddedField2 (void *data)
void set_nameGriddedField2 (void *data, char *newdata)
char * get_grid_nameGriddedField2 (Index i, void *data)
void set_grid_nameGriddedField2 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField2 (Index i, void *data)
void * get_string_gridGriddedField2 (Index i, void *data)
void set_gridGriddedField2 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField2 (void *data)
bool checksizeGriddedField2 (void *data)
BasicInterfaceCAPI (GriddedField3) BasicInputOutputCAPI(GriddedField3) VoidArrayCAPI(ArrayOfGriddedField3) BasicInterfaceCAPI(ArrayOfGriddedField3) BasicInputOutputCAPI(ArrayOfGriddedField3) VoidArrayCAPI(ArrayOfArrayOfGriddedField3) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField3) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField3) Index get_dimGriddedField3(void *data)
Index get_grid_typeIndexGriddedField3 (Index i, void *data)
Index get_grid_sizeGriddedField3 (Index i, void *data)
char * get_nameGriddedField3 (void *data)
void set_nameGriddedField3 (void *data, char *newdata)
char * get_grid_nameGriddedField3 (Index i, void *data)
void set_grid_nameGriddedField3 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField3 (Index i, void *data)
void * get_string_gridGriddedField3 (Index i, void *data)
void set_gridGriddedField3 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField3 (void *data)
bool checksizeGriddedField3 (void *data)
BasicInterfaceCAPI (GriddedField4) BasicInputOutputCAPI(GriddedField4) VoidArrayCAPI(ArrayOfGriddedField4) BasicInterfaceCAPI(ArrayOfGriddedField4) BasicInputOutputCAPI(ArrayOfGriddedField4) Index get_dimGriddedField4(void *data)
Index get_grid_typeIndexGriddedField4 (Index i, void *data)
Index get_grid_sizeGriddedField4 (Index i, void *data)
char * get_nameGriddedField4 (void *data)
void set_nameGriddedField4 (void *data, char *newdata)
char * get_grid_nameGriddedField4 (Index i, void *data)
void set_grid_nameGriddedField4 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField4 (Index i, void *data)
void * get_string_gridGriddedField4 (Index i, void *data)
void set_gridGriddedField4 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField4 (void *data)
bool checksizeGriddedField4 (void *data)
BasicInterfaceCAPI (GriddedField5) BasicInputOutputCAPI(GriddedField5) Index get_dimGriddedField5(void *data)
Index get_grid_typeIndexGriddedField5 (Index i, void *data)
Index get_grid_sizeGriddedField5 (Index i, void *data)
char * get_nameGriddedField5 (void *data)
void set_nameGriddedField5 (void *data, char *newdata)
char * get_grid_nameGriddedField5 (Index i, void *data)
void set_grid_nameGriddedField5 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField5 (Index i, void *data)
void * get_string_gridGriddedField5 (Index i, void *data)
void set_gridGriddedField5 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField5 (void *data)
bool checksizeGriddedField5 (void *data)
BasicInterfaceCAPI (GriddedField6) BasicInputOutputCAPI(GriddedField6) Index get_dimGriddedField6(void *data)
Index get_grid_typeIndexGriddedField6 (Index i, void *data)
Index get_grid_sizeGriddedField6 (Index i, void *data)
char * get_nameGriddedField6 (void *data)
void set_nameGriddedField6 (void *data, char *newdata)
char * get_grid_nameGriddedField6 (Index i, void *data)
void set_grid_nameGriddedField6 (Index i, void *data, char *newdata)
void * get_numeric_gridGriddedField6 (Index i, void *data)
void * get_string_gridGriddedField6 (Index i, void *data)
void set_gridGriddedField6 (Index i, void *data, void *newdata, bool NumericType)
void * dataGriddedField6 (void *data)
bool checksizeGriddedField6 (void *data)
BasicInterfaceCAPI (CIARecord) BasicInputOutputCAPI(CIARecord) VoidGetterCAPI(CIARecord
Data void * getSpecies1CIARecord (void *data)
void * getSpecies2CIARecord (void *data)
void setSpeciesCIARecord (void *data, void *s1, void *s2)
VoidArrayCAPI (ArrayOfCIARecord) BasicInterfaceCAPI(ArrayOfCIARecord) BasicInputOutputCAPI(ArrayOfCIARecord) BasicInterfaceCAPI(Verbosity) BasicInputOutputCAPI(Verbosity) Index getAgendaVerbosity(void *data)
Index getScreenVerbosity (void *data)
Index getFileVerbosity (void *data)
bool getMainVerbosity (void *data)
void setVerbosity (void *data, Index a, Index s, Index f, bool m)
void * createTessemNN ()
void deleteTessemNN (void *data)
void printTessemNN (void *)
BasicInputOutputCAPI (TessemNN) VoidStructGetterCAPI(TessemNN
nb_inputs VoidStructGetterCAPI (TessemNN, nb_outputs) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache VoidStructGetterCAPI (TessemNN, b1) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 VoidStructGetterCAPI (TessemNN, w1) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 VoidStructGetterCAPI (TessemNN, x_min) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 x_max VoidStructGetterCAPI (TessemNN, y_min) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 x_max y_max BasicInterfaceCAPI (SingleScatteringData) BasicInputOutputCAPI(SingleScatteringData) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype VoidStructGetterCAPI (SingleScatteringData, description) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid VoidStructGetterCAPI (SingleScatteringData, T_grid) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid VoidStructGetterCAPI (SingleScatteringData, aa_grid) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data VoidStructGetterCAPI (SingleScatteringData, ext_mat_data) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data VoidArrayCAPI (ArrayOfSingleScatteringData) BasicInterfaceCAPI(ArrayOfSingleScatteringData) BasicInputOutputCAPI(ArrayOfSingleScatteringData) VoidArrayCAPI(ArrayOfArrayOfSingleScatteringData) BasicInterfaceCAPI(ArrayOfArrayOfSingleScatteringData) BasicInputOutputCAPI(ArrayOfArrayOfSingleScatteringData) BasicInterfaceCAPI(ScatteringMetaData) BasicInputOutputCAPI(ScatteringMetaData) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description VoidStructGetterCAPI (ScatteringMetaData, source) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index VoidStructGetterCAPI (ScatteringMetaData, mass) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max VoidStructGetterCAPI (ScatteringMetaData, diameter_volume_equ) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max diameter_area_equ_aerodynamical VoidArrayCAPI (ArrayOfScatteringMetaData) BasicInterfaceCAPI(ArrayOfScatteringMetaData) BasicInputOutputCAPI(ArrayOfScatteringMetaData) VoidArrayCAPI(ArrayOfArrayOfScatteringMetaData) BasicInterfaceCAPI(ArrayOfArrayOfScatteringMetaData) BasicInputOutputCAPI(ArrayOfArrayOfScatteringMetaData) void *createTimer()
void deleteTimer (void *data)
void printTimer (void *)
BasicInputOutputCAPI (Timer) bool getrunningTimer(void *data)
bool getfinishedTimer (void *data)
Index getcputime_start_utimeTimer (void *data)
Index getcputime_start_stimeTimer (void *data)
Index getcputime_start_cutimeTimer (void *data)
Index getcputime_start_cstimeTimer (void *data)
Index getrealtime_startTimer (void *data)
Index getcputime_end_utimeTimer (void *data)
Index getcputime_end_stimeTimer (void *data)
Index getcputime_end_cutimeTimer (void *data)
Index getcputime_end_cstimeTimer (void *data)
Index getrealtime_endTimer (void *data)
void setrunningTimer (void *data, bool newdata)
void setfinishedTimer (void *data, bool newdata)
void setcputime_start_utimeTimer (void *data, Index newdata)
void setcputime_start_stimeTimer (void *data, Index newdata)
void setcputime_start_cutimeTimer (void *data, Index newdata)
void setcputime_start_cstimeTimer (void *data, Index newdata)
void setrealtime_startTimer (void *data, Index newdata)
void setcputime_end_utimeTimer (void *data, Index newdata)
void setcputime_end_stimeTimer (void *data, Index newdata)
void setcputime_end_cutimeTimer (void *data, Index newdata)
void setcputime_end_cstimeTimer (void *data, Index newdata)
void setrealtime_endTimer (void *data, Index newdata)
bool supportTimer ()
Index tickTimer ()
BasicInterfaceCAPI (TelsemAtlas) BasicInputOutputCAPI(TelsemAtlas) VoidGetterCAPI(TelsemAtlas
DataCount VoidGetterCAPI (TelsemAtlas, ChannelCount) VoidGetterCAPI(TelsemAtlas
DataCount Name VoidGetterCAPI (TelsemAtlas, Month) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat VoidGetterCAPI (TelsemAtlas, Cells) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells VoidGetterCAPI (TelsemAtlas, Emis) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err VoidGetterCAPI (TelsemAtlas, Correlations) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err Classes1 VoidGetterCAPI (TelsemAtlas, Classes2) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber VoidGetterCAPI (TelsemAtlas, Correspondance) VoidArrayCAPI(ArrayOfTelsemAtlas) BasicInterfaceCAPI(ArrayOfTelsemAtlas) BasicInputOutputCAPI(ArrayOfTelsemAtlas) Numeric getA0_K0TelsemAtlas(Index i
Numeric getA0_K1TelsemAtlas (Index i, void *data)
Numeric getA0_K2TelsemAtlas (Index i, void *data)
Numeric getA0_EVEHTelsemAtlas (Index i, void *data)
Numeric getA1_EVEHTelsemAtlas (Index i, void *data)
Numeric getA2_EVEHTelsemAtlas (Index i, void *data)
Numeric getA3_EVEHTelsemAtlas (Index i, void *data)
Numeric getB0_EVEHTelsemAtlas (Index i, void *data)
Numeric getB1_EVEHTelsemAtlas (Index i, void *data)
Numeric getB2_EVEHTelsemAtlas (Index i, void *data)
Numeric getB3_EVEHTelsemAtlas (Index i, void *data)
Numeric getRAPPORT43_32TelsemAtlas (Index i, void *data)
Numeric getRAPPORT54_43TelsemAtlas (Index i, void *data)
BasicInterfaceCAPI (MCAntenna) BasicInputOutputCAPI(MCAntenna) VoidGetterCAPI(MCAntenna
saa VoidGetterCAPI (MCAntenna, sza) VoidGetterCAPI(MCAntenna
saa aag VoidGetterCAPI (MCAntenna, zag) VoidGetterCAPI(MCAntenna
saa aag G Index getTypeMCAntenna (void *data)
Index setTypeMCAntenna (void *data, Index newval)
BasicInterfaceCAPI (GasAbsLookup) BasicInputOutputCAPI(GasAbsLookup) VoidGetterCAPI(GasAbsLookup
Species VoidGetterCAPI (GasAbsLookup, NonLinearSpecies) VoidGetterCAPI(GasAbsLookup
Species Fgrid VoidGetterCAPI (GasAbsLookup, FLAGDefault) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VoidGetterCAPI (GasAbsLookup, LogPgrid) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs VoidGetterCAPI (GasAbsLookup, Tref) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs Tpert VoidGetterCAPI (GasAbsLookup, NLSPert) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs Tpert Xsec BasicInterfaceCAPI (XsecRecord) BasicInputOutputCAPI(XsecRecord) void *getSpeciesXsecRecord(void *data)
void setSpeciesXsecRecord (void *data, void *val)
VoidGetterCAPI (XsecRecord, Coeffs) VoidGetterCAPI(XsecRecord
RefPressure VoidGetterCAPI (XsecRecord, RefTemperature) VoidGetterCAPI(XsecRecord
RefPressure Fgrids VoidGetterCAPI (XsecRecord, Xsecs) VoidGetterCAPI(XsecRecord
RefPressure Fgrids TemperatureSlope VoidGetterCAPI (XsecRecord, TemperatureIntersect) VoidArrayCAPI(ArrayOfXsecRecord) BasicInterfaceCAPI(ArrayOfXsecRecord) BasicInputOutputCAPI(ArrayOfXsecRecord) BasicInterfaceCAPI(Sparse) BasicInputOutputCAPI(Sparse) VoidArrayCAPI(ArrayOfSparse) BasicInterfaceCAPI(ArrayOfSparse) BasicInputOutputCAPI(ArrayOfSparse) void resizeSparse(Index nrows
Index rowsSparse (void *data)
Index colsSparse (void *data)
Index sizeSparse (void *data)
int * rowsptrSparse (void *data)
int * colsptrSparse (void *data)
Numeric * getDataSparse (void *data)
void setDataSparse (void *data, Index r, Index c, Numeric v)
BasicInterfaceCAPI (CovarianceMatrix) BasicInputOutputCAPI(CovarianceMatrix) Index sizeget_blocksCovarianceMatrix(void *data)
void resizeget_blocksCovarianceMatrix (Index n, void *data)
void * getelemget_blocksCovarianceMatrix (Index i, void *data)
Index sizeget_inverse_blocksCovarianceMatrix (void *data)
void resizeget_inverse_blocksCovarianceMatrix (Index n, void *data)
void * getelemget_inverse_blocksCovarianceMatrix (Index i, void *data)
void * createAny ()
void deleteAny (void *data)
void printAny (void *)
Index xmlreadAny (void *, char *)
Index xmlsaveAny (void *, char *, Index, Index)
BasicInterfaceCAPI (Agenda) BasicInputOutputCAPI(Agenda) VoidArrayCAPI(ArrayOfAgenda) BasicInterfaceCAPI(ArrayOfAgenda) BasicInputOutputCAPI(ArrayOfAgenda) BasicInterfaceCAPI(JacobianTarget) BasicInputOutputCAPI(JacobianTarget) VoidGetterCAPI(JacobianTarget
Perturbation VoidGetterCAPI (JacobianTarget, QuantumIdentity) VoidGetterCAPI(JacobianTarget
Perturbation StringKey VoidGetterCAPI (JacobianTarget, SpeciesList) StringEnumGetterSetterCAPI(JacobianTarget
Perturbation StringKey TargetType StringEnumGetterSetterCAPI (JacobianTarget, TargetSubType) VoidArrayCAPI(ArrayOfJacobianTarget) BasicInterfaceCAPI(ArrayOfJacobianTarget) BasicInputOutputCAPI(ArrayOfJacobianTarget) BasicInterfaceCAPI(RetrievalQuantity) BasicInputOutputCAPI(RetrievalQuantity) VoidGetterCAPI(RetrievalQuantity
Perturbation StringKey TargetType SubTag VoidGetterCAPI (RetrievalQuantity, SubSubTag) VoidGetterCAPI(RetrievalQuantity
Perturbation StringKey TargetType SubTag Mode VoidGetterCAPI (RetrievalQuantity, Grids) VoidGetterCAPI(RetrievalQuantity
Perturbation StringKey TargetType SubTag Mode Target VoidGetterCAPI (RetrievalQuantity, TransformationFunc) VoidGetterCAPI(RetrievalQuantity
Perturbation StringKey TargetType SubTag Mode Target TFuncParameters VoidGetterCAPI (RetrievalQuantity, Transformation) VoidGetterCAPI(RetrievalQuantity
Perturbation StringKey TargetType SubTag Mode Target TFuncParameters Offset VoidArrayCAPI (ArrayOfRetrievalQuantity) BasicInterfaceCAPI(ArrayOfRetrievalQuantity) BasicInputOutputCAPI(ArrayOfRetrievalQuantity) void *createRange()
void deleteRange (void *data)
void printRange (void *data)
Index get_startRange (void *data)
Index get_strideRange (void *data)
Index get_extentRange (void *data)
void setRange (void *data, Index start, Index extent, Index stride)
void * createBlock ()
void deleteBlock (void *data)
void printBlock (void *)
VoidGetterCAPI (Block, get_row_range) VoidGetterCAPI(Block
get_column_range VoidGetterCAPI (Block, get_dense) VoidGetterCAPI(Block
get_column_range get_sparse Index get_matrix_typeBlock (void *data)
Index get_index1Block (void *data)
Index get_index2Block (void *data)
void set_indicesBlock (void *data, Index i1, Index i2)
void set_matrixBlock (void *data, void *newdata, bool dense)
BasicInterfaceCAPI (Time) BasicInputOutputCAPI(Time) GetterSetterCAPI(Time
Numeric VoidArrayCAPI (ArrayOfTime) BasicInterfaceCAPI(ArrayOfTime) BasicInputOutputCAPI(ArrayOfTime) VoidArrayCAPI(ArrayOfArrayOfTime) BasicInterfaceCAPI(ArrayOfArrayOfTime) BasicInputOutputCAPI(ArrayOfArrayOfTime) Index setTimeFromString(void *data
Variables
gu
Numeric Nom
F0
Numeric E0
Numeric Numeric g_upp
void * data { return &static_cast<QuantumNumbers *>(data)->operator[](i)
char * isot
type upp char * str
Self
bool Cutoff Mirroring Normalization CutoffFreqValue
Type
Index ncols
Index nrows
Index npages
Index nbooks
Index nshelves
Index nvitrines
char * newdata {static_cast<String *>(data) -> operator=(String(newdata))
Seconds
Detailed Description
This file contains all declarations of the ARTS C API class interface.
Author
Richard Larsson larss.nosp@m.on@m.nosp@m.ps.mp.nosp@m.g.de
Date
2020-03-12
Definition in file arts_api_classes.cc.
Macro Definition Documentation
BasicInputOutputCAPI
#define BasicInputOutputCAPI (TYPE)
Value:
Index xmlread##TYPE(void * data, char * filepath)                                                                       \
{                                                                                                                       \
    try {                                                                                                               \
        xml_read_from_file(filepath, *static_cast<TYPE *>(data), Verbosity());                                          \
        return EXIT_SUCCESS;                                                                                            \
    } catch (std::runtime_error& e) {                                                                                   \
        return EXIT_FAILURE;                                                                                            \
    }                                                                                                                   \
}                                                                                                                       \
                                                                                                                        \
Index xmlsave##TYPE(void * data, char * filepath, Index filetype, Index clobber)                                        \
{                                                                                                                       \
    try {                                                                                                               \
        xml_write_to_file(filepath, *static_cast<const TYPE *>(data), FileType(filetype), not clobber, Verbosity());    \
        return EXIT_SUCCESS;                                                                                            \
    } catch (std::runtime_error& e) {                                                                                   \
        return EXIT_FAILURE;                                                                                            \
    }                                                                                                                   \
}
Definition at line 120 of file arts_api_classes.cc.
BasicInterfaceCAPI
#define BasicInterfaceCAPI (TYPE)
Value:
void * create##TYPE()                                       \
{                                                           \
    return new TYPE;                                        \
}                                                           \
                                                            \
void delete##TYPE(void * data)                              \
{                                                           \
    delete static_cast<TYPE *>(data);                       \
}                                                           \
                                                            \
void print##TYPE(void * data)                               \
{                                                           \
  std::cout << (*static_cast<TYPE *>(data)) << std::endl;   \
}
Definition at line 46 of file arts_api_classes.cc.
EnumGetterSetterCAPI
#define EnumGetterSetterCAPI (TYPE, VALUE, ENUM)
Value:
Index get##VALUE##TYPE(void * data)                                   \
{                                                                     \
  return Index(static_cast<TYPE *>(data) -> VALUE ());                \
}                                                                     \
Index set##VALUE##TYPE(void * data, Index newval)                     \
{                                                                     \
  if (static_cast<TYPE *>(data) -> validIndexFor##VALUE (newval)) {   \
    static_cast<TYPE *>(data) -> VALUE (ENUM(newval));                \
    return EXIT_SUCCESS;                                              \
  } else {                                                            \
    return EXIT_FAILURE;                                              \
  }                                                                   \
}                                                                     \
Index string2index##VALUE##TYPE(void * data, char * newval)           \
{                                                                     \
  return Index(static_cast<TYPE *>(data) -> string2##VALUE(newval));  \
}
Definition at line 74 of file arts_api_classes.cc.
GetterSetterCAPI
#define GetterSetterCAPI (TYPE, VALUE, BASETYPE)
Value:
BASETYPE get##VALUE##TYPE(void * data)              \
{                                                   \
    return static_cast<TYPE *>(data) -> VALUE ();   \
}                                                   \
void set##VALUE##TYPE(void * data, BASETYPE newval) \
{                                                   \
    static_cast<TYPE *>(data) -> VALUE (newval);    \
}
Definition at line 63 of file arts_api_classes.cc.
StringEnumGetterSetterCAPI
#define StringEnumGetterSetterCAPI (TYPE, ELEM)
Value:
bool enumset ## ELEM ## TYPE (void * data, char * in) { \
  auto x = static_cast<TYPE *>(data);                   \
  x -> ELEM(in);                                        \
  return not x -> ELEM ## OK();                         \
}                                                       \
void * enumget ## ELEM ## TYPE (void * data) {          \
  auto x = static_cast<TYPE *>(data);                   \
  String * out = new String(x -> ELEM());               \
  return out;                                           \
}
Definition at line 94 of file arts_api_classes.cc.
VoidArrayCAPI
#define VoidArrayCAPI (TYPE)
Value:
Index size##TYPE(void * data)                         \
{                                                     \
  return static_cast<TYPE *>(data) -> size();         \
}                                                     \
void resize##TYPE(Index n, void * data)               \
{                                                     \
  static_cast<TYPE *>(data) -> resize(n);             \
}                                                     \
void * getelem##TYPE(Index i, void * data)            \
{                                                     \
  return &static_cast<TYPE *>(data) -> operator[](i); \
}
Definition at line 142 of file arts_api_classes.cc.
VoidArrayElemCAPI
#define VoidArrayElemCAPI (TYPE, ELEM)
Value:
Index size##ELEM##TYPE(void * data)                     \
{                                                       \
  return static_cast<TYPE *>(data) -> ELEM().size();    \
}                                                       \
void resize##ELEM##TYPE(Index n, void * data)           \
{                                                       \
  static_cast<TYPE *>(data) -> ELEM().resize(n);        \
}                                                       \
void * getelem##ELEM##TYPE(Index i, void * data)        \
{                                                       \
  return &static_cast<TYPE *>(data) -> ELEM()[i];       \
}
Definition at line 157 of file arts_api_classes.cc.
VoidGetterCAPI
#define VoidGetterCAPI (TYPE, VALUE)
Value:
void * get##VALUE##TYPE(void * data)                \
{                                                   \
    return &static_cast<TYPE *>(data) -> VALUE();   \
}
Definition at line 107 of file arts_api_classes.cc.
VoidStructGetterCAPI
#define VoidStructGetterCAPI (TYPE, VALUE)
Value:
void * get##VALUE##TYPE(void * data)          \
{                                             \
  return &static_cast<TYPE *>(data) -> VALUE; \
}
Definition at line 113 of file arts_api_classes.cc.
Function Documentation
azimuthsPropagationMatrix()
Index azimuthsPropagationMatrix (void * data)
Definition at line 701 of file arts_api_classes.cc.
References data.
azimuthsStokesVector()
Index azimuthsStokesVector (void * data)
Definition at line 727 of file arts_api_classes.cc.
References data.
BasicInputOutputCAPI() [1/4]
BasicInputOutputCAPI (ArrayOfPpath)
References data.
BasicInputOutputCAPI() [2/4]
BasicInputOutputCAPI (Ppath)
BasicInputOutputCAPI() [3/4]
BasicInputOutputCAPI (TessemNN)
BasicInputOutputCAPI() [4/4]
BasicInputOutputCAPI (Timer)
Definition at line 1097 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [1/47]
BasicInterfaceCAPI (AbsorptionCutoffType)
Definition at line 512 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [2/47]
BasicInterfaceCAPI (AbsorptionLines)
BasicInterfaceCAPI() [3/47]
BasicInterfaceCAPI (AbsorptionMirroringType)
Definition at line 496 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [4/47]
BasicInterfaceCAPI (AbsorptionNormalizationType)
Definition at line 464 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [5/47]
BasicInterfaceCAPI (AbsorptionPopulationType)
Definition at line 480 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [6/47]
BasicInterfaceCAPI (Agenda)
BasicInterfaceCAPI() [7/47]
BasicInterfaceCAPI (ArrayOfQuantumIdentifier)
Definition at line 412 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [8/47]
BasicInterfaceCAPI (ArrayOfSpecies)
BasicInterfaceCAPI() [9/47]
BasicInterfaceCAPI (CIARecord)
BasicInterfaceCAPI() [10/47]
BasicInterfaceCAPI (CovarianceMatrix)
Definition at line 1361 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [11/47]
BasicInterfaceCAPI (EnergyLevelMap)
BasicInterfaceCAPI() [12/47]
BasicInterfaceCAPI (GasAbsLookup)
BasicInterfaceCAPI() [13/47]
BasicInterfaceCAPI (GriddedField1)
Definition at line 843 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [14/47]
BasicInterfaceCAPI (GriddedField2)
Definition at line 872 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [15/47]
BasicInterfaceCAPI (GriddedField3)
Definition at line 901 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [16/47]
BasicInterfaceCAPI (GriddedField4)
Definition at line 930 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [17/47]
BasicInterfaceCAPI (GriddedField5)
Definition at line 956 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [18/47]
BasicInterfaceCAPI (GriddedField6)
Definition at line 979 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [19/47]
BasicInterfaceCAPI (GridPos)
BasicInterfaceCAPI() [20/47]
BasicInterfaceCAPI (Index)
Definition at line 173 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [21/47]
BasicInterfaceCAPI (LineShapeModel)
BasicInterfaceCAPI() [22/47]
BasicInterfaceCAPI (LineShapeModelParameters)
BasicInterfaceCAPI() [23/47]
type X1 X3 BasicInterfaceCAPI (LineShapeSingleSpeciesModel)
BasicInterfaceCAPI() [24/47]
BasicInterfaceCAPI (LineShapeTemperatureModel)
Definition at line 210 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [25/47]
type X1 X3 G0 G2 FVC Y DV BasicInterfaceCAPI (LineShapeType)
Definition at line 248 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [26/47]
BasicInterfaceCAPI (Matrix)
BasicInterfaceCAPI() [27/47]
BasicInterfaceCAPI (MCAntenna)
BasicInterfaceCAPI() [28/47]
BasicInterfaceCAPI (PropagationMatrix)
BasicInterfaceCAPI() [29/47]
BasicInterfaceCAPI (QuantumIdentifier)
BasicInterfaceCAPI() [30/47]
BasicInterfaceCAPI (QuantumIdentifierType)
Definition at line 381 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [31/47]
BasicInterfaceCAPI (QuantumNumbers)
BasicInterfaceCAPI() [32/47]
BasicInterfaceCAPI (RadiationVector)
References data.
BasicInterfaceCAPI() [33/47]
nb_inputs nb_cache b2 w2 x_max y_max BasicInterfaceCAPI (SingleScatteringData)
BasicInterfaceCAPI() [34/47]
BasicInterfaceCAPI (SpeciesIsotopologueRatios)
Definition at line 376 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [35/47]
BasicInterfaceCAPI (SpeciesTag)
BasicInterfaceCAPI() [36/47]
BasicInterfaceCAPI (StokesVector)
BasicInterfaceCAPI() [37/47]
BasicInterfaceCAPI (String)
BasicInterfaceCAPI() [38/47]
BasicInterfaceCAPI (TelsemAtlas)
BasicInterfaceCAPI() [39/47]
BasicInterfaceCAPI (Tensor3)
BasicInterfaceCAPI() [40/47]
BasicInterfaceCAPI (Tensor4)
BasicInterfaceCAPI() [41/47]
BasicInterfaceCAPI (Tensor5)
BasicInterfaceCAPI() [42/47]
BasicInterfaceCAPI (Tensor6)
BasicInterfaceCAPI() [43/47]
BasicInterfaceCAPI (Tensor7)
BasicInterfaceCAPI() [44/47]
BasicInterfaceCAPI (Time)
BasicInterfaceCAPI() [45/47]
BasicInterfaceCAPI (Vector)
References data.
BasicInterfaceCAPI() [46/47]
Species Fgrid Pgrid VMRs Tpert Xsec BasicInterfaceCAPI (XsecRecord)
Definition at line 1324 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [47/47]
BasicInterfaceCAPI (ZeemanModel)
booksTensor4()
Index booksTensor4 (void * data)
Definition at line 624 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor5()
Index booksTensor5 (void * data)
Definition at line 642 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor6()
Index booksTensor6 (void * data)
Definition at line 661 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor7()
Index booksTensor7 (void * data)
Definition at line 681 of file arts_api_classes.cc.
References data, and nbooks.
checksizeGriddedField1()
bool checksizeGriddedField1 (void * data)
Definition at line 868 of file arts_api_classes.cc.
References data.
checksizeGriddedField2()
bool checksizeGriddedField2 (void * data)
Definition at line 897 of file arts_api_classes.cc.
References data.
checksizeGriddedField3()
bool checksizeGriddedField3 (void * data)
Definition at line 926 of file arts_api_classes.cc.
References data.
checksizeGriddedField4()
bool checksizeGriddedField4 (void * data)
Definition at line 952 of file arts_api_classes.cc.
References data.
checksizeGriddedField5()
bool checksizeGriddedField5 (void * data)
Definition at line 975 of file arts_api_classes.cc.
References data.
checksizeGriddedField6()
bool checksizeGriddedField6 (void * data)
Definition at line 998 of file arts_api_classes.cc.
References data.
colsMatrix()
Index colsMatrix (void * data)
Definition at line 594 of file arts_api_classes.cc.
References data, and ncols.
colsptrSparse()
int* colsptrSparse (void * data)
Definition at line 1355 of file arts_api_classes.cc.
References data.
colsSparse()
Index colsSparse (void * data)
Definition at line 1352 of file arts_api_classes.cc.
References data, and ncols.
colsTensor3()
Index colsTensor3 (void * data)
Definition at line 610 of file arts_api_classes.cc.
References data, and ncols.
colsTensor4()
Index colsTensor4 (void * data)
Definition at line 627 of file arts_api_classes.cc.
References data, and ncols.
colsTensor5()
Index colsTensor5 (void * data)
Definition at line 645 of file arts_api_classes.cc.
References data, and ncols.
colsTensor6()
Index colsTensor6 (void * data)
Definition at line 664 of file arts_api_classes.cc.
References data, and ncols.
colsTensor7()
Index colsTensor7 (void * data)
Definition at line 684 of file arts_api_classes.cc.
References data, and ncols.
createAny()
void* createAny ()
Definition at line 1372 of file arts_api_classes.cc.
createBlock()
void* createBlock ()
Definition at line 1435 of file arts_api_classes.cc.
References joker.
createPpath()
void* createPpath ()
Definition at line 776 of file arts_api_classes.cc.
createSpecies()
void* createSpecies ()
Definition at line 303 of file arts_api_classes.cc.
createTessemNN()
void* createTessemNN ()
Definition at line 1038 of file arts_api_classes.cc.
dataGriddedField1()
void* dataGriddedField1 (void * data)
Definition at line 867 of file arts_api_classes.cc.
References data.
dataGriddedField2()
void* dataGriddedField2 (void * data)
Definition at line 896 of file arts_api_classes.cc.
References data.
dataGriddedField3()
void* dataGriddedField3 (void * data)
Definition at line 925 of file arts_api_classes.cc.
References data.
dataGriddedField4()
void* dataGriddedField4 (void * data)
Definition at line 951 of file arts_api_classes.cc.
References data.
dataGriddedField5()
void* dataGriddedField5 (void * data)
Definition at line 974 of file arts_api_classes.cc.
References data.
dataGriddedField6()
void* dataGriddedField6 (void * data)
Definition at line 997 of file arts_api_classes.cc.
References data.
deleteAny()
void deleteAny (void * data)
Definition at line 1373 of file arts_api_classes.cc.
References data.
deleteArrayOfPpath()
void deleteArrayOfPpath (void * data)
Definition at line 801 of file arts_api_classes.cc.
References data.
deleteBlock()
void deleteBlock (void * data)
Definition at line 1436 of file arts_api_classes.cc.
References data.
deletePpath()
void deletePpath (void * data)
Definition at line 777 of file arts_api_classes.cc.
References data.
deleteRange()
void deleteRange (void * data)
Definition at line 1420 of file arts_api_classes.cc.
References data.
deleteSpecies()
void deleteSpecies (void * data)
Definition at line 306 of file arts_api_classes.cc.
References data.
deleteTessemNN()
void deleteTessemNN (void * data)
Definition at line 1039 of file arts_api_classes.cc.
References data.
deleteTimer()
void deleteTimer (void * data)
Definition at line 1095 of file arts_api_classes.cc.
References data.
frequenciesPropagationMatrix()
Index frequenciesPropagationMatrix (void * data)
Definition at line 699 of file arts_api_classes.cc.
References data.
frequenciesStokesVector()
Index frequenciesStokesVector (void * data)
Definition at line 725 of file arts_api_classes.cc.
References data.
get_extentRange()
Index get_extentRange (void * data)
Definition at line 1424 of file arts_api_classes.cc.
References data.
get_grid_nameGriddedField1()
char* get_grid_nameGriddedField1 (Index i, void * data)
Definition at line 856 of file arts_api_classes.cc.
References data, and GriddedField1::data.
get_grid_nameGriddedField2()
char* get_grid_nameGriddedField2 (Index i, void * data)
Definition at line 885 of file arts_api_classes.cc.
References data, and GriddedField2::data.
get_grid_nameGriddedField3()
char* get_grid_nameGriddedField3 (Index i, void * data)
Definition at line 914 of file arts_api_classes.cc.
References data, and GriddedField3::data.
get_grid_nameGriddedField4()
char* get_grid_nameGriddedField4 (Index i, void * data)
Definition at line 940 of file arts_api_classes.cc.
References data, and GriddedField4::data.
get_grid_nameGriddedField5()
char* get_grid_nameGriddedField5 (Index i, void * data)
Definition at line 963 of file arts_api_classes.cc.
References data, and GriddedField5::data.
get_grid_nameGriddedField6()
char* get_grid_nameGriddedField6 (Index i, void * data)
Definition at line 986 of file arts_api_classes.cc.
References data, and GriddedField6::data.
get_grid_sizeGriddedField1()
Index get_grid_sizeGriddedField1 (Index i, void * data)
Definition at line 853 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField2()
Index get_grid_sizeGriddedField2 (Index i, void * data)
Definition at line 882 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField3()
Index get_grid_sizeGriddedField3 (Index i, void * data)
Definition at line 911 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField4()
Index get_grid_sizeGriddedField4 (Index i, void * data)
Definition at line 937 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField5()
Index get_grid_sizeGriddedField5 (Index i, void * data)
Definition at line 960 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField6()
Index get_grid_sizeGriddedField6 (Index i, void * data)
Definition at line 983 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField1()
Index get_grid_typeIndexGriddedField1 (Index i, void * data)
Definition at line 852 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField2()
Index get_grid_typeIndexGriddedField2 (Index i, void * data)
Definition at line 881 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField3()
Index get_grid_typeIndexGriddedField3 (Index i, void * data)
Definition at line 910 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField4()
Index get_grid_typeIndexGriddedField4 (Index i, void * data)
Definition at line 936 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField5()
Index get_grid_typeIndexGriddedField5 (Index i, void * data)
Definition at line 959 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField6()
Index get_grid_typeIndexGriddedField6 (Index i, void * data)
Definition at line 982 of file arts_api_classes.cc.
References data.
get_index1Block()
Index get_index1Block (void * data)
Definition at line 1443 of file arts_api_classes.cc.
References data.
get_index2Block()
Index get_index2Block (void * data)
Definition at line 1444 of file arts_api_classes.cc.
References data.
get_matrix_typeBlock()
get_column_range get_sparse Index get_matrix_typeBlock (void * data)
Definition at line 1442 of file arts_api_classes.cc.
References data.
get_nameGriddedField1()
char* get_nameGriddedField1 (void * data)
Definition at line 854 of file arts_api_classes.cc.
References data, and GriddedField1::data.
get_nameGriddedField2()
char* get_nameGriddedField2 (void * data)
Definition at line 883 of file arts_api_classes.cc.
References data, and GriddedField2::data.
get_nameGriddedField3()
char* get_nameGriddedField3 (void * data)
Definition at line 912 of file arts_api_classes.cc.
References data, and GriddedField3::data.
get_nameGriddedField4()
char* get_nameGriddedField4 (void * data)
Definition at line 938 of file arts_api_classes.cc.
References data, and GriddedField4::data.
get_nameGriddedField5()
char* get_nameGriddedField5 (void * data)
Definition at line 961 of file arts_api_classes.cc.
References data, and GriddedField5::data.
get_nameGriddedField6()
char* get_nameGriddedField6 (void * data)
Definition at line 984 of file arts_api_classes.cc.
References data, and GriddedField6::data.
get_numeric_gridGriddedField1()
void* get_numeric_gridGriddedField1 (Index i, void * data)
Definition at line 858 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField2()
void* get_numeric_gridGriddedField2 (Index i, void * data)
Definition at line 887 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField3()
void* get_numeric_gridGriddedField3 (Index i, void * data)
Definition at line 916 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField4()
void* get_numeric_gridGriddedField4 (Index i, void * data)
Definition at line 942 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField5()
void* get_numeric_gridGriddedField5 (Index i, void * data)
Definition at line 965 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField6()
void* get_numeric_gridGriddedField6 (Index i, void * data)
Definition at line 988 of file arts_api_classes.cc.
References data.
get_startRange()
Index get_startRange (void * data)
Definition at line 1422 of file arts_api_classes.cc.
References data.
get_strideRange()
Index get_strideRange (void * data)
Definition at line 1423 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField1()
void* get_string_gridGriddedField1 (Index i, void * data)
Definition at line 859 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField2()
void* get_string_gridGriddedField2 (Index i, void * data)
Definition at line 888 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField3()
void* get_string_gridGriddedField3 (Index i, void * data)
Definition at line 917 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField4()
void* get_string_gridGriddedField4 (Index i, void * data)
Definition at line 943 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField5()
void* get_string_gridGriddedField5 (Index i, void * data)
Definition at line 966 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField6()
void* get_string_gridGriddedField6 (Index i, void * data)
Definition at line 989 of file arts_api_classes.cc.
References data.
getA0_EVEHTelsemAtlas()
Numeric getA0_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1283 of file arts_api_classes.cc.
References data.
getA0_K1TelsemAtlas()
Numeric getA0_K1TelsemAtlas (Index i, void * data)
Definition at line 1281 of file arts_api_classes.cc.
References data.
getA0_K2TelsemAtlas()
Numeric getA0_K2TelsemAtlas (Index i, void * data)
Definition at line 1282 of file arts_api_classes.cc.
References data.
getA1_EVEHTelsemAtlas()
Numeric getA1_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1284 of file arts_api_classes.cc.
References data.
getA2_EVEHTelsemAtlas()
Numeric getA2_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1285 of file arts_api_classes.cc.
References data.
getA3_EVEHTelsemAtlas()
Numeric getA3_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1286 of file arts_api_classes.cc.
References data.
getB0_EVEHTelsemAtlas()
Numeric getB0_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1287 of file arts_api_classes.cc.
References data.
getB1_EVEHTelsemAtlas()
Numeric getB1_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1288 of file arts_api_classes.cc.
References data.
getB2_EVEHTelsemAtlas()
Numeric getB2_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1289 of file arts_api_classes.cc.
References data.
getB3_EVEHTelsemAtlas()
Numeric getB3_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1290 of file arts_api_classes.cc.
References data.
getcputime_end_cstimeTimer()
Index getcputime_end_cstimeTimer (void * data)
Definition at line 1164 of file arts_api_classes.cc.
References data.
getcputime_end_cutimeTimer()
Index getcputime_end_cutimeTimer (void * data)
Definition at line 1156 of file arts_api_classes.cc.
References data.
getcputime_end_stimeTimer()
Index getcputime_end_stimeTimer (void * data)
Definition at line 1148 of file arts_api_classes.cc.
References data.
getcputime_end_utimeTimer()
Index getcputime_end_utimeTimer (void * data)
Definition at line 1140 of file arts_api_classes.cc.
References data.
getcputime_start_cstimeTimer()
Index getcputime_start_cstimeTimer (void * data)
Definition at line 1124 of file arts_api_classes.cc.
References data.
getcputime_start_cutimeTimer()
Index getcputime_start_cutimeTimer (void * data)
Definition at line 1116 of file arts_api_classes.cc.
References data.
getcputime_start_stimeTimer()
Index getcputime_start_stimeTimer (void * data)
Definition at line 1108 of file arts_api_classes.cc.
References data.
getcputime_start_utimeTimer()
Index getcputime_start_utimeTimer (void * data)
Definition at line 1100 of file arts_api_classes.cc.
References data.
getDataMatrix()
Numeric* getDataMatrix (void * data)
Definition at line 595 of file arts_api_classes.cc.
References data.
getDataSparse()
Numeric* getDataSparse (void * data)
Definition at line 1356 of file arts_api_classes.cc.
References data.
getDataTensor3()
Numeric* getDataTensor3 (void * data)
Definition at line 611 of file arts_api_classes.cc.
References data.
getDataTensor4()
Numeric* getDataTensor4 (void * data)
Definition at line 628 of file arts_api_classes.cc.
References data.
getDataTensor5()
Numeric* getDataTensor5 (void * data)
Definition at line 646 of file arts_api_classes.cc.
References data.
getDataTensor6()
Numeric* getDataTensor6 (void * data)
Definition at line 665 of file arts_api_classes.cc.
References data.
getDataTensor7()
Numeric* getDataTensor7 (void * data)
Definition at line 685 of file arts_api_classes.cc.
References data.
getDataVector()
Numeric* getDataVector (void * data)
Definition at line 580 of file arts_api_classes.cc.
References data.
getelemget_blocksCovarianceMatrix()
void* getelemget_blocksCovarianceMatrix (Index i, void * data)
Definition at line 1365 of file arts_api_classes.cc.
References data.
getelemget_inverse_blocksCovarianceMatrix()
void* getelemget_inverse_blocksCovarianceMatrix (Index i, void * data)
Definition at line 1368 of file arts_api_classes.cc.
References data.
getFileVerbosity()
Index getFileVerbosity (void * data)
Definition at line 1026 of file arts_api_classes.cc.
References data.
getfinishedTimer()
bool getfinishedTimer (void * data)
Definition at line 1099 of file arts_api_classes.cc.
References data.
getFrequenciesRadiationVector()
Index getFrequenciesRadiationVector (void * data)
Definition at line 839 of file arts_api_classes.cc.
References data.
getFrequenciesTransmissionMatrix()
Index getFrequenciesTransmissionMatrix (void * data)
Definition at line 821 of file arts_api_classes.cc.
References data.
getGSpeciesIsotopeRecord()
Index getGSpeciesIsotopeRecord (void * data)
Definition at line 371 of file arts_api_classes.cc.
References data.
getIndexSpeciesIsotopeRecordFromData()
Index getIndexSpeciesIsotopeRecordFromData (void * data)
Definition at line 347 of file arts_api_classes.cc.
References data, and Species::find_species_index().
getIsotnameSpeciesIsotopeRecord()
void * getIsotnameSpeciesIsotopeRecord (void * data)
Definition at line 365 of file arts_api_classes.cc.
References data.
getLocalQuantaAbsorptionLines()
Index getLocalQuantaAbsorptionLines (Index i, void * data)
Definition at line 550 of file arts_api_classes.cc.
References data.
getMainVerbosity()
bool getMainVerbosity (void * data)
Definition at line 1027 of file arts_api_classes.cc.
References data.
getMassSpeciesIsotopeRecord()
Numeric getMassSpeciesIsotopeRecord (void * data)
Definition at line 368 of file arts_api_classes.cc.
References data, and LineShape::mass().
getMat2TransmissionMatrix()
Numeric* getMat2TransmissionMatrix (Index i, void * data)
Definition at line 816 of file arts_api_classes.cc.
References data.
getMat3TransmissionMatrix()
Numeric* getMat3TransmissionMatrix (Index i, void * data)
Definition at line 817 of file arts_api_classes.cc.
References data.
getMat4TransmissionMatrix()
Numeric* getMat4TransmissionMatrix (Index i, void * data)
Definition at line 818 of file arts_api_classes.cc.
References data.
getNumeric()
Numeric getNumeric (void * data)
Definition at line 192 of file arts_api_classes.cc.
References data.
getOKPropagationMatrix()
bool getOKPropagationMatrix (void * data)
Definition at line 711 of file arts_api_classes.cc.
References data.
getOKStokesVector()
bool getOKStokesVector (void * data)
Definition at line 737 of file arts_api_classes.cc.
References data.
getQuantumNumbersString()
void* getQuantumNumbersString (void * data)
Definition at line 300 of file arts_api_classes.cc.
References data.
getRAPPORT43_32TelsemAtlas()
Numeric getRAPPORT43_32TelsemAtlas (Index i, void * data)
Definition at line 1291 of file arts_api_classes.cc.
References data.
getRAPPORT54_43TelsemAtlas()
Numeric getRAPPORT54_43TelsemAtlas (Index i, void * data)
Definition at line 1292 of file arts_api_classes.cc.
References data.
getrealtime_endTimer()
Index getrealtime_endTimer (void * data)
Definition at line 1172 of file arts_api_classes.cc.
References data.
getrealtime_startTimer()
Index getrealtime_startTimer (void * data)
Definition at line 1132 of file arts_api_classes.cc.
References data.
getScreenVerbosity()
Index getScreenVerbosity (void * data)
Definition at line 1025 of file arts_api_classes.cc.
References data.
getSpecies1CIARecord()
Data void* getSpecies1CIARecord (void * data)
Definition at line 1005 of file arts_api_classes.cc.
References data.
getSpecies2CIARecord()
void* getSpecies2CIARecord (void * data)
Definition at line 1008 of file arts_api_classes.cc.
References data.
getSpeciesLongName()
void* getSpeciesLongName (void * data)
Definition at line 330 of file arts_api_classes.cc.
References data.
getSpeciesNameAbsorptionLines()
void* getSpeciesNameAbsorptionLines (void * data)
Definition at line 554 of file arts_api_classes.cc.
References data.
getSpeciesShortName()
void* getSpeciesShortName (void * data)
Definition at line 333 of file arts_api_classes.cc.
References data.
getSpeciesSpeciesIsotopeRecord()
void* getSpeciesSpeciesIsotopeRecord (void * data)
Definition at line 362 of file arts_api_classes.cc.
References data.
getStokesDimRadiationVector()
Index getStokesDimRadiationVector (void * data)
Definition at line 838 of file arts_api_classes.cc.
References data.
getStokesDimTransmissionMatrix()
Index getStokesDimTransmissionMatrix (void * data)
Definition at line 820 of file arts_api_classes.cc.
References data.
getString()
char* getString (void * data)
Definition at line 750 of file arts_api_classes.cc.
References data.
GetterSetterCAPI() [1/8]
bool GetterSetterCAPI (AbsorptionLines , Bath , bool)
GetterSetterCAPI() [2/8]
bool Cutoff Mirroring Normalization Numeric GetterSetterCAPI (AbsorptionLines , LinemixingLimit , Numeric)
GetterSetterCAPI() [3/8]
bool Cutoff Mirroring Normalization GetterSetterCAPI (AbsorptionLines , T0 , Numeric)
GetterSetterCAPI() [4/8]
Numeric Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine , A , Numeric)
GetterSetterCAPI() [5/8]
Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine , g_low , Numeric)
GetterSetterCAPI() [6/8]
Numeric GetterSetterCAPI (AbsorptionSingleLine , I0 , Numeric)
GetterSetterCAPI() [7/8]
Numeric Index GetterSetterCAPI (Rational , Denom , Index)
Definition at line 206 of file arts_api_classes.cc.
References data.
GetterSetterCAPI() [8/8]
Numeric GetterSetterCAPI (ZeemanModel , gl , Numeric)
getTypeMCAntenna()
saa aag G Index getTypeMCAntenna (void * data)
Definition at line 1303 of file arts_api_classes.cc.
References data, and Type.
getVec2RadiationVector()
Numeric* getVec2RadiationVector (Index i, void * data)
Definition at line 834 of file arts_api_classes.cc.
References data.
getVec3RadiationVector()
Numeric* getVec3RadiationVector (Index i, void * data)
Definition at line 835 of file arts_api_classes.cc.
References data.
getVec4RadiationVector()
Numeric* getVec4RadiationVector (Index i, void * data)
Definition at line 836 of file arts_api_classes.cc.
References data.
isAbsorptionLinesOK()
Index isAbsorptionLinesOK (void * data)
Definition at line 553 of file arts_api_classes.cc.
References data.
librariesTensor7()
Index librariesTensor7 (void * data)
Definition at line 678 of file arts_api_classes.cc.
References data, and ARTS::Var::nlibraries().
nelemSpeciesIsotopeRecordDefined()
Index nelemSpeciesIsotopeRecordDefined ()
Definition at line 350 of file arts_api_classes.cc.
References Species::Isotopologues.
Referenced by setSpeciesIsotopeRecordToIndex().
nelemVector()
Index nelemVector (void * data)
Definition at line 579 of file arts_api_classes.cc.
References data, and Absorption::nelem().
pagesTensor3()
Index pagesTensor3 (void * data)
Definition at line 608 of file arts_api_classes.cc.
References data, and npages.
pagesTensor4()
Index pagesTensor4 (void * data)
Definition at line 625 of file arts_api_classes.cc.
References data, and npages.
pagesTensor5()
Index pagesTensor5 (void * data)
Definition at line 643 of file arts_api_classes.cc.
References data, and npages.
pagesTensor6()
Index pagesTensor6 (void * data)
Definition at line 662 of file arts_api_classes.cc.
References data, and npages.
pagesTensor7()
Index pagesTensor7 (void * data)
Definition at line 682 of file arts_api_classes.cc.
References data, and npages.
printAny()
void printAny (void *)
Definition at line 1374 of file arts_api_classes.cc.
printArrayOfPpath()
void printArrayOfPpath (void *)
Definition at line 802 of file arts_api_classes.cc.
printBlock()
void printBlock (void *)
Definition at line 1437 of file arts_api_classes.cc.
printmetaAbsorptionLines()
void printmetaAbsorptionLines (void * data)
Definition at line 552 of file arts_api_classes.cc.
References data.
printPpath()
void printPpath (void *)
Definition at line 778 of file arts_api_classes.cc.
printRange()
void printRange (void * data)
Definition at line 1421 of file arts_api_classes.cc.
References data.
printSpecies()
void printSpecies (void * data)
Definition at line 309 of file arts_api_classes.cc.
References data.
printTessemNN()
void printTessemNN (void *)
Definition at line 1040 of file arts_api_classes.cc.
printTimer()
void printTimer (void *)
Definition at line 1096 of file arts_api_classes.cc.
resizeget_blocksCovarianceMatrix()
void resizeget_blocksCovarianceMatrix (Index n, void * data)
Definition at line 1364 of file arts_api_classes.cc.
References data, and joker.
resizeget_inverse_blocksCovarianceMatrix()
void resizeget_inverse_blocksCovarianceMatrix (Index n, void * data)
Definition at line 1367 of file arts_api_classes.cc.
References data, and joker.
resizeLocalQuantaAbsorptionLines()
void resizeLocalQuantaAbsorptionLines (Index n, void * data)
Definition at line 549 of file arts_api_classes.cc.
References data.
rowsMatrix()
Index rowsMatrix (void * data)
Definition at line 593 of file arts_api_classes.cc.
References data, and nrows.
rowsptrSparse()
int* rowsptrSparse (void * data)
Definition at line 1354 of file arts_api_classes.cc.
References data.
rowsSparse()
Index rowsSparse (void * data)
Definition at line 1351 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor3()
Index rowsTensor3 (void * data)
Definition at line 609 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor4()
Index rowsTensor4 (void * data)
Definition at line 626 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor5()
Index rowsTensor5 (void * data)
Definition at line 644 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor6()
Index rowsTensor6 (void * data)
Definition at line 663 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor7()
Index rowsTensor7 (void * data)
Definition at line 683 of file arts_api_classes.cc.
References data, and nrows.
set_grid_nameGriddedField1()
void set_grid_nameGriddedField1 (Index i, void * data, char * newdata)
Definition at line 857 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField2()
void set_grid_nameGriddedField2 (Index i, void * data, char * newdata)
Definition at line 886 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField3()
void set_grid_nameGriddedField3 (Index i, void * data, char * newdata)
Definition at line 915 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField4()
void set_grid_nameGriddedField4 (Index i, void * data, char * newdata)
Definition at line 941 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField5()
void set_grid_nameGriddedField5 (Index i, void * data, char * newdata)
Definition at line 964 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField6()
void set_grid_nameGriddedField6 (Index i, void * data, char * newdata)
Definition at line 987 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField1()
void set_gridGriddedField1 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 860 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField2()
void set_gridGriddedField2 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 889 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField3()
void set_gridGriddedField3 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 918 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField4()
void set_gridGriddedField4 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 944 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField5()
void set_gridGriddedField5 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 967 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField6()
void set_gridGriddedField6 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 990 of file arts_api_classes.cc.
References data, and newdata.
set_indicesBlock()
void set_indicesBlock (void * data, Index i1, Index i2)
Definition at line 1445 of file arts_api_classes.cc.
References data.
set_matrixBlock()
void set_matrixBlock (void * data, void * newdata, bool dense)
Definition at line 1446 of file arts_api_classes.cc.
References data, newdata, and ARTS::Var::x().
set_nameGriddedField1()
void set_nameGriddedField1 (void * data, char * newdata)
Definition at line 855 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField2()
void set_nameGriddedField2 (void * data, char * newdata)
Definition at line 884 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField3()
void set_nameGriddedField3 (void * data, char * newdata)
Definition at line 913 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField4()
void set_nameGriddedField4 (void * data, char * newdata)
Definition at line 939 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField5()
void set_nameGriddedField5 (void * data, char * newdata)
Definition at line 962 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField6()
void set_nameGriddedField6 (void * data, char * newdata)
Definition at line 985 of file arts_api_classes.cc.
References data, and newdata.
setAbsorptionCutoffTypeString()
int setAbsorptionCutoffTypeString (void * data, char * val)
Definition at line 516 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setAbsorptionMirroringTypeString()
int setAbsorptionMirroringTypeString (void * data, char * val)
Definition at line 500 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setAbsorptionNormalizationTypeString()
int setAbsorptionNormalizationTypeString (void * data, char * val)
Definition at line 468 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setAbsorptionPopulationTypeString()
int setAbsorptionPopulationTypeString (void * data, char * val)
Definition at line 484 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setcputime_end_cstimeTimer()
void setcputime_end_cstimeTimer (void * data, Index newdata)
Definition at line 1230 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_cutimeTimer()
void setcputime_end_cutimeTimer (void * data, Index newdata)
Definition at line 1224 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_stimeTimer()
void setcputime_end_stimeTimer (void * data, Index newdata)
Definition at line 1218 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_utimeTimer()
void setcputime_end_utimeTimer (void * data, Index newdata)
Definition at line 1212 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_cstimeTimer()
void setcputime_start_cstimeTimer (void * data, Index newdata)
Definition at line 1200 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_cutimeTimer()
void setcputime_start_cutimeTimer (void * data, Index newdata)
Definition at line 1194 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_stimeTimer()
void setcputime_start_stimeTimer (void * data, Index newdata)
Definition at line 1188 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_utimeTimer()
void setcputime_start_utimeTimer (void * data, Index newdata)
Definition at line 1182 of file arts_api_classes.cc.
References data, and newdata.
setDataSparse()
void setDataSparse (void * data, Index r, Index c, Numeric v)
Definition at line 1357 of file arts_api_classes.cc.
References c, data, and v.
setfinishedTimer()
void setfinishedTimer (void * data, bool newdata)
Definition at line 1181 of file arts_api_classes.cc.
References data, and newdata.
setIndex()
void setIndex (void * data, Index newval)
Definition at line 176 of file arts_api_classes.cc.
References data.
setLineShapeTemperatureModelString()
int setLineShapeTemperatureModelString (void * data, char * val)
Definition at line 214 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setLineShapeTypeString()
int setLineShapeTypeString (void * data, char * val)
Definition at line 252 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setLocalQuantaAbsorptionLines()
void setLocalQuantaAbsorptionLines (Index i, void * data, Index newval)
Definition at line 551 of file arts_api_classes.cc.
References data.
setNumeric()
void setNumeric (void * data, Numeric newval)
Definition at line 193 of file arts_api_classes.cc.
References data.
setPropagationMatrix()
Index setPropagationMatrix (void * data, Index f, Index s, Index z, Index a, Numeric v)
Definition at line 702 of file arts_api_classes.cc.
References a, data, and v.
setQuantumIdentifierTypeString()
int setQuantumIdentifierTypeString (void * data, char * val)
Definition at line 385 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setQuantumNumberTypeString()
int setQuantumNumberTypeString (void * data, char * val)
Definition at line 285 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setRadiationVector()
void setRadiationVector (void * data, Index stokes, Index freqs)
Definition at line 837 of file arts_api_classes.cc.
References data.
setRange()
void setRange (void * data, Index start, Index extent, Index stride)
Definition at line 1425 of file arts_api_classes.cc.
References data, joker, and Zeeman::start().
setrealtime_endTimer()
void setrealtime_endTimer (void * data, Index newdata)
Definition at line 1236 of file arts_api_classes.cc.
References data, and newdata.
setrealtime_startTimer()
void setrealtime_startTimer (void * data, Index newdata)
Definition at line 1206 of file arts_api_classes.cc.
References data, and newdata.
setrunningTimer()
void setrunningTimer (void * data, bool newdata)
Definition at line 1180 of file arts_api_classes.cc.
References data, and newdata.
setSpeciesCIARecord()
void setSpeciesCIARecord (void * data, void * s1, void * s2)
Definition at line 1011 of file arts_api_classes.cc.
References data.
setSpeciesIsotopeRecordToIndex()
int setSpeciesIsotopeRecordToIndex (void * data, Index i)
Definition at line 353 of file arts_api_classes.cc.
References data, Species::Isotopologues, and nelemSpeciesIsotopeRecordDefined().
setSpeciesLongName()
int setSpeciesLongName (void * data, char * spec)
Definition at line 312 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setSpeciesShortName()
int setSpeciesShortName (void * data, char * spec)
Definition at line 321 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setSpeciesTag()
Index setSpeciesTag (void * data, char * newdata)
Definition at line 452 of file arts_api_classes.cc.
References data, and newdata.
setSpeciesTagTypeString()
int setSpeciesTagTypeString (void * data, char * val)
Definition at line 421 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setSpeciesXsecRecord()
void setSpeciesXsecRecord (void * data, void * val)
Definition at line 1329 of file arts_api_classes.cc.
References data.
setStokesVector()
Index setStokesVector (void * data, Index f, Index s, Index z, Index a, Numeric v)
Definition at line 728 of file arts_api_classes.cc.
References a, data, and v.
setTransmissionMatrix()
void setTransmissionMatrix (void * data, Index stokes, Index freqs)
Definition at line 819 of file arts_api_classes.cc.
References data.
setTypeMCAntenna()
Index setTypeMCAntenna (void * data, Index newval)
Definition at line 1304 of file arts_api_classes.cc.
References data, and Type.
setVerbosity()
void setVerbosity (void * data, Index a, Index s, Index f, bool m)
Definition at line 1028 of file arts_api_classes.cc.
References a, data, and ARTS::Var::x().
shelvesTensor5()
Index shelvesTensor5 (void * data)
Definition at line 641 of file arts_api_classes.cc.
References data, and nshelves.
shelvesTensor6()
Index shelvesTensor6 (void * data)
Definition at line 660 of file arts_api_classes.cc.
References data, and nshelves.
shelvesTensor7()
Index shelvesTensor7 (void * data)
Definition at line 680 of file arts_api_classes.cc.
References data, and nshelves.
sizeget_inverse_blocksCovarianceMatrix()
Index sizeget_inverse_blocksCovarianceMatrix (void * data)
Definition at line 1366 of file arts_api_classes.cc.
References data.
sizeQuantumNumbers()
Index sizeQuantumNumbers ()
Definition at line 298 of file arts_api_classes.cc.
sizeSparse()
Index sizeSparse (void * data)
Definition at line 1353 of file arts_api_classes.cc.
References data.
string2quantumnumbersindex()
Index string2quantumnumbersindex (char * str)
Definition at line 299 of file arts_api_classes.cc.
References str.
StringEnumGetterSetterCAPI()
Perturbation StringKey TargetType StringEnumGetterSetterCAPI (JacobianTarget , TargetSubType)
supportTimer()
bool supportTimer ()
Definition at line 1242 of file arts_api_classes.cc.
tickTimer()
Index tickTimer ()
Definition at line 1250 of file arts_api_classes.cc.
vitrinesTensor6()
Index vitrinesTensor6 (void * data)
Definition at line 659 of file arts_api_classes.cc.
References data, and nvitrines.
vitrinesTensor7()
Index vitrinesTensor7 (void * data)
Definition at line 679 of file arts_api_classes.cc.
References data, and nvitrines.
VoidArrayCAPI() [1/12]
bool Cutoff Mirroring Normalization Numeric QuantumIdentity AllLines VoidArrayCAPI (ArrayOfAbsorptionLines)
Definition at line 542 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [2/12]
VoidArrayCAPI (ArrayOfCIARecord)
Definition at line 1016 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [3/12]
VoidArrayCAPI (ArrayOfIndex)
VoidArrayCAPI() [4/12]
idx pos dlx VoidArrayCAPI (ArrayOfLagrangeInterpolation)
VoidArrayCAPI() [5/12]
dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon VoidArrayCAPI (ArrayOfPpath)
Definition at line 799 of file arts_api_classes.cc.
VoidArrayCAPI() [6/12]
Data VoidArrayCAPI (ArrayOfPropagationMatrix)
Definition at line 692 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [7/12]
Perturbation StringKey TargetType SubTag Mode Target TFuncParameters Offset VoidArrayCAPI (ArrayOfRetrievalQuantity)
Definition at line 1413 of file arts_api_classes.cc.
References joker.
VoidArrayCAPI() [8/12]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max diameter_area_equ_aerodynamical VoidArrayCAPI (ArrayOfScatteringMetaData)
Definition at line 1085 of file arts_api_classes.cc.
VoidArrayCAPI() [9/12]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data VoidArrayCAPI (ArrayOfSingleScatteringData)
VoidArrayCAPI() [10/12]
VoidArrayCAPI (ArrayOfSpecies)
VoidArrayCAPI() [11/12]
Data VoidArrayCAPI (ArrayOfStokesVector)
Definition at line 718 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [12/12]
Numeric VoidArrayCAPI (ArrayOfTime)
References data, and newdata.
VoidArrayElemCAPI()
Numeric Numeric Numeric Zeeman LowerQuantumNumbers VoidArrayElemCAPI (AbsorptionSingleLine , UpperQuantumNumbers)
Definition at line 278 of file arts_api_classes.cc.
References data.
VoidGetterCAPI() [1/36]
bool Cutoff Mirroring Normalization Numeric QuantumIdentity VoidGetterCAPI (AbsorptionLines , BroadeningSpecies)
VoidGetterCAPI() [2/36]
bool Cutoff VoidGetterCAPI (AbsorptionLines , LineShapeType)
VoidGetterCAPI() [3/36]
bool Cutoff Mirroring VoidGetterCAPI (AbsorptionLines , Population)
VoidGetterCAPI() [4/36]
Numeric Numeric Numeric Zeeman VoidGetterCAPI (AbsorptionSingleLine , LineShape)
VoidGetterCAPI() [5/36]
get_column_range VoidGetterCAPI (Block , get_dense)
VoidGetterCAPI() [6/36]
VoidGetterCAPI (Block , get_row_range)
VoidGetterCAPI() [7/36]
EnergyLevelMapType Energies VoidGetterCAPI (EnergyLevelMap , Data)
Definition at line 565 of file arts_api_classes.cc.
References data.
VoidGetterCAPI() [8/36]
EnergyLevelMapType VoidGetterCAPI (EnergyLevelMap , Levels)
VoidGetterCAPI() [9/36]
Species Fgrid VoidGetterCAPI (GasAbsLookup , FLAGDefault)
VoidGetterCAPI() [10/36]
Species Fgrid Pgrid VoidGetterCAPI (GasAbsLookup , LogPgrid)
VoidGetterCAPI() [11/36]
Species Fgrid Pgrid VMRs Tpert VoidGetterCAPI (GasAbsLookup , NLSPert)
VoidGetterCAPI() [12/36]
Species VoidGetterCAPI (GasAbsLookup , NonLinearSpecies)
VoidGetterCAPI() [13/36]
Species Fgrid Pgrid VMRs VoidGetterCAPI (GasAbsLookup , Tref)
VoidGetterCAPI() [14/36]
Perturbation VoidGetterCAPI (JacobianTarget , QuantumIdentity)
VoidGetterCAPI() [15/36]
Perturbation StringKey VoidGetterCAPI (JacobianTarget , SpeciesList)
VoidGetterCAPI() [16/36]
type X1 X3 G0 VoidGetterCAPI (LineShapeSingleSpeciesModel , D0)
VoidGetterCAPI() [17/36]
type X1 X3 G0 G2 VoidGetterCAPI (LineShapeSingleSpeciesModel , D2)
VoidGetterCAPI() [18/36]
type X1 X3 G0 G2 FVC VoidGetterCAPI (LineShapeSingleSpeciesModel , ETA)
VoidGetterCAPI() [19/36]
type X1 X3 G0 G2 FVC Y VoidGetterCAPI (LineShapeSingleSpeciesModel , G)
VoidGetterCAPI() [20/36]
saa VoidGetterCAPI (MCAntenna , sza)
VoidGetterCAPI() [21/36]
saa aag VoidGetterCAPI (MCAntenna , zag)
VoidGetterCAPI() [22/36]
Perturbation StringKey TargetType SubTag Mode VoidGetterCAPI (RetrievalQuantity , Grids)
VoidGetterCAPI() [23/36]
Perturbation StringKey TargetType SubTag VoidGetterCAPI (RetrievalQuantity , SubSubTag)
VoidGetterCAPI() [24/36]
Perturbation StringKey TargetType SubTag Mode Target TFuncParameters VoidGetterCAPI (RetrievalQuantity , Transformation)
VoidGetterCAPI() [25/36]
Perturbation StringKey TargetType SubTag Mode Target VoidGetterCAPI (RetrievalQuantity , TransformationFunc)
VoidGetterCAPI() [26/36]
DataCount Name Lat VoidGetterCAPI (TelsemAtlas , Cells)
VoidGetterCAPI() [27/36]
DataCount VoidGetterCAPI (TelsemAtlas , ChannelCount)
VoidGetterCAPI() [28/36]
DataCount Name Lat FirstCells Emis_err Classes1 VoidGetterCAPI (TelsemAtlas , Classes2)
VoidGetterCAPI() [29/36]
DataCount Name Lat FirstCells Emis_err VoidGetterCAPI (TelsemAtlas , Correlations)
VoidGetterCAPI() [30/36]
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber VoidGetterCAPI (TelsemAtlas , Correspondance)
References data.
VoidGetterCAPI() [31/36]
DataCount Name Lat FirstCells VoidGetterCAPI (TelsemAtlas , Emis)
VoidGetterCAPI() [32/36]
DataCount Name VoidGetterCAPI (TelsemAtlas , Month)
VoidGetterCAPI() [33/36]
VoidGetterCAPI (XsecRecord , Coeffs)
VoidGetterCAPI() [34/36]
RefPressure VoidGetterCAPI (XsecRecord , RefTemperature)
VoidGetterCAPI() [35/36]
RefPressure Fgrids TemperatureSlope VoidGetterCAPI (XsecRecord , TemperatureIntersect)
References data, ncols, and nrows.
VoidGetterCAPI() [36/36]
RefPressure Fgrids VoidGetterCAPI (XsecRecord , Xsecs)
VoidStructGetterCAPI() [1/30]
idx VoidStructGetterCAPI (GridPos , fd)
VoidStructGetterCAPI() [2/30]
idx pos VoidStructGetterCAPI (LagrangeInterpolation , lx)
VoidStructGetterCAPI() [3/30]
type VoidStructGetterCAPI (LineShapeModelParameters , X0)
VoidStructGetterCAPI() [4/30]
type X1 VoidStructGetterCAPI (LineShapeModelParameters , X2)
VoidStructGetterCAPI() [5/30]
dim constant VoidStructGetterCAPI (Ppath , background)
VoidStructGetterCAPI() [6/30]
dim constant start_pos start_lstep los lstep end_los VoidStructGetterCAPI (Ppath , end_lstep)
VoidStructGetterCAPI() [7/30]
dim constant start_pos start_lstep los lstep VoidStructGetterCAPI (Ppath , end_pos)
VoidStructGetterCAPI() [8/30]
dim constant start_pos start_lstep los lstep end_los nreal gp_p VoidStructGetterCAPI (Ppath , gp_lat)
VoidStructGetterCAPI() [9/30]
dim constant start_pos start_lstep los lstep end_los nreal VoidStructGetterCAPI (Ppath , ngroup)
VoidStructGetterCAPI() [10/30]
dim VoidStructGetterCAPI (Ppath , np)
VoidStructGetterCAPI() [11/30]
dim constant start_pos start_lstep VoidStructGetterCAPI (Ppath , pos)
VoidStructGetterCAPI() [12/30]
dim constant start_pos start_lstep los VoidStructGetterCAPI (Ppath , r)
VoidStructGetterCAPI() [13/30]
dim constant start_pos VoidStructGetterCAPI (Ppath , start_los)
VoidStructGetterCAPI() [14/30]
type upp VoidStructGetterCAPI (QuantumIdentifier , low)
VoidStructGetterCAPI() [15/30]
type VoidStructGetterCAPI (QuantumIdentifier , spec_ind)
VoidStructGetterCAPI() [16/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max VoidStructGetterCAPI (ScatteringMetaData , diameter_volume_equ)
VoidStructGetterCAPI() [17/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index VoidStructGetterCAPI (ScatteringMetaData , mass)
VoidStructGetterCAPI() [18/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description VoidStructGetterCAPI (ScatteringMetaData , source)
VoidStructGetterCAPI() [19/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid VoidStructGetterCAPI (SingleScatteringData , aa_grid)
VoidStructGetterCAPI() [20/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype VoidStructGetterCAPI (SingleScatteringData , description)
VoidStructGetterCAPI() [21/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data VoidStructGetterCAPI (SingleScatteringData , ext_mat_data)
VoidStructGetterCAPI() [22/30]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid VoidStructGetterCAPI (SingleScatteringData , T_grid)
VoidStructGetterCAPI() [23/30]
spec_ind upper_freq cia_2nd_species VoidStructGetterCAPI (SpeciesTag , cia_dataset_index)
Definition at line 439 of file arts_api_classes.cc.
References data.
VoidStructGetterCAPI() [24/30]
spec_ind VoidStructGetterCAPI (SpeciesTag , lower_freq)
VoidStructGetterCAPI() [25/30]
spec_ind upper_freq VoidStructGetterCAPI (SpeciesTag , type)
VoidStructGetterCAPI() [26/30]
nb_inputs nb_cache VoidStructGetterCAPI (TessemNN , b1)
VoidStructGetterCAPI() [27/30]
nb_inputs VoidStructGetterCAPI (TessemNN , nb_outputs)
VoidStructGetterCAPI() [28/30]
nb_inputs nb_cache b2 VoidStructGetterCAPI (TessemNN , w1)
VoidStructGetterCAPI() [29/30]
nb_inputs nb_cache b2 w2 VoidStructGetterCAPI (TessemNN , x_min)
VoidStructGetterCAPI() [30/30]
nb_inputs nb_cache b2 w2 x_max VoidStructGetterCAPI (TessemNN , y_min)
xmlreadAny()
Index xmlreadAny (void * , char *)
Definition at line 1375 of file arts_api_classes.cc.
xmlsaveAny()
Index xmlsaveAny (void * , char * , Index , Index)
Definition at line 1376 of file arts_api_classes.cc.
xmlsaveArrayOfLagrangeInterpolation()
idx pos dlx char* Index xmlsaveArrayOfLagrangeInterpolation (void * , char * , Index , Index)
Definition at line 771 of file arts_api_classes.cc.
xmlsaveArrayOfNumeric()
char* Index xmlsaveArrayOfNumeric (void * , char * , Index , Index)
Definition at line 191 of file arts_api_classes.cc.
xmlsaveArrayOfSpecies()
char* Index xmlsaveArrayOfSpecies (void * , char * , Index , Index)
Definition at line 338 of file arts_api_classes.cc.
zenithsPropagationMatrix()
Index zenithsPropagationMatrix (void * data)
Definition at line 700 of file arts_api_classes.cc.
References data.
zenithsStokesVector()
Index zenithsStokesVector (void * data)
Definition at line 726 of file arts_api_classes.cc.
References data.
Variable Documentation
CutoffFreqValue
bool Cutoff Mirroring Normalization CutoffFreqValue
Definition at line 537 of file arts_api_classes.cc.
data
RefPressure Fgrids TemperatureSlope Index void * data { return &static_cast<QuantumNumbers *>(data)->operator[](i)
Definition at line 297 of file arts_api_classes.cc.
Referenced by abs_nlteFromRaw(), ARTS::Method::abs_nlteFromRaw(), ARTS::Agenda::Method::abs_nlteFromRaw(), Linefunctions::apply_VVH_scaling(), azimuthsPropagationMatrix(), azimuthsStokesVector(), backend_channel_responseGaussian(), BasicInputOutputCAPI(), BasicInterfaceCAPI(), booksTensor4(), booksTensor5(), booksTensor6(), booksTensor7(), Raw::Calibration::caha(), checksizeGriddedField1(), checksizeGriddedField2(), checksizeGriddedField3(), checksizeGriddedField4(), checksizeGriddedField5(), checksizeGriddedField6(), chk_interpolation_grids_loose(), chk_interpolation_grids_loose_check_data(), colsMatrix(), colsptrSparse(), colsSparse(), colsTensor3(), colsTensor4(), colsTensor5(), colsTensor6(), colsTensor7(), PartitionFunctions::computeAcetonitrile(), PartitionFunctions::computeAcetylene(), PartitionFunctions::computeAmmonia(), PartitionFunctions::computeBromomethane(), PartitionFunctions::computeCarbonDioxide(), PartitionFunctions::computeCarbonDisulfide(), PartitionFunctions::computeCarbonMonosulfide(), PartitionFunctions::computeCarbonMonoxide(), PartitionFunctions::computeCarbonTetrafluoride(), PartitionFunctions::computeCarbonylFluoride(), PartitionFunctions::computeCarbonylSulfide(), PartitionFunctions::computeChlorineMonoxide(), PartitionFunctions::computeChlorineNitrate(), PartitionFunctions::computeChloromethane(), PartitionFunctions::computeCyanoacetylene(), PartitionFunctions::computeCyanogen(), PartitionFunctions::computeCyclopropene(), PartitionFunctions::computeDiacetylene(), PartitionFunctions::computeEthane(), PartitionFunctions::computeEthylene(), PartitionFunctions::computeFluoromethane(), PartitionFunctions::computeFormaldehyde(), PartitionFunctions::computeFormicAcid(), PartitionFunctions::computeGermane(), PartitionFunctions::computeHydrogen(), PartitionFunctions::computeHydrogenBromide(), PartitionFunctions::computeHydrogenChloride(), PartitionFunctions::computeHydrogenCyanide(), PartitionFunctions::computeHydrogenFluoride(), PartitionFunctions::computeHydrogenIodide(), PartitionFunctions::computeHydrogenPeroxide(), PartitionFunctions::computeHydrogenSulfide(), PartitionFunctions::computeHydroperoxyl(), PartitionFunctions::computeHydroxyl(), PartitionFunctions::computeHypobromousAcid(), PartitionFunctions::computeHypochlorousAcid(), PartitionFunctions::computeIodomethane(), PartitionFunctions::computeMethane(), PartitionFunctions::computeMethanol(), PartitionFunctions::computeMethyl(), PartitionFunctions::computeNitricAcid(), PartitionFunctions::computeNitricOxide(), PartitionFunctions::computeNitricOxideCation(), PartitionFunctions::computeNitrogen(), PartitionFunctions::computeNitrogenDioxide(), PartitionFunctions::computeNitrogenOxide(), PartitionFunctions::computeNitrogenTrifluoride(), PartitionFunctions::computeOxygen(), PartitionFunctions::computeOzone(), PartitionFunctions::computePhosgene(), PartitionFunctions::computePhosphine(), PartitionFunctions::computeSulfurDioxide(), PartitionFunctions::computeSulfurHexafluoride(), PartitionFunctions::computeSulfurMonoxide(), PartitionFunctions::computeSulfurTrioxide(), PartitionFunctions::computeWater(), dataGriddedField1(), dataGriddedField2(), dataGriddedField3(), dataGriddedField4(), dataGriddedField5(), dataGriddedField6(), deleteAny(), deleteArrayOfPpath(), deleteBlock(), deletePpath(), deleteRange(), deleteSpecies(), deleteTessemNN(), deleteTimer(), ecs_dataSetMeanAir(), ecs_dataSetSpeciesData(), EnergyLevelMap::EnergyLevelMap(), f_gridFromSensorAMSUgeneric(), frequenciesPropagationMatrix(), frequenciesStokesVector(), LineShape::from_linefunctiondata(), LineShape::from_linemixingdata(), LineShape::from_pressurebroadeningdata(), gen_dir(), get_extentRange(), get_grid_nameGriddedField1(), get_grid_nameGriddedField2(), get_grid_nameGriddedField3(), get_grid_nameGriddedField4(), get_grid_nameGriddedField5(), get_grid_nameGriddedField6(), get_grid_sizeGriddedField1(), get_grid_sizeGriddedField2(), get_grid_sizeGriddedField3(), get_grid_sizeGriddedField4(), get_grid_sizeGriddedField5(), get_grid_sizeGriddedField6(), get_grid_typeIndexGriddedField1(), get_grid_typeIndexGriddedField2(), get_grid_typeIndexGriddedField3(), get_grid_typeIndexGriddedField4(), get_grid_typeIndexGriddedField5(), get_grid_typeIndexGriddedField6(), get_index1Block(), get_index2Block(), get_matrix_typeBlock(), get_nameGriddedField1(), get_nameGriddedField2(), get_nameGriddedField3(), get_nameGriddedField4(), get_nameGriddedField5(), get_nameGriddedField6(), get_numeric_gridGriddedField1(), get_numeric_gridGriddedField2(), get_numeric_gridGriddedField3(), get_numeric_gridGriddedField4(), get_numeric_gridGriddedField5(), get_numeric_gridGriddedField6(), get_sorted_indexes(), get_startRange(), get_strideRange(), get_string_gridGriddedField1(), get_string_gridGriddedField2(), get_string_gridGriddedField3(), get_string_gridGriddedField4(), get_string_gridGriddedField5(), get_string_gridGriddedField6(), getA0_EVEHTelsemAtlas(), getA0_K1TelsemAtlas(), getA0_K2TelsemAtlas(), getA1_EVEHTelsemAtlas(), getA2_EVEHTelsemAtlas(), getA3_EVEHTelsemAtlas(), getB0_EVEHTelsemAtlas(), getB1_EVEHTelsemAtlas(), getB2_EVEHTelsemAtlas(), getB3_EVEHTelsemAtlas(), getcputime_end_cstimeTimer(), getcputime_end_cutimeTimer(), getcputime_end_stimeTimer(), getcputime_end_utimeTimer(), getcputime_start_cstimeTimer(), getcputime_start_cutimeTimer(), getcputime_start_stimeTimer(), getcputime_start_utimeTimer(), getDataMatrix(), getDataSparse(), getDataTensor3(), getDataTensor4(), getDataTensor5(), getDataTensor6(), getDataTensor7(), getDataVector(), getelemget_blocksCovarianceMatrix(), getelemget_inverse_blocksCovarianceMatrix(), getFileVerbosity(), getfinishedTimer(), getFrequenciesRadiationVector(), getFrequenciesTransmissionMatrix(), getGSpeciesIsotopeRecord(), getIndexSpeciesIsotopeRecordFromData(), getIsotnameSpeciesIsotopeRecord(), getLocalQuantaAbsorptionLines(), getMainVerbosity(), getMassSpeciesIsotopeRecord(), getMat2TransmissionMatrix(), getMat3TransmissionMatrix(), getMat4TransmissionMatrix(), getNumeric(), getOKPropagationMatrix(), getOKStokesVector(), getQuantumNumbersString(), getRAPPORT43_32TelsemAtlas(), getRAPPORT54_43TelsemAtlas(), getrealtime_endTimer(), getrealtime_startTimer(), getScreenVerbosity(), getSpecies1CIARecord(), getSpecies2CIARecord(), getSpeciesLongName(), getSpeciesNameAbsorptionLines(), getSpeciesShortName(), getSpeciesSpeciesIsotopeRecord(), getStokesDimRadiationVector(), getStokesDimTransmissionMatrix(), getString(), GetterSetterCAPI(), getTypeMCAntenna(), getVec2RadiationVector(), getVec3RadiationVector(), getVec4RadiationVector(), Jpl::id_from_lookup(), binistream::ieee_double2float(), binistream::ieee_single2float(), Sparse::insert_elements(), isAbsorptionLinesOK(), Hitran::isotopologue_ratios_impl(), librariesTensor7(), StokesVector::MultiplyAndAdd(), nca_get_data_double(), nca_get_data_int(), nca_get_data_long(), nca_get_data_text(), nca_get_dataa_double(), nelemVector(), nlte_fieldFromRaw(), ARTS::Method::nlte_fieldFromRaw(), ARTS::Agenda::Method::nlte_fieldFromRaw(), LineShape::operator<<(), LineShape::operator>>(), pagesTensor3(), pagesTensor4(), pagesTensor5(), pagesTensor6(), pagesTensor7(), particle_bulkpropRadarOnionPeeling(), pnd_fieldCalcFrompnd_field_raw(), print_auto_partfun_h(), print_data(), print_method(), printmetaAbsorptionLines(), printRange(), printSpecies(), LineShape::SingleSpeciesModel::read(), LineShape::Model::read(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitran2012Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromJplStream(), Absorption::ReadFromLBLRTMStream(), resizeget_blocksCovarianceMatrix(), resizeget_inverse_blocksCovarianceMatrix(), resizeLocalQuantaAbsorptionLines(), rowsMatrix(), rowsptrSparse(), rowsSparse(), rowsTensor3(), rowsTensor4(), rowsTensor5(), rowsTensor6(), rowsTensor7(), rtp_nlteFromRaw(), ARTS::Method::rtp_nlteFromRaw(), ARTS::Agenda::Method::rtp_nlteFromRaw(), Zeeman::SelectPolarization(), Linefunctions::set_cross_section_of_band(), Linefunctions::set_doppler(), set_grid_nameGriddedField1(), set_grid_nameGriddedField2(), set_grid_nameGriddedField3(), set_grid_nameGriddedField4(), set_grid_nameGriddedField5(), set_grid_nameGriddedField6(), set_gridGriddedField1(), set_gridGriddedField2(), set_gridGriddedField3(), set_gridGriddedField4(), set_gridGriddedField5(), set_gridGriddedField6(), set_indicesBlock(), Linefunctions::set_lineshape(), Linefunctions::set_lorentz(), set_matrixBlock(), set_nameGriddedField1(), set_nameGriddedField2(), set_nameGriddedField3(), set_nameGriddedField4(), set_nameGriddedField5(), set_nameGriddedField6(), Linefunctions::set_voigt(), setAbsorptionCutoffTypeString(), setAbsorptionMirroringTypeString(), setAbsorptionNormalizationTypeString(), setAbsorptionPopulationTypeString(), setcputime_end_cstimeTimer(), setcputime_end_cutimeTimer(), setcputime_end_stimeTimer(), setcputime_end_utimeTimer(), setcputime_start_cstimeTimer(), setcputime_start_cutimeTimer(), setcputime_start_stimeTimer(), setcputime_start_utimeTimer(), setDataSparse(), setfinishedTimer(), setIndex(), setLineShapeTemperatureModelString(), setLineShapeTypeString(), setLocalQuantaAbsorptionLines(), setNumeric(), setPropagationMatrix(), setQuantumIdentifierTypeString(), setQuantumNumberTypeString(), setRadiationVector(), setRange(), setrealtime_endTimer(), setrealtime_startTimer(), setrunningTimer(), setSpeciesCIARecord(), setSpeciesIsotopeRecordToIndex(), setSpeciesLongName(), setSpeciesShortName(), setSpeciesTag(), setSpeciesTagTypeString(), setSpeciesXsecRecord(), setStokesVector(), setTransmissionMatrix(), setTypeMCAntenna(), setVerbosity(), shelvesTensor5(), shelvesTensor6(), shelvesTensor7(), sizeget_inverse_blocksCovarianceMatrix(), sizeSparse(), sorted_index_of_ppath_field(), spectrometer_matrix(), vitrinesTensor6(), vitrinesTensor7(), VoidArrayCAPI(), VoidArrayElemCAPI(), VoidGetterCAPI(), VoidStructGetterCAPI(), LineShape::SingleSpeciesModel::write(), LineShape::Model::write(), WriteBuiltinPartitionFunctionsXML(), xml_read_from_stream(), xml_write_to_stream(), ybatchMetProfiles(), zenithsPropagationMatrix(), and zenithsStokesVector().
E0
Numeric E0
Definition at line 271 of file arts_api_classes.cc.
Referenced by boltzman_factor(), dboltzman_factordE0(), dboltzman_factordT(), dboltzman_ratio_dT(), and dboltzman_ratio_dT_div_boltzmann_ratio().
F0
F0
Definition at line 269 of file arts_api_classes.cc.
Referenced by Linefunctions::apply_linestrength_from_nlte_level_distributions(), Linefunctions::apply_rosenkranz_quadratic_scaling(), Linefunctions::apply_VVH_scaling(), Linefunctions::apply_VVW_scaling(), dabsorption_nlte_rate_dT(), LineShape::SimpleFrequencyScaling::dNdF0(), LineShape::SimpleFrequencyScaling::dNdT(), dstimulated_emissiondF0(), dstimulated_emissiondT(), dstimulated_relative_emission_dT(), LineShape::line_shape_selection(), main(), LineShape::mirror_line_shape_selection(), LineShape::normalizer_selection(), LineShape::SimpleFrequencyScaling::operator()(), Linefunctions::set_doppler(), Linefunctions::set_lorentz(), Linefunctions::set_voigt(), stimulated_emission(), test_matrix_exp_propmat(), ybatchDoublingMeanFocus(), and yDoublingMeanFocus().
g_upp
Numeric Numeric g_upp
Definition at line 273 of file arts_api_classes.cc.
gu
gu
Definition at line 198 of file arts_api_classes.cc.
Referenced by Zeeman::GetSimpleModel().
isot
char* isot
Initial value:
{
  return Species::find_species_index(spec, isot)
Definition at line 343 of file arts_api_classes.cc.
Referenced by abs_lines_per_speciesReadSpeciesSplitCatalog(), check_collision_line_identifiers(), Absorption::LineMixing::LinearRovibErrorCorrectedSudden::erot_selection(), Species::find_species_index(), split_filename_species(), and Hitran::to_species_map().
nbooks
Index Index Index nbooks
Definition at line 640 of file arts_api_classes.cc.
Referenced by booksTensor4(), booksTensor5(), booksTensor6(), booksTensor7(), chk_atm_field(), ARTS::Method::nbooksGet(), nca_get_data_Tensor4(), nca_read_from_file(), opt_prop_ScatSpecBulk(), pha_mat_sptFromDataDOITOpt(), Tensor4SetConstant(), ARTS::Method::Tensor4SetConstant(), Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), and xml_read_from_stream().
ncols
RefPressure Fgrids TemperatureSlope Index ncols
Definition at line 592 of file arts_api_classes.cc.
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesInit(), chk_atm_field(), chk_atm_surface(), colsMatrix(), colsSparse(), colsTensor3(), colsTensor4(), colsTensor5(), colsTensor6(), colsTensor7(), ConstComplexMatrixView::empty(), MatrixSetConstant(), ARTS::Method::MatrixSetConstant(), nca_get_data_Matrix(), nca_get_data_Tensor4(), nca_read_from_file(), ARTS::Method::ncolsGet(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), Sparse::operator Matrix(), MatrixView::operator*=(), MatrixView::operator+=(), MatrixView::operator-=(), MatrixView::operator/=(), ArtsParser::parse_matrix(), propmat_clearskyAddFromAbsCoefPerSpecies(), Matrix::reduce_rank(), sensor_poslosFromECEF(), sensor_poslosFromGeodetic(), sensor_responseGenericAMSU(), ComplexMatrix::size(), Matrix::size(), Tensor3SetConstant(), ARTS::Method::Tensor3SetConstant(), Tensor4SetConstant(), ARTS::Method::Tensor4SetConstant(), Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), VoidGetterCAPI(), and xml_read_from_stream().
newdata
char* newdata {static_cast<String *>(data) -> operator=(String(newdata))
Definition at line 749 of file arts_api_classes.cc.
Referenced by abs_linesSetLineShapeModelParametersForMatchingLines(), set_grid_nameGriddedField1(), set_grid_nameGriddedField2(), set_grid_nameGriddedField3(), set_grid_nameGriddedField4(), set_grid_nameGriddedField5(), set_grid_nameGriddedField6(), set_gridGriddedField1(), set_gridGriddedField2(), set_gridGriddedField3(), set_gridGriddedField4(), set_gridGriddedField5(), set_gridGriddedField6(), set_matrixBlock(), set_nameGriddedField1(), set_nameGriddedField2(), set_nameGriddedField3(), set_nameGriddedField4(), set_nameGriddedField5(), set_nameGriddedField6(), setcputime_end_cstimeTimer(), setcputime_end_cutimeTimer(), setcputime_end_stimeTimer(), setcputime_end_utimeTimer(), setcputime_start_cstimeTimer(), setcputime_start_cutimeTimer(), setcputime_start_stimeTimer(), setcputime_start_utimeTimer(), setfinishedTimer(), setrealtime_endTimer(), setrealtime_startTimer(), setrunningTimer(), setSpeciesTag(), and VoidArrayCAPI().
Nom
Numeric Nom
Definition at line 205 of file arts_api_classes.cc.
npages
Index Index Index Index npages
Definition at line 623 of file arts_api_classes.cc.
Referenced by chk_atm_field(), iyLoopFrequencies(), nca_get_data_Tensor4(), nca_read_from_file(), ARTS::Method::npagesGet(), opt_prop_ScatSpecBulk(), pagesTensor3(), pagesTensor4(), pagesTensor5(), pagesTensor6(), pagesTensor7(), pha_mat_sptFromDataDOITOpt(), Tensor3SetConstant(), ARTS::Method::Tensor3SetConstant(), Tensor4SetConstant(), ARTS::Method::Tensor4SetConstant(), Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), xml_read_from_stream(), and yRadar().
nrows
Index Index Index Index Index nrows
Definition at line 607 of file arts_api_classes.cc.
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesInit(), chk_atm_field(), chk_atm_surface(), ConstComplexMatrixView::empty(), MatrixSetConstant(), ARTS::Method::MatrixSetConstant(), nca_get_data_Matrix(), nca_get_data_Tensor4(), nca_read_from_file(), ARTS::Method::nrowsGet(), CovarianceMatrix::operator Matrix(), Sparse::operator Matrix(), MatrixView::operator*=(), MatrixView::operator+=(), MatrixView::operator-=(), MatrixView::operator/=(), ArtsParser::parse_matrix(), propmat_clearskyAddFromAbsCoefPerSpecies(), Matrix::reduce_rank(), rowsMatrix(), rowsSparse(), rowsTensor3(), rowsTensor4(), rowsTensor5(), rowsTensor6(), rowsTensor7(), sensor_poslosFromECEF(), sensor_poslosFromGeodetic(), sensor_responseGenericAMSU(), ComplexMatrix::size(), Matrix::size(), Tensor3SetConstant(), ARTS::Method::Tensor3SetConstant(), Tensor4SetConstant(), ARTS::Method::Tensor4SetConstant(), Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), VoidGetterCAPI(), and xml_read_from_stream().
nshelves
Index Index nshelves
Definition at line 658 of file arts_api_classes.cc.
Referenced by nca_read_from_file(), ARTS::Method::nshelvesGet(), pha_mat_ScatSpecBulk(), pha_mat_sptFromDataDOITOpt(), shelvesTensor5(), shelvesTensor6(), shelvesTensor7(), Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), and xml_read_from_stream().
nvitrines
Index nvitrines
Definition at line 677 of file arts_api_classes.cc.
Referenced by ARTS::Method::nvitrinesGet(), pha_mat_sptFromDataDOITOpt(), Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), vitrinesTensor6(), vitrinesTensor7(), and xml_read_from_stream().
Seconds
Seconds
Definition at line 1460 of file arts_api_classes.cc.
Referenced by time_vector().
Self
Self
Definition at line 529 of file arts_api_classes.cc.
str
type upp char* str
Initial value:
{
  try {
    static_cast<QuantumIdentifier *>(data) -> SetFromString(str);
    return EXIT_SUCCESS;
  } catch(...) {
  }
  return EXIT_FAILURE
Definition at line 402 of file arts_api_classes.cc.
Referenced by ArtsParser::eat_whitespace_from_string(), enum_strarray(), Quantum::ENUMCLASS(), Absorption::LineMixing::EquivalentLines::EquivalentLines(), GetEnvironmentVariable(), LineShape::MetaData2ModelShape(), ArtsParser::parse_intvector_from_string(), ArtsParser::parse_numvector_from_string(), ArtsParser::parse_stringarray_from_string(), binistream::readString(), string2quantumnumbersindex(), string2vecqn(), binostream::writeString(), xml_read_from_stream(), xml_read_header_from_stream(), and xml_write_to_stream().
Type
Type
Definition at line 562 of file arts_api_classes.cc.
Referenced by abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), abs_xsec_agenda_checkedCalc(), abs_xsec_per_speciesAddConts(), check_abs_species(), Jacobian::ENUMCLASS(), Species::ENUMCLASS(), getTypeMCAntenna(), propmat_clearsky_agenda_checkedCalc(), propmat_clearskyAddParticles(), setTypeMCAntenna(), Absorption::Lines::validIndexForLineShapeType(), and xml_read_from_stream().