ARTS: arts_api_classes.h File Reference
arts_api_classes.h File Reference
This file contains all declarations of the ARTS C API class interface.
#include "matpack.h"
Macros
#define DLL_PUBLIC __attribute__((visibility("default")))
#define REMOVE_DLL_PUBLIC 1
#define BasicInterfaceCAPI(TYPE)
#define GetterSetterCAPI(TYPE, VALUE, BASETYPE)
#define EnumGetterSetterCAPI(TYPE, VALUE, ENUM)
#define StringEnumGetterSetterCAPI(TYPE, ELEM)
#define VoidGetterCAPI(TYPE, VALUE)
#define VoidStructGetterCAPI(TYPE, VALUE)
#define BasicInputOutputCAPI(TYPE)
#define VoidArrayCAPI(TYPE)
#define VoidArrayElemCAPI(TYPE, ELEM)
#define StringEnumPointersCAPI(ENUM)
Functions
BasicInterfaceCAPI (Index) BasicInputOutputCAPI(Index) VoidArrayCAPI(ArrayOfIndex) BasicInterfaceCAPI(ArrayOfIndex) BasicInputOutputCAPI(ArrayOfIndex) VoidArrayCAPI(ArrayOfArrayOfIndex) BasicInterfaceCAPI(ArrayOfArrayOfIndex) BasicInputOutputCAPI(ArrayOfArrayOfIndex) DLL_PUBLIC Index getIndex(void *)
DLL_PUBLIC void setIndex (void *, Index)
BasicInterfaceCAPI (Numeric) BasicInputOutputCAPI(Numeric) VoidArrayCAPI(ArrayOfNumeric) BasicInterfaceCAPI(ArrayOfNumeric) BasicInputOutputCAPI(ArrayOfNumeric) DLL_PUBLIC Numeric getNumeric(void *data)
DLL_PUBLIC void setNumeric (void *data, Numeric newval)
BasicInterfaceCAPI (ZeemanModel) GetterSetterCAPI(ZeemanModel
Numeric GetterSetterCAPI (ZeemanModel, gl, Numeric) BasicInterfaceCAPI(Rational) BasicInputOutputCAPI(Rational) GetterSetterCAPI(Rational
Numeric Index GetterSetterCAPI (Rational, Denom, Index) DLL_PUBLIC void simplifyRational(void *)
BasicInterfaceCAPI (LineShapeTemperatureModel) StringEnumPointersCAPI(LineShapeTemperatureModel) BasicInterfaceCAPI(LineShapeModelParameters) VoidStructGetterCAPI(LineShapeModelParameters
type VoidStructGetterCAPI (LineShapeModelParameters, X0) VoidStructGetterCAPI(LineShapeModelParameters
type X1 VoidStructGetterCAPI (LineShapeModelParameters, X2) VoidStructGetterCAPI(LineShapeModelParameters
type X1 X3 BasicInterfaceCAPI (LineShapeSingleSpeciesModel) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 VoidGetterCAPI (LineShapeSingleSpeciesModel, D0) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 VoidGetterCAPI (LineShapeSingleSpeciesModel, D2) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC VoidGetterCAPI (LineShapeSingleSpeciesModel, ETA) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC Y VoidGetterCAPI (LineShapeSingleSpeciesModel, G) VoidGetterCAPI(LineShapeSingleSpeciesModel
type X1 X3 G0 G2 FVC Y DV BasicInterfaceCAPI (LineShapeType) StringEnumPointersCAPI(LineShapeType) BasicInterfaceCAPI(LineShapeModel) VoidArrayCAPI(LineShapeModel) BasicInterfaceCAPI(AbsorptionSingleLine) GetterSetterCAPI(AbsorptionSingleLine
type X1 X3 G0 G2 FVC Y DV Numeric GetterSetterCAPI (AbsorptionSingleLine, I0, Numeric) GetterSetterCAPI(AbsorptionSingleLine
type X1 X3 G0 G2 FVC Y DV Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine, g_low, Numeric) GetterSetterCAPI(AbsorptionSingleLine
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine, A, Numeric) VoidGetterCAPI(AbsorptionSingleLine
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman VoidGetterCAPI (AbsorptionSingleLine, LineShape) VoidArrayElemCAPI(AbsorptionSingleLine
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman LowerQuantumNumbers VoidArrayElemCAPI (AbsorptionSingleLine, UpperQuantumNumbers) BasicInterfaceCAPI(QuantumNumberType) StringEnumPointersCAPI(QuantumNumberType) BasicInterfaceCAPI(QuantumNumbers) DLL_PUBLIC void *getelemQuantumNumbers(Index
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman LowerQuantumNumbers void *DLL_PUBLIC Index sizeQuantumNumbers ()
DLL_PUBLIC Index string2quantumnumbersindex (char *)
DLL_PUBLIC void * getQuantumNumbersString (void *)
DLL_PUBLIC void * createSpecies ()
DLL_PUBLIC void deleteSpecies (void *)
DLL_PUBLIC void printSpecies (void *)
DLL_PUBLIC int setSpeciesLongName (void *, char *)
DLL_PUBLIC int setSpeciesShortName (void *, char *)
DLL_PUBLIC void * getSpeciesLongName (void *)
DLL_PUBLIC void * getSpeciesShortName (void *)
VoidArrayCAPI (ArrayOfSpecies) BasicInputOutputCAPI(ArrayOfSpecies) BasicInterfaceCAPI(ArrayOfSpecies) BasicInterfaceCAPI(SpeciesIsotopeRecord) DLL_PUBLIC Index getIndexSpeciesIsotopeRecordFromNames(char *spec
DLL_PUBLIC Index getIndexSpeciesIsotopeRecordFromData (void *)
DLL_PUBLIC int setSpeciesIsotopeRecordToIndex (void *, Index)
DLL_PUBLIC void * getSpeciesSpeciesIsotopeRecord (void *)
DLL_PUBLIC void * getIsotnameSpeciesIsotopeRecord (void *)
DLL_PUBLIC Numeric getMassSpeciesIsotopeRecord (void *)
DLL_PUBLIC Index getGSpeciesIsotopeRecord (void *)
DLL_PUBLIC Index nelemSpeciesIsotopeRecordDefined ()
BasicInterfaceCAPI (SpeciesIsotopologueRatios) BasicInputOutputCAPI(SpeciesIsotopologueRatios) DLL_PUBLIC Numeric *getdataSpeciesIsotopologueRatios(void *)
BasicInterfaceCAPI (QuantumIdentifierType) StringEnumPointersCAPI(QuantumIdentifierType) BasicInterfaceCAPI(QuantumIdentifier) BasicInputOutputCAPI(QuantumIdentifier) VoidStructGetterCAPI(QuantumIdentifier
type VoidStructGetterCAPI (QuantumIdentifier, spec_ind) VoidStructGetterCAPI(QuantumIdentifier
type upp VoidStructGetterCAPI (QuantumIdentifier, low) DLL_PUBLIC Index fromstringQuantumIdentifier(void *
type upp char * BasicInterfaceCAPI (ArrayOfQuantumIdentifier) BasicInputOutputCAPI(ArrayOfQuantumIdentifier) VoidArrayCAPI(ArrayOfQuantumIdentifier) BasicInterfaceCAPI(SpeciesTagType) StringEnumPointersCAPI(SpeciesTagType) BasicInterfaceCAPI(SpeciesTag) BasicInputOutputCAPI(SpeciesTag) VoidStructGetterCAPI(SpeciesTag
type upp char spec_ind VoidStructGetterCAPI (SpeciesTag, lower_freq) VoidStructGetterCAPI(SpeciesTag
type upp char spec_ind upper_freq VoidStructGetterCAPI (SpeciesTag, type) VoidStructGetterCAPI(SpeciesTag
type upp char spec_ind upper_freq cia_2nd_species VoidStructGetterCAPI (SpeciesTag, cia_dataset_index) VoidArrayCAPI(ArrayOfSpeciesTag) BasicInterfaceCAPI(ArrayOfSpeciesTag) BasicInputOutputCAPI(ArrayOfSpeciesTag) VoidArrayCAPI(ArrayOfArrayOfSpeciesTag) BasicInterfaceCAPI(ArrayOfArrayOfSpeciesTag) BasicInputOutputCAPI(ArrayOfArrayOfSpeciesTag) DLL_PUBLIC void *getNameSpeciesTag(void *)
DLL_PUBLIC Index setSpeciesTag (void *, char *)
BasicInterfaceCAPI (AbsorptionNormalizationType) StringEnumPointersCAPI(AbsorptionNormalizationType) BasicInterfaceCAPI(AbsorptionPopulationType) StringEnumPointersCAPI(AbsorptionPopulationType) BasicInterfaceCAPI(AbsorptionMirroringType) StringEnumPointersCAPI(AbsorptionMirroringType) BasicInterfaceCAPI(AbsorptionCutoffType) StringEnumPointersCAPI(AbsorptionCutoffType) BasicInterfaceCAPI(AbsorptionLines) BasicInputOutputCAPI(AbsorptionLines) GetterSetterCAPI(AbsorptionLines
bool GetterSetterCAPI (AbsorptionLines, Bath, bool) VoidGetterCAPI(AbsorptionLines
bool Cutoff VoidGetterCAPI (AbsorptionLines, LineShapeType) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring VoidGetterCAPI (AbsorptionLines, Population) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization GetterSetterCAPI (AbsorptionLines, T0, Numeric) GetterSetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric GetterSetterCAPI (AbsorptionLines, LinemixingLimit, Numeric) VoidGetterCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric QuantumIdentity VoidGetterCAPI (AbsorptionLines, BroadeningSpecies) VoidArrayElemCAPI(AbsorptionLines
bool Cutoff Mirroring Normalization Numeric QuantumIdentity AllLines VoidArrayCAPI (ArrayOfAbsorptionLines) BasicInterfaceCAPI(ArrayOfAbsorptionLines) BasicInputOutputCAPI(ArrayOfAbsorptionLines) VoidArrayCAPI(ArrayOfArrayOfAbsorptionLines) BasicInterfaceCAPI(ArrayOfArrayOfAbsorptionLines) BasicInputOutputCAPI(ArrayOfArrayOfAbsorptionLines) DLL_PUBLIC Index sizeLocalQuantaAbsorptionLines(void *data)
DLL_PUBLIC void resizeLocalQuantaAbsorptionLines (Index n, void *data)
DLL_PUBLIC Index getLocalQuantaAbsorptionLines (Index i, void *data)
DLL_PUBLIC void setLocalQuantaAbsorptionLines (Index i, void *data, Index newval)
DLL_PUBLIC void printmetaAbsorptionLines (void *)
DLL_PUBLIC Index isAbsorptionLinesOK (void *)
DLL_PUBLIC void * getSpeciesNameAbsorptionLines (void *)
BasicInterfaceCAPI (EnergyLevelMap) BasicInputOutputCAPI(EnergyLevelMap) EnumGetterSetterCAPI(EnergyLevelMap
EnergyLevelMapType VoidGetterCAPI (EnergyLevelMap, Levels) VoidGetterCAPI(EnergyLevelMap
EnergyLevelMapType Energies VoidGetterCAPI (EnergyLevelMap, Data) DLL_PUBLIC bool getOKEnergyLevelMap(void *)
BasicInterfaceCAPI (Vector) BasicInputOutputCAPI(Vector) VoidArrayCAPI(ArrayOfVector) BasicInterfaceCAPI(ArrayOfVector) BasicInputOutputCAPI(ArrayOfVector) VoidArrayCAPI(ArrayOfArrayOfVector) BasicInterfaceCAPI(ArrayOfArrayOfVector) BasicInputOutputCAPI(ArrayOfArrayOfVector) DLL_PUBLIC void resizeVector(Index
void *DLL_PUBLIC Index nelemVector (void *)
DLL_PUBLIC Numeric * getDataVector (void *)
BasicInterfaceCAPI (Matrix) BasicInputOutputCAPI(Matrix) VoidArrayCAPI(ArrayOfMatrix) BasicInterfaceCAPI(ArrayOfMatrix) BasicInputOutputCAPI(ArrayOfMatrix) VoidArrayCAPI(ArrayOfArrayOfMatrix) BasicInterfaceCAPI(ArrayOfArrayOfMatrix) BasicInputOutputCAPI(ArrayOfArrayOfMatrix) DLL_PUBLIC void resizeMatrix(Index
void *DLL_PUBLIC Index rowsMatrix (void *)
DLL_PUBLIC Index colsMatrix (void *)
DLL_PUBLIC Numeric * getDataMatrix (void *)
BasicInterfaceCAPI (Tensor3) BasicInputOutputCAPI(Tensor3) VoidArrayCAPI(ArrayOfTensor3) BasicInterfaceCAPI(ArrayOfTensor3) BasicInputOutputCAPI(ArrayOfTensor3) VoidArrayCAPI(ArrayOfArrayOfTensor3) BasicInterfaceCAPI(ArrayOfArrayOfTensor3) BasicInputOutputCAPI(ArrayOfArrayOfTensor3) DLL_PUBLIC void resizeTensor3(Index
void *DLL_PUBLIC Index pagesTensor3 (void *)
DLL_PUBLIC Index rowsTensor3 (void *)
DLL_PUBLIC Index colsTensor3 (void *)
DLL_PUBLIC Numeric * getDataTensor3 (void *)
BasicInterfaceCAPI (Tensor4) BasicInputOutputCAPI(Tensor4) VoidArrayCAPI(ArrayOfTensor4) BasicInterfaceCAPI(ArrayOfTensor4) BasicInputOutputCAPI(ArrayOfTensor4) DLL_PUBLIC void resizeTensor4(Index
void *DLL_PUBLIC Index booksTensor4 (void *)
DLL_PUBLIC Index pagesTensor4 (void *)
DLL_PUBLIC Index rowsTensor4 (void *)
DLL_PUBLIC Index colsTensor4 (void *)
DLL_PUBLIC Numeric * getDataTensor4 (void *)
BasicInterfaceCAPI (Tensor5) BasicInputOutputCAPI(Tensor5) VoidArrayCAPI(ArrayOfTensor5) BasicInterfaceCAPI(ArrayOfTensor5) BasicInputOutputCAPI(ArrayOfTensor5) DLL_PUBLIC void resizeTensor5(Index
void *DLL_PUBLIC Index shelvesTensor5 (void *)
DLL_PUBLIC Index booksTensor5 (void *)
DLL_PUBLIC Index pagesTensor5 (void *)
DLL_PUBLIC Index rowsTensor5 (void *)
DLL_PUBLIC Index colsTensor5 (void *)
DLL_PUBLIC Numeric * getDataTensor5 (void *)
BasicInterfaceCAPI (Tensor6) BasicInputOutputCAPI(Tensor6) VoidArrayCAPI(ArrayOfTensor6) BasicInterfaceCAPI(ArrayOfTensor6) BasicInputOutputCAPI(ArrayOfTensor6) VoidArrayCAPI(ArrayOfArrayOfTensor6) BasicInterfaceCAPI(ArrayOfArrayOfTensor6) BasicInputOutputCAPI(ArrayOfArrayOfTensor6) DLL_PUBLIC void resizeTensor6(Index
void *DLL_PUBLIC Index vitrinesTensor6 (void *)
DLL_PUBLIC Index shelvesTensor6 (void *)
DLL_PUBLIC Index booksTensor6 (void *)
DLL_PUBLIC Index pagesTensor6 (void *)
DLL_PUBLIC Index rowsTensor6 (void *)
DLL_PUBLIC Index colsTensor6 (void *)
DLL_PUBLIC Numeric * getDataTensor6 (void *)
BasicInterfaceCAPI (Tensor7) BasicInputOutputCAPI(Tensor7) VoidArrayCAPI(ArrayOfTensor7) BasicInterfaceCAPI(ArrayOfTensor7) BasicInputOutputCAPI(ArrayOfTensor7) DLL_PUBLIC void resizeTensor7(Index
void *DLL_PUBLIC Index librariesTensor7 (void *)
DLL_PUBLIC Index vitrinesTensor7 (void *)
DLL_PUBLIC Index shelvesTensor7 (void *)
DLL_PUBLIC Index booksTensor7 (void *)
DLL_PUBLIC Index pagesTensor7 (void *)
DLL_PUBLIC Index rowsTensor7 (void *)
DLL_PUBLIC Index colsTensor7 (void *)
DLL_PUBLIC Numeric * getDataTensor7 (void *)
BasicInterfaceCAPI (PropagationMatrix) BasicInputOutputCAPI(PropagationMatrix) VoidGetterCAPI(PropagationMatrix
Data VoidArrayCAPI (ArrayOfPropagationMatrix) BasicInterfaceCAPI(ArrayOfPropagationMatrix) BasicInputOutputCAPI(ArrayOfPropagationMatrix) VoidArrayCAPI(ArrayOfArrayOfPropagationMatrix) BasicInterfaceCAPI(ArrayOfArrayOfPropagationMatrix) BasicInputOutputCAPI(ArrayOfArrayOfPropagationMatrix) DLL_PUBLIC Index stokesPropagationMatrix(void *)
DLL_PUBLIC Index frequenciesPropagationMatrix (void *)
DLL_PUBLIC Index zenithsPropagationMatrix (void *)
DLL_PUBLIC Index azimuthsPropagationMatrix (void *)
DLL_PUBLIC Index setPropagationMatrix (void *, Index, Index, Index, Index, Numeric)
DLL_PUBLIC bool getOKPropagationMatrix (void *)
BasicInterfaceCAPI (StokesVector) BasicInputOutputCAPI(StokesVector) VoidGetterCAPI(StokesVector
Data VoidArrayCAPI (ArrayOfStokesVector) BasicInterfaceCAPI(ArrayOfStokesVector) BasicInputOutputCAPI(ArrayOfStokesVector) VoidArrayCAPI(ArrayOfArrayOfStokesVector) BasicInterfaceCAPI(ArrayOfArrayOfStokesVector) BasicInputOutputCAPI(ArrayOfArrayOfStokesVector) DLL_PUBLIC Index stokesStokesVector(void *)
DLL_PUBLIC Index frequenciesStokesVector (void *)
DLL_PUBLIC Index zenithsStokesVector (void *)
DLL_PUBLIC Index azimuthsStokesVector (void *)
DLL_PUBLIC Index setStokesVector (void *, Index, Index, Index, Index, Numeric)
DLL_PUBLIC bool getOKStokesVector (void *)
BasicInterfaceCAPI (String) BasicInputOutputCAPI(String) VoidArrayCAPI(ArrayOfString) BasicInterfaceCAPI(ArrayOfString) BasicInputOutputCAPI(ArrayOfString) VoidArrayCAPI(ArrayOfArrayOfString) BasicInterfaceCAPI(ArrayOfArrayOfString) BasicInputOutputCAPI(ArrayOfArrayOfString) DLL_PUBLIC void setString(void *data
DLL_PUBLIC char * getString (void *data)
BasicInterfaceCAPI (GridPos) BasicInputOutputCAPI(GridPos) VoidStructGetterCAPI(GridPos
idx VoidStructGetterCAPI (GridPos, fd) VoidArrayCAPI(ArrayOfGridPos) BasicInterfaceCAPI(ArrayOfGridPos) BasicInputOutputCAPI(ArrayOfGridPos) BasicInterfaceCAPI(LagrangeInterpolation) VoidStructGetterCAPI(LagrangeInterpolation
idx pos VoidStructGetterCAPI (LagrangeInterpolation, lx) VoidStructGetterCAPI(LagrangeInterpolation
idx pos dlx VoidArrayCAPI (ArrayOfLagrangeInterpolation) BasicInterfaceCAPI(ArrayOfLagrangeInterpolation) BasicInputOutputCAPI(ArrayOfLagrangeInterpolation) BasicInterfaceCAPI(Ppath) BasicInputOutputCAPI(Ppath) VoidStructGetterCAPI(Ppath
idx pos dlx dim VoidStructGetterCAPI (Ppath, np) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant VoidStructGetterCAPI (Ppath, background) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos VoidStructGetterCAPI (Ppath, start_los) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep VoidStructGetterCAPI (Ppath, pos) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los VoidStructGetterCAPI (Ppath, r) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los lstep VoidStructGetterCAPI (Ppath, end_pos) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los lstep end_los VoidStructGetterCAPI (Ppath, end_lstep) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal VoidStructGetterCAPI (Ppath, ngroup) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p VoidStructGetterCAPI (Ppath, gp_lat) VoidStructGetterCAPI(Ppath
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon VoidArrayCAPI (ArrayOfPpath) BasicInterfaceCAPI(ArrayOfPpath) BasicInputOutputCAPI(ArrayOfPpath) BasicInterfaceCAPI(TransmissionMatrix) BasicInputOutputCAPI(TransmissionMatrix) VoidArrayCAPI(ArrayOfTransmissionMatrix) BasicInterfaceCAPI(ArrayOfTransmissionMatrix) BasicInputOutputCAPI(ArrayOfTransmissionMatrix) VoidArrayCAPI(ArrayOfArrayOfTransmissionMatrix) BasicInterfaceCAPI(ArrayOfArrayOfTransmissionMatrix) BasicInputOutputCAPI(ArrayOfArrayOfTransmissionMatrix) DLL_PUBLIC Numeric *getMat1TransmissionMatrix(Index
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon void *DLL_PUBLIC Numeric * getMat2TransmissionMatrix (Index, void *)
DLL_PUBLIC Numeric * getMat3TransmissionMatrix (Index, void *)
DLL_PUBLIC Numeric * getMat4TransmissionMatrix (Index, void *)
DLL_PUBLIC void setTransmissionMatrix (void *, Index, Index)
DLL_PUBLIC Index getStokesDimTransmissionMatrix (void *)
DLL_PUBLIC Index getFrequenciesTransmissionMatrix (void *)
BasicInterfaceCAPI (RadiationVector) BasicInputOutputCAPI(RadiationVector) VoidArrayCAPI(ArrayOfRadiationVector) BasicInterfaceCAPI(ArrayOfRadiationVector) BasicInputOutputCAPI(ArrayOfRadiationVector) VoidArrayCAPI(ArrayOfArrayOfRadiationVector) BasicInterfaceCAPI(ArrayOfArrayOfRadiationVector) BasicInputOutputCAPI(ArrayOfArrayOfRadiationVector) DLL_PUBLIC Numeric *getVec1RadiationVector(Index
void *DLL_PUBLIC Numeric * getVec2RadiationVector (Index, void *)
DLL_PUBLIC Numeric * getVec3RadiationVector (Index, void *)
DLL_PUBLIC Numeric * getVec4RadiationVector (Index, void *)
DLL_PUBLIC void setRadiationVector (void *, Index, Index)
DLL_PUBLIC Index getStokesDimRadiationVector (void *)
DLL_PUBLIC Index getFrequenciesRadiationVector (void *)
BasicInterfaceCAPI (GriddedField1) BasicInputOutputCAPI(GriddedField1) VoidArrayCAPI(ArrayOfGriddedField1) BasicInterfaceCAPI(ArrayOfGriddedField1) BasicInputOutputCAPI(ArrayOfGriddedField1) VoidArrayCAPI(ArrayOfArrayOfGriddedField1) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField1) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField1) DLL_PUBLIC Index get_dimGriddedField1(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField1 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField1 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField1 (void *data)
DLL_PUBLIC void set_nameGriddedField1 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField1 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField1 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField1 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField1 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField1 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField1 (void *data)
DLL_PUBLIC bool checksizeGriddedField1 (void *data)
BasicInterfaceCAPI (GriddedField2) BasicInputOutputCAPI(GriddedField2) VoidArrayCAPI(ArrayOfGriddedField2) BasicInterfaceCAPI(ArrayOfGriddedField2) BasicInputOutputCAPI(ArrayOfGriddedField2) VoidArrayCAPI(ArrayOfArrayOfGriddedField2) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField2) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField2) DLL_PUBLIC Index get_dimGriddedField2(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField2 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField2 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField2 (void *data)
DLL_PUBLIC void set_nameGriddedField2 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField2 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField2 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField2 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField2 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField2 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField2 (void *data)
DLL_PUBLIC bool checksizeGriddedField2 (void *data)
BasicInterfaceCAPI (GriddedField3) BasicInputOutputCAPI(GriddedField3) VoidArrayCAPI(ArrayOfGriddedField3) BasicInterfaceCAPI(ArrayOfGriddedField3) BasicInputOutputCAPI(ArrayOfGriddedField3) VoidArrayCAPI(ArrayOfArrayOfGriddedField3) BasicInterfaceCAPI(ArrayOfArrayOfGriddedField3) BasicInputOutputCAPI(ArrayOfArrayOfGriddedField3) DLL_PUBLIC Index get_dimGriddedField3(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField3 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField3 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField3 (void *data)
DLL_PUBLIC void set_nameGriddedField3 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField3 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField3 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField3 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField3 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField3 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField3 (void *data)
DLL_PUBLIC bool checksizeGriddedField3 (void *data)
BasicInterfaceCAPI (GriddedField4) BasicInputOutputCAPI(GriddedField4) VoidArrayCAPI(ArrayOfGriddedField4) BasicInterfaceCAPI(ArrayOfGriddedField4) BasicInputOutputCAPI(ArrayOfGriddedField4) DLL_PUBLIC Index get_dimGriddedField4(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField4 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField4 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField4 (void *data)
DLL_PUBLIC void set_nameGriddedField4 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField4 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField4 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField4 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField4 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField4 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField4 (void *data)
DLL_PUBLIC bool checksizeGriddedField4 (void *data)
BasicInterfaceCAPI (GriddedField5) BasicInputOutputCAPI(GriddedField5) DLL_PUBLIC Index get_dimGriddedField5(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField5 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField5 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField5 (void *data)
DLL_PUBLIC void set_nameGriddedField5 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField5 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField5 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField5 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField5 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField5 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField5 (void *data)
DLL_PUBLIC bool checksizeGriddedField5 (void *data)
BasicInterfaceCAPI (GriddedField6) BasicInputOutputCAPI(GriddedField6) DLL_PUBLIC Index get_dimGriddedField6(void *data)
DLL_PUBLIC Index get_grid_typeIndexGriddedField6 (Index i, void *data)
DLL_PUBLIC Index get_grid_sizeGriddedField6 (Index i, void *data)
DLL_PUBLIC char * get_nameGriddedField6 (void *data)
DLL_PUBLIC void set_nameGriddedField6 (void *data, char *newdata)
DLL_PUBLIC char * get_grid_nameGriddedField6 (Index i, void *data)
DLL_PUBLIC void set_grid_nameGriddedField6 (Index i, void *data, char *newdata)
DLL_PUBLIC void * get_numeric_gridGriddedField6 (Index i, void *data)
DLL_PUBLIC void * get_string_gridGriddedField6 (Index i, void *data)
DLL_PUBLIC void set_gridGriddedField6 (Index i, void *data, void *newdata, bool NumericType)
DLL_PUBLIC void * dataGriddedField6 (void *data)
DLL_PUBLIC bool checksizeGriddedField6 (void *data)
BasicInterfaceCAPI (CIARecord) BasicInputOutputCAPI(CIARecord) VoidGetterCAPI(CIARecord
Data VoidArrayCAPI (ArrayOfCIARecord) BasicInterfaceCAPI(ArrayOfCIARecord) BasicInputOutputCAPI(ArrayOfCIARecord) DLL_PUBLIC void *getSpecies1CIARecord(void *)
DLL_PUBLIC void * getSpecies2CIARecord (void *)
DLL_PUBLIC void setSpeciesCIARecord (void *, void *, void *)
BasicInterfaceCAPI (Verbosity) BasicInputOutputCAPI(Verbosity) DLL_PUBLIC Index getAgendaVerbosity(void *)
DLL_PUBLIC Index getScreenVerbosity (void *)
DLL_PUBLIC Index getFileVerbosity (void *)
DLL_PUBLIC bool getMainVerbosity (void *)
DLL_PUBLIC void setVerbosity (void *, Index, Index, Index, bool)
BasicInterfaceCAPI (TessemNN) BasicInputOutputCAPI(TessemNN) VoidStructGetterCAPI(TessemNN
nb_inputs VoidStructGetterCAPI (TessemNN, nb_outputs) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache VoidStructGetterCAPI (TessemNN, b1) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 VoidStructGetterCAPI (TessemNN, w1) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 VoidStructGetterCAPI (TessemNN, x_min) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 x_max VoidStructGetterCAPI (TessemNN, y_min) VoidStructGetterCAPI(TessemNN
nb_inputs nb_cache b2 w2 x_max y_max BasicInterfaceCAPI (SingleScatteringData) BasicInputOutputCAPI(SingleScatteringData) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype VoidStructGetterCAPI (SingleScatteringData, description) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid VoidStructGetterCAPI (SingleScatteringData, T_grid) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid VoidStructGetterCAPI (SingleScatteringData, aa_grid) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data VoidStructGetterCAPI (SingleScatteringData, ext_mat_data) VoidStructGetterCAPI(SingleScatteringData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data VoidArrayCAPI (ArrayOfSingleScatteringData) BasicInterfaceCAPI(ArrayOfSingleScatteringData) BasicInputOutputCAPI(ArrayOfSingleScatteringData) VoidArrayCAPI(ArrayOfArrayOfSingleScatteringData) BasicInterfaceCAPI(ArrayOfArrayOfSingleScatteringData) BasicInputOutputCAPI(ArrayOfArrayOfSingleScatteringData) BasicInterfaceCAPI(ScatteringMetaData) BasicInputOutputCAPI(ScatteringMetaData) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description VoidStructGetterCAPI (ScatteringMetaData, source) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index VoidStructGetterCAPI (ScatteringMetaData, mass) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max VoidStructGetterCAPI (ScatteringMetaData, diameter_volume_equ) VoidStructGetterCAPI(ScatteringMetaData
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max diameter_area_equ_aerodynamical VoidArrayCAPI (ArrayOfScatteringMetaData) BasicInterfaceCAPI(ArrayOfScatteringMetaData) BasicInputOutputCAPI(ArrayOfScatteringMetaData) VoidArrayCAPI(ArrayOfArrayOfScatteringMetaData) BasicInterfaceCAPI(ArrayOfArrayOfScatteringMetaData) BasicInputOutputCAPI(ArrayOfArrayOfScatteringMetaData) BasicInterfaceCAPI(Timer) BasicInputOutputCAPI(Timer) DLL_PUBLIC bool getrunningTimer(void *)
DLL_PUBLIC bool getfinishedTimer (void *)
DLL_PUBLIC Index getcputime_start_utimeTimer (void *)
DLL_PUBLIC Index getcputime_start_stimeTimer (void *)
DLL_PUBLIC Index getcputime_start_cutimeTimer (void *)
DLL_PUBLIC Index getcputime_start_cstimeTimer (void *)
DLL_PUBLIC Index getrealtime_startTimer (void *)
DLL_PUBLIC Index getcputime_end_utimeTimer (void *)
DLL_PUBLIC Index getcputime_end_stimeTimer (void *)
DLL_PUBLIC Index getcputime_end_cutimeTimer (void *)
DLL_PUBLIC Index getcputime_end_cstimeTimer (void *)
DLL_PUBLIC Index getrealtime_endTimer (void *)
DLL_PUBLIC void setrunningTimer (void *, bool)
DLL_PUBLIC void setfinishedTimer (void *, bool)
DLL_PUBLIC void setcputime_start_utimeTimer (void *, Index)
DLL_PUBLIC void setcputime_start_stimeTimer (void *, Index)
DLL_PUBLIC void setcputime_start_cutimeTimer (void *, Index)
DLL_PUBLIC void setcputime_start_cstimeTimer (void *, Index)
DLL_PUBLIC void setrealtime_startTimer (void *, Index)
DLL_PUBLIC void setcputime_end_utimeTimer (void *, Index)
DLL_PUBLIC void setcputime_end_stimeTimer (void *, Index)
DLL_PUBLIC void setcputime_end_cutimeTimer (void *, Index)
DLL_PUBLIC void setcputime_end_cstimeTimer (void *, Index)
DLL_PUBLIC void setrealtime_endTimer (void *, Index)
DLL_PUBLIC bool supportTimer ()
DLL_PUBLIC Index tickTimer ()
BasicInterfaceCAPI (TelsemAtlas) BasicInputOutputCAPI(TelsemAtlas) VoidGetterCAPI(TelsemAtlas
DataCount VoidGetterCAPI (TelsemAtlas, ChannelCount) VoidGetterCAPI(TelsemAtlas
DataCount Name VoidGetterCAPI (TelsemAtlas, Month) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat VoidGetterCAPI (TelsemAtlas, Cells) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells VoidGetterCAPI (TelsemAtlas, Emis) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err VoidGetterCAPI (TelsemAtlas, Correlations) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err Classes1 VoidGetterCAPI (TelsemAtlas, Classes2) VoidGetterCAPI(TelsemAtlas
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber VoidGetterCAPI (TelsemAtlas, Correspondance) VoidArrayCAPI(ArrayOfTelsemAtlas) BasicInterfaceCAPI(ArrayOfTelsemAtlas) BasicInputOutputCAPI(ArrayOfTelsemAtlas) DLL_PUBLIC Numeric getA0_K0TelsemAtlas(Index
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber void *DLL_PUBLIC Numeric getA0_K1TelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getA0_K2TelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getA0_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getA1_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getA2_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getA3_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getB0_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getB1_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getB2_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getB3_EVEHTelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getRAPPORT43_32TelsemAtlas (Index, void *)
DLL_PUBLIC Numeric getRAPPORT54_43TelsemAtlas (Index, void *)
BasicInterfaceCAPI (MCAntenna) BasicInputOutputCAPI(MCAntenna) VoidGetterCAPI(MCAntenna
saa VoidGetterCAPI (MCAntenna, sza) VoidGetterCAPI(MCAntenna
saa aag VoidGetterCAPI (MCAntenna, zag) VoidGetterCAPI(MCAntenna
saa aag G DLL_PUBLIC Index getTypeMCAntenna (void *)
DLL_PUBLIC Index setTypeMCAntenna (void *, Index)
BasicInterfaceCAPI (GasAbsLookup) BasicInputOutputCAPI(GasAbsLookup) VoidGetterCAPI(GasAbsLookup
Species VoidGetterCAPI (GasAbsLookup, NonLinearSpecies) VoidGetterCAPI(GasAbsLookup
Species Fgrid VoidGetterCAPI (GasAbsLookup, FLAGDefault) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VoidGetterCAPI (GasAbsLookup, LogPgrid) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs VoidGetterCAPI (GasAbsLookup, Tref) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs Tpert VoidGetterCAPI (GasAbsLookup, NLSPert) VoidGetterCAPI(GasAbsLookup
Species Fgrid Pgrid VMRs Tpert Xsec BasicInterfaceCAPI (XsecRecord) BasicInputOutputCAPI(XsecRecord) DLL_PUBLIC void *getSpeciesXsecRecord(void *)
DLL_PUBLIC void setSpeciesXsecRecord (void *, void *)
VoidGetterCAPI (XsecRecord, Coeffs) VoidGetterCAPI(XsecRecord
RefPressure VoidGetterCAPI (XsecRecord, RefTemperature) VoidGetterCAPI(XsecRecord
RefPressure Fgrids VoidGetterCAPI (XsecRecord, Xsecs) VoidGetterCAPI(XsecRecord
RefPressure Fgrids TemperatureSlope VoidGetterCAPI (XsecRecord, TemperatureIntersect) VoidArrayCAPI(ArrayOfXsecRecord) BasicInterfaceCAPI(ArrayOfXsecRecord) BasicInputOutputCAPI(ArrayOfXsecRecord) BasicInterfaceCAPI(Sparse) BasicInputOutputCAPI(Sparse) VoidArrayCAPI(ArrayOfSparse) BasicInterfaceCAPI(ArrayOfSparse) BasicInputOutputCAPI(ArrayOfSparse) DLL_PUBLIC void resizeSparse(Index
RefPressure Fgrids TemperatureSlope void *DLL_PUBLIC Index rowsSparse (void *)
DLL_PUBLIC Index colsSparse (void *)
DLL_PUBLIC Index sizeSparse (void *)
DLL_PUBLIC int * rowsptrSparse (void *)
DLL_PUBLIC int * colsptrSparse (void *)
DLL_PUBLIC Numeric * getDataSparse (void *)
DLL_PUBLIC void setDataSparse (void *, Index, Index, Numeric)
BasicInterfaceCAPI (CovarianceMatrix) BasicInputOutputCAPI(CovarianceMatrix) VoidArrayElemCAPI(CovarianceMatrix
get_blocks VoidArrayElemCAPI (CovarianceMatrix, get_inverse_blocks) BasicInterfaceCAPI(Any) BasicInputOutputCAPI(Any) BasicInterfaceCAPI(Agenda) BasicInputOutputCAPI(Agenda) VoidArrayCAPI(ArrayOfAgenda) BasicInterfaceCAPI(ArrayOfAgenda) BasicInputOutputCAPI(ArrayOfAgenda) BasicInterfaceCAPI(JacobianTarget) BasicInputOutputCAPI(JacobianTarget) VoidGetterCAPI(JacobianTarget
get_blocks Perturbation VoidGetterCAPI (JacobianTarget, QuantumIdentity) VoidGetterCAPI(JacobianTarget
get_blocks Perturbation StringKey VoidGetterCAPI (JacobianTarget, SpeciesList) StringEnumGetterSetterCAPI(JacobianTarget
get_blocks Perturbation StringKey TargetType StringEnumGetterSetterCAPI (JacobianTarget, TargetSubType) VoidArrayCAPI(ArrayOfJacobianTarget) BasicInterfaceCAPI(ArrayOfJacobianTarget) BasicInputOutputCAPI(ArrayOfJacobianTarget) BasicInterfaceCAPI(RetrievalQuantity) BasicInputOutputCAPI(RetrievalQuantity) VoidGetterCAPI(RetrievalQuantity
get_blocks Perturbation StringKey TargetType SubTag VoidGetterCAPI (RetrievalQuantity, SubSubTag) VoidGetterCAPI(RetrievalQuantity
get_blocks Perturbation StringKey TargetType SubTag Mode VoidGetterCAPI (RetrievalQuantity, Grids) VoidGetterCAPI(RetrievalQuantity
get_blocks Perturbation StringKey TargetType SubTag Mode Target VoidGetterCAPI (RetrievalQuantity, TransformationFunc) VoidGetterCAPI(RetrievalQuantity
get_blocks Perturbation StringKey TargetType SubTag Mode Target TFuncParameters VoidGetterCAPI (RetrievalQuantity, Transformation) VoidGetterCAPI(RetrievalQuantity
get_blocks Perturbation StringKey TargetType SubTag Mode Target TFuncParameters Offset GetterSetterCAPI (RetrievalQuantity, Integration, bool) VoidArrayCAPI(ArrayOfRetrievalQuantity) BasicInterfaceCAPI(ArrayOfRetrievalQuantity) BasicInputOutputCAPI(ArrayOfRetrievalQuantity) BasicInterfaceCAPI(Range) DLL_PUBLIC Index get_startRange(void *)
DLL_PUBLIC Index get_strideRange (void *)
DLL_PUBLIC Index get_extentRange (void *)
DLL_PUBLIC void setRange (void *, Index, Index, Index)
BasicInterfaceCAPI (Block) VoidGetterCAPI(Block
get_row_range VoidGetterCAPI (Block, get_column_range) VoidGetterCAPI(Block
get_row_range get_dense VoidGetterCAPI (Block, get_sparse) DLL_PUBLIC Index get_matrix_typeBlock(void *)
DLL_PUBLIC Index get_index1Block (void *)
DLL_PUBLIC Index get_index2Block (void *)
DLL_PUBLIC void set_indicesBlock (void *, Index, Index)
DLL_PUBLIC void set_matrixBlock (void *, void *, bool)
BasicInterfaceCAPI (Time) BasicInputOutputCAPI(Time) GetterSetterCAPI(Time
Numeric VoidArrayCAPI (ArrayOfTime) BasicInterfaceCAPI(ArrayOfTime) BasicInputOutputCAPI(ArrayOfTime) VoidArrayCAPI(ArrayOfArrayOfTime) BasicInterfaceCAPI(ArrayOfArrayOfTime) BasicInputOutputCAPI(ArrayOfArrayOfTime) DLL_PUBLIC Index setTimeFromString(void *
Numeric char *DLL_PUBLIC void setTime (void *, void *)
DLL_PUBLIC bool equalTime (void *, void *)
DLL_PUBLIC bool lessTime (void *, void *)
BasicInterfaceCAPI (HitranRelaxationMatrixData) BasicInputOutputCAPI(HitranRelaxationMatrixData) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr VoidStructGetterCAPI (HitranRelaxationMatrixData, B0rr) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq VoidStructGetterCAPI (HitranRelaxationMatrixData, B0rq) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp VoidStructGetterCAPI (HitranRelaxationMatrixData, B0rp) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr VoidStructGetterCAPI (HitranRelaxationMatrixData, B0qr) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr W0qq VoidStructGetterCAPI (HitranRelaxationMatrixData, B0qq) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr W0qq W0qp VoidStructGetterCAPI (HitranRelaxationMatrixData, B0qp) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr VoidStructGetterCAPI (HitranRelaxationMatrixData, B0pr) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq VoidStructGetterCAPI (HitranRelaxationMatrixData, B0pq) VoidStructGetterCAPI(HitranRelaxationMatrixData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp VoidStructGetterCAPI (HitranRelaxationMatrixData, B0pp) BasicInterfaceCAPI(PartitionFunctionsType) StringEnumPointersCAPI(PartitionFunctionsType) BasicInterfaceCAPI(PartitionFunctionsData) BasicInputOutputCAPI(PartitionFunctionsData) VoidStructGetterCAPI(PartitionFunctionsData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type VoidStructGetterCAPI (PartitionFunctionsData, data) BasicInterfaceCAPI(SpeciesErrorCorrectedSuddenData) VoidStructGetterCAPI(SpeciesErrorCorrectedSuddenData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData, scaling) VoidStructGetterCAPI(SpeciesErrorCorrectedSuddenData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData, lambda) VoidStructGetterCAPI(SpeciesErrorCorrectedSuddenData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta collisional_distance VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData, mass) BasicInterfaceCAPI(ErrorCorrectedSuddenData) VoidStructGetterCAPI(ErrorCorrectedSuddenData
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta collisional_distance id DLL_PUBLIC void * getErrorCorrectedSuddenData (void *, void *)
DLL_PUBLIC Index getnelemErrorCorrectedSuddenData (void *)
DLL_PUBLIC void * getSpeciesErrorCorrectedSuddenDataAtErrorCorrectedSuddenData (void *, Index)
BasicInterfaceCAPI (MapOfErrorCorrectedSuddenData) BasicInputOutputCAPI(MapOfErrorCorrectedSuddenData) DLL_PUBLIC void *getMapOfErrorCorrectedSuddenData(void *
void *DLL_PUBLIC Index getnelemMapOfErrorCorrectedSuddenData (void *)
DLL_PUBLIC void * getErrorCorrectedSuddenDataAtMapOfErrorCorrectedSuddenData (void *, Index)
DLL_PUBLIC Index string2filetypeindex (char *)
DLL_PUBLIC void * get_list_of_all_workspace_classes ()
Variables
gu
Numeric Nom
type X1 X3 G0 G2 FVC Y DV F0
type X1 X3 G0 G2 FVC Y DV Numeric E0
type X1 X3 G0 G2 FVC Y DV Numeric Numeric g_upp
char * isot
Self
bool Cutoff Mirroring Normalization CutoffFreqValue
Type
Index
char * newdata
Seconds
Detailed Description
This file contains all declarations of the ARTS C API class interface.
Author
Richard Larsson larss.nosp@m.on@m.nosp@m.ps.mp.nosp@m.g.de
Date
2020-03-12
Definition in file arts_api_classes.h.
Macro Definition Documentation
BasicInputOutputCAPI
#define BasicInputOutputCAPI (TYPE)
Value:
__attribute__((visibility("default")))              \
Index xmlread##TYPE(void * data, char * filepath);  \
__attribute__((visibility("default")))              \
Index xmlsave##TYPE(void * data, char * filepath, Index filetype, Index clobber);
Definition at line 83 of file arts_api_classes.h.
BasicInterfaceCAPI
#define BasicInterfaceCAPI (TYPE)
Value:
__attribute__((visibility("default")))  \
void * create##TYPE();                  \
__attribute__((visibility("default")))  \
void delete##TYPE(void * data);         \
__attribute__((visibility("default")))  \
void print##TYPE(void * data);
Definition at line 41 of file arts_api_classes.h.
DLL_PUBLIC
#define DLL_PUBLIC __attribute__((visibility("default")))
Definition at line 35 of file arts_api_classes.h.
EnumGetterSetterCAPI
#define EnumGetterSetterCAPI (TYPE, VALUE, ENUM)
Value:
__attribute__((visibility("default")))              \
Index get##VALUE##TYPE(void * data);                \
__attribute__((visibility("default")))              \
Index set##VALUE##TYPE(void * data, Index newval);  \
__attribute__((visibility("default")))              \
Index string2index##VALUE##TYPE(void * data, char * newval);
Definition at line 57 of file arts_api_classes.h.
GetterSetterCAPI
#define GetterSetterCAPI (TYPE, VALUE, BASETYPE)
Value:
__attribute__((visibility("default")))          \
BASETYPE get##VALUE##TYPE(void * data);         \
__attribute__((visibility("default")))          \
void set##VALUE##TYPE(void * data, BASETYPE newval);
Definition at line 50 of file arts_api_classes.h.
REMOVE_DLL_PUBLIC
#define REMOVE_DLL_PUBLIC 1
Definition at line 36 of file arts_api_classes.h.
StringEnumGetterSetterCAPI
#define StringEnumGetterSetterCAPI (TYPE, ELEM)
Value:
__attribute__((visibility("default")))                  \
bool enumset ## ELEM ## TYPE (void * data, char * in);  \
__attribute__((visibility("default")))                  \
void * enumget ## ELEM ## TYPE (void * data);
Definition at line 66 of file arts_api_classes.h.
StringEnumPointersCAPI
#define StringEnumPointersCAPI (ENUM)
Value:
__attribute__((visibility("default")))          \
void * get##ENUM##String(void *);               \
__attribute__((visibility("default")))          \
int set##ENUM##String(void *, char *);
Definition at line 107 of file arts_api_classes.h.
VoidArrayCAPI
#define VoidArrayCAPI (TYPE)
Value:
__attribute__((visibility("default")))      \
Index size##TYPE(void * data);              \
__attribute__((visibility("default")))      \
void resize##TYPE(Index n, void * data);    \
__attribute__((visibility("default")))      \
void * getelem##TYPE(Index i, void * data);
Definition at line 90 of file arts_api_classes.h.
VoidArrayElemCAPI
#define VoidArrayElemCAPI (TYPE, ELEM)
Value:
__attribute__((visibility("default")))          \
Index size##ELEM##TYPE(void * data);            \
__attribute__((visibility("default")))          \
void resize##ELEM##TYPE(Index n, void * data);  \
__attribute__((visibility("default")))          \
void * getelem##ELEM##TYPE(Index i, void * data);
Definition at line 99 of file arts_api_classes.h.
VoidGetterCAPI
#define VoidGetterCAPI (TYPE, VALUE)
Value:
__attribute__((visibility("default")))  \
void * get##VALUE##TYPE(void * data);
Definition at line 73 of file arts_api_classes.h.
VoidStructGetterCAPI
#define VoidStructGetterCAPI (TYPE, VALUE)
Value:
__attribute__((visibility("default")))    \
void * get##VALUE##TYPE(void * data);
Definition at line 78 of file arts_api_classes.h.
Function Documentation
azimuthsPropagationMatrix()
DLL_PUBLIC Index azimuthsPropagationMatrix (void * data)
Definition at line 701 of file arts_api_classes.cc.
References data.
azimuthsStokesVector()
DLL_PUBLIC Index azimuthsStokesVector (void * data)
Definition at line 727 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [1/42]
BasicInterfaceCAPI (AbsorptionNormalizationType)
BasicInterfaceCAPI() [2/42]
type upp char* BasicInterfaceCAPI (ArrayOfQuantumIdentifier)
BasicInterfaceCAPI() [3/42]
BasicInterfaceCAPI (Block)
BasicInterfaceCAPI() [4/42]
BasicInterfaceCAPI (CIARecord)
BasicInterfaceCAPI() [5/42]
BasicInterfaceCAPI (CovarianceMatrix)
BasicInterfaceCAPI() [6/42]
BasicInterfaceCAPI (EnergyLevelMap)
BasicInterfaceCAPI() [7/42]
BasicInterfaceCAPI (GasAbsLookup)
BasicInterfaceCAPI() [8/42]
BasicInterfaceCAPI (GriddedField1)
Definition at line 843 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [9/42]
BasicInterfaceCAPI (GriddedField2)
Definition at line 872 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [10/42]
BasicInterfaceCAPI (GriddedField3)
Definition at line 901 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [11/42]
BasicInterfaceCAPI (GriddedField4)
Definition at line 930 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [12/42]
BasicInterfaceCAPI (GriddedField5)
Definition at line 956 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [13/42]
BasicInterfaceCAPI (GriddedField6)
Definition at line 979 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [14/42]
BasicInterfaceCAPI (GridPos)
BasicInterfaceCAPI() [15/42]
BasicInterfaceCAPI (HitranRelaxationMatrixData)
BasicInterfaceCAPI() [16/42]
BasicInterfaceCAPI (Index)
Definition at line 173 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [17/42]
type X1 X3 BasicInterfaceCAPI (LineShapeSingleSpeciesModel)
BasicInterfaceCAPI() [18/42]
BasicInterfaceCAPI (LineShapeTemperatureModel)
BasicInterfaceCAPI() [19/42]
type X1 X3 G0 G2 FVC Y DV BasicInterfaceCAPI (LineShapeType)
BasicInterfaceCAPI() [20/42]
BasicInterfaceCAPI (MapOfErrorCorrectedSuddenData)
BasicInterfaceCAPI() [21/42]
BasicInterfaceCAPI (Matrix)
BasicInterfaceCAPI() [22/42]
BasicInterfaceCAPI (MCAntenna)
BasicInterfaceCAPI() [23/42]
BasicInterfaceCAPI (Numeric)
BasicInterfaceCAPI() [24/42]
BasicInterfaceCAPI (PropagationMatrix)
BasicInterfaceCAPI() [25/42]
BasicInterfaceCAPI (QuantumIdentifierType)
BasicInterfaceCAPI() [26/42]
BasicInterfaceCAPI (RadiationVector)
BasicInterfaceCAPI() [27/42]
nb_inputs nb_cache b2 w2 x_max y_max BasicInterfaceCAPI (SingleScatteringData)
BasicInterfaceCAPI() [28/42]
BasicInterfaceCAPI (SpeciesIsotopologueRatios)
Definition at line 376 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [29/42]
BasicInterfaceCAPI (StokesVector)
BasicInterfaceCAPI() [30/42]
BasicInterfaceCAPI (String)
BasicInterfaceCAPI() [31/42]
BasicInterfaceCAPI (TelsemAtlas)
BasicInterfaceCAPI() [32/42]
BasicInterfaceCAPI (Tensor3)
BasicInterfaceCAPI() [33/42]
BasicInterfaceCAPI (Tensor4)
BasicInterfaceCAPI() [34/42]
BasicInterfaceCAPI (Tensor5)
BasicInterfaceCAPI() [35/42]
BasicInterfaceCAPI (Tensor6)
BasicInterfaceCAPI() [36/42]
BasicInterfaceCAPI (Tensor7)
BasicInterfaceCAPI() [37/42]
BasicInterfaceCAPI (TessemNN)
BasicInterfaceCAPI() [38/42]
BasicInterfaceCAPI (Time)
BasicInterfaceCAPI() [39/42]
BasicInterfaceCAPI (Vector)
BasicInterfaceCAPI() [40/42]
BasicInterfaceCAPI (Verbosity)
BasicInterfaceCAPI() [41/42]
Species Fgrid Pgrid VMRs Tpert Xsec BasicInterfaceCAPI (XsecRecord)
Definition at line 1324 of file arts_api_classes.cc.
References data.
BasicInterfaceCAPI() [42/42]
BasicInterfaceCAPI (ZeemanModel)
booksTensor4()
void* DLL_PUBLIC Index booksTensor4 (void * data)
Definition at line 624 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor5()
DLL_PUBLIC Index booksTensor5 (void * data)
Definition at line 642 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor6()
DLL_PUBLIC Index booksTensor6 (void * data)
Definition at line 661 of file arts_api_classes.cc.
References data, and nbooks.
booksTensor7()
DLL_PUBLIC Index booksTensor7 (void * data)
Definition at line 681 of file arts_api_classes.cc.
References data, and nbooks.
checksizeGriddedField1()
DLL_PUBLIC bool checksizeGriddedField1 (void * data)
Definition at line 868 of file arts_api_classes.cc.
References data.
checksizeGriddedField2()
DLL_PUBLIC bool checksizeGriddedField2 (void * data)
Definition at line 897 of file arts_api_classes.cc.
References data.
checksizeGriddedField3()
DLL_PUBLIC bool checksizeGriddedField3 (void * data)
Definition at line 926 of file arts_api_classes.cc.
References data.
checksizeGriddedField4()
DLL_PUBLIC bool checksizeGriddedField4 (void * data)
Definition at line 952 of file arts_api_classes.cc.
References data.
checksizeGriddedField5()
DLL_PUBLIC bool checksizeGriddedField5 (void * data)
Definition at line 975 of file arts_api_classes.cc.
References data.
checksizeGriddedField6()
DLL_PUBLIC bool checksizeGriddedField6 (void * data)
Definition at line 998 of file arts_api_classes.cc.
References data.
colsMatrix()
DLL_PUBLIC Index colsMatrix (void * data)
Definition at line 594 of file arts_api_classes.cc.
References data, and ncols.
colsptrSparse()
DLL_PUBLIC int* colsptrSparse (void * data)
Definition at line 1355 of file arts_api_classes.cc.
References data.
colsSparse()
DLL_PUBLIC Index colsSparse (void * data)
Definition at line 1352 of file arts_api_classes.cc.
References data, and ncols.
colsTensor3()
DLL_PUBLIC Index colsTensor3 (void * data)
Definition at line 610 of file arts_api_classes.cc.
References data, and ncols.
colsTensor4()
DLL_PUBLIC Index colsTensor4 (void * data)
Definition at line 627 of file arts_api_classes.cc.
References data, and ncols.
colsTensor5()
DLL_PUBLIC Index colsTensor5 (void * data)
Definition at line 645 of file arts_api_classes.cc.
References data, and ncols.
colsTensor6()
DLL_PUBLIC Index colsTensor6 (void * data)
Definition at line 664 of file arts_api_classes.cc.
References data, and ncols.
colsTensor7()
DLL_PUBLIC Index colsTensor7 (void * data)
Definition at line 684 of file arts_api_classes.cc.
References data, and ncols.
createSpecies()
DLL_PUBLIC void* createSpecies ()
Definition at line 303 of file arts_api_classes.cc.
dataGriddedField1()
DLL_PUBLIC void* dataGriddedField1 (void * data)
Definition at line 867 of file arts_api_classes.cc.
References data.
dataGriddedField2()
DLL_PUBLIC void* dataGriddedField2 (void * data)
Definition at line 896 of file arts_api_classes.cc.
References data.
dataGriddedField3()
DLL_PUBLIC void* dataGriddedField3 (void * data)
Definition at line 925 of file arts_api_classes.cc.
References data.
dataGriddedField4()
DLL_PUBLIC void* dataGriddedField4 (void * data)
Definition at line 951 of file arts_api_classes.cc.
References data.
dataGriddedField5()
DLL_PUBLIC void* dataGriddedField5 (void * data)
Definition at line 974 of file arts_api_classes.cc.
References data.
dataGriddedField6()
DLL_PUBLIC void* dataGriddedField6 (void * data)
Definition at line 997 of file arts_api_classes.cc.
References data.
deleteSpecies()
DLL_PUBLIC void deleteSpecies (void * data)
Definition at line 306 of file arts_api_classes.cc.
References data.
equalTime()
DLL_PUBLIC bool equalTime (void * , void *)
frequenciesPropagationMatrix()
DLL_PUBLIC Index frequenciesPropagationMatrix (void * data)
Definition at line 699 of file arts_api_classes.cc.
References data.
frequenciesStokesVector()
DLL_PUBLIC Index frequenciesStokesVector (void * data)
Definition at line 725 of file arts_api_classes.cc.
References data.
get_extentRange()
DLL_PUBLIC Index get_extentRange (void * data)
Definition at line 1424 of file arts_api_classes.cc.
References data.
get_grid_nameGriddedField1()
DLL_PUBLIC char* get_grid_nameGriddedField1 (Index i, void * data)
Definition at line 856 of file arts_api_classes.cc.
References data, and GriddedField1::data.
get_grid_nameGriddedField2()
DLL_PUBLIC char* get_grid_nameGriddedField2 (Index i, void * data)
Definition at line 885 of file arts_api_classes.cc.
References data, and GriddedField2::data.
get_grid_nameGriddedField3()
DLL_PUBLIC char* get_grid_nameGriddedField3 (Index i, void * data)
Definition at line 914 of file arts_api_classes.cc.
References data, and GriddedField3::data.
get_grid_nameGriddedField4()
DLL_PUBLIC char* get_grid_nameGriddedField4 (Index i, void * data)
Definition at line 940 of file arts_api_classes.cc.
References data, and GriddedField4::data.
get_grid_nameGriddedField5()
DLL_PUBLIC char* get_grid_nameGriddedField5 (Index i, void * data)
Definition at line 963 of file arts_api_classes.cc.
References data, and GriddedField5::data.
get_grid_nameGriddedField6()
DLL_PUBLIC char* get_grid_nameGriddedField6 (Index i, void * data)
Definition at line 986 of file arts_api_classes.cc.
References data, and GriddedField6::data.
get_grid_sizeGriddedField1()
DLL_PUBLIC Index get_grid_sizeGriddedField1 (Index i, void * data)
Definition at line 853 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField2()
DLL_PUBLIC Index get_grid_sizeGriddedField2 (Index i, void * data)
Definition at line 882 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField3()
DLL_PUBLIC Index get_grid_sizeGriddedField3 (Index i, void * data)
Definition at line 911 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField4()
DLL_PUBLIC Index get_grid_sizeGriddedField4 (Index i, void * data)
Definition at line 937 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField5()
DLL_PUBLIC Index get_grid_sizeGriddedField5 (Index i, void * data)
Definition at line 960 of file arts_api_classes.cc.
References data.
get_grid_sizeGriddedField6()
DLL_PUBLIC Index get_grid_sizeGriddedField6 (Index i, void * data)
Definition at line 983 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField1()
DLL_PUBLIC Index get_grid_typeIndexGriddedField1 (Index i, void * data)
Definition at line 852 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField2()
DLL_PUBLIC Index get_grid_typeIndexGriddedField2 (Index i, void * data)
Definition at line 881 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField3()
DLL_PUBLIC Index get_grid_typeIndexGriddedField3 (Index i, void * data)
Definition at line 910 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField4()
DLL_PUBLIC Index get_grid_typeIndexGriddedField4 (Index i, void * data)
Definition at line 936 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField5()
DLL_PUBLIC Index get_grid_typeIndexGriddedField5 (Index i, void * data)
Definition at line 959 of file arts_api_classes.cc.
References data.
get_grid_typeIndexGriddedField6()
DLL_PUBLIC Index get_grid_typeIndexGriddedField6 (Index i, void * data)
Definition at line 982 of file arts_api_classes.cc.
References data.
get_index1Block()
DLL_PUBLIC Index get_index1Block (void * data)
Definition at line 1443 of file arts_api_classes.cc.
References data.
get_index2Block()
DLL_PUBLIC Index get_index2Block (void * data)
Definition at line 1444 of file arts_api_classes.cc.
References data.
get_list_of_all_workspace_classes()
DLL_PUBLIC void* get_list_of_all_workspace_classes ()
get_nameGriddedField1()
DLL_PUBLIC char* get_nameGriddedField1 (void * data)
Definition at line 854 of file arts_api_classes.cc.
References data, and GriddedField1::data.
get_nameGriddedField2()
DLL_PUBLIC char* get_nameGriddedField2 (void * data)
Definition at line 883 of file arts_api_classes.cc.
References data, and GriddedField2::data.
get_nameGriddedField3()
DLL_PUBLIC char* get_nameGriddedField3 (void * data)
Definition at line 912 of file arts_api_classes.cc.
References data, and GriddedField3::data.
get_nameGriddedField4()
DLL_PUBLIC char* get_nameGriddedField4 (void * data)
Definition at line 938 of file arts_api_classes.cc.
References data, and GriddedField4::data.
get_nameGriddedField5()
DLL_PUBLIC char* get_nameGriddedField5 (void * data)
Definition at line 961 of file arts_api_classes.cc.
References data, and GriddedField5::data.
get_nameGriddedField6()
DLL_PUBLIC char* get_nameGriddedField6 (void * data)
Definition at line 984 of file arts_api_classes.cc.
References data, and GriddedField6::data.
get_numeric_gridGriddedField1()
DLL_PUBLIC void* get_numeric_gridGriddedField1 (Index i, void * data)
Definition at line 858 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField2()
DLL_PUBLIC void* get_numeric_gridGriddedField2 (Index i, void * data)
Definition at line 887 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField3()
DLL_PUBLIC void* get_numeric_gridGriddedField3 (Index i, void * data)
Definition at line 916 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField4()
DLL_PUBLIC void* get_numeric_gridGriddedField4 (Index i, void * data)
Definition at line 942 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField5()
DLL_PUBLIC void* get_numeric_gridGriddedField5 (Index i, void * data)
Definition at line 965 of file arts_api_classes.cc.
References data.
get_numeric_gridGriddedField6()
DLL_PUBLIC void* get_numeric_gridGriddedField6 (Index i, void * data)
Definition at line 988 of file arts_api_classes.cc.
References data.
get_strideRange()
DLL_PUBLIC Index get_strideRange (void * data)
Definition at line 1423 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField1()
DLL_PUBLIC void* get_string_gridGriddedField1 (Index i, void * data)
Definition at line 859 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField2()
DLL_PUBLIC void* get_string_gridGriddedField2 (Index i, void * data)
Definition at line 888 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField3()
DLL_PUBLIC void* get_string_gridGriddedField3 (Index i, void * data)
Definition at line 917 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField4()
DLL_PUBLIC void* get_string_gridGriddedField4 (Index i, void * data)
Definition at line 943 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField5()
DLL_PUBLIC void* get_string_gridGriddedField5 (Index i, void * data)
Definition at line 966 of file arts_api_classes.cc.
References data.
get_string_gridGriddedField6()
DLL_PUBLIC void* get_string_gridGriddedField6 (Index i, void * data)
Definition at line 989 of file arts_api_classes.cc.
References data.
getA0_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getA0_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1283 of file arts_api_classes.cc.
References data.
getA0_K1TelsemAtlas()
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber void* DLL_PUBLIC Numeric getA0_K1TelsemAtlas (Index i, void * data)
Definition at line 1281 of file arts_api_classes.cc.
References data.
getA0_K2TelsemAtlas()
DLL_PUBLIC Numeric getA0_K2TelsemAtlas (Index i, void * data)
Definition at line 1282 of file arts_api_classes.cc.
References data.
getA1_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getA1_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1284 of file arts_api_classes.cc.
References data.
getA2_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getA2_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1285 of file arts_api_classes.cc.
References data.
getA3_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getA3_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1286 of file arts_api_classes.cc.
References data.
getB0_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getB0_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1287 of file arts_api_classes.cc.
References data.
getB1_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getB1_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1288 of file arts_api_classes.cc.
References data.
getB2_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getB2_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1289 of file arts_api_classes.cc.
References data.
getB3_EVEHTelsemAtlas()
DLL_PUBLIC Numeric getB3_EVEHTelsemAtlas (Index i, void * data)
Definition at line 1290 of file arts_api_classes.cc.
References data.
getcputime_end_cstimeTimer()
DLL_PUBLIC Index getcputime_end_cstimeTimer (void * data)
Definition at line 1164 of file arts_api_classes.cc.
References data.
getcputime_end_cutimeTimer()
DLL_PUBLIC Index getcputime_end_cutimeTimer (void * data)
Definition at line 1156 of file arts_api_classes.cc.
References data.
getcputime_end_stimeTimer()
DLL_PUBLIC Index getcputime_end_stimeTimer (void * data)
Definition at line 1148 of file arts_api_classes.cc.
References data.
getcputime_end_utimeTimer()
DLL_PUBLIC Index getcputime_end_utimeTimer (void * data)
Definition at line 1140 of file arts_api_classes.cc.
References data.
getcputime_start_cstimeTimer()
DLL_PUBLIC Index getcputime_start_cstimeTimer (void * data)
Definition at line 1124 of file arts_api_classes.cc.
References data.
getcputime_start_cutimeTimer()
DLL_PUBLIC Index getcputime_start_cutimeTimer (void * data)
Definition at line 1116 of file arts_api_classes.cc.
References data.
getcputime_start_stimeTimer()
DLL_PUBLIC Index getcputime_start_stimeTimer (void * data)
Definition at line 1108 of file arts_api_classes.cc.
References data.
getcputime_start_utimeTimer()
DLL_PUBLIC Index getcputime_start_utimeTimer (void * data)
Definition at line 1100 of file arts_api_classes.cc.
References data.
getDataMatrix()
DLL_PUBLIC Numeric* getDataMatrix (void * data)
Definition at line 595 of file arts_api_classes.cc.
References data.
getDataSparse()
DLL_PUBLIC Numeric* getDataSparse (void * data)
Definition at line 1356 of file arts_api_classes.cc.
References data.
getDataTensor3()
DLL_PUBLIC Numeric* getDataTensor3 (void * data)
Definition at line 611 of file arts_api_classes.cc.
References data.
getDataTensor4()
DLL_PUBLIC Numeric* getDataTensor4 (void * data)
Definition at line 628 of file arts_api_classes.cc.
References data.
getDataTensor5()
DLL_PUBLIC Numeric* getDataTensor5 (void * data)
Definition at line 646 of file arts_api_classes.cc.
References data.
getDataTensor6()
DLL_PUBLIC Numeric* getDataTensor6 (void * data)
Definition at line 665 of file arts_api_classes.cc.
References data.
getDataTensor7()
DLL_PUBLIC Numeric* getDataTensor7 (void * data)
Definition at line 685 of file arts_api_classes.cc.
References data.
getDataVector()
DLL_PUBLIC Numeric* getDataVector (void * data)
Definition at line 580 of file arts_api_classes.cc.
References data.
getErrorCorrectedSuddenData()
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta collisional_distance id DLL_PUBLIC void* getErrorCorrectedSuddenData (void * , void *)
getErrorCorrectedSuddenDataAtMapOfErrorCorrectedSuddenData()
DLL_PUBLIC void* getErrorCorrectedSuddenDataAtMapOfErrorCorrectedSuddenData (void * , Index)
getFileVerbosity()
DLL_PUBLIC Index getFileVerbosity (void * data)
Definition at line 1026 of file arts_api_classes.cc.
References data.
getfinishedTimer()
DLL_PUBLIC bool getfinishedTimer (void * data)
Definition at line 1099 of file arts_api_classes.cc.
References data.
getFrequenciesRadiationVector()
DLL_PUBLIC Index getFrequenciesRadiationVector (void * data)
Definition at line 839 of file arts_api_classes.cc.
References data.
getFrequenciesTransmissionMatrix()
DLL_PUBLIC Index getFrequenciesTransmissionMatrix (void * data)
Definition at line 821 of file arts_api_classes.cc.
References data.
getGSpeciesIsotopeRecord()
DLL_PUBLIC Index getGSpeciesIsotopeRecord (void * data)
Definition at line 371 of file arts_api_classes.cc.
References data.
getIndexSpeciesIsotopeRecordFromData()
DLL_PUBLIC Index getIndexSpeciesIsotopeRecordFromData (void * data)
Definition at line 347 of file arts_api_classes.cc.
References data, and Species::find_species_index().
getIsotnameSpeciesIsotopeRecord()
DLL_PUBLIC void* getIsotnameSpeciesIsotopeRecord (void * data)
Definition at line 365 of file arts_api_classes.cc.
References data.
getLocalQuantaAbsorptionLines()
DLL_PUBLIC Index getLocalQuantaAbsorptionLines (Index i, void * data)
Definition at line 550 of file arts_api_classes.cc.
References data.
getMainVerbosity()
DLL_PUBLIC bool getMainVerbosity (void * data)
Definition at line 1027 of file arts_api_classes.cc.
References data.
getMassSpeciesIsotopeRecord()
DLL_PUBLIC Numeric getMassSpeciesIsotopeRecord (void * data)
Definition at line 368 of file arts_api_classes.cc.
References data, and LineShape::mass().
getMat2TransmissionMatrix()
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon void* DLL_PUBLIC Numeric* getMat2TransmissionMatrix (Index i, void * data)
Definition at line 816 of file arts_api_classes.cc.
References data.
getMat3TransmissionMatrix()
DLL_PUBLIC Numeric* getMat3TransmissionMatrix (Index i, void * data)
Definition at line 817 of file arts_api_classes.cc.
References data.
getMat4TransmissionMatrix()
DLL_PUBLIC Numeric* getMat4TransmissionMatrix (Index i, void * data)
Definition at line 818 of file arts_api_classes.cc.
References data.
getnelemErrorCorrectedSuddenData()
DLL_PUBLIC Index getnelemErrorCorrectedSuddenData (void *)
getnelemMapOfErrorCorrectedSuddenData()
void* DLL_PUBLIC Index getnelemMapOfErrorCorrectedSuddenData (void *)
getOKPropagationMatrix()
DLL_PUBLIC bool getOKPropagationMatrix (void * data)
Definition at line 711 of file arts_api_classes.cc.
References data.
getOKStokesVector()
DLL_PUBLIC bool getOKStokesVector (void * data)
Definition at line 737 of file arts_api_classes.cc.
References data.
getQuantumNumbersString()
DLL_PUBLIC void* getQuantumNumbersString (void * data)
Definition at line 300 of file arts_api_classes.cc.
References data.
getRAPPORT43_32TelsemAtlas()
DLL_PUBLIC Numeric getRAPPORT43_32TelsemAtlas (Index i, void * data)
Definition at line 1291 of file arts_api_classes.cc.
References data.
getRAPPORT54_43TelsemAtlas()
DLL_PUBLIC Numeric getRAPPORT54_43TelsemAtlas (Index i, void * data)
Definition at line 1292 of file arts_api_classes.cc.
References data.
getrealtime_endTimer()
DLL_PUBLIC Index getrealtime_endTimer (void * data)
Definition at line 1172 of file arts_api_classes.cc.
References data.
getrealtime_startTimer()
DLL_PUBLIC Index getrealtime_startTimer (void * data)
Definition at line 1132 of file arts_api_classes.cc.
References data.
getScreenVerbosity()
DLL_PUBLIC Index getScreenVerbosity (void * data)
Definition at line 1025 of file arts_api_classes.cc.
References data.
getSpecies2CIARecord()
DLL_PUBLIC void* getSpecies2CIARecord (void * data)
Definition at line 1008 of file arts_api_classes.cc.
References data.
getSpeciesErrorCorrectedSuddenDataAtErrorCorrectedSuddenData()
DLL_PUBLIC void* getSpeciesErrorCorrectedSuddenDataAtErrorCorrectedSuddenData (void * , Index)
getSpeciesLongName()
DLL_PUBLIC void* getSpeciesLongName (void * data)
Definition at line 330 of file arts_api_classes.cc.
References data.
getSpeciesNameAbsorptionLines()
DLL_PUBLIC void* getSpeciesNameAbsorptionLines (void * data)
Definition at line 554 of file arts_api_classes.cc.
References data.
getSpeciesShortName()
DLL_PUBLIC void* getSpeciesShortName (void * data)
Definition at line 333 of file arts_api_classes.cc.
References data.
getSpeciesSpeciesIsotopeRecord()
DLL_PUBLIC void* getSpeciesSpeciesIsotopeRecord (void * data)
Definition at line 362 of file arts_api_classes.cc.
References data.
getStokesDimRadiationVector()
DLL_PUBLIC Index getStokesDimRadiationVector (void * data)
Definition at line 838 of file arts_api_classes.cc.
References data.
getStokesDimTransmissionMatrix()
DLL_PUBLIC Index getStokesDimTransmissionMatrix (void * data)
Definition at line 820 of file arts_api_classes.cc.
References data.
getString()
DLL_PUBLIC char* getString (void * data)
Definition at line 750 of file arts_api_classes.cc.
References data.
GetterSetterCAPI() [1/9]
bool GetterSetterCAPI (AbsorptionLines , Bath , bool)
GetterSetterCAPI() [2/9]
bool Cutoff Mirroring Normalization Numeric GetterSetterCAPI (AbsorptionLines , LinemixingLimit , Numeric)
GetterSetterCAPI() [3/9]
bool Cutoff Mirroring Normalization GetterSetterCAPI (AbsorptionLines , T0 , Numeric)
GetterSetterCAPI() [4/9]
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine , A , Numeric)
GetterSetterCAPI() [5/9]
type X1 X3 G0 G2 FVC Y DV Numeric Numeric GetterSetterCAPI (AbsorptionSingleLine , g_low , Numeric)
GetterSetterCAPI() [6/9]
type X1 X3 G0 G2 FVC Y DV Numeric GetterSetterCAPI (AbsorptionSingleLine , I0 , Numeric)
GetterSetterCAPI() [7/9]
Numeric Index GetterSetterCAPI (Rational , Denom , Index)
Definition at line 206 of file arts_api_classes.cc.
References data.
GetterSetterCAPI() [8/9]
get_blocks Perturbation StringKey TargetType SubTag Mode Target TFuncParameters Offset GetterSetterCAPI (RetrievalQuantity , Integration , bool)
GetterSetterCAPI() [9/9]
Numeric GetterSetterCAPI (ZeemanModel , gl , Numeric)
getTypeMCAntenna()
saa aag G DLL_PUBLIC Index getTypeMCAntenna (void * data)
Definition at line 1303 of file arts_api_classes.cc.
References data, and Type.
getVec2RadiationVector()
void* DLL_PUBLIC Numeric* getVec2RadiationVector (Index i, void * data)
Definition at line 834 of file arts_api_classes.cc.
References data.
getVec3RadiationVector()
DLL_PUBLIC Numeric* getVec3RadiationVector (Index i, void * data)
Definition at line 835 of file arts_api_classes.cc.
References data.
getVec4RadiationVector()
DLL_PUBLIC Numeric* getVec4RadiationVector (Index i, void * data)
Definition at line 836 of file arts_api_classes.cc.
References data.
isAbsorptionLinesOK()
DLL_PUBLIC Index isAbsorptionLinesOK (void * data)
Definition at line 553 of file arts_api_classes.cc.
References data.
lessTime()
DLL_PUBLIC bool lessTime (void * , void *)
librariesTensor7()
void* DLL_PUBLIC Index librariesTensor7 (void * data)
Definition at line 678 of file arts_api_classes.cc.
References data, and ARTS::Var::nlibraries().
nelemSpeciesIsotopeRecordDefined()
DLL_PUBLIC Index nelemSpeciesIsotopeRecordDefined ()
Definition at line 350 of file arts_api_classes.cc.
References Species::Isotopologues.
Referenced by setSpeciesIsotopeRecordToIndex().
nelemVector()
void* DLL_PUBLIC Index nelemVector (void * data)
Definition at line 579 of file arts_api_classes.cc.
References data, and Absorption::nelem().
pagesTensor3()
void* DLL_PUBLIC Index pagesTensor3 (void * data)
Definition at line 608 of file arts_api_classes.cc.
References data, and npages.
pagesTensor4()
DLL_PUBLIC Index pagesTensor4 (void * data)
Definition at line 625 of file arts_api_classes.cc.
References data, and npages.
pagesTensor5()
DLL_PUBLIC Index pagesTensor5 (void * data)
Definition at line 643 of file arts_api_classes.cc.
References data, and npages.
pagesTensor6()
DLL_PUBLIC Index pagesTensor6 (void * data)
Definition at line 662 of file arts_api_classes.cc.
References data, and npages.
pagesTensor7()
DLL_PUBLIC Index pagesTensor7 (void * data)
Definition at line 682 of file arts_api_classes.cc.
References data, and npages.
printmetaAbsorptionLines()
DLL_PUBLIC void printmetaAbsorptionLines (void * data)
Definition at line 552 of file arts_api_classes.cc.
References data.
printSpecies()
DLL_PUBLIC void printSpecies (void * data)
Definition at line 309 of file arts_api_classes.cc.
References data.
resizeLocalQuantaAbsorptionLines()
DLL_PUBLIC void resizeLocalQuantaAbsorptionLines (Index n, void * data)
Definition at line 549 of file arts_api_classes.cc.
References data.
rowsMatrix()
void* DLL_PUBLIC Index rowsMatrix (void * data)
Definition at line 593 of file arts_api_classes.cc.
References data, and nrows.
rowsptrSparse()
DLL_PUBLIC int* rowsptrSparse (void * data)
Definition at line 1354 of file arts_api_classes.cc.
References data.
rowsSparse()
RefPressure Fgrids TemperatureSlope void* DLL_PUBLIC Index rowsSparse (void * data)
Definition at line 1351 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor3()
DLL_PUBLIC Index rowsTensor3 (void * data)
Definition at line 609 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor4()
DLL_PUBLIC Index rowsTensor4 (void * data)
Definition at line 626 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor5()
DLL_PUBLIC Index rowsTensor5 (void * data)
Definition at line 644 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor6()
DLL_PUBLIC Index rowsTensor6 (void * data)
Definition at line 663 of file arts_api_classes.cc.
References data, and nrows.
rowsTensor7()
DLL_PUBLIC Index rowsTensor7 (void * data)
Definition at line 683 of file arts_api_classes.cc.
References data, and nrows.
set_grid_nameGriddedField1()
DLL_PUBLIC void set_grid_nameGriddedField1 (Index i, void * data, char * newdata)
Definition at line 857 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField2()
DLL_PUBLIC void set_grid_nameGriddedField2 (Index i, void * data, char * newdata)
Definition at line 886 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField3()
DLL_PUBLIC void set_grid_nameGriddedField3 (Index i, void * data, char * newdata)
Definition at line 915 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField4()
DLL_PUBLIC void set_grid_nameGriddedField4 (Index i, void * data, char * newdata)
Definition at line 941 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField5()
DLL_PUBLIC void set_grid_nameGriddedField5 (Index i, void * data, char * newdata)
Definition at line 964 of file arts_api_classes.cc.
References data, and newdata.
set_grid_nameGriddedField6()
DLL_PUBLIC void set_grid_nameGriddedField6 (Index i, void * data, char * newdata)
Definition at line 987 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField1()
DLL_PUBLIC void set_gridGriddedField1 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 860 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField2()
DLL_PUBLIC void set_gridGriddedField2 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 889 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField3()
DLL_PUBLIC void set_gridGriddedField3 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 918 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField4()
DLL_PUBLIC void set_gridGriddedField4 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 944 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField5()
DLL_PUBLIC void set_gridGriddedField5 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 967 of file arts_api_classes.cc.
References data, and newdata.
set_gridGriddedField6()
DLL_PUBLIC void set_gridGriddedField6 (Index i, void * data, void * newdata, bool NumericType)
Definition at line 990 of file arts_api_classes.cc.
References data, and newdata.
set_indicesBlock()
DLL_PUBLIC void set_indicesBlock (void * data, Index i1, Index i2)
Definition at line 1445 of file arts_api_classes.cc.
References data.
set_matrixBlock()
DLL_PUBLIC void set_matrixBlock (void * data, void * newdata, bool dense)
Definition at line 1446 of file arts_api_classes.cc.
References data, newdata, and ARTS::Var::x().
set_nameGriddedField1()
DLL_PUBLIC void set_nameGriddedField1 (void * data, char * newdata)
Definition at line 855 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField2()
DLL_PUBLIC void set_nameGriddedField2 (void * data, char * newdata)
Definition at line 884 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField3()
DLL_PUBLIC void set_nameGriddedField3 (void * data, char * newdata)
Definition at line 913 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField4()
DLL_PUBLIC void set_nameGriddedField4 (void * data, char * newdata)
Definition at line 939 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField5()
DLL_PUBLIC void set_nameGriddedField5 (void * data, char * newdata)
Definition at line 962 of file arts_api_classes.cc.
References data, and newdata.
set_nameGriddedField6()
DLL_PUBLIC void set_nameGriddedField6 (void * data, char * newdata)
Definition at line 985 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_cstimeTimer()
DLL_PUBLIC void setcputime_end_cstimeTimer (void * data, Index newdata)
Definition at line 1230 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_cutimeTimer()
DLL_PUBLIC void setcputime_end_cutimeTimer (void * data, Index newdata)
Definition at line 1224 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_stimeTimer()
DLL_PUBLIC void setcputime_end_stimeTimer (void * data, Index newdata)
Definition at line 1218 of file arts_api_classes.cc.
References data, and newdata.
setcputime_end_utimeTimer()
DLL_PUBLIC void setcputime_end_utimeTimer (void * data, Index newdata)
Definition at line 1212 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_cstimeTimer()
DLL_PUBLIC void setcputime_start_cstimeTimer (void * data, Index newdata)
Definition at line 1200 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_cutimeTimer()
DLL_PUBLIC void setcputime_start_cutimeTimer (void * data, Index newdata)
Definition at line 1194 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_stimeTimer()
DLL_PUBLIC void setcputime_start_stimeTimer (void * data, Index newdata)
Definition at line 1188 of file arts_api_classes.cc.
References data, and newdata.
setcputime_start_utimeTimer()
DLL_PUBLIC void setcputime_start_utimeTimer (void * data, Index newdata)
Definition at line 1182 of file arts_api_classes.cc.
References data, and newdata.
setDataSparse()
DLL_PUBLIC void setDataSparse (void * data, Index r, Index c, Numeric v)
Definition at line 1357 of file arts_api_classes.cc.
References c, data, and v.
setfinishedTimer()
DLL_PUBLIC void setfinishedTimer (void * data, bool newdata)
Definition at line 1181 of file arts_api_classes.cc.
References data, and newdata.
setIndex()
DLL_PUBLIC void setIndex (void * data, Index newval)
Definition at line 176 of file arts_api_classes.cc.
References data.
setLocalQuantaAbsorptionLines()
DLL_PUBLIC void setLocalQuantaAbsorptionLines (Index i, void * data, Index newval)
Definition at line 551 of file arts_api_classes.cc.
References data.
setNumeric()
DLL_PUBLIC void setNumeric (void * data, Numeric newval)
Definition at line 193 of file arts_api_classes.cc.
References data.
setPropagationMatrix()
DLL_PUBLIC Index setPropagationMatrix (void * data, Index f, Index s, Index z, Index a, Numeric v)
Definition at line 702 of file arts_api_classes.cc.
References a, data, and v.
setRadiationVector()
DLL_PUBLIC void setRadiationVector (void * data, Index stokes, Index freqs)
Definition at line 837 of file arts_api_classes.cc.
References data.
setRange()
DLL_PUBLIC void setRange (void * data, Index start, Index extent, Index stride)
Definition at line 1425 of file arts_api_classes.cc.
References data, joker, and Zeeman::start().
setrealtime_endTimer()
DLL_PUBLIC void setrealtime_endTimer (void * data, Index newdata)
Definition at line 1236 of file arts_api_classes.cc.
References data, and newdata.
setrealtime_startTimer()
DLL_PUBLIC void setrealtime_startTimer (void * data, Index newdata)
Definition at line 1206 of file arts_api_classes.cc.
References data, and newdata.
setrunningTimer()
DLL_PUBLIC void setrunningTimer (void * data, bool newdata)
Definition at line 1180 of file arts_api_classes.cc.
References data, and newdata.
setSpeciesCIARecord()
DLL_PUBLIC void setSpeciesCIARecord (void * data, void * s1, void * s2)
Definition at line 1011 of file arts_api_classes.cc.
References data.
setSpeciesIsotopeRecordToIndex()
DLL_PUBLIC int setSpeciesIsotopeRecordToIndex (void * data, Index i)
Definition at line 353 of file arts_api_classes.cc.
References data, Species::Isotopologues, and nelemSpeciesIsotopeRecordDefined().
setSpeciesLongName()
DLL_PUBLIC int setSpeciesLongName (void * data, char * spec)
Definition at line 312 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setSpeciesShortName()
DLL_PUBLIC int setSpeciesShortName (void * data, char * spec)
Definition at line 321 of file arts_api_classes.cc.
References data, good_enum(), and ARTS::Var::x().
setSpeciesTag()
DLL_PUBLIC Index setSpeciesTag (void * data, char * newdata)
Definition at line 452 of file arts_api_classes.cc.
References data, and newdata.
setSpeciesXsecRecord()
DLL_PUBLIC void setSpeciesXsecRecord (void * data, void * val)
Definition at line 1329 of file arts_api_classes.cc.
References data.
setStokesVector()
DLL_PUBLIC Index setStokesVector (void * data, Index f, Index s, Index z, Index a, Numeric v)
Definition at line 728 of file arts_api_classes.cc.
References a, data, and v.
setTime()
Numeric char* DLL_PUBLIC void setTime (void * , void *)
setTransmissionMatrix()
DLL_PUBLIC void setTransmissionMatrix (void * data, Index stokes, Index freqs)
Definition at line 819 of file arts_api_classes.cc.
References data.
setTypeMCAntenna()
DLL_PUBLIC Index setTypeMCAntenna (void * data, Index newval)
Definition at line 1304 of file arts_api_classes.cc.
References data, and Type.
setVerbosity()
DLL_PUBLIC void setVerbosity (void * data, Index a, Index s, Index f, bool m)
Definition at line 1028 of file arts_api_classes.cc.
References a, data, and ARTS::Var::x().
shelvesTensor5()
void* DLL_PUBLIC Index shelvesTensor5 (void * data)
Definition at line 641 of file arts_api_classes.cc.
References data, and nshelves.
shelvesTensor6()
DLL_PUBLIC Index shelvesTensor6 (void * data)
Definition at line 660 of file arts_api_classes.cc.
References data, and nshelves.
shelvesTensor7()
DLL_PUBLIC Index shelvesTensor7 (void * data)
Definition at line 680 of file arts_api_classes.cc.
References data, and nshelves.
sizeQuantumNumbers()
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman LowerQuantumNumbers void* DLL_PUBLIC Index sizeQuantumNumbers ()
Definition at line 298 of file arts_api_classes.cc.
sizeSparse()
DLL_PUBLIC Index sizeSparse (void * data)
Definition at line 1353 of file arts_api_classes.cc.
References data.
string2filetypeindex()
DLL_PUBLIC Index string2filetypeindex (char *)
string2quantumnumbersindex()
DLL_PUBLIC Index string2quantumnumbersindex (char * str)
Definition at line 299 of file arts_api_classes.cc.
References str.
StringEnumGetterSetterCAPI()
get_blocks Perturbation StringKey TargetType StringEnumGetterSetterCAPI (JacobianTarget , TargetSubType)
supportTimer()
DLL_PUBLIC bool supportTimer ()
Definition at line 1242 of file arts_api_classes.cc.
tickTimer()
DLL_PUBLIC Index tickTimer ()
Definition at line 1250 of file arts_api_classes.cc.
vitrinesTensor6()
void* DLL_PUBLIC Index vitrinesTensor6 (void * data)
Definition at line 659 of file arts_api_classes.cc.
References data, and nvitrines.
vitrinesTensor7()
DLL_PUBLIC Index vitrinesTensor7 (void * data)
Definition at line 679 of file arts_api_classes.cc.
References data, and nvitrines.
VoidArrayCAPI() [1/10]
bool Cutoff Mirroring Normalization Numeric QuantumIdentity AllLines VoidArrayCAPI (ArrayOfAbsorptionLines)
Definition at line 542 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [2/10]
Data VoidArrayCAPI (ArrayOfCIARecord)
Definition at line 1016 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [3/10]
idx pos dlx VoidArrayCAPI (ArrayOfLagrangeInterpolation)
VoidArrayCAPI() [4/10]
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p gp_lon VoidArrayCAPI (ArrayOfPpath)
VoidArrayCAPI() [5/10]
Data VoidArrayCAPI (ArrayOfPropagationMatrix)
Definition at line 692 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [6/10]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max diameter_area_equ_aerodynamical VoidArrayCAPI (ArrayOfScatteringMetaData)
Definition at line 1085 of file arts_api_classes.cc.
VoidArrayCAPI() [7/10]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data VoidArrayCAPI (ArrayOfSingleScatteringData)
VoidArrayCAPI() [8/10]
VoidArrayCAPI (ArrayOfSpecies)
VoidArrayCAPI() [9/10]
Data VoidArrayCAPI (ArrayOfStokesVector)
Definition at line 718 of file arts_api_classes.cc.
References data.
VoidArrayCAPI() [10/10]
Numeric VoidArrayCAPI (ArrayOfTime)
VoidArrayElemCAPI() [1/2]
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman LowerQuantumNumbers VoidArrayElemCAPI (AbsorptionSingleLine , UpperQuantumNumbers)
VoidArrayElemCAPI() [2/2]
get_blocks VoidArrayElemCAPI (CovarianceMatrix , get_inverse_blocks)
VoidGetterCAPI() [1/36]
bool Cutoff Mirroring Normalization Numeric QuantumIdentity VoidGetterCAPI (AbsorptionLines , BroadeningSpecies)
VoidGetterCAPI() [2/36]
bool Cutoff VoidGetterCAPI (AbsorptionLines , LineShapeType)
VoidGetterCAPI() [3/36]
bool Cutoff Mirroring VoidGetterCAPI (AbsorptionLines , Population)
VoidGetterCAPI() [4/36]
type X1 X3 G0 G2 FVC Y DV Numeric Numeric Numeric Zeeman VoidGetterCAPI (AbsorptionSingleLine , LineShape)
VoidGetterCAPI() [5/36]
get_row_range VoidGetterCAPI (Block , get_column_range)
VoidGetterCAPI() [6/36]
get_row_range get_dense VoidGetterCAPI (Block , get_sparse)
VoidGetterCAPI() [7/36]
EnergyLevelMapType Energies VoidGetterCAPI (EnergyLevelMap , Data)
Definition at line 565 of file arts_api_classes.cc.
References data.
VoidGetterCAPI() [8/36]
EnergyLevelMapType VoidGetterCAPI (EnergyLevelMap , Levels)
VoidGetterCAPI() [9/36]
Species Fgrid VoidGetterCAPI (GasAbsLookup , FLAGDefault)
VoidGetterCAPI() [10/36]
Species Fgrid Pgrid VoidGetterCAPI (GasAbsLookup , LogPgrid)
VoidGetterCAPI() [11/36]
Species Fgrid Pgrid VMRs Tpert VoidGetterCAPI (GasAbsLookup , NLSPert)
VoidGetterCAPI() [12/36]
Species VoidGetterCAPI (GasAbsLookup , NonLinearSpecies)
VoidGetterCAPI() [13/36]
Species Fgrid Pgrid VMRs VoidGetterCAPI (GasAbsLookup , Tref)
VoidGetterCAPI() [14/36]
get_blocks Perturbation VoidGetterCAPI (JacobianTarget , QuantumIdentity)
VoidGetterCAPI() [15/36]
get_blocks Perturbation StringKey VoidGetterCAPI (JacobianTarget , SpeciesList)
VoidGetterCAPI() [16/36]
type X1 X3 G0 VoidGetterCAPI (LineShapeSingleSpeciesModel , D0)
VoidGetterCAPI() [17/36]
type X1 X3 G0 G2 VoidGetterCAPI (LineShapeSingleSpeciesModel , D2)
VoidGetterCAPI() [18/36]
type X1 X3 G0 G2 FVC VoidGetterCAPI (LineShapeSingleSpeciesModel , ETA)
VoidGetterCAPI() [19/36]
type X1 X3 G0 G2 FVC Y VoidGetterCAPI (LineShapeSingleSpeciesModel , G)
VoidGetterCAPI() [20/36]
saa VoidGetterCAPI (MCAntenna , sza)
VoidGetterCAPI() [21/36]
saa aag VoidGetterCAPI (MCAntenna , zag)
VoidGetterCAPI() [22/36]
get_blocks Perturbation StringKey TargetType SubTag Mode VoidGetterCAPI (RetrievalQuantity , Grids)
VoidGetterCAPI() [23/36]
get_blocks Perturbation StringKey TargetType SubTag VoidGetterCAPI (RetrievalQuantity , SubSubTag)
VoidGetterCAPI() [24/36]
get_blocks Perturbation StringKey TargetType SubTag Mode Target TFuncParameters VoidGetterCAPI (RetrievalQuantity , Transformation)
VoidGetterCAPI() [25/36]
get_blocks Perturbation StringKey TargetType SubTag Mode Target VoidGetterCAPI (RetrievalQuantity , TransformationFunc)
VoidGetterCAPI() [26/36]
DataCount Name Lat VoidGetterCAPI (TelsemAtlas , Cells)
VoidGetterCAPI() [27/36]
DataCount VoidGetterCAPI (TelsemAtlas , ChannelCount)
VoidGetterCAPI() [28/36]
DataCount Name Lat FirstCells Emis_err Classes1 VoidGetterCAPI (TelsemAtlas , Classes2)
VoidGetterCAPI() [29/36]
DataCount Name Lat FirstCells Emis_err VoidGetterCAPI (TelsemAtlas , Correlations)
VoidGetterCAPI() [30/36]
DataCount Name Lat FirstCells Emis_err Classes1 Cellnumber VoidGetterCAPI (TelsemAtlas , Correspondance)
VoidGetterCAPI() [31/36]
DataCount Name Lat FirstCells VoidGetterCAPI (TelsemAtlas , Emis)
VoidGetterCAPI() [32/36]
DataCount Name VoidGetterCAPI (TelsemAtlas , Month)
VoidGetterCAPI() [33/36]
VoidGetterCAPI (XsecRecord , Coeffs)
VoidGetterCAPI() [34/36]
RefPressure VoidGetterCAPI (XsecRecord , RefTemperature)
VoidGetterCAPI() [35/36]
RefPressure Fgrids TemperatureSlope VoidGetterCAPI (XsecRecord , TemperatureIntersect)
VoidGetterCAPI() [36/36]
RefPressure Fgrids VoidGetterCAPI (XsecRecord , Xsecs)
VoidStructGetterCAPI() [1/43]
idx VoidStructGetterCAPI (GridPos , fd)
VoidStructGetterCAPI() [2/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp VoidStructGetterCAPI (HitranRelaxationMatrixData , B0pp)
VoidStructGetterCAPI() [3/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq VoidStructGetterCAPI (HitranRelaxationMatrixData , B0pq)
VoidStructGetterCAPI() [4/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr VoidStructGetterCAPI (HitranRelaxationMatrixData , B0pr)
VoidStructGetterCAPI() [5/43]
W0rr W0rq W0rp W0qr W0qq W0qp VoidStructGetterCAPI (HitranRelaxationMatrixData , B0qp)
VoidStructGetterCAPI() [6/43]
W0rr W0rq W0rp W0qr W0qq VoidStructGetterCAPI (HitranRelaxationMatrixData , B0qq)
VoidStructGetterCAPI() [7/43]
W0rr W0rq W0rp W0qr VoidStructGetterCAPI (HitranRelaxationMatrixData , B0qr)
VoidStructGetterCAPI() [8/43]
W0rr W0rq W0rp VoidStructGetterCAPI (HitranRelaxationMatrixData , B0rp)
VoidStructGetterCAPI() [9/43]
W0rr W0rq VoidStructGetterCAPI (HitranRelaxationMatrixData , B0rq)
VoidStructGetterCAPI() [10/43]
W0rr VoidStructGetterCAPI (HitranRelaxationMatrixData , B0rr)
VoidStructGetterCAPI() [11/43]
idx pos VoidStructGetterCAPI (LagrangeInterpolation , lx)
VoidStructGetterCAPI() [12/43]
type VoidStructGetterCAPI (LineShapeModelParameters , X0)
VoidStructGetterCAPI() [13/43]
type X1 VoidStructGetterCAPI (LineShapeModelParameters , X2)
VoidStructGetterCAPI() [14/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type VoidStructGetterCAPI (PartitionFunctionsData , data)
VoidStructGetterCAPI() [15/43]
idx pos dlx dim constant VoidStructGetterCAPI (Ppath , background)
VoidStructGetterCAPI() [16/43]
idx pos dlx dim constant start_pos start_lstep los lstep end_los VoidStructGetterCAPI (Ppath , end_lstep)
VoidStructGetterCAPI() [17/43]
idx pos dlx dim constant start_pos start_lstep los lstep VoidStructGetterCAPI (Ppath , end_pos)
VoidStructGetterCAPI() [18/43]
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal gp_p VoidStructGetterCAPI (Ppath , gp_lat)
VoidStructGetterCAPI() [19/43]
idx pos dlx dim constant start_pos start_lstep los lstep end_los nreal VoidStructGetterCAPI (Ppath , ngroup)
VoidStructGetterCAPI() [20/43]
idx pos dlx dim VoidStructGetterCAPI (Ppath , np)
VoidStructGetterCAPI() [21/43]
idx pos dlx dim constant start_pos start_lstep VoidStructGetterCAPI (Ppath , pos)
VoidStructGetterCAPI() [22/43]
idx pos dlx dim constant start_pos start_lstep los VoidStructGetterCAPI (Ppath , r)
VoidStructGetterCAPI() [23/43]
idx pos dlx dim constant start_pos VoidStructGetterCAPI (Ppath , start_los)
VoidStructGetterCAPI() [24/43]
type upp VoidStructGetterCAPI (QuantumIdentifier , low)
VoidStructGetterCAPI() [25/43]
type VoidStructGetterCAPI (QuantumIdentifier , spec_ind)
VoidStructGetterCAPI() [26/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index diameter_max VoidStructGetterCAPI (ScatteringMetaData , diameter_volume_equ)
VoidStructGetterCAPI() [27/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description refr_index VoidStructGetterCAPI (ScatteringMetaData , mass)
VoidStructGetterCAPI() [28/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data abs_vec_data description VoidStructGetterCAPI (ScatteringMetaData , source)
VoidStructGetterCAPI() [29/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid VoidStructGetterCAPI (SingleScatteringData , aa_grid)
VoidStructGetterCAPI() [30/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype VoidStructGetterCAPI (SingleScatteringData , description)
VoidStructGetterCAPI() [31/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid za_grid pha_mat_data VoidStructGetterCAPI (SingleScatteringData , ext_mat_data)
VoidStructGetterCAPI() [32/43]
nb_inputs nb_cache b2 w2 x_max y_max ptype f_grid VoidStructGetterCAPI (SingleScatteringData , T_grid)
VoidStructGetterCAPI() [33/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData , lambda)
VoidStructGetterCAPI() [34/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec beta collisional_distance VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData , mass)
VoidStructGetterCAPI() [35/43]
W0rr W0rq W0rp W0qr W0qq W0qp W0pr W0pq W0pp type spec VoidStructGetterCAPI (SpeciesErrorCorrectedSuddenData , scaling)
VoidStructGetterCAPI() [36/43]
type upp char spec_ind upper_freq cia_2nd_species VoidStructGetterCAPI (SpeciesTag , cia_dataset_index)
Definition at line 439 of file arts_api_classes.cc.
References data.
VoidStructGetterCAPI() [37/43]
type upp char spec_ind VoidStructGetterCAPI (SpeciesTag , lower_freq)
VoidStructGetterCAPI() [38/43]
type upp char spec_ind upper_freq VoidStructGetterCAPI (SpeciesTag , type)
VoidStructGetterCAPI() [39/43]
nb_inputs nb_cache VoidStructGetterCAPI (TessemNN , b1)
VoidStructGetterCAPI() [40/43]
nb_inputs VoidStructGetterCAPI (TessemNN , nb_outputs)
VoidStructGetterCAPI() [41/43]
nb_inputs nb_cache b2 VoidStructGetterCAPI (TessemNN , w1)
VoidStructGetterCAPI() [42/43]
nb_inputs nb_cache b2 w2 VoidStructGetterCAPI (TessemNN , x_min)
VoidStructGetterCAPI() [43/43]
nb_inputs nb_cache b2 w2 x_max VoidStructGetterCAPI (TessemNN , y_min)
zenithsPropagationMatrix()
DLL_PUBLIC Index zenithsPropagationMatrix (void * data)
Definition at line 700 of file arts_api_classes.cc.
References data.
zenithsStokesVector()
DLL_PUBLIC Index zenithsStokesVector (void * data)
Definition at line 726 of file arts_api_classes.cc.
References data.
Variable Documentation
CutoffFreqValue
bool Cutoff Mirroring Normalization CutoffFreqValue
Definition at line 299 of file arts_api_classes.h.
E0
type X1 X3 G0 G2 FVC Y DV Numeric E0
Definition at line 184 of file arts_api_classes.h.
F0
type X1 X3 G0 G2 FVC Y DV F0
Definition at line 182 of file arts_api_classes.h.
g_upp
type X1 X3 G0 G2 FVC Y DV Numeric Numeric g_upp
Definition at line 186 of file arts_api_classes.h.
gu
gu
Definition at line 138 of file arts_api_classes.h.
Index
RefPressure Fgrids TemperatureSlope Index
Definition at line 349 of file arts_api_classes.h.
isot
char* isot
Definition at line 218 of file arts_api_classes.h.
newdata
char* newdata
Definition at line 482 of file arts_api_classes.h.
Nom
Numeric Nom
Definition at line 144 of file arts_api_classes.h.
Seconds
Seconds
Definition at line 941 of file arts_api_classes.h.
Self
Self
Definition at line 291 of file arts_api_classes.h.
Type
Type
Definition at line 321 of file arts_api_classes.h.