ARTS: arts.cc File Reference
arts.cc File Reference
This file contains global functions.
#include "arts.h"
#include <unistd.h>
#include <cstdlib>
#include <stdexcept>
#include "file.h"
#include "messages.h"
Functions
void arts_exit (int status)
This is the exit function of ARTS.
void arts_exit_with_error_message (const String &m, ArtsOut &out)
Print error message and exit.
Detailed Description
This file contains global functions.
Author
Oliver Lemke
Date
2003-05-07
Definition in file arts.cc.
Function Documentation
arts_exit()
void arts_exit (int status)
This is the exit function of ARTS.
Whenever arts has to be terminated at some point, call this function.
You can call without any parameters, since the exit status then defaults to EXIT_FAILURE.
Parameters
status Exit code. EXIT_FAILURE if omitted.
Definition at line 42 of file arts.cc.
References add_basedir(), cleanup_output_file(), out_basename, and report_file.
Referenced by arts_exit_with_error_message(), c_errmsg(), Exit(), get_parameters(), interp_poly(), main(), operator<<(), AgRecord::operator=(), MdRecord::operator=(), option_describe(), option_input(), option_methods(), option_workspacevariables(), polite_goodby(), set_reporting_level(), and VectorInsertGridPoints().
arts_exit_with_error_message()
void arts_exit_with_error_message (const String & m, ArtsOut & out)
Print error message and exit.
This function is intended for use in catch blocks.
Parameters
m Error message.
m ArtsOut stream to use.
Author
Stefan Buehler
Date
2008-05-09
Definition at line 64 of file arts.cc.
References add_basedir(), arts_exit(), Verbosity::get_file_verbosity(), Verbosity::get_screen_verbosity(), ArtsOut::get_verbosity(), and out_basename.
Referenced by Arts(), Arts2(), and main().