ARTS: artstime.h File Reference
artstime.h File Reference
Stuff related to time in ARTS.
#include <chrono>
#include <cmath>
#include "array.h"
#include "matpackI.h"
#include "mystring.h"
Classes
class Time
Class to handle time in ARTS.
Typedefs
using TimeStep = std::chrono::duration< Numeric >
A duration of time, 1 full tick should be 1 second.
using ArrayOfTime = Array< Time >
List of times.
using ArrayOfArrayOfTime = Array< ArrayOfTime >
List of times.
Functions
std::ostream & operator<< (std::ostream &os, const Time &t)
Output for Time.
std::istream & operator>> (std::istream &is, Time &t)
Input for Time.
std::ostream & operator<< (std::ostream &os, const TimeStep &dt)
Debug output for duration.
TimeStep time_stepper_selection (const String &time_step)
Returns a time step from valid string.
Time next_even (const Time &t, const TimeStep &dt)
Returns the next time after t with an even time-step.
ArrayOfIndex time_steps (const ArrayOfTime &times, const TimeStep &dt)
Finds the index matching demands in a list of times.
Time mean_time (const ArrayOfTime &ts, Index s=0, Index e=-1)
Computes the average time in a list.
Vector time_vector (const ArrayOfTime &times)
Converts from each Time to seconds and returns as Vector.
ArrayOfTime time_vector (const Vector &times)
Converts from each Vector entry by seconds and returns as ArrayOfTime.
Detailed Description
Stuff related to time in ARTS.
Author
Richard Larsson
Date
2020-04-13
Definition in file artstime.h.
Typedef Documentation
ArrayOfArrayOfTime
using ArrayOfArrayOfTime = Array<ArrayOfTime>
List of times.
Definition at line 89 of file artstime.h.
ArrayOfTime
using ArrayOfTime = Array<Time>
List of times.
Definition at line 86 of file artstime.h.
TimeStep
using TimeStep = std::chrono::duration<Numeric>
A duration of time, 1 full tick should be 1 second.
Definition at line 38 of file artstime.h.
Function Documentation
mean_time()
Time mean_time (const ArrayOfTime & ts, Index s = 0, Index e = -1)
Computes the average time in a list.
Parameters
[in] ts A list of time
[in] s A starting index; valid range [0, ts.nelem())
[in] e The end+1 index; valid range [-1, ts.nelem()]; -1 is treated as ts.nelem()
Definition at line 153 of file artstime.cc.
next_even()
Time next_even (const Time & t, const TimeStep & dt)
Returns the next time after t with an even time-step.
Parameters
[in] t A time
[in] dt A duration of time
Returns
Next even time, e.g., 14:14:00 with dt as 10 minutes gives 14:20:00
Definition at line 69 of file artstime.cc.
References Time::EpochTime().
Referenced by time_steps().
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const Time & t)
Output for Time.
Definition at line 106 of file artstime.cc.
References Time::PartOfSecond(), Time::toStruct(), and x.
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const TimeStep & dt) inline
Debug output for duration.
Definition at line 98 of file artstime.h.
operator>>()
std::istream& operator>> (std::istream & is, Time & t)
Input for Time.
Definition at line 124 of file artstime.cc.
References ARTS_USER_ERROR_IF, is, Array< base >::nelem(), my_basic_string< charT >::split(), and x.
time_stepper_selection()
TimeStep time_stepper_selection (const String & time_step)
Returns a time step from valid string.
The string should look like: "X type". where X is parsed as a double and where valid string type(s) are: "hour", "hours", "h": Returns a X hour time step "minute", "minutes", "min": Returns a X minute time step "second", "seconds", "s": Returns a X seconds time step
Parameters
[in] time_step A time step of format "X type"
Returns
The time step as TimeStep
Definition at line 38 of file artstime.cc.
References check_enum_error(), my_basic_string< charT >::tolower(), and x.
Referenced by test01(), and ybatchTimeAveraging().
time_steps()
ArrayOfIndex time_steps (const ArrayOfTime & times, const TimeStep & dt)
Finds the index matching demands in a list of times.
The first index is 0 and the second index is the start of the first even period of the given stepsize
The last index is times.nelem(). If output has 1 element, no range was found matching the criteria.
Parameters
[in] times Times sorted in ascending order
[in] dt A duration of time
Returns
Starting index of the time-series
Definition at line 79 of file artstime.cc.
References abs, ARTS_USER_ERROR_IF, N, Array< base >::nelem(), and next_even().
Referenced by test01(), and ybatchTimeAveraging().
time_vector() [1/2]
Vector time_vector (const ArrayOfTime & times)
Converts from each Time to seconds and returns as Vector.
Parameters
[in] times Times
Returns
Vector of Time->Seconds() calls
Definition at line 169 of file artstime.cc.
References Array< base >::nelem().
Referenced by jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), and x2artsSensor().
time_vector() [2/2]
ArrayOfTime time_vector (const Vector & times)
Converts from each Vector entry by seconds and returns as ArrayOfTime.
Parameters
[in] times Times
Returns
ArrayOfTime from seconds
Definition at line 175 of file artstime.cc.
References ConstVectorView::nelem(), and Seconds.