ARTS: auto_partfun.h File Reference
auto_partfun.h File Reference
#include <limits>
#include "template_partfun.h"
#include "debug.h"
Namespaces
PartitionFunctions
Functions
template<std::size_t N>
std::string column_string (const std::array< std::string_view, N > &list)
Auto-generated partition function data.
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeBath (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeWater (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeOzone (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitrogenOxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeMethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeOxygen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitricOxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfurDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitrogenDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeAmmonia (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitricAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydroxyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenChloride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenBromide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenIodide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeChlorineMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonylSulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHeavyFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeVeryHeavyFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHypochlorousAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitrogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenCyanide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeChloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenPeroxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeAcetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeEthane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePhosphine (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonylFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfurHexafluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenSulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeLeftHeavyFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeRightHeavyFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydroperoxyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeOxygenAtom (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeChlorineNitrate (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitricOxideCation (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeChlorineDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeBromineMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfuricAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeChlorineMonoxideDimer (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHypobromousAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeEthylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeMethanol (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeBromomethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeAcetonitrile (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHeavyAcetonitrile (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonTetrafluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeDiacetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCyanoacetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonMonosulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenIsocyanide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfurMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePropane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHydrogenAtom (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHelium (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeArgon (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfurTrioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCyanogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePhosgene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonDisulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeMethyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCyclopropene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHexafluoroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluoropropane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluorobutane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluoropentane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluorohexane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluorooctane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computePerfluorocyclobutane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCarbonTetrachloride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCFC11 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCFC113 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCFC114 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCFC115 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeCFC12 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeDichloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeTrichloroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeTrichloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeBromochlorodifluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeBromotrifluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeDibromotetrafluoroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHCFC141b (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHCFC142b (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHCFC22 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC125 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC134a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC143a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC152a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC227ea (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC23 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC245fa (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC32 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeNitrogenTrifluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeSulfurylFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeHFC4310mee (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeGermane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeIodomethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeFluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeliquidcloud (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeicecloud (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computerain (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computefree_electrons (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric PartitionFunctions::computeparticles (const Numeric T, const std::string_view name)
Variables
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasBath
constexpr std::array< std::string_view, 9 > PartitionFunctions::hasWater
constexpr std::array< std::string_view, 13 > PartitionFunctions::hasCarbonDioxide
constexpr std::array< std::string_view, 18 > PartitionFunctions::hasOzone
constexpr std::array< std::string_view, 5 > PartitionFunctions::hasNitrogenOxide
constexpr std::array< std::string_view, 9 > PartitionFunctions::hasCarbonMonoxide
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasMethane
constexpr std::array< std::string_view, 6 > PartitionFunctions::hasOxygen
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasNitricOxide
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasSulfurDioxide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasNitrogenDioxide
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasAmmonia
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasNitricAcid
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasHydroxyl
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasHydrogenFluoride
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasHydrogenChloride
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasHydrogenBromide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasHydrogenIodide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasChlorineMonoxide
constexpr std::array< std::string_view, 6 > PartitionFunctions::hasCarbonylSulfide
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasFormaldehyde
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHeavyFormaldehyde
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasVeryHeavyFormaldehyde
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasHypochlorousAcid
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasNitrogen
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasHydrogenCyanide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasChloromethane
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHydrogenPeroxide
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasAcetylene
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasEthane
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasPhosphine
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasCarbonylFluoride
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasSulfurHexafluoride
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasHydrogenSulfide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasFormicAcid
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasLeftHeavyFormicAcid
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasRightHeavyFormicAcid
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHydroperoxyl
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasOxygenAtom
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasChlorineNitrate
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasNitricOxideCation
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasChlorineDioxide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasBromineMonoxide
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasSulfuricAcid
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasChlorineMonoxideDimer
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasHypobromousAcid
constexpr std::array< std::string_view, 5 > PartitionFunctions::hasEthylene
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasMethanol
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasBromomethane
constexpr std::array< std::string_view, 5 > PartitionFunctions::hasAcetonitrile
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHeavyAcetonitrile
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasCarbonTetrafluoride
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasDiacetylene
constexpr std::array< std::string_view, 6 > PartitionFunctions::hasCyanoacetylene
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasHydrogen
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasCarbonMonosulfide
constexpr std::array< std::string_view, 4 > PartitionFunctions::hasHydrogenIsocyanide
constexpr std::array< std::string_view, 3 > PartitionFunctions::hasSulfurMonoxide
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasPropane
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHydrogenAtom
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasHelium
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasArgon
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasSulfurTrioxide
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasCyanogen
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasPhosgene
constexpr std::array< std::string_view, 5 > PartitionFunctions::hasCarbonDisulfide
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasMethyl
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasCyclopropene
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHexafluoroethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluoropropane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluorobutane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluoropentane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluorohexane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluorooctane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasPerfluorocyclobutane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCarbonTetrachloride
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCFC11
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCFC113
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCFC114
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCFC115
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasCFC12
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasDichloromethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasTrichloroethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasTrichloromethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasBromochlorodifluoromethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasBromotrifluoromethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasDibromotetrafluoroethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHCFC141b
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHCFC142b
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHCFC22
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC125
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC134a
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC143a
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC152a
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC227ea
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC23
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC245fa
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC32
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasNitrogenTrifluoride
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasSulfurylFluoride
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasHFC4310mee
constexpr std::array< std::string_view, 5 > PartitionFunctions::hasGermane
constexpr std::array< std::string_view, 2 > PartitionFunctions::hasIodomethane
constexpr std::array< std::string_view, 1 > PartitionFunctions::hasFluoromethane
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasliquidcloud
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasicecloud
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasrain
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasfree_electrons
constexpr std::array< std::string_view, 0 > PartitionFunctions::hasparticles
Function Documentation
column_string()
template<std::size_t N> std::string column_string (const std::array< std::string_view, N > & list)
Auto-generated partition function data.
Definition at line 11 of file auto_partfun.h.
References N, and ARTS::Var::x().
Referenced by PartitionFunctions::computeAcetonitrile(), PartitionFunctions::computeAcetylene(), PartitionFunctions::computeAmmonia(), PartitionFunctions::computeArgon(), PartitionFunctions::computeBath(), PartitionFunctions::computeBromineMonoxide(), PartitionFunctions::computeBromochlorodifluoromethane(), PartitionFunctions::computeBromomethane(), PartitionFunctions::computeBromotrifluoromethane(), PartitionFunctions::computeCarbonDioxide(), PartitionFunctions::computeCarbonDisulfide(), PartitionFunctions::computeCarbonMonosulfide(), PartitionFunctions::computeCarbonMonoxide(), PartitionFunctions::computeCarbonTetrachloride(), PartitionFunctions::computeCarbonTetrafluoride(), PartitionFunctions::computeCarbonylFluoride(), PartitionFunctions::computeCarbonylSulfide(), PartitionFunctions::computeCFC11(), PartitionFunctions::computeCFC113(), PartitionFunctions::computeCFC114(), PartitionFunctions::computeCFC115(), PartitionFunctions::computeCFC12(), PartitionFunctions::computeChlorineDioxide(), PartitionFunctions::computeChlorineMonoxide(), PartitionFunctions::computeChlorineMonoxideDimer(), PartitionFunctions::computeChlorineNitrate(), PartitionFunctions::computeChloromethane(), PartitionFunctions::computeCyanoacetylene(), PartitionFunctions::computeCyanogen(), PartitionFunctions::computeCyclopropene(), PartitionFunctions::computeDiacetylene(), PartitionFunctions::computeDibromotetrafluoroethane(), PartitionFunctions::computeDichloromethane(), PartitionFunctions::computeEthane(), PartitionFunctions::computeEthylene(), PartitionFunctions::computeFluoromethane(), PartitionFunctions::computeFormaldehyde(), PartitionFunctions::computeFormicAcid(), PartitionFunctions::computefree_electrons(), PartitionFunctions::computeGermane(), PartitionFunctions::computeHCFC141b(), PartitionFunctions::computeHCFC142b(), PartitionFunctions::computeHCFC22(), PartitionFunctions::computeHeavyAcetonitrile(), PartitionFunctions::computeHeavyFormaldehyde(), PartitionFunctions::computeHelium(), PartitionFunctions::computeHexafluoroethane(), PartitionFunctions::computeHFC125(), PartitionFunctions::computeHFC134a(), PartitionFunctions::computeHFC143a(), PartitionFunctions::computeHFC152a(), PartitionFunctions::computeHFC227ea(), PartitionFunctions::computeHFC23(), PartitionFunctions::computeHFC245fa(), PartitionFunctions::computeHFC32(), PartitionFunctions::computeHFC4310mee(), PartitionFunctions::computeHydrogen(), PartitionFunctions::computeHydrogenAtom(), PartitionFunctions::computeHydrogenBromide(), PartitionFunctions::computeHydrogenChloride(), PartitionFunctions::computeHydrogenCyanide(), PartitionFunctions::computeHydrogenFluoride(), PartitionFunctions::computeHydrogenIodide(), PartitionFunctions::computeHydrogenIsocyanide(), PartitionFunctions::computeHydrogenPeroxide(), PartitionFunctions::computeHydrogenSulfide(), PartitionFunctions::computeHydroperoxyl(), PartitionFunctions::computeHydroxyl(), PartitionFunctions::computeHypobromousAcid(), PartitionFunctions::computeHypochlorousAcid(), PartitionFunctions::computeicecloud(), PartitionFunctions::computeIodomethane(), PartitionFunctions::computeLeftHeavyFormicAcid(), PartitionFunctions::computeliquidcloud(), PartitionFunctions::computeMethane(), PartitionFunctions::computeMethanol(), PartitionFunctions::computeMethyl(), PartitionFunctions::computeNitricAcid(), PartitionFunctions::computeNitricOxide(), PartitionFunctions::computeNitricOxideCation(), PartitionFunctions::computeNitrogen(), PartitionFunctions::computeNitrogenDioxide(), PartitionFunctions::computeNitrogenOxide(), PartitionFunctions::computeNitrogenTrifluoride(), PartitionFunctions::computeOxygen(), PartitionFunctions::computeOxygenAtom(), PartitionFunctions::computeOzone(), PartitionFunctions::computeparticles(), PartitionFunctions::computePerfluorobutane(), PartitionFunctions::computePerfluorocyclobutane(), PartitionFunctions::computePerfluorohexane(), PartitionFunctions::computePerfluorooctane(), PartitionFunctions::computePerfluoropentane(), PartitionFunctions::computePerfluoropropane(), PartitionFunctions::computePhosgene(), PartitionFunctions::computePhosphine(), PartitionFunctions::computePropane(), PartitionFunctions::computerain(), PartitionFunctions::computeRightHeavyFormicAcid(), PartitionFunctions::computeSulfurDioxide(), PartitionFunctions::computeSulfurHexafluoride(), PartitionFunctions::computeSulfuricAcid(), PartitionFunctions::computeSulfurMonoxide(), PartitionFunctions::computeSulfurTrioxide(), PartitionFunctions::computeSulfurylFluoride(), PartitionFunctions::computeTrichloroethane(), PartitionFunctions::computeTrichloromethane(), PartitionFunctions::computeVeryHeavyFormaldehyde(), and PartitionFunctions::computeWater().