ARTS: bifstream.cc File Reference
bifstream.cc File Reference
This file contains the class implementation of bifstream.
#include "bifstream.h"
#include <fstream>
#include <stdexcept>
Functions
bifstream & operator>> (bifstream &bif, double &n)
bifstream & operator>> (bifstream &bif, float &n)
bifstream & operator>> (bifstream &bif, long &n)
bifstream & operator>> (bifstream &bif, int &n)
Detailed Description
This file contains the class implementation of bifstream.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-01-23
Definition in file bifstream.cc.
Function Documentation
operator>>() [1/4]
bifstream& operator>> (bifstream & bif, double & n)
Definition at line 75 of file bifstream.cc.
References binio::Double, and binistream::readFloat().
operator>>() [2/4]
bifstream& operator>> (bifstream & bif, float & n)
Definition at line 80 of file bifstream.cc.
References binio::Double, and binistream::readFloat().
operator>>() [3/4]
bifstream& operator>> (bifstream & bif, int & n)
Definition at line 90 of file bifstream.cc.
References binistream::readInt().
operator>>() [4/4]
bifstream& operator>> (bifstream & bif, long & n)
Definition at line 85 of file bifstream.cc.
References binistream::readInt().