ARTS: bofstream.cc File Reference
bofstream.cc File Reference
This file contains the class implementation of bofstream.
#include "bofstream.h"
#include <fstream>
#include <stdexcept>
Functions
bofstream & operator<< (bofstream &bof, double n)
bofstream & operator<< (bofstream &bof, float n)
bofstream & operator<< (bofstream &bof, long n)
bofstream & operator<< (bofstream &bof, int n)
Detailed Description
This file contains the class implementation of bofstream.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-01-21
Definition in file bofstream.cc.
Function Documentation
operator<<() [1/4]
bofstream& operator<< (bofstream & bof, double n)
Definition at line 76 of file bofstream.cc.
References binio::Double, and binostream::writeFloat().
operator<<() [2/4]
bofstream& operator<< (bofstream & bof, float n)
Definition at line 81 of file bofstream.cc.
References binio::Double, and binostream::writeFloat().
operator<<() [3/4]
bofstream& operator<< (bofstream & bof, int n)
Definition at line 91 of file bofstream.cc.
References binostream::writeInt().
operator<<() [4/4]
bofstream& operator<< (bofstream & bof, long n)
Definition at line 86 of file bofstream.cc.
References binostream::writeInt().