ARTS: check_input.cc File Reference
check_input.cc File Reference
#include "check_input.h"
#include <cfloat>
#include <cmath>
#include <stdexcept>
#include "array.h"
#include "auto_md.h"
#include "gridded_fields.h"
#include "logic.h"
Functions
void chk_if_bool (const String &x_name, const Index &x)
chk_if_bool
void chk_if_in_range (const String &x_name, const Index &x, const Index &x_low, const Index &x_high)
chk_if_in_range
void chk_if_increasing (const String &x_name, const ArrayOfIndex &x)
chk_if_increasing
void chk_not_negative (const String &x_name, const Numeric &x)
chk_not_negative
void chk_if_in_range (const String &x_name, const Numeric &x, const Numeric &x_low, const Numeric &x_high)
chk_if_in_range
void chk_if_in_range_exclude_low (const String &x_name, const Numeric &x, const Numeric &x_low, const Numeric &x_high)
chk_if_in_range_exclude_low
void chk_if_in_range_exclude_high (const String &x_name, const Numeric &x, const Numeric &x_low, const Numeric &x_high)
chk_if_in_range_exclude_high
void chk_if_in_range_exclude (const String &x_name, const Numeric &x, const Numeric &x_low, const Numeric &x_high)
chk_if_in_range_exclude
void chk_vector_length (const String &x_name, ConstVectorView x, const Index &l)
chk_vector_length
void chk_vector_length (const String &x1_name, const String &x2_name, ConstVectorView x1, ConstVectorView x2)
chk_vector_length
void chk_if_increasing (const String &x_name, ConstVectorView x)
chk_if_increasing
void chk_if_decreasing (const String &x_name, ConstVectorView x)
chk_if_decreasing
void chk_if_equal (const String &x1_name, const String &x2_name, ConstVectorView v1, ConstVectorView v2, Numeric margin)
chk_if_equal
void chk_matrix_ncols (const String &x_name, ConstMatrixView x, const Index &l)
chk_matrix_ncols
void chk_matrix_nrows (const String &x_name, ConstMatrixView x, const Index &l)
chk_matrix_nrows
void chk_size (const String &x_name, ConstVectorView x, const Index &c)
Runtime check for size of Vector.
void chk_size (const String &x_name, ConstMatrixView x, const Index &r, const Index &c)
Runtime check for size of Matrix.
void chk_size (const String &x_name, ConstTensor3View x, const Index &p, const Index &r, const Index &c)
Runtime check for size of Tensor.
void chk_size (const String &x_name, ConstTensor4View x, const Index &b, const Index &p, const Index &r, const Index &c)
Runtime check for size of Tensor.
void chk_size (const String &x_name, ConstTensor5View x, const Index &s, const Index &b, const Index &p, const Index &r, const Index &c)
Runtime check for size of Tensor.
void chk_size (const String &x_name, ConstTensor6View x, const Index &v, const Index &s, const Index &b, const Index &p, const Index &r, const Index &c)
Runtime check for size of Tensor.
void chk_size (const String &x_name, ConstTensor7View x, const Index &l, const Index &v, const Index &s, const Index &b, const Index &p, const Index &r, const Index &c)
Runtime check for size of Tensor.
void chk_not_empty (const String &x_name, const Agenda &x)
chk_not_empty
void chk_interpolation_grids_loose (Index &ing_min, Index &ing_max, const String &which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, ConstVectorView data, const Index order)
Check interpolation grids.
void chk_interpolation_grids_loose_no_data_check (Index &ing_min, Index &ing_max, const String &which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, const Index order)
Check interpolation grids.
void chk_interpolation_pgrids_loose_no_data_check (Index &ing_min, Index &ing_max, const String &which_interpolation, ConstVectorView old_pgrid, ConstVectorView new_pgrid, const Index order)
Check log pressure interpolation grids.
void chk_interpolation_grids_loose_check_data (Index &ing_min, Index &ing_max, const String &which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, ConstVectorView data)
Check interpolation grids.
void chk_interpolation_grids (const String &which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, const Index order, const Numeric &extpolfac, const bool islog)
Check interpolation grids.
void chk_interpolation_grids (const String &which_interpolation, ConstVectorView old_grid, const Numeric &new_grid, const Index order, const Numeric &extpolfac)
Check interpolation grids.
void chk_interpolation_pgrids (const String &which_interpolation, ConstVectorView old_pgrid, ConstVectorView new_pgrid, const Index order, const Numeric &extpolfac)
Check log pressure interpolation grids.
void chk_atm_grids (const Index &dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid)
chk_atm_grids
void chk_atm_field (const String &x_name, ConstTensor3View x, const Index &dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, const bool &chk_lat90)
chk_atm_field (simple fields)
void chk_atm_field (const String &x_name, ConstTensor4View x, const Index &dim, const Index &nspecies, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, const bool &check_nan)
chk_atm_field (fields with one more dimension)
void chk_atm_vecfield_lat90 (const String &x1_name, ConstTensor3View x1, const String &x2_name, ConstTensor3View x2, const Index &dim, ConstVectorView lat_grid, const Numeric &threshold)
chk_atm_vecfield_lat90
void chk_latlon_true (const Index &atmosphere_dim, ConstVectorView lat_grid, ConstVectorView lat_true, ConstVectorView lon_true)
chk_latlon_true
void chk_atm_surface (const String &x_name, const Matrix &x, const Index &dim, ConstVectorView lat_grid, ConstVectorView lon_grid)
chk_atm_surface
void chk_rte_pos (const Index &atmosphere_dim, ConstVectorView rte_pos, const bool &is_rte_pos2)
chk_rte_pos
void chk_rte_los (const Index &atmosphere_dim, ConstVectorView rte_los)
chk_rte_los
void chk_griddedfield_gridname (const GriddedField &gf, const Index gridindex, const String &gridname)
Check name of grid in GriddedField.
void chk_met_mm_backend (const Matrix &mmb)
Check met_mm_backend.
Variables
const Index GFIELD3_P_GRID
const Index GFIELD3_LAT_GRID
const Index GFIELD3_LON_GRID
Detailed Description
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-04-15
General functions to check the size and logic of input to functions.
Definition in file check_input.cc.
Function Documentation
chk_atm_field() [1/2]
void chk_atm_field (const String & x_name, ConstTensor3View x, const Index & dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, const bool & chk_lat90)
chk_atm_field (simple fields)
Checks if an atmospheric field matches the dimensionality and the grids.
The function gives an error message if this is not the case.
Parameters
x_name The name of the atmospheric field.
x A variable holding an atmospheric field.
dim The atmospheric dimensionality.
p_grid The pressure grid.
lat_grid The latitude grid.
lon_grid The longitude grid.
chk_lat90 Flag whether pole consistency check to be done (only relevant for dim==3.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 1268 of file check_input.cc.
References chk_if_bool(), is_lon_cyclic(), is_same_within_epsilon(), max, ConstTensor3View::ncols(), ConstVectorView::nelem(), ConstTensor3View::npages(), and ConstTensor3View::nrows().
Referenced by AtmFieldPerturb(), AtmFieldPerturbAtmGrids(), atmfields_checkedCalc(), AtmFieldsExpand1D(), AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), cloudbox_checkedCalc(), InterpAtmFieldToPosition(), pnd_fieldCalcFromParticleBulkProps(), and wind_u_fieldIncludePlanetRotation().
chk_atm_field() [2/2]
void chk_atm_field (const String & x_name, ConstTensor4View x, const Index & dim, const Index & nspecies, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, const bool & check_nan)
chk_atm_field (fields with one more dimension)
Checks if an atmospheric field matches the dimensionality and the grids. This is the version for fields like vmr_field, which are a Tensor4, not a Tensor3. (First dimension is the gas species.)
The function gives an error message if this is not the case.
Parameters
x_name The name of the atmospheric field.
x A variable holding an atmospheric field.
dim The atmospheric dimensionality.
nspecies Number of species.
p_grid The pressure grid.
lat_grid The latitude grid.
lon_grid The longitude grid.
Author
Stefan Buehler, cloned from Patrick Eriksson
Date
2002-12-20
Definition at line 1394 of file check_input.cc.
References is_same_within_epsilon(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstVectorView::nelem(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
chk_atm_grids()
void chk_atm_grids (const Index & dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid)
chk_atm_grids
Checks if the atmospheric grids and the specified atmospheric dimensionality match, and if the grids are ordered correctly.
The function gives an error message if this is not the case.
Parameters
dim The atmospheric dimensionality.
p_grid The pressure grid.
lat_grid The latitude grid.
lon_grid The longitude grid.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 1201 of file check_input.cc.
References chk_if_decreasing(), chk_if_increasing(), and ConstVectorView::nelem().
Referenced by atmfields_checkedCalc(), AtmFieldsCalc(), AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), cloudbox_field_monoSetConst(), cloudbox_fieldUpdateSeq3D(), cloudboxSetAutomatically(), cloudboxSetManually(), InterpAtmFieldToPosition(), InterpSurfaceFieldToPosition(), MagFieldsCalc(), MagFieldsCalcExpand1D(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), WindFieldsCalc(), and WindFieldsCalcExpand1D().
chk_atm_surface()
void chk_atm_surface (const String & x_name, const Matrix & x, const Index & dim, ConstVectorView lat_grid, ConstVectorView lon_grid)
chk_atm_surface
Checks if a surface-type variable matches the dimensionality and the grids.
The function gives an error message if this is not the case.
Parameters
x_name The name of the surface-type variable.
x The variable holding the surface data.
dim The atmospheric dimensionality.
lat_grid The latitude grid.
lon_grid The longitude grid.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 1689 of file check_input.cc.
References is_same_within_epsilon(), ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by atmgeom_checkedCalc(), and InterpSurfaceFieldToPosition().
chk_atm_vecfield_lat90()
void chk_atm_vecfield_lat90 (const String & x1_name, ConstTensor3View x1, const String & x2_name, ConstTensor3View x2, const Index & dim, ConstVectorView lat_grid, const Numeric & threshold)
chk_atm_vecfield_lat90
Checks if a two-compnent vector atmospheric field is consistant at the poles.
Similar to the field-constant at poles check of chk_atm_field, but checking the total vector instead of each component to be constant (since this involves some numerics, we allow a deviation threshold instead of perfect match). Note that each component of the vector is stored in a separate atmospheric field. Intended for variables that are supposed to be two horizontal components of a 3D vector field (e.g., winds, magnetic field). It is assumed that individual fields have passed chk_atm_field. The function gives an error message if a mismatch is encountered.
Parameters
x1_name The name of the atmospheric field.
x1 A variable holding an atmospheric field.
x2_name The name of the atmospheric field.
x2 A variable holding an atmospheric field.
dim The atmospheric dimensionality.
lat_grid The latitude grid.
threshold The percentage threshold the total vector lengths along the pole are allowed to deviate.
Author
Jana Mendrok
Date
2012-06-29
Definition at line 1540 of file check_input.cc.
References sqrt(), x1, and x2.
Referenced by atmfields_checkedCalc().
chk_griddedfield_gridname()
void chk_griddedfield_gridname (const GriddedField & gf, const Index gridindex, const String & gridname)
Check name of grid in GriddedField.
Does a case-insensitive check to verify that the name of the grid at the given index in the GriddedField has the expected name.
Parameters
gf GriddedField to check. Can be a GriddedField of any dimension.
gridindex Index of grid.
gridname Expected name of grid.
Definition at line 1891 of file check_input.cc.
References GriddedField::get_dim(), GriddedField::get_grid_name(), GriddedField::get_name(), my_basic_string< charT >::nelem(), and my_basic_string< charT >::toupper().
Referenced by complex_n_interp(), FieldFromGriddedField(), FieldFromGriddedFieldCheckLatLonHelper(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegridHelper(), GriddedFieldPRegridHelper(), GriddedFieldZToPRegrid(), GriddedFieldZToPRegridHelper(), InterpGriddedField2ToPosition(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), and surface_typeInterpTypeMask().
chk_if_bool()
void chk_if_bool (const String & x_name, const Index & x)
chk_if_bool
Checks that a variable of type Index has the value 0 or 1.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Index.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 65 of file check_input.cc.
References is_bool().
Referenced by chk_atm_field(), cloudbox_checkedCalc(), sensor_responseAntenna(), sensor_responseInit(), and sensor_responseMetMM().
chk_if_decreasing()
void chk_if_decreasing (const String & x_name, ConstVectorView x)
chk_if_decreasing
Checks if a vector is strictly decreasing.
Duplicated values are not allowed.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Vector.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 358 of file check_input.cc.
References is_decreasing().
Referenced by GasAbsLookup::Adapt(), chk_atm_grids(), cloudbox_fieldUpdate1D(), and cloudbox_fieldUpdateSeq1D().
chk_if_equal()
void chk_if_equal (const String & x1_name, const String & x2_name, ConstVectorView v1, ConstVectorView v2, Numeric margin)
chk_if_equal
Checks if two vectors are equal within a margin.
Parameters
x1_name The name of the first variable (used in error message).
x2_name The name of the second variable (used in error message).
v1 First vector
v2 Second vector
margin uncertainty margin. Default: 1e-6
Author
Gerrit Holl
Date
2011-05-04
Definition at line 381 of file check_input.cc.
References abs, chk_vector_length(), and ConstVectorView::nelem().
Referenced by FieldFromGriddedField(), and FieldFromGriddedFieldCheckLatLonHelper().
chk_if_in_range() [1/2]
void chk_if_in_range (const String & x_name, const Index & x, const Index & x_low, const Index & x_high)
chk_if_in_range
Checks that a variable of type Index has a value inside the specified range.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Index.
x_low Lowest allowed value for x.
x_high Highest allowed value for x.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 89 of file check_input.cc.
Referenced by GasAbsLookup::Adapt(), AntennaMultiBeamsToPencilBeams(), atmfields_checkedCalc(), AtmFieldsCalc(), AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), atmgeom_checkedCalc(), cloudbox_field_monoSetConst(), cloudboxSetAutomatically(), cloudboxSetManually(), cloudboxSetManuallyAltitude(), complex_n_ice_matzler06(), complex_n_water_liebe93(), complex_refr_indexIceMatzler06(), doit_za_interpSet(), DoitGetIncoming(), DoitGetIncoming1DAtm(), DoitInit(), FastemStandAlone(), InterpGriddedField2ToPosition(), iyActiveSingleScat(), iyActiveSingleScat2(), iySurfaceRtpropAgenda(), iySurfaceRtpropCalc(), MagFieldsCalc(), MagFieldsCalcExpand1D(), MCGeneral(), MCRadar(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldZero(), propmat_clearsky_fieldCalc(), refellipsoidOrbitPlane(), rte_losSet(), rte_pos_losMoveToStartOfPpath(), rte_posSet(), ScatElementsPndAndScatAdd(), ScatElementsToabs_speciesAdd(), ScatSpeciesPndAndScatAdd(), sensor_responseAntenna(), sensor_responseInit(), sensor_responseStokesRotation(), specular_losCalc(), specular_losCalcNoTopography(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), surfaceBlackbody(), surfaceFastem(), surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), surfaceTelsem(), surfaceTessem(), telsemAtlasLookup(), telsemStandalone(), telsemSurfaceTypeLandSea(), vmr_fieldSetConstant(), WindFieldsCalc(), WindFieldsCalcExpand1D(), yActive(), and yCalc().
chk_if_in_range() [2/2]
void chk_if_in_range (const String & x_name, const Numeric & x, const Numeric & x_low, const Numeric & x_high)
chk_if_in_range
Checks that a variable of type Numeric has a value inside the specified range.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Numeric.
x_low Lowest allowed value for x.
x_high Highest allowed value for x.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 167 of file check_input.cc.
chk_if_in_range_exclude()
void chk_if_in_range_exclude (const String & x_name, const Numeric & x, const Numeric & x_low, const Numeric & x_high)
chk_if_in_range_exclude
Checks that a variable of type Numeric has a value inside the specified range. The low and high values are excluded from the valid range.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Numeric.
x_low Lowest allowed value for x.
x_high Highest allowed value for x.
Author
Oliver Lemke
Date
2016-05-10
Definition at line 251 of file check_input.cc.
Referenced by FastemStandAlone(), surfaceTelsem(), and surfaceTessem().
chk_if_in_range_exclude_high()
void chk_if_in_range_exclude_high (const String & x_name, const Numeric & x, const Numeric & x_low, const Numeric & x_high)
chk_if_in_range_exclude_high
Checks that a variable of type Numeric has a value inside the specified range. The high value is excluded from the valid range.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Numeric.
x_low Lowest allowed value for x.
x_high Highest allowed value for x.
Author
Oliver Lemke
Date
2016-05-10
Definition at line 223 of file check_input.cc.
Referenced by FastemStandAlone(), and surfaceTessem().
chk_if_in_range_exclude_low()
void chk_if_in_range_exclude_low (const String & x_name, const Numeric & x, const Numeric & x_low, const Numeric & x_high)
chk_if_in_range_exclude_low
Checks that a variable of type Numeric has a value inside the specified range. The low value is excluded from the valid range.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Numeric.
x_low Lowest allowed value for x.
x_high Highest allowed value for x.
Author
Oliver Lemke
Date
2016-05-10
Definition at line 195 of file check_input.cc.
chk_if_increasing() [1/2]
void chk_if_increasing (const String & x_name, const ArrayOfIndex & x)
chk_if_increasing
Checks if an ArrayOfIndex is strictly increasing. Cloned from Patricks similar function for Vector.
Duplicated values are not allowed.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type ArrayOfIndex.
Author
Stefan Buehler
Date
2007-05-18
Definition at line 117 of file check_input.cc.
References is_increasing().
Referenced by GasAbsLookup::Adapt(), atmgeom_checkedCalc(), chk_atm_grids(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq3D(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), DoitCalc(), scat_data_checkedCalc(), ScatElementsToabs_speciesAdd(), sensor_responseAntenna(), WMRFSelectChannels(), yActive(), and yCalc().
chk_if_increasing() [2/2]
void chk_if_increasing (const String & x_name, ConstVectorView x)
chk_if_increasing
Checks if a vector is strictly increasing.
Duplicated values are not allowed.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Vector.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 334 of file check_input.cc.
References is_increasing().
chk_interpolation_grids() [1/2]
void chk_interpolation_grids (const String & which_interpolation, ConstVectorView old_grid, const Numeric & new_grid, const Index order, const Numeric & extpolfac)
Check interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking.
This is for the special case that the new grid is just a single Numeric, instead of a Vector. ("Red" interpolation.) It just calles the other more general chk_interpolation_grids function for which both grid arguments are vectors.
Parameters
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Stefan Buehler
Date
2008-11-24
Definition at line 1139 of file check_input.cc.
References chk_interpolation_grids().
chk_interpolation_grids() [2/2]
void chk_interpolation_grids (const String & which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, const Index order, const Numeric & extpolfac, const bool islog)
Check interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking.
Parameters
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Stefan Buehler
Date
2008-11-24
Definition at line 989 of file check_input.cc.
References is_decreasing(), is_increasing(), max, min, and ConstVectorView::nelem().
Referenced by atm_fields_compactAddSpecies(), chk_interpolation_grids(), chk_interpolation_pgrids(), cia_interpolation(), cloudbox_field_monoOptimizeReverse(), complex_n_interp(), XsecRecord::Extract(), GriddedFieldLatLonRegridHelper(), gridpos_poly_longitudinal(), InterpSurfaceFieldToPosition(), MagFieldsCalc(), MagFieldsFromAltitudeRawCalc(), opt_prop_sptFromData(), opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), rte_pos2gridpos(), scat_dataCalc(), scat_dataReduceT(), ScatElementsToabs_speciesAdd(), ScatSpeciesMerge(), specular_losCalc(), ssd_tinterp_parameters(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), and WindFieldsCalc().
chk_interpolation_grids_loose()
void chk_interpolation_grids_loose (Index & ing_min, Index & ing_max, const String & which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, ConstVectorView data, const Index order)
Check interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking. If the original grid does not have to cover the whole new grid. The returned ing_min and ing_max give the positions in the new grid of the first values that are outside the old grid. This is only allowed if the boundary value in the input data is 0.
Parameters
[out] ing_min Index in the new grid with first value covered by the old grid.
[out] ing_max Index in the new grid with last value covered by the old grid.
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] data The data for the interpolation.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Oliver Lemke
Date
2012-07-11
Definition at line 735 of file check_input.cc.
References chk_interpolation_grids_loose_check_data(), chk_interpolation_grids_loose_no_data_check(), and data.
chk_interpolation_grids_loose_check_data()
void chk_interpolation_grids_loose_check_data (Index & ing_min, Index & ing_max, const String & which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, ConstVectorView data)
Check interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking. If the original grid does not have to cover the whole new grid. The returned ing_min and ing_max give the positions in the new grid of the first values that are outside the old grid. This is only allowed if the boundary value in the input data is 0.
Parameters
[out] ing_min Index in the new grid with first value covered by the old grid.
[out] ing_max Index in the new grid with last value covered by the old grid.
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] data The data for the interpolation.
Author
Oliver Lemke
Date
2012-03-28
Definition at line 930 of file check_input.cc.
References data, and ConstVectorView::nelem().
Referenced by chk_interpolation_grids_loose().
chk_interpolation_grids_loose_no_data_check()
void chk_interpolation_grids_loose_no_data_check (Index & ing_min, Index & ing_max, const String & which_interpolation, ConstVectorView old_grid, ConstVectorView new_grid, const Index order)
Check interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking. The original grid does not have to cover the whole new grid. The returned ing_min and ing_max give the positions in the new grid of the first values that are outside the old grid.
Parameters
[out] ing_min Index in the new grid with first value covered by the old grid.
[out] ing_max Index in the new grid with last value covered by the old grid.
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Oliver Lemke (based on chk_interpolation_grids by Stefan)
Date
2012-03-28
Definition at line 773 of file check_input.cc.
References is_decreasing(), is_increasing(), max, min, and ConstVectorView::nelem().
Referenced by chk_interpolation_grids_loose(), chk_interpolation_pgrids_loose_no_data_check(), and GriddedFieldZToPRegridHelper().
chk_interpolation_pgrids()
void chk_interpolation_pgrids (const String & which_interpolation, ConstVectorView old_pgrid, ConstVectorView new_pgrid, const Index order, const Numeric & extpolfac)
Check log pressure interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking.
Parameters
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_pgrid The original grid.
[in] new_pgrid The new grid.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Oliver Lemke
Date
2012-07-11
Definition at line 1166 of file check_input.cc.
References chk_interpolation_grids(), ConstVectorView::nelem(), and transform().
Referenced by AtmFieldPRegridHelper(), GriddedFieldPRegridHelper(), GriddedFieldZToPRegridHelper(), MagFieldsCalc(), and WindFieldsCalc().
chk_interpolation_pgrids_loose_no_data_check()
void chk_interpolation_pgrids_loose_no_data_check (Index & ing_min, Index & ing_max, const String & which_interpolation, ConstVectorView old_pgrid, ConstVectorView new_pgrid, const Index order)
Check log pressure interpolation grids.
This function checks if old and new grid for an interpolation are ok. If not, it throws a detailed runtime error message. This is intended for workspace method input variable checking. The original grid does not have to cover the whole new grid. The returned ing_min and ing_max give the positions in the new grid of the first values that are outside the old grid.
Parameters
[out] ing_min Index in the new grid with first value covered by the old grid.
[out] ing_max Index in the new grid with last value covered by the old grid.
[in] which_interpolation A string describing the interpolation for which the grids are intended.
[in] old_grid The original grid.
[in] new_grid The new grid.
[in] order Interpolation order. (Default value is 1.)
[in] extpolfac The extrapolation fraction. See gridpos function for details. Has a default value, which is consistent with gridpos.
Author
Oliver Lemke (based on chk_interpolation_grids by Stefan)
Date
2012-03-28
Definition at line 890 of file check_input.cc.
References chk_interpolation_grids_loose_no_data_check(), ConstVectorView::nelem(), and transform().
Referenced by GriddedFieldPRegridHelper().
chk_latlon_true()
void chk_latlon_true (const Index & atmosphere_dim, ConstVectorView lat_grid, ConstVectorView lat_true, ConstVectorView lon_true)
chk_latlon_true
Checks that lat_true and lon_true have the correct size for 1D and 2D cases (they are not used for 3D).
Parameters
atmosphere_dim As the WSV with the same name
lat_grid As the WSV with the same name
lat_true As the WSV with the same name
lon_true As the WSV with the same name
Author
Patrick Eriksson
Date
2012-03-19
Definition at line 1652 of file check_input.cc.
References ConstVectorView::nelem().
Referenced by InterpGriddedField2ToPosition(), iyIndependentBeamApproximation(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), telsemSurfaceTypeLandSea(), and z_fieldFromHSE().
chk_matrix_ncols()
void chk_matrix_ncols (const String & x_name, ConstMatrixView x, const Index & l)
chk_matrix_ncols
Checks that a matrix has the specified number of columns.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A matrix.
l The expected length of x.
Author
Patrick Eriksson
Date
2002-05-16
Definition at line 419 of file check_input.cc.
References ConstMatrixView::ncols().
Referenced by GasAbsLookup::Adapt().
chk_matrix_nrows()
void chk_matrix_nrows (const String & x_name, ConstMatrixView x, const Index & l)
chk_matrix_nrows
Checks that a matrix has the specified number of rows.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A matrix.
l The expected length of x.
Author
Patrick Eriksson
Date
2002-05-16
Definition at line 441 of file check_input.cc.
References ConstMatrixView::nrows().
Referenced by GasAbsLookup::Adapt().
chk_met_mm_backend()
void chk_met_mm_backend (const Matrix & mmb)
Check met_mm_backend.
Verifies that the backend description matrix has the correct size and format.
Parameters
[in] mmb met_mm_backend
Exceptions
std::runtime_error
Author
Oliver Lemke
Definition at line 1931 of file check_input.cc.
References ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by f_gridMetMM().
chk_not_empty()
void chk_not_empty (const String & x_name, const Agenda & x)
chk_not_empty
Checks that an agenda is not empty.
The function gives an error message if the agenda is empty.
Parameters
x_name The name of the agenda.
x A variable of type Agenda.
Author
Patrick Eriksson
Date
2002-08-20
Definition at line 694 of file check_input.cc.
References Agenda::nelem().
Referenced by cloud_RT_surface(), cloudbox_field_monoIterate(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq3D(), doit_scat_fieldCalc(), doit_scat_fieldCalcLimb(), DoitCalc(), get_iy_of_background(), and surf_albedoCalc().
chk_not_negative()
void chk_not_negative (const String & x_name, const Numeric & x)
chk_not_negative
Checks that a variable of type Numeric is 0 or positive.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Numeric.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 143 of file check_input.cc.
Referenced by surfaceBlackbody(), surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), surfaceFlatScalarReflectivity(), and surfaceLambertianSimple().
chk_rte_los()
void chk_rte_los (const Index & atmosphere_dim, ConstVectorView rte_los)
chk_rte_los
Performs all needed checks of rte_los
The function gives an error message if this is not the case.
Parameters
atmosphere_dim As the WSV with the same name.
rte_los As the WSV with the same name.
Author
Patrick Eriksson
Date
2012-03-26
Definition at line 1839 of file check_input.cc.
References ConstVectorView::nelem().
Referenced by iySurfaceRtpropAgenda(), iySurfaceRtpropCalc(), ppath_calc(), ppathPlaneParallel(), specular_losCalc(), specular_losCalcNoTopography(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surfaceBlackbody(), surfaceFastem(), surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), surfaceTelsem(), and surfaceTessem().
chk_rte_pos()
void chk_rte_pos (const Index & atmosphere_dim, ConstVectorView rte_pos, const bool & is_rte_pos2)
chk_rte_pos
Performs all needed checks of rte_pos and rte_pos2.
The function gives an error message if this is not the case.
Parameters
atmosphere_dim As the WSV with the same name.
rte_pos As WSV rte_pos or rte_pos2.
is_rte_pos2 True if rte_pos actually is rte_pos2.
Author
Patrick Eriksson
Date
2012-03-26
Definition at line 1770 of file check_input.cc.
References ConstVectorView::nelem().
Referenced by InterpAtmFieldToPosition(), InterpGriddedField2ToPosition(), InterpSurfaceFieldToPosition(), iySurfaceRtpropAgenda(), iySurfaceRtpropCalc(), ppath_calc(), ppathPlaneParallel(), rte_losGeometricFromRtePosToRtePos2(), rte_pos2gridpos(), specular_losCalc(), specular_losCalcNoTopography(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), surfaceBlackbody(), surfaceFastem(), surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), surfaceTelsem(), and surfaceTessem().
chk_size() [1/7]
void chk_size (const String & x_name, ConstMatrixView x, const Index & r, const Index & c)
Runtime check for size of Matrix.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Matrix.
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 490 of file check_input.cc.
chk_size() [2/7]
void chk_size (const String & x_name, ConstTensor3View x, const Index & p, const Index & r, const Index & c)
Runtime check for size of Tensor.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Tensor3.
p Required number of pages
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 518 of file check_input.cc.
chk_size() [3/7]
void chk_size (const String & x_name, ConstTensor4View x, const Index & b, const Index & p, const Index & r, const Index & c)
Runtime check for size of Tensor.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Tensor4.
b Required number of books
p Required number of pages
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 548 of file check_input.cc.
chk_size() [4/7]
void chk_size (const String & x_name, ConstTensor5View x, const Index & s, const Index & b, const Index & p, const Index & r, const Index & c)
Runtime check for size of Tensor.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Tensor5.
s Required number of shelves
b Required number of books
p Required number of pages
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 582 of file check_input.cc.
chk_size() [5/7]
void chk_size (const String & x_name, ConstTensor6View x, const Index & v, const Index & s, const Index & b, const Index & p, const Index & r, const Index & c)
Runtime check for size of Tensor.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Tensor6.
v Required number of vitrines
s Required number of shelves
b Required number of books
p Required number of pages
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 618 of file check_input.cc.
chk_size() [6/7]
void chk_size (const String & x_name, ConstTensor7View x, const Index & l, const Index & v, const Index & s, const Index & b, const Index & p, const Index & r, const Index & c)
Runtime check for size of Tensor.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Tensor7.
l Required number of libraries
v Required number of vitrines
s Required number of shelves
b Required number of books
p Required number of pages
r Required number of rows
c Required number of columns
Author
Stefan Buehler
Date
2002-11-29
Definition at line 656 of file check_input.cc.
chk_size() [7/7]
void chk_size (const String & x_name, ConstVectorView x, const Index & c)
Runtime check for size of Vector.
This is the runtime version of is_size. An appropriate error message is generated if the size is not correct.
Parameters
x_name The name of the agenda.
x A variable of type Vector.
c Required number of elements
Author
Stefan Buehler
Date
2002-11-29
Definition at line 466 of file check_input.cc.
Referenced by abs_coefCalcFromXsec(), GasAbsLookup::Adapt(), chk_scat_data(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq3D(), ConvertAzimuthallyRandomSingleScatteringData(), doit_za_grid_optCalc(), and FieldFromGriddedFieldCheckLatLonHelper().
chk_vector_length() [1/2]
void chk_vector_length (const String & x1_name, const String & x2_name, ConstVectorView x1, ConstVectorView x2)
chk_vector_length
Checks if two vectors have the same length.
The function gives an error message if this is not the case.
Parameters
x1_name The name of the first vector
x2_name The name of the second vector
x1 The first vector.
x2 The second vector.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 306 of file check_input.cc.
References x1, and x2.
chk_vector_length() [2/2]
void chk_vector_length (const String & x_name, ConstVectorView x, const Index & l)
chk_vector_length
Checks that a vector has the specified length.
The function gives an error message if this is not the case.
Parameters
x_name The name of the variable.
x A variable of type Vector.
l The expected length of x.
Author
Patrick Eriksson
Date
2002-04-15
Definition at line 281 of file check_input.cc.
References ConstVectorView::nelem().
Referenced by GasAbsLookup::Adapt(), chk_if_equal(), and FastemStandAlone().
Variable Documentation
GFIELD3_LAT_GRID
const Index GFIELD3_LAT_GRID extern
GFIELD3_LON_GRID
const Index GFIELD3_LON_GRID extern
GFIELD3_P_GRID
const Index GFIELD3_P_GRID extern