ARTS: ARTS::Var::ArrayOfArrayOfSpeciesTag Class Reference
ARTS::Var::ArrayOfArrayOfSpeciesTag Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfSpeciesTag () noexcept
ArrayOfArrayOfSpeciesTag (std::size_t i, void *x) noexcept
ArrayOfArrayOfSpeciesTag (const Group::ArrayOfArrayOfSpeciesTag &val) noexcept
~ArrayOfArrayOfSpeciesTag () noexcept
Group::ArrayOfArrayOfSpeciesTag & value () noexcept
const Group::ArrayOfArrayOfSpeciesTag & value () const noexcept
ArrayOfArrayOfSpeciesTag & operator= (const Group::ArrayOfArrayOfSpeciesTag &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfSpeciesTag * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfSpeciesTag &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 982 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfSpeciesTag() [1/3]
ARTS::Var::ArrayOfArrayOfSpeciesTag::ArrayOfArrayOfSpeciesTag () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 987 of file autoarts.h.
ArrayOfArrayOfSpeciesTag() [2/3]
ARTS::Var::ArrayOfArrayOfSpeciesTag::ArrayOfArrayOfSpeciesTag (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 990 of file autoarts.h.
ArrayOfArrayOfSpeciesTag() [3/3]
ARTS::Var::ArrayOfArrayOfSpeciesTag::ArrayOfArrayOfSpeciesTag (const Group::ArrayOfArrayOfSpeciesTag & val) inline noexcept
Construct from Group::ArrayOfArrayOfSpeciesTag. Leaves islast() true and isnull() false
Definition at line 993 of file autoarts.h.
~ArrayOfArrayOfSpeciesTag()
ARTS::Var::ArrayOfArrayOfSpeciesTag::~ArrayOfArrayOfSpeciesTag () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 996 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfSpeciesTag::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1014 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfArrayOfSpeciesTag().
isnull()
bool ARTS::Var::ArrayOfArrayOfSpeciesTag::isnull () const inline noexcept
Return true if there is no data
Definition at line 1011 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfSpeciesTag().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfSpeciesTag::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1017 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfSpeciesTag& ARTS::Var::ArrayOfArrayOfSpeciesTag::operator= (const Group::ArrayOfArrayOfSpeciesTag & t) inline noexcept
Set value from Group::ArrayOfArrayOfSpeciesTag. Works when isnull() is false
Definition at line 1005 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfSpeciesTag::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1008 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfArrayOfSpeciesTag& ARTS::Var::ArrayOfArrayOfSpeciesTag::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfSpeciesTag. Works when isnull() is false
Definition at line 1002 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfSpeciesTag& ARTS::Var::ArrayOfArrayOfSpeciesTag::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfSpeciesTag. Works when isnull() is false
Definition at line 999 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfSpeciesTag & var) friend
Output to stream of internal variable
Definition at line 1020 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfSpeciesTag::p private
Definition at line 983 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfSpeciesTag* ARTS::Var::ArrayOfArrayOfSpeciesTag::v private
Definition at line 984 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfSpeciesTag().
The documentation for this class was generated from the following file:
autoarts.h