ARTS: ARTS::Var::WorkspaceArrayOfStokesVector Class Reference
ARTS::Var::WorkspaceArrayOfStokesVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfStokesVector () noexcept
WorkspaceArrayOfStokesVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfStokesVector () noexcept
WorkspaceArrayOfStokesVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfStokesVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfStokesVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 782 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfStokesVector::type = Group::ArrayOfStokesVector private
Definition at line 783 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfStokesVector() [1/3]
ARTS::Var::WorkspaceArrayOfStokesVector::WorkspaceArrayOfStokesVector () inline noexcept
Definition at line 787 of file autoarts.h.
WorkspaceArrayOfStokesVector() [2/3]
ARTS::Var::WorkspaceArrayOfStokesVector::WorkspaceArrayOfStokesVector (std::size_t i, void * x) inline noexcept
Definition at line 788 of file autoarts.h.
~WorkspaceArrayOfStokesVector()
ARTS::Var::WorkspaceArrayOfStokesVector::~WorkspaceArrayOfStokesVector () inline noexcept
Definition at line 789 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfStokesVector() [3/3]
ARTS::Var::WorkspaceArrayOfStokesVector::WorkspaceArrayOfStokesVector (const type & val) inline noexcept
Definition at line 790 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfStokesVector::islast () const inline noexcept
Definition at line 796 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfStokesVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfStokesVector::isnull () const inline noexcept
Definition at line 795 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfStokesVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfStokesVector::name () const inline noexcept
Definition at line 797 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfStokesVector& ARTS::Var::WorkspaceArrayOfStokesVector::operator= (const type & t) inline noexcept
Definition at line 793 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfStokesVector::pos () const inline noexcept
Definition at line 794 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfStokesVector::value () const inline noexcept
Definition at line 792 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfStokesVector::value () inline noexcept
Definition at line 791 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfStokesVector::p private
Definition at line 784 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfStokesVector::v private
Definition at line 785 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfStokesVector().
The documentation for this class was generated from the following file:
autoarts.h