ARTS: LineShape::Model Class Reference
LineShape::Model Class Reference
Main line shape model class.
#include <lineshapemodel.h>
Public Member Functions
Model (Index n=0) noexcept
Default init just sets the size.
Model (const std::vector< SingleSpeciesModel > &assm) noexcept
Init from copying a vector.
Model (const Model &m) noexcept
Init from copying itself.
Model (std::vector< SingleSpeciesModel > &&assm) noexcept
Init from moving a vector.
Model (Model &&m) noexcept
Init from moving a itself.
Model & operator= (const Model &m)
Copy and equals.
Model & operator= (Model &&m)
Move and equals.
Model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf, std::array< Numeric, 12 > aer_interp={0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}) noexcept
Standard HITRAN init.
bool OK (Type type, bool self, bool bath, const std::vector< SpeciesTag > &species) const noexcept
The Model is good to use.
Output GetParams (Numeric T, Numeric T0, Numeric P, ConstVectorView vmrs) const noexcept
Compute all shape parameters.
Output GetParams (Numeric T, Numeric T0, Numeric P, size_t k) const noexcept
Compute all shape parameters.
Output GetTemperatureDerivs (Numeric T, Numeric T0, Numeric P, ConstVectorView vmrs) const noexcept
Derivative of GetParams(...) wrt T.
Output GetVMRDerivs (Numeric T, Numeric T0, Numeric P, const Index pos) const noexcept
Derivative of GetParams(...) wrt VMR.
Numeric GetInternalDeriv (Numeric T, Numeric T0, Numeric P, Index pos, const Vector &vmrs, Jacobian::Line deriv) const noexcept
Derivative of GetParams(...) wrt Coefficient.
Index nelem () const
Number of species in Model.
Index size () const
Number of species in Model.
void resize (Index n)
Resize function for Model.
void reserve (Index n)
Reserve function for Model.
SingleSpeciesModel & operator[] (Index i)
Get a SingleSpeciesModel.
const SingleSpeciesModel & operator[] (Index i) const
Get a SingleSpeciesModel.
const std::vector< SingleSpeciesModel > & Data () const noexcept
The line shape model data.
std::vector< SingleSpeciesModel > & Data () noexcept
The line shape model data reference.
void Remove (Index i, ArrayOfSpeciesTag &specs)
Remove species and data at position.
void SetLineMixingModel (SingleSpeciesModel x)
Sets the same line mixing model to all species.
bool Match (const Model &other) const noexcept
bifstream & read (bifstream &bif)
Binary read for Model.
bofstream & write (bofstream &bof) const
Binary write for Model.
Private Attributes
std::vector< SingleSpeciesModel > mdata
Friends
std::istream & from_linefunctiondata (std::istream &data, Type &type, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species)
std::istream & from_artscat4 (std::istream &is, Type &type, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species, const QuantumIdentifier &qid)
Detailed Description
Main line shape model class.
Computes the line shape parameters for a given atmosphere
Definition at line 568 of file lineshapemodel.h.
Constructor & Destructor Documentation
Model() [1/6]
LineShape::Model::Model (Index n = 0) inline noexcept
Default init just sets the size.
Definition at line 574 of file lineshapemodel.h.
Model() [2/6]
LineShape::Model::Model (const std::vector< SingleSpeciesModel > & assm) inline explicit noexcept
Init from copying a vector.
Definition at line 577 of file lineshapemodel.h.
Model() [3/6]
LineShape::Model::Model (const Model & m) inline noexcept
Init from copying itself.
Definition at line 580 of file lineshapemodel.h.
Model() [4/6]
LineShape::Model::Model (std::vector< SingleSpeciesModel > && assm) inline explicit noexcept
Init from moving a vector.
Definition at line 583 of file lineshapemodel.h.
Model() [5/6]
LineShape::Model::Model (Model && m) inline noexcept
Init from moving a itself.
Definition at line 586 of file lineshapemodel.h.
Model() [6/6]
LineShape::Model::Model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf, std::array< Numeric, 12 > aer_interp = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}) noexcept
Standard HITRAN init.
Parameters
[in] sgam Self pressure broadening coefficient
[in] nself Self pressure broadening exponent
[in] agam Air pressure broadening coefficient
[in] nair Air pressure broadening exponent
[in] psf All pressure shifting coefficient
[in] interp The interpolation variable for AER type line mixing
Definition at line 1029 of file lineshapemodel.cc.
References x.
Member Function Documentation
Data() [1/2]
const std::vector<SingleSpeciesModel>& LineShape::Model::Data () const inline noexcept
The line shape model data.
Definition at line 826 of file lineshapemodel.h.
References mdata.
Referenced by LineShape::ModelShape2MetaData(), LineShape::operator<<(), LineShape::operator>>(), Absorption::SingleLine::SetLineMixing2AER(), and LineShape::LegacyPressureBroadeningData::vector2modelpb().
Data() [2/2]
std::vector<SingleSpeciesModel>& LineShape::Model::Data () inline noexcept
The line shape model data reference.
Definition at line 829 of file lineshapemodel.h.
References mdata.
GetInternalDeriv()
Numeric LineShape::Model::GetInternalDeriv (Numeric T, Numeric T0, Numeric P, Index pos, const Vector & vmrs, Jacobian::Line deriv) const noexcept
Derivative of GetParams(...) wrt Coefficient.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] P The pressure
[in] pos Position of species in mspecies
[in] vmrs The VMR vector as derived by this.vmrs()
[in] deriv The derivative
Returns
Derivative of GetParams(...) wrt Coefficient
Definition at line 1267 of file lineshapemodel.cc.
GetParams() [1/2]
Output LineShape::Model::GetParams (Numeric T, Numeric T0, Numeric P, ConstVectorView vmrs) const noexcept
Compute all shape parameters.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] P The pressure
[in] vmrs The VMR vector as derived by this.vmrs()
Returns
Shape parameters
Definition at line 1210 of file lineshapemodel.cc.
GetParams() [2/2]
Output LineShape::Model::GetParams (Numeric T, Numeric T0, Numeric P, size_t k) const noexcept
Compute all shape parameters.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] P The pressure
[in] k The position of the single species shape parameters
Returns
Shape parameters
Definition at line 1225 of file lineshapemodel.cc.
GetTemperatureDerivs()
Output LineShape::Model::GetTemperatureDerivs (Numeric T, Numeric T0, Numeric P, ConstVectorView vmrs) const noexcept
Derivative of GetParams(...) wrt T.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] P The pressure
[in] vmrs The VMR vector as derived by this.vmrs()
Returns
Derivative of GetParams(...) wrt T
Definition at line 1240 of file lineshapemodel.cc.
GetVMRDerivs()
Output LineShape::Model::GetVMRDerivs (Numeric T, Numeric T0, Numeric P, const Index pos) const noexcept
Derivative of GetParams(...) wrt VMR.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] P The pressure
[in] pos Position of species in mspecies
Returns
Derivative of GetParams(...) wrt VMR
Definition at line 1255 of file lineshapemodel.cc.
Match()
bool LineShape::Model::Match (const Model & other) const noexcept
Definition at line 1313 of file lineshapemodel.cc.
nelem()
Index LineShape::Model::nelem () const inline
Number of species in Model.
Definition at line 789 of file lineshapemodel.h.
References mdata.
Referenced by Absorption::SingleLine::LineShapeElems(), and Absorption::SingleLine::SingleLine().
OK()
bool LineShape::Model::OK (Type type, bool self, bool bath, const std::vector< SpeciesTag > & species) const noexcept
The Model is good to use.
Returns
true/false
Definition at line 1066 of file lineshapemodel.cc.
operator=() [1/2]
Model& LineShape::Model::operator= (const Model & m) inline
Copy and equals.
Definition at line 589 of file lineshapemodel.h.
References mdata.
operator=() [2/2]
Model& LineShape::Model::operator= (Model && m) inline
Move and equals.
Definition at line 592 of file lineshapemodel.h.
References mdata.
operator[]() [1/2]
SingleSpeciesModel& LineShape::Model::operator[] (Index i) inline
Get a SingleSpeciesModel.
Parameters
[in] i Position in mdata
Returns
reference to SingleSpeciesModel
Definition at line 815 of file lineshapemodel.h.
References mdata.
operator[]() [2/2]
const SingleSpeciesModel& LineShape::Model::operator[] (Index i) const inline
Get a SingleSpeciesModel.
Parameters
[in] i Position in mdata
Returns
reference to SingleSpeciesModel
Definition at line 822 of file lineshapemodel.h.
References mdata.
read()
bifstream & LineShape::Model::read (bifstream & bif)
Binary read for Model.
Definition at line 1317 of file lineshapemodel.cc.
References data, and mdata.
Referenced by Absorption::SingleLine::read().
Remove()
void LineShape::Model::Remove (Index i, ArrayOfSpeciesTag & specs)
Remove species and data at position.
Uses standard algorithm "erase" to remove, see it for behavior when an error occurs
Parameters
[in] i Index of position to remove
Definition at line 1300 of file lineshapemodel.cc.
References mdata.
reserve()
void LineShape::Model::reserve (Index n) inline
Reserve function for Model.
Just reserves, does nothing with the new data
Parameters
[in] n New reserves of mspecies and mdata
Definition at line 808 of file lineshapemodel.h.
References mdata.
resize()
void LineShape::Model::resize (Index n) inline
Resize function for Model.
Just resizes, does nothing with the new data
Parameters
[in] n New size of mspecies and mdata
Definition at line 800 of file lineshapemodel.h.
References mdata.
SetLineMixingModel()
void LineShape::Model::SetLineMixingModel (SingleSpeciesModel x)
Sets the same line mixing model to all species.
Looks at x and sets it Y, G and DV values to all the Y, G, and DV values in this
If LM_AER is used, Interp data is written over as well otherwise it remains untouched
Parameters
[in] x Model containing new line mixing data
Definition at line 1305 of file lineshapemodel.cc.
References mdata, and x.
Referenced by Absorption::SingleLine::SetLineMixing2SecondOrderData().
size()
Index LineShape::Model::size () const inline
Number of species in Model.
Definition at line 792 of file lineshapemodel.h.
References mdata.
write()
bofstream & LineShape::Model::write (bofstream & bof) const
Binary write for Model.
Definition at line 1323 of file lineshapemodel.cc.
References data, and mdata.
Referenced by Absorption::SingleLine::write().
Friends And Related Function Documentation
from_artscat4
std::istream& from_artscat4 (std::istream & is, Type & type, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species, const QuantumIdentifier & qid) friend
from_linefunctiondata
std::istream& from_linefunctiondata (std::istream & data, Type & type, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species) friend
Member Data Documentation
mdata
std::vector<SingleSpeciesModel> LineShape::Model::mdata private
Definition at line 570 of file lineshapemodel.h.
Referenced by Data(), LineShape::from_artscat4(), LineShape::from_linefunctiondata(), nelem(), operator=(), operator[](), read(), Remove(), reserve(), resize(), SetLineMixingModel(), size(), and write().
The documentation for this class was generated from the following files:
lineshapemodel.h
lineshapemodel.cc