ARTS: ARTS::Var::ArrayOfSparse Class Reference
ARTS::Var::ArrayOfSparse Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfSparse () noexcept
ArrayOfSparse (std::size_t i, void *x) noexcept
ArrayOfSparse (const Group::ArrayOfSparse &val) noexcept
~ArrayOfSparse () noexcept
Group::ArrayOfSparse & value () noexcept
const Group::ArrayOfSparse & value () const noexcept
ArrayOfSparse & operator= (const Group::ArrayOfSparse &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfSparse * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfSparse &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2061 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfSparse() [1/3]
ARTS::Var::ArrayOfSparse::ArrayOfSparse () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2066 of file autoarts.h.
ArrayOfSparse() [2/3]
ARTS::Var::ArrayOfSparse::ArrayOfSparse (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2069 of file autoarts.h.
ArrayOfSparse() [3/3]
ARTS::Var::ArrayOfSparse::ArrayOfSparse (const Group::ArrayOfSparse & val) inline noexcept
Construct from Group::ArrayOfSparse. Leaves islast() true and isnull() false
Definition at line 2072 of file autoarts.h.
~ArrayOfSparse()
ARTS::Var::ArrayOfSparse::~ArrayOfSparse () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2075 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfSparse::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2093 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfSparse().
isnull()
bool ARTS::Var::ArrayOfSparse::isnull () const inline noexcept
Return true if there is no data
Definition at line 2090 of file autoarts.h.
References v.
Referenced by ~ArrayOfSparse().
name()
const Group::String& ARTS::Var::ArrayOfSparse::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2096 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfSparse& ARTS::Var::ArrayOfSparse::operator= (const Group::ArrayOfSparse & t) inline noexcept
Set value from Group::ArrayOfSparse. Works when isnull() is false
Definition at line 2084 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfSparse::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2087 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfSparse& ARTS::Var::ArrayOfSparse::value () const inline noexcept
Get value const-ref as Group::ArrayOfSparse. Works when isnull() is false
Definition at line 2081 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfSparse& ARTS::Var::ArrayOfSparse::value () inline noexcept
Get value ref as Group::ArrayOfSparse. Works when isnull() is false
Definition at line 2078 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfSparse & var) friend
Output to stream of internal variable
Definition at line 2099 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfSparse::p private
Definition at line 2062 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfSparse* ARTS::Var::ArrayOfSparse::v private
Definition at line 2063 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfSparse().
The documentation for this class was generated from the following file:
autoarts.h