ARTS: ConstComplexMatrixView Class Reference
ConstComplexMatrixView Class Reference
A constant view of a ComplexMatrix.
#include <complex.h>
Public Types
typedef ConstComplexIterator2D const_iterator
Public Member Functions
constexpr ConstComplexMatrixView (const ConstComplexMatrixView &)=default
constexpr ConstComplexMatrixView (ConstComplexMatrixView &&)=default
ConstComplexMatrixView & operator= (const ConstComplexMatrixView &)=default
ConstComplexMatrixView & operator= (ConstComplexMatrixView &&)=default
bool empty () const
Index nrows () const
Index ncols () const
Complex operator() (Index r, Index c) const
Plain const index operator.
Complex get (Index r, Index c) const
Get element implementation without assertions.
Numeric get_real (Index r, Index c) const
Get element implementation without assertions.
Numeric get_imag (Index r, Index c) const
Get element implementation without assertions.
ConstMatrixView real () const
Get a view of the real part of the matrix.
ConstMatrixView imag () const
Get a view of the imaginary part of the matrix.
Index get_column_extent () const
Get the extent of the underlying data.
ConstComplexMatrixView operator() (const Range &r, const Range &c) const
Returns true if variable size is zero.
ConstComplexVectorView operator() (const Range &r, Index c) const
Const index operator returning a column as an object of type C onstComplex*VectorView.
ConstComplexVectorView operator() (Index r, const Range &c) const
Const index operator returning a row as an object of type C onstComplex*VectorView.
ConstComplexIterator2D begin () const
Return const iterator to first row.
ConstComplexIterator2D end () const
Return const iterator behind last row.
ConstComplexVectorView diagonal () const
ComplexMatrix diagonal as vector.
virtual ~ConstComplexMatrixView ()=default
Destructor.
Protected Member Functions
ConstComplexMatrixView ()=default
ConstComplexMatrixView (Complex *data, const Range &r, const Range &c)
Explicit constructor.
ConstComplexMatrixView (Complex *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Complex * mdata {nullptr}
Pointer to the plain C array that holds the data.
Friends
class ComplexMatrixView
class ConstComplexVectorView
ConstComplexMatrixView transpose (ConstComplexMatrixView m)
Const version of transpose.
void mult (ComplexVectorView, const ConstComplexMatrixView &, const ConstComplexVectorView &)
Matrix-Vector Multiplication.
void mult (ComplexMatrixView, const ConstComplexMatrixView &, const ConstComplexMatrixView &)
Matrix-Matrix Multiplication.
void mult (ComplexMatrixView, const ConstMatrixView &, const ConstComplexMatrixView &)
void mult (ComplexMatrixView, const ConstComplexMatrixView &, const ConstMatrixView &)
ComplexConstMatrixViewMap MapToEigen (const ConstComplexMatrixView &)
ComplexMatrixViewMap MapToEigen (ComplexMatrixView &)
Detailed Description
A constant view of a ComplexMatrix.
This, together with the derived class Complex*MatrixView, contains the * main implementation of a ComplexMatrix. It defines the concepts of ComplexMatrixView. Plus additionally the recursive subrange operator, which makes it possible to create a ComplexMatrixView from a subrange of a ComplexMatrixView.
The class ComplexMatrix is just a special case of a ComplexMatrixView which also allocates storage.
Definition at line 618 of file complex.h.
Member Typedef Documentation
const_iterator
typedef ConstComplexIterator2D ConstComplexMatrixView::const_iterator
Definition at line 626 of file complex.h.
Constructor & Destructor Documentation
ConstComplexMatrixView() [1/5]
constexpr ConstComplexMatrixView::ConstComplexMatrixView (const ConstComplexMatrixView &) constexpr default
ConstComplexMatrixView() [2/5]
constexpr ConstComplexMatrixView::ConstComplexMatrixView (ConstComplexMatrixView &&) constexpr default
~ConstComplexMatrixView()
virtual ConstComplexMatrixView::~ConstComplexMatrixView () virtual default
Destructor.
ConstComplexMatrixView() [3/5]
ConstComplexMatrixView::ConstComplexMatrixView () protected default
Referenced by operator()().
ConstComplexMatrixView() [4/5]
ConstComplexMatrixView::ConstComplexMatrixView (Complex * data, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Matrix to initialize its own MatrixView part. The row range rr must have a stride to account for the length of one row.
Definition at line 826 of file complex.cc.
ConstComplexMatrixView() [5/5]
ConstComplexMatrixView::ConstComplexMatrixView (Complex * data, const Range & pr, const Range & pc, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pr Previous range.
pc Previous range.
nr New Range.
nc New Range.
Definition at line 847 of file complex.cc.
Member Function Documentation
begin()
ConstComplexIterator2D ConstComplexMatrixView::begin () const
Return const iterator to first row.
Definition at line 795 of file complex.cc.
References ConstComplexVectorView, mcr, mdata, mrr, Range::mstart, and Range::mstride.
Referenced by ComplexMatrix::ComplexMatrix(), ComplexMatrixView::operator=(), and ComplexMatrix::operator=().
diagonal()
ConstComplexVectorView ConstComplexMatrixView::diagonal () const
ComplexMatrix diagonal as vector.
R eturns a ConstComplex*MatrixView on the diagonal entries of the matrix. For a given (n,m) matrix M the diagonal vector v is the vector of length min{n,m} with entries
 v[i] = M(i,i)
Returns
The diagonal vector v.
Definition at line 817 of file complex.cc.
References ConstComplexVectorView, mcr, mdata, Range::mextent, min, mrr, Range::mstart, and Range::mstride.
empty()
bool ConstComplexMatrixView::empty () const inline
Definition at line 629 of file complex.h.
end()
ConstComplexIterator2D ConstComplexMatrixView::end () const
Return const iterator behind last row.
Definition at line 801 of file complex.cc.
References ConstComplexVectorView, mcr, mdata, Range::mextent, mrr, Range::mstart, and Range::mstride.
Referenced by ComplexMatrix::ComplexMatrix(), ComplexMatrixView::operator=(), and ComplexMatrix::operator=().
get()
Complex ConstComplexMatrixView::get (Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 645 of file complex.h.
References c, and ConstComplexVectorView::mdata.
get_column_extent()
Index ConstComplexMatrixView::get_column_extent () const inline
Get the extent of the underlying data.
Definition at line 665 of file complex.h.
Referenced by diagonalize().
get_imag()
Numeric ConstComplexMatrixView::get_imag (Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 654 of file complex.h.
References c, and ComplexVectorView::get().
get_real()
Numeric ConstComplexMatrixView::get_real (Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 651 of file complex.h.
References c, and ComplexVectorView::get().
imag()
ConstMatrixView ConstComplexMatrixView::imag () const inline
Get a view of the imaginary part of the matrix.
Definition at line 661 of file complex.h.
References ConstComplexVectorView::mdata.
ncols()
Index ConstComplexMatrixView::ncols () const inline
Definition at line 631 of file complex.h.
Referenced by diagonalize(), get_maximum_error(), inv(), ComplexMatrix::inv(), mult(), ComplexMatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexMatrixView::operator/=(), and random_fill_matrix().
nrows()
Index ConstComplexMatrixView::nrows () const inline
Definition at line 630 of file complex.h.
Referenced by diagonalize(), get_maximum_error(), inv(), ComplexMatrix::inv(), mult(), ComplexMatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexMatrixView::operator/=(), and random_fill_matrix().
operator()() [1/4]
ConstComplexMatrixView ConstComplexMatrixView::operator() (const Range & r, const Range & c) const
Returns true if variable size is zero.
Returns the number of rows. Returns the number of columns. Const index operator for subrange. We have to also account for the case, that *this is already a subrange of a Matrix. This allows correct recursive behavior.
Definition at line 761 of file complex.cc.
References c, ConstComplexMatrixView(), mcr, mdata, and mrr.
operator()() [2/4]
ConstComplexVectorView ConstComplexMatrixView::operator() (const Range & r, Index c) const
Const index operator returning a column as an object of type C onstComplex*VectorView.
Parameters
r A range of rows.
c Index of selected column
Definition at line 771 of file complex.cc.
References ARTS_ASSERT, c, ConstComplexVectorView, mcr, mdata, Range::mextent, mrr, Range::mstart, and Range::mstride.
operator()() [3/4]
ConstComplexVectorView ConstComplexMatrixView::operator() (Index r, const Range & c) const
Const index operator returning a row as an object of type C onstComplex*VectorView.
Parameters
r Index of selected row.
c Range of columns
Definition at line 785 of file complex.cc.
References ARTS_ASSERT, c, ConstComplexVectorView, mcr, mdata, Range::mextent, mrr, Range::mstart, and Range::mstride.
operator()() [4/4]
Complex ConstComplexMatrixView::operator() (Index r, Index c) const inline
Plain const index operator.
Definition at line 635 of file complex.h.
References ARTS_ASSERT, c, and ComplexVectorView::get().
operator=() [1/2]
ConstComplexMatrixView& ConstComplexMatrixView::operator= (const ConstComplexMatrixView &) default
operator=() [2/2]
ConstComplexMatrixView& ConstComplexMatrixView::operator= (ConstComplexMatrixView &&) default
real()
ConstMatrixView ConstComplexMatrixView::real () const inline
Get a view of the real part of the matrix.
Definition at line 657 of file complex.h.
References ConstComplexVectorView::mdata.
Friends And Related Function Documentation
ComplexMatrixView
friend class ComplexMatrixView friend
Definition at line 682 of file complex.h.
ConstComplexVectorView
friend class ConstComplexVectorView friend
Definition at line 683 of file complex.h.
Referenced by begin(), diagonal(), end(), and operator()().
MapToEigen [1/2]
ComplexMatrixViewMap MapToEigen (ComplexMatrixView &) friend
Definition at line 1677 of file complex.cc.
MapToEigen [2/2]
ComplexConstMatrixViewMap MapToEigen (const ConstComplexMatrixView &) friend
Definition at line 1647 of file complex.cc.
mult [1/4]
void mult (ComplexMatrixView , const ConstComplexMatrixView & , const ConstComplexMatrixView &) friend
Matrix-Matrix Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand. Note that to keep speed, the inputs should be different variables. There is memory duplication if this is not the case. Note that it is mdata that is checked, so even if the matrices are at different parts of a tensor, there is still a slowdown
Parameters
[in,out] A The matrix A, that will hold the result of the multiplication.
[in] B The matrix B
[in] C The matrix C
Definition at line 1596 of file complex.cc.
mult [2/4]
void mult (ComplexMatrixView , const ConstComplexMatrixView & , const ConstMatrixView &) friend
Definition at line 1609 of file complex.cc.
mult [3/4]
void mult (ComplexMatrixView , const ConstMatrixView & , const ConstComplexMatrixView &) friend
Definition at line 1622 of file complex.cc.
mult [4/4]
void mult (ComplexVectorView , const ConstComplexMatrixView & , const ConstComplexVectorView &) friend
Matrix-Vector Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand.
For left-hand multiplication, please use pure matrix-mult.
Parameters
[out] y The length-m ComplexVectorView where the result is stored.
[in] M Reference to the m-times-n Const{Complex,}MatrixView holding the matrix M.
[in] x Reference to the length-n Const{Complex,}VectorView holding the vector x.
Definition at line 1571 of file complex.cc.
transpose
ConstComplexMatrixView transpose (ConstComplexMatrixView m) friend
Const version of transpose.
Definition at line 1501 of file complex.cc.
Member Data Documentation
mcr
Range ConstComplexMatrixView::mcr {0, 0, 1} protected
The column range of mdata that is actually used.
Definition at line 717 of file complex.h.
Referenced by ComplexMatrixView::begin(), begin(), ComplexMatrixView::diagonal(), diagonal(), ComplexMatrixView::end(), end(), ComplexMatrixView::get_c_array(), ComplexMatrixView::operator()(), operator()(), ComplexMatrixView::operator=(), and ComplexMatrix::resize().
mdata
Complex* ConstComplexMatrixView::mdata {nullptr} protected
Pointer to the plain C array that holds the data.
Definition at line 719 of file complex.h.
Referenced by ComplexMatrixView::begin(), begin(), ComplexMatrix::ComplexMatrix(), ComplexMatrixView::diagonal(), diagonal(), ComplexMatrixView::end(), end(), ComplexMatrixView::get_c_array(), ComplexMatrix::inv(), ComplexMatrixView::operator()(), operator()(), ComplexMatrix::resize(), and ComplexMatrix::~ComplexMatrix().
mrr
Range ConstComplexMatrixView::mrr {0, 0, 1} protected
The row range of mdata that is actually used.
Definition at line 715 of file complex.h.
Referenced by ComplexMatrixView::begin(), begin(), ComplexMatrixView::diagonal(), diagonal(), ComplexMatrixView::end(), end(), ComplexMatrixView::get_c_array(), ComplexMatrixView::operator()(), operator()(), ComplexMatrixView::operator=(), and ComplexMatrix::resize().
The documentation for this class was generated from the following files:
complex.h
complex.cc