ARTS: ARTS::Var::QuantumIdentifier Class Reference
ARTS::Var::QuantumIdentifier Class Reference
#include <autoarts.h>
Public Member Functions
QuantumIdentifier () noexcept
QuantumIdentifier (std::size_t i, void *x) noexcept
QuantumIdentifier (const Group::QuantumIdentifier &val) noexcept
~QuantumIdentifier () noexcept
Group::QuantumIdentifier & value () noexcept
const Group::QuantumIdentifier & value () const noexcept
QuantumIdentifier & operator= (const Group::QuantumIdentifier &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::QuantumIdentifier * v
Friends
std::ostream & operator<< (std::ostream &os, const QuantumIdentifier &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3563 of file autoarts.h.
Constructor & Destructor Documentation
QuantumIdentifier() [1/3]
ARTS::Var::QuantumIdentifier::QuantumIdentifier () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3568 of file autoarts.h.
QuantumIdentifier() [2/3]
ARTS::Var::QuantumIdentifier::QuantumIdentifier (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3571 of file autoarts.h.
QuantumIdentifier() [3/3]
ARTS::Var::QuantumIdentifier::QuantumIdentifier (const Group::QuantumIdentifier & val) inline noexcept
Construct from Group::QuantumIdentifier. Leaves islast() true and isnull() false
Definition at line 3574 of file autoarts.h.
~QuantumIdentifier()
ARTS::Var::QuantumIdentifier::~QuantumIdentifier () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3577 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::QuantumIdentifier::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3595 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Agenda::Method::abs_linesKeepBand(), ARTS::Agenda::Method::abs_linesRemoveBand(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetCutoffForMatch(), ARTS::Agenda::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Agenda::Method::abs_linesSetMirroringForMatch(), ARTS::Agenda::Method::abs_linesSetNormalizationForMatch(), ARTS::Agenda::Method::abs_linesSetPopulationForMatch(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesSetT0ForMatch(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameter(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::QuantumIdentifierSet(), ARTS::Agenda::Method::QuantumIdentifierSet(), ARTS::Agenda::Method::retrievalAddCatalogParameter(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~QuantumIdentifier().
isnull()
bool ARTS::Var::QuantumIdentifier::isnull () const inline noexcept
Return true if there is no data
Definition at line 3592 of file autoarts.h.
References v.
Referenced by ~QuantumIdentifier().
name()
const Group::String& ARTS::Var::QuantumIdentifier::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3598 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
QuantumIdentifier& ARTS::Var::QuantumIdentifier::operator= (const Group::QuantumIdentifier & t) inline noexcept
Set value from Group::QuantumIdentifier. Works when isnull() is false
Definition at line 3586 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::QuantumIdentifier::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3589 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Agenda::Method::abs_linesKeepBand(), ARTS::Agenda::Method::abs_linesRemoveBand(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetCutoffForMatch(), ARTS::Agenda::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Agenda::Method::abs_linesSetMirroringForMatch(), ARTS::Agenda::Method::abs_linesSetNormalizationForMatch(), ARTS::Agenda::Method::abs_linesSetPopulationForMatch(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesSetT0ForMatch(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameter(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameter(), ARTS::Agenda::Method::QuantumIdentifierSet(), ARTS::Agenda::Method::retrievalAddCatalogParameter(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::QuantumIdentifier& ARTS::Var::QuantumIdentifier::value () const inline noexcept
Get value const-ref as Group::QuantumIdentifier. Works when isnull() is false
Definition at line 3583 of file autoarts.h.
References v.
value() [2/2]
Group::QuantumIdentifier& ARTS::Var::QuantumIdentifier::value () inline noexcept
Get value ref as Group::QuantumIdentifier. Works when isnull() is false
Definition at line 3580 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_linesKeepBand(), ARTS::Method::abs_linesRemoveBand(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameter(), operator=(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::retrievalAddCatalogParameter(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const QuantumIdentifier & var) friend
Output to stream of internal variable
Definition at line 3601 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::QuantumIdentifier::p private
Definition at line 3564 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::QuantumIdentifier* ARTS::Var::QuantumIdentifier::v private
Definition at line 3565 of file autoarts.h.
Referenced by isnull(), value(), and ~QuantumIdentifier().
The documentation for this class was generated from the following file:
autoarts.h