ARTS: Matrix Class Reference
Matrix Class Reference
The Matrix class.
#include <matpackI.h>
Public Member Functions
Matrix ()=default
Matrix (Index r, Index c)
Constructor setting size.
Matrix (Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Matrix (const ConstMatrixView &m)
Copy constructor from MatrixView.
Matrix (const Matrix &m)
Copy constructor from Matrix.
Matrix (Matrix &&v) noexcept
Matrix (Numeric *d, const Range &r0, const Range &r1) ARTS_NOEXCEPT
Matrix & operator= (const Matrix &m)
Assignment operator from another matrix.
Matrix & operator= (Matrix &&m) noexcept
Move assignment operator from another matrix.
Matrix & operator= (Numeric x)
Assignment operator from scalar.
Matrix & operator= (const ConstVectorView &v)
Assignment from a vector.
void resize (Index r, Index c)
Resize function.
virtual ~Matrix ()
Destructor for Matrix.
Index size () const noexcept
template<std::size_t dim0>
Vector reduce_rank () &&ARTS_NOEXCEPT
Numeric * get_raw_data () ARTS_NOEXCEPT
Public Member Functions inherited from MatrixView
constexpr MatrixView (const MatrixView &)=default
Numeric & operator() (Index r, Index c) ARTS_NOEXCEPT
Plain index operator.
Numeric & get (Index r, Index c) ARTS_NOEXCEPT
Get element implementation without assertions.
MatrixView operator() (const Range &r, const Range &c) ARTS_NOEXCEPT
Index operator for subrange.
VectorView operator() (const Range &r, Index c) ARTS_NOEXCEPT
Index operator returning a column as an object of type VectorView.
VectorView operator() (Index r, const Range &c) ARTS_NOEXCEPT
Index operator returning a row as an object of type VectorView.
Iterator2D begin () ARTS_NOEXCEPT
‍** Return const iterator to first row. Has to be redefined here, since it is
Iterator2D end () ARTS_NOEXCEPT
Return iterator behind last row.
MatrixView & operator= (const ConstMatrixView &m)
Assignment operator.
MatrixView & operator= (const MatrixView &m)
Assignment from MatrixView to MatrixView.
MatrixView & operator= (const Matrix &m)
Assignment from a Matrix.
MatrixView & operator= (const ConstVectorView &m)
Assignment from a vector.
MatrixView & operator= (Numeric x)
Assigning a scalar to a MatrixView will set all elements to this value.
MatrixView & operator*= (Numeric x) ARTS_NOEXCEPT
Multiplication by scalar.
MatrixView & operator/= (Numeric x) ARTS_NOEXCEPT
Division by scalar.
MatrixView & operator+= (Numeric x) ARTS_NOEXCEPT
Addition of scalar.
MatrixView & operator-= (Numeric x) ARTS_NOEXCEPT
Subtraction of scalar.
MatrixView & operator*= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise multiplication by another Matrix.
MatrixView & operator/= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise division by another Matrix.
MatrixView & operator+= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise addition of another Matrix.
MatrixView & operator-= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise subtraction of another Matrix.
MatrixView & operator*= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise multiplication by a Vector (acting like a 1-column Matrix).
MatrixView & operator/= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise division by a Vector (acting like a 1-column Matrix).
MatrixView & operator+= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise addition of a Vector (acting like a 1-column Matrix).
MatrixView & operator-= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise subtraction of a Vector (acting like a 1-column Matrix).
const Numeric * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array.
Numeric * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array.
virtual ~MatrixView ()=default
Destructor.
ConstIterator2D begin () const ARTS_NOEXCEPT
Return const iterator to first row.
ConstIterator2D end () const ARTS_NOEXCEPT
Return const iterator behind last row.
Numeric get (Index r, Index c) const ARTS_NOEXCEPT
Get element implementation without assertions.
Public Member Functions inherited from ConstMatrixView
constexpr ConstMatrixView (const ConstMatrixView &)=default
constexpr ConstMatrixView (ConstMatrixView &&)=default
ConstMatrixView & operator= (const ConstMatrixView &)=default
ConstMatrixView & operator= (ConstMatrixView &&)=default
bool empty () const ARTS_NOEXCEPT
Returns true if variable size is zero.
Index nrows () const ARTS_NOEXCEPT
Returns the number of rows.
Index ncols () const ARTS_NOEXCEPT
Returns the number of columns.
Numeric operator() (Index r, Index c) const ARTS_NOEXCEPT
Plain const index operator.
Numeric get (Index r, Index c) const ARTS_NOEXCEPT
Get element implementation without assertions.
ConstMatrixView operator() (const Range &r, const Range &c) const ARTS_NOEXCEPT
Const index operator for subrange.
ConstVectorView operator() (const Range &r, Index c) const ARTS_NOEXCEPT
Const index operator returning a column as an object of type ConstVectorView.
ConstVectorView operator() (Index r, const Range &c) const ARTS_NOEXCEPT
Const index operator returning a row as an object of type ConstVectorView.
ConstIterator2D begin () const ARTS_NOEXCEPT
Return const iterator to first row.
ConstIterator2D end () const ARTS_NOEXCEPT
Return const iterator behind last row.
ConstVectorView diagonal () const ARTS_NOEXCEPT
Matrix diagonal as vector.
virtual ~ConstMatrixView ()=default
Destructor.
Friends
void swap (Matrix &m1, Matrix &m2)
Swaps two objects.
Additional Inherited Members
Public Types inherited from MatrixView
typedef Iterator2D iterator
Public Types inherited from ConstMatrixView
typedef ConstIterator2D const_iterator
Protected Member Functions inherited from MatrixView
MatrixView ()=default
MatrixView (Numeric *data, const Range &rr, const Range &cr) ARTS_NOEXCEPT
Explicit constructor.
MatrixView (Numeric *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc) ARTS_NOEXCEPT
Recursive constructor.
Protected Member Functions inherited from ConstMatrixView
ConstMatrixView ()=default
ConstMatrixView (Numeric *data, const Range &r, const Range &c) ARTS_NOEXCEPT
Explicit constructor.
ConstMatrixView (Numeric *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc) ARTS_NOEXCEPT
Recursive constructor.
Protected Attributes inherited from ConstMatrixView
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Matrix class.
This is a MatrixView that also allocates storage automatically, and deallocates it when it is destroyed. We take all the functionality from MatrixView. Additionally defined here are:
Constructors and destructor.
Assignment operator from scalar.
Resize function.
Definition at line 1217 of file matpackI.h.
Constructor & Destructor Documentation
Matrix() [1/7]
Matrix::Matrix () default
Matrix() [2/7]
Matrix::Matrix (Index r, Index c)
Constructor setting size.
This constructor has to set the stride in the row range correctly!
Definition at line 947 of file matpackI.cc.
Matrix() [3/7]
Matrix::Matrix (Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Definition at line 953 of file matpackI.cc.
References c, and ConstMatrixView::mdata.
Matrix() [4/7]
Matrix::Matrix (const ConstMatrixView & m)
Copy constructor from MatrixView.
This automatically sets the size and copies the data.
Definition at line 962 of file matpackI.cc.
References MatrixView::begin(), ConstMatrixView::begin(), copy(), and ConstMatrixView::end().
Matrix() [5/7]
Matrix::Matrix (const Matrix & m)
Copy constructor from Matrix.
This automatically sets the size and copies the data.
Definition at line 971 of file matpackI.cc.
References ConstMatrixView::mdata, ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Matrix() [6/7]
Matrix::Matrix (Matrix && v) inline noexcept
Definition at line 1225 of file matpackI.h.
References v.
Matrix() [7/7]
Matrix::Matrix (Numeric * d, const Range & r0, const Range & r1) inline
Construct from known data
Note that this will call delete on the pointer if it is still valid at the end of the lifetime of this variable
Parameters
[in] d - A pointer to some raw data
[in] r0 - The Range along the first dimension
[in] r1 - The Range along the second dimension
Definition at line 1238 of file matpackI.h.
References ARTS_ASSERT.
~Matrix()
Matrix::~Matrix () virtual
Destructor for Matrix.
This is important, since Matrix uses new to allocate storage.
Definition at line 1086 of file matpackI.cc.
References ConstMatrixView::mdata.
Member Function Documentation
get_raw_data()
Numeric* Matrix::get_raw_data () inline
Definition at line 1276 of file matpackI.h.
References ConstVectorView::mdata.
operator=() [1/4]
Matrix & Matrix::operator= (const ConstVectorView & v)
Assignment from a vector.
This copies the data from a VectorView to this MatrixView.
The dimension is adjusted automatically.
Parameters
v The vector to assign to this matrix.
Returns
This matrix, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 1049 of file matpackI.cc.
References MatrixView::begin(), ConstMatrixView::begin(), copy(), ConstMatrixView::end(), resize(), and v.
operator=() [2/4]
Matrix & Matrix::operator= (const Matrix & m)
Assignment operator from another matrix.
While dimensions of MatrixViews can not be adjusted, dimensions of matrices can be adjusted. Hence, the behavior of the assignment operator is different.
In this case the size of the target is automatically adjusted. This is important, so that structures containing matrices are copied correctly.
This is a deviation from the old ARTS paradigm that sizes must match exactly before copying!
Note: It is sufficient to have only this one version of the assignment (Matrix = Matrix). It implicitly covers the cases Matrix=MatrixView, etc, because there is a default constructor for Matrix from MatrixView. (See C++ Primer Plus, page 571ff.)
Parameters
m The other matrix to assign to this one.
Returns
This matrix, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 1007 of file matpackI.cc.
References ConstMatrixView::mdata, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and resize().
operator=() [3/4]
Matrix & Matrix::operator= (Matrix && m) noexcept
Move assignment operator from another matrix.
Definition at line 1016 of file matpackI.cc.
References ConstMatrixView::mdata.
operator=() [4/4]
Matrix & Matrix::operator= (Numeric x)
Assignment operator from scalar.
Assignment operators also seem to be not inherited.
Definition at line 1031 of file matpackI.cc.
References ConstMatrixView::mdata, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and ARTS::Var::x().
reduce_rank()
template<std::size_t dim0> Vector Matrix::reduce_rank () && inline
Reduce a Matrix to a Vector and leave this in an empty state
Definition at line 1264 of file matpackI.h.
References ARTS_ASSERT, ConstVectorView::mdata, ARTS::Var::ncols(), ARTS::Var::nrows(), and ConstVectorView::size().
resize()
void Matrix::resize (Index r, Index c)
Resize function.
If the size is already correct this function does nothing. All data is lost after resizing! The new Matrix is not initialized, so it will contain random values.
Definition at line 1059 of file matpackI.cc.
References ARTS_ASSERT, and c.
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesAddConts(), GasAbsLookup::Adapt(), AddZaAa(), ampmat_to_phamat(), Append(), complex_n_ice_matzler06(), complex_n_water_liebe93(), DiagonalMatrix(), DiffZaAa(), FastemStandAlone(), get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_refr_index_2d(), get_refr_index_3d(), insert_elements(), integrate_phamat_alpha10(), integrate_phamat_alpha6(), integrate_phamat_theta0_phi_alpha6(), interp_atmfield_gp2itw(), interp_atmsurface_gp2itw(), iy_transmittance_mult(), iyb_calc(), iyIndependentBeamApproximation(), Matrix1ColFromVector(), Matrix1RowFromVector(), Matrix2ColFromVectors(), Matrix2RowFromVectors(), Matrix3ColFromVectors(), Matrix3RowFromVectors(), MatrixAddScalar(), MatrixCBR(), MatrixCopySparse(), MatrixExtractFromTensor3(), MatrixIdentity(), MatrixPlanck(), MatrixScale(), MatrixUnitIntensity(), nca_get_data_Matrix(), nca_read_from_file(), operator=(), opt_prop_NScatElems(), ArtsParser::parse_matrix(), particle_bulkpropRadarOnionPeeling(), pha_mat_NScatElems(), TelsemAtlas::read(), Reduce(), regrid_atmsurf_by_gp(), regrid_atmsurf_by_gp_oem(), GriddedField2::resize(), rslope_crossing2d(), rslope_crossing3d(), sensor_responseMetMM(), InteractiveWorkspace::set_matrix_variable(), telsemStandalone(), tessem_read_ascii(), test_dense_sparse_multiplication(), test_identity(), test_insert_row(), test_sparse_dense_multiplication(), test_workspace_methods(), xml_read_from_stream(), and za_gridOpt().
size()
Index Matrix::size () const inline noexcept
Definition at line 1260 of file matpackI.h.
References ARTS::Var::ncols(), and ARTS::Var::nrows().
Referenced by Tensor3::reduce_rank(), Tensor4::reduce_rank(), Tensor5::reduce_rank(), Tensor6::reduce_rank(), and Tensor7::reduce_rank().
Friends And Related Function Documentation
swap
void swap (Matrix & m1, Matrix & m2) friend
Swaps two objects.
Definition at line 1078 of file matpackI.cc.
The documentation for this class was generated from the following files:
matpackI.h
matpackI.cc