ARTS: ARTS::Var::ArrayOfRetrievalQuantity Class Reference
ARTS::Var::ArrayOfRetrievalQuantity Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfRetrievalQuantity () noexcept
ArrayOfRetrievalQuantity (std::size_t i, void *x) noexcept
ArrayOfRetrievalQuantity (const Group::ArrayOfRetrievalQuantity &val) noexcept
~ArrayOfRetrievalQuantity () noexcept
Group::ArrayOfRetrievalQuantity & value () noexcept
const Group::ArrayOfRetrievalQuantity & value () const noexcept
ArrayOfRetrievalQuantity & operator= (const Group::ArrayOfRetrievalQuantity &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfRetrievalQuantity * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfRetrievalQuantity &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1920 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfRetrievalQuantity() [1/3]
ARTS::Var::ArrayOfRetrievalQuantity::ArrayOfRetrievalQuantity () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1925 of file autoarts.h.
ArrayOfRetrievalQuantity() [2/3]
ARTS::Var::ArrayOfRetrievalQuantity::ArrayOfRetrievalQuantity (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1928 of file autoarts.h.
ArrayOfRetrievalQuantity() [3/3]
ARTS::Var::ArrayOfRetrievalQuantity::ArrayOfRetrievalQuantity (const Group::ArrayOfRetrievalQuantity & val) inline noexcept
Construct from Group::ArrayOfRetrievalQuantity. Leaves islast() true and isnull() false
Definition at line 1931 of file autoarts.h.
~ArrayOfRetrievalQuantity()
ARTS::Var::ArrayOfRetrievalQuantity::~ArrayOfRetrievalQuantity () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1934 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfRetrievalQuantity::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1952 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfRetrievalQuantity().
isnull()
bool ARTS::Var::ArrayOfRetrievalQuantity::isnull () const inline noexcept
Return true if there is no data
Definition at line 1949 of file autoarts.h.
References v.
Referenced by ~ArrayOfRetrievalQuantity().
name()
const Group::String& ARTS::Var::ArrayOfRetrievalQuantity::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1955 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfRetrievalQuantity& ARTS::Var::ArrayOfRetrievalQuantity::operator= (const Group::ArrayOfRetrievalQuantity & t) inline noexcept
Set value from Group::ArrayOfRetrievalQuantity. Works when isnull() is false
Definition at line 1943 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfRetrievalQuantity::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1946 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfRetrievalQuantity& ARTS::Var::ArrayOfRetrievalQuantity::value () const inline noexcept
Get value const-ref as Group::ArrayOfRetrievalQuantity. Works when isnull() is false
Definition at line 1940 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfRetrievalQuantity& ARTS::Var::ArrayOfRetrievalQuantity::value () inline noexcept
Get value ref as Group::ArrayOfRetrievalQuantity. Works when isnull() is false
Definition at line 1937 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), LineShape::frequency_loop(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfRetrievalQuantity & var) friend
Output to stream of internal variable
Definition at line 1958 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfRetrievalQuantity::p private
Definition at line 1921 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfRetrievalQuantity* ARTS::Var::ArrayOfRetrievalQuantity::v private
Definition at line 1922 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfRetrievalQuantity().
The documentation for this class was generated from the following file:
autoarts.h