ARTS: ARTS::Var::ArrayOfPpath Class Reference
ARTS::Var::ArrayOfPpath Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfPpath () noexcept
ArrayOfPpath (std::size_t i, void *x) noexcept
ArrayOfPpath (const Group::ArrayOfPpath &val) noexcept
~ArrayOfPpath () noexcept
Group::ArrayOfPpath & value () noexcept
const Group::ArrayOfPpath & value () const noexcept
ArrayOfPpath & operator= (const Group::ArrayOfPpath &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfPpath * v
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1734 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfPpath() [1/3]
ARTS::Var::ArrayOfPpath::ArrayOfPpath () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1739 of file autoarts.h.
ArrayOfPpath() [2/3]
ARTS::Var::ArrayOfPpath::ArrayOfPpath (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1742 of file autoarts.h.
ArrayOfPpath() [3/3]
ARTS::Var::ArrayOfPpath::ArrayOfPpath (const Group::ArrayOfPpath & val) inline noexcept
Construct from Group::ArrayOfPpath. Leaves islast() true and isnull() false
Definition at line 1745 of file autoarts.h.
~ArrayOfPpath()
ARTS::Var::ArrayOfPpath::~ArrayOfPpath () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1748 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfPpath::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1766 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfPpath().
isnull()
bool ARTS::Var::ArrayOfPpath::isnull () const inline noexcept
Return true if there is no data
Definition at line 1763 of file autoarts.h.
References v.
Referenced by ~ArrayOfPpath().
name()
const Group::String& ARTS::Var::ArrayOfPpath::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1769 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfPpath& ARTS::Var::ArrayOfPpath::operator= (const Group::ArrayOfPpath & t) inline noexcept
Set value from Group::ArrayOfPpath. Works when isnull() is false
Definition at line 1757 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfPpath::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1760 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfPpath& ARTS::Var::ArrayOfPpath::value () const inline noexcept
Get value const-ref as Group::ArrayOfPpath. Works when isnull() is false
Definition at line 1754 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfPpath& ARTS::Var::ArrayOfPpath::value () inline noexcept
Get value ref as Group::ArrayOfPpath. Works when isnull() is false
Definition at line 1751 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfPpath::p private
Definition at line 1735 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfPpath* ARTS::Var::ArrayOfPpath::v private
Definition at line 1736 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfPpath().
The documentation for this class was generated from the following file:
autoarts.h