ARTS: ARTS::Var::WorkspaceArrayOfArrayOfTensor6 Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfTensor6 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfTensor6 () noexcept
WorkspaceArrayOfArrayOfTensor6 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfTensor6 () noexcept
WorkspaceArrayOfArrayOfTensor6 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfTensor6 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfTensor6
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 440 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfTensor6::type = Group::ArrayOfArrayOfTensor6 private
Definition at line 441 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfTensor6() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor6::WorkspaceArrayOfArrayOfTensor6 () inline noexcept
Definition at line 445 of file autoarts.h.
WorkspaceArrayOfArrayOfTensor6() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor6::WorkspaceArrayOfArrayOfTensor6 (std::size_t i, void * x) inline noexcept
Definition at line 446 of file autoarts.h.
~WorkspaceArrayOfArrayOfTensor6()
ARTS::Var::WorkspaceArrayOfArrayOfTensor6::~WorkspaceArrayOfArrayOfTensor6 () inline noexcept
Definition at line 447 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfTensor6() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor6::WorkspaceArrayOfArrayOfTensor6 (const type & val) inline noexcept
Definition at line 448 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfTensor6::islast () const inline noexcept
Definition at line 454 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfTensor6().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfTensor6::isnull () const inline noexcept
Definition at line 453 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfTensor6().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfTensor6::name () const inline noexcept
Definition at line 455 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfTensor6& ARTS::Var::WorkspaceArrayOfArrayOfTensor6::operator= (const type & t) inline noexcept
Definition at line 451 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTensor6::pos () const inline noexcept
Definition at line 452 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfTensor6::value () const inline noexcept
Definition at line 450 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfTensor6::value () inline noexcept
Definition at line 449 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTensor6::p private
Definition at line 442 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfTensor6::v private
Definition at line 443 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfTensor6().
The documentation for this class was generated from the following file:
autoarts.h