ARTS: ARTS::Var::WorkspaceArrayOfArrayOfTensor3 Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfTensor3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfTensor3 () noexcept
WorkspaceArrayOfArrayOfTensor3 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfTensor3 () noexcept
WorkspaceArrayOfArrayOfTensor3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfTensor3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfTensor3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 422 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfTensor3::type = Group::ArrayOfArrayOfTensor3 private
Definition at line 423 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfTensor3() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor3::WorkspaceArrayOfArrayOfTensor3 () inline noexcept
Definition at line 427 of file autoarts.h.
WorkspaceArrayOfArrayOfTensor3() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor3::WorkspaceArrayOfArrayOfTensor3 (std::size_t i, void * x) inline noexcept
Definition at line 428 of file autoarts.h.
~WorkspaceArrayOfArrayOfTensor3()
ARTS::Var::WorkspaceArrayOfArrayOfTensor3::~WorkspaceArrayOfArrayOfTensor3 () inline noexcept
Definition at line 429 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfTensor3() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfTensor3::WorkspaceArrayOfArrayOfTensor3 (const type & val) inline noexcept
Definition at line 430 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfTensor3::islast () const inline noexcept
Definition at line 436 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfTensor3().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfTensor3::isnull () const inline noexcept
Definition at line 435 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfTensor3().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfTensor3::name () const inline noexcept
Definition at line 437 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfTensor3& ARTS::Var::WorkspaceArrayOfArrayOfTensor3::operator= (const type & t) inline noexcept
Definition at line 433 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTensor3::pos () const inline noexcept
Definition at line 434 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfTensor3::value () const inline noexcept
Definition at line 432 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfTensor3::value () inline noexcept
Definition at line 431 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTensor3::p private
Definition at line 424 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfTensor3::v private
Definition at line 425 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfTensor3().
The documentation for this class was generated from the following file:
autoarts.h