ARTS: ARTS::Var::ArrayOfString Class Reference
ARTS::Var::ArrayOfString Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfString () noexcept
ArrayOfString (std::size_t i, void *x) noexcept
ArrayOfString (const Group::ArrayOfString &val) noexcept
~ArrayOfString () noexcept
Group::ArrayOfString & value () noexcept
const Group::ArrayOfString & value () const noexcept
ArrayOfString & operator= (const Group::ArrayOfString &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfString * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfString &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2209 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfString() [1/3]
ARTS::Var::ArrayOfString::ArrayOfString () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2214 of file autoarts.h.
ArrayOfString() [2/3]
ARTS::Var::ArrayOfString::ArrayOfString (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2217 of file autoarts.h.
ArrayOfString() [3/3]
ARTS::Var::ArrayOfString::ArrayOfString (const Group::ArrayOfString & val) inline noexcept
Construct from Group::ArrayOfString. Leaves islast() true and isnull() false
Definition at line 2220 of file autoarts.h.
~ArrayOfString()
ARTS::Var::ArrayOfString::~ArrayOfString () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2223 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfString::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2241 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_speciesAdd(), ARTS::Agenda::Method::abs_speciesSet(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Agenda::Method::ArrayOfStringSet(), ARTS::Agenda::Method::atm_fields_compactFromMatrix(), ARTS::Agenda::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Agenda::Method::CIAInfo(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameters(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameters(), ARTS::Agenda::Method::retrievalAddCatalogParameters(), ARTS::Agenda::Method::ScatElementsPndAndScatAdd(), ARTS::Agenda::Method::ScatElementsToabs_speciesAdd(), ARTS::Agenda::Method::ScatSpeciesPndAndScatAdd(), ARTS::Agenda::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfString().
isnull()
bool ARTS::Var::ArrayOfString::isnull () const inline noexcept
Return true if there is no data
Definition at line 2238 of file autoarts.h.
References v.
Referenced by ~ArrayOfString().
name()
const Group::String& ARTS::Var::ArrayOfString::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2244 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfString& ARTS::Var::ArrayOfString::operator= (const Group::ArrayOfString & t) inline noexcept
Set value from Group::ArrayOfString. Works when isnull() is false
Definition at line 2232 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfString::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2235 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_speciesAdd(), ARTS::Agenda::Method::abs_speciesSet(), ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::ArrayOfQuantumIdentifierSet(), ARTS::Agenda::Method::ArrayOfStringSet(), ARTS::Agenda::Method::atm_fields_compactFromMatrix(), ARTS::Agenda::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Agenda::Method::CIAInfo(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameters(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameters(), ARTS::Agenda::Method::retrievalAddCatalogParameters(), ARTS::Agenda::Method::ScatElementsPndAndScatAdd(), ARTS::Agenda::Method::ScatElementsToabs_speciesAdd(), ARTS::Agenda::Method::ScatSpeciesPndAndScatAdd(), ARTS::Agenda::Method::ScatSpeciesScatAndMetaRead(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfString& ARTS::Var::ArrayOfString::value () const inline noexcept
Get value const-ref as Group::ArrayOfString. Works when isnull() is false
Definition at line 2229 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfString& ARTS::Var::ArrayOfString::value () inline noexcept
Get value ref as Group::ArrayOfString. Works when isnull() is false
Definition at line 2226 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_speciesAdd(), ARTS::Method::abs_speciesSet(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Agenda::Method::ArrayOfStringSet(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::CIAInfo(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), operator=(), ARTS::Method::retrievalAddCatalogParameters(), ARTS::Method::ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::Select(), ARTS::Method::Touch(), and ARTS::Method::transmittanceFromIy_aux().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfString & var) friend
Output to stream of internal variable
Definition at line 2247 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfString::p private
Definition at line 2210 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfString* ARTS::Var::ArrayOfString::v private
Definition at line 2211 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfString().
The documentation for this class was generated from the following file:
autoarts.h