ARTS: my_basic_string< charT > Class Template Reference
my_basic_string< charT > Class Template Reference
The implementation for String, the ARTS string class.
#include <mystring.h>
Public Types
typedef Index size_type
Public Member Functions
my_basic_string ()=default
my_basic_string (Index n, char c=' ')
Constructor setting size.
my_basic_string (const std::basic_string< charT > &A, Index pos=0, Index numpos=my_basic_string< charT >::npos)
Construnctor from a basic_string.
my_basic_string (const char A[])
Constructor from a C-style char array.
my_basic_string (const std::string_view &sv)
Constructor from a std::string_view.
void insert_substr (const my_basic_string< charT > &searchstr, const my_basic_string< charT > &insstr)
Insert string before all occurrences of the substring.
void split (Array< my_basic_string< charT > > &aos, const my_basic_string< charT > &delim) const
Split string into substrings.
void toupper ()
Convert to upper case.
my_basic_string toupper () const
void tolower ()
Convert to lower case.
my_basic_string tolower () const
void trim ()
Trim leading and trailing whitespace.
Index nelem () const
Number of elements.
char operator[] (Index n) const
Constant index operator.
char & operator[] (Index n)
Non-constant index operator.
Static Public Attributes
static const Index npos = static_cast<Index>(std::basic_string<charT>::npos)
Define npos:
Detailed Description
template<class charT>
class my_basic_string< charT >
The implementation for String, the ARTS string class.
This adds some additional functionality to the standard stl string class, notably:
a) Range checking by assert
b) nelem() member function, return the size of the String of type Index.
The type string is just a typedef for basic_string<char>. Therefore, to make everything work correctly, we have to derive our own class from basic_string, not from string directly.
Definition at line 55 of file mystring.h.
Member Typedef Documentation
size_type
template<class charT > typedef Index my_basic_string< charT >::size_type
Definition at line 109 of file mystring.h.
Constructor & Destructor Documentation
my_basic_string() [1/5]
template<class charT > my_basic_string< charT >::my_basic_string () default
my_basic_string() [2/5]
template<class charT > my_basic_string< charT >::my_basic_string (Index n, char c = ' ') inline explicit
Constructor setting size.
You may give as a second argument a character with which to fill the new string. Per default this is zero.
Parameters
n Number of characters
c Optional fill character
Definition at line 124 of file mystring.h.
my_basic_string() [3/5]
template<class charT > my_basic_string< charT >::my_basic_string (const std::basic_string< charT > & A, Index pos = 0, Index numpos = my_basic_string<charT>::npos) inline
Construnctor from a basic_string.
This is important for handling of expressions like this to work correctly:
String a = b+'.'+c
As for basic_string, this constructor can also be used to initialize the new string from a subrange of the original string.
Parameters
A The original string
pos Start position (0 means from the beginning)
numpos How many characters to copy
Definition at line 141 of file mystring.h.
References ARTS_ASSERT.
my_basic_string() [4/5]
template<class charT > my_basic_string< charT >::my_basic_string (const char A[]) inline
Constructor from a C-style char array.
Definition at line 175 of file mystring.h.
my_basic_string() [5/5]
template<class charT > my_basic_string< charT >::my_basic_string (const std::string_view & sv) inline
Constructor from a std::string_view.
Definition at line 181 of file mystring.h.
Member Function Documentation
insert_substr()
template<class charT > void my_basic_string< charT >::insert_substr (const my_basic_string< charT > & searchstr, const my_basic_string< charT > & insstr) inline
Insert string before all occurrences of the substring.
Parameters
[in] searchstr String to search for.
[in] insstr String to insert.
Definition at line 191 of file mystring.h.
Referenced by write_method_header_documentation().
nelem()
template<class charT > Index my_basic_string< charT >::nelem inline
Number of elements.
Definition at line 253 of file mystring.h.
References ARTS_ASSERT.
Referenced by abs_linesChangeBaseParameterForMatchingLevel(), abs_linesChangeBaseParameterForMatchingLines(), abs_linesSetBaseParameterForMatchingLevel(), abs_linesSetBaseParameterForMatchingLines(), add_basedir(), AgendaExecute(), chk_griddedfield_gridname(), expand_path(), find_file(), ArtsXMLTag::get_attribute_value(), get_dirname(), get_parameters(), get_wsv_group_ids(), main(), LineShape::MetaData2ModelShape(), operator<<(), operator>>(), parse_a5_hitran(), ArtsParser::parse_agenda(), parse_f51_hitran(), lm_hitran_2017::read(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), CIARecord::ReadFromCIA(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitran2012Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromLBLRTMStream(), Absorption::ReadFromMytran2Stream(), SpeciesAuxData::ReadFromStream(), QuantumIdentifier::SetFromStringForCO2Band(), SpeciesTag::SpeciesTag(), my_basic_string< charT >::split(), my_basic_string< charT >::trim(), write_method_header(), and xml_read_from_file().
operator[]() [1/2]
template<class charT > char & my_basic_string< charT >::operator[] (Index n) inline
Non-constant index operator.
We redifine this here so that we can have range checking by assert.
Parameters
[in] n Index
Definition at line 279 of file mystring.h.
References ARTS_ASSERT, and Absorption::nelem().
operator[]() [2/2]
template<class charT > char my_basic_string< charT >::operator[] (Index n) const inline
Constant index operator.
We redifine this here so that we can have range checking by assert.
Parameters
[in] n Index
Definition at line 266 of file mystring.h.
References ARTS_ASSERT, and Absorption::nelem().
split()
template<class charT > void my_basic_string< charT >::split (Array< my_basic_string< charT > > & aos, const my_basic_string< charT > & delim) const inline
Split string into substrings.
Parameters
[out] aos ArrayOfString containing the returned substrings.
[in] delim Delimiter string.
Definition at line 213 of file mystring.h.
References my_basic_string< charT >::nelem(), and Absorption::nelem().
Referenced by get_dirname(), operator>>(), parse_a5_hitran(), parse_atmcompact_scattype(), parse_atmcompact_speciesname(), parse_atmcompact_speciestype(), parse_f51_hitran(), parse_partfield_name(), and ScatSpeciesScatAndMetaRead().
tolower() [1/2]
template<class charT > void my_basic_string< charT >::tolower () inline
Convert to lower case.
Definition at line 86 of file mystring.h.
References Zeeman::end(), and transform().
Referenced by my_basic_string< charT >::tolower().
tolower() [2/2]
template<class charT > my_basic_string my_basic_string< charT >::tolower () const inline
Definition at line 90 of file mystring.h.
References my_basic_string< charT >::tolower().
toupper() [1/2]
template<class charT > void my_basic_string< charT >::toupper () inline
Convert to upper case.
Definition at line 75 of file mystring.h.
References Zeeman::end(), and transform().
Referenced by atm_fields_compactFromMatrix(), chk_griddedfield_gridname(), scat_data_checkedCalc(), scat_dataCheck(), and my_basic_string< charT >::toupper().
toupper() [2/2]
template<class charT > my_basic_string my_basic_string< charT >::toupper () const inline
Definition at line 79 of file mystring.h.
References my_basic_string< charT >::toupper().
trim()
template<class charT > void my_basic_string< charT >::trim
Trim leading and trailing whitespace.
Definition at line 232 of file mystring.h.
References my_basic_string< charT >::nelem().
Referenced by parse_a5_hitran(), parse_f51_hitran(), Absorption::ReadFromArtscat4Stream(), species_index_from_species_name(), and SpeciesTag::SpeciesTag().
Member Data Documentation
npos
template<class charT > const Index my_basic_string< charT >::npos = static_cast<Index>(std::basic_string<charT>::npos) static
Define npos:
Definition at line 107 of file mystring.h.
Referenced by array_species_tag_from_string(), replace_all(), and SpeciesTag::SpeciesTag().
The documentation for this class was generated from the following file:
mystring.h