ARTS: ARTS::Var::ArrayOfCIARecord Class Reference
ARTS::Var::ArrayOfCIARecord Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfCIARecord () noexcept
ArrayOfCIARecord (std::size_t i, void *x) noexcept
ArrayOfCIARecord (const Group::ArrayOfCIARecord &val) noexcept
~ArrayOfCIARecord () noexcept
Group::ArrayOfCIARecord & value () noexcept
const Group::ArrayOfCIARecord & value () const noexcept
ArrayOfCIARecord & operator= (const Group::ArrayOfCIARecord &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfCIARecord * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfCIARecord &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1358 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfCIARecord() [1/3]
ARTS::Var::ArrayOfCIARecord::ArrayOfCIARecord () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1363 of file autoarts.h.
ArrayOfCIARecord() [2/3]
ARTS::Var::ArrayOfCIARecord::ArrayOfCIARecord (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1366 of file autoarts.h.
ArrayOfCIARecord() [3/3]
ARTS::Var::ArrayOfCIARecord::ArrayOfCIARecord (const Group::ArrayOfCIARecord & val) inline noexcept
Construct from Group::ArrayOfCIARecord. Leaves islast() true and isnull() false
Definition at line 1369 of file autoarts.h.
~ArrayOfCIARecord()
ARTS::Var::ArrayOfCIARecord::~ArrayOfCIARecord () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1372 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfCIARecord::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1390 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfCIARecord().
isnull()
bool ARTS::Var::ArrayOfCIARecord::isnull () const inline noexcept
Return true if there is no data
Definition at line 1387 of file autoarts.h.
References v.
Referenced by ~ArrayOfCIARecord().
name()
const Group::String& ARTS::Var::ArrayOfCIARecord::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1393 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfCIARecord& ARTS::Var::ArrayOfCIARecord::operator= (const Group::ArrayOfCIARecord & t) inline noexcept
Set value from Group::ArrayOfCIARecord. Works when isnull() is false
Definition at line 1381 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfCIARecord::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1384 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfCIARecord& ARTS::Var::ArrayOfCIARecord::value () const inline noexcept
Get value const-ref as Group::ArrayOfCIARecord. Works when isnull() is false
Definition at line 1378 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfCIARecord& ARTS::Var::ArrayOfCIARecord::value () inline noexcept
Get value ref as Group::ArrayOfCIARecord. Works when isnull() is false
Definition at line 1375 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfCIARecord & var) friend
Output to stream of internal variable
Definition at line 1396 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfCIARecord::p private
Definition at line 1359 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfCIARecord* ARTS::Var::ArrayOfCIARecord::v private
Definition at line 1360 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfCIARecord().
The documentation for this class was generated from the following file:
autoarts.h