ARTS: ARTS::Var::ArrayOfArrayOfVector Class Reference
ARTS::Var::ArrayOfArrayOfVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfVector () noexcept
ArrayOfArrayOfVector (std::size_t i, void *x) noexcept
ArrayOfArrayOfVector (const Group::ArrayOfArrayOfVector &val) noexcept
~ArrayOfArrayOfVector () noexcept
Group::ArrayOfArrayOfVector & value () noexcept
const Group::ArrayOfArrayOfVector & value () const noexcept
ArrayOfArrayOfVector & operator= (const Group::ArrayOfArrayOfVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1311 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfVector() [1/3]
ARTS::Var::ArrayOfArrayOfVector::ArrayOfArrayOfVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1316 of file autoarts.h.
ArrayOfArrayOfVector() [2/3]
ARTS::Var::ArrayOfArrayOfVector::ArrayOfArrayOfVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1319 of file autoarts.h.
ArrayOfArrayOfVector() [3/3]
ARTS::Var::ArrayOfArrayOfVector::ArrayOfArrayOfVector (const Group::ArrayOfArrayOfVector & val) inline noexcept
Construct from Group::ArrayOfArrayOfVector. Leaves islast() true and isnull() false
Definition at line 1322 of file autoarts.h.
~ArrayOfArrayOfVector()
ARTS::Var::ArrayOfArrayOfVector::~ArrayOfArrayOfVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1325 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1343 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfVector().
isnull()
bool ARTS::Var::ArrayOfArrayOfVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 1340 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfVector().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1346 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfVector& ARTS::Var::ArrayOfArrayOfVector::operator= (const Group::ArrayOfArrayOfVector & t) inline noexcept
Set value from Group::ArrayOfArrayOfVector. Works when isnull() is false
Definition at line 1334 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1337 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfVector& ARTS::Var::ArrayOfArrayOfVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfVector. Works when isnull() is false
Definition at line 1331 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfVector& ARTS::Var::ArrayOfArrayOfVector::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfVector. Works when isnull() is false
Definition at line 1328 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfVector & var) friend
Output to stream of internal variable
Definition at line 1349 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfVector::p private
Definition at line 1312 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfVector* ARTS::Var::ArrayOfArrayOfVector::v private
Definition at line 1313 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfVector().
The documentation for this class was generated from the following file:
autoarts.h