ARTS: ARTS::Var::WorkspaceTime Class Reference
ARTS::Var::WorkspaceTime Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTime () noexcept
WorkspaceTime (std::size_t i, void *x) noexcept
~WorkspaceTime () noexcept
WorkspaceTime (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTime & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Time
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1610 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTime::type = Group::Time private
Definition at line 1611 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTime() [1/3]
ARTS::Var::WorkspaceTime::WorkspaceTime () inline noexcept
Definition at line 1615 of file autoarts.h.
WorkspaceTime() [2/3]
ARTS::Var::WorkspaceTime::WorkspaceTime (std::size_t i, void * x) inline noexcept
Definition at line 1616 of file autoarts.h.
~WorkspaceTime()
ARTS::Var::WorkspaceTime::~WorkspaceTime () inline noexcept
Definition at line 1617 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTime() [3/3]
ARTS::Var::WorkspaceTime::WorkspaceTime (const type & val) inline noexcept
Definition at line 1618 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTime::islast () const inline noexcept
Definition at line 1624 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Sleep(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTime().
isnull()
bool ARTS::Var::WorkspaceTime::isnull () const inline noexcept
Definition at line 1623 of file autoarts.h.
References v.
Referenced by ~WorkspaceTime().
name()
const Group::String& ARTS::Var::WorkspaceTime::name () const inline noexcept
Definition at line 1625 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTime& ARTS::Var::WorkspaceTime::operator= (const type & t) inline noexcept
Definition at line 1621 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTime::pos () const inline noexcept
Definition at line 1622 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Sleep(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTime::value () const inline noexcept
Definition at line 1620 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTime::value () inline noexcept
Definition at line 1619 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Sleep(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTime::p private
Definition at line 1612 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTime::v private
Definition at line 1613 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTime().
The documentation for this class was generated from the following file:
autoarts.h