ARTS: ARTS::Var::WorkspaceArrayOfTensor3 Class Reference
ARTS::Var::WorkspaceArrayOfTensor3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTensor3 () noexcept
WorkspaceArrayOfTensor3 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTensor3 () noexcept
WorkspaceArrayOfTensor3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTensor3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 836 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTensor3::type = Group::ArrayOfTensor3 private
Definition at line 837 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTensor3() [1/3]
ARTS::Var::WorkspaceArrayOfTensor3::WorkspaceArrayOfTensor3 () inline noexcept
Definition at line 841 of file autoarts.h.
WorkspaceArrayOfTensor3() [2/3]
ARTS::Var::WorkspaceArrayOfTensor3::WorkspaceArrayOfTensor3 (std::size_t i, void * x) inline noexcept
Definition at line 842 of file autoarts.h.
~WorkspaceArrayOfTensor3()
ARTS::Var::WorkspaceArrayOfTensor3::~WorkspaceArrayOfTensor3 () inline noexcept
Definition at line 843 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTensor3() [3/3]
ARTS::Var::WorkspaceArrayOfTensor3::WorkspaceArrayOfTensor3 (const type & val) inline noexcept
Definition at line 844 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTensor3::islast () const inline noexcept
Definition at line 850 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTensor3().
isnull()
bool ARTS::Var::WorkspaceArrayOfTensor3::isnull () const inline noexcept
Definition at line 849 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTensor3().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTensor3::name () const inline noexcept
Definition at line 851 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTensor3& ARTS::Var::WorkspaceArrayOfTensor3::operator= (const type & t) inline noexcept
Definition at line 847 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTensor3::pos () const inline noexcept
Definition at line 848 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTensor3::value () const inline noexcept
Definition at line 846 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTensor3::value () inline noexcept
Definition at line 845 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTensor3::p private
Definition at line 838 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTensor3::v private
Definition at line 839 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTensor3().
The documentation for this class was generated from the following file:
autoarts.h