ARTS: Zeeman::Model Class Reference
Zeeman::Model Class Reference
Main Zeeman Model.
#include <zeemandata.h>
Public Member Functions
constexpr Model (SplittingData gs={NAN, NAN}) noexcept
Default copy/init of Model from its only private variable.
constexpr Model (Numeric gu, Numeric gl) noexcept
Default copy/init of Model from its only private variable.
Model (const QuantumIdentifier &qid) noexcept
Attempts to compute Zeeman input if available.
bool empty () const noexcept
Returns true if the Model represents no Zeeman effect.
constexpr Numeric & gu () noexcept
Returns the upper state g.
constexpr Numeric & gl () noexcept
Returns the lower state g.
constexpr void gu (Numeric x) noexcept
Sets the upper state g.
constexpr void gl (Numeric x) noexcept
Sets the lower state g.
constexpr Numeric gu () const noexcept
Returns the upper state g.
constexpr Numeric gl () const noexcept
Returns the lower state g.
Numeric Strength (Rational Ju, Rational Jl, Polarization type, Index n) const
Gives the strength of one subline of a given polarization.
constexpr Numeric Splitting (Rational Ju, Rational Jl, Polarization type, Index n) const noexcept
Gives the splitting of one subline of a given polarization.
Private Attributes
SplittingData mdata
Friends
std::ostream & operator<< (std::ostream &os, const Model &m)
Output operator for Zeeman::Model.
std::istream & operator>> (std::istream &is, Model &m)
Input operator for Zeeman::Model.
std::ostream & operator<< (bofstream &bof, const Model &m)
Output operator for Zeeman::Model.
std::istream & operator>> (bifstream &bif, Model &m)
Input operator for Zeeman::Model.
Detailed Description
Main Zeeman Model.
This model contains the splitting coefficients of an energy level. Various detailed and simplified initialization routines are defined. Is also used as the interface for all Zeeman computations
Definition at line 359 of file zeemandata.h.
Constructor & Destructor Documentation
Model() [1/3]
constexpr Zeeman::Model::Model (SplittingData gs = {NAN, NAN}) inline constexpr noexcept
Default copy/init of Model from its only private variable.
Definition at line 365 of file zeemandata.h.
Model() [2/3]
constexpr Zeeman::Model::Model (Numeric gu, Numeric gl) inline constexpr noexcept
Default copy/init of Model from its only private variable.
Definition at line 368 of file zeemandata.h.
References gl(), and gu().
Model() [3/3]
Zeeman::Model::Model (const QuantumIdentifier & qid) explicit noexcept
Attempts to compute Zeeman input if available.
Will first attempt advanced initialization from specialized functions for special species. If this fails, will attempt simple initialization from pure Hund-cases. If this fails, will throw a runtime_error.
Parameters
[in] qid Transition type quantum id
Definition at line 204 of file zeemandata.cc.
References empty(), Zeeman::GetAdvancedModel(), and Zeeman::GetSimpleModel().
Member Function Documentation
empty()
bool Zeeman::Model::empty () const inline noexcept
Returns true if the Model represents no Zeeman effect.
Definition at line 383 of file zeemandata.h.
References Zeeman::SplittingData::gl, Zeeman::SplittingData::gu, and mdata.
Referenced by Model().
gl() [1/3]
constexpr Numeric Zeeman::Model::gl () const inline constexpr noexcept
Returns the lower state g.
Definition at line 403 of file zeemandata.h.
References Zeeman::SplittingData::gl, and mdata.
gl() [2/3]
constexpr Numeric& Zeeman::Model::gl () inline constexpr noexcept
Returns the lower state g.
Definition at line 391 of file zeemandata.h.
References Zeeman::SplittingData::gl, and mdata.
Referenced by Model(), and test_zeeman().
gl() [3/3]
constexpr void Zeeman::Model::gl (Numeric x) inline constexpr noexcept
Sets the lower state g.
Definition at line 397 of file zeemandata.h.
References Zeeman::SplittingData::gl, mdata, and ARTS::Var::x().
gu() [1/3]
constexpr Numeric Zeeman::Model::gu () const inline constexpr noexcept
Returns the upper state g.
Definition at line 400 of file zeemandata.h.
References Zeeman::SplittingData::gu, and mdata.
gu() [2/3]
constexpr Numeric& Zeeman::Model::gu () inline constexpr noexcept
Returns the upper state g.
Definition at line 388 of file zeemandata.h.
References Zeeman::SplittingData::gu, and mdata.
Referenced by Model().
gu() [3/3]
constexpr void Zeeman::Model::gu (Numeric x) inline constexpr noexcept
Sets the upper state g.
Definition at line 394 of file zeemandata.h.
References Zeeman::SplittingData::gu, mdata, and ARTS::Var::x().
Splitting()
constexpr Numeric Zeeman::Model::Splitting (Rational Ju, Rational Jl, Polarization type, Index n) const inline constexpr noexcept
Gives the splitting of one subline of a given polarization.
The user has to ensure that Ju and Jl is a valid transition
The user has to ensure n is less than the number of elements
Parameters
[in] Ju J of the upper state
[in] Jl J of the upper state
[in] type The polarization type
[in] n The position
Returns
The splitting of the Zeeman subline
Definition at line 433 of file zeemandata.h.
Strength()
Numeric Zeeman::Model::Strength (Rational Ju, Rational Jl, Zeeman::Polarization type, Index n) const
Gives the strength of one subline of a given polarization.
The user has to ensure that Ju and Jl is a valid transition
The user has to ensure n is less than the number of elements
Parameters
[in] Ju J of the upper state
[in] Jl J of the upper state
[in] type The polarization type
[in] n The position
Returns
The relative strength of the Zeeman subline
Definition at line 284 of file zeemandata.cc.
References Zeeman::dM(), Zeeman::Ml(), Zeeman::Mu(), Zeeman::PolarizationFactor(), Constant::pow2(), Hitran::type, and wigner3j().
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (bofstream & bof, const Model & m) friend
Output operator for Zeeman::Model.
Definition at line 303 of file zeemandata.cc.
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const Model & m) friend
Output operator for Zeeman::Model.
Definition at line 293 of file zeemandata.cc.
operator>> [1/2]
std::istream& operator>> (bifstream & bif, Model & m) friend
Input operator for Zeeman::Model.
Definition at line 308 of file zeemandata.cc.
operator>> [2/2]
std::istream& operator>> (std::istream & is, Model & m) friend
Input operator for Zeeman::Model.
Definition at line 298 of file zeemandata.cc.
Member Data Documentation
mdata
SplittingData Zeeman::Model::mdata private
Definition at line 361 of file zeemandata.h.
Referenced by empty(), gl(), and gu().
The documentation for this class was generated from the following files:
zeemandata.h
zeemandata.cc