ARTS: XsecRecord Class Reference
XsecRecord Class Reference
#include <hitran_xsec.h>
Public Member Functions
Index Species () const
Return species index.
String SpeciesName () const
Return species name.
void SetSpecies (const Index species)
Set species name.
ConstVectorView Coeffs () const
Get coefficients.
ConstVectorView RefPressure () const
Get reference pressures.
ConstVectorView RefTemperature () const
Get reference temperatures.
const ArrayOfVector & Fgrids () const
Get frequency grids of cross sections.
const ArrayOfVector & Xsecs () const
Get cross sections.
const ArrayOfVector & TemperatureSlope () const
Get slope of temperature fit.
const ArrayOfVector & TemperatureIntersect () const
Get intersect of temperature fit.
Vector & Coeffs ()
Get coefficients.
Vector & RefPressure ()
Get reference pressures.
Vector & RefTemperature ()
Get reference temperatures.
ArrayOfVector & Fgrids ()
Get frequency grids of cross sections.
ArrayOfVector & Xsecs ()
Get cross sections.
ArrayOfVector & TemperatureSlope ()
Get slope of temperature fit.
ArrayOfVector & TemperatureIntersect ()
Get intersect of temperature fit.
void Extract (VectorView result, ConstVectorView f_grid, const Numeric &pressure, const Numeric &temperature, const Index &apply_tfit, const Verbosity &verbosity) const
Interpolate cross section data.
Private Attributes
Index mspecies
Vector mcoeffs
Vector mrefpressure
Vector mreftemperature
ArrayOfVector mfgrids
ArrayOfVector mxsecs
ArrayOfVector mtslope
ArrayOfVector mtintersect
Friends
void xml_read_from_stream (std::istream &is_xml, XsecRecord &cr, bifstream *pbifs, const Verbosity &verbosity)
Detailed Description
Definition at line 37 of file hitran_xsec.h.
Member Function Documentation
Coeffs() [1/2]
Vector& XsecRecord::Coeffs () inline
Get coefficients.
Definition at line 70 of file hitran_xsec.h.
References mcoeffs.
Coeffs() [2/2]
ConstVectorView XsecRecord::Coeffs () const inline
Get coefficients.
Definition at line 49 of file hitran_xsec.h.
References mcoeffs.
Referenced by xml_write_to_stream().
Extract()
void XsecRecord::Extract (VectorView result, ConstVectorView f_grid, const Numeric & pressure, const Numeric & temperature, const Index & apply_tfit, const Verbosity & verbosity) const
Interpolate cross section data.
Interpolate Xsec data to given frequency vector and given scalar pressure. Uses third order interpolation in both coordinates, if grid length allows, otherwise lower order or no interpolation.
Parameters
[out] result Xsec value for given frequency grid and temperature.
[in] f_grid Frequency grid.
[in] pressure Scalar pressure.
[in] temperature Scalar temperature.
[in] apply_tfit Set to 0 to not apply the temperature fit
[in] verbosity Standard verbosity object.
Definition at line 151 of file hitran_xsec.cc.
References chk_interpolation_grids(), convolve(), CREATE_OUTS, func_2straights(), gridpos_poly(), interp(), interpweights(), lorentz_pdf(), mcoeffs, mfgrids, mrefpressure, mreftemperature, mtintersect, mtslope, mxsecs, Array< base >::nelem(), ConstVectorView::nelem(), and Absorption::nelem().
Referenced by abs_xsec_per_speciesAddHitranXsec().
Fgrids() [1/2]
ArrayOfVector& XsecRecord::Fgrids () inline
Get frequency grids of cross sections.
Definition at line 79 of file hitran_xsec.h.
References mfgrids.
Fgrids() [2/2]
const ArrayOfVector& XsecRecord::Fgrids () const inline
Get frequency grids of cross sections.
Definition at line 58 of file hitran_xsec.h.
References mfgrids.
Referenced by xml_write_to_stream().
RefPressure() [1/2]
Vector& XsecRecord::RefPressure () inline
Get reference pressures.
Definition at line 73 of file hitran_xsec.h.
References mrefpressure.
RefPressure() [2/2]
ConstVectorView XsecRecord::RefPressure () const inline
Get reference pressures.
Definition at line 52 of file hitran_xsec.h.
References mrefpressure.
Referenced by xml_write_to_stream().
RefTemperature() [1/2]
Vector& XsecRecord::RefTemperature () inline
Get reference temperatures.
Definition at line 76 of file hitran_xsec.h.
References mreftemperature.
RefTemperature() [2/2]
ConstVectorView XsecRecord::RefTemperature () const inline
Get reference temperatures.
Definition at line 55 of file hitran_xsec.h.
References mreftemperature.
Referenced by xml_write_to_stream().
SetSpecies()
void XsecRecord::SetSpecies (const Index species) inline
Set species name.
Definition at line 46 of file hitran_xsec.h.
References mspecies.
Species()
Index XsecRecord::Species () const inline
Return species index.
Definition at line 40 of file hitran_xsec.h.
References mspecies.
Referenced by operator<<().
SpeciesName()
String XsecRecord::SpeciesName () const
Return species name.
Definition at line 53 of file hitran_xsec.cc.
References mspecies, and species_name_from_species_index().
Referenced by xml_write_to_stream().
TemperatureIntersect() [1/2]
ArrayOfVector& XsecRecord::TemperatureIntersect () inline
Get intersect of temperature fit.
Definition at line 88 of file hitran_xsec.h.
References mtintersect.
TemperatureIntersect() [2/2]
const ArrayOfVector& XsecRecord::TemperatureIntersect () const inline
Get intersect of temperature fit.
Definition at line 67 of file hitran_xsec.h.
References mtintersect.
Referenced by xml_write_to_stream().
TemperatureSlope() [1/2]
ArrayOfVector& XsecRecord::TemperatureSlope () inline
Get slope of temperature fit.
Definition at line 85 of file hitran_xsec.h.
References mtslope.
TemperatureSlope() [2/2]
const ArrayOfVector& XsecRecord::TemperatureSlope () const inline
Get slope of temperature fit.
Definition at line 64 of file hitran_xsec.h.
References mtslope.
Referenced by xml_write_to_stream().
Xsecs() [1/2]
ArrayOfVector& XsecRecord::Xsecs () inline
Get cross sections.
Definition at line 82 of file hitran_xsec.h.
References mxsecs.
Xsecs() [2/2]
const ArrayOfVector& XsecRecord::Xsecs () const inline
Get cross sections.
Definition at line 61 of file hitran_xsec.h.
References mxsecs.
Referenced by xml_write_to_stream().
Friends And Related Function Documentation
xml_read_from_stream
void xml_read_from_stream (std::istream & is_xml, XsecRecord & cr, bifstream * pbifs, const Verbosity & verbosity) friend
Member Data Documentation
mcoeffs
Vector XsecRecord::mcoeffs private
Definition at line 117 of file hitran_xsec.h.
Referenced by Coeffs(), Extract(), and xml_read_from_stream().
mfgrids
ArrayOfVector XsecRecord::mfgrids private
Definition at line 120 of file hitran_xsec.h.
Referenced by Extract(), Fgrids(), and xml_read_from_stream().
mrefpressure
Vector XsecRecord::mrefpressure private
Definition at line 118 of file hitran_xsec.h.
Referenced by Extract(), RefPressure(), and xml_read_from_stream().
mreftemperature
Vector XsecRecord::mreftemperature private
Definition at line 119 of file hitran_xsec.h.
Referenced by Extract(), RefTemperature(), and xml_read_from_stream().
mspecies
Index XsecRecord::mspecies private
Definition at line 116 of file hitran_xsec.h.
Referenced by SetSpecies(), Species(), SpeciesName(), and xml_read_from_stream().
mtintersect
ArrayOfVector XsecRecord::mtintersect private
Definition at line 123 of file hitran_xsec.h.
Referenced by Extract(), TemperatureIntersect(), and xml_read_from_stream().
mtslope
ArrayOfVector XsecRecord::mtslope private
Definition at line 122 of file hitran_xsec.h.
Referenced by Extract(), TemperatureSlope(), and xml_read_from_stream().
mxsecs
ArrayOfVector XsecRecord::mxsecs private
Definition at line 121 of file hitran_xsec.h.
Referenced by Extract(), xml_read_from_stream(), and Xsecs().
The documentation for this class was generated from the following files:
hitran_xsec.h
hitran_xsec.cc