ARTS: ARTS::Var::ArrayOfVector Class Reference
ARTS::Var::ArrayOfVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfVector () noexcept
ArrayOfVector (std::size_t i, void *x) noexcept
ArrayOfVector (const Group::ArrayOfVector &val) noexcept
~ArrayOfVector () noexcept
Group::ArrayOfVector & value () noexcept
const Group::ArrayOfVector & value () const noexcept
ArrayOfVector & operator= (const Group::ArrayOfVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2632 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfVector() [1/3]
ARTS::Var::ArrayOfVector::ArrayOfVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2637 of file autoarts.h.
ArrayOfVector() [2/3]
ARTS::Var::ArrayOfVector::ArrayOfVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2640 of file autoarts.h.
ArrayOfVector() [3/3]
ARTS::Var::ArrayOfVector::ArrayOfVector (const Group::ArrayOfVector & val) inline noexcept
Construct from Group::ArrayOfVector. Leaves islast() true and isnull() false
Definition at line 2643 of file autoarts.h.
~ArrayOfVector()
ARTS::Var::ArrayOfVector::~ArrayOfVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2646 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2664 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Method::Flatten(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::time_stampsSort(), ARTS::Agenda::Method::time_stampsSort(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfVector().
isnull()
bool ARTS::Var::ArrayOfVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 2661 of file autoarts.h.
References v.
Referenced by ~ArrayOfVector().
name()
const Group::String& ARTS::Var::ArrayOfVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2667 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
ArrayOfVector& ARTS::Var::ArrayOfVector::operator= (const Group::ArrayOfVector & t) inline noexcept
Set value from Group::ArrayOfVector. Works when isnull() is false
Definition at line 2655 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2658 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::Select(), ARTS::Agenda::Method::time_stampsSort(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfVector& ARTS::Var::ArrayOfVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfVector. Works when isnull() is false
Definition at line 2652 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfVector& ARTS::Var::ArrayOfVector::value () inline noexcept
Get value ref as Group::ArrayOfVector. Works when isnull() is false
Definition at line 2649 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), main(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Select(), ARTS::Method::time_stampsSort(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfVector & var) friend
Output to stream of internal variable
Definition at line 2670 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfVector::p private
Definition at line 2633 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfVector* ARTS::Var::ArrayOfVector::v private
Definition at line 2634 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfVector().
The documentation for this class was generated from the following file:
autoarts.h