ARTS: ARTS::Var::MCAntenna Class Reference
ARTS::Var::MCAntenna Class Reference
#include <autoarts.h>
Public Member Functions
MCAntenna () noexcept
MCAntenna (std::size_t i, void *x) noexcept
MCAntenna (const Group::MCAntenna &val) noexcept
~MCAntenna () noexcept
Group::MCAntenna & value () noexcept
const Group::MCAntenna & value () const noexcept
MCAntenna & operator= (const Group::MCAntenna &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::MCAntenna * v
Friends
std::ostream & operator<< (std::ostream &os, const MCAntenna &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3330 of file autoarts.h.
Constructor & Destructor Documentation
MCAntenna() [1/3]
ARTS::Var::MCAntenna::MCAntenna () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3335 of file autoarts.h.
MCAntenna() [2/3]
ARTS::Var::MCAntenna::MCAntenna (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3338 of file autoarts.h.
MCAntenna() [3/3]
ARTS::Var::MCAntenna::MCAntenna (const Group::MCAntenna & val) inline noexcept
Construct from Group::MCAntenna. Leaves islast() true and isnull() false
Definition at line 3341 of file autoarts.h.
~MCAntenna()
ARTS::Var::MCAntenna::~MCAntenna () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3344 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::MCAntenna::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3362 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~MCAntenna().
isnull()
bool ARTS::Var::MCAntenna::isnull () const inline noexcept
Return true if there is no data
Definition at line 3359 of file autoarts.h.
References v.
Referenced by ~MCAntenna().
name()
const Group::String& ARTS::Var::MCAntenna::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3365 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
MCAntenna& ARTS::Var::MCAntenna::operator= (const Group::MCAntenna & t) inline noexcept
Set value from Group::MCAntenna. Works when isnull() is false
Definition at line 3353 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::MCAntenna::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3356 of file autoarts.h.
References p.
value() [1/2]
const Group::MCAntenna& ARTS::Var::MCAntenna::value () const inline noexcept
Get value const-ref as Group::MCAntenna. Works when isnull() is false
Definition at line 3350 of file autoarts.h.
References v.
value() [2/2]
Group::MCAntenna& ARTS::Var::MCAntenna::value () inline noexcept
Get value ref as Group::MCAntenna. Works when isnull() is false
Definition at line 3347 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const MCAntenna & var) friend
Output to stream of internal variable
Definition at line 3368 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::MCAntenna::p private
Definition at line 3331 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::MCAntenna* ARTS::Var::MCAntenna::v private
Definition at line 3332 of file autoarts.h.
Referenced by isnull(), value(), and ~MCAntenna().
The documentation for this class was generated from the following file:
autoarts.h