ARTS: SpeciesRecord Class Reference
SpeciesRecord Class Reference
Contains the lookup data for one species.
#include <absorption.h>
Public Member Functions
SpeciesRecord ()
Default constructor.
SpeciesRecord (const char name[], const Index degfr, const Array< IsotopologueRecord > &isotopologue)
The constructor used in define_species_data.
const String & Name () const
Index Degfr () const
const Array< IsotopologueRecord > & Isotopologue () const
Array< IsotopologueRecord > & Isotopologue ()
String FullName (Index k) const
Return a copy of the full name of the k:th isotopologue.
Private Attributes
String mname
Species name.
Index mdegfr
Degrees of freedom.
Array< IsotopologueRecord > misotopologue
Isotopologue data.
Detailed Description
Contains the lookup data for one species.
Author
Stefan Buehler
Definition at line 144 of file absorption.h.
Constructor & Destructor Documentation
SpeciesRecord() [1/2]
SpeciesRecord::SpeciesRecord () inline
Default constructor.
Definition at line 147 of file absorption.h.
SpeciesRecord() [2/2]
SpeciesRecord::SpeciesRecord (const char name[], const Index degfr, const Array< IsotopologueRecord > & isotopologue) inline
The constructor used in define_species_data.
Definition at line 152 of file absorption.h.
References ARTS_ASSERT, misotopologue, and Array< base >::nelem().
Member Function Documentation
Degfr()
Index SpeciesRecord::Degfr () const inline
Definition at line 198 of file absorption.h.
References mdegfr.
Referenced by xml_write_to_stream().
FullName()
String SpeciesRecord::FullName (Index k) const inline
Return a copy of the full name of the k:th isotopologue.
Definition at line 205 of file absorption.h.
Isotopologue() [1/2]
Array<IsotopologueRecord>& SpeciesRecord::Isotopologue () inline
Definition at line 202 of file absorption.h.
References misotopologue.
Isotopologue() [2/2]
const Array<IsotopologueRecord>& SpeciesRecord::Isotopologue () const inline
Definition at line 199 of file absorption.h.
References misotopologue.
Referenced by checkIsotopologueRatios(), checkPartitionFunctions(), SpeciesTag::IsIsotopologue(), SpeciesTag::Name(), operator<<(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromJplStream(), Absorption::ReadFromLBLRTMStream(), Absorption::ReadFromMytran2Stream(), SpeciesAuxData::ReadFromStream(), QuantumIdentifier::SetFromString(), SpeciesAuxData::setParam(), species_iso_match(), QuantumIdentifier::SpeciesMass(), QuantumIdentifier::SpeciesName(), Absorption::Lines::SpeciesName(), SpeciesTag::SpeciesTag(), and xml_write_to_stream().
Name()
const String& SpeciesRecord::Name () const inline
Definition at line 197 of file absorption.h.
References mname.
Referenced by checkIsotopologueRatios(), checkPartitionFunctions(), SpeciesTag::Name(), operator<<(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), SpeciesAuxData::ReadFromStream(), QuantumIdentifier::SetFromString(), SpeciesAuxData::setParam(), species_name_from_species_index(), QuantumIdentifier::SpeciesName(), Absorption::Lines::SpeciesName(), and xml_write_to_stream().
Member Data Documentation
mdegfr
Index SpeciesRecord::mdegfr private
Degrees of freedom.
Definition at line 211 of file absorption.h.
Referenced by Degfr().
misotopologue
Array<IsotopologueRecord> SpeciesRecord::misotopologue private
Isotopologue data.
Definition at line 213 of file absorption.h.
Referenced by Isotopologue(), and SpeciesRecord().
mname
String SpeciesRecord::mname private
Species name.
Definition at line 209 of file absorption.h.
Referenced by Name().
The documentation for this class was generated from the following file:
absorption.h