ARTS: ARTS::Var::WorkspaceArrayOfMatrix Class Reference
ARTS::Var::WorkspaceArrayOfMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfMatrix () noexcept
WorkspaceArrayOfMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfMatrix () noexcept
WorkspaceArrayOfMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 620 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfMatrix::type = Group::ArrayOfMatrix private
Definition at line 621 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfMatrix::WorkspaceArrayOfMatrix () inline noexcept
Definition at line 625 of file autoarts.h.
WorkspaceArrayOfMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfMatrix::WorkspaceArrayOfMatrix (std::size_t i, void * x) inline noexcept
Definition at line 626 of file autoarts.h.
~WorkspaceArrayOfMatrix()
ARTS::Var::WorkspaceArrayOfMatrix::~WorkspaceArrayOfMatrix () inline noexcept
Definition at line 627 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfMatrix::WorkspaceArrayOfMatrix (const type & val) inline noexcept
Definition at line 628 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfMatrix::islast () const inline noexcept
Definition at line 634 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfMatrix::isnull () const inline noexcept
Definition at line 633 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfMatrix::name () const inline noexcept
Definition at line 635 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceArrayOfMatrix& ARTS::Var::WorkspaceArrayOfMatrix::operator= (const type & t) inline noexcept
Definition at line 631 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfMatrix::pos () const inline noexcept
Definition at line 632 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfMatrix::value () const inline noexcept
Definition at line 630 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfMatrix::value () inline noexcept
Definition at line 629 of file autoarts.h.
References v.
Referenced by ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Select(), ARTS::Method::Touch(), and ARTS::Method::transmittanceFromIy_aux().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfMatrix::p private
Definition at line 622 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfMatrix::v private
Definition at line 623 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfMatrix().
The documentation for this class was generated from the following file:
autoarts.h