ARTS: ARTS::Var::Timer Class Reference
ARTS::Var::Timer Class Reference
#include <autoarts.h>
Public Member Functions
Timer () noexcept
Timer (std::size_t i, void *x) noexcept
Timer (const Group::Timer &val) noexcept
~Timer () noexcept
Group::Timer & value () noexcept
const Group::Timer & value () const noexcept
Timer & operator= (const Group::Timer &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Timer * v
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4461 of file autoarts.h.
Constructor & Destructor Documentation
Timer() [1/3]
ARTS::Var::Timer::Timer () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4466 of file autoarts.h.
Timer() [2/3]
ARTS::Var::Timer::Timer (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4469 of file autoarts.h.
Timer() [3/3]
ARTS::Var::Timer::Timer (const Group::Timer & val) inline noexcept
Construct from Group::Timer. Leaves islast() true and isnull() false
Definition at line 4472 of file autoarts.h.
~Timer()
ARTS::Var::Timer::~Timer () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4475 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Timer::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4493 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Timer().
isnull()
bool ARTS::Var::Timer::isnull () const inline noexcept
Return true if there is no data
Definition at line 4490 of file autoarts.h.
References v.
Referenced by ~Timer().
name()
const Group::String& ARTS::Var::Timer::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4496 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Timer& ARTS::Var::Timer::operator= (const Group::Timer & t) inline noexcept
Set value from Group::Timer. Works when isnull() is false
Definition at line 4484 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Timer::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4487 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Timer& ARTS::Var::Timer::value () const inline noexcept
Get value const-ref as Group::Timer. Works when isnull() is false
Definition at line 4481 of file autoarts.h.
References v.
value() [2/2]
Group::Timer& ARTS::Var::Timer::value () inline noexcept
Get value ref as Group::Timer. Works when isnull() is false
Definition at line 4478 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::Timer::p private
Definition at line 4462 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Timer* ARTS::Var::Timer::v private
Definition at line 4463 of file autoarts.h.
Referenced by isnull(), value(), and ~Timer().
The documentation for this class was generated from the following file:
autoarts.h