ARTS: ARTS::Var::WorkspaceSparse Class Reference
ARTS::Var::WorkspaceSparse Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceSparse () noexcept
WorkspaceSparse (std::size_t i, void *x) noexcept
~WorkspaceSparse () noexcept
WorkspaceSparse (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceSparse & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Sparse
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1412 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceSparse::type = Group::Sparse private
Definition at line 1413 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceSparse() [1/3]
ARTS::Var::WorkspaceSparse::WorkspaceSparse () inline noexcept
Definition at line 1417 of file autoarts.h.
WorkspaceSparse() [2/3]
ARTS::Var::WorkspaceSparse::WorkspaceSparse (std::size_t i, void * x) inline noexcept
Definition at line 1418 of file autoarts.h.
~WorkspaceSparse()
ARTS::Var::WorkspaceSparse::~WorkspaceSparse () inline noexcept
Definition at line 1419 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceSparse() [3/3]
ARTS::Var::WorkspaceSparse::WorkspaceSparse (const type & val) inline noexcept
Definition at line 1420 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceSparse::islast () const inline noexcept
Definition at line 1426 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::Method::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::Method::DiagonalMatrix(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::MatrixCopySparse(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::SparseSparseMultiply(), ARTS::Method::SparseSparseMultiply(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceSparse().
isnull()
bool ARTS::Var::WorkspaceSparse::isnull () const inline noexcept
Definition at line 1425 of file autoarts.h.
References v.
Referenced by ~WorkspaceSparse().
name()
const Group::String& ARTS::Var::WorkspaceSparse::name () const inline noexcept
Definition at line 1427 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceSparse& ARTS::Var::WorkspaceSparse::operator= (const type & t) inline noexcept
Definition at line 1423 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceSparse::pos () const inline noexcept
Definition at line 1424 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::MatrixCopySparse(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::SparseSparseMultiply(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceSparse::value () const inline noexcept
Definition at line 1422 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceSparse::value () inline noexcept
Definition at line 1421 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::Ignore(), ARTS::Method::MatrixCopySparse(), ARTS::Method::ncolsGet(), ARTS::Method::nrowsGet(), operator=(), ARTS::Method::Select(), ARTS::Method::SparseSparseMultiply(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceSparse::p private
Definition at line 1414 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceSparse::v private
Definition at line 1415 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceSparse().
The documentation for this class was generated from the following file:
autoarts.h