ARTS: ARTS::Var::WorkspaceSpeciesAuxData Class Reference
ARTS::Var::WorkspaceSpeciesAuxData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceSpeciesAuxData () noexcept
WorkspaceSpeciesAuxData (std::size_t i, void *x) noexcept
~WorkspaceSpeciesAuxData () noexcept
WorkspaceSpeciesAuxData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceSpeciesAuxData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::SpeciesAuxData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1430 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceSpeciesAuxData::type = Group::SpeciesAuxData private
Definition at line 1431 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceSpeciesAuxData() [1/3]
ARTS::Var::WorkspaceSpeciesAuxData::WorkspaceSpeciesAuxData () inline noexcept
Definition at line 1435 of file autoarts.h.
WorkspaceSpeciesAuxData() [2/3]
ARTS::Var::WorkspaceSpeciesAuxData::WorkspaceSpeciesAuxData (std::size_t i, void * x) inline noexcept
Definition at line 1436 of file autoarts.h.
~WorkspaceSpeciesAuxData()
ARTS::Var::WorkspaceSpeciesAuxData::~WorkspaceSpeciesAuxData () inline noexcept
Definition at line 1437 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceSpeciesAuxData() [3/3]
ARTS::Var::WorkspaceSpeciesAuxData::WorkspaceSpeciesAuxData (const type & val) inline noexcept
Definition at line 1438 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceSpeciesAuxData::islast () const inline noexcept
Definition at line 1444 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceSpeciesAuxData().
isnull()
bool ARTS::Var::WorkspaceSpeciesAuxData::isnull () const inline noexcept
Definition at line 1443 of file autoarts.h.
References v.
Referenced by ~WorkspaceSpeciesAuxData().
name()
const Group::String& ARTS::Var::WorkspaceSpeciesAuxData::name () const inline noexcept
Definition at line 1445 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceSpeciesAuxData& ARTS::Var::WorkspaceSpeciesAuxData::operator= (const type & t) inline noexcept
Definition at line 1441 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceSpeciesAuxData::pos () const inline noexcept
Definition at line 1442 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceSpeciesAuxData::value () const inline noexcept
Definition at line 1440 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceSpeciesAuxData::value () inline noexcept
Definition at line 1439 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceSpeciesAuxData::p private
Definition at line 1432 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceSpeciesAuxData::v private
Definition at line 1433 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceSpeciesAuxData().
The documentation for this class was generated from the following file:
autoarts.h