ARTS: ARTS::Var::ArrayOfTelsemAtlas Class Reference
ARTS::Var::ArrayOfTelsemAtlas Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTelsemAtlas () noexcept
ArrayOfTelsemAtlas (std::size_t i, void *x) noexcept
~ArrayOfTelsemAtlas () noexcept
ArrayOfTelsemAtlas (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
ArrayOfTelsemAtlas & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTelsemAtlas
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 840 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::ArrayOfTelsemAtlas::type = Group::ArrayOfTelsemAtlas private
Definition at line 841 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTelsemAtlas() [1/3]
ARTS::Var::ArrayOfTelsemAtlas::ArrayOfTelsemAtlas () inline noexcept
Definition at line 845 of file autoarts.h.
ArrayOfTelsemAtlas() [2/3]
ARTS::Var::ArrayOfTelsemAtlas::ArrayOfTelsemAtlas (std::size_t i, void * x) inline noexcept
Definition at line 846 of file autoarts.h.
~ArrayOfTelsemAtlas()
ARTS::Var::ArrayOfTelsemAtlas::~ArrayOfTelsemAtlas () inline noexcept
Definition at line 847 of file autoarts.h.
References islast(), isnull(), and v.
ArrayOfTelsemAtlas() [3/3]
ARTS::Var::ArrayOfTelsemAtlas::ArrayOfTelsemAtlas (const type & val) inline noexcept
Definition at line 848 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTelsemAtlas::islast () const inline noexcept
Definition at line 854 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~ArrayOfTelsemAtlas().
isnull()
bool ARTS::Var::ArrayOfTelsemAtlas::isnull () const inline noexcept
Definition at line 853 of file autoarts.h.
References v.
Referenced by ~ArrayOfTelsemAtlas().
name()
const Group::String& ARTS::Var::ArrayOfTelsemAtlas::name () const inline noexcept
Definition at line 855 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
ArrayOfTelsemAtlas& ARTS::Var::ArrayOfTelsemAtlas::operator= (const type & t) inline noexcept
Definition at line 851 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTelsemAtlas::pos () const inline noexcept
Definition at line 852 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::ArrayOfTelsemAtlas::value () const inline noexcept
Definition at line 850 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::ArrayOfTelsemAtlas::value () inline noexcept
Definition at line 849 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTelsemAtlas::p private
Definition at line 842 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::ArrayOfTelsemAtlas::v private
Definition at line 843 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTelsemAtlas().
The documentation for this class was generated from the following file:
autoarts.h