ARTS: ARTS::Var::ArrayOfArrayOfTensor3 Class Reference
ARTS::Var::ArrayOfArrayOfTensor3 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfTensor3 () noexcept
ArrayOfArrayOfTensor3 (std::size_t i, void *x) noexcept
ArrayOfArrayOfTensor3 (const Group::ArrayOfArrayOfTensor3 &val) noexcept
~ArrayOfArrayOfTensor3 () noexcept
Group::ArrayOfArrayOfTensor3 & value () noexcept
const Group::ArrayOfArrayOfTensor3 & value () const noexcept
ArrayOfArrayOfTensor3 & operator= (const Group::ArrayOfArrayOfTensor3 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfTensor3 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfTensor3 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1130 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfTensor3() [1/3]
ARTS::Var::ArrayOfArrayOfTensor3::ArrayOfArrayOfTensor3 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1135 of file autoarts.h.
ArrayOfArrayOfTensor3() [2/3]
ARTS::Var::ArrayOfArrayOfTensor3::ArrayOfArrayOfTensor3 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1138 of file autoarts.h.
ArrayOfArrayOfTensor3() [3/3]
ARTS::Var::ArrayOfArrayOfTensor3::ArrayOfArrayOfTensor3 (const Group::ArrayOfArrayOfTensor3 & val) inline noexcept
Construct from Group::ArrayOfArrayOfTensor3. Leaves islast() true and isnull() false
Definition at line 1141 of file autoarts.h.
~ArrayOfArrayOfTensor3()
ARTS::Var::ArrayOfArrayOfTensor3::~ArrayOfArrayOfTensor3 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1144 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfTensor3::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1162 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfTensor3().
isnull()
bool ARTS::Var::ArrayOfArrayOfTensor3::isnull () const inline noexcept
Return true if there is no data
Definition at line 1159 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfTensor3().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfTensor3::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1165 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfTensor3& ARTS::Var::ArrayOfArrayOfTensor3::operator= (const Group::ArrayOfArrayOfTensor3 & t) inline noexcept
Set value from Group::ArrayOfArrayOfTensor3. Works when isnull() is false
Definition at line 1153 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfTensor3::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1156 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfTensor3& ARTS::Var::ArrayOfArrayOfTensor3::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfTensor3. Works when isnull() is false
Definition at line 1150 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfTensor3& ARTS::Var::ArrayOfArrayOfTensor3::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfTensor3. Works when isnull() is false
Definition at line 1147 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfTensor3 & var) friend
Output to stream of internal variable
Definition at line 1168 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfTensor3::p private
Definition at line 1131 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfTensor3* ARTS::Var::ArrayOfArrayOfTensor3::v private
Definition at line 1132 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfTensor3().
The documentation for this class was generated from the following file:
autoarts.h