ARTS: ARTS::Var::ArrayOfIndex Class Reference
ARTS::Var::ArrayOfIndex Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfIndex () noexcept
ArrayOfIndex (std::size_t i, void *x) noexcept
ArrayOfIndex (const Group::ArrayOfIndex &val) noexcept
~ArrayOfIndex () noexcept
Group::ArrayOfIndex & value () noexcept
const Group::ArrayOfIndex & value () const noexcept
ArrayOfIndex & operator= (const Group::ArrayOfIndex &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfIndex * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfIndex &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1593 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfIndex() [1/3]
ARTS::Var::ArrayOfIndex::ArrayOfIndex () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1598 of file autoarts.h.
ArrayOfIndex() [2/3]
ARTS::Var::ArrayOfIndex::ArrayOfIndex (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1601 of file autoarts.h.
ArrayOfIndex() [3/3]
ARTS::Var::ArrayOfIndex::ArrayOfIndex (const Group::ArrayOfIndex & val) inline noexcept
Construct from Group::ArrayOfIndex. Leaves islast() true and isnull() false
Definition at line 1604 of file autoarts.h.
~ArrayOfIndex()
ARTS::Var::ArrayOfIndex::~ArrayOfIndex () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1607 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfIndex::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1625 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::ArrayOfIndexLinSpace(), ARTS::Agenda::Method::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexSet(), ARTS::Agenda::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Agenda::Method::ArrayOfIndexSetConstant(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfIndex().
isnull()
bool ARTS::Var::ArrayOfIndex::isnull () const inline noexcept
Return true if there is no data
Definition at line 1622 of file autoarts.h.
References v.
Referenced by ~ArrayOfIndex().
name()
const Group::String& ARTS::Var::ArrayOfIndex::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1628 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfIndex& ARTS::Var::ArrayOfIndex::operator= (const Group::ArrayOfIndex & t) inline noexcept
Set value from Group::ArrayOfIndex. Works when isnull() is false
Definition at line 1616 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfIndex::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1619 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::ArrayOfIndexLinSpace(), ARTS::Agenda::Method::ArrayOfIndexSet(), ARTS::Agenda::Method::ArrayOfIndexSetConstant(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfIndex& ARTS::Var::ArrayOfIndex::value () const inline noexcept
Get value const-ref as Group::ArrayOfIndex. Works when isnull() is false
Definition at line 1613 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfIndex& ARTS::Var::ArrayOfIndex::value () inline noexcept
Get value ref as Group::ArrayOfIndex. Works when isnull() is false
Definition at line 1610 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexSet(), ARTS::Agenda::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfIndex & var) friend
Output to stream of internal variable
Definition at line 1631 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfIndex::p private
Definition at line 1594 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfIndex* ARTS::Var::ArrayOfIndex::v private
Definition at line 1595 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfIndex().
The documentation for this class was generated from the following file:
autoarts.h