ARTS: ARTS::Var::HitranRelaxationMatrixData Class Reference
ARTS::Var::HitranRelaxationMatrixData Class Reference
#include <autoarts.h>
Public Member Functions
HitranRelaxationMatrixData () noexcept
HitranRelaxationMatrixData (std::size_t i, void *x) noexcept
HitranRelaxationMatrixData (const Group::HitranRelaxationMatrixData &val) noexcept
~HitranRelaxationMatrixData () noexcept
Group::HitranRelaxationMatrixData & value () noexcept
const Group::HitranRelaxationMatrixData & value () const noexcept
HitranRelaxationMatrixData & operator= (const Group::HitranRelaxationMatrixData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::HitranRelaxationMatrixData * v
Friends
std::ostream & operator<< (std::ostream &os, const HitranRelaxationMatrixData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3189 of file autoarts.h.
Constructor & Destructor Documentation
HitranRelaxationMatrixData() [1/3]
ARTS::Var::HitranRelaxationMatrixData::HitranRelaxationMatrixData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3194 of file autoarts.h.
HitranRelaxationMatrixData() [2/3]
ARTS::Var::HitranRelaxationMatrixData::HitranRelaxationMatrixData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3197 of file autoarts.h.
HitranRelaxationMatrixData() [3/3]
ARTS::Var::HitranRelaxationMatrixData::HitranRelaxationMatrixData (const Group::HitranRelaxationMatrixData & val) inline noexcept
Construct from Group::HitranRelaxationMatrixData. Leaves islast() true and isnull() false
Definition at line 3200 of file autoarts.h.
~HitranRelaxationMatrixData()
ARTS::Var::HitranRelaxationMatrixData::~HitranRelaxationMatrixData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3203 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::HitranRelaxationMatrixData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3221 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~HitranRelaxationMatrixData().
isnull()
bool ARTS::Var::HitranRelaxationMatrixData::isnull () const inline noexcept
Return true if there is no data
Definition at line 3218 of file autoarts.h.
References v.
Referenced by ~HitranRelaxationMatrixData().
name()
const Group::String& ARTS::Var::HitranRelaxationMatrixData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3224 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
HitranRelaxationMatrixData& ARTS::Var::HitranRelaxationMatrixData::operator= (const Group::HitranRelaxationMatrixData & t) inline noexcept
Set value from Group::HitranRelaxationMatrixData. Works when isnull() is false
Definition at line 3212 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::HitranRelaxationMatrixData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3215 of file autoarts.h.
References p.
value() [1/2]
const Group::HitranRelaxationMatrixData& ARTS::Var::HitranRelaxationMatrixData::value () const inline noexcept
Get value const-ref as Group::HitranRelaxationMatrixData. Works when isnull() is false
Definition at line 3209 of file autoarts.h.
References v.
value() [2/2]
Group::HitranRelaxationMatrixData& ARTS::Var::HitranRelaxationMatrixData::value () inline noexcept
Get value ref as Group::HitranRelaxationMatrixData. Works when isnull() is false
Definition at line 3206 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const HitranRelaxationMatrixData & var) friend
Output to stream of internal variable
Definition at line 3227 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::HitranRelaxationMatrixData::p private
Definition at line 3190 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::HitranRelaxationMatrixData* ARTS::Var::HitranRelaxationMatrixData::v private
Definition at line 3191 of file autoarts.h.
Referenced by isnull(), value(), and ~HitranRelaxationMatrixData().
The documentation for this class was generated from the following file:
autoarts.h