ARTS: ARTS::Var::WorkspaceArrayOfTelsemAtlas Class Reference
ARTS::Var::WorkspaceArrayOfTelsemAtlas Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTelsemAtlas () noexcept
WorkspaceArrayOfTelsemAtlas (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTelsemAtlas () noexcept
WorkspaceArrayOfTelsemAtlas (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTelsemAtlas & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTelsemAtlas
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 818 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTelsemAtlas::type = Group::ArrayOfTelsemAtlas private
Definition at line 819 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTelsemAtlas() [1/3]
ARTS::Var::WorkspaceArrayOfTelsemAtlas::WorkspaceArrayOfTelsemAtlas () inline noexcept
Definition at line 823 of file autoarts.h.
WorkspaceArrayOfTelsemAtlas() [2/3]
ARTS::Var::WorkspaceArrayOfTelsemAtlas::WorkspaceArrayOfTelsemAtlas (std::size_t i, void * x) inline noexcept
Definition at line 824 of file autoarts.h.
~WorkspaceArrayOfTelsemAtlas()
ARTS::Var::WorkspaceArrayOfTelsemAtlas::~WorkspaceArrayOfTelsemAtlas () inline noexcept
Definition at line 825 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTelsemAtlas() [3/3]
ARTS::Var::WorkspaceArrayOfTelsemAtlas::WorkspaceArrayOfTelsemAtlas (const type & val) inline noexcept
Definition at line 826 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTelsemAtlas::islast () const inline noexcept
Definition at line 832 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTelsemAtlas().
isnull()
bool ARTS::Var::WorkspaceArrayOfTelsemAtlas::isnull () const inline noexcept
Definition at line 831 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTelsemAtlas().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTelsemAtlas::name () const inline noexcept
Definition at line 833 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTelsemAtlas& ARTS::Var::WorkspaceArrayOfTelsemAtlas::operator= (const type & t) inline noexcept
Definition at line 829 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTelsemAtlas::pos () const inline noexcept
Definition at line 830 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTelsemAtlas::value () const inline noexcept
Definition at line 828 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTelsemAtlas::value () inline noexcept
Definition at line 827 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTelsemAtlas::p private
Definition at line 820 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTelsemAtlas::v private
Definition at line 821 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTelsemAtlas().
The documentation for this class was generated from the following file:
autoarts.h