ARTS: ARTS::Var::WorkspacePpath Class Reference
ARTS::Var::WorkspacePpath Class Reference
#include <autoarts.h>
Public Member Functions
WorkspacePpath () noexcept
WorkspacePpath (std::size_t i, void *x) noexcept
~WorkspacePpath () noexcept
WorkspacePpath (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspacePpath & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Ppath
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1286 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspacePpath::type = Group::Ppath private
Definition at line 1287 of file autoarts.h.
Constructor & Destructor Documentation
WorkspacePpath() [1/3]
ARTS::Var::WorkspacePpath::WorkspacePpath () inline noexcept
Definition at line 1291 of file autoarts.h.
WorkspacePpath() [2/3]
ARTS::Var::WorkspacePpath::WorkspacePpath (std::size_t i, void * x) inline noexcept
Definition at line 1292 of file autoarts.h.
~WorkspacePpath()
ARTS::Var::WorkspacePpath::~WorkspacePpath () inline noexcept
Definition at line 1293 of file autoarts.h.
References islast(), isnull(), and v.
WorkspacePpath() [3/3]
ARTS::Var::WorkspacePpath::WorkspacePpath (const type & val) inline noexcept
Definition at line 1294 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspacePpath::islast () const inline noexcept
Definition at line 1300 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspacePpath().
isnull()
bool ARTS::Var::WorkspacePpath::isnull () const inline noexcept
Definition at line 1299 of file autoarts.h.
References v.
Referenced by ~WorkspacePpath().
name()
const Group::String& ARTS::Var::WorkspacePpath::name () const inline noexcept
Definition at line 1301 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspacePpath& ARTS::Var::WorkspacePpath::operator= (const type & t) inline noexcept
Definition at line 1297 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspacePpath::pos () const inline noexcept
Definition at line 1298 of file autoarts.h.
References p.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), cloud_RT_surface(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), diy_from_path_to_rgrids(), error_if_limb_ppath(), find_tanpoint(), geo_posEndOfPpath(), geo_posLowestAltitudeOfPpath(), geo_posWherePpathPassesZref(), get_iy_of_background(), ARTS::AgendaMethod::Ignore(), iyActiveSingleScat(), iyActiveSingleScat2(), iyIndependentBeamApproximation(), iyTransmissionStandard(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_init_structure(), ppath_start_1d(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_stepRefractionBasic(), ppathCalcFromAltitude(), ppathFromRtePos2(), ppathPlaneParallel(), rte_pos_losMoveToStartOfPpath(), TangentPointExtract(), TangentPointPrint(), ARTS::AgendaMethod::Touch(), xml_read_from_stream(), xml_write_to_stream(), and yActive().
value() [1/2]
const type& ARTS::Var::WorkspacePpath::value () const inline noexcept
Definition at line 1296 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspacePpath::value () inline noexcept
Definition at line 1295 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::TangentPointExtract(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspacePpath::p private
Definition at line 1288 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspacePpath::v private
Definition at line 1289 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspacePpath().
The documentation for this class was generated from the following file:
autoarts.h