ARTS: Tensor4 Class Reference
Tensor4 Class Reference
The Tensor4 class.
#include <matpackIV.h>
Public Member Functions
Tensor4 ()=default
Tensor4 (Index b, Index p, Index r, Index c)
Constructor setting size.
Tensor4 (Index b, Index p, Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Tensor4 (const ConstTensor4View &v)
Copy constructor from Tensor4View.
Tensor4 (const Tensor4 &v)
Copy constructor from Tensor4.
Tensor4 (Tensor4 &&v) noexcept
Tensor4 (Numeric *d, const Range &r0, const Range &r1, const Range &r2, const Range &r3) ARTS_NOEXCEPT
Tensor4 & operator= (const Tensor4 &x)
Assignment operator from another tensor.
Tensor4 & operator= (Tensor4 &&x) noexcept
Move assignment operator from another tensor.
Tensor4 & operator= (Numeric x)
Assignment operator from scalar.
void resize (Index b, Index p, Index r, Index c)
Resize function.
virtual ~Tensor4 ()
Destructor for Tensor4.
Index size () const noexcept
template<std::size_t dim0>
Vector reduce_rank () &&ARTS_NOEXCEPT
template<std::size_t dim0, std::size_t dim1>
Matrix reduce_rank () &&ARTS_NOEXCEPT
template<std::size_t dim0, std::size_t dim1, std::size_t dim2>
Tensor3 reduce_rank () &&ARTS_NOEXCEPT
Public Member Functions inherited from Tensor4View
constexpr Tensor4View (const Tensor4View &)=default
Tensor4View operator() (const Range &b, const Range &p, const Range &r, const Range &c)
Index operator for subrange.
Tensor3View operator() (const Range &b, const Range &p, const Range &r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &b, const Range &p, Index r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &b, Index p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index b, const Range &p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
MatrixView operator() (const Range &b, const Range &p, Index r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &b, Index p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &b, Index p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, const Range &p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, const Range &p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, Index p, const Range &r, const Range &c)
Index operator returning an object of type MatrixView.
VectorView operator() (const Range &b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, const Range &p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, Index p, const Range &r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, Index p, Index r, const Range &c)
Index operator returning an object of type VectorView.
Numeric & operator() (Index b, Index p, Index r, Index c)
Plain non-const index operator.
Numeric & get (Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array.
Numeric * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array.
Iterator4D begin ()
Return iterator to first book.
Iterator4D end ()
Return iterator behind last book.
Tensor4View & operator= (const ConstTensor4View &v)
Assignment operator.
Tensor4View & operator= (const Tensor4View &v)
Assignment from Tensor4View to Tensor4View.
Tensor4View & operator= (const Tensor4 &v)
Assignment from a Tensor4.
Tensor4View & operator= (Numeric x)
Assigning a scalar to a Tensor4View will set all elements to this value.
Tensor4View & operator*= (Numeric x)
Multiplication by scalar.
Tensor4View & operator/= (Numeric x)
Division by scalar.
Tensor4View & operator+= (Numeric x)
Addition of scalar.
Tensor4View & operator-= (Numeric x)
Subtraction of scalar.
Tensor4View & operator*= (const ConstTensor4View &x)
Element-vise multiplication by another Tensor4.
Tensor4View & operator/= (const ConstTensor4View &x)
Element-vise division by another Tensor4.
Tensor4View & operator+= (const ConstTensor4View &x)
Element-vise addition of another Tensor4.
Tensor4View & operator-= (const ConstTensor4View &x)
Element-vise subtraction of another Tensor4.
virtual ~Tensor4View ()=default
Destructor.
Tensor4View (const Tensor3View &a)
Special constructor to make a Tensor4 view of a Tensor3.
ConstIterator4D begin () const
Return const iterator to first book.
ConstIterator4D end () const
Return const iterator behind last book.
Numeric get (Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Public Member Functions inherited from ConstTensor4View
constexpr ConstTensor4View (const ConstTensor4View &)=default
constexpr ConstTensor4View (ConstTensor4View &&)=default
ConstTensor4View & operator= (const ConstTensor4View &)=default
ConstTensor4View & operator= (ConstTensor4View &&)=default
bool empty () const
Check if variable is empty.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor4View operator() (const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor3View operator() (const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator4D begin () const
Return const iterator to first book.
ConstIterator4D end () const
Return const iterator behind last book.
virtual ~ConstTensor4View ()=default
Destructor.
ConstTensor4View (const ConstTensor3View &a)
Special constructor to make a Tensor4 view of a Tensor3.
Friends
void swap (Tensor4 &t1, Tensor4 &t2)
Swaps two objects.
Additional Inherited Members
Protected Member Functions inherited from Tensor4View
Tensor4View ()=default
Tensor4View (Numeric *data, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor4View (Numeric *data, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor4View
ConstTensor4View ()=default
ConstTensor4View (Numeric *data, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor4View (Numeric *data, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes inherited from ConstTensor4View
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor4 class.
This is a Tensor4View that also allocates storage automatically, and deallocates it when it is destroyed. We take all the functionality from Tensor4View. Additionally defined here are:
Constructors and destructor.
Assignment operators.
Resize function.
Definition at line 421 of file matpackIV.h.
Constructor & Destructor Documentation
Tensor4() [1/7]
Tensor4::Tensor4 () default
Tensor4() [2/7]
Tensor4::Tensor4 (Index b, Index p, Index r, Index c)
Constructor setting size.
This constructor has to set the strides in the book, page and row ranges correctly!
Definition at line 946 of file matpackIV.cc.
Tensor4() [3/7]
Tensor4::Tensor4 (Index b, Index p, Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Definition at line 956 of file matpackIV.cc.
References b, c, and ConstTensor4View::mdata.
Tensor4() [4/7]
Tensor4::Tensor4 (const ConstTensor4View & m)
Copy constructor from Tensor4View.
This automatically sets the size and copies the data.
Definition at line 969 of file matpackIV.cc.
References Tensor4View::begin(), ConstTensor4View::begin(), copy(), and ConstTensor4View::end().
Tensor4() [5/7]
Tensor4::Tensor4 (const Tensor4 & m)
Copy constructor from Tensor4.
This automatically sets the size and copies the data.
Definition at line 980 of file matpackIV.cc.
References ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Tensor4() [6/7]
Tensor4::Tensor4 (Tensor4 && v) inline noexcept
Definition at line 429 of file matpackIV.h.
References v.
Tensor4() [7/7]
Tensor4::Tensor4 (Numeric * d, const Range & r0, const Range & r1, const Range & r2, const Range & r3) inline
Construct from known data
Note that this will call delete on the pointer if it is still valid at the end of the lifetime of this variable
Parameters
[in] d - A pointer to some raw data
[in] r0 - The Range along the first dimension
[in] r1 - The Range along the second dimension
[in] r2 - The Range along the third dimension
[in] r3 - The Range along the fourth dimension
Definition at line 444 of file matpackIV.h.
References ARTS_ASSERT.
~Tensor4()
Tensor4::~Tensor4 () virtual
Destructor for Tensor4.
This is important, since Tensor4 uses new to allocate storage.
Definition at line 1098 of file matpackIV.cc.
References ConstTensor4View::mdata.
Member Function Documentation
operator=() [1/3]
Tensor4 & Tensor4::operator= (const Tensor4 & x)
Assignment operator from another tensor.
While dimensions of views can not be adjusted, dimensions of tensors can be adjusted. Hence, the behavior of the assignment operator is different.
In this case the size of the target is automatically adjusted. This is important, so that structures containing tensors are copied correctly.
This is a deviation from the old ARTS paradigm that sizes must match exactly before copying!
Note: It is sufficient to have only this one version of the assignment (Tensor = Tensor). It implicitly covers the cases Tensor=TensorView, etc, because there is a default constructor for Tensor from TensorView. (See C++ Primer Plus, page 571ff.)
Parameters
m The other tensor to assign to this one.
Returns
This tensor, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 1020 of file matpackIV.cc.
References ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), resize(), and ARTS::Var::x().
operator=() [2/3]
Tensor4 & Tensor4::operator= (Numeric x)
Assignment operator from scalar.
Assignment operators are not inherited.
Definition at line 1050 of file matpackIV.cc.
References ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and ARTS::Var::x().
operator=() [3/3]
Tensor4 & Tensor4::operator= (Tensor4 && x) noexcept
Move assignment operator from another tensor.
Definition at line 1031 of file matpackIV.cc.
References ARTS::Var::x().
reduce_rank() [1/3]
template<std::size_t dim0> Vector Tensor4::reduce_rank () && inline
Reduce a Tensor4 to a Vector and leave this in an empty state
Definition at line 471 of file matpackIV.h.
References ARTS_ASSERT, ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and ConstVectorView::size().
Referenced by test48().
reduce_rank() [2/3]
template<std::size_t dim0, std::size_t dim1> Matrix Tensor4::reduce_rank () && inline
Reduce a Tensor4 to a Matrix and leave this in an empty state
Definition at line 484 of file matpackIV.h.
References ARTS_ASSERT, Range::get_extent(), ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Matrix::size().
reduce_rank() [3/3]
template<std::size_t dim0, std::size_t dim1, std::size_t dim2> Tensor3 Tensor4::reduce_rank () && inline
Reduce a Tensor4 to a Tensor3 and leave this in an empty state
Definition at line 499 of file matpackIV.h.
References ARTS_ASSERT, Range::get_extent(), ConstTensor4View::mdata, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor3::size().
resize()
void Tensor4::resize (Index b, Index p, Index r, Index c)
Resize function.
If the size is already correct this function does nothing. All data is lost after resizing! The new tensor is not initialized, so it will contain random values.
Definition at line 1058 of file matpackIV.cc.
References ARTS_ASSERT, b, c, ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
Referenced by GasAbsLookup::Adapt(), antenna_responseGaussian(), antenna_responseVaryingGaussian(), Append(), AtmFieldPRegrid(), Extract(), FieldFromGriddedField(), irradiance_fieldFromRadiance(), iyIndependentBeamApproximation(), nca_get_data_Tensor4(), nca_read_from_file(), StokesVector::operator=(), operator=(), PropagationMatrix::PropagationMatrix(), RadiationFieldSpectralIntegrate(), Reduce(), GriddedField4::resize(), StokesVector::StokesVector(), Tensor4AddScalar(), Tensor4Scale(), and xml_read_from_stream().
size()
Index Tensor4::size () const inline noexcept
Definition at line 467 of file matpackIV.h.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Referenced by Tensor5::reduce_rank(), Tensor6::reduce_rank(), and Tensor7::reduce_rank().
Friends And Related Function Documentation
swap
void swap (Tensor4 & t1, Tensor4 & t2) friend
Swaps two objects.
Definition at line 1088 of file matpackIV.cc.
The documentation for this class was generated from the following files:
matpackIV.h
matpackIV.cc