ARTS: ARTS::Var::JacobianTarget Class Reference
ARTS::Var::JacobianTarget Class Reference
#include <autoarts.h>
Public Member Functions
JacobianTarget () noexcept
JacobianTarget (std::size_t i, void *x) noexcept
JacobianTarget (const Group::JacobianTarget &val) noexcept
~JacobianTarget () noexcept
Group::JacobianTarget & value () noexcept
const Group::JacobianTarget & value () const noexcept
JacobianTarget & operator= (const Group::JacobianTarget &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::JacobianTarget * v
Friends
std::ostream & operator<< (std::ostream &os, const JacobianTarget &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3283 of file autoarts.h.
Constructor & Destructor Documentation
JacobianTarget() [1/3]
ARTS::Var::JacobianTarget::JacobianTarget () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3288 of file autoarts.h.
JacobianTarget() [2/3]
ARTS::Var::JacobianTarget::JacobianTarget (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3291 of file autoarts.h.
JacobianTarget() [3/3]
ARTS::Var::JacobianTarget::JacobianTarget (const Group::JacobianTarget & val) inline noexcept
Construct from Group::JacobianTarget. Leaves islast() true and isnull() false
Definition at line 3294 of file autoarts.h.
~JacobianTarget()
ARTS::Var::JacobianTarget::~JacobianTarget () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3297 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::JacobianTarget::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3315 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~JacobianTarget().
isnull()
bool ARTS::Var::JacobianTarget::isnull () const inline noexcept
Return true if there is no data
Definition at line 3312 of file autoarts.h.
References v.
Referenced by ~JacobianTarget().
name()
const Group::String& ARTS::Var::JacobianTarget::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3318 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
JacobianTarget& ARTS::Var::JacobianTarget::operator= (const Group::JacobianTarget & t) inline noexcept
Set value from Group::JacobianTarget. Works when isnull() is false
Definition at line 3306 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::JacobianTarget::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3309 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::JacobianTarget& ARTS::Var::JacobianTarget::value () const inline noexcept
Get value const-ref as Group::JacobianTarget. Works when isnull() is false
Definition at line 3303 of file autoarts.h.
References v.
value() [2/2]
Group::JacobianTarget& ARTS::Var::JacobianTarget::value () inline noexcept
Get value ref as Group::JacobianTarget. Works when isnull() is false
Definition at line 3300 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const JacobianTarget & var) friend
Output to stream of internal variable
Definition at line 3321 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::JacobianTarget::p private
Definition at line 3284 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::JacobianTarget* ARTS::Var::JacobianTarget::v private
Definition at line 3285 of file autoarts.h.
Referenced by isnull(), value(), and ~JacobianTarget().
The documentation for this class was generated from the following file:
autoarts.h