ARTS: ARTS::Var::ArrayOfTensor5 Class Reference
ARTS::Var::ArrayOfTensor5 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTensor5 () noexcept
ArrayOfTensor5 (std::size_t i, void *x) noexcept
ArrayOfTensor5 (const Group::ArrayOfTensor5 &val) noexcept
~ArrayOfTensor5 () noexcept
Group::ArrayOfTensor5 & value () noexcept
const Group::ArrayOfTensor5 & value () const noexcept
ArrayOfTensor5 & operator= (const Group::ArrayOfTensor5 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfTensor5 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfTensor5 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2397 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTensor5() [1/3]
ARTS::Var::ArrayOfTensor5::ArrayOfTensor5 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2402 of file autoarts.h.
ArrayOfTensor5() [2/3]
ARTS::Var::ArrayOfTensor5::ArrayOfTensor5 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2405 of file autoarts.h.
ArrayOfTensor5() [3/3]
ARTS::Var::ArrayOfTensor5::ArrayOfTensor5 (const Group::ArrayOfTensor5 & val) inline noexcept
Construct from Group::ArrayOfTensor5. Leaves islast() true and isnull() false
Definition at line 2408 of file autoarts.h.
~ArrayOfTensor5()
ARTS::Var::ArrayOfTensor5::~ArrayOfTensor5 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2411 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTensor5::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2429 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Agenda::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfTensor5().
isnull()
bool ARTS::Var::ArrayOfTensor5::isnull () const inline noexcept
Return true if there is no data
Definition at line 2426 of file autoarts.h.
References v.
Referenced by ~ArrayOfTensor5().
name()
const Group::String& ARTS::Var::ArrayOfTensor5::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2432 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfTensor5& ARTS::Var::ArrayOfTensor5::operator= (const Group::ArrayOfTensor5 & t) inline noexcept
Set value from Group::ArrayOfTensor5. Works when isnull() is false
Definition at line 2420 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTensor5::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2423 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfTensor5& ARTS::Var::ArrayOfTensor5::value () const inline noexcept
Get value const-ref as Group::ArrayOfTensor5. Works when isnull() is false
Definition at line 2417 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfTensor5& ARTS::Var::ArrayOfTensor5::value () inline noexcept
Get value ref as Group::ArrayOfTensor5. Works when isnull() is false
Definition at line 2414 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::Copy(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfTensor5 & var) friend
Output to stream of internal variable
Definition at line 2435 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTensor5::p private
Definition at line 2398 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfTensor5* ARTS::Var::ArrayOfTensor5::v private
Definition at line 2399 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTensor5().
The documentation for this class was generated from the following file:
autoarts.h