ARTS: ARTS::Var::Rational Class Reference
ARTS::Var::Rational Class Reference
#include <autoarts.h>
Public Member Functions
Rational () noexcept
Rational (std::size_t i, void *x) noexcept
Rational (const Group::Rational &val) noexcept
~Rational () noexcept
Group::Rational & value () noexcept
const Group::Rational & value () const noexcept
Rational & operator= (const Group::Rational &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Rational * v
Friends
std::ostream & operator<< (std::ostream &os, const Rational &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3758 of file autoarts.h.
Constructor & Destructor Documentation
Rational() [1/3]
ARTS::Var::Rational::Rational () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3763 of file autoarts.h.
Rational() [2/3]
ARTS::Var::Rational::Rational (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3766 of file autoarts.h.
Rational() [3/3]
ARTS::Var::Rational::Rational (const Group::Rational & val) inline noexcept
Construct from Group::Rational. Leaves islast() true and isnull() false
Definition at line 3769 of file autoarts.h.
~Rational()
ARTS::Var::Rational::~Rational () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3772 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Rational::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3790 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::RationalAdd(), ARTS::Agenda::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Agenda::Method::RationalInvScale(), ARTS::Method::RationalScale(), ARTS::Agenda::Method::RationalScale(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Rational().
isnull()
bool ARTS::Var::Rational::isnull () const inline noexcept
Return true if there is no data
Definition at line 3787 of file autoarts.h.
References v.
Referenced by ~Rational().
name()
const Group::String& ARTS::Var::Rational::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3793 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Rational& ARTS::Var::Rational::operator= (const Group::Rational & t) inline noexcept
Set value from Group::Rational. Works when isnull() is false
Definition at line 3781 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Rational::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3784 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::RationalAdd(), ARTS::Agenda::Method::RationalInvScale(), ARTS::Agenda::Method::RationalScale(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Rational& ARTS::Var::Rational::value () const inline noexcept
Get value const-ref as Group::Rational. Works when isnull() is false
Definition at line 3778 of file autoarts.h.
References v.
value() [2/2]
Group::Rational& ARTS::Var::Rational::value () inline noexcept
Get value ref as Group::Rational. Works when isnull() is false
Definition at line 3775 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Method::RationalScale(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Rational & var) friend
Output to stream of internal variable
Definition at line 3796 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Rational::p private
Definition at line 3759 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Rational* ARTS::Var::Rational::v private
Definition at line 3760 of file autoarts.h.
Referenced by isnull(), value(), and ~Rational().
The documentation for this class was generated from the following file:
autoarts.h