ARTS: ARTS::Var::WorkspaceArrayOfPropagationMatrix Class Reference
ARTS::Var::WorkspaceArrayOfPropagationMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfPropagationMatrix () noexcept
WorkspaceArrayOfPropagationMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfPropagationMatrix () noexcept
WorkspaceArrayOfPropagationMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfPropagationMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfPropagationMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 656 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfPropagationMatrix::type = Group::ArrayOfPropagationMatrix private
Definition at line 657 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfPropagationMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfPropagationMatrix::WorkspaceArrayOfPropagationMatrix () inline noexcept
Definition at line 661 of file autoarts.h.
WorkspaceArrayOfPropagationMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfPropagationMatrix::WorkspaceArrayOfPropagationMatrix (std::size_t i, void * x) inline noexcept
Definition at line 662 of file autoarts.h.
~WorkspaceArrayOfPropagationMatrix()
ARTS::Var::WorkspaceArrayOfPropagationMatrix::~WorkspaceArrayOfPropagationMatrix () inline noexcept
Definition at line 663 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfPropagationMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfPropagationMatrix::WorkspaceArrayOfPropagationMatrix (const type & val) inline noexcept
Definition at line 664 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfPropagationMatrix::islast () const inline noexcept
Definition at line 670 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfPropagationMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfPropagationMatrix::isnull () const inline noexcept
Definition at line 669 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfPropagationMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfPropagationMatrix::name () const inline noexcept
Definition at line 671 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfPropagationMatrix& ARTS::Var::WorkspaceArrayOfPropagationMatrix::operator= (const type & t) inline noexcept
Definition at line 667 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfPropagationMatrix::pos () const inline noexcept
Definition at line 668 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfPropagationMatrix::value () const inline noexcept
Definition at line 666 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfPropagationMatrix::value () inline noexcept
Definition at line 665 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfPropagationMatrix::p private
Definition at line 658 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfPropagationMatrix::v private
Definition at line 659 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfPropagationMatrix().
The documentation for this class was generated from the following file:
autoarts.h