ARTS: Tensor7View Class Reference
Tensor7View Class Reference
The Tensor7View class.
#include <matpackVII.h>
Public Member Functions
constexpr Tensor7View (const Tensor7View &)=default
Tensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & get (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
Iterator7D begin ()
Return iterator to first sub-tensor.
Iterator7D end ()
Return iterator behind last sub-tensor.
Tensor7View & operator= (const ConstTensor7View &v)
Assignment operator.
Tensor7View & operator= (const Tensor7View &v)
Assignment from Tensor7View to Tensor7View.
Tensor7View & operator= (const Tensor7 &v)
Assignment from a Tensor7.
Tensor7View & operator= (Numeric x)
Assigning a scalar to a Tensor7View will set all elements to this value.
Tensor7View & operator*= (Numeric x)
Multiplication by scalar.
Tensor7View & operator/= (Numeric x)
Division by scalar.
Tensor7View & operator+= (Numeric x)
Addition of scalar.
Tensor7View & operator-= (Numeric x)
Subtraction of scalar.
Tensor7View & operator*= (const ConstTensor7View &x)
Element-vise multiplication by another Tensor7.
Tensor7View & operator/= (const ConstTensor7View &x)
Element-vise division by another Tensor7.
Tensor7View & operator+= (const ConstTensor7View &x)
Element-vise addition of another Tensor7.
Tensor7View & operator-= (const ConstTensor7View &x)
Element-vise subtraction of another Tensor7.
virtual ~Tensor7View ()=default
Destructor.
Tensor7View (const Tensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Public Member Functions inherited from ConstTensor7View
constexpr ConstTensor7View (const ConstTensor7View &)=default
constexpr ConstTensor7View (ConstTensor7View &&)=default
ConstTensor7View & operator= (const ConstTensor7View &)=default
ConstTensor7View & operator= (ConstTensor7View &&)=default
bool empty () const
Check if variable is empty.
Index nlibraries () const
Returns the number of libraries.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor7View ()=default
Destructor.
ConstTensor7View (const ConstTensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
Protected Member Functions
Tensor7View ()=default
Tensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor7View
ConstTensor7View ()=default
ConstTensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Additional Inherited Members
Protected Attributes inherited from ConstTensor7View
Range mlr {0, 0, 1}
The library range of mdata that is actually used.
Range mvr {0, 0, 1}
The vitrine range of mdata that is actually used.
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor7View class.
This contains the main implementation of a Tensor7. It defines the concepts of Tensor7View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor7View from a subrange of a Tensor7View.
The class Tensor7 is just a special case of a Tensor7View which also allocates storage.
Definition at line 1286 of file matpackVII.h.
Constructor & Destructor Documentation
Tensor7View() [1/5]
constexpr Tensor7View::Tensor7View (const Tensor7View &) constexpr default
~Tensor7View()
virtual Tensor7View::~Tensor7View () virtual default
Destructor.
Tensor7View() [2/5]
Tensor7View::Tensor7View (const Tensor6View & a)
Special constructor to make a Tensor7 view of a Tensor6.
Definition at line 5225 of file matpackVII.cc.
Tensor7View() [3/5]
Tensor7View::Tensor7View () protected default
Tensor7View() [4/5]
Tensor7View::Tensor7View (Numeric * data, const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor7 to initialize its own Tensor7View part.
Definition at line 5242 of file matpackVII.cc.
Tensor7View() [5/5]
Tensor7View::Tensor7View (Numeric * data, const Range & pl, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nl, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pl Previous range.
pv Previous range.
ps Previous range.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
nl New Range.
nv New Range.
ns New Range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 5278 of file matpackVII.cc.
Member Function Documentation
begin() [1/2]
Iterator7D Tensor7View::begin ()
Return iterator to first sub-tensor.
Definition at line 5033 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and Tensor7::Tensor7().
begin() [2/2]
ConstIterator7D ConstTensor7View::begin
Return const iterator to first sub-tensor.
Definition at line 1218 of file matpackVII.cc.
end() [1/2]
Iterator7D Tensor7View::end ()
Return iterator behind last sub-tensor.
Definition at line 5040 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
end() [2/2]
ConstIterator7D ConstTensor7View::end
Return const iterator behind last sub-tensor.
Definition at line 1219 of file matpackVII.cc.
get() [1/2]
Numeric& Tensor7View::get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 2308 of file matpackVII.h.
get() [2/2]
Numeric ConstTensor7View::get inline
Get element implementation without assertions.
Definition at line 1211 of file matpackVII.h.
get_c_array() [1/2]
Numeric * Tensor7View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 4986 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
get_c_array() [2/2]
const Numeric * Tensor7View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 5012 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
Referenced by get_variable_value(), and Reduce().
operator()() [1/128]
Tensor7View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2596 of file matpackVII.cc.
operator()() [2/128]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2620 of file matpackVII.cc.
operator()() [3/128]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 2646 of file matpackVII.cc.
operator()() [4/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 2776 of file matpackVII.cc.
operator()() [5/128]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 2672 of file matpackVII.cc.
operator()() [6/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 2811 of file matpackVII.cc.
operator()() [7/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 2951 of file matpackVII.cc.
operator()() [8/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 3301 of file matpackVII.cc.
operator()() [9/128]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 2698 of file matpackVII.cc.
operator()() [10/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 2846 of file matpackVII.cc.
operator()() [11/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 2986 of file matpackVII.cc.
operator()() [12/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 3343 of file matpackVII.cc.
operator()() [13/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3091 of file matpackVII.cc.
operator()() [14/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 3469 of file matpackVII.cc.
operator()() [15/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 3721 of file matpackVII.cc.
operator()() [16/128]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4715 of file matpackVII.cc.
operator()() [17/128]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2724 of file matpackVII.cc.
operator()() [18/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2881 of file matpackVII.cc.
operator()() [19/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3021 of file matpackVII.cc.
operator()() [20/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3385 of file matpackVII.cc.
operator()() [21/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3126 of file matpackVII.cc.
operator()() [22/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3511 of file matpackVII.cc.
operator()() [23/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3763 of file matpackVII.cc.
operator()() [24/128]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4674 of file matpackVII.cc.
operator()() [25/128]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3196 of file matpackVII.cc.
operator()() [26/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3595 of file matpackVII.cc.
operator()() [27/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3847 of file matpackVII.cc.
operator()() [28/128]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4592 of file matpackVII.cc.
operator()() [29/128]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3973 of file matpackVII.cc.
operator()() [30/128]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4469 of file matpackVII.cc.
operator()() [31/128]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4305 of file matpackVII.cc.
operator()() [32/128]
MatrixView Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4931 of file matpackVII.cc.
operator()() [33/128]
Tensor6View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2750 of file matpackVII.cc.
operator()() [34/128]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2916 of file matpackVII.cc.
operator()() [35/128]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3056 of file matpackVII.cc.
operator()() [36/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3427 of file matpackVII.cc.
operator()() [37/128]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3161 of file matpackVII.cc.
operator()() [38/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3553 of file matpackVII.cc.
operator()() [39/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3805 of file matpackVII.cc.
operator()() [40/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 4633 of file matpackVII.cc.
operator()() [41/128]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3231 of file matpackVII.cc.
operator()() [42/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3637 of file matpackVII.cc.
operator()() [43/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3889 of file matpackVII.cc.
operator()() [44/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 4551 of file matpackVII.cc.
operator()() [45/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4015 of file matpackVII.cc.
operator()() [46/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 4428 of file matpackVII.cc.
operator()() [47/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 4264 of file matpackVII.cc.
operator()() [48/128]
MatrixView Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4896 of file matpackVII.cc.
operator()() [49/128]
Tensor5View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3266 of file matpackVII.cc.
operator()() [50/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3679 of file matpackVII.cc.
operator()() [51/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3931 of file matpackVII.cc.
operator()() [52/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 4510 of file matpackVII.cc.
operator()() [53/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 4057 of file matpackVII.cc.
operator()() [54/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 4387 of file matpackVII.cc.
operator()() [55/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 4223 of file matpackVII.cc.
operator()() [56/128]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4861 of file matpackVII.cc.
operator()() [57/128]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 4099 of file matpackVII.cc.
operator()() [58/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 4346 of file matpackVII.cc.
operator()() [59/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4182 of file matpackVII.cc.
operator()() [60/128]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4826 of file matpackVII.cc.
operator()() [61/128]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4141 of file matpackVII.cc.
operator()() [62/128]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4791 of file matpackVII.cc.
operator()() [63/128]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4756 of file matpackVII.cc.
operator()() [64/128]
VectorView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4966 of file matpackVII.cc.
operator()() [65/128]
Tensor6View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2607 of file matpackVII.cc.
operator()() [66/128]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2632 of file matpackVII.cc.
operator()() [67/128]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 2658 of file matpackVII.cc.
operator()() [68/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 2789 of file matpackVII.cc.
operator()() [69/128]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 2684 of file matpackVII.cc.
operator()() [70/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 2824 of file matpackVII.cc.
operator()() [71/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 2964 of file matpackVII.cc.
operator()() [72/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 3322 of file matpackVII.cc.
operator()() [73/128]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 2710 of file matpackVII.cc.
operator()() [74/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 2859 of file matpackVII.cc.
operator()() [75/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 2999 of file matpackVII.cc.
operator()() [76/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 3364 of file matpackVII.cc.
operator()() [77/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3104 of file matpackVII.cc.
operator()() [78/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 3490 of file matpackVII.cc.
operator()() [79/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 3742 of file matpackVII.cc.
operator()() [80/128]
MatrixView Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4735 of file matpackVII.cc.
operator()() [81/128]
Tensor5View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2736 of file matpackVII.cc.
operator()() [82/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2894 of file matpackVII.cc.
operator()() [83/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3034 of file matpackVII.cc.
operator()() [84/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3406 of file matpackVII.cc.
operator()() [85/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3139 of file matpackVII.cc.
operator()() [86/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3532 of file matpackVII.cc.
operator()() [87/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3784 of file matpackVII.cc.
operator()() [88/128]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4694 of file matpackVII.cc.
operator()() [89/128]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3209 of file matpackVII.cc.
operator()() [90/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3616 of file matpackVII.cc.
operator()() [91/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3868 of file matpackVII.cc.
operator()() [92/128]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4612 of file matpackVII.cc.
operator()() [93/128]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3994 of file matpackVII.cc.
operator()() [94/128]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4489 of file matpackVII.cc.
operator()() [95/128]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4325 of file matpackVII.cc.
operator()() [96/128]
VectorView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4951 of file matpackVII.cc.
operator()() [97/128]
Tensor5View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 2762 of file matpackVII.cc.
operator()() [98/128]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 2929 of file matpackVII.cc.
operator()() [99/128]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3069 of file matpackVII.cc.
operator()() [100/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3448 of file matpackVII.cc.
operator()() [101/128]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3174 of file matpackVII.cc.
operator()() [102/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3574 of file matpackVII.cc.
operator()() [103/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3826 of file matpackVII.cc.
operator()() [104/128]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 4653 of file matpackVII.cc.
operator()() [105/128]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3244 of file matpackVII.cc.
operator()() [106/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3658 of file matpackVII.cc.
operator()() [107/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3910 of file matpackVII.cc.
operator()() [108/128]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 4571 of file matpackVII.cc.
operator()() [109/128]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4036 of file matpackVII.cc.
operator()() [110/128]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 4448 of file matpackVII.cc.
operator()() [111/128]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 4284 of file matpackVII.cc.
operator()() [112/128]
VectorView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4916 of file matpackVII.cc.
operator()() [113/128]
Tensor4View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3279 of file matpackVII.cc.
operator()() [114/128]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3700 of file matpackVII.cc.
operator()() [115/128]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3952 of file matpackVII.cc.
operator()() [116/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 4530 of file matpackVII.cc.
operator()() [117/128]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 4078 of file matpackVII.cc.
operator()() [118/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 4407 of file matpackVII.cc.
operator()() [119/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 4243 of file matpackVII.cc.
operator()() [120/128]
VectorView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4881 of file matpackVII.cc.
operator()() [121/128]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 4120 of file matpackVII.cc.
operator()() [122/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 4366 of file matpackVII.cc.
operator()() [123/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4202 of file matpackVII.cc.
operator()() [124/128]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4846 of file matpackVII.cc.
operator()() [125/128]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4161 of file matpackVII.cc.
operator()() [126/128]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4811 of file matpackVII.cc.
operator()() [127/128]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4776 of file matpackVII.cc.
operator()() [128/128]
Numeric& Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) inline
Definition at line 2295 of file matpackVII.h.
operator*=() [1/2]
Tensor7View & Tensor7View::operator*= (const ConstTensor7View & x)
Element-vise multiplication by another Tensor7.
Definition at line 5153 of file matpackVII.cc.
References begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and x.
operator*=() [2/2]
Tensor7View & Tensor7View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 5117 of file matpackVII.cc.
References begin(), end(), and x.
operator+=() [1/2]
Tensor7View & Tensor7View::operator+= (const ConstTensor7View & x)
Element-vise addition of another Tensor7.
Definition at line 5189 of file matpackVII.cc.
References begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and x.
operator+=() [2/2]
Tensor7View & Tensor7View::operator+= (Numeric x)
Addition of scalar.
Definition at line 5135 of file matpackVII.cc.
References begin(), end(), and x.
operator-=() [1/2]
Tensor7View & Tensor7View::operator-= (const ConstTensor7View & x)
Element-vise subtraction of another Tensor7.
Definition at line 5207 of file matpackVII.cc.
References begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and x.
operator-=() [2/2]
Tensor7View & Tensor7View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 5144 of file matpackVII.cc.
References begin(), end(), and x.
operator/=() [1/2]
Tensor7View & Tensor7View::operator/= (const ConstTensor7View & x)
Element-vise division by another Tensor7.
Definition at line 5171 of file matpackVII.cc.
References begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and x.
operator/=() [2/2]
Tensor7View & Tensor7View::operator/= (Numeric x)
Division by scalar.
Definition at line 5126 of file matpackVII.cc.
References begin(), end(), and x.
operator=() [1/4]
Tensor7View & Tensor7View::operator= (const ConstTensor7View & m)
Assignment operator.
This copies the data from another Tensor7View to this Tensor7View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor7View by setting its range.
Definition at line 5056 of file matpackVII.cc.
References begin(), ConstTensor7View::begin(), copy(), ConstTensor7View::end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [2/4]
Tensor7View & Tensor7View::operator= (const Tensor7 & m)
Assignment from a Tensor7.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 5092 of file matpackVII.cc.
References begin(), copy(), end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [3/4]
Tensor7View & Tensor7View::operator= (const Tensor7View & m)
Assignment from Tensor7View to Tensor7View.
This is a tricky one. The problem is that since Tensor7View is derived from ConstTensor7View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 5075 of file matpackVII.cc.
References begin(), copy(), end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [4/4]
Tensor7View & Tensor7View::operator= (Numeric x)
Assigning a scalar to a Tensor7View will set all elements to this value.
Definition at line 5108 of file matpackVII.cc.
References begin(), copy(), end(), and x.
The documentation for this class was generated from the following files:
matpackVII.h
matpackVII.cc