ARTS: ARTS::Var::WorkspaceTessemNN Class Reference
ARTS::Var::WorkspaceTessemNN Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTessemNN () noexcept
WorkspaceTessemNN (std::size_t i, void *x) noexcept
~WorkspaceTessemNN () noexcept
WorkspaceTessemNN (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTessemNN & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::TessemNN
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1592 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTessemNN::type = Group::TessemNN private
Definition at line 1593 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTessemNN() [1/3]
ARTS::Var::WorkspaceTessemNN::WorkspaceTessemNN () inline noexcept
Definition at line 1597 of file autoarts.h.
WorkspaceTessemNN() [2/3]
ARTS::Var::WorkspaceTessemNN::WorkspaceTessemNN (std::size_t i, void * x) inline noexcept
Definition at line 1598 of file autoarts.h.
~WorkspaceTessemNN()
ARTS::Var::WorkspaceTessemNN::~WorkspaceTessemNN () inline noexcept
Definition at line 1599 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTessemNN() [3/3]
ARTS::Var::WorkspaceTessemNN::WorkspaceTessemNN (const type & val) inline noexcept
Definition at line 1600 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTessemNN::islast () const inline noexcept
Definition at line 1606 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::TessemNNReadAscii(), ARTS::Method::TessemNNReadAscii(), ARTS::AgendaMethod::TestTessem(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTessemNN().
isnull()
bool ARTS::Var::WorkspaceTessemNN::isnull () const inline noexcept
Definition at line 1605 of file autoarts.h.
References v.
Referenced by ~WorkspaceTessemNN().
name()
const Group::String& ARTS::Var::WorkspaceTessemNN::name () const inline noexcept
Definition at line 1607 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTessemNN& ARTS::Var::WorkspaceTessemNN::operator= (const type & t) inline noexcept
Definition at line 1603 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTessemNN::pos () const inline noexcept
Definition at line 1604 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::TessemNNReadAscii(), ARTS::AgendaMethod::TestTessem(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTessemNN::value () const inline noexcept
Definition at line 1602 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTessemNN::value () inline noexcept
Definition at line 1601 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::TestTessem(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTessemNN::p private
Definition at line 1594 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTessemNN::v private
Definition at line 1595 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTessemNN().
The documentation for this class was generated from the following file:
autoarts.h