ARTS: ARTS::Var::ArrayOfTensor7 Class Reference
ARTS::Var::ArrayOfTensor7 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTensor7 () noexcept
ArrayOfTensor7 (std::size_t i, void *x) noexcept
ArrayOfTensor7 (const Group::ArrayOfTensor7 &val) noexcept
~ArrayOfTensor7 () noexcept
Group::ArrayOfTensor7 & value () noexcept
const Group::ArrayOfTensor7 & value () const noexcept
ArrayOfTensor7 & operator= (const Group::ArrayOfTensor7 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfTensor7 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfTensor7 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2437 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTensor7() [1/3]
ARTS::Var::ArrayOfTensor7::ArrayOfTensor7 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2442 of file autoarts.h.
ArrayOfTensor7() [2/3]
ARTS::Var::ArrayOfTensor7::ArrayOfTensor7 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2445 of file autoarts.h.
ArrayOfTensor7() [3/3]
ARTS::Var::ArrayOfTensor7::ArrayOfTensor7 (const Group::ArrayOfTensor7 & val) inline noexcept
Construct from Group::ArrayOfTensor7. Leaves islast() true and isnull() false
Definition at line 2448 of file autoarts.h.
~ArrayOfTensor7()
ARTS::Var::ArrayOfTensor7::~ArrayOfTensor7 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2451 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTensor7::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2469 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfTensor7().
isnull()
bool ARTS::Var::ArrayOfTensor7::isnull () const inline noexcept
Return true if there is no data
Definition at line 2466 of file autoarts.h.
References v.
Referenced by ~ArrayOfTensor7().
name()
const Group::String& ARTS::Var::ArrayOfTensor7::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2472 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfTensor7& ARTS::Var::ArrayOfTensor7::operator= (const Group::ArrayOfTensor7 & t) inline noexcept
Set value from Group::ArrayOfTensor7. Works when isnull() is false
Definition at line 2460 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTensor7::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2463 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfTensor7& ARTS::Var::ArrayOfTensor7::value () const inline noexcept
Get value const-ref as Group::ArrayOfTensor7. Works when isnull() is false
Definition at line 2457 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfTensor7& ARTS::Var::ArrayOfTensor7::value () inline noexcept
Get value ref as Group::ArrayOfTensor7. Works when isnull() is false
Definition at line 2454 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfTensor7 & var) friend
Output to stream of internal variable
Definition at line 2475 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTensor7::p private
Definition at line 2438 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfTensor7* ARTS::Var::ArrayOfTensor7::v private
Definition at line 2439 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTensor7().
The documentation for this class was generated from the following file:
autoarts.h