ARTS: ComplexMatrix Class Reference
ComplexMatrix Class Reference
The ComplexMatrix class.
#include <complex.h>
Public Member Functions
ComplexMatrix ()=default
ComplexMatrix (Index r, Index c)
Constructor setting size.
ComplexMatrix (Index r, Index c, Complex fill)
Constructor setting size and filling with constant value.
ComplexMatrix (Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
ComplexMatrix (const ConstComplexMatrixView &v)
Copy constructor from MatrixView.
ComplexMatrix (const ComplexMatrix &v)
Copy constructor from Matrix.
ComplexMatrix & operator= (ComplexMatrix x)
Assignment operator from another matrix.
ComplexMatrix & operator= (Complex x)
Assignment operator from scalar.
ComplexMatrix & operator= (const ConstComplexVectorView &v)
Assignment from a vector.
ComplexMatrix & inv (const lapack_help::Inverse< Complex > &help=lapack_help::Inverse< Complex >{0})
void resize (Index r, Index c)
Resize function.
virtual ~ComplexMatrix ()
Destructor for Matrix.
Complex * get_raw_data ()
Public Member Functions inherited from ComplexMatrixView
constexpr ComplexMatrixView (const ComplexMatrixView &)=default
Complex & operator() (Index r, Index c)
Plain index operator.
Complex & get (Index r, Index c)
Get element implementation without assertions.
Numeric & get_real (Index r, Index c)
Get element implementation without assertions.
Numeric & get_imag (Index r, Index c)
Get element implementation without assertions.
MatrixView real ()
Get a view of the real part of the matrix.
MatrixView imag ()
Get a view of the imaginary parts of the matrix.
ComplexMatrixView operator() (const Range &r, const Range &c)
Index operator for subrange.
ComplexVectorView operator() (const Range &r, Index c)
Index operator returning a column as an object of type ComplexVectorView.
ComplexVectorView operator() (Index r, const Range &c)
Index operator returning a row as an object of type ComplexVectorView.
ComplexIterator2D begin ()
Return iterator to first row.
ComplexIterator2D end ()
Return iterator behind last row.
ComplexVectorView diagonal ()
ComplexMatrix diagonal as vector.
ComplexMatrixView & operator= (const ConstComplexMatrixView &v)
Assignment operator.
ComplexMatrixView & operator= (const ComplexMatrixView &v)
Assignment from ComplexMatrixView to ComplexMatrixView.
ComplexMatrixView & operator= (const ComplexMatrix &v)
Assignment from a ComplexMatrix.
ComplexMatrixView & operator= (const ConstComplexVectorView &v)
Assignment from a vector.
ComplexMatrixView & operator= (Complex x)
Assigning a scalar to a MatrixView will set all elements to this value.
ComplexMatrixView & operator*= (Complex x)
Multiplication by scalar.
ComplexMatrixView & operator/= (Complex x)
Division by scalar.
ComplexMatrixView & operator+= (Complex x)
Addition of scalar.
ComplexMatrixView & operator-= (Complex x)
Subtraction of scalar.
ComplexMatrixView & operator*= (Numeric x)
Multiplication by scalar.
ComplexMatrixView & operator/= (Numeric x)
Division by scalar.
ComplexMatrixView & operator+= (Numeric x)
Addition of scalar.
ComplexMatrixView & operator-= (Numeric x)
Subtraction of scalar.
ComplexMatrixView & operator*= (const ConstComplexMatrixView &x)
Element-vise multiplication by another Matrix.
ComplexMatrixView & operator/= (const ConstComplexMatrixView &x)
Element-vise division by another Matrix.
ComplexMatrixView & operator+= (const ConstComplexMatrixView &x)
Element-vise addition of another Matrix.
ComplexMatrixView & operator-= (const ConstComplexMatrixView &x)
Element-vise subtraction of another Matrix.
ComplexMatrixView & operator*= (const ConstMatrixView &x)
Element-vise multiplication by another Matrix.
ComplexMatrixView & operator/= (const ConstMatrixView &x)
Element-vise division by another Matrix.
ComplexMatrixView & operator+= (const ConstMatrixView &x)
Element-vise addition of another Matrix.
ComplexMatrixView & operator-= (const ConstMatrixView &x)
Element-vise subtraction of another Matrix.
ComplexMatrixView & operator*= (const ConstComplexVectorView &x)
ComplexMatrixView & operator/= (const ConstComplexVectorView &x)
ComplexMatrixView & operator+= (const ConstComplexVectorView &x)
ComplexMatrixView & operator-= (const ConstComplexVectorView &x)
const Complex * get_c_array () const
Conversion to plain C-array.
Complex * get_c_array ()
Conversion to plain C-array.
virtual ~ComplexMatrixView ()=default
Destructor.
ConstComplexIterator2D begin () const
Return const iterator to first row.
ConstComplexIterator2D end () const
Return const iterator behind last row.
Complex get (Index r, Index c) const
Get element implementation without assertions.
Numeric get_imag (Index r, Index c) const
Get element implementation without assertions.
Numeric get_real (Index r, Index c) const
Get element implementation without assertions.
ConstMatrixView imag () const
Get a view of the imaginary part of the matrix.
ConstMatrixView real () const
Get a view of the real part of the matrix.
ConstComplexVectorView diagonal () const
ComplexMatrix diagonal as vector.
Public Member Functions inherited from ConstComplexMatrixView
constexpr ConstComplexMatrixView (const ConstComplexMatrixView &)=default
constexpr ConstComplexMatrixView (ConstComplexMatrixView &&)=default
ConstComplexMatrixView & operator= (const ConstComplexMatrixView &)=default
ConstComplexMatrixView & operator= (ConstComplexMatrixView &&)=default
bool empty () const
Index nrows () const
Index ncols () const
Complex operator() (Index r, Index c) const
Plain const index operator.
Complex get (Index r, Index c) const
Get element implementation without assertions.
Numeric get_real (Index r, Index c) const
Get element implementation without assertions.
Numeric get_imag (Index r, Index c) const
Get element implementation without assertions.
ConstMatrixView real () const
Get a view of the real part of the matrix.
ConstMatrixView imag () const
Get a view of the imaginary part of the matrix.
Index get_column_extent () const
Get the extent of the underlying data.
ConstComplexMatrixView operator() (const Range &r, const Range &c) const
Returns true if variable size is zero.
ConstComplexVectorView operator() (const Range &r, Index c) const
Const index operator returning a column as an object of type C onstComplex*VectorView.
ConstComplexVectorView operator() (Index r, const Range &c) const
Const index operator returning a row as an object of type C onstComplex*VectorView.
ConstComplexIterator2D begin () const
Return const iterator to first row.
ConstComplexIterator2D end () const
Return const iterator behind last row.
ConstComplexVectorView diagonal () const
ComplexMatrix diagonal as vector.
virtual ~ConstComplexMatrixView ()=default
Destructor.
Friends
void swap (ComplexMatrix &m1, ComplexMatrix &m2)
Swaps two objects.
Additional Inherited Members
Public Types inherited from ComplexMatrixView
typedef ComplexIterator2D iterator
Public Types inherited from ConstComplexMatrixView
typedef ConstComplexIterator2D const_iterator
Protected Member Functions inherited from ComplexMatrixView
ComplexMatrixView ()
Default constructor.
ComplexMatrixView (Complex *data, const Range &r, const Range &c)
Explicit constructor.
ComplexMatrixView (Complex *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstComplexMatrixView
ConstComplexMatrixView ()=default
ConstComplexMatrixView (Complex *data, const Range &r, const Range &c)
Explicit constructor.
ConstComplexMatrixView (Complex *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes inherited from ConstComplexMatrixView
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Complex * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The ComplexMatrix class.
This is a ComplexMatrixView that also allocates storage automatically, and deallocates it when it is destroyed. We take * all the functionality from ComplexMatrixView. Additionally defined here are:
Constructors and destructor.
Assignment operator from scalar.
Resize function.
Definition at line 858 of file complex.h.
Constructor & Destructor Documentation
ComplexMatrix() [1/6]
ComplexMatrix::ComplexMatrix () default
ComplexMatrix() [2/6]
ComplexMatrix::ComplexMatrix (Index r, Index c)
Constructor setting size.
This constructor has to set the stride in the row range correctly!
Definition at line 1350 of file complex.cc.
ComplexMatrix() [3/6]
ComplexMatrix::ComplexMatrix (Index r, Index c, Complex fill)
Constructor setting size and filling with constant value.
Definition at line 1356 of file complex.cc.
ComplexMatrix() [4/6]
ComplexMatrix::ComplexMatrix (Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Definition at line 1365 of file complex.cc.
ComplexMatrix() [5/6]
ComplexMatrix::ComplexMatrix (const ConstComplexMatrixView & m)
Copy constructor from MatrixView.
This automatically sets the size and copies the data.
Definition at line 1375 of file complex.cc.
References ComplexMatrixView::begin(), ConstComplexMatrixView::begin(), copy(), and ConstComplexMatrixView::end().
ComplexMatrix() [6/6]
ComplexMatrix::ComplexMatrix (const ComplexMatrix & m)
Copy constructor from Matrix.
This automatically sets the size and copies the data.
Definition at line 1384 of file complex.cc.
References ComplexMatrixView::begin(), copy(), and ComplexMatrixView::end().
~ComplexMatrix()
ComplexMatrix::~ComplexMatrix () virtual
Destructor for Matrix.
This is important, since Matrix uses new to allocate storage.
Definition at line 1482 of file complex.cc.
References ConstComplexMatrixView::mdata.
Member Function Documentation
get_raw_data()
Complex* ComplexMatrix::get_raw_data () inline
Definition at line 885 of file complex.h.
References ConstComplexMatrixView::mdata.
inv()
ComplexMatrix & ComplexMatrix::inv (const lapack_help::Inverse< Complex > & help = lapack_help::Inverse<Complex>{0})
Definition at line 1488 of file complex.cc.
References lapack_help::Inverse< T >::ipivdata(), lapack_help::Inverse< T >::lsize(), ConstComplexMatrixView::mdata, ConstComplexMatrixView::ncols(), ConstComplexMatrixView::nrows(), lapack_help::Inverse< T >::resize_if_smaller(), lapack_help::Inverse< T >::size(), lapack_help::Inverse< T >::workdata(), lapack::zgetrf_(), and lapack::zgetri_().
operator=() [1/3]
ComplexMatrix & ComplexMatrix::operator= (Complex x)
Assignment operator from scalar.
Assignment operators also seem to be not inherited.
Definition at line 1427 of file complex.cc.
References ComplexMatrixView::begin(), copy(), ComplexMatrixView::end(), and ARTS::Var::x().
operator=() [2/3]
ComplexMatrix & ComplexMatrix::operator= (ComplexMatrix m)
Assignment operator from another matrix.
While dimensions of MatrixViews can not be adjusted, dimensions of matrices can be adjusted. Hence, the behavior of the assignment operator is different.
In this case the size of the target is automatically adjusted. This is important, so that structures containing matrices are copied correctly.
This is a deviation from the old ARTS paradigm that sizes must match exactly before copying!
Note: It is sufficient to have only this one version of the assignment (Matrix = Matrix). It implicitly covers the cases Matrix=MatrixView, etc, because there is a default constructor for Matrix from MatrixView. (See C++ Primer Plus, page 571ff.)
Parameters
m The other matrix to assign to this one.
Returns
This matrix, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 1420 of file complex.cc.
References swap.
operator=() [3/3]
ComplexMatrix & ComplexMatrix::operator= (const ConstComplexVectorView & v)
Assignment from a vector.
This copies the data from a VectorView to this MatrixView.
The dimension is adjusted automatically.
Parameters
v The vector to assign to this matrix.
Returns
This matrix, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 1445 of file complex.cc.
References ComplexMatrixView::begin(), ConstComplexMatrixView::begin(), copy(), ConstComplexMatrixView::end(), ConstComplexVectorView::nelem(), and resize().
resize()
void ComplexMatrix::resize (Index r, Index c)
Resize function.
If the size is already correct this function does nothing. All data is lost after resizing! The new Matrix is not initialized, so it will contain random values.
Definition at line 1455 of file complex.cc.
Referenced by operator=().
Friends And Related Function Documentation
swap
void swap (ComplexMatrix & m1, ComplexMatrix & m2) friend
Swaps two objects.
Definition at line 1474 of file complex.cc.
Referenced by operator=().
The documentation for this class was generated from the following files:
complex.h
complex.cc