ARTS: ARTS::Var::ArrayOfRadiationVector Class Reference
ARTS::Var::ArrayOfRadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfRadiationVector () noexcept
ArrayOfRadiationVector (std::size_t i, void *x) noexcept
ArrayOfRadiationVector (const Group::ArrayOfRadiationVector &val) noexcept
~ArrayOfRadiationVector () noexcept
Group::ArrayOfRadiationVector & value () noexcept
const Group::ArrayOfRadiationVector & value () const noexcept
ArrayOfRadiationVector & operator= (const Group::ArrayOfRadiationVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfRadiationVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfRadiationVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1873 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfRadiationVector() [1/3]
ARTS::Var::ArrayOfRadiationVector::ArrayOfRadiationVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1878 of file autoarts.h.
ArrayOfRadiationVector() [2/3]
ARTS::Var::ArrayOfRadiationVector::ArrayOfRadiationVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1881 of file autoarts.h.
ArrayOfRadiationVector() [3/3]
ARTS::Var::ArrayOfRadiationVector::ArrayOfRadiationVector (const Group::ArrayOfRadiationVector & val) inline noexcept
Construct from Group::ArrayOfRadiationVector. Leaves islast() true and isnull() false
Definition at line 1884 of file autoarts.h.
~ArrayOfRadiationVector()
ARTS::Var::ArrayOfRadiationVector::~ArrayOfRadiationVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1887 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfRadiationVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1905 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfRadiationVector().
isnull()
bool ARTS::Var::ArrayOfRadiationVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 1902 of file autoarts.h.
References v.
Referenced by ~ArrayOfRadiationVector().
name()
const Group::String& ARTS::Var::ArrayOfRadiationVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1908 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfRadiationVector& ARTS::Var::ArrayOfRadiationVector::operator= (const Group::ArrayOfRadiationVector & t) inline noexcept
Set value from Group::ArrayOfRadiationVector. Works when isnull() is false
Definition at line 1896 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfRadiationVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1899 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfRadiationVector& ARTS::Var::ArrayOfRadiationVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfRadiationVector. Works when isnull() is false
Definition at line 1893 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfRadiationVector& ARTS::Var::ArrayOfRadiationVector::value () inline noexcept
Get value ref as Group::ArrayOfRadiationVector. Works when isnull() is false
Definition at line 1890 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfRadiationVector & var) friend
Output to stream of internal variable
Definition at line 1911 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfRadiationVector::p private
Definition at line 1874 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfRadiationVector* ARTS::Var::ArrayOfRadiationVector::v private
Definition at line 1875 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfRadiationVector().
The documentation for this class was generated from the following file:
autoarts.h