ARTS: ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfAbsorptionLines () noexcept
WorkspaceArrayOfArrayOfAbsorptionLines (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfAbsorptionLines () noexcept
WorkspaceArrayOfArrayOfAbsorptionLines (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfAbsorptionLines & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfAbsorptionLines
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 188 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::type = Group::ArrayOfArrayOfAbsorptionLines private
Definition at line 189 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfAbsorptionLines() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::WorkspaceArrayOfArrayOfAbsorptionLines () inline noexcept
Definition at line 193 of file autoarts.h.
WorkspaceArrayOfArrayOfAbsorptionLines() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::WorkspaceArrayOfArrayOfAbsorptionLines (std::size_t i, void * x) inline noexcept
Definition at line 194 of file autoarts.h.
~WorkspaceArrayOfArrayOfAbsorptionLines()
ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::~WorkspaceArrayOfArrayOfAbsorptionLines () inline noexcept
Definition at line 195 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfAbsorptionLines() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::WorkspaceArrayOfArrayOfAbsorptionLines (const type & val) inline noexcept
Definition at line 196 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::islast () const inline noexcept
Definition at line 202 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfAbsorptionLines().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::isnull () const inline noexcept
Definition at line 201 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfAbsorptionLines().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::name () const inline noexcept
Definition at line 203 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfAbsorptionLines& ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::operator= (const type & t) inline noexcept
Definition at line 199 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::pos () const inline noexcept
Definition at line 200 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::value () const inline noexcept
Definition at line 198 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::value () inline noexcept
Definition at line 197 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::p private
Definition at line 190 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfAbsorptionLines::v private
Definition at line 191 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfAbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h