ARTS: ARTS::Var::WorkspaceAgenda Class Reference
ARTS::Var::WorkspaceAgenda Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceAgenda () noexcept
WorkspaceAgenda (std::size_t i, void *x) noexcept
~WorkspaceAgenda () noexcept
WorkspaceAgenda (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceAgenda & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Agenda
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 134 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceAgenda::type = Group::Agenda private
Definition at line 135 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceAgenda() [1/3]
ARTS::Var::WorkspaceAgenda::WorkspaceAgenda () inline noexcept
Definition at line 139 of file autoarts.h.
WorkspaceAgenda() [2/3]
ARTS::Var::WorkspaceAgenda::WorkspaceAgenda (std::size_t i, void * x) inline noexcept
Definition at line 140 of file autoarts.h.
~WorkspaceAgenda()
ARTS::Var::WorkspaceAgenda::~WorkspaceAgenda () inline noexcept
Definition at line 141 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceAgenda() [3/3]
ARTS::Var::WorkspaceAgenda::WorkspaceAgenda (const type & val) inline noexcept
Definition at line 142 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceAgenda::islast () const inline noexcept
Definition at line 148 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::AgendaExecute(), ARTS::AgendaMethod::AgendaExecuteExclusive(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceAgenda().
isnull()
bool ARTS::Var::WorkspaceAgenda::isnull () const inline noexcept
Definition at line 147 of file autoarts.h.
References v.
Referenced by ~WorkspaceAgenda().
name()
const Group::String& ARTS::Var::WorkspaceAgenda::name () const inline noexcept
Definition at line 149 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), iySurfaceRtpropAgenda(), and iySurfaceRtpropCalc().
operator=()
WorkspaceAgenda& ARTS::Var::WorkspaceAgenda::operator= (const type & t) inline noexcept
Definition at line 145 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceAgenda::pos () const inline noexcept
Definition at line 146 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::AgendaExecute(), ARTS::AgendaMethod::AgendaExecuteExclusive(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceAgenda::value () const inline noexcept
Definition at line 144 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceAgenda::value () inline noexcept
Definition at line 143 of file autoarts.h.
References v.
Referenced by ARTS::AgendaDefine::abs_xsec_agenda(), ARTS::Method::AgendaExecute(), ARTS::Method::AgendaExecuteExclusive(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::AgendaDefine::dobatch_calc_agenda(), ARTS::AgendaDefine::doit_conv_test_agenda(), ARTS::AgendaDefine::doit_mono_agenda(), ARTS::AgendaDefine::doit_rte_agenda(), ARTS::AgendaDefine::doit_scat_field_agenda(), ARTS::AgendaDefine::forloop_agenda(), ARTS::AgendaDefine::g0_agenda(), ARTS::AgendaDefine::geo_pos_agenda(), ARTS::Method::Ignore(), ARTS::AgendaDefine::inversion_iterate_agenda(), ARTS::AgendaDefine::iy_cloudbox_agenda(), ARTS::AgendaDefine::iy_independent_beam_approx_agenda(), ARTS::AgendaDefine::iy_loop_freqs_agenda(), ARTS::AgendaDefine::iy_main_agenda(), ARTS::AgendaDefine::iy_space_agenda(), ARTS::AgendaDefine::iy_surface_agenda(), ARTS::AgendaDefine::iy_transmitter_agenda(), ARTS::AgendaDefine::jacobian_agenda(), ARTS::AgendaDefine::main_agenda(), ARTS::AgendaDefine::met_profile_calc_agenda(), operator=(), ARTS::AgendaDefine::pha_mat_spt_agenda(), ARTS::AgendaDefine::ppath_agenda(), ARTS::AgendaDefine::ppath_step_agenda(), ARTS::AgendaDefine::propmat_clearsky_agenda(), ARTS::AgendaDefine::refr_index_air_agenda(), ARTS::AgendaDefine::sensor_response_agenda(), ARTS::AgendaDefine::spt_calc_agenda(), ARTS::AgendaDefine::surface_rtprop_agenda(), ARTS::AgendaDefine::surface_rtprop_sub_agenda(), ARTS::AgendaDefine::test_agenda(), ARTS::Method::Touch(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::AgendaDefine::water_p_eq_agenda(), and ARTS::AgendaDefine::ybatch_calc_agenda().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceAgenda::p private
Definition at line 136 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceAgenda::v private
Definition at line 137 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceAgenda().
The documentation for this class was generated from the following file:
autoarts.h