ARTS: ARTS::Var::ArrayOfArrayOfIndex Class Reference
ARTS::Var::ArrayOfArrayOfIndex Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfIndex () noexcept
ArrayOfArrayOfIndex (std::size_t i, void *x) noexcept
ArrayOfArrayOfIndex (const Group::ArrayOfArrayOfIndex &val) noexcept
~ArrayOfArrayOfIndex () noexcept
Group::ArrayOfArrayOfIndex & value () noexcept
const Group::ArrayOfArrayOfIndex & value () const noexcept
ArrayOfArrayOfIndex & operator= (const Group::ArrayOfArrayOfIndex &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfIndex * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfIndex &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 700 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfIndex() [1/3]
ARTS::Var::ArrayOfArrayOfIndex::ArrayOfArrayOfIndex () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 705 of file autoarts.h.
ArrayOfArrayOfIndex() [2/3]
ARTS::Var::ArrayOfArrayOfIndex::ArrayOfArrayOfIndex (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 708 of file autoarts.h.
ArrayOfArrayOfIndex() [3/3]
ARTS::Var::ArrayOfArrayOfIndex::ArrayOfArrayOfIndex (const Group::ArrayOfArrayOfIndex & val) inline noexcept
Construct from Group::ArrayOfArrayOfIndex. Leaves islast() true and isnull() false
Definition at line 711 of file autoarts.h.
~ArrayOfArrayOfIndex()
ARTS::Var::ArrayOfArrayOfIndex::~ArrayOfArrayOfIndex () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 714 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfIndex::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 732 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfArrayOfIndex().
isnull()
bool ARTS::Var::ArrayOfArrayOfIndex::isnull () const inline noexcept
Return true if there is no data
Definition at line 729 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfIndex().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfIndex::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 735 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfIndex& ARTS::Var::ArrayOfArrayOfIndex::operator= (const Group::ArrayOfArrayOfIndex & t) inline noexcept
Set value from Group::ArrayOfArrayOfIndex. Works when isnull() is false
Definition at line 723 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfIndex::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 726 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfArrayOfIndex& ARTS::Var::ArrayOfArrayOfIndex::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfIndex. Works when isnull() is false
Definition at line 720 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfIndex& ARTS::Var::ArrayOfArrayOfIndex::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfIndex. Works when isnull() is false
Definition at line 717 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfIndex & var) friend
Output to stream of internal variable
Definition at line 738 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfIndex::p private
Definition at line 701 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfIndex* ARTS::Var::ArrayOfArrayOfIndex::v private
Definition at line 702 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfIndex().
The documentation for this class was generated from the following file:
autoarts.h