ARTS: ARTS::Var::GriddedField1 Class Reference
ARTS::Var::GriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField1 () noexcept
GriddedField1 (std::size_t i, void *x) noexcept
GriddedField1 (const Group::GriddedField1 &val) noexcept
~GriddedField1 () noexcept
Group::GriddedField1 & value () noexcept
const Group::GriddedField1 & value () const noexcept
GriddedField1 & operator= (const Group::GriddedField1 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField1 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField1 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2961 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField1() [1/3]
ARTS::Var::GriddedField1::GriddedField1 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2966 of file autoarts.h.
GriddedField1() [2/3]
ARTS::Var::GriddedField1::GriddedField1 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2969 of file autoarts.h.
GriddedField1() [3/3]
ARTS::Var::GriddedField1::GriddedField1 (const Group::GriddedField1 & val) inline noexcept
Construct from Group::GriddedField1. Leaves islast() true and isnull() false
Definition at line 2972 of file autoarts.h.
~GriddedField1()
ARTS::Var::GriddedField1::~GriddedField1 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2975 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField1::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2993 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~GriddedField1().
isnull()
bool ARTS::Var::GriddedField1::isnull () const inline noexcept
Return true if there is no data
Definition at line 2990 of file autoarts.h.
References v.
Referenced by ~GriddedField1().
name()
const Group::String& ARTS::Var::GriddedField1::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2996 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField1& ARTS::Var::GriddedField1::operator= (const Group::GriddedField1 & t) inline noexcept
Set value from Group::GriddedField1. Works when isnull() is false
Definition at line 2984 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField1::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2987 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::GriddedField1& ARTS::Var::GriddedField1::value () const inline noexcept
Get value const-ref as Group::GriddedField1. Works when isnull() is false
Definition at line 2981 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField1& ARTS::Var::GriddedField1::value () inline noexcept
Get value ref as Group::GriddedField1. Works when isnull() is false
Definition at line 2978 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField1 & var) friend
Output to stream of internal variable
Definition at line 2999 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField1::p private
Definition at line 2962 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField1* ARTS::Var::GriddedField1::v private
Definition at line 2963 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField1().
The documentation for this class was generated from the following file:
autoarts.h