ARTS: ARTS::Var::RadiationVector Class Reference
ARTS::Var::RadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
RadiationVector () noexcept
RadiationVector (std::size_t i, void *x) noexcept
RadiationVector (const Group::RadiationVector &val) noexcept
~RadiationVector () noexcept
Group::RadiationVector & value () noexcept
const Group::RadiationVector & value () const noexcept
RadiationVector & operator= (const Group::RadiationVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::RadiationVector * v
Friends
std::ostream & operator<< (std::ostream &os, const RadiationVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3610 of file autoarts.h.
Constructor & Destructor Documentation
RadiationVector() [1/3]
ARTS::Var::RadiationVector::RadiationVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3615 of file autoarts.h.
RadiationVector() [2/3]
ARTS::Var::RadiationVector::RadiationVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3618 of file autoarts.h.
RadiationVector() [3/3]
ARTS::Var::RadiationVector::RadiationVector (const Group::RadiationVector & val) inline noexcept
Construct from Group::RadiationVector. Leaves islast() true and isnull() false
Definition at line 3621 of file autoarts.h.
~RadiationVector()
ARTS::Var::RadiationVector::~RadiationVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3624 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::RadiationVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3642 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~RadiationVector().
isnull()
bool ARTS::Var::RadiationVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 3639 of file autoarts.h.
References v.
Referenced by ~RadiationVector().
name()
const Group::String& ARTS::Var::RadiationVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3645 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
RadiationVector& ARTS::Var::RadiationVector::operator= (const Group::RadiationVector & t) inline noexcept
Set value from Group::RadiationVector. Works when isnull() is false
Definition at line 3633 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::RadiationVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3636 of file autoarts.h.
References p.
value() [1/2]
const Group::RadiationVector& ARTS::Var::RadiationVector::value () const inline noexcept
Get value const-ref as Group::RadiationVector. Works when isnull() is false
Definition at line 3630 of file autoarts.h.
References v.
value() [2/2]
Group::RadiationVector& ARTS::Var::RadiationVector::value () inline noexcept
Get value ref as Group::RadiationVector. Works when isnull() is false
Definition at line 3627 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const RadiationVector & var) friend
Output to stream of internal variable
Definition at line 3648 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::RadiationVector::p private
Definition at line 3611 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::RadiationVector* ARTS::Var::RadiationVector::v private
Definition at line 3612 of file autoarts.h.
Referenced by isnull(), value(), and ~RadiationVector().
The documentation for this class was generated from the following file:
autoarts.h