ARTS: ARTS::Var::Vector Class Reference
ARTS::Var::Vector Class Reference
#include <autoarts.h>
Public Member Functions
Vector () noexcept
Vector (std::size_t i, void *x) noexcept
Vector (const Group::Vector &val) noexcept
~Vector () noexcept
Group::Vector & value () noexcept
const Group::Vector & value () const noexcept
Vector & operator= (const Group::Vector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Vector * v
Friends
std::ostream & operator<< (std::ostream &os, const Vector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4553 of file autoarts.h.
Constructor & Destructor Documentation
Vector() [1/3]
ARTS::Var::Vector::Vector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4558 of file autoarts.h.
Vector() [2/3]
ARTS::Var::Vector::Vector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4561 of file autoarts.h.
Vector() [3/3]
ARTS::Var::Vector::Vector (const Group::Vector & val) inline noexcept
Construct from Group::Vector. Leaves islast() true and isnull() false
Definition at line 4564 of file autoarts.h.
~Vector()
ARTS::Var::Vector::~Vector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4567 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Vector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4585 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Agenda::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetZeemanCoefficients(), ARTS::Agenda::Method::AddZaAa(), ARTS::Agenda::Method::cloudbox_field_monoSetConst(), ARTS::Agenda::Method::cloudbox_fieldSetConst(), ARTS::Agenda::Method::complex_refr_indexIceMatzler06(), ARTS::Agenda::Method::complex_refr_indexIceWarren84(), ARTS::Agenda::Method::complex_refr_indexWaterLiebe93(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Agenda::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Agenda::Method::covmatDiagonal(), ARTS::Agenda::Method::DiffZaAa(), ARTS::Method::EnergyLevelMapSet(), ARTS::Agenda::Method::EnergyLevelMapSet(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Agenda::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddScatSpecies(), ARTS::Agenda::Method::jacobianAddSpecialSpecies(), ARTS::Agenda::Method::jacobianAddSurfaceQuantity(), ARTS::Agenda::Method::jacobianFromTwoY(), ARTS::Agenda::Method::jacobianSetAffineTransformation(), ARTS::Agenda::Method::Matrix2ColFromVectors(), ARTS::Agenda::Method::Matrix2RowFromVectors(), ARTS::Agenda::Method::Matrix3ColFromVectors(), ARTS::Agenda::Method::Matrix3RowFromVectors(), ARTS::Agenda::Method::MatrixCBR(), ARTS::Agenda::Method::MatrixMatrixMultiply(), ARTS::Agenda::Method::MatrixPlanck(), ARTS::Agenda::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Agenda::Method::MatrixVectorMultiply(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Agenda::Method::p_gridRefine(), ARTS::Method::PFromZSimple(), ARTS::Agenda::Method::PFromZSimple(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::retrievalAddScatSpecies(), ARTS::Agenda::Method::retrievalAddSpecialSpecies(), ARTS::Agenda::Method::retrievalAddSurfaceQuantity(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Agenda::Method::SurfaceFlatScalarReflectivity(), ARTS::Method::TangentPointExtract(), ARTS::Agenda::Method::TangentPointExtract(), ARTS::Method::telsemAtlasLookup(), ARTS::Agenda::Method::telsemAtlasLookup(), ARTS::Method::TestTessem(), ARTS::Agenda::Method::TestTessem(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Agenda::Method::transmittanceFromIy_aux(), ARTS::Agenda::Method::Trapz(), ARTS::Method::VectorAddScalar(), ARTS::Agenda::Method::VectorAddScalar(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Agenda::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Agenda::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Agenda::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Agenda::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Agenda::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Agenda::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Agenda::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Agenda::Method::VectorNLogSpace(), ARTS::Method::VectorPower(), ARTS::Agenda::Method::VectorPower(), ARTS::Method::VectorScale(), ARTS::Agenda::Method::VectorScale(), ARTS::Method::VectorSet(), ARTS::Agenda::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Agenda::Method::VectorSetConstant(), ARTS::Method::VectorVectorMultiply(), ARTS::Agenda::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Agenda::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Agenda::Method::VectorZtanToZaRefr1D(), ARTS::Agenda::Method::vmr_fieldSetAllConstant(), ARTS::Method::ZFromPSimple(), ARTS::Agenda::Method::ZFromPSimple(), and ~Vector().
isnull()
bool ARTS::Var::Vector::isnull () const inline noexcept
Return true if there is no data
Definition at line 4582 of file autoarts.h.
References v.
Referenced by ~Vector().
name()
const Group::String& ARTS::Var::Vector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4588 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), Print(), print_agenda_methods(), print_full_methods(), print_gin_methods(), and ARTS::Method::ReadNetCDF().
operator=()
Vector& ARTS::Var::Vector::operator= (const Group::Vector & t) inline noexcept
Set value from Group::Vector. Works when isnull() is false
Definition at line 4576 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Vector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4579 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Agenda::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetZeemanCoefficients(), ARTS::Agenda::Method::AddZaAa(), ARTS::Agenda::Method::cloudbox_field_monoSetConst(), ARTS::Agenda::Method::cloudbox_fieldSetConst(), ARTS::Agenda::Method::complex_refr_indexIceMatzler06(), ARTS::Agenda::Method::complex_refr_indexIceWarren84(), ARTS::Agenda::Method::complex_refr_indexWaterLiebe93(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Agenda::Method::covmatDiagonal(), ARTS::Agenda::Method::DiffZaAa(), ARTS::Agenda::Method::EnergyLevelMapSet(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Agenda::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Agenda::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::jacobianAddScatSpecies(), ARTS::Agenda::Method::jacobianAddSpecialSpecies(), ARTS::Agenda::Method::jacobianAddSurfaceQuantity(), ARTS::Agenda::Method::jacobianFromTwoY(), ARTS::Agenda::Method::jacobianSetAffineTransformation(), ARTS::Agenda::Method::Matrix2ColFromVectors(), ARTS::Agenda::Method::Matrix2RowFromVectors(), ARTS::Agenda::Method::Matrix3ColFromVectors(), ARTS::Agenda::Method::Matrix3RowFromVectors(), ARTS::Agenda::Method::MatrixCBR(), ARTS::Agenda::Method::MatrixMatrixMultiply(), ARTS::Agenda::Method::MatrixPlanck(), ARTS::Agenda::Method::MatrixUnitIntensity(), ARTS::Agenda::Method::MatrixVectorMultiply(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Agenda::Method::p_gridRefine(), ARTS::Agenda::Method::PFromZSimple(), Print(), print_agenda_methods(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::retrievalAddScatSpecies(), ARTS::Agenda::Method::retrievalAddSpecialSpecies(), ARTS::Agenda::Method::retrievalAddSurfaceQuantity(), ARTS::Agenda::Method::Select(), ARTS::Agenda::Method::SurfaceFlatScalarReflectivity(), ARTS::Agenda::Method::TangentPointExtract(), ARTS::Agenda::Method::telsemAtlasLookup(), ARTS::Agenda::Method::TestTessem(), ARTS::Agenda::Method::Touch(), ARTS::Agenda::Method::transmittanceFromIy_aux(), ARTS::Agenda::Method::Trapz(), ARTS::Agenda::Method::VectorAddScalar(), ARTS::Agenda::Method::VectorExtractFromMatrix(), ARTS::Agenda::Method::VectorFlip(), ARTS::Agenda::Method::VectorInsertGridPoints(), ARTS::Agenda::Method::VectorLinSpace(), ARTS::Agenda::Method::VectorLogSpace(), ARTS::Agenda::Method::VectorMatrixMultiply(), ARTS::Agenda::Method::VectorNLinSpace(), ARTS::Agenda::Method::VectorNLogSpace(), ARTS::Agenda::Method::VectorPower(), ARTS::Agenda::Method::VectorScale(), ARTS::Agenda::Method::VectorSet(), ARTS::Agenda::Method::VectorSetConstant(), ARTS::Agenda::Method::VectorVectorMultiply(), ARTS::Agenda::Method::VectorZtanToZa1D(), ARTS::Agenda::Method::VectorZtanToZaRefr1D(), ARTS::Agenda::Method::vmr_fieldSetAllConstant(), and ARTS::Agenda::Method::ZFromPSimple().
value() [1/2]
const Group::Vector& ARTS::Var::Vector::value () const inline noexcept
Get value const-ref as Group::Vector. Works when isnull() is false
Definition at line 4573 of file autoarts.h.
References v.
value() [2/2]
Group::Vector& ARTS::Var::Vector::value () inline noexcept
Get value ref as Group::Vector. Works when isnull() is false
Definition at line 4570 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetZeemanCoefficients(), ARTS::Method::AddZaAa(), ARTS::Method::cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_fieldSetConst(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), ARTS::Method::complex_refr_indexWaterLiebe93(), ARTS::Method::Copy(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmatDiagonal(), ARTS::Method::DiffZaAa(), ARTS::Method::EnergyLevelMapSet(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::Ignore(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::NumericFromVector(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::PFromZSimple(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::Select(), ARTS::Method::SurfaceFlatScalarReflectivity(), ARTS::Method::TangentPointExtract(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::TestTessem(), ARTS::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::Trapz(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorPower(), ARTS::Method::VectorScale(), ARTS::Method::VectorSet(), ARTS::Agenda::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Method::vmr_fieldSetAllConstant(), and ARTS::Method::ZFromPSimple().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Vector & var) friend
Output to stream of internal variable
Definition at line 4591 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Vector::p private
Definition at line 4554 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Vector* ARTS::Var::Vector::v private
Definition at line 4555 of file autoarts.h.
Referenced by isnull(), value(), and ~Vector().
The documentation for this class was generated from the following file:
autoarts.h