ARTS: ComplexVectorView Class Reference
ComplexVectorView Class Reference
The ComplexVectorView class.
#include <complex.h>
Public Types
typedef ComplexIterator1D iterator
Public Types inherited from ConstComplexVectorView
typedef ConstComplexIterator1D const_iterator
Public Member Functions
constexpr ComplexVectorView (const ComplexVectorView &)=default
ComplexVectorView (const ComplexVector &)
Bail out immediately if somebody tries to create a ComplexVectorView from a const Complex*Vector.
ComplexVectorView (ComplexVector &v)
Create ComplexVectorView from a ComplexVector.
Complex & operator[] (Index n)
Plain Index operator.
Complex & get (Index n)
Get element implementation without assertions.
Numeric & get_real (Index n)
Get element implementation without assertions.
Numeric & get_imag (Index n)
Get element implementation without assertions.
VectorView real ()
Get a view of the real part of the vector.
VectorView imag ()
Get a view of the imaginary part of the vector.
ComplexVectorView operator[] (const Range &r)
Index operator for subrange.
ComplexIterator1D begin ()
Return iterator to first element.
ComplexIterator1D end ()
Return iterator behind last element.
ComplexVectorView & operator= (const ConstComplexVectorView &v)
Assignment operator.
ComplexVectorView & operator= (const ComplexVectorView &v)
Assignment from ComplexVectorView to ComplexVectorView.
ComplexVectorView & operator= (const ComplexVector &v)
Assignment from ComplexVector.
ComplexVectorView & operator= (const Array< Complex > &v)
Assignment operator from Array<Complex>.
ComplexVectorView & operator= (Complex x)
Assigning a scalar to a ComplexVectorView will set all elements to this value.
ComplexVectorView & operator= (const ConstVectorView &v)
ComplexVectorView & operator= (const VectorView &v)
ComplexVectorView & operator= (const Vector &v)
ComplexVectorView & operator= (const Array< Numeric > &v)
ComplexVectorView & operator= (Numeric x)
ComplexVectorView operator*= (Complex x)
Multiplication by scalar.
ComplexVectorView operator/= (Complex x)
Division by scalar.
ComplexVectorView operator+= (Complex x)
Addition of scalar.
ComplexVectorView operator-= (Complex x)
Subtraction of scalar.
ComplexVectorView operator*= (Numeric x)
Multiplication by scalar.
ComplexVectorView operator/= (Numeric x)
Division by scalar.
ComplexVectorView operator+= (Numeric x)
Addition of scalar.
ComplexVectorView operator-= (Numeric x)
Subtraction of scalar.
ComplexVectorView operator*= (const ConstComplexVectorView &x)
Element-vise multiplication by another vector.
ComplexVectorView operator/= (const ConstComplexVectorView &x)
Element-vise division by another vector.
ComplexVectorView operator+= (const ConstComplexVectorView &x)
Element-vise addition of another vector.
ComplexVectorView operator-= (const ConstComplexVectorView &x)
Element-vise subtraction of another vector.
ComplexVectorView operator*= (const ConstVectorView &x)
Element-vise multiplication by another vector.
ComplexVectorView operator/= (const ConstVectorView &x)
Element-vise division by another vector.
ComplexVectorView operator+= (const ConstVectorView &x)
Element-vise addition of another vector.
ComplexVectorView operator-= (const ConstVectorView &x)
Element-vise subtraction of another vector.
operator ComplexMatrixView ()
Conversion to 1 column matrix.
const Complex * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array.
Complex * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array.
virtual ~ComplexVectorView ()=default
Destructor.
ComplexVectorView (Complex &a)
A special constructor, which allows to make a VectorView from a scalar.
ConstComplexIterator1D begin () const
Return const iterator to first element.
ConstComplexIterator1D end () const
Return const iterator behind last element.
const Complex & get (Index n) const
Get element implementation without assertions.
const Numeric & get_imag (Index n) const
Get element implementation without assertions.
const Numeric & get_real (Index n) const
Get element implementation without assertions.
ConstVectorView imag () const
Get a view of the imaginary part of the vector.
ConstVectorView real () const
Get a view of the real part of the vector.
Public Member Functions inherited from ConstComplexVectorView
constexpr ConstComplexVectorView (const ConstComplexVectorView &)=default
constexpr ConstComplexVectorView (ConstComplexVectorView &&)=default
ConstComplexVectorView & operator= (const ConstComplexVectorView &)=default
ConstComplexVectorView & operator= (ConstComplexVectorView &&)=default
bool empty () const
Index nelem () const
Complex sum () const
Returns true if variable size is zero.
const Complex & operator[] (Index n) const
Plain const index operator.
const Complex & get (Index n) const
Get element implementation without assertions.
const Numeric & get_real (Index n) const
Get element implementation without assertions.
const Numeric & get_imag (Index n) const
Get element implementation without assertions.
ConstVectorView real () const
Get a view of the real part of the vector.
ConstVectorView imag () const
Get a view of the imaginary part of the vector.
ConstComplexVectorView operator[] (const Range &r) const
Const index operator for subrange.
ConstComplexIterator1D begin () const
Return const iterator to first element.
ConstComplexIterator1D end () const
Return const iterator behind last element.
operator ConstComplexMatrixView () const
Conversion to const 1 column matrix.
virtual ~ConstComplexVectorView ()=default
Destructor.
ConstComplexVectorView (const Complex &a)
A special constructor, which allows to make a ConstComplexVectorView from a scalar.
Protected Member Functions
ComplexVectorView ()=default
ComplexVectorView (Complex *data, const Range &range)
Explicit constructor.
ComplexVectorView (Complex *data, const Range &p, const Range &n)
Recursive constructor.
Protected Member Functions inherited from ConstComplexVectorView
ConstComplexVectorView ()=default
ConstComplexVectorView (Complex *data, const Range &range)
Explicit constructor.
ConstComplexVectorView (Complex *data, const Range &p, const Range &n)
Recursive constructor.
Friends
class ConstComplexIterator2D
class ComplexIterator2D
class ComplexMatrixView
Additional Inherited Members
Protected Attributes inherited from ConstComplexVectorView
Range mrange {0, 0}
The range of mdata that is actually used.
Complex * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The ComplexVectorView class.
This contains the main implementation of a complex vector. The class
ComplexVector is just a special case of subvector which also allocates storage.
Unfortunately, names of element functions of derived classes hide the names of the original class, even if the arguments are different. This means that we have to redefine those element functions that can have different arguments, for example the constant index operators and iterators.
Definition at line 367 of file complex.h.
Member Typedef Documentation
iterator
typedef ComplexIterator1D ComplexVectorView::iterator
Definition at line 384 of file complex.h.
Constructor & Destructor Documentation
ComplexVectorView() [1/7]
constexpr ComplexVectorView::ComplexVectorView (const ComplexVectorView &) constexpr default
ComplexVectorView() [2/7]
ComplexVectorView::ComplexVectorView (const ComplexVector &)
Bail out immediately if somebody tries to create a ComplexVectorView from a const Complex*Vector.
Definition at line 151 of file complex.cc.
References ARTS_ASSERT.
ComplexVectorView() [3/7]
ComplexVectorView::ComplexVectorView (ComplexVector & v)
Create ComplexVectorView from a ComplexVector.
Definition at line 162 of file complex.cc.
References ConstComplexVectorView::mdata, ConstComplexVectorView::mrange, and v().
~ComplexVectorView()
virtual ComplexVectorView::~ComplexVectorView () virtual default
Destructor.
ComplexVectorView() [4/7]
ComplexVectorView::ComplexVectorView (Complex & a)
A special constructor, which allows to make a VectorView from a scalar.
Definition at line 439 of file complex.cc.
ComplexVectorView() [5/7]
ComplexVectorView::ComplexVectorView () protected default
Referenced by operator[]().
ComplexVectorView() [6/7]
ComplexVectorView::ComplexVectorView (Complex * data, const Range & range) protected
Explicit constructor.
This one is used by Vector to initialize its own VectorView part.
Definition at line 445 of file complex.cc.
ComplexVectorView() [7/7]
ComplexVectorView::ComplexVectorView (Complex * data, const Range & p, const Range & n) protected
Recursive constructor.
This is used to construct sub ranges from sub ranges. That means that the new range has to be interpreted relative to the original range. The new range may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
p Previous range.
n New Range.
Definition at line 460 of file complex.cc.
Member Function Documentation
begin() [1/2]
ComplexIterator1D ComplexVectorView::begin ()
Return iterator to first element.
Definition at line 175 of file complex.cc.
References ConstComplexVectorView::mdata, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by ComplexVector::ComplexVector(), copy(), ComplexMatrixView::operator*=(), operator*=(), ComplexMatrixView::operator+=(), operator+=(), ComplexMatrixView::operator-=(), operator-=(), ComplexMatrixView::operator/=(), operator/=(), and operator=().
begin() [2/2]
ConstComplexIterator1D ConstComplexVectorView::begin
Return const iterator to first element.
Definition at line 317 of file complex.cc.
end() [1/2]
ComplexIterator1D ComplexVectorView::end ()
Return iterator behind last element.
Definition at line 180 of file complex.cc.
References ConstComplexVectorView::mdata, Range::mextent, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by ComplexMatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexMatrixView::operator/=(), and operator=().
end() [2/2]
ConstComplexIterator1D ConstComplexVectorView::end
Return const iterator behind last element.
Definition at line 318 of file complex.cc.
get() [1/2]
Complex& ComplexVectorView::get (Index n) inline
Get element implementation without assertions.
Definition at line 394 of file complex.h.
References ConstComplexVectorView::mdata, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
get() [2/2]
const Complex& ConstComplexVectorView::get inline
Get element implementation without assertions.
Definition at line 292 of file complex.h.
Referenced by get_imag(), ComplexMatrixView::get_imag(), ConstComplexMatrixView::get_imag(), get_real(), ComplexMatrixView::get_real(), ConstComplexMatrixView::get_real(), ComplexMatrixView::operator()(), ConstComplexMatrixView::operator()(), and operator[]().
get_c_array() [1/2]
Complex * ComplexVectorView::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the VectorView is not pointing to the beginning of a Vector or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 430 of file complex.cc.
References ARTS_ASSERT, ConstComplexVectorView::mdata, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Complex * ComplexVectorView::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the VectorView is not pointing to the beginning of a Vector or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 418 of file complex.cc.
References ARTS_ASSERT, ConstComplexVectorView::mdata, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by diagonalize(), and inv().
get_imag() [1/2]
Numeric& ComplexVectorView::get_imag (Index n) inline
Get element implementation without assertions.
Definition at line 404 of file complex.h.
References get().
get_imag() [2/2]
const Numeric& ConstComplexVectorView::get_imag inline
Get element implementation without assertions.
Definition at line 302 of file complex.h.
get_real() [1/2]
Numeric& ComplexVectorView::get_real (Index n) inline
Get element implementation without assertions.
Definition at line 399 of file complex.h.
References get().
get_real() [2/2]
const Numeric& ConstComplexVectorView::get_real inline
Get element implementation without assertions.
Definition at line 297 of file complex.h.
imag() [1/2]
VectorView ComplexVectorView::imag () inline
Get a view of the imaginary part of the vector.
Definition at line 412 of file complex.h.
References ConstComplexVectorView::mdata, Range::mextent, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
imag() [2/2]
ConstVectorView ConstComplexVectorView::imag inline
Get a view of the imaginary part of the vector.
Definition at line 310 of file complex.h.
operator ComplexMatrixView()
ComplexVectorView::operator ComplexMatrixView ()
Conversion to 1 column matrix.
Definition at line 403 of file complex.cc.
operator*=() [1/4]
ComplexVectorView ComplexVectorView::operator*= (Complex x)
Multiplication by scalar.
Definition at line 239 of file complex.cc.
operator*=() [2/4]
ComplexVectorView ComplexVectorView::operator*= (const ConstComplexVectorView & x)
Element-vise multiplication by another vector.
Definition at line 295 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator*=() [3/4]
ComplexVectorView ComplexVectorView::operator*= (const ConstVectorView & x)
Element-vise multiplication by another vector.
Definition at line 309 of file complex.cc.
References ARTS_ASSERT, ConstComplexVectorView::nelem(), and x.
operator*=() [4/4]
ComplexVectorView ComplexVectorView::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 246 of file complex.cc.
operator+=() [1/4]
ComplexVectorView ComplexVectorView::operator+= (Complex x)
Addition of scalar.
Definition at line 267 of file complex.cc.
operator+=() [2/4]
ComplexVectorView ComplexVectorView::operator+= (const ConstComplexVectorView & x)
Element-vise addition of another vector.
Definition at line 349 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator+=() [3/4]
ComplexVectorView ComplexVectorView::operator+= (const ConstVectorView & x)
Element-vise addition of another vector.
Definition at line 363 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator+=() [4/4]
ComplexVectorView ComplexVectorView::operator+= (Numeric x)
Addition of scalar.
Definition at line 274 of file complex.cc.
operator-=() [1/4]
ComplexVectorView ComplexVectorView::operator-= (Complex x)
Subtraction of scalar.
Definition at line 281 of file complex.cc.
operator-=() [2/4]
ComplexVectorView ComplexVectorView::operator-= (const ConstComplexVectorView & x)
Element-vise subtraction of another vector.
Definition at line 376 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator-=() [3/4]
ComplexVectorView ComplexVectorView::operator-= (const ConstVectorView & x)
Element-vise subtraction of another vector.
Definition at line 390 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator-=() [4/4]
ComplexVectorView ComplexVectorView::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 288 of file complex.cc.
operator/=() [1/4]
ComplexVectorView ComplexVectorView::operator/= (Complex x)
Division by scalar.
Definition at line 253 of file complex.cc.
operator/=() [2/4]
ComplexVectorView ComplexVectorView::operator/= (const ConstComplexVectorView & x)
Element-vise division by another vector.
Definition at line 322 of file complex.cc.
References ARTS_ASSERT, begin(), ConstComplexVectorView::nelem(), and x.
operator/=() [3/4]
ComplexVectorView ComplexVectorView::operator/= (const ConstVectorView & x)
Element-vise division by another vector.
Definition at line 336 of file complex.cc.
operator/=() [4/4]
ComplexVectorView ComplexVectorView::operator/= (Numeric x)
Division by scalar.
Definition at line 260 of file complex.cc.
operator=() [1/10]
ComplexVectorView & ComplexVectorView::operator= (Complex x)
Assigning a scalar to a ComplexVectorView will set all elements to this value.
Definition at line 233 of file complex.cc.
References begin(), copy(), end(), and x.
operator=() [2/10]
ComplexVectorView & ComplexVectorView::operator= (const Array< Complex > & v)
Assignment operator from Array<Complex>.
This copies the data from an Array<Complex> to this VectorView. Dimensions must agree! Resizing would destroy the selection that we might have done in this VectorView by setting its range.
Array<Complex> can be useful to collect things in, because there is a .push_back method for it. Then, after collecting we usually have to transfer the content to a Vector. With this assignment operator that's easy.
Definition at line 1526 of file complex.cc.
References ARTS_ASSERT, Range::mextent, ConstComplexVectorView::mrange, and v().
operator=() [3/10]
ComplexVectorView& ComplexVectorView::operator= (const Array< Numeric > & v)
operator=() [4/10]
ComplexVectorView & ComplexVectorView::operator= (const ComplexVector & v)
Assignment from ComplexVector.
This is important to avoid a bug when assigning a Vector to a Complex*VectorView.
Definition at line 220 of file complex.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstComplexVectorView::mrange, and v().
operator=() [5/10]
ComplexVectorView & ComplexVectorView::operator= (const ComplexVectorView & v)
Assignment from ComplexVectorView to ComplexVectorView.
This is a tricky one. The problem is that since ComplexVectorView is derived from ConstComplexVectorView, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 207 of file complex.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstComplexVectorView::mrange, and v().
operator=() [6/10]
ComplexVectorView & ComplexVectorView::operator= (const ConstComplexVectorView & v)
Assignment operator.
This copies the data from another VectorView t o this Complex*VectorView. Dimensions must agree! Resizing would destroy the selection that we might have done in this VectorView by setting its range.
Definition at line 190 of file complex.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstComplexVectorView::mrange, and v().
Referenced by ComplexVector::operator=().
operator=() [7/10]
ComplexVectorView& ComplexVectorView::operator= (const ConstVectorView & v)
operator=() [8/10]
ComplexVectorView& ComplexVectorView::operator= (const Vector & v)
operator=() [9/10]
ComplexVectorView& ComplexVectorView::operator= (const VectorView & v)
operator=() [10/10]
ComplexVectorView& ComplexVectorView::operator= (Numeric x)
operator[]() [1/2]
ComplexVectorView ComplexVectorView::operator[] (const Range & r)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Vector. This allows correct recursive behavior.
Definition at line 170 of file complex.cc.
References ComplexVectorView(), ConstComplexVectorView::mdata, and ConstComplexVectorView::mrange.
operator[]() [2/2]
Complex& ComplexVectorView::operator[] (Index n) inline
Plain Index operator.
Definition at line 387 of file complex.h.
References ARTS_ASSERT, get(), Range::mextent, and ConstComplexVectorView::mrange.
real() [1/2]
VectorView ComplexVectorView::real () inline
Get a view of the real part of the vector.
Definition at line 409 of file complex.h.
References ConstComplexVectorView::mdata, Range::mextent, ConstComplexVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_absorption_impl(), and Absorption::LineMixing::ecs_absorption_zeeman_impl().
real() [2/2]
ConstVectorView ConstComplexVectorView::real inline
Get a view of the real part of the vector.
Definition at line 307 of file complex.h.
Friends And Related Function Documentation
ComplexIterator2D
friend class ComplexIterator2D friend
Definition at line 462 of file complex.h.
ComplexMatrixView
friend class ComplexMatrixView friend
Definition at line 463 of file complex.h.
ConstComplexIterator2D
friend class ConstComplexIterator2D friend
Definition at line 461 of file complex.h.
The documentation for this class was generated from the following files:
complex.h
complex.cc