ARTS: Agenda Class Reference
Agenda Class Reference
The Agenda class.
#include <agenda_class.h>
Public Member Functions
Agenda ()
Agenda (const Agenda &x)
void append (const String &methodname, const TokVal &keywordvalue)
Appends methods to an agenda.
void check (Workspace &ws, const Verbosity &verbosity)
Checks consistency of an agenda.
void push_back (const MRecord &n)
Append a new method to end of list.
void execute (Workspace &ws) const
Execute an agenda.
void resize (Index n)
Resize the method list.
Index nelem () const
Return the number of agenda elements.
Agenda & operator= (const Agenda &x)
Assignment operator.
const Array< MRecord > & Methods () const
bool has_method (const String &methodname) const
Check if method is in Agenda.
void set_methods (const Array< MRecord > &ml)
void set_outputs_to_push_and_dup (const Verbosity &verbosity)
Retrieve indexes of all input and output WSVs.
bool is_input (Workspace &ws, Index var) const
Check if given variable is agenda input.
bool is_output (Index var) const
Check if given variable is agenda output.
void set_name (const String &nname)
Set agenda name.
String name () const
Agenda name.
const ArrayOfIndex & get_output2push () const
const ArrayOfIndex & get_output2dup () const
void print (ostream &os, const String &indent) const
Print an agenda.
void set_main_agenda ()
bool is_main_agenda () const
bool checked () const
Private Attributes
String mname
Array< MRecord > mml
ArrayOfIndex moutput_push
ArrayOfIndex moutput_dup
bool main_agenda
Is set to true if this is the main agenda.
bool mchecked
Flag indicating that the agenda was checked for consistency.
Detailed Description
The Agenda class.
An agenda is a list of workspace methods (including keyword data) to be executed. There are workspace variables of class agenda that can contain a list of methods to execute for a particular purpose, for example to compute the lineshape in an absorption calculation.
Definition at line 44 of file agenda_class.h.
Constructor & Destructor Documentation
Agenda() [1/2]
Agenda::Agenda () inline
Definition at line 46 of file agenda_class.h.
Referenced by append().
Agenda() [2/2]
Agenda::Agenda (const Agenda & x) inline
Copies an agenda.
Definition at line 58 of file agenda_class.h.
Member Function Documentation
append()
void Agenda::append (const String & methodname, const TokVal & keywordvalue)
Appends methods to an agenda.
This function appends a workspace method to the agenda. It currently only supports appending WSMs which have no generic input or output, and which are defined as Set methods which take only one keyword.
The keyword value has to be a string, which for no value should be of length zero.
Parameters
ws Workspace reference
methodname The name of the WSM
keywordvalue The value of the keyword
Author
Mattias Ekstrom
Date
2005-01-05
Definition at line 58 of file agenda_class.cc.
References Agenda(), ARTS_ASSERT, mchecked, global_data::md_data, global_data::MdMap, and mml.
check()
void Agenda::check (Workspace & ws, const Verbosity & verbosity)
Checks consistency of an agenda.
Checks that the input used by the agenda and the output produced by the actual methods corresponds to what is desired in the lookup data.
Definition at line 80 of file agenda_class.cc.
References global_data::agenda_data, global_data::AgendaMap, AgRecord::In(), is_input(), is_output(), mchecked, mname, nelem(), Array< base >::nelem(), AgRecord::Out(), set_outputs_to_push_and_dup(), ARTS::Var::verbosity(), and Workspace::wsv_data.
Referenced by AgendaAppend(), AgendaSet(), ArrayOfAgendaAppend(), Copy(), and InteractiveWorkspace::set_agenda_variable().
checked()
bool Agenda::checked () const inline
Definition at line 93 of file agenda_class.h.
References mchecked.
Referenced by abs_xsec_agendaExecute(), AgendaExecute(), dobatch_calc_agendaExecute(), doit_conv_test_agendaExecute(), doit_mono_agendaExecute(), doit_rte_agendaExecute(), doit_scat_field_agendaExecute(), forloop_agendaExecute(), g0_agendaExecute(), geo_pos_agendaExecute(), inversion_iterate_agendaExecute(), iy_cloudbox_agendaExecute(), iy_independent_beam_approx_agendaExecute(), iy_loop_freqs_agendaExecute(), iy_main_agendaExecute(), iy_radar_agendaExecute(), iy_space_agendaExecute(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iy_transmitter_agendaExecute(), jacobian_agendaExecute(), met_profile_calc_agendaExecute(), pha_mat_spt_agendaExecute(), pnd_agenda_arrayExecute(), ppath_agendaExecute(), ppath_step_agendaExecute(), propmat_clearsky_agendaExecute(), refr_index_air_agendaExecute(), sensor_response_agendaExecute(), spt_calc_agendaExecute(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), surface_rtprop_sub_agendaExecute(), test_agenda_arrayExecute(), water_p_eq_agendaExecute(), and ybatch_calc_agendaExecute().
execute()
void Agenda::execute (Workspace & ws) const
Execute an agenda.
This executes the methods specified in tasklist on the given workspace. It also checks for errors during the method execution and stops the program if an error has occured.
Definition at line 148 of file agenda_class.cc.
References ARTS_ASSERT, CREATE_OUT1, CREATE_OUT3, Workspace::duplicate(), get_wsv_id(), getaways, MRecord::Id(), MRecord::In(), MdRecord::InOut(), Workspace::is_initialized(), is_main_agenda(), MRecord::isInternal(), mchecked, global_data::md_data, mml, mname, name(), MdRecord::Name(), Array< base >::nelem(), MRecord::Out(), Workspace::pop_free(), Verbosity::set_main_agenda(), MdRecord::SetMethod(), v, ARTS::Var::verbosity(), Workspace::wsv_data, and ARTS::Var::x().
Referenced by AgendaExecute(), Arts2(), and auto_md_agenda_execute_helper().
get_output2dup()
const ArrayOfIndex& Agenda::get_output2dup () const inline
Definition at line 86 of file agenda_class.h.
References moutput_dup.
Referenced by AgendaExecute(), and auto_md_agenda_execute_helper().
get_output2push()
const ArrayOfIndex& Agenda::get_output2push () const inline
Definition at line 85 of file agenda_class.h.
References moutput_push.
Referenced by AgendaExecute(), and auto_md_agenda_execute_helper().
has_method()
bool Agenda::has_method (const String & methodname) const
Check if method is in Agenda.
This function checks if the method with the given name is called by this agenda.
Parameters
methodname Name of method to look for.
Returns
True if method is part of Agenda.
Author
Oliver Lemke
Date
2013-03-18
Definition at line 672 of file agenda_class.cc.
References global_data::md_data, and mml.
is_input()
bool Agenda::is_input (Workspace & ws, Index var) const
Check if given variable is agenda input.
A variable is agenda input if it is an input variable to any of the methods making up the agenda.
Parameters
[in,out] ws Current Workspace
[in] var The workspace variable to check.
Returns
True if var is an input variable of this agenda.
Definition at line 498 of file agenda_class.cc.
References global_data::agenda_data, global_data::AgendaMap, ARTS_ASSERT, MRecord::Id(), MRecord::In(), global_data::md_data, global_data::MdMap, mml, nelem(), Array< base >::nelem(), MRecord::Out(), Raw::Average::var(), Workspace::wsv_data, and global_data::WsvGroupMap.
Referenced by check().
is_main_agenda()
bool Agenda::is_main_agenda () const inline
Definition at line 92 of file agenda_class.h.
References main_agenda.
Referenced by execute().
is_output()
bool Agenda::is_output (Index var) const
Check if given variable is agenda output.
A variable is agenda output if it is an output variable to any of the methods making up the agenda.
Parameters
var The workspace variable to check.
Returns
True if var is an output variable of this agenda.
Definition at line 580 of file agenda_class.cc.
References global_data::agenda_data, global_data::AgendaMap, MRecord::Id(), MRecord::In(), global_data::md_data, global_data::MdMap, mml, nelem(), Array< base >::nelem(), MRecord::Out(), Raw::Average::var(), Workspace::wsv_data, and global_data::WsvGroupMap.
Referenced by check().
Methods()
const Array<MRecord>& Agenda::Methods () const inline
Definition at line 74 of file agenda_class.h.
References mml.
Referenced by agenda_append(), AgendaAppend(), and ArtsParser::parse_agenda().
name()
String Agenda::name () const
Agenda name.
Returns the private member mname.
Returns
The name of this agenda.
Definition at line 658 of file agenda_class.cc.
References mname.
Referenced by abs_xsec_agendaExecute(), AgendaExecute(), dobatch_calc_agendaExecute(), doit_conv_test_agendaExecute(), doit_mono_agendaExecute(), doit_rte_agendaExecute(), doit_scat_field_agendaExecute(), execute(), forloop_agendaExecute(), g0_agendaExecute(), geo_pos_agendaExecute(), inversion_iterate_agendaExecute(), iy_cloudbox_agendaExecute(), iy_independent_beam_approx_agendaExecute(), iy_loop_freqs_agendaExecute(), iy_main_agendaExecute(), iy_radar_agendaExecute(), iy_space_agendaExecute(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iy_transmitter_agendaExecute(), jacobian_agendaExecute(), met_profile_calc_agendaExecute(), pha_mat_spt_agendaExecute(), pnd_agenda_arrayExecute(), ppath_agendaExecute(), ppath_step_agendaExecute(), propmat_clearsky_agendaExecute(), refr_index_air_agendaExecute(), sensor_response_agendaExecute(), InteractiveWorkspace::set_agenda_variable(), set_outputs_to_push_and_dup(), spt_calc_agendaExecute(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), surface_rtprop_sub_agendaExecute(), test_agenda_arrayExecute(), water_p_eq_agendaExecute(), and ybatch_calc_agendaExecute().
nelem()
Index Agenda::nelem () const inline
Return the number of agenda elements.
This is needed, so that we can find out the correct size for resize, befor we do a copy.
Returns
Number of agenda elements.
Definition at line 266 of file agenda_class.h.
References mml, and Array< base >::nelem().
Referenced by check(), is_input(), is_output(), ArtsParser::parse_agenda(), and set_outputs_to_push_and_dup().
operator=()
Agenda & Agenda::operator= (const Agenda & x) inline
Assignment operator.
Copies an agenda.
Definition at line 283 of file agenda_class.h.
References mchecked, mml, mname, moutput_dup, moutput_push, and ARTS::Var::x().
print()
void Agenda::print (ostream & os, const String & indent) const
Print an agenda.
This prints an agenda, by printing the individual methods, just as they would appear in the controlfile.
Parameters
os Output stream.
indent How many characters of indentation.
Author
Stefan Buehler
Date
2002-12-02
Definition at line 696 of file agenda_class.cc.
References mml, and Array< base >::nelem().
Referenced by MRecord::print().
push_back()
void Agenda::push_back (const MRecord & n) inline
Append a new method to end of list.
This is used by the parser to fill up the agenda.
Parameters
n New method to add.
Definition at line 274 of file agenda_class.h.
References mchecked, and mml.
Referenced by agenda_append(), ArtsParser::parse_agenda(), and ArtsParser::tasklist_insert_set_delete().
resize()
void Agenda::resize (Index n) inline
Resize the method list.
Resizes the agenda's method list to n elements
Definition at line 257 of file agenda_class.h.
References mml.
Referenced by MRecord::operator=(), and ArtsParser::parse_method().
set_main_agenda()
void Agenda::set_main_agenda () inline
Definition at line 88 of file agenda_class.h.
References main_agenda, and mchecked.
Referenced by main().
set_methods()
void Agenda::set_methods (const Array< MRecord > & ml) inline
Definition at line 76 of file agenda_class.h.
References mchecked, and mml.
Referenced by AgendaAppend().
set_name()
void Agenda::set_name (const String & nname)
Set agenda name.
This sets the private member mname to the given string.
Parameters
nname The name for the agenda.
Definition at line 647 of file agenda_class.cc.
References mchecked, and mname.
Referenced by AgendaSet(), ArrayOfAgendaAppend(), Copy(), create_agenda(), InteractiveWorkspace::InteractiveWorkspace(), main(), and InteractiveWorkspace::set_agenda_variable().
set_outputs_to_push_and_dup()
void Agenda::set_outputs_to_push_and_dup (const Verbosity & verbosity)
Retrieve indexes of all input and output WSVs.
Builds arrays of WSM output variables which need to be duplicated or pushed on the WSV stack before the agenda is executed.
Definition at line 269 of file agenda_class.cc.
References global_data::agenda_data, global_data::AgendaMap, CREATE_OUT3, AgRecord::In(), global_data::md_data, global_data::MdMap, mml, moutput_dup, moutput_push, name(), nelem(), Array< base >::nelem(), AgRecord::Out(), PrintWsvNames(), Workspace::wsv_data, and global_data::WsvGroupMap.
Referenced by check().
Member Data Documentation
main_agenda
bool Agenda::main_agenda private
Is set to true if this is the main agenda.
Definition at line 104 of file agenda_class.h.
Referenced by is_main_agenda(), and set_main_agenda().
mchecked
bool Agenda::mchecked private
Flag indicating that the agenda was checked for consistency.
Definition at line 107 of file agenda_class.h.
Referenced by append(), check(), checked(), execute(), operator=(), push_back(), set_main_agenda(), set_methods(), and set_name().
mml
Array<MRecord> Agenda::mml private
The actual list of methods to execute.
Definition at line 97 of file agenda_class.h.
Referenced by append(), execute(), has_method(), is_input(), is_output(), Methods(), nelem(), operator=(), print(), push_back(), resize(), set_methods(), and set_outputs_to_push_and_dup().
mname
String Agenda::mname private
Agenda name.
Definition at line 96 of file agenda_class.h.
Referenced by check(), execute(), name(), operator=(), and set_name().
moutput_dup
ArrayOfIndex Agenda::moutput_dup private
Definition at line 101 of file agenda_class.h.
Referenced by get_output2dup(), operator=(), and set_outputs_to_push_and_dup().
moutput_push
ArrayOfIndex Agenda::moutput_push private
Definition at line 99 of file agenda_class.h.
Referenced by get_output2push(), operator=(), and set_outputs_to_push_and_dup().
The documentation for this class was generated from the following files:
agenda_class.h
agenda_class.cc