ARTS: ARTS::Var::ArrayOfArrayOfTransmissionMatrix Class Reference
ARTS::Var::ArrayOfArrayOfTransmissionMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfTransmissionMatrix () noexcept
ArrayOfArrayOfTransmissionMatrix (std::size_t i, void *x) noexcept
ArrayOfArrayOfTransmissionMatrix (const Group::ArrayOfArrayOfTransmissionMatrix &val) noexcept
~ArrayOfArrayOfTransmissionMatrix () noexcept
Group::ArrayOfArrayOfTransmissionMatrix & value () noexcept
const Group::ArrayOfArrayOfTransmissionMatrix & value () const noexcept
ArrayOfArrayOfTransmissionMatrix & operator= (const Group::ArrayOfArrayOfTransmissionMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfTransmissionMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfTransmissionMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1271 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfTransmissionMatrix() [1/3]
ARTS::Var::ArrayOfArrayOfTransmissionMatrix::ArrayOfArrayOfTransmissionMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1276 of file autoarts.h.
ArrayOfArrayOfTransmissionMatrix() [2/3]
ARTS::Var::ArrayOfArrayOfTransmissionMatrix::ArrayOfArrayOfTransmissionMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1279 of file autoarts.h.
ArrayOfArrayOfTransmissionMatrix() [3/3]
ARTS::Var::ArrayOfArrayOfTransmissionMatrix::ArrayOfArrayOfTransmissionMatrix (const Group::ArrayOfArrayOfTransmissionMatrix & val) inline noexcept
Construct from Group::ArrayOfArrayOfTransmissionMatrix. Leaves islast() true and isnull() false
Definition at line 1282 of file autoarts.h.
~ArrayOfArrayOfTransmissionMatrix()
ARTS::Var::ArrayOfArrayOfTransmissionMatrix::~ArrayOfArrayOfTransmissionMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1285 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfTransmissionMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1303 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfTransmissionMatrix().
isnull()
bool ARTS::Var::ArrayOfArrayOfTransmissionMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 1300 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfTransmissionMatrix().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfTransmissionMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1306 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfTransmissionMatrix& ARTS::Var::ArrayOfArrayOfTransmissionMatrix::operator= (const Group::ArrayOfArrayOfTransmissionMatrix & t) inline noexcept
Set value from Group::ArrayOfArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 1294 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfTransmissionMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1297 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfTransmissionMatrix& ARTS::Var::ArrayOfArrayOfTransmissionMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 1291 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfTransmissionMatrix& ARTS::Var::ArrayOfArrayOfTransmissionMatrix::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 1288 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfTransmissionMatrix & var) friend
Output to stream of internal variable
Definition at line 1309 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfTransmissionMatrix::p private
Definition at line 1272 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfTransmissionMatrix* ARTS::Var::ArrayOfArrayOfTransmissionMatrix::v private
Definition at line 1273 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfTransmissionMatrix().
The documentation for this class was generated from the following file:
autoarts.h