ARTS: ARTS::Var::ArrayOfTime Class Reference
ARTS::Var::ArrayOfTime Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTime () noexcept
ArrayOfTime (std::size_t i, void *x) noexcept
~ArrayOfTime () noexcept
ArrayOfTime (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
ArrayOfTime & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTime
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 948 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::ArrayOfTime::type = Group::ArrayOfTime private
Definition at line 949 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTime() [1/3]
ARTS::Var::ArrayOfTime::ArrayOfTime () inline noexcept
Definition at line 953 of file autoarts.h.
ArrayOfTime() [2/3]
ARTS::Var::ArrayOfTime::ArrayOfTime (std::size_t i, void * x) inline noexcept
Definition at line 954 of file autoarts.h.
~ArrayOfTime()
ARTS::Var::ArrayOfTime::~ArrayOfTime () inline noexcept
Definition at line 955 of file autoarts.h.
References islast(), isnull(), and v.
ArrayOfTime() [3/3]
ARTS::Var::ArrayOfTime::ArrayOfTime (const type & val) inline noexcept
Definition at line 956 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTime::islast () const inline noexcept
Definition at line 962 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::time_stampsSort(), ARTS::Method::time_stampsSort(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~ArrayOfTime().
isnull()
bool ARTS::Var::ArrayOfTime::isnull () const inline noexcept
Definition at line 961 of file autoarts.h.
References v.
Referenced by ~ArrayOfTime().
name()
const Group::String& ARTS::Var::ArrayOfTime::name () const inline noexcept
Definition at line 963 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
ArrayOfTime& ARTS::Var::ArrayOfTime::operator= (const type & t) inline noexcept
Definition at line 959 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTime::pos () const inline noexcept
Definition at line 960 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::time_stampsSort(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::ArrayOfTime::value () const inline noexcept
Definition at line 958 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::ArrayOfTime::value () inline noexcept
Definition at line 957 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), ARTS::Method::time_stampsSort(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTime::p private
Definition at line 950 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::ArrayOfTime::v private
Definition at line 951 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTime().
The documentation for this class was generated from the following file:
autoarts.h