ARTS: ARTS::Var::WorkspaceQuantumIdentifier Class Reference
ARTS::Var::WorkspaceQuantumIdentifier Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceQuantumIdentifier () noexcept
WorkspaceQuantumIdentifier (std::size_t i, void *x) noexcept
~WorkspaceQuantumIdentifier () noexcept
WorkspaceQuantumIdentifier (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceQuantumIdentifier & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::QuantumIdentifier
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1322 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceQuantumIdentifier::type = Group::QuantumIdentifier private
Definition at line 1323 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceQuantumIdentifier() [1/3]
ARTS::Var::WorkspaceQuantumIdentifier::WorkspaceQuantumIdentifier () inline noexcept
Definition at line 1327 of file autoarts.h.
WorkspaceQuantumIdentifier() [2/3]
ARTS::Var::WorkspaceQuantumIdentifier::WorkspaceQuantumIdentifier (std::size_t i, void * x) inline noexcept
Definition at line 1328 of file autoarts.h.
~WorkspaceQuantumIdentifier()
ARTS::Var::WorkspaceQuantumIdentifier::~WorkspaceQuantumIdentifier () inline noexcept
Definition at line 1329 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceQuantumIdentifier() [3/3]
ARTS::Var::WorkspaceQuantumIdentifier::WorkspaceQuantumIdentifier (const type & val) inline noexcept
Definition at line 1330 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceQuantumIdentifier::islast () const inline noexcept
Definition at line 1336 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetMirroringForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetPopulationForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForMatch(), ARTS::AgendaMethod::abs_linesRemoveBand(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetCutoffForMatch(), ARTS::AgendaMethod::abs_linesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetLineShapeTypeForMatch(), ARTS::AgendaMethod::abs_linesSetMirroringForMatch(), ARTS::AgendaMethod::abs_linesSetNormalizationForMatch(), ARTS::AgendaMethod::abs_linesSetPopulationForMatch(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesSetT0ForMatch(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameter(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameter(), ARTS::AgendaMethod::QuantumIdentifierSet(), ARTS::Method::QuantumIdentifierSet(), ARTS::AgendaMethod::retrievalAddCatalogParameter(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceQuantumIdentifier().
isnull()
bool ARTS::Var::WorkspaceQuantumIdentifier::isnull () const inline noexcept
Definition at line 1335 of file autoarts.h.
References v.
Referenced by ~WorkspaceQuantumIdentifier().
name()
const Group::String& ARTS::Var::WorkspaceQuantumIdentifier::name () const inline noexcept
Definition at line 1337 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceQuantumIdentifier& ARTS::Var::WorkspaceQuantumIdentifier::operator= (const type & t) inline noexcept
Definition at line 1333 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceQuantumIdentifier::pos () const inline noexcept
Definition at line 1334 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_lines_per_speciesSetCutoffForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::AgendaMethod::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetMirroringForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetPopulationForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_lines_per_speciesSetT0ForMatch(), ARTS::AgendaMethod::abs_linesRemoveBand(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevel(), ARTS::AgendaMethod::abs_linesSetCutoffForMatch(), ARTS::AgendaMethod::abs_linesSetLinemixingLimitForMatch(), ARTS::AgendaMethod::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::AgendaMethod::abs_linesSetLineShapeTypeForMatch(), ARTS::AgendaMethod::abs_linesSetMirroringForMatch(), ARTS::AgendaMethod::abs_linesSetNormalizationForMatch(), ARTS::AgendaMethod::abs_linesSetPopulationForMatch(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesSetT0ForMatch(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameter(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameter(), ARTS::AgendaMethod::QuantumIdentifierSet(), ARTS::AgendaMethod::retrievalAddCatalogParameter(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceQuantumIdentifier::value () const inline noexcept
Definition at line 1332 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceQuantumIdentifier::value () inline noexcept
Definition at line 1331 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParameterForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_linesRemoveBand(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParameterForMatchingLines(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameter(), operator=(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::retrievalAddCatalogParameter(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceQuantumIdentifier::p private
Definition at line 1324 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceQuantumIdentifier::v private
Definition at line 1325 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceQuantumIdentifier().
The documentation for this class was generated from the following file:
autoarts.h