ARTS: ARTS::Var::WorkspaceEnergyLevelMap Class Reference
ARTS::Var::WorkspaceEnergyLevelMap Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceEnergyLevelMap () noexcept
WorkspaceEnergyLevelMap (std::size_t i, void *x) noexcept
~WorkspaceEnergyLevelMap () noexcept
WorkspaceEnergyLevelMap (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceEnergyLevelMap & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::EnergyLevelMap
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1034 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceEnergyLevelMap::type = Group::EnergyLevelMap private
Definition at line 1035 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceEnergyLevelMap() [1/3]
ARTS::Var::WorkspaceEnergyLevelMap::WorkspaceEnergyLevelMap () inline noexcept
Definition at line 1039 of file autoarts.h.
WorkspaceEnergyLevelMap() [2/3]
ARTS::Var::WorkspaceEnergyLevelMap::WorkspaceEnergyLevelMap (std::size_t i, void * x) inline noexcept
Definition at line 1040 of file autoarts.h.
~WorkspaceEnergyLevelMap()
ARTS::Var::WorkspaceEnergyLevelMap::~WorkspaceEnergyLevelMap () inline noexcept
Definition at line 1041 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceEnergyLevelMap() [3/3]
ARTS::Var::WorkspaceEnergyLevelMap::WorkspaceEnergyLevelMap (const type & val) inline noexcept
Definition at line 1042 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceEnergyLevelMap::islast () const inline noexcept
Definition at line 1048 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceEnergyLevelMap().
isnull()
bool ARTS::Var::WorkspaceEnergyLevelMap::isnull () const inline noexcept
Definition at line 1047 of file autoarts.h.
References v.
Referenced by ~WorkspaceEnergyLevelMap().
name()
const Group::String& ARTS::Var::WorkspaceEnergyLevelMap::name () const inline noexcept
Definition at line 1049 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceEnergyLevelMap& ARTS::Var::WorkspaceEnergyLevelMap::operator= (const type & t) inline noexcept
Definition at line 1045 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceEnergyLevelMap::pos () const inline noexcept
Definition at line 1046 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceEnergyLevelMap::value () const inline noexcept
Definition at line 1044 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceEnergyLevelMap::value () inline noexcept
Definition at line 1043 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceEnergyLevelMap::p private
Definition at line 1036 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceEnergyLevelMap::v private
Definition at line 1037 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceEnergyLevelMap().
The documentation for this class was generated from the following file:
autoarts.h