ARTS: ARTS::Var::ArrayOfAgenda Class Reference
ARTS::Var::ArrayOfAgenda Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfAgenda () noexcept
ArrayOfAgenda (std::size_t i, void *x) noexcept
ArrayOfAgenda (const Group::ArrayOfAgenda &val) noexcept
~ArrayOfAgenda () noexcept
Group::ArrayOfAgenda & value () noexcept
const Group::ArrayOfAgenda & value () const noexcept
ArrayOfAgenda & operator= (const Group::ArrayOfAgenda &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfAgenda * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfAgenda &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 465 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfAgenda() [1/3]
ARTS::Var::ArrayOfAgenda::ArrayOfAgenda () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 470 of file autoarts.h.
ArrayOfAgenda() [2/3]
ARTS::Var::ArrayOfAgenda::ArrayOfAgenda (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 473 of file autoarts.h.
ArrayOfAgenda() [3/3]
ARTS::Var::ArrayOfAgenda::ArrayOfAgenda (const Group::ArrayOfAgenda & val) inline noexcept
Construct from Group::ArrayOfAgenda. Leaves islast() true and isnull() false
Definition at line 476 of file autoarts.h.
~ArrayOfAgenda()
ARTS::Var::ArrayOfAgenda::~ArrayOfAgenda () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 479 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfAgenda::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 497 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfAgenda().
isnull()
bool ARTS::Var::ArrayOfAgenda::isnull () const inline noexcept
Return true if there is no data
Definition at line 494 of file autoarts.h.
References v.
Referenced by ~ArrayOfAgenda().
name()
const Group::String& ARTS::Var::ArrayOfAgenda::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 500 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfAgenda& ARTS::Var::ArrayOfAgenda::operator= (const Group::ArrayOfAgenda & t) inline noexcept
Set value from Group::ArrayOfAgenda. Works when isnull() is false
Definition at line 488 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfAgenda::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 491 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfAgenda& ARTS::Var::ArrayOfAgenda::value () const inline noexcept
Get value const-ref as Group::ArrayOfAgenda. Works when isnull() is false
Definition at line 485 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfAgenda& ARTS::Var::ArrayOfAgenda::value () inline noexcept
Get value ref as Group::ArrayOfAgenda. Works when isnull() is false
Definition at line 482 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfAgenda & var) friend
Output to stream of internal variable
Definition at line 503 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfAgenda::p private
Definition at line 466 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfAgenda* ARTS::Var::ArrayOfAgenda::v private
Definition at line 467 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfAgenda().
The documentation for this class was generated from the following file:
autoarts.h