ARTS: QuadraticModel Class Reference
QuadraticModel Class Reference
Quadratic Forward Model.
Public Member Functions
QuadraticModel (Index m_, Index n_)
Constructor.
~QuadraticModel ()
Destructor.
OEMMatrix Jacobian (const ConstVectorView &xi)
Virtual function of the FowardModel class.
OEMVector evaluate (const OEMVector &xi)
Virtual function of the FowardModel class.
Public Attributes
const unsigned int m
const unsigned int n
Private Attributes
OEMMatrix J
OEMMatrix * Hessians
Detailed Description
Quadratic Forward Model.
Test class for the ForwardModel class as defined in oem.h. Implements a quadratic length-m vector valued function in n variables. The function is represented by a set of m-hessians and a Jacobian. On construction those are set to random matrices to test the non-linear OEM methods.
Definition at line 91 of file test_oem.cc.
Constructor & Destructor Documentation
QuadraticModel()
QuadraticModel::QuadraticModel (Index m_, Index n_) inline
Constructor.
Construct a random quadratic model. Allocates the necessary space and fille the Jacobian with values in the range [-10,10] and the Hessians in the range [0,0.1]. Also writes all matrices to text files for the communication with the Matlab process.
Parameters
[in] m_ The dimension of the measurement space.
[in] n_ The dimension of the state space.
Definition at line 103 of file test_oem.cc.
References Hessians, J, m, n, random_fill_matrix(), random_fill_matrix_symmetric(), and write_matrix().
~QuadraticModel()
QuadraticModel::~QuadraticModel () inline
Destructor.
Definition at line 122 of file test_oem.cc.
References Hessians.
Member Function Documentation
evaluate()
OEMVector QuadraticModel::evaluate (const OEMVector & xi) inline
Virtual function of the FowardModel class.
Definition at line 139 of file test_oem.cc.
References Hessians, J, m, mult(), and n.
Referenced by test_oem_gauss_newton(), test_oem_gauss_newton_sparse(), and test_oem_levenberg_marquardt().
Jacobian()
OEMMatrix QuadraticModel::Jacobian (const ConstVectorView & xi) inline
Virtual function of the FowardModel class.
Definition at line 125 of file test_oem.cc.
References Hessians, J, m, mult(), and n.
Member Data Documentation
Hessians
OEMMatrix* QuadraticModel::Hessians private
Definition at line 159 of file test_oem.cc.
Referenced by evaluate(), Jacobian(), QuadraticModel(), and ~QuadraticModel().
J
OEMMatrix QuadraticModel::J private
Definition at line 158 of file test_oem.cc.
Referenced by evaluate(), Jacobian(), and QuadraticModel().
m
const unsigned int QuadraticModel::m
Definition at line 155 of file test_oem.cc.
Referenced by evaluate(), Jacobian(), and QuadraticModel().
n
const unsigned int QuadraticModel::n
Definition at line 155 of file test_oem.cc.
Referenced by evaluate(), Jacobian(), and QuadraticModel().
The documentation for this class was generated from the following file:
test_oem.cc