ARTS: ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfPropagationMatrix () noexcept
WorkspaceArrayOfArrayOfPropagationMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfPropagationMatrix () noexcept
WorkspaceArrayOfArrayOfPropagationMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfPropagationMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfPropagationMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 296 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::type = Group::ArrayOfArrayOfPropagationMatrix private
Definition at line 297 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfPropagationMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::WorkspaceArrayOfArrayOfPropagationMatrix () inline noexcept
Definition at line 301 of file autoarts.h.
WorkspaceArrayOfArrayOfPropagationMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::WorkspaceArrayOfArrayOfPropagationMatrix (std::size_t i, void * x) inline noexcept
Definition at line 302 of file autoarts.h.
~WorkspaceArrayOfArrayOfPropagationMatrix()
ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::~WorkspaceArrayOfArrayOfPropagationMatrix () inline noexcept
Definition at line 303 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfPropagationMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::WorkspaceArrayOfArrayOfPropagationMatrix (const type & val) inline noexcept
Definition at line 304 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::islast () const inline noexcept
Definition at line 310 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfPropagationMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::isnull () const inline noexcept
Definition at line 309 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfPropagationMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::name () const inline noexcept
Definition at line 311 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfPropagationMatrix& ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::operator= (const type & t) inline noexcept
Definition at line 307 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::pos () const inline noexcept
Definition at line 308 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::value () const inline noexcept
Definition at line 306 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::value () inline noexcept
Definition at line 305 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::p private
Definition at line 298 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfPropagationMatrix::v private
Definition at line 299 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfPropagationMatrix().
The documentation for this class was generated from the following file:
autoarts.h