ARTS: ARTS::Var::WorkspaceArrayOfGriddedField1 Class Reference
ARTS::Var::WorkspaceArrayOfGriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfGriddedField1 () noexcept
WorkspaceArrayOfGriddedField1 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfGriddedField1 () noexcept
WorkspaceArrayOfGriddedField1 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfGriddedField1 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfGriddedField1
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 530 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfGriddedField1::type = Group::ArrayOfGriddedField1 private
Definition at line 531 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfGriddedField1() [1/3]
ARTS::Var::WorkspaceArrayOfGriddedField1::WorkspaceArrayOfGriddedField1 () inline noexcept
Definition at line 535 of file autoarts.h.
WorkspaceArrayOfGriddedField1() [2/3]
ARTS::Var::WorkspaceArrayOfGriddedField1::WorkspaceArrayOfGriddedField1 (std::size_t i, void * x) inline noexcept
Definition at line 536 of file autoarts.h.
~WorkspaceArrayOfGriddedField1()
ARTS::Var::WorkspaceArrayOfGriddedField1::~WorkspaceArrayOfGriddedField1 () inline noexcept
Definition at line 537 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfGriddedField1() [3/3]
ARTS::Var::WorkspaceArrayOfGriddedField1::WorkspaceArrayOfGriddedField1 (const type & val) inline noexcept
Definition at line 538 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfGriddedField1::islast () const inline noexcept
Definition at line 544 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfGriddedField1().
isnull()
bool ARTS::Var::WorkspaceArrayOfGriddedField1::isnull () const inline noexcept
Definition at line 543 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfGriddedField1().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfGriddedField1::name () const inline noexcept
Definition at line 545 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfGriddedField1& ARTS::Var::WorkspaceArrayOfGriddedField1::operator= (const type & t) inline noexcept
Definition at line 541 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField1::pos () const inline noexcept
Definition at line 542 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfGriddedField1::value () const inline noexcept
Definition at line 540 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfGriddedField1::value () inline noexcept
Definition at line 539 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField1::p private
Definition at line 532 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfGriddedField1::v private
Definition at line 533 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfGriddedField1().
The documentation for this class was generated from the following file:
autoarts.h