ARTS: AgRecord Class Reference
AgRecord Class Reference
Lookup information for one agenda.
#include <agenda_record.h>
Public Member Functions
AgRecord ()
Default constructor.
AgRecord (const char name[], const char description[], const ArrayOfString &output, const ArrayOfString &input)
The only non-trivial constructor for AgRecord, which sets all the fields.
AgRecord (const AgRecord &)=default
const String & Name () const
const String & Description () const
const ArrayOfIndex & Out () const
const ArrayOfIndex & In () const
AgRecord operator= (const AgRecord &)
Assignment operator.
Private Attributes
String mname
The name of this agenda.
String mdescription
A text string describing this agenda.
ArrayOfIndex moutput
Workspace Output.
ArrayOfIndex minput
Workspace Input.
Detailed Description
Lookup information for one agenda.
An object of this class contains the documentation for an agenda, plus the list of output and input variables.
This cannot be set in the workspace lookup data, since we need to use the handles for the WSVs.
Definition at line 43 of file agenda_record.h.
Constructor & Destructor Documentation
AgRecord() [1/3]
AgRecord::AgRecord () inline
Default constructor.
Definition at line 46 of file agenda_record.h.
Referenced by operator=().
AgRecord() [2/3]
AgRecord::AgRecord (const char name[], const char description[], const ArrayOfString & output, const ArrayOfString & input)
The only non-trivial constructor for AgRecord, which sets all the fields.
We work on the assumption, that the workspace lookup data has been defined before. So, what we have to do here is make sure that this agenda exists.
Parameters
name Agenda name.
description Agenda documentation.
output List of output WSVs.
input List of input WSVs.
Definition at line 52 of file agenda_record.cc.
References Zeeman::end(), get_wsv_id(), minput, mname, moutput, Array< base >::nelem(), and Workspace::WsvMap.
AgRecord() [3/3]
AgRecord::AgRecord (const AgRecord &) default
Member Function Documentation
Description()
const String& AgRecord::Description () const inline
Definition at line 59 of file agenda_record.h.
References mdescription.
Referenced by operator<<().
In()
const ArrayOfIndex& AgRecord::In () const inline
Definition at line 61 of file agenda_record.h.
References minput.
Referenced by abs_xsec_agendaExecute(), AgendaExecute(), Agenda::check(), dobatch_calc_agendaExecute(), doit_conv_test_agendaExecute(), doit_mono_agendaExecute(), doit_rte_agendaExecute(), doit_scat_field_agendaExecute(), forloop_agendaExecute(), g0_agendaExecute(), geo_pos_agendaExecute(), inversion_iterate_agendaExecute(), iy_cloudbox_agendaExecute(), iy_independent_beam_approx_agendaExecute(), iy_loop_freqs_agendaExecute(), iy_main_agendaExecute(), iy_radar_agendaExecute(), iy_space_agendaExecute(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iy_transmitter_agendaExecute(), jacobian_agendaExecute(), met_profile_calc_agendaExecute(), operator<<(), pha_mat_spt_agendaExecute(), pnd_agenda_arrayExecute(), ppath_agendaExecute(), ppath_step_agendaExecute(), propmat_clearsky_agendaExecute(), refr_index_air_agendaExecute(), sensor_response_agendaExecute(), Agenda::set_outputs_to_push_and_dup(), spt_calc_agendaExecute(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), surface_rtprop_sub_agendaExecute(), test_agenda_arrayExecute(), water_p_eq_agendaExecute(), write_agenda_wrapper_header(), and ybatch_calc_agendaExecute().
Name()
const String& AgRecord::Name () const inline
Definition at line 58 of file agenda_record.h.
References mname.
Referenced by operator<<(), and write_agenda_wrapper_header().
operator=()
AgRecord AgRecord::operator= (const AgRecord &) inline
Assignment operator.
To override the default assignment operator. AgRecords cannot be assigned!
Definition at line 66 of file agenda_record.h.
References AgRecord(), and arts_exit().
Out()
const ArrayOfIndex& AgRecord::Out () const inline
Definition at line 60 of file agenda_record.h.
References moutput.
Referenced by abs_xsec_agendaExecute(), AgendaExecute(), Agenda::check(), dobatch_calc_agendaExecute(), doit_conv_test_agendaExecute(), doit_mono_agendaExecute(), doit_rte_agendaExecute(), doit_scat_field_agendaExecute(), g0_agendaExecute(), geo_pos_agendaExecute(), inversion_iterate_agendaExecute(), iy_cloudbox_agendaExecute(), iy_independent_beam_approx_agendaExecute(), iy_loop_freqs_agendaExecute(), iy_main_agendaExecute(), iy_radar_agendaExecute(), iy_space_agendaExecute(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iy_transmitter_agendaExecute(), jacobian_agendaExecute(), met_profile_calc_agendaExecute(), operator<<(), pha_mat_spt_agendaExecute(), pnd_agenda_arrayExecute(), ppath_agendaExecute(), ppath_step_agendaExecute(), propmat_clearsky_agendaExecute(), refr_index_air_agendaExecute(), sensor_response_agendaExecute(), Agenda::set_outputs_to_push_and_dup(), spt_calc_agendaExecute(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), surface_rtprop_sub_agendaExecute(), water_p_eq_agendaExecute(), write_agenda_wrapper_header(), and ybatch_calc_agendaExecute().
Member Data Documentation
mdescription
String AgRecord::mdescription private
A text string describing this agenda.
Definition at line 77 of file agenda_record.h.
Referenced by Description().
minput
ArrayOfIndex AgRecord::minput private
Workspace Input.
Definition at line 83 of file agenda_record.h.
Referenced by AgRecord(), and In().
mname
String AgRecord::mname private
The name of this agenda.
Definition at line 74 of file agenda_record.h.
Referenced by AgRecord(), and Name().
moutput
ArrayOfIndex AgRecord::moutput private
Workspace Output.
Definition at line 80 of file agenda_record.h.
Referenced by AgRecord(), and Out().
The documentation for this class was generated from the following files:
agenda_record.h
agenda_record.cc