ARTS: ARTS::Var::WorkspaceArrayOfGriddedField2 Class Reference
ARTS::Var::WorkspaceArrayOfGriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfGriddedField2 () noexcept
WorkspaceArrayOfGriddedField2 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfGriddedField2 () noexcept
WorkspaceArrayOfGriddedField2 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfGriddedField2 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfGriddedField2
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 548 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfGriddedField2::type = Group::ArrayOfGriddedField2 private
Definition at line 549 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfGriddedField2() [1/3]
ARTS::Var::WorkspaceArrayOfGriddedField2::WorkspaceArrayOfGriddedField2 () inline noexcept
Definition at line 553 of file autoarts.h.
WorkspaceArrayOfGriddedField2() [2/3]
ARTS::Var::WorkspaceArrayOfGriddedField2::WorkspaceArrayOfGriddedField2 (std::size_t i, void * x) inline noexcept
Definition at line 554 of file autoarts.h.
~WorkspaceArrayOfGriddedField2()
ARTS::Var::WorkspaceArrayOfGriddedField2::~WorkspaceArrayOfGriddedField2 () inline noexcept
Definition at line 555 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfGriddedField2() [3/3]
ARTS::Var::WorkspaceArrayOfGriddedField2::WorkspaceArrayOfGriddedField2 (const type & val) inline noexcept
Definition at line 556 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfGriddedField2::islast () const inline noexcept
Definition at line 562 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfGriddedField2().
isnull()
bool ARTS::Var::WorkspaceArrayOfGriddedField2::isnull () const inline noexcept
Definition at line 561 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfGriddedField2().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfGriddedField2::name () const inline noexcept
Definition at line 563 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfGriddedField2& ARTS::Var::WorkspaceArrayOfGriddedField2::operator= (const type & t) inline noexcept
Definition at line 559 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField2::pos () const inline noexcept
Definition at line 560 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfGriddedField2::value () const inline noexcept
Definition at line 558 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfGriddedField2::value () inline noexcept
Definition at line 557 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField2::p private
Definition at line 550 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfGriddedField2::v private
Definition at line 551 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfGriddedField2().
The documentation for this class was generated from the following file:
autoarts.h