ARTS: ConstTensor7View Class Reference
ConstTensor7View Class Reference
A constant view of a Tensor7.
#include <matpackVII.h>
Public Member Functions
constexpr ConstTensor7View (const ConstTensor7View &)=default
constexpr ConstTensor7View (ConstTensor7View &&)=default
ConstTensor7View & operator= (const ConstTensor7View &)=default
ConstTensor7View & operator= (ConstTensor7View &&)=default
bool empty () const
Check if variable is empty.
Index nlibraries () const
Returns the number of libraries.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor7View ()=default
Destructor.
ConstTensor7View (const ConstTensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
Protected Member Functions
ConstTensor7View ()=default
ConstTensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes
Range mlr {0, 0, 1}
The library range of mdata that is actually used.
Range mvr {0, 0, 1}
The vitrine range of mdata that is actually used.
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Friends
class Tensor7View
Detailed Description
A constant view of a Tensor7.
This, together with the derived class Tensor7View, contains the main implementation of a Tensor7. It defines the concepts of Tensor7View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor7View from a subrange of a Tensor7View.
Dimensions are called: library, vitrine, shelf, book, page, row, column. or short: l, v, s, b, p, r, c
The class Tensor7 is just a special case of a Tensor7View which also allocates storage.
Definition at line 147 of file matpackVII.h.
Constructor & Destructor Documentation
ConstTensor7View() [1/6]
constexpr ConstTensor7View::ConstTensor7View (const ConstTensor7View &) constexpr default
ConstTensor7View() [2/6]
constexpr ConstTensor7View::ConstTensor7View (ConstTensor7View &&) constexpr default
~ConstTensor7View()
virtual ConstTensor7View::~ConstTensor7View () virtual default
Destructor.
ConstTensor7View() [3/6]
ConstTensor7View::ConstTensor7View (const ConstTensor6View & a)
Special constructor to make a Tensor7 view of a Tensor6.
Definition at line 2505 of file matpackVII.cc.
ConstTensor7View() [4/6]
ConstTensor7View::ConstTensor7View () protected default
ConstTensor7View() [5/6]
ConstTensor7View::ConstTensor7View (Numeric * data, const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor7 to initialize its own Tensor7View part. The row range rr must have a stride to account for the length of one row. The page range pr must have a stride to account for the length of one page.
Definition at line 2524 of file matpackVII.cc.
ConstTensor7View() [6/6]
ConstTensor7View::ConstTensor7View (Numeric * data, const Range & pl, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nl, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct sub-tensors from sub-tensors. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Definition at line 2543 of file matpackVII.cc.
Member Function Documentation
begin()
ConstIterator7D ConstTensor7View::begin () const
Return const iterator to first sub-tensor.
Definition at line 2485 of file matpackVII.cc.
References mbr, mcr, mdata, mlr, mpr, mrr, msr, Range::mstart, Range::mstride, and mvr.
Referenced by operator<<(), Tensor7View::operator=(), and Tensor7::Tensor7().
empty()
bool ConstTensor7View::empty () const
Check if variable is empty.
Parameters
[in] x The variable to check.
Returns
True if the size of any dimension of x is 0.
Definition at line 36 of file matpackVII.cc.
References nbooks(), ncols(), nlibraries(), npages(), nrows(), nshelves(), and nvitrines().
Referenced by get_variable_value(), and test_empty().
end()
ConstIterator7D ConstTensor7View::end () const
Return const iterator behind last sub-tensor.
Definition at line 2492 of file matpackVII.cc.
References mbr, mcr, mdata, Range::mextent, mlr, mpr, mrr, msr, Range::mstart, Range::mstride, and mvr.
Referenced by operator<<(), Tensor7View::operator=(), and Tensor7::Tensor7().
get()
Numeric ConstTensor7View::get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 1211 of file matpackVII.h.
nbooks()
Index ConstTensor7View::nbooks () const
Returns the number of books.
Definition at line 51 of file matpackVII.cc.
References mbr, and Range::mextent.
Referenced by Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
ncols()
Index ConstTensor7View::ncols () const
Returns the number of columns.
Definition at line 60 of file matpackVII.cc.
References mcr, and Range::mextent.
Referenced by cloudbox_fieldSetFromPrecalc(), Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), Reduce(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
nlibraries()
Index ConstTensor7View::nlibraries () const
Returns the number of libraries.
Definition at line 42 of file matpackVII.cc.
References Range::mextent, and mlr.
Referenced by _cr_internal_(), cloudbox_fieldSetFromPrecalc(), Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), xml_read_from_stream(), and xml_write_to_stream().
npages()
Index ConstTensor7View::npages () const
Returns the number of pages.
Definition at line 54 of file matpackVII.cc.
References Range::mextent, and mpr.
Referenced by cloudbox_fieldSetFromPrecalc(), Compare(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
nrows()
Index ConstTensor7View::nrows () const
Returns the number of rows.
Definition at line 57 of file matpackVII.cc.
References Range::mextent, and mrr.
Referenced by Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
nshelves()
Index ConstTensor7View::nshelves () const
Returns the number of shelves.
Definition at line 48 of file matpackVII.cc.
References Range::mextent, and msr.
Referenced by Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
nvitrines()
Index ConstTensor7View::nvitrines () const
Returns the number of vitrines.
Definition at line 45 of file matpackVII.cc.
References Range::mextent, and mvr.
Referenced by cloudbox_fieldSetFromPrecalc(), Compare(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), FouComp_1ScatElem(), get_variable_value(), Tensor7View::operator*=(), Tensor7View::operator+=(), Tensor7View::operator-=(), Tensor7View::operator/=(), Tensor7::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), select_dims_by_size(), Tensor7::Tensor7(), Tensor7Scale(), test7(), and xml_write_to_stream().
operator()() [1/128]
ConstTensor7View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 65 of file matpackVII.cc.
operator()() [2/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 89 of file matpackVII.cc.
operator()() [3/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 115 of file matpackVII.cc.
operator()() [4/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 245 of file matpackVII.cc.
operator()() [5/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 141 of file matpackVII.cc.
operator()() [6/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 280 of file matpackVII.cc.
operator()() [7/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 420 of file matpackVII.cc.
operator()() [8/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 770 of file matpackVII.cc.
operator()() [9/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 167 of file matpackVII.cc.
operator()() [10/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 315 of file matpackVII.cc.
operator()() [11/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 455 of file matpackVII.cc.
operator()() [12/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 812 of file matpackVII.cc.
operator()() [13/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 560 of file matpackVII.cc.
operator()() [14/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 938 of file matpackVII.cc.
operator()() [15/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1190 of file matpackVII.cc.
operator()() [16/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2184 of file matpackVII.cc.
operator()() [17/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 193 of file matpackVII.cc.
operator()() [18/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 350 of file matpackVII.cc.
operator()() [19/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 490 of file matpackVII.cc.
operator()() [20/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 854 of file matpackVII.cc.
operator()() [21/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 595 of file matpackVII.cc.
operator()() [22/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 980 of file matpackVII.cc.
operator()() [23/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1232 of file matpackVII.cc.
operator()() [24/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2143 of file matpackVII.cc.
operator()() [25/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 665 of file matpackVII.cc.
operator()() [26/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1064 of file matpackVII.cc.
operator()() [27/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1316 of file matpackVII.cc.
operator()() [28/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2061 of file matpackVII.cc.
operator()() [29/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1442 of file matpackVII.cc.
operator()() [30/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 1938 of file matpackVII.cc.
operator()() [31/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 1774 of file matpackVII.cc.
operator()() [32/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 2425 of file matpackVII.cc.
operator()() [33/128]
ConstTensor6View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 219 of file matpackVII.cc.
operator()() [34/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 385 of file matpackVII.cc.
operator()() [35/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 525 of file matpackVII.cc.
operator()() [36/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 896 of file matpackVII.cc.
operator()() [37/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 630 of file matpackVII.cc.
operator()() [38/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1022 of file matpackVII.cc.
operator()() [39/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1274 of file matpackVII.cc.
operator()() [40/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2102 of file matpackVII.cc.
operator()() [41/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 700 of file matpackVII.cc.
operator()() [42/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1106 of file matpackVII.cc.
operator()() [43/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1358 of file matpackVII.cc.
operator()() [44/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2020 of file matpackVII.cc.
operator()() [45/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1484 of file matpackVII.cc.
operator()() [46/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 1897 of file matpackVII.cc.
operator()() [47/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1733 of file matpackVII.cc.
operator()() [48/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2385 of file matpackVII.cc.
operator()() [49/128]
ConstTensor5View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 735 of file matpackVII.cc.
operator()() [50/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1148 of file matpackVII.cc.
operator()() [51/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1400 of file matpackVII.cc.
operator()() [52/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1979 of file matpackVII.cc.
operator()() [53/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1526 of file matpackVII.cc.
operator()() [54/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1856 of file matpackVII.cc.
operator()() [55/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1692 of file matpackVII.cc.
operator()() [56/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2345 of file matpackVII.cc.
operator()() [57/128]
ConstTensor4View ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1568 of file matpackVII.cc.
operator()() [58/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1815 of file matpackVII.cc.
operator()() [59/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1651 of file matpackVII.cc.
operator()() [60/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2305 of file matpackVII.cc.
operator()() [61/128]
ConstTensor3View ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1610 of file matpackVII.cc.
operator()() [62/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2265 of file matpackVII.cc.
operator()() [63/128]
ConstMatrixView ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2225 of file matpackVII.cc.
operator()() [64/128]
ConstVectorView ConstTensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 2465 of file matpackVII.cc.
operator()() [65/128]
ConstTensor6View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 76 of file matpackVII.cc.
operator()() [66/128]
ConstTensor5View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 101 of file matpackVII.cc.
operator()() [67/128]
ConstTensor5View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 127 of file matpackVII.cc.
operator()() [68/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 258 of file matpackVII.cc.
operator()() [69/128]
ConstTensor5View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 153 of file matpackVII.cc.
operator()() [70/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 293 of file matpackVII.cc.
operator()() [71/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 433 of file matpackVII.cc.
operator()() [72/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 791 of file matpackVII.cc.
operator()() [73/128]
ConstTensor5View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 179 of file matpackVII.cc.
operator()() [74/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 328 of file matpackVII.cc.
operator()() [75/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 468 of file matpackVII.cc.
operator()() [76/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 833 of file matpackVII.cc.
operator()() [77/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 573 of file matpackVII.cc.
operator()() [78/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 959 of file matpackVII.cc.
operator()() [79/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1211 of file matpackVII.cc.
operator()() [80/128]
ConstMatrixView ConstTensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2204 of file matpackVII.cc.
operator()() [81/128]
ConstTensor5View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 205 of file matpackVII.cc.
operator()() [82/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 363 of file matpackVII.cc.
operator()() [83/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 503 of file matpackVII.cc.
operator()() [84/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 875 of file matpackVII.cc.
operator()() [85/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 608 of file matpackVII.cc.
operator()() [86/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1001 of file matpackVII.cc.
operator()() [87/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1253 of file matpackVII.cc.
operator()() [88/128]
ConstMatrixView ConstTensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2163 of file matpackVII.cc.
operator()() [89/128]
ConstTensor4View ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 678 of file matpackVII.cc.
operator()() [90/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1085 of file matpackVII.cc.
operator()() [91/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1337 of file matpackVII.cc.
operator()() [92/128]
ConstMatrixView ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2081 of file matpackVII.cc.
operator()() [93/128]
ConstTensor3View ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1463 of file matpackVII.cc.
operator()() [94/128]
ConstMatrixView ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 1958 of file matpackVII.cc.
operator()() [95/128]
ConstMatrixView ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 1794 of file matpackVII.cc.
operator()() [96/128]
ConstVectorView ConstTensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 2445 of file matpackVII.cc.
operator()() [97/128]
ConstTensor5View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 231 of file matpackVII.cc.
operator()() [98/128]
ConstTensor4View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 398 of file matpackVII.cc.
operator()() [99/128]
ConstTensor4View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 538 of file matpackVII.cc.
operator()() [100/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 917 of file matpackVII.cc.
operator()() [101/128]
ConstTensor4View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 643 of file matpackVII.cc.
operator()() [102/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1043 of file matpackVII.cc.
operator()() [103/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1295 of file matpackVII.cc.
operator()() [104/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2122 of file matpackVII.cc.
operator()() [105/128]
ConstTensor4View ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 713 of file matpackVII.cc.
operator()() [106/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1127 of file matpackVII.cc.
operator()() [107/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1379 of file matpackVII.cc.
operator()() [108/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2040 of file matpackVII.cc.
operator()() [109/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1505 of file matpackVII.cc.
operator()() [110/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 1917 of file matpackVII.cc.
operator()() [111/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1753 of file matpackVII.cc.
operator()() [112/128]
ConstVectorView ConstTensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2405 of file matpackVII.cc.
operator()() [113/128]
ConstTensor4View ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 748 of file matpackVII.cc.
operator()() [114/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1169 of file matpackVII.cc.
operator()() [115/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1421 of file matpackVII.cc.
operator()() [116/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1999 of file matpackVII.cc.
operator()() [117/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1547 of file matpackVII.cc.
operator()() [118/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1876 of file matpackVII.cc.
operator()() [119/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1712 of file matpackVII.cc.
operator()() [120/128]
ConstVectorView ConstTensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2365 of file matpackVII.cc.
operator()() [121/128]
ConstTensor3View ConstTensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1589 of file matpackVII.cc.
operator()() [122/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1835 of file matpackVII.cc.
operator()() [123/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1671 of file matpackVII.cc.
operator()() [124/128]
ConstVectorView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2325 of file matpackVII.cc.
operator()() [125/128]
ConstMatrixView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1630 of file matpackVII.cc.
operator()() [126/128]
ConstVectorView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2285 of file matpackVII.cc.
operator()() [127/128]
ConstVectorView ConstTensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2245 of file matpackVII.cc.
operator()() [128/128]
Numeric ConstTensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const inline
Definition at line 1198 of file matpackVII.h.
operator=() [1/2]
ConstTensor7View& ConstTensor7View::operator= (const ConstTensor7View &) default
operator=() [2/2]
ConstTensor7View& ConstTensor7View::operator= (ConstTensor7View &&) default
Friends And Related Function Documentation
Tensor7View
friend class Tensor7View friend
Definition at line 1225 of file matpackVII.h.
Member Data Documentation
mbr
Range ConstTensor7View::mbr {0, 0, 1} protected
The book range of mdata that is actually used.
Definition at line 1266 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), nbooks(), Tensor7View::operator=(), and swap().
mcr
Range ConstTensor7View::mcr {0, 0, 1} protected
The column range of mdata that is actually used.
Definition at line 1272 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), ncols(), Tensor7View::operator=(), and swap().
mdata
Numeric* ConstTensor7View::mdata {nullptr} protected
Pointer to the plain C array that holds the data.
Definition at line 1274 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), Tensor7::operator=(), swap(), Tensor7::Tensor7(), and Tensor7::~Tensor7().
mlr
Range ConstTensor7View::mlr {0, 0, 1} protected
The library range of mdata that is actually used.
Definition at line 1260 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), nlibraries(), Tensor7View::operator=(), and swap().
mpr
Range ConstTensor7View::mpr {0, 0, 1} protected
The page range of mdata that is actually used.
Definition at line 1268 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), npages(), Tensor7View::operator=(), and swap().
mrr
Range ConstTensor7View::mrr {0, 0, 1} protected
The row range of mdata that is actually used.
Definition at line 1270 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), nrows(), Tensor7View::operator=(), and swap().
msr
Range ConstTensor7View::msr {0, 0, 1} protected
The shelf range of mdata that is actually used.
Definition at line 1264 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), nshelves(), Tensor7View::operator=(), and swap().
mvr
Range ConstTensor7View::mvr {0, 0, 1} protected
The vitrine range of mdata that is actually used.
Definition at line 1262 of file matpackVII.h.
Referenced by Tensor7View::begin(), begin(), Tensor7View::end(), end(), Tensor7View::get_c_array(), nvitrines(), Tensor7View::operator=(), and swap().
The documentation for this class was generated from the following files:
matpackVII.h
matpackVII.cc