ARTS: ARTS::Var::ArrayOfArrayOfGriddedField3 Class Reference
ARTS::Var::ArrayOfArrayOfGriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfGriddedField3 () noexcept
ArrayOfArrayOfGriddedField3 (std::size_t i, void *x) noexcept
~ArrayOfArrayOfGriddedField3 () noexcept
ArrayOfArrayOfGriddedField3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
ArrayOfArrayOfGriddedField3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfGriddedField3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 244 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::ArrayOfArrayOfGriddedField3::type = Group::ArrayOfArrayOfGriddedField3 private
Definition at line 245 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfGriddedField3() [1/3]
ARTS::Var::ArrayOfArrayOfGriddedField3::ArrayOfArrayOfGriddedField3 () inline noexcept
Definition at line 249 of file autoarts.h.
ArrayOfArrayOfGriddedField3() [2/3]
ARTS::Var::ArrayOfArrayOfGriddedField3::ArrayOfArrayOfGriddedField3 (std::size_t i, void * x) inline noexcept
Definition at line 250 of file autoarts.h.
~ArrayOfArrayOfGriddedField3()
ARTS::Var::ArrayOfArrayOfGriddedField3::~ArrayOfArrayOfGriddedField3 () inline noexcept
Definition at line 251 of file autoarts.h.
ArrayOfArrayOfGriddedField3() [3/3]
ARTS::Var::ArrayOfArrayOfGriddedField3::ArrayOfArrayOfGriddedField3 (const type & val) inline noexcept
Definition at line 252 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfGriddedField3::islast () const inline noexcept
Definition at line 258 of file autoarts.h.
Referenced by ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Var::ArrayOfPropagationMatrix::value(), and ARTS::Method::WriteXML().
isnull()
bool ARTS::Var::ArrayOfArrayOfGriddedField3::isnull () const inline noexcept
Definition at line 257 of file autoarts.h.
Referenced by ARTS::Var::ArrayOfPropagationMatrix::value().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfGriddedField3::name () const inline noexcept
Definition at line 259 of file autoarts.h.
operator=()
ArrayOfArrayOfGriddedField3& ARTS::Var::ArrayOfArrayOfGriddedField3::operator= (const type & t) inline noexcept
Definition at line 255 of file autoarts.h.
pos()
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField3::pos () const inline noexcept
Definition at line 256 of file autoarts.h.
value() [1/2]
const type& ARTS::Var::ArrayOfArrayOfGriddedField3::value () const inline noexcept
Definition at line 254 of file autoarts.h.
value() [2/2]
type& ARTS::Var::ArrayOfArrayOfGriddedField3::value () inline noexcept
Definition at line 253 of file autoarts.h.
Referenced by ARTS::AgendaMethod::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::IndexSetToLast(), and ARTS::Method::WriteXML().
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField3::p private
Definition at line 246 of file autoarts.h.
Referenced by ARTS::Var::ArrayOfQuantumIdentifier::pos(), and ARTS::Var::ArrayOfQuantumIdentifier::value().
v
type* ARTS::Var::ArrayOfArrayOfGriddedField3::v private
Definition at line 247 of file autoarts.h.
Referenced by ARTS::Var::ArrayOfQuantumIdentifier::ArrayOfQuantumIdentifier(), ARTS::Var::ArrayOfPropagationMatrix::name(), ARTS::Var::ArrayOfPropagationMatrix::pos(), and ARTS::Var::ArrayOfPropagationMatrix::value().
The documentation for this class was generated from the following file:
autoarts.h