ARTS: ARTS::Var::Ppath Class Reference
ARTS::Var::Ppath Class Reference
#include <autoarts.h>
Public Member Functions
Ppath () noexcept
Ppath (std::size_t i, void *x) noexcept
Ppath (const Group::Ppath &val) noexcept
~Ppath () noexcept
Group::Ppath & value () noexcept
const Group::Ppath & value () const noexcept
Ppath & operator= (const Group::Ppath &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Ppath * v
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3471 of file autoarts.h.
Constructor & Destructor Documentation
Ppath() [1/3]
ARTS::Var::Ppath::Ppath () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3476 of file autoarts.h.
Ppath() [2/3]
ARTS::Var::Ppath::Ppath (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3479 of file autoarts.h.
Ppath() [3/3]
ARTS::Var::Ppath::Ppath (const Group::Ppath & val) inline noexcept
Construct from Group::Ppath. Leaves islast() true and isnull() false
Definition at line 3482 of file autoarts.h.
~Ppath()
ARTS::Var::Ppath::~Ppath () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3485 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Ppath::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3503 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Ppath().
isnull()
bool ARTS::Var::Ppath::isnull () const inline noexcept
Return true if there is no data
Definition at line 3500 of file autoarts.h.
References v.
Referenced by ~Ppath().
name()
const Group::String& ARTS::Var::Ppath::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3506 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Ppath& ARTS::Var::Ppath::operator= (const Group::Ppath & t) inline noexcept
Set value from Group::Ppath. Works when isnull() is false
Definition at line 3494 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Ppath::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3497 of file autoarts.h.
References p.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), cloud_RT_surface(), ARTS::Agenda::Method::Copy(), diy_from_path_to_rgrids(), error_if_limb_ppath(), find_tanpoint(), geo_posEndOfPpath(), geo_posLowestAltitudeOfPpath(), geo_posWherePpathPassesZref(), get_iy_of_background(), ARTS::Agenda::Method::Ignore(), iyIndependentBeamApproximation(), iyRadarSingleScat(), iyTransmissionStandard(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_init_structure(), ppath_start_1d(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_stepRefractionBasic(), ppathCalcFromAltitude(), ppathFromRtePos2(), ppathPlaneParallel(), rte_pos_losMoveToStartOfPpath(), TangentPointExtract(), TangentPointPrint(), ARTS::Agenda::Method::Touch(), xml_read_from_stream(), xml_write_to_stream(), and yRadar().
value() [1/2]
const Group::Ppath& ARTS::Var::Ppath::value () const inline noexcept
Get value const-ref as Group::Ppath. Works when isnull() is false
Definition at line 3491 of file autoarts.h.
References v.
value() [2/2]
Group::Ppath& ARTS::Var::Ppath::value () inline noexcept
Get value ref as Group::Ppath. Works when isnull() is false
Definition at line 3488 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::TangentPointExtract(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::Ppath::p private
Definition at line 3472 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Ppath* ARTS::Var::Ppath::v private
Definition at line 3473 of file autoarts.h.
Referenced by isnull(), value(), and ~Ppath().
The documentation for this class was generated from the following file:
autoarts.h