ARTS: ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfTransmissionMatrix () noexcept
WorkspaceArrayOfArrayOfTransmissionMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfTransmissionMatrix () noexcept
WorkspaceArrayOfArrayOfTransmissionMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfTransmissionMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfTransmissionMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 476 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::type = Group::ArrayOfArrayOfTransmissionMatrix private
Definition at line 477 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfTransmissionMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::WorkspaceArrayOfArrayOfTransmissionMatrix () inline noexcept
Definition at line 481 of file autoarts.h.
WorkspaceArrayOfArrayOfTransmissionMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::WorkspaceArrayOfArrayOfTransmissionMatrix (std::size_t i, void * x) inline noexcept
Definition at line 482 of file autoarts.h.
~WorkspaceArrayOfArrayOfTransmissionMatrix()
ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::~WorkspaceArrayOfArrayOfTransmissionMatrix () inline noexcept
Definition at line 483 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfTransmissionMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::WorkspaceArrayOfArrayOfTransmissionMatrix (const type & val) inline noexcept
Definition at line 484 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::islast () const inline noexcept
Definition at line 490 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfTransmissionMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::isnull () const inline noexcept
Definition at line 489 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfTransmissionMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::name () const inline noexcept
Definition at line 491 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfTransmissionMatrix& ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::operator= (const type & t) inline noexcept
Definition at line 487 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::pos () const inline noexcept
Definition at line 488 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::value () const inline noexcept
Definition at line 486 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::value () inline noexcept
Definition at line 485 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::p private
Definition at line 478 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfTransmissionMatrix::v private
Definition at line 479 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfTransmissionMatrix().
The documentation for this class was generated from the following file:
autoarts.h