ARTS: ARTS::Var::WorkspaceArrayOfSingleScatteringData Class Reference
ARTS::Var::WorkspaceArrayOfSingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfSingleScatteringData () noexcept
WorkspaceArrayOfSingleScatteringData (std::size_t i, void *x) noexcept
~WorkspaceArrayOfSingleScatteringData () noexcept
WorkspaceArrayOfSingleScatteringData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfSingleScatteringData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfSingleScatteringData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 746 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfSingleScatteringData::type = Group::ArrayOfSingleScatteringData private
Definition at line 747 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfSingleScatteringData() [1/3]
ARTS::Var::WorkspaceArrayOfSingleScatteringData::WorkspaceArrayOfSingleScatteringData () inline noexcept
Definition at line 751 of file autoarts.h.
WorkspaceArrayOfSingleScatteringData() [2/3]
ARTS::Var::WorkspaceArrayOfSingleScatteringData::WorkspaceArrayOfSingleScatteringData (std::size_t i, void * x) inline noexcept
Definition at line 752 of file autoarts.h.
~WorkspaceArrayOfSingleScatteringData()
ARTS::Var::WorkspaceArrayOfSingleScatteringData::~WorkspaceArrayOfSingleScatteringData () inline noexcept
Definition at line 753 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfSingleScatteringData() [3/3]
ARTS::Var::WorkspaceArrayOfSingleScatteringData::WorkspaceArrayOfSingleScatteringData (const type & val) inline noexcept
Definition at line 754 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfSingleScatteringData::islast () const inline noexcept
Definition at line 760 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfSingleScatteringData().
isnull()
bool ARTS::Var::WorkspaceArrayOfSingleScatteringData::isnull () const inline noexcept
Definition at line 759 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfSingleScatteringData().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfSingleScatteringData::name () const inline noexcept
Definition at line 761 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfSingleScatteringData& ARTS::Var::WorkspaceArrayOfSingleScatteringData::operator= (const type & t) inline noexcept
Definition at line 757 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfSingleScatteringData::pos () const inline noexcept
Definition at line 758 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfSingleScatteringData::value () const inline noexcept
Definition at line 756 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfSingleScatteringData::value () inline noexcept
Definition at line 755 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfSingleScatteringData::p private
Definition at line 748 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfSingleScatteringData::v private
Definition at line 749 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfSingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h