ARTS: ARTS::Var::WorkspaceGriddedField3 Class Reference
ARTS::Var::WorkspaceGriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField3 () noexcept
WorkspaceGriddedField3 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField3 () noexcept
WorkspaceGriddedField3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1124 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField3::type = Group::GriddedField3 private
Definition at line 1125 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField3() [1/3]
ARTS::Var::WorkspaceGriddedField3::WorkspaceGriddedField3 () inline noexcept
Definition at line 1129 of file autoarts.h.
WorkspaceGriddedField3() [2/3]
ARTS::Var::WorkspaceGriddedField3::WorkspaceGriddedField3 (std::size_t i, void * x) inline noexcept
Definition at line 1130 of file autoarts.h.
~WorkspaceGriddedField3()
ARTS::Var::WorkspaceGriddedField3::~WorkspaceGriddedField3 () inline noexcept
Definition at line 1131 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField3() [3/3]
ARTS::Var::WorkspaceGriddedField3::WorkspaceGriddedField3 (const type & val) inline noexcept
Definition at line 1132 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField3::islast () const inline noexcept
Definition at line 1138 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::atm_fields_compactCreateFromField(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::lat_gridFromRawField(), ARTS::AgendaMethod::lon_gridFromRawField(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField3().
isnull()
bool ARTS::Var::WorkspaceGriddedField3::isnull () const inline noexcept
Definition at line 1137 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField3().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField3::name () const inline noexcept
Definition at line 1139 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField3& ARTS::Var::WorkspaceGriddedField3::operator= (const type & t) inline noexcept
Definition at line 1135 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField3::pos () const inline noexcept
Definition at line 1136 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::atm_fields_compactCreateFromField(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::lat_gridFromRawField(), ARTS::AgendaMethod::lon_gridFromRawField(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField3::value () const inline noexcept
Definition at line 1134 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField3::value () inline noexcept
Definition at line 1133 of file autoarts.h.
References v.
Referenced by ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::lon_gridFromRawField(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField3::p private
Definition at line 1126 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField3::v private
Definition at line 1127 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField3().
The documentation for this class was generated from the following file:
autoarts.h