ARTS: ARTS::Var::MapOfErrorCorrectedSuddenData Class Reference
ARTS::Var::MapOfErrorCorrectedSuddenData Class Reference
#include <autoarts.h>
Public Member Functions
MapOfErrorCorrectedSuddenData () noexcept
MapOfErrorCorrectedSuddenData (std::size_t i, void *x) noexcept
MapOfErrorCorrectedSuddenData (const Group::MapOfErrorCorrectedSuddenData &val) noexcept
~MapOfErrorCorrectedSuddenData () noexcept
Group::MapOfErrorCorrectedSuddenData & value () noexcept
const Group::MapOfErrorCorrectedSuddenData & value () const noexcept
MapOfErrorCorrectedSuddenData & operator= (const Group::MapOfErrorCorrectedSuddenData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::MapOfErrorCorrectedSuddenData * v
Friends
std::ostream & operator<< (std::ostream &os, const MapOfErrorCorrectedSuddenData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3431 of file autoarts.h.
Constructor & Destructor Documentation
MapOfErrorCorrectedSuddenData() [1/3]
ARTS::Var::MapOfErrorCorrectedSuddenData::MapOfErrorCorrectedSuddenData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3436 of file autoarts.h.
MapOfErrorCorrectedSuddenData() [2/3]
ARTS::Var::MapOfErrorCorrectedSuddenData::MapOfErrorCorrectedSuddenData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3439 of file autoarts.h.
MapOfErrorCorrectedSuddenData() [3/3]
ARTS::Var::MapOfErrorCorrectedSuddenData::MapOfErrorCorrectedSuddenData (const Group::MapOfErrorCorrectedSuddenData & val) inline noexcept
Construct from Group::MapOfErrorCorrectedSuddenData. Leaves islast() true and isnull() false
Definition at line 3442 of file autoarts.h.
~MapOfErrorCorrectedSuddenData()
ARTS::Var::MapOfErrorCorrectedSuddenData::~MapOfErrorCorrectedSuddenData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3445 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::MapOfErrorCorrectedSuddenData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3463 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~MapOfErrorCorrectedSuddenData().
isnull()
bool ARTS::Var::MapOfErrorCorrectedSuddenData::isnull () const inline noexcept
Return true if there is no data
Definition at line 3460 of file autoarts.h.
References v.
Referenced by ~MapOfErrorCorrectedSuddenData().
name()
const Group::String& ARTS::Var::MapOfErrorCorrectedSuddenData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3466 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
MapOfErrorCorrectedSuddenData& ARTS::Var::MapOfErrorCorrectedSuddenData::operator= (const Group::MapOfErrorCorrectedSuddenData & t) inline noexcept
Set value from Group::MapOfErrorCorrectedSuddenData. Works when isnull() is false
Definition at line 3454 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::MapOfErrorCorrectedSuddenData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3457 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::MapOfErrorCorrectedSuddenData& ARTS::Var::MapOfErrorCorrectedSuddenData::value () const inline noexcept
Get value const-ref as Group::MapOfErrorCorrectedSuddenData. Works when isnull() is false
Definition at line 3451 of file autoarts.h.
References v.
value() [2/2]
Group::MapOfErrorCorrectedSuddenData& ARTS::Var::MapOfErrorCorrectedSuddenData::value () inline noexcept
Get value ref as Group::MapOfErrorCorrectedSuddenData. Works when isnull() is false
Definition at line 3448 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const MapOfErrorCorrectedSuddenData & var) friend
Output to stream of internal variable
Definition at line 3469 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::MapOfErrorCorrectedSuddenData::p private
Definition at line 3432 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::MapOfErrorCorrectedSuddenData* ARTS::Var::MapOfErrorCorrectedSuddenData::v private
Definition at line 3433 of file autoarts.h.
Referenced by isnull(), value(), and ~MapOfErrorCorrectedSuddenData().
The documentation for this class was generated from the following file:
autoarts.h