ARTS: ARTS::Var::SpeciesAuxData Class Reference
ARTS::Var::SpeciesAuxData Class Reference
#include <autoarts.h>
Public Member Functions
SpeciesAuxData () noexcept
SpeciesAuxData (std::size_t i, void *x) noexcept
SpeciesAuxData (const Group::SpeciesAuxData &val) noexcept
~SpeciesAuxData () noexcept
Group::SpeciesAuxData & value () noexcept
const Group::SpeciesAuxData & value () const noexcept
SpeciesAuxData & operator= (const Group::SpeciesAuxData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::SpeciesAuxData * v
Friends
std::ostream & operator<< (std::ostream &os, const SpeciesAuxData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3845 of file autoarts.h.
Constructor & Destructor Documentation
SpeciesAuxData() [1/3]
ARTS::Var::SpeciesAuxData::SpeciesAuxData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3850 of file autoarts.h.
SpeciesAuxData() [2/3]
ARTS::Var::SpeciesAuxData::SpeciesAuxData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3853 of file autoarts.h.
SpeciesAuxData() [3/3]
ARTS::Var::SpeciesAuxData::SpeciesAuxData (const Group::SpeciesAuxData & val) inline noexcept
Construct from Group::SpeciesAuxData. Leaves islast() true and isnull() false
Definition at line 3856 of file autoarts.h.
~SpeciesAuxData()
ARTS::Var::SpeciesAuxData::~SpeciesAuxData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3859 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::SpeciesAuxData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3877 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~SpeciesAuxData().
isnull()
bool ARTS::Var::SpeciesAuxData::isnull () const inline noexcept
Return true if there is no data
Definition at line 3874 of file autoarts.h.
References v.
Referenced by ~SpeciesAuxData().
name()
const Group::String& ARTS::Var::SpeciesAuxData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3880 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
SpeciesAuxData& ARTS::Var::SpeciesAuxData::operator= (const Group::SpeciesAuxData & t) inline noexcept
Set value from Group::SpeciesAuxData. Works when isnull() is false
Definition at line 3868 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::SpeciesAuxData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3871 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::SpeciesAuxData& ARTS::Var::SpeciesAuxData::value () const inline noexcept
Get value const-ref as Group::SpeciesAuxData. Works when isnull() is false
Definition at line 3865 of file autoarts.h.
References v.
value() [2/2]
Group::SpeciesAuxData& ARTS::Var::SpeciesAuxData::value () inline noexcept
Get value ref as Group::SpeciesAuxData. Works when isnull() is false
Definition at line 3862 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SpeciesAuxData & var) friend
Output to stream of internal variable
Definition at line 3883 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::SpeciesAuxData::p private
Definition at line 3846 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::SpeciesAuxData* ARTS::Var::SpeciesAuxData::v private
Definition at line 3847 of file autoarts.h.
Referenced by isnull(), value(), and ~SpeciesAuxData().
The documentation for this class was generated from the following file:
autoarts.h