ARTS: ARTS::Var::Verbosity Class Reference
ARTS::Var::Verbosity Class Reference
#include <autoarts.h>
Public Member Functions
Verbosity () noexcept
Verbosity (std::size_t i, void *x) noexcept
Verbosity (const Group::Verbosity &val) noexcept
~Verbosity () noexcept
Group::Verbosity & value () noexcept
const Group::Verbosity & value () const noexcept
Verbosity & operator= (const Group::Verbosity &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Verbosity * v
Friends
std::ostream & operator<< (std::ostream &os, const Verbosity &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4600 of file autoarts.h.
Constructor & Destructor Documentation
Verbosity() [1/3]
ARTS::Var::Verbosity::Verbosity () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4605 of file autoarts.h.
Verbosity() [2/3]
ARTS::Var::Verbosity::Verbosity (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4608 of file autoarts.h.
Verbosity() [3/3]
ARTS::Var::Verbosity::Verbosity (const Group::Verbosity & val) inline noexcept
Construct from Group::Verbosity. Leaves islast() true and isnull() false
Definition at line 4611 of file autoarts.h.
~Verbosity()
ARTS::Var::Verbosity::~Verbosity () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4614 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Verbosity::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4632 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Verbosity().
isnull()
bool ARTS::Var::Verbosity::isnull () const inline noexcept
Return true if there is no data
Definition at line 4629 of file autoarts.h.
References v.
Referenced by ~Verbosity().
name()
const Group::String& ARTS::Var::Verbosity::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4635 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Verbosity& ARTS::Var::Verbosity::operator= (const Group::Verbosity & t) inline noexcept
Set value from Group::Verbosity. Works when isnull() is false
Definition at line 4623 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Verbosity::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4626 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Verbosity& ARTS::Var::Verbosity::value () const inline noexcept
Get value const-ref as Group::Verbosity. Works when isnull() is false
Definition at line 4620 of file autoarts.h.
References v.
value() [2/2]
Group::Verbosity& ARTS::Var::Verbosity::value () inline noexcept
Get value ref as Group::Verbosity. Works when isnull() is false
Definition at line 4617 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_cia_dataReadFromCIA(), ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetCutoff(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeType(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroring(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalization(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulation(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesDeleteWithLines(), ARTS::Method::abs_linesKeepBand(), ARTS::Method::abs_linesRemoveBand(), ARTS::Method::abs_linesReplaceWithLines(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetLineShapeType(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetMirroring(), ARTS::Method::abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetNormalization(), ARTS::Method::abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetPopulation(), ARTS::Method::abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetT0(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::abs_linesSetZeemanCoefficients(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), ARTS::Method::abs_nlteFromRaw(), ARTS::Method::abs_speciesAdd(), ARTS::Method::abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesSet(), ARTS::Method::AddZaAa(), ARTS::Method::AgendaExecute(), ARTS::Method::AgendaExecuteExclusive(), ARTS::Method::Append(), ARTS::Method::ArrayOfAgendaExecute(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfSpeciesTagSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Method::ArrayOfTimeNLinSpace(), ARTS::Method::ArrayOfTimeSetConstant(), ARTS::Method::atm_fields_compactCleanup(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::AtmRawRead(), ARTS::Method::backend_channel_responseFlat(), ARTS::Method::batch_atm_fields_compactCleanup(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::CIAInfo(), ARTS::Method::CIARecordReadFromFile(), ARTS::Method::cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudboxSetManually(), ARTS::Method::cloudboxSetManuallyAltitude(), ARTS::Method::Compare(), ARTS::Method::CompareRelative(), ARTS::Method::complex_refr_indexConstant(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), ARTS::Method::complex_refr_indexWaterLiebe93(), ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::DiffZaAa(), ARTS::Method::doit_za_grid_optCalc(), ARTS::Method::Duration(), ARTS::Method::ecs_dataSetMeanAir(), ARTS::Method::EnergyLevelMapSet(), ARTS::Method::Error(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::FlagOff(), ARTS::Method::FlagOn(), ARTS::Method::Flatten(), ARTS::Method::ForLoop(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::geo_posWherePpathPassesZref(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GetNumberOfThreads(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::IndexAdd(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexSet(), ARTS::Method::IndexSetToLast(), ARTS::Method::IndexStepDown(), ARTS::Method::IndexStepUp(), ARTS::init(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcSinefit(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::LocalTimeOffset(), ARTS::Method::lon_gridFromRawField(), ARTS::Method::MagRawRead(), ARTS::Method::Matrix1ColFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixCopySparse(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::MatrixFromCovarianceMatrix(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::Method::MatrixSet(), ARTS::Method::MatrixSetConstant(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussianByFWHM(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::nelemGet(), ARTS::Method::nlibrariesGet(), ARTS::Method::nlte_fieldFromRaw(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), ARTS::Method::NumericAdd(), ARTS::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::Method::NumericSet(), ARTS::Method::nvitrinesGet(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::PFromZSimple(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Method::RationalScale(), ARTS::Method::ReadNetCDF(), ARTS::Method::ReadXML(), ARTS::Method::ReadXMLIndexed(), ARTS::Method::Reduce(), ARTS::Method::refellipsoidForAzimuth(), ARTS::Method::refellipsoidOrbitPlane(), ARTS::Method::retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::rte_losSet(), ARTS::Method::rte_posSet(), ARTS::Method::rtp_nlteFromRaw(), ARTS::Method::ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::Select(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::SetNumberOfThreads(), ARTS::Method::Sleep(), ARTS::Method::SparseSparseMultiply(), ARTS::Method::StringSet(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::SurfaceFlatScalarReflectivity(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::TangentPointExtract(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::telsemSurfaceTypeLandSea(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3FromVector(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::TestTessem(), ARTS::Method::time_gridOffset(), ARTS::Method::time_stampsSort(), ARTS::Method::timeOffset(), ARTS::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::Trapz(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorAddVector(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorPower(), ARTS::Method::VectorScale(), ARTS::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorSubtractVector(), ARTS::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Method::vmr_fieldSetAllConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::WindRawRead(), ARTS::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Method::WriteMolTau(), ARTS::Method::WriteNetCDF(), ARTS::Method::WriteNetCDFIndexed(), ARTS::Method::WriteXML(), ARTS::Method::WriteXMLIndexed(), ARTS::Method::ybatchMaskOutsideMedianRange(), ARTS::Method::ybatchMetProfiles(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::yMaskOutsideMedianRange(), ARTS::Method::ySimpleSpectrometer(), and ARTS::Method::ZFromPSimple().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Verbosity & var) friend
Output to stream of internal variable
Definition at line 4638 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Verbosity::p private
Definition at line 4601 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Verbosity* ARTS::Var::Verbosity::v private
Definition at line 4602 of file autoarts.h.
Referenced by isnull(), value(), and ~Verbosity().
The documentation for this class was generated from the following file:
autoarts.h