ARTS: ArtsOut Class Reference
ArtsOut Class Reference
#include <messages.h>
Public Member Functions
ArtsOut (const int p, const Verbosity &v)
int get_priority () const
const Verbosity & get_verbosity () const
bool sufficient_priority () const
Does the current message have sufficient priority for output?
bool sufficient_priority_agenda () const
Does the current message have sufficient priority for agenda?
bool sufficient_priority_screen () const
Does the current message have sufficient priority for screen?
bool sufficient_priority_file () const
Does the current message have sufficient priority for file?
bool in_main_agenda () const
Are we in the main agenda?
Private Attributes
const Verbosity & verbosity
int priority
Detailed Description
Definition at line 87 of file messages.h.
Constructor & Destructor Documentation
ArtsOut()
ArtsOut::ArtsOut (const int p, const Verbosity & v) inline
Definition at line 89 of file messages.h.
Member Function Documentation
get_priority()
int ArtsOut::get_priority () const inline
Definition at line 91 of file messages.h.
References priority.
Referenced by operator<<().
get_verbosity()
const Verbosity& ArtsOut::get_verbosity () const inline
Definition at line 92 of file messages.h.
References verbosity.
Referenced by arts_exit_with_error_message().
in_main_agenda()
bool ArtsOut::in_main_agenda () const inline
Are we in the main agenda?
Returns
true if in main agenda, otherwise false.
Definition at line 131 of file messages.h.
References Verbosity::is_main_agenda(), and verbosity.
Referenced by sufficient_priority_agenda().
sufficient_priority()
bool ArtsOut::sufficient_priority () const inline
Does the current message have sufficient priority for output?
Returns
true if priority is sufficient, otherwise false.
Definition at line 98 of file messages.h.
References sufficient_priority_agenda(), sufficient_priority_file(), and sufficient_priority_screen().
sufficient_priority_agenda()
bool ArtsOut::sufficient_priority_agenda () const inline
Does the current message have sufficient priority for agenda?
Returns
true if priority is sufficient, otherwise false.
Definition at line 107 of file messages.h.
References Verbosity::get_agenda_verbosity(), in_main_agenda(), priority, and verbosity.
Referenced by operator<<(), and sufficient_priority().
sufficient_priority_file()
bool ArtsOut::sufficient_priority_file () const inline
Does the current message have sufficient priority for file?
Returns
true if priority is sufficient, otherwise false.
Definition at line 123 of file messages.h.
References Verbosity::get_file_verbosity(), priority, and verbosity.
Referenced by operator<<(), and sufficient_priority().
sufficient_priority_screen()
bool ArtsOut::sufficient_priority_screen () const inline
Does the current message have sufficient priority for screen?
Returns
true if priority is sufficient, otherwise false.
Definition at line 115 of file messages.h.
References Verbosity::get_screen_verbosity(), priority, and verbosity.
Referenced by operator<<(), and sufficient_priority().
Member Data Documentation
priority
int ArtsOut::priority private
Definition at line 135 of file messages.h.
Referenced by get_priority(), sufficient_priority_agenda(), sufficient_priority_file(), and sufficient_priority_screen().
verbosity
const Verbosity& ArtsOut::verbosity private
Definition at line 134 of file messages.h.
Referenced by get_verbosity(), in_main_agenda(), sufficient_priority_agenda(), sufficient_priority_file(), and sufficient_priority_screen().
The documentation for this class was generated from the following file:
messages.h