ARTS: ARTS::Var::WorkspaceArrayOfAbsorptionLines Class Reference
ARTS::Var::WorkspaceArrayOfAbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfAbsorptionLines () noexcept
WorkspaceArrayOfAbsorptionLines (std::size_t i, void *x) noexcept
~WorkspaceArrayOfAbsorptionLines () noexcept
WorkspaceArrayOfAbsorptionLines (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfAbsorptionLines & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfAbsorptionLines
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 152 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfAbsorptionLines::type = Group::ArrayOfAbsorptionLines private
Definition at line 153 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfAbsorptionLines() [1/3]
ARTS::Var::WorkspaceArrayOfAbsorptionLines::WorkspaceArrayOfAbsorptionLines () inline noexcept
Definition at line 157 of file autoarts.h.
WorkspaceArrayOfAbsorptionLines() [2/3]
ARTS::Var::WorkspaceArrayOfAbsorptionLines::WorkspaceArrayOfAbsorptionLines (std::size_t i, void * x) inline noexcept
Definition at line 158 of file autoarts.h.
~WorkspaceArrayOfAbsorptionLines()
ARTS::Var::WorkspaceArrayOfAbsorptionLines::~WorkspaceArrayOfAbsorptionLines () inline noexcept
Definition at line 159 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfAbsorptionLines() [3/3]
ARTS::Var::WorkspaceArrayOfAbsorptionLines::WorkspaceArrayOfAbsorptionLines (const type & val) inline noexcept
Definition at line 160 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfAbsorptionLines::islast () const inline noexcept
Definition at line 166 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_linesDeleteWithLines(), ARTS::AgendaMethod::abs_linesReplaceWithLines(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfAbsorptionLines().
isnull()
bool ARTS::Var::WorkspaceArrayOfAbsorptionLines::isnull () const inline noexcept
Definition at line 165 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfAbsorptionLines().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfAbsorptionLines::name () const inline noexcept
Definition at line 167 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfAbsorptionLines& ARTS::Var::WorkspaceArrayOfAbsorptionLines::operator= (const type & t) inline noexcept
Definition at line 163 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfAbsorptionLines::pos () const inline noexcept
Definition at line 164 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_linesDeleteWithLines(), ARTS::AgendaMethod::abs_linesReplaceWithLines(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfAbsorptionLines::value () const inline noexcept
Definition at line 162 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfAbsorptionLines::value () inline noexcept
Definition at line 161 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_linesDeleteWithLines(), ARTS::Method::abs_linesReplaceWithLines(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfAbsorptionLines::p private
Definition at line 154 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfAbsorptionLines::v private
Definition at line 155 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfAbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h