ARTS: WsvRecord Class Reference
WsvRecord Class Reference
This class contains all static information for one workspace variable.
#include <wsv_aux.h>
Public Member Functions
WsvRecord ()
Default constructor.
WsvRecord (const char name[], const char description[], const String &group, const bool implicit=false)
Initializing constructor.
WsvRecord (const char name[], const char description[], const Index group, const bool implicit=false)
Initializing constructor.
const String & Name () const
Name of this workspace variable.
const String & Description () const
A text describing this workspace variable.
Index Group () const
The wsv group to which this variable belongs.
bool Implicit () const
Returns true if the variable was automatically created.
Private Attributes
String mname
String mdescription
Index mgroup
bool mimplicit
Detailed Description
This class contains all static information for one workspace variable.
The program make_wsv_h.cc uses these records to generate the file wsv.h, which contains both the declaration of the wsv handles and the declaration of the workspace itself.
Author
Stefan Buehler
Definition at line 56 of file wsv_aux.h.
Constructor & Destructor Documentation
WsvRecord() [1/3]
WsvRecord::WsvRecord () inline
Default constructor.
Definition at line 59 of file wsv_aux.h.
WsvRecord() [2/3]
WsvRecord::WsvRecord (const char name[], const char description[], const String & group, const bool implicit = false) inline
Initializing constructor.
This is used by Workspace::define_wsv_data() to set the information for each workspace variable.
Definition at line 70 of file wsv_aux.h.
References get_wsv_group_id(), mgroup, and mname.
WsvRecord() [3/3]
WsvRecord::WsvRecord (const char name[], const char description[], const Index group, const bool implicit = false) inline
Initializing constructor.
This is used by the parser to create automatically allocated variables
Definition at line 91 of file wsv_aux.h.
Member Function Documentation
Description()
const String& WsvRecord::Description () const inline
A text describing this workspace variable.
Definition at line 104 of file wsv_aux.h.
References mdescription.
Referenced by get_variable(), and operator<<().
Group()
Index WsvRecord::Group () const inline
The wsv group to which this variable belongs.
Definition at line 106 of file wsv_aux.h.
References mgroup.
Referenced by get_variable(), and operator<<().
Implicit()
bool WsvRecord::Implicit () const inline
Returns true if the variable was automatically created.
Definition at line 108 of file wsv_aux.h.
References mimplicit.
Name()
const String& WsvRecord::Name () const inline
Name of this workspace variable.
Definition at line 102 of file wsv_aux.h.
References mname.
Referenced by get_variable(), and operator<<().
Member Data Documentation
mdescription
String WsvRecord::mdescription private
Definition at line 112 of file wsv_aux.h.
Referenced by Description().
mgroup
Index WsvRecord::mgroup private
Definition at line 113 of file wsv_aux.h.
Referenced by Group(), and WsvRecord().
mimplicit
bool WsvRecord::mimplicit private
Definition at line 114 of file wsv_aux.h.
Referenced by Implicit().
mname
String WsvRecord::mname private
Definition at line 111 of file wsv_aux.h.
Referenced by Name(), and WsvRecord().
The documentation for this class was generated from the following file:
wsv_aux.h