ARTS: ARTS::Var::GriddedField6 Class Reference
ARTS::Var::GriddedField6 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField6 () noexcept
GriddedField6 (std::size_t i, void *x) noexcept
GriddedField6 (const Group::GriddedField6 &val) noexcept
~GriddedField6 () noexcept
Group::GriddedField6 & value () noexcept
const Group::GriddedField6 & value () const noexcept
GriddedField6 & operator= (const Group::GriddedField6 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField6 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField6 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3142 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField6() [1/3]
ARTS::Var::GriddedField6::GriddedField6 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3147 of file autoarts.h.
GriddedField6() [2/3]
ARTS::Var::GriddedField6::GriddedField6 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3150 of file autoarts.h.
GriddedField6() [3/3]
ARTS::Var::GriddedField6::GriddedField6 (const Group::GriddedField6 & val) inline noexcept
Construct from Group::GriddedField6. Leaves islast() true and isnull() false
Definition at line 3153 of file autoarts.h.
~GriddedField6()
ARTS::Var::GriddedField6::~GriddedField6 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3156 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField6::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3174 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~GriddedField6().
isnull()
bool ARTS::Var::GriddedField6::isnull () const inline noexcept
Return true if there is no data
Definition at line 3171 of file autoarts.h.
References v.
Referenced by ~GriddedField6().
name()
const Group::String& ARTS::Var::GriddedField6::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3177 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField6& ARTS::Var::GriddedField6::operator= (const Group::GriddedField6 & t) inline noexcept
Set value from Group::GriddedField6. Works when isnull() is false
Definition at line 3165 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField6::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3168 of file autoarts.h.
References p.
value() [1/2]
const Group::GriddedField6& ARTS::Var::GriddedField6::value () const inline noexcept
Get value const-ref as Group::GriddedField6. Works when isnull() is false
Definition at line 3162 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField6& ARTS::Var::GriddedField6::value () inline noexcept
Get value ref as Group::GriddedField6. Works when isnull() is false
Definition at line 3159 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField6 & var) friend
Output to stream of internal variable
Definition at line 3180 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField6::p private
Definition at line 3143 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField6* ARTS::Var::GriddedField6::v private
Definition at line 3144 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField6().
The documentation for this class was generated from the following file:
autoarts.h