ARTS: ARTS::Var::ArrayOfArrayOfAbsorptionLines Class Reference
ARTS::Var::ArrayOfArrayOfAbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfAbsorptionLines () noexcept
ArrayOfArrayOfAbsorptionLines (std::size_t i, void *x) noexcept
ArrayOfArrayOfAbsorptionLines (const Group::ArrayOfArrayOfAbsorptionLines &val) noexcept
~ArrayOfArrayOfAbsorptionLines () noexcept
Group::ArrayOfArrayOfAbsorptionLines & value () noexcept
const Group::ArrayOfArrayOfAbsorptionLines & value () const noexcept
ArrayOfArrayOfAbsorptionLines & operator= (const Group::ArrayOfArrayOfAbsorptionLines &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfAbsorptionLines * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfAbsorptionLines &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 512 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfAbsorptionLines() [1/3]
ARTS::Var::ArrayOfArrayOfAbsorptionLines::ArrayOfArrayOfAbsorptionLines () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 517 of file autoarts.h.
ArrayOfArrayOfAbsorptionLines() [2/3]
ARTS::Var::ArrayOfArrayOfAbsorptionLines::ArrayOfArrayOfAbsorptionLines (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 520 of file autoarts.h.
ArrayOfArrayOfAbsorptionLines() [3/3]
ARTS::Var::ArrayOfArrayOfAbsorptionLines::ArrayOfArrayOfAbsorptionLines (const Group::ArrayOfArrayOfAbsorptionLines & val) inline noexcept
Construct from Group::ArrayOfArrayOfAbsorptionLines. Leaves islast() true and isnull() false
Definition at line 523 of file autoarts.h.
~ArrayOfArrayOfAbsorptionLines()
ARTS::Var::ArrayOfArrayOfAbsorptionLines::~ArrayOfArrayOfAbsorptionLines () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 526 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfAbsorptionLines::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 544 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfAbsorptionLines().
isnull()
bool ARTS::Var::ArrayOfArrayOfAbsorptionLines::isnull () const inline noexcept
Return true if there is no data
Definition at line 541 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfAbsorptionLines().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfAbsorptionLines::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 547 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfAbsorptionLines& ARTS::Var::ArrayOfArrayOfAbsorptionLines::operator= (const Group::ArrayOfArrayOfAbsorptionLines & t) inline noexcept
Set value from Group::ArrayOfArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 535 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfAbsorptionLines::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 538 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfAbsorptionLines& ARTS::Var::ArrayOfArrayOfAbsorptionLines::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 532 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfAbsorptionLines& ARTS::Var::ArrayOfArrayOfAbsorptionLines::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 529 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfAbsorptionLines & var) friend
Output to stream of internal variable
Definition at line 550 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfAbsorptionLines::p private
Definition at line 513 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfAbsorptionLines* ARTS::Var::ArrayOfArrayOfAbsorptionLines::v private
Definition at line 514 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfAbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h