ARTS: ARTS::Var::ArrayOfPropagationMatrix Class Reference
ARTS::Var::ArrayOfPropagationMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfPropagationMatrix () noexcept
ArrayOfPropagationMatrix (std::size_t i, void *x) noexcept
ArrayOfPropagationMatrix (const Group::ArrayOfPropagationMatrix &val) noexcept
~ArrayOfPropagationMatrix () noexcept
Group::ArrayOfPropagationMatrix & value () noexcept
const Group::ArrayOfPropagationMatrix & value () const noexcept
ArrayOfPropagationMatrix & operator= (const Group::ArrayOfPropagationMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfPropagationMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfPropagationMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1779 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfPropagationMatrix() [1/3]
ARTS::Var::ArrayOfPropagationMatrix::ArrayOfPropagationMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1784 of file autoarts.h.
ArrayOfPropagationMatrix() [2/3]
ARTS::Var::ArrayOfPropagationMatrix::ArrayOfPropagationMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1787 of file autoarts.h.
ArrayOfPropagationMatrix() [3/3]
ARTS::Var::ArrayOfPropagationMatrix::ArrayOfPropagationMatrix (const Group::ArrayOfPropagationMatrix & val) inline noexcept
Construct from Group::ArrayOfPropagationMatrix. Leaves islast() true and isnull() false
Definition at line 1790 of file autoarts.h.
~ArrayOfPropagationMatrix()
ARTS::Var::ArrayOfPropagationMatrix::~ArrayOfPropagationMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1793 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfPropagationMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1811 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfPropagationMatrix().
isnull()
bool ARTS::Var::ArrayOfPropagationMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 1808 of file autoarts.h.
References v.
Referenced by ~ArrayOfPropagationMatrix().
name()
const Group::String& ARTS::Var::ArrayOfPropagationMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1814 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfPropagationMatrix& ARTS::Var::ArrayOfPropagationMatrix::operator= (const Group::ArrayOfPropagationMatrix & t) inline noexcept
Set value from Group::ArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 1802 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfPropagationMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1805 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfPropagationMatrix& ARTS::Var::ArrayOfPropagationMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 1799 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfPropagationMatrix& ARTS::Var::ArrayOfPropagationMatrix::value () inline noexcept
Get value ref as Group::ArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 1796 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfPropagationMatrix & var) friend
Output to stream of internal variable
Definition at line 1817 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfPropagationMatrix::p private
Definition at line 1780 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfPropagationMatrix* ARTS::Var::ArrayOfPropagationMatrix::v private
Definition at line 1781 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfPropagationMatrix().
The documentation for this class was generated from the following file:
autoarts.h