ARTS: ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfRadiationVector () noexcept
WorkspaceArrayOfArrayOfRadiationVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfRadiationVector () noexcept
WorkspaceArrayOfArrayOfRadiationVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfRadiationVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfRadiationVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 314 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::type = Group::ArrayOfArrayOfRadiationVector private
Definition at line 315 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfRadiationVector() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::WorkspaceArrayOfArrayOfRadiationVector () inline noexcept
Definition at line 319 of file autoarts.h.
WorkspaceArrayOfArrayOfRadiationVector() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::WorkspaceArrayOfArrayOfRadiationVector (std::size_t i, void * x) inline noexcept
Definition at line 320 of file autoarts.h.
~WorkspaceArrayOfArrayOfRadiationVector()
ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::~WorkspaceArrayOfArrayOfRadiationVector () inline noexcept
Definition at line 321 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfRadiationVector() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::WorkspaceArrayOfArrayOfRadiationVector (const type & val) inline noexcept
Definition at line 322 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::islast () const inline noexcept
Definition at line 328 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfRadiationVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::isnull () const inline noexcept
Definition at line 327 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfRadiationVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::name () const inline noexcept
Definition at line 329 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfRadiationVector& ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::operator= (const type & t) inline noexcept
Definition at line 325 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::pos () const inline noexcept
Definition at line 326 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::value () const inline noexcept
Definition at line 324 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::value () inline noexcept
Definition at line 323 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::p private
Definition at line 316 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfRadiationVector::v private
Definition at line 317 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfRadiationVector().
The documentation for this class was generated from the following file:
autoarts.h