ARTS: ARTS::Var::Tensor5 Class Reference
ARTS::Var::Tensor5 Class Reference
#include <autoarts.h>
Public Member Functions
Tensor5 () noexcept
Tensor5 (std::size_t i, void *x) noexcept
Tensor5 (const Group::Tensor5 &val) noexcept
~Tensor5 () noexcept
Group::Tensor5 & value () noexcept
const Group::Tensor5 & value () const noexcept
Tensor5 & operator= (const Group::Tensor5 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Tensor5 * v
Friends
std::ostream & operator<< (std::ostream &os, const Tensor5 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4228 of file autoarts.h.
Constructor & Destructor Documentation
Tensor5() [1/3]
ARTS::Var::Tensor5::Tensor5 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4233 of file autoarts.h.
Tensor5() [2/3]
ARTS::Var::Tensor5::Tensor5 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4236 of file autoarts.h.
Tensor5() [3/3]
ARTS::Var::Tensor5::Tensor5 (const Group::Tensor5 & val) inline noexcept
Construct from Group::Tensor5. Leaves islast() true and isnull() false
Definition at line 4239 of file autoarts.h.
~Tensor5()
ARTS::Var::Tensor5::~Tensor5 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4242 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Tensor5::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4260 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Method::Flatten(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Agenda::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Method::Tensor5Scale(), ARTS::Agenda::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Agenda::Method::Tensor5SetConstant(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Tensor5().
isnull()
bool ARTS::Var::Tensor5::isnull () const inline noexcept
Return true if there is no data
Definition at line 4257 of file autoarts.h.
References v.
Referenced by ~Tensor5().
name()
const Group::String& ARTS::Var::Tensor5::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4263 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
Tensor5& ARTS::Var::Tensor5::operator= (const Group::Tensor5 & t) inline noexcept
Set value from Group::Tensor5. Works when isnull() is false
Definition at line 4251 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Tensor5::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4254 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::RadiationFieldSpectralIntegrate(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::Tensor5Scale(), ARTS::Agenda::Method::Tensor5SetConstant(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Tensor5& ARTS::Var::Tensor5::value () const inline noexcept
Get value const-ref as Group::Tensor5. Works when isnull() is false
Definition at line 4248 of file autoarts.h.
References v.
value() [2/2]
Group::Tensor5& ARTS::Var::Tensor5::value () inline noexcept
Get value ref as Group::Tensor5. Works when isnull() is false
Definition at line 4245 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Tensor5 & var) friend
Output to stream of internal variable
Definition at line 4266 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Tensor5::p private
Definition at line 4229 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Tensor5* ARTS::Var::Tensor5::v private
Definition at line 4230 of file autoarts.h.
Referenced by isnull(), value(), and ~Tensor5().
The documentation for this class was generated from the following file:
autoarts.h