ARTS: VectorView Class Reference
VectorView Class Reference
The VectorView class.
#include <matpackI.h>
Public Types
typedef Iterator1D iterator
Public Types inherited from ConstVectorView
typedef ConstIterator1D const_iterator
Public Member Functions
constexpr VectorView (const VectorView &)=default
VectorView (const Vector &)
Bail out immediately if somebody tries to create a VectorView from a const Vector.
VectorView (Vector &v) ARTS_NOEXCEPT
Create VectorView from a Vector.
Numeric & operator[] (Index n) ARTS_NOEXCEPT
Plain Index operator.
Numeric & get (Index n) ARTS_NOEXCEPT
Get element implementation without assertions.
VectorView operator[] (const Range &r) ARTS_NOEXCEPT
Index operator for subrange.
Iterator1D begin () ARTS_NOEXCEPT
Return iterator to first element.
Iterator1D end () ARTS_NOEXCEPT
Return iterator behind last element.
VectorView & operator= (const ConstVectorView &v)
Assignment operator.
VectorView & operator= (const VectorView &v)
Assignment from VectorView to VectorView.
VectorView & operator= (const Vector &v)
Assignment from Vector.
VectorView & operator= (const Array< Numeric > &v)
Assignment operator from Array<Numeric>.
VectorView & operator= (Numeric x)
Assigning a scalar to a VectorView will set all elements to this value.
VectorView operator*= (Numeric x) ARTS_NOEXCEPT
Multiplication by scalar.
VectorView operator/= (Numeric x) ARTS_NOEXCEPT
Division by scalar.
VectorView operator+= (Numeric x) ARTS_NOEXCEPT
Addition of scalar.
VectorView operator-= (Numeric x) ARTS_NOEXCEPT
Subtraction of scalar.
VectorView operator*= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise multiplication by another vector.
VectorView operator/= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise division by another vector.
VectorView operator+= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise addition of another vector.
VectorView operator-= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise subtraction of another vector.
operator MatrixView () ARTS_NOEXCEPT
Conversion to 1 column matrix.
const Numeric * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array, const-version.
Numeric * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array, non-const version.
virtual ~VectorView ()=default
Destructor.
VectorView (Numeric &a) ARTS_NOEXCEPT
A special constructor, which allows to make a VectorView from a scalar.
ConstIterator1D begin () const ARTS_NOEXCEPT
Return const iterator to first element.
ConstIterator1D end () const ARTS_NOEXCEPT
Return const iterator behind last element.
Numeric get (Index n) const ARTS_NOEXCEPT
Get element implementation without assertions.
Public Member Functions inherited from ConstVectorView
constexpr ConstVectorView (const ConstVectorView &)=default
constexpr ConstVectorView (ConstVectorView &&)=default
ConstVectorView & operator= (const ConstVectorView &)=default
ConstVectorView & operator= (ConstVectorView &&)=default
bool empty () const ARTS_NOEXCEPT
Returns true if variable size is zero.
Index nelem () const ARTS_NOEXCEPT
Returns the number of elements.
Index size () const ARTS_NOEXCEPT
Numeric sum () const ARTS_NOEXCEPT
The sum of all elements of a Vector.
Numeric operator[] (Index n) const ARTS_NOEXCEPT
Plain const index operator.
Numeric get (Index n) const ARTS_NOEXCEPT
Get element implementation without assertions.
ConstVectorView operator[] (const Range &r) const ARTS_NOEXCEPT
Const index operator for subrange.
ConstIterator1D begin () const ARTS_NOEXCEPT
Return const iterator to first element.
ConstIterator1D end () const ARTS_NOEXCEPT
Return const iterator behind last element.
operator ConstMatrixView () const
Conversion to const 1 column matrix.
virtual ~ConstVectorView ()=default
Destructor.
ConstVectorView (const Numeric &a) ARTS_NOEXCEPT
A special constructor, which allows to make a ConstVectorView from a scalar.
Protected Member Functions
VectorView ()=default
VectorView (Numeric *data, const Range &range) ARTS_NOEXCEPT
Explicit constructor.
VectorView (Numeric *data, const Range &p, const Range &n) ARTS_NOEXCEPT
Recursive constructor.
Protected Member Functions inherited from ConstVectorView
ConstVectorView ()=default
ConstVectorView (Numeric *data, const Range &range) ARTS_NOEXCEPT
Explicit constructor.
ConstVectorView (Numeric *data, const Range &p, const Range &n) ARTS_NOEXCEPT
Recursive constructor.
Friends
class ConstIterator2D
class Iterator2D
class MatrixView
class Tensor3View
class Tensor4View
class Tensor5View
class Tensor6View
class Tensor7View
class ComplexVectorView
Additional Inherited Members
Protected Attributes inherited from ConstVectorView
Range mrange {0, 0}
The range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The VectorView class.
This contains the main implementation of a vector. The class Vector is just a special case of subvector which also allocates storage.
Unfortunately, names of element functions of derived classes hide the names of the original class, even if the arguments are different. This means that we have to redefine those element functions that can have different arguments, for example the constant index operators and iterators.
Definition at line 618 of file matpackI.h.
Member Typedef Documentation
iterator
typedef Iterator1D VectorView::iterator
Definition at line 636 of file matpackI.h.
Constructor & Destructor Documentation
VectorView() [1/7]
constexpr VectorView::VectorView (const VectorView &) constexpr default
VectorView() [2/7]
VectorView::VectorView (const Vector &)
Bail out immediately if somebody tries to create a VectorView from a const Vector.
Definition at line 127 of file matpackI.cc.
References ARTS_ASSERT.
VectorView() [3/7]
VectorView::VectorView (Vector & v)
Create VectorView from a Vector.
Definition at line 137 of file matpackI.cc.
References v.
~VectorView()
virtual VectorView::~VectorView () virtual default
Destructor.
VectorView() [4/7]
VectorView::VectorView (Numeric & a)
A special constructor, which allows to make a VectorView from a scalar.
Definition at line 288 of file matpackI.cc.
VectorView() [5/7]
VectorView::VectorView () protected default
VectorView() [6/7]
VectorView::VectorView (Numeric * data, const Range & range) protected
Explicit constructor.
This one is used by Vector to initialize its own VectorView part.
Definition at line 292 of file matpackI.cc.
VectorView() [7/7]
VectorView::VectorView (Numeric * data, const Range & p, const Range & n) protected
Recursive constructor.
This is used to construct sub ranges from sub ranges. That means that the new range has to be interpreted relative to the original range. The new range may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
[in] *data The actual data.
[in] p Previous range.
[in] n New Range.
Definition at line 297 of file matpackI.cc.
Member Function Documentation
begin() [1/2]
Iterator1D VectorView::begin ()
Return iterator to first element.
Definition at line 146 of file matpackI.cc.
References ConstVectorView::mdata, ConstVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by Raw::Average::nanstd(), MatrixView::operator*=(), MatrixView::operator+=(), MatrixView::operator-=(), MatrixView::operator/=(), operator=(), Vector::operator=(), Raw::Average::std(), test46(), transform(), and Vector::Vector().
begin() [2/2]
ConstIterator1D ConstVectorView::begin
Return const iterator to first element.
Definition at line 536 of file matpackI.cc.
end() [1/2]
Iterator1D VectorView::end ()
Return iterator behind last element.
Definition at line 150 of file matpackI.cc.
References ConstVectorView::mdata, Range::mextent, ConstVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by Raw::Average::nanstd(), MatrixView::operator*=(), MatrixView::operator+=(), MatrixView::operator-=(), MatrixView::operator/=(), operator=(), Raw::Average::std(), and test46().
end() [2/2]
ConstIterator1D ConstVectorView::end
Return const iterator behind last element.
Definition at line 539 of file matpackI.cc.
get() [1/2]
Numeric& VectorView::get (Index n) inline
Get element implementation without assertions.
Definition at line 646 of file matpackI.h.
References ConstVectorView::mdata, ConstVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by interpweights().
get() [2/2]
Numeric ConstVectorView::get inline
Get element implementation without assertions.
Definition at line 522 of file matpackI.h.
Referenced by MatrixView::operator()(), ConstMatrixView::operator()(), and operator[]().
get_c_array() [1/2]
Numeric * VectorView::get_c_array ()
Conversion to plain C-array, non-const version.
This function returns a pointer to the raw data. It fails if the VectorView is not pointing to the beginning of a Vector or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 281 of file matpackI.cc.
References ARTS_ASSERT, ConstVectorView::mdata, ConstVectorView::mrange, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Numeric * VectorView::get_c_array () const
Conversion to plain C-array, const-version.
This function returns a pointer to the raw data. It fails if the VectorView is not pointing to the beginning of a Vector or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 274 of file matpackI.cc.
References ARTS_ASSERT, ConstVectorView::mdata, ConstVectorView::mrange, Range::mstart, and Range::mstride.
Referenced by diagonalize(), fastem(), Reduce(), tmatrix_random_orientation(), and tmatrix_tmd_test().
operator MatrixView()
VectorView::operator MatrixView ()
Conversion to 1 column matrix.
Definition at line 265 of file matpackI.cc.
operator*=() [1/2]
VectorView VectorView::operator*= (const ConstVectorView & x)
Element-vise multiplication by another vector.
Definition at line 217 of file matpackI.cc.
References ARTS_ASSERT, Absorption::nelem(), and ARTS::Var::x().
operator*=() [2/2]
VectorView VectorView::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 193 of file matpackI.cc.
operator+=() [1/2]
VectorView VectorView::operator+= (const ConstVectorView & x)
Element-vise addition of another vector.
Definition at line 241 of file matpackI.cc.
References ARTS_ASSERT, Absorption::nelem(), and ARTS::Var::x().
operator+=() [2/2]
VectorView VectorView::operator+= (Numeric x)
Addition of scalar.
Definition at line 205 of file matpackI.cc.
operator-=() [1/2]
VectorView VectorView::operator-= (const ConstVectorView & x)
Element-vise subtraction of another vector.
Definition at line 253 of file matpackI.cc.
References ARTS_ASSERT, Absorption::nelem(), and ARTS::Var::x().
operator-=() [2/2]
VectorView VectorView::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 211 of file matpackI.cc.
operator/=() [1/2]
VectorView VectorView::operator/= (const ConstVectorView & x)
Element-vise division by another vector.
Definition at line 229 of file matpackI.cc.
References ARTS_ASSERT, Absorption::nelem(), and ARTS::Var::x().
operator/=() [2/2]
VectorView VectorView::operator/= (Numeric x)
Division by scalar.
Definition at line 199 of file matpackI.cc.
operator=() [1/5]
VectorView & VectorView::operator= (const Array< Numeric > & v)
Assignment operator from Array<Numeric>.
This copies the data from an Array<Numeric> to this VectorView. Dimensions must agree! Resizing would destroy the selection that we might have done in this VectorView by setting its range.
Array<Numeric> can be useful to collect things in, because there is a .push_back method for it. Then, after collecting we usually have to transfer the content to a Vector. With this assignment operator that's easy.
Definition at line 1652 of file matpackI.cc.
References ARTS_ASSERT, Range::mextent, ConstVectorView::mrange, and v.
operator=() [2/5]
VectorView & VectorView::operator= (const ConstVectorView & v)
Assignment operator.
This copies the data from another VectorView to this VectorView. Dimensions must agree! Resizing would destroy the selection that we might have done in this VectorView by setting its range.
Definition at line 155 of file matpackI.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstVectorView::mrange, and v.
Referenced by Vector::operator=().
operator=() [3/5]
VectorView & VectorView::operator= (const Vector & v)
Assignment from Vector.
This is important to avoid a bug when assigning a Vector to a VectorView.
Definition at line 177 of file matpackI.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstVectorView::mrange, and v.
operator=() [4/5]
VectorView & VectorView::operator= (const VectorView & v)
Assignment from VectorView to VectorView.
This is a tricky one. The problem is that since VectorView is derived from ConstVectorView, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 166 of file matpackI.cc.
References ARTS_ASSERT, begin(), copy(), Range::mextent, ConstVectorView::mrange, and v.
operator=() [5/5]
VectorView & VectorView::operator= (Numeric x)
Assigning a scalar to a VectorView will set all elements to this value.
Definition at line 188 of file matpackI.cc.
References begin(), copy(), end(), and ARTS::Var::x().
operator[]() [1/2]
VectorView VectorView::operator[] (const Range & r)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Vector. This allows correct recursive behavior.
Definition at line 142 of file matpackI.cc.
operator[]() [2/2]
Numeric& VectorView::operator[] (Index n) inline
Plain Index operator.
Definition at line 639 of file matpackI.h.
References ARTS_ASSERT, get(), Range::mextent, and ConstVectorView::mrange.
Friends And Related Function Documentation
ComplexVectorView
friend class ComplexVectorView friend
Definition at line 743 of file matpackI.h.
ConstIterator2D
friend class ConstIterator2D friend
Definition at line 735 of file matpackI.h.
Iterator2D
friend class Iterator2D friend
Definition at line 736 of file matpackI.h.
MatrixView
friend class MatrixView friend
Definition at line 737 of file matpackI.h.
Tensor3View
friend class Tensor3View friend
Definition at line 738 of file matpackI.h.
Tensor4View
friend class Tensor4View friend
Definition at line 739 of file matpackI.h.
Tensor5View
friend class Tensor5View friend
Definition at line 740 of file matpackI.h.
Tensor6View
friend class Tensor6View friend
Definition at line 741 of file matpackI.h.
Tensor7View
friend class Tensor7View friend
Definition at line 742 of file matpackI.h.
The documentation for this class was generated from the following files:
matpackI.h
matpackI.cc