ARTS: ARTS::Var::WorkspaceRational Class Reference
ARTS::Var::WorkspaceRational Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceRational () noexcept
WorkspaceRational (std::size_t i, void *x) noexcept
~WorkspaceRational () noexcept
WorkspaceRational (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceRational & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Rational
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1358 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceRational::type = Group::Rational private
Definition at line 1359 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceRational() [1/3]
ARTS::Var::WorkspaceRational::WorkspaceRational () inline noexcept
Definition at line 1363 of file autoarts.h.
WorkspaceRational() [2/3]
ARTS::Var::WorkspaceRational::WorkspaceRational (std::size_t i, void * x) inline noexcept
Definition at line 1364 of file autoarts.h.
~WorkspaceRational()
ARTS::Var::WorkspaceRational::~WorkspaceRational () inline noexcept
Definition at line 1365 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceRational() [3/3]
ARTS::Var::WorkspaceRational::WorkspaceRational (const type & val) inline noexcept
Definition at line 1366 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceRational::islast () const inline noexcept
Definition at line 1372 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::RationalAdd(), ARTS::Method::RationalAdd(), ARTS::AgendaMethod::RationalInvScale(), ARTS::Method::RationalInvScale(), ARTS::AgendaMethod::RationalScale(), ARTS::Method::RationalScale(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceRational().
isnull()
bool ARTS::Var::WorkspaceRational::isnull () const inline noexcept
Definition at line 1371 of file autoarts.h.
References v.
Referenced by ~WorkspaceRational().
name()
const Group::String& ARTS::Var::WorkspaceRational::name () const inline noexcept
Definition at line 1373 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceRational& ARTS::Var::WorkspaceRational::operator= (const type & t) inline noexcept
Definition at line 1369 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceRational::pos () const inline noexcept
Definition at line 1370 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::AgendaMethod::abs_linesSetQuantumNumberForMatch(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::RationalAdd(), ARTS::AgendaMethod::RationalInvScale(), ARTS::AgendaMethod::RationalScale(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceRational::value () const inline noexcept
Definition at line 1368 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceRational::value () inline noexcept
Definition at line 1367 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Method::RationalScale(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceRational::p private
Definition at line 1360 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceRational::v private
Definition at line 1361 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceRational().
The documentation for this class was generated from the following file:
autoarts.h