ARTS: ARTS::Var::WorkspaceAbsorptionLines Class Reference
ARTS::Var::WorkspaceAbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceAbsorptionLines () noexcept
WorkspaceAbsorptionLines (std::size_t i, void *x) noexcept
~WorkspaceAbsorptionLines () noexcept
WorkspaceAbsorptionLines (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceAbsorptionLines & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::AbsorptionLines
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 116 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceAbsorptionLines::type = Group::AbsorptionLines private
Definition at line 117 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceAbsorptionLines() [1/3]
ARTS::Var::WorkspaceAbsorptionLines::WorkspaceAbsorptionLines () inline noexcept
Definition at line 121 of file autoarts.h.
WorkspaceAbsorptionLines() [2/3]
ARTS::Var::WorkspaceAbsorptionLines::WorkspaceAbsorptionLines (std::size_t i, void * x) inline noexcept
Definition at line 122 of file autoarts.h.
~WorkspaceAbsorptionLines()
ARTS::Var::WorkspaceAbsorptionLines::~WorkspaceAbsorptionLines () inline noexcept
Definition at line 123 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceAbsorptionLines() [3/3]
ARTS::Var::WorkspaceAbsorptionLines::WorkspaceAbsorptionLines (const type & val) inline noexcept
Definition at line 124 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceAbsorptionLines::islast () const inline noexcept
Definition at line 130 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceAbsorptionLines().
isnull()
bool ARTS::Var::WorkspaceAbsorptionLines::isnull () const inline noexcept
Definition at line 129 of file autoarts.h.
References v.
Referenced by ~WorkspaceAbsorptionLines().
name()
const Group::String& ARTS::Var::WorkspaceAbsorptionLines::name () const inline noexcept
Definition at line 131 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceAbsorptionLines& ARTS::Var::WorkspaceAbsorptionLines::operator= (const type & t) inline noexcept
Definition at line 127 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceAbsorptionLines::pos () const inline noexcept
Definition at line 128 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceAbsorptionLines::value () const inline noexcept
Definition at line 126 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceAbsorptionLines::value () inline noexcept
Definition at line 125 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceAbsorptionLines::p private
Definition at line 118 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceAbsorptionLines::v private
Definition at line 119 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceAbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h