ARTS: ARTS::Var::WorkspaceArrayOfArrayOfTime Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfTime Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfTime () noexcept
WorkspaceArrayOfArrayOfTime (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfTime () noexcept
WorkspaceArrayOfArrayOfTime (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfTime & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfTime
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 458 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfTime::type = Group::ArrayOfArrayOfTime private
Definition at line 459 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfTime() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfTime::WorkspaceArrayOfArrayOfTime () inline noexcept
Definition at line 463 of file autoarts.h.
WorkspaceArrayOfArrayOfTime() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfTime::WorkspaceArrayOfArrayOfTime (std::size_t i, void * x) inline noexcept
Definition at line 464 of file autoarts.h.
~WorkspaceArrayOfArrayOfTime()
ARTS::Var::WorkspaceArrayOfArrayOfTime::~WorkspaceArrayOfArrayOfTime () inline noexcept
Definition at line 465 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfTime() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfTime::WorkspaceArrayOfArrayOfTime (const type & val) inline noexcept
Definition at line 466 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfTime::islast () const inline noexcept
Definition at line 472 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfTime().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfTime::isnull () const inline noexcept
Definition at line 471 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfTime().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfTime::name () const inline noexcept
Definition at line 473 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfTime& ARTS::Var::WorkspaceArrayOfArrayOfTime::operator= (const type & t) inline noexcept
Definition at line 469 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTime::pos () const inline noexcept
Definition at line 470 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfTime::value () const inline noexcept
Definition at line 468 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfTime::value () inline noexcept
Definition at line 467 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfTime::p private
Definition at line 460 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfTime::v private
Definition at line 461 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfTime().
The documentation for this class was generated from the following file:
autoarts.h