ARTS: GriddedField2 Class Reference
GriddedField2 Class Reference final
#include <gridded_fields.h>
Public Member Functions
GriddedField2 ()
Construct an empty GriddedField2.
GriddedField2 (const String &s)
Construct an empty GriddedField2 with the given name.
bool checksize () const final
Consistency check.
void checksize_strict () const final
Strict consistency check.
void resize (const GriddedField2 &gf)
Make this GriddedField2 the same size as the given one.
void resize (Index r, Index c)
Resize the data matrix.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
const Vector & get_numeric_grid (Index i) const
Get a numeric grid.
Vector & get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Matrix data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField2 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 237 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField2() [1/2]
GriddedField2::GriddedField2 () inline
Construct an empty GriddedField2.
Definition at line 240 of file gridded_fields.h.
GriddedField2() [2/2]
GriddedField2::GriddedField2 (const String & s) inline
Construct an empty GriddedField2 with the given name.
Parameters
[in] s Name.
Definition at line 243 of file gridded_fields.h.
Member Function Documentation
checksize()
bool GriddedField2::checksize () const inline final virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 245 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by checksize_strict(), and main().
checksize_strict()
void GriddedField2::checksize_strict () const inline final virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 252 of file gridded_fields.h.
References CHECK_ERROR_BOILERPLATE, checksize(), data, GriddedField::get_grid_name(), GriddedField::get_grid_size(), GriddedField::get_name(), ConstMatrixView::ncols(), Absorption::nelem(), and ConstMatrixView::nrows().
Referenced by InterpGriddedField2ToPosition().
resize() [1/2]
void GriddedField2::resize (const GriddedField2 & gf) inline
Make this GriddedField2 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 271 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Matrix::resize().
Referenced by CIARecord::AppendDataset(), GriddedFieldLatLonExpand(), and GriddedFieldLatLonRegrid().
resize() [2/2]
void GriddedField2::resize (Index r, Index c) inline
Resize the data matrix.
See also
Matrix::resize
Definition at line 277 of file gridded_fields.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField2 & gf) friend
Member Data Documentation
data
Matrix GriddedField2::data
Definition at line 281 of file gridded_fields.h.
Referenced by CIARecord::AppendDataset(), checksize(), checksize_strict(), FieldFromGriddedField(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), InterpGriddedField2ToPosition(), main(), resize(), test01(), and z_surfaceFromFileAndGrid().
The documentation for this class was generated from the following file:
gridded_fields.h