ARTS: ARTS::Var::Tensor6 Class Reference
ARTS::Var::Tensor6 Class Reference
#include <autoarts.h>
Public Member Functions
Tensor6 () noexcept
Tensor6 (std::size_t i, void *x) noexcept
Tensor6 (const Group::Tensor6 &val) noexcept
~Tensor6 () noexcept
Group::Tensor6 & value () noexcept
const Group::Tensor6 & value () const noexcept
Tensor6 & operator= (const Group::Tensor6 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Tensor6 * v
Friends
std::ostream & operator<< (std::ostream &os, const Tensor6 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4174 of file autoarts.h.
Constructor & Destructor Documentation
Tensor6() [1/3]
ARTS::Var::Tensor6::Tensor6 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4179 of file autoarts.h.
Tensor6() [2/3]
ARTS::Var::Tensor6::Tensor6 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4182 of file autoarts.h.
Tensor6() [3/3]
ARTS::Var::Tensor6::Tensor6 (const Group::Tensor6 & val) inline noexcept
Construct from Group::Tensor6. Leaves islast() true and isnull() false
Definition at line 4185 of file autoarts.h.
~Tensor6()
ARTS::Var::Tensor6::~Tensor6 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4188 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Tensor6::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4206 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Flatten(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Method::Tensor6Scale(), ARTS::Agenda::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Agenda::Method::Tensor6SetConstant(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Tensor6().
isnull()
bool ARTS::Var::Tensor6::isnull () const inline noexcept
Return true if there is no data
Definition at line 4203 of file autoarts.h.
References v.
Referenced by ~Tensor6().
name()
const Group::String& ARTS::Var::Tensor6::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4209 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Tensor6& ARTS::Var::Tensor6::operator= (const Group::Tensor6 & t) inline noexcept
Set value from Group::Tensor6. Works when isnull() is false
Definition at line 4197 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Tensor6::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4200 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::Tensor6Scale(), ARTS::Agenda::Method::Tensor6SetConstant(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Tensor6& ARTS::Var::Tensor6::value () const inline noexcept
Get value const-ref as Group::Tensor6. Works when isnull() is false
Definition at line 4194 of file autoarts.h.
References v.
value() [2/2]
Group::Tensor6& ARTS::Var::Tensor6::value () inline noexcept
Get value ref as Group::Tensor6. Works when isnull() is false
Definition at line 4191 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Reduce(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Tensor6 & var) friend
Output to stream of internal variable
Definition at line 4212 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Tensor6::p private
Definition at line 4175 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Tensor6* ARTS::Var::Tensor6::v private
Definition at line 4176 of file autoarts.h.
Referenced by isnull(), value(), and ~Tensor6().
The documentation for this class was generated from the following file:
autoarts.h