ARTS: ARTS::Var::WorkspaceGriddedField5 Class Reference
ARTS::Var::WorkspaceGriddedField5 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField5 () noexcept
WorkspaceGriddedField5 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField5 () noexcept
WorkspaceGriddedField5 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField5 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField5
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1160 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField5::type = Group::GriddedField5 private
Definition at line 1161 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField5() [1/3]
ARTS::Var::WorkspaceGriddedField5::WorkspaceGriddedField5 () inline noexcept
Definition at line 1165 of file autoarts.h.
WorkspaceGriddedField5() [2/3]
ARTS::Var::WorkspaceGriddedField5::WorkspaceGriddedField5 (std::size_t i, void * x) inline noexcept
Definition at line 1166 of file autoarts.h.
~WorkspaceGriddedField5()
ARTS::Var::WorkspaceGriddedField5::~WorkspaceGriddedField5 () inline noexcept
Definition at line 1167 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField5() [3/3]
ARTS::Var::WorkspaceGriddedField5::WorkspaceGriddedField5 (const type & val) inline noexcept
Definition at line 1168 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField5::islast () const inline noexcept
Definition at line 1174 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_complex_refr_indexFromGriddedField5(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField5().
isnull()
bool ARTS::Var::WorkspaceGriddedField5::isnull () const inline noexcept
Definition at line 1173 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField5().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField5::name () const inline noexcept
Definition at line 1175 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField5& ARTS::Var::WorkspaceGriddedField5::operator= (const type & t) inline noexcept
Definition at line 1171 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField5::pos () const inline noexcept
Definition at line 1172 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_complex_refr_indexFromGriddedField5(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField5::value () const inline noexcept
Definition at line 1170 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField5::value () inline noexcept
Definition at line 1169 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), operator=(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField5::p private
Definition at line 1162 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField5::v private
Definition at line 1163 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField5().
The documentation for this class was generated from the following file:
autoarts.h