ARTS: ARTS::Var::WorkspaceGriddedField1 Class Reference
ARTS::Var::WorkspaceGriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField1 () noexcept
WorkspaceGriddedField1 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField1 () noexcept
WorkspaceGriddedField1 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField1 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField1
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1088 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField1::type = Group::GriddedField1 private
Definition at line 1089 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField1() [1/3]
ARTS::Var::WorkspaceGriddedField1::WorkspaceGriddedField1 () inline noexcept
Definition at line 1093 of file autoarts.h.
WorkspaceGriddedField1() [2/3]
ARTS::Var::WorkspaceGriddedField1::WorkspaceGriddedField1 (std::size_t i, void * x) inline noexcept
Definition at line 1094 of file autoarts.h.
~WorkspaceGriddedField1()
ARTS::Var::WorkspaceGriddedField1::~WorkspaceGriddedField1 () inline noexcept
Definition at line 1095 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField1() [3/3]
ARTS::Var::WorkspaceGriddedField1::WorkspaceGriddedField1 (const type & val) inline noexcept
Definition at line 1096 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField1::islast () const inline noexcept
Definition at line 1102 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField1().
isnull()
bool ARTS::Var::WorkspaceGriddedField1::isnull () const inline noexcept
Definition at line 1101 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField1().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField1::name () const inline noexcept
Definition at line 1103 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField1& ARTS::Var::WorkspaceGriddedField1::operator= (const type & t) inline noexcept
Definition at line 1099 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField1::pos () const inline noexcept
Definition at line 1100 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField1::value () const inline noexcept
Definition at line 1098 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField1::value () inline noexcept
Definition at line 1097 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField1::p private
Definition at line 1090 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField1::v private
Definition at line 1091 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField1().
The documentation for this class was generated from the following file:
autoarts.h