ARTS: ARTS::Var::ArrayOfGriddedField3 Class Reference
ARTS::Var::ArrayOfGriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfGriddedField3 () noexcept
ArrayOfGriddedField3 (std::size_t i, void *x) noexcept
ArrayOfGriddedField3 (const Group::ArrayOfGriddedField3 &val) noexcept
~ArrayOfGriddedField3 () noexcept
Group::ArrayOfGriddedField3 & value () noexcept
const Group::ArrayOfGriddedField3 & value () const noexcept
ArrayOfGriddedField3 & operator= (const Group::ArrayOfGriddedField3 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfGriddedField3 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfGriddedField3 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1499 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfGriddedField3() [1/3]
ARTS::Var::ArrayOfGriddedField3::ArrayOfGriddedField3 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1504 of file autoarts.h.
ArrayOfGriddedField3() [2/3]
ARTS::Var::ArrayOfGriddedField3::ArrayOfGriddedField3 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1507 of file autoarts.h.
ArrayOfGriddedField3() [3/3]
ARTS::Var::ArrayOfGriddedField3::ArrayOfGriddedField3 (const Group::ArrayOfGriddedField3 & val) inline noexcept
Construct from Group::ArrayOfGriddedField3. Leaves islast() true and isnull() false
Definition at line 1510 of file autoarts.h.
~ArrayOfGriddedField3()
ARTS::Var::ArrayOfGriddedField3::~ArrayOfGriddedField3 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1513 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfGriddedField3::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1531 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::GriddedFieldLatLonExpand(), and ~ArrayOfGriddedField3().
isnull()
bool ARTS::Var::ArrayOfGriddedField3::isnull () const inline noexcept
Return true if there is no data
Definition at line 1528 of file autoarts.h.
References v.
Referenced by ~ArrayOfGriddedField3().
name()
const Group::String& ARTS::Var::ArrayOfGriddedField3::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1534 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfGriddedField3& ARTS::Var::ArrayOfGriddedField3::operator= (const Group::ArrayOfGriddedField3 & t) inline noexcept
Set value from Group::ArrayOfGriddedField3. Works when isnull() is false
Definition at line 1522 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfGriddedField3::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1525 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfGriddedField3& ARTS::Var::ArrayOfGriddedField3::value () const inline noexcept
Get value const-ref as Group::ArrayOfGriddedField3. Works when isnull() is false
Definition at line 1519 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfGriddedField3& ARTS::Var::ArrayOfGriddedField3::value () inline noexcept
Get value ref as Group::ArrayOfGriddedField3. Works when isnull() is false
Definition at line 1516 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfGriddedField3 & var) friend
Output to stream of internal variable
Definition at line 1537 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfGriddedField3::p private
Definition at line 1500 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfGriddedField3* ARTS::Var::ArrayOfGriddedField3::v private
Definition at line 1501 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfGriddedField3().
The documentation for this class was generated from the following file:
autoarts.h