ARTS: ARTS::Var::Time Class Reference
ARTS::Var::Time Class Reference
#include <autoarts.h>
Public Member Functions
Time () noexcept
Time (std::size_t i, void *x) noexcept
Time (const Group::Time &val) noexcept
~Time () noexcept
Group::Time & value () noexcept
const Group::Time & value () const noexcept
Time & operator= (const Group::Time &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Time * v
Friends
std::ostream & operator<< (std::ostream &os, const Time &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4414 of file autoarts.h.
Constructor & Destructor Documentation
Time() [1/3]
ARTS::Var::Time::Time () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4419 of file autoarts.h.
Time() [2/3]
ARTS::Var::Time::Time (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4422 of file autoarts.h.
Time() [3/3]
ARTS::Var::Time::Time (const Group::Time & val) inline noexcept
Construct from Group::Time. Leaves islast() true and isnull() false
Definition at line 4425 of file autoarts.h.
~Time()
ARTS::Var::Time::~Time () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4428 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Time::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4446 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::ArrayOfTimeSetConstant(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Sleep(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Time().
isnull()
bool ARTS::Var::Time::isnull () const inline noexcept
Return true if there is no data
Definition at line 4443 of file autoarts.h.
References v.
Referenced by ~Time().
name()
const Group::String& ARTS::Var::Time::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4449 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Time& ARTS::Var::Time::operator= (const Group::Time & t) inline noexcept
Set value from Group::Time. Works when isnull() is false
Definition at line 4437 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Time::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4440 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::ArrayOfTimeSetConstant(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Sleep(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Time& ARTS::Var::Time::value () const inline noexcept
Get value const-ref as Group::Time. Works when isnull() is false
Definition at line 4434 of file autoarts.h.
References v.
value() [2/2]
Group::Time& ARTS::Var::Time::value () inline noexcept
Get value ref as Group::Time. Works when isnull() is false
Definition at line 4431 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfTimeSetConstant(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Sleep(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Time & var) friend
Output to stream of internal variable
Definition at line 4452 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Time::p private
Definition at line 4415 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Time* ARTS::Var::Time::v private
Definition at line 4416 of file autoarts.h.
Referenced by isnull(), value(), and ~Time().
The documentation for this class was generated from the following file:
autoarts.h