ARTS: ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfSingleScatteringData () noexcept
WorkspaceArrayOfArrayOfSingleScatteringData (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfSingleScatteringData () noexcept
WorkspaceArrayOfArrayOfSingleScatteringData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfSingleScatteringData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfSingleScatteringData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 350 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::type = Group::ArrayOfArrayOfSingleScatteringData private
Definition at line 351 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfSingleScatteringData() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::WorkspaceArrayOfArrayOfSingleScatteringData () inline noexcept
Definition at line 355 of file autoarts.h.
WorkspaceArrayOfArrayOfSingleScatteringData() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::WorkspaceArrayOfArrayOfSingleScatteringData (std::size_t i, void * x) inline noexcept
Definition at line 356 of file autoarts.h.
~WorkspaceArrayOfArrayOfSingleScatteringData()
ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::~WorkspaceArrayOfArrayOfSingleScatteringData () inline noexcept
Definition at line 357 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfSingleScatteringData() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::WorkspaceArrayOfArrayOfSingleScatteringData (const type & val) inline noexcept
Definition at line 358 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::islast () const inline noexcept
Definition at line 364 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfSingleScatteringData().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::isnull () const inline noexcept
Definition at line 363 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfSingleScatteringData().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::name () const inline noexcept
Definition at line 365 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfSingleScatteringData& ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::operator= (const type & t) inline noexcept
Definition at line 361 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::pos () const inline noexcept
Definition at line 362 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::value () const inline noexcept
Definition at line 360 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::value () inline noexcept
Definition at line 359 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::p private
Definition at line 352 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfSingleScatteringData::v private
Definition at line 353 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfSingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h