ARTS: ARTS::Var::ArrayOfXsecRecord Class Reference
ARTS::Var::ArrayOfXsecRecord Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfXsecRecord () noexcept
ArrayOfXsecRecord (std::size_t i, void *x) noexcept
ArrayOfXsecRecord (const Group::ArrayOfXsecRecord &val) noexcept
~ArrayOfXsecRecord () noexcept
Group::ArrayOfXsecRecord & value () noexcept
const Group::ArrayOfXsecRecord & value () const noexcept
ArrayOfXsecRecord & operator= (const Group::ArrayOfXsecRecord &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfXsecRecord * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfXsecRecord &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2625 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfXsecRecord() [1/3]
ARTS::Var::ArrayOfXsecRecord::ArrayOfXsecRecord () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2630 of file autoarts.h.
ArrayOfXsecRecord() [2/3]
ARTS::Var::ArrayOfXsecRecord::ArrayOfXsecRecord (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2633 of file autoarts.h.
ArrayOfXsecRecord() [3/3]
ARTS::Var::ArrayOfXsecRecord::ArrayOfXsecRecord (const Group::ArrayOfXsecRecord & val) inline noexcept
Construct from Group::ArrayOfXsecRecord. Leaves islast() true and isnull() false
Definition at line 2636 of file autoarts.h.
~ArrayOfXsecRecord()
ARTS::Var::ArrayOfXsecRecord::~ArrayOfXsecRecord () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2639 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfXsecRecord::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2657 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfXsecRecord().
isnull()
bool ARTS::Var::ArrayOfXsecRecord::isnull () const inline noexcept
Return true if there is no data
Definition at line 2654 of file autoarts.h.
References v.
Referenced by ~ArrayOfXsecRecord().
name()
const Group::String& ARTS::Var::ArrayOfXsecRecord::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2660 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfXsecRecord& ARTS::Var::ArrayOfXsecRecord::operator= (const Group::ArrayOfXsecRecord & t) inline noexcept
Set value from Group::ArrayOfXsecRecord. Works when isnull() is false
Definition at line 2648 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfXsecRecord::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2651 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfXsecRecord& ARTS::Var::ArrayOfXsecRecord::value () const inline noexcept
Get value const-ref as Group::ArrayOfXsecRecord. Works when isnull() is false
Definition at line 2645 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfXsecRecord& ARTS::Var::ArrayOfXsecRecord::value () inline noexcept
Get value ref as Group::ArrayOfXsecRecord. Works when isnull() is false
Definition at line 2642 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfXsecRecord & var) friend
Output to stream of internal variable
Definition at line 2663 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfXsecRecord::p private
Definition at line 2626 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfXsecRecord* ARTS::Var::ArrayOfXsecRecord::v private
Definition at line 2627 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfXsecRecord().
The documentation for this class was generated from the following file:
autoarts.h