ARTS: MatrixView Class Reference
MatrixView Class Reference
The MatrixView class.
#include <matpackI.h>
Public Types
typedef Iterator2D iterator
Public Types inherited from ConstMatrixView
typedef ConstIterator2D const_iterator
Public Member Functions
constexpr MatrixView (const MatrixView &)=default
Numeric & operator() (Index r, Index c) ARTS_NOEXCEPT
Plain index operator.
Numeric & get (Index r, Index c) ARTS_NOEXCEPT
Get element implementation without assertions.
MatrixView operator() (const Range &r, const Range &c) ARTS_NOEXCEPT
Index operator for subrange.
VectorView operator() (const Range &r, Index c) ARTS_NOEXCEPT
Index operator returning a column as an object of type VectorView.
VectorView operator() (Index r, const Range &c) ARTS_NOEXCEPT
Index operator returning a row as an object of type VectorView.
Iterator2D begin () ARTS_NOEXCEPT
‍** Return const iterator to first row. Has to be redefined here, since it is
Iterator2D end () ARTS_NOEXCEPT
Return iterator behind last row.
MatrixView & operator= (const ConstMatrixView &m)
Assignment operator.
MatrixView & operator= (const MatrixView &m)
Assignment from MatrixView to MatrixView.
MatrixView & operator= (const Matrix &m)
Assignment from a Matrix.
MatrixView & operator= (const ConstVectorView &m)
Assignment from a vector.
MatrixView & operator= (Numeric x)
Assigning a scalar to a MatrixView will set all elements to this value.
MatrixView & operator*= (Numeric x) ARTS_NOEXCEPT
Multiplication by scalar.
MatrixView & operator/= (Numeric x) ARTS_NOEXCEPT
Division by scalar.
MatrixView & operator+= (Numeric x) ARTS_NOEXCEPT
Addition of scalar.
MatrixView & operator-= (Numeric x) ARTS_NOEXCEPT
Subtraction of scalar.
MatrixView & operator*= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise multiplication by another Matrix.
MatrixView & operator/= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise division by another Matrix.
MatrixView & operator+= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise addition of another Matrix.
MatrixView & operator-= (const ConstMatrixView &x) ARTS_NOEXCEPT
Element-vise subtraction of another Matrix.
MatrixView & operator*= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise multiplication by a Vector (acting like a 1-column Matrix).
MatrixView & operator/= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise division by a Vector (acting like a 1-column Matrix).
MatrixView & operator+= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise addition of a Vector (acting like a 1-column Matrix).
MatrixView & operator-= (const ConstVectorView &x) ARTS_NOEXCEPT
Element-vise subtraction of a Vector (acting like a 1-column Matrix).
const Numeric * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array.
Numeric * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array.
virtual ~MatrixView ()=default
Destructor.
ConstIterator2D begin () const ARTS_NOEXCEPT
Return const iterator to first row.
ConstIterator2D end () const ARTS_NOEXCEPT
Return const iterator behind last row.
Numeric get (Index r, Index c) const ARTS_NOEXCEPT
Get element implementation without assertions.
Public Member Functions inherited from ConstMatrixView
constexpr ConstMatrixView (const ConstMatrixView &)=default
constexpr ConstMatrixView (ConstMatrixView &&)=default
ConstMatrixView & operator= (const ConstMatrixView &)=default
ConstMatrixView & operator= (ConstMatrixView &&)=default
bool empty () const ARTS_NOEXCEPT
Returns true if variable size is zero.
Index nrows () const ARTS_NOEXCEPT
Returns the number of rows.
Index ncols () const ARTS_NOEXCEPT
Returns the number of columns.
Numeric operator() (Index r, Index c) const ARTS_NOEXCEPT
Plain const index operator.
Numeric get (Index r, Index c) const ARTS_NOEXCEPT
Get element implementation without assertions.
ConstMatrixView operator() (const Range &r, const Range &c) const ARTS_NOEXCEPT
Const index operator for subrange.
ConstVectorView operator() (const Range &r, Index c) const ARTS_NOEXCEPT
Const index operator returning a column as an object of type ConstVectorView.
ConstVectorView operator() (Index r, const Range &c) const ARTS_NOEXCEPT
Const index operator returning a row as an object of type ConstVectorView.
ConstIterator2D begin () const ARTS_NOEXCEPT
Return const iterator to first row.
ConstIterator2D end () const ARTS_NOEXCEPT
Return const iterator behind last row.
ConstVectorView diagonal () const ARTS_NOEXCEPT
Matrix diagonal as vector.
virtual ~ConstMatrixView ()=default
Destructor.
Protected Member Functions
MatrixView ()=default
MatrixView (Numeric *data, const Range &rr, const Range &cr) ARTS_NOEXCEPT
Explicit constructor.
MatrixView (Numeric *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc) ARTS_NOEXCEPT
Recursive constructor.
Protected Member Functions inherited from ConstMatrixView
ConstMatrixView ()=default
ConstMatrixView (Numeric *data, const Range &r, const Range &c) ARTS_NOEXCEPT
Explicit constructor.
ConstMatrixView (Numeric *data, const Range &pr, const Range &pc, const Range &nr, const Range &nc) ARTS_NOEXCEPT
Recursive constructor.
Friends
class VectorView
class Iterator3D
class Tensor3View
class Tensor4View
class Tensor5View
class Tensor6View
class Tensor7View
class ComplexMatrixView
ConstMatrixView transpose (ConstMatrixView m) ARTS_NOEXCEPT
Const version of transpose.
MatrixView transpose (MatrixView m) ARTS_NOEXCEPT
Returns the transpose.
void mult (MatrixView, const ConstMatrixView &, const ConstMatrixView &)
Matrix-Matrix Multiplication.
Additional Inherited Members
Protected Attributes inherited from ConstMatrixView
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The MatrixView class.
This contains the main implementation of a Matrix. It defines the concepts of MatrixView. Plus additionally the recursive subrange operator, which makes it possible to create a MatrixView from a subrange of a MatrixView.
The class Matrix is just a special case of a MatrixView which also allocates storage.
Definition at line 1117 of file matpackI.h.
Member Typedef Documentation
iterator
typedef Iterator2D MatrixView::iterator
Definition at line 1128 of file matpackI.h.
Constructor & Destructor Documentation
MatrixView() [1/4]
constexpr MatrixView::MatrixView (const MatrixView &) constexpr default
~MatrixView()
virtual MatrixView::~MatrixView () virtual default
Destructor.
MatrixView() [2/4]
MatrixView::MatrixView () protected default
MatrixView() [3/4]
MatrixView::MatrixView (Numeric * data, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Matrix to initialize its own MatrixView part. The row range rr must have a stride to account for the length of one row.
Definition at line 885 of file matpackI.cc.
MatrixView() [4/4]
MatrixView::MatrixView (Numeric * data, const Range & pr, const Range & pc, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pr Previous range.
pc Previous range.
nr New Range.
nc New Range.
Definition at line 904 of file matpackI.cc.
Member Function Documentation
begin() [1/2]
Iterator2D MatrixView::begin ()
‍** Return const iterator to first row. Has to be redefined here, since it is
‍** Return const iterator behind last row. *‍/ Return iterator to first row.
Definition at line 625 of file matpackI.cc.
References ConstMatrixView::mcr, ConstMatrixView::mdata, ConstMatrixView::mrr, Range::mstart, Range::mstride, and VectorView.
Referenced by copy(), Matrix::Matrix(), operator=(), and Matrix::operator=().
begin() [2/2]
ConstIterator2D ConstMatrixView::begin
Return const iterator to first row.
Definition at line 1043 of file matpackI.cc.
end() [1/2]
Iterator2D MatrixView::end ()
Return iterator behind last row.
Definition at line 630 of file matpackI.cc.
References ConstMatrixView::mcr, ConstMatrixView::mdata, Range::mextent, ConstMatrixView::mrr, Range::mstart, Range::mstride, and VectorView.
Referenced by copy(), and operator=().
end() [2/2]
ConstIterator2D ConstMatrixView::end
Return const iterator behind last row.
Definition at line 1044 of file matpackI.cc.
get() [1/2]
Numeric& MatrixView::get (Index r, Index c) inline
Get element implementation without assertions.
Definition at line 1142 of file matpackI.h.
References c, and ConstVectorView::mdata.
Referenced by interpweights().
get() [2/2]
Numeric ConstMatrixView::get inline
Get element implementation without assertions.
Definition at line 1033 of file matpackI.h.
get_c_array() [1/2]
Numeric * MatrixView::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the MatrixView is not pointing to the beginning of a Matrix or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 755 of file matpackI.cc.
References ARTS_ASSERT, ConstMatrixView::mcr, ConstMatrixView::mdata, Range::mextent, ConstMatrixView::mrr, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Numeric * MatrixView::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the MatrixView is not pointing to the beginning of a Matrix or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 742 of file matpackI.cc.
References ARTS_ASSERT, ConstMatrixView::mcr, ConstMatrixView::mdata, Range::mextent, ConstMatrixView::mrr, Range::mstart, and Range::mstride.
Referenced by get_covariance_matrix_block(), get_variable_value(), nca_get_data_Matrix(), nca_put_var_Matrix(), nca_read_from_file(), nca_write_to_file(), Reduce(), InteractiveWorkspace::set_matrix_variable(), and test38().
operator()() [1/4]
MatrixView MatrixView::operator() (const Range & r, const Range & c)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Matrix. This allows correct recursive behavior.
Definition at line 583 of file matpackI.cc.
References c.
operator()() [2/4]
VectorView MatrixView::operator() (const Range & r, Index c)
Index operator returning a column as an object of type VectorView.
Parameters
r A range of rows.
c Index of selected column
Definition at line 591 of file matpackI.cc.
References ARTS_ASSERT, and c.
operator()() [3/4]
VectorView MatrixView::operator() (Index r, const Range & c)
Index operator returning a row as an object of type VectorView.
Parameters
r Index of selected row.
c Range of columns
Definition at line 603 of file matpackI.cc.
References ARTS_ASSERT, and c.
operator()() [4/4]
Numeric& MatrixView::operator() (Index r, Index c) inline
Plain index operator.
Definition at line 1132 of file matpackI.h.
References ARTS_ASSERT, c, and VectorView::get().
operator*=() [1/3]
MatrixView & MatrixView::operator*= (const ConstMatrixView & x)
Element-vise multiplication by another Matrix.
Definition at line 763 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), ConstVectorView::begin(), c, VectorView::end(), Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator*=() [2/3]
MatrixView & MatrixView::operator*= (const ConstVectorView & x)
Element-vise multiplication by a Vector (acting like a 1-column Matrix).
Definition at line 827 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), c, Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator*=() [3/3]
MatrixView & MatrixView::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 697 of file matpackI.cc.
References c, Zeeman::end(), and ARTS::Var::x().
operator+=() [1/3]
MatrixView & MatrixView::operator+= (const ConstMatrixView & x)
Element-vise addition of another Matrix.
Definition at line 795 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), ConstVectorView::begin(), c, VectorView::end(), Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator+=() [2/3]
MatrixView & MatrixView::operator+= (const ConstVectorView & x)
Element-vise addition of a Vector (acting like a 1-column Matrix).
Definition at line 855 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), c, Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator+=() [3/3]
MatrixView & MatrixView::operator+= (Numeric x)
Addition of scalar.
Definition at line 717 of file matpackI.cc.
References c, Zeeman::end(), and ARTS::Var::x().
operator-=() [1/3]
MatrixView & MatrixView::operator-= (const ConstMatrixView & x)
Element-vise subtraction of another Matrix.
Definition at line 811 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), ConstVectorView::begin(), c, VectorView::end(), Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator-=() [2/3]
MatrixView & MatrixView::operator-= (const ConstVectorView & x)
Element-vise subtraction of a Vector (acting like a 1-column Matrix).
Definition at line 869 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), c, Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator-=() [3/3]
MatrixView & MatrixView::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 727 of file matpackI.cc.
References c, Zeeman::end(), and ARTS::Var::x().
operator/=() [1/3]
MatrixView & MatrixView::operator/= (const ConstMatrixView & x)
Element-vise division by another Matrix.
Definition at line 779 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), ConstVectorView::begin(), c, VectorView::end(), Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator/=() [2/3]
MatrixView & MatrixView::operator/= (const ConstVectorView & x)
Element-vise division by a Vector (acting like a 1-column Matrix).
Definition at line 841 of file matpackI.cc.
References ARTS_ASSERT, VectorView::begin(), c, Zeeman::end(), ARTS::Var::ncols(), ARTS::Var::nrows(), and ARTS::Var::x().
operator/=() [3/3]
MatrixView & MatrixView::operator/= (Numeric x)
Division by scalar.
Definition at line 707 of file matpackI.cc.
References c, Zeeman::end(), and ARTS::Var::x().
operator=() [1/5]
MatrixView & MatrixView::operator= (const ConstMatrixView & m)
Assignment operator.
This copies the data from another MatrixView to this MatrixView. Dimensions must agree! Resizing would destroy the selection that we might have done in this MatrixView by setting its range.
Definition at line 640 of file matpackI.cc.
References ARTS_ASSERT, begin(), ConstMatrixView::begin(), copy(), ConstMatrixView::end(), ConstMatrixView::mcr, Range::mextent, and ConstMatrixView::mrr.
operator=() [2/5]
MatrixView & MatrixView::operator= (const ConstVectorView & v)
Assignment from a vector.
This copies the data from a VectorView to this MatrixView. Dimensions must agree! Resizing would destroy the selection that we might have done in this MatrixView by setting its range.
Definition at line 679 of file matpackI.cc.
References ARTS_ASSERT, begin(), ConstMatrixView::begin(), copy(), ConstMatrixView::end(), ConstMatrixView::mcr, Range::mextent, ConstMatrixView::mrr, and v.
operator=() [3/5]
MatrixView & MatrixView::operator= (const Matrix & m)
Assignment from a Matrix.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 666 of file matpackI.cc.
References ARTS_ASSERT, begin(), copy(), end(), ConstMatrixView::mcr, Range::mextent, and ConstMatrixView::mrr.
operator=() [4/5]
MatrixView & MatrixView::operator= (const MatrixView & m)
Assignment from MatrixView to MatrixView.
This is a tricky one. The problem is that since MatrixView is derived from ConstMatrixView, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 654 of file matpackI.cc.
References ARTS_ASSERT, begin(), copy(), end(), ConstMatrixView::mcr, Range::mextent, and ConstMatrixView::mrr.
operator=() [5/5]
MatrixView & MatrixView::operator= (Numeric x)
Assigning a scalar to a MatrixView will set all elements to this value.
Definition at line 691 of file matpackI.cc.
References begin(), copy(), end(), and ARTS::Var::x().
Friends And Related Function Documentation
ComplexMatrixView
friend class ComplexMatrixView friend
Definition at line 1193 of file matpackI.h.
Iterator3D
friend class Iterator3D friend
Definition at line 1187 of file matpackI.h.
mult
void mult (MatrixView , const ConstMatrixView & , const ConstMatrixView &) friend
Matrix-Matrix Multiplication.
Performs the matrix multiplication A = B * C. The dimensions must match, i.e. A must be a m times n matrix, B a m times k matrix and C a k times c matrix. No memory reallocation takes place, only the data is copied. Using this function on overlapping MatrixViews belonging to the same Matrix will lead to unpredictable results. In particular, this means that A and B must not be the same matrix!
If the memory layout allows it, the multiplication is performed using BLAS' _dgemm, which leads to a significant speed up of the operation. To be compatible with BLAS the matrix views A, B and C must satisfy:
A must have column or row stride 1
B must have column or row stride 1
C must have column stride 1
That means that A and B can be ConstMatrixView objects corresponding to transposed/non-transposed submatrices of a matrix, that are continuous along their first/second dimension. C must correspond to a non-transposed submatrix of a matrix, that is continuous along its second dimension.
Parameters
[in,out] A The matrix A, that will hold the result of the multiplication.
[in] B The matrix B
[in] C The matrix C
Definition at line 1245 of file matpackI.cc.
Tensor3View
friend class Tensor3View friend
Definition at line 1188 of file matpackI.h.
Tensor4View
friend class Tensor4View friend
Definition at line 1189 of file matpackI.h.
Tensor5View
friend class Tensor5View friend
Definition at line 1190 of file matpackI.h.
Tensor6View
friend class Tensor6View friend
Definition at line 1191 of file matpackI.h.
Tensor7View
friend class Tensor7View friend
Definition at line 1192 of file matpackI.h.
transpose [1/2]
ConstMatrixView transpose (ConstMatrixView m) friend
Const version of transpose.
Definition at line 1447 of file matpackI.cc.
transpose [2/2]
MatrixView transpose (MatrixView m) friend
Returns the transpose.
This creates a special MatrixView for the transpose. The original is not changed!
Definition at line 1453 of file matpackI.cc.
VectorView
friend class VectorView friend
Definition at line 1186 of file matpackI.h.
Referenced by begin(), and end().
The documentation for this class was generated from the following files:
matpackI.h
matpackI.cc