ARTS: ARTS::Var::ArrayOfArrayOfSingleScatteringData Class Reference
ARTS::Var::ArrayOfArrayOfSingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfSingleScatteringData () noexcept
ArrayOfArrayOfSingleScatteringData (std::size_t i, void *x) noexcept
ArrayOfArrayOfSingleScatteringData (const Group::ArrayOfArrayOfSingleScatteringData &val) noexcept
~ArrayOfArrayOfSingleScatteringData () noexcept
Group::ArrayOfArrayOfSingleScatteringData & value () noexcept
const Group::ArrayOfArrayOfSingleScatteringData & value () const noexcept
ArrayOfArrayOfSingleScatteringData & operator= (const Group::ArrayOfArrayOfSingleScatteringData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfSingleScatteringData * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfSingleScatteringData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 935 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfSingleScatteringData() [1/3]
ARTS::Var::ArrayOfArrayOfSingleScatteringData::ArrayOfArrayOfSingleScatteringData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 940 of file autoarts.h.
ArrayOfArrayOfSingleScatteringData() [2/3]
ARTS::Var::ArrayOfArrayOfSingleScatteringData::ArrayOfArrayOfSingleScatteringData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 943 of file autoarts.h.
ArrayOfArrayOfSingleScatteringData() [3/3]
ARTS::Var::ArrayOfArrayOfSingleScatteringData::ArrayOfArrayOfSingleScatteringData (const Group::ArrayOfArrayOfSingleScatteringData & val) inline noexcept
Construct from Group::ArrayOfArrayOfSingleScatteringData. Leaves islast() true and isnull() false
Definition at line 946 of file autoarts.h.
~ArrayOfArrayOfSingleScatteringData()
ARTS::Var::ArrayOfArrayOfSingleScatteringData::~ArrayOfArrayOfSingleScatteringData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 949 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfSingleScatteringData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 967 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfSingleScatteringData().
isnull()
bool ARTS::Var::ArrayOfArrayOfSingleScatteringData::isnull () const inline noexcept
Return true if there is no data
Definition at line 964 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfSingleScatteringData().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfSingleScatteringData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 970 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfSingleScatteringData& ARTS::Var::ArrayOfArrayOfSingleScatteringData::operator= (const Group::ArrayOfArrayOfSingleScatteringData & t) inline noexcept
Set value from Group::ArrayOfArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 958 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfSingleScatteringData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 961 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfSingleScatteringData& ARTS::Var::ArrayOfArrayOfSingleScatteringData::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 955 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfSingleScatteringData& ARTS::Var::ArrayOfArrayOfSingleScatteringData::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 952 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfSingleScatteringData & var) friend
Output to stream of internal variable
Definition at line 973 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfSingleScatteringData::p private
Definition at line 936 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfSingleScatteringData* ARTS::Var::ArrayOfArrayOfSingleScatteringData::v private
Definition at line 937 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfSingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h