ARTS: ARTS::Var::CIARecord Class Reference
ARTS::Var::CIARecord Class Reference
#include <autoarts.h>
Public Member Functions
CIARecord () noexcept
CIARecord (std::size_t i, void *x) noexcept
CIARecord (const Group::CIARecord &val) noexcept
~CIARecord () noexcept
Group::CIARecord & value () noexcept
const Group::CIARecord & value () const noexcept
CIARecord & operator= (const Group::CIARecord &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::CIARecord * v
Friends
std::ostream & operator<< (std::ostream &os, const CIARecord &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2726 of file autoarts.h.
Constructor & Destructor Documentation
CIARecord() [1/3]
ARTS::Var::CIARecord::CIARecord () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2731 of file autoarts.h.
CIARecord() [2/3]
ARTS::Var::CIARecord::CIARecord (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2734 of file autoarts.h.
CIARecord() [3/3]
ARTS::Var::CIARecord::CIARecord (const Group::CIARecord & val) inline noexcept
Construct from Group::CIARecord. Leaves islast() true and isnull() false
Definition at line 2737 of file autoarts.h.
~CIARecord()
ARTS::Var::CIARecord::~CIARecord () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2740 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::CIARecord::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2758 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::CIARecordReadFromFile(), ARTS::Agenda::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~CIARecord().
isnull()
bool ARTS::Var::CIARecord::isnull () const inline noexcept
Return true if there is no data
Definition at line 2755 of file autoarts.h.
References v.
Referenced by ~CIARecord().
name()
const Group::String& ARTS::Var::CIARecord::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2761 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
CIARecord& ARTS::Var::CIARecord::operator= (const Group::CIARecord & t) inline noexcept
Set value from Group::CIARecord. Works when isnull() is false
Definition at line 2749 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::CIARecord::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2752 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::CIARecordReadFromFile(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::CIARecord& ARTS::Var::CIARecord::value () const inline noexcept
Get value const-ref as Group::CIARecord. Works when isnull() is false
Definition at line 2746 of file autoarts.h.
References v.
value() [2/2]
Group::CIARecord& ARTS::Var::CIARecord::value () inline noexcept
Get value ref as Group::CIARecord. Works when isnull() is false
Definition at line 2743 of file autoarts.h.
References v.
Referenced by ARTS::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CIARecord & var) friend
Output to stream of internal variable
Definition at line 2764 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::CIARecord::p private
Definition at line 2727 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::CIARecord* ARTS::Var::CIARecord::v private
Definition at line 2728 of file autoarts.h.
Referenced by isnull(), value(), and ~CIARecord().
The documentation for this class was generated from the following file:
autoarts.h