ARTS: ARTS::Var::ArrayOfArrayOfPropagationMatrix Class Reference
ARTS::Var::ArrayOfArrayOfPropagationMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfPropagationMatrix () noexcept
ArrayOfArrayOfPropagationMatrix (std::size_t i, void *x) noexcept
ArrayOfArrayOfPropagationMatrix (const Group::ArrayOfArrayOfPropagationMatrix &val) noexcept
~ArrayOfArrayOfPropagationMatrix () noexcept
Group::ArrayOfArrayOfPropagationMatrix & value () noexcept
const Group::ArrayOfArrayOfPropagationMatrix & value () const noexcept
ArrayOfArrayOfPropagationMatrix & operator= (const Group::ArrayOfArrayOfPropagationMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfPropagationMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfPropagationMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 794 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfPropagationMatrix() [1/3]
ARTS::Var::ArrayOfArrayOfPropagationMatrix::ArrayOfArrayOfPropagationMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 799 of file autoarts.h.
ArrayOfArrayOfPropagationMatrix() [2/3]
ARTS::Var::ArrayOfArrayOfPropagationMatrix::ArrayOfArrayOfPropagationMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 802 of file autoarts.h.
ArrayOfArrayOfPropagationMatrix() [3/3]
ARTS::Var::ArrayOfArrayOfPropagationMatrix::ArrayOfArrayOfPropagationMatrix (const Group::ArrayOfArrayOfPropagationMatrix & val) inline noexcept
Construct from Group::ArrayOfArrayOfPropagationMatrix. Leaves islast() true and isnull() false
Definition at line 805 of file autoarts.h.
~ArrayOfArrayOfPropagationMatrix()
ARTS::Var::ArrayOfArrayOfPropagationMatrix::~ArrayOfArrayOfPropagationMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 808 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfPropagationMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 826 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfPropagationMatrix().
isnull()
bool ARTS::Var::ArrayOfArrayOfPropagationMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 823 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfPropagationMatrix().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfPropagationMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 829 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfPropagationMatrix& ARTS::Var::ArrayOfArrayOfPropagationMatrix::operator= (const Group::ArrayOfArrayOfPropagationMatrix & t) inline noexcept
Set value from Group::ArrayOfArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 817 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfPropagationMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 820 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfPropagationMatrix& ARTS::Var::ArrayOfArrayOfPropagationMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 814 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfPropagationMatrix& ARTS::Var::ArrayOfArrayOfPropagationMatrix::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfPropagationMatrix. Works when isnull() is false
Definition at line 811 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfPropagationMatrix & var) friend
Output to stream of internal variable
Definition at line 832 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfPropagationMatrix::p private
Definition at line 795 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfPropagationMatrix* ARTS::Var::ArrayOfArrayOfPropagationMatrix::v private
Definition at line 796 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfPropagationMatrix().
The documentation for this class was generated from the following file:
autoarts.h