ARTS: ARTS::Var::ArrayOfTensor6 Class Reference
ARTS::Var::ArrayOfTensor6 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTensor6 () noexcept
ArrayOfTensor6 (std::size_t i, void *x) noexcept
~ArrayOfTensor6 () noexcept
ArrayOfTensor6 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
ArrayOfTensor6 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor6
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 892 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::ArrayOfTensor6::type = Group::ArrayOfTensor6 private
Definition at line 893 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTensor6() [1/3]
ARTS::Var::ArrayOfTensor6::ArrayOfTensor6 () inline noexcept
Definition at line 897 of file autoarts.h.
ArrayOfTensor6() [2/3]
ARTS::Var::ArrayOfTensor6::ArrayOfTensor6 (std::size_t i, void * x) inline noexcept
Definition at line 898 of file autoarts.h.
~ArrayOfTensor6()
ARTS::Var::ArrayOfTensor6::~ArrayOfTensor6 () inline noexcept
Definition at line 899 of file autoarts.h.
ArrayOfTensor6() [3/3]
ARTS::Var::ArrayOfTensor6::ArrayOfTensor6 (const type & val) inline noexcept
Definition at line 900 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTensor6::islast () const inline noexcept
Definition at line 906 of file autoarts.h.
References ARTS::Var::ArrayOfArrayOfScatteringMetaData::v.
isnull()
bool ARTS::Var::ArrayOfTensor6::isnull () const inline noexcept
Definition at line 905 of file autoarts.h.
References ARTS::Var::ArrayOfArrayOfScatteringMetaData::v.
name()
const Group::String& ARTS::Var::ArrayOfTensor6::name () const inline noexcept
Definition at line 907 of file autoarts.h.
operator=()
ArrayOfTensor6& ARTS::Var::ArrayOfTensor6::operator= (const type & t) inline noexcept
Definition at line 903 of file autoarts.h.
pos()
std::size_t ARTS::Var::ArrayOfTensor6::pos () const inline noexcept
Definition at line 904 of file autoarts.h.
value() [1/2]
const type& ARTS::Var::ArrayOfTensor6::value () const inline noexcept
Definition at line 902 of file autoarts.h.
References ARTS::Var::ArrayOfArrayOfScatteringMetaData::islast(), ARTS::Var::ArrayOfArrayOfScatteringMetaData::isnull(), and ARTS::Var::ArrayOfArrayOfScatteringMetaData::v.
value() [2/2]
type& ARTS::Var::ArrayOfTensor6::value () inline noexcept
Definition at line 901 of file autoarts.h.
Referenced by ARTS::Method::nlte_fieldRescalePopulationLevels().
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTensor6::p private
Definition at line 894 of file autoarts.h.
v
type* ARTS::Var::ArrayOfTensor6::v private
Definition at line 895 of file autoarts.h.
The documentation for this class was generated from the following file:
autoarts.h