ARTS: ARTS::Var::WorkspaceArrayOfTensor5 Class Reference
ARTS::Var::WorkspaceArrayOfTensor5 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTensor5 () noexcept
WorkspaceArrayOfTensor5 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTensor5 () noexcept
WorkspaceArrayOfTensor5 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTensor5 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor5
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 872 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTensor5::type = Group::ArrayOfTensor5 private
Definition at line 873 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTensor5() [1/3]
ARTS::Var::WorkspaceArrayOfTensor5::WorkspaceArrayOfTensor5 () inline noexcept
Definition at line 877 of file autoarts.h.
WorkspaceArrayOfTensor5() [2/3]
ARTS::Var::WorkspaceArrayOfTensor5::WorkspaceArrayOfTensor5 (std::size_t i, void * x) inline noexcept
Definition at line 878 of file autoarts.h.
~WorkspaceArrayOfTensor5()
ARTS::Var::WorkspaceArrayOfTensor5::~WorkspaceArrayOfTensor5 () inline noexcept
Definition at line 879 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTensor5() [3/3]
ARTS::Var::WorkspaceArrayOfTensor5::WorkspaceArrayOfTensor5 (const type & val) inline noexcept
Definition at line 880 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTensor5::islast () const inline noexcept
Definition at line 886 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTensor5().
isnull()
bool ARTS::Var::WorkspaceArrayOfTensor5::isnull () const inline noexcept
Definition at line 885 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTensor5().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTensor5::name () const inline noexcept
Definition at line 887 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTensor5& ARTS::Var::WorkspaceArrayOfTensor5::operator= (const type & t) inline noexcept
Definition at line 883 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTensor5::pos () const inline noexcept
Definition at line 884 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTensor5::value () const inline noexcept
Definition at line 882 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTensor5::value () inline noexcept
Definition at line 881 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTensor5::p private
Definition at line 874 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTensor5::v private
Definition at line 875 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTensor5().
The documentation for this class was generated from the following file:
autoarts.h