ARTS: ARTS::Var::WorkspaceArrayOfTime Class Reference
ARTS::Var::WorkspaceArrayOfTime Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTime () noexcept
WorkspaceArrayOfTime (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTime () noexcept
WorkspaceArrayOfTime (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTime & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTime
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 926 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTime::type = Group::ArrayOfTime private
Definition at line 927 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTime() [1/3]
ARTS::Var::WorkspaceArrayOfTime::WorkspaceArrayOfTime () inline noexcept
Definition at line 931 of file autoarts.h.
WorkspaceArrayOfTime() [2/3]
ARTS::Var::WorkspaceArrayOfTime::WorkspaceArrayOfTime (std::size_t i, void * x) inline noexcept
Definition at line 932 of file autoarts.h.
~WorkspaceArrayOfTime()
ARTS::Var::WorkspaceArrayOfTime::~WorkspaceArrayOfTime () inline noexcept
Definition at line 933 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTime() [3/3]
ARTS::Var::WorkspaceArrayOfTime::WorkspaceArrayOfTime (const type & val) inline noexcept
Definition at line 934 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTime::islast () const inline noexcept
Definition at line 940 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::time_stampsSort(), ARTS::Method::time_stampsSort(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTime().
isnull()
bool ARTS::Var::WorkspaceArrayOfTime::isnull () const inline noexcept
Definition at line 939 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTime().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTime::name () const inline noexcept
Definition at line 941 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTime& ARTS::Var::WorkspaceArrayOfTime::operator= (const type & t) inline noexcept
Definition at line 937 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTime::pos () const inline noexcept
Definition at line 938 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::time_stampsSort(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTime::value () const inline noexcept
Definition at line 936 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTime::value () inline noexcept
Definition at line 935 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), ARTS::Method::time_stampsSort(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTime::p private
Definition at line 928 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTime::v private
Definition at line 929 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTime().
The documentation for this class was generated from the following file:
autoarts.h