ARTS: ARTS::Var::SingleScatteringData Class Reference
ARTS::Var::SingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
SingleScatteringData () noexcept
SingleScatteringData (std::size_t i, void *x) noexcept
SingleScatteringData (const Group::SingleScatteringData &val) noexcept
~SingleScatteringData () noexcept
Group::SingleScatteringData & value () noexcept
const Group::SingleScatteringData & value () const noexcept
SingleScatteringData & operator= (const Group::SingleScatteringData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::SingleScatteringData * v
Friends
std::ostream & operator<< (std::ostream &os, const SingleScatteringData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3852 of file autoarts.h.
Constructor & Destructor Documentation
SingleScatteringData() [1/3]
ARTS::Var::SingleScatteringData::SingleScatteringData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3857 of file autoarts.h.
SingleScatteringData() [2/3]
ARTS::Var::SingleScatteringData::SingleScatteringData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3860 of file autoarts.h.
SingleScatteringData() [3/3]
ARTS::Var::SingleScatteringData::SingleScatteringData (const Group::SingleScatteringData & val) inline noexcept
Construct from Group::SingleScatteringData. Leaves islast() true and isnull() false
Definition at line 3863 of file autoarts.h.
~SingleScatteringData()
ARTS::Var::SingleScatteringData::~SingleScatteringData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3866 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::SingleScatteringData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3884 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~SingleScatteringData().
isnull()
bool ARTS::Var::SingleScatteringData::isnull () const inline noexcept
Return true if there is no data
Definition at line 3881 of file autoarts.h.
References v.
Referenced by ~SingleScatteringData().
name()
const Group::String& ARTS::Var::SingleScatteringData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3887 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
SingleScatteringData& ARTS::Var::SingleScatteringData::operator= (const Group::SingleScatteringData & t) inline noexcept
Set value from Group::SingleScatteringData. Works when isnull() is false
Definition at line 3875 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::SingleScatteringData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3878 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::SingleScatteringData& ARTS::Var::SingleScatteringData::value () const inline noexcept
Get value const-ref as Group::SingleScatteringData. Works when isnull() is false
Definition at line 3872 of file autoarts.h.
References v.
value() [2/2]
Group::SingleScatteringData& ARTS::Var::SingleScatteringData::value () inline noexcept
Get value ref as Group::SingleScatteringData. Works when isnull() is false
Definition at line 3869 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SingleScatteringData & var) friend
Output to stream of internal variable
Definition at line 3890 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::SingleScatteringData::p private
Definition at line 3853 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::SingleScatteringData* ARTS::Var::SingleScatteringData::v private
Definition at line 3854 of file autoarts.h.
Referenced by isnull(), value(), and ~SingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h