ARTS: ARTS::Var::GriddedField3 Class Reference
ARTS::Var::GriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField3 () noexcept
GriddedField3 (std::size_t i, void *x) noexcept
GriddedField3 (const Group::GriddedField3 &val) noexcept
~GriddedField3 () noexcept
Group::GriddedField3 & value () noexcept
const Group::GriddedField3 & value () const noexcept
GriddedField3 & operator= (const Group::GriddedField3 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField3 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField3 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3055 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField3() [1/3]
ARTS::Var::GriddedField3::GriddedField3 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3060 of file autoarts.h.
GriddedField3() [2/3]
ARTS::Var::GriddedField3::GriddedField3 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3063 of file autoarts.h.
GriddedField3() [3/3]
ARTS::Var::GriddedField3::GriddedField3 (const Group::GriddedField3 & val) inline noexcept
Construct from Group::GriddedField3. Leaves islast() true and isnull() false
Definition at line 3066 of file autoarts.h.
~GriddedField3()
ARTS::Var::GriddedField3::~GriddedField3 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3069 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField3::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3087 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::atm_fields_compactCreateFromField(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::lat_gridFromRawField(), ARTS::Agenda::Method::lon_gridFromRawField(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~GriddedField3().
isnull()
bool ARTS::Var::GriddedField3::isnull () const inline noexcept
Return true if there is no data
Definition at line 3084 of file autoarts.h.
References v.
Referenced by ~GriddedField3().
name()
const Group::String& ARTS::Var::GriddedField3::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3090 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField3& ARTS::Var::GriddedField3::operator= (const Group::GriddedField3 & t) inline noexcept
Set value from Group::GriddedField3. Works when isnull() is false
Definition at line 3078 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField3::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3081 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::atm_fields_compactCreateFromField(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::lat_gridFromRawField(), ARTS::Agenda::Method::lon_gridFromRawField(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::GriddedField3& ARTS::Var::GriddedField3::value () const inline noexcept
Get value const-ref as Group::GriddedField3. Works when isnull() is false
Definition at line 3075 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField3& ARTS::Var::GriddedField3::value () inline noexcept
Get value ref as Group::GriddedField3. Works when isnull() is false
Definition at line 3072 of file autoarts.h.
References v.
Referenced by ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::lon_gridFromRawField(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField3 & var) friend
Output to stream of internal variable
Definition at line 3093 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField3::p private
Definition at line 3056 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField3* ARTS::Var::GriddedField3::v private
Definition at line 3057 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField3().
The documentation for this class was generated from the following file:
autoarts.h