ARTS: ARTS::Var::ArrayOfArrayOfScatteringMetaData Class Reference
ARTS::Var::ArrayOfArrayOfScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfScatteringMetaData () noexcept
ArrayOfArrayOfScatteringMetaData (std::size_t i, void *x) noexcept
ArrayOfArrayOfScatteringMetaData (const Group::ArrayOfArrayOfScatteringMetaData &val) noexcept
~ArrayOfArrayOfScatteringMetaData () noexcept
Group::ArrayOfArrayOfScatteringMetaData & value () noexcept
const Group::ArrayOfArrayOfScatteringMetaData & value () const noexcept
ArrayOfArrayOfScatteringMetaData & operator= (const Group::ArrayOfArrayOfScatteringMetaData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfScatteringMetaData * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfScatteringMetaData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 895 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfScatteringMetaData() [1/3]
ARTS::Var::ArrayOfArrayOfScatteringMetaData::ArrayOfArrayOfScatteringMetaData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 900 of file autoarts.h.
ArrayOfArrayOfScatteringMetaData() [2/3]
ARTS::Var::ArrayOfArrayOfScatteringMetaData::ArrayOfArrayOfScatteringMetaData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 903 of file autoarts.h.
ArrayOfArrayOfScatteringMetaData() [3/3]
ARTS::Var::ArrayOfArrayOfScatteringMetaData::ArrayOfArrayOfScatteringMetaData (const Group::ArrayOfArrayOfScatteringMetaData & val) inline noexcept
Construct from Group::ArrayOfArrayOfScatteringMetaData. Leaves islast() true and isnull() false
Definition at line 906 of file autoarts.h.
~ArrayOfArrayOfScatteringMetaData()
ARTS::Var::ArrayOfArrayOfScatteringMetaData::~ArrayOfArrayOfScatteringMetaData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 909 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfScatteringMetaData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 927 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfScatteringMetaData().
isnull()
bool ARTS::Var::ArrayOfArrayOfScatteringMetaData::isnull () const inline noexcept
Return true if there is no data
Definition at line 924 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfScatteringMetaData().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfScatteringMetaData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 930 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfScatteringMetaData& ARTS::Var::ArrayOfArrayOfScatteringMetaData::operator= (const Group::ArrayOfArrayOfScatteringMetaData & t) inline noexcept
Set value from Group::ArrayOfArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 918 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfScatteringMetaData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 921 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfScatteringMetaData& ARTS::Var::ArrayOfArrayOfScatteringMetaData::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 915 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfScatteringMetaData& ARTS::Var::ArrayOfArrayOfScatteringMetaData::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 912 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfScatteringMetaData & var) friend
Output to stream of internal variable
Definition at line 933 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfScatteringMetaData::p private
Definition at line 896 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfScatteringMetaData* ARTS::Var::ArrayOfArrayOfScatteringMetaData::v private
Definition at line 897 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h