ARTS: ARTS::Var::ArrayOfTensor4 Class Reference
ARTS::Var::ArrayOfTensor4 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTensor4 () noexcept
ArrayOfTensor4 (std::size_t i, void *x) noexcept
ArrayOfTensor4 (const Group::ArrayOfTensor4 &val) noexcept
~ArrayOfTensor4 () noexcept
Group::ArrayOfTensor4 & value () noexcept
const Group::ArrayOfTensor4 & value () const noexcept
ArrayOfTensor4 & operator= (const Group::ArrayOfTensor4 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfTensor4 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfTensor4 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2350 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTensor4() [1/3]
ARTS::Var::ArrayOfTensor4::ArrayOfTensor4 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2355 of file autoarts.h.
ArrayOfTensor4() [2/3]
ARTS::Var::ArrayOfTensor4::ArrayOfTensor4 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2358 of file autoarts.h.
ArrayOfTensor4() [3/3]
ARTS::Var::ArrayOfTensor4::ArrayOfTensor4 (const Group::ArrayOfTensor4 & val) inline noexcept
Construct from Group::ArrayOfTensor4. Leaves islast() true and isnull() false
Definition at line 2361 of file autoarts.h.
~ArrayOfTensor4()
ARTS::Var::ArrayOfTensor4::~ArrayOfTensor4 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2364 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTensor4::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2382 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfTensor4().
isnull()
bool ARTS::Var::ArrayOfTensor4::isnull () const inline noexcept
Return true if there is no data
Definition at line 2379 of file autoarts.h.
References v.
Referenced by ~ArrayOfTensor4().
name()
const Group::String& ARTS::Var::ArrayOfTensor4::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2385 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfTensor4& ARTS::Var::ArrayOfTensor4::operator= (const Group::ArrayOfTensor4 & t) inline noexcept
Set value from Group::ArrayOfTensor4. Works when isnull() is false
Definition at line 2373 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTensor4::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2376 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfTensor4& ARTS::Var::ArrayOfTensor4::value () const inline noexcept
Get value const-ref as Group::ArrayOfTensor4. Works when isnull() is false
Definition at line 2370 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfTensor4& ARTS::Var::ArrayOfTensor4::value () inline noexcept
Get value ref as Group::ArrayOfTensor4. Works when isnull() is false
Definition at line 2367 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfTensor4 & var) friend
Output to stream of internal variable
Definition at line 2388 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTensor4::p private
Definition at line 2351 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfTensor4* ARTS::Var::ArrayOfTensor4::v private
Definition at line 2352 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTensor4().
The documentation for this class was generated from the following file:
autoarts.h