ARTS: ARTS::Var::WorkspaceArrayOfSparse Class Reference
ARTS::Var::WorkspaceArrayOfSparse Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfSparse () noexcept
WorkspaceArrayOfSparse (std::size_t i, void *x) noexcept
~WorkspaceArrayOfSparse () noexcept
WorkspaceArrayOfSparse (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfSparse & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfSparse
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 764 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfSparse::type = Group::ArrayOfSparse private
Definition at line 765 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfSparse() [1/3]
ARTS::Var::WorkspaceArrayOfSparse::WorkspaceArrayOfSparse () inline noexcept
Definition at line 769 of file autoarts.h.
WorkspaceArrayOfSparse() [2/3]
ARTS::Var::WorkspaceArrayOfSparse::WorkspaceArrayOfSparse (std::size_t i, void * x) inline noexcept
Definition at line 770 of file autoarts.h.
~WorkspaceArrayOfSparse()
ARTS::Var::WorkspaceArrayOfSparse::~WorkspaceArrayOfSparse () inline noexcept
Definition at line 771 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfSparse() [3/3]
ARTS::Var::WorkspaceArrayOfSparse::WorkspaceArrayOfSparse (const type & val) inline noexcept
Definition at line 772 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfSparse::islast () const inline noexcept
Definition at line 778 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfSparse().
isnull()
bool ARTS::Var::WorkspaceArrayOfSparse::isnull () const inline noexcept
Definition at line 777 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfSparse().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfSparse::name () const inline noexcept
Definition at line 779 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfSparse& ARTS::Var::WorkspaceArrayOfSparse::operator= (const type & t) inline noexcept
Definition at line 775 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfSparse::pos () const inline noexcept
Definition at line 776 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfSparse::value () const inline noexcept
Definition at line 774 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfSparse::value () inline noexcept
Definition at line 773 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfSparse::p private
Definition at line 766 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfSparse::v private
Definition at line 767 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfSparse().
The documentation for this class was generated from the following file:
autoarts.h