ARTS: ARTS::Var::WorkspaceArrayOfVector Class Reference
ARTS::Var::WorkspaceArrayOfVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfVector () noexcept
WorkspaceArrayOfVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfVector () noexcept
WorkspaceArrayOfVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 962 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfVector::type = Group::ArrayOfVector private
Definition at line 963 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfVector() [1/3]
ARTS::Var::WorkspaceArrayOfVector::WorkspaceArrayOfVector () inline noexcept
Definition at line 967 of file autoarts.h.
WorkspaceArrayOfVector() [2/3]
ARTS::Var::WorkspaceArrayOfVector::WorkspaceArrayOfVector (std::size_t i, void * x) inline noexcept
Definition at line 968 of file autoarts.h.
~WorkspaceArrayOfVector()
ARTS::Var::WorkspaceArrayOfVector::~WorkspaceArrayOfVector () inline noexcept
Definition at line 969 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfVector() [3/3]
ARTS::Var::WorkspaceArrayOfVector::WorkspaceArrayOfVector (const type & val) inline noexcept
Definition at line 970 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfVector::islast () const inline noexcept
Definition at line 976 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::time_stampsSort(), ARTS::Method::time_stampsSort(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfVector::isnull () const inline noexcept
Definition at line 975 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfVector::name () const inline noexcept
Definition at line 977 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceArrayOfVector& ARTS::Var::WorkspaceArrayOfVector::operator= (const type & t) inline noexcept
Definition at line 973 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfVector::pos () const inline noexcept
Definition at line 974 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::time_stampsSort(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfVector::value () const inline noexcept
Definition at line 972 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfVector::value () inline noexcept
Definition at line 971 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Select(), ARTS::Method::time_stampsSort(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfVector::p private
Definition at line 964 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfVector::v private
Definition at line 965 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfVector().
The documentation for this class was generated from the following file:
autoarts.h