ARTS: QuantumNumbers Class Reference
QuantumNumbers Class Reference
Container class for Quantum Numbers.
#include <quantum.h>
Public Types
typedef std::array< Rational, Index(QuantumNumberType::FINAL)> QuantumContainer
Public Member Functions
constexpr QuantumNumbers () noexcept
Initializer with undefined values.
constexpr QuantumNumbers (Rational J, Rational N, Rational v) noexcept
constexpr Rational operator[] (const Index qn) const noexcept
Access operator.
constexpr Rational operator[] (const QuantumNumberType qn) const noexcept
Access operator.
constexpr Rational & operator[] (const Index qn) noexcept
Access operator.
constexpr Rational & operator[] (const QuantumNumberType qn) noexcept
Access operator.
constexpr void Set (Index qn, Rational r)
Set quantum number at position.
constexpr void Set (QuantumNumberType qn, Rational r)
Set quantum number at position.
constexpr void Set (const std::string_view qn, Rational r)
Set quantum number at position.
constexpr const QuantumContainer & GetNumbers () const
Get the numbers.
constexpr Index nNumbers () const
The number of defined quantum numbers.
constexpr bool Compare (const QuantumNumbers &qn) const
Compare Quantum Numbers.
String toString () const
Returns this as a string.
Private Attributes
QuantumContainer mqnumbers
Detailed Description
Container class for Quantum Numbers.
Definition at line 111 of file quantum.h.
Member Typedef Documentation
QuantumContainer
typedef std::array<Rational, Index(QuantumNumberType::FINAL)> QuantumNumbers::QuantumContainer
Definition at line 114 of file quantum.h.
Constructor & Destructor Documentation
QuantumNumbers() [1/2]
constexpr QuantumNumbers::QuantumNumbers () inline constexpr noexcept
Initializer with undefined values.
Definition at line 117 of file quantum.h.
References RATIONAL_UNDEFINED.
QuantumNumbers() [2/2]
constexpr QuantumNumbers::QuantumNumbers (Rational J, Rational N, Rational v) inline constexpr noexcept
Definition at line 139 of file quantum.h.
References N, RATIONAL_UNDEFINED, and v().
Member Function Documentation
Compare()
constexpr bool QuantumNumbers::Compare (const QuantumNumbers & qn) const inline constexpr
Compare Quantum Numbers.
Compare all quantum numbers in mqnumbers and qn.mqnumbers Both numbers must be defined or the comparison is ignored
Parameters
[in] qn Quantum Numbers to compare to
Returns
true For a match
false Otherwise
Definition at line 247 of file quantum.h.
References mqnumbers.
GetNumbers()
constexpr const QuantumContainer& QuantumNumbers::GetNumbers () const inline constexpr
Get the numbers.
Returns
const QuantumContainer& All the numbers
Definition at line 225 of file quantum.h.
References mqnumbers.
Referenced by operator==(), and xml_write_to_stream().
nNumbers()
constexpr Index QuantumNumbers::nNumbers () const inline constexpr
The number of defined quantum numbers.
Returns
Index Count of defined numbers
Definition at line 231 of file quantum.h.
References mqnumbers.
operator[]() [1/4]
constexpr Rational QuantumNumbers::operator[] (const Index qn) const inline constexpr noexcept
Access operator.
Parameters
[in] qn Index Pos to access
Returns
constexpr Rational Copy of value at pos
Definition at line 163 of file quantum.h.
References mqnumbers.
operator[]() [2/4]
constexpr Rational& QuantumNumbers::operator[] (const Index qn) inline constexpr noexcept
Access operator.
Parameters
[in] qn Index Pos to access
Returns
constexpr Rational Copy of value at pos
Definition at line 181 of file quantum.h.
References mqnumbers.
operator[]() [3/4]
constexpr Rational QuantumNumbers::operator[] (const QuantumNumberType qn) const inline constexpr noexcept
Access operator.
Parameters
qn[in] Index Pos to access
Returns
constexpr Rational Copy of value at pos
Definition at line 172 of file quantum.h.
References mqnumbers.
operator[]() [4/4]
constexpr Rational& QuantumNumbers::operator[] (const QuantumNumberType qn) inline constexpr noexcept
Access operator.
Parameters
qn[in] Index Pos to access
Returns
constexpr Rational Copy of value at pos
Definition at line 190 of file quantum.h.
References mqnumbers.
Set() [1/3]
constexpr void QuantumNumbers::Set (const std::string_view qn, Rational r) inline constexpr
Set quantum number at position.
Parameters
[in] qn String Pos to set at by name
[in] r Rational to set
Definition at line 217 of file quantum.h.
References mqnumbers.
Set() [2/3]
constexpr void QuantumNumbers::Set (Index qn, Rational r) inline constexpr
Set quantum number at position.
Parameters
[in] qn Index Pos to set at
[in] r Rational to set
Definition at line 199 of file quantum.h.
References mqnumbers.
Referenced by ArtsXMLTag::get_attribute_value(), operator>>(), QuantumFieldDescription::Parse(), postprocess_group1_hitran(), postprocess_group2_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), and test_zeeman().
Set() [3/3]
constexpr void QuantumNumbers::Set (QuantumNumberType qn, Rational r) inline constexpr
Set quantum number at position.
Parameters
[in] qn Index Pos to set at
[in] r Rational to set
Definition at line 208 of file quantum.h.
References mqnumbers.
toString()
String QuantumNumbers::toString () const
Returns this as a string.
Definition at line 295 of file quantum.cc.
Member Data Documentation
mqnumbers
QuantumContainer QuantumNumbers::mqnumbers private
Definition at line 262 of file quantum.h.
Referenced by Compare(), GetNumbers(), nNumbers(), operator[](), and Set().
The documentation for this class was generated from the following files:
quantum.h
quantum.cc