ARTS: MRecord Class Reference
MRecord Class Reference
Method runtime data.
#include <agenda_class.h>
Public Member Functions
MRecord ()
MRecord (const MRecord &x)
MRecord (const Index id, const ArrayOfIndex &output, const ArrayOfIndex &input, const TokVal &setvalue, const Agenda &tasks, bool internal=false)
Index Id () const
const ArrayOfIndex & Out () const
const ArrayOfIndex & In () const
const TokVal & SetValue () const
const Agenda & Tasks () const
bool isInternal () const
Indicates the origin of this method.
MRecord & operator= (const MRecord &x)
Assignment operator for MRecord.
void ginput_only (ArrayOfIndex &ginonly) const
Get list of generic input only WSVs.
void print (ostream &os, const String &indent) const
Print an MRecord.
Private Attributes
Index mid
Method id.
ArrayOfIndex moutput
Output workspace variables.
ArrayOfIndex minput
Input workspace variables.
TokVal msetvalue
Keyword value for Set methods.
Agenda mtasks
An agenda, which can be given in the controlfile instead of keywords.
bool minternal
Flag if this method is called internally by the engine.
Detailed Description
Method runtime data.
In contrast to MdRecord, an object of this class contains the runtime information for one method: The method id. This is all that the engine needs to execute the stack of methods.
An MRecord includes a member magenda, which can contain an entire agenda, i.e., a list of other MRecords.
Author
Stefan Buehler
Definition at line 121 of file agenda_class.h.
Constructor & Destructor Documentation
MRecord() [1/3]
MRecord::MRecord () inline
Definition at line 123 of file agenda_class.h.
MRecord() [2/3]
MRecord::MRecord (const MRecord & x) inline
Definition at line 132 of file agenda_class.h.
MRecord() [3/3]
MRecord::MRecord (const Index id, const ArrayOfIndex & output, const ArrayOfIndex & input, const TokVal & setvalue, const Agenda & tasks, bool internal = false) inline
Definition at line 141 of file agenda_class.h.
Member Function Documentation
ginput_only()
void MRecord::ginput_only (ArrayOfIndex & ginonly) const inline
Get list of generic input only WSVs.
This function returns an array with the indexes of WSVs which are only input variables but not output.
Parameters
[out] ginonly Index array of input only WSVs.
Author
Oliver Lemke
Date
2008-02-27
Definition at line 219 of file agenda_class.h.
References minput, and moutput.
Id()
Index MRecord::Id () const inline
Definition at line 155 of file agenda_class.h.
References mid.
Referenced by Agenda::execute(), Agenda::is_input(), Agenda::is_output(), and print().
In()
const ArrayOfIndex& MRecord::In () const inline
Definition at line 157 of file agenda_class.h.
References minput.
Referenced by abs_cia_dataAddCIARecord_g(), abs_cia_dataReadFromCIA_g(), abs_cia_dataReadFromXML_g(), abs_cont_descriptionAppend_g(), abs_hitran_relmat_dataReadHitranRelmatDataAndLines_g(), abs_lines_per_speciesAdaptHitranLineMixing_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLevel_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLines_g(), abs_lines_per_speciesChangeBaseParameterForSpecies_g(), abs_lines_per_speciesCompact_g(), abs_lines_per_speciesCreateFromLines_g(), abs_lines_per_speciesHitranLineMixingAdaptationData_g(), abs_lines_per_speciesMakeManualMirroringSpecies_g(), abs_lines_per_speciesReadSpeciesSplitCatalog_g(), abs_lines_per_speciesReadSplitCatalog_g(), abs_lines_per_speciesSetBaseParameterForMatchingLevel_g(), abs_lines_per_speciesSetBaseParameterForMatchingLevels_g(), abs_lines_per_speciesSetCutoff_g(), abs_lines_per_speciesSetCutoffForMatch_g(), abs_lines_per_speciesSetCutoffForSpecies_g(), abs_lines_per_speciesSetEmpty_g(), abs_lines_per_speciesSetLinemixingLimit_g(), abs_lines_per_speciesSetLinemixingLimitForMatch_g(), abs_lines_per_speciesSetLinemixingLimitForSpecies_g(), abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines_g(), abs_lines_per_speciesSetLineShapeType_g(), abs_lines_per_speciesSetLineShapeTypeForMatch_g(), abs_lines_per_speciesSetLineShapeTypeForSpecies_g(), abs_lines_per_speciesSetMirroring_g(), abs_lines_per_speciesSetMirroringForMatch_g(), abs_lines_per_speciesSetMirroringForSpecies_g(), abs_lines_per_speciesSetNormalization_g(), abs_lines_per_speciesSetNormalizationForMatch_g(), abs_lines_per_speciesSetNormalizationForSpecies_g(), abs_lines_per_speciesSetPopulation_g(), abs_lines_per_speciesSetPopulationForMatch_g(), abs_lines_per_speciesSetPopulationForSpecies_g(), abs_lines_per_speciesSetQuantumNumberForMatch_g(), abs_lines_per_speciesSetT0_g(), abs_lines_per_speciesSetT0ForMatch_g(), abs_lines_per_speciesSetT0ForSpecies_g(), abs_lines_per_speciesSetZeemanCoefficients_g(), abs_lines_per_speciesTruncateQuantumNumbers_g(), abs_lines_per_speciesWriteSpeciesSplitXML_g(), abs_lines_per_speciesWriteSplitXML_g(), abs_linesAppendWithLines_g(), abs_linesChangeBaseParameterForMatchingLevel_g(), abs_linesChangeBaseParameterForMatchingLevels_g(), abs_linesChangeBaseParameterForMatchingLines_g(), abs_linesCompact_g(), abs_linesDeleteBadF0_g(), abs_linesDeleteLinesWithQuantumNumberAbove_g(), abs_linesDeleteWithLines_g(), abs_linesKeepBand_g(), abs_linesPrintDefinedQuantumNumbers_g(), abs_linesReadSpeciesSplitCatalog_g(), abs_linesRemoveBand_g(), abs_linesReplaceWithLines_g(), abs_linesSetBaseParameterForMatchingLevel_g(), abs_linesSetBaseParameterForMatchingLevels_g(), abs_linesSetBaseParameterForMatchingLines_g(), abs_linesSetCutoff_g(), abs_linesSetCutoffForMatch_g(), abs_linesSetLinemixingLimit_g(), abs_linesSetLinemixingLimitForMatch_g(), abs_linesSetLineShapeModelParametersForMatchingLines_g(), abs_linesSetLineShapeType_g(), abs_linesSetLineShapeTypeForMatch_g(), abs_linesSetMirroring_g(), abs_linesSetMirroringForMatch_g(), abs_linesSetNormalization_g(), abs_linesSetNormalizationForMatch_g(), abs_linesSetPopulation_g(), abs_linesSetPopulationForMatch_g(), abs_linesSetQuantumNumberForMatch_g(), abs_linesSetT0_g(), abs_linesSetT0ForMatch_g(), abs_linesSetZeemanCoefficients_g(), abs_linesWriteSpeciesSplitXML_g(), abs_linesWriteSplitXML_g(), abs_lookupAdapt_g(), abs_lookupCalc_g(), abs_lookupSetup_g(), abs_lookupSetupBatch_g(), abs_lookupSetupWide_g(), abs_lookupTestAccMC_g(), abs_lookupTestAccuracy_g(), abs_nlteFromRaw_g(), abs_speciesAdd2_g(), abs_speciesAdd_g(), abs_speciesDefineAllInScenario_g(), abs_speciesSet_g(), abs_vecAddGas_g(), abs_xsec_agenda_checkedCalc_g(), abs_xsec_per_speciesAddCIA_g(), abs_xsec_per_speciesAddConts_g(), abs_xsec_per_speciesAddHitranXsec_g(), abs_xsec_per_speciesAddLines_g(), abs_xsec_per_speciesAddPredefinedO2MPM2020_g(), abs_xsec_per_speciesInit_g(), AbsInputFromAtmFields_g(), AddZaAa_g(), AgendaAppend_g(), AgendaExecute_g(), AgendaExecuteExclusive_g(), AngularGridsSetFluxCalc_g(), antenna_responseGaussian_g(), antenna_responseVaryingGaussian_g(), AntennaConstantGaussian1D_g(), AntennaMultiBeamsToPencilBeams_g(), Append_sg_ArrayOfAbsorptionLinesAbsorptionLines_g(), Append_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfAgendaAgenda_g(), Append_sg_ArrayOfAgendaArrayOfAgenda_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Append_sg_ArrayOfArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Append_sg_ArrayOfArrayOfStringArrayOfString_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Append_sg_ArrayOfArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Append_sg_ArrayOfArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Append_sg_ArrayOfCIARecordCIARecord_g(), Append_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfGriddedField1GriddedField1_g(), Append_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfGriddedField2GriddedField2_g(), Append_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfGriddedField3GriddedField3_g(), Append_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Append_sg_ArrayOfGriddedField4GriddedField4_g(), Append_sg_ArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfIndexIndex_g(), Append_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Append_sg_ArrayOfJacobianTargetJacobianTarget_g(), Append_sg_ArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfMatrixMatrix_g(), Append_sg_ArrayOfPpathArrayOfPpath_g(), Append_sg_ArrayOfPpathPpath_g(), Append_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfPropagationMatrixPropagationMatrix_g(), Append_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Append_sg_ArrayOfQuantumIdentifierQuantumIdentifier_g(), Append_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfRadiationVectorRadiationVector_g(), Append_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Append_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfScatteringMetaDataScatteringMetaData_g(), Append_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfSingleScatteringDataSingleScatteringData_g(), Append_sg_ArrayOfSparseArrayOfSparse_g(), Append_sg_ArrayOfSparseSparse_g(), Append_sg_ArrayOfSpeciesTagArrayOfSpeciesTag_g(), Append_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfStokesVectorStokesVector_g(), Append_sg_ArrayOfStringArrayOfString_g(), Append_sg_ArrayOfStringString_g(), Append_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Append_sg_ArrayOfTelsemAtlasTelsemAtlas_g(), Append_sg_ArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfTensor3Tensor3_g(), Append_sg_ArrayOfTensor4ArrayOfTensor4_g(), Append_sg_ArrayOfTensor4Tensor4_g(), Append_sg_ArrayOfTensor5ArrayOfTensor5_g(), Append_sg_ArrayOfTensor5Tensor5_g(), Append_sg_ArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfTensor6Tensor6_g(), Append_sg_ArrayOfTensor7ArrayOfTensor7_g(), Append_sg_ArrayOfTensor7Tensor7_g(), Append_sg_ArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfTimeTime_g(), Append_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfTransmissionMatrixTransmissionMatrix_g(), Append_sg_ArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfVectorVector_g(), Append_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Append_sg_MatrixMatrix_g(), Append_sg_MatrixVector_g(), Append_sg_StringString_g(), Append_sg_Tensor3Matrix_g(), Append_sg_Tensor3Tensor3_g(), Append_sg_Tensor4Tensor3_g(), Append_sg_Tensor4Tensor4_g(), Append_sg_VectorNumeric_g(), Append_sg_VectorVector_g(), ArrayOfAgendaExecute_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField1_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField2_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField3_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField4_g(), ArrayOfIndexLinSpace_g(), ArrayOfIndexSetConstant_g(), ArrayOfQuantumIdentifierFromLines_g(), ArrayOfQuantumIdentifierSet_g(), ArrayOfTimeNLinSpace_g(), ArrayOfTimeSetConstant_g(), atm_fields_compactAddConstant_g(), atm_fields_compactAddSpecies_g(), atm_fields_compactCleanup_g(), atm_fields_compactCreateFromField_g(), atm_fields_compactFromMatrix_g(), atm_gridsFromZRaw_g(), AtmFieldPerturb_g(), AtmFieldPerturbAtmGrids_g(), AtmFieldPRegrid_sg_Tensor3Tensor3_g(), AtmFieldPRegrid_sg_Tensor4Tensor4_g(), atmfields_checkedCalc_g(), AtmFieldsAndParticleBulkPropFieldFromCompact_g(), AtmFieldsCalc_g(), AtmFieldsCalcExpand1D_g(), AtmFieldsExpand1D_g(), AtmFieldsExtract1D_g(), AtmFieldsRefinePgrid_g(), atmgeom_checkedCalc_g(), AtmRawRead_g(), AtmWithNLTERawRead_g(), avkCalc_g(), backend_channel_responseFlat_g(), backend_channel_responseGaussian_g(), batch_atm_fields_compactAddConstant_g(), batch_atm_fields_compactAddSpecies_g(), batch_atm_fields_compactCleanup_g(), batch_atm_fields_compactFromArrayOfMatrix_g(), CIAInfo_g(), CIARecordReadFromFile_g(), cloudbox_checkedCalc_g(), cloudbox_field_monoIterate_g(), cloudbox_field_monoOptimizeReverse_g(), cloudbox_field_monoSetConst_g(), cloudbox_fieldCrop_g(), cloudbox_fieldSetClearsky_g(), cloudbox_fieldSetConst_g(), cloudbox_fieldSetConstPerFreq_g(), cloudbox_fieldSetFromPrecalc_g(), cloudbox_fieldUpdate1D_g(), cloudbox_fieldUpdateSeq1D_g(), cloudbox_fieldUpdateSeq1DPP_g(), cloudbox_fieldUpdateSeq3D_g(), cloudboxOff_g(), cloudboxSetAutomatically_g(), cloudboxSetFullAtm_g(), cloudboxSetManually_g(), cloudboxSetManuallyAltitude_g(), collision_coefficientsFromSplitFiles_g(), Compare_sg_ArrayOfMatrixArrayOfMatrix_g(), Compare_sg_ArrayOfTensor7ArrayOfTensor7_g(), Compare_sg_ArrayOfVectorArrayOfVector_g(), Compare_sg_GriddedField3GriddedField3_g(), Compare_sg_MatrixMatrix_g(), Compare_sg_NumericNumeric_g(), Compare_sg_SingleScatteringDataSingleScatteringData_g(), Compare_sg_SparseSparse_g(), Compare_sg_Tensor3Tensor3_g(), Compare_sg_Tensor4Tensor4_g(), Compare_sg_Tensor5Tensor5_g(), Compare_sg_Tensor7Tensor7_g(), Compare_sg_VectorVector_g(), CompareRelative_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), CompareRelative_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), CompareRelative_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), CompareRelative_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), CompareRelative_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), CompareRelative_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), CompareRelative_sg_ArrayOfMatrixArrayOfMatrix_g(), CompareRelative_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), CompareRelative_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), CompareRelative_sg_ArrayOfTensor3ArrayOfTensor3_g(), CompareRelative_sg_ArrayOfTensor4ArrayOfTensor4_g(), CompareRelative_sg_ArrayOfTensor6ArrayOfTensor6_g(), CompareRelative_sg_ArrayOfTensor7ArrayOfTensor7_g(), CompareRelative_sg_ArrayOfVectorArrayOfVector_g(), CompareRelative_sg_EnergyLevelMapEnergyLevelMap_g(), CompareRelative_sg_MatrixMatrix_g(), CompareRelative_sg_NumericNumeric_g(), CompareRelative_sg_PropagationMatrixPropagationMatrix_g(), CompareRelative_sg_StokesVectorStokesVector_g(), CompareRelative_sg_Tensor3Tensor3_g(), CompareRelative_sg_Tensor4Tensor4_g(), CompareRelative_sg_Tensor5Tensor5_g(), CompareRelative_sg_Tensor6Tensor6_g(), CompareRelative_sg_Tensor7Tensor7_g(), CompareRelative_sg_VectorVector_g(), complex_refr_indexConstant_g(), complex_refr_indexIceMatzler06_g(), complex_refr_indexIceWarren84_g(), complex_refr_indexWaterLiebe93_g(), Copy_sg_AbsorptionLines_g(), Copy_sg_Agenda_g(), Copy_sg_ArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfAgenda_g(), Copy_sg_ArrayOfArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfArrayOfGriddedField1_g(), Copy_sg_ArrayOfArrayOfGriddedField2_g(), Copy_sg_ArrayOfArrayOfGriddedField3_g(), Copy_sg_ArrayOfArrayOfIndex_g(), Copy_sg_ArrayOfArrayOfMatrix_g(), Copy_sg_ArrayOfArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfArrayOfRadiationVector_g(), Copy_sg_ArrayOfArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfArrayOfSpeciesTag_g(), Copy_sg_ArrayOfArrayOfStokesVector_g(), Copy_sg_ArrayOfArrayOfString_g(), Copy_sg_ArrayOfArrayOfTensor3_g(), Copy_sg_ArrayOfArrayOfTensor6_g(), Copy_sg_ArrayOfArrayOfTime_g(), Copy_sg_ArrayOfArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfArrayOfVector_g(), Copy_sg_ArrayOfCIARecord_g(), Copy_sg_ArrayOfGriddedField1_g(), Copy_sg_ArrayOfGriddedField2_g(), Copy_sg_ArrayOfGriddedField3_g(), Copy_sg_ArrayOfGriddedField4_g(), Copy_sg_ArrayOfIndex_g(), Copy_sg_ArrayOfJacobianTarget_g(), Copy_sg_ArrayOfMatrix_g(), Copy_sg_ArrayOfPpath_g(), Copy_sg_ArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfQuantumIdentifier_g(), Copy_sg_ArrayOfRadiationVector_g(), Copy_sg_ArrayOfRetrievalQuantity_g(), Copy_sg_ArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfSparse_g(), Copy_sg_ArrayOfSpeciesTag_g(), Copy_sg_ArrayOfStokesVector_g(), Copy_sg_ArrayOfString_g(), Copy_sg_ArrayOfTelsemAtlas_g(), Copy_sg_ArrayOfTensor3_g(), Copy_sg_ArrayOfTensor4_g(), Copy_sg_ArrayOfTensor5_g(), Copy_sg_ArrayOfTensor6_g(), Copy_sg_ArrayOfTensor7_g(), Copy_sg_ArrayOfTime_g(), Copy_sg_ArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfVector_g(), Copy_sg_ArrayOfXsecRecord_g(), Copy_sg_CIARecord_g(), Copy_sg_CovarianceMatrix_g(), Copy_sg_EnergyLevelMap_g(), Copy_sg_GasAbsLookup_g(), Copy_sg_GriddedField1_g(), Copy_sg_GriddedField2_g(), Copy_sg_GriddedField3_g(), Copy_sg_GriddedField4_g(), Copy_sg_GriddedField5_g(), Copy_sg_GriddedField6_g(), Copy_sg_GridPos_g(), Copy_sg_HitranRelaxationMatrixData_g(), Copy_sg_Index_g(), Copy_sg_JacobianTarget_g(), Copy_sg_MapOfErrorCorrectedSuddenData_g(), Copy_sg_Matrix_g(), Copy_sg_MCAntenna_g(), Copy_sg_Numeric_g(), Copy_sg_Ppath_g(), Copy_sg_PropagationMatrix_g(), Copy_sg_QuantumIdentifier_g(), Copy_sg_RadiationVector_g(), Copy_sg_Rational_g(), Copy_sg_ScatteringMetaData_g(), Copy_sg_SingleScatteringData_g(), Copy_sg_Sparse_g(), Copy_sg_SpeciesIsotopologueRatios_g(), Copy_sg_StokesVector_g(), Copy_sg_String_g(), Copy_sg_TelsemAtlas_g(), Copy_sg_Tensor3_g(), Copy_sg_Tensor4_g(), Copy_sg_Tensor5_g(), Copy_sg_Tensor6_g(), Copy_sg_Tensor7_g(), Copy_sg_TessemNN_g(), Copy_sg_Time_g(), Copy_sg_Timer_g(), Copy_sg_TransmissionMatrix_g(), Copy_sg_Vector_g(), Copy_sg_Verbosity_g(), covmat1D_sg_Matrix_g(), covmat1D_sg_Sparse_g(), covmat1DMarkov_sg_MatrixMatrix_g(), covmat1DMarkov_sg_SparseSparse_g(), covmat_seAddBlock_sg_Matrix_g(), covmat_seAddBlock_sg_Sparse_g(), covmat_seAddInverseBlock_sg_Matrix_g(), covmat_seAddInverseBlock_sg_Sparse_g(), covmat_seSet_sg_CovarianceMatrix_g(), covmat_seSet_sg_Matrix_g(), covmat_seSet_sg_Sparse_g(), covmat_soCalc_g(), covmat_ssCalc_g(), covmat_sxAddBlock_sg_Matrix_g(), covmat_sxAddBlock_sg_Sparse_g(), covmat_sxAddInverseBlock_sg_Matrix_g(), covmat_sxAddInverseBlock_sg_Sparse_g(), covmat_sxExtractSqrtDiagonal_g(), covmat_sxSet_sg_CovarianceMatrix_g(), covmat_sxSet_sg_Matrix_g(), covmat_sxSet_sg_Sparse_g(), covmatDiagonal_sg_MatrixMatrix_g(), covmatDiagonal_sg_SparseSparse_g(), Delete_sg_AbsorptionLines_g(), Delete_sg_Agenda_g(), Delete_sg_ArrayOfAbsorptionLines_g(), Delete_sg_ArrayOfAgenda_g(), Delete_sg_ArrayOfArrayOfAbsorptionLines_g(), Delete_sg_ArrayOfArrayOfGriddedField1_g(), Delete_sg_ArrayOfArrayOfGriddedField2_g(), Delete_sg_ArrayOfArrayOfGriddedField3_g(), Delete_sg_ArrayOfArrayOfIndex_g(), Delete_sg_ArrayOfArrayOfMatrix_g(), Delete_sg_ArrayOfArrayOfPropagationMatrix_g(), Delete_sg_ArrayOfArrayOfRadiationVector_g(), Delete_sg_ArrayOfArrayOfScatteringMetaData_g(), Delete_sg_ArrayOfArrayOfSingleScatteringData_g(), Delete_sg_ArrayOfArrayOfSpeciesTag_g(), Delete_sg_ArrayOfArrayOfStokesVector_g(), Delete_sg_ArrayOfArrayOfString_g(), Delete_sg_ArrayOfArrayOfTensor3_g(), Delete_sg_ArrayOfArrayOfTensor6_g(), Delete_sg_ArrayOfArrayOfTime_g(), Delete_sg_ArrayOfArrayOfTransmissionMatrix_g(), Delete_sg_ArrayOfArrayOfVector_g(), Delete_sg_ArrayOfCIARecord_g(), Delete_sg_ArrayOfGriddedField1_g(), Delete_sg_ArrayOfGriddedField2_g(), Delete_sg_ArrayOfGriddedField3_g(), Delete_sg_ArrayOfGriddedField4_g(), Delete_sg_ArrayOfIndex_g(), Delete_sg_ArrayOfJacobianTarget_g(), Delete_sg_ArrayOfMatrix_g(), Delete_sg_ArrayOfPpath_g(), Delete_sg_ArrayOfPropagationMatrix_g(), Delete_sg_ArrayOfQuantumIdentifier_g(), Delete_sg_ArrayOfRadiationVector_g(), Delete_sg_ArrayOfRetrievalQuantity_g(), Delete_sg_ArrayOfScatteringMetaData_g(), Delete_sg_ArrayOfSingleScatteringData_g(), Delete_sg_ArrayOfSparse_g(), Delete_sg_ArrayOfSpeciesTag_g(), Delete_sg_ArrayOfStokesVector_g(), Delete_sg_ArrayOfString_g(), Delete_sg_ArrayOfTelsemAtlas_g(), Delete_sg_ArrayOfTensor3_g(), Delete_sg_ArrayOfTensor4_g(), Delete_sg_ArrayOfTensor5_g(), Delete_sg_ArrayOfTensor6_g(), Delete_sg_ArrayOfTensor7_g(), Delete_sg_ArrayOfTime_g(), Delete_sg_ArrayOfTransmissionMatrix_g(), Delete_sg_ArrayOfVector_g(), Delete_sg_ArrayOfXsecRecord_g(), Delete_sg_CIARecord_g(), Delete_sg_CovarianceMatrix_g(), Delete_sg_EnergyLevelMap_g(), Delete_sg_GasAbsLookup_g(), Delete_sg_GriddedField1_g(), Delete_sg_GriddedField2_g(), Delete_sg_GriddedField3_g(), Delete_sg_GriddedField4_g(), Delete_sg_GriddedField5_g(), Delete_sg_GriddedField6_g(), Delete_sg_GridPos_g(), Delete_sg_HitranRelaxationMatrixData_g(), Delete_sg_Index_g(), Delete_sg_JacobianTarget_g(), Delete_sg_MapOfErrorCorrectedSuddenData_g(), Delete_sg_Matrix_g(), Delete_sg_MCAntenna_g(), Delete_sg_Numeric_g(), Delete_sg_Ppath_g(), Delete_sg_PropagationMatrix_g(), Delete_sg_QuantumIdentifier_g(), Delete_sg_RadiationVector_g(), Delete_sg_Rational_g(), Delete_sg_ScatteringMetaData_g(), Delete_sg_SingleScatteringData_g(), Delete_sg_Sparse_g(), Delete_sg_SpeciesIsotopologueRatios_g(), Delete_sg_StokesVector_g(), Delete_sg_String_g(), Delete_sg_TelsemAtlas_g(), Delete_sg_Tensor3_g(), Delete_sg_Tensor4_g(), Delete_sg_Tensor5_g(), Delete_sg_Tensor6_g(), Delete_sg_Tensor7_g(), Delete_sg_TessemNN_g(), Delete_sg_Time_g(), Delete_sg_Timer_g(), Delete_sg_TransmissionMatrix_g(), Delete_sg_Vector_g(), Delete_sg_Verbosity_g(), DiagonalMatrix_sg_Matrix_g(), DiagonalMatrix_sg_Sparse_g(), diameter_maxFromDiameter_volume_equ_g(), diameter_volume_equFromDiameter_max_g(), DiffZaAa_g(), DisortCalc_g(), DisortCalcClearsky_g(), DisortCalcWithARTSSurface_g(), DOAngularGridsSet_g(), DOBatchCalc_g(), doit_conv_flagAbs_g(), doit_conv_flagAbsBT_g(), doit_conv_flagLsq_g(), doit_scat_fieldCalc_g(), doit_scat_fieldCalcLimb_g(), doit_za_grid_optCalc_g(), doit_za_interpSet_g(), DoitCalc_g(), DoitGetIncoming1DAtm_g(), DoitGetIncoming_g(), DoitInit_g(), DoitScatteringDataPrepare_g(), DoitWriteIterationFields_g(), Duration_g(), ecs_dataAddMakarov2020_g(), ecs_dataAddRodrigues1997_g(), ecs_dataAddTran2011_g(), ecs_dataSetMeanAir_g(), ecs_dataSetSpeciesData_g(), EnergyLevelMapSet_g(), Error_g(), Agenda::execute(), ext_matAddGas_g(), Extract_sg_ArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Extract_sg_ArrayOfIndexArrayOfArrayOfIndex_g(), Extract_sg_ArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Extract_sg_GriddedField3ArrayOfGriddedField3_g(), Extract_sg_GriddedField4ArrayOfGriddedField4_g(), Extract_sg_IndexArrayOfIndex_g(), Extract_sg_MatrixArrayOfMatrix_g(), Extract_sg_MatrixTensor3_g(), Extract_sg_NumericVector_g(), Extract_sg_QuantumIdentifierArrayOfQuantumIdentifier_g(), Extract_sg_SingleScatteringDataArrayOfSingleScatteringData_g(), Extract_sg_StringArrayOfString_g(), Extract_sg_TelsemAtlasArrayOfTelsemAtlas_g(), Extract_sg_Tensor3Tensor4_g(), Extract_sg_Tensor4ArrayOfTensor4_g(), Extract_sg_Tensor4Tensor5_g(), Extract_sg_VectorArrayOfVector_g(), ExtractFromMetaSingleScatSpecies_g(), f_gridFromAbsorptionLines_g(), f_gridFromGasAbsLookup_g(), f_gridFromSensorAMSU_g(), f_gridFromSensorAMSUgeneric_g(), f_gridFromSensorHIRS_g(), f_gridMetMM_g(), FastemStandAlone_g(), FieldFromGriddedField_sg_MatrixGriddedField2_g(), FieldFromGriddedField_sg_Tensor3GriddedField3_g(), FieldFromGriddedField_sg_Tensor4ArrayOfGriddedField3_g(), FieldFromGriddedField_sg_Tensor4GriddedField4_g(), Flatten_sg_ArrayOfTimeArrayOfArrayOfTime_g(), Flatten_sg_ArrayOfVectorArrayOfArrayOfVector_g(), Flatten_sg_MatrixArrayOfVector_g(), Flatten_sg_Tensor3ArrayOfMatrix_g(), Flatten_sg_Tensor4ArrayOfTensor3_g(), Flatten_sg_Tensor5ArrayOfTensor4_g(), Flatten_sg_Tensor6ArrayOfTensor5_g(), Flatten_sg_Tensor7ArrayOfTensor6_g(), ForLoop_g(), FrequencyFromCGSAngularWavenumber_sg_NumericNumeric_g(), FrequencyFromCGSAngularWavenumber_sg_VectorVector_g(), FrequencyFromCGSKayserWavenumber_sg_NumericNumeric_g(), FrequencyFromCGSKayserWavenumber_sg_VectorVector_g(), FrequencyFromWavelength_sg_NumericNumeric_g(), FrequencyFromWavelength_sg_VectorVector_g(), g0Earth_g(), geo_posEndOfPpath_g(), geo_posLowestAltitudeOfPpath_g(), geo_posWherePpathPassesZref_g(), GetEnvironmentVariable_sg_Index_g(), GetEnvironmentVariable_sg_String_g(), GriddedFieldGetName_sg_GriddedField1_g(), GriddedFieldGetName_sg_GriddedField2_g(), GriddedFieldGetName_sg_GriddedField3_g(), GriddedFieldGetName_sg_GriddedField4_g(), GriddedFieldGetName_sg_GriddedField5_g(), GriddedFieldGetName_sg_GriddedField6_g(), GriddedFieldLatLonExpand_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldLatLonExpand_sg_GriddedField2GriddedField2_g(), GriddedFieldLatLonExpand_sg_GriddedField3GriddedField3_g(), GriddedFieldLatLonExpand_sg_GriddedField4GriddedField4_g(), GriddedFieldLatLonRegrid_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldLatLonRegrid_sg_GriddedField2GriddedField2_g(), GriddedFieldLatLonRegrid_sg_GriddedField3GriddedField3_g(), GriddedFieldLatLonRegrid_sg_GriddedField4GriddedField4_g(), GriddedFieldPRegrid_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldPRegrid_sg_GriddedField3GriddedField3_g(), GriddedFieldPRegrid_sg_GriddedField4GriddedField4_g(), GriddedFieldZToPRegrid_g(), heating_ratesFromIrradiance_g(), Ignore_sg_AbsorptionLines_g(), Ignore_sg_Agenda_g(), Ignore_sg_ArrayOfAbsorptionLines_g(), Ignore_sg_ArrayOfAgenda_g(), Ignore_sg_ArrayOfArrayOfAbsorptionLines_g(), Ignore_sg_ArrayOfArrayOfGriddedField1_g(), Ignore_sg_ArrayOfArrayOfGriddedField2_g(), Ignore_sg_ArrayOfArrayOfGriddedField3_g(), Ignore_sg_ArrayOfArrayOfIndex_g(), Ignore_sg_ArrayOfArrayOfMatrix_g(), Ignore_sg_ArrayOfArrayOfPropagationMatrix_g(), Ignore_sg_ArrayOfArrayOfRadiationVector_g(), Ignore_sg_ArrayOfArrayOfScatteringMetaData_g(), Ignore_sg_ArrayOfArrayOfSingleScatteringData_g(), Ignore_sg_ArrayOfArrayOfSpeciesTag_g(), Ignore_sg_ArrayOfArrayOfStokesVector_g(), Ignore_sg_ArrayOfArrayOfString_g(), Ignore_sg_ArrayOfArrayOfTensor3_g(), Ignore_sg_ArrayOfArrayOfTensor6_g(), Ignore_sg_ArrayOfArrayOfTime_g(), Ignore_sg_ArrayOfArrayOfTransmissionMatrix_g(), Ignore_sg_ArrayOfArrayOfVector_g(), Ignore_sg_ArrayOfCIARecord_g(), Ignore_sg_ArrayOfGriddedField1_g(), Ignore_sg_ArrayOfGriddedField2_g(), Ignore_sg_ArrayOfGriddedField3_g(), Ignore_sg_ArrayOfGriddedField4_g(), Ignore_sg_ArrayOfIndex_g(), Ignore_sg_ArrayOfJacobianTarget_g(), Ignore_sg_ArrayOfMatrix_g(), Ignore_sg_ArrayOfPpath_g(), Ignore_sg_ArrayOfPropagationMatrix_g(), Ignore_sg_ArrayOfQuantumIdentifier_g(), Ignore_sg_ArrayOfRadiationVector_g(), Ignore_sg_ArrayOfRetrievalQuantity_g(), Ignore_sg_ArrayOfScatteringMetaData_g(), Ignore_sg_ArrayOfSingleScatteringData_g(), Ignore_sg_ArrayOfSparse_g(), Ignore_sg_ArrayOfSpeciesTag_g(), Ignore_sg_ArrayOfStokesVector_g(), Ignore_sg_ArrayOfString_g(), Ignore_sg_ArrayOfTelsemAtlas_g(), Ignore_sg_ArrayOfTensor3_g(), Ignore_sg_ArrayOfTensor4_g(), Ignore_sg_ArrayOfTensor5_g(), Ignore_sg_ArrayOfTensor6_g(), Ignore_sg_ArrayOfTensor7_g(), Ignore_sg_ArrayOfTime_g(), Ignore_sg_ArrayOfTransmissionMatrix_g(), Ignore_sg_ArrayOfVector_g(), Ignore_sg_ArrayOfXsecRecord_g(), Ignore_sg_CIARecord_g(), Ignore_sg_CovarianceMatrix_g(), Ignore_sg_EnergyLevelMap_g(), Ignore_sg_GasAbsLookup_g(), Ignore_sg_GriddedField1_g(), Ignore_sg_GriddedField2_g(), Ignore_sg_GriddedField3_g(), Ignore_sg_GriddedField4_g(), Ignore_sg_GriddedField5_g(), Ignore_sg_GriddedField6_g(), Ignore_sg_GridPos_g(), Ignore_sg_HitranRelaxationMatrixData_g(), Ignore_sg_Index_g(), Ignore_sg_JacobianTarget_g(), Ignore_sg_MapOfErrorCorrectedSuddenData_g(), Ignore_sg_Matrix_g(), Ignore_sg_MCAntenna_g(), Ignore_sg_Numeric_g(), Ignore_sg_Ppath_g(), Ignore_sg_PropagationMatrix_g(), Ignore_sg_QuantumIdentifier_g(), Ignore_sg_RadiationVector_g(), Ignore_sg_Rational_g(), Ignore_sg_ScatteringMetaData_g(), Ignore_sg_SingleScatteringData_g(), Ignore_sg_Sparse_g(), Ignore_sg_SpeciesIsotopologueRatios_g(), Ignore_sg_StokesVector_g(), Ignore_sg_String_g(), Ignore_sg_TelsemAtlas_g(), Ignore_sg_Tensor3_g(), Ignore_sg_Tensor4_g(), Ignore_sg_Tensor5_g(), Ignore_sg_Tensor6_g(), Ignore_sg_Tensor7_g(), Ignore_sg_TessemNN_g(), Ignore_sg_Time_g(), Ignore_sg_Timer_g(), Ignore_sg_TransmissionMatrix_g(), Ignore_sg_Vector_g(), Ignore_sg_Verbosity_g(), IndexAdd_g(), IndexNumberOfAtmosphericPoints_g(), IndexSetToLast_sg_ArrayOfAbsorptionLines_g(), IndexSetToLast_sg_ArrayOfAgenda_g(), IndexSetToLast_sg_ArrayOfArrayOfAbsorptionLines_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField1_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField2_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField3_g(), IndexSetToLast_sg_ArrayOfArrayOfIndex_g(), IndexSetToLast_sg_ArrayOfArrayOfMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfPropagationMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfRadiationVector_g(), IndexSetToLast_sg_ArrayOfArrayOfScatteringMetaData_g(), IndexSetToLast_sg_ArrayOfArrayOfSingleScatteringData_g(), IndexSetToLast_sg_ArrayOfArrayOfSpeciesTag_g(), IndexSetToLast_sg_ArrayOfArrayOfStokesVector_g(), IndexSetToLast_sg_ArrayOfArrayOfString_g(), IndexSetToLast_sg_ArrayOfArrayOfTensor3_g(), IndexSetToLast_sg_ArrayOfArrayOfTensor6_g(), IndexSetToLast_sg_ArrayOfArrayOfTime_g(), IndexSetToLast_sg_ArrayOfArrayOfTransmissionMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfVector_g(), IndexSetToLast_sg_ArrayOfCIARecord_g(), IndexSetToLast_sg_ArrayOfGriddedField1_g(), IndexSetToLast_sg_ArrayOfGriddedField2_g(), IndexSetToLast_sg_ArrayOfGriddedField3_g(), IndexSetToLast_sg_ArrayOfGriddedField4_g(), IndexSetToLast_sg_ArrayOfIndex_g(), IndexSetToLast_sg_ArrayOfJacobianTarget_g(), IndexSetToLast_sg_ArrayOfMatrix_g(), IndexSetToLast_sg_ArrayOfPpath_g(), IndexSetToLast_sg_ArrayOfPropagationMatrix_g(), IndexSetToLast_sg_ArrayOfQuantumIdentifier_g(), IndexSetToLast_sg_ArrayOfRadiationVector_g(), IndexSetToLast_sg_ArrayOfRetrievalQuantity_g(), IndexSetToLast_sg_ArrayOfScatteringMetaData_g(), IndexSetToLast_sg_ArrayOfSingleScatteringData_g(), IndexSetToLast_sg_ArrayOfSparse_g(), IndexSetToLast_sg_ArrayOfSpeciesTag_g(), IndexSetToLast_sg_ArrayOfStokesVector_g(), IndexSetToLast_sg_ArrayOfString_g(), IndexSetToLast_sg_ArrayOfTelsemAtlas_g(), IndexSetToLast_sg_ArrayOfTensor3_g(), IndexSetToLast_sg_ArrayOfTensor4_g(), IndexSetToLast_sg_ArrayOfTensor5_g(), IndexSetToLast_sg_ArrayOfTensor6_g(), IndexSetToLast_sg_ArrayOfTensor7_g(), IndexSetToLast_sg_ArrayOfTime_g(), IndexSetToLast_sg_ArrayOfTransmissionMatrix_g(), IndexSetToLast_sg_ArrayOfVector_g(), IndexSetToLast_sg_ArrayOfXsecRecord_g(), IndexSetToLast_sg_Vector_g(), IndexStepDown_g(), IndexStepUp_g(), InterpAtmFieldToPosition_g(), InterpGriddedField2ToPosition_g(), InterpSurfaceFieldToPosition_g(), irradiance_fieldFromRadiance_g(), Agenda::is_input(), Agenda::is_output(), isotopologue_ratiosInitFromHitran_g(), iy_transmitterMultiplePol_g(), iy_transmitterSinglePol_g(), iyApplyUnit_g(), iyCalc_g(), iyEmissionStandard_g(), iyHybrid_g(), iyIndependentBeamApproximation_g(), iyInterpCloudboxField_g(), iyLoopFrequencies_g(), iyMC_g(), iyRadarSingleScat_g(), iyReplaceFromAux_g(), iySurfaceCallAgendaX_g(), iySurfaceFastem_g(), iySurfaceRtpropAgenda_g(), iySurfaceRtpropCalc_g(), iyTransmissionStandard_g(), jacobianAddAbsSpecies_g(), jacobianAddBasicCatalogParameter_g(), jacobianAddBasicCatalogParameters_g(), jacobianAddFreqShift_g(), jacobianAddFreqStretch_g(), jacobianAddMagField_g(), jacobianAddNLTE_g(), jacobianAddNLTEs_g(), jacobianAddPointingZa_g(), jacobianAddPolyfit_g(), jacobianAddScatSpecies_g(), jacobianAddShapeCatalogParameter_g(), jacobianAddShapeCatalogParameters_g(), jacobianAddSinefit_g(), jacobianAddSpecialSpecies_g(), jacobianAddSurfaceQuantity_g(), jacobianAddTemperature_g(), jacobianAddWind_g(), jacobianAdjustAndTransform_g(), jacobianCalcDoNothing_g(), jacobianCalcFreqShift_g(), jacobianCalcFreqStretch_g(), jacobianCalcPointingZaInterp_g(), jacobianCalcPointingZaRecalc_g(), jacobianCalcPolyfit_g(), jacobianCalcSinefit_g(), jacobianClose_g(), jacobianFromTwoY_g(), jacobianFromYbatch_g(), jacobianSetAffineTransformation_g(), jacobianSetFuncTransformation_g(), lat_gridFromRawField_g(), lat_gridFromZRaw_g(), lbl_checkedCalc_g(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D_g(), lon_gridFromRawField_g(), lon_gridFromZRaw_g(), MagFieldsCalc_g(), MagFieldsCalcExpand1D_g(), MagFieldsCalcIGRF_g(), MagFieldsFromAltitudeRawCalc_g(), MagRawRead_g(), Matrix1ColFromVector_g(), Matrix1RowFromVector_g(), Matrix2ColFromVectors_g(), Matrix2RowFromVectors_g(), Matrix3ColFromVectors_g(), Matrix3RowFromVectors_g(), MatrixAddScalar_g(), MatrixCBR_g(), MatrixCopySparse_g(), MatrixExtractFromTensor3_g(), MatrixFromCovarianceMatrix_g(), MatrixIdentity_g(), MatrixMatrixMultiply_g(), MatrixPlanck_g(), MatrixScale_g(), MatrixSetConstant_g(), MatrixUnitIntensity_g(), MatrixVectorMultiply_g(), mblock_dlos_gridUniformCircular_g(), mblock_dlos_gridUniformRectangular_g(), mc_antennaSetGaussian_g(), mc_antennaSetGaussianByFWHM_g(), MCGeneral_g(), MCRadar_g(), nbooksGet_sg_Tensor4_g(), nbooksGet_sg_Tensor5_g(), nbooksGet_sg_Tensor6_g(), nbooksGet_sg_Tensor7_g(), ncolsGet_sg_Matrix_g(), ncolsGet_sg_Sparse_g(), ncolsGet_sg_Tensor3_g(), ncolsGet_sg_Tensor4_g(), ncolsGet_sg_Tensor5_g(), ncolsGet_sg_Tensor6_g(), ncolsGet_sg_Tensor7_g(), nelemGet_sg_ArrayOfAbsorptionLines_g(), nelemGet_sg_ArrayOfAgenda_g(), nelemGet_sg_ArrayOfArrayOfAbsorptionLines_g(), nelemGet_sg_ArrayOfArrayOfGriddedField1_g(), nelemGet_sg_ArrayOfArrayOfGriddedField2_g(), nelemGet_sg_ArrayOfArrayOfGriddedField3_g(), nelemGet_sg_ArrayOfArrayOfIndex_g(), nelemGet_sg_ArrayOfArrayOfMatrix_g(), nelemGet_sg_ArrayOfArrayOfPropagationMatrix_g(), nelemGet_sg_ArrayOfArrayOfRadiationVector_g(), nelemGet_sg_ArrayOfArrayOfScatteringMetaData_g(), nelemGet_sg_ArrayOfArrayOfSingleScatteringData_g(), nelemGet_sg_ArrayOfArrayOfSpeciesTag_g(), nelemGet_sg_ArrayOfArrayOfStokesVector_g(), nelemGet_sg_ArrayOfArrayOfString_g(), nelemGet_sg_ArrayOfArrayOfTensor3_g(), nelemGet_sg_ArrayOfArrayOfTensor6_g(), nelemGet_sg_ArrayOfArrayOfTime_g(), nelemGet_sg_ArrayOfArrayOfTransmissionMatrix_g(), nelemGet_sg_ArrayOfArrayOfVector_g(), nelemGet_sg_ArrayOfCIARecord_g(), nelemGet_sg_ArrayOfGriddedField1_g(), nelemGet_sg_ArrayOfGriddedField2_g(), nelemGet_sg_ArrayOfGriddedField3_g(), nelemGet_sg_ArrayOfGriddedField4_g(), nelemGet_sg_ArrayOfIndex_g(), nelemGet_sg_ArrayOfJacobianTarget_g(), nelemGet_sg_ArrayOfMatrix_g(), nelemGet_sg_ArrayOfPpath_g(), nelemGet_sg_ArrayOfPropagationMatrix_g(), nelemGet_sg_ArrayOfQuantumIdentifier_g(), nelemGet_sg_ArrayOfRadiationVector_g(), nelemGet_sg_ArrayOfRetrievalQuantity_g(), nelemGet_sg_ArrayOfScatteringMetaData_g(), nelemGet_sg_ArrayOfSingleScatteringData_g(), nelemGet_sg_ArrayOfSparse_g(), nelemGet_sg_ArrayOfSpeciesTag_g(), nelemGet_sg_ArrayOfStokesVector_g(), nelemGet_sg_ArrayOfString_g(), nelemGet_sg_ArrayOfTelsemAtlas_g(), nelemGet_sg_ArrayOfTensor3_g(), nelemGet_sg_ArrayOfTensor4_g(), nelemGet_sg_ArrayOfTensor5_g(), nelemGet_sg_ArrayOfTensor6_g(), nelemGet_sg_ArrayOfTensor7_g(), nelemGet_sg_ArrayOfTime_g(), nelemGet_sg_ArrayOfTransmissionMatrix_g(), nelemGet_sg_ArrayOfVector_g(), nelemGet_sg_ArrayOfXsecRecord_g(), nelemGet_sg_Vector_g(), nlibrariesGet_g(), nlte_fieldForSingleSpeciesNonOverlappingLines_g(), nlte_fieldFromRaw_g(), nlte_fieldRescalePopulationLevels_g(), nlte_fieldSetLteExternalPartitionFunction_g(), nlte_fieldSetLteInternalPartitionFunction_g(), nlteSetByQuantumIdentifiers_g(), npagesGet_sg_Tensor3_g(), npagesGet_sg_Tensor4_g(), npagesGet_sg_Tensor5_g(), npagesGet_sg_Tensor6_g(), npagesGet_sg_Tensor7_g(), nrowsGet_sg_Matrix_g(), nrowsGet_sg_Sparse_g(), nrowsGet_sg_Tensor3_g(), nrowsGet_sg_Tensor4_g(), nrowsGet_sg_Tensor5_g(), nrowsGet_sg_Tensor6_g(), nrowsGet_sg_Tensor7_g(), nshelvesGet_sg_Tensor5_g(), nshelvesGet_sg_Tensor6_g(), nshelvesGet_sg_Tensor7_g(), NumericAdd_g(), NumericClip_g(), NumericFromVector_g(), NumericInvScale_g(), NumericScale_g(), nvitrinesGet_sg_Tensor6_g(), nvitrinesGet_sg_Tensor7_g(), OEM_g(), opt_prop_bulkCalc_g(), opt_prop_sptFromData_g(), opt_prop_sptFromMonoData_g(), opt_prop_sptFromScat_data_g(), OptimizeDoitPressureGrid_g(), p_gridDensify_g(), p_gridFromGasAbsLookup_g(), p_gridFromZRaw_g(), p_gridRefine_g(), particle_bulkprop_fieldClip_g(), particle_bulkprop_fieldPerturb_g(), particle_bulkprop_fieldPerturbAtmGrids_g(), particle_bulkpropRadarOnionPeeling_g(), particle_fieldCleanup_g(), particle_massesFromMetaData_g(), particle_massesFromMetaDataSingleCategory_g(), PFromZSimple_g(), pha_mat_sptFromData_g(), pha_mat_sptFromDataDOITOpt_g(), pha_mat_sptFromMonoData_g(), pha_mat_sptFromScat_data_g(), pha_matCalc_g(), pnd_fieldCalcFromParticleBulkProps_g(), pnd_fieldCalcFrompnd_field_raw_g(), pnd_fieldExpand1D_g(), pnd_fieldZero_g(), pndFromPsd_g(), pndFromPsdBasic_g(), ppath_fieldCalc_g(), ppath_fieldFromDownUpLimbGeoms_g(), ppath_stepGeometric_g(), ppath_stepRefractionBasic_g(), ppathCalc_g(), ppathCalcFromAltitude_g(), ppathFixedLstep_g(), ppathFromRtePos2_g(), ppathPlaneParallel_g(), ppathStepByStep_g(), ppathWriteXMLPartial_g(), ppvar_optical_depthFromPpvar_trans_cumulat_g(), print(), Print_sg_AbsorptionLines_g(), Print_sg_Agenda_g(), Print_sg_ArrayOfAbsorptionLines_g(), Print_sg_ArrayOfAgenda_g(), Print_sg_ArrayOfArrayOfAbsorptionLines_g(), Print_sg_ArrayOfArrayOfGriddedField1_g(), Print_sg_ArrayOfArrayOfGriddedField2_g(), Print_sg_ArrayOfArrayOfGriddedField3_g(), Print_sg_ArrayOfArrayOfIndex_g(), Print_sg_ArrayOfArrayOfMatrix_g(), Print_sg_ArrayOfArrayOfPropagationMatrix_g(), Print_sg_ArrayOfArrayOfRadiationVector_g(), Print_sg_ArrayOfArrayOfScatteringMetaData_g(), Print_sg_ArrayOfArrayOfSingleScatteringData_g(), Print_sg_ArrayOfArrayOfSpeciesTag_g(), Print_sg_ArrayOfArrayOfStokesVector_g(), Print_sg_ArrayOfArrayOfString_g(), Print_sg_ArrayOfArrayOfTensor3_g(), Print_sg_ArrayOfArrayOfTensor6_g(), Print_sg_ArrayOfArrayOfTime_g(), Print_sg_ArrayOfArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfArrayOfVector_g(), Print_sg_ArrayOfCIARecord_g(), Print_sg_ArrayOfGriddedField1_g(), Print_sg_ArrayOfGriddedField2_g(), Print_sg_ArrayOfGriddedField3_g(), Print_sg_ArrayOfGriddedField4_g(), Print_sg_ArrayOfIndex_g(), Print_sg_ArrayOfJacobianTarget_g(), Print_sg_ArrayOfMatrix_g(), Print_sg_ArrayOfPpath_g(), Print_sg_ArrayOfPropagationMatrix_g(), Print_sg_ArrayOfQuantumIdentifier_g(), Print_sg_ArrayOfRadiationVector_g(), Print_sg_ArrayOfRetrievalQuantity_g(), Print_sg_ArrayOfScatteringMetaData_g(), Print_sg_ArrayOfSingleScatteringData_g(), Print_sg_ArrayOfSparse_g(), Print_sg_ArrayOfSpeciesTag_g(), Print_sg_ArrayOfStokesVector_g(), Print_sg_ArrayOfString_g(), Print_sg_ArrayOfTelsemAtlas_g(), Print_sg_ArrayOfTensor3_g(), Print_sg_ArrayOfTensor4_g(), Print_sg_ArrayOfTensor5_g(), Print_sg_ArrayOfTensor6_g(), Print_sg_ArrayOfTensor7_g(), Print_sg_ArrayOfTime_g(), Print_sg_ArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfVector_g(), Print_sg_ArrayOfXsecRecord_g(), Print_sg_CIARecord_g(), Print_sg_CovarianceMatrix_g(), Print_sg_EnergyLevelMap_g(), Print_sg_GasAbsLookup_g(), Print_sg_GriddedField1_g(), Print_sg_GriddedField2_g(), Print_sg_GriddedField3_g(), Print_sg_GriddedField4_g(), Print_sg_GriddedField5_g(), Print_sg_GriddedField6_g(), Print_sg_GridPos_g(), Print_sg_HitranRelaxationMatrixData_g(), Print_sg_Index_g(), Print_sg_JacobianTarget_g(), Print_sg_MapOfErrorCorrectedSuddenData_g(), Print_sg_Matrix_g(), Print_sg_MCAntenna_g(), Print_sg_Numeric_g(), Print_sg_Ppath_g(), Print_sg_PropagationMatrix_g(), Print_sg_QuantumIdentifier_g(), Print_sg_RadiationVector_g(), Print_sg_Rational_g(), Print_sg_ScatteringMetaData_g(), Print_sg_SingleScatteringData_g(), Print_sg_Sparse_g(), Print_sg_SpeciesIsotopologueRatios_g(), Print_sg_StokesVector_g(), Print_sg_String_g(), Print_sg_TelsemAtlas_g(), Print_sg_Tensor3_g(), Print_sg_Tensor4_g(), Print_sg_Tensor5_g(), Print_sg_Tensor6_g(), Print_sg_Tensor7_g(), Print_sg_TessemNN_g(), Print_sg_Time_g(), Print_sg_Timer_g(), Print_sg_TransmissionMatrix_g(), Print_sg_Vector_g(), Print_sg_Verbosity_g(), PrintWorkspace_g(), propmat_clearsky_agenda_checkedCalc_g(), propmat_clearsky_fieldCalc_g(), propmat_clearskyAddFaraday_g(), propmat_clearskyAddFromLookup_g(), propmat_clearskyAddHitranLineMixingLines_g(), propmat_clearskyAddLines_g(), propmat_clearskyAddOnTheFlyLineMixing_g(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman_g(), propmat_clearskyAddParticles_g(), propmat_clearskyAddXsecAgenda_g(), propmat_clearskyAddZeeman_g(), propmat_clearskyInit_g(), propmat_clearskyZero_g(), psdAbelBoutle12_g(), psdDelanoeEtAl14_g(), psdFieldEtAl07_g(), psdFieldEtAl19_g(), psdMcFarquaharHeymsfield97_g(), psdMilbrandtYau05_g(), psdModifiedGamma_g(), psdModifiedGammaMass_g(), psdModifiedGammaMassMeanParticleMass_g(), psdModifiedGammaMassNtot_g(), psdModifiedGammaMassSingleMoment_g(), psdModifiedGammaMassXmean_g(), psdModifiedGammaMassXmedian_g(), psdMonoDispersive_g(), psdMonoMass_g(), psdSeifertBeheng06_g(), psdWangEtAl16_g(), QuantumIdentifierSet_g(), RadarOnionPeelingTableCalc_g(), RadiationFieldSpectralIntegrate_sg_Tensor4Tensor5_g(), RadiationFieldSpectralIntegrate_sg_Tensor5Tensor7_g(), RationalAdd_g(), RationalInvScale_g(), RationalScale_g(), RationalSet_g(), ReadArrayOfARTSCAT_g(), ReadARTSCAT_g(), ReadHITRAN_g(), ReadJPL_g(), ReadLBLRTM_g(), ReadNetCDF_sg_ArrayOfMatrix_g(), ReadNetCDF_sg_ArrayOfVector_g(), ReadNetCDF_sg_GasAbsLookup_g(), ReadNetCDF_sg_Matrix_g(), ReadNetCDF_sg_Tensor3_g(), ReadNetCDF_sg_Tensor4_g(), ReadNetCDF_sg_Tensor5_g(), ReadNetCDF_sg_Vector_g(), ReadSplitARTSCAT_g(), ReadXML_sg_AbsorptionLines_g(), ReadXML_sg_Agenda_g(), ReadXML_sg_ArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfAgenda_g(), ReadXML_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfArrayOfIndex_g(), ReadXML_sg_ArrayOfArrayOfMatrix_g(), ReadXML_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfArrayOfStokesVector_g(), ReadXML_sg_ArrayOfArrayOfString_g(), ReadXML_sg_ArrayOfArrayOfTensor3_g(), ReadXML_sg_ArrayOfArrayOfTensor6_g(), ReadXML_sg_ArrayOfArrayOfTime_g(), ReadXML_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfArrayOfVector_g(), ReadXML_sg_ArrayOfCIARecord_g(), ReadXML_sg_ArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfGriddedField4_g(), ReadXML_sg_ArrayOfIndex_g(), ReadXML_sg_ArrayOfJacobianTarget_g(), ReadXML_sg_ArrayOfMatrix_g(), ReadXML_sg_ArrayOfPpath_g(), ReadXML_sg_ArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfQuantumIdentifier_g(), ReadXML_sg_ArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfRetrievalQuantity_g(), ReadXML_sg_ArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfSparse_g(), ReadXML_sg_ArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfStokesVector_g(), ReadXML_sg_ArrayOfString_g(), ReadXML_sg_ArrayOfTelsemAtlas_g(), ReadXML_sg_ArrayOfTensor3_g(), ReadXML_sg_ArrayOfTensor4_g(), ReadXML_sg_ArrayOfTensor5_g(), ReadXML_sg_ArrayOfTensor6_g(), ReadXML_sg_ArrayOfTensor7_g(), ReadXML_sg_ArrayOfTime_g(), ReadXML_sg_ArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfVector_g(), ReadXML_sg_ArrayOfXsecRecord_g(), ReadXML_sg_CIARecord_g(), ReadXML_sg_CovarianceMatrix_g(), ReadXML_sg_EnergyLevelMap_g(), ReadXML_sg_GasAbsLookup_g(), ReadXML_sg_GriddedField1_g(), ReadXML_sg_GriddedField2_g(), ReadXML_sg_GriddedField3_g(), ReadXML_sg_GriddedField4_g(), ReadXML_sg_GriddedField5_g(), ReadXML_sg_GriddedField6_g(), ReadXML_sg_GridPos_g(), ReadXML_sg_HitranRelaxationMatrixData_g(), ReadXML_sg_Index_g(), ReadXML_sg_JacobianTarget_g(), ReadXML_sg_MapOfErrorCorrectedSuddenData_g(), ReadXML_sg_Matrix_g(), ReadXML_sg_MCAntenna_g(), ReadXML_sg_Numeric_g(), ReadXML_sg_Ppath_g(), ReadXML_sg_PropagationMatrix_g(), ReadXML_sg_QuantumIdentifier_g(), ReadXML_sg_RadiationVector_g(), ReadXML_sg_Rational_g(), ReadXML_sg_ScatteringMetaData_g(), ReadXML_sg_SingleScatteringData_g(), ReadXML_sg_Sparse_g(), ReadXML_sg_SpeciesIsotopologueRatios_g(), ReadXML_sg_StokesVector_g(), ReadXML_sg_String_g(), ReadXML_sg_TelsemAtlas_g(), ReadXML_sg_Tensor3_g(), ReadXML_sg_Tensor4_g(), ReadXML_sg_Tensor5_g(), ReadXML_sg_Tensor6_g(), ReadXML_sg_Tensor7_g(), ReadXML_sg_TessemNN_g(), ReadXML_sg_Time_g(), ReadXML_sg_Timer_g(), ReadXML_sg_TransmissionMatrix_g(), ReadXML_sg_Vector_g(), ReadXML_sg_Verbosity_g(), ReadXMLIndexed_sg_AbsorptionLines_g(), ReadXMLIndexed_sg_Agenda_g(), ReadXMLIndexed_sg_ArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfAgenda_g(), ReadXMLIndexed_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfCIARecord_g(), ReadXMLIndexed_sg_ArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfGriddedField4_g(), ReadXMLIndexed_sg_ArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfJacobianTarget_g(), ReadXMLIndexed_sg_ArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfPpath_g(), ReadXMLIndexed_sg_ArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfQuantumIdentifier_g(), ReadXMLIndexed_sg_ArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfRetrievalQuantity_g(), ReadXMLIndexed_sg_ArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfSparse_g(), ReadXMLIndexed_sg_ArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfTelsemAtlas_g(), ReadXMLIndexed_sg_ArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfTensor4_g(), ReadXMLIndexed_sg_ArrayOfTensor5_g(), ReadXMLIndexed_sg_ArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfTensor7_g(), ReadXMLIndexed_sg_ArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfXsecRecord_g(), ReadXMLIndexed_sg_CIARecord_g(), ReadXMLIndexed_sg_CovarianceMatrix_g(), ReadXMLIndexed_sg_EnergyLevelMap_g(), ReadXMLIndexed_sg_GasAbsLookup_g(), ReadXMLIndexed_sg_GriddedField1_g(), ReadXMLIndexed_sg_GriddedField2_g(), ReadXMLIndexed_sg_GriddedField3_g(), ReadXMLIndexed_sg_GriddedField4_g(), ReadXMLIndexed_sg_GriddedField5_g(), ReadXMLIndexed_sg_GriddedField6_g(), ReadXMLIndexed_sg_GridPos_g(), ReadXMLIndexed_sg_HitranRelaxationMatrixData_g(), ReadXMLIndexed_sg_Index_g(), ReadXMLIndexed_sg_JacobianTarget_g(), ReadXMLIndexed_sg_MapOfErrorCorrectedSuddenData_g(), ReadXMLIndexed_sg_Matrix_g(), ReadXMLIndexed_sg_MCAntenna_g(), ReadXMLIndexed_sg_Numeric_g(), ReadXMLIndexed_sg_Ppath_g(), ReadXMLIndexed_sg_PropagationMatrix_g(), ReadXMLIndexed_sg_QuantumIdentifier_g(), ReadXMLIndexed_sg_RadiationVector_g(), ReadXMLIndexed_sg_Rational_g(), ReadXMLIndexed_sg_ScatteringMetaData_g(), ReadXMLIndexed_sg_SingleScatteringData_g(), ReadXMLIndexed_sg_Sparse_g(), ReadXMLIndexed_sg_SpeciesIsotopologueRatios_g(), ReadXMLIndexed_sg_StokesVector_g(), ReadXMLIndexed_sg_String_g(), ReadXMLIndexed_sg_TelsemAtlas_g(), ReadXMLIndexed_sg_Tensor3_g(), ReadXMLIndexed_sg_Tensor4_g(), ReadXMLIndexed_sg_Tensor5_g(), ReadXMLIndexed_sg_Tensor6_g(), ReadXMLIndexed_sg_Tensor7_g(), ReadXMLIndexed_sg_TessemNN_g(), ReadXMLIndexed_sg_Time_g(), ReadXMLIndexed_sg_Timer_g(), ReadXMLIndexed_sg_TransmissionMatrix_g(), ReadXMLIndexed_sg_Vector_g(), ReadXMLIndexed_sg_Verbosity_g(), Reduce_sg_MatrixTensor3_g(), Reduce_sg_MatrixTensor4_g(), Reduce_sg_MatrixTensor5_g(), Reduce_sg_MatrixTensor6_g(), Reduce_sg_MatrixTensor7_g(), Reduce_sg_NumericMatrix_g(), Reduce_sg_NumericTensor3_g(), Reduce_sg_NumericTensor4_g(), Reduce_sg_NumericTensor5_g(), Reduce_sg_NumericTensor6_g(), Reduce_sg_NumericTensor7_g(), Reduce_sg_NumericVector_g(), Reduce_sg_Tensor3Tensor4_g(), Reduce_sg_Tensor3Tensor5_g(), Reduce_sg_Tensor3Tensor6_g(), Reduce_sg_Tensor3Tensor7_g(), Reduce_sg_Tensor4Tensor5_g(), Reduce_sg_Tensor4Tensor6_g(), Reduce_sg_Tensor4Tensor7_g(), Reduce_sg_Tensor5Tensor6_g(), Reduce_sg_Tensor5Tensor7_g(), Reduce_sg_Tensor6Tensor7_g(), Reduce_sg_VectorMatrix_g(), Reduce_sg_VectorTensor3_g(), Reduce_sg_VectorTensor4_g(), Reduce_sg_VectorTensor5_g(), Reduce_sg_VectorTensor6_g(), Reduce_sg_VectorTensor7_g(), refellipsoidEarth_g(), refellipsoidEuropa_g(), refellipsoidForAzimuth_g(), refellipsoidGanymede_g(), refellipsoidIo_g(), refellipsoidJupiter_g(), refellipsoidMars_g(), refellipsoidMoon_g(), refellipsoidOrbitPlane_g(), refellipsoidSet_g(), refellipsoidVenus_g(), refr_index_airFreeElectrons_g(), refr_index_airInfraredEarth_g(), refr_index_airMicrowavesEarth_g(), refr_index_airMicrowavesGeneral_g(), retrievalAddAbsSpecies_g(), retrievalAddCatalogParameter_g(), retrievalAddCatalogParameters_g(), retrievalAddFreqShift_g(), retrievalAddFreqStretch_g(), retrievalAddMagField_g(), retrievalAddPointingZa_g(), retrievalAddPolyfit_g(), retrievalAddScatSpecies_g(), retrievalAddSinefit_g(), retrievalAddSpecialSpecies_g(), retrievalAddSurfaceQuantity_g(), retrievalAddTemperature_g(), retrievalAddWind_g(), retrievalDefClose_g(), retrievalDefInit_g(), retrievalErrorsExtract_g(), RT4Calc_g(), RT4CalcWithRT4Surface_g(), RT4Test_g(), rte_losGeometricFromRtePosToRtePos2_g(), rte_losSet_g(), rte_pos_losMoveToStartOfPpath_g(), rte_poslosFromECEF_g(), rte_poslosFromGeodetic_g(), rte_posSet_g(), rtp_nlteFromRaw_g(), scat_data_checkedCalc_g(), scat_data_monoCalc_g(), scat_data_monoExtract_g(), scat_data_singleTmatrix_g(), scat_dataCalc_g(), scat_dataCheck_g(), scat_dataReduceT_g(), ScatElementsPndAndScatAdd_g(), ScatElementsSelect_g(), ScatElementsToabs_speciesAdd_g(), ScatSpeciesExtendTemperature_g(), ScatSpeciesMerge_g(), ScatSpeciesPndAndScatAdd_g(), ScatSpeciesScatAndMetaRead_g(), ScatSpeciesSizeMassInfo_g(), Select_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Select_sg_ArrayOfAgendaArrayOfAgenda_g(), Select_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Select_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Select_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Select_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Select_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Select_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Select_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Select_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Select_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Select_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Select_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Select_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Select_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Select_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Select_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Select_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Select_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Select_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Select_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Select_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Select_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Select_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Select_sg_ArrayOfIndexArrayOfIndex_g(), Select_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Select_sg_ArrayOfMatrixArrayOfMatrix_g(), Select_sg_ArrayOfPpathArrayOfPpath_g(), Select_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Select_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Select_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Select_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Select_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Select_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Select_sg_ArrayOfSparseArrayOfSparse_g(), Select_sg_ArrayOfSpeciesTagArrayOfSpeciesTag_g(), Select_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Select_sg_ArrayOfStringArrayOfString_g(), Select_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Select_sg_ArrayOfTensor3ArrayOfTensor3_g(), Select_sg_ArrayOfTensor4ArrayOfTensor4_g(), Select_sg_ArrayOfTensor5ArrayOfTensor5_g(), Select_sg_ArrayOfTensor6ArrayOfTensor6_g(), Select_sg_ArrayOfTensor7ArrayOfTensor7_g(), Select_sg_ArrayOfTimeArrayOfTime_g(), Select_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfVectorArrayOfVector_g(), Select_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Select_sg_MatrixMatrix_g(), Select_sg_SparseSparse_g(), Select_sg_VectorVector_g(), sensor_checkedCalc_g(), sensor_losGeometricFromSensorPosToOtherPositions_g(), sensor_poslosFromECEF_g(), sensor_poslosFromGeodetic_g(), sensor_responseAntenna_g(), sensor_responseBackend_g(), sensor_responseBackendFrequencySwitching_g(), sensor_responseBeamSwitching_g(), sensor_responseFillFgrid_g(), sensor_responseFrequencySwitching_g(), sensor_responseGenericAMSU_g(), sensor_responseIF2RF_g(), sensor_responseInit_g(), sensor_responseMetMM_g(), sensor_responseMixer_g(), sensor_responseMixerBackendPrecalcWeights_g(), sensor_responseMultiMixerBackend_g(), sensor_responsePolarisation_g(), sensor_responseSimpleAMSU_g(), sensor_responseStokesRotation_g(), sensor_responseWMRF_g(), sensorOff_g(), SetNumberOfThreads_g(), Sleep_g(), sparse_f_gridFromFrequencyGrid_g(), SparseMatrixIdentity_g(), SparseSparseMultiply_g(), spectral_irradiance_fieldFromSpectralRadianceField_g(), spectral_radiance_fieldClearskyPlaneParallel_g(), spectral_radiance_fieldCopyCloudboxField_g(), spectral_radiance_fieldExpandCloudboxField_g(), specular_losCalc_g(), specular_losCalcNoTopography_g(), StringJoin_g(), surface_complex_refr_indexFromGriddedField5_g(), surface_reflectivityFromGriddedField6_g(), surface_rtpropCallAgendaX_g(), surface_scalar_reflectivityFromGriddedField4_g(), surface_scalar_reflectivityFromSurface_rmatrix_g(), surface_typeInterpTypeMask_g(), surfaceBlackbody_g(), SurfaceBlackbody_g(), SurfaceDummy_g(), surfaceFastem_g(), SurfaceFastem_g(), surfaceFlatReflectivity_g(), surfaceFlatRefractiveIndex_g(), surfaceFlatRvRh_g(), surfaceFlatScalarReflectivity_g(), SurfaceFlatScalarReflectivity_g(), surfaceLambertianSimple_g(), surfaceSemiSpecularBy3beams_g(), surfaceSplitSpecularTo3beams_g(), surfaceTelsem_g(), surfaceTessem_g(), SurfaceTessem_g(), TangentPointExtract_g(), TangentPointPrint_g(), telsem_atlasesReadAscii_g(), telsem_atlasReadAscii_g(), telsemAtlasLookup_g(), telsemStandalone_g(), telsemSurfaceTypeLandSea_g(), Tensor3AddScalar_g(), Tensor3ExtractFromTensor4_g(), Tensor3FromVector_g(), Tensor3Scale_g(), Tensor3SetConstant_g(), Tensor4AddScalar_g(), Tensor4Scale_g(), Tensor4SetConstant_g(), Tensor5Scale_g(), Tensor5SetConstant_g(), Tensor6Scale_g(), Tensor6SetConstant_g(), Tensor7Scale_g(), Tensor7SetConstant_g(), TessemNNReadAscii_g(), TestArrayOfAgenda_g(), TestTessem_g(), time_gridOffset_g(), time_stampsSort_sg_ArrayOfTimeArrayOfTime_g(), time_stampsSort_sg_ArrayOfVectorArrayOfVector_g(), timeOffset_g(), timeSleep_g(), transmittanceFromIy_aux_g(), Trapz_g(), VectorAddScalar_g(), VectorAddVector_g(), VectorClip_g(), VectorCrop_g(), VectorExtractFromMatrix_g(), VectorFlip_g(), VectorInsertGridPoints_g(), VectorLinSpace_g(), VectorLogSpace_g(), VectorMatrixMultiply_g(), VectorNLinSpace_g(), VectorNLogSpace_g(), VectorPower_g(), VectorReshapeMatrix_g(), VectorScale_g(), VectorSetConstant_g(), VectorSubtractVector_g(), VectorVectorMultiply_g(), VectorZtanToZa1D_g(), VectorZtanToZaRefr1D_g(), verbositySet_g(), verbositySetAgenda_g(), verbositySetFile_g(), verbositySetScreen_g(), vmr_fieldClip_g(), vmr_fieldPerturb_g(), vmr_fieldPerturbAtmGrids_g(), vmr_fieldSetAllConstant_g(), vmr_fieldSetConstant_g(), water_p_eq_fieldMK05_g(), Wigner3Init_g(), Wigner6Init_g(), WignerFastInfoPrint_g(), wind_u_fieldIncludePlanetRotation_g(), WindFieldsCalc_g(), WindFieldsCalcExpand1D_g(), WindRawRead_g(), WMRFSelectChannels_g(), WriteBuiltinPartitionFunctionsXML_g(), WriteMolTau_g(), WriteNetCDF_sg_ArrayOfMatrix_g(), WriteNetCDF_sg_ArrayOfVector_g(), WriteNetCDF_sg_GasAbsLookup_g(), WriteNetCDF_sg_Matrix_g(), WriteNetCDF_sg_Tensor3_g(), WriteNetCDF_sg_Tensor4_g(), WriteNetCDF_sg_Tensor5_g(), WriteNetCDF_sg_Vector_g(), WriteNetCDFIndexed_sg_ArrayOfMatrix_g(), WriteNetCDFIndexed_sg_ArrayOfVector_g(), WriteNetCDFIndexed_sg_GasAbsLookup_g(), WriteNetCDFIndexed_sg_Matrix_g(), WriteNetCDFIndexed_sg_Tensor3_g(), WriteNetCDFIndexed_sg_Tensor4_g(), WriteNetCDFIndexed_sg_Tensor5_g(), WriteNetCDFIndexed_sg_Vector_g(), WriteXML_sg_AbsorptionLines_g(), WriteXML_sg_Agenda_g(), WriteXML_sg_ArrayOfAbsorptionLines_g(), WriteXML_sg_ArrayOfAgenda_g(), WriteXML_sg_ArrayOfArrayOfAbsorptionLines_g(), WriteXML_sg_ArrayOfArrayOfGriddedField1_g(), WriteXML_sg_ArrayOfArrayOfGriddedField2_g(), WriteXML_sg_ArrayOfArrayOfGriddedField3_g(), WriteXML_sg_ArrayOfArrayOfIndex_g(), WriteXML_sg_ArrayOfArrayOfMatrix_g(), WriteXML_sg_ArrayOfArrayOfPropagationMatrix_g(), WriteXML_sg_ArrayOfArrayOfRadiationVector_g(), WriteXML_sg_ArrayOfArrayOfScatteringMetaData_g(), WriteXML_sg_ArrayOfArrayOfSingleScatteringData_g(), WriteXML_sg_ArrayOfArrayOfSpeciesTag_g(), WriteXML_sg_ArrayOfArrayOfStokesVector_g(), WriteXML_sg_ArrayOfArrayOfString_g(), WriteXML_sg_ArrayOfArrayOfTensor3_g(), WriteXML_sg_ArrayOfArrayOfTensor6_g(), WriteXML_sg_ArrayOfArrayOfTime_g(), WriteXML_sg_ArrayOfArrayOfTransmissionMatrix_g(), WriteXML_sg_ArrayOfArrayOfVector_g(), WriteXML_sg_ArrayOfCIARecord_g(), WriteXML_sg_ArrayOfGriddedField1_g(), WriteXML_sg_ArrayOfGriddedField2_g(), WriteXML_sg_ArrayOfGriddedField3_g(), WriteXML_sg_ArrayOfGriddedField4_g(), WriteXML_sg_ArrayOfIndex_g(), WriteXML_sg_ArrayOfJacobianTarget_g(), WriteXML_sg_ArrayOfMatrix_g(), WriteXML_sg_ArrayOfPpath_g(), WriteXML_sg_ArrayOfPropagationMatrix_g(), WriteXML_sg_ArrayOfQuantumIdentifier_g(), WriteXML_sg_ArrayOfRadiationVector_g(), WriteXML_sg_ArrayOfRetrievalQuantity_g(), WriteXML_sg_ArrayOfScatteringMetaData_g(), WriteXML_sg_ArrayOfSingleScatteringData_g(), WriteXML_sg_ArrayOfSparse_g(), WriteXML_sg_ArrayOfSpeciesTag_g(), WriteXML_sg_ArrayOfStokesVector_g(), WriteXML_sg_ArrayOfString_g(), WriteXML_sg_ArrayOfTelsemAtlas_g(), WriteXML_sg_ArrayOfTensor3_g(), WriteXML_sg_ArrayOfTensor4_g(), WriteXML_sg_ArrayOfTensor5_g(), WriteXML_sg_ArrayOfTensor6_g(), WriteXML_sg_ArrayOfTensor7_g(), WriteXML_sg_ArrayOfTime_g(), WriteXML_sg_ArrayOfTransmissionMatrix_g(), WriteXML_sg_ArrayOfVector_g(), WriteXML_sg_ArrayOfXsecRecord_g(), WriteXML_sg_CIARecord_g(), WriteXML_sg_CovarianceMatrix_g(), WriteXML_sg_EnergyLevelMap_g(), WriteXML_sg_GasAbsLookup_g(), WriteXML_sg_GriddedField1_g(), WriteXML_sg_GriddedField2_g(), WriteXML_sg_GriddedField3_g(), WriteXML_sg_GriddedField4_g(), WriteXML_sg_GriddedField5_g(), WriteXML_sg_GriddedField6_g(), WriteXML_sg_GridPos_g(), WriteXML_sg_HitranRelaxationMatrixData_g(), WriteXML_sg_Index_g(), WriteXML_sg_JacobianTarget_g(), WriteXML_sg_MapOfErrorCorrectedSuddenData_g(), WriteXML_sg_Matrix_g(), WriteXML_sg_MCAntenna_g(), WriteXML_sg_Numeric_g(), WriteXML_sg_Ppath_g(), WriteXML_sg_PropagationMatrix_g(), WriteXML_sg_QuantumIdentifier_g(), WriteXML_sg_RadiationVector_g(), WriteXML_sg_Rational_g(), WriteXML_sg_ScatteringMetaData_g(), WriteXML_sg_SingleScatteringData_g(), WriteXML_sg_Sparse_g(), WriteXML_sg_SpeciesIsotopologueRatios_g(), WriteXML_sg_StokesVector_g(), WriteXML_sg_String_g(), WriteXML_sg_TelsemAtlas_g(), WriteXML_sg_Tensor3_g(), WriteXML_sg_Tensor4_g(), WriteXML_sg_Tensor5_g(), WriteXML_sg_Tensor6_g(), WriteXML_sg_Tensor7_g(), WriteXML_sg_TessemNN_g(), WriteXML_sg_Time_g(), WriteXML_sg_Timer_g(), WriteXML_sg_TransmissionMatrix_g(), WriteXML_sg_Vector_g(), WriteXML_sg_Verbosity_g(), WriteXMLIndexed_sg_AbsorptionLines_g(), WriteXMLIndexed_sg_Agenda_g(), WriteXMLIndexed_sg_ArrayOfAbsorptionLines_g(), WriteXMLIndexed_sg_ArrayOfAgenda_g(), WriteXMLIndexed_sg_ArrayOfArrayOfAbsorptionLines_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField1_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField2_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField3_g(), WriteXMLIndexed_sg_ArrayOfArrayOfIndex_g(), WriteXMLIndexed_sg_ArrayOfArrayOfMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfPropagationMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfRadiationVector_g(), WriteXMLIndexed_sg_ArrayOfArrayOfScatteringMetaData_g(), WriteXMLIndexed_sg_ArrayOfArrayOfSingleScatteringData_g(), WriteXMLIndexed_sg_ArrayOfArrayOfSpeciesTag_g(), WriteXMLIndexed_sg_ArrayOfArrayOfStokesVector_g(), WriteXMLIndexed_sg_ArrayOfArrayOfString_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTensor3_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTensor6_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTime_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTransmissionMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfVector_g(), WriteXMLIndexed_sg_ArrayOfCIARecord_g(), WriteXMLIndexed_sg_ArrayOfGriddedField1_g(), WriteXMLIndexed_sg_ArrayOfGriddedField2_g(), WriteXMLIndexed_sg_ArrayOfGriddedField3_g(), WriteXMLIndexed_sg_ArrayOfGriddedField4_g(), WriteXMLIndexed_sg_ArrayOfIndex_g(), WriteXMLIndexed_sg_ArrayOfJacobianTarget_g(), WriteXMLIndexed_sg_ArrayOfMatrix_g(), WriteXMLIndexed_sg_ArrayOfPpath_g(), WriteXMLIndexed_sg_ArrayOfPropagationMatrix_g(), WriteXMLIndexed_sg_ArrayOfQuantumIdentifier_g(), WriteXMLIndexed_sg_ArrayOfRadiationVector_g(), WriteXMLIndexed_sg_ArrayOfRetrievalQuantity_g(), WriteXMLIndexed_sg_ArrayOfScatteringMetaData_g(), WriteXMLIndexed_sg_ArrayOfSingleScatteringData_g(), WriteXMLIndexed_sg_ArrayOfSparse_g(), WriteXMLIndexed_sg_ArrayOfSpeciesTag_g(), WriteXMLIndexed_sg_ArrayOfStokesVector_g(), WriteXMLIndexed_sg_ArrayOfString_g(), WriteXMLIndexed_sg_ArrayOfTelsemAtlas_g(), WriteXMLIndexed_sg_ArrayOfTensor3_g(), WriteXMLIndexed_sg_ArrayOfTensor4_g(), WriteXMLIndexed_sg_ArrayOfTensor5_g(), WriteXMLIndexed_sg_ArrayOfTensor6_g(), WriteXMLIndexed_sg_ArrayOfTensor7_g(), WriteXMLIndexed_sg_ArrayOfTime_g(), WriteXMLIndexed_sg_ArrayOfTransmissionMatrix_g(), WriteXMLIndexed_sg_ArrayOfVector_g(), WriteXMLIndexed_sg_ArrayOfXsecRecord_g(), WriteXMLIndexed_sg_CIARecord_g(), WriteXMLIndexed_sg_CovarianceMatrix_g(), WriteXMLIndexed_sg_EnergyLevelMap_g(), WriteXMLIndexed_sg_GasAbsLookup_g(), WriteXMLIndexed_sg_GriddedField1_g(), WriteXMLIndexed_sg_GriddedField2_g(), WriteXMLIndexed_sg_GriddedField3_g(), WriteXMLIndexed_sg_GriddedField4_g(), WriteXMLIndexed_sg_GriddedField5_g(), WriteXMLIndexed_sg_GriddedField6_g(), WriteXMLIndexed_sg_GridPos_g(), WriteXMLIndexed_sg_HitranRelaxationMatrixData_g(), WriteXMLIndexed_sg_Index_g(), WriteXMLIndexed_sg_JacobianTarget_g(), WriteXMLIndexed_sg_MapOfErrorCorrectedSuddenData_g(), WriteXMLIndexed_sg_Matrix_g(), WriteXMLIndexed_sg_MCAntenna_g(), WriteXMLIndexed_sg_Numeric_g(), WriteXMLIndexed_sg_Ppath_g(), WriteXMLIndexed_sg_PropagationMatrix_g(), WriteXMLIndexed_sg_QuantumIdentifier_g(), WriteXMLIndexed_sg_RadiationVector_g(), WriteXMLIndexed_sg_Rational_g(), WriteXMLIndexed_sg_ScatteringMetaData_g(), WriteXMLIndexed_sg_SingleScatteringData_g(), WriteXMLIndexed_sg_Sparse_g(), WriteXMLIndexed_sg_SpeciesIsotopologueRatios_g(), WriteXMLIndexed_sg_StokesVector_g(), WriteXMLIndexed_sg_String_g(), WriteXMLIndexed_sg_TelsemAtlas_g(), WriteXMLIndexed_sg_Tensor3_g(), WriteXMLIndexed_sg_Tensor4_g(), WriteXMLIndexed_sg_Tensor5_g(), WriteXMLIndexed_sg_Tensor6_g(), WriteXMLIndexed_sg_Tensor7_g(), WriteXMLIndexed_sg_TessemNN_g(), WriteXMLIndexed_sg_Time_g(), WriteXMLIndexed_sg_Timer_g(), WriteXMLIndexed_sg_TransmissionMatrix_g(), WriteXMLIndexed_sg_Vector_g(), WriteXMLIndexed_sg_Verbosity_g(), x2artsAtmAndSurf_g(), x2artsSensor_g(), xaStandard_g(), xClip_g(), y_geoToGeodetic_g(), yApplySensorPol_g(), yApplyUnit_g(), ybatchCalc_g(), ybatchColdAtmHotAtmCycle_g(), ybatchDoublingMeanFocus_g(), ybatchMaskOutsideMedianRange_g(), ybatchMetProfiles_g(), ybatchMetProfilesClear_g(), ybatchTimeAveraging_g(), ybatchTroposphericCorrectionNaiveMedianForward_g(), ybatchTroposphericCorrectionNaiveMedianInverse_g(), yCalc_g(), yCalcAppend_g(), yColdAtmHot_g(), yDoublingMeanFocus_g(), yMaskOutsideMedianRange_g(), yRadar_g(), ySimpleSpectrometer_g(), z_fieldFromHSE_g(), z_surfaceConstantAltitude_g(), z_surfaceFromFileAndGrid_g(), and ZFromPSimple_g().
isInternal()
bool MRecord::isInternal () const inline
Indicates the origin of this method.
Returns true if this method originates from a controlfile and false if it was added by the engine. E.g., for Create and Delete that are added for variables that are added internally to handle literals in the controlfile this flag will be set to true.
Definition at line 169 of file agenda_class.h.
References minternal.
Referenced by Agenda::execute(), and InteractiveWorkspace::execute_workspace_method().
operator=()
MRecord& MRecord::operator= (const MRecord & x) inline
Assignment operator for MRecord.
This is necessary, because it is used implicitly if agendas (which contain an array of MRecord) are copied. The default assignment operator generated by the compiler does not do the right thing!
This became clear due to a bug when agendas were re-defined in the controlfile, which was discoverd by Patrick.
The problem is that MRecord contains some arrays. The copy semantics for Array require the target Array to have the right size. But if we overwrite an old MRecord with a new one, we want all arrays to be overwritten. We don't care about their old size.
Parameters
x The other MRecord to assign.
Returns
The freshly assigned MRecord.
Author
Stefan Buehler
Date
2002-12-02
Definition at line 192 of file agenda_class.h.
References mid, minput, moutput, msetvalue, mtasks, Agenda::resize(), and ARTS::Var::x().
Out()
const ArrayOfIndex& MRecord::Out () const inline
Definition at line 156 of file agenda_class.h.
References moutput.
Referenced by abs_cia_dataAddCIARecord_g(), abs_cia_dataReadFromCIA_g(), abs_cia_dataReadFromXML_g(), abs_cont_descriptionAppend_g(), abs_cont_descriptionInit_g(), abs_hitran_relmat_dataReadHitranRelmatDataAndLines_g(), abs_lines_per_speciesAdaptHitranLineMixing_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLevel_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels_g(), abs_lines_per_speciesChangeBaseParameterForMatchingLines_g(), abs_lines_per_speciesChangeBaseParameterForSpecies_g(), abs_lines_per_speciesCompact_g(), abs_lines_per_speciesCreateFromLines_g(), abs_lines_per_speciesHitranLineMixingAdaptationData_g(), abs_lines_per_speciesMakeManualMirroring_g(), abs_lines_per_speciesMakeManualMirroringSpecies_g(), abs_lines_per_speciesReadSpeciesSplitCatalog_g(), abs_lines_per_speciesReadSplitCatalog_g(), abs_lines_per_speciesSetBaseParameterForMatchingLevel_g(), abs_lines_per_speciesSetBaseParameterForMatchingLevels_g(), abs_lines_per_speciesSetCutoff_g(), abs_lines_per_speciesSetCutoffForMatch_g(), abs_lines_per_speciesSetCutoffForSpecies_g(), abs_lines_per_speciesSetEmpty_g(), abs_lines_per_speciesSetLinemixingLimit_g(), abs_lines_per_speciesSetLinemixingLimitForMatch_g(), abs_lines_per_speciesSetLinemixingLimitForSpecies_g(), abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines_g(), abs_lines_per_speciesSetLineShapeType_g(), abs_lines_per_speciesSetLineShapeTypeForMatch_g(), abs_lines_per_speciesSetLineShapeTypeForSpecies_g(), abs_lines_per_speciesSetMirroring_g(), abs_lines_per_speciesSetMirroringForMatch_g(), abs_lines_per_speciesSetMirroringForSpecies_g(), abs_lines_per_speciesSetNormalization_g(), abs_lines_per_speciesSetNormalizationForMatch_g(), abs_lines_per_speciesSetNormalizationForSpecies_g(), abs_lines_per_speciesSetPopulation_g(), abs_lines_per_speciesSetPopulationForMatch_g(), abs_lines_per_speciesSetPopulationForSpecies_g(), abs_lines_per_speciesSetQuantumNumberForMatch_g(), abs_lines_per_speciesSetT0_g(), abs_lines_per_speciesSetT0ForMatch_g(), abs_lines_per_speciesSetT0ForSpecies_g(), abs_lines_per_speciesSetZeemanCoefficients_g(), abs_lines_per_speciesTruncateQuantumNumbers_g(), abs_linesAppendWithLines_g(), abs_linesChangeBaseParameterForMatchingLevel_g(), abs_linesChangeBaseParameterForMatchingLevels_g(), abs_linesChangeBaseParameterForMatchingLines_g(), abs_linesCleanupEmpty_g(), abs_linesCompact_g(), abs_linesDeleteBadF0_g(), abs_linesDeleteLinesWithBadOrHighChangingJs_g(), abs_linesDeleteLinesWithQuantumNumberAbove_g(), abs_linesDeleteLinesWithUndefinedLocalQuanta_g(), abs_linesDeleteWithLines_g(), abs_linesKeepBand_g(), abs_linesMakeManualMirroring_g(), abs_linesReadSpeciesSplitCatalog_g(), abs_linesRemoveBand_g(), abs_linesRemoveUnusedLocalQuantumNumbers_g(), abs_linesReplaceWithLines_g(), abs_linesSetBaseParameterForMatchingLevel_g(), abs_linesSetBaseParameterForMatchingLevels_g(), abs_linesSetBaseParameterForMatchingLines_g(), abs_linesSetCutoff_g(), abs_linesSetCutoffForMatch_g(), abs_linesSetEmptyBroadeningParametersToEmpty_g(), abs_linesSetLinemixingLimit_g(), abs_linesSetLinemixingLimitForMatch_g(), abs_linesSetLineShapeModelParametersForMatchingLines_g(), abs_linesSetLineShapeType_g(), abs_linesSetLineShapeTypeForMatch_g(), abs_linesSetMirroring_g(), abs_linesSetMirroringForMatch_g(), abs_linesSetNormalization_g(), abs_linesSetNormalizationForMatch_g(), abs_linesSetPopulation_g(), abs_linesSetPopulationForMatch_g(), abs_linesSetQuantumNumberForMatch_g(), abs_linesSetT0_g(), abs_linesSetT0ForMatch_g(), abs_linesSetZeemanCoefficients_g(), abs_linesTruncateGlobalQuantumNumbers_g(), abs_linesTruncateQuantumNumbers_g(), abs_lookupAdapt_g(), abs_lookupCalc_g(), abs_lookupInit_g(), abs_lookupSetup_g(), abs_lookupSetupBatch_g(), abs_lookupSetupWide_g(), abs_nlteFromRaw_g(), abs_speciesAdd2_g(), abs_speciesAdd_g(), abs_speciesDefineAll_g(), abs_speciesDefineAllInScenario_g(), abs_speciesInit_g(), abs_speciesSet_g(), abs_vecAddGas_g(), abs_xsec_agenda_checkedCalc_g(), abs_xsec_per_speciesAddCIA_g(), abs_xsec_per_speciesAddConts_g(), abs_xsec_per_speciesAddHitranXsec_g(), abs_xsec_per_speciesAddLines_g(), abs_xsec_per_speciesAddPredefinedO2MPM2020_g(), abs_xsec_per_speciesInit_g(), AbsInputFromAtmFields_g(), AbsorptionLinesCreate_g(), AddZaAa_g(), AgendaAppend_g(), AgendaCreate_g(), AgendaSet_g(), AngularGridsSetFluxCalc_g(), antenna_responseGaussian_g(), antenna_responseVaryingGaussian_g(), AntennaConstantGaussian1D_g(), AntennaMultiBeamsToPencilBeams_g(), AntennaOff_g(), Append_sg_ArrayOfAbsorptionLinesAbsorptionLines_g(), Append_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfAgendaAgenda_g(), Append_sg_ArrayOfAgendaArrayOfAgenda_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Append_sg_ArrayOfArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Append_sg_ArrayOfArrayOfStringArrayOfString_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Append_sg_ArrayOfArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Append_sg_ArrayOfArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Append_sg_ArrayOfCIARecordCIARecord_g(), Append_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfGriddedField1GriddedField1_g(), Append_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfGriddedField2GriddedField2_g(), Append_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfGriddedField3GriddedField3_g(), Append_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Append_sg_ArrayOfGriddedField4GriddedField4_g(), Append_sg_ArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfIndexIndex_g(), Append_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Append_sg_ArrayOfJacobianTargetJacobianTarget_g(), Append_sg_ArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfMatrixMatrix_g(), Append_sg_ArrayOfPpathArrayOfPpath_g(), Append_sg_ArrayOfPpathPpath_g(), Append_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfPropagationMatrixPropagationMatrix_g(), Append_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Append_sg_ArrayOfQuantumIdentifierQuantumIdentifier_g(), Append_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfRadiationVectorRadiationVector_g(), Append_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Append_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfScatteringMetaDataScatteringMetaData_g(), Append_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfSingleScatteringDataSingleScatteringData_g(), Append_sg_ArrayOfSparseArrayOfSparse_g(), Append_sg_ArrayOfSparseSparse_g(), Append_sg_ArrayOfSpeciesTagArrayOfSpeciesTag_g(), Append_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfStokesVectorStokesVector_g(), Append_sg_ArrayOfStringArrayOfString_g(), Append_sg_ArrayOfStringString_g(), Append_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Append_sg_ArrayOfTelsemAtlasTelsemAtlas_g(), Append_sg_ArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfTensor3Tensor3_g(), Append_sg_ArrayOfTensor4ArrayOfTensor4_g(), Append_sg_ArrayOfTensor4Tensor4_g(), Append_sg_ArrayOfTensor5ArrayOfTensor5_g(), Append_sg_ArrayOfTensor5Tensor5_g(), Append_sg_ArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfTensor6Tensor6_g(), Append_sg_ArrayOfTensor7ArrayOfTensor7_g(), Append_sg_ArrayOfTensor7Tensor7_g(), Append_sg_ArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfTimeTime_g(), Append_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfTransmissionMatrixTransmissionMatrix_g(), Append_sg_ArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfVectorVector_g(), Append_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Append_sg_MatrixMatrix_g(), Append_sg_MatrixVector_g(), Append_sg_StringString_g(), Append_sg_Tensor3Matrix_g(), Append_sg_Tensor3Tensor3_g(), Append_sg_Tensor4Tensor3_g(), Append_sg_Tensor4Tensor4_g(), Append_sg_VectorNumeric_g(), Append_sg_VectorVector_g(), ArrayOfAbsorptionLinesCreate_g(), ArrayOfAgendaAppend_g(), ArrayOfAgendaCreate_g(), ArrayOfArrayOfAbsorptionLinesCreate_g(), ArrayOfArrayOfGriddedField1Create_g(), ArrayOfArrayOfGriddedField2Create_g(), ArrayOfArrayOfGriddedField3Create_g(), ArrayOfArrayOfIndexCreate_g(), ArrayOfArrayOfMatrixCreate_g(), ArrayOfArrayOfPropagationMatrixCreate_g(), ArrayOfArrayOfRadiationVectorCreate_g(), ArrayOfArrayOfScatteringMetaDataCreate_g(), ArrayOfArrayOfSingleScatteringDataCreate_g(), ArrayOfArrayOfSpeciesTagCreate_g(), ArrayOfArrayOfStokesVectorCreate_g(), ArrayOfArrayOfStringCreate_g(), ArrayOfArrayOfTensor3Create_g(), ArrayOfArrayOfTensor6Create_g(), ArrayOfArrayOfTimeCreate_g(), ArrayOfArrayOfTransmissionMatrixCreate_g(), ArrayOfArrayOfVectorCreate_g(), ArrayOfCIARecordCreate_g(), ArrayOfGriddedField1Create_g(), ArrayOfGriddedField2Create_g(), ArrayOfGriddedField3Create_g(), ArrayOfGriddedField4Create_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField1_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField2_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField3_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField4_g(), ArrayOfIndexCreate_g(), ArrayOfIndexLinSpace_g(), ArrayOfIndexSet_g(), ArrayOfIndexSetConstant_g(), ArrayOfJacobianTargetCreate_g(), ArrayOfMatrixCreate_g(), ArrayOfPpathCreate_g(), ArrayOfPropagationMatrixCreate_g(), ArrayOfQuantumIdentifierCreate_g(), ArrayOfQuantumIdentifierFromLines_g(), ArrayOfQuantumIdentifierSet_g(), ArrayOfRadiationVectorCreate_g(), ArrayOfRetrievalQuantityCreate_g(), ArrayOfScatteringMetaDataCreate_g(), ArrayOfSingleScatteringDataCreate_g(), ArrayOfSparseCreate_g(), ArrayOfSpeciesTagCreate_g(), ArrayOfSpeciesTagSet_g(), ArrayOfStokesVectorCreate_g(), ArrayOfStringCreate_g(), ArrayOfStringSet_g(), ArrayOfTelsemAtlasCreate_g(), ArrayOfTensor3Create_g(), ArrayOfTensor4Create_g(), ArrayOfTensor5Create_g(), ArrayOfTensor6Create_g(), ArrayOfTensor7Create_g(), ArrayOfTimeCreate_g(), ArrayOfTimeNLinSpace_g(), ArrayOfTimeSetConstant_g(), ArrayOfTransmissionMatrixCreate_g(), ArrayOfVectorCreate_g(), ArrayOfXsecRecordCreate_g(), atm_fields_compactAddConstant_g(), atm_fields_compactAddSpecies_g(), atm_fields_compactCleanup_g(), atm_fields_compactCreateFromField_g(), atm_fields_compactFromMatrix_g(), atm_gridsFromZRaw_g(), AtmFieldPerturb_g(), AtmFieldPerturbAtmGrids_g(), AtmFieldPRegrid_sg_Tensor3Tensor3_g(), AtmFieldPRegrid_sg_Tensor4Tensor4_g(), atmfields_checkedCalc_g(), AtmFieldsAndParticleBulkPropFieldFromCompact_g(), AtmFieldsCalc_g(), AtmFieldsCalcExpand1D_g(), AtmFieldsExpand1D_g(), AtmFieldsExtract1D_g(), AtmFieldsRefinePgrid_g(), atmgeom_checkedCalc_g(), AtmosphereSet1D_g(), AtmosphereSet2D_g(), AtmosphereSet3D_g(), AtmRawRead_g(), AtmWithNLTERawRead_g(), avkCalc_g(), backend_channel_responseFlat_g(), backend_channel_responseGaussian_g(), batch_atm_fields_compactAddConstant_g(), batch_atm_fields_compactAddSpecies_g(), batch_atm_fields_compactCleanup_g(), batch_atm_fields_compactFromArrayOfMatrix_g(), CIARecordCreate_g(), CIARecordReadFromFile_g(), cloudbox_checkedCalc_g(), cloudbox_field_monoIterate_g(), cloudbox_field_monoOptimizeReverse_g(), cloudbox_field_monoSetConst_g(), cloudbox_fieldCrop_g(), cloudbox_fieldSetClearsky_g(), cloudbox_fieldSetConst_g(), cloudbox_fieldSetConstPerFreq_g(), cloudbox_fieldSetFromPrecalc_g(), cloudbox_fieldUpdate1D_g(), cloudbox_fieldUpdateSeq1D_g(), cloudbox_fieldUpdateSeq1DPP_g(), cloudbox_fieldUpdateSeq3D_g(), cloudboxOff_g(), cloudboxSetAutomatically_g(), cloudboxSetFullAtm_g(), cloudboxSetManually_g(), cloudboxSetManuallyAltitude_g(), collision_coefficientsFromSplitFiles_g(), complex_refr_indexConstant_g(), complex_refr_indexIceMatzler06_g(), complex_refr_indexIceWarren84_g(), complex_refr_indexWaterLiebe93_g(), Copy_sg_AbsorptionLines_g(), Copy_sg_Agenda_g(), Copy_sg_ArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfAgenda_g(), Copy_sg_ArrayOfArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfArrayOfGriddedField1_g(), Copy_sg_ArrayOfArrayOfGriddedField2_g(), Copy_sg_ArrayOfArrayOfGriddedField3_g(), Copy_sg_ArrayOfArrayOfIndex_g(), Copy_sg_ArrayOfArrayOfMatrix_g(), Copy_sg_ArrayOfArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfArrayOfRadiationVector_g(), Copy_sg_ArrayOfArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfArrayOfSpeciesTag_g(), Copy_sg_ArrayOfArrayOfStokesVector_g(), Copy_sg_ArrayOfArrayOfString_g(), Copy_sg_ArrayOfArrayOfTensor3_g(), Copy_sg_ArrayOfArrayOfTensor6_g(), Copy_sg_ArrayOfArrayOfTime_g(), Copy_sg_ArrayOfArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfArrayOfVector_g(), Copy_sg_ArrayOfCIARecord_g(), Copy_sg_ArrayOfGriddedField1_g(), Copy_sg_ArrayOfGriddedField2_g(), Copy_sg_ArrayOfGriddedField3_g(), Copy_sg_ArrayOfGriddedField4_g(), Copy_sg_ArrayOfIndex_g(), Copy_sg_ArrayOfJacobianTarget_g(), Copy_sg_ArrayOfMatrix_g(), Copy_sg_ArrayOfPpath_g(), Copy_sg_ArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfQuantumIdentifier_g(), Copy_sg_ArrayOfRadiationVector_g(), Copy_sg_ArrayOfRetrievalQuantity_g(), Copy_sg_ArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfSparse_g(), Copy_sg_ArrayOfSpeciesTag_g(), Copy_sg_ArrayOfStokesVector_g(), Copy_sg_ArrayOfString_g(), Copy_sg_ArrayOfTelsemAtlas_g(), Copy_sg_ArrayOfTensor3_g(), Copy_sg_ArrayOfTensor4_g(), Copy_sg_ArrayOfTensor5_g(), Copy_sg_ArrayOfTensor6_g(), Copy_sg_ArrayOfTensor7_g(), Copy_sg_ArrayOfTime_g(), Copy_sg_ArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfVector_g(), Copy_sg_ArrayOfXsecRecord_g(), Copy_sg_CIARecord_g(), Copy_sg_CovarianceMatrix_g(), Copy_sg_EnergyLevelMap_g(), Copy_sg_GasAbsLookup_g(), Copy_sg_GriddedField1_g(), Copy_sg_GriddedField2_g(), Copy_sg_GriddedField3_g(), Copy_sg_GriddedField4_g(), Copy_sg_GriddedField5_g(), Copy_sg_GriddedField6_g(), Copy_sg_GridPos_g(), Copy_sg_HitranRelaxationMatrixData_g(), Copy_sg_Index_g(), Copy_sg_JacobianTarget_g(), Copy_sg_MapOfErrorCorrectedSuddenData_g(), Copy_sg_Matrix_g(), Copy_sg_MCAntenna_g(), Copy_sg_Numeric_g(), Copy_sg_Ppath_g(), Copy_sg_PropagationMatrix_g(), Copy_sg_QuantumIdentifier_g(), Copy_sg_RadiationVector_g(), Copy_sg_Rational_g(), Copy_sg_ScatteringMetaData_g(), Copy_sg_SingleScatteringData_g(), Copy_sg_Sparse_g(), Copy_sg_SpeciesIsotopologueRatios_g(), Copy_sg_StokesVector_g(), Copy_sg_String_g(), Copy_sg_TelsemAtlas_g(), Copy_sg_Tensor3_g(), Copy_sg_Tensor4_g(), Copy_sg_Tensor5_g(), Copy_sg_Tensor6_g(), Copy_sg_Tensor7_g(), Copy_sg_TessemNN_g(), Copy_sg_Time_g(), Copy_sg_Timer_g(), Copy_sg_TransmissionMatrix_g(), Copy_sg_Vector_g(), Copy_sg_Verbosity_g(), CovarianceMatrixCreate_g(), covmat1D_sg_Matrix_g(), covmat1D_sg_Sparse_g(), covmat1DMarkov_sg_MatrixMatrix_g(), covmat1DMarkov_sg_SparseSparse_g(), covmat_seAddBlock_sg_Matrix_g(), covmat_seAddBlock_sg_Sparse_g(), covmat_seAddInverseBlock_sg_Matrix_g(), covmat_seAddInverseBlock_sg_Sparse_g(), covmat_seSet_sg_CovarianceMatrix_g(), covmat_seSet_sg_Matrix_g(), covmat_seSet_sg_Sparse_g(), covmat_soCalc_g(), covmat_ssCalc_g(), covmat_sxAddBlock_sg_Matrix_g(), covmat_sxAddBlock_sg_Sparse_g(), covmat_sxAddInverseBlock_sg_Matrix_g(), covmat_sxAddInverseBlock_sg_Sparse_g(), covmat_sxExtractSqrtDiagonal_g(), covmat_sxSet_sg_CovarianceMatrix_g(), covmat_sxSet_sg_Matrix_g(), covmat_sxSet_sg_Sparse_g(), covmatDiagonal_sg_MatrixMatrix_g(), covmatDiagonal_sg_SparseSparse_g(), DiagonalMatrix_sg_Matrix_g(), DiagonalMatrix_sg_Sparse_g(), diameter_maxFromDiameter_volume_equ_g(), diameter_volume_equFromDiameter_max_g(), DiffZaAa_g(), DisortCalc_g(), DisortCalcClearsky_g(), DisortCalcWithARTSSurface_g(), DOAngularGridsSet_g(), DOBatchCalc_g(), doit_conv_flagAbs_g(), doit_conv_flagAbsBT_g(), doit_conv_flagLsq_g(), doit_scat_fieldCalc_g(), doit_scat_fieldCalcLimb_g(), doit_za_grid_optCalc_g(), doit_za_interpSet_g(), DoitCalc_g(), DoitGetIncoming1DAtm_g(), DoitGetIncoming_g(), DoitInit_g(), DoitScatteringDataPrepare_g(), Duration_g(), ecs_dataAddMakarov2020_g(), ecs_dataAddRodrigues1997_g(), ecs_dataAddTran2011_g(), ecs_dataInit_g(), ecs_dataSetMeanAir_g(), ecs_dataSetSpeciesData_g(), EnergyLevelMapCreate_g(), EnergyLevelMapSet_g(), Agenda::execute(), ext_matAddGas_g(), Extract_sg_ArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Extract_sg_ArrayOfIndexArrayOfArrayOfIndex_g(), Extract_sg_ArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Extract_sg_GriddedField3ArrayOfGriddedField3_g(), Extract_sg_GriddedField4ArrayOfGriddedField4_g(), Extract_sg_IndexArrayOfIndex_g(), Extract_sg_MatrixArrayOfMatrix_g(), Extract_sg_MatrixTensor3_g(), Extract_sg_NumericVector_g(), Extract_sg_QuantumIdentifierArrayOfQuantumIdentifier_g(), Extract_sg_SingleScatteringDataArrayOfSingleScatteringData_g(), Extract_sg_StringArrayOfString_g(), Extract_sg_TelsemAtlasArrayOfTelsemAtlas_g(), Extract_sg_Tensor3Tensor4_g(), Extract_sg_Tensor4ArrayOfTensor4_g(), Extract_sg_Tensor4Tensor5_g(), Extract_sg_VectorArrayOfVector_g(), ExtractFromMetaSingleScatSpecies_g(), f_gridFromAbsorptionLines_g(), f_gridFromGasAbsLookup_g(), f_gridFromSensorAMSU_g(), f_gridFromSensorAMSUgeneric_g(), f_gridFromSensorHIRS_g(), f_gridMetMM_g(), FastemStandAlone_g(), FieldFromGriddedField_sg_MatrixGriddedField2_g(), FieldFromGriddedField_sg_Tensor3GriddedField3_g(), FieldFromGriddedField_sg_Tensor4ArrayOfGriddedField3_g(), FieldFromGriddedField_sg_Tensor4GriddedField4_g(), FlagOff_g(), FlagOn_g(), Flatten_sg_ArrayOfTimeArrayOfArrayOfTime_g(), Flatten_sg_ArrayOfVectorArrayOfArrayOfVector_g(), Flatten_sg_MatrixArrayOfVector_g(), Flatten_sg_Tensor3ArrayOfMatrix_g(), Flatten_sg_Tensor4ArrayOfTensor3_g(), Flatten_sg_Tensor5ArrayOfTensor4_g(), Flatten_sg_Tensor6ArrayOfTensor5_g(), Flatten_sg_Tensor7ArrayOfTensor6_g(), FrequencyFromCGSAngularWavenumber_sg_NumericNumeric_g(), FrequencyFromCGSAngularWavenumber_sg_VectorVector_g(), FrequencyFromCGSKayserWavenumber_sg_NumericNumeric_g(), FrequencyFromCGSKayserWavenumber_sg_VectorVector_g(), FrequencyFromWavelength_sg_NumericNumeric_g(), FrequencyFromWavelength_sg_VectorVector_g(), g0Earth_g(), g0Io_g(), g0Jupiter_g(), g0Mars_g(), g0Venus_g(), GasAbsLookupCreate_g(), geo_posEndOfPpath_g(), geo_posLowestAltitudeOfPpath_g(), geo_posWherePpathPassesZref_g(), GetEnvironmentVariable_sg_Index_g(), GetEnvironmentVariable_sg_String_g(), GetNumberOfThreads_g(), GriddedField1Create_g(), GriddedField2Create_g(), GriddedField3Create_g(), GriddedField4Create_g(), GriddedField5Create_g(), GriddedField6Create_g(), GriddedFieldGetName_sg_GriddedField1_g(), GriddedFieldGetName_sg_GriddedField2_g(), GriddedFieldGetName_sg_GriddedField3_g(), GriddedFieldGetName_sg_GriddedField4_g(), GriddedFieldGetName_sg_GriddedField5_g(), GriddedFieldGetName_sg_GriddedField6_g(), GriddedFieldLatLonExpand_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldLatLonExpand_sg_GriddedField2GriddedField2_g(), GriddedFieldLatLonExpand_sg_GriddedField3GriddedField3_g(), GriddedFieldLatLonExpand_sg_GriddedField4GriddedField4_g(), GriddedFieldLatLonRegrid_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldLatLonRegrid_sg_GriddedField2GriddedField2_g(), GriddedFieldLatLonRegrid_sg_GriddedField3GriddedField3_g(), GriddedFieldLatLonRegrid_sg_GriddedField4GriddedField4_g(), GriddedFieldPRegrid_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), GriddedFieldPRegrid_sg_GriddedField3GriddedField3_g(), GriddedFieldPRegrid_sg_GriddedField4GriddedField4_g(), GriddedFieldZToPRegrid_g(), GridPosCreate_g(), heating_ratesFromIrradiance_g(), HitranRelaxationMatrixDataCreate_g(), IndexAdd_g(), IndexCreate_g(), IndexNumberOfAtmosphericPoints_g(), IndexSet_g(), IndexSetToLast_sg_ArrayOfAbsorptionLines_g(), IndexSetToLast_sg_ArrayOfAgenda_g(), IndexSetToLast_sg_ArrayOfArrayOfAbsorptionLines_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField1_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField2_g(), IndexSetToLast_sg_ArrayOfArrayOfGriddedField3_g(), IndexSetToLast_sg_ArrayOfArrayOfIndex_g(), IndexSetToLast_sg_ArrayOfArrayOfMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfPropagationMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfRadiationVector_g(), IndexSetToLast_sg_ArrayOfArrayOfScatteringMetaData_g(), IndexSetToLast_sg_ArrayOfArrayOfSingleScatteringData_g(), IndexSetToLast_sg_ArrayOfArrayOfSpeciesTag_g(), IndexSetToLast_sg_ArrayOfArrayOfStokesVector_g(), IndexSetToLast_sg_ArrayOfArrayOfString_g(), IndexSetToLast_sg_ArrayOfArrayOfTensor3_g(), IndexSetToLast_sg_ArrayOfArrayOfTensor6_g(), IndexSetToLast_sg_ArrayOfArrayOfTime_g(), IndexSetToLast_sg_ArrayOfArrayOfTransmissionMatrix_g(), IndexSetToLast_sg_ArrayOfArrayOfVector_g(), IndexSetToLast_sg_ArrayOfCIARecord_g(), IndexSetToLast_sg_ArrayOfGriddedField1_g(), IndexSetToLast_sg_ArrayOfGriddedField2_g(), IndexSetToLast_sg_ArrayOfGriddedField3_g(), IndexSetToLast_sg_ArrayOfGriddedField4_g(), IndexSetToLast_sg_ArrayOfIndex_g(), IndexSetToLast_sg_ArrayOfJacobianTarget_g(), IndexSetToLast_sg_ArrayOfMatrix_g(), IndexSetToLast_sg_ArrayOfPpath_g(), IndexSetToLast_sg_ArrayOfPropagationMatrix_g(), IndexSetToLast_sg_ArrayOfQuantumIdentifier_g(), IndexSetToLast_sg_ArrayOfRadiationVector_g(), IndexSetToLast_sg_ArrayOfRetrievalQuantity_g(), IndexSetToLast_sg_ArrayOfScatteringMetaData_g(), IndexSetToLast_sg_ArrayOfSingleScatteringData_g(), IndexSetToLast_sg_ArrayOfSparse_g(), IndexSetToLast_sg_ArrayOfSpeciesTag_g(), IndexSetToLast_sg_ArrayOfStokesVector_g(), IndexSetToLast_sg_ArrayOfString_g(), IndexSetToLast_sg_ArrayOfTelsemAtlas_g(), IndexSetToLast_sg_ArrayOfTensor3_g(), IndexSetToLast_sg_ArrayOfTensor4_g(), IndexSetToLast_sg_ArrayOfTensor5_g(), IndexSetToLast_sg_ArrayOfTensor6_g(), IndexSetToLast_sg_ArrayOfTensor7_g(), IndexSetToLast_sg_ArrayOfTime_g(), IndexSetToLast_sg_ArrayOfTransmissionMatrix_g(), IndexSetToLast_sg_ArrayOfVector_g(), IndexSetToLast_sg_ArrayOfXsecRecord_g(), IndexSetToLast_sg_Vector_g(), IndexStepDown_g(), IndexStepUp_g(), InterpAtmFieldToPosition_g(), InterpGriddedField2ToPosition_g(), InterpSurfaceFieldToPosition_g(), irradiance_fieldFromRadiance_g(), Agenda::is_input(), Agenda::is_output(), isotopologue_ratiosInitFromBuiltin_g(), isotopologue_ratiosInitFromHitran_g(), iy_transmitterMultiplePol_g(), iy_transmitterSinglePol_g(), iyApplyUnit_g(), iyCalc_g(), iyEmissionStandard_g(), iyHybrid_g(), iyIndependentBeamApproximation_g(), iyInterpCloudboxField_g(), iyLoopFrequencies_g(), iyMC_g(), iyRadarSingleScat_g(), iyReplaceFromAux_g(), iySurfaceCallAgendaX_g(), iySurfaceFastem_g(), iySurfaceRtpropAgenda_g(), iySurfaceRtpropCalc_g(), iyTransmissionStandard_g(), jacobianAddAbsSpecies_g(), jacobianAddBasicCatalogParameter_g(), jacobianAddBasicCatalogParameters_g(), jacobianAddFreqShift_g(), jacobianAddFreqStretch_g(), jacobianAddMagField_g(), jacobianAddNLTE_g(), jacobianAddNLTEs_g(), jacobianAddPointingZa_g(), jacobianAddPolyfit_g(), jacobianAddScatSpecies_g(), jacobianAddShapeCatalogParameter_g(), jacobianAddShapeCatalogParameters_g(), jacobianAddSinefit_g(), jacobianAddSpecialSpecies_g(), jacobianAddSurfaceQuantity_g(), jacobianAddTemperature_g(), jacobianAddWind_g(), jacobianAdjustAndTransform_g(), jacobianCalcDoNothing_g(), jacobianCalcFreqShift_g(), jacobianCalcFreqStretch_g(), jacobianCalcPointingZaInterp_g(), jacobianCalcPointingZaRecalc_g(), jacobianCalcPolyfit_g(), jacobianCalcSinefit_g(), jacobianClose_g(), jacobianFromTwoY_g(), jacobianFromYbatch_g(), jacobianInit_g(), jacobianOff_g(), jacobianSetAffineTransformation_g(), jacobianSetFuncTransformation_g(), JacobianTargetCreate_g(), lat_gridFromRawField_g(), lat_gridFromZRaw_g(), lbl_checkedCalc_g(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D_g(), LocalTimeOffset_g(), lon_gridFromRawField_g(), lon_gridFromZRaw_g(), MagFieldsCalc_g(), MagFieldsCalcExpand1D_g(), MagFieldsCalcIGRF_g(), MagFieldsFromAltitudeRawCalc_g(), MagRawRead_g(), MapOfErrorCorrectedSuddenDataCreate_g(), Matrix1ColFromVector_g(), Matrix1RowFromVector_g(), Matrix2ColFromVectors_g(), Matrix2RowFromVectors_g(), Matrix3ColFromVectors_g(), Matrix3RowFromVectors_g(), MatrixAddScalar_g(), MatrixCBR_g(), MatrixCopySparse_g(), MatrixCreate_g(), MatrixExtractFromTensor3_g(), MatrixFromCovarianceMatrix_g(), MatrixIdentity_g(), MatrixMatrixMultiply_g(), MatrixPlanck_g(), MatrixScale_g(), MatrixSet_g(), MatrixSetConstant_g(), MatrixUnitIntensity_g(), MatrixVectorMultiply_g(), mblock_dlos_gridUniformCircular_g(), mblock_dlos_gridUniformRectangular_g(), mc_antennaSetGaussian_g(), mc_antennaSetGaussianByFWHM_g(), mc_antennaSetPencilBeam_g(), MCAntennaCreate_g(), MCGeneral_g(), MCRadar_g(), MCSetSeedFromTime_g(), nbooksGet_sg_Tensor4_g(), nbooksGet_sg_Tensor5_g(), nbooksGet_sg_Tensor6_g(), nbooksGet_sg_Tensor7_g(), ncolsGet_sg_Matrix_g(), ncolsGet_sg_Sparse_g(), ncolsGet_sg_Tensor3_g(), ncolsGet_sg_Tensor4_g(), ncolsGet_sg_Tensor5_g(), ncolsGet_sg_Tensor6_g(), ncolsGet_sg_Tensor7_g(), nelemGet_sg_ArrayOfAbsorptionLines_g(), nelemGet_sg_ArrayOfAgenda_g(), nelemGet_sg_ArrayOfArrayOfAbsorptionLines_g(), nelemGet_sg_ArrayOfArrayOfGriddedField1_g(), nelemGet_sg_ArrayOfArrayOfGriddedField2_g(), nelemGet_sg_ArrayOfArrayOfGriddedField3_g(), nelemGet_sg_ArrayOfArrayOfIndex_g(), nelemGet_sg_ArrayOfArrayOfMatrix_g(), nelemGet_sg_ArrayOfArrayOfPropagationMatrix_g(), nelemGet_sg_ArrayOfArrayOfRadiationVector_g(), nelemGet_sg_ArrayOfArrayOfScatteringMetaData_g(), nelemGet_sg_ArrayOfArrayOfSingleScatteringData_g(), nelemGet_sg_ArrayOfArrayOfSpeciesTag_g(), nelemGet_sg_ArrayOfArrayOfStokesVector_g(), nelemGet_sg_ArrayOfArrayOfString_g(), nelemGet_sg_ArrayOfArrayOfTensor3_g(), nelemGet_sg_ArrayOfArrayOfTensor6_g(), nelemGet_sg_ArrayOfArrayOfTime_g(), nelemGet_sg_ArrayOfArrayOfTransmissionMatrix_g(), nelemGet_sg_ArrayOfArrayOfVector_g(), nelemGet_sg_ArrayOfCIARecord_g(), nelemGet_sg_ArrayOfGriddedField1_g(), nelemGet_sg_ArrayOfGriddedField2_g(), nelemGet_sg_ArrayOfGriddedField3_g(), nelemGet_sg_ArrayOfGriddedField4_g(), nelemGet_sg_ArrayOfIndex_g(), nelemGet_sg_ArrayOfJacobianTarget_g(), nelemGet_sg_ArrayOfMatrix_g(), nelemGet_sg_ArrayOfPpath_g(), nelemGet_sg_ArrayOfPropagationMatrix_g(), nelemGet_sg_ArrayOfQuantumIdentifier_g(), nelemGet_sg_ArrayOfRadiationVector_g(), nelemGet_sg_ArrayOfRetrievalQuantity_g(), nelemGet_sg_ArrayOfScatteringMetaData_g(), nelemGet_sg_ArrayOfSingleScatteringData_g(), nelemGet_sg_ArrayOfSparse_g(), nelemGet_sg_ArrayOfSpeciesTag_g(), nelemGet_sg_ArrayOfStokesVector_g(), nelemGet_sg_ArrayOfString_g(), nelemGet_sg_ArrayOfTelsemAtlas_g(), nelemGet_sg_ArrayOfTensor3_g(), nelemGet_sg_ArrayOfTensor4_g(), nelemGet_sg_ArrayOfTensor5_g(), nelemGet_sg_ArrayOfTensor6_g(), nelemGet_sg_ArrayOfTensor7_g(), nelemGet_sg_ArrayOfTime_g(), nelemGet_sg_ArrayOfTransmissionMatrix_g(), nelemGet_sg_ArrayOfVector_g(), nelemGet_sg_ArrayOfXsecRecord_g(), nelemGet_sg_Vector_g(), nlibrariesGet_g(), nlte_fieldForSingleSpeciesNonOverlappingLines_g(), nlte_fieldFromRaw_g(), nlte_fieldRescalePopulationLevels_g(), nlte_fieldSetLteExternalPartitionFunction_g(), nlte_fieldSetLteInternalPartitionFunction_g(), nlteOff_g(), nlteSetByQuantumIdentifiers_g(), npagesGet_sg_Tensor3_g(), npagesGet_sg_Tensor4_g(), npagesGet_sg_Tensor5_g(), npagesGet_sg_Tensor6_g(), npagesGet_sg_Tensor7_g(), nrowsGet_sg_Matrix_g(), nrowsGet_sg_Sparse_g(), nrowsGet_sg_Tensor3_g(), nrowsGet_sg_Tensor4_g(), nrowsGet_sg_Tensor5_g(), nrowsGet_sg_Tensor6_g(), nrowsGet_sg_Tensor7_g(), nshelvesGet_sg_Tensor5_g(), nshelvesGet_sg_Tensor6_g(), nshelvesGet_sg_Tensor7_g(), NumericAdd_g(), NumericClip_g(), NumericCreate_g(), NumericFromVector_g(), NumericInvScale_g(), NumericScale_g(), NumericSet_g(), nvitrinesGet_sg_Tensor6_g(), nvitrinesGet_sg_Tensor7_g(), OEM_g(), opt_prop_bulkCalc_g(), opt_prop_sptFromData_g(), opt_prop_sptFromMonoData_g(), opt_prop_sptFromScat_data_g(), OptimizeDoitPressureGrid_g(), output_file_formatSetAscii_g(), output_file_formatSetBinary_g(), output_file_formatSetZippedAscii_g(), p_gridDensify_g(), p_gridFromGasAbsLookup_g(), p_gridFromZRaw_g(), p_gridRefine_g(), particle_bulkprop_fieldClip_g(), particle_bulkprop_fieldPerturb_g(), particle_bulkprop_fieldPerturbAtmGrids_g(), particle_bulkpropRadarOnionPeeling_g(), particle_fieldCleanup_g(), particle_massesFromMetaData_g(), particle_massesFromMetaDataSingleCategory_g(), PFromZSimple_g(), pha_mat_sptFromData_g(), pha_mat_sptFromDataDOITOpt_g(), pha_mat_sptFromMonoData_g(), pha_mat_sptFromScat_data_g(), pha_matCalc_g(), pnd_fieldCalcFromParticleBulkProps_g(), pnd_fieldCalcFrompnd_field_raw_g(), pnd_fieldExpand1D_g(), pnd_fieldZero_g(), pndFromPsd_g(), pndFromPsdBasic_g(), ppath_fieldCalc_g(), ppath_fieldFromDownUpLimbGeoms_g(), ppath_stepGeometric_g(), ppath_stepRefractionBasic_g(), ppathCalc_g(), ppathCalcFromAltitude_g(), PpathCreate_g(), ppathFixedLstep_g(), ppathFromRtePos2_g(), ppathPlaneParallel_g(), ppathStepByStep_g(), ppvar_optical_depthFromPpvar_trans_cumulat_g(), print(), PropagationMatrixCreate_g(), propmat_clearsky_agenda_checkedCalc_g(), propmat_clearsky_fieldCalc_g(), propmat_clearskyAddFaraday_g(), propmat_clearskyAddFromLookup_g(), propmat_clearskyAddHitranLineMixingLines_g(), propmat_clearskyAddLines_g(), propmat_clearskyAddOnTheFlyLineMixing_g(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman_g(), propmat_clearskyAddParticles_g(), propmat_clearskyAddXsecAgenda_g(), propmat_clearskyAddZeeman_g(), propmat_clearskyForceNegativeToZero_g(), propmat_clearskyInit_g(), propmat_clearskyZero_g(), psdAbelBoutle12_g(), psdDelanoeEtAl14_g(), psdFieldEtAl07_g(), psdFieldEtAl19_g(), psdMcFarquaharHeymsfield97_g(), psdMilbrandtYau05_g(), psdModifiedGamma_g(), psdModifiedGammaMass_g(), psdModifiedGammaMassMeanParticleMass_g(), psdModifiedGammaMassNtot_g(), psdModifiedGammaMassSingleMoment_g(), psdModifiedGammaMassXmean_g(), psdModifiedGammaMassXmedian_g(), psdMonoDispersive_g(), psdMonoMass_g(), psdSeifertBeheng06_g(), psdWangEtAl16_g(), QuantumIdentifierCreate_g(), QuantumIdentifierSet_g(), RadarOnionPeelingTableCalc_g(), RadiationFieldSpectralIntegrate_sg_Tensor4Tensor5_g(), RadiationFieldSpectralIntegrate_sg_Tensor5Tensor7_g(), RadiationVectorCreate_g(), RationalAdd_g(), RationalCreate_g(), RationalInvScale_g(), RationalScale_g(), RationalSet_g(), ReadArrayOfARTSCAT_g(), ReadARTSCAT_g(), ReadHITRAN_g(), ReadJPL_g(), ReadLBLRTM_g(), ReadNetCDF_sg_ArrayOfMatrix_g(), ReadNetCDF_sg_ArrayOfVector_g(), ReadNetCDF_sg_GasAbsLookup_g(), ReadNetCDF_sg_Matrix_g(), ReadNetCDF_sg_Tensor3_g(), ReadNetCDF_sg_Tensor4_g(), ReadNetCDF_sg_Tensor5_g(), ReadNetCDF_sg_Vector_g(), ReadSplitARTSCAT_g(), ReadXML_sg_AbsorptionLines_g(), ReadXML_sg_Agenda_g(), ReadXML_sg_ArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfAgenda_g(), ReadXML_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfArrayOfIndex_g(), ReadXML_sg_ArrayOfArrayOfMatrix_g(), ReadXML_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfArrayOfStokesVector_g(), ReadXML_sg_ArrayOfArrayOfString_g(), ReadXML_sg_ArrayOfArrayOfTensor3_g(), ReadXML_sg_ArrayOfArrayOfTensor6_g(), ReadXML_sg_ArrayOfArrayOfTime_g(), ReadXML_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfArrayOfVector_g(), ReadXML_sg_ArrayOfCIARecord_g(), ReadXML_sg_ArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfGriddedField4_g(), ReadXML_sg_ArrayOfIndex_g(), ReadXML_sg_ArrayOfJacobianTarget_g(), ReadXML_sg_ArrayOfMatrix_g(), ReadXML_sg_ArrayOfPpath_g(), ReadXML_sg_ArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfQuantumIdentifier_g(), ReadXML_sg_ArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfRetrievalQuantity_g(), ReadXML_sg_ArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfSparse_g(), ReadXML_sg_ArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfStokesVector_g(), ReadXML_sg_ArrayOfString_g(), ReadXML_sg_ArrayOfTelsemAtlas_g(), ReadXML_sg_ArrayOfTensor3_g(), ReadXML_sg_ArrayOfTensor4_g(), ReadXML_sg_ArrayOfTensor5_g(), ReadXML_sg_ArrayOfTensor6_g(), ReadXML_sg_ArrayOfTensor7_g(), ReadXML_sg_ArrayOfTime_g(), ReadXML_sg_ArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfVector_g(), ReadXML_sg_ArrayOfXsecRecord_g(), ReadXML_sg_CIARecord_g(), ReadXML_sg_CovarianceMatrix_g(), ReadXML_sg_EnergyLevelMap_g(), ReadXML_sg_GasAbsLookup_g(), ReadXML_sg_GriddedField1_g(), ReadXML_sg_GriddedField2_g(), ReadXML_sg_GriddedField3_g(), ReadXML_sg_GriddedField4_g(), ReadXML_sg_GriddedField5_g(), ReadXML_sg_GriddedField6_g(), ReadXML_sg_GridPos_g(), ReadXML_sg_HitranRelaxationMatrixData_g(), ReadXML_sg_Index_g(), ReadXML_sg_JacobianTarget_g(), ReadXML_sg_MapOfErrorCorrectedSuddenData_g(), ReadXML_sg_Matrix_g(), ReadXML_sg_MCAntenna_g(), ReadXML_sg_Numeric_g(), ReadXML_sg_Ppath_g(), ReadXML_sg_PropagationMatrix_g(), ReadXML_sg_QuantumIdentifier_g(), ReadXML_sg_RadiationVector_g(), ReadXML_sg_Rational_g(), ReadXML_sg_ScatteringMetaData_g(), ReadXML_sg_SingleScatteringData_g(), ReadXML_sg_Sparse_g(), ReadXML_sg_SpeciesIsotopologueRatios_g(), ReadXML_sg_StokesVector_g(), ReadXML_sg_String_g(), ReadXML_sg_TelsemAtlas_g(), ReadXML_sg_Tensor3_g(), ReadXML_sg_Tensor4_g(), ReadXML_sg_Tensor5_g(), ReadXML_sg_Tensor6_g(), ReadXML_sg_Tensor7_g(), ReadXML_sg_TessemNN_g(), ReadXML_sg_Time_g(), ReadXML_sg_Timer_g(), ReadXML_sg_TransmissionMatrix_g(), ReadXML_sg_Vector_g(), ReadXML_sg_Verbosity_g(), ReadXMLIndexed_sg_AbsorptionLines_g(), ReadXMLIndexed_sg_Agenda_g(), ReadXMLIndexed_sg_ArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfAgenda_g(), ReadXMLIndexed_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfCIARecord_g(), ReadXMLIndexed_sg_ArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfGriddedField4_g(), ReadXMLIndexed_sg_ArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfJacobianTarget_g(), ReadXMLIndexed_sg_ArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfPpath_g(), ReadXMLIndexed_sg_ArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfQuantumIdentifier_g(), ReadXMLIndexed_sg_ArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfRetrievalQuantity_g(), ReadXMLIndexed_sg_ArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfSparse_g(), ReadXMLIndexed_sg_ArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfTelsemAtlas_g(), ReadXMLIndexed_sg_ArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfTensor4_g(), ReadXMLIndexed_sg_ArrayOfTensor5_g(), ReadXMLIndexed_sg_ArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfTensor7_g(), ReadXMLIndexed_sg_ArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfXsecRecord_g(), ReadXMLIndexed_sg_CIARecord_g(), ReadXMLIndexed_sg_CovarianceMatrix_g(), ReadXMLIndexed_sg_EnergyLevelMap_g(), ReadXMLIndexed_sg_GasAbsLookup_g(), ReadXMLIndexed_sg_GriddedField1_g(), ReadXMLIndexed_sg_GriddedField2_g(), ReadXMLIndexed_sg_GriddedField3_g(), ReadXMLIndexed_sg_GriddedField4_g(), ReadXMLIndexed_sg_GriddedField5_g(), ReadXMLIndexed_sg_GriddedField6_g(), ReadXMLIndexed_sg_GridPos_g(), ReadXMLIndexed_sg_HitranRelaxationMatrixData_g(), ReadXMLIndexed_sg_Index_g(), ReadXMLIndexed_sg_JacobianTarget_g(), ReadXMLIndexed_sg_MapOfErrorCorrectedSuddenData_g(), ReadXMLIndexed_sg_Matrix_g(), ReadXMLIndexed_sg_MCAntenna_g(), ReadXMLIndexed_sg_Numeric_g(), ReadXMLIndexed_sg_Ppath_g(), ReadXMLIndexed_sg_PropagationMatrix_g(), ReadXMLIndexed_sg_QuantumIdentifier_g(), ReadXMLIndexed_sg_RadiationVector_g(), ReadXMLIndexed_sg_Rational_g(), ReadXMLIndexed_sg_ScatteringMetaData_g(), ReadXMLIndexed_sg_SingleScatteringData_g(), ReadXMLIndexed_sg_Sparse_g(), ReadXMLIndexed_sg_SpeciesIsotopologueRatios_g(), ReadXMLIndexed_sg_StokesVector_g(), ReadXMLIndexed_sg_String_g(), ReadXMLIndexed_sg_TelsemAtlas_g(), ReadXMLIndexed_sg_Tensor3_g(), ReadXMLIndexed_sg_Tensor4_g(), ReadXMLIndexed_sg_Tensor5_g(), ReadXMLIndexed_sg_Tensor6_g(), ReadXMLIndexed_sg_Tensor7_g(), ReadXMLIndexed_sg_TessemNN_g(), ReadXMLIndexed_sg_Time_g(), ReadXMLIndexed_sg_Timer_g(), ReadXMLIndexed_sg_TransmissionMatrix_g(), ReadXMLIndexed_sg_Vector_g(), ReadXMLIndexed_sg_Verbosity_g(), Reduce_sg_MatrixTensor3_g(), Reduce_sg_MatrixTensor4_g(), Reduce_sg_MatrixTensor5_g(), Reduce_sg_MatrixTensor6_g(), Reduce_sg_MatrixTensor7_g(), Reduce_sg_NumericMatrix_g(), Reduce_sg_NumericTensor3_g(), Reduce_sg_NumericTensor4_g(), Reduce_sg_NumericTensor5_g(), Reduce_sg_NumericTensor6_g(), Reduce_sg_NumericTensor7_g(), Reduce_sg_NumericVector_g(), Reduce_sg_Tensor3Tensor4_g(), Reduce_sg_Tensor3Tensor5_g(), Reduce_sg_Tensor3Tensor6_g(), Reduce_sg_Tensor3Tensor7_g(), Reduce_sg_Tensor4Tensor5_g(), Reduce_sg_Tensor4Tensor6_g(), Reduce_sg_Tensor4Tensor7_g(), Reduce_sg_Tensor5Tensor6_g(), Reduce_sg_Tensor5Tensor7_g(), Reduce_sg_Tensor6Tensor7_g(), Reduce_sg_VectorMatrix_g(), Reduce_sg_VectorTensor3_g(), Reduce_sg_VectorTensor4_g(), Reduce_sg_VectorTensor5_g(), Reduce_sg_VectorTensor6_g(), Reduce_sg_VectorTensor7_g(), refellipsoidEarth_g(), refellipsoidEuropa_g(), refellipsoidForAzimuth_g(), refellipsoidGanymede_g(), refellipsoidIo_g(), refellipsoidJupiter_g(), refellipsoidMars_g(), refellipsoidMoon_g(), refellipsoidOrbitPlane_g(), refellipsoidSet_g(), refellipsoidVenus_g(), refr_index_airFreeElectrons_g(), refr_index_airInfraredEarth_g(), refr_index_airMicrowavesEarth_g(), refr_index_airMicrowavesGeneral_g(), retrievalAddAbsSpecies_g(), retrievalAddCatalogParameter_g(), retrievalAddCatalogParameters_g(), retrievalAddFreqShift_g(), retrievalAddFreqStretch_g(), retrievalAddMagField_g(), retrievalAddPointingZa_g(), retrievalAddPolyfit_g(), retrievalAddScatSpecies_g(), retrievalAddSinefit_g(), retrievalAddSpecialSpecies_g(), retrievalAddSurfaceQuantity_g(), retrievalAddTemperature_g(), retrievalAddWind_g(), retrievalDefClose_g(), retrievalDefInit_g(), retrievalErrorsExtract_g(), RT4Calc_g(), RT4CalcWithRT4Surface_g(), RT4Test_g(), rte_losGeometricFromRtePosToRtePos2_g(), rte_losSet_g(), rte_pos_losMoveToStartOfPpath_g(), rte_poslosFromECEF_g(), rte_poslosFromGeodetic_g(), rte_posSet_g(), rtp_nlteFromRaw_g(), scat_data_checkedCalc_g(), scat_data_monoCalc_g(), scat_data_monoExtract_g(), scat_data_singleTmatrix_g(), scat_dataCalc_g(), scat_dataReduceT_g(), ScatElementsPndAndScatAdd_g(), ScatElementsSelect_g(), ScatElementsToabs_speciesAdd_g(), ScatSpeciesExtendTemperature_g(), ScatSpeciesInit_g(), ScatSpeciesMerge_g(), ScatSpeciesPndAndScatAdd_g(), ScatSpeciesScatAndMetaRead_g(), ScatSpeciesSizeMassInfo_g(), ScatteringMetaDataCreate_g(), Select_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Select_sg_ArrayOfAgendaArrayOfAgenda_g(), Select_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Select_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Select_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Select_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Select_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Select_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Select_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Select_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Select_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Select_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Select_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Select_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Select_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Select_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Select_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Select_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Select_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Select_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Select_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Select_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Select_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Select_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Select_sg_ArrayOfIndexArrayOfIndex_g(), Select_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Select_sg_ArrayOfMatrixArrayOfMatrix_g(), Select_sg_ArrayOfPpathArrayOfPpath_g(), Select_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Select_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Select_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Select_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Select_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Select_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Select_sg_ArrayOfSparseArrayOfSparse_g(), Select_sg_ArrayOfSpeciesTagArrayOfSpeciesTag_g(), Select_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Select_sg_ArrayOfStringArrayOfString_g(), Select_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Select_sg_ArrayOfTensor3ArrayOfTensor3_g(), Select_sg_ArrayOfTensor4ArrayOfTensor4_g(), Select_sg_ArrayOfTensor5ArrayOfTensor5_g(), Select_sg_ArrayOfTensor6ArrayOfTensor6_g(), Select_sg_ArrayOfTensor7ArrayOfTensor7_g(), Select_sg_ArrayOfTimeArrayOfTime_g(), Select_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfVectorArrayOfVector_g(), Select_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Select_sg_MatrixMatrix_g(), Select_sg_SparseSparse_g(), Select_sg_VectorVector_g(), sensor_checkedCalc_g(), sensor_losGeometricFromSensorPosToOtherPositions_g(), sensor_poslosFromECEF_g(), sensor_poslosFromGeodetic_g(), sensor_responseAntenna_g(), sensor_responseBackend_g(), sensor_responseBackendFrequencySwitching_g(), sensor_responseBeamSwitching_g(), sensor_responseFillFgrid_g(), sensor_responseFrequencySwitching_g(), sensor_responseGenericAMSU_g(), sensor_responseIF2RF_g(), sensor_responseInit_g(), sensor_responseMetMM_g(), sensor_responseMixer_g(), sensor_responseMixerBackendPrecalcWeights_g(), sensor_responseMultiMixerBackend_g(), sensor_responsePolarisation_g(), sensor_responseSimpleAMSU_g(), sensor_responseStokesRotation_g(), sensor_responseWMRF_g(), sensorOff_g(), SingleScatteringDataCreate_g(), sparse_f_gridFromFrequencyGrid_g(), SparseCreate_g(), SparseMatrixIdentity_g(), SparseSparseMultiply_g(), SpeciesIsotopologueRatiosCreate_g(), spectral_irradiance_fieldFromSpectralRadianceField_g(), spectral_radiance_fieldClearskyPlaneParallel_g(), spectral_radiance_fieldCopyCloudboxField_g(), spectral_radiance_fieldExpandCloudboxField_g(), specular_losCalc_g(), specular_losCalcNoTopography_g(), StokesVectorCreate_g(), StringCreate_g(), StringJoin_g(), StringSet_g(), surface_complex_refr_indexFromGriddedField5_g(), surface_reflectivityFromGriddedField6_g(), surface_rtpropCallAgendaX_g(), surface_scalar_reflectivityFromGriddedField4_g(), surface_scalar_reflectivityFromSurface_rmatrix_g(), surface_typeInterpTypeMask_g(), surfaceBlackbody_g(), SurfaceBlackbody_g(), SurfaceDummy_g(), surfaceFastem_g(), SurfaceFastem_g(), surfaceFlatReflectivity_g(), surfaceFlatRefractiveIndex_g(), surfaceFlatRvRh_g(), surfaceFlatScalarReflectivity_g(), SurfaceFlatScalarReflectivity_g(), surfaceLambertianSimple_g(), surfaceSemiSpecularBy3beams_g(), surfaceSplitSpecularTo3beams_g(), surfaceTelsem_g(), surfaceTessem_g(), SurfaceTessem_g(), TangentPointExtract_g(), telsem_atlasesReadAscii_g(), telsem_atlasReadAscii_g(), TelsemAtlasCreate_g(), telsemAtlasLookup_g(), telsemStandalone_g(), telsemSurfaceTypeLandSea_g(), Tensor3AddScalar_g(), Tensor3Create_g(), Tensor3ExtractFromTensor4_g(), Tensor3FromVector_g(), Tensor3Scale_g(), Tensor3SetConstant_g(), Tensor4AddScalar_g(), Tensor4Create_g(), Tensor4Scale_g(), Tensor4SetConstant_g(), Tensor5Create_g(), Tensor5Scale_g(), Tensor5SetConstant_g(), Tensor6Create_g(), Tensor6Scale_g(), Tensor6SetConstant_g(), Tensor7Create_g(), Tensor7Scale_g(), Tensor7SetConstant_g(), TessemNNCreate_g(), TessemNNReadAscii_g(), TestTessem_g(), time_gridOffset_g(), time_stampsSort_sg_ArrayOfTimeArrayOfTime_g(), time_stampsSort_sg_ArrayOfVectorArrayOfVector_g(), TimeCreate_g(), timeNow_g(), timeOffset_g(), TimerCreate_g(), timerStart_g(), timerStop_g(), Touch_sg_AbsorptionLines_g(), Touch_sg_Agenda_g(), Touch_sg_ArrayOfAbsorptionLines_g(), Touch_sg_ArrayOfAgenda_g(), Touch_sg_ArrayOfArrayOfAbsorptionLines_g(), Touch_sg_ArrayOfArrayOfGriddedField1_g(), Touch_sg_ArrayOfArrayOfGriddedField2_g(), Touch_sg_ArrayOfArrayOfGriddedField3_g(), Touch_sg_ArrayOfArrayOfIndex_g(), Touch_sg_ArrayOfArrayOfMatrix_g(), Touch_sg_ArrayOfArrayOfPropagationMatrix_g(), Touch_sg_ArrayOfArrayOfRadiationVector_g(), Touch_sg_ArrayOfArrayOfScatteringMetaData_g(), Touch_sg_ArrayOfArrayOfSingleScatteringData_g(), Touch_sg_ArrayOfArrayOfSpeciesTag_g(), Touch_sg_ArrayOfArrayOfStokesVector_g(), Touch_sg_ArrayOfArrayOfString_g(), Touch_sg_ArrayOfArrayOfTensor3_g(), Touch_sg_ArrayOfArrayOfTensor6_g(), Touch_sg_ArrayOfArrayOfTime_g(), Touch_sg_ArrayOfArrayOfTransmissionMatrix_g(), Touch_sg_ArrayOfArrayOfVector_g(), Touch_sg_ArrayOfCIARecord_g(), Touch_sg_ArrayOfGriddedField1_g(), Touch_sg_ArrayOfGriddedField2_g(), Touch_sg_ArrayOfGriddedField3_g(), Touch_sg_ArrayOfGriddedField4_g(), Touch_sg_ArrayOfIndex_g(), Touch_sg_ArrayOfJacobianTarget_g(), Touch_sg_ArrayOfMatrix_g(), Touch_sg_ArrayOfPpath_g(), Touch_sg_ArrayOfPropagationMatrix_g(), Touch_sg_ArrayOfQuantumIdentifier_g(), Touch_sg_ArrayOfRadiationVector_g(), Touch_sg_ArrayOfRetrievalQuantity_g(), Touch_sg_ArrayOfScatteringMetaData_g(), Touch_sg_ArrayOfSingleScatteringData_g(), Touch_sg_ArrayOfSparse_g(), Touch_sg_ArrayOfSpeciesTag_g(), Touch_sg_ArrayOfStokesVector_g(), Touch_sg_ArrayOfString_g(), Touch_sg_ArrayOfTelsemAtlas_g(), Touch_sg_ArrayOfTensor3_g(), Touch_sg_ArrayOfTensor4_g(), Touch_sg_ArrayOfTensor5_g(), Touch_sg_ArrayOfTensor6_g(), Touch_sg_ArrayOfTensor7_g(), Touch_sg_ArrayOfTime_g(), Touch_sg_ArrayOfTransmissionMatrix_g(), Touch_sg_ArrayOfVector_g(), Touch_sg_ArrayOfXsecRecord_g(), Touch_sg_CIARecord_g(), Touch_sg_CovarianceMatrix_g(), Touch_sg_EnergyLevelMap_g(), Touch_sg_GasAbsLookup_g(), Touch_sg_GriddedField1_g(), Touch_sg_GriddedField2_g(), Touch_sg_GriddedField3_g(), Touch_sg_GriddedField4_g(), Touch_sg_GriddedField5_g(), Touch_sg_GriddedField6_g(), Touch_sg_GridPos_g(), Touch_sg_HitranRelaxationMatrixData_g(), Touch_sg_Index_g(), Touch_sg_JacobianTarget_g(), Touch_sg_MapOfErrorCorrectedSuddenData_g(), Touch_sg_Matrix_g(), Touch_sg_MCAntenna_g(), Touch_sg_Numeric_g(), Touch_sg_Ppath_g(), Touch_sg_PropagationMatrix_g(), Touch_sg_QuantumIdentifier_g(), Touch_sg_RadiationVector_g(), Touch_sg_Rational_g(), Touch_sg_ScatteringMetaData_g(), Touch_sg_SingleScatteringData_g(), Touch_sg_Sparse_g(), Touch_sg_SpeciesIsotopologueRatios_g(), Touch_sg_StokesVector_g(), Touch_sg_String_g(), Touch_sg_TelsemAtlas_g(), Touch_sg_Tensor3_g(), Touch_sg_Tensor4_g(), Touch_sg_Tensor5_g(), Touch_sg_Tensor6_g(), Touch_sg_Tensor7_g(), Touch_sg_TessemNN_g(), Touch_sg_Time_g(), Touch_sg_Timer_g(), Touch_sg_TransmissionMatrix_g(), Touch_sg_Vector_g(), Touch_sg_Verbosity_g(), TransmissionMatrixCreate_g(), transmittanceFromIy_aux_g(), Trapz_g(), VectorAddScalar_g(), VectorAddVector_g(), VectorClip_g(), VectorCreate_g(), VectorCrop_g(), VectorExtractFromMatrix_g(), VectorFlip_g(), VectorInsertGridPoints_g(), VectorLinSpace_g(), VectorLogSpace_g(), VectorMatrixMultiply_g(), VectorNLinSpace_g(), VectorNLogSpace_g(), VectorPower_g(), VectorReshapeMatrix_g(), VectorScale_g(), VectorSet_g(), VectorSetConstant_g(), VectorSubtractVector_g(), VectorVectorMultiply_g(), VectorZtanToZa1D_g(), VectorZtanToZaRefr1D_g(), VerbosityCreate_g(), verbosityInit_g(), verbositySet_g(), verbositySetAgenda_g(), verbositySetFile_g(), verbositySetScreen_g(), vmr_fieldClip_g(), vmr_fieldPerturb_g(), vmr_fieldPerturbAtmGrids_g(), vmr_fieldSetAllConstant_g(), vmr_fieldSetConstant_g(), water_p_eq_fieldMK05_g(), Wigner3Init_g(), Wigner3Unload_g(), Wigner6Init_g(), Wigner6Unload_g(), wind_u_fieldIncludePlanetRotation_g(), WindFieldsCalc_g(), WindFieldsCalcExpand1D_g(), WindRawRead_g(), WMRFSelectChannels_g(), x2artsAtmAndSurf_g(), x2artsSensor_g(), xaStandard_g(), xClip_g(), y_geoToGeodetic_g(), yApplySensorPol_g(), yApplyUnit_g(), ybatchCalc_g(), ybatchColdAtmHotAtmCycle_g(), ybatchDoublingMeanFocus_g(), ybatchMaskOutsideMedianRange_g(), ybatchMetProfiles_g(), ybatchMetProfilesClear_g(), ybatchTimeAveraging_g(), ybatchTroposphericCorrectionNaiveMedianForward_g(), ybatchTroposphericCorrectionNaiveMedianInverse_g(), yCalc_g(), yCalcAppend_g(), yColdAtmHot_g(), yDoublingMeanFocus_g(), yMaskOutsideMedianRange_g(), yRadar_g(), ySimpleSpectrometer_g(), z_fieldFromHSE_g(), z_surfaceConstantAltitude_g(), z_surfaceFromFileAndGrid_g(), and ZFromPSimple_g().
print()
void MRecord::print (ostream & os, const String & indent) const
Print an MRecord.
Since the MRecord contains all runtime information for one method, the best way to print it is exactly as it would appear in the controlfile.
This has to work in a recursive way, since the method can be an agenda method, which includes other methods, which can be agenda methods, ...
Therefore, the indentation is increased more and more for recursive calls.
At the moment, this is used just for debugging.
Parameters
os Output stream.
indent How many characters of indentation.
Author
Stefan Buehler
Date
2002-12-02
Definition at line 746 of file agenda_class.cc.
References MdRecord::GInType(), MdRecord::GOutType(), Id(), In(), global_data::md_data, MdRecord::Name(), Array< base >::nelem(), Absorption::nelem(), Out(), Agenda::print(), Tasks(), and Workspace::wsv_data.
SetValue()
const TokVal& MRecord::SetValue () const inline
Definition at line 158 of file agenda_class.h.
References msetvalue.
Referenced by ArrayOfIndexSet_g(), ArrayOfIndexSetConstant_g(), ArrayOfSpeciesTagSet_g(), ArrayOfStringSet_g(), callback_getaway(), IndexSet_g(), jacobianCalcPolyfit_g(), jacobianCalcSinefit_g(), MatrixSet_g(), NumericSet_g(), StringSet_g(), and VectorSet_g().
Tasks()
const Agenda& MRecord::Tasks () const inline
Definition at line 159 of file agenda_class.h.
References mtasks.
Referenced by AgendaAppend_g(), AgendaSet_g(), ArrayOfAgendaAppend_g(), Arts2_g(), Arts_g(), and print().
Member Data Documentation
mid
Index MRecord::mid private
Method id.
Definition at line 239 of file agenda_class.h.
Referenced by Id(), and operator=().
minput
ArrayOfIndex MRecord::minput private
Input workspace variables.
Definition at line 243 of file agenda_class.h.
Referenced by ginput_only(), In(), and operator=().
minternal
bool MRecord::minternal private
Flag if this method is called internally by the engine.
Definition at line 250 of file agenda_class.h.
Referenced by isInternal().
moutput
ArrayOfIndex MRecord::moutput private
Output workspace variables.
Definition at line 241 of file agenda_class.h.
Referenced by ginput_only(), operator=(), and Out().
msetvalue
TokVal MRecord::msetvalue private
Keyword value for Set methods.
Definition at line 245 of file agenda_class.h.
Referenced by operator=(), and SetValue().
mtasks
Agenda MRecord::mtasks private
An agenda, which can be given in the controlfile instead of keywords.
Definition at line 248 of file agenda_class.h.
Referenced by operator=(), and Tasks().
The documentation for this class was generated from the following files:
agenda_class.h
agenda_class.cc