ARTS: QuantumParserHITRAN2004 Class Reference
QuantumParserHITRAN2004 Class Reference
Parser for quantum number strings from HITRAN 2004 and later.
#include <quantum_parser_hitran.h>
Classes
class QuantumClassGroup
struct QuantumGroup
Public Member Functions
QuantumParserHITRAN2004 ()
Constructor initializing the parser.
void Parse (QuantumIdentifier &qid, const String &quantum_string) const
Parse quantum numbers from string.
Private Types
enum ClassIds {
CI_CLASS1 = 0, CI_CLASS2, CI_CLASS3, CI_CLASS4,
CI_CLASS5, CI_CLASS6, CI_CLASS7, CI_CLASS8,
CI_CLASS9, CI_CLASS10, CI_FINAL
}
enum GroupIds {
GI_GROUP1 = 0, GI_GROUP2, GI_GROUP3, GI_GROUP4,
GI_GROUP5, GI_GROUP6, GI_GROUP6OH, GI_FINAL,
GI_UNDEFINED
}
typedef Array< QuantumFieldDescription > QuantumClass
Private Member Functions
void SetClassGroup (const String &species_name, const ClassIds iclass, const GroupIds igroup)
Private Attributes
Array< QuantumClass > mclass
Array< QuantumGroup > mgroup
Array< QuantumClassGroup > mspecies
Detailed Description
Parser for quantum number strings from HITRAN 2004 and later.
Definition at line 31 of file quantum_parser_hitran.h.
Member Typedef Documentation
QuantumClass
typedef Array<QuantumFieldDescription> QuantumParserHITRAN2004::QuantumClass private
Definition at line 87 of file quantum_parser_hitran.h.
Member Enumeration Documentation
ClassIds
enum QuantumParserHITRAN2004::ClassIds private
Enumerator
CI_CLASS1
CI_CLASS2
CI_CLASS3
CI_CLASS4
CI_CLASS5
CI_CLASS6
CI_CLASS7
CI_CLASS8
CI_CLASS9
CI_CLASS10
CI_FINAL
Definition at line 56 of file quantum_parser_hitran.h.
GroupIds
enum QuantumParserHITRAN2004::GroupIds private
Enumerator
GI_GROUP1
GI_GROUP2
GI_GROUP3
GI_GROUP4
GI_GROUP5
GI_GROUP6
GI_GROUP6OH
GI_FINAL
GI_UNDEFINED
Definition at line 70 of file quantum_parser_hitran.h.
Constructor & Destructor Documentation
QuantumParserHITRAN2004()
QuantumParserHITRAN2004::QuantumParserHITRAN2004 ()
Constructor initializing the parser.
Definition at line 53 of file quantum_parser_hitran.cc.
References CI_CLASS1, CI_CLASS10, CI_CLASS2, CI_CLASS3, CI_CLASS4, CI_CLASS5, CI_CLASS6, CI_CLASS7, CI_CLASS8, CI_CLASS9, CI_FINAL, F, GI_FINAL, GI_GROUP1, GI_GROUP2, GI_GROUP3, J, mclass, mgroup, parse_a1_br_hitran(), parse_a1_pm_hitran(), parse_a1_s_hitran(), parse_a1_sym_hitran(), parse_a1_x_hitran(), parse_a2_hitran(), parse_a3_hitran(), parse_a5_hitran(), parse_i1_hitran(), parse_i2_hitran(), parse_i3_hitran(), r, SKIP_X_SPACES, global_data::species_data, v1, and v2.
Member Function Documentation
Parse()
void QuantumParserHITRAN2004::Parse (QuantumIdentifier & qid, const String & quantum_string) const
Parse quantum numbers from string.
Parameters
[in,out] qid (out) Quantum numbers extracted from the string (in) must have defined Species()
[in] quantum_string Quantum number string as found in the HITRAN catalog (Length: 15*4 characters).
Definition at line 410 of file quantum_parser_hitran.cc.
References GI_GROUP1, GI_GROUP2, GI_GROUP5, GI_GROUP6, GI_GROUP6OH, GI_UNDEFINED, QuantumParserHITRAN2004::QuantumClassGroup::iclass, QuantumParserHITRAN2004::QuantumClassGroup::igroup, QuantumIdentifier::LowerQuantumNumbers(), mclass, mgroup, mspecies, postprocess_group1_hitran(), postprocess_group2_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), QuantumIdentifier::SetTransition(), QuantumIdentifier::Species(), and QuantumIdentifier::UpperQuantumNumbers().
SetClassGroup()
void QuantumParserHITRAN2004::SetClassGroup (const String & species_name, const ClassIds iclass, const GroupIds igroup) private
Definition at line 469 of file quantum_parser_hitran.cc.
References mspecies, and species_index_from_species_name().
Member Data Documentation
mclass
Array<QuantumClass> QuantumParserHITRAN2004::mclass private
Definition at line 97 of file quantum_parser_hitran.h.
Referenced by Parse(), and QuantumParserHITRAN2004().
mgroup
Array<QuantumGroup> QuantumParserHITRAN2004::mgroup private
Definition at line 98 of file quantum_parser_hitran.h.
Referenced by Parse(), and QuantumParserHITRAN2004().
mspecies
Array<QuantumClassGroup> QuantumParserHITRAN2004::mspecies private
Definition at line 99 of file quantum_parser_hitran.h.
Referenced by Parse(), and SetClassGroup().
The documentation for this class was generated from the following files:
quantum_parser_hitran.h
quantum_parser_hitran.cc