ARTS: ConstTensor6View Class Reference
ConstTensor6View Class Reference
A constant view of a Tensor6.
#include <matpackVI.h>
Public Member Functions
constexpr ConstTensor6View (const ConstTensor6View &)=default
constexpr ConstTensor6View (ConstTensor6View &&)=default
ConstTensor6View & operator= (const ConstTensor6View &)=default
ConstTensor6View & operator= (ConstTensor6View &&)=default
bool empty () const
Check if variable is empty.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator6D begin () const
Return const iterator to first sub-tensor.
ConstIterator6D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor6View ()=default
ConstTensor6View (const ConstTensor5View &a)
Special constructor to make a Tensor6 view of a Tensor5.
Protected Member Functions
ConstTensor6View ()=default
ConstTensor6View (Numeric *data, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor6View (Numeric *data, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes
Range mvr {0, 0, 1}
The vitrine range of mdata that is actually used.
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Friends
class ConstIterator7D
class Tensor6View
class ConstTensor7View
Detailed Description
A constant view of a Tensor6.
This, together with the derived class Tensor6View, contains the main implementation of a Tensor6. It defines the concepts of Tensor6View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor6View from a subrange of a Tensor6View.
Dimensions are called: vitrine, shelf, book, page, row, column. or short: v, s, b, p, r, c
The class Tensor6 is just a special case of a Tensor6View which also allocates storage.
Definition at line 149 of file matpackVI.h.
Constructor & Destructor Documentation
ConstTensor6View() [1/6]
constexpr ConstTensor6View::ConstTensor6View (const ConstTensor6View &) constexpr default
ConstTensor6View() [2/6]
constexpr ConstTensor6View::ConstTensor6View (ConstTensor6View &&) constexpr default
~ConstTensor6View()
virtual ConstTensor6View::~ConstTensor6View () virtual default
ConstTensor6View() [3/6]
ConstTensor6View::ConstTensor6View (const ConstTensor5View & a)
Special constructor to make a Tensor6 view of a Tensor5.
Definition at line 894 of file matpackVI.cc.
ConstTensor6View() [4/6]
ConstTensor6View::ConstTensor6View () protected default
Referenced by operator()().
ConstTensor6View() [5/6]
ConstTensor6View::ConstTensor6View (Numeric * data, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor6 to initialize its own Tensor6View part. The row range rr must have a stride to account for the length of one row. The page range pr must have a stride to account for the length of one page.
Definition at line 912 of file matpackVI.cc.
ConstTensor6View() [6/6]
ConstTensor6View::ConstTensor6View (Numeric * data, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct sub-tensors from sub-tensors. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Definition at line 930 of file matpackVI.cc.
Member Function Documentation
begin()
ConstIterator6D ConstTensor6View::begin () const
Return const iterator to first sub-tensor.
Definition at line 875 of file matpackVI.cc.
References mbr, mcr, mdata, mpr, mrr, msr, Range::mstart, Range::mstride, and mvr.
Referenced by copy(), Tensor6View::operator=(), and Tensor6::Tensor6().
empty()
bool ConstTensor6View::empty () const
Check if variable is empty.
Parameters
[in] x The variable to check.
Returns
True if the size of any dimension of x is 0.
Definition at line 36 of file matpackVI.cc.
References nbooks(), ncols(), npages(), nrows(), nshelves(), and nvitrines().
Referenced by get_variable_value().
end()
ConstIterator6D ConstTensor6View::end () const
Return const iterator behind last sub-tensor.
Definition at line 882 of file matpackVI.cc.
References mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, Range::mstride, and mvr.
Referenced by copy(), Tensor6View::operator=(), and Tensor6::Tensor6().
get()
Numeric ConstTensor6View::get (Index v, Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 550 of file matpackVI.h.
References b, c, mdata, OFFSET, and v().
Referenced by interp(), and operator()().
nbooks()
Index ConstTensor6View::nbooks () const
Returns the number of books.
Definition at line 48 of file matpackVI.cc.
References mbr, and Range::mextent.
Referenced by GriddedField6::checksize(), cloudbox_field_monoIterate(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldNormalize(), empty(), get_variable_value(), Interpolation::interp(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), and xml_write_to_stream().
ncols()
Index ConstTensor6View::ncols () const
Returns the number of columns.
Definition at line 57 of file matpackVI.cc.
References mcr, and Range::mextent.
Referenced by GriddedField6::checksize(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_no_background(), cloudbox_field_monoIterate(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq3D(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldCalc(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), doit_za_grid_optCalc(), empty(), get_variable_value(), Interpolation::interp(), interp_cloud_coeff1D(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), OptimizeDoitPressureGrid(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), and xml_write_to_stream().
npages()
Index ConstTensor6View::npages () const
Returns the number of pages.
Definition at line 51 of file matpackVI.cc.
References Range::mextent, and mpr.
Referenced by GriddedField6::checksize(), cloudbox_field_monoIterate(), cloudbox_field_monoOptimizeReverse(), cloudbox_field_ngAcceleration(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldNormalize(), empty(), get_variable_value(), Interpolation::interp(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), xml_write_to_stream(), and za_gridOpt().
nrows()
Index ConstTensor6View::nrows () const
Returns the number of rows.
Definition at line 54 of file matpackVI.cc.
References Range::mextent, and mrr.
Referenced by GriddedField6::checksize(), cloudbox_field_monoIterate(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldNormalize(), empty(), get_variable_value(), Interpolation::interp(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), and xml_write_to_stream().
nshelves()
Index ConstTensor6View::nshelves () const
Returns the number of shelves.
Definition at line 45 of file matpackVI.cc.
References Range::mextent, and msr.
Referenced by GriddedField6::checksize(), cloudbox_field_monoIterate(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldNormalize(), empty(), get_variable_value(), Interpolation::interp(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), and xml_write_to_stream().
nvitrines()
Index ConstTensor6View::nvitrines () const
Returns the number of vitrines.
Definition at line 42 of file matpackVI.cc.
References Range::mextent, and mvr.
Referenced by GriddedField6::checksize(), cloudbox_field_monoIterate(), cloudbox_field_ngAcceleration(), cloudbox_fieldUpdateSeq1D(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldNormalize(), doit_za_grid_optCalc(), empty(), get_variable_value(), Interpolation::interp(), Tensor6View::operator*=(), Tensor6View::operator+=(), Tensor6View::operator-=(), Tensor6View::operator/=(), Tensor6::operator=(), pha_mat_1ScatElem(), Reduce(), Tensor6::reduce_rank(), select_dims_by_size(), Tensor6::size(), surface_reflectivityFromGriddedField6(), Tensor6::Tensor6(), Tensor6Scale(), transform(), xml_write_to_stream(), and za_gridOpt().
operator()() [1/64]
ConstTensor6View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 63 of file matpackVI.cc.
References b, c, ConstTensor6View(), mbr, mcr, mdata, mpr, mrr, msr, mvr, and v().
operator()() [2/64]
ConstTensor5View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 75 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, mrr, msr, mvr, OFFSET, and v().
operator()() [3/64]
ConstTensor5View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 87 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, msr, mvr, OFFSET, and v().
operator()() [4/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 148 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, msr, mvr, OFFSET, and v().
operator()() [5/64]
ConstTensor5View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 99 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mrr, msr, mvr, OFFSET, and v().
operator()() [6/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 161 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mrr, msr, mvr, OFFSET, and v().
operator()() [7/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 213 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, msr, mvr, OFFSET, and v().
operator()() [8/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 344 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, msr, mvr, OFFSET, and v().
operator()() [9/64]
ConstTensor5View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 111 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, mrr, msr, mvr, OFFSET, and v().
operator()() [10/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 174 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, mrr, msr, mvr, OFFSET, and v().
operator()() [11/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 226 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, msr, mvr, OFFSET, and v().
operator()() [12/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 358 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, msr, mvr, OFFSET, and v().
operator()() [13/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 265 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mrr, msr, mvr, OFFSET, and v().
operator()() [14/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 400 of file matpackVI.cc.
References b, c, CHECK, mdata, mrr, msr, mvr, OFFSET, and v().
operator()() [15/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 484 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, msr, mvr, OFFSET, and v().
operator()() [16/64]
ConstMatrixView ConstTensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 779 of file matpackVI.cc.
References b, c, CHECK, mdata, msr, mvr, OFFSET, and v().
operator()() [17/64]
ConstTensor5View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 123 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, mrr, mvr, OFFSET, and v().
operator()() [18/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 187 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, mrr, mvr, OFFSET, and v().
operator()() [19/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 239 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, mvr, OFFSET, and v().
operator()() [20/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 372 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, mvr, OFFSET, and v().
operator()() [21/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 278 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mrr, mvr, OFFSET, and v().
operator()() [22/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 414 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mrr, mvr, OFFSET, and v().
operator()() [23/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 498 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mvr, OFFSET, and v().
operator()() [24/64]
ConstMatrixView ConstTensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 768 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mvr, OFFSET, and v().
operator()() [25/64]
ConstTensor4View ConstTensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 304 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, mrr, mvr, OFFSET, and v().
operator()() [26/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 442 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, mrr, mvr, OFFSET, and v().
operator()() [27/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 526 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, mvr, OFFSET, and v().
operator()() [28/64]
ConstMatrixView ConstTensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 746 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, mvr, OFFSET, and v().
operator()() [29/64]
ConstTensor3View ConstTensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 568 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mrr, mvr, OFFSET, and v().
operator()() [30/64]
ConstMatrixView ConstTensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 713 of file matpackVI.cc.
References b, c, CHECK, mdata, mrr, mvr, OFFSET, and v().
operator()() [31/64]
ConstMatrixView ConstTensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 669 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mvr, OFFSET, and v().
operator()() [32/64]
ConstVectorView ConstTensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 861 of file matpackVI.cc.
References b, c, CHECK, mdata, mvr, OFFSET, and v().
operator()() [33/64]
ConstTensor5View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 135 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, mrr, msr, OFFSET, and v().
operator()() [34/64]
ConstTensor4View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 200 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, mrr, msr, OFFSET, and v().
operator()() [35/64]
ConstTensor4View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 252 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, msr, OFFSET, and v().
operator()() [36/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 386 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, msr, OFFSET, and v().
operator()() [37/64]
ConstTensor4View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 291 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mrr, msr, OFFSET, and v().
operator()() [38/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 428 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mrr, msr, OFFSET, and v().
operator()() [39/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 512 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, msr, OFFSET, and v().
operator()() [40/64]
ConstMatrixView ConstTensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 757 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, msr, OFFSET, and v().
operator()() [41/64]
ConstTensor4View ConstTensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 317 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, mrr, msr, OFFSET, and v().
operator()() [42/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 456 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, mrr, msr, OFFSET, and v().
operator()() [43/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 540 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, msr, OFFSET, and v().
operator()() [44/64]
ConstMatrixView ConstTensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 735 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, msr, OFFSET, and v().
operator()() [45/64]
ConstTensor3View ConstTensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 582 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mrr, msr, OFFSET, and v().
operator()() [46/64]
ConstMatrixView ConstTensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 702 of file matpackVI.cc.
References b, c, CHECK, mdata, mrr, msr, OFFSET, and v().
operator()() [47/64]
ConstMatrixView ConstTensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 658 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, msr, OFFSET, and v().
operator()() [48/64]
ConstVectorView ConstTensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 847 of file matpackVI.cc.
References b, c, CHECK, mdata, msr, OFFSET, and v().
operator()() [49/64]
ConstTensor4View ConstTensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 330 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mpr, mrr, OFFSET, and v().
operator()() [50/64]
ConstTensor3View ConstTensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 470 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, mrr, OFFSET, and v().
operator()() [51/64]
ConstTensor3View ConstTensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 554 of file matpackVI.cc.
operator()() [52/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 724 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mpr, OFFSET, and v().
operator()() [53/64]
ConstTensor3View ConstTensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 596 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, mrr, OFFSET, and v().
operator()() [54/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 691 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, mrr, OFFSET, and v().
operator()() [55/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 647 of file matpackVI.cc.
References b, c, CHECK, mbr, mcr, mdata, OFFSET, and v().
operator()() [56/64]
ConstVectorView ConstTensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 833 of file matpackVI.cc.
References b, c, CHECK, mbr, mdata, OFFSET, and v().
operator()() [57/64]
ConstTensor3View ConstTensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 610 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, mrr, OFFSET, and v().
operator()() [58/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 680 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, mrr, OFFSET, and v().
operator()() [59/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 636 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mpr, OFFSET, and v().
operator()() [60/64]
ConstVectorView ConstTensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 819 of file matpackVI.cc.
References b, c, CHECK, mdata, mpr, OFFSET, and v().
operator()() [61/64]
ConstMatrixView ConstTensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 625 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, mrr, OFFSET, and v().
operator()() [62/64]
ConstVectorView ConstTensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 805 of file matpackVI.cc.
References b, c, CHECK, mdata, mrr, OFFSET, and v().
operator()() [63/64]
ConstVectorView ConstTensor6View::operator() (Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 791 of file matpackVI.cc.
References b, c, CHECK, mcr, mdata, OFFSET, and v().
operator()() [64/64]
Numeric ConstTensor6View::operator() (Index v, Index s, Index b, Index p, Index r, Index c) const inline
Definition at line 538 of file matpackVI.h.
References b, c, CHECK, get(), and v().
operator=() [1/2]
ConstTensor6View& ConstTensor6View::operator= (const ConstTensor6View &) default
operator=() [2/2]
ConstTensor6View& ConstTensor6View::operator= (ConstTensor6View &&) default
Friends And Related Function Documentation
ConstIterator7D
friend class ConstIterator7D friend
Definition at line 563 of file matpackVI.h.
ConstTensor7View
friend class ConstTensor7View friend
Definition at line 565 of file matpackVI.h.
Tensor6View
friend class Tensor6View friend
Definition at line 564 of file matpackVI.h.
Member Data Documentation
mbr
Range ConstTensor6View::mbr {0, 0, 1} protected
The book range of mdata that is actually used.
Definition at line 601 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), end(), Tensor6View::end(), Tensor6View::get_c_array(), nbooks(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
mcr
Range ConstTensor6View::mcr {0, 0, 1} protected
The column range of mdata that is actually used.
Definition at line 607 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), end(), Tensor6View::end(), Tensor6View::get_c_array(), ncols(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
mdata
Numeric* ConstTensor6View::mdata {nullptr} protected
Pointer to the plain C array that holds the data.
Definition at line 609 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), end(), Tensor6View::end(), Tensor6View::get(), get(), Tensor6View::get_c_array(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Iterator7D::operator++(), ConstIterator7D::operator++(), Tensor6::operator=(), Tensor6::reduce_rank(), Tensor6::resize(), Tensor6::Tensor6(), and Tensor6::~Tensor6().
mpr
Range ConstTensor6View::mpr {0, 0, 1} protected
The page range of mdata that is actually used.
Definition at line 603 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), end(), Tensor6View::end(), Tensor6View::get_c_array(), npages(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
mrr
Range ConstTensor6View::mrr {0, 0, 1} protected
The row range of mdata that is actually used.
Definition at line 605 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), Tensor6View::end(), end(), Tensor6View::get_c_array(), nrows(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
msr
Range ConstTensor6View::msr {0, 0, 1} protected
The shelf range of mdata that is actually used.
Definition at line 599 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), Tensor6View::end(), end(), Tensor6View::get_c_array(), nshelves(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
mvr
Range ConstTensor6View::mvr {0, 0, 1} protected
The vitrine range of mdata that is actually used.
Definition at line 597 of file matpackVI.h.
Referenced by Tensor6View::begin(), begin(), Tensor6View::end(), end(), Tensor6View::get_c_array(), nvitrines(), ConstIterator7D::operator!=(), Iterator7D::operator!=(), Tensor6View::operator()(), operator()(), Tensor6View::operator=(), and Tensor6::resize().
The documentation for this class was generated from the following files:
matpackVI.h
matpackVI.cc