ARTS: ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfScatteringMetaData () noexcept
WorkspaceArrayOfArrayOfScatteringMetaData (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfScatteringMetaData () noexcept
WorkspaceArrayOfArrayOfScatteringMetaData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfScatteringMetaData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfScatteringMetaData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 332 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::type = Group::ArrayOfArrayOfScatteringMetaData private
Definition at line 333 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfScatteringMetaData() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::WorkspaceArrayOfArrayOfScatteringMetaData () inline noexcept
Definition at line 337 of file autoarts.h.
WorkspaceArrayOfArrayOfScatteringMetaData() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::WorkspaceArrayOfArrayOfScatteringMetaData (std::size_t i, void * x) inline noexcept
Definition at line 338 of file autoarts.h.
~WorkspaceArrayOfArrayOfScatteringMetaData()
ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::~WorkspaceArrayOfArrayOfScatteringMetaData () inline noexcept
Definition at line 339 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfScatteringMetaData() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::WorkspaceArrayOfArrayOfScatteringMetaData (const type & val) inline noexcept
Definition at line 340 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::islast () const inline noexcept
Definition at line 346 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfScatteringMetaData().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::isnull () const inline noexcept
Definition at line 345 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfScatteringMetaData().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::name () const inline noexcept
Definition at line 347 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfScatteringMetaData& ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::operator= (const type & t) inline noexcept
Definition at line 343 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::pos () const inline noexcept
Definition at line 344 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::value () const inline noexcept
Definition at line 342 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::value () inline noexcept
Definition at line 341 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::p private
Definition at line 334 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfScatteringMetaData::v private
Definition at line 335 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h