ARTS: ARTS::Var::WorkspaceSingleScatteringData Class Reference
ARTS::Var::WorkspaceSingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceSingleScatteringData () noexcept
WorkspaceSingleScatteringData (std::size_t i, void *x) noexcept
~WorkspaceSingleScatteringData () noexcept
WorkspaceSingleScatteringData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceSingleScatteringData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::SingleScatteringData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1394 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceSingleScatteringData::type = Group::SingleScatteringData private
Definition at line 1395 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceSingleScatteringData() [1/3]
ARTS::Var::WorkspaceSingleScatteringData::WorkspaceSingleScatteringData () inline noexcept
Definition at line 1399 of file autoarts.h.
WorkspaceSingleScatteringData() [2/3]
ARTS::Var::WorkspaceSingleScatteringData::WorkspaceSingleScatteringData (std::size_t i, void * x) inline noexcept
Definition at line 1400 of file autoarts.h.
~WorkspaceSingleScatteringData()
ARTS::Var::WorkspaceSingleScatteringData::~WorkspaceSingleScatteringData () inline noexcept
Definition at line 1401 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceSingleScatteringData() [3/3]
ARTS::Var::WorkspaceSingleScatteringData::WorkspaceSingleScatteringData (const type & val) inline noexcept
Definition at line 1402 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceSingleScatteringData::islast () const inline noexcept
Definition at line 1408 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceSingleScatteringData().
isnull()
bool ARTS::Var::WorkspaceSingleScatteringData::isnull () const inline noexcept
Definition at line 1407 of file autoarts.h.
References v.
Referenced by ~WorkspaceSingleScatteringData().
name()
const Group::String& ARTS::Var::WorkspaceSingleScatteringData::name () const inline noexcept
Definition at line 1409 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceSingleScatteringData& ARTS::Var::WorkspaceSingleScatteringData::operator= (const type & t) inline noexcept
Definition at line 1405 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceSingleScatteringData::pos () const inline noexcept
Definition at line 1406 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceSingleScatteringData::value () const inline noexcept
Definition at line 1404 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceSingleScatteringData::value () inline noexcept
Definition at line 1403 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceSingleScatteringData::p private
Definition at line 1396 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceSingleScatteringData::v private
Definition at line 1397 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceSingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h