ARTS: Verbosity Class Reference
Verbosity Class Reference
#include <messages.h>
Public Member Functions
Verbosity ()
Verbosity (Index vagenda, Index vscreen, Index vfile)
bool valid () const
Check if artsmessages contains valid message levels.
Index get_agenda_verbosity () const
Index get_screen_verbosity () const
Index get_file_verbosity () const
bool is_main_agenda () const
void set_agenda_verbosity (Index v)
void set_screen_verbosity (Index v)
void set_file_verbosity (Index v)
void set_main_agenda (bool main_agenda)
Private Attributes
Index va
Verbosity for agenda output.
Index vs
Verbosity for output to screen.
Index vf
Verbosity for output to file.
bool in_main_agenda
Friends
ostream & operator<< (ostream &os, const Verbosity &v)
Detailed Description
Definition at line 49 of file messages.h.
Constructor & Destructor Documentation
Verbosity() [1/2]
Verbosity::Verbosity () inline
Definition at line 51 of file messages.h.
Verbosity() [2/2]
Verbosity::Verbosity (Index vagenda, Index vscreen, Index vfile) inline
Definition at line 53 of file messages.h.
Member Function Documentation
get_agenda_verbosity()
Index Verbosity::get_agenda_verbosity () const inline
Definition at line 65 of file messages.h.
References va.
Referenced by main(), operator<<(), set_reporting_level(), ArtsOut::sufficient_priority_agenda(), and verbosityInit().
get_file_verbosity()
Index Verbosity::get_file_verbosity () const inline
Definition at line 67 of file messages.h.
References vf.
Referenced by arts_exit_with_error_message(), main(), operator<<(), set_reporting_level(), ArtsOut::sufficient_priority_file(), and verbosityInit().
get_screen_verbosity()
Index Verbosity::get_screen_verbosity () const inline
Definition at line 66 of file messages.h.
References vs.
Referenced by arts_exit_with_error_message(), main(), operator<<(), set_reporting_level(), ArtsOut::sufficient_priority_screen(), and verbosityInit().
is_main_agenda()
bool Verbosity::is_main_agenda () const inline
Definition at line 68 of file messages.h.
References in_main_agenda.
Referenced by ArtsOut::in_main_agenda().
set_agenda_verbosity()
void Verbosity::set_agenda_verbosity (Index v) inline
Definition at line 70 of file messages.h.
References va.
Referenced by InteractiveWorkspace::InteractiveWorkspace(), set_reporting_level(), verbosityInit(), verbositySet(), and verbositySetAgenda().
set_file_verbosity()
void Verbosity::set_file_verbosity (Index v) inline
Definition at line 72 of file messages.h.
References vf.
Referenced by InteractiveWorkspace::InteractiveWorkspace(), set_reporting_level(), verbosityInit(), verbositySet(), and verbositySetFile().
set_main_agenda()
void Verbosity::set_main_agenda (bool main_agenda) inline
Definition at line 73 of file messages.h.
References in_main_agenda.
Referenced by Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), and main().
set_screen_verbosity()
void Verbosity::set_screen_verbosity (Index v) inline
Definition at line 71 of file messages.h.
References vs.
Referenced by InteractiveWorkspace::InteractiveWorkspace(), set_reporting_level(), verbosityInit(), verbositySet(), and verbositySetScreen().
valid()
bool Verbosity::valid () const inline
Check if artsmessages contains valid message levels.
Returns
True if ok.
Definition at line 61 of file messages.h.
References va, vf, and vs.
Referenced by set_reporting_level().
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & os, const Verbosity & v) friend
Definition at line 47 of file messages.cc.
Member Data Documentation
in_main_agenda
bool Verbosity::in_main_agenda private
Definition at line 84 of file messages.h.
Referenced by is_main_agenda(), and set_main_agenda().
va
Index Verbosity::va private
Verbosity for agenda output.
Can be 0-3.
Definition at line 79 of file messages.h.
Referenced by get_agenda_verbosity(), set_agenda_verbosity(), and valid().
vf
Index Verbosity::vf private
Verbosity for output to file.
Can be 0-3.
Definition at line 83 of file messages.h.
Referenced by get_file_verbosity(), set_file_verbosity(), and valid().
vs
Index Verbosity::vs private
Verbosity for output to screen.
Can be 0-3.
Definition at line 81 of file messages.h.
Referenced by get_screen_verbosity(), set_screen_verbosity(), and valid().
The documentation for this class was generated from the following file:
messages.h