ARTS: ARTS::Var::GriddedField5 Class Reference
ARTS::Var::GriddedField5 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField5 () noexcept
GriddedField5 (std::size_t i, void *x) noexcept
GriddedField5 (const Group::GriddedField5 &val) noexcept
~GriddedField5 () noexcept
Group::GriddedField5 & value () noexcept
const Group::GriddedField5 & value () const noexcept
GriddedField5 & operator= (const Group::GriddedField5 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField5 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField5 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3095 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField5() [1/3]
ARTS::Var::GriddedField5::GriddedField5 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3100 of file autoarts.h.
GriddedField5() [2/3]
ARTS::Var::GriddedField5::GriddedField5 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3103 of file autoarts.h.
GriddedField5() [3/3]
ARTS::Var::GriddedField5::GriddedField5 (const Group::GriddedField5 & val) inline noexcept
Construct from Group::GriddedField5. Leaves islast() true and isnull() false
Definition at line 3106 of file autoarts.h.
~GriddedField5()
ARTS::Var::GriddedField5::~GriddedField5 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3109 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField5::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3127 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::surface_complex_refr_indexFromGriddedField5(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~GriddedField5().
isnull()
bool ARTS::Var::GriddedField5::isnull () const inline noexcept
Return true if there is no data
Definition at line 3124 of file autoarts.h.
References v.
Referenced by ~GriddedField5().
name()
const Group::String& ARTS::Var::GriddedField5::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3130 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField5& ARTS::Var::GriddedField5::operator= (const Group::GriddedField5 & t) inline noexcept
Set value from Group::GriddedField5. Works when isnull() is false
Definition at line 3118 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField5::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3121 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::surface_complex_refr_indexFromGriddedField5(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::GriddedField5& ARTS::Var::GriddedField5::value () const inline noexcept
Get value const-ref as Group::GriddedField5. Works when isnull() is false
Definition at line 3115 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField5& ARTS::Var::GriddedField5::value () inline noexcept
Get value ref as Group::GriddedField5. Works when isnull() is false
Definition at line 3112 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), operator=(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField5 & var) friend
Output to stream of internal variable
Definition at line 3133 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField5::p private
Definition at line 3096 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField5* ARTS::Var::GriddedField5::v private
Definition at line 3097 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField5().
The documentation for this class was generated from the following file:
autoarts.h