ARTS: ARTS::Var::WorkspacePropagationMatrix Class Reference
ARTS::Var::WorkspacePropagationMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspacePropagationMatrix () noexcept
WorkspacePropagationMatrix (std::size_t i, void *x) noexcept
~WorkspacePropagationMatrix () noexcept
WorkspacePropagationMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspacePropagationMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::PropagationMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1304 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspacePropagationMatrix::type = Group::PropagationMatrix private
Definition at line 1305 of file autoarts.h.
Constructor & Destructor Documentation
WorkspacePropagationMatrix() [1/3]
ARTS::Var::WorkspacePropagationMatrix::WorkspacePropagationMatrix () inline noexcept
Definition at line 1309 of file autoarts.h.
WorkspacePropagationMatrix() [2/3]
ARTS::Var::WorkspacePropagationMatrix::WorkspacePropagationMatrix (std::size_t i, void * x) inline noexcept
Definition at line 1310 of file autoarts.h.
~WorkspacePropagationMatrix()
ARTS::Var::WorkspacePropagationMatrix::~WorkspacePropagationMatrix () inline noexcept
Definition at line 1311 of file autoarts.h.
References islast(), isnull(), and v.
WorkspacePropagationMatrix() [3/3]
ARTS::Var::WorkspacePropagationMatrix::WorkspacePropagationMatrix (const type & val) inline noexcept
Definition at line 1312 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspacePropagationMatrix::islast () const inline noexcept
Definition at line 1318 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspacePropagationMatrix().
isnull()
bool ARTS::Var::WorkspacePropagationMatrix::isnull () const inline noexcept
Definition at line 1317 of file autoarts.h.
References v.
Referenced by ~WorkspacePropagationMatrix().
name()
const Group::String& ARTS::Var::WorkspacePropagationMatrix::name () const inline noexcept
Definition at line 1319 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspacePropagationMatrix& ARTS::Var::WorkspacePropagationMatrix::operator= (const type & t) inline noexcept
Definition at line 1315 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspacePropagationMatrix::pos () const inline noexcept
Definition at line 1316 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspacePropagationMatrix::value () const inline noexcept
Definition at line 1314 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspacePropagationMatrix::value () inline noexcept
Definition at line 1313 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspacePropagationMatrix::p private
Definition at line 1306 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspacePropagationMatrix::v private
Definition at line 1307 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspacePropagationMatrix().
The documentation for this class was generated from the following file:
autoarts.h