ARTS: ARTS::Var::WorkspaceArrayOfArrayOfString Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfString Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfString () noexcept
WorkspaceArrayOfArrayOfString (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfString () noexcept
WorkspaceArrayOfArrayOfString (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfString & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfString
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 404 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfString::type = Group::ArrayOfArrayOfString private
Definition at line 405 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfString() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfString::WorkspaceArrayOfArrayOfString () inline noexcept
Definition at line 409 of file autoarts.h.
WorkspaceArrayOfArrayOfString() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfString::WorkspaceArrayOfArrayOfString (std::size_t i, void * x) inline noexcept
Definition at line 410 of file autoarts.h.
~WorkspaceArrayOfArrayOfString()
ARTS::Var::WorkspaceArrayOfArrayOfString::~WorkspaceArrayOfArrayOfString () inline noexcept
Definition at line 411 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfString() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfString::WorkspaceArrayOfArrayOfString (const type & val) inline noexcept
Definition at line 412 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfString::islast () const inline noexcept
Definition at line 418 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfString().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfString::isnull () const inline noexcept
Definition at line 417 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfString().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfString::name () const inline noexcept
Definition at line 419 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfString& ARTS::Var::WorkspaceArrayOfArrayOfString::operator= (const type & t) inline noexcept
Definition at line 415 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfString::pos () const inline noexcept
Definition at line 416 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfString::value () const inline noexcept
Definition at line 414 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfString::value () inline noexcept
Definition at line 413 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfString::p private
Definition at line 406 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfString::v private
Definition at line 407 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfString().
The documentation for this class was generated from the following file:
autoarts.h