ARTS: ARTS::Var::ArrayOfGriddedField4 Class Reference
ARTS::Var::ArrayOfGriddedField4 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfGriddedField4 () noexcept
ArrayOfGriddedField4 (std::size_t i, void *x) noexcept
ArrayOfGriddedField4 (const Group::ArrayOfGriddedField4 &val) noexcept
~ArrayOfGriddedField4 () noexcept
Group::ArrayOfGriddedField4 & value () noexcept
const Group::ArrayOfGriddedField4 & value () const noexcept
ArrayOfGriddedField4 & operator= (const Group::ArrayOfGriddedField4 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfGriddedField4 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfGriddedField4 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1546 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfGriddedField4() [1/3]
ARTS::Var::ArrayOfGriddedField4::ArrayOfGriddedField4 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1551 of file autoarts.h.
ArrayOfGriddedField4() [2/3]
ARTS::Var::ArrayOfGriddedField4::ArrayOfGriddedField4 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1554 of file autoarts.h.
ArrayOfGriddedField4() [3/3]
ARTS::Var::ArrayOfGriddedField4::ArrayOfGriddedField4 (const Group::ArrayOfGriddedField4 & val) inline noexcept
Construct from Group::ArrayOfGriddedField4. Leaves islast() true and isnull() false
Definition at line 1557 of file autoarts.h.
~ArrayOfGriddedField4()
ARTS::Var::ArrayOfGriddedField4::~ArrayOfGriddedField4 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1560 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfGriddedField4::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1578 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfGriddedField4().
isnull()
bool ARTS::Var::ArrayOfGriddedField4::isnull () const inline noexcept
Return true if there is no data
Definition at line 1575 of file autoarts.h.
References v.
Referenced by ~ArrayOfGriddedField4().
name()
const Group::String& ARTS::Var::ArrayOfGriddedField4::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1581 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfGriddedField4& ARTS::Var::ArrayOfGriddedField4::operator= (const Group::ArrayOfGriddedField4 & t) inline noexcept
Set value from Group::ArrayOfGriddedField4. Works when isnull() is false
Definition at line 1569 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfGriddedField4::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1572 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfGriddedField4& ARTS::Var::ArrayOfGriddedField4::value () const inline noexcept
Get value const-ref as Group::ArrayOfGriddedField4. Works when isnull() is false
Definition at line 1566 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfGriddedField4& ARTS::Var::ArrayOfGriddedField4::value () inline noexcept
Get value ref as Group::ArrayOfGriddedField4. Works when isnull() is false
Definition at line 1563 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfGriddedField4 & var) friend
Output to stream of internal variable
Definition at line 1584 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfGriddedField4::p private
Definition at line 1547 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfGriddedField4* ARTS::Var::ArrayOfGriddedField4::v private
Definition at line 1548 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfGriddedField4().
The documentation for this class was generated from the following file:
autoarts.h