ARTS: ARTS::Var::WorkspaceArrayOfArrayOfIndex Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfIndex Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfIndex () noexcept
WorkspaceArrayOfArrayOfIndex (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfIndex () noexcept
WorkspaceArrayOfArrayOfIndex (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfIndex & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfIndex
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 260 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfIndex::type = Group::ArrayOfArrayOfIndex private
Definition at line 261 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfIndex() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfIndex::WorkspaceArrayOfArrayOfIndex () inline noexcept
Definition at line 265 of file autoarts.h.
WorkspaceArrayOfArrayOfIndex() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfIndex::WorkspaceArrayOfArrayOfIndex (std::size_t i, void * x) inline noexcept
Definition at line 266 of file autoarts.h.
~WorkspaceArrayOfArrayOfIndex()
ARTS::Var::WorkspaceArrayOfArrayOfIndex::~WorkspaceArrayOfArrayOfIndex () inline noexcept
Definition at line 267 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfIndex() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfIndex::WorkspaceArrayOfArrayOfIndex (const type & val) inline noexcept
Definition at line 268 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfIndex::islast () const inline noexcept
Definition at line 274 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfIndex().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfIndex::isnull () const inline noexcept
Definition at line 273 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfIndex().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfIndex::name () const inline noexcept
Definition at line 275 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfIndex& ARTS::Var::WorkspaceArrayOfArrayOfIndex::operator= (const type & t) inline noexcept
Definition at line 271 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfIndex::pos () const inline noexcept
Definition at line 272 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfIndex::value () const inline noexcept
Definition at line 270 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfIndex::value () inline noexcept
Definition at line 269 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfIndex::p private
Definition at line 262 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfIndex::v private
Definition at line 263 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfIndex().
The documentation for this class was generated from the following file:
autoarts.h