ARTS: ARTS::Var::ArrayOfArrayOfTime Class Reference
ARTS::Var::ArrayOfArrayOfTime Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfTime () noexcept
ArrayOfArrayOfTime (std::size_t i, void *x) noexcept
ArrayOfArrayOfTime (const Group::ArrayOfArrayOfTime &val) noexcept
~ArrayOfArrayOfTime () noexcept
Group::ArrayOfArrayOfTime & value () noexcept
const Group::ArrayOfArrayOfTime & value () const noexcept
ArrayOfArrayOfTime & operator= (const Group::ArrayOfArrayOfTime &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfTime * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfTime &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1217 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfTime() [1/3]
ARTS::Var::ArrayOfArrayOfTime::ArrayOfArrayOfTime () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1222 of file autoarts.h.
ArrayOfArrayOfTime() [2/3]
ARTS::Var::ArrayOfArrayOfTime::ArrayOfArrayOfTime (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1225 of file autoarts.h.
ArrayOfArrayOfTime() [3/3]
ARTS::Var::ArrayOfArrayOfTime::ArrayOfArrayOfTime (const Group::ArrayOfArrayOfTime & val) inline noexcept
Construct from Group::ArrayOfArrayOfTime. Leaves islast() true and isnull() false
Definition at line 1228 of file autoarts.h.
~ArrayOfArrayOfTime()
ARTS::Var::ArrayOfArrayOfTime::~ArrayOfArrayOfTime () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1231 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfTime::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1249 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfTime().
isnull()
bool ARTS::Var::ArrayOfArrayOfTime::isnull () const inline noexcept
Return true if there is no data
Definition at line 1246 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfTime().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfTime::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1252 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfTime& ARTS::Var::ArrayOfArrayOfTime::operator= (const Group::ArrayOfArrayOfTime & t) inline noexcept
Set value from Group::ArrayOfArrayOfTime. Works when isnull() is false
Definition at line 1240 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfTime::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1243 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfTime& ARTS::Var::ArrayOfArrayOfTime::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfTime. Works when isnull() is false
Definition at line 1237 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfTime& ARTS::Var::ArrayOfArrayOfTime::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfTime. Works when isnull() is false
Definition at line 1234 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfTime & var) friend
Output to stream of internal variable
Definition at line 1255 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfTime::p private
Definition at line 1218 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfTime* ARTS::Var::ArrayOfArrayOfTime::v private
Definition at line 1219 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfTime().
The documentation for this class was generated from the following file:
autoarts.h