ARTS: ARTS::Var::ArrayOfSpeciesTag Class Reference
ARTS::Var::ArrayOfSpeciesTag Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfSpeciesTag () noexcept
ArrayOfSpeciesTag (std::size_t i, void *x) noexcept
ArrayOfSpeciesTag (const Group::ArrayOfSpeciesTag &val) noexcept
~ArrayOfSpeciesTag () noexcept
Group::ArrayOfSpeciesTag & value () noexcept
const Group::ArrayOfSpeciesTag & value () const noexcept
ArrayOfSpeciesTag & operator= (const Group::ArrayOfSpeciesTag &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfSpeciesTag * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfSpeciesTag &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2115 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfSpeciesTag() [1/3]
ARTS::Var::ArrayOfSpeciesTag::ArrayOfSpeciesTag () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2120 of file autoarts.h.
ArrayOfSpeciesTag() [2/3]
ARTS::Var::ArrayOfSpeciesTag::ArrayOfSpeciesTag (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2123 of file autoarts.h.
ArrayOfSpeciesTag() [3/3]
ARTS::Var::ArrayOfSpeciesTag::ArrayOfSpeciesTag (const Group::ArrayOfSpeciesTag & val) inline noexcept
Construct from Group::ArrayOfSpeciesTag. Leaves islast() true and isnull() false
Definition at line 2126 of file autoarts.h.
~ArrayOfSpeciesTag()
ARTS::Var::ArrayOfSpeciesTag::~ArrayOfSpeciesTag () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2129 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfSpeciesTag::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2147 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::ArrayOfSpeciesTagSet(), ARTS::Agenda::Method::ArrayOfSpeciesTagSet(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::ecs_dataSetMeanAir(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfSpeciesTag().
isnull()
bool ARTS::Var::ArrayOfSpeciesTag::isnull () const inline noexcept
Return true if there is no data
Definition at line 2144 of file autoarts.h.
References v.
Referenced by ~ArrayOfSpeciesTag().
name()
const Group::String& ARTS::Var::ArrayOfSpeciesTag::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2150 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfSpeciesTag& ARTS::Var::ArrayOfSpeciesTag::operator= (const Group::ArrayOfSpeciesTag & t) inline noexcept
Set value from Group::ArrayOfSpeciesTag. Works when isnull() is false
Definition at line 2138 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfSpeciesTag::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2141 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Agenda::Method::ArrayOfSpeciesTagSet(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::ecs_dataSetMeanAir(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfSpeciesTag& ARTS::Var::ArrayOfSpeciesTag::value () const inline noexcept
Get value const-ref as Group::ArrayOfSpeciesTag. Works when isnull() is false
Definition at line 2135 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfSpeciesTag& ARTS::Var::ArrayOfSpeciesTag::value () inline noexcept
Get value ref as Group::ArrayOfSpeciesTag. Works when isnull() is false
Definition at line 2132 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::ArrayOfSpeciesTagSet(), ARTS::Agenda::Method::ArrayOfSpeciesTagSet(), ARTS::Method::Copy(), ARTS::Method::ecs_dataSetMeanAir(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfSpeciesTag & var) friend
Output to stream of internal variable
Definition at line 2153 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfSpeciesTag::p private
Definition at line 2116 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfSpeciesTag* ARTS::Var::ArrayOfSpeciesTag::v private
Definition at line 2117 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfSpeciesTag().
The documentation for this class was generated from the following file:
autoarts.h