ARTS: ARTS::Var::GridPos Class Reference
ARTS::Var::GridPos Class Reference
#include <autoarts.h>
Public Member Functions
GridPos () noexcept
GridPos (std::size_t i, void *x) noexcept
GridPos (const Group::GridPos &val) noexcept
~GridPos () noexcept
Group::GridPos & value () noexcept
const Group::GridPos & value () const noexcept
GridPos & operator= (const Group::GridPos &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GridPos * v
Friends
std::ostream & operator<< (std::ostream &os, const GridPos &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2914 of file autoarts.h.
Constructor & Destructor Documentation
GridPos() [1/3]
ARTS::Var::GridPos::GridPos () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2919 of file autoarts.h.
GridPos() [2/3]
ARTS::Var::GridPos::GridPos (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2922 of file autoarts.h.
GridPos() [3/3]
ARTS::Var::GridPos::GridPos (const Group::GridPos & val) inline noexcept
Construct from Group::GridPos. Leaves islast() true and isnull() false
Definition at line 2925 of file autoarts.h.
~GridPos()
ARTS::Var::GridPos::~GridPos () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2928 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GridPos::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2946 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~GridPos().
isnull()
bool ARTS::Var::GridPos::isnull () const inline noexcept
Return true if there is no data
Definition at line 2943 of file autoarts.h.
References v.
Referenced by ~GridPos().
name()
const Group::String& ARTS::Var::GridPos::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2949 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GridPos& ARTS::Var::GridPos::operator= (const Group::GridPos & t) inline noexcept
Set value from Group::GridPos. Works when isnull() is false
Definition at line 2937 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GridPos::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2940 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::GridPos& ARTS::Var::GridPos::value () const inline noexcept
Get value const-ref as Group::GridPos. Works when isnull() is false
Definition at line 2934 of file autoarts.h.
References v.
value() [2/2]
Group::GridPos& ARTS::Var::GridPos::value () inline noexcept
Get value ref as Group::GridPos. Works when isnull() is false
Definition at line 2931 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GridPos & var) friend
Output to stream of internal variable
Definition at line 2952 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GridPos::p private
Definition at line 2915 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GridPos* ARTS::Var::GridPos::v private
Definition at line 2916 of file autoarts.h.
Referenced by isnull(), value(), and ~GridPos().
The documentation for this class was generated from the following file:
autoarts.h