ARTS: ARTS::Var::ArrayOfQuantumIdentifier Class Reference
ARTS::Var::ArrayOfQuantumIdentifier Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfQuantumIdentifier () noexcept
ArrayOfQuantumIdentifier (std::size_t i, void *x) noexcept
ArrayOfQuantumIdentifier (const Group::ArrayOfQuantumIdentifier &val) noexcept
~ArrayOfQuantumIdentifier () noexcept
Group::ArrayOfQuantumIdentifier & value () noexcept
const Group::ArrayOfQuantumIdentifier & value () const noexcept
ArrayOfQuantumIdentifier & operator= (const Group::ArrayOfQuantumIdentifier &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfQuantumIdentifier * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfQuantumIdentifier &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1826 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfQuantumIdentifier() [1/3]
ARTS::Var::ArrayOfQuantumIdentifier::ArrayOfQuantumIdentifier () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1831 of file autoarts.h.
ArrayOfQuantumIdentifier() [2/3]
ARTS::Var::ArrayOfQuantumIdentifier::ArrayOfQuantumIdentifier (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1834 of file autoarts.h.
ArrayOfQuantumIdentifier() [3/3]
ARTS::Var::ArrayOfQuantumIdentifier::ArrayOfQuantumIdentifier (const Group::ArrayOfQuantumIdentifier & val) inline noexcept
Construct from Group::ArrayOfQuantumIdentifier. Leaves islast() true and isnull() false
Definition at line 1837 of file autoarts.h.
~ArrayOfQuantumIdentifier()
ARTS::Var::ArrayOfQuantumIdentifier::~ArrayOfQuantumIdentifier () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1840 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfQuantumIdentifier::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1858 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::Copy(), and ~ArrayOfQuantumIdentifier().
isnull()
bool ARTS::Var::ArrayOfQuantumIdentifier::isnull () const inline noexcept
Return true if there is no data
Definition at line 1855 of file autoarts.h.
References v.
Referenced by ~ArrayOfQuantumIdentifier().
name()
const Group::String& ARTS::Var::ArrayOfQuantumIdentifier::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1861 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfQuantumIdentifier& ARTS::Var::ArrayOfQuantumIdentifier::operator= (const Group::ArrayOfQuantumIdentifier & t) inline noexcept
Set value from Group::ArrayOfQuantumIdentifier. Works when isnull() is false
Definition at line 1849 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfQuantumIdentifier::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1852 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfQuantumIdentifier& ARTS::Var::ArrayOfQuantumIdentifier::value () const inline noexcept
Get value const-ref as Group::ArrayOfQuantumIdentifier. Works when isnull() is false
Definition at line 1846 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfQuantumIdentifier& ARTS::Var::ArrayOfQuantumIdentifier::value () inline noexcept
Get value ref as Group::ArrayOfQuantumIdentifier. Works when isnull() is false
Definition at line 1843 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetZeemanCoefficients(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), operator=(), and ARTS::Method::retrievalAddCatalogParameters().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfQuantumIdentifier & var) friend
Output to stream of internal variable
Definition at line 1864 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfQuantumIdentifier::p private
Definition at line 1827 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfQuantumIdentifier* ARTS::Var::ArrayOfQuantumIdentifier::v private
Definition at line 1828 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfQuantumIdentifier().
The documentation for this class was generated from the following file:
autoarts.h