ARTS: double_istream Class Reference
double_istream Class Reference
Input stream class for doubles that correctly handles nan and inf.
#include <file.h>
Public Member Functions
double_istream (std::istream &i)
double_istream & parse_on_fail (double &x, bool neg)
double_istream & operator>> (double &x)
Private Attributes
std::istream & in
Detailed Description
Input stream class for doubles that correctly handles nan and inf.
Definition at line 93 of file file.h.
Constructor & Destructor Documentation
double_istream()
double_istream::double_istream (std::istream & i) inline
Definition at line 95 of file file.h.
Member Function Documentation
operator>>()
double_istream& double_istream::operator>> (double & x) inline
Definition at line 99 of file file.h.
References c, in, parse_on_fail(), and ARTS::Var::x().
parse_on_fail()
double_istream & double_istream::parse_on_fail (double & x, bool neg)
Definition at line 602 of file file.cc.
Referenced by operator>>().
Member Data Documentation
in
std::istream& double_istream::in private
Definition at line 113 of file file.h.
Referenced by operator>>().
The documentation for this class was generated from the following files:
file.h
file.cc