ARTS: LineShape::SingleSpeciesModel Class Reference
LineShape::SingleSpeciesModel Class Reference
Compute the line shape parameters for a single broadening species.
#include <lineshapemodel.h>
Public Member Functions
constexpr SingleSpeciesModel (ModelParameters G0=ModelParameters{}, ModelParameters D0=ModelParameters{}, ModelParameters G2=ModelParameters{}, ModelParameters D2=ModelParameters{}, ModelParameters FVC=ModelParameters{}, ModelParameters ETA=ModelParameters{}, ModelParameters Y=ModelParameters{}, ModelParameters G=ModelParameters{}, ModelParameters DV=ModelParameters{})
Default initialization.
Numeric compute (Numeric T, Numeric T0, Variable var) const noexcept
Compute the broadening parameter at the input.
Numeric compute_dX0 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x0.
Numeric compute_dX1 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x1.
Numeric compute_dX2 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x2.
Numeric compute_dX3 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x3.
Numeric compute_dT (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt T.
Numeric compute_dT0 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt T0.
ACCESS_INTERNAL (G0)
ACCESS_INTERNAL (D0)
ACCESS_INTERNAL (G2)
ACCESS_INTERNAL (D2)
ACCESS_INTERNAL (FVC)
ACCESS_INTERNAL (ETA)
ACCESS_INTERNAL (Y)
ACCESS_INTERNAL (G)
ACCESS_INTERNAL (DV)
constexpr std::array< ModelParameters, nVars > & Data () noexcept
Get internal Data reference.
constexpr const std::array< ModelParameters, nVars > & Data () const noexcept
Get const internal Data reference.
constexpr void Set (Variable var, const ModelParameters &x) noexcept
Set variable to a different ModelParameters.
constexpr ModelParameters Get (Variable var) const noexcept
Get variable by type.
bifstream & read (bifstream &bif)
Binary read for SingleSpeciesModel.
bofstream & write (bofstream &bof) const
Binary write for SingleSpeciesModel.
bool MatchTypes (const SingleSpeciesModel &other) const noexcept
Private Member Functions
constexpr Numeric special_linemixing_aer (Numeric T, ModelParameters mp) const noexcept
Line mixing as done by AER data in ARTS.
constexpr Numeric special_linemixing_aer_dT (Numeric T, ModelParameters mp) const noexcept
The temperature derivative of special_linemixing_aer.
constexpr Numeric special_linemixing_aer_dX0 (Numeric T) const noexcept
The derivative of special_linemixing_aer wrt X0.
constexpr Numeric special_linemixing_aer_dX1 (Numeric T) const noexcept
The derivative of special_linemixing_aer wrt X1.
constexpr Numeric special_linemixing_aer_dX2 (Numeric T) const noexcept
The derivative of special_linemixing_aer wrt X2.
constexpr Numeric special_linemixing_aer_dX3 (Numeric T) const noexcept
The derivative of special_linemixing_aer wrt X3.
Private Attributes
std::array< ModelParameters, nVars > X
Detailed Description
Compute the line shape parameters for a single broadening species.
Definition at line 197 of file lineshapemodel.h.
Constructor & Destructor Documentation
SingleSpeciesModel()
constexpr LineShape::SingleSpeciesModel::SingleSpeciesModel (ModelParameters G0 = ModelParameters{}, ModelParameters D0 = ModelParameters{}, ModelParameters G2 = ModelParameters{}, ModelParameters D2 = ModelParameters{}, ModelParameters FVC = ModelParameters{}, ModelParameters ETA = ModelParameters{}, ModelParameters Y = ModelParameters{}, ModelParameters G = ModelParameters{}, ModelParameters DV = ModelParameters{}) inline constexpr
Default initialization.
Definition at line 299 of file lineshapemodel.h.
Member Function Documentation
ACCESS_INTERNAL() [1/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (D0)
ACCESS_INTERNAL() [2/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (D2)
ACCESS_INTERNAL() [3/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (DV)
ACCESS_INTERNAL() [4/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (ETA)
ACCESS_INTERNAL() [5/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (FVC)
ACCESS_INTERNAL() [6/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (G)
ACCESS_INTERNAL() [7/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (G0)
ACCESS_INTERNAL() [8/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (G2)
ACCESS_INTERNAL() [9/9]
LineShape::SingleSpeciesModel::ACCESS_INTERNAL (Y)
compute()
Numeric LineShape::SingleSpeciesModel::compute (Numeric T, Numeric T0, Variable var) const noexcept
Compute the broadening parameter at the input.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
The broadening parameter at temperature
Definition at line 741 of file lineshapemodel.cc.
compute_dT()
Numeric LineShape::SingleSpeciesModel::compute_dT (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt T.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt T
Definition at line 886 of file lineshapemodel.cc.
compute_dT0()
Numeric LineShape::SingleSpeciesModel::compute_dT0 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt T0.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt T0
Definition at line 917 of file lineshapemodel.cc.
compute_dX0()
Numeric LineShape::SingleSpeciesModel::compute_dX0 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x0.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt x0
Definition at line 770 of file lineshapemodel.cc.
compute_dX1()
Numeric LineShape::SingleSpeciesModel::compute_dX1 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x1.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt x1
Definition at line 799 of file lineshapemodel.cc.
compute_dX2()
Numeric LineShape::SingleSpeciesModel::compute_dX2 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x2.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt x2
Definition at line 828 of file lineshapemodel.cc.
compute_dX3()
Numeric LineShape::SingleSpeciesModel::compute_dX3 (Numeric T, Numeric T0, Variable var) const noexcept
Derivative of compute(...) wrt x3.
Parameters
[in] T The temperature
[in] T0 The temperature used to derive the coefficients
[in] var The variable
Returns
Derivative of compute(...) wrt x3
Definition at line 857 of file lineshapemodel.cc.
Data() [1/2]
constexpr const std::array<ModelParameters, nVars>& LineShape::SingleSpeciesModel::Data () const inline constexpr noexcept
Get const internal Data reference.
Definition at line 399 of file lineshapemodel.h.
References X.
Data() [2/2]
constexpr std::array<ModelParameters, nVars>& LineShape::SingleSpeciesModel::Data () inline constexpr noexcept
Get internal Data reference.
Definition at line 396 of file lineshapemodel.h.
References X.
Referenced by LineShape::operator<<(), and LineShape::operator>>().
Get()
constexpr ModelParameters LineShape::SingleSpeciesModel::Get (Variable var) const inline constexpr noexcept
Get variable by type.
Parameters
[in] var The variable type
Returns
ModelParameters copy
Definition at line 432 of file lineshapemodel.h.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, MODELPARAMCASEGETTER, Raw::Average::var(), and LineShape::Y.
MatchTypes()
bool LineShape::SingleSpeciesModel::MatchTypes (const SingleSpeciesModel & other) const noexcept
Definition at line 969 of file lineshapemodel.cc.
References a, and b.
read()
bifstream & LineShape::SingleSpeciesModel::read (bifstream & bif)
Binary read for SingleSpeciesModel.
Definition at line 953 of file lineshapemodel.cc.
References data, ARTS::Var::x(), and X.
Set()
constexpr void LineShape::SingleSpeciesModel::Set (Variable var, const ModelParameters & x) inline constexpr noexcept
Set variable to a different ModelParameters.
Parameters
[in] var The variable
[in] x The new ModelParameters for var
Definition at line 406 of file lineshapemodel.h.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, MODELPARAMCASESETTER, Raw::Average::var(), and LineShape::Y.
special_linemixing_aer()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer (Numeric T, ModelParameters mp) const inline constexpr private noexcept
Line mixing as done by AER data in ARTS.
Uses piece-wise linear interpolation and extrapolates at the edges
var must be G or Y
Parameters
[in] T The temperature
[in] var The variable
Returns
The broadening parameter at temperature
Definition at line 212 of file lineshapemodel.h.
special_linemixing_aer_dT()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer_dT (Numeric T, ModelParameters mp) const inline constexpr private noexcept
The temperature derivative of special_linemixing_aer.
Parameters
[in] T The temperature
[in] var The variable
Returns
The temperature derivative of the broadening parameter at temperature
Definition at line 228 of file lineshapemodel.h.
special_linemixing_aer_dX0()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer_dX0 (Numeric T) const inline constexpr private noexcept
The derivative of special_linemixing_aer wrt X0.
Parameters
[in] T The temperature
Returns
The temperature derivative of the broadening parameter at temperature
Definition at line 243 of file lineshapemodel.h.
special_linemixing_aer_dX1()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer_dX1 (Numeric T) const inline constexpr private noexcept
The derivative of special_linemixing_aer wrt X1.
Parameters
[in] T The temperature
Returns
The temperature derivative of the broadening parameter at temperature
Definition at line 258 of file lineshapemodel.h.
special_linemixing_aer_dX2()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer_dX2 (Numeric T) const inline constexpr private noexcept
The derivative of special_linemixing_aer wrt X2.
Parameters
[in] T The temperature
Returns
The temperature derivative of the broadening parameter at temperature
Definition at line 273 of file lineshapemodel.h.
special_linemixing_aer_dX3()
constexpr Numeric LineShape::SingleSpeciesModel::special_linemixing_aer_dX3 (Numeric T) const inline constexpr private noexcept
The derivative of special_linemixing_aer wrt X3.
Parameters
[in] T The temperature
Returns
The temperature derivative of the broadening parameter at temperature
Definition at line 288 of file lineshapemodel.h.
write()
bofstream & LineShape::SingleSpeciesModel::write (bofstream & bof) const
Binary write for SingleSpeciesModel.
Definition at line 962 of file lineshapemodel.cc.
References data, and X.
Member Data Documentation
X
std::array<ModelParameters, nVars> LineShape::SingleSpeciesModel::X private
Definition at line 199 of file lineshapemodel.h.
Referenced by Data(), read(), and write().
The documentation for this class was generated from the following files:
lineshapemodel.h
lineshapemodel.cc