ARTS: ARTS::Var::WorkspaceTensor6 Class Reference
ARTS::Var::WorkspaceTensor6 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTensor6 () noexcept
WorkspaceTensor6 (std::size_t i, void *x) noexcept
~WorkspaceTensor6 () noexcept
WorkspaceTensor6 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTensor6 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Tensor6
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1556 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTensor6::type = Group::Tensor6 private
Definition at line 1557 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTensor6() [1/3]
ARTS::Var::WorkspaceTensor6::WorkspaceTensor6 () inline noexcept
Definition at line 1561 of file autoarts.h.
WorkspaceTensor6() [2/3]
ARTS::Var::WorkspaceTensor6::WorkspaceTensor6 (std::size_t i, void * x) inline noexcept
Definition at line 1562 of file autoarts.h.
~WorkspaceTensor6()
ARTS::Var::WorkspaceTensor6::~WorkspaceTensor6 () inline noexcept
Definition at line 1563 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTensor6() [3/3]
ARTS::Var::WorkspaceTensor6::WorkspaceTensor6 (const type & val) inline noexcept
Definition at line 1564 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTensor6::islast () const inline noexcept
Definition at line 1570 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::nvitrinesGet(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::Tensor6Scale(), ARTS::Method::Tensor6Scale(), ARTS::AgendaMethod::Tensor6SetConstant(), ARTS::Method::Tensor6SetConstant(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTensor6().
isnull()
bool ARTS::Var::WorkspaceTensor6::isnull () const inline noexcept
Definition at line 1569 of file autoarts.h.
References v.
Referenced by ~WorkspaceTensor6().
name()
const Group::String& ARTS::Var::WorkspaceTensor6::name () const inline noexcept
Definition at line 1571 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTensor6& ARTS::Var::WorkspaceTensor6::operator= (const type & t) inline noexcept
Definition at line 1567 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTensor6::pos () const inline noexcept
Definition at line 1568 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::nvitrinesGet(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor6Scale(), ARTS::AgendaMethod::Tensor6SetConstant(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTensor6::value () const inline noexcept
Definition at line 1566 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTensor6::value () inline noexcept
Definition at line 1565 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), ARTS::Method::nvitrinesGet(), operator=(), ARTS::Method::Reduce(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTensor6::p private
Definition at line 1558 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTensor6::v private
Definition at line 1559 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTensor6().
The documentation for this class was generated from the following file:
autoarts.h