ARTS: ARTS::Var::ArrayOfSingleScatteringData Class Reference
ARTS::Var::ArrayOfSingleScatteringData Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfSingleScatteringData () noexcept
ArrayOfSingleScatteringData (std::size_t i, void *x) noexcept
ArrayOfSingleScatteringData (const Group::ArrayOfSingleScatteringData &val) noexcept
~ArrayOfSingleScatteringData () noexcept
Group::ArrayOfSingleScatteringData & value () noexcept
const Group::ArrayOfSingleScatteringData & value () const noexcept
ArrayOfSingleScatteringData & operator= (const Group::ArrayOfSingleScatteringData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfSingleScatteringData * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfSingleScatteringData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2014 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfSingleScatteringData() [1/3]
ARTS::Var::ArrayOfSingleScatteringData::ArrayOfSingleScatteringData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2019 of file autoarts.h.
ArrayOfSingleScatteringData() [2/3]
ARTS::Var::ArrayOfSingleScatteringData::ArrayOfSingleScatteringData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2022 of file autoarts.h.
ArrayOfSingleScatteringData() [3/3]
ARTS::Var::ArrayOfSingleScatteringData::ArrayOfSingleScatteringData (const Group::ArrayOfSingleScatteringData & val) inline noexcept
Construct from Group::ArrayOfSingleScatteringData. Leaves islast() true and isnull() false
Definition at line 2025 of file autoarts.h.
~ArrayOfSingleScatteringData()
ARTS::Var::ArrayOfSingleScatteringData::~ArrayOfSingleScatteringData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2028 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfSingleScatteringData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2046 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfSingleScatteringData().
isnull()
bool ARTS::Var::ArrayOfSingleScatteringData::isnull () const inline noexcept
Return true if there is no data
Definition at line 2043 of file autoarts.h.
References v.
Referenced by ~ArrayOfSingleScatteringData().
name()
const Group::String& ARTS::Var::ArrayOfSingleScatteringData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2049 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfSingleScatteringData& ARTS::Var::ArrayOfSingleScatteringData::operator= (const Group::ArrayOfSingleScatteringData & t) inline noexcept
Set value from Group::ArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 2037 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfSingleScatteringData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2040 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfSingleScatteringData& ARTS::Var::ArrayOfSingleScatteringData::value () const inline noexcept
Get value const-ref as Group::ArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 2034 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfSingleScatteringData& ARTS::Var::ArrayOfSingleScatteringData::value () inline noexcept
Get value ref as Group::ArrayOfSingleScatteringData. Works when isnull() is false
Definition at line 2031 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfSingleScatteringData & var) friend
Output to stream of internal variable
Definition at line 2052 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfSingleScatteringData::p private
Definition at line 2015 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfSingleScatteringData* ARTS::Var::ArrayOfSingleScatteringData::v private
Definition at line 2016 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfSingleScatteringData().
The documentation for this class was generated from the following file:
autoarts.h