ARTS: ARTS::Var::WorkspaceArrayOfTensor7 Class Reference
ARTS::Var::WorkspaceArrayOfTensor7 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTensor7 () noexcept
WorkspaceArrayOfTensor7 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTensor7 () noexcept
WorkspaceArrayOfTensor7 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTensor7 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor7
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 908 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTensor7::type = Group::ArrayOfTensor7 private
Definition at line 909 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTensor7() [1/3]
ARTS::Var::WorkspaceArrayOfTensor7::WorkspaceArrayOfTensor7 () inline noexcept
Definition at line 913 of file autoarts.h.
WorkspaceArrayOfTensor7() [2/3]
ARTS::Var::WorkspaceArrayOfTensor7::WorkspaceArrayOfTensor7 (std::size_t i, void * x) inline noexcept
Definition at line 914 of file autoarts.h.
~WorkspaceArrayOfTensor7()
ARTS::Var::WorkspaceArrayOfTensor7::~WorkspaceArrayOfTensor7 () inline noexcept
Definition at line 915 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTensor7() [3/3]
ARTS::Var::WorkspaceArrayOfTensor7::WorkspaceArrayOfTensor7 (const type & val) inline noexcept
Definition at line 916 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTensor7::islast () const inline noexcept
Definition at line 922 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTensor7().
isnull()
bool ARTS::Var::WorkspaceArrayOfTensor7::isnull () const inline noexcept
Definition at line 921 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTensor7().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTensor7::name () const inline noexcept
Definition at line 923 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTensor7& ARTS::Var::WorkspaceArrayOfTensor7::operator= (const type & t) inline noexcept
Definition at line 919 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTensor7::pos () const inline noexcept
Definition at line 920 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTensor7::value () const inline noexcept
Definition at line 918 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTensor7::value () inline noexcept
Definition at line 917 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTensor7::p private
Definition at line 910 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTensor7::v private
Definition at line 911 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTensor7().
The documentation for this class was generated from the following file:
autoarts.h