ARTS: ARTS::Var::WorkspaceCIARecord Class Reference
ARTS::Var::WorkspaceCIARecord Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceCIARecord () noexcept
WorkspaceCIARecord (std::size_t i, void *x) noexcept
~WorkspaceCIARecord () noexcept
WorkspaceCIARecord (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceCIARecord & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::CIARecord
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 998 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceCIARecord::type = Group::CIARecord private
Definition at line 999 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceCIARecord() [1/3]
ARTS::Var::WorkspaceCIARecord::WorkspaceCIARecord () inline noexcept
Definition at line 1003 of file autoarts.h.
WorkspaceCIARecord() [2/3]
ARTS::Var::WorkspaceCIARecord::WorkspaceCIARecord (std::size_t i, void * x) inline noexcept
Definition at line 1004 of file autoarts.h.
~WorkspaceCIARecord()
ARTS::Var::WorkspaceCIARecord::~WorkspaceCIARecord () inline noexcept
Definition at line 1005 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceCIARecord() [3/3]
ARTS::Var::WorkspaceCIARecord::WorkspaceCIARecord (const type & val) inline noexcept
Definition at line 1006 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceCIARecord::islast () const inline noexcept
Definition at line 1012 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::CIARecordReadFromFile(), ARTS::Method::CIARecordReadFromFile(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceCIARecord().
isnull()
bool ARTS::Var::WorkspaceCIARecord::isnull () const inline noexcept
Definition at line 1011 of file autoarts.h.
References v.
Referenced by ~WorkspaceCIARecord().
name()
const Group::String& ARTS::Var::WorkspaceCIARecord::name () const inline noexcept
Definition at line 1013 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceCIARecord& ARTS::Var::WorkspaceCIARecord::operator= (const type & t) inline noexcept
Definition at line 1009 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceCIARecord::pos () const inline noexcept
Definition at line 1010 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::CIARecordReadFromFile(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceCIARecord::value () const inline noexcept
Definition at line 1008 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceCIARecord::value () inline noexcept
Definition at line 1007 of file autoarts.h.
References v.
Referenced by ARTS::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceCIARecord::p private
Definition at line 1000 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceCIARecord::v private
Definition at line 1001 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceCIARecord().
The documentation for this class was generated from the following file:
autoarts.h