ARTS: ARTS::Var::GasAbsLookup Class Reference
ARTS::Var::GasAbsLookup Class Reference
#include <autoarts.h>
Public Member Functions
GasAbsLookup () noexcept
GasAbsLookup (std::size_t i, void *x) noexcept
~GasAbsLookup () noexcept
GasAbsLookup (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
GasAbsLookup & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GasAbsLookup
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1074 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::GasAbsLookup::type = Group::GasAbsLookup private
Definition at line 1075 of file autoarts.h.
Constructor & Destructor Documentation
GasAbsLookup() [1/3]
ARTS::Var::GasAbsLookup::GasAbsLookup () inline noexcept
Definition at line 1079 of file autoarts.h.
GasAbsLookup() [2/3]
ARTS::Var::GasAbsLookup::GasAbsLookup (std::size_t i, void * x) inline noexcept
Definition at line 1080 of file autoarts.h.
~GasAbsLookup()
ARTS::Var::GasAbsLookup::~GasAbsLookup () inline noexcept
Definition at line 1081 of file autoarts.h.
References islast(), isnull(), and v.
GasAbsLookup() [3/3]
ARTS::Var::GasAbsLookup::GasAbsLookup (const type & val) inline noexcept
Definition at line 1082 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::GasAbsLookup::islast () const inline noexcept
Definition at line 1088 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~GasAbsLookup().
isnull()
bool ARTS::Var::GasAbsLookup::isnull () const inline noexcept
Definition at line 1087 of file autoarts.h.
References v.
Referenced by ~GasAbsLookup().
name()
const Group::String& ARTS::Var::GasAbsLookup::name () const inline noexcept
Definition at line 1089 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
GasAbsLookup& ARTS::Var::GasAbsLookup::operator= (const type & t) inline noexcept
Definition at line 1085 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GasAbsLookup::pos () const inline noexcept
Definition at line 1086 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::ReadNetCDF(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::GasAbsLookup::value () const inline noexcept
Definition at line 1084 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::GasAbsLookup::value () inline noexcept
Definition at line 1083 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::ReadNetCDF(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::GasAbsLookup::p private
Definition at line 1076 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::GasAbsLookup::v private
Definition at line 1077 of file autoarts.h.
Referenced by isnull(), value(), and ~GasAbsLookup().
The documentation for this class was generated from the following file:
autoarts.h