ARTS: ARTS::Var::CovarianceMatrix Class Reference
ARTS::Var::CovarianceMatrix Class Reference
#include <autoarts.h>
Public Member Functions
CovarianceMatrix () noexcept
CovarianceMatrix (std::size_t i, void *x) noexcept
CovarianceMatrix (const Group::CovarianceMatrix &val) noexcept
~CovarianceMatrix () noexcept
Group::CovarianceMatrix & value () noexcept
const Group::CovarianceMatrix & value () const noexcept
CovarianceMatrix & operator= (const Group::CovarianceMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::CovarianceMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const CovarianceMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2719 of file autoarts.h.
Constructor & Destructor Documentation
CovarianceMatrix() [1/3]
ARTS::Var::CovarianceMatrix::CovarianceMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2724 of file autoarts.h.
CovarianceMatrix() [2/3]
ARTS::Var::CovarianceMatrix::CovarianceMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2727 of file autoarts.h.
CovarianceMatrix() [3/3]
ARTS::Var::CovarianceMatrix::CovarianceMatrix (const Group::CovarianceMatrix & val) inline noexcept
Construct from Group::CovarianceMatrix. Leaves islast() true and isnull() false
Definition at line 2730 of file autoarts.h.
~CovarianceMatrix()
ARTS::Var::CovarianceMatrix::~CovarianceMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2733 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::CovarianceMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2751 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::covmat_seSet(), ARTS::Agenda::Method::covmat_sxSet(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::MatrixFromCovarianceMatrix(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~CovarianceMatrix().
isnull()
bool ARTS::Var::CovarianceMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 2748 of file autoarts.h.
References v.
Referenced by ~CovarianceMatrix().
name()
const Group::String& ARTS::Var::CovarianceMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2754 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
CovarianceMatrix& ARTS::Var::CovarianceMatrix::operator= (const Group::CovarianceMatrix & t) inline noexcept
Set value from Group::CovarianceMatrix. Works when isnull() is false
Definition at line 2742 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::CovarianceMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2745 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::covmat_seSet(), ARTS::Agenda::Method::covmat_sxSet(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::MatrixFromCovarianceMatrix(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::CovarianceMatrix& ARTS::Var::CovarianceMatrix::value () const inline noexcept
Get value const-ref as Group::CovarianceMatrix. Works when isnull() is false
Definition at line 2739 of file autoarts.h.
References v.
value() [2/2]
Group::CovarianceMatrix& ARTS::Var::CovarianceMatrix::value () inline noexcept
Get value ref as Group::CovarianceMatrix. Works when isnull() is false
Definition at line 2736 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::Ignore(), ARTS::Method::MatrixFromCovarianceMatrix(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CovarianceMatrix & var) friend
Output to stream of internal variable
Definition at line 2757 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::CovarianceMatrix::p private
Definition at line 2720 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::CovarianceMatrix* ARTS::Var::CovarianceMatrix::v private
Definition at line 2721 of file autoarts.h.
Referenced by isnull(), value(), and ~CovarianceMatrix().
The documentation for this class was generated from the following file:
autoarts.h