ARTS: ARTS::Var::ArrayOfAbsorptionLines Class Reference
ARTS::Var::ArrayOfAbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfAbsorptionLines () noexcept
ArrayOfAbsorptionLines (std::size_t i, void *x) noexcept
ArrayOfAbsorptionLines (const Group::ArrayOfAbsorptionLines &val) noexcept
~ArrayOfAbsorptionLines () noexcept
Group::ArrayOfAbsorptionLines & value () noexcept
const Group::ArrayOfAbsorptionLines & value () const noexcept
ArrayOfAbsorptionLines & operator= (const Group::ArrayOfAbsorptionLines &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfAbsorptionLines * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfAbsorptionLines &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 425 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfAbsorptionLines() [1/3]
ARTS::Var::ArrayOfAbsorptionLines::ArrayOfAbsorptionLines () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 430 of file autoarts.h.
ArrayOfAbsorptionLines() [2/3]
ARTS::Var::ArrayOfAbsorptionLines::ArrayOfAbsorptionLines (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 433 of file autoarts.h.
ArrayOfAbsorptionLines() [3/3]
ARTS::Var::ArrayOfAbsorptionLines::ArrayOfAbsorptionLines (const Group::ArrayOfAbsorptionLines & val) inline noexcept
Construct from Group::ArrayOfAbsorptionLines. Leaves islast() true and isnull() false
Definition at line 436 of file autoarts.h.
~ArrayOfAbsorptionLines()
ARTS::Var::ArrayOfAbsorptionLines::~ArrayOfAbsorptionLines () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 439 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfAbsorptionLines::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 457 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_linesDeleteWithLines(), ARTS::Agenda::Method::abs_linesReplaceWithLines(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfAbsorptionLines().
isnull()
bool ARTS::Var::ArrayOfAbsorptionLines::isnull () const inline noexcept
Return true if there is no data
Definition at line 454 of file autoarts.h.
References v.
Referenced by ~ArrayOfAbsorptionLines().
name()
const Group::String& ARTS::Var::ArrayOfAbsorptionLines::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 460 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfAbsorptionLines& ARTS::Var::ArrayOfAbsorptionLines::operator= (const Group::ArrayOfAbsorptionLines & t) inline noexcept
Set value from Group::ArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 448 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfAbsorptionLines::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 451 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_linesDeleteWithLines(), ARTS::Agenda::Method::abs_linesReplaceWithLines(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfAbsorptionLines& ARTS::Var::ArrayOfAbsorptionLines::value () const inline noexcept
Get value const-ref as Group::ArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 445 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfAbsorptionLines& ARTS::Var::ArrayOfAbsorptionLines::value () inline noexcept
Get value ref as Group::ArrayOfAbsorptionLines. Works when isnull() is false
Definition at line 442 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_linesDeleteWithLines(), ARTS::Method::abs_linesReplaceWithLines(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfAbsorptionLines & var) friend
Output to stream of internal variable
Definition at line 463 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfAbsorptionLines::p private
Definition at line 426 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfAbsorptionLines* ARTS::Var::ArrayOfAbsorptionLines::v private
Definition at line 427 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfAbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h