ARTS: ARTS::Var::WorkspaceArrayOfString Class Reference
ARTS::Var::WorkspaceArrayOfString Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfString () noexcept
WorkspaceArrayOfString (std::size_t i, void *x) noexcept
~WorkspaceArrayOfString () noexcept
WorkspaceArrayOfString (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfString & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfString
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 800 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfString::type = Group::ArrayOfString private
Definition at line 801 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfString() [1/3]
ARTS::Var::WorkspaceArrayOfString::WorkspaceArrayOfString () inline noexcept
Definition at line 805 of file autoarts.h.
WorkspaceArrayOfString() [2/3]
ARTS::Var::WorkspaceArrayOfString::WorkspaceArrayOfString (std::size_t i, void * x) inline noexcept
Definition at line 806 of file autoarts.h.
~WorkspaceArrayOfString()
ARTS::Var::WorkspaceArrayOfString::~WorkspaceArrayOfString () inline noexcept
Definition at line 807 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfString() [3/3]
ARTS::Var::WorkspaceArrayOfString::WorkspaceArrayOfString (const type & val) inline noexcept
Definition at line 808 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfString::islast () const inline noexcept
Definition at line 814 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_speciesAdd(), ARTS::AgendaMethod::abs_speciesSet(), ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::ArrayOfQuantumIdentifierSet(), ARTS::AgendaMethod::ArrayOfStringSet(), ARTS::Method::ArrayOfStringSet(), ARTS::AgendaMethod::atm_fields_compactFromMatrix(), ARTS::AgendaMethod::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::AgendaMethod::CIAInfo(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameters(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameters(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::retrievalAddCatalogParameters(), ARTS::AgendaMethod::ScatElementsPndAndScatAdd(), ARTS::AgendaMethod::ScatElementsToabs_speciesAdd(), ARTS::AgendaMethod::ScatSpeciesPndAndScatAdd(), ARTS::AgendaMethod::ScatSpeciesScatAndMetaRead(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfString().
isnull()
bool ARTS::Var::WorkspaceArrayOfString::isnull () const inline noexcept
Definition at line 813 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfString().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfString::name () const inline noexcept
Definition at line 815 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfString& ARTS::Var::WorkspaceArrayOfString::operator= (const type & t) inline noexcept
Definition at line 811 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfString::pos () const inline noexcept
Definition at line 812 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_speciesAdd(), ARTS::AgendaMethod::abs_speciesSet(), ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::ArrayOfQuantumIdentifierSet(), ARTS::AgendaMethod::ArrayOfStringSet(), ARTS::AgendaMethod::atm_fields_compactFromMatrix(), ARTS::AgendaMethod::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::AgendaMethod::CIAInfo(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameters(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameters(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::retrievalAddCatalogParameters(), ARTS::AgendaMethod::ScatElementsPndAndScatAdd(), ARTS::AgendaMethod::ScatElementsToabs_speciesAdd(), ARTS::AgendaMethod::ScatSpeciesPndAndScatAdd(), ARTS::AgendaMethod::ScatSpeciesScatAndMetaRead(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfString::value () const inline noexcept
Definition at line 810 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfString::value () inline noexcept
Definition at line 809 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_speciesAdd(), ARTS::Method::abs_speciesSet(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::AgendaMethod::ArrayOfStringSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::CIAInfo(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::retrievalAddCatalogParameters(), ARTS::Method::ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::Select(), ARTS::Method::Touch(), and ARTS::Method::transmittanceFromIy_aux().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfString::p private
Definition at line 802 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfString::v private
Definition at line 803 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfString().
The documentation for this class was generated from the following file:
autoarts.h