ARTS: ARTS::Var::ArrayOfArrayOfRadiationVector Class Reference
ARTS::Var::ArrayOfArrayOfRadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfRadiationVector () noexcept
ArrayOfArrayOfRadiationVector (std::size_t i, void *x) noexcept
ArrayOfArrayOfRadiationVector (const Group::ArrayOfArrayOfRadiationVector &val) noexcept
~ArrayOfArrayOfRadiationVector () noexcept
Group::ArrayOfArrayOfRadiationVector & value () noexcept
const Group::ArrayOfArrayOfRadiationVector & value () const noexcept
ArrayOfArrayOfRadiationVector & operator= (const Group::ArrayOfArrayOfRadiationVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfRadiationVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfRadiationVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 841 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfRadiationVector() [1/3]
ARTS::Var::ArrayOfArrayOfRadiationVector::ArrayOfArrayOfRadiationVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 846 of file autoarts.h.
ArrayOfArrayOfRadiationVector() [2/3]
ARTS::Var::ArrayOfArrayOfRadiationVector::ArrayOfArrayOfRadiationVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 849 of file autoarts.h.
ArrayOfArrayOfRadiationVector() [3/3]
ARTS::Var::ArrayOfArrayOfRadiationVector::ArrayOfArrayOfRadiationVector (const Group::ArrayOfArrayOfRadiationVector & val) inline noexcept
Construct from Group::ArrayOfArrayOfRadiationVector. Leaves islast() true and isnull() false
Definition at line 852 of file autoarts.h.
~ArrayOfArrayOfRadiationVector()
ARTS::Var::ArrayOfArrayOfRadiationVector::~ArrayOfArrayOfRadiationVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 855 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfRadiationVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 873 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfArrayOfRadiationVector().
isnull()
bool ARTS::Var::ArrayOfArrayOfRadiationVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 870 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfRadiationVector().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfRadiationVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 876 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfRadiationVector& ARTS::Var::ArrayOfArrayOfRadiationVector::operator= (const Group::ArrayOfArrayOfRadiationVector & t) inline noexcept
Set value from Group::ArrayOfArrayOfRadiationVector. Works when isnull() is false
Definition at line 864 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfRadiationVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 867 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfArrayOfRadiationVector& ARTS::Var::ArrayOfArrayOfRadiationVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfRadiationVector. Works when isnull() is false
Definition at line 861 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfRadiationVector& ARTS::Var::ArrayOfArrayOfRadiationVector::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfRadiationVector. Works when isnull() is false
Definition at line 858 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfRadiationVector & var) friend
Output to stream of internal variable
Definition at line 879 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfRadiationVector::p private
Definition at line 842 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfRadiationVector* ARTS::Var::ArrayOfArrayOfRadiationVector::v private
Definition at line 843 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfRadiationVector().
The documentation for this class was generated from the following file:
autoarts.h