ARTS: ARTS::Var::WorkspaceMCAntenna Class Reference
ARTS::Var::WorkspaceMCAntenna Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceMCAntenna () noexcept
WorkspaceMCAntenna (std::size_t i, void *x) noexcept
~WorkspaceMCAntenna () noexcept
WorkspaceMCAntenna (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceMCAntenna & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::MCAntenna
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1232 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceMCAntenna::type = Group::MCAntenna private
Definition at line 1233 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceMCAntenna() [1/3]
ARTS::Var::WorkspaceMCAntenna::WorkspaceMCAntenna () inline noexcept
Definition at line 1237 of file autoarts.h.
WorkspaceMCAntenna() [2/3]
ARTS::Var::WorkspaceMCAntenna::WorkspaceMCAntenna (std::size_t i, void * x) inline noexcept
Definition at line 1238 of file autoarts.h.
~WorkspaceMCAntenna()
ARTS::Var::WorkspaceMCAntenna::~WorkspaceMCAntenna () inline noexcept
Definition at line 1239 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceMCAntenna() [3/3]
ARTS::Var::WorkspaceMCAntenna::WorkspaceMCAntenna (const type & val) inline noexcept
Definition at line 1240 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceMCAntenna::islast () const inline noexcept
Definition at line 1246 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceMCAntenna().
isnull()
bool ARTS::Var::WorkspaceMCAntenna::isnull () const inline noexcept
Definition at line 1245 of file autoarts.h.
References v.
Referenced by ~WorkspaceMCAntenna().
name()
const Group::String& ARTS::Var::WorkspaceMCAntenna::name () const inline noexcept
Definition at line 1247 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceMCAntenna& ARTS::Var::WorkspaceMCAntenna::operator= (const type & t) inline noexcept
Definition at line 1243 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceMCAntenna::pos () const inline noexcept
Definition at line 1244 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceMCAntenna::value () const inline noexcept
Definition at line 1242 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceMCAntenna::value () inline noexcept
Definition at line 1241 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceMCAntenna::p private
Definition at line 1234 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceMCAntenna::v private
Definition at line 1235 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceMCAntenna().
The documentation for this class was generated from the following file:
autoarts.h