ARTS: ARTS::Var::ArrayOfGriddedField2 Class Reference
ARTS::Var::ArrayOfGriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfGriddedField2 () noexcept
ArrayOfGriddedField2 (std::size_t i, void *x) noexcept
ArrayOfGriddedField2 (const Group::ArrayOfGriddedField2 &val) noexcept
~ArrayOfGriddedField2 () noexcept
Group::ArrayOfGriddedField2 & value () noexcept
const Group::ArrayOfGriddedField2 & value () const noexcept
ArrayOfGriddedField2 & operator= (const Group::ArrayOfGriddedField2 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfGriddedField2 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfGriddedField2 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1452 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfGriddedField2() [1/3]
ARTS::Var::ArrayOfGriddedField2::ArrayOfGriddedField2 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1457 of file autoarts.h.
ArrayOfGriddedField2() [2/3]
ARTS::Var::ArrayOfGriddedField2::ArrayOfGriddedField2 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1460 of file autoarts.h.
ArrayOfGriddedField2() [3/3]
ARTS::Var::ArrayOfGriddedField2::ArrayOfGriddedField2 (const Group::ArrayOfGriddedField2 & val) inline noexcept
Construct from Group::ArrayOfGriddedField2. Leaves islast() true and isnull() false
Definition at line 1463 of file autoarts.h.
~ArrayOfGriddedField2()
ARTS::Var::ArrayOfGriddedField2::~ArrayOfGriddedField2 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1466 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfGriddedField2::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1484 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfGriddedField2().
isnull()
bool ARTS::Var::ArrayOfGriddedField2::isnull () const inline noexcept
Return true if there is no data
Definition at line 1481 of file autoarts.h.
References v.
Referenced by ~ArrayOfGriddedField2().
name()
const Group::String& ARTS::Var::ArrayOfGriddedField2::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1487 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfGriddedField2& ARTS::Var::ArrayOfGriddedField2::operator= (const Group::ArrayOfGriddedField2 & t) inline noexcept
Set value from Group::ArrayOfGriddedField2. Works when isnull() is false
Definition at line 1475 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfGriddedField2::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1478 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfGriddedField2& ARTS::Var::ArrayOfGriddedField2::value () const inline noexcept
Get value const-ref as Group::ArrayOfGriddedField2. Works when isnull() is false
Definition at line 1472 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfGriddedField2& ARTS::Var::ArrayOfGriddedField2::value () inline noexcept
Get value ref as Group::ArrayOfGriddedField2. Works when isnull() is false
Definition at line 1469 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfGriddedField2 & var) friend
Output to stream of internal variable
Definition at line 1490 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfGriddedField2::p private
Definition at line 1453 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfGriddedField2* ARTS::Var::ArrayOfGriddedField2::v private
Definition at line 1454 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfGriddedField2().
The documentation for this class was generated from the following file:
autoarts.h