ARTS: GriddedField1 Class Reference
GriddedField1 Class Reference final
#include <gridded_fields.h>
Public Member Functions
GriddedField1 ()
Construct an empty GriddedField1.
GriddedField1 (const String &s)
Construct an empty GriddedField1 with the given name.
bool checksize () const final
Consistency check.
void checksize_strict () const final
Strict consistency check.
void resize (const GriddedField1 &gf)
Make this GriddedField1 the same size as the given one.
void resize (Index n)
Resize the data vector.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
const Vector & get_numeric_grid (Index i) const
Get a numeric grid.
Vector & get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Vector data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField1 &gf)
String metaErrorData (const GriddedField1 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 225 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField1() [1/2]
GriddedField1::GriddedField1 () inline
Construct an empty GriddedField1.
Definition at line 228 of file gridded_fields.h.
GriddedField1() [2/2]
GriddedField1::GriddedField1 (const String & s) inline
Construct an empty GriddedField1 with the given name.
Parameters
[in] s Name.
Definition at line 231 of file gridded_fields.h.
Member Function Documentation
checksize()
bool GriddedField1::checksize () const inline final virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 233 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and ConstVectorView::nelem().
Referenced by checksize_strict(), and main().
checksize_strict()
void GriddedField1::checksize_strict () const inline final virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 238 of file gridded_fields.h.
References ARTS_USER_ERROR_IF, and checksize().
Referenced by xml_read_from_stream().
resize() [1/2]
void GriddedField1::resize (const GriddedField1 & gf) inline
Make this GriddedField1 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 244 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Vector::resize().
Referenced by sensor_responseGenericAMSU(), and sensor_responseSimpleAMSU().
resize() [2/2]
void GriddedField1::resize (Index n) inline
Resize the data vector.
See also
Vector::resize
Definition at line 248 of file gridded_fields.h.
References data, and Vector::resize().
Friends And Related Function Documentation
metaErrorData
String metaErrorData (const GriddedField1 & gf) friend
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField1 & gf) friend
Member Data Documentation
data
Vector GriddedField1::data
Definition at line 254 of file gridded_fields.h.
Referenced by checksize(), get_grid_nameGriddedField1(), get_nameGriddedField1(), main(), mixer_matrix(), operator<<(), resize(), sensor_responseGenericAMSU(), sensor_responseSimpleAMSU(), xml_read_from_stream(), and xml_write_to_stream().
The documentation for this class was generated from the following file:
gridded_fields.h