ARTS: ARTS::Var::ArrayOfArrayOfString Class Reference
ARTS::Var::ArrayOfArrayOfString Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfString () noexcept
ArrayOfArrayOfString (std::size_t i, void *x) noexcept
ArrayOfArrayOfString (const Group::ArrayOfArrayOfString &val) noexcept
~ArrayOfArrayOfString () noexcept
Group::ArrayOfArrayOfString & value () noexcept
const Group::ArrayOfArrayOfString & value () const noexcept
ArrayOfArrayOfString & operator= (const Group::ArrayOfArrayOfString &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfString * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfString &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1076 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfString() [1/3]
ARTS::Var::ArrayOfArrayOfString::ArrayOfArrayOfString () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1081 of file autoarts.h.
ArrayOfArrayOfString() [2/3]
ARTS::Var::ArrayOfArrayOfString::ArrayOfArrayOfString (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1084 of file autoarts.h.
ArrayOfArrayOfString() [3/3]
ARTS::Var::ArrayOfArrayOfString::ArrayOfArrayOfString (const Group::ArrayOfArrayOfString & val) inline noexcept
Construct from Group::ArrayOfArrayOfString. Leaves islast() true and isnull() false
Definition at line 1087 of file autoarts.h.
~ArrayOfArrayOfString()
ARTS::Var::ArrayOfArrayOfString::~ArrayOfArrayOfString () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1090 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfString::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1108 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfString().
isnull()
bool ARTS::Var::ArrayOfArrayOfString::isnull () const inline noexcept
Return true if there is no data
Definition at line 1105 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfString().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfString::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1111 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfString& ARTS::Var::ArrayOfArrayOfString::operator= (const Group::ArrayOfArrayOfString & t) inline noexcept
Set value from Group::ArrayOfArrayOfString. Works when isnull() is false
Definition at line 1099 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfString::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1102 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfString& ARTS::Var::ArrayOfArrayOfString::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfString. Works when isnull() is false
Definition at line 1096 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfString& ARTS::Var::ArrayOfArrayOfString::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfString. Works when isnull() is false
Definition at line 1093 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfString & var) friend
Output to stream of internal variable
Definition at line 1114 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfString::p private
Definition at line 1077 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfString* ARTS::Var::ArrayOfArrayOfString::v private
Definition at line 1078 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfString().
The documentation for this class was generated from the following file:
autoarts.h