ARTS: ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1 Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfGriddedField1 () noexcept
WorkspaceArrayOfArrayOfGriddedField1 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfGriddedField1 () noexcept
WorkspaceArrayOfArrayOfGriddedField1 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfGriddedField1 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfGriddedField1
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 206 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::type = Group::ArrayOfArrayOfGriddedField1 private
Definition at line 207 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfGriddedField1() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::WorkspaceArrayOfArrayOfGriddedField1 () inline noexcept
Definition at line 211 of file autoarts.h.
WorkspaceArrayOfArrayOfGriddedField1() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::WorkspaceArrayOfArrayOfGriddedField1 (std::size_t i, void * x) inline noexcept
Definition at line 212 of file autoarts.h.
~WorkspaceArrayOfArrayOfGriddedField1()
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::~WorkspaceArrayOfArrayOfGriddedField1 () inline noexcept
Definition at line 213 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfGriddedField1() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::WorkspaceArrayOfArrayOfGriddedField1 (const type & val) inline noexcept
Definition at line 214 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::islast () const inline noexcept
Definition at line 220 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfGriddedField1().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::isnull () const inline noexcept
Definition at line 219 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfGriddedField1().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::name () const inline noexcept
Definition at line 221 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfGriddedField1& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::operator= (const type & t) inline noexcept
Definition at line 217 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::pos () const inline noexcept
Definition at line 218 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::value () const inline noexcept
Definition at line 216 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::value () inline noexcept
Definition at line 215 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::p private
Definition at line 208 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfGriddedField1::v private
Definition at line 209 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfGriddedField1().
The documentation for this class was generated from the following file:
autoarts.h