ARTS: ARTS::Var::Agenda Class Reference
ARTS::Var::Agenda Class Reference
#include <autoarts.h>
Public Member Functions
Agenda () noexcept
Agenda (std::size_t i, void *x) noexcept
Agenda (const Group::Agenda &val) noexcept
~Agenda () noexcept
Group::Agenda & value () noexcept
const Group::Agenda & value () const noexcept
Agenda & operator= (const Group::Agenda &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Agenda * v
Friends
std::ostream & operator<< (std::ostream &os, const Agenda &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 371 of file autoarts.h.
Constructor & Destructor Documentation
Agenda() [1/3]
ARTS::Var::Agenda::Agenda () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 376 of file autoarts.h.
Agenda() [2/3]
ARTS::Var::Agenda::Agenda (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 379 of file autoarts.h.
Agenda() [3/3]
ARTS::Var::Agenda::Agenda (const Group::Agenda & val) inline noexcept
Construct from Group::Agenda. Leaves islast() true and isnull() false
Definition at line 382 of file autoarts.h.
~Agenda()
ARTS::Var::Agenda::~Agenda () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 385 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Agenda::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 403 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Agenda().
isnull()
bool ARTS::Var::Agenda::isnull () const inline noexcept
Return true if there is no data
Definition at line 400 of file autoarts.h.
References v.
Referenced by ~Agenda().
name()
const Group::String& ARTS::Var::Agenda::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 406 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), iySurfaceRtpropAgenda(), and iySurfaceRtpropCalc().
operator=()
Agenda& ARTS::Var::Agenda::operator= (const Group::Agenda & t) inline noexcept
Set value from Group::Agenda. Works when isnull() is false
Definition at line 394 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Agenda::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 397 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Agenda& ARTS::Var::Agenda::value () const inline noexcept
Get value const-ref as Group::Agenda. Works when isnull() is false
Definition at line 391 of file autoarts.h.
References v.
value() [2/2]
Group::Agenda& ARTS::Var::Agenda::value () inline noexcept
Get value ref as Group::Agenda. Works when isnull() is false
Definition at line 388 of file autoarts.h.
References v.
Referenced by ARTS::Agenda::Define::abs_xsec_agenda(), ARTS::Method::Copy(), ARTS::Agenda::Define::dobatch_calc_agenda(), ARTS::Agenda::Define::doit_conv_test_agenda(), ARTS::Agenda::Define::doit_mono_agenda(), ARTS::Agenda::Define::doit_rte_agenda(), ARTS::Agenda::Define::doit_scat_field_agenda(), ARTS::Agenda::Define::forloop_agenda(), ARTS::Agenda::Define::g0_agenda(), ARTS::Agenda::Define::geo_pos_agenda(), ARTS::Method::Ignore(), ARTS::Agenda::Define::inversion_iterate_agenda(), ARTS::Agenda::Define::iy_cloudbox_agenda(), ARTS::Agenda::Define::iy_independent_beam_approx_agenda(), ARTS::Agenda::Define::iy_loop_freqs_agenda(), ARTS::Agenda::Define::iy_main_agenda(), ARTS::Agenda::Define::iy_radar_agenda(), ARTS::Agenda::Define::iy_space_agenda(), ARTS::Agenda::Define::iy_surface_agenda(), ARTS::Agenda::Define::iy_transmitter_agenda(), ARTS::Agenda::Define::jacobian_agenda(), ARTS::Agenda::Define::main_agenda(), ARTS::Agenda::Define::met_profile_calc_agenda(), operator=(), ARTS::Agenda::Define::pha_mat_spt_agenda(), ARTS::Agenda::Define::ppath_agenda(), ARTS::Agenda::Define::ppath_step_agenda(), ARTS::Agenda::Define::propmat_clearsky_agenda(), ARTS::Agenda::Define::refr_index_air_agenda(), ARTS::Agenda::Define::sensor_response_agenda(), ARTS::Agenda::Define::spt_calc_agenda(), ARTS::Agenda::Define::surface_rtprop_agenda(), ARTS::Agenda::Define::surface_rtprop_sub_agenda(), ARTS::Agenda::Define::test_agenda(), ARTS::Method::Touch(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Agenda::Define::water_p_eq_agenda(), and ARTS::Agenda::Define::ybatch_calc_agenda().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Agenda & var) friend
Output to stream of internal variable
Definition at line 409 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Agenda::p private
Definition at line 372 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Agenda* ARTS::Var::Agenda::v private
Definition at line 373 of file autoarts.h.
Referenced by isnull(), value(), and ~Agenda().
The documentation for this class was generated from the following file:
autoarts.h