ARTS: ARTS::Var::WorkspaceGriddedField4 Class Reference
ARTS::Var::WorkspaceGriddedField4 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField4 () noexcept
WorkspaceGriddedField4 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField4 () noexcept
WorkspaceGriddedField4 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField4 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField4
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1142 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField4::type = Group::GriddedField4 private
Definition at line 1143 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField4() [1/3]
ARTS::Var::WorkspaceGriddedField4::WorkspaceGriddedField4 () inline noexcept
Definition at line 1147 of file autoarts.h.
WorkspaceGriddedField4() [2/3]
ARTS::Var::WorkspaceGriddedField4::WorkspaceGriddedField4 (std::size_t i, void * x) inline noexcept
Definition at line 1148 of file autoarts.h.
~WorkspaceGriddedField4()
ARTS::Var::WorkspaceGriddedField4::~WorkspaceGriddedField4 () inline noexcept
Definition at line 1149 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField4() [3/3]
ARTS::Var::WorkspaceGriddedField4::WorkspaceGriddedField4 (const type & val) inline noexcept
Definition at line 1150 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField4::islast () const inline noexcept
Definition at line 1156 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_scalar_reflectivityFromGriddedField4(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField4().
isnull()
bool ARTS::Var::WorkspaceGriddedField4::isnull () const inline noexcept
Definition at line 1155 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField4().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField4::name () const inline noexcept
Definition at line 1157 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField4& ARTS::Var::WorkspaceGriddedField4::operator= (const type & t) inline noexcept
Definition at line 1153 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField4::pos () const inline noexcept
Definition at line 1154 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_scalar_reflectivityFromGriddedField4(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField4::value () const inline noexcept
Definition at line 1152 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField4::value () inline noexcept
Definition at line 1151 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), operator=(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField4::p private
Definition at line 1144 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField4::v private
Definition at line 1145 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField4().
The documentation for this class was generated from the following file:
autoarts.h