ARTS: ARTS::Var::WorkspaceVector Class Reference
ARTS::Var::WorkspaceVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceVector () noexcept
WorkspaceVector (std::size_t i, void *x) noexcept
~WorkspaceVector () noexcept
WorkspaceVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Vector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1664 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceVector::type = Group::Vector private
Definition at line 1665 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceVector() [1/3]
ARTS::Var::WorkspaceVector::WorkspaceVector () inline noexcept
Definition at line 1669 of file autoarts.h.
WorkspaceVector() [2/3]
ARTS::Var::WorkspaceVector::WorkspaceVector (std::size_t i, void * x) inline noexcept
Definition at line 1670 of file autoarts.h.
~WorkspaceVector()
ARTS::Var::WorkspaceVector::~WorkspaceVector () inline noexcept
Definition at line 1671 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceVector() [3/3]
ARTS::Var::WorkspaceVector::WorkspaceVector (const type & val) inline noexcept
Definition at line 1672 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceVector::islast () const inline noexcept
Definition at line 1678 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::AddZaAa(), ARTS::AgendaMethod::cloudbox_field_monoSetConst(), ARTS::AgendaMethod::cloudbox_fieldSetConst(), ARTS::AgendaMethod::complex_refr_indexIceMatzler06(), ARTS::AgendaMethod::complex_refr_indexIceWarren84(), ARTS::AgendaMethod::complex_refr_indexWaterLiebe93(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::AgendaMethod::DiffZaAa(), ARTS::AgendaMethod::EnergyLevelMapSet(), ARTS::Method::EnergyLevelMapSet(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::AgendaMethod::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::AgendaMethod::FrequencyFromWavelength(), ARTS::Method::FrequencyFromWavelength(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddScatSpecies(), ARTS::AgendaMethod::jacobianAddSpecialSpecies(), ARTS::AgendaMethod::jacobianAddSurfaceQuantity(), ARTS::AgendaMethod::jacobianFromTwoY(), ARTS::AgendaMethod::jacobianSetAffineTransformation(), ARTS::AgendaMethod::Matrix1ColFromVector(), ARTS::AgendaMethod::Matrix1RowFromVector(), ARTS::AgendaMethod::Matrix2ColFromVectors(), ARTS::AgendaMethod::Matrix2RowFromVectors(), ARTS::AgendaMethod::Matrix3ColFromVectors(), ARTS::AgendaMethod::Matrix3RowFromVectors(), ARTS::AgendaMethod::MatrixCBR(), ARTS::AgendaMethod::MatrixMatrixMultiply(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::AgendaMethod::MatrixUnitIntensity(), ARTS::AgendaMethod::MatrixVectorMultiply(), ARTS::Method::MatrixVectorMultiply(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::NumericFromVector(), ARTS::AgendaMethod::p_gridRefine(), ARTS::AgendaMethod::PFromZSimple(), ARTS::Method::PFromZSimple(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::retrievalAddScatSpecies(), ARTS::AgendaMethod::retrievalAddSpecialSpecies(), ARTS::AgendaMethod::retrievalAddSurfaceQuantity(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::TangentPointExtract(), ARTS::Method::TangentPointExtract(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::Method::telsemAtlasLookup(), ARTS::AgendaMethod::TestTessem(), ARTS::Method::TestTessem(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), ARTS::AgendaMethod::transmittanceFromIy_aux(), ARTS::Method::transmittanceFromIy_aux(), ARTS::AgendaMethod::VectorAddScalar(), ARTS::Method::VectorAddScalar(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::Method::VectorExtractFromMatrix(), ARTS::AgendaMethod::VectorFlip(), ARTS::Method::VectorFlip(), ARTS::AgendaMethod::VectorInsertGridPoints(), ARTS::Method::VectorInsertGridPoints(), ARTS::AgendaMethod::VectorLinSpace(), ARTS::Method::VectorLinSpace(), ARTS::AgendaMethod::VectorLogSpace(), ARTS::Method::VectorLogSpace(), ARTS::AgendaMethod::VectorMatrixMultiply(), ARTS::Method::VectorMatrixMultiply(), ARTS::AgendaMethod::VectorNLinSpace(), ARTS::Method::VectorNLinSpace(), ARTS::AgendaMethod::VectorNLogSpace(), ARTS::Method::VectorNLogSpace(), ARTS::AgendaMethod::VectorScale(), ARTS::Method::VectorScale(), ARTS::AgendaMethod::VectorSet(), ARTS::Method::VectorSet(), ARTS::AgendaMethod::VectorSetConstant(), ARTS::Method::VectorSetConstant(), ARTS::AgendaMethod::VectorVectorMultiply(), ARTS::Method::VectorVectorMultiply(), ARTS::AgendaMethod::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZa1D(), ARTS::AgendaMethod::VectorZtanToZaRefr1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::AgendaMethod::vmr_fieldSetAllConstant(), ARTS::AgendaMethod::ZFromPSimple(), ARTS::Method::ZFromPSimple(), and ~WorkspaceVector().
isnull()
bool ARTS::Var::WorkspaceVector::isnull () const inline noexcept
Definition at line 1677 of file autoarts.h.
References v.
Referenced by ~WorkspaceVector().
name()
const Group::String& ARTS::Var::WorkspaceVector::name () const inline noexcept
Definition at line 1679 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), main(), Print(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceVector& ARTS::Var::WorkspaceVector::operator= (const type & t) inline noexcept
Definition at line 1675 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceVector::pos () const inline noexcept
Definition at line 1676 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::AddZaAa(), ARTS::AgendaMethod::cloudbox_field_monoSetConst(), ARTS::AgendaMethod::cloudbox_fieldSetConst(), ARTS::AgendaMethod::complex_refr_indexIceMatzler06(), ARTS::AgendaMethod::complex_refr_indexIceWarren84(), ARTS::AgendaMethod::complex_refr_indexWaterLiebe93(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::covmat_sxExtractSqrtDiagonal(), ARTS::AgendaMethod::covmatDiagonal(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::DiagonalMatrix(), ARTS::AgendaMethod::DiffZaAa(), ARTS::AgendaMethod::EnergyLevelMapSet(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::ExtractFromMetaSingleScatSpecies(), ARTS::AgendaMethod::FrequencyFromCGSAngularWavenumber(), ARTS::AgendaMethod::FrequencyFromCGSKayserWavenumber(), ARTS::AgendaMethod::FrequencyFromWavelength(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddScatSpecies(), ARTS::AgendaMethod::jacobianAddSpecialSpecies(), ARTS::AgendaMethod::jacobianAddSurfaceQuantity(), ARTS::AgendaMethod::jacobianFromTwoY(), ARTS::AgendaMethod::jacobianSetAffineTransformation(), main(), ARTS::AgendaMethod::Matrix1ColFromVector(), ARTS::AgendaMethod::Matrix1RowFromVector(), ARTS::AgendaMethod::Matrix2ColFromVectors(), ARTS::AgendaMethod::Matrix2RowFromVectors(), ARTS::AgendaMethod::Matrix3ColFromVectors(), ARTS::AgendaMethod::Matrix3RowFromVectors(), ARTS::AgendaMethod::MatrixCBR(), ARTS::AgendaMethod::MatrixMatrixMultiply(), ARTS::AgendaMethod::MatrixPlanck(), ARTS::AgendaMethod::MatrixUnitIntensity(), ARTS::AgendaMethod::MatrixVectorMultiply(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::NumericFromVector(), ARTS::AgendaMethod::p_gridRefine(), ARTS::AgendaMethod::PFromZSimple(), Print(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::retrievalAddScatSpecies(), ARTS::AgendaMethod::retrievalAddSpecialSpecies(), ARTS::AgendaMethod::retrievalAddSurfaceQuantity(), ARTS::AgendaMethod::Select(), ARTS::AgendaMethod::TangentPointExtract(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::TestTessem(), ARTS::AgendaMethod::Touch(), ARTS::AgendaMethod::transmittanceFromIy_aux(), ARTS::AgendaMethod::VectorAddScalar(), ARTS::AgendaMethod::VectorExtractFromMatrix(), ARTS::AgendaMethod::VectorFlip(), ARTS::AgendaMethod::VectorInsertGridPoints(), ARTS::AgendaMethod::VectorLinSpace(), ARTS::AgendaMethod::VectorLogSpace(), ARTS::AgendaMethod::VectorMatrixMultiply(), ARTS::AgendaMethod::VectorNLinSpace(), ARTS::AgendaMethod::VectorNLogSpace(), ARTS::AgendaMethod::VectorScale(), ARTS::AgendaMethod::VectorSet(), ARTS::AgendaMethod::VectorSetConstant(), ARTS::AgendaMethod::VectorVectorMultiply(), ARTS::AgendaMethod::VectorZtanToZa1D(), ARTS::AgendaMethod::VectorZtanToZaRefr1D(), ARTS::AgendaMethod::vmr_fieldSetAllConstant(), and ARTS::AgendaMethod::ZFromPSimple().
value() [1/2]
const type& ARTS::Var::WorkspaceVector::value () const inline noexcept
Definition at line 1674 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceVector::value () inline noexcept
Definition at line 1673 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::AddZaAa(), ARTS::Method::cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_fieldSetConst(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), ARTS::Method::complex_refr_indexWaterLiebe93(), ARTS::Method::Copy(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmatDiagonal(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::DiffZaAa(), ARTS::Method::EnergyLevelMapSet(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::Ignore(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexSetToLast(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::Matrix1ColFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::nelemGet(), ARTS::Method::NumericFromVector(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::PFromZSimple(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::Select(), ARTS::Method::TangentPointExtract(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::TestTessem(), ARTS::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorScale(), ARTS::AgendaMethod::VectorSet(), ARTS::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), ARTS::Method::vmr_fieldSetAllConstant(), and ARTS::Method::ZFromPSimple().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceVector::p private
Definition at line 1666 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceVector::v private
Definition at line 1667 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceVector().
The documentation for this class was generated from the following file:
autoarts.h