ARTS: ARTS::Var::WorkspaceTensor4 Class Reference
ARTS::Var::WorkspaceTensor4 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTensor4 () noexcept
WorkspaceTensor4 (std::size_t i, void *x) noexcept
~WorkspaceTensor4 () noexcept
WorkspaceTensor4 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTensor4 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Tensor4
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1520 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTensor4::type = Group::Tensor4 private
Definition at line 1521 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTensor4() [1/3]
ARTS::Var::WorkspaceTensor4::WorkspaceTensor4 () inline noexcept
Definition at line 1525 of file autoarts.h.
WorkspaceTensor4() [2/3]
ARTS::Var::WorkspaceTensor4::WorkspaceTensor4 (std::size_t i, void * x) inline noexcept
Definition at line 1526 of file autoarts.h.
~WorkspaceTensor4()
ARTS::Var::WorkspaceTensor4::~WorkspaceTensor4 () inline noexcept
Definition at line 1527 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTensor4() [3/3]
ARTS::Var::WorkspaceTensor4::WorkspaceTensor4 (const type & val) inline noexcept
Definition at line 1528 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTensor4::islast () const inline noexcept
Definition at line 1534 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::particle_fieldCleanup(), ARTS::Method::particle_fieldCleanup(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Tensor4AddScalar(), ARTS::Method::Tensor4AddScalar(), ARTS::AgendaMethod::Tensor4Scale(), ARTS::Method::Tensor4Scale(), ARTS::AgendaMethod::Tensor4SetConstant(), ARTS::Method::Tensor4SetConstant(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTensor4().
isnull()
bool ARTS::Var::WorkspaceTensor4::isnull () const inline noexcept
Definition at line 1533 of file autoarts.h.
References v.
Referenced by ~WorkspaceTensor4().
name()
const Group::String& ARTS::Var::WorkspaceTensor4::name () const inline noexcept
Definition at line 1535 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceTensor4& ARTS::Var::WorkspaceTensor4::operator= (const type & t) inline noexcept
Definition at line 1531 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTensor4::pos () const inline noexcept
Definition at line 1532 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::particle_fieldCleanup(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Tensor4AddScalar(), ARTS::AgendaMethod::Tensor4Scale(), ARTS::AgendaMethod::Tensor4SetConstant(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTensor4::value () const inline noexcept
Definition at line 1530 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTensor4::value () inline noexcept
Definition at line 1529 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), operator=(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Touch(), and ARTS::Method::VectorZtanToZaRefr1D().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTensor4::p private
Definition at line 1522 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTensor4::v private
Definition at line 1523 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTensor4().
The documentation for this class was generated from the following file:
autoarts.h