ARTS: ARTS::Var::ArrayOfArrayOfTensor6 Class Reference
ARTS::Var::ArrayOfArrayOfTensor6 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfTensor6 () noexcept
ArrayOfArrayOfTensor6 (std::size_t i, void *x) noexcept
ArrayOfArrayOfTensor6 (const Group::ArrayOfArrayOfTensor6 &val) noexcept
~ArrayOfArrayOfTensor6 () noexcept
Group::ArrayOfArrayOfTensor6 & value () noexcept
const Group::ArrayOfArrayOfTensor6 & value () const noexcept
ArrayOfArrayOfTensor6 & operator= (const Group::ArrayOfArrayOfTensor6 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfTensor6 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfTensor6 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1170 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfTensor6() [1/3]
ARTS::Var::ArrayOfArrayOfTensor6::ArrayOfArrayOfTensor6 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1175 of file autoarts.h.
ArrayOfArrayOfTensor6() [2/3]
ARTS::Var::ArrayOfArrayOfTensor6::ArrayOfArrayOfTensor6 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1178 of file autoarts.h.
ArrayOfArrayOfTensor6() [3/3]
ARTS::Var::ArrayOfArrayOfTensor6::ArrayOfArrayOfTensor6 (const Group::ArrayOfArrayOfTensor6 & val) inline noexcept
Construct from Group::ArrayOfArrayOfTensor6. Leaves islast() true and isnull() false
Definition at line 1181 of file autoarts.h.
~ArrayOfArrayOfTensor6()
ARTS::Var::ArrayOfArrayOfTensor6::~ArrayOfArrayOfTensor6 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1184 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfTensor6::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1202 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfTensor6().
isnull()
bool ARTS::Var::ArrayOfArrayOfTensor6::isnull () const inline noexcept
Return true if there is no data
Definition at line 1199 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfTensor6().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfTensor6::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1205 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfTensor6& ARTS::Var::ArrayOfArrayOfTensor6::operator= (const Group::ArrayOfArrayOfTensor6 & t) inline noexcept
Set value from Group::ArrayOfArrayOfTensor6. Works when isnull() is false
Definition at line 1193 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfTensor6::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1196 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfTensor6& ARTS::Var::ArrayOfArrayOfTensor6::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfTensor6. Works when isnull() is false
Definition at line 1190 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfTensor6& ARTS::Var::ArrayOfArrayOfTensor6::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfTensor6. Works when isnull() is false
Definition at line 1187 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfTensor6 & var) friend
Output to stream of internal variable
Definition at line 1208 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfTensor6::p private
Definition at line 1171 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfTensor6* ARTS::Var::ArrayOfArrayOfTensor6::v private
Definition at line 1172 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfTensor6().
The documentation for this class was generated from the following file:
autoarts.h