ARTS: ARTS::Var::WorkspaceTensor5 Class Reference
ARTS::Var::WorkspaceTensor5 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTensor5 () noexcept
WorkspaceTensor5 (std::size_t i, void *x) noexcept
~WorkspaceTensor5 () noexcept
WorkspaceTensor5 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTensor5 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Tensor5
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1538 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTensor5::type = Group::Tensor5 private
Definition at line 1539 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTensor5() [1/3]
ARTS::Var::WorkspaceTensor5::WorkspaceTensor5 () inline noexcept
Definition at line 1543 of file autoarts.h.
WorkspaceTensor5() [2/3]
ARTS::Var::WorkspaceTensor5::WorkspaceTensor5 (std::size_t i, void * x) inline noexcept
Definition at line 1544 of file autoarts.h.
~WorkspaceTensor5()
ARTS::Var::WorkspaceTensor5::~WorkspaceTensor5 () inline noexcept
Definition at line 1545 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTensor5() [3/3]
ARTS::Var::WorkspaceTensor5::WorkspaceTensor5 (const type & val) inline noexcept
Definition at line 1546 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTensor5::islast () const inline noexcept
Definition at line 1552 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::Tensor5Scale(), ARTS::Method::Tensor5Scale(), ARTS::AgendaMethod::Tensor5SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTensor5().
isnull()
bool ARTS::Var::WorkspaceTensor5::isnull () const inline noexcept
Definition at line 1551 of file autoarts.h.
References v.
Referenced by ~WorkspaceTensor5().
name()
const Group::String& ARTS::Var::WorkspaceTensor5::name () const inline noexcept
Definition at line 1553 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceTensor5& ARTS::Var::WorkspaceTensor5::operator= (const type & t) inline noexcept
Definition at line 1549 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTensor5::pos () const inline noexcept
Definition at line 1550 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor5Scale(), ARTS::AgendaMethod::Tensor5SetConstant(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTensor5::value () const inline noexcept
Definition at line 1548 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTensor5::value () inline noexcept
Definition at line 1547 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), operator=(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTensor5::p private
Definition at line 1540 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTensor5::v private
Definition at line 1541 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTensor5().
The documentation for this class was generated from the following file:
autoarts.h