ARTS: ARTS::Var::ArrayOfArrayOfGriddedField2 Class Reference
ARTS::Var::ArrayOfArrayOfGriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfGriddedField2 () noexcept
ArrayOfArrayOfGriddedField2 (std::size_t i, void *x) noexcept
ArrayOfArrayOfGriddedField2 (const Group::ArrayOfArrayOfGriddedField2 &val) noexcept
~ArrayOfArrayOfGriddedField2 () noexcept
Group::ArrayOfArrayOfGriddedField2 & value () noexcept
const Group::ArrayOfArrayOfGriddedField2 & value () const noexcept
ArrayOfArrayOfGriddedField2 & operator= (const Group::ArrayOfArrayOfGriddedField2 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfGriddedField2 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfGriddedField2 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 613 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfGriddedField2() [1/3]
ARTS::Var::ArrayOfArrayOfGriddedField2::ArrayOfArrayOfGriddedField2 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 618 of file autoarts.h.
ArrayOfArrayOfGriddedField2() [2/3]
ARTS::Var::ArrayOfArrayOfGriddedField2::ArrayOfArrayOfGriddedField2 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 621 of file autoarts.h.
ArrayOfArrayOfGriddedField2() [3/3]
ARTS::Var::ArrayOfArrayOfGriddedField2::ArrayOfArrayOfGriddedField2 (const Group::ArrayOfArrayOfGriddedField2 & val) inline noexcept
Construct from Group::ArrayOfArrayOfGriddedField2. Leaves islast() true and isnull() false
Definition at line 624 of file autoarts.h.
~ArrayOfArrayOfGriddedField2()
ARTS::Var::ArrayOfArrayOfGriddedField2::~ArrayOfArrayOfGriddedField2 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 627 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfGriddedField2::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 645 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfGriddedField2().
isnull()
bool ARTS::Var::ArrayOfArrayOfGriddedField2::isnull () const inline noexcept
Return true if there is no data
Definition at line 642 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfGriddedField2().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfGriddedField2::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 648 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfGriddedField2& ARTS::Var::ArrayOfArrayOfGriddedField2::operator= (const Group::ArrayOfArrayOfGriddedField2 & t) inline noexcept
Set value from Group::ArrayOfArrayOfGriddedField2. Works when isnull() is false
Definition at line 636 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField2::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 639 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfGriddedField2& ARTS::Var::ArrayOfArrayOfGriddedField2::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfGriddedField2. Works when isnull() is false
Definition at line 633 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfGriddedField2& ARTS::Var::ArrayOfArrayOfGriddedField2::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfGriddedField2. Works when isnull() is false
Definition at line 630 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfGriddedField2 & var) friend
Output to stream of internal variable
Definition at line 651 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField2::p private
Definition at line 614 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfGriddedField2* ARTS::Var::ArrayOfArrayOfGriddedField2::v private
Definition at line 615 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfGriddedField2().
The documentation for this class was generated from the following file:
autoarts.h