ARTS: ARTS::Var::WorkspaceScatteringMetaData Class Reference
ARTS::Var::WorkspaceScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceScatteringMetaData () noexcept
WorkspaceScatteringMetaData (std::size_t i, void *x) noexcept
~WorkspaceScatteringMetaData () noexcept
WorkspaceScatteringMetaData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceScatteringMetaData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ScatteringMetaData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1376 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceScatteringMetaData::type = Group::ScatteringMetaData private
Definition at line 1377 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceScatteringMetaData() [1/3]
ARTS::Var::WorkspaceScatteringMetaData::WorkspaceScatteringMetaData () inline noexcept
Definition at line 1381 of file autoarts.h.
WorkspaceScatteringMetaData() [2/3]
ARTS::Var::WorkspaceScatteringMetaData::WorkspaceScatteringMetaData (std::size_t i, void * x) inline noexcept
Definition at line 1382 of file autoarts.h.
~WorkspaceScatteringMetaData()
ARTS::Var::WorkspaceScatteringMetaData::~WorkspaceScatteringMetaData () inline noexcept
Definition at line 1383 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceScatteringMetaData() [3/3]
ARTS::Var::WorkspaceScatteringMetaData::WorkspaceScatteringMetaData (const type & val) inline noexcept
Definition at line 1384 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceScatteringMetaData::islast () const inline noexcept
Definition at line 1390 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceScatteringMetaData().
isnull()
bool ARTS::Var::WorkspaceScatteringMetaData::isnull () const inline noexcept
Definition at line 1389 of file autoarts.h.
References v.
Referenced by ~WorkspaceScatteringMetaData().
name()
const Group::String& ARTS::Var::WorkspaceScatteringMetaData::name () const inline noexcept
Definition at line 1391 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceScatteringMetaData& ARTS::Var::WorkspaceScatteringMetaData::operator= (const type & t) inline noexcept
Definition at line 1387 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceScatteringMetaData::pos () const inline noexcept
Definition at line 1388 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceScatteringMetaData::value () const inline noexcept
Definition at line 1386 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceScatteringMetaData::value () inline noexcept
Definition at line 1385 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceScatteringMetaData::p private
Definition at line 1378 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceScatteringMetaData::v private
Definition at line 1379 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h