ARTS: ARTS::Var::WorkspaceArrayOfArrayOfVector Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfVector () noexcept
WorkspaceArrayOfArrayOfVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfVector () noexcept
WorkspaceArrayOfArrayOfVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 494 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfVector::type = Group::ArrayOfArrayOfVector private
Definition at line 495 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfVector() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfVector::WorkspaceArrayOfArrayOfVector () inline noexcept
Definition at line 499 of file autoarts.h.
WorkspaceArrayOfArrayOfVector() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfVector::WorkspaceArrayOfArrayOfVector (std::size_t i, void * x) inline noexcept
Definition at line 500 of file autoarts.h.
~WorkspaceArrayOfArrayOfVector()
ARTS::Var::WorkspaceArrayOfArrayOfVector::~WorkspaceArrayOfArrayOfVector () inline noexcept
Definition at line 501 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfVector() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfVector::WorkspaceArrayOfArrayOfVector (const type & val) inline noexcept
Definition at line 502 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfVector::islast () const inline noexcept
Definition at line 508 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfVector::isnull () const inline noexcept
Definition at line 507 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfVector::name () const inline noexcept
Definition at line 509 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfVector& ARTS::Var::WorkspaceArrayOfArrayOfVector::operator= (const type & t) inline noexcept
Definition at line 505 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfVector::pos () const inline noexcept
Definition at line 506 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfVector::value () const inline noexcept
Definition at line 504 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfVector::value () inline noexcept
Definition at line 503 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfVector::p private
Definition at line 496 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfVector::v private
Definition at line 497 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfVector().
The documentation for this class was generated from the following file:
autoarts.h