ARTS: ARTS::Var::WorkspaceTelsemAtlas Class Reference
ARTS::Var::WorkspaceTelsemAtlas Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTelsemAtlas () noexcept
WorkspaceTelsemAtlas (std::size_t i, void *x) noexcept
~WorkspaceTelsemAtlas () noexcept
WorkspaceTelsemAtlas (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTelsemAtlas & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::TelsemAtlas
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1484 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTelsemAtlas::type = Group::TelsemAtlas private
Definition at line 1485 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTelsemAtlas() [1/3]
ARTS::Var::WorkspaceTelsemAtlas::WorkspaceTelsemAtlas () inline noexcept
Definition at line 1489 of file autoarts.h.
WorkspaceTelsemAtlas() [2/3]
ARTS::Var::WorkspaceTelsemAtlas::WorkspaceTelsemAtlas (std::size_t i, void * x) inline noexcept
Definition at line 1490 of file autoarts.h.
~WorkspaceTelsemAtlas()
ARTS::Var::WorkspaceTelsemAtlas::~WorkspaceTelsemAtlas () inline noexcept
Definition at line 1491 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTelsemAtlas() [3/3]
ARTS::Var::WorkspaceTelsemAtlas::WorkspaceTelsemAtlas (const type & val) inline noexcept
Definition at line 1492 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTelsemAtlas::islast () const inline noexcept
Definition at line 1498 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::telsemSurfaceTypeLandSea(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTelsemAtlas().
isnull()
bool ARTS::Var::WorkspaceTelsemAtlas::isnull () const inline noexcept
Definition at line 1497 of file autoarts.h.
References v.
Referenced by ~WorkspaceTelsemAtlas().
name()
const Group::String& ARTS::Var::WorkspaceTelsemAtlas::name () const inline noexcept
Definition at line 1499 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTelsemAtlas& ARTS::Var::WorkspaceTelsemAtlas::operator= (const type & t) inline noexcept
Definition at line 1495 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTelsemAtlas::pos () const inline noexcept
Definition at line 1496 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::telsemSurfaceTypeLandSea(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTelsemAtlas::value () const inline noexcept
Definition at line 1494 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTelsemAtlas::value () inline noexcept
Definition at line 1493 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::telsemSurfaceTypeLandSea(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTelsemAtlas::p private
Definition at line 1486 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTelsemAtlas::v private
Definition at line 1487 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTelsemAtlas().
The documentation for this class was generated from the following file:
autoarts.h