ARTS: ARTS::Var::StokesVector Class Reference
ARTS::Var::StokesVector Class Reference
#include <autoarts.h>
Public Member Functions
StokesVector () noexcept
StokesVector (std::size_t i, void *x) noexcept
StokesVector (const Group::StokesVector &val) noexcept
~StokesVector () noexcept
Group::StokesVector & value () noexcept
const Group::StokesVector & value () const noexcept
StokesVector & operator= (const Group::StokesVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::StokesVector * v
Friends
std::ostream & operator<< (std::ostream &os, const StokesVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3892 of file autoarts.h.
Constructor & Destructor Documentation
StokesVector() [1/3]
ARTS::Var::StokesVector::StokesVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3897 of file autoarts.h.
StokesVector() [2/3]
ARTS::Var::StokesVector::StokesVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3900 of file autoarts.h.
StokesVector() [3/3]
ARTS::Var::StokesVector::StokesVector (const Group::StokesVector & val) inline noexcept
Construct from Group::StokesVector. Leaves islast() true and isnull() false
Definition at line 3903 of file autoarts.h.
~StokesVector()
ARTS::Var::StokesVector::~StokesVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3906 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::StokesVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3924 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~StokesVector().
isnull()
bool ARTS::Var::StokesVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 3921 of file autoarts.h.
References v.
Referenced by ~StokesVector().
name()
const Group::String& ARTS::Var::StokesVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3927 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
StokesVector& ARTS::Var::StokesVector::operator= (const Group::StokesVector & t) inline noexcept
Set value from Group::StokesVector. Works when isnull() is false
Definition at line 3915 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::StokesVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3918 of file autoarts.h.
References p.
value() [1/2]
const Group::StokesVector& ARTS::Var::StokesVector::value () const inline noexcept
Get value const-ref as Group::StokesVector. Works when isnull() is false
Definition at line 3912 of file autoarts.h.
References v.
value() [2/2]
Group::StokesVector& ARTS::Var::StokesVector::value () inline noexcept
Get value ref as Group::StokesVector. Works when isnull() is false
Definition at line 3909 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const StokesVector & var) friend
Output to stream of internal variable
Definition at line 3930 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::StokesVector::p private
Definition at line 3893 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::StokesVector* ARTS::Var::StokesVector::v private
Definition at line 3894 of file autoarts.h.
Referenced by isnull(), value(), and ~StokesVector().
The documentation for this class was generated from the following file:
autoarts.h