ARTS: ARTS::Var::WorkspaceTimer Class Reference
ARTS::Var::WorkspaceTimer Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTimer () noexcept
WorkspaceTimer (std::size_t i, void *x) noexcept
~WorkspaceTimer () noexcept
WorkspaceTimer (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTimer & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Timer
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1628 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTimer::type = Group::Timer private
Definition at line 1629 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTimer() [1/3]
ARTS::Var::WorkspaceTimer::WorkspaceTimer () inline noexcept
Definition at line 1633 of file autoarts.h.
WorkspaceTimer() [2/3]
ARTS::Var::WorkspaceTimer::WorkspaceTimer (std::size_t i, void * x) inline noexcept
Definition at line 1634 of file autoarts.h.
~WorkspaceTimer()
ARTS::Var::WorkspaceTimer::~WorkspaceTimer () inline noexcept
Definition at line 1635 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTimer() [3/3]
ARTS::Var::WorkspaceTimer::WorkspaceTimer (const type & val) inline noexcept
Definition at line 1636 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTimer::islast () const inline noexcept
Definition at line 1642 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTimer().
isnull()
bool ARTS::Var::WorkspaceTimer::isnull () const inline noexcept
Definition at line 1641 of file autoarts.h.
References v.
Referenced by ~WorkspaceTimer().
name()
const Group::String& ARTS::Var::WorkspaceTimer::name () const inline noexcept
Definition at line 1643 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTimer& ARTS::Var::WorkspaceTimer::operator= (const type & t) inline noexcept
Definition at line 1639 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTimer::pos () const inline noexcept
Definition at line 1640 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTimer::value () const inline noexcept
Definition at line 1638 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTimer::value () inline noexcept
Definition at line 1637 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTimer::p private
Definition at line 1630 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTimer::v private
Definition at line 1631 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTimer().
The documentation for this class was generated from the following file:
autoarts.h