ARTS: ARTS::Var::WorkspaceGriddedField6 Class Reference
ARTS::Var::WorkspaceGriddedField6 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField6 () noexcept
WorkspaceGriddedField6 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField6 () noexcept
WorkspaceGriddedField6 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField6 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField6
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1178 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField6::type = Group::GriddedField6 private
Definition at line 1179 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField6() [1/3]
ARTS::Var::WorkspaceGriddedField6::WorkspaceGriddedField6 () inline noexcept
Definition at line 1183 of file autoarts.h.
WorkspaceGriddedField6() [2/3]
ARTS::Var::WorkspaceGriddedField6::WorkspaceGriddedField6 (std::size_t i, void * x) inline noexcept
Definition at line 1184 of file autoarts.h.
~WorkspaceGriddedField6()
ARTS::Var::WorkspaceGriddedField6::~WorkspaceGriddedField6 () inline noexcept
Definition at line 1185 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField6() [3/3]
ARTS::Var::WorkspaceGriddedField6::WorkspaceGriddedField6 (const type & val) inline noexcept
Definition at line 1186 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField6::islast () const inline noexcept
Definition at line 1192 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_reflectivityFromGriddedField6(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField6().
isnull()
bool ARTS::Var::WorkspaceGriddedField6::isnull () const inline noexcept
Definition at line 1191 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField6().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField6::name () const inline noexcept
Definition at line 1193 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField6& ARTS::Var::WorkspaceGriddedField6::operator= (const type & t) inline noexcept
Definition at line 1189 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField6::pos () const inline noexcept
Definition at line 1190 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::surface_reflectivityFromGriddedField6(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField6::value () const inline noexcept
Definition at line 1188 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField6::value () inline noexcept
Definition at line 1187 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), operator=(), ARTS::Method::surface_reflectivityFromGriddedField6(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField6::p private
Definition at line 1180 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField6::v private
Definition at line 1181 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField6().
The documentation for this class was generated from the following file:
autoarts.h