ARTS: QuantumIdentifier Class Reference
QuantumIdentifier Class Reference
Class to identify and match lines by their quantum numbers.
#include <quantum.h>
Public Types
enum QType : Index { TRANSITION , ENERGY_LEVEL , ALL , NONE }
Ways to identify quantum numbers.
Public Member Functions
constexpr QuantumIdentifier () noexcept
Initialize with no matches.
constexpr QuantumIdentifier (const QuantumIdentifier::QType &qt, const Index species, const Index iso) noexcept
Initialize with no quantum numbers defined but known species and matching type.
constexpr QuantumIdentifier (const Index spec, const Index isot, const QuantumNumbers &upper, const QuantumNumbers &lower) noexcept
Initialize with transition identifier type.
QuantumIdentifier (const Index spec, const Index isot, const std::vector< QuantumNumberType > &keys, const std::vector< Rational > &upper, const std::vector< Rational > &lower)
Initialize with transition identifier type.
constexpr QuantumIdentifier (const Index spec, const Index isot, const QuantumNumbers &qnr) noexcept
Initialize with energy level identifier type.
QuantumIdentifier (String x)
Construct a new Quantum Identifier object from text.
constexpr void Species (Index sp)
Set the Species.
constexpr void Isotopologue (Index iso)
Set the Isotopologue.
constexpr void SetTransition (const QuantumNumbers &upper, const QuantumNumbers &lower)
Set to transition type identifier.
constexpr void SetEnergyLevel (const QuantumNumbers &q)
Set to energy level identifier.
constexpr void SetAll ()
Set to All identifier.
constexpr void SetNone ()
Set to NONE identifier.
constexpr void SetTransition ()
Set key to transition type.
void SetFromString (String str)
Set from a String object.
void SetFromStringForCO2Band (String upper, String lower, String iso)
Set CO2 transition from String objects.
constexpr QType Type () const
constexpr void Type (QType x)
Set Type.
constexpr std::string_view TypeStr () const noexcept
String SpeciesName () const
Return the Species by name.
constexpr Index Species () const
Return the Species by index.
Numeric SpeciesMass () const
Return the Species mass.
constexpr Index & Species ()
Return the Species by index reference.
constexpr Index Isotopologue () const
Return the Isotopologue by index.
constexpr Index & Isotopologue ()
Return the Isotopologue by index reference.
constexpr const std::array< QuantumNumbers, 2 > & QuantumMatch () const
Return the quantum numbers array const reference.
constexpr std::array< QuantumNumbers, 2 > & QuantumMatch ()
Return the quantum numbers array reference.
constexpr QuantumIdentifier UpperQuantumId () const noexcept
Return a quantum identifer as if it wants to match to upper energy level.
constexpr QuantumIdentifier LowerQuantumId () const noexcept
Return a quantum identifer as if it wants to match to lower energy level.
constexpr const QuantumNumbers & UpperQuantumNumbers () const noexcept
Return the upper quantum numbers by const reference.
constexpr const QuantumNumbers & LowerQuantumNumbers () const noexcept
Return the lower quantum numbers by const reference.
constexpr Rational UpperQuantumNumber (QuantumNumberType X) const noexcept
Return a upper quantum number by copy.
constexpr Rational LowerQuantumNumber (QuantumNumberType X) const noexcept
Return a lower quantum number by copy.
constexpr Rational & UpperQuantumNumber (QuantumNumberType X) noexcept
Return a upper quantum number by copy.
constexpr Rational & LowerQuantumNumber (QuantumNumberType X) noexcept
Return a lower quantum number by copy.
constexpr const QuantumNumbers & EnergyLevelQuantumNumbers () const noexcept
Return the energy level quantum numbers by const reference.
constexpr Rational EnergyLevelQuantumNumber (QuantumNumberType X) const noexcept
Return a energy level quantum number by copy.
constexpr QuantumNumbers & UpperQuantumNumbers ()
Return the upper quantum numbers by reference.
constexpr QuantumNumbers & LowerQuantumNumbers ()
Return the lower quantum numbers by reference.
constexpr QuantumNumbers & EnergyLevelQuantumNumbers ()
Return the energy level quantum numbers by reference.
constexpr bool In (const QuantumIdentifier &other) const
Return if this is in other.
constexpr bool InLower (const QuantumIdentifier &other) const
Return if this is in other's lower energy state.
constexpr bool InUpper (const QuantumIdentifier &other) const
Return if this is in other's upper energy state.
constexpr bool any_quantumnumbers () const noexcept
Check if there are any quantum numbers defined.
constexpr bool IsEnergyLevelType () const noexcept
Check if *this is a energy level type of identifier.
Static Public Member Functions
static constexpr bool validIndexForType (Index x) noexcept
Checks if input is a valid Type.
static constexpr QType string2Type (const std::string_view str) noexcept
Static Public Attributes
static constexpr Index TRANSITION_UPPER_INDEX = 0
Upper level index.
static constexpr Index TRANSITION_LOWER_INDEX = 1
Lower level index.
static constexpr Index ENERGY_LEVEL_INDEX = 0
Energy level index.
Private Attributes
QType mqtype
Index mspecies
Index miso
std::array< QuantumNumbers, 2 > mqm
Detailed Description
Class to identify and match lines by their quantum numbers.
Describes a transition, an energy level, all numbers or none as matchable. Useful to match to line energy levels and to identify lines themselves.
For transitions, the QI contains upper and lower quantum numbers. For energy levels, it only holds one set of quantum numbers which are then matched against the upper and lower qns of the lines. For all and none no quantum numbers are considered
File format: Transition: SPECIES_NAME-ISOTOPE TR UP QUANTUMNUMBERS LO QUANTUMNUMBERS Energy level: SPECIES_NAME-ISOTOPE EN QUANTUMNUMBERS All lines: SPECIES_NAME-ISOTOPE ALL No lines: SPECIES_NAME-ISOTOPE NONE
Example written out: H2O-161 TR UP J 0/1 v1 2/3 LO J 1/1 v2 1/2 H2O-161 EN J 0/1 v1 2/3 H2O-161 ALL H2O-161 NONE
Definition at line 290 of file quantum.h.
Member Enumeration Documentation
QType
enum QuantumIdentifier::QType : Index
Ways to identify quantum numbers.
Enumerator
TRANSITION
ENERGY_LEVEL
ALL
NONE
Definition at line 293 of file quantum.h.
Constructor & Destructor Documentation
QuantumIdentifier() [1/6]
constexpr QuantumIdentifier::QuantumIdentifier () inline constexpr noexcept
Initialize with no matches.
Definition at line 296 of file quantum.h.
Referenced by LowerQuantumId(), and UpperQuantumId().
QuantumIdentifier() [2/6]
constexpr QuantumIdentifier::QuantumIdentifier (const QuantumIdentifier::QType & qt, const Index species, const Index iso) inline constexpr noexcept
Initialize with no quantum numbers defined but known species and matching type.
Parameters
[in] qt Way to identify quantum numbers
[in] species Species index-mapped
[in] iso Isotopologue index-mapped
Definition at line 305 of file quantum.h.
QuantumIdentifier() [3/6]
constexpr QuantumIdentifier::QuantumIdentifier (const Index spec, const Index isot, const QuantumNumbers & upper, const QuantumNumbers & lower) inline constexpr noexcept
Initialize with transition identifier type.
Parameters
[in] species Species index-mapped
[in] iso Isotopologue index-mapped
[in] upper Upper state quantum numbers
[in] lower Lower state quantum numbers
Definition at line 317 of file quantum.h.
QuantumIdentifier() [4/6]
QuantumIdentifier::QuantumIdentifier (const Index spec, const Index isot, const std::vector< QuantumNumberType > & keys, const std::vector< Rational > & upper, const std::vector< Rational > & lower)
Initialize with transition identifier type.
Parameters
[in] species Species index-mapped
[in] iso Isotopologue index-mapped
[in] ids List of quantum number keys
[in] upper Upper state quantum numbers
[in] lower Lower state quantum numbers
Definition at line 305 of file quantum.cc.
References mqm, TRANSITION_LOWER_INDEX, and TRANSITION_UPPER_INDEX.
QuantumIdentifier() [5/6]
constexpr QuantumIdentifier::QuantumIdentifier (const Index spec, const Index isot, const QuantumNumbers & qnr) inline constexpr noexcept
Initialize with energy level identifier type.
Parameters
[in] species Species index-mapped
[in] iso Isotopologue index-mapped
[in] qnr Quantum numbers
Definition at line 346 of file quantum.h.
QuantumIdentifier() [6/6]
QuantumIdentifier::QuantumIdentifier (String x) inline explicit
Construct a new Quantum Identifier object from text.
Parameters
[in] x Text
Definition at line 358 of file quantum.h.
References SetFromString(), and x.
Member Function Documentation
any_quantumnumbers()
constexpr bool QuantumIdentifier::any_quantumnumbers () const inline constexpr noexcept
Check if there are any quantum numbers defined.
Definition at line 690 of file quantum.h.
References ALL, ENERGY_LEVEL, mqm, mqtype, NONE, and TRANSITION.
EnergyLevelQuantumNumber()
constexpr Rational QuantumIdentifier::EnergyLevelQuantumNumber (QuantumNumberType X) const inline constexpr noexcept
Return a energy level quantum number by copy.
Definition at line 531 of file quantum.h.
References ENERGY_LEVEL_INDEX, and mqm.
EnergyLevelQuantumNumbers() [1/2]
constexpr QuantumNumbers& QuantumIdentifier::EnergyLevelQuantumNumbers () inline constexpr
Return the energy level quantum numbers by reference.
Definition at line 546 of file quantum.h.
References ENERGY_LEVEL_INDEX, and mqm.
EnergyLevelQuantumNumbers() [2/2]
constexpr const QuantumNumbers& QuantumIdentifier::EnergyLevelQuantumNumbers () const inline constexpr noexcept
Return the energy level quantum numbers by const reference.
Definition at line 526 of file quantum.h.
References ENERGY_LEVEL_INDEX, and mqm.
Referenced by abs_linesKeepBands().
In()
constexpr bool QuantumIdentifier::In (const QuantumIdentifier & other) const inline constexpr
Return if this is in other.
All quantum numbers defined in *this must be the same as the quantum numbers in other for a call to In() to return true. All numbers in other must not be defined in *this.
Parameters
[in] other Another quantum identifier
Returns
true If the above description holds
false Otherwise
Definition at line 561 of file quantum.h.
References ALL, ENERGY_LEVEL_INDEX, miso, mqm, mqtype, mspecies, NONE, TRANSITION, TRANSITION_LOWER_INDEX, and TRANSITION_UPPER_INDEX.
Referenced by abs_linesRemoveBand(), abs_linesSetCutoffForMatch(), abs_linesSetLinemixingLimitForMatch(), abs_linesSetLineShapeTypeForMatch(), abs_linesSetMirroringForMatch(), abs_linesSetNormalizationForMatch(), abs_linesSetPopulationForMatch(), and abs_linesSetT0ForMatch().
InLower()
constexpr bool QuantumIdentifier::InLower (const QuantumIdentifier & other) const inline constexpr
Return if this is in other's lower energy state.
All quantum numbers defined in *this must be the same as the quantum numbers in other for a call to In() to return true. All numbers in other must not be defined in *this.
Parameters
[in] other Another quantum identifier
Returns
true If the above description holds
false Otherwise
Definition at line 620 of file quantum.h.
References ALL, ENERGY_LEVEL, ENERGY_LEVEL_INDEX, miso, mqm, mqtype, mspecies, NONE, TRANSITION, and TRANSITION_LOWER_INDEX.
InUpper()
constexpr bool QuantumIdentifier::InUpper (const QuantumIdentifier & other) const inline constexpr
Return if this is in other's upper energy state.
All quantum numbers defined in *this must be the same as the quantum numbers in other for a call to In() to return true. All numbers in other must not be defined in *this.
Parameters
[in] other Another quantum identifier
Returns
true If the above description holds
false Otherwise
Definition at line 660 of file quantum.h.
References ALL, ENERGY_LEVEL, ENERGY_LEVEL_INDEX, miso, mqm, mqtype, mspecies, NONE, TRANSITION, and TRANSITION_UPPER_INDEX.
IsEnergyLevelType()
constexpr bool QuantumIdentifier::IsEnergyLevelType () const inline constexpr noexcept
Check if *this is a energy level type of identifier.
Definition at line 708 of file quantum.h.
References ENERGY_LEVEL, and mqtype.
Isotopologue() [1/3]
constexpr Index& QuantumIdentifier::Isotopologue () inline constexpr
Return the Isotopologue by index reference.
Definition at line 477 of file quantum.h.
References miso.
Isotopologue() [2/3]
constexpr Index QuantumIdentifier::Isotopologue () const inline constexpr
Return the Isotopologue by index.
Definition at line 474 of file quantum.h.
References miso.
Referenced by SetFromString(), SpeciesMass(), and SpeciesName().
Isotopologue() [3/3]
constexpr void QuantumIdentifier::Isotopologue (Index iso) inline constexpr
Set the Isotopologue.
Parameters
[in] is Isotopologue index-mapped
Definition at line 379 of file quantum.h.
References iso(), and miso.
Referenced by abs_linesKeepBands(), SpeciesAuxData::getIsotopologueRatio(), SpeciesAuxData::getParam(), SpeciesAuxData::getParamType(), Absorption::Lines::Isotopologue(), jacobianAddAbsSpecies(), operator<<(), operator==(), species_iso_match(), and species_match().
LowerQuantumId()
constexpr QuantumIdentifier QuantumIdentifier::LowerQuantumId () const inline constexpr noexcept
Return a quantum identifer as if it wants to match to lower energy level.
Definition at line 491 of file quantum.h.
References miso, mqm, mspecies, QuantumIdentifier(), and TRANSITION_LOWER_INDEX.
LowerQuantumNumber() [1/2]
constexpr Rational QuantumIdentifier::LowerQuantumNumber (QuantumNumberType X) const inline constexpr noexcept
Return a lower quantum number by copy.
Definition at line 511 of file quantum.h.
References mqm, and TRANSITION_LOWER_INDEX.
Referenced by postprocess_group1_hitran(), postprocess_group2_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), Absorption::SingleLine::SetAutomaticZeeman(), and update_id().
LowerQuantumNumber() [2/2]
constexpr Rational& QuantumIdentifier::LowerQuantumNumber (QuantumNumberType X) inline constexpr noexcept
Return a lower quantum number by copy.
Definition at line 521 of file quantum.h.
References mqm, and TRANSITION_LOWER_INDEX.
LowerQuantumNumbers() [1/2]
constexpr QuantumNumbers& QuantumIdentifier::LowerQuantumNumbers () inline constexpr
Return the lower quantum numbers by reference.
Definition at line 541 of file quantum.h.
References mqm, and TRANSITION_LOWER_INDEX.
LowerQuantumNumbers() [2/2]
constexpr const QuantumNumbers& QuantumIdentifier::LowerQuantumNumbers () const inline constexpr noexcept
Return the lower quantum numbers by const reference.
Definition at line 501 of file quantum.h.
References mqm, and TRANSITION_LOWER_INDEX.
Referenced by abs_linesKeepBands(), QuantumParserHITRAN2004::Parse(), postprocess_group1_hitran(), postprocess_group2_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), and postprocess_group6oh_hitran().
QuantumMatch() [1/2]
constexpr std::array<QuantumNumbers, 2>& QuantumIdentifier::QuantumMatch () inline constexpr
Return the quantum numbers array reference.
Definition at line 483 of file quantum.h.
References mqm.
QuantumMatch() [2/2]
constexpr const std::array<QuantumNumbers, 2>& QuantumIdentifier::QuantumMatch () const inline constexpr
Return the quantum numbers array const reference.
Definition at line 480 of file quantum.h.
References mqm.
Referenced by operator<<(), operator==(), and SetFromString().
SetAll()
constexpr void QuantumIdentifier::SetAll () inline constexpr
Set to All identifier.
Definition at line 402 of file quantum.h.
References ALL, and mqtype.
Referenced by jacobianAddAbsSpecies().
SetEnergyLevel()
constexpr void QuantumIdentifier::SetEnergyLevel (const QuantumNumbers & q) inline constexpr
Set to energy level identifier.
Parameters
[in] q Quantum numbers
Definition at line 396 of file quantum.h.
References ENERGY_LEVEL, ENERGY_LEVEL_INDEX, mqm, mqtype, and q.
SetFromString()
void QuantumIdentifier::SetFromString (String str)
Set from a String object.
Parameters
[in] str The string to set this from
Definition at line 91 of file quantum.cc.
References ALL, ENERGY_LEVEL, is, SpeciesRecord::Isotopologue(), Isotopologue(), mqtype, SpeciesRecord::Name(), Absorption::nelem(), NONE, QuantumMatch(), Species(), global_data::species_data, ThrowIfQuantumNumberNameInvalid(), TRANSITION, TRANSITION_LOWER_INDEX, and TRANSITION_UPPER_INDEX.
Referenced by QuantumIdentifier(), SetFromStringForCO2Band(), and xml_read_from_stream().
SetFromStringForCO2Band()
void QuantumIdentifier::SetFromStringForCO2Band (String upper, String lower, String iso)
Set CO2 transition from String objects.
Parameters
[in] upper Upper state quantum numbers
[in] lower Lower state quantum numbers
[in] iso Isotopologue by string
Definition at line 191 of file quantum.cc.
References iso(), my_basic_string< charT >::nelem(), and SetFromString().
SetNone()
constexpr void QuantumIdentifier::SetNone () inline constexpr
Set to NONE identifier.
Definition at line 405 of file quantum.h.
References mqtype, and NONE.
SetTransition() [1/2]
constexpr void QuantumIdentifier::SetTransition () inline constexpr
Set key to transition type.
Definition at line 408 of file quantum.h.
References mqtype, and TRANSITION.
SetTransition() [2/2]
constexpr void QuantumIdentifier::SetTransition (const QuantumNumbers & upper, const QuantumNumbers & lower) inline constexpr
Set to transition type identifier.
Parameters
[in] upper Upper state quantum numbers
[in] lower Lower state quantum numbers
Definition at line 386 of file quantum.h.
References mqm, mqtype, TRANSITION, TRANSITION_LOWER_INDEX, and TRANSITION_UPPER_INDEX.
Referenced by abs_linesKeepBands(), QuantumParserHITRAN2004::Parse(), and Absorption::Lines::truncate_global_quantum_numbers().
Species() [1/3]
constexpr Index& QuantumIdentifier::Species () inline constexpr
Return the Species by index reference.
Definition at line 471 of file quantum.h.
References mspecies.
Species() [2/3]
constexpr Index QuantumIdentifier::Species () const inline constexpr
Return the Species by index.
Definition at line 465 of file quantum.h.
References mspecies.
Referenced by SetFromString(), SpeciesMass(), and SpeciesName().
Species() [3/3]
constexpr void QuantumIdentifier::Species (Index sp) inline constexpr
Set the Species.
Parameters
[in] sp Species index-mapped
Definition at line 373 of file quantum.h.
References mspecies.
Referenced by abs_linesKeepBands(), SpeciesAuxData::getIsotopologueRatio(), SpeciesAuxData::getParam(), SpeciesAuxData::getParamType(), jacobianAddAbsSpecies(), operator<<(), operator==(), QuantumParserHITRAN2004::Parse(), postprocess_group1_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), LineShape::LegacyPressureBroadeningData::self_listed(), Absorption::Lines::Species(), and species_match().
SpeciesMass()
Numeric QuantumIdentifier::SpeciesMass () const
Return the Species mass.
Definition at line 80 of file quantum.cc.
References SpeciesRecord::Isotopologue(), Isotopologue(), Species(), and global_data::species_data.
SpeciesName()
String QuantumIdentifier::SpeciesName () const
Return the Species by name.
Definition at line 68 of file quantum.cc.
References SpeciesRecord::Isotopologue(), Isotopologue(), SpeciesRecord::Name(), Species(), and global_data::species_data.
Referenced by operator<<().
string2Type()
static constexpr QType QuantumIdentifier::string2Type (const std::string_view str) inline static constexpr noexcept
Returns
QType if string is a Type or -1 if not
Definition at line 436 of file quantum.h.
References ALL, ENERGY_LEVEL, NONE, and TRANSITION.
Type() [1/2]
constexpr QType QuantumIdentifier::Type () const inline constexpr
Returns
constexpr QType Type of identifier
Definition at line 425 of file quantum.h.
References mqtype.
Referenced by abs_linesChangeBaseParameterForMatchingLevel(), abs_linesKeepBands(), abs_linesSetBaseParameterForMatchingLevel(), jacobianAddShapeCatalogParameter(), operator<<(), operator==(), and species_match().
Type() [2/2]
constexpr void QuantumIdentifier::Type (QType x) inline constexpr
Set Type.
Definition at line 428 of file quantum.h.
References mqtype, and x.
TypeStr()
constexpr std::string_view QuantumIdentifier::TypeStr () const inline constexpr noexcept
Returns
QType as String
Definition at line 451 of file quantum.h.
References ALL, ENERGY_LEVEL, mqtype, NONE, and TRANSITION.
UpperQuantumId()
constexpr QuantumIdentifier QuantumIdentifier::UpperQuantumId () const inline constexpr noexcept
Return a quantum identifer as if it wants to match to upper energy level.
Definition at line 486 of file quantum.h.
References miso, mqm, mspecies, QuantumIdentifier(), and TRANSITION_UPPER_INDEX.
UpperQuantumNumber() [1/2]
constexpr Rational QuantumIdentifier::UpperQuantumNumber (QuantumNumberType X) const inline constexpr noexcept
Return a upper quantum number by copy.
Definition at line 506 of file quantum.h.
References mqm, and TRANSITION_UPPER_INDEX.
Referenced by postprocess_group1_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), Absorption::SingleLine::SetAutomaticZeeman(), and update_id().
UpperQuantumNumber() [2/2]
constexpr Rational& QuantumIdentifier::UpperQuantumNumber (QuantumNumberType X) inline constexpr noexcept
Return a upper quantum number by copy.
Definition at line 516 of file quantum.h.
References mqm, and TRANSITION_UPPER_INDEX.
UpperQuantumNumbers() [1/2]
constexpr QuantumNumbers& QuantumIdentifier::UpperQuantumNumbers () inline constexpr
Return the upper quantum numbers by reference.
Definition at line 536 of file quantum.h.
References mqm, and TRANSITION_UPPER_INDEX.
UpperQuantumNumbers() [2/2]
constexpr const QuantumNumbers& QuantumIdentifier::UpperQuantumNumbers () const inline constexpr noexcept
Return the upper quantum numbers by const reference.
Definition at line 496 of file quantum.h.
References mqm, and TRANSITION_UPPER_INDEX.
Referenced by abs_linesKeepBands(), QuantumParserHITRAN2004::Parse(), postprocess_group1_hitran(), postprocess_group2_hitran(), postprocess_group5_hitran(), postprocess_group6_hitran(), and postprocess_group6oh_hitran().
validIndexForType()
static constexpr bool QuantumIdentifier::validIndexForType (Index x) inline static constexpr noexcept
Checks if input is a valid Type.
Definition at line 431 of file quantum.h.
References ALL, ENERGY_LEVEL, NONE, TRANSITION, and x.
Member Data Documentation
ENERGY_LEVEL_INDEX
constexpr Index QuantumIdentifier::ENERGY_LEVEL_INDEX = 0 static constexpr
Energy level index.
Definition at line 367 of file quantum.h.
Referenced by EnergyLevelQuantumNumber(), EnergyLevelQuantumNumbers(), In(), InLower(), InUpper(), operator<<(), operator==(), and SetEnergyLevel().
miso
Index QuantumIdentifier::miso private
Definition at line 713 of file quantum.h.
Referenced by In(), InLower(), InUpper(), Isotopologue(), LowerQuantumId(), and UpperQuantumId().
mqm
std::array<QuantumNumbers, 2> QuantumIdentifier::mqm private
Definition at line 714 of file quantum.h.
Referenced by any_quantumnumbers(), EnergyLevelQuantumNumber(), EnergyLevelQuantumNumbers(), In(), InLower(), InUpper(), LowerQuantumId(), LowerQuantumNumber(), LowerQuantumNumbers(), QuantumIdentifier(), QuantumMatch(), SetEnergyLevel(), SetTransition(), UpperQuantumId(), UpperQuantumNumber(), and UpperQuantumNumbers().
mqtype
QType QuantumIdentifier::mqtype private
Definition at line 711 of file quantum.h.
Referenced by any_quantumnumbers(), In(), InLower(), InUpper(), IsEnergyLevelType(), SetAll(), SetEnergyLevel(), SetFromString(), SetNone(), SetTransition(), Type(), and TypeStr().
mspecies
Index QuantumIdentifier::mspecies private
Definition at line 712 of file quantum.h.
Referenced by In(), InLower(), InUpper(), LowerQuantumId(), Species(), and UpperQuantumId().
TRANSITION_LOWER_INDEX
constexpr Index QuantumIdentifier::TRANSITION_LOWER_INDEX = 1 static constexpr
Lower level index.
Definition at line 364 of file quantum.h.
Referenced by In(), InLower(), LowerQuantumId(), LowerQuantumNumber(), LowerQuantumNumbers(), operator<<(), operator==(), QuantumIdentifier(), SetFromString(), and SetTransition().
TRANSITION_UPPER_INDEX
constexpr Index QuantumIdentifier::TRANSITION_UPPER_INDEX = 0 static constexpr
Upper level index.
Definition at line 361 of file quantum.h.
Referenced by In(), InUpper(), operator<<(), operator==(), QuantumIdentifier(), SetFromString(), SetTransition(), UpperQuantumId(), UpperQuantumNumber(), and UpperQuantumNumbers().
The documentation for this class was generated from the following files:
quantum.h
quantum.cc