ARTS: ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3 Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfGriddedField3 () noexcept
WorkspaceArrayOfArrayOfGriddedField3 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfGriddedField3 () noexcept
WorkspaceArrayOfArrayOfGriddedField3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfGriddedField3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfGriddedField3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 242 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::type = Group::ArrayOfArrayOfGriddedField3 private
Definition at line 243 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfGriddedField3() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::WorkspaceArrayOfArrayOfGriddedField3 () inline noexcept
Definition at line 247 of file autoarts.h.
WorkspaceArrayOfArrayOfGriddedField3() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::WorkspaceArrayOfArrayOfGriddedField3 (std::size_t i, void * x) inline noexcept
Definition at line 248 of file autoarts.h.
~WorkspaceArrayOfArrayOfGriddedField3()
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::~WorkspaceArrayOfArrayOfGriddedField3 () inline noexcept
Definition at line 249 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfGriddedField3() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::WorkspaceArrayOfArrayOfGriddedField3 (const type & val) inline noexcept
Definition at line 250 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::islast () const inline noexcept
Definition at line 256 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfGriddedField3().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::isnull () const inline noexcept
Definition at line 255 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfGriddedField3().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::name () const inline noexcept
Definition at line 257 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfGriddedField3& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::operator= (const type & t) inline noexcept
Definition at line 253 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::pos () const inline noexcept
Definition at line 254 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::value () const inline noexcept
Definition at line 252 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::value () inline noexcept
Definition at line 251 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::p private
Definition at line 244 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfGriddedField3::v private
Definition at line 245 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfGriddedField3().
The documentation for this class was generated from the following file:
autoarts.h