ARTS: ARTS::Var::WorkspaceGridPos Class Reference
ARTS::Var::WorkspaceGridPos Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGridPos () noexcept
WorkspaceGridPos (std::size_t i, void *x) noexcept
~WorkspaceGridPos () noexcept
WorkspaceGridPos (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGridPos & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GridPos
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1070 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGridPos::type = Group::GridPos private
Definition at line 1071 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGridPos() [1/3]
ARTS::Var::WorkspaceGridPos::WorkspaceGridPos () inline noexcept
Definition at line 1075 of file autoarts.h.
WorkspaceGridPos() [2/3]
ARTS::Var::WorkspaceGridPos::WorkspaceGridPos (std::size_t i, void * x) inline noexcept
Definition at line 1076 of file autoarts.h.
~WorkspaceGridPos()
ARTS::Var::WorkspaceGridPos::~WorkspaceGridPos () inline noexcept
Definition at line 1077 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGridPos() [3/3]
ARTS::Var::WorkspaceGridPos::WorkspaceGridPos (const type & val) inline noexcept
Definition at line 1078 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGridPos::islast () const inline noexcept
Definition at line 1084 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGridPos().
isnull()
bool ARTS::Var::WorkspaceGridPos::isnull () const inline noexcept
Definition at line 1083 of file autoarts.h.
References v.
Referenced by ~WorkspaceGridPos().
name()
const Group::String& ARTS::Var::WorkspaceGridPos::name () const inline noexcept
Definition at line 1085 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGridPos& ARTS::Var::WorkspaceGridPos::operator= (const type & t) inline noexcept
Definition at line 1081 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGridPos::pos () const inline noexcept
Definition at line 1082 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGridPos::value () const inline noexcept
Definition at line 1080 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGridPos::value () inline noexcept
Definition at line 1079 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGridPos::p private
Definition at line 1072 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGridPos::v private
Definition at line 1073 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGridPos().
The documentation for this class was generated from the following file:
autoarts.h