ARTS: ARTS::Var::AbsorptionLines Class Reference
ARTS::Var::AbsorptionLines Class Reference
#include <autoarts.h>
Public Member Functions
AbsorptionLines () noexcept
AbsorptionLines (std::size_t i, void *x) noexcept
AbsorptionLines (const Group::AbsorptionLines &val) noexcept
~AbsorptionLines () noexcept
Group::AbsorptionLines & value () noexcept
const Group::AbsorptionLines & value () const noexcept
AbsorptionLines & operator= (const Group::AbsorptionLines &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::AbsorptionLines * v
Friends
std::ostream & operator<< (std::ostream &os, const AbsorptionLines &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 331 of file autoarts.h.
Constructor & Destructor Documentation
AbsorptionLines() [1/3]
ARTS::Var::AbsorptionLines::AbsorptionLines () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 336 of file autoarts.h.
AbsorptionLines() [2/3]
ARTS::Var::AbsorptionLines::AbsorptionLines (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 339 of file autoarts.h.
AbsorptionLines() [3/3]
ARTS::Var::AbsorptionLines::AbsorptionLines (const Group::AbsorptionLines & val) inline noexcept
Construct from Group::AbsorptionLines. Leaves islast() true and isnull() false
Definition at line 342 of file autoarts.h.
~AbsorptionLines()
ARTS::Var::AbsorptionLines::~AbsorptionLines () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 345 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::AbsorptionLines::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 363 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~AbsorptionLines().
isnull()
bool ARTS::Var::AbsorptionLines::isnull () const inline noexcept
Return true if there is no data
Definition at line 360 of file autoarts.h.
References v.
Referenced by ~AbsorptionLines().
name()
const Group::String& ARTS::Var::AbsorptionLines::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 366 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
AbsorptionLines& ARTS::Var::AbsorptionLines::operator= (const Group::AbsorptionLines & t) inline noexcept
Set value from Group::AbsorptionLines. Works when isnull() is false
Definition at line 354 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::AbsorptionLines::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 357 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::AbsorptionLines& ARTS::Var::AbsorptionLines::value () const inline noexcept
Get value const-ref as Group::AbsorptionLines. Works when isnull() is false
Definition at line 351 of file autoarts.h.
References v.
value() [2/2]
Group::AbsorptionLines& ARTS::Var::AbsorptionLines::value () inline noexcept
Get value ref as Group::AbsorptionLines. Works when isnull() is false
Definition at line 348 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const AbsorptionLines & var) friend
Output to stream of internal variable
Definition at line 369 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::AbsorptionLines::p private
Definition at line 332 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::AbsorptionLines* ARTS::Var::AbsorptionLines::v private
Definition at line 333 of file autoarts.h.
Referenced by isnull(), value(), and ~AbsorptionLines().
The documentation for this class was generated from the following file:
autoarts.h