ARTS: ARTS::Var::WorkspaceArrayOfGriddedField3 Class Reference
ARTS::Var::WorkspaceArrayOfGriddedField3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfGriddedField3 () noexcept
WorkspaceArrayOfGriddedField3 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfGriddedField3 () noexcept
WorkspaceArrayOfGriddedField3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfGriddedField3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfGriddedField3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 566 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfGriddedField3::type = Group::ArrayOfGriddedField3 private
Definition at line 567 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfGriddedField3() [1/3]
ARTS::Var::WorkspaceArrayOfGriddedField3::WorkspaceArrayOfGriddedField3 () inline noexcept
Definition at line 571 of file autoarts.h.
WorkspaceArrayOfGriddedField3() [2/3]
ARTS::Var::WorkspaceArrayOfGriddedField3::WorkspaceArrayOfGriddedField3 (std::size_t i, void * x) inline noexcept
Definition at line 572 of file autoarts.h.
~WorkspaceArrayOfGriddedField3()
ARTS::Var::WorkspaceArrayOfGriddedField3::~WorkspaceArrayOfGriddedField3 () inline noexcept
Definition at line 573 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfGriddedField3() [3/3]
ARTS::Var::WorkspaceArrayOfGriddedField3::WorkspaceArrayOfGriddedField3 (const type & val) inline noexcept
Definition at line 574 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfGriddedField3::islast () const inline noexcept
Definition at line 580 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfGriddedField3().
isnull()
bool ARTS::Var::WorkspaceArrayOfGriddedField3::isnull () const inline noexcept
Definition at line 579 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfGriddedField3().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfGriddedField3::name () const inline noexcept
Definition at line 581 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfGriddedField3& ARTS::Var::WorkspaceArrayOfGriddedField3::operator= (const type & t) inline noexcept
Definition at line 577 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField3::pos () const inline noexcept
Definition at line 578 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfGriddedField3::value () const inline noexcept
Definition at line 576 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfGriddedField3::value () inline noexcept
Definition at line 575 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField3::p private
Definition at line 568 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfGriddedField3::v private
Definition at line 569 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfGriddedField3().
The documentation for this class was generated from the following file:
autoarts.h