ARTS: ARTS::Var::Sparse Class Reference
ARTS::Var::Sparse Class Reference
#include <autoarts.h>
Public Member Functions
Sparse () noexcept
Sparse (std::size_t i, void *x) noexcept
Sparse (const Group::Sparse &val) noexcept
~Sparse () noexcept
Group::Sparse & value () noexcept
const Group::Sparse & value () const noexcept
Sparse & operator= (const Group::Sparse &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Sparse * v
Friends
std::ostream & operator<< (std::ostream &os, const Sparse &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3798 of file autoarts.h.
Constructor & Destructor Documentation
Sparse() [1/3]
ARTS::Var::Sparse::Sparse () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3803 of file autoarts.h.
Sparse() [2/3]
ARTS::Var::Sparse::Sparse (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3806 of file autoarts.h.
Sparse() [3/3]
ARTS::Var::Sparse::Sparse (const Group::Sparse & val) inline noexcept
Construct from Group::Sparse. Leaves islast() true and isnull() false
Definition at line 3809 of file autoarts.h.
~Sparse()
ARTS::Var::Sparse::~Sparse () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3812 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Sparse::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3830 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::covmat_seSet(), ARTS::Agenda::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Agenda::Method::covmatDiagonal(), ARTS::Method::DiagonalMatrix(), ARTS::Agenda::Method::DiagonalMatrix(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::MatrixCopySparse(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::SparseSparseMultiply(), ARTS::Agenda::Method::SparseSparseMultiply(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Sparse().
isnull()
bool ARTS::Var::Sparse::isnull () const inline noexcept
Return true if there is no data
Definition at line 3827 of file autoarts.h.
References v.
Referenced by ~Sparse().
name()
const Group::String& ARTS::Var::Sparse::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3833 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Sparse& ARTS::Var::Sparse::operator= (const Group::Sparse & t) inline noexcept
Set value from Group::Sparse. Works when isnull() is false
Definition at line 3821 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Sparse::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3824 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::covmat_seSet(), ARTS::Agenda::Method::covmat_sxSet(), ARTS::Agenda::Method::covmatDiagonal(), ARTS::Agenda::Method::DiagonalMatrix(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::MatrixCopySparse(), ARTS::Agenda::Method::Select(), ARTS::Agenda::Method::SparseSparseMultiply(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Sparse& ARTS::Var::Sparse::value () const inline noexcept
Get value const-ref as Group::Sparse. Works when isnull() is false
Definition at line 3818 of file autoarts.h.
References v.
value() [2/2]
Group::Sparse& ARTS::Var::Sparse::value () inline noexcept
Get value ref as Group::Sparse. Works when isnull() is false
Definition at line 3815 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), ARTS::Method::DiagonalMatrix(), ARTS::Method::Ignore(), ARTS::Method::MatrixCopySparse(), operator=(), ARTS::Method::Select(), ARTS::Method::SparseSparseMultiply(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Sparse & var) friend
Output to stream of internal variable
Definition at line 3836 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Sparse::p private
Definition at line 3799 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Sparse* ARTS::Var::Sparse::v private
Definition at line 3800 of file autoarts.h.
Referenced by isnull(), value(), and ~Sparse().
The documentation for this class was generated from the following file:
autoarts.h