ARTS: ARTS::Var::WorkspaceGriddedField2 Class Reference
ARTS::Var::WorkspaceGriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGriddedField2 () noexcept
WorkspaceGriddedField2 (std::size_t i, void *x) noexcept
~WorkspaceGriddedField2 () noexcept
WorkspaceGriddedField2 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGriddedField2 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GriddedField2
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1106 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGriddedField2::type = Group::GriddedField2 private
Definition at line 1107 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGriddedField2() [1/3]
ARTS::Var::WorkspaceGriddedField2::WorkspaceGriddedField2 () inline noexcept
Definition at line 1111 of file autoarts.h.
WorkspaceGriddedField2() [2/3]
ARTS::Var::WorkspaceGriddedField2::WorkspaceGriddedField2 (std::size_t i, void * x) inline noexcept
Definition at line 1112 of file autoarts.h.
~WorkspaceGriddedField2()
ARTS::Var::WorkspaceGriddedField2::~WorkspaceGriddedField2 () inline noexcept
Definition at line 1113 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGriddedField2() [3/3]
ARTS::Var::WorkspaceGriddedField2::WorkspaceGriddedField2 (const type & val) inline noexcept
Definition at line 1114 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGriddedField2::islast () const inline noexcept
Definition at line 1120 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpGriddedField2ToPosition(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGriddedField2().
isnull()
bool ARTS::Var::WorkspaceGriddedField2::isnull () const inline noexcept
Definition at line 1119 of file autoarts.h.
References v.
Referenced by ~WorkspaceGriddedField2().
name()
const Group::String& ARTS::Var::WorkspaceGriddedField2::name () const inline noexcept
Definition at line 1121 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceGriddedField2& ARTS::Var::WorkspaceGriddedField2::operator= (const type & t) inline noexcept
Definition at line 1117 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGriddedField2::pos () const inline noexcept
Definition at line 1118 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::GriddedFieldGetName(), ARTS::AgendaMethod::GriddedFieldLatLonExpand(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpGriddedField2ToPosition(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGriddedField2::value () const inline noexcept
Definition at line 1116 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGriddedField2::value () inline noexcept
Definition at line 1115 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::InterpGriddedField2ToPosition(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGriddedField2::p private
Definition at line 1108 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGriddedField2::v private
Definition at line 1109 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGriddedField2().
The documentation for this class was generated from the following file:
autoarts.h