ARTS: Rational Class Reference
Rational Class Reference
Implements rational numbers to work with other ARTS types.
#include <rational.h>
Public Member Functions
constexpr Rational (const Index nom=0, const Index denom=1) noexcept
Initialization call.
Rational (const String &s)
Initialization call.
constexpr Index Nom () const noexcept
Nominator.
constexpr Index Denom () const noexcept
Denominator.
constexpr Index & Nom () noexcept
Nominator.
constexpr Index & Denom () noexcept
Denominator.
constexpr void Nom (Index x) noexcept
Nominator.
constexpr void Denom (Index x) noexcept
Denominator.
void simplify_in_place () noexcept
Simplify by reducing the values locally.
constexpr bool isUndefined () const noexcept
Is the object not defined.
constexpr bool isDefined () const noexcept
Is the object defined.
constexpr bool isIndex (int n=1) const noexcept
Is the object a n-scaled Index.
constexpr Index toIndex (int n=1) const noexcept
Converts the value to index by n-scaled division.
constexpr Numeric toNumeric () const noexcept
Converts this to a Numeric.
constexpr int toInt (int n=1) const noexcept
Converts the value to int by n-scaled division in Index form.
constexpr Rational & operator+= (const Rational &a) noexcept
Add to this.
constexpr Rational & operator+= (const Index &a) noexcept
Add to this.
constexpr Rational & operator+= (const int &a) noexcept
Add to this.
constexpr Rational & operator-= (const Rational &a) noexcept
Remove from this.
constexpr Rational & operator-= (const Index &a) noexcept
Remove from this.
constexpr Rational & operator-= (const int &a) noexcept
Remove from this.
constexpr Rational & operator/= (const Rational &a) noexcept
Divide by this.
constexpr Rational & operator/= (const Index &a) noexcept
Divide by this.
constexpr Rational & operator/= (const int &a) noexcept
Divide by this.
constexpr Rational & operator*= (const Rational &a) noexcept
Multiply by this.
constexpr Rational & operator*= (const Index &a) noexcept
Multiply by this.
constexpr Rational & operator*= (const int &a) noexcept
Multiply by this.
constexpr Rational operator++ (int) const noexcept
Add one if possible.
constexpr Rational operator-- (int) const noexcept
Remove one if possible.
constexpr Rational & operator++ () noexcept
Add one if possible.
constexpr Rational & operator-- () noexcept
Remove one if possible.
constexpr operator bool () const noexcept
Cast to bool.
constexpr operator Numeric () const noexcept
Cast to Numeric.
constexpr operator Index () const noexcept
Cast to Index.
constexpr operator int () const noexcept
Cast to int.
bifstream & read (bifstream &bif)
Binary read for Rational.
bofstream & write (bofstream &bof) const
Binary write for Rational.
constexpr Rational & fixSign () noexcept
Makes the sign of mdenom positive.
Private Attributes
Index mnom
Index mdenom
Detailed Description
Implements rational numbers to work with other ARTS types.
Definition at line 53 of file rational.h.
Constructor & Destructor Documentation
Rational() [1/2]
constexpr Rational::Rational (const Index nom = 0, const Index denom = 1) inline constexpr noexcept
Initialization call.
Parameters
[in] nom Nominator
[in] denom Denominator
Definition at line 60 of file rational.h.
References gcd(), mdenom, and mnom.
Referenced by operator++(), operator--(), and Rational().
Rational() [2/2]
Rational::Rational (const String & s) explicit
Initialization call.
Sets the rational from the string. Formats accepted are
Numeric: 1.234567890 Fraction: 12345/67890 Index: 1234567890
Note that overflow is possible and we do not care to capture it
Parameters
[in] s String of the value
Definition at line 83 of file rational.cc.
References numeric2rational(), Rational(), and RATIONAL_UNDEFINED.
Member Function Documentation
Denom() [1/3]
constexpr Index Rational::Denom () const inline constexpr noexcept
Denominator.
Definition at line 87 of file rational.h.
References mdenom.
Referenced by operator<<().
Denom() [2/3]
constexpr Index& Rational::Denom () inline constexpr noexcept
Denominator.
Definition at line 93 of file rational.h.
References mdenom.
Denom() [3/3]
constexpr void Rational::Denom (Index x) inline constexpr noexcept
Denominator.
Definition at line 99 of file rational.h.
References mdenom, and ARTS::Var::x().
fixSign()
constexpr Rational& Rational::fixSign () inline constexpr noexcept
Makes the sign of mdenom positive.
Definition at line 329 of file rational.h.
References mdenom, and mnom.
Referenced by operator<<(), and simplify_in_place().
isDefined()
constexpr bool Rational::isDefined () const inline constexpr noexcept
Is the object defined.
Returns
true If Denom() is not 0
false Otherwise
Definition at line 116 of file rational.h.
References isUndefined().
Referenced by isIndex(), operator bool(), and operator==().
isIndex()
constexpr bool Rational::isIndex (int n = 1) const inline constexpr noexcept
Is the object a n-scaled Index.
Parameters
[in] n Scale
Returns
true If n*Nom() % Denom() is 0
false Otherwise
Definition at line 124 of file rational.h.
References isDefined(), mdenom, and mnom.
isUndefined()
constexpr bool Rational::isUndefined () const inline constexpr noexcept
Is the object not defined.
Returns
true If Denom() is 0
false Otherwise
Definition at line 109 of file rational.h.
References mdenom.
Referenced by case_b_g_coefficient_o2(), Absorption::ENUMCLASS(), isDefined(), and QuantumFieldDescription::Parse().
Nom() [1/3]
constexpr Index Rational::Nom () const inline constexpr noexcept
Nominator.
Definition at line 84 of file rational.h.
References mnom.
Referenced by operator<<().
Nom() [2/3]
constexpr Index& Rational::Nom () inline constexpr noexcept
Nominator.
Definition at line 90 of file rational.h.
References mnom.
Nom() [3/3]
constexpr void Rational::Nom (Index x) inline constexpr noexcept
Nominator.
Definition at line 96 of file rational.h.
References mnom, and ARTS::Var::x().
operator bool()
constexpr Rational::operator bool () const inline explicit constexpr noexcept
Cast to bool.
Definition at line 303 of file rational.h.
References isDefined(), and mnom.
operator Index()
constexpr Rational::operator Index () const inline explicit constexpr noexcept
Cast to Index.
Definition at line 311 of file rational.h.
References toIndex().
operator int()
constexpr Rational::operator int () const inline explicit constexpr noexcept
Cast to int.
Definition at line 314 of file rational.h.
References toInt().
operator Numeric()
constexpr Rational::operator Numeric () const inline explicit constexpr noexcept
Cast to Numeric.
Definition at line 308 of file rational.h.
References toNumeric().
operator*=() [1/3]
constexpr Rational& Rational::operator*= (const Index & a) inline constexpr noexcept
Multiply by this.
Parameters
[in] a To multiply by
Returns
Rational& *this
Definition at line 265 of file rational.h.
References a, and mnom.
operator*=() [2/3]
constexpr Rational& Rational::operator*= (const int & a) inline constexpr noexcept
Multiply by this.
Parameters
[in] a To multiply by
Returns
Rational& *this
Definition at line 275 of file rational.h.
References a, and mnom.
operator*=() [3/3]
constexpr Rational& Rational::operator*= (const Rational & a) inline constexpr noexcept
Multiply by this.
Parameters
[in] a To multiply by
Returns
Rational& *this
Definition at line 254 of file rational.h.
References a, mdenom, and mnom.
operator++() [1/2]
constexpr Rational& Rational::operator++ () inline constexpr noexcept
Add one if possible.
Definition at line 291 of file rational.h.
References mdenom, and mnom.
operator++() [2/2]
constexpr Rational Rational::operator++ (int) const inline constexpr noexcept
Add one if possible.
Definition at line 281 of file rational.h.
References mdenom, mnom, and Rational().
operator+=() [1/3]
constexpr Rational& Rational::operator+= (const Index & a) inline constexpr noexcept
Add to this.
Parameters
[in] a To add
Returns
Rational& *this
Definition at line 172 of file rational.h.
References a, mdenom, and mnom.
operator+=() [2/3]
constexpr Rational& Rational::operator+= (const int & a) inline constexpr noexcept
Add to this.
Parameters
[in] a To add
Returns
Rational& *this
Definition at line 182 of file rational.h.
References a, mdenom, and mnom.
operator+=() [3/3]
constexpr Rational& Rational::operator+= (const Rational & a) inline constexpr noexcept
Add to this.
Parameters
[in] a To add
Returns
Rational& *this
Definition at line 161 of file rational.h.
References a, mdenom, and mnom.
operator--() [1/2]
constexpr Rational& Rational::operator-- () inline constexpr noexcept
Remove one if possible.
Definition at line 297 of file rational.h.
References mdenom, and mnom.
operator--() [2/2]
constexpr Rational Rational::operator-- (int) const inline constexpr noexcept
Remove one if possible.
Definition at line 286 of file rational.h.
References mdenom, mnom, and Rational().
operator-=() [1/3]
constexpr Rational& Rational::operator-= (const Index & a) inline constexpr noexcept
Remove from this.
Parameters
[in] a To remove
Returns
Rational& *this
Definition at line 203 of file rational.h.
References a, mdenom, and mnom.
operator-=() [2/3]
constexpr Rational& Rational::operator-= (const int & a) inline constexpr noexcept
Remove from this.
Parameters
[in] a To remove
Returns
Rational& *this
Definition at line 213 of file rational.h.
References a, mdenom, and mnom.
operator-=() [3/3]
constexpr Rational& Rational::operator-= (const Rational & a) inline constexpr noexcept
Remove from this.
Parameters
[in] a To remove
Returns
Rational& *this
Definition at line 192 of file rational.h.
References a, mdenom, and mnom.
operator/=() [1/3]
constexpr Rational& Rational::operator/= (const Index & a) inline constexpr noexcept
Divide by this.
Parameters
[in] a To divide by
Returns
Rational& *this
Definition at line 234 of file rational.h.
References a, and mdenom.
operator/=() [2/3]
constexpr Rational& Rational::operator/= (const int & a) inline constexpr noexcept
Divide by this.
Parameters
[in] a To divide by
Returns
Rational& *this
Definition at line 244 of file rational.h.
References a, and mdenom.
operator/=() [3/3]
constexpr Rational& Rational::operator/= (const Rational & a) inline constexpr noexcept
Divide by this.
Parameters
[in] a To divide by
Returns
Rational& *this
Definition at line 223 of file rational.h.
References a, mdenom, and mnom.
read()
bifstream& Rational::read (bifstream & bif) inline
Binary read for Rational.
Definition at line 317 of file rational.h.
References mdenom, and mnom.
simplify_in_place()
void Rational::simplify_in_place () noexcept
Simplify by reducing the values locally.
Definition at line 104 of file rational.cc.
References a, fixSign(), mdenom, mnom, and reduce_by_gcd().
toIndex()
constexpr Index Rational::toIndex (int n = 1) const inline constexpr noexcept
Converts the value to index by n-scaled division.
Throws a logic error if *this is not an Index
Parameters
[in] n Scale to *this
Returns
constexpr Index Of *this
Definition at line 135 of file rational.h.
References mdenom, and mnom.
Referenced by lm_hitran_2017::calcw(), operator Index(), postprocess_group5_hitran(), postprocess_group6_hitran(), postprocess_group6oh_hitran(), and toInt().
toInt()
constexpr int Rational::toInt (int n = 1) const inline constexpr noexcept
Converts the value to int by n-scaled division in Index form.
Throws a logic error if *this is not an Index
Parameters
[in] n Scale to *this
Returns
constexpr int Of *this
Definition at line 154 of file rational.h.
References toIndex().
Referenced by is_wigner3_ready(), is_wigner6_ready(), and operator int().
toNumeric()
constexpr Numeric Rational::toNumeric () const inline constexpr noexcept
Converts this to a Numeric.
Returns
constexpr Numeric of *this
Definition at line 143 of file rational.h.
References mdenom, and mnom.
Referenced by case_b_g_coefficient_o2(), operator Numeric(), pow(), and sqrt().
write()
bofstream& Rational::write (bofstream & bof) const inline
Binary write for Rational.
Definition at line 323 of file rational.h.
References mdenom, and mnom.
Member Data Documentation
mdenom
Index Rational::mdenom private
Definition at line 340 of file rational.h.
Referenced by Denom(), fixSign(), isIndex(), isUndefined(), operator*=(), operator++(), operator+=(), operator--(), operator-=(), operator/=(), Rational(), read(), simplify_in_place(), toIndex(), toNumeric(), and write().
mnom
Index Rational::mnom private
Definition at line 339 of file rational.h.
Referenced by fixSign(), isIndex(), Nom(), operator bool(), operator*=(), operator++(), operator+=(), operator--(), operator-=(), operator/=(), Rational(), read(), simplify_in_place(), toIndex(), toNumeric(), and write().
The documentation for this class was generated from the following files:
rational.h
rational.cc