ARTS: ParseError Class Reference
ParseError Class Reference
#include <exceptions.h>
Public Member Functions
ParseError (const String &s="", const String &f="", Index l=0, Index c=0)
virtual ~ParseError () throw ()
virtual String file () const
virtual Index line () const
virtual Index column () const
Private Attributes
String mFile
Filename associated with this part of the text.
Index mLine
Line where the error occured.
Index mColumn
Column where the error occured.
Detailed Description
Definition at line 40 of file exceptions.h.
Constructor & Destructor Documentation
ParseError()
ParseError::ParseError (const String & s = "", const String & f = "", Index l = 0, Index c = 0) inline
Definition at line 42 of file exceptions.h.
~ParseError()
virtual ParseError::~ParseError () throw () inline virtual
Definition at line 52 of file exceptions.h.
Member Function Documentation
column()
virtual Index ParseError::column () const inline virtual
Definition at line 56 of file exceptions.h.
References mColumn.
Referenced by ArtsParser::set_gin_to_default().
file()
virtual String ParseError::file () const inline virtual
Definition at line 54 of file exceptions.h.
References mFile.
Referenced by ArtsParser::set_gin_to_default().
line()
virtual Index ParseError::line () const inline virtual
Definition at line 55 of file exceptions.h.
References mLine.
Referenced by ArtsParser::set_gin_to_default().
Member Data Documentation
mColumn
Index ParseError::mColumn private
Column where the error occured.
Definition at line 64 of file exceptions.h.
Referenced by column().
mFile
String ParseError::mFile private
Filename associated with this part of the text.
Definition at line 60 of file exceptions.h.
Referenced by file().
mLine
Index ParseError::mLine private
Line where the error occured.
Definition at line 62 of file exceptions.h.
Referenced by line().
The documentation for this class was generated from the following file:
exceptions.h