ARTS: ARTS::Var::WorkspaceArrayOfArrayOfMatrix Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfMatrix () noexcept
WorkspaceArrayOfArrayOfMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfMatrix () noexcept
WorkspaceArrayOfArrayOfMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 278 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfMatrix::type = Group::ArrayOfArrayOfMatrix private
Definition at line 279 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfMatrix::WorkspaceArrayOfArrayOfMatrix () inline noexcept
Definition at line 283 of file autoarts.h.
WorkspaceArrayOfArrayOfMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfMatrix::WorkspaceArrayOfArrayOfMatrix (std::size_t i, void * x) inline noexcept
Definition at line 284 of file autoarts.h.
~WorkspaceArrayOfArrayOfMatrix()
ARTS::Var::WorkspaceArrayOfArrayOfMatrix::~WorkspaceArrayOfArrayOfMatrix () inline noexcept
Definition at line 285 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfMatrix::WorkspaceArrayOfArrayOfMatrix (const type & val) inline noexcept
Definition at line 286 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfMatrix::islast () const inline noexcept
Definition at line 292 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfMatrix::isnull () const inline noexcept
Definition at line 291 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfMatrix::name () const inline noexcept
Definition at line 293 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfMatrix& ARTS::Var::WorkspaceArrayOfArrayOfMatrix::operator= (const type & t) inline noexcept
Definition at line 289 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfMatrix::pos () const inline noexcept
Definition at line 290 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfMatrix::value () const inline noexcept
Definition at line 288 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfMatrix::value () inline noexcept
Definition at line 287 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfMatrix::p private
Definition at line 280 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfMatrix::v private
Definition at line 281 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfMatrix().
The documentation for this class was generated from the following file:
autoarts.h