ARTS: ARTS::Var::String Class Reference
ARTS::Var::String Class Reference
#include <autoarts.h>
Public Member Functions
String () noexcept
String (std::size_t i, void *x) noexcept
String (const Group::String &val) noexcept
~String () noexcept
Group::String & value () noexcept
const Group::String & value () const noexcept
String & operator= (const Group::String &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::String * v
Friends
std::ostream & operator<< (std::ostream &os, const String &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4040 of file autoarts.h.
Constructor & Destructor Documentation
String() [1/3]
ARTS::Var::String::String () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4045 of file autoarts.h.
String() [2/3]
ARTS::Var::String::String (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4048 of file autoarts.h.
String() [3/3]
ARTS::Var::String::String (const Group::String & val) inline noexcept
Construct from Group::String. Leaves islast() true and isnull() false
Definition at line 4051 of file autoarts.h.
~String()
ARTS::Var::String::~String () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4054 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::String::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4072 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_cia_dataReadFromCIA(), ARTS::Agenda::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Agenda::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Agenda::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Agenda::Method::abs_linesWriteSplitXML(), ARTS::Agenda::Method::abs_speciesDefineAllInScenario(), ARTS::Agenda::Method::ArrayOfTimeNLinSpace(), ARTS::Agenda::Method::atm_fields_compactCreateFromField(), ARTS::Agenda::Method::AtmRawRead(), ARTS::Agenda::Method::CIAInfo(), ARTS::Agenda::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Agenda::Method::diameter_volume_equFromDiameter_max(), ARTS::Agenda::Method::Error(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::GetEnvironmentVariable(), ARTS::Agenda::Method::GetEnvironmentVariable(), ARTS::Method::GriddedFieldGetName(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::iyReplaceFromAux(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameter(), ARTS::Agenda::Method::jacobianAddScatSpecies(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameter(), ARTS::Agenda::Method::jacobianAddSpecialSpecies(), ARTS::Agenda::Method::jacobianAddSurfaceQuantity(), ARTS::Agenda::Method::MagRawRead(), ARTS::Agenda::Method::MatrixExtractFromTensor3(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Agenda::Method::QuantumIdentifierSet(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::retrievalAddCatalogParameter(), ARTS::Agenda::Method::retrievalAddScatSpecies(), ARTS::Agenda::Method::retrievalAddSpecialSpecies(), ARTS::Agenda::Method::retrievalAddSurfaceQuantity(), ARTS::Agenda::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::StringSet(), ARTS::Agenda::Method::StringSet(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Agenda::Method::TessemNNReadAscii(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), ARTS::Agenda::Method::VectorExtractFromMatrix(), ARTS::Agenda::Method::vmr_fieldSetConstant(), ARTS::Agenda::Method::WindRawRead(), ARTS::Agenda::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Agenda::Method::WriteMolTau(), ARTS::Agenda::Method::ybatchMetProfiles(), ARTS::Agenda::Method::ybatchMetProfilesClear(), and ~String().
isnull()
bool ARTS::Var::String::isnull () const inline noexcept
Return true if there is no data
Definition at line 4069 of file autoarts.h.
References v.
Referenced by ~String().
name()
const Group::String& ARTS::Var::String::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4075 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
String& ARTS::Var::String::operator= (const Group::String & t) inline noexcept
Set value from Group::String. Works when isnull() is false
Definition at line 4063 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::String::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4066 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_cia_dataReadFromCIA(), ARTS::Agenda::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Agenda::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Agenda::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Agenda::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Agenda::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Agenda::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Agenda::Method::abs_linesWriteSplitXML(), ARTS::Agenda::Method::abs_speciesDefineAllInScenario(), ARTS::Agenda::Method::ArrayOfTimeNLinSpace(), ARTS::Agenda::Method::atm_fields_compactCreateFromField(), ARTS::Agenda::Method::AtmRawRead(), ARTS::Agenda::Method::CIAInfo(), ARTS::Agenda::Method::CIARecordReadFromFile(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Agenda::Method::diameter_volume_equFromDiameter_max(), ARTS::Agenda::Method::Error(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Agenda::Method::GetEnvironmentVariable(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::iyReplaceFromAux(), ARTS::Agenda::Method::jacobianAddBasicCatalogParameter(), ARTS::Agenda::Method::jacobianAddScatSpecies(), ARTS::Agenda::Method::jacobianAddShapeCatalogParameter(), ARTS::Agenda::Method::jacobianAddSpecialSpecies(), ARTS::Agenda::Method::jacobianAddSurfaceQuantity(), ARTS::Agenda::Method::MagRawRead(), ARTS::Agenda::Method::MatrixExtractFromTensor3(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Agenda::Method::QuantumIdentifierSet(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::retrievalAddCatalogParameter(), ARTS::Agenda::Method::retrievalAddScatSpecies(), ARTS::Agenda::Method::retrievalAddSpecialSpecies(), ARTS::Agenda::Method::retrievalAddSurfaceQuantity(), ARTS::Agenda::Method::ScatSpeciesPndAndScatAdd(), ARTS::Agenda::Method::StringSet(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Agenda::Method::TessemNNReadAscii(), ARTS::Agenda::Method::Touch(), ARTS::Agenda::Method::VectorExtractFromMatrix(), ARTS::Agenda::Method::vmr_fieldSetConstant(), ARTS::Agenda::Method::WindRawRead(), ARTS::Agenda::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Agenda::Method::WriteMolTau(), ARTS::Agenda::Method::ybatchMetProfiles(), and ARTS::Agenda::Method::ybatchMetProfilesClear().
value() [1/2]
const Group::String& ARTS::Var::String::value () const inline noexcept
Get value const-ref as Group::String. Works when isnull() is false
Definition at line 4060 of file autoarts.h.
References v.
value() [2/2]
Group::String& ARTS::Var::String::value () inline noexcept
Get value ref as Group::String. Works when isnull() is false
Definition at line 4057 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_cia_dataReadFromCIA(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), ARTS::Method::abs_speciesDefineAllInScenario(), ARTS::Method::ArrayOfTimeNLinSpace(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::AtmRawRead(), ARTS::Method::CIAInfo(), ARTS::Method::CIARecordReadFromFile(), ARTS::Method::Copy(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::Error(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::Ignore(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::MagRawRead(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::NumericFromVector(), operator=(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::ReadNetCDF(), ARTS::Method::retrievalAddCatalogParameter(), ARTS::Method::retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ARTS::Method::StringSet(), ARTS::Agenda::Method::StringSet(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::Touch(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::WindRawRead(), ARTS::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Method::WriteMolTau(), ARTS::Method::ybatchMetProfiles(), and ARTS::Method::ybatchMetProfilesClear().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const String & var) friend
Output to stream of internal variable
Definition at line 4078 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::String::p private
Definition at line 4041 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::String* ARTS::Var::String::v private
Definition at line 4042 of file autoarts.h.
Referenced by isnull(), value(), and ~String().
The documentation for this class was generated from the following file:
autoarts.h