ARTS: ARTS::Var::TelsemAtlas Class Reference
ARTS::Var::TelsemAtlas Class Reference
#include <autoarts.h>
Public Member Functions
TelsemAtlas () noexcept
TelsemAtlas (std::size_t i, void *x) noexcept
~TelsemAtlas () noexcept
TelsemAtlas (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
TelsemAtlas & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::TelsemAtlas
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1524 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::TelsemAtlas::type = Group::TelsemAtlas private
Definition at line 1525 of file autoarts.h.
Constructor & Destructor Documentation
TelsemAtlas() [1/3]
ARTS::Var::TelsemAtlas::TelsemAtlas () inline noexcept
Definition at line 1529 of file autoarts.h.
TelsemAtlas() [2/3]
ARTS::Var::TelsemAtlas::TelsemAtlas (std::size_t i, void * x) inline noexcept
Definition at line 1530 of file autoarts.h.
~TelsemAtlas()
ARTS::Var::TelsemAtlas::~TelsemAtlas () inline noexcept
Definition at line 1531 of file autoarts.h.
References islast(), isnull(), and v.
TelsemAtlas() [3/3]
ARTS::Var::TelsemAtlas::TelsemAtlas (const type & val) inline noexcept
Definition at line 1532 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::TelsemAtlas::islast () const inline noexcept
Definition at line 1538 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::telsemSurfaceTypeLandSea(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~TelsemAtlas().
isnull()
bool ARTS::Var::TelsemAtlas::isnull () const inline noexcept
Definition at line 1537 of file autoarts.h.
References v.
Referenced by ~TelsemAtlas().
name()
const Group::String& ARTS::Var::TelsemAtlas::name () const inline noexcept
Definition at line 1539 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
TelsemAtlas& ARTS::Var::TelsemAtlas::operator= (const type & t) inline noexcept
Definition at line 1535 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::TelsemAtlas::pos () const inline noexcept
Definition at line 1536 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::telsemAtlasLookup(), ARTS::AgendaMethod::telsemSurfaceTypeLandSea(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::TelsemAtlas::value () const inline noexcept
Definition at line 1534 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::TelsemAtlas::value () inline noexcept
Definition at line 1533 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), operator=(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::telsemSurfaceTypeLandSea(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::TelsemAtlas::p private
Definition at line 1526 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::TelsemAtlas::v private
Definition at line 1527 of file autoarts.h.
Referenced by isnull(), value(), and ~TelsemAtlas().
The documentation for this class was generated from the following file:
autoarts.h