ARTS: ARTS::Var::ArrayOfTransmissionMatrix Class Reference
ARTS::Var::ArrayOfTransmissionMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTransmissionMatrix () noexcept
ArrayOfTransmissionMatrix (std::size_t i, void *x) noexcept
ArrayOfTransmissionMatrix (const Group::ArrayOfTransmissionMatrix &val) noexcept
~ArrayOfTransmissionMatrix () noexcept
Group::ArrayOfTransmissionMatrix & value () noexcept
const Group::ArrayOfTransmissionMatrix & value () const noexcept
ArrayOfTransmissionMatrix & operator= (const Group::ArrayOfTransmissionMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfTransmissionMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfTransmissionMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2531 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTransmissionMatrix() [1/3]
ARTS::Var::ArrayOfTransmissionMatrix::ArrayOfTransmissionMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2536 of file autoarts.h.
ArrayOfTransmissionMatrix() [2/3]
ARTS::Var::ArrayOfTransmissionMatrix::ArrayOfTransmissionMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2539 of file autoarts.h.
ArrayOfTransmissionMatrix() [3/3]
ARTS::Var::ArrayOfTransmissionMatrix::ArrayOfTransmissionMatrix (const Group::ArrayOfTransmissionMatrix & val) inline noexcept
Construct from Group::ArrayOfTransmissionMatrix. Leaves islast() true and isnull() false
Definition at line 2542 of file autoarts.h.
~ArrayOfTransmissionMatrix()
ARTS::Var::ArrayOfTransmissionMatrix::~ArrayOfTransmissionMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2545 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTransmissionMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2563 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfTransmissionMatrix().
isnull()
bool ARTS::Var::ArrayOfTransmissionMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 2560 of file autoarts.h.
References v.
Referenced by ~ArrayOfTransmissionMatrix().
name()
const Group::String& ARTS::Var::ArrayOfTransmissionMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2566 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfTransmissionMatrix& ARTS::Var::ArrayOfTransmissionMatrix::operator= (const Group::ArrayOfTransmissionMatrix & t) inline noexcept
Set value from Group::ArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 2554 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTransmissionMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2557 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfTransmissionMatrix& ARTS::Var::ArrayOfTransmissionMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 2551 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfTransmissionMatrix& ARTS::Var::ArrayOfTransmissionMatrix::value () inline noexcept
Get value ref as Group::ArrayOfTransmissionMatrix. Works when isnull() is false
Definition at line 2548 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfTransmissionMatrix & var) friend
Output to stream of internal variable
Definition at line 2569 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTransmissionMatrix::p private
Definition at line 2532 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfTransmissionMatrix* ARTS::Var::ArrayOfTransmissionMatrix::v private
Definition at line 2533 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTransmissionMatrix().
The documentation for this class was generated from the following file:
autoarts.h