ARTS: Tensor6View Class Reference
Tensor6View Class Reference
The Tensor6View class.
#include <matpackVI.h>
Public Member Functions
constexpr Tensor6View (const Tensor6View &)=default
Tensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c)
MatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c)
MatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c)
MatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c)
MatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c)
MatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c)
VectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c)
VectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c)
VectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c)
VectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c)
Numeric & operator() (Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & get (Index v, Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
Iterator6D begin ()
Return iterator to first sub-tensor.
Iterator6D end ()
Return iterator behind last sub-tensor.
Tensor6View & operator= (const ConstTensor6View &v)
Assignment operator.
Tensor6View & operator= (const Tensor6View &v)
Assignment from Tensor6View to Tensor6View.
Tensor6View & operator= (const Tensor6 &v)
Assignment from a Tensor6.
Tensor6View & operator= (Numeric x)
Assigning a scalar to a Tensor6View will set all elements to this value.
Tensor6View & operator*= (Numeric x)
Multiplication by scalar.
Tensor6View & operator/= (Numeric x)
Division by scalar.
Tensor6View & operator+= (Numeric x)
Addition of scalar.
Tensor6View & operator-= (Numeric x)
Subtraction of scalar.
Tensor6View & operator*= (const ConstTensor6View &x)
Element-vise multiplication by another Tensor6.
Tensor6View & operator/= (const ConstTensor6View &x)
Element-vise division by another Tensor6.
Tensor6View & operator+= (const ConstTensor6View &x)
Element-vise addition of another Tensor6.
Tensor6View & operator-= (const ConstTensor6View &x)
Element-vise subtraction of another Tensor6.
virtual ~Tensor6View ()=default
Tensor6View (const Tensor5View &a)
Special constructor to make a Tensor6 view of a Tensor5.
ConstIterator6D begin () const
Return const iterator to first sub-tensor.
ConstIterator6D end () const
Return const iterator behind last sub-tensor.
Numeric get (Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Public Member Functions inherited from ConstTensor6View
constexpr ConstTensor6View (const ConstTensor6View &)=default
constexpr ConstTensor6View (ConstTensor6View &&)=default
ConstTensor6View & operator= (const ConstTensor6View &)=default
ConstTensor6View & operator= (ConstTensor6View &&)=default
bool empty () const
Check if variable is empty.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator6D begin () const
Return const iterator to first sub-tensor.
ConstIterator6D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor6View ()=default
ConstTensor6View (const ConstTensor5View &a)
Special constructor to make a Tensor6 view of a Tensor5.
Protected Member Functions
Tensor6View ()=default
Tensor6View (Numeric *data, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor6View (Numeric *data, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor6View
ConstTensor6View ()=default
ConstTensor6View (Numeric *data, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor6View (Numeric *data, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Friends
class Iterator7D
class Tensor7View
Additional Inherited Members
Protected Attributes inherited from ConstTensor6View
Range mvr {0, 0, 1}
The vitrine range of mdata that is actually used.
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor6View class.
This contains the main implementation of a Tensor6. It defines the concepts of Tensor6View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor6View from a subrange of a Tensor6View.
The class Tensor6 is just a special case of a Tensor6View which also allocates storage.
Definition at line 621 of file matpackVI.h.
Constructor & Destructor Documentation
Tensor6View() [1/5]
constexpr Tensor6View::Tensor6View (const Tensor6View &) constexpr default
~Tensor6View()
virtual Tensor6View::~Tensor6View () virtual default
Tensor6View() [2/5]
Tensor6View::Tensor6View (const Tensor5View & a)
Special constructor to make a Tensor6 view of a Tensor5.
Definition at line 1935 of file matpackVI.cc.
Tensor6View() [3/5]
Tensor6View::Tensor6View () protected default
Tensor6View() [4/5]
Tensor6View::Tensor6View (Numeric * data, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor6 to initialize its own Tensor6View part. The row range rr must have a stride to account for the length of one row.
Definition at line 1952 of file matpackVI.cc.
Tensor6View() [5/5]
Tensor6View::Tensor6View (Numeric * data, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pv Previous range.
ps Previous range.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
nv New Range.
ns New Range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 1985 of file matpackVI.cc.
Member Function Documentation
begin() [1/2]
Iterator6D Tensor6View::begin ()
Return iterator to first sub-tensor.
Definition at line 1752 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and Tensor6::Tensor6().
begin() [2/2]
ConstIterator6D ConstTensor6View::begin
Return const iterator to first sub-tensor.
Definition at line 556 of file matpackVI.cc.
end() [1/2]
Iterator6D Tensor6View::end ()
Return iterator behind last sub-tensor.
Definition at line 1758 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
end() [2/2]
ConstIterator6D ConstTensor6View::end
Return const iterator behind last sub-tensor.
Definition at line 557 of file matpackVI.cc.
get() [1/2]
Numeric& Tensor6View::get (Index v, Index s, Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 1015 of file matpackVI.h.
get() [2/2]
Numeric ConstTensor6View::get inline
Get element implementation without assertions.
Definition at line 550 of file matpackVI.h.
get_c_array() [1/2]
Numeric * Tensor6View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 1711 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
get_c_array() [2/2]
const Numeric * Tensor6View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 1734 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
Referenced by get_variable_value(), and Reduce().
operator()() [1/64]
Tensor6View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 981 of file matpackVI.cc.
operator()() [2/64]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 992 of file matpackVI.cc.
operator()() [3/64]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1003 of file matpackVI.cc.
operator()() [4/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1059 of file matpackVI.cc.
operator()() [5/64]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1014 of file matpackVI.cc.
operator()() [6/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1072 of file matpackVI.cc.
operator()() [7/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1124 of file matpackVI.cc.
operator()() [8/64]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 1255 of file matpackVI.cc.
operator()() [9/64]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1025 of file matpackVI.cc.
operator()() [10/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1085 of file matpackVI.cc.
operator()() [11/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1137 of file matpackVI.cc.
operator()() [12/64]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 1265 of file matpackVI.cc.
operator()() [13/64]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 1176 of file matpackVI.cc.
operator()() [14/64]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 1295 of file matpackVI.cc.
operator()() [15/64]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 1355 of file matpackVI.cc.
operator()() [16/64]
MatrixView Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 1610 of file matpackVI.cc.
operator()() [17/64]
Tensor5View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1036 of file matpackVI.cc.
operator()() [18/64]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1098 of file matpackVI.cc.
operator()() [19/64]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1150 of file matpackVI.cc.
operator()() [20/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1275 of file matpackVI.cc.
operator()() [21/64]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1189 of file matpackVI.cc.
operator()() [22/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1305 of file matpackVI.cc.
operator()() [23/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1365 of file matpackVI.cc.
operator()() [24/64]
MatrixView Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 1599 of file matpackVI.cc.
operator()() [25/64]
Tensor4View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1215 of file matpackVI.cc.
operator()() [26/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1325 of file matpackVI.cc.
operator()() [27/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1385 of file matpackVI.cc.
operator()() [28/64]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 1577 of file matpackVI.cc.
operator()() [29/64]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 1415 of file matpackVI.cc.
operator()() [30/64]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 1544 of file matpackVI.cc.
operator()() [31/64]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 1500 of file matpackVI.cc.
operator()() [32/64]
VectorView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 1692 of file matpackVI.cc.
operator()() [33/64]
Tensor5View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1047 of file matpackVI.cc.
operator()() [34/64]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1111 of file matpackVI.cc.
operator()() [35/64]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1163 of file matpackVI.cc.
operator()() [36/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1285 of file matpackVI.cc.
operator()() [37/64]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1202 of file matpackVI.cc.
operator()() [38/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1315 of file matpackVI.cc.
operator()() [39/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1375 of file matpackVI.cc.
operator()() [40/64]
MatrixView Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 1588 of file matpackVI.cc.
operator()() [41/64]
Tensor4View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1228 of file matpackVI.cc.
operator()() [42/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1335 of file matpackVI.cc.
operator()() [43/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1395 of file matpackVI.cc.
operator()() [44/64]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 1566 of file matpackVI.cc.
operator()() [45/64]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 1425 of file matpackVI.cc.
operator()() [46/64]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 1533 of file matpackVI.cc.
operator()() [47/64]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 1489 of file matpackVI.cc.
operator()() [48/64]
VectorView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 1678 of file matpackVI.cc.
operator()() [49/64]
Tensor4View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1241 of file matpackVI.cc.
operator()() [50/64]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1345 of file matpackVI.cc.
operator()() [51/64]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1405 of file matpackVI.cc.
operator()() [52/64]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1555 of file matpackVI.cc.
operator()() [53/64]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1435 of file matpackVI.cc.
operator()() [54/64]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1522 of file matpackVI.cc.
operator()() [55/64]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1478 of file matpackVI.cc.
operator()() [56/64]
VectorView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 1664 of file matpackVI.cc.
operator()() [57/64]
Tensor3View Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1445 of file matpackVI.cc.
operator()() [58/64]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1511 of file matpackVI.cc.
operator()() [59/64]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1467 of file matpackVI.cc.
operator()() [60/64]
VectorView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 1650 of file matpackVI.cc.
operator()() [61/64]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 1456 of file matpackVI.cc.
operator()() [62/64]
VectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 1636 of file matpackVI.cc.
operator()() [63/64]
VectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 1622 of file matpackVI.cc.
operator()() [64/64]
Numeric& Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, Index c) inline
Definition at line 1004 of file matpackVI.h.
operator*=() [1/2]
Tensor6View & Tensor6View::operator*= (const ConstTensor6View & x)
Element-vise multiplication by another Tensor6.
Definition at line 1867 of file matpackVI.cc.
References begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and ARTS::Var::x().
operator*=() [2/2]
Tensor6View & Tensor6View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 1831 of file matpackVI.cc.
References begin(), end(), and ARTS::Var::x().
operator+=() [1/2]
Tensor6View & Tensor6View::operator+= (const ConstTensor6View & x)
Element-vise addition of another Tensor6.
Definition at line 1901 of file matpackVI.cc.
References begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and ARTS::Var::x().
operator+=() [2/2]
Tensor6View & Tensor6View::operator+= (Numeric x)
Addition of scalar.
Definition at line 1849 of file matpackVI.cc.
References begin(), end(), and ARTS::Var::x().
operator-=() [1/2]
Tensor6View & Tensor6View::operator-= (const ConstTensor6View & x)
Element-vise subtraction of another Tensor6.
Definition at line 1918 of file matpackVI.cc.
References begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and ARTS::Var::x().
operator-=() [2/2]
Tensor6View & Tensor6View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 1858 of file matpackVI.cc.
References begin(), end(), and ARTS::Var::x().
operator/=() [1/2]
Tensor6View & Tensor6View::operator/= (const ConstTensor6View & x)
Element-vise division by another Tensor6.
Definition at line 1884 of file matpackVI.cc.
References begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and ARTS::Var::x().
operator/=() [2/2]
Tensor6View & Tensor6View::operator/= (Numeric x)
Division by scalar.
Definition at line 1840 of file matpackVI.cc.
References begin(), end(), and ARTS::Var::x().
operator=() [1/4]
Tensor6View & Tensor6View::operator= (const ConstTensor6View & m)
Assignment operator.
This copies the data from another Tensor6View to this Tensor6View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor6View by setting its range.
Definition at line 1773 of file matpackVI.cc.
References begin(), ConstTensor6View::begin(), copy(), ConstTensor6View::end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [2/4]
Tensor6View & Tensor6View::operator= (const Tensor6 & m)
Assignment from a Tensor6.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 1807 of file matpackVI.cc.
References begin(), copy(), end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [3/4]
Tensor6View & Tensor6View::operator= (const Tensor6View & m)
Assignment from Tensor6View to Tensor6View.
This is a tricky one. The problem is that since Tensor6View is derived from ConstTensor6View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 1791 of file matpackVI.cc.
References begin(), copy(), end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [4/4]
Tensor6View & Tensor6View::operator= (Numeric x)
Assigning a scalar to a Tensor6View will set all elements to this value.
Definition at line 1822 of file matpackVI.cc.
References begin(), copy(), end(), and ARTS::Var::x().
Friends And Related Function Documentation
Iterator7D
friend class Iterator7D friend
Definition at line 1049 of file matpackVI.h.
Tensor7View
friend class Tensor7View friend
Definition at line 1050 of file matpackVI.h.
The documentation for this class was generated from the following files:
matpackVI.h
matpackVI.cc