ARTS: ARTS::Var::WorkspaceArrayOfRadiationVector Class Reference
ARTS::Var::WorkspaceArrayOfRadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfRadiationVector () noexcept
WorkspaceArrayOfRadiationVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfRadiationVector () noexcept
WorkspaceArrayOfRadiationVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfRadiationVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfRadiationVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 692 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfRadiationVector::type = Group::ArrayOfRadiationVector private
Definition at line 693 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfRadiationVector() [1/3]
ARTS::Var::WorkspaceArrayOfRadiationVector::WorkspaceArrayOfRadiationVector () inline noexcept
Definition at line 697 of file autoarts.h.
WorkspaceArrayOfRadiationVector() [2/3]
ARTS::Var::WorkspaceArrayOfRadiationVector::WorkspaceArrayOfRadiationVector (std::size_t i, void * x) inline noexcept
Definition at line 698 of file autoarts.h.
~WorkspaceArrayOfRadiationVector()
ARTS::Var::WorkspaceArrayOfRadiationVector::~WorkspaceArrayOfRadiationVector () inline noexcept
Definition at line 699 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfRadiationVector() [3/3]
ARTS::Var::WorkspaceArrayOfRadiationVector::WorkspaceArrayOfRadiationVector (const type & val) inline noexcept
Definition at line 700 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfRadiationVector::islast () const inline noexcept
Definition at line 706 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfRadiationVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfRadiationVector::isnull () const inline noexcept
Definition at line 705 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfRadiationVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfRadiationVector::name () const inline noexcept
Definition at line 707 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfRadiationVector& ARTS::Var::WorkspaceArrayOfRadiationVector::operator= (const type & t) inline noexcept
Definition at line 703 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfRadiationVector::pos () const inline noexcept
Definition at line 704 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfRadiationVector::value () const inline noexcept
Definition at line 702 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfRadiationVector::value () inline noexcept
Definition at line 701 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfRadiationVector::p private
Definition at line 694 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfRadiationVector::v private
Definition at line 695 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfRadiationVector().
The documentation for this class was generated from the following file:
autoarts.h