ARTS: TelsemAtlas Class Reference
TelsemAtlas Class Reference
A telsem atlas.
#include <telsem.h>
Public Member Functions
TelsemAtlas ()=default
TelsemAtlas (const TelsemAtlas &)=default
TelsemAtlas (TelsemAtlas &&)=default
TelsemAtlas & operator= (const TelsemAtlas &)=default
TelsemAtlas & operator= (TelsemAtlas &&)=default
~TelsemAtlas ()=default
TelsemAtlas (String filename)
void set_month (Index m)
Index get_month () const
const Tensor3 & get_correl () const
void set_correl (const Tensor3 &t)
bool contains (Index cellnumber) const
Index get_class1 (Index cellnumber) const
Index get_class2 (Index cellnumber) const
Vector get_emis_v (Index i) const
Vector get_emis_h (Index cellnum) const
ConstVectorView operator[] (Index cellnumber) const
void read (std::istream &is)
void equare ()
void telsem_calc_correspondence ()
Index calc_cellnum (Numeric lat, Numeric lon) const
Index calc_cellnum_nearest_neighbor (Numeric lat, Numeric lon) const
std::pair< Numeric, Numeric > get_coordinates (Index cellnum) const
Numeric interp_freq2 (Numeric emiss19, Numeric emiss37, Numeric emiss85, Numeric f, Index class2) const
std::pair< Numeric, Numeric > emis_interp (Numeric theta, Numeric freq, Index class1, Index class2, const ConstVectorView &ev, const ConstVectorView &eh) const
Index & DataCount ()
Index & ChannelCount ()
String & Name ()
Index & Month ()
Numeric & Lat ()
ArrayOfIndex & Cells ()
ArrayOfIndex & FirstCells ()
Matrix & Emis ()
Matrix & Emis_err ()
Tensor3 & Correlations ()
ArrayOfIndex & Classes1 ()
ArrayOfIndex & Classes2 ()
ArrayOfIndex & Cellnumber ()
ArrayOfIndex & Correspondance ()
Numeric A0_K0 (Index i)
Numeric A0_K1 (Index i)
Numeric A0_K2 (Index i)
Numeric A0_EVEH (Index i)
Numeric A1_EVEH (Index i)
Numeric A2_EVEH (Index i)
Numeric A3_EVEH (Index i)
Numeric B0_EVEH (Index i)
Numeric B1_EVEH (Index i)
Numeric B2_EVEH (Index i)
Numeric B3_EVEH (Index i)
Numeric RAPPORT43_32 (Index i)
Numeric RAPPORT54_43 (Index i)
Private Attributes
Index ndat
Index nchan
String name
Index month
Numeric dlat
ArrayOfIndex ncells
ArrayOfIndex firstcells
Matrix emis
Matrix emis_err
Tensor3 correl
ArrayOfIndex classes1
ArrayOfIndex classes2
ArrayOfIndex cellnums
ArrayOfIndex correspondence
Static Private Attributes
static const std::array< Numeric, 30 > a0_k0
static const std::array< Numeric, 30 > a0_k1
static const std::array< Numeric, 30 > a0_k2
static const std::array< Numeric, 30 > a0_eveh
static const std::array< Numeric, 30 > a1_eveh
static const std::array< Numeric, 30 > a2_eveh
static const std::array< Numeric, 30 > a3_eveh
static const std::array< Numeric, 30 > b0_eveh
static const std::array< Numeric, 30 > b1_eveh
static const std::array< Numeric, 30 > b2_eveh
static const std::array< Numeric, 30 > b3_eveh
static const std::array< Numeric, 4 > rapport43_32
static const std::array< Numeric, 4 > rapport54_43
Friends
std::ostream & operator<< (std::ostream &os, const TelsemAtlas &ta)
void xml_write_to_stream (ostream &, const TelsemAtlas &, bofstream *, const String &, const Verbosity &)
Writes TelsemAtlas to XML output stream.
void xml_read_from_stream (istream &, TelsemAtlas &, bifstream *, const Verbosity &)
Reads TelsemAtlas from XML input stream.
Detailed Description
A telsem atlas.
Represents a Telsem2 atlas containing land surface microwave emissivities. Since the Atlas contains emissivities only for land surfaces, the data is stored in a sparse format.
The emissivities are represented on an equal area grid and numbered sequentially starting with the first latitude band at -90 degrees and moving up to 90 degrees.
The correspondance array contains the data indices for each cellnumber if it is contained in the Atlas and NAN otherwise.
Definition at line 59 of file telsem.h.
Constructor & Destructor Documentation
TelsemAtlas() [1/4]
TelsemAtlas::TelsemAtlas () default
TelsemAtlas() [2/4]
TelsemAtlas::TelsemAtlas (const TelsemAtlas &) default
TelsemAtlas() [3/4]
TelsemAtlas::TelsemAtlas (TelsemAtlas &&) default
~TelsemAtlas()
TelsemAtlas::~TelsemAtlas () default
TelsemAtlas() [4/4]
TelsemAtlas::TelsemAtlas (String filename)
Create and read atlas from file.
Parameters
filename The path of the file from which to read the atlas
Definition at line 41 of file telsem.cc.
References read().
Member Function Documentation
A0_EVEH()
Numeric TelsemAtlas::A0_EVEH (Index i) inline
Definition at line 340 of file telsem.h.
References a0_eveh.
A0_K0()
Numeric TelsemAtlas::A0_K0 (Index i) inline
Definition at line 337 of file telsem.h.
References a0_k0.
A0_K1()
Numeric TelsemAtlas::A0_K1 (Index i) inline
Definition at line 338 of file telsem.h.
References a0_k1.
A0_K2()
Numeric TelsemAtlas::A0_K2 (Index i) inline
Definition at line 339 of file telsem.h.
References a0_k2.
A1_EVEH()
Numeric TelsemAtlas::A1_EVEH (Index i) inline
Definition at line 341 of file telsem.h.
References a1_eveh.
A2_EVEH()
Numeric TelsemAtlas::A2_EVEH (Index i) inline
Definition at line 342 of file telsem.h.
References a2_eveh.
A3_EVEH()
Numeric TelsemAtlas::A3_EVEH (Index i) inline
Definition at line 343 of file telsem.h.
References a3_eveh.
B0_EVEH()
Numeric TelsemAtlas::B0_EVEH (Index i) inline
Definition at line 344 of file telsem.h.
References b0_eveh.
B1_EVEH()
Numeric TelsemAtlas::B1_EVEH (Index i) inline
Definition at line 345 of file telsem.h.
References b1_eveh.
B2_EVEH()
Numeric TelsemAtlas::B2_EVEH (Index i) inline
Definition at line 346 of file telsem.h.
References b2_eveh.
B3_EVEH()
Numeric TelsemAtlas::B3_EVEH (Index i) inline
Definition at line 347 of file telsem.h.
References b3_eveh.
calc_cellnum()
Index TelsemAtlas::calc_cellnum (Numeric lat, Numeric lon) const
Compute the cellnumber corrsponding to given coordinates.
Computes the cellnumber of the lon/lat grid that contains the given coordinates.
Note: The cell may not be contained in the atlas if it is above the sea. The result should be checked using the contains(...) member function before it is used.
Parameters
[in] lat The latitude coordinate for which to compute the containing cell.
[out] lon The longitude coordinates for which to compute the containing cell.
Definition at line 142 of file telsem.cc.
References ARTS_USER_ERROR_IF, dlat, ARTS::Var::lat(), ARTS::Var::lon(), and ncells.
Referenced by calc_cellnum_nearest_neighbor(), surfaceTelsem(), telsemAtlasLookup(), telsemStandalone(), telsemSurfaceTypeLandSea(), test_telsem_interpolate(), and test_telsem_read().
calc_cellnum_nearest_neighbor()
Index TelsemAtlas::calc_cellnum_nearest_neighbor (Numeric lat, Numeric lon) const
Compute the cellnumber of closest cell contained in atlas.
Parameters
[in] lat The latitude coordinate for which to compute the containing cell.
[out] lon The longitude coordinates for which to compute the containing cell.
Definition at line 170 of file telsem.cc.
References calc_cellnum(), contains(), cycle_lat_lon(), dlat, ARTS::Var::lat(), and ARTS::Var::lon().
Referenced by surfaceTelsem(), and telsemStandalone().
Cellnumber()
ArrayOfIndex& TelsemAtlas::Cellnumber () inline
Definition at line 331 of file telsem.h.
References cellnums.
Cells()
ArrayOfIndex& TelsemAtlas::Cells () inline
Definition at line 312 of file telsem.h.
References ncells.
ChannelCount()
Index& TelsemAtlas::ChannelCount () inline
Definition at line 300 of file telsem.h.
References nchan.
Classes1()
ArrayOfIndex& TelsemAtlas::Classes1 () inline
Definition at line 327 of file telsem.h.
References classes1.
Classes2()
ArrayOfIndex& TelsemAtlas::Classes2 () inline
Definition at line 328 of file telsem.h.
References classes2.
contains()
bool TelsemAtlas::contains (Index cellnumber) const inline
Check if cell is contained in atlas.
Parameters
cellnumber The cellnumber for given coordinates obtained from calc cellnum.
Definition at line 85 of file telsem.h.
References correspondence, and Array< base >::nelem().
Referenced by calc_cellnum_nearest_neighbor(), surfaceTelsem(), telsemAtlasLookup(), telsemStandalone(), and telsemSurfaceTypeLandSea().
Correlations()
Tensor3& TelsemAtlas::Correlations () inline
Definition at line 324 of file telsem.h.
References correl.
Correspondance()
ArrayOfIndex& TelsemAtlas::Correspondance () inline
Definition at line 334 of file telsem.h.
References correspondence.
DataCount()
Index& TelsemAtlas::DataCount () inline
Definition at line 297 of file telsem.h.
References ndat.
Emis()
Matrix& TelsemAtlas::Emis () inline
Definition at line 318 of file telsem.h.
References emis.
Emis_err()
Matrix& TelsemAtlas::Emis_err () inline
Definition at line 321 of file telsem.h.
References emis_err.
emis_interp()
std::pair< Numeric, Numeric > TelsemAtlas::emis_interp (Numeric theta, Numeric freq, Index class1, Index class2, const ConstVectorView & ev, const ConstVectorView & eh) const
Interpolat emissivities to given zenith angle and frequency.
Parameters
theta The zenith angle
freq The frequency in GHz (!!!)
class1 The surface type class
class2 The sruface type class
ev The vertical emissivities from the atlas
eh The horizontal emissivities from atlas
Returns
A pair containing the interpolated horizontal and vertical emissivities.
Definition at line 287 of file telsem.cc.
References a0_eveh, a0_k0, a0_k1, a0_k2, a1, a1_eveh, a2, a2_eveh, a3_eveh, b0, b0_eveh, b1, b1_eveh, b2, b2_eveh, b3_eveh, interp_freq2(), and pow().
Referenced by telsemStandalone().
equare()
void TelsemAtlas::equare ()
Compute the number of cells in each latitude band.
Telsem surface emissivities are represented on an equal area grid. This functions computes the number of grid cells for each latitude band as well as the cell number of the first grid cell in each band.
Definition at line 93 of file telsem.cc.
References DEG2RAD, dlat, EARTH_RADIUS, firstcells, ncells, and PI.
Referenced by read().
FirstCells()
ArrayOfIndex& TelsemAtlas::FirstCells () inline
Definition at line 315 of file telsem.h.
References firstcells.
get_class1()
Index TelsemAtlas::get_class1 (Index cellnumber) const inline
Class of a given cell. Return the class1 value of the given cell. Indexed by cellnumber obtained from calc_cellnum(...).
Throws a runtime error if cellnumber is not contained in the atlas, i.e. is not over land.
Parameters
cellnumber The cellnumber for which to lookup the class.
Returns
The index representing the class1 value of the cell.
Definition at line 102 of file telsem.h.
References classes1, and correspondence.
Referenced by surfaceTelsem(), and telsemStandalone().
get_class2()
Index TelsemAtlas::get_class2 (Index cellnumber) const inline
Class of a given cell. Return the class2 value of the given cell. Indexed by cellnumber obtained from calc_cellnum(...).
Throws a runtime error if cellnumber is not contained in the atlas, i.e. is not over land.
Parameters
cellnumber The cellnumber for which to lookup the class.
Returns
The index representing the class2 value of the cell.
Definition at line 120 of file telsem.h.
References classes2, and correspondence.
Referenced by surfaceTelsem(), and telsemStandalone().
get_coordinates()
std::pair< Numeric, Numeric > TelsemAtlas::get_coordinates (Index cellnum) const
Compute corrdinates of a given cell.
Parameters
[in] cellnum The cell number for which to compute the coordinates.
[out] The latitiude and longitude coordinates of the cell.
Definition at line 225 of file telsem.cc.
References dlat, firstcells, ARTS::Var::lat(), ARTS::Var::lon(), and ncells.
Referenced by surfaceTelsem(), and telsemStandalone().
get_correl()
const Tensor3& TelsemAtlas::get_correl () const inline
Definition at line 77 of file telsem.h.
References correl.
get_emis_h()
Vector TelsemAtlas::get_emis_h (Index cellnum) const inline
Horizontally polarized emissivities at 19, 37 and 85 GHz.
The horizontally polarized emissivities that are used for the Telsem2 emissivity interpolation. The index here is the cellnumber obtained for given latitude and longitude using calc_cellnum(...).
Parameters
cellnum The atlas' cellunmber from which to extract the emissivities.
Returns
3-element vector containing the emissivities.
Definition at line 159 of file telsem.h.
References correspondence, and emis.
Referenced by surfaceTelsem(), and telsemStandalone().
get_emis_v()
Vector TelsemAtlas::get_emis_v (Index i) const inline
Verically polarized emissivities at 19, 37 and 85 GHz.
The vertically polarized emissivities that are used for the Telsem2 emissivity interpolation. The index here is the cellnumber obtained for given latitude and longitude using calc_cellnum(...).
Parameters
cellnum The atlas' cellunmber from which to extract the emissivities.
Returns
3-element vector containing the emissivities.
Definition at line 137 of file telsem.h.
References correspondence, and emis.
Referenced by surfaceTelsem(), and telsemStandalone().
get_month()
Index TelsemAtlas::get_month () const inline
Definition at line 75 of file telsem.h.
References month.
interp_freq2()
Numeric TelsemAtlas::interp_freq2 (Numeric emiss19, Numeric emiss37, Numeric emiss85, Numeric f, Index class2) const
Inter-/Extrapolate emissivities to given frequency.
This function interpolates the SSMI emissivities at 19, 37, 85 GHz to the given frequency value.
Parameters
emiss19 The SSMI emissivity at 19 GHz
emiss37 The SSMI emissivity at 37 GHz
emiss85 The SSMI emissivity at 85 GHz
f The frequency in GHz (!)
class2 The surface class
Returns
The interpolated emissivity
Definition at line 246 of file telsem.cc.
References a, b, c, rapport43_32, and rapport54_43.
Referenced by emis_interp().
Lat()
Numeric& TelsemAtlas::Lat () inline
Definition at line 309 of file telsem.h.
References dlat.
Month()
Index& TelsemAtlas::Month () inline
Definition at line 306 of file telsem.h.
References month.
Name()
String& TelsemAtlas::Name () inline
Definition at line 303 of file telsem.h.
References name.
operator=() [1/2]
TelsemAtlas& TelsemAtlas::operator= (const TelsemAtlas &) default
operator=() [2/2]
TelsemAtlas& TelsemAtlas::operator= (TelsemAtlas &&) default
operator[]()
ConstVectorView TelsemAtlas::operator[] (Index cellnumber) const inline
ConstVectorView on emissivities at given index.
The vector containing the seven SSMI emissivities contained in the atlas.
Throws a runtime error if cellnumber is not contained in the atlas, i.e. over land.
Parameters
The cellnumber
Returns
The ConstVectorView on the emissivities.
Definition at line 183 of file telsem.h.
References correspondence, emis, and joker.
RAPPORT43_32()
Numeric TelsemAtlas::RAPPORT43_32 (Index i) inline
Definition at line 348 of file telsem.h.
References rapport43_32.
RAPPORT54_43()
Numeric TelsemAtlas::RAPPORT54_43 (Index i) inline
Definition at line 349 of file telsem.h.
References rapport54_43.
read()
void TelsemAtlas::read (std::istream & is)
Read Telsem Atlas from input stream.
Definition at line 46 of file telsem.cc.
References ARTS_USER_ERROR_IF, cellnums, classes1, classes2, dlat, emis, emis_err, equare(), name, nchan, ndat, Matrix::resize(), sqrt(), and telsem_calc_correspondence().
Referenced by telsem_atlasReadAscii(), and TelsemAtlas().
set_correl()
void TelsemAtlas::set_correl (const Tensor3 & t) inline
Definition at line 78 of file telsem.h.
References correl.
set_month()
void TelsemAtlas::set_month (Index m) inline
Definition at line 74 of file telsem.h.
References month.
Referenced by telsem_atlasReadAscii().
telsem_calc_correspondence()
void TelsemAtlas::telsem_calc_correspondence ()
Compute cell indices in sparse data storage.
For each cell in the Atlas, this function stores the corresponding index in the data array in the correspondence member of this atlas object.
Definition at line 134 of file telsem.cc.
References cellnums, correspondence, and ndat.
Referenced by read().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TelsemAtlas & ta) friend
Definition at line 342 of file telsem.cc.
xml_read_from_stream
void xml_read_from_stream (istream & is_xml, TelsemAtlas & ta, bifstream * pbifs, const Verbosity & verbosity) friend
Reads TelsemAtlas from XML input stream.
Parameters
is_xml XML Input stream
pm TelsemAtlas return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1850 of file xml_io_compound_types.cc.
xml_write_to_stream
void xml_write_to_stream (ostream & os_xml, const TelsemAtlas & ta, bofstream * pbofs, const String & name, const Verbosity & verbosity) friend
Writes TelsemAtlas to XML output stream.
Parameters
os_xml XML Output stream
pm TelsemAtlas
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1882 of file xml_io_compound_types.cc.
Member Data Documentation
a0_eveh
const std::array< Numeric, 30 > TelsemAtlas::a0_eveh static private
Initial value:
= {
    0.9592599869E+00, 0.9565299749E+00, 0.9511899948E+00, 0.9560700059E+00,
    0.9541199803E+00, 0.9483199716E+00, 0.9461100101E+00, 0.9439799786E+00,
    0.9387800097E+00, 0.9317600131E+00, 0.9289000034E+00, 0.9236800075E+00,
    0.9208700061E+00, 0.9190599918E+00, 0.9105200171E+00, 0.9162799716E+00,
    0.8937299848E+00, 0.8014699817E+00, 0.9570500255E+00, 0.9213600159E+00,
    0.7893999815E+00, 0.9639400244E+00, 0.9530599713E+00, 0.8850200176E+00,
    0.9685299993E+00, 0.9622600079E+00, 0.9118800163E+00, 0.8997200131E+00,
    0.9012699723E+00, 0.9107499719E+00}
Definition at line 384 of file telsem.h.
Referenced by A0_EVEH(), and emis_interp().
a0_k0
const std::array< Numeric, 30 > TelsemAtlas::a0_k0 static private
Initial value:
= {
    0.11509,   0.091535, 0.34796,   0.10525,  0.16627,  0.24434,
    0.29217,   0.23809,  0.28954,   0.17516,  0.19459,  0.28697,
    0.10521,   0.12126,  0.30278,   0.18212,  0.19625,  0.14551,
    -0.19202,  0.5411,   0.03739,   0.10292,  0.5486,   -0.058937,
    -0.022672, 0.44492,  -0.058448, -0.33894, -0.17621, 0.14742}
Definition at line 381 of file telsem.h.
Referenced by A0_K0(), and emis_interp().
a0_k1
const std::array< Numeric, 30 > TelsemAtlas::a0_k1 static private
Initial value:
= {
    0.61168, 0.59095,  0.7918, 0.60271, 0.69213, 0.62218, 0.32728, 0.34334,
    0.37062, 0.51217,  0.4491, 0.50101, 0.48913, 0.41932, 0.29734, 0.64474,
    0.30637, 0.031107, 1.0405, 0.17538, 1.3215,  0.61819, 0.31298, 1.7218,
    0.87761, 0.47583,  1.2583, 1.0959,  0.92842, 0.51033}
Definition at line 382 of file telsem.h.
Referenced by A0_K1(), and emis_interp().
a0_k2
const std::array< Numeric, 30 > TelsemAtlas::a0_k2 static private
Initial value:
= {
    0.26726, 0.32033,  -0.14778, 0.28547, 0.13592,  0.13193, 0.37178, 0.41813,
    0.33875, 0.30203,  0.35479,  0.20189, 0.40663,  0.47493, 0.40668, 0.14811,
    0.52382, 0.86634,  0.14286,  0.27164, -0.37947, 0.2737,  0.12001, -0.67315,
    0.13492, 0.065463, -0.19316, 0.24905, 0.25475,  0.34637}
Definition at line 383 of file telsem.h.
Referenced by A0_K2(), and emis_interp().
a1_eveh
const std::array< Numeric, 30 > TelsemAtlas::a1_eveh static private
Initial value:
= {
    0.3627802414E-07, -0.7778328204E-08, 0.4396108011E-07,  0.2503205394E-06,
    0.1996262995E-06, 0.2929977541E-06,  0.4190530660E-06,  0.3655744649E-06,
    0.3519195673E-06, 0.5574374313E-06,  0.5273076340E-06,  0.5376484182E-06,
    0.1026844529E-05, 0.9679998811E-06,  0.8616486866E-06,  0.3180800832E-06,
    0.2886778532E-06, 0.2310362675E-06,  -0.1118036366E-06, -0.1502856577E-06,
    0.4842232926E-07, -0.8410978580E-08, -0.3478669441E-07, 0.2209441590E-06,
    0.2485776633E-06, 0.1800235907E-06,  0.2510202251E-06,  0.2687000915E-06,
    0.1740325644E-06, 0.3562134339E-06}
Definition at line 385 of file telsem.h.
Referenced by A1_EVEH(), and emis_interp().
a2_eveh
const std::array< Numeric, 30 > TelsemAtlas::a2_eveh static private
Initial value:
= {
    0.3067140824E-05, 0.2520012231E-05, 0.4831396382E-05, 0.8213598448E-05,
    0.7378375358E-05, 0.1022081960E-04, 0.1225889173E-04, 0.1165553113E-04,
    0.1188659007E-04, 0.1693615741E-04, 0.1648317448E-04, 0.1715818144E-04,
    0.2744720041E-04, 0.2642072104E-04, 0.2671847506E-04, 0.1349592094E-04,
    0.1261523357E-04, 0.5447756394E-05, 0.2064244654E-05, 0.1919016057E-06,
    0.5940860319E-06, 0.5334760772E-05, 0.4130339221E-05, 0.4104662821E-05,
    0.6530796327E-05, 0.5727014013E-05, 0.7451782039E-05, 0.1071246970E-04,
    0.9539280654E-05, 0.1034286015E-04}
Definition at line 386 of file telsem.h.
Referenced by A2_EVEH(), and emis_interp().
a3_eveh
const std::array< Numeric, 30 > TelsemAtlas::a3_eveh static private
Initial value:
= {
    -0.2004991551E-07, -0.6895366056E-07, -0.2047409282E-06, -0.7322448425E-07,
    -0.1273002681E-06, -0.2729916844E-06, -0.9421125213E-07, -0.1683332300E-06,
    -0.2726891637E-06, -0.1317753799E-06, -0.2107972250E-06, -0.3556060904E-06,
    -0.1889465580E-06, -0.2757958271E-06, -0.4909850304E-06, 0.7339644004E-08,
    -0.4058669560E-06, -0.4146343997E-06, 0.6170279931E-07,  -0.1998567996E-06,
    -0.4713119139E-07, -0.1361754887E-07, -0.1765622955E-06, -0.2348146637E-06,
    -0.3901189061E-07, -0.1305666189E-06, -0.1533838798E-06, -.2679148992E-07,
    -0.4441960044E-07, -0.1815613899E-06}
Definition at line 387 of file telsem.h.
Referenced by A3_EVEH(), and emis_interp().
b0_eveh
const std::array< Numeric, 30 > TelsemAtlas::b0_eveh static private
Initial value:
= {
    0.9592599869E+00, 0.9565299749E+00, 0.9511899948E+00, 0.9560700059E+00,
    0.9541199803E+00, 0.9483199716E+00, 0.9461100101E+00, 0.9439799786E+00,
    0.9387800097E+00, 0.9317600131E+00, 0.9289000034E+00, 0.9236800075E+00,
    0.9208700061E+00, 0.9190599918E+00, 0.9105200171E+00, 0.9162799716E+00,
    0.8937299848E+00, 0.8014699817E+00, 0.9570500255E+00, 0.9213600159E+00,
    0.7893999815E+00, 0.9639400244E+00, 0.9530599713E+00, 0.8850200176E+00,
    0.9685299993E+00, 0.9622600079E+00, 0.9118800163E+00, 0.8997200131E+00,
    0.9012699723E+00, 0.9107499719E+00}
Definition at line 388 of file telsem.h.
Referenced by B0_EVEH(), and emis_interp().
b1_eveh
const std::array< Numeric, 30 > TelsemAtlas::b1_eveh static private
Initial value:
= {
    0.3626608347E-07, -0.7786279177E-08, 0.4393379172E-07,  0.2502746099E-06,
    0.1995944388E-06, 0.2929554341E-06,  0.4189516289E-06,  0.3655020180E-06,
    0.3518483140E-06, 0.5572838404E-06,  0.5271903092E-06,  0.5375342766E-06,
    0.1026605219E-05, 0.9677979733E-06,  0.8614680951E-06,  0.3179358714E-06,
    0.2884899004E-06, 0.2308632219E-06,  -0.1118781370E-06, -0.1503948681E-06,
    0.4834672396E-07, -0.8455684153E-08, -0.3485171618E-07, 0.2208606134E-06,
    0.2485595019E-06, 0.1799959364E-06,  0.2509846695E-06,  0.2686167306E-06,
    0.1739760478E-06, 0.3561317214E-06}
Definition at line 389 of file telsem.h.
Referenced by B1_EVEH(), and emis_interp().
b2_eveh
const std::array< Numeric, 30 > TelsemAtlas::b2_eveh static private
Initial value:
= {
    0.3065537157E-05, 0.2518960400E-05, 0.4829731552E-05, 0.8209894986E-05,
    0.7375769655E-05, 0.1021809931E-04, 0.1225203869E-04, 0.1165053800E-04,
    0.1188218721E-04, 0.1692612022E-04, 0.1647546378E-04, 0.1715117833E-04,
    0.2743142431E-04, 0.2640772436E-04, 0.2670711910E-04, 0.1348545720E-04,
    0.1260529825E-04, 0.5439695997E-05, 0.2058213340E-05, 0.1860650656E-06,
    0.5898303925E-06, 0.5330772183E-05, 0.4126528893E-05, 0.4100859314E-05,
    0.6528573977E-05, 0.5725009032E-05, 0.7449450095E-05, 0.1070590315E-04,
    0.9534271157E-05, 0.1033751869E-04}
Definition at line 390 of file telsem.h.
Referenced by B2_EVEH(), and emis_interp().
b3_eveh
const std::array< Numeric, 30 > TelsemAtlas::b3_eveh static private
Initial value:
= {
    -0.1370247134E-06, -0.1436897747E-06, -0.2954870411E-06, -0.3118435643E-06,
    -0.2916583242E-06, -0.4311032171E-06, -0.5048401022E-06, -0.4662823869E-06,
    -0.5206445053E-06, -0.7210980471E-06, -0.6662896794E-06, -0.7548637200E-06,
    -0.1110204039E-05, -0.1030801400E-05, -0.1140921199E-05, -0.6330818110E-06,
    -0.9186441048E-06, -0.7947813856E-06, -0.3242539890E-06, -0.5027602583E-06,
    -0.2777987334E-06, -0.2747250676E-06, -0.3811997260E-06, -0.4102405455E-06,
    -0.1994112324E-06, -0.2555484855E-06, -0.2842682534E-06, -0.4413041665E-06,
    -0.3717419474E-06, -0.4975536854E-06}
Definition at line 391 of file telsem.h.
Referenced by B3_EVEH(), and emis_interp().
cellnums
ArrayOfIndex TelsemAtlas::cellnums private
Definition at line 376 of file telsem.h.
Referenced by Cellnumber(), read(), and telsem_calc_correspondence().
classes1
ArrayOfIndex TelsemAtlas::classes1 private
Definition at line 373 of file telsem.h.
Referenced by Classes1(), get_class1(), and read().
classes2
ArrayOfIndex TelsemAtlas::classes2 private
Definition at line 374 of file telsem.h.
Referenced by Classes2(), get_class2(), and read().
correl
Tensor3 TelsemAtlas::correl private
Definition at line 371 of file telsem.h.
Referenced by Correlations(), get_correl(), and set_correl().
correspondence
ArrayOfIndex TelsemAtlas::correspondence private
Definition at line 378 of file telsem.h.
Referenced by contains(), Correspondance(), get_class1(), get_class2(), get_emis_h(), get_emis_v(), operator[](), and telsem_calc_correspondence().
dlat
Numeric TelsemAtlas::dlat private
Definition at line 361 of file telsem.h.
Referenced by calc_cellnum(), calc_cellnum_nearest_neighbor(), equare(), get_coordinates(), Lat(), and read().
emis
Matrix TelsemAtlas::emis private
Definition at line 367 of file telsem.h.
Referenced by Emis(), get_emis_h(), get_emis_v(), operator[](), and read().
emis_err
Matrix TelsemAtlas::emis_err private
Definition at line 369 of file telsem.h.
Referenced by Emis_err(), and read().
firstcells
ArrayOfIndex TelsemAtlas::firstcells private
Definition at line 365 of file telsem.h.
Referenced by equare(), FirstCells(), and get_coordinates().
month
Index TelsemAtlas::month private
Definition at line 359 of file telsem.h.
Referenced by get_month(), Month(), and set_month().
name
String TelsemAtlas::name private
Definition at line 357 of file telsem.h.
Referenced by Name(), and read().
ncells
ArrayOfIndex TelsemAtlas::ncells private
Definition at line 363 of file telsem.h.
Referenced by calc_cellnum(), Cells(), equare(), and get_coordinates().
nchan
Index TelsemAtlas::nchan private
Definition at line 355 of file telsem.h.
Referenced by ChannelCount(), and read().
ndat
Index TelsemAtlas::ndat private
Definition at line 353 of file telsem.h.
Referenced by DataCount(), read(), and telsem_calc_correspondence().
rapport43_32
const std::array< Numeric, 4 > TelsemAtlas::rapport43_32 static private
Initial value:
= {
    0.62, 0.37, 0.46, 0.63}
Definition at line 392 of file telsem.h.
Referenced by interp_freq2(), and RAPPORT43_32().
rapport54_43
const std::array< Numeric, 4 > TelsemAtlas::rapport54_43 static private
Initial value:
= {
    0.30, 0.60, 0.47, 0.35}
Definition at line 393 of file telsem.h.
Referenced by interp_freq2(), and RAPPORT54_43().
The documentation for this class was generated from the following files:
telsem.h
telsem.cc