ARTS: ARTS::Var::ArrayOfArrayOfGriddedField1 Class Reference
ARTS::Var::ArrayOfArrayOfGriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfGriddedField1 () noexcept
ArrayOfArrayOfGriddedField1 (std::size_t i, void *x) noexcept
ArrayOfArrayOfGriddedField1 (const Group::ArrayOfArrayOfGriddedField1 &val) noexcept
~ArrayOfArrayOfGriddedField1 () noexcept
Group::ArrayOfArrayOfGriddedField1 & value () noexcept
const Group::ArrayOfArrayOfGriddedField1 & value () const noexcept
ArrayOfArrayOfGriddedField1 & operator= (const Group::ArrayOfArrayOfGriddedField1 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfGriddedField1 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfGriddedField1 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 559 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfGriddedField1() [1/3]
ARTS::Var::ArrayOfArrayOfGriddedField1::ArrayOfArrayOfGriddedField1 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 564 of file autoarts.h.
ArrayOfArrayOfGriddedField1() [2/3]
ARTS::Var::ArrayOfArrayOfGriddedField1::ArrayOfArrayOfGriddedField1 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 567 of file autoarts.h.
ArrayOfArrayOfGriddedField1() [3/3]
ARTS::Var::ArrayOfArrayOfGriddedField1::ArrayOfArrayOfGriddedField1 (const Group::ArrayOfArrayOfGriddedField1 & val) inline noexcept
Construct from Group::ArrayOfArrayOfGriddedField1. Leaves islast() true and isnull() false
Definition at line 570 of file autoarts.h.
~ArrayOfArrayOfGriddedField1()
ARTS::Var::ArrayOfArrayOfGriddedField1::~ArrayOfArrayOfGriddedField1 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 573 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfGriddedField1::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 591 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfArrayOfGriddedField1().
isnull()
bool ARTS::Var::ArrayOfArrayOfGriddedField1::isnull () const inline noexcept
Return true if there is no data
Definition at line 588 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfGriddedField1().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfGriddedField1::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 594 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfGriddedField1& ARTS::Var::ArrayOfArrayOfGriddedField1::operator= (const Group::ArrayOfArrayOfGriddedField1 & t) inline noexcept
Set value from Group::ArrayOfArrayOfGriddedField1. Works when isnull() is false
Definition at line 582 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField1::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 585 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfArrayOfGriddedField1& ARTS::Var::ArrayOfArrayOfGriddedField1::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfGriddedField1. Works when isnull() is false
Definition at line 579 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfGriddedField1& ARTS::Var::ArrayOfArrayOfGriddedField1::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfGriddedField1. Works when isnull() is false
Definition at line 576 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfGriddedField1 & var) friend
Output to stream of internal variable
Definition at line 597 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfGriddedField1::p private
Definition at line 560 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfGriddedField1* ARTS::Var::ArrayOfArrayOfGriddedField1::v private
Definition at line 561 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfGriddedField1().
The documentation for this class was generated from the following file:
autoarts.h