ARTS: GriddedField4 Class Reference
GriddedField4 Class Reference final
#include <gridded_fields.h>
Public Member Functions
GriddedField4 ()
Construct an empty GriddedField4.
GriddedField4 (const String &s)
Construct an empty GriddedField4 with the given name.
bool checksize () const final
Consistency check.
void checksize_strict () const final
Strict consistency check.
void resize (const GriddedField4 &gf)
Make this GriddedField4 the same size as the given one.
void resize (Index b, Index p, Index r, Index c)
Resize the data tensor.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
const Vector & get_numeric_grid (Index i) const
Get a numeric grid.
Vector & get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Tensor4 data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField4 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 340 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField4() [1/2]
GriddedField4::GriddedField4 () inline
Construct an empty GriddedField4.
Definition at line 343 of file gridded_fields.h.
GriddedField4() [2/2]
GriddedField4::GriddedField4 (const String & s) inline
Construct an empty GriddedField4 with the given name.
Parameters
[in] s Name.
Definition at line 346 of file gridded_fields.h.
Member Function Documentation
checksize()
bool GriddedField4::checksize () const inline final virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 348 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Referenced by checksize_strict().
checksize_strict()
void GriddedField4::checksize_strict () const inline final virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 359 of file gridded_fields.h.
References CHECK_ERROR_BOILERPLATE, checksize(), data, GriddedField::get_grid_name(), GriddedField::get_grid_size(), GriddedField::get_name(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), Absorption::nelem(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Referenced by surface_scalar_reflectivityFromGriddedField4(), and xml_read_from_stream().
resize() [1/2]
void GriddedField4::resize (const GriddedField4 & gf) inline
Make this GriddedField4 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 379 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Tensor4::resize().
Referenced by atm_fields_compactExpand(), atm_fields_compactFromMatrix(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), and GriddedFieldPRegrid().
resize() [2/2]
void GriddedField4::resize (Index b, Index p, Index r, Index c) inline
Resize the data tensor.
See also
Tensor4::resize
Definition at line 388 of file gridded_fields.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField4 & gf) friend
Member Data Documentation
data
Tensor4 GriddedField4::data
Definition at line 392 of file gridded_fields.h.
Referenced by antenna_responseGaussian(), antenna_responseVaryingGaussian(), AntennaConstantGaussian1D(), atm_fields_compactAddConstant(), atm_fields_compactExpand(), atm_fields_compactFromMatrix(), checksize(), checksize_strict(), FieldFromGriddedField(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), operator<<(), resize(), surface_scalar_reflectivityFromGriddedField4(), xml_read_from_stream(), and xml_write_to_stream().
The documentation for this class was generated from the following file:
gridded_fields.h