ARTS: ARTS::Var::WorkspaceArrayOfRetrievalQuantity Class Reference
ARTS::Var::WorkspaceArrayOfRetrievalQuantity Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfRetrievalQuantity () noexcept
WorkspaceArrayOfRetrievalQuantity (std::size_t i, void *x) noexcept
~WorkspaceArrayOfRetrievalQuantity () noexcept
WorkspaceArrayOfRetrievalQuantity (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfRetrievalQuantity & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfRetrievalQuantity
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 710 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfRetrievalQuantity::type = Group::ArrayOfRetrievalQuantity private
Definition at line 711 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfRetrievalQuantity() [1/3]
ARTS::Var::WorkspaceArrayOfRetrievalQuantity::WorkspaceArrayOfRetrievalQuantity () inline noexcept
Definition at line 715 of file autoarts.h.
WorkspaceArrayOfRetrievalQuantity() [2/3]
ARTS::Var::WorkspaceArrayOfRetrievalQuantity::WorkspaceArrayOfRetrievalQuantity (std::size_t i, void * x) inline noexcept
Definition at line 716 of file autoarts.h.
~WorkspaceArrayOfRetrievalQuantity()
ARTS::Var::WorkspaceArrayOfRetrievalQuantity::~WorkspaceArrayOfRetrievalQuantity () inline noexcept
Definition at line 717 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfRetrievalQuantity() [3/3]
ARTS::Var::WorkspaceArrayOfRetrievalQuantity::WorkspaceArrayOfRetrievalQuantity (const type & val) inline noexcept
Definition at line 718 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfRetrievalQuantity::islast () const inline noexcept
Definition at line 724 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfRetrievalQuantity().
isnull()
bool ARTS::Var::WorkspaceArrayOfRetrievalQuantity::isnull () const inline noexcept
Definition at line 723 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfRetrievalQuantity().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfRetrievalQuantity::name () const inline noexcept
Definition at line 725 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfRetrievalQuantity& ARTS::Var::WorkspaceArrayOfRetrievalQuantity::operator= (const type & t) inline noexcept
Definition at line 721 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfRetrievalQuantity::pos () const inline noexcept
Definition at line 722 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfRetrievalQuantity::value () const inline noexcept
Definition at line 720 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfRetrievalQuantity::value () inline noexcept
Definition at line 719 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfRetrievalQuantity::p private
Definition at line 712 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfRetrievalQuantity::v private
Definition at line 713 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfRetrievalQuantity().
The documentation for this class was generated from the following file:
autoarts.h