ARTS: PropagationMatrix Class Reference
PropagationMatrix Class Reference
#include <propagationmatrix.h>
Public Member Functions
PropagationMatrix (const Index nr_frequencies=0, const Index stokes_dim=1, const Index nr_za=1, const Index nr_aa=1, const Numeric v=0.0)
Initialize variable sizes.
PropagationMatrix (const PropagationMatrix &pm)
Construct a new Propagation Matrix object.
PropagationMatrix (PropagationMatrix &&pm) noexcept
Construct a new Propagation Matrix object.
PropagationMatrix (ConstTensor4View x)
Construct a new Propagation Matrix object.
PropagationMatrix (ConstMatrixView x, const bool &assume_fit=false)
Initialize from single stokes_dim-by-stokes_dim matrix.
Index StokesDimensions () const
The stokes dimension of the propagation matrix.
Index NumberOfFrequencies () const
The number of frequencies of the propagation matrix.
Index NumberOfZenithAngles () const
The number of zenith angles of the propagation matrix.
Index NumberOfAzimuthAngles () const
The number of azimuth angles of the propagation matrix.
bool OK () const
void SetVectorType (bool vectortype)
Set the Vector Type object.
bool IsEmpty () const
Asks if the class is empty.
bool IsZero (const Index iv=0, const Index iz=0, const Index ia=0) const
False if any non-zeroes in internal Matrix representation.
bool IsRotational (const Index iv=0, const Index iz=0, const Index ia=0) const
False if diagonal element is non-zero in internal Matrix representation.
Index NumberOfNeededVectors () const
The number of required vectors to fill this PropagationMatrix.
Numeric operator() (const Index iv=0, const Index is1=0, const Index is2=0, const Index iz=0, const Index ia=0) const
access operator.
void AddFaraday (const Numeric &rot, const Index iv=0, const Index iz=0, const Index ia=0)
Adds the Faraday rotation to the PropagationMatrix at required position.
void SetFaraday (const Numeric &rot, const Index iv=0, const Index iz=0, const Index ia=0)
Sets the Faraday rotation to the PropagationMatrix at required position.
void MatrixAtPosition (MatrixView ret, const Index iv=0, const Index iz=0, const Index ia=0) const
Sets the dense matrix.
PropagationMatrix & operator= (PropagationMatrix &&pm) noexcept
Move operator.
PropagationMatrix & operator= (const LazyScale< PropagationMatrix > &lpms)
Laze equal to opeartor.
PropagationMatrix & operator= (const PropagationMatrix &other)
Copy operator.
PropagationMatrix & operator= (const Numeric &x)
Sets all data to constant.
void SetAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
void SetAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
void SetAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
PropagationMatrix & operator/= (const PropagationMatrix &other)
Divide operator.
PropagationMatrix & operator/= (ConstVectorView x)
Divide operator.
PropagationMatrix & operator/= (const Numeric &x)
Divide operator.
void DivideAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
void DivideAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
void DivideAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
PropagationMatrix & operator*= (const PropagationMatrix &other)
Multiply operator.
PropagationMatrix & operator*= (ConstVectorView x)
Multiply operator.
PropagationMatrix & operator*= (const Numeric &x)
Multiply operator.
void MultiplyAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
void MultiplyAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
void MultiplyAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
PropagationMatrix & operator+= (const PropagationMatrix &other)
Addition operator.
PropagationMatrix & operator+= (const LazyScale< PropagationMatrix > &lpms)
Addition operator.
PropagationMatrix & operator+= (ConstVectorView x)
Addition operator.
PropagationMatrix & operator+= (const Numeric &x)
Addition operator.
void AddAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
void AddAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
void AddAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
PropagationMatrix & operator-= (const PropagationMatrix &other)
Subtraction operator.
PropagationMatrix & operator-= (ConstVectorView x)
Subtraction operator.
PropagationMatrix & operator-= (const Numeric &x)
Subtraction operator.
void RemoveAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void RemoveAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void RemoveAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void AddAbsorptionVectorAtPosition (ConstVectorView x, const Index iv=0, const Index iz=0, const Index ia=0)
Adds as a Stokes vector at position.
void AddAverageAtPosition (ConstMatrixView mat1, ConstMatrixView mat2, const Index iv=0, const Index iz=0, const Index ia=0)
Add the average of the two input at position.
void MultiplyAndAdd (const Numeric x, const PropagationMatrix &y)
Multiply input by scalar and add to this.
void MatrixInverseAtPosition (MatrixView ret, const Index iv=0, const Index iz=0, const Index ia=0) const
Return the matrix inverse at the position.
bool FittingShape (ConstMatrixView x) const
Tests of the input matrix fits Propagation Matrix style.
void GetTensor3 (Tensor3View tensor3, const Index iz=0, const Index ia=0)
Get a Tensor3 object from this.
VectorView Kjj (const Index iz=0, const Index ia=0)
Vector view to diagonal elements.
VectorView K12 (const Index iz=0, const Index ia=0)
Vector view to K(0, 1) elements.
VectorView K13 (const Index iz=0, const Index ia=0)
Vector view to K(0, 2) elements.
VectorView K14 (const Index iz=0, const Index ia=0)
Vector view to K(0, 3) elements.
VectorView K23 (const Index iz=0, const Index ia=0)
Vector view to K(1, 2) elements.
VectorView K24 (const Index iz=0, const Index ia=0)
Vector view to K(1, 3) elements.
VectorView K34 (const Index iz=0, const Index ia=0)
Vector view to K(2, 3) elements.
ConstVectorView Kjj (const Index iz=0, const Index ia=0) const
Vector view to diagonal elements.
ConstVectorView K12 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 1) elements.
ConstVectorView K13 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 2) elements.
ConstVectorView K14 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 3) elements.
ConstVectorView K23 (const Index iz=0, const Index ia=0) const
Vector view to K(1, 3) elements.
ConstVectorView K24 (const Index iz=0, const Index ia=0) const
Vector view to K(1, 3) elements.
ConstVectorView K34 (const Index iz=0, const Index ia=0) const
Vector view to diagonal elements.
void SetZero ()
Sets all data to zero.
Tensor4 & Data ()
Get full view to data.
const Tensor4 & Data () const
Get full const view to data.
void LeftMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv=0, const Index iz=0, const Index ia=0) const
Multiply the matrix input from the left of this at position.
void RightMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv=0, const Index iz=0, const Index ia=0) const
Multiply the matrix input from the right of this at position.
Protected Attributes
Index mfreqs
Index mstokes_dim
Index mza
Index maa
Tensor4 mdata
bool mvectortype
Detailed Description
Propagation Matrix Holder Class With Some Computational Capabilities
The idea comes from the fact that the propagation matrix has the looks
/ \ | a b c d | | b a u v | | c -u a w | | d -v -w a | \ /
So we instead store the inner parts of the matrix linearly as [a b c d u v w], and all computations happens on these variables instead. Note that the variables changes with the Stokes dimension
Stokes Dim 4: [a b c d u v w] Stokes Dim 3: [a b c u] Stokes Dim 2: [a b] Stokes Dim 1: [a]
And for devs: the u-variable is at vector position of the Stokes Dim in case 4 and 3, and that the other variables never change their positions, which is why the switch cases are all consistently fall-through-able in this class
Definition at line 87 of file propagationmatrix.h.
Constructor & Destructor Documentation
PropagationMatrix() [1/5]
PropagationMatrix::PropagationMatrix (const Index nr_frequencies = 0, const Index stokes_dim = 1, const Index nr_za = 1, const Index nr_aa = 1, const Numeric v = 0.0) inline
Initialize variable sizes.
Will create a Tensor4 of the size and order (nr_aa, nr_za, NumberOfNeededVectors(), nr_frequencies)
Parameters
[in] nr_frequencies Number of Dirac frequencies
[in] stokes_dim Stokes dimensionality
[in] nr_za Number of Dirac Zeniths
[in] nr_aa Number of Dirac Azimuths
[in] v Initial values of things in the created Tensor4
Definition at line 100 of file propagationmatrix.h.
References maa, mdata, mfreqs, mza, and NumberOfNeededVectors().
PropagationMatrix() [2/5]
PropagationMatrix::PropagationMatrix (const PropagationMatrix & pm) inline
Construct a new Propagation Matrix object.
Parameters
[in] pm Old propagation matrix object to copy
Definition at line 118 of file propagationmatrix.h.
PropagationMatrix() [3/5]
PropagationMatrix::PropagationMatrix (PropagationMatrix && pm) inline noexcept
Construct a new Propagation Matrix object.
Parameters
[in] pm old Propagation Matrix object to move from
Definition at line 130 of file propagationmatrix.h.
PropagationMatrix() [4/5]
PropagationMatrix::PropagationMatrix (ConstTensor4View x) inline explicit
Construct a new Propagation Matrix object.
Parameters
[in] x Tensor4 object to use to initialize from
Definition at line 142 of file propagationmatrix.h.
References mstokes_dim, and ARTS::Var::x().
PropagationMatrix() [5/5]
PropagationMatrix::PropagationMatrix (ConstMatrixView x, const bool & assume_fit = false) inline explicit
Initialize from single stokes_dim-by-stokes_dim matrix.
Parameters
[in] x The matrix
[in] assume_fit Assume a correct fit? Do not set this in manual interface
Definition at line 172 of file propagationmatrix.h.
References FittingShape(), mdata, mstokes_dim, mvectortype, NumberOfNeededVectors(), Tensor4::resize(), and ARTS::Var::x().
Member Function Documentation
AddAbsorptionVectorAtPosition()
void PropagationMatrix::AddAbsorptionVectorAtPosition (ConstVectorView x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Adds as a Stokes vector at position.
Parameters
[in] x
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 739 of file propagationmatrix.h.
References mdata, mstokes_dim, and ARTS::Var::x().
AddAtPosition() [1/3]
void PropagationMatrix::AddAtPosition (const Numeric & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Addition at position operator.
Parameters
[in] other Addition by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 649 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
AddAtPosition() [2/3]
void PropagationMatrix::AddAtPosition (const PropagationMatrix & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Addition at position operator.
Parameters
[in] other Addition by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 623 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
AddAtPosition() [3/3]
void PropagationMatrix::AddAtPosition (ConstMatrixView x, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Addition at position operator.
Parameters
[in] other Addition by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1852 of file propagationmatrix.cc.
References mdata, mstokes_dim, and ARTS::Var::x().
AddAverageAtPosition()
void PropagationMatrix::AddAverageAtPosition (ConstMatrixView mat1, ConstMatrixView mat2, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Add the average of the two input at position.
Parameters
[in] mat1 input 1
[in] mat2 input 2
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1610 of file propagationmatrix.cc.
References mdata, and mstokes_dim.
AddFaraday()
void PropagationMatrix::AddFaraday (const Numeric & rot, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Adds the Faraday rotation to the PropagationMatrix at required position.
No vector function exists since rot is a function of frequency
Parameters
[in] rot rotation
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 297 of file propagationmatrix.h.
References mdata, and mstokes_dim.
Data() [1/2]
Tensor4& PropagationMatrix::Data () inline
Get full view to data.
Definition at line 937 of file propagationmatrix.h.
References mdata.
Referenced by _cr_internal_(), operator<<(), test_r_deriv_propagationmatrix(), and xml_write_to_stream().
Data() [2/2]
const Tensor4& PropagationMatrix::Data () const inline
Get full const view to data.
Definition at line 940 of file propagationmatrix.h.
References mdata.
DivideAtPosition() [1/3]
void PropagationMatrix::DivideAtPosition (const Numeric & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Divide at position.
Parameters
[in] other Divide by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 495 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
DivideAtPosition() [2/3]
void PropagationMatrix::DivideAtPosition (const PropagationMatrix & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Divide at position.
Parameters
[in] other Divide by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 469 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
DivideAtPosition() [3/3]
void PropagationMatrix::DivideAtPosition (ConstMatrixView x, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Divide at position.
Parameters
[in] other Divide by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1890 of file propagationmatrix.cc.
References mdata, mstokes_dim, and ARTS::Var::x().
FittingShape()
bool PropagationMatrix::FittingShape (ConstMatrixView x) const
Tests of the input matrix fits Propagation Matrix style.
Parameters
[in] x Input matrix
Definition at line 1640 of file propagationmatrix.cc.
References mstokes_dim, Absorption::nelem(), and ARTS::Var::x().
Referenced by PropagationMatrix().
GetTensor3()
void PropagationMatrix::GetTensor3 (Tensor3View tensor3, const Index iz = 0, const Index ia = 0)
Get a Tensor3 object from this.
Parameters
[in,out] tensor3 New tensor
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1674 of file propagationmatrix.cc.
References joker, mdata, and mstokes_dim.
IsEmpty()
bool PropagationMatrix::IsEmpty () const inline
Asks if the class is empty.
Definition at line 221 of file propagationmatrix.h.
References maa, mfreqs, and mza.
Referenced by get_stepwise_effective_source(), and RadiationVector::setSource().
IsRotational()
bool PropagationMatrix::IsRotational (const Index iv = 0, const Index iz = 0, const Index ia = 0) const inline
False if diagonal element is non-zero in internal Matrix representation.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
False if diagonal is non-zero
Definition at line 247 of file propagationmatrix.h.
References mdata.
Referenced by get_stepwise_effective_source(), and stepwise_source().
IsZero()
bool PropagationMatrix::IsZero (const Index iv = 0, const Index iz = 0, const Index ia = 0) const inline
False if any non-zeroes in internal Matrix representation.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
False if any non-zeroes
Definition at line 230 of file propagationmatrix.h.
References joker, and mdata.
K12() [1/2]
VectorView PropagationMatrix::K12 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(0, 1) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 1) elements
Definition at line 809 of file propagationmatrix.h.
References joker, and mdata.
Referenced by abs_vecTransform(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), dtransmat2(), dtransmat3(), dtransmat4(), ext_matTransform(), StokesVector::IsPolarized(), LeftMultiplyAtPosition(), MatrixInverseAtPosition(), operator>>(), RightMultiplyAtPosition(), RadiationVector::setSource(), stepwise_source(), test_r_deriv_propagationmatrix(), transmat2(), transmat3(), and transmat4().
K12() [2/2]
ConstVectorView PropagationMatrix::K12 (const Index iz = 0, const Index ia = 0) const inline
Vector view to K(0, 1) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 1) elements
Definition at line 879 of file propagationmatrix.h.
References joker, and mdata.
K13() [1/2]
VectorView PropagationMatrix::K13 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(0, 2) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 2) elements
Definition at line 819 of file propagationmatrix.h.
References joker, and mdata.
Referenced by StokesVector::IsPolarized(), operator>>(), RadiationVector::setSource(), stepwise_source(), and test_r_deriv_propagationmatrix().
K13() [2/2]
ConstVectorView PropagationMatrix::K13 (const Index iz = 0, const Index ia = 0) const inline
Vector view to K(0, 2) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 2) elements
Definition at line 889 of file propagationmatrix.h.
References joker, and mdata.
K14() [1/2]
VectorView PropagationMatrix::K14 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(0, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 3) elements
Definition at line 829 of file propagationmatrix.h.
References joker, and mdata.
Referenced by StokesVector::IsPolarized(), operator>>(), RadiationVector::setSource(), stepwise_source(), and test_r_deriv_propagationmatrix().
K14() [2/2]
ConstVectorView PropagationMatrix::K14 (const Index iz = 0, const Index ia = 0) const inline
Vector view to K(0, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(0, 3) elements
Definition at line 899 of file propagationmatrix.h.
References joker, and mdata.
K23() [1/2]
VectorView PropagationMatrix::K23 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(1, 2) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(1, 2) elements
Definition at line 839 of file propagationmatrix.h.
References joker, mdata, and mstokes_dim.
Referenced by operator>>(), stepwise_source(), and test_r_deriv_propagationmatrix().
K23() [2/2]
ConstVectorView PropagationMatrix::K23 (const Index iz = 0, const Index ia = 0) const inline
Vector view to K(1, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(1, 3) elements
Definition at line 909 of file propagationmatrix.h.
References joker, mdata, and mstokes_dim.
K24() [1/2]
VectorView PropagationMatrix::K24 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(1, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(1, 3) elements
Definition at line 849 of file propagationmatrix.h.
References joker, and mdata.
Referenced by operator>>(), stepwise_source(), and test_r_deriv_propagationmatrix().
K24() [2/2]
ConstVectorView PropagationMatrix::K24 (const Index iz = 0, const Index ia = 0) const inline
Vector view to K(1, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(1, 3) elements
Definition at line 919 of file propagationmatrix.h.
References joker, and mdata.
K34() [1/2]
VectorView PropagationMatrix::K34 (const Index iz = 0, const Index ia = 0) inline
Vector view to K(2, 3) elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView K(2, 3) elements
Definition at line 859 of file propagationmatrix.h.
References joker, and mdata.
Referenced by ext_matTransform(), operator>>(), stepwise_source(), and test_r_deriv_propagationmatrix().
K34() [2/2]
ConstVectorView PropagationMatrix::K34 (const Index iz = 0, const Index ia = 0) const inline
Vector view to diagonal elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView Diagonal elements
Definition at line 929 of file propagationmatrix.h.
References joker, and mdata.
Kjj() [1/2]
VectorView PropagationMatrix::Kjj (const Index iz = 0, const Index ia = 0) inline
Vector view to diagonal elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView Diagonal elements
Definition at line 799 of file propagationmatrix.h.
References joker, and mdata.
Referenced by abs_vecTransform(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), dtransmat1(), dtransmat2(), dtransmat3(), dtransmat4(), ext_matTransform(), get_gasoptprop(), LeftMultiplyAtPosition(), MatrixInverseAtPosition(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), operator>>(), RightMultiplyAtPosition(), rte_step_doit_replacement(), RadiationVector::setSource(), stepwise_source(), test_r_deriv_propagationmatrix(), transmat1(), transmat2(), transmat3(), and transmat4().
Kjj() [2/2]
ConstVectorView PropagationMatrix::Kjj (const Index iz = 0, const Index ia = 0) const inline
Vector view to diagonal elements.
Parameters
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView Diagonal elements
Definition at line 869 of file propagationmatrix.h.
References joker, and mdata.
LeftMultiplyAtPosition()
void PropagationMatrix::LeftMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv = 0, const Index iz = 0, const Index ia = 0) const
Multiply the matrix input from the left of this at position.
Parameters
[in,out] out Outgoing matrix
[in] in Incoming matrix
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1707 of file propagationmatrix.cc.
References K12(), Kjj(), and mstokes_dim.
MatrixAtPosition()
void PropagationMatrix::MatrixAtPosition (MatrixView ret, const Index iv = 0, const Index iz = 0, const Index ia = 0) const
Sets the dense matrix.
Avoid using if possible.
Parameters
[in,out] Full propagation matrix
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1928 of file propagationmatrix.cc.
References mdata, and mstokes_dim.
Referenced by clear_rt_vars_at_gp(), cloud_fieldsCalc(), and cloudy_rt_vars_at_gp().
MatrixInverseAtPosition()
void PropagationMatrix::MatrixInverseAtPosition (MatrixView ret, const Index iv = 0, const Index iz = 0, const Index ia = 0) const
Return the matrix inverse at the position.
Parameters
[in,out] ret Inversed matrix
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1506 of file propagationmatrix.cc.
References a2, b2, K12(), Kjj(), and mstokes_dim.
Referenced by get_stepwise_effective_source(), and rte_step_doit_replacement().
MultiplyAndAdd()
void PropagationMatrix::MultiplyAndAdd (const Numeric x, const PropagationMatrix & y)
Multiply input by scalar and add to this.
Parameters
x scalar
y input
Definition at line 1631 of file propagationmatrix.cc.
References maa, and mza.
Referenced by operator+=(), and opt_prop_bulkCalc().
MultiplyAtPosition() [1/3]
void PropagationMatrix::MultiplyAtPosition (const Numeric & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Multiply operator at position.
Parameters
[in] other Multiply by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 567 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
MultiplyAtPosition() [2/3]
void PropagationMatrix::MultiplyAtPosition (const PropagationMatrix & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Multiply operator at position.
Parameters
[in] other Multiply by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 541 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
MultiplyAtPosition() [3/3]
void PropagationMatrix::MultiplyAtPosition (ConstMatrixView x, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Multiply operator at position.
Parameters
[in] other Multiply by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1871 of file propagationmatrix.cc.
References mdata, mstokes_dim, and ARTS::Var::x().
NumberOfAzimuthAngles()
Index PropagationMatrix::NumberOfAzimuthAngles () const inline
The number of azimuth angles of the propagation matrix.
Definition at line 210 of file propagationmatrix.h.
References maa.
Referenced by RadiationVector::setSource(), and StokesVector::StokesVector().
NumberOfFrequencies()
Index PropagationMatrix::NumberOfFrequencies () const inline
The number of frequencies of the propagation matrix.
Definition at line 204 of file propagationmatrix.h.
References mfreqs.
Referenced by abs_vecTransform(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), dtransmat1(), dtransmat2(), dtransmat3(), dtransmat4(), ext_matTransform(), get_stepwise_effective_source(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), get_stepwise_transmission_matrix(), rte_step_doit_replacement(), stepwise_source(), StokesVector::StokesVector(), transmat1(), transmat2(), transmat3(), transmat4(), and TransmissionMatrix::TransmissionMatrix().
NumberOfNeededVectors()
Index PropagationMatrix::NumberOfNeededVectors () const inline
The number of required vectors to fill this PropagationMatrix.
Definition at line 257 of file propagationmatrix.h.
References mstokes_dim, and mvectortype.
Referenced by OK(), operator*=(), operator+=(), operator-=(), operator/=(), and PropagationMatrix().
NumberOfZenithAngles()
Index PropagationMatrix::NumberOfZenithAngles () const inline
The number of zenith angles of the propagation matrix.
Definition at line 207 of file propagationmatrix.h.
References mza.
Referenced by RadiationVector::setSource(), and StokesVector::StokesVector().
OK()
bool PropagationMatrix::OK () const inline
Definition at line 212 of file propagationmatrix.h.
References maa, mdata, mfreqs, mza, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and NumberOfNeededVectors().
operator()()
Numeric PropagationMatrix::operator() (const Index iv = 0, const Index is1 = 0, const Index is2 = 0, const Index iz = 0, const Index ia = 0) const
access operator.
Please refrain from using this if possible since it copies
Definition at line 1953 of file propagationmatrix.cc.
References mdata, and mstokes_dim.
operator*=() [1/3]
PropagationMatrix& PropagationMatrix::operator*= (const Numeric & x) inline
Multiply operator.
Parameters
[in] other Multiply by other
Returns
PropagationMatrix& *this
Definition at line 529 of file propagationmatrix.h.
References mdata, and ARTS::Var::x().
operator*=() [2/3]
PropagationMatrix& PropagationMatrix::operator*= (const PropagationMatrix & other) inline
Multiply operator.
Parameters
[in] other Multiply by other
Returns
PropagationMatrix& *this
Definition at line 507 of file propagationmatrix.h.
References mdata.
operator*=() [3/3]
PropagationMatrix& PropagationMatrix::operator*= (ConstVectorView x) inline
Multiply operator.
Parameters
[in] other Multiply by other
Returns
PropagationMatrix& *this
Definition at line 517 of file propagationmatrix.h.
References mza, and NumberOfNeededVectors().
operator+=() [1/4]
PropagationMatrix& PropagationMatrix::operator+= (const LazyScale< PropagationMatrix > & lpms) inline
Addition operator.
Parameters
[in] other Addition by other
Returns
PropagationMatrix& *this
Definition at line 589 of file propagationmatrix.h.
References LazyScale< base >::bas, MultiplyAndAdd(), and LazyScale< base >::scale.
operator+=() [2/4]
PropagationMatrix& PropagationMatrix::operator+= (const Numeric & x) inline
Addition operator.
Parameters
[in] other Addition by other
Returns
PropagationMatrix& *this
Definition at line 611 of file propagationmatrix.h.
References mdata, and ARTS::Var::x().
operator+=() [3/4]
PropagationMatrix& PropagationMatrix::operator+= (const PropagationMatrix & other) inline
Addition operator.
Parameters
[in] other Addition by other
Returns
PropagationMatrix& *this
Definition at line 579 of file propagationmatrix.h.
References mdata.
operator+=() [4/4]
PropagationMatrix& PropagationMatrix::operator+= (ConstVectorView x) inline
Addition operator.
Parameters
[in] other Addition by other
Returns
PropagationMatrix& *this
Definition at line 599 of file propagationmatrix.h.
References mza, and NumberOfNeededVectors().
operator-=() [1/3]
PropagationMatrix& PropagationMatrix::operator-= (const Numeric & x) inline
Subtraction operator.
Parameters
[in] other Subtract by other
Returns
PropagationMatrix& *this
Definition at line 687 of file propagationmatrix.h.
References mdata, and ARTS::Var::x().
operator-=() [2/3]
PropagationMatrix& PropagationMatrix::operator-= (const PropagationMatrix & other) inline
Subtraction operator.
Parameters
[in] other Subtract by other
Returns
PropagationMatrix& *this
Definition at line 661 of file propagationmatrix.h.
References mdata.
operator-=() [3/3]
PropagationMatrix& PropagationMatrix::operator-= (ConstVectorView x) inline
Subtraction operator.
Parameters
[in] other Subtract by other
Returns
PropagationMatrix& *this
Definition at line 671 of file propagationmatrix.h.
References mza, and NumberOfNeededVectors().
operator/=() [1/3]
PropagationMatrix& PropagationMatrix::operator/= (const Numeric & x) inline
Divide operator.
Parameters
[in] other Divide by other
Returns
PropagationMatrix& *this
Definition at line 457 of file propagationmatrix.h.
References mdata, and ARTS::Var::x().
operator/=() [2/3]
PropagationMatrix& PropagationMatrix::operator/= (const PropagationMatrix & other) inline
Divide operator.
Parameters
[in] other Divide by other
Returns
PropagationMatrix& *this
Definition at line 431 of file propagationmatrix.h.
References mdata.
operator/=() [3/3]
PropagationMatrix& PropagationMatrix::operator/= (ConstVectorView x) inline
Divide operator.
Parameters
[in] other Divide by other
Returns
PropagationMatrix& *this
Definition at line 441 of file propagationmatrix.h.
References mza, and NumberOfNeededVectors().
operator=() [1/4]
PropagationMatrix& PropagationMatrix::operator= (const LazyScale< PropagationMatrix > & lpms) inline
Laze equal to opeartor.
Parameters
[in] lpms lazified propagation matrix
Returns
PropagationMatrix& *this
Definition at line 354 of file propagationmatrix.h.
References LazyScale< base >::bas, mdata, operator=(), and LazyScale< base >::scale.
operator=() [2/4]
PropagationMatrix& PropagationMatrix::operator= (const Numeric & x) inline
Sets all data to constant.
Parameters
[in] x new constant value
Returns
PropagationMatrix& *this
Definition at line 380 of file propagationmatrix.h.
References mdata, and ARTS::Var::x().
operator=() [3/4]
PropagationMatrix& PropagationMatrix::operator= (const PropagationMatrix & other) inline
Copy operator.
Parameters
[in] other PropagationMatrix to copy
Returns
PropagationMatrix& *this
Definition at line 365 of file propagationmatrix.h.
References maa, mdata, mfreqs, mstokes_dim, mvectortype, and mza.
operator=() [4/4]
PropagationMatrix& PropagationMatrix::operator= (PropagationMatrix && pm) inline noexcept
Move operator.
Parameters
[in] pm PropagationMatrix to move from
Returns
PropagationMatrix& *this
Definition at line 337 of file propagationmatrix.h.
References maa, mdata, mfreqs, mstokes_dim, mvectortype, and mza.
Referenced by operator=().
RemoveAtPosition() [1/3]
void PropagationMatrix::RemoveAtPosition (const Numeric & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Subtraction at position.
Parameters
[in] other Subtract by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 725 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
RemoveAtPosition() [2/3]
void PropagationMatrix::RemoveAtPosition (const PropagationMatrix & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Subtraction at position.
Parameters
[in] other Subtract by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 699 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
RemoveAtPosition() [3/3]
void PropagationMatrix::RemoveAtPosition (ConstMatrixView x, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Subtraction at position.
Parameters
[in] other Subtract by other
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1833 of file propagationmatrix.cc.
References mdata, mstokes_dim, and ARTS::Var::x().
RightMultiplyAtPosition()
void PropagationMatrix::RightMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv = 0, const Index iz = 0, const Index ia = 0) const
Multiply the matrix input from the right of this at position.
Parameters
[in,out] out Outgoing matrix
[in] in Incoming matrix
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1770 of file propagationmatrix.cc.
References K12(), Kjj(), and mstokes_dim.
SetAtPosition() [1/3]
void PropagationMatrix::SetAtPosition (const Numeric & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Set the At Position object.
Parameters
[in] x Object to set
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 419 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
SetAtPosition() [2/3]
void PropagationMatrix::SetAtPosition (const PropagationMatrix & x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Set the At Position object.
Parameters
[in] x Object to set
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 392 of file propagationmatrix.h.
References joker, mdata, and ARTS::Var::x().
Referenced by get_stepwise_scattersky_propmat().
SetAtPosition() [3/3]
void PropagationMatrix::SetAtPosition (ConstMatrixView x, const Index iv = 0, const Index iz = 0, const Index ia = 0)
Set the At Position object.
Parameters
[in] x Object to set
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1909 of file propagationmatrix.cc.
References mdata, mstokes_dim, and ARTS::Var::x().
SetFaraday()
void PropagationMatrix::SetFaraday (const Numeric & rot, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Sets the Faraday rotation to the PropagationMatrix at required position.
No vector function exists since rot is a function of frequency
Parameters
[in] rot rotation
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 313 of file propagationmatrix.h.
References mdata, and mstokes_dim.
SetVectorType()
void PropagationMatrix::SetVectorType (bool vectortype) inline
Set the Vector Type object.
Parameters
[in] vectortype True if this is a vector false if not
Definition at line 218 of file propagationmatrix.h.
References mvectortype.
SetZero()
void PropagationMatrix::SetZero () inline
Sets all data to zero.
Definition at line 934 of file propagationmatrix.h.
References mdata.
Referenced by abs_vecTransform(), ext_matTransform(), get_stepwise_clearsky_propmat(), and opt_prop_bulkCalc().
StokesDimensions()
Index PropagationMatrix::StokesDimensions () const inline
The stokes dimension of the propagation matrix.
Definition at line 201 of file propagationmatrix.h.
References mstokes_dim.
Referenced by abs_vecTransform(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), dtransmat(), ext_matTransform(), get_stepwise_effective_source(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), rte_step_doit_replacement(), StokesVector::StokesVector(), transmat(), and TransmissionMatrix::TransmissionMatrix().
Member Data Documentation
maa
Index PropagationMatrix::maa protected
Definition at line 973 of file propagationmatrix.h.
Referenced by IsEmpty(), MultiplyAndAdd(), StokesVector::MultiplyAndAdd(), NumberOfAzimuthAngles(), OK(), StokesVector::operator=(), operator=(), PropagationMatrix(), and StokesVector::StokesVector().
mdata
Tensor4 PropagationMatrix::mdata protected
Definition at line 974 of file propagationmatrix.h.
Referenced by AddAbsorptionVectorAtPosition(), AddAtPosition(), AddAverageAtPosition(), StokesVector::AddAverageAtPosition(), AddFaraday(), Data(), DivideAtPosition(), GetTensor3(), IsRotational(), IsZero(), K12(), K13(), K14(), K23(), K24(), K34(), Kjj(), MatrixAtPosition(), MultiplyAtPosition(), OK(), operator()(), operator*=(), operator+=(), StokesVector::operator+=(), operator-=(), operator/=(), StokesVector::operator=(), operator=(), PropagationMatrix(), RemoveAtPosition(), SetAtPosition(), StokesVector::SetAtPosition(), SetFaraday(), SetZero(), StokesVector::StokesVector(), and StokesVector::VectorAtPosition().
mfreqs
Index PropagationMatrix::mfreqs protected
Definition at line 972 of file propagationmatrix.h.
Referenced by IsEmpty(), StokesVector::MultiplyAndAdd(), NumberOfFrequencies(), OK(), StokesVector::operator=(), operator=(), PropagationMatrix(), and StokesVector::StokesVector().
mstokes_dim
Index PropagationMatrix::mstokes_dim protected
Definition at line 972 of file propagationmatrix.h.
Referenced by AddAbsorptionVectorAtPosition(), AddAtPosition(), AddAverageAtPosition(), StokesVector::AddAverageAtPosition(), AddFaraday(), DivideAtPosition(), FittingShape(), GetTensor3(), StokesVector::IsPolarized(), K23(), LeftMultiplyAtPosition(), MatrixAtPosition(), MatrixInverseAtPosition(), StokesVector::MultiplyAndAdd(), MultiplyAtPosition(), NumberOfNeededVectors(), StokesVector::NumberOfNeededVectors(), operator()(), StokesVector::operator+=(), StokesVector::operator=(), operator=(), PropagationMatrix(), RemoveAtPosition(), RightMultiplyAtPosition(), SetAtPosition(), SetFaraday(), StokesDimensions(), and StokesVector::StokesVector().
mvectortype
bool PropagationMatrix::mvectortype protected
Definition at line 975 of file propagationmatrix.h.
Referenced by NumberOfNeededVectors(), operator=(), PropagationMatrix(), SetVectorType(), and StokesVector::StokesVector().
mza
Index PropagationMatrix::mza protected
Definition at line 973 of file propagationmatrix.h.
Referenced by IsEmpty(), MultiplyAndAdd(), StokesVector::MultiplyAndAdd(), NumberOfZenithAngles(), OK(), operator*=(), operator+=(), operator-=(), operator/=(), StokesVector::operator=(), operator=(), PropagationMatrix(), and StokesVector::StokesVector().
The documentation for this class was generated from the following files:
propagationmatrix.h
propagationmatrix.cc