ARTS: StokesVector Class Reference
StokesVector Class Reference final
Stokes vector is as Propagation matrix but only has 4 possible values.
#include <propagationmatrix.h>
Public Member Functions
StokesVector (const Index nr_frequencies=0, const Index stokes_dim=1, const Index nr_za=1, const Index nr_aa=1, const Numeric &v=0.0)
Initialize variable sizes.
StokesVector (ConstTensor4View x)
Construct a new Propagation Matrix object.
StokesVector (ConstVectorView x)
Construct a new Stokes Vector object.
StokesVector (const StokesVector &a, const StokesVector &b, const Numeric &scale=0.5)
Construct a new Stokes Vector as a scale between two others.
Index NumberOfNeededVectors () const
The number of required vectors to fill this StokesVector.
StokesVector & operator+= (const PropagationMatrix &x)
Addition operator.
StokesVector & operator+= (const LazyScale< PropagationMatrix > &lpms)
Addition operator.
StokesVector & operator= (const PropagationMatrix &x)
Set *this from a Propagation matrix.
StokesVector & operator= (const LazyScale< PropagationMatrix > &lpms)
Set this lazily.
StokesVector & operator= (const Numeric &x)
Set this to constant value.
void MultiplyAndAdd (const Numeric x, const PropagationMatrix &y)
Add a scaled version of the input.
VectorView VectorAtPosition (const Index iv=0, const Index iz=0, const Index ia=0)
Get a vectorview to the position.
ConstVectorView VectorAtPosition (const Index iv=0, const Index iz=0, const Index ia=0) const
Get a vectorview to the position.
void SetAtPosition (ConstVectorView x, const Index iv=0, const Index iz=0, const Index ia=0)
void AddAverageAtPosition (ConstVectorView vec1, ConstVectorView vec2, const Index iv=0, const Index iz=0, const Index ia=0)
Add the average of both inputs at position.
bool IsPolarized (const Index iv=0, const Index iz=0, const Index ia=0) const
Checks if vector is polarized.
bool IsUnpolarized (const Index iv=0, const Index iz=0, const Index ia=0) const
Checks if vector is polarized.
bool allZeroes () const
Public Member Functions inherited from PropagationMatrix
PropagationMatrix (const Index nr_frequencies=0, const Index stokes_dim=1, const Index nr_za=1, const Index nr_aa=1, const Numeric v=0.0)
Initialize variable sizes.
PropagationMatrix (const PropagationMatrix &pm)
Construct a new Propagation Matrix object.
PropagationMatrix (PropagationMatrix &&pm) noexcept
Construct a new Propagation Matrix object.
PropagationMatrix (ConstTensor4View x)
Construct a new Propagation Matrix object.
PropagationMatrix (ConstMatrixView x, const bool &assume_fit=false)
Initialize from single stokes_dim-by-stokes_dim matrix.
Index StokesDimensions () const
The stokes dimension of the propagation matrix.
Index NumberOfFrequencies () const
The number of frequencies of the propagation matrix.
Index NumberOfZenithAngles () const
The number of zenith angles of the propagation matrix.
Index NumberOfAzimuthAngles () const
The number of azimuth angles of the propagation matrix.
bool OK () const
bool IsEmpty () const
Asks if the class is empty.
bool IsZero (const Index iv=0, const Index iz=0, const Index ia=0) const
False if any non-zeroes in internal Matrix representation.
bool IsRotational (const Index iv=0, const Index iz=0, const Index ia=0) const
False if diagonal element is non-zero in internal Matrix representation.
Index NumberOfNeededVectors () const
The number of required vectors to fill this PropagationMatrix.
Numeric operator() (const Index iv=0, const Index is1=0, const Index is2=0, const Index iz=0, const Index ia=0) const
access operator.
void AddFaraday (const Numeric &rot, const Index iv=0, const Index iz=0, const Index ia=0)
Adds the Faraday rotation to the PropagationMatrix at required position.
void SetFaraday (const Numeric &rot, const Index iv=0, const Index iz=0, const Index ia=0)
Sets the Faraday rotation to the PropagationMatrix at required position.
void MatrixAtPosition (MatrixView ret, const Index iv=0, const Index iz=0, const Index ia=0) const
Sets the dense matrix.
PropagationMatrix & operator= (PropagationMatrix &&pm) noexcept
Move operator.
PropagationMatrix & operator= (const LazyScale< PropagationMatrix > &lpms)
Laze equal to opeartor.
PropagationMatrix & operator= (const PropagationMatrix &other)
Copy operator.
PropagationMatrix & operator= (const Numeric &x)
Sets all data to constant.
void SetAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
void SetAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
void SetAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Set the At Position object.
PropagationMatrix & operator/= (const PropagationMatrix &other)
Divide operator.
PropagationMatrix & operator/= (ConstVectorView x)
Divide operator.
PropagationMatrix & operator/= (const Numeric &x)
Divide operator.
void DivideAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
void DivideAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
void DivideAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Divide at position.
PropagationMatrix & operator*= (const PropagationMatrix &other)
Multiply operator.
PropagationMatrix & operator*= (ConstVectorView x)
Multiply operator.
PropagationMatrix & operator*= (const Numeric &x)
Multiply operator.
void MultiplyAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
void MultiplyAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
void MultiplyAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Multiply operator at position.
PropagationMatrix & operator+= (const PropagationMatrix &other)
Addition operator.
PropagationMatrix & operator+= (const LazyScale< PropagationMatrix > &lpms)
Addition operator.
PropagationMatrix & operator+= (ConstVectorView x)
Addition operator.
PropagationMatrix & operator+= (const Numeric &x)
Addition operator.
void AddAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
void AddAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
void AddAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Addition at position operator.
PropagationMatrix & operator-= (const PropagationMatrix &other)
Subtraction operator.
PropagationMatrix & operator-= (ConstVectorView x)
Subtraction operator.
PropagationMatrix & operator-= (const Numeric &x)
Subtraction operator.
void RemoveAtPosition (const PropagationMatrix &x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void RemoveAtPosition (ConstMatrixView x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void RemoveAtPosition (const Numeric &x, const Index iv=0, const Index iz=0, const Index ia=0)
Subtraction at position.
void AddAbsorptionVectorAtPosition (ConstVectorView x, const Index iv=0, const Index iz=0, const Index ia=0)
Adds as a Stokes vector at position.
void AddAverageAtPosition (ConstMatrixView mat1, ConstMatrixView mat2, const Index iv=0, const Index iz=0, const Index ia=0)
Add the average of the two input at position.
void MultiplyAndAdd (const Numeric x, const PropagationMatrix &y)
Multiply input by scalar and add to this.
void MatrixInverseAtPosition (MatrixView ret, const Index iv=0, const Index iz=0, const Index ia=0) const
Return the matrix inverse at the position.
bool FittingShape (ConstMatrixView x) const
Tests of the input matrix fits Propagation Matrix style.
void GetTensor3 (Tensor3View tensor3, const Index iz=0, const Index ia=0)
Get a Tensor3 object from this.
VectorView Kjj (const Index iz=0, const Index ia=0)
Vector view to diagonal elements.
VectorView K12 (const Index iz=0, const Index ia=0)
Vector view to K(0, 1) elements.
VectorView K13 (const Index iz=0, const Index ia=0)
Vector view to K(0, 2) elements.
VectorView K14 (const Index iz=0, const Index ia=0)
Vector view to K(0, 3) elements.
VectorView K23 (const Index iz=0, const Index ia=0)
Vector view to K(1, 2) elements.
VectorView K24 (const Index iz=0, const Index ia=0)
Vector view to K(1, 3) elements.
VectorView K34 (const Index iz=0, const Index ia=0)
Vector view to K(2, 3) elements.
ConstVectorView Kjj (const Index iz=0, const Index ia=0) const
Vector view to diagonal elements.
ConstVectorView K12 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 1) elements.
ConstVectorView K13 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 2) elements.
ConstVectorView K14 (const Index iz=0, const Index ia=0) const
Vector view to K(0, 3) elements.
ConstVectorView K23 (const Index iz=0, const Index ia=0) const
Vector view to K(1, 3) elements.
ConstVectorView K24 (const Index iz=0, const Index ia=0) const
Vector view to K(1, 3) elements.
ConstVectorView K34 (const Index iz=0, const Index ia=0) const
Vector view to diagonal elements.
void SetZero ()
Sets all data to zero.
Tensor4 & Data ()
Get full view to data.
const Tensor4 & Data () const
Get full const view to data.
void LeftMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv=0, const Index iz=0, const Index ia=0) const
Multiply the matrix input from the left of this at position.
void RightMultiplyAtPosition (MatrixView out, ConstMatrixView in, const Index iv=0, const Index iz=0, const Index ia=0) const
Multiply the matrix input from the right of this at position.
Additional Inherited Members
Protected Attributes inherited from PropagationMatrix
Index mfreqs
Index mstokes_dim
Index mza
Index maa
Tensor4 mdata
bool mvectortype
Detailed Description
Stokes vector is as Propagation matrix but only has 4 possible values.
Definition at line 1201 of file propagationmatrix.h.
Constructor & Destructor Documentation
StokesVector() [1/4]
StokesVector::StokesVector (const Index nr_frequencies = 0, const Index stokes_dim = 1, const Index nr_za = 1, const Index nr_aa = 1, const Numeric & v = 0.0) inline
Initialize variable sizes.
Will create a Tensor4 of the size and order (nr_aa, nr_za, NumberOfNeededVectors(), nr_frequencies)
Parameters
[in] nr_frequencies Number of Dirac frequencies
[in] stokes_dim Stokes dimensionality
[in] nr_za Number of Dirac Zeniths
[in] nr_aa Number of Dirac Azimuths
[in] v Initial values of things in the created Tensor4
Definition at line 1215 of file propagationmatrix.h.
References ARTS_ASSERT, PropagationMatrix::maa, PropagationMatrix::mdata, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mvectortype, PropagationMatrix::mza, ARTS::Var::stokes_dim(), and v.
StokesVector() [2/4]
StokesVector::StokesVector (ConstTensor4View x) inline explicit
Construct a new Propagation Matrix object.
Parameters
[in] x Tensor4 object to use to initialize from
Definition at line 1233 of file propagationmatrix.h.
References ARTS_ASSERT, PropagationMatrix::maa, PropagationMatrix::mdata, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mvectortype, PropagationMatrix::mza, and ARTS::Var::x().
StokesVector() [3/4]
StokesVector::StokesVector (ConstVectorView x) inline explicit
Construct a new Stokes Vector object.
Parameters
x Single Stokes vector
Definition at line 1248 of file propagationmatrix.h.
References ARTS_ASSERT, PropagationMatrix::maa, PropagationMatrix::mdata, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mvectortype, PropagationMatrix::mza, Tensor4::resize(), and ARTS::Var::x().
StokesVector() [4/4]
StokesVector::StokesVector (const StokesVector & a, const StokesVector & b, const Numeric & scale = 0.5) inline
Construct a new Stokes Vector as a scale between two others.
Parameters
a input 1
b input 2
scale Scale of inputs
Definition at line 1265 of file propagationmatrix.h.
References a, PropagationMatrix::maa, PropagationMatrix::mdata, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mvectortype, PropagationMatrix::mza, and Tensor4::resize().
Member Function Documentation
AddAverageAtPosition()
void StokesVector::AddAverageAtPosition (ConstVectorView vec1, ConstVectorView vec2, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Add the average of both inputs at position.
Parameters
[in] vec1 input 1
[in] vec2 input 2
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 1426 of file propagationmatrix.h.
References PropagationMatrix::mdata, and PropagationMatrix::mstokes_dim.
allZeroes()
bool StokesVector::allZeroes () const inline
Definition at line 1479 of file propagationmatrix.h.
References PropagationMatrix::maa, and PropagationMatrix::mza.
Referenced by get_stepwise_clearsky_propmat().
IsPolarized()
bool StokesVector::IsPolarized (const Index iv = 0, const Index iz = 0, const Index ia = 0) const inline
Checks if vector is polarized.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
true if polarized
false if not polarized
Definition at line 1451 of file propagationmatrix.h.
References PropagationMatrix::K12(), PropagationMatrix::K13(), PropagationMatrix::K14(), and PropagationMatrix::mstokes_dim.
Referenced by IsUnpolarized().
IsUnpolarized()
bool StokesVector::IsUnpolarized (const Index iv = 0, const Index iz = 0, const Index ia = 0) const inline
Checks if vector is polarized.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
true if not polarized
false if polarized
Definition at line 1473 of file propagationmatrix.h.
References IsPolarized().
MultiplyAndAdd()
void StokesVector::MultiplyAndAdd (const Numeric x, const PropagationMatrix & y) inline
Add a scaled version of the input.
Parameters
[in] x Scale
[in] y Input
Definition at line 1359 of file propagationmatrix.h.
References ARTS_ASSERT, data, PropagationMatrix::maa, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mza, and ARTS::Var::y().
Referenced by operator+=(), and opt_prop_bulkCalc().
NumberOfNeededVectors()
Index StokesVector::NumberOfNeededVectors () const inline
The number of required vectors to fill this StokesVector.
Definition at line 1296 of file propagationmatrix.h.
References PropagationMatrix::mstokes_dim.
operator+=() [1/2]
StokesVector& StokesVector::operator+= (const LazyScale< PropagationMatrix > & lpms) inline
Addition operator.
Parameters
x Lazy addition
Returns
StokesVector& *this
Definition at line 1313 of file propagationmatrix.h.
References LazyScale< base >::bas, MultiplyAndAdd(), and LazyScale< base >::scale.
operator+=() [2/2]
StokesVector& StokesVector::operator+= (const PropagationMatrix & x) inline
Addition operator.
Parameters
x Stokes Vector or Propagation Matrix to add
Returns
StokesVector& *this
Definition at line 1303 of file propagationmatrix.h.
References joker, PropagationMatrix::mdata, PropagationMatrix::mstokes_dim, and ARTS::Var::x().
operator=() [1/3]
StokesVector& StokesVector::operator= (const LazyScale< PropagationMatrix > & lpms) inline
Set this lazily.
Parameters
[in] lpms Lazy propagation matrix
Returns
StokesVector& *this
Definition at line 1338 of file propagationmatrix.h.
References LazyScale< base >::bas, PropagationMatrix::mdata, operator=(), and LazyScale< base >::scale.
operator=() [2/3]
StokesVector& StokesVector::operator= (const Numeric & x) inline
Set this to constant value.
Parameters
[in] x constant value
Returns
StokesVector& *this
Definition at line 1349 of file propagationmatrix.h.
References PropagationMatrix::mdata, and ARTS::Var::x().
operator=() [3/3]
StokesVector& StokesVector::operator= (const PropagationMatrix & x) inline
Set *this from a Propagation matrix.
Parameters
x Propagation matrix
Returns
StokesVector& *this
Definition at line 1323 of file propagationmatrix.h.
References joker, PropagationMatrix::maa, PropagationMatrix::mdata, PropagationMatrix::mfreqs, PropagationMatrix::mstokes_dim, PropagationMatrix::mza, Tensor4::resize(), and ARTS::Var::x().
Referenced by operator=().
SetAtPosition()
void StokesVector::SetAtPosition (ConstVectorView x, const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Definition at line 1411 of file propagationmatrix.h.
References joker, PropagationMatrix::mdata, and ARTS::Var::x().
Referenced by get_stepwise_scattersky_propmat(), and get_stepwise_scattersky_source().
VectorAtPosition() [1/2]
VectorView StokesVector::VectorAtPosition (const Index iv = 0, const Index iz = 0, const Index ia = 0) inline
Get a vectorview to the position.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView To StokesVector
Definition at line 1392 of file propagationmatrix.h.
References joker, and PropagationMatrix::mdata.
Referenced by clear_rt_vars_at_gp(), cloud_fieldsCalc(), cloudy_rt_vars_at_gp(), get_stepwise_effective_source(), and rte_step_doit_replacement().
VectorAtPosition() [2/2]
ConstVectorView StokesVector::VectorAtPosition (const Index iv = 0, const Index iz = 0, const Index ia = 0) const inline
Get a vectorview to the position.
Parameters
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Returns
VectorView To StokesVector
Definition at line 1405 of file propagationmatrix.h.
References joker, and PropagationMatrix::mdata.
The documentation for this class was generated from the following file:
propagationmatrix.h