ARTS: ARTS::Var::WorkspaceGasAbsLookup Class Reference
ARTS::Var::WorkspaceGasAbsLookup Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceGasAbsLookup () noexcept
WorkspaceGasAbsLookup (std::size_t i, void *x) noexcept
~WorkspaceGasAbsLookup () noexcept
WorkspaceGasAbsLookup (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceGasAbsLookup & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::GasAbsLookup
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1052 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceGasAbsLookup::type = Group::GasAbsLookup private
Definition at line 1053 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceGasAbsLookup() [1/3]
ARTS::Var::WorkspaceGasAbsLookup::WorkspaceGasAbsLookup () inline noexcept
Definition at line 1057 of file autoarts.h.
WorkspaceGasAbsLookup() [2/3]
ARTS::Var::WorkspaceGasAbsLookup::WorkspaceGasAbsLookup (std::size_t i, void * x) inline noexcept
Definition at line 1058 of file autoarts.h.
~WorkspaceGasAbsLookup()
ARTS::Var::WorkspaceGasAbsLookup::~WorkspaceGasAbsLookup () inline noexcept
Definition at line 1059 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceGasAbsLookup() [3/3]
ARTS::Var::WorkspaceGasAbsLookup::WorkspaceGasAbsLookup (const type & val) inline noexcept
Definition at line 1060 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceGasAbsLookup::islast () const inline noexcept
Definition at line 1066 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceGasAbsLookup().
isnull()
bool ARTS::Var::WorkspaceGasAbsLookup::isnull () const inline noexcept
Definition at line 1065 of file autoarts.h.
References v.
Referenced by ~WorkspaceGasAbsLookup().
name()
const Group::String& ARTS::Var::WorkspaceGasAbsLookup::name () const inline noexcept
Definition at line 1067 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceGasAbsLookup& ARTS::Var::WorkspaceGasAbsLookup::operator= (const type & t) inline noexcept
Definition at line 1063 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceGasAbsLookup::pos () const inline noexcept
Definition at line 1064 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::ReadNetCDF(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceGasAbsLookup::value () const inline noexcept
Definition at line 1062 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceGasAbsLookup::value () inline noexcept
Definition at line 1061 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), ARTS::Method::ReadNetCDF(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceGasAbsLookup::p private
Definition at line 1054 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceGasAbsLookup::v private
Definition at line 1055 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceGasAbsLookup().
The documentation for this class was generated from the following file:
autoarts.h