ARTS: ARTS::Var::WorkspaceArrayOfGriddedField4 Class Reference
ARTS::Var::WorkspaceArrayOfGriddedField4 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfGriddedField4 () noexcept
WorkspaceArrayOfGriddedField4 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfGriddedField4 () noexcept
WorkspaceArrayOfGriddedField4 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfGriddedField4 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfGriddedField4
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 584 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfGriddedField4::type = Group::ArrayOfGriddedField4 private
Definition at line 585 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfGriddedField4() [1/3]
ARTS::Var::WorkspaceArrayOfGriddedField4::WorkspaceArrayOfGriddedField4 () inline noexcept
Definition at line 589 of file autoarts.h.
WorkspaceArrayOfGriddedField4() [2/3]
ARTS::Var::WorkspaceArrayOfGriddedField4::WorkspaceArrayOfGriddedField4 (std::size_t i, void * x) inline noexcept
Definition at line 590 of file autoarts.h.
~WorkspaceArrayOfGriddedField4()
ARTS::Var::WorkspaceArrayOfGriddedField4::~WorkspaceArrayOfGriddedField4 () inline noexcept
Definition at line 591 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfGriddedField4() [3/3]
ARTS::Var::WorkspaceArrayOfGriddedField4::WorkspaceArrayOfGriddedField4 (const type & val) inline noexcept
Definition at line 592 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfGriddedField4::islast () const inline noexcept
Definition at line 598 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfGriddedField4().
isnull()
bool ARTS::Var::WorkspaceArrayOfGriddedField4::isnull () const inline noexcept
Definition at line 597 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfGriddedField4().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfGriddedField4::name () const inline noexcept
Definition at line 599 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfGriddedField4& ARTS::Var::WorkspaceArrayOfGriddedField4::operator= (const type & t) inline noexcept
Definition at line 595 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField4::pos () const inline noexcept
Definition at line 596 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::ArrayOfGriddedFieldGetNames(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfGriddedField4::value () const inline noexcept
Definition at line 594 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfGriddedField4::value () inline noexcept
Definition at line 593 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfGriddedField4::p private
Definition at line 586 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfGriddedField4::v private
Definition at line 587 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfGriddedField4().
The documentation for this class was generated from the following file:
autoarts.h