ARTS: ARTS::Var::ArrayOfArrayOfStokesVector Class Reference
ARTS::Var::ArrayOfArrayOfStokesVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfStokesVector () noexcept
ArrayOfArrayOfStokesVector (std::size_t i, void *x) noexcept
ArrayOfArrayOfStokesVector (const Group::ArrayOfArrayOfStokesVector &val) noexcept
~ArrayOfArrayOfStokesVector () noexcept
Group::ArrayOfArrayOfStokesVector & value () noexcept
const Group::ArrayOfArrayOfStokesVector & value () const noexcept
ArrayOfArrayOfStokesVector & operator= (const Group::ArrayOfArrayOfStokesVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfStokesVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfStokesVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1029 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfStokesVector() [1/3]
ARTS::Var::ArrayOfArrayOfStokesVector::ArrayOfArrayOfStokesVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1034 of file autoarts.h.
ArrayOfArrayOfStokesVector() [2/3]
ARTS::Var::ArrayOfArrayOfStokesVector::ArrayOfArrayOfStokesVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1037 of file autoarts.h.
ArrayOfArrayOfStokesVector() [3/3]
ARTS::Var::ArrayOfArrayOfStokesVector::ArrayOfArrayOfStokesVector (const Group::ArrayOfArrayOfStokesVector & val) inline noexcept
Construct from Group::ArrayOfArrayOfStokesVector. Leaves islast() true and isnull() false
Definition at line 1040 of file autoarts.h.
~ArrayOfArrayOfStokesVector()
ARTS::Var::ArrayOfArrayOfStokesVector::~ArrayOfArrayOfStokesVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1043 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfStokesVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1061 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfArrayOfStokesVector().
isnull()
bool ARTS::Var::ArrayOfArrayOfStokesVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 1058 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfStokesVector().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfStokesVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1064 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfStokesVector& ARTS::Var::ArrayOfArrayOfStokesVector::operator= (const Group::ArrayOfArrayOfStokesVector & t) inline noexcept
Set value from Group::ArrayOfArrayOfStokesVector. Works when isnull() is false
Definition at line 1052 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfStokesVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1055 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfArrayOfStokesVector& ARTS::Var::ArrayOfArrayOfStokesVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfStokesVector. Works when isnull() is false
Definition at line 1049 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfStokesVector& ARTS::Var::ArrayOfArrayOfStokesVector::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfStokesVector. Works when isnull() is false
Definition at line 1046 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfStokesVector & var) friend
Output to stream of internal variable
Definition at line 1067 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfStokesVector::p private
Definition at line 1030 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfStokesVector* ARTS::Var::ArrayOfArrayOfStokesVector::v private
Definition at line 1031 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfStokesVector().
The documentation for this class was generated from the following file:
autoarts.h