ARTS: ARTS::Var::WorkspaceArrayOfIndex Class Reference
ARTS::Var::WorkspaceArrayOfIndex Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfIndex () noexcept
WorkspaceArrayOfIndex (std::size_t i, void *x) noexcept
~WorkspaceArrayOfIndex () noexcept
WorkspaceArrayOfIndex (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfIndex & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfIndex
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 602 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfIndex::type = Group::ArrayOfIndex private
Definition at line 603 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfIndex() [1/3]
ARTS::Var::WorkspaceArrayOfIndex::WorkspaceArrayOfIndex () inline noexcept
Definition at line 607 of file autoarts.h.
WorkspaceArrayOfIndex() [2/3]
ARTS::Var::WorkspaceArrayOfIndex::WorkspaceArrayOfIndex (std::size_t i, void * x) inline noexcept
Definition at line 608 of file autoarts.h.
~WorkspaceArrayOfIndex()
ARTS::Var::WorkspaceArrayOfIndex::~WorkspaceArrayOfIndex () inline noexcept
Definition at line 609 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfIndex() [3/3]
ARTS::Var::WorkspaceArrayOfIndex::WorkspaceArrayOfIndex (const type & val) inline noexcept
Definition at line 610 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfIndex::islast () const inline noexcept
Definition at line 616 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSet(), ARTS::AgendaMethod::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfIndex().
isnull()
bool ARTS::Var::WorkspaceArrayOfIndex::isnull () const inline noexcept
Definition at line 615 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfIndex().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfIndex::name () const inline noexcept
Definition at line 617 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfIndex& ARTS::Var::WorkspaceArrayOfIndex::operator= (const type & t) inline noexcept
Definition at line 613 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfIndex::pos () const inline noexcept
Definition at line 614 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSet(), ARTS::AgendaMethod::ArrayOfIndexSetConstant(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfIndex::value () const inline noexcept
Definition at line 612 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfIndex::value () inline noexcept
Definition at line 611 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfIndexLinSpace(), ARTS::AgendaMethod::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfIndex::p private
Definition at line 604 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfIndex::v private
Definition at line 605 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfIndex().
The documentation for this class was generated from the following file:
autoarts.h