ARTS: ARTS::Var::WorkspaceArrayOfScatteringMetaData Class Reference
ARTS::Var::WorkspaceArrayOfScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfScatteringMetaData () noexcept
WorkspaceArrayOfScatteringMetaData (std::size_t i, void *x) noexcept
~WorkspaceArrayOfScatteringMetaData () noexcept
WorkspaceArrayOfScatteringMetaData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfScatteringMetaData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfScatteringMetaData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 728 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfScatteringMetaData::type = Group::ArrayOfScatteringMetaData private
Definition at line 729 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfScatteringMetaData() [1/3]
ARTS::Var::WorkspaceArrayOfScatteringMetaData::WorkspaceArrayOfScatteringMetaData () inline noexcept
Definition at line 733 of file autoarts.h.
WorkspaceArrayOfScatteringMetaData() [2/3]
ARTS::Var::WorkspaceArrayOfScatteringMetaData::WorkspaceArrayOfScatteringMetaData (std::size_t i, void * x) inline noexcept
Definition at line 734 of file autoarts.h.
~WorkspaceArrayOfScatteringMetaData()
ARTS::Var::WorkspaceArrayOfScatteringMetaData::~WorkspaceArrayOfScatteringMetaData () inline noexcept
Definition at line 735 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfScatteringMetaData() [3/3]
ARTS::Var::WorkspaceArrayOfScatteringMetaData::WorkspaceArrayOfScatteringMetaData (const type & val) inline noexcept
Definition at line 736 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfScatteringMetaData::islast () const inline noexcept
Definition at line 742 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfScatteringMetaData().
isnull()
bool ARTS::Var::WorkspaceArrayOfScatteringMetaData::isnull () const inline noexcept
Definition at line 741 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfScatteringMetaData().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfScatteringMetaData::name () const inline noexcept
Definition at line 743 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfScatteringMetaData& ARTS::Var::WorkspaceArrayOfScatteringMetaData::operator= (const type & t) inline noexcept
Definition at line 739 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfScatteringMetaData::pos () const inline noexcept
Definition at line 740 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfScatteringMetaData::value () const inline noexcept
Definition at line 738 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfScatteringMetaData::value () inline noexcept
Definition at line 737 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfScatteringMetaData::p private
Definition at line 730 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfScatteringMetaData::v private
Definition at line 731 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h