ARTS: ARTS::Var::WorkspaceHitranRelaxationMatrixData Class Reference
ARTS::Var::WorkspaceHitranRelaxationMatrixData Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceHitranRelaxationMatrixData () noexcept
WorkspaceHitranRelaxationMatrixData (std::size_t i, void *x) noexcept
~WorkspaceHitranRelaxationMatrixData () noexcept
WorkspaceHitranRelaxationMatrixData (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceHitranRelaxationMatrixData & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::HitranRelaxationMatrixData
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1196 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceHitranRelaxationMatrixData::type = Group::HitranRelaxationMatrixData private
Definition at line 1197 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceHitranRelaxationMatrixData() [1/3]
ARTS::Var::WorkspaceHitranRelaxationMatrixData::WorkspaceHitranRelaxationMatrixData () inline noexcept
Definition at line 1201 of file autoarts.h.
WorkspaceHitranRelaxationMatrixData() [2/3]
ARTS::Var::WorkspaceHitranRelaxationMatrixData::WorkspaceHitranRelaxationMatrixData (std::size_t i, void * x) inline noexcept
Definition at line 1202 of file autoarts.h.
~WorkspaceHitranRelaxationMatrixData()
ARTS::Var::WorkspaceHitranRelaxationMatrixData::~WorkspaceHitranRelaxationMatrixData () inline noexcept
Definition at line 1203 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceHitranRelaxationMatrixData() [3/3]
ARTS::Var::WorkspaceHitranRelaxationMatrixData::WorkspaceHitranRelaxationMatrixData (const type & val) inline noexcept
Definition at line 1204 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceHitranRelaxationMatrixData::islast () const inline noexcept
Definition at line 1210 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceHitranRelaxationMatrixData().
isnull()
bool ARTS::Var::WorkspaceHitranRelaxationMatrixData::isnull () const inline noexcept
Definition at line 1209 of file autoarts.h.
References v.
Referenced by ~WorkspaceHitranRelaxationMatrixData().
name()
const Group::String& ARTS::Var::WorkspaceHitranRelaxationMatrixData::name () const inline noexcept
Definition at line 1211 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceHitranRelaxationMatrixData& ARTS::Var::WorkspaceHitranRelaxationMatrixData::operator= (const type & t) inline noexcept
Definition at line 1207 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceHitranRelaxationMatrixData::pos () const inline noexcept
Definition at line 1208 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceHitranRelaxationMatrixData::value () const inline noexcept
Definition at line 1206 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceHitranRelaxationMatrixData::value () inline noexcept
Definition at line 1205 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceHitranRelaxationMatrixData::p private
Definition at line 1198 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceHitranRelaxationMatrixData::v private
Definition at line 1199 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceHitranRelaxationMatrixData().
The documentation for this class was generated from the following file:
autoarts.h