ARTS: ARTS::Var::WorkspaceArrayOfQuantumIdentifier Class Reference
ARTS::Var::WorkspaceArrayOfQuantumIdentifier Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfQuantumIdentifier () noexcept
WorkspaceArrayOfQuantumIdentifier (std::size_t i, void *x) noexcept
~WorkspaceArrayOfQuantumIdentifier () noexcept
WorkspaceArrayOfQuantumIdentifier (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfQuantumIdentifier & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfQuantumIdentifier
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 674 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfQuantumIdentifier::type = Group::ArrayOfQuantumIdentifier private
Definition at line 675 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfQuantumIdentifier() [1/3]
ARTS::Var::WorkspaceArrayOfQuantumIdentifier::WorkspaceArrayOfQuantumIdentifier () inline noexcept
Definition at line 679 of file autoarts.h.
WorkspaceArrayOfQuantumIdentifier() [2/3]
ARTS::Var::WorkspaceArrayOfQuantumIdentifier::WorkspaceArrayOfQuantumIdentifier (std::size_t i, void * x) inline noexcept
Definition at line 680 of file autoarts.h.
~WorkspaceArrayOfQuantumIdentifier()
ARTS::Var::WorkspaceArrayOfQuantumIdentifier::~WorkspaceArrayOfQuantumIdentifier () inline noexcept
Definition at line 681 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfQuantumIdentifier() [3/3]
ARTS::Var::WorkspaceArrayOfQuantumIdentifier::WorkspaceArrayOfQuantumIdentifier (const type & val) inline noexcept
Definition at line 682 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfQuantumIdentifier::islast () const inline noexcept
Definition at line 688 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameters(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameters(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::retrievalAddCatalogParameters(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfQuantumIdentifier().
isnull()
bool ARTS::Var::WorkspaceArrayOfQuantumIdentifier::isnull () const inline noexcept
Definition at line 687 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfQuantumIdentifier().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfQuantumIdentifier::name () const inline noexcept
Definition at line 689 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfQuantumIdentifier& ARTS::Var::WorkspaceArrayOfQuantumIdentifier::operator= (const type & t) inline noexcept
Definition at line 685 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfQuantumIdentifier::pos () const inline noexcept
Definition at line 686 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::abs_linesSetBaseParameterForMatchingLevels(), ARTS::AgendaMethod::ArrayOfQuantumIdentifierSet(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::jacobianAddBasicCatalogParameters(), ARTS::AgendaMethod::jacobianAddShapeCatalogParameters(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::retrievalAddCatalogParameters(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfQuantumIdentifier::value () const inline noexcept
Definition at line 684 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfQuantumIdentifier::value () inline noexcept
Definition at line 683 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::retrievalAddCatalogParameters(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfQuantumIdentifier::p private
Definition at line 676 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfQuantumIdentifier::v private
Definition at line 677 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfQuantumIdentifier().
The documentation for this class was generated from the following file:
autoarts.h