ARTS: ARTS::Var::WorkspaceTensor3 Class Reference
ARTS::Var::WorkspaceTensor3 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTensor3 () noexcept
WorkspaceTensor3 (std::size_t i, void *x) noexcept
~WorkspaceTensor3 () noexcept
WorkspaceTensor3 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTensor3 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Tensor3
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1502 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTensor3::type = Group::Tensor3 private
Definition at line 1503 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTensor3() [1/3]
ARTS::Var::WorkspaceTensor3::WorkspaceTensor3 () inline noexcept
Definition at line 1507 of file autoarts.h.
WorkspaceTensor3() [2/3]
ARTS::Var::WorkspaceTensor3::WorkspaceTensor3 (std::size_t i, void * x) inline noexcept
Definition at line 1508 of file autoarts.h.
~WorkspaceTensor3()
ARTS::Var::WorkspaceTensor3::~WorkspaceTensor3 () inline noexcept
Definition at line 1509 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTensor3() [3/3]
ARTS::Var::WorkspaceTensor3::WorkspaceTensor3 (const type & val) inline noexcept
Definition at line 1510 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTensor3::islast () const inline noexcept
Definition at line 1516 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::Method::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpAtmFieldToPosition(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::Method::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::Method::Reduce(), ARTS::AgendaMethod::Tensor3AddScalar(), ARTS::Method::Tensor3AddScalar(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Tensor3Scale(), ARTS::Method::Tensor3Scale(), ARTS::AgendaMethod::Tensor3SetConstant(), ARTS::Method::Tensor3SetConstant(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTensor3().
isnull()
bool ARTS::Var::WorkspaceTensor3::isnull () const inline noexcept
Definition at line 1515 of file autoarts.h.
References v.
Referenced by ~WorkspaceTensor3().
name()
const Group::String& ARTS::Var::WorkspaceTensor3::name () const inline noexcept
Definition at line 1517 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), and ARTS::Method::ReadNetCDF().
operator=()
WorkspaceTensor3& ARTS::Var::WorkspaceTensor3::operator= (const type & t) inline noexcept
Definition at line 1513 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTensor3::pos () const inline noexcept
Definition at line 1514 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::FieldFromGriddedField(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::InterpAtmFieldToPosition(), ARTS::AgendaMethod::MatrixExtractFromTensor3(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::ReadNetCDF(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor3AddScalar(), ARTS::AgendaMethod::Tensor3ExtractFromTensor4(), ARTS::AgendaMethod::Tensor3Scale(), ARTS::AgendaMethod::Tensor3SetConstant(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTensor3::value () const inline noexcept
Definition at line 1512 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTensor3::value () inline noexcept
Definition at line 1511 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::ncolsGet(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Touch(), and ARTS::Method::VectorZtanToZaRefr1D().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTensor3::p private
Definition at line 1504 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTensor3::v private
Definition at line 1505 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTensor3().
The documentation for this class was generated from the following file:
autoarts.h