ARTS: ARTS::Var::Tensor4 Class Reference
ARTS::Var::Tensor4 Class Reference
#include <autoarts.h>
Public Member Functions
Tensor4 () noexcept
Tensor4 (std::size_t i, void *x) noexcept
Tensor4 (const Group::Tensor4 &val) noexcept
~Tensor4 () noexcept
Group::Tensor4 & value () noexcept
const Group::Tensor4 & value () const noexcept
Tensor4 & operator= (const Group::Tensor4 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Tensor4 * v
Friends
std::ostream & operator<< (std::ostream &os, const Tensor4 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4181 of file autoarts.h.
Constructor & Destructor Documentation
Tensor4() [1/3]
ARTS::Var::Tensor4::Tensor4 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4186 of file autoarts.h.
Tensor4() [2/3]
ARTS::Var::Tensor4::Tensor4 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4189 of file autoarts.h.
Tensor4() [3/3]
ARTS::Var::Tensor4::Tensor4 (const Group::Tensor4 & val) inline noexcept
Construct from Group::Tensor4. Leaves islast() true and isnull() false
Definition at line 4192 of file autoarts.h.
~Tensor4()
ARTS::Var::Tensor4::~Tensor4 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4195 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Tensor4::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4213 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Method::particle_fieldCleanup(), ARTS::Agenda::Method::particle_fieldCleanup(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Agenda::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor4AddScalar(), ARTS::Agenda::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Agenda::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Agenda::Method::Tensor4SetConstant(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Tensor4().
isnull()
bool ARTS::Var::Tensor4::isnull () const inline noexcept
Return true if there is no data
Definition at line 4210 of file autoarts.h.
References v.
Referenced by ~Tensor4().
name()
const Group::String& ARTS::Var::Tensor4::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4216 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
Tensor4& ARTS::Var::Tensor4::operator= (const Group::Tensor4 & t) inline noexcept
Set value from Group::Tensor4. Works when isnull() is false
Definition at line 4204 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Tensor4::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4207 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::particle_fieldCleanup(), ARTS::Agenda::Method::RadiationFieldSpectralIntegrate(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Agenda::Method::Tensor4AddScalar(), ARTS::Agenda::Method::Tensor4Scale(), ARTS::Agenda::Method::Tensor4SetConstant(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Tensor4& ARTS::Var::Tensor4::value () const inline noexcept
Get value const-ref as Group::Tensor4. Works when isnull() is false
Definition at line 4201 of file autoarts.h.
References v.
value() [2/2]
Group::Tensor4& ARTS::Var::Tensor4::value () inline noexcept
Get value ref as Group::Tensor4. Works when isnull() is false
Definition at line 4198 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Touch(), and ARTS::Method::VectorZtanToZaRefr1D().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Tensor4 & var) friend
Output to stream of internal variable
Definition at line 4219 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Tensor4::p private
Definition at line 4182 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Tensor4* ARTS::Var::Tensor4::v private
Definition at line 4183 of file autoarts.h.
Referenced by isnull(), value(), and ~Tensor4().
The documentation for this class was generated from the following file:
autoarts.h