ARTS: ARTS::Var::ArrayOfJacobianTarget Class Reference
ARTS::Var::ArrayOfJacobianTarget Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfJacobianTarget () noexcept
ArrayOfJacobianTarget (std::size_t i, void *x) noexcept
ArrayOfJacobianTarget (const Group::ArrayOfJacobianTarget &val) noexcept
~ArrayOfJacobianTarget () noexcept
Group::ArrayOfJacobianTarget & value () noexcept
const Group::ArrayOfJacobianTarget & value () const noexcept
ArrayOfJacobianTarget & operator= (const Group::ArrayOfJacobianTarget &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfJacobianTarget * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfJacobianTarget &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1640 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfJacobianTarget() [1/3]
ARTS::Var::ArrayOfJacobianTarget::ArrayOfJacobianTarget () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1645 of file autoarts.h.
ArrayOfJacobianTarget() [2/3]
ARTS::Var::ArrayOfJacobianTarget::ArrayOfJacobianTarget (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1648 of file autoarts.h.
ArrayOfJacobianTarget() [3/3]
ARTS::Var::ArrayOfJacobianTarget::ArrayOfJacobianTarget (const Group::ArrayOfJacobianTarget & val) inline noexcept
Construct from Group::ArrayOfJacobianTarget. Leaves islast() true and isnull() false
Definition at line 1651 of file autoarts.h.
~ArrayOfJacobianTarget()
ARTS::Var::ArrayOfJacobianTarget::~ArrayOfJacobianTarget () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1654 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfJacobianTarget::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1672 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfJacobianTarget().
isnull()
bool ARTS::Var::ArrayOfJacobianTarget::isnull () const inline noexcept
Return true if there is no data
Definition at line 1669 of file autoarts.h.
References v.
Referenced by ~ArrayOfJacobianTarget().
name()
const Group::String& ARTS::Var::ArrayOfJacobianTarget::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1675 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfJacobianTarget& ARTS::Var::ArrayOfJacobianTarget::operator= (const Group::ArrayOfJacobianTarget & t) inline noexcept
Set value from Group::ArrayOfJacobianTarget. Works when isnull() is false
Definition at line 1663 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfJacobianTarget::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1666 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfJacobianTarget& ARTS::Var::ArrayOfJacobianTarget::value () const inline noexcept
Get value const-ref as Group::ArrayOfJacobianTarget. Works when isnull() is false
Definition at line 1660 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfJacobianTarget& ARTS::Var::ArrayOfJacobianTarget::value () inline noexcept
Get value ref as Group::ArrayOfJacobianTarget. Works when isnull() is false
Definition at line 1657 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfJacobianTarget & var) friend
Output to stream of internal variable
Definition at line 1678 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfJacobianTarget::p private
Definition at line 1641 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfJacobianTarget* ARTS::Var::ArrayOfJacobianTarget::v private
Definition at line 1642 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfJacobianTarget().
The documentation for this class was generated from the following file:
autoarts.h