ARTS: Tensor7 Class Reference
Tensor7 Class Reference
The Tensor7 class.
#include <matpackVII.h>
Public Member Functions
Tensor7 ()=default
Tensor7 (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Constructor setting size.
Tensor7 (Index l, Index v, Index s, Index b, Index p, Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Tensor7 (const ConstTensor7View &v)
Copy constructor from Tensor7View.
Tensor7 (const Tensor7 &v)
Copy constructor from Tensor7.
Tensor7 (Tensor7 &&v) noexcept
Tensor7 & operator= (const Tensor7 &x)
Assignment operator from another tensor.
Tensor7 & operator= (Tensor7 &&x) noexcept
Copy assignment operator from another tensor.
Tensor7 & operator= (Numeric x)
Assignment operator from scalar.
void resize (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Resize function.
virtual ~Tensor7 ()
Destructor for Tensor7.
Public Member Functions inherited from Tensor7View
constexpr Tensor7View (const Tensor7View &)=default
Tensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & get (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
Iterator7D begin ()
Return iterator to first sub-tensor.
Iterator7D end ()
Return iterator behind last sub-tensor.
Tensor7View & operator= (const ConstTensor7View &v)
Assignment operator.
Tensor7View & operator= (const Tensor7View &v)
Assignment from Tensor7View to Tensor7View.
Tensor7View & operator= (const Tensor7 &v)
Assignment from a Tensor7.
Tensor7View & operator= (Numeric x)
Assigning a scalar to a Tensor7View will set all elements to this value.
Tensor7View & operator*= (Numeric x)
Multiplication by scalar.
Tensor7View & operator/= (Numeric x)
Division by scalar.
Tensor7View & operator+= (Numeric x)
Addition of scalar.
Tensor7View & operator-= (Numeric x)
Subtraction of scalar.
Tensor7View & operator*= (const ConstTensor7View &x)
Element-vise multiplication by another Tensor7.
Tensor7View & operator/= (const ConstTensor7View &x)
Element-vise division by another Tensor7.
Tensor7View & operator+= (const ConstTensor7View &x)
Element-vise addition of another Tensor7.
Tensor7View & operator-= (const ConstTensor7View &x)
Element-vise subtraction of another Tensor7.
virtual ~Tensor7View ()=default
Destructor.
Tensor7View (const Tensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Public Member Functions inherited from ConstTensor7View
constexpr ConstTensor7View (const ConstTensor7View &)=default
constexpr ConstTensor7View (ConstTensor7View &&)=default
ConstTensor7View & operator= (const ConstTensor7View &)=default
ConstTensor7View & operator= (ConstTensor7View &&)=default
bool empty () const
Check if variable is empty.
Index nlibraries () const
Returns the number of libraries.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor7View ()=default
Destructor.
ConstTensor7View (const ConstTensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
Friends
void swap (Tensor7 &t1, Tensor7 &t2)
Swaps two objects.
Additional Inherited Members
Protected Member Functions inherited from Tensor7View
Tensor7View ()=default
Tensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor7View
ConstTensor7View ()=default
ConstTensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes inherited from ConstTensor7View
Range mlr {0, 0, 1}
The library range of mdata that is actually used.
Range mvr {0, 0, 1}
The vitrine range of mdata that is actually used.
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor7 class.
This is a Tensor7View that also allocates storage automatically, and deallocates it when it is destroyed. We take all the functionality from Tensor7View. Additionally defined here are:
Constructors and destructor.
Assignment operators.
Resize function.
Definition at line 2382 of file matpackVII.h.
Constructor & Destructor Documentation
Tensor7() [1/6]
Tensor7::Tensor7 () default
Tensor7() [2/6]
Tensor7::Tensor7 (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Constructor setting size.
This constructor has to set the strides in the page and row ranges correctly!
Definition at line 5326 of file matpackVII.cc.
Tensor7() [3/6]
Tensor7::Tensor7 (Index l, Index v, Index s, Index b, Index p, Index r, Index c, Numeric fill)
Constructor setting size and filling with constant value.
Definition at line 5339 of file matpackVII.cc.
Tensor7() [4/6]
Tensor7::Tensor7 (const ConstTensor7View & m)
Copy constructor from Tensor7View.
This automatically sets the size and copies the data.
Definition at line 5356 of file matpackVII.cc.
References Tensor7View::begin(), ConstTensor7View::begin(), copy(), and ConstTensor7View::end().
Tensor7() [5/6]
Tensor7::Tensor7 (const Tensor7 & m)
Copy constructor from Tensor7.
This automatically sets the size and copies the data.
Definition at line 5378 of file matpackVII.cc.
References ConstTensor7View::mdata, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
Tensor7() [6/6]
Tensor7::Tensor7 (Tensor7 && v) inline noexcept
Definition at line 2397 of file matpackVII.h.
~Tensor7()
Tensor7::~Tensor7 () virtual
Destructor for Tensor7.
This is important, since Tensor7 uses new to allocate storage.
Definition at line 5544 of file matpackVII.cc.
References ConstTensor7View::mdata.
Member Function Documentation
operator=() [1/3]
Tensor7 & Tensor7::operator= (const Tensor7 & x)
Assignment operator from another tensor.
While dimensions of views can not be adjusted, dimensions of tensors can be adjusted. Hence, the behavior of the assignment operator is different.
In this case the size of the target is automatically adjusted. This is important, so that structures containing tensors are copied correctly.
This is a deviation from the old ARTS paradigm that sizes must match exactly before copying!
Note: It is sufficient to have only this one version of the assignment (Tensor = Tensor). It implicitly covers the cases Tensor=TensorView, etc, because there is a default constructor for Tensor from TensorView. (See C++ Primer Plus, page 571ff.)
Parameters
m The other tensor to assign to this one.
Returns
This tensor, by tradition.
Author
Stefan Buehler
Date
2002-12-19
Definition at line 5430 of file matpackVII.cc.
References ConstTensor7View::mdata, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), resize(), and ARTS::Var::x().
operator=() [2/3]
Tensor7 & Tensor7::operator= (Numeric x)
Assignment operator from scalar.
Assignment operators are not inherited.
Definition at line 5473 of file matpackVII.cc.
References ConstTensor7View::mdata, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and ARTS::Var::x().
operator=() [3/3]
Tensor7 & Tensor7::operator= (Tensor7 && x) noexcept
Copy assignment operator from another tensor.
Definition at line 5448 of file matpackVII.cc.
References ARTS::Var::x().
resize()
void Tensor7::resize (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Resize function.
If the size is already correct this function does nothing. All data is lost after resizing! The new tensor is not initialized, so it will contain random values.
Definition at line 5484 of file matpackVII.cc.
Referenced by calcSingleScatteringDataProperties(), ConvertAzimuthallyRandomSingleScatteringData(), operator=(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), Tensor7Scale(), test_empty(), and xml_read_from_stream().
Friends And Related Function Documentation
swap
void swap (Tensor7 & t1, Tensor7 & t2) friend
Swaps two objects.
Definition at line 5531 of file matpackVII.cc.
The documentation for this class was generated from the following files:
matpackVII.h
matpackVII.cc