ARTS: ARTS::Var::ArrayOfStokesVector Class Reference
ARTS::Var::ArrayOfStokesVector Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfStokesVector () noexcept
ArrayOfStokesVector (std::size_t i, void *x) noexcept
ArrayOfStokesVector (const Group::ArrayOfStokesVector &val) noexcept
~ArrayOfStokesVector () noexcept
Group::ArrayOfStokesVector & value () noexcept
const Group::ArrayOfStokesVector & value () const noexcept
ArrayOfStokesVector & operator= (const Group::ArrayOfStokesVector &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfStokesVector * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfStokesVector &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2162 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfStokesVector() [1/3]
ARTS::Var::ArrayOfStokesVector::ArrayOfStokesVector () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2167 of file autoarts.h.
ArrayOfStokesVector() [2/3]
ARTS::Var::ArrayOfStokesVector::ArrayOfStokesVector (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2170 of file autoarts.h.
ArrayOfStokesVector() [3/3]
ARTS::Var::ArrayOfStokesVector::ArrayOfStokesVector (const Group::ArrayOfStokesVector & val) inline noexcept
Construct from Group::ArrayOfStokesVector. Leaves islast() true and isnull() false
Definition at line 2173 of file autoarts.h.
~ArrayOfStokesVector()
ARTS::Var::ArrayOfStokesVector::~ArrayOfStokesVector () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2176 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfStokesVector::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2194 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfStokesVector().
isnull()
bool ARTS::Var::ArrayOfStokesVector::isnull () const inline noexcept
Return true if there is no data
Definition at line 2191 of file autoarts.h.
References v.
Referenced by ~ArrayOfStokesVector().
name()
const Group::String& ARTS::Var::ArrayOfStokesVector::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2197 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfStokesVector& ARTS::Var::ArrayOfStokesVector::operator= (const Group::ArrayOfStokesVector & t) inline noexcept
Set value from Group::ArrayOfStokesVector. Works when isnull() is false
Definition at line 2185 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfStokesVector::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2188 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfStokesVector& ARTS::Var::ArrayOfStokesVector::value () const inline noexcept
Get value const-ref as Group::ArrayOfStokesVector. Works when isnull() is false
Definition at line 2182 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfStokesVector& ARTS::Var::ArrayOfStokesVector::value () inline noexcept
Get value ref as Group::ArrayOfStokesVector. Works when isnull() is false
Definition at line 2179 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfStokesVector & var) friend
Output to stream of internal variable
Definition at line 2200 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfStokesVector::p private
Definition at line 2163 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfStokesVector* ARTS::Var::ArrayOfStokesVector::v private
Definition at line 2164 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfStokesVector().
The documentation for this class was generated from the following file:
autoarts.h