ARTS: Absorption::Lines Class Reference
Absorption::Lines Class Reference
#include <absorptionlines.h>
Public Member Functions
Lines (bool selfbroadening=false, bool bathbroadening=false, CutoffType cutoff=CutoffType::None, MirroringType mirroring=MirroringType::None, PopulationType population=PopulationType::LTE, NormalizationType normalization=NormalizationType::None, LineShape::Type lineshapetype=LineShape::Type::DP, Numeric T0=296, Numeric cutofffreq=-1, Numeric linemixinglimit=-1, const QuantumIdentifier &quantumidentity=QuantumIdentifier(), const std::vector< QuantumNumberType > &localquanta={}, const ArrayOfSpeciesTag &broadeningspecies={}, const std::vector< SingleLine > &lines={})
Default initialization.
Lines (bool selfbroadening, bool bathbroadening, size_t nlines, CutoffType cutoff, MirroringType mirroring, PopulationType population, NormalizationType normalization, LineShape::Type lineshapetype, Numeric T0, Numeric cutofffreq, Numeric linemixinglimit, const QuantumIdentifier &quantumidentity, const std::vector< QuantumNumberType > &localquanta, const ArrayOfSpeciesTag &broadeningspecies, const LineShape::Model &metamodel)
XML-tag initialization.
void AppendSingleLine (SingleLine &&sl)
Appends a single line to the absorption lines.
void AppendSingleLine (const SingleLine &sl)
Appends a single line to the absorption lines.
bool MatchWithExternal (const SingleLineExternal &sle, const QuantumIdentifier &quantumidentity) const noexcept
Checks if an external line matches this structure.
bool Match (const Lines &l) const noexcept
Checks if another line list matches this structure.
void sort_by_frequency ()
Sort inner line list by frequency.
void sort_by_einstein ()
Sort inner line list by Einstein coefficient.
void truncate_global_quantum_numbers ()
Removes all global quantum numbers.
void truncate_local_quantum_numbers ()
Removes all local quantum numbers.
String SpeciesName () const noexcept
Species Name.
String UpperQuantumNumbers () const noexcept
Upper quantum numbers string.
String LowerQuantumNumbers () const noexcept
Lower quantum numbers string.
String LineShapeMetaData () const noexcept
Meta data for the line shape if it exists.
Index Species () const noexcept
Species Index.
Index Isotopologue () const noexcept
Isotopologue Index.
Index NumLines () const noexcept
Number of lines.
const std::vector< SingleLine > & AllLines () const noexcept
Lines.
std::vector< SingleLine > & AllLines () noexcept
Lines.
Index NumBroadeners () const noexcept
Number of broadening species.
Index NumLocalQuanta () const noexcept
Number of local quantum numbers.
void RemoveUnusedLocalQuantums ()
Remove quantum numbers that are not used by even a single line.
void RemoveLocalQuantum (size_t)
Remove quantum numbers at the given position from all lines.
Rational LowerQuantumNumber (size_t k, QuantumNumberType qnt) const noexcept
Quantum number lower level.
Rational UpperQuantumNumber (size_t k, QuantumNumberType qnt) const noexcept
Quantum number upper level.
Rational & LowerQuantumNumber (size_t k, QuantumNumberType qnt) noexcept
Quantum number lower level.
Rational & UpperQuantumNumber (size_t k, QuantumNumberType qnt) noexcept
Quantum number upper level.
Index ZeemanCount (size_t k, Zeeman::Polarization type) const noexcept
Returns the number of Zeeman split lines.
Numeric ZeemanStrength (size_t k, Zeeman::Polarization type, Index i) const noexcept
Returns the strength of a Zeeman split line.
Numeric ZeemanSplitting (size_t k, Zeeman::Polarization type, Index i) const noexcept
Returns the splitting of a Zeeman split line.
void SetAutomaticZeeman () noexcept
Set Zeeman effect for all lines that have the correct quantum numbers.
Numeric F0 (size_t k) const noexcept
Central frequency.
Numeric & F0 (size_t k) noexcept
Central frequency.
Numeric F_mean () const noexcept
Mean frequency by weight of line strengt.
Numeric F_mean (const ConstVectorView wgts) const noexcept
Mean frequency by weight of line strengt.
Numeric E0 (size_t k) const noexcept
Lower level energy.
Numeric & E0 (size_t k) noexcept
Lower level energy.
Numeric I0 (size_t k) const noexcept
Reference line strength.
Numeric & I0 (size_t k) noexcept
Reference line strength.
Numeric A (size_t k) const noexcept
Einstein spontaneous emission.
Numeric & A (size_t k) noexcept
Einstein spontaneous emission.
Numeric g_low (size_t k) const noexcept
Lower level statistical weight.
Numeric & g_low (size_t k) noexcept
Lower level statistical weight.
Numeric g_upp (size_t k) const noexcept
Upper level statistical weight.
Numeric & g_upp (size_t k) noexcept
Upper level statistical weight.
MirroringType Mirroring () const noexcept
Returns mirroring style.
void Mirroring (MirroringType x) noexcept
Returns mirroring style.
NormalizationType Normalization () const noexcept
Returns normalization style.
void Normalization (NormalizationType x) noexcept
Returns normalization style.
CutoffType Cutoff () const noexcept
Returns cutoff style.
void Cutoff (CutoffType x) noexcept
Sets cutoff style.
PopulationType Population () const noexcept
Returns population style.
void Population (PopulationType x) noexcept
Sets population style.
LineShape::Type LineShapeType () const noexcept
Returns lineshapetype style.
void LineShapeType (LineShape::Type x) noexcept
Sets lineshapetype style.
bool DoLineMixing (Numeric P) const noexcept
Returns if the pressure should do line mixing.
LineShape::Output ShapeParameters (size_t k, Numeric T, Numeric P, const Vector &vmrs) const noexcept
Line shape parameters.
LineShape::Output ShapeParameters (size_t k, Numeric T, Numeric P, size_t m) const noexcept
Line shape parameters.
LineShape::Output ShapeParameters_dT (size_t k, Numeric T, Numeric P, const Vector &vmrs) const noexcept
Line shape parameters temperature derivatives.
Index LineShapePos (const Index &spec) const noexcept
Position among broadening species or -1.
Index LineShapePos (const QuantumIdentifier &qid) const noexcept
Position among broadening species or -1.
LineShape::Output ShapeParameters_dVMR (size_t k, Numeric T, Numeric P, const QuantumIdentifier &vmr_qid) const noexcept
Line shape parameters vmr derivative.
Numeric ShapeParameter_dInternal (size_t k, Numeric T, Numeric P, const Vector &vmrs, const RetrievalQuantity &derivative) const noexcept
Line shape parameter internal derivative.
Numeric CutoffFreq (size_t k) const noexcept
Returns cutoff frequency or maximum value.
Numeric CutoffFreqMinus (size_t k, Numeric fmean) const noexcept
Returns negative cutoff frequency or lowest value.
Numeric T0 () const noexcept
Returns reference temperature.
void T0 (Numeric x) noexcept
Sets reference temperature.
Numeric CutoffFreqValue () const noexcept
Returns internal cutoff frequency value.
void CutoffFreqValue (Numeric x) noexcept
Sets internal cutoff frequency value.
Numeric LinemixingLimit () const noexcept
Returns line mixing limit.
void LinemixingLimit (Numeric x) noexcept
Sets line mixing limit.
const std::vector< QuantumNumberType > & LocalQuanta () const noexcept
Returns local quantum numbers.
std::vector< QuantumNumberType > & LocalQuanta () noexcept
Returns local quantum numbers.
const ArrayOfSpeciesTag & BroadeningSpecies () const noexcept
Returns the broadening species.
ArrayOfSpeciesTag & BroadeningSpecies () noexcept
Returns the broadening species.
bool Self () const noexcept
Returns self broadening status.
void Self (bool x) noexcept
Returns self broadening status.
bool Bath () const noexcept
Returns bath broadening status.
void Bath (bool x) noexcept
Returns bath broadening status.
const QuantumIdentifier & QuantumIdentity () const noexcept
Returns identity status.
QuantumIdentifier & QuantumIdentity () noexcept
Returns identity status.
QuantumIdentifier QuantumIdentityOfLine (Index k) const noexcept
Returns identity status.
String MetaData () const
Returns a printable statement about the lines.
void RemoveLine (Index) noexcept
Removes a single line.
SingleLine PopLine (Index) noexcept
Pops a single line.
SingleLine & Line (Index) noexcept
Returns a single line.
const SingleLine & Line (Index) const noexcept
Returns a single line.
void ReverseLines () noexcept
Reverses the order of the internal lines.
Numeric SpeciesMass () const noexcept
Mass of the molecule.
Vector BroadeningSpeciesVMR (const ConstVectorView, const ArrayOfArrayOfSpeciesTag &) const
Returns the VMRs of the broadening species.
Vector BroadeningSpeciesMass (const ConstVectorView, const ArrayOfArrayOfSpeciesTag &, const Numeric &bath_mass=0) const
Returns the mass of the broadening species.
Numeric SelfVMR (const ConstVectorView, const ArrayOfArrayOfSpeciesTag &) const
Returns the VMR of the species.
bifstream & read (bifstream &is)
Binary read for Lines.
bofstream & write (bofstream &os) const
Binary write for Lines.
bool OK () const noexcept
Numeric DopplerConstant (Numeric T) const noexcept
Static Public Member Functions
static bool validIndexForMirroring (Index x) noexcept
Checks if index is a valid mirroring.
static MirroringType string2Mirroring (const String &in) noexcept
static bool validIndexForNormalization (Index x) noexcept
Checks if index is a valid normalization.
static NormalizationType string2Normalization (const String &in) noexcept
static bool validIndexForCutoff (Index x) noexcept
Checks if index is a valid cutoff.
static CutoffType string2Cutoff (const String &in) noexcept
static bool validIndexForPopulation (Index x) noexcept
Checks if index is a valid population.
static PopulationType string2Population (const String &in) noexcept
static bool validIndexForLineShapeType (Index x) noexcept
Checks if index is a valid lineshapetype.
static LineShape::Type string2LineShapeType (const String &type) noexcept
Private Attributes
bool mselfbroadening
Does the line broadening have self broadening.
bool mbathbroadening
Does the line broadening have bath broadening.
CutoffType mcutoff
cutoff type, by band or by line
MirroringType mmirroring
Mirroring type.
PopulationType mpopulation
Line population distribution.
NormalizationType mnormalization
Line normalization type.
LineShape::Type mlineshapetype
Type of line shape.
Numeric mT0
Reference temperature for all parameters of the lines.
Numeric mcutofffreq
cutoff frequency
Numeric mlinemixinglimit
linemixing limit
QuantumIdentifier mquantumidentity
Catalog ID.
std::vector< QuantumNumberType > mlocalquanta
List of local quantum numbers, these must be defined.
ArrayOfSpeciesTag mbroadeningspecies
A list of broadening species.
std::vector< SingleLine > mlines
A list of individual lines.
Detailed Description
Definition at line 409 of file absorptionlines.h.
Constructor & Destructor Documentation
Lines() [1/2]
Absorption::Lines::Lines (bool selfbroadening = false, bool bathbroadening = false, CutoffType cutoff = CutoffType::None, MirroringType mirroring = MirroringType::None, PopulationType population = PopulationType::LTE, NormalizationType normalization = NormalizationType::None, LineShape::Type lineshapetype = LineShape::Type::DP, Numeric T0 = 296, Numeric cutofffreq = -1, Numeric linemixinglimit = -1, const QuantumIdentifier & quantumidentity = QuantumIdentifier(), const std::vector< QuantumNumberType > & localquanta = {}, const ArrayOfSpeciesTag & broadeningspecies = {}, const std::vector< SingleLine > & lines = {}) inline
Default initialization.
Parameters
[in] selfbroadening Do self broadening
[in] bathbroadening Do bath broadening
[in] cutoff Type of cutoff frequency
[in] mirroring Type of mirroring
[in] population Type of line strengths distributions
[in] normalization Type of normalization
[in] lineshapetype Type of line shape
[in] T0 Reference temperature
[in] cutofffreq Cutoff frequency
[in] linemixinglimit Line mixing limit
[in] quantumidentity Identity of global lines
[in] localquanta List of local quantum number(s)
[in] broadeningspecies List of broadening species
[in] lines List of SingleLine(s)
Definition at line 471 of file absorptionlines.h.
Lines() [2/2]
Absorption::Lines::Lines (bool selfbroadening, bool bathbroadening, size_t nlines, CutoffType cutoff, MirroringType mirroring, PopulationType population, NormalizationType normalization, LineShape::Type lineshapetype, Numeric T0, Numeric cutofffreq, Numeric linemixinglimit, const QuantumIdentifier & quantumidentity, const std::vector< QuantumNumberType > & localquanta, const ArrayOfSpeciesTag & broadeningspecies, const LineShape::Model & metamodel) inline
XML-tag initialization.
Parameters
[in] selfbroadening Do self broadening
[in] bathbroadening Do bath broadening
[in] nlines Number of SingleLine(s) to initiate as empty
[in] cutoff Type of cutoff frequency
[in] mirroring Type of mirroring
[in] population Type of line strengths distributions
[in] normalization Type of normalization
[in] lineshapetype Type of line shape
[in] T0 Reference temperature
[in] cutofffreq Cutoff frequency
[in] linemixinglimit Line mixing limit
[in] quantumidentity Identity of global lines
[in] localquanta List of local quantum number(s)
[in] broadeningspecies List of broadening species
[in] metamodel A line shape model with defined shapes
Definition at line 518 of file absorptionlines.h.
Member Function Documentation
A() [1/2]
Numeric Absorption::Lines::A (size_t k) const inline noexcept
Einstein spontaneous emission.
Parameters
[in] k Line number (less than NumLines())
Returns
Einstein spontaneous emission
Definition at line 763 of file absorptionlines.h.
Referenced by Linefunctions::set_cross_section_of_band().
A() [2/2]
Numeric& Absorption::Lines::A (size_t k) inline noexcept
Einstein spontaneous emission.
Parameters
[in] k Line number (less than NumLines())
Returns
Einstein spontaneous emission
Definition at line 770 of file absorptionlines.h.
AllLines() [1/2]
const std::vector<SingleLine>& Absorption::Lines::AllLines () const inline noexcept
Lines.
Definition at line 626 of file absorptionlines.h.
References mlines.
Referenced by Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::operator<<(), and Absorption::operator>>().
AllLines() [2/2]
std::vector<SingleLine>& Absorption::Lines::AllLines () inline noexcept
Lines.
Definition at line 629 of file absorptionlines.h.
References mlines.
AppendSingleLine() [1/2]
void Absorption::Lines::AppendSingleLine (const SingleLine & sl)
Appends a single line to the absorption lines.
Useful for reading undefined number of lines and setting their structures
Warning: caller must guarantee that the broadening species and the quantum numbers of both levels have the correct order and the correct size. Only the sizes can be and are tested.
Parameters
[in] sl A single line
Definition at line 3214 of file absorptionlines.cc.
References ARTS_USER_ERROR_IF, Absorption::SingleLine::LineShapeElems(), Absorption::SingleLine::LowerQuantumElems(), mlines, NumLines(), NumLocalQuanta(), and Absorption::SingleLine::UpperQuantumElems().
AppendSingleLine() [2/2]
void Absorption::Lines::AppendSingleLine (SingleLine && sl)
Appends a single line to the absorption lines.
Useful for reading undefined number of lines and setting their structures
Warning: caller must guarantee that the broadening species and the quantum numbers of both levels have the correct order and the correct size. Only the sizes can be and are tested.
Parameters
[in] sl A single line
Definition at line 3202 of file absorptionlines.cc.
References ARTS_USER_ERROR_IF, mlines, NumLines(), and NumLocalQuanta().
Bath() [1/2]
bool Absorption::Lines::Bath () const inline noexcept
Returns bath broadening status.
Definition at line 1034 of file absorptionlines.h.
References mbathbroadening.
Referenced by Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), and xml_write_to_stream().
Bath() [2/2]
void Absorption::Lines::Bath (bool x) inline noexcept
Returns bath broadening status.
Definition at line 1039 of file absorptionlines.h.
References mbathbroadening, and ARTS::Var::x().
BroadeningSpecies() [1/2]
const ArrayOfSpeciesTag& Absorption::Lines::BroadeningSpecies () const inline noexcept
Returns the broadening species.
Definition at line 1014 of file absorptionlines.h.
References mbroadeningspecies.
Referenced by Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), and xml_write_to_stream().
BroadeningSpecies() [2/2]
ArrayOfSpeciesTag& Absorption::Lines::BroadeningSpecies () inline noexcept
Returns the broadening species.
Definition at line 1019 of file absorptionlines.h.
References mbroadeningspecies.
BroadeningSpeciesMass()
Vector Absorption::Lines::BroadeningSpeciesMass (const ConstVectorView atm_vmrs, const ArrayOfArrayOfSpeciesTag & atm_spec, const Numeric & bath_mass = 0) const
Returns the mass of the broadening species.
Parameters
[in] atm_vmrs Atmospheric VMRs
[in] atm_spec Atmospheric Species
[in] bath_mass Mass of Bath/Air (optional, will compute it if <=0)
Returns
Mass list of the species
Definition at line 2496 of file absorptionlines.cc.
References LineShape::mass(), ConstVectorView::nelem(), and Self.
BroadeningSpeciesVMR()
Vector Absorption::Lines::BroadeningSpeciesVMR (const ConstVectorView atm_vmrs, const ArrayOfArrayOfSpeciesTag & atm_spec) const
Returns the VMRs of the broadening species.
Parameters
[in] atm_vmrs Atmospheric VMRs
[in] atm_spec Atmospheric Species
Returns
VMR list of the species
Definition at line 2489 of file absorptionlines.cc.
References Self, and LineShape::vmrs().
Referenced by xsec_species().
Cutoff() [1/2]
CutoffType Absorption::Lines::Cutoff () const inline noexcept
Returns cutoff style.
Definition at line 833 of file absorptionlines.h.
References mcutoff.
Referenced by Linefunctions::set_cross_section_of_band(), and xml_write_to_stream().
Cutoff() [2/2]
void Absorption::Lines::Cutoff (CutoffType x) inline noexcept
Sets cutoff style.
Definition at line 836 of file absorptionlines.h.
References mcutoff, and ARTS::Var::x().
CutoffFreq()
Numeric Absorption::Lines::CutoffFreq (size_t k) const noexcept
Returns cutoff frequency or maximum value.
Parameters
[in] k Line number (less than NumLines())
Returns
Cutoff frequency or 0
Definition at line 3381 of file absorptionlines.cc.
Referenced by Linefunctions::set_cross_section_of_band().
CutoffFreqMinus()
Numeric Absorption::Lines::CutoffFreqMinus (size_t k, Numeric fmean) const noexcept
Returns negative cutoff frequency or lowest value.
Parameters
[in] k Line number (less than NumLines())
Returns
Negative cutoff frequency or the lowest value
Definition at line 3396 of file absorptionlines.cc.
Referenced by Linefunctions::set_cross_section_of_band().
CutoffFreqValue() [1/2]
Numeric Absorption::Lines::CutoffFreqValue () const inline noexcept
Returns internal cutoff frequency value.
Definition at line 984 of file absorptionlines.h.
References mcutofffreq.
Referenced by xml_write_to_stream().
CutoffFreqValue() [2/2]
void Absorption::Lines::CutoffFreqValue (Numeric x) inline noexcept
Sets internal cutoff frequency value.
Definition at line 989 of file absorptionlines.h.
References mcutofffreq, and ARTS::Var::x().
DoLineMixing()
bool Absorption::Lines::DoLineMixing (Numeric P) const inline noexcept
Returns if the pressure should do line mixing.
Parameters
[in] P Atmospheric pressure
Returns
true if no limit or P less than limit
Definition at line 885 of file absorptionlines.h.
Referenced by Linefunctions::set_cross_section_of_band().
DopplerConstant()
Numeric Absorption::Lines::DopplerConstant (Numeric T) const noexcept
Definition at line 3123 of file absorptionlines.cc.
References sqrt().
E0() [1/2]
Numeric Absorption::Lines::E0 (size_t k) const inline noexcept
Lower level energy.
Parameters
[in] k Line number (less than NumLines())
Returns
Lower level energy
Definition at line 735 of file absorptionlines.h.
Referenced by lm_hitran_2017::convtp().
E0() [2/2]
Numeric& Absorption::Lines::E0 (size_t k) inline noexcept
Lower level energy.
Parameters
[in] k Line number (less than NumLines())
Returns
Lower level energy
Definition at line 742 of file absorptionlines.h.
F0() [1/2]
Numeric Absorption::Lines::F0 (size_t k) const inline noexcept
Central frequency.
Parameters
[in] k Line number (less than NumLines())
Returns
Central frequency
Definition at line 708 of file absorptionlines.h.
Referenced by lm_hitran_2017::convtp(), and Linefunctions::set_cross_section_of_band().
F0() [2/2]
Numeric& Absorption::Lines::F0 (size_t k) inline noexcept
Central frequency.
Parameters
[in] k Line number (less than NumLines())
Returns
Central frequency
Definition at line 715 of file absorptionlines.h.
F_mean() [1/2]
Numeric Absorption::Lines::F_mean () const noexcept
Mean frequency by weight of line strengt.
Returns
Mean frequency
Definition at line 3362 of file absorptionlines.cc.
References a, b, and mlines.
Referenced by lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), and Linefunctions::set_cross_section_of_band().
F_mean() [2/2]
Numeric Absorption::Lines::F_mean (const ConstVectorView wgts) const noexcept
Mean frequency by weight of line strengt.
Parameters
[in] wgts Weight of averaging
Returns
Mean frequency
Definition at line 3371 of file absorptionlines.cc.
References a, and b.
g_low() [1/2]
Numeric Absorption::Lines::g_low (size_t k) const inline noexcept
Lower level statistical weight.
Parameters
[in] k Line number (less than NumLines())
Returns
Lower level statistical weight
Definition at line 777 of file absorptionlines.h.
Referenced by Linefunctions::set_cross_section_of_band().
g_low() [2/2]
Numeric& Absorption::Lines::g_low (size_t k) inline noexcept
Lower level statistical weight.
Parameters
[in] k Line number (less than NumLines())
Returns
Lower level statistical weight
Definition at line 784 of file absorptionlines.h.
g_upp() [1/2]
Numeric Absorption::Lines::g_upp (size_t k) const inline noexcept
Upper level statistical weight.
Parameters
[in] k Line number (less than NumLines())
Returns
Upper level statistical weight
Definition at line 791 of file absorptionlines.h.
Referenced by lm_hitran_2017::convtp(), and Linefunctions::set_cross_section_of_band().
g_upp() [2/2]
Numeric& Absorption::Lines::g_upp (size_t k) inline noexcept
Upper level statistical weight.
Parameters
[in] k Line number (less than NumLines())
Returns
Upper level statistical weight
Definition at line 798 of file absorptionlines.h.
I0() [1/2]
Numeric Absorption::Lines::I0 (size_t k) const inline noexcept
Reference line strength.
Parameters
[in] k Line number (less than NumLines())
Returns
Reference line strength
Definition at line 749 of file absorptionlines.h.
Referenced by lm_hitran_2017::convtp().
I0() [2/2]
Numeric& Absorption::Lines::I0 (size_t k) inline noexcept
Reference line strength.
Parameters
[in] k Line number (less than NumLines())
Returns
Reference line strength
Definition at line 756 of file absorptionlines.h.
Isotopologue()
Index Absorption::Lines::Isotopologue () const inline noexcept
Isotopologue Index.
Definition at line 620 of file absorptionlines.h.
References QuantumIdentifier::Isotopologue(), and mquantumidentity.
Referenced by lm_hitran_2017::calcw(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), and SpeciesName().
Line() [1/2]
const Absorption::SingleLine & Absorption::Lines::Line (Index i) const noexcept
Returns a single line.
Definition at line 2474 of file absorptionlines.cc.
Line() [2/2]
Absorption::SingleLine & Absorption::Lines::Line (Index i) noexcept
Returns a single line.
Definition at line 2468 of file absorptionlines.cc.
Referenced by lm_hitran_2017::convtp(), LineShape::linestrength_selection(), and Linefunctions::set_cross_section_of_band().
LinemixingLimit() [1/2]
Numeric Absorption::Lines::LinemixingLimit () const inline noexcept
Returns line mixing limit.
Definition at line 994 of file absorptionlines.h.
References mlinemixinglimit.
Referenced by xml_write_to_stream().
LinemixingLimit() [2/2]
void Absorption::Lines::LinemixingLimit (Numeric x) inline noexcept
Sets line mixing limit.
Definition at line 999 of file absorptionlines.h.
References mlinemixinglimit, and ARTS::Var::x().
LineShapeMetaData()
String Absorption::Lines::LineShapeMetaData () const noexcept
Meta data for the line shape if it exists.
Definition at line 3315 of file absorptionlines.cc.
References mlines, LineShape::ModelShape2MetaData(), and NumLines().
Referenced by xml_write_to_stream().
LineShapePos() [1/2]
Index Absorption::Lines::LineShapePos (const Index & spec) const noexcept
Position among broadening species or -1.
Parameters
[in] A species index that might be among the broadener species
Returns
Position among broadening species or -1
Definition at line 89 of file absorptionlines.cc.
Referenced by LineShapePos().
LineShapePos() [2/2]
Index Absorption::Lines::LineShapePos (const QuantumIdentifier & qid) const inline noexcept
Position among broadening species or -1.
Parameters
[in] An identity that might be among the broadener species
Returns
Position among broadening species or -1
Definition at line 931 of file absorptionlines.h.
References LineShapePos().
LineShapeType() [1/2]
LineShape::Type Absorption::Lines::LineShapeType () const inline noexcept
Returns lineshapetype style.
Definition at line 865 of file absorptionlines.h.
References mlineshapetype.
Referenced by Linefunctions::set_cross_section_of_band(), and xml_write_to_stream().
LineShapeType() [2/2]
void Absorption::Lines::LineShapeType (LineShape::Type x) inline noexcept
Sets lineshapetype style.
Definition at line 868 of file absorptionlines.h.
References mlineshapetype, and ARTS::Var::x().
LocalQuanta() [1/2]
const std::vector<QuantumNumberType>& Absorption::Lines::LocalQuanta () const inline noexcept
Returns local quantum numbers.
Definition at line 1004 of file absorptionlines.h.
References mlocalquanta.
Referenced by xml_write_to_stream().
LocalQuanta() [2/2]
std::vector<QuantumNumberType>& Absorption::Lines::LocalQuanta () inline noexcept
Returns local quantum numbers.
Definition at line 1009 of file absorptionlines.h.
References mlocalquanta.
LowerQuantumNumber() [1/2]
Rational Absorption::Lines::LowerQuantumNumber (size_t k, QuantumNumberType qnt) const noexcept
Quantum number lower level.
Parameters
[in] k Line number (less than NumLines())
[in] qnt Quantum number type
Returns
Quantum number
Definition at line 41 of file absorptionlines.cc.
Referenced by lm_hitran_2017::calcw().
LowerQuantumNumber() [2/2]
Rational & Absorption::Lines::LowerQuantumNumber (size_t k, QuantumNumberType qnt) noexcept
Quantum number lower level.
Parameters
[in] k Line number (less than NumLines())
[in] qnt Quantum number type
Returns
Quantum number
Definition at line 55 of file absorptionlines.cc.
LowerQuantumNumbers()
String Absorption::Lines::LowerQuantumNumbers () const noexcept
Lower quantum numbers string.
Definition at line 2334 of file absorptionlines.cc.
Referenced by xml_write_to_stream().
Match()
bool Absorption::Lines::Match (const Lines & l) const noexcept
Checks if another line list matches this structure.
Parameters
[in] sle Full external lines
[in] quantumidentity Expected global quantum id of the line
Definition at line 3260 of file absorptionlines.cc.
References Interpolation::l().
MatchWithExternal()
bool Absorption::Lines::MatchWithExternal (const SingleLineExternal & sle, const QuantumIdentifier & quantumidentity) const noexcept
Checks if an external line matches this structure.
Parameters
[in] sle Full external lines
[in] quantumidentity Expected global quantum id of the line
Definition at line 3226 of file absorptionlines.cc.
MetaData()
String Absorption::Lines::MetaData () const
Returns a printable statement about the lines.
Definition at line 2339 of file absorptionlines.cc.
References Absorption::cutofftype2metadatastring(), and LineShape::ModelMetaDataArray().
Referenced by xml_write_to_stream().
Mirroring() [1/2]
MirroringType Absorption::Lines::Mirroring () const inline noexcept
Returns mirroring style.
Definition at line 801 of file absorptionlines.h.
References mmirroring.
Referenced by Linefunctions::set_cross_section_of_band(), and xml_write_to_stream().
Mirroring() [2/2]
void Absorption::Lines::Mirroring (MirroringType x) inline noexcept
Returns mirroring style.
Definition at line 804 of file absorptionlines.h.
References mmirroring, and ARTS::Var::x().
Normalization() [1/2]
NormalizationType Absorption::Lines::Normalization () const inline noexcept
Returns normalization style.
Definition at line 817 of file absorptionlines.h.
References mnormalization.
Referenced by Linefunctions::set_cross_section_of_band(), and xml_write_to_stream().
Normalization() [2/2]
void Absorption::Lines::Normalization (NormalizationType x) inline noexcept
Returns normalization style.
Definition at line 820 of file absorptionlines.h.
References mnormalization, and ARTS::Var::x().
NumBroadeners()
Index Absorption::Lines::NumBroadeners () const inline noexcept
Number of broadening species.
Definition at line 632 of file absorptionlines.h.
References mbroadeningspecies, and Array< base >::nelem().
Referenced by Absorption::LineMixing::ecs_rosenkranz_adaptation(), and Absorption::LineMixing::ecs_rosenkranz_approximation().
NumLines()
Index Absorption::Lines::NumLines () const inline noexcept
Number of lines.
Definition at line 623 of file absorptionlines.h.
References mlines.
Referenced by AppendSingleLine(), lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), Absorption::LineMixing::ecs_relaxation_matrix(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::LineMixing::ecs_rosenkranz_approximation(), LineShapeMetaData(), Linefunctions::set_cross_section_of_band(), Absorption::LineMixing::single_species_ecs_relaxation_matrix(), xml_write_to_stream(), and xsec_species().
NumLocalQuanta()
Index Absorption::Lines::NumLocalQuanta () const inline noexcept
Number of local quantum numbers.
Definition at line 635 of file absorptionlines.h.
References mlocalquanta.
Referenced by AppendSingleLine().
OK()
bool Absorption::Lines::OK () const noexcept
Definition at line 3098 of file absorptionlines.cc.
PopLine()
Absorption::SingleLine Absorption::Lines::PopLine (Index i) noexcept
Pops a single line.
Definition at line 2452 of file absorptionlines.cc.
Population() [1/2]
PopulationType Absorption::Lines::Population () const inline noexcept
Returns population style.
Definition at line 849 of file absorptionlines.h.
References mpopulation.
Referenced by lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), LineShape::linestrength_selection(), Linefunctions::set_cross_section_of_band(), Absorption::LineMixing::single_species_ecs_relaxation_matrix(), and xml_write_to_stream().
Population() [2/2]
void Absorption::Lines::Population (PopulationType x) inline noexcept
Sets population style.
Definition at line 852 of file absorptionlines.h.
References mpopulation, and ARTS::Var::x().
QuantumIdentity() [1/2]
const QuantumIdentifier& Absorption::Lines::QuantumIdentity () const inline noexcept
Returns identity status.
Definition at line 1044 of file absorptionlines.h.
References mquantumidentity.
Referenced by Absorption::ENUMCLASS(), and Linefunctions::set_cross_section_of_band().
QuantumIdentity() [2/2]
QuantumIdentifier& Absorption::Lines::QuantumIdentity () inline noexcept
Returns identity status.
Definition at line 1049 of file absorptionlines.h.
References mquantumidentity.
QuantumIdentityOfLine()
QuantumIdentifier Absorption::Lines::QuantumIdentityOfLine (Index k) const noexcept
Returns identity status.
Definition at line 3421 of file absorptionlines.cc.
read()
bifstream & Absorption::Lines::read (bifstream & is)
Binary read for Lines.
Definition at line 3409 of file absorptionlines.cc.
References mlines.
RemoveLine()
void Absorption::Lines::RemoveLine (Index i) noexcept
Removes a single line.
Definition at line 2446 of file absorptionlines.cc.
RemoveLocalQuantum()
void Absorption::Lines::RemoveLocalQuantum (size_t x)
Remove quantum numbers at the given position from all lines.
Definition at line 2428 of file absorptionlines.cc.
References ARTS::Var::x().
RemoveUnusedLocalQuantums()
void Absorption::Lines::RemoveUnusedLocalQuantums ()
Remove quantum numbers that are not used by even a single line.
Definition at line 2402 of file absorptionlines.cc.
ReverseLines()
void Absorption::Lines::ReverseLines () noexcept
Reverses the order of the internal lines.
Definition at line 2479 of file absorptionlines.cc.
Self() [1/2]
bool Absorption::Lines::Self () const inline noexcept
Returns self broadening status.
Definition at line 1024 of file absorptionlines.h.
References mselfbroadening.
Referenced by Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), and xml_write_to_stream().
Self() [2/2]
void Absorption::Lines::Self (bool x) inline noexcept
Returns self broadening status.
Definition at line 1029 of file absorptionlines.h.
References mselfbroadening, and ARTS::Var::x().
SelfVMR()
Numeric Absorption::Lines::SelfVMR (const ConstVectorView atm_vmrs, const ArrayOfArrayOfSpeciesTag & atm_spec) const
Returns the VMR of the species.
Parameters
[in] atm_vmrs Atmospheric VMRs
[in] atm_spec Atmospheric Species
Returns
VMR of the species
Definition at line 2505 of file absorptionlines.cc.
References ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), Absorption::nelem(), and Species.
SetAutomaticZeeman()
void Absorption::Lines::SetAutomaticZeeman () noexcept
Set Zeeman effect for all lines that have the correct quantum numbers.
Definition at line 3357 of file absorptionlines.cc.
References mlines, mlocalquanta, and mquantumidentity.
ShapeParameter_dInternal()
Numeric Absorption::Lines::ShapeParameter_dInternal (size_t k, Numeric T, Numeric P, const Vector & vmrs, const RetrievalQuantity & derivative) const noexcept
Line shape parameter internal derivative.
Parameters
[in] k Line number (less than NumLines())
[in] T Atmospheric temperature
[in] P Atmospheric pressure
[in] vmrs Line broadener's volume mixing ratio
[in] derivative Type of line shape derivative
Returns
Line shape parameter internal derivative
Definition at line 120 of file absorptionlines.cc.
Referenced by Linefunctions::apply_lineshapemodel_jacobian_scaling().
ShapeParameters() [1/2]
LineShape::Output Absorption::Lines::ShapeParameters (size_t k, Numeric T, Numeric P, const Vector & vmrs) const noexcept
Line shape parameters.
Parameters
[in] k Line number (less than NumLines())
[in] T Atmospheric temperature
[in] P Atmospheric pressure
[in] vmrs Line broadener species's volume mixing ratio
Returns
Line shape parameters
Definition at line 69 of file absorptionlines.cc.
Referenced by Linefunctions::set_cross_section_of_band(), and Absorption::LineMixing::single_species_ecs_relaxation_matrix().
ShapeParameters() [2/2]
LineShape::Output Absorption::Lines::ShapeParameters (size_t k, Numeric T, Numeric P, size_t m) const noexcept
Line shape parameters.
Parameters
[in] k Line number (less than NumLines())
[in] T Atmospheric temperature
[in] P Atmospheric pressure
[in] m Line broadening species position
Returns
Line shape parameters
Definition at line 77 of file absorptionlines.cc.
ShapeParameters_dT()
LineShape::Output Absorption::Lines::ShapeParameters_dT (size_t k, Numeric T, Numeric P, const Vector & vmrs) const noexcept
Line shape parameters temperature derivatives.
Parameters
[in] k Line number (less than NumLines())
[in] T Atmospheric temperature
[in] P Atmospheric pressure
[in] vmrs Line broadener's volume mixing ratio
Returns
Line shape parameters temperature derivatives
Definition at line 81 of file absorptionlines.cc.
Referenced by Linefunctions::set_cross_section_of_band().
ShapeParameters_dVMR()
LineShape::Output Absorption::Lines::ShapeParameters_dVMR (size_t k, Numeric T, Numeric P, const QuantumIdentifier & vmr_qid) const noexcept
Line shape parameters vmr derivative.
Parameters
[in] k Line number (less than NumLines())
[in] T Atmospheric temperature
[in] P Atmospheric pressure
[in] vmr_qid Identity of species whose VMR derivative is requested
Returns
Line shape parameters vmr derivative
Definition at line 111 of file absorptionlines.cc.
Referenced by Linefunctions::set_cross_section_of_band().
sort_by_einstein()
void Absorption::Lines::sort_by_einstein ()
Sort inner line list by Einstein coefficient.
Definition at line 3298 of file absorptionlines.cc.
References a, b, and mlines.
sort_by_frequency()
void Absorption::Lines::sort_by_frequency ()
Sort inner line list by frequency.
Definition at line 3293 of file absorptionlines.cc.
References a, b, and mlines.
Species()
Index Absorption::Lines::Species () const inline noexcept
Species Index.
Definition at line 617 of file absorptionlines.h.
References mquantumidentity, and QuantumIdentifier::Species().
Referenced by Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), SpeciesDataOfBand(), and SpeciesName().
SpeciesMass()
Numeric Absorption::Lines::SpeciesMass () const noexcept
Mass of the molecule.
Definition at line 2484 of file absorptionlines.cc.
References Isotopologue, Species, and global_data::species_data.
Referenced by Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), Absorption::LineMixing::single_species_ecs_relaxation_matrix(), and xsec_species().
SpeciesName()
String Absorption::Lines::SpeciesName () const noexcept
Species Name.
Definition at line 2316 of file absorptionlines.cc.
References SpeciesRecord::Isotopologue(), Isotopologue(), SpeciesRecord::Name(), Species(), and global_data::species_data.
Referenced by xml_write_to_stream().
string2Cutoff()
static CutoffType Absorption::Lines::string2Cutoff (const String & in) inline static noexcept
Returns
CutoffType if string is a CutoffType or -1 if not
Definition at line 844 of file absorptionlines.h.
string2LineShapeType()
static LineShape::Type Absorption::Lines::string2LineShapeType (const String & type) inline static noexcept
Returns
LineShape::Type if string is a LineShape::Type or -1 if not
Definition at line 876 of file absorptionlines.h.
References Hitran::type.
string2Mirroring()
static MirroringType Absorption::Lines::string2Mirroring (const String & in) inline static noexcept
Returns
MirroringType if string is a MirroringType or -1 if not
Definition at line 812 of file absorptionlines.h.
string2Normalization()
static NormalizationType Absorption::Lines::string2Normalization (const String & in) inline static noexcept
Returns
NormalizationType if string is a NormalizationType or -1 if not
Definition at line 828 of file absorptionlines.h.
string2Population()
static PopulationType Absorption::Lines::string2Population (const String & in) inline static noexcept
Returns
PopulationType if string is a PopulationType or -1 if not
Definition at line 860 of file absorptionlines.h.
T0() [1/2]
Numeric Absorption::Lines::T0 () const inline noexcept
Returns reference temperature.
Definition at line 974 of file absorptionlines.h.
References mT0.
Referenced by lm_hitran_2017::calcw(), lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::LineMixing::ecs_rosenkranz_approximation(), LineShape::linestrength_selection(), Linefunctions::set_cross_section_of_band(), xml_write_to_stream(), and xsec_species().
T0() [2/2]
void Absorption::Lines::T0 (Numeric x) inline noexcept
Sets reference temperature.
Definition at line 979 of file absorptionlines.h.
References mT0, and ARTS::Var::x().
truncate_global_quantum_numbers()
void Absorption::Lines::truncate_global_quantum_numbers ()
Removes all global quantum numbers.
Definition at line 3303 of file absorptionlines.cc.
References mquantumidentity, and QuantumIdentifier::SetTransition().
truncate_local_quantum_numbers()
void Absorption::Lines::truncate_local_quantum_numbers ()
Removes all local quantum numbers.
Definition at line 3307 of file absorptionlines.cc.
References mlines, and mlocalquanta.
UpperQuantumNumber() [1/2]
Rational Absorption::Lines::UpperQuantumNumber (size_t k, QuantumNumberType qnt) const noexcept
Quantum number upper level.
Parameters
[in] k Line number (less than NumLines())
[in] qnt Quantum number type
Returns
Quantum number
Definition at line 48 of file absorptionlines.cc.
Referenced by lm_hitran_2017::calcw().
UpperQuantumNumber() [2/2]
Rational & Absorption::Lines::UpperQuantumNumber (size_t k, QuantumNumberType qnt) noexcept
Quantum number upper level.
Parameters
[in] k Line number (less than NumLines())
[in] qnt Quantum number type
Returns
Quantum number
Definition at line 62 of file absorptionlines.cc.
UpperQuantumNumbers()
String Absorption::Lines::UpperQuantumNumbers () const noexcept
Upper quantum numbers string.
Definition at line 2329 of file absorptionlines.cc.
Referenced by xml_write_to_stream().
validIndexForCutoff()
static bool Absorption::Lines::validIndexForCutoff (Index x) inline static noexcept
Checks if index is a valid cutoff.
Definition at line 839 of file absorptionlines.h.
References good_enum(), and ARTS::Var::x().
validIndexForLineShapeType()
static bool Absorption::Lines::validIndexForLineShapeType (Index x) inline static noexcept
Checks if index is a valid lineshapetype.
Definition at line 871 of file absorptionlines.h.
References good_enum(), Type, and ARTS::Var::x().
validIndexForMirroring()
static bool Absorption::Lines::validIndexForMirroring (Index x) inline static noexcept
Checks if index is a valid mirroring.
Definition at line 807 of file absorptionlines.h.
References good_enum(), and ARTS::Var::x().
validIndexForNormalization()
static bool Absorption::Lines::validIndexForNormalization (Index x) inline static noexcept
Checks if index is a valid normalization.
Definition at line 823 of file absorptionlines.h.
References good_enum(), and ARTS::Var::x().
validIndexForPopulation()
static bool Absorption::Lines::validIndexForPopulation (Index x) inline static noexcept
Checks if index is a valid population.
Definition at line 855 of file absorptionlines.h.
References good_enum(), and ARTS::Var::x().
write()
bofstream & Absorption::Lines::write (bofstream & os) const
Binary write for Lines.
Definition at line 3415 of file absorptionlines.cc.
References mlines.
Referenced by xml_write_to_stream().
ZeemanCount()
Index Absorption::Lines::ZeemanCount (size_t k, Zeeman::Polarization type) const noexcept
Returns the number of Zeeman split lines.
Parameters
[in] k Line number (less than NumLines())
[in] type Type of Zeeman polarization
Definition at line 3321 of file absorptionlines.cc.
Referenced by Absorption::LineMixing::ecs_absorption_zeeman_impl(), and Linefunctions::set_cross_section_of_band().
ZeemanSplitting()
Numeric Absorption::Lines::ZeemanSplitting (size_t k, Zeeman::Polarization type, Index i) const noexcept
Returns the splitting of a Zeeman split line.
Parameters
[in] k Line number (less than NumLines())
[in] type Type of Zeeman polarization
[in] i Zeeman line count
Definition at line 3345 of file absorptionlines.cc.
Referenced by Absorption::LineMixing::ecs_absorption_zeeman_impl(), and Linefunctions::set_cross_section_of_band().
ZeemanStrength()
Numeric Absorption::Lines::ZeemanStrength (size_t k, Zeeman::Polarization type, Index i) const noexcept
Returns the strength of a Zeeman split line.
Parameters
[in] k Line number (less than NumLines())
[in] type Type of Zeeman polarization
[in] i Zeeman line count
Definition at line 3333 of file absorptionlines.cc.
Referenced by Absorption::LineMixing::ecs_absorption_zeeman_impl(), and Linefunctions::set_cross_section_of_band().
Member Data Documentation
mbathbroadening
bool Absorption::Lines::mbathbroadening private
Does the line broadening have bath broadening.
Definition at line 415 of file absorptionlines.h.
Referenced by Bath().
mbroadeningspecies
ArrayOfSpeciesTag Absorption::Lines::mbroadeningspecies private
A list of broadening species.
Definition at line 448 of file absorptionlines.h.
Referenced by BroadeningSpecies(), and NumBroadeners().
mcutoff
CutoffType Absorption::Lines::mcutoff private
cutoff type, by band or by line
Definition at line 418 of file absorptionlines.h.
Referenced by Cutoff().
mcutofffreq
Numeric Absorption::Lines::mcutofffreq private
cutoff frequency
Definition at line 436 of file absorptionlines.h.
Referenced by CutoffFreqValue().
mlinemixinglimit
Numeric Absorption::Lines::mlinemixinglimit private
linemixing limit
Definition at line 439 of file absorptionlines.h.
Referenced by LinemixingLimit().
mlines
std::vector<SingleLine> Absorption::Lines::mlines private
A list of individual lines.
Definition at line 451 of file absorptionlines.h.
Referenced by AllLines(), AppendSingleLine(), F_mean(), LineShapeMetaData(), NumLines(), read(), SetAutomaticZeeman(), sort_by_einstein(), sort_by_frequency(), truncate_local_quantum_numbers(), and write().
mlineshapetype
LineShape::Type Absorption::Lines::mlineshapetype private
Type of line shape.
Definition at line 430 of file absorptionlines.h.
Referenced by LineShapeType().
mlocalquanta
std::vector<QuantumNumberType> Absorption::Lines::mlocalquanta private
List of local quantum numbers, these must be defined.
Definition at line 445 of file absorptionlines.h.
Referenced by LocalQuanta(), NumLocalQuanta(), SetAutomaticZeeman(), and truncate_local_quantum_numbers().
mmirroring
MirroringType Absorption::Lines::mmirroring private
Mirroring type.
Definition at line 421 of file absorptionlines.h.
Referenced by Mirroring().
mnormalization
NormalizationType Absorption::Lines::mnormalization private
Line normalization type.
Definition at line 427 of file absorptionlines.h.
Referenced by Normalization().
mpopulation
PopulationType Absorption::Lines::mpopulation private
Line population distribution.
Definition at line 424 of file absorptionlines.h.
Referenced by Population().
mquantumidentity
QuantumIdentifier Absorption::Lines::mquantumidentity private
Catalog ID.
Definition at line 442 of file absorptionlines.h.
Referenced by Isotopologue(), QuantumIdentity(), SetAutomaticZeeman(), Species(), and truncate_global_quantum_numbers().
mselfbroadening
bool Absorption::Lines::mselfbroadening private
Does the line broadening have self broadening.
Definition at line 412 of file absorptionlines.h.
Referenced by Self().
mT0
Numeric Absorption::Lines::mT0 private
Reference temperature for all parameters of the lines.
Definition at line 433 of file absorptionlines.h.
Referenced by T0().
The documentation for this class was generated from the following files:
absorptionlines.h
absorptionlines.cc