ARTS: ARTS::Var::Tensor7 Class Reference
ARTS::Var::Tensor7 Class Reference
#include <autoarts.h>
Public Member Functions
Tensor7 () noexcept
Tensor7 (std::size_t i, void *x) noexcept
~Tensor7 () noexcept
Tensor7 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
Tensor7 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::Tensor7
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1614 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::Tensor7::type = Group::Tensor7 private
Definition at line 1615 of file autoarts.h.
Constructor & Destructor Documentation
Tensor7() [1/3]
ARTS::Var::Tensor7::Tensor7 () inline noexcept
Definition at line 1619 of file autoarts.h.
Tensor7() [2/3]
ARTS::Var::Tensor7::Tensor7 (std::size_t i, void * x) inline noexcept
Definition at line 1620 of file autoarts.h.
~Tensor7()
ARTS::Var::Tensor7::~Tensor7 () inline noexcept
Definition at line 1621 of file autoarts.h.
References islast(), isnull(), and v.
Tensor7() [3/3]
ARTS::Var::Tensor7::Tensor7 (const type & val) inline noexcept
Definition at line 1622 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::Tensor7::islast () const inline noexcept
Definition at line 1628 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::cloudbox_fieldSetFromPrecalc(), ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::Method::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nlibrariesGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::nvitrinesGet(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor7Scale(), ARTS::Method::Tensor7Scale(), ARTS::AgendaMethod::Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~Tensor7().
isnull()
bool ARTS::Var::Tensor7::isnull () const inline noexcept
Definition at line 1627 of file autoarts.h.
References v.
Referenced by ~Tensor7().
name()
const Group::String& ARTS::Var::Tensor7::name () const inline noexcept
Definition at line 1629 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
Tensor7& ARTS::Var::Tensor7::operator= (const type & t) inline noexcept
Definition at line 1625 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Tensor7::pos () const inline noexcept
Definition at line 1626 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::cloudbox_fieldSetFromPrecalc(), ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::nbooksGet(), ARTS::AgendaMethod::ncolsGet(), ARTS::AgendaMethod::nlibrariesGet(), ARTS::AgendaMethod::npagesGet(), ARTS::AgendaMethod::nrowsGet(), ARTS::AgendaMethod::nshelvesGet(), ARTS::AgendaMethod::nvitrinesGet(), ARTS::AgendaMethod::RadiationFieldSpectralIntegrate(), ARTS::AgendaMethod::Reduce(), ARTS::AgendaMethod::Tensor7Scale(), ARTS::AgendaMethod::Tensor7SetConstant(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::Tensor7::value () const inline noexcept
Definition at line 1624 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::Tensor7::value () inline noexcept
Definition at line 1623 of file autoarts.h.
References v.
Referenced by ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::nbooksGet(), ARTS::Method::ncolsGet(), ARTS::Method::nlibrariesGet(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), ARTS::Method::nvitrinesGet(), operator=(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::Reduce(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::Tensor7::p private
Definition at line 1616 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::Tensor7::v private
Definition at line 1617 of file autoarts.h.
Referenced by isnull(), value(), and ~Tensor7().
The documentation for this class was generated from the following file:
autoarts.h