ARTS: Absorption::SingleLine Class Reference
Absorption::SingleLine Class Reference
Computations and data for a single absorption line.
#include <absorptionlines.h>
Public Member Functions
SingleLine (Numeric F0=0, Numeric I0=0, Numeric E0=0, Numeric glow=0, Numeric gupp=0, Numeric A=0, Zeeman::Model zeeman=Zeeman::Model(), const LineShape::Model &lineshape=LineShape::Model(), const std::vector< Rational > &lowerquanta={}, const std::vector< Rational > &upperquanta={})
Default initialization.
SingleLine (size_t nbroadeners, size_t nquanta, const LineShape::Model &metamodel)
Initialization for constant sizes.
Index LineShapeElems () const noexcept
Number of lineshape elements.
Index LowerQuantumElems () const noexcept
Number of lower quantum numbers.
Index UpperQuantumElems () const noexcept
Number of upper quantum numbers.
Numeric F0 () const noexcept
Central frequency.
Numeric E0 () const noexcept
Lower level energy.
Numeric I0 () const noexcept
Reference line strength.
Numeric A () const noexcept
Einstein spontaneous emission.
Numeric g_low () const noexcept
Lower level statistical weight.
Numeric g_upp () const noexcept
Upper level statistical weight.
Zeeman::Model Zeeman () const noexcept
Zeeman model.
const LineShape::Model & LineShape () const noexcept
Line shape model.
const std::vector< Rational > & LowerQuantumNumbers () const noexcept
Lower level quantum numbers.
const std::vector< Rational > & UpperQuantumNumbers () const noexcept
Upper level quantum numbers.
Numeric & F0 () noexcept
Central frequency.
Numeric & E0 () noexcept
Lower level energy.
Numeric & I0 () noexcept
Reference line strength.
Numeric & A () noexcept
Einstein spontaneous emission.
Numeric & g_low () noexcept
Lower level statistical weight.
Numeric & g_upp () noexcept
Upper level statistical weight.
Zeeman::Model & Zeeman () noexcept
Zeeman model.
LineShape::Model & LineShape () noexcept
Line shape model.
std::vector< Rational > & LowerQuantumNumbers () noexcept
Lower level quantum numbers.
std::vector< Rational > & UpperQuantumNumbers () noexcept
Upper level quantum numbers.
void F0 (Numeric x) noexcept
Central frequency.
void E0 (Numeric x) noexcept
Lower level energy.
void I0 (Numeric x) noexcept
Reference line strength.
void A (Numeric x) noexcept
Einstein spontaneous emission.
void g_low (Numeric x) noexcept
Lower level statistical weight.
void g_upp (Numeric x) noexcept
Upper level statistical weight.
Rational LowerQuantumNumber (size_t i) const noexcept
Lower quantum number.
Rational UpperQuantumNumber (size_t i) const noexcept
Upper quantum number.
Rational & LowerQuantumNumber (size_t i) noexcept
Lower quantum number.
Rational & UpperQuantumNumber (size_t i) noexcept
Upper quantum number.
bool SameQuantumNumbers (const SingleLine &sl) const noexcept
Checks if the quantum numbers are the same of the two lines.
void SetAutomaticZeeman (QuantumIdentifier qid, const std::vector< QuantumNumberType > &keys)
Set Zeeman effect by automatic detection.
void SetLineMixing2SecondOrderData (const Vector &d)
Set the line mixing model to 2nd order.
void SetLineMixing2AER (const Vector &d)
Set the line mixing model to AER kind.
bifstream & read (bifstream &bif)
Binary read for AbsorptionLines.
bofstream & write (bofstream &bof) const
Binary write for AbsorptionLines.
Private Attributes
Numeric mF0
Central frequency.
Numeric mI0
Reference intensity.
Numeric mE0
Lower state energy level.
Numeric mglow
Lower level statistical weight.
Numeric mgupp
Upper level statistical weight.
Numeric mA
Einstein spontaneous emission coefficient.
Zeeman::Model mzeeman
Zeeman model.
LineShape::Model mlineshape
Line shape model.
std::vector< Rational > mlowerquanta
Lower level quantum numbers.
std::vector< Rational > mupperquanta
Upper level quantum numbers.
Detailed Description
Computations and data for a single absorption line.
Definition at line 246 of file absorptionlines.h.
Constructor & Destructor Documentation
SingleLine() [1/2]
Absorption::SingleLine::SingleLine (Numeric F0 = 0, Numeric I0 = 0, Numeric E0 = 0, Numeric glow = 0, Numeric gupp = 0, Numeric A = 0, Zeeman::Model zeeman = Zeeman::Model(), const LineShape::Model & lineshape = LineShape::Model(), const std::vector< Rational > & lowerquanta = {}, const std::vector< Rational > & upperquanta = {}) inline
Default initialization.
Parameters
[in] F0 Central frequency
[in] I0 Reference line strength at external T0
[in] E0 Lower energy level
[in] glow Lower level statistical weight
[in] gupp Upper level statistical weight
[in] A Einstein spontaneous emission coefficient
[in] zeeman Zeeman model
[in] lineshape Line shape model
[in] lowerquanta Lower quantum numbers
[in] upperquanta Upper quantum numbers
Definition at line 292 of file absorptionlines.h.
SingleLine() [2/2]
Absorption::SingleLine::SingleLine (size_t nbroadeners, size_t nquanta, const LineShape::Model & metamodel) inline
Initialization for constant sizes.
Parameters
[in] nbroadeners Number of broadening species
[in] nquanta Number of local quantum numbers
Definition at line 318 of file absorptionlines.h.
References mlineshape, and LineShape::Model::nelem().
Member Function Documentation
A() [1/3]
Numeric Absorption::SingleLine::A () const inline noexcept
Einstein spontaneous emission.
Definition at line 351 of file absorptionlines.h.
References mA.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
A() [2/3]
Numeric& Absorption::SingleLine::A () inline noexcept
Einstein spontaneous emission.
Definition at line 385 of file absorptionlines.h.
References mA.
A() [3/3]
void Absorption::SingleLine::A (Numeric x) inline noexcept
Einstein spontaneous emission.
Definition at line 419 of file absorptionlines.h.
References mA, and ARTS::Var::x().
E0() [1/3]
Numeric Absorption::SingleLine::E0 () const inline noexcept
Lower level energy.
Definition at line 345 of file absorptionlines.h.
References mE0.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
E0() [2/3]
Numeric& Absorption::SingleLine::E0 () inline noexcept
Lower level energy.
Definition at line 379 of file absorptionlines.h.
References mE0.
E0() [3/3]
void Absorption::SingleLine::E0 (Numeric x) inline noexcept
Lower level energy.
Definition at line 413 of file absorptionlines.h.
References mE0, and ARTS::Var::x().
F0() [1/3]
Numeric Absorption::SingleLine::F0 () const inline noexcept
Central frequency.
Definition at line 342 of file absorptionlines.h.
References mF0.
Referenced by Absorption::operator<<(), Absorption::operator>>(), and Linefunctions::set_lineshape().
F0() [2/3]
Numeric& Absorption::SingleLine::F0 () inline noexcept
Central frequency.
Definition at line 376 of file absorptionlines.h.
References mF0.
F0() [3/3]
void Absorption::SingleLine::F0 (Numeric x) inline noexcept
Central frequency.
Definition at line 410 of file absorptionlines.h.
References mF0, and ARTS::Var::x().
g_low() [1/3]
Numeric Absorption::SingleLine::g_low () const inline noexcept
Lower level statistical weight.
Definition at line 354 of file absorptionlines.h.
References mglow.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
g_low() [2/3]
Numeric& Absorption::SingleLine::g_low () inline noexcept
Lower level statistical weight.
Definition at line 388 of file absorptionlines.h.
References mglow.
g_low() [3/3]
void Absorption::SingleLine::g_low (Numeric x) inline noexcept
Lower level statistical weight.
Definition at line 422 of file absorptionlines.h.
References mglow, and ARTS::Var::x().
g_upp() [1/3]
Numeric Absorption::SingleLine::g_upp () const inline noexcept
Upper level statistical weight.
Definition at line 357 of file absorptionlines.h.
References mgupp.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
g_upp() [2/3]
Numeric& Absorption::SingleLine::g_upp () inline noexcept
Upper level statistical weight.
Definition at line 391 of file absorptionlines.h.
References mgupp.
g_upp() [3/3]
void Absorption::SingleLine::g_upp (Numeric x) inline noexcept
Upper level statistical weight.
Definition at line 425 of file absorptionlines.h.
References mgupp, and ARTS::Var::x().
I0() [1/3]
Numeric Absorption::SingleLine::I0 () const inline noexcept
Reference line strength.
Definition at line 348 of file absorptionlines.h.
References mI0.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
I0() [2/3]
Numeric& Absorption::SingleLine::I0 () inline noexcept
Reference line strength.
Definition at line 382 of file absorptionlines.h.
References mI0.
I0() [3/3]
void Absorption::SingleLine::I0 (Numeric x) inline noexcept
Reference line strength.
Definition at line 416 of file absorptionlines.h.
References mI0, and ARTS::Var::x().
LineShape() [1/2]
const LineShape::Model& Absorption::SingleLine::LineShape () const inline noexcept
Line shape model.
Definition at line 363 of file absorptionlines.h.
References mlineshape.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
LineShape() [2/2]
LineShape::Model& Absorption::SingleLine::LineShape () inline noexcept
Line shape model.
Definition at line 397 of file absorptionlines.h.
References mlineshape.
LineShapeElems()
Index Absorption::SingleLine::LineShapeElems () const inline noexcept
Number of lineshape elements.
Definition at line 329 of file absorptionlines.h.
References mlineshape, and LineShape::Model::nelem().
Referenced by Absorption::Lines::AppendSingleLine().
LowerQuantumElems()
Index Absorption::SingleLine::LowerQuantumElems () const inline noexcept
Number of lower quantum numbers.
Definition at line 332 of file absorptionlines.h.
References mlowerquanta.
Referenced by Absorption::Lines::AppendSingleLine().
LowerQuantumNumber() [1/2]
Rational Absorption::SingleLine::LowerQuantumNumber (size_t i) const inline noexcept
Lower quantum number.
Definition at line 432 of file absorptionlines.h.
References mlowerquanta.
LowerQuantumNumber() [2/2]
Rational& Absorption::SingleLine::LowerQuantumNumber (size_t i) inline noexcept
Lower quantum number.
Definition at line 438 of file absorptionlines.h.
References mlowerquanta.
LowerQuantumNumbers() [1/2]
const std::vector<Rational>& Absorption::SingleLine::LowerQuantumNumbers () const inline noexcept
Lower level quantum numbers.
Definition at line 366 of file absorptionlines.h.
References mlowerquanta.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
LowerQuantumNumbers() [2/2]
std::vector<Rational>& Absorption::SingleLine::LowerQuantumNumbers () inline noexcept
Lower level quantum numbers.
Definition at line 400 of file absorptionlines.h.
References mlowerquanta.
read()
bifstream& Absorption::SingleLine::read (bifstream & bif) inline
Binary read for AbsorptionLines.
Standard parameters
Line shape model
Lower level quantum numbers
Upper level quantum numbers
Definition at line 491 of file absorptionlines.h.
References mA, mE0, mF0, mglow, mgupp, mI0, mlineshape, mlowerquanta, mupperquanta, mzeeman, and LineShape::Model::read().
SameQuantumNumbers()
bool Absorption::SingleLine::SameQuantumNumbers (const SingleLine & sl) const noexcept
Checks if the quantum numbers are the same of the two lines.
Definition at line 2679 of file absorptionlines.cc.
SetAutomaticZeeman()
void Absorption::SingleLine::SetAutomaticZeeman (QuantumIdentifier qid, const std::vector< QuantumNumberType > & keys) inline
Set Zeeman effect by automatic detection.
Will fail if the available and provided quantum numbers are bad
Parameters
[in] qid Copy of the global identifier to fill by local numbers
[in] keys List of quantum number keys in this line's local quantum number lists
Definition at line 457 of file absorptionlines.h.
References QuantumIdentifier::LowerQuantumNumber(), mlowerquanta, mupperquanta, mzeeman, and QuantumIdentifier::UpperQuantumNumber().
SetLineMixing2AER()
void Absorption::SingleLine::SetLineMixing2AER (const Vector & d) inline
Set the line mixing model to AER kind.
Parameters
[in] d Data in AER format
Definition at line 481 of file absorptionlines.h.
References LineShape::Model::Data(), and mlineshape.
SetLineMixing2SecondOrderData()
void Absorption::SingleLine::SetLineMixing2SecondOrderData (const Vector & d) inline
Set the line mixing model to 2nd order.
Parameters
[in] d Data in 2nd order format
Definition at line 470 of file absorptionlines.h.
References mlineshape, LineShape::Model::SetLineMixingModel(), and LineShape::LegacyLineMixingData::vector2modellm().
UpperQuantumElems()
Index Absorption::SingleLine::UpperQuantumElems () const inline noexcept
Number of upper quantum numbers.
Definition at line 335 of file absorptionlines.h.
References mupperquanta.
Referenced by Absorption::Lines::AppendSingleLine().
UpperQuantumNumber() [1/2]
Rational Absorption::SingleLine::UpperQuantumNumber (size_t i) const inline noexcept
Upper quantum number.
Definition at line 435 of file absorptionlines.h.
References mupperquanta.
UpperQuantumNumber() [2/2]
Rational& Absorption::SingleLine::UpperQuantumNumber (size_t i) inline noexcept
Upper quantum number.
Definition at line 441 of file absorptionlines.h.
References mupperquanta.
UpperQuantumNumbers() [1/2]
const std::vector<Rational>& Absorption::SingleLine::UpperQuantumNumbers () const inline noexcept
Upper level quantum numbers.
Definition at line 369 of file absorptionlines.h.
References mupperquanta.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
UpperQuantumNumbers() [2/2]
std::vector<Rational>& Absorption::SingleLine::UpperQuantumNumbers () inline noexcept
Upper level quantum numbers.
Definition at line 403 of file absorptionlines.h.
References mupperquanta.
write()
bofstream& Absorption::SingleLine::write (bofstream & bof) const inline
Binary write for AbsorptionLines.
Standard parameters
Line shape model
Lower level quantum numbers
Upper level quantum numbers
Definition at line 508 of file absorptionlines.h.
References mA, mE0, mF0, mglow, mgupp, mI0, mlineshape, mlowerquanta, mupperquanta, mzeeman, and LineShape::Model::write().
Zeeman() [1/2]
Zeeman::Model Absorption::SingleLine::Zeeman () const inline noexcept
Zeeman model.
Definition at line 360 of file absorptionlines.h.
References mzeeman.
Referenced by Absorption::operator<<(), and Absorption::operator>>().
Zeeman() [2/2]
Zeeman::Model& Absorption::SingleLine::Zeeman () inline noexcept
Zeeman model.
Definition at line 394 of file absorptionlines.h.
References mzeeman.
Member Data Documentation
mA
Numeric Absorption::SingleLine::mA private
Einstein spontaneous emission coefficient.
Definition at line 264 of file absorptionlines.h.
Referenced by A(), read(), and write().
mE0
Numeric Absorption::SingleLine::mE0 private
Lower state energy level.
Definition at line 255 of file absorptionlines.h.
Referenced by E0(), read(), and write().
mF0
Numeric Absorption::SingleLine::mF0 private
Central frequency.
Definition at line 249 of file absorptionlines.h.
Referenced by F0(), read(), and write().
mglow
Numeric Absorption::SingleLine::mglow private
Lower level statistical weight.
Definition at line 258 of file absorptionlines.h.
Referenced by g_low(), read(), and write().
mgupp
Numeric Absorption::SingleLine::mgupp private
Upper level statistical weight.
Definition at line 261 of file absorptionlines.h.
Referenced by g_upp(), read(), and write().
mI0
Numeric Absorption::SingleLine::mI0 private
Reference intensity.
Definition at line 252 of file absorptionlines.h.
Referenced by I0(), read(), and write().
mlineshape
LineShape::Model Absorption::SingleLine::mlineshape private
Line shape model.
Definition at line 270 of file absorptionlines.h.
Referenced by LineShape(), LineShapeElems(), read(), SetLineMixing2AER(), SetLineMixing2SecondOrderData(), SingleLine(), and write().
mlowerquanta
std::vector<Rational> Absorption::SingleLine::mlowerquanta private
Lower level quantum numbers.
Definition at line 273 of file absorptionlines.h.
Referenced by LowerQuantumElems(), LowerQuantumNumber(), LowerQuantumNumbers(), read(), SetAutomaticZeeman(), and write().
mupperquanta
std::vector<Rational> Absorption::SingleLine::mupperquanta private
Upper level quantum numbers.
Definition at line 276 of file absorptionlines.h.
Referenced by read(), SetAutomaticZeeman(), UpperQuantumElems(), UpperQuantumNumber(), UpperQuantumNumbers(), and write().
mzeeman
Zeeman::Model Absorption::SingleLine::mzeeman private
Zeeman model.
Definition at line 267 of file absorptionlines.h.
Referenced by read(), SetAutomaticZeeman(), write(), and Zeeman().
The documentation for this class was generated from the following files:
absorptionlines.h
absorptionlines.cc