ARTS: ARTS::Var::WorkspaceArrayOfXsecRecord Class Reference
ARTS::Var::WorkspaceArrayOfXsecRecord Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfXsecRecord () noexcept
WorkspaceArrayOfXsecRecord (std::size_t i, void *x) noexcept
~WorkspaceArrayOfXsecRecord () noexcept
WorkspaceArrayOfXsecRecord (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfXsecRecord & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfXsecRecord
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 980 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfXsecRecord::type = Group::ArrayOfXsecRecord private
Definition at line 981 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfXsecRecord() [1/3]
ARTS::Var::WorkspaceArrayOfXsecRecord::WorkspaceArrayOfXsecRecord () inline noexcept
Definition at line 985 of file autoarts.h.
WorkspaceArrayOfXsecRecord() [2/3]
ARTS::Var::WorkspaceArrayOfXsecRecord::WorkspaceArrayOfXsecRecord (std::size_t i, void * x) inline noexcept
Definition at line 986 of file autoarts.h.
~WorkspaceArrayOfXsecRecord()
ARTS::Var::WorkspaceArrayOfXsecRecord::~WorkspaceArrayOfXsecRecord () inline noexcept
Definition at line 987 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfXsecRecord() [3/3]
ARTS::Var::WorkspaceArrayOfXsecRecord::WorkspaceArrayOfXsecRecord (const type & val) inline noexcept
Definition at line 988 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfXsecRecord::islast () const inline noexcept
Definition at line 994 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfXsecRecord().
isnull()
bool ARTS::Var::WorkspaceArrayOfXsecRecord::isnull () const inline noexcept
Definition at line 993 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfXsecRecord().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfXsecRecord::name () const inline noexcept
Definition at line 995 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfXsecRecord& ARTS::Var::WorkspaceArrayOfXsecRecord::operator= (const type & t) inline noexcept
Definition at line 991 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfXsecRecord::pos () const inline noexcept
Definition at line 992 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfXsecRecord::value () const inline noexcept
Definition at line 990 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfXsecRecord::value () inline noexcept
Definition at line 989 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfXsecRecord::p private
Definition at line 982 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfXsecRecord::v private
Definition at line 983 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfXsecRecord().
The documentation for this class was generated from the following file:
autoarts.h