ARTS: ARTS::Var::ScatteringMetaData Class Reference
ARTS::Var::ScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
ScatteringMetaData () noexcept
ScatteringMetaData (std::size_t i, void *x) noexcept
ScatteringMetaData (const Group::ScatteringMetaData &val) noexcept
~ScatteringMetaData () noexcept
Group::ScatteringMetaData & value () noexcept
const Group::ScatteringMetaData & value () const noexcept
ScatteringMetaData & operator= (const Group::ScatteringMetaData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ScatteringMetaData * v
Friends
std::ostream & operator<< (std::ostream &os, const ScatteringMetaData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3704 of file autoarts.h.
Constructor & Destructor Documentation
ScatteringMetaData() [1/3]
ARTS::Var::ScatteringMetaData::ScatteringMetaData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3709 of file autoarts.h.
ScatteringMetaData() [2/3]
ARTS::Var::ScatteringMetaData::ScatteringMetaData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3712 of file autoarts.h.
ScatteringMetaData() [3/3]
ARTS::Var::ScatteringMetaData::ScatteringMetaData (const Group::ScatteringMetaData & val) inline noexcept
Construct from Group::ScatteringMetaData. Leaves islast() true and isnull() false
Definition at line 3715 of file autoarts.h.
~ScatteringMetaData()
ARTS::Var::ScatteringMetaData::~ScatteringMetaData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3718 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ScatteringMetaData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3736 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ScatteringMetaData().
isnull()
bool ARTS::Var::ScatteringMetaData::isnull () const inline noexcept
Return true if there is no data
Definition at line 3733 of file autoarts.h.
References v.
Referenced by ~ScatteringMetaData().
name()
const Group::String& ARTS::Var::ScatteringMetaData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3739 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ScatteringMetaData& ARTS::Var::ScatteringMetaData::operator= (const Group::ScatteringMetaData & t) inline noexcept
Set value from Group::ScatteringMetaData. Works when isnull() is false
Definition at line 3727 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ScatteringMetaData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3730 of file autoarts.h.
References p.
value() [1/2]
const Group::ScatteringMetaData& ARTS::Var::ScatteringMetaData::value () const inline noexcept
Get value const-ref as Group::ScatteringMetaData. Works when isnull() is false
Definition at line 3724 of file autoarts.h.
References v.
value() [2/2]
Group::ScatteringMetaData& ARTS::Var::ScatteringMetaData::value () inline noexcept
Get value ref as Group::ScatteringMetaData. Works when isnull() is false
Definition at line 3721 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ScatteringMetaData & var) friend
Output to stream of internal variable
Definition at line 3742 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ScatteringMetaData::p private
Definition at line 3705 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ScatteringMetaData* ARTS::Var::ScatteringMetaData::v private
Definition at line 3706 of file autoarts.h.
Referenced by isnull(), value(), and ~ScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h