ARTS: ARTS::Var::ArrayOfGriddedField1 Class Reference
ARTS::Var::ArrayOfGriddedField1 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfGriddedField1 () noexcept
ArrayOfGriddedField1 (std::size_t i, void *x) noexcept
ArrayOfGriddedField1 (const Group::ArrayOfGriddedField1 &val) noexcept
~ArrayOfGriddedField1 () noexcept
Group::ArrayOfGriddedField1 & value () noexcept
const Group::ArrayOfGriddedField1 & value () const noexcept
ArrayOfGriddedField1 & operator= (const Group::ArrayOfGriddedField1 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfGriddedField1 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfGriddedField1 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1405 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfGriddedField1() [1/3]
ARTS::Var::ArrayOfGriddedField1::ArrayOfGriddedField1 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1410 of file autoarts.h.
ArrayOfGriddedField1() [2/3]
ARTS::Var::ArrayOfGriddedField1::ArrayOfGriddedField1 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1413 of file autoarts.h.
ArrayOfGriddedField1() [3/3]
ARTS::Var::ArrayOfGriddedField1::ArrayOfGriddedField1 (const Group::ArrayOfGriddedField1 & val) inline noexcept
Construct from Group::ArrayOfGriddedField1. Leaves islast() true and isnull() false
Definition at line 1416 of file autoarts.h.
~ArrayOfGriddedField1()
ARTS::Var::ArrayOfGriddedField1::~ArrayOfGriddedField1 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1419 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfGriddedField1::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1437 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfGriddedField1().
isnull()
bool ARTS::Var::ArrayOfGriddedField1::isnull () const inline noexcept
Return true if there is no data
Definition at line 1434 of file autoarts.h.
References v.
Referenced by ~ArrayOfGriddedField1().
name()
const Group::String& ARTS::Var::ArrayOfGriddedField1::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1440 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfGriddedField1& ARTS::Var::ArrayOfGriddedField1::operator= (const Group::ArrayOfGriddedField1 & t) inline noexcept
Set value from Group::ArrayOfGriddedField1. Works when isnull() is false
Definition at line 1428 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfGriddedField1::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1431 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::ArrayOfGriddedFieldGetNames(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfGriddedField1& ARTS::Var::ArrayOfGriddedField1::value () const inline noexcept
Get value const-ref as Group::ArrayOfGriddedField1. Works when isnull() is false
Definition at line 1425 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfGriddedField1& ARTS::Var::ArrayOfGriddedField1::value () inline noexcept
Get value ref as Group::ArrayOfGriddedField1. Works when isnull() is false
Definition at line 1422 of file autoarts.h.
References v.
Referenced by ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfGriddedField1 & var) friend
Output to stream of internal variable
Definition at line 1443 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfGriddedField1::p private
Definition at line 1406 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfGriddedField1* ARTS::Var::ArrayOfGriddedField1::v private
Definition at line 1407 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfGriddedField1().
The documentation for this class was generated from the following file:
autoarts.h