ARTS: ARTS::Var::WorkspaceArrayOfTensor6 Class Reference
ARTS::Var::WorkspaceArrayOfTensor6 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTensor6 () noexcept
WorkspaceArrayOfTensor6 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTensor6 () noexcept
WorkspaceArrayOfTensor6 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTensor6 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor6
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 890 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTensor6::type = Group::ArrayOfTensor6 private
Definition at line 891 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTensor6() [1/3]
ARTS::Var::WorkspaceArrayOfTensor6::WorkspaceArrayOfTensor6 () inline noexcept
Definition at line 895 of file autoarts.h.
WorkspaceArrayOfTensor6() [2/3]
ARTS::Var::WorkspaceArrayOfTensor6::WorkspaceArrayOfTensor6 (std::size_t i, void * x) inline noexcept
Definition at line 896 of file autoarts.h.
~WorkspaceArrayOfTensor6()
ARTS::Var::WorkspaceArrayOfTensor6::~WorkspaceArrayOfTensor6 () inline noexcept
Definition at line 897 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTensor6() [3/3]
ARTS::Var::WorkspaceArrayOfTensor6::WorkspaceArrayOfTensor6 (const type & val) inline noexcept
Definition at line 898 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTensor6::islast () const inline noexcept
Definition at line 904 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTensor6().
isnull()
bool ARTS::Var::WorkspaceArrayOfTensor6::isnull () const inline noexcept
Definition at line 903 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTensor6().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTensor6::name () const inline noexcept
Definition at line 905 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTensor6& ARTS::Var::WorkspaceArrayOfTensor6::operator= (const type & t) inline noexcept
Definition at line 901 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTensor6::pos () const inline noexcept
Definition at line 902 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTensor6::value () const inline noexcept
Definition at line 900 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTensor6::value () inline noexcept
Definition at line 899 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTensor6::p private
Definition at line 892 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTensor6::v private
Definition at line 893 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTensor6().
The documentation for this class was generated from the following file:
autoarts.h