ARTS: ARTS::Var::ArrayOfScatteringMetaData Class Reference
ARTS::Var::ArrayOfScatteringMetaData Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfScatteringMetaData () noexcept
ArrayOfScatteringMetaData (std::size_t i, void *x) noexcept
ArrayOfScatteringMetaData (const Group::ArrayOfScatteringMetaData &val) noexcept
~ArrayOfScatteringMetaData () noexcept
Group::ArrayOfScatteringMetaData & value () noexcept
const Group::ArrayOfScatteringMetaData & value () const noexcept
ArrayOfScatteringMetaData & operator= (const Group::ArrayOfScatteringMetaData &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfScatteringMetaData * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfScatteringMetaData &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1974 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfScatteringMetaData() [1/3]
ARTS::Var::ArrayOfScatteringMetaData::ArrayOfScatteringMetaData () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1979 of file autoarts.h.
ArrayOfScatteringMetaData() [2/3]
ARTS::Var::ArrayOfScatteringMetaData::ArrayOfScatteringMetaData (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1982 of file autoarts.h.
ArrayOfScatteringMetaData() [3/3]
ARTS::Var::ArrayOfScatteringMetaData::ArrayOfScatteringMetaData (const Group::ArrayOfScatteringMetaData & val) inline noexcept
Construct from Group::ArrayOfScatteringMetaData. Leaves islast() true and isnull() false
Definition at line 1985 of file autoarts.h.
~ArrayOfScatteringMetaData()
ARTS::Var::ArrayOfScatteringMetaData::~ArrayOfScatteringMetaData () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1988 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfScatteringMetaData::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2006 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfScatteringMetaData().
isnull()
bool ARTS::Var::ArrayOfScatteringMetaData::isnull () const inline noexcept
Return true if there is no data
Definition at line 2003 of file autoarts.h.
References v.
Referenced by ~ArrayOfScatteringMetaData().
name()
const Group::String& ARTS::Var::ArrayOfScatteringMetaData::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2009 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfScatteringMetaData& ARTS::Var::ArrayOfScatteringMetaData::operator= (const Group::ArrayOfScatteringMetaData & t) inline noexcept
Set value from Group::ArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 1997 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfScatteringMetaData::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2000 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfScatteringMetaData& ARTS::Var::ArrayOfScatteringMetaData::value () const inline noexcept
Get value const-ref as Group::ArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 1994 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfScatteringMetaData& ARTS::Var::ArrayOfScatteringMetaData::value () inline noexcept
Get value ref as Group::ArrayOfScatteringMetaData. Works when isnull() is false
Definition at line 1991 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfScatteringMetaData & var) friend
Output to stream of internal variable
Definition at line 2012 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfScatteringMetaData::p private
Definition at line 1975 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfScatteringMetaData* ARTS::Var::ArrayOfScatteringMetaData::v private
Definition at line 1976 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfScatteringMetaData().
The documentation for this class was generated from the following file:
autoarts.h