ARTS: EnergyLevelMap Class Reference
EnergyLevelMap Class Reference
#include <energylevelmap.h>
Public Member Functions
bool OK () const noexcept
void ThrowIfNotOK () const ARTS_NOEXCEPT
EnergyLevelMap ()
EnergyLevelMap (EnergyLevelMapType new_type, Index pages, Index rows, Index cols, const EnergyLevelMap &old)
EnergyLevelMap (const Tensor4 &data, const ArrayOfQuantumIdentifier &levels, const Vector &energies=Vector(0))
EnergyLevelMap (const Matrix &data, const ArrayOfQuantumIdentifier &levels, const Vector &energies=Vector(0))
EnergyLevelMap (const Vector &data, const ArrayOfQuantumIdentifier &levels, const Vector &energies=Vector(0))
EnergyLevelMap InterpToGridPos (Index atmosphere_dim, const ArrayOfGridPos &p, const ArrayOfGridPos &lat, const ArrayOfGridPos &lon) const
EnergyLevelMap operator[] (Index ip) const
EnergyLevelMap operator() (Index ip, Index ilat, Index ilon) const
EnergyLevelMapType Type () const noexcept
Energy level type.
const ArrayOfQuantumIdentifier & Levels () const noexcept
Energy level type.
const Vector & Energies () const noexcept
Energy level type.
const Tensor4 & Data () const noexcept
Energy level type.
EnergyLevelMapType & Type () noexcept
Energy level type.
ArrayOfQuantumIdentifier & Levels () noexcept
Energy level type.
Vector & Energies () noexcept
Energy level type.
Tensor4 & Data () noexcept
Energy level type.
void Type (EnergyLevelMapType x) noexcept
Energy level type.
Output2 get_ratio_params (const AbsorptionLines &band, const Index &line_index) const
Get the output required for Population::NLTE.
Output4 get_vibtemp_params (const AbsorptionLines &band, const Index &line_index, const Numeric T) const
Get the output required for Population::NLTE-VibrationalTemperatures.
Static Public Member Functions
static bool validIndexForType (Index x) noexcept
static EnergyLevelMapType string2Type (const String &s) noexcept
Private Attributes
EnergyLevelMapType mtype
ArrayOfQuantumIdentifier mlevels
Vector mvib_energy
Tensor4 mvalue
Detailed Description
Definition at line 60 of file energylevelmap.h.
Constructor & Destructor Documentation
EnergyLevelMap() [1/5]
EnergyLevelMap::EnergyLevelMap () inline
Definition at line 72 of file energylevelmap.h.
Referenced by InterpToGridPos(), operator()(), and operator[]().
EnergyLevelMap() [2/5]
EnergyLevelMap::EnergyLevelMap (EnergyLevelMapType new_type, Index pages, Index rows, Index cols, const EnergyLevelMap & old) inline
Definition at line 75 of file energylevelmap.h.
References ThrowIfNotOK().
EnergyLevelMap() [3/5]
EnergyLevelMap::EnergyLevelMap (const Tensor4 & data, const ArrayOfQuantumIdentifier & levels, const Vector & energies = Vector(0))
Definition at line 120 of file energylevelmap.cc.
References Tensor3_t, and ThrowIfNotOK().
EnergyLevelMap() [4/5]
EnergyLevelMap::EnergyLevelMap (const Matrix & data, const ArrayOfQuantumIdentifier & levels, const Vector & energies = Vector(0))
Definition at line 129 of file energylevelmap.cc.
References data, joker, mvalue, and ThrowIfNotOK().
EnergyLevelMap() [5/5]
EnergyLevelMap::EnergyLevelMap (const Vector & data, const ArrayOfQuantumIdentifier & levels, const Vector & energies = Vector(0))
Definition at line 139 of file energylevelmap.cc.
References data, joker, mvalue, and ThrowIfNotOK().
Member Function Documentation
Data() [1/2]
const Tensor4& EnergyLevelMap::Data () const inline noexcept
Energy level type.
Definition at line 108 of file energylevelmap.h.
References mvalue.
Referenced by AtmFieldsCalcExpand1D(), operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Data() [2/2]
Tensor4& EnergyLevelMap::Data () inline noexcept
Energy level type.
Definition at line 120 of file energylevelmap.h.
References mvalue.
Energies() [1/2]
const Vector& EnergyLevelMap::Energies () const inline noexcept
Energy level type.
Definition at line 105 of file energylevelmap.h.
References mvib_energy.
Referenced by operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Energies() [2/2]
Vector& EnergyLevelMap::Energies () inline noexcept
Energy level type.
Definition at line 117 of file energylevelmap.h.
References mvib_energy.
get_ratio_params()
Output2 EnergyLevelMap::get_ratio_params (const AbsorptionLines & band, const Index & line_index) const
Get the output required for Population::NLTE.
Parameters
[in] transition A line-by-line transition
Returns
Upper and lower level distributions
Definition at line 58 of file energylevelmap.cc.
References ARTS_USER_ERROR_IF, mlevels, mtype, mvalue, Numeric_t, and ARTS::Var::x().
Referenced by LineShape::linestrength_selection(), and Linefunctions::set_cross_section_of_band().
get_vibtemp_params()
Output4 EnergyLevelMap::get_vibtemp_params (const AbsorptionLines & band, const Index & line_index, const Numeric T) const
Get the output required for Population::NLTE-VibrationalTemperatures.
Parameters
[in] transition A line-by-line transition
Returns
Upper and lower level distributions and energies
Definition at line 86 of file energylevelmap.cc.
References ARTS_USER_ERROR_IF, mlevels, mtype, mvalue, mvib_energy, Array< base >::nelem(), Numeric_t, and ARTS::Var::x().
Referenced by LineShape::linestrength_selection(), and Linefunctions::set_cross_section_of_band().
InterpToGridPos()
EnergyLevelMap EnergyLevelMap::InterpToGridPos (Index atmosphere_dim, const ArrayOfGridPos & p, const ArrayOfGridPos & lat, const ArrayOfGridPos & lon) const
Definition at line 149 of file energylevelmap.cc.
References ARTS_USER_ERROR_IF, ARTS::Var::atmosphere_dim(), EnergyLevelMap(), interp_atmfield_by_itw(), interp_atmfield_gp2itw(), joker, ARTS::Var::lat(), ARTS::Var::lon(), mlevels, mtype, mvalue, Array< base >::nelem(), None_t, Tensor3_t, and Vector_t.
Levels() [1/2]
const ArrayOfQuantumIdentifier& EnergyLevelMap::Levels () const inline noexcept
Energy level type.
Definition at line 102 of file energylevelmap.h.
References mlevels.
Referenced by operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Levels() [2/2]
ArrayOfQuantumIdentifier& EnergyLevelMap::Levels () inline noexcept
Energy level type.
Definition at line 114 of file energylevelmap.h.
References mlevels.
OK()
bool EnergyLevelMap::OK () const noexcept
Definition at line 31 of file energylevelmap.cc.
References mlevels, mtype, mvalue, mvib_energy, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), None_t, ConstTensor4View::npages(), ConstTensor4View::nrows(), Numeric_t, Tensor3_t, and Vector_t.
Referenced by ThrowIfNotOK().
operator()()
EnergyLevelMap EnergyLevelMap::operator() (Index ip, Index ilat, Index ilon) const
Definition at line 224 of file energylevelmap.cc.
References ARTS_USER_ERROR_IF, EnergyLevelMap(), joker, mtype, mvalue, None_t, Numeric_t, and Tensor3_t.
operator[]()
EnergyLevelMap EnergyLevelMap::operator[] (Index ip) const
Definition at line 169 of file energylevelmap.cc.
References ARTS_USER_ERROR_IF, EnergyLevelMap(), joker, mtype, mvalue, ConstTensor4View::ncols(), None_t, Numeric_t, and Vector_t.
string2Type()
static EnergyLevelMapType EnergyLevelMap::string2Type (const String & s) inline static noexcept
Definition at line 135 of file energylevelmap.h.
References None_t, Numeric_t, Tensor3_t, and Vector_t.
ThrowIfNotOK()
void EnergyLevelMap::ThrowIfNotOK () const inline
Definition at line 70 of file energylevelmap.h.
References ARTS_ASSERT, and OK().
Referenced by EnergyLevelMap(), and xml_read_from_stream().
Type() [1/3]
EnergyLevelMapType EnergyLevelMap::Type () const inline noexcept
Energy level type.
Definition at line 99 of file energylevelmap.h.
References mtype.
Referenced by operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Type() [2/3]
EnergyLevelMapType& EnergyLevelMap::Type () inline noexcept
Energy level type.
Definition at line 111 of file energylevelmap.h.
References mtype.
Type() [3/3]
void EnergyLevelMap::Type (EnergyLevelMapType x) inline noexcept
Energy level type.
Definition at line 133 of file energylevelmap.h.
References mtype, and ARTS::Var::x().
validIndexForType()
static bool EnergyLevelMap::validIndexForType (Index x) inline static noexcept
Definition at line 126 of file energylevelmap.h.
References None_t, Numeric_t, stdarrayify(), Tensor3_t, Vector_t, ARTS::Var::x(), and ARTS::Var::y().
Member Data Documentation
mlevels
ArrayOfQuantumIdentifier EnergyLevelMap::mlevels private
Definition at line 63 of file energylevelmap.h.
Referenced by get_ratio_params(), get_vibtemp_params(), InterpToGridPos(), Levels(), and OK().
mtype
EnergyLevelMapType EnergyLevelMap::mtype private
Definition at line 62 of file energylevelmap.h.
Referenced by get_ratio_params(), get_vibtemp_params(), InterpToGridPos(), OK(), operator()(), operator[](), and Type().
mvalue
Tensor4 EnergyLevelMap::mvalue private
Definition at line 65 of file energylevelmap.h.
Referenced by Data(), EnergyLevelMap(), get_ratio_params(), get_vibtemp_params(), InterpToGridPos(), OK(), operator()(), and operator[]().
mvib_energy
Vector EnergyLevelMap::mvib_energy private
Definition at line 64 of file energylevelmap.h.
Referenced by Energies(), get_vibtemp_params(), and OK().
The documentation for this class was generated from the following files:
energylevelmap.h
energylevelmap.cc