ARTS: ARTS::Var::ArrayOfArrayOfMatrix Class Reference
ARTS::Var::ArrayOfArrayOfMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfArrayOfMatrix () noexcept
ArrayOfArrayOfMatrix (std::size_t i, void *x) noexcept
ArrayOfArrayOfMatrix (const Group::ArrayOfArrayOfMatrix &val) noexcept
~ArrayOfArrayOfMatrix () noexcept
Group::ArrayOfArrayOfMatrix & value () noexcept
const Group::ArrayOfArrayOfMatrix & value () const noexcept
ArrayOfArrayOfMatrix & operator= (const Group::ArrayOfArrayOfMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfArrayOfMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 754 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfArrayOfMatrix() [1/3]
ARTS::Var::ArrayOfArrayOfMatrix::ArrayOfArrayOfMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 759 of file autoarts.h.
ArrayOfArrayOfMatrix() [2/3]
ARTS::Var::ArrayOfArrayOfMatrix::ArrayOfArrayOfMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 762 of file autoarts.h.
ArrayOfArrayOfMatrix() [3/3]
ARTS::Var::ArrayOfArrayOfMatrix::ArrayOfArrayOfMatrix (const Group::ArrayOfArrayOfMatrix & val) inline noexcept
Construct from Group::ArrayOfArrayOfMatrix. Leaves islast() true and isnull() false
Definition at line 765 of file autoarts.h.
~ArrayOfArrayOfMatrix()
ARTS::Var::ArrayOfArrayOfMatrix::~ArrayOfArrayOfMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 768 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfArrayOfMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 786 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Select(), ARTS::Agenda::Method::Select(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~ArrayOfArrayOfMatrix().
isnull()
bool ARTS::Var::ArrayOfArrayOfMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 783 of file autoarts.h.
References v.
Referenced by ~ArrayOfArrayOfMatrix().
name()
const Group::String& ARTS::Var::ArrayOfArrayOfMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 789 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfArrayOfMatrix& ARTS::Var::ArrayOfArrayOfMatrix::operator= (const Group::ArrayOfArrayOfMatrix & t) inline noexcept
Set value from Group::ArrayOfArrayOfMatrix. Works when isnull() is false
Definition at line 777 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfArrayOfMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 780 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::Select(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::ArrayOfArrayOfMatrix& ARTS::Var::ArrayOfArrayOfMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfArrayOfMatrix. Works when isnull() is false
Definition at line 774 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfArrayOfMatrix& ARTS::Var::ArrayOfArrayOfMatrix::value () inline noexcept
Get value ref as Group::ArrayOfArrayOfMatrix. Works when isnull() is false
Definition at line 771 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfMatrix & var) friend
Output to stream of internal variable
Definition at line 792 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfArrayOfMatrix::p private
Definition at line 755 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfArrayOfMatrix* ARTS::Var::ArrayOfArrayOfMatrix::v private
Definition at line 756 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfArrayOfMatrix().
The documentation for this class was generated from the following file:
autoarts.h