ARTS: ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2 Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfGriddedField2 () noexcept
WorkspaceArrayOfArrayOfGriddedField2 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfGriddedField2 () noexcept
WorkspaceArrayOfArrayOfGriddedField2 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfGriddedField2 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfGriddedField2
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 224 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::type = Group::ArrayOfArrayOfGriddedField2 private
Definition at line 225 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfGriddedField2() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::WorkspaceArrayOfArrayOfGriddedField2 () inline noexcept
Definition at line 229 of file autoarts.h.
WorkspaceArrayOfArrayOfGriddedField2() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::WorkspaceArrayOfArrayOfGriddedField2 (std::size_t i, void * x) inline noexcept
Definition at line 230 of file autoarts.h.
~WorkspaceArrayOfArrayOfGriddedField2()
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::~WorkspaceArrayOfArrayOfGriddedField2 () inline noexcept
Definition at line 231 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfGriddedField2() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::WorkspaceArrayOfArrayOfGriddedField2 (const type & val) inline noexcept
Definition at line 232 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::islast () const inline noexcept
Definition at line 238 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfGriddedField2().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::isnull () const inline noexcept
Definition at line 237 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfGriddedField2().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::name () const inline noexcept
Definition at line 239 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfGriddedField2& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::operator= (const type & t) inline noexcept
Definition at line 235 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::pos () const inline noexcept
Definition at line 236 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::value () const inline noexcept
Definition at line 234 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::value () inline noexcept
Definition at line 233 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::p private
Definition at line 226 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfGriddedField2::v private
Definition at line 227 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfGriddedField2().
The documentation for this class was generated from the following file:
autoarts.h