ARTS: ARTS::Var::TessemNN Class Reference
ARTS::Var::TessemNN Class Reference
#include <autoarts.h>
Public Member Functions
TessemNN () noexcept
TessemNN (std::size_t i, void *x) noexcept
~TessemNN () noexcept
TessemNN (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
TessemNN & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::TessemNN
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1594 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::TessemNN::type = Group::TessemNN private
Definition at line 1595 of file autoarts.h.
Constructor & Destructor Documentation
TessemNN() [1/3]
ARTS::Var::TessemNN::TessemNN () inline noexcept
Definition at line 1599 of file autoarts.h.
Referenced by ARTS::Var::mc_antenna().
TessemNN() [2/3]
ARTS::Var::TessemNN::TessemNN (std::size_t i, void * x) inline noexcept
Definition at line 1600 of file autoarts.h.
~TessemNN()
ARTS::Var::TessemNN::~TessemNN () inline noexcept
Definition at line 1601 of file autoarts.h.
Referenced by ARTS::Var::mc_antenna().
TessemNN() [3/3]
ARTS::Var::TessemNN::TessemNN (const type & val) inline noexcept
Definition at line 1602 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::TessemNN::islast () const inline noexcept
Definition at line 1608 of file autoarts.h.
References ARTS::Var::ArrayOfIndex::v.
Referenced by ARTS::Var::mc_antenna().
isnull()
bool ARTS::Var::TessemNN::isnull () const inline noexcept
Definition at line 1607 of file autoarts.h.
References ARTS::Var::ArrayOfIndex::islast(), isnull(), and ARTS::Var::ArrayOfIndex::v.
Referenced by isnull(), and ARTS::Var::mc_antenna().
name()
const Group::String& ARTS::Var::TessemNN::name () const inline noexcept
Definition at line 1609 of file autoarts.h.
operator=()
TessemNN& ARTS::Var::TessemNN::operator= (const type & t) inline noexcept
Definition at line 1605 of file autoarts.h.
pos()
std::size_t ARTS::Var::TessemNN::pos () const inline noexcept
Definition at line 1606 of file autoarts.h.
value() [1/2]
const type& ARTS::Var::TessemNN::value () const inline noexcept
Definition at line 1604 of file autoarts.h.
value() [2/2]
type& ARTS::Var::TessemNN::value () inline noexcept
Definition at line 1603 of file autoarts.h.
Referenced by ARTS::Var::mc_antenna(), and ARTS::Var::mc_iteration_count().
Member Data Documentation
p
std::size_t ARTS::Var::TessemNN::p private
Definition at line 1596 of file autoarts.h.
Referenced by ARTS::Var::mc_antenna(), and ARTS::Var::mc_max_iter().
v
type* ARTS::Var::TessemNN::v private
Definition at line 1597 of file autoarts.h.
Referenced by ARTS::Var::mc_antenna().
The documentation for this class was generated from the following file:
autoarts.h