ARTS: Jacobian::Target Class Reference
Jacobian::Target Class Reference
Holds all information required for individual partial derivatives.
#include <jacobian.h>
Public Member Functions
constexpr Target (Atm type) noexcept
Atmospheric type.
constexpr Target (Line type, const QuantumIdentifier &qid, const Index pos=-std::numeric_limits< Index >::max()) noexcept
Line type.
constexpr Target (Sensor type) noexcept
Sensor type.
constexpr Target (Special type, const QuantumIdentifier &qid) noexcept
Special type.
constexpr Target () noexcept
A defaultable none-type.
void Perturbation (Numeric x) noexcept
Perturbation.
Numeric & Perturbation () noexcept
Numeric Perturbation () const noexcept
void QuantumIdentity (const QuantumIdentifier &x) noexcept
ID.
QuantumIdentifier & QuantumIdentity () noexcept
const QuantumIdentifier & QuantumIdentity () const noexcept
bool operator== (const Target &other) const noexcept
Equality.
constexpr Line LineType () const
Return the line type.
constexpr Atm AtmType () const
Return the atm type.
constexpr bool operator== (Atm other) const noexcept
Checks if the type of jacobian is the input atmospheric parameter.
constexpr bool operator== (Line other) const noexcept
Checks if the type of jacobian is the input line parameter.
constexpr bool operator== (Sensor other) const noexcept
Checks if the type of jacobian is the input sensor parameter.
constexpr bool operator== (Special other) const noexcept
Checks if the type of jacobian is the input sensor parameter.
constexpr bool operator== (Type other) const noexcept
Checks if the type is correct.
constexpr std::string_view TargetType () const noexcept
Return type as string.
constexpr void TargetType (const std::string_view &s) noexcept
Sets target based on a string.
constexpr bool TargetTypeOK () const noexcept
Are we good?
constexpr std::string_view TargetSubType () const noexcept
Return sub type as string.
constexpr void TargetSubType (const std::string_view &s) noexcept
Sets target based on a string.
constexpr bool TargetSubTypeOK () const noexcept
Are we good?
constexpr bool isSpeciesVMR () const noexcept
Special species case.
constexpr bool isWind () const noexcept
Special wind case.
constexpr bool isMagnetic () const noexcept
Special magnetic field case.
constexpr bool isFrequency () const noexcept
Special frequency case.
constexpr bool isPointing () const noexcept
Special pointing case.
constexpr bool needQuantumIdentity () const noexcept
Does this type need the QuantumIdentifier?
constexpr Index Position () const
Position for cases that requires it.
constexpr Index & Position ()
Position for cases that requires it.
constexpr void Position (Index pos)
Position for cases that requires it.
Private Attributes
Type mtype
! Type of quantity, never set manually
TypeOfTarget msubtype
Type of quantity, set manually.
Numeric mperturbation
Perturbations for methods where theoretical computations are impossible or plain slow.
QuantumIdentifier mqid
ID for the Line types of partial derivatives.
Index position
A position for a Target that requires it.
Detailed Description
Holds all information required for individual partial derivatives.
Definition at line 146 of file jacobian.h.
Constructor & Destructor Documentation
Target() [1/5]
constexpr Jacobian::Target::Target (Atm type) inline explicit constexpr noexcept
Atmospheric type.
Definition at line 165 of file jacobian.h.
Target() [2/5]
constexpr Jacobian::Target::Target (Line type, const QuantumIdentifier & qid, const Index pos = -std::numeric_limits<Index>::max()) inline explicit constexpr noexcept
Line type.
Definition at line 168 of file jacobian.h.
Target() [3/5]
constexpr Jacobian::Target::Target (Sensor type) inline explicit constexpr noexcept
Sensor type.
Definition at line 171 of file jacobian.h.
Target() [4/5]
constexpr Jacobian::Target::Target (Special type, const QuantumIdentifier & qid) inline explicit constexpr noexcept
Special type.
Definition at line 174 of file jacobian.h.
Target() [5/5]
constexpr Jacobian::Target::Target () inline constexpr noexcept
A defaultable none-type.
Definition at line 177 of file jacobian.h.
Member Function Documentation
AtmType()
constexpr Atm Jacobian::Target::AtmType () const inline constexpr
Return the atm type.
Definition at line 207 of file jacobian.h.
References msubtype.
isFrequency()
constexpr bool Jacobian::Target::isFrequency () const inline constexpr noexcept
Special frequency case.
Definition at line 277 of file jacobian.h.
References Jacobian::FrequencyShift, Jacobian::FrequencyStretch, msubtype, and mtype.
isMagnetic()
constexpr bool Jacobian::Target::isMagnetic () const inline constexpr noexcept
Special magnetic field case.
Definition at line 269 of file jacobian.h.
References Jacobian::MagneticMagnitude, Jacobian::MagneticU, Jacobian::MagneticV, Jacobian::MagneticW, msubtype, and mtype.
isPointing()
constexpr bool Jacobian::Target::isPointing () const inline constexpr noexcept
Special pointing case.
Definition at line 283 of file jacobian.h.
References msubtype, mtype, and Jacobian::PointingZenithInterp.
isSpeciesVMR()
constexpr bool Jacobian::Target::isSpeciesVMR () const inline constexpr noexcept
Special species case.
Definition at line 256 of file jacobian.h.
isWind()
constexpr bool Jacobian::Target::isWind () const inline constexpr noexcept
Special wind case.
Definition at line 261 of file jacobian.h.
References msubtype, mtype, Jacobian::WindMagnitude, Jacobian::WindU, Jacobian::WindV, and Jacobian::WindW.
LineType()
constexpr Line Jacobian::Target::LineType () const inline constexpr
Return the line type.
Definition at line 204 of file jacobian.h.
References msubtype.
Referenced by RetrievalQuantity::LineType().
needQuantumIdentity()
constexpr bool Jacobian::Target::needQuantumIdentity () const inline constexpr noexcept
Does this type need the QuantumIdentifier?
Definition at line 289 of file jacobian.h.
References mtype.
Referenced by xml_read_from_stream(), and xml_write_to_stream().
operator==() [1/6]
constexpr bool Jacobian::Target::operator== (Atm other) const inline constexpr noexcept
Checks if the type of jacobian is the input atmospheric parameter.
Definition at line 210 of file jacobian.h.
References msubtype, and mtype.
operator==() [2/6]
bool Jacobian::Target::operator== (const Target & other) const inline noexcept
Equality.
Definition at line 190 of file jacobian.h.
References mqid, msubtype, and mtype.
operator==() [3/6]
constexpr bool Jacobian::Target::operator== (Line other) const inline constexpr noexcept
Checks if the type of jacobian is the input line parameter.
Definition at line 213 of file jacobian.h.
References msubtype, and mtype.
operator==() [4/6]
constexpr bool Jacobian::Target::operator== (Sensor other) const inline constexpr noexcept
Checks if the type of jacobian is the input sensor parameter.
Definition at line 216 of file jacobian.h.
References msubtype, and mtype.
operator==() [5/6]
constexpr bool Jacobian::Target::operator== (Special other) const inline constexpr noexcept
Checks if the type of jacobian is the input sensor parameter.
Definition at line 219 of file jacobian.h.
References msubtype, and mtype.
operator==() [6/6]
constexpr bool Jacobian::Target::operator== (Type other) const inline constexpr noexcept
Checks if the type is correct.
Definition at line 222 of file jacobian.h.
References mtype.
Perturbation() [1/3]
Numeric Jacobian::Target::Perturbation () const inline noexcept
Definition at line 182 of file jacobian.h.
References mperturbation.
Perturbation() [2/3]
Numeric& Jacobian::Target::Perturbation () inline noexcept
Definition at line 181 of file jacobian.h.
References mperturbation.
Perturbation() [3/3]
void Jacobian::Target::Perturbation (Numeric x) inline noexcept
Perturbation.
Definition at line 180 of file jacobian.h.
References mperturbation, and x.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddMagField(), jacobianAddNLTE(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianAddWind(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), RetrievalQuantity::RetrievalQuantity(), xml_read_from_stream(), and xml_write_to_stream().
Position() [1/3]
constexpr Index& Jacobian::Target::Position () inline constexpr
Position for cases that requires it.
Definition at line 297 of file jacobian.h.
References position.
Position() [2/3]
constexpr Index Jacobian::Target::Position () const inline constexpr
Position for cases that requires it.
Definition at line 294 of file jacobian.h.
References position.
Position() [3/3]
constexpr void Jacobian::Target::Position (Index pos) inline constexpr
Position for cases that requires it.
Definition at line 300 of file jacobian.h.
References position.
QuantumIdentity() [1/3]
const QuantumIdentifier& Jacobian::Target::QuantumIdentity () const inline noexcept
Definition at line 187 of file jacobian.h.
References mqid.
QuantumIdentity() [2/3]
QuantumIdentifier& Jacobian::Target::QuantumIdentity () inline noexcept
Definition at line 186 of file jacobian.h.
References mqid.
QuantumIdentity() [3/3]
void Jacobian::Target::QuantumIdentity (const QuantumIdentifier & x) inline noexcept
ID.
Definition at line 185 of file jacobian.h.
References mqid, and x.
Referenced by RetrievalQuantity::QuantumIdentity(), xml_read_from_stream(), and xml_write_to_stream().
TargetSubType() [1/2]
constexpr std::string_view Jacobian::Target::TargetSubType () const inline constexpr noexcept
Return sub type as string.
Definition at line 234 of file jacobian.h.
References msubtype, mtype, and Jacobian::toString().
Referenced by xml_read_from_stream(), and xml_write_to_stream().
TargetSubType() [2/2]
constexpr void Jacobian::Target::TargetSubType (const std::string_view & s) inline constexpr noexcept
Sets target based on a string.
Definition at line 237 of file jacobian.h.
References msubtype, mtype, and Jacobian::toTypeOfTarget().
TargetSubTypeOK()
constexpr bool Jacobian::Target::TargetSubTypeOK () const inline constexpr noexcept
Are we good?
Definition at line 240 of file jacobian.h.
References good_enum(), msubtype, and mtype.
Referenced by xml_read_from_stream().
TargetType() [1/2]
constexpr std::string_view Jacobian::Target::TargetType () const inline constexpr noexcept
Return type as string.
Definition at line 225 of file jacobian.h.
References mtype, and Jacobian::toString().
Referenced by xml_read_from_stream(), and xml_write_to_stream().
TargetType() [2/2]
constexpr void Jacobian::Target::TargetType (const std::string_view & s) inline constexpr noexcept
Sets target based on a string.
Definition at line 228 of file jacobian.h.
References mtype.
TargetTypeOK()
constexpr bool Jacobian::Target::TargetTypeOK () const inline constexpr noexcept
Are we good?
Definition at line 231 of file jacobian.h.
References good_enum(), and mtype.
Member Data Documentation
mperturbation
Numeric Jacobian::Target::mperturbation private
Perturbations for methods where theoretical computations are impossible or plain slow.
Definition at line 155 of file jacobian.h.
Referenced by Perturbation().
mqid
QuantumIdentifier Jacobian::Target::mqid private
ID for the Line types of partial derivatives.
Definition at line 158 of file jacobian.h.
Referenced by operator==(), and QuantumIdentity().
msubtype
TypeOfTarget Jacobian::Target::msubtype private
Type of quantity, set manually.
Definition at line 152 of file jacobian.h.
Referenced by AtmType(), isFrequency(), isMagnetic(), isPointing(), isWind(), LineType(), operator==(), TargetSubType(), and TargetSubTypeOK().
mtype
Type Jacobian::Target::mtype private
! Type of quantity, never set manually
Definition at line 149 of file jacobian.h.
Referenced by isFrequency(), isMagnetic(), isPointing(), isWind(), needQuantumIdentity(), operator==(), TargetSubType(), TargetSubTypeOK(), TargetType(), and TargetTypeOK().
position
Index Jacobian::Target::position private
A position for a Target that requires it.
Definition at line 161 of file jacobian.h.
Referenced by Position().
The documentation for this class was generated from the following file:
jacobian.h