ARTS: ConstComplexVectorView Class Reference
ConstComplexVectorView Class Reference
A constant view of a ComplexVector.
#include <complex.h>
Public Types
typedef ConstComplexIterator1D const_iterator
Public Member Functions
constexpr ConstComplexVectorView (const ConstComplexVectorView &)=default
constexpr ConstComplexVectorView (ConstComplexVectorView &&)=default
ConstComplexVectorView & operator= (const ConstComplexVectorView &)=default
ConstComplexVectorView & operator= (ConstComplexVectorView &&)=default
bool empty () const
Index nelem () const
Complex sum () const
Returns true if variable size is zero.
const Complex & operator[] (Index n) const
Plain const index operator.
const Complex & get (Index n) const
Get element implementation without assertions.
const Numeric & get_real (Index n) const
Get element implementation without assertions.
const Numeric & get_imag (Index n) const
Get element implementation without assertions.
ConstVectorView real () const
Get a view of the real part of the vector.
ConstVectorView imag () const
Get a view of the imaginary part of the vector.
ConstComplexVectorView operator[] (const Range &r) const
Const index operator for subrange.
ConstComplexIterator1D begin () const
Return const iterator to first element.
ConstComplexIterator1D end () const
Return const iterator behind last element.
operator ConstComplexMatrixView () const
Conversion to const 1 column matrix.
virtual ~ConstComplexVectorView ()=default
Destructor.
ConstComplexVectorView (const Complex &a)
A special constructor, which allows to make a ConstComplexVectorView from a scalar.
Protected Member Functions
ConstComplexVectorView ()=default
ConstComplexVectorView (Complex *data, const Range &range)
Explicit constructor.
ConstComplexVectorView (Complex *data, const Range &p, const Range &n)
Recursive constructor.
Protected Attributes
Range mrange {0, 0}
The range of mdata that is actually used.
Complex * mdata {nullptr}
Pointer to the plain C array that holds the data.
Friends
class ComplexVectorView
class ConstComplexIterator2D
class ConstComplexMatrixView
Complex operator* (const ConstComplexVectorView &a, const ConstComplexVectorView &b)
Scalar product.
void mult (ComplexVectorView, const ConstComplexMatrixView &, const ConstComplexVectorView &)
Matrix-Vector Multiplication.
ComplexConstMatrixViewMap MapToEigen (const ConstComplexVectorView &)
ComplexConstMatrixViewMap MapToEigenCol (const ConstComplexVectorView &)
ComplexMatrixViewMap MapToEigen (ComplexVectorView &)
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView &)
Detailed Description
A constant view of a ComplexVector.
Together with the derived class ComplexVectorView this contains the main implementation of a ComplexVector. The class ComplexVector is just a special case of a ComplexVectorView which also allocates storage.
Definition at line 268 of file complex.h.
Member Typedef Documentation
const_iterator
typedef ConstComplexIterator1D ConstComplexVectorView::const_iterator
Definition at line 276 of file complex.h.
Constructor & Destructor Documentation
ConstComplexVectorView() [1/6]
constexpr ConstComplexVectorView::ConstComplexVectorView (const ConstComplexVectorView &) constexpr default
ConstComplexVectorView() [2/6]
constexpr ConstComplexVectorView::ConstComplexVectorView (ConstComplexVectorView &&) constexpr default
~ConstComplexVectorView()
virtual ConstComplexVectorView::~ConstComplexVectorView () virtual default
Destructor.
ConstComplexVectorView() [3/6]
ConstComplexVectorView::ConstComplexVectorView (const Complex & a)
A special constructor, which allows to make a ConstComplexVectorView from a scalar.
This one is a bit tricky: We have to cast away the arguments const qualifier, because mdata is not const. This should be safe, since there are no non-const methods for ConstComplexVectorView.
Definition at line 101 of file complex.cc.
ConstComplexVectorView() [4/6]
ConstComplexVectorView::ConstComplexVectorView () protected default
Referenced by operator[]().
ConstComplexVectorView() [5/6]
ConstComplexVectorView::ConstComplexVectorView (Complex * data, const Range & range) protected
Explicit constructor.
This one is used by Vector to initialize its own VectorView part.
Definition at line 108 of file complex.cc.
ConstComplexVectorView() [6/6]
ConstComplexVectorView::ConstComplexVectorView (Complex * data, const Range & p, const Range & n) protected
Recursive constructor.
This is used to construct sub ranges from sub ranges. That means that the new range has to be interpreted relative to the original range. The new range may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
p Previous range.
n New Range.
Definition at line 124 of file complex.cc.
Member Function Documentation
begin()
ConstComplexIterator1D ConstComplexVectorView::begin () const
Return const iterator to first element.
Definition at line 78 of file complex.cc.
References mdata, mrange, Range::mstart, and Range::mstride.
Referenced by copy(), ComplexMatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexMatrixView::operator/=(), operator<<(), and sum().
empty()
bool ConstComplexVectorView::empty () const inline
Definition at line 279 of file complex.h.
References nelem().
end()
ConstComplexIterator1D ConstComplexVectorView::end () const
Return const iterator behind last element.
Definition at line 83 of file complex.cc.
References mdata, Range::mextent, mrange, Range::mstart, and Range::mstride.
Referenced by operator<<().
get()
const Complex& ConstComplexVectorView::get (Index n) const inline
Get element implementation without assertions.
Definition at line 292 of file complex.h.
References mdata, mrange, Range::mstart, and Range::mstride.
Referenced by get_imag(), get_real(), and operator[]().
get_imag()
const Numeric& ConstComplexVectorView::get_imag (Index n) const inline
Get element implementation without assertions.
Definition at line 302 of file complex.h.
References get().
get_real()
const Numeric& ConstComplexVectorView::get_real (Index n) const inline
Get element implementation without assertions.
Definition at line 297 of file complex.h.
References get().
imag()
ConstVectorView ConstComplexVectorView::imag () const inline
Get a view of the imaginary part of the vector.
Definition at line 310 of file complex.h.
References mdata, Range::mextent, mrange, Range::mstart, and Range::mstride.
nelem()
Index ConstComplexVectorView::nelem () const inline
Definition at line 280 of file complex.h.
References Range::mextent, and mrange.
Referenced by ComplexVector::ComplexVector(), diagonalize(), empty(), ComplexVectorView::operator*=(), ComplexVectorView::operator+=(), ComplexVectorView::operator-=(), and ComplexVectorView::operator/=().
operator ConstComplexMatrixView()
ConstComplexVectorView::operator ConstComplexMatrixView () const
Conversion to const 1 column matrix.
Definition at line 90 of file complex.cc.
operator=() [1/2]
ConstComplexVectorView& ConstComplexVectorView::operator= (const ConstComplexVectorView &) default
operator=() [2/2]
ConstComplexVectorView& ConstComplexVectorView::operator= (ConstComplexVectorView &&) default
operator[]() [1/2]
ConstComplexVectorView ConstComplexVectorView::operator[] (const Range & r) const
Const index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Vector. This allows correct recursive behavior.
Definition at line 72 of file complex.cc.
References ConstComplexVectorView(), mdata, and mrange.
operator[]() [2/2]
const Complex& ConstComplexVectorView::operator[] (Index n) const inline
Plain const index operator.
Definition at line 285 of file complex.h.
References get(), Range::mextent, and mrange.
real()
ConstVectorView ConstComplexVectorView::real () const inline
Get a view of the real part of the vector.
Definition at line 307 of file complex.h.
References mdata, Range::mextent, mrange, Range::mstart, and Range::mstride.
sum()
Complex ConstComplexVectorView::sum () const
Returns true if variable size is zero.
Returns the number of elements. The names ‘size’ and ‘length’ are already used by STL functions returning size_t. To avoid confusion we choose the name ‘nelem’. This is also more consistent with ‘nrow’ and ‘ncol’ for matrices.
The value range of long, which is used to store the index is on a PC from -2147483648 to 2147483647. This means that a 15GB large array of float can be addressed with this index. So the extra bit that size_t has compared to long is not needed. The sum of all elements of a Vector.
Definition at line 59 of file complex.cc.
References begin().
Friends And Related Function Documentation
ComplexVectorView
friend class ComplexVectorView friend
Definition at line 327 of file complex.h.
ConstComplexIterator2D
friend class ConstComplexIterator2D friend
Definition at line 328 of file complex.h.
ConstComplexMatrixView
friend class ConstComplexMatrixView friend
Definition at line 329 of file complex.h.
MapToEigen [1/2]
ComplexMatrixViewMap MapToEigen (ComplexVectorView &) friend
Definition at line 1698 of file complex.cc.
MapToEigen [2/2]
ComplexConstMatrixViewMap MapToEigen (const ConstComplexVectorView &) friend
Definition at line 1668 of file complex.cc.
MapToEigenCol [1/2]
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView &) friend
Definition at line 1711 of file complex.cc.
MapToEigenCol [2/2]
ComplexConstMatrixViewMap MapToEigenCol (const ConstComplexVectorView &) friend
Definition at line 1681 of file complex.cc.
mult
void mult (ComplexVectorView , const ConstComplexMatrixView & , const ConstComplexVectorView &) friend
Matrix-Vector Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand.
For left-hand multiplication, please use pure matrix-mult.
Parameters
[out] y The length-m ComplexVectorView where the result is stored.
[in] M Reference to the m-times-n Const{Complex,}MatrixView holding the matrix M.
[in] x Reference to the length-n Const{Complex,}VectorView holding the vector x.
Definition at line 1583 of file complex.cc.
operator*
Complex operator* (const ConstComplexVectorView & a, const ConstComplexVectorView & b) friend
Scalar product.
The two vectors may be identical.
Definition at line 1558 of file complex.cc.
Member Data Documentation
mdata
Complex* ConstComplexVectorView::mdata {nullptr} protected
Pointer to the plain C array that holds the data.
Definition at line 353 of file complex.h.
Referenced by ComplexVectorView::begin(), begin(), ComplexVector::ComplexVector(), ComplexVectorView::ComplexVectorView(), ComplexVectorView::end(), end(), ComplexVectorView::get(), get(), ComplexVectorView::get_c_array(), ComplexVectorView::imag(), imag(), ComplexIterator2D::operator!=(), ConstComplexIterator2D::operator!=(), ComplexIterator2D::operator++(), ConstComplexIterator2D::operator++(), ComplexVectorView::operator[](), operator[](), ComplexVectorView::real(), real(), ComplexVector::resize(), and ComplexVector::~ComplexVector().
mrange
Range ConstComplexVectorView::mrange {0, 0} protected
The range of mdata that is actually used.
Definition at line 351 of file complex.h.
Referenced by ComplexVectorView::begin(), begin(), ComplexVectorView::ComplexVectorView(), ComplexVectorView::end(), end(), ComplexVectorView::get(), get(), ComplexVectorView::get_c_array(), ComplexVectorView::imag(), imag(), nelem(), ComplexIterator2D::operator!=(), ConstComplexIterator2D::operator!=(), ComplexVectorView::operator=(), ComplexVectorView::operator[](), operator[](), ComplexVectorView::real(), real(), and ComplexVector::resize().
The documentation for this class was generated from the following files:
complex.h
complex.cc