ARTS: Zeeman::PolarizationVector Class Reference
Zeeman::PolarizationVector Class Reference
Polarization vector for Zeeman Propagation Matrix.
#include <zeemandata.h>
Public Member Functions
PolarizationVector (Numeric a=1, Numeric b=0, Numeric c=0, Numeric d=0, Numeric u=0, Numeric v=0, Numeric w=0) noexcept
Default init of class.
const Eigen::RowVector4d & attenuation () const noexcept
Returns the attenuation vector.
const Eigen::RowVector3d & dispersion () const noexcept
Returns the dispersion vector.
Eigen::RowVector4d & attenuation () noexcept
Returns the attenuation vector.
Eigen::RowVector3d & dispersion () noexcept
Returns the dispersion vector.
Eigen::Matrix4d matrix () const noexcept
Returns the true propagation matrix.
Private Attributes
Eigen::RowVector4d att
Eigen::RowVector3d dis
Detailed Description
Polarization vector for Zeeman Propagation Matrix.
Meant to contain the polarization state in two vectors representing [a,b,c,d] and [u,v,w] of PropagationMatrix class
Definition at line 491 of file zeemandata.h.
Constructor & Destructor Documentation
PolarizationVector()
Zeeman::PolarizationVector::PolarizationVector (Numeric a = 1, Numeric b = 0, Numeric c = 0, Numeric d = 0, Numeric u = 0, Numeric v = 0, Numeric w = 0) inline noexcept
Default init of class.
Definition at line 498 of file zeemandata.h.
Member Function Documentation
attenuation() [1/2]
const Eigen::RowVector4d& Zeeman::PolarizationVector::attenuation () const inline noexcept
Returns the attenuation vector.
Definition at line 508 of file zeemandata.h.
References att.
Referenced by Zeeman::dsum(), and Zeeman::sum().
attenuation() [2/2]
Eigen::RowVector4d& Zeeman::PolarizationVector::attenuation () inline noexcept
Returns the attenuation vector.
Definition at line 514 of file zeemandata.h.
References att.
dispersion() [1/2]
const Eigen::RowVector3d& Zeeman::PolarizationVector::dispersion () const inline noexcept
Returns the dispersion vector.
Definition at line 511 of file zeemandata.h.
References dis.
Referenced by Zeeman::dsum(), and Zeeman::sum().
dispersion() [2/2]
Eigen::RowVector3d& Zeeman::PolarizationVector::dispersion () inline noexcept
Returns the dispersion vector.
Definition at line 517 of file zeemandata.h.
References dis.
matrix()
Eigen::Matrix4d Zeeman::PolarizationVector::matrix () const inline noexcept
Returns the true propagation matrix.
Use only for debug printing if possible
Definition at line 523 of file zeemandata.h.
References att, and dis.
Member Data Documentation
att
Eigen::RowVector4d Zeeman::PolarizationVector::att private
Definition at line 493 of file zeemandata.h.
Referenced by attenuation(), and matrix().
dis
Eigen::RowVector3d Zeeman::PolarizationVector::dis private
Definition at line 494 of file zeemandata.h.
Referenced by dispersion(), and matrix().
The documentation for this class was generated from the following file:
zeemandata.h