ARTS: ARTS::Var::GriddedField2 Class Reference
ARTS::Var::GriddedField2 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField2 () noexcept
GriddedField2 (std::size_t i, void *x) noexcept
GriddedField2 (const Group::GriddedField2 &val) noexcept
~GriddedField2 () noexcept
Group::GriddedField2 & value () noexcept
const Group::GriddedField2 & value () const noexcept
GriddedField2 & operator= (const Group::GriddedField2 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField2 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField2 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3008 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField2() [1/3]
ARTS::Var::GriddedField2::GriddedField2 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3013 of file autoarts.h.
GriddedField2() [2/3]
ARTS::Var::GriddedField2::GriddedField2 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3016 of file autoarts.h.
GriddedField2() [3/3]
ARTS::Var::GriddedField2::GriddedField2 (const Group::GriddedField2 & val) inline noexcept
Construct from Group::GriddedField2. Leaves islast() true and isnull() false
Definition at line 3019 of file autoarts.h.
~GriddedField2()
ARTS::Var::GriddedField2::~GriddedField2 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3022 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField2::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3040 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::InterpGriddedField2ToPosition(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~GriddedField2().
isnull()
bool ARTS::Var::GriddedField2::isnull () const inline noexcept
Return true if there is no data
Definition at line 3037 of file autoarts.h.
References v.
Referenced by ~GriddedField2().
name()
const Group::String& ARTS::Var::GriddedField2::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3043 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField2& ARTS::Var::GriddedField2::operator= (const Group::GriddedField2 & t) inline noexcept
Set value from Group::GriddedField2. Works when isnull() is false
Definition at line 3031 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField2::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3034 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::GriddedFieldGetName(), ARTS::Agenda::Method::GriddedFieldLatLonExpand(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::InterpGriddedField2ToPosition(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::GriddedField2& ARTS::Var::GriddedField2::value () const inline noexcept
Get value const-ref as Group::GriddedField2. Works when isnull() is false
Definition at line 3028 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField2& ARTS::Var::GriddedField2::value () inline noexcept
Get value ref as Group::GriddedField2. Works when isnull() is false
Definition at line 3025 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), ARTS::Method::InterpGriddedField2ToPosition(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField2 & var) friend
Output to stream of internal variable
Definition at line 3046 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField2::p private
Definition at line 3009 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField2* ARTS::Var::GriddedField2::v private
Definition at line 3010 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField2().
The documentation for this class was generated from the following file:
autoarts.h