ARTS: ARTS::Var::ArrayOfMatrix Class Reference
ARTS::Var::ArrayOfMatrix Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfMatrix () noexcept
ArrayOfMatrix (std::size_t i, void *x) noexcept
ArrayOfMatrix (const Group::ArrayOfMatrix &val) noexcept
~ArrayOfMatrix () noexcept
Group::ArrayOfMatrix & value () noexcept
const Group::ArrayOfMatrix & value () const noexcept
ArrayOfMatrix & operator= (const Group::ArrayOfMatrix &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfMatrix * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfMatrix &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 1687 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfMatrix() [1/3]
ARTS::Var::ArrayOfMatrix::ArrayOfMatrix () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 1692 of file autoarts.h.
ArrayOfMatrix() [2/3]
ARTS::Var::ArrayOfMatrix::ArrayOfMatrix (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 1695 of file autoarts.h.
ArrayOfMatrix() [3/3]
ARTS::Var::ArrayOfMatrix::ArrayOfMatrix (const Group::ArrayOfMatrix & val) inline noexcept
Construct from Group::ArrayOfMatrix. Leaves islast() true and isnull() false
Definition at line 1698 of file autoarts.h.
~ArrayOfMatrix()
ARTS::Var::ArrayOfMatrix::~ArrayOfMatrix () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 1701 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfMatrix::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 1719 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Method::ReadNetCDF(), and ~ArrayOfMatrix().
isnull()
bool ARTS::Var::ArrayOfMatrix::isnull () const inline noexcept
Return true if there is no data
Definition at line 1716 of file autoarts.h.
References v.
Referenced by ~ArrayOfMatrix().
name()
const Group::String& ARTS::Var::ArrayOfMatrix::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 1722 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
ArrayOfMatrix& ARTS::Var::ArrayOfMatrix::operator= (const Group::ArrayOfMatrix & t) inline noexcept
Set value from Group::ArrayOfMatrix. Works when isnull() is false
Definition at line 1710 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfMatrix::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 1713 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfMatrix& ARTS::Var::ArrayOfMatrix::value () const inline noexcept
Get value const-ref as Group::ArrayOfMatrix. Works when isnull() is false
Definition at line 1707 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfMatrix& ARTS::Var::ArrayOfMatrix::value () inline noexcept
Get value ref as Group::ArrayOfMatrix. Works when isnull() is false
Definition at line 1704 of file autoarts.h.
References v.
Referenced by ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::ReadNetCDF().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfMatrix & var) friend
Output to stream of internal variable
Definition at line 1725 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfMatrix::p private
Definition at line 1688 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfMatrix* ARTS::Var::ArrayOfMatrix::v private
Definition at line 1689 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfMatrix().
The documentation for this class was generated from the following file:
autoarts.h