ARTS: ARTS::Var::WorkspaceStokesVector Class Reference
ARTS::Var::WorkspaceStokesVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceStokesVector () noexcept
WorkspaceStokesVector (std::size_t i, void *x) noexcept
~WorkspaceStokesVector () noexcept
WorkspaceStokesVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceStokesVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::StokesVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1448 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceStokesVector::type = Group::StokesVector private
Definition at line 1449 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceStokesVector() [1/3]
ARTS::Var::WorkspaceStokesVector::WorkspaceStokesVector () inline noexcept
Definition at line 1453 of file autoarts.h.
WorkspaceStokesVector() [2/3]
ARTS::Var::WorkspaceStokesVector::WorkspaceStokesVector (std::size_t i, void * x) inline noexcept
Definition at line 1454 of file autoarts.h.
~WorkspaceStokesVector()
ARTS::Var::WorkspaceStokesVector::~WorkspaceStokesVector () inline noexcept
Definition at line 1455 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceStokesVector() [3/3]
ARTS::Var::WorkspaceStokesVector::WorkspaceStokesVector (const type & val) inline noexcept
Definition at line 1456 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceStokesVector::islast () const inline noexcept
Definition at line 1462 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceStokesVector().
isnull()
bool ARTS::Var::WorkspaceStokesVector::isnull () const inline noexcept
Definition at line 1461 of file autoarts.h.
References v.
Referenced by ~WorkspaceStokesVector().
name()
const Group::String& ARTS::Var::WorkspaceStokesVector::name () const inline noexcept
Definition at line 1463 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceStokesVector& ARTS::Var::WorkspaceStokesVector::operator= (const type & t) inline noexcept
Definition at line 1459 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceStokesVector::pos () const inline noexcept
Definition at line 1460 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceStokesVector::value () const inline noexcept
Definition at line 1458 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceStokesVector::value () inline noexcept
Definition at line 1457 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceStokesVector::p private
Definition at line 1450 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceStokesVector::v private
Definition at line 1451 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceStokesVector().
The documentation for this class was generated from the following file:
autoarts.h