ARTS: ConstTensor5View Class Reference
ConstTensor5View Class Reference
A constant view of a Tensor5.
#include <matpackV.h>
Public Member Functions
constexpr ConstTensor5View (const ConstTensor5View &)=default
constexpr ConstTensor5View (ConstTensor5View &&)=default
ConstTensor5View & operator= (const ConstTensor5View &)=default
ConstTensor5View & operator= (ConstTensor5View &&)=default
bool empty () const
Check if variable is empty.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor5View operator() (const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor3View operator() (const Range &s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &s, Index b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index s, Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator5D begin () const
Return const iterator to first shelf.
ConstIterator5D end () const
Return const iterator behind last shelf.
virtual ~ConstTensor5View ()=default
Destructor.
ConstTensor5View (const ConstTensor4View &a)
Special constructor to make a Tensor5 view of a Tensor4.
Protected Member Functions
ConstTensor5View ()=default
ConstTensor5View (Numeric *data, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor5View (Numeric *data, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Attributes
Range msr {0, 0, 1}
The shelf range of mdata that is actually used.
Range mbr {0, 0, 1}
The book range of mdata that is actually used.
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Friends
class Tensor5View
class ConstIterator6D
class ConstTensor6View
class ConstTensor7View
Detailed Description
A constant view of a Tensor5.
This, together with the derived class Tensor5View, contains the main implementation of a Tensor5. It defines the concepts of Tensor5View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor5View from a subrange of a Tensor5View.
The five dimensions of the tensor are called: shelf, book, page, row, column.
The class Tensor5 is just a special case of a Tensor5View which also allocates storage.
Definition at line 143 of file matpackV.h.
Constructor & Destructor Documentation
ConstTensor5View() [1/6]
constexpr ConstTensor5View::ConstTensor5View (const ConstTensor5View &) constexpr default
ConstTensor5View() [2/6]
constexpr ConstTensor5View::ConstTensor5View (ConstTensor5View &&) constexpr default
~ConstTensor5View()
virtual ConstTensor5View::~ConstTensor5View () virtual default
Destructor.
ConstTensor5View() [3/6]
ConstTensor5View::ConstTensor5View (const ConstTensor4View & a)
Special constructor to make a Tensor5 view of a Tensor4.
Definition at line 702 of file matpackV.cc.
ConstTensor5View() [4/6]
ConstTensor5View::ConstTensor5View () protected default
Referenced by operator()().
ConstTensor5View() [5/6]
ConstTensor5View::ConstTensor5View (Numeric * data, const Range & sr, const Range & br, const Range & pr, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Tensor5 to initialize its own Tensor5View part. The book range br must have a stride to account for the length of one book. The shelf range sr must have a stride to account for the length of one shelf.
Definition at line 716 of file matpackV.cc.
ConstTensor5View() [6/6]
ConstTensor5View::ConstTensor5View (Numeric * data, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct sub-tensors from sub-tensors. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Definition at line 733 of file matpackV.cc.
Member Function Documentation
begin()
ConstIterator5D ConstTensor5View::begin () const
Return const iterator to first shelf.
Definition at line 688 of file matpackV.cc.
References mbr, mcr, mdata, mpr, mrr, msr, Range::mstart, and Range::mstride.
Referenced by copy(), Tensor5View::operator=(), and Tensor5::Tensor5().
empty()
bool ConstTensor5View::empty () const
Check if variable is empty.
Parameters
[in] x The variable to check.
Returns
True if the size of any dimension of x is 0.
Definition at line 38 of file matpackV.cc.
References nbooks(), ncols(), npages(), nrows(), and nshelves().
Referenced by get_variable_value().
end()
ConstIterator5D ConstTensor5View::end () const
Return const iterator behind last shelf.
Definition at line 694 of file matpackV.cc.
References mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
Referenced by copy(), Tensor5View::operator=(), and Tensor5::Tensor5().
get()
Numeric ConstTensor5View::get (Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 265 of file matpackV.h.
References b, c, mbr, mcr, mdata, mpr, mrr, msr, Range::mstart, and Range::mstride.
Referenced by interp(), and operator()().
nbooks()
Index ConstTensor5View::nbooks () const
Returns the number of books.
Definition at line 47 of file matpackV.cc.
References mbr, and Range::mextent.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), GriddedField5::checksize(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), Extract(), get_variable_value(), Interpolation::interp(), nca_write_to_file(), Tensor5View::operator*=(), Tensor5View::operator+=(), Tensor5View::operator-=(), Tensor5View::operator/=(), Tensor5::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), Tensor5::reduce_rank(), Tensor5::size(), spectral_irradiance_fieldFromSpectralRadianceField(), surface_complex_refr_indexFromGriddedField5(), Tensor5::Tensor5(), Tensor5Scale(), and xml_write_to_stream().
ncols()
Index ConstTensor5View::ncols () const
Returns the number of columns.
Definition at line 56 of file matpackV.cc.
References mcr, and Range::mextent.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), GriddedField5::checksize(), cloud_fieldsCalc(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), Extract(), get_variable_value(), Interpolation::interp(), interpolate_scat_angle(), nca_write_to_file(), Tensor5View::operator*=(), Tensor5View::operator+=(), Tensor5View::operator-=(), Tensor5View::operator/=(), Tensor5::operator=(), opt_prop_1ScatElem(), pha_matTransform(), RadiationFieldSpectralIntegrate(), Reduce(), Tensor5::reduce_rank(), ScatSpeciesExtendTemperature(), ScatSpeciesMerge(), Tensor5::size(), spectral_irradiance_fieldFromSpectralRadianceField(), surface_complex_refr_indexFromGriddedField5(), Tensor5::Tensor5(), Tensor5Scale(), and xml_write_to_stream().
npages()
Index ConstTensor5View::npages () const
Returns the number of pages.
Definition at line 50 of file matpackV.cc.
References Range::mextent, and mpr.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), GriddedField5::checksize(), empty(), Extract(), get_variable_value(), Interpolation::interp(), nca_write_to_file(), Tensor5View::operator*=(), Tensor5View::operator+=(), Tensor5View::operator-=(), Tensor5View::operator/=(), Tensor5::operator=(), pha_matTransform(), RadiationFieldSpectralIntegrate(), Reduce(), Tensor5::reduce_rank(), ScatSpeciesMerge(), Tensor5::size(), spectral_irradiance_fieldFromSpectralRadianceField(), surface_complex_refr_indexFromGriddedField5(), Tensor5::Tensor5(), Tensor5Scale(), and xml_write_to_stream().
nrows()
Index ConstTensor5View::nrows () const
Returns the number of rows.
Definition at line 53 of file matpackV.cc.
References Range::mextent, and mrr.
Referenced by GriddedField5::checksize(), cloud_fieldsCalc(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), Extract(), get_variable_value(), Interpolation::interp(), nca_write_to_file(), Tensor5View::operator*=(), Tensor5View::operator+=(), Tensor5View::operator-=(), Tensor5View::operator/=(), Tensor5::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), Tensor5::reduce_rank(), ScatSpeciesMerge(), Tensor5::size(), spectral_irradiance_fieldFromSpectralRadianceField(), surface_complex_refr_indexFromGriddedField5(), Tensor5::Tensor5(), Tensor5Scale(), and xml_write_to_stream().
nshelves()
Index ConstTensor5View::nshelves () const
Returns the number of shelves.
Definition at line 44 of file matpackV.cc.
References Range::mextent, and msr.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), GriddedField5::checksize(), ConvertAzimuthallyRandomSingleScatteringData(), empty(), Extract(), get_variable_value(), Interpolation::interp(), nca_write_to_file(), Tensor5View::operator*=(), Tensor5View::operator+=(), Tensor5View::operator-=(), Tensor5View::operator/=(), Tensor5::operator=(), RadiationFieldSpectralIntegrate(), Reduce(), Tensor5::reduce_rank(), ScatSpeciesMerge(), Tensor5::size(), spectral_irradiance_fieldFromSpectralRadianceField(), surface_complex_refr_indexFromGriddedField5(), Tensor5::Tensor5(), Tensor5Scale(), and xml_write_to_stream().
operator()() [1/32]
ConstTensor5View ConstTensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Const index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor5. This allows correct recursive behavior.
Definition at line 61 of file matpackV.cc.
References b, c, ConstTensor5View(), mbr, mcr, mdata, mpr, mrr, and msr.
operator()() [2/32]
ConstTensor4View ConstTensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.)
Definition at line 71 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [3/32]
ConstTensor4View ConstTensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.)
Definition at line 86 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [4/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 146 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [5/32]
ConstTensor4View ConstTensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.)
Definition at line 101 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [6/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 166 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [7/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, const Range & b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 186 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [8/32]
ConstMatrixView ConstTensor5View::operator() (const Range & s, const Range & b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 346 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [9/32]
ConstTensor4View ConstTensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.)
Definition at line 116 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [10/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 226 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [11/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, Index b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 206 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [12/32]
ConstMatrixView ConstTensor5View::operator() (const Range & s, Index b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 366 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [13/32]
ConstTensor3View ConstTensor5View::operator() (const Range & s, Index b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 246 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [14/32]
ConstMatrixView ConstTensor5View::operator() (const Range & s, Index b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 386 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [15/32]
ConstMatrixView ConstTensor5View::operator() (const Range & s, Index b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 406 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [16/32]
ConstVectorView ConstTensor5View::operator() (const Range & s, Index b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 546 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [17/32]
ConstTensor4View ConstTensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.)
Definition at line 131 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [18/32]
ConstTensor3View ConstTensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 306 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [19/32]
ConstTensor3View ConstTensor5View::operator() (Index s, const Range & b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 286 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [20/32]
ConstMatrixView ConstTensor5View::operator() (Index s, const Range & b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 466 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [21/32]
ConstTensor3View ConstTensor5View::operator() (Index s, const Range & b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 266 of file matpackV.cc.
References ARTS_ASSERT, Range::mextent, and msr.
operator()() [22/32]
ConstMatrixView ConstTensor5View::operator() (Index s, const Range & b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 446 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [23/32]
ConstMatrixView ConstTensor5View::operator() (Index s, const Range & b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 426 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [24/32]
ConstVectorView ConstTensor5View::operator() (Index s, const Range & b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 567 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [25/32]
ConstTensor3View ConstTensor5View::operator() (Index s, Index b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.)
Definition at line 326 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [26/32]
ConstMatrixView ConstTensor5View::operator() (Index s, Index b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 486 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [27/32]
ConstMatrixView ConstTensor5View::operator() (Index s, Index b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 506 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [28/32]
ConstVectorView ConstTensor5View::operator() (Index s, Index b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 588 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [29/32]
ConstMatrixView ConstTensor5View::operator() (Index s, Index b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.)
Definition at line 526 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [30/32]
ConstVectorView ConstTensor5View::operator() (Index s, Index b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 609 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [31/32]
ConstVectorView ConstTensor5View::operator() (Index s, Index b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 630 of file matpackV.cc.
References ARTS_ASSERT, b, c, mbr, mcr, mdata, Range::mextent, mpr, mrr, msr, Range::mstart, and Range::mstride.
operator()() [32/32]
Numeric ConstTensor5View::operator() (Index s, Index b, Index p, Index r, Index c) const inline
Plain const index operator.
Definition at line 245 of file matpackV.h.
References ARTS_ASSERT, b, c, get(), mbr, mcr, Range::mextent, mpr, mrr, and msr.
operator=() [1/2]
ConstTensor5View& ConstTensor5View::operator= (const ConstTensor5View &) default
operator=() [2/2]
ConstTensor5View& ConstTensor5View::operator= (ConstTensor5View &&) default
Friends And Related Function Documentation
ConstIterator6D
friend class ConstIterator6D friend
Definition at line 280 of file matpackV.h.
ConstTensor6View
friend class ConstTensor6View friend
Definition at line 281 of file matpackV.h.
ConstTensor7View
friend class ConstTensor7View friend
Definition at line 282 of file matpackV.h.
Tensor5View
friend class Tensor5View friend
Definition at line 279 of file matpackV.h.
Member Data Documentation
mbr
Range ConstTensor5View::mbr {0, 0, 1} protected
The book range of mdata that is actually used.
Definition at line 313 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), nbooks(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Tensor5View::operator=(), and Tensor5::resize().
mcr
Range ConstTensor5View::mcr {0, 0, 1} protected
The column range of mdata that is actually used.
Definition at line 319 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), ncols(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Tensor5View::operator=(), and Tensor5::resize().
mdata
Numeric* ConstTensor5View::mdata {nullptr} protected
Pointer to the plain C array that holds the data.
Definition at line 321 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Iterator6D::operator++(), ConstIterator6D::operator++(), Tensor5::operator=(), Tensor5::reduce_rank(), Tensor5::resize(), Tensor5::Tensor5(), and Tensor5::~Tensor5().
mpr
Range ConstTensor5View::mpr {0, 0, 1} protected
The page range of mdata that is actually used.
Definition at line 315 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), npages(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Tensor5View::operator=(), and Tensor5::resize().
mrr
Range ConstTensor5View::mrr {0, 0, 1} protected
The row range of mdata that is actually used.
Definition at line 317 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), nrows(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Tensor5View::operator=(), and Tensor5::resize().
msr
Range ConstTensor5View::msr {0, 0, 1} protected
The shelf range of mdata that is actually used.
Definition at line 311 of file matpackV.h.
Referenced by Tensor5View::begin(), begin(), Tensor5View::end(), end(), Tensor5View::get(), get(), Tensor5View::get_c_array(), nshelves(), ConstIterator6D::operator!=(), Iterator6D::operator!=(), Tensor5View::operator()(), operator()(), Tensor5View::operator=(), and Tensor5::resize().
The documentation for this class was generated from the following files:
matpackV.h
matpackV.cc