ARTS: Tensor3View Class Reference
Tensor3View Class Reference
The Tensor3View class.
#include <matpackIII.h>
Public Member Functions
constexpr Tensor3View (const Tensor3View &)=default
Tensor3View operator() (const Range &p, const Range &r, const Range &c)
Index operator for subrange.
MatrixView operator() (const Range &p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index p, const Range &r, const Range &c)
Index operator returning an object of type MatrixView.
VectorView operator() (Index p, Index r, const Range &c)
Index operator returning an object of type VectorView.
VectorView operator() (Index p, const Range &r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (const Range &p, Index r, Index c)
Index operator returning an object of type VectorView.
Numeric & operator() (Index p, Index r, Index c)
Plain non-const index operator.
Numeric & get (Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const ARTS_NOEXCEPT
Conversion to plain C-array.
Numeric * get_c_array () ARTS_NOEXCEPT
Conversion to plain C-array.
Iterator3D begin ()
Return iterator to first page.
Iterator3D end ()
Return iterator behind last page.
Tensor3View & operator= (const ConstTensor3View &v)
Assignment operator.
Tensor3View & operator= (const Tensor3View &v)
Assignment from Tensor3View to Tensor3View.
Tensor3View & operator= (const Tensor3 &v)
Assignment from a Tensor3.
Tensor3View & operator= (Numeric x)
Assigning a scalar to a Tensor3View will set all elements to this value.
Tensor3View & operator*= (Numeric x)
Multiplication by scalar.
Tensor3View & operator/= (Numeric x)
Division by scalar.
Tensor3View & operator+= (Numeric x)
Addition of scalar.
Tensor3View & operator-= (Numeric x)
Subtraction of scalar.
Tensor3View & operator*= (const ConstTensor3View &x)
Element-vise multiplication by another Tensor3.
Tensor3View & operator/= (const ConstTensor3View &x)
Element-vise division by another Tensor3.
Tensor3View & operator+= (const ConstTensor3View &x)
Element-vise addition of another Tensor3.
Tensor3View & operator-= (const ConstTensor3View &x)
Element-vise subtraction of another Tensor3.
virtual ~Tensor3View ()=default
Destructor.
Tensor3View (const MatrixView &a)
Special constructor to make a Tensor3 view of a matrix.
ConstIterator3D begin () const
Return const iterator to first page.
ConstIterator3D end () const
Return const iterator behind last page.
Numeric get (Index p, Index r, Index c) const
Get element implementation without assertions.
Public Member Functions inherited from ConstTensor3View
constexpr ConstTensor3View (const ConstTensor3View &)=default
constexpr ConstTensor3View (ConstTensor3View &&)=default
ConstTensor3View & operator= (const ConstTensor3View &)=default
ConstTensor3View & operator= (ConstTensor3View &&)=default
bool empty () const
Check if variable is empty.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor3View operator() (const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstMatrixView operator() (const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator3D begin () const
Return const iterator to first page.
ConstIterator3D end () const
Return const iterator behind last page.
virtual ~ConstTensor3View ()=default
Destructor.
ConstTensor3View (const ConstMatrixView &a)
Special constructor to make a Tensor3 view of a matrix.
Protected Member Functions
Tensor3View ()=default
Tensor3View (Numeric *data, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor3View (Numeric *data, const Range &pp, const Range &pr, const Range &pc, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor3View
ConstTensor3View ()=default
ConstTensor3View (Numeric *data, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor3View (Numeric *data, const Range &pp, const Range &pr, const Range &pc, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Friends
class Iterator4D
class Tensor4View
class Tensor5View
class Tensor6View
class Tensor7View
Additional Inherited Members
Protected Attributes inherited from ConstTensor3View
Range mpr {0, 0, 1}
The page range of mdata that is actually used.
Range mrr {0, 0, 1}
The row range of mdata that is actually used.
Range mcr {0, 0, 1}
The column range of mdata that is actually used.
Numeric * mdata {nullptr}
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor3View class.
This contains the main implementation of a Tensor3. It defines the concepts of Tensor3View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor3View from a subrange of a Tensor3View.
The class Tensor3 is just a special case of a Tensor3View which also allocates storage.
Definition at line 239 of file matpackIII.h.
Constructor & Destructor Documentation
Tensor3View() [1/5]
constexpr Tensor3View::Tensor3View (const Tensor3View &) constexpr default
~Tensor3View()
virtual Tensor3View::~Tensor3View () virtual default
Destructor.
Tensor3View() [2/5]
Tensor3View::Tensor3View (const MatrixView & a)
Special constructor to make a Tensor3 view of a matrix.
Definition at line 484 of file matpackIII.cc.
Tensor3View() [3/5]
Tensor3View::Tensor3View () protected default
Referenced by operator()().
Tensor3View() [4/5]
Tensor3View::Tensor3View (Numeric * data, const Range & pr, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Tensor3 to initialize its own Tensor3View part. The row range rr must have a stride to account for the length of one row.
Definition at line 493 of file matpackIII.cc.
Tensor3View() [5/5]
Tensor3View::Tensor3View (Numeric * data, const Range & pp, const Range & pr, const Range & pc, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pp Previous range.
pr Previous range.
pc Previous range.
np New Range.
nr New Range.
nc New Range.
Definition at line 517 of file matpackIII.cc.
Member Function Documentation
begin() [1/2]
Iterator3D Tensor3View::begin ()
Return iterator to first page.
Definition at line 326 of file matpackIII.cc.
References ConstTensor3View::mcr, ConstTensor3View::mdata, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and Tensor3::Tensor3().
begin() [2/2]
ConstIterator3D ConstTensor3View::begin
Return const iterator to first page.
Definition at line 186 of file matpackIII.cc.
end() [1/2]
Iterator3D Tensor3View::end ()
Return iterator behind last page.
Definition at line 331 of file matpackIII.cc.
References ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
end() [2/2]
ConstIterator3D ConstTensor3View::end
Return const iterator behind last page.
Definition at line 187 of file matpackIII.cc.
get() [1/2]
Numeric& Tensor3View::get (Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 275 of file matpackIII.h.
References c, ConstTensor3View::mcr, ConstTensor3View::mdata, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
Referenced by interpweights().
get() [2/2]
Numeric ConstTensor3View::get inline
Get element implementation without assertions.
Definition at line 180 of file matpackIII.h.
Referenced by operator()().
get_c_array() [1/2]
Numeric * Tensor3View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor3View is not pointing to the beginning of a Tensor3 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 303 of file matpackIII.cc.
References ARTS_ASSERT, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Numeric * Tensor3View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor3View is not pointing to the beginning of a Tensor3 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 317 of file matpackIII.cc.
References ARTS_ASSERT, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
Referenced by get_variable_value(), nca_read_from_file(), nca_write_to_file(), Reduce(), InteractiveWorkspace::set_tensor3_variable(), and test38().
operator()() [1/8]
Tensor3View Tensor3View::operator() (const Range & p, const Range & r, const Range & c)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor3. This allows correct recursive behavior.
Definition at line 216 of file matpackIII.cc.
References c, ConstTensor3View::mcr, ConstTensor3View::mdata, ConstTensor3View::mpr, ConstTensor3View::mrr, and Tensor3View().
operator()() [2/8]
MatrixView Tensor3View::operator() (const Range & p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by one.)
Definition at line 224 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [3/8]
MatrixView Tensor3View::operator() (const Range & p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by one.)
Definition at line 234 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [4/8]
VectorView Tensor3View::operator() (const Range & p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by two.)
Definition at line 284 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [5/8]
MatrixView Tensor3View::operator() (Index p, const Range & r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by one.)
Definition at line 244 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [6/8]
VectorView Tensor3View::operator() (Index p, const Range & r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by two.)
Definition at line 269 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [7/8]
VectorView Tensor3View::operator() (Index p, Index r, const Range & c)
Index operator returning an object of type VectorView.
(Reducing the dimension by two.)
Definition at line 254 of file matpackIII.cc.
References ARTS_ASSERT, c, ConstTensor3View::mcr, ConstTensor3View::mdata, Range::mextent, ConstTensor3View::mpr, ConstTensor3View::mrr, Range::mstart, and Range::mstride.
operator()() [8/8]
Numeric& Tensor3View::operator() (Index p, Index r, Index c) inline
Plain non-const index operator.
Definition at line 262 of file matpackIII.h.
References ARTS_ASSERT, c, get(), ConstTensor3View::mcr, Range::mextent, ConstTensor3View::mpr, and ConstTensor3View::mrr.
operator*=() [1/2]
Tensor3View & Tensor3View::operator*= (const ConstTensor3View & x)
Element-vise multiplication by another Tensor3.
Definition at line 428 of file matpackIII.cc.
References ARTS_ASSERT, begin(), end(), ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and ARTS::Var::x().
operator*=() [2/2]
Tensor3View & Tensor3View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 392 of file matpackIII.cc.
References begin(), end(), and ARTS::Var::x().
operator+=() [1/2]
Tensor3View & Tensor3View::operator+= (const ConstTensor3View & x)
Element-vise addition of another Tensor3.
Definition at line 456 of file matpackIII.cc.
References ARTS_ASSERT, begin(), end(), ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and ARTS::Var::x().
operator+=() [2/2]
Tensor3View & Tensor3View::operator+= (Numeric x)
Addition of scalar.
Definition at line 410 of file matpackIII.cc.
References begin(), end(), and ARTS::Var::x().
operator-=() [1/2]
Tensor3View & Tensor3View::operator-= (const ConstTensor3View & x)
Element-vise subtraction of another Tensor3.
Definition at line 470 of file matpackIII.cc.
References ARTS_ASSERT, begin(), end(), ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and ARTS::Var::x().
operator-=() [2/2]
Tensor3View & Tensor3View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 419 of file matpackIII.cc.
References begin(), end(), and ARTS::Var::x().
operator/=() [1/2]
Tensor3View & Tensor3View::operator/= (const ConstTensor3View & x)
Element-vise division by another Tensor3.
Definition at line 442 of file matpackIII.cc.
References ARTS_ASSERT, begin(), end(), ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and ARTS::Var::x().
operator/=() [2/2]
Tensor3View & Tensor3View::operator/= (Numeric x)
Division by scalar.
Definition at line 401 of file matpackIII.cc.
References begin(), end(), and ARTS::Var::x().
operator=() [1/4]
Tensor3View & Tensor3View::operator= (const ConstTensor3View & m)
Assignment operator.
This copies the data from another Tensor3View to this Tensor3View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor3View by setting its range.
Definition at line 341 of file matpackIII.cc.
References ARTS_ASSERT, begin(), ConstTensor3View::begin(), copy(), ConstTensor3View::end(), ConstTensor3View::mcr, Range::mextent, ConstTensor3View::mpr, and ConstTensor3View::mrr.
operator=() [2/4]
Tensor3View & Tensor3View::operator= (const Tensor3 & m)
Assignment from a Tensor3.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 369 of file matpackIII.cc.
References ARTS_ASSERT, begin(), copy(), end(), ConstTensor3View::mcr, Range::mextent, ConstTensor3View::mpr, and ConstTensor3View::mrr.
operator=() [3/4]
Tensor3View & Tensor3View::operator= (const Tensor3View & m)
Assignment from Tensor3View to Tensor3View.
This is a tricky one. The problem is that since Tensor3View is derived from ConstTensor3View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 356 of file matpackIII.cc.
References ARTS_ASSERT, begin(), copy(), end(), ConstTensor3View::mcr, Range::mextent, ConstTensor3View::mpr, and ConstTensor3View::mrr.
operator=() [4/4]
Tensor3View & Tensor3View::operator= (Numeric x)
Assigning a scalar to a Tensor3View will set all elements to this value.
Definition at line 381 of file matpackIII.cc.
References begin(), copy(), end(), and ARTS::Var::x().
Friends And Related Function Documentation
Iterator4D
friend class Iterator4D friend
Definition at line 309 of file matpackIII.h.
Tensor4View
friend class Tensor4View friend
Definition at line 310 of file matpackIII.h.
Tensor5View
friend class Tensor5View friend
Definition at line 311 of file matpackIII.h.
Tensor6View
friend class Tensor6View friend
Definition at line 312 of file matpackIII.h.
Tensor7View
friend class Tensor7View friend
Definition at line 313 of file matpackIII.h.
The documentation for this class was generated from the following files:
matpackIII.h
matpackIII.cc