ARTS: ARTS::Var::ArrayOfTensor3 Class Reference
ARTS::Var::ArrayOfTensor3 Class Reference
#include <autoarts.h>
Public Member Functions
ArrayOfTensor3 () noexcept
ArrayOfTensor3 (std::size_t i, void *x) noexcept
ArrayOfTensor3 (const Group::ArrayOfTensor3 &val) noexcept
~ArrayOfTensor3 () noexcept
Group::ArrayOfTensor3 & value () noexcept
const Group::ArrayOfTensor3 & value () const noexcept
ArrayOfTensor3 & operator= (const Group::ArrayOfTensor3 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::ArrayOfTensor3 * v
Friends
std::ostream & operator<< (std::ostream &os, const ArrayOfTensor3 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2249 of file autoarts.h.
Constructor & Destructor Documentation
ArrayOfTensor3() [1/3]
ARTS::Var::ArrayOfTensor3::ArrayOfTensor3 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2254 of file autoarts.h.
ArrayOfTensor3() [2/3]
ARTS::Var::ArrayOfTensor3::ArrayOfTensor3 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2257 of file autoarts.h.
ArrayOfTensor3() [3/3]
ARTS::Var::ArrayOfTensor3::ArrayOfTensor3 (const Group::ArrayOfTensor3 & val) inline noexcept
Construct from Group::ArrayOfTensor3. Leaves islast() true and isnull() false
Definition at line 2260 of file autoarts.h.
~ArrayOfTensor3()
ARTS::Var::ArrayOfTensor3::~ArrayOfTensor3 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2263 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::ArrayOfTensor3::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2281 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), and ~ArrayOfTensor3().
isnull()
bool ARTS::Var::ArrayOfTensor3::isnull () const inline noexcept
Return true if there is no data
Definition at line 2278 of file autoarts.h.
References v.
Referenced by ~ArrayOfTensor3().
name()
const Group::String& ARTS::Var::ArrayOfTensor3::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2284 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
ArrayOfTensor3& ARTS::Var::ArrayOfTensor3::operator= (const Group::ArrayOfTensor3 & t) inline noexcept
Set value from Group::ArrayOfTensor3. Works when isnull() is false
Definition at line 2272 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::ArrayOfTensor3::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2275 of file autoarts.h.
References p.
value() [1/2]
const Group::ArrayOfTensor3& ARTS::Var::ArrayOfTensor3::value () const inline noexcept
Get value const-ref as Group::ArrayOfTensor3. Works when isnull() is false
Definition at line 2269 of file autoarts.h.
References v.
value() [2/2]
Group::ArrayOfTensor3& ARTS::Var::ArrayOfTensor3::value () inline noexcept
Get value ref as Group::ArrayOfTensor3. Works when isnull() is false
Definition at line 2266 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const ArrayOfTensor3 & var) friend
Output to stream of internal variable
Definition at line 2287 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::ArrayOfTensor3::p private
Definition at line 2250 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::ArrayOfTensor3* ARTS::Var::ArrayOfTensor3::v private
Definition at line 2251 of file autoarts.h.
Referenced by isnull(), value(), and ~ArrayOfTensor3().
The documentation for this class was generated from the following file:
autoarts.h