ARTS: ARTS::Var::GriddedField4 Class Reference
ARTS::Var::GriddedField4 Class Reference
#include <autoarts.h>
Public Member Functions
GriddedField4 () noexcept
GriddedField4 (std::size_t i, void *x) noexcept
GriddedField4 (const Group::GriddedField4 &val) noexcept
~GriddedField4 () noexcept
Group::GriddedField4 & value () noexcept
const Group::GriddedField4 & value () const noexcept
GriddedField4 & operator= (const Group::GriddedField4 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::GriddedField4 * v
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField4 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3048 of file autoarts.h.
Constructor & Destructor Documentation
GriddedField4() [1/3]
ARTS::Var::GriddedField4::GriddedField4 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3053 of file autoarts.h.
GriddedField4() [2/3]
ARTS::Var::GriddedField4::GriddedField4 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3056 of file autoarts.h.
GriddedField4() [3/3]
ARTS::Var::GriddedField4::GriddedField4 (const Group::GriddedField4 & val) inline noexcept
Construct from Group::GriddedField4. Leaves islast() true and isnull() false
Definition at line 3059 of file autoarts.h.
~GriddedField4()
ARTS::Var::GriddedField4::~GriddedField4 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3062 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::GriddedField4::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3080 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::GriddedFieldLatLonExpand(), and ~GriddedField4().
isnull()
bool ARTS::Var::GriddedField4::isnull () const inline noexcept
Return true if there is no data
Definition at line 3077 of file autoarts.h.
References v.
Referenced by ~GriddedField4().
name()
const Group::String& ARTS::Var::GriddedField4::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3083 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
GriddedField4& ARTS::Var::GriddedField4::operator= (const Group::GriddedField4 & t) inline noexcept
Set value from Group::GriddedField4. Works when isnull() is false
Definition at line 3071 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::GriddedField4::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3074 of file autoarts.h.
References p.
value() [1/2]
const Group::GriddedField4& ARTS::Var::GriddedField4::value () const inline noexcept
Get value const-ref as Group::GriddedField4. Works when isnull() is false
Definition at line 3068 of file autoarts.h.
References v.
value() [2/2]
Group::GriddedField4& ARTS::Var::GriddedField4::value () inline noexcept
Get value ref as Group::GriddedField4. Works when isnull() is false
Definition at line 3065 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::GriddedFieldGetName(), ARTS::Method::GriddedFieldLatLonExpand(), ARTS::Method::Ignore(), and operator=().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField4 & var) friend
Output to stream of internal variable
Definition at line 3086 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::GriddedField4::p private
Definition at line 3049 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::GriddedField4* ARTS::Var::GriddedField4::v private
Definition at line 3050 of file autoarts.h.
Referenced by isnull(), value(), and ~GriddedField4().
The documentation for this class was generated from the following file:
autoarts.h