ARTS: ARTS::Var::WorkspaceArrayOfCIARecord Class Reference
ARTS::Var::WorkspaceArrayOfCIARecord Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfCIARecord () noexcept
WorkspaceArrayOfCIARecord (std::size_t i, void *x) noexcept
~WorkspaceArrayOfCIARecord () noexcept
WorkspaceArrayOfCIARecord (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfCIARecord & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfCIARecord
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 512 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfCIARecord::type = Group::ArrayOfCIARecord private
Definition at line 513 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfCIARecord() [1/3]
ARTS::Var::WorkspaceArrayOfCIARecord::WorkspaceArrayOfCIARecord () inline noexcept
Definition at line 517 of file autoarts.h.
WorkspaceArrayOfCIARecord() [2/3]
ARTS::Var::WorkspaceArrayOfCIARecord::WorkspaceArrayOfCIARecord (std::size_t i, void * x) inline noexcept
Definition at line 518 of file autoarts.h.
~WorkspaceArrayOfCIARecord()
ARTS::Var::WorkspaceArrayOfCIARecord::~WorkspaceArrayOfCIARecord () inline noexcept
Definition at line 519 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfCIARecord() [3/3]
ARTS::Var::WorkspaceArrayOfCIARecord::WorkspaceArrayOfCIARecord (const type & val) inline noexcept
Definition at line 520 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfCIARecord::islast () const inline noexcept
Definition at line 526 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfCIARecord().
isnull()
bool ARTS::Var::WorkspaceArrayOfCIARecord::isnull () const inline noexcept
Definition at line 525 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfCIARecord().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfCIARecord::name () const inline noexcept
Definition at line 527 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfCIARecord& ARTS::Var::WorkspaceArrayOfCIARecord::operator= (const type & t) inline noexcept
Definition at line 523 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfCIARecord::pos () const inline noexcept
Definition at line 524 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfCIARecord::value () const inline noexcept
Definition at line 522 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfCIARecord::value () inline noexcept
Definition at line 521 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfCIARecord::p private
Definition at line 514 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfCIARecord::v private
Definition at line 515 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfCIARecord().
The documentation for this class was generated from the following file:
autoarts.h