ARTS: ARTS::Var::EnergyLevelMap Class Reference
ARTS::Var::EnergyLevelMap Class Reference
#include <autoarts.h>
Public Member Functions
EnergyLevelMap () noexcept
EnergyLevelMap (std::size_t i, void *x) noexcept
EnergyLevelMap (const Group::EnergyLevelMap &val) noexcept
~EnergyLevelMap () noexcept
Group::EnergyLevelMap & value () noexcept
const Group::EnergyLevelMap & value () const noexcept
EnergyLevelMap & operator= (const Group::EnergyLevelMap &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::EnergyLevelMap * v
Friends
std::ostream & operator<< (std::ostream &os, const EnergyLevelMap &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 2766 of file autoarts.h.
Constructor & Destructor Documentation
EnergyLevelMap() [1/3]
ARTS::Var::EnergyLevelMap::EnergyLevelMap () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 2771 of file autoarts.h.
EnergyLevelMap() [2/3]
ARTS::Var::EnergyLevelMap::EnergyLevelMap (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 2774 of file autoarts.h.
EnergyLevelMap() [3/3]
ARTS::Var::EnergyLevelMap::EnergyLevelMap (const Group::EnergyLevelMap & val) inline noexcept
Construct from Group::EnergyLevelMap. Leaves islast() true and isnull() false
Definition at line 2777 of file autoarts.h.
~EnergyLevelMap()
ARTS::Var::EnergyLevelMap::~EnergyLevelMap () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 2780 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::EnergyLevelMap::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 2798 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~EnergyLevelMap().
isnull()
bool ARTS::Var::EnergyLevelMap::isnull () const inline noexcept
Return true if there is no data
Definition at line 2795 of file autoarts.h.
References v.
Referenced by ~EnergyLevelMap().
name()
const Group::String& ARTS::Var::EnergyLevelMap::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 2801 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
EnergyLevelMap& ARTS::Var::EnergyLevelMap::operator= (const Group::EnergyLevelMap & t) inline noexcept
Set value from Group::EnergyLevelMap. Works when isnull() is false
Definition at line 2789 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::EnergyLevelMap::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 2792 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Ignore(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::EnergyLevelMap& ARTS::Var::EnergyLevelMap::value () const inline noexcept
Get value const-ref as Group::EnergyLevelMap. Works when isnull() is false
Definition at line 2786 of file autoarts.h.
References v.
value() [2/2]
Group::EnergyLevelMap& ARTS::Var::EnergyLevelMap::value () inline noexcept
Get value ref as Group::EnergyLevelMap. Works when isnull() is false
Definition at line 2783 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const EnergyLevelMap & var) friend
Output to stream of internal variable
Definition at line 2804 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::EnergyLevelMap::p private
Definition at line 2767 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::EnergyLevelMap* ARTS::Var::EnergyLevelMap::v private
Definition at line 2768 of file autoarts.h.
Referenced by isnull(), value(), and ~EnergyLevelMap().
The documentation for this class was generated from the following file:
autoarts.h