ARTS: ARTS::Var::WorkspaceArrayOfArrayOfStokesVector Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfStokesVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfStokesVector () noexcept
WorkspaceArrayOfArrayOfStokesVector (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfStokesVector () noexcept
WorkspaceArrayOfArrayOfStokesVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfStokesVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfStokesVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 386 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::type = Group::ArrayOfArrayOfStokesVector private
Definition at line 387 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfStokesVector() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::WorkspaceArrayOfArrayOfStokesVector () inline noexcept
Definition at line 391 of file autoarts.h.
WorkspaceArrayOfArrayOfStokesVector() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::WorkspaceArrayOfArrayOfStokesVector (std::size_t i, void * x) inline noexcept
Definition at line 392 of file autoarts.h.
~WorkspaceArrayOfArrayOfStokesVector()
ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::~WorkspaceArrayOfArrayOfStokesVector () inline noexcept
Definition at line 393 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfStokesVector() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::WorkspaceArrayOfArrayOfStokesVector (const type & val) inline noexcept
Definition at line 394 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::islast () const inline noexcept
Definition at line 400 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfStokesVector().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::isnull () const inline noexcept
Definition at line 399 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfStokesVector().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::name () const inline noexcept
Definition at line 401 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfStokesVector& ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::operator= (const type & t) inline noexcept
Definition at line 397 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::pos () const inline noexcept
Definition at line 398 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::value () const inline noexcept
Definition at line 396 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::value () inline noexcept
Definition at line 395 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::p private
Definition at line 388 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfStokesVector::v private
Definition at line 389 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfStokesVector().
The documentation for this class was generated from the following file:
autoarts.h