ARTS: ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag Class Reference
ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfArrayOfSpeciesTag () noexcept
WorkspaceArrayOfArrayOfSpeciesTag (std::size_t i, void *x) noexcept
~WorkspaceArrayOfArrayOfSpeciesTag () noexcept
WorkspaceArrayOfArrayOfSpeciesTag (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfArrayOfSpeciesTag & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfArrayOfSpeciesTag
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 368 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::type = Group::ArrayOfArrayOfSpeciesTag private
Definition at line 369 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfArrayOfSpeciesTag() [1/3]
ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::WorkspaceArrayOfArrayOfSpeciesTag () inline noexcept
Definition at line 373 of file autoarts.h.
WorkspaceArrayOfArrayOfSpeciesTag() [2/3]
ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::WorkspaceArrayOfArrayOfSpeciesTag (std::size_t i, void * x) inline noexcept
Definition at line 374 of file autoarts.h.
~WorkspaceArrayOfArrayOfSpeciesTag()
ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::~WorkspaceArrayOfArrayOfSpeciesTag () inline noexcept
Definition at line 375 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfArrayOfSpeciesTag() [3/3]
ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::WorkspaceArrayOfArrayOfSpeciesTag (const type & val) inline noexcept
Definition at line 376 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::islast () const inline noexcept
Definition at line 382 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfArrayOfSpeciesTag().
isnull()
bool ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::isnull () const inline noexcept
Definition at line 381 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfArrayOfSpeciesTag().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::name () const inline noexcept
Definition at line 383 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfArrayOfSpeciesTag& ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::operator= (const type & t) inline noexcept
Definition at line 379 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::pos () const inline noexcept
Definition at line 380 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::value () const inline noexcept
Definition at line 378 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::value () inline noexcept
Definition at line 377 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::p private
Definition at line 370 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfArrayOfSpeciesTag::v private
Definition at line 371 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfArrayOfSpeciesTag().
The documentation for this class was generated from the following file:
autoarts.h