ARTS: ARTS::Var::WorkspaceArrayOfTensor4 Class Reference
ARTS::Var::WorkspaceArrayOfTensor4 Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTensor4 () noexcept
WorkspaceArrayOfTensor4 (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTensor4 () noexcept
WorkspaceArrayOfTensor4 (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTensor4 & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTensor4
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 854 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTensor4::type = Group::ArrayOfTensor4 private
Definition at line 855 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTensor4() [1/3]
ARTS::Var::WorkspaceArrayOfTensor4::WorkspaceArrayOfTensor4 () inline noexcept
Definition at line 859 of file autoarts.h.
WorkspaceArrayOfTensor4() [2/3]
ARTS::Var::WorkspaceArrayOfTensor4::WorkspaceArrayOfTensor4 (std::size_t i, void * x) inline noexcept
Definition at line 860 of file autoarts.h.
~WorkspaceArrayOfTensor4()
ARTS::Var::WorkspaceArrayOfTensor4::~WorkspaceArrayOfTensor4 () inline noexcept
Definition at line 861 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTensor4() [3/3]
ARTS::Var::WorkspaceArrayOfTensor4::WorkspaceArrayOfTensor4 (const type & val) inline noexcept
Definition at line 862 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTensor4::islast () const inline noexcept
Definition at line 868 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTensor4().
isnull()
bool ARTS::Var::WorkspaceArrayOfTensor4::isnull () const inline noexcept
Definition at line 867 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTensor4().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTensor4::name () const inline noexcept
Definition at line 869 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTensor4& ARTS::Var::WorkspaceArrayOfTensor4::operator= (const type & t) inline noexcept
Definition at line 865 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTensor4::pos () const inline noexcept
Definition at line 866 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Extract(), ARTS::AgendaMethod::Flatten(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTensor4::value () const inline noexcept
Definition at line 864 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTensor4::value () inline noexcept
Definition at line 863 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Extract(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTensor4::p private
Definition at line 856 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTensor4::v private
Definition at line 857 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTensor4().
The documentation for this class was generated from the following file:
autoarts.h