ARTS: ARTS::Var::WorkspaceArrayOfTransmissionMatrix Class Reference
ARTS::Var::WorkspaceArrayOfTransmissionMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfTransmissionMatrix () noexcept
WorkspaceArrayOfTransmissionMatrix (std::size_t i, void *x) noexcept
~WorkspaceArrayOfTransmissionMatrix () noexcept
WorkspaceArrayOfTransmissionMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfTransmissionMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfTransmissionMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 944 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfTransmissionMatrix::type = Group::ArrayOfTransmissionMatrix private
Definition at line 945 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfTransmissionMatrix() [1/3]
ARTS::Var::WorkspaceArrayOfTransmissionMatrix::WorkspaceArrayOfTransmissionMatrix () inline noexcept
Definition at line 949 of file autoarts.h.
WorkspaceArrayOfTransmissionMatrix() [2/3]
ARTS::Var::WorkspaceArrayOfTransmissionMatrix::WorkspaceArrayOfTransmissionMatrix (std::size_t i, void * x) inline noexcept
Definition at line 950 of file autoarts.h.
~WorkspaceArrayOfTransmissionMatrix()
ARTS::Var::WorkspaceArrayOfTransmissionMatrix::~WorkspaceArrayOfTransmissionMatrix () inline noexcept
Definition at line 951 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfTransmissionMatrix() [3/3]
ARTS::Var::WorkspaceArrayOfTransmissionMatrix::WorkspaceArrayOfTransmissionMatrix (const type & val) inline noexcept
Definition at line 952 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfTransmissionMatrix::islast () const inline noexcept
Definition at line 958 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfTransmissionMatrix().
isnull()
bool ARTS::Var::WorkspaceArrayOfTransmissionMatrix::isnull () const inline noexcept
Definition at line 957 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfTransmissionMatrix().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfTransmissionMatrix::name () const inline noexcept
Definition at line 959 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfTransmissionMatrix& ARTS::Var::WorkspaceArrayOfTransmissionMatrix::operator= (const type & t) inline noexcept
Definition at line 955 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfTransmissionMatrix::pos () const inline noexcept
Definition at line 956 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfTransmissionMatrix::value () const inline noexcept
Definition at line 954 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfTransmissionMatrix::value () inline noexcept
Definition at line 953 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfTransmissionMatrix::p private
Definition at line 946 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfTransmissionMatrix::v private
Definition at line 947 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfTransmissionMatrix().
The documentation for this class was generated from the following file:
autoarts.h