ARTS: RadiationVector Class Reference
RadiationVector Class Reference
Radiation Vector for Stokes dimension 1-4.
#include <transmissionmatrix.h>
Public Member Functions
RadiationVector (Index nf=0, Index stokes=1)
Construct a new Radiation Vector object.
RadiationVector (RadiationVector &&rv) noexcept
Construct a new Radiation Vector object.
RadiationVector (const RadiationVector &rv)=default
Construct a new Radiation Vector object.
RadiationVector & operator= (const RadiationVector &rv)=default
Assign old radiation vector to this.
RadiationVector & operator= (RadiationVector &&rv) noexcept
Assign old radiation vector to this.
void leftMul (const TransmissionMatrix &T)
Multiply radiation vector from the left.
void SetZero (size_t i)
Set Radiation Vector to Zero at position.
const Eigen::Vector4d & Vec4 (size_t i) const
Return Vector at position.
const Eigen::Vector3d & Vec3 (size_t i) const
Return Vector at position.
const Eigen::Vector2d & Vec2 (size_t i) const
Return Vector at position.
const Eigen::Matrix< double, 1, 1 > & Vec1 (size_t i) const
Return Vector at position.
Eigen::VectorXd Vec (size_t i) const
Return Vector at position by copy.
Eigen::Vector4d & Vec4 (size_t i)
Return Vector at position.
Eigen::Vector3d & Vec3 (size_t i)
Return Vector at position.
Eigen::Vector2d & Vec2 (size_t i)
Return Vector at position.
Eigen::Matrix< double, 1, 1 > & Vec1 (size_t i)
Return Vector at position.
void rem_avg (const RadiationVector &O1, const RadiationVector &O2)
Remove the average of two other RadiationVector from *this.
void add_avg (const RadiationVector &O1, const RadiationVector &O2)
Add the average of two other RadiationVector to *this.
void add_weighted (const TransmissionMatrix &T, const RadiationVector &far, const RadiationVector &close, const ConstMatrixView Kfar, const ConstMatrixView Kclose, const Numeric r)
Add the weighted source of two RadiationVector to *this.
void addDerivEmission (const TransmissionMatrix &PiT, const TransmissionMatrix &dT, const TransmissionMatrix &T, const RadiationVector &ImJ, const RadiationVector &dJ)
Add the emission derivative to this.
void addWeightedDerivEmission (const TransmissionMatrix &PiT, const TransmissionMatrix &dT, const TransmissionMatrix &T, const RadiationVector &I, const RadiationVector &far, const RadiationVector &close, const RadiationVector &d, bool isfar)
Add the emission derivative to this.
void addDerivTransmission (const TransmissionMatrix &PiT, const TransmissionMatrix &dT, const RadiationVector &I)
Add the transmission derivative to this.
void addMultiplied (const TransmissionMatrix &A, const RadiationVector &x)
Add multiply.
void setDerivReflection (const RadiationVector &I, const TransmissionMatrix &PiT, const TransmissionMatrix &Z, const TransmissionMatrix &dZ)
Sets *this to the reflection derivative.
void setBackscatterTransmission (const RadiationVector &I0, const TransmissionMatrix &Tr, const TransmissionMatrix &Tf, const TransmissionMatrix &Z)
Set this to backscatter transmission.
void setBackscatterTransmissionDerivative (const RadiationVector &I0, const TransmissionMatrix &Tr, const TransmissionMatrix &Tf, const TransmissionMatrix &dZ)
Set this to backscatter transmission scatter derivative.
RadiationVector & operator= (const ConstMatrixView &M)
Set *this from matrix.
const Numeric & operator() (const Index i, const Index j) const
Access operator.
operator Matrix () const
Convert *this to Matrix class.
void setSource (const StokesVector &a, const ConstVectorView &B, const StokesVector &S, Index i)
Set this to source vector at position.
Index StokesDim () const
Get Stokes dimension.
Index Frequencies () const
Get frequency count.
Private Attributes
Index stokes_dim
std::vector< Eigen::Vector4d, Eigen::aligned_allocator< Eigen::Vector4d > > R4
std::vector< Eigen::Vector3d, Eigen::aligned_allocator< Eigen::Vector3d > > R3
std::vector< Eigen::Vector2d, Eigen::aligned_allocator< Eigen::Vector2d > > R2
std::vector< Eigen::Matrix< double, 1, 1 >, Eigen::aligned_allocator< Eigen::Matrix< double, 1, 1 > > > R1
Friends
std::ostream & operator<< (std::ostream &os, const RadiationVector &rv)
Output operator.
std::istream & operator>> (std::istream &data, RadiationVector &rv)
Input operator.
Detailed Description
Radiation Vector for Stokes dimension 1-4.
Definition at line 471 of file transmissionmatrix.h.
Constructor & Destructor Documentation
RadiationVector() [1/3]
RadiationVector::RadiationVector (Index nf = 0, Index stokes = 1) inline
Construct a new Radiation Vector object.
Parameters
[in] nf Number of frequencies
[in] stokes Stokes dimension
Definition at line 488 of file transmissionmatrix.h.
References ARTS_ASSERT.
RadiationVector() [2/3]
RadiationVector::RadiationVector (RadiationVector && rv) inline noexcept
Construct a new Radiation Vector object.
Parameters
[in] rv Old Radiation Vector to move from
Definition at line 501 of file transmissionmatrix.h.
RadiationVector() [3/3]
RadiationVector::RadiationVector (const RadiationVector & rv) default
Construct a new Radiation Vector object.
Parameters
[in] rv Old Vector to copy from
Member Function Documentation
add_avg()
void RadiationVector::add_avg (const RadiationVector & O1, const RadiationVector & O2) inline
Add the average of two other RadiationVector to *this.
Parameters
[in] O1 Input 1
[in] O2 Input 2
Definition at line 664 of file transmissionmatrix.h.
References R1, R2, R3, and R4.
Referenced by update_radiation_vector().
add_weighted()
void RadiationVector::add_weighted (const TransmissionMatrix & T, const RadiationVector & far, const RadiationVector & close, const ConstMatrixView Kfar, const ConstMatrixView Kclose, const Numeric r) inline
Add the weighted source of two RadiationVector to *this.
Parameters
[in] T The transmission matrix
[in] far Input 1
[in] close Input 2
Definition at line 681 of file transmissionmatrix.h.
References joker, R1, R2, R3, R4, TransmissionMatrix::second_order_integration_source(), and TransmissionMatrix::TraMat().
Referenced by update_radiation_vector().
addDerivEmission()
void RadiationVector::addDerivEmission (const TransmissionMatrix & PiT, const TransmissionMatrix & dT, const TransmissionMatrix & T, const RadiationVector & ImJ, const RadiationVector & dJ) inline
Add the emission derivative to this.
Parameters
[in] PiT Accumulated transmission to space
[in] dT Derivative of transmission matrix
[in] T Transmission matrix
[in] ImJ Intensity minus the emission vector
[in] dJ Derivative of the emission vector
Definition at line 705 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
addDerivTransmission()
void RadiationVector::addDerivTransmission (const TransmissionMatrix & PiT, const TransmissionMatrix & dT, const RadiationVector & I) inline
Add the transmission derivative to this.
Parameters
[in] PiT Accumulated transmission to space
[in] dT Derivative of transmission matrix
[in] I Intensity vector
Definition at line 757 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
addMultiplied()
void RadiationVector::addMultiplied (const TransmissionMatrix & A, const RadiationVector & x) inline
Add multiply.
Performs essentially this += A * x
Assumes this and x are not aliases
Parameters
[in] A Derivative of transmission matrix
[in] x Intensity vector
Definition at line 780 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, R4, and x.
addWeightedDerivEmission()
void RadiationVector::addWeightedDerivEmission (const TransmissionMatrix & PiT, const TransmissionMatrix & dT, const TransmissionMatrix & T, const RadiationVector & I, const RadiationVector & far, const RadiationVector & close, const RadiationVector & d, bool isfar) inline
Add the emission derivative to this.
Parameters
[in] PiT Accumulated transmission to space
[in] dT Derivative of transmission matrix
[in] T Transmission matrix
[in] ImJ Intensity minus the emission vector
[in] dJ Derivative of the emission vector
Definition at line 732 of file transmissionmatrix.h.
References d, TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, R4, and TransmissionMatrix::second_order_integration_dsource().
Frequencies()
Index RadiationVector::Frequencies () const inline
Get frequency count.
Definition at line 974 of file transmissionmatrix.h.
References R1, R2, R3, R4, and stokes_dim.
Referenced by operator Matrix(), operator=(), and xml_write_to_stream().
leftMul()
void RadiationVector::leftMul (const TransmissionMatrix & T) inline
Multiply radiation vector from the left.
Parameters
[in] T Tranmission Vector
Definition at line 539 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
Referenced by update_radiation_vector().
operator Matrix()
RadiationVector::operator Matrix () const inline
Convert *this to Matrix class.
Returns
Matrix
Definition at line 907 of file transmissionmatrix.h.
References Frequencies(), M, R1, R2, R3, R4, and stokes_dim.
operator()()
const Numeric& RadiationVector::operator() (const Index i, const Index j) const inline
Access operator.
Parameters
[in] i Position in outer vector
[in] j Position in inner vector
Returns
const Numeric&
Definition at line 890 of file transmissionmatrix.h.
References R1, R2, R3, R4, and stokes_dim.
operator=() [1/3]
RadiationVector& RadiationVector::operator= (const ConstMatrixView & M) inline
Set *this from matrix.
Parameters
[in] M Matrix
Returns
RadiationVector& *this
Definition at line 861 of file transmissionmatrix.h.
References ARTS_ASSERT, Frequencies(), M, R1, R2, R3, R4, and stokes_dim.
operator=() [2/3]
RadiationVector& RadiationVector::operator= (const RadiationVector & rv) default
Assign old radiation vector to this.
Parameters
[in] rv old vetor to copy
Returns
RadiationVector& *this
operator=() [3/3]
RadiationVector& RadiationVector::operator= (RadiationVector && rv) inline noexcept
Assign old radiation vector to this.
Parameters
[in] rv old vetor to move from
Returns
RadiationVector& *this
Definition at line 526 of file transmissionmatrix.h.
References R1, R2, R3, R4, and stokes_dim.
rem_avg()
void RadiationVector::rem_avg (const RadiationVector & O1, const RadiationVector & O2) inline
Remove the average of two other RadiationVector from *this.
Parameters
[in] O1 Input 1
[in] O2 Input 2
Definition at line 647 of file transmissionmatrix.h.
References R1, R2, R3, and R4.
Referenced by update_radiation_vector().
setBackscatterTransmission()
void RadiationVector::setBackscatterTransmission (const RadiationVector & I0, const TransmissionMatrix & Tr, const TransmissionMatrix & Tf, const TransmissionMatrix & Z) inline
Set this to backscatter transmission.
Parameters
[in] I0 Incoming intensity vector
[in] Tr Reflection transmission
[in] Tf Forward transmission
[in] Z Reflection matrix
Definition at line 821 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
setBackscatterTransmissionDerivative()
void RadiationVector::setBackscatterTransmissionDerivative (const RadiationVector & I0, const TransmissionMatrix & Tr, const TransmissionMatrix & Tf, const TransmissionMatrix & dZ) inline
Set this to backscatter transmission scatter derivative.
Parameters
[in] I0 Incoming intensity vector
[in] Tr Reflection transmission
[in] Tf Forward transmission
[in] dZ Reflection matrix derivative
Definition at line 842 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
setDerivReflection()
void RadiationVector::setDerivReflection (const RadiationVector & I, const TransmissionMatrix & PiT, const TransmissionMatrix & Z, const TransmissionMatrix & dZ) inline
Sets *this to the reflection derivative.
Parameters
[in] I Intensity vector
[in] PiT Accumulated transmission to space
[in] Z Reflection matrix
[in] dZ Derivative of reflection matrix
Definition at line 799 of file transmissionmatrix.h.
References TransmissionMatrix::Mat1(), TransmissionMatrix::Mat2(), TransmissionMatrix::Mat3(), TransmissionMatrix::Mat4(), R1, R2, R3, and R4.
setSource()
void RadiationVector::setSource (const StokesVector & a, const ConstVectorView & B, const StokesVector & S, Index i) inline
Set this to source vector at position.
Parameters
[in] a Absorption vector
[in] B Planck vector
[in] S Scattering source vector
[in] i Position
Definition at line 926 of file transmissionmatrix.h.
References a, ARTS_ASSERT, PropagationMatrix::IsEmpty(), PropagationMatrix::K12(), PropagationMatrix::K13(), PropagationMatrix::K14(), PropagationMatrix::Kjj(), PropagationMatrix::NumberOfAzimuthAngles(), PropagationMatrix::NumberOfZenithAngles(), R1, R2, R3, R4, and stokes_dim.
Referenced by stepwise_source().
SetZero()
void RadiationVector::SetZero (size_t i) inline
Set Radiation Vector to Zero at position.
Parameters
[in] i position
Definition at line 550 of file transmissionmatrix.h.
References R1, R2, R3, R4, and stokes_dim.
Referenced by stepwise_source().
StokesDim()
Index RadiationVector::StokesDim () const inline
Get Stokes dimension.
Definition at line 971 of file transmissionmatrix.h.
References stokes_dim.
Referenced by stepwise_source(), and xml_write_to_stream().
Vec()
Eigen::VectorXd RadiationVector::Vec (size_t i) const inline
Return Vector at position by copy.
Parameters
[in] i position
Returns
const Eigen::Matrix<double, 1, 1>& Vector
Definition at line 600 of file transmissionmatrix.h.
References stokes_dim, Vec1(), Vec2(), Vec3(), and Vec4().
Vec1() [1/2]
Eigen::Matrix<double, 1, 1>& RadiationVector::Vec1 (size_t i) inline
Return Vector at position.
Parameters
[in] i position
Returns
Eigen::Matrix<double, 1, 1>& Vector
Definition at line 640 of file transmissionmatrix.h.
References R1.
Vec1() [2/2]
const Eigen::Matrix<double, 1, 1>& RadiationVector::Vec1 (size_t i) const inline
Return Vector at position.
Parameters
[in] i position
Returns
const Eigen::Matrix<double, 1, 1>& Vector
Definition at line 593 of file transmissionmatrix.h.
References R1.
Referenced by stepwise_source(), and Vec().
Vec2() [1/2]
Eigen::Vector2d& RadiationVector::Vec2 (size_t i) inline
Return Vector at position.
Parameters
[in] i position
Returns
Eigen::Vector2d& Vector
Definition at line 633 of file transmissionmatrix.h.
References R2.
Vec2() [2/2]
const Eigen::Vector2d& RadiationVector::Vec2 (size_t i) const inline
Return Vector at position.
Parameters
[in] i position
Returns
const Eigen::Vector2d& Vector
Definition at line 586 of file transmissionmatrix.h.
References R2.
Referenced by stepwise_source(), and Vec().
Vec3() [1/2]
Eigen::Vector3d& RadiationVector::Vec3 (size_t i) inline
Return Vector at position.
Parameters
[in] i position
Returns
Eigen::Vector3d& Vector
Definition at line 626 of file transmissionmatrix.h.
References R3.
Vec3() [2/2]
const Eigen::Vector3d& RadiationVector::Vec3 (size_t i) const inline
Return Vector at position.
Parameters
[in] i position
Returns
const Eigen::Vector3d& Vector
Definition at line 579 of file transmissionmatrix.h.
References R3.
Referenced by stepwise_source(), and Vec().
Vec4() [1/2]
Eigen::Vector4d& RadiationVector::Vec4 (size_t i) inline
Return Vector at position.
Parameters
[in] i position
Returns
Eigen::Vector4d& Vector
Definition at line 619 of file transmissionmatrix.h.
References R4.
Vec4() [2/2]
const Eigen::Vector4d& RadiationVector::Vec4 (size_t i) const inline
Return Vector at position.
Parameters
[in] i position
Returns
const Eigen::Vector4d& Vector
Definition at line 572 of file transmissionmatrix.h.
References R4.
Referenced by stepwise_source(), and Vec().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const RadiationVector & rv) friend
Output operator.
Definition at line 1695 of file transmissionmatrix.cc.
operator>>
std::istream& operator>> (std::istream & data, RadiationVector & rv) friend
Input operator.
Definition at line 1731 of file transmissionmatrix.cc.
Member Data Documentation
R1
std::vector<Eigen::Matrix<double, 1, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 1, 1> > > RadiationVector::R1 private
Definition at line 479 of file transmissionmatrix.h.
Referenced by add_avg(), add_weighted(), addDerivEmission(), addDerivTransmission(), addMultiplied(), addWeightedDerivEmission(), Frequencies(), leftMul(), operator Matrix(), operator()(), operator=(), rem_avg(), setBackscatterTransmission(), setBackscatterTransmissionDerivative(), setDerivReflection(), setSource(), SetZero(), and Vec1().
R2
std::vector<Eigen::Vector2d, Eigen::aligned_allocator<Eigen::Vector2d> > RadiationVector::R2 private
Definition at line 476 of file transmissionmatrix.h.
Referenced by add_avg(), add_weighted(), addDerivEmission(), addDerivTransmission(), addMultiplied(), addWeightedDerivEmission(), Frequencies(), leftMul(), operator Matrix(), operator()(), operator=(), rem_avg(), setBackscatterTransmission(), setBackscatterTransmissionDerivative(), setDerivReflection(), setSource(), SetZero(), and Vec2().
R3
std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > RadiationVector::R3 private
Definition at line 475 of file transmissionmatrix.h.
Referenced by add_avg(), add_weighted(), addDerivEmission(), addDerivTransmission(), addMultiplied(), addWeightedDerivEmission(), Frequencies(), leftMul(), operator Matrix(), operator()(), operator=(), rem_avg(), setBackscatterTransmission(), setBackscatterTransmissionDerivative(), setDerivReflection(), setSource(), SetZero(), and Vec3().
R4
std::vector<Eigen::Vector4d, Eigen::aligned_allocator<Eigen::Vector4d> > RadiationVector::R4 private
Definition at line 474 of file transmissionmatrix.h.
Referenced by add_avg(), add_weighted(), addDerivEmission(), addDerivTransmission(), addMultiplied(), addWeightedDerivEmission(), Frequencies(), leftMul(), operator Matrix(), operator()(), operator=(), rem_avg(), setBackscatterTransmission(), setBackscatterTransmissionDerivative(), setDerivReflection(), setSource(), SetZero(), and Vec4().
stokes_dim
Index RadiationVector::stokes_dim private
Definition at line 473 of file transmissionmatrix.h.
Referenced by Frequencies(), operator Matrix(), operator()(), operator=(), setSource(), SetZero(), StokesDim(), and Vec().
The documentation for this class was generated from the following file:
transmissionmatrix.h