ARTS: ARTS::Var::WorkspaceTransmissionMatrix Class Reference
ARTS::Var::WorkspaceTransmissionMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceTransmissionMatrix () noexcept
WorkspaceTransmissionMatrix (std::size_t i, void *x) noexcept
~WorkspaceTransmissionMatrix () noexcept
WorkspaceTransmissionMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceTransmissionMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::TransmissionMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1646 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceTransmissionMatrix::type = Group::TransmissionMatrix private
Definition at line 1647 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceTransmissionMatrix() [1/3]
ARTS::Var::WorkspaceTransmissionMatrix::WorkspaceTransmissionMatrix () inline noexcept
Definition at line 1651 of file autoarts.h.
WorkspaceTransmissionMatrix() [2/3]
ARTS::Var::WorkspaceTransmissionMatrix::WorkspaceTransmissionMatrix (std::size_t i, void * x) inline noexcept
Definition at line 1652 of file autoarts.h.
~WorkspaceTransmissionMatrix()
ARTS::Var::WorkspaceTransmissionMatrix::~WorkspaceTransmissionMatrix () inline noexcept
Definition at line 1653 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceTransmissionMatrix() [3/3]
ARTS::Var::WorkspaceTransmissionMatrix::WorkspaceTransmissionMatrix (const type & val) inline noexcept
Definition at line 1654 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceTransmissionMatrix::islast () const inline noexcept
Definition at line 1660 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceTransmissionMatrix().
isnull()
bool ARTS::Var::WorkspaceTransmissionMatrix::isnull () const inline noexcept
Definition at line 1659 of file autoarts.h.
References v.
Referenced by ~WorkspaceTransmissionMatrix().
name()
const Group::String& ARTS::Var::WorkspaceTransmissionMatrix::name () const inline noexcept
Definition at line 1661 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceTransmissionMatrix& ARTS::Var::WorkspaceTransmissionMatrix::operator= (const type & t) inline noexcept
Definition at line 1657 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceTransmissionMatrix::pos () const inline noexcept
Definition at line 1658 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceTransmissionMatrix::value () const inline noexcept
Definition at line 1656 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceTransmissionMatrix::value () inline noexcept
Definition at line 1655 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceTransmissionMatrix::p private
Definition at line 1648 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceTransmissionMatrix::v private
Definition at line 1649 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceTransmissionMatrix().
The documentation for this class was generated from the following file:
autoarts.h