ARTS: MdRecord Class Reference
MdRecord Class Reference
All information for one workspace method.
#include <methods.h>
Public Member Functions
MdRecord ()
Default constructor.
MdRecord (const char name[], const char description[], const ArrayOfString &authors, const ArrayOfString &output, const ArrayOfString &gout, const ArrayOfString &gouttype, const ArrayOfString &goutdesc, const ArrayOfString &input, const ArrayOfString &gin, const ArrayOfString &gintype, const ArrayOfString &gindefault, const ArrayOfString &gindesc, bool set_method=false, bool agenda_method=false, bool uses_templates=false, bool pass_workspace=false, bool pass_wsv_names=false)
Initializing constructor for MdRecord.
MdRecord (const MdRecord &)=default
MdRecord (MdRecord &&)=default
const String & Name () const
const String & Description () const
const ArrayOfString & Authors () const
const ArrayOfIndex & Out () const
const ArrayOfString & GOut () const
const ArrayOfIndex & GOutType () const
const ArrayOfArrayOfIndex & GOutSpecType () const
const Array< String > & GOutDescription () const
const ArrayOfIndex & In () const
const ArrayOfString & GIn () const
const ArrayOfIndex & GInType () const
const ArrayOfArrayOfIndex & GInSpecType () const
const Array< String > & GInDefault () const
const Array< String > & GInDescription () const
const ArrayOfIndex & InOnly () const
const ArrayOfIndex & InOut () const
const ArrayOfIndex & OutOnly () const
bool SetMethod () const
bool AgendaMethod () const
bool Supergeneric () const
bool UsesTemplates () const
bool PassWorkspace () const
bool PassWsvNames () const
const String & ActualGroups () const
void SetPassWorkspace ()
void subst_any_with_group (Index g)
Expand supergeneric record for given group.
void subst_any_with_specific_group (Index g)
Expand supergeneric record for given Index in GOutSpecType and GInSpecType.
ostream & PrintTemplate (ostream &os, bool show_description=true) const
Print method template for the control file.
MdRecord & operator= (const MdRecord &m)
To override the default assignment operator.
Private Attributes
String mname
The name of this method.
String mdescription
A text string describing this method.
ArrayOfString mauthors
Author(s) of this method.
ArrayOfIndex moutput
Workspace Output.
ArrayOfString mgout
Generic Workspace Output Names.
ArrayOfIndex mgouttype
Generic Workspace Output Type.
ArrayOfArrayOfIndex mgoutspectype
Generic Workspace Output Types (Contains the valid types if the method.
ArrayOfString mgoutdesc
Generic Workspace Output Description.
ArrayOfIndex minput
Workspace Input.
ArrayOfString mgin
Generic Workspace Input Names.
ArrayOfIndex mgintype
Generic Workspace Input.
ArrayOfArrayOfIndex mginspectype
Generic Workspace Input Types (Contains the valid types if the method.
ArrayOfString mgindefault
Generic Workspace Input Defaults.
ArrayOfString mgindesc
Generic Workspace Input Description.
ArrayOfIndex minonly
Indexes of Input-only variables.
ArrayOfIndex moutonly
Indexes of Output-only variables.
ArrayOfIndex minout
Indexes of Input-Output variables.
bool mset_method
Flag, whether this is a set method.
bool magenda_method
Flag, whether this is an agenda method.
bool msupergeneric
Flag, whether this method is supergeneric.
bool muses_templates
Flag, whether method implementation relies on templates.
bool mpass_workspace
Flag, whether a workspace reference should be passed to the WSM.
bool mpass_wsv_names
Flag, whether WSV names should be passed to the WSM.
String mactual_groups
The actual groups of a supergeneric method.
Friends
void subst_any_with_group (MdRecord &mdd, Index g)
Detailed Description
All information for one workspace method.
Definition at line 41 of file methods.h.
Constructor & Destructor Documentation
MdRecord() [1/4]
MdRecord::MdRecord () inline
Default constructor.
Definition at line 44 of file methods.h.
MdRecord() [2/4]
MdRecord::MdRecord (const char name[], const char description[], const ArrayOfString & authors, const ArrayOfString & output, const ArrayOfString & gout, const ArrayOfString & gouttype, const ArrayOfString & goutdesc, const ArrayOfString & input, const ArrayOfString & gin, const ArrayOfString & gintype, const ArrayOfString & gindefault, const ArrayOfString & gindesc, bool set_method = false, bool agenda_method = false, bool uses_templates = false, bool pass_workspace = false, bool pass_wsv_names = false)
Initializing constructor for MdRecord.
This is the only non-trivial constructor, which sets all the fields. The flag for supergenericity is not set directly, but inferred from the presence of Any_ in the generic input or output list.
Definition at line 67 of file methods_aux.cc.
References ARTS_ASSERT, get_wsv_group_id(), get_wsv_group_ids(), get_wsv_id(), mgin, mgindefault, mginspectype, mgintype, mgout, mgoutspectype, mgouttype, minonly, minput, mname, moutput, msupergeneric, muses_templates, Array< base >::nelem(), and Absorption::nelem().
MdRecord() [3/4]
MdRecord::MdRecord (const MdRecord &) default
MdRecord() [4/4]
MdRecord::MdRecord (MdRecord &&) default
Member Function Documentation
ActualGroups()
const String& MdRecord::ActualGroups () const inline
Definition at line 111 of file methods.h.
References mactual_groups.
Referenced by define_md_map(), and main().
AgendaMethod()
bool MdRecord::AgendaMethod () const inline
Definition at line 106 of file methods.h.
References magenda_method.
Referenced by main(), ArtsParser::parse_method(), write_method_header(), and write_method_header_documentation().
Authors()
const ArrayOfString& MdRecord::Authors () const inline
Definition at line 90 of file methods.h.
References mauthors.
Referenced by operator<<(), and write_method_header_documentation().
Description()
const String& MdRecord::Description () const inline
Definition at line 89 of file methods.h.
References mdescription.
Referenced by operator<<(), and write_method_header_documentation().
GIn()
const ArrayOfString& MdRecord::GIn () const inline
Definition at line 97 of file methods.h.
References mgin.
Referenced by operator<<(), ArtsParser::parse_generic_input(), ArtsParser::parse_method_args(), PrintTemplate(), ArtsParser::set_gin_to_default(), write_method_header(), and write_method_header_documentation().
GInDefault()
const Array<String>& MdRecord::GInDefault () const inline
Definition at line 100 of file methods.h.
References mgindefault.
Referenced by operator<<(), ArtsParser::parse_method_args(), ArtsParser::set_gin_to_default(), and write_method_header_documentation().
GInDescription()
const Array<String>& MdRecord::GInDescription () const inline
Definition at line 101 of file methods.h.
References mgindesc.
Referenced by operator<<().
GInSpecType()
const ArrayOfArrayOfIndex& MdRecord::GInSpecType () const inline
Definition at line 99 of file methods.h.
References mginspectype.
Referenced by expand_md_data_raw_to_md_data(), operator<<(), option_input(), and ArtsParser::parse_generic_input().
GInType()
const ArrayOfIndex& MdRecord::GInType () const inline
Definition at line 98 of file methods.h.
References mgintype.
Referenced by main(), operator<<(), option_input(), option_workspacevariables(), ArtsParser::parse_generic_input(), MRecord::print(), PrintTemplate(), ArtsParser::set_gin_to_default(), write_method_header(), and write_method_header_documentation().
GOut()
const ArrayOfString& MdRecord::GOut () const inline
Definition at line 92 of file methods.h.
References mgout.
Referenced by operator<<(), ArtsParser::parse_generic_output(), ArtsParser::parse_method_args(), write_method_header(), and write_method_header_documentation().
GOutDescription()
const Array<String>& MdRecord::GOutDescription () const inline
Definition at line 95 of file methods.h.
References mgoutdesc.
Referenced by operator<<().
GOutSpecType()
const ArrayOfArrayOfIndex& MdRecord::GOutSpecType () const inline
Definition at line 94 of file methods.h.
References mgoutspectype.
Referenced by expand_md_data_raw_to_md_data(), operator<<(), option_methods(), and ArtsParser::parse_generic_output().
GOutType()
const ArrayOfIndex& MdRecord::GOutType () const inline
Definition at line 93 of file methods.h.
References mgouttype.
Referenced by main(), operator<<(), option_methods(), ArtsParser::parse_generic_output(), MRecord::print(), PrintTemplate(), write_method_header(), and write_method_header_documentation().
In()
const ArrayOfIndex& MdRecord::In () const inline
Definition at line 96 of file methods.h.
References minput.
Referenced by main(), operator<<(), option_input(), option_workspacevariables(), write_method_header(), and write_method_header_documentation().
InOnly()
const ArrayOfIndex& MdRecord::InOnly () const inline
Definition at line 102 of file methods.h.
References minonly.
Referenced by main(), operator<<(), ArtsParser::parse_method_args(), ArtsParser::parse_specific_input(), write_method_header(), and write_method_header_documentation().
InOut()
const ArrayOfIndex& MdRecord::InOut () const inline
Definition at line 103 of file methods.h.
References minout.
Referenced by Agenda::execute().
Name()
const String& MdRecord::Name () const inline
Definition at line 88 of file methods.h.
References mname.
Referenced by define_md_map(), Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), main(), operator<<(), option_input(), option_methods(), option_workspacevariables(), ArtsParser::parse_generic_input(), ArtsParser::parse_generic_output(), ArtsParser::parse_method(), ArtsParser::parse_method_args(), ArtsParser::parse_specific_output(), MRecord::print(), PrintTemplate(), ArtsParser::read_name_or_value(), ArtsParser::set_gin_to_default(), write_method_header(), and write_method_header_documentation().
operator=()
MdRecord& MdRecord::operator= (const MdRecord & m) inline
To override the default assignment operator.
MdRecords cannot be assigned!
Definition at line 133 of file methods.h.
References arts_exit(), and ARTS::Var::verbosity().
Out()
const ArrayOfIndex& MdRecord::Out () const inline
Definition at line 91 of file methods.h.
References moutput.
Referenced by main(), operator<<(), option_methods(), ArtsParser::parse_method_args(), ArtsParser::parse_specific_input(), ArtsParser::parse_specific_output(), write_method_header(), and write_method_header_documentation().
OutOnly()
const ArrayOfIndex& MdRecord::OutOnly () const inline
Definition at line 104 of file methods.h.
References moutonly.
PassWorkspace()
bool MdRecord::PassWorkspace () const inline
Definition at line 109 of file methods.h.
References mpass_workspace.
Referenced by write_method_header(), and write_method_header_documentation().
PassWsvNames()
bool MdRecord::PassWsvNames () const inline
Definition at line 110 of file methods.h.
References mpass_wsv_names.
Referenced by write_method_header(), and write_method_header_documentation().
PrintTemplate()
ostream & MdRecord::PrintTemplate (ostream & os, bool show_description = true) const
Print method template for the control file.
This prints the method data exactly in the same way how it can be included in the control file. The description string is also printed as a comment, but this can be turned off by setting show_comment to false.
Parameters
os Output stream
show_description Should the description string also be printed?
Definition at line 572 of file methods_aux.cc.
References GIn(), GInType(), GOutType(), Name(), Array< base >::nelem(), Absorption::nelem(), and global_data::wsv_group_names.
SetMethod()
bool MdRecord::SetMethod () const inline
Definition at line 105 of file methods.h.
References mset_method.
Referenced by Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), and ArtsParser::parse_generic_input().
SetPassWorkspace()
void MdRecord::SetPassWorkspace () inline
Definition at line 112 of file methods.h.
References mpass_workspace.
subst_any_with_group()
void MdRecord::subst_any_with_group (Index g)
Expand supergeneric record for given group.
This function will substitute any occurance of Any_ in the GOutType and GInType list of MdRecord by group g.
It also adds the group to the name like this: Copy becomes Copy_sg_Vector, Copy_sg_Matrix, etc..
Parameters
g The group for which to expand.
Definition at line 321 of file methods_aux.cc.
References ARTS_ASSERT, get_wsv_group_id(), mactual_groups, mgintype, mgouttype, Array< base >::nelem(), Supergeneric(), and global_data::wsv_group_names.
subst_any_with_specific_group()
void MdRecord::subst_any_with_specific_group (Index g)
Expand supergeneric record for given Index in GOutSpecType and GInSpecType.
This function will substitute any occurance of Any_ in the GOutType and GInType list of MdRecord by group GOutSpecType[g] and GInSpecType[g].
It also adds the group to the name like this: Copy becomes Copy_sg_Vector, Copy_sg_Matrix, etc..
Parameters
g The SpecType index for which to expand.
Definition at line 364 of file methods_aux.cc.
References ARTS_ASSERT, get_wsv_group_id(), mactual_groups, mginspectype, mgintype, mgoutspectype, mgouttype, Array< base >::nelem(), Supergeneric(), and global_data::wsv_group_names.
Supergeneric()
bool MdRecord::Supergeneric () const inline
Definition at line 107 of file methods.h.
References msupergeneric.
Referenced by define_md_map(), expand_md_data_raw_to_md_data(), main(), ArtsParser::parse_method_args(), subst_any_with_group(), subst_any_with_specific_group(), write_method_header(), and write_method_header_documentation().
UsesTemplates()
bool MdRecord::UsesTemplates () const inline
Definition at line 108 of file methods.h.
References muses_templates.
Referenced by main(), and write_method_header().
Friends And Related Function Documentation
subst_any_with_group
void subst_any_with_group (MdRecord & mdd, Index g) friend
Member Data Documentation
mactual_groups
String MdRecord::mactual_groups private
The actual groups of a supergeneric method.
This holds the actual groups after expansion of a supergeneric method.
Definition at line 246 of file methods.h.
Referenced by ActualGroups(), subst_any_with_group(), and subst_any_with_specific_group().
magenda_method
bool MdRecord::magenda_method private
Flag, whether this is an agenda method.
Agenda methods expect other method definitions inside their body in the controlfile.
Definition at line 211 of file methods.h.
Referenced by AgendaMethod().
mauthors
ArrayOfString MdRecord::mauthors private
Author(s) of this method.
Definition at line 153 of file methods.h.
Referenced by Authors().
mdescription
String MdRecord::mdescription private
A text string describing this method.
Definition at line 150 of file methods.h.
Referenced by Description().
mgin
ArrayOfString MdRecord::mgin private
Generic Workspace Input Names.
Definition at line 175 of file methods.h.
Referenced by GIn(), and MdRecord().
mgindefault
ArrayOfString MdRecord::mgindefault private
Generic Workspace Input Defaults.
Definition at line 185 of file methods.h.
Referenced by GInDefault(), and MdRecord().
mgindesc
ArrayOfString MdRecord::mgindesc private
Generic Workspace Input Description.
Definition at line 188 of file methods.h.
Referenced by GInDescription().
mginspectype
ArrayOfArrayOfIndex MdRecord::mginspectype private
Generic Workspace Input Types (Contains the valid types if the method.
Definition at line 182 of file methods.h.
Referenced by GInSpecType(), MdRecord(), and subst_any_with_specific_group().
mgintype
ArrayOfIndex MdRecord::mgintype private
Generic Workspace Input.
Definition at line 178 of file methods.h.
Referenced by GInType(), MdRecord(), subst_any_with_group(), and subst_any_with_specific_group().
mgout
ArrayOfString MdRecord::mgout private
Generic Workspace Output Names.
Definition at line 159 of file methods.h.
Referenced by GOut(), and MdRecord().
mgoutdesc
ArrayOfString MdRecord::mgoutdesc private
Generic Workspace Output Description.
Definition at line 169 of file methods.h.
Referenced by GOutDescription().
mgoutspectype
ArrayOfArrayOfIndex MdRecord::mgoutspectype private
Generic Workspace Output Types (Contains the valid types if the method.
Definition at line 166 of file methods.h.
Referenced by GOutSpecType(), MdRecord(), and subst_any_with_specific_group().
mgouttype
ArrayOfIndex MdRecord::mgouttype private
Generic Workspace Output Type.
Definition at line 162 of file methods.h.
Referenced by GOutType(), MdRecord(), subst_any_with_group(), and subst_any_with_specific_group().
minonly
ArrayOfIndex MdRecord::minonly private
Indexes of Input-only variables.
Definition at line 191 of file methods.h.
Referenced by InOnly(), and MdRecord().
minout
ArrayOfIndex MdRecord::minout private
Indexes of Input-Output variables.
Definition at line 197 of file methods.h.
Referenced by InOut().
minput
ArrayOfIndex MdRecord::minput private
Workspace Input.
Definition at line 172 of file methods.h.
Referenced by In(), and MdRecord().
mname
String MdRecord::mname private
The name of this method.
Definition at line 147 of file methods.h.
Referenced by MdRecord(), and Name().
moutonly
ArrayOfIndex MdRecord::moutonly private
Indexes of Output-only variables.
Definition at line 194 of file methods.h.
Referenced by OutOnly().
moutput
ArrayOfIndex MdRecord::moutput private
Workspace Output.
Definition at line 156 of file methods.h.
Referenced by MdRecord(), and Out().
mpass_workspace
bool MdRecord::mpass_workspace private
Flag, whether a workspace reference should be passed to the WSM.
Some WSMs (like Delete) need direct access to the workspace object. If this flag is set to true, the gateway function will take care of that.
Definition at line 232 of file methods.h.
Referenced by PassWorkspace(), and SetPassWorkspace().
mpass_wsv_names
bool MdRecord::mpass_wsv_names private
Flag, whether WSV names should be passed to the WSM.
Some WSMs (like ReadXML, WriteXML) need to know the names of the WSVs that have been passed to them. If this flag is set to true, the gateway function will take care of that.
Definition at line 240 of file methods.h.
Referenced by PassWsvNames().
mset_method
bool MdRecord::mset_method private
Flag, whether this is a set method.
Set methods have exactly one generic input. Unlike other inputs these are not stored in a workspace variable.
Definition at line 204 of file methods.h.
Referenced by SetMethod().
msupergeneric
bool MdRecord::msupergeneric private
Flag, whether this method is supergeneric.
This flag is set automatically if the gouttype or gintype contains Any_.
Definition at line 218 of file methods.h.
Referenced by MdRecord(), and Supergeneric().
muses_templates
bool MdRecord::muses_templates private
Flag, whether method implementation relies on templates.
If we want to implement a supergeneric method by a template function, we must not generate explicit method headers in auto_md.h.
Definition at line 225 of file methods.h.
Referenced by MdRecord(), and UsesTemplates().
The documentation for this class was generated from the following files:
methods.h
methods_aux.cc