ARTS: GriddedField3 Class Reference
GriddedField3 Class Reference final
#include <gridded_fields.h>
Public Member Functions
GriddedField3 ()
Construct an empty GriddedField3.
GriddedField3 (const String &s)
Construct an empty GriddedField3 with the given name.
GriddedField3 & operator= (Numeric n)
bool checksize () const final
Consistency check.
void checksize_strict () const final
Strict consistency check.
void resize (const GriddedField3 &gf)
Make this GriddedField3 the same size as the given one.
void resize (Index p, Index r, Index c)
Resize the data tensor.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
const Vector & get_numeric_grid (Index i) const
Get a numeric grid.
Vector & get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Tensor3 data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField3 &gf)
String metaErrorData (const GriddedField3 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 293 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField3() [1/2]
GriddedField3::GriddedField3 () inline
Construct an empty GriddedField3.
Definition at line 296 of file gridded_fields.h.
GriddedField3() [2/2]
GriddedField3::GriddedField3 (const String & s) inline
Construct an empty GriddedField3 with the given name.
Parameters
[in] s Name.
Definition at line 299 of file gridded_fields.h.
Member Function Documentation
checksize()
bool GriddedField3::checksize () const inline final virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 307 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), ConstTensor3View::ncols(), ConstTensor3View::npages(), and ConstTensor3View::nrows().
Referenced by atm_fields_compactAddSpecies(), atm_fields_compactCreateFromField(), and checksize_strict().
checksize_strict()
void GriddedField3::checksize_strict () const inline final virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 316 of file gridded_fields.h.
References ARTS_USER_ERROR_IF, and checksize().
Referenced by complex_n_interp(), and xml_read_from_stream().
operator=()
GriddedField3& GriddedField3::operator= (Numeric n) inline
Definition at line 301 of file gridded_fields.h.
References data.
resize() [1/2]
void GriddedField3::resize (const GriddedField3 & gf) inline
Make this GriddedField3 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 322 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Tensor3::resize().
Referenced by complex_refr_indexConstant(), complex_refr_indexIceMatzler06(), complex_refr_indexWaterLiebe93(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), GriddedFieldZToPRegrid(), and surface_complex_refr_indexFromGriddedField5().
resize() [2/2]
void GriddedField3::resize (Index p, Index r, Index c) inline
Resize the data tensor.
See also
Tensor3::resize
Definition at line 328 of file gridded_fields.h.
References c, data, and Tensor3::resize().
Friends And Related Function Documentation
metaErrorData
String metaErrorData (const GriddedField3 & gf) friend
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField3 & gf) friend
Member Data Documentation
data
Tensor3 GriddedField3::data
Definition at line 334 of file gridded_fields.h.
Referenced by atm_fields_compactAddSpecies(), atm_fields_compactCreateFromField(), AtmFieldsCalc(), checksize(), complex_n_interp(), complex_refr_indexConstant(), complex_refr_indexIceMatzler06(), complex_refr_indexWaterLiebe93(), FieldFromGriddedField(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), GriddedFieldZToPRegrid(), MagFieldsCalc(), operator<<(), operator=(), resize(), surface_complex_refr_indexFromGriddedField5(), WindFieldsCalc(), xml_read_from_stream(), xml_write_to_stream(), ybatchMetProfiles(), and ybatchMetProfilesClear().
The documentation for this class was generated from the following file:
gridded_fields.h