ARTS: ARTS::Var::Numeric Class Reference
ARTS::Var::Numeric Class Reference
#include <autoarts.h>
Public Member Functions
Numeric () noexcept
Numeric (std::size_t i, void *x) noexcept
Numeric (const Group::Numeric &val) noexcept
~Numeric () noexcept
Group::Numeric & value () noexcept
const Group::Numeric & value () const noexcept
Numeric & operator= (const Group::Numeric &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Numeric * v
Friends
std::ostream & operator<< (std::ostream &os, const Numeric &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 3525 of file autoarts.h.
Constructor & Destructor Documentation
Numeric() [1/3]
ARTS::Var::Numeric::Numeric () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 3530 of file autoarts.h.
Numeric() [2/3]
ARTS::Var::Numeric::Numeric (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 3533 of file autoarts.h.
Numeric() [3/3]
ARTS::Var::Numeric::Numeric (const Group::Numeric & val) inline noexcept
Construct from Group::Numeric. Leaves islast() true and isnull() false
Definition at line 3536 of file autoarts.h.
~Numeric()
ARTS::Var::Numeric::~Numeric () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 3539 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Numeric::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 3557 of file autoarts.h.
References max, and p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoff(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetCutoff(), ARTS::Agenda::Method::abs_linesSetCutoffForMatch(), ARTS::Agenda::Method::abs_linesSetLinemixingLimit(), ARTS::Agenda::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_linesSetT0(), ARTS::Agenda::Method::abs_linesSetT0ForMatch(), ARTS::Agenda::Method::atm_fields_compactCleanup(), ARTS::Agenda::Method::backend_channel_responseFlat(), ARTS::Agenda::Method::batch_atm_fields_compactCleanup(), ARTS::Agenda::Method::cloudboxSetManually(), ARTS::Agenda::Method::cloudboxSetManuallyAltitude(), ARTS::Agenda::Method::complex_refr_indexConstant(), ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Agenda::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Agenda::Method::diameter_volume_equFromDiameter_max(), ARTS::Agenda::Method::doit_za_grid_optCalc(), ARTS::Method::Duration(), ARTS::Agenda::Method::Duration(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::geo_posWherePpathPassesZref(), ARTS::Agenda::Method::Ignore(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Agenda::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Agenda::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Method::jacobianFromTwoY(), ARTS::Agenda::Method::jacobianFromYbatch(), ARTS::Method::LocalTimeOffset(), ARTS::Agenda::Method::LocalTimeOffset(), ARTS::Agenda::Method::MatrixAddScalar(), ARTS::Agenda::Method::MatrixPlanck(), ARTS::Agenda::Method::MatrixScale(), ARTS::Agenda::Method::MatrixSetConstant(), ARTS::Agenda::Method::mc_antennaSetGaussian(), ARTS::Agenda::Method::mc_antennaSetGaussianByFWHM(), ARTS::Agenda::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::NumericAdd(), ARTS::Agenda::Method::NumericAdd(), ARTS::Method::NumericFromVector(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Agenda::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::Agenda::Method::NumericScale(), ARTS::Method::NumericSet(), ARTS::Agenda::Method::NumericSet(), ARTS::Agenda::Method::p_gridRefine(), ARTS::Agenda::Method::particle_fieldCleanup(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::refellipsoidForAzimuth(), ARTS::Agenda::Method::refellipsoidOrbitPlane(), ARTS::Agenda::Method::rte_losSet(), ARTS::Agenda::Method::rte_posSet(), ARTS::Agenda::Method::sensor_responseBackendFrequencySwitching(), ARTS::Agenda::Method::surfaceSemiSpecularBy3beams(), ARTS::Agenda::Method::surfaceSplitSpecularTo3beams(), ARTS::Agenda::Method::telsemAtlasLookup(), ARTS::Agenda::Method::Tensor3AddScalar(), ARTS::Agenda::Method::Tensor3Scale(), ARTS::Agenda::Method::Tensor3SetConstant(), ARTS::Agenda::Method::Tensor4AddScalar(), ARTS::Agenda::Method::Tensor4Scale(), ARTS::Agenda::Method::Tensor4SetConstant(), ARTS::Agenda::Method::Tensor5Scale(), ARTS::Agenda::Method::Tensor5SetConstant(), ARTS::Agenda::Method::Tensor6Scale(), ARTS::Agenda::Method::Tensor6SetConstant(), ARTS::Agenda::Method::Tensor7Scale(), ARTS::Agenda::Method::Tensor7SetConstant(), ARTS::Agenda::Method::time_gridOffset(), ARTS::Agenda::Method::timeOffset(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), ARTS::Method::Trapz(), ARTS::Agenda::Method::Trapz(), ARTS::Agenda::Method::VectorAddScalar(), ARTS::Agenda::Method::VectorLinSpace(), ARTS::Agenda::Method::VectorLogSpace(), ARTS::Agenda::Method::VectorNLinSpace(), ARTS::Agenda::Method::VectorNLogSpace(), ARTS::Agenda::Method::VectorPower(), ARTS::Agenda::Method::VectorScale(), ARTS::Agenda::Method::VectorSetConstant(), ARTS::Agenda::Method::vmr_fieldSetConstant(), ARTS::Agenda::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Agenda::Method::ySimpleSpectrometer(), and ~Numeric().
isnull()
bool ARTS::Var::Numeric::isnull () const inline noexcept
Return true if there is no data
Definition at line 3554 of file autoarts.h.
References v.
Referenced by ~Numeric().
name()
const Group::String& ARTS::Var::Numeric::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 3560 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy().
operator=()
Numeric& ARTS::Var::Numeric::operator= (const Group::Numeric & t) inline noexcept
Set value from Group::Numeric. Works when isnull() is false
Definition at line 3548 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Numeric::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 3551 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Agenda::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoff(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Agenda::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Agenda::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Agenda::Method::abs_linesSetCutoff(), ARTS::Agenda::Method::abs_linesSetCutoffForMatch(), ARTS::Agenda::Method::abs_linesSetLinemixingLimit(), ARTS::Agenda::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Agenda::Method::abs_linesSetT0(), ARTS::Agenda::Method::abs_linesSetT0ForMatch(), ARTS::Agenda::Method::atm_fields_compactCleanup(), ARTS::Agenda::Method::backend_channel_responseFlat(), ARTS::Agenda::Method::batch_atm_fields_compactCleanup(), ARTS::Agenda::Method::cloudboxSetManually(), ARTS::Agenda::Method::cloudboxSetManuallyAltitude(), ARTS::Agenda::Method::complex_refr_indexConstant(), ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Agenda::Method::diameter_volume_equFromDiameter_max(), ARTS::Agenda::Method::doit_za_grid_optCalc(), ARTS::Agenda::Method::Duration(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Agenda::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Agenda::Method::FrequencyFromWavelength(), ARTS::Agenda::Method::geo_posWherePpathPassesZref(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::InterpAtmFieldToPosition(), ARTS::Agenda::Method::InterpGriddedField2ToPosition(), ARTS::Agenda::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Method::jacobianFromTwoY(), ARTS::Agenda::Method::jacobianFromYbatch(), ARTS::Agenda::Method::LocalTimeOffset(), ARTS::Agenda::Method::MatrixAddScalar(), ARTS::Agenda::Method::MatrixPlanck(), ARTS::Agenda::Method::MatrixScale(), ARTS::Agenda::Method::MatrixSetConstant(), ARTS::Agenda::Method::mc_antennaSetGaussian(), ARTS::Agenda::Method::mc_antennaSetGaussianByFWHM(), ARTS::Agenda::Method::nlte_fieldRescalePopulationLevels(), ARTS::Agenda::Method::NumericAdd(), ARTS::Agenda::Method::NumericFromVector(), ARTS::Agenda::Method::NumericInvScale(), ARTS::Agenda::Method::NumericScale(), ARTS::Agenda::Method::NumericSet(), ARTS::Agenda::Method::p_gridRefine(), ARTS::Agenda::Method::particle_fieldCleanup(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::refellipsoidForAzimuth(), ARTS::Agenda::Method::refellipsoidOrbitPlane(), ARTS::Agenda::Method::rte_losSet(), ARTS::Agenda::Method::rte_posSet(), ARTS::Agenda::Method::sensor_responseBackendFrequencySwitching(), ARTS::Agenda::Method::surfaceSemiSpecularBy3beams(), ARTS::Agenda::Method::surfaceSplitSpecularTo3beams(), ARTS::Agenda::Method::telsemAtlasLookup(), ARTS::Agenda::Method::Tensor3AddScalar(), ARTS::Agenda::Method::Tensor3Scale(), ARTS::Agenda::Method::Tensor3SetConstant(), ARTS::Agenda::Method::Tensor4AddScalar(), ARTS::Agenda::Method::Tensor4Scale(), ARTS::Agenda::Method::Tensor4SetConstant(), ARTS::Agenda::Method::Tensor5Scale(), ARTS::Agenda::Method::Tensor5SetConstant(), ARTS::Agenda::Method::Tensor6Scale(), ARTS::Agenda::Method::Tensor6SetConstant(), ARTS::Agenda::Method::Tensor7Scale(), ARTS::Agenda::Method::Tensor7SetConstant(), ARTS::Agenda::Method::time_gridOffset(), ARTS::Agenda::Method::timeOffset(), ARTS::Agenda::Method::Touch(), ARTS::Agenda::Method::Trapz(), ARTS::Agenda::Method::VectorAddScalar(), ARTS::Agenda::Method::VectorLinSpace(), ARTS::Agenda::Method::VectorLogSpace(), ARTS::Agenda::Method::VectorNLinSpace(), ARTS::Agenda::Method::VectorNLogSpace(), ARTS::Agenda::Method::VectorPower(), ARTS::Agenda::Method::VectorScale(), ARTS::Agenda::Method::VectorSetConstant(), ARTS::Agenda::Method::vmr_fieldSetConstant(), ARTS::Agenda::Method::WriteBuiltinPartitionFunctionsXML(), and ARTS::Agenda::Method::ySimpleSpectrometer().
value() [1/2]
const Group::Numeric& ARTS::Var::Numeric::value () const inline noexcept
Get value const-ref as Group::Numeric. Works when isnull() is false
Definition at line 3545 of file autoarts.h.
References v.
value() [2/2]
Group::Numeric& ARTS::Var::Numeric::value () inline noexcept
Get value ref as Group::Numeric. Works when isnull() is false
Definition at line 3542 of file autoarts.h.
References v.
Referenced by ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetCutoff(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetT0(), ARTS::Method::abs_linesSetT0ForMatch(), ARTS::Method::atm_fields_compactCleanup(), ARTS::Method::backend_channel_responseFlat(), ARTS::Method::batch_atm_fields_compactCleanup(), ARTS::Method::cloudboxSetManually(), ARTS::Method::cloudboxSetManuallyAltitude(), ARTS::Method::complex_refr_indexConstant(), ARTS::Method::Copy(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::doit_za_grid_optCalc(), ARTS::Method::Duration(), ARTS::Method::Extract(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Method::geo_posWherePpathPassesZref(), ARTS::Method::Ignore(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::LocalTimeOffset(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::Method::MatrixSetConstant(), ARTS::Method::mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussianByFWHM(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::NumericAdd(), ARTS::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::Method::NumericSet(), ARTS::Agenda::Method::NumericSet(), operator=(), ARTS::Method::p_gridRefine(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::Reduce(), ARTS::Method::refellipsoidForAzimuth(), ARTS::Method::refellipsoidOrbitPlane(), ARTS::Method::rte_losSet(), ARTS::Method::rte_posSet(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::time_gridOffset(), ARTS::Method::timeOffset(), ARTS::Method::Touch(), ARTS::Method::Trapz(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorPower(), ARTS::Method::VectorScale(), ARTS::Method::VectorSetConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::WriteBuiltinPartitionFunctionsXML(), and ARTS::Method::ySimpleSpectrometer().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Numeric & var) friend
Output to stream of internal variable
Definition at line 3563 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Numeric::p private
Definition at line 3526 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Numeric* ARTS::Var::Numeric::v private
Definition at line 3527 of file autoarts.h.
Referenced by isnull(), value(), and ~Numeric().
The documentation for this class was generated from the following file:
autoarts.h