ARTS: ARTS::Var::WorkspaceArrayOfPpath Class Reference
ARTS::Var::WorkspaceArrayOfPpath Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfPpath () noexcept
WorkspaceArrayOfPpath (std::size_t i, void *x) noexcept
~WorkspaceArrayOfPpath () noexcept
WorkspaceArrayOfPpath (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfPpath & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfPpath
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 638 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfPpath::type = Group::ArrayOfPpath private
Definition at line 639 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfPpath() [1/3]
ARTS::Var::WorkspaceArrayOfPpath::WorkspaceArrayOfPpath () inline noexcept
Definition at line 643 of file autoarts.h.
WorkspaceArrayOfPpath() [2/3]
ARTS::Var::WorkspaceArrayOfPpath::WorkspaceArrayOfPpath (std::size_t i, void * x) inline noexcept
Definition at line 644 of file autoarts.h.
~WorkspaceArrayOfPpath()
ARTS::Var::WorkspaceArrayOfPpath::~WorkspaceArrayOfPpath () inline noexcept
Definition at line 645 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfPpath() [3/3]
ARTS::Var::WorkspaceArrayOfPpath::WorkspaceArrayOfPpath (const type & val) inline noexcept
Definition at line 646 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfPpath::islast () const inline noexcept
Definition at line 652 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfPpath().
isnull()
bool ARTS::Var::WorkspaceArrayOfPpath::isnull () const inline noexcept
Definition at line 651 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfPpath().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfPpath::name () const inline noexcept
Definition at line 653 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfPpath& ARTS::Var::WorkspaceArrayOfPpath::operator= (const type & t) inline noexcept
Definition at line 649 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfPpath::pos () const inline noexcept
Definition at line 650 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfPpath::value () const inline noexcept
Definition at line 648 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfPpath::value () inline noexcept
Definition at line 647 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfPpath::p private
Definition at line 640 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfPpath::v private
Definition at line 641 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfPpath().
The documentation for this class was generated from the following file:
autoarts.h