ARTS: SpeciesAuxData Class Reference
SpeciesAuxData Class Reference
Auxiliary data for isotopologues.
#include <absorption.h>
Public Types
enum AuxType {
AT_NONE , AT_ISOTOPOLOGUE_RATIO , AT_ISOTOPOLOGUE_QUANTUM , AT_PARTITIONFUNCTION_TFIELD ,
AT_PARTITIONFUNCTION_COEFF , AT_PARTITIONFUNCTION_COEFF_VIBROT , AT_FINAL_ENTRY
}
typedef Array< Array< AuxType > > ArrayOfArrayOfAuxType
typedef Array< GriddedField1 > AuxData
typedef Array< Array< AuxData > > ArrayOfArrayOfAuxData
Public Member Functions
SpeciesAuxData ()
Default constructor.
void InitFromSpeciesData ()
Index nspecies () const
Returns number of species.
Index nisotopologues (const Index species) const
Returns number of isotopologues for a certain species.
const ArrayOfGriddedField1 & getParam (const Index species, const Index isotopologue) const
Return a constant reference to the parameters.
Numeric getIsotopologueRatio (const SpeciesTag &st) const
Returns mparams[st.Species()][st.Isotopologue()][0].data[0] if st.Isotopologue() > 0, else 1.
Numeric getIsotopologueRatio (const QuantumIdentifier &qid) const
Returns mparams[qid.Species()][qid.Isotopologue()][0].data[0].
const ArrayOfGriddedField1 & getParam (const QuantumIdentifier &qid) const
Return a constant reference to the parameters.
String getTypeString (const Index species, const Index isotopologue) const
Return a parameter type as string.
void setParam (const Index species, const Index isotopologue, const AuxType auxtype, const ArrayOfGriddedField1 &auxdata)
Set parameter.
void setParam (const String &artstag, const String &auxtype, const ArrayOfGriddedField1 &auxdata)
Set parameter by ARTS tag.
const AuxType & getParamType (const Index species, const Index isotopologue) const
Return a constant reference to the parameter types.
const AuxType & getParamType (const QuantumIdentifier &qid) const
Return a constant reference to the parameter types.
bool ReadFromStream (String &artsid, istream &is, Index nparams, const Verbosity &verbosity)
Read parameters from input stream (only for version 1 format).
ArrayOfGriddedField1 & Data (const Index species, const Index isotopologue)
Returns value for one isotopologue.
Index setParamType (const Index species, const Index isotopologue, Index type)
Sets type for one isotopologue if type is valid (returns 0 if valid)
bool validIndex (Index species, Index isotopologue) const
Returns true if species and isotopologue are valid.
Private Attributes
ArrayOfArrayOfAuxData mparams
ArrayOfArrayOfAuxType mparam_type
Detailed Description
Auxiliary data for isotopologues.
Definition at line 199 of file absorption.h.
Member Typedef Documentation
ArrayOfArrayOfAuxData
typedef Array<Array<AuxData> > SpeciesAuxData::ArrayOfArrayOfAuxData
Definition at line 213 of file absorption.h.
ArrayOfArrayOfAuxType
typedef Array<Array<AuxType> > SpeciesAuxData::ArrayOfArrayOfAuxType
Definition at line 211 of file absorption.h.
AuxData
typedef Array<GriddedField1> SpeciesAuxData::AuxData
Definition at line 212 of file absorption.h.
Member Enumeration Documentation
AuxType
enum SpeciesAuxData::AuxType
Enumerator
AT_NONE
AT_ISOTOPOLOGUE_RATIO
AT_ISOTOPOLOGUE_QUANTUM
AT_PARTITIONFUNCTION_TFIELD
AT_PARTITIONFUNCTION_COEFF
AT_PARTITIONFUNCTION_COEFF_VIBROT
AT_FINAL_ENTRY
Definition at line 201 of file absorption.h.
Constructor & Destructor Documentation
SpeciesAuxData()
SpeciesAuxData::SpeciesAuxData () inline
Default constructor.
Definition at line 216 of file absorption.h.
Member Function Documentation
Data()
ArrayOfGriddedField1& SpeciesAuxData::Data (const Index species, const Index isotopologue) inline
Returns value for one isotopologue.
Definition at line 275 of file absorption.h.
References mparams.
getIsotopologueRatio() [1/2]
Numeric SpeciesAuxData::getIsotopologueRatio (const QuantumIdentifier & qid) const
Returns mparams[qid.Species()][qid.Isotopologue()][0].data[0].
Definition at line 154 of file absorption.cc.
References getParam(), QuantumIdentifier::Isotopologue(), and QuantumIdentifier::Species().
getIsotopologueRatio() [2/2]
Numeric SpeciesAuxData::getIsotopologueRatio (const SpeciesTag & st) const
Returns mparams[st.Species()][st.Isotopologue()][0].data[0] if st.Isotopologue() > 0, else 1.
Definition at line 147 of file absorption.cc.
References getParam(), SpeciesTag::Isotopologue(), and SpeciesTag::Species().
getParam() [1/2]
const ArrayOfGriddedField1 & SpeciesAuxData::getParam (const Index species, const Index isotopologue) const
Return a constant reference to the parameters.
Definition at line 142 of file absorption.cc.
References mparams.
Referenced by checkIsotopologueRatios(), getIsotopologueRatio(), getParam(), operator<<(), and xml_write_to_stream().
getParam() [2/2]
const ArrayOfGriddedField1& SpeciesAuxData::getParam (const QuantumIdentifier & qid) const inline
Return a constant reference to the parameters.
Definition at line 239 of file absorption.h.
References getParam(), QuantumIdentifier::Isotopologue(), and QuantumIdentifier::Species().
getParamType() [1/2]
const AuxType& SpeciesAuxData::getParamType (const Index species, const Index isotopologue) const inline
Return a constant reference to the parameter types.
Definition at line 258 of file absorption.h.
References mparam_type.
Referenced by getParamType().
getParamType() [2/2]
const AuxType& SpeciesAuxData::getParamType (const QuantumIdentifier & qid) const inline
Return a constant reference to the parameter types.
Definition at line 264 of file absorption.h.
References getParamType(), QuantumIdentifier::Isotopologue(), and QuantumIdentifier::Species().
getTypeString()
String SpeciesAuxData::getTypeString (const Index species, const Index isotopologue) const
Return a parameter type as string.
Definition at line 158 of file absorption.cc.
References ARTS_ASSERT, AT_FINAL_ENTRY, and mparam_type.
Referenced by operator<<(), and xml_write_to_stream().
InitFromSpeciesData()
void SpeciesAuxData::InitFromSpeciesData ()
Definition at line 59 of file absorption.cc.
References AT_NONE, iso(), mparam_type, mparams, and global_data::species_data.
Referenced by fillSpeciesAuxDataWithIsotopologueRatiosFromSpeciesData(), fillSpeciesAuxDataWithPartitionFunctionsFromSpeciesData(), and xml_read_from_stream().
nisotopologues()
Index SpeciesAuxData::nisotopologues (const Index species) const inline
Returns number of isotopologues for a certain species.
Definition at line 224 of file absorption.h.
References mparams, and Array< base >::nelem().
Referenced by checkIsotopologueRatios(), checkPartitionFunctions(), operator<<(), and xml_write_to_stream().
nspecies()
Index SpeciesAuxData::nspecies () const inline
Returns number of species.
Definition at line 221 of file absorption.h.
References mparams, and Array< base >::nelem().
Referenced by checkIsotopologueRatios(), checkPartitionFunctions(), operator<<(), and xml_write_to_stream().
ReadFromStream()
bool SpeciesAuxData::ReadFromStream (String & artsid, istream & is, Index nparams, const Verbosity & verbosity)
Read parameters from input stream (only for version 1 format).
Definition at line 164 of file absorption.cc.
References ARTS_USER_ERROR, ARTS_USER_ERROR_IF, c, CREATE_OUT3, extract(), SpeciesRecord::Isotopologue(), mparams, SpeciesRecord::Name(), my_basic_string< charT >::nelem(), Absorption::nelem(), nlinspace(), ConstVectorView::size(), global_data::species_data, and SpecIsoMap::Speciesindex().
Referenced by xml_read_from_stream().
setParam() [1/2]
void SpeciesAuxData::setParam (const Index species, const Index isotopologue, const AuxType auxtype, const ArrayOfGriddedField1 & auxdata)
Set parameter.
Definition at line 76 of file absorption.cc.
References mparam_type, and mparams.
Referenced by fillSpeciesAuxDataWithIsotopologueRatiosFromSpeciesData(), and fillSpeciesAuxDataWithPartitionFunctionsFromSpeciesData().
setParam() [2/2]
void SpeciesAuxData::setParam (const String & artstag, const String & auxtype, const ArrayOfGriddedField1 & auxdata)
Set parameter by ARTS tag.
Definition at line 84 of file absorption.cc.
References ARTS_USER_ERROR_IF, AT_FINAL_ENTRY, SpeciesRecord::Isotopologue(), SpeciesRecord::Name(), Absorption::nelem(), global_data::species_data, and SpecIsoMap::Speciesindex().
setParamType()
Index SpeciesAuxData::setParamType (const Index species, const Index isotopologue, Index type) inline
Sets type for one isotopologue if type is valid (returns 0 if valid)
Definition at line 278 of file absorption.h.
References AT_FINAL_ENTRY, AT_ISOTOPOLOGUE_QUANTUM, AT_ISOTOPOLOGUE_RATIO, AT_NONE, AT_PARTITIONFUNCTION_COEFF, AT_PARTITIONFUNCTION_COEFF_VIBROT, AT_PARTITIONFUNCTION_TFIELD, mparam_type, Hitran::type, and ARTS::Var::y().
validIndex()
bool SpeciesAuxData::validIndex (Index species, Index isotopologue) const inline
Returns true if species and isotopologue are valid.
Definition at line 289 of file absorption.h.
References mparam_type, mparams, and Array< base >::nelem().
Member Data Documentation
mparam_type
ArrayOfArrayOfAuxType SpeciesAuxData::mparam_type private
Definition at line 300 of file absorption.h.
Referenced by getParamType(), getTypeString(), InitFromSpeciesData(), setParam(), setParamType(), and validIndex().
mparams
ArrayOfArrayOfAuxData SpeciesAuxData::mparams private
Definition at line 299 of file absorption.h.
Referenced by Data(), getParam(), InitFromSpeciesData(), nisotopologues(), nspecies(), ReadFromStream(), setParam(), and validIndex().
The documentation for this class was generated from the following files:
absorption.h
absorption.cc