ARTS: ARTS::Var::WorkspaceArrayOfAgenda Class Reference
ARTS::Var::WorkspaceArrayOfAgenda Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceArrayOfAgenda () noexcept
WorkspaceArrayOfAgenda (std::size_t i, void *x) noexcept
~WorkspaceArrayOfAgenda () noexcept
WorkspaceArrayOfAgenda (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceArrayOfAgenda & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::ArrayOfAgenda
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 170 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceArrayOfAgenda::type = Group::ArrayOfAgenda private
Definition at line 171 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceArrayOfAgenda() [1/3]
ARTS::Var::WorkspaceArrayOfAgenda::WorkspaceArrayOfAgenda () inline noexcept
Definition at line 175 of file autoarts.h.
WorkspaceArrayOfAgenda() [2/3]
ARTS::Var::WorkspaceArrayOfAgenda::WorkspaceArrayOfAgenda (std::size_t i, void * x) inline noexcept
Definition at line 176 of file autoarts.h.
~WorkspaceArrayOfAgenda()
ARTS::Var::WorkspaceArrayOfAgenda::~WorkspaceArrayOfAgenda () inline noexcept
Definition at line 177 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceArrayOfAgenda() [3/3]
ARTS::Var::WorkspaceArrayOfAgenda::WorkspaceArrayOfAgenda (const type & val) inline noexcept
Definition at line 178 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceArrayOfAgenda::islast () const inline noexcept
Definition at line 184 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), ARTS::Method::Select(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceArrayOfAgenda().
isnull()
bool ARTS::Var::WorkspaceArrayOfAgenda::isnull () const inline noexcept
Definition at line 183 of file autoarts.h.
References v.
Referenced by ~WorkspaceArrayOfAgenda().
name()
const Group::String& ARTS::Var::WorkspaceArrayOfAgenda::name () const inline noexcept
Definition at line 185 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceArrayOfAgenda& ARTS::Var::WorkspaceArrayOfAgenda::operator= (const type & t) inline noexcept
Definition at line 181 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceArrayOfAgenda::pos () const inline noexcept
Definition at line 182 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::IndexSetToLast(), ARTS::AgendaMethod::nelemGet(), ARTS::AgendaMethod::Select(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceArrayOfAgenda::value () const inline noexcept
Definition at line 180 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceArrayOfAgenda::value () inline noexcept
Definition at line 179 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), operator=(), ARTS::Method::Select(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceArrayOfAgenda::p private
Definition at line 172 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceArrayOfAgenda::v private
Definition at line 173 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceArrayOfAgenda().
The documentation for this class was generated from the following file:
autoarts.h