ARTS: ARTS::Var::WorkspaceCovarianceMatrix Class Reference
ARTS::Var::WorkspaceCovarianceMatrix Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceCovarianceMatrix () noexcept
WorkspaceCovarianceMatrix (std::size_t i, void *x) noexcept
~WorkspaceCovarianceMatrix () noexcept
WorkspaceCovarianceMatrix (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceCovarianceMatrix & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::CovarianceMatrix
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1016 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceCovarianceMatrix::type = Group::CovarianceMatrix private
Definition at line 1017 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceCovarianceMatrix() [1/3]
ARTS::Var::WorkspaceCovarianceMatrix::WorkspaceCovarianceMatrix () inline noexcept
Definition at line 1021 of file autoarts.h.
WorkspaceCovarianceMatrix() [2/3]
ARTS::Var::WorkspaceCovarianceMatrix::WorkspaceCovarianceMatrix (std::size_t i, void * x) inline noexcept
Definition at line 1022 of file autoarts.h.
~WorkspaceCovarianceMatrix()
ARTS::Var::WorkspaceCovarianceMatrix::~WorkspaceCovarianceMatrix () inline noexcept
Definition at line 1023 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceCovarianceMatrix() [3/3]
ARTS::Var::WorkspaceCovarianceMatrix::WorkspaceCovarianceMatrix (const type & val) inline noexcept
Definition at line 1024 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceCovarianceMatrix::islast () const inline noexcept
Definition at line 1030 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::MatrixFromCovarianceMatrix(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceCovarianceMatrix().
isnull()
bool ARTS::Var::WorkspaceCovarianceMatrix::isnull () const inline noexcept
Definition at line 1029 of file autoarts.h.
References v.
Referenced by ~WorkspaceCovarianceMatrix().
name()
const Group::String& ARTS::Var::WorkspaceCovarianceMatrix::name () const inline noexcept
Definition at line 1031 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceCovarianceMatrix& ARTS::Var::WorkspaceCovarianceMatrix::operator= (const type & t) inline noexcept
Definition at line 1027 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceCovarianceMatrix::pos () const inline noexcept
Definition at line 1028 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::covmat_seSet(), ARTS::AgendaMethod::covmat_sxSet(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::MatrixFromCovarianceMatrix(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceCovarianceMatrix::value () const inline noexcept
Definition at line 1026 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceCovarianceMatrix::value () inline noexcept
Definition at line 1025 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::Delete(), ARTS::Method::Ignore(), ARTS::Method::MatrixFromCovarianceMatrix(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceCovarianceMatrix::p private
Definition at line 1018 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceCovarianceMatrix::v private
Definition at line 1019 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceCovarianceMatrix().
The documentation for this class was generated from the following file:
autoarts.h