ARTS: ARTS::Var::WorkspaceRadiationVector Class Reference
ARTS::Var::WorkspaceRadiationVector Class Reference
#include <autoarts.h>
Public Member Functions
WorkspaceRadiationVector () noexcept
WorkspaceRadiationVector (std::size_t i, void *x) noexcept
~WorkspaceRadiationVector () noexcept
WorkspaceRadiationVector (const type &val) noexcept
type & value () noexcept
const type & value () const noexcept
WorkspaceRadiationVector & operator= (const type &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Types
using type = Group::RadiationVector
Private Attributes
std::size_t p
type * v
Detailed Description
Definition at line 1340 of file autoarts.h.
Member Typedef Documentation
type
using ARTS::Var::WorkspaceRadiationVector::type = Group::RadiationVector private
Definition at line 1341 of file autoarts.h.
Constructor & Destructor Documentation
WorkspaceRadiationVector() [1/3]
ARTS::Var::WorkspaceRadiationVector::WorkspaceRadiationVector () inline noexcept
Definition at line 1345 of file autoarts.h.
WorkspaceRadiationVector() [2/3]
ARTS::Var::WorkspaceRadiationVector::WorkspaceRadiationVector (std::size_t i, void * x) inline noexcept
Definition at line 1346 of file autoarts.h.
~WorkspaceRadiationVector()
ARTS::Var::WorkspaceRadiationVector::~WorkspaceRadiationVector () inline noexcept
Definition at line 1347 of file autoarts.h.
References islast(), isnull(), and v.
WorkspaceRadiationVector() [3/3]
ARTS::Var::WorkspaceRadiationVector::WorkspaceRadiationVector (const type & val) inline noexcept
Definition at line 1348 of file autoarts.h.
Member Function Documentation
islast()
bool ARTS::Var::WorkspaceRadiationVector::islast () const inline noexcept
Definition at line 1354 of file autoarts.h.
References max, and p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::Method::Copy(), ARTS::AgendaMethod::Delete(), ARTS::Method::Delete(), ARTS::AgendaMethod::Ignore(), ARTS::AgendaMethod::Touch(), ARTS::Method::Touch(), and ~WorkspaceRadiationVector().
isnull()
bool ARTS::Var::WorkspaceRadiationVector::isnull () const inline noexcept
Definition at line 1353 of file autoarts.h.
References v.
Referenced by ~WorkspaceRadiationVector().
name()
const Group::String& ARTS::Var::WorkspaceRadiationVector::name () const inline noexcept
Definition at line 1355 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::Delete().
operator=()
WorkspaceRadiationVector& ARTS::Var::WorkspaceRadiationVector::operator= (const type & t) inline noexcept
Definition at line 1351 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::WorkspaceRadiationVector::pos () const inline noexcept
Definition at line 1352 of file autoarts.h.
References p.
Referenced by ARTS::AgendaMethod::Copy(), ARTS::AgendaMethod::Delete(), ARTS::AgendaMethod::Ignore(), and ARTS::AgendaMethod::Touch().
value() [1/2]
const type& ARTS::Var::WorkspaceRadiationVector::value () const inline noexcept
Definition at line 1350 of file autoarts.h.
References v.
value() [2/2]
type& ARTS::Var::WorkspaceRadiationVector::value () inline noexcept
Definition at line 1349 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Delete(), ARTS::Method::Ignore(), operator=(), and ARTS::Method::Touch().
Member Data Documentation
p
std::size_t ARTS::Var::WorkspaceRadiationVector::p private
Definition at line 1342 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
type* ARTS::Var::WorkspaceRadiationVector::v private
Definition at line 1343 of file autoarts.h.
Referenced by isnull(), value(), and ~WorkspaceRadiationVector().
The documentation for this class was generated from the following file:
autoarts.h