ARTS: GriddedField5 Class Reference
GriddedField5 Class Reference final
#include <gridded_fields.h>
Public Member Functions
GriddedField5 ()
Construct an empty GriddedField5.
GriddedField5 (const String &s)
Construct an empty GriddedField5 with the given name.
bool checksize () const final
Consistency check.
void checksize_strict () const final
Strict consistency check.
void resize (const GriddedField5 &gf)
Make this GriddedField5 the same size as the given one.
void resize (Index s, Index b, Index p, Index r, Index c)
Resize the data tensor.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
const Vector & get_numeric_grid (Index i) const
Get a numeric grid.
Vector & get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Tensor5 data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField5 &gf)
String metaErrorData (const GriddedField5 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 380 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField5() [1/2]
GriddedField5::GriddedField5 () inline
Construct an empty GriddedField5.
Definition at line 383 of file gridded_fields.h.
GriddedField5() [2/2]
GriddedField5::GriddedField5 (const String & s) inline
Construct an empty GriddedField5 with the given name.
Parameters
[in] s Name.
Definition at line 386 of file gridded_fields.h.
Member Function Documentation
checksize()
bool GriddedField5::checksize () const inline final virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 388 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
Referenced by checksize_strict().
checksize_strict()
void GriddedField5::checksize_strict () const inline final virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 401 of file gridded_fields.h.
References ARTS_USER_ERROR_IF, and checksize().
Referenced by surface_complex_refr_indexFromGriddedField5(), and xml_read_from_stream().
resize() [1/2]
void GriddedField5::resize (const GriddedField5 & gf) inline
Make this GriddedField5 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 407 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Tensor5::resize().
resize() [2/2]
void GriddedField5::resize (Index s, Index b, Index p, Index r, Index c) inline
Resize the data tensor.
See also
Tensor5::resize
Definition at line 417 of file gridded_fields.h.
References b, c, data, and Tensor5::resize().
Friends And Related Function Documentation
metaErrorData
String metaErrorData (const GriddedField5 & gf) friend
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField5 & gf) friend
Member Data Documentation
data
Tensor5 GriddedField5::data
Definition at line 425 of file gridded_fields.h.
Referenced by checksize(), operator<<(), resize(), surface_complex_refr_indexFromGriddedField5(), xml_read_from_stream(), and xml_write_to_stream().
The documentation for this class was generated from the following file:
gridded_fields.h