ARTS: ARTS::Var::Tensor3 Class Reference
ARTS::Var::Tensor3 Class Reference
#include <autoarts.h>
Public Member Functions
Tensor3 () noexcept
Tensor3 (std::size_t i, void *x) noexcept
Tensor3 (const Group::Tensor3 &val) noexcept
~Tensor3 () noexcept
Group::Tensor3 & value () noexcept
const Group::Tensor3 & value () const noexcept
Tensor3 & operator= (const Group::Tensor3 &t) noexcept
std::size_t pos () const noexcept
bool isnull () const noexcept
bool islast () const noexcept
const Group::String & name () const noexcept
Private Attributes
std::size_t p
Group::Tensor3 * v
Friends
std::ostream & operator<< (std::ostream &os, const Tensor3 &var)
Detailed Description
Workspace Variable class. Used as default input to many Method and AgendaMethod. Note that it is not recommended to manually create this class as many methods makes distinct assumptions about the states that this class are allowed to be in
Definition at line 4033 of file autoarts.h.
Constructor & Destructor Documentation
Tensor3() [1/3]
ARTS::Var::Tensor3::Tensor3 () inline noexcept
Default construct. DO NOT USE MANUALLY. Leaves islast() true and isnull() true
Definition at line 4038 of file autoarts.h.
Tensor3() [2/3]
ARTS::Var::Tensor3::Tensor3 (std::size_t i, void * x) inline noexcept
Construct from existing Workspace. DO NOT USE MANUALLY. Leaves islast() false and isnull() false
Definition at line 4041 of file autoarts.h.
Tensor3() [3/3]
ARTS::Var::Tensor3::Tensor3 (const Group::Tensor3 & val) inline noexcept
Construct from Group::Tensor3. Leaves islast() true and isnull() false
Definition at line 4044 of file autoarts.h.
~Tensor3()
ARTS::Var::Tensor3::~Tensor3 () inline noexcept
Delete data only when islast() is true and isnull() is false
Definition at line 4047 of file autoarts.h.
References islast(), isnull(), and v.
Member Function Documentation
islast()
bool ARTS::Var::Tensor3::islast () const inline noexcept
Return true if data is not in the Workspace
Definition at line 4065 of file autoarts.h.
References max, and p.
Referenced by ARTS::Method::Copy(), ARTS::Agenda::Method::Copy(), ARTS::Method::Extract(), ARTS::Agenda::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::InterpAtmFieldToPosition(), ARTS::Agenda::Method::MatrixExtractFromTensor3(), ARTS::Method::ReadNetCDF(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Agenda::Method::Reduce(), ARTS::Method::Tensor3AddScalar(), ARTS::Agenda::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3FromVector(), ARTS::Agenda::Method::Tensor3FromVector(), ARTS::Method::Tensor3Scale(), ARTS::Agenda::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Agenda::Method::Tensor3SetConstant(), ARTS::Method::Touch(), ARTS::Agenda::Method::Touch(), and ~Tensor3().
isnull()
bool ARTS::Var::Tensor3::isnull () const inline noexcept
Return true if there is no data
Definition at line 4062 of file autoarts.h.
References v.
Referenced by ~Tensor3().
name()
const Group::String& ARTS::Var::Tensor3::name () const inline noexcept
Name of variable. Must be in the workspace
Definition at line 4068 of file autoarts.h.
References p, and Workspace::wsv_data.
Referenced by ARTS::Method::Copy(), and ARTS::Method::ReadNetCDF().
operator=()
Tensor3& ARTS::Var::Tensor3::operator= (const Group::Tensor3 & t) inline noexcept
Set value from Group::Tensor3. Works when isnull() is false
Definition at line 4056 of file autoarts.h.
References value().
pos()
std::size_t ARTS::Var::Tensor3::pos () const inline noexcept
Return the position of the variable in the Workspace
Definition at line 4059 of file autoarts.h.
References p.
Referenced by ARTS::Agenda::Method::Copy(), ARTS::Agenda::Method::Extract(), ARTS::Agenda::Method::FieldFromGriddedField(), ARTS::Agenda::Method::Flatten(), ARTS::Agenda::Method::Ignore(), ARTS::Agenda::Method::InterpAtmFieldToPosition(), ARTS::Agenda::Method::MatrixExtractFromTensor3(), ARTS::Agenda::Method::ReadNetCDF(), ARTS::Agenda::Method::Reduce(), ARTS::Agenda::Method::Tensor3AddScalar(), ARTS::Agenda::Method::Tensor3ExtractFromTensor4(), ARTS::Agenda::Method::Tensor3FromVector(), ARTS::Agenda::Method::Tensor3Scale(), ARTS::Agenda::Method::Tensor3SetConstant(), and ARTS::Agenda::Method::Touch().
value() [1/2]
const Group::Tensor3& ARTS::Var::Tensor3::value () const inline noexcept
Get value const-ref as Group::Tensor3. Works when isnull() is false
Definition at line 4053 of file autoarts.h.
References v.
value() [2/2]
Group::Tensor3& ARTS::Var::Tensor3::value () inline noexcept
Get value ref as Group::Tensor3. Works when isnull() is false
Definition at line 4050 of file autoarts.h.
References v.
Referenced by ARTS::Method::Copy(), ARTS::Method::Extract(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::Flatten(), ARTS::Method::Ignore(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::MatrixExtractFromTensor3(), operator=(), ARTS::Method::ReadNetCDF(), ARTS::Method::Reduce(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3FromVector(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Touch(), and ARTS::Method::VectorZtanToZaRefr1D().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Tensor3 & var) friend
Output to stream of internal variable
Definition at line 4071 of file autoarts.h.
Member Data Documentation
p
std::size_t ARTS::Var::Tensor3::p private
Definition at line 4034 of file autoarts.h.
Referenced by islast(), name(), and pos().
v
Group::Tensor3* ARTS::Var::Tensor3::v private
Definition at line 4035 of file autoarts.h.
Referenced by isnull(), value(), and ~Tensor3().
The documentation for this class was generated from the following file:
autoarts.h