ARTS: complex.h File Reference
complex.h File Reference
A class implementing complex numbers for ARTS.
#include <complex>
#include "lapack.h"
#include "matpackI.h"
Classes
class ComplexIterator1D
The iterator class for sub vectors.
class ConstComplexIterator1D
The constant iterator class for sub vectors.
class ConstComplexVectorView
A constant view of a ComplexVector.
class ComplexVectorView
The ComplexVectorView class.
class ComplexIterator2D
The row iterator class for sub matrices.
class ConstComplexIterator2D
The const row iterator class for sub matrices.
class ComplexVector
The ComplexVector class.
class ConstComplexMatrixView
A constant view of a ComplexMatrix.
class ComplexMatrixView
The ComplexMatrixView class.
class ComplexMatrix
The ComplexMatrix class.
Macros
#define a1 c.real()
#define b1 c.imag()
#define a2 z.real()
#define b2 z.imag()
#define _complex_operations_(T)
Typedefs
typedef std::complex< Numeric > Complex
typedef Eigen::Matrix< Complex, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor > ComplexMatrixType
typedef Eigen::Map< ComplexMatrixType, 0, StrideType > ComplexMatrixViewMap
typedef Eigen::Map< const ComplexMatrixType, 0, StrideType > ConstComplexMatrixViewMap
typedef Array< ComplexVector > ArrayOfComplexVector
typedef Array< ComplexMatrix > ArrayOfComplexMatrix
Functions
Numeric & real_val (Complex &c) noexcept
Return a reference to the real value of c.
Numeric & imag_val (Complex &c) noexcept
Return a reference to the imaginary value of c.
const Numeric & real_val (const Complex &c) noexcept
Return a const reference to the real value of c.
const Numeric & imag_val (const Complex &c) noexcept
Return a const reference to the imaginary value of c.
std::complex< float > operator+ (const double &d, const std::complex< float > &c)
std::complex< float > operator* (const double &d, const std::complex< float > &c)
std::complex< float > operator+ (const std::complex< float > &c, const double &d)
std::complex< float > operator* (const std::complex< float > &c, const double &d)
constexpr Numeric abs2 (Complex c) noexcept
squared magnitude of c
constexpr Complex conj (Complex c) noexcept
the conjugate of c
constexpr Numeric real (Complex c) noexcept
real
constexpr Numeric imag (Complex c) noexcept
imag
constexpr Complex operator+ (Complex c, Numeric n) noexcept
constexpr Complex operator- (Complex c, Numeric n) noexcept
constexpr Complex operator* (Complex c, Numeric n) noexcept
constexpr Complex operator/ (Complex c, Numeric n) noexcept
constexpr Complex operator+ (Numeric n, Complex c) noexcept
constexpr Complex operator- (Numeric n, Complex c) noexcept
constexpr Complex operator* (Numeric n, Complex c) noexcept
constexpr Complex operator/ (Numeric n, Complex c) noexcept
constexpr Complex operator+ (Complex c, Complex z) noexcept
constexpr Complex operator- (Complex c, Complex z) noexcept
constexpr Complex operator* (Complex c, Complex z) noexcept
constexpr Complex operator/ (Complex c, Complex z) noexcept
constexpr Complex operator- (Complex c) noexcept
_complex_operations_ (int) _complex_operations_(float) _complex_operations_(Index) extern const Joker joker
ConstComplexMatrixView transpose (ConstComplexMatrixView m)
Const version of transpose.
ComplexMatrixView transpose (ComplexMatrixView m)
Returns the transpose.
void copy (ConstComplexIterator1D origin, const ConstComplexIterator1D &end, ComplexIterator1D target)
Copy data between begin and end to target.
void copy (Complex x, ComplexIterator1D target, const ComplexIterator1D &end)
Copy a scalar to all elements.
void copy (ConstComplexIterator2D origin, const ConstComplexIterator2D &end, ComplexIterator2D target)
Copy data between begin and end to target.
void copy (Complex x, ComplexIterator2D target, const ComplexIterator2D &end)
Copy a scalar to all elements.
void mult (ComplexVectorView y, const ConstComplexMatrixView &M, const ConstComplexVectorView &x)
Matrix-Vector Multiplication.
void mult (ComplexMatrixView A, const ConstComplexMatrixView &B, const ConstComplexMatrixView &C)
Matrix-Matrix Multiplication.
void mult (ComplexMatrixView A, const ConstMatrixView &B, const ConstComplexMatrixView &C)
void mult (ComplexMatrixView A, const ConstComplexMatrixView &B, const ConstMatrixView &C)
void mult (ComplexMatrixView A, const ConstMatrixView &B, const ConstMatrixView &C)
Complex operator* (const ConstComplexVectorView &a, const ConstComplexVectorView &b)
Scalar product.
std::ostream & operator<< (std::ostream &os, const ConstComplexVectorView &v)
Output operator.
std::ostream & operator<< (std::ostream &os, const ConstComplexMatrixView &v)
Output operator.
ConstComplexMatrixViewMap MapToEigen (const ConstComplexMatrixView &A)
ConstComplexMatrixViewMap MapToEigen (const ConstComplexVectorView &A)
ConstComplexMatrixViewMap MapToEigenRow (const ConstComplexVectorView &A)
ConstComplexMatrixViewMap MapToEigenCol (const ConstComplexVectorView &A)
ComplexMatrixViewMap MapToEigen (ComplexMatrixView &A)
ComplexMatrixViewMap MapToEigen (ComplexVectorView &A)
ComplexMatrixViewMap MapToEigenRow (ComplexVectorView &A)
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView &A)
Detailed Description
A class implementing complex numbers for ARTS.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2002-12-19
Definition in file complex.h.
Macro Definition Documentation
_complex_operations_
#define _complex_operations_ (T)
Value:
  constexpr Complex operator+(Complex c, T x) noexcept {   \
    return operator+(c, static_cast<Numeric>(x)); \
  }                                               \
  constexpr Complex operator-(Complex c, T x) noexcept {   \
    return operator-(c, static_cast<Numeric>(x)); \
  }                                               \
  constexpr Complex operator*(Complex c, T x) noexcept {   \
    return operator*(c, static_cast<Numeric>(x)); \
  }                                               \
  constexpr Complex operator/(Complex c, T x) noexcept {   \
    return operator/(c, static_cast<Numeric>(x)); \
  }                                               \
                                                  \
  constexpr Complex operator+(T x, Complex c) noexcept {   \
    return operator+(static_cast<Numeric>(x), c); \
  }                                               \
  constexpr Complex operator-(T x, Complex c) noexcept {   \
    return operator-(static_cast<Numeric>(x), c); \
  }                                               \
  constexpr Complex operator*(T x, Complex c) noexcept {   \
    return operator*(static_cast<Numeric>(x), c); \
  }                                               \
  constexpr Complex operator/(T x, Complex c) noexcept {   \
    return operator/(static_cast<Numeric>(x), c); \
  }
Definition at line 137 of file complex.h.
a1
#define a1 c.real()
Definition at line 68 of file complex.h.
a2
#define a2 z.real()
Definition at line 70 of file complex.h.
b1
#define b1 c.imag()
Definition at line 69 of file complex.h.
b2
#define b2 z.imag()
Definition at line 71 of file complex.h.
Typedef Documentation
ArrayOfComplexMatrix
typedef Array<ComplexMatrix> ArrayOfComplexMatrix
Definition at line 975 of file complex.h.
ArrayOfComplexVector
typedef Array<ComplexVector> ArrayOfComplexVector
Definition at line 974 of file complex.h.
Complex
typedef std::complex<Numeric> Complex
Definition at line 33 of file complex.h.
ComplexMatrixType
typedef Eigen::Matrix<Complex, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> ComplexMatrixType
Definition at line 186 of file complex.h.
ComplexMatrixViewMap
typedef Eigen::Map<ComplexMatrixType, 0, StrideType> ComplexMatrixViewMap
Definition at line 187 of file complex.h.
ConstComplexMatrixViewMap
typedef Eigen::Map<const ComplexMatrixType, 0, StrideType> ConstComplexMatrixViewMap
Definition at line 188 of file complex.h.
Function Documentation
_complex_operations_()
_complex_operations_ (int) const
abs2()
constexpr Numeric abs2 (Complex c) constexpr noexcept
squared magnitude of c
Definition at line 74 of file complex.h.
References a1, and b1.
Referenced by operator/(), and test02().
conj()
constexpr Complex conj (Complex c) constexpr noexcept
the conjugate of c
Definition at line 77 of file complex.h.
References a1, and b1.
Referenced by ampmat_to_phamat(), Linefunctions::apply_linemixing_scaling_and_mirroring(), LineShape::frequency_loop(), pCqSDHC_to_arts(), and surface_specular_R_and_b().
copy() [1/4]
void copy (Complex x, ComplexIterator1D target, const ComplexIterator1D & end)
Copy a scalar to all elements.
Definition at line 483 of file complex.cc.
References Zeeman::end(), and ARTS::Var::x().
copy() [2/4]
void copy (Complex x, ComplexIterator2D target, const ComplexIterator2D & end)
Copy a scalar to all elements.
Definition at line 1321 of file complex.cc.
References ComplexVectorView::begin(), and Zeeman::end().
copy() [3/4]
void copy (ConstComplexIterator1D origin, const ConstComplexIterator1D & end, ComplexIterator1D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can for example copy data between different kinds of subvectors.
Definition at line 221 of file complex.cc.
Referenced by ComplexMatrix::ComplexMatrix(), ComplexVector::ComplexVector(), ComplexMatrix::operator=(), Array< base >::operator=(), ComplexMatrixView::operator=(), ComplexVectorView::operator=(), and InteractiveWorkspace::resize().
copy() [4/4]
void copy (ConstComplexIterator2D origin, const ConstComplexIterator2D & end, ComplexIterator2D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can for example copy data between different kinds of subvectors.
Origin, end, and target are 2D iterators, marking rows in a matrix. For each row the 1D iterator is obtained and used to copy the elements.
Definition at line 1309 of file complex.cc.
References ConstComplexVectorView::begin(), and Zeeman::end().
imag()
constexpr Numeric imag (Complex c) constexpr noexcept
imag
Definition at line 83 of file complex.h.
References b1.
Referenced by dtransmat3(), get_maximum_error(), Linefunctions::set_htp(), surface_specular_R_and_b(), test03(), test_ls(), and transmat3().
imag_val() [1/2]
Numeric& imag_val (Complex & c) inline noexcept
Return a reference to the imaginary value of c.
Definition at line 39 of file complex.h.
References c.
Referenced by LineShape::SpeedDependentVoigt::operator()(), and LineShape::HartmannTran::operator()().
imag_val() [2/2]
const Numeric& imag_val (const Complex & c) inline noexcept
Return a const reference to the imaginary value of c.
Definition at line 45 of file complex.h.
References c.
MapToEigen() [1/4]
ComplexMatrixViewMap MapToEigen (ComplexMatrixView & A)
Definition at line 723 of file complex.cc.
MapToEigen() [2/4]
ComplexMatrixViewMap MapToEigen (ComplexVectorView & A)
Definition at line 352 of file complex.cc.
MapToEigen() [3/4]
ConstComplexMatrixViewMap MapToEigen (const ConstComplexMatrixView & A)
Definition at line 722 of file complex.cc.
Referenced by Zeeman::dsum(), MapToEigenRow(), mult(), Linefunctions::set_cross_section_of_band(), Zeeman::sum(), test03(), test48(), test_matrix_exp_propmat(), and xsec_species().
MapToEigen() [4/4]
ConstComplexMatrixViewMap MapToEigen (const ConstComplexVectorView & A)
Definition at line 350 of file complex.cc.
MapToEigenCol() [1/2]
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView & A)
Definition at line 353 of file complex.cc.
MapToEigenCol() [2/2]
ConstComplexMatrixViewMap MapToEigenCol (const ConstComplexVectorView & A)
Definition at line 351 of file complex.cc.
MapToEigenRow() [1/2]
ComplexMatrixViewMap MapToEigenRow (ComplexVectorView & A)
Definition at line 1694 of file complex.cc.
References MapToEigen().
MapToEigenRow() [2/2]
ConstComplexMatrixViewMap MapToEigenRow (const ConstComplexVectorView & A)
Definition at line 1664 of file complex.cc.
References MapToEigen().
mult() [1/5]
void mult (ComplexMatrixView A, const ConstComplexMatrixView & B, const ConstComplexMatrixView & C)
Matrix-Matrix Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand. Note that to keep speed, the inputs should be different variables. There is memory duplication if this is not the case. Note that it is mdata that is checked, so even if the matrices are at different parts of a tensor, there is still a slowdown
Parameters
[in,out] A The matrix A, that will hold the result of the multiplication.
[in] B The matrix B
[in] C The matrix C
Definition at line 711 of file complex.cc.
mult() [2/5]
void mult (ComplexMatrixView A, const ConstComplexMatrixView & B, const ConstMatrixView & C)
Definition at line 717 of file complex.cc.
mult() [3/5]
void mult (ComplexMatrixView A, const ConstMatrixView & B, const ConstComplexMatrixView & C)
Definition at line 714 of file complex.cc.
mult() [4/5]
void mult (ComplexMatrixView A, const ConstMatrixView & B, const ConstMatrixView & C)
Definition at line 1635 of file complex.cc.
References ARTS_ASSERT, MapToEigen(), ConstMatrixView::ncols(), ConstComplexMatrixView::ncols(), ConstMatrixView::nrows(), and ConstComplexMatrixView::nrows().
mult() [5/5]
void mult (ComplexVectorView y, const ConstComplexMatrixView & M, const ConstComplexVectorView & x)
Matrix-Vector Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand.
For left-hand multiplication, please use pure matrix-mult.
Parameters
[out] y The length-m ComplexVectorView where the result is stored.
[in] M Reference to the m-times-n Const{Complex,}MatrixView holding the matrix M.
[in] x Reference to the length-n Const{Complex,}VectorView holding the vector x.
Definition at line 346 of file complex.cc.
Referenced by benchmark_mult(), benchmark_oem_linear(), cloud_RT_surface(), MCAntenna::draw_los(), LinearModel::evaluate(), QuadraticModel::evaluate(), generate_test_data(), get_ppath_transmat(), get_stepwise_effective_source(), get_stepwise_transmission_matrix(), iy_transmittance_mult(), iySurfaceFastem(), QuadraticModel::Jacobian(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), lsf(), matrix_vector_mult(), MatrixMatrixMultiply(), MatrixVectorMultiply(), MCGeneral(), mcPathTraceRadar(), MCRadar(), met_mm_polarisation_hmatrix(), random_fill_matrix_pos_def(), random_fill_matrix_pos_semi_def(), MCAntenna::return_los(), rte_step_doit_replacement(), rtmethods_jacobian_finalisation(), sensor_responseAntenna(), sensor_responseBackend(), sensor_responseFrequencySwitching(), sensor_responseMetMM(), sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), sensor_responsePolarisation(), sensor_responseStokesRotation(), sensor_responseWMRF(), SparseSparseMultiply(), surface_calc(), test4(), test40(), test42(), test5(), test_complex_diagonalize(), test_dense_sparse_multiplication(), test_inv(), test_lusolve4D(), test_real_diagonalize(), test_solve_linear_system(), test_sparse_arithmetic(), test_sparse_dense_multiplication(), transform_jacobian(), transform_x(), transform_x_back(), VectorMatrixMultiply(), yCalc(), yCalc_mblock_loop_body(), yRadar(), and ySimpleSpectrometer().
operator*() [1/6]
constexpr Complex operator* (Complex c, Complex z) constexpr noexcept
Definition at line 120 of file complex.h.
References a1, a2, b1, and b2.
operator*() [2/6]
constexpr Complex operator* (Complex c, Numeric n) constexpr noexcept
Definition at line 94 of file complex.h.
References a1, and b1.
operator*() [3/6]
Complex operator* (const ConstComplexVectorView & a, const ConstComplexVectorView & b)
Scalar product.
The two vectors may be identical.
Definition at line 329 of file complex.cc.
operator*() [4/6]
std::complex<float> operator* (const double & d, const std::complex< float > & c) inline
Definition at line 51 of file complex.h.
References c, and d.
operator*() [5/6]
std::complex<float> operator* (const std::complex< float > & c, const double & d) inline
Definition at line 60 of file complex.h.
References c, and d.
operator*() [6/6]
constexpr Complex operator* (Numeric n, Complex c) constexpr noexcept
Definition at line 107 of file complex.h.
References a1, and b1.
operator+() [1/5]
constexpr Complex operator+ (Complex c, Complex z) constexpr noexcept
Definition at line 114 of file complex.h.
References a1, a2, b1, and b2.
operator+() [2/5]
constexpr Complex operator+ (Complex c, Numeric n) constexpr noexcept
Definition at line 88 of file complex.h.
References a1, and b1.
operator+() [3/5]
std::complex<float> operator+ (const double & d, const std::complex< float > & c) inline
Definition at line 47 of file complex.h.
References c, and d.
operator+() [4/5]
std::complex<float> operator+ (const std::complex< float > & c, const double & d) inline
Definition at line 56 of file complex.h.
References c, and d.
operator+() [5/5]
constexpr Complex operator+ (Numeric n, Complex c) constexpr noexcept
Definition at line 101 of file complex.h.
References a1, and b1.
operator-() [1/4]
constexpr Complex operator- (Complex c) constexpr noexcept
Definition at line 126 of file complex.h.
References a1, and b1.
operator-() [2/4]
constexpr Complex operator- (Complex c, Complex z) constexpr noexcept
Definition at line 117 of file complex.h.
References a1, a2, b1, and b2.
operator-() [3/4]
constexpr Complex operator- (Complex c, Numeric n) constexpr noexcept
Definition at line 91 of file complex.h.
References a1, and b1.
operator-() [4/4]
constexpr Complex operator- (Numeric n, Complex c) constexpr noexcept
Definition at line 104 of file complex.h.
References a1, and b1.
operator/() [1/3]
constexpr Complex operator/ (Complex c, Complex z) constexpr noexcept
Definition at line 123 of file complex.h.
References a1, a2, abs2(), b1, and b2.
operator/() [2/3]
constexpr Complex operator/ (Complex c, Numeric n) constexpr noexcept
Definition at line 97 of file complex.h.
References a1, and b1.
operator/() [3/3]
constexpr Complex operator/ (Numeric n, Complex c) constexpr noexcept
Definition at line 110 of file complex.h.
References a1, abs2(), b1, and c.
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const ConstComplexMatrixView & v)
Output operator.
This demonstrates how iterators can be used to traverse the matrix. The iterators know which part of the matrix is ‘active’, and also the strides in both directions. This function is a bit more complicated than necessary to illustrate the concept, because the formating should look nice. This means that the first row, and the first element in each row, have to be treated individually.
Definition at line 863 of file complex.cc.
References ConstComplexVectorView::begin(), ConstComplexVectorView::end(), and v.
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const ConstComplexVectorView & v)
Output operator.
This demonstrates how iterators can be used to traverse the vector. The iterators know which part of the vector is ‘active’, and also the stride.
Definition at line 131 of file complex.cc.
References Zeeman::end(), and v.
real()
constexpr Numeric real (Complex c) constexpr noexcept
real
Definition at line 80 of file complex.h.
References a1.
Referenced by ampmat_to_phamat(), lm_hitran_2017::compabs(), dtransmat3(), get_maximum_error(), Linefunctions::set_htp(), surface_specular_R_and_b(), test03(), test_ls(), and transmat3().
real_val() [1/2]
Numeric& real_val (Complex & c) inline noexcept
Return a reference to the real value of c.
Definition at line 36 of file complex.h.
References c.
real_val() [2/2]
const Numeric& real_val (const Complex & c) inline noexcept
Return a const reference to the real value of c.
Definition at line 42 of file complex.h.
References c.
transpose() [1/2]
ComplexMatrixView transpose (ComplexMatrixView m)
Returns the transpose.
This creates a special MatrixView for the transpose. The original is not changed!
Definition at line 860 of file complex.cc.
transpose() [2/2]
ConstComplexMatrixView transpose (ConstComplexMatrixView m)
Const version of transpose.
Definition at line 707 of file complex.cc.
Referenced by Append(), lm_hitran_2017::calcw(), generate_test_data(), jacobianSetAffineTransformation(), lsf(), matrix_vector_mult(), MCRadar(), CovarianceMatrix::operator Matrix(), operator+=(), random_fill_matrix_pos_def(), random_fill_matrix_pos_semi_def(), random_fill_matrix_symmetric(), rtmethods_jacobian_finalisation(), test03(), test1(), test33(), test41(), test42(), test5(), test_dense_sparse_multiplication(), test_diagonal(), test_sparse_dense_multiplication(), transform_x(), transpose(), and WMRFSelectChannels().