ARTS: complex.cc File Reference
complex.cc File Reference
A class implementing complex numbers for ARTS.
#include "complex.h"
#include <cmath>
#include <cstring>
#include "blas.h"
#include "exceptions.h"
Functions
std::ostream & operator<< (std::ostream &os, const ConstComplexVectorView &v)
Output operator.
void copy (ConstComplexIterator1D origin, const ConstComplexIterator1D &end, ComplexIterator1D target)
Copy data between begin and end to target.
void copy (Complex x, ComplexIterator1D target, const ComplexIterator1D &end)
Copy a scalar to all elements.
void swap (ComplexVector &v1, ComplexVector &v2)
Swaps two objects.
std::ostream & operator<< (std::ostream &os, const ConstComplexMatrixView &v)
Output operator.
void copy (ConstComplexIterator2D origin, const ConstComplexIterator2D &end, ComplexIterator2D target)
Copy data between begin and end to target.
void copy (Complex x, ComplexIterator2D target, const ComplexIterator2D &end)
Copy a scalar to all elements.
void copy (Numeric x, ComplexIterator2D target, const ComplexIterator2D &end)
Copy a scalar to all elements.
void swap (ComplexMatrix &m1, ComplexMatrix &m2)
Swaps two objects.
ConstComplexMatrixView transpose (ConstComplexMatrixView m)
Const version of transpose.
ComplexMatrixView transpose (ComplexMatrixView m)
Returns the transpose.
ComplexMatrixView transpose (ComplexVector v)
Returns the transpose.
Complex operator* (const ConstComplexVectorView &a, const ConstComplexVectorView &b)
Scalar product.
void mult (ComplexVectorView y, const ConstComplexMatrixView &M, const ConstComplexVectorView &x)
Matrix-Vector Multiplication.
void mult (ComplexMatrixView A, const ConstComplexMatrixView &B, const ConstComplexMatrixView &C)
Matrix-Matrix Multiplication.
void mult (ComplexMatrixView A, const ConstComplexMatrixView &B, const ConstMatrixView &C)
void mult (ComplexMatrixView A, const ConstMatrixView &B, const ConstComplexMatrixView &C)
void mult (ComplexMatrixView A, const ConstMatrixView &B, const ConstMatrixView &C)
ComplexConstMatrixViewMap MapToEigen (const ConstComplexMatrixView &A)
ComplexConstMatrixViewMap MapToEigen (const ConstComplexVectorView &A)
ComplexConstMatrixViewMap MapToEigenRow (const ConstComplexVectorView &A)
ComplexConstMatrixViewMap MapToEigenCol (const ConstComplexVectorView &A)
ComplexMatrixViewMap MapToEigen (ComplexMatrixView &A)
ComplexMatrixViewMap MapToEigen (ComplexVectorView &A)
ComplexMatrixViewMap MapToEigenRow (ComplexVectorView &A)
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView &A)
Complex debug_matrixview_get_elem (ComplexMatrixView &mv, Index r, Index c)
Helper function to access matrix elements.
Detailed Description
A class implementing complex numbers for ARTS.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2002-12-19
Definition in file complex.cc.
Function Documentation
copy() [1/5]
void copy (Complex x, ComplexIterator1D target, const ComplexIterator1D & end)
Copy a scalar to all elements.
Definition at line 483 of file complex.cc.
References Zeeman::end(), and x.
copy() [2/5]
void copy (Complex x, ComplexIterator2D target, const ComplexIterator2D & end)
Copy a scalar to all elements.
Definition at line 1321 of file complex.cc.
References ComplexVectorView::begin(), and Zeeman::end().
copy() [3/5]
void copy (ConstComplexIterator1D origin, const ConstComplexIterator1D & end, ComplexIterator1D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can for example copy data between different kinds of subvectors.
Definition at line 471 of file complex.cc.
Referenced by ComplexMatrix::ComplexMatrix(), ComplexVector::ComplexVector(), ComplexMatrix::operator=(), Array< base >::operator=(), ComplexMatrixView::operator=(), ComplexVectorView::operator=(), and InteractiveWorkspace::resize().
copy() [4/5]
void copy (ConstComplexIterator2D origin, const ConstComplexIterator2D & end, ComplexIterator2D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can for example copy data between different kinds of subvectors.
Origin, end, and target are 2D iterators, marking rows in a matrix. For each row the 1D iterator is obtained and used to copy the elements.
Definition at line 1309 of file complex.cc.
References ConstComplexVectorView::begin(), and Zeeman::end().
copy() [5/5]
void copy (Numeric x, ComplexIterator2D target, const ComplexIterator2D & end)
Copy a scalar to all elements.
Definition at line 1330 of file complex.cc.
References ComplexVectorView::begin(), and Zeeman::end().
debug_matrixview_get_elem()
Complex debug_matrixview_get_elem (ComplexMatrixView & mv, Index r, Index c)
Helper function to access matrix elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Matrix elements from within the debugger.
Parameters
mv MatrixView
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 1723 of file complex.cc.
References c.
MapToEigen() [1/4]
ComplexMatrixViewMap MapToEigen (ComplexMatrixView & A)
Definition at line 1677 of file complex.cc.
MapToEigen() [2/4]
ComplexMatrixViewMap MapToEigen (ComplexVectorView & A)
Definition at line 1686 of file complex.cc.
MapToEigen() [3/4]
ComplexConstMatrixViewMap MapToEigen (const ConstComplexMatrixView & A)
Definition at line 1647 of file complex.cc.
Referenced by MapToEigenRow(), mult(), Linefunctions::set_cross_section_of_band(), test03(), test48(), test_matrix_exp_propmat(), xsec_species(), and zeeman_on_the_fly().
MapToEigen() [4/4]
ComplexConstMatrixViewMap MapToEigen (const ConstComplexVectorView & A)
Definition at line 1656 of file complex.cc.
MapToEigenCol() [1/2]
ComplexMatrixViewMap MapToEigenCol (ComplexVectorView & A)
Definition at line 1699 of file complex.cc.
MapToEigenCol() [2/2]
ComplexConstMatrixViewMap MapToEigenCol (const ConstComplexVectorView & A)
Definition at line 1669 of file complex.cc.
MapToEigenRow() [1/2]
ComplexMatrixViewMap MapToEigenRow (ComplexVectorView & A)
Definition at line 1694 of file complex.cc.
References MapToEigen().
MapToEigenRow() [2/2]
ComplexConstMatrixViewMap MapToEigenRow (const ConstComplexVectorView & A)
Definition at line 1664 of file complex.cc.
References MapToEigen().
mult() [1/5]
void mult (ComplexMatrixView A, const ConstComplexMatrixView & B, const ConstComplexMatrixView & C)
Matrix-Matrix Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand. Note that to keep speed, the inputs should be different variables. There is memory duplication if this is not the case. Note that it is mdata that is checked, so even if the matrices are at different parts of a tensor, there is still a slowdown
Parameters
[in,out] A The matrix A, that will hold the result of the multiplication.
[in] B The matrix B
[in] C The matrix C
Definition at line 1596 of file complex.cc.
mult() [2/5]
void mult (ComplexMatrixView A, const ConstComplexMatrixView & B, const ConstMatrixView & C)
Definition at line 1609 of file complex.cc.
mult() [3/5]
void mult (ComplexMatrixView A, const ConstMatrixView & B, const ConstComplexMatrixView & C)
Definition at line 1622 of file complex.cc.
mult() [4/5]
void mult (ComplexMatrixView A, const ConstMatrixView & B, const ConstMatrixView & C)
Definition at line 1635 of file complex.cc.
References ARTS_ASSERT, MapToEigen(), ConstComplexMatrixView::ncols(), ConstMatrixView::ncols(), ConstComplexMatrixView::nrows(), and ConstMatrixView::nrows().
mult() [5/5]
void mult (ComplexVectorView y, const ConstComplexMatrixView & M, const ConstComplexVectorView & x)
Matrix-Vector Multiplication.
Uses the Eigen library. Be carful to test the size of your input beforehand.
For left-hand multiplication, please use pure matrix-mult.
Parameters
[out] y The length-m ComplexVectorView where the result is stored.
[in] M Reference to the m-times-n Const{Complex,}MatrixView holding the matrix M.
[in] x Reference to the length-n Const{Complex,}VectorView holding the vector x.
Definition at line 1571 of file complex.cc.
Referenced by benchmark_mult(), benchmark_oem_linear(), cloud_RT_surface(), MCAntenna::draw_los(), LinearModel::evaluate(), QuadraticModel::evaluate(), generate_test_data(), get_ppath_transmat(), get_stepwise_effective_source(), get_stepwise_transmission_matrix(), iy_transmittance_mult(), iySurfaceFastem(), QuadraticModel::Jacobian(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), lsf(), matrix_vector_mult(), MatrixMatrixMultiply(), MatrixVectorMultiply(), MCGeneral(), mcPathTraceRadar(), MCRadar(), met_mm_polarisation_hmatrix(), random_fill_matrix_pos_def(), random_fill_matrix_pos_semi_def(), MCAntenna::return_los(), rte_step_doit_replacement(), rtmethods_jacobian_finalisation(), sensor_responseAntenna(), sensor_responseBackend(), sensor_responseFrequencySwitching(), sensor_responseMetMM(), sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), sensor_responsePolarisation(), sensor_responseStokesRotation(), sensor_responseWMRF(), SparseSparseMultiply(), surface_calc(), test4(), test40(), test42(), test5(), test_complex_diagonalize(), test_dense_sparse_multiplication(), test_inv(), test_lusolve4D(), test_real_diagonalize(), test_solve_linear_system(), test_sparse_arithmetic(), test_sparse_dense_multiplication(), transform_jacobian(), transform_x(), transform_x_back(), VectorMatrixMultiply(), yCalc(), yCalc_mblock_loop_body(), yRadar(), and ySimpleSpectrometer().
operator*()
Complex operator* (const ConstComplexVectorView & a, const ConstComplexVectorView & b)
Scalar product.
The two vectors may be identical.
Definition at line 1546 of file complex.cc.
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const ConstComplexMatrixView & v)
Output operator.
This demonstrates how iterators can be used to traverse the matrix. The iterators know which part of the matrix is ‘active’, and also the strides in both directions. This function is a bit more complicated than necessary to illustrate the concept, because the formating should look nice. This means that the first row, and the first element in each row, have to be treated individually.
Definition at line 863 of file complex.cc.
References ConstComplexVectorView::begin(), ConstComplexVectorView::end(), and v().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const ConstComplexVectorView & v)
Output operator.
This demonstrates how iterators can be used to traverse the vector. The iterators know which part of the vector is ‘active’, and also the stride.
Definition at line 131 of file complex.cc.
References Zeeman::end(), and v().
swap() [1/2]
void swap (ComplexMatrix & m1, ComplexMatrix & m2)
Swaps two objects.
Definition at line 1467 of file complex.cc.
swap() [2/2]
void swap (ComplexVector & v1, ComplexVector & v2)
Swaps two objects.
Definition at line 728 of file complex.cc.
Referenced by lm_hitran_2017::calcw(), create_covariance_matrix_1D(), create_sparse_covariance_matrix_1D(), diagonalize(), emission_from_propmat_field(), CovarianceMatrix::get_block(), CovarianceMatrix::has_block(), iyHybrid(), iyTransmissionStandard(), binistream::readFloat(), InteractiveWorkspace::resize(), Absorption::LineMixing::PopulationAndDipole::sort(), InteractiveWorkspace::swap(), transform_jacobian(), transform_x(), transform_x_back(), and binostream::writeFloat().
transpose() [1/3]
ComplexMatrixView transpose (ComplexMatrixView m)
Returns the transpose.
This creates a special MatrixView for the transpose. The original is not changed!
Definition at line 1507 of file complex.cc.
transpose() [2/3]
ComplexMatrixView transpose (ComplexVector v)
Returns the transpose.
This creates a special MatrixView for the transpose. The original is not changed!
Definition at line 1513 of file complex.cc.
References transpose(), and v().
transpose() [3/3]
ConstComplexMatrixView transpose (ConstComplexMatrixView m)
Const version of transpose.
Definition at line 1501 of file complex.cc.
Referenced by Append(), lm_hitran_2017::calcw(), generate_test_data(), jacobianSetAffineTransformation(), lsf(), matrix_vector_mult(), MCRadar(), CovarianceMatrix::operator Matrix(), operator+=(), random_fill_matrix_pos_def(), random_fill_matrix_pos_semi_def(), random_fill_matrix_symmetric(), rtmethods_jacobian_finalisation(), test03(), test1(), test33(), test41(), test42(), test5(), test_dense_sparse_multiplication(), test_diagonal(), test_sparse_dense_multiplication(), transform_x(), transpose(), and WMRFSelectChannels().