ARTS: covariance_matrix.cc File Reference
covariance_matrix.cc File Reference
Implementation of CovarianceMatrix class.
#include <queue>
#include <tuple>
#include <utility>
#include <vector>
#include "covariance_matrix.h"
#include "lapack.h"
Functions
void mult (MatrixView C, ConstMatrixView A, const Block &B)
void mult (MatrixView C, const Block &A, ConstMatrixView B)
void mult (VectorView w, const Block &A, ConstVectorView v)
MatrixView & operator+= (MatrixView &A, const Block &B)
void mult (MatrixView C, ConstMatrixView A, const CovarianceMatrix &B)
void mult (MatrixView C, const CovarianceMatrix &A, ConstMatrixView B)
void mult (VectorView w, const CovarianceMatrix &A, ConstVectorView v)
void mult_inv (MatrixView C, ConstMatrixView A, const CovarianceMatrix &B)
void mult_inv (MatrixView C, const CovarianceMatrix &A, ConstMatrixView B)
void solve (VectorView w, const CovarianceMatrix &A, ConstVectorView v)
MatrixView & operator+= (MatrixView &A, const CovarianceMatrix &B)
void add_inv (MatrixView A, const CovarianceMatrix &B)
std::ostream & operator<< (std::ostream &os, const CovarianceMatrix &covmat)
Detailed Description
Implementation of CovarianceMatrix class.
Author
Simon Pfreundschuh simon.nosp@m..pfr.nosp@m.eunds.nosp@m.chuh.nosp@m.@chal.nosp@m.mers.nosp@m..se
Date
2017-06-19
Definition in file covariance_matrix.cc.
Function Documentation
add_inv()
void add_inv (MatrixView A, const CovarianceMatrix & B)
Definition at line 624 of file covariance_matrix.cc.
References CovarianceMatrix::correlations_.
mult() [1/6]
void mult (MatrixView C, const Block & A, ConstMatrixView B)
Definition at line 68 of file covariance_matrix.cc.
mult() [2/6]
void mult (MatrixView C, const CovarianceMatrix & A, ConstMatrixView B)
Definition at line 567 of file covariance_matrix.cc.
mult() [3/6]
void mult (MatrixView C, ConstMatrixView A, const Block & B)
Definition at line 38 of file covariance_matrix.cc.
mult() [4/6]
void mult (MatrixView C, ConstMatrixView A, const CovarianceMatrix & B)
Definition at line 557 of file covariance_matrix.cc.
mult() [5/6]
void mult (VectorView w, const Block & A, ConstVectorView v)
Definition at line 98 of file covariance_matrix.cc.
mult() [6/6]
void mult (VectorView w, const CovarianceMatrix & A, ConstVectorView v)
Definition at line 577 of file covariance_matrix.cc.
References CovarianceMatrix::correlations_.
mult_inv() [1/2]
void mult_inv (MatrixView C, const CovarianceMatrix & A, ConstMatrixView B)
Definition at line 597 of file covariance_matrix.cc.
mult_inv() [2/2]
void mult_inv (MatrixView C, ConstMatrixView A, const CovarianceMatrix & B)
Definition at line 587 of file covariance_matrix.cc.
operator+=() [1/2]
MatrixView& operator+= (MatrixView & A, const Block & B)
Definition at line 120 of file covariance_matrix.cc.
References c, Block::dense, and transpose().
operator+=() [2/2]
MatrixView& operator+= (MatrixView & A, const CovarianceMatrix & B)
Definition at line 617 of file covariance_matrix.cc.
operator<<()
std::ostream& operator<< (std::ostream & os, const CovarianceMatrix & covmat)
Definition at line 630 of file covariance_matrix.cc.
solve()
void solve (VectorView w, const CovarianceMatrix & A, ConstVectorView v)
Definition at line 607 of file covariance_matrix.cc.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines(), oem::NormalizingSolver< TransformationMatrixType, SolverType >::solve(), and test_solve_linear_system().