ARTS: covariance_matrix.h File Reference
covariance_matrix.h File Reference
Header files of CovarianceMatrix class.
#include <memory>
#include "jacobian.h"
#include "matpackI.h"
#include "matpackII.h"
Classes
class Block
class CovarianceMatrix
Typedefs
using IndexPair = std::pair< Index, Index >
Functions
void mult (MatrixView, ConstMatrixView, const Block &)
void mult (MatrixView, const Block &, ConstMatrixView)
void mult (VectorView, const Block &, ConstVectorView)
MatrixView & operator+= (MatrixView &, const Block &)
void add_inv (MatrixView A, const Block &)
void mult (MatrixView, ConstMatrixView, const CovarianceMatrix &)
void mult (MatrixView, const CovarianceMatrix &, ConstMatrixView)
void mult (VectorView, const CovarianceMatrix &, ConstVectorView)
void mult_inv (MatrixView, ConstMatrixView, const CovarianceMatrix &)
void mult_inv (MatrixView, const CovarianceMatrix &, ConstMatrixView)
void solve (VectorView, const CovarianceMatrix &, ConstVectorView)
MatrixView & operator+= (MatrixView &, const CovarianceMatrix &)
void add_inv (MatrixView, const CovarianceMatrix &)
std::ostream & operator<< (std::ostream &os, const ConstVectorView &v)
Detailed Description
Header files of CovarianceMatrix class.
Author
Simon Pfreundschuh simon.nosp@m..pfr.nosp@m.eunds.nosp@m.chuh.nosp@m.@chal.nosp@m.mers.nosp@m..se
Date
2017-06-19
Notes:
Defines the CovarianceMatrix class which implements the specific structure of covariance matrices and their inverse.
Definition in file covariance_matrix.h.
Typedef Documentation
IndexPair
using IndexPair = std::pair<Index, Index>
Definition at line 49 of file covariance_matrix.h.
Function Documentation
add_inv() [1/2]
void add_inv (MatrixView A, const Block &)
add_inv() [2/2]
void add_inv (MatrixView A, const CovarianceMatrix & B)
Definition at line 384 of file covariance_matrix.cc.
References CovarianceMatrix::correlations_.
mult() [1/6]
void mult (MatrixView C, const Block & A, ConstMatrixView B)
Definition at line 182 of file covariance_matrix.cc.
mult() [2/6]
void mult (MatrixView C, const CovarianceMatrix & A, ConstMatrixView B)
Definition at line 376 of file covariance_matrix.cc.
mult() [3/6]
void mult (MatrixView C, ConstMatrixView A, const Block & B)
Definition at line 181 of file covariance_matrix.cc.
mult() [4/6]
void mult (MatrixView C, ConstMatrixView A, const CovarianceMatrix & B)
Definition at line 375 of file covariance_matrix.cc.
mult() [5/6]
void mult (VectorView w, const Block & A, ConstVectorView v)
Definition at line 183 of file covariance_matrix.cc.
mult() [6/6]
void mult (VectorView w, const CovarianceMatrix & A, ConstVectorView v)
Definition at line 377 of file covariance_matrix.cc.
References CovarianceMatrix::correlations_.
mult_inv() [1/2]
void mult_inv (MatrixView C, const CovarianceMatrix & A, ConstMatrixView B)
Definition at line 380 of file covariance_matrix.cc.
mult_inv() [2/2]
void mult_inv (MatrixView C, ConstMatrixView A, const CovarianceMatrix & B)
Definition at line 379 of file covariance_matrix.cc.
operator+=() [1/2]
MatrixView& operator+= (MatrixView & A, const Block & B)
Definition at line 185 of file covariance_matrix.cc.
References c, Block::dense, and transpose().
operator+=() [2/2]
MatrixView& operator+= (MatrixView & A, const CovarianceMatrix & B)
Definition at line 383 of file covariance_matrix.cc.
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstVectorView & v)
Definition at line 109 of file matpackI.cc.
References Zeeman::end(), and v.
solve()
void solve (VectorView w, const CovarianceMatrix & A, ConstVectorView v)
Definition at line 381 of file covariance_matrix.cc.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines(), oem::NormalizingSolver< TransformationMatrixType, SolverType >::solve(), and test_solve_linear_system().