ARTS: describe.h File Reference
describe.h File Reference
Header file for describe.cc.
#include "matpackVII.h"
#include "mystring.h"
Functions
String describe (ConstTensor7View x)
Describe Tensor7.
String describe (ConstTensor6View x)
Describe Tensor6.
String describe (ConstTensor5View x)
Describe Tensor5.
String describe (ConstTensor4View x)
Describe Tensor4.
String describe (ConstTensor3View x)
Describe Tensor3.
String describe (ConstMatrixView x)
Describe Matrix.
String describe (ConstVectorView x)
Describe Vector.
String describe (const Numeric &x)
Describe Scalar.
Detailed Description
Header file for describe.cc.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Feb 25 15:35:56 2003
For documentation see file describe.cc
Definition in file describe.h.
Function Documentation
describe() [1/8]
String describe (const Numeric & x)
Describe Scalar.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 114 of file describe.cc.
References ARTS::Var::x().
describe() [2/8]
String describe (ConstMatrixView x)
Describe Matrix.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 94 of file describe.cc.
References ARTS::Var::x().
describe() [3/8]
String describe (ConstTensor3View x)
Describe Tensor3.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 83 of file describe.cc.
References ARTS::Var::x().
describe() [4/8]
String describe (ConstTensor4View x)
Describe Tensor4.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 72 of file describe.cc.
References ARTS::Var::x().
describe() [5/8]
String describe (ConstTensor5View x)
Describe Tensor5.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 61 of file describe.cc.
References ARTS::Var::x().
describe() [6/8]
String describe (ConstTensor6View x)
Describe Tensor6.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 50 of file describe.cc.
References ARTS::Var::x().
describe() [7/8]
String describe (ConstTensor7View x)
Describe Tensor7.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 38 of file describe.cc.
References ARTS::Var::x().
Referenced by junk2(), junk4(), option_describe(), and test33().
describe() [8/8]
String describe (ConstVectorView x)
Describe Vector.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 104 of file describe.cc.
References ARTS::Var::x().