ARTS: disort.cc File Reference
disort.cc File Reference
This file contains functions related to the DISORT interface.
#include "disort.h"
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <stdexcept>
#include "agenda_class.h"
#include "array.h"
#include "auto_md.h"
#include "check_input.h"
#include "cdisort.h"
#include "interpolation.h"
#include "logic.h"
#include "math_funcs.h"
#include "messages.h"
#include "rte.h"
#include "xml_io.h"
Macros
#define MAX_WARNINGS 100
Functions
void check_disort_input (const Index &cloudbox_on, const Index &atmfields_checked, const Index &atmgeom_checked, const Index &cloudbox_checked, const Index &scat_data_checked, const Index &atmosphere_dim, const Index &stokes_dim, const ArrayOfIndex &cloudbox_limits, const ArrayOfArrayOfSingleScatteringData &scat_data, ConstVectorView za_grid, const Index &nstreams, const String &pfct_method)
check_disort_input.
void init_ifield (Tensor7 &cloudbox_field, const Vector &f_grid, const ArrayOfIndex &cloudbox_limits, const Index &nang, const Index &stokes_dim)
init_ifield.
void get_disortsurf_props (Vector &albedo, Numeric &btemp, ConstVectorView f_grid, const Numeric &surface_skin_t, ConstVectorView surface_scalar_reflectivity)
get_disortsurf_props.
void get_gasoptprop (Workspace &ws, MatrixView ext_bulk_gas, const Agenda &propmat_clearsky_agenda, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstVectorView p_grid, ConstVectorView f_grid)
get_gasoptprop.
void get_paroptprop (MatrixView ext_bulk_par, MatrixView abs_bulk_par, const ArrayOfArrayOfSingleScatteringData &scat_data, ConstMatrixView pnd_profiles, ConstVectorView t_profile, ConstVectorView DEBUG_ONLY(p_grid), const ArrayOfIndex &cloudbox_limits, ConstVectorView f_grid)
void get_dtauc_ssalb (MatrixView dtauc, MatrixView ssalb, ConstMatrixView ext_bulk_gas, ConstMatrixView ext_bulk_par, ConstMatrixView abs_bulk_par, ConstVectorView z_profile)
get_dtauc_ssalb
void get_angs (Vector &pfct_angs, const ArrayOfArrayOfSingleScatteringData &scat_data, const Index &Npfct)
get_angs.
void get_parZ (Tensor3 &pha_bulk_par, const ArrayOfArrayOfSingleScatteringData &scat_data, ConstMatrixView pnd_profiles, ConstVectorView t_profile, ConstVectorView pfct_angs, const ArrayOfIndex &cloudbox_limits)
get_parZ.
void get_pfct (Tensor3 &pfct_bulk_par, ConstTensor3View &pha_bulk_par, ConstMatrixView ext_bulk_par, ConstMatrixView abs_bulk_par, const ArrayOfIndex &cloudbox_limits)
get_pfct.
void get_pmom (Tensor3View pmom, ConstTensor3View pfct_bulk_par, ConstVectorView pfct_angs, const Index &Nlegendre)
get_pmom
void c_errmsg (const char *messag, int type)
Verbosity enabled replacement for the original cdisort function.
int c_write_bad_var (int quiet, const char *varnam)
Verbosity enabled replacement for the original cdisort function.
int c_write_too_small_dim (int quiet, const char *dimnam, int minval)
Verbosity enabled replacement for the original cdisort function.
void reduced_1datm (Vector &p, Vector &z, Vector &t, Matrix &vmr, Matrix &pnd, ArrayOfIndex &cboxlims, Index &ncboxremoved, ConstVectorView p_grid, ConstVectorView z_profile, const Numeric &z_surface, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstMatrixView pnd_profiles, const ArrayOfIndex &cloudbox_limits)
reduced_1datm
void run_cdisort (Workspace &ws, Tensor7 &cloudbox_field, ConstVectorView f_grid, ConstVectorView p_grid, ConstVectorView z_profile, const Numeric &z_surface, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstMatrixView pnd_profiles, const ArrayOfArrayOfSingleScatteringData &scat_data, const Agenda &propmat_clearsky_agenda, const ArrayOfIndex &cloudbox_limits, const Numeric &surface_skin_t, const Vector &surface_scalar_reflectivity, ConstVectorView za_grid, const Index &nstreams, const Index &Npfct, const Index &quiet, const Verbosity &verbosity)
Calculate doit_i_feild with Disort.
void surf_albedoCalc (Workspace &ws, VectorView albedo, Numeric &btemp, const Agenda &surface_rtprop_agenda, ConstVectorView f_grid, ConstVectorView scat_za_grid, const Numeric &surf_alt, const Verbosity &verbosity)
Surface albed.
Variables
const Numeric PI
const Numeric DEG2RAD
const Numeric PLANCK_CONST
const Numeric SPEED_OF_LIGHT
const Numeric COSMIC_BG_TEMP
thread_local Verbosity disort_verbosity
Detailed Description
This file contains functions related to the DISORT interface.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@d.nosp@m.lr.d.nosp@m.e
Date
Tue Feb 7 10:08:28 2006
Definition in file disort.cc.
Macro Definition Documentation
MAX_WARNINGS
#define MAX_WARNINGS 100
Definition at line 633 of file disort.cc.
Function Documentation
c_errmsg()
void c_errmsg (const char * messag, int type)
Verbosity enabled replacement for the original cdisort function.
Definition at line 636 of file disort.cc.
References arts_exit(), CREATE_OUT0, CREATE_OUT1, disort_verbosity, and MAX_WARNINGS.
Referenced by c_write_bad_var().
c_write_bad_var()
int c_write_bad_var (int quiet, const char * varnam)
Verbosity enabled replacement for the original cdisort function.
Definition at line 664 of file disort.cc.
References c_errmsg(), CREATE_OUT1, and disort_verbosity.
c_write_too_small_dim()
int c_write_too_small_dim (int quiet, const char * dimnam, int minval)
Verbosity enabled replacement for the original cdisort function.
Definition at line 682 of file disort.cc.
References CREATE_OUT1, and disort_verbosity.
check_disort_input()
void check_disort_input (const Index & cloudbox_on, const Index & atmfields_checked, const Index & atmgeom_checked, const Index & cloudbox_checked, const Index & scat_data_checked, const Index & atmosphere_dim, const Index & stokes_dim, const ArrayOfIndex & cloudbox_limits, const ArrayOfArrayOfSingleScatteringData & scat_data, ConstVectorView za_grid, const Index & nstreams, const String & pfct_method)
check_disort_input.
*** FIXMEDOC *** in disort.cc, line 197
Checks that input of DisortCalc* is sane.
Parameters
[in] cloudbox_on as the WSV.
[in] disort_is_initialized as the WSV.
[in] atmfields_checked as the WSV.
[in] atmgeom_checked as the WSV.
[in] cloudbox_checked as the WSV.
[in] scat_data as the WSV.
[in] za_grid as the WSV.
[in] nstreams Number of quadrature angles (both hemispheres).
[in] pfct_method see DisortCalc doc.
Author
Jana Mendrok
Date
2017-02-23
Definition at line 55 of file disort.cc.
References is_increasing(), Array< base >::nelem(), ConstVectorView::nelem(), PTYPE_AZIMUTH_RND, PTYPE_GENERAL, PTYPE_TOTAL_RND, and PTypeToString().
Referenced by DisortCalc(), and DisortCalcWithARTSSurface().
get_angs()
void get_angs (Vector & pfct_angs, const ArrayOfArrayOfSingleScatteringData & scat_data, const Index & Npfct)
get_angs.
Derives angular grid to derive bulk phase matrix/function data on for further Legendre decomposition.
Parameters
[out] pfct_angs Angular grid of pfct_bulk_par.
[in] scat_data As the WSV.
[in] nang Number of angular grid points in pfct_angs. If<0,
pfct_angs is taken from scat_data (the finest za_grid used over the scat elems), else an equidistant grid with nang grid points is used.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 432 of file disort.cc.
References Array< base >::nelem(), Absorption::nelem(), and nlinspace().
Referenced by run_cdisort().
get_disortsurf_props()
void get_disortsurf_props (Vector & albedo, Numeric & btemp, ConstVectorView f_grid, const Numeric & surface_skin_t, ConstVectorView surface_scalar_reflectivity)
get_disortsurf_props.
*** FIXMEDOC *** input/output
Derive surface property input for RT4's proprietary surface handling depending on surface reflection type.
Parameters
[out] ground_albedo Scalar surface albedo (for ground_type=L).
[out] ground_reflec Vector surface relfectivity (for ground_type=S).
[out] ground_index Surface complex refractive index (for ground_type=F).
[out] btemp Surface temperature
[in] f_grid As the WSV.
[in] ground_type Surface reflection type flag.
[in] surface_skin_t As the WSV.
[in] surface_scalar_reflectivity As the WSV (used with ground_type=L).
[in] surface_reflectivity As the WSV (used with ground_type=S).
[in] surface_complex_refr_index As the WSV (used with ground_type=F).
[in] stokes_dim As the WSV.
Author
Jana Mendrok
Date
2017-02-23
Definition at line 223 of file disort.cc.
References max, min, and ConstVectorView::nelem().
Referenced by DisortCalc().
get_dtauc_ssalb()
void get_dtauc_ssalb (MatrixView dtauc, MatrixView ssalb, ConstMatrixView ext_bulk_gas, ConstMatrixView ext_bulk_par, ConstMatrixView abs_bulk_par, ConstVectorView z_profile)
get_dtauc_ssalb
Calculates layer averaged cloud optical depth (dtauc) and single scattering albedo (ssalb) as required as DISORT subroutine input from level-based gas extinction and particle extinction and absorption.
Parameters
[out] dtauc Optical depths for all layers.
[out] ssalb Single scattering albedos for all layers.
[in] ext_bulk_gas See get_gasoptprop.
[in] ext_bulk_par See get_paroptprop.
[in] abs_bulk_par See get_paroptprop.
[in] z_profile Profile of geometrical altitudes.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 396 of file disort.cc.
References abs, ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by run_cdisort().
get_gasoptprop()
void get_gasoptprop (Workspace & ws, MatrixView ext_bulk_gas, const Agenda & propmat_clearsky_agenda, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstVectorView p_grid, ConstVectorView f_grid)
get_gasoptprop.
Derives level-based gas bulk optical properties (extinction).
Parameters
[in,out] ws Current workspace.
[out] ext_bulk_gas Gas bulk extinction (all levels & freqs).
[in] propmat_clearsky_agenda As the WSV.
[in] t_profile Temperature profile
[in] vmr_profiles VMR profiles
[in] p_grid As the WSV.
[in] f_grid As the WSV.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 268 of file disort.cc.
References joker, PropagationMatrix::Kjj(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and propmat_clearsky_agendaExecute().
Referenced by run_cdisort().
get_paroptprop()
void get_paroptprop (MatrixView ext_bulk_par, MatrixView abs_bulk_par, const ArrayOfArrayOfSingleScatteringData & scat_data, ConstMatrixView pnd_profiles, ConstVectorView t_profile, ConstVectorView DEBUG_ONLYp_grid, const ArrayOfIndex & cloudbox_limits, ConstVectorView f_grid)
Definition at line 321 of file disort.cc.
References DEBUG_ONLY, ConstTensor4View::nbooks(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), opt_prop_Bulk(), opt_prop_NScatElems(), and opt_prop_ScatSpecBulk().
Referenced by run_cdisort().
get_parZ()
void get_parZ (Tensor3 & pha_bulk_par, const ArrayOfArrayOfSingleScatteringData & scat_data, ConstMatrixView pnd_profiles, ConstVectorView t_profile, ConstVectorView pfct_angs, const ArrayOfIndex & cloudbox_limits)
get_parZ.
Derives level-based particle bulk phase matrix Z (Csca scaled). NOTE: Provided on ssd's freq grid (i.e. for nf=1 only of ssd.f_grid.nelem==1) in order to avoid duplicate calculations in get_pmom (instead we duplicate the results there to the RT calc's f_grid).
Parameters
[out] pha_bulk_par Particle bulk phase function (all levels & ssd freqs).
[out] pfct_angs Angular grid of pfct_bulk_par.
[in] scat_data As the WSV.
[in] pnd_profiles PND profiles.
[in] t_profile Temperature profile.
[in] p_grid As the WSV.
[in] cloudbox_limits As the WSV.
[in] ext_bulk_par See get_paroptprop.
[in] abs_bulk_par See get_paroptprop.
[in] nang Number of angular grid points in pfct_angs. If<0,
pfct_angs is taken from scat_data (the finest za_grid used over the scat elems), else an equidistant grid with nang grid points is used.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 464 of file disort.cc.
References joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), pha_mat_Bulk(), pha_mat_NScatElems(), and pha_mat_ScatSpecBulk().
Referenced by run_cdisort().
get_pfct()
void get_pfct (Tensor3 & pfct_bulk_par, ConstTensor3View & pha_bulk_par, ConstMatrixView ext_bulk_par, ConstMatrixView abs_bulk_par, const ArrayOfIndex & cloudbox_limits)
get_pfct.
Derives layer averaged particle bulk phase function P (4Pi scaled) NOTE: Provided on ssd's freq grid (i.e. for nf=1 only if ssd.f_grid.nelem==1) in order to avoid duplicate calculations in get_pmom (instead we duplicate the results there to the RT calc's f_grid).
Parameters
[out] pfct_bulk_par Particle bulk phase function (all levels & ssd freqs).
[in] pha_bulk_par See get_parZ.
[in] ext_bulk_par See get_paroptprop.
[in] abs_bulk_par See get_paroptprop.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 516 of file disort.cc.
References joker, ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and PI.
Referenced by run_cdisort().
get_pmom()
void get_pmom (Tensor3View pmom, ConstTensor3View pfct_bulk_par, ConstVectorView pfct_angs, const Index & Nlegendre)
get_pmom
Calculates Legendre moments of the layer averaged phase functionss (pmom) as required as DISORT subroutine input from level-based bulk particle phase function (4-Pi normalized scalar phase matrix).
Parameters
[out] pmom Legendre moments for all layers.
[in] pfct_bulk_par See get_pfct.
[in] pfct_angs See get_parZ.
[in] Nlegendre Number of Legendre moments to derive.
Author
Jana Mendrok
Date
2018-04-04
Definition at line 551 of file disort.cc.
References abs, joker, ConstTensor3View::ncols(), ConstVectorView::nelem(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and PI.
Referenced by run_cdisort().
init_ifield()
void init_ifield (Tensor7 & cloudbox_field, const Vector & f_grid, const ArrayOfIndex & cloudbox_limits, const Index & nang, const Index & stokes_dim)
init_ifield.
Initialize cloudbox_field with the right size and NaN values.
Parameters
[out] cloudbox_field As the WSV.
[in] f_grid As the WSV.
[in] cloudbox_limits As the WSV.
[in] nang Total number of angles with RT output.
[in] stokes_dim As the WSV.
Author
Jana Mendrok
Date
2017-03-06
Definition at line 207 of file disort.cc.
References ConstVectorView::nelem(), and Tensor7::resize().
Referenced by DisortCalc(), and DisortCalcWithARTSSurface().
reduced_1datm()
void reduced_1datm (Vector & p, Vector & z, Vector & t, Matrix & vmr, Matrix & pnd, ArrayOfIndex & cboxlims, Index & ncboxremoved, ConstVectorView p_grid, ConstVectorView z_profile, const Numeric & z_surface, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstMatrixView pnd_profiles, const ArrayOfIndex & cloudbox_limits)
reduced_1datm
Crops a 1D atmosphere, to create an atmosphere where the surface is placed at p_grid[0]. Developed to work with DISORT and RT4.
Parameters
[out] p New pressure grid,
[out] z New profile of geometrical altitudes.
[out] t New temperature profile,
[out] vmr New VMR profiles.
[out] pnd New PND profiles.
[out] cboxlims Adjusted version of cloudbox_limits.
[out] ncboxremoved Number of levels inside cloudbox removed
[in] p_grid Original pressure grid
[in] z_profile Original profile of geometric altitudes.
[in] z_surface Surface altitude.
[in] t_profile Original temperature profile.
[in] vmr_profiles Original VMR profiles.
[in] pnd_profiles Original PND profiles.
[in] cloudbox_limits Original cloudbox limits
Author
Patrick Eriksson
Date
2019-10-22
Definition at line 693 of file disort.cc.
References abs.
Referenced by run_cdisort().
run_cdisort()
void run_cdisort (Workspace & ws, Tensor7 & cloudbox_field, ConstVectorView f_grid, ConstVectorView p_grid, ConstVectorView z_profile, const Numeric & z_surface, ConstVectorView t_profile, ConstMatrixView vmr_profiles, ConstMatrixView pnd_profiles, const ArrayOfArrayOfSingleScatteringData & scat_data, const Agenda & propmat_clearsky_agenda, const ArrayOfIndex & cloudbox_limits, const Numeric & surface_skin_t, const Vector & surface_scalar_reflectivity, ConstVectorView za_grid, const Index & nstreams, const Index & Npfct, const Index & quiet, const Verbosity & verbosity)
Calculate doit_i_feild with Disort.
Prepares actual input variables for Disort, runs it, and sorts the output into cloudbox_field.
This version uses the C implementation of Disort based on ::run_disort.
Altitudes, temperatures, VMRs and PNDs shall be provided with lat and lon dimensions removed
Parameters
[in,out] ws Current workspace
[out] cloudbox_field Radiation field
[in] f_grid Frequency grid
[in] p_grid Pressure grid
[in] z_profile Profile of geometric altitudes.
[in] z_surface Surface altitude.
[in] t_profile Temperature profile.
[in] vmr_profiles VMR profiles.
[in] pnd_profiles PND profiles.
[in] scat_data Array of single scattering data
[in] propmat_clearsky_agenda calculates the absorption coefficient matrix
[in] cloudbox_limits Cloudbox limits
[in] surface_skin_t Surface skin temperature
[in] surface_scalar_reflectivity Surface scalar reflectivity
[in] za_grid Zenith angle grid
[in] nstreams Number of quadrature angles (both hemispheres).
[in] Npfct Number of angular grid points to calculate bulk phase function
[in] quiet Silence warnings
[in] verbosity Verbosity setting
Author
Oliver Lemke
Date
2019-09-19
Definition at line 769 of file disort.cc.
References COSMIC_BG_TEMP, disort_verbosity, get_angs(), get_dtauc_ssalb(), get_gasoptprop(), get_paroptprop(), get_parZ(), get_pfct(), get_pmom(), joker, Array< base >::nelem(), ConstVectorView::nelem(), PI, reduced_1datm(), and SPEED_OF_LIGHT.
Referenced by DisortCalc(), and DisortCalcWithARTSSurface().
surf_albedoCalc()
void surf_albedoCalc (Workspace & ws, VectorView albedo, Numeric & btemp, const Agenda & surface_rtprop_agenda, ConstVectorView f_grid, ConstVectorView scat_za_grid, const Numeric & surf_alt, const Verbosity & verbosity)
Surface albed.
Computes surface albedo for using ARTS' surface with DISORT.
Parameters
[in,out] ws The workspace
[out] albedo The computed albedo
[out] btemp Upw. bts.
[in] surface_rtprop_agenda Agenda to compute surf. props
[in] f_grid Frequency grid
[in] scat_za_grid Zenith angle grid
[in] surface_alt surface altitude
[in] verbosity
Author
Patrick Eriksson
Date
2019-10-22
Definition at line 960 of file disort.cc.
References chk_not_empty(), CREATE_OUT2, is_same_within_epsilon(), joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and surface_rtprop_agendaExecute().
Referenced by DisortCalcWithARTSSurface().
Variable Documentation
COSMIC_BG_TEMP
const Numeric COSMIC_BG_TEMP extern
Referenced by run_cdisort().
DEG2RAD
const Numeric DEG2RAD extern
disort_verbosity
thread_local Verbosity disort_verbosity
Definition at line 631 of file disort.cc.
Referenced by c_errmsg(), c_write_bad_var(), c_write_too_small_dim(), and run_cdisort().
PI
const Numeric PI extern
Referenced by get_pfct(), get_pmom(), and run_cdisort().
PLANCK_CONST
const Numeric PLANCK_CONST extern
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by run_cdisort().