ARTS: energylevelmap.cc File Reference
energylevelmap.cc File Reference
#include "energylevelmap.h"
#include "special_interp.h"
Functions
EnergyLevelMapType string2energylevelmaptype (const String &s)
String energylevelmaptype2string (EnergyLevelMapType type)
std::ostream & operator<< (std::ostream &os, const EnergyLevelMap &elm)
Function Documentation
energylevelmaptype2string()
String energylevelmaptype2string (EnergyLevelMapType type)
Definition at line 202 of file energylevelmap.cc.
References None_t, Numeric_t, Tensor3_t, Hitran::type, and Vector_t.
Referenced by operator<<(), and xml_write_to_stream().
operator<<()
std::ostream& operator<< (std::ostream & os, const EnergyLevelMap & elm)
Definition at line 217 of file energylevelmap.cc.
References EnergyLevelMap::Data(), EnergyLevelMap::Energies(), energylevelmaptype2string(), EnergyLevelMap::Levels(), and EnergyLevelMap::Type().
string2energylevelmaptype()
EnergyLevelMapType string2energylevelmaptype (const String & s)
Definition at line 187 of file energylevelmap.cc.
References ARTS_USER_ERROR, None_t, Numeric_t, Tensor3_t, and Vector_t.
Referenced by xml_read_from_stream().