ARTS: energylevelmap.h File Reference
energylevelmap.h File Reference
Class to map energy levels.
#include "absorptionlines.h"
#include "matpackIV.h"
#include "mystring.h"
#include "quantum.h"
Classes
struct Output2
struct Output4
class EnergyLevelMap
Enumerations
enum EnergyLevelMapType { EnergyLevelMapType::Tensor3_t, EnergyLevelMapType::Vector_t, EnergyLevelMapType::Numeric_t, EnergyLevelMapType::None_t }
Functions
EnergyLevelMapType string2energylevelmaptype (const String &s)
String energylevelmaptype2string (EnergyLevelMapType type)
std::ostream & operator<< (std::ostream &os, const EnergyLevelMap &elm)
Detailed Description
Class to map energy levels.
Author
Richard Larsson
Date
2019-10-28
Definition in file energylevelmap.h.
Enumeration Type Documentation
EnergyLevelMapType
enum EnergyLevelMapType strong
Enumerator
Tensor3_t
Vector_t
Numeric_t
None_t
Definition at line 49 of file energylevelmap.h.
Function Documentation
energylevelmaptype2string()
String energylevelmaptype2string (EnergyLevelMapType type)
Definition at line 177 of file energylevelmap.cc.
References Numeric_t, Tensor3_t, and Vector_t.
Referenced by operator<<(), and xml_write_to_stream().
operator<<()
std::ostream& operator<< (std::ostream & os, const EnergyLevelMap & elm)
Definition at line 192 of file energylevelmap.cc.
References EnergyLevelMap::Data(), EnergyLevelMap::Energies(), energylevelmaptype2string(), EnergyLevelMap::Levels(), and EnergyLevelMap::Type().
string2energylevelmaptype()
EnergyLevelMapType string2energylevelmaptype (const String & s)
Definition at line 160 of file energylevelmap.cc.
References Numeric_t, Tensor3_t, and Vector_t.
Referenced by xml_read_from_stream().