ARTS: fastem.cc File Reference
fastem.cc File Reference
This file contains functions that are adapted from FASTEM code which is used to calculate surface emissivity.
#include <cmath>
#include <stdexcept>
#include "complex.h"
#include "exceptions.h"
#include "matpackI.h"
Functions
void rttov_fastem5_ (const Index &fastem_version, const Numeric &frequency, const Numeric &za, const Numeric &temperature, const Numeric &salinity, const Numeric &wind_speed, Numeric *emissivity, Numeric *reflectivity, const Numeric &transmittance, const Numeric &rel_azimuth)
void fastem (Vector &emissivity, Vector &reflectivity, const Numeric frequency, const Numeric za, const Numeric temperature, const Numeric salinity, const Numeric wind_speed, const Numeric transmittance, const Numeric rel_azimuth, const Index fastem_version)
Calculate the surface emissivity using FASTEM.
Variables
const Numeric PI
const Numeric DEG2RAD
const Numeric RAD2DEG
Detailed Description
This file contains functions that are adapted from FASTEM code which is used to calculate surface emissivity.
Author
Sreerekha Ravi rekha.nosp@m.@sat.nosp@m..phys.nosp@m.ik.u.nosp@m.ni-br.nosp@m.emen.nosp@m..de
Date
Tue Aug 10 15:16:31 2004
Definition in file fastem.cc.
Function Documentation
fastem()
void fastem (Vector & emissivity, Vector & reflectivity, const Numeric frequency, const Numeric za, const Numeric temperature, const Numeric salinity, const Numeric wind_speed, const Numeric transmittance, const Numeric rel_azimuth, const Index fastem_version)
Calculate the surface emissivity using FASTEM.
Calculate surface emissivity using the FASTEM model from RTTOV.
This is a direct interface to the code from RTTOV. No checkls of input is made, to obtain this feature use FastemStandAlone that is also handling multiple frequencies.
Parameters
[out] emissivity Calculated surface emissivity
[out] reflectivity Calculated surface reflectivity
[in] frequency Frequency [Hz]
[in] za Zenith angle of line-of-sigh
[in] temperature Temperature
[in] salinity Salinity [0-1]
[in] wind_speed Wind speed
[in] transmittance Transmittance along downwelling direction.
[in] rel_azimuth Relative azimuth angle (may not be used)
[in] fastem_version FASTEM version
Author
Oliver Lemke
Date
2014-12-09
Definition at line 107 of file fastem.cc.
References VectorView::get_c_array(), Vector::resize(), and rttov_fastem5_().
rttov_fastem5_()
void rttov_fastem5_ (const Index & fastem_version, const Numeric & frequency, const Numeric & za, const Numeric & temperature, const Numeric & salinity, const Numeric & wind_speed, Numeric * emissivity, Numeric * reflectivity, const Numeric & transmittance, const Numeric & rel_azimuth)
Definition at line 69 of file fastem.cc.
Referenced by fastem().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
PI
const Numeric PI extern
RAD2DEG
const Numeric RAD2DEG extern