ARTS: file.h File Reference
file.h File Reference
This file contains basic functions to handle ASCII files.
#include <fstream>
#include "messages.h"
#include "mystring.h"
Classes
class double_istream
Input stream class for doubles that correctly handles nan and inf.
class double_imanip
Input manipulator class for doubles to enable nan and inf parsing.
Functions
void filename_ascii (String &filename, const String &varname)
Gives the default file name for the ASCII formats.
void filename_bin (String &filename, const String &varname)
void open_output_file (std::ofstream &file, const String &name)
void cleanup_output_file (std::ofstream &file, const String &name)
void open_input_file (std::ifstream &file, const String &name)
void read_text_from_stream (ArrayOfString &text, std::istream &is)
void read_text_from_file (ArrayOfString &text, const String &name)
Reads an ASCII file and appends the contents to the String vector text.
void replace_all (String &s, const String &what, const String &with)
Replace all occurances of ‘what’ in ‘s’ with ‘with’.
int check_newline (const String &s)
Checks if there is exactly one newline character at the end of the string.
bool file_exists (const String &filename)
Checks if the given file exists.
bool find_file (ArrayOfString &matches, const String &filename, const ArrayOfString &paths, const ArrayOfString &extensions={""})
Searches through paths for a file with a matching name.
void find_xml_file (String &filename, const Verbosity &verbosity)
Find an xml file.
bool find_xml_file_existence (String &filename)
As find_xml_file but does not throw in the main body.
String expand_path (const String &path)
String add_basedir (const String &path)
void get_dirname (String &dirname, const String &path)
Return the parent directory of a path.
void list_directory (ArrayOfString &files, String dirname)
Return list of files in directory.
void make_filename_unique (String &filename, const String &extension="")
Make filename unique.
const double_imanip & operator>> (std::istream &in, const double_imanip &dm)
Detailed Description
This file contains basic functions to handle ASCII files.
Author
Patrick Eriksson
Date
2000-10-28
Definition in file file.h.
Function Documentation
add_basedir()
String add_basedir (const String & path)
Adds base directory to the given path if it is a relative path.
Parameters
[in] path String with path
Returns
Expanded path.
Author
Oliver Lemke
Date
2012-05-01
Definition at line 499 of file file.cc.
References expand_path(), my_basic_string< charT >::nelem(), Parameters::outdir, and parameters.
Referenced by arts_exit(), arts_exit_with_error_message(), nca_write_to_file(), open_output_file(), and xml_write_to_file().
check_newline()
int check_newline (const String & s)
Checks if there is exactly one newline character at the end of the string.
Parameters
s The String to check.
Returns
Error code (0=ok, 1=empty, 2=missing, 3=extra newline
Author
Oliver Lemke
Definition at line 271 of file file.cc.
References d, and replace_all().
Referenced by md_sanity_checks().
cleanup_output_file()
void cleanup_output_file (std::ofstream & file, const String & name)
expand_path()
String expand_path (const String & path)
Expands the ~ to home directory location in given path.
Parameters
[in] path String with path
Returns
Expanded path.
Author
Oliver Lemke
Date
2010-04-30
Definition at line 480 of file file.cc.
References my_basic_string< charT >::nelem().
Referenced by add_basedir(), find_file(), nca_read_from_file(), and open_input_file().
file_exists()
bool file_exists (const String & filename)
Checks if the given file exists.
Parameters
filename File to check.
Returns
Error code (true = file exists, false = file doesn't exist)
Author
Oliver Lemke
Definition at line 303 of file file.cc.
Referenced by find_file(), make_filename_unique(), and ScatSpeciesScatAndMetaRead().
filename_ascii()
void filename_ascii (String & filename, const String & varname)
Gives the default file name for the ASCII formats.
The default name is only used if the file name is empty.
Parameters
filename Output: file name
varname variable name
Author
Patrick Eriksson
Date
2000-11-01
Definition at line 73 of file file.cc.
References out_basename.
filename_bin()
void filename_bin (String & filename, const String & varname)
find_file()
bool find_file (ArrayOfString & matches, const String & filename, const ArrayOfString & paths, const ArrayOfString & extensions)
Searches through paths for a file with a matching name.
If the filename starts with '/', the search path is ignored.
Parameters
[in,out] matches Matching files are appended to this list.
[in] filename File to find.
[in] paths List of paths to look in for the file.
[in] extensions List of extensions to add to base filename.
Returns
Error code (true = file found, false = file not found)
Author
Oliver Lemke
Definition at line 353 of file file.cc.
References expand_path(), file_exists(), get_absolute_path(), my_basic_string< charT >::nelem(), and Array< base >::nelem().
Referenced by find_xml_file(), find_xml_file_existence(), open_input_file(), and ArtsParser::parse_agenda().
find_xml_file()
void find_xml_file (String & filename, const Verbosity & verbosity)
Find an xml file.
If it doesn't exist in the current directory, also search the include and data path. Also tests if a compressed version exists.
The filename will be modified to contain the full path to the found match.
Parameters
[in,out] filename File to check.
[in] verbosity Verbosity
Exceptions
runtime_error if file is not found.
Author
Oliver Lemke
Definition at line 414 of file file.cc.
References CREATE_OUT1, Parameters::datapath, find_file(), Parameters::includepath, Array< base >::nelem(), and parameters.
Referenced by abs_speciesDefineAllInScenario(), ScatSpeciesScatAndMetaRead(), xml_find_and_open_input_file(), and xml_read_from_file().
find_xml_file_existence()
bool find_xml_file_existence (String & filename)
As find_xml_file but does not throw in the main body.
The filename will be modified to contain the full path to the found match if there is a match
Parameters
[in,out] filename File to check.
Returns
If file is found
Author
Oliver Lemke
Definition at line 452 of file file.cc.
References Parameters::datapath, find_file(), Parameters::includepath, Array< base >::nelem(), and parameters.
get_dirname()
void get_dirname (String & dirname, const String & path)
Return the parent directory of a path.
Extracts the parent directory part of the given path.
Parameters
[out] dirname Parent directory of path
[in] path Path
Author
Oliver Lemke
Definition at line 519 of file file.cc.
References my_basic_string< charT >::nelem(), Array< base >::nelem(), and my_basic_string< charT >::split().
Referenced by get_parameters(), and ArtsParser::parse_agenda().
list_directory()
void list_directory (ArrayOfString & files, String dirname)
Return list of files in directory.
Returns list of all files in the given path.
Parameters
[out] files List of files
[in] dirname Parent directory of path
Author
Oliver Lemke
Definition at line 543 of file file.cc.
Referenced by abs_cia_dataReadFromCIA().
make_filename_unique()
void make_filename_unique (String & filename, const String & extension)
Make filename unique.
Checks if a file (or a gzipped version of it) with the given name already exists und appends a unique number to the filename if necessary
Parameters
[in,out] filename Filename
[in] extension Optional, number is inserted before the extension
Returns
Author
Oliver Lemke
Definition at line 571 of file file.cc.
References file_exists().
Referenced by xml_write_to_file().
open_input_file()
void open_input_file (std::ifstream & file, const String & name)
open_output_file()
void open_output_file (std::ofstream & file, const String & name)
operator>>()
const double_imanip& operator>> (std::istream & in, const double_imanip & dm)
Definition at line 125 of file file.cc.
read_text_from_file()
void read_text_from_file (ArrayOfString & text, const String & name)
Reads an ASCII file and appends the contents to the String vector text.
This uses the function
See also
read_text_from_stream. TEXT IS NOT OVERWRITTEN, BUT APPENDED!
Parameters
text Output. The contents fo the file
name Name of file to read
Exceptions
IOError
Version
1
Author
Stefan Buehler
Definition at line 225 of file file.cc.
References open_input_file(), read_text_from_stream(), and x.
Referenced by SourceText::AppendFile().
read_text_from_stream()
void read_text_from_stream (ArrayOfString & text, std::istream & is)
replace_all()
void replace_all (String & s, const String & what, const String & with)
Replace all occurances of ‘what’ in ‘s’ with ‘with’.
Parameters
s Output. The String to act on.
what The String to replace.
with The replacement.
Author
Stefan Buehler
Definition at line 253 of file file.cc.
References my_basic_string< charT >::npos.
Referenced by check_newline().