ARTS: gen_auto_partfun.cc File Reference
gen_auto_partfun.cc File Reference
#include <filesystem>
#include <fstream>
#include <limits>
#include <map>
#include <vector>
#include "debug.h"
#include "gridded_fields.h"
#include "species.h"
#include "xml_io_partfun.h"
Classes
struct PrintData
Contains the partition function data in a simple format.
Functions
std::pair< std::string_view, std::string_view > split_filename_species (const std::string_view isot)
std::pair< Species::Species, PrintData > gen_fil (std::filesystem::path fil)
std::map< Species::Species, std::vector< PrintData > > gen_dir (std::filesystem::path dir)
void print_data (const PrintData &data)
void print_method (const PrintData &data)
void print_auto_partfun_h (const std::map< Species::Species, std::vector< PrintData >> &data)
int main (int argc, char **argv)
Function Documentation
gen_dir()
std::map<Species::Species, std::vector<PrintData> > gen_dir (std::filesystem::path dir)
Definition at line 46 of file gen_auto_partfun.cc.
References a, ARTS_USER_ERROR, b, data, Zeeman::end(), and gen_fil().
Referenced by main().
gen_fil()
std::pair<Species::Species, PrintData> gen_fil (std::filesystem::path fil)
Definition at line 27 of file gen_auto_partfun.cc.
References ARTS_USER_ERROR, ARTS_USER_ERROR_IF, PrintData::data, PartitionFunctions::data_read_file(), good_enum(), PrintData::name, and split_filename_species().
Referenced by gen_dir().
main()
int main (int argc, char ** argv)
All calculations are done on the directory data
Definition at line 153 of file gen_auto_partfun.cc.
References ARTS_USER_ERROR_IF, gen_dir(), and print_auto_partfun_h().
Referenced by bad_propmat().
print_auto_partfun_h()
void print_auto_partfun_h (const std::map< Species::Species, std::vector< PrintData >> & data)
Definition at line 82 of file gen_auto_partfun.cc.
References data, print_data(), and print_method().
Referenced by main().
print_data()
void print_data (const PrintData & data)
Definition at line 72 of file gen_auto_partfun.cc.
References data.
Referenced by print_auto_partfun_h().
print_method()
void print_method (const PrintData & data)
Definition at line 77 of file gen_auto_partfun.cc.
References data.
Referenced by print_auto_partfun_h().
split_filename_species()
std::pair<std::string_view, std::string_view> split_filename_species (const std::string_view isot)
Definition at line 20 of file gen_auto_partfun.cc.
References isot, min, and ARTS::Var::x().
Referenced by gen_fil().