ARTS: grids.h File Reference
grids.h File Reference
#include <array>
#include <iostream>
#include <vector>
Classes
class Grid< b, n >
Row-major grid creation.
class FixedGrid< b, Sizes >
Row-major fixed grid creation.
Functions
template<typename... Inds>
constexpr std::size_t mul (Inds... inds) noexcept
template<std::size_t N>
constexpr std::size_t mul (const std::array< std::size_t, N > &arr) noexcept
template<typename... Inds>
constexpr std::array< std::size_t, sizeof...(Inds)> gridsize_from_index (Inds... inds) noexcept
template<std::size_t N>
constexpr std::size_t index_from_gridsize (std::array< std::size_t, N > gridsize, std::array< std::size_t, N > inds) noexcept
Function Documentation
gridsize_from_index()
template<typename... Inds> constexpr std::array<std::size_t, sizeof...(Inds)> gridsize_from_index (Inds... inds) constexpr noexcept
Compute gridsizes from indices
Definition at line 28 of file grids.h.
Referenced by FixedGrid< b, Sizes >::operator()().
index_from_gridsize()
template<std::size_t N> constexpr std::size_t index_from_gridsize (std::array< std::size_t, N > gridsize, std::array< std::size_t, N > inds) constexpr noexcept
Compute gridsizes from indices
Definition at line 43 of file grids.h.
References N.
Referenced by Grid< b, n >::operator()(), and FixedGrid< b, Sizes >::operator()().
mul() [1/2]
template<std::size_t N> constexpr std::size_t mul (const std::array< std::size_t, N > & arr) constexpr noexcept
Compute the multiplication of all inds in arr
Definition at line 16 of file grids.h.
References N.
mul() [2/2]
template<typename... Inds> constexpr std::size_t mul (Inds... inds) constexpr noexcept
Compute the multiplication of all inds
Definition at line 10 of file grids.h.
Referenced by cumulative_transmission().