ARTS: groups.cc File Reference
groups.cc File Reference
Defines workspace variable groups.
#include <map>
#include "array.h"
#include "arts.h"
#include "mystring.h"
#include "wsv_aux.h"
Namespaces
global_data
Functions
void define_valid_keyword_groups ()
void define_wsv_group_map ()
void define_wsv_group_names ()
Define the array of workspace variable group names.
bool is_valid_keyword_group (const Index group)
void get_wsv_group_ids (ArrayOfIndex &ids, String name)
Returns list of ids of the given group names.
bool is_agenda_group_id (const Index group)
Check if group is an agenda group.
Index get_wsv_group_id (const String &name)
Returns the id of the given group.
String get_array_groups_as_string (bool basetype_is_group, bool return_basetype_only)
Return string list of array types.
Variables
ArrayOfIndex valid_keyword_groups
Detailed Description
Defines workspace variable groups.
If you want to add new workspace variable groups you have to do it in this file. This is used by the program make_wsv_group_h to generate the header file wsv_group.h
Author
Stefan Buehler
Date
2000-08-04
Definition in file groups.cc.
Function Documentation
define_valid_keyword_groups()
void define_valid_keyword_groups ()
Definition at line 47 of file groups.cc.
References get_wsv_group_id(), and valid_keyword_groups.
Referenced by define_wsv_group_names().
define_wsv_group_map()
void define_wsv_group_map ()
Definition at line 57 of file groups.cc.
References Array< base >::nelem(), global_data::wsv_group_names, and global_data::WsvGroupMap.
Referenced by define_wsv_group_names().
define_wsv_group_names()
void define_wsv_group_names ()
Define the array of workspace variable group names.
This defines the global variable wsv_group_names. It is used in two different programs:
In arts.
In make_wsv_group_h.
Author
Stefan Buehler
Date
2000-08-04
Definition at line 77 of file groups.cc.
References define_valid_keyword_groups(), define_wsv_group_map(), and global_data::wsv_group_names.
Referenced by ARTS::init(), InteractiveWorkspace::initialize(), and main().
get_array_groups_as_string()
String get_array_groups_as_string (bool basetype_is_group, bool return_basetype_only)
Return string list of array types.
Definition at line 234 of file groups.cc.
References get_wsv_group_id(), Array< base >::nelem(), and global_data::wsv_group_names.
Referenced by define_md_data_raw().
get_wsv_group_id()
Index get_wsv_group_id (const String & name)
Returns the id of the given group.
Definition at line 225 of file groups.cc.
References global_data::WsvGroupMap.
Referenced by define_valid_keyword_groups(), expand_md_data_raw_to_md_data(), get_array_groups_as_string(), get_wsv_group_ids(), is_agenda_group_id(), main(), MdRecord::MdRecord(), operator<<(), option_input(), option_methods(), ArtsParser::parse_agenda(), ArtsParser::parse_generic_input(), ArtsParser::parse_generic_output(), ArtsParser::read_name_or_value(), ArtsParser::set_gin_to_default(), MdRecord::subst_any_with_group(), MdRecord::subst_any_with_specific_group(), ArtsParser::tasklist_insert_set_delete(), and WsvRecord::WsvRecord().
get_wsv_group_ids()
void get_wsv_group_ids (ArrayOfIndex & ids, String name)
Returns list of ids of the given group names.
Definition at line 188 of file groups.cc.
References get_wsv_group_id(), and my_basic_string< charT >::nelem().
Referenced by MdRecord::MdRecord().
is_agenda_group_id()
bool is_agenda_group_id (const Index group)
Check if group is an agenda group.
Definition at line 220 of file groups.cc.
References get_wsv_group_id().
Referenced by main(), write_method_header(), and write_method_header_documentation().
is_valid_keyword_group()
bool is_valid_keyword_group (const Index group)
Definition at line 180 of file groups.cc.
References Array< base >::nelem(), and valid_keyword_groups.
Variable Documentation
valid_keyword_groups
ArrayOfIndex valid_keyword_groups
Groups that can be used as keywords
Definition at line 45 of file groups.cc.
Referenced by define_valid_keyword_groups(), and is_valid_keyword_group().