ARTS: hitran_xsec.cc File Reference
hitran_xsec.cc File Reference
#include "arts.h"
#include "interpolation_lagrange.h"
#include "absorption.h"
#include "check_input.h"
#include "hitran_xsec.h"
Functions
Numeric func_2straights (const Numeric x, const Vector &coeffs)
Numeric lorentz_pdf (const Numeric x, const Numeric x0, const Numeric gamma)
void convolve (Vector &result, const ConstVectorView &xsec, const ConstVectorView &lorentz)
Index hitran_xsec_get_index (const ArrayOfXsecRecord &xsec_data, const Species::Species species)
Get the index in hitran_xsec_data for the given species.
std::ostream & operator<< (std::ostream &os, const XsecRecord &xd)
Variables
const Numeric PI
Function Documentation
convolve()
void convolve (Vector & result, const ConstVectorView & xsec, const ConstVectorView & lorentz)
Definition at line 59 of file hitran_xsec.cc.
References ConstVectorView::nelem(), Zeeman::sum(), and temp.
Referenced by XsecRecord::Extract().
func_2straights()
Numeric func_2straights (const Numeric x, const Vector & coeffs)
Definition at line 42 of file hitran_xsec.cc.
References ARTS_ASSERT, ConstVectorView::nelem(), and ARTS::Var::x().
Referenced by XsecRecord::Extract().
hitran_xsec_get_index()
Index hitran_xsec_get_index (const ArrayOfXsecRecord & xsec_data, const Species::Species species)
Get the index in hitran_xsec_data for the given species.
Parameters
[in] hitran_xsec_data Hitran Xsec data array
[in] species Species name
Returns
Index of this species in hitran_xsec_data. -1 if not found.
Definition at line 331 of file hitran_xsec.cc.
References Array< base >::nelem().
Referenced by abs_xsec_per_speciesAddHitranXsec().
lorentz_pdf()
Numeric lorentz_pdf (const Numeric x, const Numeric x0, const Numeric gamma)
Definition at line 48 of file hitran_xsec.cc.
References PI, and ARTS::Var::x().
Referenced by XsecRecord::Extract().
operator<<()
std::ostream& operator<< (std::ostream & os, const XsecRecord & xd)
Definition at line 339 of file hitran_xsec.cc.
References XsecRecord::Species().
Variable Documentation
PI
const Numeric PI extern
Referenced by lorentz_pdf().