ARTS: hitran_xsec.h File Reference
hitran_xsec.h File Reference
Methods and classes for HITRAN absorption cross section data.
#include "arts.h"
#include "array.h"
#include "bifstream.h"
#include "matpackI.h"
#include "messages.h"
#include "mystring.h"
Classes
class XsecRecord
Typedefs
typedef Array< XsecRecord > ArrayOfXsecRecord
Functions
Index hitran_xsec_get_index (const ArrayOfXsecRecord &xsec_data, const Index species)
Get the index in hitran_xsec_data for the given species.
std::ostream & operator<< (std::ostream &os, const XsecRecord &xd)
Detailed Description
Methods and classes for HITRAN absorption cross section data.
Author
Oliver Lemke olive.nosp@m.r.le.nosp@m.mke@u.nosp@m.ni-h.nosp@m.ambur.nosp@m.g.de
Date
2018-01-08
Definition in file hitran_xsec.h.
Typedef Documentation
ArrayOfXsecRecord
typedef Array<XsecRecord> ArrayOfXsecRecord
Definition at line 126 of file hitran_xsec.h.
Function Documentation
hitran_xsec_get_index()
Index hitran_xsec_get_index (const ArrayOfXsecRecord & xsec_data, const Index species)
Get the index in hitran_xsec_data for the given species.
Parameters
[in] hitran_xsec_data Hitran Xsec data array
[in] species Species name
Returns
Index of this species in hitran_xsec_data. -1 if not found.
Definition at line 331 of file hitran_xsec.cc.
References Array< base >::nelem(), and Species.
Referenced by abs_xsec_per_speciesAddHitranXsec().
operator<<()
std::ostream& operator<< (std::ostream & os, const XsecRecord & xd)
Definition at line 339 of file hitran_xsec.cc.
References XsecRecord::Species().