ARTS: interactive_workspace.h File Reference
interactive_workspace.h File Reference
This file contains all declarations of the ARTS C API.
#include "agenda_class.h"
#include "workspace_ng.h"
Classes
class Callback
External callbacks.
class InteractiveWorkspace
Interactive ARTS workspace.
Variables
void(* getaways [])(Workspace &, const MRecord &)
Detailed Description
This file contains all declarations of the ARTS C API.
This file contains the declaration and partly the implementation of the InteractiveWorkspace class.
Author
Simon Pfreundschuh simon.nosp@m..pfr.nosp@m.eunds.nosp@m.chuh.nosp@m.@chal.nosp@m.mers.nosp@m..se
Date
2017-08-21
Author
Simon Pfreundschuh simon.nosp@m..pfr.nosp@m.eunds.nosp@m.chuh.nosp@m.@chal.nosp@m.mers.nosp@m..se
Date
2017-08-21
Definition in file interactive_workspace.h.
Variable Documentation
getaways
void(* getaways[])(Workspace &, const MRecord &) extern
Definition at line 21480 of file auto_md.cc.
Referenced by Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), and InteractiveWorkspace::initialize().