ARTS: interactive_workspace.cc File Reference
interactive_workspace.cc File Reference
#include "interactive_workspace.h"
#include "matpackI.h"
#include "matpackII.h"
#include "matpackIII.h"
#include "matpackIV.h"
#include "matpackV.h"
#include "matpackVI.h"
#include "matpackVII.h"
#include "methods.h"
#include "workspace_memory_handler.h"
#include "agenda_class.h"
#include "agenda_record.h"
Namespaces
global_data
Functions
Index get_wsv_id (const char *)
Get index of WSV.
void callback_getaway (Workspace &ws, const MRecord &mr)
Variables
Verbosity verbosity_at_launch
The global message verbosity settings:
std::string string_buffer
MdRecord callback_mr
Function Documentation
callback_getaway()
void callback_getaway (Workspace & ws, const MRecord & mr)
Definition at line 32 of file interactive_workspace.cc.
References InteractiveWorkspace::execute_callback(), and MRecord::SetValue().
Referenced by InteractiveWorkspace::initialize().
get_wsv_id()
Index get_wsv_id (const char * name)
Get index of WSV.
Returns the index the Workspace of the given WSV.
Convenience function which can be called from within the debugger because it takes a plain char pointer instead of a String object as input.
Parameters
[in] name WSV name
Returns
Index in Workspace
Author
Oliver Lemke
Definition at line 5801 of file workspace.cc.
Referenced by InteractiveWorkspace::execute_workspace_method().
Variable Documentation
callback_mr
MdRecord callback_mr
Initial value:
= MdRecord("APICallback",
                                "",
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                ArrayOfString(),
                                false,
                                false,
                                false,
                                false,
                                false)
Definition at line 38 of file interactive_workspace.cc.
Referenced by InteractiveWorkspace::initialize().
string_buffer
std::string string_buffer extern
Definition at line 22 of file arts_api.cc.
Referenced by InteractiveWorkspace::execute_workspace_method(), get_error(), and method_print_doc().
verbosity_at_launch
Verbosity verbosity_at_launch extern
The global message verbosity settings:
Definition at line 34 of file messages.cc.
Referenced by InteractiveWorkspace::InteractiveWorkspace(), and InteractiveWorkspace::set_agenda_variable().