ARTS: jacobian.cc File Reference
jacobian.cc File Reference
Routines for setting up the jacobian.
#include "jacobian.h"
#include "arts.h"
#include "auto_md.h"
#include "check_input.h"
#include "global_data.h"
#include "lin_alg.h"
#include "physics_funcs.h"
#include "rte.h"
#include "special_interp.h"
Macros
#define ISLINESHAPETYPE(X)
#define VARISLINESHAPEPARAM(X, Y) (t == Jacobian::Line::Shape##X##Y)
Functions
ostream & operator<< (ostream &os, const RetrievalQuantity &ot)
Output operator for RetrievalQuantity.
void jac_ranges_indices (ArrayOfArrayOfIndex &jis, bool &any_affine, const ArrayOfRetrievalQuantity &jqs, const bool &before_affine)
Determines the index range inside x and the Jacobian for each retrieval quantity.
void transform_jacobian (Matrix &jacobian, const Vector x, const ArrayOfRetrievalQuantity &jqs)
Applies both functional and affine transformations.
void transform_x (Vector &x, const ArrayOfRetrievalQuantity &jqs)
Handles transformations of the state vector.
void transform_x_back (Vector &x_t, const ArrayOfRetrievalQuantity &jqs, bool revert_functional_transforms)
Handles back-transformations of the state vector.
void from_dpath_to_dx (MatrixView diy_dx, ConstMatrixView diy_dq, const Numeric &w)
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity &jacobian_quantity, ConstTensor3View diy_dpath, const Index &atmosphere_dim, const Ppath &ppath, ConstVectorView ppath_p)
Maps jacobian data for points along the propagation path, to jacobian retrieval grid data.
void diy_from_pos_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity &jacobian_quantity, ConstMatrixView diy_dpos, const Index &atmosphere_dim, ConstVectorView rtp_pos)
diy_from_pos_to_rgrids
ArrayOfIndex get_pointers_for_analytical_species (const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfSpeciesTag &abs_species)
Help function for analytical jacobian calculations.
ArrayOfTensor3 get_standard_diy_dpath (const ArrayOfRetrievalQuantity &jacobian_quantities, Index np, Index nf, Index ns, bool active)
Help function for analytical jacobian calculations.
ArrayOfTensor3 get_standard_starting_diy_dx (const ArrayOfRetrievalQuantity &jacobian_quantities, Index np, Index nf, Index ns, bool active)
Help function for analytical jacobian calculations.
ArrayOfIndex get_pointers_for_scat_species (const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfString &scat_species, const bool cloudbox_on)
Help function for analytical jacobian calculations.
bool check_retrieval_grids (ArrayOfVector &grids, ostringstream &os, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Vector &p_retr, const Vector &lat_retr, const Vector &lon_retr, const String &p_retr_name, const String &lat_retr_name, const String &lon_retr_name, const Index &dim)
Check that the retrieval grids are defined for each atmosphere dim.
bool check_retrieval_grids (ArrayOfVector &grids, ostringstream &os, const Vector &lat_grid, const Vector &lon_grid, const Vector &lat_retr, const Vector &lon_retr, const String &lat_retr_name, const String &lon_retr_name, const Index &dim)
Check that the retrieval grids are defined for each atmosphere dim.
void jacobian_type_extrapol (ArrayOfGridPos &gp)
Adopts grid positions to extrapolation used for jacobians.
void polynomial_basis_func (Vector &b, const Vector &x, const Index &poly_coeff)
Calculates polynomial basis functions.
void calcBaselineFit (Vector &y_baseline, const Vector &x, const Index &mblock_index, const Sparse &sensor_response, const ArrayOfIndex &sensor_response_pol_grid, const Vector &sensor_response_f_grid, const Matrix &sensor_response_dlos_grid, const RetrievalQuantity &rq, const Index rq_index, const ArrayOfArrayOfIndex &jacobian_indices)
Calculate baseline fit.
void vmrunitscf (Numeric &x, const String &unit, const Numeric &vmr, const Numeric &p, const Numeric &t)
Scale factor for conversion between gas species units.
void dxdvmrscf (Numeric &x, const String &unit, const Numeric &vmr, const Numeric &p, const Numeric &t)
Scale factor for conversion of derivatives with respect to VMR.
bool propmattype_index (const ArrayOfRetrievalQuantity &js, const Index i) ARTS_NOEXCEPT
Returns if the indexed value is a propagation matrix value.
bool is_special_vmr (const RetrievalQuantity &t, const ArrayOfSpeciesTag &species_list)
Returns if the indexed value is a propagation matrix value.
bool is_wind_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a wind parameter.
bool is_frequency_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a frequency parameter in propagation matrix calculations.
bool is_derived_magnetic_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a derived magnetic parameter.
bool is_magnetic_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a magnetic parameter.
bool is_nlte_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a NLTE parameter.
bool is_lineshape_parameter_X0 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X0 derivative.
bool is_lineshape_parameter_X1 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X1 derivative.
bool is_lineshape_parameter_X2 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X2 derivative.
bool is_lineshape_parameter_X3 (const RetrievalQuantity &t) noexcept
bool is_lineshape_parameter_bar_linemixing (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC derivative.
bool is_lineshape_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC, Y, G, DV derivative.
bool is_line_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is related to the absorption line.
bool supports_CIA (const ArrayOfRetrievalQuantity &js)
Returns if the array supports CIA derivatives.
bool supports_hitran_xsec (const ArrayOfRetrievalQuantity &js)
Returns if the array supports HITRAN cross-section derivatives.
bool supports_continuum (const ArrayOfRetrievalQuantity &js)
Returns if the array supports continuum derivatives.
bool supports_relaxation_matrix (const ArrayOfRetrievalQuantity &js)
Returns if the array supports relaxation matrix derivatives.
bool supports_lookup (const ArrayOfRetrievalQuantity &js)
Returns if the array supports lookup table derivatives.
bool supports_propmat_clearsky (const ArrayOfRetrievalQuantity &js)
Returns if the array supports propagation matrix derivatives.
bool species_match (const RetrievalQuantity &rq, const ArrayOfSpeciesTag &ast)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool species_match (const RetrievalQuantity &rq, const Index species)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool species_iso_match (const RetrievalQuantity &rq, const Index species, const Index iso)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool do_temperature_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants the temperature derivative.
jacobianVMRcheck do_vmr_jacobian (const ArrayOfRetrievalQuantity &js, const QuantumIdentifier &line_qid) noexcept
Returns the required info for VMR Jacobian.
bool do_line_center_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a line center derivative.
bool do_frequency_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a frequency derivative.
bool do_magnetic_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a magnetic derivative.
Numeric temperature_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the temperature perturbation if it exists.
Numeric frequency_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the frequency perturbation if it exists.
Numeric magnetic_field_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the magnetic field perturbation if it exists.
Variables
const Numeric NAT_LOG_TEN
const Numeric PI
Detailed Description
Routines for setting up the jacobian.
Author
Mattias Ekstrom ekstr.nosp@m.om@r.nosp@m.ss.ch.nosp@m.alme.nosp@m.rs.se
Date
2004-09-14
Definition in file jacobian.cc.
Macro Definition Documentation
ISLINESHAPETYPE
#define ISLINESHAPETYPE (X)
Value:
  bool is_pressure_broadening_##X(const RetrievalQuantity& t) noexcept { \
    return t == Jacobian::Line::Shape##X##X0 or                          \
           t == Jacobian::Line::Shape##X##X1 or                          \
           t == Jacobian::Line::Shape##X##X2 or                          \
           t == Jacobian::Line::Shape##X##X3;                            \
  }
Definition at line 1039 of file jacobian.cc.
VARISLINESHAPEPARAM
#define VARISLINESHAPEPARAM (X, Y) (t == Jacobian::Line::Shape##X##Y)
Definition at line 1057 of file jacobian.cc.
Function Documentation
calcBaselineFit()
void calcBaselineFit (Vector & y_baseline, const Vector & x, const Index & mblock_index, const Sparse & sensor_response, const ArrayOfIndex & sensor_response_pol_grid, const Vector & sensor_response_f_grid, const Matrix & sensor_response_dlos_grid, const RetrievalQuantity & rq, const Index rq_index, const ArrayOfArrayOfIndex & jacobian_indices)
Calculate baseline fit.
Computes the baseline fit from a given state vector.
Given a retrieval quantitiy which is either a polynomial or a sine baseline fit this function computes the baseline offset in y_baseline.
Parameters
[out] y_baseline The computed baseline offset. Computed baseline offset are accumulated into this vector, so it must be initialized externally!
[in] x State vector consisten with given retrieval quantity
[in] mblock_index The index of the measurement block.
[in] sensor_response Must be consistent with size of y_baseline.
[in] sensor_response_pol_grid Must be consistent with size of y_baseline.
[in] sensor_response_f_grid Must be consistent with size of y_baseline.
[in] sensor_dlos_grid Must be consistent with size of y_baseline.
[in] rq The poly- or sinefit retrieval quantity
[in] rq_index The index of the retrieval quantity
[in] jacobian_indices
Definition at line 872 of file jacobian.cc.
References a, ARTS_USER_ERROR, c, get_rowindex_for_mblock(), Range::get_start(), RetrievalQuantity::Grids(), Interpolation::l(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, Jacobian::Polyfit, polynomial_basis_func(), Vector::resize(), Jacobian::Sinefit, w(), and x.
Referenced by x2artsSensor().
check_retrieval_grids() [1/2]
bool check_retrieval_grids (ArrayOfVector & grids, ostringstream & os, const Vector & lat_grid, const Vector & lon_grid, const Vector & lat_retr, const Vector & lon_retr, const String & lat_retr_name, const String & lon_retr_name, const Index & dim)
Check that the retrieval grids are defined for each atmosphere dim.
Use this version for surface variables
This function checks for the given atmosphere dimension that I) the retrieval grids are defined II) and that they are covered by the corresponding atmospheric grid. If not the return is false and an output string is created to print the error to the user. If the grids are ok they are stored in an array and true is returned.
Parameters
[out] grids The array of retrieval grids.
[in,out] os The output string stream.
[in] lat_grid The atmospheric latitude grid
[in] lon_grid The atmospheric longitude grid
[in] lat_retr The latitude retrieval grid.
[in] lon_retr The longitude retrieval grid.
[in] lat_retr_name The control file name for the latitude retrieval grid.
[in] lon_retr_name The control file name for the longitude retrieval grid.
[in] dim The atmosphere dimension
Returns
Boolean for check.
Author
Mattias Ekstrom
Date
2005-05-11
Definition at line 751 of file jacobian.cc.
References ARTS_ASSERT, is_increasing(), max, Array< base >::nelem(), and ConstVectorView::nelem().
check_retrieval_grids() [2/2]
bool check_retrieval_grids (ArrayOfVector & grids, ostringstream & os, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Vector & p_retr, const Vector & lat_retr, const Vector & lon_retr, const String & p_retr_name, const String & lat_retr_name, const String & lon_retr_name, const Index & dim)
Check that the retrieval grids are defined for each atmosphere dim.
Use this version for atmospheric fields.
This function checks for the given atmosphere dimension that I) the retrieval grids are defined II) and that they are covered by the corresponding atmospheric grid. If not the return is false and an output string is created to print the error to the user. If the grids are ok they are stored in an array and true is returned.
Parameters
[out] grids The array of retrieval grids.
[in,out] os The output string stream.
[in] p_grid The atmospheric pressure grid
[in] lat_grid The atmospheric latitude grid
[in] lon_grid The atmospheric longitude grid
[in] p_retr The pressure retrieval grid.
[in] lat_retr The latitude retrieval grid.
[in] lon_retr The longitude retrieval grid.
[in] p_retr_name The control file name used for the pressure retrieval grid.
[in] lat_retr_name The control file name for the latitude retrieval grid.
[in] lon_retr_name The control file name for the longitude retrieval grid.
[in] dim The atmosphere dimension
Returns
Boolean for check.
Author
Mattias Ekstrom
Date
2005-05-11
Definition at line 641 of file jacobian.cc.
References ARTS_ASSERT, is_decreasing(), is_increasing(), Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by jacobianAddAbsSpecies(), jacobianAddMagField(), jacobianAddNLTE(), jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), jacobianAddTemperature(), and jacobianAddWind().
diy_from_path_to_rgrids()
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity & jacobian_quantity, ConstTensor3View diy_dpath, const Index & atmosphere_dim, const Ppath & ppath, ConstVectorView ppath_p)
Maps jacobian data for points along the propagation path, to jacobian retrieval grid data.
Parameters
[out] diy_dx One element of the WSV diy_dx.
[in] jacobian_quantity One element of of the WSV jacobian_quantities.
[in] diy_dpath Jacobians along the propagation path.
[in] atmosphere_dim As the WSV.
[in] ppath As the WSV.
[in] ppath_p The pressure at each ppath point.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 312 of file jacobian.cc.
References ARTS_ASSERT, from_dpath_to_dx(), gp4length1grid(), gridpos(), RetrievalQuantity::Grids(), jacobian_type_extrapol(), joker, Array< base >::nelem(), Ppath::np, p2gridpos(), and Ppath::pos.
Referenced by rtmethods_jacobian_finalisation().
diy_from_pos_to_rgrids()
void diy_from_pos_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity & jacobian_quantity, ConstMatrixView diy_dpos, const Index & atmosphere_dim, ConstVectorView rtp_pos)
diy_from_pos_to_rgrids
Maps jacobian data for a surface position, to jacobian retrieval grid data.
Parameters
[out] diy_dx One element of the WSV diy_dx.
[in] jacobian_quantity One element of of the WSV jacobian_quantities.
[in] diy_dpos Jacobian for the position itself.
[in] atmosphere_dim As the WSV.
[in] rtp_pos As the WSV.
Author
Patrick Eriksson
Date
2018-04-10
Definition at line 474 of file jacobian.cc.
References ARTS_ASSERT, from_dpath_to_dx(), gp4length1grid(), gridpos(), RetrievalQuantity::Grids(), jacobian_type_extrapol(), joker, max, Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by iySurfaceRtpropCalc().
do_frequency_jacobian()
bool do_frequency_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a frequency derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1192 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), propmat_clearskyAddFromLookup(), and propmat_clearskyAddParticles().
do_line_center_jacobian()
bool do_line_center_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a line center derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1188 of file jacobian.cc.
do_magnetic_jacobian()
bool do_magnetic_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a magnetic derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1196 of file jacobian.cc.
Referenced by propmat_clearskyAddFaraday().
do_temperature_jacobian()
bool do_temperature_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants the temperature derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1175 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), Linefunctions::apply_rosenkranz_quadratic_scaling(), iyEmissionStandard(), iyHybrid(), Absorption::PredefinedModel::makarov2020_o2_lines_mpm(), propmat_clearskyAddFromLookup(), propmat_clearskyAddParticles(), and Linefunctions::set_cross_section_of_band().
do_vmr_jacobian()
jacobianVMRcheck do_vmr_jacobian (const ArrayOfRetrievalQuantity & js, const QuantumIdentifier & line_qid) noexcept
Returns the required info for VMR Jacobian.
Parameters
[in] js As jacobian_quantities WSV
[in] line_qid A line identifier
Returns
true and retrieval quantity quantum identity pointer if available
false and line_qid pointer if not available
Definition at line 1179 of file jacobian.cc.
Referenced by Linefunctions::set_cross_section_of_band().
dxdvmrscf()
void dxdvmrscf (Numeric & x, const String & unit, const Numeric & vmr, const Numeric & p, const Numeric & t)
Scale factor for conversion of derivatives with respect to VMR.
The function finds the factor with which a partial derivative with respect to gas species VMR shall be multiplicated to match the selected (jacobian) unit. The function was implemented for scaling of dpropmat_clearsky_dx but it could also be of use in other contexts.
Parameters
[out] x Scale factor
[in] unit Unit selected.
[in] vmr VMR value.
[in] p Pressure
[in] t Temperature.
Author
Patrick Eriksson
Date
2015-12-11
Definition at line 979 of file jacobian.cc.
References ARTS_USER_ERROR, number_density(), and x.
Referenced by adapt_stepwise_partial_derivatives().
frequency_perturbation()
Numeric frequency_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the frequency perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Frequency perturbation
Definition at line 1208 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), and propmat_clearskyAddFromLookup().
from_dpath_to_dx()
void from_dpath_to_dx (MatrixView diy_dx, ConstMatrixView diy_dq, const Numeric & w)
Definition at line 302 of file jacobian.cc.
References ConstMatrixView::ncols(), ConstMatrixView::nrows(), and w().
Referenced by diy_from_path_to_rgrids(), and diy_from_pos_to_rgrids().
get_pointers_for_analytical_species()
ArrayOfIndex get_pointers_for_analytical_species (const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfSpeciesTag & abs_species)
Help function for analytical jacobian calculations.
The function determines which terms in jacobian_quantities that are analytical absorption species.
The output Array has the position in abs_species for Jacobian::Line::VMR and Jacobian::Special::ArrayOfSpeciesTagVMR quantities. It has -9999 for Jacobian::Atm::Particulates and for Jacobian::Atm::Electrons. It has -1 for all other types of partial derivatives
Parameters
[in] jacobian_quantities As the WSV.
[in] abs_species As the WSV.
Returns
ArrayOfIndex With information as above (size: jacobain_quantities.nelem())
Author
Richard Larsson
Date
2020-11-12
Definition at line 564 of file jacobian.cc.
References ARTS_USER_ERROR, FOR_ANALYTICAL_JACOBIANS_DO, and Array< base >::nelem().
Referenced by iyEmissionStandard(), iyHybrid(), iyRadarSingleScat(), and iyTransmissionStandard().
get_pointers_for_scat_species()
ArrayOfIndex get_pointers_for_scat_species (const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfString & scat_species, const bool cloudbox_on)
Help function for analytical jacobian calculations.
The function determines which terms in jacobian_quantities that are analytical absorption species.
If the scat species is there, it will have an index pointing to it, otherwise the index will be -1
cloudbox_on must be true or all output is -1
Parameters
[in] jacobian_quantities As the WSV.
[in] scat_species As the WSV.
[in] cloudbox_on As the WSV.
Returns
ArrayOfIndex With information as above (size: jacobain_quantities.nelem())
Author
Richard Larsson
Date
2020-11-12
Definition at line 619 of file jacobian.cc.
References ARTS_USER_ERROR_IF, find_first(), FOR_ANALYTICAL_JACOBIANS_DO, and Array< base >::nelem().
Referenced by iyHybrid(), iyRadarSingleScat(), and iyTransmissionStandard().
get_standard_diy_dpath()
ArrayOfTensor3 get_standard_diy_dpath (const ArrayOfRetrievalQuantity & jacobian_quantities, Index np, Index nf, Index ns, bool active)
Help function for analytical jacobian calculations.
The size of the by-path computations of the Jacobian is set and zeroed
Parameters
[in] jacobian_quantities As the WSV.
[in] np The path grid count
[in] nf The frequency grid count
[in] ns The Stokes grid count
[in] active If true, the middle dimension is np times nf, otherwise it is nf
Returns
diy_dpath As expected by the methods using diy_dpath (size: jacobain_quantities.nelem())
Author
Richard Larsson
Date
2020-11-12
Definition at line 597 of file jacobian.cc.
References FOR_ANALYTICAL_JACOBIANS_DO, Array< base >::nelem(), and ns.
Referenced by iyEmissionStandard(), iyHybrid(), iyRadarSingleScat(), and iyTransmissionStandard().
get_standard_starting_diy_dx()
ArrayOfTensor3 get_standard_starting_diy_dx (const ArrayOfRetrievalQuantity & jacobian_quantities, Index np, Index nf, Index ns, bool active)
Help function for analytical jacobian calculations.
The size of the computations of the Jacobian is set and zeroed
Parameters
[in] jacobian_quantities As the WSV.
[in] np The path grid count
[in] nf The frequency grid count
[in] ns The Stokes grid count
[in] active If true, the middle dimension is np times nf, otherwise it is nf
Returns
diy_dx As expected by the methods using diy_dpath (size: jacobain_quantities.nelem())
Author
Richard Larsson
Date
2020-11-12
Definition at line 606 of file jacobian.cc.
References FOR_ANALYTICAL_JACOBIANS_DO2, jac_ranges_indices(), Array< base >::nelem(), and ns.
Referenced by iyEmissionStandard(), iyHybrid(), iyRadarSingleScat(), and iyTransmissionStandard().
is_derived_magnetic_parameter()
bool is_derived_magnetic_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a derived magnetic parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1027 of file jacobian.cc.
References Jacobian::MagneticMagnitude.
is_frequency_parameter()
bool is_frequency_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a frequency parameter in propagation matrix calculations.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1023 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddConts(), Linefunctions::apply_rosenkranz_quadratic_scaling(), Linefunctions::apply_VVH_scaling(), Linefunctions::apply_VVW_scaling(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), propmat_clearskyAddFaraday(), propmat_clearskyAddFromLookup(), Linefunctions::set_doppler(), Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_line_parameter()
bool is_line_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is related to the absorption line.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1106 of file jacobian.cc.
is_lineshape_parameter()
bool is_lineshape_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC, Y, G, DV derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1098 of file jacobian.cc.
References is_pressure_broadening_D0(), is_pressure_broadening_D2(), is_pressure_broadening_DV(), is_pressure_broadening_ETA(), is_pressure_broadening_FVC(), is_pressure_broadening_G(), is_pressure_broadening_G0(), is_pressure_broadening_G2(), and is_pressure_broadening_Y().
Referenced by Linefunctions::apply_lineshapemodel_jacobian_scaling().
is_lineshape_parameter_bar_linemixing()
bool is_lineshape_parameter_bar_linemixing (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1091 of file jacobian.cc.
References is_pressure_broadening_D0(), is_pressure_broadening_D2(), is_pressure_broadening_ETA(), is_pressure_broadening_FVC(), is_pressure_broadening_G0(), and is_pressure_broadening_G2().
is_lineshape_parameter_X0()
bool is_lineshape_parameter_X0 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X0 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1058 of file jacobian.cc.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, VARISLINESHAPEPARAM, Options::X0, and LineShape::Y.
is_lineshape_parameter_X1()
bool is_lineshape_parameter_X1 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X1 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1066 of file jacobian.cc.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, VARISLINESHAPEPARAM, Options::X1, and LineShape::Y.
is_lineshape_parameter_X2()
bool is_lineshape_parameter_X2 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X2 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1074 of file jacobian.cc.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, VARISLINESHAPEPARAM, Options::X2, and LineShape::Y.
is_lineshape_parameter_X3()
bool is_lineshape_parameter_X3 (const RetrievalQuantity & t) noexcept
Definition at line 1082 of file jacobian.cc.
References LineShape::D0, LineShape::D2, LineShape::ETA, LineShape::FVC, LineShape::G, LineShape::G0, LineShape::G2, VARISLINESHAPEPARAM, and LineShape::Y.
is_magnetic_parameter()
bool is_magnetic_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a magnetic parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1031 of file jacobian.cc.
Referenced by Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_nlte_parameter()
bool is_nlte_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a NLTE parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1035 of file jacobian.cc.
is_special_vmr()
bool is_special_vmr (const RetrievalQuantity & t, const ArrayOfSpeciesTag & species_list)
Returns if the indexed value is a propagation matrix value.
Parameters
[in] t A retrieval quantity
[in] species_list A list of species
Returns
true if this index is a special VMR derivative
Definition at line 1010 of file jacobian.cc.
References array_species_tag_from_string(), and RetrievalQuantity::Subtag().
Referenced by propmat_clearskyAddFaraday(), propmat_clearskyAddFromAbsCoefPerSpecies(), propmat_clearskyAddFromLookup(), propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), and zeeman_on_the_fly().
is_wind_parameter()
bool is_wind_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a wind parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1019 of file jacobian.cc.
Referenced by adapt_stepwise_partial_derivatives().
jac_ranges_indices()
void jac_ranges_indices (ArrayOfArrayOfIndex & jis, bool & any_affine, const ArrayOfRetrievalQuantity & jqs, const bool & before_affine = false)
Determines the index range inside x and the Jacobian for each retrieval quantity.
The ranges are given as an ArrayOfArrayOfIndex, where outermost dimension corresponds to retrieval quantity. The inner dimension has throughout size 2, where element 0 is the first index and element 1 is the last index of the range.
Parameters
[out] jis Indices, as described above
[in] any_affine True if at least one quantity has affine transformation.
[in] jqs The WSV jacobian_quantities
[in] before_affine Set to true to get indices without any affine transformation. Default is false.
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 45 of file jacobian.cc.
References RetrievalQuantity::HasAffine(), ConstMatrixView::ncols(), RetrievalQuantity::nelem(), Array< base >::nelem(), and RetrievalQuantity::TransformationMatrix().
Referenced by covmat_sxAddBlock(), covmat_sxAddInverseBlock(), get_standard_starting_diy_dx(), jacobianAdjustAndTransform(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), jacobianCalcSinefit(), retrievalDefClose(), transform_jacobian(), transform_x(), transform_x_back(), x2artsAtmAndSurf(), x2artsSensor(), yCalc(), yCalcAppend(), and yRadar().
jacobian_type_extrapol()
void jacobian_type_extrapol (ArrayOfGridPos & gp)
Adopts grid positions to extrapolation used for jacobians.
The standard interpolation scheme applies a linear extrapolation, while for the jacobians the extrapolation can be seen as a "closest" interpolation. That is, for points outisde the covered grid, the value at closest end point is taken. And here extrapolation to +-Inf is allowed.
This function modifies grid positions to jacobaina extrapolation approach. For efficiency, the input grid positions are not asserted at all, and "extrapolation points" are identified simply by a fd outside [0,1].
Parameters
[in/out] gp Array of grid positions.
Author
Patrick Eriksson
Date
2015-09-10
Definition at line 836 of file jacobian.cc.
References Array< base >::nelem().
Referenced by diy_from_path_to_rgrids(), diy_from_pos_to_rgrids(), and get_gp_rq_to_atmgrids().
magnetic_field_perturbation()
Numeric magnetic_field_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the magnetic field perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Magnetic field perturbation
Definition at line 1216 of file jacobian.cc.
Referenced by propmat_clearskyAddFaraday().
operator<<()
ostream& operator<< (ostream & os, const RetrievalQuantity & ot)
Output operator for RetrievalQuantity.
Definition at line 39 of file jacobian.cc.
References RetrievalQuantity::Mode(), RetrievalQuantity::Subtag(), and RetrievalQuantity::Target().
polynomial_basis_func()
void polynomial_basis_func (Vector & b, const Vector & x, const Index & poly_coeff)
Calculates polynomial basis functions.
The basis function is b(x) = 1 for poly_coeff = 0. For higher coefficients, x^poly_coeff - m, where first the range covered by x* is normalised to [-1,1] and m is selected in such way that sum(b) = 0.
Parameters
[out] b Calculated basis function.
[in] x The grid over which the fit shall be performed.
[in] poly_coeff Polynomial coefficient.
Author
Patrick Eriksson
Date
2008-11-07
Definition at line 848 of file jacobian.cc.
References ARTS_ASSERT, b, dx, Interpolation::l(), max, mean(), min, pow(), and x.
Referenced by calcBaselineFit(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), and x2artsSensor().
propmattype_index()
bool propmattype_index (const ArrayOfRetrievalQuantity & js, const Index i)
Returns if the indexed value is a propagation matrix value.
Parameters
[in] js As jacobian_quantities WSV
[in] i A position in jacobian_quantities
Returns
true if this index can be used in propmat calculations
Definition at line 1002 of file jacobian.cc.
References ARTS_ASSERT.
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesAddConts(), Linefunctions::apply_linemixing_scaling_and_mirroring(), Linefunctions::apply_lineshapemodel_jacobian_scaling(), Linefunctions::apply_rosenkranz_quadratic_scaling(), Linefunctions::apply_VVH_scaling(), Linefunctions::apply_VVW_scaling(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), propmat_clearskyAddFromLookup(), propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), Linefunctions::set_cross_section_of_band(), Linefunctions::set_doppler(), Linefunctions::set_lorentz(), Linefunctions::set_voigt(), xsec_species(), and zeeman_on_the_fly().
species_iso_match()
bool species_iso_match (const RetrievalQuantity & rq, const Index species, const Index iso)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Parameters
[in] rq A retrieval quantity
[in] species An index-mapped species
[in] iso An index-mapped isotopologue
Returns
true the species and isotopologue match the species and isotopologue in the retrieval quantity
false otherwise
Definition at line 1164 of file jacobian.cc.
References iso(), SpeciesRecord::Isotopologue(), QuantumIdentifier::Isotopologue(), Array< base >::nelem(), RetrievalQuantity::QuantumIdentity(), global_data::species_data, and species_match().
species_match() [1/2]
bool species_match (const RetrievalQuantity & rq, const ArrayOfSpeciesTag & ast)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Very slow compared to index input
Parameters
[in] rq A retrieval quantity
[in] ast A list of species tags
Returns
true if all species in the tags list matches the species in the retrieval quantity
false otherwise
Definition at line 1140 of file jacobian.cc.
References QuantumIdentifier::ALL, array_species_tag_from_string(), QuantumIdentifier::Isotopologue(), RetrievalQuantity::QuantumIdentity(), QuantumIdentifier::Species(), RetrievalQuantity::Subtag(), and QuantumIdentifier::Type().
Referenced by species_iso_match().
species_match() [2/2]
bool species_match (const RetrievalQuantity & rq, const Index species)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Parameters
[in] rq A retrieval quantity
[in] species An index-mapped species
Returns
true the species match the species in the retrieval quantity
false otherwise
Definition at line 1158 of file jacobian.cc.
References RetrievalQuantity::QuantumIdentity(), and QuantumIdentifier::Species().
supports_CIA()
bool supports_CIA (const ArrayOfRetrievalQuantity & js)
Returns if the array supports CIA derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1110 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA().
supports_continuum()
bool supports_continuum (const ArrayOfRetrievalQuantity & js)
Returns if the array supports continuum derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1118 of file jacobian.cc.
References ARTS_USER_ERROR_IF.
Referenced by abs_xsec_per_speciesAddConts().
supports_hitran_xsec()
bool supports_hitran_xsec (const ArrayOfRetrievalQuantity & js)
Returns if the array supports HITRAN cross-section derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1114 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddHitranXsec().
supports_lookup()
bool supports_lookup (const ArrayOfRetrievalQuantity & js)
Returns if the array supports lookup table derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1130 of file jacobian.cc.
References ARTS_USER_ERROR_IF.
Referenced by propmat_clearskyAddFromLookup().
supports_propmat_clearsky()
bool supports_propmat_clearsky (const ArrayOfRetrievalQuantity & js)
Returns if the array supports propagation matrix derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1136 of file jacobian.cc.
supports_relaxation_matrix()
bool supports_relaxation_matrix (const ArrayOfRetrievalQuantity & js)
Returns if the array supports relaxation matrix derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1124 of file jacobian.cc.
References ARTS_USER_ERROR_IF.
temperature_perturbation()
Numeric temperature_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the temperature perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Temperature perturbation
Definition at line 1200 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), propmat_clearskyAddFromLookup(), and propmat_clearskyAddParticles().
transform_jacobian()
void transform_jacobian (Matrix & jacobian, const Vector x, const ArrayOfRetrievalQuantity & jqs)
Applies both functional and affine transformations.
Parameters
[in] jacobian As the WSV jacobian
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 90 of file jacobian.cc.
References ARTS_ASSERT, c, RetrievalQuantity::HasAffine(), jac_ranges_indices(), joker, mult(), NAT_LOG_TEN, Array< base >::nelem(), ConstMatrixView::nrows(), pow(), swap(), RetrievalQuantity::TFuncParameters(), transform_x_back(), RetrievalQuantity::TransformationFunc(), RetrievalQuantity::TransformationMatrix(), and x.
Referenced by jacobianAdjustAndTransform().
transform_x()
void transform_x (Vector & x, const ArrayOfRetrievalQuantity & jqs)
Handles transformations of the state vector.
Applies both functional and affine transformations.
Parameters
[in,out] x As the WSV x
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 155 of file jacobian.cc.
References ARTS_ASSERT, ARTS_USER_ERROR_IF, RetrievalQuantity::HasAffine(), jac_ranges_indices(), mult(), Array< base >::nelem(), RetrievalQuantity::OffsetVector(), swap(), RetrievalQuantity::TFuncParameters(), RetrievalQuantity::TransformationFunc(), RetrievalQuantity::TransformationMatrix(), transpose(), and x.
transform_x_back()
void transform_x_back (Vector & x_t, const ArrayOfRetrievalQuantity & jqs, bool revert_functional_transforms = true)
Handles back-transformations of the state vector.
Applies both functional and affine transformations.
Parameters
[in] x As the WSV x
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 232 of file jacobian.cc.
References ARTS_ASSERT, RetrievalQuantity::HasAffine(), jac_ranges_indices(), mult(), Array< base >::nelem(), RetrievalQuantity::OffsetVector(), pow(), swap(), RetrievalQuantity::TFuncParameters(), RetrievalQuantity::TransformationFunc(), RetrievalQuantity::TransformationMatrix(), and x.
Referenced by jacobianAdjustAndTransform(), transform_jacobian(), x2artsAtmAndSurf(), and x2artsSensor().
vmrunitscf()
void vmrunitscf (Numeric & x, const String & unit, const Numeric & vmr, const Numeric & p, const Numeric & t)
Scale factor for conversion between gas species units.
The function finds the factor with which the total absorption of a gas species shall be multiplicated to match the selected (jacobian) unit.
Parameters
[out] x Scale factor
[in] unit Unit selected.
[in] vmr VMR value.
[in] p Pressure
[in] t Temperature.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 952 of file jacobian.cc.
References ARTS_USER_ERROR, number_density(), and x.
Referenced by adapt_stepwise_partial_derivatives().
Variable Documentation
NAT_LOG_TEN
const Numeric NAT_LOG_TEN extern
Referenced by transform_jacobian().
PI
const Numeric PI extern
Referenced by calcBaselineFit().