ARTS: jacobian.h File Reference
jacobian.h File Reference
Routines for setting up the jacobian.
#include <iostream>
#include <map>
#include <stdexcept>
#include "abs_species_tags.h"
#include "agenda_class.h"
#include "array.h"
#include "bifstream.h"
#include "interpolation.h"
#include "logic.h"
#include "matpackI.h"
#include "methods.h"
#include "mystring.h"
#include "ppath.h"
#include "quantum.h"
Classes
class Jacobian::Target
Holds all information required for individual partial derivatives.
class RetrievalQuantity
Deals with internal derivatives, Jacobian definition, and OEM calculations.
struct jacobianVMRcheck
Deals with whether or not we should do a VMR derivative.
Namespaces
Jacobian
Macros
#define ENUMARTS(ENUMTYPE, ...)
ENUMARTS.
#define FOR_ANALYTICAL_JACOBIANS_DO(what_to_do)
#define FOR_ANALYTICAL_JACOBIANS_DO2(what_to_do)
Typedefs
using JacobianTarget = Jacobian::Target
using ArrayOfJacobianTarget = Array< Jacobian::Target >
typedef Array< RetrievalQuantity > ArrayOfRetrievalQuantity
Enumerations
enum JacobianType : Index {
JacobianType::None = 0, JacobianType::Temperature, JacobianType::WindFieldU, JacobianType::WindFieldV,
JacobianType::WindFieldW, JacobianType::AbsWind, JacobianType::MagFieldU, JacobianType::MagFieldV,
JacobianType::MagFieldW, JacobianType::AbsMag, JacobianType::Other
}
Enum for knowing what Jacobian scheme is in-play in the m_rte.cc methods.
Functions
template<typename T >
constexpr bool good_enum (T x)
template<typename T >
std::array< String, Index(T::FINAL)> enum_strarray (const String &strchars)
Jacobian::ENUMARTS (Type, Atm, Line, Sensor, Special) ENUMARTS(Atm
Holds the type of the target quantity.
Particulates Jacobian::ENUMARTS (Line, VMR, Strength, Center, ShapeG0X0, ShapeG0X1, ShapeG0X2, ShapeG0X3, ShapeD0X0, ShapeD0X1, ShapeD0X2, ShapeD0X3, ShapeG2X0, ShapeG2X1, ShapeG2X2, ShapeG2X3, ShapeD2X0, ShapeD2X1, ShapeD2X2, ShapeD2X3, ShapeFVCX0, ShapeFVCX1, ShapeFVCX2, ShapeFVCX3, ShapeETAX0, ShapeETAX1, ShapeETAX2, ShapeETAX3, ShapeYX0, ShapeYX1, ShapeYX2, ShapeYX3, ShapeGX0, ShapeGX1, ShapeGX2, ShapeGX3, ShapeDVX0, ShapeDVX1, ShapeDVX2, ShapeDVX3, NLTE, SpecialParameter1) ENUMARTS(Sensor
Holds the Line-related targets.
Particulates PointingZenithRecalc Jacobian::ENUMARTS (Special, ArrayOfSpeciesTagVMR, ScatteringString, SurfaceString) union TypeOfTarget
Holds special targets that require careful extra manipulation.
TypeOfTarget Jacobian::toTypeOfTarget (const String &s, Type x) noexcept
String Jacobian::toString (TypeOfTarget y, Type x) noexcept
std::ostream & Jacobian::operator<< (std::ostream &os, const Target &x)
Output operator.
ostream & operator<< (ostream &os, const RetrievalQuantity &ot)
Output operator for RetrievalQuantity.
void jac_ranges_indices (ArrayOfArrayOfIndex &jis, bool &any_affine, const ArrayOfRetrievalQuantity &jqs, const bool &before_affine=false)
Determines the index range inside x and the Jacobian for each retrieval quantity.
void transform_jacobian (Matrix &jacobian, const Vector x, const ArrayOfRetrievalQuantity &jqs)
Applies both functional and affine transformations.
void transform_x (Vector &x, const ArrayOfRetrievalQuantity &jqs)
Handles transformations of the state vector.
void transform_x_back (Vector &x_t, const ArrayOfRetrievalQuantity &jqs, bool revert_functional_transforms=true)
Handles back-transformations of the state vector.
bool check_retrieval_grids (ArrayOfVector &grids, ostringstream &os, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Vector &p_retr, const Vector &lat_retr, const Vector &lon_retr, const String &p_retr_name, const String &lat_retr_name, const String &lon_retr_name, const Index &dim)
Check that the retrieval grids are defined for each atmosphere dim.
bool check_retrieval_grids (ArrayOfVector &grids, ostringstream &os, const Vector &lat_grid, const Vector &lon_grid, const Vector &lat_retr, const Vector &lon_retr, const String &lat_retr_name, const String &lon_retr_name, const Index &dim)
Check that the retrieval grids are defined for each atmosphere dim.
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity &jacobian_quantity, ConstTensor3View diy_dpath, const Index &atmosphere_dim, const Ppath &ppath, ConstVectorView ppath_p)
Maps jacobian data for points along the propagation path, to jacobian retrieval grid data.
void diy_from_pos_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity &jacobian_quantity, ConstMatrixView diy_dpos, const Index &atmosphere_dim, ConstVectorView rtp_pos)
diy_from_pos_to_rgrids
void get_pointers_for_analytical_jacobians (ArrayOfIndex &abs_species_i, ArrayOfIndex &scat_species_i, ArrayOfIndex &is_t, ArrayOfIndex &wind_i, ArrayOfIndex &magfield_i, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfSpeciesTag &abs_species, const Index &cloudbox_on, const ArrayOfString &scat_species)
Help function for analytical jacobian calculations.
void jacobian_type_extrapol (ArrayOfGridPos &gp)
Adopts grid positions to extrapolation used for jacobians.
void polynomial_basis_func (Vector &b, const Vector &x, const Index &poly_coeff)
Calculates polynomial basis functions.
void calcBaselineFit (Vector &y_baseline, const Vector &x, const Index &mblock_index, const Sparse &sensor_response, const ArrayOfIndex &sensor_response_pol_grid, const Vector &sensor_response_f_grid, const Matrix &sensor_response_dlos_grid, const RetrievalQuantity &rq, const Index rq_index, const ArrayOfArrayOfIndex &jacobian_indices)
Calculate baseline fit.
void vmrunitscf (Numeric &x, const String &unit, const Numeric &vmr, const Numeric &p, const Numeric &t)
Scale factor for conversion between gas species units.
void dxdvmrscf (Numeric &x, const String &unit, const Numeric &vmr, const Numeric &p, const Numeric &t)
Scale factor for conversion of derivatives with respect to VMR.
void get_diydx (VectorView diy1, VectorView diy2, ConstMatrixView ImT, ConstMatrixView cumulative_transmission, ConstMatrixView dT1, ConstMatrixView dT2, ConstVectorView iYmJ, ConstVectorView dJ1, ConstVectorView dJ2, const Index stokes_dim, const bool transmission_only=false)
ArrayOfIndex equivalent_propmattype_indexes (const ArrayOfRetrievalQuantity &js)
Returns a list of positions for the derivatives in Propagation Matrix calculations.
Index equivalent_propmattype_index (const ArrayOfRetrievalQuantity &js, const Index i) noexcept
Returns a list of positions for the derivatives in Propagation Matrix calculations.
Numeric temperature_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the temperature perturbation if it exists.
Numeric frequency_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the frequency perturbation if it exists.
Numeric magnetic_field_perturbation (const ArrayOfRetrievalQuantity &js) noexcept
Returns the magnetic field perturbation if it exists.
String propmattype_string (const RetrievalQuantity &rq)
Returns a string of the retrieval quantity propagation matrix type.
bool is_wind_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a wind parameter.
bool is_frequency_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a frequency parameter in propagation matrix calculations.
bool is_derived_magnetic_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a derived magnetic parameter.
bool is_magnetic_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a magnetic parameter.
bool is_nlte_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a NLTE parameter.
bool is_pressure_broadening_G0 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0 derivative.
bool is_pressure_broadening_D0 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a D0 derivative.
bool is_pressure_broadening_G2 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0 derivative.
bool is_pressure_broadening_D2 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a D2 derivative.
bool is_pressure_broadening_FVC (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a FVC derivative.
bool is_pressure_broadening_ETA (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a ETA derivative.
bool is_pressure_broadening_Y (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a Y derivative.
bool is_pressure_broadening_G (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G derivative.
bool is_pressure_broadening_DV (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a DV derivative.
bool is_lineshape_parameter_X0 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X0 derivative.
bool is_lineshape_parameter_X1 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X1 derivative.
bool is_lineshape_parameter_X2 (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a X2 derivative.
bool is_lineshape_parameter_bar_linemixing (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC derivative.
bool is_lineshape_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC, Y, G, DV derivative.
bool is_line_parameter (const RetrievalQuantity &t) noexcept
Returns if the Retrieval quantity is related to the absorption line.
bool supports_CIA (const ArrayOfRetrievalQuantity &js)
Returns if the array supports CIA derivatives.
bool supports_hitran_xsec (const ArrayOfRetrievalQuantity &js)
Returns if the array supports HITRAN cross-section derivatives.
bool supports_continuum (const ArrayOfRetrievalQuantity &js)
Returns if the array supports continuum derivatives.
bool supports_relaxation_matrix (const ArrayOfRetrievalQuantity &js)
Returns if the array supports relaxation matrix derivatives.
bool supports_lookup (const ArrayOfRetrievalQuantity &js)
Returns if the array supports lookup table derivatives.
bool supports_zeeman (const ArrayOfRetrievalQuantity &js)
Returns if the array supports Zeeman derivatives.
bool supports_faraday (const ArrayOfRetrievalQuantity &js)
Returns if the array supports Faraday derivatives.
bool supports_particles (const ArrayOfRetrievalQuantity &js)
Returns if the array supports particulate derivatives.
bool supports_propmat_clearsky (const ArrayOfRetrievalQuantity &js)
Returns if the array supports propagation matrix derivatives.
bool species_match (const RetrievalQuantity &rq, const ArrayOfSpeciesTag &ast)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool species_match (const RetrievalQuantity &rq, const Index species)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool species_iso_match (const RetrievalQuantity &rq, const Index species, const Index iso)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
bool do_temperature_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants the temperature derivative.
jacobianVMRcheck do_vmr_jacobian (const ArrayOfRetrievalQuantity &js, const QuantumIdentifier &line_qid) noexcept
Returns the required info for VMR Jacobian.
bool do_line_center_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a line center derivative.
bool do_frequency_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a frequency derivative.
bool do_magnetic_jacobian (const ArrayOfRetrievalQuantity &js) noexcept
Returns if the array wants a magnetic derivative.
Variables
Jacobian::Temperature
Jacobian::WindMagnitude
Jacobian::WindU
Jacobian::WindV
Jacobian::WindW
Jacobian::MagneticMagnitude
Jacobian::MagneticU
Jacobian::MagneticV
Jacobian::MagneticW
Jacobian::Electrons
Particulates Jacobian::FrequencyShift
Particulates Jacobian::FrequencyStretch
Particulates Jacobian::Polyfit
Particulates Jacobian::Sinefit
Particulates Jacobian::PointingZenithInterp
Detailed Description
Routines for setting up the jacobian.
Author
Mattias Ekstrom ekstr.nosp@m.om@r.nosp@m.ss.ch.nosp@m.alme.nosp@m.rs.se
Date
2004-09-14
Definition in file jacobian.h.
Macro Definition Documentation
ENUMARTS
#define ENUMARTS (ENUMTYPE, ...)
Value:
  enum class ENUMTYPE : Index {__VA_ARGS__, FINAL} ;                          \
                                                                              \
  namespace enumstrs {                                                        \
  static const auto ENUMTYPE ## Names =                                       \
                               enum_strarray<ENUMTYPE>(#__VA_ARGS__);         \
  };                                                                          \
                                                                              \
  inline String toString(ENUMTYPE x) noexcept {                               \
    if (good_enum(x))                                                         \
      return enumstrs::ENUMTYPE ## Names [Index(x)];                          \
    else                                                                      \
      return "BAD " # ENUMTYPE;                                               \
  }                                                                           \
                                                                              \
  inline ENUMTYPE  to ## ENUMTYPE(const String& x) noexcept {                 \
    for (Index i=0; i<Index(ENUMTYPE::FINAL); i++)                            \
      if (enumstrs::ENUMTYPE ## Names [i] == x)                               \
        return ENUMTYPE(i);                                                   \
    return ENUMTYPE::FINAL;                                                   \
  }                                                                           \
                                                                              \
  inline std::ostream& operator<<(std::ostream& os, const ENUMTYPE x) {       \
    return os << toString(x);                                                 \
  }                                                                           \
                                                                              \
  inline std::istream& operator<<(std::istream& is, ENUMTYPE& x) {            \
    String val; is >> val; x = to ## ENUMTYPE(val); return is;                \
  }
ENUMARTS.
Generates a "enum class ENUMTYPE : Index" with all the following arguments and terminated by FINAL
Additionally, will fill a local namespace "enumstrs" with a std::array<String, Index(ENUMTYPE::FINAL)> with all of the names in the ENUMTYPE enum class
Additionally, will generate a inlined "toString" function that takes a ENUMTYPE object and returns either its partial name or "BAD ENUMTYPE" as a string
Additionally, will generate a inlined "toENUMTYPE" function that takes a String and returns a corresponding ENUMTYPE object or ENUMTYPE::FINAL if the object is bad
Use the "good_enum(ENUMTYPE)" template function to check if the enum classs object is any good
Will be updated as soon as possible to ensure that all functions that can be are turned into constexpr functions
Example: ENUMARTS(Test, Value)
Generates: enum class Test : Index {Value, FINAL}; namespace enumstrs {std::array<String, 1> TestNames={"Value"};}; String toString(Test x) noexcept; Test toTest(const String& x) noexcept;
Definition at line 95 of file jacobian.h.
FOR_ANALYTICAL_JACOBIANS_DO
#define FOR_ANALYTICAL_JACOBIANS_DO (what_to_do)
Value:
  for (Index iq = 0; iq < jacobian_quantities.nelem(); iq++) {              \
    if (not(jacobian_quantities[iq] == Jacobian::Type::Sensor) and          \
        not(jacobian_quantities[iq] == Jacobian::Special::SurfaceString)) { \
      what_to_do                                                            \
    }                                                                       \
  }
Definition at line 589 of file jacobian.h.
FOR_ANALYTICAL_JACOBIANS_DO2
#define FOR_ANALYTICAL_JACOBIANS_DO2 (what_to_do)
Value:
  for (Index iq = 0; iq < jacobian_quantities.nelem(); iq++) {    \
    if (not(jacobian_quantities[iq] == Jacobian::Type::Sensor)) { \
      what_to_do                                                  \
    }                                                             \
  }
Definition at line 597 of file jacobian.h.
Typedef Documentation
ArrayOfJacobianTarget
using ArrayOfJacobianTarget = Array<Jacobian::Target>
Definition at line 378 of file jacobian.h.
ArrayOfRetrievalQuantity
typedef Array<RetrievalQuantity> ArrayOfRetrievalQuantity
Definition at line 586 of file jacobian.h.
JacobianTarget
using JacobianTarget = Jacobian::Target
Definition at line 377 of file jacobian.h.
Enumeration Type Documentation
JacobianType
enum JacobianType : Index strong
Enum for knowing what Jacobian scheme is in-play in the m_rte.cc methods.
Enumerator
None
Temperature
WindFieldU
WindFieldV
WindFieldW
AbsWind
MagFieldU
MagFieldV
MagFieldW
AbsMag
Other
Definition at line 931 of file jacobian.h.
Function Documentation
calcBaselineFit()
void calcBaselineFit (Vector & y_baseline, const Vector & x, const Index & mblock_index, const Sparse & sensor_response, const ArrayOfIndex & sensor_response_pol_grid, const Vector & sensor_response_f_grid, const Matrix & sensor_response_dlos_grid, const RetrievalQuantity & rq, const Index rq_index, const ArrayOfArrayOfIndex & jacobian_indices)
Calculate baseline fit.
Computes the baseline fit from a given state vector.
Given a retrieval quantitiy which is either a polynomial or a sine baseline fit this function computes the baseline offset in y_baseline.
Parameters
[out] y_baseline The computed baseline offset. Computed baseline offset are accumulated into this vector, so it must be initialized externally!
[in] x State vector consisten with given retrieval quantity
[in] mblock_index The index of the measurement block.
[in] sensor_response Must be consistent with size of y_baseline.
[in] sensor_response_pol_grid Must be consistent with size of y_baseline.
[in] sensor_response_f_grid Must be consistent with size of y_baseline.
[in] sensor_dlos_grid Must be consistent with size of y_baseline.
[in] rq The poly- or sinefit retrieval quantity
[in] rq_index The index of the retrieval quantity
[in] jacobian_indices
Definition at line 894 of file jacobian.cc.
References Jacobian::Polyfit, ARTS::Var::sensor_response_dlos_grid(), ARTS::Var::sensor_response_f_grid(), ARTS::Var::sensor_response_pol_grid(), Jacobian::Sinefit, and w().
check_retrieval_grids() [1/2]
bool check_retrieval_grids (ArrayOfVector & grids, ostringstream & os, const Vector & lat_grid, const Vector & lon_grid, const Vector & lat_retr, const Vector & lon_retr, const String & lat_retr_name, const String & lon_retr_name, const Index & dim)
Check that the retrieval grids are defined for each atmosphere dim.
Use this version for surface variables
This function checks for the given atmosphere dimension that I) the retrieval grids are defined II) and that they are covered by the corresponding atmospheric grid. If not the return is false and an output string is created to print the error to the user. If the grids are ok they are stored in an array and true is returned.
Parameters
[out] grids The array of retrieval grids.
[in,out] os The output string stream.
[in] lat_grid The atmospheric latitude grid
[in] lon_grid The atmospheric longitude grid
[in] lat_retr The latitude retrieval grid.
[in] lon_retr The longitude retrieval grid.
[in] lat_retr_name The control file name for the latitude retrieval grid.
[in] lon_retr_name The control file name for the longitude retrieval grid.
[in] dim The atmosphere dimension
Returns
Boolean for check.
Author
Mattias Ekstrom
Date
2005-05-11
Definition at line 773 of file jacobian.cc.
References is_increasing(), ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), max, Array< base >::nelem(), and ConstVectorView::nelem().
check_retrieval_grids() [2/2]
bool check_retrieval_grids (ArrayOfVector & grids, ostringstream & os, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Vector & p_retr, const Vector & lat_retr, const Vector & lon_retr, const String & p_retr_name, const String & lat_retr_name, const String & lon_retr_name, const Index & dim)
Check that the retrieval grids are defined for each atmosphere dim.
Use this version for atmospheric fields.
This function checks for the given atmosphere dimension that I) the retrieval grids are defined II) and that they are covered by the corresponding atmospheric grid. If not the return is false and an output string is created to print the error to the user. If the grids are ok they are stored in an array and true is returned.
Parameters
[out] grids The array of retrieval grids.
[in,out] os The output string stream.
[in] p_grid The atmospheric pressure grid
[in] lat_grid The atmospheric latitude grid
[in] lon_grid The atmospheric longitude grid
[in] p_retr The pressure retrieval grid.
[in] lat_retr The latitude retrieval grid.
[in] lon_retr The longitude retrieval grid.
[in] p_retr_name The control file name used for the pressure retrieval grid.
[in] lat_retr_name The control file name for the latitude retrieval grid.
[in] lon_retr_name The control file name for the longitude retrieval grid.
[in] dim The atmosphere dimension
Returns
Boolean for check.
Author
Mattias Ekstrom
Date
2005-05-11
Definition at line 663 of file jacobian.cc.
References is_decreasing(), is_increasing(), ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), Array< base >::nelem(), ConstVectorView::nelem(), and ARTS::Var::p_grid().
Referenced by jacobianAddAbsSpecies(), jacobianAddMagField(), jacobianAddNLTE(), jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), jacobianAddTemperature(), and jacobianAddWind().
diy_from_path_to_rgrids()
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity & jacobian_quantity, ConstTensor3View diy_dpath, const Index & atmosphere_dim, const Ppath & ppath, ConstVectorView ppath_p)
Maps jacobian data for points along the propagation path, to jacobian retrieval grid data.
Parameters
[out] diy_dx One element of the WSV diy_dx.
[in] jacobian_quantity One element of of the WSV jacobian_quantities.
[in] diy_dpath Jacobians along the propagation path.
[in] atmosphere_dim As the WSV.
[in] ppath As the WSV.
[in] ppath_p The pressure at each ppath point.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 324 of file jacobian.cc.
References ARTS::Var::atmosphere_dim(), ARTS::Var::diy_dx(), from_dpath_to_dx(), gp4length1grid(), gridpos(), RetrievalQuantity::Grids(), jacobian_type_extrapol(), joker, Array< base >::nelem(), p2gridpos(), ARTS::Var::Ppath::pos(), and ARTS::Var::ppath().
Referenced by rtmethods_jacobian_finalisation().
diy_from_pos_to_rgrids()
void diy_from_pos_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity & jacobian_quantity, ConstMatrixView diy_dpos, const Index & atmosphere_dim, ConstVectorView rtp_pos)
diy_from_pos_to_rgrids
Maps jacobian data for a surface position, to jacobian retrieval grid data.
Parameters
[out] diy_dx One element of the WSV diy_dx.
[in] jacobian_quantity One element of of the WSV jacobian_quantities.
[in] diy_dpos Jacobian for the position itself.
[in] atmosphere_dim As the WSV.
[in] rtp_pos As the WSV.
Author
Patrick Eriksson
Date
2018-04-10
Definition at line 486 of file jacobian.cc.
References ARTS::Var::atmosphere_dim(), ARTS::Var::diy_dx(), from_dpath_to_dx(), gp4length1grid(), gridpos(), RetrievalQuantity::Grids(), jacobian_type_extrapol(), joker, max, Array< base >::nelem(), and ARTS::Var::rtp_pos().
Referenced by iySurfaceRtpropCalc().
do_frequency_jacobian()
bool do_frequency_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a frequency derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1269 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), propmat_clearskyAddFromLookup(), and propmat_clearskyAddParticles().
do_line_center_jacobian()
bool do_line_center_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a line center derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1265 of file jacobian.cc.
do_magnetic_jacobian()
bool do_magnetic_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants a magnetic derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1273 of file jacobian.cc.
Referenced by propmat_clearskyAddFaraday().
do_temperature_jacobian()
bool do_temperature_jacobian (const ArrayOfRetrievalQuantity & js) noexcept
Returns if the array wants the temperature derivative.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1252 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), Linefunctions::apply_rosenkranz_quadratic_scaling(), iyEmissionStandard(), iyHybrid(), iyHybrid2(), Absorption::PredefinedModel::makarov2020_o2_lines_mpm(), propmat_clearskyAddFromLookup(), propmat_clearskyAddParticles(), and Linefunctions::set_cross_section_of_band().
do_vmr_jacobian()
jacobianVMRcheck do_vmr_jacobian (const ArrayOfRetrievalQuantity & js, const QuantumIdentifier & line_qid) noexcept
Returns the required info for VMR Jacobian.
Parameters
[in] js As jacobian_quantities WSV
[in] line_qid A line identifier
Returns
true and retrieval quantity quantum identity pointer if available
false and line_qid pointer if not available
Definition at line 1256 of file jacobian.cc.
Referenced by Linefunctions::set_cross_section_of_band().
dxdvmrscf()
void dxdvmrscf (Numeric & x, const String & unit, const Numeric & vmr, const Numeric & p, const Numeric & t)
Scale factor for conversion of derivatives with respect to VMR.
The function finds the factor with which a partial derivative with respect to gas species VMR shall be multiplicated to match the selected (jacobian) unit. The function was implemented for scaling of dpropmat_clearsky_dx but it could also be of use in other contexts.
Parameters
[out] x Scale factor
[in] unit Unit selected.
[in] vmr VMR value.
[in] p Pressure
[in] t Temperature.
Author
Patrick Eriksson
Date
2015-12-11
Definition at line 1002 of file jacobian.cc.
References number_density(), and ARTS::Var::x().
Referenced by adapt_stepwise_partial_derivatives().
enum_strarray()
template<typename T > std::array<String, Index(T::FINAL)> enum_strarray (const String & strchars)
Definition at line 52 of file jacobian.h.
References Zeeman::end(), and ARTS::Var::x().
equivalent_propmattype_index()
Index equivalent_propmattype_index (const ArrayOfRetrievalQuantity & js, const Index i) noexcept
Returns a list of positions for the derivatives in Propagation Matrix calculations.
Parameters
[in] js As jacobian_quantities WSV
[in] i A position in jacobian_quantities
Returns
List of position
Definition at line 1081 of file jacobian.cc.
References equivalent_propmattype_indexes().
Referenced by get_stepwise_clearsky_propmat().
equivalent_propmattype_indexes()
ArrayOfIndex equivalent_propmattype_indexes (const ArrayOfRetrievalQuantity & js)
Returns a list of positions for the derivatives in Propagation Matrix calculations.
Parameters
[in] js As jacobian_quantities WSV
Returns
List of positions
Definition at line 1072 of file jacobian.cc.
References Array< base >::nelem().
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), equivalent_propmattype_index(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), propmat_clearskyAddFaraday(), propmat_clearskyAddFromLookup(), propmat_clearskyAddParticles(), propmat_clearskyInit(), and zeeman_on_the_fly().
frequency_perturbation()
Numeric frequency_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the frequency perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Frequency perturbation
Definition at line 1285 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), and propmat_clearskyAddFromLookup().
get_diydx()
void get_diydx (VectorView diy1, VectorView diy2, ConstMatrixView ImT, ConstMatrixView cumulative_transmission, ConstMatrixView dT1, ConstMatrixView dT2, ConstVectorView iYmJ, ConstVectorView dJ1, ConstVectorView dJ2, const Index stokes_dim, const bool transmission_only = false)
FIXMEDOC: Remove this function when iyHybrid2 has become new iyHybrid The function helps to calculate the partial derivative of iy with respect to one input at one pressure. The formalism here assumes that the radiation terms are averaged rather than the absorption parameters, thus this can be solved per layer rather than for two layers at a time. Still, the absorption parameters for the transmission needs to be considered by the two layer derivatives
FIXME: Add HSE support
Parameters
[in,out] diy1 Derivative if iy for level 1
[in,out] diy2 Derivative if iy for level 2
[in] ImT Identity matrix minus the transmission matrix
[in] cumulative_transmission Accumulative transmission from level to sensor
[in] dT1 Transmission matrix derivative for level 1
[in] dT2 Transmission matrix derivative for level 2
[in] iYmJ iy minus the source
[in] dJ1 Source vector derivative for level 1
[in] dJ2 Source vector derivative for level 2
[in] stokes_dim As WSV
[in] transmission_only Bool for not doing emission calculations
Author
Richard Larsson
Date
2017-09-20
Definition at line 1022 of file jacobian.cc.
References cumulative_transmission(), mult(), and ARTS::Var::stokes_dim().
Referenced by iyHybrid().
get_pointers_for_analytical_jacobians()
void get_pointers_for_analytical_jacobians (ArrayOfIndex & abs_species_i, ArrayOfIndex & scat_species_i, ArrayOfIndex & is_t, ArrayOfIndex & wind_i, ArrayOfIndex & magfield_i, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfSpeciesTag & abs_species, const Index & cloudbox_on, const ArrayOfString & scat_species)
Help function for analytical jacobian calculations.
The function determines which terms in jacobian_quantities that are analytical absorption species and temperature jacobians.
abs_species_i* and is_t shall be sized to have the same length as jacobian_quantities. For analytical absorption species jacobians, abs_species_i is set to the matching index in abs_species*. Otherwise, to -1. For analytical temperature jacobians, is_t is set to 1. Otherwise to 0.
Parameters
[out] abs_species_i Matching index in abs_species
[out] scat_species_i Matching index among scattering species
[out] is_t Flag for: Is a temperature jacobian?
[in] jacobian_quantities As the WSV.
[in] abs_species As the WSV.
[in] cloudbox_on As the WSV.
[in] scat_species As the WSV.
Author
Patrick Eriksson
Date
2009-10-07
Definition at line 576 of file jacobian.cc.
References ARTS::Var::abs_species(), FOR_ANALYTICAL_JACOBIANS_DO, ARTS::Var::jacobian_quantities(), and Jacobian::Temperature.
Referenced by rtmethods_jacobian_init().
good_enum()
template<typename T > constexpr bool good_enum (T x) constexpr
Definition at line 46 of file jacobian.h.
References ARTS::Var::x().
Referenced by Jacobian::Target::TargetSubTypeOK(), and Jacobian::Target::TargetTypeOK().
is_derived_magnetic_parameter()
bool is_derived_magnetic_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a derived magnetic parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1094 of file jacobian.cc.
References Jacobian::MagneticMagnitude.
is_frequency_parameter()
bool is_frequency_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a frequency parameter in propagation matrix calculations.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1090 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddConts(), Linefunctions::apply_rosenkranz_quadratic_scaling(), Linefunctions::apply_VVH_scaling(), Linefunctions::apply_VVW_scaling(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), propmat_clearskyAddFaraday(), propmat_clearskyAddFromLookup(), Linefunctions::set_doppler(), Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_line_parameter()
bool is_line_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is related to the absorption line.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1173 of file jacobian.cc.
is_lineshape_parameter()
bool is_lineshape_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC, Y, G, DV derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1165 of file jacobian.cc.
References is_pressure_broadening_D0(), is_pressure_broadening_D2(), is_pressure_broadening_DV(), is_pressure_broadening_ETA(), is_pressure_broadening_FVC(), is_pressure_broadening_G(), is_pressure_broadening_G0(), is_pressure_broadening_G2(), and is_pressure_broadening_Y().
Referenced by Linefunctions::apply_lineshapemodel_jacobian_scaling().
is_lineshape_parameter_bar_linemixing()
bool is_lineshape_parameter_bar_linemixing (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0, D0, G2, D2, ETA, FVC derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1158 of file jacobian.cc.
References is_pressure_broadening_D0(), is_pressure_broadening_D2(), is_pressure_broadening_ETA(), is_pressure_broadening_FVC(), is_pressure_broadening_G0(), and is_pressure_broadening_G2().
is_lineshape_parameter_X0()
bool is_lineshape_parameter_X0 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X0 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1125 of file jacobian.cc.
References VARISLINESHAPEPARAM.
is_lineshape_parameter_X1()
bool is_lineshape_parameter_X1 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X1 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1133 of file jacobian.cc.
References VARISLINESHAPEPARAM.
is_lineshape_parameter_X2()
bool is_lineshape_parameter_X2 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a X2 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1141 of file jacobian.cc.
References VARISLINESHAPEPARAM.
is_magnetic_parameter()
bool is_magnetic_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a magnetic parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1098 of file jacobian.cc.
Referenced by Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_nlte_parameter()
bool is_nlte_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a NLTE parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1102 of file jacobian.cc.
is_pressure_broadening_D0()
bool is_pressure_broadening_D0 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a D0 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), is_lineshape_parameter_bar_linemixing(), Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_pressure_broadening_D2()
bool is_pressure_broadening_D2 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a D2 derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), and is_lineshape_parameter_bar_linemixing().
is_pressure_broadening_DV()
bool is_pressure_broadening_DV (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a DV derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_pressure_broadening_ETA()
bool is_pressure_broadening_ETA (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a ETA derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), and is_lineshape_parameter_bar_linemixing().
is_pressure_broadening_FVC()
bool is_pressure_broadening_FVC (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a FVC derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), and is_lineshape_parameter_bar_linemixing().
is_pressure_broadening_G()
bool is_pressure_broadening_G (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter().
is_pressure_broadening_G0()
bool is_pressure_broadening_G0 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0 derivative.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), is_lineshape_parameter_bar_linemixing(), Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
is_pressure_broadening_G2()
bool is_pressure_broadening_G2 (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a G0 derivative.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter(), and is_lineshape_parameter_bar_linemixing().
is_pressure_broadening_Y()
bool is_pressure_broadening_Y (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a Y derivative.
See LineShape::Model for details on parameter
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Referenced by is_lineshape_parameter().
is_wind_parameter()
bool is_wind_parameter (const RetrievalQuantity & t) noexcept
Returns if the Retrieval quantity is a wind parameter.
Parameters
[in] t A retrieval quantity
Returns
true if it is
false if it is not
Definition at line 1086 of file jacobian.cc.
jac_ranges_indices()
void jac_ranges_indices (ArrayOfArrayOfIndex & jis, bool & any_affine, const ArrayOfRetrievalQuantity & jqs, const bool & before_affine = false)
Determines the index range inside x and the Jacobian for each retrieval quantity.
The ranges are given as an ArrayOfArrayOfIndex, where outermost dimension corresponds to retrieval quantity. The inner dimension has throughout size 2, where element 0 is the first index and element 1 is the last index of the range.
Parameters
[out] jis Indices, as described above
[in] any_affine True if at least one quantity has affine transformation.
[in] jqs The WSV jacobian_quantities
[in] before_affine Set to true to get indices without any affine transformation. Default is false.
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 45 of file jacobian.cc.
References RetrievalQuantity::HasAffine(), ConstMatrixView::ncols(), Array< base >::nelem(), RetrievalQuantity::nelem(), and RetrievalQuantity::TransformationMatrix().
Referenced by covmat_sxAddBlock(), covmat_sxAddInverseBlock(), jacobianAdjustAndTransform(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), OEM_checks(), retrievalDefClose(), rtmethods_jacobian_init(), transform_jacobian(), transform_x(), transform_x_back(), x2artsAtmAndSurf(), x2artsSensor(), xaStandard(), xClip(), yActive(), yCalc(), and yCalcAppend().
jacobian_type_extrapol()
void jacobian_type_extrapol (ArrayOfGridPos & gp)
Adopts grid positions to extrapolation used for jacobians.
The standard interpolation scheme applies a linear extrapolation, while for the jacobians the extrapolation can be seen as a "closest" interpolation. That is, for points outisde the covered grid, the value at closest end point is taken. And here extrapolation to +-Inf is allowed.
This function modifies grid positions to jacobaina extrapolation approach. For efficiency, the input grid positions are not asserted at all, and "extrapolation points" are identified simply by a fd outside [0,1].
Parameters
[in/out] gp Array of grid positions.
Author
Patrick Eriksson
Date
2015-09-10
Definition at line 858 of file jacobian.cc.
References Array< base >::nelem().
Referenced by diy_from_path_to_rgrids(), diy_from_pos_to_rgrids(), and get_gp_rq_to_atmgrids().
magnetic_field_perturbation()
Numeric magnetic_field_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the magnetic field perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Magnetic field perturbation
Definition at line 1293 of file jacobian.cc.
Referenced by propmat_clearskyAddFaraday().
operator<<()
ostream& operator<< (ostream & os, const RetrievalQuantity & ot)
Output operator for RetrievalQuantity.
Definition at line 39 of file jacobian.cc.
References RetrievalQuantity::Mode(), RetrievalQuantity::Subtag(), and RetrievalQuantity::Target().
polynomial_basis_func()
void polynomial_basis_func (Vector & b, const Vector & x, const Index & poly_coeff)
Calculates polynomial basis functions.
The basis function is b(x) = 1 for poly_coeff = 0. For higher coefficients, x^poly_coeff - m, where first the range covered by x* is normalised to [-1,1] and m is selected in such way that sum(b) = 0.
Parameters
[out] b Calculated basis function.
[in] x The grid over which the fit shall be performed.
[in] poly_coeff Polynomial coefficient.
Author
Patrick Eriksson
Date
2008-11-07
Definition at line 870 of file jacobian.cc.
References dx, max, mean(), min, ConstVectorView::nelem(), pow(), Vector::resize(), and ARTS::Var::x().
Referenced by jacobianCalcFreqStretch(), and jacobianCalcPolyfit().
propmattype_string()
String propmattype_string (const RetrievalQuantity & rq)
Returns a string of the retrieval quantity propagation matrix type.
Only use for debugging purpose
Parameters
[in] rq A retrieval quantity
Returns
Text representation
species_iso_match()
bool species_iso_match (const RetrievalQuantity & rq, const Index species, const Index iso)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Parameters
[in] rq A retrieval quantity
[in] species An index-mapped species
[in] iso An index-mapped isotopologue
Returns
true the species and isotopologue match the species and isotopologue in the retrieval quantity
false otherwise
Definition at line 1241 of file jacobian.cc.
References iso(), SpeciesRecord::Isotopologue(), QuantumIdentifier::Isotopologue(), Array< base >::nelem(), RetrievalQuantity::QuantumIdentity(), global_data::species_data, and species_match().
species_match() [1/2]
bool species_match (const RetrievalQuantity & rq, const ArrayOfSpeciesTag & ast)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Very slow compared to index input
Parameters
[in] rq A retrieval quantity
[in] ast A list of species tags
Returns
true if all species in the tags list matches the species in the retrieval quantity
false otherwise
Definition at line 1217 of file jacobian.cc.
References QuantumIdentifier::ALL, array_species_tag_from_string(), QuantumIdentifier::Isotopologue(), RetrievalQuantity::QuantumIdentity(), QuantumIdentifier::Species(), RetrievalQuantity::Subtag(), and QuantumIdentifier::Type().
Referenced by species_iso_match().
species_match() [2/2]
bool species_match (const RetrievalQuantity & rq, const Index species)
Returns if the Retrieval quantity is VMR derivative for all the species in the species tags.
Parameters
[in] rq A retrieval quantity
[in] species An index-mapped species
Returns
true the species match the species in the retrieval quantity
false otherwise
Definition at line 1235 of file jacobian.cc.
References RetrievalQuantity::QuantumIdentity(), and QuantumIdentifier::Species().
supports_CIA()
bool supports_CIA (const ArrayOfRetrievalQuantity & js)
Returns if the array supports CIA derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1177 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA().
supports_continuum()
bool supports_continuum (const ArrayOfRetrievalQuantity & js)
Returns if the array supports continuum derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1185 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddConts().
supports_faraday()
bool supports_faraday (const ArrayOfRetrievalQuantity & js)
Returns if the array supports Faraday derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1203 of file jacobian.cc.
Referenced by propmat_clearskyAddFaraday().
supports_hitran_xsec()
bool supports_hitran_xsec (const ArrayOfRetrievalQuantity & js)
Returns if the array supports HITRAN cross-section derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1181 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddHitranXsec().
supports_lookup()
bool supports_lookup (const ArrayOfRetrievalQuantity & js)
Returns if the array supports lookup table derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1197 of file jacobian.cc.
Referenced by propmat_clearskyAddFromLookup().
supports_particles()
bool supports_particles (const ArrayOfRetrievalQuantity & js)
Returns if the array supports particulate derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1209 of file jacobian.cc.
Referenced by propmat_clearskyAddParticles().
supports_propmat_clearsky()
bool supports_propmat_clearsky (const ArrayOfRetrievalQuantity & js)
Returns if the array supports propagation matrix derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1213 of file jacobian.cc.
supports_relaxation_matrix()
bool supports_relaxation_matrix (const ArrayOfRetrievalQuantity & js)
Returns if the array supports relaxation matrix derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
Definition at line 1191 of file jacobian.cc.
supports_zeeman()
bool supports_zeeman (const ArrayOfRetrievalQuantity & js)
Returns if the array supports Zeeman derivatives.
Parameters
[in] js As jacobian_quantities WSV
Returns
true if it does
false if it does not
temperature_perturbation()
Numeric temperature_perturbation (const ArrayOfRetrievalQuantity & js) noexcept
Returns the temperature perturbation if it exists.
Parameters
[in] js As jacobian_quantities WSV
Returns
Temperature perturbation
Definition at line 1277 of file jacobian.cc.
Referenced by abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), propmat_clearskyAddFromLookup(), propmat_clearskyAddParticles(), xsec_species(), and zeeman_on_the_fly().
transform_jacobian()
void transform_jacobian (Matrix & jacobian, const Vector x, const ArrayOfRetrievalQuantity & jqs)
Applies both functional and affine transformations.
Parameters
[in] jacobian As the WSV jacobian
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 90 of file jacobian.cc.
References jac_ranges_indices(), Array< base >::nelem(), transform_x_back(), RetrievalQuantity::TransformationFunc(), and ARTS::Var::x().
Referenced by jacobianAdjustAndTransform().
transform_x()
void transform_x (Vector & x, const ArrayOfRetrievalQuantity & jqs)
Handles transformations of the state vector.
Applies both functional and affine transformations.
Parameters
[in,out] x As the WSV x
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 155 of file jacobian.cc.
References RetrievalQuantity::HasAffine(), jac_ranges_indices(), mult(), Array< base >::nelem(), RetrievalQuantity::OffsetVector(), swap(), RetrievalQuantity::TFuncParameters(), RetrievalQuantity::TransformationFunc(), RetrievalQuantity::TransformationMatrix(), transpose(), and ARTS::Var::x().
transform_x_back()
void transform_x_back (Vector & x_t, const ArrayOfRetrievalQuantity & jqs, bool revert_functional_transforms = true)
Handles back-transformations of the state vector.
Applies both functional and affine transformations.
Parameters
[in] x As the WSV x
[in] jqs As the WSV jacobian_quantities
Author
Simon Pfreundschuh and Patrick Eriksson
Date
2017-12-30
Definition at line 244 of file jacobian.cc.
References RetrievalQuantity::HasAffine(), jac_ranges_indices(), mult(), Array< base >::nelem(), RetrievalQuantity::OffsetVector(), pow(), swap(), RetrievalQuantity::TFuncParameters(), RetrievalQuantity::TransformationFunc(), RetrievalQuantity::TransformationMatrix(), and ARTS::Var::x().
Referenced by jacobianAdjustAndTransform(), transform_jacobian(), x2artsAtmAndSurf(), and x2artsSensor().
vmrunitscf()
void vmrunitscf (Numeric & x, const String & unit, const Numeric & vmr, const Numeric & p, const Numeric & t)
Scale factor for conversion between gas species units.
The function finds the factor with which the total absorption of a gas species shall be multiplicated to match the selected (jacobian) unit.
Parameters
[out] x Scale factor
[in] unit Unit selected.
[in] vmr VMR value.
[in] p Pressure
[in] t Temperature.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 974 of file jacobian.cc.
References number_density(), and ARTS::Var::x().
Referenced by adapt_stepwise_partial_derivatives().