ARTS: legacy_continua.cc File Reference
legacy_continua.cc File Reference
#include "legacy_continua.h"
#include <cmath>
#include "absorption.h"
#include "array.h"
#include "arts.h"
#include "global_data.h"
#include "matpackI.h"
Classes
struct complex_t
struct doublecomplex
struct cilist
struct icilist
struct olist
struct cllist
struct alist
struct inlist
union Multitype
struct Vardesc
struct Namelist
struct s_blockin_
struct s_app3a_
struct s_app3b_
struct s_rsilo_
struct s_bou43_
union u_bba_
struct u_bba_::s_m_1
struct u_bba_::s_m_2
struct s_bbc_
struct s_bf_
struct like_1_
struct s_k1k0_
struct s_bbb_
struct energ_1_
struct s_dimer_
struct n2part_1_
struct n2part_2_
union u_bl3_
struct u_bl3_::s_m_1
struct u_bl3_::s_m_2
union u_bbbb_
struct u_bbbb_::s_m_1
struct u_bbbb_::s_m_2
struct s_energe_
struct s_n2part_
struct s_like_
struct fh2oa_1_
struct fh2ob_1_
struct fh2ob_2_
struct sh2oa_1_
struct sh2ob_1_
struct sh2ob_2_
struct s260a_1_
struct s260b_1_
struct s260b_2_
struct consts_1_
struct s_fh2oa_
struct s_fh2ob_
struct s_sh2oa_
struct s_sh2ob_
struct s_s260a_
struct s_s260b_
struct s_consts_
Macros
#define F2C_INCLUDE
#define TRUE_ (1)
#define FALSE_ (0)
#define Extern extern
#define VOID void
#define abs(x) ((x) >= 0 ? (x) : -(x))
#define dabs(x) (doublereal) abs(x)
#define min(a, b) ((a) <= (b) ? (a) : (b))
#define max(a, b) ((a) >= (b) ? (a) : (b))
#define dmin(a, b) (doublereal) min(a, b)
#define dmax(a, b) (doublereal) max(a, b)
#define bit_test(a, b) ((a) >> (b)&1)
#define bit_clear(a, b) ((a) & ~((uinteger)1 << (b)))
#define bit_set(a, b) ((a) | ((uinteger)1 << (b)))
#define F2C_proc_par_types 1
#define blockin_1 blockin_
#define app3a_1 app3a_
#define app3b_1 app3b_
#define rsilo_1 rsilo_
#define bou43_1 bou43_
#define bba_1 (bba_.m_1)
#define bba_2 (bba_.m_2)
#define bbc_1 bbc_
#define bf_1 bf_
#define like_1 (*(struct like_1_ *)&like_)
#define k1k0_1 k1k0_
#define bbb_1 bbb_
#define energ_1 (*(struct energ_1_ *)&energ_)
#define dimer_1 dimer_
#define n2part_1 (*(struct n2part_1_ *)&n2part_)
#define n2part_2 (*(struct n2part_2_ *)&n2part_)
#define bl3_1 (bl3_.m_1)
#define bl3_2 (bl3_.m_2)
#define bbbb_1 (bbbb_.m_1)
#define bbbb_2 (bbbb_.m_2)
#define temp (blockin_1.temp)
#define fnumin (blockin_1.fnumin)
#define fnumax (blockin_1.fnumax)
#define dnu (blockin_1.dnu)
#define slit (app3a_1.slit)
#define dx (app3a_1.dx)
#define rsilo (rsilo_1.rsilo)
#define omeg (bba_1.omeg)
#define rsi (bba_1.rsi)
#define rsigg (bba_1.rsigg)
#define nsol (bbc_1.nsol)
#define like (like_1.like)
#define ik1k0 (k1k0_1.ik1k0)
#define ibound (bbb_1.ibound)
#define wnrmax3 (app3a_1.wnrmax3)
#define rsilo (rsilo_1.rsilo)
#define omeg (bba_2.omeg)
#define rsigg (bba_2.rsigg)
#define beta (bba_2.beta)
#define nsol (bbc_1.nsol)
#define ibound (bbb_1.ibound)
#define q1 (n2part_1.q1)
#define wn2 (n2part_1.wn2)
#define b01 (n2part_1.b01)
#define d01 (n2part_1.d01)
#define jrange2 (n2part_1.jrange2)
#define q (n2part_2.q)
#define wn2 (n2part_2.wn2)
#define b0 (n2part_2.b0)
#define d0 (n2part_2.d0)
#define jrange1 (n2part_2.jrange1)
#define slit (app3a_1.slit)
#define dx (app3a_1.dx)
#define wnrmax3 (app3a_1.wnrmax3)
#define nsri (app3b_1.nsri)
#define ns (app3b_1.ns)
#define nsriup (app3b_1.nsriup)
#define rsi (bl3_1.rsi)
#define slit (app3a_1.slit)
#define dx (app3a_1.dx)
#define wnrmax3 (app3a_1.wnrmax3)
#define nsri (app3b_1.nsri)
#define ns (app3b_1.ns)
#define nsriup (app3b_1.nsriup)
#define eb (energ_1.eb)
#define niv (energ_1.niv)
#define nlines (dimer_1.nlines)
#define rsibb (bl3_2.rsibb)
#define ldelvi (bbbb_2.ldelvi)
#define ivi (bbbb_2.ivi)
#define ivip (bbbb_2.ivip)
#define ldelel (bbbb_2.ldelel)
#define ll (bbbb_2.ll)
#define llp (bbbb_2.llp)
#define eb_ref(a_1, a_2) eb[(a_2)*41 + a_1 - 42]
#define slit (app3a_1.slit)
#define dx (app3a_1.dx)
#define wnrmax3 (app3a_1.wnrmax3)
#define nsri (app3b_1.nsri)
#define ns (app3b_1.ns)
#define nsriup (app3b_1.nsriup)
#define eb (energ_1.eb)
#define niv (energ_1.niv)
#define nlines (dimer_1.nlines)
#define rsibb (bl3_2.rsibb)
#define eb_ref(a_1, a_2) eb[(a_2)*41 + a_1 - 42]
#define ik1k0 (k1k0_1.ik1k0)
#define fh2oa_1 (*(struct fh2oa_1_ *)&fh2oa_)
#define fh2ob_1 (*(struct fh2ob_1_ *)&fh2ob_)
#define fh2ob_2 (*(struct fh2ob_2_ *)&fh2ob_)
#define sh2oa_1 (*(struct sh2oa_1_ *)&sh2oa_)
#define sh2ob_1 (*(struct sh2ob_1_ *)&sh2ob_)
#define sh2ob_2 (*(struct sh2ob_2_ *)&sh2ob_)
#define s260a_1 (*(struct s260a_1_ *)&s260a_)
#define s260b_1 (*(struct s260b_1_ *)&s260b_)
#define s260b_2 (*(struct s260b_2_ *)&s260b_)
#define consts_1 (*(struct consts_1_ *)&consts_)
Typedefs
typedef long int integer
typedef unsigned long int uinteger
typedef char * address
typedef short int shortint
typedef float real_t
typedef double doublereal
typedef long int logical
typedef short int shortlogical
typedef char logical1
typedef char integer1
typedef long int flag
typedef long int ftnlen
typedef long int ftnint
typedef union Multitype Multitype
typedef struct Vardesc Vardesc
typedef struct Namelist Namelist
typedef int(* U_fp) ()
typedef shortint(* J_fp) ()
typedef integer(* I_fp) ()
typedef real_t(* R_fp) ()
typedef doublereal(* D_fp) ()
typedef doublereal(*)(* E_fp) ()
typedef VOID(* C_fp) ()
typedef VOID(* Z_fp) ()
typedef logical(* L_fp) ()
typedef shortlogical(* K_fp) ()
typedef VOID(* H_fp) ()
typedef int(* S_fp) ()
typedef VOID C_f
typedef VOID H_f
typedef VOID Z_f
typedef doublereal E_f
Functions
void MPM87H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM87H2OAbsModel.
void MPM89H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM89H2OAbsModel.
void MPM02H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM02H2OAbsModel.
void MPM93H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93H2OAbsModel.
void PWR98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
PWR98H2OAbsModel.
void CP98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CP98H2OAbsModel.
void Standard_H2O_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_self_continuum.
void Standard_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_foreign_continuum.
void MaTipping_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MaTipping_H2O_foreign_continuum.
Numeric XINT_FUN (const Numeric V1A, const Numeric, const Numeric DVA, ConstVectorView A, const Numeric VI)
Numeric XINT_FUN (const Numeric V1A, const Numeric, const Numeric DVA, const Numeric A[], const Index nA, const Numeric VI)
Numeric RADFN_FUN (const Numeric VI, const Numeric XKT)
void CKD_222_self_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
void CKD_222_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
void CKD_242_self_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
void CKD_242_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
void CKD_mt_100_self_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
void CKD_mt_100_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
void CKD_mt_250_self_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 2.50 H2O self continuum absorption model.
void CKD_mt_250_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 2.50 H2O foreign continuum absorption model.
void CKD_mt_320_self_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 3.20 H2O self continuum absorption model.
void CKD_mt_320_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 3.20 H2O foreign continuum absorption model.
void CKD_241_co2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
void CKD_mt_co2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
void CKD_mt_250_co2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 2.50 CO2 continuum absorption model.
void CKD_mt_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
void CKD_mt_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
void CKD_mt_250_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity &verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (rotational band)
void CKD_mt_250_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity &verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (fundamental band)
void CKD_mt_CIAfun_o2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
void CKD_mt_v0v0_o2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
void CKD_mt_v1v0_o2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
void CKD_mt_250_o2_vis (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView DEBUG_ONLY(vmr), const Verbosity &verbosity)
CKD version MT 2.50 O2.
void CKD24_H20 (MatrixView pxsec, int isf, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.4 H2O continuum absorption model.
void Pardo_ATM_H2O_ForeignContinuum (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Pardo_ATM_H2O_ForeignContinuum.
void MPM93_H2O_continuum (MatrixView pxsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 H2O pseudo continuum line parameters:
void MPM85O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM85O2AbsModel.
void MPM87O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM87O2AbsModel.
void MPM89O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM89O2AbsModel.
void MPM92O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM92O2AbsModel.
void TRE05O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
TRE05O2AbsModel.
void MPM93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93O2AbsModel.
void PWR93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String &model, const String &version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmrh2o, ConstVectorView vmr, const Verbosity &verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
void MPM93_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 O2 continuum:
void Rosenkranz_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
3) O2-air
void Standard_O2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric G0in, const Numeric G0Ain, const Numeric G0Bin, const Numeric XG0din, const Numeric XG0win, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
Standard_O2_continuum.
void BF86_CIA_N2 (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
void MPM93_N2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 N2 continuum.
void Pardo_ATM_N2_dry_continuum (MatrixView pxsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView h2ovmr, const Verbosity &verbosity)
Pardo_ATM_N2_dry_continuum.
void Rosenkranz_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_N2_self_continuum.
void Standard_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
4) N2-N2
void Rosenkranz_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_self_continuum.
void Rosenkranz_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_foreign_continuum.
void Ho66_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Ho66_CO2_self_continuum.
void Ho66_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity &verbosity)
Ho66_CO2_foreign_continuum.
void MPM93WaterDropletAbs (MatrixView pxsec, const Numeric CCin, const Numeric CGin, const Numeric CEin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93WaterDropletAbs.
void ELL07WaterDropletAbs (MatrixView pxsec, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
ELL07WaterDropletAbs.
void MPM93IceCrystalAbs (MatrixView pxsec, const Numeric CCin, const Numeric CAin, const Numeric CBin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93IceCrystalAbs.
void MPM93RainExt (MatrixView pxsec, const Numeric CEin, const Numeric CAin, const Numeric CBin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93RainExt.
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
void xsec_continuum_tag (MatrixView xsec, const String &name, ConstVectorView parameters, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView abs_o2, ConstVectorView vmr, const Verbosity &verbosity)
Calculates model absorption for one continuum or full model tag.
void check_continuum_model (const String &name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
Numeric n2n2tks_ (double t, double f)
int addspec_ (double *g0, double *ep, double *tau1, double *tau2, double *tau5, double *tau6, double *temp, int *nf, double *freq, double *abscoef, int *, int *like, int *lambda1, int *lambda2, int *lambda, int *)
int partsum_ (double *temp)
int profile_ (double *x, double *y)
double specfct_ (double *freq, double *omega, double *phi, double *phi2, int *n, double *rtemp)
int bound32_ (double *temp, double *rsi, int *nsol)
int bound54_ (double *temp, double *rsi, int *nsol)
double clebsqr_0_ (int n__, int *l, int *lambda, int *lp)
double clebsqr_ (int *l, int *lambda, int *lp)
double fctl_ (int *n)
double bgama_ (double *fnu, double *t1, double *t2, double *eps, double *t3, double *t4, double *temp)
int spline_0_ (int n__, int *l, int *m, int *k, double *eps, double *x, double *y, double *t, double *ss, double *si, int *nr, double *s2)
int spline_ (int *l, int *m, int *k, double *eps, double *x, double *y, double *t, double *ss, double *si, int *nr, double *s2)
int ixpolat_ (int *l, int *m, int *k, double *eps, double *x, double *y, double *t, double *ss, double *si, int *nr, double *s2)
double artsckd_ (double p, double t, double vmrh2o, double vmrn2, double vmro2, double freq, int ivc)
double fwv_ (int ivc, double wn, double *w_wv__, double *rft, double *xn, double *xn_wv__, double *xn0, double *xfrg)
double fwv_mpmf87s93__ (double wn, double *w_wv__, double *rft, double *xn, double *xn_wv__, double *xn0, double *xfrg)
double fwv24_ (double wn, double *w_wv__, double *rft, double *xn, double *xn_wv__, double *xn0, double *xfrg)
double swv_ (int ivc, double wn, double t, double *t0, double *w_wv__, double *rft, double *xn, double *xn_wv__, double *xn0, double *xslf)
double swv24_ (double wn, double t, double *t0, double *w_wv__, double *rft, double *, double *xn_wv__, double *xn0, double *xslf)
double swv_mpmf87s93__ (double wn, double t, double *t0, double *w_wv__, double *rft, double *, double *xn_wv__, double *xn0, double *xslf)
double conti_n2__ (double wn, double t, double *t0, double *w_n2__, double *rft, double *rhofac, double *xcn2)
double xlgr_ (double *xf, double *x)
int initi_ (double p, double t, double *radct, double *t0, double *p0, double *w_wv__, double *w_o2__, double *w_n2__, double *w_other__, double *xn0, double *xn, double *xn_wv__, double *rhofac)
int phys_consts__ (void)
int bsa296_ (void)
int bsb296_ (void)
int bs260a_ (void)
int bs260b_ (void)
int bfh2oa_ (void)
int bfh2ob_ (void)
Variables
const Numeric EULER_NUMBER
const Numeric LOG10_EULER_NUMBER
const Numeric NAT_LOG_TEN
const Numeric PI
const Numeric SPEED_OF_LIGHT
const Numeric DENSITY_OF_WATER
const Numeric LIQUID_AND_ICE_TREAT_AS_ZERO = 1e-10
const Numeric Hz_to_GHz = 1.000000e-9
const Numeric Pa_to_kPa = 1.000000e-3
const Numeric Pa_to_hPa = 1.000000e-2
const Numeric dB_km_to_1_m = (1.00000e-3 / (10.0 * LOG10_EULER_NUMBER))
const Numeric VMRCalcLimit = 1.000e-25
const int addF77fields = 1
const Numeric SL296_ckd_0_v1 = -20.0
const Numeric SL296_ckd_0_v2 = 20000.0
const Numeric SL296_ckd_0_dv = 10.0
const int SL296_ckd_0_npt = 2003
const double SL296_ckd_0 [SL296_ckd_0_npt+addF77fields]
const Numeric FH2O_ckd_0_v1 = -20.0
const Numeric FH2O_ckd_0_v2 = 20000.0
const Numeric FH2O_ckd_0_dv = 10.0
const int FH2O_ckd_0_npt = 2003
const double FH2O_ckd_0 [FH2O_ckd_0_npt+addF77fields]
const Numeric SL260_ckd_0_v1 = -20.0
const Numeric SL260_ckd_0_v2 = 20000.0
const Numeric SL260_ckd_0_dv = 10.0
const int SL260_ckd_0_npt = 2003
const double SL260_ckd_0 [SL260_ckd_0_npt+addF77fields]
const Numeric SL296_ckd_mt_100_v1 = -20.0
const Numeric SL296_ckd_mt_100_v2 = 20000.0
const Numeric SL296_ckd_mt_100_dv = 10.0
const int SL296_ckd_mt_100_npt = 2003
const double SL296_ckd_mt_100 [SL296_ckd_mt_100_npt+addF77fields]
const Numeric SL260_ckd_mt_100_v1 = -20.0
const Numeric SL260_ckd_mt_100_v2 = 20000.0
const Numeric SL260_ckd_mt_100_dv = 10.0
const int SL260_ckd_mt_100_npt = 2003
const double SL260_ckd_mt_100 [SL260_ckd_mt_100_npt+addF77fields]
const Numeric FH2O_ckd_mt_100_v1 = -20.0
const Numeric FH2O_ckd_mt_100_v2 = 20000.0
const Numeric FH2O_ckd_mt_100_dv = 10.0
const int FH2O_ckd_mt_100_npt = 2003
const double FH2O_ckd_mt_100 [FH2O_ckd_mt_100_npt+addF77fields]
const Numeric SL296_ckd_mt_320_v1 = -20.0
const Numeric SL296_ckd_mt_320_v2 = 20000.0
const Numeric SL296_ckd_mt_320_dv = 10.0
const int SL296_ckd_mt_320_npt = 2003
const double SL296_ckd_mt_320 [SL296_ckd_mt_320_npt+addF77fields]
const Numeric SL260_ckd_mt_320_v1 = -20.0
const Numeric SL260_ckd_mt_320_v2 = 20000.0
const Numeric SL260_ckd_mt_320_dv = 10.0
const int SL260_ckd_mt_320_npt = 2003
const double SL260_ckd_mt_320 [SL260_ckd_mt_320_npt+addF77fields]
const Numeric FH2O_ckd_mt_320_v1 = -20.0
const Numeric FH2O_ckd_mt_320_v2 = 20000.0
const Numeric FH2O_ckd_mt_320_dv = 10.0
const int FH2O_ckd_mt_320_npt = 2003
const double FH2O_ckd_mt_320 [FH2O_ckd_mt_320_npt+addF77fields]
const Numeric FCO2_ckd_mt_100_v1 = -20.0
const Numeric FCO2_ckd_mt_100_v2 = 10000.0
const Numeric FCO2_ckd_mt_100_dv = 10.0
const int FCO2_ckd_mt_100_npt = 1003
const double FCO2_ckd_mt_100 [FCO2_ckd_mt_100_npt+addF77fields]
const Numeric FCO2_ckd_mt_250_v1 = -4.0
const Numeric FCO2_ckd_mt_250_v2 = 10000.0
const Numeric FCO2_ckd_mt_250_dv = 2.0
const int FCO2_ckd_mt_250_npt = 5003
const double FCO2_ckd_mt_250 [FCO2_ckd_mt_250_npt+addF77fields]
const Numeric N2N2_CT296_ckd_mt_100_v1 = -10.0
const Numeric N2N2_CT296_ckd_mt_100_v2 = 350.0
const Numeric N2N2_CT296_ckd_mt_100_dv = 5.0
const int N2N2_CT296_ckd_mt_100_npt = 73
const double N2N2_CT296_ckd_mt_100 [N2N2_CT296_ckd_mt_100_npt+addF77fields]
const double N2N2_sf_296_ckd_mt_100 [N2N2_CT296_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_CT220_ckd_mt_100_v1 = -10.0
const Numeric N2N2_CT220_ckd_mt_100_v2 = 350.0
const Numeric N2N2_CT220_ckd_mt_100_dv = 5.0
const int N2N2_CT220_ckd_mt_100_npt = 73
const double N2N2_CT220_ckd_mt_100 [N2N2_CT220_ckd_mt_100_npt+addF77fields]
const double N2N2_sf_220_ckd_mt_100 [N2N2_CT220_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_N2F_ckd_mt_100_v1 = 2085.000
const Numeric N2N2_N2F_ckd_mt_100_v2 = 2670.000
const Numeric N2N2_N2F_ckd_mt_100_dv = 5.000
const int N2N2_N2F_ckd_mt_100_npt = 118
const double N2N2_N2F_ckd_mt_100 [N2N2_N2F_ckd_mt_100_npt+addF77fields]
const double N2N2_N2Ft_ckd_mt_100 [N2N2_N2F_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_N2F_ckd_mt_250_v1 = 2001.766357
const Numeric N2N2_N2F_ckd_mt_250_v2 = 2710.45
const Numeric N2N2_N2F_ckd_mt_250_dv = 3.981461525
const int N2N2_N2F_ckd_mt_250_npt = 179
const double N2N2_N2F_ckd_mt_250 [N2N2_N2F_ckd_mt_250_npt+addF77fields]
const double N2N2_N2Ft_ckd_mt_250 [N2N2_N2F_ckd_mt_250_npt+addF77fields]
const Numeric O2O2_O2F_ckd_mt_100_v1 = 1340.000
const Numeric O2O2_O2F_ckd_mt_100_v2 = 1850.000
const Numeric O2O2_O2F_ckd_mt_100_dv = 5.000
const int O2O2_O2F_ckd_mt_100_npt = 103
const double O2O2_O2Fo_ckd_mt_100 [O2O2_O2F_ckd_mt_100_npt+addF77fields]
const double O2O2_O2Ft_ckd_mt_100 [O2O2_O2F_ckd_mt_100_npt+addF77fields]
const Numeric O2_00_ckd_mt_100_v1 = 7536.000e0
const Numeric O2_00_ckd_mt_100_v2 = 8500.000e0
const Numeric O2_00_ckd_mt_100_dv = 2.000e0
const int O2_00_ckd_mt_100_npt = 483
const double O2_00_ckd_mt_100 [O2_00_ckd_mt_100_npt+addF77fields]
const Numeric O2_10_ckd_mt_100_v1 = 9100.000e0
const Numeric O2_10_ckd_mt_100_v2 = 11000.000e0
const Numeric O2_10_ckd_mt_100_dv = 2.000e0
const Numeric O2_vis_ckd_mt_250_v1 = 15000.000e0
const Numeric O2_vis_ckd_mt_250_v2 = 29870.000e0
const Numeric O2_vis_ckd_mt_250_dv = 10.000e0
const int O2_vis_ckd_mt_250_npt = 1488
const double O2_vis_ckd_mt_250 [O2_vis_ckd_mt_250_npt+addF77fields]
struct s_blockin_ blockin_
struct s_app3a_ app3a_
struct s_app3b_ app3b_
struct s_rsilo_ rsilo_
struct s_bou43_ bou43_
union u_bba_ bba_
struct s_bbc_ bbc_
struct s_bf_ bf_
struct s_k1k0_ k1k0_
struct s_bbb_ bbb_
struct s_dimer_ dimer_
union u_bl3_ bl3_
union u_bbbb_ bbbb_
struct s_energe_ energ_
struct s_n2part_ n2part_ = {{0}, {2., 1., 1.98957, 5.8e-6}, {0}}
struct s_like_ like_ = {{0}, "N2N2"}
struct s_fh2oa_ fh2oa_
struct s_fh2ob_ fh2ob_ = {{-20., 2e4, 10.}, 2003}
struct s_sh2oa_ sh2oa_
struct s_sh2ob_ sh2ob_ = {{-20., 2e4, 10.}, 2003}
struct s_s260a_ s260a_
struct s_s260b_ s260b_ = {{-20., 2e4, 10.}, 2003}
struct s_consts_ consts_
Macro Definition Documentation
abs
#define abs (x) ((x) >= 0 ? (x) : -(x))
Definition at line 20626 of file legacy_continua.cc.
app3a_1
#define app3a_1 app3a_
Definition at line 20715 of file legacy_continua.cc.
app3b_1
#define app3b_1 app3b_
Definition at line 20721 of file legacy_continua.cc.
b0
#define b0 (n2part_2.b0)
Definition at line 21714 of file legacy_continua.cc.
b01
#define b01 (n2part_1.b01)
Definition at line 21440 of file legacy_continua.cc.
bba_1
#define bba_1 (bba_.m_1)
Definition at line 20744 of file legacy_continua.cc.
bba_2
#define bba_2 (bba_.m_2)
Definition at line 20745 of file legacy_continua.cc.
bbb_1
#define bbb_1 bbb_
Definition at line 20776 of file legacy_continua.cc.
bbbb_1
#define bbbb_1 (bbbb_.m_1)
Definition at line 20824 of file legacy_continua.cc.
bbbb_2
#define bbbb_2 (bbbb_.m_2)
Definition at line 20825 of file legacy_continua.cc.
bbc_1
#define bbc_1 bbc_
Definition at line 20751 of file legacy_continua.cc.
beta
#define beta (bba_2.beta)
Definition at line 21435 of file legacy_continua.cc.
bf_1
#define bf_1 bf_
Definition at line 20757 of file legacy_continua.cc.
bit_clear
#define bit_clear (a, b) ((a) & ~((uinteger)1 << (b)))
Definition at line 20633 of file legacy_continua.cc.
bit_set
#define bit_set (a, b) ((a) | ((uinteger)1 << (b)))
Definition at line 20634 of file legacy_continua.cc.
bit_test
#define bit_test (a, b) ((a) >> (b)&1)
Definition at line 20632 of file legacy_continua.cc.
bl3_1
#define bl3_1 (bl3_.m_1)
Definition at line 20812 of file legacy_continua.cc.
bl3_2
#define bl3_2 (bl3_.m_2)
Definition at line 20813 of file legacy_continua.cc.
blockin_1
#define blockin_1 blockin_
Definition at line 20709 of file legacy_continua.cc.
bou43_1
#define bou43_1 bou43_
Definition at line 20733 of file legacy_continua.cc.
consts_1
#define consts_1 (*(struct consts_1_ *)&consts_)
Definition at line 22969 of file legacy_continua.cc.
d0
#define d0 (n2part_2.d0)
Definition at line 21715 of file legacy_continua.cc.
d01
#define d01 (n2part_1.d01)
Definition at line 21441 of file legacy_continua.cc.
dabs
#define dabs (x) (doublereal) abs(x)
Definition at line 20627 of file legacy_continua.cc.
dimer_1
#define dimer_1 dimer_
Definition at line 20789 of file legacy_continua.cc.
dmax
#define dmax (a, b) (doublereal) max(a, b)
Definition at line 20631 of file legacy_continua.cc.
dmin
#define dmin (a, b) (doublereal) min(a, b)
Definition at line 20630 of file legacy_continua.cc.
dnu
#define dnu (blockin_1.dnu)
Definition at line 20954 of file legacy_continua.cc.
dx [1/4]
#define dx (app3a_1.dx)
Definition at line 22180 of file legacy_continua.cc.
dx [2/4]
#define dx (app3a_1.dx)
Definition at line 22180 of file legacy_continua.cc.
dx [3/4]
#define dx (app3a_1.dx)
Definition at line 22180 of file legacy_continua.cc.
dx [4/4]
#define dx (app3a_1.dx)
Definition at line 22180 of file legacy_continua.cc.
eb [1/2]
#define eb (energ_1.eb)
Definition at line 22185 of file legacy_continua.cc.
eb [2/2]
#define eb (energ_1.eb)
Definition at line 22185 of file legacy_continua.cc.
eb_ref [1/2]
#define eb_ref (a_1, a_2) eb[(a_2)*41 + a_1 - 42]
eb_ref [2/2]
#define eb_ref (a_1, a_2) eb[(a_2)*41 + a_1 - 42]
energ_1
#define energ_1 (*(struct energ_1_ *)&energ_)
Definition at line 20783 of file legacy_continua.cc.
Extern
#define Extern extern
Definition at line 20503 of file legacy_continua.cc.
F2C_INCLUDE
#define F2C_INCLUDE
Definition at line 20473 of file legacy_continua.cc.
F2C_proc_par_types
#define F2C_proc_par_types 1
Definition at line 20638 of file legacy_continua.cc.
FALSE_
#define FALSE_ (0)
Definition at line 20499 of file legacy_continua.cc.
fh2oa_1
#define fh2oa_1 (*(struct fh2oa_1_ *)&fh2oa_)
Definition at line 22915 of file legacy_continua.cc.
fh2ob_1
#define fh2ob_1 (*(struct fh2ob_1_ *)&fh2ob_)
Definition at line 22926 of file legacy_continua.cc.
fh2ob_2
#define fh2ob_2 (*(struct fh2ob_2_ *)&fh2ob_)
Definition at line 22927 of file legacy_continua.cc.
fnumax
#define fnumax (blockin_1.fnumax)
Definition at line 20953 of file legacy_continua.cc.
fnumin
#define fnumin (blockin_1.fnumin)
Definition at line 20952 of file legacy_continua.cc.
ibound [1/2]
#define ibound (bbb_1.ibound)
Definition at line 21437 of file legacy_continua.cc.
ibound [2/2]
#define ibound (bbb_1.ibound)
Definition at line 21437 of file legacy_continua.cc.
ik1k0 [1/2]
#define ik1k0 (k1k0_1.ik1k0)
Definition at line 22482 of file legacy_continua.cc.
ik1k0 [2/2]
#define ik1k0 (k1k0_1.ik1k0)
Definition at line 22482 of file legacy_continua.cc.
ivi
#define ivi (bbbb_2.ivi)
Definition at line 21956 of file legacy_continua.cc.
ivip
#define ivip (bbbb_2.ivip)
Definition at line 21957 of file legacy_continua.cc.
jrange1
#define jrange1 (n2part_2.jrange1)
Definition at line 21716 of file legacy_continua.cc.
jrange2
#define jrange2 (n2part_1.jrange2)
Definition at line 21442 of file legacy_continua.cc.
k1k0_1
#define k1k0_1 k1k0_
Definition at line 20770 of file legacy_continua.cc.
ldelel
#define ldelel (bbbb_2.ldelel)
Definition at line 21958 of file legacy_continua.cc.
ldelvi
#define ldelvi (bbbb_2.ldelvi)
Definition at line 21955 of file legacy_continua.cc.
like
#define like (like_1.like)
Definition at line 20962 of file legacy_continua.cc.
like_1
#define like_1 (*(struct like_1_ *)&like_)
Definition at line 20764 of file legacy_continua.cc.
ll
#define ll (bbbb_2.ll)
Definition at line 21959 of file legacy_continua.cc.
llp
#define llp (bbbb_2.llp)
Definition at line 21960 of file legacy_continua.cc.
max
#define max (a, b) ((a) >= (b) ? (a) : (b))
Definition at line 20629 of file legacy_continua.cc.
min
#define min (a, b) ((a) <= (b) ? (a) : (b))
Definition at line 20628 of file legacy_continua.cc.
n2part_1
#define n2part_1 (*(struct n2part_1_ *)&n2part_)
Definition at line 20800 of file legacy_continua.cc.
n2part_2
#define n2part_2 (*(struct n2part_2_ *)&n2part_)
Definition at line 20801 of file legacy_continua.cc.
niv [1/2]
#define niv (energ_1.niv)
Definition at line 22186 of file legacy_continua.cc.
niv [2/2]
#define niv (energ_1.niv)
Definition at line 22186 of file legacy_continua.cc.
nlines [1/2]
#define nlines (dimer_1.nlines)
Definition at line 22187 of file legacy_continua.cc.
nlines [2/2]
#define nlines (dimer_1.nlines)
Definition at line 22187 of file legacy_continua.cc.
ns [1/3]
#define ns (app3b_1.ns)
Definition at line 22183 of file legacy_continua.cc.
ns [2/3]
#define ns (app3b_1.ns)
Definition at line 22183 of file legacy_continua.cc.
ns [3/3]
#define ns (app3b_1.ns)
Definition at line 22183 of file legacy_continua.cc.
nsol [1/2]
#define nsol (bbc_1.nsol)
Definition at line 21436 of file legacy_continua.cc.
nsol [2/2]
#define nsol (bbc_1.nsol)
Definition at line 21436 of file legacy_continua.cc.
nsri [1/3]
#define nsri (app3b_1.nsri)
Definition at line 22182 of file legacy_continua.cc.
nsri [2/3]
#define nsri (app3b_1.nsri)
Definition at line 22182 of file legacy_continua.cc.
nsri [3/3]
#define nsri (app3b_1.nsri)
Definition at line 22182 of file legacy_continua.cc.
nsriup [1/3]
#define nsriup (app3b_1.nsriup)
Definition at line 22184 of file legacy_continua.cc.
nsriup [2/3]
#define nsriup (app3b_1.nsriup)
Definition at line 22184 of file legacy_continua.cc.
nsriup [3/3]
#define nsriup (app3b_1.nsriup)
Definition at line 22184 of file legacy_continua.cc.
omeg [1/2]
#define omeg (bba_1.omeg)
Definition at line 21433 of file legacy_continua.cc.
omeg [2/2]
#define omeg (bba_2.omeg)
Definition at line 21433 of file legacy_continua.cc.
q
#define q (n2part_2.q)
Definition at line 21712 of file legacy_continua.cc.
q1
#define q1 (n2part_1.q1)
Definition at line 21438 of file legacy_continua.cc.
rsi [1/2]
#define rsi (bba_1.rsi)
Definition at line 21759 of file legacy_continua.cc.
rsi [2/2]
#define rsi (bl3_1.rsi)
Definition at line 21759 of file legacy_continua.cc.
rsibb [1/2]
#define rsibb (bl3_2.rsibb)
Definition at line 22188 of file legacy_continua.cc.
rsibb [2/2]
#define rsibb (bl3_2.rsibb)
Definition at line 22188 of file legacy_continua.cc.
rsigg [1/2]
#define rsigg (bba_1.rsigg)
Definition at line 21434 of file legacy_continua.cc.
rsigg [2/2]
#define rsigg (bba_2.rsigg)
Definition at line 21434 of file legacy_continua.cc.
rsilo [1/2]
#define rsilo (rsilo_1.rsilo)
Definition at line 21432 of file legacy_continua.cc.
rsilo [2/2]
#define rsilo (rsilo_1.rsilo)
Definition at line 21432 of file legacy_continua.cc.
rsilo_1
#define rsilo_1 rsilo_
Definition at line 20727 of file legacy_continua.cc.
s260a_1
#define s260a_1 (*(struct s260a_1_ *)&s260a_)
Definition at line 22951 of file legacy_continua.cc.
s260b_1
#define s260b_1 (*(struct s260b_1_ *)&s260b_)
Definition at line 22962 of file legacy_continua.cc.
s260b_2
#define s260b_2 (*(struct s260b_2_ *)&s260b_)
Definition at line 22963 of file legacy_continua.cc.
sh2oa_1
#define sh2oa_1 (*(struct sh2oa_1_ *)&sh2oa_)
Definition at line 22933 of file legacy_continua.cc.
sh2ob_1
#define sh2ob_1 (*(struct sh2ob_1_ *)&sh2ob_)
Definition at line 22944 of file legacy_continua.cc.
sh2ob_2
#define sh2ob_2 (*(struct sh2ob_2_ *)&sh2ob_)
Definition at line 22945 of file legacy_continua.cc.
slit [1/4]
#define slit (app3a_1.slit)
Definition at line 22179 of file legacy_continua.cc.
slit [2/4]
#define slit (app3a_1.slit)
Definition at line 22179 of file legacy_continua.cc.
slit [3/4]
#define slit (app3a_1.slit)
Definition at line 22179 of file legacy_continua.cc.
slit [4/4]
#define slit (app3a_1.slit)
Definition at line 22179 of file legacy_continua.cc.
temp
#define temp (blockin_1.temp)
Definition at line 20951 of file legacy_continua.cc.
TRUE_
#define TRUE_ (1)
Definition at line 20498 of file legacy_continua.cc.
VOID
#define VOID void
Definition at line 20594 of file legacy_continua.cc.
wn2 [1/2]
#define wn2 (n2part_1.wn2)
Definition at line 21713 of file legacy_continua.cc.
wn2 [2/2]
#define wn2 (n2part_2.wn2)
Definition at line 21713 of file legacy_continua.cc.
wnrmax3 [1/4]
#define wnrmax3 (app3a_1.wnrmax3)
Definition at line 22181 of file legacy_continua.cc.
wnrmax3 [2/4]
#define wnrmax3 (app3a_1.wnrmax3)
Definition at line 22181 of file legacy_continua.cc.
wnrmax3 [3/4]
#define wnrmax3 (app3a_1.wnrmax3)
Definition at line 22181 of file legacy_continua.cc.
wnrmax3 [4/4]
#define wnrmax3 (app3a_1.wnrmax3)
Definition at line 22181 of file legacy_continua.cc.
Typedef Documentation
address
typedef char* address
Definition at line 20477 of file legacy_continua.cc.
C_f
typedef VOID C_f
Definition at line 20665 of file legacy_continua.cc.
C_fp
typedef VOID(* C_fp) ()
Definition at line 20657 of file legacy_continua.cc.
D_fp
typedef doublereal(* D_fp) ()
Definition at line 20656 of file legacy_continua.cc.
doublereal
typedef double doublereal
Definition at line 20480 of file legacy_continua.cc.
E_f
typedef doublereal E_f
Definition at line 20668 of file legacy_continua.cc.
E_fp
typedef doublereal(*)(* E_fp) ()
Definition at line 20656 of file legacy_continua.cc.
flag
typedef long int flag
Definition at line 20514 of file legacy_continua.cc.
ftnint
typedef long int ftnint
Definition at line 20516 of file legacy_continua.cc.
ftnlen
typedef long int ftnlen
Definition at line 20515 of file legacy_continua.cc.
H_f
typedef VOID H_f
Definition at line 20666 of file legacy_continua.cc.
H_fp
typedef VOID(* H_fp) ()
Definition at line 20661 of file legacy_continua.cc.
I_fp
typedef integer(* I_fp) ()
Definition at line 20654 of file legacy_continua.cc.
integer
typedef long int integer
Definition at line 20475 of file legacy_continua.cc.
integer1
typedef char integer1
Definition at line 20490 of file legacy_continua.cc.
J_fp
typedef shortint(* J_fp) ()
Definition at line 20653 of file legacy_continua.cc.
K_fp
typedef shortlogical(* K_fp) ()
Definition at line 20660 of file legacy_continua.cc.
L_fp
typedef logical(* L_fp) ()
Definition at line 20659 of file legacy_continua.cc.
logical
typedef long int logical
Definition at line 20487 of file legacy_continua.cc.
logical1
typedef char logical1
Definition at line 20489 of file legacy_continua.cc.
Multitype
typedef union Multitype Multitype
Definition at line 20516 of file legacy_continua.cc.
Namelist
typedef struct Namelist Namelist
Definition at line 20516 of file legacy_continua.cc.
R_fp
typedef real_t(* R_fp) ()
Definition at line 20655 of file legacy_continua.cc.
real_t
typedef float real_t
Definition at line 20479 of file legacy_continua.cc.
S_fp
typedef int(* S_fp) ()
Definition at line 20662 of file legacy_continua.cc.
shortint
typedef short int shortint
Definition at line 20478 of file legacy_continua.cc.
shortlogical
typedef short int shortlogical
Definition at line 20488 of file legacy_continua.cc.
U_fp
typedef int(* U_fp) ()
Definition at line 20652 of file legacy_continua.cc.
uinteger
typedef unsigned long int uinteger
Definition at line 20476 of file legacy_continua.cc.
Vardesc
typedef struct Vardesc Vardesc
Definition at line 20516 of file legacy_continua.cc.
Z_f
typedef VOID Z_f
Definition at line 20667 of file legacy_continua.cc.
Z_fp
typedef VOID(* Z_fp) ()
Definition at line 20658 of file legacy_continua.cc.
Function Documentation
addspec_()
int addspec_ (double * g0, double * ep, double * tau1, double * tau2, double * tau5, double * tau6, double * temp, int * nf, double * freq, double * abscoef, int * , int * like, int * lambda1, int * lambda2, int * lambda, int *)
Definition at line 21446 of file legacy_continua.cc.
artsckd_()
double artsckd_ (double p, double t, double vmrh2o, double vmrn2, double vmro2, double freq, int ivc)
Definition at line 24052 of file legacy_continua.cc.
References conti_n2__(), fwv_(), initi_(), and swv_().
Referenced by CKD24_H20().
BF86_CIA_N2()
void BF86_CIA_N2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
see publication A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see http://adsabs.harvard.edu/article_service.html for a scanned version of the paper
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-CIA according to BF-86 model [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Note
this "crude" version of the N2-N2 model is a f2c conversion of the N2-N2 F77 code of Prof. A. Borysow. The original code can be downloaded at F77 code.
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-05
Definition at line 14522 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), n2n2tks_(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
bfh2oa_()
int bfh2oa_ (void)
Definition at line 24768 of file legacy_continua.cc.
bfh2ob_()
int bfh2ob_ (void)
Definition at line 24770 of file legacy_continua.cc.
bgama_()
double bgama_ (double * fnu, double * t1, double * t2, double * eps, double * t3, double * t4, double * temp)
Definition at line 22484 of file legacy_continua.cc.
bound32_()
int bound32_ (double * temp, double * rsi, int * nsol)
Definition at line 21962 of file legacy_continua.cc.
bound54_()
int bound54_ (double * temp, double * rsi, int * nsol)
Definition at line 22190 of file legacy_continua.cc.
bs260a_()
int bs260a_ (void)
Definition at line 24762 of file legacy_continua.cc.
bs260b_()
int bs260b_ (void)
Definition at line 24764 of file legacy_continua.cc.
bsa296_()
int bsa296_ (void)
Definition at line 24756 of file legacy_continua.cc.
bsb296_()
int bsb296_ (void)
Definition at line 24758 of file legacy_continua.cc.
check_continuum_model()
void check_continuum_model (const String & name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
This is just in order to verify that this really represents a valid continuum model.
The given name should be something like 'H2O-ContStandardSelf'. The function simply checks if there is a species H2O with an isotopologue ContStandardSelf.
For user-friendliness, the function also compiles a list of allowed continuum models and gives this as an error message if the model is not found.
The function has no return value, since, if the name does not match a valid model an error is thrown anyway.
Parameters
name The name of the continuum model to check.
Exceptions
runtime_error The model does not exist.
Author
Stefan Buehler
Date
2001-03-12
Definition at line 20406 of file legacy_continua.cc.
References Zeeman::end(), Isotopologue, and global_data::species_data.
Referenced by abs_cont_descriptionAppend().
CKD24_H20()
void CKD24_H20 (MatrixView pxsec, int isf, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.4 H2O continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O continuum according to CKD2.4 [1/m]
isf =0 self continuum, =1 foreign continuum
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
this "crude" version of the CKD2.4 model is a f2c conversion of the F77 code taken out of MonoRTM RT-model written by
S. BOUKABARA, S.A. CLOUGH, and R. HOFFMAN
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421
USA
E-mail: sbouk.nosp@m.aba@.nosp@m.aer.c.nosp@m.om, cloug.nosp@m.h@ae.nosp@m.r.com
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-06
Definition at line 11744 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), artsckd_(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
CKD_222_foreign_h2o()
void CKD_222_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.2.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 7437 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_222_self_h2o()
void CKD_222_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_2_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-31-10
Definition at line 7181 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_241_co2()
void CKD_241_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.1 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 9506 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_242_foreign_h2o()
void CKD_242_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.4.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 7909 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_242_self_h2o()
void CKD_242_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_4_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-30-10
Definition at line 7641 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_100_foreign_h2o()
void CKD_mt_100_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 8369 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FH2O_ckd_mt_100, FH2O_ckd_mt_100_dv, FH2O_ckd_mt_100_npt, FH2O_ckd_mt_100_v1, FH2O_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_100_self_h2o()
void CKD_mt_100_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 8133 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_100, SL260_ckd_mt_100_dv, SL260_ckd_mt_100_npt, SL260_ckd_mt_100_v1, SL260_ckd_mt_100_v2, SL296_ckd_mt_100, SL296_ckd_mt_100_dv, SL296_ckd_mt_100_npt, SL296_ckd_mt_100_v1, SL296_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_CIAfun_n2()
void CKD_mt_250_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity & verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (fundamental band)
Model reference: version_1 of the Nitrogen Collision Induced Fundamental Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann, Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling, Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann,
Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996)
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-27-06
Definition at line 10762 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), N2N2_N2F_ckd_mt_250, N2N2_N2F_ckd_mt_250_dv, N2N2_N2F_ckd_mt_250_npt, N2N2_N2F_ckd_mt_250_v1, N2N2_N2F_ckd_mt_250_v2, N2N2_N2Ft_ckd_mt_250, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
CKD_mt_250_CIArot_n2()
void CKD_mt_250_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity & verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (rotational band)
Model reference: Borysow, A, and L. Frommhold, "Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K", The Astrophysical Journal, 311, 1043-1057, 1986.
Updated 2014/06/26 based on:
Boissoles, J., C. Boulet, R.H. Tipping, A. Brown and Q. Ma, "Theoretical CAlculations of the Translation-Rotation Collision-Induced Absorption in N2-N2, O2-O2 and N2-O2 Pairs", J.Quant. Spec. Rad. Transfer, 82,505 (2003).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA rot. band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr1 N2 volume mixing ratio profile [1]
vmr2 O2 volume mixing ratio profile [1]
vmr3 H2O volume mixing ratio profile [1]
Remarks
Borysow, A, and L. Frommhold,
Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K,
The Astrophysical Journal, 311, 1043-1057, 1986.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-27-06
Definition at line 10525 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), N2N2_CT220_ckd_mt_100, N2N2_CT220_ckd_mt_100_dv, N2N2_CT220_ckd_mt_100_npt, N2N2_CT220_ckd_mt_100_v1, N2N2_CT220_ckd_mt_100_v2, N2N2_CT296_ckd_mt_100, N2N2_CT296_ckd_mt_100_dv, N2N2_CT296_ckd_mt_100_npt, N2N2_CT296_ckd_mt_100_v1, N2N2_CT296_ckd_mt_100_v2, N2N2_sf_220_ckd_mt_100, N2N2_sf_296_ckd_mt_100, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_co2()
void CKD_mt_250_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 2.50 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-26-06
Definition at line 9850 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FCO2_ckd_mt_250, FCO2_ckd_mt_250_dv, FCO2_ckd_mt_250_npt, FCO2_ckd_mt_250_v1, FCO2_ckd_mt_250_v2, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_foreign_h2o()
void CKD_mt_250_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 2.50 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-30-06
Definition at line 8817 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FH2O_ckd_mt_100, FH2O_ckd_mt_100_dv, FH2O_ckd_mt_100_npt, FH2O_ckd_mt_100_v1, FH2O_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_o2_vis()
void CKD_mt_250_o2_vis (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView DEBUG_ONLYvmr, const Verbosity & verbosity)
CKD version MT 2.50 O2.
Model reference: O2 continuum formulated by Greenblatt et al. over the spectral region 8797-29870 cm-1: "Absorption Coefficients of Oxygen Between 330 and 1140 nm, G.D. Green blatt, J.J. Orlando, J.B. Burkholder, and A.R. Ravishabkara, J. Geophys. Res., 95, 18577-18582, 1990.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v1<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Mayuri Tatiya
Date
2014-27-06
Definition at line 11555 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), O2_vis_ckd_mt_250, O2_vis_ckd_mt_250_dv, O2_vis_ckd_mt_250_npt, O2_vis_ckd_mt_250_v1, O2_vis_ckd_mt_250_v2, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_self_h2o()
void CKD_mt_250_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 2.50 H2O self continuum absorption model.
The following modifications to the water vapor continuum arise from new analyses of ARM measurements in the microwave and far-IR regions. Analyses of measurements in the microwave are based primarily on the two-channel MWR (23.8 and 31.4 GHz) at SGP, with supporting evidence from 150 GHz MWRHF measurements during the COPS campaign and from 170 GHz GVRP measurements at SGP (V. H. Payne, E. J. Mlawer and S. A. Clough). Measurements in the far-IR were from the AERI_ext at the NSA site, in the time surrounding and including the RHUBC-I campaign (J. Delamere and S. A. Clough).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-26-06
Definition at line 8553 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_100, SL260_ckd_mt_100_dv, SL260_ckd_mt_100_npt, SL260_ckd_mt_100_v1, SL260_ckd_mt_100_v2, SL296_ckd_mt_100, SL296_ckd_mt_100_dv, SL296_ckd_mt_100_npt, SL296_ckd_mt_100_v1, SL296_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_320_foreign_h2o()
void CKD_mt_320_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 3.20 H2O foreign continuum absorption model.
Changes from the release notes:
December 2016: The continuum has been updated to MT_CKD v3.0, which included modifications to the H2O foreign continuum from 0-600 cm-1 and the self continuum in the microwave that resulted from an analysis of measurements taken at the ARM RHUBC-II campaign and a re-analysis of RHUBC-I measurements. (E.J. Mlawer, D.D. Turner, S.N. Paine, V.H. Payne). Includes modifications to H2O foreign continuum coefficients in the far-infrared based on the analysis of REFIR-PAD (Bianchini and Palchetti, 2008) measurements taken at Cerro Toco, Chile, as part of the ARM RHUBC-II campaign and a re-analysis of the AERI-ER measurements from the ARM NSA site (first analyzed in Delamere et al., (2010)). The foreign continuum was also changed in the sub-millimeter and microwave regions as a result of the analysis of SAO FTS (Paine and Turner, 2013) measurements taken during the RHUBC-II campaign, which led to modification of the H2O self continuum in this region to maintain good agreement with the microwave measurements analyzed in Payne et al. (2008 and 2011).
July 2016: Foreign continuum coefficients from 1800-3000 cm-1 were modified to improve agreement with Baranov and Lafferty (2012); in the 1900-2150 cm-1 region, attention was also paid to IASI measurements (Alvarado et al., 2013). Foreign continuum coefficients at wavenumbers greater than 4000 cm-1 were modified based on Baranov and Lafferty (2012) and Mondelain et al. (2014) measurements (E.J. Mlawer and M.J. Alvarado).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 3.20 contnm.f90 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Emma Turner
Date
2018-29-10
Definition at line 9292 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FH2O_ckd_mt_320, FH2O_ckd_mt_320_dv, FH2O_ckd_mt_320_npt, FH2O_ckd_mt_320_v1, FH2O_ckd_mt_320_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_320_self_h2o()
void CKD_mt_320_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 3.20 H2O self continuum absorption model.
The following modifications to the self water vapor continuum arise from:
August 2017: New coefficients for self continuum in window regions for wavenumbers greater than 2000 cm-1 were added and self continuum temperature dependence from 1800-3500 cm-1 were updated (E.J. Mlawer, M.J. Alvarado, K.E. Cady-Pereira).
November 2016: SFAC re-adjusted based on RHUBC-II campaign. (Mlawer, E.J. et al. 2018 Analysis of water vapor absorption in the far-infrared and submillimeter regions using surface radiometric measurements fromextremely dry locations, submitted)
July 2016: Self continuum coefficients were modified from 1880-2390 cm-1 to fix issues in the CO fundamental region that were pointed out by Alvarado et al. (2013).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 3.20 contnm.f90 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Emma Turner
Date
2018-29-10
Definition at line 9019 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_320, SL260_ckd_mt_320_dv, SL260_ckd_mt_320_npt, SL260_ckd_mt_320_v1, SL260_ckd_mt_320_v2, SL296_ckd_mt_320, SL296_ckd_mt_320_dv, SL296_ckd_mt_320_npt, SL296_ckd_mt_320_v1, SL296_ckd_mt_320_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_n2()
void CKD_mt_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
Model reference: version_1 of the Nitrogen Collision Induced Fundamental Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann, Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling, Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann,
Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996)
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10332 of file legacy_continua.cc.
References a1, a2, ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), N2N2_N2F_ckd_mt_100, N2N2_N2F_ckd_mt_100_dv, N2N2_N2F_ckd_mt_100_npt, N2N2_N2F_ckd_mt_100_v1, N2N2_N2F_ckd_mt_100_v2, N2N2_N2Ft_ckd_mt_100, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_o2()
void CKD_mt_CIAfun_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
Model reference: F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet, "Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling", Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-O2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet,
Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996).
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10958 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), O2O2_O2F_ckd_mt_100_dv, O2O2_O2F_ckd_mt_100_npt, O2O2_O2F_ckd_mt_100_v1, O2O2_O2F_ckd_mt_100_v2, O2O2_O2Fo_ckd_mt_100, O2O2_O2Ft_ckd_mt_100, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_CIArot_n2()
void CKD_mt_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
Model reference: Borysow, A, and L. Frommhold, "Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K", The Astrophysical Journal, 311, 1043-1057, 1986.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA rot. band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Borysow, A, and L. Frommhold,
Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K,
The Astrophysical Journal, 311, 1043-1057, 1986.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10113 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), N2N2_CT220_ckd_mt_100, N2N2_CT220_ckd_mt_100_dv, N2N2_CT220_ckd_mt_100_npt, N2N2_CT220_ckd_mt_100_v1, N2N2_CT220_ckd_mt_100_v2, N2N2_CT296_ckd_mt_100, N2N2_CT296_ckd_mt_100_dv, N2N2_CT296_ckd_mt_100_npt, N2N2_CT296_ckd_mt_100_v1, N2N2_CT296_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_co2()
void CKD_mt_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 9678 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_v0v0_o2()
void CKD_mt_v0v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen collision induced fundamental model of O2 continuum formulated by Mate et al. over the spectral region 7550-8486 cm-1: B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty, "Absolute Intensities for the O2 1.27 micron continuum absorption", J. Geophys. Res., 104, 30,585-30,590, 1999.
The units of these continua coefficients are 1 / (amagat_O2*amagat_air)
Also, refer to the paper "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Mlawer, Clough, Brown, Stephen, Landry, Goldman, & Murcray, Journal of Geophysical Research (1997).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v0<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Remarks
B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty,
Absolute Intensities for the O2 1.27 micron continuum absorption,
J. Geophys. Res., 104, 30,585-30,590, 1999.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 11157 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_00_ckd_mt_100, O2_00_ckd_mt_100_dv, O2_00_ckd_mt_100_npt, O2_00_ckd_mt_100_v1, O2_00_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_v1v0_o2()
void CKD_mt_v1v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen v1<-v0 band model of Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray, "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Journal of Geophysical Research, vol 103, no. D4, pp. 3859-3863, 1998.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v1<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray,
Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands,
J. Geophys. Res., 103, D4, 3859-3863, 1998.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 11344 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), addF77fields, CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_10_ckd_mt_100_dv, O2_10_ckd_mt_100_v1, O2_10_ckd_mt_100_v2, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
clebsqr_()
double clebsqr_ (int * l, int * lambda, int * lp)
Definition at line 22442 of file legacy_continua.cc.
References clebsqr_0_().
clebsqr_0_()
double clebsqr_0_ (int n__, int * l, int * lambda, int * lp)
Definition at line 22373 of file legacy_continua.cc.
References fctl_().
Referenced by clebsqr_().
conti_n2__()
double conti_n2__ (double wn, double t, double * t0, double * w_n2__, double * rft, double * rhofac, double * xcn2)
Definition at line 24584 of file legacy_continua.cc.
References pow(), ARTS::Var::x(), and xlgr_().
Referenced by artsckd_().
CP98H2OAbsModel()
void CP98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CP98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to Cruz-Pol 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'CruzPol', 'CruzPolLines', 'CruzPolContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: S. L. Cruz-Pol et al., Radio Science, 33(5), 1319, 1998.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6610 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
ELL07WaterDropletAbs()
void ELL07WaterDropletAbs (MatrixView pxsec, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
ELL07WaterDropletAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to ELL07 [1/m]
model allows choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Allowed models: 'ELL07'. See the user guide for detailed explanations.
Remarks
Reference: W. J. Ellison,
Permittivity of Pure Water, at Standard Atmospheric Pressure, over the Frequency Range 0-25 THz and Temperature Range 0-100C,
J. Phys. Chem. Ref. Data, Vol. 36, No. 1, 2007
Author
Stuart Fox
Date
2015-06-03
Definition at line 15608 of file legacy_continua.cc.
References a1, a2, ARTS::Var::abs_p(), ARTS::Var::abs_t(), b1, b2, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, and pow().
Referenced by xsec_continuum_tag().
fctl_()
double fctl_ (int * n)
Definition at line 22446 of file legacy_continua.cc.
References pow().
Referenced by clebsqr_0_().
fwv24_()
double fwv24_ (double wn, double * w_wv__, double * rft, double * xn, double * xn_wv__, double * xn0, double * xfrg)
Definition at line 24349 of file legacy_continua.cc.
Referenced by fwv_().
fwv_()
double fwv_ (int ivc, double wn, double * w_wv__, double * rft, double * xn, double * xn_wv__, double * xn0, double * xfrg)
Definition at line 24287 of file legacy_continua.cc.
References fwv24_(), and fwv_mpmf87s93__().
Referenced by artsckd_().
fwv_mpmf87s93__()
double fwv_mpmf87s93__ (double wn, double * w_wv__, double * rft, double * xn, double * xn_wv__, double * xn0, double * xfrg)
Definition at line 24319 of file legacy_continua.cc.
References fh2oa_1, fh2ob_1, ARTS::Var::x(), and xlgr_().
Referenced by fwv_().
Ho66_CO2_foreign_continuum()
void Ho66_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity & verbosity)
Ho66_CO2_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-CO2-continuum according to Ho et al 1966 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_n2 N2 volume mixing ratio profile [1]
vmr CO2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Ho66' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Ho, Kaufman and Thaddeus, "Laboratory measurements of microwave absorption in models of the atmosphere of Venus", JGR, 1966.
Author
Patrick Eriksson (mainly by copying Thomas PWR function)
Date
2013-10-15
Definition at line 15354 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Ho66_CO2_self_continuum()
void Ho66_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Ho66_CO2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-CO2-continuum according to Ho et al 1966 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Ho66' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Ho, Kaufman and Thaddeus, "Laboratory measurements of microwave absorption in models of the atmosphere of Venus", JGR, 1966.
Author
Patrick Eriksson (mainly by copying Thomas PWR function)
Date
2013-10-15
Definition at line 15261 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
initi_()
int initi_ (double p, double t, double * radct, double * t0, double * p0, double * w_wv__, double * w_o2__, double * w_n2__, double * w_other__, double * xn0, double * xn, double * xn_wv__, double * rhofac)
Definition at line 24700 of file legacy_continua.cc.
References consts_1.
Referenced by artsckd_().
ixpolat_()
int ixpolat_ (int * l, int * m, int * k, double * eps, double * x, double * y, double * t, double * ss, double * si, int * nr, double * s2)
Definition at line 22891 of file legacy_continua.cc.
Referenced by specfct_().
MaTipping_H2O_foreign_continuum()
void MaTipping_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MaTipping_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'MaTipping', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Q. Ma and R. H. Tipping, J. Chem. Phys., 117(23), 10581, 2002.
Author
Thomas Kuhn
Date
2002-12-04
Definition at line 6950 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
MPM02H2OAbsModel()
void MPM02H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM02H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM93 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Attention
Corrected version of MPM93 by TKS, iup, 2002 The H2O lines at 547.676440 GHz and 552.020960 GHz are isotopologue lines:
547 GHz is from the isotopologue 1-8-1 (HITRAN code 181, JPL code 20003) with an isotopologue ratio of 0.00199983 and
552 GHz is from the isotopologue 1-7-1 (HITRAN code 171, JPL code 19003) with an isotopologue ratio of 0.00037200.
The original source code of MPM93 has these isotopologue ratios not included in the line strength parameter b1, which is an error.
In the arts implementation the line strength parameter b1 of these two lines is multiplied with the appropriate isotopologue ratio.
Author
Thomas Kuhn
Date
2002-05-06
Definition at line 5845 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and pow().
MPM85O2AbsModel()
void MPM85O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM85O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM85', 'MPM85Lines', 'MPM85Continuum', 'MPM85NoCoupling', 'MPM85NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
An updated model for millimeter wave propagation in moist air,,
Radio Science, vol. 20, pp. 1069-1089, 1985
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12160 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM87H2OAbsModel()
void MPM87H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM87H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM87 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the H2O-line strengths [1]
CWin scaling factor for the H2O-line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
H. J. Liebe,
A contribution to modeling atmospheric millimeter-wave properties,
Frequenz, 41, 1987, 31-36
and
H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modeling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences,
325 Broadway, Boulder, CO 80303-3328, report 87224.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 5482 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and pow().
Referenced by xsec_continuum_tag().
MPM87O2AbsModel()
void MPM87O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM87O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', 'MPM87NoCoupling', 'MPM87NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modelling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences, rep. 87-224,
325 Broadway, Boulder, CO 80303-3328
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12430 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM89H2OAbsModel()
void MPM89H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM89H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM89 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe, Int. J. Infrared and Millimeter Waves, 10(6), 1989, 631.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 5654 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and pow().
Referenced by xsec_continuum_tag().
MPM89O2AbsModel()
void MPM89O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM89O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', 'MPM89NoCoupling', 'MPM89NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
MPM - an atmospheric millimeter-wave propagation model,
Int. J. Infrared and Mill. Waves, Vol 10, pp. 631-650, 1989.
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12693 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM92O2AbsModel()
void MPM92O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM92O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM93 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM92', 'MPM92Lines', 'MPM92Continuum', 'MPM92NoCoupling', 'MPM92NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe, P. W. Rosenkranz and G. A. Hufford,
Atmospheric 60-GHz Oxygen Spectrum: New Laboratory Measurements and Line Parameters,
JQSRT, Vol 48, pp. 629-643, 1992
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 12950 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93_H2O_continuum()
void MPM93_H2O_continuum (MatrixView pxsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 H2O pseudo continuum line parameters:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O according to MPM87 [1/m]
fcenter continuum pseudo-line center frequency [Hz]
b1 continuum pseudo-line line strength [Hz/Pa]
b2 continuum pseudo-line line strength temperature exponent [1]
b3 continuum pseudo-line line broadening parameter [Hz/Pa]
b4 continuum pseudo-line line broadening parameter [1]
b5 continuum pseudo-line line broadening parameter [1]
b6 continuum pseudo-line line broadening parameter [1]
model allows user defined input parameter set (fcenter and b1 to b6)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters fcenter and b1 to b6 are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 12033 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), b1, b2, CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93_N2_continuum()
void MPM93_N2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 N2 continuum.
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to MPM93 [1/m]
Cin continuum strength [ppm/GHz]
Gin width parameter [Hz/Pa]
xTin continuum strength temperature exponent [1]
xfin continuum frequency exponent [1]
model allows user defined input parameter set (Cin, Gin, xTin, and xfin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr N2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin, Gin, xTin, and xfin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14640 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), fac(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
MPM93_O2_continuum()
void MPM93_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 O2 continuum:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to MPM93 [1/m]
S0in O2-continuum strength [1/Pa]
G0in O2-continuum width [Hz/Pa]
XS0in O2-continuum strength temperature exponent [1]
XG0in O2-continuum width temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, xS0in, and xG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, xS0in, and xG0in are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14098 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, pow(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93H2OAbsModel()
void MPM93H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM93 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Attention
The H2O lines at 547.676440 GHz and 552.020960 GHz are isotopologue lines:
547 GHz is from the isotopologue 1-8-1 (HITRAN code 181, JPL code 20003) with an isotopologue ratio of 0.00199983 and
552 GHz is from the isotopologue 1-7-1 (HITRAN code 171, JPL code 19003) with an isotopologue ratio of 0.00037200.
The original source code of MPM93 has these isotopologue ratios not included in the line strength parameter b1, which is an error.
In the arts implementation the line strength parameter b1 of these two lines is multiplied with the appropriate isotopologue ratio.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6095 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and pow().
Referenced by xsec_continuum_tag().
MPM93IceCrystalAbs()
void MPM93IceCrystalAbs (MatrixView pxsec, const Numeric CCin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93IceCrystalAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of ice clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the permittivity function a (see page 3-6 in the reference) [1]
CBin scaling parameter of the permittivity function b (see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Except for model 'user' the input parameters CCin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15832 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93O2AbsModel()
void MPM93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM93 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', 'MPM93NoCoupling', 'MPM93NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 13479 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93RainExt()
void MPM93RainExt (MatrixView pxsec, const Numeric CEin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93RainExt.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CEin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the factor a_rain [1]
CBin scaling parameter of the exponent b_rain [1]
model allows user defined input parameter (CEin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr rain rate vector (i.e. vertical profile) kg/m2/s
Note
Except for model 'user' the input parameters CEin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: R. L. Olsen and D.V. Rogers and D. B. Hodge,
The aR^b relation in the calculation of rain attenuation,
IEEE Trans. Antennas Propagat., vol. AP-26, pp. 318-329, 1978.
Author
Christian Melsheimer
Date
2003-22-05
Definition at line 15977 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), dB_km_to_1_m, DENSITY_OF_WATER, ARTS::Var::f_grid(), Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93WaterDropletAbs()
void MPM93WaterDropletAbs (MatrixView pxsec, const Numeric CCin, const Numeric CGin, const Numeric CEin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93WaterDropletAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CGin scaling parameter of the first relaxation frequency (gamma_1, see page 3-6 in the reference) [1]
CEin scaling parameter of the first permittivity component (epsilon_0, see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CGin, CEin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Except for model 'user' the input parameters CCin, CGin, and CEin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15455 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPMLineShapeFunction()
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Return values
MPMLineShapeFunction H2O-line shape function value [1/Hz]
Parameters
gamma H2O-line width [Hz]
fl H2O-line central frequency [Hz]
f frequency position of calculation [Hz]
Note
This function calculates the line shape function of Van Vleck and Weisskopf with the factor (f/fl)ą. for the MPM pseudo continuum line.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 16206 of file legacy_continua.cc.
Referenced by CP98H2OAbsModel(), MPM02H2OAbsModel(), MPM87H2OAbsModel(), MPM89H2OAbsModel(), MPM93_H2O_continuum(), and MPM93H2OAbsModel().
MPMLineShapeO2Function()
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
Return values
MPMLineShapeO2Function O2-line shape function value [1]
Parameters
gamma O2-line width [Hz]
fl H2O-line central frequency of the [Hz]
f frequency position of calculation [Hz]
delta O2-line mixing parameter [1]
Note
This function calculates the line shape function of Van Vleck and Weisskopf for O2 with line mixing.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 16262 of file legacy_continua.cc.
Referenced by MPM85O2AbsModel(), MPM87O2AbsModel(), MPM92O2AbsModel(), MPM93O2AbsModel(), and TRE05O2AbsModel().
n2n2tks_()
Numeric n2n2tks_ (double t, double f)
Definition at line 20967 of file legacy_continua.cc.
Referenced by BF86_CIA_N2().
Pardo_ATM_H2O_ForeignContinuum()
void Pardo_ATM_H2O_ForeignContinuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Pardo_ATM_H2O_ForeignContinuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 11922 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Pardo_ATM_N2_dry_continuum()
void Pardo_ATM_N2_dry_continuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView h2ovmr, const Verbosity & verbosity)
Pardo_ATM_N2_dry_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio [1]
h2ovmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 14766 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
partsum_()
int partsum_ (double * temp)
Definition at line 21718 of file legacy_continua.cc.
References b0, d0, jrange1, q, temp, and wn2.
phys_consts__()
int phys_consts__ (void)
Definition at line 24741 of file legacy_continua.cc.
profile_()
int profile_ (double * x, double * y)
Definition at line 21761 of file legacy_continua.cc.
References dx, ns, nsri, nsriup, rsi, slit, wnrmax3, ARTS::Var::x(), x0, and ARTS::Var::y().
PWR93O2AbsModel()
void PWR93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, const String & version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmrh2o, ConstVectorView vmr, const Verbosity & verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
REFERENCES FOR EQUATIONS AND COEFFICIENTS: P.W. Rosenkranz, CHAP. 2 and appendix, in ATMOSPHERIC REMOTE SENSING BY MICROWAVE RADIOMETRY (M.A. Janssen, ed., 1993). H.J. Liebe et al, JQSRT V.48, PP.629-643 (1992). M.J. Schwartz, Ph.D. thesis, M.I.T. (1997). SUBMILLIMETER LINE INTENSITIES FROM HITRAN96. This version differs from Liebe's MPM92 in two significant respects:
It uses the modification of the 1- line width temperature dependence recommended by Schwartz: (1/T).
It uses the same temperature dependence (X) for submillimeter line widths as in the 60 GHz band: (1/T)**0.8
history: 05-01-95 P. Rosenkranz 11-05-97 P. Rosenkranz - 1- line modification. 12-16-98 pwr - updated submm freq's and intensities from HITRAN96
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to the P. W. Rosenkranz, 1993 [1/m]
CCin O2-continuum scale factor [1]
CLin O2 line strength scale factor [1]
CWin O2 line broadening scale factor [1]
COin O2 line coupling scale factor [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
version determines model version: 1988, 1993, 1998
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmrh2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models:
'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', 'RosenkranzNoCoupling', and 'user'.
For the parameter version the following three string values are allowed: 'PWR88', 'PWR93', 'PWR98'.
See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 13762 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, PI, pow(), and VMRCalcLimit.
Referenced by test_mpm20(), and xsec_continuum_tag().
PWR98H2OAbsModel()
void PWR98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
PWR98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to P. W. Rosenkranz, 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6329 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and pow().
Referenced by xsec_continuum_tag().
RADFN_FUN()
Numeric RADFN_FUN (const Numeric VI, const Numeric XKT)
Definition at line 7105 of file legacy_continua.cc.
Rosenkranz_CO2_foreign_continuum()
void Rosenkranz_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_n2 N2 volume mixing ratio profile [1]
vmr CO2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15168 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Rosenkranz_CO2_self_continuum()
void Rosenkranz_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-CO2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15073 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Rosenkranz_N2_self_continuum()
void Rosenkranz_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_N2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin temperature exponent of N2-continuum [1]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14865 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Rosenkranz_O2_continuum()
void Rosenkranz_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
3) O2-air
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993. Also stated in Liebe et al. JQSRT, Vol 48, Nr 5/6, pp. 629-643, 1992. Default continuum parameters are C=1.6E-17*10E-9, x=0.8
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to Rosenkranz 1993 [1/m]
S0in line strength [K˛/(Hz*Pa*m)]
G0in line width [Hz/Pa]
XS0in line strength temperature exponent [1]
XG0in line widths temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, XS0in, and XG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, XS0in, and XG0in are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14242 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
specfct_()
double specfct_ (double * freq, double * omega, double * phi, double * phi2, int * n, double * rtemp)
Definition at line 21859 of file legacy_continua.cc.
References abs, and ixpolat_().
spline_()
int spline_ (int * l, int * m, int * k, double * eps, double * x, double * y, double * t, double * ss, double * si, int * nr, double * s2)
Definition at line 22877 of file legacy_continua.cc.
spline_0_()
int spline_0_ (int n__, int * l, int * m, int * k, double * eps, double * x, double * y, double * t, double * ss, double * si, int * nr, double * s2)
Definition at line 22620 of file legacy_continua.cc.
Standard_H2O_foreign_continuum()
void Standard_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_t predefined temperature grid [K]
abs_p predefined pressure [Pa]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-08-03
Definition at line 6839 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Standard_H2O_self_continuum()
void Standard_H2O_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-H2O continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent of (300/T) [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6730 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and ARTS::Var::x().
Referenced by xsec_continuum_tag().
Standard_N2_self_continuum()
void Standard_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
4) N2-N2
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xfin continuum frequency exponent [1]
xtin continuum strength temperature exponent [1]
xpin continuum strength pressure exponent [1]
model allows user defined input parameter set (Cin, xfin, xtin, and xpin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin, xfin, xtin, and xpin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14964 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Standard_O2_continuum()
void Standard_O2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric G0in, const Numeric G0Ain, const Numeric G0Bin, const Numeric XG0din, const Numeric XG0win, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
Standard_O2_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to Rosenkranz 1993 [1/m]
Cin O2-continuum coefficient [1/(Hz*Pa*m)]
G0in line width [Hz/Pa]
G0Ain dry air broadening parameter [1]
G0Bin water vapor broadening parameter [1]
XG0din line strength temperature exponent [1]
XG0win line widths temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, XS0in, and XG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, XS0in, and XG0in are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14363 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, ARTS::Var::f_grid(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), PI, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
swv24_()
double swv24_ (double wn, double t, double * t0, double * w_wv__, double * rft, double * , double * xn_wv__, double * xn0, double * xslf)
Definition at line 24470 of file legacy_continua.cc.
Referenced by swv_().
swv_()
double swv_ (int ivc, double wn, double t, double * t0, double * w_wv__, double * rft, double * xn, double * xn_wv__, double * xn0, double * xslf)
Definition at line 24420 of file legacy_continua.cc.
References swv24_(), and swv_mpmf87s93__().
Referenced by artsckd_().
swv_mpmf87s93__()
double swv_mpmf87s93__ (double wn, double t, double * t0, double * w_wv__, double * rft, double * , double * xn_wv__, double * xn0, double * xslf)
Definition at line 24541 of file legacy_continua.cc.
References pow(), s260a_1, sh2oa_1, sh2ob_1, ARTS::Var::x(), and xlgr_().
Referenced by swv_().
TRE05O2AbsModel()
void TRE05O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
TRE05O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to TRE05 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'TRE05', 'TRE05Lines', 'TRE05Continuum', 'TRE05NoCoupling', 'TRE05NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
References: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
M.Yu. Tretyakov, M.A. Koshelev, V.V. Dorovskikh, D.S. Makarov, P.W. Rosenkranz; 60-GHz oxygen band: precise broadening and central frequencies of fine-structure lines, absolute absorption profile at atmospheric pressure, and revision of mixing coefficients doi:10.1016/j.jms.2004.11.011
Remarks
This is a copy of MPM93O2AbsModel with an exception of having new values from the Tretyakov etal. 2005 paper.
Author
Richard Larsson
Date
2013-09-20
Definition at line 13217 of file legacy_continua.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_t(), CREATE_OUT3, dB_km_to_1_m, ARTS::Var::f_grid(), Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
XINT_FUN() [1/2]
Numeric XINT_FUN (const Numeric V1A, const Numeric, const Numeric DVA, const Numeric A[], const Index nA, const Numeric VI)
Definition at line 7062 of file legacy_continua.cc.
XINT_FUN() [2/2]
Numeric XINT_FUN (const Numeric V1A, const Numeric, const Numeric DVA, ConstVectorView A, const Numeric VI)
Definition at line 7022 of file legacy_continua.cc.
References ConstVectorView::nelem().
xlgr_()
double xlgr_ (double * xf, double * x)
Definition at line 24676 of file legacy_continua.cc.
References ARTS::Var::x().
Referenced by conti_n2__(), fwv_mpmf87s93__(), and swv_mpmf87s93__().
xsec_continuum_tag()
void xsec_continuum_tag (MatrixView xsec, const String & name, ConstVectorView parameters, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView abs_o2, ConstVectorView vmr, const Verbosity & verbosity)
Calculates model absorption for one continuum or full model tag.
Note, that only one tag can be taken at a time.
Calculated is the true absorption cross section, that means you have to multiply this with n*VMR in order to get the absorption coefficient in units of 1/m.
This is the type of xsec that is used all over ARTS, but not what is used by the internal continuum functions! (We have to divide the output of the internal continuum functions by the number density n.)
Return values
xsec Cross section of one continuum tag,
xsec = alpha / (n*VMR) [m^2]. This is both input and output! (The function adds the continuum absorption cross section to the previous content of xsec.)
Parameters
name The name of the model to calculate (derived from the tag name)
parameters model parameters, as defined in method abs_cont_parameters.
model model, related to model parameters
f_grid Frequency grid [Hz]
abs_p Pressure grid [Pa]
abs_t Temperatures associated with the pressure grid, abs_p [K]
abs_n2 Total volume mixing ratio profile of molecular nitrogen.
This will be needed only for the CO2 foreign continuum [1]
however one is forced to give this input [1]
abs_h2o Total volume mixing ratio profile of water vapor.
This will be needed only for the oxygen continuum
however one is forced to give this input [1]
vmr Volume mixing ratio profile of the actual species [1]
Author
Stefan Buehler, Thomas Kuhn
Date
2001-11-05
Definition at line 16340 of file legacy_continua.cc.
References abs, ARTS::Var::abs_p(), ARTS::Var::abs_t(), BF86_CIA_N2(), BOLTZMAN_CONST, CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), CP98H2OAbsModel(), CREATE_OUT3, ELL07WaterDropletAbs(), ARTS::Var::f_grid(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), joker, LIQUID_AND_ICE_TREAT_AS_ZERO, MaTipping_H2O_foreign_continuum(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), parameters, Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), ConstVectorView::sum(), TRE05O2AbsModel(), and ARTS::Var::verbosity().
Referenced by abs_xsec_per_speciesAddConts().
Variable Documentation
addF77fields
const int addF77fields = 1
Definition at line 461 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), and CKD_mt_v1v0_o2().
app3a_
struct s_app3a_ app3a_
app3b_
struct s_app3b_ app3b_
bba_
union u_bba_ bba_
bbb_
struct s_bbb_ bbb_
bbbb_
union u_bbbb_ bbbb_
bbc_
struct s_bbc_ bbc_
bf_
struct s_bf_ bf_
bl3_
union u_bl3_ bl3_
blockin_
struct s_blockin_ blockin_
bou43_
struct s_bou43_ bou43_
consts_
struct s_consts_ consts_
Initial value:
= {{3.1415927410125732,
              6.62606876e-27,
              1.3806503e-16,
              29979245800.,
              6.02214199e23,
              2.6867775e19,
              83144720.,
              1.191042722e-12,
              1.4387752}}
dB_km_to_1_m
const Numeric dB_km_to_1_m = (1.00000e-3 / (10.0 * LOG10_EULER_NUMBER))
Definition at line 450 of file legacy_continua.cc.
Referenced by ELL07WaterDropletAbs(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), and TRE05O2AbsModel().
DENSITY_OF_WATER
const Numeric DENSITY_OF_WATER extern
Referenced by MPM93RainExt().
dimer_
struct s_dimer_ dimer_
energ_
struct s_energe_ energ_
EULER_NUMBER
const Numeric EULER_NUMBER extern
FCO2_ckd_mt_100
const double FCO2_ckd_mt_100[FCO2_ckd_mt_100_npt+addF77fields]
Definition at line 3946 of file legacy_continua.cc.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_dv
const Numeric FCO2_ckd_mt_100_dv = 10.0
Definition at line 3944 of file legacy_continua.cc.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_npt
const int FCO2_ckd_mt_100_npt = 1003
Definition at line 3945 of file legacy_continua.cc.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_v1
const Numeric FCO2_ckd_mt_100_v1 = -20.0
Definition at line 3942 of file legacy_continua.cc.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_v2
const Numeric FCO2_ckd_mt_100_v2 = 10000.0
Definition at line 3943 of file legacy_continua.cc.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_250
const double FCO2_ckd_mt_250[FCO2_ckd_mt_250_npt+addF77fields]
Definition at line 4157 of file legacy_continua.cc.
Referenced by CKD_mt_250_co2().
FCO2_ckd_mt_250_dv
const Numeric FCO2_ckd_mt_250_dv = 2.0
Definition at line 4155 of file legacy_continua.cc.
Referenced by CKD_mt_250_co2().
FCO2_ckd_mt_250_npt
const int FCO2_ckd_mt_250_npt = 5003
Definition at line 4156 of file legacy_continua.cc.
Referenced by CKD_mt_250_co2().
FCO2_ckd_mt_250_v1
const Numeric FCO2_ckd_mt_250_v1 = -4.0
Definition at line 4153 of file legacy_continua.cc.
Referenced by CKD_mt_250_co2().
FCO2_ckd_mt_250_v2
const Numeric FCO2_ckd_mt_250_v2 = 10000.0
Definition at line 4154 of file legacy_continua.cc.
Referenced by CKD_mt_250_co2().
FH2O_ckd_0
const double FH2O_ckd_0[FH2O_ckd_0_npt+addF77fields]
Definition at line 903 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_dv
const Numeric FH2O_ckd_0_dv = 10.0
Definition at line 901 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_npt
const int FH2O_ckd_0_npt = 2003
Definition at line 902 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_v1
const Numeric FH2O_ckd_0_v1 = -20.0
Definition at line 899 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_v2
const Numeric FH2O_ckd_0_v2 = 20000.0
Definition at line 900 of file legacy_continua.cc.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_mt_100
const double FH2O_ckd_mt_100[FH2O_ckd_mt_100_npt+addF77fields]
Definition at line 2346 of file legacy_continua.cc.
Referenced by CKD_mt_100_foreign_h2o(), and CKD_mt_250_foreign_h2o().
FH2O_ckd_mt_100_dv
const Numeric FH2O_ckd_mt_100_dv = 10.0
Definition at line 2344 of file legacy_continua.cc.
Referenced by CKD_mt_100_foreign_h2o(), and CKD_mt_250_foreign_h2o().
FH2O_ckd_mt_100_npt
const int FH2O_ckd_mt_100_npt = 2003
Definition at line 2345 of file legacy_continua.cc.
Referenced by CKD_mt_100_foreign_h2o(), and CKD_mt_250_foreign_h2o().
FH2O_ckd_mt_100_v1
const Numeric FH2O_ckd_mt_100_v1 = -20.0
Definition at line 2342 of file legacy_continua.cc.
Referenced by CKD_mt_100_foreign_h2o(), and CKD_mt_250_foreign_h2o().
FH2O_ckd_mt_100_v2
const Numeric FH2O_ckd_mt_100_v2 = 20000.0
Definition at line 2343 of file legacy_continua.cc.
Referenced by CKD_mt_100_foreign_h2o(), and CKD_mt_250_foreign_h2o().
FH2O_ckd_mt_320
const double FH2O_ckd_mt_320[FH2O_ckd_mt_320_npt+addF77fields]
Definition at line 3534 of file legacy_continua.cc.
Referenced by CKD_mt_320_foreign_h2o().
FH2O_ckd_mt_320_dv
const Numeric FH2O_ckd_mt_320_dv = 10.0
Definition at line 3531 of file legacy_continua.cc.
Referenced by CKD_mt_320_foreign_h2o().
FH2O_ckd_mt_320_npt
const int FH2O_ckd_mt_320_npt = 2003
Definition at line 3532 of file legacy_continua.cc.
Referenced by CKD_mt_320_foreign_h2o().
FH2O_ckd_mt_320_v1
const Numeric FH2O_ckd_mt_320_v1 = -20.0
Definition at line 3529 of file legacy_continua.cc.
Referenced by CKD_mt_320_foreign_h2o().
FH2O_ckd_mt_320_v2
const Numeric FH2O_ckd_mt_320_v2 = 20000.0
Definition at line 3530 of file legacy_continua.cc.
Referenced by CKD_mt_320_foreign_h2o().
fh2oa_
struct s_fh2oa_ fh2oa_
fh2ob_
struct s_fh2ob_ fh2ob_ = {{-20., 2e4, 10.}, 2003}
Hz_to_GHz
const Numeric Hz_to_GHz = 1.000000e-9
Definition at line 429 of file legacy_continua.cc.
Referenced by CP98H2OAbsModel(), ELL07WaterDropletAbs(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), PWR93O2AbsModel(), PWR98H2OAbsModel(), and TRE05O2AbsModel().
k1k0_
struct s_k1k0_ k1k0_
like_
struct s_like_ like_ = {{0}, "N2N2"}
LIQUID_AND_ICE_TREAT_AS_ZERO
const Numeric LIQUID_AND_ICE_TREAT_AS_ZERO = 1e-10
Definition at line 418 of file legacy_continua.cc.
Referenced by ELL07WaterDropletAbs(), MPM93IceCrystalAbs(), MPM93WaterDropletAbs(), and xsec_continuum_tag().
LOG10_EULER_NUMBER
const Numeric LOG10_EULER_NUMBER extern
N2N2_CT220_ckd_mt_100
const double N2N2_CT220_ckd_mt_100[N2N2_CT220_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.0000e0,   0.4946E-06, 0.5756E-06, 0.5964E-06, 0.5756E-06, 0.4946E-06,
    0.4145E-06, 0.3641E-06, 0.3482E-06, 0.3340E-06, 0.3252E-06, 0.3299E-06,
    0.3206E-06, 0.3184E-06, 0.3167E-06, 0.2994E-06, 0.2943E-06, 0.2794E-06,
    0.2582E-06, 0.2468E-06, 0.2237E-06, 0.2038E-06, 0.1873E-06, 0.1641E-06,
    0.1474E-06, 0.1297E-06, 0.1114E-06, 0.9813E-07, 0.8309E-07, 0.7059E-07,
    0.6068E-07, 0.5008E-07, 0.4221E-07, 0.3537E-07, 0.2885E-07, 0.2407E-07,
    0.1977E-07, 0.1605E-07, 0.1313E-07, 0.1057E-07, 0.8482E-08, 0.6844E-08,
    0.5595E-08, 0.4616E-08, 0.3854E-08, 0.3257E-08, 0.2757E-08, 0.2372E-08,
    0.2039E-08, 0.1767E-08, 0.1548E-08, 0.1346E-08, 0.1181E-08, 0.1043E-08,
    0.9110E-09, 0.8103E-09, 0.7189E-09, 0.6314E-09, 0.5635E-09, 0.4976E-09,
    0.4401E-09, 0.3926E-09, 0.3477E-09, 0.3085E-09, 0.2745E-09, 0.2416E-09,
    0.2155E-09, 0.1895E-09, 0.1678E-09, 0.1493E-09, 0.1310E-09, 0.1154E-09,
    0.1019E-09, 0.8855E-10}
Definition at line 4922 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_dv
const Numeric N2N2_CT220_ckd_mt_100_dv = 5.0
Definition at line 4920 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_npt
const int N2N2_CT220_ckd_mt_100_npt = 73
Definition at line 4921 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_v1
const Numeric N2N2_CT220_ckd_mt_100_v1 = -10.0
Definition at line 4918 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_v2
const Numeric N2N2_CT220_ckd_mt_100_v2 = 350.0
Definition at line 4919 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100
const double N2N2_CT296_ckd_mt_100[N2N2_CT296_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.0000e0,   0.4303E-06, 0.4850E-06, 0.4979E-06, 0.4850E-06, 0.4303E-06,
    0.3715E-06, 0.3292E-06, 0.3086E-06, 0.2920E-06, 0.2813E-06, 0.2804E-06,
    0.2738E-06, 0.2726E-06, 0.2724E-06, 0.2635E-06, 0.2621E-06, 0.2547E-06,
    0.2428E-06, 0.2371E-06, 0.2228E-06, 0.2100E-06, 0.1991E-06, 0.1822E-06,
    0.1697E-06, 0.1555E-06, 0.1398E-06, 0.1281E-06, 0.1138E-06, 0.1012E-06,
    0.9078E-07, 0.7879E-07, 0.6944E-07, 0.6084E-07, 0.5207E-07, 0.4540E-07,
    0.3897E-07, 0.3313E-07, 0.2852E-07, 0.2413E-07, 0.2045E-07, 0.1737E-07,
    0.1458E-07, 0.1231E-07, 0.1031E-07, 0.8586E-08, 0.7162E-08, 0.5963E-08,
    0.4999E-08, 0.4226E-08, 0.3607E-08, 0.3090E-08, 0.2669E-08, 0.2325E-08,
    0.2024E-08, 0.1783E-08, 0.1574E-08, 0.1387E-08, 0.1236E-08, 0.1098E-08,
    0.9777E-09, 0.8765E-09, 0.7833E-09, 0.7022E-09, 0.6317E-09, 0.5650E-09,
    0.5100E-09, 0.4572E-09, 0.4115E-09, 0.3721E-09, 0.3339E-09, 0.3005E-09,
    0.2715E-09, 0.2428E-09}
Definition at line 4885 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_dv
const Numeric N2N2_CT296_ckd_mt_100_dv = 5.0
Definition at line 4883 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_npt
const int N2N2_CT296_ckd_mt_100_npt = 73
Definition at line 4884 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_v1
const Numeric N2N2_CT296_ckd_mt_100_v1 = -10.0
Definition at line 4881 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_v2
const Numeric N2N2_CT296_ckd_mt_100_v2 = 350.0
Definition at line 4882 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2(), and CKD_mt_CIArot_n2().
N2N2_N2F_ckd_mt_100
const double N2N2_N2F_ckd_mt_100[N2N2_N2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.000E+00, 0.000E+00, 2.000E-10, 5.200E-09, 1.020E-08, 1.520E-08,
    2.020E-08, 2.520E-08, 3.020E-08, 4.450E-08, 5.220E-08, 6.460E-08,
    7.750E-08, 9.030E-08, 1.060E-07, 1.210E-07, 1.370E-07, 1.570E-07,
    1.750E-07, 2.010E-07, 2.300E-07, 2.590E-07, 2.950E-07, 3.260E-07,
    3.660E-07, 4.050E-07, 4.470E-07, 4.920E-07, 5.340E-07, 5.840E-07,
    6.240E-07, 6.670E-07, 7.140E-07, 7.260E-07, 7.540E-07, 7.840E-07,
    8.090E-07, 8.420E-07, 8.620E-07, 8.870E-07, 9.110E-07, 9.360E-07,
    9.760E-07, 1.030E-06, 1.110E-06, 1.230E-06, 1.390E-06, 1.610E-06,
    1.760E-06, 1.940E-06, 1.970E-06, 1.870E-06, 1.750E-06, 1.560E-06,
    1.420E-06, 1.350E-06, 1.320E-06, 1.290E-06, 1.290E-06, 1.290E-06,
    1.300E-06, 1.320E-06, 1.330E-06, 1.340E-06, 1.350E-06, 1.330E-06,
    1.310E-06, 1.290E-06, 1.240E-06, 1.200E-06, 1.160E-06, 1.100E-06,
    1.040E-06, 9.960E-07, 9.380E-07, 8.630E-07, 7.980E-07, 7.260E-07,
    6.550E-07, 5.940E-07, 5.350E-07, 4.740E-07, 4.240E-07, 3.770E-07,
    3.330E-07, 2.960E-07, 2.630E-07, 2.340E-07, 2.080E-07, 1.850E-07,
    1.670E-07, 1.470E-07, 1.320E-07, 1.200E-07, 1.090E-07, 9.850E-08,
    9.080E-08, 8.180E-08, 7.560E-08, 6.850E-08, 6.140E-08, 5.830E-08,
    5.770E-08, 5.000E-08, 4.320E-08, 3.140E-08, 2.890E-08, 2.640E-08,
    2.390E-08, 2.140E-08, 1.890E-08, 1.640E-08, 1.390E-08, 1.140E-08,
    8.900E-09, 6.400E-09, 3.900E-09, 1.400E-09, 0.000E+00}
Definition at line 4957 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_dv
const Numeric N2N2_N2F_ckd_mt_100_dv = 5.000
Definition at line 4955 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_npt
const int N2N2_N2F_ckd_mt_100_npt = 118
Definition at line 4956 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_v1
const Numeric N2N2_N2F_ckd_mt_100_v1 = 2085.000
Definition at line 4953 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_v2
const Numeric N2N2_N2F_ckd_mt_100_v2 = 2670.000
Definition at line 4954 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_250
const double N2N2_N2F_ckd_mt_250[N2N2_N2F_ckd_mt_250_npt+addF77fields]
Initial value:
= {
    0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00,
    0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00,
    9.280E-11, 3.660E-10, 8.130E-10, 1.430E-09, 2.230E-09, 3.210E-09, 4.370E-09,
    5.750E-09, 7.340E-09, 9.190E-09, 1.130E-08, 1.370E-08, 1.650E-08, 1.960E-08,
    2.310E-08, 2.710E-08, 3.160E-08, 3.660E-08, 4.230E-08, 4.860E-08, 5.570E-08,
    6.350E-08, 7.230E-08, 8.200E-08, 9.270E-08, 1.050E-07, 1.180E-07, 1.320E-07,
    1.480E-07, 1.650E-07, 1.840E-07, 2.040E-07, 2.270E-07, 2.510E-07, 2.770E-07,
    3.060E-07, 3.360E-07, 3.670E-07, 4.010E-07, 4.330E-07, 4.710E-07, 5.050E-07,
    5.450E-07, 5.790E-07, 6.200E-07, 6.540E-07, 6.940E-07, 7.240E-07, 7.610E-07,
    7.880E-07, 8.220E-07, 8.440E-07, 8.720E-07, 8.930E-07, 9.190E-07, 9.370E-07,
    9.620E-07, 9.870E-07, 1.020E-06, 1.060E-06, 1.110E-06, 1.180E-06, 1.280E-06,
    1.400E-06, 1.570E-06, 1.750E-06, 1.880E-06, 2.020E-06, 2.080E-06, 2.060E-06,
    1.960E-06, 1.860E-06, 1.710E-06, 1.570E-06, 1.490E-06, 1.440E-06, 1.410E-06,
    1.390E-06, 1.380E-06, 1.380E-06, 1.390E-06, 1.390E-06, 1.410E-06, 1.420E-06,
    1.430E-06, 1.420E-06, 1.430E-06, 1.410E-06, 1.400E-06, 1.370E-06, 1.350E-06,
    1.310E-06, 1.270E-06, 1.220E-06, 1.170E-06, 1.120E-06, 1.060E-06, 1.010E-06,
    9.470E-07, 8.910E-07, 8.290E-07, 7.740E-07, 7.160E-07, 6.620E-07, 6.090E-07,
    5.600E-07, 5.130E-07, 4.680E-07, 4.290E-07, 3.900E-07, 3.560E-07, 3.240E-07,
    2.950E-07, 2.680E-07, 2.440E-07, 2.230E-07, 2.030E-07, 1.850E-07, 1.690E-07,
    1.540E-07, 1.410E-07, 1.290E-07, 1.180E-07, 1.080E-07, 9.950E-08, 9.100E-08,
    8.380E-08, 7.700E-08, 7.100E-08, 6.510E-08, 6.010E-08, 5.550E-08, 5.110E-08,
    4.710E-08, 4.340E-08, 3.980E-08, 3.660E-08, 3.380E-08, 3.110E-08, 2.840E-08,
    2.610E-08, 2.390E-08, 2.210E-08, 2.010E-08, 1.830E-08, 1.710E-08, 1.550E-08,
    1.450E-08, 1.320E-08, 1.250E-08, 1.140E-08, 1.070E-08, 1.000E-08, 8.100E-09,
    6.400E-09, 4.900E-09, 3.600E-09, 2.500E-09, 1.600E-09, 9.000E-10, 4.000E-10,
    1.000E-10, 0.000E+00, 0.000E+00, 0.000E+00}
Definition at line 5011 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_N2F_ckd_mt_250_dv
const Numeric N2N2_N2F_ckd_mt_250_dv = 3.981461525
Definition at line 5009 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_N2F_ckd_mt_250_npt
const int N2N2_N2F_ckd_mt_250_npt = 179
Definition at line 5010 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_N2F_ckd_mt_250_v1
const Numeric N2N2_N2F_ckd_mt_250_v1 = 2001.766357
Definition at line 5007 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_N2F_ckd_mt_250_v2
const Numeric N2N2_N2F_ckd_mt_250_v2 = 2710.45
Definition at line 5008 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_N2Ft_ckd_mt_100
const double N2N2_N2Ft_ckd_mt_100[N2N2_N2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.000E+00,  1.040E+03,  1.010E+03,  9.800E+02,  9.500E+02,  9.200E+02,
    8.900E+02,  8.600E+02,  8.300E+02,  8.020E+02,  7.610E+02,  7.220E+02,
    6.790E+02,  6.460E+02,  6.090E+02,  5.620E+02,  5.110E+02,  4.720E+02,
    4.360E+02,  4.060E+02,  3.770E+02,  3.550E+02,  3.380E+02,  3.190E+02,
    2.990E+02,  2.780E+02,  2.550E+02,  2.330E+02,  2.080E+02,  1.840E+02,
    1.490E+02,  1.070E+02,  6.600E+01,  2.500E+01,  -1.300E+01, -4.900E+01,
    -8.200E+01, -1.040E+02, -1.190E+02, -1.300E+02, -1.390E+02, -1.440E+02,
    -1.460E+02, -1.460E+02, -1.470E+02, -1.480E+02, -1.500E+02, -1.530E+02,
    -1.600E+02, -1.690E+02, -1.810E+02, -1.890E+02, -1.950E+02, -2.000E+02,
    -2.050E+02, -2.090E+02, -2.110E+02, -2.100E+02, -2.100E+02, -2.090E+02,
    -2.050E+02, -1.990E+02, -1.900E+02, -1.800E+02, -1.680E+02, -1.570E+02,
    -1.430E+02, -1.260E+02, -1.080E+02, -8.900E+01, -6.300E+01, -3.200E+01,
    1.000E+00,  3.500E+01,  6.500E+01,  9.500E+01,  1.210E+02,  1.410E+02,
    1.520E+02,  1.610E+02,  1.640E+02,  1.640E+02,  1.610E+02,  1.550E+02,
    1.480E+02,  1.430E+02,  1.370E+02,  1.330E+02,  1.310E+02,  1.330E+02,
    1.390E+02,  1.500E+02,  1.650E+02,  1.870E+02,  2.130E+02,  2.480E+02,
    2.840E+02,  3.210E+02,  3.720E+02,  4.490E+02,  5.140E+02,  5.690E+02,
    6.090E+02,  6.420E+02,  6.730E+02,  7.000E+02,  7.300E+02,  7.600E+02,
    7.900E+02,  8.200E+02,  8.500E+02,  8.800E+02,  9.100E+02,  9.400E+02,
    9.700E+02,  1.000E+03,  1.030E+03,  1.060E+03,  1.090E+03}
Definition at line 4980 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2Ft_ckd_mt_250
const double N2N2_N2Ft_ckd_mt_250[N2N2_N2F_ckd_mt_250_npt+addF77fields]
Initial value:
= {
    0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00,
    0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00,
    1.880E-10, 7.160E-10, 1.530E-09, 2.580E-09, 3.840E-09, 5.270E-09, 6.850E-09,
    8.550E-09, 1.040E-08, 1.230E-08, 1.440E-08, 1.650E-08, 1.880E-08, 2.130E-08,
    2.400E-08, 2.690E-08, 3.010E-08, 3.360E-08, 3.750E-08, 4.180E-08, 4.670E-08,
    5.210E-08, 5.830E-08, 6.520E-08, 7.290E-08, 8.170E-08, 9.150E-08, 1.030E-07,
    1.150E-07, 1.290E-07, 1.440E-07, 1.610E-07, 1.800E-07, 2.020E-07, 2.250E-07,
    2.510E-07, 2.790E-07, 3.090E-07, 3.430E-07, 3.770E-07, 4.160E-07, 4.540E-07,
    4.990E-07, 5.370E-07, 5.850E-07, 6.250E-07, 6.750E-07, 7.130E-07, 7.610E-07,
    7.970E-07, 8.410E-07, 8.720E-07, 9.100E-07, 9.380E-07, 9.720E-07, 9.940E-07,
    1.020E-06, 1.050E-06, 1.080E-06, 1.120E-06, 1.170E-06, 1.240E-06, 1.340E-06,
    1.470E-06, 1.660E-06, 1.870E-06, 2.040E-06, 2.220E-06, 2.300E-06, 2.290E-06,
    2.160E-06, 2.050E-06, 1.870E-06, 1.710E-06, 1.620E-06, 1.580E-06, 1.550E-06,
    1.540E-06, 1.540E-06, 1.550E-06, 1.560E-06, 1.570E-06, 1.590E-06, 1.590E-06,
    1.600E-06, 1.580E-06, 1.570E-06, 1.540E-06, 1.510E-06, 1.470E-06, 1.430E-06,
    1.370E-06, 1.310E-06, 1.250E-06, 1.180E-06, 1.110E-06, 1.040E-06, 9.740E-07,
    9.020E-07, 8.360E-07, 7.650E-07, 7.050E-07, 6.430E-07, 5.860E-07, 5.320E-07,
    4.820E-07, 4.370E-07, 3.950E-07, 3.570E-07, 3.220E-07, 2.910E-07, 2.630E-07,
    2.390E-07, 2.160E-07, 1.960E-07, 1.780E-07, 1.620E-07, 1.480E-07, 1.330E-07,
    1.220E-07, 1.120E-07, 1.020E-07, 9.280E-08, 8.420E-08, 7.700E-08, 6.990E-08,
    6.390E-08, 5.880E-08, 5.380E-08, 4.840E-08, 4.380E-08, 4.020E-08, 3.690E-08,
    3.290E-08, 3.050E-08, 2.720E-08, 2.490E-08, 2.260E-08, 2.020E-08, 1.810E-08,
    1.620E-08, 1.500E-08, 1.310E-08, 1.100E-08, 1.020E-08, 8.730E-09, 8.190E-09,
    6.630E-09, 5.960E-09, 5.110E-09, 4.500E-09, 3.810E-09, 2.680E-09, 3.050E-09,
    2.480E-09, 1.370E-09, 1.550E-09, 4.690E-10, 5.120E-10, 0.000E+00, 0.000E+00,
    0.000E+00, 0.000E+00, 0.000E+00, 0.000E+00}
Definition at line 5040 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2().
N2N2_sf_220_ckd_mt_100
const double N2N2_sf_220_ckd_mt_100[N2N2_CT220_ckd_mt_100_npt+addF77fields]
Initial value:
=
    {0.0e0,  1.3536, 1.3515, 1.3502, 1.3515, 1.3536, 1.3565, 1.3592, 1.3612,
     1.3623, 1.3626, 1.3623, 1.3616, 1.3609, 1.3600, 1.3591, 1.3583, 1.3576,
     1.3571, 1.3571, 1.3572, 1.3574, 1.3578, 1.3585, 1.3597, 1.3616, 1.3640,
     1.3666, 1.3698, 1.3734, 1.3776, 1.3828, 1.3894, 1.3969, 1.4049, 1.4127,
     1.4204, 1.4302, 1.4427, 1.4562, 1.4687, 1.4798, 1.4894, 1.5000, 1.5142,
     1.5299, 1.5441, 1.5555, 1.5615, 1.5645, 1.5730, 1.5880, 1.6028, 1.6121,
     1.6133, 1.6094, 1.6117, 1.6244, 1.6389, 1.6485, 1.6513, 1.6468, 1.6438,
     1.6523, 1.6523, 1.6523, 1.6523, 1.6523, 1.6523, 1.6523, 1.6523, 1.6523,
     1.6523, 1.6523}
Definition at line 4937 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2().
N2N2_sf_296_ckd_mt_100
const double N2N2_sf_296_ckd_mt_100[N2N2_CT296_ckd_mt_100_npt+addF77fields]
Initial value:
=
    {0.0e0,  1.3534, 1.3517, 1.3508, 1.3517, 1.3534, 1.3558, 1.3584, 1.3607,
     1.3623, 1.3632, 1.3634, 1.3632, 1.3627, 1.3620, 1.3612, 1.3605, 1.3597,
     1.3590, 1.3585, 1.3582, 1.3579, 1.3577, 1.3577, 1.3580, 1.3586, 1.3594,
     1.3604, 1.3617, 1.3633, 1.3653, 1.3677, 1.3706, 1.3742, 1.3780, 1.3822,
     1.3868, 1.3923, 1.3989, 1.4062, 1.4138, 1.4216, 1.4298, 1.4388, 1.4491,
     1.4604, 1.4718, 1.4829, 1.4930, 1.5028, 1.5138, 1.5265, 1.5392, 1.5499,
     1.5577, 1.5639, 1.5714, 1.5816, 1.5920, 1.6003, 1.6051, 1.6072, 1.6097,
     1.6157, 1.6157, 1.6157, 1.6157, 1.6157, 1.6157, 1.6157, 1.6157, 1.6157,
     1.6157, 1.6157}
Definition at line 4900 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIArot_n2().
n2part_
struct s_n2part_ n2part_ = {{0}, {2., 1., 1.98957, 5.8e-6}, {0}}
NAT_LOG_TEN
const Numeric NAT_LOG_TEN extern
O2_00_ckd_mt_100
const double O2_00_ckd_mt_100[O2_00_ckd_mt_100_npt+addF77fields]
Definition at line 5134 of file legacy_continua.cc.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_dv
const Numeric O2_00_ckd_mt_100_dv = 2.000e0
Definition at line 5132 of file legacy_continua.cc.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_npt
const int O2_00_ckd_mt_100_npt = 483
Definition at line 5133 of file legacy_continua.cc.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_v1
const Numeric O2_00_ckd_mt_100_v1 = 7536.000e0
Definition at line 5130 of file legacy_continua.cc.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_v2
const Numeric O2_00_ckd_mt_100_v2 = 8500.000e0
Definition at line 5131 of file legacy_continua.cc.
Referenced by CKD_mt_v0v0_o2().
O2_10_ckd_mt_100_dv
const Numeric O2_10_ckd_mt_100_dv = 2.000e0
Definition at line 5223 of file legacy_continua.cc.
Referenced by CKD_mt_v1v0_o2().
O2_10_ckd_mt_100_v1
const Numeric O2_10_ckd_mt_100_v1 = 9100.000e0
Definition at line 5221 of file legacy_continua.cc.
Referenced by CKD_mt_v1v0_o2().
O2_10_ckd_mt_100_v2
const Numeric O2_10_ckd_mt_100_v2 = 11000.000e0
Definition at line 5222 of file legacy_continua.cc.
Referenced by CKD_mt_v1v0_o2().
O2_vis_ckd_mt_250
const double O2_vis_ckd_mt_250[O2_vis_ckd_mt_250_npt+addF77fields]
Definition at line 5229 of file legacy_continua.cc.
Referenced by CKD_mt_250_o2_vis().
O2_vis_ckd_mt_250_dv
const Numeric O2_vis_ckd_mt_250_dv = 10.000e0
Definition at line 5227 of file legacy_continua.cc.
Referenced by CKD_mt_250_o2_vis().
O2_vis_ckd_mt_250_npt
const int O2_vis_ckd_mt_250_npt = 1488
Definition at line 5228 of file legacy_continua.cc.
Referenced by CKD_mt_250_o2_vis().
O2_vis_ckd_mt_250_v1
const Numeric O2_vis_ckd_mt_250_v1 = 15000.000e0
Definition at line 5225 of file legacy_continua.cc.
Referenced by CKD_mt_250_o2_vis().
O2_vis_ckd_mt_250_v2
const Numeric O2_vis_ckd_mt_250_v2 = 29870.000e0
Definition at line 5226 of file legacy_continua.cc.
Referenced by CKD_mt_250_o2_vis().
O2O2_O2F_ckd_mt_100_dv
const Numeric O2O2_O2F_ckd_mt_100_dv = 5.000
Definition at line 5076 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_npt
const int O2O2_O2F_ckd_mt_100_npt = 103
Definition at line 5077 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_v1
const Numeric O2O2_O2F_ckd_mt_100_v1 = 1340.000
Definition at line 5074 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_v2
const Numeric O2O2_O2F_ckd_mt_100_v2 = 1850.000
Definition at line 5075 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2Fo_ckd_mt_100
const double O2O2_O2Fo_ckd_mt_100[O2O2_O2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.000E+00, 0.000E+00, 9.744E-09, 2.256E-08, 3.538E-08, 4.820E-08, 6.100E-08,
    7.400E-08, 8.400E-08, 9.600E-08, 1.200E-07, 1.620E-07, 2.080E-07, 2.460E-07,
    2.850E-07, 3.140E-07, 3.800E-07, 4.440E-07, 5.000E-07, 5.710E-07, 6.730E-07,
    7.680E-07, 8.530E-07, 9.660E-07, 1.100E-06, 1.210E-06, 1.330E-06, 1.470E-06,
    1.590E-06, 1.690E-06, 1.800E-06, 1.920E-06, 2.040E-06, 2.150E-06, 2.260E-06,
    2.370E-06, 2.510E-06, 2.670E-06, 2.850E-06, 3.070E-06, 3.420E-06, 3.830E-06,
    4.200E-06, 4.450E-06, 4.600E-06, 4.530E-06, 4.280E-06, 3.960E-06, 3.680E-06,
    3.480E-06, 3.350E-06, 3.290E-06, 3.250E-06, 3.230E-06, 3.230E-06, 3.210E-06,
    3.190E-06, 3.110E-06, 3.030E-06, 2.910E-06, 2.800E-06, 2.650E-06, 2.510E-06,
    2.320E-06, 2.130E-06, 1.930E-06, 1.760E-06, 1.590E-06, 1.420E-06, 1.250E-06,
    1.110E-06, 9.900E-07, 8.880E-07, 7.910E-07, 6.780E-07, 5.870E-07, 5.240E-07,
    4.640E-07, 4.030E-07, 3.570E-07, 3.200E-07, 2.900E-07, 2.670E-07, 2.420E-07,
    2.150E-07, 1.820E-07, 1.600E-07, 1.460E-07, 1.280E-07, 1.030E-07, 8.700E-08,
    8.100E-08, 7.100E-08, 6.400E-08, 5.807E-08, 5.139E-08, 4.496E-08, 3.854E-08,
    3.212E-08, 2.569E-08, 1.927E-08, 1.285E-08, 6.423E-09, 0.000E+00}
Definition at line 5078 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2Ft_ckd_mt_100
const double O2O2_O2Ft_ckd_mt_100[O2O2_O2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
    0.000E+00,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,
    4.670E+02,  4.000E+02,  3.150E+02,  3.790E+02,  3.680E+02,  4.750E+02,
    5.210E+02,  5.310E+02,  5.120E+02,  4.420E+02,  4.440E+02,  4.300E+02,
    3.810E+02,  3.350E+02,  3.240E+02,  2.960E+02,  2.480E+02,  2.150E+02,
    1.930E+02,  1.580E+02,  1.270E+02,  1.010E+02,  7.100E+01,  3.100E+01,
    -6.000E+00, -2.600E+01, -4.700E+01, -6.300E+01, -7.900E+01, -8.800E+01,
    -8.800E+01, -8.700E+01, -9.000E+01, -9.800E+01, -9.900E+01, -1.090E+02,
    -1.340E+02, -1.600E+02, -1.670E+02, -1.640E+02, -1.580E+02, -1.530E+02,
    -1.510E+02, -1.560E+02, -1.660E+02, -1.680E+02, -1.730E+02, -1.700E+02,
    -1.610E+02, -1.450E+02, -1.260E+02, -1.080E+02, -8.400E+01, -5.900E+01,
    -2.900E+01, 4.000E+00,  4.100E+01,  7.300E+01,  9.700E+01,  1.230E+02,
    1.590E+02,  1.980E+02,  2.200E+02,  2.420E+02,  2.560E+02,  2.810E+02,
    3.110E+02,  3.340E+02,  3.190E+02,  3.130E+02,  3.210E+02,  3.230E+02,
    3.100E+02,  3.150E+02,  3.200E+02,  3.350E+02,  3.610E+02,  3.780E+02,
    3.730E+02,  3.380E+02,  3.190E+02,  3.460E+02,  3.220E+02,  2.910E+02,
    2.900E+02,  3.500E+02,  3.710E+02,  5.040E+02,  4.000E+02,  4.000E+02,
    4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,
    4.000E+02,  4.000E+02}
Definition at line 5095 of file legacy_continua.cc.
Referenced by CKD_mt_CIAfun_o2().
Pa_to_hPa
const Numeric Pa_to_hPa = 1.000000e-2
Definition at line 437 of file legacy_continua.cc.
Referenced by CP98H2OAbsModel(), MPM02H2OAbsModel(), MPM92O2AbsModel(), MPM93H2OAbsModel(), MPM93O2AbsModel(), PWR93O2AbsModel(), PWR98H2OAbsModel(), and TRE05O2AbsModel().
Pa_to_kPa
const Numeric Pa_to_kPa = 1.000000e-3
Definition at line 433 of file legacy_continua.cc.
Referenced by MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), and MPM89O2AbsModel().
PI
const Numeric PI extern
Referenced by ELL07WaterDropletAbs(), MPM93_N2_continuum(), MPM93_O2_continuum(), PWR93O2AbsModel(), and Standard_O2_continuum().
rsilo_
struct s_rsilo_ rsilo_
s260a_
struct s_s260a_ s260a_
s260b_
struct s_s260b_ s260b_ = {{-20., 2e4, 10.}, 2003}
sh2oa_
struct s_sh2oa_ sh2oa_
sh2ob_
struct s_sh2ob_ sh2ob_ = {{-20., 2e4, 10.}, 2003}
SL260_ckd_0
const double SL260_ckd_0[SL260_ckd_0_npt+addF77fields]
Definition at line 1314 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_dv
const Numeric SL260_ckd_0_dv = 10.0
Definition at line 1312 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_npt
const int SL260_ckd_0_npt = 2003
Definition at line 1313 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_v1
const Numeric SL260_ckd_0_v1 = -20.0
Definition at line 1310 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_v2
const Numeric SL260_ckd_0_v2 = 20000.0
Definition at line 1311 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_mt_100
const double SL260_ckd_mt_100[SL260_ckd_mt_100_npt+addF77fields]
Definition at line 2050 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL260_ckd_mt_100_dv
const Numeric SL260_ckd_mt_100_dv = 10.0
Definition at line 2048 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL260_ckd_mt_100_npt
const int SL260_ckd_mt_100_npt = 2003
Definition at line 2049 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL260_ckd_mt_100_v1
const Numeric SL260_ckd_mt_100_v1 = -20.0
Definition at line 2046 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL260_ckd_mt_100_v2
const Numeric SL260_ckd_mt_100_v2 = 20000.0
Definition at line 2047 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL260_ckd_mt_320
const double SL260_ckd_mt_320[SL260_ckd_mt_320_npt+addF77fields]
Definition at line 3020 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL260_ckd_mt_320_dv
const Numeric SL260_ckd_mt_320_dv = 10.0
Definition at line 3017 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL260_ckd_mt_320_npt
const int SL260_ckd_mt_320_npt = 2003
Definition at line 3018 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL260_ckd_mt_320_v1
const Numeric SL260_ckd_mt_320_v1 = -20.0
Definition at line 3015 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL260_ckd_mt_320_v2
const Numeric SL260_ckd_mt_320_v2 = 20000.0
Definition at line 3016 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL296_ckd_0
const double SL296_ckd_0[SL296_ckd_0_npt+addF77fields]
Definition at line 492 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_dv
const Numeric SL296_ckd_0_dv = 10.0
Definition at line 490 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_npt
const int SL296_ckd_0_npt = 2003
Definition at line 491 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_v1
const Numeric SL296_ckd_0_v1 = -20.0
Definition at line 488 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_v2
const Numeric SL296_ckd_0_v2 = 20000.0
Definition at line 489 of file legacy_continua.cc.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_mt_100
const double SL296_ckd_mt_100[SL296_ckd_mt_100_npt+addF77fields]
Definition at line 1754 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL296_ckd_mt_100_dv
const Numeric SL296_ckd_mt_100_dv = 10.0
Definition at line 1752 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL296_ckd_mt_100_npt
const int SL296_ckd_mt_100_npt = 2003
Definition at line 1753 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL296_ckd_mt_100_v1
const Numeric SL296_ckd_mt_100_v1 = -20.0
Definition at line 1750 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL296_ckd_mt_100_v2
const Numeric SL296_ckd_mt_100_v2 = 20000.0
Definition at line 1751 of file legacy_continua.cc.
Referenced by CKD_mt_100_self_h2o(), and CKD_mt_250_self_h2o().
SL296_ckd_mt_320
const double SL296_ckd_mt_320[SL296_ckd_mt_320_npt+addF77fields]
Definition at line 2675 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL296_ckd_mt_320_dv
const Numeric SL296_ckd_mt_320_dv = 10.0
Definition at line 2673 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL296_ckd_mt_320_npt
const int SL296_ckd_mt_320_npt = 2003
Definition at line 2674 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL296_ckd_mt_320_v1
const Numeric SL296_ckd_mt_320_v1 = -20.0
Definition at line 2671 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SL296_ckd_mt_320_v2
const Numeric SL296_ckd_mt_320_v2 = 20000.0
Definition at line 2672 of file legacy_continua.cc.
Referenced by CKD_mt_320_self_h2o().
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), MPM93_N2_continuum(), MPM93_O2_continuum(), and Standard_O2_continuum().
VMRCalcLimit
const Numeric VMRCalcLimit = 1.000e-25
Definition at line 454 of file legacy_continua.cc.
Referenced by CKD_mt_250_CIAfun_n2(), CKD_mt_CIAfun_n2(), CP98H2OAbsModel(), MPM85O2AbsModel(), MPM87O2AbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_O2_continuum(), MPM93O2AbsModel(), Pardo_ATM_N2_dry_continuum(), PWR93O2AbsModel(), and TRE05O2AbsModel().