ARTS: legacy_continua.h File Reference
legacy_continua.h File Reference
#include "matpackI.h"
#include "messages.h"
#include "mystring.h"
Functions
void xsec_continuum_tag (MatrixView xsec, const String &name, ConstVectorView parameters, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView abs_o2, ConstVectorView vmr, const Verbosity &verbosity)
Calculates model absorption for one continuum or full model tag.
void check_continuum_model (const String &name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
void MPM87H2OAbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM87H2OAbsModel.
void MPM89H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM89H2OAbsModel.
void MPM93H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93H2OAbsModel.
void PWR98H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
PWR98H2OAbsModel.
void CP98H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CP98H2OAbsModel.
void Pardo_ATM_H2O_ForeignContinuum (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Pardo_ATM_H2O_ForeignContinuum.
void Standard_H2O_self_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_self_continuum.
void Standard_H2O_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_foreign_continuum.
void MaTipping_H2O_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MaTipping_H2O_foreign_continuum.
void MPM93_H2O_continuum (MatrixView xsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 H2O pseudo continuum line parameters:
void CKD_222_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
void CKD_222_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
void CKD_242_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
void CKD24_H20 (MatrixView xsec, int isf, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.4 H2O continuum absorption model.
void CKD_242_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
void CKD_mt_100_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
void CKD_mt_100_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
void CKD_mt_250_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 2.50 H2O self continuum absorption model.
void CKD_mt_250_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 2.50 H2O foreign continuum absorption model.
void CKD_mt_320_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 3.20 H2O self continuum absorption model.
void CKD_mt_320_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 3.20 H2O foreign continuum absorption model.
void MPM85O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM85O2AbsModel.
void MPM87O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM87O2AbsModel.
void MPM89O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM89O2AbsModel.
void MPM92O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr)
void MPM93O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93O2AbsModel.
void TRE05O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
TRE05O2AbsModel.
void PWR93O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, const String &version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
void MPM93_O2_continuum (MatrixView xsec, const Numeric S0in, const Numeric G0in, const Numeric XSOin, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 O2 continuum:
void Rosenkranz_O2_continuum (MatrixView xsec, const Numeric S0in, const Numeric G0in, const Numeric XSOin, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
3) O2-air
void CKD_mt_CIAfun_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
void CKD_mt_v0v0_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
void CKD_mt_v1v0_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
void CKD_mt_250_o2_vis (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
void CKD_mt_CIArot_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
void CKD_mt_CIAfun_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
void CKD_mt_250_CIArot_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity &verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (rotational band)
void CKD_mt_250_CIAfun_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity &verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (fundamental band)
void BF86_CIA_N2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
void MPM93_N2_continuum (MatrixView xsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 N2 continuum.
void Rosenkranz_N2_self_continuum (MatrixView xsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_N2_self_continuum.
void Standard_N2_self_continuum (MatrixView xsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
4) N2-N2
void Pardo_ATM_N2_dry_continuum (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, const Verbosity &verbosity)
Pardo_ATM_N2_dry_continuum.
void CKD_241_co2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
void CKD_mt_co2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
void CKD_250_mt_co2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
void Rosenkranz_CO2_self_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_self_continuum.
void Rosenkranz_CO2_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_foreign_continuum.
void MPM93WaterDropletAbs (MatrixView xsec, const Numeric CC, const Numeric CG, const Numeric CE, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93WaterDropletAbs.
void MPM93IceCrystalAbs (MatrixView xsec, const Numeric CC, const Numeric CA, const Numeric CB, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93IceCrystalAbs.
void MPM93RainExt (MatrixView xsec, const Numeric CE, const Numeric CA, const Numeric CB, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93RainExt.
void ELL07WaterDropletAbs (MatrixView xsec, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
ELL07WaterDropletAbs.
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
Function Documentation
BF86_CIA_N2()
void BF86_CIA_N2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
see publication A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see http://adsabs.harvard.edu/article_service.html for a scanned version of the paper
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-CIA according to BF-86 model [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Note
this "crude" version of the N2-N2 model is a f2c conversion of the N2-N2 F77 code of Prof. A. Borysow. The original code can be downloaded at F77 code.
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-05
Definition at line 14522 of file legacy_continua.cc.
References CREATE_OUT3, n2n2tks_(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
check_continuum_model()
void check_continuum_model (const String & name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
This is just in order to verify that this really represents a valid continuum model.
The given name should be something like 'H2O-ContStandardSelf'. The function simply checks if there is a species H2O with an isotopologue ContStandardSelf.
For user-friendliness, the function also compiles a list of allowed continuum models and gives this as an error message if the model is not found.
The function has no return value, since, if the name does not match a valid model an error is thrown anyway.
Parameters
name The name of the continuum model to check.
Exceptions
runtime_error The model does not exist.
Author
Stefan Buehler
Date
2001-03-12
Definition at line 20406 of file legacy_continua.cc.
References Zeeman::end(), Isotopologue, and global_data::species_data.
Referenced by abs_cont_descriptionAppend().
CKD24_H20()
void CKD24_H20 (MatrixView pxsec, int isf, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.4 H2O continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O continuum according to CKD2.4 [1/m]
isf =0 self continuum, =1 foreign continuum
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
this "crude" version of the CKD2.4 model is a f2c conversion of the F77 code taken out of MonoRTM RT-model written by
S. BOUKABARA, S.A. CLOUGH, and R. HOFFMAN
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421
USA
E-mail: sbouk.nosp@m.aba@.nosp@m.aer.c.nosp@m.om, cloug.nosp@m.h@ae.nosp@m.r.com
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-06
Definition at line 11744 of file legacy_continua.cc.
References artsckd_(), CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
CKD_222_foreign_h2o()
void CKD_222_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.2.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 7437 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_222_self_h2o()
void CKD_222_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_2_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-31-10
Definition at line 7181 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_241_co2()
void CKD_241_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.1 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 9506 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_242_foreign_h2o()
void CKD_242_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.4.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 7909 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_242_self_h2o()
void CKD_242_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_4_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-30-10
Definition at line 7641 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_250_mt_co2()
void CKD_250_mt_co2 (MatrixView xsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD_mt_100_foreign_h2o()
void CKD_mt_100_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 8369 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_mt_100, FH2O_ckd_mt_100_dv, FH2O_ckd_mt_100_npt, FH2O_ckd_mt_100_v1, FH2O_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_100_self_h2o()
void CKD_mt_100_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 8133 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_100, SL260_ckd_mt_100_dv, SL260_ckd_mt_100_npt, SL260_ckd_mt_100_v1, SL260_ckd_mt_100_v2, SL296_ckd_mt_100, SL296_ckd_mt_100_dv, SL296_ckd_mt_100_npt, SL296_ckd_mt_100_v1, SL296_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_CIAfun_n2()
void CKD_mt_250_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity & verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (fundamental band)
Model reference: version_1 of the Nitrogen Collision Induced Fundamental Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann, Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling, Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann,
Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996)
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-27-06
Definition at line 10762 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, N2N2_N2F_ckd_mt_250, N2N2_N2F_ckd_mt_250_dv, N2N2_N2F_ckd_mt_250_npt, N2N2_N2F_ckd_mt_250_v1, N2N2_N2F_ckd_mt_250_v2, N2N2_N2Ft_ckd_mt_250, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
CKD_mt_250_CIArot_n2()
void CKD_mt_250_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, ConstVectorView abs_o2, const Verbosity & verbosity)
CKD version MT 2.50 N2-N2 collision induced absorption (rotational band)
Model reference: Borysow, A, and L. Frommhold, "Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K", The Astrophysical Journal, 311, 1043-1057, 1986.
Updated 2014/06/26 based on:
Boissoles, J., C. Boulet, R.H. Tipping, A. Brown and Q. Ma, "Theoretical CAlculations of the Translation-Rotation Collision-Induced Absorption in N2-N2, O2-O2 and N2-O2 Pairs", J.Quant. Spec. Rad. Transfer, 82,505 (2003).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA rot. band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr1 N2 volume mixing ratio profile [1]
vmr2 O2 volume mixing ratio profile [1]
vmr3 H2O volume mixing ratio profile [1]
Remarks
Borysow, A, and L. Frommhold,
Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K,
The Astrophysical Journal, 311, 1043-1057, 1986.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-27-06
Definition at line 10525 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, N2N2_CT220_ckd_mt_100, N2N2_CT220_ckd_mt_100_dv, N2N2_CT220_ckd_mt_100_npt, N2N2_CT220_ckd_mt_100_v1, N2N2_CT220_ckd_mt_100_v2, N2N2_CT296_ckd_mt_100, N2N2_CT296_ckd_mt_100_dv, N2N2_CT296_ckd_mt_100_npt, N2N2_CT296_ckd_mt_100_v1, N2N2_CT296_ckd_mt_100_v2, N2N2_sf_220_ckd_mt_100, N2N2_sf_296_ckd_mt_100, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_foreign_h2o()
void CKD_mt_250_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 2.50 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-30-06
Definition at line 8817 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_mt_100, FH2O_ckd_mt_100_dv, FH2O_ckd_mt_100_npt, FH2O_ckd_mt_100_v1, FH2O_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_250_o2_vis()
void CKD_mt_250_o2_vis (MatrixView xsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD_mt_250_self_h2o()
void CKD_mt_250_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 2.50 H2O self continuum absorption model.
The following modifications to the water vapor continuum arise from new analyses of ARM measurements in the microwave and far-IR regions. Analyses of measurements in the microwave are based primarily on the two-channel MWR (23.8 and 31.4 GHz) at SGP, with supporting evidence from 150 GHz MWRHF measurements during the COPS campaign and from 170 GHz GVRP measurements at SGP (V. H. Payne, E. J. Mlawer and S. A. Clough). Measurements in the far-IR were from the AERI_ext at the NSA site, in the time surrounding and including the RHUBC-I campaign (J. Delamere and S. A. Clough).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 2.50 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Mayuri Tatiya
Date
2014-26-06
Definition at line 8553 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_100, SL260_ckd_mt_100_dv, SL260_ckd_mt_100_npt, SL260_ckd_mt_100_v1, SL260_ckd_mt_100_v2, SL296_ckd_mt_100, SL296_ckd_mt_100_dv, SL296_ckd_mt_100_npt, SL296_ckd_mt_100_v1, SL296_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_320_foreign_h2o()
void CKD_mt_320_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 3.20 H2O foreign continuum absorption model.
Changes from the release notes:
December 2016: The continuum has been updated to MT_CKD v3.0, which included modifications to the H2O foreign continuum from 0-600 cm-1 and the self continuum in the microwave that resulted from an analysis of measurements taken at the ARM RHUBC-II campaign and a re-analysis of RHUBC-I measurements. (E.J. Mlawer, D.D. Turner, S.N. Paine, V.H. Payne). Includes modifications to H2O foreign continuum coefficients in the far-infrared based on the analysis of REFIR-PAD (Bianchini and Palchetti, 2008) measurements taken at Cerro Toco, Chile, as part of the ARM RHUBC-II campaign and a re-analysis of the AERI-ER measurements from the ARM NSA site (first analyzed in Delamere et al., (2010)). The foreign continuum was also changed in the sub-millimeter and microwave regions as a result of the analysis of SAO FTS (Paine and Turner, 2013) measurements taken during the RHUBC-II campaign, which led to modification of the H2O self continuum in this region to maintain good agreement with the microwave measurements analyzed in Payne et al. (2008 and 2011).
July 2016: Foreign continuum coefficients from 1800-3000 cm-1 were modified to improve agreement with Baranov and Lafferty (2012); in the 1900-2150 cm-1 region, attention was also paid to IASI measurements (Alvarado et al., 2013). Foreign continuum coefficients at wavenumbers greater than 4000 cm-1 were modified based on Baranov and Lafferty (2012) and Mondelain et al. (2014) measurements (E.J. Mlawer and M.J. Alvarado).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 3.20 contnm.f90 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Emma Turner
Date
2018-29-10
Definition at line 9292 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_mt_320, FH2O_ckd_mt_320_dv, FH2O_ckd_mt_320_npt, FH2O_ckd_mt_320_v1, FH2O_ckd_mt_320_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_320_self_h2o()
void CKD_mt_320_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 3.20 H2O self continuum absorption model.
The following modifications to the self water vapor continuum arise from:
August 2017: New coefficients for self continuum in window regions for wavenumbers greater than 2000 cm-1 were added and self continuum temperature dependence from 1800-3500 cm-1 were updated (E.J. Mlawer, M.J. Alvarado, K.E. Cady-Pereira).
November 2016: SFAC re-adjusted based on RHUBC-II campaign. (Mlawer, E.J. et al. 2018 Analysis of water vapor absorption in the far-infrared and submillimeter regions using surface radiometric measurements fromextremely dry locations, submitted)
July 2016: Self continuum coefficients were modified from 1880-2390 cm-1 to fix issues in the CO fundamental region that were pointed out by Alvarado et al. (2013).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 3.20 contnm.f90 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Emma Turner
Date
2018-29-10
Definition at line 9019 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SL260_ckd_mt_320, SL260_ckd_mt_320_dv, SL260_ckd_mt_320_npt, SL260_ckd_mt_320_v1, SL260_ckd_mt_320_v2, SL296_ckd_mt_320, SL296_ckd_mt_320_dv, SL296_ckd_mt_320_npt, SL296_ckd_mt_320_v1, SL296_ckd_mt_320_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_n2()
void CKD_mt_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
Model reference: version_1 of the Nitrogen Collision Induced Fundamental Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann, Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling, Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann,
Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996)
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10332 of file legacy_continua.cc.
References a1, a2, addF77fields, CREATE_OUT3, N2N2_N2F_ckd_mt_100, N2N2_N2F_ckd_mt_100_dv, N2N2_N2F_ckd_mt_100_npt, N2N2_N2F_ckd_mt_100_v1, N2N2_N2F_ckd_mt_100_v2, N2N2_N2Ft_ckd_mt_100, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_o2()
void CKD_mt_CIAfun_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
Model reference: F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet, "Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling", Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-O2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet,
Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996).
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10958 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2O2_O2F_ckd_mt_100_dv, O2O2_O2F_ckd_mt_100_npt, O2O2_O2F_ckd_mt_100_v1, O2O2_O2F_ckd_mt_100_v2, O2O2_O2Fo_ckd_mt_100, O2O2_O2Ft_ckd_mt_100, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_CIArot_n2()
void CKD_mt_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
Model reference: Borysow, A, and L. Frommhold, "Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K", The Astrophysical Journal, 311, 1043-1057, 1986.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA rot. band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Borysow, A, and L. Frommhold,
Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K,
The Astrophysical Journal, 311, 1043-1057, 1986.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 10113 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, N2N2_CT220_ckd_mt_100, N2N2_CT220_ckd_mt_100_dv, N2N2_CT220_ckd_mt_100_npt, N2N2_CT220_ckd_mt_100_v1, N2N2_CT220_ckd_mt_100_v2, N2N2_CT296_ckd_mt_100, N2N2_CT296_ckd_mt_100_dv, N2N2_CT296_ckd_mt_100_npt, N2N2_CT296_ckd_mt_100_v1, N2N2_CT296_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_co2()
void CKD_mt_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 9678 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_v0v0_o2()
void CKD_mt_v0v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen collision induced fundamental model of O2 continuum formulated by Mate et al. over the spectral region 7550-8486 cm-1: B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty, "Absolute Intensities for the O2 1.27 micron continuum absorption", J. Geophys. Res., 104, 30,585-30,590, 1999.
The units of these continua coefficients are 1 / (amagat_O2*amagat_air)
Also, refer to the paper "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Mlawer, Clough, Brown, Stephen, Landry, Goldman, & Murcray, Journal of Geophysical Research (1997).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v0<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Remarks
B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty,
Absolute Intensities for the O2 1.27 micron continuum absorption,
J. Geophys. Res., 104, 30,585-30,590, 1999.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 11157 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_00_ckd_mt_100, O2_00_ckd_mt_100_dv, O2_00_ckd_mt_100_npt, O2_00_ckd_mt_100_v1, O2_00_ckd_mt_100_v2, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CKD_mt_v1v0_o2()
void CKD_mt_v1v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen v1<-v0 band model of Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray, "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Journal of Geophysical Research, vol 103, no. D4, pp. 3859-3863, 1998.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v1<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray,
Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands,
J. Geophys. Res., 103, D4, 3859-3863, 1998.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 11344 of file legacy_continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_10_ckd_mt_100_dv, O2_10_ckd_mt_100_v1, O2_10_ckd_mt_100_v2, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
CP98H2OAbsModel()
void CP98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CP98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to Cruz-Pol 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'CruzPol', 'CruzPolLines', 'CruzPolContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: S. L. Cruz-Pol et al., Radio Science, 33(5), 1319, 1998.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6610 of file legacy_continua.cc.
References CREATE_OUT3, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
ELL07WaterDropletAbs()
void ELL07WaterDropletAbs (MatrixView pxsec, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
ELL07WaterDropletAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to ELL07 [1/m]
model allows choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Allowed models: 'ELL07'. See the user guide for detailed explanations.
Remarks
Reference: W. J. Ellison,
Permittivity of Pure Water, at Standard Atmospheric Pressure, over the Frequency Range 0-25 THz and Temperature Range 0-100C,
J. Phys. Chem. Ref. Data, Vol. 36, No. 1, 2007
Author
Stuart Fox
Date
2015-06-03
Definition at line 15608 of file legacy_continua.cc.
References a1, a2, b1, b2, dB_km_to_1_m, Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, and pow().
Referenced by xsec_continuum_tag().
MaTipping_H2O_foreign_continuum()
void MaTipping_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MaTipping_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'MaTipping', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Q. Ma and R. H. Tipping, J. Chem. Phys., 117(23), 10581, 2002.
Author
Thomas Kuhn
Date
2002-12-04
Definition at line 6950 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM85O2AbsModel()
void MPM85O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM85O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM85', 'MPM85Lines', 'MPM85Continuum', 'MPM85NoCoupling', 'MPM85NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
An updated model for millimeter wave propagation in moist air,,
Radio Science, vol. 20, pp. 1069-1089, 1985
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12160 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM87H2OAbsModel()
void MPM87H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM87H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM87 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the H2O-line strengths [1]
CWin scaling factor for the H2O-line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
H. J. Liebe,
A contribution to modeling atmospheric millimeter-wave properties,
Frequenz, 41, 1987, 31-36
and
H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modeling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences,
325 Broadway, Boulder, CO 80303-3328, report 87224.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 5482 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and pow().
Referenced by xsec_continuum_tag().
MPM87O2AbsModel()
void MPM87O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM87O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', 'MPM87NoCoupling', 'MPM87NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modelling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences, rep. 87-224,
325 Broadway, Boulder, CO 80303-3328
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12430 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM89H2OAbsModel()
void MPM89H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM89H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM89 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe, Int. J. Infrared and Millimeter Waves, 10(6), 1989, 631.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 5654 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and pow().
Referenced by xsec_continuum_tag().
MPM89O2AbsModel()
void MPM89O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM89O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', 'MPM89NoCoupling', 'MPM89NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
MPM - an atmospheric millimeter-wave propagation model,
Int. J. Infrared and Mill. Waves, Vol 10, pp. 631-650, 1989.
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 12693 of file legacy_continua.cc.
References CREATE_OUT3, Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM92O2AbsModel()
void MPM92O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr)
MPM93_H2O_continuum()
void MPM93_H2O_continuum (MatrixView pxsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 H2O pseudo continuum line parameters:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O according to MPM87 [1/m]
fcenter continuum pseudo-line center frequency [Hz]
b1 continuum pseudo-line line strength [Hz/Pa]
b2 continuum pseudo-line line strength temperature exponent [1]
b3 continuum pseudo-line line broadening parameter [Hz/Pa]
b4 continuum pseudo-line line broadening parameter [1]
b5 continuum pseudo-line line broadening parameter [1]
b6 continuum pseudo-line line broadening parameter [1]
model allows user defined input parameter set (fcenter and b1 to b6)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters fcenter and b1 to b6 are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 12033 of file legacy_continua.cc.
References b1, b2, CREATE_OUT3, dB_km_to_1_m, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93_N2_continuum()
void MPM93_N2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 N2 continuum.
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to MPM93 [1/m]
Cin continuum strength [ppm/GHz]
Gin width parameter [Hz/Pa]
xTin continuum strength temperature exponent [1]
xfin continuum frequency exponent [1]
model allows user defined input parameter set (Cin, Gin, xTin, and xfin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr N2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin, Gin, xTin, and xfin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14640 of file legacy_continua.cc.
References CREATE_OUT3, fac(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, pow(), and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
MPM93_O2_continuum()
void MPM93_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 O2 continuum:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to MPM93 [1/m]
S0in O2-continuum strength [1/Pa]
G0in O2-continuum width [Hz/Pa]
XS0in O2-continuum strength temperature exponent [1]
XG0in O2-continuum width temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, xS0in, and xG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, xS0in, and xG0in are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14098 of file legacy_continua.cc.
References CREATE_OUT3, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, pow(), SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93H2OAbsModel()
void MPM93H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM93 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Attention
The H2O lines at 547.676440 GHz and 552.020960 GHz are isotopologue lines:
547 GHz is from the isotopologue 1-8-1 (HITRAN code 181, JPL code 20003) with an isotopologue ratio of 0.00199983 and
552 GHz is from the isotopologue 1-7-1 (HITRAN code 171, JPL code 19003) with an isotopologue ratio of 0.00037200.
The original source code of MPM93 has these isotopologue ratios not included in the line strength parameter b1, which is an error.
In the arts implementation the line strength parameter b1 of these two lines is multiplied with the appropriate isotopologue ratio.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6095 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and pow().
Referenced by xsec_continuum_tag().
MPM93IceCrystalAbs()
void MPM93IceCrystalAbs (MatrixView pxsec, const Numeric CCin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93IceCrystalAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of ice clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the permittivity function a (see page 3-6 in the reference) [1]
CBin scaling parameter of the permittivity function b (see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Except for model 'user' the input parameters CCin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15832 of file legacy_continua.cc.
References dB_km_to_1_m, Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93O2AbsModel()
void MPM93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM93 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', 'MPM93NoCoupling', 'MPM93NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 13479 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93RainExt()
void MPM93RainExt (MatrixView pxsec, const Numeric CEin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93RainExt.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CEin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the factor a_rain [1]
CBin scaling parameter of the exponent b_rain [1]
model allows user defined input parameter (CEin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr rain rate vector (i.e. vertical profile) kg/m2/s
Note
Except for model 'user' the input parameters CEin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: R. L. Olsen and D.V. Rogers and D. B. Hodge,
The aR^b relation in the calculation of rain attenuation,
IEEE Trans. Antennas Propagat., vol. AP-26, pp. 318-329, 1978.
Author
Christian Melsheimer
Date
2003-22-05
Definition at line 15977 of file legacy_continua.cc.
References dB_km_to_1_m, DENSITY_OF_WATER, Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPM93WaterDropletAbs()
void MPM93WaterDropletAbs (MatrixView pxsec, const Numeric CCin, const Numeric CGin, const Numeric CEin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &)
MPM93WaterDropletAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CGin scaling parameter of the first relaxation frequency (gamma_1, see page 3-6 in the reference) [1]
CEin scaling parameter of the first permittivity component (epsilon_0, see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CGin, CEin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile kg/mł
Note
Except for model 'user' the input parameters CCin, CGin, and CEin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15455 of file legacy_continua.cc.
References dB_km_to_1_m, Hz_to_GHz, joker, LIQUID_AND_ICE_TREAT_AS_ZERO, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
MPMLineShapeFunction()
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Return values
MPMLineShapeFunction H2O-line shape function value [1/Hz]
Parameters
gamma H2O-line width [Hz]
fl H2O-line central frequency [Hz]
f frequency position of calculation [Hz]
Note
This function calculates the line shape function of Van Vleck and Weisskopf with the factor (f/fl)ą. for the MPM pseudo continuum line.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 16206 of file legacy_continua.cc.
Referenced by CP98H2OAbsModel(), MPM02H2OAbsModel(), MPM87H2OAbsModel(), MPM89H2OAbsModel(), MPM93_H2O_continuum(), and MPM93H2OAbsModel().
MPMLineShapeO2Function()
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
Return values
MPMLineShapeO2Function O2-line shape function value [1]
Parameters
gamma O2-line width [Hz]
fl H2O-line central frequency of the [Hz]
f frequency position of calculation [Hz]
delta O2-line mixing parameter [1]
Note
This function calculates the line shape function of Van Vleck and Weisskopf for O2 with line mixing.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 16262 of file legacy_continua.cc.
Referenced by MPM85O2AbsModel(), MPM87O2AbsModel(), MPM92O2AbsModel(), MPM93O2AbsModel(), and TRE05O2AbsModel().
Pardo_ATM_H2O_ForeignContinuum()
void Pardo_ATM_H2O_ForeignContinuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Pardo_ATM_H2O_ForeignContinuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 11922 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Pardo_ATM_N2_dry_continuum()
void Pardo_ATM_N2_dry_continuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView h2ovmr, const Verbosity & verbosity)
Pardo_ATM_N2_dry_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio [1]
h2ovmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 14766 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
PWR93O2AbsModel()
void PWR93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, const String & version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmrh2o, ConstVectorView vmr, const Verbosity & verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
REFERENCES FOR EQUATIONS AND COEFFICIENTS: P.W. Rosenkranz, CHAP. 2 and appendix, in ATMOSPHERIC REMOTE SENSING BY MICROWAVE RADIOMETRY (M.A. Janssen, ed., 1993). H.J. Liebe et al, JQSRT V.48, PP.629-643 (1992). M.J. Schwartz, Ph.D. thesis, M.I.T. (1997). SUBMILLIMETER LINE INTENSITIES FROM HITRAN96. This version differs from Liebe's MPM92 in two significant respects:
It uses the modification of the 1- line width temperature dependence recommended by Schwartz: (1/T).
It uses the same temperature dependence (X) for submillimeter line widths as in the 60 GHz band: (1/T)**0.8
history: 05-01-95 P. Rosenkranz 11-05-97 P. Rosenkranz - 1- line modification. 12-16-98 pwr - updated submm freq's and intensities from HITRAN96
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to the P. W. Rosenkranz, 1993 [1/m]
CCin O2-continuum scale factor [1]
CLin O2 line strength scale factor [1]
CWin O2 line broadening scale factor [1]
COin O2 line coupling scale factor [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
version determines model version: 1988, 1993, 1998
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmrh2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models:
'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', 'RosenkranzNoCoupling', and 'user'.
For the parameter version the following three string values are allowed: 'PWR88', 'PWR93', 'PWR98'.
See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 13762 of file legacy_continua.cc.
References CREATE_OUT3, Hz_to_GHz, joker, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, PI, pow(), and VMRCalcLimit.
Referenced by test_mpm20(), and xsec_continuum_tag().
PWR98H2OAbsModel()
void PWR98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
PWR98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to P. W. Rosenkranz, 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6329 of file legacy_continua.cc.
References CREATE_OUT3, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and pow().
Referenced by xsec_continuum_tag().
Rosenkranz_CO2_foreign_continuum()
void Rosenkranz_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_n2 N2 volume mixing ratio profile [1]
vmr CO2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15168 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Rosenkranz_CO2_self_continuum()
void Rosenkranz_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-CO2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 15073 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Rosenkranz_N2_self_continuum()
void Rosenkranz_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_N2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xin temperature exponent of N2-continuum [1]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14865 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Rosenkranz_O2_continuum()
void Rosenkranz_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
3) O2-air
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993. Also stated in Liebe et al. JQSRT, Vol 48, Nr 5/6, pp. 629-643, 1992. Default continuum parameters are C=1.6E-17*10E-9, x=0.8
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to Rosenkranz 1993 [1/m]
S0in line strength [K˛/(Hz*Pa*m)]
G0in line width [Hz/Pa]
XS0in line strength temperature exponent [1]
XG0in line widths temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, XS0in, and XG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, XS0in, and XG0in are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14242 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Standard_H2O_foreign_continuum()
void Standard_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_t predefined temperature grid [K]
abs_p predefined pressure [Pa]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-08-03
Definition at line 6839 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Standard_H2O_self_continuum()
void Standard_H2O_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-H2O continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)˛]
xin temperature exponent of (300/T) [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6730 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
Standard_N2_self_continuum()
void Standard_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
4) N2-N2
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)˛]
xfin continuum frequency exponent [1]
xtin continuum strength temperature exponent [1]
xpin continuum strength pressure exponent [1]
model allows user defined input parameter set (Cin, xfin, xtin, and xpin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin, xfin, xtin, and xpin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 14964 of file legacy_continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and pow().
Referenced by xsec_continuum_tag().
TRE05O2AbsModel()
void TRE05O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
TRE05O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to TRE05 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'TRE05', 'TRE05Lines', 'TRE05Continuum', 'TRE05NoCoupling', 'TRE05NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
References: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
M.Yu. Tretyakov, M.A. Koshelev, V.V. Dorovskikh, D.S. Makarov, P.W. Rosenkranz; 60-GHz oxygen band: precise broadening and central frequencies of fine-structure lines, absolute absorption profile at atmospheric pressure, and revision of mixing coefficients doi:10.1016/j.jms.2004.11.011
Remarks
This is a copy of MPM93O2AbsModel with an exception of having new values from the Tretyakov etal. 2005 paper.
Author
Richard Larsson
Date
2013-09-20
Definition at line 13217 of file legacy_continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, joker, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, pow(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
xsec_continuum_tag()
void xsec_continuum_tag (MatrixView xsec, const String & name, ConstVectorView parameters, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView abs_o2, ConstVectorView vmr, const Verbosity & verbosity)
Calculates model absorption for one continuum or full model tag.
Note, that only one tag can be taken at a time.
Calculated is the true absorption cross section, that means you have to multiply this with n*VMR in order to get the absorption coefficient in units of 1/m.
This is the type of xsec that is used all over ARTS, but not what is used by the internal continuum functions! (We have to divide the output of the internal continuum functions by the number density n.)
Return values
xsec Cross section of one continuum tag,
xsec = alpha / (n*VMR) [m^2]. This is both input and output! (The function adds the continuum absorption cross section to the previous content of xsec.)
Parameters
name The name of the model to calculate (derived from the tag name)
parameters model parameters, as defined in method abs_cont_parameters.
model model, related to model parameters
f_grid Frequency grid [Hz]
abs_p Pressure grid [Pa]
abs_t Temperatures associated with the pressure grid, abs_p [K]
abs_n2 Total volume mixing ratio profile of molecular nitrogen.
This will be needed only for the CO2 foreign continuum [1]
however one is forced to give this input [1]
abs_h2o Total volume mixing ratio profile of water vapor.
This will be needed only for the oxygen continuum
however one is forced to give this input [1]
vmr Volume mixing ratio profile of the actual species [1]
Author
Stefan Buehler, Thomas Kuhn
Date
2001-11-05
Definition at line 16340 of file legacy_continua.cc.
References abs, BF86_CIA_N2(), BOLTZMAN_CONST, CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), CP98H2OAbsModel(), CREATE_OUT3, ELL07WaterDropletAbs(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), joker, LIQUID_AND_ICE_TREAT_AS_ZERO, MaTipping_H2O_foreign_continuum(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), parameters, Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), ConstVectorView::sum(), and TRE05O2AbsModel().
Referenced by abs_xsec_per_speciesAddConts().