ARTS: legendre.h File Reference
legendre.h File Reference
Contains the code to calculate Legendre polynomials.
#include "arts.h"
#include "grids.h"
#include "matpackI.h"
Classes
struct gsl_integration_glfixed_table
struct Legendre::SphericalField
Stores the up (U), south (S), east (E) values of a field relative to the sphere.
Namespaces
Legendre
Typedefs
using Legendre::MatrixOfSphericalField = Grid< SphericalField, 2 >
Holds a SphericalField for multiple dimensions (radius times longitudes)
Functions
bool gsl_integration_glfixed_table_alloc (Vector &x, Vector &w, Index n)
gsl_integration_glfixed_table_alloc
SphericalField Legendre::schmidt_fieldcalc (const Matrix &g, const Matrix &h, const Numeric r0, const Numeric r, const Numeric lat, const Numeric lon) ARTS_NOEXCEPT
Computes the spherical field.
MatrixOfSphericalField Legendre::schmidt_fieldcalc (const Matrix &g, const Matrix &h, const Numeric r0, const Vector &r, const Numeric lat, const Vector &lon) ARTS_NOEXCEPT
Computes the spherical field for many radius and longitudes.
Detailed Description
Contains the code to calculate Legendre polynomials.
Author
Oliver Lemke
Date
2003-08-14
Definition in file legendre.h.
Function Documentation
gsl_integration_glfixed_table_alloc()
bool gsl_integration_glfixed_table_alloc (Vector & x, Vector & w, Index n)
gsl_integration_glfixed_table_alloc
This function determines the Gauss-Legendre abscissae and weights necessary for an n-point fixed order integration scheme. If possible, high precision precomputed coefficients are used. If precomputed weights are not available, lower precision coefficients are computed on the fly.
Code is taken from the GNU Scientific Library under GPLv3 license. Adapted to return ARTS datatypes.
Parameters
[out] x Vector with Gauss-Legendre abscissae.
[out] w Vector with Gauss-Legendre weights.
[in] n Integration scheme order.
Returns
true if precomputed values have been used.
Author
Oliver Lemke
Date
2018-05-29
Definition at line 1940 of file legendre.cc.
References w(), and ARTS::Var::x().
Referenced by AngularGridsSetFluxCalc().