ARTS: linefunctions.cc File Reference
linefunctions.cc File Reference
#include "linefunctions.h"
#include <Eigen/Core>
#include <Faddeeva/Faddeeva.hh>
#include "constants.h"
#include "linescaling.h"
Functions
Complex w (Complex z) noexcept
The Faddeeva function.
constexpr Complex dw (Complex z, Complex w) noexcept
The Faddeeva function partial derivative.
constexpr Complex pCqSDHC_to_arts (Complex x) noexcept
Conversion from CGS-style lineshape to ARTS.
constexpr Complex pCqSDHC_to_arts_freq_deriv (Complex x) noexcept
Conversion from CGS-style lineshape to ARTS for frequncy derivatives.
constexpr Complex pCqSDHC_to_arts_G2_deriv (Complex x) noexcept
Conversion from CGS-style lineshape to ARTS G2 derivative.
constexpr Complex pCqSDHC_to_arts_D2_deriv (Complex x) noexcept
Conversion from CGS-style lineshape to ARTS D2 derivative.
Function Documentation
dw()
constexpr Complex dw (Complex z, Complex w) constexpr noexcept
The Faddeeva function partial derivative.
Definition at line 45 of file linefunctions.cc.
References w().
Referenced by Linefunctions::set_lorentz(), and Linefunctions::set_voigt().
pCqSDHC_to_arts()
constexpr Complex pCqSDHC_to_arts (Complex x) constexpr noexcept
Conversion from CGS-style lineshape to ARTS.
Definition at line 50 of file linefunctions.cc.
References c, conj(), Conversion::kaycm_per_cmsquared2hz_per_msquared(), Constant::pow2(), and ARTS::Var::x().
pCqSDHC_to_arts_D2_deriv()
constexpr Complex pCqSDHC_to_arts_D2_deriv (Complex x) constexpr noexcept
Conversion from CGS-style lineshape to ARTS D2 derivative.
Definition at line 78 of file linefunctions.cc.
References c, Conversion::kaycm_per_cmsquared2hz_per_msquared(), Constant::pow4(), and ARTS::Var::x().
pCqSDHC_to_arts_freq_deriv()
constexpr Complex pCqSDHC_to_arts_freq_deriv (Complex x) constexpr noexcept
Conversion from CGS-style lineshape to ARTS for frequncy derivatives.
Definition at line 59 of file linefunctions.cc.
References c, Conversion::kaycm_per_cmsquared2hz_per_msquared(), Constant::pow4(), and ARTS::Var::x().
pCqSDHC_to_arts_G2_deriv()
constexpr Complex pCqSDHC_to_arts_G2_deriv (Complex x) constexpr noexcept
Conversion from CGS-style lineshape to ARTS G2 derivative.
Definition at line 68 of file linefunctions.cc.
References c, Conversion::kaycm_per_cmsquared2hz_per_msquared(), Constant::pow4(), and ARTS::Var::x().
w()
Complex w (Complex z) inline noexcept
The Faddeeva function.
Definition at line 42 of file linefunctions.cc.
Referenced by AngularGridsSetFluxCalc(), bin_quadweights(), LineShape::SpeedDependentVoigt::calc(), LineShape::HartmannTran::calc(), calcBaselineFit(), calculate_weights_linear(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__eigen(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__explicit(), lm_hitran_2017::compabs(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), dotprod_with_los(), dtransmat4(), dw(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), find_all(), find_first(), Flatten(), gzstreambuf::flush_buffer(), from_dpath_to_dx(), Zeeman::FromGrids(), geo_posWherePpathPassesZref(), gsl_integration_glfixed_table_alloc(), jacobianAddMagField(), jacobianAddWind(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), PropagationMatrix::LeftMultiplyAtPosition(), los_xyz_by_uvw_local(), MagFieldsFromAltitudeRawCalc(), PropagationMatrix::MatrixInverseAtPosition(), mblock_dlos_gridUniformCircular(), mblock_dlos_gridUniformRectangular(), met_mm_polarisation_hmatrix(), polint(), ppath_end_2d(), ppathFromRtePos2(), CIARecord::ReadFromCIA(), PropagationMatrix::RightMultiplyAtPosition(), sensor_responseFillFgrid(), sensor_responsePolarisation(), Linefunctions::set_voigt(), oem::NormalizingSolver< TransformationMatrixType, SolverType >::solve(), stokes2pol(), surfaceLambertianSimple(), surfaceSplitSpecularTo3beams(), test_gsl_int(), test_matrix_buildup(), test_matrix_exp_propmat(), test_transmat_from_propmat(), transmat4(), and x2artsSensor().