ARTS: linescaling.h File Reference
linescaling.h File Reference
Constains various line scaling functions.
#include "absorption.h"
#include "constants.h"
Functions
Numeric single_partition_function (const Numeric &T, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data) noexcept
Computes the partition function at one temperature.
Numeric dsingle_partition_function_dT (const Numeric &T, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data) noexcept
Computes the partition function temperature derivative.
Numeric stimulated_emission (Numeric T, Numeric F0)
Computes exp(-hf/kT)
Numeric dstimulated_emissiondT (Numeric T, Numeric F0)
Computes temperature derivative of exp(-hf/kT)
Numeric dstimulated_emissiondF0 (Numeric T, Numeric F0)
Computes frequency derivative of exp(-hf/kT)
Numeric stimulated_relative_emission (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
Numeric dstimulated_relative_emission_dT (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
Numeric dstimulated_relative_emission_dF0 (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
Numeric stimulated_relative_emission (const Numeric &gamma, const Numeric &gamma_ref)
Computes (1 - gamma) / (1 - gamma_ref)
Numeric dstimulated_relative_emission_dT (const Numeric &gamma, const Numeric &gamma_ref, const Numeric &F0, const Numeric &T)
Computes temperature derivative of (1 - gamma) / (1 - gamma_ref)
Numeric dstimulated_relative_emission_dF0 (const Numeric &gamma, const Numeric &gamma_ref, const Numeric &T, const Numeric &T0)
Computes frequency derivative of (1 - gamma) / (1 - gamma_ref)
Numeric boltzman_ratio (const Numeric &T, const Numeric &T0, const Numeric &E0)
Computes exp(E0/c (T - T0) / (T * T0))
Numeric dboltzman_ratio_dT (const Numeric &boltzmann_ratio, const Numeric &T, const Numeric &E0)
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0))
constexpr Numeric dboltzman_ratio_dT_div_boltzmann_ratio (Numeric T, Numeric E0)
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0)) / exp(E0/c (T - T0) / (T * T0))
Numeric boltzman_factor (Numeric T, Numeric E0)
Computes exp(- E0/kT)
Numeric dboltzman_factordT (Numeric T, Numeric E0)
Computes temperature derivatives exp(- E0/kT)
Numeric dboltzman_factordE0 (Numeric T, Numeric E0)
Computes lower state energy derivatives exp(- E0/kT)
Numeric absorption_nlte_ratio (const Numeric &gamma, const Numeric &r_upp=1.0, const Numeric &r_low=1.0) noexcept
Computes (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dT (const Numeric &gamma, const Numeric &T, const Numeric &F0, const Numeric &El, const Numeric &Eu, const Numeric &r_upp=1.0, const Numeric &r_low=1.0)
Computes temperature derivatives of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dF0 (const Numeric &gamma, const Numeric &T, const Numeric &r_upp=1.0, const Numeric &r_low=1.0)
Computes frequency derivative of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dTl (const Numeric &gamma, const Numeric &T, const Numeric &Tl, const Numeric &El, const Numeric &r_low=1.0)
Computes lower state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dTu (const Numeric &gamma, const Numeric &T, const Numeric &Tu, const Numeric &Eu, const Numeric &r_upp=1.0)
Computes upper state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Detailed Description
Constains various line scaling functions.
Author
Richard Larsson
Date
2015-06-25
Headers for line scaling functions
Helps to solve line scaling and derivatives for lbl calculations
Definition in file linescaling.h.
Function Documentation
absorption_nlte_ratio()
Numeric absorption_nlte_ratio (const Numeric & gamma, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0) noexcept
Computes (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
(r_low - r_upp * gamma) / (1 - gamma)
Definition at line 195 of file linescaling.cc.
boltzman_factor()
Numeric boltzman_factor (Numeric T, Numeric E0)
Computes exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
exp(- E0/kT)
Definition at line 176 of file linescaling.cc.
References E0.
Referenced by lm_hitran_2017::convtp(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
boltzman_ratio()
Numeric boltzman_ratio (const Numeric & T, const Numeric & T0, const Numeric & E0)
Computes exp(E0/c (T - T0) / (T * T0))
Parameters
[in] T Temperature
[in] T0 Reference temperature
[in] E0 Lower state energy
Returns
exp(E0/c (T - T0) / (T * T0))
Definition at line 159 of file linescaling.cc.
Referenced by lm_hitran_2017::convtp(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
dabsorption_nlte_rate_dF0()
Numeric dabsorption_nlte_rate_dF0 (const Numeric & gamma, const Numeric & T, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0)
Computes frequency derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dF0
Definition at line 225 of file linescaling.cc.
References BOLTZMAN_CONST, c, PLANCK_CONST, and Constant::pow2().
dabsorption_nlte_rate_dT()
Numeric dabsorption_nlte_rate_dT (const Numeric & gamma, const Numeric & T, const Numeric & F0, const Numeric & El, const Numeric & Eu, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0)
Computes temperature derivatives of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] F0 Central frequency
[in] El Lower state energy
[in] Eu Upper state energy
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dT
Definition at line 201 of file linescaling.cc.
References ARTS_USER_ERROR_IF, BOLTZMAN_CONST, c, F0, PLANCK_CONST, and ARTS::Var::x().
dabsorption_nlte_rate_dTl()
Numeric dabsorption_nlte_rate_dTl (const Numeric & gamma, const Numeric & T, const Numeric & Tl, const Numeric & El, const Numeric & r_low = 1.0)
Computes lower state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] Tl Temperature of lower level
[in] El Lower state energy
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dTl
Definition at line 236 of file linescaling.cc.
References BOLTZMAN_CONST, ARTS::Var::x(), and ARTS::Var::y().
dabsorption_nlte_rate_dTu()
Numeric dabsorption_nlte_rate_dTu (const Numeric & gamma, const Numeric & T, const Numeric & Tu, const Numeric & Eu, const Numeric & r_upp = 1.0)
Computes upper state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] Tu Temperature of lower level
[in] Eu Lower state energy
[in] r_upp Relative ratio NLTE/LTE in upper ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dTu
Definition at line 249 of file linescaling.cc.
References BOLTZMAN_CONST, ARTS::Var::x(), and ARTS::Var::y().
dboltzman_factordE0()
Numeric dboltzman_factordE0 (Numeric T, Numeric E0)
Computes lower state energy derivatives exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
dexp(- E0/kT) / dE0
Definition at line 189 of file linescaling.cc.
References E0.
dboltzman_factordT()
Numeric dboltzman_factordT (Numeric T, Numeric E0)
Computes temperature derivatives exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
dexp(- E0/kT) / dT
Definition at line 182 of file linescaling.cc.
References E0, and Constant::pow2().
dboltzman_ratio_dT()
Numeric dboltzman_ratio_dT (const Numeric & boltzmann_ratio, const Numeric & T, const Numeric & E0)
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0))
Parameters
[in] boltzmann_ratio Output of boltzmann_ratio(...)
[in] T Temperature
[in] E0 Lower state energy
Returns
exp(E0/k (T - T0) / (T * T0))
Definition at line 166 of file linescaling.cc.
References BOLTZMAN_CONST, c, and E0.
dboltzman_ratio_dT_div_boltzmann_ratio()
constexpr Numeric dboltzman_ratio_dT_div_boltzmann_ratio (Numeric T, Numeric E0) constexpr
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0)) / exp(E0/c (T - T0) / (T * T0))
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
E0 k / T^2
Definition at line 194 of file linescaling.h.
References E0.
dsingle_partition_function_dT()
Numeric dsingle_partition_function_dT (const Numeric & T, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data) noexcept
Computes the partition function temperature derivative.
Parameters
[in] T Temperature
[in] partition_type Switch for partition type of line
[in] partition_data Partition data of line
Returns
partition function derivative wrt temperature
Definition at line 78 of file linescaling.cc.
References SpeciesAuxData::AT_PARTITIONFUNCTION_COEFF, SpeciesAuxData::AT_PARTITIONFUNCTION_TFIELD, data, SingleCalculatePartitionFctFromCoeff_dT(), and SingleCalculatePartitionFctFromData_dT().
Referenced by LineShape::compute(), and xsec_species().
dstimulated_emissiondF0()
Numeric dstimulated_emissiondF0 (Numeric T, Numeric F0)
Computes frequency derivative of exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
dexp(-hf/kT) / dF0
Definition at line 107 of file linescaling.cc.
References F0.
dstimulated_emissiondT()
Numeric dstimulated_emissiondT (Numeric T, Numeric F0)
Computes temperature derivative of exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
dexp(-hf/kT) / dT
Definition at line 101 of file linescaling.cc.
References F0, and Constant::pow2().
dstimulated_relative_emission_dF0() [1/2]
Numeric dstimulated_relative_emission_dF0 (const Numeric & gamma, const Numeric & gamma_ref, const Numeric & T, const Numeric & T0)
Computes frequency derivative of (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
[in] T Temperature
[in] T0 Reference temperature
Returns
d[(1 - gamma) / (1 - gamma_ref)] / dF0
Definition at line 144 of file linescaling.cc.
dstimulated_relative_emission_dF0() [2/2]
Numeric dstimulated_relative_emission_dF0 (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
\[ \frac{h\left(T\left[1 -e^{h f_0/k T}\right] e^{h f_0 / k T_0} - T_0 \left[1 -e^{h f_0/k T_0}\right] e^{h f_0 / k T} \right)}{kTT_0 \left(1 -e^{h f_0/k T_0}\right)^2} \]
using std::expm1 for increased low number accuracies
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
Returns
\(\frac{h\left(T\left[1 -e^{h f_0/k T}\right] e^{h f_0 / k T_0} - T_0 \left[1 -e^{h f_0/k T_0}\right] e^{h f_0 / k T} \right)}{kTT_0 \left(1 -e^{h f_0/k T_0}\right)^2} \)
Definition at line 122 of file linescaling.cc.
dstimulated_relative_emission_dT() [1/2]
Numeric dstimulated_relative_emission_dT (const Numeric & gamma, const Numeric & gamma_ref, const Numeric & F0, const Numeric & T)
Computes temperature derivative of (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
[in] F0 Frequency
[in] T Temperature
Returns
d[(1 - gamma) / (1 - gamma_ref)] / dT
Definition at line 133 of file linescaling.cc.
References BOLTZMAN_CONST, c, F0, and PLANCK_CONST.
dstimulated_relative_emission_dT() [2/2]
Numeric dstimulated_relative_emission_dT (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
\[ \frac{1}{T} \frac{h f_0}{k T} \frac{e^{h f_0/k T}}{1 - e^{h f_0 / k T_0}} \]
using std::expm1 for increased low number accuracies
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
Returns
\(\frac{1}{T} \frac{h f_0}{k T} \frac{e^{h f_0/k T}}{1 - e^{h f_0 / k T_0}} \)
Definition at line 117 of file linescaling.cc.
single_partition_function()
Numeric single_partition_function (const Numeric & T, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data) noexcept
Computes the partition function at one temperature.
Parameters
[in] T Temperature
[in] partition_type Switch for partition type of line
[in] partition_data Partition data of line
Returns
partition function
Definition at line 64 of file linescaling.cc.
References SpeciesAuxData::AT_PARTITIONFUNCTION_COEFF, SpeciesAuxData::AT_PARTITIONFUNCTION_TFIELD, data, SingleCalculatePartitionFctFromCoeff(), and SingleCalculatePartitionFctFromData().
Referenced by LineShape::compute(), lm_hitran_2017::convtp(), Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole(), and xsec_species().
stimulated_emission()
Numeric stimulated_emission (Numeric T, Numeric F0)
Computes exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
exp(-hf/kT)
Definition at line 95 of file linescaling.cc.
References F0.
Referenced by lm_hitran_2017::compabs(), lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
stimulated_relative_emission() [1/2]
Numeric stimulated_relative_emission (const Numeric & gamma, const Numeric & gamma_ref)
Computes (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
Returns
(1 - gamma) / (1 - gamma_ref)
Definition at line 128 of file linescaling.cc.
stimulated_relative_emission() [2/2]
Numeric stimulated_relative_emission (const Numeric F0, const Numeric T0, const Numeric T) noexcept
Computes.
\[ \frac{1 - e^{h f_0/k T}}{1 - e^{h f_0 / k T_0}} \]
using std::expm1 for increased low number accuracies
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
Returns
\(\frac{1 - e^{h f_0/k T}}{1 - e^{h f_0 / k T_0}} \)
Definition at line 113 of file linescaling.cc.