ARTS: lineshapemodel.cc File Reference
lineshapemodel.cc File Reference
Contains the line shape namespace.
#include "lineshapemodel.h"
Namespaces
LineShape
Computations of line shape derived parameters.
LineShape::LegacyLineFunctionData
Legacy dealing with reading old LineFunctionData.
LineShape::LegacyLineMixingData
Legacy dealing with reading old LineMixingData.
LineShape::LegacyPressureBroadeningData
Legacy dealing with reading old PressureBroadeningData.
Macros
#define ReturnJacPropMatType(ID)
#define x0 X[Index(var)].X0
#define x1 X[Index(var)].X1
#define x2 X[Index(var)].X2
#define x3 X[Index(var)].X3
#define LSPC(XVAR, PVAR)
#define LSPCV(XVAR, PVAR)
#define LSPCT(XVAR, PVAR)
#define LSPDC(XVAR, DERIV, PVAR)
#define RETURNINTERNALDERIVATIVE(TYPE)
Functions
ArrayOfString AllLineShapeCoeffs ()
All available line shape coefficients.
ArrayOfString AllLineShapeVars ()
All available line shape variables.
Jacobian::Line select_derivativeLineShape (const String &var, const String &coeff)
Return the derivative type based on string input.
Numeric & LineShape::SingleModelParameter (ModelParameters &mp, const String &type)
Get a coefficient from ModelParameters by name.
std::ostream & LineShape::operator<< (std::ostream &os, const ModelParameters &mp)
Output operator for ModelParameters.
std::istream & LineShape::operator>> (std::istream &is, ModelParameters &mp)
Input operator for ModelParameters.
std::ostream & LineShape::operator<< (std::ostream &os, const SingleSpeciesModel &ssm)
Output operator for SingleSpeciesModel.
std::istream & LineShape::operator>> (std::istream &is, SingleSpeciesModel &ssm)
Input operator for SingleSpeciesModel.
std::ostream & LineShape::operator<< (std::ostream &os, Output x)
Type of line shape to compute.
std::vector< Variable > LineShape::LegacyLineFunctionData::lineshapetag2variablesvector (String type)
Line shape models from string.
std::vector< Variable > LineShape::LegacyLineFunctionData::linemixingtag2variablesvector (String type)
Line mixing models from string.
LegacyLineMixingData::TypeLM LineShape::LegacyLineMixingData::string2typelm (String type)
Line mixing types from string.
LegacyPressureBroadeningData::TypePB LineShape::LegacyPressureBroadeningData::string2typepb (String type)
Pressure broadening types from string.
Index LineShape::LegacyPressureBroadeningData::self_listed (const QuantumIdentifier &qid, LegacyPressureBroadeningData::TypePB t)
Pressure broadening if self exist.
Detailed Description
Contains the line shape namespace.
Author
Richard Larsson
Date
2018-09-19
Implementations of lineshapemodel.h
This mostly contains functions that either did not compile while placed in the header or for other reasons are not there. This means most of the real work happens in the header file and not here
Definition in file lineshapemodel.cc.
Macro Definition Documentation
LSPC
#define LSPC (XVAR, PVAR)
Value:
  Numeric Model::XVAR(                                                         \
      Numeric T, Numeric T0, Numeric P [[maybe_unused]], ConstVectorView vmrs) \
      const noexcept {                                                         \
    return PVAR *                                                              \
           std::inner_product(                                                 \
               mdata.cbegin(),                                                 \
               mdata.cend(),                                                   \
               vmrs.begin(),                                                   \
               0.0,                                                            \
               std::plus<Numeric>(),                                           \
               [=](auto& x, auto vmr) -> Numeric {                             \
                 return vmr * x.compute(T, T0, Variable::XVAR);                \
               });                                                             \
  }
Definition at line 1078 of file lineshapemodel.cc.
LSPCT
#define LSPCT (XVAR, PVAR)
Value:
  Numeric Model::d##XVAR##_dT(                                                  \
      Numeric T, Numeric T0, Numeric P [[maybe_unused]], ConstVectorView vmrs)  \
      const noexcept {                                                          \
    return PVAR *                                                               \
           std::inner_product(                                                  \
               mdata.cbegin(),                                                  \
               mdata.cend(),                                                    \
               vmrs.begin(),                                                    \
               0.0,                                                             \
               std::plus<Numeric>(),                                            \
               [=](auto& x, auto vmr) -> Numeric {                              \
                 return vmr * x.compute_dT(T, T0, Variable::XVAR);              \
               });                                                              \
  }
Definition at line 1125 of file lineshapemodel.cc.
LSPCV
#define LSPCV (XVAR, PVAR)
Value:
  Numeric Model::d##XVAR##_dVMR(Numeric T,                           \
                         Numeric T0,                                 \
                         Numeric P [[maybe_unused]],                 \
                         const Index deriv_pos) const noexcept {     \
    if (deriv_pos not_eq -1)                                         \
      return PVAR * mdata[deriv_pos].compute(T, T0, Variable::XVAR); \
    else                                                             \
      return 0;                                                      \
  }
Definition at line 1104 of file lineshapemodel.cc.
LSPDC
#define LSPDC (XVAR, DERIV, PVAR)
Value:
  Numeric Model::d##XVAR##DERIV(Numeric T,                           \
                         Numeric T0,                                 \
                         Numeric P [[maybe_unused]],                 \
                         Index deriv_pos,                            \
                         ConstVectorView vmrs) const noexcept {      \
    if (deriv_pos not_eq -1)                                         \
      return vmrs[deriv_pos] * PVAR *                                \
             mdata[deriv_pos].compute##DERIV(T, T0, Variable::XVAR); \
    else                                                             \
      return 0;                                                      \
  }
Definition at line 1151 of file lineshapemodel.cc.
RETURNINTERNALDERIVATIVE
#define RETURNINTERNALDERIVATIVE (TYPE)
Value:
  case Jacobian::Line::Shape##TYPE##X0:        \
    return d##TYPE##_dX0(T, T0, P, pos, vmrs); \
  case Jacobian::Line::Shape##TYPE##X1:        \
    return d##TYPE##_dX1(T, T0, P, pos, vmrs); \
  case Jacobian::Line::Shape##TYPE##X2:        \
    return d##TYPE##_dX2(T, T0, P, pos, vmrs); \
  case Jacobian::Line::Shape##TYPE##X3:        \
    return d##TYPE##_dX3(T, T0, P, pos, vmrs)
ReturnJacPropMatType
#define ReturnJacPropMatType (ID)
Value:
  (var == #ID) {                                \
    if (coeff == "X0")                          \
      return Jacobian::Line::Shape##ID##X0; \
    else if (coeff == "X1")                     \
      return Jacobian::Line::Shape##ID##X1; \
    else if (coeff == "X2")                     \
      return Jacobian::Line::Shape##ID##X2; \
    else if (coeff == "X3")                     \
      return Jacobian::Line::Shape##ID##X3; \
  }
x0
#define x0 X[Index(var)].X0
Definition at line 772 of file lineshapemodel.cc.
x1
#define x1 X[Index(var)].X1
Definition at line 773 of file lineshapemodel.cc.
x2
#define x2 X[Index(var)].X2
Definition at line 774 of file lineshapemodel.cc.
x3
#define x3 X[Index(var)].X3
Definition at line 775 of file lineshapemodel.cc.
Function Documentation
AllLineShapeCoeffs()
ArrayOfString AllLineShapeCoeffs ()
All available line shape coefficients.
Definition at line 37 of file lineshapemodel.cc.
Referenced by jacobianAddShapeCatalogParameters(), and select_derivativeLineShape().
AllLineShapeVars()
ArrayOfString AllLineShapeVars ()
All available line shape variables.
Definition at line 39 of file lineshapemodel.cc.
Referenced by jacobianAddShapeCatalogParameters(), LineShape::MetaData2ModelShape(), LineShape::ModelShape2MetaData(), and select_derivativeLineShape().
select_derivativeLineShape()
Jacobian::Line select_derivativeLineShape (const String & var, const String & coeff)
Return the derivative type based on string input.
Parameters
[in] var Variable in AllLineShapeVars()
[in] coeff Coefficient in AllLineShapeCoeffs()
Returns
Derivative
Definition at line 43 of file lineshapemodel.cc.
References AllLineShapeCoeffs(), AllLineShapeVars(), v(), and linalg::var().
Referenced by jacobianAddShapeCatalogParameter().