ARTS: linescaling.cc File Reference
linescaling.cc File Reference
#include "linescaling.h"
#include "interpolation_lagrange.h"
Functions
Numeric SingleCalculatePartitionFctFromCoeff (const Numeric &T, ConstVectorView q_grid)
Numeric SingleCalculatePartitionFctFromCoeff_dT (const Numeric &T, ConstVectorView q_grid)
Numeric SingleCalculatePartitionFctFromData (const Numeric &T, ConstVectorView t_grid, ConstVectorView q_grid)
Numeric SingleCalculatePartitionFctFromData_dT (const Numeric &T, ConstVectorView t_grid, ConstVectorView q_grid)
Numeric single_partition_function (const Numeric &T, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data)
Computes the partition function at one temperature.
Numeric dsingle_partition_function_dT (const Numeric &T, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data)
Computes the partition function temperature derivative.
Numeric stimulated_emission (Numeric T, Numeric F0)
Computes exp(-hf/kT)
Numeric dstimulated_emissiondT (Numeric T, Numeric F0)
Computes temperature derivative of exp(-hf/kT)
Numeric dstimulated_emissiondF0 (Numeric T, Numeric F0)
Computes frequency derivative of exp(-hf/kT)
Numeric stimulated_relative_emission (const Numeric &gamma, const Numeric &gamma_ref)
Computes (1 - gamma) / (1 - gamma_ref)
Numeric dstimulated_relative_emission_dT (const Numeric &gamma, const Numeric &gamma_ref, const Numeric &F0, const Numeric &T)
Computes temperature derivative of (1 - gamma) / (1 - gamma_ref)
Numeric dstimulated_relative_emission_dF0 (const Numeric &gamma, const Numeric &gamma_ref, const Numeric &T, const Numeric &T0)
Computes frequency derivative of (1 - gamma) / (1 - gamma_ref)
Numeric boltzman_ratio (const Numeric &T, const Numeric &T0, const Numeric &E0)
Computes exp(E0/c (T - T0) / (T * T0))
Numeric dboltzman_ratio_dT (const Numeric &boltzmann_ratio, const Numeric &T, const Numeric &E0)
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0))
Numeric boltzman_factor (Numeric T, Numeric E0)
Computes exp(- E0/kT)
Numeric dboltzman_factordT (Numeric T, Numeric E0)
Computes temperature derivatives exp(- E0/kT)
Numeric dboltzman_factordE0 (Numeric T, Numeric E0)
Computes lower state energy derivatives exp(- E0/kT)
Numeric absorption_nlte_ratio (const Numeric &gamma, const Numeric &r_upp, const Numeric &r_low)
Computes (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dT (const Numeric &gamma, const Numeric &T, const Numeric &F0, const Numeric &El, const Numeric &Eu, const Numeric &r_upp, const Numeric &r_low)
Computes temperature derivatives of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dF0 (const Numeric &gamma, const Numeric &T, const Numeric &r_upp, const Numeric &r_low)
Computes frequency derivative of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dTl (const Numeric &gamma, const Numeric &T, const Numeric &Tl, const Numeric &El, const Numeric &r_low)
Computes lower state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Numeric dabsorption_nlte_rate_dTu (const Numeric &gamma, const Numeric &T, const Numeric &Tu, const Numeric &Eu, const Numeric &r_upp)
Computes upper state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Function Documentation
absorption_nlte_ratio()
Numeric absorption_nlte_ratio (const Numeric & gamma, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0)
Computes (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
(r_low - r_upp * gamma) / (1 - gamma)
Definition at line 182 of file linescaling.cc.
boltzman_factor()
Numeric boltzman_factor (Numeric T, Numeric E0)
Computes exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
exp(- E0/kT)
Definition at line 163 of file linescaling.cc.
References E0.
Referenced by lm_hitran_2017::convtp(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
boltzman_ratio()
Numeric boltzman_ratio (const Numeric & T, const Numeric & T0, const Numeric & E0)
Computes exp(E0/c (T - T0) / (T * T0))
Parameters
[in] T Temperature
[in] T0 Reference temperature
[in] E0 Lower state energy
Returns
exp(E0/c (T - T0) / (T * T0))
Definition at line 146 of file linescaling.cc.
Referenced by lm_hitran_2017::convtp(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
dabsorption_nlte_rate_dF0()
Numeric dabsorption_nlte_rate_dF0 (const Numeric & gamma, const Numeric & T, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0)
Computes frequency derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dF0
Definition at line 215 of file linescaling.cc.
References BOLTZMAN_CONST, and PLANCK_CONST.
dabsorption_nlte_rate_dT()
Numeric dabsorption_nlte_rate_dT (const Numeric & gamma, const Numeric & T, const Numeric & F0, const Numeric & El, const Numeric & Eu, const Numeric & r_upp = 1.0, const Numeric & r_low = 1.0)
Computes temperature derivatives of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] F0 Central frequency
[in] El Lower state energy
[in] Eu Upper state energy
[in] r_upp Relative ratio NLTE/LTE in upper ratio
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dT
Definition at line 188 of file linescaling.cc.
References BOLTZMAN_CONST, and PLANCK_CONST.
dabsorption_nlte_rate_dTl()
Numeric dabsorption_nlte_rate_dTl (const Numeric & gamma, const Numeric & T, const Numeric & Tl, const Numeric & El, const Numeric & r_low = 1.0)
Computes lower state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] Tl Temperature of lower level
[in] El Lower state energy
[in] r_low Relative ratio NLTE/LTE in lower ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dTl
Definition at line 226 of file linescaling.cc.
References BOLTZMAN_CONST, x, and ARTS::Var::y().
dabsorption_nlte_rate_dTu()
Numeric dabsorption_nlte_rate_dTu (const Numeric & gamma, const Numeric & T, const Numeric & Tu, const Numeric & Eu, const Numeric & r_upp = 1.0)
Computes upper state temperature derivative of (r_low - r_upp * gamma) / (1 - gamma)
Parameters
[in] gamma Stimulated emission at temperature
[in] T Temperature
[in] Tu Temperature of lower level
[in] Eu Lower state energy
[in] r_upp Relative ratio NLTE/LTE in upper ratio
Returns
d[(r_low - r_upp * gamma) / (1 - gamma)] / dTu
Definition at line 239 of file linescaling.cc.
References BOLTZMAN_CONST, x, and ARTS::Var::y().
dboltzman_factordE0()
Numeric dboltzman_factordE0 (Numeric T, Numeric E0)
Computes lower state energy derivatives exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
dexp(- E0/kT) / dE0
Definition at line 176 of file linescaling.cc.
References E0.
dboltzman_factordT()
Numeric dboltzman_factordT (Numeric T, Numeric E0)
Computes temperature derivatives exp(- E0/kT)
Parameters
[in] T Temperature
[in] E0 Lower state energy
Returns
dexp(- E0/kT) / dT
Definition at line 169 of file linescaling.cc.
References E0, and Constant::pow2().
dboltzman_ratio_dT()
Numeric dboltzman_ratio_dT (const Numeric & boltzmann_ratio, const Numeric & T, const Numeric & E0)
Computes temperature derivatives exp(E0/k (T - T0) / (T * T0))
Parameters
[in] boltzmann_ratio Output of boltzmann_ratio(...)
[in] T Temperature
[in] E0 Lower state energy
Returns
exp(E0/k (T - T0) / (T * T0))
Definition at line 153 of file linescaling.cc.
References BOLTZMAN_CONST.
dsingle_partition_function_dT()
Numeric dsingle_partition_function_dT (const Numeric & T, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data)
Computes the partition function temperature derivative.
Parameters
[in] T Temperature
[in] partition_type Switch for partition type of line
[in] partition_data Partition data of line
Returns
partition function derivative wrt temperature
Definition at line 79 of file linescaling.cc.
References SpeciesAuxData::AT_PARTITIONFUNCTION_COEFF, SpeciesAuxData::AT_PARTITIONFUNCTION_TFIELD, data, SingleCalculatePartitionFctFromCoeff_dT(), and SingleCalculatePartitionFctFromData_dT().
Referenced by xsec_species(), and zeeman_on_the_fly().
dstimulated_emissiondF0()
Numeric dstimulated_emissiondF0 (Numeric T, Numeric F0)
Computes frequency derivative of exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
dexp(-hf/kT) / dF0
Definition at line 109 of file linescaling.cc.
References F0.
dstimulated_emissiondT()
Numeric dstimulated_emissiondT (Numeric T, Numeric F0)
Computes temperature derivative of exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
dexp(-hf/kT) / dT
Definition at line 103 of file linescaling.cc.
References F0, and Constant::pow2().
dstimulated_relative_emission_dF0()
Numeric dstimulated_relative_emission_dF0 (const Numeric & gamma, const Numeric & gamma_ref, const Numeric & T, const Numeric & T0)
Computes frequency derivative of (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
[in] T Temperature
[in] T0 Reference temperature
Returns
d[(1 - gamma) / (1 - gamma_ref)] / dF0
Definition at line 131 of file linescaling.cc.
dstimulated_relative_emission_dT()
Numeric dstimulated_relative_emission_dT (const Numeric & gamma, const Numeric & gamma_ref, const Numeric & F0, const Numeric & T)
Computes temperature derivative of (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
[in] F0 Frequency
[in] T Temperature
Returns
d[(1 - gamma) / (1 - gamma_ref)] / dT
Definition at line 120 of file linescaling.cc.
References BOLTZMAN_CONST, and PLANCK_CONST.
single_partition_function()
Numeric single_partition_function (const Numeric & T, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data)
Computes the partition function at one temperature.
Parameters
[in] T Temperature
[in] partition_type Switch for partition type of line
[in] partition_data Partition data of line
Returns
partition function
Definition at line 64 of file linescaling.cc.
References SpeciesAuxData::AT_PARTITIONFUNCTION_COEFF, SpeciesAuxData::AT_PARTITIONFUNCTION_TFIELD, data, SingleCalculatePartitionFctFromCoeff(), and SingleCalculatePartitionFctFromData().
Referenced by lm_hitran_2017::convtp(), Absorption::LineMixing::linemixing_ecs_absorption_rosenkranz_limit(), Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole(), xsec_species(), and zeeman_on_the_fly().
SingleCalculatePartitionFctFromCoeff()
Numeric SingleCalculatePartitionFctFromCoeff (const Numeric & T, ConstVectorView q_grid)
Definition at line 22 of file linescaling.cc.
References ConstVectorView::nelem().
Referenced by single_partition_function().
SingleCalculatePartitionFctFromCoeff_dT()
Numeric SingleCalculatePartitionFctFromCoeff_dT (const Numeric & T, ConstVectorView q_grid)
Definition at line 35 of file linescaling.cc.
References ConstVectorView::nelem().
Referenced by dsingle_partition_function_dT().
SingleCalculatePartitionFctFromData()
Numeric SingleCalculatePartitionFctFromData (const Numeric & T, ConstVectorView t_grid, ConstVectorView q_grid)
Definition at line 48 of file linescaling.cc.
References interp(), and interpweights().
Referenced by single_partition_function().
SingleCalculatePartitionFctFromData_dT()
Numeric SingleCalculatePartitionFctFromData_dT (const Numeric & T, ConstVectorView t_grid, ConstVectorView q_grid)
Definition at line 56 of file linescaling.cc.
References Interpolation::dinterpweights(), and interp().
Referenced by dsingle_partition_function_dT().
stimulated_emission()
Numeric stimulated_emission (Numeric T, Numeric F0)
Computes exp(-hf/kT)
Parameters
[in] T Temperatures
[in] F0 Frequency
Returns
exp(-hf/kT)
Definition at line 97 of file linescaling.cc.
References F0.
Referenced by lm_hitran_2017::compabs(), lm_hitran_2017::convtp(), Absorption::LineMixing::linemixing_ecs_absorption(), Absorption::LineMixing::linemixing_ecs_absorption_with_zeeman_perturbations(), and Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole().
stimulated_relative_emission()
Numeric stimulated_relative_emission (const Numeric & gamma, const Numeric & gamma_ref)
Computes (1 - gamma) / (1 - gamma_ref)
Parameters
[in] gamma Stimulated emission at temperature
[in] gamma_ref Stimulated emission at reference temperature
Returns
(1 - gamma) / (1 - gamma_ref)
Definition at line 115 of file linescaling.cc.