ARTS: m_append.h File Reference
m_append.h File Reference
Implementation of Append.
#include "agenda_class.h"
#include "array.h"
#include "exceptions.h"
#include "matpackI.h"
#include "matpackIII.h"
#include "matpackVI.h"
Functions
template<class T >
void Append (Array< T > &out, const String &, const Array< T > &in, const String &direction, const String &, const String &, const Verbosity &)
template<class T >
void Append (Array< T > &out, const String &, const T &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Workspace &ws, ArrayOfAgenda &out, const String &out_name, const Agenda &in, const String &direction, const String &, const String &, const Verbosity &verbosity)
void Append (Workspace &ws, ArrayOfAgenda &out, const String &out_name, const ArrayOfAgenda &in, const String &direction, const String &, const String &, const Verbosity &verbosity)
void Append (Vector &out, const String &, const Vector &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Matrix &out, const String &, const Matrix &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Matrix &out, const String &, const Vector &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Vector &out, const String &, const Numeric &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Tensor3 &out, const String &, const Matrix &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Tensor3 &out, const String &, const Tensor3 &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Tensor4 &out, const String &, const Tensor3 &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (Tensor4 &out, const String &, const Tensor4 &in, const String &direction, const String &, const String &, const Verbosity &)
void Append (String &out, const String &, const String &in, const String &direction, const String &, const String &, const Verbosity &)
Detailed Description
Implementation of Append.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Append.
Definition in file m_append.h.
Function Documentation
Append() [1/13]
template<class T > void Append (Array< T > & out, const String & , const Array< T > & in, const String & direction, const String & , const String & , const Verbosity &)
Definition at line 43 of file m_append.h.
References Array< base >::nelem().
Referenced by Append_sg_ArrayOfAbsorptionLinesAbsorptionLines_g(), Append_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfAgendaAgenda_g(), Append_sg_ArrayOfAgendaArrayOfAgenda_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Append_sg_ArrayOfArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Append_sg_ArrayOfArrayOfStringArrayOfString_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Append_sg_ArrayOfArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Append_sg_ArrayOfArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Append_sg_ArrayOfCIARecordCIARecord_g(), Append_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfGriddedField1GriddedField1_g(), Append_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfGriddedField2GriddedField2_g(), Append_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfGriddedField3GriddedField3_g(), Append_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Append_sg_ArrayOfGriddedField4GriddedField4_g(), Append_sg_ArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfIndexIndex_g(), Append_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Append_sg_ArrayOfJacobianTargetJacobianTarget_g(), Append_sg_ArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfMatrixMatrix_g(), Append_sg_ArrayOfPpathArrayOfPpath_g(), Append_sg_ArrayOfPpathPpath_g(), Append_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Append_sg_ArrayOfPropagationMatrixPropagationMatrix_g(), Append_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Append_sg_ArrayOfQuantumIdentifierQuantumIdentifier_g(), Append_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Append_sg_ArrayOfRadiationVectorRadiationVector_g(), Append_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Append_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfScatteringMetaDataScatteringMetaData_g(), Append_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfSingleScatteringDataSingleScatteringData_g(), Append_sg_ArrayOfSparseArrayOfSparse_g(), Append_sg_ArrayOfSparseSparse_g(), Append_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Append_sg_ArrayOfStokesVectorStokesVector_g(), Append_sg_ArrayOfStringArrayOfString_g(), Append_sg_ArrayOfStringString_g(), Append_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Append_sg_ArrayOfTelsemAtlasTelsemAtlas_g(), Append_sg_ArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfTensor3Tensor3_g(), Append_sg_ArrayOfTensor4ArrayOfTensor4_g(), Append_sg_ArrayOfTensor4Tensor4_g(), Append_sg_ArrayOfTensor5ArrayOfTensor5_g(), Append_sg_ArrayOfTensor5Tensor5_g(), Append_sg_ArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfTensor6Tensor6_g(), Append_sg_ArrayOfTensor7ArrayOfTensor7_g(), Append_sg_ArrayOfTensor7Tensor7_g(), Append_sg_ArrayOfTimeArrayOfTime_g(), Append_sg_ArrayOfTimeTime_g(), Append_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Append_sg_ArrayOfTransmissionMatrixTransmissionMatrix_g(), Append_sg_ArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfVectorVector_g(), Append_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Append_sg_MatrixMatrix_g(), Append_sg_MatrixVector_g(), Append_sg_StringString_g(), Append_sg_Tensor3Matrix_g(), Append_sg_Tensor3Tensor3_g(), Append_sg_Tensor4Tensor3_g(), Append_sg_Tensor4Tensor4_g(), Append_sg_VectorNumeric_g(), and Append_sg_VectorVector_g().
Append() [2/13]
template<class T > void Append (Array< T > & out, const String & , const T & in, const String & direction, const String & , const String & , const Verbosity &)
Definition at line 71 of file m_append.h.
Append() [3/13]
void Append (Matrix & out, const String & , const Matrix & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 155 of file m_append.h.
References ConstMatrixView::ncols(), ConstMatrixView::nrows(), and Matrix::resize().
Append() [4/13]
void Append (Matrix & out, const String & , const Vector & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 210 of file m_append.h.
References ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Matrix::resize(), and transpose().
Append() [5/13]
void Append (String & out, const String & , const String & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 438 of file m_append.h.
Append() [6/13]
void Append (Tensor3 & out, const String & , const Matrix & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 277 of file m_append.h.
References joker, ConstTensor3View::ncols(), ConstMatrixView::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), ConstMatrixView::nrows(), and Tensor3::resize().
Append() [7/13]
void Append (Tensor3 & out, const String & , const Tensor3 & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 308 of file m_append.h.
References ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and Tensor3::resize().
Append() [8/13]
void Append (Tensor4 & out, const String & , const Tensor3 & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 351 of file m_append.h.
References joker, ConstTensor4View::nbooks(), ConstTensor3View::ncols(), ConstTensor4View::ncols(), ConstTensor3View::npages(), ConstTensor4View::npages(), ConstTensor3View::nrows(), ConstTensor4View::nrows(), and Tensor4::resize().
Append() [9/13]
void Append (Tensor4 & out, const String & , const Tensor4 & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 388 of file m_append.h.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor4::resize().
Append() [10/13]
void Append (Vector & out, const String & , const Numeric & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 254 of file m_append.h.
References ConstVectorView::nelem(), and Vector::resize().
Append() [11/13]
void Append (Vector & out, const String & , const Vector & in, const String & direction, const String & , const String & , const Verbosity &) inline
Definition at line 121 of file m_append.h.
References ConstVectorView::nelem(), and Vector::resize().
Append() [12/13]
void Append (Workspace & ws, ArrayOfAgenda & out, const String & out_name, const Agenda & in, const String & direction, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 85 of file m_append.h.
References Array< base >::nelem(), and ARTS::Var::verbosity().
Append() [13/13]
void Append (Workspace & ws, ArrayOfAgenda & out, const String & out_name, const ArrayOfAgenda & in, const String & direction, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 102 of file m_append.h.
References Array< base >::nelem(), and ARTS::Var::verbosity().