ARTS: m_absorptionlines.cc File Reference
m_absorptionlines.cc File Reference
Contains the absorption namespace.
#include "absorptionlines.h"
#include "auto_md.h"
#include "enums.h"
#include "file.h"
#include "global_data.h"
#include "xml_io_private.h"
#include "m_xml.h"
Functions
std::vector< QuantumNumberType > string2vecqn (const String &qnstr)
Get a list of quantum numbers from a string.
void ReadArrayOfARTSCAT (ArrayOfAbsorptionLines &abs_lines, const String &artscat_file, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadArrayOfARTSCAT.
void ReadARTSCAT (ArrayOfAbsorptionLines &abs_lines, const String &artscat_file, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadARTSCAT.
void ReadSplitARTSCAT (ArrayOfAbsorptionLines &abs_lines, const ArrayOfArrayOfSpeciesTag &abs_species, const String &basename, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const Index &ignore_missing, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadSplitARTSCAT.
ENUMCLASS (HitranType, char, Pre2004, Post2004, Online) void ReadHITRAN(ArrayOfAbsorptionLines &abs_lines
check_enum_error (hitran_version, "Cannot understand hitran_type: ", hitran_type)
open_input_file (is, hitran_file)
std::vector< Absorption::SingleLineExternal > v (0)
while (go_on)
for (auto &x:v) x.line.Zeeman()
abs_lines resize (0)
abs_lines reserve (x.size())
while (x.size())
abs_linesSetNormalization (abs_lines, normalization_option, verbosity)
abs_linesSetMirroring (abs_lines, mirroring_option, verbosity)
abs_linesSetPopulation (abs_lines, population_option, verbosity)
abs_linesSetLineShapeType (abs_lines, lineshapetype_option, verbosity)
abs_linesSetCutoff (abs_lines, cutoff_option, cutoff_value, verbosity)
abs_linesSetLinemixingLimit (abs_lines, linemixinglimit_value, verbosity)
void ReadLBLRTM (ArrayOfAbsorptionLines &abs_lines, const String &lblrtm_file, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadLBLRTM.
void ReadMytran2 (ArrayOfAbsorptionLines &abs_lines, const String &mytran2_file, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadMytran2.
void ReadJPL (ArrayOfAbsorptionLines &abs_lines, const String &jpl_file, const Numeric &fmin, const Numeric &fmax, const String &globalquantumnumbers, const String &localquantumnumbers, const String &normalization_option, const String &mirroring_option, const String &population_option, const String &lineshapetype_option, const String &cutoff_option, const Numeric &cutoff_value, const Numeric &linemixinglimit_value, const Verbosity &verbosity)
WORKSPACE METHOD: ReadJPL.
void abs_linesWriteSplitXML (const String &output_format, const ArrayOfAbsorptionLines &abs_lines, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesWriteSplitXML.
void abs_linesWriteSpeciesSplitXML (const String &output_format, const ArrayOfAbsorptionLines &abs_lines, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesWriteSpeciesSplitXML.
void abs_lines_per_speciesWriteSplitXML (const String &output_format, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesWriteSplitXML.
void abs_lines_per_speciesWriteSpeciesSplitXML (const String &output_format, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesWriteSpeciesSplitXML.
void abs_lines_per_speciesReadSplitCatalog (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadSplitCatalog.
void abs_linesReadSpeciesSplitCatalog (ArrayOfAbsorptionLines &abs_lines, const String &basename, const Index &robust, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadSpeciesSplitCatalog.
void abs_lines_per_speciesReadSpeciesSplitCatalog (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &basename, const Index &robust, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadSpeciesSplitCatalog.
void abs_linesSetQuantumNumberForMatch (ArrayOfAbsorptionLines &abs_lines, const String &qn, const Rational &x, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetQuantumNumberForMatch.
void abs_lines_per_speciesSetQuantumNumberForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &qn, const Rational &x, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetQuantumNumberForMatch.
void abs_linesTruncateGlobalQuantumNumbers (ArrayOfAbsorptionLines &abs_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesTruncateGlobalQuantumNumbers.
void abs_linesRemoveUnusedLocalQuantumNumbers (ArrayOfAbsorptionLines &abs_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesRemoveUnusedLocalQuantumNumbers.
void abs_linesReplaceWithLines (ArrayOfAbsorptionLines &abs_lines, const ArrayOfAbsorptionLines &replacing_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesReplaceWithLines.
void abs_linesAppendWithLines (ArrayOfAbsorptionLines &abs_lines, const ArrayOfAbsorptionLines &appending_lines, const Index &safe, const Verbosity &)
WORKSPACE METHOD: abs_linesAppendWithLines.
void abs_linesDeleteBadF0 (ArrayOfAbsorptionLines &abs_lines, const Numeric &f0, const Index &lower, const Verbosity &)
WORKSPACE METHOD: abs_linesDeleteBadF0.
void abs_linesDeleteWithLines (ArrayOfAbsorptionLines &abs_lines, const ArrayOfAbsorptionLines &deleting_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesDeleteWithLines.
void abs_linesDeleteLinesWithUndefinedLocalQuanta (ArrayOfAbsorptionLines &abs_lines, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesDeleteLinesWithUndefinedLocalQuanta.
void abs_linesDeleteLinesWithBadOrHighChangingJs (ArrayOfAbsorptionLines &abs_lines, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesDeleteLinesWithBadOrHighChangingJs.
void abs_linesDeleteLinesWithQuantumNumberAbove (ArrayOfAbsorptionLines &abs_lines, const String &qn_id, const Index &qn_val, const Verbosity &)
WORKSPACE METHOD: abs_linesDeleteLinesWithQuantumNumberAbove.
void abs_linesSetEmptyBroadeningParametersToEmpty (ArrayOfAbsorptionLines &abs_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesSetEmptyBroadeningParametersToEmpty.
void abs_linesKeepBands (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &qid, const Index &ignore_spec, const Index &ignore_isot, const Verbosity &)
WORKSPACE METHOD: abs_linesKeepBands.
void abs_linesCleanupEmpty (ArrayOfAbsorptionLines &abs_lines, const Verbosity &)
WORKSPACE METHOD: abs_linesCleanupEmpty.
void abs_linesSetCutoff (ArrayOfAbsorptionLines &abs_lines, const String &type, const Numeric &x, const Verbosity &)
WORKSPACE METHOD: abs_linesSetCutoff.
void abs_lines_per_speciesSetCutoff (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Numeric &x, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoff.
void abs_linesSetCutoffForMatch (ArrayOfAbsorptionLines &abs_lines, const String &type, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetCutoffForMatch.
void abs_lines_per_speciesSetCutoffForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoffForMatch.
void abs_lines_per_speciesSetCutoffForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &type, const Numeric &x, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoffForSpecies.
void abs_linesSetMirroring (ArrayOfAbsorptionLines &abs_lines, const String &type, const Verbosity &)
WORKSPACE METHOD: abs_linesSetMirroring.
void abs_lines_per_speciesSetMirroring (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroring.
void abs_linesSetMirroringForMatch (ArrayOfAbsorptionLines &abs_lines, const String &type, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetMirroringForMatch.
void abs_lines_per_speciesSetMirroringForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroringForMatch.
void abs_lines_per_speciesSetMirroringForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &type, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroringForSpecies.
void abs_linesSetPopulation (ArrayOfAbsorptionLines &abs_lines, const String &type, const Verbosity &)
WORKSPACE METHOD: abs_linesSetPopulation.
void abs_lines_per_speciesSetPopulation (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulation.
void abs_linesSetPopulationForMatch (ArrayOfAbsorptionLines &abs_lines, const String &type, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetPopulationForMatch.
void abs_lines_per_speciesSetPopulationForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulationForMatch.
void abs_lines_per_speciesSetPopulationForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &type, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulationForSpecies.
void abs_linesSetNormalization (ArrayOfAbsorptionLines &abs_lines, const String &type, const Verbosity &)
WORKSPACE METHOD: abs_linesSetNormalization.
void abs_lines_per_speciesSetNormalization (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalization.
void abs_linesSetNormalizationForMatch (ArrayOfAbsorptionLines &abs_lines, const String &type, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetNormalizationForMatch.
void abs_lines_per_speciesSetNormalizationForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalizationForMatch.
void abs_lines_per_speciesSetNormalizationForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &type, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalizationForSpecies.
void abs_linesSetLineShapeType (ArrayOfAbsorptionLines &abs_lines, const String &type, const Verbosity &)
WORKSPACE METHOD: abs_linesSetLineShapeType.
void abs_lines_per_speciesSetLineShapeType (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeType.
void abs_linesSetLineShapeTypeForMatch (ArrayOfAbsorptionLines &abs_lines, const String &type, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetLineShapeTypeForMatch.
void abs_lines_per_speciesSetLineShapeTypeForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const String &type, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeTypeForMatch.
void abs_lines_per_speciesSetLineShapeTypeForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &type, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeTypeForSpecies.
void abs_linesSetLinemixingLimit (ArrayOfAbsorptionLines &abs_lines, const Numeric &x, const Verbosity &)
WORKSPACE METHOD: abs_linesSetLinemixingLimit.
void abs_lines_per_speciesSetLinemixingLimit (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Numeric &x, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimit.
void abs_linesSetLinemixingLimitForMatch (ArrayOfAbsorptionLines &abs_lines, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetLinemixingLimitForMatch.
void abs_lines_per_speciesSetLinemixingLimitForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimitForMatch.
void abs_lines_per_speciesSetLinemixingLimitForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const Numeric &x, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimitForSpecies.
void abs_linesSetT0 (ArrayOfAbsorptionLines &abs_lines, const Numeric &x, const Verbosity &)
WORKSPACE METHOD: abs_linesSetT0.
void abs_lines_per_speciesSetT0 (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Numeric &x, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetT0.
void abs_linesSetT0ForMatch (ArrayOfAbsorptionLines &abs_lines, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &)
WORKSPACE METHOD: abs_linesSetT0ForMatch.
void abs_lines_per_speciesSetT0ForMatch (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Numeric &x, const QuantumIdentifier &QI, const Verbosity &v)
WORKSPACE METHOD: abs_lines_per_speciesSetT0ForMatch.
void abs_lines_per_speciesSetT0ForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const Numeric &x, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetT0ForSpecies.
void abs_linesChangeBaseParameterForMatchingLines (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &relative, const Index &loose_matching, const Verbosity &)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLines.
void abs_lines_per_speciesChangeBaseParameterForMatchingLines (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &relative, const Index &loose_matching, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLines.
void abs_lines_per_speciesChangeBaseParameterForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &relative, const Index &loose_matching, const String &species_tag, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForSpecies.
void abs_linesSetBaseParameterForMatchingLines (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &x, const Index &loose_matching, const Verbosity &)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLines.
void abs_lines_per_speciesSetBaseParameterForMatchingLines (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &loose_matching, const Verbosity &verbosity)
void abs_lines_per_speciesSetBaseParameterForSpecies (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &loose_matching, const String &species_tag, const Verbosity &verbosity)
void abs_linesSetLineShapeModelParametersForMatchingLines (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &QI, const String &parameter, const String &species, const String &temperaturemodel, const Vector &new_values, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesSetLineShapeModelParametersForMatchingLines.
void abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const QuantumIdentifier &QI, const String &parameter, const String &species, const String &temperaturemodel, const Vector &new_values, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines.
void abs_linesChangeBaseParameterForMatchingLevel (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &relative, const Verbosity &)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLevel.
void abs_lines_per_speciesChangeBaseParameterForMatchingLevel (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Index &relative, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLevel.
void abs_linesChangeBaseParameterForMatchingLevels (ArrayOfAbsorptionLines &abs_lines, const ArrayOfQuantumIdentifier &QID, const String &parameter_name, const Vector &change, const Index &relative, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLevels.
void abs_lines_per_speciesChangeBaseParameterForMatchingLevels (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfQuantumIdentifier &QID, const String &parameter_name, const Vector &change, const Index &relative, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLevels.
void abs_linesSetBaseParameterForMatchingLevel (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &x, const Verbosity &)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLevel.
void abs_lines_per_speciesSetBaseParameterForMatchingLevel (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const QuantumIdentifier &QI, const String &parameter_name, const Numeric &change, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetBaseParameterForMatchingLevel.
void abs_linesSetBaseParameterForMatchingLevels (ArrayOfAbsorptionLines &abs_lines, const ArrayOfQuantumIdentifier &QID, const String &parameter_name, const Vector &change, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLevels.
void abs_lines_per_speciesSetBaseParameterForMatchingLevels (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfQuantumIdentifier &QID, const String &parameter_name, const Vector &change, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetBaseParameterForMatchingLevels.
void nlteSetByQuantumIdentifiers (Index &nlte_do, ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const EnergyLevelMap &nlte_field, const Verbosity &)
WORKSPACE METHOD: nlteSetByQuantumIdentifiers.
void abs_lines_per_speciesSetEmpty (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesSetEmpty.
void abs_linesCompact (ArrayOfAbsorptionLines &abs_lines, const Vector &f_grid, const Verbosity &)
WORKSPACE METHOD: abs_linesCompact.
void abs_lines_per_speciesCompact (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Vector &f_grid, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesCompact.
void abs_linesRemoveBand (ArrayOfAbsorptionLines &abs_lines, const QuantumIdentifier &qid, const Verbosity &)
WORKSPACE METHOD: abs_linesRemoveBand.
void abs_linesSetZeemanCoefficients (ArrayOfAbsorptionLines &abs_lines, const ArrayOfQuantumIdentifier &qid, const Vector &gs, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesSetZeemanCoefficients.
void abs_lines_per_speciesSetZeemanCoefficients (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfQuantumIdentifier &qid, const Vector &gs, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetZeemanCoefficients.
template<class T >
std::vector< T > linspace (T s, T e, typename std::vector< T >::size_type count) noexcept
void f_gridFromAbsorptionLines (Vector &f_grid, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Numeric &delta_f_low, const Numeric &delta_f_upp, const Index &num_freqs, const Verbosity &)
WORKSPACE METHOD: f_gridFromAbsorptionLines.
void abs_linesPrintDefinedQuantumNumbers (const ArrayOfAbsorptionLines &abs_lines, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesPrintDefinedQuantumNumbers.
Variables
const String & hitran_file
const String const Numeric & fmin
const String const Numeric const Numeric & fmax
const String const Numeric const Numeric const String & globalquantumnumbers
const String const Numeric const Numeric const String const String & localquantumnumbers
const String const Numeric const Numeric const String const String const String & hitran_type
const String const Numeric const Numeric const String const String const String const String & normalization_option
const String const Numeric const Numeric const String const String const String const String const String & mirroring_option
const String const Numeric const Numeric const String const String const String const String const String const String & population_option
const String const Numeric const Numeric const String const String const String const String const String const String const String & lineshapetype_option
const String const Numeric const Numeric const String const String const String const String const String const String const String const String & cutoff_option
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric & cutoff_value
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric const Numeric & linemixinglimit_value
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric const Numeric const Verbosity & verbosity
const std::vector< QuantumNumberType > local_nums = string2vecqn(localquantumnumbers)
const HitranType hitran_version = toHitranType(hitran_type)
ifstream is
bool go_on = true
auto x = Absorption::split_list_of_external_lines(v, local_nums, global_nums)
Detailed Description
Contains the absorption namespace.
Author
Richard Larsson
Date
2019-09-11
Contains the user interaction with absorption lines
Definition in file m_absorptionlines.cc.
Function Documentation
abs_lines_per_speciesChangeBaseParameterForMatchingLevel()
void abs_lines_per_speciesChangeBaseParameterForMatchingLevel (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & relative, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLevel.
See abs_linesChangeBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
Definition at line 2134 of file m_absorptionlines.cc.
References abs_linesChangeBaseParameterForMatchingLevel(), and verbosity.
Referenced by abs_lines_per_speciesChangeBaseParameterForMatchingLevel_g().
abs_lines_per_speciesChangeBaseParameterForMatchingLevels()
void abs_lines_per_speciesChangeBaseParameterForMatchingLevels (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfQuantumIdentifier & QI, const String & parameter_name, const Vector & change, const Index & relative, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLevels.
See abs_linesChangeBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
Definition at line 2161 of file m_absorptionlines.cc.
References abs_linesChangeBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_lines_per_speciesChangeBaseParameterForMatchingLevels_g().
abs_lines_per_speciesChangeBaseParameterForMatchingLines()
void abs_lines_per_speciesChangeBaseParameterForMatchingLines (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & relative, const Index & loose_matching, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForMatchingLines.
See abs_linesChangeBaseParameterForMatchingLines
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
[in] loose_matching Generic Input (Default: "0")
Definition at line 1854 of file m_absorptionlines.cc.
References abs_linesChangeBaseParameterForMatchingLines(), and verbosity.
Referenced by abs_lines_per_speciesChangeBaseParameterForMatchingLines_g().
abs_lines_per_speciesChangeBaseParameterForSpecies()
void abs_lines_per_speciesChangeBaseParameterForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & relative, const Index & loose_matching, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesChangeBaseParameterForSpecies.
See abs_linesChangeBaseParameterForMatchingLines but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
[in] loose_matching Generic Input (Default: "0")
[in] species_tag Generic Input
Definition at line 1867 of file m_absorptionlines.cc.
References abs_linesChangeBaseParameterForMatchingLines(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
Referenced by abs_lines_per_speciesChangeBaseParameterForSpecies_g().
abs_lines_per_speciesCompact()
void abs_lines_per_speciesCompact (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Vector & f_grid, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesCompact.
See abs_linesCompact
Author
Stefan Buehler
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] f_grid WS Input
Definition at line 2346 of file m_absorptionlines.cc.
References abs_linesCompact(), and verbosity.
Referenced by abs_lines_per_speciesCompact_g().
abs_lines_per_speciesReadSpeciesSplitCatalog()
void abs_lines_per_speciesReadSpeciesSplitCatalog (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & basename, const Index & robust, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadSpeciesSplitCatalog.
See abs_lines_per_speciesReadSplitCatalog but expects a single file per species of ArrayOfAbsorptionLines
Author
Richard Larsson
Parameters
[out] abs_lines_per_species WS Output
[in] abs_species WS Input
[in] basename Generic Input
[in] robust Generic Input (Default: "0")
Definition at line 885 of file m_absorptionlines.cc.
References CREATE_OUT3, global_data::species_data, SpeciesTag::TYPE_PLAIN, and SpeciesTag::TYPE_ZEEMAN.
Referenced by abs_lines_per_speciesReadSpeciesSplitCatalog_g().
abs_lines_per_speciesReadSplitCatalog()
void abs_lines_per_speciesReadSplitCatalog (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadSplitCatalog.
Reads abs_lines_per_species split by abs_linesWriteSplitXML* or abs_lines_per_speciesWriteSplitXML
Note that this will sort the isotopologue
Author
Richard Larsson
Parameters
[out] abs_lines_per_species WS Output
[in] abs_species WS Input
[in] basename Generic Input
Definition at line 800 of file m_absorptionlines.cc.
References global_data::species_data, SpeciesTag::TYPE_PLAIN, and SpeciesTag::TYPE_ZEEMAN.
Referenced by abs_lines_per_speciesReadSplitCatalog_g().
abs_lines_per_speciesSetBaseParameterForMatchingLevel()
void abs_lines_per_speciesSetBaseParameterForMatchingLevel (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetBaseParameterForMatchingLevel.
See abs_linesSetBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
Definition at line 2231 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLevel(), and verbosity.
Referenced by abs_lines_per_speciesSetBaseParameterForMatchingLevel_g().
abs_lines_per_speciesSetBaseParameterForMatchingLevels()
void abs_lines_per_speciesSetBaseParameterForMatchingLevels (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfQuantumIdentifier & QI, const String & parameter_name, const Vector & change, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetBaseParameterForMatchingLevels.
See abs_linesSetBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
Definition at line 2256 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetBaseParameterForMatchingLevels_g().
abs_lines_per_speciesSetBaseParameterForMatchingLines()
void abs_lines_per_speciesSetBaseParameterForMatchingLines (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & loose_matching, const Verbosity & verbosity)
Definition at line 1960 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLines(), and verbosity.
abs_lines_per_speciesSetBaseParameterForSpecies()
void abs_lines_per_speciesSetBaseParameterForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & loose_matching, const String & species_tag, const Verbosity & verbosity)
Definition at line 1972 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLines(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
abs_lines_per_speciesSetCutoff()
void abs_lines_per_speciesSetCutoff (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoff.
See abs_linesSetCutoff
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] value Generic Input
Definition at line 1310 of file m_absorptionlines.cc.
References abs_linesSetCutoff(), v(), and x.
Referenced by abs_lines_per_speciesSetCutoff_g().
abs_lines_per_speciesSetCutoffForMatch()
void abs_lines_per_speciesSetCutoffForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoffForMatch.
See abs_linesSetCutoff for more options.
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] value Generic Input
[in] ID Generic Input
Definition at line 1338 of file m_absorptionlines.cc.
References abs_linesSetCutoffForMatch(), verbosity, and x.
Referenced by abs_lines_per_speciesSetCutoffForMatch_g().
abs_lines_per_speciesSetCutoffForSpecies()
void abs_lines_per_speciesSetCutoffForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & option, const Numeric & value, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetCutoffForSpecies.
See abs_linesSetCutoff but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] option Generic Input
[in] value Generic Input
[in] species_tag Generic Input
Definition at line 1351 of file m_absorptionlines.cc.
References abs_linesSetCutoff(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), verbosity, and x.
Referenced by abs_lines_per_speciesSetCutoffForSpecies_g().
abs_lines_per_speciesSetEmpty()
void abs_lines_per_speciesSetEmpty (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetEmpty.
Empties abs_lines_per_species at the correct size.
Author
Richard Larsson
Parameters
[out] abs_lines_per_species WS Output
[in] abs_species WS Input
Definition at line 2318 of file m_absorptionlines.cc.
References Array< base >::nelem().
Referenced by abs_lines_per_speciesSetEmpty_g().
abs_lines_per_speciesSetLinemixingLimit()
void abs_lines_per_speciesSetLinemixingLimit (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimit.
See abs_linesSetLinemixingLimit
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] value Generic Input
Definition at line 1645 of file m_absorptionlines.cc.
References abs_linesSetLinemixingLimit(), v(), and x.
Referenced by abs_lines_per_speciesSetLinemixingLimit_g().
abs_lines_per_speciesSetLinemixingLimitForMatch()
void abs_lines_per_speciesSetLinemixingLimitForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimitForMatch.
See abs_linesSetLinemixingLimit for values
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] value Generic Input
[in] ID Generic Input
Definition at line 1665 of file m_absorptionlines.cc.
References abs_linesSetLinemixingLimitForMatch(), v(), and x.
Referenced by abs_lines_per_speciesSetLinemixingLimitForMatch_g().
abs_lines_per_speciesSetLinemixingLimitForSpecies()
void abs_lines_per_speciesSetLinemixingLimitForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Numeric & value, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLinemixingLimitForSpecies.
See abs_linesSetLinemixingLimit but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] value Generic Input
[in] species_tag Generic Input
Definition at line 1675 of file m_absorptionlines.cc.
References abs_linesSetLinemixingLimit(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), verbosity, and x.
Referenced by abs_lines_per_speciesSetLinemixingLimitForSpecies_g().
abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines()
void abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const QuantumIdentifier & QI, const String & parameter, const String & species, const String & temperaturemodel, const Vector & new_values, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines.
See abs_linesSetLineShapeModelParametersForMatchingLines
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] QI Generic Input
[in] parameter Generic Input
[in] species Generic Input
[in] temperaturemodel Generic Input
[in] new_values Generic Input
Definition at line 2048 of file m_absorptionlines.cc.
References abs_linesSetLineShapeModelParametersForMatchingLines(), and verbosity.
Referenced by abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines_g().
abs_lines_per_speciesSetLineShapeType()
void abs_lines_per_speciesSetLineShapeType (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeType.
See abs_linesSetLineShapeType
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
Definition at line 1582 of file m_absorptionlines.cc.
References abs_linesSetLineShapeType(), and v().
Referenced by abs_lines_per_speciesSetLineShapeType_g().
abs_lines_per_speciesSetLineShapeTypeForMatch()
void abs_lines_per_speciesSetLineShapeTypeForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeTypeForMatch.
See abs_linesSetLineShapeType for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1604 of file m_absorptionlines.cc.
References abs_linesSetLineShapeTypeForMatch(), and v().
Referenced by abs_lines_per_speciesSetLineShapeTypeForMatch_g().
abs_lines_per_speciesSetLineShapeTypeForSpecies()
void abs_lines_per_speciesSetLineShapeTypeForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & option, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetLineShapeTypeForSpecies.
See abs_linesSetLineShapeType but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] option Generic Input
[in] species_tag Generic Input
Definition at line 1614 of file m_absorptionlines.cc.
References abs_linesSetLineShapeType(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetLineShapeTypeForSpecies_g().
abs_lines_per_speciesSetMirroring()
void abs_lines_per_speciesSetMirroring (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroring.
See abs_linesSetMirroring
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
Definition at line 1385 of file m_absorptionlines.cc.
References abs_linesSetMirroring(), and v().
Referenced by abs_lines_per_speciesSetMirroring_g().
abs_lines_per_speciesSetMirroringForMatch()
void abs_lines_per_speciesSetMirroringForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroringForMatch.
See abs_linesSetMirroring for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1409 of file m_absorptionlines.cc.
References abs_linesSetMirroringForMatch(), and v().
Referenced by abs_lines_per_speciesSetMirroringForMatch_g().
abs_lines_per_speciesSetMirroringForSpecies()
void abs_lines_per_speciesSetMirroringForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & option, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetMirroringForSpecies.
See abs_linesSetMirroring but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] option Generic Input
[in] species_tag Generic Input
Definition at line 1419 of file m_absorptionlines.cc.
References abs_linesSetMirroring(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetMirroringForSpecies_g().
abs_lines_per_speciesSetNormalization()
void abs_lines_per_speciesSetNormalization (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalization.
See abs_linesSetNormalization
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
Definition at line 1517 of file m_absorptionlines.cc.
References abs_linesSetNormalization(), and v().
Referenced by abs_lines_per_speciesSetNormalization_g().
abs_lines_per_speciesSetNormalizationForMatch()
void abs_lines_per_speciesSetNormalizationForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalizationForMatch.
See abs_linesSetNormalization for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1539 of file m_absorptionlines.cc.
References abs_linesSetNormalizationForMatch(), and v().
Referenced by abs_lines_per_speciesSetNormalizationForMatch_g().
abs_lines_per_speciesSetNormalizationForSpecies()
void abs_lines_per_speciesSetNormalizationForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & option, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetNormalizationForSpecies.
See abs_linesSetNormalization but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] option Generic Input
[in] species_tag Generic Input
Definition at line 1549 of file m_absorptionlines.cc.
References abs_linesSetNormalization(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetNormalizationForSpecies_g().
abs_lines_per_speciesSetPopulation()
void abs_lines_per_speciesSetPopulation (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulation.
See abs_linesSetPopulation
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
Definition at line 1452 of file m_absorptionlines.cc.
References abs_linesSetPopulation(), and v().
Referenced by abs_lines_per_speciesSetPopulation_g().
abs_lines_per_speciesSetPopulationForMatch()
void abs_lines_per_speciesSetPopulationForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulationForMatch.
See abs_linesSetPopulation for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1474 of file m_absorptionlines.cc.
References abs_linesSetPopulationForMatch(), and v().
Referenced by abs_lines_per_speciesSetPopulationForMatch_g().
abs_lines_per_speciesSetPopulationForSpecies()
void abs_lines_per_speciesSetPopulationForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & option, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetPopulationForSpecies.
See abs_linesSetPopulation but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] option Generic Input
[in] species_tag Generic Input
Definition at line 1484 of file m_absorptionlines.cc.
References abs_linesSetPopulation(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetPopulationForSpecies_g().
abs_lines_per_speciesSetQuantumNumberForMatch()
void abs_lines_per_speciesSetQuantumNumberForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & quantum_number, const Rational & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetQuantumNumberForMatch.
See abs_linesSetQuantumNumberForMatch
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] quantum_number Generic Input
[in] value Generic Input
[in] ID Generic Input
Definition at line 963 of file m_absorptionlines.cc.
References abs_linesSetQuantumNumberForMatch(), v(), and x.
Referenced by abs_lines_per_speciesSetQuantumNumberForMatch_g().
abs_lines_per_speciesSetT0()
void abs_lines_per_speciesSetT0 (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetT0.
See abs_linesSetT0
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] value Generic Input
Definition at line 1706 of file m_absorptionlines.cc.
References abs_linesSetT0(), v(), and x.
Referenced by abs_lines_per_speciesSetT0_g().
abs_lines_per_speciesSetT0ForMatch()
void abs_lines_per_speciesSetT0ForMatch (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetT0ForMatch.
Sets reference temperature
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] value Generic Input
[in] ID Generic Input
Definition at line 1726 of file m_absorptionlines.cc.
References abs_linesSetT0ForMatch(), v(), and x.
Referenced by abs_lines_per_speciesSetT0ForMatch_g().
abs_lines_per_speciesSetT0ForSpecies()
void abs_lines_per_speciesSetT0ForSpecies (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Numeric & value, const String & species_tag, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetT0ForSpecies.
See abs_linesSetT0 but for single species
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] value Generic Input
[in] species_tag Generic Input
Definition at line 1736 of file m_absorptionlines.cc.
References abs_linesSetT0(), abs_speciesSet(), Zeeman::end(), Array< base >::nelem(), verbosity, and x.
Referenced by abs_lines_per_speciesSetT0ForSpecies_g().
abs_lines_per_speciesSetZeemanCoefficients()
void abs_lines_per_speciesSetZeemanCoefficients (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfQuantumIdentifier & qid, const Vector & gs, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetZeemanCoefficients.
See abs_linesSetZeemanCoefficients
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] qid Generic Input
[in] gs Generic Input
Definition at line 2382 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_lines_per_speciesSetZeemanCoefficients_g().
abs_lines_per_speciesWriteSpeciesSplitXML()
void abs_lines_per_speciesWriteSpeciesSplitXML (const String & output_file_format, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesWriteSpeciesSplitXML.
See abs_linesWriteSpeciesSplitXML
In addition, the structure of the files generated will not care about generating identifiers for the order in abs_species
Author
Richard Larsson
Parameters
[in] output_file_format WS Input
[in] abs_lines_per_species WS Input
[in] basename Generic Input
Definition at line 782 of file m_absorptionlines.cc.
References abs_linesWriteSpeciesSplitXML(), and verbosity.
Referenced by abs_lines_per_speciesWriteSpeciesSplitXML_g().
abs_lines_per_speciesWriteSplitXML()
void abs_lines_per_speciesWriteSplitXML (const String & output_file_format, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesWriteSplitXML.
See abs_linesWriteSplitXML
In addition, the structure of the files generated will not care about generating identifiers for the order in abs_species
Author
Richard Larsson
Parameters
[in] output_file_format WS Input
[in] abs_lines_per_species WS Input
[in] basename Generic Input
Definition at line 758 of file m_absorptionlines.cc.
References verbosity, and WriteXML().
Referenced by abs_lines_per_speciesWriteSplitXML_g().
abs_linesAppendWithLines()
void abs_linesAppendWithLines (ArrayOfAbsorptionLines & abs_lines, const ArrayOfAbsorptionLines & appending_lines, const Index & safe, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesAppendWithLines.
Appends all lines in abs_lines that match with lines in replacement_lines if safe. If not safe, appends all lines.
No appended line is allowed to match any line in abs_lines if safe
Conditional behavior if safe: If the AbosorptionLines to be appended match no AbsorptionLines in abs_lines, then the entire AbsorptionLines is appended. Otherwise, only a single AbsorptionLines can be matched and is not allowed to have any internal matches
Note that lines are identified by their AbsorptionLines tags and by their quantum numbers in safe mode.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] appending_lines Generic Input
[in] safe Generic Input (Default: "1")
Definition at line 1050 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF.
Referenced by abs_linesAppendWithLines_g().
abs_linesChangeBaseParameterForMatchingLevel()
void abs_linesChangeBaseParameterForMatchingLevel (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & relative, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLevel.
Change parameter of all levels in abs_lines that match with QuantumIdentifier. Only works for these parameters: parameter_name = "Statistical Weight" parameter_name = "Zeeman Coefficient"
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
Definition at line 2067 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, QuantumIdentifier::ENERGY_LEVEL, my_basic_string< charT >::nelem(), and QuantumIdentifier::Type().
Referenced by abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), abs_linesChangeBaseParameterForMatchingLevel_g(), and abs_linesChangeBaseParameterForMatchingLevels().
abs_linesChangeBaseParameterForMatchingLevels()
void abs_linesChangeBaseParameterForMatchingLevels (ArrayOfAbsorptionLines & abs_lines, const ArrayOfQuantumIdentifier & QI, const String & parameter_name, const Vector & change, const Index & relative, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLevels.
See abs_linesChangeBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
Definition at line 2146 of file m_absorptionlines.cc.
References abs_linesChangeBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_linesChangeBaseParameterForMatchingLevels_g().
abs_linesChangeBaseParameterForMatchingLines()
void abs_linesChangeBaseParameterForMatchingLines (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & relative, const Index & loose_matching, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesChangeBaseParameterForMatchingLines.
Change parameter of all lines in abs_lines that match with QuantumIdentifier. Only works for these parameters: parameter_name = "Central Frequency" parameter_name = "Line Strength" parameter_name = "Lower State Energy" parameter_name = "Einstein Coefficient" parameter_name = "Lower Statistical Weight" parameter_name = "Upper Statistical Weight" parameter_name = "Lower Zeeman Coefficient" parameter_name = "Upper Zeeman Coefficient"
Note that loose_matching:=0 means only identical quantum identifiers are accepted, otherwise the numbers in QI must just be contained in the line identifier
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] relative Generic Input (Default: "0")
[in] loose_matching Generic Input (Default: "0")
Definition at line 1758 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, and my_basic_string< charT >::nelem().
Referenced by abs_lines_per_speciesChangeBaseParameterForMatchingLines(), abs_lines_per_speciesChangeBaseParameterForSpecies(), and abs_linesChangeBaseParameterForMatchingLines_g().
abs_linesCleanupEmpty()
void abs_linesCleanupEmpty (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesCleanupEmpty.
Removes empty bands from abs_lines.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 1278 of file m_absorptionlines.cc.
References Array< base >::nelem().
Referenced by abs_linesCleanupEmpty_g().
abs_linesCompact()
void abs_linesCompact (ArrayOfAbsorptionLines & abs_lines, const Vector & f_grid, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesCompact.
Removes lines that are unimportant because of their cutoff frequency range
Author
Stefan Buehler
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] f_grid WS Input
Definition at line 2325 of file m_absorptionlines.cc.
References fmax, fmin, max, and min.
Referenced by abs_lines_per_speciesCompact(), and abs_linesCompact_g().
abs_linesDeleteBadF0()
void abs_linesDeleteBadF0 (ArrayOfAbsorptionLines & abs_lines, const Numeric & f0, const Index & lower, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesDeleteBadF0.
Deletes all lines in abs_lines that have bad central frequencies
If lower evaluates as true, deletes all lines with a frequency below f0. Otherwise deletes all lines with a frequency above f0.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] f0 Generic Input
[in] lower Generic Input (Default: "1")
Definition at line 1094 of file m_absorptionlines.cc.
Referenced by abs_linesDeleteBadF0_g().
abs_linesDeleteLinesWithBadOrHighChangingJs()
void abs_linesDeleteLinesWithBadOrHighChangingJs (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesDeleteLinesWithBadOrHighChangingJs.
Deletes all lines in abs_lines that have undefined Js or Js that change more than 1 between energy levels
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 1178 of file m_absorptionlines.cc.
References abs, and CREATE_OUT2.
Referenced by abs_linesDeleteLinesWithBadOrHighChangingJs_g().
abs_linesDeleteLinesWithQuantumNumberAbove()
void abs_linesDeleteLinesWithQuantumNumberAbove (ArrayOfAbsorptionLines & abs_lines, const String & quantumnumber, const Index & quantumnumber_value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesDeleteLinesWithQuantumNumberAbove.
Deletes all lines in abs_lines that have too large quantum number
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] quantumnumber Generic Input
[in] quantumnumber_value Generic Input
Definition at line 1206 of file m_absorptionlines.cc.
Referenced by abs_linesDeleteLinesWithQuantumNumberAbove_g().
abs_linesDeleteLinesWithUndefinedLocalQuanta()
void abs_linesDeleteLinesWithUndefinedLocalQuanta (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesDeleteLinesWithUndefinedLocalQuanta.
Deletes all lines in abs_lines that have undefined local quanta
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 1148 of file m_absorptionlines.cc.
References CREATE_OUT2, and x.
Referenced by abs_linesDeleteLinesWithUndefinedLocalQuanta_g().
abs_linesDeleteWithLines()
void abs_linesDeleteWithLines (ArrayOfAbsorptionLines & abs_lines, const ArrayOfAbsorptionLines & deleting_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesDeleteWithLines.
Deletes all lines in abs_lines that match with lines in replacement_lines.
If a deleted line has no match, then nothing happens.
Note that lines are identified by their AbsorptionLines tags and by their quantum numbers. There is no need to have all values correct.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] deleting_lines Generic Input
Definition at line 1115 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF.
Referenced by abs_linesDeleteWithLines_g().
abs_linesKeepBands()
void abs_linesKeepBands (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & qid, const Index & ignore_spec, const Index & ignore_isot, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesKeepBands.
Keep only qid-matches in abs_lines
The ignore values will ignore isotopologue and/or species. The latter means the isotopologue has to be ignores.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] qid Generic Input
[in] ignore_spec Generic Input (Default: "1")
[in] ignore_isot Generic Input (Default: "1")
Definition at line 1250 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, QuantumIdentifier::ENERGY_LEVEL, QuantumIdentifier::EnergyLevelQuantumNumbers(), QuantumIdentifier::Isotopologue(), QuantumIdentifier::LowerQuantumNumbers(), QuantumIdentifier::SetTransition(), QuantumIdentifier::Species(), QuantumIdentifier::Type(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by abs_linesKeepBands_g().
abs_linesPrintDefinedQuantumNumbers()
void abs_linesPrintDefinedQuantumNumbers (const ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesPrintDefinedQuantumNumbers.
Print the count of defined quantum numbers in the catalog
Author
Richard Larsson
Parameters
[in] abs_lines WS Input
Definition at line 2464 of file m_absorptionlines.cc.
References CREATE_OUT0.
Referenced by abs_linesPrintDefinedQuantumNumbers_g().
abs_linesReadSpeciesSplitCatalog()
void abs_linesReadSpeciesSplitCatalog (ArrayOfAbsorptionLines & abs_lines, const String & basename, const Index & robust, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadSpeciesSplitCatalog.
Reads a catalog of absorption lines files in a directory
Author
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] basename Generic Input
[in] robust Generic Input (Default: "0")
Definition at line 846 of file m_absorptionlines.cc.
References CREATE_OUT3, and global_data::species_data.
Referenced by abs_linesReadSpeciesSplitCatalog_g().
abs_linesRemoveBand()
void abs_linesRemoveBand (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & qid, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesRemoveBand.
Removes qid band from abs_lines
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] qid Generic Input
Definition at line 2356 of file m_absorptionlines.cc.
References QuantumIdentifier::In(), and Array< base >::nelem().
Referenced by abs_linesRemoveBand_g().
abs_linesRemoveUnusedLocalQuantumNumbers()
void abs_linesRemoveUnusedLocalQuantumNumbers (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesRemoveUnusedLocalQuantumNumbers.
Removes unused quantums from local values in the line lists
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 1004 of file m_absorptionlines.cc.
Referenced by abs_linesRemoveUnusedLocalQuantumNumbers_g().
abs_linesReplaceWithLines()
void abs_linesReplaceWithLines (ArrayOfAbsorptionLines & abs_lines, const ArrayOfAbsorptionLines & replacing_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReplaceWithLines.
Replace all lines in abs_lines that match with lines in replacement_lines.
Each replacement_lines must match excatly a single line in abs_lines.
The matching required identical quantum number signatures to work
Note that lines are identified by their AbsorptionLines tags and by their quantum numbers.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] replacing_lines Generic Input
Definition at line 1017 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF.
Referenced by abs_linesReplaceWithLines_g().
abs_linesSetBaseParameterForMatchingLevel()
void abs_linesSetBaseParameterForMatchingLevel (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLevel.
Set parameter of all levels in abs_lines that match with QuantumIdentifier. Only works for these parameters: parameter_name = "Statistical Weight" parameter_name = "Zeeman Coefficient"
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
Definition at line 2177 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, QuantumIdentifier::ENERGY_LEVEL, my_basic_string< charT >::nelem(), and QuantumIdentifier::Type().
Referenced by abs_lines_per_speciesSetBaseParameterForMatchingLevel(), abs_lines_per_speciesSetBaseParameterForMatchingLevels(), abs_lines_per_speciesSetZeemanCoefficients(), abs_linesSetBaseParameterForMatchingLevel_g(), abs_linesSetBaseParameterForMatchingLevels(), and abs_linesSetZeemanCoefficients().
abs_linesSetBaseParameterForMatchingLevels()
void abs_linesSetBaseParameterForMatchingLevels (ArrayOfAbsorptionLines & abs_lines, const ArrayOfQuantumIdentifier & QI, const String & parameter_name, const Vector & change, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLevels.
See abs_linesSetBaseParameterForMatchingLevel
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
Definition at line 2242 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_linesSetBaseParameterForMatchingLevels_g().
abs_linesSetBaseParameterForMatchingLines()
void abs_linesSetBaseParameterForMatchingLines (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & QI, const String & parameter_name, const Numeric & change, const Index & loose_matching, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetBaseParameterForMatchingLines.
Set parameter of all lines in abs_lines that match with QuantumIdentifier. Only works for these parameters: parameter_name = "Central Frequency" parameter_name = "Line Strength" parameter_name = "Lower State Energy" parameter_name = "Einstein Coefficient" parameter_name = "Lower Statistical Weight" parameter_name = "Upper Statistical Weight" parameter_name = "Lower Zeeman Coefficient" parameter_name = "Upper Zeeman Coefficient"
Note that loose_matching:=0 means only identical quantum identifiers are accepted, otherwise the numbers in QI must just be contained in the line identifier
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter_name Generic Input
[in] change Generic Input
[in] loose_matching Generic Input (Default: "0")
Definition at line 1889 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, and my_basic_string< charT >::nelem().
Referenced by abs_lines_per_speciesSetBaseParameterForMatchingLines(), abs_lines_per_speciesSetBaseParameterForSpecies(), and abs_linesSetBaseParameterForMatchingLines_g().
abs_linesSetCutoff() [1/2]
abs_linesSetCutoff (abs_lines , cutoff_option , cutoff_value , verbosity)
Referenced by abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetCutoffForSpecies(), abs_linesSetCutoff_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetCutoff() [2/2]
void abs_linesSetCutoff (ArrayOfAbsorptionLines & abs_lines, const String & option, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetCutoff.
Sets cutoff type and magnitude for all lines.
The line is cut off when this is active at the given frequency. The only non-zero range is from this range to its negative equivalent
Available options: "None" - No cutoff "ByLine" - Cutoff relative line center, highest frequency: F0+cutoff "ByBand" - Absolute frequency, highest frequency: cutoff
For "ByLine", the negative frequency is at F0-cutoff For "ByBand", the negative frequency is at cutoff minus twice the average band frequency
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] value Generic Input
Definition at line 1296 of file m_absorptionlines.cc.
References check_enum_error(), and x.
abs_linesSetCutoffForMatch()
void abs_linesSetCutoffForMatch (ArrayOfAbsorptionLines & abs_lines, const String & option, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetCutoffForMatch.
See abs_linesSetCutoff for more options.
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] value Generic Input
[in] ID Generic Input
Definition at line 1320 of file m_absorptionlines.cc.
References check_enum_error(), QuantumIdentifier::In(), and x.
Referenced by abs_lines_per_speciesSetCutoffForMatch(), and abs_linesSetCutoffForMatch_g().
abs_linesSetEmptyBroadeningParametersToEmpty()
void abs_linesSetEmptyBroadeningParametersToEmpty (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetEmptyBroadeningParametersToEmpty.
Sets a broadening parameter to empty if it is efficiently empty
This will not save RAM but it will save disk space (reading time), and computational time by not doing unecessary calculations
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 1220 of file m_absorptionlines.cc.
References LineShape::modelparameterEmpty(), and LineShape::nVars.
Referenced by abs_linesSetEmptyBroadeningParametersToEmpty_g().
abs_linesSetLinemixingLimit() [1/2]
abs_linesSetLinemixingLimit (abs_lines , linemixinglimit_value , verbosity)
Referenced by abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_linesSetLinemixingLimit_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetLinemixingLimit() [2/2]
void abs_linesSetLinemixingLimit (ArrayOfAbsorptionLines & abs_lines, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetLinemixingLimit.
Sets line mixing limit for all lines.
If value is less than 0, no limit is applied and line mixing is active. Otherwise, line mixing is inactive if the pressure is below the limit.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] value Generic Input
Definition at line 1636 of file m_absorptionlines.cc.
References x.
abs_linesSetLinemixingLimitForMatch()
void abs_linesSetLinemixingLimitForMatch (ArrayOfAbsorptionLines & abs_lines, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetLinemixingLimitForMatch.
See abs_linesSetLinemixingLimit for values
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] value Generic Input
[in] ID Generic Input
Definition at line 1654 of file m_absorptionlines.cc.
References QuantumIdentifier::In(), and x.
Referenced by abs_lines_per_speciesSetLinemixingLimitForMatch(), and abs_linesSetLinemixingLimitForMatch_g().
abs_linesSetLineShapeModelParametersForMatchingLines()
void abs_linesSetLineShapeModelParametersForMatchingLines (ArrayOfAbsorptionLines & abs_lines, const QuantumIdentifier & QI, const String & parameter, const String & species, const String & temperaturemodel, const Vector & new_values, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetLineShapeModelParametersForMatchingLines.
Sets line shape model data parameter in matching lines.
The matching is done so that QI must be in the line identifier
Acceptable parameter(s) are: "G0" "D0" "G2" "D2" "FVC" "ETA" "Y" "G" "DV"
Acceptable temperaturemodel(s) are: None, "T0" "T1" "T2" "T3" "T4" "T5" "LM_AER" "DPL"
Acceptable species are: "AIR" (so long as it is the broadening species list) "SELF" (so long as it is the broadening species list) Any species in the line broadening species
See the user guide for the meanings of all of these keywords
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] QI Generic Input
[in] parameter Generic Input
[in] species Generic Input
[in] temperaturemodel Generic Input
[in] new_values Generic Input
Definition at line 1993 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, check_enum_error(), CREATE_OUT3, ConstVectorView::nelem(), newdata, LineShape::nmaxTempModelParams, SpeciesTag::Species(), and Raw::Average::var().
Referenced by abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), and abs_linesSetLineShapeModelParametersForMatchingLines_g().
abs_linesSetLineShapeType() [1/2]
abs_linesSetLineShapeType (abs_lines , lineshapetype_option , verbosity)
Referenced by abs_lines_per_speciesSetLineShapeType(), abs_lines_per_speciesSetLineShapeTypeForSpecies(), abs_linesSetLineShapeType_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetLineShapeType() [2/2]
void abs_linesSetLineShapeType (ArrayOfAbsorptionLines & abs_lines, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetLineShapeType.
Sets shape calculations type for all lines.
Available options: "DP" - Doppler profile "LP" - Lorentz profile "VP" - Voigt profile "SDVP" - Speed-dependent Voigt profile "HTP" - Hartman-Tran profile
See the theory guide for more details.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
Definition at line 1571 of file m_absorptionlines.cc.
References check_enum_error().
abs_linesSetLineShapeTypeForMatch()
void abs_linesSetLineShapeTypeForMatch (ArrayOfAbsorptionLines & abs_lines, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetLineShapeTypeForMatch.
See abs_linesSetLineShapeType for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1591 of file m_absorptionlines.cc.
References check_enum_error(), and QuantumIdentifier::In().
Referenced by abs_lines_per_speciesSetLineShapeTypeForMatch(), and abs_linesSetLineShapeTypeForMatch_g().
abs_linesSetMirroring() [1/2]
abs_linesSetMirroring (abs_lines , mirroring_option , verbosity)
Referenced by abs_lines_per_speciesSetMirroring(), abs_lines_per_speciesSetMirroringForSpecies(), abs_linesSetMirroring_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetMirroring() [2/2]
void abs_linesSetMirroring (ArrayOfAbsorptionLines & abs_lines, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetMirroring.
Sets mirroring type for all lines.
Available options: "None" - No mirrored line "SameAsLineShape" - Mirrored line broadened by line shape "Manual" - Manually mirrored line (be careful; allows all frequencies) "Lorentz" - Mirrored line broadened by Lorentz
Note that mirroring is never applied for DP line shape Also note that Lorentz profile is approached by most line shapes at high frequency offset. Also note that Manual settings are potentially dangerous as other frequency offsets might not work as hoped.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
Definition at line 1374 of file m_absorptionlines.cc.
References check_enum_error().
abs_linesSetMirroringForMatch()
void abs_linesSetMirroringForMatch (ArrayOfAbsorptionLines & abs_lines, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetMirroringForMatch.
See abs_linesSetMirroring for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1394 of file m_absorptionlines.cc.
References check_enum_error(), and QuantumIdentifier::In().
Referenced by abs_lines_per_speciesSetMirroringForMatch(), and abs_linesSetMirroringForMatch_g().
abs_linesSetNormalization() [1/2]
abs_linesSetNormalization (abs_lines , normalization_option , verbosity)
Referenced by abs_lines_per_speciesSetNormalization(), abs_lines_per_speciesSetNormalizationForSpecies(), abs_linesSetNormalization_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetNormalization() [2/2]
void abs_linesSetNormalization (ArrayOfAbsorptionLines & abs_lines, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetNormalization.
Sets normalization type for all lines.
Available options: "VVH" - Van Vleck and Huber "VVW" - Van Vleck and Weisskopf "RQ" - Rosenkranz quadratic "None" - No extra normalization
See the theory guide for more details.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
Definition at line 1506 of file m_absorptionlines.cc.
References check_enum_error().
abs_linesSetNormalizationForMatch()
void abs_linesSetNormalizationForMatch (ArrayOfAbsorptionLines & abs_lines, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetNormalizationForMatch.
See abs_linesSetNormalization for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1526 of file m_absorptionlines.cc.
References check_enum_error(), and QuantumIdentifier::In().
Referenced by abs_lines_per_speciesSetNormalizationForMatch(), and abs_linesSetNormalizationForMatch_g().
abs_linesSetPopulation() [1/2]
abs_linesSetPopulation (abs_lines , population_option , verbosity)
Referenced by abs_lines_per_speciesSetPopulation(), abs_lines_per_speciesSetPopulationForSpecies(), abs_linesSetPopulation_g(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
abs_linesSetPopulation() [2/2]
void abs_linesSetPopulation (ArrayOfAbsorptionLines & abs_lines, const String & option, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetPopulation.
Sets population type for all lines.
Available options: "LTE" - Standard distribution by temperature "NLTE-VibrationalTemperatures" - LTE but with vibrational temperatures "NLTE" - Distribution is given as input
You must have set nlte_field and/or its ilk to use the NLTE methods.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
Definition at line 1441 of file m_absorptionlines.cc.
References check_enum_error().
abs_linesSetPopulationForMatch()
void abs_linesSetPopulationForMatch (ArrayOfAbsorptionLines & abs_lines, const String & option, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetPopulationForMatch.
See abs_linesSetPopulation for options
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] option Generic Input
[in] ID Generic Input
Definition at line 1461 of file m_absorptionlines.cc.
References check_enum_error(), and QuantumIdentifier::In().
Referenced by abs_lines_per_speciesSetPopulationForMatch(), and abs_linesSetPopulationForMatch_g().
abs_linesSetQuantumNumberForMatch()
void abs_linesSetQuantumNumberForMatch (ArrayOfAbsorptionLines & abs_lines, const String & quantum_number, const Rational & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetQuantumNumberForMatch.
Sets a quantum number to a new value
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] quantum_number Generic Input
[in] value Generic Input
[in] ID Generic Input
Definition at line 941 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF.
Referenced by abs_lines_per_speciesSetQuantumNumberForMatch(), and abs_linesSetQuantumNumberForMatch_g().
abs_linesSetT0()
void abs_linesSetT0 (ArrayOfAbsorptionLines & abs_lines, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetT0.
Sets reference temperature for all lines.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] value Generic Input
Definition at line 1697 of file m_absorptionlines.cc.
References x.
Referenced by abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForSpecies(), and abs_linesSetT0_g().
abs_linesSetT0ForMatch()
void abs_linesSetT0ForMatch (ArrayOfAbsorptionLines & abs_lines, const Numeric & value, const QuantumIdentifier & ID, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetT0ForMatch.
Sets reference temperature
This function only acts on matches between the bands and input ID
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] value Generic Input
[in] ID Generic Input
Definition at line 1715 of file m_absorptionlines.cc.
References QuantumIdentifier::In(), and x.
Referenced by abs_lines_per_speciesSetT0ForMatch(), and abs_linesSetT0ForMatch_g().
abs_linesSetZeemanCoefficients()
void abs_linesSetZeemanCoefficients (ArrayOfAbsorptionLines & abs_lines, const ArrayOfQuantumIdentifier & qid, const Vector & gs, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesSetZeemanCoefficients.
Sets the Zeeman coefficients of the lines by user input
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
[in] qid Generic Input
[in] gs Generic Input
Definition at line 2372 of file m_absorptionlines.cc.
References abs_linesSetBaseParameterForMatchingLevel(), ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and verbosity.
Referenced by abs_linesSetZeemanCoefficients_g().
abs_linesTruncateGlobalQuantumNumbers()
void abs_linesTruncateGlobalQuantumNumbers (ArrayOfAbsorptionLines & abs_lines, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesTruncateGlobalQuantumNumbers.
Truncates all global quantum numbers and then recombine the line list.
Author
Richard Larsson
Parameters
[in,out] abs_lines WS Input/Output
Definition at line 974 of file m_absorptionlines.cc.
References x.
Referenced by abs_linesTruncateGlobalQuantumNumbers_g().
abs_linesWriteSpeciesSplitXML()
void abs_linesWriteSpeciesSplitXML (const String & output_file_format, const ArrayOfAbsorptionLines & abs_lines, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesWriteSpeciesSplitXML.
As abs_linesWriteSplitXML but writes an array per species
Author
Richard Larsson
Parameters
[in] output_file_format WS Input
[in] abs_lines WS Input
[in] basename Generic Input
Definition at line 712 of file m_absorptionlines.cc.
References abs_lines_per_speciesCreateFromLines(), abs_speciesSet(), Array< base >::nelem(), verbosity, and WriteXML().
Referenced by abs_lines_per_speciesWriteSpeciesSplitXML(), and abs_linesWriteSpeciesSplitXML_g().
abs_linesWriteSplitXML()
void abs_linesWriteSplitXML (const String & output_file_format, const ArrayOfAbsorptionLines & abs_lines, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesWriteSplitXML.
Writes a split catalog, AbsorptionLines by AbsorptionLines.
There will be one unique file generated per AbsorptionLines in abs_lines.
The names of these files will be: basename+"."+AbsorptionLines.SpeciesName()+"."+to_string(N)+".xml" where N>=0 and the species name is something line "H2O".
Author
Richard Larsson
Parameters
[in] output_file_format WS Input
[in] abs_lines WS Input
[in] basename Generic Input
Definition at line 690 of file m_absorptionlines.cc.
References verbosity, and WriteXML().
Referenced by abs_linesWriteSplitXML_g().
check_enum_error()
check_enum_error (hitran_version , "Cannot understand hitran_type: " , hitran_type)
Referenced by abs_linesSetCutoff(), abs_linesSetCutoffForMatch(), abs_linesSetLineShapeModelParametersForMatchingLines(), abs_linesSetLineShapeType(), abs_linesSetLineShapeTypeForMatch(), abs_linesSetMirroring(), abs_linesSetMirroringForMatch(), abs_linesSetNormalization(), abs_linesSetNormalizationForMatch(), abs_linesSetPopulation(), and abs_linesSetPopulationForMatch().
ENUMCLASS()
ENUMCLASS (HitranType , char , Pre2004 , Post2004 , Online) &
f_gridFromAbsorptionLines()
void f_gridFromAbsorptionLines (Vector & f_grid, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Numeric & delta_f_low, const Numeric & delta_f_upp, const Index & num_freqs, const Verbosity & verbosity)
WORKSPACE METHOD: f_gridFromAbsorptionLines.
Sets f_grid to a grid relative to abs_lines_per_species
Each line will have abs_lines_per_species will have a grid of num_freqs grid points in [f0+*delta_f_low*, f0+*delta_f_upp*], where f0 is the line center.
Before leaving the function, f_grid is sorted.
Note that this method could generate significantly large f_grid if used carelessly
Author
Richard Larsson
Parameters
[out] f_grid WS Output
[in] abs_lines_per_species WS Input
[in] delta_f_low Generic Input (Default: "-5e6")
[in] delta_f_upp Generic Input (Default: "5e6")
[in] num_freqs Generic Input
Definition at line 2418 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, and Absorption::nelem().
Referenced by f_gridFromAbsorptionLines_g().
for()
for (auto &x:v)
Referenced by TransmissionMatrix::mul_aliased(), print_agenda_methods(), print_full_methods(), print_gin_methods(), and rtmethods_jacobian_finalisation().
linspace()
template<class T > std::vector<T> linspace (T s, T e, typename std::vector< T >::size_type count) noexcept
Definition at line 2399 of file m_absorptionlines.cc.
Referenced by mblock_dlos_gridUniformCircular(), mblock_dlos_gridUniformRectangular(), VectorLinSpace(), VectorLogSpace(), and ySimpleSpectrometer().
nlteSetByQuantumIdentifiers()
void nlteSetByQuantumIdentifiers (Index & nlte_do, ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const EnergyLevelMap & nlte_field, const Verbosity & verbosity)
WORKSPACE METHOD: nlteSetByQuantumIdentifiers.
Turns on NTLE calculations.
Takes the quantum identifers for NLTE temperatures and matches it to lines in abs_lines_per_species. abs_species must be set and is used to speed up calculations. After the function is done, all affected lines in abs_lines_per_species will have an internal tag to the relevant quantum identifier, which is a requirement for deeper code.
If vibrational_energies is input it must match nlte_level_identifiers in length. The vibrational energies of the affected lines will then be set by the function. Otherwise, it is assumed the vibrational energies are set by another method. If they are not set, calculations will complain later on while running deeper code.
For now only vibrational energy states are assumed to be able to be in non-LTE conditions. The QuantumIdentifier for an energy state in ARTS can look like: "CO2-626 EN v1 0/1 v2 1/1 l2 1/1 v3 0/1 r 1/1" and the matching will match ALL lines with the above. Note then that if, e.g., the "v1 0/1" term was removed from the above, then ARTS will assume that "v1" is not part of the level of energy state of interest, so lines of different "v1" will be matched as the same state. If a line is matched to more than one energy state, errors should be thrown, but be careful.
Set type of population to change computations and expected input as: LTE: Compute population by ratios found from LTE temperatures TV: Compute population by ratios found from NLTE vibrational temperatures ND: Compute population by ratios found from NLTE number densities
Author
Richard Larsson
Parameters
[out] nlte_do WS Output
[in,out] abs_lines_per_species WS Input/Output
[in] nlte_field WS Input
Definition at line 2275 of file m_absorptionlines.cc.
References EnergyLevelMap::Data(), ConstTensor4View::empty(), ConstVectorView::empty(), EnergyLevelMap::Energies(), EnergyLevelMap::Levels(), and EnergyLevelMap::ThrowIfNotOK().
Referenced by nlteSetByQuantumIdentifiers_g().
open_input_file()
open_input_file (is , hitran_file)
Referenced by ReadJPL(), ReadLBLRTM(), and ReadMytran2().
ReadArrayOfARTSCAT()
void ReadArrayOfARTSCAT (ArrayOfAbsorptionLines & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadArrayOfARTSCAT.
Reads an old Array<ArrayOfLineRecord> ARTSCAT file.
Note that the ARTSCAT-5 had quantum numbers and options stored inside it but that the options will overwrite that information. Be careful setting the options!
Author
Stefan Buehler
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 67 of file m_absorptionlines.cc.
References a, abs_linesSetCutoff(), abs_linesSetLinemixingLimit(), abs_linesSetLineShapeType(), abs_linesSetMirroring(), abs_linesSetNormalization(), abs_linesSetPopulation(), ARTS_ASSERT, ARTS_USER_ERROR, ARTS_USER_ERROR_IF, b, c, ArtsXMLTag::check_name(), CREATE_OUT2, cutoff_option, cutoff_value, ENDIAN_TYPE_LITTLE, FILE_TYPE_ASCII, fmax, fmin, ArtsXMLTag::get_attribute_value(), Zeeman::GetAdvancedModel(), globalquantumnumbers, go_on, is, linemixinglimit_value, lineshapetype_option, local_nums, localquantumnumbers, mirroring_option, Absorption::nelem(), normalization_option, NUMERIC_TYPE_DOUBLE, population_option, ArtsXMLTag::read_from_stream(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), Absorption::split_list_of_external_lines(), string2vecqn(), v(), verbosity, x, xml_find_and_open_input_file(), and xml_read_header_from_stream().
Referenced by ReadArrayOfARTSCAT_g().
ReadARTSCAT()
void ReadARTSCAT (ArrayOfAbsorptionLines & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadARTSCAT.
Reads an old ArrayOfLineRecord ARTSCAT file
Note that the ARTSCAT-5 had quantum numbers and options stored inside it but that the options will overwrite that information. Be careful setting the options!
Author
Stefan Buehler
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 194 of file m_absorptionlines.cc.
References a, abs_linesSetCutoff(), abs_linesSetLinemixingLimit(), abs_linesSetLineShapeType(), abs_linesSetMirroring(), abs_linesSetNormalization(), abs_linesSetPopulation(), ARTS_ASSERT, ARTS_USER_ERROR, ARTS_USER_ERROR_IF, b, c, ArtsXMLTag::check_name(), CREATE_OUT2, cutoff_option, cutoff_value, ENDIAN_TYPE_LITTLE, FILE_TYPE_ASCII, fmax, fmin, ArtsXMLTag::get_attribute_value(), Zeeman::GetAdvancedModel(), globalquantumnumbers, go_on, is, linemixinglimit_value, lineshapetype_option, local_nums, localquantumnumbers, mirroring_option, Absorption::nelem(), normalization_option, NUMERIC_TYPE_DOUBLE, population_option, ArtsXMLTag::read_from_stream(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), Absorption::split_list_of_external_lines(), string2vecqn(), v(), verbosity, x, xml_find_and_open_input_file(), and xml_read_header_from_stream().
Referenced by ReadARTSCAT_g(), and ReadSplitARTSCAT().
ReadJPL()
void ReadJPL (ArrayOfAbsorptionLines & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadJPL.
Reads a JPL file.
Be careful setting the options!
Author
Thomas Kuhn
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 623 of file m_absorptionlines.cc.
References abs_linesSetCutoff(), abs_linesSetLinemixingLimit(), abs_linesSetLineShapeType(), abs_linesSetMirroring(), abs_linesSetNormalization(), abs_linesSetPopulation(), cutoff_option, cutoff_value, fmax, fmin, Zeeman::GetAdvancedModel(), globalquantumnumbers, go_on, is, linemixinglimit_value, lineshapetype_option, local_nums, localquantumnumbers, mirroring_option, normalization_option, open_input_file(), population_option, Absorption::ReadFromJplStream(), Absorption::split_list_of_external_lines(), string2vecqn(), v(), verbosity, and x.
Referenced by ReadJPL_g().
ReadLBLRTM()
void ReadLBLRTM (ArrayOfAbsorptionLines & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadLBLRTM.
Reads a LBLRTM file.
Be careful setting the options!
Author
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 497 of file m_absorptionlines.cc.
References abs_linesSetCutoff(), abs_linesSetLinemixingLimit(), abs_linesSetLineShapeType(), abs_linesSetMirroring(), abs_linesSetNormalization(), abs_linesSetPopulation(), cutoff_option, cutoff_value, fmax, fmin, Zeeman::GetAdvancedModel(), globalquantumnumbers, go_on, is, linemixinglimit_value, lineshapetype_option, local_nums, localquantumnumbers, mirroring_option, normalization_option, open_input_file(), population_option, Absorption::ReadFromLBLRTMStream(), Absorption::split_list_of_external_lines(), string2vecqn(), v(), verbosity, and x.
Referenced by ReadLBLRTM_g().
ReadMytran2()
void ReadMytran2 (ArrayOfAbsorptionLines & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadMytran2.
Reads a Mytran2 file.
Be careful setting the options!
Author
Axel von Engeln
Stefan Buehler
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 560 of file m_absorptionlines.cc.
References abs_linesSetCutoff(), abs_linesSetLinemixingLimit(), abs_linesSetLineShapeType(), abs_linesSetMirroring(), abs_linesSetNormalization(), abs_linesSetPopulation(), cutoff_option, cutoff_value, fmax, fmin, Zeeman::GetAdvancedModel(), globalquantumnumbers, go_on, is, linemixinglimit_value, lineshapetype_option, local_nums, localquantumnumbers, mirroring_option, normalization_option, open_input_file(), population_option, Absorption::ReadFromMytran2Stream(), Absorption::split_list_of_external_lines(), string2vecqn(), v(), verbosity, and x.
Referenced by ReadMytran2_g().
ReadSplitARTSCAT()
void ReadSplitARTSCAT (ArrayOfAbsorptionLines & abs_lines, const ArrayOfArrayOfSpeciesTag & abs_species, const String & basename, const Numeric & fmin, const Numeric & fmax, const String & globalquantumnumbers, const String & localquantumnumbers, const Index & ignore_missing, const String & normalization_option, const String & mirroring_option, const String & population_option, const String & lineshapetype_option, const String & cutoff_option, const Numeric & cutoff_value, const Numeric & linemixinglimit_value, const Verbosity & verbosity)
WORKSPACE METHOD: ReadSplitARTSCAT.
Reads several old ArrayOfLineRecord ARTSCAT file
Note that the ARTSCAT-5 had quantum numbers and options stored inside it but that the options will overwrite that information. Be careful setting the options!
Author
Oliver Lemke
Richard Larsson
Parameters
[out] abs_lines WS Output
[in] abs_species WS Input
[in] basename Generic Input
[in] fmin Generic Input (Default: "0")
[in] fmax Generic Input (Default: "1e99")
[in] globalquantumnumbers Generic Input (Default: "")
[in] localquantumnumbers Generic Input (Default: "")
[in] ignore_missing Generic Input (Default: "0")
[in] normalization_option Generic Input (Default: "None")
[in] mirroring_option Generic Input (Default: "None")
[in] population_option Generic Input (Default: "LTE")
[in] lineshapetype_option Generic Input (Default: "VP")
[in] cutoff_option Generic Input (Default: "None")
[in] cutoff_value Generic Input (Default: "750e9")
[in] linemixinglimit_value Generic Input (Default: "-1")
Definition at line 315 of file m_absorptionlines.cc.
References cutoff_option, cutoff_value, fmax, fmin, globalquantumnumbers, linemixinglimit_value, lineshapetype_option, localquantumnumbers, mirroring_option, normalization_option, population_option, ReadARTSCAT(), global_data::species_data, SpeciesTag::TYPE_PLAIN, SpeciesTag::TYPE_ZEEMAN, and verbosity.
Referenced by ReadSplitARTSCAT_g().
reserve()
abs_lines reserve (x. size())
resize()
abs_lines resize (0)
Referenced by iyb_calc(), Array< base >::operator=(), yApplySensorPol(), and yRadar().
string2vecqn()
std::vector<QuantumNumberType> string2vecqn (const String & qnstr)
Get a list of quantum numbers from a string.
Parameters
[in] qnstr A string such as "J N v1"
Returns
List of quantum numbers
Definition at line 48 of file m_absorptionlines.cc.
References ARTS_USER_ERROR_IF, and IsValidQuantumNumberName().
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
v()
std::vector<Absorption::SingleLineExternal> v (0)
Referenced by abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLineShapeType(), abs_lines_per_speciesSetLineShapeTypeForMatch(), abs_lines_per_speciesSetMirroring(), abs_lines_per_speciesSetMirroringForMatch(), abs_lines_per_speciesSetNormalization(), abs_lines_per_speciesSetNormalizationForMatch(), abs_lines_per_speciesSetPopulation(), abs_lines_per_speciesSetPopulationForMatch(), abs_lines_per_speciesSetQuantumNumberForMatch(), abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForMatch(), ArtsXMLTag::add_attribute(), add_noise(), Arts2(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__eigen(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__explicit(), chk_interpolation_grids(), chk_pnd_field_raw_only_in_cloudbox(), chk_size(), cloudbox_field_monoIterate(), ComplexVector::ComplexVector(), ComplexVectorView::ComplexVectorView(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), covmat1D(), debug_tensor6view_get_elem(), debug_tensor7view_get_elem(), Sparse::diagonal(), dotprod_with_los(), dtransmat4(), Tensor6View::end(), Agenda::execute(), Extract(), fill_tensor6(), fill_tensor7(), Flatten(), LineShape::from_artscat4(), Zeeman::FromGrids(), Tensor7View::get(), ConstTensor7View::get(), Tensor6View::get(), ConstTensor6View::get(), get_variable_value(), GriddedFieldLatLonExpand(), gridpos(), Sparse::insert_row(), interp(), interpweights(), is_size(), jacobianAddShapeCatalogParameters(), PropagationMatrix::LeftMultiplyAtPosition(), los_xyz_by_uvw_local(), MagFieldsFromAltitudeRawCalc(), main(), Matrix::Matrix(), Matrix1ColFromVector(), Matrix1RowFromVector(), PropagationMatrix::MatrixInverseAtPosition(), Raw::Average::median(), methods(), Raw::Average::nanmedian(), nca_def_Vector(), nca_get_data_Vector(), nca_put_var_Vector(), nca_read_from_file(), nca_write_to_file(), Tensor7View::operator()(), ConstTensor7View::operator()(), Tensor6View::operator()(), ConstTensor6View::operator()(), operator<<(), ComplexVector::operator=(), ComplexVectorView::operator=(), ComplexMatrixView::operator=(), ComplexMatrix::operator=(), MatrixView::operator=(), VectorView::operator=(), Matrix::operator=(), Vector::operator=(), QuantumNumbers::QuantumNumbers(), random_fill_vector(), ReadArrayOfARTSCAT(), ReadARTSCAT(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromLBLRTMStream(), Absorption::ReadFromMytran2Stream(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), ReadNetCDF(), readppdata(), ReadXML(), ReadXMLIndexed(), refellipsoidForAzimuth(), Tensor7::resize(), GriddedField6::resize(), Tensor6::resize(), PropagationMatrix::RightMultiplyAtPosition(), rte_poslosFromECEF(), rte_poslosFromGeodetic(), ScatSpeciesMerge(), sensor_responseMetMM(), Verbosity::set_agenda_verbosity(), Verbosity::set_file_verbosity(), ArtsParser::set_gin_to_default(), Verbosity::set_screen_verbosity(), oem::NormalizingSolver< TransformationMatrixType, SolverType >::solve(), surface_props_interp(), Tensor3::Tensor3(), Tensor3FromVector(), Tensor4::Tensor4(), Tensor5::Tensor5(), Tensor6::Tensor6(), Tensor7::Tensor7(), test1(), test10(), test11(), test13(), test2(), test38(), test40(), test44(), test46(), test47(), test5(), test_diagonal(), test_empty(), test_insert_row(), test_matrix_buildup(), test_matrix_exp_propmat(), test_transmat_from_propmat(), testVector(), transmat4(), transpose(), Vector::Vector(), VectorExtractFromMatrix(), VectorFlip(), VectorView::VectorView(), while(), write_vector(), WriteNetCDF(), WriteNetCDFIndexed(), WriteXML(), WriteXMLIndexed(), xml_read_from_stream(), and xml_write_to_stream().
while() [1/2]
while (go_on)
Definition at line 450 of file m_absorptionlines.cc.
References ARTS_ASSERT, fmax, fmin, go_on, hitran_version, is, Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitranOnlineStream(), and v().
while() [2/2]
while (x. size())
Definition at line 482 of file m_absorptionlines.cc.
References x.
Variable Documentation
cutoff_option
const String const Numeric const Numeric const String const String const String const String const String const String const String const String& cutoff_option
Definition at line 428 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
cutoff_value
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric& cutoff_value
Definition at line 429 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
fmax
const String const Numeric const Numeric& fmax
Definition at line 420 of file m_absorptionlines.cc.
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), abs_linesCompact(), XsecRecord::Extract(), f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), f_gridFromSensorHIRS(), Linefunctions::find_cutoff_ranges(), find_effective_channel_boundaries(), lm_hitran_2017::read(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), ReadSplitARTSCAT(), test_and_merge_two_channels(), while(), xml_read_from_stream(), and xml_write_to_stream().
fmin
const String const Numeric& fmin
Definition at line 419 of file m_absorptionlines.cc.
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), abs_linesCompact(), XsecRecord::Extract(), f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), f_gridFromSensorHIRS(), Linefunctions::find_cutoff_ranges(), find_effective_channel_boundaries(), lm_hitran_2017::read(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), ReadSplitARTSCAT(), test_and_merge_two_channels(), while(), xml_read_from_stream(), and xml_write_to_stream().
globalquantumnumbers
const String const Numeric const Numeric const String& globalquantumnumbers
Definition at line 421 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
go_on
bool go_on = true
Definition at line 449 of file m_absorptionlines.cc.
Referenced by array_species_tag_from_string(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and while().
hitran_file
const String& hitran_file
Definition at line 418 of file m_absorptionlines.cc.
hitran_type
const String const Numeric const Numeric const String const String const String& hitran_type
Definition at line 423 of file m_absorptionlines.cc.
hitran_version
const HitranType hitran_version = toHitranType(hitran_type)
Definition at line 440 of file m_absorptionlines.cc.
Referenced by while().
is
ifstream is
Definition at line 444 of file m_absorptionlines.cc.
Referenced by apply_iy_unit(), apply_iy_unit2(), AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), chk_atm_field(), clear_rt_vars_at_gp(), cloud_atm_vars_by_gp(), ext_matFromabs_vec(), fill_tensor6(), fill_tensor7(), LineShape::from_artscat4(), get_ppath_atmvars(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), GetEnvironmentVariable(), interp(), interpweights(), iyb_calc_body(), iyIndependentBeamApproximation(), iyInterpCloudboxField(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), main(), next_species(), operator<<(), Absorption::operator>>(), LineShape::operator>>(), operator>>(), ArtsParser::parse_integer(), ArtsParser::parse_intvector_from_string(), ArtsParser::parse_numeric(), ArtsParser::parse_numvector_from_string(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldExpand1D(), Absorption::Lines::read(), TelsemAtlas::read(), ArtsXMLTag::read_from_stream(), read_text_from_stream(), ReadArrayOfARTSCAT(), ReadARTSCAT(), Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), CIARecord::ReadFromCIA(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromLBLRTMStream(), Absorption::ReadFromMytran2Stream(), SpeciesAuxData::ReadFromStream(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), readppdata(), readppheader(), rtmethods_unit_conversion(), sensor_responseInit(), sensor_responseStokesRotation(), ArtsParser::set_gin_to_default(), QuantumIdentifier::SetFromString(), SpeciesTag::SpeciesTag(), surfaceBlackbody(), telsem_atlasesReadAscii(), telsem_atlasReadAscii(), Tensor4Clip(), tessem_read_ascii(), while(), xClip(), xml_read_footer_from_stream(), xml_read_header_from_stream(), and ySimpleSpectrometer().
linemixinglimit_value
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric const Numeric& linemixinglimit_value
Definition at line 430 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
lineshapetype_option
const String const Numeric const Numeric const String const String const String const String const String const String const String& lineshapetype_option
Definition at line 427 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
local_nums
const std::vector<QuantumNumberType> local_nums = string2vecqn(localquantumnumbers)
Definition at line 437 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), and ReadMytran2().
localquantumnumbers
const String const Numeric const Numeric const String const String& localquantumnumbers
Definition at line 422 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
mirroring_option
const String const Numeric const Numeric const String const String const String const String const String& mirroring_option
Definition at line 425 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
normalization_option
const String const Numeric const Numeric const String const String const String const String& normalization_option
Definition at line 424 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
population_option
const String const Numeric const Numeric const String const String const String const String const String const String& population_option
Definition at line 426 of file m_absorptionlines.cc.
Referenced by ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), and ReadSplitARTSCAT().
verbosity
const String const Numeric const Numeric const String const String const String const String const String const String const String const String const Numeric const Numeric const Verbosity& verbosity
Initial value:
{
  const std::vector<QuantumNumberType> global_nums = string2vecqn(globalquantumnumbers)
Definition at line 431 of file m_absorptionlines.cc.
Referenced by abs_cia_dataReadFromXML(), abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), abs_lines_per_speciesChangeBaseParameterForMatchingLines(), abs_lines_per_speciesChangeBaseParameterForSpecies(), abs_lines_per_speciesCompact(), abs_lines_per_speciesSetBaseParameterForMatchingLevel(), abs_lines_per_speciesSetBaseParameterForMatchingLevels(), abs_lines_per_speciesSetBaseParameterForMatchingLines(), abs_lines_per_speciesSetBaseParameterForSpecies(), abs_lines_per_speciesSetCutoffForMatch(), abs_lines_per_speciesSetCutoffForSpecies(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), abs_lines_per_speciesSetLineShapeTypeForSpecies(), abs_lines_per_speciesSetMirroringForSpecies(), abs_lines_per_speciesSetNormalizationForSpecies(), abs_lines_per_speciesSetPopulationForSpecies(), abs_lines_per_speciesSetT0ForSpecies(), abs_lines_per_speciesSetZeemanCoefficients(), abs_lines_per_speciesWriteSpeciesSplitXML(), abs_lines_per_speciesWriteSplitXML(), abs_linesChangeBaseParameterForMatchingLevels(), abs_linesSetBaseParameterForMatchingLevels(), abs_linesSetZeemanCoefficients(), abs_linesWriteSpeciesSplitXML(), abs_linesWriteSplitXML(), abs_lookupAdapt(), abs_lookupInit(), abs_lookupSetup(), abs_lookupSetupBatch(), abs_lookupSetupWide(), abs_speciesAdd2(), abs_speciesDefineAll(), abs_speciesDefineAllInScenario(), abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), GasAbsLookup::Adapt(), AgendaAppend(), AgendaExecuteExclusive(), AgendaSet(), antenna_responseVaryingGaussian(), AntennaConstantGaussian1D(), AntennaMultiBeamsToPencilBeams(), Append(), ArrayOfAgendaAppend(), ArrayOfAgendaExecute(), ArrayOfQuantumIdentifierSet(), Arts2(), atm_fields_compactAddConstant(), atm_fields_compactAddSpecies(), AtmFieldPRegrid(), AtmFieldsCalc(), AtmFieldsCalcExpand1D(), AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), AtmRawRead(), AtmWithNLTERawRead(), batch_atm_fields_compactAddConstant(), batch_atm_fields_compactAddSpecies(), batch_atm_fields_compactCleanup(), batch_atm_fields_compactFromArrayOfMatrix(), c_errmsg(), c_write_bad_var(), c_write_too_small_dim(), Agenda::check(), chk_pnd_raw_data(), choose_abs_nls(), choose_abs_nls_pert(), CIAInfo(), CIARecordReadFromFile(), cloud_fieldsCalc(), cloud_ppath_update3D(), cloudbox_field_monoIterate(), cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq3D(), collision_coefficientsFromSplitFiles(), Copy(), create_workspace(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), DOAngularGridsSet(), doit_scat_fieldCalc(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), DoitScatteringDataPrepare(), DoitWriteIterationFields(), emission_from_propmat_field(), Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), CIARecord::Extract(), f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), f_gridFromSensorHIRS(), GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), GriddedFieldZToPRegrid(), InteractiveWorkspace::InteractiveWorkspace(), iyHybrid(), iyMC(), iySurfaceFastem(), jacobianAddBasicCatalogParameters(), jacobianAddNLTEs(), jacobianAddShapeCatalogParameters(), jacobianCalcPointingZaRecalc(), jacobianClose(), jacobianOff(), MagFieldsCalc(), MagFieldsCalcExpand1D(), MagFieldsFromAltitudeRawCalc(), MagRawRead(), main(), MCGeneral(), mcPathTraceRadar(), MCRadar(), nca_read_from_file(), nca_write_to_file(), nlte_fieldForSingleSpeciesNonOverlappingLines(), MdRecord::operator=(), opt_prop_sptFromData(), opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), pha_mat_sptFromData(), pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), pnd_fieldCalcFrompnd_field_raw(), ppath_calc(), ppath_fieldCalc(), ppathCalcFromAltitude(), ppathFromRtePos2(), ppathStepByStep(), ppathWriteXMLPartial(), Print(), propmat_clearskyAddOnTheFly(), psdAbelBoutle12(), psdFieldEtAl19(), psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), psdMonoDispersive(), psdMonoMass(), psdWangEtAl16(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), ReadMytran2(), ReadNetCDF(), ReadSplitARTSCAT(), ReadXML(), ReadXMLIndexed(), retrievalAddAbsSpecies(), retrievalAddCatalogParameter(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), retrievalAddFreqStretch(), retrievalAddMagField(), retrievalAddPointingZa(), retrievalAddPolyfit(), retrievalAddScatSpecies(), retrievalAddSinefit(), retrievalAddSpecialSpecies(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), retrievalAddWind(), retrievalDefClose(), retrievalDefInit(), run_cdisort(), scat_data_checkedCalc(), ScatElementsPndAndScatAdd(), ScatElementsToabs_speciesAdd(), ScatSpeciesPndAndScatAdd(), ScatSpeciesScatAndMetaRead(), Select(), sensor_losGeometricFromSensorPosToOtherPositions(), sensor_responseBackendFrequencySwitching(), sensor_responseGenericAMSU(), sensor_responseMetMM(), sensor_responseMultiMixerBackend(), sensor_responseSimpleAMSU(), sensorOff(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), specular_losCalc(), SurfaceFastem(), surfaceFastem(), surfaceTelsem(), SurfaceTessem(), surfaceTessem(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), time_gridOffset(), TMatrixTest(), verbosityInit(), verbositySet(), verbositySetAgenda(), verbositySetFile(), verbositySetScreen(), vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), WindFieldsCalc(), WindFieldsCalcExpand1D(), WindRawRead(), WMRFSelectChannels(), WriteNetCDF(), WriteNetCDFIndexed(), WriteXML(), WriteXMLIndexed(), xml_find_and_open_input_file(), xml_parse_from_stream(), xml_read_footer_from_stream(), xml_read_from_file(), xml_read_from_stream(), xml_read_header_from_stream(), xml_write_footer_to_stream(), xml_write_header_to_stream(), xml_write_to_file(), xml_write_to_stream(), xsec_continuum_tag(), ybatchMaskOutsideMedianRange(), ybatchMetProfiles(), ybatchMetProfilesClear(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ySimpleSpectrometer(), and z_surfaceFromFileAndGrid().
x
auto x = Absorption::split_list_of_external_lines(v, local_nums, global_nums)
Definition at line 479 of file m_absorptionlines.cc.
Referenced by Absorption::SingleLine::A(), Interpolation::nonstd::abs(), abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetCutoffForMatch(), abs_lines_per_speciesSetCutoffForSpecies(), abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetQuantumNumberForMatch(), abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForMatch(), abs_lines_per_speciesSetT0ForSpecies(), abs_linesDeleteLinesWithUndefinedLocalQuanta(), abs_linesSetCutoff(), abs_linesSetCutoffForMatch(), abs_linesSetLinemixingLimit(), abs_linesSetLinemixingLimitForMatch(), abs_linesSetT0(), abs_linesSetT0ForMatch(), abs_linesTruncateGlobalQuantumNumbers(), abs_lookupInit(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), Conversion::acosd(), add(), PropagationMatrix::AddAbsorptionVectorAtPosition(), PropagationMatrix::AddAtPosition(), RadiationVector::addMultiplied(), agendas(), AngularGridsSetFluxCalc(), antenna_responseGaussian(), antenna_responseVaryingGaussian(), Linefunctions::apply_linestrength_from_nlte_level_distributions(), ArrayOfIndexLinSpace(), ArrayOfQuantumIdentifierSet(), Conversion::asind(), Conversion::atan2d(), Conversion::atand(), Conversion::atm2pa(), AtmFieldPerturb(), backend_channel_responseFlat(), backend_channel_responseGaussian(), Absorption::Lines::Bath(), bin_quadweights(), by_reference(), by_value(), calcBaselineFit(), calculate_weights_linear(), cart2pol(), cart2poslos(), cart2poslos_plain(), cart2sph(), cart2sph_plain(), Conversion::celsius2kelvin(), check_collision_line_identifiers(), chk_atm_field(), chk_atm_surface(), chk_contains(), chk_if_bool(), chk_if_decreasing(), chk_if_in_range(), chk_if_in_range_exclude(), chk_if_in_range_exclude_high(), chk_if_in_range_exclude_low(), chk_if_increasing(), chk_matrix_ncols(), chk_matrix_nrows(), chk_not_empty(), chk_not_negative(), chk_size(), chk_vector_length(), SpeciesTag::CIADataset(), SpeciesTag::CIASecond(), ComplexMatrix::ComplexMatrix(), ComplexVector::ComplexVector(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), conti_n2__(), copy(), Conversion::cosd(), covmat1D(), Absorption::Lines::Cutoff(), Absorption::Lines::CutoffFreqValue(), Interpolation::cyclic_clamp(), dabsorption_nlte_rate_dT(), dabsorption_nlte_rate_dTl(), dabsorption_nlte_rate_dTu(), dampened_statistical_equilibrium_equation(), defocusing_general_sub(), Rational::Denom(), derive_scat_species_a_and_b(), describe(), lm_hitran_2017::detband(), LineShape::differenceOutput(), PropagationMatrix::DivideAtPosition(), Interpolation::dl_dval(), Interpolation::Lagrange::dlx_finder(), Interpolation::FixedLagrange< PolyOrder >::dlx_finder(), do_gridcell_2d_byltest(), do_gridcell_3d_byltest(), dtransmat3(), dxdvmrscf(), Absorption::SingleLine::E0(), EnergyLevelMapSet(), Agenda::execute(), extract(), Absorption::SingleLine::F0(), fill_tensor6(), fill_tensor7(), fill_with_junk(), find_all(), find_first(), Raw::Reduce::find_first_and_last_1(), PropagationMatrix::FittingShape(), fixed_defaults(), FlagOff(), FlagOn(), flat(), Raw::Reduce::focus(), Raw::Reduce::focus_doublescaling(), LineShape::from_linemixingdata(), LineShape::from_pressurebroadeningdata(), Zeeman::FromGrids(), func_2straights(), fwv_mpmf87s93__(), g0Earth(), g_legendre_poly(), g_legendre_poly_deriv(), g_legendre_poly_norm_schmidt(), g_legendre_poly_norm_schmidt_deriv(), g_legendre_poly_norm_schmidt_deriv1(), g_legendre_poly_norm_schmidt_deriv2(), g_legendre_poly_norm_schmidt_deriv3(), g_legendre_poly_norm_schmidt_deriv4(), Absorption::SingleLine::g_low(), Absorption::SingleLine::g_upp(), gaussian_response(), gaussian_response_autogrid(), geompath_tanpos_3d(), EnergyLevelMap::get_ratio_params(), EnergyLevelMap::get_vibtemp_params(), Zeeman::Model::gl(), good_enum(), groups(), gsl_integration_glfixed_table_alloc(), gsl_rng_uniform_pos(), Zeeman::Model::gu(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), Conversion::hz_per_msquared2kaycm_per_cmsquared(), Conversion::hz_per_pa2kaycm_per_atm(), Absorption::SingleLine::I0(), IndexSet(), IndexSetToLast(), init_mpm2020_lsm(), init_mpm2020_slsm(), integer_div(), interp_atmfield_by_gp(), interp_atmfield_by_itw(), interp_atmsurface_by_gp(), interp_atmsurface_by_itw(), interp_poly(), inversion_iterate_agendaExecute(), is_bool(), is_decreasing(), is_increasing(), is_multiple(), is_size(), is_sorted(), is_space_char(), is_unique(), isnormal_or_zero(), SpeciesTag::Isotopologue(), iySurfaceFastem(), jacobianAdjustAndTransform(), Conversion::kaycm_per_atm2hz_per_pa(), Conversion::kelvin2celsius(), LagrangeInterpol4(), Interpolation::LagrangeVector(), last(), lbl_checkedCalc(), legendre_poly(), legendre_poly_deriv(), legendre_poly_norm_schmidt(), legendre_poly_norm_schmidt_deriv(), SpeciesTag::Lf(), Absorption::Lines::LinemixingLimit(), Absorption::Lines::LineShapeType(), linreg(), linspace(), lorentz_pdf(), lsf(), Interpolation::Lagrange::lx_finder(), Interpolation::FixedLagrange< PolyOrder >::lx_finder(), main(), Raw::Mask::mask(), MaTipping_H2O_foreign_continuum(), matrix_vector_mult(), MatrixSet(), MatrixSetConstant(), max(), mblock_dlos_gridUniformCircular(), mean(), LineShape::MetaData2ModelShape(), Conversion::meter2angstrom(), methods(), mgd(), mgd_with_derivatives(), Conversion::mhz_per_torr2hz_per_pa(), min(), Interpolation::min_cyclic(), LineShape::mirroredOutput(), Absorption::Lines::Mirroring(), mod_gamma_dist(), LineShape::Model::Model(), LineShape::ModelShape2MetaData(), PropagationMatrix::MultiplyAtPosition(), NameMaps::NameMaps(), Raw::Reduce::nanfocus(), nanmean(), Raw::Average::nanmedian(), Raw::Average::nanstd(), LineShape::negativeOutput(), Absorption::nelem(), nelemGet(), nlinspace(), nlogspace(), nlte_fieldForSingleSpeciesNonOverlappingLines(), Rational::Nom(), Absorption::Lines::Normalization(), numeric2rational(), NumericSet(), operator*(), ComplexMatrixView::operator*=(), ComplexVectorView::operator*=(), VectorView::operator*=(), PropagationMatrix::operator*=(), Sparse::operator*=(), Tensor3View::operator*=(), Tensor4View::operator*=(), Tensor5View::operator*=(), Tensor6View::operator*=(), Tensor7View::operator*=(), MatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexVectorView::operator+=(), VectorView::operator+=(), PropagationMatrix::operator+=(), StokesVector::operator+=(), Tensor3View::operator+=(), Tensor4View::operator+=(), Tensor5View::operator+=(), Tensor6View::operator+=(), Tensor7View::operator+=(), MatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexVectorView::operator-=(), VectorView::operator-=(), PropagationMatrix::operator-=(), Tensor3View::operator-=(), Tensor4View::operator-=(), Tensor5View::operator-=(), Tensor6View::operator-=(), Tensor7View::operator-=(), MatrixView::operator-=(), ComplexMatrixView::operator/=(), ComplexVectorView::operator/=(), VectorView::operator/=(), PropagationMatrix::operator/=(), Sparse::operator/=(), Tensor3View::operator/=(), Tensor4View::operator/=(), Tensor5View::operator/=(), Tensor6View::operator/=(), Tensor7View::operator/=(), MatrixView::operator/=(), Jacobian::operator<<(), operator<<(), LineShape::operator<<(), ComplexVectorView::operator=(), ComplexMatrixView::operator=(), ComplexMatrix::operator=(), Agenda::operator=(), ComplexVector::operator=(), Vector::operator=(), MRecord::operator=(), PropagationMatrix::operator=(), StokesVector::operator=(), Tensor3::operator=(), Tensor4::operator=(), Tensor5::operator=(), Tensor6::operator=(), Tensor7::operator=(), VectorView::operator=(), MatrixView::operator=(), Matrix::operator=(), Tensor3View::operator=(), Tensor4View::operator=(), Tensor5View::operator=(), Tensor6View::operator=(), Tensor7View::operator=(), double_istream::operator>>(), double_imanip::operator>>(), operator>>(), Raw::Mask::out_of_bounds(), Conversion::pa2atm(), Conversion::pa2torr(), ArtsParser::parse_main(), ArtsParser::parse_method(), pCqSDHC_to_arts(), pCqSDHC_to_arts_D2_deriv(), pCqSDHC_to_arts_freq_deriv(), pCqSDHC_to_arts_G2_deriv(), Jacobian::Target::Perturbation(), pol2cart(), polint(), polynomial_basis_func(), Absorption::Lines::Population(), poslos2cart(), Constant::pow2(), Constant::pow3(), Constant::pow4(), ppath_start_stepping(), Print(), print_agenda_define(), print_agenda_execute(), print_agenda_methods(), print_full_methods(), print_gin_methods(), print_groups_and_namespaces(), print_variables(), profile_(), PropagationMatrix::PropagationMatrix(), psd_mono_common(), lm_hitran_2017::qsdv(), lm_hitran_2017::qsdv_si(), QuantumIdentifier::QuantumIdentifier(), QuantumIdentifierSet(), Jacobian::Target::QuantumIdentity(), r_crossing_3d(), ran_gaussian(), random_covariance_matrix(), RationalSet(), raytrace_3d_linear_basic(), LineShape::SingleSpeciesModel::read(), read_text_from_file(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), lm_hitran_2017::readlines(), ReadMytran2(), PropagationMatrix::RemoveAtPosition(), Absorption::Lines::RemoveLocalQuantum(), reshape(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), rte_step_doit_replacement(), run_oem_matlab(), Time::Seconds(), Time::seconds_into_day(), Absorption::Lines::Self(), set_constant_statistical_equilibrium_matrix(), Linefunctions::set_doppler(), PropagationMatrix::SetAtPosition(), StokesVector::SetAtPosition(), LineShape::Model::SetLineMixingModel(), LineShape::si2cgs(), sign(), Conversion::sind(), ArtsParser::skip_to_next_argument(), solve(), SpeciesTag::Species(), sph2cart(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Interpolation::start_pos_finder(), Raw::Average::std(), StokesVector::StokesVector(), surf_radius_at_l(), swv_mpmf87s93__(), Absorption::Lines::T0(), Conversion::tand(), Tensor3SetConstant(), Tensor4Clip(), Tensor4SetConstant(), Tensor5SetConstant(), Tensor6SetConstant(), Tensor7SetConstant(), test01(), test09(), test12(), test13(), test14(), test16(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), test26(), test34(), test42(), test44(), test6(), test7(), test8(), test_gsl_int(), test_lusolve1D(), test_lusolve4D(), test_r_deriv_propagationmatrix(), test_solve_linear_system(), time_stepper_selection(), Time::toGMTStruct(), Conversion::torr2pa(), Jacobian::toString(), Time::toStruct(), Jacobian::toTypeOfTarget(), transform(), transform_jacobian(), transform_x(), transform_x_back(), transmat3(), transpose(), Trapz(), MCAntenna::Type(), EnergyLevelMap::Type(), SpeciesTag::Type(), QuantumIdentifier::Type(), lm_hitran_2017::typeFull(), lm_hitran_2017::typeLP(), lm_hitran_2017::typeVP(), SpeciesTag::Uf(), unitl(), Absorption::Lines::validIndexForCutoff(), Absorption::Lines::validIndexForLineShapeType(), Absorption::Lines::validIndexForMirroring(), Absorption::Lines::validIndexForNormalization(), Absorption::Lines::validIndexForPopulation(), SpeciesTag::validIndexForType(), EnergyLevelMap::validIndexForType(), QuantumIdentifier::validIndexForType(), MCAntenna::validType(), Vector::Vector(), LineShape::LegacyLineMixingData::vector2modellm(), LineShape::LegacyPressureBroadeningData::vector2modelpb(), VectorInsertGridPoints(), VectorLinSpace(), VectorLogSpace(), VectorMatrixMultiply(), VectorNLinSpace(), VectorNLinSpaceConst(), vmrunitscf(), while(), x2artsAtmAndSurf(), x2artsSensor(), and xlgr_().