ARTS: m_artstime.cc File Reference
m_artstime.cc File Reference
Stuff related to manipulating time.
#include <thread>
#include "matpackI.h"
#include "artstime.h"
#include "messages.h"
#include "sorting.h"
Functions
void timeNow (Time &time, const Verbosity &)
WORKSPACE METHOD: timeNow.
void Duration (Numeric &duration, const Time &t0, const Time &t1, const Verbosity &)
WORKSPACE METHOD: Duration.
void Sleep (const Numeric &duration, const Verbosity &)
WORKSPACE METHOD: Sleep.
void timeSleep (const Time &time, const Verbosity &)
WORKSPACE METHOD: timeSleep.
void LocalTimeOffset (Numeric &dt, const Verbosity &)
WORKSPACE METHOD: LocalTimeOffset.
void timeOffset (Time &time, const Numeric &offset, const Verbosity &)
WORKSPACE METHOD: timeOffset.
void time_gridOffset (ArrayOfTime &time_grid, const Numeric &offset, const Verbosity &verbosity)
WORKSPACE METHOD: time_gridOffset.
Detailed Description
Stuff related to manipulating time.
Author
Richard Larsson
Date
2020-04-13
Definition in file m_artstime.cc.
Function Documentation
Duration()
void Duration (Numeric & duration, const Time & start, const Time & end, const Verbosity & verbosity)
WORKSPACE METHOD: Duration.
Sets the seconds between two times.
Author
Richard Larsson
Parameters
[out] duration Generic output
[in] start Generic Input
[in] end Generic Input
Definition at line 41 of file m_artstime.cc.
Referenced by Duration_g().
LocalTimeOffset()
void LocalTimeOffset (Numeric & dt, const Verbosity & verbosity)
WORKSPACE METHOD: LocalTimeOffset.
Sets the seconds between localtime and gmtime representation of now().
Author
Richard Larsson
Parameters
[out] dt Generic output
Definition at line 59 of file m_artstime.cc.
References ARTS::Var::time().
Referenced by LocalTimeOffset_g().
Sleep()
void Sleep (const Numeric & time, const Verbosity & verbosity)
WORKSPACE METHOD: Sleep.
Sleeps for a number of seconds
Author
Richard Larsson
Parameters
[in] time Generic Input
Definition at line 47 of file m_artstime.cc.
Referenced by Sleep_g().
time_gridOffset()
void time_gridOffset (ArrayOfTime & time_grid, const Numeric & dt, const Verbosity & verbosity)
WORKSPACE METHOD: time_gridOffset.
Offsets a time grid by some seconds.
Author
Richard Larsson
Parameters
[in,out] time_grid WS Input/Output
[in] dt Generic Input
Definition at line 74 of file m_artstime.cc.
References ARTS::Var::time(), ARTS::Var::time_grid(), timeOffset(), and ARTS::Var::verbosity().
Referenced by time_gridOffset_g().
timeNow()
void timeNow (Time & time, const Verbosity & verbosity)
WORKSPACE METHOD: timeNow.
Sets time to system_clock::now().
Author
Richard Larsson
Parameters
[out] time WS Output
Definition at line 35 of file m_artstime.cc.
References ARTS::Var::time().
Referenced by timeNow_g().
timeOffset()
void timeOffset (Time & time, const Numeric & offset, const Verbosity & verbosity)
WORKSPACE METHOD: timeOffset.
Offsets time for some seconds
Author
Richard Larsson
Parameters
[in,out] time WS Input/Output
[in] offset Generic Input
Definition at line 68 of file m_artstime.cc.
References ARTS::Var::time().
Referenced by time_gridOffset(), and timeOffset_g().
timeSleep()
void timeSleep (const Time & time, const Verbosity & verbosity)
WORKSPACE METHOD: timeSleep.
Sleeps until time has been reached.
Author
Richard Larsson
Parameters
[in] time WS Input
Definition at line 53 of file m_artstime.cc.
References ARTS::Var::time().
Referenced by timeSleep_g().