ARTS: m_array.cc File Reference
m_array.cc File Reference
Stuff related to manipulating arrays.
#include "artstime.h"
#include "matpackVII.h"
#include "messages.h"
#include "sorting.h"
Macros
#define TIME_SORT_MACRO(VAR)
#define FLATTEN_MACRO(VAR)
Functions
template<class T >
Array< T > TimeSortTemplate (const Array< T > &arr, const ArrayOfTime &time_stamps)
template<class T >
Array< T > FlattenArrayTemplate (const Array< Array< T >> &in)
void Flatten (Matrix &out, const ArrayOfVector &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
void Flatten (Tensor3 &out, const ArrayOfMatrix &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
void Flatten (Tensor4 &out, const ArrayOfTensor3 &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
void Flatten (Tensor5 &out, const ArrayOfTensor4 &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
void Flatten (Tensor6 &out, const ArrayOfTensor5 &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
void Flatten (Tensor7 &out, const ArrayOfTensor6 &in, const Verbosity &)
WORKSPACE METHOD: Flatten.
Detailed Description
Stuff related to manipulating arrays.
Author
Richard Larsson
Date
2020-04-24
Definition in file m_array.cc.
Macro Definition Documentation
FLATTEN_MACRO
#define FLATTEN_MACRO (VAR)
Value:
void Flatten(VAR & out, const Array< VAR > & in, const Verbosity&) \
{out = FlattenArrayTemplate(in);}
Definition at line 86 of file m_array.cc.
TIME_SORT_MACRO
#define TIME_SORT_MACRO (VAR)
Value:
void time_stampsSort(VAR & out, const ArrayOfTime& time_stamps, const VAR & in, const Verbosity&) \
{out = TimeSortTemplate(in, time_stamps);}
Definition at line 54 of file m_array.cc.
Function Documentation
Flatten() [1/6]
void Flatten (Matrix & out, const ArrayOfVector & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 95 of file m_array.cc.
References joker, Array< base >::nelem(), and v().
Referenced by Flatten_sg_ArrayOfTimeArrayOfArrayOfTime_g(), Flatten_sg_ArrayOfVectorArrayOfArrayOfVector_g(), Flatten_sg_MatrixArrayOfVector_g(), Flatten_sg_Tensor3ArrayOfMatrix_g(), Flatten_sg_Tensor4ArrayOfTensor3_g(), Flatten_sg_Tensor5ArrayOfTensor4_g(), Flatten_sg_Tensor6ArrayOfTensor5_g(), and Flatten_sg_Tensor7ArrayOfTensor6_g().
Flatten() [2/6]
void Flatten (Tensor3 & out, const ArrayOfMatrix & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 112 of file m_array.cc.
References c, joker, Array< base >::nelem(), and v().
Flatten() [3/6]
void Flatten (Tensor4 & out, const ArrayOfTensor3 & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 133 of file m_array.cc.
References c, joker, Array< base >::nelem(), and v().
Flatten() [4/6]
void Flatten (Tensor5 & out, const ArrayOfTensor4 & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 157 of file m_array.cc.
References b, c, joker, Array< base >::nelem(), and v().
Flatten() [5/6]
void Flatten (Tensor6 & out, const ArrayOfTensor5 & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 184 of file m_array.cc.
References b, c, joker, Array< base >::nelem(), and v().
Flatten() [6/6]
void Flatten (Tensor7 & out, const ArrayOfTensor6 & in, const Verbosity & verbosity)
WORKSPACE METHOD: Flatten.
Flattens an ArrayOfArray<T> to Array<T> or an Array of matpack-types to a larger dimension matpack (if dimensions agree)
The intended transformation for arrays is (sub-arrays can have different sizes): <br> {{a, b, c}, {d, e}} -> {a, b, c, d, e}
The intended transformation for arrays to matpack types is (sub-types must have same size): <br> {{a, b, c}, {d, e, f}} -> {a, b, c, d, e, f}
Author
Richard Larsson
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 214 of file m_array.cc.
References b, c, joker, Array< base >::nelem(), v(), and w().
FlattenArrayTemplate()
template<class T > Array<T> FlattenArrayTemplate (const Array< Array< T >> & in)
Definition at line 64 of file m_array.cc.
TimeSortTemplate()
template<class T > Array<T> TimeSortTemplate (const Array< T > & arr, const ArrayOfTime & time_stamps)
Definition at line 35 of file m_array.cc.
References get_sorted_indexes(), and Array< base >::nelem().