ARTS: m_basic_types.cc File Reference
m_basic_types.cc File Reference
Workspace functions for straightforward operations on variables of basic types.
#include <cmath>
#include "array.h"
#include "arts.h"
#include "artstime.h"
#include "energylevelmap.h"
#include "exceptions.h"
#include "gridded_fields.h"
#include "lin_alg.h"
#include "logic.h"
#include "math_funcs.h"
#include "matpackI.h"
#include "matpackII.h"
#include "matpackIII.h"
#include "matpackIV.h"
#include "matpackV.h"
#include "matpackVI.h"
#include "matpackVII.h"
#include "messages.h"
#include "mystring.h"
#include "optproperties.h"
#include "quantum.h"
#include "sorting.h"
Functions
void ArrayOfIndexSet (ArrayOfIndex &aoi, const ArrayOfIndex &values, const Verbosity &)
WORKSPACE METHOD: ArrayOfIndexSet.
void ArrayOfIndexSetConstant (ArrayOfIndex &aoi, const Index &nelem, const Index &value, const Verbosity &)
WORKSPACE METHOD: ArrayOfIndexSetConstant.
void ArrayOfIndexLinSpace (ArrayOfIndex &x, const Index &start, const Index &stop, const Index &step, const Verbosity &verbosity)
WORKSPACE METHOD: ArrayOfIndexLinSpace.
void ArrayOfStringSet (ArrayOfString &sa, const ArrayOfString &sa2, const Verbosity &)
WORKSPACE METHOD: ArrayOfStringSet.
void FlagOff (Index &x, const Verbosity &)
WORKSPACE METHOD: FlagOff.
void FlagOn (Index &x, const Verbosity &)
WORKSPACE METHOD: FlagOn.
void IndexAdd (Index &out, const Index &in, const Index &value, const Verbosity &)
WORKSPACE METHOD: IndexAdd.
void IndexSet (Index &x, const Index &value, const Verbosity &)
WORKSPACE METHOD: IndexSet.
void IndexStepDown (Index &xout, const Index &xin, const Verbosity &)
WORKSPACE METHOD: IndexStepDown.
void IndexStepUp (Index &xout, const Index &xin, const Verbosity &)
WORKSPACE METHOD: IndexStepUp.
void MatrixAddScalar (Matrix &out, const Matrix &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: MatrixAddScalar.
void MatrixCopySparse (Matrix &out, const Sparse &in, const Verbosity &)
WORKSPACE METHOD: MatrixCopySparse.
void MatrixExtractFromTensor3 (Matrix &m, const Tensor3 &t3, const Index &index, const String &direction, const Verbosity &)
WORKSPACE METHOD: MatrixExtractFromTensor3.
void MatrixMatrixMultiply (Matrix &Y, const Matrix &M, const Matrix &X, const Verbosity &)
WORKSPACE METHOD: MatrixMatrixMultiply.
void MatrixVectorMultiply (Vector &Y, const Matrix &M, const Vector &X, const Verbosity &)
WORKSPACE METHOD: MatrixVectorMultiply.
void Matrix1ColFromVector (Matrix &m, const Vector &v, const Verbosity &)
WORKSPACE METHOD: Matrix1ColFromVector.
void Matrix2ColFromVectors (Matrix &m, const Vector &v1, const Vector &v2, const Verbosity &)
WORKSPACE METHOD: Matrix2ColFromVectors.
void Matrix3ColFromVectors (Matrix &m, const Vector &v1, const Vector &v2, const Vector &v3, const Verbosity &)
WORKSPACE METHOD: Matrix3ColFromVectors.
void Matrix1RowFromVector (Matrix &m, const Vector &v, const Verbosity &)
WORKSPACE METHOD: Matrix1RowFromVector.
void Matrix2RowFromVectors (Matrix &m, const Vector &v1, const Vector &v2, const Verbosity &)
WORKSPACE METHOD: Matrix2RowFromVectors.
void Matrix3RowFromVectors (Matrix &m, const Vector &v1, const Vector &v2, const Vector &v3, const Verbosity &)
WORKSPACE METHOD: Matrix3RowFromVectors.
void MatrixIdentity (Matrix &out, const Index &n, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: MatrixIdentity.
void MatrixScale (Matrix &out, const Matrix &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: MatrixScale.
void MatrixSet (Matrix &x, const Matrix &values, const Verbosity &)
WORKSPACE METHOD: MatrixSet.
void MatrixSetConstant (Matrix &x, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: MatrixSetConstant.
void NumericAdd (Numeric &out, const Numeric &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: NumericAdd.
void NumericClip (Numeric &out, const Numeric &in, const Numeric &limit_low, const Numeric &limit_high, const Verbosity &)
WORKSPACE METHOD: NumericClip.
void NumericFromVector (Numeric &out, const Vector &in, const String &op, const Verbosity &)
WORKSPACE METHOD: NumericFromVector.
void NumericInvScale (Numeric &out, const Numeric &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: NumericInvScale.
void NumericScale (Numeric &out, const Numeric &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: NumericScale.
void NumericSet (Numeric &x, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: NumericSet.
void QuantumIdentifierSet (QuantumIdentifier &x, const String &value, const Verbosity &)
WORKSPACE METHOD: QuantumIdentifierSet.
void ArrayOfQuantumIdentifierSet (ArrayOfQuantumIdentifier &x, const ArrayOfString &values, const Verbosity &verbosity)
WORKSPACE METHOD: ArrayOfQuantumIdentifierSet.
void RationalAdd (Rational &out, const Rational &in, const Rational &value, const Verbosity &)
WORKSPACE METHOD: RationalAdd.
void RationalInvScale (Rational &out, const Rational &in, const Rational &value, const Verbosity &)
WORKSPACE METHOD: RationalInvScale.
void RationalScale (Rational &out, const Rational &in, const Rational &value, const Verbosity &)
WORKSPACE METHOD: RationalScale.
void RationalSet (Rational &x, const Index &numerator, const Index &denominator, const Verbosity &)
WORKSPACE METHOD: RationalSet.
void SparseSparseMultiply (Sparse &Y, const Sparse &M, const Sparse &X, const Verbosity &)
WORKSPACE METHOD: SparseSparseMultiply.
void SparseMatrixIdentity (Sparse &X, const Index &n, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: SparseMatrixIdentity.
void DiagonalMatrix (Matrix &X, const Vector &diag, const Verbosity &)
WORKSPACE METHOD: DiagonalMatrix.
void DiagonalMatrix (Sparse &X, const Vector &diag, const Verbosity &)
WORKSPACE METHOD: DiagonalMatrix.
void StringSet (String &s, const String &s2, const Verbosity &)
WORKSPACE METHOD: StringSet.
void Tensor3AddScalar (Tensor3 &out, const Tensor3 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor3AddScalar.
void Tensor3FromVector (Tensor3 &m, const Vector &v, const Verbosity &)
WORKSPACE METHOD: Tensor3FromVector.
void Tensor3Scale (Tensor3 &out, const Tensor3 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor3Scale.
void Tensor3SetConstant (Tensor3 &x, const Index &npages, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: Tensor3SetConstant.
void Tensor3ExtractFromTensor4 (Tensor3 &t3, const Tensor4 &t4, const Index &index, const String &direction, const Verbosity &)
WORKSPACE METHOD: Tensor3ExtractFromTensor4.
void Tensor4AddScalar (Tensor4 &out, const Tensor4 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor4AddScalar.
void Tensor4Scale (Tensor4 &out, const Tensor4 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor4Scale.
void Tensor4SetConstant (Tensor4 &x, const Index &nbooks, const Index &npages, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: Tensor4SetConstant.
void Tensor5Scale (Tensor5 &out, const Tensor5 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor5Scale.
void Tensor5SetConstant (Tensor5 &x, const Index &nshelves, const Index &nbooks, const Index &npages, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: Tensor5SetConstant.
void Tensor6Scale (Tensor6 &out, const Tensor6 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor6Scale.
void Tensor6SetConstant (Tensor6 &x, const Index &nvitrines, const Index &nshelves, const Index &nbooks, const Index &npages, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: Tensor6SetConstant.
void Tensor7Scale (Tensor7 &out, const Tensor7 &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: Tensor7Scale.
void Tensor7SetConstant (Tensor7 &x, const Index &nlibraries, const Index &nvitrines, const Index &nshelves, const Index &nbooks, const Index &npages, const Index &nrows, const Index &ncols, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: Tensor7SetConstant.
void Trapz (Numeric &out, const Vector &x, const Vector &y, const Verbosity &)
WORKSPACE METHOD: Trapz.
void VectorAddScalar (Vector &out, const Vector &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: VectorAddScalar.
void VectorAddVector (Vector &c, const Vector &a, const Vector &b, const Verbosity &)
WORKSPACE METHOD: VectorAddVector.
void VectorSubtractVector (Vector &c, const Vector &a, const Vector &b, const Verbosity &)
WORKSPACE METHOD: VectorSubtractVector.
void VectorClip (Vector &out, const Vector &in, const Numeric &limit_low, const Numeric &limit_high, const Verbosity &)
WORKSPACE METHOD: VectorClip.
void VectorCrop (Vector &out, const Vector &in, const Numeric &min_value, const Numeric &max_value, const Verbosity &)
WORKSPACE METHOD: VectorCrop.
void VectorExtractFromMatrix (Vector &v, const Matrix &m, const Index &index, const String &direction, const Verbosity &)
WORKSPACE METHOD: VectorExtractFromMatrix.
void VectorFlip (Vector &out, const Vector &in, const Verbosity &)
WORKSPACE METHOD: VectorFlip.
void VectorInsertGridPoints (Vector &og, const Vector &ingrid, const Vector &points, const Verbosity &verbosity)
WORKSPACE METHOD: VectorInsertGridPoints.
void VectorLinSpace (Vector &x, const Numeric &start, const Numeric &stop, const Numeric &step, const Verbosity &verbosity)
WORKSPACE METHOD: VectorLinSpace.
void VectorLogSpace (Vector &x, const Numeric &start, const Numeric &stop, const Numeric &step, const Verbosity &verbosity)
WORKSPACE METHOD: VectorLogSpace.
void VectorMatrixMultiply (Vector &y, const Matrix &M, const Vector &x, const Verbosity &)
WORKSPACE METHOD: VectorMatrixMultiply.
void VectorNLinSpace (Vector &x, const Index &n, const Numeric &start, const Numeric &stop, const Verbosity &verbosity)
WORKSPACE METHOD: VectorNLinSpace.
void ArrayOfTimeNLinSpace (ArrayOfTime &x, const Index &n, const String &start, const String &stop, const Verbosity &)
WORKSPACE METHOD: ArrayOfTimeNLinSpace.
void VectorNLogSpace (Vector &x, const Index &n, const Numeric &start, const Numeric &stop, const Verbosity &verbosity)
WORKSPACE METHOD: VectorNLogSpace.
void VectorPower (Vector &out, const Vector &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: VectorPower.
void VectorReshapeMatrix (Vector &v, const Matrix &m, const String &direction, const Verbosity &)
WORKSPACE METHOD: VectorReshapeMatrix.
void VectorScale (Vector &out, const Vector &in, const Numeric &value, const Verbosity &)
WORKSPACE METHOD: VectorScale.
void VectorSetConstant (Vector &x, const Index &n, const Numeric &value, const Verbosity &verbosity)
WORKSPACE METHOD: VectorSetConstant.
void ArrayOfTimeSetConstant (ArrayOfTime &x, const Index &n, const Time &value, const Verbosity &verbosity)
WORKSPACE METHOD: ArrayOfTimeSetConstant.
void VectorSet (Vector &x, const Vector &values, const Verbosity &)
WORKSPACE METHOD: VectorSet.
void VectorVectorMultiply (Vector &y, const Vector &x1, const Vector &x2, const Verbosity &)
WORKSPACE METHOD: VectorVectorMultiply.
void Compare (const Numeric &var1, const Numeric &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Vector &var1, const Vector &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Matrix &var1, const Matrix &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Tensor3 &var1, const Tensor3 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Tensor4 &var1, const Tensor4 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Tensor5 &var1, const Tensor5 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Tensor7 &var1, const Tensor7 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const ArrayOfVector &var1, const ArrayOfVector &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const ArrayOfMatrix &var1, const ArrayOfMatrix &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const ArrayOfTensor7 &var1, const ArrayOfTensor7 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const GriddedField3 &var1, const GriddedField3 &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const Sparse &var1, const Sparse &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void Compare (const SingleScatteringData &var1, const SingleScatteringData &var2, const Numeric &maxabsdiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: Compare.
void _cr_internal_ (const Numeric &var1, const Numeric &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &)
void _cr_internal_ (const ConstVectorView var1, const ConstVectorView var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstMatrixView var1, const ConstMatrixView var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstTensor3View var1, const ConstTensor3View var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstTensor4View var1, const ConstTensor4View var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstTensor5View var1, const ConstTensor5View var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstTensor6View var1, const ConstTensor6View var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const ConstTensor7View var1, const ConstTensor7View var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const PropagationMatrix &var1, const PropagationMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void _cr_internal_ (const StokesVector &var1, const StokesVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
template<class T >
void _cr_internal_ (const Array< T > &var1, const Array< T > &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void CompareRelative (const Numeric &var1, const Numeric &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Vector &var1, const Vector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Matrix &var1, const Matrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Tensor3 &var1, const Tensor3 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Tensor4 &var1, const Tensor4 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Tensor5 &var1, const Tensor5 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Tensor6 &var1, const Tensor6 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const Tensor7 &var1, const Tensor7 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfVector &var1, const ArrayOfVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfMatrix &var1, const ArrayOfMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfTensor3 &var1, const ArrayOfTensor3 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfTensor4 &var1, const ArrayOfTensor4 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfTensor5 &var1, const ArrayOfTensor5 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void CompareRelative (const ArrayOfTensor6 &var1, const ArrayOfTensor6 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfTensor7 &var1, const ArrayOfTensor7 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfVector &var1, const ArrayOfArrayOfVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfMatrix &var1, const ArrayOfArrayOfMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfTensor3 &var1, const ArrayOfArrayOfTensor3 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfTensor4 &var1, const ArrayOfArrayOfTensor4 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void CompareRelative (const ArrayOfArrayOfTensor5 &var1, const ArrayOfArrayOfTensor5 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void CompareRelative (const ArrayOfArrayOfTensor6 &var1, const ArrayOfArrayOfTensor6 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfTensor7 &var1, const ArrayOfArrayOfTensor7 &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
void CompareRelative (const PropagationMatrix &var1, const PropagationMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfPropagationMatrix &var1, const ArrayOfPropagationMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfPropagationMatrix &var1, const ArrayOfArrayOfPropagationMatrix &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const StokesVector &var1, const StokesVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfStokesVector &var1, const ArrayOfStokesVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const ArrayOfArrayOfStokesVector &var1, const ArrayOfArrayOfStokesVector &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void CompareRelative (const EnergyLevelMap &var1, const EnergyLevelMap &var2, const Numeric &maxabsreldiff, const String &error_message, const String &var1name, const String &var2name, const String &, const String &, const Verbosity &verbosity)
WORKSPACE METHOD: CompareRelative.
void PrintPhysicalConstants (const Verbosity &verbosity)
WORKSPACE METHOD: PrintPhysicalConstants.
Detailed Description
Workspace functions for straightforward operations on variables of basic types.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-08
This file includes workspace functions for variables of basic types, such as Matrix and ArrayOfIndex. The functions are mainly of two types:
Initiation of variables by keyword arguments, such as StringSet.
Basic math, such as MatrixVectorMultiply.
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_basic_types.cc.
Function Documentation
_cr_internal_() [1/11]
template<class T > void _cr_internal_ (const Array< T > & var1, const Array< T > & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2512 of file m_basic_types.cc.
_cr_internal_() [2/11]
void _cr_internal_ (const ConstMatrixView var1, const ConstMatrixView var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2327 of file m_basic_types.cc.
_cr_internal_() [3/11]
void _cr_internal_ (const ConstTensor3View var1, const ConstTensor3View var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2351 of file m_basic_types.cc.
_cr_internal_() [4/11]
void _cr_internal_ (const ConstTensor4View var1, const ConstTensor4View var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2375 of file m_basic_types.cc.
_cr_internal_() [5/11]
void _cr_internal_ (const ConstTensor5View var1, const ConstTensor5View var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2399 of file m_basic_types.cc.
_cr_internal_() [6/11]
void _cr_internal_ (const ConstTensor6View var1, const ConstTensor6View var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2423 of file m_basic_types.cc.
_cr_internal_() [7/11]
void _cr_internal_ (const ConstTensor7View var1, const ConstTensor7View var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2447 of file m_basic_types.cc.
_cr_internal_() [8/11]
void _cr_internal_ (const ConstVectorView var1, const ConstVectorView var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2303 of file m_basic_types.cc.
_cr_internal_() [9/11]
void _cr_internal_ (const Numeric & var1, const Numeric & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity &) inline
Definition at line 2277 of file m_basic_types.cc.
_cr_internal_() [10/11]
void _cr_internal_ (const PropagationMatrix & var1, const PropagationMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2471 of file m_basic_types.cc.
_cr_internal_() [11/11]
void _cr_internal_ (const StokesVector & var1, const StokesVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity) inline
Definition at line 2491 of file m_basic_types.cc.
ArrayOfIndexLinSpace()
void ArrayOfIndexLinSpace (ArrayOfIndex & out, const Index & start, const Index & stop, const Index & step, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfIndexLinSpace.
Initializes an ArrayOfIndex with linear spacing.
The first element equals always the start value, and the spacing equals always the step value, but the last value can deviate from the stop value. step can be both positive and negative.
The created array is [start, start+step, start+2*step, ...] <br>
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] start Generic Input
[in] stop Generic Input
[in] step Generic Input
Definition at line 89 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, Zeeman::start(), and x.
Referenced by ArrayOfIndexLinSpace_g().
ArrayOfIndexSet()
void ArrayOfIndexSet (ArrayOfIndex & out, const ArrayOfIndex & value, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfIndexSet.
Creates an ArrayOfIndex from the given list of numbers.
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 73 of file m_basic_types.cc.
Referenced by ArrayOfIndexSet_g().
ArrayOfIndexSetConstant()
void ArrayOfIndexSetConstant (ArrayOfIndex & out, const Index & nelem, const Index & value, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfIndexSetConstant.
Creates an ArrayOfIndex of length nelem, with all values identical.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] value Generic Input
Definition at line 80 of file m_basic_types.cc.
References Absorption::nelem().
Referenced by ArrayOfIndexSetConstant_g().
ArrayOfQuantumIdentifierSet()
void ArrayOfQuantumIdentifierSet (ArrayOfQuantumIdentifier & out, const ArrayOfString & string_initializers, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfQuantumIdentifierSet.
Sets an ArrayOfQuantumIdentifier workspace variable to the given value by converting the input ArrayOfString
Author
Richard Larsson
Parameters
[out] out Generic output
[in] string_initializers Generic Input
Definition at line 494 of file m_basic_types.cc.
References Array< base >::nelem(), QuantumIdentifierSet(), verbosity, and x.
Referenced by ArrayOfQuantumIdentifierSet_g().
ArrayOfStringSet()
void ArrayOfStringSet (ArrayOfString & out, const ArrayOfString & value, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfStringSet.
Sets a String array according the given text. The format is text = ["String1","String2",...]
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 115 of file m_basic_types.cc.
References Array< base >::nelem().
Referenced by ArrayOfStringSet_g().
ArrayOfTimeNLinSpace()
void ArrayOfTimeNLinSpace (ArrayOfTime & out, const Index & nelem, const String & start, const String & stop, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfTimeNLinSpace.
Creates a time array with length nelem, equally spaced between the given end values.
The length (nelem) must be larger than 1.
Author
Richard Larsson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] start Generic Input
[in] stop Generic Input
Definition at line 1339 of file m_basic_types.cc.
References ARTS_USER_ERROR_IF, and Zeeman::start().
Referenced by ArrayOfTimeNLinSpace_g().
ArrayOfTimeSetConstant()
void ArrayOfTimeSetConstant (ArrayOfTime & out, const Index & nelem, const Time & value, const Verbosity & verbosity)
WORKSPACE METHOD: ArrayOfTimeSetConstant.
Creates an ArrayOfTime and sets all elements to the specified value.
The vector length is determined by nelem.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] value Generic Input
Definition at line 1462 of file m_basic_types.cc.
Referenced by ArrayOfTimeSetConstant_g().
Compare() [1/13]
void Compare (const ArrayOfMatrix & var1, const ArrayOfMatrix & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2003 of file m_basic_types.cc.
Compare() [2/13]
void Compare (const ArrayOfTensor7 & var1, const ArrayOfTensor7 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2048 of file m_basic_types.cc.
Compare() [3/13]
void Compare (const ArrayOfVector & var1, const ArrayOfVector & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1958 of file m_basic_types.cc.
Compare() [4/13]
void Compare (const GriddedField3 & var1, const GriddedField3 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2093 of file m_basic_types.cc.
Compare() [5/13]
void Compare (const Matrix & var1, const Matrix & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1611 of file m_basic_types.cc.
Compare() [6/13]
void Compare (const Numeric & var1, const Numeric & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1507 of file m_basic_types.cc.
Referenced by Compare_sg_ArrayOfMatrixArrayOfMatrix_g(), Compare_sg_ArrayOfTensor7ArrayOfTensor7_g(), Compare_sg_ArrayOfVectorArrayOfVector_g(), Compare_sg_GriddedField3GriddedField3_g(), Compare_sg_MatrixMatrix_g(), Compare_sg_NumericNumeric_g(), Compare_sg_SingleScatteringDataSingleScatteringData_g(), Compare_sg_SparseSparse_g(), Compare_sg_Tensor3Tensor3_g(), Compare_sg_Tensor4Tensor4_g(), Compare_sg_Tensor5Tensor5_g(), Compare_sg_Tensor7Tensor7_g(), and Compare_sg_VectorVector_g().
Compare() [7/13]
void Compare (const SingleScatteringData & var1, const SingleScatteringData & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2196 of file m_basic_types.cc.
Compare() [8/13]
void Compare (const Sparse & var1, const Sparse & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2131 of file m_basic_types.cc.
Compare() [9/13]
void Compare (const Tensor3 & var1, const Tensor3 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1676 of file m_basic_types.cc.
Compare() [10/13]
void Compare (const Tensor4 & var1, const Tensor4 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1741 of file m_basic_types.cc.
Compare() [11/13]
void Compare (const Tensor5 & var1, const Tensor5 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1808 of file m_basic_types.cc.
Compare() [12/13]
void Compare (const Tensor7 & var1, const Tensor7 & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1880 of file m_basic_types.cc.
Compare() [13/13]
void Compare (const Vector & var1, const Vector & var2, const Numeric & maxabsdiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsdiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Compare.
Checks the consistency between two variables.
The two variables are checked to not deviate outside the specified value (maxabsdiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
Author
Oliver Lemke
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsdiff Generic Input (Default: "")
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsdiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 1551 of file m_basic_types.cc.
CompareRelative() [1/29]
void CompareRelative (const ArrayOfArrayOfMatrix & var1, const ArrayOfArrayOfMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2841 of file m_basic_types.cc.
CompareRelative() [2/29]
void CompareRelative (const ArrayOfArrayOfPropagationMatrix & var1, const ArrayOfArrayOfPropagationMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2996 of file m_basic_types.cc.
CompareRelative() [3/29]
void CompareRelative (const ArrayOfArrayOfStokesVector & var1, const ArrayOfArrayOfStokesVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 3056 of file m_basic_types.cc.
CompareRelative() [4/29]
void CompareRelative (const ArrayOfArrayOfTensor3 & var1, const ArrayOfArrayOfTensor3 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2860 of file m_basic_types.cc.
CompareRelative() [5/29]
void CompareRelative (const ArrayOfArrayOfTensor4 & var1, const ArrayOfArrayOfTensor4 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity)
Definition at line 2879 of file m_basic_types.cc.
CompareRelative() [6/29]
void CompareRelative (const ArrayOfArrayOfTensor5 & var1, const ArrayOfArrayOfTensor5 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity)
Definition at line 2898 of file m_basic_types.cc.
CompareRelative() [7/29]
void CompareRelative (const ArrayOfArrayOfTensor6 & var1, const ArrayOfArrayOfTensor6 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2917 of file m_basic_types.cc.
CompareRelative() [8/29]
void CompareRelative (const ArrayOfArrayOfTensor7 & var1, const ArrayOfArrayOfTensor7 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity)
Definition at line 2936 of file m_basic_types.cc.
CompareRelative() [9/29]
void CompareRelative (const ArrayOfArrayOfVector & var1, const ArrayOfArrayOfVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2822 of file m_basic_types.cc.
CompareRelative() [10/29]
void CompareRelative (const ArrayOfMatrix & var1, const ArrayOfMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2708 of file m_basic_types.cc.
CompareRelative() [11/29]
void CompareRelative (const ArrayOfPropagationMatrix & var1, const ArrayOfPropagationMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2976 of file m_basic_types.cc.
CompareRelative() [12/29]
void CompareRelative (const ArrayOfStokesVector & var1, const ArrayOfStokesVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 3036 of file m_basic_types.cc.
CompareRelative() [13/29]
void CompareRelative (const ArrayOfTensor3 & var1, const ArrayOfTensor3 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2727 of file m_basic_types.cc.
CompareRelative() [14/29]
void CompareRelative (const ArrayOfTensor4 & var1, const ArrayOfTensor4 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2746 of file m_basic_types.cc.
CompareRelative() [15/29]
void CompareRelative (const ArrayOfTensor5 & var1, const ArrayOfTensor5 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1name, const String & var2name, const String & , const String & , const Verbosity & verbosity)
Definition at line 2765 of file m_basic_types.cc.
CompareRelative() [16/29]
void CompareRelative (const ArrayOfTensor6 & var1, const ArrayOfTensor6 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2784 of file m_basic_types.cc.
CompareRelative() [17/29]
void CompareRelative (const ArrayOfTensor7 & var1, const ArrayOfTensor7 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2803 of file m_basic_types.cc.
CompareRelative() [18/29]
void CompareRelative (const ArrayOfVector & var1, const ArrayOfVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2689 of file m_basic_types.cc.
CompareRelative() [19/29]
void CompareRelative (const EnergyLevelMap & var1, const EnergyLevelMap & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 3077 of file m_basic_types.cc.
CompareRelative() [20/29]
void CompareRelative (const Matrix & var1, const Matrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2575 of file m_basic_types.cc.
CompareRelative() [21/29]
void CompareRelative (const Numeric & var1, const Numeric & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2537 of file m_basic_types.cc.
Referenced by CompareRelative_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), CompareRelative_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), CompareRelative_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), CompareRelative_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), CompareRelative_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), CompareRelative_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), CompareRelative_sg_ArrayOfMatrixArrayOfMatrix_g(), CompareRelative_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), CompareRelative_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), CompareRelative_sg_ArrayOfTensor3ArrayOfTensor3_g(), CompareRelative_sg_ArrayOfTensor4ArrayOfTensor4_g(), CompareRelative_sg_ArrayOfTensor6ArrayOfTensor6_g(), CompareRelative_sg_ArrayOfTensor7ArrayOfTensor7_g(), CompareRelative_sg_ArrayOfVectorArrayOfVector_g(), CompareRelative_sg_EnergyLevelMapEnergyLevelMap_g(), CompareRelative_sg_MatrixMatrix_g(), CompareRelative_sg_NumericNumeric_g(), CompareRelative_sg_PropagationMatrixPropagationMatrix_g(), CompareRelative_sg_StokesVectorStokesVector_g(), CompareRelative_sg_Tensor3Tensor3_g(), CompareRelative_sg_Tensor4Tensor4_g(), CompareRelative_sg_Tensor5Tensor5_g(), CompareRelative_sg_Tensor6Tensor6_g(), CompareRelative_sg_Tensor7Tensor7_g(), and CompareRelative_sg_VectorVector_g().
CompareRelative() [22/29]
void CompareRelative (const PropagationMatrix & var1, const PropagationMatrix & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2956 of file m_basic_types.cc.
CompareRelative() [23/29]
void CompareRelative (const StokesVector & var1, const StokesVector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 3016 of file m_basic_types.cc.
CompareRelative() [24/29]
void CompareRelative (const Tensor3 & var1, const Tensor3 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2594 of file m_basic_types.cc.
CompareRelative() [25/29]
void CompareRelative (const Tensor4 & var1, const Tensor4 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2613 of file m_basic_types.cc.
CompareRelative() [26/29]
void CompareRelative (const Tensor5 & var1, const Tensor5 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2632 of file m_basic_types.cc.
CompareRelative() [27/29]
void CompareRelative (const Tensor6 & var1, const Tensor6 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2651 of file m_basic_types.cc.
CompareRelative() [28/29]
void CompareRelative (const Tensor7 & var1, const Tensor7 & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2670 of file m_basic_types.cc.
CompareRelative() [29/29]
void CompareRelative (const Vector & var1, const Vector & var2, const Numeric & maxabsreldiff, const String & error_message, const String & var1_wsvname, const String & var2_wsvname, const String & maxabsreldiff_wsvname, const String & error_message_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: CompareRelative.
Checks the consistency between two variables by their relative values.
The two variables are checked to not deviate outside the specified relative value (maxabsreldiff). An error is issued if this is not fulfilled.
The main application of this method is to be part of the test control files, and then used to check that a calculated value is consistent with an old, reference, value.
If either value is 0.0, the relative error is considered as 0 for easier use. This really means infinite differences, though allowing zero-crossings is useful for plenty of tests. So Be Aware!
If both var1 and var2 are non-zero, the difference is evaluated as: abs(var1/var2-1) That is, var2 is taken as the reference value.
Author
Oliver Lemke
Richard Larsson
Parameters
[in] var1 Generic Input
[in] var2 Generic Input
[in] maxabsreldiff Generic Input
[in] error_message Generic Input (Default: "")
[in] var1_wsvname Generic Input Name
[in] var2_wsvname Generic Input Name
[in] maxabsreldiff_wsvname Generic Input Name
[in] error_message_wsvname Generic Input Name
Definition at line 2556 of file m_basic_types.cc.
DiagonalMatrix() [1/2]
void DiagonalMatrix (Matrix & out, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: DiagonalMatrix.
Create a diagonal matrix from a vector. This creates a dense or sparse diagonal matrix with the elements of the given vector <br> on the diagonal.
Author
Simon Pfreundschuh
Parameters
[out] out Supergeneric output
[in] v Generic Input
Definition at line 571 of file m_basic_types.cc.
References ConstVectorView::nelem(), and Matrix::resize().
Referenced by DiagonalMatrix_sg_Matrix_g(), and DiagonalMatrix_sg_Sparse_g().
DiagonalMatrix() [2/2]
void DiagonalMatrix (Sparse & out, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: DiagonalMatrix.
Create a diagonal matrix from a vector. This creates a dense or sparse diagonal matrix with the elements of the given vector <br> on the diagonal.
Author
Simon Pfreundschuh
Parameters
[out] out Supergeneric output
[in] v Generic Input
Definition at line 582 of file m_basic_types.cc.
References Sparse::insert_elements(), ConstVectorView::nelem(), and Sparse::resize().
FlagOff()
void FlagOff (Index & flag, const Verbosity & verbosity)
WORKSPACE METHOD: FlagOff.
Sets an index variable that acts as an on/off flag to 0.
Author
Patrick Eriksson
Parameters
[out] flag Generic output
Definition at line 123 of file m_basic_types.cc.
References x.
Referenced by FlagOff_g().
FlagOn()
void FlagOn (Index & flag, const Verbosity & verbosity)
WORKSPACE METHOD: FlagOn.
Sets an index variable that acts as an on/off flag to 1.
Author
Patrick Eriksson
Parameters
[out] flag Generic output
Definition at line 126 of file m_basic_types.cc.
References x.
Referenced by FlagOn_g().
IndexAdd()
void IndexAdd (Index & out, const Index & in, const Index & value, const Verbosity & verbosity)
WORKSPACE METHOD: IndexAdd.
Adds a index and a value (out = in+value).
The result can either be stored in the same or another index. (in and out can be the same variable, but not out and value)
Author
Patrick Eriksson, Oliver Lemke
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 129 of file m_basic_types.cc.
Referenced by IndexAdd_g().
IndexSet()
void IndexSet (Index & out, const Index & value, const Verbosity & verbosity)
WORKSPACE METHOD: IndexSet.
Sets an index workspace variable to the given value.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 137 of file m_basic_types.cc.
References x.
Referenced by IndexSet_g().
IndexStepDown()
void IndexStepDown (Index & out, const Index & in, const Verbosity & verbosity)
WORKSPACE METHOD: IndexStepDown.
Performas: out = in - 1
Input and output can be same variable.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
Definition at line 140 of file m_basic_types.cc.
Referenced by IndexStepDown_g().
IndexStepUp()
void IndexStepUp (Index & out, const Index & in, const Verbosity & verbosity)
WORKSPACE METHOD: IndexStepUp.
Performas: out = in + 1
Input and output can be same variable.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
Definition at line 145 of file m_basic_types.cc.
Referenced by IndexStepUp_g().
Matrix1ColFromVector()
void Matrix1ColFromVector (Matrix & out, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix1ColFromVector.
Forms a matrix containing one column from a vector.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v Generic Input
Definition at line 280 of file m_basic_types.cc.
References joker, Matrix::resize(), and v().
Referenced by Matrix1ColFromVector_g().
Matrix1RowFromVector()
void Matrix1RowFromVector (Matrix & out, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix1RowFromVector.
Forms a matrix containing one row from a vector.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v Generic Input
Definition at line 328 of file m_basic_types.cc.
References joker, Matrix::resize(), and v().
Referenced by Matrix1RowFromVector_g().
Matrix2ColFromVectors()
void Matrix2ColFromVectors (Matrix & out, const Vector & v1, const Vector & v2, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix2ColFromVectors.
Forms a matrix containing two columns from two vectors.
The vectors are included as columns in the matrix in the same order as they are given.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v1 Generic Input
[in] v2 Generic Input
Definition at line 292 of file m_basic_types.cc.
References joker, ConstVectorView::nelem(), and Matrix::resize().
Referenced by Matrix2ColFromVectors_g().
Matrix2RowFromVectors()
void Matrix2RowFromVectors (Matrix & out, const Vector & v1, const Vector & v2, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix2RowFromVectors.
Forms a matrix containing two rows from two vectors.
The vectors are included as rows in the matrix in the same order as they are given.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v1 Generic Input
[in] v2 Generic Input
Definition at line 340 of file m_basic_types.cc.
References joker, ConstVectorView::nelem(), and Matrix::resize().
Referenced by Matrix2RowFromVectors_g().
Matrix3ColFromVectors()
void Matrix3ColFromVectors (Matrix & out, const Vector & v1, const Vector & v2, const Vector & v3, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix3ColFromVectors.
Forms a matrix containing three columns from three vectors.
The vectors are included as columns in the matrix in the same order as they are given.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v1 Generic Input
[in] v2 Generic Input
[in] v3 Generic Input
Definition at line 309 of file m_basic_types.cc.
References joker, ConstVectorView::nelem(), and Matrix::resize().
Referenced by Matrix3ColFromVectors_g().
Matrix3RowFromVectors()
void Matrix3RowFromVectors (Matrix & out, const Vector & v1, const Vector & v2, const Vector & v3, const Verbosity & verbosity)
WORKSPACE METHOD: Matrix3RowFromVectors.
Forms a matrix containing three rows from three vectors.
The vectors are included as rows in the matrix in the same order as they are given.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] v1 Generic Input
[in] v2 Generic Input
[in] v3 Generic Input
Definition at line 357 of file m_basic_types.cc.
References joker, ConstVectorView::nelem(), and Matrix::resize().
Referenced by Matrix3RowFromVectors_g().
MatrixAddScalar()
void MatrixAddScalar (Matrix & out, const Matrix & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixAddScalar.
Adds a scalar to all elements of a matrix.
The result can either be stored in the same or another matrix.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 150 of file m_basic_types.cc.
References ConstMatrixView::ncols(), ConstMatrixView::nrows(), and Matrix::resize().
Referenced by MatrixAddScalar_g().
MatrixCopySparse()
void MatrixCopySparse (Matrix & out, const Sparse & in, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixCopySparse.
Creates a matrix by copying a variable of type Sparse.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
Definition at line 168 of file m_basic_types.cc.
References c, Sparse::ncols(), Sparse::nrows(), and Matrix::resize().
Referenced by MatrixCopySparse_g().
MatrixExtractFromTensor3()
void MatrixExtractFromTensor3 (Matrix & out, const Tensor3 & in, const Index & i, const String & direction, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixExtractFromTensor3.
Extracts a Matrix from a Tensor3.
Copies page or row or column with given Index from input Tensor3 variable to output Matrix. Higher order equivalent of VectorExtractFromMatrix.
Author
Jana Mendrok
Parameters
[out] out Generic output
[in] in Generic Input
[in] i Generic Input
[in] direction Generic Input
Definition at line 179 of file m_basic_types.cc.
References joker, ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and Matrix::resize().
Referenced by MatrixExtractFromTensor3_g().
MatrixIdentity()
void MatrixIdentity (Matrix & out, const Index & n, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixIdentity.
Returns an identity matrix.
The size if the matrix created is n x n. Default is to return a true identity matrix (I), but you can also select another value along the diagonal by setting value. That is, the output is value*I.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] n Generic Input
[in] value Generic Input (Default: "1")
Definition at line 376 of file m_basic_types.cc.
References id_mat(), and Matrix::resize().
Referenced by MatrixIdentity_g().
MatrixMatrixMultiply()
void MatrixMatrixMultiply (Matrix & out, const Matrix & m, const Matrix & x, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixMatrixMultiply.
Multiply a Matrix with another Matrix and store the result in the result Matrix.
This just computes the normal Matrix-Matrix product, Y=M*X. It is ok if Y and X are the same Matrix.
Author
Stefan Buehler
Parameters
[out] out Generic output
[in] m Generic Input
[in] x Generic Input
Definition at line 227 of file m_basic_types.cc.
References M, mult(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), and LineShape::Y.
Referenced by MatrixMatrixMultiply_g().
MatrixScale()
void MatrixScale (Matrix & out, const Matrix & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixScale.
Scales all elements of a matrix with the specified value.
The result can either be stored in the same or another variable.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 388 of file m_basic_types.cc.
References ConstMatrixView::ncols(), ConstMatrixView::nrows(), and Matrix::resize().
Referenced by MatrixScale_g().
MatrixSet()
void MatrixSet (Matrix & out, const Matrix & value, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixSet.
Initialize a Matrix from the given list of numbers.
Usage: <br> MatrixSet(m1, [1, 2, 3; 4, 5, 6])
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 406 of file m_basic_types.cc.
References x.
Referenced by MatrixSet_g().
MatrixSetConstant()
void MatrixSetConstant (Matrix & out, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixSetConstant.
Creates a matrix and sets all elements to the specified value.
The size is determined by ncols and nrows.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 411 of file m_basic_types.cc.
References x.
Referenced by MatrixSetConstant_g().
MatrixVectorMultiply()
void MatrixVectorMultiply (Vector & out, const Matrix & m, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixVectorMultiply.
Multiply a Matrix with a Vector
Computes the normal Matrix-Vector product, out=m*v. It is ok if out and v are the same Vector.
Author
Stefan Buehler and Patrick Eriksson
Parameters
[out] out Generic output
[in] m Generic Input
[in] v Generic Input
Definition at line 255 of file m_basic_types.cc.
References M, mult(), ConstVectorView::nelem(), and LineShape::Y.
Referenced by MatrixVectorMultiply_g().
NumericAdd()
void NumericAdd (Numeric & out, const Numeric & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: NumericAdd.
Adds a numeric and a value (out = in+value).
The result can either be stored in the same or another numeric. (in and out can be the same varible, but not out and value)
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 421 of file m_basic_types.cc.
Referenced by NumericAdd_g().
NumericClip()
void NumericClip (Numeric & out, const Numeric & in, const Numeric & limit_low, const Numeric & limit_high, const Verbosity & verbosity)
WORKSPACE METHOD: NumericClip.
Clipping of a numeric.
The input value is copied to the output one (that can be same WSV) but ensures that out is inside the range [limit_low,limit_high]. When the input value is below limit_low, out is set to limit_low. And the same is performed with respect to limit_high.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] limit_low Generic Input (Default: "-Inf")
[in] limit_high Generic Input (Default: "Inf")
Definition at line 429 of file m_basic_types.cc.
Referenced by NumericClip_g().
NumericFromVector()
void NumericFromVector (Numeric & out, const Vector & in, const String & op, const Verbosity & verbosity)
WORKSPACE METHOD: NumericFromVector.
Derivs a numeric from a vector, following selected operation.
The following operations can be selected: <br> first : Selects the first element of the vector. <br> last : Selects the last element of the vector. <br> max : Selects the maximum element of the vector. <br> min : Selects the minimum element of the vector. <br> mean : Calculates the mean of the vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] op Generic Input
Definition at line 443 of file m_basic_types.cc.
References max, mean(), min, and ConstVectorView::nelem().
Referenced by NumericFromVector_g().
NumericInvScale()
void NumericInvScale (Numeric & out, const Numeric & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: NumericInvScale.
Inversely scales/divides a numeric with a value (out = in/value).
The result can either be stored in the same or another numeric. (in and out can be the same varible, but not out and value)
Author
Jana Mendrok
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 466 of file m_basic_types.cc.
Referenced by NumericInvScale_g().
NumericScale()
void NumericScale (Numeric & out, const Numeric & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: NumericScale.
Scales/multiplies a numeric with a value (out = in*value).
The result can either be stored in the same or another numeric. (in and out can be the same varible, but not out and value)
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 474 of file m_basic_types.cc.
Referenced by NumericScale_g().
NumericSet()
void NumericSet (Numeric & out, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: NumericSet.
Sets a numeric workspace variable to the given value.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 482 of file m_basic_types.cc.
References x.
Referenced by NumericSet_g().
PrintPhysicalConstants()
void PrintPhysicalConstants (const Verbosity & verbosity)
WORKSPACE METHOD: PrintPhysicalConstants.
Prints (most) physical constants used in ARTS.
Author
Richard Larsson
Definition at line 3106 of file m_basic_types.cc.
Referenced by PrintPhysicalConstants_g().
QuantumIdentifierSet()
void QuantumIdentifierSet (QuantumIdentifier & out, const String & string_initializer, const Verbosity & verbosity)
WORKSPACE METHOD: QuantumIdentifierSet.
Sets a QuantumIdentifier workspace variable to the given value by converting the input String
Author
Richard Larsson
Parameters
[out] out Generic output
[in] string_initializer Generic Input
Definition at line 487 of file m_basic_types.cc.
References x.
Referenced by ArrayOfQuantumIdentifierSet(), and QuantumIdentifierSet_g().
RationalAdd()
void RationalAdd (Rational & out, const Rational & in, const Rational & value, const Verbosity & verbosity)
WORKSPACE METHOD: RationalAdd.
Adds a Rational and a value (out = in+value).
The result can either be stored in the same or another Rational. (in and out can be the same varible, but not out and value)
Author
Richard Larsson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 503 of file m_basic_types.cc.
Referenced by RationalAdd_g().
RationalInvScale()
void RationalInvScale (Rational & out, const Rational & in, const Rational & value, const Verbosity & verbosity)
WORKSPACE METHOD: RationalInvScale.
Inversely scales/divides a Rational with a value (out = in/value).
The result can either be stored in the same or another Rational. (in and out can be the same varible, but not out and value)
Author
Richard Larsson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 511 of file m_basic_types.cc.
Referenced by RationalInvScale_g().
RationalScale()
void RationalScale (Rational & out, const Rational & in, const Rational & value, const Verbosity & verbosity)
WORKSPACE METHOD: RationalScale.
Scales/multiplies a Rational with a value (out = in*value).
The result can either be stored in the same or another Rational. (in and out can be the same varible, but not out and value)
Author
Richard Larsson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 519 of file m_basic_types.cc.
Referenced by RationalScale_g().
RationalSet()
void RationalSet (Rational & out, const Index & numerator, const Index & denominator, const Verbosity & verbosity)
WORKSPACE METHOD: RationalSet.
Sets a Rational workspace variable to the given value.
Author
Richard Larsson
Parameters
[out] out Generic output
[in] numerator Generic Input
[in] denominator Generic Input (Default: "1")
Definition at line 527 of file m_basic_types.cc.
References x.
Referenced by RationalSet_g().
SparseMatrixIdentity()
void SparseMatrixIdentity (Sparse & out, const Index & n, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: SparseMatrixIdentity.
Returns a sparse dentity matrix.
The size of the matrix created is n x n. Default is to return a true identity matrix (I), but you can also select another value along the diagonal be setting value. That is, the output is value*I.
Author
Simon Pfreundschuh
Parameters
[out] out Generic output
[in] n Generic Input
[in] value Generic Input (Default: "1")
Definition at line 560 of file m_basic_types.cc.
References id_mat(), and Sparse::resize().
Referenced by SparseMatrixIdentity_g().
SparseSparseMultiply()
void SparseSparseMultiply (Sparse & out, const Sparse & m1, const Sparse & m2, const Verbosity & verbosity)
WORKSPACE METHOD: SparseSparseMultiply.
Multiplies a Sparse with another Sparse, result stored in Sparse.
Makes the calculation: out = m1 * m2
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] m1 Generic Input
[in] m2 Generic Input
Definition at line 535 of file m_basic_types.cc.
References M, mult(), Sparse::ncols(), Sparse::nrows(), and LineShape::Y.
Referenced by SparseSparseMultiply_g().
StringSet()
void StringSet (String & out, const String & text, const Verbosity & verbosity)
WORKSPACE METHOD: StringSet.
Sets a String to the given text string.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] text Generic Input
Definition at line 596 of file m_basic_types.cc.
Referenced by StringSet_g().
Tensor3AddScalar()
void Tensor3AddScalar (Tensor3 & out, const Tensor3 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor3AddScalar.
Adds a scalar value to all elements of a tensor3.
The result can either be stored in the same or another variable.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 599 of file m_basic_types.cc.
References ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and Tensor3::resize().
Referenced by Tensor3AddScalar_g().
Tensor3ExtractFromTensor4()
void Tensor3ExtractFromTensor4 (Tensor3 & out, const Tensor4 & in, const Index & i, const String & direction, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor3ExtractFromTensor4.
Extracts a Tensor3 from a Tensor4.
Copies book, page, row or column with given Index from input Tensor4 variable to output Tensor3. Higher order equivalent of VectorExtractFromMatrix.
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] in Generic Input
[in] i Generic Input
[in] direction Generic Input
Definition at line 666 of file m_basic_types.cc.
References joker, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor3::resize().
Referenced by Tensor3ExtractFromTensor4_g().
Tensor3FromVector()
void Tensor3FromVector (Tensor3 & out, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor3FromVector.
Forms a Tensor3 of size nx1x1 from a vector of length n.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] v Generic Input
Definition at line 617 of file m_basic_types.cc.
References joker, Tensor3::resize(), and v().
Referenced by Tensor3FromVector_g().
Tensor3Scale()
void Tensor3Scale (Tensor3 & out, const Tensor3 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor3Scale.
Scales all elements of a tensor with the specified value.
The result can either be stored in the same or another variable.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 629 of file m_basic_types.cc.
References ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and Tensor3::resize().
Referenced by Tensor3Scale_g().
Tensor3SetConstant()
void Tensor3SetConstant (Tensor3 & out, const Index & npages, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor3SetConstant.
Creates a tensor and sets all elements to the specified value.
The size is determined by ncols, nrows etc.
Author
Claudia Emde
Parameters
[out] out Generic output
[in] npages WS Input
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 647 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, and x.
Referenced by Tensor3SetConstant_g().
Tensor4AddScalar()
void Tensor4AddScalar (Tensor4 & out, const Tensor4 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor4AddScalar.
Adds a scalar value to all elements of a tensor4.
The result can either be stored in the same or another variable.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 725 of file m_basic_types.cc.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor4::resize().
Referenced by Tensor4AddScalar_g().
Tensor4Scale()
void Tensor4Scale (Tensor4 & out, const Tensor4 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor4Scale.
Scales all elements of a tensor with the specified value.
The result can either be stored in the same or another variable.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 743 of file m_basic_types.cc.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor4::resize().
Referenced by Tensor4Scale_g().
Tensor4SetConstant()
void Tensor4SetConstant (Tensor4 & out, const Index & nbooks, const Index & npages, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor4SetConstant.
Creates a tensor and sets all elements to the specified value.
The size is determined by ncols, nrows etc.
Author
Claudia Emde
Parameters
[out] out Generic output
[in] nbooks WS Input
[in] npages WS Input
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 761 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, and x.
Referenced by Tensor4SetConstant_g().
Tensor5Scale()
void Tensor5Scale (Tensor5 & out, const Tensor5 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor5Scale.
Scales all elements of a tensor with the specified value.
The result can either be stored in the same or another variable.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 782 of file m_basic_types.cc.
References ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), and Tensor5::resize().
Referenced by Tensor5Scale_g().
Tensor5SetConstant()
void Tensor5SetConstant (Tensor5 & out, const Index & nshelves, const Index & nbooks, const Index & npages, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor5SetConstant.
Creates a tensor and sets all elements to the specified value.
The size is determined by ncols, nrows etc.
Author
Claudia Emde
Parameters
[out] out Generic output
[in] nshelves WS Input
[in] nbooks WS Input
[in] npages WS Input
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 800 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, and x.
Referenced by Tensor5SetConstant_g().
Tensor6Scale()
void Tensor6Scale (Tensor6 & out, const Tensor6 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor6Scale.
Scales all elements of a tensor with the specified value.
The result can either be stored in the same or another variable.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 823 of file m_basic_types.cc.
References ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and Tensor6::resize().
Referenced by Tensor6Scale_g().
Tensor6SetConstant()
void Tensor6SetConstant (Tensor6 & out, const Index & nvitrines, const Index & nshelves, const Index & nbooks, const Index & npages, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor6SetConstant.
Creates a tensor and sets all elements to the specified value.
The size is determined by ncols, nrows etc.
Author
Claudia Emde
Parameters
[out] out Generic output
[in] nvitrines WS Input
[in] nshelves WS Input
[in] nbooks WS Input
[in] npages WS Input
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 846 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, and x.
Referenced by Tensor6SetConstant_g().
Tensor7Scale()
void Tensor7Scale (Tensor7 & out, const Tensor7 & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor7Scale.
Scales all elements of a tensor with the specified value.
The result can either be stored in the same or another variable.
Author
Mattias Ekstrom
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 871 of file m_basic_types.cc.
References ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and Tensor7::resize().
Referenced by Tensor7Scale_g().
Tensor7SetConstant()
void Tensor7SetConstant (Tensor7 & out, const Index & nlibraries, const Index & nvitrines, const Index & nshelves, const Index & nbooks, const Index & npages, const Index & nrows, const Index & ncols, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: Tensor7SetConstant.
Creates a tensor and sets all elements to the specified value.
The size is determined by ncols, nrows etc.
Author
Claudia Emde
Parameters
[out] out Generic output
[in] nlibraries WS Input
[in] nvitrines WS Input
[in] nshelves WS Input
[in] nbooks WS Input
[in] npages WS Input
[in] nrows WS Input
[in] ncols WS Input
[in] value Generic Input
Definition at line 895 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, and x.
Referenced by Tensor7SetConstant_g().
Trapz()
void Trapz (Numeric & out, const Vector & x, const Vector & y, const Verbosity & verbosity)
WORKSPACE METHOD: Trapz.
Intregrates a vector of over its grid range
The method integrates y(x) by the trapezoidal method.
The vector x is the positions where the integrand, y, is known.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] x Generic Input
[in] y Generic Input
Definition at line 922 of file m_basic_types.cc.
References ConstVectorView::nelem(), and x.
Referenced by Trapz_g().
VectorAddScalar()
void VectorAddScalar (Vector & out, const Vector & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: VectorAddScalar.
Adds a scalar to all elements of a vector.
The result can either be stored in the same or another vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 937 of file m_basic_types.cc.
References ConstVectorView::nelem(), and Vector::resize().
Referenced by VectorAddScalar_g().
VectorAddVector()
void VectorAddVector (Vector & c, const Vector & a, const Vector & b, const Verbosity & verbosity)
WORKSPACE METHOD: VectorAddVector.
Element-wise addition of two vectors.
The method calculates c = a + b.
The variable b is allowed to have length 1, for any length of a*. This single value in b is then added to every element of a.
The vectors a and c can be the same WSV, while b can not be the same WSV as any of the the other vector.
Author
Patrick Eriksson
Parameters
[out] c Generic output
[in] a Generic Input
[in] b Generic Input
Definition at line 955 of file m_basic_types.cc.
References a, b, and c.
Referenced by VectorAddVector_g().
VectorClip()
void VectorClip (Vector & out, const Vector & in, const Numeric & limit_low, const Numeric & limit_high, const Verbosity & verbosity)
WORKSPACE METHOD: VectorClip.
Clipping of a vector.
The input vector is copied to the output one (that can be same WSV) but ensures that all values in out are inside the range [limit_low, limit_high]. Where the input vector is below limit_low, out is set to limit_low. And the same is performed with respect to limit_high. That is, the method works as NumericClip for each element of the vector.
The method adopts the length of out when needed.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] limit_low Generic Input (Default: "-Inf")
[in] limit_high Generic Input (Default: "Inf")
Definition at line 1033 of file m_basic_types.cc.
References Interpolation::l(), ConstVectorView::nelem(), and Vector::resize().
Referenced by VectorClip_g().
VectorCrop()
void VectorCrop (Vector & out, const Vector & in, const Numeric & min_value, const Numeric & max_value, const Verbosity & verbosity)
WORKSPACE METHOD: VectorCrop.
Keeps only values of a vector inside the specified range.
All values outside the range [min_value,max-value] are removed. Note the default values, that basically should act as -+Inf.
The result can either be stored in the same or another vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] min_value Generic Input (Default: "-99e99")
[in] max_value Generic Input (Default: "99e99")
Definition at line 1053 of file m_basic_types.cc.
References c, ConstVectorView::nelem(), and Vector::resize().
Referenced by VectorCrop_g().
VectorExtractFromMatrix()
void VectorExtractFromMatrix (Vector & out, const Matrix & in, const Index & i, const String & direction, const Verbosity & verbosity)
WORKSPACE METHOD: VectorExtractFromMatrix.
Extracts a Vector from a Matrix.
Copies row or column with given Index from input Matrix variable to create output Vector.
Author
Patrick Eriksson, Oliver Lemke, Stefan Buehler
Parameters
[out] out Generic output
[in] in Generic Input
[in] i Generic Input
[in] direction Generic Input
Definition at line 1090 of file m_basic_types.cc.
References joker, ConstMatrixView::ncols(), ConstMatrixView::nrows(), and v().
Referenced by VectorExtractFromMatrix_g().
VectorFlip()
void VectorFlip (Vector & out, const Vector & in, const Verbosity & verbosity)
WORKSPACE METHOD: VectorFlip.
Flips a vector.
The output is the input vector in reversed order. The result can either be stored in the same or another vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
Definition at line 1128 of file m_basic_types.cc.
References ConstVectorView::nelem(), Vector::resize(), and v().
Referenced by VectorFlip_g().
VectorInsertGridPoints()
void VectorInsertGridPoints (Vector & out, const Vector & in, const Vector & points, const Verbosity & verbosity)
WORKSPACE METHOD: VectorInsertGridPoints.
Insert some additional points into a grid.
This method can for example be used to add line center frequencies to a regular frequency grid. If the original grid is [1,2,3], and the additional points are [2.2,2.4], the result will be [1,2,2.2,2.4,3].
It is assumed that the original grid is sorted, otherwise a runtime error is thrown. The vector with the points to insert does not have to be sorted. If some of the input points are already in the grid, these points are not inserted again. New points outside the original grid are appended at the appropriate end. Input vector and output vector can be the same.
Generic output: <br> Vector : The new grid vector.
Generic input: <br> Vector : The original grid vector. <br> Vector : The points to insert.
Author
Stefan Buehler
Parameters
[out] out Generic output
[in] in Generic Input
[in] points Generic Input
Definition at line 1144 of file m_basic_types.cc.
References ARTS_ASSERT, arts_exit(), CREATE_OUT2, CREATE_OUT3, get_sorted_indexes(), is_decreasing(), is_increasing(), ConstVectorView::nelem(), Vector::resize(), and x.
Referenced by choose_abs_nls_pert(), and VectorInsertGridPoints_g().
VectorLinSpace()
void VectorLinSpace (Vector & out, const Numeric & start, const Numeric & stop, const Numeric & step, const Verbosity & verbosity)
WORKSPACE METHOD: VectorLinSpace.
Initializes a vector with linear spacing.
The first element equals always the start value, and the spacing equals always the step value, but the last value can deviate from the stop value. step can be both positive and negative.
The created vector is [start, start+step, start+2*step, ...] <br>
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] start Generic Input
[in] stop Generic Input
[in] step Generic Input
Definition at line 1248 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, linspace(), Zeeman::start(), and x.
Referenced by VectorLinSpace_g().
VectorLogSpace()
void VectorLogSpace (Vector & out, const Numeric & start, const Numeric & stop, const Numeric & step, const Verbosity & verbosity)
WORKSPACE METHOD: VectorLogSpace.
Initializes a vector with logarithmic spacing.
The first element equals always the start value, and the spacing equals always the step value, but note that the last value can deviate from the stop value. The keyword step can be both positive and negative.
Note, that although start has to be given in direct coordinates, step has to be given in log coordinates.
Explicitly, the vector is: <br> exp([ln(start), ln(start)+step, ln(start)+2*step, ...])
Author
Stefan Buehler
Parameters
[out] out Generic output
[in] start Generic Input
[in] stop Generic Input
[in] step Generic Input
Definition at line 1269 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, linspace(), Zeeman::start(), transform(), and x.
Referenced by VectorLogSpace_g().
VectorMatrixMultiply()
void VectorMatrixMultiply (Vector & out, const Matrix & m, const Vector & v, const Verbosity & verbosity)
WORKSPACE METHOD: VectorMatrixMultiply.
Multiply a Vector with a Matrix and store the result in another Vector.
This just computes the normal Matrix-Vector product, y=M*x. It is ok if input and output Vector are the same. This function is handy for multiplying the H Matrix to spectra.
Author
Stefan Buehler
Parameters
[out] out Generic output
[in] m Generic Input
[in] v Generic Input
Definition at line 1291 of file m_basic_types.cc.
References M, mult(), ConstVectorView::nelem(), Vector::resize(), and x.
Referenced by VectorMatrixMultiply_g().
VectorNLinSpace()
void VectorNLinSpace (Vector & out, const Index & nelem, const Numeric & start, const Numeric & stop, const Verbosity & verbosity)
WORKSPACE METHOD: VectorNLinSpace.
Creates a vector with length nelem, equally spaced between the given end values.
The length (nelem) must be larger than 1.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] start Generic Input
[in] stop Generic Input
Definition at line 1317 of file m_basic_types.cc.
References CREATE_OUT2, CREATE_OUT3, nlinspace(), Zeeman::start(), and x.
Referenced by test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), VectorNLinSpace_g(), and VectorNLinSpaceConst().
VectorNLogSpace()
void VectorNLogSpace (Vector & out, const Index & nelem, const Numeric & start, const Numeric & stop, const Verbosity & verbosity)
WORKSPACE METHOD: VectorNLogSpace.
Creates a vector with length nelem, equally logarithmically spaced between the given end values.
The length (nelem) must be larger than 1.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] start Generic Input
[in] stop Generic Input
Definition at line 1354 of file m_basic_types.cc.
Referenced by antenna_responseVaryingGaussian(), main(), test28(), VectorNLogSpace_g(), ybatchMetProfiles(), and ybatchMetProfilesClear().
VectorPower()
void VectorPower (Vector & out, const Vector & in, const Numeric & power, const Verbosity & verbosity)
WORKSPACE METHOD: VectorPower.
Calculates the power of each element in a vector.
The result can either be stored in the same or another vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] power Generic Input
Definition at line 1377 of file m_basic_types.cc.
Referenced by VectorPower_g().
VectorReshapeMatrix()
void VectorReshapeMatrix (Vector & out, const Matrix & in, const String & direction, const Verbosity & verbosity)
WORKSPACE METHOD: VectorReshapeMatrix.
Converts a Matrix to a Vector.
The matrix is reshaped into a vector. That is, all elements of the matrix are kept. The elements can be extracted both in column (default) and row order. The ouput vector has the same length for both options.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] direction Generic Input (Default: "column")
Definition at line 1394 of file m_basic_types.cc.
Referenced by VectorReshapeMatrix_g().
VectorScale()
void VectorScale (Vector & out, const Vector & in, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: VectorScale.
Scales all elements of a vector with the same value.
The result can either be stored in the same or another vector.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] in Generic Input
[in] value Generic Input
Definition at line 1428 of file m_basic_types.cc.
Referenced by VectorScale_g().
VectorSet()
void VectorSet (Vector & out, const Vector & value, const Verbosity & verbosity)
WORKSPACE METHOD: VectorSet.
Create a vector from the given list of numbers.
<br> VectorSet(p_grid, [1000, 100, 10]) <br> Will create a p_grid vector with these three elements.
Author
Stefan Buehler
Parameters
[out] out Generic output
[in] value Generic Input
Definition at line 1478 of file m_basic_types.cc.
Referenced by ARTS::Agenda::geo_pos_agenda_empty(), main(), and VectorSet_g().
VectorSetConstant()
void VectorSetConstant (Vector & out, const Index & nelem, const Numeric & value, const Verbosity & verbosity)
WORKSPACE METHOD: VectorSetConstant.
Creates a vector and sets all elements to the specified value.
The vector length is determined by nelem.
Author
Patrick Eriksson
Parameters
[out] out Generic output
[in] nelem WS Input
[in] value Generic Input
Definition at line 1446 of file m_basic_types.cc.
Referenced by VectorSetConstant_g().
VectorSubtractVector()
void VectorSubtractVector (Vector & c, const Vector & a, const Vector & b, const Verbosity & verbosity)
WORKSPACE METHOD: VectorSubtractVector.
Element-wise subtraction of two vectors.
The method calculates c = a - b.
The variable b is allowed to have length 1, for any length of a*. This single value in b is then added to every element of a.
The vectors a and c can be the same WSV, while b can not be the same WSV as any of the the other vector.
Author
Patrick Eriksson
Parameters
[out] c Generic output
[in] a Generic Input
[in] b Generic Input
Definition at line 994 of file m_basic_types.cc.
References a, b, and c.
Referenced by VectorSubtractVector_g().
VectorVectorMultiply()
void VectorVectorMultiply (Vector & out, const Vector & v1, const Vector & v2, const Verbosity & verbosity)
WORKSPACE METHOD: VectorVectorMultiply.
Multiply a Vector with another Vector and store result in a third one.
This is an element-wise multiplication. It is ok if output Vector is the same as any of the input Vectors.
Author
Jana Mendrok
Parameters
[out] out Generic output
[in] v1 Generic Input
[in] v2 Generic Input
Definition at line 1483 of file m_basic_types.cc.
Referenced by VectorVectorMultiply_g().