ARTS: m_cloudradar.cc File Reference
m_cloudradar.cc File Reference
Workspace functions related to simulation of cloud radars.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "auto_md.h"
#include "logic.h"
#include "messages.h"
#include "montecarlo.h"
#include "propagationmatrix.h"
#include "rte.h"
#include "sensor.h"
Functions
void iyActiveSingleScat (Workspace &ws, Matrix &iy, ArrayOfMatrix &iy_aux, ArrayOfTensor3 &diy_dx, Vector &ppvar_p, Vector &ppvar_t, EnergyLevelMap &ppvar_nlte, Matrix &ppvar_vmr, Matrix &ppvar_wind, Matrix &ppvar_mag, Matrix &ppvar_pnd, Matrix &ppvar_f, Tensor4 &ppvar_trans_cumulat, const Index &stokes_dim, const Vector &f_grid, const Index &atmosphere_dim, const Vector &p_grid, const Tensor3 &t_field, const EnergyLevelMap &nlte_field, const Tensor4 &vmr_field, const ArrayOfArrayOfSpeciesTag &abs_species, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Tensor3 &mag_u_field, const Tensor3 &mag_v_field, const Tensor3 &mag_w_field, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfTensor4 &dpnd_field_dx, const ArrayOfString &scat_species, const ArrayOfArrayOfSingleScatteringData &scat_data, const Index &scat_data_checked, const ArrayOfString &iy_aux_vars, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const Ppath &ppath, const Agenda &propmat_clearsky_agenda, const Agenda &water_p_eq_agenda, const Agenda &iy_transmitter_agenda, const Index &iy_agenda_call1, const Tensor3 &iy_transmittance, const Numeric &rte_alonglos_v, const Index &trans_in_jacobian, const Numeric &pext_scaling, const Index &t_interp_order, const Verbosity &verbosity)
WORKSPACE METHOD: iyActiveSingleScat.
void iyActiveSingleScat2 (Workspace &ws, Matrix &iy, ArrayOfMatrix &iy_aux, ArrayOfTensor3 &diy_dx, Vector &ppvar_p, Vector &ppvar_t, EnergyLevelMap &ppvar_nlte, Matrix &ppvar_vmr, Matrix &ppvar_wind, Matrix &ppvar_mag, Matrix &ppvar_pnd, Matrix &ppvar_f, Tensor4 &ppvar_trans_cumulat, const Index &stokes_dim, const Vector &f_grid, const Index &atmosphere_dim, const Vector &p_grid, const Tensor3 &t_field, const EnergyLevelMap &nlte_field, const Tensor4 &vmr_field, const ArrayOfArrayOfSpeciesTag &abs_species, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Tensor3 &mag_u_field, const Tensor3 &mag_v_field, const Tensor3 &mag_w_field, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfTensor4 &dpnd_field_dx, const ArrayOfString &scat_species, const ArrayOfArrayOfSingleScatteringData &scat_data, const Index &scat_data_checked, const ArrayOfString &iy_aux_vars, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const Ppath &ppath, const Agenda &propmat_clearsky_agenda, const Agenda &water_p_eq_agenda, const Agenda &iy_transmitter_agenda, const Index &iy_agenda_call1, const Tensor3 &iy_transmittance, const Numeric &rte_alonglos_v, const Index &trans_in_jacobian, const Numeric &pext_scaling, const Index &t_interp_order, const Verbosity &verbosity)
WORKSPACE METHOD: iyActiveSingleScat2.
void yActive (Workspace &ws, Vector &y, Vector &y_f, ArrayOfIndex &y_pol, Matrix &y_pos, Matrix &y_los, ArrayOfVector &y_aux, Matrix &y_geo, Matrix &jacobian, const Index &atmgeom_checked, const Index &atmfields_checked, const String &iy_unit, const ArrayOfString &iy_aux_vars, const Index &stokes_dim, const Vector &f_grid, const Index &atmosphere_dim, const EnergyLevelMap &nlte_field, const Index &cloudbox_on, const Index &cloudbox_checked, const Matrix &sensor_pos, const Matrix &sensor_los, const Index &sensor_checked, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const Agenda &iy_main_agenda, const Agenda &geo_pos_agenda, const ArrayOfArrayOfIndex &instrument_pol_array, const Vector &range_bins, const Numeric &ze_tref, const Numeric &k2, const Numeric &dbze_min, const Verbosity &)
WORKSPACE METHOD: yActive.
Variables
const Numeric PI
const Numeric SPEED_OF_LIGHT
Detailed Description
Workspace functions related to simulation of cloud radars.
Author
Patrick Eriksson patri.nosp@m.ck.e.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2010-10-31
Definition in file m_cloudradar.cc.
Function Documentation
iyActiveSingleScat()
void iyActiveSingleScat (Workspace & ws, Matrix & iy, ArrayOfMatrix & iy_aux, ArrayOfTensor3 & diy_dx, Vector & ppvar_p, Vector & ppvar_t, EnergyLevelMap & ppvar_nlte, Matrix & ppvar_vmr, Matrix & ppvar_wind, Matrix & ppvar_mag, Matrix & ppvar_pnd, Matrix & ppvar_f, Tensor4 & ppvar_trans_cumulat, const Index & stokes_dim, const Vector & f_grid, const Index & atmosphere_dim, const Vector & p_grid, const Tensor3 & t_field, const EnergyLevelMap & nlte_field, const Tensor4 & vmr_field, const ArrayOfArrayOfSpeciesTag & abs_species, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Tensor3 & mag_u_field, const Tensor3 & mag_v_field, const Tensor3 & mag_w_field, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfTensor4 & dpnd_field_dx, const ArrayOfString & scat_species, const ArrayOfArrayOfSingleScatteringData & scat_data, const Index & scat_data_checked, const ArrayOfString & iy_aux_vars, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const Ppath & ppath, const Agenda & propmat_clearsky_agenda, const Agenda & water_p_eq_agenda, const Agenda & iy_transmitter_agenda, const Index & iy_agenda_call1, const Tensor3 & iy_transmittance, const Numeric & rte_alonglos_v, const Index & trans_in_jacobian, const Numeric & pext_scaling, const Index & t_interp_order, const Verbosity & verbosity)
WORKSPACE METHOD: iyActiveSingleScat.
Simulation of radar/lidar, restricted to single scattering.
The WSM treats e.g. radar measurements of cloud and precipitation, on the condition that multiple scattering can be ignored. Beside the direct backsacttering, the two-way attenuation by gases and particles is considered. Surface scattering is ignored.
The method could potentially be used for lidars, but multiple scattering poses here a must stronger constrain for the range of applications.
The method can be used with iyCalc, but not with yCalc. In the later case, use instead yActive.
The method returns the backscattering for each point of ppath. Several frequencies can be treated in parallel. The size of iy is [ nf*np, stokes_dim ], where nf is the length of f_grid and np is the number of path points. The data are stored in blocks of [ np, stokes_dim ]. That is, all the results for the first frequency occupy the np first rows of iy etc.
The polarisation state of the transmitted pulse is taken from iy_transmitter_agenda*. If the radar transmits several polarisations at the same frequency, you need to handle this by using two frequencies in f_grid, but these can be almost identical.
This method does not consider iy_unit. Unit changes are insted applied in *yActive. The output of this method matches the option "1".
Transmittance is handled in a slightly simplified manner for efficiency reasons. First of all, the transmittance matrix is assumed to be the same in both directions between the sensor and the point of back-scattering. This should in general be true, but exceptions could exist. The extinction due to particles can also be scaled, which could be of interest when e.g. characterising inversions.
Further, for Jacobian calculations the default is to assume that the transmittance is unaffected by the retrieval quantities. This is done to save computational time, and should be a valid approximation for the single-scattering conditions. Set trans_in_jacobian to 1 to obtain the more accurate Jacobian.
Some auxiliary radiative transfer quantities can be obtained. Auxiliary quantities are selected by iy_aux_vars and returned by iy_aux. Valid choices for auxiliary data are: <br> "Radiative background": Index value flagging the radiative <br> background. The following coding is used: 0=space, 1=surface <br> and 2=cloudbox. <br> "Backscattering": The unattenuated backscattering. That is, as <br> iy but with no attenuated applied. Here all columns are filled. <br> "Optical depth": Scalar, total and two-way, optical depth between <br> sensor and each point of the propagation path. Calculated based on <br> the (1,1)-element of the transmittance matrix (1-based indexing), <br> i.e. only fully valid for scalar RT. <br> "Particle extinction": As "Optical depth", but only with particle <br> attenuation included. That is, gas absorption is ignored. If nothing else is stated, only the first column of iy_aux is filled, i.e. the column matching Stokes element I, while remaing columns are are filled with zeros.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_aux WS Output
[in,out] diy_dx WS Input/Output
[out] ppvar_p WS Output
[out] ppvar_t WS Output
[out] ppvar_nlte WS Output
[out] ppvar_vmr WS Output
[out] ppvar_wind WS Output
[out] ppvar_mag WS Output
[out] ppvar_pnd WS Output
[out] ppvar_f WS Output
[out] ppvar_trans_cumulat WS Output
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] t_field WS Input
[in] nlte_field WS Input
[in] vmr_field WS Input
[in] abs_species WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] mag_u_field WS Input
[in] mag_v_field WS Input
[in] mag_w_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] pnd_field WS Input
[in] dpnd_field_dx WS Input
[in] scat_species WS Input
[in] scat_data WS Input
[in] scat_data_checked WS Input
[in] iy_aux_vars WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] ppath WS Input
[in] propmat_clearsky_agenda WS Input
[in] water_p_eq_agenda WS Input
[in] iy_transmitter_agenda WS Input
[in] iy_agenda_call1 WS Input
[in] iy_transmittance WS Input
[in] rte_alonglos_v WS Input
[in] trans_in_jacobian Generic Input (Default: "0")
[in] pext_scaling Generic Input (Default: "1")
[in] t_interp_order Generic Input (Default: "1")
Definition at line 48 of file m_cloudradar.cc.
References abs, ARTS::Var::abs_species(), adapt_stepwise_partial_derivatives(), ARTS::Var::atmosphere_dim(), chk_if_in_range(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::dpnd_field_dx(), ARTS::Var::f_grid(), FOR_ANALYTICAL_JACOBIANS_DO, get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_stepwise_clearsky_propmat(), get_stepwise_scattersky_propmat(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), ARTS::Var::jacobian_do(), ARTS::Var::jacobian_quantities(), joker, ARTS::Var::mag_u_field(), ARTS::Var::mag_v_field(), ARTS::Var::mag_w_field(), min, ConstMatrixView::ncols(), ARTS::Var::nlte_field(), ConstMatrixView::nrows(), ns, ARTS::Var::p_grid(), ARTS::Var::pnd_field(), ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), ppath_what_background(), ARTS::Var::ppvar_f(), ARTS::Var::ppvar_mag(), ARTS::Var::ppvar_nlte(), ARTS::Var::ppvar_p(), ARTS::Var::ppvar_pnd(), ARTS::Var::ppvar_t(), ARTS::Var::ppvar_trans_cumulat(), ARTS::Var::ppvar_vmr(), ARTS::Var::ppvar_wind(), ARTS::Var::propmat_clearsky_agenda(), Vector::resize(), Tensor5::resize(), ARTS::Var::rte_alonglos_v(), rtmethods_jacobian_init(), ARTS::Var::scat_data(), ARTS::Var::scat_data_checked(), ARTS::Var::scat_species(), ARTS::Var::stokes_dim(), ARTS::Var::t_field(), TotalNumberOfElements(), ARTS::Var::vmr_field(), ARTS::Var::wind_u_field(), ARTS::Var::wind_v_field(), and ARTS::Var::wind_w_field().
Referenced by iyActiveSingleScat_g().
iyActiveSingleScat2()
void iyActiveSingleScat2 (Workspace & ws, Matrix & iy, ArrayOfMatrix & iy_aux, ArrayOfTensor3 & diy_dx, Vector & ppvar_p, Vector & ppvar_t, EnergyLevelMap & ppvar_nlte, Matrix & ppvar_vmr, Matrix & ppvar_wind, Matrix & ppvar_mag, Matrix & ppvar_pnd, Matrix & ppvar_f, Tensor4 & ppvar_trans_cumulat, const Index & stokes_dim, const Vector & f_grid, const Index & atmosphere_dim, const Vector & p_grid, const Tensor3 & t_field, const EnergyLevelMap & nlte_field, const Tensor4 & vmr_field, const ArrayOfArrayOfSpeciesTag & abs_species, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Tensor3 & mag_u_field, const Tensor3 & mag_v_field, const Tensor3 & mag_w_field, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfTensor4 & dpnd_field_dx, const ArrayOfString & scat_species, const ArrayOfArrayOfSingleScatteringData & scat_data, const Index & scat_data_checked, const ArrayOfString & iy_aux_vars, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const Ppath & ppath, const Agenda & propmat_clearsky_agenda, const Agenda & water_p_eq_agenda, const Agenda & iy_transmitter_agenda, const Index & iy_agenda_call1, const Tensor3 & iy_transmittance, const Numeric & rte_alonglos_v, const Index & trans_in_jacobian, const Numeric & pext_scaling, const Index & t_interp_order, const Verbosity & verbosity)
WORKSPACE METHOD: iyActiveSingleScat2.
TESTING
Author
Patrick Eriksson
Richard Larsson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_aux WS Output
[in,out] diy_dx WS Input/Output
[out] ppvar_p WS Output
[out] ppvar_t WS Output
[out] ppvar_nlte WS Output
[out] ppvar_vmr WS Output
[out] ppvar_wind WS Output
[out] ppvar_mag WS Output
[out] ppvar_pnd WS Output
[out] ppvar_f WS Output
[out] ppvar_trans_cumulat WS Output
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] t_field WS Input
[in] nlte_field WS Input
[in] vmr_field WS Input
[in] abs_species WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] mag_u_field WS Input
[in] mag_v_field WS Input
[in] mag_w_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] pnd_field WS Input
[in] dpnd_field_dx WS Input
[in] scat_species WS Input
[in] scat_data WS Input
[in] scat_data_checked WS Input
[in] iy_aux_vars WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] ppath WS Input
[in] propmat_clearsky_agenda WS Input
[in] water_p_eq_agenda WS Input
[in] iy_transmitter_agenda WS Input
[in] iy_agenda_call1 WS Input
[in] iy_transmittance WS Input
[in] rte_alonglos_v WS Input
[in] trans_in_jacobian Generic Input (Default: "0")
[in] pext_scaling Generic Input (Default: "1")
[in] t_interp_order Generic Input (Default: "1")
Definition at line 679 of file m_cloudradar.cc.
References abs, ARTS::Var::abs_species(), adapt_stepwise_partial_derivatives(), ARTS::Var::atmosphere_dim(), chk_if_in_range(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::dpnd_field_dx(), ARTS::Var::f_grid(), FOR_ANALYTICAL_JACOBIANS_DO, get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_stepwise_clearsky_propmat(), get_stepwise_scattersky_propmat(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), ARTS::Var::jacobian_do(), ARTS::Var::jacobian_quantities(), joker, ARTS::Var::mag_u_field(), ARTS::Var::mag_v_field(), ARTS::Var::mag_w_field(), min, ConstMatrixView::ncols(), ARTS::Var::nlte_field(), ConstMatrixView::nrows(), ns, ARTS::Var::p_grid(), ARTS::Var::pnd_field(), ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), ppath_what_background(), ARTS::Var::ppvar_f(), ARTS::Var::ppvar_mag(), ARTS::Var::ppvar_nlte(), ARTS::Var::ppvar_p(), ARTS::Var::ppvar_pnd(), ARTS::Var::ppvar_t(), ARTS::Var::ppvar_trans_cumulat(), ARTS::Var::ppvar_vmr(), ARTS::Var::ppvar_wind(), ARTS::Var::propmat_clearsky_agenda(), Vector::resize(), ARTS::Var::rte_alonglos_v(), rtmethods_jacobian_init(), ARTS::Var::scat_data(), ARTS::Var::scat_data_checked(), ARTS::Var::scat_species(), ARTS::Var::stokes_dim(), ARTS::Var::t_field(), Jacobian::Temperature, TotalNumberOfElements(), ARTS::Var::vmr_field(), ARTS::Var::wind_u_field(), ARTS::Var::wind_v_field(), and ARTS::Var::wind_w_field().
Referenced by iyActiveSingleScat2_g().
yActive()
void yActive (Workspace & ws, Vector & y, Vector & y_f, ArrayOfIndex & y_pol, Matrix & y_pos, Matrix & y_los, ArrayOfVector & y_aux, Matrix & y_geo, Matrix & jacobian, const Index & atmgeom_checked, const Index & atmfields_checked, const String & iy_unit, const ArrayOfString & iy_aux_vars, const Index & stokes_dim, const Vector & f_grid, const Index & atmosphere_dim, const EnergyLevelMap & nlte_field, const Index & cloudbox_on, const Index & cloudbox_checked, const Matrix & sensor_pos, const Matrix & sensor_los, const Index & sensor_checked, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const Agenda & iy_main_agenda, const Agenda & geo_pos_agenda, const ArrayOfArrayOfIndex & instrument_pol_array, const Vector & range_bins, const Numeric & ze_tref, const Numeric & k2, const Numeric & dbze_min, const Verbosity & verbosity)
WORKSPACE METHOD: yActive.
Replaces yCalc for radar/lidar calculations.
The output format for iy when simulating radars and lidars differs from the standard one, and yCalc can not be used for such simulations. This method works largely as yCalc, but is tailored to handle the output from iyActiveSingleScat.
The method requires additional information about the sensor, regarding its recieving properties. First of all, recieved polarisation states are taken from instrument_pol_array. Note that this WSV allows to define several measured polarisations for each transmitted signal. For example, it is possible to simulate transmittance of V and measuring backsacttered V and H.
Secondly, the range averaging is described by range_bins. These bins can either be specified in altitude or two-way travel time. In both case, the edges of the range bins shall be specified. All data (including auxiliary variables) are returned as the average inside the bins. If a bin is totally outside the model atmosphere, NaN is returned.
The options for iy_unit are: <br> "1" : Backscatter coefficient. Unit is 1/(m*sr). At zero <br> attenuation, this equals the scattering matrix value for <br> the backward direction. See further AUG. <br> "Ze" : Equivalent reflectivity. Unit is mm^6/m^3. Conversion <br> formula is given below. <br> "dBZe": 10*log10(Ze/Z0), where Z0 is 1 mm^6/m^3.
The conversion from backscatter coefficient to Ze is: <br> Ze = 1e18 * lambda^4 / (k2 * pi^5) * sum(sigma), where sum(sigma) = 4 * pi * b, and b is the backscatter coefficient.
The reference dielectric factor can either specified directly by the argument k2. For example, to mimic the CloudSat data, k2 shall be set to 0.75 (citaion needed). If k2 is set to be negative (which is defualt), k2 is calculated as: <br> k2 = abs((n^2-1)/(n^2+2))^2, where n is the refractive index of liquid water at temperature ze_tref* and the frequency of the radar, calculated by the MPM93 parameterization.
A lower limit for dBZe is applied (dbze_min). The main reason is to handle the fact dBZe is not defined for Ze=0, and dBZe is set to the clip value when Ze < 10^(dbze_min/10).
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] y WS Output
[out] y_f WS Output
[out] y_pol WS Output
[out] y_pos WS Output
[out] y_los WS Output
[out] y_aux WS Output
[out] y_geo WS Output
[out] jacobian WS Output
[in] atmgeom_checked WS Input
[in] atmfields_checked WS Input
[in] iy_unit WS Input
[in] iy_aux_vars WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] atmosphere_dim WS Input
[in] nlte_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_checked WS Input
[in] sensor_pos WS Input
[in] sensor_los WS Input
[in] sensor_checked WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] iy_main_agenda WS Input
[in] geo_pos_agenda WS Input
[in] instrument_pol_array WS Input
[in] range_bins WS Input
[in] ze_tref Generic Input (Default: "273.15")
[in] k2 Generic Input (Default: "-1")
[in] dbze_min Generic Input (Default: "-99")
Definition at line 1189 of file m_cloudradar.cc.
References ARTS::Var::atmfields_checked(), ARTS::Var::atmgeom_checked(), chk_if_in_range(), chk_if_increasing(), ARTS::Var::cloudbox_checked(), ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), error_if_limb_ppath(), ARTS::Var::f_grid(), FOR_ANALYTICAL_JACOBIANS_DO, ARTS::Var::instrument_pol_array(), integration_bin_by_vecmult(), is_increasing(), ARTS::Var::iy(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_unit(), jac_ranges_indices(), ARTS::Var::jacobian(), ARTS::Var::jacobian_do(), ARTS::Var::jacobian_quantities(), joker, max, min, mult(), Array< base >::nelem(), ARTS::Var::nlte_field(), ARTS::Var::npages(), ARTS::Var::Ppath::pos(), pow(), ARTS::Var::ppath(), ARTS::Var::range_bins(), ARTS::Var::rte_pos2(), ARTS::Var::sensor_checked(), ARTS::Var::sensor_los(), ARTS::Var::sensor_pos(), SPEED_OF_LIGHT, stokes2pol(), ARTS::Var::stokes_dim(), ARTS::Var::y(), ARTS::Var::y_aux(), ARTS::Var::y_f(), ARTS::Var::y_geo(), ARTS::Var::y_los(), ARTS::Var::y_pol(), ARTS::Var::y_pos(), and ze_cfac().
Referenced by yActive_g().
Variable Documentation
PI
const Numeric PI extern
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by yActive().