ARTS: m_conversion.h File Reference
m_conversion.h File Reference
Implementation of unit conversion functions.
Functions
void FrequencyFromWavelength (Numeric &frequency, const Numeric &wavelength, const Verbosity &)
WORKSPACE METHOD: FrequencyFromWavelength.
void FrequencyFromWavelength (Vector &frequency, const Vector &wavelength, const Verbosity &)
WORKSPACE METHOD: FrequencyFromWavelength.
void FrequencyFromCGSAngularWavenumber (Numeric &frequency, const Numeric &angular_wavenumber, const Verbosity &)
WORKSPACE METHOD: FrequencyFromCGSAngularWavenumber.
void FrequencyFromCGSAngularWavenumber (Vector &frequency, const Vector &angular_wavenumber, const Verbosity &)
WORKSPACE METHOD: FrequencyFromCGSAngularWavenumber.
void FrequencyFromCGSKayserWavenumber (Numeric &frequency, const Numeric &kayser_wavenumber, const Verbosity &)
WORKSPACE METHOD: FrequencyFromCGSKayserWavenumber.
void FrequencyFromCGSKayserWavenumber (Vector &frequency, const Vector &kayser_wavenumber, const Verbosity &)
WORKSPACE METHOD: FrequencyFromCGSKayserWavenumber.
Variables
const Numeric SPEED_OF_LIGHT
const Numeric PI
Detailed Description
Implementation of unit conversion functions.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@l.nosp@m.mu.d.nosp@m.e
Date
2010-07-21
Definition in file m_conversion.h.
Function Documentation
FrequencyFromCGSAngularWavenumber() [1/2]
void FrequencyFromCGSAngularWavenumber (Numeric & frequency, const Numeric & angular_wavenumber, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromCGSAngularWavenumber.
Convert from angular wavenumber [cm^-1] to frequency [Hz].
This converts angular wavenumber (2*PI/wavelength) into frequency.
Author
Richard Larsson
Parameters
[out] frequency Supergeneric output
[in] angular_wavenumber Generic Input
Definition at line 56 of file m_conversion.h.
References PI, and SPEED_OF_LIGHT.
Referenced by FrequencyFromCGSAngularWavenumber_sg_NumericNumeric_g(), and FrequencyFromCGSAngularWavenumber_sg_VectorVector_g().
FrequencyFromCGSAngularWavenumber() [2/2]
void FrequencyFromCGSAngularWavenumber (Vector & frequency, const Vector & angular_wavenumber, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromCGSAngularWavenumber.
Convert from angular wavenumber [cm^-1] to frequency [Hz].
This converts angular wavenumber (2*PI/wavelength) into frequency.
Author
Richard Larsson
Parameters
[out] frequency Supergeneric output
[in] angular_wavenumber Generic Input
Definition at line 65 of file m_conversion.h.
References ConstVectorView::nelem(), PI, Vector::resize(), and SPEED_OF_LIGHT.
FrequencyFromCGSKayserWavenumber() [1/2]
void FrequencyFromCGSKayserWavenumber (Numeric & frequency, const Numeric & kayser_wavenumber, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromCGSKayserWavenumber.
Convert from Kayser wavenumber [cm^-1] to frequency [Hz].
This converts Kayser wavenumber (1/wavelength) into frequency.
Author
Richard Larsson
Parameters
[out] frequency Supergeneric output
[in] kayser_wavenumber Generic Input
Definition at line 77 of file m_conversion.h.
References SPEED_OF_LIGHT.
Referenced by FrequencyFromCGSKayserWavenumber_sg_NumericNumeric_g(), and FrequencyFromCGSKayserWavenumber_sg_VectorVector_g().
FrequencyFromCGSKayserWavenumber() [2/2]
void FrequencyFromCGSKayserWavenumber (Vector & frequency, const Vector & kayser_wavenumber, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromCGSKayserWavenumber.
Convert from Kayser wavenumber [cm^-1] to frequency [Hz].
This converts Kayser wavenumber (1/wavelength) into frequency.
Author
Richard Larsson
Parameters
[out] frequency Supergeneric output
[in] kayser_wavenumber Generic Input
Definition at line 86 of file m_conversion.h.
References ConstVectorView::nelem(), Vector::resize(), and SPEED_OF_LIGHT.
FrequencyFromWavelength() [1/2]
void FrequencyFromWavelength (Numeric & frequency, const Numeric & wavelength, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromWavelength.
Convert from wavelength [m] to frequency [Hz].
This is a generic method. It can take a single wavelength value or a wavelength vector as input.
Author
Claudia Emde
Parameters
[out] frequency Supergeneric output
[in] wavelength Generic Input
Definition at line 34 of file m_conversion.h.
References SPEED_OF_LIGHT.
Referenced by FrequencyFromWavelength_sg_NumericNumeric_g(), and FrequencyFromWavelength_sg_VectorVector_g().
FrequencyFromWavelength() [2/2]
void FrequencyFromWavelength (Vector & frequency, const Vector & wavelength, const Verbosity & verbosity) inline
WORKSPACE METHOD: FrequencyFromWavelength.
Convert from wavelength [m] to frequency [Hz].
This is a generic method. It can take a single wavelength value or a wavelength vector as input.
Author
Claudia Emde
Parameters
[out] frequency Supergeneric output
[in] wavelength Generic Input
Definition at line 44 of file m_conversion.h.
References ConstVectorView::nelem(), Vector::resize(), and SPEED_OF_LIGHT.
Variable Documentation
PI
const Numeric PI extern
Referenced by FrequencyFromCGSAngularWavenumber().
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by FrequencyFromCGSAngularWavenumber(), FrequencyFromCGSKayserWavenumber(), and FrequencyFromWavelength().