ARTS: m_copy.h File Reference
m_copy.h File Reference
Implementation of Copy.
#include "agenda_class.h"
#include "messages.h"
#include "mystring.h"
#include "workspace_ng.h"
Functions
template<class T >
void Copy (T &out, const String &, const T &in, const String &, const Verbosity &)
WORKSPACE METHOD: Copy.
void Copy (Workspace &ws, Agenda &out, const String &out_name, const Agenda &in, const String &, const Verbosity &verbosity)
void Copy (Workspace &ws, ArrayOfAgenda &out, const String &out_name, const ArrayOfAgenda &in, const String &, const Verbosity &verbosity)
Detailed Description
Implementation of Copy.
Implementation of Select.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Copy.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2008-08-27
This file contains the implementation of the supergeneric method Select.
Definition in file m_copy.h.
Function Documentation
Copy() [1/3]
template<class T > void Copy (T & out, const String & out_wsvname, const T & in, const String & in_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Copy.
Copy a workspace variable.
This method can copy any workspace variable to another workspace variable of the same group. (E.g., a Matrix to another Matrix.)
As always, output comes first in the argument list!
Usage example:
Copy(f_grid, p_grid)
Will copy the content of p_grid to f_grid. The size of f_grid is adjusted automatically (the normal behaviour for workspace methods).
Author
Stefan Buehler
Parameters
[out] out Supergeneric output
[in] out_wsvname Generic Output Name
[in] in Generic Input
[in] in_wsvname Generic Input Name
Definition at line 39 of file m_copy.h.
Referenced by Copy_sg_AbsorptionLines_g(), Copy_sg_Agenda_g(), Copy_sg_ArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfAgenda_g(), Copy_sg_ArrayOfArrayOfAbsorptionLines_g(), Copy_sg_ArrayOfArrayOfGriddedField1_g(), Copy_sg_ArrayOfArrayOfGriddedField2_g(), Copy_sg_ArrayOfArrayOfGriddedField3_g(), Copy_sg_ArrayOfArrayOfIndex_g(), Copy_sg_ArrayOfArrayOfMatrix_g(), Copy_sg_ArrayOfArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfArrayOfRadiationVector_g(), Copy_sg_ArrayOfArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfArrayOfSpeciesTag_g(), Copy_sg_ArrayOfArrayOfStokesVector_g(), Copy_sg_ArrayOfArrayOfString_g(), Copy_sg_ArrayOfArrayOfTensor3_g(), Copy_sg_ArrayOfArrayOfTensor6_g(), Copy_sg_ArrayOfArrayOfTime_g(), Copy_sg_ArrayOfArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfArrayOfVector_g(), Copy_sg_ArrayOfCIARecord_g(), Copy_sg_ArrayOfGriddedField1_g(), Copy_sg_ArrayOfGriddedField2_g(), Copy_sg_ArrayOfGriddedField3_g(), Copy_sg_ArrayOfGriddedField4_g(), Copy_sg_ArrayOfIndex_g(), Copy_sg_ArrayOfJacobianTarget_g(), Copy_sg_ArrayOfMatrix_g(), Copy_sg_ArrayOfPpath_g(), Copy_sg_ArrayOfPropagationMatrix_g(), Copy_sg_ArrayOfQuantumIdentifier_g(), Copy_sg_ArrayOfRadiationVector_g(), Copy_sg_ArrayOfRetrievalQuantity_g(), Copy_sg_ArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfSparse_g(), Copy_sg_ArrayOfStokesVector_g(), Copy_sg_ArrayOfString_g(), Copy_sg_ArrayOfTelsemAtlas_g(), Copy_sg_ArrayOfTensor3_g(), Copy_sg_ArrayOfTensor4_g(), Copy_sg_ArrayOfTensor5_g(), Copy_sg_ArrayOfTensor6_g(), Copy_sg_ArrayOfTensor7_g(), Copy_sg_ArrayOfTime_g(), Copy_sg_ArrayOfTransmissionMatrix_g(), Copy_sg_ArrayOfVector_g(), Copy_sg_ArrayOfXsecRecord_g(), Copy_sg_CIARecord_g(), Copy_sg_CovarianceMatrix_g(), Copy_sg_EnergyLevelMap_g(), Copy_sg_GasAbsLookup_g(), Copy_sg_GriddedField1_g(), Copy_sg_GriddedField2_g(), Copy_sg_GriddedField3_g(), Copy_sg_GriddedField4_g(), Copy_sg_GriddedField5_g(), Copy_sg_GriddedField6_g(), Copy_sg_GridPos_g(), Copy_sg_HitranRelaxationMatrixData_g(), Copy_sg_Index_g(), Copy_sg_JacobianTarget_g(), Copy_sg_Matrix_g(), Copy_sg_MCAntenna_g(), Copy_sg_Numeric_g(), Copy_sg_Ppath_g(), Copy_sg_PropagationMatrix_g(), Copy_sg_QuantumIdentifier_g(), Copy_sg_RadiationVector_g(), Copy_sg_Rational_g(), Copy_sg_ScatteringMetaData_g(), Copy_sg_SingleScatteringData_g(), Copy_sg_Sparse_g(), Copy_sg_SpeciesAuxData_g(), Copy_sg_StokesVector_g(), Copy_sg_String_g(), Copy_sg_TelsemAtlas_g(), Copy_sg_Tensor3_g(), Copy_sg_Tensor4_g(), Copy_sg_Tensor5_g(), Copy_sg_Tensor6_g(), Copy_sg_Tensor7_g(), Copy_sg_TessemNN_g(), Copy_sg_Time_g(), Copy_sg_Timer_g(), Copy_sg_TransmissionMatrix_g(), Copy_sg_Vector_g(), and Copy_sg_Verbosity_g().
Copy() [2/3]
void Copy (Workspace & ws, Agenda & out, const String & out_name, const Agenda & in, const String & , const Verbosity & verbosity) inline
Definition at line 50 of file m_copy.h.
References Agenda::check(), Agenda::set_name(), and ARTS::Var::verbosity().
Copy() [3/3]
void Copy (Workspace & ws, ArrayOfAgenda & out, const String & out_name, const ArrayOfAgenda & in, const String & , const Verbosity & verbosity) inline
Definition at line 64 of file m_copy.h.
References ARTS::Var::verbosity().