ARTS: m_delete.h File Reference
m_delete.h File Reference
Implementation of Delete.
#include <map>
#include "mystring.h"
#include "workspace_ng.h"
Functions
template<typename T >
void Delete (Workspace &ws, const T &x, const String &x_name, const Verbosity &)
WORKSPACE METHOD: Delete.
Detailed Description
Implementation of Delete.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2007-11-26
This file contains the implementation of the supergeneric method Delete.
Definition in file m_delete.h.
Function Documentation
Delete()
template<typename T > void Delete (Workspace & ws, const T & v, const String & v_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: Delete.
Deletes a workspace variable.
The variable is marked as uninitialized and its memory freed. It is not removed from the workspace though, therefore you don't need to/can't call Create for this variable again.
Author
Oliver Lemke
Parameters
[in,out] ws Workspace
[in] v Generic Input
[in] v_wsvname Generic Input Name
Definition at line 39 of file m_delete.h.
References Workspace::del(), and Workspace::WsvMap.
Referenced by Delete_sg_AbsorptionLines_g(), Delete_sg_Agenda_g(), Delete_sg_ArrayOfAbsorptionLines_g(), Delete_sg_ArrayOfAgenda_g(), Delete_sg_ArrayOfArrayOfAbsorptionLines_g(), Delete_sg_ArrayOfArrayOfGriddedField1_g(), Delete_sg_ArrayOfArrayOfGriddedField2_g(), Delete_sg_ArrayOfArrayOfGriddedField3_g(), Delete_sg_ArrayOfArrayOfIndex_g(), Delete_sg_ArrayOfArrayOfMatrix_g(), Delete_sg_ArrayOfArrayOfPropagationMatrix_g(), Delete_sg_ArrayOfArrayOfRadiationVector_g(), Delete_sg_ArrayOfArrayOfScatteringMetaData_g(), Delete_sg_ArrayOfArrayOfSingleScatteringData_g(), Delete_sg_ArrayOfArrayOfSpeciesTag_g(), Delete_sg_ArrayOfArrayOfStokesVector_g(), Delete_sg_ArrayOfArrayOfString_g(), Delete_sg_ArrayOfArrayOfTensor3_g(), Delete_sg_ArrayOfArrayOfTensor6_g(), Delete_sg_ArrayOfArrayOfTime_g(), Delete_sg_ArrayOfArrayOfTransmissionMatrix_g(), Delete_sg_ArrayOfArrayOfVector_g(), Delete_sg_ArrayOfCIARecord_g(), Delete_sg_ArrayOfGriddedField1_g(), Delete_sg_ArrayOfGriddedField2_g(), Delete_sg_ArrayOfGriddedField3_g(), Delete_sg_ArrayOfGriddedField4_g(), Delete_sg_ArrayOfIndex_g(), Delete_sg_ArrayOfJacobianTarget_g(), Delete_sg_ArrayOfMatrix_g(), Delete_sg_ArrayOfPpath_g(), Delete_sg_ArrayOfPropagationMatrix_g(), Delete_sg_ArrayOfQuantumIdentifier_g(), Delete_sg_ArrayOfRadiationVector_g(), Delete_sg_ArrayOfRetrievalQuantity_g(), Delete_sg_ArrayOfScatteringMetaData_g(), Delete_sg_ArrayOfSingleScatteringData_g(), Delete_sg_ArrayOfSparse_g(), Delete_sg_ArrayOfStokesVector_g(), Delete_sg_ArrayOfString_g(), Delete_sg_ArrayOfTelsemAtlas_g(), Delete_sg_ArrayOfTensor3_g(), Delete_sg_ArrayOfTensor4_g(), Delete_sg_ArrayOfTensor5_g(), Delete_sg_ArrayOfTensor6_g(), Delete_sg_ArrayOfTensor7_g(), Delete_sg_ArrayOfTime_g(), Delete_sg_ArrayOfTransmissionMatrix_g(), Delete_sg_ArrayOfVector_g(), Delete_sg_ArrayOfXsecRecord_g(), Delete_sg_CIARecord_g(), Delete_sg_CovarianceMatrix_g(), Delete_sg_EnergyLevelMap_g(), Delete_sg_GasAbsLookup_g(), Delete_sg_GriddedField1_g(), Delete_sg_GriddedField2_g(), Delete_sg_GriddedField3_g(), Delete_sg_GriddedField4_g(), Delete_sg_GriddedField5_g(), Delete_sg_GriddedField6_g(), Delete_sg_GridPos_g(), Delete_sg_HitranRelaxationMatrixData_g(), Delete_sg_Index_g(), Delete_sg_JacobianTarget_g(), Delete_sg_Matrix_g(), Delete_sg_MCAntenna_g(), Delete_sg_Numeric_g(), Delete_sg_Ppath_g(), Delete_sg_PropagationMatrix_g(), Delete_sg_QuantumIdentifier_g(), Delete_sg_RadiationVector_g(), Delete_sg_Rational_g(), Delete_sg_ScatteringMetaData_g(), Delete_sg_SingleScatteringData_g(), Delete_sg_Sparse_g(), Delete_sg_SpeciesAuxData_g(), Delete_sg_StokesVector_g(), Delete_sg_String_g(), Delete_sg_TelsemAtlas_g(), Delete_sg_Tensor3_g(), Delete_sg_Tensor4_g(), Delete_sg_Tensor5_g(), Delete_sg_Tensor6_g(), Delete_sg_Tensor7_g(), Delete_sg_TessemNN_g(), Delete_sg_Time_g(), Delete_sg_Timer_g(), Delete_sg_TransmissionMatrix_g(), Delete_sg_Vector_g(), and Delete_sg_Verbosity_g().