ARTS: m_extract.h File Reference
m_extract.h File Reference
Implementation of Extract.
#include "array.h"
#include "exceptions.h"
#include "gridded_fields.h"
#include "matpackV.h"
#include "quantum.h"
Functions
template<typename T >
void Extract (T &e, const Array< T > &arr, const Index &index, const Verbosity &)
void ArrayOfIndexExtractFromArrayOfArrayOfIndex (ArrayOfIndex &aoi, const ArrayOfArrayOfIndex &aoaoi, const Index &index, const Verbosity &)
void Extract (Numeric &n, const Vector &v, const Index &index, const Verbosity &)
void Extract (Matrix &m, const Tensor3 &t3, const Index &index, const Verbosity &)
void Extract (Tensor3 &t3, const Tensor4 &t4, const Index &index, const Verbosity &)
void Extract (Tensor4 &t4, const Tensor5 &t5, const Index &index, const Verbosity &)
void Extract (ArrayOfGriddedField3 &agf, const ArrayOfArrayOfGriddedField3 &aagf, const Index &index, const Verbosity &)
void Extract (GriddedField4 &m, const ArrayOfGriddedField4 &agf4, const Index &index, const Verbosity &)
void Extract (QuantumIdentifier &qi, const ArrayOfQuantumIdentifier &aoqi, const Index &index, const Verbosity &)
Detailed Description
Implementation of Extract.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2008-10-08
This file contains the implementation of the supergeneric method Extract.
Definition in file m_extract.h.
Function Documentation
ArrayOfIndexExtractFromArrayOfArrayOfIndex()
void ArrayOfIndexExtractFromArrayOfArrayOfIndex (ArrayOfIndex & aoi, const ArrayOfArrayOfIndex & aoaoi, const Index & index, const Verbosity &) inline
Definition at line 62 of file m_extract.h.
References Array< base >::nelem(), and Absorption::nelem().
Extract() [1/8]
void Extract (ArrayOfGriddedField3 & agf, const ArrayOfArrayOfGriddedField3 & aagf, const Index & index, const Verbosity &) inline
Definition at line 159 of file m_extract.h.
References Array< base >::nelem(), and Absorption::nelem().
Extract() [2/8]
void Extract (GriddedField4 & m, const ArrayOfGriddedField4 & agf4, const Index & index, const Verbosity &) inline
Definition at line 183 of file m_extract.h.
References Array< base >::nelem().
Extract() [3/8]
void Extract (Matrix & m, const Tensor3 & t3, const Index & index, const Verbosity &) inline
Definition at line 99 of file m_extract.h.
References joker, and ConstTensor3View::npages().
Extract() [4/8]
void Extract (Numeric & n, const Vector & v, const Index & index, const Verbosity &) inline
Definition at line 81 of file m_extract.h.
References v.
Extract() [5/8]
void Extract (QuantumIdentifier & qi, const ArrayOfQuantumIdentifier & aoqi, const Index & index, const Verbosity &) inline
Definition at line 204 of file m_extract.h.
References Array< base >::nelem().
Extract() [6/8]
template<typename T > void Extract (T & e, const Array< T > & arr, const Index & index, const Verbosity &)
Definition at line 44 of file m_extract.h.
Referenced by Extract_sg_ArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Extract_sg_ArrayOfIndexArrayOfArrayOfIndex_g(), Extract_sg_ArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Extract_sg_GriddedField3ArrayOfGriddedField3_g(), Extract_sg_GriddedField4ArrayOfGriddedField4_g(), Extract_sg_IndexArrayOfIndex_g(), Extract_sg_MatrixArrayOfMatrix_g(), Extract_sg_MatrixTensor3_g(), Extract_sg_NumericVector_g(), Extract_sg_QuantumIdentifierArrayOfQuantumIdentifier_g(), Extract_sg_SingleScatteringDataArrayOfSingleScatteringData_g(), Extract_sg_StringArrayOfString_g(), Extract_sg_TelsemAtlasArrayOfTelsemAtlas_g(), Extract_sg_Tensor3Tensor4_g(), Extract_sg_Tensor4ArrayOfTensor4_g(), Extract_sg_Tensor4Tensor5_g(), and Extract_sg_VectorArrayOfVector_g().
Extract() [7/8]
void Extract (Tensor3 & t3, const Tensor4 & t4, const Index & index, const Verbosity &) inline
Definition at line 117 of file m_extract.h.
References joker, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor3::resize().
Extract() [8/8]
void Extract (Tensor4 & t4, const Tensor5 & t5, const Index & index, const Verbosity &) inline
Definition at line 136 of file m_extract.h.
References joker, ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), and Tensor4::resize().