ARTS: m_fos.cc File Reference
m_fos.cc File Reference
Workspace functions associated with the FOS scattering scheme.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "arts_omp.h"
#include "auto_md.h"
#include "doit.h"
#include "m_xml.h"
#include "math_funcs.h"
#include "montecarlo.h"
#include "rte.h"
Functions
void iyHybrid (Workspace &ws, Matrix &iy, ArrayOfMatrix &iy_aux, ArrayOfTensor3 &diy_dx, Vector &ppvar_p, Vector &ppvar_t, EnergyLevelMap &ppvar_nlte, Matrix &ppvar_vmr, Matrix &ppvar_wind, Matrix &ppvar_mag, Matrix &ppvar_pnd, Matrix &ppvar_f, Tensor3 &ppvar_iy, Tensor4 &ppvar_trans_cumulat, const Index &iy_id, const Index &stokes_dim, const Vector &f_grid, const Index &atmosphere_dim, const Vector &p_grid, const Tensor3 &t_field, const EnergyLevelMap &nlte_field, const Tensor4 &vmr_field, const ArrayOfArrayOfSpeciesTag &abs_species, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Tensor3 &mag_u_field, const Tensor3 &mag_v_field, const Tensor3 &mag_w_field, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfTensor4 &dpnd_field_dx, const ArrayOfString &scat_species, const ArrayOfArrayOfSingleScatteringData &scat_data, const String &iy_unit, const ArrayOfString &iy_aux_vars, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const Agenda &propmat_clearsky_agenda, const Agenda &water_p_eq_agenda, const String &rt_integration_option, const Agenda &iy_main_agenda, const Agenda &iy_space_agenda, const Agenda &iy_surface_agenda, const Agenda &iy_cloudbox_agenda, const Index &iy_agenda_call1, const Tensor3 &iy_transmittance, const Ppath &ppath, const Vector &rte_pos2, const Numeric &rte_alonglos_v, const Tensor3 &surface_props_data, const Tensor7 &cloudbox_field, const Vector &za_grid, const Index &Naa, const Index &t_interp_order, const Verbosity &verbosity)
WORKSPACE METHOD: iyHybrid.
Variables
const Numeric DEG2RAD
const Numeric RAD2DEG
const Numeric PI
Detailed Description
Workspace functions associated with the FOS scattering scheme.
Author
Patrick Eriksson patri.nosp@m.ck.e.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2013-04-29
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_fos.cc.
Function Documentation
iyHybrid()
void iyHybrid (Workspace & ws, Matrix & iy, ArrayOfMatrix & iy_aux, ArrayOfTensor3 & diy_dx, Vector & ppvar_p, Vector & ppvar_t, EnergyLevelMap & ppvar_nlte, Matrix & ppvar_vmr, Matrix & ppvar_wind, Matrix & ppvar_mag, Matrix & ppvar_pnd, Matrix & ppvar_f, Tensor3 & ppvar_iy, Tensor4 & ppvar_trans_cumulat, const Index & iy_id, const Index & stokes_dim, const Vector & f_grid, const Index & atmosphere_dim, const Vector & p_grid, const Tensor3 & t_field, const EnergyLevelMap & nlte_field, const Tensor4 & vmr_field, const ArrayOfArrayOfSpeciesTag & abs_species, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Tensor3 & mag_u_field, const Tensor3 & mag_v_field, const Tensor3 & mag_w_field, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfTensor4 & dpnd_field_dx, const ArrayOfString & scat_species, const ArrayOfArrayOfSingleScatteringData & scat_data, const String & iy_unit, const ArrayOfString & iy_aux_vars, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const Agenda & propmat_clearsky_agenda, const Agenda & water_p_eq_agenda, const String & rt_integration_option, const Agenda & iy_main_agenda, const Agenda & iy_space_agenda, const Agenda & iy_surface_agenda, const Agenda & iy_cloudbox_agenda, const Index & iy_agenda_call1, const Tensor3 & iy_transmittance, const Ppath & ppath, const Vector & rte_pos2, const Numeric & rte_alonglos_v, const Tensor3 & surface_props_data, const Tensor7 & cloudbox_field, const Vector & za_grid, const Index & Naa_grid, const Index & t_interp_order, const Verbosity & verbosity)
WORKSPACE METHOD: iyHybrid.
So far just for testing.
Author
Patrick Eriksson
Jana Mendrok
Richard Larsson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_aux WS Output
[in,out] diy_dx WS Input/Output
[out] ppvar_p WS Output
[out] ppvar_t WS Output
[out] ppvar_nlte WS Output
[out] ppvar_vmr WS Output
[out] ppvar_wind WS Output
[out] ppvar_mag WS Output
[out] ppvar_pnd WS Output
[out] ppvar_f WS Output
[out] ppvar_iy WS Output
[out] ppvar_trans_cumulat WS Output
[in] iy_id WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] t_field WS Input
[in] nlte_field WS Input
[in] vmr_field WS Input
[in] abs_species WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] mag_u_field WS Input
[in] mag_v_field WS Input
[in] mag_w_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] pnd_field WS Input
[in] dpnd_field_dx WS Input
[in] scat_species WS Input
[in] scat_data WS Input
[in] iy_unit WS Input
[in] iy_aux_vars WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] propmat_clearsky_agenda WS Input
[in] water_p_eq_agenda WS Input
[in] rt_integration_option WS Input
[in] iy_main_agenda WS Input
[in] iy_space_agenda WS Input
[in] iy_surface_agenda WS Input
[in] iy_cloudbox_agenda WS Input
[in] iy_agenda_call1 WS Input
[in] iy_transmittance WS Input
[in] ppath WS Input
[in] rte_pos2 WS Input
[in] rte_alonglos_v WS Input
[in] surface_props_data WS Input
[in] cloudbox_field WS Input
[in] za_grid WS Input
[in] Naa_grid Generic Input (Default: "19")
[in] t_interp_order Generic Input (Default: "1")
Definition at line 858 of file m_fos.cc.
References ARTS::Var::aa_grid(), ARTS::Var::abs_species(), adapt_stepwise_partial_derivatives(), ARTS::Var::atmosphere_dim(), ARTS::Var::cloudbox_field(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), cumulative_transmission(), ARTS::Var::diy_dx(), do_temperature_jacobian(), ARTS::Var::dpnd_field_dx(), Emission, ARTS::Var::f_grid(), FOR_ANALYTICAL_JACOBIANS_DO, Forward, get_iy_of_background(), get_pointers_for_analytical_species(), get_pointers_for_scat_species(), get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_standard_diy_dpath(), get_standard_starting_diy_dx(), get_stepwise_blackbody_radiation(), get_stepwise_clearsky_propmat(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), ARTS::Var::iy(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_cloudbox_agenda(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), ARTS::Var::iy_space_agenda(), ARTS::Var::iy_surface_agenda(), iy_transmittance_mult(), ARTS::Var::iy_unit(), iyEmissionStandard(), ARTS::Var::jacobian_do(), ARTS::Var::jacobian_quantities(), joker, ARTS::Var::mag_u_field(), ARTS::Var::mag_v_field(), ARTS::Var::mag_w_field(), min, Array< base >::nelem(), nlinspace(), ARTS::Var::nlte_field(), ns, ARTS::Var::p_grid(), ARTS::Var::pnd_field(), ARTS::Var::ppath(), ppath_what_background(), ARTS::Var::ppvar_f(), ARTS::Var::ppvar_iy(), ARTS::Var::ppvar_mag(), ARTS::Var::ppvar_nlte(), ARTS::Var::ppvar_p(), ARTS::Var::ppvar_pnd(), ARTS::Var::ppvar_t(), ARTS::Var::ppvar_trans_cumulat(), ARTS::Var::ppvar_vmr(), ARTS::Var::ppvar_wind(), ARTS::Var::propmat_clearsky_agenda(), Vector::resize(), ARTS::Var::rte_alonglos_v(), ARTS::Var::rte_pos2(), rtmethods_jacobian_finalisation(), rtmethods_unit_conversion(), ARTS::Var::scat_data(), ARTS::Var::scat_species(), stepwise_source(), stepwise_transmission(), ARTS::Var::stokes_dim(), ARTS::Var::surface_props_data(), swap(), ARTS::Var::t_field(), Jacobian::Temperature, update_radiation_vector(), verbosity, ARTS::Var::vmr_field(), ARTS::Var::water_p_eq_agenda(), ARTS::Var::wind_u_field(), ARTS::Var::wind_v_field(), ARTS::Var::wind_w_field(), and ARTS::Var::za_grid().
Referenced by iyHybrid_g().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
PI
const Numeric PI extern
RAD2DEG
const Numeric RAD2DEG extern