ARTS: m_geodetic.cc File Reference
m_geodetic.cc File Reference
Workspace functions of geodetic character.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "auto_md.h"
#include "check_input.h"
#include "geodetic.h"
#include "matpackI.h"
#include "messages.h"
Functions
void refellipsoidForAzimuth (Vector &refellipsoid, const Numeric &latitude, const Numeric &azimuth, const Verbosity &)
WORKSPACE METHOD: refellipsoidForAzimuth.
void refellipsoidOrbitPlane (Vector &refellipsoid, const Numeric &orbitinc, const Verbosity &)
WORKSPACE METHOD: refellipsoidOrbitPlane.
void refellipsoidSet (Vector &refellipsoid, const Numeric &re, const Numeric &e, const Verbosity &)
WORKSPACE METHOD: refellipsoidSet.
void rte_poslosFromECEF (Vector &rte_pos, Vector &rte_los, const Matrix &sensor_pos_ecef, const Matrix &sensor_los_ecef, const Vector &refellipsoid, const Verbosity &v)
WORKSPACE METHOD: rte_poslosFromECEF.
void rte_poslosFromGeodetic (Vector &rte_pos, Vector &rte_los, const Matrix &sensor_pos_geodetic, const Matrix &sensor_los_geodetic, const Vector &refellipsoid, const Verbosity &v)
WORKSPACE METHOD: rte_poslosFromGeodetic.
void sensor_poslosFromECEF (Matrix &sensor_pos, Matrix &sensor_los, const Matrix &sensor_pos_ecef, const Matrix &sensor_los_ecef, const Vector &refellipsoid, const Verbosity &)
WORKSPACE METHOD: sensor_poslosFromECEF.
void sensor_poslosFromGeodetic (Matrix &sensor_pos, Matrix &sensor_los, const Matrix &sensor_pos_geodetic, const Matrix &sensor_los_geodetic, const Vector &refellipsoid, const Verbosity &)
WORKSPACE METHOD: sensor_poslosFromGeodetic.
void y_geoToGeodetic (Matrix &y_geo, const Vector &refellipsoid, const Verbosity &)
WORKSPACE METHOD: y_geoToGeodetic.
Variables
const Numeric DEG2RAD
Detailed Description
Workspace functions of geodetic character.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2012-02-06
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_geodetic.cc.
Function Documentation
refellipsoidForAzimuth()
void refellipsoidForAzimuth (Vector & refellipsoid, const Numeric & latitude, const Numeric & azimuth, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidForAzimuth.
Conversion of 3D ellipsoid to 1D curvature radius.
Calculates the curvature radius for the given latitude and azimuth angle, and uses this to set a spherical reference ellipsoid suitable for 1D calculations. The curvature radius is a better local approximation than using the local ellipsoid radius.
The used expression assumes a geodetic latitude, but also latitudes should be OK as using this method anyhow signifies an approximation.
Author
Patrick Eriksson
Parameters
[in,out] refellipsoid WS Input/Output
[in] latitude Generic Input
[in] azimuth Generic Input
Definition at line 54 of file m_geodetic.cc.
References a, ARTS_USER_ERROR_IF, DEG2RAD, pow(), ARTS::Var::refellipsoid(), sqrt(), and v.
Referenced by refellipsoidForAzimuth_g().
refellipsoidOrbitPlane()
void refellipsoidOrbitPlane (Vector & refellipsoid, const Numeric & orbitinc, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidOrbitPlane.
Conversion of 3D ellipsoid to 2D orbit track geometry.
Determines an approximate reference ellipsoid following an orbit track. The new ellipsoid is determined simply, by determining the radius at the maximum latitude and from this value calculate a new new eccentricity. The orbit is specified by giving the orbit inclination (orbitinc), that is normally a value around 100 deg for polar sun-synchronous orbits.
Author
Patrick Eriksson
Parameters
[in,out] refellipsoid WS Input/Output
[in] orbitinc Generic Input
Definition at line 79 of file m_geodetic.cc.
References ARTS_USER_ERROR_IF, chk_if_in_range(), pow(), refell2r(), ARTS::Var::refellipsoid(), and sqrt().
Referenced by refellipsoidOrbitPlane_g().
refellipsoidSet()
void refellipsoidSet (Vector & refellipsoid, const Numeric & re, const Numeric & e, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidSet.
Manual setting of the reference ellipsoid.
The two values of refellipsoid can here be set manually. The two arguments correspond directly to first and second element of refellipsoid*.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] re Generic Input
[in] e Generic Input (Default: "0")
Definition at line 96 of file m_geodetic.cc.
Referenced by refellipsoidSet_g().
rte_poslosFromECEF()
void rte_poslosFromECEF (Vector & rte_pos, Vector & rte_los, const Matrix & sensor_pos_ecef, const Matrix & sensor_los_ecef, const Vector & refellipsoid, const Verbosity & verbosity)
WORKSPACE METHOD: rte_poslosFromECEF.
Converts sensor position and LOS from ECEF to geocentric values.
Works exactly as sensor_poslosFromECEF but places the output in rte_pos and rte_los. Accordingly, the input can only cover one combination of position and LOS.
Author
Patrick Eriksson
Parameters
[out] rte_pos WS Output
[out] rte_los WS Output
[in] sensor_pos_ecef WS Input
[in] sensor_los_ecef WS Input
[in] refellipsoid WS Input
Definition at line 109 of file m_geodetic.cc.
References ARTS_USER_ERROR_IF, joker, ARTS::Var::refellipsoid(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), ARTS::Var::sensor_los(), ARTS::Var::sensor_los_ecef(), ARTS::Var::sensor_pos(), ARTS::Var::sensor_pos_ecef(), sensor_poslosFromECEF(), and v.
Referenced by rte_poslosFromECEF_g().
rte_poslosFromGeodetic()
void rte_poslosFromGeodetic (Vector & rte_pos, Vector & rte_los, const Matrix & sensor_pos_geodetic, const Matrix & sensor_los_geodetic, const Vector & refellipsoid, const Verbosity & verbosity)
WORKSPACE METHOD: rte_poslosFromGeodetic.
Converts sensor position and LOS from geodetic to geocentric values.
Works exactly as sensor_poslosFromGeodetic but places the output in rte_pos and rte_los. Accordingly, the input can only cover one combination of position and LOS.
Author
Patrick Eriksson
Parameters
[out] rte_pos WS Output
[out] rte_los WS Output
[in] sensor_pos_geodetic WS Input
[in] sensor_los_geodetic WS Input
[in] refellipsoid WS Input
Definition at line 135 of file m_geodetic.cc.
References ARTS_USER_ERROR_IF, joker, ARTS::Var::refellipsoid(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), ARTS::Var::sensor_los(), ARTS::Var::sensor_los_geodetic(), ARTS::Var::sensor_pos(), ARTS::Var::sensor_pos_geodetic(), sensor_poslosFromGeodetic(), and v.
Referenced by rte_poslosFromGeodetic_g().
sensor_poslosFromECEF()
void sensor_poslosFromECEF (Matrix & sensor_pos, Matrix & sensor_los, const Matrix & sensor_pos_ecef, const Matrix & sensor_los_ecef, const Vector & refellipsoid, const Verbosity & verbosity)
WORKSPACE METHOD: sensor_poslosFromECEF.
Converts sensor position and LOS from ECEF to geocentric values.
The geodetic position and line-of-sight (LOS) are defined by sensor_pos_ecef* and sensor_los_ecef. The later WSV is here allowed to be empty (but gives an empty sensor_los). Otherwise the number of rows in the two WSVs must agree.
So far only 3D is handled.
Author
Patrick Eriksson
Parameters
[out] sensor_pos WS Output
[out] sensor_los WS Output
[in] sensor_pos_ecef WS Input
[in] sensor_los_ecef WS Input
[in] refellipsoid WS Input
Definition at line 161 of file m_geodetic.cc.
References ARTS_USER_ERROR_IF, cart2poslos_plain(), cart2sph_plain(), ARTS::Var::ncols(), ARTS::Var::nrows(), refell2r(), ARTS::Var::refellipsoid(), ARTS::Var::sensor_los(), ARTS::Var::sensor_los_ecef(), ARTS::Var::sensor_pos(), and ARTS::Var::sensor_pos_ecef().
Referenced by rte_poslosFromECEF(), and sensor_poslosFromECEF_g().
sensor_poslosFromGeodetic()
void sensor_poslosFromGeodetic (Matrix & sensor_pos, Matrix & sensor_los, const Matrix & sensor_pos_geodetic, const Matrix & sensor_los_geodetic, const Vector & refellipsoid, const Verbosity & verbosity)
WORKSPACE METHOD: sensor_poslosFromGeodetic.
Converts sensor position and LOS from geodetic to geocentric values.
The geodetic position and line-of-sight (LOS) are defined by sensor_pos_geodetic* and sensor_los_geodetic. The later WSV is here allowed to be empty (but gives an empty sensor_los). Otherwise the number of rows in the two WSVs must agree.
So far only 3D is handled.
Author
Patrick Eriksson
Parameters
[out] sensor_pos WS Output
[out] sensor_los WS Output
[in] sensor_pos_geodetic WS Input
[in] sensor_los_geodetic WS Input
[in] refellipsoid WS Input
Definition at line 219 of file m_geodetic.cc.
References ARTS_USER_ERROR_IF, ARTS::Var::ncols(), ARTS::Var::nrows(), ARTS::Var::refellipsoid(), and ARTS::Var::sensor_pos_geodetic().
Referenced by rte_poslosFromGeodetic(), and sensor_poslosFromGeodetic_g().
y_geoToGeodetic()
void y_geoToGeodetic (Matrix & y_geo, const Vector & refellipsoid, const Verbosity & verbosity)
WORKSPACE METHOD: y_geoToGeodetic.
Converts y_geo to hold geodetic values.
Replaces geocentric values with corresponding geodetic ones.
Author
Patrick Eriksson
Parameters
[in,out] y_geo WS Input/Output
[in] refellipsoid WS Input
Definition at line 290 of file m_geodetic.cc.
References ARTS::Var::refellipsoid(), and ARTS::Var::y_geo().
Referenced by y_geoToGeodetic_g().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by refellipsoidForAzimuth().