ARTS: m_general.h File Reference
m_general.h File Reference
Template functions for general supergeneric ws methods.
#include "arts.h"
#include <iostream>
#include <stdexcept>
#include "cia.h"
#include "messages.h"
#include "mystring.h"
#include "ppath.h"
#include "special_interp.h"
#include "tessem.h"
Classes
class Timer
Macros
#define SWITCH_OUTPUT(x, y)
Functions
template<typename T >
void Print (const T &x, const Index &level, const Verbosity &verbosity)
WORKSPACE METHOD: Print.
void Print (Workspace &ws, const Agenda &x, const Index &level, const Verbosity &verbosity)
void Print (Workspace &ws, const ArrayOfAgenda &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfGridPos &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfCIARecord &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfString &x, const Index &level, const Verbosity &verbosity)
void Print (const Ppath &ppath, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfPpath &x, const Index &level, const Verbosity &verbosity)
void Print (const Timer &x, const Index &level, const Verbosity &verbosity)
void Print (const TessemNN &x, const Index &level, const Verbosity &verbosity)
void PrintWorkspace (Workspace &ws, const Index &only_allocated, const Index &level, const Verbosity &verbosity)
Detailed Description
Template functions for general supergeneric ws methods.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-07-24
Definition in file m_general.h.
Macro Definition Documentation
SWITCH_OUTPUT
#define SWITCH_OUTPUT (x, y)
Value:
  {                                                                   \
    ostringstream so_os;                                              \
    so_os << y << '\n';                                               \
    switch (x) {                                                      \
      case 0:                                                         \
        out0 << so_os.str();                                          \
        break;                                                        \
      case 1:                                                         \
        out1 << so_os.str();                                          \
        break;                                                        \
      case 2:                                                         \
        out2 << so_os.str();                                          \
        break;                                                        \
      case 3:                                                         \
        out3 << so_os.str();                                          \
        break;                                                        \
      default:                                                        \
        throw runtime_error("Output level must have value from 0-3"); \
    }                                                                 \
  }
Definition at line 46 of file m_general.h.
Function Documentation
Print() [1/10]
void Print (const ArrayOfCIARecord & x, const Index & level, const Verbosity & verbosity)
Definition at line 128 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), ConstVectorView::nelem(), SPEED_OF_LIGHT, and SWITCH_OUTPUT.
Print() [2/10]
void Print (const ArrayOfGridPos & x, const Index & level, const Verbosity & verbosity)
Definition at line 113 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), and SWITCH_OUTPUT.
Print() [3/10]
void Print (const ArrayOfPpath & x, const Index & level, const Verbosity & verbosity)
Definition at line 220 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), Print(), and SWITCH_OUTPUT.
Print() [4/10]
void Print (const ArrayOfString & x, const Index & level, const Verbosity & verbosity)
Definition at line 154 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), and SWITCH_OUTPUT.
Print() [5/10]
void Print (const Ppath & ppath, const Index & level, const Verbosity & verbosity)
Definition at line 169 of file m_general.cc.
References Ppath::background, Ppath::constant, CREATE_OUTS, Ppath::dim, Ppath::end_los, Ppath::end_lstep, Ppath::end_pos, Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, Ppath::los, Ppath::lstep, Ppath::ngroup, Ppath::np, Ppath::nreal, Ppath::pos, Print(), Ppath::r, Ppath::start_los, Ppath::start_lstep, Ppath::start_pos, and SWITCH_OUTPUT.
Print() [6/10]
template<typename T > void Print (const T & in, const Index & level, const Verbosity & verbosity)
WORKSPACE METHOD: Print.
Prints a variable on the screen.
Author
Oliver Lemke
Parameters
[in] in Generic Input
[in] level Generic Input (Default: "1")
Definition at line 83 of file m_general.h.
References CREATE_OUTS, and SWITCH_OUTPUT.
Print() [7/10]
void Print (const TessemNN & x, const Index & level, const Verbosity & verbosity)
Definition at line 296 of file m_general.cc.
References CREATE_OUTS, TessemNN::nb_cache, TessemNN::nb_inputs, TessemNN::nb_outputs, and SWITCH_OUTPUT.
Print() [8/10]
void Print (const Timer & x, const Index & level, const Verbosity & verbosity)
Definition at line 286 of file m_general.cc.
References SWITCH_OUTPUT.
Print() [9/10]
void Print (Workspace & ws, const Agenda & x, const Index & level, const Verbosity & verbosity)
Definition at line 76 of file m_general.cc.
References CREATE_OUTS, Agenda::name(), Agenda::print(), and SWITCH_OUTPUT.
Referenced by CIAInfo(), Print(), Print_sg_AbsorptionLines_g(), Print_sg_Agenda_g(), Print_sg_ArrayOfAbsorptionLines_g(), Print_sg_ArrayOfAgenda_g(), Print_sg_ArrayOfArrayOfAbsorptionLines_g(), Print_sg_ArrayOfArrayOfGriddedField1_g(), Print_sg_ArrayOfArrayOfGriddedField2_g(), Print_sg_ArrayOfArrayOfGriddedField3_g(), Print_sg_ArrayOfArrayOfIndex_g(), Print_sg_ArrayOfArrayOfMatrix_g(), Print_sg_ArrayOfArrayOfPropagationMatrix_g(), Print_sg_ArrayOfArrayOfRadiationVector_g(), Print_sg_ArrayOfArrayOfScatteringMetaData_g(), Print_sg_ArrayOfArrayOfSingleScatteringData_g(), Print_sg_ArrayOfArrayOfSpeciesTag_g(), Print_sg_ArrayOfArrayOfStokesVector_g(), Print_sg_ArrayOfArrayOfString_g(), Print_sg_ArrayOfArrayOfTensor3_g(), Print_sg_ArrayOfArrayOfTensor6_g(), Print_sg_ArrayOfArrayOfTime_g(), Print_sg_ArrayOfArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfArrayOfVector_g(), Print_sg_ArrayOfCIARecord_g(), Print_sg_ArrayOfGriddedField1_g(), Print_sg_ArrayOfGriddedField2_g(), Print_sg_ArrayOfGriddedField3_g(), Print_sg_ArrayOfGriddedField4_g(), Print_sg_ArrayOfIndex_g(), Print_sg_ArrayOfMatrix_g(), Print_sg_ArrayOfPpath_g(), Print_sg_ArrayOfPropagationMatrix_g(), Print_sg_ArrayOfQuantumIdentifier_g(), Print_sg_ArrayOfRadiationVector_g(), Print_sg_ArrayOfRetrievalQuantity_g(), Print_sg_ArrayOfScatteringMetaData_g(), Print_sg_ArrayOfSingleScatteringData_g(), Print_sg_ArrayOfSparse_g(), Print_sg_ArrayOfStokesVector_g(), Print_sg_ArrayOfString_g(), Print_sg_ArrayOfTelsemAtlas_g(), Print_sg_ArrayOfTensor3_g(), Print_sg_ArrayOfTensor4_g(), Print_sg_ArrayOfTensor5_g(), Print_sg_ArrayOfTensor6_g(), Print_sg_ArrayOfTensor7_g(), Print_sg_ArrayOfTime_g(), Print_sg_ArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfVector_g(), Print_sg_ArrayOfXsecRecord_g(), Print_sg_CIARecord_g(), Print_sg_CovarianceMatrix_g(), Print_sg_EnergyLevelMap_g(), Print_sg_GasAbsLookup_g(), Print_sg_GriddedField1_g(), Print_sg_GriddedField2_g(), Print_sg_GriddedField3_g(), Print_sg_GriddedField4_g(), Print_sg_GriddedField5_g(), Print_sg_GriddedField6_g(), Print_sg_GridPos_g(), Print_sg_HitranRelaxationMatrixData_g(), Print_sg_Index_g(), Print_sg_Matrix_g(), Print_sg_MCAntenna_g(), Print_sg_Numeric_g(), Print_sg_Ppath_g(), Print_sg_PropagationMatrix_g(), Print_sg_QuantumIdentifier_g(), Print_sg_RadiationVector_g(), Print_sg_Rational_g(), Print_sg_ScatteringMetaData_g(), Print_sg_SingleScatteringData_g(), Print_sg_Sparse_g(), Print_sg_SpeciesAuxData_g(), Print_sg_StokesVector_g(), Print_sg_String_g(), Print_sg_TelsemAtlas_g(), Print_sg_Tensor3_g(), Print_sg_Tensor4_g(), Print_sg_Tensor5_g(), Print_sg_Tensor6_g(), Print_sg_Tensor7_g(), Print_sg_TessemNN_g(), Print_sg_Time_g(), Print_sg_Timer_g(), Print_sg_TransmissionMatrix_g(), Print_sg_Vector_g(), and Print_sg_Verbosity_g().
Print() [10/10]
void Print (Workspace & ws, const ArrayOfAgenda & x, const Index & level, const Verbosity & verbosity)
Definition at line 92 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), and SWITCH_OUTPUT.
PrintWorkspace()
void PrintWorkspace (Workspace & ws, const Index & only_allocated, const Index & level, const Verbosity & verbosity)
Definition at line 309 of file m_general.cc.
References CREATE_OUTS, Workspace::depth(), Workspace::is_initialized(), Workspace::nelem(), PrintWsvName(), and SWITCH_OUTPUT.
Referenced by PrintWorkspace_g().