ARTS: m_general.cc File Reference
m_general.cc File Reference
Workspace functions of a general and overall character.
#include "arts.h"
#include <cstdlib>
#include <stdexcept>
#include "array.h"
#include "check_input.h"
#include "m_general.h"
#include "messages.h"
#include "mystring.h"
#include "math_funcs.h"
#include "wsv_aux.h"
#include "auto_md.h"
#include "workspace_ng.h"
#include "sensor.h"
#include "fastem.h"
#include "tessem.h"
Functions
void INCLUDE (const Verbosity &)
WORKSPACE METHOD: INCLUDE.
void Print (Workspace &ws, const Agenda &x, const Index &level, const Verbosity &verbosity)
void Print (Workspace &ws, const ArrayOfAgenda &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfGridPos &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfCIARecord &cia_data, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfString &x, const Index &level, const Verbosity &verbosity)
void Print (const Ppath &x, const Index &level, const Verbosity &verbosity)
void Print (const ArrayOfPpath &x, const Index &level, const Verbosity &verbosity)
void Print (const Timer &, const Index &level, const Verbosity &verbosity)
void Print (const TessemNN &x, const Index &level, const Verbosity &verbosity)
void PrintWorkspace (Workspace &ws, const Index &only_allocated, const Index &level, const Verbosity &verbosity)
void StringJoin (String &out, const String &in1, const String &in2, const String &in3, const String &in4, const String &in5, const String &in6, const String &in7, const String &in8, const String &in9, const String &in10, const Verbosity &)
WORKSPACE METHOD: StringJoin.
void timerStart (Timer &, const Verbosity &)
WORKSPACE METHOD: timerStart.
void timerStop (const Timer &, const Verbosity &)
void Error (const String &msg, const Verbosity &verbosity)
WORKSPACE METHOD: Error.
void Exit (const Verbosity &verbosity)
WORKSPACE METHOD: Exit.
void TestArrayOfAgenda (Workspace &ws, const ArrayOfAgenda &test_agenda_array, const Index &index, const Verbosity &)
WORKSPACE METHOD: TestArrayOfAgenda.
void Test (const Verbosity &)
WORKSPACE METHOD: Test.
void verbosityInit (Verbosity &verbosity)
WORKSPACE METHOD: verbosityInit.
void verbositySet (Verbosity &verbosity, const Index &agenda, const Index &screen, const Index &file)
WORKSPACE METHOD: verbositySet.
void verbositySetAgenda (Verbosity &verbosity, const Index &level)
WORKSPACE METHOD: verbositySetAgenda.
void verbositySetFile (Verbosity &verbosity, const Index &level)
WORKSPACE METHOD: verbositySetFile.
void verbositySetScreen (Verbosity &verbosity, const Index &level)
WORKSPACE METHOD: verbositySetScreen.
void GetEnvironmentVariable (String &str, const String &envvar, const Verbosity &)
WORKSPACE METHOD: GetEnvironmentVariable.
void GetNumberOfThreads (Index &nthreads, const Verbosity &)
WORKSPACE METHOD: GetNumberOfThreads.
void GetEnvironmentVariable (Index &i, const String &envvar, const Verbosity &)
WORKSPACE METHOD: GetEnvironmentVariable.
void SetNumberOfThreads (const Index &, const Verbosity &verbosity)
WORKSPACE METHOD: SetNumberOfThreads.
Variables
const Numeric SPEED_OF_LIGHT
Detailed Description
Workspace functions of a general and overall character.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-08
This file is for general functions that do not fit in any other "m_"-file.
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_general.cc.
Function Documentation
Error()
void Error (const String & msg, const Verbosity & verbosity)
WORKSPACE METHOD: Error.
Issues an error and exits ARTS.
This method can be placed in agendas that must be specified, but are expected not to be used for the particular case. An inclusion in surface_rtprop_agenda could look like: <br> Error{"Surface interceptions of propagation path not expected."}
Ignore and other dummy method calls must still be included.
Author
Patrick Eriksson
Parameters
[in] msg Generic Input
Definition at line 397 of file m_general.cc.
References ARTS_USER_ERROR, and CREATE_OUT0.
Referenced by Error_g().
Exit()
void Exit (const Verbosity & verbosity)
WORKSPACE METHOD: Exit.
Stops the execution and exits ARTS.
This method is handy if you want to debug one of your control files. You can insert it anywhere in the control file. When it is reached, it will terminate the program.
Author
Patrick Eriksson
Definition at line 403 of file m_general.cc.
References arts_exit(), and CREATE_OUT1.
Referenced by Exit_g().
GetEnvironmentVariable() [1/2]
void GetEnvironmentVariable (Index & out, const String & in, const Verbosity & verbosity)
WORKSPACE METHOD: GetEnvironmentVariable.
Copy the contents of an environment variable to an ARTS String or Index.
Author
Oliver Lemke
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 494 of file m_general.cc.
References ARTS_USER_ERROR_IF.
GetEnvironmentVariable() [2/2]
void GetEnvironmentVariable (String & out, const String & in, const Verbosity & verbosity)
WORKSPACE METHOD: GetEnvironmentVariable.
Copy the contents of an environment variable to an ARTS String or Index.
Author
Oliver Lemke
Parameters
[out] out Supergeneric output
[in] in Generic Input
Definition at line 476 of file m_general.cc.
References ARTS_USER_ERROR_IF.
Referenced by GetEnvironmentVariable_sg_Index_g(), and GetEnvironmentVariable_sg_String_g().
GetNumberOfThreads()
void GetNumberOfThreads (Index & nthreads, const Verbosity & verbosity)
WORKSPACE METHOD: GetNumberOfThreads.
Returns the number of threads used by ARTS.
Author
Oliver Lemke
Parameters
[out] nthreads Generic output
Definition at line 489 of file m_general.cc.
References arts_omp_get_max_threads().
Referenced by GetNumberOfThreads_g().
INCLUDE()
void INCLUDE (const Verbosity & verbosity)
WORKSPACE METHOD: INCLUDE.
Includes the contents of another controlfile.
The INCLUDE statement inserts the contents of the controlfile with the given name into the current controlfile. If the filename is given without path information, ARTS will first search for the file in all directories specified with the -I (see arts -h) commandline option and then in directories given in the environment variable ARTS_INCLUDE_PATH. In the environment variable multiple paths have to be separated by colons.
Note that INCLUDE is not a workspace method and thus the syntax is different:
Arts { <br> INCLUDE "general.arts" }
Includes can also be nested. In the example above general.arts can contain further includes which will then be treated the same way.
The idea behind this mechanism is that you can write common settings for a bunch of calculations into one file. Then, you can create several controlfiles which include the basic settings and tweak them for different cases. When you decide to make changes to your setup that should apply to all calculations, you only have to make a single change in the include file instead of modifying all your controlfiles.
Author
Oliver Lemke
Definition at line 73 of file m_general.cc.
Referenced by INCLUDE_g().
Print() [1/9]
void Print (const ArrayOfCIARecord & cia_data, const Index & level, const Verbosity & verbosity)
Definition at line 128 of file m_general.cc.
References CREATE_OUTS, Array< base >::nelem(), ConstVectorView::nelem(), SPEED_OF_LIGHT, and SWITCH_OUTPUT.
Print() [2/9]
void Print (const ArrayOfGridPos & x, const Index & level, const Verbosity & verbosity)
Definition at line 113 of file m_general.cc.
References CREATE_OUTS, SWITCH_OUTPUT, and ARTS::Var::x().
Print() [3/9]
void Print (const ArrayOfPpath & x, const Index & level, const Verbosity & verbosity)
Definition at line 220 of file m_general.cc.
References CREATE_OUTS, Print(), SWITCH_OUTPUT, ARTS::Var::verbosity(), and ARTS::Var::x().
Print() [4/9]
void Print (const ArrayOfString & x, const Index & level, const Verbosity & verbosity)
Definition at line 154 of file m_general.cc.
References CREATE_OUTS, SWITCH_OUTPUT, and ARTS::Var::x().
Print() [5/9]
void Print (const Ppath & x, const Index & level, const Verbosity & verbosity)
Definition at line 169 of file m_general.cc.
References CREATE_OUTS, ARTS::Var::Vector::pos(), Print(), SWITCH_OUTPUT, ARTS::Var::verbosity(), and ARTS::Var::x().
Print() [6/9]
void Print (const TessemNN & x, const Index & level, const Verbosity & verbosity)
Definition at line 296 of file m_general.cc.
References CREATE_OUTS, SWITCH_OUTPUT, and ARTS::Var::x().
Print() [7/9]
void Print (const Timer & x, const Index & level, const Verbosity & verbosity)
Definition at line 286 of file m_general.cc.
References SWITCH_OUTPUT.
Print() [8/9]
void Print (Workspace & ws, const Agenda & x, const Index & level, const Verbosity & verbosity)
Definition at line 76 of file m_general.cc.
References CREATE_OUTS, ARTS::Var::Vector::name(), SWITCH_OUTPUT, and ARTS::Var::x().
Referenced by CIAInfo(), Print(), Print_sg_AbsorptionLines_g(), Print_sg_Agenda_g(), Print_sg_ArrayOfAbsorptionLines_g(), Print_sg_ArrayOfAgenda_g(), Print_sg_ArrayOfArrayOfAbsorptionLines_g(), Print_sg_ArrayOfArrayOfGriddedField1_g(), Print_sg_ArrayOfArrayOfGriddedField2_g(), Print_sg_ArrayOfArrayOfGriddedField3_g(), Print_sg_ArrayOfArrayOfIndex_g(), Print_sg_ArrayOfArrayOfMatrix_g(), Print_sg_ArrayOfArrayOfPropagationMatrix_g(), Print_sg_ArrayOfArrayOfRadiationVector_g(), Print_sg_ArrayOfArrayOfScatteringMetaData_g(), Print_sg_ArrayOfArrayOfSingleScatteringData_g(), Print_sg_ArrayOfArrayOfSpeciesTag_g(), Print_sg_ArrayOfArrayOfStokesVector_g(), Print_sg_ArrayOfArrayOfString_g(), Print_sg_ArrayOfArrayOfTensor3_g(), Print_sg_ArrayOfArrayOfTensor6_g(), Print_sg_ArrayOfArrayOfTime_g(), Print_sg_ArrayOfArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfArrayOfVector_g(), Print_sg_ArrayOfCIARecord_g(), Print_sg_ArrayOfGriddedField1_g(), Print_sg_ArrayOfGriddedField2_g(), Print_sg_ArrayOfGriddedField3_g(), Print_sg_ArrayOfGriddedField4_g(), Print_sg_ArrayOfIndex_g(), Print_sg_ArrayOfJacobianTarget_g(), Print_sg_ArrayOfMatrix_g(), Print_sg_ArrayOfPpath_g(), Print_sg_ArrayOfPropagationMatrix_g(), Print_sg_ArrayOfQuantumIdentifier_g(), Print_sg_ArrayOfRadiationVector_g(), Print_sg_ArrayOfRetrievalQuantity_g(), Print_sg_ArrayOfScatteringMetaData_g(), Print_sg_ArrayOfSingleScatteringData_g(), Print_sg_ArrayOfSparse_g(), Print_sg_ArrayOfStokesVector_g(), Print_sg_ArrayOfString_g(), Print_sg_ArrayOfTelsemAtlas_g(), Print_sg_ArrayOfTensor3_g(), Print_sg_ArrayOfTensor4_g(), Print_sg_ArrayOfTensor5_g(), Print_sg_ArrayOfTensor6_g(), Print_sg_ArrayOfTensor7_g(), Print_sg_ArrayOfTime_g(), Print_sg_ArrayOfTransmissionMatrix_g(), Print_sg_ArrayOfVector_g(), Print_sg_ArrayOfXsecRecord_g(), Print_sg_CIARecord_g(), Print_sg_CovarianceMatrix_g(), Print_sg_EnergyLevelMap_g(), Print_sg_GasAbsLookup_g(), Print_sg_GriddedField1_g(), Print_sg_GriddedField2_g(), Print_sg_GriddedField3_g(), Print_sg_GriddedField4_g(), Print_sg_GriddedField5_g(), Print_sg_GriddedField6_g(), Print_sg_GridPos_g(), Print_sg_HitranRelaxationMatrixData_g(), Print_sg_Index_g(), Print_sg_JacobianTarget_g(), Print_sg_Matrix_g(), Print_sg_MCAntenna_g(), Print_sg_Numeric_g(), Print_sg_Ppath_g(), Print_sg_PropagationMatrix_g(), Print_sg_QuantumIdentifier_g(), Print_sg_RadiationVector_g(), Print_sg_Rational_g(), Print_sg_ScatteringMetaData_g(), Print_sg_SingleScatteringData_g(), Print_sg_Sparse_g(), Print_sg_SpeciesAuxData_g(), Print_sg_StokesVector_g(), Print_sg_String_g(), Print_sg_TelsemAtlas_g(), Print_sg_Tensor3_g(), Print_sg_Tensor4_g(), Print_sg_Tensor5_g(), Print_sg_Tensor6_g(), Print_sg_Tensor7_g(), Print_sg_TessemNN_g(), Print_sg_Time_g(), Print_sg_Timer_g(), Print_sg_TransmissionMatrix_g(), Print_sg_Vector_g(), and Print_sg_Verbosity_g().
Print() [9/9]
void Print (Workspace & ws, const ArrayOfAgenda & x, const Index & level, const Verbosity & verbosity)
Definition at line 92 of file m_general.cc.
References CREATE_OUTS, ARTS::Var::Vector::name(), SWITCH_OUTPUT, and ARTS::Var::x().
PrintWorkspace()
void PrintWorkspace (Workspace & ws, const Index & only_allocated, const Index & level, const Verbosity & verbosity)
Definition at line 309 of file m_general.cc.
References CREATE_OUTS, Workspace::depth(), Workspace::is_initialized(), Workspace::nelem(), PrintWsvName(), and SWITCH_OUTPUT.
Referenced by PrintWorkspace_g().
SetNumberOfThreads()
void SetNumberOfThreads (const Index & nthreads, const Verbosity & verbosity)
WORKSPACE METHOD: SetNumberOfThreads.
Change the number of threads used by ARTS.
Author
Oliver Lemke
Parameters
[in] nthreads Generic Input
Definition at line 518 of file m_general.cc.
References CREATE_OUT1.
Referenced by SetNumberOfThreads_g().
StringJoin()
void StringJoin (String & out, const String & in1, const String & in2, const String & in3, const String & in4, const String & in5, const String & in6, const String & in7, const String & in8, const String & in9, const String & in10, const Verbosity & verbosity)
WORKSPACE METHOD: StringJoin.
Concatenate two or more strings.
The output string is overwritten, but is allowed to appear in the input list. Up to 10 strings can be concatenated at once.
Author
Oliver Lemke
Parameters
[out] out Generic output
[in] in1 Generic Input
[in] in2 Generic Input
[in] in3 Generic Input (Default: "")
[in] in4 Generic Input (Default: "")
[in] in5 Generic Input (Default: "")
[in] in6 Generic Input (Default: "")
[in] in7 Generic Input (Default: "")
[in] in8 Generic Input (Default: "")
[in] in9 Generic Input (Default: "")
[in] in10 Generic Input (Default: "")
Definition at line 338 of file m_general.cc.
Referenced by StringJoin_g().
Test()
void Test (const Verbosity & verbosity)
WORKSPACE METHOD: Test.
A dummy method that can be used for test purposes.
This method can be used by ARTS developers to quickly test stuff. The implementation is in file m_general.cc. This just saves you the trouble of adding a dummy method everytime you want to try something out quickly.
Author
Patrick Eriksson
Definition at line 420 of file m_general.cc.
References add_za_aa(), and diff_za_aa().
Referenced by Test_g().
TestArrayOfAgenda()
void TestArrayOfAgenda (Workspace & ws, const ArrayOfAgenda & test_agenda_array, const Index & index, const Verbosity & verbosity)
WORKSPACE METHOD: TestArrayOfAgenda.
A method that is used for the TestArrayOfAgenda test case.
Author
Oliver Lemke
Parameters
[in,out] ws Workspace
[in] test_agenda_array WS Input
[in] index Generic Input (Default: "0")
Definition at line 410 of file m_general.cc.
References ARTS::Var::test_agenda_array(), and test_agenda_arrayExecute().
Referenced by TestArrayOfAgenda_g().
timerStart()
void timerStart (Timer & timer, const Verbosity & verbosity)
WORKSPACE METHOD: timerStart.
Initializes the CPU timer. Use timerStop to stop the timer.
Usage example: <br> timerStart <br> ReadXML(f_grid,"frequencies.xml") <br> timerStop <br> Print(timer)
Author
Oliver Lemke
Parameters
[out] timer WS Output
Definition at line 365 of file m_general.cc.
References ARTS_USER_ERROR.
Referenced by timerStart_g().
timerStop()
void timerStop (const Timer & , const Verbosity &)
Definition at line 388 of file m_general.cc.
References ARTS_USER_ERROR.
Referenced by timerStop_g().
verbosityInit()
void verbosityInit (Verbosity & verbosity)
WORKSPACE METHOD: verbosityInit.
Initializes the verbosity levels.
Sets verbosity to defaults or the levels specified by -r on the command line.
Author
Oliver Lemke
Parameters
[in,out] verbosity WS Input/Output
Definition at line 430 of file m_general.cc.
References Verbosity::get_agenda_verbosity(), Verbosity::get_file_verbosity(), Verbosity::get_screen_verbosity(), ARTS::Var::verbosity(), and verbosity_at_launch.
Referenced by verbosityInit_g().
verbositySet()
void verbositySet (Verbosity & verbosity, const Index & agenda, const Index & screen, const Index & file)
WORKSPACE METHOD: verbositySet.
Sets the verbosity levels.
Sets the reporting level for agenda calls, screen and file. All reporting levels can reach from 0 (only error messages) to 3 (everything). The agenda setting applies in addition to both screen and file output.
Author
Oliver Lemke
Parameters
[in,out] verbosity WS Input/Output
[in] agenda Generic Input
[in] screen Generic Input
[in] file Generic Input
Definition at line 440 of file m_general.cc.
References ARTS::Var::verbosity().
Referenced by verbositySet_g().
verbositySetAgenda()
void verbositySetAgenda (Verbosity & verbosity, const Index & level)
WORKSPACE METHOD: verbositySetAgenda.
Sets the verbosity level for agenda output.
See verbositySet
Author
Oliver Lemke
Parameters
[in,out] verbosity WS Input/Output
[in] level Generic Input
Definition at line 452 of file m_general.cc.
References ARTS::Var::verbosity().
Referenced by verbositySetAgenda_g().
verbositySetFile()
void verbositySetFile (Verbosity & verbosity, const Index & level)
WORKSPACE METHOD: verbositySetFile.
Sets the verbosity level for report file output.
See verbositySet
Author
Oliver Lemke
Parameters
[in,out] verbosity WS Input/Output
[in] level Generic Input
Definition at line 460 of file m_general.cc.
References ARTS::Var::verbosity().
Referenced by verbositySetFile_g().
verbositySetScreen()
void verbositySetScreen (Verbosity & verbosity, const Index & level)
WORKSPACE METHOD: verbositySetScreen.
Sets the verbosity level for screen output.
See verbositySet
Author
Oliver Lemke
Parameters
[in,out] verbosity WS Input/Output
[in] level Generic Input
Definition at line 468 of file m_general.cc.
References ARTS::Var::verbosity().
Referenced by verbositySetScreen_g().
Variable Documentation
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by Print().