ARTS: m_gridded_fields.h File Reference
m_gridded_fields.h File Reference
Implementation of GriddedField workspace methods.
#include "gridded_fields.h"
#include "mystring.h"
Functions
template<typename T >
void GriddedFieldGetName (String &name, const T &gf, const Verbosity &)
WORKSPACE METHOD: GriddedFieldGetName.
template<typename T >
void ArrayOfGriddedFieldGetNames (ArrayOfString &names, const Array< T > &aogf, const Verbosity &)
Detailed Description
Implementation of GriddedField workspace methods.
Author
Lukas Kluft lukas.nosp@m..klu.nosp@m.ft@gm.nosp@m.ail..nosp@m.com
Date
2017-02-01
This file contains the implementation of the supergeneric methods.
Definition in file m_gridded_fields.h.
Function Documentation
ArrayOfGriddedFieldGetNames()
template<typename T > void ArrayOfGriddedFieldGetNames (ArrayOfString & names, const Array< T > & aogf, const Verbosity &)
Definition at line 47 of file m_gridded_fields.h.
References Array< base >::nelem().
Referenced by ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField1_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField2_g(), ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField3_g(), and ArrayOfGriddedFieldGetNames_sg_ArrayOfGriddedField4_g().
GriddedFieldGetName()
template<typename T > void GriddedFieldGetName (String & name, const T & griddedfield, const Verbosity & verbosity)
WORKSPACE METHOD: GriddedFieldGetName.
Get the name of a GriddedField.
See ArrayOfGriddedFieldGetNames.
Author
Lukas Kluft
Parameters
[out] name Supergeneric output
[in] griddedfield Generic Input
Definition at line 36 of file m_gridded_fields.h.
Referenced by GriddedFieldGetName_sg_GriddedField1_g(), GriddedFieldGetName_sg_GriddedField2_g(), GriddedFieldGetName_sg_GriddedField3_g(), GriddedFieldGetName_sg_GriddedField4_g(), GriddedFieldGetName_sg_GriddedField5_g(), and GriddedFieldGetName_sg_GriddedField6_g().