ARTS: m_hitran_xsec.cc File Reference
m_hitran_xsec.cc File Reference
Workspace methods for HITRAN absorption cross section data.
#include "absorption.h"
#include "arts.h"
#include "messages.h"
#include "auto_md.h"
#include "hitran_xsec.h"
#include "physics_funcs.h"
#include "xml_io.h"
Functions
void abs_xsec_per_speciesAddHitranXsec (ArrayOfMatrix &abs_xsec_per_species, ArrayOfArrayOfMatrix &dabs_xsec_per_species_dx, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfIndex &abs_species_active, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const ArrayOfXsecRecord &hitran_xsec_data, const Index &apply_tfit, const Numeric &force_p, const Numeric &force_t, const Verbosity &verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddHitranXsec.
Variables
const Numeric SPEED_OF_LIGHT
Detailed Description
Workspace methods for HITRAN absorption cross section data.
Author
Oliver Lemke olive.nosp@m.r.le.nosp@m.mke@u.nosp@m.ni-h.nosp@m.ambur.nosp@m.g.de
Stefan Buehler
Date
2018-01-08
Definition in file m_hitran_xsec.cc.
Function Documentation
abs_xsec_per_speciesAddHitranXsec()
void abs_xsec_per_speciesAddHitranXsec (ArrayOfMatrix & abs_xsec_per_species, ArrayOfArrayOfMatrix & dabs_xsec_per_species_dx, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfIndex & abs_species_active, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const ArrayOfXsecRecord & hitran_xsec_data, const Index & apply_tfit, const Numeric & force_p, const Numeric & force_t, const Verbosity & verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddHitranXsec.
Calculate absorption cross sections per tag group for HITRAN xsec species.
This broadens the cross section data from hitran_xsec_data and interpolates it onto the current f_grid.
apply_tfit turns of the temperature fit. It is only meant for testing and should alwasy be kept on for real calculations.
This method depends on the FFTW-3 library.
Author
Oliver Lemke
Parameters
[in,out] abs_xsec_per_species WS Input/Output
[in,out] dabs_xsec_per_species_dx WS Input/Output
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] abs_species_active WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] hitran_xsec_data WS Input
[in] apply_tfit Generic Input (Default: "1")
[in] force_p Generic Input (Default: "-1")
[in] force_t Generic Input (Default: "-1")
Definition at line 41 of file m_hitran_xsec.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_species(), ARTS::Var::abs_species_active(), ARTS::Var::abs_t(), ARTS::Var::abs_xsec_per_species(), ARTS_USER_ERROR_IF, CREATE_OUTS, ARTS::Var::dabs_xsec_per_species_dx(), do_frequency_jacobian(), XsecRecord::Extract(), ARTS::Var::f_grid(), frequency_perturbation(), ARTS::Var::hitran_xsec_data(), hitran_xsec_get_index(), ARTS::Var::jacobian_quantities(), SpeciesTag::Name(), Vector::resize(), SpeciesTag::Species(), supports_hitran_xsec(), SpeciesTag::Type(), SpeciesTag::TYPE_HITRAN_XSEC, and ARTS::Var::verbosity().
Referenced by abs_xsec_per_speciesAddHitranXsec_g().
Variable Documentation
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern