ARTS: m_ignore.h File Reference
m_ignore.h File Reference
Implementation of Ignore.
#include "agenda_class.h"
#include "exceptions.h"
#include "messages.h"
#include "mystring.h"
#include "workspace_ng.h"
Functions
void Ignore (Workspace &, const Agenda &, const Verbosity &)
void Ignore (Workspace &, const ArrayOfAgenda &, const Verbosity &)
template<class T >
void Ignore (const T &, const Verbosity &)
WORKSPACE METHOD: Ignore.
void Touch (Workspace &, Agenda &, const Verbosity &)
template<class T >
void Touch (T &, const Verbosity &)
WORKSPACE METHOD: Touch.
Detailed Description
Implementation of Ignore.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Ignore.
Definition in file m_ignore.h.
Function Documentation
Ignore() [1/3]
template<class T > void Ignore (const T & in, const Verbosity & verbosity)
WORKSPACE METHOD: Ignore.
Ignore a workspace variable.
This method is handy for use in agendas in order to suppress warnings about unused input workspace variables. What it does is: Nothing! In other words, it just ignores the variable it is called on.
This method can ignore any workspace variable you want.
Usage example:
AgendaSet(els_agenda){ <br> Ignore(ls_sigma) <br> elsLorentz }
Without Ignore you would get an error message, because 'els_agenda' is supposed to use the Doppler width 'ls_sigma', but the Lorentz lineshape 'elsLorentz' does not need it.
Author
Stefan Buehler
Parameters
[in] in Generic Input
Definition at line 52 of file m_ignore.h.
Ignore() [2/3]
void Ignore (Workspace & , const Agenda & , const Verbosity &) inline
Definition at line 39 of file m_ignore.h.
Referenced by ARTS::Agenda::geo_pos_agenda_empty(), Ignore_sg_AbsorptionLines_g(), Ignore_sg_Agenda_g(), Ignore_sg_ArrayOfAbsorptionLines_g(), Ignore_sg_ArrayOfAgenda_g(), Ignore_sg_ArrayOfArrayOfAbsorptionLines_g(), Ignore_sg_ArrayOfArrayOfGriddedField1_g(), Ignore_sg_ArrayOfArrayOfGriddedField2_g(), Ignore_sg_ArrayOfArrayOfGriddedField3_g(), Ignore_sg_ArrayOfArrayOfIndex_g(), Ignore_sg_ArrayOfArrayOfMatrix_g(), Ignore_sg_ArrayOfArrayOfPropagationMatrix_g(), Ignore_sg_ArrayOfArrayOfRadiationVector_g(), Ignore_sg_ArrayOfArrayOfScatteringMetaData_g(), Ignore_sg_ArrayOfArrayOfSingleScatteringData_g(), Ignore_sg_ArrayOfArrayOfSpeciesTag_g(), Ignore_sg_ArrayOfArrayOfStokesVector_g(), Ignore_sg_ArrayOfArrayOfString_g(), Ignore_sg_ArrayOfArrayOfTensor3_g(), Ignore_sg_ArrayOfArrayOfTensor6_g(), Ignore_sg_ArrayOfArrayOfTime_g(), Ignore_sg_ArrayOfArrayOfTransmissionMatrix_g(), Ignore_sg_ArrayOfArrayOfVector_g(), Ignore_sg_ArrayOfCIARecord_g(), Ignore_sg_ArrayOfGriddedField1_g(), Ignore_sg_ArrayOfGriddedField2_g(), Ignore_sg_ArrayOfGriddedField3_g(), Ignore_sg_ArrayOfGriddedField4_g(), Ignore_sg_ArrayOfIndex_g(), Ignore_sg_ArrayOfJacobianTarget_g(), Ignore_sg_ArrayOfMatrix_g(), Ignore_sg_ArrayOfPpath_g(), Ignore_sg_ArrayOfPropagationMatrix_g(), Ignore_sg_ArrayOfQuantumIdentifier_g(), Ignore_sg_ArrayOfRadiationVector_g(), Ignore_sg_ArrayOfRetrievalQuantity_g(), Ignore_sg_ArrayOfScatteringMetaData_g(), Ignore_sg_ArrayOfSingleScatteringData_g(), Ignore_sg_ArrayOfSparse_g(), Ignore_sg_ArrayOfSpeciesTag_g(), Ignore_sg_ArrayOfStokesVector_g(), Ignore_sg_ArrayOfString_g(), Ignore_sg_ArrayOfTelsemAtlas_g(), Ignore_sg_ArrayOfTensor3_g(), Ignore_sg_ArrayOfTensor4_g(), Ignore_sg_ArrayOfTensor5_g(), Ignore_sg_ArrayOfTensor6_g(), Ignore_sg_ArrayOfTensor7_g(), Ignore_sg_ArrayOfTime_g(), Ignore_sg_ArrayOfTransmissionMatrix_g(), Ignore_sg_ArrayOfVector_g(), Ignore_sg_ArrayOfXsecRecord_g(), Ignore_sg_CIARecord_g(), Ignore_sg_CovarianceMatrix_g(), Ignore_sg_EnergyLevelMap_g(), Ignore_sg_GasAbsLookup_g(), Ignore_sg_GriddedField1_g(), Ignore_sg_GriddedField2_g(), Ignore_sg_GriddedField3_g(), Ignore_sg_GriddedField4_g(), Ignore_sg_GriddedField5_g(), Ignore_sg_GriddedField6_g(), Ignore_sg_GridPos_g(), Ignore_sg_HitranRelaxationMatrixData_g(), Ignore_sg_Index_g(), Ignore_sg_JacobianTarget_g(), Ignore_sg_MapOfErrorCorrectedSuddenData_g(), Ignore_sg_Matrix_g(), Ignore_sg_MCAntenna_g(), Ignore_sg_Numeric_g(), Ignore_sg_Ppath_g(), Ignore_sg_PropagationMatrix_g(), Ignore_sg_QuantumIdentifier_g(), Ignore_sg_RadiationVector_g(), Ignore_sg_Rational_g(), Ignore_sg_ScatteringMetaData_g(), Ignore_sg_SingleScatteringData_g(), Ignore_sg_Sparse_g(), Ignore_sg_SpeciesIsotopologueRatios_g(), Ignore_sg_StokesVector_g(), Ignore_sg_String_g(), Ignore_sg_TelsemAtlas_g(), Ignore_sg_Tensor3_g(), Ignore_sg_Tensor4_g(), Ignore_sg_Tensor5_g(), Ignore_sg_Tensor6_g(), Ignore_sg_Tensor7_g(), Ignore_sg_TessemNN_g(), Ignore_sg_Time_g(), Ignore_sg_Timer_g(), Ignore_sg_TransmissionMatrix_g(), Ignore_sg_Vector_g(), Ignore_sg_Verbosity_g(), ARTS::Agenda::iy_main_agenda_transmission(), ARTS::Agenda::iy_space_agenda_cosmic_background(), ARTS::Agenda::ppath_agenda_follow_sensor_los(), ARTS::Agenda::ppath_agenda_plane_parallel(), ARTS::Agenda::ppath_step_agenda_geometric_path(), and ARTS::Agenda::propmat_clearsky_agenda_xsec_agenda().
Ignore() [3/3]
void Ignore (Workspace & , const ArrayOfAgenda & , const Verbosity &) inline
Definition at line 45 of file m_ignore.h.
Touch() [1/2]
template<class T > void Touch (T & in, const Verbosity & verbosity)
WORKSPACE METHOD: Touch.
As Ignore but for agenda output.
This method is handy for use in agendas in order to suppress warnings about not-produced output workspace variables.
What it does, in case the variable is initialized already, is: Nothing! In case the variable is not yet initialized, it is set to NaN.
Author
Oliver Lemke
Parameters
[out] in Supergeneric output
Definition at line 64 of file m_ignore.h.
Touch() [2/2]
void Touch (Workspace & , Agenda & , const Verbosity &) inline
Definition at line 57 of file m_ignore.h.
Referenced by Touch_sg_AbsorptionLines_g(), Touch_sg_Agenda_g(), Touch_sg_ArrayOfAbsorptionLines_g(), Touch_sg_ArrayOfAgenda_g(), Touch_sg_ArrayOfArrayOfAbsorptionLines_g(), Touch_sg_ArrayOfArrayOfGriddedField1_g(), Touch_sg_ArrayOfArrayOfGriddedField2_g(), Touch_sg_ArrayOfArrayOfGriddedField3_g(), Touch_sg_ArrayOfArrayOfIndex_g(), Touch_sg_ArrayOfArrayOfMatrix_g(), Touch_sg_ArrayOfArrayOfPropagationMatrix_g(), Touch_sg_ArrayOfArrayOfRadiationVector_g(), Touch_sg_ArrayOfArrayOfScatteringMetaData_g(), Touch_sg_ArrayOfArrayOfSingleScatteringData_g(), Touch_sg_ArrayOfArrayOfSpeciesTag_g(), Touch_sg_ArrayOfArrayOfStokesVector_g(), Touch_sg_ArrayOfArrayOfString_g(), Touch_sg_ArrayOfArrayOfTensor3_g(), Touch_sg_ArrayOfArrayOfTensor6_g(), Touch_sg_ArrayOfArrayOfTime_g(), Touch_sg_ArrayOfArrayOfTransmissionMatrix_g(), Touch_sg_ArrayOfArrayOfVector_g(), Touch_sg_ArrayOfCIARecord_g(), Touch_sg_ArrayOfGriddedField1_g(), Touch_sg_ArrayOfGriddedField2_g(), Touch_sg_ArrayOfGriddedField3_g(), Touch_sg_ArrayOfGriddedField4_g(), Touch_sg_ArrayOfIndex_g(), Touch_sg_ArrayOfJacobianTarget_g(), Touch_sg_ArrayOfMatrix_g(), Touch_sg_ArrayOfPpath_g(), Touch_sg_ArrayOfPropagationMatrix_g(), Touch_sg_ArrayOfQuantumIdentifier_g(), Touch_sg_ArrayOfRadiationVector_g(), Touch_sg_ArrayOfRetrievalQuantity_g(), Touch_sg_ArrayOfScatteringMetaData_g(), Touch_sg_ArrayOfSingleScatteringData_g(), Touch_sg_ArrayOfSparse_g(), Touch_sg_ArrayOfSpeciesTag_g(), Touch_sg_ArrayOfStokesVector_g(), Touch_sg_ArrayOfString_g(), Touch_sg_ArrayOfTelsemAtlas_g(), Touch_sg_ArrayOfTensor3_g(), Touch_sg_ArrayOfTensor4_g(), Touch_sg_ArrayOfTensor5_g(), Touch_sg_ArrayOfTensor6_g(), Touch_sg_ArrayOfTensor7_g(), Touch_sg_ArrayOfTime_g(), Touch_sg_ArrayOfTransmissionMatrix_g(), Touch_sg_ArrayOfVector_g(), Touch_sg_ArrayOfXsecRecord_g(), Touch_sg_CIARecord_g(), Touch_sg_CovarianceMatrix_g(), Touch_sg_EnergyLevelMap_g(), Touch_sg_GasAbsLookup_g(), Touch_sg_GriddedField1_g(), Touch_sg_GriddedField2_g(), Touch_sg_GriddedField3_g(), Touch_sg_GriddedField4_g(), Touch_sg_GriddedField5_g(), Touch_sg_GriddedField6_g(), Touch_sg_GridPos_g(), Touch_sg_HitranRelaxationMatrixData_g(), Touch_sg_Index_g(), Touch_sg_JacobianTarget_g(), Touch_sg_MapOfErrorCorrectedSuddenData_g(), Touch_sg_Matrix_g(), Touch_sg_MCAntenna_g(), Touch_sg_Numeric_g(), Touch_sg_Ppath_g(), Touch_sg_PropagationMatrix_g(), Touch_sg_QuantumIdentifier_g(), Touch_sg_RadiationVector_g(), Touch_sg_Rational_g(), Touch_sg_ScatteringMetaData_g(), Touch_sg_SingleScatteringData_g(), Touch_sg_Sparse_g(), Touch_sg_SpeciesIsotopologueRatios_g(), Touch_sg_StokesVector_g(), Touch_sg_String_g(), Touch_sg_TelsemAtlas_g(), Touch_sg_Tensor3_g(), Touch_sg_Tensor4_g(), Touch_sg_Tensor5_g(), Touch_sg_Tensor6_g(), Touch_sg_Tensor7_g(), Touch_sg_TessemNN_g(), Touch_sg_Time_g(), Touch_sg_Timer_g(), Touch_sg_TransmissionMatrix_g(), Touch_sg_Vector_g(), and Touch_sg_Verbosity_g().