ARTS: m_linemixing.cc File Reference
m_linemixing.cc File Reference
User interface for dealing with pure line mixing calculations.
#include "hitran_species.h"
#include "linemixing.h"
#include "linemixing_hitran.h"
#include "propagationmatrix.h"
Functions
void abs_hitran_relmat_dataReadHitranRelmatDataAndLines (HitranRelaxationMatrixData &abs_hitran_relmat_data, ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &abs_species, const String &basedir, const Numeric &linemixinglimit, const Numeric &fmin, const Numeric &fmax, const Numeric &stot, const String &mode, const String &hitran_type, const Verbosity &)
WORKSPACE METHOD: abs_hitran_relmat_dataReadHitranRelmatDataAndLines.
void propmat_clearskyAddHitranLineMixingLines (PropagationMatrix &propmat_clearsky, const HitranRelaxationMatrixData &abs_hitran_relmat_data, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const SpeciesIsotopologueRatios &isotopologue_ratios, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const Vector &rtp_vmr, const Verbosity &)
WORKSPACE METHOD: propmat_clearskyAddHitranLineMixingLines.
void abs_lines_per_speciesAdaptHitranLineMixing (ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const HitranRelaxationMatrixData &abs_hitran_relmat_data, const Vector &t_grid, const Numeric &pressure, const Index &order, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesAdaptHitranLineMixing.
void abs_lines_per_speciesHitranLineMixingAdaptationData (ArrayOfTensor5 &lm_data, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const HitranRelaxationMatrixData &abs_hitran_relmat_data, const Vector &t_grid, const Vector &p_grid, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesHitranLineMixingAdaptationData.
void propmat_clearskyAddOnTheFlyLineMixing (PropagationMatrix &propmat_clearsky, ArrayOfPropagationMatrix &dpropmat_clearsky_dx, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const Vector &rtp_vmr, const Index &lbl_checked, const Verbosity &)
WORKSPACE METHOD: propmat_clearskyAddOnTheFlyLineMixing.
void propmat_clearskyAddOnTheFlyLineMixingWithZeeman (PropagationMatrix &propmat_clearsky, ArrayOfPropagationMatrix &dpropmat_clearsky_dx, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const Vector &rtp_vmr, const Vector &rtp_mag, const Vector &rtp_los, const Index &lbl_checked, const Verbosity &)
WORKSPACE METHOD: propmat_clearskyAddOnTheFlyLineMixingWithZeeman.
void ecs_dataInit (MapOfErrorCorrectedSuddenData &ecs_data, const Verbosity &)
WORKSPACE METHOD: ecs_dataInit.
void ecs_dataSetSpeciesData (MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Quantum::Identifier &qid, const String &species, const String &scaling_type, const Vector &scaling, const String &beta_type, const Vector &beta, const String &lambda_type, const Vector &lambda, const String &collisional_distance_type, const Vector &collisional_distance, const Verbosity &)
WORKSPACE METHOD: ecs_dataSetSpeciesData.
void ecs_dataSetMeanAir (MapOfErrorCorrectedSuddenData &ecs_data, const Vector &vmrs, const ArrayOfSpeciesTag &specs, const Verbosity &)
WORKSPACE METHOD: ecs_dataSetMeanAir.
void ecs_dataAddMakarov2020 (MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Verbosity &)
WORKSPACE METHOD: ecs_dataAddMakarov2020.
void ecs_dataAddRodrigues1997 (MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Verbosity &)
WORKSPACE METHOD: ecs_dataAddRodrigues1997.
void ecs_dataAddTran2011 (MapOfErrorCorrectedSuddenData &ecs_data, const SpeciesIsotopologueRatios &isotopologue_ratios, const Verbosity &)
WORKSPACE METHOD: ecs_dataAddTran2011.
Detailed Description
User interface for dealing with pure line mixing calculations.
Author
Richard Larsson
Date
2020-06-23
Note: If defined using parameterized form, the normal line-functions approach is faster and more appropriate. These functions should first compute the relaxation, not simply use the relaxation
Definition in file m_linemixing.cc.
Function Documentation
abs_hitran_relmat_dataReadHitranRelmatDataAndLines()
void abs_hitran_relmat_dataReadHitranRelmatDataAndLines (HitranRelaxationMatrixData & abs_hitran_relmat_data, ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const String & basedir, const Numeric & linemixinglimit, const Numeric & fmin, const Numeric & fmax, const Numeric & stot, const String & mode, const String & hitran_type, const Verbosity & verbosity)
WORKSPACE METHOD: abs_hitran_relmat_dataReadHitranRelmatDataAndLines.
Reads HITRAN line mixing data from a basedir The basedir must point at line mixing data as provided by HITRAN. The lines will be changed such that ALL CO2 lines are truncated before adding the HITRAN line mixing lines.
The available modes are such that "VP*" uses Voigt profiles and "SDVP*" uses speed-dependent Voigt profiles, where the "_Y" signifies if Rosenkranz-style line mixing is considered or not, and the "W" at the end signifies that full calculations are used. At the line mixing limit, line mixing is simply turned off.
The "FullW" mode uses Lorentzian calculations with the full relaxation matrix until the line mixing limit is reached and it switches to Voigt.
The HITRAN LM data is available for download at: https://hitran.org/supplementary/
Author
Richard Larsson
Parameters
[out] abs_hitran_relmat_data WS Output
[in,out] abs_lines_per_species WS Input/Output
[in] abs_species WS Input
[in] basedir Generic Input
[in] linemixinglimit Generic Input (Default: "-1")
[in] fmin Generic Input (Default: "-1e99")
[in] fmax Generic Input (Default: "1e99")
[in] stot Generic Input (Default: "0")
[in] mode Generic Input (Default: "VP_W")
[in] hitran_type Generic Input (Default: "Newest")
Definition at line 37 of file m_linemixing.cc.
References ARTS::Var::abs_hitran_relmat_data(), ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), ARTS_USER_ERROR_IF, Hitran::isotopologue_ratios(), Array< base >::nelem(), and lm_hitran_2017::read().
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines_g().
abs_lines_per_speciesAdaptHitranLineMixing()
void abs_lines_per_speciesAdaptHitranLineMixing (ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const HitranRelaxationMatrixData & abs_hitran_relmat_data, const Vector & t_grid, const Numeric & pressure, const Index & order, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesAdaptHitranLineMixing.
Adapts the line-catalog from using HITRAN data to. instead fit ordered parameters to imitate the line mxixing
The order should be 1 or 2. It will compute at 3 as well, but there's no support in current ARTS LBL to make use of it so it will crash at some point
Author
Richard Larsson
Parameters
[in,out] abs_lines_per_species WS Input/Output
[in] abs_hitran_relmat_data WS Input
[in] t_grid Generic Input
[in] pressure Generic Input
[in] order Generic Input
Definition at line 133 of file m_linemixing.cc.
References ARTS::Var::abs_hitran_relmat_data(), ARTS::Var::abs_lines(), ARTS::Var::abs_lines_per_species(), and lm_hitran_2017::hitran_lm_eigenvalue_adaptation().
Referenced by abs_lines_per_speciesAdaptHitranLineMixing_g().
abs_lines_per_speciesHitranLineMixingAdaptationData()
void abs_lines_per_speciesHitranLineMixingAdaptationData (ArrayOfTensor5 & lm_data, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const HitranRelaxationMatrixData & abs_hitran_relmat_data, const Vector & t_grid, const Vector & p_grid, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesHitranLineMixingAdaptationData.
Calls underlying functions to get adaptation data
Author
Richard Larsson
Parameters
[out] lm_data Generic output
[in] abs_lines_per_species WS Input
[in] abs_hitran_relmat_data WS Input
[in] t_grid Generic Input
[in] p_grid Generic Input
Definition at line 149 of file m_linemixing.cc.
References ARTS::Var::abs_hitran_relmat_data(), ARTS::Var::abs_lines(), ARTS::Var::abs_lines_per_species(), lm_hitran_2017::hitran_lm_eigenvalue_adaptation_test(), and ARTS::Var::p_grid().
Referenced by abs_lines_per_speciesHitranLineMixingAdaptationData_g().
ecs_dataAddMakarov2020()
void ecs_dataAddMakarov2020 (MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataAddMakarov2020.
Sets the O2-66 microwave band data for ECS.
Author
Richard Larsson
Parameters
[in,out] ecs_data WS Input/Output
[in] isotopologue_ratios WS Input
Definition at line 413 of file m_linemixing.cc.
References ARTS::Var::ecs_data().
Referenced by ecs_dataAddMakarov2020_g().
ecs_dataAddRodrigues1997()
void ecs_dataAddRodrigues1997 (MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataAddRodrigues1997.
Sets the CO2-626, CO2-636, and CO2-628 IR band data for ECS.
Note that the broadening species has to be N2 and not AIR for the band, and that N2 VMR must be present
Author
Richard Larsson
Parameters
[in,out] ecs_data WS Input/Output
[in] isotopologue_ratios WS Input
Definition at line 435 of file m_linemixing.cc.
References ARTS::Var::ecs_data(), and Conversion::kaycm_per_atm2hz_per_pa().
Referenced by ecs_dataAddRodrigues1997_g().
ecs_dataAddTran2011()
void ecs_dataAddTran2011 (MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataAddTran2011.
Sets the CO2-626, CO2-636, and CO2-628 IR band data for ECS.
Author
Richard Larsson
Parameters
[in,out] ecs_data WS Input/Output
[in] isotopologue_ratios WS Input
Definition at line 456 of file m_linemixing.cc.
References ARTS::Var::ecs_data().
Referenced by ecs_dataAddTran2011_g().
ecs_dataInit()
void ecs_dataInit (MapOfErrorCorrectedSuddenData & ecs_data, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataInit.
Resets/initializes the ECS data.
Author
Richard Larsson
Parameters
[out] ecs_data WS Output
Definition at line 308 of file m_linemixing.cc.
References ARTS::Var::ecs_data().
Referenced by ecs_dataInit_g().
ecs_dataSetMeanAir()
void ecs_dataSetMeanAir (MapOfErrorCorrectedSuddenData & ecs_data, const Vector & vmrs, const ArrayOfSpeciesTag & specs, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataSetMeanAir.
Sets ECS data for air from other data if available.
Author
Richard Larsson
Parameters
[in,out] ecs_data WS Input/Output
[in] vmrs Generic Input
[in] specs Generic Input
Definition at line 339 of file m_linemixing.cc.
References ARTS_USER_ERROR_IF, Absorption::LineMixing::SpeciesErrorCorrectedSuddenData::beta, Absorption::LineMixing::SpeciesErrorCorrectedSuddenData::collisional_distance, data, ARTS::Var::ecs_data(), joker, Absorption::LineMixing::SpeciesErrorCorrectedSuddenData::lambda, Absorption::LineMixing::SpeciesErrorCorrectedSuddenData::mass, LineShape::ModelParameters::N, Array< base >::nelem(), ConstVectorView::nelem(), Absorption::LineMixing::SpeciesErrorCorrectedSuddenData::scaling, LineShape::ModelParameters::type, LineShape::vmrs(), ARTS::Var::x(), LineShape::ModelParameters::X0, LineShape::ModelParameters::X1, LineShape::ModelParameters::X2, and LineShape::ModelParameters::X3.
Referenced by ecs_dataSetMeanAir_g().
ecs_dataSetSpeciesData()
void ecs_dataSetSpeciesData (MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const QuantumIdentifier & qid, const String & species, const String & scaling_type, const Vector & scaling, const String & beta_type, const Vector & beta, const String & lambda_type, const Vector & lambda, const String & collisional_distance_type, const Vector & collisional_distance, const Verbosity & verbosity)
WORKSPACE METHOD: ecs_dataSetSpeciesData.
Sets ECS data for one set of species and quantum identifiers.
Author
Richard Larsson
Parameters
[in,out] ecs_data WS Input/Output
[in] isotopologue_ratios WS Input
[in] qid Generic Input
[in] species Generic Input
[in] scaling_type Generic Input (Default: "T0")
[in] scaling Generic Input
[in] beta_type Generic Input (Default: "T0")
[in] beta Generic Input
[in] lambda_type Generic Input (Default: "T0")
[in] lambda Generic Input
[in] collisional_distance_type Generic Input (Default: "T0")
[in] collisional_distance Generic Input
Definition at line 314 of file m_linemixing.cc.
References ARTS_USER_ERROR_IF, beta, data, ARTS::Var::ecs_data(), good_enum(), Hitran::isotopologue_ratios(), and Species::mean_mass().
Referenced by ecs_dataSetSpeciesData_g().
propmat_clearskyAddHitranLineMixingLines()
void propmat_clearskyAddHitranLineMixingLines (PropagationMatrix & propmat_clearsky, const HitranRelaxationMatrixData & abs_hitran_relmat_data, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const SpeciesIsotopologueRatios & isotopologue_ratios, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const Vector & rtp_vmr, const Verbosity & verbosity)
WORKSPACE METHOD: propmat_clearskyAddHitranLineMixingLines.
Calculates gas absorption coefficients line-by-line for HITRAN line mixed data.
Wigner6Init* or Wigner3Init must be called before this function.
Note that you need to have propmat_clearskyAddLines in addition to this method to compensate the calculations for the pressure limit
Please ensure you cite the original authors when you use this function: J. Lamouroux, L. Realia, X. Thomas, et al., J.Q.S.R.T. 151 (2015), 88-96
Author
Richard Larsson
Parameters
[in,out] propmat_clearsky WS Input/Output
[in] abs_hitran_relmat_data WS Input
[in] abs_lines_per_species WS Input
[in] isotopologue_ratios WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] rtp_pressure WS Input
[in] rtp_temperature WS Input
[in] rtp_vmr WS Input
Definition at line 91 of file m_linemixing.cc.
References ARTS::Var::abs_hitran_relmat_data(), ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), ARTS_USER_ERROR_IF, lm_hitran_2017::compute(), ARTS::Var::f_grid(), Hitran::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), Absorption::nelem(), ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), ARTS::Var::rtp_vmr(), and LineShape::vmrs().
Referenced by propmat_clearskyAddHitranLineMixingLines_g().
propmat_clearskyAddOnTheFlyLineMixing()
void propmat_clearskyAddOnTheFlyLineMixing (PropagationMatrix & propmat_clearsky, ArrayOfPropagationMatrix & dpropmat_clearsky_dx, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const Vector & rtp_vmr, const Index & lbl_checked, const Verbosity & verbosity)
WORKSPACE METHOD: propmat_clearskyAddOnTheFlyLineMixing.
Compute the line mixing of matching lines and add it to the propagation matrix
Each band's Population Type is checked and the calculations are only performed for bands with matching population types (and a good pressure limits)
Presently only supports one method: ByMakarovFullRelmat, based on Makarov et al 2020
Wigner6Init* or Wigner3Init must be called before this function.
Note that you need to have propmat_clearskyAddLines addition to this method to compensate the calculations for the pressure limit
Author
Richard Larsson
Parameters
[in,out] propmat_clearsky WS Input/Output
[in,out] dpropmat_clearsky_dx WS Input/Output
[in] abs_lines_per_species WS Input
[in] ecs_data WS Input
[in] isotopologue_ratios WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] rtp_pressure WS Input
[in] rtp_temperature WS Input
[in] rtp_vmr WS Input
[in] lbl_checked WS Input
Definition at line 166 of file m_linemixing.cc.
References abs, ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), ARTS_USER_ERROR_IF, dabs, ARTS::Var::dpropmat_clearsky_dx(), Absorption::LineMixing::ecs_absorption(), ARTS::Var::ecs_data(), ARTS::Var::f_grid(), Hitran::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), ARTS::Var::lbl_checked(), ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), and ARTS::Var::rtp_vmr().
Referenced by propmat_clearskyAddOnTheFlyLineMixing_g().
propmat_clearskyAddOnTheFlyLineMixingWithZeeman()
void propmat_clearskyAddOnTheFlyLineMixingWithZeeman (PropagationMatrix & propmat_clearsky, ArrayOfPropagationMatrix & dpropmat_clearsky_dx, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const MapOfErrorCorrectedSuddenData & ecs_data, const SpeciesIsotopologueRatios & isotopologue_ratios, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const Vector & rtp_vmr, const Vector & rtp_mag, const Vector & rtp_los, const Index & lbl_checked, const Verbosity & verbosity)
WORKSPACE METHOD: propmat_clearskyAddOnTheFlyLineMixingWithZeeman.
Compute the line mixing of matching lines and add it to the propagation matrix Also computes Zeeman effect for all the lines in the band
Each band's Population Type is checked and the calculations are only performed for bands with matching population types (and a good pressure limits)
Presently only supports one method: ByMakarovFullRelmat, based on Makarov et al 2020
Wigner6Init* or Wigner3Init must be called before this function.
Note that you need to have propmat_clearskyAddLines in addition to this method to compensate the calculations for the pressure limit
Author
Richard Larsson
Parameters
[in,out] propmat_clearsky WS Input/Output
[in,out] dpropmat_clearsky_dx WS Input/Output
[in] abs_lines_per_species WS Input
[in] ecs_data WS Input
[in] isotopologue_ratios WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] rtp_pressure WS Input
[in] rtp_temperature WS Input
[in] rtp_vmr WS Input
[in] rtp_mag WS Input
[in] rtp_los WS Input
[in] lbl_checked WS Input
Definition at line 220 of file m_linemixing.cc.
References abs, ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), Zeeman::AllPolarization(), Zeeman::AllPolarization_deta(), Zeeman::AllPolarization_dtheta(), ARTS_USER_ERROR_IF, dabs, Conversion::deg2rad(), ARTS::Var::dpropmat_clearsky_dx(), Zeeman::dsum(), Absorption::LineMixing::ecs_absorption_zeeman(), ARTS::Var::ecs_data(), ARTS::Var::f_grid(), Zeeman::FromGrids(), Hitran::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), ARTS::Var::lbl_checked(), Jacobian::MagneticU, Jacobian::MagneticV, Jacobian::MagneticW, Zeeman::Pi, ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_los(), ARTS::Var::rtp_mag(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), ARTS::Var::rtp_vmr(), Zeeman::SelectPolarization(), Zeeman::SigmaMinus, Zeeman::SigmaPlus, and Zeeman::sum().
Referenced by propmat_clearskyAddOnTheFlyLineMixingWithZeeman_g().