ARTS: m_planets.cc File Reference
m_planets.cc File Reference
Planet specific workspace methods.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "check_input.h"
#include "matpackI.h"
#include "messages.h"
Functions
void g0Earth (Numeric &g0, const Numeric &lat, const Verbosity &)
WORKSPACE METHOD: g0Earth.
void g0Jupiter (Numeric &g0, const Verbosity &)
WORKSPACE METHOD: g0Jupiter.
void g0Mars (Numeric &g0, const Verbosity &)
WORKSPACE METHOD: g0Mars.
void g0Venus (Numeric &g0, const Verbosity &)
WORKSPACE METHOD: g0Venus.
void g0Io (Numeric &g0, const Verbosity &)
WORKSPACE METHOD: g0Io.
void refellipsoidEarth (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidEarth.
void refellipsoidJupiter (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidJupiter.
void refellipsoidMars (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidMars.
void refellipsoidMoon (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidMoon.
void refellipsoidIo (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidIo.
void refellipsoidEuropa (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidEuropa.
void refellipsoidGanymede (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidGanymede.
void refellipsoidVenus (Vector &refellipsoid, const String &model, const Verbosity &)
WORKSPACE METHOD: refellipsoidVenus.
Variables
const Numeric EARTH_RADIUS
const Numeric DEG2RAD
Detailed Description
Planet specific workspace methods.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2012-03-16
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_planets.cc.
Function Documentation
g0Earth()
void g0Earth (Numeric & g0, const Numeric & lat, const Verbosity & verbosity)
WORKSPACE METHOD: g0Earth.
Gravity at zero altitude on Earth.
Sets g0 for the given latitude using a standard parameterisation.
Author
Patrick Eriksson
Parameters
[out] g0 WS Output
[in] lat WS Input
Definition at line 59 of file m_planets.cc.
References DEG2RAD, and pow().
Referenced by g0Earth_g().
g0Io()
void g0Io (Numeric & g0, const Verbosity & verbosity)
WORKSPACE METHOD: g0Io.
Gravity at zero altitude on Io.
Numeric from Wikipedia.
Author
Richard Larsson
Parameters
[out] g0 WS Output
Definition at line 92 of file m_planets.cc.
Referenced by g0Io_g().
g0Jupiter()
void g0Jupiter (Numeric & g0, const Verbosity & verbosity)
WORKSPACE METHOD: g0Jupiter.
Gravity at zero altitude on Jupiter.
Sets g0 to mean equatorial gravity on Jupiter. Value provided by MPS under ESA-planetary study (TN1).
Author
Jana Mendrok
Parameters
[out] g0 WS Output
Definition at line 72 of file m_planets.cc.
Referenced by g0Jupiter_g().
g0Mars()
void g0Mars (Numeric & g0, const Verbosity & verbosity)
WORKSPACE METHOD: g0Mars.
Gravity at zero altitude on Mars.
Sets g0 to mean equatorial gravity on Mars. Value provided by MPS under ESA-planetary study (TN1).
Author
Jana Mendrok
Parameters
[out] g0 WS Output
Definition at line 80 of file m_planets.cc.
Referenced by g0Mars_g().
g0Venus()
void g0Venus (Numeric & g0, const Verbosity & verbosity)
WORKSPACE METHOD: g0Venus.
Gravity at zero altitude on Venus.
Sets g0 to mean equatorial gravity on Venus. Value from Ahrens (1995), provided by MPS under ESA-planetary study (TN1).
Author
Jana Mendrok
Parameters
[out] g0 WS Output
Definition at line 86 of file m_planets.cc.
Referenced by g0Venus_g().
refellipsoidEarth()
void refellipsoidEarth (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidEarth.
Earth reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model the Earth, following different models. The options are:
<br> "Sphere" : A spherical Earth. The radius is set following <br> the value set for the Earth radius in constants.cc.
<br> "WGS84" : The reference ellipsoid used by the GPS system. <br> Should be the standard choice for a non-spherical Earth.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 98 of file m_planets.cc.
References EARTH_RADIUS, and Vector::resize().
Referenced by refellipsoidEarth_g().
refellipsoidEuropa()
void refellipsoidEuropa (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidEuropa.
Io reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Io, folowing different models. The options are:
<br> "Sphere" : A spherical planetesimal. The radius is taken from <br> report of the IAU/IAG Working Group.
Author
Richard Larsson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 197 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidEuropa_g().
refellipsoidGanymede()
void refellipsoidGanymede (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidGanymede.
Ganymede reference ellipsoids.
From Wikipedia
Author
Takayoshi Yamada
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 213 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidGanymede_g().
refellipsoidIo()
void refellipsoidIo (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidIo.
Io reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Io, folowing different models. The options are:
<br> "Sphere" : A spherical planetesimal. The radius is taken from <br> report of the IAU/IAG Working Group.
Author
Richard Larsson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 181 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidIo_g().
refellipsoidJupiter()
void refellipsoidJupiter (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidJupiter.
Jupiter reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Jupiter, folowing different models. The options are:
<br> "Sphere" : A spherical planet. The radius is taken from a <br> report of the IAU/IAG Working Group.
<br> "Ellipsoid" : A reference ellipsoid with parameters taken from <br> a report of the IAU/IAG Working Group.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 118 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidJupiter_g().
refellipsoidMars()
void refellipsoidMars (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidMars.
Mars reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Mars, folowing different models. The options are:
<br> "Sphere" : A spherical planet. The radius is taken from a <br> report of the IAU/IAG Working Group.
<br> "Ellipsoid" : A reference ellipsoid with parameters taken from <br> a report of the IAU/IAG Working Group.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 138 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidMars_g().
refellipsoidMoon()
void refellipsoidMoon (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidMoon.
Moon reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Moon, folowing different models. The options are:
<br> "Sphere" : A spherical planet. The radius is taken from a <br> report of the IAU/IAG Working Group.
<br> "Ellipsoid" : A reference ellipsoid with parameters taken from <br> Wikepedia (see code for details). The IAU/IAG working group <br> defines the Moon ellipsoid to be a sphere.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 158 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidMoon_g().
refellipsoidVenus()
void refellipsoidVenus (Vector & refellipsoid, const String & model, const Verbosity & verbosity)
WORKSPACE METHOD: refellipsoidVenus.
Venus reference ellipsoids.
The reference ellipsoid (refellipsoid) is set to model Venus, folowing different models. The options are:
<br> "Sphere" : A spherical planet. The radius is taken from a <br> report of the IAU/IAG Working Group.
According to the report used above, the Venus ellipsoid lacks eccentricity and no further models should be required.
Author
Patrick Eriksson
Parameters
[out] refellipsoid WS Output
[in] model Generic Input (Default: "Sphere")
Definition at line 229 of file m_planets.cc.
References Vector::resize().
Referenced by refellipsoidVenus_g().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by g0Earth().
EARTH_RADIUS
const Numeric EARTH_RADIUS extern
Referenced by refellipsoidEarth().