ARTS: m_partfun.cc File Reference
m_partfun.cc File Reference
#include <filesystem>
#include "math_funcs.h"
#include "matpack.h"
#include "messages.h"
#include "mystring.h"
#include "partfun.h"
#include "xml_io.h"
Functions
void WriteBuiltinPartitionFunctionsXML (const String &fileformat, const String &dir, const Numeric &Tlow, const Numeric &Tupp, const Index &N, const Verbosity &verbosity)
WORKSPACE METHOD: WriteBuiltinPartitionFunctionsXML.
Function Documentation
WriteBuiltinPartitionFunctionsXML()
void WriteBuiltinPartitionFunctionsXML (const String & output_file_format, const String & dir, const Numeric & Tlow, const Numeric & Tupp, const Index & N, const Verbosity & verbosity)
WORKSPACE METHOD: WriteBuiltinPartitionFunctionsXML.
Writes all the builtin partition functions to file.
All available partition functions are written to files in the select format in the select directory
The temperature will be linearly spaced between [Tlow, Tupp] with N values
Author
Richard Larsson
Parameters
[in] output_file_format WS Input
[in] dir Generic Input
[in] Tlow Generic Input
[in] Tupp Generic Input
[in] N Generic Input
Definition at line 11 of file m_partfun.cc.
References ARTS_USER_ERROR_IF, CREATE_OUT2, d, data, PartitionFunctions::has_partfun(), Species::Isotopologues, N, nlinspace(), PartitionFunctions::Q(), string2filetype(), ARTS::Var::verbosity(), ARTS::Var::x(), and xml_write_to_file().
Referenced by WriteBuiltinPartitionFunctionsXML_g().