ARTS: m_predefined_absorption_models.cc File Reference
m_predefined_absorption_models.cc File Reference
#include "predefined_absorption_models.h"
Functions
void abs_xsec_per_speciesAddPredefinedO2MPM2020 (ArrayOfMatrix &abs_xsec_per_species, ArrayOfArrayOfMatrix &dabs_xsec_per_species_dx, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const Matrix &abs_vmrs, const Verbosity &)
WORKSPACE METHOD: abs_xsec_per_speciesAddPredefinedO2MPM2020.
Function Documentation
abs_xsec_per_speciesAddPredefinedO2MPM2020()
void abs_xsec_per_speciesAddPredefinedO2MPM2020 (ArrayOfMatrix & abs_xsec_per_species, ArrayOfArrayOfMatrix & dabs_xsec_per_species_dx, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const Matrix & abs_vmrs, const Verbosity & verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddPredefinedO2MPM2020.
Reimplementation of published O2 absorption line cross-section algorithm
Based on: Dmitriy S. Makarov, Mikhail Yu. Tretyakov, Philip W. Rosenkranz, JQSRT 243, 2020, Revision of the 60-GHz atmospheric oxygen absorption band models for practical use, https://doi.org/10.1016/j.jqsrt.2019.106798
Note that this is only really applicable to Earth and at lower altitudes. The only two tested derivatives are for frequency and for temperature but other untested derivatives are available for all model parameters except a2
Author
Richard Larsson
Parameters
[in,out] abs_xsec_per_species WS Input/Output
[in,out] dabs_xsec_per_species_dx WS Input/Output
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] abs_vmrs WS Input
Definition at line 32 of file m_predefined_absorption_models.cc.
References ARTS::Var::abs_p(), ARTS::Var::abs_species(), ARTS::Var::abs_t(), ARTS::Var::abs_vmrs(), ARTS::Var::abs_xsec_per_species(), ARTS::Var::dabs_xsec_per_species_dx(), equivalent_propmattype_indexes(), ARTS::Var::f_grid(), ARTS::Var::jacobian_quantities(), ARTS::Var::x(), and x1.
Referenced by abs_xsec_per_speciesAddPredefinedO2MPM2020_g().