ARTS: m_quantum.cc File Reference
m_quantum.cc File Reference
Quantum handling functions.
#include "energylevelmap.h"
#include "quantum.h"
#include "messages.h"
Functions
void nlte_fieldFromRaw (EnergyLevelMap &nlte_field, const ArrayOfQuantumIdentifier &nlte_level_identifiers, const Vector &nlte_vibrational_energies, const Tensor4 &data, const Verbosity &)
WORKSPACE METHOD: nlte_fieldFromRaw.
void abs_nlteFromRaw (EnergyLevelMap &abs_nlte, const ArrayOfQuantumIdentifier &nlte_level_identifiers, const Vector &nlte_vibrational_energies, const Matrix &data, const Verbosity &)
WORKSPACE METHOD: abs_nlteFromRaw.
void rtp_nlteFromRaw (EnergyLevelMap &rtp_nlte, const ArrayOfQuantumIdentifier &nlte_level_identifiers, const Vector &nlte_vibrational_energies, const Vector &data, const Verbosity &)
WORKSPACE METHOD: rtp_nlteFromRaw.
void EnergyLevelMapSet (EnergyLevelMap &x, const EnergyLevelMap &y, const Verbosity &)
WORKSPACE METHOD: EnergyLevelMapSet.
Detailed Description
Quantum handling functions.
Author
Richard Larsson <larsson (at) mps.mpg.de>
Date
2019-10-22
Definition in file m_quantum.cc.
Function Documentation
abs_nlteFromRaw()
void abs_nlteFromRaw (EnergyLevelMap & abs_nlte, const ArrayOfQuantumIdentifier & nlte_level_identifiers, const Vector & nlte_vibrational_energies, const Matrix & data, const Verbosity & verbosity)
WORKSPACE METHOD: abs_nlteFromRaw.
Sets NLTE values manually
Touch
Author
Richard Larsson
Parameters
[out] abs_nlte WS Output
[in] nlte_level_identifiers WS Input
[in] nlte_vibrational_energies WS Input
[in] data Generic Input
Definition at line 39 of file m_quantum.cc.
References ARTS::Var::abs_nlte(), data, ARTS::Var::nlte_level_identifiers(), and ARTS::Var::nlte_vibrational_energies().
Referenced by abs_nlteFromRaw_g().
EnergyLevelMapSet()
void EnergyLevelMapSet (EnergyLevelMap & x, const EnergyLevelMap & y, const Verbosity & verbosity)
WORKSPACE METHOD: EnergyLevelMapSet.
Sets an EnergyLevelMap
Author
Richard Larsson
Parameters
[out] x Generic output
[in] y Generic Input
Definition at line 59 of file m_quantum.cc.
References ARTS::Var::x(), and ARTS::Var::y().
Referenced by EnergyLevelMapSet_g().
nlte_fieldFromRaw()
void nlte_fieldFromRaw (EnergyLevelMap & nlte_field, const ArrayOfQuantumIdentifier & nlte_level_identifiers, const Vector & nlte_vibrational_energies, const Tensor4 & data, const Verbosity & verbosity)
WORKSPACE METHOD: nlte_fieldFromRaw.
Sets NLTE values manually
Touch
Author
Richard Larsson
Parameters
[out] nlte_field WS Output
[in] nlte_level_identifiers WS Input
[in] nlte_vibrational_energies WS Input
[in] data Generic Input
Definition at line 30 of file m_quantum.cc.
References data, ARTS::Var::nlte_field(), ARTS::Var::nlte_level_identifiers(), and ARTS::Var::nlte_vibrational_energies().
Referenced by nlte_fieldFromRaw_g().
rtp_nlteFromRaw()
void rtp_nlteFromRaw (EnergyLevelMap & rtp_nlte, const ArrayOfQuantumIdentifier & nlte_level_identifiers, const Vector & nlte_vibrational_energies, const Vector & data, const Verbosity & verbosity)
WORKSPACE METHOD: rtp_nlteFromRaw.
Sets NLTE values manually
Touch
Author
Richard Larsson
Parameters
[out] rtp_nlte WS Output
[in] nlte_level_identifiers WS Input
[in] nlte_vibrational_energies WS Input
[in] data Generic Input
Definition at line 48 of file m_quantum.cc.
References data, ARTS::Var::nlte_level_identifiers(), ARTS::Var::nlte_vibrational_energies(), and ARTS::Var::rtp_nlte().
Referenced by rtp_nlteFromRaw_g().