ARTS: m_raw.cc File Reference
m_raw.cc File Reference
Stuff related to generating y-data from raw data.
#include "artstime.h"
#include "raw.h"
Functions
void yColdAtmHot (Vector &y, const Vector &cold, const Vector &atm, const Vector &hot, const Numeric &cold_temp, const Numeric &hot_temp, const Index &calib, const Verbosity &)
WORKSPACE METHOD: yColdAtmHot.
void ybatchColdAtmHotAtmCycle (ArrayOfVector &ybatch, ArrayOfTime &sensor_time, const ArrayOfVector &level0_data, const ArrayOfTime &level0_time, const Vector &cold_temp, const Vector &hot_temp, const Index &first_c_index, const Verbosity &)
WORKSPACE METHOD: ybatchColdAtmHotAtmCycle.
void ybatchTimeAveraging (ArrayOfVector &ybatch, ArrayOfTime &sensor_time, const String &time_step, const Index &disregard_first, const Index &disregard_last, const Verbosity &)
WORKSPACE METHOD: ybatchTimeAveraging.
void ybatchTroposphericCorrectionNaiveMedianForward (ArrayOfVector &ybatch_corr, ArrayOfVector &ybatch, const ArrayOfIndex &range, const Vector &trop_temp, const Numeric &targ_temp, const Verbosity &)
WORKSPACE METHOD: ybatchTroposphericCorrectionNaiveMedianForward.
void ybatchTroposphericCorrectionNaiveMedianInverse (ArrayOfVector &ybatch, const ArrayOfVector &ybatch_corr, const Verbosity &)
WORKSPACE METHOD: ybatchTroposphericCorrectionNaiveMedianInverse.
void yMaskOutsideMedianRange (Vector &y, const Numeric &dx, const Verbosity &)
WORKSPACE METHOD: yMaskOutsideMedianRange.
void ybatchMaskOutsideMedianRange (ArrayOfVector &ybatch, const Numeric &dx, const Verbosity &verbosity)
WORKSPACE METHOD: ybatchMaskOutsideMedianRange.
void yDoublingMeanFocus (Vector &f_grid, Vector &y, const Numeric &f0, const Numeric &df, const Verbosity &)
WORKSPACE METHOD: yDoublingMeanFocus.
void ybatchDoublingMeanFocus (Vector &f_grid, ArrayOfVector &ybatch, const Numeric &f0, const Numeric &df, const Verbosity &)
WORKSPACE METHOD: ybatchDoublingMeanFocus.
Detailed Description
Stuff related to generating y-data from raw data.
Author
Richard Larsson
Date
2020-04-13
Definition in file m_raw.cc.
Function Documentation
ybatchColdAtmHotAtmCycle()
void ybatchColdAtmHotAtmCycle (ArrayOfVector & ybatch, ArrayOfTime & sensor_time, const ArrayOfVector & level0_data, const ArrayOfTime & level0_time, const Vector & cold_temp, const Vector & hot_temp, const Index & first_c_index, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchColdAtmHotAtmCycle.
Computes ybatch from input using standard calibration scheme of a cycle through cold-atm-hot-atm-cold-... observations
Computes for every full cycle reaching a new hot or cold: <br> y = cold_temp + (hot_temp - cold_temp) * (atm - cold) / (hot - cold)
Assumes data is ordered as Cold-Atm-Hot-Atm-Cold-Atm-Hot-Atm-..., but Cold does not have to be at data[0], instead the first cold position is set by first_c_index, which defaults to 0 but can be any positive index so that level0_data[first_c_index] is a cold-measurements. Note that if first_c_index* is larger than 1, then the first output data will be around the observation cycle -HAC-, where H is at first_c_index-2
Also returns the times of the Atm measurements in sensor_time if the measurement's time data is provided
Author
Richard Larsson
Parameters
[out] ybatch WS Output
[out] sensor_time WS Output
[in] level0_data WS Input
[in] level0_time WS Input
[in] cold_temp Generic Input
[in] hot_temp Generic Input
[in] first_c_index Generic Input (Default: "0")
Definition at line 53 of file m_raw.cc.
References ARTS_USER_ERROR_IF, Raw::Calibration::caha(), Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by main(), and ybatchColdAtmHotAtmCycle_g().
ybatchDoublingMeanFocus()
void ybatchDoublingMeanFocus (Vector & f_grid, ArrayOfVector & ybatch, const Numeric & f0, const Numeric & df, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchDoublingMeanFocus.
See yDoublingMeanFocus
Author
Richard Larsson
Parameters
[in,out] f_grid WS Input/Output
[in,out] ybatch WS Input/Output
[in] f0 Generic Input (Default: "-1")
[in] df Generic Input (Default: "-1")
Definition at line 251 of file m_raw.cc.
References F0, Raw::Reduce::focus_doublescaling(), is_increasing(), last(), mean(), Raw::Reduce::nanfocus(), and ConstVectorView::nelem().
Referenced by main(), and ybatchDoublingMeanFocus_g().
ybatchMaskOutsideMedianRange()
void ybatchMaskOutsideMedianRange (ArrayOfVector & ybatch, const Numeric & dx, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchMaskOutsideMedianRange.
Apply yMaskOutsideMedianRange for each y in ybatch
Author
Richard Larsson
Parameters
[in,out] ybatch WS Input/Output
[in] dx Generic Input
Definition at line 215 of file m_raw.cc.
References dx, verbosity, and yMaskOutsideMedianRange().
Referenced by ybatchMaskOutsideMedianRange_g().
ybatchTimeAveraging()
void ybatchTimeAveraging (ArrayOfVector & ybatch, ArrayOfTime & sensor_time, const String & time_step, const Index & disregard_first, const Index & disregard_last, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchTimeAveraging.
Time average of ybatch and sensor_time
Author
Richard Larsson
Parameters
[in,out] ybatch WS Input/Output
[in,out] sensor_time WS Input/Output
[in] time_step Generic Input
[in] disregard_first Generic Input (Default: "0")
[in] disregard_last Generic Input (Default: "0")
Definition at line 83 of file m_raw.cc.
References ARTS_USER_ERROR_IF, is_sorted(), Array< base >::nelem(), time_stepper_selection(), and time_steps().
Referenced by main(), and ybatchTimeAveraging_g().
ybatchTroposphericCorrectionNaiveMedianForward()
void ybatchTroposphericCorrectionNaiveMedianForward (ArrayOfVector & ybatch_corr, ArrayOfVector & ybatch, const ArrayOfIndex & range, const Vector & trop_temp, const Numeric & targ_temp, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchTroposphericCorrectionNaiveMedianForward.
Performs naive tropospheric corrections on ybatch
Sets ybatch_corr to be able to perform the inverse of the corrections, each array-element with 3 entries as [median, part_trans, trop_temp]
Uses the same tropospheric temperature for all values if trop_temp.nelem()==1
Author
Richard Larsson
Parameters
[out] ybatch_corr WS Output
[in,out] ybatch WS Input/Output
[in] range Generic Input (Default: "ArrayOfIndex(0)")
[in] trop_temp Generic Input
[in] targ_temp Generic Input (Default: "2.73")
Definition at line 147 of file m_raw.cc.
References ARTS_USER_ERROR_IF, Raw::Average::nanmedian(), Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by main(), and ybatchTroposphericCorrectionNaiveMedianForward_g().
ybatchTroposphericCorrectionNaiveMedianInverse()
void ybatchTroposphericCorrectionNaiveMedianInverse (ArrayOfVector & ybatch, const ArrayOfVector & ybatch_corr, const Verbosity & verbosity)
WORKSPACE METHOD: ybatchTroposphericCorrectionNaiveMedianInverse.
Performs inverse of naive tropospheric corrections on ybatch
Author
Richard Larsson
Parameters
[in,out] ybatch WS Input/Output
[in] ybatch_corr WS Input
Definition at line 187 of file m_raw.cc.
References ARTS_USER_ERROR_IF, and Array< base >::nelem().
Referenced by ybatchTroposphericCorrectionNaiveMedianInverse_g().
yColdAtmHot()
void yColdAtmHot (Vector & y, const Vector & cold, const Vector & atm, const Vector & hot, const Numeric & cold_temp, const Numeric & hot_temp, const Index & calib, const Verbosity & verbosity)
WORKSPACE METHOD: yColdAtmHot.
Computes y from input using standard calibration scheme of cold-atm-hot observations
If calib evaluates as true: <br> y = cold_temp + (hot_temp - cold_temp) * (atm - cold) / (hot - cold)
If calib evaluates as false: <br> y = (hot_temp * cold - cold_temp * hot) / (hot - cold)
Author
Richard Larsson
Parameters
[out] y WS Output
[in] cold Generic Input
[in] atm Generic Input
[in] hot Generic Input
[in] cold_temp Generic Input
[in] hot_temp Generic Input
[in] calib Generic Input (Default: "1")
Definition at line 32 of file m_raw.cc.
References ARTS_USER_ERROR_IF, Raw::Calibration::calibration(), ConstVectorView::nelem(), Vector::resize(), and Raw::Calibration::systemtemp().
Referenced by yColdAtmHot_g().
yDoublingMeanFocus()
void yDoublingMeanFocus (Vector & f_grid, Vector & y, const Numeric & f0, const Numeric & df, const Verbosity & verbosity)
WORKSPACE METHOD: yDoublingMeanFocus.
Focus in on y around some f_grid, then sets f_grid to same focus
The algorithm will double the frequency spacing DF steps away from F0, doubling it again DF steps away from F0+DF, and so on until the end of the range. The same happens but reversely towards F0-DF, ...
Inside these ranges, the values will be averaged so that there's one value per original input between F0-DF and F0+DF, 1 value per 2 original values between F0+DF and F0+2*DF, and so on ever doubling the number of original values per output value
F0 and DF are set inside the function to either the values given by the user, or if they are non-positive as mean(f_grid) and 10 * (f_grid[1] - f_grid[0]), respectively
Ignores NaNs and infinities in averaging calculations.
Author
Richard Larsson
Parameters
[in,out] f_grid WS Input/Output
[in,out] y WS Input/Output
[in] f0 Generic Input (Default: "-1")
[in] df Generic Input (Default: "-1")
Definition at line 221 of file m_raw.cc.
References F0, Raw::Reduce::focus_doublescaling(), is_increasing(), last(), mean(), Raw::Reduce::nanfocus(), and ConstVectorView::nelem().
Referenced by yDoublingMeanFocus_g().
yMaskOutsideMedianRange()
void yMaskOutsideMedianRange (Vector & y, const Numeric & dx, const Verbosity & verbosity)
WORKSPACE METHOD: yMaskOutsideMedianRange.
Masks values not within the range as NaN: [median(y) - dx, median(y) + dx] Ignores NaNs in median calculations.
Author
Richard Larsson
Parameters
[in,out] y WS Input/Output
[in] dx Generic Input
Definition at line 204 of file m_raw.cc.
References dx, Raw::Mask::mask(), Raw::Average::median(), Raw::Average::nanmedian(), ConstVectorView::nelem(), and Raw::Mask::out_of_bounds().
Referenced by ybatchMaskOutsideMedianRange(), and yMaskOutsideMedianRange_g().