ARTS: m_radiation_field.cc File Reference
m_radiation_field.cc File Reference
Radiation field calculations for the user.
#include "absorption.h"
#include "arts.h"
#include "arts_omp.h"
#include "auto_md.h"
#include "linefunctions.h"
#include "physics_funcs.h"
#include "ppath.h"
#include "propmat_field.h"
#include "radiation_field.h"
Functions
void line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D (Workspace &ws, Matrix &line_irradiance, Tensor3 &line_transmission, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const EnergyLevelMap &nlte_field, const Tensor4 &vmr_field, const Tensor3 &t_field, const Tensor3 &z_field, const Vector &p_grid, const Vector &refellipsoid, const Tensor3 &surface_props_data, const Agenda &ppath_agenda, const Agenda &iy_main_agenda, const Agenda &iy_space_agenda, const Agenda &iy_surface_agenda, const Agenda &iy_cloudbox_agenda, const Agenda &propmat_clearsky_agenda, const Numeric &df, const Index &nz, const Index &nf, const Numeric &r, const Verbosity &verbosity)
WORKSPACE METHOD: line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D.
Detailed Description
Radiation field calculations for the user.
Author
Richard Larsson
Date
2015-09-13
Definition in file m_radiation_field.cc.
Function Documentation
line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D()
void line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D (Workspace & ws, Matrix & line_irradiance, Tensor3 & line_transmission, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const EnergyLevelMap & nlte_field, const Tensor4 & vmr_field, const Tensor3 & t_field, const Tensor3 & z_field, const Vector & p_grid, const Vector & refellipsoid, const Tensor3 & surface_props_data, const Agenda & iy_main_agenda, const Agenda & ppath_agenda, const Agenda & iy_space_agenda, const Agenda & iy_surface_agenda, const Agenda & iy_cloudbox_agenda, const Agenda & propmat_clearsky_agenda, const Numeric & df, const Index & nz, const Index & nf, const Numeric & r, const Verbosity & verbosity)
WORKSPACE METHOD: line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D.
Computes the line irradiance and line transmission
Presently only works for 1D atmospheres
Author
Richard Larsson
Parameters
[in,out] ws Workspace
[out] line_irradiance WS Output
[out] line_transmission WS Output
[in] abs_species WS Input
[in] abs_lines_per_species WS Input
[in] nlte_field WS Input
[in] vmr_field WS Input
[in] t_field WS Input
[in] z_field WS Input
[in] p_grid WS Input
[in] refellipsoid WS Input
[in] surface_props_data WS Input
[in] iy_main_agenda WS Input
[in] ppath_agenda WS Input
[in] iy_space_agenda WS Input
[in] iy_surface_agenda WS Input
[in] iy_cloudbox_agenda WS Input
[in] propmat_clearsky_agenda WS Input
[in] df Generic Input
[in] nz Generic Input
[in] nf Generic Input
[in] r Generic Input (Default: "1.0")
Definition at line 37 of file m_radiation_field.cc.
References ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), and Absorption::nelem().
Referenced by line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D_g(), and nlte_fieldForSingleSpeciesNonOverlappingLines().