ARTS: m_select.h File Reference
m_select.h File Reference
#include "agenda_class.h"
#include "matpackII.h"
#include "messages.h"
#include "mystring.h"
#include "workspace_ng.h"
Functions
template<class T >
void Select (Array< T > &needles, const Array< T > &haystack, const ArrayOfIndex &needleind, const Verbosity &)
void Select (Workspace &, ArrayOfAgenda &needles, const ArrayOfAgenda &haystack, const ArrayOfIndex &needleind, const Verbosity &verbosity)
void Select (Vector &needles, const Vector &haystack, const ArrayOfIndex &needleind, const Verbosity &)
void Select (Matrix &needles, const Matrix &haystack, const ArrayOfIndex &needleind, const Verbosity &)
void Select (Sparse &needles, const Sparse &haystack, const ArrayOfIndex &needleind, const Verbosity &verbosity)
Function Documentation
Select() [1/5]
template<class T > void Select (Array< T > & needles, const Array< T > & haystack, const ArrayOfIndex & needleind, const Verbosity &)
Definition at line 39 of file m_select.h.
References Array< base >::nelem().
Referenced by Select(), Select_sg_ArrayOfAbsorptionLinesArrayOfAbsorptionLines_g(), Select_sg_ArrayOfAgendaArrayOfAgenda_g(), Select_sg_ArrayOfArrayOfAbsorptionLinesArrayOfArrayOfAbsorptionLines_g(), Select_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Select_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Select_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Select_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Select_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Select_sg_ArrayOfArrayOfPropagationMatrixArrayOfArrayOfPropagationMatrix_g(), Select_sg_ArrayOfArrayOfRadiationVectorArrayOfArrayOfRadiationVector_g(), Select_sg_ArrayOfArrayOfScatteringMetaDataArrayOfArrayOfScatteringMetaData_g(), Select_sg_ArrayOfArrayOfSingleScatteringDataArrayOfArrayOfSingleScatteringData_g(), Select_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Select_sg_ArrayOfArrayOfStokesVectorArrayOfArrayOfStokesVector_g(), Select_sg_ArrayOfArrayOfStringArrayOfArrayOfString_g(), Select_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Select_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Select_sg_ArrayOfArrayOfTimeArrayOfArrayOfTime_g(), Select_sg_ArrayOfArrayOfTransmissionMatrixArrayOfArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Select_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Select_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Select_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Select_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Select_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Select_sg_ArrayOfIndexArrayOfIndex_g(), Select_sg_ArrayOfJacobianTargetArrayOfJacobianTarget_g(), Select_sg_ArrayOfMatrixArrayOfMatrix_g(), Select_sg_ArrayOfPpathArrayOfPpath_g(), Select_sg_ArrayOfPropagationMatrixArrayOfPropagationMatrix_g(), Select_sg_ArrayOfQuantumIdentifierArrayOfQuantumIdentifier_g(), Select_sg_ArrayOfRadiationVectorArrayOfRadiationVector_g(), Select_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Select_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Select_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Select_sg_ArrayOfSparseArrayOfSparse_g(), Select_sg_ArrayOfStokesVectorArrayOfStokesVector_g(), Select_sg_ArrayOfStringArrayOfString_g(), Select_sg_ArrayOfTelsemAtlasArrayOfTelsemAtlas_g(), Select_sg_ArrayOfTensor3ArrayOfTensor3_g(), Select_sg_ArrayOfTensor4ArrayOfTensor4_g(), Select_sg_ArrayOfTensor5ArrayOfTensor5_g(), Select_sg_ArrayOfTensor6ArrayOfTensor6_g(), Select_sg_ArrayOfTensor7ArrayOfTensor7_g(), Select_sg_ArrayOfTimeArrayOfTime_g(), Select_sg_ArrayOfTransmissionMatrixArrayOfTransmissionMatrix_g(), Select_sg_ArrayOfVectorArrayOfVector_g(), Select_sg_ArrayOfXsecRecordArrayOfXsecRecord_g(), Select_sg_MatrixMatrix_g(), Select_sg_SparseSparse_g(), Select_sg_VectorVector_g(), and WMRFSelectChannels().
Select() [2/5]
void Select (Matrix & needles, const Matrix & haystack, const ArrayOfIndex & needleind, const Verbosity &) inline
Definition at line 126 of file m_select.h.
References joker, ConstMatrixView::ncols(), Array< base >::nelem(), and ConstMatrixView::nrows().
Select() [3/5]
void Select (Sparse & needles, const Sparse & haystack, const ArrayOfIndex & needleind, const Verbosity & verbosity) inline
Definition at line 164 of file m_select.h.
References CREATE_OUT3, Sparse::ncols(), Array< base >::nelem(), Sparse::nnz(), Sparse::nrows(), and Sparse::rw().
Select() [4/5]
void Select (Vector & needles, const Vector & haystack, const ArrayOfIndex & needleind, const Verbosity &) inline
Definition at line 88 of file m_select.h.
References Array< base >::nelem(), and ConstVectorView::nelem().
Select() [5/5]
void Select (Workspace & , ArrayOfAgenda & needles, const ArrayOfAgenda & haystack, const ArrayOfIndex & needleind, const Verbosity & verbosity) inline
Definition at line 77 of file m_select.h.
References Select(), and ARTS::Var::verbosity().