ARTS: m_tessem.cc File Reference
m_tessem.cc File Reference
This file contains functions that are adapted from TESSEM code which is used to calculate surface emissivity.
#include "file.h"
#include "matpackI.h"
#include "mystring.h"
#include "tessem.h"
Functions
void TessemNNReadAscii (TessemNN &net, const String &net_file, const Verbosity &)
WORKSPACE METHOD: TessemNNReadAscii.
void TestTessem (Vector &outvalues, const TessemNN &net, const Vector &invalues, const Verbosity &verbosity)
WORKSPACE METHOD: TestTessem.
Detailed Description
This file contains functions that are adapted from TESSEM code which is used to calculate surface emissivity.
Definition in file m_tessem.cc.
Function Documentation
TessemNNReadAscii()
void TessemNNReadAscii (TessemNN & tessem_nn, const String & filename, const Verbosity & verbosity)
WORKSPACE METHOD: TessemNNReadAscii.
Reads the initialization data for the TESSEM NeuralNet from an ASCII file.
Author
Oliver Lemke
Parameters
[out] tessem_nn Generic output
[in] filename Generic Input
Definition at line 33 of file m_tessem.cc.
References open_input_file(), and tessem_read_ascii().
Referenced by TessemNNReadAscii_g().
TestTessem()
void TestTessem (Vector & outvalues, const TessemNN & net, const Vector & invalues, const Verbosity & verbosity)
WORKSPACE METHOD: TestTessem.
Example method for TESSEM2.
When using the default neural network parameter files from the Tessem 2 distribution, the input Vector should contain 5 elements: <br> - Frequency (10-700) in GHz. <br> - Theta (0-90) Incidence angle in degrees. <br> - Windspeed (0-25) at 10m (m/s) <br> Higher wind speed can be used, but without garantee. <br> - Surface skin temperature (270-310) in K. <br> - Salinity (0-0.04) in kg/kg
Author
Oliver Lemke
Parameters
[out] outvalues Generic output
[in] net Generic Input
[in] invalues Generic Input
Definition at line 43 of file m_tessem.cc.
References CREATE_OUT1, TessemNN::nb_outputs, Vector::resize(), and tessem_prop_nn().
Referenced by TestTessem_g().