ARTS: m_wigner.cc File Reference
m_wigner.cc File Reference
Wigner symbol interactions.
#include "messages.h"
#include "wigner_functions.h"
Functions
void Wigner6Init (Index &wigner_initialized, const Index &fast_wigner_stored_symbols, const Index &largest_wigner_symbol_parameter, const Verbosity &)
WORKSPACE METHOD: Wigner6Init.
void Wigner3Init (Index &wigner_initialized, const Index &fast_wigner_stored_symbols, const Index &largest_wigner_symbol_parameter, const Verbosity &)
WORKSPACE METHOD: Wigner3Init.
void WignerFastInfoPrint (const Index &wigner_initialized, const Verbosity &)
WORKSPACE METHOD: WignerFastInfoPrint.
void Wigner6Unload (Index &wigner_initialized, const Verbosity &)
WORKSPACE METHOD: Wigner6Unload.
void Wigner3Unload (Index &wigner_initialized, const Verbosity &)
WORKSPACE METHOD: Wigner3Unload.
Detailed Description
Wigner symbol interactions.
Author
Richard Larsson
Date
2018-04-03
Definition in file m_wigner.cc.
Function Documentation
Wigner3Init()
void Wigner3Init (Index & wigner_initialized, const Index & fast_wigner_stored_symbols, const Index & largest_wigner_symbol_parameter, const Verbosity & verbosity)
WORKSPACE METHOD: Wigner3Init.
Initialize the wigner 3 tables
The default values take about 400 Mb memory.
Author
Richard Larsson
Parameters
[out] wigner_initialized WS Output
[in] fast_wigner_stored_symbols Generic Input (Default: "20000000")
[in] largest_wigner_symbol_parameter Generic Input (Default: "250")
Definition at line 39 of file m_wigner.cc.
References make_wigner_ready(), and ARTS::Var::wigner_initialized().
Referenced by Wigner3Init_g().
Wigner3Unload()
void Wigner3Unload (Index & wigner_initialized, const Verbosity & verbosity)
WORKSPACE METHOD: Wigner3Unload.
Unloads the wigner 3 tables
Author
Richard Larsson
Parameters
[in,out] wigner_initialized WS Input/Output
Definition at line 73 of file m_wigner.cc.
References ARTS::Var::wigner_initialized().
Referenced by Wigner3Unload_g().
Wigner6Init()
void Wigner6Init (Index & wigner_initialized, const Index & fast_wigner_stored_symbols, const Index & largest_wigner_symbol_parameter, const Verbosity & verbosity)
WORKSPACE METHOD: Wigner6Init.
Initialize the wigner 3 and 6 tables
The default values take about 1 Gb memory.
Author
Richard Larsson
Parameters
[out] wigner_initialized WS Output
[in] fast_wigner_stored_symbols Generic Input (Default: "20000000")
[in] largest_wigner_symbol_parameter Generic Input (Default: "250")
Definition at line 31 of file m_wigner.cc.
References make_wigner_ready(), and ARTS::Var::wigner_initialized().
Referenced by Wigner6Init_g().
Wigner6Unload()
void Wigner6Unload (Index & wigner_initialized, const Verbosity & verbosity)
WORKSPACE METHOD: Wigner6Unload.
Unloads the wigner 3 and 6 tables
Author
Richard Larsson
Parameters
[in,out] wigner_initialized WS Input/Output
Definition at line 60 of file m_wigner.cc.
References ARTS::Var::wigner_initialized().
Referenced by Wigner6Unload_g().
WignerFastInfoPrint()
void WignerFastInfoPrint (const Index & wigner_initialized, const Verbosity & verbosity)
WORKSPACE METHOD: WignerFastInfoPrint.
Prints the fast wigner table information if compiled with this option
Author
Richard Larsson
Parameters
[in] wigner_initialized WS Input
Definition at line 47 of file m_wigner.cc.
References ARTS::Var::wigner_initialized().
Referenced by WignerFastInfoPrint_g().