ARTS: m_xml.cc File Reference
m_xml.cc File Reference
Non-template implementations of workspace methods for XML IO.
#include "m_xml.h"
Functions
void output_file_formatSetAscii (String &file_format, const Verbosity &)
WORKSPACE METHOD: output_file_formatSetAscii.
void output_file_formatSetZippedAscii (String &file_format, const Verbosity &)
WORKSPACE METHOD: output_file_formatSetZippedAscii.
void output_file_formatSetBinary (String &file_format, const Verbosity &)
WORKSPACE METHOD: output_file_formatSetBinary.
Detailed Description
Non-template implementations of workspace methods for XML IO.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2013-03-04
Definition in file m_xml.cc.
Function Documentation
output_file_formatSetAscii()
void output_file_formatSetAscii (String & output_file_format, const Verbosity & verbosity)
WORKSPACE METHOD: output_file_formatSetAscii.
Sets the output file format to ASCII.
Author
Oliver Lemke
Parameters
[out] output_file_format WS Output
Definition at line 30 of file m_xml.cc.
Referenced by output_file_formatSetAscii_g().
output_file_formatSetBinary()
void output_file_formatSetBinary (String & output_file_format, const Verbosity & verbosity)
WORKSPACE METHOD: output_file_formatSetBinary.
Sets the output file format to binary.
Author
Oliver Lemke
Parameters
[out] output_file_format WS Output
Definition at line 44 of file m_xml.cc.
Referenced by output_file_formatSetBinary_g().
output_file_formatSetZippedAscii()
void output_file_formatSetZippedAscii (String & output_file_format, const Verbosity & verbosity)
WORKSPACE METHOD: output_file_formatSetZippedAscii.
Sets the output file format to zipped ASCII.
Author
Oliver Lemke
Parameters
[out] output_file_format WS Output
Definition at line 37 of file m_xml.cc.
Referenced by output_file_formatSetZippedAscii_g().