ARTS: m_xml.h File Reference
m_xml.h File Reference
Workspace methods and template functions for supergeneric XML IO.
#include "agenda_class.h"
#include "exceptions.h"
#include "workspace_ng.h"
#include "xml_io.h"
Functions
template<typename T >
void ReadXML (T &v, const String &v_name, const String &f, const String &f_name, const Verbosity &verbosity)
WORKSPACE METHOD: ReadXML.
template<typename T >
void ReadXML (Workspace &ws, T &v, const String &v_name, const String &f, const String &f_name, const Verbosity &verbosity)
template<typename T >
void ReadXMLIndexed (T &v, const String &v_name, const Index &file_index, const String &f, const Index &digits, const String &f_name, const String &digits_name, const Verbosity &verbosity)
WORKSPACE METHOD: ReadXMLIndexed.
template<typename T >
void ReadXMLIndexed (Workspace &ws, T &v, const String &v_name, const Index &file_index, const String &f, const Index &digits, const String &f_name, const String &digits_name, const Verbosity &verbosity)
template<typename T >
void WriteXML (const String &file_format, const T &v, const String &f, const Index &no_clobber, const String &v_name, const String &f_name, const String &no_clobber_name, const Verbosity &verbosity)
WORKSPACE METHOD: WriteXML.
template<typename T >
void WriteXML (Workspace &ws, const String &file_format, const T &v, const String &f, const Index &no_clobber, const String &v_name, const String &f_name, const String &no_clobber_name, const Verbosity &verbosity)
template<typename T >
void WriteXMLIndexed (const String &file_format, const Index &file_index, const T &v, const String &f, const Index &digits, const String &v_name, const String &f_name, const String &digits_name, const Verbosity &verbosity)
WORKSPACE METHOD: WriteXMLIndexed.
template<typename T >
void WriteXMLIndexed (Workspace &ws, const String &file_format, const Index &file_index, const T &v, const String &f, const Index &digits, const String &v_name, const String &f_name, const String &digits_name, const Verbosity &verbosity)
Detailed Description
Workspace methods and template functions for supergeneric XML IO.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
2002-06-18
Definition in file m_xml.h.
Function Documentation
ReadXML() [1/2]
template<typename T > void ReadXML (T & out, const String & out_wsvname, const String & filename, const String & filename_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: ReadXML.
Reads a workspace variable from an XML file.
This method can read variables of any group.
If the filename is omitted, the variable is read from <basename>.<variable_name>.xml. If the given filename does not exist, this method will also look for files with an added .xml, .xml.gz and .gz extension
Author
Oliver Lemke
Parameters
[out] out Supergeneric output
[in] out_wsvname Generic Output Name
[in] filename Generic Input (Default: "")
[in] filename_wsvname Generic Input Name
Definition at line 41 of file m_xml.h.
References filename_xml(), v, ARTS::Var::verbosity(), and xml_read_from_file().
Referenced by ReadXML(), ReadXML_sg_AbsorptionLines_g(), ReadXML_sg_Agenda_g(), ReadXML_sg_ArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfAgenda_g(), ReadXML_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXML_sg_ArrayOfArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfArrayOfIndex_g(), ReadXML_sg_ArrayOfArrayOfMatrix_g(), ReadXML_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfArrayOfStokesVector_g(), ReadXML_sg_ArrayOfArrayOfString_g(), ReadXML_sg_ArrayOfArrayOfTensor3_g(), ReadXML_sg_ArrayOfArrayOfTensor6_g(), ReadXML_sg_ArrayOfArrayOfTime_g(), ReadXML_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfArrayOfVector_g(), ReadXML_sg_ArrayOfCIARecord_g(), ReadXML_sg_ArrayOfGriddedField1_g(), ReadXML_sg_ArrayOfGriddedField2_g(), ReadXML_sg_ArrayOfGriddedField3_g(), ReadXML_sg_ArrayOfGriddedField4_g(), ReadXML_sg_ArrayOfIndex_g(), ReadXML_sg_ArrayOfJacobianTarget_g(), ReadXML_sg_ArrayOfMatrix_g(), ReadXML_sg_ArrayOfPpath_g(), ReadXML_sg_ArrayOfPropagationMatrix_g(), ReadXML_sg_ArrayOfQuantumIdentifier_g(), ReadXML_sg_ArrayOfRadiationVector_g(), ReadXML_sg_ArrayOfRetrievalQuantity_g(), ReadXML_sg_ArrayOfScatteringMetaData_g(), ReadXML_sg_ArrayOfSingleScatteringData_g(), ReadXML_sg_ArrayOfSparse_g(), ReadXML_sg_ArrayOfSpeciesTag_g(), ReadXML_sg_ArrayOfStokesVector_g(), ReadXML_sg_ArrayOfString_g(), ReadXML_sg_ArrayOfTelsemAtlas_g(), ReadXML_sg_ArrayOfTensor3_g(), ReadXML_sg_ArrayOfTensor4_g(), ReadXML_sg_ArrayOfTensor5_g(), ReadXML_sg_ArrayOfTensor6_g(), ReadXML_sg_ArrayOfTensor7_g(), ReadXML_sg_ArrayOfTime_g(), ReadXML_sg_ArrayOfTransmissionMatrix_g(), ReadXML_sg_ArrayOfVector_g(), ReadXML_sg_ArrayOfXsecRecord_g(), ReadXML_sg_CIARecord_g(), ReadXML_sg_CovarianceMatrix_g(), ReadXML_sg_EnergyLevelMap_g(), ReadXML_sg_GasAbsLookup_g(), ReadXML_sg_GriddedField1_g(), ReadXML_sg_GriddedField2_g(), ReadXML_sg_GriddedField3_g(), ReadXML_sg_GriddedField4_g(), ReadXML_sg_GriddedField5_g(), ReadXML_sg_GriddedField6_g(), ReadXML_sg_GridPos_g(), ReadXML_sg_HitranRelaxationMatrixData_g(), ReadXML_sg_Index_g(), ReadXML_sg_JacobianTarget_g(), ReadXML_sg_MapOfErrorCorrectedSuddenData_g(), ReadXML_sg_Matrix_g(), ReadXML_sg_MCAntenna_g(), ReadXML_sg_Numeric_g(), ReadXML_sg_Ppath_g(), ReadXML_sg_PropagationMatrix_g(), ReadXML_sg_QuantumIdentifier_g(), ReadXML_sg_RadiationVector_g(), ReadXML_sg_Rational_g(), ReadXML_sg_ScatteringMetaData_g(), ReadXML_sg_SingleScatteringData_g(), ReadXML_sg_Sparse_g(), ReadXML_sg_SpeciesIsotopologueRatios_g(), ReadXML_sg_StokesVector_g(), ReadXML_sg_String_g(), ReadXML_sg_TelsemAtlas_g(), ReadXML_sg_Tensor3_g(), ReadXML_sg_Tensor4_g(), ReadXML_sg_Tensor5_g(), ReadXML_sg_Tensor6_g(), ReadXML_sg_Tensor7_g(), ReadXML_sg_TessemNN_g(), ReadXML_sg_Time_g(), ReadXML_sg_Timer_g(), ReadXML_sg_TransmissionMatrix_g(), ReadXML_sg_Vector_g(), and ReadXML_sg_Verbosity_g().
ReadXML() [2/2]
template<typename T > void ReadXML (Workspace & ws, T & v, const String & v_name, const String & f, const String & f_name, const Verbosity & verbosity)
Definition at line 60 of file m_xml.h.
References ReadXML(), v, and ARTS::Var::verbosity().
ReadXMLIndexed() [1/2]
template<typename T > void ReadXMLIndexed (T & out, const String & out_wsvname, const Index & file_index, const String & filename, const Index & digits, const String & filename_wsvname, const String & digits_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: ReadXMLIndexed.
As ReadXML, but reads indexed file names.
The variable is read from a file with name: <br> <filename>.<file_index>.xml. where <file_index> is the value of file_index.
This means that filename shall here not include the .xml extension. Omitting filename works as for ReadXML.
Author
Oliver Lemke
Parameters
[out] out Supergeneric output
[in] out_wsvname Generic Output Name
[in] file_index WS Input
[in] filename Generic Input (Default: "")
[in] digits Generic Input (Default: "0")
[in] filename_wsvname Generic Input Name
[in] digits_wsvname Generic Input Name
Definition at line 75 of file m_xml.h.
References ARTS::Var::file_index(), filename_xml_with_index(), v, ARTS::Var::verbosity(), and xml_read_from_file().
Referenced by ReadXMLIndexed(), ReadXMLIndexed_sg_AbsorptionLines_g(), ReadXMLIndexed_sg_Agenda_g(), ReadXMLIndexed_sg_ArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfAgenda_g(), ReadXMLIndexed_sg_ArrayOfArrayOfAbsorptionLines_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfCIARecord_g(), ReadXMLIndexed_sg_ArrayOfGriddedField1_g(), ReadXMLIndexed_sg_ArrayOfGriddedField2_g(), ReadXMLIndexed_sg_ArrayOfGriddedField3_g(), ReadXMLIndexed_sg_ArrayOfGriddedField4_g(), ReadXMLIndexed_sg_ArrayOfIndex_g(), ReadXMLIndexed_sg_ArrayOfJacobianTarget_g(), ReadXMLIndexed_sg_ArrayOfMatrix_g(), ReadXMLIndexed_sg_ArrayOfPpath_g(), ReadXMLIndexed_sg_ArrayOfPropagationMatrix_g(), ReadXMLIndexed_sg_ArrayOfQuantumIdentifier_g(), ReadXMLIndexed_sg_ArrayOfRadiationVector_g(), ReadXMLIndexed_sg_ArrayOfRetrievalQuantity_g(), ReadXMLIndexed_sg_ArrayOfScatteringMetaData_g(), ReadXMLIndexed_sg_ArrayOfSingleScatteringData_g(), ReadXMLIndexed_sg_ArrayOfSparse_g(), ReadXMLIndexed_sg_ArrayOfSpeciesTag_g(), ReadXMLIndexed_sg_ArrayOfStokesVector_g(), ReadXMLIndexed_sg_ArrayOfString_g(), ReadXMLIndexed_sg_ArrayOfTelsemAtlas_g(), ReadXMLIndexed_sg_ArrayOfTensor3_g(), ReadXMLIndexed_sg_ArrayOfTensor4_g(), ReadXMLIndexed_sg_ArrayOfTensor5_g(), ReadXMLIndexed_sg_ArrayOfTensor6_g(), ReadXMLIndexed_sg_ArrayOfTensor7_g(), ReadXMLIndexed_sg_ArrayOfTime_g(), ReadXMLIndexed_sg_ArrayOfTransmissionMatrix_g(), ReadXMLIndexed_sg_ArrayOfVector_g(), ReadXMLIndexed_sg_ArrayOfXsecRecord_g(), ReadXMLIndexed_sg_CIARecord_g(), ReadXMLIndexed_sg_CovarianceMatrix_g(), ReadXMLIndexed_sg_EnergyLevelMap_g(), ReadXMLIndexed_sg_GasAbsLookup_g(), ReadXMLIndexed_sg_GriddedField1_g(), ReadXMLIndexed_sg_GriddedField2_g(), ReadXMLIndexed_sg_GriddedField3_g(), ReadXMLIndexed_sg_GriddedField4_g(), ReadXMLIndexed_sg_GriddedField5_g(), ReadXMLIndexed_sg_GriddedField6_g(), ReadXMLIndexed_sg_GridPos_g(), ReadXMLIndexed_sg_HitranRelaxationMatrixData_g(), ReadXMLIndexed_sg_Index_g(), ReadXMLIndexed_sg_JacobianTarget_g(), ReadXMLIndexed_sg_MapOfErrorCorrectedSuddenData_g(), ReadXMLIndexed_sg_Matrix_g(), ReadXMLIndexed_sg_MCAntenna_g(), ReadXMLIndexed_sg_Numeric_g(), ReadXMLIndexed_sg_Ppath_g(), ReadXMLIndexed_sg_PropagationMatrix_g(), ReadXMLIndexed_sg_QuantumIdentifier_g(), ReadXMLIndexed_sg_RadiationVector_g(), ReadXMLIndexed_sg_Rational_g(), ReadXMLIndexed_sg_ScatteringMetaData_g(), ReadXMLIndexed_sg_SingleScatteringData_g(), ReadXMLIndexed_sg_Sparse_g(), ReadXMLIndexed_sg_SpeciesIsotopologueRatios_g(), ReadXMLIndexed_sg_StokesVector_g(), ReadXMLIndexed_sg_String_g(), ReadXMLIndexed_sg_TelsemAtlas_g(), ReadXMLIndexed_sg_Tensor3_g(), ReadXMLIndexed_sg_Tensor4_g(), ReadXMLIndexed_sg_Tensor5_g(), ReadXMLIndexed_sg_Tensor6_g(), ReadXMLIndexed_sg_Tensor7_g(), ReadXMLIndexed_sg_TessemNN_g(), ReadXMLIndexed_sg_Time_g(), ReadXMLIndexed_sg_Timer_g(), ReadXMLIndexed_sg_TransmissionMatrix_g(), ReadXMLIndexed_sg_Vector_g(), and ReadXMLIndexed_sg_Verbosity_g().
ReadXMLIndexed() [2/2]
template<typename T > void ReadXMLIndexed (Workspace & ws, T & v, const String & v_name, const Index & file_index, const String & f, const Index & digits, const String & f_name, const String & digits_name, const Verbosity & verbosity)
Definition at line 98 of file m_xml.h.
References ARTS::Var::file_index(), ReadXMLIndexed(), v, and ARTS::Var::verbosity().
WriteXML() [1/2]
template<typename T > void WriteXML (const String & output_file_format, const T & in, const String & filename, const Index & no_clobber, const String & in_wsvname, const String & filename_wsvname, const String & no_clobber_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: WriteXML.
Writes a workspace variable to an XML file.
This method can write variables of any group.
If the filename is omitted, the variable is written to <basename>.<variable_name>.xml. If no_clobber is set to 1, an increasing number will be appended to the filename if the file already exists.
Author
Oliver Lemke
Parameters
[in] output_file_format WS Input
[in] in Generic Input
[in] filename Generic Input (Default: "")
[in] no_clobber Generic Input (Default: "0")
[in] in_wsvname Generic Input Name
[in] filename_wsvname Generic Input Name
[in] no_clobber_wsvname Generic Input Name
Definition at line 118 of file m_xml.h.
References filename_xml(), string2filetype(), v, ARTS::Var::verbosity(), and xml_write_to_file().
Referenced by abs_lines_per_speciesWriteSplitXML(), abs_linesWriteSpeciesSplitXML(), abs_linesWriteSplitXML(), ppathWriteXMLPartial(), WriteXML(), WriteXML_sg_AbsorptionLines_g(), WriteXML_sg_Agenda_g(), WriteXML_sg_ArrayOfAbsorptionLines_g(), WriteXML_sg_ArrayOfAgenda_g(), WriteXML_sg_ArrayOfArrayOfAbsorptionLines_g(), WriteXML_sg_ArrayOfArrayOfGriddedField1_g(), WriteXML_sg_ArrayOfArrayOfGriddedField2_g(), WriteXML_sg_ArrayOfArrayOfGriddedField3_g(), WriteXML_sg_ArrayOfArrayOfIndex_g(), WriteXML_sg_ArrayOfArrayOfMatrix_g(), WriteXML_sg_ArrayOfArrayOfPropagationMatrix_g(), WriteXML_sg_ArrayOfArrayOfRadiationVector_g(), WriteXML_sg_ArrayOfArrayOfScatteringMetaData_g(), WriteXML_sg_ArrayOfArrayOfSingleScatteringData_g(), WriteXML_sg_ArrayOfArrayOfSpeciesTag_g(), WriteXML_sg_ArrayOfArrayOfStokesVector_g(), WriteXML_sg_ArrayOfArrayOfString_g(), WriteXML_sg_ArrayOfArrayOfTensor3_g(), WriteXML_sg_ArrayOfArrayOfTensor6_g(), WriteXML_sg_ArrayOfArrayOfTime_g(), WriteXML_sg_ArrayOfArrayOfTransmissionMatrix_g(), WriteXML_sg_ArrayOfArrayOfVector_g(), WriteXML_sg_ArrayOfCIARecord_g(), WriteXML_sg_ArrayOfGriddedField1_g(), WriteXML_sg_ArrayOfGriddedField2_g(), WriteXML_sg_ArrayOfGriddedField3_g(), WriteXML_sg_ArrayOfGriddedField4_g(), WriteXML_sg_ArrayOfIndex_g(), WriteXML_sg_ArrayOfJacobianTarget_g(), WriteXML_sg_ArrayOfMatrix_g(), WriteXML_sg_ArrayOfPpath_g(), WriteXML_sg_ArrayOfPropagationMatrix_g(), WriteXML_sg_ArrayOfQuantumIdentifier_g(), WriteXML_sg_ArrayOfRadiationVector_g(), WriteXML_sg_ArrayOfRetrievalQuantity_g(), WriteXML_sg_ArrayOfScatteringMetaData_g(), WriteXML_sg_ArrayOfSingleScatteringData_g(), WriteXML_sg_ArrayOfSparse_g(), WriteXML_sg_ArrayOfSpeciesTag_g(), WriteXML_sg_ArrayOfStokesVector_g(), WriteXML_sg_ArrayOfString_g(), WriteXML_sg_ArrayOfTelsemAtlas_g(), WriteXML_sg_ArrayOfTensor3_g(), WriteXML_sg_ArrayOfTensor4_g(), WriteXML_sg_ArrayOfTensor5_g(), WriteXML_sg_ArrayOfTensor6_g(), WriteXML_sg_ArrayOfTensor7_g(), WriteXML_sg_ArrayOfTime_g(), WriteXML_sg_ArrayOfTransmissionMatrix_g(), WriteXML_sg_ArrayOfVector_g(), WriteXML_sg_ArrayOfXsecRecord_g(), WriteXML_sg_CIARecord_g(), WriteXML_sg_CovarianceMatrix_g(), WriteXML_sg_EnergyLevelMap_g(), WriteXML_sg_GasAbsLookup_g(), WriteXML_sg_GriddedField1_g(), WriteXML_sg_GriddedField2_g(), WriteXML_sg_GriddedField3_g(), WriteXML_sg_GriddedField4_g(), WriteXML_sg_GriddedField5_g(), WriteXML_sg_GriddedField6_g(), WriteXML_sg_GridPos_g(), WriteXML_sg_HitranRelaxationMatrixData_g(), WriteXML_sg_Index_g(), WriteXML_sg_JacobianTarget_g(), WriteXML_sg_MapOfErrorCorrectedSuddenData_g(), WriteXML_sg_Matrix_g(), WriteXML_sg_MCAntenna_g(), WriteXML_sg_Numeric_g(), WriteXML_sg_Ppath_g(), WriteXML_sg_PropagationMatrix_g(), WriteXML_sg_QuantumIdentifier_g(), WriteXML_sg_RadiationVector_g(), WriteXML_sg_Rational_g(), WriteXML_sg_ScatteringMetaData_g(), WriteXML_sg_SingleScatteringData_g(), WriteXML_sg_Sparse_g(), WriteXML_sg_SpeciesIsotopologueRatios_g(), WriteXML_sg_StokesVector_g(), WriteXML_sg_String_g(), WriteXML_sg_TelsemAtlas_g(), WriteXML_sg_Tensor3_g(), WriteXML_sg_Tensor4_g(), WriteXML_sg_Tensor5_g(), WriteXML_sg_Tensor6_g(), WriteXML_sg_Tensor7_g(), WriteXML_sg_TessemNN_g(), WriteXML_sg_Time_g(), WriteXML_sg_Timer_g(), WriteXML_sg_TransmissionMatrix_g(), WriteXML_sg_Vector_g(), WriteXML_sg_Verbosity_g(), and WriteXMLIndexed().
WriteXML() [2/2]
template<typename T > void WriteXML (Workspace & ws, const String & file_format, const T & v, const String & f, const Index & no_clobber, const String & v_name, const String & f_name, const String & no_clobber_name, const Verbosity & verbosity)
Definition at line 168 of file m_xml.h.
References v, ARTS::Var::verbosity(), and WriteXML().
WriteXMLIndexed() [1/2]
template<typename T > void WriteXMLIndexed (const String & output_file_format, const Index & file_index, const T & in, const String & filename, const Index & digits, const String & in_wsvname, const String & filename_wsvname, const String & digits_wsvname, const Verbosity & verbosity)
WORKSPACE METHOD: WriteXMLIndexed.
As WriteXML, but creates indexed file names.
The variable is written to a file with name: <br> <filename>.<file_index>.xml. where <file_index> is the value of file_index.
This means that filename shall here not include the .xml extension. Omitting filename works as for WriteXML.
Author
Patrick Eriksson, Oliver Lemke
Parameters
[in] output_file_format WS Input
[in] file_index WS Input
[in] in Generic Input
[in] filename Generic Input (Default: "")
[in] digits Generic Input (Default: "0")
[in] in_wsvname Generic Input Name
[in] filename_wsvname Generic Input Name
[in] digits_wsvname Generic Input Name
Definition at line 192 of file m_xml.h.
References ARTS::Var::file_index(), filename_xml_with_index(), v, ARTS::Var::verbosity(), and WriteXML().
Referenced by WriteXMLIndexed(), WriteXMLIndexed_sg_AbsorptionLines_g(), WriteXMLIndexed_sg_Agenda_g(), WriteXMLIndexed_sg_ArrayOfAbsorptionLines_g(), WriteXMLIndexed_sg_ArrayOfAgenda_g(), WriteXMLIndexed_sg_ArrayOfArrayOfAbsorptionLines_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField1_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField2_g(), WriteXMLIndexed_sg_ArrayOfArrayOfGriddedField3_g(), WriteXMLIndexed_sg_ArrayOfArrayOfIndex_g(), WriteXMLIndexed_sg_ArrayOfArrayOfMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfPropagationMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfRadiationVector_g(), WriteXMLIndexed_sg_ArrayOfArrayOfScatteringMetaData_g(), WriteXMLIndexed_sg_ArrayOfArrayOfSingleScatteringData_g(), WriteXMLIndexed_sg_ArrayOfArrayOfSpeciesTag_g(), WriteXMLIndexed_sg_ArrayOfArrayOfStokesVector_g(), WriteXMLIndexed_sg_ArrayOfArrayOfString_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTensor3_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTensor6_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTime_g(), WriteXMLIndexed_sg_ArrayOfArrayOfTransmissionMatrix_g(), WriteXMLIndexed_sg_ArrayOfArrayOfVector_g(), WriteXMLIndexed_sg_ArrayOfCIARecord_g(), WriteXMLIndexed_sg_ArrayOfGriddedField1_g(), WriteXMLIndexed_sg_ArrayOfGriddedField2_g(), WriteXMLIndexed_sg_ArrayOfGriddedField3_g(), WriteXMLIndexed_sg_ArrayOfGriddedField4_g(), WriteXMLIndexed_sg_ArrayOfIndex_g(), WriteXMLIndexed_sg_ArrayOfJacobianTarget_g(), WriteXMLIndexed_sg_ArrayOfMatrix_g(), WriteXMLIndexed_sg_ArrayOfPpath_g(), WriteXMLIndexed_sg_ArrayOfPropagationMatrix_g(), WriteXMLIndexed_sg_ArrayOfQuantumIdentifier_g(), WriteXMLIndexed_sg_ArrayOfRadiationVector_g(), WriteXMLIndexed_sg_ArrayOfRetrievalQuantity_g(), WriteXMLIndexed_sg_ArrayOfScatteringMetaData_g(), WriteXMLIndexed_sg_ArrayOfSingleScatteringData_g(), WriteXMLIndexed_sg_ArrayOfSparse_g(), WriteXMLIndexed_sg_ArrayOfSpeciesTag_g(), WriteXMLIndexed_sg_ArrayOfStokesVector_g(), WriteXMLIndexed_sg_ArrayOfString_g(), WriteXMLIndexed_sg_ArrayOfTelsemAtlas_g(), WriteXMLIndexed_sg_ArrayOfTensor3_g(), WriteXMLIndexed_sg_ArrayOfTensor4_g(), WriteXMLIndexed_sg_ArrayOfTensor5_g(), WriteXMLIndexed_sg_ArrayOfTensor6_g(), WriteXMLIndexed_sg_ArrayOfTensor7_g(), WriteXMLIndexed_sg_ArrayOfTime_g(), WriteXMLIndexed_sg_ArrayOfTransmissionMatrix_g(), WriteXMLIndexed_sg_ArrayOfVector_g(), WriteXMLIndexed_sg_ArrayOfXsecRecord_g(), WriteXMLIndexed_sg_CIARecord_g(), WriteXMLIndexed_sg_CovarianceMatrix_g(), WriteXMLIndexed_sg_EnergyLevelMap_g(), WriteXMLIndexed_sg_GasAbsLookup_g(), WriteXMLIndexed_sg_GriddedField1_g(), WriteXMLIndexed_sg_GriddedField2_g(), WriteXMLIndexed_sg_GriddedField3_g(), WriteXMLIndexed_sg_GriddedField4_g(), WriteXMLIndexed_sg_GriddedField5_g(), WriteXMLIndexed_sg_GriddedField6_g(), WriteXMLIndexed_sg_GridPos_g(), WriteXMLIndexed_sg_HitranRelaxationMatrixData_g(), WriteXMLIndexed_sg_Index_g(), WriteXMLIndexed_sg_JacobianTarget_g(), WriteXMLIndexed_sg_MapOfErrorCorrectedSuddenData_g(), WriteXMLIndexed_sg_Matrix_g(), WriteXMLIndexed_sg_MCAntenna_g(), WriteXMLIndexed_sg_Numeric_g(), WriteXMLIndexed_sg_Ppath_g(), WriteXMLIndexed_sg_PropagationMatrix_g(), WriteXMLIndexed_sg_QuantumIdentifier_g(), WriteXMLIndexed_sg_RadiationVector_g(), WriteXMLIndexed_sg_Rational_g(), WriteXMLIndexed_sg_ScatteringMetaData_g(), WriteXMLIndexed_sg_SingleScatteringData_g(), WriteXMLIndexed_sg_Sparse_g(), WriteXMLIndexed_sg_SpeciesIsotopologueRatios_g(), WriteXMLIndexed_sg_StokesVector_g(), WriteXMLIndexed_sg_String_g(), WriteXMLIndexed_sg_TelsemAtlas_g(), WriteXMLIndexed_sg_Tensor3_g(), WriteXMLIndexed_sg_Tensor4_g(), WriteXMLIndexed_sg_Tensor5_g(), WriteXMLIndexed_sg_Tensor6_g(), WriteXMLIndexed_sg_Tensor7_g(), WriteXMLIndexed_sg_TessemNN_g(), WriteXMLIndexed_sg_Time_g(), WriteXMLIndexed_sg_Timer_g(), WriteXMLIndexed_sg_TransmissionMatrix_g(), WriteXMLIndexed_sg_Vector_g(), and WriteXMLIndexed_sg_Verbosity_g().
WriteXMLIndexed() [2/2]
template<typename T > void WriteXMLIndexed (Workspace & ws, const String & file_format, const Index & file_index, const T & v, const String & f, const Index & digits, const String & v_name, const String & f_name, const String & digits_name, const Verbosity & verbosity)
Definition at line 214 of file m_xml.h.
References ARTS::Var::file_index(), v, ARTS::Var::verbosity(), and WriteXMLIndexed().