ARTS: m_zeeman.cc File Reference
m_zeeman.cc File Reference
#include "global_data.h"
#include "propagationmatrix.h"
#include "zeeman.h"
Functions
void propmat_clearskyAddZeeman (ArrayOfPropagationMatrix &propmat_clearsky, ArrayOfStokesVector &nlte_source, ArrayOfPropagationMatrix &dpropmat_clearsky_dx, ArrayOfStokesVector &dnlte_dx_source, ArrayOfStokesVector &nlte_dsource_dx, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const SpeciesAuxData &isotopologue_ratios, const SpeciesAuxData &partition_functions, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const EnergyLevelMap &rtp_nlte, const Vector &rtp_vmr, const Vector &rtp_mag, const Vector &ppath_los, const Index &atmosphere_dim, const Index &lbl_checked, const Index &manual_zeeman_tag, const Numeric &manual_zeeman_magnetic_field_strength, const Numeric &manual_zeeman_theta, const Numeric &manual_zeeman_eta, const Verbosity &)
WORKSPACE METHOD: propmat_clearskyAddZeeman.
Function Documentation
propmat_clearskyAddZeeman()
void propmat_clearskyAddZeeman (ArrayOfPropagationMatrix & propmat_clearsky, ArrayOfStokesVector & nlte_source, ArrayOfPropagationMatrix & dpropmat_clearsky_dx, ArrayOfStokesVector & dnlte_dx_source, ArrayOfStokesVector & nlte_dsource_dx, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const SpeciesAuxData & isotopologue_ratios, const SpeciesAuxData & partition_functions, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const EnergyLevelMap & rtp_nlte, const Vector & rtp_vmr, const Vector & rtp_mag, const Vector & rtp_los, const Index & atmosphere_dim, const Index & lbl_checked, const Index & manual_zeeman_tag, const Numeric & manual_zeeman_magnetic_field_strength, const Numeric & manual_zeeman_theta, const Numeric & manual_zeeman_eta, const Verbosity & verbosity)
WORKSPACE METHOD: propmat_clearskyAddZeeman.
Calculates Zeeman-affected polarized propagation matrix and its derivatives.
Otherwise as propmat_clearskyAddFromLookup
Author
Richard Larsson
Parameters
[in,out] propmat_clearsky WS Input/Output
[in,out] nlte_source WS Input/Output
[in,out] dpropmat_clearsky_dx WS Input/Output
[in,out] dnlte_dx_source WS Input/Output
[in,out] nlte_dsource_dx WS Input/Output
[in] abs_lines_per_species WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] jacobian_quantities WS Input
[in] isotopologue_ratios WS Input
[in] partition_functions WS Input
[in] rtp_pressure WS Input
[in] rtp_temperature WS Input
[in] rtp_nlte WS Input
[in] rtp_vmr WS Input
[in] rtp_mag WS Input
[in] rtp_los WS Input
[in] atmosphere_dim WS Input
[in] lbl_checked WS Input
[in] manual_zeeman_tag Generic Input (Default: "0")
[in] manual_zeeman_magnetic_field_strength Generic Input (Default: "1.0")
[in] manual_zeeman_theta Generic Input (Default: "0.0")
[in] manual_zeeman_eta Generic Input (Default: "0.0")
Definition at line 35 of file m_zeeman.cc.
References ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), ARTS::Var::atmosphere_dim(), ARTS::Var::dnlte_dx_source(), ARTS::Var::dpropmat_clearsky_dx(), ARTS::Var::f_grid(), ARTS::Var::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), ARTS::Var::lbl_checked(), mirror_los(), ConstVectorView::nelem(), ARTS::Var::nlte_dsource_dx(), ARTS::Var::nlte_source(), ARTS::Var::partition_functions(), ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_los(), ARTS::Var::rtp_mag(), ARTS::Var::rtp_nlte(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), ARTS::Var::rtp_vmr(), and zeeman_on_the_fly().
Referenced by ARTS::Agenda::propmat_clearsky_agenda_on_the_fly_zeeman(), and propmat_clearskyAddZeeman_g().