ARTS: make_auto_md_cc.cc File Reference
make_auto_md_cc.cc File Reference
#include "agenda_record.h"
#include "array.h"
#include "arts.h"
#include "file.h"
#include "global_data.h"
#include "methods.h"
#include "workspace_ng.h"
Functions
void align (ofstream &ofs, bool &is_first_parameter, const String &indent)
int main ()
Function Documentation
align()
void align (ofstream & ofs, bool & is_first_parameter, const String & indent)
Definition at line 27 of file make_auto_md_cc.cc.
main()
int main (void)
Definition at line 38 of file make_auto_md_cc.cc.
References MdRecord::ActualGroups(), MdRecord::AgendaMethod(), define_md_data_raw(), Workspace::define_wsv_data(), define_wsv_group_names(), Workspace::define_wsv_map(), expand_md_data_raw_to_md_data(), MdRecord::GInType(), MdRecord::GOutType(), MdRecord::In(), MdRecord::InOnly(), is_agenda_group_id(), global_data::md_data, MdRecord::Name(), my_basic_string< charT >::nelem(), Array< base >::nelem(), Absorption::nelem(), open_output_file(), MdRecord::Out(), MdRecord::Supergeneric(), Workspace::wsv_data, and global_data::wsv_group_names.