ARTS: make_auto_md_h.cc File Reference
make_auto_md_h.cc File Reference
This is a little C++ program that generates the file auto_md.h from the workspace methods data md_data.
#include "agenda_record.h"
#include "array.h"
#include "arts.h"
#include "file.h"
#include "global_data.h"
#include "methods.h"
#include "workspace_ng.h"
Functions
void align (ofstream &ofs, bool &is_first_parameter, const String &indent)
void write_method_header_documentation (ofstream &ofs, const MdRecord &mdd)
Write method header documentation.
void write_method_header (ofstream &ofs, const MdRecord &mdd)
Write a method header.
bool md_sanity_checks (const Array< MdRecord > &md_data)
int main ()
Detailed Description
This is a little C++ program that generates the file auto_md.h from the workspace methods data md_data.
The file auto_md.h declares the enum type MdHandle that is used to access the method data, so it has to be made sure that the two are allways consistent.
A second file is produced: auto_md.cc. This contains the ‘get-away’ functions that provided the interface between the engine and the workspace methods. The get-functions all have the same arguments:
void get_away_example_g(Workspace& ws,
const MRecord& mr);
Their names all have the extension _g
Pointers to the get-away functions are stored in the array ‘getaway’.
Each get-away function simply contains a function call to the matching workspace method. The parameters are arranged similar to the follwing example:
void SomeMethod(owsv1,iwsv1,iwsv2,iwsv3,c1,c2,c3,...)
First come the output workspace variables, then the input workspace variables, and then the control parameters. There can be an arbitrary number of parameters of each type, but the most usual case is to have only one output workspace variable.
The same variable may be both in the list of input and in the list of output workspace variables. This case makes good sense, actually, if you think for example of a method that adds an offset to the absorption coefficients. IN THAT CASE THE VARIABLE IS ADDED TO THE LIST ONLY ONCE, namely among the OUTPUT variables.
For generic methods the names of the actual workspace variables are also passed on to the method function.
Author
Stefan Buehler
Date
2000-07-29
Definition in file make_auto_md_h.cc.
Function Documentation
align()
void align (ofstream & ofs, bool & is_first_parameter, const String & indent)
Definition at line 77 of file make_auto_md_h.cc.
Referenced by write_method_header(), and write_method_header_documentation().
main()
int main (void)
Definition at line 562 of file make_auto_md_h.cc.
References MdRecord::ActualGroups(), global_data::agenda_data, define_agenda_data(), define_md_data_raw(), Workspace::define_wsv_data(), define_wsv_group_names(), Workspace::define_wsv_map(), expand_md_data_raw_to_md_data(), get_wsv_group_id(), get_wsv_id(), global_data::md_data, global_data::md_data_raw, md_sanity_checks(), MdRecord::Name(), open_output_file(), MdRecord::Supergeneric(), MdRecord::UsesTemplates(), write_agenda_wrapper_header(), write_method_header(), write_method_header_documentation(), Workspace::wsv_data, and x.
md_sanity_checks()
bool md_sanity_checks (const Array< MdRecord > & md_data)
Definition at line 519 of file make_auto_md_h.cc.
References check_newline(), Zeeman::end(), and global_data::md_data.
Referenced by main().
write_method_header()
void write_method_header (ofstream & ofs, const MdRecord & mdd)
Write a method header.
Parameters
ofs The stream to write to.
mdd Method lookup data.
Definition at line 263 of file make_auto_md_h.cc.
References MdRecord::AgendaMethod(), align(), MdRecord::GIn(), MdRecord::GInType(), MdRecord::GOut(), MdRecord::GOutType(), MdRecord::In(), MdRecord::InOnly(), is_agenda_group_id(), MdRecord::Name(), Array< base >::nelem(), my_basic_string< charT >::nelem(), Absorption::nelem(), MdRecord::Out(), MdRecord::PassWorkspace(), MdRecord::PassWsvNames(), MdRecord::Supergeneric(), MdRecord::UsesTemplates(), Workspace::wsv_data, and global_data::wsv_group_names.
Referenced by main().
write_method_header_documentation()
void write_method_header_documentation (ofstream & ofs, const MdRecord & mdd)
Write method header documentation.
Parameters
[in,out] ofs The stream to write to.
mdd Method lookup data.
Definition at line 93 of file make_auto_md_h.cc.
References MdRecord::AgendaMethod(), align(), MdRecord::Authors(), MdRecord::Description(), MdRecord::GIn(), MdRecord::GInDefault(), MdRecord::GInType(), MdRecord::GOut(), MdRecord::GOutType(), MdRecord::In(), MdRecord::InOnly(), my_basic_string< charT >::insert_substr(), is_agenda_group_id(), MdRecord::Name(), Array< base >::nelem(), Absorption::nelem(), NODEF, MdRecord::Out(), MdRecord::PassWorkspace(), MdRecord::PassWsvNames(), MdRecord::Supergeneric(), and Workspace::wsv_data.
Referenced by main().