ARTS: make_autoarts_h.cc File Reference
make_autoarts_h.cc File Reference
#include <auto_md.h>
#include <global_data.h>
#include <algorithm>
#include <iostream>
#include <map>
#include <string>
#include <vector>
Classes
struct Group
struct Method
struct Method::Gin
struct Method::Gout
struct Method::In
struct Method::Out
struct AgendaData
struct SpeciesData
struct NameMaps
Functions
std::map< std::string, Group > groups ()
std::pair< std::vector< std::string >, std::vector< bool > > fixed_defaults (const std::vector< std::string > &vargroups, const std::vector< std::string > &vardefaults)
std::vector< Method > methods ()
std::map< std::string, AgendaData > agendas ()
std::vector< SpeciesData > all_species ()
void print_include_and_external ()
void print_groups_and_namespaces (const NameMaps &artsname)
void print_variables (const NameMaps &artsname)
std::string spaces (std::size_t n)
void print_gin_methods (const NameMaps &artsname)
void print_full_methods (const NameMaps &artsname)
void print_methods (const NameMaps &artsname)
void print_agenda_methods (const NameMaps &artsname)
void print_agenda_execute (const NameMaps &artsname)
void print_agenda_define (const NameMaps &artsname)
void print_agendas (const NameMaps &artsname)
void print_species_identification (const NameMaps &artsname)
void print_startup ()
int main ()
Function Documentation
agendas()
std::map<std::string, AgendaData> agendas ()
Definition at line 311 of file make_autoarts_h.cc.
References global_data::agenda_data, global_data::AgendaMap, groups(), ARTS::Var::x(), and ARTS::Var::y().
Referenced by ARTS::Method::ArrayOfAgendaExecute(), ARTS::Agenda::Method::ArrayOfAgendaExecute(), and NameMaps::NameMaps().
all_species()
std::vector<SpeciesData> all_species ()
Definition at line 352 of file make_autoarts_h.cc.
References iso(), SpeciesData::isoname, SpeciesData::name, SpeciesData::spec, global_data::species_data, and global_data::SpeciesMap.
Referenced by NameMaps::NameMaps().
fixed_defaults()
std::pair<std::vector<std::string>, std::vector<bool> > fixed_defaults (const std::vector< std::string > & vargroups, const std::vector< std::string > & vardefaults)
Definition at line 93 of file make_autoarts_h.cc.
References NODEF, and ARTS::Var::x().
Referenced by methods().
groups()
std::map<std::string, Group> groups ()
Definition at line 71 of file make_autoarts_h.cc.
References Workspace::wsv_data, global_data::WsvGroupMap, Workspace::WsvMap, ARTS::Var::x(), and ARTS::Var::y().
Referenced by agendas(), and NameMaps::NameMaps().
main()
int main (void)
Definition at line 1220 of file make_autoarts_h.cc.
References define_agenda_data(), define_agenda_map(), define_md_data_raw(), define_md_map(), define_species_data(), define_species_map(), Workspace::define_wsv_data(), define_wsv_group_names(), Workspace::define_wsv_map(), expand_md_data_raw_to_md_data(), print_agendas(), print_groups_and_namespaces(), print_include_and_external(), print_methods(), print_species_identification(), print_startup(), and print_variables().
methods()
std::vector<Method> methods ()
Definition at line 135 of file make_autoarts_h.cc.
References Method::agenda_method, Method::authors, Method::Gin::defs, Method::Gin::desc, Method::Gout::desc, Method::desc, fixed_defaults(), Method::gin, Method::gout, Method::Gin::group, Method::Gout::group, Method::Gin::hasdefs, Method::in, Method::inoutvarpos, global_data::md_data, global_data::MdMap, Method::Gin::name, Method::Gout::name, Method::name, Method::out, Method::pass_workspace, Method::pass_wsv_names, Method::pos, Method::set_method, Method::supergeneric, Method::uses_templates, v, Method::In::varname, Method::Out::varname, Method::In::varpos, Method::Out::varpos, global_data::WsvGroupMap, Workspace::WsvMap, ARTS::Var::x(), and ARTS::Var::y().
Referenced by agenda_append(), AgendaAppend(), NameMaps::NameMaps(), and option_methods().
print_agenda_define()
void print_agenda_define (const NameMaps & artsname)
Definition at line 1076 of file make_autoarts_h.cc.
References NameMaps::agendaname_agenda, NameMaps::varname_group, and ARTS::Var::x().
Referenced by print_agendas().
print_agenda_execute()
void print_agenda_execute (const NameMaps & artsname)
Definition at line 1053 of file make_autoarts_h.cc.
References NameMaps::agendaname_agenda, spaces(), and ARTS::Var::x().
Referenced by print_agendas().
print_agenda_methods()
void print_agenda_methods (const NameMaps & artsname)
Definition at line 903 of file make_autoarts_h.cc.
References a, NameMaps::group, NameMaps::methodname_method, ARTS::Var::Vector::name(), ARTS::Var::Vector::pos(), spaces(), ARTS::Var::x(), and ARTS::Var::y().
Referenced by print_agendas().
print_agendas()
void print_agendas (const NameMaps & artsname)
Definition at line 1106 of file make_autoarts_h.cc.
References print_agenda_define(), print_agenda_execute(), and print_agenda_methods().
Referenced by main().
print_full_methods()
void print_full_methods (const NameMaps & artsname)
Definition at line 722 of file make_autoarts_h.cc.
References a, NameMaps::group, NameMaps::methodname_method, ARTS::Var::Vector::name(), spaces(), NameMaps::varname_group, ARTS::Var::x(), and ARTS::Var::y().
Referenced by print_methods().
print_gin_methods()
void print_gin_methods (const NameMaps & artsname)
Definition at line 558 of file make_autoarts_h.cc.
References a, NameMaps::group, NameMaps::methodname_method, ARTS::Var::Vector::name(), spaces(), ARTS::Var::x(), and ARTS::Var::y().
Referenced by print_methods().
print_groups_and_namespaces()
void print_groups_and_namespaces (const NameMaps & artsname)
Definition at line 406 of file make_autoarts_h.cc.
References NameMaps::group, and ARTS::Var::x().
Referenced by main().
print_include_and_external()
void print_include_and_external ()
Definition at line 383 of file make_autoarts_h.cc.
Referenced by main().
print_methods()
void print_methods (const NameMaps & artsname)
Definition at line 893 of file make_autoarts_h.cc.
References print_full_methods(), and print_gin_methods().
Referenced by main().
print_species_identification()
void print_species_identification (const NameMaps & artsname)
Definition at line 1117 of file make_autoarts_h.cc.
References iso(), and NameMaps::specdata.
Referenced by main().
print_startup()
void print_startup ()
Definition at line 1171 of file make_autoarts_h.cc.
Referenced by main().
print_variables()
void print_variables (const NameMaps & artsname)
Definition at line 431 of file make_autoarts_h.cc.
References NameMaps::group, NameMaps::varname_group, and ARTS::Var::x().
Referenced by main().
spaces()
std::string spaces (std::size_t n)
Definition at line 551 of file make_autoarts_h.cc.
Referenced by print_agenda_execute(), print_agenda_methods(), print_full_methods(), and print_gin_methods().