ARTS: matpackVI.h File Reference
matpackVI.h File Reference
#include "matpackV.h"
Classes
class Iterator6D
The outermost iterator class for rank 6 tensors.
class ConstIterator6D
Const version of Iterator6D.
class ConstTensor6View
A constant view of a Tensor6.
class Tensor6View
The Tensor6View class.
class Tensor6
The Tensor6 class.
Macros
#define CHECK(x)
Implementation of Tensors of Rank 6.
#define OFFSET(x) m##x##r.mstart + x* m##x##r.mstride
Functions
void copy (ConstIterator6D origin, const ConstIterator6D &end, Iterator6D target)
Copy data between begin and end to target.
void copy (Numeric x, Iterator6D target, const Iterator6D &end)
Copy a scalar to all elements.
void transform (Tensor6View y, double(&my_func)(double), ConstTensor6View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Numeric max (const ConstTensor6View &x)
Max function, tensor version.
Numeric min (const ConstTensor6View &x)
Min function, tensor version.
std::ostream & operator<< (std::ostream &os, const ConstTensor6View &v)
Output operator.
Numeric debug_tensor6view_get_elem (Tensor6View &tv, Index v, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Macro Definition Documentation
CHECK
#define CHECK (x)
Value:
  assert(0 <= x); \
  assert(x < m##x##r.mextent)
Implementation of Tensors of Rank 6.
Dimensions are called: vitrine, shelf, book, page, row, column. or short: v, s, b, p, r, c
Author
Stefan Buehler
Date
2001-11-22
Definition at line 33 of file matpackVI.h.
OFFSET
#define OFFSET (x) m##x##r.mstart + x* m##x##r.mstride
Definition at line 36 of file matpackVI.h.
Function Documentation
copy() [1/2]
void copy (ConstIterator6D origin, const ConstIterator6D & end, Iterator6D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can copy data between different kinds of subtensors.
Definition at line 2006 of file matpackVI.cc.
References Tensor5View::begin(), ConstTensor5View::begin(), copy(), ConstTensor5View::end(), and Zeeman::end().
Referenced by copy(), Tensor6View::operator=(), and Tensor6::Tensor6().
copy() [2/2]
void copy (Numeric x, Iterator6D target, const Iterator6D & end)
Copy a scalar to all elements.
Definition at line 2017 of file matpackVI.cc.
References Tensor5View::begin(), copy(), Tensor5View::end(), and Zeeman::end().
debug_tensor6view_get_elem()
Numeric debug_tensor6view_get_elem (Tensor6View & tv, Index v, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Tensor elements from within the debugger.
Parameters
tv TensorView
v Vitrine index
s Shelf index
b Book index
p Page index
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 2326 of file matpackVI.cc.
max()
Numeric max (const ConstTensor6View & x)
Max function, tensor version.
Definition at line 2268 of file matpackVI.cc.
References ConstTensor6View::begin(), ConstTensor6View::end(), and max().
Referenced by max().
min()
Numeric min (const ConstTensor6View & x)
Min function, tensor version.
Definition at line 2287 of file matpackVI.cc.
References ConstTensor6View::begin(), ConstTensor6View::end(), and min().
Referenced by min().
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstTensor6View & v)
Output operator.
This demonstrates how iterators can be used to traverse the tensor. We use the standard output operator for Tensor5 to print each page in turn.
Definition at line 956 of file matpackVI.cc.
References ConstTensor6View::begin(), and ConstTensor6View::end().
transform()
void transform (Tensor6View y, double(&)(double) my_func, ConstTensor6View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Because we have this, we don't need explicit functions like sqrt for tensors! The type of the mathematical function is double (&my_func)(double). Numeric would not work here, since mathematical functions for float do not exist!
transform(y,sin,x) computes y = sin(x)
The two views may be the same one, in which case the conversion happens in place.
Parameters
y Output: The results of the function acting on each element of x.
my_func A function (e.g., sqrt).
x A tensor.
Definition at line 2248 of file matpackVI.cc.
References Tensor6View::begin(), ConstTensor6View::begin(), ConstTensor6View::end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and transform().
Referenced by transform().