ARTS: matpackVII.h File Reference
matpackVII.h File Reference
#include "matpackVI.h"
Classes
class Iterator7D
Implementation of Tensors of Rank 7.
class ConstIterator7D
Const version of Iterator7D.
class ConstTensor7View
A constant view of a Tensor7.
class Tensor7View
The Tensor7View class.
class Tensor7
The Tensor7 class.
Functions
void copy (ConstIterator7D origin, const ConstIterator7D &end, Iterator7D target)
Copy data between begin and end to target.
void copy (Numeric x, Iterator7D target, const Iterator7D &end)
Copy a scalar to all elements.
void transform (Tensor7View y, double(&my_func)(double), ConstTensor7View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Numeric max (const ConstTensor7View &x)
Max function, tensor version.
Numeric min (const ConstTensor7View &x)
Min function, tensor version.
std::ostream & operator<< (std::ostream &os, const ConstTensor7View &v)
Output operator.
Numeric debug_tensor7view_get_elem (Tensor7View &tv, Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Function Documentation
copy() [1/2]
void copy (ConstIterator7D origin, const ConstIterator7D & end, Iterator7D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can copy data between different kinds of subtensors.
Definition at line 5300 of file matpackVII.cc.
References Tensor6View::begin(), ConstTensor6View::begin(), ConstTensor6View::end(), and Zeeman::end().
Referenced by copy(), Tensor7View::operator=(), and Tensor7::Tensor7().
copy() [2/2]
void copy (Numeric x, Iterator7D target, const Iterator7D & end)
Copy a scalar to all elements.
Definition at line 5311 of file matpackVII.cc.
References Tensor6View::begin(), copy(), Tensor6View::end(), Zeeman::end(), and ARTS::Var::x().
debug_tensor7view_get_elem()
Numeric debug_tensor7view_get_elem (Tensor7View & tv, Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Tensor elements from within the debugger.
Parameters
tv TensorView
l Library index
v Vitrine index
s Shelf index
b Book index
p Page index
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 5643 of file matpackVII.cc.
References b, c, Interpolation::l(), and v.
max()
Numeric max (const ConstTensor7View & x)
Max function, tensor version.
Definition at line 5584 of file matpackVII.cc.
References ARTS::Var::x().
min()
Numeric min (const ConstTensor7View & x)
Min function, tensor version.
Definition at line 5603 of file matpackVII.cc.
References ARTS::Var::x().
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstTensor7View & v)
Output operator.
This demonstrates how iterators can be used to traverse the tensor. We use the standard output operator for Tensor6 to print each page in turn.
Definition at line 2572 of file matpackVII.cc.
References v.
transform()
void transform (Tensor7View y, double(&)(double) my_func, ConstTensor7View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Because we have this, we don't need explicit functions like sqrt for tensors! The type of the mathematical function is double (&my_func)(double). Numeric would not work here, since mathematical functions for float do not exist!
transform(y,sin,x) computes y = sin(x)
The two views may be the same one, in which case the conversion happens in place.
Parameters
y Output: The results of the function acting on each element of x.
my_func A function (e.g., sqrt).
x A tensor.
Definition at line 5563 of file matpackVII.cc.
References ARTS_ASSERT, ARTS::Var::x(), and ARTS::Var::y().