ARTS: matpackIII.h File Reference
matpackIII.h File Reference
#include "matpackI.h"
Classes
class Iterator3D
Implementation of Tensors of Rank 3.
class ConstIterator3D
Const version of Iterator3D.
class ConstTensor3View
A constant view of a Tensor3.
class Tensor3View
The Tensor3View class.
class Tensor3
The Tensor3 class.
Functions
void copy (ConstIterator3D origin, const ConstIterator3D &end, Iterator3D target)
Copy data between begin and end to target.
void copy (Numeric x, Iterator3D target, const Iterator3D &end)
Copy a scalar to all elements.
void transform (Tensor3View y, double(&my_func)(double), ConstTensor3View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Numeric max (const ConstTensor3View &x)
Max function, tensor version.
Numeric min (const ConstTensor3View &x)
Min function, tensor version.
std::ostream & operator<< (std::ostream &os, const ConstTensor3View &v)
Output operator.
Numeric debug_tensor3view_get_elem (Tensor3View &tv, Index p, Index r, Index c)
Helper function to access tensor elements.
void mult (Tensor3View A, const ConstVectorView B, const ConstMatrixView C)
mult Tensor3
Function Documentation
copy() [1/2]
void copy (ConstIterator3D origin, const ConstIterator3D & end, Iterator3D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can copy data between different kinds of subtensors.
Definition at line 538 of file matpackIII.cc.
References MatrixView::begin(), ConstMatrixView::begin(), copy(), ConstMatrixView::end(), and Zeeman::end().
Referenced by copy(), Tensor3View::operator=(), and Tensor3::Tensor3().
copy() [2/2]
void copy (Numeric x, Iterator3D target, const Iterator3D & end)
Copy a scalar to all elements.
Definition at line 549 of file matpackIII.cc.
References MatrixView::begin(), copy(), MatrixView::end(), Zeeman::end(), and ARTS::Var::x().
debug_tensor3view_get_elem()
Numeric debug_tensor3view_get_elem (Tensor3View & tv, Index p, Index r, Index c)
Helper function to access tensor elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Tensor elements from within the debugger.
Parameters
tv TensorView
p Page index
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 790 of file matpackIII.cc.
max()
Numeric max (const ConstTensor3View & x)
Max function, tensor version.
Definition at line 735 of file matpackIII.cc.
References max(), and ARTS::Var::x().
Referenced by max().
min()
Numeric min (const ConstTensor3View & x)
Min function, tensor version.
Definition at line 754 of file matpackIII.cc.
References min(), and ARTS::Var::x().
Referenced by min().
mult()
void mult (Tensor3View A, const ConstVectorView B, const ConstMatrixView C)
mult Tensor3
Pointwise multiplication of a vector element and matrix.
mult(Tensor3& A, const ConstVectorView B, const ConstMatrixView C) for multiplying vector pointwise with matrix. Useful, e.g., for frequency gridded absorption vector multiplied by normalized Stokes extinction matrix to get extinction matrix as a function of frequency.
Parameters
A Out: Tensor3 with N pages, M rows and L columns
B In: A Vector of length N.
C In: A Matrix of size M x L.
Author
Richard Larsson
Date
2012-07-17
Definition at line 813 of file matpackIII.cc.
References joker, ConstMatrixView::ncols(), ConstTensor3View::ncols(), ConstVectorView::nelem(), ConstTensor3View::npages(), ConstMatrixView::nrows(), and ConstTensor3View::nrows().
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstTensor3View & v)
Output operator.
This demonstrates how iterators can be used to traverse the tensor. We use the standard output operator for Matrix to print each page in turn.
Definition at line 194 of file matpackIII.cc.
References ConstTensor3View::begin(), and ConstTensor3View::end().
transform()
void transform (Tensor3View y, double(&)(double) my_func, ConstTensor3View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Because we have this, we don't need explicit functions like sqrt for tensors! The type of the mathematical function is double (&my_func)(double). Numeric would not work here, since mathematical functions for float do not exist!
transform(y,sin,x) computes y = sin(x)
The two views may be the same one, in which case the conversion happens in place.
Parameters
y Output: The results of the function acting on each element of x.
my_func A function (e.g., sqrt).
x A tensor.
Definition at line 718 of file matpackIII.cc.
References transform(), ARTS::Var::x(), and ARTS::Var::y().
Referenced by transform().