ARTS: matpackIV.h File Reference
matpackIV.h File Reference
#include "matpackIII.h"
Classes
class Iterator4D
Implementation of Tensors of Rank 4.
class ConstIterator4D
Const version of Iterator4D.
class ConstTensor4View
A constant view of a Tensor4.
class Tensor4View
The Tensor4View class.
class Tensor4
The Tensor4 class.
Functions
void copy (ConstIterator4D origin, const ConstIterator4D &end, Iterator4D target)
Copy data between begin and end to target.
void copy (Numeric x, Iterator4D target, const Iterator4D &end)
Copy a scalar to all elements.
void transform (Tensor4View y, double(&my_func)(double), ConstTensor4View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Numeric max (const ConstTensor4View &x)
Max function, tensor version.
Numeric min (const ConstTensor4View &x)
Min function, tensor version.
std::ostream & operator<< (std::ostream &os, const ConstTensor4View &v)
Output operator.
Numeric debug_tensor4view_get_elem (Tensor4View &tv, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Function Documentation
copy() [1/2]
void copy (ConstIterator4D origin, const ConstIterator4D & end, Iterator4D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can copy data between different kinds of subtensors.
Definition at line 922 of file matpackIV.cc.
References Tensor3View::begin(), ConstTensor3View::begin(), ConstTensor3View::end(), and Zeeman::end().
Referenced by copy(), Tensor4View::operator=(), and Tensor4::Tensor4().
copy() [2/2]
void copy (Numeric x, Iterator4D target, const Iterator4D & end)
Copy a scalar to all elements.
Definition at line 933 of file matpackIV.cc.
References Tensor3View::begin(), copy(), Tensor3View::end(), Zeeman::end(), and x.
debug_tensor4view_get_elem()
Numeric debug_tensor4view_get_elem (Tensor4View & tv, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Tensor elements from within the debugger.
Parameters
tv TensorView
b Book index
p Page index
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 1193 of file matpackIV.cc.
References b, and c.
max()
Numeric max (const ConstTensor4View & x)
Max function, tensor version.
Definition at line 1137 of file matpackIV.cc.
References x.
min()
Numeric min (const ConstTensor4View & x)
Min function, tensor version.
Definition at line 1156 of file matpackIV.cc.
References x.
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstTensor4View & v)
Output operator.
This demonstrates how iterators can be used to traverse the tensor. We use the standard output operator for Tensor to print each book in turn.
Definition at line 424 of file matpackIV.cc.
References v().
transform()
void transform (Tensor4View y, double(&)(double) my_func, ConstTensor4View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Because we have this, we don't need explicit functions like sqrt for tensors! The type of the mathematical function is double (&my_func)(double). Numeric would not work here, since mathematical functions for float do not exist!
transform(y,sin,x) computes y = sin(x)
The two views may be the same one, in which case the conversion happens in place.
Parameters
y Output: The results of the function acting on each element of x.
my_func A function (e.g., sqrt).
x A tensor.
Definition at line 1119 of file matpackIV.cc.
References ARTS_ASSERT, Tensor4View::begin(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and x.