ARTS: matpackV.h File Reference
matpackV.h File Reference
#include "matpackIV.h"
Classes
class Iterator5D
Implementation of Tensors of Rank 5.
class ConstIterator5D
Const version of Iterator5D.
class ConstTensor5View
A constant view of a Tensor5.
class Tensor5View
The Tensor5View class.
class Tensor5
The Tensor5 class.
Functions
void copy (ConstIterator5D origin, const ConstIterator5D &end, Iterator5D target)
Copy data between begin and end to target.
void copy (Numeric x, Iterator5D target, const Iterator5D &end)
Copy a scalar to all elements.
void transform (Tensor5View y, double(&my_func)(double), ConstTensor5View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Numeric max (const ConstTensor5View &x)
Max function, tensor version.
Numeric min (const ConstTensor5View &x)
Min function, tensor version.
std::ostream & operator<< (std::ostream &os, const ConstTensor5View &v)
Output operator.
Numeric debug_tensor5view_get_elem (Tensor5View &tv, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Function Documentation
copy() [1/2]
void copy (ConstIterator5D origin, const ConstIterator5D & end, Iterator5D target)
Copy data between begin and end to target.
Target must be a valid area of memory. Note that the strides in the iterators can be different, so that we can copy data between different kinds of subtensors.
Definition at line 1593 of file matpackV.cc.
References Tensor4View::begin(), ConstTensor4View::begin(), copy(), ConstTensor4View::end(), and Zeeman::end().
Referenced by copy(), Tensor5View::operator=(), and Tensor5::Tensor5().
copy() [2/2]
void copy (Numeric x, Iterator5D target, const Iterator5D & end)
Copy a scalar to all elements.
Definition at line 1604 of file matpackV.cc.
References Tensor4View::begin(), copy(), Tensor4View::end(), and Zeeman::end().
debug_tensor5view_get_elem()
Numeric debug_tensor5view_get_elem (Tensor5View & tv, Index s, Index b, Index p, Index r, Index c)
Helper function to access tensor elements.
Because of function inlining the operator() is not accessible from the debuggger. This function helps to access Tensor elements from within the debugger.
Parameters
tv TensorView
s Shelf index
b Book index
p Page index
r Row index
c Column index
Author
Oliver Lemke
Date
2004-05-10
Definition at line 1886 of file matpackV.cc.
max()
Numeric max (const ConstTensor5View & x)
Max function, tensor version.
Definition at line 1829 of file matpackV.cc.
References ConstTensor5View::begin(), ConstTensor5View::end(), and max().
Referenced by max().
min()
Numeric min (const ConstTensor5View & x)
Min function, tensor version.
Definition at line 1848 of file matpackV.cc.
References ConstTensor5View::begin(), ConstTensor5View::end(), and min().
Referenced by min().
operator<<()
std::ostream& operator<< (std::ostream & os, const ConstTensor5View & v)
Output operator.
This demonstrates how iterators can be used to traverse the tensor. We use the standard output operator for Tensor to print each book in turn.
Definition at line 758 of file matpackV.cc.
References ConstTensor5View::begin(), and ConstTensor5View::end().
transform()
void transform (Tensor5View y, double(&)(double) my_func, ConstTensor5View x)
A generic transform function for tensors, which can be used to implement mathematical functions operating on all elements.
Because we have this, we don't need explicit functions like sqrt for tensors! The type of the mathematical function is double (&my_func)(double). Numeric would not work here, since mathematical functions for float do not exist!
transform(y,sin,x) computes y = sin(x)
The two views may be the same one, in which case the conversion happens in place.
Parameters
y Output: The results of the function acting on each element of x.
my_func A function (e.g., sqrt).
x A tensor.
Definition at line 1810 of file matpackV.cc.
References Tensor5View::begin(), ConstTensor5View::begin(), ConstTensor5View::end(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), and transform().
Referenced by transform().