ARTS: messages.h File Reference
messages.h File Reference
Declarations having to do with the four output streams.
#include <fstream>
#include <iostream>
#include "array.h"
#include "arts.h"
#include "arts_omp.h"
Classes
class Verbosity
class ArtsOut
class ArtsOut0
class ArtsOut1
class ArtsOut2
class ArtsOut3
Macros
#define CREATE_OUT0 ArtsOut0 out0(verbosity)
#define CREATE_OUT1 ArtsOut1 out1(verbosity)
#define CREATE_OUT2 ArtsOut2 out2(verbosity)
#define CREATE_OUT3 ArtsOut3 out3(verbosity)
#define CREATE_OUTS
Functions
template<class T >
ArtsOut & operator<< (ArtsOut &aos, const T &t)
Output operator for ArtsOut.
Detailed Description
Declarations having to do with the four output streams.
ARTS uses four output streams: out0 to out3, where out0 has the highest priority, out3 the lowest. These are global variables. They are intended to be used as follows:
out0: Error messages.
out1: Output of the 'engine'.
out2: Important workspace method output.
out3: Unimportant workspace method output.
The classes associated with the four output stream variables have the same name, but start with a capital letter: Out0, Out1, Out2, and Out3.
Author
Stefan Buehler
Date
2000-07-31
Definition in file messages.h.
Macro Definition Documentation
CREATE_OUT0
#define CREATE_OUT0 ArtsOut0 out0(verbosity)
Definition at line 204 of file messages.h.
CREATE_OUT1
#define CREATE_OUT1 ArtsOut1 out1(verbosity)
Definition at line 205 of file messages.h.
CREATE_OUT2
#define CREATE_OUT2 ArtsOut2 out2(verbosity)
Definition at line 206 of file messages.h.
CREATE_OUT3
#define CREATE_OUT3 ArtsOut3 out3(verbosity)
Definition at line 207 of file messages.h.
CREATE_OUTS
#define CREATE_OUTS
Value:
  ArtsOut0 out0(verbosity); \
  ArtsOut1 out1(verbosity); \
  ArtsOut2 out2(verbosity); \
  ArtsOut3 out3(verbosity)
Definition at line 209 of file messages.h.
Function Documentation
operator<<()
template<class T > ArtsOut& operator<< (ArtsOut & aos, const T & t)
Output operator for ArtsOut.
Definition at line 160 of file messages.h.
References ArtsOut::get_priority(), report_file, ArtsOut::sufficient_priority_agenda(), ArtsOut::sufficient_priority_file(), and ArtsOut::sufficient_priority_screen().