ARTS: microphysics.h File Reference
microphysics.h File Reference
Internal functions for microphysics calculations (size distributions etc.)
#include "array.h"
#include "gridded_fields.h"
#include "interpolation.h"
#include "matpackVII.h"
#include "messages.h"
#include "optproperties.h"
#include "ppath.h"
Functions
void derive_scat_species_a_and_b (Numeric &a, Numeric &b, const Vector &x, const Vector &mass, const Numeric &x_fit_start, const Numeric &x_fit_end)
Detailed Description
Internal functions for microphysics calculations (size distributions etc.)
Author
Jana Mendrok, Daniel Kreyling, Manfred Brath, Patrick Eriksson
Date
2017-07-10
Definition in file microphysics.h.
Function Documentation
derive_scat_species_a_and_b()
void derive_scat_species_a_and_b (Numeric & a, Numeric & b, const Vector & x, const Vector & mass, const Numeric & x_fit_start, const Numeric & x_fit_end)
Derives a and b for relationship mass = a * x^b
The parameters a and b are derived by a fit including all data inside the size range [x_fit_start,x_fit_end].
The vector x must have been checked to have at least 2 elements.
An error is thrown if less than two data points are found inside [x_fit_start,x_fit_end].
Returns
a Derived a parameter.
b Derived b parameter.
Parameters
x Size grid
mass Particle masses
x_fit_start Start point of x-range to use for fitting
x_fit_end Endpoint of x-range to use for fitting
Author
Jana Mendrok, Patrick Eriksson
Date
2017-10-18
Definition at line 77 of file microphysics.cc.
References a, ARTS_ASSERT, b, get_sorted_indexes(), nonstd::isnan(), linreg(), LineShape::mass(), q, and ARTS::Var::x().
Referenced by ScatSpeciesSizeMassInfo().