ARTS: microphysics.cc File Reference
microphysics.cc File Reference
Internal functions for microphysics calculations (size distributions etc.)
#include "microphysics.h"
#include <algorithm>
#include <cmath>
#include <ctime>
#include <limits>
#include <stdexcept>
#include "arts.h"
#include "check_input.h"
#include "cloudbox.h"
#include "lin_alg.h"
#include "logic.h"
#include "math_funcs.h"
#include "mc_antenna.h"
#include "messages.h"
#include "physics_funcs.h"
#include "ppath.h"
#include "psd.h"
#include "rng.h"
#include "sorting.h"
Functions
void derive_scat_species_a_and_b (Numeric &a, Numeric &b, const Vector &x, const Vector &mass, const Numeric &x_fit_start, const Numeric &x_fit_end)
Variables
const Numeric PI
const Numeric DENSITY_OF_ICE
const Numeric DENSITY_OF_WATER
Detailed Description
Internal functions for microphysics calculations (size distributions etc.)
>
Author
Jana Mendrok, Daniel Kreyling, Manfred Brath, Patrick Eriksson
Date
2017-08-01
Author
Jana Mendrok, Patrick Eriksson
Date
2017-11-05
Internal functions associated with size distributions
Definition in file microphysics.cc.
Function Documentation
derive_scat_species_a_and_b()
void derive_scat_species_a_and_b (Numeric & a, Numeric & b, const Vector & x, const Vector & mass, const Numeric & x_fit_start, const Numeric & x_fit_end)
Derives a and b for relationship mass = a * x^b
The parameters a and b are derived by a fit including all data inside the size range [x_fit_start,x_fit_end].
The vector x must have been checked to have at least 2 elements.
An error is thrown if less than two data points are found inside [x_fit_start,x_fit_end].
Returns
a Derived a parameter.
b Derived b parameter.
Parameters
x Size grid
mass Particle masses
x_fit_start Start point of x-range to use for fitting
x_fit_end Endpoint of x-range to use for fitting
Author
Jana Mendrok, Patrick Eriksson
Date
2017-10-18
Definition at line 77 of file microphysics.cc.
References get_sorted_indexes(), linreg(), q, and ARTS::Var::x().
Referenced by ScatSpeciesSizeMassInfo().
Variable Documentation
DENSITY_OF_ICE
const Numeric DENSITY_OF_ICE extern
DENSITY_OF_WATER
const Numeric DENSITY_OF_WATER extern
PI
const Numeric PI extern