ARTS: mystring.h File Reference
mystring.h File Reference
This file contains the definition of String, the ARTS string class.
#include <algorithm>
#include <cassert>
#include <climits>
#include <sstream>
#include <string>
#include "array.h"
#include "matpack.h"
Classes
class my_basic_string< charT >
The implementation for String, the ARTS string class.
Typedefs
typedef my_basic_string< char > String
The String type for ARTS.
typedef Array< String > ArrayOfString
An array of Strings.
typedef Array< Array< String > > ArrayOfArrayOfString
An array of Strings.
Functions
template<class T >
void extract (T &x, String &line, Index n)
Extract something from the beginning of a string.
Detailed Description
This file contains the definition of String, the ARTS string class.
Author
Stefan Buehler
Date
2001-09-14
Definition in file mystring.h.
Typedef Documentation
ArrayOfArrayOfString
typedef Array<Array<String> > ArrayOfArrayOfString
An array of Strings.
Definition at line 286 of file mystring.h.
ArrayOfString
typedef Array<String> ArrayOfString
An array of Strings.
Definition at line 283 of file mystring.h.
String
typedef my_basic_string<char> String
The String type for ARTS.
Implementation see documentation of class my_basic_string.
Definition at line 280 of file mystring.h.
Function Documentation
extract()
template<class T > void extract (T & x, String & line, Index n)
Extract something from the beginning of a string.
This is just a small helper function to safe some typing.
Return values
x What was extracted from the beginning of the line.
line What was extracted is also cut away from line.
Parameters
n The width of the stuff to extract.
Author
Stefan Buehler
Definition at line 297 of file mystring.h.
References ARTS::Var::x().
Referenced by parse_a3_hitran(), parse_f51_hitran(), parse_i1_hitran(), parse_i2_hitran(), parse_i3_hitran(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromLBLRTMStream(), and Absorption::ReadFromMytran2Stream().