ARTS: Absorption::LineMixing Namespace Reference
Absorption::LineMixing Namespace Reference
Namespaces
LinearRovibErrorCorrectedSudden
Generic interface for ECS calculations.
Makarov2020etal
Classes
struct EquivalentLines
Contains recomputed equivalent lines (sorting is unknown)
struct PopulationAndDipole
Contains the population distribution and dipole.
struct SpeciesErrorCorrectedSuddenData
struct ErrorCorrectedSuddenData
Rovibrational line mixing data following the ideas of Collisional Effects On Molecular Spectra by J.
struct MapOfErrorCorrectedSuddenData
Typedefs
using EnergyFunction = std::function< Numeric(const Rational)>
Functions
std::ostream & operator<< (std::ostream &os, const EquivalentLines &eqv)
std::ostream & operator<< (std::ostream &os, const SpeciesErrorCorrectedSuddenData &srbd)
std::istream & operator>> (std::istream &is, SpeciesErrorCorrectedSuddenData &srbd)
std::pair< ArrayOfIndex, PopulationAndDipole > sorted_population_and_dipole (const Numeric T, const AbsorptionLines &band)
PopulationAndDipole presorted_population_and_dipole (const Numeric T, const ArrayOfIndex &presorting, const AbsorptionLines &band)
ComplexMatrix single_species_ecs_relaxation_matrix (const AbsorptionLines &band, const ArrayOfIndex &sorting, const Numeric T, const Numeric P, const SpeciesErrorCorrectedSuddenData &species_ecs_data, const Index species_pos)
ComplexMatrix ecs_relaxation_matrix (const Numeric T, const Numeric P, const Vector &vmrs, const ErrorCorrectedSuddenData &ecs_data, const AbsorptionLines &band, const ArrayOfIndex &sorting, const Numeric frenorm)
ComplexVector ecs_absorption_impl (const Numeric T, const Numeric P, const Numeric this_vmr, const Vector &vmrs, const ErrorCorrectedSuddenData &ecs_data, const Vector &f_grid, const AbsorptionLines &band)
std::pair< ComplexVector, ArrayOfComplexVector > ecs_absorption (const Numeric T, const Numeric P, const Numeric this_vmr, const Vector &vmrs, const ErrorCorrectedSuddenData &ecs_data, const Vector &f_grid, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities)
ComplexVector ecs_absorption_zeeman_impl (const Numeric T, const Numeric H, const Numeric P, const Numeric this_vmr, const Vector &vmrs, const ErrorCorrectedSuddenData &ecs_data, const Vector &f_grid, const Zeeman::Polarization zeeman_polarization, const AbsorptionLines &band)
std::pair< ComplexVector, ArrayOfComplexVector > ecs_absorption_zeeman (const Numeric T, const Numeric H, const Numeric P, const Numeric this_vmr, const Vector &vmrs, const ErrorCorrectedSuddenData &ecs_data, const Vector &f_grid, const Zeeman::Polarization zeeman_polarization, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities)
Index band_eigenvalue_adaptation (AbsorptionLines &band, const Tensor4 &tempdata, const Vector &temperatures, const Numeric P0, const Index ord)
Adapts the band to the temperature data.
Vector RosenkranzY (const Vector &dip, const ConstMatrixView &W, const AbsorptionLines &band)
Vector RosenkranzG (const Vector &dip, const ConstMatrixView &W, const AbsorptionLines &band)
Vector RosenkranzDV (const Vector &dip, const ConstMatrixView &W, const AbsorptionLines &band)
EquivalentLines eigenvalue_adaptation_of_relmat (const ComplexMatrix &W, const Vector &pop, const Vector &dip, const AbsorptionLines &band, const Numeric frenorm, const Numeric T, const Numeric P, const Numeric QT, const Numeric QT0, const Index broadener)
Adapts the relaxation matrix eigenvalues to a form where they represent additions towards the three Rosenkranz parameters and the 3rd order pressure broadening term.
Tensor4 ecs_eigenvalue_approximation (const AbsorptionLines &band, const Vector &temperatures, const ErrorCorrectedSuddenData &ecs_data, const Numeric P)
void ecs_eigenvalue_adaptation (AbsorptionLines &band, const Vector &temperatures, const ErrorCorrectedSuddenData &ecs_data, const Numeric P0, const Index ord)
Tensor5 ecs_eigenvalue_adaptation_test (const AbsorptionLines &band, const Vector &temperatures, const ErrorCorrectedSuddenData &ecs_data, const Vector &pressures)
Typedef Documentation
EnergyFunction
using Absorption::LineMixing::EnergyFunction = typedef std::function<Numeric (const Rational)>
Definition at line 80 of file linemixing.h.
Function Documentation
band_eigenvalue_adaptation()
Index Absorption::LineMixing::band_eigenvalue_adaptation (AbsorptionLines & band, const Tensor4 & tempdata, const Vector & temperatures, const Numeric P0, const Index ord)
Adapts the band to the temperature data.
Returns
EXIT_FAILURE on failure
EXIT_SUCCESS on success
Definition at line 1294 of file linemixing.cc.
References ARTS_USER_ERROR, c, joker, Absorption::Lines::Line(), Absorption::SingleLine::LineShape(), LineShape::ModelParameters::N, N, Absorption::Lines::Normalization(), Absorption::Lines::NumBroadeners(), Absorption::Lines::NumLines(), and Absorption::Lines::Population().
Referenced by ecs_eigenvalue_adaptation(), and lm_hitran_2017::hitran_lm_eigenvalue_adaptation().
ecs_absorption()
std::pair< ComplexVector, ArrayOfComplexVector > Absorption::LineMixing::ecs_absorption (const Numeric T, const Numeric P, const Numeric this_vmr, const Vector & vmrs, const ErrorCorrectedSuddenData & ecs_data, const Vector & f_grid, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities = {})
Computed the Error Corrected Sudden Complex absorption
Parameters
[in] T The temperature
[in] P The pressure
[in] this_vmr The VMR of this species
[in] vmrs The VMRs of all broadeners of the absorption band
[in] mass The mass of all broadeners of the absorption band
[in] f_grid The grid of frequencies
[in] band The absorption band
[in] jacobian_quantities As WSV
Returns
Complex absorption and list of Complex absorption partial derivatives
Definition at line 782 of file linemixing.cc.
References Absorption::Lines::Bath(), Absorption::Lines::BroadeningSpecies(), d, ecs_absorption_impl(), ARTS::Var::ecs_data(), ARTS::Var::f_grid(), Absorption::Lines::Isotopologue(), ARTS::Var::jacobian(), ARTS::Var::jacobian_quantities(), Array< base >::nelem(), Absorption::Lines::Self(), Absorption::Lines::Species(), Jacobian::Temperature, and LineShape::vmrs().
Referenced by propmat_clearskyAddOnTheFlyLineMixing().
ecs_absorption_impl()
ComplexVector Absorption::LineMixing::ecs_absorption_impl (const Numeric T, const Numeric P, const Numeric this_vmr, const Vector & vmrs, const ErrorCorrectedSuddenData & ecs_data, const Vector & f_grid, const AbsorptionLines & band)
Definition at line 727 of file linemixing.cc.
References ARTS_USER_ERROR_IF, Linefunctions::DopplerConstant(), ARTS::Var::ecs_data(), ecs_relaxation_matrix(), ARTS::Var::f_grid(), Absorption::Lines::F_mean(), nonstd::isnan(), Absorption::Lines::MetaData(), number_density(), Absorption::Lines::NumLines(), ComplexVectorView::real(), sorted_population_and_dipole(), Absorption::Lines::SpeciesMass(), Absorption::LineMixing::EquivalentLines::str, Absorption::LineMixing::EquivalentLines::val, LineShape::vmrs(), and w().
Referenced by ecs_absorption().
ecs_absorption_zeeman()
std::pair< ComplexVector, ArrayOfComplexVector > Absorption::LineMixing::ecs_absorption_zeeman (const Numeric T, const Numeric H, const Numeric P, const Numeric this_vmr, const Vector & vmrs, const ErrorCorrectedSuddenData & ecs_data, const Vector & f_grid, const Zeeman::Polarization zeeman_polarization, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities = {})
Computed the Error Corrected Sudden Complex absorption with Zeeman effect perturbations
Note that Zeeman perturbations are only applied after the ECS computations
Parameters
[in] T The temperature
[in] P The pressure
[in] this_vmr The VMR of this species
[in] vmrs The VMRs of all broadeners of the absorption band
[in] mass The mass of all broadeners of the absorption band
[in] f_grid The grid of frequencies
[in] zeeman_polarization The Zeeman polarization to consider
[in] band The absorption band
Returns
Complex absorption of the Zeeman component
Definition at line 1067 of file linemixing.cc.
References Absorption::Lines::Bath(), Absorption::Lines::BroadeningSpecies(), d, ecs_absorption_zeeman_impl(), ARTS::Var::ecs_data(), ARTS::Var::f_grid(), Absorption::Lines::Isotopologue(), ARTS::Var::jacobian(), ARTS::Var::jacobian_quantities(), Array< base >::nelem(), Absorption::Lines::Self(), Jacobian::Temperature, and LineShape::vmrs().
Referenced by propmat_clearskyAddOnTheFlyLineMixingWithZeeman().
ecs_absorption_zeeman_impl()
ComplexVector Absorption::LineMixing::ecs_absorption_zeeman_impl (const Numeric T, const Numeric H, const Numeric P, const Numeric this_vmr, const Vector & vmrs, const ErrorCorrectedSuddenData & ecs_data, const Vector & f_grid, const Zeeman::Polarization zeeman_polarization, const AbsorptionLines & band)
Definition at line 1003 of file linemixing.cc.
References ARTS_USER_ERROR_IF, Linefunctions::DopplerConstant(), ARTS::Var::ecs_data(), ecs_relaxation_matrix(), ARTS::Var::f_grid(), Absorption::Lines::F_mean(), nonstd::isnan(), Absorption::Lines::MetaData(), number_density(), Absorption::Lines::NumLines(), ComplexVectorView::real(), sorted_population_and_dipole(), Absorption::Lines::SpeciesMass(), Absorption::LineMixing::EquivalentLines::str, Absorption::LineMixing::EquivalentLines::val, LineShape::vmrs(), w(), Absorption::Lines::ZeemanCount(), Absorption::Lines::ZeemanSplitting(), and Absorption::Lines::ZeemanStrength().
Referenced by ecs_absorption_zeeman().
ecs_eigenvalue_adaptation()
void Absorption::LineMixing::ecs_eigenvalue_adaptation (AbsorptionLines & band, const Vector & temperatures, const ErrorCorrectedSuddenData & ecs_data, const Numeric P0, const Index ord)
Adapts the band to use Rosenkranz parameters from Eigenvalue decomposition
Fits will be of form:
Y ~ P * polyfit(x, y, LineShape::ModelParameters::N - 1) DV ~ P ** 2 * polyfit(x, dv, LineShape::ModelParameters::N - 1) G ~ P ** 2 * polyfit(x, g, LineShape::ModelParameters::N - 1) DG ~ P ** 3 * polyfit(x, dg, LineShape::ModelParameters::N - 1)
where all the values are computed at P0 but re-normalized by the order above
Note that these parameters will fail at high pressures
Parameters
[in] band The absorption band
[in] temperatures The temperature grid for fitting parameters upon
[in] mass The mass of all broadeners of the absorption band
[in] P0 The pressure at which temperature dependencies are computed at
[in] ord The order of the parameters [1: Y; 2: Y, DF, G; 3: Y, DF, G, DG]
Returns
EXIT_FAILURE when some parameterization fit fails
EXIT_SUCCESS if all algorithms worked (independent of if the absorption will be reasonable)
Definition at line 1583 of file linemixing.cc.
References ARTS_USER_ERROR, ARTS_USER_ERROR_IF, band_eigenvalue_adaptation(), ARTS::Var::ecs_data(), ecs_eigenvalue_approximation(), and is_sorted().
ecs_eigenvalue_adaptation_test()
Tensor5 Absorption::LineMixing::ecs_eigenvalue_adaptation_test (const AbsorptionLines & band, const Vector & temperatures, const ErrorCorrectedSuddenData & ecs_data, const Vector & pressures)
Outputs the adaptation values used for ecs_eigenvalue_adaptation but as a function of pressure. ecs_eigenvalue_adaptation makes strong assumptions about the pressure order of the outputs used, and if this work for a given band can be found out using this data
Parameters
[in] band The absorption band [N lines]
[in] temperatures The temperature grid for fitting parameters upon [K temperatures]
[in] mass The mass of all broadeners of the absorption band [M broadeners]
[in] pressures The pressures for testing [L pressures]
Returns
Tensor with size [4, N, M, K, L]
Definition at line 1607 of file linemixing.cc.
References ARTS::Var::ecs_data(), ecs_eigenvalue_approximation(), joker, Interpolation::l(), M, N, ConstVectorView::nelem(), Absorption::Lines::NumBroadeners(), Absorption::Lines::NumLines(), and ConstVectorView::size().
ecs_eigenvalue_approximation()
Tensor4 Absorption::LineMixing::ecs_eigenvalue_approximation (const AbsorptionLines & band, const Vector & temperatures, const ErrorCorrectedSuddenData & ecs_data, const Numeric P)
Computes the Eigenvalue adaptation values
The output is sorted based on frequency. If pressure shifts moves one line's frequency past another, this introduces errors. This is uncommon but happens more easily at higher pressures.
If this happens, the output of this function is not usable, but no safe-guards are in place to guard against this.
Parameters
[in] band The absorption band [N lines]
[in] temperatures The temperature grid for fitting parameters upon [K temperatures]
[in] mass The mass of all broadeners of the absorption band [M broadeners]
Returns
Eigenvalue line mixing parameters
Definition at line 1538 of file linemixing.cc.
References Absorption::Lines::F_mean(), Absorption::Lines::Isotopologue(), M, N, ConstVectorView::nelem(), Absorption::Lines::NumBroadeners(), Absorption::Lines::NumLines(), single_partition_function(), sorted_population_and_dipole(), and Absorption::Lines::T0().
Referenced by ecs_eigenvalue_adaptation(), and ecs_eigenvalue_adaptation_test().
ecs_relaxation_matrix()
ComplexMatrix Absorption::LineMixing::ecs_relaxation_matrix (const Numeric T, const Numeric P, const Vector & vmrs, const ErrorCorrectedSuddenData & ecs_data, const AbsorptionLines & band, const ArrayOfIndex & sorting, const Numeric frenorm)
Computes the Error Corrected Sudden relaxation matrix
Parameters
[in] T The temperature
[in] P The pressure
[in] vmrs The VMRs of all broadeners of the absorption band
[in] mass The mass of all broadeners of the absorption band
[in] band The absorption band
[in] sorting The sorting of the band
[in] frenorm The renormalization of frequency
Returns
The relaxation matrix
Definition at line 694 of file linemixing.cc.
References M, N, ConstVectorView::nelem(), Absorption::Lines::NumLines(), and LineShape::vmrs().
Referenced by ecs_absorption_impl(), and ecs_absorption_zeeman_impl().
eigenvalue_adaptation_of_relmat()
EquivalentLines Absorption::LineMixing::eigenvalue_adaptation_of_relmat (const ComplexMatrix & W, const Vector & pop, const Vector & dip, const AbsorptionLines & band, const Numeric frenorm, const Numeric T, const Numeric P, const Numeric QT, const Numeric QT0, const Index broadener)
Adapts the relaxation matrix eigenvalues to a form where they represent additions towards the three Rosenkranz parameters and the 3rd order pressure broadening term.
The EquivalentLines are sorted by the real part of the val-component. At a sufficiently small pressure, this is equivalent to sorting by line frequency. At higher pressures, the sorting might be wrong
The output is adapted to fit into standard LBL calculations assuming that the pressure-sorting works. This happens via an adaptation so that
X = val - Complex(F0 + D0(T), G0(T)) Y = str / I(T) - 1
are the two return values, where val and str are the output of the standard constructor of EquivalentLines.
Definition at line 1469 of file linemixing.cc.
References Absorption::Lines::E0(), eig(), Absorption::Lines::F0(), Absorption::Lines::I0(), Absorption::Lines::Line(), Absorption::SingleLine::LineShape(), Linefunctions::lte_linestrength(), Absorption::Lines::NumLines(), ConstVectorView::size(), swap(), and Absorption::Lines::T0().
operator<<() [1/2]
std::ostream& Absorption::LineMixing::operator<< (std::ostream & os, const EquivalentLines & eqv)
Definition at line 84 of file linemixing.cc.
operator<<() [2/2]
std::ostream& Absorption::LineMixing::operator<< (std::ostream & os, const SpeciesErrorCorrectedSuddenData & srbd)
Definition at line 93 of file linemixing.cc.
operator>>()
std::istream& Absorption::LineMixing::operator>> (std::istream & is, SpeciesErrorCorrectedSuddenData & srbd)
Definition at line 103 of file linemixing.cc.
presorted_population_and_dipole()
PopulationAndDipole Absorption::LineMixing::presorted_population_and_dipole (const Numeric T, const ArrayOfIndex & presorting, const AbsorptionLines & band)
Returns pre-sorted population distribtions and dipoles
Parameters
[in] T The temperature
[in] presorting Changes positions from [0 ... N-1] to presorting positions
[in] band The absorption band
Returns
Pre-sorted population distribtions and dipoles
Definition at line 219 of file linemixing.cc.
References Absorption::LineMixing::PopulationAndDipole::sort().
RosenkranzDV()
Vector Absorption::LineMixing::RosenkranzDV (const Vector & dip, const ConstMatrixView & W, const AbsorptionLines & band)
Computes the Rosenkranz second order imaginary perturbation
Parameters
[in] dip Reduced dipoles
[in] W The relaxation matrix
[in] band The absorption band
Returns
Second order imaginary coefficients
Definition at line 1449 of file linemixing.cc.
References N, and ConstVectorView::nelem().
RosenkranzG()
Vector Absorption::LineMixing::RosenkranzG (const Vector & dip, const ConstMatrixView & W, const AbsorptionLines & band)
Computes the Rosenkranz second order real perturbation
Parameters
[in] dip Reduced dipoles
[in] W The relaxation matrix
[in] band The absorption band
Returns
Second order real coefficients
Definition at line 1412 of file linemixing.cc.
References LineShape::G, N, and ConstVectorView::nelem().
RosenkranzY()
Vector Absorption::LineMixing::RosenkranzY (const Vector & dip, const ConstMatrixView & W, const AbsorptionLines & band)
Computes the Rosenkranz first order perturbation
Parameters
[in] dip Reduced dipoles
[in] W The relaxation matrix
[in] band The absorption band
Returns
First order coefficients
Definition at line 1385 of file linemixing.cc.
References N, ConstVectorView::nelem(), and LineShape::Y.
single_species_ecs_relaxation_matrix()
ComplexMatrix Absorption::LineMixing::single_species_ecs_relaxation_matrix (const AbsorptionLines & band, const ArrayOfIndex & sorting, const Numeric T, const Numeric P, const SpeciesErrorCorrectedSuddenData & species_ecs_data, const Index species_pos)
Computes the Error Corrected Sudden relaxation matrix for a single species
The band population type is used to select type of off-diagonal element computations
Parameters
[in] band The absorption band
[in] sorting The sorting of the band
[in] T The temperature
[in] P The pressure
[in] species_mass The mass of the colliding species
[in] species_pos The index position of the colliding species among the band broadeners
Returns
The single species relaxation matrix
Definition at line 647 of file linemixing.cc.
References ARTS_ASSERT, ComplexMatrixView::imag(), N, Absorption::Lines::NumLines(), Absorption::Lines::Population(), Absorption::LineMixing::Makarov2020etal::relaxation_matrix_offdiagonal(), Absorption::LineMixing::LinearRovibErrorCorrectedSudden::relaxation_matrix_offdiagonal(), and Absorption::Lines::ShapeParameters().
sorted_population_and_dipole()
std::pair<ArrayOfIndex, PopulationAndDipole> Absorption::LineMixing::sorted_population_and_dipole (const Numeric T, const AbsorptionLines & band)
Returns sorted population distribtions and dipoles and the original sorting
Parameters
[in] T The temperature
[in] band The absorption band
Returns
{sorting, sorted population distribtions and dipoles}
Definition at line 205 of file linemixing.cc.
References Absorption::LineMixing::PopulationAndDipole::sort().
Referenced by ecs_absorption_impl(), ecs_absorption_zeeman_impl(), and ecs_eigenvalue_approximation().