ARTS: Raw::Calibration Namespace Reference
Raw::Calibration Namespace Reference
Functions
Vector calibration (const Vector &pc, const Vector &pa, const Vector &ph, Numeric tc, Numeric th) noexcept
Computes the linear calibration formula elementwise.
Vector systemtemp (const Vector &pc, const Vector &ph, Numeric tc, Numeric th) noexcept
Computes the linear receiver temperature formula elementwise.
ArrayOfVector caha (const ArrayOfVector &data, const Vector &tcvec, const Vector &thvec, const Index first_c_index)
Calibrate the data by CAHA.
constexpr Numeric calibration (Numeric pc, Numeric pa, Numeric ph, Numeric tc, Numeric th) noexcept
Computes the linear calibration formula.
constexpr Numeric systemtemp (Numeric pc, Numeric ph, Numeric tc, Numeric th) noexcept
Computes the linear receiver temperature formula.
Function Documentation
caha()
ArrayOfVector Raw::Calibration::caha (const ArrayOfVector & data, const Vector & tcvec, const Vector & thvec, const Index first_c_index)
Calibrate the data by CAHA.
CAHA stands for cold-atm-hot-atm, and is the presumed observation scheme for the calibration. The calibration will happen on the atmospheric measurement between any two pairs of cold and hot (cold then hot; hot then cold)
Parameters
[in] data A list or array or vector of measurements
[in] tcvec A Vector of cold load temperatures at corresponding data entry
[in] thvec A Vector of hot load temperatures at corresponding data entry
[in] first_c_index The position of the first C in data [must be positive]
Returns
Calibrated values [use calibration() if calib, else use systemtemp()]
Definition at line 53 of file raw.cc.
References calibration(), data, and Zeeman::start().
Referenced by ybatchColdAtmHotAtmCycle().
calibration() [1/2]
Vector Raw::Calibration::calibration (const Vector & pc, const Vector & pa, const Vector & ph, Numeric tc, Numeric th) noexcept
Computes the linear calibration formula elementwise.
\[ \vec{T}_a = T_c + \frac{(T_h - T_c)(\vec{P}_a - \vec{P}_c)}{\vec{P}_h - \vec{P}_c} \]
Parameters
[in] pc \(\vec{P}_c \), linear power of cold load; cold count
[in] pa \(\vec{P}_a \), linear power of atmospheric measurement; atmospheric count
[in] ph \(\vec{P}_h \), linear power of got load; hot count
[in] tc \(T_c \), cold load temperature
[in] th \(T_h \), hot load temperature
Returns
\(\vec{T}_a \), atmospheric temperature
Definition at line 37 of file raw.cc.
References N.
Referenced by caha(), and yColdAtmHot().
calibration() [2/2]
constexpr Numeric Raw::Calibration::calibration (Numeric pc, Numeric pa, Numeric ph, Numeric tc, Numeric th) constexpr noexcept
Computes the linear calibration formula.
\[ T_a = T_c + \frac{(T_h - T_c)(P_a - P_c)}{P_h - P_c} \]
Parameters
[in] pc \(P_c \), linear power of cold load; cold count
[in] pa \(P_a \), linear power of atmospheric measurement; atmospheric count
[in] ph \(P_h \), linear power of got load; hot count
[in] tc \(T_c \), cold load temperature
[in] th \(T_h \), hot load temperature
Returns
\(T_a \), atmospheric temperature
Definition at line 46 of file raw.h.
systemtemp() [1/2]
Vector Raw::Calibration::systemtemp (const Vector & pc, const Vector & ph, Numeric tc, Numeric th) noexcept
Computes the linear receiver temperature formula elementwise.
\[ \vec{T}_r = \frac{T_h \vec{P}_c - T_c \vec{P}_h}{\vec{P}_h - \vec{P}_c} \]
Parameters
[in] pc \(\vec{P}_c \), linear power of cold load; cold count
[in] ph \(\vec{P}_h \), linear power of got load; hot count
[in] tc \(T_c \), cold load temperature
[in] th \(T_h \), hot load temperature
Returns
\(\vec{T}_r \), receiver temperature
Definition at line 45 of file raw.cc.
References N.
Referenced by yColdAtmHot().
systemtemp() [2/2]
constexpr Numeric Raw::Calibration::systemtemp (Numeric pc, Numeric ph, Numeric tc, Numeric th) constexpr noexcept
Computes the linear receiver temperature formula.
\[ T_r = \frac{T_hP_c - T_cP_h}{P_h - P_c} \]
Parameters
[in] pc \(P_c \), linear power of cold load; cold count
[in] ph \(P_h \), linear power of got load; hot count
[in] tc \(T_c \), cold load temperature
[in] th \(T_h \), hot load temperature
Returns
\(T_r \), receiver temperature
Definition at line 73 of file raw.h.