ARTS: lm_hitran_2017 Namespace Reference
lm_hitran_2017 Namespace Reference
Namespaces
parameters
Classes
struct CommonBlock
struct ConvTPOut
Typedefs
using EqvLinesOut = Absorption::LineMixing::EquivalentLines
Enumerations
enum class calctype {
FullVP , FullRosenkranz , FullW , SDVP ,
SDRosenkranz , SDW , NoneVP , NoneRosenkranz ,
NoneW
}
enum class ModeOfLineMixing {
VP , VP_Y , SDVP , SDVP_Y ,
FullW , VP_W
}
Class that controls ReadFromLineMixingStream output.
Functions
Rational toRationalSum (char a, char b=' ')
void readlines (CommonBlock &cmn, const String &basedir="data_new/")
template<size_t NT>
Numeric atob (const Numeric &aa, const std::array< Numeric, NT > &a, const std::array< Numeric, NT > &b)
void qt_co2 (const Numeric &t, const Index &iso, Numeric &gsi, Numeric &qt)
void calcw (CommonBlock &cmn, const Index &n, const Index &iband, const Numeric &temp)
void calcw (ConvTPOut &out, const HitranRelaxationMatrixData &hitran, const AbsorptionLines &band, const Numeric T)
void eqvlines (CommonBlock &cmn, const Index &iband, const Index &n, const Numeric &sigmoy)
EqvLinesOut eqvlines (const ConstComplexMatrixView W, const ConstVectorView pop, const ConstVectorView dip, const Numeric &fmean)
void convtp (CommonBlock &cmn, const Index &iband, const Index &isotc, const Index &nlinec, const Numeric &xh2o, const Numeric &xco2, const Numeric &temp, const Numeric &ptot, Numeric &sigmoy, Numeric &gamd_gam0_mx, const bool mixfull, const bool mixsdv)
ConvTPOut convtp (const ConstVectorView vmrs, const HitranRelaxationMatrixData &hitran, const AbsorptionLines &band, const Numeric T, const Numeric P, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data)
void qsdv (const Numeric &sg0, const Numeric &gamd, const Numeric &gam0, const Numeric &gam2, const Numeric &shift0, const Numeric &shift2, const Numeric &sg, Numeric &ls_qsdv_r, Numeric &ls_qsdv_i)
Complex qsdv_si (const Numeric F0, const Numeric gamd, const Numeric gam0, const Numeric gam2, const Numeric shift0, const Numeric shift2, const Numeric f)
void compabs (CommonBlock &cmn, const Numeric &temp, const Numeric &ptot, const Numeric &xco2, const Numeric &xh2o, const ConstVectorView invcm_grid, const bool mixsdv, const bool mixfull, VectorView absv, VectorView absy, VectorView absw)
Vector compabs (const Numeric T, const Numeric P, const HitranRelaxationMatrixData &hitran, const ArrayOfAbsorptionLines &bands, const ConstVectorView vmrs, const ConstVectorView f_grid, const SpeciesAuxData &partition_functions)
void detband (CommonBlock &cmn, const Numeric &sgminr, const Numeric &sgmaxr, const Numeric &stotmax, const String &basedir="data_new/")
void readw (CommonBlock &cmn, const String &basedir="data_new/")
Vector compute (const Numeric p, const Numeric t, const Numeric xco2, const Numeric xh2o, const ConstVectorView invcm_grid, const Numeric stotmax, const calctype type)
Vector compute (const HitranRelaxationMatrixData &hitran, const ArrayOfAbsorptionLines &bands, const Numeric P, const Numeric T, const ConstVectorView vmrs, const ConstVectorView f_grid, const SpeciesAuxData &partition_functions)
Compute the absorptionlines.
void read (HitranRelaxationMatrixData &hitran, ArrayOfAbsorptionLines &bands, const String &basedir, const Numeric linemixinglimit, const Numeric fmin, const Numeric fmax, const Numeric stot, const ModeOfLineMixing mode)
Read from HITRAN online line mixing file.
constexpr bool typeVP (ModeOfLineMixing x)
constexpr bool typeLP (ModeOfLineMixing x)
constexpr bool typeFull (ModeOfLineMixing x)
Typedef Documentation
EqvLinesOut
using lm_hitran_2017::EqvLinesOut = typedef Absorption::LineMixing::EquivalentLines
Definition at line 952 of file linemixing_hitran.cc.
Enumeration Type Documentation
calctype
enum lm_hitran_2017::calctype strong
Enumerator
FullVP
FullRosenkranz
FullW
SDVP
SDRosenkranz
SDW
NoneVP
NoneRosenkranz
NoneW
Definition at line 66 of file linemixing_hitran.h.
ModeOfLineMixing
enum lm_hitran_2017::ModeOfLineMixing strong
Class that controls ReadFromLineMixingStream output.
Enumerator
VP
VP_Y
SDVP
SDVP_Y
FullW
VP_W
Definition at line 106 of file linemixing_hitran.h.
Function Documentation
atob()
template<size_t NT> Numeric lm_hitran_2017::atob (const Numeric & aa, const std::array< Numeric, NT > & a, const std::array< Numeric, NT > & b)
Definition at line 408 of file linemixing_hitran.cc.
References a, and b.
Referenced by qt_co2().
calcw() [1/2]
void lm_hitran_2017::calcw (CommonBlock & cmn, const Index & n, const Index & iband, const Numeric & temp)
Definition at line 784 of file linemixing_hitran.cc.
References abs, b0, lm_hitran_2017::CommonBlock::Bfittedp::B0pp, lm_hitran_2017::CommonBlock::Bfittedp::B0pq, lm_hitran_2017::CommonBlock::Bfittedp::B0pr, lm_hitran_2017::CommonBlock::Bfittedq::B0qp, lm_hitran_2017::CommonBlock::Bfittedq::B0qq, lm_hitran_2017::CommonBlock::Bfittedq::B0qr, lm_hitran_2017::CommonBlock::Bfittedr::B0rp, lm_hitran_2017::CommonBlock::Bfittedr::B0rq, lm_hitran_2017::CommonBlock::Bfittedr::B0rr, lm_hitran_2017::CommonBlock::Bands, lm_hitran_2017::CommonBlock::Bfittedp, lm_hitran_2017::CommonBlock::Bfittedq, lm_hitran_2017::CommonBlock::Bfittedr, lm_hitran_2017::CommonBlock::DipoRigid::Dipo0, lm_hitran_2017::CommonBlock::DipoRigid, lm_hitran_2017::CommonBlock::DipoTcm::DipoT, lm_hitran_2017::CommonBlock::DipoTcm, lm_hitran_2017::CommonBlock::GamT, lm_hitran_2017::CommonBlock::GamT::HWSDV2T, lm_hitran_2017::CommonBlock::GamT::HWT, lm_hitran_2017::CommonBlock::Bands::Isot, lm_hitran_2017::CommonBlock::Jfln::Jf, lm_hitran_2017::CommonBlock::Jfln, lm_hitran_2017::CommonBlock::Jiln::Ji, lm_hitran_2017::CommonBlock::Jiln, lm_hitran_2017::CommonBlock::Bands::lf, lm_hitran_2017::CommonBlock::Bands::li, lm_hitran_2017::CommonBlock::LineSg, max, min, lm_hitran_2017::CommonBlock::PopuT::PopuT, lm_hitran_2017::CommonBlock::PopuT, Constant::pow2(), lm_hitran_2017::CommonBlock::SHIFT::shft, lm_hitran_2017::CommonBlock::SHIFT, lm_hitran_2017::CommonBlock::LineSg::Sig, swap(), temp, lm_hitran_2017::CommonBlock::Wmatrix::W, lm_hitran_2017::CommonBlock::Wfittedp::W0pp, lm_hitran_2017::CommonBlock::Wfittedp::W0pq, lm_hitran_2017::CommonBlock::Wfittedp::W0pr, lm_hitran_2017::CommonBlock::Wfittedq::W0qp, lm_hitran_2017::CommonBlock::Wfittedq::W0qq, lm_hitran_2017::CommonBlock::Wfittedq::W0qr, lm_hitran_2017::CommonBlock::Wfittedr::W0rp, lm_hitran_2017::CommonBlock::Wfittedr::W0rq, lm_hitran_2017::CommonBlock::Wfittedr::W0rr, lm_hitran_2017::CommonBlock::Wfittedp, lm_hitran_2017::CommonBlock::Wfittedq, lm_hitran_2017::CommonBlock::Wfittedr, lm_hitran_2017::CommonBlock::Wmatrix, lm_hitran_2017::CommonBlock::YLT, and lm_hitran_2017::CommonBlock::YLT::YT.
Referenced by convtp().
calcw() [2/2]
void lm_hitran_2017::calcw (ConvTPOut & out, const HitranRelaxationMatrixData & hitran, const AbsorptionLines & band, const Numeric T)
Definition at line 967 of file linemixing_hitran.cc.
References abs, b0, HitranRelaxationMatrixData::B0pp, HitranRelaxationMatrixData::B0pq, HitranRelaxationMatrixData::B0pr, HitranRelaxationMatrixData::B0qp, HitranRelaxationMatrixData::B0qq, HitranRelaxationMatrixData::B0qr, HitranRelaxationMatrixData::B0rp, HitranRelaxationMatrixData::B0rq, HitranRelaxationMatrixData::B0rr, d0, lm_hitran_2017::ConvTPOut::dip, lm_hitran_2017::ConvTPOut::f0, lm_hitran_2017::ConvTPOut::hwt, lm_hitran_2017::ConvTPOut::hwt2, ComplexMatrixView::imag(), Absorption::Lines::Isotopologue(), Conversion::kaycm2freq(), Absorption::Lines::LowerQuantumNumber(), max, min, lm_hitran_2017::ConvTPOut::pop, Constant::pow2(), Absorption::reduced_rovibrational_dipole(), lm_hitran_2017::ConvTPOut::shft, swap(), Absorption::Lines::T0(), Rational::toIndex(), transpose(), Absorption::Lines::UpperQuantumNumber(), lm_hitran_2017::ConvTPOut::W, HitranRelaxationMatrixData::W0pp, HitranRelaxationMatrixData::W0pq, HitranRelaxationMatrixData::W0pr, HitranRelaxationMatrixData::W0qp, HitranRelaxationMatrixData::W0qq, HitranRelaxationMatrixData::W0qr, HitranRelaxationMatrixData::W0rp, HitranRelaxationMatrixData::W0rq, HitranRelaxationMatrixData::W0rr, lm_hitran_2017::ConvTPOut::Y, and LineShape::Y.
compabs() [1/2]
void lm_hitran_2017::compabs (CommonBlock & cmn, const Numeric & temp, const Numeric & ptot, const Numeric & xco2, const Numeric & xh2o, const ConstVectorView invcm_grid, const bool mixsdv, const bool mixfull, VectorView absv, VectorView absy, VectorView absw)
Definition at line 1534 of file linemixing_hitran.cc.
References abs, lm_hitran_2017::CommonBlock::Bands, convtp(), lm_hitran_2017::CommonBlock::DipoTcm::DipoT, lm_hitran_2017::CommonBlock::DipoTcm, lm_hitran_2017::CommonBlock::GamT, lm_hitran_2017::CommonBlock::GamT::HWSDV2T, lm_hitran_2017::CommonBlock::GamT::HWT, lm_hitran_2017::CommonBlock::Bands::Isot, lm_hitran_2017::CommonBlock::LineSg, lm_hitran_2017::CommonBlock::Bands::nBand, ConstVectorView::nelem(), lm_hitran_2017::CommonBlock::Bands::nLines, lm_hitran_2017::CommonBlock::PopuT::PopuT, lm_hitran_2017::CommonBlock::PopuT, pow(), Constant::pow2(), Constant::pow3(), qsdv(), lm_hitran_2017::CommonBlock::SHIFT::shft, lm_hitran_2017::CommonBlock::SHIFT, lm_hitran_2017::CommonBlock::LineSg::Sig, sqrt(), temp, w(), lm_hitran_2017::CommonBlock::YLT, lm_hitran_2017::CommonBlock::YLT::YT, lm_hitran_2017::CommonBlock::Zaa::ZA, lm_hitran_2017::CommonBlock::Zaa, lm_hitran_2017::CommonBlock::Zss::ZS, and lm_hitran_2017::CommonBlock::Zss.
Referenced by compute().
compabs() [2/2]
Vector lm_hitran_2017::compabs (const Numeric T, const Numeric P, const HitranRelaxationMatrixData & hitran, const ArrayOfAbsorptionLines & bands, const ConstVectorView vmrs, const ConstVectorView f_grid, const SpeciesAuxData & partition_functions)
Definition at line 1651 of file linemixing_hitran.cc.
References a, ARTS_USER_ERROR, convtp(), Linefunctions::DopplerConstant(), SpeciesAuxData::getParam(), SpeciesAuxData::getParamType(), Array< base >::nelem(), ConstVectorView::nelem(), number_density(), Constant::pow2(), Constant::pow3(), qsdv_si(), stimulated_emission(), LineShape::vmrs(), and w().
compute() [1/2]
Vector lm_hitran_2017::compute (const HitranRelaxationMatrixData & hitran, const ArrayOfAbsorptionLines & bands, const Numeric P, const Numeric T, const ConstVectorView vmrs, const ConstVectorView f_grid, const SpeciesAuxData & partition_functions)
Compute the absorptionlines.
Parameters
[in] hitran Hitran data for the relaxation matrix calculations
[in] bands List of absorption bands
[in] P Pressure in Pascal
[in] T Temperatures in Kelvin
[in] vmrs VMR ratio. Must be 3-long containing {air, h2o, co2} vmrs
[in] f_grid Frequency grid in Hz
[in] partition_functions As WSV
Returns
The absorption, a vector same length as f_grid
Definition at line 1914 of file linemixing_hitran.cc.
References compabs(), ConstVectorView::nelem(), and LineShape::vmrs().
compute() [2/2]
Vector lm_hitran_2017::compute (const Numeric p, const Numeric t, const Numeric xco2, const Numeric xh2o, const ConstVectorView invcm_grid, const Numeric stotmax, const calctype type)
Definition at line 1867 of file linemixing_hitran.cc.
References compabs(), detband(), FullRosenkranz, FullVP, FullW, ConstVectorView::nelem(), NoneRosenkranz, NoneVP, NoneW, readlines(), readw(), SDRosenkranz, SDVP, and SDW.
Referenced by propmat_clearskyAddHitranLineMixingLines(), and test_hitran2017().
convtp() [1/2]
void lm_hitran_2017::convtp (CommonBlock & cmn, const Index & iband, const Index & isotc, const Index & nlinec, const Numeric & xh2o, const Numeric & xco2, const Numeric & temp, const Numeric & ptot, Numeric & sigmoy, Numeric & gamd_gam0_mx, const bool mixfull, const bool mixsdv)
Definition at line 1243 of file linemixing_hitran.cc.
References lm_hitran_2017::CommonBlock::DTGAMAIR::BHWAIR, lm_hitran_2017::CommonBlock::DTGAMH2O::BHWH2O, lm_hitran_2017::CommonBlock::DTGAMCO2::BHWSELF, calcw(), lm_hitran_2017::CommonBlock::DiagnI, lm_hitran_2017::CommonBlock::DiagnR, lm_hitran_2017::CommonBlock::DipoTcm::DipoT, lm_hitran_2017::CommonBlock::DipoTcm, lm_hitran_2017::CommonBlock::DTGAMAIR, lm_hitran_2017::CommonBlock::DTGAMCO2, lm_hitran_2017::CommonBlock::DTGAMH2O, lm_hitran_2017::CommonBlock::Energy::E, lm_hitran_2017::CommonBlock::Energy, eqvlines(), lm_hitran_2017::CommonBlock::GamSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0CO2, lm_hitran_2017::CommonBlock::GamSDVT0H2O, lm_hitran_2017::CommonBlock::GamT, lm_hitran_2017::CommonBlock::GamVT0AIR, lm_hitran_2017::CommonBlock::GamVT0CO2, lm_hitran_2017::CommonBlock::GamVT0H2O, lm_hitran_2017::CommonBlock::GamT::HWSDV2T, lm_hitran_2017::CommonBlock::GamSDVT0AIR::HWSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::HWSDVT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::HWSDVT0SELF, lm_hitran_2017::CommonBlock::GamT::HWT, lm_hitran_2017::CommonBlock::GamVT0AIR::HWVT0AIR, lm_hitran_2017::CommonBlock::GamVT0H2O::HWVT0H2O, lm_hitran_2017::CommonBlock::GamVT0CO2::HWVT0SELF, lm_hitran_2017::CommonBlock::LineSg, max, lm_hitran_2017::CommonBlock::DiagnI::OpI, lm_hitran_2017::CommonBlock::DiagnR::OpR, lm_hitran_2017::CommonBlock::PopTrf, lm_hitran_2017::CommonBlock::PopuT::PopuT, lm_hitran_2017::CommonBlock::PopuT, lm_hitran_2017::CommonBlock::PopTrf::PopuT0, pow(), Constant::pow2(), qt_co2(), lm_hitran_2017::CommonBlock::GamSDVT0AIR::rHWT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::rHWT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::rHWT0SELF, lm_hitran_2017::CommonBlock::SHIFT::shft, lm_hitran_2017::CommonBlock::SHIFT0::shft0, lm_hitran_2017::CommonBlock::SHIFT, lm_hitran_2017::CommonBlock::SHIFT0, lm_hitran_2017::CommonBlock::LineSg::Sig, sqrt(), temp, lm_hitran_2017::CommonBlock::Wmatrix::W, lm_hitran_2017::CommonBlock::Wmatrix, lm_hitran_2017::CommonBlock::YLT, and lm_hitran_2017::CommonBlock::YLT::YT.
Referenced by compabs().
convtp() [2/2]
ConvTPOut lm_hitran_2017::convtp (const ConstVectorView vmrs, const HitranRelaxationMatrixData & hitran, const AbsorptionLines & band, const Numeric T, const Numeric P, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data)
Definition at line 1316 of file linemixing_hitran.cc.
References boltzman_factor(), boltzman_ratio(), calcw(), ComplexMatrixView::diagonal(), lm_hitran_2017::ConvTPOut::dip, Absorption::Lines::E0(), lm_hitran_2017::ConvTPOut::eqv, eqvlines(), Absorption::Lines::F0(), lm_hitran_2017::ConvTPOut::f0, Absorption::Lines::F_mean(), Absorption::Lines::g_upp(), lm_hitran_2017::ConvTPOut::hwt, lm_hitran_2017::ConvTPOut::hwt2, Absorption::Lines::I0(), ComplexMatrixView::imag(), Absorption::Lines::Line(), Absorption::SingleLine::LineShape(), Absorption::Lines::NumLines(), lm_hitran_2017::ConvTPOut::pop, Absorption::Lines::Population(), Constant::pow2(), ComplexVectorView::real(), lm_hitran_2017::ConvTPOut::shft, single_partition_function(), sqrt(), stimulated_emission(), Absorption::Lines::T0(), LineShape::vmrs(), lm_hitran_2017::ConvTPOut::W, and lm_hitran_2017::ConvTPOut::Y.
detband()
void lm_hitran_2017::detband (CommonBlock & cmn, const Numeric & sgminr, const Numeric & sgmaxr, const Numeric & stotmax, const String & basedir = "data_new/")
Definition at line 1731 of file linemixing_hitran.cc.
References ARTS_USER_ERROR_IF, lm_hitran_2017::CommonBlock::Bands::BandFile, lm_hitran_2017::CommonBlock::Bands, lm_hitran_2017::CommonBlock::Bands::Isot, lm_hitran_2017::CommonBlock::Bands::lf, lm_hitran_2017::CommonBlock::Bands::li, lm_hitran_2017::CommonBlock::Bands::nBand, and x.
Referenced by compute(), and read().
eqvlines() [1/2]
void lm_hitran_2017::eqvlines (CommonBlock & cmn, const Index & iband, const Index & n, const Numeric & sigmoy)
Definition at line 1171 of file linemixing_hitran.cc.
References lm_hitran_2017::CommonBlock::DiagnI, lm_hitran_2017::CommonBlock::DiagnR, diagonalize(), lm_hitran_2017::CommonBlock::DipoTcm::DipoT, lm_hitran_2017::CommonBlock::DipoTcm, inv(), lm_hitran_2017::CommonBlock::DiagnI::OpI, lm_hitran_2017::CommonBlock::DiagnR::OpR, lm_hitran_2017::CommonBlock::PopuT::PopuT, lm_hitran_2017::CommonBlock::PopuT, lm_hitran_2017::CommonBlock::Zaa::ZA, lm_hitran_2017::CommonBlock::Zaa, lm_hitran_2017::CommonBlock::Zss::ZS, and lm_hitran_2017::CommonBlock::Zss.
Referenced by convtp().
eqvlines() [2/2]
EqvLinesOut lm_hitran_2017::eqvlines (const ConstComplexMatrixView W, const ConstVectorView pop, const ConstVectorView dip, const Numeric & fmean)
Definition at line 1204 of file linemixing_hitran.cc.
References diagonalize(), ComplexMatrix::inv(), ConstVectorView::nelem(), Absorption::LineMixing::EquivalentLines::str, and Absorption::LineMixing::EquivalentLines::val.
qsdv()
void lm_hitran_2017::qsdv (const Numeric & sg0, const Numeric & gamd, const Numeric & gam0, const Numeric & gam2, const Numeric & shift0, const Numeric & shift2, const Numeric & sg, Numeric & ls_qsdv_r, Numeric & ls_qsdv_i)
Definition at line 1367 of file linemixing_hitran.cc.
References Constant::pow2(), and x.
Referenced by compabs().
qsdv_si()
Complex lm_hitran_2017::qsdv_si (const Numeric F0, const Numeric gamd, const Numeric gam0, const Numeric gam2, const Numeric shift0, const Numeric shift2, const Numeric f)
Definition at line 1454 of file linemixing_hitran.cc.
References Constant::pow2(), and x.
Referenced by compabs().
qt_co2()
void lm_hitran_2017::qt_co2 (const Numeric & t, const Index & iso, Numeric & gsi, Numeric & qt)
Definition at line 468 of file linemixing_hitran.cc.
References atob(), iso(), q, and stdarrayify().
Referenced by convtp().
read()
void lm_hitran_2017::read (HitranRelaxationMatrixData & hitran, ArrayOfAbsorptionLines & bands, const String & basedir, const Numeric linemixinglimit, const Numeric fmin, const Numeric fmax, const Numeric stot, const ModeOfLineMixing mode)
Read from HITRAN online line mixing file.
Parameters
[out] hitran Hitran data for the relaxation matrix calculations
[out] bands List of absorption bands
[in] basedir The base directory of the HITRAN line mixing files
[in] linemixinglimit The pressure limit for using line mixing instead of pure Voigt
[in] fmin Minimum frequency
[in] fmax Maximum frequency
[in] stot Minimum band-strength
[in] mode The type of calculations
Definition at line 1925 of file linemixing_hitran.cc.
References ARTS_ASSERT, lm_hitran_2017::CommonBlock::Bfittedp::B0pp, HitranRelaxationMatrixData::B0pp, lm_hitran_2017::CommonBlock::Bfittedp::B0pq, HitranRelaxationMatrixData::B0pq, lm_hitran_2017::CommonBlock::Bfittedp::B0pr, HitranRelaxationMatrixData::B0pr, lm_hitran_2017::CommonBlock::Bfittedq::B0qp, HitranRelaxationMatrixData::B0qp, lm_hitran_2017::CommonBlock::Bfittedq::B0qq, HitranRelaxationMatrixData::B0qq, lm_hitran_2017::CommonBlock::Bfittedq::B0qr, HitranRelaxationMatrixData::B0qr, lm_hitran_2017::CommonBlock::Bfittedr::B0rp, HitranRelaxationMatrixData::B0rp, lm_hitran_2017::CommonBlock::Bfittedr::B0rq, HitranRelaxationMatrixData::B0rq, lm_hitran_2017::CommonBlock::Bfittedr::B0rr, HitranRelaxationMatrixData::B0rr, lm_hitran_2017::CommonBlock::Bands, lm_hitran_2017::CommonBlock::Bfittedp, lm_hitran_2017::CommonBlock::Bfittedq, lm_hitran_2017::CommonBlock::Bfittedr, lm_hitran_2017::CommonBlock::DTGAMAIR::BHWAIR, lm_hitran_2017::CommonBlock::DTGAMH2O::BHWH2O, lm_hitran_2017::CommonBlock::DTGAMCO2::BHWSELF, LineShape::D0, detband(), lm_hitran_2017::CommonBlock::DTGAMAIR, lm_hitran_2017::CommonBlock::DTGAMCO2, lm_hitran_2017::CommonBlock::DTGAMH2O, lm_hitran_2017::CommonBlock::UnusedBandParams::fl2, fmax, fmin, lm_hitran_2017::CommonBlock::UnusedBandParams::fr, Conversion::freq2kaycm(), FullW, lm_hitran_2017::CommonBlock::UnusedBandParams::fv1, lm_hitran_2017::CommonBlock::UnusedBandParams::fv2, lm_hitran_2017::CommonBlock::UnusedBandParams::fv3, lm_hitran_2017::CommonBlock::GamSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0CO2, lm_hitran_2017::CommonBlock::GamSDVT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0AIR::HWSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::HWSDVT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::HWSDVT0SELF, Conversion::hz_per_msquared2kaycm_per_cmsquared(), lm_hitran_2017::CommonBlock::UnusedBandParams::il2, lm_hitran_2017::CommonBlock::UnusedBandParams::ir, lm_hitran_2017::CommonBlock::Bands::Isot, lm_hitran_2017::CommonBlock::UnusedBandParams::iv1, lm_hitran_2017::CommonBlock::UnusedBandParams::iv2, lm_hitran_2017::CommonBlock::UnusedBandParams::iv3, lm_hitran_2017::CommonBlock::Jfln::Jf, lm_hitran_2017::CommonBlock::Jfln, lm_hitran_2017::CommonBlock::Jiln::Ji, lm_hitran_2017::CommonBlock::Jiln, Conversion::kaycm_per_atm2hz_per_pa(), lm_hitran_2017::CommonBlock::Bands::lf, lm_hitran_2017::CommonBlock::Bands::li, lm_hitran_2017::CommonBlock::Bands::nBand, my_basic_string< charT >::nelem(), lm_hitran_2017::CommonBlock::Bands::nLines, readlines(), readw(), lm_hitran_2017::CommonBlock::GamSDVT0AIR::rHWT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::rHWT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::rHWT0SELF, SDVP, SDVP_Y, stdarrayify(), typeFull(), typeLP(), typeVP(), lm_hitran_2017::CommonBlock::UnusedBandParams, VP, VP_W, VP_Y, lm_hitran_2017::CommonBlock::Wfittedp::W0pp, HitranRelaxationMatrixData::W0pp, lm_hitran_2017::CommonBlock::Wfittedp::W0pq, HitranRelaxationMatrixData::W0pq, lm_hitran_2017::CommonBlock::Wfittedp::W0pr, HitranRelaxationMatrixData::W0pr, lm_hitran_2017::CommonBlock::Wfittedq::W0qp, HitranRelaxationMatrixData::W0qp, lm_hitran_2017::CommonBlock::Wfittedq::W0qq, HitranRelaxationMatrixData::W0qq, lm_hitran_2017::CommonBlock::Wfittedq::W0qr, HitranRelaxationMatrixData::W0qr, lm_hitran_2017::CommonBlock::Wfittedr::W0rp, HitranRelaxationMatrixData::W0rp, lm_hitran_2017::CommonBlock::Wfittedr::W0rq, HitranRelaxationMatrixData::W0rq, lm_hitran_2017::CommonBlock::Wfittedr::W0rr, HitranRelaxationMatrixData::W0rr, lm_hitran_2017::CommonBlock::Wfittedp, lm_hitran_2017::CommonBlock::Wfittedq, lm_hitran_2017::CommonBlock::Wfittedr, and LineShape::ModelParameters::X0.
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), bifstream::getRaw(), binistream::readString(), and test_hitran2017().
readlines()
void lm_hitran_2017::readlines (CommonBlock & cmn, const String & basedir = "data_new/")
Definition at line 282 of file linemixing_hitran.cc.
References ARTS_USER_ERROR_IF, lm_hitran_2017::CommonBlock::Bands::BandFile, lm_hitran_2017::CommonBlock::Bands, lm_hitran_2017::CommonBlock::DTGAMAIR::BHWAIR, lm_hitran_2017::CommonBlock::DTGAMH2O::BHWH2O, lm_hitran_2017::CommonBlock::DTGAMCO2::BHWSELF, lm_hitran_2017::CommonBlock::DipoRigid::Dipo0, lm_hitran_2017::CommonBlock::DipoRigid, lm_hitran_2017::CommonBlock::DipoTcm::DipoT, lm_hitran_2017::CommonBlock::DipoTcm, lm_hitran_2017::CommonBlock::DTGAMAIR, lm_hitran_2017::CommonBlock::DTGAMCO2, lm_hitran_2017::CommonBlock::DTGAMH2O, lm_hitran_2017::CommonBlock::Energy::E, lm_hitran_2017::CommonBlock::UnusedBandParams::eina, lm_hitran_2017::CommonBlock::Energy, lm_hitran_2017::CommonBlock::UnusedBandParams::fl2, lm_hitran_2017::CommonBlock::UnusedBandParams::fr, lm_hitran_2017::CommonBlock::UnusedBandParams::fv1, lm_hitran_2017::CommonBlock::UnusedBandParams::fv2, lm_hitran_2017::CommonBlock::UnusedBandParams::fv3, lm_hitran_2017::CommonBlock::GamSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0CO2, lm_hitran_2017::CommonBlock::GamSDVT0H2O, lm_hitran_2017::CommonBlock::GamVT0AIR, lm_hitran_2017::CommonBlock::GamVT0CO2, lm_hitran_2017::CommonBlock::GamVT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0AIR::HWSDVT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::HWSDVT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::HWSDVT0SELF, lm_hitran_2017::CommonBlock::GamVT0AIR::HWVT0AIR, lm_hitran_2017::CommonBlock::GamVT0H2O::HWVT0H2O, lm_hitran_2017::CommonBlock::GamVT0CO2::HWVT0SELF, lm_hitran_2017::CommonBlock::UnusedBandParams::il2, lm_hitran_2017::CommonBlock::UnusedBandParams::intens, lm_hitran_2017::CommonBlock::UnusedBandParams::ir, lm_hitran_2017::CommonBlock::Bands::Isot, lm_hitran_2017::CommonBlock::UnusedBandParams::iv1, lm_hitran_2017::CommonBlock::UnusedBandParams::iv2, lm_hitran_2017::CommonBlock::UnusedBandParams::iv3, lm_hitran_2017::CommonBlock::Jfln::Jf, lm_hitran_2017::CommonBlock::Jfln, lm_hitran_2017::CommonBlock::Jiln::Ji, lm_hitran_2017::CommonBlock::Jiln, lm_hitran_2017::CommonBlock::LineSg, lm_hitran_2017::CommonBlock::Bands::nBand, lm_hitran_2017::CommonBlock::Bands::nLines, lm_hitran_2017::CommonBlock::PopTrf, lm_hitran_2017::CommonBlock::PopTrf::PopuT0, lm_hitran_2017::CommonBlock::GamSDVT0AIR::rHWT0AIR, lm_hitran_2017::CommonBlock::GamSDVT0H2O::rHWT0H2O, lm_hitran_2017::CommonBlock::GamSDVT0CO2::rHWT0SELF, lm_hitran_2017::CommonBlock::SHIFT0::shft0, lm_hitran_2017::CommonBlock::SHIFT0, lm_hitran_2017::CommonBlock::LineSg::Sig, sqrt(), toRationalSum(), lm_hitran_2017::CommonBlock::UnusedBandParams, and x.
Referenced by compute(), and read().
readw()
void lm_hitran_2017::readw (CommonBlock & cmn, const String & basedir = "data_new/")
Definition at line 1795 of file linemixing_hitran.cc.
References ARTS_USER_ERROR_IF, lm_hitran_2017::CommonBlock::Bfittedp::B0pp, lm_hitran_2017::CommonBlock::Bfittedp::B0pq, lm_hitran_2017::CommonBlock::Bfittedp::B0pr, lm_hitran_2017::CommonBlock::Bfittedq::B0qp, lm_hitran_2017::CommonBlock::Bfittedq::B0qq, lm_hitran_2017::CommonBlock::Bfittedq::B0qr, lm_hitran_2017::CommonBlock::Bfittedr::B0rp, lm_hitran_2017::CommonBlock::Bfittedr::B0rq, lm_hitran_2017::CommonBlock::Bfittedr::B0rr, lm_hitran_2017::CommonBlock::Bfittedp, lm_hitran_2017::CommonBlock::Bfittedq, lm_hitran_2017::CommonBlock::Bfittedr, Interpolation::l(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), lm_hitran_2017::CommonBlock::Wfittedp::W0pp, lm_hitran_2017::CommonBlock::Wfittedp::W0pq, lm_hitran_2017::CommonBlock::Wfittedp::W0pr, lm_hitran_2017::CommonBlock::Wfittedq::W0qp, lm_hitran_2017::CommonBlock::Wfittedq::W0qq, lm_hitran_2017::CommonBlock::Wfittedq::W0qr, lm_hitran_2017::CommonBlock::Wfittedr::W0rp, lm_hitran_2017::CommonBlock::Wfittedr::W0rq, lm_hitran_2017::CommonBlock::Wfittedr::W0rr, lm_hitran_2017::CommonBlock::Wfittedp, lm_hitran_2017::CommonBlock::Wfittedq, and lm_hitran_2017::CommonBlock::Wfittedr.
Referenced by compute(), and read().
toRationalSum()
Rational lm_hitran_2017::toRationalSum (char a, char b = ' ')
Definition at line 270 of file linemixing_hitran.cc.
References a, and b.
Referenced by readlines().
typeFull()
constexpr bool lm_hitran_2017::typeFull (ModeOfLineMixing x) constexpr
Definition at line 125 of file linemixing_hitran.h.
References FullW, VP_W, and x.
Referenced by read().
typeLP()
constexpr bool lm_hitran_2017::typeLP (ModeOfLineMixing x) constexpr
Definition at line 120 of file linemixing_hitran.h.
References FullW, and x.
Referenced by read().
typeVP()
constexpr bool lm_hitran_2017::typeVP (ModeOfLineMixing x) constexpr
Definition at line 115 of file linemixing_hitran.h.
References FullW, VP, VP_W, VP_Y, and x.
Referenced by read().