ARTS: Minimize Namespace Reference
Minimize Namespace Reference
Classes
struct Wave
Functor for minimizing X0 + X1 * SIN(S * T) + X2 * COS(S * T) - Y.
struct T4
Functor for minimizing (X0 + X1 (T0 / T - 1)) * (T0 / T) ** X2 - Y.
struct DPL
Functor for minimizing X0 * (T0 / T) ** X1 + X2 * (T0 / T) ** X3 - Y.
Functions
constexpr bool goodStatus (int status)
template<class Functor >
std::pair< bool, typename Functor::InputType > curve_fit (const Functor &fun)
template<class Functor , typename ... Inputs>
std::pair< bool, typename Functor::InputType > curve_fit (const ConstVectorView &X, const ConstVectorView &Y, Inputs &&... ins)
Function Documentation
curve_fit() [1/2]
template<class Functor , typename ... Inputs> std::pair<bool, typename Functor::InputType> Minimize::curve_fit (const ConstVectorView & X, const ConstVectorView & Y, Inputs &&... ins)
Fit a curve to data values
See curve_fit(Functor(X, Y, std::forward<Inputs>(ins)...)) for more details.
In addition to the Functor definition of that signature, the Functor must also have defined the implied constructor:
struct Functor {
Functor(const ConstVectorView& X, const ConstVectorView& Y, std::forward<Inputs>(ins)...);
};
The Functor itself is initialized inside curve_fit(X, Y, ...) with a call to its constructor with all Inputs simply forwarded as received. This initialization is to a constant so the interface functions must be acceptable from const-marked calls.
Parameters
[in] X The X-Grid
[in] Y The computed/measured/simulated values at X
[in] ins Inputs to forward to the constructor of Functor
Returns
See curve_fit(Functor(X, Y, std::forward<Inputs>(ins)...))
Definition at line 345 of file minimize.h.
References curve_fit(), and LineShape::Y.
curve_fit() [2/2]
template<class Functor > std::pair<bool, typename Functor::InputType> Minimize::curve_fit (const Functor & fun)
Fit a curve to data values
The Functor is required to have this signature:
struct Functor {
typedef Numeric Scalar;
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, 1> InputType;
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, 1> ValueType;
typedef Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic> JacobianType;
typedef Eigen::ColPivHouseholderQR<JacobianType> QRSolver;
int operator()(const InputType& p, ValueType& f) const;
int df(const InputType& p, JacobianType& J) const;
InputType x0() const;
int inputs() const;
int values() const;
};
Note that the functions can also be declared as static and/or constexpr, but the constexpr support and the constant-sized matrices/vectors did not work within the solver at the time of implementing this.
Parameters
[in] fun A Functor fulfilling the above conditions
Returns
{true if successful curve fit else false, list of parameters that minimizes the functor}
Definition at line 311 of file minimize.h.
References goodStatus().
Referenced by curve_fit(), and test_minimize_wave().
goodStatus()
constexpr bool Minimize::goodStatus (int status) constexpr
Returns wether or not the Eigen minimize call worked
Parameters
[in] status Eigen::LevenbergMarquardtSpace::Status value from minimize(x) call
Definition at line 261 of file minimize.h.
Referenced by curve_fit().