ARTS: ARTS::Var Namespace Reference
ARTS::Var Namespace Reference
Classes
class AbsorptionLines
class Agenda
class ArrayOfAbsorptionLines
class ArrayOfAgenda
class ArrayOfArrayOfAbsorptionLines
class ArrayOfArrayOfGriddedField1
class ArrayOfArrayOfGriddedField2
class ArrayOfArrayOfGriddedField3
class ArrayOfArrayOfIndex
class ArrayOfArrayOfMatrix
class ArrayOfArrayOfPropagationMatrix
class ArrayOfArrayOfRadiationVector
class ArrayOfArrayOfScatteringMetaData
class ArrayOfArrayOfSingleScatteringData
class ArrayOfArrayOfSpeciesTag
class ArrayOfArrayOfStokesVector
class ArrayOfArrayOfString
class ArrayOfArrayOfTensor3
class ArrayOfArrayOfTensor6
class ArrayOfArrayOfTime
class ArrayOfArrayOfTransmissionMatrix
class ArrayOfArrayOfVector
class ArrayOfCIARecord
class ArrayOfGriddedField1
class ArrayOfGriddedField2
class ArrayOfGriddedField3
class ArrayOfGriddedField4
class ArrayOfIndex
class ArrayOfJacobianTarget
class ArrayOfMatrix
class ArrayOfPpath
class ArrayOfPropagationMatrix
class ArrayOfQuantumIdentifier
class ArrayOfRadiationVector
class ArrayOfRetrievalQuantity
class ArrayOfScatteringMetaData
class ArrayOfSingleScatteringData
class ArrayOfSparse
class ArrayOfSpeciesTag
class ArrayOfStokesVector
class ArrayOfString
class ArrayOfTelsemAtlas
class ArrayOfTensor3
class ArrayOfTensor4
class ArrayOfTensor5
class ArrayOfTensor6
class ArrayOfTensor7
class ArrayOfTime
class ArrayOfTransmissionMatrix
class ArrayOfVector
class ArrayOfXsecRecord
class CIARecord
class CovarianceMatrix
class EnergyLevelMap
class GasAbsLookup
class GridPos
class GriddedField1
class GriddedField2
class GriddedField3
class GriddedField4
class GriddedField5
class GriddedField6
class HitranRelaxationMatrixData
class Index
class JacobianTarget
class MCAntenna
class MapOfErrorCorrectedSuddenData
class Matrix
class Numeric
class Ppath
class PropagationMatrix
class QuantumIdentifier
class RadiationVector
class Rational
class ScatteringMetaData
class SingleScatteringData
class Sparse
class SpeciesIsotopologueRatios
class StokesVector
class String
class TelsemAtlas
class Tensor3
class Tensor4
class Tensor5
class Tensor6
class Tensor7
class TessemNN
class Time
class Timer
class TransmissionMatrix
class Vector
class Verbosity
Functions
Vector aa_grid (Workspace &ws) noexcept
Index aa_index (Workspace &ws) noexcept
ArrayOfCIARecord abs_cia_data (Workspace &ws) noexcept
ArrayOfString abs_cont_models (Workspace &ws) noexcept
ArrayOfString abs_cont_names (Workspace &ws) noexcept
ArrayOfVector abs_cont_parameters (Workspace &ws) noexcept
Index abs_f_interp_order (Workspace &ws) noexcept
HitranRelaxationMatrixData abs_hitran_relmat_data (Workspace &ws) noexcept
ArrayOfAbsorptionLines abs_lines (Workspace &ws) noexcept
ArrayOfArrayOfAbsorptionLines abs_lines_per_species (Workspace &ws) noexcept
GasAbsLookup abs_lookup (Workspace &ws) noexcept
Index abs_lookup_is_adapted (Workspace &ws) noexcept
ArrayOfArrayOfSpeciesTag abs_nls (Workspace &ws) noexcept
Index abs_nls_interp_order (Workspace &ws) noexcept
Vector abs_nls_pert (Workspace &ws) noexcept
EnergyLevelMap abs_nlte (Workspace &ws) noexcept
Vector abs_p (Workspace &ws) noexcept
Index abs_p_interp_order (Workspace &ws) noexcept
ArrayOfArrayOfSpeciesTag abs_species (Workspace &ws) noexcept
ArrayOfIndex abs_species_active (Workspace &ws) noexcept
Vector abs_t (Workspace &ws) noexcept
Index abs_t_interp_order (Workspace &ws) noexcept
Vector abs_t_pert (Workspace &ws) noexcept
StokesVector abs_vec (Workspace &ws) noexcept
ArrayOfStokesVector abs_vec_spt (Workspace &ws) noexcept
Matrix abs_vmrs (Workspace &ws) noexcept
Agenda abs_xsec_agenda (Workspace &ws) noexcept
Index abs_xsec_agenda_checked (Workspace &ws) noexcept
ArrayOfMatrix abs_xsec_per_species (Workspace &ws) noexcept
Index agenda_array_index (Workspace &ws) noexcept
Index antenna_dim (Workspace &ws) noexcept
Matrix antenna_dlos (Workspace &ws) noexcept
GriddedField4 antenna_response (Workspace &ws) noexcept
GriddedField4 atm_fields_compact (Workspace &ws) noexcept
Index atmfields_checked (Workspace &ws) noexcept
Index atmgeom_checked (Workspace &ws) noexcept
Index atmosphere_dim (Workspace &ws) noexcept
Matrix avk (Workspace &ws) noexcept
ArrayOfGriddedField1 backend_channel_response (Workspace &ws) noexcept
ArrayOfArrayOfGriddedField1 backend_channel_response_multi (Workspace &ws) noexcept
ArrayOfQuantumIdentifier band_identifiers (Workspace &ws) noexcept
ArrayOfGriddedField4 batch_atm_fields_compact (Workspace &ws) noexcept
ArrayOfArrayOfIndex batch_cloudbox_limits (Workspace &ws) noexcept
ArrayOfTensor4 batch_pnd_fields (Workspace &ws) noexcept
ArrayOfArrayOfIndex channel2fgrid_indexes (Workspace &ws) noexcept
ArrayOfVector channel2fgrid_weights (Workspace &ws) noexcept
Index cloudbox_checked (Workspace &ws) noexcept
Tensor7 cloudbox_field (Workspace &ws) noexcept
Tensor6 cloudbox_field_mono (Workspace &ws) noexcept
Tensor6 cloudbox_field_mono_old (Workspace &ws) noexcept
ArrayOfIndex cloudbox_limits (Workspace &ws) noexcept
Index cloudbox_on (Workspace &ws) noexcept
ArrayOfArrayOfGriddedField1 collision_coefficients (Workspace &ws) noexcept
ArrayOfQuantumIdentifier collision_line_identifiers (Workspace &ws) noexcept
GriddedField3 complex_refr_index (Workspace &ws) noexcept
Sparse covmat_block (Workspace &ws) noexcept
Sparse covmat_inv_block (Workspace &ws) noexcept
CovarianceMatrix covmat_se (Workspace &ws) noexcept
Matrix covmat_so (Workspace &ws) noexcept
Matrix covmat_ss (Workspace &ws) noexcept
CovarianceMatrix covmat_sx (Workspace &ws) noexcept
ArrayOfMatrix dabs_coef_dx (Workspace &ws) noexcept
ArrayOfArrayOfMatrix dabs_xsec_per_species_dx (Workspace &ws) noexcept
ArrayOfTensor3 diy_dx (Workspace &ws) noexcept
ArrayOfStokesVector dnlte_source_dx (Workspace &ws) noexcept
Agenda dobatch_calc_agenda (Workspace &ws) noexcept
ArrayOfTensor7 dobatch_cloudbox_field (Workspace &ws) noexcept
ArrayOfTensor4 dobatch_irradiance_field (Workspace &ws) noexcept
ArrayOfTensor5 dobatch_radiance_field (Workspace &ws) noexcept
ArrayOfTensor5 dobatch_spectral_irradiance_field (Workspace &ws) noexcept
Index doit_conv_flag (Workspace &ws) noexcept
Agenda doit_conv_test_agenda (Workspace &ws) noexcept
Index doit_is_initialized (Workspace &ws) noexcept
Index doit_iteration_counter (Workspace &ws) noexcept
Agenda doit_mono_agenda (Workspace &ws) noexcept
Agenda doit_rte_agenda (Workspace &ws) noexcept
Tensor6 doit_scat_field (Workspace &ws) noexcept
Agenda doit_scat_field_agenda (Workspace &ws) noexcept
Vector doit_za_grid_opt (Workspace &ws) noexcept
Index doit_za_grid_size (Workspace &ws) noexcept
Index doit_za_interp (Workspace &ws) noexcept
Tensor3 dpnd_data_dx (Workspace &ws) noexcept
ArrayOfString dpnd_data_dx_names (Workspace &ws) noexcept
ArrayOfTensor4 dpnd_field_dx (Workspace &ws) noexcept
ArrayOfPropagationMatrix dpropmat_clearsky_dx (Workspace &ws) noexcept
Tensor3 dpsd_data_dx (Workspace &ws) noexcept
ArrayOfArrayOfMatrix dsrc_xsec_per_species_dx (Workspace &ws) noexcept
ArrayOfMatrix dsurface_emission_dx (Workspace &ws) noexcept
ArrayOfString dsurface_names (Workspace &ws) noexcept
ArrayOfTensor4 dsurface_rmatrix_dx (Workspace &ws) noexcept
Matrix dxdy (Workspace &ws) noexcept
MapOfErrorCorrectedSuddenData ecs_data (Workspace &ws) noexcept
PropagationMatrix ext_mat (Workspace &ws) noexcept
ArrayOfPropagationMatrix ext_mat_spt (Workspace &ws) noexcept
Vector f_backend (Workspace &ws) noexcept
ArrayOfVector f_backend_multi (Workspace &ws) noexcept
Vector f_grid (Workspace &ws) noexcept
Index f_index (Workspace &ws) noexcept
Index file_index (Workspace &ws) noexcept
Agenda forloop_agenda (Workspace &ws) noexcept
Index forloop_index (Workspace &ws) noexcept
Vector fos_iyin_za_angles (Workspace &ws) noexcept
Matrix fos_scatint_angles (Workspace &ws) noexcept
Numeric g0 (Workspace &ws) noexcept
Agenda g0_agenda (Workspace &ws) noexcept
Vector geo_pos (Workspace &ws) noexcept
Agenda geo_pos_agenda (Workspace &ws) noexcept
Tensor3 heating_rates (Workspace &ws) noexcept
ArrayOfXsecRecord hitran_xsec_data (Workspace &ws) noexcept
ArrayOfIndex instrument_pol (Workspace &ws) noexcept
ArrayOfArrayOfIndex instrument_pol_array (Workspace &ws) noexcept
Agenda inversion_iterate_agenda (Workspace &ws) noexcept
Index inversion_iteration_counter (Workspace &ws) noexcept
Tensor4 irradiance_field (Workspace &ws) noexcept
SpeciesIsotopologueRatios isotopologue_ratios (Workspace &ws) noexcept
Matrix iy (Workspace &ws) noexcept
Index iy_agenda_call1 (Workspace &ws) noexcept
ArrayOfMatrix iy_aux (Workspace &ws) noexcept
ArrayOfString iy_aux_vars (Workspace &ws) noexcept
Agenda iy_cloudbox_agenda (Workspace &ws) noexcept
Index iy_id (Workspace &ws) noexcept
Agenda iy_independent_beam_approx_agenda (Workspace &ws) noexcept
Agenda iy_loop_freqs_agenda (Workspace &ws) noexcept
Agenda iy_main_agenda (Workspace &ws) noexcept
Agenda iy_radar_agenda (Workspace &ws) noexcept
Agenda iy_space_agenda (Workspace &ws) noexcept
Agenda iy_surface_agenda (Workspace &ws) noexcept
ArrayOfAgenda iy_surface_agenda_array (Workspace &ws) noexcept
Tensor3 iy_transmittance (Workspace &ws) noexcept
Agenda iy_transmitter_agenda (Workspace &ws) noexcept
String iy_unit (Workspace &ws) noexcept
String iy_unit_radar (Workspace &ws) noexcept
Vector iyb (Workspace &ws) noexcept
Matrix jacobian (Workspace &ws) noexcept
Agenda jacobian_agenda (Workspace &ws) noexcept
Index jacobian_do (Workspace &ws) noexcept
ArrayOfRetrievalQuantity jacobian_quantities (Workspace &ws) noexcept
ArrayOfJacobianTarget jacobian_targets (Workspace &ws) noexcept
Numeric lat (Workspace &ws) noexcept
Vector lat_grid (Workspace &ws) noexcept
Vector lat_true (Workspace &ws) noexcept
Index lbl_checked (Workspace &ws) noexcept
ArrayOfVector level0_data (Workspace &ws) noexcept
ArrayOfTime level0_time (Workspace &ws) noexcept
Matrix line_irradiance (Workspace &ws) noexcept
Tensor3 line_transmission (Workspace &ws) noexcept
Vector lm_ga_history (Workspace &ws) noexcept
Numeric lo (Workspace &ws) noexcept
Vector lo_multi (Workspace &ws) noexcept
Numeric lon (Workspace &ws) noexcept
Vector lon_grid (Workspace &ws) noexcept
Vector lon_true (Workspace &ws) noexcept
Tensor3 mag_u_field (Workspace &ws) noexcept
GriddedField3 mag_u_field_raw (Workspace &ws) noexcept
Tensor3 mag_v_field (Workspace &ws) noexcept
GriddedField3 mag_v_field_raw (Workspace &ws) noexcept
Tensor3 mag_w_field (Workspace &ws) noexcept
GriddedField3 mag_w_field_raw (Workspace &ws) noexcept
Agenda main_agenda (Workspace &ws) noexcept
Matrix mblock_dlos_grid (Workspace &ws) noexcept
Index mblock_index (Workspace &ws) noexcept
MCAntenna mc_antenna (Workspace &ws) noexcept
Vector mc_error (Workspace &ws) noexcept
Index mc_iteration_count (Workspace &ws) noexcept
Index mc_max_iter (Workspace &ws) noexcept
Index mc_max_scatorder (Workspace &ws) noexcept
Index mc_max_time (Workspace &ws) noexcept
Index mc_min_iter (Workspace &ws) noexcept
Tensor3 mc_points (Workspace &ws) noexcept
ArrayOfIndex mc_scat_order (Workspace &ws) noexcept
Index mc_seed (Workspace &ws) noexcept
ArrayOfIndex mc_source_domain (Workspace &ws) noexcept
Numeric mc_std_err (Workspace &ws) noexcept
Numeric mc_taustep_limit (Workspace &ws) noexcept
Vector mc_y_tx (Workspace &ws) noexcept
Matrix met_amsu_data (Workspace &ws) noexcept
Vector met_mm_antenna (Workspace &ws) noexcept
Matrix met_mm_backend (Workspace &ws) noexcept
ArrayOfString met_mm_polarisation (Workspace &ws) noexcept
Agenda met_profile_calc_agenda (Workspace &ws) noexcept
Numeric molarmass_dry_air (Workspace &ws) noexcept
Index nbooks (Workspace &ws) noexcept
Index ncols (Workspace &ws) noexcept
Index nelem (Workspace &ws) noexcept
Index nlibraries (Workspace &ws) noexcept
Index nlte_do (Workspace &ws) noexcept
EnergyLevelMap nlte_field (Workspace &ws) noexcept
ArrayOfGriddedField3 nlte_field_raw (Workspace &ws) noexcept
ArrayOfQuantumIdentifier nlte_level_identifiers (Workspace &ws) noexcept
StokesVector nlte_source (Workspace &ws) noexcept
Vector nlte_vibrational_energies (Workspace &ws) noexcept
Index npages (Workspace &ws) noexcept
Index nrows (Workspace &ws) noexcept
Index nshelves (Workspace &ws) noexcept
Index nvitrines (Workspace &ws) noexcept
Vector oem_diagnostics (Workspace &ws) noexcept
ArrayOfString oem_errors (Workspace &ws) noexcept
String output_file_format (Workspace &ws) noexcept
Vector p_grid (Workspace &ws) noexcept
Vector p_grid_orig (Workspace &ws) noexcept
Numeric p_hse (Workspace &ws) noexcept
Tensor4 particle_bulkprop_field (Workspace &ws) noexcept
ArrayOfString particle_bulkprop_names (Workspace &ws) noexcept
Matrix particle_masses (Workspace &ws) noexcept
Tensor4 pha_mat (Workspace &ws) noexcept
Tensor7 pha_mat_doit (Workspace &ws) noexcept
Tensor5 pha_mat_spt (Workspace &ws) noexcept
ArrayOfTensor7 pha_mat_sptDOITOpt (Workspace &ws) noexcept
Agenda pha_mat_spt_agenda (Workspace &ws) noexcept
Numeric planet_rotation_period (Workspace &ws) noexcept
ArrayOfAgenda pnd_agenda_array (Workspace &ws) noexcept
ArrayOfArrayOfString pnd_agenda_array_input_names (Workspace &ws) noexcept
Matrix pnd_agenda_input (Workspace &ws) noexcept
ArrayOfString pnd_agenda_input_names (Workspace &ws) noexcept
Vector pnd_agenda_input_t (Workspace &ws) noexcept
Matrix pnd_data (Workspace &ws) noexcept
Tensor4 pnd_field (Workspace &ws) noexcept
ArrayOfGriddedField3 pnd_field_raw (Workspace &ws) noexcept
Vector pnd_size_grid (Workspace &ws) noexcept
Ppath ppath (Workspace &ws) noexcept
Agenda ppath_agenda (Workspace &ws) noexcept
ArrayOfPpath ppath_field (Workspace &ws) noexcept
Index ppath_inside_cloudbox_do (Workspace &ws) noexcept
Numeric ppath_lmax (Workspace &ws) noexcept
Numeric ppath_lraytrace (Workspace &ws) noexcept
Ppath ppath_step (Workspace &ws) noexcept
Agenda ppath_step_agenda (Workspace &ws) noexcept
Matrix ppvar_f (Workspace &ws) noexcept
Tensor3 ppvar_iy (Workspace &ws) noexcept
Matrix ppvar_mag (Workspace &ws) noexcept
EnergyLevelMap ppvar_nlte (Workspace &ws) noexcept
Matrix ppvar_optical_depth (Workspace &ws) noexcept
Vector ppvar_p (Workspace &ws) noexcept
Matrix ppvar_pnd (Workspace &ws) noexcept
Vector ppvar_t (Workspace &ws) noexcept
Tensor4 ppvar_trans_cumulat (Workspace &ws) noexcept
Tensor4 ppvar_trans_partial (Workspace &ws) noexcept
Matrix ppvar_vmr (Workspace &ws) noexcept
Matrix ppvar_wind (Workspace &ws) noexcept
PropagationMatrix propmat_clearsky (Workspace &ws) noexcept
Agenda propmat_clearsky_agenda (Workspace &ws) noexcept
Index propmat_clearsky_agenda_checked (Workspace &ws) noexcept
Tensor7 propmat_clearsky_field (Workspace &ws) noexcept
Matrix psd_data (Workspace &ws) noexcept
Vector psd_size_grid (Workspace &ws) noexcept
Tensor5 radiance_field (Workspace &ws) noexcept
Vector range_bins (Workspace &ws) noexcept
Vector refellipsoid (Workspace &ws) noexcept
Numeric refr_index_air (Workspace &ws) noexcept
Agenda refr_index_air_agenda (Workspace &ws) noexcept
Numeric refr_index_air_group (Workspace &ws) noexcept
ArrayOfArrayOfMatrix relmat_per_band (Workspace &ws) noexcept
ArrayOfIndex relmat_type_per_band (Workspace &ws) noexcept
Index retrieval_checked (Workspace &ws) noexcept
Vector retrieval_eo (Workspace &ws) noexcept
Vector retrieval_ss (Workspace &ws) noexcept
String rt_integration_option (Workspace &ws) noexcept
Numeric rte_alonglos_v (Workspace &ws) noexcept
Vector rte_los (Workspace &ws) noexcept
Vector rte_pos (Workspace &ws) noexcept
Vector rte_pos2 (Workspace &ws) noexcept
Vector rtp_los (Workspace &ws) noexcept
Vector rtp_mag (Workspace &ws) noexcept
EnergyLevelMap rtp_nlte (Workspace &ws) noexcept
Vector rtp_pos (Workspace &ws) noexcept
Numeric rtp_pressure (Workspace &ws) noexcept
Numeric rtp_temperature (Workspace &ws) noexcept
Vector rtp_vmr (Workspace &ws) noexcept
ArrayOfArrayOfSingleScatteringData scat_data (Workspace &ws) noexcept
Index scat_data_checked (Workspace &ws) noexcept
ArrayOfArrayOfSingleScatteringData scat_data_mono (Workspace &ws) noexcept
ArrayOfArrayOfSingleScatteringData scat_data_raw (Workspace &ws) noexcept
SingleScatteringData scat_data_single (Workspace &ws) noexcept
Index scat_lat_index (Workspace &ws) noexcept
Index scat_lon_index (Workspace &ws) noexcept
ArrayOfArrayOfScatteringMetaData scat_meta (Workspace &ws) noexcept
ScatteringMetaData scat_meta_single (Workspace &ws) noexcept
Index scat_p_index (Workspace &ws) noexcept
ArrayOfString scat_species (Workspace &ws) noexcept
Numeric scat_species_a (Workspace &ws) noexcept
Numeric scat_species_b (Workspace &ws) noexcept
Vector scat_species_x (Workspace &ws) noexcept
Index sensor_checked (Workspace &ws) noexcept
Matrix sensor_description_amsu (Workspace &ws) noexcept
Matrix sensor_los (Workspace &ws) noexcept
Matrix sensor_los_ecef (Workspace &ws) noexcept
Matrix sensor_los_geodetic (Workspace &ws) noexcept
Index sensor_norm (Workspace &ws) noexcept
Matrix sensor_pol (Workspace &ws) noexcept
Matrix sensor_pos (Workspace &ws) noexcept
Matrix sensor_pos_ecef (Workspace &ws) noexcept
Matrix sensor_pos_geodetic (Workspace &ws) noexcept
Sparse sensor_response (Workspace &ws) noexcept
Vector sensor_response_aa (Workspace &ws) noexcept
Agenda sensor_response_agenda (Workspace &ws) noexcept
Matrix sensor_response_dlos (Workspace &ws) noexcept
Matrix sensor_response_dlos_grid (Workspace &ws) noexcept
Vector sensor_response_f (Workspace &ws) noexcept
Vector sensor_response_f_grid (Workspace &ws) noexcept
ArrayOfIndex sensor_response_pol (Workspace &ws) noexcept
ArrayOfIndex sensor_response_pol_grid (Workspace &ws) noexcept
ArrayOfTime sensor_time (Workspace &ws) noexcept
String sideband_mode (Workspace &ws) noexcept
ArrayOfString sideband_mode_multi (Workspace &ws) noexcept
GriddedField1 sideband_response (Workspace &ws) noexcept
ArrayOfGriddedField1 sideband_response_multi (Workspace &ws) noexcept
Tensor3 specific_heat_capacity (Workspace &ws) noexcept
Tensor5 spectral_irradiance_field (Workspace &ws) noexcept
Tensor7 spectral_radiance_field (Workspace &ws) noexcept
Vector specular_los (Workspace &ws) noexcept
Agenda spt_calc_agenda (Workspace &ws) noexcept
ArrayOfMatrix src_xsec_per_species (Workspace &ws) noexcept
Index stokes_dim (Workspace &ws) noexcept
Vector stokes_rotation (Workspace &ws) noexcept
GriddedField3 surface_complex_refr_index (Workspace &ws) noexcept
Matrix surface_emission (Workspace &ws) noexcept
Matrix surface_los (Workspace &ws) noexcept
Vector surface_normal (Workspace &ws) noexcept
Tensor3 surface_props_data (Workspace &ws) noexcept
ArrayOfString surface_props_names (Workspace &ws) noexcept
Tensor3 surface_reflectivity (Workspace &ws) noexcept
Tensor4 surface_rmatrix (Workspace &ws) noexcept
Agenda surface_rtprop_agenda (Workspace &ws) noexcept
ArrayOfAgenda surface_rtprop_agenda_array (Workspace &ws) noexcept
Agenda surface_rtprop_sub_agenda (Workspace &ws) noexcept
Matrix surface_rv_rh (Workspace &ws) noexcept
Vector surface_scalar_reflectivity (Workspace &ws) noexcept
Numeric surface_skin_t (Workspace &ws) noexcept
Index surface_type (Workspace &ws) noexcept
Numeric surface_type_aux (Workspace &ws) noexcept
GriddedField2 surface_type_mask (Workspace &ws) noexcept
ArrayOfIndex surface_types (Workspace &ws) noexcept
Vector surface_types_aux (Workspace &ws) noexcept
Vector surface_types_weights (Workspace &ws) noexcept
Tensor3 t_field (Workspace &ws) noexcept
GriddedField3 t_field_raw (Workspace &ws) noexcept
Matrix t_surface (Workspace &ws) noexcept
ArrayOfTelsemAtlas telsem_atlases (Workspace &ws) noexcept
TessemNN tessem_neth (Workspace &ws) noexcept
TessemNN tessem_netv (Workspace &ws) noexcept
Agenda test_agenda (Workspace &ws) noexcept
ArrayOfAgenda test_agenda_array (Workspace &ws) noexcept
Time time (Workspace &ws) noexcept
ArrayOfTime time_grid (Workspace &ws) noexcept
ArrayOfTime time_stamps (Workspace &ws) noexcept
Timer timer (Workspace &ws) noexcept
Matrix transmitter_pos (Workspace &ws) noexcept
Verbosity verbosity (Workspace &ws) noexcept
Tensor4 vmr_field (Workspace &ws) noexcept
ArrayOfGriddedField3 vmr_field_raw (Workspace &ws) noexcept
Agenda water_p_eq_agenda (Workspace &ws) noexcept
Tensor3 water_p_eq_field (Workspace &ws) noexcept
Index wigner_initialized (Workspace &ws) noexcept
Tensor3 wind_u_field (Workspace &ws) noexcept
GriddedField3 wind_u_field_raw (Workspace &ws) noexcept
Tensor3 wind_v_field (Workspace &ws) noexcept
GriddedField3 wind_v_field_raw (Workspace &ws) noexcept
Tensor3 wind_w_field (Workspace &ws) noexcept
GriddedField3 wind_w_field_raw (Workspace &ws) noexcept
ArrayOfIndex wmrf_channels (Workspace &ws) noexcept
Sparse wmrf_weights (Workspace &ws) noexcept
Vector x (Workspace &ws) noexcept
Vector xa (Workspace &ws) noexcept
Index xml_output_type (Workspace &ws) noexcept
Vector y (Workspace &ws) noexcept
ArrayOfVector y_aux (Workspace &ws) noexcept
Vector y_baseline (Workspace &ws) noexcept
Vector y_f (Workspace &ws) noexcept
Matrix y_geo (Workspace &ws) noexcept
Matrix y_los (Workspace &ws) noexcept
ArrayOfIndex y_pol (Workspace &ws) noexcept
Matrix y_pos (Workspace &ws) noexcept
Vector yb (Workspace &ws) noexcept
ArrayOfVector ybatch (Workspace &ws) noexcept
ArrayOfArrayOfVector ybatch_aux (Workspace &ws) noexcept
Agenda ybatch_calc_agenda (Workspace &ws) noexcept
ArrayOfVector ybatch_corr (Workspace &ws) noexcept
Index ybatch_index (Workspace &ws) noexcept
ArrayOfMatrix ybatch_jacobians (Workspace &ws) noexcept
Index ybatch_n (Workspace &ws) noexcept
Index ybatch_start (Workspace &ws) noexcept
Vector yf (Workspace &ws) noexcept
Tensor3 z_field (Workspace &ws) noexcept
GriddedField3 z_field_raw (Workspace &ws) noexcept
Numeric z_hse_accuracy (Workspace &ws) noexcept
Matrix z_surface (Workspace &ws) noexcept
Vector za_grid (Workspace &ws) noexcept
Vector za_grid_weights (Workspace &ws) noexcept
Index za_index (Workspace &ws) noexcept
AbsorptionLines AbsorptionLinesCreate (Workspace &ws, const Group::AbsorptionLines &inval, const Group::String &name, const Group::String &desc="nodescription")
Agenda AgendaCreate (Workspace &ws, const Group::Agenda &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfAbsorptionLines ArrayOfAbsorptionLinesCreate (Workspace &ws, const Group::ArrayOfAbsorptionLines &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfAgenda ArrayOfAgendaCreate (Workspace &ws, const Group::ArrayOfAgenda &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfAbsorptionLines ArrayOfArrayOfAbsorptionLinesCreate (Workspace &ws, const Group::ArrayOfArrayOfAbsorptionLines &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfGriddedField1 ArrayOfArrayOfGriddedField1Create (Workspace &ws, const Group::ArrayOfArrayOfGriddedField1 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfGriddedField2 ArrayOfArrayOfGriddedField2Create (Workspace &ws, const Group::ArrayOfArrayOfGriddedField2 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfGriddedField3 ArrayOfArrayOfGriddedField3Create (Workspace &ws, const Group::ArrayOfArrayOfGriddedField3 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfIndex ArrayOfArrayOfIndexCreate (Workspace &ws, const Group::ArrayOfArrayOfIndex &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfMatrix ArrayOfArrayOfMatrixCreate (Workspace &ws, const Group::ArrayOfArrayOfMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfPropagationMatrix ArrayOfArrayOfPropagationMatrixCreate (Workspace &ws, const Group::ArrayOfArrayOfPropagationMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfRadiationVector ArrayOfArrayOfRadiationVectorCreate (Workspace &ws, const Group::ArrayOfArrayOfRadiationVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfScatteringMetaData ArrayOfArrayOfScatteringMetaDataCreate (Workspace &ws, const Group::ArrayOfArrayOfScatteringMetaData &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfSingleScatteringData ArrayOfArrayOfSingleScatteringDataCreate (Workspace &ws, const Group::ArrayOfArrayOfSingleScatteringData &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfSpeciesTag ArrayOfArrayOfSpeciesTagCreate (Workspace &ws, const Group::ArrayOfArrayOfSpeciesTag &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfStokesVector ArrayOfArrayOfStokesVectorCreate (Workspace &ws, const Group::ArrayOfArrayOfStokesVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfString ArrayOfArrayOfStringCreate (Workspace &ws, const Group::ArrayOfArrayOfString &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfTensor3 ArrayOfArrayOfTensor3Create (Workspace &ws, const Group::ArrayOfArrayOfTensor3 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfTensor6 ArrayOfArrayOfTensor6Create (Workspace &ws, const Group::ArrayOfArrayOfTensor6 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfTime ArrayOfArrayOfTimeCreate (Workspace &ws, const Group::ArrayOfArrayOfTime &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfTransmissionMatrix ArrayOfArrayOfTransmissionMatrixCreate (Workspace &ws, const Group::ArrayOfArrayOfTransmissionMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfArrayOfVector ArrayOfArrayOfVectorCreate (Workspace &ws, const Group::ArrayOfArrayOfVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfCIARecord ArrayOfCIARecordCreate (Workspace &ws, const Group::ArrayOfCIARecord &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfGriddedField1 ArrayOfGriddedField1Create (Workspace &ws, const Group::ArrayOfGriddedField1 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfGriddedField2 ArrayOfGriddedField2Create (Workspace &ws, const Group::ArrayOfGriddedField2 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfGriddedField3 ArrayOfGriddedField3Create (Workspace &ws, const Group::ArrayOfGriddedField3 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfGriddedField4 ArrayOfGriddedField4Create (Workspace &ws, const Group::ArrayOfGriddedField4 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfIndex ArrayOfIndexCreate (Workspace &ws, const Group::ArrayOfIndex &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfJacobianTarget ArrayOfJacobianTargetCreate (Workspace &ws, const Group::ArrayOfJacobianTarget &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfMatrix ArrayOfMatrixCreate (Workspace &ws, const Group::ArrayOfMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfPpath ArrayOfPpathCreate (Workspace &ws, const Group::ArrayOfPpath &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfPropagationMatrix ArrayOfPropagationMatrixCreate (Workspace &ws, const Group::ArrayOfPropagationMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfQuantumIdentifier ArrayOfQuantumIdentifierCreate (Workspace &ws, const Group::ArrayOfQuantumIdentifier &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfRadiationVector ArrayOfRadiationVectorCreate (Workspace &ws, const Group::ArrayOfRadiationVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfRetrievalQuantity ArrayOfRetrievalQuantityCreate (Workspace &ws, const Group::ArrayOfRetrievalQuantity &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfScatteringMetaData ArrayOfScatteringMetaDataCreate (Workspace &ws, const Group::ArrayOfScatteringMetaData &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfSingleScatteringData ArrayOfSingleScatteringDataCreate (Workspace &ws, const Group::ArrayOfSingleScatteringData &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfSparse ArrayOfSparseCreate (Workspace &ws, const Group::ArrayOfSparse &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfSpeciesTag ArrayOfSpeciesTagCreate (Workspace &ws, const Group::ArrayOfSpeciesTag &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfStokesVector ArrayOfStokesVectorCreate (Workspace &ws, const Group::ArrayOfStokesVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfString ArrayOfStringCreate (Workspace &ws, const Group::ArrayOfString &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTelsemAtlas ArrayOfTelsemAtlasCreate (Workspace &ws, const Group::ArrayOfTelsemAtlas &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTensor3 ArrayOfTensor3Create (Workspace &ws, const Group::ArrayOfTensor3 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTensor4 ArrayOfTensor4Create (Workspace &ws, const Group::ArrayOfTensor4 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTensor5 ArrayOfTensor5Create (Workspace &ws, const Group::ArrayOfTensor5 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTensor6 ArrayOfTensor6Create (Workspace &ws, const Group::ArrayOfTensor6 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTensor7 ArrayOfTensor7Create (Workspace &ws, const Group::ArrayOfTensor7 &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTime ArrayOfTimeCreate (Workspace &ws, const Group::ArrayOfTime &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfTransmissionMatrix ArrayOfTransmissionMatrixCreate (Workspace &ws, const Group::ArrayOfTransmissionMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfVector ArrayOfVectorCreate (Workspace &ws, const Group::ArrayOfVector &inval, const Group::String &name, const Group::String &desc="nodescription")
ArrayOfXsecRecord ArrayOfXsecRecordCreate (Workspace &ws, const Group::ArrayOfXsecRecord &inval, const Group::String &name, const Group::String &desc="nodescription")
CIARecord CIARecordCreate (Workspace &ws, const Group::CIARecord &inval, const Group::String &name, const Group::String &desc="nodescription")
CovarianceMatrix CovarianceMatrixCreate (Workspace &ws, const Group::CovarianceMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
EnergyLevelMap EnergyLevelMapCreate (Workspace &ws, const Group::EnergyLevelMap &inval, const Group::String &name, const Group::String &desc="nodescription")
GasAbsLookup GasAbsLookupCreate (Workspace &ws, const Group::GasAbsLookup &inval, const Group::String &name, const Group::String &desc="nodescription")
GridPos GridPosCreate (Workspace &ws, const Group::GridPos &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField1 GriddedField1Create (Workspace &ws, const Group::GriddedField1 &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField2 GriddedField2Create (Workspace &ws, const Group::GriddedField2 &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField3 GriddedField3Create (Workspace &ws, const Group::GriddedField3 &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField4 GriddedField4Create (Workspace &ws, const Group::GriddedField4 &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField5 GriddedField5Create (Workspace &ws, const Group::GriddedField5 &inval, const Group::String &name, const Group::String &desc="nodescription")
GriddedField6 GriddedField6Create (Workspace &ws, const Group::GriddedField6 &inval, const Group::String &name, const Group::String &desc="nodescription")
HitranRelaxationMatrixData HitranRelaxationMatrixDataCreate (Workspace &ws, const Group::HitranRelaxationMatrixData &inval, const Group::String &name, const Group::String &desc="nodescription")
Index IndexCreate (Workspace &ws, const Group::Index &inval, const Group::String &name, const Group::String &desc="nodescription")
JacobianTarget JacobianTargetCreate (Workspace &ws, const Group::JacobianTarget &inval, const Group::String &name, const Group::String &desc="nodescription")
MCAntenna MCAntennaCreate (Workspace &ws, const Group::MCAntenna &inval, const Group::String &name, const Group::String &desc="nodescription")
MapOfErrorCorrectedSuddenData MapOfErrorCorrectedSuddenDataCreate (Workspace &ws, const Group::MapOfErrorCorrectedSuddenData &inval, const Group::String &name, const Group::String &desc="nodescription")
Matrix MatrixCreate (Workspace &ws, const Group::Matrix &inval, const Group::String &name, const Group::String &desc="nodescription")
Numeric NumericCreate (Workspace &ws, const Group::Numeric &inval, const Group::String &name, const Group::String &desc="nodescription")
Ppath PpathCreate (Workspace &ws, const Group::Ppath &inval, const Group::String &name, const Group::String &desc="nodescription")
PropagationMatrix PropagationMatrixCreate (Workspace &ws, const Group::PropagationMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
QuantumIdentifier QuantumIdentifierCreate (Workspace &ws, const Group::QuantumIdentifier &inval, const Group::String &name, const Group::String &desc="nodescription")
RadiationVector RadiationVectorCreate (Workspace &ws, const Group::RadiationVector &inval, const Group::String &name, const Group::String &desc="nodescription")
Rational RationalCreate (Workspace &ws, const Group::Rational &inval, const Group::String &name, const Group::String &desc="nodescription")
ScatteringMetaData ScatteringMetaDataCreate (Workspace &ws, const Group::ScatteringMetaData &inval, const Group::String &name, const Group::String &desc="nodescription")
SingleScatteringData SingleScatteringDataCreate (Workspace &ws, const Group::SingleScatteringData &inval, const Group::String &name, const Group::String &desc="nodescription")
Sparse SparseCreate (Workspace &ws, const Group::Sparse &inval, const Group::String &name, const Group::String &desc="nodescription")
SpeciesIsotopologueRatios SpeciesIsotopologueRatiosCreate (Workspace &ws, const Group::SpeciesIsotopologueRatios &inval, const Group::String &name, const Group::String &desc="nodescription")
StokesVector StokesVectorCreate (Workspace &ws, const Group::StokesVector &inval, const Group::String &name, const Group::String &desc="nodescription")
String StringCreate (Workspace &ws, const Group::String &inval, const Group::String &name, const Group::String &desc="nodescription")
TelsemAtlas TelsemAtlasCreate (Workspace &ws, const Group::TelsemAtlas &inval, const Group::String &name, const Group::String &desc="nodescription")
Tensor3 Tensor3Create (Workspace &ws, const Group::Tensor3 &inval, const Group::String &name, const Group::String &desc="nodescription")
Tensor4 Tensor4Create (Workspace &ws, const Group::Tensor4 &inval, const Group::String &name, const Group::String &desc="nodescription")
Tensor5 Tensor5Create (Workspace &ws, const Group::Tensor5 &inval, const Group::String &name, const Group::String &desc="nodescription")
Tensor6 Tensor6Create (Workspace &ws, const Group::Tensor6 &inval, const Group::String &name, const Group::String &desc="nodescription")
Tensor7 Tensor7Create (Workspace &ws, const Group::Tensor7 &inval, const Group::String &name, const Group::String &desc="nodescription")
TessemNN TessemNNCreate (Workspace &ws, const Group::TessemNN &inval, const Group::String &name, const Group::String &desc="nodescription")
Time TimeCreate (Workspace &ws, const Group::Time &inval, const Group::String &name, const Group::String &desc="nodescription")
Timer TimerCreate (Workspace &ws, const Group::Timer &inval, const Group::String &name, const Group::String &desc="nodescription")
TransmissionMatrix TransmissionMatrixCreate (Workspace &ws, const Group::TransmissionMatrix &inval, const Group::String &name, const Group::String &desc="nodescription")
Vector VectorCreate (Workspace &ws, const Group::Vector &inval, const Group::String &name, const Group::String &desc="nodescription")
Verbosity VerbosityCreate (Workspace &ws, const Group::Verbosity &inval, const Group::String &name, const Group::String &desc="nodescription")
Function Documentation
aa_grid()
Vector ARTS::Var::aa_grid (Workspace & ws) inline noexcept
Azimuthal angle grid.
The azimutal angle grid, on which the cloudbox_field is stored. This grid is used for RT calculations inside the cloudbox, therefore one has to define it if the cloudbox is activated by the flag cloudbox_on. Furthermore the zenith angle grid is also usedfor RT calculations of clear-sky spectral radiance field. The grid must be sorted in increasing order, with no repetitions.
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4656 of file autoarts.h.
Referenced by AngIntegrate_trapezoid(), AngIntegrate_trapezoid_fixedstep(), AngIntegrate_trapezoid_fixedstep_opt(), AngIntegrate_trapezoid_fixedstep_opt2(), AngIntegrate_trapezoid_opt(), AngIntegrate_trapezoid_opti(), AngIntegrate_trapezoid_original(), AngularGridsSetFluxCalc(), ARTS::Method::AngularGridsSetFluxCalc(), antenna2d_gridded_dlos(), cloud_ppath_update3D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), DOAngularGridsSet(), ARTS::Method::DOAngularGridsSet(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), FouComp_1ScatElem(), get_stepwise_scattersky_source(), init_xy(), irradiance_fieldFromRadiance(), ARTS::Method::irradiance_fieldFromRadiance(), iyHybrid(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matTransform(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), spectral_irradiance_fieldFromSpectralRadianceField(), ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField(), test_AngIntegrate_trapezoid_opti(), test_xy(), test_xy_fixedstep(), test_xy_fixedstep_opt(), test_xy_fixedstep_opt2(), and test_xy_opt().
aa_index()
Index ARTS::Var::aa_index (Workspace & ws) inline noexcept
Azimuth angle index for scattering calculations.
This variable is used in methods used for computing scattering properties. It holds the information about the azimuth angles for which the scattering calculations are done. The angles used for computing scattering properties of particles can be different from that used for radiative transfer calculation.
Usage: Method output.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4672 of file autoarts.h.
Referenced by cloud_fieldsCalc(), cloud_ppath_update3D(), cloudbox_fieldSetClearsky(), cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq3D(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), DoitGetIncoming(), DoitGetIncoming1DAtm(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
abs_cia_data()
ArrayOfCIARecord ARTS::Var::abs_cia_data (Workspace & ws) inline noexcept
HITRAN Collision Induced Absorption (CIA) Data.
This variable holds HITRAN CIA data (binary absorption cross-sections). The data itself is described in: Richard, C. et al. (2012), New section of the HITRAN database: Collision-induced absorption (CIA), J. Quant. Spectrosc. Radiat. Transfer, 113, 1276-1285, doi:10.1016/j.jqsrt.2011.11.004.
The binary absorption cross-sections have to be multiplied with the densities of both molecules to get absorption coefficients.
Dimensions:
The outer array dimension in the ArrayOfArrayOfCIARecord is the same as that of abs_species. There will be CIA data only for those species that contain a CIA tag, for all other species it will be empty. The inner array dimension corresponds to the number of CIA tags for this species (there could be for example both N2-N2 and N2-H2) in the same species.
The CIA abs_species tags are described in abs_speciesSet.
Each individual CIARecord holds the complete information from one HITRAN CIA file. For the given pair of molecules A HITRAN CIA data file can hold several datasets (data for different temperatures but fixed frequency range).
Units: Frequencies: Hz Binary absorption cross-sections: m^5*molecule^-2
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4708 of file autoarts.h.
Referenced by abs_cia_dataAddCIARecord(), ARTS::Method::abs_cia_dataAddCIARecord(), abs_cia_dataReadFromCIA(), ARTS::Method::abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), ARTS::Method::abs_cia_dataReadFromXML(), abs_xsec_per_speciesAddCIA(), and ARTS::Method::abs_xsec_per_speciesAddCIA().
abs_cont_models()
ArrayOfString ARTS::Var::abs_cont_models (Workspace & ws) inline noexcept
Continuum / full model absorption model description parameter.
See the WSV ‘abs_cont_names’ for a detailed description of the allowed continuum models. There should be one string here for each entry in ‘abs_cont_names’.See also the online documentation in arts/doc/doxygen/html/continua_cc.html.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4720 of file autoarts.h.
Referenced by abs_cont_descriptionAppend(), ARTS::Method::abs_cont_descriptionAppend(), ARTS::Method::abs_cont_descriptionInit(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), and continua_model_error_message().
abs_cont_names()
ArrayOfString ARTS::Var::abs_cont_names (Workspace & ws) inline noexcept
Continuum / full model absorption tag names.
This variable should contain a list of tag names of continuum and full models, respectively. Associated with this WSV is the WSV ‘abs_cont_models’ which contains the specific model version of each continuum / full model absorption tag and the WSV ‘abs_cont_parameters’ which should contain the continuum / full model user defined parameters. The user defined parameters are only used when the specified model is 'user'. See also the online documentation in arts/doc/doxygen/html/continua_cc.html.
The following full water vapor models are implemented: 'H2O-MPM87': absorption model (line and continuum) according to H. J. Liebe, A contribution to modeling atmospheric millimeter-wave properties, Frequenz, 41, 1987, 31-36 and H. J. Liebe and D. H. Layton, Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modeling, U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences, 325 Broadway, Boulder, CO 80303-3328, report 87224. 'H2O-MPM89': absorption model (line and continuum) according to H. J. Liebe, Int. J. Infrared and Millimeter Waves, 10(6), 1989, 631 'H2O-MPM93': absorption model (line and continuum) according to H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) 'H2O-CP98': absorption model (line and continuum) according to S. L. Cruz-Pol et al., Radio Science, 33(5), 1319, 1998 (ece.uprm.edu/~pol/Atmosphere.html) 'H2O-PWR98': absorption model (line and continuum) according to P. W. Rosenkranz, Radio Science, 33(4), 919, 1998, Radio Science, 34(4), 1025, 1999 (ftp: mesa.mit.edu/phil/lbl_rt).
The following full oxygen models are implemented: 'O2-MPM93': absorption model (line and continuum) according to H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) 'O2-PWR93': absorption model (line and continuum) according to P. W. Rosenkranz, Chapter 2, in M. A. Janssen, Atmospheric Remote Sensing by Microwave Radiometry John Wiley & Sons, Inc., 1993 (mesa.mit.edu/phil/lbl_rt)
The following continuum parameterizations are implemented: H2O-H2O ('H2O-SelfContStandardType'): P. W. Rosenkranz, Radio Science, Vol. 33, No 4, Pages 919-928, 1998 and Radio Science, Vol. 34, No 4, Page 1025, 1999 (mesa.mit.edu/phil/lbl_rt) H2O-air ('H2O-ForeignContStandardType'): P. W. Rosenkranz, Radio Science, Vol. 33, No 4, Pages 919-928, 1998 and Radio Science, Vol. 34, No 4, Page 1025, 1999 (mesa.mit.edu/phil/lbl_rt) H2O-air ('H2O-ContMPM93'): H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) O2-air ('O2-SelfContStandardType'): P. W. Rosenkranz, Chapter 2, in M. A. Janssen, Atmospheric Remote Sensing by Microwave Radiometry, John Wiley & Sons, Inc., 1993 (mesa.mit.edu/phil/lbl_rt) and also described in H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) N2-N2 ('N2-SelfContStandardType'): The functional form of Rosenkranz but with more input parameters. P. W. Rosenkranz, Chapter 2, in M. A. Janssen, Atmospheric Remote Sensing by Microwave Radiometry, John Wiley & Sons, Inc., 1993 (mesa.mit.edu/phil/lbl_rt) N2-N2 ('N2-SelfContMPM93'): H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) CO2-CO2 ('CO2-SelfContPWR93'): P. W. Rosenkranz, Chapter 2, in M. A. Janssen, Atmospheric Remote Sensing by Microwave Radiometry, John Wiley & Sons, Inc., 1993 (mesa.mit.edu/phil/lbl_rt) CO2-N2 ('CO2-ForeignContPWR93'): P. W. Rosenkranz, Chapter 2, in M. A. Janssen, Atmospheric Remote Sensing by Microwave Radiometry, John Wiley & Sons, Inc., 1993 (mesa.mit.edu/phil/lbl_rt)
The following cloud absorption models are implemented: Suspended water droplet ('liquidcloud-MPM93') absorption parameterization from the MPM93 model: H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/) Ice water droplet absorption ('icecloud-MPM93') parameterization from MPM93 model: H. J. Liebe and G. A. Hufford and M. G. Cotton, Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz, AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel, Palma de Mallorca, Spain, 1993, May 17-21 (ftp.its.bldrdoc.gov/pub/mpm93/)
The following rain extinction model is implemented: Rain extinction parameterization ('rain-MPM93') from the MPM93 model, described in: H. J. Liebe, MPM - An Atmospheric Millimeter-Wave Propagation Model, Int. J. Infrared and Millimeter Waves, vol. 10(6), pp. 631-650, 1989; and based on: Olsen, R.L., D.V. Rogers, and D. B. Hodge, The aR^b relation in the calculation of rain attenuation, IEEE Trans. Antennas Propagat., vol. AP-26, pp. 318-329, 1978. IMPORTANT NOTE: rain-MPM93 parameterizes the EXTINCTION by rain, not just the absorption. Therefore it is not suitable for calculating thermal emission by rain! Please use rain-MPM93 only for calculation of attenuation.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4874 of file autoarts.h.
Referenced by abs_cont_descriptionAppend(), ARTS::Method::abs_cont_descriptionAppend(), abs_cont_descriptionInit(), ARTS::Method::abs_cont_descriptionInit(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), and continua_model_error_message().
abs_cont_parameters()
ArrayOfVector ARTS::Var::abs_cont_parameters (Workspace & ws) inline noexcept
Continuum model parameters. See the WSV abs_cont_names
for a detailed description of the allowed continuum models. There should be one parameter vector here for each entry in abs_cont_names*. See also the online documentation in arts/doc/doxygen/html/continua_cc.html.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4886 of file autoarts.h.
Referenced by abs_cont_descriptionAppend(), ARTS::Method::abs_cont_descriptionAppend(), abs_cont_descriptionInit(), ARTS::Method::abs_cont_descriptionInit(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), and continua_model_error_message().
abs_f_interp_order()
Index ARTS::Var::abs_f_interp_order (Workspace & ws) inline noexcept
Frequency interpolation order for absorption lookup table.
The interpolation order to use when interpolating the absorption lookup table in frequency. This is in particular needed for calculations with Doppler shift, so that absorption is interpolated to the shifted frequency grid. One is linear interpolation, two quadratic, and so on.
As a special case, order 0 in this particular case means no interpolation. In that case f_grid must match exactly the grid inside the lookup table. This is the global default value, set in general.arts.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4904 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_hitran_relmat_data()
HitranRelaxationMatrixData ARTS::Var::abs_hitran_relmat_data (Workspace & ws) inline noexcept
HITRAN line mixing data to compute the relaxation matrix.
This variable holds HITRAN line mixing data as per J. Lamouroux, L. Realia, X. Thomas, et al., J.Q.S.R.T. 151 (2015), 88-96
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4914 of file autoarts.h.
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), ARTS::Method::abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), propmat_clearskyAddHitranLineMixingLines(), and ARTS::Method::propmat_clearskyAddHitranLineMixingLines().
abs_lines()
ArrayOfAbsorptionLines ARTS::Var::abs_lines (Workspace & ws) inline noexcept
A list of spectral line data.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4921 of file autoarts.h.
Referenced by abs_lines_per_speciesAdaptHitranLineMixing(), abs_lines_per_speciesCreateFromLines(), ARTS::Method::abs_lines_per_speciesCreateFromLines(), abs_lines_per_speciesHitranLineMixingAdaptationData(), abs_lines_per_speciesMakeManualMirroring(), abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLineShapeType(), abs_lines_per_speciesSetLineShapeTypeForMatch(), abs_lines_per_speciesSetMirroring(), abs_lines_per_speciesSetMirroringForMatch(), abs_lines_per_speciesSetNormalization(), abs_lines_per_speciesSetNormalizationForMatch(), abs_lines_per_speciesSetPopulation(), abs_lines_per_speciesSetPopulationForMatch(), abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForMatch(), abs_lines_per_speciesSetZeemanCoefficients(), abs_lines_per_speciesTruncateQuantumNumbers(), abs_lines_per_speciesWriteSpeciesSplitXML(), abs_linesAppendWithLines(), ARTS::Method::abs_linesAppendWithLines(), abs_linesChangeBaseParameterForMatchingLevel(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLevel(), abs_linesChangeBaseParameterForMatchingLevels(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLevels(), abs_linesChangeBaseParameterForMatchingLines(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLines(), abs_linesCleanupEmpty(), ARTS::Method::abs_linesCleanupEmpty(), abs_linesCompact(), ARTS::Method::abs_linesCompact(), abs_linesDeleteBadF0(), ARTS::Method::abs_linesDeleteBadF0(), abs_linesDeleteLinesWithBadOrHighChangingJs(), ARTS::Method::abs_linesDeleteLinesWithBadOrHighChangingJs(), abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), abs_linesDeleteLinesWithUndefinedLocalQuanta(), ARTS::Method::abs_linesDeleteLinesWithUndefinedLocalQuanta(), abs_linesDeleteWithLines(), ARTS::Method::abs_linesDeleteWithLines(), abs_linesKeepBand(), ARTS::Method::abs_linesKeepBand(), abs_linesMakeManualMirroring(), ARTS::Method::abs_linesMakeManualMirroring(), abs_linesPrintDefinedQuantumNumbers(), ARTS::Method::abs_linesPrintDefinedQuantumNumbers(), abs_linesReadSpeciesSplitCatalog(), ARTS::Method::abs_linesReadSpeciesSplitCatalog(), abs_linesRemoveBand(), ARTS::Method::abs_linesRemoveBand(), abs_linesRemoveUnusedLocalQuantumNumbers(), ARTS::Method::abs_linesRemoveUnusedLocalQuantumNumbers(), abs_linesReplaceWithLines(), ARTS::Method::abs_linesReplaceWithLines(), abs_linesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), abs_linesSetBaseParameterForMatchingLines(), ARTS::Method::abs_linesSetBaseParameterForMatchingLines(), abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoff(), abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetCutoffForMatch(), abs_linesSetEmptyBroadeningParametersToEmpty(), ARTS::Method::abs_linesSetEmptyBroadeningParametersToEmpty(), abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimit(), abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), abs_linesSetLineShapeType(), ARTS::Method::abs_linesSetLineShapeType(), abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), abs_linesSetMirroring(), ARTS::Method::abs_linesSetMirroring(), abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetMirroringForMatch(), abs_linesSetNormalization(), ARTS::Method::abs_linesSetNormalization(), abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetNormalizationForMatch(), abs_linesSetPopulation(), ARTS::Method::abs_linesSetPopulation(), abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetPopulationForMatch(), abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), abs_linesSetT0(), ARTS::Method::abs_linesSetT0(), abs_linesSetT0ForMatch(), ARTS::Method::abs_linesSetT0ForMatch(), abs_linesSetZeemanCoefficients(), ARTS::Method::abs_linesSetZeemanCoefficients(), abs_linesTruncateGlobalQuantumNumbers(), ARTS::Method::abs_linesTruncateGlobalQuantumNumbers(), abs_linesTruncateQuantumNumbers(), ARTS::Method::abs_linesTruncateQuantumNumbers(), abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), abs_linesWriteSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), checkIsotopologueRatios(), checkPartitionFunctions(), createAij(), createBij(), createBji(), createCji(), nlte_collision_factorsCalcFromCoeffs(), nlte_positions_in_statistical_equilibrium_matrix(), ReadArrayOfARTSCAT(), ARTS::Method::ReadArrayOfARTSCAT(), ReadARTSCAT(), ARTS::Method::ReadARTSCAT(), ReadHITRAN(), ARTS::Method::ReadHITRAN(), ReadJPL(), ARTS::Method::ReadJPL(), ReadLBLRTM(), ARTS::Method::ReadLBLRTM(), ReadSplitARTSCAT(), ARTS::Method::ReadSplitARTSCAT(), and setCji().
abs_lines_per_species()
ArrayOfArrayOfAbsorptionLines ARTS::Var::abs_lines_per_species (Workspace & ws) inline noexcept
A list of spectral line data for each tag.
Dimensions: [abs_species.nelem()][Depends on how many bands there are in abs_lines]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4930 of file autoarts.h.
Referenced by abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), ARTS::Method::abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), abs_lines_per_speciesAdaptHitranLineMixing(), ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), abs_lines_per_speciesChangeBaseParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLines(), abs_lines_per_speciesChangeBaseParameterForSpecies(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForSpecies(), abs_lines_per_speciesCompact(), ARTS::Method::abs_lines_per_speciesCompact(), abs_lines_per_speciesCreateFromLines(), ARTS::Method::abs_lines_per_speciesCreateFromLines(), abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), abs_lines_per_speciesMakeManualMirroring(), ARTS::Method::abs_lines_per_speciesMakeManualMirroring(), abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), abs_lines_per_speciesReadSpeciesSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), abs_lines_per_speciesSetBaseParameterForMatchingLines(), abs_lines_per_speciesSetBaseParameterForSpecies(), abs_lines_per_speciesSetCutoff(), ARTS::Method::abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), abs_lines_per_speciesSetEmpty(), ARTS::Method::abs_lines_per_speciesSetEmpty(), abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForMatch(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), abs_lines_per_speciesSetLineShapeType(), ARTS::Method::abs_lines_per_speciesSetLineShapeType(), abs_lines_per_speciesSetLineShapeTypeForMatch(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), abs_lines_per_speciesSetMirroring(), ARTS::Method::abs_lines_per_speciesSetMirroring(), abs_lines_per_speciesSetMirroringForMatch(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), abs_lines_per_speciesSetNormalization(), ARTS::Method::abs_lines_per_speciesSetNormalization(), abs_lines_per_speciesSetNormalizationForMatch(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), abs_lines_per_speciesSetPopulation(), ARTS::Method::abs_lines_per_speciesSetPopulation(), abs_lines_per_speciesSetPopulationForMatch(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForMatch(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), abs_lines_per_speciesTruncateQuantumNumbers(), ARTS::Method::abs_lines_per_speciesTruncateQuantumNumbers(), abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), ArrayOfQuantumIdentifierFromLines(), ARTS::Method::ArrayOfQuantumIdentifierFromLines(), checkIsotopologueRatios(), checkPartitionFunctions(), f_gridFromAbsorptionLines(), ARTS::Method::f_gridFromAbsorptionLines(), lbl_checkedCalc(), ARTS::Method::lbl_checkedCalc(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), nlteSetByQuantumIdentifiers(), ARTS::Method::nlteSetByQuantumIdentifiers(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), and zeeman_on_the_fly().
abs_lookup()
GasAbsLookup ARTS::Var::abs_lookup (Workspace & ws) inline noexcept
An absorption lookup table.
It holds an absorption lookup table, as well as all information that is necessary to use the table to extract absorption. Extraction routines are implemented as member functions.
It has quite a complicated structure. For details see the Arts User Guide section "The gas absorption lookup table" or the source code documentation in gas_abs_lookup.h.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4945 of file autoarts.h.
Referenced by abs_lookupAdapt(), ARTS::Method::abs_lookupAdapt(), ARTS::Method::abs_lookupCalc(), ARTS::Method::abs_lookupInit(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), f_gridFromGasAbsLookup(), ARTS::Method::f_gridFromGasAbsLookup(), p_gridFromGasAbsLookup(), ARTS::Method::p_gridFromGasAbsLookup(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_lookup_is_adapted()
Index ARTS::Var::abs_lookup_is_adapted (Workspace & ws) inline noexcept
Flag to indicate whether abs_lookupAdapt has already been called.
Values: 0=false, 1=true.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4955 of file autoarts.h.
Referenced by abs_lookupAdapt(), ARTS::Method::abs_lookupAdapt(), ARTS::Method::abs_lookupCalc(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_nls()
ArrayOfArrayOfSpeciesTag ARTS::Var::abs_nls (Workspace & ws) inline noexcept
Nonlinear species for absorption lookup table generation.
A list of absorption species that should be treated non-linearly. This means that the H2O VMR should be varied when calculating the lookup table for those species.
A typical example is for this to containt the Rosenkranz full absorption model species for water vapor and oxygen (["H2O-PWR98", "O2-PWR93"]).
See user guide and online documentation of abs_lookupCalc for more details and usage examples.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4973 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), and choose_abs_nls().
abs_nls_interp_order()
Index ARTS::Var::abs_nls_interp_order (Workspace & ws) inline noexcept
The interpolation order to use when interpolating absorption between the H2O values given by abs_nls_pert.
This is used by methods extracting absorption coefficients from the lookup table, and by methods setting up parameters for lookup table generation. Has a default value, which is set in general.arts.
Note that the number of points used in the interpolation scheme is interpolation order + 1 (e.g., two for first order interpolation).
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 4989 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupWide(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_nls_pert()
Vector ARTS::Var::abs_nls_pert (Workspace & ws) inline noexcept
Fractional perturbations for the nonlinear species in the absorption lookup table.
This is a vector of fractional perturbations that should contain 1 (the unperturbed reference profile). A value of 0 may lead to error messages from some absorption routines, so a possible content for this variable is: [1e-24, 1, 2]. (This is similar to abs_t_pert, but multiplicative, not additive.)
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5003 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupWide(), and choose_abs_nls_pert().
abs_nlte()
EnergyLevelMap ARTS::Var::abs_nlte (Workspace & ws) inline noexcept
NLTE temperatures or ratios to be used for the calculation of absorption coefficients.
In contrast to the global nlte_field, this is just a matrix. Any absorption method should check that the columns of this vector is the same as that of abs_p
Dimension: [nltes, 1, 1, p_grid] or [ 0, 0, 0, 0 ]
Unit: K
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5019 of file autoarts.h.
Referenced by abs_nlteFromRaw(), ARTS::Method::abs_nlteFromRaw(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), and xsec_species().
abs_p()
Vector ARTS::Var::abs_p (Workspace & ws) inline noexcept
List of pressures to be used for the calculation of absorption coefficients.
This can be copied from the global p_grid, but could also be different.
Any absorption method should check that the length of this vector is the same as that of abs_t
Dimension: [p_grid]
Unit: Pa
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5037 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), AbsInputFromRteScalars(), BF86_CIA_N2(), CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), CP98H2OAbsModel(), ELL07WaterDropletAbs(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), MaTipping_H2O_foreign_continuum(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), propmat_clearskyAddXsecAgenda(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), TRE05O2AbsModel(), xsec_continuum_tag(), and xsec_species().
abs_p_interp_order()
Index ARTS::Var::abs_p_interp_order (Workspace & ws) inline noexcept
The interpolation order to use when interpolating absorption between pressure levels.
This is used by methods extracting absorption coefficients from the lookup table, and by methods setting up parameters for lookup table generation. Has a default value, which is set in general.arts.
Note that the number of points used in the interpolation scheme is interpolation order + 1 (e.g., two for first order interpolation).
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5053 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_species()
ArrayOfArrayOfSpeciesTag ARTS::Var::abs_species (Workspace & ws) inline noexcept
Tag groups for gas absorption.
This is an array of arrays of SpeciesTag tag definitions. It defines the available tag groups for the calculation of scalar gas absorption coefficients. See online documentation of method abs_speciesSet for more detailed information how tag groups work and some examples.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5065 of file autoarts.h.
Referenced by abs_cia_dataReadFromCIA(), ARTS::Method::abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), ARTS::Method::abs_cia_dataReadFromXML(), abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), ARTS::Method::abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), abs_lines_per_speciesChangeBaseParameterForSpecies(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForSpecies(), ARTS::Method::abs_lines_per_speciesCreateFromLines(), abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), abs_lines_per_speciesReadSpeciesSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), abs_lines_per_speciesSetBaseParameterForSpecies(), abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), abs_lines_per_speciesSetEmpty(), ARTS::Method::abs_lines_per_speciesSetEmpty(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), abs_lookupAdapt(), ARTS::Method::abs_lookupAdapt(), ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), abs_speciesAdd(), ARTS::Method::abs_speciesAdd(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), abs_speciesDefineAll(), ARTS::Method::abs_speciesDefineAll(), ARTS::Method::abs_speciesDefineAllInScenario(), abs_speciesInit(), ARTS::Method::abs_speciesInit(), abs_speciesSet(), ARTS::Method::abs_speciesSet(), ARTS::Agenda::Execute::abs_xsec_agenda(), ARTS::Method::abs_xsec_agenda_checkedCalc(), abs_xsec_agenda_checkedCalc(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesInit(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), check_abs_species(), choose_abs_nls(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), collision_coefficientsFromSplitFiles(), ARTS::Method::collision_coefficientsFromSplitFiles(), find_nonlinear_continua(), get_pointers_for_analytical_species(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), lbl_checkedCalc(), ARTS::Method::lbl_checkedCalc(), lbl_species(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), nlte_collision_factorsCalcFromCoeffs(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::propmat_clearsky_agenda_checkedCalc(), propmat_clearsky_agenda_checkedCalc(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddFromAbsCoefPerSpecies(), propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), ReadSplitARTSCAT(), ARTS::Method::ReadSplitARTSCAT(), ARTS::Method::refr_index_airFreeElectrons(), refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), set_vmr_from_first_species(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), vmr_fieldClip(), ARTS::Method::vmr_fieldClip(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldSetAllConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), xsec_species(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::z_fieldFromHSE(), and zeeman_on_the_fly().
abs_species_active()
ArrayOfIndex ARTS::Var::abs_species_active (Workspace & ws) inline noexcept
Indices of active absorption species.
This variable selects, which absorption species are active in abs_xsec_agenda*.
Dimension: A vector with one element for every active species, at max same number of elements as abs_species.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5078 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), and propmat_clearskyAddXsecAgenda().
abs_t()
Vector ARTS::Var::abs_t (Workspace & ws) inline noexcept
List of temperatures to be used for the calculation of absorption coefficients.
In contrast to the global t_field, this is just a vector. Any absorption method should check that the length of this vector is the same as that of abs_p
Dimension: [p_grid]
Unit: K
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5094 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), AbsInputFromRteScalars(), BF86_CIA_N2(), choose_abs_t_pert(), CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), CP98H2OAbsModel(), ELL07WaterDropletAbs(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), MaTipping_H2O_foreign_continuum(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), propmat_clearskyAddXsecAgenda(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), TRE05O2AbsModel(), xsec_continuum_tag(), and xsec_species().
abs_t_interp_order()
Index ARTS::Var::abs_t_interp_order (Workspace & ws) inline noexcept
The interpolation order to use when interpolating absorption between the temperature values given by abs_t_pert.
This is used by methods extracting absorption coefficients from the lookup table, and by methods setting up parameters for lookup table generation. Has a default value, which is set in general.arts.
Note that the number of points used in the interpolation scheme is interpolation order + 1 (e.g., two for first order interpolation).
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5110 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), propmat_clearskyAddFromLookup(), and ARTS::Method::propmat_clearskyAddFromLookup().
abs_t_pert()
Vector ARTS::Var::abs_t_pert (Workspace & ws) inline noexcept
Temperature perturbations for the absorption lookup table.
This is a vector containing temperature perturbations (in Kelvin) that should be added to the reference temperature profile. (Similar to abs_nls_pert*, but additive, not multiplicative.) Should normally contain 0, to include the reference profile itself. Example content: [-5, 0, 5].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5123 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), and choose_abs_t_pert().
abs_vec()
StokesVector ARTS::Var::abs_vec (Workspace & ws) inline noexcept
Total absorption vector.
This variable contains the absorption coefficient vector which is used in the RTE calculation. It is the physical absorption which includes particle absorption for all considered scattering elements as well as gaseous absorption for all selected gaseous species. The vector is calculated by opt_prop_bulkCalc The dimension of the variable adapts to stokes_dim.
See ARTS user guide (AUG) for further information. Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Output of opt_prop_bulkCalc
Unit: m^2
Dimensions: [f_grid, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5147 of file autoarts.h.
Referenced by abs_vecAddGas(), ARTS::Method::abs_vecAddGas(), cloud_ppath_update1D_planeparallel(), ext_matFromabs_vec(), opt_prop_1ScatElem(), opt_prop_Bulk(), opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_NScatElems(), opt_prop_ScatSpecBulk(), opt_prop_sum_propmat_clearsky(), and OptimizeDoitPressureGrid().
abs_vec_spt()
ArrayOfStokesVector ARTS::Var::abs_vec_spt (Workspace & ws) inline noexcept
Absorption vectors of the scattering elements.
This variable contains the elements of the absorption vector of the individual scattering elements. It is calculated in the agenda spt_calc_agenda*.
See ARTS user guide (AUG) for further information.
Usage: Input and Output of the method abs_vec_sptCalc
Unit: m^2
Dimensions: [number of scattering elements, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5166 of file autoarts.h.
Referenced by opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
abs_vmrs()
Matrix ARTS::Var::abs_vmrs (Workspace & ws) inline noexcept
The VMRs (unit: absolute number) on the abs_p grid.
Dimensions: [tag_groups.nelem(), abs_p.nelem()]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5175 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Method::abs_lookupCalc(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), ARTS::Method::abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupWide(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), AbsInputFromRteScalars(), GasAbsLookup::Extract(), propmat_clearskyAddXsecAgenda(), set_vmr_from_first_species(), and xsec_species().
abs_xsec_agenda()
Agenda ARTS::Var::abs_xsec_agenda (Workspace & ws) inline noexcept
Agenda to calculate scalar gas absorption cross sections.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5182 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupCalc(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), ARTS::Agenda::Execute::abs_xsec_agenda(), ARTS::Agenda::Define::abs_xsec_agenda(), ARTS::Method::abs_xsec_agenda_checkedCalc(), abs_xsec_agenda_checkedCalc(), ARTS::Agenda::abs_xsec_agenda_standard(), ARTS::Agenda::abs_xsec_agenda_standard_with_cia(), ARTS::Method::propmat_clearskyAddXsecAgenda(), and propmat_clearskyAddXsecAgenda().
abs_xsec_agenda_checked()
Index ARTS::Var::abs_xsec_agenda_checked (Workspace & ws) inline noexcept
OK-flag for abs_xsec_agenda.
Set by abs_xsec_agenda_checkedCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5191 of file autoarts.h.
Referenced by abs_speciesAdd(), ARTS::Method::abs_speciesAdd(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), abs_speciesDefineAll(), ARTS::Method::abs_speciesDefineAll(), abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesDefineAllInScenario(), abs_speciesSet(), ARTS::Method::abs_speciesSet(), ARTS::Method::abs_xsec_agenda_checkedCalc(), abs_xsec_agenda_checkedCalc(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), ScatElementsToabs_speciesAdd(), and ARTS::Method::ScatElementsToabs_speciesAdd().
abs_xsec_per_species()
ArrayOfMatrix ARTS::Var::abs_xsec_per_species (Workspace & ws) inline noexcept
Absorption cross sections for the attenuation.
This variable contains absorption cross section xsec individually for each tag group. The Array contains one matrix for each tag group, the matrix format is the same as that of abs_coef.
Dimensions: [abs_species](f_grid, abs_p)
Unit: m^2 (alpha = xsec * n * VMR), where n is total density.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5207 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), and propmat_clearskyAddXsecAgenda().
AbsorptionLinesCreate()
AbsorptionLines ARTS::Var::AbsorptionLinesCreate (Workspace & ws, const Group::AbsorptionLines & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an AbsorptionLines
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] AbsorptionLines inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10781 of file autoarts.h.
References Workspace::add_wsv_inplace().
agenda_array_index()
Index ARTS::Var::agenda_array_index (Workspace & ws) inline noexcept
Index of the current agenda in ArrayOfAgenda.
This is set during the execution of an agenda from an ArrayOfAgenda. It indicates the index of the current agenda inside the array.
Unit: Integer value.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5219 of file autoarts.h.
Referenced by ArrayOfAgendaExecute(), ARTS::Method::ArrayOfAgendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), ARTS::Agenda::Execute::test_agenda_array(), and test_agenda_arrayExecute().
AgendaCreate()
Agenda ARTS::Var::AgendaCreate (Workspace & ws, const Group::Agenda & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Agenda
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Agenda inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10800 of file autoarts.h.
References Workspace::add_wsv_inplace().
antenna_dim()
Index ARTS::Var::antenna_dim (Workspace & ws) inline noexcept
The dimensionality of the antenna pattern (1-2).
A dimensionality of 1 means that only the respons variation in the zenith direction is considered. The provided respons shall then be the integrated in the azimuth direction. For 2D, the respons of the antenna has both a zenith and azimuth variation.
Usage: Set by the user.
Unit: Integer value [1-2].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5235 of file autoarts.h.
Referenced by antenna1d_matrix(), antenna2d_interp_response(), AntennaConstantGaussian1D(), ARTS::Method::AntennaConstantGaussian1D(), AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), AntennaOff(), ARTS::Method::AntennaOff(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensorOff(), and ySimpleSpectrometer().
antenna_dlos()
Matrix ARTS::Var::antenna_dlos (Workspace & ws) inline noexcept
The relative line-of-sight of each antenna pattern.
This variable describes the line-of-sight of the individual antennae relative to sensor_los. If each measurement block corresponds to a single antenna pattern, the normal choice is to set the angle(s) of this variable to zero.
The first column holds the relative zenith angle. This column is mandatory for all atmospheric dimensionalities. For 3D, there can also be a second column, giving relative azimuth angles. If this column is not present (for 3D) zero azimuth off-sets are assumed.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: [ degrees, degrees ]
Size: [ number of antennae, 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5262 of file autoarts.h.
Referenced by antenna2d_interp_response(), AntennaConstantGaussian1D(), ARTS::Method::AntennaConstantGaussian1D(), AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseMetMM(), and ARTS::Method::sensor_responseMetMM().
antenna_response()
GriddedField4 ARTS::Var::antenna_response (Workspace & ws) inline noexcept
The antenna pattern/response.
This WSV describes the antenna response as a function of polarisation (pol), frequencue (f), zenith angle (za) and azimuth angle (aa).
Polarisation dimension: If this dimension has size 1, the data are applied for all polarisations of concern. The data are otherwise used in sequential order. This signifies that, in general, the first polarisation "layer" corresponds to the first stokes dimension etc. An exception is if a polarisation rotation has been applied. In any case, it is up to the user to ensure that polarisations are consistently defined.
Frequency dimension: If this dimension has size 1, the data are applied for all frequencies of concern. The given frequency must be inside the frequency range of concern. A linear interpolation is otherwise applied.
Zenith angle dimension: This dimension must always have a size >= 2 The response outside covered grid range is treated as zero. If antenna_dim* equals 1, the data should correspond to the response integrated in the azimuthal direction.
Azimuth angle dimension: If antenna_dim equals 1, this dimension must have size 1. A size >= 2 is otherwise required. The response outside covered grid range is treated as zero.
Usage: Set by the user.
Dimensions: GriddedField4: ArrayOfString field_names[N_pol] Vector f_grid[N_f] Vector za_grid[N_za] Vector aa_grid[N_aa] Tensor4 data[N_pol][N_f][N_za][N_aa]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5304 of file autoarts.h.
Referenced by antenna1d_matrix(), antenna2d_interp_response(), ARTS::Method::antenna_responseGaussian(), ARTS::Method::antenna_responseVaryingGaussian(), ARTS::Method::AntennaConstantGaussian1D(), sensor_responseAntenna(), and ARTS::Method::sensor_responseAntenna().
ArrayOfAbsorptionLinesCreate()
ArrayOfAbsorptionLines ARTS::Var::ArrayOfAbsorptionLinesCreate (Workspace & ws, const Group::ArrayOfAbsorptionLines & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfAbsorptionLines
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfAbsorptionLines inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10819 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfAgendaCreate()
ArrayOfAgenda ARTS::Var::ArrayOfAgendaCreate (Workspace & ws, const Group::ArrayOfAgenda & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfAgenda
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfAgenda inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10838 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfAbsorptionLinesCreate()
ArrayOfArrayOfAbsorptionLines ARTS::Var::ArrayOfArrayOfAbsorptionLinesCreate (Workspace & ws, const Group::ArrayOfArrayOfAbsorptionLines & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfAbsorptionLines
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfAbsorptionLines inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10857 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfGriddedField1Create()
ArrayOfArrayOfGriddedField1 ARTS::Var::ArrayOfArrayOfGriddedField1Create (Workspace & ws, const Group::ArrayOfArrayOfGriddedField1 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfGriddedField1
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfGriddedField1 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10876 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfGriddedField2Create()
ArrayOfArrayOfGriddedField2 ARTS::Var::ArrayOfArrayOfGriddedField2Create (Workspace & ws, const Group::ArrayOfArrayOfGriddedField2 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfGriddedField2
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfGriddedField2 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10895 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfGriddedField3Create()
ArrayOfArrayOfGriddedField3 ARTS::Var::ArrayOfArrayOfGriddedField3Create (Workspace & ws, const Group::ArrayOfArrayOfGriddedField3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfGriddedField3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfGriddedField3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10914 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfIndexCreate()
ArrayOfArrayOfIndex ARTS::Var::ArrayOfArrayOfIndexCreate (Workspace & ws, const Group::ArrayOfArrayOfIndex & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfIndex
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfIndex inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10933 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfMatrixCreate()
ArrayOfArrayOfMatrix ARTS::Var::ArrayOfArrayOfMatrixCreate (Workspace & ws, const Group::ArrayOfArrayOfMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10952 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfPropagationMatrixCreate()
ArrayOfArrayOfPropagationMatrix ARTS::Var::ArrayOfArrayOfPropagationMatrixCreate (Workspace & ws, const Group::ArrayOfArrayOfPropagationMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfPropagationMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfPropagationMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10971 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfRadiationVectorCreate()
ArrayOfArrayOfRadiationVector ARTS::Var::ArrayOfArrayOfRadiationVectorCreate (Workspace & ws, const Group::ArrayOfArrayOfRadiationVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfRadiationVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfRadiationVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 10990 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfScatteringMetaDataCreate()
ArrayOfArrayOfScatteringMetaData ARTS::Var::ArrayOfArrayOfScatteringMetaDataCreate (Workspace & ws, const Group::ArrayOfArrayOfScatteringMetaData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfScatteringMetaData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfScatteringMetaData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11009 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfSingleScatteringDataCreate()
ArrayOfArrayOfSingleScatteringData ARTS::Var::ArrayOfArrayOfSingleScatteringDataCreate (Workspace & ws, const Group::ArrayOfArrayOfSingleScatteringData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfSingleScatteringData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfSingleScatteringData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11028 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfSpeciesTagCreate()
ArrayOfArrayOfSpeciesTag ARTS::Var::ArrayOfArrayOfSpeciesTagCreate (Workspace & ws, const Group::ArrayOfArrayOfSpeciesTag & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfSpeciesTag
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfSpeciesTag inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11047 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfStokesVectorCreate()
ArrayOfArrayOfStokesVector ARTS::Var::ArrayOfArrayOfStokesVectorCreate (Workspace & ws, const Group::ArrayOfArrayOfStokesVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfStokesVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfStokesVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11066 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfStringCreate()
ArrayOfArrayOfString ARTS::Var::ArrayOfArrayOfStringCreate (Workspace & ws, const Group::ArrayOfArrayOfString & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfString
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfString inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11085 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfTensor3Create()
ArrayOfArrayOfTensor3 ARTS::Var::ArrayOfArrayOfTensor3Create (Workspace & ws, const Group::ArrayOfArrayOfTensor3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfTensor3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfTensor3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11104 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfTensor6Create()
ArrayOfArrayOfTensor6 ARTS::Var::ArrayOfArrayOfTensor6Create (Workspace & ws, const Group::ArrayOfArrayOfTensor6 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfTensor6
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfTensor6 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11123 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfTimeCreate()
ArrayOfArrayOfTime ARTS::Var::ArrayOfArrayOfTimeCreate (Workspace & ws, const Group::ArrayOfArrayOfTime & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfTime
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfTime inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11142 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfTransmissionMatrixCreate()
ArrayOfArrayOfTransmissionMatrix ARTS::Var::ArrayOfArrayOfTransmissionMatrixCreate (Workspace & ws, const Group::ArrayOfArrayOfTransmissionMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfTransmissionMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfTransmissionMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11161 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfArrayOfVectorCreate()
ArrayOfArrayOfVector ARTS::Var::ArrayOfArrayOfVectorCreate (Workspace & ws, const Group::ArrayOfArrayOfVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfArrayOfVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfArrayOfVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11180 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfCIARecordCreate()
ArrayOfCIARecord ARTS::Var::ArrayOfCIARecordCreate (Workspace & ws, const Group::ArrayOfCIARecord & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfCIARecord
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfCIARecord inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11199 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfGriddedField1Create()
ArrayOfGriddedField1 ARTS::Var::ArrayOfGriddedField1Create (Workspace & ws, const Group::ArrayOfGriddedField1 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfGriddedField1
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfGriddedField1 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11218 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfGriddedField2Create()
ArrayOfGriddedField2 ARTS::Var::ArrayOfGriddedField2Create (Workspace & ws, const Group::ArrayOfGriddedField2 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfGriddedField2
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfGriddedField2 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11237 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfGriddedField3Create()
ArrayOfGriddedField3 ARTS::Var::ArrayOfGriddedField3Create (Workspace & ws, const Group::ArrayOfGriddedField3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfGriddedField3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfGriddedField3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11256 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfGriddedField4Create()
ArrayOfGriddedField4 ARTS::Var::ArrayOfGriddedField4Create (Workspace & ws, const Group::ArrayOfGriddedField4 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfGriddedField4
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfGriddedField4 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11275 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfIndexCreate()
ArrayOfIndex ARTS::Var::ArrayOfIndexCreate (Workspace & ws, const Group::ArrayOfIndex & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfIndex
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfIndex inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11294 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfJacobianTargetCreate()
ArrayOfJacobianTarget ARTS::Var::ArrayOfJacobianTargetCreate (Workspace & ws, const Group::ArrayOfJacobianTarget & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfJacobianTarget
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfJacobianTarget inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11313 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfMatrixCreate()
ArrayOfMatrix ARTS::Var::ArrayOfMatrixCreate (Workspace & ws, const Group::ArrayOfMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11332 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfPpathCreate()
ArrayOfPpath ARTS::Var::ArrayOfPpathCreate (Workspace & ws, const Group::ArrayOfPpath & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfPpath
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfPpath inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11351 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfPropagationMatrixCreate()
ArrayOfPropagationMatrix ARTS::Var::ArrayOfPropagationMatrixCreate (Workspace & ws, const Group::ArrayOfPropagationMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfPropagationMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfPropagationMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11370 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfQuantumIdentifierCreate()
ArrayOfQuantumIdentifier ARTS::Var::ArrayOfQuantumIdentifierCreate (Workspace & ws, const Group::ArrayOfQuantumIdentifier & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfQuantumIdentifier
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfQuantumIdentifier inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11389 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfRadiationVectorCreate()
ArrayOfRadiationVector ARTS::Var::ArrayOfRadiationVectorCreate (Workspace & ws, const Group::ArrayOfRadiationVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfRadiationVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfRadiationVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11408 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfRetrievalQuantityCreate()
ArrayOfRetrievalQuantity ARTS::Var::ArrayOfRetrievalQuantityCreate (Workspace & ws, const Group::ArrayOfRetrievalQuantity & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfRetrievalQuantity
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfRetrievalQuantity inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11427 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfScatteringMetaDataCreate()
ArrayOfScatteringMetaData ARTS::Var::ArrayOfScatteringMetaDataCreate (Workspace & ws, const Group::ArrayOfScatteringMetaData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfScatteringMetaData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfScatteringMetaData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11446 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfSingleScatteringDataCreate()
ArrayOfSingleScatteringData ARTS::Var::ArrayOfSingleScatteringDataCreate (Workspace & ws, const Group::ArrayOfSingleScatteringData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfSingleScatteringData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfSingleScatteringData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11465 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfSparseCreate()
ArrayOfSparse ARTS::Var::ArrayOfSparseCreate (Workspace & ws, const Group::ArrayOfSparse & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfSparse
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfSparse inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11484 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfSpeciesTagCreate()
ArrayOfSpeciesTag ARTS::Var::ArrayOfSpeciesTagCreate (Workspace & ws, const Group::ArrayOfSpeciesTag & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfSpeciesTag
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfSpeciesTag inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11503 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfStokesVectorCreate()
ArrayOfStokesVector ARTS::Var::ArrayOfStokesVectorCreate (Workspace & ws, const Group::ArrayOfStokesVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfStokesVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfStokesVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11522 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfStringCreate()
ArrayOfString ARTS::Var::ArrayOfStringCreate (Workspace & ws, const Group::ArrayOfString & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfString
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfString inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11541 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTelsemAtlasCreate()
ArrayOfTelsemAtlas ARTS::Var::ArrayOfTelsemAtlasCreate (Workspace & ws, const Group::ArrayOfTelsemAtlas & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTelsemAtlas
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTelsemAtlas inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11560 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTensor3Create()
ArrayOfTensor3 ARTS::Var::ArrayOfTensor3Create (Workspace & ws, const Group::ArrayOfTensor3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTensor3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTensor3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11579 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTensor4Create()
ArrayOfTensor4 ARTS::Var::ArrayOfTensor4Create (Workspace & ws, const Group::ArrayOfTensor4 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTensor4
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTensor4 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11598 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTensor5Create()
ArrayOfTensor5 ARTS::Var::ArrayOfTensor5Create (Workspace & ws, const Group::ArrayOfTensor5 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTensor5
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTensor5 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11617 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTensor6Create()
ArrayOfTensor6 ARTS::Var::ArrayOfTensor6Create (Workspace & ws, const Group::ArrayOfTensor6 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTensor6
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTensor6 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11636 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTensor7Create()
ArrayOfTensor7 ARTS::Var::ArrayOfTensor7Create (Workspace & ws, const Group::ArrayOfTensor7 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTensor7
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTensor7 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11655 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTimeCreate()
ArrayOfTime ARTS::Var::ArrayOfTimeCreate (Workspace & ws, const Group::ArrayOfTime & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTime
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTime inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11674 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfTransmissionMatrixCreate()
ArrayOfTransmissionMatrix ARTS::Var::ArrayOfTransmissionMatrixCreate (Workspace & ws, const Group::ArrayOfTransmissionMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfTransmissionMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfTransmissionMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11693 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfVectorCreate()
ArrayOfVector ARTS::Var::ArrayOfVectorCreate (Workspace & ws, const Group::ArrayOfVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11712 of file autoarts.h.
References Workspace::add_wsv_inplace().
ArrayOfXsecRecordCreate()
ArrayOfXsecRecord ARTS::Var::ArrayOfXsecRecordCreate (Workspace & ws, const Group::ArrayOfXsecRecord & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ArrayOfXsecRecord
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ArrayOfXsecRecord inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11731 of file autoarts.h.
References Workspace::add_wsv_inplace().
atm_fields_compact()
GriddedField4 ARTS::Var::atm_fields_compact (Workspace & ws) inline noexcept
A compact set of atmospheric fields on a common set of grids.
Data is supposed to contain basic atmsopheric fields for a RT calculation, i.e., temperature, altitude, and gas VMRs. It can furthermore contain fields describing scattering species like mass content, mass flux, number density of diverse scattering species.
VMR fields are unitless, scattering species fields are supposed to be in SI units (i.e. kg/m3 for mass contents, kg/m2/s for mass flux, 1/m3 for number densities).
The data are stored in a GriddedField4.
The first field in the matrix (i.e., first matrix column) has to be atmospheric pressure. Apart from this, the order of the fields is free. Field content (apart from pressure) is identified by their given field name tag. Furthermore, absorption species (e.g. VMR) fields and scattering species fields are related to abs_species and scat_species entries, respectively, by their field name tags. The tags must exhibit the following structure:
0) species identifier: Fields, supposed to be sorted into vmr_field, must be headed the tag 'abs_species'. Names of scattering species fields likewise must be headed by the 'scat_species' tag. Temperature and altitude fields do not hold any heading tag. 1) species name: The (core) name of the field: 'T' for temperature, 'z' for altitude, the absorption species name (e.g. 'H2O, 'O3', etc.) for absorption species, the scattering species name (e.g. 'IWC') for scattering species. For scattering species, this part is matched against the scattering species name part of the scat_species tags. 2) field type: This has to be given for scattering species only, indicating the type of the scattering species fields, i.e. 'mass_density', 'mass_flux', 'number_density', 'mean_mass'. Dashes ('-') serve as delimiter, separating the elements of each field name tag.
Usage: Used inside batch calculations, to hold successive atmospheric states from an ArrayOfGriddedField4.
Dimensions: GriddedField4: ArrayOfString field_names[N_fields] Vector p_grid[N_p] Vector lat_grid[N_lat] Vector lon_grid[N_lon] Tensor4 data[N_fields][N_p][N_lat][N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5360 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), ARTS::Method::atm_fields_compactAddConstant(), atm_fields_compactAddSpecies(), ARTS::Method::atm_fields_compactAddSpecies(), atm_fields_compactCleanup(), ARTS::Method::atm_fields_compactCleanup(), atm_fields_compactCreateFromField(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::atm_fields_compactFromMatrix(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), iyIndependentBeamApproximation(), and ARTS::Method::iyIndependentBeamApproximation().
atmfields_checked()
Index ARTS::Var::atmfields_checked (Workspace & ws) inline noexcept
OK-flag for atmospheric grids and (physical) fields.
The variable flags that clear-sky part of the atmosphere is defined in formally correct way. Example on problems captured include that the size of an atmospheric fields does not match the length of the atmospheric grids, and physically incorrect data such as negative temperatures.
Note that z_field is not covered by this variable, it is instead treated to be part of the geometrical considerations where the ok-flag is denoted as atmgeom_checked. The cloudbox is covered by cloudbox_checked*.
Shall be set by atmfields_checkedCalc. See that WSMs for treated WSVs. Only the value 1 is taken as OK.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5381 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), check_disort_input(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), ARTS::Method::iyCalc(), iyCalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), p_gridDensify(), ARTS::Method::p_gridDensify(), ARTS::Method::p_gridRefine(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), ARTS::Method::yRadar(), and ARTS::Method::z_fieldFromHSE().
atmgeom_checked()
Index ARTS::Var::atmgeom_checked (Workspace & ws) inline noexcept
OK-flag for the geometry of the model atmosphere.
The variable flags that reference ellipsoid, the surfae and z_field contain formally correct values. Includes for example, that z_field holds strictly increasing values at each geographical position.
See also atmfields_checked.
Shall be set by atmgeom_checkedCalc. Only the value 1 is taken as OK.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5397 of file autoarts.h.
Referenced by AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), check_disort_input(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), ARTS::Method::iyCalc(), iyCalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), p_gridDensify(), ARTS::Method::p_gridDensify(), ARTS::Method::p_gridRefine(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
atmosphere_dim()
Index ARTS::Var::atmosphere_dim (Workspace & ws) inline noexcept
The atmospheric dimensionality (1-3).
This variable defines the complexity of the atmospheric structure. The dimensionality is given by an integer between 1 and 3, where 1 means 1D etc. This is the master variable for the atmospheric dimensionality, variables which size changes with the dimensionality are checked to match this variable.
Methods adapt automatically to this variable. That is, it should not be needed to change any methods if the dimensionality is changed. However, not all methods are working for higher dimensions.
Usage: Set by the user.
Unit: Integer value.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5418 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupBatch(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), adapt_stepwise_partial_derivatives(), adjust_los(), AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), atm_fields_compactFromMatrix(), ARTS::Method::atm_fields_compactFromMatrix(), AtmFieldPerturb(), ARTS::Method::AtmFieldPerturb(), AtmFieldPerturbAtmGrids(), ARTS::Method::AtmFieldPerturbAtmGrids(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), AtmosphereSet1D(), ARTS::Method::AtmosphereSet1D(), AtmosphereSet2D(), ARTS::Method::AtmosphereSet2D(), AtmosphereSet3D(), ARTS::Method::AtmosphereSet3D(), batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), check_disort_input(), chk_latlon_true(), chk_pnd_data(), chk_pnd_raw_data(), chk_rte_los(), chk_rte_pos(), cloud_atm_vars_by_gp(), cloud_fieldsCalc(), cloud_ppath_update1D_planeparallel(), cloud_RT_no_background(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldCrop(), ARTS::Method::cloudbox_fieldCrop(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), diy_from_path_to_rgrids(), diy_from_pos_to_rgrids(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), doit_za_interpSet(), ARTS::Method::doit_za_interpSet(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), dotprod_with_los(), find_cloudlimits(), get_gp_atmgrids_to_rq(), get_gp_atmsurf_to_rq(), get_gp_rq_to_atmgrids(), get_iy_of_background(), get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_stepwise_f_partials(), get_stepwise_frequency_grid(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexNumberOfAtmosphericPoints(), interp_atmfield_by_gp(), interp_atmfield_by_itw(), interp_atmfield_gp2itw(), interp_atmsurface_by_gp(), interp_atmsurface_by_itw(), interp_atmsurface_gp2itw(), interp_cloudfield_gp2itw(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), EnergyLevelMap::InterpToGridPos(), is_gp_inside_cloudbox(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), jacobianAddAbsSpecies(), ARTS::Method::jacobianAddAbsSpecies(), jacobianAddMagField(), ARTS::Method::jacobianAddMagField(), jacobianAddNLTE(), ARTS::Method::jacobianAddNLTE(), jacobianAddNLTEs(), ARTS::Method::jacobianAddNLTEs(), jacobianAddScatSpecies(), ARTS::Method::jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddSurfaceQuantity(), jacobianAddTemperature(), ARTS::Method::jacobianAddTemperature(), jacobianAddWind(), ARTS::Method::jacobianAddWind(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), mirror_los(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), pha_matCalc(), ARTS::Method::pha_matCalc(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pnd_fieldExpand1D(), ARTS::Method::pnd_fieldExpand1D(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), pos2refell_r(), pos2true_latlon(), ppath_calc(), ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_init_structure(), ppath_start_stepping(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), regrid_atmfield_by_gp(), regrid_atmfield_by_gp_oem(), regrid_atmsurf_by_gp(), regrid_atmsurf_by_gp_oem(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_losSet(), ARTS::Method::rte_losSet(), rte_pos2gridpos(), rte_pos_losMoveToStartOfPpath(), ARTS::Method::rte_pos_losMoveToStartOfPpath(), rte_posSet(), ARTS::Method::rte_posSet(), rtmethods_jacobian_finalisation(), ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsPndAndScatAdd(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensorOff(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), specular_losCalc(), ARTS::Method::specular_losCalc(), specular_losCalcNoTopography(), ARTS::Method::specular_losCalcNoTopography(), surf_radius_at_l(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surface_props_check(), surface_props_interp(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), ARTS::Method::surface_typeInterpTypeMask(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), telsemSurfaceTypeLandSea(), ARTS::Method::telsemSurfaceTypeLandSea(), VectorZtanToZa1D(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), WriteMolTau(), ARTS::Method::WriteMolTau(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), ARTS::Method::yRadar(), ySimpleSpectrometer(), and ARTS::Method::z_fieldFromHSE().
avk()
Matrix ARTS::Var::avk (Workspace & ws) inline noexcept
Averaging kernel matrix.
This matrix is the partial derivative of the retrieved state vector with respect to the measurement vector (y).
Usage: Used and set by inversion methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5430 of file autoarts.h.
Referenced by ARTS::Method::avkCalc(), and ARTS::Method::covmat_ssCalc().
backend_channel_response()
ArrayOfGriddedField1 ARTS::Var::backend_channel_response (Workspace & ws) inline noexcept
The response of each backend channel.
The response is given as an ArrayOfGriddedField1. The grid consists of relative frequencies. These relative frequencies are added to f_backend* to obtain the absolute frequency for each response value. The actual data are the response at each frequency grid point.
There are here two options. If the array has length 1, the same response is applied for all channels. Accordingly, this assumes that all channels have the same response function. The second option is to specify the response for each channel seperately. This signifies that the backend_channel_response array has either 1 or n elements, where n is the length of f_backend
Usage: Set by the user.
Size: Array[N_ch] GriddedField1 [N_f] [N_f]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5456 of file autoarts.h.
Referenced by ARTS::Method::backend_channel_responseFlat(), ARTS::Method::backend_channel_responseGaussian(), f_gridFromSensorAMSU(), f_gridFromSensorHIRS(), ARTS::Method::f_gridFromSensorHIRS(), find_effective_channel_boundaries(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), and ARTS::Method::sensor_responseBackendFrequencySwitching().
backend_channel_response_multi()
ArrayOfArrayOfGriddedField1 ARTS::Var::backend_channel_response_multi (Workspace & ws) inline noexcept
As backend_channel_response but describes an instrument with muliple mixer/receiver chains.
See f_backend_multi for when to use this variable and size constraints.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5469 of file autoarts.h.
Referenced by ARTS::Method::f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), ARTS::Method::f_gridFromSensorAMSUgeneric(), sensor_responseGenericAMSU(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), and sensor_responseSimpleAMSU().
band_identifiers()
ArrayOfQuantumIdentifier ARTS::Var::band_identifiers (Workspace & ws) inline noexcept
An array of identifiers for bands.
Used by line mixing calculations to identify which bands to match to the line database.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5479 of file autoarts.h.
batch_atm_fields_compact()
ArrayOfGriddedField4 ARTS::Var::batch_atm_fields_compact (Workspace & ws) inline noexcept
An array of compact atmospheric states.
This is used to hold a set of atm_fields_compact for batch calculations. For further information see atm_fields_compact.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5489 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupSetupBatch(), batch_atm_fields_compactAddConstant(), ARTS::Method::batch_atm_fields_compactAddConstant(), batch_atm_fields_compactAddSpecies(), ARTS::Method::batch_atm_fields_compactAddSpecies(), batch_atm_fields_compactCleanup(), ARTS::Method::batch_atm_fields_compactCleanup(), batch_atm_fields_compactFromArrayOfMatrix(), and ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix().
batch_cloudbox_limits()
ArrayOfArrayOfIndex ARTS::Var::batch_cloudbox_limits (Workspace & ws) inline noexcept
An array of cloudbox_limits.
This is used to hold a set of cloudbox_limits for batch calculations.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5499 of file autoarts.h.
batch_pnd_fields()
ArrayOfTensor4 ARTS::Var::batch_pnd_fields (Workspace & ws) inline noexcept
An array of compact pnd states.
This is used to hold a set of 1D pnd_field for batch calculations.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5509 of file autoarts.h.
channel2fgrid_indexes()
ArrayOfArrayOfIndex ARTS::Var::channel2fgrid_indexes (Workspace & ws) inline noexcept
Definition of backend frequency response, link to f_grid.
The WSV is used to describe the frequency response of backend channels together with the accompanying WSV channel2fgrid_weights.
This WSV links each channel to the elements of f_grid. In short it lists what elements of f_grid that are relevant for each channel.
More precisely, the first dimension gives the number of output channels. Each ArrayOfIndex gives the index of the values in f_grid associated with the channel of concern. For a pure double-sideband receiver, where there is one monochromatic frequency per passband, this argument could look like: [[0,5],[1,4],[2,3],[7,8],[7,8]].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5528 of file autoarts.h.
Referenced by f_gridMetMM(), ARTS::Method::f_gridMetMM(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixerBackendPrecalcWeights(), and ARTS::Method::sensor_responseMixerBackendPrecalcWeights().
channel2fgrid_weights()
ArrayOfVector ARTS::Var::channel2fgrid_weights (Workspace & ws) inline noexcept
Definition of backend frequency response, weighting of f_grid.
The WSV is used to describe the frequency response of backend channels together with the accompanying WSV channel2fgrid_indexes.
This WSV shall have excatly the same sizes as channel2fgrid_indexes. Each element gives the weight to be assigned to the associated monochromatic frequency.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5542 of file autoarts.h.
Referenced by f_gridMetMM(), ARTS::Method::f_gridMetMM(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixerBackendPrecalcWeights(), and ARTS::Method::sensor_responseMixerBackendPrecalcWeights().
CIARecordCreate()
CIARecord ARTS::Var::CIARecordCreate (Workspace & ws, const Group::CIARecord & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an CIARecord
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] CIARecord inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11750 of file autoarts.h.
References Workspace::add_wsv_inplace().
cloudbox_checked()
Index ARTS::Var::cloudbox_checked (Workspace & ws) inline noexcept
OK-flag for variables associated with the cloudbox.
This variable flags that cloudbox variables are defined in a formally and practically correct way. For example, that there is sufficient space between the cloudbox and edges of the model atmosphere (for 2D and 3D). Pure clear-sky variables are covered by atmfields_checked* (and atmgeom_checked).
Relevant checks are performed by *cloudbox_checkedCalc. Only the value 1 is taken as OK.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5558 of file autoarts.h.
Referenced by AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), check_disort_input(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), ARTS::Method::iyCalc(), iyCalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), p_gridDensify(), ARTS::Method::p_gridDensify(), ARTS::Method::p_gridRefine(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
cloudbox_field()
Tensor7 ARTS::Var::cloudbox_field (Workspace & ws) inline noexcept
The spectral radiance field inside the cloudbx.
This variable is used to store the radiance field inside the cloud box, probably determined by a scattering solver method.
That is, this variable matches spectral_radiance_field but holds a field that is restricted to the cloud box.
Unit: W / (m^2 Hz sr) for each Stokes component.
Size: [f_grid, p_grid, lat_grid, lon_grid, za_grid, aa_grid, stokes_dim ]
Note: For 1D, the size of the latitude, longitude and azimuth dimension (N_aa) are all 1.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5584 of file autoarts.h.
Referenced by cloudbox_fieldCrop(), ARTS::Method::cloudbox_fieldCrop(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), DOBatchCalc(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), get_stepwise_scattersky_source(), init_ifield(), iyHybrid(), ARTS::Method::iyHybrid(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), and ARTS::Method::spectral_radiance_fieldExpandCloudboxField().
cloudbox_field_mono()
Tensor6 ARTS::Var::cloudbox_field_mono (Workspace & ws) inline noexcept
Monochromatic radiation field inside the cloudbox.
This variable is used to store the monochromatic radiation field inside the cloudbox which is found by an iterative solution (DOIT). Refer to AUG for further information.
Usage: Method output.
Unit: W / (m^2 Hz sr) for each Stokes component.
Size: [(cloudbox_limits[1] - cloudbox_limits[0]) +1, (cloudbox_limits[3] - cloudbox_limits[2]) +1, (cloudbox_limits[5] - cloudbox_limits[4]) +1, N_za, N_aa, N_i ]
Note: For 1D, the size of the azimuth angle dimension (N_aa) is always 1.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5607 of file autoarts.h.
Referenced by cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_no_background(), cloud_RT_surface(), cloudbox_field_monoIterate(), ARTS::Method::cloudbox_field_monoIterate(), cloudbox_field_monoOptimizeReverse(), ARTS::Method::cloudbox_field_monoOptimizeReverse(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_field_ngAcceleration(), cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), doit_conv_flagAbs(), ARTS::Method::doit_conv_flagAbs(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_conv_test_agenda(), doit_conv_test_agendaExecute(), ARTS::Agenda::Execute::doit_mono_agenda(), doit_mono_agendaExecute(), ARTS::Agenda::Execute::doit_rte_agenda(), doit_rte_agendaExecute(), ARTS::Agenda::Execute::doit_scat_field_agenda(), doit_scat_field_agendaExecute(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), doit_za_grid_optCalc(), ARTS::Method::doit_za_grid_optCalc(), DoitWriteIterationFields(), ARTS::Method::DoitWriteIterationFields(), interp_cloud_coeff1D(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), and za_gridOpt().
cloudbox_field_mono_old()
Tensor6 ARTS::Var::cloudbox_field_mono_old (Workspace & ws) inline noexcept
As cloudbox_field_mono but from previous iteration.
This variable is used to store the intensity field inside the cloudbox while performing the iteration. One has to store the intensity field of the previous iteration to be able to do the convergence test after each iteration. Refer to AUG for more information.
Usage: Method output.
Unit: W / (m^2 Hz sr) for each Stokes component.
Size: [(cloudbox_limits[1] - cloudbox_limits[0]) +1, (cloudbox_limits[3] - cloudbox_limits[2]) +1, (cloudbox_limits[5] - cloudbox_limits[4]) +1, N_za, N_aa, N_i ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5629 of file autoarts.h.
Referenced by doit_conv_flagAbs(), ARTS::Method::doit_conv_flagAbs(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_conv_test_agenda(), and doit_conv_test_agendaExecute().
cloudbox_limits()
ArrayOfIndex ARTS::Var::cloudbox_limits (Workspace & ws) inline noexcept
The limits of the cloud box.
This variable defines the extension of the cloud box. The cloud box is defined to be rectangular in the used coordinate system, with limits exactly at points of the involved grids. This means, for example, that the vertical limits of the cloud box are two pressure levels. For 2D, the angular extension of the cloud box is between two points of the latitude grid, and likewise for 3D but then also with a longitude extension between two grid points. The latitude and longitude limits for the cloud box cannot be placed at the end points of the corresponding grid as it must be possible to calculate the incoming intensity field.
The variable cloudbox_limits is an array of index value with length twice atmosphere_dim. For each dimension there is a lower limit and an upper limit. The order of the dimensions is as usual pressure, latitude and longitude. The upper limit index must be greater then the lower limit index. For example, cloudbox_limits* = [0 5 4 11 4 11] means that cloud box extends between pressure levels 0 and 5, and latitude and longitude points 4 and 11.
If cloudbox_on = 0, the content of this variable is neglected, but it must be initiated to some dummy values.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user, either directly or using a method checking the extension of scattering particles.
Unit: Index values.
Size: [ 2 * atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5670 of file autoarts.h.
Referenced by check_disort_input(), chk_pnd_field_raw_only_in_cloudbox(), cloud_atm_vars_by_gp(), cloud_fieldsCalc(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_no_background(), cloud_RT_surface(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoOptimizeReverse(), ARTS::Method::cloudbox_field_monoOptimizeReverse(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldCrop(), ARTS::Method::cloudbox_fieldCrop(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxOff(), ARTS::Method::cloudboxOff(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), cloudy_rt_vars_at_gp(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), get_paroptprop(), get_parZ(), get_pfct(), get_ppath_cloudvars(), get_ppath_transmat(), init_ifield(), interp_cloud_coeff1D(), interp_cloudfield_gp2itw(), is_gp_inside_cloudbox(), is_inside_cloudbox(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pnd_fieldExpand1D(), ARTS::Method::pnd_fieldExpand1D(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), ppath_calc(), ppath_start_stepping(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), run_cdisort(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ybatchMetProfiles(), and ybatchMetProfilesClear().
cloudbox_on()
Index ARTS::Var::cloudbox_on (Workspace & ws) inline noexcept
Flag to activate the cloud box.
Scattering calculations are confined to a part of the atmosphere denoted as the cloud box. The extension of the cloud box is given by cloudbox_limits*. This variable tells methods if a cloud box is activated or not.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: Boolean.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5690 of file autoarts.h.
Referenced by check_disort_input(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_fieldCrop(), ARTS::Method::cloudbox_fieldCrop(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudboxOff(), ARTS::Method::cloudboxOff(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), get_iy(), get_iy_of_background(), get_pointers_for_scat_species(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldExpand1D(), ARTS::Method::pnd_fieldExpand1D(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_stepping(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
collision_coefficients()
ArrayOfArrayOfGriddedField1 ARTS::Var::collision_coefficients (Workspace & ws) inline noexcept
An array of coefficients for effective collisions
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5697 of file autoarts.h.
Referenced by collision_coefficientsFromSplitFiles(), ARTS::Method::collision_coefficientsFromSplitFiles(), nlte_fieldForSingleSpeciesNonOverlappingLines(), and ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines().
collision_line_identifiers()
ArrayOfQuantumIdentifier ARTS::Var::collision_line_identifiers (Workspace & ws) inline noexcept
An array of quantum identifiers for finding collisional rates in collision_coefficients
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5705 of file autoarts.h.
Referenced by check_collision_line_identifiers(), collision_coefficientsFromSplitFiles(), ARTS::Method::collision_coefficientsFromSplitFiles(), nlte_collision_factorsCalcFromCoeffs(), nlte_fieldForSingleSpeciesNonOverlappingLines(), and ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines().
complex_refr_index()
GriddedField3 ARTS::Var::complex_refr_index (Workspace & ws) inline noexcept
Complex refractive index (n) data.
The variable works as a lookup-table of complex refractive index. The matter type (water, ice ...) is unspecified, it is up to the user to fill the variable with data for the expected matter. This variable type can be used to describe n of both the surface and atmospheric particles. For the surface, a dedicated variable exists: surface_complex_refr_index*.
The column dimension has always size 2, where the first and second column holds the real and imaginary part of n, respectively. The row dimension matches temperature, and the page dimension is frequency. Both the temperature and frequency dimensions grids are allowed to have length 1, which is interpreted as n being constant in that dimension.
When mapping these data to the required frequencies and temperatures a bi-linear interpolation is applied.
Unit: -
Dimensions: Vector f_grid[N_f] Vector T_grid[N_T] ArrayOfString Complex[2] Tensor3 data[N_f][N_T][2]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5737 of file autoarts.h.
Referenced by complex_refr_indexConstant(), ARTS::Method::complex_refr_indexConstant(), complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), complex_refr_indexWaterLiebe93(), ARTS::Method::complex_refr_indexWaterLiebe93(), and ARTS::Method::scat_data_singleTmatrix().
CovarianceMatrixCreate()
CovarianceMatrix ARTS::Var::CovarianceMatrixCreate (Workspace & ws, const Group::CovarianceMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an CovarianceMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] CovarianceMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11769 of file autoarts.h.
References Workspace::add_wsv_inplace().
covmat_block()
Sparse ARTS::Var::covmat_block (Workspace & ws) inline noexcept
Holds matrices used to set blocks in covmat_sx and covmat_se.
The matrix contained in this block will be added to the blocks in in covmat_sx and covmat_se by the corresponding WSMs. Its dimensions must agree with gridpoints of the correlated retrieval quantities. Usage: Used by the retrievalAdd functions.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5749 of file autoarts.h.
Referenced by check_and_add_block(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), retrievalDefInit(), and ARTS::Method::retrievalDefInit().
covmat_inv_block()
Sparse ARTS::Var::covmat_inv_block (Workspace & ws) inline noexcept
Holds matrices used to set the inverse blocks in covmat_sx and covmat_se.
The matrix contained in this block will be used as the inverse of the matrix contained in covmat_block.
Usage: Used by the retrievalAdd functions.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5761 of file autoarts.h.
Referenced by check_and_add_block(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), retrievalDefInit(), and ARTS::Method::retrievalDefInit().
covmat_se()
CovarianceMatrix ARTS::Var::covmat_se (Workspace & ws) inline noexcept
Covariance matrix for observation uncertainties.
This matrix (Se) describes the uncertainty of the measurement vector (y), and can be writtenn as Se = Seps + Kb * Sb * Kb', where Seps describes direct measurement errors (such as thermal noise), Kb is Jacobian for forward model parameters, and Sb describes the uncertainty of the forwatrd model parameters.
Usage: Used by inversion methods.
Dimensions: [ y, y ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5780 of file autoarts.h.
Referenced by covmat_seAddBlock(), ARTS::Method::covmat_seAddBlock(), covmat_seAddInverseBlock(), ARTS::Method::covmat_seAddInverseBlock(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_soCalc(), ARTS::Method::OEM(), retrievalDefInit(), and ARTS::Method::retrievalDefInit().
covmat_so()
Matrix ARTS::Var::covmat_so (Workspace & ws) inline noexcept
Covariance matrix describing the retrieval error due to uncertainties of the observation system.
That is: So = G * Se * G', where G is the gain matrix (dxdy).
Usage: Set by the covmat_soCalc workspace method to characterize the error. of a successful OEM calculation.
Dimensions: [x,x]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5796 of file autoarts.h.
Referenced by ARTS::Method::covmat_soCalc(), retrievalErrorsExtract(), and ARTS::Method::retrievalErrorsExtract().
covmat_ss()
Matrix ARTS::Var::covmat_ss (Workspace & ws) inline noexcept
Covariance matrix describing the retrieval error due to smoothing.
That is: Ss = (A-I) * Sx * (A-I)', where A is the averaging kernel matrix (avk).
Usage: Set by the covmat_ssCalc workspace method to characterize the. errors of a successful OEM calculation. Dimensions: [x,x]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5810 of file autoarts.h.
Referenced by ARTS::Method::covmat_ssCalc(), retrievalErrorsExtract(), and ARTS::Method::retrievalErrorsExtract().
covmat_sx()
CovarianceMatrix ARTS::Var::covmat_sx (Workspace & ws) inline noexcept
Covariance matrix of a priori distribution
This covariance matrix describes the Gaussian a priori distribution for an OEM retrieval. It is represented using a symmetric block matrix. covmat_sx can be used in two ways: Either with a block for each retrieval quantity or with a single block containing the full covariance matrix.
Using a single block for each retrieval quantity has is advantageous for if the retrieval quantities are assumed to be independent. In this case, the covariance blocks can be added separately for each quantity and will allow optimizing matrix multiplications and inverses required for the OEM calculation.
The other case of using a single-block covariance matrix is supported for convenience as well.
Usage: Used by inversion methods.
Dimensions: [ x, x ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5836 of file autoarts.h.
Referenced by ARTS::Method::covmat_ssCalc(), covmat_sxAddBlock(), ARTS::Method::covmat_sxAddBlock(), covmat_sxAddInverseBlock(), ARTS::Method::covmat_sxAddInverseBlock(), covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::OEM(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameter(), retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), ARTS::Method::retrievalDefClose(), retrievalDefClose(), retrievalDefInit(), and ARTS::Method::retrievalDefInit().
dabs_coef_dx()
ArrayOfMatrix ARTS::Var::dabs_coef_dx (Workspace & ws) inline noexcept
The partial derivatives of the matrix of total scalar absorption coefficients.
Contains the derivative of the gas absorption summed over all species as a function of f_grid and abs_p, i.e., for a single atmospheric profile for some parameter.
This variable is not used explicitly in a standard calculation, where absorption comes from the lookup table abs_lookup. However, it is useful for testing the methods that actually calculate line-by-line absorption, which have this variable as output. These methods are called internally by the method abs_lookupCalc, which generates the lookup table.
Dimensions: [n_quantities][f_grid, abs_p]
Unit: 1/m/quantity
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5859 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), propmat_clearskyAddFromAbsCoefPerSpecies(), and propmat_clearskyAddXsecAgenda().
dabs_xsec_per_species_dx()
ArrayOfArrayOfMatrix ARTS::Var::dabs_xsec_per_species_dx (Workspace & ws) inline noexcept
Derivative of abs_xsec_per_species with respect to retrieval quantities.
The variable gives the derivative of abs_xsec_per_species with respect to some variables (but not all jacobian variables). Handled are only variables that are involved in xsec and cannot be calculated at transmission level
Usage: Output of abs_xsec_agenda.
Dimensions: [abs_species][n_quantities][f_grid, abs_p ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5877 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), and propmat_clearskyAddXsecAgenda().
diy_dx()
ArrayOfTensor3 ARTS::Var::diy_dx (Workspace & ws) inline noexcept
Derivative of iy with respect to retrieval quantities.
The variable gives the derivative if iy with respect to some variables (but not all jacobian variables). Handled are only variables affecting monochromatic pencil beam radiances where an (semi-) analytical expression can be applied (and that this calculation way has been selected when the jacobian was been set-up).
The values in diy_dx considers the retrieval unit selected (such as "nd"), but no transformations are applied.
Usage: Output of iy_main_agenda.
Dimensions: [n_quantities][ n_retrieval_points, f_grid, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5898 of file autoarts.h.
Referenced by diy_from_path_to_rgrids(), diy_from_pos_to_rgrids(), DoitGetIncoming(), DoitGetIncoming1DAtm(), from_dpath_to_dx(), get_iy(), get_iy_of_background(), get_standard_starting_diy_dx(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyb_calc_body(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), rtmethods_jacobian_finalisation(), rtmethods_unit_conversion(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), and yRadar().
dnlte_source_dx()
ArrayOfStokesVector ARTS::Var::dnlte_source_dx (Workspace & ws) inline noexcept
NLTE partial derivatives output is two parts: S*dB/dx+dS/dx*B.
Dimensions: [ quantities ] [nza, naa, nf, stokes_dim] or [0]
Unit: 1/m/jacobian_quantity
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5909 of file autoarts.h.
Referenced by nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), and zeeman_on_the_fly().
dobatch_calc_agenda()
Agenda ARTS::Var::dobatch_calc_agenda (Workspace & ws) inline noexcept
Agenda defining the calculations to perform for each batch case.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5916 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::dobatch_calc_agenda(), ARTS::Agenda::Define::dobatch_calc_agenda(), and DOBatchCalc().
dobatch_cloudbox_field()
ArrayOfTensor7 ARTS::Var::dobatch_cloudbox_field (Workspace & ws) inline noexcept
Batch of radiation fields.
Each element of dobatch_cloudbox_field corresponds to a radiation field. See further DOBatchCalc.
Usage: Most commonly produced by DOBatchCalc.
Unit: See cloudbox_field.
Dimensions: Number of array elements equals number of batch cases.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5932 of file autoarts.h.
Referenced by DOBatchCalc(), and ARTS::Method::DOBatchCalc().
dobatch_irradiance_field()
ArrayOfTensor4 ARTS::Var::dobatch_irradiance_field (Workspace & ws) inline noexcept
Batch of irradiance fields.
Each element of dobatch_irradiance_field corresponds to a irradiance field. See further DOBatchCalc.
Usage: Most commonly produced by DOBatchCalc.
Unit: See irradiance_field.
Dimensions: Number of array elements equals number of batch cases.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5948 of file autoarts.h.
Referenced by DOBatchCalc(), and ARTS::Method::DOBatchCalc().
dobatch_radiance_field()
ArrayOfTensor5 ARTS::Var::dobatch_radiance_field (Workspace & ws) inline noexcept
Batch of radiance fields.
Each element of dobatch_radiance_field corresponds to a radiance field. See further DOBatchCalc.
Usage: Most commonly produced by DOBatchCalc.
Unit: See radiance_field.
Dimensions: Number of array elements equals number of batch cases.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5964 of file autoarts.h.
Referenced by DOBatchCalc(), and ARTS::Method::DOBatchCalc().
dobatch_spectral_irradiance_field()
ArrayOfTensor5 ARTS::Var::dobatch_spectral_irradiance_field (Workspace & ws) inline noexcept
Batch of spectral irradiance fields.
Each element of dobatch_spectral_irradiance_field corresponds to a spectral irradiance field. See further DOBatchCalc.
Usage: Most commonly produced by DOBatchCalc.
Unit: See spectral_irradiance_field.
Dimensions: Number of array elements equals number of batch cases.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5981 of file autoarts.h.
Referenced by DOBatchCalc(), and ARTS::Method::DOBatchCalc().
doit_conv_flag()
Index ARTS::Var::doit_conv_flag (Workspace & ws) inline noexcept
Flag for the convergence test.
This variable is initialized with 0 inside the method cloudbox_field_monoIterate*. If after an iteration the convergence test is fulfilled, 1 is assigned which means that the iteration is completed.
Usage: Method output.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 5995 of file autoarts.h.
Referenced by doit_conv_flagAbs(), ARTS::Method::doit_conv_flagAbs(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_conv_test_agenda(), and doit_conv_test_agendaExecute().
doit_conv_test_agenda()
Agenda ARTS::Var::doit_conv_test_agenda (Workspace & ws) inline noexcept
Agenda executing the DOIT convergence test.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6002 of file autoarts.h.
Referenced by cloudbox_field_monoIterate(), ARTS::Agenda::Execute::doit_conv_test_agenda(), and ARTS::Agenda::Define::doit_conv_test_agenda().
doit_is_initialized()
Index ARTS::Var::doit_is_initialized (Workspace & ws) inline noexcept
Flag to determine if DoitInit was called.
This flag is checked by DoitCalc to make sure that DoitInit* was called before.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6012 of file autoarts.h.
Referenced by cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), and ARTS::Method::DoitInit().
doit_iteration_counter()
Index ARTS::Var::doit_iteration_counter (Workspace & ws) inline noexcept
Counter for number of iterations.
This variable holds the number of iterations while solving the VRTE using the DOIT method.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6022 of file autoarts.h.
Referenced by doit_conv_flagAbs(), ARTS::Method::doit_conv_flagAbs(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_conv_test_agenda(), doit_conv_test_agendaExecute(), DoitWriteIterationFields(), and ARTS::Method::DoitWriteIterationFields().
doit_mono_agenda()
Agenda ARTS::Var::doit_mono_agenda (Workspace & ws) inline noexcept
Agenda performing monochromatic DOIT calculation.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6029 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::doit_mono_agenda(), ARTS::Agenda::Define::doit_mono_agenda(), ARTS::Method::DoitCalc(), and DoitCalc().
doit_rte_agenda()
Agenda ARTS::Var::doit_rte_agenda (Workspace & ws) inline noexcept
Agenda performing the DOIT cloudbox radiative transfer update.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6036 of file autoarts.h.
Referenced by cloudbox_field_monoIterate(), ARTS::Agenda::Execute::doit_rte_agenda(), and ARTS::Agenda::Define::doit_rte_agenda().
doit_scat_field()
Tensor6 ARTS::Var::doit_scat_field (Workspace & ws) inline noexcept
Scattered field inside the cloudbox.
This variable holds the value of the scattering integral for all points inside the cloudbox. For more information refer to AUG.
Usage: Input to cloudbox_fieldUpdate....
Unit: W / (m^2 Hz sr) for each Stokes component.
Size: [(cloudbox_limits[1] - cloudbox_limits[0]) +1, (cloudbox_limits[3] - cloudbox_limits[2]) +1, (cloudbox_limits[5] - cloudbox_limits[4]) +1, N_za, N_aa, N_i ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6055 of file autoarts.h.
Referenced by cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), ARTS::Agenda::Execute::doit_rte_agenda(), doit_rte_agendaExecute(), ARTS::Agenda::Execute::doit_scat_field_agenda(), doit_scat_field_agendaExecute(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), DoitInit(), ARTS::Method::DoitInit(), and interp_cloud_coeff1D().
doit_scat_field_agenda()
Agenda ARTS::Var::doit_scat_field_agenda (Workspace & ws) inline noexcept
Agenda calculating the scattering integral field in DOIT.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6062 of file autoarts.h.
Referenced by cloudbox_field_monoIterate(), ARTS::Agenda::Execute::doit_scat_field_agenda(), and ARTS::Agenda::Define::doit_scat_field_agenda().
doit_za_grid_opt()
Vector ARTS::Var::doit_za_grid_opt (Workspace & ws) inline noexcept
Optimized zenith angle grid.
Output of the method doit_za_grid_optCalc.
Usage: Output of doit_za_grid_optCalc
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6075 of file autoarts.h.
Referenced by doit_za_grid_optCalc(), and ARTS::Method::doit_za_grid_optCalc().
doit_za_grid_size()
Index ARTS::Var::doit_za_grid_size (Workspace & ws) inline noexcept
Number of equidistant grid points of the zenith angle grid.
Grid points are defined from 0 to 180 deg, for the scattering integral calculation.
Usage: Output of DOAngularGridsSet.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6087 of file autoarts.h.
Referenced by DOAngularGridsSet(), ARTS::Method::DOAngularGridsSet(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), DoitInit(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), and ARTS::Method::pha_mat_sptFromMonoData().
doit_za_interp()
Index ARTS::Var::doit_za_interp (Workspace & ws) inline noexcept
Flag for interplation method in zenith angle dimension.
0 - linear interpolation 1 - cubic interpolation
Usage: Set by user in doit_za_interpSet.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6099 of file autoarts.h.
Referenced by ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_za_grid_optCalc(), ARTS::Method::doit_za_grid_optCalc(), doit_za_interpSet(), and ARTS::Method::doit_za_interpSet().
dpnd_data_dx()
Tensor3 ARTS::Var::dpnd_data_dx (Workspace & ws) inline noexcept
Partial derivates of pnd_data.
The variable gives the particle derivate of pnd_data with respect to the quantities set in dpnd_data_dx_names.
Dimensions: [ n_quantities, n_points, n_scattering_elements ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6111 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), pnd_fieldCalcFromParticleBulkProps(), pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), and ARTS::Method::pndFromPsdBasic().
dpnd_data_dx_names()
ArrayOfString ARTS::Var::dpnd_data_dx_names (Workspace & ws) inline noexcept
Selection of partial derivatives of pnd_data.
This variable tells an element in pnd_agenda_array for which quantities partial derivatives shall be calculated.
Dimensions: [ n_quantities ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6123 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), pnd_fieldCalcFromParticleBulkProps(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), ARTS::Method::psdModifiedGamma(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
dpnd_field_dx()
ArrayOfTensor4 ARTS::Var::dpnd_field_dx (Workspace & ws) inline noexcept
Partial derivatives of pnd_field.
The variable gives the particle derivative of pnd_field with respect to scattering species variables included in jacobian_quantities.
The length of this array shall match the size of jacobian_quantities. For retrieval quantities that are not scattering species, the matching Tensor4 is of no relevance and must be set to be empty.
Dimensions: [n_quantities][ n_scattering_elements, n_p, n_lat, n_lon ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6139 of file autoarts.h.
Referenced by cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudboxOff(), ARTS::Method::cloudboxOff(), DisortCalcClearsky(), get_ppath_cloudvars(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pnd_fieldZero(), and ARTS::Method::pnd_fieldZero().
dpropmat_clearsky_dx()
ArrayOfPropagationMatrix ARTS::Var::dpropmat_clearsky_dx (Workspace & ws) inline noexcept
Partial derivative of absorption coefficients.
This contains the partial derivative of absorption coefficients for one point in the atmosphere (one set of pressure, temperature, znmagnetic field, and VMR values) with respect to one of the input parameters.
Dimension: [ n_quantities ] [naa, nza, nf, f(stokes_dim)]
jacobian_quantities* should be used to set the input variable for partial derivation
Unit: 1/m/jacobian_quantity
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6157 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddFromAbsCoefPerSpecies(), propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), and zeeman_on_the_fly().
dpsd_data_dx()
Tensor3 ARTS::Var::dpsd_data_dx (Workspace & ws) inline noexcept
Partial derivates of psd_data.
The variable gives the particle derivate of psd_data with respect to the quantities set in dpnd_data_dx_names.
Dimensions: [ n_quantities, n_points, n_scattering_elements ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6169 of file autoarts.h.
Referenced by pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), ARTS::Method::pndFromPsdBasic(), psd_mgd_mass_and_something(), psd_mono_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), psdModifiedGamma(), ARTS::Method::psdModifiedGamma(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
dsrc_xsec_per_species_dx()
ArrayOfArrayOfMatrix ARTS::Var::dsrc_xsec_per_species_dx (Workspace & ws) inline noexcept
Derivative of src_xsec_per_species with respect to retrieval quantities.
The variable gives the derivative of src_xsec_per_species with respect to some variables (but not all jacobian variables). Handled are only variables that are involved in xsec and cannot be calculated at transmission level
Usage: Output of abs_xsec_agenda.
Dimensions: [abs_species][n_quantities][f_grid, abs_p ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6187 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), and propmat_clearskyAddXsecAgenda().
dsurface_emission_dx()
ArrayOfMatrix ARTS::Var::dsurface_emission_dx (Workspace & ws) inline noexcept
The derivative of surface_emission with respect to quantities listed in dsurface_names.
Usage: Used internally of radiative transfer methods
Dimensions: [dsurface_names][f_grid, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6199 of file autoarts.h.
Referenced by dsurface_check(), get_iy_of_background(), ARTS::Agenda::Execute::iy_surface_agenda(), iy_surface_agendaExecute(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), and ARTS::Method::SurfaceTessem().
dsurface_names()
ArrayOfString ARTS::Var::dsurface_names (Workspace & ws) inline noexcept
Name of surface retrieval quantities.
Usage: Used internally of radiative transfer methods
Dimensions: [retrieval quantity]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6210 of file autoarts.h.
Referenced by dsurface_check(), get_iy_of_background(), ARTS::Agenda::Execute::iy_surface_agenda(), iy_surface_agendaExecute(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), and ARTS::Method::SurfaceTessem().
dsurface_rmatrix_dx()
ArrayOfTensor4 ARTS::Var::dsurface_rmatrix_dx (Workspace & ws) inline noexcept
The derivative of surface_rmatrix with respect to quantities listed in dsurface_names.
Usage: Used internally of radiative transfer methods
Dimensions: [dsurface_names][surface_los, f_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6222 of file autoarts.h.
Referenced by dsurface_check(), get_iy_of_background(), ARTS::Agenda::Execute::iy_surface_agenda(), iy_surface_agendaExecute(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), and ARTS::Method::SurfaceTessem().
dxdy()
Matrix ARTS::Var::dxdy (Workspace & ws) inline noexcept
Contribution function (or gain) matrix.
This matrix is the partial derivative of the retrieved state vector with respect to the measurement vector (y).
Usage: Used and set by inversion methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6234 of file autoarts.h.
Referenced by ARTS::Method::avkCalc(), ARTS::Method::covmat_soCalc(), and ARTS::Method::OEM().
ecs_data()
MapOfErrorCorrectedSuddenData ARTS::Var::ecs_data (Workspace & ws) inline noexcept
Error corrected sudden data
Dimensions: [num IDs] [num Species]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6243 of file autoarts.h.
Referenced by Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), ecs_dataAddMakarov2020(), ARTS::Method::ecs_dataAddMakarov2020(), ecs_dataAddRodrigues1997(), ARTS::Method::ecs_dataAddRodrigues1997(), ecs_dataAddTran2011(), ARTS::Method::ecs_dataAddTran2011(), ecs_dataInit(), ARTS::Method::ecs_dataInit(), ecs_dataSetMeanAir(), ARTS::Method::ecs_dataSetMeanAir(), ecs_dataSetSpeciesData(), ARTS::Method::ecs_dataSetSpeciesData(), Absorption::LineMixing::ecs_eigenvalue_adaptation(), Absorption::LineMixing::ecs_eigenvalue_adaptation_test(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), and ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman().
EnergyLevelMapCreate()
EnergyLevelMap ARTS::Var::EnergyLevelMapCreate (Workspace & ws, const Group::EnergyLevelMap & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an EnergyLevelMap
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] EnergyLevelMap inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11788 of file autoarts.h.
References Workspace::add_wsv_inplace().
ext_mat()
PropagationMatrix ARTS::Var::ext_mat (Workspace & ws) inline noexcept
Total extinction matrix.
This variable contains the extinction coefficient matrix, which is used in the RT calculation in the cloudbox. It is the physical extinction matrix which includes particle extinction for all chosen scattering species and gaseous extinction for all chosen gaseous species.
See the ARTS user guide (AUG) for further information. Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Output of opt_prop_bulkCalc
Unit: m^2
Dimensions: [f_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6265 of file autoarts.h.
Referenced by cloud_ppath_update1D_planeparallel(), ext2trans(), ext_mat_case(), ext_matAddGas(), ARTS::Method::ext_matAddGas(), ext_matFromabs_vec(), get_ppath_transmat(), mcPathTraceGeneral(), mcPathTraceRadar(), opt_prop_1ScatElem(), opt_prop_Bulk(), opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_NScatElems(), opt_prop_ScatSpecBulk(), opt_prop_sum_propmat_clearsky(), and OptimizeDoitPressureGrid().
ext_mat_spt()
ArrayOfPropagationMatrix ARTS::Var::ext_mat_spt (Workspace & ws) inline noexcept
Extinction matrix for all individual scattering elements.
This variable contains the elements of the extinction matrix of all individual scattering elements for a given propagation direction. It is calculated input as well as the output of the agenda spt_calc_agenda.
Usage: Output of spt_calc_agenda
Unit: m^2
Dimensions: [number of scattering elements, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6282 of file autoarts.h.
Referenced by opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
f_backend()
Vector ARTS::Var::f_backend (Workspace & ws) inline noexcept
The frequency position of each backend (spectrometer) channel.
Usage: Set by the user.
Unit: Hz
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6293 of file autoarts.h.
Referenced by f_gridFromSensorAMSU(), f_gridFromSensorHIRS(), ARTS::Method::f_gridFromSensorHIRS(), f_gridMetMM(), ARTS::Method::f_gridMetMM(), find_effective_channel_boundaries(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), WMRFSelectChannels(), ARTS::Method::WMRFSelectChannels(), ARTS::Method::x2artsSensor(), x2artsSensor(), and ySimpleSpectrometer().
f_backend_multi()
ArrayOfVector ARTS::Var::f_backend_multi (Workspace & ws) inline noexcept
As f_backend but describes an instrument with muliple mixer/receiver chains.
This variable is needed when e.g. the receiver has several mixers or the the receiver measures several polarisation and the channels differ in position or response function.
The array has one element for each "receiver chain". The array length must match backend_channel_response_multi, and possibly also lo_multi.
Usage: Set by the user.
Unit: Hz
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6313 of file autoarts.h.
Referenced by ARTS::Method::f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), ARTS::Method::f_gridFromSensorAMSUgeneric(), sensor_responseGenericAMSU(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), and sensor_responseSimpleAMSU().
f_grid()
Vector ARTS::Var::f_grid (Workspace & ws) inline noexcept
The frequency grid for monochromatic pencil beam calculations.
Usage: Set by the user.
Unit: Hz
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6324 of file autoarts.h.
Referenced by abs_lines_per_speciesCompact(), ARTS::Method::abs_lines_per_speciesCompact(), abs_linesCompact(), ARTS::Method::abs_linesCompact(), abs_lookupAdapt(), ARTS::Method::abs_lookupAdapt(), ARTS::Method::abs_lookupCalc(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), antenna1d_matrix(), antenna2d_gridded_dlos(), antenna2d_interp_response(), antenna_responseVaryingGaussian(), apply_iy_unit(), apply_iy_unit2(), Linefunctions::apply_rosenkranz_quadratic_scaling(), Linefunctions::apply_VVH_scaling(), Linefunctions::apply_VVW_scaling(), bad_propmat(), BF86_CIA_N2(), cia_interpolation(), CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_250_CIAfun_n2(), CKD_mt_250_CIArot_n2(), CKD_mt_250_co2(), CKD_mt_250_foreign_h2o(), CKD_mt_250_o2_vis(), CKD_mt_250_self_h2o(), CKD_mt_320_foreign_h2o(), CKD_mt_320_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), cloud_RT_surface(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudy_rt_vars_at_gp(), lm_hitran_2017::compabs(), complex_n_ice_matzler06(), complex_n_interp(), complex_n_water_liebe93(), complex_refr_indexIceMatzler06(), complex_refr_indexWaterLiebe93(), lm_hitran_2017::compute(), CP98H2OAbsModel(), create_sparse_f_grid_internal(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_mono_agenda(), doit_mono_agendaExecute(), ARTS::Method::DoitCalc(), DoitCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), ELL07WaterDropletAbs(), emission_from_propmat_field(), XsecRecord::Extract(), CIARecord::Extract(), ARTS::Method::f_gridFromAbsorptionLines(), f_gridFromGasAbsLookup(), ARTS::Method::f_gridFromGasAbsLookup(), f_gridFromSensorAMSU(), ARTS::Method::f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), ARTS::Method::f_gridFromSensorAMSUgeneric(), f_gridFromSensorHIRS(), ARTS::Method::f_gridFromSensorHIRS(), f_gridMetMM(), ARTS::Method::f_gridMetMM(), FastemStandAlone(), ARTS::Method::FastemStandAlone(), field_of_propagation(), Linefunctions::find_cutoff_ranges(), get_disortsurf_props(), get_gasoptprop(), get_iy(), get_iy_of_background(), get_paroptprop(), get_ppath_f(), get_ppath_transmat(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), get_stepwise_f_partials(), get_stepwise_frequency_grid(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), init_ifield(), LineShape::ComputeData::interp_add_even(), LineShape::ComputeData::interp_add_triplequad(), ARTS::Agenda::Execute::iy_cloudbox_agenda(), iy_cloudbox_agendaExecute(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_space_agenda(), ARTS::Agenda::iy_space_agenda_cosmic_background(), iy_space_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Agenda::Execute::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), iy_transmitterMultiplePol(), ARTS::Method::iy_transmitterMultiplePol(), iy_transmitterSinglePol(), ARTS::Method::iy_transmitterSinglePol(), ARTS::Method::iyApplyUnit(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), jacobianAddFreqShift(), ARTS::Method::jacobianAddFreqShift(), jacobianAddFreqStretch(), ARTS::Method::jacobianAddFreqStretch(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), LineShape::limited_range(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), LineShape::linear_sparse_f_grid(), LineShape::linear_sparse_limited_range(), main(), MaTipping_H2O_foreign_continuum(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), mixer_matrix(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::OptimizeDoitPressureGrid(), Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), pndFromPsd(), ARTS::Method::pndFromPsd(), ARTS::Agenda::Execute::ppath_agenda(), ARTS::Agenda::ppath_agenda_plane_parallel(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Agenda::Execute::ppath_step_agenda(), ARTS::Agenda::ppath_step_agenda_geometric_path(), ppath_step_agendaExecute(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), propmat_clearskyZero(), ARTS::Method::propmat_clearskyZero(), PWR93O2AbsModel(), PWR98H2OAbsModel(), LineShape::quad_sparse_limited_range(), RadarOnionPeelingTableCalc(), ARTS::Method::RadarOnionPeelingTableCalc(), RadiationFieldSpectralIntegrate(), ARTS::Method::RadiationFieldSpectralIntegrate(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), ARTS::Method::refr_index_airFreeElectrons(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), rtmethods_unit_conversion(), run_cdisort(), scat_data_checkedCalc(), ARTS::Method::scat_data_checkedCalc(), ARTS::Method::scat_data_monoCalc(), scat_dataCalc(), ARTS::Method::scat_dataCalc(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensorOff(), ARTS::Method::sensorOff(), Linefunctions::set_cross_section_of_band(), Linefunctions::set_doppler(), Linefunctions::set_lineshape(), Linefunctions::set_lorentz(), Linefunctions::set_voigt(), LineShape::sparse_f_grid_red(), sparse_f_gridFromFrequencyGrid(), ARTS::Method::sparse_f_gridFromFrequencyGrid(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), surf_albedoCalc(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSemiSpecularBy3beams(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), test_hitran2017(), test_ls(), test_norm(), TRE05O2AbsModel(), LineShape::triple_sparse_f_grid(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), WMRFSelectChannels(), ARTS::Method::WMRFSelectChannels(), WriteMolTau(), ARTS::Method::WriteMolTau(), xsec_continuum_tag(), xsec_species(), ybatchDoublingMeanFocus(), ARTS::Method::ybatchDoublingMeanFocus(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yDoublingMeanFocus(), ARTS::Method::yDoublingMeanFocus(), yRadar(), ARTS::Method::yRadar(), ySimpleSpectrometer(), ARTS::Method::ySimpleSpectrometer(), ze_cfac(), and zeeman_on_the_fly().
f_index()
Index ARTS::Var::f_index (Workspace & ws) inline noexcept
Frequency index.
Not all methods handle all monochromatic frequencies (of f_grid) in parellel and this variable is used for communication between methods, holding the index of the frequency treated presently.
In some contexts, a negative f_index means all frequencies.
Usage: Method output.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6339 of file autoarts.h.
Referenced by calcSingleScatteringDataProperties(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), cloud_RT_surface(), cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudy_rt_vars_at_gp(), doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagAbsBT(), doit_conv_flagLsq(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Execute::doit_mono_agenda(), doit_mono_agendaExecute(), DoitCalc(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), DoitWriteIterationFields(), ARTS::Method::DoitWriteIterationFields(), f_gridMetMM(), get_disortsurf_props(), get_dtauc_ssalb(), get_paroptprop(), get_pfct(), get_pmom(), get_ppath_transmat(), iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), opt_prop_NScatElems(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Method::OptimizeDoitPressureGrid(), pha_mat_NScatElems(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), run_cdisort(), Sample_los(), ARTS::Method::scat_data_monoCalc(), scat_data_monoExtract(), ARTS::Method::scat_data_monoExtract(), and surf_albedoCalc().
file_index()
Index ARTS::Var::file_index (Workspace & ws) inline noexcept
Index number for files.
See WriteXMLIndexed for further information.
Usage: Input to WriteXMLIndexed and ReadXMLIndexed.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6350 of file autoarts.h.
Referenced by filename_xml_with_index(), nca_filename_with_index(), ppathWriteXMLPartial(), ARTS::Method::ppathWriteXMLPartial(), ReadXMLIndexed(), ARTS::Method::ReadXMLIndexed(), WriteNetCDFIndexed(), ARTS::Method::WriteNetCDFIndexed(), WriteXMLIndexed(), and ARTS::Method::WriteXMLIndexed().
forloop_agenda()
Agenda ARTS::Var::forloop_agenda (Workspace & ws) inline noexcept
Agenda performing a for loop.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6357 of file autoarts.h.
Referenced by ForLoop(), ARTS::Method::ForLoop(), ARTS::Agenda::Execute::forloop_agenda(), and ARTS::Agenda::Define::forloop_agenda().
forloop_index()
Index ARTS::Var::forloop_index (Workspace & ws) inline noexcept
The index for for-loops.
This is the index that is used by method ForLoop to loop over forloop_agenda*.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6367 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::forloop_agenda(), and forloop_agendaExecute().
fos_iyin_za_angles()
Vector ARTS::Var::fos_iyin_za_angles (Workspace & ws) inline noexcept
So far just testing of FOS ...
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6374 of file autoarts.h.
fos_scatint_angles()
Matrix ARTS::Var::fos_scatint_angles (Workspace & ws) inline noexcept
So far just testing of FOS ...
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6381 of file autoarts.h.
g0()
Numeric ARTS::Var::g0 (Workspace & ws) inline noexcept
Gravity at zero altitude.
This variable is "little g" at the reference ellipsiod. That is, for Earth this is a value around 9.81 m/s2
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6391 of file autoarts.h.
Referenced by lm_hitran_2017::calcw(), ARTS::Agenda::Execute::g0_agenda(), g0_agendaExecute(), g0Earth(), ARTS::Method::g0Earth(), g0Io(), ARTS::Method::g0Io(), g0Jupiter(), ARTS::Method::g0Jupiter(), g0Mars(), ARTS::Method::g0Mars(), g0Venus(), ARTS::Method::g0Venus(), GriddedFieldLatLonRegrid(), heating_ratesFromIrradiance(), ARTS::Method::heating_ratesFromIrradiance(), init_mpm2020_lsm(), init_mpm2020_slsm(), and lm_hitran_2017::sorter_calcw().
g0_agenda()
Agenda ARTS::Var::g0_agenda (Workspace & ws) inline noexcept
Agenda providing the gravity constant.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6398 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::g0_agenda(), ARTS::Agenda::Define::g0_agenda(), and ARTS::Method::z_fieldFromHSE().
GasAbsLookupCreate()
GasAbsLookup ARTS::Var::GasAbsLookupCreate (Workspace & ws, const Group::GasAbsLookup & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GasAbsLookup
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GasAbsLookup inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11807 of file autoarts.h.
References Workspace::add_wsv_inplace().
geo_pos()
Vector ARTS::Var::geo_pos (Workspace & ws) inline noexcept
Geo-position of a measurement.
An empty vector is allowed, then flagging that no geo-positioning has been performed.
Otherwise, this should be a vector having length 5. The elements are: altitude latitude longitide zenith angle azimuth angle
Dimensions: 0 or 5
Unit: [ m, deg, deg, deg, deg ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6419 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::geo_pos_agenda(), ARTS::Agenda::geo_pos_agenda_empty(), geo_pos_agendaExecute(), geo_posEndOfPpath(), ARTS::Method::geo_posEndOfPpath(), geo_posLowestAltitudeOfPpath(), ARTS::Method::geo_posLowestAltitudeOfPpath(), geo_posWherePpathPassesZref(), ARTS::Method::geo_posWherePpathPassesZref(), iyb_calc(), and jacobianCalcPointingZaRecalc().
geo_pos_agenda()
Agenda ARTS::Var::geo_pos_agenda (Workspace & ws) inline noexcept
Agenda deriving the geo-position of a pencil beam calculation.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6426 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::geo_pos_agenda(), ARTS::Agenda::Define::geo_pos_agenda(), ARTS::Agenda::geo_pos_agenda_empty(), iyb_calc(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), and yCalcAppend().
GriddedField1Create()
GriddedField1 ARTS::Var::GriddedField1Create (Workspace & ws, const Group::GriddedField1 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField1
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField1 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11845 of file autoarts.h.
References Workspace::add_wsv_inplace().
GriddedField2Create()
GriddedField2 ARTS::Var::GriddedField2Create (Workspace & ws, const Group::GriddedField2 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField2
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField2 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11864 of file autoarts.h.
References Workspace::add_wsv_inplace().
GriddedField3Create()
GriddedField3 ARTS::Var::GriddedField3Create (Workspace & ws, const Group::GriddedField3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11883 of file autoarts.h.
References Workspace::add_wsv_inplace().
GriddedField4Create()
GriddedField4 ARTS::Var::GriddedField4Create (Workspace & ws, const Group::GriddedField4 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField4
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField4 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11902 of file autoarts.h.
References Workspace::add_wsv_inplace().
GriddedField5Create()
GriddedField5 ARTS::Var::GriddedField5Create (Workspace & ws, const Group::GriddedField5 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField5
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField5 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11921 of file autoarts.h.
References Workspace::add_wsv_inplace().
GriddedField6Create()
GriddedField6 ARTS::Var::GriddedField6Create (Workspace & ws, const Group::GriddedField6 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GriddedField6
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GriddedField6 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11940 of file autoarts.h.
References Workspace::add_wsv_inplace().
GridPosCreate()
GridPos ARTS::Var::GridPosCreate (Workspace & ws, const Group::GridPos & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an GridPos
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] GridPos inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11826 of file autoarts.h.
References Workspace::add_wsv_inplace().
heating_rates()
Tensor3 ARTS::Var::heating_rates (Workspace & ws) inline noexcept
The heating rates of atmospheric layers.
The heating rate is defined as the rate of temperature change of an atmospheric layer due to heating by absorption of radiation or if it is negative due to loss of energy by emission of radiation.
Units: K s^-1
Size: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6443 of file autoarts.h.
Referenced by heating_ratesFromIrradiance(), and ARTS::Method::heating_ratesFromIrradiance().
hitran_xsec_data()
ArrayOfXsecRecord ARTS::Var::hitran_xsec_data (Workspace & ws) inline noexcept
Data for Hitran cross section species.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6450 of file autoarts.h.
Referenced by abs_xsec_per_speciesAddHitranXsec(), and ARTS::Method::abs_xsec_per_speciesAddHitranXsec().
HitranRelaxationMatrixDataCreate()
HitranRelaxationMatrixData ARTS::Var::HitranRelaxationMatrixDataCreate (Workspace & ws, const Group::HitranRelaxationMatrixData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an HitranRelaxationMatrixData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] HitranRelaxationMatrixData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11959 of file autoarts.h.
References Workspace::add_wsv_inplace().
IndexCreate()
Index ARTS::Var::IndexCreate (Workspace & ws, const Group::Index & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Index
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Index inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11978 of file autoarts.h.
References Workspace::add_wsv_inplace().
instrument_pol()
ArrayOfIndex ARTS::Var::instrument_pol (Workspace & ws) inline noexcept
Definition of the polarisation of an instrument.
The default for output is to give data for the selected Stokes elements (1:stokes_dim). This variable defines the polarisations that are actually measured, or are transmitted.
The polarisation states/components are coded as 0 = Undefined. 1 = I, total intensity. 2 = Q, second Stokes component, Iv - Ih. 3 = U, third Stokes component, I+45 - I-45. 4 = V, forth Stokes component, Irc - Ilc 5 = Iv, intensity of vertically polarised component. 6 = Ih, intensity of horizontally polarised component. 7 = I+45, intensity of +45 deg linearly polarised component. 8 = I-45, intensity of -45 deg linearly polarised component. 9 = Ilhc, intensity of left-hand circularly polarised component. 10 = Irhc, intensity of right-hand circularly polarised component.
See the documentation for definition of the Stokes vector and the different components.
If the instrument measures, or transmits, vertical and horizontal components, this variable shall accordingly be set to [5,6].
Conversion to Planck-BT of components 2-4 requires that component 1 is kept, and must be included as first element.
The shift from the Stokes vector can be made at any stage when of the sensor response set-up. The responses used must of course be adopted correspondingly. Or reversed, if the antenna response is defined for Iv or Ih it could be useful to shift polarisation as first sensor operation.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6491 of file autoarts.h.
Referenced by iy_transmitterMultiplePol(), ARTS::Method::iy_transmitterMultiplePol(), iy_transmitterSinglePol(), ARTS::Method::iy_transmitterSinglePol(), sensor_responsePolarisation(), and ARTS::Method::sensor_responsePolarisation().
instrument_pol_array()
ArrayOfArrayOfIndex ARTS::Var::instrument_pol_array (Workspace & ws) inline noexcept
Multiple definition of instrument polarisation.
Defined as instrument_pol but used when multiple polarisations are possible/required.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6503 of file autoarts.h.
Referenced by yRadar(), and ARTS::Method::yRadar().
inversion_iterate_agenda()
Agenda ARTS::Var::inversion_iterate_agenda (Workspace & ws) inline noexcept
Agenda recalculating spectra and Jacobian for iterative inversion methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6510 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::inversion_iterate_agenda(), and ARTS::Agenda::Define::inversion_iterate_agenda().
inversion_iteration_counter()
Index ARTS::Var::inversion_iteration_counter (Workspace & ws) inline noexcept
Iteration counter variable for inversion_iterate_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6517 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::inversion_iterate_agenda(), and inversion_iterate_agendaExecute().
irradiance_field()
Tensor4 ARTS::Var::irradiance_field (Workspace & ws) inline noexcept
Irradiance field also known as flux density.
Radiant flux received by a surface per unit area for each hemisphere. The last dimension denotes the hemispheres. The first component is the downward irradiance and the second component is the upward irradiance
Units: W m^-2
Size: [ p_grid, lat_grid, lon_grid, 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6535 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), DOBatchCalc(), heating_ratesFromIrradiance(), ARTS::Method::heating_ratesFromIrradiance(), irradiance_fieldFromRadiance(), and ARTS::Method::irradiance_fieldFromRadiance().
isotopologue_ratios()
SpeciesIsotopologueRatios ARTS::Var::isotopologue_ratios (Workspace & ws) inline noexcept
Contains the isotopologue ratios.
This variable can be set to default values by calling isotopologue_ratiosInitFromBuiltin
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6545 of file autoarts.h.
Referenced by ARTS::Method::abs_xsec_per_speciesAddLines(), ARTS::Method::ecs_dataAddMakarov2020(), ARTS::Method::ecs_dataAddRodrigues1997(), ARTS::Method::ecs_dataAddTran2011(), ARTS::Method::ecs_dataSetSpeciesData(), ARTS::Method::isotopologue_ratiosInitFromBuiltin(), ARTS::Method::isotopologue_ratiosInitFromHitran(), ARTS::Method::lbl_checkedCalc(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), and ARTS::Method::propmat_clearskyAddZeeman().
iy()
Matrix ARTS::Var::iy (Workspace & ws) inline noexcept
Monochromatic pencil beam radiance spectrum.
This variable holds a single spectrum, with values corresponding to infinite frequency and spatial resolution (compare to y).
The variable is used to represent spectra at all positions of the propagation path and can e.g. temporarily hold radiation entering the atmosphere from space.
Usage: Used by radiative transfer methods.
Unit: For passive observations, as selected by iy_unit. For transmission calculations, same as for transmitted signal.
Dimensions: [ f_grid, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6567 of file autoarts.h.
Referenced by apply_iy_unit(), apply_iy_unit2(), cloud_RT_surface(), DoitGetIncoming(), DoitGetIncoming1DAtm(), emission_from_propmat_field(), get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_cloudbox_agenda(), iy_cloudbox_agendaExecute(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Agenda::Execute::iy_space_agenda(), ARTS::Agenda::iy_space_agenda_cosmic_background(), iy_space_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Agenda::Execute::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), iy_transmitterMultiplePol(), ARTS::Method::iy_transmitterMultiplePol(), iy_transmitterSinglePol(), ARTS::Method::iy_transmitterSinglePol(), iyApplyUnit(), ARTS::Method::iyApplyUnit(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::iyRadarSingleScat(), iyReplaceFromAux(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), Interpolation::reinterp(), rtmethods_unit_conversion(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), surface_calc(), yRadar(), ySimpleSpectrometer(), and ARTS::Method::ySimpleSpectrometer().
iy_agenda_call1()
Index ARTS::Var::iy_agenda_call1 (Workspace & ws) inline noexcept
Flag to handle recursive calls of iy_main_agenda
The agenda iy_main_agenda can be used recursively and this flag is used to tell the methods inside the agenda which is the primary call. This is handled automatically for methods using iy_main_agenda*, such as yCalc, but the user must set this variable to 1 if the agenda is called directly inside the control file (which should be a rare case).
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6581 of file autoarts.h.
Referenced by get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), iyb_calc_body(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
iy_aux()
ArrayOfMatrix ARTS::Var::iy_aux (Workspace & ws) inline noexcept
Data auxiliary to iy.
Different data beside the direct result of the radiative transfer calculations (iy) can be obtained by this variable. These auxilary data are selected by iy_aux_vars.
Usage: Provided by some radiative transfer methods.
Dimensions: [quantity][ f_grid, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6596 of file autoarts.h.
Referenced by DoitGetIncoming(), DoitGetIncoming1DAtm(), get_iy(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Method::iyApplyUnit(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iyReplaceFromAux(), ARTS::Method::iyReplaceFromAux(), iySurfaceFastem(), iySurfaceRtpropAgenda(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), transmittanceFromIy_aux(), ARTS::Method::transmittanceFromIy_aux(), and yRadar().
iy_aux_vars()
ArrayOfString ARTS::Var::iy_aux_vars (Workspace & ws) inline noexcept
Selection of quantities for iy_aux and when applicable also y_aux.
Each element of this string array determines the quantity for the corresponding element in iy_aux and y_aux (i.e. the quantities are stored in the order given in iy_aux_vars).
The possible choices vary between the methods. See the WSM you select for iy_main_agenda for the complete set of choices. Please not that if the calculations are done through yCalc, you can not select along-the-path variables.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6612 of file autoarts.h.
Referenced by DoitGetIncoming(), DoitGetIncoming1DAtm(), get_iy(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Method::iyApplyUnit(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iyReplaceFromAux(), ARTS::Method::iyReplaceFromAux(), iySurfaceFastem(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), main(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), transmittanceFromIy_aux(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
iy_cloudbox_agenda()
Agenda ARTS::Var::iy_cloudbox_agenda (Workspace & ws) inline noexcept
Agenda deriving the intensity at boundary or interior of the cloudbox.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6619 of file autoarts.h.
Referenced by cloudboxOff(), ARTS::Method::cloudboxOff(), emission_from_propmat_field(), get_iy_of_background(), ARTS::Agenda::Execute::iy_cloudbox_agenda(), ARTS::Agenda::Define::iy_cloudbox_agenda(), ARTS::Method::iyEmissionStandard(), iyHybrid(), nlte_fieldForSingleSpeciesNonOverlappingLines(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
iy_id()
Index ARTS::Var::iy_id (Workspace & ws) inline noexcept
Identification number of iy.
This variable is intended to be an identification number for individual calculations of iy. This id-number can e.g. be used as input to WriteXMLIndexed*, to link filenames to the different calculations.
Some methods sets and updates iy_id. The general numbering scheme is: xxxyyycba where xxx identifies the row in sensorPos/los (i.e. the mblock_index), yyy identifies pencil beam direction inside measurement block (should in general match a row in mblock_dlos_grid), and cba identies later legs of total propagation paths, where a, b and c identifies secondary, tertiary and quaternary part, respectively. 1-based numbering is used. That is, the primary path of the first pencil beam of the first measurement block has iy_id = 001001000.
Accordingly, the primary propagation path has cba = 000. If the primary path intersects with the surface, and the downwelling radiation is calculated for three directions, these secondary paths get cba = 001, 002 and 003. If tertiary paths appear, they have numbers such as 011.
As the numbering scheme has nine positions, it is suitable to store files as: WriteXMLIndexed(output_file_format,iy_id,in,filename,9)
Setting of iy_id is not yet supported together with scattering calculations. The value of iy_id then differs, it is either set to 0 or keeps its value set by yCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6652 of file autoarts.h.
Referenced by get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), ARTS::Agenda::iy_main_agenda_transmission(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), and yRadar().
iy_independent_beam_approx_agenda()
Agenda ARTS::Var::iy_independent_beam_approx_agenda (Workspace & ws) inline noexcept
Agenda dedicated to iyIndependentBeamApproximation.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6658 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), ARTS::Agenda::Define::iy_independent_beam_approx_agenda(), and iyIndependentBeamApproximation().
iy_loop_freqs_agenda()
Agenda ARTS::Var::iy_loop_freqs_agenda (Workspace & ws) inline noexcept
Agenda dedicated to iyLoopFrequencies.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6664 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_loop_freqs_agenda(), ARTS::Agenda::Define::iy_loop_freqs_agenda(), ARTS::Method::iyLoopFrequencies(), and iyLoopFrequencies().
iy_main_agenda()
Agenda ARTS::Var::iy_main_agenda (Workspace & ws) inline noexcept
Agenda calculating the single monochromatic pencil beam spectrum.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6671 of file autoarts.h.
Referenced by DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), emission_from_propmat_field(), get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_main_agenda(), ARTS::Agenda::Define::iy_main_agenda(), ARTS::Agenda::iy_main_agenda_emission(), ARTS::Agenda::iy_main_agenda_transmission(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), nlte_fieldForSingleSpeciesNonOverlappingLines(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), and yCalcAppend().
iy_radar_agenda()
Agenda ARTS::Var::iy_radar_agenda (Workspace & ws) inline noexcept
Agenda calculating pointwise backscattering.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6678 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_radar_agenda(), ARTS::Agenda::Define::iy_radar_agenda(), and yRadar().
iy_space_agenda()
Agenda ARTS::Var::iy_space_agenda (Workspace & ws) inline noexcept
Agenda providing the downwelling radiation at the top of the atmosphere.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6685 of file autoarts.h.
Referenced by emission_from_propmat_field(), get_iy_of_background(), ARTS::Agenda::Execute::iy_space_agenda(), ARTS::Agenda::Define::iy_space_agenda(), ARTS::Agenda::iy_space_agenda_cosmic_background(), ARTS::Method::iyEmissionStandard(), iyHybrid(), iyMC(), MCGeneral(), nlte_fieldForSingleSpeciesNonOverlappingLines(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
iy_surface_agenda()
Agenda ARTS::Var::iy_surface_agenda (Workspace & ws) inline noexcept
Agenda providing the upwelling radiation from the surface.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6692 of file autoarts.h.
Referenced by emission_from_propmat_field(), get_iy_of_background(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Define::iy_surface_agenda(), ARTS::Agenda::iy_surface_agenda_use_surface_property(), ARTS::Method::iyEmissionStandard(), iyHybrid(), nlte_fieldForSingleSpeciesNonOverlappingLines(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
iy_surface_agenda_array()
ArrayOfAgenda ARTS::Var::iy_surface_agenda_array (Workspace & ws) inline noexcept
Upwelling radiation from the surface, divided into surface types.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6699 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_surface_agenda_array(), ARTS::Method::iySurfaceCallAgendaX(), and iySurfaceCallAgendaX().
iy_transmittance()
Tensor3 ARTS::Var::iy_transmittance (Workspace & ws) inline noexcept
Transmittance to be included in iy.
The calculation of iy can be performed over several propation path branches, and there can be recursive calls of iy_main_agenda. This variable gives the transmittance from the end point of the present branch and the sensor for such recursive cases.
This variable is used purely internally. The exact usage can vary between different RT integration schemes.
Usage: Internally inside iy_main_agenda.
Unit: 1
Dimensions: [ f_grid, stokes_dim, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6720 of file autoarts.h.
Referenced by DoitGetIncoming(), DoitGetIncoming1DAtm(), get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyb_calc_body(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
iy_transmitter_agenda()
Agenda ARTS::Var::iy_transmitter_agenda (Workspace & ws) inline noexcept
Agenda providing a transmitter signal.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6727 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_transmitter_agenda(), ARTS::Agenda::Define::iy_transmitter_agenda(), iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), and iyTransmissionStandard().
iy_unit()
String ARTS::Var::iy_unit (Workspace & ws) inline noexcept
Selection of output unit for radiative transfer methods.
This variable allows that the unit of the output radiance/intensity is changed. The possible choices differ between the radiative methods, including not considering the variable at all. Accordingly, for details see the radiative method you have selected (e.g., iyEmissionStandard, iyMC and the like).
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6740 of file autoarts.h.
Referenced by apply_iy_unit(), apply_iy_unit2(), DoitGetIncoming(), DoitGetIncoming1DAtm(), get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), ARTS::Agenda::iy_main_agenda_transmission(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), iyApplyUnit(), ARTS::Method::iyApplyUnit(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), main(), MCGeneral(), ARTS::Method::MCGeneral(), met_mm_polarisation_hmatrix(), rtmethods_unit_conversion(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Agenda::Execute::test_agenda_array(), test_agenda_arrayExecute(), yApplyUnit(), ARTS::Method::yApplyUnit(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), and ARTS::Method::yCalcAppend().
iy_unit_radar()
String ARTS::Var::iy_unit_radar (Workspace & ws) inline noexcept
Unit for radar simulations.
See the radar methods for allowed options.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6749 of file autoarts.h.
Referenced by MCRadar(), ARTS::Method::MCRadar(), yRadar(), and ARTS::Method::yRadar().
iyb()
Vector ARTS::Var::iyb (Workspace & ws) inline noexcept
Monochromatic pencil beam data for one measurement block.
The data for all iy of a measurement block appended to a vector, following the sorting order used for y.
Usage: Used internally.
Unit: W / (m^2 Hz sr) or transmittance.
Dimensions: [ nlos * nf * stokes_dim ] where nlos is number of rows in mblock_dlos_grid, and nf is length of f_grid.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6766 of file autoarts.h.
Referenced by iyb_calc(), iyb_calc_body(), ARTS::Agenda::Execute::jacobian_agenda(), jacobian_agendaExecute(), ARTS::Method::jacobianCalcDoNothing(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), ARTS::Method::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcSinefit(), yCalc_mblock_loop_body(), and ySimpleSpectrometer().
jacobian()
Matrix ARTS::Var::jacobian (Workspace & ws) inline noexcept
The Jacobian matrix.
The matrix holding the Jacobians of the retrieval quantities. The matrix has to be initialised before the retrieval quantities can be defined. Initialisation is done by*jacobianInit*. Retrieval quantities are then added with jacobianAdd... or retrievalAdd.. methods.
The order between rows and columns follows how data are stored in y and x, respectively.
Units: See the different retrieval quantities.
Dimension: [ y, number of retrieval quantities and grids ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6785 of file autoarts.h.
Referenced by ARTS::Method::avkCalc(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), ARTS::Agenda::Execute::inversion_iterate_agenda(), inversion_iterate_agendaExecute(), oem::AgendaWrapperMPI::Jacobian(), ARTS::Agenda::Execute::jacobian_agenda(), jacobian_agendaExecute(), jacobianAdjustAndTransform(), ARTS::Method::jacobianAdjustAndTransform(), ARTS::Method::jacobianCalcDoNothing(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), jacobianFromTwoY(), ARTS::Method::jacobianFromTwoY(), jacobianFromYbatch(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::OEM(), transform_jacobian(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yApplyUnit(), ARTS::Agenda::Execute::ybatch_calc_agenda(), ybatch_calc_agendaExecute(), ybatchCalc(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
jacobian_agenda()
Agenda ARTS::Var::jacobian_agenda (Workspace & ws) inline noexcept
Pure numerical Jacobian calculation agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6792 of file autoarts.h.
Referenced by abs_speciesAdd2(), ARTS::Agenda::Execute::jacobian_agenda(), ARTS::Agenda::Define::jacobian_agenda(), jacobianAddAbsSpecies(), jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddBasicCatalogParameter(), jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddBasicCatalogParameters(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddMagField(), jacobianAddNLTE(), jacobianAddNLTEs(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddScatSpecies(), ARTS::Method::jacobianAddScatSpecies(), jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameter(), jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), jacobianAddSinefit(), jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddSurfaceQuantity(), jacobianAddTemperature(), jacobianAddWind(), ARTS::Method::jacobianClose(), jacobianClose(), jacobianInit(), ARTS::Method::jacobianInit(), jacobianOff(), ARTS::Method::jacobianOff(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameter(), retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), retrievalAddFreqStretch(), retrievalAddMagField(), retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalDefClose(), retrievalDefClose(), retrievalDefInit(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), and yCalcAppend().
jacobian_do()
Index ARTS::Var::jacobian_do (Workspace & ws) inline noexcept
Flag to activate (clear-sky) Jacobian calculations.
If this variable is set to 0, no Jacobian calculations will be done, even if such calculations have been set-up (through the jacobianAddXxx methods).
Needs to be 0 if cloudy-sky (Doit) Jacobians shall be calculated.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6805 of file autoarts.h.
Referenced by adapt_stepwise_partial_derivatives(), get_iy(), get_iy_of_background(), get_stepwise_clearsky_propmat(), get_stepwise_effective_source(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), ARTS::Agenda::Execute::inversion_iterate_agenda(), inversion_iterate_agendaExecute(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iyReplaceFromAux(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::jacobianClose(), jacobianClose(), jacobianOff(), ARTS::Method::jacobianOff(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), ARTS::Method::retrievalDefClose(), retrievalDefClose(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), stepwise_source(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), ARTS::Method::SurfaceTessem(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
jacobian_quantities()
ArrayOfRetrievalQuantity ARTS::Var::jacobian_quantities (Workspace & ws) inline noexcept
The retrieval quantities in the Jacobian matrix.
An array of retrieval quantities for which the Jacobians are calculated.
Usage: Quantities are added by the jacobianAdd WSMs.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6817 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Method::abs_speciesAdd2(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), adapt_stepwise_partial_derivatives(), add_scalar_variance(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudboxOff(), ARTS::Method::cloudboxOff(), LineShape::compute(), ARTS::Method::covmat_sxAddBlock(), ARTS::Method::covmat_sxAddInverseBlock(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_zeeman(), field_of_propagation(), get_iy_of_background(), get_pointers_for_analytical_species(), get_pointers_for_scat_species(), get_standard_diy_dpath(), get_standard_starting_diy_dx(), get_stepwise_clearsky_propmat(), get_stepwise_effective_source(), get_stepwise_scattersky_source(), iyb_calc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::jacobianAddAbsSpecies(), ARTS::Method::jacobianAddBasicCatalogParameter(), ARTS::Method::jacobianAddBasicCatalogParameters(), jacobianAddFreqShift(), ARTS::Method::jacobianAddFreqShift(), jacobianAddFreqStretch(), ARTS::Method::jacobianAddFreqStretch(), ARTS::Method::jacobianAddMagField(), ARTS::Method::jacobianAddNLTE(), ARTS::Method::jacobianAddNLTEs(), jacobianAddPointingZa(), ARTS::Method::jacobianAddPointingZa(), ARTS::Method::jacobianAddPolyfit(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddSinefit(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddTemperature(), ARTS::Method::jacobianAddWind(), jacobianAdjustAndTransform(), ARTS::Method::jacobianAdjustAndTransform(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), ARTS::Method::jacobianClose(), jacobianClose(), jacobianInit(), ARTS::Method::jacobianInit(), jacobianOff(), ARTS::Method::jacobianOff(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::jacobianSetFuncTransformation(), LineShape::line_loop(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), ARTS::Method::OEM(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearsky_fieldCalc(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddFromAbsCoefPerSpecies(), propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameter(), retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), ARTS::Method::retrievalDefClose(), retrievalDefClose(), retrievalDefInit(), ARTS::Method::retrievalDefInit(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), stepwise_source(), test_ls(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::xaStandard(), xClip(), ARTS::Method::xClip(), xsec_species(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), ARTS::Method::yRadar(), and zeeman_on_the_fly().
jacobian_targets()
ArrayOfJacobianTarget ARTS::Var::jacobian_targets (Workspace & ws) inline noexcept
The partial derivatives that are computed for the Jacobian matrix.
An array of jacobian targets for which the Jacobians are calculated.
Usage: Input to absorption agendas.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6829 of file autoarts.h.
JacobianTargetCreate()
JacobianTarget ARTS::Var::JacobianTargetCreate (Workspace & ws, const Group::JacobianTarget & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an JacobianTarget
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] JacobianTarget inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 11997 of file autoarts.h.
References Workspace::add_wsv_inplace().
lat()
Numeric ARTS::Var::lat (Workspace & ws) inline noexcept
A latitude.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6838 of file autoarts.h.
Referenced by TelsemAtlas::calc_cellnum(), TelsemAtlas::calc_cellnum_nearest_neighbor(), cart2pol(), cart2poslos(), cart2poslos_plain(), cart2sph(), cart2sph_plain(), chk_pnd_field_raw_only_in_cloudbox(), cycle_lat_lon(), DoitGetIncoming1DAtm(), ARTS::Agenda::Execute::g0_agenda(), g0_agendaExecute(), g0Earth(), ARTS::Method::g0Earth(), geompath_from_r1_to_r2(), geompath_r_at_lat(), geompath_tanpos_3d(), TelsemAtlas::get_coordinates(), get_refr_index_2d(), get_refr_index_3d(), GriddedFieldLatLonRegrid(), InterpGriddedField2ToPosition(), EnergyLevelMap::InterpToGridPos(), plevel_crossing_2d(), plevel_slope_3d(), pol2cart(), pos2true_latlon(), poslos2cart(), r_crossing_2d(), r_crossing_3d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_2d(), refr_gradients_3d(), rsurf_at_lat(), rsurf_at_latlon(), rte_posSet(), ARTS::Method::rte_posSet(), ARTS::Agenda::Method::rte_posSet(), sph2cart(), surf_radius_at_l(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), surfaceTelsem(), telsemAtlasLookup(), ARTS::Method::telsemAtlasLookup(), ARTS::Agenda::Method::telsemAtlasLookup(), telsemStandalone(), ARTS::Method::telsemStandalone(), telsemSurfaceTypeLandSea(), test_telsem_interpolate(), test_telsem_read(), ybatchMetProfiles(), and ybatchMetProfilesClear().
lat_grid()
Vector ARTS::Var::lat_grid (Workspace & ws) inline noexcept
The latitude grid.
The latitudes for which the atmospheric fields are defined. The atmosphere is undefined outside the range covered by the grid. The grid must be sorted in increasing order, with no repetitions.
Geocentric latitudes are used.
For 1D calculations this vector shall be set to be empty.
For 2D cases the latitudes shall be interpreted as the angular distance inside the orbit plane from the equator (values outside +-90 deg are allowed).
For 3D, the valid latitude range is [-90,90].
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6867 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), ARTS::Method::atm_gridsFromZRaw(), AtmFieldPerturb(), ARTS::Method::AtmFieldPerturb(), AtmFieldPerturbAtmGrids(), ARTS::Method::AtmFieldPerturbAtmGrids(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), AtmosphereSet1D(), ARTS::Method::AtmosphereSet1D(), check_retrieval_grids(), chk_atm_field(), chk_atm_grids(), chk_atm_surface(), chk_latlon_true(), chk_pnd_field_raw_only_in_cloudbox(), chk_scat_species_field(), cloud_ppath_update3D(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), FieldFromGriddedFieldCheckLatLonHelper(), get_gp_atmgrids_to_rq(), get_gp_atmsurf_to_rq(), get_gp_rq_to_atmgrids(), get_refr_index_2d(), get_refr_index_3d(), GriddedFieldZToPRegrid(), ARTS::Method::GriddedFieldZToPRegrid(), IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexNumberOfAtmosphericPoints(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), jacobianAddAbsSpecies(), ARTS::Method::jacobianAddAbsSpecies(), jacobianAddMagField(), ARTS::Method::jacobianAddMagField(), jacobianAddNLTE(), ARTS::Method::jacobianAddNLTE(), jacobianAddNLTEs(), ARTS::Method::jacobianAddNLTEs(), jacobianAddScatSpecies(), ARTS::Method::jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddSurfaceQuantity(), jacobianAddTemperature(), ARTS::Method::jacobianAddTemperature(), jacobianAddWind(), ARTS::Method::jacobianAddWind(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::lat_gridFromZRaw(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), plevel_slope_2d(), plevel_slope_3d(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pos2refell_r(), pos2true_latlon(), ppath_calc(), ppath_end_2d(), ppath_end_3d(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_step_geom_2d(), ppath_step_geom_3d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refell2d(), refr_gradients_2d(), refr_gradients_3d(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_pos2gridpos(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), specular_losCalc(), ARTS::Method::specular_losCalc(), surf_radius_at_l(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surface_props_check(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), ARTS::Method::surface_typeInterpTypeMask(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), ARTS::Method::SurfaceTessem(), telsemSurfaceTypeLandSea(), ARTS::Method::telsemSurfaceTypeLandSea(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), z_at_lat_2d(), z_at_latlon(), ARTS::Method::z_fieldFromHSE(), z_surfaceConstantAltitude(), ARTS::Method::z_surfaceConstantAltitude(), z_surfaceFromFileAndGrid(), and ARTS::Method::z_surfaceFromFileAndGrid().
lat_true()
Vector ARTS::Var::lat_true (Workspace & ws) inline noexcept
Latitudinal geolocation for 1D and 2D data.
The variables lat_grid and lon_grid contain true positions only for 3D. For 1D and 2D, the geographical position is given by lat_true* and lon_true. Can be left empty when not used. Otherwise:
1D: lat_true shall have length 1
2D: Both lat_true and lon_true shall have a length matching lat_grid*. That is, lat_true and lon_true shall not be seen as grids, they are vectors giving the actual lat or lon for each point corresponding to lat_grid.
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6890 of file autoarts.h.
Referenced by atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), AtmosphereSet3D(), ARTS::Method::AtmosphereSet3D(), chk_latlon_true(), GriddedFieldLatLonRegrid(), ARTS::Method::GriddedFieldLatLonRegrid(), GriddedFieldLatLonRegridHelper(), InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), pos2true_latlon(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), ARTS::Method::surface_typeInterpTypeMask(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), telsemSurfaceTypeLandSea(), ARTS::Method::telsemSurfaceTypeLandSea(), and ARTS::Method::z_fieldFromHSE().
lbl_checked()
Index ARTS::Var::lbl_checked (Workspace & ws) inline noexcept
Flag to check if the line-by-line calculations will work
Usage: Set manually on own risk, or use lbl_checkedCalc.
Unit: Boolean
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6901 of file autoarts.h.
Referenced by abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), lbl_checkedCalc(), ARTS::Method::lbl_checkedCalc(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddZeeman(), and ARTS::Method::propmat_clearskyAddZeeman().
level0_data()
ArrayOfVector ARTS::Var::level0_data (Workspace & ws) inline noexcept
List of L0 data. Can be of any type. It is method-dependent how this is used to calibrated to L1
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6909 of file autoarts.h.
Referenced by main(), ybatchColdAtmHotAtmCycle(), and ARTS::Method::ybatchColdAtmHotAtmCycle().
level0_time()
ArrayOfTime ARTS::Var::level0_time (Workspace & ws) inline noexcept
List of L0 times. Should be in UTC. It is method-dependent how this is used to calibrated to L1
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6917 of file autoarts.h.
Referenced by main(), ybatchColdAtmHotAtmCycle(), and ARTS::Method::ybatchColdAtmHotAtmCycle().
line_irradiance()
Matrix ARTS::Var::line_irradiance (Workspace & ws) inline noexcept
Irradiance as seen by a single absorption line.
Used internally for, e.g., NLTE effects
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6926 of file autoarts.h.
Referenced by ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), and nlte_fieldForSingleSpeciesNonOverlappingLines().
line_transmission()
Tensor3 ARTS::Var::line_transmission (Workspace & ws) inline noexcept
Transmission as seen by a single absorption line.
Used internally for, e.g., NLTE effects
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6935 of file autoarts.h.
Referenced by ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), and nlte_fieldForSingleSpeciesNonOverlappingLines().
lm_ga_history()
Vector ARTS::Var::lm_ga_history (Workspace & ws) inline noexcept
The series of gamma values for a Marquardt-levenberg inversion.
The values are stored following iteration order, i.e. the first is the gamma factor for the first iteration etc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6945 of file autoarts.h.
Referenced by ARTS::Method::OEM().
lo()
Numeric ARTS::Var::lo (Workspace & ws) inline noexcept
The local oscillator frequency.
A local oscillator frequency is used in a heterodyne system when the mixer folds the spectra from from radio frequencies (RF) to intermediate frequencies (IF).
Unit: Hz
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6960 of file autoarts.h.
Referenced by chk_met_mm_backend(), defocusing_general(), f_gridFromSensorAMSU(), f_gridMetMM(), Interpolation::min_cyclic(), mixer_matrix(), Rand< Index >::Rand(), sensor_responseIF2RF(), ARTS::Method::sensor_responseIF2RF(), sensor_responseMixer(), and ARTS::Method::sensor_responseMixer().
lo_multi()
Vector ARTS::Var::lo_multi (Workspace & ws) inline noexcept
Local oscillator frequencies.
As lo but describes an instrument with multiple mixers. A vector element for each LO. The size of this variable and sideband_response_multi* shall match, and probably also sideband_mode_multi*.
Unit: Hz
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6976 of file autoarts.h.
Referenced by ARTS::Method::f_gridFromSensorAMSU(), sensor_responseGenericAMSU(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), and sensor_responseSimpleAMSU().
lon()
Numeric ARTS::Var::lon (Workspace & ws) inline noexcept
A longitude.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 6985 of file autoarts.h.
Referenced by TelsemAtlas::calc_cellnum(), TelsemAtlas::calc_cellnum_nearest_neighbor(), cart2poslos(), cart2poslos_plain(), cart2sph(), cart2sph_plain(), chk_pnd_field_raw_only_in_cloudbox(), cycle_lat_lon(), DoitGetIncoming1DAtm(), ARTS::Agenda::Execute::g0_agenda(), g0_agendaExecute(), geompath_tanpos_3d(), TelsemAtlas::get_coordinates(), get_refr_index_3d(), InterpGriddedField2ToPosition(), EnergyLevelMap::InterpToGridPos(), lon_shiftgrid(), Legendre::longitude_clamp(), plevel_slope_3d(), pos2true_latlon(), poslos2cart(), r_crossing_3d(), raytrace_3d_linear_basic(), refr_gradients_3d(), regrid_atmsurf_by_gp_oem(), resolve_lon(), rsurf_at_latlon(), rte_posSet(), ARTS::Method::rte_posSet(), ARTS::Agenda::Method::rte_posSet(), sph2cart(), surf_radius_at_l(), surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), surfaceTelsem(), telsemAtlasLookup(), ARTS::Method::telsemAtlasLookup(), ARTS::Agenda::Method::telsemAtlasLookup(), telsemStandalone(), ARTS::Method::telsemStandalone(), telsemSurfaceTypeLandSea(), test_telsem_interpolate(), test_telsem_read(), ybatchMetProfiles(), and ybatchMetProfilesClear().
lon_grid()
Vector ARTS::Var::lon_grid (Workspace & ws) inline noexcept
The longitude grid.
The longitudes for which the atmospheric fields are defined. The atmosphere is undefined outside the range covered by the grid. The grid must be sorted in increasing order, with no repetitions.
For 1D and 2D, this WSV shall be set to be empty.
Allowed values for longitudes is the range [-360,360]. The difference between last and first value can not exceed 360 degrees. A difference of exactly 360 deg. means that the complete globe is covered and no propagation paths will reach a longitude edge.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7011 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), ARTS::Method::atm_gridsFromZRaw(), AtmFieldPerturb(), ARTS::Method::AtmFieldPerturb(), AtmFieldPerturbAtmGrids(), ARTS::Method::AtmFieldPerturbAtmGrids(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), AtmosphereSet1D(), ARTS::Method::AtmosphereSet1D(), AtmosphereSet2D(), ARTS::Method::AtmosphereSet2D(), check_retrieval_grids(), chk_atm_field(), chk_atm_grids(), chk_atm_surface(), chk_pnd_field_raw_only_in_cloudbox(), chk_scat_species_field(), cloud_ppath_update3D(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), FieldFromGriddedFieldCheckLatLonHelper(), get_gp_atmgrids_to_rq(), get_gp_atmsurf_to_rq(), get_gp_rq_to_atmgrids(), get_refr_index_3d(), GriddedFieldZToPRegrid(), ARTS::Method::GriddedFieldZToPRegrid(), IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexNumberOfAtmosphericPoints(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), jacobianAddAbsSpecies(), ARTS::Method::jacobianAddAbsSpecies(), jacobianAddMagField(), ARTS::Method::jacobianAddMagField(), jacobianAddNLTE(), ARTS::Method::jacobianAddNLTE(), jacobianAddNLTEs(), ARTS::Method::jacobianAddNLTEs(), jacobianAddScatSpecies(), ARTS::Method::jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddSurfaceQuantity(), jacobianAddTemperature(), ARTS::Method::jacobianAddTemperature(), jacobianAddWind(), ARTS::Method::jacobianAddWind(), ARTS::Method::lon_gridFromRawField(), ARTS::Method::lon_gridFromZRaw(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), plevel_slope_3d(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pos2refell_r(), ppath_calc(), ppath_end_3d(), ppath_start_3d(), ppath_start_stepping(), ppath_step_geom_3d(), ppath_step_refr_3d(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), raytrace_3d_linear_basic(), refr_gradients_3d(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_pos2gridpos(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), specular_losCalc(), ARTS::Method::specular_losCalc(), surf_radius_at_l(), surface_props_check(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), ARTS::Method::SurfaceTessem(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), z_at_latlon(), ARTS::Method::z_fieldFromHSE(), z_surfaceConstantAltitude(), ARTS::Method::z_surfaceConstantAltitude(), z_surfaceFromFileAndGrid(), and ARTS::Method::z_surfaceFromFileAndGrid().
lon_true()
Vector ARTS::Var::lon_true (Workspace & ws) inline noexcept
Longitudinal geolocation for 1D and 2D data.
The variables lat_grid and lon_grid contain true positions only for 3D. For 1D and 2D, the geographical position is given by lat_true* and lon_true. Can be left empty when not used. Otherwise:
1D: lon_true shall have length 1
2D: Both lat_true and lon_true shall have a length matching lat_grid*. That is, lat_true and lon_true shall not be seen as grids, they are vectors giving the actual lat or lon for each point corresponding to lat_grid.
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7034 of file autoarts.h.
Referenced by atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), AtmosphereSet3D(), ARTS::Method::AtmosphereSet3D(), chk_latlon_true(), GriddedFieldLatLonRegrid(), ARTS::Method::GriddedFieldLatLonRegrid(), GriddedFieldLatLonRegridHelper(), InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), pos2true_latlon(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), ARTS::Method::surface_typeInterpTypeMask(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), telsemSurfaceTypeLandSea(), ARTS::Method::telsemSurfaceTypeLandSea(), and ARTS::Method::z_fieldFromHSE().
mag_u_field()
Tensor3 ARTS::Var::mag_u_field (Workspace & ws) inline noexcept
Zonal component of the magnetic field.
The East-West magnetic field component. Positive values, when pointing eastward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7051 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
mag_u_field_raw()
GriddedField3 ARTS::Var::mag_u_field_raw (Workspace & ws) inline noexcept
Raw zonal component of the magnetic field.
The East-West magnetic field component. Positive values, when pointing eastward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7068 of file autoarts.h.
Referenced by MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MagRawRead(), and ARTS::Method::MagRawRead().
mag_v_field()
Tensor3 ARTS::Var::mag_v_field (Workspace & ws) inline noexcept
Meridional component of the magnetic field.
The North-South magnetic field component. Positive values, when pointing northward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7085 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
mag_v_field_raw()
GriddedField3 ARTS::Var::mag_v_field_raw (Workspace & ws) inline noexcept
Raw meridional component of the magnetic field.
The North-South magnetic field component. Positive values, when pointing northward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7102 of file autoarts.h.
Referenced by MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MagRawRead(), and ARTS::Method::MagRawRead().
mag_w_field()
Tensor3 ARTS::Var::mag_w_field (Workspace & ws) inline noexcept
Vertical component of the magnetic field.
Positive values, when pointing upward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7118 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
mag_w_field_raw()
GriddedField3 ARTS::Var::mag_w_field_raw (Workspace & ws) inline noexcept
Raw vertical component of the magnetic field.
Positive values, when pointing upward.
Can be set to be empty, which is interpreted as zero field strength everywhere.
Unit: T
Dimensions: [ p_grid, lat_grid, lon_grid ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7134 of file autoarts.h.
Referenced by MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MagRawRead(), and ARTS::Method::MagRawRead().
main_agenda()
Agenda ARTS::Var::main_agenda (Workspace & ws) inline noexcept
Agenda corresponding to the entire controlfile.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7141 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::main_agenda(), ARTS::Agenda::Define::main_agenda(), and Verbosity::set_main_agenda().
MapOfErrorCorrectedSuddenDataCreate()
MapOfErrorCorrectedSuddenData ARTS::Var::MapOfErrorCorrectedSuddenDataCreate (Workspace & ws, const Group::MapOfErrorCorrectedSuddenData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an MapOfErrorCorrectedSuddenData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] MapOfErrorCorrectedSuddenData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12035 of file autoarts.h.
References Workspace::add_wsv_inplace().
MatrixCreate()
Matrix ARTS::Var::MatrixCreate (Workspace & ws, const Group::Matrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Matrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Matrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12054 of file autoarts.h.
References Workspace::add_wsv_inplace().
mblock_dlos_grid()
Matrix ARTS::Var::mblock_dlos_grid (Workspace & ws) inline noexcept
The set of angular pencil beam directions for each measurement block.
The relative angles in this variable are angular off-sets with respect to the angles in sensor_los.
The first column holds the relative zenith angle. This column is mandatory for all atmospheric dimensionalities. For 3D, there can also be a second column, giving relative azimuth angles. If this column is not present (for 3D) zero azimuth off-sets are assumed.
This rule applies to all WSVs of dlos-type, while for WSVs holding absolute angles (los-type, such as sensor_los), the second column is mandatory for 3D.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user or output of antenna WSMs.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7168 of file autoarts.h.
Referenced by AntennaConstantGaussian1D(), ARTS::Method::AntennaConstantGaussian1D(), AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), AntennaOff(), ARTS::Method::AntennaOff(), iyb_calc(), iyb_calc_body(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), mblock_dlos_gridUniformCircular(), ARTS::Method::mblock_dlos_gridUniformCircular(), mblock_dlos_gridUniformRectangular(), ARTS::Method::mblock_dlos_gridUniformRectangular(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), and ySimpleSpectrometer().
mblock_index()
Index ARTS::Var::mblock_index (Workspace & ws) inline noexcept
Measurement block index.
Used to tell agendas the index of present measurement block.
Usage: Used internally.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7179 of file autoarts.h.
Referenced by calcBaselineFit(), get_rowindex_for_mblock(), iyb_calc(), iyb_calc_body(), ARTS::Agenda::Execute::jacobian_agenda(), jacobian_agendaExecute(), ARTS::Method::jacobianCalcDoNothing(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), yCalc(), and yCalc_mblock_loop_body().
mc_antenna()
MCAntenna ARTS::Var::mc_antenna (Workspace & ws) inline noexcept
Antenna pattern description for dedicated MC calculaions.
Usage: Input to MCGeneral. Set by mc_antennaSetGaussian and similar methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7189 of file autoarts.h.
Referenced by iyMC(), mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussian(), mc_antennaSetGaussianByFWHM(), ARTS::Method::mc_antennaSetGaussianByFWHM(), mc_antennaSetPencilBeam(), ARTS::Method::mc_antennaSetPencilBeam(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), and ARTS::Method::MCRadar().
mc_error()
Vector ARTS::Var::mc_error (Workspace & ws) inline noexcept
Error in simulated y when using a Monte Carlo approach.
Usage: Output from Monte Carlo functions.
Units: Depends on iy_unit.
Size: [ stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7202 of file autoarts.h.
Referenced by iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), and ARTS::Method::MCRadar().
mc_iteration_count()
Index ARTS::Var::mc_iteration_count (Workspace & ws) inline noexcept
Counts the number of iterations (or photons) used in the MC scattering algorithm.
Usage: Set by MCGeneral and other MC methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7212 of file autoarts.h.
Referenced by iyMC(), MCGeneral(), and ARTS::Method::MCGeneral().
mc_max_iter()
Index ARTS::Var::mc_max_iter (Workspace & ws) inline noexcept
The maximum number of iterations allowed for Monte Carlo calculations.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7222 of file autoarts.h.
Referenced by iyMC(), ARTS::Method::iyMC(), ARTS::Method::MCGeneral(), MCRadar(), and ARTS::Method::MCRadar().
mc_max_scatorder()
Index ARTS::Var::mc_max_scatorder (Workspace & ws) inline noexcept
The maximum scattering order allowed for Monte Carlo radar calculations.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7232 of file autoarts.h.
Referenced by ARTS::Method::MCRadar().
mc_max_time()
Index ARTS::Var::mc_max_time (Workspace & ws) inline noexcept
The maximum time allowed for Monte Carlo calculations.
Usage: Set by the user.
Unit: s
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7243 of file autoarts.h.
Referenced by iyMC(), ARTS::Method::iyMC(), and ARTS::Method::MCGeneral().
mc_min_iter()
Index ARTS::Var::mc_min_iter (Workspace & ws) inline noexcept
The minimum number of iterations allowed for Monte Carlo calculations.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7253 of file autoarts.h.
Referenced by iyMC(), ARTS::Method::iyMC(), and ARTS::Method::MCGeneral().
mc_points()
Tensor3 ARTS::Var::mc_points (Workspace & ws) inline noexcept
Source to emission, position.
Counts the number of MC endpoints in each grid cell.
Usage: Set by MCGeneral and other MC methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7264 of file autoarts.h.
Referenced by iyMC(), MCGeneral(), and ARTS::Method::MCGeneral().
mc_scat_order()
ArrayOfIndex ARTS::Var::mc_scat_order (Workspace & ws) inline noexcept
Number of atmospheric scattering events between emission point and sensor.
The first element gives the number of cases with zero scattering events, the second the number of single scattering cases etc.
Scattering orders above what the variable can hold are not stored at all. The number of such cases can be determined by comparing mc_iteration_count* with the sum of the elements in this array.
Usage: Set by MCGeneral and other MC methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7280 of file autoarts.h.
Referenced by iyMC(), MCGeneral(), and ARTS::Method::MCGeneral().
mc_seed()
Index ARTS::Var::mc_seed (Workspace & ws) inline noexcept
The integer seed for the random number generator used by Monte Carlo methods.
Usage: Set by MCSetSeed.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7290 of file autoarts.h.
Referenced by ARTS::Method::abs_lookupTestAccMC(), iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), MCSetSeedFromTime(), ARTS::Method::MCSetSeedFromTime(), and psd_cloudice_MH97().
mc_source_domain()
ArrayOfIndex ARTS::Var::mc_source_domain (Workspace & ws) inline noexcept
Rough classification of source to emission.
This is an array of length 4, where the elements in order represent space, the surface, atmospheric gas and atmospheric particle. The distinction between the two last elements is if the emission is associated with vmr_field or pnd_field.
The values of the array give the number of cases where the emission source was found to be inside each "domain".
Usage: Set by MCGeneral and other MC methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7307 of file autoarts.h.
Referenced by iyMC(), MCGeneral(), and ARTS::Method::MCGeneral().
mc_std_err()
Numeric ARTS::Var::mc_std_err (Workspace & ws) inline noexcept
Target precision (1 std. dev.) for Monte Carlo calculations.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7316 of file autoarts.h.
Referenced by iyMC(), ARTS::Method::iyMC(), and ARTS::Method::MCGeneral().
mc_taustep_limit()
Numeric ARTS::Var::mc_taustep_limit (Workspace & ws) inline noexcept
Defines an upper step length in terms of optical thickness for Monte Carlo calculations.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7325 of file autoarts.h.
Referenced by iyMC(), ARTS::Method::iyMC(), and ARTS::Method::MCGeneral().
mc_y_tx()
Vector ARTS::Var::mc_y_tx (Workspace & ws) inline noexcept
Normalized Stokes vector for transmittance (e.g., radar).
The first element (intensity) should have a value of 1. Usage: Set by user.
Units: Unitless.
Size: [ stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7339 of file autoarts.h.
Referenced by MCRadar(), and ARTS::Method::MCRadar().
MCAntennaCreate()
MCAntenna ARTS::Var::MCAntennaCreate (Workspace & ws, const Group::MCAntenna & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an MCAntenna
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] MCAntenna inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12016 of file autoarts.h.
References Workspace::add_wsv_inplace().
met_amsu_data()
Matrix ARTS::Var::met_amsu_data (Workspace & ws) inline noexcept
The AMSU data set.
This is intended as input for the method ybatchMetProfiles. It holds the latitude, longitude, satellite zenith angle and amsu-b corrected and uncorrected brightness temperatures. It also has information about the particular pixel corresponds to a land or sea point. This will be read in the method ybatchMetProfiles and the profiles corresponding to each latitude and longitude will be read in.
See documentation of WSM ybatchMetProfiles for more information.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7355 of file autoarts.h.
Referenced by ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), and ARTS::Method::ybatchMetProfilesClear().
met_mm_antenna()
Vector ARTS::Var::met_mm_antenna (Workspace & ws) inline noexcept
The antenna beam width for meteorological millimeter instruments.
This Vector must match the number and order of channels in met_mm_backend*.
Usage: Set by the user.
Unit: [ Hz ]
Size: [ number of channels ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7371 of file autoarts.h.
Referenced by ARTS::Method::sensor_responseMetMM().
met_mm_backend()
Matrix ARTS::Var::met_mm_backend (Workspace & ws) inline noexcept
Backend description for meteorological millimeter sensors with passbands.
This is a compact description of a passband-type sensor, e.g. AMSU-A. The matrix contains one row for each instrument channel. Each row contains four elements:
LO position [Hz] first offset from the LO [Hz] second offset from the LO+offset1 [Hz] channel width [Hz]
                    LO
                     |
         offset1     |    offset1
     ----------------+----------------
     |                               |
     |                               |
offset2 | offset2 offset2 | offset2 ------—+------— ------—+------— | | | | | | | |
width width width width
For a sensor with 1 passband, offset1 and offset2 are zero. For a sensor with 2 passbands, only offset2 is zero.
Usage: Set by the user.
Unit: All entries in Hz.
Size: [number of channels, 4]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7408 of file autoarts.h.
Referenced by ARTS::Method::f_gridMetMM().
met_mm_polarisation()
ArrayOfString ARTS::Var::met_mm_polarisation (Workspace & ws) inline noexcept
The polarisation for meteorological millimeter instruments.
This array must match the number and order of channels in met_mm_backend*.
Possible values: V: Vertical polarisation H: Horizontal polarisation LHC: Left-hand circular polarisation RHC: Right-hand circular polarisation AMSU-V: Vertical polarisation dependening on AMSU zenith angle AMSU-H: Horizontal polarisation dependening on AMSU zenith angle ISMAR-V: Vertical polarisation dependening on ISMAR zenith angle ISMAR-H: Horizontal polarisation dependening on AMSU zenith angle
Usage: Set by the user.
Unit: [ String ]
Size: [ number of channels ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7434 of file autoarts.h.
Referenced by ARTS::Method::sensor_responseMetMM().
met_profile_calc_agenda()
Agenda ARTS::Var::met_profile_calc_agenda (Workspace & ws) inline noexcept
Agenda for metoffice profile calculations.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7441 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::met_profile_calc_agenda(), ARTS::Agenda::Define::met_profile_calc_agenda(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), and ARTS::Method::ybatchMetProfilesClear().
molarmass_dry_air()
Numeric ARTS::Var::molarmass_dry_air (Workspace & ws) inline noexcept
The average molar mass of dry air.
This could also be referred to as the average molecular weight for dry air. The definition of "dry air" can differ between planets and methods using the WSV. For Earth, this should be a value around 28.97.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7453 of file autoarts.h.
Referenced by ARTS::Method::z_fieldFromHSE().
nbooks()
Index ARTS::Var::nbooks (Workspace & ws) inline noexcept
Number of elements in 4th lowest dimension of a Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7460 of file autoarts.h.
Referenced by ARTS::Method::nbooksGet(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
ncols()
Index ARTS::Var::ncols (Workspace & ws) inline noexcept
Number of columns (elements in lowest dimension) of a Matrix or Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7467 of file autoarts.h.
Referenced by ARTS::Method::MatrixSetConstant(), ARTS::Method::ncolsGet(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
nelem()
Index ARTS::Var::nelem (Workspace & ws) inline noexcept
Number of elements of a Vector or Array.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7474 of file autoarts.h.
Referenced by ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfTimeNLinSpace(), ARTS::Method::ArrayOfTimeSetConstant(), ARTS::Method::IndexSetToLast(), ARTS::Method::nelemGet(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), and ARTS::Method::VectorSetConstant().
nlibraries()
Index ARTS::Var::nlibraries (Workspace & ws) inline noexcept
Number of elements in 7th lowest dimension of a Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7481 of file autoarts.h.
Referenced by librariesTensor7(), ARTS::Method::nlibrariesGet(), pha_mat_sptFromDataDOITOpt(), Tensor7SetConstant(), ARTS::Method::Tensor7SetConstant(), and xml_read_from_stream().
nlte_do()
Index ARTS::Var::nlte_do (Workspace & ws) inline noexcept
Flag to perform Non-LTE calculations.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7488 of file autoarts.h.
Referenced by abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), nlteOff(), ARTS::Method::nlteOff(), nlteSetByQuantumIdentifiers(), ARTS::Method::nlteSetByQuantumIdentifiers(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), and zeeman_on_the_fly().
nlte_field()
EnergyLevelMap ARTS::Var::nlte_field (Workspace & ws) inline noexcept
The field of NLTE temperatures and/or ratios.
This variable gives the NLTE temperature/ratio at each crossing of the pressure, latitude and longitude grids. The size of the array is the number of NLTE levels in all molecules.
The temperature/ratio for a point between the grid crossings is obtained by (multi-)linear interpolation of the nlte_field.
There are two types of NLTE computations available in ARTS. One from giving excitiation temperatures that makes the absorption/emission diverge from LTE. The other is to use the absolute ratios of upper-to-lower states at the levels of interest.
Units: [ K or % ]]
Dimensions: [ NLTE levels, p_grid, lat_grid, lon_grid ] or [ 0, 0, 0, 0 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7511 of file autoarts.h.
Referenced by AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), emission_from_propmat_field(), get_iy(), get_iy_of_background(), get_ppath_atmvars(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), iy_surface_agendaExecute(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), nlte_fieldFromRaw(), ARTS::Method::nlte_fieldFromRaw(), nlte_fieldRescalePopulationLevels(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), nlte_positions_in_statistical_equilibrium_matrix(), nlteOff(), ARTS::Method::nlteOff(), nlteSetByQuantumIdentifiers(), ARTS::Method::nlteSetByQuantumIdentifiers(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), and ARTS::Method::yCalcAppend().
nlte_field_raw()
ArrayOfGriddedField3 ARTS::Var::nlte_field_raw (Workspace & ws) inline noexcept
Raw data for NLTE temperatures and/or ratios.
This variable gives the NLTE temperature/ratio as stored in the database for the atmospheric scenarios.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user by choosing a climatology.
Unit: K
Size ArrayOfGriddedField3 array: [NLTE levels] or [ 0 ] fields: [N_p] [N_lat] [N_lon] [N_p, N_lat, N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7538 of file autoarts.h.
Referenced by AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), and ARTS::Method::AtmWithNLTERawRead().
nlte_level_identifiers()
ArrayOfQuantumIdentifier ARTS::Var::nlte_level_identifiers (Workspace & ws) inline noexcept
An array of non-lte quantum identifiers for levels matching nlte_field_raw* and on request nlte_vibrational_energies.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7546 of file autoarts.h.
Referenced by abs_nlteFromRaw(), ARTS::Method::abs_nlteFromRaw(), ARTS::Method::AtmFieldsCalc(), ARTS::Method::AtmFieldsCalcExpand1D(), ARTS::Method::AtmRawRead(), ARTS::Method::AtmWithNLTERawRead(), nlte_fieldFromRaw(), ARTS::Method::nlte_fieldFromRaw(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), nlteOff(), ARTS::Method::nlteOff(), rtp_nlteFromRaw(), and ARTS::Method::rtp_nlteFromRaw().
nlte_source()
StokesVector ARTS::Var::nlte_source (Workspace & ws) inline noexcept
Variable to contain the additional source function due to NLTE effects.
Dimensions: [nza, naa, nf, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7555 of file autoarts.h.
Referenced by nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), and zeeman_on_the_fly().
nlte_vibrational_energies()
Vector ARTS::Var::nlte_vibrational_energies (Workspace & ws) inline noexcept
An list of vibrational energies matching nlte_level_identifiers* and nlte_field_raw or being 0.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7563 of file autoarts.h.
Referenced by abs_nlteFromRaw(), ARTS::Method::abs_nlteFromRaw(), ARTS::Method::AtmFieldsCalc(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), nlte_fieldFromRaw(), ARTS::Method::nlte_fieldFromRaw(), rtp_nlteFromRaw(), and ARTS::Method::rtp_nlteFromRaw().
npages()
Index ARTS::Var::npages (Workspace & ws) inline noexcept
Number of elements in 3rd lowest dimension of a Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7570 of file autoarts.h.
Referenced by ARTS::Method::npagesGet(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
nrows()
Index ARTS::Var::nrows (Workspace & ws) inline noexcept
Number of rows (elements in 2nd lowest dimension) of a Matrix or Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7577 of file autoarts.h.
Referenced by ARTS::Method::MatrixSetConstant(), ARTS::Method::nrowsGet(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
nshelves()
Index ARTS::Var::nshelves (Workspace & ws) inline noexcept
Number of elements in 5th lowest dimension of a Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7584 of file autoarts.h.
Referenced by ARTS::Method::nshelvesGet(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
NumericCreate()
Numeric ARTS::Var::NumericCreate (Workspace & ws, const Group::Numeric & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Numeric
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Numeric inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12073 of file autoarts.h.
References Workspace::add_wsv_inplace().
nvitrines()
Index ARTS::Var::nvitrines (Workspace & ws) inline noexcept
Number of elements in 6th lowest dimension of a Tensor.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7591 of file autoarts.h.
Referenced by ARTS::Method::nvitrinesGet(), ARTS::Method::Tensor6SetConstant(), and ARTS::Method::Tensor7SetConstant().
oem_diagnostics()
Vector ARTS::Var::oem_diagnostics (Workspace & ws) inline noexcept
Basic diagnostics of an OEM type inversion.
This is a vector of length 5, having the elements (0-based index): 0: Convergence status, with coding 0 = converged 1 = max iterations reached 2 = max gamma of LM reached 9 = some error when calling inversion_iterate_agenda 99 = too high start cost. 1: Start value of cost function. 2: End value of cost function. 3: End value of y-part of cost function. 4: Number of iterations used.
See WSM OEM for a definition of "cost". Values not calculated are set to NaN.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7613 of file autoarts.h.
Referenced by ARTS::Method::OEM().
oem_errors()
ArrayOfString ARTS::Var::oem_errors (Workspace & ws) inline noexcept
Errors encountered during OEM execution.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7620 of file autoarts.h.
Referenced by ARTS::Method::OEM().
output_file_format()
String ARTS::Var::output_file_format (Workspace & ws) inline noexcept
Output file format.
This variable sets the format for output files. It could be set to "ascii" for plain xml files, "zascii" for zipped xml files, or "binary".
To change the value of this variable use the workspace methods output_file_formatSetAscii*, output_file_formatSetZippedAscii, and output_file_formatSetBinary*
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7635 of file autoarts.h.
Referenced by ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), ARTS::Method::output_file_formatSetAscii(), ARTS::Method::output_file_formatSetBinary(), ARTS::Method::output_file_formatSetZippedAscii(), ARTS::Method::ppathWriteXMLPartial(), ARTS::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Method::WriteXML(), and ARTS::Method::WriteXMLIndexed().
p_grid()
Vector ARTS::Var::p_grid (Workspace & ws) inline noexcept
The pressure grid.
The pressure levels on which the atmospheric fields are defined. This variable must always be defined. The grid must be sorted in decreasing order, with no repetitions.
No gap between the lowermost pressure level and the surface is allowed. The uppermost pressure level defines the practical upper limit of the atmosphere as vacuum is assumed above.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: Pa
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7658 of file autoarts.h.
Referenced by abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), ARTS::Agenda::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), ARTS::Method::atm_gridsFromZRaw(), AtmFieldPerturb(), ARTS::Method::AtmFieldPerturb(), AtmFieldPerturbAtmGrids(), ARTS::Method::AtmFieldPerturbAtmGrids(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), check_retrieval_grids(), chk_atm_field(), chk_atm_grids(), chk_pnd_field_raw_only_in_cloudbox(), chk_scat_species_field(), clear_rt_vars_at_gp(), cloud_ppath_update3D(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoOptimizeReverse(), ARTS::Method::cloudbox_field_monoOptimizeReverse(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxSetAutomatically(), ARTS::Method::cloudboxSetAutomatically(), cloudboxSetFullAtm(), ARTS::Method::cloudboxSetFullAtm(), cloudboxSetManually(), ARTS::Method::cloudboxSetManually(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), FieldFromGriddedField(), ARTS::Method::FieldFromGriddedField(), get_gasoptprop(), get_gp_atmgrids_to_rq(), get_gp_rq_to_atmgrids(), get_paroptprop(), get_ppath_atmvars(), get_ppath_transmat(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), GriddedFieldPRegrid(), ARTS::Method::GriddedFieldPRegrid(), GriddedFieldPRegridHelper(), GriddedFieldZToPRegrid(), ARTS::Method::GriddedFieldZToPRegrid(), heating_ratesFromIrradiance(), ARTS::Method::heating_ratesFromIrradiance(), IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexNumberOfAtmosphericPoints(), interp_cloud_coeff1D(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), itw2p(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), jacobianAddAbsSpecies(), ARTS::Method::jacobianAddAbsSpecies(), jacobianAddMagField(), ARTS::Method::jacobianAddMagField(), jacobianAddNLTE(), ARTS::Method::jacobianAddNLTE(), jacobianAddNLTEs(), ARTS::Method::jacobianAddNLTEs(), jacobianAddScatSpecies(), ARTS::Method::jacobianAddScatSpecies(), jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSpecialSpecies(), jacobianAddTemperature(), ARTS::Method::jacobianAddTemperature(), jacobianAddWind(), ARTS::Method::jacobianAddWind(), line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), main(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), p_gridDensify(), ARTS::Method::p_gridDensify(), p_gridFromGasAbsLookup(), ARTS::Method::p_gridFromGasAbsLookup(), ARTS::Method::p_gridFromZRaw(), ARTS::Method::p_gridRefine(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), PFromZSimple(), ARTS::Method::PFromZSimple(), ARTS::Agenda::Method::PFromZSimple(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), ppath_calc(), ppath_start_stepping(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), rte_pos2gridpos(), run_cdisort(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), ybatchMetProfiles(), ybatchMetProfilesClear(), z_at_lat_2d(), z_at_latlon(), ARTS::Method::z_fieldFromHSE(), ZFromPSimple(), ARTS::Method::ZFromPSimple(), and ARTS::Agenda::Method::ZFromPSimple().
p_grid_orig()
Vector ARTS::Var::p_grid_orig (Workspace & ws) inline noexcept
The original pressure grid before optimization.
This variable is used to interpolate cloudbox_field back to its original size after the calculation with OptimizeDoitPressureGrid. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: Pa
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7674 of file autoarts.h.
Referenced by cloudbox_field_monoOptimizeReverse(), ARTS::Method::cloudbox_field_monoOptimizeReverse(), OptimizeDoitPressureGrid(), and ARTS::Method::OptimizeDoitPressureGrid().
p_hse()
Numeric ARTS::Var::p_hse (Workspace & ws) inline noexcept
Reference pressure calculation of hydrostatic equilibrium.
The altitude specified by this pressure is used as the reference when calculating hydrostatic equilibrium. That is, the geometrical altitude at this pressure is not changed.
Usage: Set by the user.
Unit: Pa
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7689 of file autoarts.h.
Referenced by ARTS::Method::z_fieldFromHSE().
particle_bulkprop_field()
Tensor4 ARTS::Var::particle_bulkprop_field (Workspace & ws) inline noexcept
Container for various data that describes scattering bulk properties.
The number and order of bulk properties is free, as long as the data are consistent with the content of particle_bulkprop_names.
The data shall be given on the standard atmospheric grids. When actually used, this variable must have zeros at all positions outside and at the border of the cloudbox.
Dimensions: [ particle_bulkprop_names, p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7705 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), particle_bulkprop_fieldClip(), ARTS::Method::particle_bulkprop_fieldClip(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
particle_bulkprop_names()
ArrayOfString ARTS::Var::particle_bulkprop_names (Workspace & ws) inline noexcept
Identification of the data in particle_bulkprop_field.
This variable assigns a name to each field in particle_bulkprop_field. The naming is totally free. If two fields are given the same name, the first one will be selected.
Dimensions: length should match book-dimension of particle_bulkprop_field
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7718 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), particle_bulkprop_fieldClip(), ARTS::Method::particle_bulkprop_fieldClip(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
particle_masses()
Matrix ARTS::Var::particle_masses (Workspace & ws) inline noexcept
The mass of individual particles (or bulks).
Each row corresponds to a scattering element (i.e. an element in scat_data*). The user is free to define different mass categories and assign a mass for each category. Each column of particle_masses corresponds to such a mass category. A scattering element can have a non-zero mass for more than one category.
For example, if you work with clouds, your mass categories could be ice and liquid, corresponding to IWC and LWC, respectively. The mass of particles inside the melting layer, having a mixed phase, could be divided between the two columns of the matrix.
Shall either be empty, or have a row size consistent with the scattering variables (scat_data, pnd_field).
Usage: Set by the user.
Unit: kg
Dimensions: [number of scattering elements, number of mass categories]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7745 of file autoarts.h.
Referenced by cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudboxOff(), ARTS::Method::cloudboxOff(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), particle_massesFromMetaData(), ARTS::Method::particle_massesFromMetaData(), particle_massesFromMetaDataSingleCategory(), and ARTS::Method::particle_massesFromMetaDataSingleCategory().
pha_mat()
Tensor4 ARTS::Var::pha_mat (Workspace & ws) inline noexcept
Ensemble averaged phase matrix.
This workspace variable represents the actual physical phase matrix (averaged over all scattering elements) for given propagation directions. It is calculated in the method pha_matCalc.
See ARTS user guide (AUG) for further information. Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Output of the method pha_matCalc
Unit: m^2
Dimensions: [za_grid, aa_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7766 of file autoarts.h.
Referenced by FouComp_1ScatElem(), pha_mat_1ScatElem(), pha_mat_Bulk(), pha_mat_NScatElems(), pha_mat_ScatSpecBulk(), pha_matCalc(), and ARTS::Method::pha_matCalc().
pha_mat_doit()
Tensor7 ARTS::Var::pha_mat_doit (Workspace & ws) inline noexcept
Ensemble averaged phase matrix for DOIT calculation.
This workspace variable represents the actual physical phase matrix (averaged over all scattering elements) for given incident and propagation directions. It is calculated in the method DoitScatteringDataPrepare.
See ARTS user guide (AUG) for further information. Usage: Output of the method pha_matCalc
Unit: m^2
Dimensions: [T,za_grid, aa_grid, za_grid, aa_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7785 of file autoarts.h.
Referenced by ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), and ARTS::Method::OptimizeDoitPressureGrid().
pha_mat_spt()
Tensor5 ARTS::Var::pha_mat_spt (Workspace & ws) inline noexcept
Phase matrix for all individual scattering elements.
This variable contains the elements of phase matrix for all individual scattering elements for given propagation directions. It is the calculated in the agenda pha_mat_spt_agenda. The elements of the phase matrix are calculated from the single scattering data.
See ARTS user guide (AUG) for further information.
Usage: Input and Output of the pha_mat_sptFrom* methods
Unit: m^2
Dimensions: [number of scattering elements, za_grid, aa_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7806 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), and ARTS::Method::pha_matCalc().
pha_mat_spt_agenda()
Agenda ARTS::Var::pha_mat_spt_agenda (Workspace & ws) inline noexcept
Agenda calculates the phase matrix for individual scattering elements.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7835 of file autoarts.h.
Referenced by ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), and ARTS::Agenda::Define::pha_mat_spt_agenda().
pha_mat_sptDOITOpt()
ArrayOfTensor7 ARTS::Var::pha_mat_sptDOITOpt (Workspace & ws) inline noexcept
Interpolated phase matrix.
This variable contains the data of the phase matrix in the scattering frame interpolated on the actual frequency (the variable is used inside doit_mono_agenda) and also interpolated on all possible scattering angles following from all combinations of za_grid* and aa_grid.
Usage: Input of the method pha_mat_sptFromDataDOITOpt
Unit: m^2
Dimensions: [number of scattering elements] [T, za_grid, aa_grid, za_grid, aa_grid, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7828 of file autoarts.h.
Referenced by ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), pha_mat_sptFromDataDOITOpt(), and ARTS::Method::pha_mat_sptFromDataDOITOpt().
planet_rotation_period()
Numeric ARTS::Var::planet_rotation_period (Workspace & ws) inline noexcept
The sidereal rotation period of the planet.
This is time that it takes for the planet to complete one revolution around its axis of rotation relative to the stars. For Earth, this is a value roughly 4 min less than 24 h.
A negative value signifies a retrograde rotation, i.e. opposite to the rotation of Earth. Unit: s
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7850 of file autoarts.h.
Referenced by ARTS::Method::wind_u_fieldIncludePlanetRotation().
pnd_agenda_array()
ArrayOfAgenda ARTS::Var::pnd_agenda_array (Workspace & ws) inline noexcept
Mapping of particle bulk properties to number density data.
The length of this agenda array shall match the size of scat_species. That is there is a "pnd-agenda" associated with each scattering species.
In short, each agenda takes some bulk property data as input, and returns particle number densities for all scattering elements of the species. See further pnd_agenda_input and associated variables.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7864 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), and pnd_fieldCalcFromParticleBulkProps().
pnd_agenda_array_input_names()
ArrayOfArrayOfString ARTS::Var::pnd_agenda_array_input_names (Workspace & ws) inline noexcept
Naming of all input expected by pnd_agenda_array.
This variable contains pnd_agenda_input_names for each agenda element in pnd_agenda_array.
Dimension: [ n_scattering_species ][ n_input_variables ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7876 of file autoarts.h.
Referenced by ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), RadarOnionPeelingTableCalc(), and ARTS::Method::RadarOnionPeelingTableCalc().
pnd_agenda_input()
Matrix ARTS::Var::pnd_agenda_input (Workspace & ws) inline noexcept
The variable input to one element of pnd_agenda_array.
The column dimension corresponds to the input to the underlying particle size distribution method. For example, the first column can hold ice water content values, and the second one temperature data.
Temperatures are handled by pnd_agenda_input_t and shall not be included in this variable.
Each row corresponds to a position. That is, the methods in the pnd-agendas are expected to process multiple points in one call.
Dimensions: [ n_points, n_input_variables ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7896 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), pnd_fieldCalcFromParticleBulkProps(), psd_mgd_mass_and_something(), psd_mgd_smm_common(), psd_mono_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), psdFieldEtAl07(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), psdModifiedGamma(), ARTS::Method::psdModifiedGamma(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
pnd_agenda_input_names()
ArrayOfString ARTS::Var::pnd_agenda_input_names (Workspace & ws) inline noexcept
Naming of (existing or expected) data in pnd_agenda_input.
The strings of this variable refer to the corresponding column in pnd_agenda_input*.
Dimension: [ n_input_variables ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7908 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), ARTS::Method::psdModifiedGamma(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
pnd_agenda_input_t()
Vector ARTS::Var::pnd_agenda_input_t (Workspace & ws) inline noexcept
Temperature input to one element of pnd_agenda_array.
This WSV works as pnd_agenda_input but holds a specific quantity, temperature.
Each element corresponds to a position. That is, the methods in the pnd-agendas are expected to process multiple points in one call.
Dimensions: [ n_points ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7923 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), pnd_fieldCalcFromParticleBulkProps(), psd_mgd_mass_and_something(), psd_mgd_smm_common(), psd_mono_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), psdFieldEtAl07(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), psdModifiedGamma(), ARTS::Method::psdModifiedGamma(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
pnd_data()
Matrix ARTS::Var::pnd_data (Workspace & ws) inline noexcept
Particle number density values for a set of points.
The variable contains particle number density data for one scattering species. The row dimension corresponds to different positions, in the same way as pnd_agenda_input is defined.
Dimensions: [ n_points, n_scattering_elements ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7936 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::pnd_agenda_array(), pnd_agenda_arrayExecute(), pnd_fieldCalcFromParticleBulkProps(), pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), and ARTS::Method::pndFromPsdBasic().
pnd_field()
Tensor4 ARTS::Var::pnd_field (Workspace & ws) inline noexcept
Particle number density field.
This variable holds the particle number density fields for all scattering elements being read in the WSMs ScatElementsPndAndScatAdd* or ScatSpeciesPndAndScatAdd and interpolated to the calculation grids p_grid, lat_grid, and lon_grid* inside the cloudbox. An alternative method to create pnd_field* is pnd_fieldCalcFromParticleBulkProps.
Total number and order of scattering elements in pnd_field and (the flattened) scat_data has to be identical.
Note: To ensure that no particles exist outside the cloudbox, pnd_field* is required to be 0 at its outer limits (corresponding to the cloudbox_limits).
Usage: Set by user or output of pnd_fieldCalcFromParticleBulkProps
Unit: m^-3
Size: [number of scattering elements, (cloudbox_limits[1] - cloudbox_limits[0]) +1, (cloudbox_limits[3] - cloudbox_limits[2]) +1, (cloudbox_limits[5] - cloudbox_limits[4]) +1 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7966 of file autoarts.h.
Referenced by cloud_atm_vars_by_gp(), cloud_fieldsCalc(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxOff(), ARTS::Method::cloudboxOff(), cloudy_rt_vars_at_gp(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), get_ppath_cloudvars(), get_ppath_transmat(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Method::pha_matCalc(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), pnd_fieldExpand1D(), ARTS::Method::pnd_fieldExpand1D(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ScatSpeciesMerge(), and ARTS::Method::ScatSpeciesMerge().
pnd_field_raw()
ArrayOfGriddedField3 ARTS::Var::pnd_field_raw (Workspace & ws) inline noexcept
The particle number density field raw data.
This variable contains the particle number density data for all considered scattering elements. pnd_field_raw is an Array of GriddedField3. It includes one GriddedField3 for each scattering element, which contains both the data and the corresponding grids.
Usage: Set by the user. Input to methods ScatElementsPndAndScatAdd and ScatSpeciesPndAndScatAdd*
Unit: m^-3
Size: Array[number of scattering elementst] GriddedField3 [number of pressure levels] [number of latitudes] [number of longitudes] [number of pressure levels, number of latitudes, number of longitudes]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 7990 of file autoarts.h.
Referenced by chk_pnd_data(), chk_pnd_field_raw_only_in_cloudbox(), chk_pnd_raw_data(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsPndAndScatAdd(), ScatSpeciesInit(), ARTS::Method::ScatSpeciesInit(), ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ybatchMetProfiles(), and ybatchMetProfilesClear().
pnd_size_grid()
Vector ARTS::Var::pnd_size_grid (Workspace & ws) inline noexcept
The particle sizes associated with pnd_data.
This variable holds the size of each scattering element considered. Size can be defined differently, depending on particle size distribution used. Most common choices should by equivalent diameter, maximum diameter and mass.
Dimension: [ n_sizes ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8004 of file autoarts.h.
Referenced by pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), and ARTS::Method::pndFromPsdBasic().
ppath()
Ppath ARTS::Var::ppath (Workspace & ws) inline noexcept
The propagation path for one line-of-sight.
This variable describes the total (pencil beam) propagation path for a given combination of starting point and line-of-sight. The path is described by a data structure of type Ppath. This structure contains also additional fields to faciliate the calculation of spectra and interpolation of the atmospheric fields.
The data struture is too extensive to be described here, but it is described carefully in the ARTS user guide (AUG). Use the index to find where the data structure, Ppath, for propagation paths is discussed. It is listed as a subentry to "data structures".
Usage: Output from ppath_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8024 of file autoarts.h.
Referenced by defocusing_general(), defocusing_sat2sat(), diy_from_path_to_rgrids(), DoitGetIncoming(), DoitGetIncoming1DAtm(), emission_from_propmat_field(), error_if_limb_ppath(), find_tanpoint(), ARTS::Agenda::Execute::geo_pos_agenda(), ARTS::Agenda::geo_pos_agenda_empty(), geo_pos_agendaExecute(), geo_posEndOfPpath(), ARTS::Method::geo_posEndOfPpath(), geo_posLowestAltitudeOfPpath(), ARTS::Method::geo_posLowestAltitudeOfPpath(), geo_posWherePpathPassesZref(), ARTS::Method::geo_posWherePpathPassesZref(), get_iy(), get_iy_of_background(), get_ppath_atmvars(), get_ppath_cloudvars(), get_ppath_f(), get_ppath_transmat(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iySurfaceFastem(), iySurfaceRtpropAgenda(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MCRadar(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_append(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_init_structure(), ppath_set_background(), ppath_start_1d(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_step_geom_1d(), ppath_step_geom_2d(), ppath_step_geom_3d(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ppath_what_background(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ppathWriteXMLPartial(), ARTS::Method::ppathWriteXMLPartial(), rte_pos_losMoveToStartOfPpath(), ARTS::Method::rte_pos_losMoveToStartOfPpath(), rtmethods_jacobian_finalisation(), rtmethods_unit_conversion(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), TangentPointExtract(), ARTS::Method::TangentPointExtract(), TangentPointPrint(), ARTS::Method::TangentPointPrint(), xml_read_from_stream(), xml_write_to_stream(), and yRadar().
ppath_agenda()
Agenda ARTS::Var::ppath_agenda (Workspace & ws) inline noexcept
Agenda calculating complete propagation paths.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8031 of file autoarts.h.
Referenced by iyIndependentBeamApproximation(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Agenda::Execute::ppath_agenda(), ARTS::Agenda::Define::ppath_agenda(), ARTS::Agenda::ppath_agenda_follow_sensor_los(), ARTS::Agenda::ppath_agenda_plane_parallel(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppathCalc(), ppathCalc(), and ppathCalcFromAltitude().
ppath_field()
ArrayOfPpath ARTS::Var::ppath_field (Workspace & ws) inline noexcept
An array meant to build up the necessary geometries for radiative field calculations.
Can be ordered or not
Size: user-defined
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8043 of file autoarts.h.
Referenced by line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), and sorted_index_of_ppath_field().
ppath_inside_cloudbox_do()
Index ARTS::Var::ppath_inside_cloudbox_do (Workspace & ws) inline noexcept
Flag to perform ray tracing inside the cloudbox.
Standard propagation path calculations stop at the boundary of the cloudbox, or stop directly if started inside the cloudbox. This WSV allows scattering methods to obtain propagation paths inside the cloudbox. Hence, this variable is for internal usage primarily.
Usage: For communication between modules of arts.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8057 of file autoarts.h.
Referenced by cloudboxOff(), ARTS::Method::cloudboxOff(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_stepping(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppath_lmax()
Numeric ARTS::Var::ppath_lmax (Workspace & ws) inline noexcept
Maximum length between points describing propagation paths.
See ppath_stepGeometric for a description of this variable.
Usage: Ppath methods such as ppath_stepGeometric.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8068 of file autoarts.h.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Agenda::Execute::ppath_step_agenda(), ppath_step_agendaExecute(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), and ARTS::Method::spectral_radiance_fieldExpandCloudboxField().
ppath_lraytrace()
Numeric ARTS::Var::ppath_lraytrace (Workspace & ws) inline noexcept
Maximum length of ray tracing steps when determining propagation paths.
See ppath_stepRefractionBasic for a description of this variable.
Usage: Refraction ppath methods such as ppath_stepRefractionBasic.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8080 of file autoarts.h.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::ppath_agenda(), ARTS::Agenda::ppath_agenda_plane_parallel(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Agenda::Execute::ppath_step_agenda(), ARTS::Agenda::ppath_step_agenda_geometric_path(), ppath_step_agendaExecute(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), and ppathStepByStep().
ppath_step()
Ppath ARTS::Var::ppath_step (Workspace & ws) inline noexcept
A propagation path step.
The main intention of this variable is communication with the agenda ppath_step_agenda*.
See ppath_step_agenda for more information on this variable and the calculation of propagation paths. Or read the chapter on propagation paths in the ARTS user guide.
Usage: In/output to/from ppath_step_agenda.
Members: See AUG.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8098 of file autoarts.h.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), cloud_RT_no_background(), cloud_RT_surface(), interp_cloud_coeff1D(), is_inside_cloudbox(), MCGeneral(), mcPathTraceRadar(), MCRadar(), ppath_calc(), ARTS::Agenda::Execute::ppath_step_agenda(), ppath_step_agendaExecute(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), and ppath_stepRefractionBasic().
ppath_step_agenda()
Agenda ARTS::Var::ppath_step_agenda (Workspace & ws) inline noexcept
Agenda calculating a propagation path step.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8105 of file autoarts.h.
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), iyMC(), MCGeneral(), mcPathTraceRadar(), MCRadar(), ppath_calc(), ARTS::Agenda::Execute::ppath_step_agenda(), ARTS::Agenda::Define::ppath_step_agenda(), ARTS::Agenda::ppath_step_agenda_geometric_path(), ARTS::Agenda::ppath_step_agenda_refracted_path(), ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), and ppathStepByStep().
PpathCreate()
Ppath ARTS::Var::PpathCreate (Workspace & ws, const Group::Ppath & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Ppath
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Ppath inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12092 of file autoarts.h.
References Workspace::add_wsv_inplace().
ppvar_f()
Matrix ARTS::Var::ppvar_f (Workspace & ws) inline noexcept
Doppler adjusted frequencies along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ number of frequencies, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8118 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_iy()
Tensor3 ARTS::Var::ppvar_iy (Workspace & ws) inline noexcept
iy-values along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ number of frequencies, stokes_dim, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8131 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_unit_conversion(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_mag()
Matrix ARTS::Var::ppvar_mag (Workspace & ws) inline noexcept
Magnetic field along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ 3, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8144 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_nlte()
EnergyLevelMap ARTS::Var::ppvar_nlte (Workspace & ws) inline noexcept
Non-LTE temperatures/ratios along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ number of non-lte temperatures, 1, 1, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8157 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_optical_depth()
Matrix ARTS::Var::ppvar_optical_depth (Workspace & ws) inline noexcept
The optical depth between the sensor and each point of the propagation path.
Returned as the one-way optical depth even in the case of radar simulations. Just a scalar value, i.e. no polarisation information is provided.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ ppath.np, f_grid]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8174 of file autoarts.h.
Referenced by ppvar_optical_depthFromPpvar_trans_cumulat(), and ARTS::Method::ppvar_optical_depthFromPpvar_trans_cumulat().
ppvar_p()
Vector ARTS::Var::ppvar_p (Workspace & ws) inline noexcept
Pressure along the propagation path.
ppvar stands for propagation path variable. The variables named in is way describe the atmosphere and its properties at each point of the propagation path
Dimension: [ ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8189 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_pnd()
Matrix ARTS::Var::ppvar_pnd (Workspace & ws) inline noexcept
PND values along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ number of scattering elements, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8202 of file autoarts.h.
Referenced by iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), and iyTransmissionStandard().
ppvar_t()
Vector ARTS::Var::ppvar_t (Workspace & ws) inline noexcept
Temperature along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8215 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_trans_cumulat()
Tensor4 ARTS::Var::ppvar_trans_cumulat (Workspace & ws) inline noexcept
The transmittance between the sensor and each point of the propagation path.
Returned as the one-way transmittance even in the case of radar simulations.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ ppath.np, f_grid, stokes_dim, stokes_dim ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8231 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ppvar_optical_depthFromPpvar_trans_cumulat(), ARTS::Method::ppvar_optical_depthFromPpvar_trans_cumulat(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_trans_partial()
Tensor4 ARTS::Var::ppvar_trans_partial (Workspace & ws) inline noexcept
The transmittance between each point along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ ppath.np, f_grid, stokes_dim, stokes_dim ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8244 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_vmr()
Matrix ARTS::Var::ppvar_vmr (Workspace & ws) inline noexcept
VMR values along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ number of abs. species, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8257 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
ppvar_wind()
Matrix ARTS::Var::ppvar_wind (Workspace & ws) inline noexcept
Winds along the propagation path.
See ppvar_p for a general description of WSVs of ppvar-type.
Dimension: [ 3, ppath.np ]
Usage: Output of radiative transfer methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8270 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
PropagationMatrixCreate()
PropagationMatrix ARTS::Var::PropagationMatrixCreate (Workspace & ws, const Group::PropagationMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an PropagationMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] PropagationMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12111 of file autoarts.h.
References Workspace::add_wsv_inplace().
propmat_clearsky()
PropagationMatrix ARTS::Var::propmat_clearsky (Workspace & ws) inline noexcept
This contains the absorption coefficients for one point in the atmosphere (one set of pressure, temperature, magnetic field, and VMR values).
Dimensions: [naa, nza, nf, f(stokes_dim)]
Unit: 1/m
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8283 of file autoarts.h.
Referenced by abs_vecAddGas(), ARTS::Method::abs_vecAddGas(), cloud_ppath_update1D_planeparallel(), ext_matAddGas(), ARTS::Method::ext_matAddGas(), opt_prop_sum_propmat_clearsky(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddFromAbsCoefPerSpecies(), propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), propmat_clearskyForceNegativeToZero(), ARTS::Method::propmat_clearskyForceNegativeToZero(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), propmat_clearskyZero(), ARTS::Method::propmat_clearskyZero(), and zeeman_on_the_fly().
propmat_clearsky_agenda()
Agenda ARTS::Var::propmat_clearsky_agenda (Workspace & ws) inline noexcept
Agenda calculating the absorption coefficient matrices.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8290 of file autoarts.h.
Referenced by clear_rt_vars_at_gp(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudy_rt_vars_at_gp(), DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), field_of_propagation(), get_gasoptprop(), get_ppath_transmat(), get_stepwise_clearsky_propmat(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), iyMC(), iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MCGeneral(), mcPathTraceRadar(), MCRadar(), nlte_fieldForSingleSpeciesNonOverlappingLines(), particle_bulkpropRadarOnionPeeling(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), ARTS::Agenda::Define::propmat_clearsky_agenda(), ARTS::Method::propmat_clearsky_agenda_checkedCalc(), propmat_clearsky_agenda_checkedCalc(), ARTS::Agenda::propmat_clearsky_agenda_on_the_fly_zeeman(), ARTS::Agenda::propmat_clearsky_agenda_xsec_agenda(), run_cdisort(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
propmat_clearsky_agenda_checked()
Index ARTS::Var::propmat_clearsky_agenda_checked (Workspace & ws) inline noexcept
OK-flag for propmat_clearsky_agenda.
Set by propmat_clearsky_agenda_checkedCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8299 of file autoarts.h.
Referenced by abs_speciesAdd(), ARTS::Method::abs_speciesAdd(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), abs_speciesDefineAll(), ARTS::Method::abs_speciesDefineAll(), abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesDefineAllInScenario(), abs_speciesSet(), ARTS::Method::abs_speciesSet(), ARTS::Method::propmat_clearsky_agenda_checkedCalc(), propmat_clearsky_agenda_checkedCalc(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), ScatElementsToabs_speciesAdd(), and ARTS::Method::ScatElementsToabs_speciesAdd().
propmat_clearsky_field()
Tensor7 ARTS::Var::propmat_clearsky_field (Workspace & ws) inline noexcept
Gas absorption field.
Contains the (polarized) gas absorption coefficients for all species as a function of f_grid, p_grid, lat_grid, and lon_grid.
This is mainly for testing and plotting gas absorption. For RT calculations, gas absorption is calculated or extracted locally, therefore there is no need to store a global field. But this variable is handy for easy plotting of absorption vs. pressure, for example.
Unit: 1/m
Dimensions: [species, f_grid, stokes_dim, stokes_dim, p_grid, lat_grid, lon_grid]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8318 of file autoarts.h.
Referenced by propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), WriteMolTau(), and ARTS::Method::WriteMolTau().
psd_data()
Matrix ARTS::Var::psd_data (Workspace & ws) inline noexcept
Particle size distribution values for a set of points.
The variable contains particle size distribution data for one scattering species. The row dimension corresponds to different positions, in the same way as pnd_agenda_input is defined.
Dimensions: [ n_points, n_scattering_elements ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8331 of file autoarts.h.
Referenced by pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), ARTS::Method::pndFromPsdBasic(), psd_mgd_mass_and_something(), psd_mono_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), psdModifiedGamma(), ARTS::Method::psdModifiedGamma(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
psd_size_grid()
Vector ARTS::Var::psd_size_grid (Workspace & ws) inline noexcept
The particle sizes associated with psd_data.
This variable holds the size of each scattering element considered. Size can be defined differently, depending on particle size distribution used. Most common choices should by equivalent diameter, maximum diameter and mass.
Dimension: [ n_sizes ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8345 of file autoarts.h.
Referenced by pndFromPsd(), ARTS::Method::pndFromPsd(), pndFromPsdBasic(), ARTS::Method::pndFromPsdBasic(), psd_mgd_mass_and_something(), psd_mono_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdMilbrandtYau05(), ARTS::Method::psdMilbrandtYau05(), psdModifiedGamma(), ARTS::Method::psdModifiedGamma(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdSeifertBeheng06(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), and ARTS::Method::psdWangEtAl16().
QuantumIdentifierCreate()
QuantumIdentifier ARTS::Var::QuantumIdentifierCreate (Workspace & ws, const Group::QuantumIdentifier & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an QuantumIdentifier
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] QuantumIdentifier inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12130 of file autoarts.h.
References Workspace::add_wsv_inplace().
radiance_field()
Tensor5 ARTS::Var::radiance_field (Workspace & ws) inline noexcept
Radiance field.
Radiant flux received by a surface per unit solid angle and per unit area for each hemisphere. The last dimension denotes the hemispheres. The first component is the downward radiance and the second component is the upward radiance.
Units: W / (m^2 sr)
Size: [p_grid, lat_grid, lon_grid, N_za, N_aa
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8364 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), DOBatchCalc(), irradiance_fieldFromRadiance(), and ARTS::Method::irradiance_fieldFromRadiance().
RadiationVectorCreate()
RadiationVector ARTS::Var::RadiationVectorCreate (Workspace & ws, const Group::RadiationVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an RadiationVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] RadiationVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12149 of file autoarts.h.
References Workspace::add_wsv_inplace().
range_bins()
Vector ARTS::Var::range_bins (Workspace & ws) inline noexcept
The range bins of an active instrument.
The bins are assumed to cover a range without gaps, and the bins are defined by their edges. That is, the length of this vector is the number of bins + 1.
The bins can potentially be defined in two ways, by altitude or time. See the method you are using, if this variable shall hold time or altitude (or maybe both options are treated).
Unit: m or s
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8381 of file autoarts.h.
Referenced by MCRadar(), ARTS::Method::MCRadar(), yRadar(), and ARTS::Method::yRadar().
RationalCreate()
Rational ARTS::Var::RationalCreate (Workspace & ws, const Group::Rational & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Rational
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Rational inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12168 of file autoarts.h.
References Workspace::add_wsv_inplace().
refellipsoid()
Vector ARTS::Var::refellipsoid (Workspace & ws) inline noexcept
Reference ellipsoid.
This vector specifies the shape of the reference ellipsoid. The vector must have length 2, where the two elements are: 1: Equatorial radius. 2: The eccentricity. The eccentricity is sqrt(1-b*b/a*a) where a and b are equatorial and polar radius, respectively. If the eccentricity is set to 0, an average radius should be used instead of the equatorial one.
The eccentricity must be 0 for 1D calculations, as a spherical Earth is implied by setting atmosphere_dim to 1. For 2D, the selected ellipsoid parameters should be selected according to cross-section between the real ellipsoid and the 2D plane considered. That is the applied ellipsoid shall have een converted to match the internal treatment of 2D cases. For 3D, models can be used, such as WGS84.
Usage: Set by the user.
Size: [ 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8407 of file autoarts.h.
Referenced by atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), line_refellipsoid_intersect(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), plevel_slope_2d(), plevel_slope_3d(), pos2refell_r(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_step_geom_1d(), ppath_step_geom_2d(), ppath_step_geom_3d(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refell2d(), refell2r(), refellipsoidEarth(), ARTS::Method::refellipsoidEarth(), refellipsoidEuropa(), ARTS::Method::refellipsoidEuropa(), refellipsoidForAzimuth(), ARTS::Method::refellipsoidForAzimuth(), refellipsoidGanymede(), ARTS::Method::refellipsoidGanymede(), refellipsoidIo(), ARTS::Method::refellipsoidIo(), refellipsoidJupiter(), ARTS::Method::refellipsoidJupiter(), refellipsoidMars(), ARTS::Method::refellipsoidMars(), refellipsoidMoon(), ARTS::Method::refellipsoidMoon(), refellipsoidOrbitPlane(), ARTS::Method::refellipsoidOrbitPlane(), refellipsoidVenus(), ARTS::Method::refellipsoidVenus(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_poslosFromECEF(), ARTS::Method::rte_poslosFromECEF(), rte_poslosFromGeodetic(), ARTS::Method::rte_poslosFromGeodetic(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromECEF(), sensor_poslosFromGeodetic(), ARTS::Method::sensor_poslosFromGeodetic(), specular_losCalc(), ARTS::Method::specular_losCalc(), surf_radius_at_l(), VectorZtanToZa1D(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), y_geoToGeodetic(), ARTS::Method::y_geoToGeodetic(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), and ARTS::Method::z_fieldFromHSE().
refr_index_air()
Numeric ARTS::Var::refr_index_air (Workspace & ws) inline noexcept
Real part of the refractive index of air.
The variable contains the refractive index summed over all relevant constituents, at one position in the atmosphere. This refractive is related to the phase velocity. See also refr_index_air_group.
Unit: 1
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8420 of file autoarts.h.
Referenced by get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), ppath_step_refr_1d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), ARTS::Method::refr_index_airFreeElectrons(), refr_index_airInfraredEarth(), ARTS::Method::refr_index_airInfraredEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), refraction_ppc(), and VectorZtanToZaRefr1D().
refr_index_air_agenda()
Agenda ARTS::Var::refr_index_air_agenda (Workspace & ws) inline noexcept
Agenda calculating the refractive index of air.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8427 of file autoarts.h.
Referenced by get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Agenda::Execute::refr_index_air_agenda(), ARTS::Agenda::Define::refr_index_air_agenda(), ARTS::Method::VectorZtanToZaRefr1D(), and VectorZtanToZaRefr1D().
refr_index_air_group()
Numeric ARTS::Var::refr_index_air_group (Workspace & ws) inline noexcept
Group index of refractivity.
This variable is defined as the ratio between group velocity and the speed of ligh in vacuum. That is, it is defined as the "standard" refractive index, but refers to the group velocity instead of the phase velocity. See also refr_index_air.
Unit: 1
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8441 of file autoarts.h.
Referenced by get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), ppath_step_refr_1d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), ARTS::Method::refr_index_airFreeElectrons(), refr_index_airInfraredEarth(), ARTS::Method::refr_index_airInfraredEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), and VectorZtanToZaRefr1D().
relmat_per_band()
ArrayOfArrayOfMatrix ARTS::Var::relmat_per_band (Workspace & ws) inline noexcept
Relaxation matrix per band per pressure level.
Dimensions: [pressures][band][n_linex, nlines] Units: Hz/Pa in HWHM
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8451 of file autoarts.h.
relmat_type_per_band()
ArrayOfIndex ARTS::Var::relmat_type_per_band (Workspace & ws) inline noexcept
Used to set the type of line mixing relaxation matrix that will be calculated.
Supported types by index: 0: Hartmann-Tran type relaxation matrix. 1: Linear type relaxation matrix.
Dimensions: [number of bands]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8465 of file autoarts.h.
retrieval_checked()
Index ARTS::Var::retrieval_checked (Workspace & ws) inline noexcept
Flag indicating completeness and consistency of retrieval setup.
Unit: Boolean
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8474 of file autoarts.h.
Referenced by ARTS::Method::retrievalDefClose(), and retrievalDefClose().
retrieval_eo()
Vector ARTS::Var::retrieval_eo (Workspace & ws) inline noexcept
The estimated error in the retrieval due to uncertainty in the observations.
The vector contains the square roots of the diagonal elements of the covariance matrix of the error due to measurement noise, S_m in Rodgers' book.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8485 of file autoarts.h.
Referenced by retrievalErrorsExtract(), and ARTS::Method::retrievalErrorsExtract().
retrieval_ss()
Vector ARTS::Var::retrieval_ss (Workspace & ws) inline noexcept
The estimated error in the retrieval due to limited resolution of the observation system.
The vector contains the square roots of the diagonal elements of the covariance matrix of the smoothing error, S_s in Rodgers' book.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8497 of file autoarts.h.
Referenced by retrievalErrorsExtract(), and ARTS::Method::retrievalErrorsExtract().
rt_integration_option()
String ARTS::Var::rt_integration_option (Workspace & ws) inline noexcept
Switch between integration approaches for radiative transfer steps.
See each WSM using this varaible as input for available options.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8506 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), and ARTS::Method::spectral_radiance_fieldExpandCloudboxField().
rte_alonglos_v()
Numeric ARTS::Var::rte_alonglos_v (Workspace & ws) inline noexcept
Velocity along the line-of-sight to consider for a RT calculation.
This variable gives the velocity of the imaginary detector in monochromatic pencil beam calculations. The relevant velocity is the projection along the line-of-sight (ie. total velocity shall not be given). A positive value means a movement of the detector in the same direction as the line-of-sight.
This variable is required to include Doppler effects due to velocities of the observer, relative the centre of the coordinate system used that is fixed to the planets centre point.
Unit: [ m/s ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8525 of file autoarts.h.
Referenced by get_ppath_f(), get_stepwise_frequency_grid(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), and ARTS::Method::spectral_radiance_fieldExpandCloudboxField().
rte_los()
Vector ARTS::Var::rte_los (Workspace & ws) inline noexcept
A line-of-sight for (complete) radiative transfer calculations.
This variable gives the observation direction for monochromatic pencil beam calculations. Hence, it is the line-of-sight at the end point of the propagation path.
For 1D and 2D cases, rte_los is a vector of length 1 holding the zenith angle. For 3D, the length of the vector is 2, where the additional element is the azimuthal angle. These angles are defined in the ARTS user guide (AUG). Look in the index for "zenith angle" and "azimuthal angle".
Usage: See above.
Units: [ degree, degree ]
Size: [ 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8548 of file autoarts.h.
Referenced by calc_incang(), chk_rte_los(), cloud_RT_surface(), cloudy_rt_vars_at_gp(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), get_iy(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Method::iyCalc(), iyCalc(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), mcPathTraceRadar(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_stepping(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_losSet(), ARTS::Method::rte_losSet(), rte_pos_losMoveToStartOfPpath(), ARTS::Method::rte_pos_losMoveToStartOfPpath(), rte_poslosFromECEF(), ARTS::Method::rte_poslosFromECEF(), rte_poslosFromGeodetic(), ARTS::Method::rte_poslosFromGeodetic(), Sample_los(), sensor_losGeometricFromSensorPosToOtherPositions(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
rte_pos()
Vector ARTS::Var::rte_pos (Workspace & ws) inline noexcept
A geographical position for starting radiative transfer calculations.
This variable gives the observation position for monochromatic pencil beam calculations. Hence, it is the end point of the propagation path.
This variable is a vector with a length equalling the atmospheric dimensionality. The first element is the geometrical altitude. Element 2 is the latitude and element 3 is the longitude.
Usage: See above.
Units: [ m, degree, degree ]
Size: [ atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8569 of file autoarts.h.
Referenced by chk_rte_pos(), cloud_RT_surface(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), get_iy(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_radar_agenda(), iy_radar_agendaExecute(), ARTS::Method::iyCalc(), iyCalc(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), mcPathTraceRadar(), pos2refell_r(), ARTS::Agenda::Execute::ppath_agenda(), ppath_agendaExecute(), ppath_calc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_stepping(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFixedLstep(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), rte_pos2gridpos(), rte_pos_losMoveToStartOfPpath(), ARTS::Method::rte_pos_losMoveToStartOfPpath(), rte_poslosFromECEF(), ARTS::Method::rte_poslosFromECEF(), rte_poslosFromGeodetic(), ARTS::Method::rte_poslosFromGeodetic(), rte_posSet(), ARTS::Method::rte_posSet(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
rte_pos2()
Vector ARTS::Var::rte_pos2 (Workspace & ws) inline noexcept
A second geographical position to define the geometry for radiative transfer calculations.
This variable is used when the propagation path is defined by two positions, instead of a position (rte_pos) and a line-of-sight (rte_los). That is, this variable basically replaces rte_los for the cases of consideration. In practice, rte_los is determined by finding the propagation path between rte_pos and rte_pos2.
As rte_pos with the exception that a "latitude" must also be specified for 1D. This is the angular distance to rte_pos, where this distance is defined as the 2D-"latitude".
Usage: See above.
Units: [ m, degree, degree ]
Size: [ atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8593 of file autoarts.h.
Referenced by get_iy(), get_iy_of_background(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Agenda::Execute::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Agenda::Execute::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Method::iyCalc(), iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Agenda::Execute::ppath_agenda(), ARTS::Agenda::ppath_agenda_follow_sensor_los(), ARTS::Agenda::ppath_agenda_plane_parallel(), ppath_agendaExecute(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppathCalc(), ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), spectral_radiance_fieldClearskyPlaneParallel(), and spectral_radiance_fieldExpandCloudboxField().
rtp_los()
Vector ARTS::Var::rtp_los (Workspace & ws) inline noexcept
Line-of-sight at a radiative transfer point.
This variable holds a local line-of-sight. The angles of this vector are defined as for rte_los.
The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ degree, degree ]
Size: [ 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8612 of file autoarts.h.
Referenced by get_iy_of_background(), ARTS::Agenda::Execute::iy_cloudbox_agenda(), iy_cloudbox_agendaExecute(), ARTS::Agenda::Execute::iy_space_agenda(), ARTS::Agenda::iy_space_agenda_cosmic_background(), iy_space_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Agenda::Execute::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), ARTS::Agenda::propmat_clearsky_agenda_xsec_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), specular_losCalc(), ARTS::Method::specular_losCalc(), specular_losCalcNoTopography(), ARTS::Method::specular_losCalcNoTopography(), surf_albedoCalc(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), and zeeman_on_the_fly().
rtp_mag()
Vector ARTS::Var::rtp_mag (Workspace & ws) inline noexcept
Magnetic field at a radiative transfer point.
See mag_u_field etc. for a definition of the different components. For this variable the components are put together and thus defines magnetic field vector. Hence, this is a vector of length three, even if any of the input fields is set to be empty.
The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: T
Size: [ u-component, v-component, w-component ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8633 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::propmat_clearsky_agenda(), ARTS::Agenda::propmat_clearsky_agenda_xsec_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), and zeeman_on_the_fly().
rtp_nlte()
EnergyLevelMap ARTS::Var::rtp_nlte (Workspace & ws) inline noexcept
NLTE temperature/ratio at a radiative transfer point.
This vector variable can hold the NLTE temperature/ratio. It is intended mainly for communication with various methods and agendas, such as methods and agendas calculating absorption coefficients. The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ K/# ] Size: [ NLTE levels, 1, 1, 1 ] or [ 0, 0, 0, 0 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8651 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), rtp_nlteFromRaw(), ARTS::Method::rtp_nlteFromRaw(), and zeeman_on_the_fly().
rtp_pos()
Vector ARTS::Var::rtp_pos (Workspace & ws) inline noexcept
Position of a radiative transfer point.
This vector is defined as rte_pos, but holds a position along the propgation path, or the start point for new paths, in contrast to rte_pos that is position of the (imaginary) detector.
The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ m, degree, degree ]
Size: [ atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8671 of file autoarts.h.
Referenced by diy_from_pos_to_rgrids(), get_iy_of_background(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), InterpGriddedField2ToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Execute::iy_cloudbox_agenda(), iy_cloudbox_agendaExecute(), ARTS::Agenda::Execute::iy_space_agenda(), ARTS::Agenda::iy_space_agenda_cosmic_background(), iy_space_agendaExecute(), ARTS::Agenda::Execute::iy_surface_agenda(), ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), iy_surface_agendaExecute(), ARTS::Agenda::Execute::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), iyb_calc_body(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), specular_losCalc(), ARTS::Method::specular_losCalc(), specular_losCalcNoTopography(), ARTS::Method::specular_losCalcNoTopography(), surf_albedoCalc(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_typeInterpTypeMask(), ARTS::Method::surface_typeInterpTypeMask(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), telsemSurfaceTypeLandSea(), and ARTS::Method::telsemSurfaceTypeLandSea().
rtp_pressure()
Numeric ARTS::Var::rtp_pressure (Workspace & ws) inline noexcept
Pressure at a radiative transfer point.
This scalar variable holds the local pressure.
The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ Pa ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8687 of file autoarts.h.
Referenced by AbsInputFromRteScalars(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), refr_index_airInfraredEarth(), ARTS::Method::refr_index_airInfraredEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), and zeeman_on_the_fly().
rtp_temperature()
Numeric ARTS::Var::rtp_temperature (Workspace & ws) inline noexcept
Temperature at a radiative transfer point.
This scalar variable can hold the local temperature. It is intended mainly for communication with various methods and agendas, such as methods and agendas calculating absorption coefficients. The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ K ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8704 of file autoarts.h.
Referenced by AbsInputFromRteScalars(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), refr_index_airInfraredEarth(), ARTS::Method::refr_index_airInfraredEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), Sample_los(), ARTS::Agenda::Execute::spt_calc_agenda(), spt_calc_agendaExecute(), and zeeman_on_the_fly().
rtp_vmr()
Vector ARTS::Var::rtp_vmr (Workspace & ws) inline noexcept
Absorption species abundances for radiative transfer calculations.
This vector variable holds the local abundance of the constituents included in abs_species.
The WSV is used as input to methods and agendas calculating radiative properties for a given conditions.
Usage: Communication variable.
Units: [ Differ between the elements, can be VMR, kg/m3 or #/m3. ]
Size: Should match abs_species.nelem()
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8723 of file autoarts.h.
Referenced by AbsInputFromRteScalars(), cloud_ppath_update1D_planeparallel(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), ARTS::Agenda::Execute::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFromLookup(), propmat_clearskyAddHitranLineMixingLines(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyAddZeeman(), ARTS::Agenda::Execute::refr_index_air_agenda(), refr_index_air_agendaExecute(), ARTS::Method::refr_index_airFreeElectrons(), refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), and zeeman_on_the_fly().
scat_data()
ArrayOfArrayOfSingleScatteringData ARTS::Var::scat_data (Workspace & ws) inline noexcept
Array of single scattering data.
As scat_data_raw, but with frequency grids and dimensions reduced to the RT's f_grid or a single frequency entry. Also, temperature grid or dimensions can be reduced to a single entry, meaning no temperature interpolation is done for the respective data.
Standard approach to derive scat_data is to use scat_dataCalc to derive it from scat_data_raw.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8737 of file autoarts.h.
Referenced by check_disort_input(), chk_scattering_data(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudboxOff(), ARTS::Method::cloudboxOff(), cloudy_rt_vars_at_gp(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), get_angs(), get_paroptprop(), get_parZ(), get_ppath_transmat(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), is_anyptype_nonTotRan(), iyHybrid(), ARTS::Method::iyHybrid(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), opt_prop_NScatElems(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), pha_mat_NScatElems(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), pnd_fieldZero(), ARTS::Method::pnd_fieldZero(), pndFromPsd(), ARTS::Method::pndFromPsd(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), RadarOnionPeelingTableCalc(), ARTS::Method::RadarOnionPeelingTableCalc(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), run_cdisort(), Sample_los(), scat_data_checkedCalc(), ARTS::Method::scat_data_checkedCalc(), ARTS::Method::scat_data_monoCalc(), scat_data_monoExtract(), ARTS::Method::scat_data_monoExtract(), scat_dataCalc(), ARTS::Method::scat_dataCalc(), scat_dataCheck(), ARTS::Method::scat_dataCheck(), scat_dataReduceT(), ARTS::Method::scat_dataReduceT(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), ybatchMetProfiles(), and ARTS::Method::ybatchMetProfiles().
scat_data_checked()
Index ARTS::Var::scat_data_checked (Workspace & ws) inline noexcept
OK-flag for scat_data.
Relevant checks are performed by *scat_data_checkedCalc. Only the value 1 is taken as OK.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8747 of file autoarts.h.
Referenced by check_disort_input(), cloudboxOff(), ARTS::Method::cloudboxOff(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::DoitCalc(), DoitCalc(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), ARTS::Method::iyCalc(), iyCalc(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pndFromPsd(), ARTS::Method::pndFromPsd(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), scat_data_checkedCalc(), ARTS::Method::scat_data_checkedCalc(), ScatSpeciesInit(), ARTS::Method::ScatSpeciesInit(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), and ARTS::Method::yCalcAppend().
scat_data_mono()
ArrayOfArrayOfSingleScatteringData ARTS::Var::scat_data_mono (Workspace & ws) inline noexcept
Monochromatic single scattering data.
This variable holds the single scattering properties for all scattering species and scattering elements for a specified frequency. It can be calculated from scat_data using scat_data_monoCalc, which interpolates scat_data to the required frequency.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8759 of file autoarts.h.
Referenced by ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), get_stepwise_scattersky_propmat(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), ARTS::Method::scat_data_monoCalc(), scat_data_monoExtract(), and ARTS::Method::scat_data_monoExtract().
scat_data_raw()
ArrayOfArrayOfSingleScatteringData ARTS::Var::scat_data_raw (Workspace & ws) inline noexcept
Array of raw single scattering data.
This variable holds the single scattering properties for all scattering elements, organized according to their assignment to a scattering species. scat_data_raw entries can be derived from precalculated data files using the methods ScatElementsPndAndScatAdd, ScatSpeciesPndAndScatAdd*, or ScatSpeciesScatAndMetaRead or can be calculated using scat_data_singleTmatrix.
This may be used in combination with scat_meta
Usage: Method ouput.
Members: SingleScatteringData: Enum[ptype attribute] String[description] Vector[f_grid] Vector[T_grid] Vector[za_grid] Vector[aa_grid] Tensor7[pha_mat_data] [f_grid, T_grid, za_grid, aa_grid, za_grid, aa_grid, matrix_element] ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ scattered incoming Tensor5[ext_mat_data] [f_grid, T_grid, za_grid, aa_grid, matrix_element] Tensor5[abs_vec_data] [f_grid, T_grid, za_grid, aa_grid, matrix_element]
Dimensions: [number of scattering species][number of scattering elements]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8795 of file autoarts.h.
Referenced by cloudboxOff(), ARTS::Method::cloudboxOff(), scat_dataCalc(), ARTS::Method::scat_dataCalc(), ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsPndAndScatAdd(), ScatElementsSelect(), ARTS::Method::ScatElementsSelect(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ScatSpeciesExtendTemperature(), ARTS::Method::ScatSpeciesExtendTemperature(), ScatSpeciesInit(), ARTS::Method::ScatSpeciesInit(), ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), and ARTS::Method::ScatSpeciesScatAndMetaRead().
scat_data_single()
SingleScatteringData ARTS::Var::scat_data_single (Workspace & ws) inline noexcept
Structure for the single scattering data.
Comprises the single scattering data of a single scattering element. See ARTS user guide for further information.
Usage: Set by the user.
Dimensions: SingleScatteringData Enum[ptype attribute] String[description] Vector[f_grid] Vector[T_grid] Vector[za_grid] Vector[aa_grid] Tensor7[pha_mat_data] [f_grid, T_grid, za_grid, aa_grid, za_grid, aa_grid, matrix_element] ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^ scattered incoming Tensor5[ext_mat_data] [f_grid, T_grid, za_grid, aa_grid, matrix_element] Tensor5[abs_vec_data] [f_grid, T_grid, za_grid, aa_grid, matrix_element]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8823 of file autoarts.h.
Referenced by chk_scat_data(), scat_data_singleTmatrix(), ARTS::Method::scat_data_singleTmatrix(), ScatElementsPndAndScatAdd(), and ScatElementsToabs_speciesAdd().
scat_lat_index()
Index ARTS::Var::scat_lat_index (Workspace & ws) inline noexcept
Latitude index for scattering calculations.
This variable is used in methods used for computing scattering properties of scattering elements like opt_prop_sptFromData and pha_matCalc*. It holds the information about the position for which the scattering calculations are done.
Usage: Input to the methods spt_calc_agenda, pha_mat_spt_agenda*
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8838 of file autoarts.h.
Referenced by opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Method::pha_matCalc(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
scat_lon_index()
Index ARTS::Var::scat_lon_index (Workspace & ws) inline noexcept
Longitude index for scattering calculations.
This variable is used in methods used for computing scattering properties of scattering elements like opt_prop_sptFromData and pha_matCalc*. It holds the information about the position for which the scattering calculations are done.
Usage: Input to the methods spt_calc_agenda, pha_mat_spt_agenda*
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8853 of file autoarts.h.
Referenced by opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Method::pha_matCalc(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
scat_meta()
ArrayOfArrayOfScatteringMetaData ARTS::Var::scat_meta (Workspace & ws) inline noexcept
An Array of scattering meta data (scat_meta_single).
The array holds the meta data for all scattering elements. For a description of the meta data contents refer to the documentation of scat_data_single.
Corresponding to scat_data, it is organized in terms of scattering species (i.e., one sub-array per scattering species holding one scat_meta_single* instance per scattering element assigned to this scattering species). It is primarily used for particle size and shape distribution calculations using pnd_fieldCalcFromParticleBulkProps. It is also applied for deducing microphysical characterizations of scattering species, e.g., by particle_massesFromMetaData.
Note: This array must contain as many elements as scat_data (on both array levels).
Usage: Set by the user.
Dimensions: [scattering species][scattering elements] For more details, see also scat_meta_single.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8880 of file autoarts.h.
Referenced by chk_scattering_data(), ExtractFromMetaSingleScatSpecies(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), particle_massesFromMetaData(), ARTS::Method::particle_massesFromMetaData(), particle_massesFromMetaDataSingleCategory(), ARTS::Method::particle_massesFromMetaDataSingleCategory(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), psd_mono_common(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), RadarOnionPeelingTableCalc(), ARTS::Method::RadarOnionPeelingTableCalc(), ScatElementsSelect(), ARTS::Method::ScatElementsSelect(), ScatSpeciesInit(), ARTS::Method::ScatSpeciesInit(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ScatSpeciesSizeMassInfo(), and ARTS::Method::ScatSpeciesSizeMassInfo().
scat_meta_single()
ScatteringMetaData ARTS::Var::scat_meta_single (Workspace & ws) inline noexcept
Structure for the scattering meta data.
This variable holds the scattering meta data for a single scattering element (see AUG for definition). Scattering meta data comprises the microphysical description of the scattering element as necessary to relate single scattering properties with mass density or flux fields. That is, e.g., in order to handle the scattering element in particle size (and shape) distribution calculations.
For a definition of the structure members see below.
Members of Numeric type can be flagged as unknown by setting them to NAN. This will cause a runtime error in case the parameter is needed in the calculation, but will be ignored otherwise.
Usage: Set by the user.
Members: description [String] Description: Free-form description of the scattering element, holding information deemed of interest by the user but not covered by other structure members (and not used within ARTS). source [String] Description: Free-form description of the source of the data, e.g., Mie, T-Matrix, or DDA calculation or a database or a literature source. refr_index [String] Description: Free-form description of the underlying complex refractive index data, e.g., a literature source. mass [Numeric] Unit: [kg] Description: The mass of the scattering element. diameter_max [Numeric] Unit: [m] Description: The maximum diameter (or dimension) of the scattering element, defined by the circumferential sphere diameter of the element. Note that this parameter is only used by some size distributions; it does not have a proper meaning if the scattering element represents an ensemble of differently sized particles. diameter_volume_equ [Numeric] Unit: [m] Description: The volume equivalent sphere diameter of the scattering element, i.e., the diameter of a sphere with the same volume. For nonspherical particles, volume refers to the volume of the particle-forming substance, not that of the circumferential sphere (which can be derived from diameter_max). If the particle consists of a mixture of materials, the substance encompasses the complete mixture. E.g., the substance of 'soft' ice particles includes both the ice and the air. diameter_area_equ_aerodynamical [Numeric] Unit: [m] Description: The area equivalent sphere diameter of the scattering element, i.e., the diameter of a sphere with the same cross-sectional area. Here, area refers to the aerodynamically relevant area, i.e., the cross-sectional area perpendicular to the direction of fall. Similarly to volume in the definition of diameter_volume_equ, for non-spherical and mixed-material particles, area refers to the area covered by the substance mixture of the particle.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8945 of file autoarts.h.
Referenced by ARTS::Method::scat_data_singleTmatrix().
scat_p_index()
Index ARTS::Var::scat_p_index (Workspace & ws) inline noexcept
Pressure index for scattering calculations.
This variable is used in methods used for computing scattering properties of scattering elements like opt_prop_sptFromData and pha_matCalc*. It holds the information about the location for which the scattering calculations are done.
Usage: Input to the methods spt_calc_agenda, pha_mat_spt_agenda*
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8960 of file autoarts.h.
Referenced by opt_prop_bulkCalc(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Method::pha_matCalc(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().
scat_species()
ArrayOfString ARTS::Var::scat_species (Workspace & ws) inline noexcept
Array of Strings defining the scattering species to consider.
Each String contains the information to connect scattering species (e.g., hydrometeor) atmospheric fields with the microphysical information like size and shape distributions. The strings follow the following structure with individual elements separated by dashes:
scattering species name [String] the name of the scattering species' atmospheric field. Free form, but is matched to atm_fields_compact fields by their names. Common are, e.g., IWC (ice water content), LWC (liquid water content), RR (rain rate), and SR (snow rate).
particle size distribution [String]: the size distribution function/parametrization to apply. For currently possible PSDs see pnd_fieldCalcFromParticleBulkProps.
Example: [''IWC-MH97'', ''LWC-H98_STCO'', ...]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 8983 of file autoarts.h.
Referenced by cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), cloudboxOff(), ARTS::Method::cloudboxOff(), get_pointers_for_scat_species(), iyHybrid(), ARTS::Method::iyHybrid(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), RadarOnionPeelingTableCalc(), ARTS::Method::RadarOnionPeelingTableCalc(), ScatElementsSelect(), ARTS::Method::ScatElementsSelect(), ScatSpeciesExtendTemperature(), ARTS::Method::ScatSpeciesExtendTemperature(), ScatSpeciesInit(), ARTS::Method::ScatSpeciesInit(), ScatSpeciesMerge(), and ARTS::Method::ScatSpeciesMerge().
scat_species_a()
Numeric ARTS::Var::scat_species_a (Workspace & ws) inline noexcept
Mass-size relationship parameter, for one scattering species.
Some methods require a relationship between mass and particle size, valid for the complete scattering species. A common model for this relationship is: mass(x) = a * x^b, where x is size (that could be Dveq, Dmax or mass) and a/b are parameters.
This WSV is a in the expression above. The WSV matching b is scat_species_b. The WSV matching x is scat_species_x.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9000 of file autoarts.h.
Referenced by psd_mgd_mass_and_something(), psd_mgd_smm_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), psdFieldEtAl07(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdWangEtAl16(), ARTS::Method::psdWangEtAl16(), ScatSpeciesSizeMassInfo(), and ARTS::Method::ScatSpeciesSizeMassInfo().
scat_species_b()
Numeric ARTS::Var::scat_species_b (Workspace & ws) inline noexcept
Mass-size relationship parameter, for one scattering species.
See scat_species_a for details.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9009 of file autoarts.h.
Referenced by psd_mgd_mass_and_something(), psd_mgd_smm_common(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), psdFieldEtAl07(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), psdMcFarquaharHeymsfield97(), ARTS::Method::psdMcFarquaharHeymsfield97(), psdModifiedGammaMass(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdWangEtAl16(), ARTS::Method::psdWangEtAl16(), ScatSpeciesSizeMassInfo(), and ARTS::Method::ScatSpeciesSizeMassInfo().
scat_species_x()
Vector ARTS::Var::scat_species_x (Workspace & ws) inline noexcept
The size grid of one scattering species.
The variable holds the sizes associated with one scattering species. The typical application of these data are as the size grid when calculating particle size distributions.
The user must set this WSV as several quantities can be used as size, such as mass and maximum diamater.
See also scat_species_a, for example usage of this WSV.
Dimension: [number of scattering elements]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9027 of file autoarts.h.
Referenced by ScatSpeciesSizeMassInfo(), and ARTS::Method::ScatSpeciesSizeMassInfo().
ScatteringMetaDataCreate()
ScatteringMetaData ARTS::Var::ScatteringMetaDataCreate (Workspace & ws, const Group::ScatteringMetaData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an ScatteringMetaData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] ScatteringMetaData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12187 of file autoarts.h.
References Workspace::add_wsv_inplace().
sensor_checked()
Index ARTS::Var::sensor_checked (Workspace & ws) inline noexcept
OK-flag for sensor related variables.
This variable flags that sensor variables are defined in a formally and practically correct way. For example, it checks for correct dimensions of sensor_pos and sensor_los.
Shall be set by sensor_checkedCalc. See that WSM for treated WSVs. Only the value 1 is taken as OK.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9041 of file autoarts.h.
Referenced by sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
sensor_description_amsu()
Matrix ARTS::Var::sensor_description_amsu (Workspace & ws) inline noexcept
Sensor description for simple AMSU setup.
This is a compact description of an AMSU-type sensor. The matrix contains one row for each instrument channel. Each row contains three elements: LO position [Hz], offset of the channel center from the LO [Hz], and channel width [Hz].
Usage: Set by the user.
Unit: All entries in Hz.
Size: [number of channels, 3]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9059 of file autoarts.h.
Referenced by sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseSimpleAMSU(), and ARTS::Method::sensor_responseSimpleAMSU().
sensor_los()
Matrix ARTS::Var::sensor_los (Workspace & ws) inline noexcept
The sensor line-of-sight (LOS) for each measurement block.
Line-of-sights are specified by giving the zenith and azimuth angles. Column 1 holds the zenith angle. This angle is simply the angle between the zenith and LOS directions. For 1D and 3D the valid range is [0 180], while for 2D angles down to -180 degrees are allowed. Negative angles signifies for 2D observations towards lower latitudes, while positive angles means observations towards higher latitudes. Nadir corresponds throughout to 180 degrees.
The azimuth angle is given with respect to the meridian plane. That is, the plane going through the north and south poles. The valid range is [-180,180] where angles are counted clockwise; 0 means that the viewing or propagation direction is north-wise and +90 means that the direction of concern goes eastward.
No azimuth angle shall be specified for 1D and 2D. This angle is in general of no concern for these atmospheric dimensionalities, but matter in some cases, such as with respect to the Doppler shift due to winds. For 1D the azimuth angle is then assumed to be 0 deg, i.e. the sensor is treated to be directed towards North. For 2D, the implied azimuth is 0 or 180, depending of the zenith angle is positive or negative.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: [ degrees, degrees ]
Size: [ number of measurement blocks, 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9098 of file autoarts.h.
Referenced by AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), iyb_calc(), iyb_calc_body(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), rte_poslosFromECEF(), rte_poslosFromGeodetic(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromGeodetic(), ARTS::Method::x2artsSensor(), x2artsSensor(), ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
sensor_los_ecef()
Matrix ARTS::Var::sensor_los_ecef (Workspace & ws) inline noexcept
As sensor_los but matching ECEF coordinates.
For this version of sensor_los, each row shall hold [dx,dy,dz], where dx, dy and dz are the x, y and z components if the line-of-sight directions in ECEF coordinates. [dx,dy,dz] must form a unit vector (i.e. its 2-norm shall be 1).
Probably only useful for 3D.
Usage: Set by the user.
Unit: [ m, m, m ]
Size: [ number of measurement blocks, 3 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9118 of file autoarts.h.
Referenced by rte_poslosFromECEF(), ARTS::Method::rte_poslosFromECEF(), sensor_poslosFromECEF(), and ARTS::Method::sensor_poslosFromECEF().
sensor_los_geodetic()
Matrix ARTS::Var::sensor_los_geodetic (Workspace & ws) inline noexcept
As sensor_los but matching geodetic coordinates.
For this version zenith is defined as the normal of the reference ellipsoid, in contrast to sensor_los zenith is along the direction towards the planets centre.
Probably only useful for 3D.
Usage: Set by the user.
Unit: [ degrees, degrees ]
Size: [ number of measurement blocks, 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9137 of file autoarts.h.
Referenced by rte_poslosFromGeodetic(), ARTS::Method::rte_poslosFromGeodetic(), and ARTS::Method::sensor_poslosFromGeodetic().
sensor_norm()
Index ARTS::Var::sensor_norm (Workspace & ws) inline noexcept
Flag if sensor response should be normalised or not (0 or 1).
If the flag is set to 1 each sensor response is normalised (where applicable). If set to 0 the sensor responses are left as provided.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a sub-entry to "workspace variables".
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9153 of file autoarts.h.
Referenced by sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensorOff(), and ySimpleSpectrometer().
sensor_pol()
Matrix ARTS::Var::sensor_pol (Workspace & ws) inline noexcept
A set of polarisation response angles.
The standard choice to consider the polarisation response of the reciever is by instrument_pol, and this response becomes then part of sensor_response. However, that choice is not possible when the polartisation response changes between measurement blocks, and this variable combined with the yApplySensorPol offers an alternative for such situations. This WSV also allows defintion of an arbitrary polarisation angle.
When applying the polarisation response by yApplySensorPol, this variable complements sensor_pos and sensor_los. This WSV matrix is also a matrix, that shall have the same number of rows as the other two matrices.
The columns of sensor_pol corresponds to the channels/frequencies of the receiver. Each element gives the polarisation angle. A pure vertical response has the angle 0 deg, and pure horisontal 90 deg. If all U values (Stokes element 3) are zero, the sign of the angle does, not matter, and 0 and 180 degrees give the same result. With non-zero U, the result of e.g. -45 and +45 degrees differ.
Note that a receiver with a linear response is assumed. Circular polarisation is not affected by any rotation.
Usage: Set by the user.
Unit: [ degrees ]
Size: [ number of measurement blocks, number of channels/frequencies ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9189 of file autoarts.h.
Referenced by yApplySensorPol(), and ARTS::Method::yApplySensorPol().
sensor_pos()
Matrix ARTS::Var::sensor_pos (Workspace & ws) inline noexcept
The sensor position for each measurement block.
The sensor positions are specified as a matrix, where the number of columns shall be equal to atmosphere_dim. Column 1 shall contain the altitude of the sensor platform, column 2 the latitude and the last column the longitude. The number of rows corresponds to the number of measurement blocks.
Valid range for latitudes in 3D is [-90,90], while for 2D any value is accepted. Accepted range for longitudes are [-360,360].
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user.
Unit: [ m, degrees, degrees ]
Size: [ number of measurement blocks, atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9215 of file autoarts.h.
Referenced by AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), iyb_calc(), iyb_calc_body(), jacobianAddPointingZa(), ARTS::Method::jacobianAddPointingZa(), jacobianAddPolyfit(), ARTS::Method::jacobianAddPolyfit(), jacobianAddSinefit(), ARTS::Method::jacobianAddSinefit(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), rte_poslosFromECEF(), rte_poslosFromGeodetic(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromGeodetic(), VectorZtanToZa1D(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
sensor_pos_ecef()
Matrix ARTS::Var::sensor_pos_ecef (Workspace & ws) inline noexcept
As sensor_pos but using ECEF coordinates.
The sensor position is here specified as earth-centered, earth-fixed (ECEF) coordinates (using standard definition of ECEF).
Probably only useful for 3D.
Column 1, 2 and 3 shall hold x, y and z coordinate, respectively.
Usage: Set by the user.
Unit: [ m, m, m ]
Size: [ number of measurement blocks, atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9235 of file autoarts.h.
Referenced by rte_poslosFromECEF(), ARTS::Method::rte_poslosFromECEF(), sensor_poslosFromECEF(), and ARTS::Method::sensor_poslosFromECEF().
sensor_pos_geodetic()
Matrix ARTS::Var::sensor_pos_geodetic (Workspace & ws) inline noexcept
As sensor_pos but using geodetic coordinates.
For this version the second column shall hold geodetic latitudes, in contrast to sensor_pos where the geocentric system us used. Please note that also the altitude (column 1) differs between the two versions of the variables. Here the altitude is with taken along the local nadir, while for sensor_pos it is taken along the direction towards the planets centre.
Probably only useful for 3D.
Usage: Set by the user.
Unit: [ m, degrees, degrees ]
Size: [ number of measurement blocks, atmosphere_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9257 of file autoarts.h.
Referenced by rte_poslosFromGeodetic(), ARTS::Method::rte_poslosFromGeodetic(), sensor_poslosFromGeodetic(), and ARTS::Method::sensor_poslosFromGeodetic().
sensor_response()
Sparse ARTS::Var::sensor_response (Workspace & ws) inline noexcept
The matrix modelling the total sensor response.
This matrix describes the sensor respons for one measurement block The response is assumed to be identical for each such block.
The matrix is the product of all the individual sensor response matrices. Therefore its dimensions are depending on the total sensor configuration. The sensor_response has to initialised by the sensor_responseInit* method.
Usage: Output/input to the sensor_response... methods.
Units: -
Dimension: See the individual sensor_response... method.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9278 of file autoarts.h.
Referenced by calcBaselineFit(), get_rowindex_for_mblock(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseFillFgrid(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseStokesRotation(), ARTS::Method::sensor_responseStokesRotation(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), and ySimpleSpectrometer().
sensor_response_aa()
Vector ARTS::Var::sensor_response_aa (Workspace & ws) inline noexcept
The relative azimuth angles associated with the output of sensor_response*.
The variable shall not be set manually, it will be set together with sensor_response* by sensor response WSMs.
Usage: Set by sensor response methods.
Unit: [ degrees ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9293 of file autoarts.h.
sensor_response_agenda()
Agenda ARTS::Var::sensor_response_agenda (Workspace & ws) inline noexcept
Agenda providing the sensor response data for a measurement block.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9300 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::sensor_response_agenda(), ARTS::Agenda::Define::sensor_response_agenda(), ARTS::Method::x2artsSensor(), and x2artsSensor().
sensor_response_dlos()
Matrix ARTS::Var::sensor_response_dlos (Workspace & ws) inline noexcept
The relative zenith and azimuth angles associated with the output of sensor_response*.
Definition of angles match mblock_dlos_grid. Works otherwise as sensor_response_f*.
The variable shall not be set manually, it will be set together with sensor_response* by sensor response WSMs.
Usage: Set by sensor response methods.
Unit: [ degrees ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9318 of file autoarts.h.
Referenced by sensor_aux_vectors(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), and ySimpleSpectrometer().
sensor_response_dlos_grid()
Matrix ARTS::Var::sensor_response_dlos_grid (Workspace & ws) inline noexcept
The zenith and azimuth angles associated with sensor_response.
A variable for communication between sensor response WSMs. Matches initially mblock_dlos_grid, but is later adjusted according to the sensor specifications. Only defined when a common grid exists. Values are here not repeated as in sensor_response_dlos
Usage: Set by sensor response methods.
Unit: [ degrees ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9334 of file autoarts.h.
Referenced by calcBaselineFit(), jacobianAddPolyfit(), ARTS::Method::jacobianAddPolyfit(), jacobianAddSinefit(), ARTS::Method::jacobianAddSinefit(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), sensor_aux_vectors(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseFillFgrid(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseStokesRotation(), ARTS::Method::sensor_responseStokesRotation(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), and ySimpleSpectrometer().
sensor_response_f()
Vector ARTS::Var::sensor_response_f (Workspace & ws) inline noexcept
The frequencies associated with the output of sensor_response.
This vector gives the frequency for each element of the measurement vector produced inside one measurement block. The frequencies of the total measurement vector, y, are obtained by repeating these frequencies n times, where n is the number of measurement blocks (e.g. the number of rows in sensor_pos).
The variable shall not be set manually, it will be set together with sensor_response* by sensor response WSMs.
Usage: Set by sensor response methods.
Unit: [ Hz ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9354 of file autoarts.h.
Referenced by sensor_aux_vectors(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseFillFgrid(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseIF2RF(), ARTS::Method::sensor_responseIF2RF(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), and ySimpleSpectrometer().
sensor_response_f_grid()
Vector ARTS::Var::sensor_response_f_grid (Workspace & ws) inline noexcept
The frequency grid associated with sensor_response.
A variable for communication between sensor response WSMs. Matches initially f_grid, but is later adjusted according to the sensor specifications. Only defined when a common grid exists. Values are here not repeated as in sensor_response_f
Usage: Set by sensor response methods.
Unit: [ Hz ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9370 of file autoarts.h.
Referenced by calcBaselineFit(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), sensor_aux_vectors(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseFillFgrid(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseIF2RF(), ARTS::Method::sensor_responseIF2RF(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseStokesRotation(), ARTS::Method::sensor_responseStokesRotation(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), and ySimpleSpectrometer().
sensor_response_pol()
ArrayOfIndex ARTS::Var::sensor_response_pol (Workspace & ws) inline noexcept
The polarisation states associated with the output of sensor_response*.
Works basically as sensor_response_f.
See instrument_pol for coding of polarisation states.
The variable shall not be set manually, it will be set together with sensor_response* by sensor response WSMs.
Usage: Set by sensor response methods.
Unit: [ - ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9389 of file autoarts.h.
Referenced by sensor_aux_vectors(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), and ySimpleSpectrometer().
sensor_response_pol_grid()
ArrayOfIndex ARTS::Var::sensor_response_pol_grid (Workspace & ws) inline noexcept
The "polarisation grid" associated with sensor_response.
A variable for communication between sensor response WSMs. It is initially 1:stokes_dim, but can later adjusted according to the sensor specifications. Only defined when a common grid exists.
See instrument_pol for coding of polarisation states.
Usage: Set by sensor response methods.
Unit: [ - ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9406 of file autoarts.h.
Referenced by calcBaselineFit(), jacobianAddPolyfit(), ARTS::Method::jacobianAddPolyfit(), jacobianAddSinefit(), ARTS::Method::jacobianAddSinefit(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPolyfit(), ARTS::Method::jacobianCalcPolyfit(), jacobianCalcSinefit(), ARTS::Method::jacobianCalcSinefit(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), sensor_aux_vectors(), ARTS::Agenda::Execute::sensor_response_agenda(), sensor_response_agendaExecute(), sensor_responseAntenna(), ARTS::Method::sensor_responseAntenna(), sensor_responseBackend(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), sensor_responseFillFgrid(), ARTS::Method::sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responseMixer(), ARTS::Method::sensor_responseMixer(), sensor_responseMixerBackendPrecalcWeights(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseStokesRotation(), ARTS::Method::sensor_responseStokesRotation(), sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::x2artsSensor(), x2artsSensor(), and ySimpleSpectrometer().
sensor_time()
ArrayOfTime ARTS::Var::sensor_time (Workspace & ws) inline noexcept
The time for each measurement block.
This WSV is used when a time must be assigned to the measurements.
Usage: Set by the user.
Unit: [ UTC date and time ]
Size: [ number of measurement blocks ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9421 of file autoarts.h.
Referenced by jacobianAddPointingZa(), ARTS::Method::jacobianAddPointingZa(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), ARTS::Method::x2artsSensor(), x2artsSensor(), ybatchColdAtmHotAtmCycle(), ARTS::Method::ybatchColdAtmHotAtmCycle(), ybatchTimeAveraging(), and ARTS::Method::ybatchTimeAveraging().
sideband_mode()
String ARTS::Var::sideband_mode (Workspace & ws) inline noexcept
Description of target sideband.
A text string describing which of the two sidebands (of a heterodyne instrument) that can be seen as "main" band. Possible choices are: "lower" : Low frequency sideband shall be considered as target. "upper" : High frequency sideband shall be considered as target.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9435 of file autoarts.h.
Referenced by sensor_responseIF2RF(), and ARTS::Method::sensor_responseIF2RF().
sideband_mode_multi()
ArrayOfString ARTS::Var::sideband_mode_multi (Workspace & ws) inline noexcept
Description of target sideband for a multiple LO receiver.
As sideband_mode but handles an instrument with several LO chains. See further lo_multi and sideband_response_multi. This length of this array must match the size of those WSVs.
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9448 of file autoarts.h.
Referenced by sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), and sensor_responseSimpleAMSU().
sideband_response()
GriddedField1 ARTS::Var::sideband_response (Workspace & ws) inline noexcept
Description of (mixer) sideband response.
This variable describes the response of each sideband of a heterodyne receiver. The response is given as a GriddedField1, with frequency as the grid. The actual data describe the sideband filter function at each frequency grid point. An interpolation is applied to obtain the response for other frequencies.
The frequency grid should be given in terms of IF, with end points symmetrically placed around zero. That is, the grid must contain both negative and positive values. The sideband response (after summation with lo) is not allowed to extend outside the range for which spectral data exist (normally determined by f_grid).
Usage: Set by the user.
Dimensions: GriddedField1: Vector f_grid[N_f] Vector data[N_f]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9474 of file autoarts.h.
Referenced by sensor_responseMixer(), and ARTS::Method::sensor_responseMixer().
sideband_response_multi()
ArrayOfGriddedField1 ARTS::Var::sideband_response_multi (Workspace & ws) inline noexcept
Description of multiple (mixer) sideband responses.
As sideband_response but describes an instrument with multiple mixers. An array element for each LO. The size of this variable and lo_multi* shall match.
Unit: Hz
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9489 of file autoarts.h.
Referenced by sensor_responseGenericAMSU(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), and sensor_responseSimpleAMSU().
SingleScatteringDataCreate()
SingleScatteringData ARTS::Var::SingleScatteringDataCreate (Workspace & ws, const Group::SingleScatteringData & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an SingleScatteringData
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] SingleScatteringData inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12206 of file autoarts.h.
References Workspace::add_wsv_inplace().
SparseCreate()
Sparse ARTS::Var::SparseCreate (Workspace & ws, const Group::Sparse & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Sparse
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Sparse inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12225 of file autoarts.h.
References Workspace::add_wsv_inplace().
SpeciesIsotopologueRatiosCreate()
SpeciesIsotopologueRatios ARTS::Var::SpeciesIsotopologueRatiosCreate (Workspace & ws, const Group::SpeciesIsotopologueRatios & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an SpeciesIsotopologueRatios
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] SpeciesIsotopologueRatios inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12244 of file autoarts.h.
References Workspace::add_wsv_inplace().
specific_heat_capacity()
Tensor3 ARTS::Var::specific_heat_capacity (Workspace & ws) inline noexcept
Specific heat capacity.
It is the heat capacity per unit mass of a material.
Units: K J^-1 kg^-1
Size: [ p_grid, lat_grid, lon_grid]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9505 of file autoarts.h.
Referenced by heating_ratesFromIrradiance(), and ARTS::Method::heating_ratesFromIrradiance().
spectral_irradiance_field()
Tensor5 ARTS::Var::spectral_irradiance_field (Workspace & ws) inline noexcept
Spectral irradiance field.
Spectral irradiance is the radiative power per unit area and unit frequency. The last dimension denotes the hemispheres. The first component denotes the downward direction and the second component denotes the upward direction.
Units: W m^-2 Hz^-1
Size: [ Nf, p_grid, lat_grid, lon_grid, 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9525 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), DOBatchCalc(), spectral_irradiance_fieldFromSpectralRadianceField(), and ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField().
spectral_radiance_field()
Tensor7 ARTS::Var::spectral_radiance_field (Workspace & ws) inline noexcept
Spectral radiance field.
This variable holds a calculation of the radiance field through the atmosphere, for the directions matching za_grid and aa_grid.
Don't confuse this variable with cloudbox_field. That varinale also holds a field of spectral radiances, but is restricted to the cloud box.
Units: W / (m^2 Hz sr)
Size: [f_grid, p_grid, lat_grid, lon_grid, za_grid, aa_grid, stokes_dim ]
Note: For 1D, the size of the latitude, longitude and azimuth dimension (N_aa) are all 1.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9551 of file autoarts.h.
Referenced by DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), ARTS::Agenda::Execute::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), spectral_irradiance_fieldFromSpectralRadianceField(), ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldCopyCloudboxField(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), and ARTS::Method::spectral_radiance_fieldExpandCloudboxField().
specular_los()
Vector ARTS::Var::specular_los (Workspace & ws) inline noexcept
The specular direction (for reflection by a flat surface).
The specular direction as a standard line-of-sight vector, consisting of a zenith and azimuth angle (the later only for 3D).
Units: degrees
Size: [ 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9565 of file autoarts.h.
Referenced by calc_incang(), iySurfaceFastem(), specular_losCalc(), ARTS::Method::specular_losCalc(), specular_losCalcNoTopography(), ARTS::Method::specular_losCalcNoTopography(), surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), and surfaceTessem().
spt_calc_agenda()
Agenda ARTS::Var::spt_calc_agenda (Workspace & ws) inline noexcept
Agenda calculating single scattering properties from the amplitude matrix.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9572 of file autoarts.h.
Referenced by cloud_fieldsCalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), doit_scat_fieldNormalize(), ARTS::Agenda::Execute::spt_calc_agenda(), and ARTS::Agenda::Define::spt_calc_agenda().
src_xsec_per_species()
ArrayOfMatrix ARTS::Var::src_xsec_per_species (Workspace & ws) inline noexcept
Absorption cross sections for the source function for NLTE calculations.
This variable contains absorption cross section xsec individually for each tag group. The Array contains one matrix for each tag group, the matrix format is the same as that of abs_coef.
Dimensions: [abs_species](f_grid, abs_p), or (0, 0) Unit: m^2 (alpha = xsec * n * VMR), where n is total density.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9588 of file autoarts.h.
Referenced by abs_coefCalcFromXsec(), ARTS::Agenda::Execute::abs_xsec_agenda(), abs_xsec_agendaExecute(), abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesInit(), ARTS::Method::abs_xsec_per_speciesInit(), and propmat_clearskyAddXsecAgenda().
stokes_dim()
Index ARTS::Var::stokes_dim (Workspace & ws) inline noexcept
The dimensionality of the Stokes vector (1-4).
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9597 of file autoarts.h.
Referenced by abs_vec_SSD2Stokes(), abs_vecAddGas(), abs_vecTransform(), cloud_fieldsCalc(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_no_background(), cloud_RT_surface(), cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_field_monoSetConst(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq3D(), cloudy_rt_vars_at_gp(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_scat_fieldCalc(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), ext2trans(), ext_mat_case(), ext_mat_SSD2Stokes(), ext_matAddGas(), ext_matFromabs_vec(), ext_matTransform(), field_of_propagation(), FouComp_1ScatElem(), get_iy_of_background(), get_ppath_transmat(), get_stepwise_scattersky_propmat(), get_stepwise_scattersky_source(), get_stepwise_transmission_matrix(), init_ifield(), interp_cloud_coeff1D(), iy_transmitterMultiplePol(), ARTS::Method::iy_transmitterMultiplePol(), iy_transmitterSinglePol(), ARTS::Method::iy_transmitterSinglePol(), ARTS::Method::iyApplyUnit(), iyb_calc(), iyb_calc_body(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), MatrixCBR(), ARTS::Method::MatrixCBR(), MatrixPlanck(), ARTS::Method::MatrixPlanck(), MatrixUnitIntensity(), ARTS::Method::MatrixUnitIntensity(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), met_mm_polarisation_hmatrix(), mueller_rotation(), opt_prop_1ScatElem(), opt_prop_bulkCalc(), opt_prop_NScatElems(), opt_prop_ScatSpecBulk(), opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), opt_prop_sum_propmat_clearsky(), pha_mat_1ScatElem(), pha_mat_labCalc(), pha_mat_NScatElems(), pha_mat_ScatSpecBulk(), pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), pha_matCalc(), pha_matTransform(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFaraday(), propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddParticles(), propmat_clearskyInit(), ARTS::Method::propmat_clearskyInit(), propmat_clearskyZero(), ARTS::Method::propmat_clearskyZero(), rotmat_stokes(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), rte_step_doit_replacement(), Sample_los(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), sensor_responseInit(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), sensor_responsePolarisation(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), sensor_responseStokesRotation(), ARTS::Method::sensor_responseStokesRotation(), sensorOff(), ARTS::Method::sensorOff(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), stokes2pol(), StokesVector::StokesVector(), surface_calc(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_specular_R_and_b(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), xml_read_from_stream(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), ARTS::Method::yRadar(), ySimpleSpectrometer(), and ARTS::Method::ySimpleSpectrometer().
stokes_rotation()
Vector ARTS::Var::stokes_rotation (Workspace & ws) inline noexcept
Rotation of the Stokes H and V directions.
This variable allows to introduce a rotation of the Stokes coordinate system. Such a rotation could be needed to handle the scanning procedure of some instruments, such as AMSU-A. The variable is applied by the sensor_responseStokesRotation WSM.
The rotation is given as an angle for each direction. In general, the number of rotations to be specified follows sensor_response_dlos_grid. In more detail, if no antenna is included or a 1D antenna is used, and the rotation is applied before the antenna is included in sensor_response*, there should be one angle for each row of mblock_dlos_grid*. After inclusion of an antenna response, the relevant number of angles is determined by the rows of antenna_dlos.
It is assumed that the rotation is common for all frequency elements.
Units: degrees
Size: [ number of directions ]
Usage: Set by the user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9625 of file autoarts.h.
Referenced by sensor_responseStokesRotation(), and ARTS::Method::sensor_responseStokesRotation().
StokesVectorCreate()
StokesVector ARTS::Var::StokesVectorCreate (Workspace & ws, const Group::StokesVector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an StokesVector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] StokesVector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12263 of file autoarts.h.
References Workspace::add_wsv_inplace().
StringCreate()
String ARTS::Var::StringCreate (Workspace & ws, const Group::String & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an String
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] String inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12282 of file autoarts.h.
References Workspace::add_wsv_inplace().
surface_complex_refr_index()
GriddedField3 ARTS::Var::surface_complex_refr_index (Workspace & ws) inline noexcept
Complex refractive index of the surface, at a single point.
See complex_refr_index for the expected format and how the data are treated.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9635 of file autoarts.h.
Referenced by ARTS::Method::RT4CalcWithRT4Surface(), surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), surfaceFlatRefractiveIndex(), and ARTS::Method::surfaceFlatRefractiveIndex().
surface_emission()
Matrix ARTS::Var::surface_emission (Workspace & ws) inline noexcept
The emission from the surface.
See specific methods generating surface_emission and the user guide for more information.
Dimensions: [ f_grid, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9647 of file autoarts.h.
Referenced by cloud_RT_surface(), iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), surf_albedoCalc(), surface_calc(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_specular_R_and_b(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), and ARTS::Method::surfaceTessem().
surface_los()
Matrix ARTS::Var::surface_los (Workspace & ws) inline noexcept
Downwelling radiation directions to consider in surface reflection.
The directions are given as a zenith and azimuth angle (the later only for 3D), following the definition of line-of-sights.
Units: degrees
Size: [ any number, 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9661 of file autoarts.h.
Referenced by cloud_RT_surface(), iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), surf_albedoCalc(), surface_calc(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), and ARTS::Method::surfaceTessem().
surface_normal()
Vector ARTS::Var::surface_normal (Workspace & ws) inline noexcept
The normal vector for a point at the surface.
The vector is given as a zenith and azimuth (the later only for 3D) angle, following the definition of line-of-sights. For example, this vector is always [0] for 1D, as there is no surface topography for this atmospheric dimensionality.
Units: degrees
Size: [ 1 or 2 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9677 of file autoarts.h.
Referenced by iySurfaceFastem(), specular_losCalc(), ARTS::Method::specular_losCalc(), specular_losCalcNoTopography(), ARTS::Method::specular_losCalcNoTopography(), surfaceFastem(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), and surfaceTessem().
surface_props_data()
Tensor3 ARTS::Var::surface_props_data (Workspace & ws) inline noexcept
Various surface properties.
A general container for passing data to surface methods. Each surface property shall be specified on the grid set by lat_grid and lon_grid.
The properties are identified by the accompanying variable surface_props_names*.
Size: [ number of props., lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9692 of file autoarts.h.
Referenced by emission_from_propmat_field(), get_iy_of_background(), ARTS::Agenda::Execute::iy_surface_agenda(), iy_surface_agendaExecute(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), surface_props_check(), surface_props_interp(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
surface_props_names()
ArrayOfString ARTS::Var::surface_props_names (Workspace & ws) inline noexcept
Name on surface properties found in surface_props_data.
Each string names a property in surface_props_data. The user is free to include data with any name, but the surface methods making use of surface_props_data* expect data to be named in a specific way. See the documentation of each method for recognised choices.
Size: [ number of props. ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9706 of file autoarts.h.
Referenced by dsurface_check(), main(), surface_props_check(), surface_props_interp(), SurfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceDummy(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), ARTS::Method::SurfaceFastem(), SurfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), SurfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
surface_reflectivity()
Tensor3 ARTS::Var::surface_reflectivity (Workspace & ws) inline noexcept
Surface reflectivity, for a given position and angle.
This variable describes the surface reflectivity at one position and one incidence angle. It works as surface_scalar_reflectivity but is also defined for vector radiative transfer.
The first dimension of the variable shall either match f_grid or be 1. The later case is interpreted as the reflectivity is the same for all frequencies.
Usage: Input to some surface properties methods.
Dimensions: [ f_grid or 1, stokes_dim, stokes_dim]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9725 of file autoarts.h.
Referenced by ARTS::Method::RT4CalcWithRT4Surface(), surface_reflectivityFromGriddedField6(), ARTS::Method::surface_reflectivityFromGriddedField6(), surfaceFlatReflectivity(), and ARTS::Method::surfaceFlatReflectivity().
surface_rmatrix()
Tensor4 ARTS::Var::surface_rmatrix (Workspace & ws) inline noexcept
The reflection coefficients for the directions given by surface_los* to the direction of interest.
The rows and columns of this tensor holds the reflection coefficient matrix for one frequency and one LOS. The reflection coefficients shall take into accound the angular weighting of the downwelling radiation.
See specific methods generating surface_rmatrix and the user guide for more information.
Usage: Input to methods for surface_rtprop_agenda.
Units: -
Dimensions: [ surface_los, f_grid, stokes_dim, stokes_dim ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9747 of file autoarts.h.
Referenced by cloud_RT_surface(), iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), iySurfaceRtpropCalc(), surf_albedoCalc(), surface_calc(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_scalar_reflectivityFromSurface_rmatrix(), ARTS::Method::surface_scalar_reflectivityFromSurface_rmatrix(), surface_specular_R_and_b(), SurfaceBlackbody(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), and ARTS::Method::surfaceTessem().
surface_rtprop_agenda()
Agenda ARTS::Var::surface_rtprop_agenda (Workspace & ws) inline noexcept
Agenda providing radiative properties of the surface.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9754 of file autoarts.h.
Referenced by cloud_RT_surface(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), DisortCalcWithARTSSurface(), iyMC(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), MCGeneral(), surf_albedoCalc(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Define::surface_rtprop_agenda(), ARTS::Agenda::surface_rtprop_agenda_blackbody_from_atmosphere(), and ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface().
surface_rtprop_agenda_array()
ArrayOfAgenda ARTS::Var::surface_rtprop_agenda_array (Workspace & ws) inline noexcept
Description of surface radiative properties, divided into surface types.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9761 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::surface_rtprop_agenda_array(), ARTS::Method::surface_rtpropCallAgendaX(), and surface_rtpropCallAgendaX().
surface_rtprop_sub_agenda()
Agenda ARTS::Var::surface_rtprop_sub_agenda (Workspace & ws) inline noexcept
Sub-agenda to surface_rtprop_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9768 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), ARTS::Agenda::Define::surface_rtprop_sub_agenda(), ARTS::Method::surfaceSemiSpecularBy3beams(), and surfaceSemiSpecularBy3beams().
surface_rv_rh()
Matrix ARTS::Var::surface_rv_rh (Workspace & ws) inline noexcept
Surface reflectivity, described by rv and rh (power) reflectivities.
This variable describes the surface reflectivity at one position and one incidence angle. For this position and angle, one or multiple combinations of rv and rh are specified, where rv and rh are the reflectivity for vertical and horizontal polarisation, respectively.
This matrix shall always have two columns, where the first column holds rv values, and the second column rh. It is up to the user to make sure that data are put into the correct column, this can not be checked bu the methods using this WSV.
The number of rows shall either match f_grid or be 1. The later case is interpreted as the reflectivities are the same for all frequencies.
Usage: Input to some surface properties methods.
Dimensions: [ f_grid or 1, 2]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9792 of file autoarts.h.
Referenced by surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), surfaceTelsem(), and surfaceTessem().
surface_scalar_reflectivity()
Vector ARTS::Var::surface_scalar_reflectivity (Workspace & ws) inline noexcept
Surface reflectivity, assuming it can be described as a scalar value.
This variable describes the surface reflectivity at one position and one incidence angle. For this position and angle, one or multiple scalar reflectivities are specified.
The length of the vector shall either match f_grid or be 1. The later case is interpreted as the reflectivity is the same for all frequencies (ie. matches a constant vector).
Usage: Input to some surface properties methods.
Dimensions: [ f_grid or 1]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9811 of file autoarts.h.
Referenced by DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), get_disortsurf_props(), ARTS::Method::RT4CalcWithRT4Surface(), surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), surface_scalar_reflectivityFromSurface_rmatrix(), ARTS::Method::surface_scalar_reflectivityFromSurface_rmatrix(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), and ARTS::Method::surfaceLambertianSimple().
surface_skin_t()
Numeric ARTS::Var::surface_skin_t (Workspace & ws) inline noexcept
Surface skin temperature.
This temperature shall be selected considering the radiative properties of the surface, and can differ from the "bulk" temperature.
Usage: Input to methods for surface_rtprop_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9824 of file autoarts.h.
Referenced by cloud_RT_surface(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), FastemStandAlone(), ARTS::Method::FastemStandAlone(), get_disortsurf_props(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), iySurfaceRtpropAgenda(), ARTS::Method::RT4CalcWithRT4Surface(), run_cdisort(), surf_albedoCalc(), ARTS::Agenda::Execute::surface_rtprop_agenda(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), ARTS::Agenda::surface_rtprop_agenda_blackbody_from_atmosphere(), ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface(), surface_rtprop_agendaExecute(), ARTS::Agenda::Execute::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), ARTS::Method::surface_rtpropCallAgendaX(), surface_specular_R_and_b(), surfaceBlackbody(), ARTS::Method::surfaceBlackbody(), surfaceFastem(), ARTS::Method::surfaceFastem(), surfaceFlatReflectivity(), ARTS::Method::surfaceFlatReflectivity(), surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRefractiveIndex(), surfaceFlatRvRh(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), surfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), surfaceSemiSpecularBy3beams(), surfaceTelsem(), ARTS::Method::surfaceTelsem(), surfaceTessem(), and ARTS::Method::surfaceTessem().
surface_type()
Index ARTS::Var::surface_type (Workspace & ws) inline noexcept
Local, single surface type value.
See surface_type_mask for details.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9833 of file autoarts.h.
Referenced by telsemSurfaceTypeLandSea(), and ARTS::Method::telsemSurfaceTypeLandSea().
surface_type_aux()
Numeric ARTS::Var::surface_type_aux (Workspace & ws) inline noexcept
Auxiliary variable to surface_type.
See surface_type_mask for details.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9842 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), ARTS::Agenda::Execute::surface_rtprop_agenda_array(), and surface_rtprop_agenda_arrayExecute().
surface_type_mask()
GriddedField2 ARTS::Var::surface_type_mask (Workspace & ws) inline noexcept
Classification of the surface using a type coding.
This variable gives a description of the surface using a type class coding. A common term for such a variable is "surface mask".
The mask is a latitude and longtide field. The mask values are floating numbers, where the integer part is the type and the remainder can be used to provide auxilary information. In terms of the local variables, the mask values equal surface_type + surface_type_aux.
There is no fixed type coding, it is up to the user to set up a consistent system. The critical point is in the agendas matching each surface type, that are denoted as iy_surface_sub_agendaX where X is the surface_type index.
The surface type can be any integer (>=0) for which a corresponding agenda exists.
Dimensions: GriddedField2: Vector Latitude [N_lat] Vector Longitude [N_lon] Matrix data [N_lat][N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9871 of file autoarts.h.
Referenced by surface_typeInterpTypeMask(), and ARTS::Method::surface_typeInterpTypeMask().
surface_types()
ArrayOfIndex ARTS::Var::surface_types (Workspace & ws) inline noexcept
This and associated WSVs describe a mixture of surface types.
Holds a number of surface_type.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9880 of file autoarts.h.
Referenced by ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), ARTS::Method::surface_rtpropCallAgendaX(), surface_rtpropCallAgendaX(), surface_typeInterpTypeMask(), and ARTS::Method::surface_typeInterpTypeMask().
surface_types_aux()
Vector ARTS::Var::surface_types_aux (Workspace & ws) inline noexcept
Auxiliary variable to surface_types.
Holds a number of surface_type_aux..
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9889 of file autoarts.h.
Referenced by ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), ARTS::Method::surface_rtpropCallAgendaX(), surface_typeInterpTypeMask(), and ARTS::Method::surface_typeInterpTypeMask().
surface_types_weights()
Vector ARTS::Var::surface_types_weights (Workspace & ws) inline noexcept
Auxiliary variable to surface_type.
Holds the relative weight of each surface type.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9898 of file autoarts.h.
Referenced by ARTS::Method::iySurfaceCallAgendaX(), iySurfaceCallAgendaX(), ARTS::Method::surface_rtpropCallAgendaX(), surface_rtpropCallAgendaX(), surface_typeInterpTypeMask(), and ARTS::Method::surface_typeInterpTypeMask().
t_field()
Tensor3 ARTS::Var::t_field (Workspace & ws) inline noexcept
The field of atmospheric temperatures.
This variable gives the atmospheric temperature at each crossing of the pressure, latitude and longitude grids.
The temperature for a point between the grid crossings is obtained by (multi-)linear interpolation of the t_field.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Output of AtmFieldsCalc.
Unit: K
Dimensions: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9921 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), clear_rt_vars_at_gp(), cloud_fieldsCalc(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), emission_from_propmat_field(), get_ppath_atmvars(), get_ppath_transmat(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), interp_cloud_coeff1D(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), ARTS::Method::OptimizeDoitPressureGrid(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFromParticleBulkProps(), ARTS::Agenda::ppath_agenda_plane_parallel(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Agenda::surface_rtprop_agenda_blackbody_from_atmosphere(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), ARTS::Agenda::Execute::water_p_eq_agenda(), water_p_eq_agendaExecute(), water_p_eq_fieldMK05(), ARTS::Method::water_p_eq_fieldMK05(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), and ARTS::Method::z_fieldFromHSE().
t_field_raw()
GriddedField3 ARTS::Var::t_field_raw (Workspace & ws) inline noexcept
Raw data for atmospheric temperatures.
This variable gives the atmospheric temperature as stored in the database for the atmospheric scenarios.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user by choosing a climatology.
Unit: K
Size GriddedField3 [N_p] [N_lat] [N_lon] [N_p, N_lat, N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9945 of file autoarts.h.
Referenced by AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ybatchMetProfiles(), and ybatchMetProfilesClear().
t_surface()
Matrix ARTS::Var::t_surface (Workspace & ws) inline noexcept
The surface temperature.
This variable holds the temperature of the surface at each latitude and longitude grid crossing. The normal case should be that this temperature field is interpolated to obtain surface_skin_t. Accordingly, for 1D cases it could be a better idea to specify surface_skin_t* directly.
These temperature shall be selected considering the radiative properties of the surface, and can differ from the "bulk" temperatures.
Usage: Set by user.
Unit: K
Dimensions: [ lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9968 of file autoarts.h.
Referenced by ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface().
telsem_atlases()
ArrayOfTelsemAtlas ARTS::Var::telsem_atlases (Workspace & ws) inline noexcept
TELSEM 2 emissivity atlases.
Array should be filled with 12 atlases, one for each month. Index 0 is January, index 11 December.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9978 of file autoarts.h.
Referenced by telsem_atlasesReadAscii(), and ARTS::Method::telsem_atlasesReadAscii().
TelsemAtlasCreate()
TelsemAtlas ARTS::Var::TelsemAtlasCreate (Workspace & ws, const Group::TelsemAtlas & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an TelsemAtlas
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] TelsemAtlas inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12301 of file autoarts.h.
References Workspace::add_wsv_inplace().
Tensor3Create()
Tensor3 ARTS::Var::Tensor3Create (Workspace & ws, const Group::Tensor3 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Tensor3
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Tensor3 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12320 of file autoarts.h.
References Workspace::add_wsv_inplace().
Tensor4Create()
Tensor4 ARTS::Var::Tensor4Create (Workspace & ws, const Group::Tensor4 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Tensor4
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Tensor4 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12339 of file autoarts.h.
References Workspace::add_wsv_inplace().
Tensor5Create()
Tensor5 ARTS::Var::Tensor5Create (Workspace & ws, const Group::Tensor5 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Tensor5
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Tensor5 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12358 of file autoarts.h.
References Workspace::add_wsv_inplace().
Tensor6Create()
Tensor6 ARTS::Var::Tensor6Create (Workspace & ws, const Group::Tensor6 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Tensor6
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Tensor6 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12377 of file autoarts.h.
References Workspace::add_wsv_inplace().
Tensor7Create()
Tensor7 ARTS::Var::Tensor7Create (Workspace & ws, const Group::Tensor7 & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Tensor7
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Tensor7 inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12396 of file autoarts.h.
References Workspace::add_wsv_inplace().
tessem_neth()
TessemNN ARTS::Var::tessem_neth (Workspace & ws) inline noexcept
TESSEM2 neural network parameters for horizontal polarization.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9985 of file autoarts.h.
Referenced by ARTS::Method::SurfaceTessem(), and ARTS::Method::surfaceTessem().
tessem_netv()
TessemNN ARTS::Var::tessem_netv (Workspace & ws) inline noexcept
TESSEM2 neural network parameters for vertical polarization.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 9992 of file autoarts.h.
Referenced by ARTS::Method::SurfaceTessem(), and ARTS::Method::surfaceTessem().
TessemNNCreate()
TessemNN ARTS::Var::TessemNNCreate (Workspace & ws, const Group::TessemNN & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an TessemNN
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] TessemNN inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12415 of file autoarts.h.
References Workspace::add_wsv_inplace().
test_agenda()
Agenda ARTS::Var::test_agenda (Workspace & ws) inline noexcept
A dummy agenda for testing purposes.
Only used for testing by developers.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10001 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::test_agenda(), and ARTS::Agenda::Define::test_agenda().
test_agenda_array()
ArrayOfAgenda ARTS::Var::test_agenda_array (Workspace & ws) inline noexcept
Array of agenda for TestArrayOfAgenda case.
Only used for testing by developers.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10010 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::test_agenda_array(), and TestArrayOfAgenda().
time()
Time ARTS::Var::time (Workspace & ws) inline noexcept
A UTC time point.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10017 of file autoarts.h.
Referenced by IGRF::compute(), LocalTimeOffset(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), main(), MCGeneral(), MCSetSeedFromTime(), psd_cloudice_MH97(), run_oem_matlab(), run_test_matlab(), ARTS::Method::Sleep(), ARTS::Agenda::Method::Sleep(), test_complex_diagonalize(), test_inv(), test_real_diagonalize(), test_solve_linear_system(), time_gridOffset(), timeNow(), ARTS::Method::timeNow(), timeOffset(), ARTS::Method::timeOffset(), timeSleep(), and ARTS::Method::timeSleep().
time_grid()
ArrayOfTime ARTS::Var::time_grid (Workspace & ws) inline noexcept
A grid of times. Should be increasing
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10024 of file autoarts.h.
Referenced by time_gridOffset(), and ARTS::Method::time_gridOffset().
time_stamps()
ArrayOfTime ARTS::Var::time_stamps (Workspace & ws) inline noexcept
A set of times. Can be in random order
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10031 of file autoarts.h.
Referenced by ARTS::Method::time_stampsSort(), and TimeSortTemplate().
TimeCreate()
Time ARTS::Var::TimeCreate (Workspace & ws, const Group::Time & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Time
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Time inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12434 of file autoarts.h.
References Workspace::add_wsv_inplace().
timer()
Timer ARTS::Var::timer (Workspace & ws) inline noexcept
Stores the starting time for time measurements.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10038 of file autoarts.h.
Referenced by ARTS::Method::timerStart(), and ARTS::Method::timerStop().
TimerCreate()
Timer ARTS::Var::TimerCreate (Workspace & ws, const Group::Timer & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Timer
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Timer inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12453 of file autoarts.h.
References Workspace::add_wsv_inplace().
TransmissionMatrixCreate()
TransmissionMatrix ARTS::Var::TransmissionMatrixCreate (Workspace & ws, const Group::TransmissionMatrix & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an TransmissionMatrix
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] TransmissionMatrix inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12472 of file autoarts.h.
References Workspace::add_wsv_inplace().
transmitter_pos()
Matrix ARTS::Var::transmitter_pos (Workspace & ws) inline noexcept
Transmitter positions.
Used for radio link calculations and gives then the position of the transmitting device. The corresponding positions of the receiver are given by sensor_pos. The number of rows in transmitter_pos and sensor_pos* must be equal.
This WSV is also defined as sensor_pos regarding the content of the columns, accepted range for latitudes etc. With one exception, this WSV is demanded to have two columns also for 1D. The additional second value is the angular distance between the transmitter and the reciver. This angle is defined as "latitude" for 2D, with the sensor fixed at the angle of 0 degree.
Each row this matrix defines rte_pos2 for the measurement block, exactly as sensor_pos is translated to rte_pos.
If no transmitter is involved in the calculations, the variable can be set to be empty.
Usage: Set by the user.
Unit: [ m, degrees, degrees ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10067 of file autoarts.h.
Referenced by iyb_calc(), iyb_calc_body(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), sensor_checkedCalc(), ARTS::Method::sensor_checkedCalc(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), and ARTS::Method::yCalcAppend().
VectorCreate()
Vector ARTS::Var::VectorCreate (Workspace & ws, const Group::Vector & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Vector
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Vector inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12491 of file autoarts.h.
References Workspace::add_wsv_inplace().
verbosity()
Verbosity ARTS::Var::verbosity (Workspace & ws) inline noexcept
ARTS verbosity.
The verbosity variable is implicitly passed to all workspace methods. It can be used to dynamically control the reporting level during runtime.
Usage: Set by user.
See also: verbosityInit verbositySet* verbositySetAgenda* verbositySetScreen* verbositySetFile*
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10086 of file autoarts.h.
Referenced by ARTS::Method::abs_cia_dataAddCIARecord(), ARTS::Method::abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), ARTS::Method::abs_cia_dataReadFromXML(), ARTS::Method::abs_cont_descriptionAppend(), ARTS::Method::abs_cont_descriptionInit(), ARTS::Method::abs_hitran_relmat_dataReadHitranRelmatDataAndLines(), ARTS::Method::abs_lines_per_speciesAdaptHitranLineMixing(), abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLevel(), abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLevels(), abs_lines_per_speciesChangeBaseParameterForMatchingLines(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForMatchingLines(), abs_lines_per_speciesChangeBaseParameterForSpecies(), ARTS::Method::abs_lines_per_speciesChangeBaseParameterForSpecies(), abs_lines_per_speciesCompact(), ARTS::Method::abs_lines_per_speciesCompact(), ARTS::Method::abs_lines_per_speciesCreateFromLines(), ARTS::Method::abs_lines_per_speciesHitranLineMixingAdaptationData(), abs_lines_per_speciesMakeManualMirroring(), ARTS::Method::abs_lines_per_speciesMakeManualMirroring(), abs_lines_per_speciesMakeManualMirroringSpecies(), ARTS::Method::abs_lines_per_speciesMakeManualMirroringSpecies(), abs_lines_per_speciesReadSpeciesSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), ARTS::Method::abs_lines_per_speciesReadSplitCatalog(), abs_lines_per_speciesSetBaseParameterForMatchingLevel(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevel(), abs_lines_per_speciesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_lines_per_speciesSetBaseParameterForMatchingLevels(), abs_lines_per_speciesSetBaseParameterForMatchingLines(), abs_lines_per_speciesSetBaseParameterForSpecies(), ARTS::Method::abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetCutoffForMatch(), ARTS::Method::abs_lines_per_speciesSetCutoffForMatch(), abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetCutoffForSpecies(), ARTS::Method::abs_lines_per_speciesSetEmpty(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimit(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), ARTS::Method::abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_lines_per_speciesSetLineShapeType(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForMatch(), abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetLineShapeTypeForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroring(), ARTS::Method::abs_lines_per_speciesSetMirroringForMatch(), abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetMirroringForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalization(), ARTS::Method::abs_lines_per_speciesSetNormalizationForMatch(), abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetNormalizationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulation(), ARTS::Method::abs_lines_per_speciesSetPopulationForMatch(), abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetPopulationForSpecies(), ARTS::Method::abs_lines_per_speciesSetQuantumNumberForMatch(), ARTS::Method::abs_lines_per_speciesSetT0(), ARTS::Method::abs_lines_per_speciesSetT0ForMatch(), abs_lines_per_speciesSetT0ForSpecies(), ARTS::Method::abs_lines_per_speciesSetT0ForSpecies(), abs_lines_per_speciesSetZeemanCoefficients(), ARTS::Method::abs_lines_per_speciesSetZeemanCoefficients(), abs_lines_per_speciesTruncateQuantumNumbers(), ARTS::Method::abs_lines_per_speciesTruncateQuantumNumbers(), abs_lines_per_speciesWriteSpeciesSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSpeciesSplitXML(), abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_lines_per_speciesWriteSplitXML(), ARTS::Method::abs_linesAppendWithLines(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLevel(), abs_linesChangeBaseParameterForMatchingLevels(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLevels(), ARTS::Method::abs_linesChangeBaseParameterForMatchingLines(), ARTS::Method::abs_linesCleanupEmpty(), ARTS::Method::abs_linesCompact(), ARTS::Method::abs_linesDeleteBadF0(), ARTS::Method::abs_linesDeleteLinesWithBadOrHighChangingJs(), ARTS::Method::abs_linesDeleteLinesWithQuantumNumberAbove(), ARTS::Method::abs_linesDeleteLinesWithUndefinedLocalQuanta(), ARTS::Method::abs_linesDeleteWithLines(), ARTS::Method::abs_linesKeepBand(), ARTS::Method::abs_linesMakeManualMirroring(), ARTS::Method::abs_linesPrintDefinedQuantumNumbers(), abs_linesReadSpeciesSplitCatalog(), ARTS::Method::abs_linesReadSpeciesSplitCatalog(), ARTS::Method::abs_linesRemoveBand(), ARTS::Method::abs_linesRemoveUnusedLocalQuantumNumbers(), ARTS::Method::abs_linesReplaceWithLines(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevel(), abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetBaseParameterForMatchingLevels(), ARTS::Method::abs_linesSetBaseParameterForMatchingLines(), ARTS::Method::abs_linesSetCutoff(), ARTS::Method::abs_linesSetCutoffForMatch(), ARTS::Method::abs_linesSetEmptyBroadeningParametersToEmpty(), ARTS::Method::abs_linesSetLinemixingLimit(), ARTS::Method::abs_linesSetLinemixingLimitForMatch(), ARTS::Method::abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Method::abs_linesSetLineShapeType(), ARTS::Method::abs_linesSetLineShapeTypeForMatch(), ARTS::Method::abs_linesSetMirroring(), ARTS::Method::abs_linesSetMirroringForMatch(), ARTS::Method::abs_linesSetNormalization(), ARTS::Method::abs_linesSetNormalizationForMatch(), ARTS::Method::abs_linesSetPopulation(), ARTS::Method::abs_linesSetPopulationForMatch(), ARTS::Method::abs_linesSetQuantumNumberForMatch(), ARTS::Method::abs_linesSetT0(), ARTS::Method::abs_linesSetT0ForMatch(), abs_linesSetZeemanCoefficients(), ARTS::Method::abs_linesSetZeemanCoefficients(), ARTS::Method::abs_linesTruncateGlobalQuantumNumbers(), abs_linesTruncateQuantumNumbers(), ARTS::Method::abs_linesTruncateQuantumNumbers(), abs_linesWriteSpeciesSplitXML(), ARTS::Method::abs_linesWriteSpeciesSplitXML(), abs_linesWriteSplitXML(), ARTS::Method::abs_linesWriteSplitXML(), abs_lookupAdapt(), ARTS::Method::abs_lookupAdapt(), ARTS::Method::abs_lookupCalc(), abs_lookupInit(), ARTS::Method::abs_lookupInit(), abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), ARTS::Method::abs_lookupSetupBatch(), abs_lookupSetupWide(), ARTS::Method::abs_lookupSetupWide(), ARTS::Method::abs_lookupTestAccMC(), ARTS::Method::abs_lookupTestAccuracy(), ARTS::Method::abs_nlteFromRaw(), ARTS::Method::abs_speciesAdd(), abs_speciesAdd2(), ARTS::Method::abs_speciesAdd2(), abs_speciesDefineAll(), ARTS::Method::abs_speciesDefineAll(), abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesDefineAllInScenario(), ARTS::Method::abs_speciesInit(), ARTS::Method::abs_speciesSet(), ARTS::Method::abs_vecAddGas(), ARTS::Agenda::Define::abs_xsec_agenda(), ARTS::Method::abs_xsec_agenda_checkedCalc(), abs_xsec_per_speciesAddCIA(), ARTS::Method::abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), ARTS::Method::abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddHitranXsec(), ARTS::Method::abs_xsec_per_speciesAddLines(), ARTS::Method::abs_xsec_per_speciesAddPredefinedO2MPM2020(), ARTS::Method::abs_xsec_per_speciesInit(), ARTS::Method::AbsInputFromAtmFields(), GasAbsLookup::Adapt(), ARTS::Method::AddZaAa(), AgendaAppend(), ARTS::Method::AgendaExecute(), AgendaExecuteExclusive(), ARTS::Method::AgendaExecuteExclusive(), AgendaSet(), ARTS::Method::AngularGridsSetFluxCalc(), ARTS::Method::antenna_responseGaussian(), antenna_responseVaryingGaussian(), ARTS::Method::antenna_responseVaryingGaussian(), AntennaConstantGaussian1D(), ARTS::Method::AntennaConstantGaussian1D(), AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaMultiBeamsToPencilBeams(), ARTS::Method::AntennaOff(), Append(), ARTS::Method::Append(), ArrayOfAgendaAppend(), ArrayOfAgendaExecute(), ARTS::Method::ArrayOfAgendaExecute(), ARTS::Method::ArrayOfGriddedFieldGetNames(), ARTS::Method::ArrayOfIndexLinSpace(), ARTS::Method::ArrayOfIndexSet(), ARTS::Method::ArrayOfIndexSetConstant(), ARTS::Method::ArrayOfQuantumIdentifierFromLines(), ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfQuantumIdentifierSet(), ARTS::Method::ArrayOfSpeciesTagSet(), ARTS::Method::ArrayOfStringSet(), ARTS::Method::ArrayOfTimeNLinSpace(), ARTS::Method::ArrayOfTimeSetConstant(), Arts2(), atm_fields_compactAddConstant(), ARTS::Method::atm_fields_compactAddConstant(), atm_fields_compactAddSpecies(), ARTS::Method::atm_fields_compactAddSpecies(), ARTS::Method::atm_fields_compactCleanup(), ARTS::Method::atm_fields_compactCreateFromField(), ARTS::Method::atm_fields_compactFromMatrix(), ARTS::Method::atm_gridsFromZRaw(), ARTS::Method::AtmFieldPerturb(), ARTS::Method::AtmFieldPerturbAtmGrids(), AtmFieldPRegrid(), ARTS::Method::AtmFieldPRegrid(), ARTS::Method::atmfields_checkedCalc(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), ARTS::Method::atmgeom_checkedCalc(), ARTS::Method::AtmosphereSet1D(), ARTS::Method::AtmosphereSet2D(), ARTS::Method::AtmosphereSet3D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), ARTS::Method::avkCalc(), ARTS::Method::backend_channel_responseFlat(), ARTS::Method::backend_channel_responseGaussian(), batch_atm_fields_compactAddConstant(), ARTS::Method::batch_atm_fields_compactAddConstant(), batch_atm_fields_compactAddSpecies(), ARTS::Method::batch_atm_fields_compactAddSpecies(), batch_atm_fields_compactCleanup(), ARTS::Method::batch_atm_fields_compactCleanup(), batch_atm_fields_compactFromArrayOfMatrix(), ARTS::Method::batch_atm_fields_compactFromArrayOfMatrix(), c_errmsg(), c_write_bad_var(), c_write_too_small_dim(), Agenda::check(), chk_pnd_raw_data(), choose_abs_nls(), choose_abs_nls_pert(), CIAInfo(), ARTS::Method::CIAInfo(), CIARecordReadFromFile(), ARTS::Method::CIARecordReadFromFile(), cloud_fieldsCalc(), cloud_ppath_update3D(), ARTS::Method::cloudbox_checkedCalc(), cloudbox_field_monoIterate(), ARTS::Method::cloudbox_field_monoIterate(), ARTS::Method::cloudbox_field_monoOptimizeReverse(), ARTS::Method::cloudbox_field_monoSetConst(), ARTS::Method::cloudbox_fieldCrop(), ARTS::Method::cloudbox_fieldSetClearsky(), cloudbox_fieldSetConst(), ARTS::Method::cloudbox_fieldSetConst(), cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetConstPerFreq(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), ARTS::Method::cloudboxOff(), ARTS::Method::cloudboxSetAutomatically(), ARTS::Method::cloudboxSetFullAtm(), ARTS::Method::cloudboxSetManually(), ARTS::Method::cloudboxSetManuallyAltitude(), collision_coefficientsFromSplitFiles(), ARTS::Method::collision_coefficientsFromSplitFiles(), ARTS::Method::Compare(), ARTS::Method::CompareRelative(), ARTS::Method::complex_refr_indexConstant(), ARTS::Method::complex_refr_indexIceMatzler06(), ARTS::Method::complex_refr_indexIceWarren84(), ARTS::Method::complex_refr_indexWaterLiebe93(), Copy(), ARTS::Method::Copy(), ARTS::Method::covmat1D(), ARTS::Method::covmat1DMarkov(), ARTS::Method::covmat_seAddBlock(), ARTS::Method::covmat_seAddInverseBlock(), ARTS::Method::covmat_seSet(), ARTS::Method::covmat_soCalc(), ARTS::Method::covmat_ssCalc(), ARTS::Method::covmat_sxAddBlock(), ARTS::Method::covmat_sxAddInverseBlock(), ARTS::Method::covmat_sxExtractSqrtDiagonal(), ARTS::Method::covmat_sxSet(), ARTS::Method::covmatDiagonal(), create_sparse_f_grid_internal(), create_workspace(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), ARTS::Method::Delete(), ARTS::Method::DiagonalMatrix(), ARTS::Method::diameter_maxFromDiameter_volume_equ(), ARTS::Method::diameter_volume_equFromDiameter_max(), ARTS::Method::DiffZaAa(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), DOAngularGridsSet(), ARTS::Method::DOAngularGridsSet(), ARTS::Agenda::Define::dobatch_calc_agenda(), ARTS::Method::DOBatchCalc(), ARTS::Method::doit_conv_flagAbs(), ARTS::Method::doit_conv_flagAbsBT(), ARTS::Method::doit_conv_flagLsq(), ARTS::Agenda::Define::doit_conv_test_agenda(), ARTS::Agenda::Define::doit_mono_agenda(), ARTS::Agenda::Define::doit_rte_agenda(), ARTS::Agenda::Define::doit_scat_field_agenda(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), ARTS::Method::doit_za_grid_optCalc(), ARTS::Method::doit_za_interpSet(), ARTS::Method::DoitCalc(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), ARTS::Method::DoitInit(), ARTS::Method::DoitScatteringDataPrepare(), DoitScatteringDataPrepare(), DoitWriteIterationFields(), ARTS::Method::DoitWriteIterationFields(), ARTS::Method::Duration(), ARTS::Method::ecs_dataAddMakarov2020(), ARTS::Method::ecs_dataAddRodrigues1997(), ARTS::Method::ecs_dataAddTran2011(), ARTS::Method::ecs_dataInit(), ARTS::Method::ecs_dataSetMeanAir(), ARTS::Method::ecs_dataSetSpeciesData(), emission_from_propmat_field(), ARTS::Method::EnergyLevelMapSet(), ARTS::Method::Error(), Agenda::execute(), InteractiveWorkspace::execute_workspace_method(), ARTS::Method::Exit(), ARTS::Method::ext_matAddGas(), CIARecord::Extract(), ARTS::Method::Extract(), ARTS::Method::ExtractFromMetaSingleScatSpecies(), ARTS::Method::f_gridFromAbsorptionLines(), ARTS::Method::f_gridFromGasAbsLookup(), f_gridFromSensorAMSU(), ARTS::Method::f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), ARTS::Method::f_gridFromSensorAMSUgeneric(), f_gridFromSensorHIRS(), ARTS::Method::f_gridFromSensorHIRS(), ARTS::Method::f_gridMetMM(), ARTS::Method::FastemStandAlone(), ARTS::Method::FieldFromGriddedField(), ARTS::Method::FlagOff(), ARTS::Method::FlagOn(), ARTS::Method::Flatten(), ARTS::Method::ForLoop(), ARTS::Agenda::Define::forloop_agenda(), ARTS::Method::FrequencyFromCGSAngularWavenumber(), ARTS::Method::FrequencyFromCGSKayserWavenumber(), ARTS::Method::FrequencyFromWavelength(), ARTS::Agenda::Define::g0_agenda(), ARTS::Method::g0Earth(), ARTS::Method::g0Io(), ARTS::Method::g0Jupiter(), ARTS::Method::g0Mars(), ARTS::Method::g0Venus(), ARTS::Agenda::Define::geo_pos_agenda(), ARTS::Method::geo_posEndOfPpath(), ARTS::Method::geo_posLowestAltitudeOfPpath(), ARTS::Method::geo_posWherePpathPassesZref(), ARTS::Method::GetEnvironmentVariable(), ARTS::Method::GetNumberOfThreads(), ARTS::Method::GriddedFieldGetName(), GriddedFieldLatLonExpand(), ARTS::Method::GriddedFieldLatLonExpand(), GriddedFieldLatLonRegrid(), ARTS::Method::GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), ARTS::Method::GriddedFieldPRegrid(), GriddedFieldZToPRegrid(), ARTS::Method::GriddedFieldZToPRegrid(), ARTS::Method::heating_ratesFromIrradiance(), ARTS::Method::Ignore(), ARTS::Method::INCLUDE(), ARTS::Method::IndexAdd(), ARTS::Method::IndexNumberOfAtmosphericPoints(), ARTS::Method::IndexSet(), ARTS::Method::IndexSetToLast(), ARTS::Method::IndexStepDown(), ARTS::Method::IndexStepUp(), ARTS::init(), InteractiveWorkspace::InteractiveWorkspace(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Method::InterpGriddedField2ToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Define::inversion_iterate_agenda(), ARTS::Method::irradiance_fieldFromRadiance(), ARTS::Method::isotopologue_ratiosInitFromBuiltin(), ARTS::Method::isotopologue_ratiosInitFromHitran(), ARTS::Agenda::Define::iy_cloudbox_agenda(), ARTS::Agenda::Define::iy_independent_beam_approx_agenda(), ARTS::Agenda::Define::iy_loop_freqs_agenda(), ARTS::Agenda::Define::iy_main_agenda(), ARTS::Agenda::Define::iy_radar_agenda(), ARTS::Agenda::Define::iy_space_agenda(), ARTS::Agenda::Define::iy_surface_agenda(), ARTS::Agenda::Define::iy_transmitter_agenda(), ARTS::Method::iy_transmitterMultiplePol(), ARTS::Method::iy_transmitterSinglePol(), ARTS::Method::iyApplyUnit(), ARTS::Method::iyCalc(), ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), ARTS::Method::iyIndependentBeamApproximation(), ARTS::Method::iyInterpCloudboxField(), ARTS::Method::iyLoopFrequencies(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyReplaceFromAux(), ARTS::Method::iySurfaceCallAgendaX(), iySurfaceFastem(), ARTS::Method::iySurfaceFastem(), ARTS::Method::iySurfaceRtpropAgenda(), ARTS::Method::iySurfaceRtpropCalc(), ARTS::Method::iyTransmissionStandard(), ARTS::Agenda::Define::jacobian_agenda(), ARTS::Method::jacobianAddAbsSpecies(), ARTS::Method::jacobianAddBasicCatalogParameter(), jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddBasicCatalogParameters(), ARTS::Method::jacobianAddFreqShift(), ARTS::Method::jacobianAddFreqStretch(), ARTS::Method::jacobianAddMagField(), ARTS::Method::jacobianAddNLTE(), jacobianAddNLTEs(), ARTS::Method::jacobianAddNLTEs(), ARTS::Method::jacobianAddPointingZa(), ARTS::Method::jacobianAddPolyfit(), ARTS::Method::jacobianAddScatSpecies(), ARTS::Method::jacobianAddShapeCatalogParameter(), jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddShapeCatalogParameters(), ARTS::Method::jacobianAddSinefit(), ARTS::Method::jacobianAddSpecialSpecies(), ARTS::Method::jacobianAddSurfaceQuantity(), ARTS::Method::jacobianAddTemperature(), ARTS::Method::jacobianAddWind(), ARTS::Method::jacobianAdjustAndTransform(), ARTS::Method::jacobianCalcDoNothing(), ARTS::Method::jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), ARTS::Method::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcSinefit(), ARTS::Method::jacobianClose(), jacobianClose(), ARTS::Method::jacobianFromTwoY(), ARTS::Method::jacobianFromYbatch(), ARTS::Method::jacobianInit(), jacobianOff(), ARTS::Method::jacobianOff(), ARTS::Method::jacobianSetAffineTransformation(), ARTS::Method::jacobianSetFuncTransformation(), ARTS::Method::lat_gridFromRawField(), ARTS::Method::lat_gridFromZRaw(), ARTS::Method::lbl_checkedCalc(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), ARTS::Method::LocalTimeOffset(), ARTS::Method::lon_gridFromRawField(), ARTS::Method::lon_gridFromZRaw(), MagFieldsCalc(), ARTS::Method::MagFieldsCalc(), MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcExpand1D(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MagRawRead(), ARTS::Method::MagRawRead(), main(), ARTS::Agenda::Define::main_agenda(), ARTS::Method::Matrix1ColFromVector(), ARTS::Method::Matrix1RowFromVector(), ARTS::Method::Matrix2ColFromVectors(), ARTS::Method::Matrix2RowFromVectors(), ARTS::Method::Matrix3ColFromVectors(), ARTS::Method::Matrix3RowFromVectors(), ARTS::Method::MatrixAddScalar(), ARTS::Method::MatrixCBR(), ARTS::Method::MatrixCopySparse(), ARTS::Method::MatrixExtractFromTensor3(), ARTS::Method::MatrixFromCovarianceMatrix(), ARTS::Method::MatrixIdentity(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Method::MatrixPlanck(), ARTS::Method::MatrixScale(), ARTS::Method::MatrixSet(), ARTS::Method::MatrixSetConstant(), ARTS::Method::MatrixUnitIntensity(), ARTS::Method::MatrixVectorMultiply(), ARTS::Method::mblock_dlos_gridUniformCircular(), ARTS::Method::mblock_dlos_gridUniformRectangular(), ARTS::Method::mc_antennaSetGaussian(), ARTS::Method::mc_antennaSetGaussianByFWHM(), ARTS::Method::mc_antennaSetPencilBeam(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Method::MCSetSeedFromTime(), ARTS::Agenda::Define::met_profile_calc_agenda(), ARTS::Method::nbooksGet(), nca_read_from_file(), nca_write_to_file(), ARTS::Method::ncolsGet(), ARTS::Method::nelemGet(), ARTS::Method::nlibrariesGet(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldFromRaw(), ARTS::Method::nlte_fieldRescalePopulationLevels(), ARTS::Method::nlte_fieldSetLteExternalPartitionFunction(), ARTS::Method::nlte_fieldSetLteInternalPartitionFunction(), ARTS::Method::nlteOff(), ARTS::Method::nlteSetByQuantumIdentifiers(), ARTS::Method::npagesGet(), ARTS::Method::nrowsGet(), ARTS::Method::nshelvesGet(), ARTS::Method::NumericAdd(), ARTS::Method::NumericClip(), ARTS::Method::NumericFromVector(), ARTS::Method::NumericInvScale(), ARTS::Method::NumericScale(), ARTS::Method::NumericSet(), ARTS::Method::nvitrinesGet(), ARTS::Method::OEM(), MdRecord::operator=(), ARTS::Method::opt_prop_bulkCalc(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Method::OptimizeDoitPressureGrid(), ARTS::Method::output_file_formatSetAscii(), ARTS::Method::output_file_formatSetBinary(), ARTS::Method::output_file_formatSetZippedAscii(), ARTS::Method::p_gridDensify(), ARTS::Method::p_gridFromGasAbsLookup(), ARTS::Method::p_gridFromZRaw(), ARTS::Method::p_gridRefine(), ARTS::Method::particle_bulkprop_fieldClip(), particle_bulkprop_fieldPerturb(), ARTS::Method::particle_bulkprop_fieldPerturb(), particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkprop_fieldPerturbAtmGrids(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_fieldCleanup(), ARTS::Method::particle_massesFromMetaData(), ARTS::Method::particle_massesFromMetaDataSingleCategory(), ARTS::Method::PFromZSimple(), ARTS::Agenda::Define::pha_mat_spt_agenda(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), ARTS::Method::pha_matCalc(), ARTS::Method::pnd_fieldCalcFromParticleBulkProps(), pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldCalcFrompnd_field_raw(), ARTS::Method::pnd_fieldExpand1D(), ARTS::Method::pnd_fieldZero(), ARTS::Method::pndFromPsd(), ARTS::Method::pndFromPsdBasic(), ARTS::Agenda::Define::ppath_agenda(), ppath_calc(), ARTS::Method::ppath_fieldCalc(), ppath_fieldCalc(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ARTS::Agenda::Define::ppath_step_agenda(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ARTS::Method::ppathCalc(), ppathCalcFromAltitude(), ARTS::Method::ppathCalcFromAltitude(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), ppathWriteXMLPartial(), ARTS::Method::ppathWriteXMLPartial(), ARTS::Method::ppvar_optical_depthFromPpvar_trans_cumulat(), Print(), ARTS::Method::Print(), ARTS::Method::PrintPhysicalConstants(), ARTS::Method::PrintWorkspace(), ARTS::Agenda::Define::propmat_clearsky_agenda(), ARTS::Method::propmat_clearsky_agenda_checkedCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearskyAddFaraday(), ARTS::Method::propmat_clearskyAddFromLookup(), ARTS::Method::propmat_clearskyAddHitranLineMixingLines(), propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddLines(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixing(), ARTS::Method::propmat_clearskyAddOnTheFlyLineMixingWithZeeman(), ARTS::Method::propmat_clearskyAddParticles(), ARTS::Method::propmat_clearskyAddXsecAgenda(), propmat_clearskyAddXsecAgenda(), ARTS::Method::propmat_clearskyAddZeeman(), ARTS::Method::propmat_clearskyForceNegativeToZero(), ARTS::Method::propmat_clearskyInit(), ARTS::Method::propmat_clearskyZero(), psdAbelBoutle12(), ARTS::Method::psdAbelBoutle12(), ARTS::Method::psdFieldEtAl07(), psdFieldEtAl19(), ARTS::Method::psdFieldEtAl19(), ARTS::Method::psdMcFarquaharHeymsfield97(), ARTS::Method::psdMilbrandtYau05(), ARTS::Method::psdModifiedGamma(), ARTS::Method::psdModifiedGammaMass(), psdModifiedGammaMassMeanParticleMass(), ARTS::Method::psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), ARTS::Method::psdModifiedGammaMassNtot(), psdModifiedGammaMassSingleMoment(), ARTS::Method::psdModifiedGammaMassSingleMoment(), psdModifiedGammaMassXmean(), ARTS::Method::psdModifiedGammaMassXmean(), psdModifiedGammaMassXmedian(), ARTS::Method::psdModifiedGammaMassXmedian(), psdMonoDispersive(), ARTS::Method::psdMonoDispersive(), psdMonoMass(), ARTS::Method::psdMonoMass(), ARTS::Method::psdSeifertBeheng06(), psdWangEtAl16(), ARTS::Method::psdWangEtAl16(), ARTS::Method::QuantumIdentifierSet(), ARTS::Method::RadarOnionPeelingTableCalc(), ARTS::Method::RadiationFieldSpectralIntegrate(), ARTS::Method::RationalAdd(), ARTS::Method::RationalInvScale(), ARTS::Method::RationalScale(), ARTS::Method::RationalSet(), ReadArrayOfARTSCAT(), ARTS::Method::ReadArrayOfARTSCAT(), ReadARTSCAT(), ARTS::Method::ReadARTSCAT(), ReadHITRAN(), ARTS::Method::ReadHITRAN(), ReadJPL(), ARTS::Method::ReadJPL(), ReadLBLRTM(), ARTS::Method::ReadLBLRTM(), ReadNetCDF(), ARTS::Method::ReadNetCDF(), ReadSplitARTSCAT(), ARTS::Method::ReadSplitARTSCAT(), ReadXML(), ARTS::Method::ReadXML(), ReadXMLIndexed(), ARTS::Method::ReadXMLIndexed(), ARTS::Method::Reduce(), ARTS::Method::refellipsoidEarth(), ARTS::Method::refellipsoidEuropa(), ARTS::Method::refellipsoidForAzimuth(), ARTS::Method::refellipsoidGanymede(), ARTS::Method::refellipsoidIo(), ARTS::Method::refellipsoidJupiter(), ARTS::Method::refellipsoidMars(), ARTS::Method::refellipsoidMoon(), ARTS::Method::refellipsoidOrbitPlane(), ARTS::Method::refellipsoidVenus(), ARTS::Agenda::Define::refr_index_air_agenda(), ARTS::Method::refr_index_airFreeElectrons(), ARTS::Method::refr_index_airInfraredEarth(), ARTS::Method::refr_index_airMicrowavesEarth(), ARTS::Method::refr_index_airMicrowavesGeneral(), retrievalAddAbsSpecies(), ARTS::Method::retrievalAddAbsSpecies(), ARTS::Method::retrievalAddCatalogParameter(), retrievalAddCatalogParameter(), ARTS::Method::retrievalAddCatalogParameters(), retrievalAddCatalogParameters(), retrievalAddFreqShift(), ARTS::Method::retrievalAddFreqShift(), retrievalAddFreqStretch(), ARTS::Method::retrievalAddFreqStretch(), retrievalAddMagField(), ARTS::Method::retrievalAddMagField(), retrievalAddPointingZa(), ARTS::Method::retrievalAddPointingZa(), retrievalAddPolyfit(), ARTS::Method::retrievalAddPolyfit(), ARTS::Method::retrievalAddScatSpecies(), retrievalAddScatSpecies(), retrievalAddSinefit(), ARTS::Method::retrievalAddSinefit(), ARTS::Method::retrievalAddSpecialSpecies(), retrievalAddSpecialSpecies(), ARTS::Method::retrievalAddSurfaceQuantity(), retrievalAddSurfaceQuantity(), retrievalAddTemperature(), ARTS::Method::retrievalAddTemperature(), retrievalAddWind(), ARTS::Method::retrievalAddWind(), ARTS::Method::retrievalDefClose(), retrievalDefClose(), retrievalDefInit(), ARTS::Method::retrievalDefInit(), ARTS::Method::retrievalErrorsExtract(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), ARTS::Method::RT4Test(), ARTS::Method::rte_losGeometricFromRtePosToRtePos2(), ARTS::Method::rte_losSet(), ARTS::Method::rte_pos_losMoveToStartOfPpath(), ARTS::Method::rte_poslosFromECEF(), ARTS::Method::rte_poslosFromGeodetic(), ARTS::Method::rte_posSet(), ARTS::Method::rtp_nlteFromRaw(), run_cdisort(), scat_data_checkedCalc(), ARTS::Method::scat_data_checkedCalc(), ARTS::Method::scat_data_monoCalc(), ARTS::Method::scat_data_monoExtract(), ARTS::Method::scat_data_singleTmatrix(), ARTS::Method::scat_dataCalc(), ARTS::Method::scat_dataCheck(), ARTS::Method::scat_dataReduceT(), ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsPndAndScatAdd(), ARTS::Method::ScatElementsSelect(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ARTS::Method::ScatSpeciesExtendTemperature(), ARTS::Method::ScatSpeciesInit(), ARTS::Method::ScatSpeciesMerge(), ScatSpeciesPndAndScatAdd(), ARTS::Method::ScatSpeciesPndAndScatAdd(), ScatSpeciesScatAndMetaRead(), ARTS::Method::ScatSpeciesScatAndMetaRead(), ARTS::Method::ScatSpeciesSizeMassInfo(), Select(), ARTS::Method::Select(), ARTS::Method::sensor_checkedCalc(), sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_losGeometricFromSensorPosToOtherPositions(), ARTS::Method::sensor_poslosFromECEF(), ARTS::Method::sensor_poslosFromGeodetic(), ARTS::Agenda::Define::sensor_response_agenda(), ARTS::Method::sensor_responseAntenna(), ARTS::Method::sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseBackendFrequencySwitching(), ARTS::Method::sensor_responseFillFgrid(), ARTS::Method::sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), ARTS::Method::sensor_responseGenericAMSU(), ARTS::Method::sensor_responseIF2RF(), ARTS::Method::sensor_responseInit(), sensor_responseMetMM(), ARTS::Method::sensor_responseMetMM(), ARTS::Method::sensor_responseMixer(), ARTS::Method::sensor_responseMixerBackendPrecalcWeights(), sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responseMultiMixerBackend(), ARTS::Method::sensor_responsePolarisation(), sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseSimpleAMSU(), ARTS::Method::sensor_responseStokesRotation(), ARTS::Method::sensor_responseWMRF(), sensorOff(), ARTS::Method::sensorOff(), ARTS::Method::SetNumberOfThreads(), ARTS::Method::Sleep(), ARTS::Method::sparse_f_gridFromFrequencyGrid(), ARTS::Method::SparseMatrixIdentity(), ARTS::Method::SparseSparseMultiply(), ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldCopyCloudboxField(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), specular_losCalc(), ARTS::Method::specular_losCalc(), ARTS::Method::specular_losCalcNoTopography(), ARTS::Agenda::Define::spt_calc_agenda(), ARTS::Method::StringJoin(), ARTS::Method::StringSet(), ARTS::Method::surface_complex_refr_indexFromGriddedField5(), ARTS::Method::surface_reflectivityFromGriddedField6(), ARTS::Agenda::Define::surface_rtprop_agenda(), ARTS::Agenda::Define::surface_rtprop_sub_agenda(), ARTS::Method::surface_rtpropCallAgendaX(), ARTS::Method::surface_scalar_reflectivityFromGriddedField4(), ARTS::Method::surface_scalar_reflectivityFromSurface_rmatrix(), ARTS::Method::surface_typeInterpTypeMask(), SurfaceBlackbody(), ARTS::Method::surfaceBlackbody(), ARTS::Method::SurfaceBlackbody(), ARTS::Method::SurfaceDummy(), SurfaceFastem(), surfaceFastem(), ARTS::Method::SurfaceFastem(), ARTS::Method::surfaceFastem(), ARTS::Method::surfaceFlatReflectivity(), ARTS::Method::surfaceFlatRefractiveIndex(), ARTS::Method::surfaceFlatRvRh(), SurfaceFlatScalarReflectivity(), ARTS::Method::surfaceFlatScalarReflectivity(), ARTS::Method::SurfaceFlatScalarReflectivity(), ARTS::Method::surfaceLambertianSimple(), ARTS::Method::surfaceSemiSpecularBy3beams(), ARTS::Method::surfaceSplitSpecularTo3beams(), ARTS::Method::surfaceTelsem(), SurfaceTessem(), surfaceTessem(), ARTS::Method::SurfaceTessem(), ARTS::Method::surfaceTessem(), ARTS::Method::TangentPointExtract(), ARTS::Method::TangentPointPrint(), ARTS::Method::telsem_atlasesReadAscii(), ARTS::Method::telsem_atlasReadAscii(), ARTS::Method::telsemAtlasLookup(), ARTS::Method::telsemStandalone(), ARTS::Method::telsemSurfaceTypeLandSea(), ARTS::Method::Tensor3AddScalar(), ARTS::Method::Tensor3ExtractFromTensor4(), ARTS::Method::Tensor3FromVector(), ARTS::Method::Tensor3Scale(), ARTS::Method::Tensor3SetConstant(), ARTS::Method::Tensor4AddScalar(), ARTS::Method::Tensor4Scale(), ARTS::Method::Tensor4SetConstant(), ARTS::Method::Tensor5Scale(), ARTS::Method::Tensor5SetConstant(), ARTS::Method::Tensor6Scale(), ARTS::Method::Tensor6SetConstant(), ARTS::Method::Tensor7Scale(), ARTS::Method::Tensor7SetConstant(), ARTS::Method::TessemNNReadAscii(), ARTS::Method::Test(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), ARTS::Agenda::Define::test_agenda(), ARTS::Method::TestArrayOfAgenda(), ARTS::Method::TestTessem(), time_gridOffset(), ARTS::Method::time_gridOffset(), ARTS::Method::time_stampsSort(), ARTS::Method::timeNow(), ARTS::Method::timeOffset(), ARTS::Method::timerStart(), ARTS::Method::timerStop(), ARTS::Method::timeSleep(), TMatrixTest(), ARTS::Method::TMatrixTest(), ARTS::Method::Touch(), ARTS::Method::transmittanceFromIy_aux(), ARTS::Method::Trapz(), ARTS::Method::VectorAddScalar(), ARTS::Method::VectorAddVector(), ARTS::Method::VectorClip(), ARTS::Method::VectorCrop(), ARTS::Method::VectorExtractFromMatrix(), ARTS::Method::VectorFlip(), ARTS::Method::VectorInsertGridPoints(), ARTS::Method::VectorLinSpace(), ARTS::Method::VectorLogSpace(), ARTS::Method::VectorMatrixMultiply(), ARTS::Method::VectorNLinSpace(), ARTS::Method::VectorNLogSpace(), ARTS::Method::VectorPower(), ARTS::Method::VectorReshapeMatrix(), ARTS::Method::VectorScale(), ARTS::Method::VectorSet(), ARTS::Method::VectorSetConstant(), ARTS::Method::VectorSubtractVector(), ARTS::Method::VectorVectorMultiply(), ARTS::Method::VectorZtanToZa1D(), ARTS::Method::VectorZtanToZaRefr1D(), verbosityInit(), ARTS::Method::verbosityInit(), verbositySet(), ARTS::Method::verbositySet(), verbositySetAgenda(), ARTS::Method::verbositySetAgenda(), verbositySetFile(), ARTS::Method::verbositySetFile(), verbositySetScreen(), ARTS::Method::verbositySetScreen(), ARTS::Method::vmr_fieldClip(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldSetAllConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Agenda::Define::water_p_eq_agenda(), ARTS::Method::water_p_eq_fieldMK05(), ARTS::Method::Wigner3Init(), ARTS::Method::Wigner3Unload(), ARTS::Method::Wigner6Init(), ARTS::Method::Wigner6Unload(), ARTS::Method::WignerFastInfoPrint(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), WindRawRead(), ARTS::Method::WindRawRead(), WMRFSelectChannels(), ARTS::Method::WMRFSelectChannels(), WriteBuiltinPartitionFunctionsXML(), ARTS::Method::WriteBuiltinPartitionFunctionsXML(), ARTS::Method::WriteMolTau(), WriteNetCDF(), ARTS::Method::WriteNetCDF(), WriteNetCDFIndexed(), ARTS::Method::WriteNetCDFIndexed(), WriteXML(), ARTS::Method::WriteXML(), WriteXMLIndexed(), ARTS::Method::WriteXMLIndexed(), ARTS::Method::x2artsAtmAndSurf(), ARTS::Method::x2artsSensor(), ARTS::Method::x2artsSpectroscopy(), ARTS::Method::xaStandard(), ARTS::Method::xClip(), xml_find_and_open_input_file(), xml_parse_from_stream(), xml_read_footer_from_stream(), xml_read_from_file(), xml_read_from_file_base(), xml_read_from_stream(), xml_read_header_from_stream(), xml_write_footer_to_stream(), xml_write_header_to_stream(), xml_write_to_file(), xml_write_to_file_base(), xml_write_to_stream(), xsec_continuum_tag(), ARTS::Method::y_geoToGeodetic(), ARTS::Method::yApplySensorPol(), ARTS::Method::yApplyUnit(), ARTS::Agenda::Define::ybatch_calc_agenda(), ARTS::Method::ybatchCalc(), ARTS::Method::ybatchColdAtmHotAtmCycle(), ARTS::Method::ybatchDoublingMeanFocus(), ybatchMaskOutsideMedianRange(), ARTS::Method::ybatchMaskOutsideMedianRange(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::ybatchTimeAveraging(), ARTS::Method::ybatchTroposphericCorrectionNaiveMedianForward(), ARTS::Method::ybatchTroposphericCorrectionNaiveMedianInverse(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), ARTS::Method::yColdAtmHot(), ARTS::Method::yDoublingMeanFocus(), ARTS::Method::yMaskOutsideMedianRange(), ARTS::Method::yRadar(), ySimpleSpectrometer(), ARTS::Method::ySimpleSpectrometer(), ARTS::Method::z_fieldFromHSE(), ARTS::Method::z_surfaceConstantAltitude(), z_surfaceFromFileAndGrid(), ARTS::Method::z_surfaceFromFileAndGrid(), and ARTS::Method::ZFromPSimple().
VerbosityCreate()
Verbosity ARTS::Var::VerbosityCreate (Workspace & ws, const Group::Verbosity & inval, const Group::String & name, const Group::String & desc = "nodescription") inline
Creates in, and returns from, Workspace a/an Verbosity
Parameters
[in,out] Workspace ws - An ARTS workspace
[in] Verbosity inval - The default value the variable will have in the workspace
[in] String name - The name the variable will have in the workspace
[in] String desc - The description the variable will have in the workspace (default: "nodescription")
Returns
A class with a pointer to this variable and its new position in the workspace
Definition at line 12510 of file autoarts.h.
References Workspace::add_wsv_inplace().
vmr_field()
Tensor4 ARTS::Var::vmr_field (Workspace & ws) inline noexcept
VMR field.
This variable gives the volume mixing ratio of the chosen gaseous species as a function of p_grid, lat_grid, lon_grid.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Units: [ Differ between the elements, can be VMR, kg/m3 or #/m3. ]
Dimensions: [species, p_grid, lat_grid, lon_grid]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10104 of file autoarts.h.
Referenced by abs_lookupSetup(), ARTS::Method::abs_lookupSetup(), abs_lookupSetupBatch(), AbsInputFromAtmFields(), ARTS::Method::AbsInputFromAtmFields(), atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), clear_rt_vars_at_gp(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), get_ppath_atmvars(), get_ppath_transmat(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), interp_cloud_coeff1D(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyMC(), ARTS::Method::iyMC(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::OptimizeDoitPressureGrid(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ARTS::Agenda::ppath_agenda_plane_parallel(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), propmat_clearsky_fieldCalc(), ARTS::Method::propmat_clearsky_fieldCalc(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), vmr_fieldClip(), ARTS::Method::vmr_fieldClip(), vmr_fieldPerturb(), ARTS::Method::vmr_fieldPerturb(), vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldPerturbAtmGrids(), ARTS::Method::vmr_fieldSetAllConstant(), ARTS::Method::vmr_fieldSetConstant(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::xaStandard(), and ARTS::Method::z_fieldFromHSE().
vmr_field_raw()
ArrayOfGriddedField3 ARTS::Var::vmr_field_raw (Workspace & ws) inline noexcept
VMR data for the chosen gaseous species.
This variable contains the volume mixing ratios (VMR) for all chosen gaseous species. It includes the grids corresponding to the grids in the database. vmr_field_raw* is an Array of Array of Tensor3. It contains one gridded field for each species which contains the data and also the grids. For the calculation the data is interpolated on p_grid, lat_grid and lon_grid
Usage: Output of AtmRawRead Input to AtmFieldsCalc.
Unit: absolute number
Size: Array[number of absorption species] GriddedField3 [N_p] [N_lat] [N_lon] [N_p, N_lat, N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10132 of file autoarts.h.
Referenced by AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ScatElementsToabs_speciesAdd(), ARTS::Method::ScatElementsToabs_speciesAdd(), ybatchMetProfiles(), and ybatchMetProfilesClear().
water_p_eq_agenda()
Agenda ARTS::Var::water_p_eq_agenda (Workspace & ws) inline noexcept
Agenda to calculate the saturation pressure of water.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10139 of file autoarts.h.
Referenced by ARTS::Method::iyEmissionStandard(), iyHybrid(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), rtmethods_jacobian_finalisation(), spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Agenda::Execute::water_p_eq_agenda(), ARTS::Agenda::Define::water_p_eq_agenda(), ARTS::Agenda::water_p_eq_agenda_default(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
water_p_eq_field()
Tensor3 ARTS::Var::water_p_eq_field (Workspace & ws) inline noexcept
The field of water saturation pressure.
This variable holds the saturation pressure of water at each crossing of the pressure, latitude and longitude grids.
Unit: Pa
Dimensions: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10153 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::water_p_eq_agenda(), water_p_eq_agendaExecute(), water_p_eq_fieldMK05(), and ARTS::Method::water_p_eq_fieldMK05().
wigner_initialized()
Index ARTS::Var::wigner_initialized (Workspace & ws) inline noexcept
Indicates if the wigner tables are initialized. If they are not, computations will be aborted.
Will hold the value of provided maximum factorial value
The developer should always test this variable in functions that might require computing wigner symbols because the error handling is otherwise offloaded to third party software...
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10167 of file autoarts.h.
Referenced by main(), Wigner3Init(), ARTS::Method::Wigner3Init(), Wigner3Unload(), ARTS::Method::Wigner3Unload(), Wigner6Init(), ARTS::Method::Wigner6Init(), Wigner6Unload(), ARTS::Method::Wigner6Unload(), WignerFastInfoPrint(), and ARTS::Method::WignerFastInfoPrint().
wind_u_field()
Tensor3 ARTS::Var::wind_u_field (Workspace & ws) inline noexcept
Zonal component of the wind field.
The East-West wind component. Air moving towards higher longitudes is a positive wind. This wind causes no Doppler shift for 1D and 2D simulations.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10185 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
wind_u_field_raw()
GriddedField3 ARTS::Var::wind_u_field_raw (Workspace & ws) inline noexcept
Raw zonal component of the wind field.
The East-West wind component. Air moving towards higher longitudes is a positive wind. This wind causes no Doppler shift for 1D and 2D simulations.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ].
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10203 of file autoarts.h.
Referenced by WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), WindRawRead(), and ARTS::Method::WindRawRead().
wind_v_field()
Tensor3 ARTS::Var::wind_v_field (Workspace & ws) inline noexcept
Meridional component of the magnetic field.
The North-South wind component. Air moving towards higher latitudes is a positive wind.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10220 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
wind_v_field_raw()
GriddedField3 ARTS::Var::wind_v_field_raw (Workspace & ws) inline noexcept
Raw meridional component of the magnetic field.
The North-South wind component. Air moving towards higher latitudes is a positive wind.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10237 of file autoarts.h.
Referenced by WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), WindRawRead(), and ARTS::Method::WindRawRead().
wind_w_field()
Tensor3 ARTS::Var::wind_w_field (Workspace & ws) inline noexcept
Vertical wind component field.
Upward moving air corresponds to a positive wind speed.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ] or [ 0 0 0 ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10253 of file autoarts.h.
Referenced by atmfields_checkedCalc(), ARTS::Method::atmfields_checkedCalc(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), get_ppath_atmvars(), ARTS::Method::iyEmissionStandard(), iyEmissionStandard(), iyHybrid(), ARTS::Method::iyHybrid(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyRadarSingleScat(), ARTS::Method::iyRadarSingleScat(), ARTS::Method::iyTransmissionStandard(), iyTransmissionStandard(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), ARTS::Method::x2artsAtmAndSurf(), and ARTS::Method::xaStandard().
wind_w_field_raw()
GriddedField3 ARTS::Var::wind_w_field_raw (Workspace & ws) inline noexcept
Raw vertical wind component field.
Upward moving air corresponds to a positive wind speed.
Can be set to be empty, which is interpreted as zero wind speed everywhere.
Unit: m/s
Dimensions: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10269 of file autoarts.h.
Referenced by WindFieldsCalc(), ARTS::Method::WindFieldsCalc(), WindFieldsCalcExpand1D(), ARTS::Method::WindFieldsCalcExpand1D(), WindRawRead(), and ARTS::Method::WindRawRead().
wmrf_channels()
ArrayOfIndex ARTS::Var::wmrf_channels (Workspace & ws) inline noexcept
Channel selection for WMRF fast calculation.
This variable can be used to select one or several instrument channels from the list of all possible channels. Zero-based indexing is used, so Channel 0 is the first instrument channel!
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10280 of file autoarts.h.
Referenced by WMRFSelectChannels(), and ARTS::Method::WMRFSelectChannels().
wmrf_weights()
Sparse ARTS::Var::wmrf_weights (Workspace & ws) inline noexcept
The weights for a WMRF fast calculation.
Weights are stored in a sparse matrix. This can be used as a sensor_response matrix.
The dimension of the matrix is (nchan, nfreq), where nchan is the number of instrument channels and nfreq is the number of monochromatic frequencies.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10294 of file autoarts.h.
Referenced by sensor_responseWMRF(), ARTS::Method::sensor_responseWMRF(), WMRFSelectChannels(), and ARTS::Method::WMRFSelectChannels().
x()
Vector ARTS::Var::x (Workspace & ws) inline noexcept
The state vector.
This WSV matches directly the x-vector in the formalism by C.D. Rodgers.
Inside x, the elements matching one retrieval quantity, such as atmospheric temperatures, are kept together. That is, each retrieval quantity covers a continuous range inside x. The start and index of these ranges can be deduced by jacobian_quantities (see function(s) inside jacobian.cc for details).
The order of elements inside each retrieval quantity should be clarified by corresponding "adding" method, i.e. jacobianAddTemperature for atmospheric temperatures. The general rule is that data are sorted from left to right with respect to the order in the corresponding WSV. For example, inside x atmospheric data are stored with pressure as inner- most loop, followed by latitude and longitude as outermost loop.
Usage: Used by inversion methods.
Unit: Varies, follows unit of selected retrieval quantities.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10320 of file autoarts.h.
Referenced by Absorption::SingleLine::A(), nonstd::abs(), abs_lines_per_speciesSetCutoff(), abs_lines_per_speciesSetCutoffForMatch(), abs_lines_per_speciesSetCutoffForSpecies(), abs_lines_per_speciesSetLinemixingLimit(), abs_lines_per_speciesSetLinemixingLimitForMatch(), abs_lines_per_speciesSetLinemixingLimitForSpecies(), abs_lines_per_speciesSetQuantumNumberForMatch(), abs_lines_per_speciesSetT0(), abs_lines_per_speciesSetT0ForMatch(), abs_lines_per_speciesSetT0ForSpecies(), abs_linesDeleteLinesWithUndefinedLocalQuanta(), abs_linesSetCutoff(), abs_linesSetCutoffForMatch(), abs_linesSetLinemixingLimit(), abs_linesSetLinemixingLimitForMatch(), abs_linesSetT0(), abs_linesSetT0ForMatch(), abs_linesTruncateGlobalQuantumNumbers(), abs_lookupInit(), abs_xsec_per_speciesAddPredefinedO2MPM2020(), Conversion::acosd(), add(), PropagationMatrix::AddAbsorptionVectorAtPosition(), PropagationMatrix::AddAtPosition(), RadiationVector::addMultiplied(), agendas(), AngularGridsSetFluxCalc(), antenna_responseGaussian(), antenna_responseVaryingGaussian(), ARTS::Agenda::Define::Append(), Linefunctions::apply_linestrength_from_nlte_level_distributions(), ArrayOfIndexLinSpace(), ArrayOfQuantumIdentifierSet(), Conversion::asind(), Conversion::atan2d(), Conversion::atand(), Conversion::atm2pa(), AtmFieldPerturb(), backend_channel_responseFlat(), backend_channel_responseGaussian(), Absorption::Lines::Bath(), bin_quadweights(), by_reference(), by_value(), calcBaselineFit(), calculate_weights_linear(), cart2pol(), cart2poslos(), cart2poslos_plain(), cart2sph(), cart2sph_plain(), Conversion::celsius2kelvin(), check_collision_line_identifiers(), chk_atm_field(), chk_atm_surface(), chk_contains(), chk_if_bool(), chk_if_decreasing(), chk_if_in_range(), chk_if_in_range_exclude(), chk_if_in_range_exclude_high(), chk_if_in_range_exclude_low(), chk_if_increasing(), chk_matrix_ncols(), chk_matrix_nrows(), chk_not_empty(), chk_not_negative(), chk_size(), chk_vector_length(), column_string(), ComplexMatrix::ComplexMatrix(), ComplexVector::ComplexVector(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), conti_n2__(), copy(), Conversion::cosd(), covmat1D(), Absorption::Lines::Cutoff(), Absorption::Lines::CutoffFreqValue(), Interpolation::cyclic_clamp(), dabsorption_nlte_rate_dT(), dabsorption_nlte_rate_dTl(), dabsorption_nlte_rate_dTu(), dampened_statistical_equilibrium_equation(), defocusing_general_sub(), Rational::Denom(), derive_scat_species_a_and_b(), describe(), lm_hitran_2017::detband(), Minimize::Polynom::df(), LineShape::differenceOutput(), PropagationMatrix::DivideAtPosition(), Interpolation::dl_dval(), Interpolation::Lagrange::dlx_finder(), Interpolation::FixedLagrange< PolyOrder >::dlx_finder(), do_gridcell_2d_byltest(), do_gridcell_3d_byltest(), dtransmat3(), dxdvmrscf(), Absorption::SingleLine::E0(), ecs_dataSetMeanAir(), EnergyLevelMapSet(), ARTS::Method::EnergyLevelMapSet(), ARTS::Agenda::Method::EnergyLevelMapSet(), Quantum::ENUMCLASS(), lm_hitran_2017::ENUMCLASS(), Absorption::ENUMCLASS(), Jacobian::ENUMCLASS(), Agenda::execute(), extract(), Absorption::SingleLine::F0(), fill_tensor6(), fill_tensor7(), fill_with_junk(), find_all(), find_first(), Raw::Reduce::find_first_and_last_1(), PropagationMatrix::FittingShape(), fixed_defaults(), FlagOff(), FlagOn(), flat(), Raw::Reduce::focus(), Raw::Reduce::focus_doublescaling(), LineShape::from_linemixingdata(), LineShape::from_pressurebroadeningdata(), Zeeman::FromGrids(), func_2straights(), fwv_mpmf87s93__(), g0Earth(), Absorption::SingleLine::g_low(), Absorption::SingleLine::g_upp(), gaussian_response(), gaussian_response_autogrid(), geompath_tanpos_3d(), ArtsXMLTag::get_attribute_value(), EnergyLevelMap::get_ratio_params(), EnergyLevelMap::get_vibtemp_params(), Zeeman::Model::gl(), good_enum(), groups(), gsl_integration_glfixed_table_alloc(), gsl_rng_uniform_pos(), Zeeman::Model::gu(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), Conversion::hz_per_msquared2kaycm_per_cmsquared(), Conversion::hz_per_pa2kaycm_per_atm(), Absorption::SingleLine::I0(), IndexSet(), IndexSetToLast(), LineShape::SpeedDependentVoigt::init(), LineShape::HartmannTran::init(), init_mpm2020_lsm(), init_mpm2020_slsm(), integer_div(), interp_atmfield_by_gp(), interp_atmfield_by_itw(), interp_atmsurface_by_gp(), interp_atmsurface_by_itw(), interp_poly(), ARTS::Agenda::Execute::inversion_iterate_agenda(), inversion_iterate_agendaExecute(), is_bool(), is_decreasing(), is_increasing(), is_multiple(), is_size(), is_sorted(), is_space_char(), is_unique(), isnormal_or_zero(), Hitran::isotopologue_ratios_impl(), Species::IsotopologueRatios::IsotopologueRatios(), Species::isotopologues_names(), iySurfaceFastem(), jacobianAdjustAndTransform(), ARTS::Method::jacobianAdjustAndTransform(), Conversion::kaycm_per_atm2hz_per_pa(), Conversion::kelvin2celsius(), LagrangeInterpol4(), Interpolation::LagrangeVector(), last(), lbl_checkedCalc(), Absorption::Lines::LinemixingLimit(), Absorption::Lines::LineShapeType(), linreg(), linspace(), lorentz_pdf(), lsf(), Interpolation::Lagrange::lx_finder(), Interpolation::FixedLagrange< PolyOrder >::lx_finder(), main(), Raw::Mask::mask(), MaTipping_H2O_foreign_continuum(), matrix_vector_mult(), ARTS::Method::MatrixMatrixMultiply(), ARTS::Agenda::Method::MatrixMatrixMultiply(), MatrixSet(), MatrixSetConstant(), max(), mblock_dlos_gridUniformCircular(), mean(), LineShape::MetaData2ModelShape(), Conversion::meter2angstrom(), methods(), mgd(), mgd_with_derivatives(), Conversion::mhz2joule(), Conversion::mhz_per_torr2hz_per_pa(), min(), Interpolation::min_cyclic(), LineShape::mirroredOutput(), Absorption::Lines::Mirroring(), mod_gamma_dist(), LineShape::Model::Model(), LineShape::ModelShape2MetaData(), PropagationMatrix::MultiplyAtPosition(), NameMaps::NameMaps(), Raw::Reduce::nanfocus(), nanmean(), Raw::Average::nanmedian(), Raw::Average::nanstd(), LineShape::negativeOutput(), Absorption::nelem(), nelemGet(), nlinspace(), nlogspace(), nlte_fieldForSingleSpeciesNonOverlappingLines(), Rational::Nom(), Absorption::Lines::Normalization(), numeric2rational(), NumericSet(), ARTS::Method::OEM(), Species::IsotopeRecord::operator!=(), Minimize::Polynom::operator()(), LineShape::Doppler::operator()(), LineShape::SpeedDependentVoigt::operator()(), LineShape::HartmannTran::operator()(), operator*(), ComplexMatrixView::operator*=(), ComplexVectorView::operator*=(), VectorView::operator*=(), PropagationMatrix::operator*=(), Sparse::operator*=(), Tensor3View::operator*=(), Tensor4View::operator*=(), Tensor5View::operator*=(), Tensor6View::operator*=(), Tensor7View::operator*=(), MatrixView::operator*=(), ComplexMatrixView::operator+=(), ComplexVectorView::operator+=(), VectorView::operator+=(), PropagationMatrix::operator+=(), StokesVector::operator+=(), Tensor3View::operator+=(), Tensor4View::operator+=(), Tensor5View::operator+=(), Tensor6View::operator+=(), Tensor7View::operator+=(), MatrixView::operator+=(), ComplexMatrixView::operator-=(), ComplexVectorView::operator-=(), VectorView::operator-=(), PropagationMatrix::operator-=(), Tensor3View::operator-=(), Tensor4View::operator-=(), Tensor5View::operator-=(), Tensor6View::operator-=(), Tensor7View::operator-=(), MatrixView::operator-=(), ComplexMatrixView::operator/=(), ComplexVectorView::operator/=(), VectorView::operator/=(), PropagationMatrix::operator/=(), Sparse::operator/=(), Tensor3View::operator/=(), Tensor4View::operator/=(), Tensor5View::operator/=(), Tensor6View::operator/=(), Tensor7View::operator/=(), MatrixView::operator/=(), Jacobian::operator<<(), operator<<(), LineShape::operator<<(), ComplexVectorView::operator=(), ComplexMatrixView::operator=(), ComplexMatrix::operator=(), Agenda::operator=(), ComplexVector::operator=(), Vector::operator=(), MRecord::operator=(), PropagationMatrix::operator=(), StokesVector::operator=(), Tensor3::operator=(), Tensor4::operator=(), Tensor5::operator=(), Tensor6::operator=(), Tensor7::operator=(), VectorView::operator=(), MatrixView::operator=(), Matrix::operator=(), Tensor3View::operator=(), Tensor4View::operator=(), Tensor5View::operator=(), Tensor6View::operator=(), Tensor7View::operator=(), double_istream::operator>>(), double_imanip::operator>>(), operator>>(), Raw::Mask::out_of_bounds(), Conversion::pa2atm(), Conversion::pa2torr(), ArtsParser::parse_main(), ArtsParser::parse_method(), pCqSDHC_to_arts(), pCqSDHC_to_arts_D2_deriv(), pCqSDHC_to_arts_freq_deriv(), pCqSDHC_to_arts_G2_deriv(), pol2cart(), polint(), polynomial_basis_func(), Absorption::Lines::Population(), poslos2cart(), Constant::pow2(), Constant::pow3(), Constant::pow4(), ppath_start_stepping(), Species::predefined_model_names(), Print(), print_agenda_define(), print_agenda_execute(), print_agenda_methods(), print_full_methods(), print_gin_methods(), print_groups_and_namespaces(), print_variables(), profile_(), PropagationMatrix::PropagationMatrix(), psd_mono_common(), lm_hitran_2017::qsdv(), lm_hitran_2017::qsdv_si(), QuantumIdentifierSet(), r_crossing_3d(), ran_gaussian(), random_covariance_matrix(), RationalSet(), raytrace_3d_linear_basic(), LineShape::SingleSpeciesModel::read(), read_text_from_file(), ReadArrayOfARTSCAT(), ReadARTSCAT(), ReadJPL(), ReadLBLRTM(), lm_hitran_2017::readlines(), PropagationMatrix::RemoveAtPosition(), Absorption::Lines::RemoveLocalQuantum(), reshape(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), rte_step_doit_replacement(), run_oem_matlab(), Legendre::schmidt(), Time::Seconds(), Time::seconds_into_day(), Absorption::Lines::Self(), set_constant_statistical_equilibrium_matrix(), Linefunctions::set_doppler(), set_matrixBlock(), setAbsorptionCutoffTypeString(), setAbsorptionMirroringTypeString(), setAbsorptionNormalizationTypeString(), setAbsorptionPopulationTypeString(), PropagationMatrix::SetAtPosition(), StokesVector::SetAtPosition(), LineShape::Model::SetLineMixingModel(), setLineShapeTemperatureModelString(), setLineShapeTypeString(), setQuantumIdentifierTypeString(), setQuantumNumberTypeString(), setSpeciesLongName(), setSpeciesShortName(), setSpeciesTagTypeString(), setVerbosity(), LineShape::si2cgs(), sign(), Conversion::sind(), ArtsParser::skip_to_next_argument(), solve(), sph2cart(), split_filename_species(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Interpolation::start_pos_finder(), Species::start_positions(), Raw::Average::std(), StokesVector::StokesVector(), surf_radius_at_l(), swv_mpmf87s93__(), Absorption::Lines::T0(), Conversion::tand(), Tensor3SetConstant(), Tensor4Clip(), Tensor4SetConstant(), Tensor5SetConstant(), Tensor6SetConstant(), Tensor7SetConstant(), test01(), test09(), test12(), test13(), test14(), test16(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), test26(), test34(), test42(), test44(), test6(), test7(), test8(), test_lusolve1D(), test_lusolve4D(), test_r_deriv_propagationmatrix(), test_solve_linear_system(), CompileTimeTests::testIsotopologuesAllValid(), time_stepper_selection(), to_species_map(), Time::toGMTStruct(), Conversion::torr2pa(), Time::toStruct(), transform(), transform_jacobian(), transform_x(), transform_x_back(), transmat3(), transpose(), Trapz(), ARTS::Method::Trapz(), ARTS::Agenda::Method::Trapz(), MCAntenna::Type(), EnergyLevelMap::Type(), lm_hitran_2017::typeFull(), lm_hitran_2017::typeLP(), unitl(), Absorption::Lines::validIndexForCutoff(), Absorption::Lines::validIndexForLineShapeType(), Absorption::Lines::validIndexForMirroring(), Absorption::Lines::validIndexForNormalization(), Absorption::Lines::validIndexForPopulation(), EnergyLevelMap::validIndexForType(), MCAntenna::validType(), Vector::Vector(), LineShape::LegacyLineMixingData::vector2modellm(), LineShape::LegacyPressureBroadeningData::vector2modelpb(), VectorInsertGridPoints(), VectorLinSpace(), VectorLogSpace(), VectorMatrixMultiply(), VectorNLinSpace(), VectorNLinSpaceConst(), VectorNLogSpaceConst(), vmrunitscf(), WriteBuiltinPartitionFunctionsXML(), ARTS::Method::x2artsAtmAndSurf(), x2artsAtmAndSurf(), ARTS::Method::x2artsSensor(), x2artsSensor(), ARTS::Method::xClip(), xlgr_(), and xml_read_from_stream().
xa()
Vector ARTS::Var::xa (Workspace & ws) inline noexcept
The a priori state vector.
This WSV matches directly the x_a-vector in the formalism by C.D. Rodgers.
Usage: Used by inversion methods.
Unit: Varies, follows unit of selected retrieval quantities.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10333 of file autoarts.h.
Referenced by benchmark_oem_linear(), generate_test_data(), interp_poly(), ARTS::Method::OEM(), polint(), test_oem_gauss_newton(), test_oem_gauss_newton_sparse(), test_oem_levenberg_marquardt(), test_oem_linear(), ARTS::Method::xaStandard(), and xaStandard().
xml_output_type()
Index ARTS::Var::xml_output_type (Workspace & ws) inline noexcept
Flag to determine whether XML output shall be binary or ascii.
This flag has to be set using the workspace method output_file_formatSetAscii* or output_file_formatSetBinary. One of these methods MUST be called before writing the first output file.
Usage: Set by user.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10347 of file autoarts.h.
y()
Vector ARTS::Var::y (Workspace & ws) inline noexcept
The measurement vector.
This vector holds radiances averaged in frequency and spatially, and can contain many spectra appended. That is, this WSV matches directly the y-vector in the formalism by C.D. Rodgers.
The polarisation, frequency, position and line-of-sight associated with each element in y are given by y_pol, y_f, y_pos and y_los*. For monochromatic pencil beam radiances, data are sorted in the following way, from the innermost to the outermost loop Stokes Frequency LOS inside the measurement block Measurement block With sensor response included, the order can be differ. As output of yRadar, the order will also be different.
Usage: Output from radiative transfer calculations considering sensor response.
Unit: Undefined. Possibilities include: K, W/(m^2 Hz sr) and optical thickness.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10375 of file autoarts.h.
Referenced by add(), agendas(), antenna_responseGaussian(), antenna_responseVaryingGaussian(), Conversion::atan2d(), Raw::Average::avg(), backend_channel_responseGaussian(), benchmark_oem_linear(), cart2poslos(), cart2poslos_plain(), cart2sph(), cart2sph_plain(), dabsorption_nlte_rate_dTl(), dabsorption_nlte_rate_dTu(), defocusing_general_sub(), LineShape::differenceOutput(), do_gridcell_3d_byltest(), EnergyLevelMapSet(), ARTS::Method::EnergyLevelMapSet(), ARTS::Agenda::Method::EnergyLevelMapSet(), LinearModel::evaluate(), Zeeman::FromGrids(), gaussian_response(), gaussian_response_autogrid(), generate_test_data(), geompath_tanpos_3d(), groups(), oem::ArtsLog< type >::init(), integer_div(), interp_poly(), is_multiple(), Hitran::isotopologue_ratios_impl(), iyMC(), jacobianFromTwoY(), ARTS::Method::jacobianFromTwoY(), jacobianFromYbatch(), ARTS::Method::jacobianFromYbatch(), LagrangeInterpol4(), linreg(), lsf(), matrix_vector_mult(), MCGeneral(), ARTS::Method::MCGeneral(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), methods(), StokesVector::MultiplyAndAdd(), Raw::Average::nanavg(), Raw::Average::nanstd(), Raw::Average::nanvar(), ARTS::Method::OEM(), poslos2cart(), ppath_start_stepping(), print_agenda_methods(), print_full_methods(), print_gin_methods(), profile_(), lm_hitran_2017::qsdv(), lm_hitran_2017::qsdv_si(), r_crossing_3d(), ran_gaussian(), random_covariance_matrix(), raytrace_3d_linear_basic(), sph2cart(), Raw::Average::std(), surf_radius_at_l(), test12(), test13(), test14(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), test42(), test6(), test7(), test_lusolve4D(), test_oem_linear(), Time::toGMTStruct(), Time::toStruct(), transform(), transpose(), Trapz(), ARTS::Method::Trapz(), ARTS::Agenda::Method::Trapz(), EnergyLevelMap::validIndexForType(), MCAntenna::validType(), LineShape::LegacyLineMixingData::vector2modellm(), VectorMatrixMultiply(), xml_read_from_stream(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), yApplyUnit(), ARTS::Method::yApplyUnit(), ARTS::Agenda::Execute::ybatch_calc_agenda(), ybatch_calc_agendaExecute(), ybatchCalc(), ybatchDoublingMeanFocus(), ybatchMaskOutsideMedianRange(), ybatchMetProfiles(), ybatchMetProfilesClear(), ybatchTroposphericCorrectionNaiveMedianForward(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yColdAtmHot(), ARTS::Method::yColdAtmHot(), yDoublingMeanFocus(), ARTS::Method::yDoublingMeanFocus(), yMaskOutsideMedianRange(), ARTS::Method::yMaskOutsideMedianRange(), yRadar(), ARTS::Method::yRadar(), ySimpleSpectrometer(), and ARTS::Method::ySimpleSpectrometer().
y_aux()
ArrayOfVector ARTS::Var::y_aux (Workspace & ws) inline noexcept
Data auxilary to y.
Different data beside the direct result of the radiative transfer calculations can be obtained by this variable. These auxilary data are selected by iy_aux_vars.
In contrast to iy_aux, this variable can only hold quantities such as optical depth, and other quantites that could be the result of a complete radiative transfer calculation. The data are weighted with sensor properties in the same way as for y.
See also iy_aux_vars.
Usage: Output of yCalc.
Dimensions: [quantity][ element of y ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10397 of file autoarts.h.
Referenced by yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Agenda::Execute::ybatch_calc_agenda(), ybatch_calc_agendaExecute(), ybatchCalc(), ARTS::Method::yCalc(), yCalc(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
y_baseline()
Vector ARTS::Var::y_baseline (Workspace & ws) inline noexcept
The baseline of y.
In retrieval "lingo", the baseline is an addiative disturbance of the measured spectrum. That is, it can be seen as a shift (from zero) of measurement. Reflections inside microwave receivers is one source to a baseline off-set.
So far there is no module in ARTS that actually tries to physically model any baseline effect. y_baseline is just used as a pure fitting parameter in retrievals. One example on method to include a baseline fit is jacobianAddPolyfit*.
If the baseline is totally constant, it is allowed to set y_baseline to have length one, with this element set to the baseline value.
Usage: Output of retrievals.
Unit: Same as applied for y.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10421 of file autoarts.h.
Referenced by calcBaselineFit(), ARTS::Method::x2artsSensor(), and x2artsSensor().
y_f()
Vector ARTS::Var::y_f (Workspace & ws) inline noexcept
The frequencies associated with y.
A value is returned for each element of y. Depending on the sensor set-up and number of measurement blocks, this can be a copy of sensor_response_f*, sveral copies of this vector appended, or some other frequenices.
Don't confuse this variable with yf.
Usage: Output from radiative transfer calculations considering sensor response.
Unit: [ Hz ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10440 of file autoarts.h.
Referenced by yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yApplyUnit(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), ARTS::Method::yRadar(), ySimpleSpectrometer(), and ARTS::Method::ySimpleSpectrometer().
y_geo()
Matrix ARTS::Var::y_geo (Workspace & ws) inline noexcept
The geo-positioning associated with y.
The columns of this matrix matches the elements of geo_pos.
If no geo-position is obtained (i.e. geo_pos_agenda sets geo_pos to be empty), all elements of y_geo is set to NaN.
Unit: [ m, deg, deg, deg, deg ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10454 of file autoarts.h.
Referenced by y_geoToGeodetic(), ARTS::Method::y_geoToGeodetic(), yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
y_los()
Matrix ARTS::Var::y_los (Workspace & ws) inline noexcept
The line-of-sights associated with y.
Definition of angles matches sensor_los (such as first column holds zenith angles), but gives actual observed LOS. That is, the values of both sensor_los and antenna_dlos are considered. Data are provided for each element of y, following y_f, and the number of rows equals the length of y.
Usage: Output from radiative transfer calculations considering sensor response.
Unit: [ degrees, degrees ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10472 of file autoarts.h.
Referenced by yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
y_pol()
ArrayOfIndex ARTS::Var::y_pol (Workspace & ws) inline noexcept
The polarisation states associated with y.
Data are provided for each element of y, following y_f, and the length of this variable and y is equal.
See instrument_pol for coding of polarisation components.
Usage: Output from radiative transfer calculations considering sensor response.
Unit: [ - ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10489 of file autoarts.h.
Referenced by yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yApplyUnit(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
y_pos()
Matrix ARTS::Var::y_pos (Workspace & ws) inline noexcept
The sensor positions associated with y.
Definition of positions matches sensor_pos (such as first column holds the altitude). Data are provided for each element of y, following y_f, and the number of rows equals the length of y.
Usage: Output from radiative transfer calculations considering sensor response.
Unit: [ m, deg, deg ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10505 of file autoarts.h.
Referenced by yApplySensorPol(), ARTS::Method::yApplySensorPol(), ARTS::Method::yCalc(), yCalc(), yCalc_mblock_loop_body(), yCalcAppend(), ARTS::Method::yCalcAppend(), yRadar(), and ARTS::Method::yRadar().
yb()
Vector ARTS::Var::yb (Workspace & ws) inline noexcept
The measurement vector for a single measurement block.
Exactly as y, but holds data only for a single measurement block.
Usage: Used internally.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10516 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::jacobian_agenda(), jacobian_agendaExecute(), ARTS::Method::jacobianCalcDoNothing(), jacobianCalcFreqShift(), ARTS::Method::jacobianCalcFreqShift(), jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcFreqStretch(), ARTS::Method::jacobianCalcPointingZaInterp(), ARTS::Method::jacobianCalcPointingZaRecalc(), jacobianCalcPointingZaRecalc(), ARTS::Method::jacobianCalcPolyfit(), ARTS::Method::jacobianCalcSinefit(), and yCalc_mblock_loop_body().
ybatch()
ArrayOfVector ARTS::Var::ybatch (Workspace & ws) inline noexcept
Batch of spectra.
Each element of ybatch corresponds to a spectrum vector y. See further ybatchCalc.
Usage: Most commonly produced by ybatchCalc.
Unit: Undefined. Possibilities include: K, W/(m^2 Hz sr) and optical thickness.
Dimensions: Number of array elements equals number of batch cases, Vectors have length(y)
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10534 of file autoarts.h.
Referenced by jacobianFromYbatch(), ARTS::Method::jacobianFromYbatch(), main(), ybatchCalc(), ARTS::Method::ybatchCalc(), ybatchColdAtmHotAtmCycle(), ARTS::Method::ybatchColdAtmHotAtmCycle(), ybatchDoublingMeanFocus(), ARTS::Method::ybatchDoublingMeanFocus(), ybatchMaskOutsideMedianRange(), ARTS::Method::ybatchMaskOutsideMedianRange(), ybatchMetProfiles(), ARTS::Method::ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::ybatchMetProfilesClear(), ARTS::Method::ybatchTimeAveraging(), ybatchTroposphericCorrectionNaiveMedianForward(), ARTS::Method::ybatchTroposphericCorrectionNaiveMedianForward(), ybatchTroposphericCorrectionNaiveMedianInverse(), and ARTS::Method::ybatchTroposphericCorrectionNaiveMedianInverse().
ybatch_aux()
ArrayOfArrayOfVector ARTS::Var::ybatch_aux (Workspace & ws) inline noexcept
Data auxilary to ybatch.
Each element of ybatch_aux corresponds to a auxiliary data y_aux. See further y_aux and ybatchCalc.
Usage: Most commonly produced by ybatchCalc.
Dimensions: Number of array elements equals number of batch cases,
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10548 of file autoarts.h.
Referenced by ybatchCalc(), and ARTS::Method::ybatchCalc().
ybatch_calc_agenda()
Agenda ARTS::Var::ybatch_calc_agenda (Workspace & ws) inline noexcept
Agenda defining the calculations to perform for each batch case.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10555 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::ybatch_calc_agenda(), ARTS::Agenda::Define::ybatch_calc_agenda(), and ybatchCalc().
ybatch_corr()
ArrayOfVector ARTS::Var::ybatch_corr (Workspace & ws) inline noexcept
Correction terms for ybatch.
Dimensions: Number of array elements equals number of batch cases, Vectors have length depending on correction method
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10565 of file autoarts.h.
Referenced by ybatchTroposphericCorrectionNaiveMedianForward(), ARTS::Method::ybatchTroposphericCorrectionNaiveMedianForward(), ybatchTroposphericCorrectionNaiveMedianInverse(), and ARTS::Method::ybatchTroposphericCorrectionNaiveMedianInverse().
ybatch_index()
Index ARTS::Var::ybatch_index (Workspace & ws) inline noexcept
Index of batch case.
See further ybatchCalc.
Usage: Set by ybatchCalc, for communication with ybatch_calc_agenda*.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10577 of file autoarts.h.
Referenced by ARTS::Agenda::Execute::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), DOBatchCalc(), ARTS::Agenda::Execute::ybatch_calc_agenda(), ybatch_calc_agendaExecute(), and ybatchCalc().
ybatch_jacobians()
ArrayOfMatrix ARTS::Var::ybatch_jacobians (Workspace & ws) inline noexcept
All the Jacobians associated with ybatch.
The batch index here is the array dimension.
Usage: Most commonly produced by ybatch.
Unit: Depends on unit of y and on Jacobian type.
Dimensions: [number of batch cases] (length(y), number of retrieval quantities and grids)
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10594 of file autoarts.h.
Referenced by ybatchCalc(), and ARTS::Method::ybatchCalc().
ybatch_n()
Index ARTS::Var::ybatch_n (Workspace & ws) inline noexcept
Number of batch cases for ybatchCalc.
See further ybatchCalc.
Usage: Input to ybatchCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10605 of file autoarts.h.
Referenced by DOBatchCalc(), ARTS::Method::DOBatchCalc(), ybatchCalc(), and ARTS::Method::ybatchCalc().
ybatch_start()
Index ARTS::Var::ybatch_start (Workspace & ws) inline noexcept
Start index for ybatchCalc.
This is set to a default of zero in general.arts.
See further ybatchCalc.
Usage: Input to ybatchCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10618 of file autoarts.h.
Referenced by DOBatchCalc(), ARTS::Method::DOBatchCalc(), ybatchCalc(), and ARTS::Method::ybatchCalc().
yf()
Vector ARTS::Var::yf (Workspace & ws) inline noexcept
A fitted measurement vector.
This WSV is the measurement vector matching the retrieved state, i.e. the spectrum of the fit.
Don't confuse this variable with y_f.
Usage: Output from inversion methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10632 of file autoarts.h.
Referenced by benchmark_oem_linear(), ARTS::Agenda::Execute::inversion_iterate_agenda(), inversion_iterate_agendaExecute(), and ARTS::Method::OEM().
z_field()
Tensor3 ARTS::Var::z_field (Workspace & ws) inline noexcept
The field of geometrical altitudes.
This variable gives the geometrical altitude, above the ellipsoid, of each crossing of the pressure, latitude and longitude grids. For 1D cases the altitudes give the geometrical position of the pressure levels.
For each geographical position (lat,lon), the values must be sorted in increasing order, with no repetitions. Otherwise the altitudes can be set to arbitrary values. Hydrostatic equilibrium is not applied automatically. If hydrostatic equilibrium applies, z_field must be set by a method ensuring that this criterium is fulfilled.
The radius (from the coordinate centre) for a point between the grid crossings is obtained by a (multi-)linear interpolation of the sum of the ellipsoid radius and z_field.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Output of AtmFieldsCalc
Unit: m
Dimensions: [ p_grid, lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10664 of file autoarts.h.
Referenced by abs_lookupSetupBatch(), AtmFieldsAndParticleBulkPropFieldFromCompact(), ARTS::Method::AtmFieldsAndParticleBulkPropFieldFromCompact(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmFieldsExpand1D(), ARTS::Method::AtmFieldsExpand1D(), AtmFieldsExtract1D(), ARTS::Method::AtmFieldsExtract1D(), AtmFieldsRefinePgrid(), ARTS::Method::AtmFieldsRefinePgrid(), atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), cloudboxSetManuallyAltitude(), ARTS::Method::cloudboxSetManuallyAltitude(), IGRF::compute(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), field_of_propagation(), get_refr_index_1d(), get_refr_index_2d(), get_refr_index_3d(), GriddedFieldZToPRegrid(), ARTS::Method::GriddedFieldZToPRegrid(), InterpAtmFieldToPosition(), ARTS::Method::InterpAtmFieldToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyIndependentBeamApproximation(), ARTS::Method::iyIndependentBeamApproximation(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), ARTS::Method::line_irradianceCalcForSingleSpeciesNonOverlappingLinesPseudo2D(), MagFieldsCalcIGRF(), ARTS::Method::MagFieldsCalcIGRF(), MagFieldsFromAltitudeRawCalc(), ARTS::Method::MagFieldsFromAltitudeRawCalc(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), nlte_fieldForSingleSpeciesNonOverlappingLines(), ARTS::Method::nlte_fieldForSingleSpeciesNonOverlappingLines(), OptimizeDoitPressureGrid(), ARTS::Method::OptimizeDoitPressureGrid(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_fieldFromDownUpLimbGeoms(), ARTS::Method::ppath_fieldFromDownUpLimbGeoms(), ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), ppath_step_geom_1d(), ppath_step_geom_2d(), ppath_step_geom_3d(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), raytrace_3d_linear_basic(), refr_gradients_1d(), refr_gradients_2d(), refr_gradients_3d(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), rte_pos2gridpos(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::VectorZtanToZaRefr1D(), VectorZtanToZaRefr1D(), ARTS::Method::wind_u_fieldIncludePlanetRotation(), WriteMolTau(), ARTS::Method::WriteMolTau(), z_at_lat_2d(), z_at_latlon(), and ARTS::Method::z_fieldFromHSE().
z_field_raw()
GriddedField3 ARTS::Var::z_field_raw (Workspace & ws) inline noexcept
Raw data for geometrical altitudes.
This variable gives the geometrical altitudes as stored in the database for atmospheric scenarios.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by the user by choosing a climatology.
Unit: K
Size GriddedField3 [N_p] [N_lat] [N_lon] [N_p, N_lat, N_lon]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10688 of file autoarts.h.
Referenced by ARTS::Method::atm_gridsFromZRaw(), AtmFieldsCalc(), ARTS::Method::AtmFieldsCalc(), AtmFieldsCalcExpand1D(), ARTS::Method::AtmFieldsCalcExpand1D(), AtmRawRead(), ARTS::Method::AtmRawRead(), AtmWithNLTERawRead(), ARTS::Method::AtmWithNLTERawRead(), ARTS::Method::lat_gridFromZRaw(), ARTS::Method::lon_gridFromZRaw(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ARTS::Method::p_gridFromZRaw(), ybatchMetProfiles(), and ybatchMetProfilesClear().
z_hse_accuracy()
Numeric ARTS::Var::z_hse_accuracy (Workspace & ws) inline noexcept
Minimum accuracy for calculation of hydrostatic equilibrium.
Usage: Set by the user.
Unit: m
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10699 of file autoarts.h.
Referenced by ARTS::Method::z_fieldFromHSE().
z_surface()
Matrix ARTS::Var::z_surface (Workspace & ws) inline noexcept
The surface altitude.
This variable defines the shape of the surface, by giving the geometrical altitude above the geiod for each crossing of the latitude and longitude grids. Any shape of the surface is accepted. No gap between the surface and the lowermost pressure level is allowed.
The radius (from the coordinate centre) for a point between the grid crossings is obtained by a linear (1D) or bi-linear (2D) interpolation of the sum of the ellipsoid radius and z_surface. That is, the radius for the surface is assumed to vary linear along the latitudes and longitudes in lat_grid and lon_grid.
See further the ARTS user guide (AUG). Use the index to find where this variable is discussed. The variable is listed as a subentry to "workspace variables".
Usage: Set by user.
Unit: m
Dimensions: [ lat_grid, lon_grid ]
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10728 of file autoarts.h.
Referenced by atmgeom_checkedCalc(), ARTS::Method::atmgeom_checkedCalc(), cloudbox_checkedCalc(), ARTS::Method::cloudbox_checkedCalc(), defocusing_general(), defocusing_general_sub(), defocusing_sat2sat(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), index_of_zsurface(), InterpSurfaceFieldToPosition(), ARTS::Method::InterpSurfaceFieldToPosition(), ARTS::Agenda::Execute::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), iyMC(), ARTS::Method::iyMC(), MCGeneral(), ARTS::Method::MCGeneral(), mcPathTraceRadar(), MCRadar(), ARTS::Method::MCRadar(), ARTS::Agenda::Execute::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), particle_bulkpropRadarOnionPeeling(), ARTS::Method::particle_bulkpropRadarOnionPeeling(), ppath_calc(), ppath_start_2d(), ppath_start_stepping(), ppath_step_geom_1d(), ppath_step_geom_2d(), ppath_step_geom_3d(), ppath_step_refr_1d(), ppath_step_refr_2d(), ppath_step_refr_3d(), ppath_stepGeometric(), ARTS::Method::ppath_stepGeometric(), ARTS::Method::ppath_stepRefractionBasic(), ppath_stepRefractionBasic(), ARTS::Method::ppathFixedLstep(), ppathFromRtePos2(), ARTS::Method::ppathFromRtePos2(), ppathPlaneParallel(), ARTS::Method::ppathPlaneParallel(), ARTS::Method::ppathStepByStep(), ppathStepByStep(), reduced_1datm(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), run_cdisort(), ScatSpeciesMerge(), ARTS::Method::ScatSpeciesMerge(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), specular_losCalc(), ARTS::Method::specular_losCalc(), surf_radius_at_l(), ybatchMetProfiles(), ybatchMetProfilesClear(), ARTS::Method::z_fieldFromHSE(), z_surfaceConstantAltitude(), ARTS::Method::z_surfaceConstantAltitude(), z_surfaceFromFileAndGrid(), and ARTS::Method::z_surfaceFromFileAndGrid().
za_grid()
Vector ARTS::Var::za_grid (Workspace & ws) inline noexcept
Zenith angle grid.
The zenith angle grid, on which the cloudbox_field is stored. This grid is used for RT calculations inside the cloudbox, therefore the grid has to be defined if the cloudbox is activated by the flag cloudbox_on*. Furthermore the zenith angle grid is also used for RT calculations of clear-sky spectral radiance field. The grid must be sorted in increasing order, with no repetitions.
Usage: Set by the user.
Unit: degrees
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10746 of file autoarts.h.
Referenced by AngIntegrate_trapezoid(), AngIntegrate_trapezoid_fixedstep(), AngIntegrate_trapezoid_fixedstep_opt(), AngIntegrate_trapezoid_fixedstep_opt2(), AngIntegrate_trapezoid_opt(), AngIntegrate_trapezoid_opti(), AngIntegrate_trapezoid_original(), AngularGridsSetFluxCalc(), ARTS::Method::AngularGridsSetFluxCalc(), antenna1d_matrix(), antenna2d_gridded_dlos(), check_disort_input(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_surface(), cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldSetFromPrecalc(), ARTS::Method::cloudbox_fieldUpdate1D(), cloudbox_fieldUpdate1D(), cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1D(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), ARTS::Method::cloudbox_fieldUpdateSeq3D(), cloudbox_fieldUpdateSeq3D(), DisortCalc(), ARTS::Method::DisortCalc(), DisortCalcClearsky(), ARTS::Method::DisortCalcClearsky(), DisortCalcWithARTSSurface(), ARTS::Method::DisortCalcWithARTSSurface(), DOAngularGridsSet(), ARTS::Method::DOAngularGridsSet(), ARTS::Method::doit_scat_fieldCalc(), doit_scat_fieldCalc(), ARTS::Method::doit_scat_fieldCalcLimb(), doit_scat_fieldCalcLimb(), doit_scat_fieldNormalize(), doit_za_grid_optCalc(), ARTS::Method::doit_za_grid_optCalc(), DoitGetIncoming(), ARTS::Method::DoitGetIncoming(), ARTS::Method::DoitGetIncoming1DAtm(), DoitGetIncoming1DAtm(), DoitInit(), ARTS::Method::DoitInit(), DoitScatteringDataPrepare(), get_angs(), get_stepwise_scattersky_source(), init_xy(), interp_cloud_coeff1D(), irradiance_fieldFromRadiance(), ARTS::Method::irradiance_fieldFromRadiance(), iyHybrid(), ARTS::Method::iyHybrid(), iyInterpCloudboxField(), ARTS::Method::iyInterpCloudboxField(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matTransform(), pnd_fieldZero(), ARTS::Method::RT4Calc(), ARTS::Method::RT4CalcWithRT4Surface(), run_cdisort(), spectral_irradiance_fieldFromSpectralRadianceField(), ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField(), spectral_radiance_fieldClearskyPlaneParallel(), ARTS::Method::spectral_radiance_fieldClearskyPlaneParallel(), spectral_radiance_fieldExpandCloudboxField(), ARTS::Method::spectral_radiance_fieldExpandCloudboxField(), test_AngIntegrate_trapezoid_opti(), test_xy(), test_xy_fixedstep(), test_xy_fixedstep_opt(), test_xy_fixedstep_opt2(), and test_xy_opt().
za_grid_weights()
Vector ARTS::Var::za_grid_weights (Workspace & ws) inline noexcept
Zenith angle integration weights.
The integration weight are needed for calculation of radiation fluxes
Unit: unitless
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10757 of file autoarts.h.
Referenced by AngularGridsSetFluxCalc(), ARTS::Method::AngularGridsSetFluxCalc(), irradiance_fieldFromRadiance(), ARTS::Method::irradiance_fieldFromRadiance(), spectral_irradiance_fieldFromSpectralRadianceField(), and ARTS::Method::spectral_irradiance_fieldFromSpectralRadianceField().
za_index()
Index ARTS::Var::za_index (Workspace & ws) inline noexcept
Zenith angle index for scattering calculations.
This variable is used internally in WSMs for computing scattering properties.
Usage: Input to the agendas spt_calc_agenda, pha_mat_spt_agenda*.
Parameters
[in,out] Workspace ws - An ARTS workspace
Returns
A class with a pointer to this variable and its position in the workspace
Definition at line 10770 of file autoarts.h.
Referenced by cloud_fieldsCalc(), cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update1D_planeparallel(), cloud_ppath_update3D(), cloud_RT_surface(), cloudbox_field_ngAcceleration(), cloudbox_fieldSetClearsky(), ARTS::Method::cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq1DPP(), cloudbox_fieldUpdateSeq3D(), doit_conv_flagAbs(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), DoitGetIncoming(), DoitGetIncoming1DAtm(), opt_prop_sptFromData(), ARTS::Method::opt_prop_sptFromData(), opt_prop_sptFromMonoData(), ARTS::Method::opt_prop_sptFromMonoData(), opt_prop_sptFromScat_data(), ARTS::Method::opt_prop_sptFromScat_data(), ARTS::Agenda::Execute::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), pha_mat_sptFromData(), ARTS::Method::pha_mat_sptFromData(), pha_mat_sptFromDataDOITOpt(), ARTS::Method::pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), ARTS::Method::pha_mat_sptFromMonoData(), pha_mat_sptFromScat_data(), ARTS::Method::pha_mat_sptFromScat_data(), pha_matCalc(), ARTS::Agenda::Execute::spt_calc_agenda(), and spt_calc_agendaExecute().