ARTS: Interpolation Namespace Reference
Interpolation Namespace Reference
Namespaces
nonstd
Classes
class Grid
Row-major grid creation.
class FixedGrid
Row-major fixed grid creation.
struct Lagrange
A Lagrange interpolation computer.
struct FixedLagrange
Functions
Array< Lagrange > LagrangeVector (const ConstVectorView &xs, const ConstVectorView &xi, const Index polyorder, const Numeric extrapol, const bool do_derivs, const GridType type, const std::pair< Numeric, Numeric > cycle)
Vector interpweights (const Lagrange &dim0)
Grid< Vector, 1 > interpweights (const Array< Lagrange > &dim0)
Vector dinterpweights (const Lagrange &dim0)
Grid< Vector, 1 > dinterpweights (const Array< Lagrange > &dim0)
Numeric interp (const ConstVectorView &yi, const ConstVectorView &iw, const Lagrange &dim0)
void reinterp (VectorView out, const ConstVectorView &iy, const Grid< Vector, 1 > &iw, const Array< Lagrange > &dim0)
Vector reinterp (const ConstVectorView &iy, const Grid< Vector, 1 > &iw, const Array< Lagrange > &dim0)
Matrix interpweights (const Lagrange &dim0, const Lagrange &dim1)
Grid< Matrix, 2 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1)
Matrix dinterpweights (const Lagrange &dim0, const Lagrange &dim1, Index dim)
Grid< Matrix, 2 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, Index dim)
Numeric interp (const ConstMatrixView &yi, const ConstMatrixView &iw, const Lagrange &dim0, const Lagrange &dim1)
void reinterp (MatrixView out, const ConstMatrixView &iy, const Grid< Matrix, 2 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1)
Matrix reinterp (const ConstMatrixView &iy, const Grid< Matrix, 2 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1)
Tensor3 interpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2)
Grid< Tensor3, 3 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2)
Tensor3 dinterpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, Index dim)
Grid< Tensor3, 3 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, Index dim)
Numeric interp (const ConstTensor3View &yi, const ConstTensor3View &iw, const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2)
void reinterp (Tensor3View out, const ConstTensor3View &iy, const Grid< Tensor3, 3 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2)
Tensor3 reinterp (const ConstTensor3View &iy, const Grid< Tensor3, 3 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2)
Tensor4 interpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3)
Grid< Tensor4, 4 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3)
Tensor4 dinterpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, Index dim)
Grid< Tensor4, 4 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, Index dim)
Numeric interp (const ConstTensor4View &yi, const ConstTensor4View &iw, const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3)
void reinterp (Tensor4View out, const ConstTensor4View &iy, const Grid< Tensor4, 4 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3)
Tensor4 reinterp (const ConstTensor4View &iy, const Grid< Tensor4, 4 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3)
Tensor5 interpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4)
Grid< Tensor5, 5 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4)
Tensor5 dinterpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, Index dim)
Grid< Tensor5, 5 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, Index dim)
Numeric interp (const ConstTensor5View &yi, const ConstTensor5View &iw, const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4)
void reinterp (Tensor5View out, const ConstTensor5View &iy, const Grid< Tensor5, 5 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4)
Tensor5 reinterp (const ConstTensor5View &iy, const Grid< Tensor5, 5 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4)
Tensor6 interpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5)
Grid< Tensor6, 6 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5)
Tensor6 dinterpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5, Index dim)
Grid< Tensor6, 6 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5, Index dim)
Numeric interp (const ConstTensor6View &yi, const ConstTensor6View &iw, const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5)
void reinterp (Tensor6View out, const ConstTensor6View &iy, const Grid< Tensor6, 6 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5)
Tensor6 reinterp (const ConstTensor6View &iy, const Grid< Tensor6, 6 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5)
Tensor7 interpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5, const Lagrange &dim6)
Grid< Tensor7, 7 > interpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5, const Array< Lagrange > &dim6)
Tensor7 dinterpweights (const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5, const Lagrange &dim6, Index dim)
Grid< Tensor7, 7 > dinterpweights (const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5, const Array< Lagrange > &dim6, Index dim)
Numeric interp (const ConstTensor7View &yi, const ConstTensor7View &iw, const Lagrange &dim0, const Lagrange &dim1, const Lagrange &dim2, const Lagrange &dim3, const Lagrange &dim4, const Lagrange &dim5, const Lagrange &dim6)
void reinterp (Tensor7View out, const ConstTensor7View &iy, const Grid< Tensor7, 7 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5, const Array< Lagrange > &dim6)
Tensor7 reinterp (const ConstTensor7View &iy, const Grid< Tensor7, 7 > &iw, const Array< Lagrange > &dim0, const Array< Lagrange > &dim1, const Array< Lagrange > &dim2, const Array< Lagrange > &dim3, const Array< Lagrange > &dim4, const Array< Lagrange > &dim5, const Array< Lagrange > &dim6)
template<typename... Inds>
constexpr std::size_t mul (Inds... inds) noexcept
template<std::size_t N>
constexpr std::size_t mul (const std::array< std::size_t, N > &arr) noexcept
template<typename... Inds>
constexpr std::array< std::size_t, sizeof...(Inds)> gridsize_from_index (Inds... inds) noexcept
template<std::size_t N>
constexpr std::size_t index_from_gridsize (std::array< std::size_t, N > gridsize, std::array< std::size_t, N > inds) noexcept
constexpr Index cycler (const Index n, const Index N) noexcept
constexpr Numeric cyclic_clamp (const Numeric x, const std::pair< Numeric, Numeric > xlim) noexcept
constexpr Numeric min_cyclic (const Numeric x, const std::pair< Numeric, Numeric > xlim) noexcept
constexpr bool full_cycle (const Numeric xo, const Numeric xn, const std::pair< Numeric, Numeric > xlim) noexcept
template<class SortedVectorType >
constexpr Index start_pos_finder (const Numeric x, const SortedVectorType &xvec) noexcept
constexpr Index IMAX (const Index a, const Index b) noexcept
Return the maximum of two integer numbers.
constexpr Index IMIN (const Index a, const Index b) noexcept
Return the minimum of two integer numbers.
template<class SortedVectorType >
constexpr Index pos_finder (const Index pos0, const Numeric x, const SortedVectorType &xi, const Index polyorder, const bool cyclic, const bool ascending, const std::pair< Numeric, Numeric > cycle={ -180, 180}) noexcept
ENUMCLASS (GridType, char, Standard, Cyclic, Log, Log10, Log2, SinDeg, SinRad, CosDeg, CosRad)
template<GridType type, class SortedVectorType >
constexpr Numeric l (const Index p0, const Index n, const Numeric x, const SortedVectorType &xi, const Index j, [[maybe_unused]] const std::pair< Numeric, Numeric > cycle={ -180, 180}) noexcept
template<GridType type, class SortedVectorType , class LagrangeVectorType >
constexpr double dl_dval (const Index p0, const Index n, const Numeric x, const SortedVectorType &xi, [[maybe_unused]] const LagrangeVectorType &li, const Index j, const Index i, [[maybe_unused]] const std::pair< Numeric, Numeric > cycle) noexcept
template<GridType type, class SortedVectorType , class LagrangeVectorType >
constexpr Numeric dl (const Index p0, const Index n, const Numeric x, const SortedVectorType &xi, const LagrangeVectorType &li, const Index j, const std::pair< Numeric, Numeric > cycle={-180, 180}) noexcept
template<class SortedVectorType >
constexpr bool is_ascending (const SortedVectorType &xi) noexcept
Checks whether the Sorted Vector is ascending or not by checking its first two elements.
template<class SortedVectorType >
void check_lagrange_interpolation ([[maybe_unused]] const SortedVectorType &xi, [[maybe_unused]] const Index polyorder=1, [[maybe_unused]] const std::pair< Numeric, Numeric > x={std::numeric_limits< Numeric >::infinity(), -std::numeric_limits< Numeric >::infinity()}, [[maybe_unused]] const Numeric extrapol=0.5, [[maybe_unused]] const GridType type=GridType::Standard, [[maybe_unused]] const std::pair< Numeric, Numeric > cycle={-180, 180})
template<class SortedVectorType >
void check_lagrange_interpolation ([[maybe_unused]] const SortedVectorType &xi, [[maybe_unused]] const Index polyorder, [[maybe_unused]] const Numeric x, [[maybe_unused]] const Numeric extrapol=0.5, [[maybe_unused]] const GridType type=GridType::Standard, [[maybe_unused]] const std::pair< Numeric, Numeric > cycle={-180, 180})
template<std::size_t PolyOrder, class UnsortedVectorType , class SortedVectorType >
Array< FixedLagrange< PolyOrder > > FixedLagrangeVector (const UnsortedVectorType &xs, const SortedVectorType &xi, const bool do_derivs=false, const GridType type=GridType::Standard, const std::pair< Numeric, Numeric > cycle={-180, 180})
template<std::size_t PolyOrder>
constexpr const std::array< Numeric, PolyOrder+1 > & interpweights (const FixedLagrange< PolyOrder > &dim0)
template<std::size_t PolyOrder>
Grid< std::array< Numeric, PolyOrder+1 >, 1 > interpweights (const Array< FixedLagrange< PolyOrder >> &dim0)
template<std::size_t PolyOrder>
constexpr std::array< Numeric, PolyOrder+1 > dinterpweights (const FixedLagrange< PolyOrder > &dim0)
template<std::size_t PolyOrder>
Grid< std::array< Numeric, PolyOrder+1 >, 1 > dinterpweights (const Array< FixedLagrange< PolyOrder >> &dim0)
template<std::size_t PolyOrder, class VectorType >
constexpr Numeric interp (const VectorType &yi, const std::array< Numeric, PolyOrder+1 > &iw, const FixedLagrange< PolyOrder > &dim0)
template<std::size_t PolyOrder>
Vector reinterp (const ConstVectorView &iy, const Grid< std::array< Numeric, PolyOrder+1 >, 1 > &iw, const Array< FixedLagrange< PolyOrder >> &dim0)
template<std::size_t PolyOrder0, std::size_t PolyOrder1>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 >, 2 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 >, 2 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, class MatrixType >
constexpr Numeric interp (const MatrixType &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1>
Matrix reinterp (const ConstMatrixView &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 >, 2 > &iw, const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 >, 3 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 >, 3 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, class Tensor3Type >
constexpr Numeric interp (const Tensor3Type &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2>
Tensor3 reinterp (const ConstTensor3View &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 >, 3 > &iw, const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 >, 4 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 >, 4 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, class Tensor4Type >
constexpr Numeric interp (const Tensor4Type &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3>
Tensor4 reinterp (const ConstTensor4View &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 >, 4 > &iw, const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 >, 5 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 >, 5 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, class Tensor5Type >
constexpr Numeric interp (const Tensor5Type &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4>
Tensor5 reinterp (const ConstTensor5View &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 >, 5 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 >, 6 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 >, 6 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, class Tensor6Type >
constexpr Numeric interp (const Tensor6Type &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5>
Tensor6 reinterp (const ConstTensor6View &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 >, 6 > &iw, const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 > interpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5, const FixedLagrange< PolyOrder6 > &dim6)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 >, 7 > interpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5, const Array< FixedLagrange< PolyOrder6 >> &dim6)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, std::size_t DerivativeDim>
constexpr FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 > dinterpweights (const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5, const FixedLagrange< PolyOrder6 > &dim6)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, std::size_t DerivativeDim>
Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 >, 7 > dinterpweights (const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5, const Array< FixedLagrange< PolyOrder6 >> &dim6)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, class Tensor7Type >
constexpr Numeric interp (const Tensor7Type &yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 > &iw, const FixedLagrange< PolyOrder0 > &dim0, const FixedLagrange< PolyOrder1 > &dim1, const FixedLagrange< PolyOrder2 > &dim2, const FixedLagrange< PolyOrder3 > &dim3, const FixedLagrange< PolyOrder4 > &dim4, const FixedLagrange< PolyOrder5 > &dim5, const FixedLagrange< PolyOrder6 > &dim6)
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6>
Tensor7 reinterp (const ConstTensor7View &iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 >, 7 > &iw, const Array< FixedLagrange< PolyOrder0 >> &dim0, const Array< FixedLagrange< PolyOrder1 >> &dim1, const Array< FixedLagrange< PolyOrder2 >> &dim2, const Array< FixedLagrange< PolyOrder3 >> &dim3, const Array< FixedLagrange< PolyOrder4 >> &dim4, const Array< FixedLagrange< PolyOrder5 >> &dim5, const Array< FixedLagrange< PolyOrder6 >> &dim6)
Function Documentation
check_lagrange_interpolation() [1/2]
template<class SortedVectorType > void Interpolation::check_lagrange_interpolation ([[maybe_unused] ] const SortedVectorType & xi, [[maybe_unused] ] const Index polyorder, [[maybe_unused] ] const Numeric x, [[maybe_unused] ] const Numeric extrapol = 0.5, [[maybe_unused] ] const GridType type = GridType::Standard, [[maybe_unused] ] const std::pair< Numeric, Numeric > cycle = {-180, 180})
Checks the interpolation grid and throws if it is bad
Parameters
[in] xi Old grid positions
[in] polyorder Polynominal degree
[in] x New grid position
[in] extrapol Level of extrapolation
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 658 of file interpolation_lagrange.h.
check_lagrange_interpolation() [2/2]
template<class SortedVectorType > void Interpolation::check_lagrange_interpolation ([[maybe_unused] ] const SortedVectorType & xi, [[maybe_unused] ] const Index polyorder = 1, [[maybe_unused] ] const std::pair< Numeric, Numeric > x = {std::numeric_limits<Numeric>::infinity(), -std::numeric_limits<Numeric>::infinity()}, [[maybe_unused] ] const Numeric extrapol = 0.5, [[maybe_unused] ] const GridType type = GridType::Standard, [[maybe_unused] ] const std::pair< Numeric, Numeric > cycle = {-180, 180})
Checks the interpolation grid and throws if it is bad
Parameters
[in] xi Old grid positions
[in] polyorder Polynominal degree
[in] x {Min new x, Max new x}
[in] extrapol Level of extrapolation
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 617 of file interpolation_lagrange.h.
Referenced by LagrangeVector().
cycler()
constexpr Index Interpolation::cycler (const Index n, const Index N) constexpr noexcept
Cycle once back through a list
Parameters
[in] n Index in a list 0 <= n < 2*N
[in] N Index size of a list
Returns
n - N if n >= N else n
Definition at line 219 of file interpolation_lagrange.h.
References N.
Referenced by dl_dval(), and interp().
cyclic_clamp()
constexpr Numeric Interpolation::cyclic_clamp (const Numeric x, const std::pair< Numeric, Numeric > xlim) constexpr noexcept
Clamp the value within a cycle by recursion
Note that your compiler will have a hard limit on recursion. If this is reached, this function will fail. If you even encounter this issue, the code below must be updated
Parameters
[in] x Value to clamp
[in] xlim [Lower, Upper) bound of cycle
Returns
Value of x in the cycle [Lower, Upper)
Definition at line 232 of file interpolation_lagrange.h.
References x.
Referenced by dl_dval(), and test26().
dinterpweights() [1/28]
template<std::size_t PolyOrder> Grid<std::array<Numeric, PolyOrder + 1>, 1> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder >> & dim0)
Interpolation weights derivative for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights derivative along 0th dimension
Definition at line 1174 of file interpolation_lagrange.h.
References dinterpweights().
dinterpweights() [2/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1>, 2> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1)
Interpolation weights derivative for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim - Axis along which to compute the derivatives
Returns
Matrix - interpweights derivative along dim dimension
Definition at line 1373 of file interpolation_lagrange.h.
dinterpweights() [3/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1>, 3> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2)
Interpolation weights derivative for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim - Axis along which to compute the derivatives
Returns
Tensor3 - interpweights derivative along dim dimension
Definition at line 1616 of file interpolation_lagrange.h.
dinterpweights() [4/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1>, 4> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3)
Interpolation weights derivative for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim - Axis along which to compute the derivatives
Returns
Tensor4 - interpweights derivative along dim dimension
Definition at line 1909 of file interpolation_lagrange.h.
dinterpweights() [5/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1>, 5> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4)
Interpolation weights derivative for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim - Axis along which to compute the derivatives
Returns
Tensor5 - interpweights derivative along dim dimension
Definition at line 2243 of file interpolation_lagrange.h.
dinterpweights() [6/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1>, 6> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5)
Interpolation weights derivative for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim - Axis along which to compute the derivatives
Returns
Tensor6 - interpweights derivative along dim dimension
Definition at line 2616 of file interpolation_lagrange.h.
dinterpweights() [7/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, std::size_t DerivativeDim> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1, PolyOrder6 + 1>, 7> Interpolation::dinterpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5, const Array< FixedLagrange< PolyOrder6 >> & dim6)
Interpolation weights derivative for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
[in] dim - Axis along which to compute the derivatives
Returns
Tensor7 - interpweights derivative along dim dimension
Definition at line 3033 of file interpolation_lagrange.h.
dinterpweights() [8/28]
Grid< Vector, 1 > Interpolation::dinterpweights (const Array< Lagrange > & dim0)
Interpolation weights derivative for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights derivative along 0th dimension
Definition at line 49 of file interpolation_lagrange.cc.
References dinterpweights().
dinterpweights() [9/28]
Grid< Tensor7, 7 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5, const Array< Lagrange > & dim6, Index dim)
Interpolation weights derivative for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
[in] dim - Axis along which to compute the derivatives
Returns
Tensor7 - interpweights derivative along dim dimension
Definition at line 760 of file interpolation_lagrange.cc.
dinterpweights() [10/28]
Grid< Tensor6, 6 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5, Index dim)
Interpolation weights derivative for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim - Axis along which to compute the derivatives
Returns
Tensor6 - interpweights derivative along dim dimension
Definition at line 593 of file interpolation_lagrange.cc.
dinterpweights() [11/28]
Grid< Tensor5, 5 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, Index dim)
Interpolation weights derivative for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim - Axis along which to compute the derivatives
Returns
Tensor5 - interpweights derivative along dim dimension
Definition at line 448 of file interpolation_lagrange.cc.
dinterpweights() [12/28]
Grid< Tensor4, 4 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, Index dim)
Interpolation weights derivative for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim - Axis along which to compute the derivatives
Returns
Tensor4 - interpweights derivative along dim dimension
Definition at line 320 of file interpolation_lagrange.cc.
dinterpweights() [13/28]
Grid< Tensor3, 3 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, Index dim)
Interpolation weights derivative for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim - Axis along which to compute the derivatives
Returns
Tensor3 - interpweights derivative along dim dimension
Definition at line 215 of file interpolation_lagrange.cc.
dinterpweights() [14/28]
Grid< Matrix, 2 > Interpolation::dinterpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, Index dim)
Interpolation weights derivative for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim - Axis along which to compute the derivatives
Returns
Matrix - interpweights derivative along dim dimension
Definition at line 124 of file interpolation_lagrange.cc.
References dinterpweights().
dinterpweights() [15/28]
template<std::size_t PolyOrder> constexpr std::array<Numeric, PolyOrder + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder > & dim0) constexpr
Interpolation weights derivative for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights derivative along 0th dimension
Definition at line 1163 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::dlx.
dinterpweights() [16/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1) constexpr
Interpolation weights derivative for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim - Axis along which to compute the derivatives
Returns
Matrix - interpweights derivative along dim dimension
Definition at line 1351 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::dlx, Interpolation::FixedLagrange< PolyOrder >::lx, and Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [17/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2) constexpr
Interpolation weights derivative for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim - Axis along which to compute the derivatives
Returns
Tensor3 - interpweights derivative along dim dimension
Definition at line 1590 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [18/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3) constexpr
Interpolation weights derivative for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim - Axis along which to compute the derivatives
Returns
Tensor4 - interpweights derivative along dim dimension
Definition at line 1874 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [19/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4) constexpr
Interpolation weights derivative for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim - Axis along which to compute the derivatives
Returns
Tensor5 - interpweights derivative along dim dimension
Definition at line 2203 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [20/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5) constexpr
Interpolation weights derivative for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim - Axis along which to compute the derivatives
Returns
Tensor6 - interpweights derivative along dim dimension
Definition at line 2571 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [21/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, std::size_t DerivativeDim> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1, PolyOrder6 + 1> Interpolation::dinterpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5, const FixedLagrange< PolyOrder6 > & dim6) constexpr
Interpolation weights derivative for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
[in] dim - Axis along which to compute the derivatives
Returns
Tensor7 - interpweights derivative along dim dimension
Definition at line 2984 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
dinterpweights() [22/28]
Vector Interpolation::dinterpweights (const Lagrange & dim0)
Interpolation weights derivative for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights derivative along 0th dimension
Definition at line 47 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::dlx.
Referenced by dinterpweights(), SingleCalculatePartitionFctFromData_dT(), test14(), test17(), test18(), test19(), test20(), test21(), test22(), test23(), test25(), and test26().
dinterpweights() [23/28]
Tensor7 Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5, const Lagrange & dim6, Index dim)
Interpolation weights derivative for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
[in] dim - Axis along which to compute the derivatives
Returns
Tensor7 - interpweights derivative along dim dimension
Definition at line 736 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
dinterpweights() [24/28]
Tensor6 Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5, Index dim)
Interpolation weights derivative for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim - Axis along which to compute the derivatives
Returns
Tensor6 - interpweights derivative along dim dimension
Definition at line 573 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
dinterpweights() [25/28]
Tensor5 Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, Index dim)
Interpolation weights derivative for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim - Axis along which to compute the derivatives
Returns
Tensor5 - interpweights derivative along dim dimension
Definition at line 431 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
dinterpweights() [26/28]
Tensor4 Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, Index dim)
Interpolation weights derivative for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim - Axis along which to compute the derivatives
Returns
Tensor4 - interpweights derivative along dim dimension
Definition at line 306 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
dinterpweights() [27/28]
Tensor3 Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, Index dim)
Interpolation weights derivative for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim - Axis along which to compute the derivatives
Returns
Tensor3 - interpweights derivative along dim dimension
Definition at line 203 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
dinterpweights() [28/28]
Matrix Interpolation::dinterpweights (const Lagrange & dim0, const Lagrange & dim1, Index dim)
Interpolation weights derivative for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim - Axis along which to compute the derivatives
Returns
Matrix - interpweights derivative along dim dimension
Definition at line 115 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::dlx, Interpolation::Lagrange::lx, and Interpolation::Lagrange::size().
dl()
template<GridType type, class SortedVectorType , class LagrangeVectorType > constexpr Numeric Interpolation::dl (const Index p0, const Index n, const Numeric x, const SortedVectorType & xi, const LagrangeVectorType & li, const Index j, const std::pair< Numeric, Numeric > cycle = {-180, 180}) constexpr noexcept
Computes the derivatives of the weights for a given coefficient
Parameters
[in] p0 The origin position
[in] n The number of weights
[in] x The position for the weights
[in] xi The sorted vector of values
[in] li The Lagrange weights
[in] j The current coefficient
[in] cycle The size of a cycle (optional)
Definition at line 584 of file interpolation_lagrange.h.
Referenced by defocusing_general_sub(), get_pmom(), get_ppath_transmat(), and mcPathTraceRadar().
dl_dval()
template<GridType type, class SortedVectorType , class LagrangeVectorType > constexpr double Interpolation::dl_dval (const Index p0, const Index n, const Numeric x, const SortedVectorType & xi, [[maybe_unused] ] const LagrangeVectorType & li, const Index j, const Index i, [[maybe_unused] ] const std::pair< Numeric, Numeric > cycle) constexpr noexcept
Computes the derivatives of the weights for a given coefficient for a given weight
If x is on the grid, this is more expensive than if x is not on the grid
Parameters
[in] p0 The origin position
[in] n The number of weights
[in] x The position for the weights
[in] xi The sorted vector of values
[in] li The Lagrange weights
[in] j The current coefficient
[in] i The current wight Index
[in] cycle The size of a cycle (optional)
Definition at line 498 of file interpolation_lagrange.h.
References cycler(), cyclic_clamp(), full_cycle(), min_cyclic(), N, and x.
ENUMCLASS()
Interpolation::ENUMCLASS (GridType , char , Standard , Cyclic , Log , Log10 , Log2 , SinDeg , SinRad , CosDeg , CosRad)
Type of Lagrange interpolation weights
Note that Cyclic interpolation has reduced poly-order crossing the cycle if both the start and the end of the cycle are in the original x-data and the polyorder is above 1.
Note that all derivatives are linear regardless of the type
FixedLagrangeVector()
template<std::size_t PolyOrder, class UnsortedVectorType , class SortedVectorType > Array<FixedLagrange<PolyOrder> > Interpolation::FixedLagrangeVector (const UnsortedVectorType & xs, const SortedVectorType & xi, const bool do_derivs = false, const GridType type = GridType::Standard, const std::pair< Numeric, Numeric > cycle = {-180, 180})
Gets a vector of Lagrange interpolation points
Estimates start position using start_pos_finder
Parameters
[in] x New grid positions
[in] xi Old grid positions
[in] do_derivs Flag to activate derivative calculations
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Returns
vector of FixedLagrange
Definition at line 1076 of file interpolation_lagrange.h.
full_cycle()
constexpr bool Interpolation::full_cycle (const Numeric xo, const Numeric xn, const std::pair< Numeric, Numeric > xlim) constexpr noexcept
Find if the end points represent a full cycle
Parameters
[in] xo Start position of grid
[in] xn End position of grid
[in] xlim [Lower, Upper) bound of cycle
Returns
true if xlim = [xo, xn] or xlim = [xn, xo]
Definition at line 270 of file interpolation_lagrange.h.
Referenced by dl_dval().
gridsize_from_index()
template<typename... Inds> constexpr std::array<std::size_t, sizeof...(Inds)> Interpolation::gridsize_from_index (Inds... inds) constexpr noexcept
Compute gridsizes from indices
Definition at line 39 of file interpolation_lagrange.h.
Referenced by Interpolation::FixedGrid< b, Sizes >::operator()().
IMAX()
constexpr Index Interpolation::IMAX (const Index a, const Index b) constexpr noexcept
Return the maximum of two integer numbers.
T his function is based on a macro from Numerical Rec*eipes. The original macro:
static Index imaxarg1, imaxarg2; #define IMAX(a,b) (imaxarg1=(a), imaxarg2=(b),(imaxarg1) > (imaxarg2) ? \ (imaxarg1) : (imaxarg2))
The macro can cause trouble if used in parallel regions, so we use this function instead.
Parameters
a Input a.
b Input b.
Returns
The maximum of a and b.
Definition at line 314 of file interpolation_lagrange.h.
References a, and b.
IMIN()
constexpr Index Interpolation::IMIN (const Index a, const Index b) constexpr noexcept
Return the minimum of two integer numbers.
T his function is based on a macro from Numerical Rec*eipes. The original macro:
static Index iminarg1, iminarg2; #define IMIN(a,b) (iminarg1=(a), iminarg2=(b),(iminarg1) < (iminarg2) ? \ (iminarg1) : (iminarg2))
The macro can cause trouble if used in parallel regions, so we use this function instead.
Parameters
a Input a.
b Input b.
Returns
The minimum of a and b.
Definition at line 333 of file interpolation_lagrange.h.
References a, and b.
index_from_gridsize()
template<std::size_t N> constexpr std::size_t Interpolation::index_from_gridsize (std::array< std::size_t, N > gridsize, std::array< std::size_t, N > inds) constexpr noexcept
Compute gridsizes from indices
Definition at line 54 of file interpolation_lagrange.h.
References N.
Referenced by Interpolation::Grid< b, n >::operator()(), and Interpolation::FixedGrid< b, Sizes >::operator()().
interp() [1/14]
Numeric Interpolation::interp (const ConstMatrixView & yi, const ConstMatrixView & iw, const Lagrange & dim0, const Lagrange & dim1)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 137 of file interpolation_lagrange.cc.
References cycler(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), Interpolation::Lagrange::pos, and Interpolation::Lagrange::size().
interp() [2/14]
Numeric Interpolation::interp (const ConstTensor3View & yi, const ConstTensor3View & iw, const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 230 of file interpolation_lagrange.cc.
References ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), and Interpolation::Lagrange::size().
interp() [3/14]
Numeric Interpolation::interp (const ConstTensor4View & yi, const ConstTensor4View & iw, const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 338 of file interpolation_lagrange.cc.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Interpolation::Lagrange::size().
interp() [4/14]
Numeric Interpolation::interp (const ConstTensor5View & yi, const ConstTensor5View & iw, const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 469 of file interpolation_lagrange.cc.
References M, ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), and Interpolation::Lagrange::size().
interp() [5/14]
Numeric Interpolation::interp (const ConstTensor6View & yi, const ConstTensor6View & iw, const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 616 of file interpolation_lagrange.cc.
References M, N, ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), and Interpolation::Lagrange::size().
interp() [6/14]
Numeric Interpolation::interp (const ConstTensor7View & yi, const ConstTensor7View & iw, const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5, const Lagrange & dim6)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
[in] dim6 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 786 of file interpolation_lagrange.cc.
References M, N, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), and Interpolation::Lagrange::size().
interp() [7/14]
Numeric Interpolation::interp (const ConstVectorView & yi, const ConstVectorView & iw, const Lagrange & dim0)
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 60 of file interpolation_lagrange.cc.
References cycler(), Interpolation::Lagrange::pos, ConstVectorView::size(), and Interpolation::Lagrange::size().
Referenced by reinterp().
interp() [8/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, class MatrixType > constexpr Numeric Interpolation::interp (const MatrixType & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 1413 of file interpolation_lagrange.h.
References cycler(), Interpolation::FixedLagrange< PolyOrder >::pos, and Interpolation::FixedLagrange< PolyOrder >::size().
interp() [9/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, class Tensor3Type > constexpr Numeric Interpolation::interp (const Tensor3Type & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 1660 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interp() [10/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, class Tensor4Type > constexpr Numeric Interpolation::interp (const Tensor4Type & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 1959 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interp() [11/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, class Tensor5Type > constexpr Numeric Interpolation::interp (const Tensor5Type & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 2299 of file interpolation_lagrange.h.
References M, and Interpolation::FixedLagrange< PolyOrder >::size().
interp() [12/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, class Tensor6Type > constexpr Numeric Interpolation::interp (const Tensor6Type & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 2678 of file interpolation_lagrange.h.
References M, N, and Interpolation::FixedLagrange< PolyOrder >::size().
interp() [13/14]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6, class Tensor7Type > constexpr Numeric Interpolation::interp (const Tensor7Type & yi, const FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5, const FixedLagrange< PolyOrder6 > & dim6) constexpr
Squashing interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
[in] dim6 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 3103 of file interpolation_lagrange.h.
References M, N, and Interpolation::FixedLagrange< PolyOrder >::size().
interp() [14/14]
template<std::size_t PolyOrder, class VectorType > constexpr Numeric Interpolation::interp (const VectorType & yi, const std::array< Numeric, PolyOrder+1 > & iw, const FixedLagrange< PolyOrder > & dim0) constexpr
Squashing fixed interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
Returns
Numeric of interpolated value
Definition at line 1206 of file interpolation_lagrange.h.
References cycler(), Interpolation::FixedLagrange< PolyOrder >::pos, and Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [1/28]
template<std::size_t PolyOrder> Grid<std::array<Numeric, PolyOrder + 1>, 1> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder >> & dim0)
Interpolation weights for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights
Definition at line 1132 of file interpolation_lagrange.h.
References interpweights().
interpweights() [2/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1>, 2> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1)
Interpolation weights for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
Returns
Matrix - interpweights
Definition at line 1308 of file interpolation_lagrange.h.
References interpweights().
interpweights() [3/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1>, 3> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2)
Interpolation weights for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
Returns
Tensor3 - interpweights
Definition at line 1540 of file interpolation_lagrange.h.
interpweights() [4/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1>, 4> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3)
Interpolation weights for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
Returns
Tensor4 - interpweights
Definition at line 1814 of file interpolation_lagrange.h.
interpweights() [5/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1>, 5> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4)
Interpolation weights for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
Returns
Tensor5 - interpweights
Definition at line 2135 of file interpolation_lagrange.h.
interpweights() [6/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1>, 6> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5)
Interpolation weights for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
Returns
Tensor6 - interpweights
Definition at line 2495 of file interpolation_lagrange.h.
interpweights() [7/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6> Grid<FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1, PolyOrder6 + 1>, 7> Interpolation::interpweights (const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5, const Array< FixedLagrange< PolyOrder6 >> & dim6)
Interpolation weights for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
Returns
Tensor7 - interpweights
Definition at line 2898 of file interpolation_lagrange.h.
interpweights() [8/28]
Grid< Vector, 1 > Interpolation::interpweights (const Array< Lagrange > & dim0)
Interpolation weights for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights
Definition at line 37 of file interpolation_lagrange.cc.
References interpweights().
interpweights() [9/28]
Grid< Matrix, 2 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1)
Interpolation weights for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
Returns
Matrix - interpweights
Definition at line 102 of file interpolation_lagrange.cc.
References interpweights().
interpweights() [10/28]
Grid< Tensor3, 3 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2)
Interpolation weights for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
Returns
Tensor3 - interpweights
Definition at line 188 of file interpolation_lagrange.cc.
interpweights() [11/28]
Grid< Tensor4, 4 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3)
Interpolation weights for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
Returns
Tensor4 - interpweights
Definition at line 289 of file interpolation_lagrange.cc.
interpweights() [12/28]
Grid< Tensor5, 5 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4)
Interpolation weights for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
Returns
Tensor5 - interpweights
Definition at line 410 of file interpolation_lagrange.cc.
interpweights() [13/28]
Grid< Tensor6, 6 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5)
Interpolation weights for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
Returns
Tensor6 - interpweights
Definition at line 550 of file interpolation_lagrange.cc.
interpweights() [14/28]
Grid< Tensor7, 7 > Interpolation::interpweights (const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5, const Array< Lagrange > & dim6)
Interpolation weights for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
Returns
Tensor7 - interpweights
Definition at line 710 of file interpolation_lagrange.cc.
interpweights() [15/28]
template<std::size_t PolyOrder> constexpr const std::array<Numeric, PolyOrder + 1>& Interpolation::interpweights (const FixedLagrange< PolyOrder > & dim0) constexpr
Interpolation weights for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights
Definition at line 1121 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::lx.
interpweights() [16/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1) constexpr
Interpolation weights for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
Returns
Matrix - interpweights
Definition at line 1292 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::lx, and Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [17/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2) constexpr
Interpolation weights for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
Returns
Tensor3 - interpweights
Definition at line 1519 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [18/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3) constexpr
Interpolation weights for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
Returns
Tensor4 - interpweights
Definition at line 1786 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [19/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4) constexpr
Interpolation weights for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
Returns
Tensor5 - interpweights
Definition at line 2102 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [20/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5) constexpr
Interpolation weights for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
Returns
Tensor6 - interpweights
Definition at line 2459 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [21/28]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6> constexpr FixedGrid<Numeric, PolyOrder0 + 1, PolyOrder1 + 1, PolyOrder2 + 1, PolyOrder3 + 1, PolyOrder4 + 1, PolyOrder5 + 1, PolyOrder6 + 1> Interpolation::interpweights (const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4, const FixedLagrange< PolyOrder5 > & dim5, const FixedLagrange< PolyOrder6 > & dim6) constexpr
Interpolation weights for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
Returns
Tensor7 - interpweights
Definition at line 2857 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
interpweights() [22/28]
Vector Interpolation::interpweights (const Lagrange & dim0)
Interpolation weights for a 1D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
Returns
Vector - interpweights
Definition at line 35 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::lx.
Referenced by interpweights().
interpweights() [23/28]
Matrix Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1)
Interpolation weights for a 2D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
Returns
Matrix - interpweights
Definition at line 95 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::lx, and Interpolation::Lagrange::size().
interpweights() [24/28]
Tensor3 Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2)
Interpolation weights for a 3D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
Returns
Tensor3 - interpweights
Definition at line 178 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
interpweights() [25/28]
Tensor4 Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3)
Interpolation weights for a 4D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
Returns
Tensor4 - interpweights
Definition at line 278 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
interpweights() [26/28]
Tensor5 Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4)
Interpolation weights for a 5D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
Returns
Tensor5 - interpweights
Definition at line 396 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
interpweights() [27/28]
Tensor6 Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5)
Interpolation weights for a 6D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
Returns
Tensor6 - interpweights
Definition at line 534 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
interpweights() [28/28]
Tensor7 Interpolation::interpweights (const Lagrange & dim0, const Lagrange & dim1, const Lagrange & dim2, const Lagrange & dim3, const Lagrange & dim4, const Lagrange & dim5, const Lagrange & dim6)
Interpolation weights for a 7D reduction
Parameters
[in] dim0 - Interpolation along dimension 0
[in] dim1 - Interpolation along dimension 1
[in] dim2 - Interpolation along dimension 2
[in] dim3 - Interpolation along dimension 3
[in] dim4 - Interpolation along dimension 4
[in] dim5 - Interpolation along dimension 5
[in] dim6 - Interpolation along dimension 6
Returns
Tensor7 - interpweights
Definition at line 691 of file interpolation_lagrange.cc.
References Interpolation::Lagrange::size().
is_ascending()
template<class SortedVectorType > constexpr bool Interpolation::is_ascending (const SortedVectorType & xi) constexpr noexcept
Checks whether the Sorted Vector is ascending or not by checking its first two elements.
Definition at line 600 of file interpolation_lagrange.h.
l()
template<GridType type, class SortedVectorType > constexpr Numeric Interpolation::l (const Index p0, const Index n, const Numeric x, const SortedVectorType & xi, const Index j, [[maybe_unused] ] const std::pair< Numeric, Numeric > cycle = { -180, 180}) constexpr noexcept
Computes the weights for a given coefficient
Parameters
[in] p0 The origin position
[in] n The number of weights
[in] x The position for the weights
[in] xi The sorted vector of values
[in] j The current coefficient
[in] cycle The size of a cycle (optional)
Definition at line 421 of file interpolation_lagrange.h.
Referenced by antenna2d_interp_response(), AtmFieldsAndParticleBulkPropFieldFromCompact(), calcBaselineFit(), cart2poslos(), chk_matrix_ncols(), chk_matrix_nrows(), chk_size(), chk_vector_length(), clebsqr_(), clebsqr_0_(), cloudboxSetAutomatically(), debug_tensor7view_get_elem(), distance2D(), distance3D(), do_gridcell_2d_byltest(), do_gridcell_3d_byltest(), Jacobian::ENUMCLASS(), fill_tensor7(), find_first_unique_in_lower(), g_legendre_poly(), g_legendre_poly_deriv(), g_legendre_poly_norm_schmidt(), g_legendre_poly_norm_schmidt_deriv(), g_legendre_poly_norm_schmidt_deriv1(), g_legendre_poly_norm_schmidt_deriv2(), g_legendre_poly_norm_schmidt_deriv3(), g_legendre_poly_norm_schmidt_deriv4(), geompath_from_r1_to_r2(), geompath_r_at_l(), Tensor7View::get(), ConstTensor7View::get(), get_pmom(), is_size(), jacobianAddShapeCatalogParameters(), jacobianCalcFreqStretch(), jacobianCalcPolyfit(), jacobianCalcSinefit(), jacobianFromYbatch(), legendre_poly(), legendre_poly_deriv(), legendre_poly_norm_schmidt(), legendre_poly_norm_schmidt_deriv(), main(), Absorption::Lines::Match(), mblock_dlos_gridUniformCircular(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93H2OAbsModel(), MPM93O2AbsModel(), Absorption::nelem(), Tensor7View::operator()(), ConstTensor7View::operator()(), operator<<(), Interpolation::FixedLagrange< PolyOrder >::operator=(), Interpolation::Lagrange::operator=(), opt_prop_bulkCalc(), plevel_crossing_2d(), polynomial_basis_func(), PWR93O2AbsModel(), PWR98H2OAbsModel(), r_crossing_2d(), r_crossing_3d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), lm_hitran_2017::readw(), Tensor7::resize(), InteractiveWorkspace::set_tensor3_variable(), stokes2pol(), surf_radius_at_l(), surface_scalar_reflectivityFromSurface_rmatrix(), Tensor7::Tensor7(), test_lusolve1D(), test_lusolve4D(), TRE05O2AbsModel(), unitl(), VectorClip(), xml_read_from_stream(), and xml_write_to_stream().
LagrangeVector()
Array< Lagrange > Interpolation::LagrangeVector (const ConstVectorView & x, const ConstVectorView & xi, const Index polyorder, const Numeric extrapol = 0.5, const bool do_derivs = false, const GridType type = GridType::Standard, const std::pair< Numeric, Numeric > cycle = {-180, 180})
Gets a vector of Lagrange interpolation points
Estimates start position using start_pos_finder
Parameters
[in] x New grid positions
[in] xi Old grid positions
[in] polyorder Polynominal degree
[in] extrapol Level of extrapolation
[in] do_derivs Flag to activate derivative calculations
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Returns
vector of Lagrange
Definition at line 5 of file interpolation_lagrange.cc.
References check_lagrange_interpolation(), max, min, ConstVectorView::size(), start_pos_finder(), and x.
Referenced by GasAbsLookup::Adapt(), AtmFieldPRegridHelper(), GasAbsLookup::Extract(), GriddedFieldLatLonRegridHelper(), GriddedFieldPRegridHelper(), GriddedFieldZToPRegridHelper(), MagFieldsCalc(), MagFieldsFromAltitudeRawCalc(), scat_dataCalc(), sensor_responseFillFgrid(), ssd_tinterp_parameters(), test09(), test11(), test16(), and WindFieldsCalc().
min_cyclic()
constexpr Numeric Interpolation::min_cyclic (const Numeric x, const std::pair< Numeric, Numeric > xlim) constexpr noexcept
Find the absolute minimum in a cycle
Parameters
[in] x A position relative to a cycle
[in] xlim [Lower, Upper) bound of cycle
Returns
x-dx, x, or x+dx, whichever absolute is the smallest, where dx=Upper-Lower
Definition at line 254 of file interpolation_lagrange.h.
References Interpolation::nonstd::abs(), dx, and x.
Referenced by dl_dval().
mul() [1/2]
template<std::size_t N> constexpr std::size_t Interpolation::mul (const std::array< std::size_t, N > & arr) constexpr noexcept
Compute the multiplication of all inds in arr
Definition at line 27 of file interpolation_lagrange.h.
References N.
mul() [2/2]
template<typename... Inds> constexpr std::size_t Interpolation::mul (Inds... inds) constexpr noexcept
Compute the multiplication of all inds
Definition at line 21 of file interpolation_lagrange.h.
Referenced by cumulative_transmission().
pos_finder()
template<class SortedVectorType > constexpr Index Interpolation::pos_finder (const Index pos0, const Numeric x, const SortedVectorType & xi, const Index polyorder, const bool cyclic, const bool ascending, const std::pair< Numeric, Numeric > cycle = { -180, 180}) constexpr noexcept
Finds the position of interpolation of x in xi
Will first find the first position with one lower value to the side of the point before adjusting so that x is in the center of a multiple interpolation order curve
Parameters
[in] pos0 Estimation of the first position, must be [0, xi.size())
[in] x Coordinate to find a position for
[in] xi Original sorted grid
[in] polyorder Polynominal orders
[in] cyclic The sorting is cyclic (1, 2, 3, 0.5, 1.5...)
[in] ascending The sorting is ascending (1, 2, 3...)
[in] cycle The size of a cycle (optional; increasing first->second)
Definition at line 350 of file interpolation_lagrange.h.
Referenced by choose_abs_nls_pert(), and choose_abs_t_pert().
reinterp() [1/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1> Matrix Interpolation::reinterp (const ConstMatrixView & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1 >, 2 > & iw, const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
Returns
Matrix of interpolated value
Definition at line 1468 of file interpolation_lagrange.h.
References interp().
reinterp() [2/21]
Matrix Interpolation::reinterp (const ConstMatrixView & iy, const Grid< Matrix, 2 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
Returns
Matrix of interpolated value
Definition at line 160 of file interpolation_lagrange.cc.
References interp().
reinterp() [3/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2> Tensor3 Interpolation::reinterp (const ConstTensor3View & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1 >, 3 > & iw, const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
Returns
Tensor3 of interpolated value
Definition at line 1726 of file interpolation_lagrange.h.
reinterp() [4/21]
Tensor3 Interpolation::reinterp (const ConstTensor3View & iy, const Grid< Tensor3, 3 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
Returns
Tensor3 of interpolated value
Definition at line 258 of file interpolation_lagrange.cc.
reinterp() [5/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3> Tensor4 Interpolation::reinterp (const ConstTensor4View & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1 >, 4 > & iw, const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
Returns
Tensor4 of interpolated value
Definition at line 2034 of file interpolation_lagrange.h.
reinterp() [6/21]
Tensor4 Interpolation::reinterp (const ConstTensor4View & iy, const Grid< Tensor4, 4 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
Returns
Tensor4 of interpolated value
Definition at line 373 of file interpolation_lagrange.cc.
reinterp() [7/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4> Tensor5 Interpolation::reinterp (const ConstTensor5View & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1 >, 5 > & iw, const FixedLagrange< PolyOrder0 > & dim0, const FixedLagrange< PolyOrder1 > & dim1, const FixedLagrange< PolyOrder2 > & dim2, const FixedLagrange< PolyOrder3 > & dim3, const FixedLagrange< PolyOrder4 > & dim4)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
Returns
Tensor5 of interpolated value
Definition at line 2384 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::size().
reinterp() [8/21]
Tensor5 Interpolation::reinterp (const ConstTensor5View & iy, const Grid< Tensor5, 5 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
Returns
Tensor5 of interpolated value
Definition at line 509 of file interpolation_lagrange.cc.
reinterp() [9/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5> Tensor6 Interpolation::reinterp (const ConstTensor6View & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1 >, 6 > & iw, const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
Returns
Tensor6 of interpolated value
Definition at line 2771 of file interpolation_lagrange.h.
reinterp() [10/21]
Tensor6 Interpolation::reinterp (const ConstTensor6View & iy, const Grid< Tensor6, 6 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
Returns
Tensor6 of interpolated value
Definition at line 662 of file interpolation_lagrange.cc.
reinterp() [11/21]
template<std::size_t PolyOrder0, std::size_t PolyOrder1, std::size_t PolyOrder2, std::size_t PolyOrder3, std::size_t PolyOrder4, std::size_t PolyOrder5, std::size_t PolyOrder6> Tensor7 Interpolation::reinterp (const ConstTensor7View & iy, const Grid< FixedGrid< Numeric, PolyOrder0+1, PolyOrder1+1, PolyOrder2+1, PolyOrder3+1, PolyOrder4+1, PolyOrder5+1, PolyOrder6+1 >, 7 > & iw, const Array< FixedLagrange< PolyOrder0 >> & dim0, const Array< FixedLagrange< PolyOrder1 >> & dim1, const Array< FixedLagrange< PolyOrder2 >> & dim2, const Array< FixedLagrange< PolyOrder3 >> & dim3, const Array< FixedLagrange< PolyOrder4 >> & dim4, const Array< FixedLagrange< PolyOrder5 >> & dim5, const Array< FixedLagrange< PolyOrder6 >> & dim6)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
[in] dim6 - Lagrange weights along the dimension
Returns
Tensor7 of interpolated value
Definition at line 3207 of file interpolation_lagrange.h.
reinterp() [12/21]
Tensor7 Interpolation::reinterp (const ConstTensor7View & iy, const Grid< Tensor7, 7 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5, const Array< Lagrange > & dim6)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
[in] dim6 - Lagrange weights along the dimension
Returns
Tensor7 of interpolated value
Definition at line 837 of file interpolation_lagrange.cc.
reinterp() [13/21]
template<std::size_t PolyOrder> Vector Interpolation::reinterp (const ConstVectorView & iy, const Grid< std::array< Numeric, PolyOrder+1 >, 1 > & iw, const Array< FixedLagrange< PolyOrder >> & dim0)
Reinterpreting fixed interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
Returns
Vector of interpolated value
Definition at line 1252 of file interpolation_lagrange.h.
References interp().
reinterp() [14/21]
Vector Interpolation::reinterp (const ConstVectorView & iy, const Grid< Vector, 1 > & iw, const Array< Lagrange > & dim0)
Reinterpreting interpolation routine
Parameters
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
Returns
Vector of interpolated value
Definition at line 79 of file interpolation_lagrange.cc.
References interp().
reinterp() [15/21]
void Interpolation::reinterp (MatrixView out, const ConstMatrixView & iy, const Grid< Matrix, 2 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
Returns
Matrix of interpolated value
Definition at line 152 of file interpolation_lagrange.cc.
References interp().
reinterp() [16/21]
void Interpolation::reinterp (Tensor3View out, const ConstTensor3View & iy, const Grid< Tensor3, 3 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
Returns
Tensor3 of interpolated value
Definition at line 248 of file interpolation_lagrange.cc.
reinterp() [17/21]
void Interpolation::reinterp (Tensor4View out, const ConstTensor4View & iy, const Grid< Tensor4, 4 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
Returns
Tensor4 of interpolated value
Definition at line 360 of file interpolation_lagrange.cc.
reinterp() [18/21]
void Interpolation::reinterp (Tensor5View out, const ConstTensor5View & iy, const Grid< Tensor5, 5 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
Returns
Tensor5 of interpolated value
Definition at line 494 of file interpolation_lagrange.cc.
reinterp() [19/21]
void Interpolation::reinterp (Tensor6View out, const ConstTensor6View & iy, const Grid< Tensor6, 6 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
Returns
Tensor6 of interpolated value
Definition at line 644 of file interpolation_lagrange.cc.
reinterp() [20/21]
void Interpolation::reinterp (Tensor7View out, const ConstTensor7View & iy, const Grid< Tensor7, 7 > & iw, const Array< Lagrange > & dim0, const Array< Lagrange > & dim1, const Array< Lagrange > & dim2, const Array< Lagrange > & dim3, const Array< Lagrange > & dim4, const Array< Lagrange > & dim5, const Array< Lagrange > & dim6)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
[in] dim1 - Lagrange weights along the dimension
[in] dim2 - Lagrange weights along the dimension
[in] dim3 - Lagrange weights along the dimension
[in] dim4 - Lagrange weights along the dimension
[in] dim5 - Lagrange weights along the dimension
[in] dim6 - Lagrange weights along the dimension
Returns
Tensor7 of interpolated value
Definition at line 817 of file interpolation_lagrange.cc.
reinterp() [21/21]
void Interpolation::reinterp (VectorView out, const ConstVectorView & iy, const Grid< Vector, 1 > & iw, const Array< Lagrange > & dim0)
Reinterpreting interpolation routine
Parameters
[in,out] out - Reinterpreted field
[in] yi - Original data to squash
[in] iw - Interpolation weights grid or their derivatives from the Lagrange routines
[in] dim0 - Lagrange weights along the dimension
Returns
Vector of interpolated value
Definition at line 73 of file interpolation_lagrange.cc.
References interp().
Referenced by AtmFieldPRegrid(), XsecRecord::Extract(), FouComp_1ScatElem(), GriddedFieldLatLonRegrid(), GriddedFieldPRegrid(), GriddedFieldZToPRegrid(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), MagFieldsCalc(), MagFieldsFromAltitudeRawCalc(), opt_prop_1ScatElem(), pha_mat_1ScatElem(), scat_dataCalc(), test09(), test11(), test14(), and WindFieldsCalc().
start_pos_finder()
template<class SortedVectorType > constexpr Index Interpolation::start_pos_finder (const Numeric x, const SortedVectorType & xvec) constexpr noexcept
Find an estimation of the start position in a linearly separated grid (useful as a start position esitmated
Parameters
[in] x The position
[in] xvec The grid
Returns
Estimated position of x [0, xvec.size())
Definition at line 285 of file interpolation_lagrange.h.
References x, x0, and x1.
Referenced by LagrangeVector().