ARTS: ARTS::AgendaExecute Namespace Reference
ARTS::AgendaExecute Namespace Reference
Functions
void abs_xsec_agenda (Workspace &ws)
void dobatch_calc_agenda (Workspace &ws)
void doit_conv_test_agenda (Workspace &ws)
void doit_mono_agenda (Workspace &ws)
void doit_rte_agenda (Workspace &ws)
void doit_scat_field_agenda (Workspace &ws)
void forloop_agenda (Workspace &ws)
void g0_agenda (Workspace &ws)
void geo_pos_agenda (Workspace &ws)
void inversion_iterate_agenda (Workspace &ws)
void iy_cloudbox_agenda (Workspace &ws)
void iy_independent_beam_approx_agenda (Workspace &ws)
void iy_loop_freqs_agenda (Workspace &ws)
void iy_main_agenda (Workspace &ws)
void iy_space_agenda (Workspace &ws)
void iy_surface_agenda (Workspace &ws)
void iy_surface_agenda_array (Workspace &ws)
void iy_transmitter_agenda (Workspace &ws)
void jacobian_agenda (Workspace &ws)
void main_agenda (Workspace &ws)
void met_profile_calc_agenda (Workspace &ws)
void pha_mat_spt_agenda (Workspace &ws)
void pnd_agenda_array (Workspace &ws)
void ppath_agenda (Workspace &ws)
void ppath_step_agenda (Workspace &ws)
void propmat_clearsky_agenda (Workspace &ws)
void refr_index_air_agenda (Workspace &ws)
void sensor_response_agenda (Workspace &ws)
void spt_calc_agenda (Workspace &ws)
void surface_rtprop_agenda (Workspace &ws)
void surface_rtprop_agenda_array (Workspace &ws)
void surface_rtprop_sub_agenda (Workspace &ws)
void test_agenda (Workspace &ws)
void test_agenda_array (Workspace &ws)
void water_p_eq_agenda (Workspace &ws)
void ybatch_calc_agenda (Workspace &ws)
Function Documentation
abs_xsec_agenda()
void ARTS::AgendaExecute::abs_xsec_agenda (Workspace & ws) inline
Calculate scalar gas absorption cross sections.
Basically, this agenda calculates absorption for all the tags defined in abs_species. It is used both in the calculation of an absorption lookup table, and in on-the-fly calculations. Typical effects to include here are:
Explicit line-by-line calculation (abs_xsec_per_speciesAddLines),
Continua and complete absorption models (abs_xsec_per_speciesAddConts), and
HITRAN style CIA continua (abs_xsec_per_speciesAddCIA)
The only kind of absorption tag not handled here are Zeeman tags and free electron density tags, because they need additional input and because they return an absorption matrix, rather than a scalar.
The include file 'agendas.arts' predefines a number of agendas that should be useful for most users.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146513 of file autoarts.h.
References ARTS::Var::abs_nlte(), ARTS::Var::abs_p(), ARTS::Var::abs_species(), ARTS::Var::abs_species_active(), ARTS::Var::abs_t(), ARTS::Var::abs_vmrs(), ARTS::Var::abs_xsec_agenda(), abs_xsec_agendaExecute(), ARTS::Var::abs_xsec_per_species(), ARTS::Var::dabs_xsec_per_species_dx(), ARTS::Var::dsrc_xsec_per_species_dx(), ARTS::Var::f_grid(), ARTS::Var::jacobian_quantities(), and ARTS::Var::src_xsec_per_species().
dobatch_calc_agenda()
void ARTS::AgendaExecute::dobatch_calc_agenda (Workspace & ws) inline
Calculations to perform for each batch case.
See further DOBatchCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146536 of file autoarts.h.
References ARTS::Var::dobatch_calc_agenda(), dobatch_calc_agendaExecute(), ARTS::Var::irradiance_field(), ARTS::Var::radiance_field(), ARTS::Var::spectral_irradiance_field(), ARTS::Var::spectral_radiance_field(), and ARTS::Var::ybatch_index().
doit_conv_test_agenda()
void ARTS::AgendaExecute::doit_conv_test_agenda (Workspace & ws) inline
Compute the convergence test.
The method cloudbox_field_monoIterate solves the VRTE iteratively.This method requires a convergence test. The user can choose different convergence tests which are to be defined in this agenda.
Possible workspace methods are: doit_conv_flagAbs*: Calculates the absolute differences for each Stokes component separately. doit_conv_flagAbsBT*: Same as above, but the convergence limit can be specified in Kelvin BT (Rayleigh Jeans). doit_conv_flagLsq*: Least square convergence test. Not recommended because result can be inaccurate.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146562 of file autoarts.h.
References ARTS::Var::cloudbox_field_mono(), ARTS::Var::cloudbox_field_mono_old(), ARTS::Var::doit_conv_flag(), ARTS::Var::doit_conv_test_agenda(), doit_conv_test_agendaExecute(), and ARTS::Var::doit_iteration_counter().
doit_mono_agenda()
void ARTS::AgendaExecute::doit_mono_agenda (Workspace & ws) inline
Performs monochromatic DOIT calculation. This agenda includes for example the following methods:
DoitScatteringDataPrepare
cloudbox_field_monoIterate
The result of the agenda is the radiation field inside the cloudbox and on the cloudbox boundary, which can be used as radiative background for a clearsky radiative transfer calculation.
See the Arts online documentation for more information about the methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146586 of file autoarts.h.
References ARTS::Var::cloudbox_field_mono(), ARTS::Var::doit_mono_agenda(), doit_mono_agendaExecute(), ARTS::Var::f_grid(), and ARTS::Var::f_index().
doit_rte_agenda()
void ARTS::AgendaExecute::doit_rte_agenda (Workspace & ws) inline
Radiative transfer calculations in cloudbox.
Agenda for radiative transfer step calculations with fixed scattering integral term shoul be specified here. Output is the updated radiation field in the cloudbox. This agenda is called repeatedly in each DOIT iteration.
Normally one should use cloudbox_fieldUpdateSeq1D* or cloudbox_fieldUpdateSeq3D: Seqential update of the radiation field. This method is the fastest and most accurate method.
A very similar method in plane parallel approximation is cloudbox_fieldUpdateSeq1DPP*: This method also includes the sequential update and is slightly faster than the above one. The drawback is that it is less accurate, especially for limb geometries and large off-nadir viewing angles.
The following method was used before the sequential update was invented. It is very slow and should therefore only be used for test cases. cloudbox_fieldUpdate1D*: Old method.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146620 of file autoarts.h.
References ARTS::Var::cloudbox_field_mono(), ARTS::Var::doit_rte_agenda(), doit_rte_agendaExecute(), and ARTS::Var::doit_scat_field().
doit_scat_field_agenda()
void ARTS::AgendaExecute::doit_scat_field_agenda (Workspace & ws) inline
Calculation of the scattering integral field (DOIT).
This agenda is called repeatedly in each DOIT iteration. The following methods can be used for calculating the scattering integral field:
doit_scat_fieldCalc*: This method calculates the scattering integral field by using the angular grids za_grid and aa_grid, which are also used in the update of the radiation field (doit_rte_agenda).
doit_scat_fieldCalcLimb*: This method calculates the scattering integral field. The difference to the previous method is that the data is interpolated on equidistant angular grids. Especially for limb, where a very fine zenith angle grid resolution is required for the RT transfer part, this method is much faster than doit_scat_fieldCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146647 of file autoarts.h.
References ARTS::Var::cloudbox_field_mono(), ARTS::Var::doit_scat_field(), ARTS::Var::doit_scat_field_agenda(), and doit_scat_field_agendaExecute().
forloop_agenda()
void ARTS::AgendaExecute::forloop_agenda (Workspace & ws) inline
The body for a for loop.
This agenda contains the body of the for loop to be execute by the method ForLoop.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146661 of file autoarts.h.
References ARTS::Var::forloop_agenda(), forloop_agendaExecute(), and ARTS::Var::forloop_index().
g0_agenda()
void ARTS::AgendaExecute::g0_agenda (Workspace & ws) inline
Calculation of the gravity at zero altitude.
Returns g0 for given geographical position.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146673 of file autoarts.h.
References ARTS::Var::g0(), ARTS::Var::g0_agenda(), g0_agendaExecute(), ARTS::Var::lat(), and ARTS::Var::lon().
geo_pos_agenda()
void ARTS::AgendaExecute::geo_pos_agenda (Workspace & ws) inline
Geo-positioning of a pencil beam calculation.
The task of this agenda is to set geo_pos. The standard choices are to set that WSV to be empty or select a position along the propagation path (described by ppath).
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146689 of file autoarts.h.
References ARTS::Var::geo_pos(), ARTS::Var::geo_pos_agenda(), geo_pos_agendaExecute(), and ARTS::Var::ppath().
inversion_iterate_agenda()
void ARTS::AgendaExecute::inversion_iterate_agenda (Workspace & ws) inline
Work in progress ...
The WSV jacobian is both in- and output. As input variable, jacobian is assumed to be valid for the previous iteration. For the first iteration the input jacobian shall be set to have size zero, to flag that there is not yet any calculated Jacobian.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146705 of file autoarts.h.
References ARTS::Var::inversion_iterate_agenda(), inversion_iterate_agendaExecute(), ARTS::Var::inversion_iteration_counter(), ARTS::Var::jacobian(), ARTS::Var::jacobian_do(), ARTS::Var::x(), and ARTS::Var::yf().
iy_cloudbox_agenda()
void ARTS::AgendaExecute::iy_cloudbox_agenda (Workspace & ws) inline
Intensity at boundary or interior of the cloudbox.
The task of the agenda is to determine the intensity at some point at the boundary of or inside the cloudbox. The actual calculations inside the agenda differ depending on scattering solution method. If DOIT is used, an interpolating of the intensity field should be performed. Another option is to start backward Monte Carlo calculations from this point.
A function calling this agenda shall set rte_pos and rte_los to the position and line-of-sight for which the scattered radiation shall be determined.
The include-file 'agendas.arts' pre-defines some agendas that can either be used directly, or serve as examples.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146733 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_cloudbox_agenda(), iy_cloudbox_agendaExecute(), ARTS::Var::rtp_los(), and ARTS::Var::rtp_pos().
iy_independent_beam_approx_agenda()
void ARTS::AgendaExecute::iy_independent_beam_approx_agenda (Workspace & ws) inline
Agenda dedicated to iyIndependentBeamApproximation.
If iyIndependentBeamApproximation is used, this agenda basically replaces iy_main_agenda. Accordingly, this agenda has exactly the same output as iy_main_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146750 of file autoarts.h.
References ARTS::Var::atmosphere_dim(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_id(), ARTS::Var::iy_independent_beam_approx_agenda(), iy_independent_beam_approx_agendaExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_unit(), ARTS::Var::jacobian_do(), ARTS::Var::lat_grid(), ARTS::Var::lat_true(), ARTS::Var::lon_grid(), ARTS::Var::lon_true(), ARTS::Var::p_grid(), ARTS::Var::pnd_field(), ARTS::Var::ppath(), ARTS::Var::ppath_lmax(), ARTS::Var::ppath_lraytrace(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), ARTS::Var::rte_pos2(), ARTS::Var::t_field(), ARTS::Var::vmr_field(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
iy_loop_freqs_agenda()
void ARTS::AgendaExecute::iy_loop_freqs_agenda (Workspace & ws) inline
Agenda dedicated to iyLoopFrequencies.
If iyLoopFrequencies is used, this agenda basically replaces iy_main_agenda*.Accordingly, this agenda has exactly the same output as iy_main_agenda.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146792 of file autoarts.h.
References ARTS::Var::diy_dx(), ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_id(), ARTS::Var::iy_loop_freqs_agenda(), iy_loop_freqs_agendaExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::ppath(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), and ARTS::Var::rte_pos2().
iy_main_agenda()
void ARTS::AgendaExecute::iy_main_agenda (Workspace & ws) inline
Calculation of a single monochromatic pencil beam spectrum.
The task of the agenda is to calculate the monochromatic pencil beam spectrum for the position specified by rte_pos and the viewing direction specified by rte_los.
Methods for this agenda can either handle the complete calculation, make use of e.g. iy_cloudbox_agenda or be restricted to special cases. See the documentation for the different methods.
The include-file 'agendas.arts' predefines some typical alternatives that can be used directly, or adapted for specific applications.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146824 of file autoarts.h.
References ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_agenda_call1(), ARTS::Var::iy_aux(), ARTS::Var::iy_aux_vars(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), iy_main_agendaExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_unit(), ARTS::Var::jacobian_do(), ARTS::Var::nlte_field(), ARTS::Var::ppath(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), and ARTS::Var::rte_pos2().
iy_space_agenda()
void ARTS::AgendaExecute::iy_space_agenda (Workspace & ws) inline
Downwelling radiation at the top of the atmosphere.
Possible terms to include in this agenda include cosmic background radiation and solar radiation.
A function calling this agenda shall set rtp_pos and rtp_los to the position and line-of-sight for which the entering radiation shall be determined. The position and line-of-sight must be known, for example, when radiation from the sun is considered.
The include-file 'agendas.arts' predefines an agenda that can be applied directly for most users.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146860 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_space_agenda(), iy_space_agendaExecute(), ARTS::Var::rtp_los(), and ARTS::Var::rtp_pos().
iy_surface_agenda()
void ARTS::AgendaExecute::iy_surface_agenda (Workspace & ws) inline
Upwelling radiation from the surface.
The task of the agenda is to determine the upwelling intensity from the surface, for given point and direction.
The standard choice should be to make use of surface_rtprop_agenda through the WSM iySurfaceRtpropAgenda.
A function calling this agenda shall set rtp_pos and rtp_los to the position and line-of-sight for which the upwelling radiation shall be determined.
See also the include-file 'agendas.arts' for a predefined agenda suitable to be used in most applications.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146886 of file autoarts.h.
References ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::dsurface_emission_dx(), ARTS::Var::dsurface_names(), ARTS::Var::dsurface_rmatrix_dx(), ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), ARTS::Var::iy_surface_agenda(), iy_surface_agendaExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_unit(), ARTS::Var::jacobian_do(), ARTS::Var::nlte_field(), ARTS::Var::rte_pos2(), ARTS::Var::rtp_los(), ARTS::Var::rtp_pos(), and ARTS::Var::surface_props_data().
iy_surface_agenda_array()
void ARTS::AgendaExecute::iy_surface_agenda_array (Workspace & ws) inline
Upwelling radiation from the surface, divided into surface types.
Each agenda element shall treat the radiative properties of a surface type. The task of these agendas match directly iy_surface_agenda. This with one exception, these agendas have one additional input: surface_type_aux*.
See surface_type_mask for comments on the surface type coding scheme. Note the parallel agenda array: surface_rtprop_agenda_array.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146920 of file autoarts.h.
References ARTS::Var::agenda_array_index(), ARTS::Var::cloudbox_on(), ARTS::Var::diy_dx(), ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), ARTS::Var::iy_surface_agenda_array(), iy_surface_agenda_arrayExecute(), ARTS::Var::iy_transmittance(), ARTS::Var::iy_unit(), ARTS::Var::jacobian_do(), ARTS::Var::rte_pos2(), ARTS::Var::rtp_los(), ARTS::Var::rtp_pos(), and ARTS::Var::surface_type_aux().
iy_transmitter_agenda()
void ARTS::AgendaExecute::iy_transmitter_agenda (Workspace & ws) inline
Transmitter signal.
This agenda describes the signal at the start of the propagation path for calculations of transmission type. That is, the agenda describes a transmitter, which either can be a natural source or an artificial device.
The include-file 'agendas.arts' defines an example agenda that can be used for transmission calculations
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146951 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::iy(), ARTS::Var::iy_transmitter_agenda(), iy_transmitter_agendaExecute(), ARTS::Var::rtp_los(), and ARTS::Var::rtp_pos().
jacobian_agenda()
void ARTS::AgendaExecute::jacobian_agenda (Workspace & ws) inline
Pure numerical Jacobian calculations.
Parts of the Jacobian matrix can be determined by (semi-)analytical expressions, while other parts are calculated in a pure numerical manner (by perturbations). This agenda describes the calculations to be performed in the later case.
This agenda is normally not set directly by the user, but is created by calling the the jacobianAdd set of methods.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146972 of file autoarts.h.
References ARTS::Var::iyb(), ARTS::Var::jacobian(), ARTS::Var::jacobian_agenda(), jacobian_agendaExecute(), ARTS::Var::mblock_index(), and ARTS::Var::yb().
main_agenda()
void ARTS::AgendaExecute::main_agenda (Workspace & ws) inline
The agenda corresponding to the entire controlfile. This is executed when ARTS is run.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 146986 of file autoarts.h.
References ARTS::Var::main_agenda(), and main_agendaExecute().
met_profile_calc_agenda()
void ARTS::AgendaExecute::met_profile_calc_agenda (Workspace & ws) inline
This agenda is used for metoffice profile calculations.
This agenda is called inside the method ybatchMetProfiles which is used to make a batch calculation for the metoffice profiles.
See the documentation of ybatchMetProfiles for more information.
This agenda can be, for example, set up like this:
AtmFieldsCalc* abs_lookupAdapt* DoitInit* DoitGetIncoming* cloudbox_fieldSetClearsky* DoitCalc* yCalc*
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147009 of file autoarts.h.
References ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), ARTS::Var::met_profile_calc_agenda(), met_profile_calc_agendaExecute(), ARTS::Var::p_grid(), ARTS::Var::pnd_field_raw(), ARTS::Var::sensor_los(), ARTS::Var::t_field_raw(), ARTS::Var::vmr_field_raw(), ARTS::Var::y(), ARTS::Var::z_field_raw(), and ARTS::Var::z_surface().
pha_mat_spt_agenda()
void ARTS::AgendaExecute::pha_mat_spt_agenda (Workspace & ws) inline
Calculates the phase matrix for individual scattering elements.
Different options are possible for the usage of this agenda: pha_mat_sptFromData* or pha_mat_sptFromDataDOITOpt.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147031 of file autoarts.h.
References ARTS::Var::aa_index(), ARTS::Var::pha_mat_spt(), ARTS::Var::pha_mat_spt_agenda(), pha_mat_spt_agendaExecute(), ARTS::Var::rtp_temperature(), ARTS::Var::scat_lat_index(), ARTS::Var::scat_lon_index(), ARTS::Var::scat_p_index(), and ARTS::Var::za_index().
pnd_agenda_array()
void ARTS::AgendaExecute::pnd_agenda_array (Workspace & ws) inline
Returns particle number density data for each scattering species.
This variable is used when mapping data in particle_bulkprop_field to pnd_field. The variable is also necessary when calculating scattering species weighting functions.
Note that content of this agenda array, scat_species and pnd_agenda_array_input_names* must be consistent.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147054 of file autoarts.h.
References ARTS::Var::agenda_array_index(), ARTS::Var::dpnd_data_dx(), ARTS::Var::dpnd_data_dx_names(), ARTS::Var::pnd_agenda_array(), pnd_agenda_arrayExecute(), ARTS::Var::pnd_agenda_input(), ARTS::Var::pnd_agenda_input_names(), ARTS::Var::pnd_agenda_input_t(), and ARTS::Var::pnd_data().
ppath_agenda()
void ARTS::AgendaExecute::ppath_agenda (Workspace & ws) inline
Calculation of complete propagation paths.
In contrast to ppath_step_agenda that controls the ray tracing inside each grid box, this agenda determines how complete paths are determined. The standard choice is to do this in a step-by-step manner using ppath_step_agenda, with this agenda set to call ppathStepByStep*.
The WSV rte_los is both input and output as in some cases it is determined as part of the propagation path calculations (such as radio link calculations).
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147080 of file autoarts.h.
References ARTS::Var::cloudbox_on(), ARTS::Var::f_grid(), ARTS::Var::ppath(), ARTS::Var::ppath_agenda(), ppath_agendaExecute(), ARTS::Var::ppath_inside_cloudbox_do(), ARTS::Var::ppath_lmax(), ARTS::Var::ppath_lraytrace(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), and ARTS::Var::rte_pos2().
ppath_step_agenda()
void ARTS::AgendaExecute::ppath_step_agenda (Workspace & ws) inline
Calculation of a propagation path step.
A propagation path step is defined as the path between some point to a crossing with either the pressure, latitude or longitude grid, and this agenda performs the calculations to determine such a partial propagation path. The starting point is normally a grid crossing point, but can also be an arbitrary point inside the atmosphere, such as the sensor position. Only points inside the model atmosphere are handled.
The communication between this agenda and the calling method is handled by ppath_step. That variable is used both as input and output to ppath_step_agenda. The agenda gets back ppath_step as returned to the calling method and the last path point hold by the structure is accordingly the starting point for the new calculations. If a total propagation path shall be determined, this agenda is called repeatedly until the starting point of the propagation path is found and ppath_step will hold all path steps that together make up ppath. The starting point is included in the returned structure.
The path is determined by starting at the end point and moving backwards to the starting point. The calculations are initiated by filling ppath_step with the practical end point of the path. This is either the position of the sensor (true or hypothetical), or some point at the top of the atmosphere (determined by geometrical calculations starting at the sensor). This initialisation is not handled by ppath_step_agenda (but by the internal function ppath_start_stepping).
The ppath_step_agenda put in points along the propagation path at all crossings with the grids, tangent points and points of surface reflection. It is also allowed to make agendas that put in additional points to fulfil some criterion, such as a maximum distance along the path between the points. Accordingly, the number of new points of each step can exceed one.
The include file 'agendas.arts' defines some agendas that can be used here.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147135 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::ppath_lmax(), ARTS::Var::ppath_lraytrace(), ARTS::Var::ppath_step(), ARTS::Var::ppath_step_agenda(), and ppath_step_agendaExecute().
propmat_clearsky_agenda()
void ARTS::AgendaExecute::propmat_clearsky_agenda (Workspace & ws) inline
Calculate the absorption coefficient matrix.
This agenda calculates the absorption coefficient matrix for all absorption species as a function of the given atmospheric state for one point in the atmosphere. The result is returned in propmat_clearsky*. The atmospheric state has to be specified by rtp_pressure*, rtp_temperature, rtp_mag, and rtp_vmr.
The methods inside this agenda may require a lot of additional input variables, such as abs_species, etc.
The include file 'agendas.arts' predefines some possible agendas that can be used here.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147160 of file autoarts.h.
References ARTS::Var::dnlte_dx_source(), ARTS::Var::dpropmat_clearsky_dx(), ARTS::Var::f_grid(), ARTS::Var::jacobian_quantities(), ARTS::Var::nlte_dsource_dx(), ARTS::Var::nlte_source(), ARTS::Var::propmat_clearsky(), ARTS::Var::propmat_clearsky_agenda(), propmat_clearsky_agendaExecute(), ARTS::Var::rtp_los(), ARTS::Var::rtp_mag(), ARTS::Var::rtp_nlte(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), and ARTS::Var::rtp_vmr().
refr_index_air_agenda()
void ARTS::AgendaExecute::refr_index_air_agenda (Workspace & ws) inline
Calculation of the refractive index of air.
This agenda should calculate the summed refractive index for all relevant atmospheric constituents, with respect to both phase and group velocity.
The include file 'agendas.arts' predefines several agendas that may either be used directly, or serve as inspiration.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147189 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::refr_index_air(), ARTS::Var::refr_index_air_agenda(), refr_index_air_agendaExecute(), ARTS::Var::refr_index_air_group(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), and ARTS::Var::rtp_vmr().
sensor_response_agenda()
void ARTS::AgendaExecute::sensor_response_agenda (Workspace & ws) inline
This agenda shall provide sensor_response and associated variables.
So far only required when doing inversions involving some sensor variables.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147206 of file autoarts.h.
References ARTS::Var::f_backend(), ARTS::Var::mblock_dlos_grid(), ARTS::Var::sensor_response(), ARTS::Var::sensor_response_agenda(), sensor_response_agendaExecute(), ARTS::Var::sensor_response_dlos(), ARTS::Var::sensor_response_dlos_grid(), ARTS::Var::sensor_response_f(), ARTS::Var::sensor_response_f_grid(), ARTS::Var::sensor_response_pol(), and ARTS::Var::sensor_response_pol_grid().
spt_calc_agenda()
void ARTS::AgendaExecute::spt_calc_agenda (Workspace & ws) inline
Calculates single scattering properties for individual scattering elements from the amplitude matrix.
This agenda sets up the methods, which should be used to calculate the single scattering properties, i.e. the extinction matrix and the absorbtion vector.
Normally you use: opt_prop_sptFromMonoData*
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147232 of file autoarts.h.
References ARTS::Var::aa_index(), ARTS::Var::abs_vec_spt(), ARTS::Var::ext_mat_spt(), ARTS::Var::rtp_temperature(), ARTS::Var::scat_lat_index(), ARTS::Var::scat_lon_index(), ARTS::Var::scat_p_index(), ARTS::Var::spt_calc_agenda(), spt_calc_agendaExecute(), and ARTS::Var::za_index().
surface_rtprop_agenda()
void ARTS::AgendaExecute::surface_rtprop_agenda (Workspace & ws) inline
Provides radiative properties of the surface.
Provides surface emission and surface reflection coefficient matrix (see user guide for closer definitions of the respective variables surface_emission*, surface_los, and surface_rmatrix) according to the characteristics of the surface specified by the methods called within the agenda. Typical meyhods include surfaceBlackbody, surfaceFlatScalarReflectivity*, surfaceFlatReflectivity, surfaceFlatRefractiveIndex*, and surfaceLambertianSimple.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147257 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::rtp_los(), ARTS::Var::rtp_pos(), ARTS::Var::surface_emission(), ARTS::Var::surface_los(), ARTS::Var::surface_rmatrix(), ARTS::Var::surface_rtprop_agenda(), surface_rtprop_agendaExecute(), and ARTS::Var::surface_skin_t().
surface_rtprop_agenda_array()
void ARTS::AgendaExecute::surface_rtprop_agenda_array (Workspace & ws) inline
Description of surface radiative properties, divided into surface types.
Each of these agendas shall treat the radiative properties of a surface type. The task of these agendas is equivalent to that of surface_rtprop_agenda*. This with one exception, these agendas have one additional input: surface_type_aux.
See surface_type_mask for comments on the surface type coding scheme. Note the parallel agenda series: iy_surface_sub_agendaX.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147281 of file autoarts.h.
References ARTS::Var::agenda_array_index(), ARTS::Var::f_grid(), ARTS::Var::rtp_los(), ARTS::Var::rtp_pos(), ARTS::Var::surface_emission(), ARTS::Var::surface_los(), ARTS::Var::surface_rmatrix(), ARTS::Var::surface_rtprop_agenda_array(), surface_rtprop_agenda_arrayExecute(), ARTS::Var::surface_skin_t(), and ARTS::Var::surface_type_aux().
surface_rtprop_sub_agenda()
void ARTS::AgendaExecute::surface_rtprop_sub_agenda (Workspace & ws) inline
Has exact same functionality as surface_rtprop_sub_agenda.
This agenda complements surface_rtprop_sub_agenda, to allow specifying the surface properties using two levels of agendas. For example, this agenda can describe the properties for pure specular reflections, and surface_rtprop_agenda can call this agenda for several angles to build up a more complex surface model.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147305 of file autoarts.h.
References ARTS::Var::f_grid(), ARTS::Var::rtp_los(), ARTS::Var::rtp_pos(), ARTS::Var::surface_emission(), ARTS::Var::surface_los(), ARTS::Var::surface_rmatrix(), ARTS::Var::surface_rtprop_sub_agenda(), surface_rtprop_sub_agendaExecute(), and ARTS::Var::surface_skin_t().
test_agenda()
void ARTS::AgendaExecute::test_agenda (Workspace & ws) inline
Dummy agenda for testing purposes.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147321 of file autoarts.h.
References ARTS::Var::test_agenda(), and test_agendaExecute().
test_agenda_array()
void ARTS::AgendaExecute::test_agenda_array (Workspace & ws) inline
Agenda array for TestArrayOfAgenda test case.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147330 of file autoarts.h.
References ARTS::Var::agenda_array_index(), ARTS::Var::iy_unit(), ARTS::Var::test_agenda_array(), and test_agenda_arrayExecute().
water_p_eq_agenda()
void ARTS::AgendaExecute::water_p_eq_agenda (Workspace & ws) inline
Calculation of the saturation pressure of water.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147341 of file autoarts.h.
References ARTS::Var::t_field(), ARTS::Var::water_p_eq_agenda(), water_p_eq_agendaExecute(), and ARTS::Var::water_p_eq_field().
ybatch_calc_agenda()
void ARTS::AgendaExecute::ybatch_calc_agenda (Workspace & ws) inline
Calculations to perform for each batch case.
Must produce a new spectrum vector (y) and Jacobi matrix (jacobian). See further ybatchCalc.
Parameters
[in,out] Workspace ws - An ARTS workspace
Definition at line 147355 of file autoarts.h.
References ARTS::Var::jacobian(), ARTS::Var::y(), ARTS::Var::y_aux(), ARTS::Var::ybatch_calc_agenda(), ybatch_calc_agendaExecute(), and ARTS::Var::ybatch_index().