ARTS: Constant Namespace Reference
Constant Namespace Reference
Namespace containing several constants, physical and mathematical.
Functions
template<class T >
constexpr auto pow2 (T x) -> decltype(x *x)
power of two
template<class T >
constexpr auto pow3 (T x) -> decltype(pow2(x) *x)
power of three
template<class T >
constexpr auto pow4 (T x) -> decltype(pow2(pow2(x)))
power of four
Detailed Description
Namespace containing several constants, physical and mathematical.
Function Documentation
pow2()
template<class T > constexpr auto Constant::pow2 (T x) -> decltype(x * x) constexpr
power of two
Definition at line 65 of file constants.h.
References ARTS::Var::x().
Referenced by LineShape::abs_squared(), Linefunctions::apply_linestrength_from_nlte_level_distributions(), lm_hitran_2017::calcw(), case_b_g_coefficient_o2(), lm_hitran_2017::compabs(), lm_hitran_2017::convtp(), dabsorption_nlte_rate_dF0(), dboltzman_factordT(), LineShape::HartmannTran::dFdD0(), LineShape::SpeedDependentVoigt::dFdD0(), LineShape::HartmannTran::dFdD2(), LineShape::SpeedDependentVoigt::dFdD2(), LineShape::HartmannTran::dFdETA(), LineShape::SpeedDependentVoigt::dFdF0(), LineShape::HartmannTran::dFdF0(), LineShape::HartmannTran::dFdG2(), LineShape::SpeedDependentVoigt::dFdG2(), LineShape::SpeedDependentVoigt::dFdH(), LineShape::HartmannTran::dFdH(), LineShape::Doppler::dFdT(), LineShape::SpeedDependentVoigt::dFdT(), LineShape::SpeedDependentVoigt::dFdVMR(), LineShape::HartmannTran::dFdVMR(), LineShape::VanVleckHuber::dNdf(), LineShape::VanVleckWeisskopf::dNdf(), LineShape::VanVleckHuber::dNdF0(), LineShape::VanVleckHuber::dNdT(), dnumber_density_dt(), dplanck_df(), dplanck_dt(), dstimulated_emissiondT(), Absorption::LineMixing::ENUMCLASS(), Zeeman::FromGrids(), LineShape::ComputeData::interp_add_triplequad(), Absorption::PredefinedModel::makarov2020_o2_lines_mpm(), LineShape::Lorentz::operator()(), LineShape::VanVleckWeisskopf::operator()(), pCqSDHC_to_arts(), planck(), pow3(), pow4(), lm_hitran_2017::qsdv(), lm_hitran_2017::qsdv_si(), Linefunctions::set_htp(), Absorption::LineMixing::PopulationAndDipole::sort(), Zeeman::Model::Strength(), test26(), and test28().
pow3()
template<class T > constexpr auto Constant::pow3 (T x) -> decltype(pow2(x) * x) constexpr
power of three
Definition at line 71 of file constants.h.
References pow2(), and ARTS::Var::x().
Referenced by case_b_g_coefficient_o2(), lm_hitran_2017::compabs(), Absorption::LineMixing::ENUMCLASS(), Absorption::PredefinedModel::makarov2020_o2_lines_mpm(), planck(), Linefunctions::set_htp(), and test28().
pow4()
template<class T > constexpr auto Constant::pow4 (T x) -> decltype(pow2(pow2(x))) constexpr
power of four
Definition at line 77 of file constants.h.
References pow2(), and ARTS::Var::x().
Referenced by dplanck_dt(), pCqSDHC_to_arts_D2_deriv(), pCqSDHC_to_arts_freq_deriv(), pCqSDHC_to_arts_G2_deriv(), and Linefunctions::set_htp().