ARTS: linalg Namespace Reference
linalg Namespace Reference
Functions
void avg (VectorView y, const ArrayOfVector &ys, const Index start=0, const Index end=-1)
Compute the average of the ranged ys.
void std (VectorView std, const Vector &y, const ArrayOfVector &ys, const Index start=0, const Index end=-1)
Compute the standard deviation of the ranged ys.
void var (VectorView var, const Vector &y, const ArrayOfVector &ys, const Index start=0, const Index end=-1)
Compute the variance of the ranged ys.
void cov (MatrixView cov, const Vector &y, const ArrayOfVector &ys, const Index start=0, const Index end=-1)
Compute the covariance matrix of the ranged ys.
Numeric median (const ConstVectorView v, const ArrayOfIndex &pos=ArrayOfIndex{})
Get the median of the vector in the range.
Function Documentation
avg()
void linalg::avg (VectorView y, const ArrayOfVector & ys, const Index start = 0, const Index end = -1)
Compute the average of the ranged ys.
The range of ys is [start, end) if end is positive or [start, ys.nelem()+end] otherwise
Parameters
[in,out] y N-dimensional Vector; Averages of y in given range
[in] ys list of N-dimensional Vector(s) to average
[in] start First index in ys
[in] end Past last index representation
Definition at line 32 of file raw.cc.
References Zeeman::end(), Array< base >::nelem(), Zeeman::start(), and ARTS::Var::y().
cov()
void linalg::cov (MatrixView cov, const Vector & y, const ArrayOfVector & ys, const Index start = 0, const Index end = -1)
Compute the covariance matrix of the ranged ys.
The range of ys is [start, end) if end is positive or [start, ys.nelem()+end] otherwise
Parameters
[in,out] cov N-by-N-dimensional Matrix; Covariance matrix
[in] y Averages of y in given range
[in] ys list of N-dimensional Vector(s) to average
[in] start First index in ys
[in] end Past last index representation
Definition at line 72 of file raw.cc.
References Zeeman::end(), Array< base >::nelem(), and Zeeman::start().
median()
Numeric linalg::median (const ConstVectorView v, const ArrayOfIndex & pos = ArrayOfIndex{})
Get the median of the vector in the range.
If pos is empty, use all numbers
Parameters
[in] v A Vector of any length
[in] pos Positions to use in the vector
Definition at line 90 of file raw.cc.
References Array< base >::nelem(), and v().
Referenced by ybatchTroposphericCorrectionNaiveMedianForward().
std()
void linalg::std (VectorView std, const Vector & y, const ArrayOfVector & ys, const Index start = 0, const Index end = -1)
Compute the standard deviation of the ranged ys.
The range of ys is [start, end) if end is positive or [start, ys.nelem()+end] otherwise
Parameters
[in,out] std N-dimensional Vector; Standard deviations
[in] y Averages of y in given range
[in] ys list of N-dimensional Vector(s) to average
[in] start First index in ys
[in] end Past last index representation
Definition at line 66 of file raw.cc.
References Zeeman::start(), transform(), var(), x, and ARTS::Var::y().
Referenced by test_oem_gauss_newton(), test_oem_gauss_newton_sparse(), test_oem_levenberg_marquardt(), and test_oem_linear().
var()
void linalg::var (VectorView var, const Vector & y, const ArrayOfVector & ys, const Index start = 0, const Index end = -1)
Compute the variance of the ranged ys.
The range of ys is [start, end) if end is positive or [start, ys.nelem()+end] otherwise
Parameters
[in,out] var N-dimensional Vector; Variance
[in] y Averages of y in given range
[in] ys list of N-dimensional Vector(s) to average
[in] start First index in ys
[in] end Past last index representation
Definition at line 49 of file raw.cc.
References Zeeman::end(), Array< base >::nelem(), and Zeeman::start().
Referenced by abs_linesSetLineShapeModelParametersForMatchingLines(), ARTS::Var::abs_t_interp_order(), AbsorptionLinesCreate(), add_scalar_variance(), AgendaCreate(), any_negative(), ArrayOfAbsorptionLinesCreate(), ArrayOfAgendaCreate(), ArrayOfArrayOfAbsorptionLinesCreate(), ArrayOfArrayOfGriddedField1Create(), ArrayOfArrayOfGriddedField2Create(), ArrayOfArrayOfGriddedField3Create(), ArrayOfArrayOfIndexCreate(), ArrayOfArrayOfMatrixCreate(), ArrayOfArrayOfPropagationMatrixCreate(), ArrayOfArrayOfRadiationVectorCreate(), ArrayOfArrayOfScatteringMetaDataCreate(), ArrayOfArrayOfSingleScatteringDataCreate(), ArrayOfArrayOfSpeciesTagCreate(), ArrayOfArrayOfStokesVectorCreate(), ArrayOfArrayOfStringCreate(), ArrayOfArrayOfTensor3Create(), ArrayOfArrayOfTensor6Create(), ArrayOfArrayOfTimeCreate(), ArrayOfArrayOfTransmissionMatrixCreate(), ArrayOfArrayOfVectorCreate(), ArrayOfCIARecordCreate(), ArrayOfGriddedField1Create(), ArrayOfGriddedField2Create(), ArrayOfGriddedField3Create(), ArrayOfGriddedField4Create(), ArrayOfIndexCreate(), ArrayOfJacobianTargetCreate(), ArrayOfMatrixCreate(), ArrayOfPpathCreate(), ArrayOfPropagationMatrixCreate(), ArrayOfQuantumIdentifierCreate(), ArrayOfRadiationVectorCreate(), ArrayOfRetrievalQuantityCreate(), ARTS::Var::ArrayOfScatteringMetaData::ArrayOfScatteringMetaData(), ArrayOfScatteringMetaDataCreate(), ArrayOfSingleScatteringDataCreate(), ArrayOfSparseCreate(), ArrayOfStokesVectorCreate(), ArrayOfStringCreate(), ArrayOfTelsemAtlasCreate(), ArrayOfTensor3Create(), ArrayOfTensor4Create(), ARTS::Var::ArrayOfTensor5::ArrayOfTensor5(), ArrayOfTensor5Create(), ArrayOfTensor6Create(), ArrayOfTensor7Create(), ArrayOfTimeCreate(), ArrayOfTransmissionMatrixCreate(), ArrayOfVectorCreate(), ArrayOfXsecRecordCreate(), ARTS::Var::atmfields_checked(), ARTS::Var::avk(), bad_propmat(), CIARecordCreate(), CovarianceMatrixCreate(), ARTS::Var::covmat_sx(), ARTS::Var::dsrc_xsec_per_species_dx(), ARTS::Var::dxdy(), EnergyLevelMapCreate(), GasAbsLookupCreate(), LineShape::SingleSpeciesModel::Get(), GriddedField1Create(), ARTS::Var::GriddedField2::GriddedField2(), GriddedField2Create(), GriddedField3Create(), GriddedField4Create(), GriddedField5Create(), GriddedField6Create(), GridPosCreate(), HitranRelaxationMatrixDataCreate(), IndexCreate(), Agenda::is_input(), Agenda::is_output(), ARTS::Var::ArrayOfArrayOfTensor6::islast(), ARTS::Var::ArrayOfTensor7::islast(), ARTS::Var::Ppath::islast(), ARTS::Var::GasAbsLookup::isnull(), ARTS::Var::iy_cloudbox_agenda(), ARTS::Var::iy_loop_freqs_agenda(), ARTS::Var::iy_transmission(), JacobianTargetCreate(), ARTS::Var::lm_ga_history(), MatrixCreate(), MCAntennaCreate(), LineShape::MetaData2ModelShape(), LineShape::ModelShape2MetaData(), ARTS::Var::ArrayOfQuantumIdentifier::name(), ARTS::Var::GriddedField4::name(), ARTS::Var::Tensor4::name(), NumericCreate(), ARTS::Var::ArrayOfGriddedField4::operator=(), ARTS::Var::SpeciesAuxData::operator=(), ARTS::Var::ArrayOfTelsemAtlas::pos(), ARTS::Var::Vector::pos(), PpathCreate(), PropagationMatrixCreate(), QuantumIdentifierCreate(), RadiationVectorCreate(), RationalCreate(), retrievalAddCatalogParameter(), ScatteringMetaDataCreate(), select_derivativeLineShape(), LineShape::SingleSpeciesModel::Set(), SingleScatteringDataCreate(), SparseCreate(), SpeciesAuxDataCreate(), split_quantum_numbers_from_hitran_online(), std(), StokesVectorCreate(), StringCreate(), TelsemAtlasCreate(), Tensor3Create(), Tensor4Create(), Tensor5Create(), Tensor6Create(), ARTS::Var::Tensor7::Tensor7(), Tensor7Create(), TessemNNCreate(), TimeCreate(), TimerCreate(), TransmissionMatrixCreate(), ARTS::Var::ArrayOfArrayOfSingleScatteringData::value(), ARTS::Var::HitranRelaxationMatrixData::value(), ARTS::Var::ArrayOfVector::value(), VectorCreate(), VerbosityCreate(), ARTS::Var::ArrayOfArrayOfVector::~ArrayOfArrayOfVector(), and ARTS::Var::RadiationVector::~RadiationVector().