ARTS: LineShape::LegacyLineMixingData Namespace Reference
LineShape::LegacyLineMixingData Namespace Reference
Legacy dealing with reading old LineMixingData.
Enumerations
enum class TypeLM {
LM_NONE , LM_LBLRTM , LM_LBLRTM_O2NonResonant , LM_1STORDER ,
LM_2NDORDER , LM_BYBAND
}
Line mixing types that used to exist.
Functions
LegacyLineMixingData::TypeLM string2typelm (String type)
Line mixing types from string.
constexpr Index typelm2nelem (LegacyLineMixingData::TypeLM type)
Line mixing types to number.
Model vector2modellm (Vector x, LegacyLineMixingData::TypeLM type)
LineShape::Model from legacy input vector.
Detailed Description
Legacy dealing with reading old LineMixingData.
Enumeration Type Documentation
TypeLM
enum LineShape::LegacyLineMixingData::TypeLM strong
Line mixing types that used to exist.
Enumerator
LM_NONE
LM_LBLRTM
LM_LBLRTM_O2NonResonant
LM_1STORDER
LM_2NDORDER
LM_BYBAND
Definition at line 1031 of file lineshapemodel.h.
Function Documentation
string2typelm()
LegacyLineMixingData::TypeLM LineShape::LegacyLineMixingData::string2typelm (String type)
Line mixing types from string.
Definition at line 1394 of file lineshapemodel.cc.
References ARTS_USER_ERROR, LM_1STORDER, LM_2NDORDER, LM_BYBAND, LM_LBLRTM, LM_LBLRTM_O2NonResonant, LM_NONE, and Hitran::type.
Referenced by LineShape::from_linemixingdata().
typelm2nelem()
constexpr Index LineShape::LegacyLineMixingData::typelm2nelem (LegacyLineMixingData::TypeLM type) constexpr
Line mixing types to number.
Definition at line 1046 of file lineshapemodel.h.
References Hitran::type.
Referenced by LineShape::from_linemixingdata().
vector2modellm()
LineShape::Model LineShape::LegacyLineMixingData::vector2modellm (Vector x, LegacyLineMixingData::TypeLM type)
LineShape::Model from legacy input vector.
Definition at line 404 of file lineshapemodel.cc.
References Hitran::type, ARTS::Var::x(), and ARTS::Var::y().
Referenced by LineShape::from_linemixingdata(), and Absorption::SingleLine::SetLineMixing2SecondOrderData().