ARTS: PartitionFunctions Namespace Reference
PartitionFunctions Namespace Reference
Namespaces
detail
Classes
struct Data
Enumerations
enum class Derivatives : bool { No , Yes }
Functions
constexpr Numeric Q (Numeric T, const Species::IsotopeRecord &ir)
constexpr Numeric dQdT (Numeric T, const Species::IsotopeRecord &ir)
constexpr bool has_partfun (const Species::IsotopeRecord &ir) noexcept
template<Derivatives deriv, std::size_t N>
Numeric linterp (const std::array< Numeric, N > &Tg, const std::array< Numeric, N > &Qg, const Numeric T) noexcept
template<Derivatives deriv, std::size_t N>
constexpr Numeric polynom (const std::array< Numeric, N > &coeffs, const Numeric T) noexcept
Data data_read_file (const std::filesystem::path &path)
template<Derivatives derivative>
constexpr Numeric computeBath (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeWater (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeOzone (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitrogenOxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeMethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeOxygen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitricOxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfurDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitrogenDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeAmmonia (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitricAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydroxyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenChloride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenBromide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenIodide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeChlorineMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonylSulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHeavyFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeVeryHeavyFormaldehyde (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHypochlorousAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitrogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenCyanide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeChloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenPeroxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeAcetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeEthane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePhosphine (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonylFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfurHexafluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenSulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeLeftHeavyFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeRightHeavyFormicAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydroperoxyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeOxygenAtom (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeChlorineNitrate (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitricOxideCation (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeChlorineDioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeBromineMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfuricAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeChlorineMonoxideDimer (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHypobromousAcid (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeEthylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeMethanol (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeBromomethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeAcetonitrile (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHeavyAcetonitrile (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonTetrafluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeDiacetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCyanoacetylene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonMonosulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenIsocyanide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfurMonoxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePropane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHydrogenAtom (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHelium (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeArgon (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfurTrioxide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCyanogen (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePhosgene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonDisulfide (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeMethyl (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCyclopropene (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHexafluoroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluoropropane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluorobutane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluoropentane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluorohexane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluorooctane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computePerfluorocyclobutane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCarbonTetrachloride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCFC11 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCFC113 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCFC114 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCFC115 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeCFC12 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeDichloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeTrichloroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeTrichloromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeBromochlorodifluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeBromotrifluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeDibromotetrafluoroethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHCFC141b (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHCFC142b (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHCFC22 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC125 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC134a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC143a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC152a (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC227ea (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC23 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC245fa (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC32 (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeNitrogenTrifluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeSulfurylFluoride (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeHFC4310mee (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeGermane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeIodomethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeFluoromethane (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeliquidcloud (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeicecloud (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computerain (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computefree_electrons (const Numeric T, const std::string_view name)
template<Derivatives derivative>
constexpr Numeric computeparticles (const Numeric T, const std::string_view name)
Variables
constexpr std::array< std::string_view, 0 > hasBath
constexpr std::array< std::string_view, 9 > hasWater
constexpr std::array< std::string_view, 13 > hasCarbonDioxide
constexpr std::array< std::string_view, 18 > hasOzone
constexpr std::array< std::string_view, 5 > hasNitrogenOxide
constexpr std::array< std::string_view, 9 > hasCarbonMonoxide
constexpr std::array< std::string_view, 4 > hasMethane
constexpr std::array< std::string_view, 6 > hasOxygen
constexpr std::array< std::string_view, 3 > hasNitricOxide
constexpr std::array< std::string_view, 4 > hasSulfurDioxide
constexpr std::array< std::string_view, 2 > hasNitrogenDioxide
constexpr std::array< std::string_view, 3 > hasAmmonia
constexpr std::array< std::string_view, 2 > hasNitricAcid
constexpr std::array< std::string_view, 3 > hasHydroxyl
constexpr std::array< std::string_view, 2 > hasHydrogenFluoride
constexpr std::array< std::string_view, 4 > hasHydrogenChloride
constexpr std::array< std::string_view, 4 > hasHydrogenBromide
constexpr std::array< std::string_view, 2 > hasHydrogenIodide
constexpr std::array< std::string_view, 2 > hasChlorineMonoxide
constexpr std::array< std::string_view, 6 > hasCarbonylSulfide
constexpr std::array< std::string_view, 3 > hasFormaldehyde
constexpr std::array< std::string_view, 1 > hasHeavyFormaldehyde
constexpr std::array< std::string_view, 1 > hasVeryHeavyFormaldehyde
constexpr std::array< std::string_view, 2 > hasHypochlorousAcid
constexpr std::array< std::string_view, 3 > hasNitrogen
constexpr std::array< std::string_view, 4 > hasHydrogenCyanide
constexpr std::array< std::string_view, 2 > hasChloromethane
constexpr std::array< std::string_view, 1 > hasHydrogenPeroxide
constexpr std::array< std::string_view, 3 > hasAcetylene
constexpr std::array< std::string_view, 3 > hasEthane
constexpr std::array< std::string_view, 1 > hasPhosphine
constexpr std::array< std::string_view, 2 > hasCarbonylFluoride
constexpr std::array< std::string_view, 1 > hasSulfurHexafluoride
constexpr std::array< std::string_view, 4 > hasHydrogenSulfide
constexpr std::array< std::string_view, 2 > hasFormicAcid
constexpr std::array< std::string_view, 1 > hasLeftHeavyFormicAcid
constexpr std::array< std::string_view, 1 > hasRightHeavyFormicAcid
constexpr std::array< std::string_view, 1 > hasHydroperoxyl
constexpr std::array< std::string_view, 1 > hasOxygenAtom
constexpr std::array< std::string_view, 2 > hasChlorineNitrate
constexpr std::array< std::string_view, 1 > hasNitricOxideCation
constexpr std::array< std::string_view, 2 > hasChlorineDioxide
constexpr std::array< std::string_view, 2 > hasBromineMonoxide
constexpr std::array< std::string_view, 1 > hasSulfuricAcid
constexpr std::array< std::string_view, 2 > hasChlorineMonoxideDimer
constexpr std::array< std::string_view, 2 > hasHypobromousAcid
constexpr std::array< std::string_view, 5 > hasEthylene
constexpr std::array< std::string_view, 1 > hasMethanol
constexpr std::array< std::string_view, 2 > hasBromomethane
constexpr std::array< std::string_view, 5 > hasAcetonitrile
constexpr std::array< std::string_view, 1 > hasHeavyAcetonitrile
constexpr std::array< std::string_view, 1 > hasCarbonTetrafluoride
constexpr std::array< std::string_view, 1 > hasDiacetylene
constexpr std::array< std::string_view, 6 > hasCyanoacetylene
constexpr std::array< std::string_view, 2 > hasHydrogen
constexpr std::array< std::string_view, 4 > hasCarbonMonosulfide
constexpr std::array< std::string_view, 4 > hasHydrogenIsocyanide
constexpr std::array< std::string_view, 3 > hasSulfurMonoxide
constexpr std::array< std::string_view, 1 > hasPropane
constexpr std::array< std::string_view, 1 > hasHydrogenAtom
constexpr std::array< std::string_view, 1 > hasHelium
constexpr std::array< std::string_view, 1 > hasArgon
constexpr std::array< std::string_view, 1 > hasSulfurTrioxide
constexpr std::array< std::string_view, 2 > hasCyanogen
constexpr std::array< std::string_view, 2 > hasPhosgene
constexpr std::array< std::string_view, 5 > hasCarbonDisulfide
constexpr std::array< std::string_view, 1 > hasMethyl
constexpr std::array< std::string_view, 1 > hasCyclopropene
constexpr std::array< std::string_view, 0 > hasHexafluoroethane
constexpr std::array< std::string_view, 0 > hasPerfluoropropane
constexpr std::array< std::string_view, 0 > hasPerfluorobutane
constexpr std::array< std::string_view, 0 > hasPerfluoropentane
constexpr std::array< std::string_view, 0 > hasPerfluorohexane
constexpr std::array< std::string_view, 0 > hasPerfluorooctane
constexpr std::array< std::string_view, 0 > hasPerfluorocyclobutane
constexpr std::array< std::string_view, 0 > hasCarbonTetrachloride
constexpr std::array< std::string_view, 0 > hasCFC11
constexpr std::array< std::string_view, 0 > hasCFC113
constexpr std::array< std::string_view, 0 > hasCFC114
constexpr std::array< std::string_view, 0 > hasCFC115
constexpr std::array< std::string_view, 0 > hasCFC12
constexpr std::array< std::string_view, 0 > hasDichloromethane
constexpr std::array< std::string_view, 0 > hasTrichloroethane
constexpr std::array< std::string_view, 0 > hasTrichloromethane
constexpr std::array< std::string_view, 0 > hasBromochlorodifluoromethane
constexpr std::array< std::string_view, 0 > hasBromotrifluoromethane
constexpr std::array< std::string_view, 0 > hasDibromotetrafluoroethane
constexpr std::array< std::string_view, 0 > hasHCFC141b
constexpr std::array< std::string_view, 0 > hasHCFC142b
constexpr std::array< std::string_view, 0 > hasHCFC22
constexpr std::array< std::string_view, 0 > hasHFC125
constexpr std::array< std::string_view, 0 > hasHFC134a
constexpr std::array< std::string_view, 0 > hasHFC143a
constexpr std::array< std::string_view, 0 > hasHFC152a
constexpr std::array< std::string_view, 0 > hasHFC227ea
constexpr std::array< std::string_view, 0 > hasHFC23
constexpr std::array< std::string_view, 0 > hasHFC245fa
constexpr std::array< std::string_view, 0 > hasHFC32
constexpr std::array< std::string_view, 1 > hasNitrogenTrifluoride
constexpr std::array< std::string_view, 0 > hasSulfurylFluoride
constexpr std::array< std::string_view, 0 > hasHFC4310mee
constexpr std::array< std::string_view, 5 > hasGermane
constexpr std::array< std::string_view, 2 > hasIodomethane
constexpr std::array< std::string_view, 1 > hasFluoromethane
constexpr std::array< std::string_view, 0 > hasliquidcloud
constexpr std::array< std::string_view, 0 > hasicecloud
constexpr std::array< std::string_view, 0 > hasrain
constexpr std::array< std::string_view, 0 > hasfree_electrons
constexpr std::array< std::string_view, 0 > hasparticles
Enumeration Type Documentation
Derivatives
enum PartitionFunctions::Derivatives : bool strong
Enumerator
No
Yes
Definition at line 26 of file template_partfun.h.
Function Documentation
computeAcetonitrile()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeAcetonitrile (const Numeric T, const std::string_view name) constexpr
Definition at line 137007 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasAcetonitrile.
computeAcetylene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeAcetylene (const Numeric T, const std::string_view name) constexpr
Definition at line 110353 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasAcetylene.
computeAmmonia()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeAmmonia (const Numeric T, const std::string_view name) constexpr
Definition at line 64524 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasAmmonia.
computeArgon()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeArgon (const Numeric T, const std::string_view name) constexpr
Definition at line 158299 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasArgon.
computeBath()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeBath (const Numeric T, const std::string_view name) constexpr
Definition at line 24 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasBath.
computeBromineMonoxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeBromineMonoxide (const Numeric T, const std::string_view name) constexpr
Definition at line 127745 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasBromineMonoxide.
computeBromochlorodifluoromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeBromochlorodifluoromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169339 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasBromochlorodifluoromethane.
computeBromomethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeBromomethane (const Numeric T, const std::string_view name) constexpr
Definition at line 134982 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasBromomethane.
computeBromotrifluoromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeBromotrifluoromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169351 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasBromotrifluoromethane.
computeCarbonDioxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonDioxide (const Numeric T, const std::string_view name) constexpr
Definition at line 9706 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonDioxide.
computeCarbonDisulfide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonDisulfide (const Numeric T, const std::string_view name) constexpr
Definition at line 163081 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonDisulfide.
computeCarbonMonosulfide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonMonosulfide (const Numeric T, const std::string_view name) constexpr
Definition at line 151160 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonMonosulfide.
computeCarbonMonoxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonMonoxide (const Numeric T, const std::string_view name) constexpr
Definition at line 29718 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonMonoxide.
computeCarbonTetrachloride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonTetrachloride (const Numeric T, const std::string_view name) constexpr
Definition at line 169231 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCarbonTetrachloride.
computeCarbonTetrafluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonTetrafluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 141057 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonTetrafluoride.
computeCarbonylFluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonylFluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 117323 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonylFluoride.
computeCarbonylSulfide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCarbonylSulfide (const Numeric T, const std::string_view name) constexpr
Definition at line 88733 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCarbonylSulfide.
computeCFC11()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCFC11 (const Numeric T, const std::string_view name) constexpr
Definition at line 169243 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCFC11.
computeCFC113()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCFC113 (const Numeric T, const std::string_view name) constexpr
Definition at line 169255 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCFC113.
computeCFC114()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCFC114 (const Numeric T, const std::string_view name) constexpr
Definition at line 169267 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCFC114.
computeCFC115()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCFC115 (const Numeric T, const std::string_view name) constexpr
Definition at line 169279 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCFC115.
computeCFC12()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCFC12 (const Numeric T, const std::string_view name) constexpr
Definition at line 169291 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasCFC12.
computeChlorineDioxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeChlorineDioxide (const Numeric T, const std::string_view name) constexpr
Definition at line 127723 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasChlorineDioxide.
computeChlorineMonoxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeChlorineMonoxide (const Numeric T, const std::string_view name) constexpr
Definition at line 86707 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasChlorineMonoxide.
computeChlorineMonoxideDimer()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeChlorineMonoxideDimer (const Numeric T, const std::string_view name) constexpr
Definition at line 127784 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasChlorineMonoxideDimer.
computeChlorineNitrate()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeChlorineNitrate (const Numeric T, const std::string_view name) constexpr
Definition at line 124684 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasChlorineNitrate.
computeChloromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeChloromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 107113 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasChloromethane.
computeCyanoacetylene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCyanoacetylene (const Numeric T, const std::string_view name) constexpr
Definition at line 142698 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCyanoacetylene.
computeCyanogen()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCyanogen (const Numeric T, const std::string_view name) constexpr
Definition at line 159034 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCyanogen.
computeCyclopropene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeCyclopropene (const Numeric T, const std::string_view name) constexpr
Definition at line 168131 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasCyclopropene.
computeDiacetylene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeDiacetylene (const Numeric T, const std::string_view name) constexpr
Definition at line 141676 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasDiacetylene.
computeDibromotetrafluoroethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeDibromotetrafluoroethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169363 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasDibromotetrafluoroethane.
computeDichloromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeDichloromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169303 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasDichloromethane.
computeEthane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeEthane (const Numeric T, const std::string_view name) constexpr
Definition at line 113380 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasEthane.
computeEthylene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeEthylene (const Numeric T, const std::string_view name) constexpr
Definition at line 129831 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasEthylene.
computeFluoromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeFluoromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 177608 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasFluoromethane.
computeFormaldehyde()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeFormaldehyde (const Numeric T, const std::string_view name) constexpr
Definition at line 94772 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasFormaldehyde.
computeFormicAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeFormicAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 122594 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasFormicAcid.
computefree_electrons()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computefree_electrons (const Numeric T, const std::string_view name) constexpr
Definition at line 178660 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasfree_electrons.
computeGermane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeGermane (const Numeric T, const std::string_view name) constexpr
Definition at line 170553 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasGermane.
computeHCFC141b()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHCFC141b (const Numeric T, const std::string_view name) constexpr
Definition at line 169375 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHCFC141b.
computeHCFC142b()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHCFC142b (const Numeric T, const std::string_view name) constexpr
Definition at line 169387 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHCFC142b.
computeHCFC22()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHCFC22 (const Numeric T, const std::string_view name) constexpr
Definition at line 169399 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHCFC22.
computeHeavyAcetonitrile()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHeavyAcetonitrile (const Numeric T, const std::string_view name) constexpr
Definition at line 141040 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHeavyAcetonitrile.
computeHeavyFormaldehyde()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHeavyFormaldehyde (const Numeric T, const std::string_view name) constexpr
Definition at line 97497 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHeavyFormaldehyde.
computeHelium()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHelium (const Numeric T, const std::string_view name) constexpr
Definition at line 158282 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHelium.
computeHexafluoroethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHexafluoroethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169147 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHexafluoroethane.
computeHFC125()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC125 (const Numeric T, const std::string_view name) constexpr
Definition at line 169411 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC125.
computeHFC134a()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC134a (const Numeric T, const std::string_view name) constexpr
Definition at line 169423 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC134a.
computeHFC143a()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC143a (const Numeric T, const std::string_view name) constexpr
Definition at line 169435 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC143a.
computeHFC152a()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC152a (const Numeric T, const std::string_view name) constexpr
Definition at line 169447 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC152a.
computeHFC227ea()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC227ea (const Numeric T, const std::string_view name) constexpr
Definition at line 169459 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC227ea.
computeHFC23()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC23 (const Numeric T, const std::string_view name) constexpr
Definition at line 169471 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC23.
computeHFC245fa()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC245fa (const Numeric T, const std::string_view name) constexpr
Definition at line 169483 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC245fa.
computeHFC32()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC32 (const Numeric T, const std::string_view name) constexpr
Definition at line 169495 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC32.
computeHFC4310mee()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHFC4310mee (const Numeric T, const std::string_view name) constexpr
Definition at line 170536 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHFC4310mee.
computeHydrogen()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogen (const Numeric T, const std::string_view name) constexpr
Definition at line 148736 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogen.
computeHydrogenAtom()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenAtom (const Numeric T, const std::string_view name) constexpr
Definition at line 158265 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHydrogenAtom.
computeHydrogenBromide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenBromide (const Numeric T, const std::string_view name) constexpr
Definition at line 79455 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenBromide.
computeHydrogenChloride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenChloride (const Numeric T, const std::string_view name) constexpr
Definition at line 74623 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenChloride.
computeHydrogenCyanide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenCyanide (const Numeric T, const std::string_view name) constexpr
Definition at line 104983 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenCyanide.
computeHydrogenFluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenFluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 72199 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenFluoride.
computeHydrogenIodide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenIodide (const Numeric T, const std::string_view name) constexpr
Definition at line 84285 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenIodide.
computeHydrogenIsocyanide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenIsocyanide (const Numeric T, const std::string_view name) constexpr
Definition at line 155192 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasHydrogenIsocyanide.
computeHydrogenPeroxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenPeroxide (const Numeric T, const std::string_view name) constexpr
Definition at line 109134 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenPeroxide.
computeHydrogenSulfide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydrogenSulfide (const Numeric T, const std::string_view name) constexpr
Definition at line 119764 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydrogenSulfide.
computeHydroperoxyl()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydroperoxyl (const Numeric T, const std::string_view name) constexpr
Definition at line 123649 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydroperoxyl.
computeHydroxyl()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHydroxyl (const Numeric T, const std::string_view name) constexpr
Definition at line 68373 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHydroxyl.
computeHypobromousAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHypobromousAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 127806 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHypobromousAcid.
computeHypochlorousAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeHypochlorousAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 97532 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasHypochlorousAcid.
computeicecloud()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeicecloud (const Numeric T, const std::string_view name) constexpr
Definition at line 178636 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasicecloud.
computeIodomethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeIodomethane (const Numeric T, const std::string_view name) constexpr
Definition at line 175587 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasIodomethane.
computeLeftHeavyFormicAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeLeftHeavyFormicAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 123615 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasLeftHeavyFormicAcid.
computeliquidcloud()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeliquidcloud (const Numeric T, const std::string_view name) constexpr
Definition at line 178624 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasliquidcloud.
computeMethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeMethane (const Numeric T, const std::string_view name) constexpr
Definition at line 45970 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasMethane.
computeMethanol()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeMethanol (const Numeric T, const std::string_view name) constexpr
Definition at line 134264 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasMethanol.
computeMethyl()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeMethyl (const Numeric T, const std::string_view name) constexpr
Definition at line 167114 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasMethyl.
computeNitricAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitricAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 66950 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitricAcid.
computeNitricOxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitricOxide (const Numeric T, const std::string_view name) constexpr
Definition at line 57043 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitricOxide.
computeNitricOxideCation()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitricOxideCation (const Numeric T, const std::string_view name) constexpr
Definition at line 126705 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitricOxideCation.
computeNitrogen()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitrogen (const Numeric T, const std::string_view name) constexpr
Definition at line 99555 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitrogen.
computeNitrogenDioxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitrogenDioxide (const Numeric T, const std::string_view name) constexpr
Definition at line 64101 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitrogenDioxide.
computeNitrogenOxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitrogenOxide (const Numeric T, const std::string_view name) constexpr
Definition at line 24677 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitrogenOxide.
computeNitrogenTrifluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeNitrogenTrifluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 169508 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasNitrogenTrifluoride.
computeOxygen()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeOxygen (const Numeric T, const std::string_view name) constexpr
Definition at line 48004 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasOxygen.
computeOxygenAtom()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeOxygenAtom (const Numeric T, const std::string_view name) constexpr
Definition at line 124666 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasOxygenAtom.
computeOzone()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeOzone (const Numeric T, const std::string_view name) constexpr
Definition at line 20988 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasOzone.
computeparticles()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeparticles (const Numeric T, const std::string_view name) constexpr
Definition at line 178672 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasparticles.
computePerfluorobutane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluorobutane (const Numeric T, const std::string_view name) constexpr
Definition at line 169171 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluorobutane.
computePerfluorocyclobutane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluorocyclobutane (const Numeric T, const std::string_view name) constexpr
Definition at line 169219 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluorocyclobutane.
computePerfluorohexane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluorohexane (const Numeric T, const std::string_view name) constexpr
Definition at line 169195 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluorohexane.
computePerfluorooctane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluorooctane (const Numeric T, const std::string_view name) constexpr
Definition at line 169207 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluorooctane.
computePerfluoropentane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluoropentane (const Numeric T, const std::string_view name) constexpr
Definition at line 169183 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluoropentane.
computePerfluoropropane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePerfluoropropane (const Numeric T, const std::string_view name) constexpr
Definition at line 169159 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPerfluoropropane.
computePhosgene()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePhosgene (const Numeric T, const std::string_view name) constexpr
Definition at line 161056 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasPhosgene.
computePhosphine()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePhosphine (const Numeric T, const std::string_view name) constexpr
Definition at line 116405 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasPhosphine.
computePropane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computePropane (const Numeric T, const std::string_view name) constexpr
Definition at line 158248 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasPropane.
computerain()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computerain (const Numeric T, const std::string_view name) constexpr
Definition at line 178648 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasrain.
computeRightHeavyFormicAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeRightHeavyFormicAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 123632 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasRightHeavyFormicAcid.
computeSulfurDioxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfurDioxide (const Numeric T, const std::string_view name) constexpr
Definition at line 60071 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasSulfurDioxide.
computeSulfurHexafluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfurHexafluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 118744 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasSulfurHexafluoride.
computeSulfuricAcid()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfuricAcid (const Numeric T, const std::string_view name) constexpr
Definition at line 127766 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasSulfuricAcid.
computeSulfurMonoxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfurMonoxide (const Numeric T, const std::string_view name) constexpr
Definition at line 155223 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasSulfurMonoxide.
computeSulfurTrioxide()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfurTrioxide (const Numeric T, const std::string_view name) constexpr
Definition at line 158316 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasSulfurTrioxide.
computeSulfurylFluoride()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeSulfurylFluoride (const Numeric T, const std::string_view name) constexpr
Definition at line 170524 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasSulfurylFluoride.
computeTrichloroethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeTrichloroethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169315 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasTrichloroethane.
computeTrichloromethane()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeTrichloromethane (const Numeric T, const std::string_view name) constexpr
Definition at line 169327 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasTrichloromethane.
computeVeryHeavyFormaldehyde()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeVeryHeavyFormaldehyde (const Numeric T, const std::string_view name) constexpr
Definition at line 97514 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), and hasVeryHeavyFormaldehyde.
computeWater()
template<Derivatives derivative> constexpr Numeric PartitionFunctions::computeWater (const Numeric T, const std::string_view name) constexpr
Definition at line 45 of file auto_partfun.h.
References ARTS_USER_ERROR, column_string(), data, and hasWater.
data_read_file()
Data PartitionFunctions::data_read_file (const std::filesystem::path & path)
Definition at line 114 of file xml_io_partfun.cc.
References xml_read_from_file_base().
Referenced by gen_fil().
dQdT()
constexpr Numeric PartitionFunctions::dQdT (Numeric T, const Species::IsotopeRecord & ir) constexpr
Definition at line 143 of file partfun.h.
Referenced by dsingle_partition_function_dT(), and Species::ENUMCLASS().
has_partfun()
constexpr bool PartitionFunctions::has_partfun (const Species::IsotopeRecord & ir) constexpr noexcept
Definition at line 147 of file partfun.h.
References deal_with_spec.
Referenced by checkPartitionFunctions(), nonexistentPartfun(), and WriteBuiltinPartitionFunctionsXML().
linterp()
template<Derivatives deriv, std::size_t N> Numeric PartitionFunctions::linterp (const std::array< Numeric, N > & Tg, const std::array< Numeric, N > & Qg, const Numeric T) noexcept
Definition at line 29 of file template_partfun.h.
References min, N, and No.
polynom()
template<Derivatives deriv, std::size_t N> constexpr Numeric PartitionFunctions::polynom (const std::array< Numeric, N > & coeffs, const Numeric T) constexpr noexcept
Definition at line 46 of file template_partfun.h.
References c, N, and No.
Q()
constexpr Numeric PartitionFunctions::Q (Numeric T, const Species::IsotopeRecord & ir) constexpr
Definition at line 139 of file partfun.h.
Referenced by Species::ENUMCLASS(), ext_I(), main(), MCGeneral(), single_partition_function(), and WriteBuiltinPartitionFunctionsXML().
Variable Documentation
hasAcetonitrile
constexpr std::array<std::string_view, 5> PartitionFunctions::hasAcetonitrile constexpr
Initial value:
{
"2124",
"2125",
"2134",
"3124",
"3134",
}
Definition at line 136998 of file auto_partfun.h.
Referenced by computeAcetonitrile().
hasAcetylene
constexpr std::array<std::string_view, 3> PartitionFunctions::hasAcetylene constexpr
Initial value:
{
"1221",
"1222",
"1231",
}
Definition at line 110346 of file auto_partfun.h.
Referenced by computeAcetylene().
hasAmmonia
constexpr std::array<std::string_view, 3> PartitionFunctions::hasAmmonia constexpr
Initial value:
{
"4111",
"4112",
"5111",
}
Definition at line 64517 of file auto_partfun.h.
Referenced by computeAmmonia().
hasArgon
constexpr std::array<std::string_view, 1> PartitionFunctions::hasArgon constexpr
Initial value:
{
"8",
}
Definition at line 158294 of file auto_partfun.h.
Referenced by computeArgon().
hasBath
constexpr std::array<std::string_view, 0> PartitionFunctions::hasBath constexpr
Initial value:
{
}
Definition at line 20 of file auto_partfun.h.
Referenced by computeBath().
hasBromineMonoxide
constexpr std::array<std::string_view, 2> PartitionFunctions::hasBromineMonoxide constexpr
Initial value:
{
"16",
"96",
}
Definition at line 127739 of file auto_partfun.h.
Referenced by computeBromineMonoxide().
hasBromochlorodifluoromethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasBromochlorodifluoromethane constexpr
Initial value:
{
}
Definition at line 169335 of file auto_partfun.h.
Referenced by computeBromochlorodifluoromethane().
hasBromomethane
constexpr std::array<std::string_view, 2> PartitionFunctions::hasBromomethane constexpr
Initial value:
{
"211",
"219",
}
Definition at line 134976 of file auto_partfun.h.
Referenced by computeBromomethane().
hasBromotrifluoromethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasBromotrifluoromethane constexpr
Initial value:
{
}
Definition at line 169347 of file auto_partfun.h.
Referenced by computeBromotrifluoromethane().
hasCarbonDioxide
constexpr std::array<std::string_view, 13> PartitionFunctions::hasCarbonDioxide constexpr
Initial value:
{
"626",
"627",
"628",
"636",
"637",
"638",
"646",
"727",
"737",
"827",
"828",
"837",
"838",
}
Definition at line 9689 of file auto_partfun.h.
Referenced by computeCarbonDioxide().
hasCarbonDisulfide
constexpr std::array<std::string_view, 5> PartitionFunctions::hasCarbonDisulfide constexpr
Initial value:
{
"222",
"223",
"224",
"232",
"244",
}
Definition at line 163072 of file auto_partfun.h.
Referenced by computeCarbonDisulfide().
hasCarbonMonosulfide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasCarbonMonosulfide constexpr
Initial value:
{
"22",
"23",
"24",
"32",
}
Definition at line 151152 of file auto_partfun.h.
Referenced by computeCarbonMonosulfide().
hasCarbonMonoxide
constexpr std::array<std::string_view, 9> PartitionFunctions::hasCarbonMonoxide constexpr
Initial value:
{
"26",
"27",
"28",
"36",
"37",
"38",
"46",
"47",
"48",
}
Definition at line 29705 of file auto_partfun.h.
Referenced by computeCarbonMonoxide().
hasCarbonTetrachloride
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCarbonTetrachloride constexpr
Initial value:
{
}
Definition at line 169227 of file auto_partfun.h.
Referenced by computeCarbonTetrachloride().
hasCarbonTetrafluoride
constexpr std::array<std::string_view, 1> PartitionFunctions::hasCarbonTetrafluoride constexpr
Initial value:
{
"29",
}
Definition at line 141052 of file auto_partfun.h.
Referenced by computeCarbonTetrafluoride().
hasCarbonylFluoride
constexpr std::array<std::string_view, 2> PartitionFunctions::hasCarbonylFluoride constexpr
Initial value:
{
"269",
"369",
}
Definition at line 117317 of file auto_partfun.h.
Referenced by computeCarbonylFluoride().
hasCarbonylSulfide
constexpr std::array<std::string_view, 6> PartitionFunctions::hasCarbonylSulfide constexpr
Initial value:
{
"622",
"623",
"624",
"632",
"634",
"822",
}
Definition at line 88723 of file auto_partfun.h.
Referenced by computeCarbonylSulfide().
hasCFC11
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCFC11 constexpr
Initial value:
{
}
Definition at line 169239 of file auto_partfun.h.
Referenced by computeCFC11().
hasCFC113
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCFC113 constexpr
Initial value:
{
}
Definition at line 169251 of file auto_partfun.h.
Referenced by computeCFC113().
hasCFC114
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCFC114 constexpr
Initial value:
{
}
Definition at line 169263 of file auto_partfun.h.
Referenced by computeCFC114().
hasCFC115
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCFC115 constexpr
Initial value:
{
}
Definition at line 169275 of file auto_partfun.h.
Referenced by computeCFC115().
hasCFC12
constexpr std::array<std::string_view, 0> PartitionFunctions::hasCFC12 constexpr
Initial value:
{
}
Definition at line 169287 of file auto_partfun.h.
Referenced by computeCFC12().
hasChlorineDioxide
constexpr std::array<std::string_view, 2> PartitionFunctions::hasChlorineDioxide constexpr
Initial value:
{
"656",
"676",
}
Definition at line 127717 of file auto_partfun.h.
Referenced by computeChlorineDioxide().
hasChlorineMonoxide
constexpr std::array<std::string_view, 2> PartitionFunctions::hasChlorineMonoxide constexpr
Initial value:
{
"56",
"76",
}
Definition at line 86701 of file auto_partfun.h.
Referenced by computeChlorineMonoxide().
hasChlorineMonoxideDimer
constexpr std::array<std::string_view, 2> PartitionFunctions::hasChlorineMonoxideDimer constexpr
Initial value:
{
"565",
"765",
}
Definition at line 127778 of file auto_partfun.h.
Referenced by computeChlorineMonoxideDimer().
hasChlorineNitrate
constexpr std::array<std::string_view, 2> PartitionFunctions::hasChlorineNitrate constexpr
Initial value:
{
"5646",
"7646",
}
Definition at line 124678 of file auto_partfun.h.
Referenced by computeChlorineNitrate().
hasChloromethane
constexpr std::array<std::string_view, 2> PartitionFunctions::hasChloromethane constexpr
Initial value:
{
"215",
"217",
}
Definition at line 107107 of file auto_partfun.h.
Referenced by computeChloromethane().
hasCyanoacetylene
constexpr std::array<std::string_view, 6> PartitionFunctions::hasCyanoacetylene constexpr
Initial value:
{
"12224",
"12225",
"12234",
"12324",
"13224",
"22224",
}
Definition at line 142688 of file auto_partfun.h.
Referenced by computeCyanoacetylene().
hasCyanogen
constexpr std::array<std::string_view, 2> PartitionFunctions::hasCyanogen constexpr
Initial value:
{
"4224",
"5225",
}
Definition at line 159028 of file auto_partfun.h.
Referenced by computeCyanogen().
hasCyclopropene
constexpr std::array<std::string_view, 1> PartitionFunctions::hasCyclopropene constexpr
Initial value:
{
"1221",
}
Definition at line 168126 of file auto_partfun.h.
Referenced by computeCyclopropene().
hasDiacetylene
constexpr std::array<std::string_view, 1> PartitionFunctions::hasDiacetylene constexpr
Initial value:
{
"2211",
}
Definition at line 141671 of file auto_partfun.h.
Referenced by computeDiacetylene().
hasDibromotetrafluoroethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasDibromotetrafluoroethane constexpr
Initial value:
{
}
Definition at line 169359 of file auto_partfun.h.
Referenced by computeDibromotetrafluoroethane().
hasDichloromethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasDichloromethane constexpr
Initial value:
{
}
Definition at line 169299 of file auto_partfun.h.
Referenced by computeDichloromethane().
hasEthane
constexpr std::array<std::string_view, 3> PartitionFunctions::hasEthane constexpr
Initial value:
{
"1221",
"1222",
"1231",
}
Definition at line 113373 of file auto_partfun.h.
Referenced by computeEthane().
hasEthylene
constexpr std::array<std::string_view, 5> PartitionFunctions::hasEthylene constexpr
Initial value:
{
"112211",
"112212",
"112311",
"221",
"231",
}
Definition at line 129822 of file auto_partfun.h.
Referenced by computeEthylene().
hasFluoromethane
constexpr std::array<std::string_view, 1> PartitionFunctions::hasFluoromethane constexpr
Initial value:
{
"219",
}
Definition at line 177603 of file auto_partfun.h.
Referenced by computeFluoromethane().
hasFormaldehyde
constexpr std::array<std::string_view, 3> PartitionFunctions::hasFormaldehyde constexpr
Initial value:
{
"126",
"128",
"136",
}
Definition at line 94765 of file auto_partfun.h.
Referenced by computeFormaldehyde().
hasFormicAcid
constexpr std::array<std::string_view, 2> PartitionFunctions::hasFormicAcid constexpr
Initial value:
{
"126",
"136",
}
Definition at line 122588 of file auto_partfun.h.
Referenced by computeFormicAcid().
hasfree_electrons
constexpr std::array<std::string_view, 0> PartitionFunctions::hasfree_electrons constexpr
Initial value:
{
}
Definition at line 178656 of file auto_partfun.h.
Referenced by computefree_electrons().
hasGermane
constexpr std::array<std::string_view, 5> PartitionFunctions::hasGermane constexpr
Initial value:
{
"7011",
"7211",
"7311",
"7411",
"7611",
}
Definition at line 170544 of file auto_partfun.h.
Referenced by computeGermane().
hasHCFC141b
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHCFC141b constexpr
Initial value:
{
}
Definition at line 169371 of file auto_partfun.h.
Referenced by computeHCFC141b().
hasHCFC142b
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHCFC142b constexpr
Initial value:
{
}
Definition at line 169383 of file auto_partfun.h.
Referenced by computeHCFC142b().
hasHCFC22
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHCFC22 constexpr
Initial value:
{
}
Definition at line 169395 of file auto_partfun.h.
Referenced by computeHCFC22().
hasHeavyAcetonitrile
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHeavyAcetonitrile constexpr
Initial value:
{
"224",
}
Definition at line 141035 of file auto_partfun.h.
Referenced by computeHeavyAcetonitrile().
hasHeavyFormaldehyde
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHeavyFormaldehyde constexpr
Initial value:
{
"26",
}
Definition at line 97492 of file auto_partfun.h.
Referenced by computeHeavyFormaldehyde().
hasHelium
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHelium constexpr
Initial value:
{
"4",
}
Definition at line 158277 of file auto_partfun.h.
Referenced by computeHelium().
hasHexafluoroethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHexafluoroethane constexpr
Initial value:
{
}
Definition at line 169143 of file auto_partfun.h.
Referenced by computeHexafluoroethane().
hasHFC125
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC125 constexpr
Initial value:
{
}
Definition at line 169407 of file auto_partfun.h.
Referenced by computeHFC125().
hasHFC134a
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC134a constexpr
Initial value:
{
}
Definition at line 169419 of file auto_partfun.h.
Referenced by computeHFC134a().
hasHFC143a
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC143a constexpr
Initial value:
{
}
Definition at line 169431 of file auto_partfun.h.
Referenced by computeHFC143a().
hasHFC152a
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC152a constexpr
Initial value:
{
}
Definition at line 169443 of file auto_partfun.h.
Referenced by computeHFC152a().
hasHFC227ea
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC227ea constexpr
Initial value:
{
}
Definition at line 169455 of file auto_partfun.h.
Referenced by computeHFC227ea().
hasHFC23
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC23 constexpr
Initial value:
{
}
Definition at line 169467 of file auto_partfun.h.
Referenced by computeHFC23().
hasHFC245fa
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC245fa constexpr
Initial value:
{
}
Definition at line 169479 of file auto_partfun.h.
Referenced by computeHFC245fa().
hasHFC32
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC32 constexpr
Initial value:
{
}
Definition at line 169491 of file auto_partfun.h.
Referenced by computeHFC32().
hasHFC4310mee
constexpr std::array<std::string_view, 0> PartitionFunctions::hasHFC4310mee constexpr
Initial value:
{
}
Definition at line 170532 of file auto_partfun.h.
Referenced by computeHFC4310mee().
hasHydrogen
constexpr std::array<std::string_view, 2> PartitionFunctions::hasHydrogen constexpr
Initial value:
{
"11",
"12",
}
Definition at line 148730 of file auto_partfun.h.
Referenced by computeHydrogen().
hasHydrogenAtom
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHydrogenAtom constexpr
Initial value:
{
"1",
}
Definition at line 158260 of file auto_partfun.h.
Referenced by computeHydrogenAtom().
hasHydrogenBromide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasHydrogenBromide constexpr
Initial value:
{
"11",
"19",
"21",
"29",
}
Definition at line 79447 of file auto_partfun.h.
Referenced by computeHydrogenBromide().
hasHydrogenChloride
constexpr std::array<std::string_view, 4> PartitionFunctions::hasHydrogenChloride constexpr
Initial value:
{
"15",
"17",
"25",
"27",
}
Definition at line 74615 of file auto_partfun.h.
Referenced by computeHydrogenChloride().
hasHydrogenCyanide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasHydrogenCyanide constexpr
Initial value:
{
"124",
"125",
"134",
"224",
}
Definition at line 104975 of file auto_partfun.h.
Referenced by computeHydrogenCyanide().
hasHydrogenFluoride
constexpr std::array<std::string_view, 2> PartitionFunctions::hasHydrogenFluoride constexpr
Initial value:
{
"19",
"29",
}
Definition at line 72193 of file auto_partfun.h.
Referenced by computeHydrogenFluoride().
hasHydrogenIodide
constexpr std::array<std::string_view, 2> PartitionFunctions::hasHydrogenIodide constexpr
Initial value:
{
"17",
"27",
}
Definition at line 84279 of file auto_partfun.h.
Referenced by computeHydrogenIodide().
hasHydrogenIsocyanide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasHydrogenIsocyanide constexpr
Initial value:
{
"142",
"143",
"152",
"242",
}
Definition at line 155184 of file auto_partfun.h.
Referenced by computeHydrogenIsocyanide().
hasHydrogenPeroxide
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHydrogenPeroxide constexpr
Initial value:
{
"1661",
}
Definition at line 109129 of file auto_partfun.h.
Referenced by computeHydrogenPeroxide().
hasHydrogenSulfide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasHydrogenSulfide constexpr
Initial value:
{
"121",
"122",
"131",
"141",
}
Definition at line 119756 of file auto_partfun.h.
Referenced by computeHydrogenSulfide().
hasHydroperoxyl
constexpr std::array<std::string_view, 1> PartitionFunctions::hasHydroperoxyl constexpr
Initial value:
{
"166",
}
Definition at line 123644 of file auto_partfun.h.
Referenced by computeHydroperoxyl().
hasHydroxyl
constexpr std::array<std::string_view, 3> PartitionFunctions::hasHydroxyl constexpr
Initial value:
{
"61",
"62",
"81",
}
Definition at line 68366 of file auto_partfun.h.
Referenced by computeHydroxyl().
hasHypobromousAcid
constexpr std::array<std::string_view, 2> PartitionFunctions::hasHypobromousAcid constexpr
Initial value:
{
"161",
"169",
}
Definition at line 127800 of file auto_partfun.h.
Referenced by computeHypobromousAcid().
hasHypochlorousAcid
constexpr std::array<std::string_view, 2> PartitionFunctions::hasHypochlorousAcid constexpr
Initial value:
{
"165",
"167",
}
Definition at line 97526 of file auto_partfun.h.
Referenced by computeHypochlorousAcid().
hasicecloud
constexpr std::array<std::string_view, 0> PartitionFunctions::hasicecloud constexpr
Initial value:
{
}
Definition at line 178632 of file auto_partfun.h.
Referenced by computeicecloud().
hasIodomethane
constexpr std::array<std::string_view, 2> PartitionFunctions::hasIodomethane constexpr
Initial value:
{
"271",
"317",
}
Definition at line 175581 of file auto_partfun.h.
Referenced by computeIodomethane().
hasLeftHeavyFormicAcid
constexpr std::array<std::string_view, 1> PartitionFunctions::hasLeftHeavyFormicAcid constexpr
Initial value:
{
"266",
}
Definition at line 123610 of file auto_partfun.h.
Referenced by computeLeftHeavyFormicAcid().
hasliquidcloud
constexpr std::array<std::string_view, 0> PartitionFunctions::hasliquidcloud constexpr
Initial value:
{
}
Definition at line 178620 of file auto_partfun.h.
Referenced by computeliquidcloud().
hasMethane
constexpr std::array<std::string_view, 4> PartitionFunctions::hasMethane constexpr
Initial value:
{
"211",
"212",
"311",
"312",
}
Definition at line 45962 of file auto_partfun.h.
Referenced by computeMethane().
hasMethanol
constexpr std::array<std::string_view, 1> PartitionFunctions::hasMethanol constexpr
Initial value:
{
"2161",
}
Definition at line 134259 of file auto_partfun.h.
Referenced by computeMethanol().
hasMethyl
constexpr std::array<std::string_view, 1> PartitionFunctions::hasMethyl constexpr
Initial value:
{
"2111",
}
Definition at line 167109 of file auto_partfun.h.
Referenced by computeMethyl().
hasNitricAcid
constexpr std::array<std::string_view, 2> PartitionFunctions::hasNitricAcid constexpr
Initial value:
{
"146",
"156",
}
Definition at line 66944 of file auto_partfun.h.
Referenced by computeNitricAcid().
hasNitricOxide
constexpr std::array<std::string_view, 3> PartitionFunctions::hasNitricOxide constexpr
Initial value:
{
"46",
"48",
"56",
}
Definition at line 57036 of file auto_partfun.h.
Referenced by computeNitricOxide().
hasNitricOxideCation
constexpr std::array<std::string_view, 1> PartitionFunctions::hasNitricOxideCation constexpr
Initial value:
{
"46",
}
Definition at line 126700 of file auto_partfun.h.
Referenced by computeNitricOxideCation().
hasNitrogen
constexpr std::array<std::string_view, 3> PartitionFunctions::hasNitrogen constexpr
Initial value:
{
"44",
"45",
"55",
}
Definition at line 99548 of file auto_partfun.h.
Referenced by computeNitrogen().
hasNitrogenDioxide
constexpr std::array<std::string_view, 2> PartitionFunctions::hasNitrogenDioxide constexpr
Initial value:
{
"646",
"656",
}
Definition at line 64095 of file auto_partfun.h.
Referenced by computeNitrogenDioxide().
hasNitrogenOxide
constexpr std::array<std::string_view, 5> PartitionFunctions::hasNitrogenOxide constexpr
Initial value:
{
"446",
"447",
"448",
"456",
"546",
}
Definition at line 24668 of file auto_partfun.h.
Referenced by computeNitrogenOxide().
hasNitrogenTrifluoride
constexpr std::array<std::string_view, 1> PartitionFunctions::hasNitrogenTrifluoride constexpr
Initial value:
{
"49",
}
Definition at line 169503 of file auto_partfun.h.
Referenced by computeNitrogenTrifluoride().
hasOxygen
constexpr std::array<std::string_view, 6> PartitionFunctions::hasOxygen constexpr
Initial value:
{
"66",
"67",
"68",
"77",
"87",
"88",
}
Definition at line 47994 of file auto_partfun.h.
Referenced by computeOxygen().
hasOxygenAtom
constexpr std::array<std::string_view, 1> PartitionFunctions::hasOxygenAtom constexpr
Initial value:
{
"6",
}
Definition at line 124661 of file auto_partfun.h.
Referenced by computeOxygenAtom().
hasOzone
constexpr std::array<std::string_view, 18> PartitionFunctions::hasOzone constexpr
Initial value:
{
"666",
"667",
"668",
"676",
"678",
"686",
"767",
"768",
"776",
"777",
"778",
"786",
"787",
"868",
"878",
"886",
"887",
"888",
}
Definition at line 20966 of file auto_partfun.h.
Referenced by computeOzone().
hasparticles
constexpr std::array<std::string_view, 0> PartitionFunctions::hasparticles constexpr
Initial value:
{
}
Definition at line 178668 of file auto_partfun.h.
Referenced by computeparticles().
hasPerfluorobutane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluorobutane constexpr
Initial value:
{
}
Definition at line 169167 of file auto_partfun.h.
Referenced by computePerfluorobutane().
hasPerfluorocyclobutane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluorocyclobutane constexpr
Initial value:
{
}
Definition at line 169215 of file auto_partfun.h.
Referenced by computePerfluorocyclobutane().
hasPerfluorohexane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluorohexane constexpr
Initial value:
{
}
Definition at line 169191 of file auto_partfun.h.
Referenced by computePerfluorohexane().
hasPerfluorooctane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluorooctane constexpr
Initial value:
{
}
Definition at line 169203 of file auto_partfun.h.
Referenced by computePerfluorooctane().
hasPerfluoropentane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluoropentane constexpr
Initial value:
{
}
Definition at line 169179 of file auto_partfun.h.
Referenced by computePerfluoropentane().
hasPerfluoropropane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasPerfluoropropane constexpr
Initial value:
{
}
Definition at line 169155 of file auto_partfun.h.
Referenced by computePerfluoropropane().
hasPhosgene
constexpr std::array<std::string_view, 2> PartitionFunctions::hasPhosgene constexpr
Initial value:
{
"2655",
"2657",
}
Definition at line 161050 of file auto_partfun.h.
Referenced by computePhosgene().
hasPhosphine
constexpr std::array<std::string_view, 1> PartitionFunctions::hasPhosphine constexpr
Initial value:
{
"1111",
}
Definition at line 116400 of file auto_partfun.h.
Referenced by computePhosphine().
hasPropane
constexpr std::array<std::string_view, 1> PartitionFunctions::hasPropane constexpr
Initial value:
{
"21",
}
Definition at line 158243 of file auto_partfun.h.
Referenced by computePropane().
hasrain
constexpr std::array<std::string_view, 0> PartitionFunctions::hasrain constexpr
Initial value:
{
}
Definition at line 178644 of file auto_partfun.h.
Referenced by computerain().
hasRightHeavyFormicAcid
constexpr std::array<std::string_view, 1> PartitionFunctions::hasRightHeavyFormicAcid constexpr
Initial value:
{
"266",
}
Definition at line 123627 of file auto_partfun.h.
Referenced by computeRightHeavyFormicAcid().
hasSulfurDioxide
constexpr std::array<std::string_view, 4> PartitionFunctions::hasSulfurDioxide constexpr
Initial value:
{
"626",
"628",
"636",
"646",
}
Definition at line 60063 of file auto_partfun.h.
Referenced by computeSulfurDioxide().
hasSulfurHexafluoride
constexpr std::array<std::string_view, 1> PartitionFunctions::hasSulfurHexafluoride constexpr
Initial value:
{
"29",
}
Definition at line 118739 of file auto_partfun.h.
Referenced by computeSulfurHexafluoride().
hasSulfuricAcid
constexpr std::array<std::string_view, 1> PartitionFunctions::hasSulfuricAcid constexpr
Initial value:
{
"126",
}
Definition at line 127761 of file auto_partfun.h.
Referenced by computeSulfuricAcid().
hasSulfurMonoxide
constexpr std::array<std::string_view, 3> PartitionFunctions::hasSulfurMonoxide constexpr
Initial value:
{
"26",
"28",
"46",
}
Definition at line 155216 of file auto_partfun.h.
Referenced by computeSulfurMonoxide().
hasSulfurTrioxide
constexpr std::array<std::string_view, 1> PartitionFunctions::hasSulfurTrioxide constexpr
Initial value:
{
"26",
}
Definition at line 158311 of file auto_partfun.h.
Referenced by computeSulfurTrioxide().
hasSulfurylFluoride
constexpr std::array<std::string_view, 0> PartitionFunctions::hasSulfurylFluoride constexpr
Initial value:
{
}
Definition at line 170520 of file auto_partfun.h.
Referenced by computeSulfurylFluoride().
hasTrichloroethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasTrichloroethane constexpr
Initial value:
{
}
Definition at line 169311 of file auto_partfun.h.
Referenced by computeTrichloroethane().
hasTrichloromethane
constexpr std::array<std::string_view, 0> PartitionFunctions::hasTrichloromethane constexpr
Initial value:
{
}
Definition at line 169323 of file auto_partfun.h.
Referenced by computeTrichloromethane().
hasVeryHeavyFormaldehyde
constexpr std::array<std::string_view, 1> PartitionFunctions::hasVeryHeavyFormaldehyde constexpr
Initial value:
{
"26",
}
Definition at line 97509 of file auto_partfun.h.
Referenced by computeVeryHeavyFormaldehyde().
hasWater
constexpr std::array<std::string_view, 9> PartitionFunctions::hasWater constexpr
Initial value:
{
"161",
"162",
"171",
"172",
"181",
"182",
"262",
"272",
"282",
}
Definition at line 32 of file auto_partfun.h.
Referenced by computeWater().