ARTS: Raw::Mask Namespace Reference
Raw::Mask Namespace Reference
Functions
std::vector< bool > out_of_bounds (const Vector &x, const Numeric xmin, const Numeric xmax)
Masks values that are out of bounds in x.
VectorView mask (VectorView x, const std::vector< bool > &masking)
Masks all true entries of masking in x by turning them into NaN.
Function Documentation
mask()
VectorView Raw::Mask::mask (VectorView x, const std::vector< bool > & masking)
Masks all true entries of masking in x by turning them into NaN.
Parameters
[in,out] x A Vector to mask
[in] masking The mask
Returns
x masked (note, x is masked in-place anyways)
Definition at line 411 of file raw.cc.
References N, and ARTS::Var::x().
Referenced by out_of_bounds(), and yMaskOutsideMedianRange().
out_of_bounds()
std::vector< bool > Raw::Mask::out_of_bounds (const Vector & x, const Numeric xmin, const Numeric xmax)
Masks values that are out of bounds in x.
Acceptable values are xmin <= x[i] <= xmax
All other i are marked as masked (true)
Parameters
[in] x A vector to mask
[in] xmin The minimum acceptable value of x
[in] xmax The maximum acceptable value of x
Returns
A mask (true is masked, false is unmasked)
Definition at line 404 of file raw.cc.
References isnormal_or_zero(), mask(), and ARTS::Var::x().
Referenced by yMaskOutsideMedianRange().