ARTS: ARTS::Continua Namespace Reference
ARTS::Continua Namespace Reference
Functions
Workspace & init (Workspace &ws)
Workspace & addH2OPWR98 (Workspace &ws)
Workspace & addO2PWR98 (Workspace &ws)
Function Documentation
addH2OPWR98()
Workspace& ARTS::Continua::addH2OPWR98 (Workspace & ws)
Definition at line 147 of file test_cpp_api.cc.
References ARTS::Method::abs_cont_descriptionAppend().
Referenced by main().
addO2PWR98()
Workspace& ARTS::Continua::addO2PWR98 (Workspace & ws)
Definition at line 149 of file test_cpp_api.cc.
References ARTS::Method::abs_cont_descriptionAppend().
Referenced by main().
init()
Workspace& ARTS::Continua::init (Workspace & ws)
Definition at line 145 of file test_cpp_api.cc.
References ARTS::Method::abs_cont_descriptionInit().
Referenced by gzstreambase::gzstreambase(), main(), and Vector::Vector().