ARTS: ARTS Namespace Reference
ARTS Namespace Reference
Namespaces
Agenda
AgendaDefine
AgendaExecute
AgendaMethod
Continua
Group
Method
Var
Typedefs
using Workspace = Workspace
Functions
Workspace init (std::size_t screen=0, std::size_t file=0, std::size_t agenda=0, const Group::String &basename="arts", int numthreads=0)
Typedef Documentation
Workspace
using ARTS::Workspace = typedef Workspace
Definition at line 24 of file autoarts.h.
Function Documentation
init()
Workspace ARTS::init (std::size_t screen = 0, std::size_t file = 0, std::size_t agenda = 0, const Group::String & basename = "arts", int numthreads = 0) inline
Create a Workspace and set its main verbosity
Parameters
[in] screen Screen verbosity
[in] file File verbosity
[in] agenda Agenda verbosity
[in] basename Default basename for output variables
[in] numthreads OpenMP thread count (defaults to max if invalid count)
Returns
Workspace a full ARTS Workspace
Definition at line 148081 of file autoarts.h.
References arts_omp_get_max_threads(), Workspace::context, define_agenda_data(), define_agenda_map(), define_md_data_raw(), define_md_map(), define_species_data(), define_species_map(), Workspace::define_wsv_data(), define_wsv_group_names(), Workspace::define_wsv_map(), expand_md_data_raw_to_md_data(), WorkspaceMemoryHandler::initialize(), Workspace::initialize(), out_basename, ARTS::Var::Verbosity::value(), ARTS::Var::verbosity(), and global_data::workspace_memory_handler.
Referenced by main().