ARTS: LineShape Namespace Reference
LineShape Namespace Reference
Computations of line shape derived parameters.
Namespaces
LegacyLineFunctionData
Legacy dealing with reading old LineFunctionData.
LegacyLineMixingData
Legacy dealing with reading old LineMixingData.
LegacyPressureBroadeningData
Legacy dealing with reading old PressureBroadeningData.
Classes
struct FullNonLocalThermodynamicEquilibriumInitialization
struct VibrationalTemperaturesNonLocalThermodynamicEquilibriumInitializer
struct CutoffRange
Struct to keep the cutoff limited range values.
struct SparseLimitRange
Struct to keep the cutoff limited range values and the sparse limits.
struct Derivatives
Data struct for keeping derivative keys and values.
struct ComputeValues
struct Noshape
struct Doppler
struct Lorentz
struct Voigt
struct SpeedDependentVoigt
struct HartmannTran
struct Nonorm
struct VanVleckHuber
struct VanVleckWeisskopf
struct RosenkranzQuadratic
struct Nostrength
struct LocalThermodynamicEquilibrium
struct FullNonLocalThermodynamicEquilibrium
struct VibrationalTemperaturesNonLocalThermodynamicEquilibrium
struct ComputeData
struct ModelParameters
Coefficients and temperature model for SingleSpeciesModel.
class SingleSpeciesModel
Compute the line shape parameters for a single broadening species.
class Model
Main line shape model class.
Typedefs
typedef Array< Derivatives > ArrayOfDerivatives
Helper to keep function signature clean.
typedef std::variant< Noshape, Doppler, Lorentz, Voigt, SpeedDependentVoigt, HartmannTran > Calculator
typedef std::variant< Nonorm, VanVleckHuber, VanVleckWeisskopf, RosenkranzQuadratic > Normalizer
typedef std::variant< Nostrength, LocalThermodynamicEquilibrium, FullNonLocalThermodynamicEquilibrium, VibrationalTemperaturesNonLocalThermodynamicEquilibrium > IntensityCalculator
Functions
constexpr Numeric abs_squared (Complex z) noexcept
Calculator line_shape_selection (const Type type, const Numeric F0, const Output &X, const Numeric DC, const Numeric DZ)
Calculator mirror_line_shape_selection (const Absorption::MirroringType mirror, const Type type, const Numeric F0, const Output &X, const Numeric DC, const Numeric DZ)
Normalizer normalizer_selection (const Absorption::NormalizationType type, const Numeric F0, const Numeric T)
IntensityCalculator linestrength_selection (const Numeric T, const Numeric QT, const Numeric QT0, const Numeric dQTdT, const Numeric r, const Numeric drdSELFVMR, const Numeric drdT, const EnergyLevelMap &nlte, const Absorption::Lines &band, const Index line_index)
CutoffRange limited_range (const Numeric fl, const Numeric fu, const Vector &f_grid) ARTS_NOEXCEPT
Gets the start and size of a range such that.
SparseLimitRange linear_sparse_limited_range (const Numeric flc, const Numeric fuc, const Numeric fls, const Numeric fus, const Vector &f_grid, const Vector &sparse_f_grid) ARTS_NOEXCEPT
SparseLimitRange quad_sparse_limited_range (const Numeric flc, const Numeric fuc, const Numeric fls, const Numeric fus, const Vector &f_grid, const Vector &sparse_f_grid) ARTS_NOEXCEPT
void frequency_loop (ComputeValues &com, Calculator &ls, Calculator &ls_mirr, Normalizer &ls_norm, const IntensityCalculator &ls_str, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfDerivatives &derivs, const Complex LM, const Numeric &T, const Numeric &dfdH, const Numeric &Sz, const Index self_species) ARTS_NOEXCEPT
Frequency loop of the line shape call.
void cutoff_loop_sparse_linear (ComputeData &com, ComputeData &sparse_com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfDerivatives &derivs, const Output X, const Numeric &T, const Numeric &H, const Numeric &sparse_lim, const Numeric &f_mean, const Numeric &DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization) ARTS_NOEXCEPT
Cutoff considerations of the line shape.
void cutoff_loop_sparse_triple (ComputeData &com, ComputeData &sparse_com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfDerivatives &derivs, const Output X, const Numeric &T, const Numeric &H, const Numeric &sparse_lim, const Numeric &f_mean, const Numeric &DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization) ARTS_NOEXCEPT
void cutoff_loop (ComputeData &com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfDerivatives &derivs, const Output X, const Numeric &T, const Numeric &H, const Numeric &f_mean, const Numeric &DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization) ARTS_NOEXCEPT
Cutoff considerations of the line shape.
void line_loop (ComputeData &com, ComputeData &sparse_com, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities, const EnergyLevelMap &nlte, const Vector &vmrs, const Numeric &P, const Numeric &T, const Numeric &H, const Numeric &sparse_lim, const Numeric QT, const Numeric QT0, const Numeric dQTdT, const Numeric r, const Numeric drdSELFVMR, const Numeric drdT, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization, const Options::LblSpeedup speedup_type) ARTS_NOEXCEPT
Loop all the lines of the band.
void compute (ComputeData &com, ComputeData &sparse_com, const AbsorptionLines &band, const ArrayOfRetrievalQuantity &jacobian_quantities, const EnergyLevelMap &nlte, const SpeciesAuxData::AuxType &partfun_type, const ArrayOfGriddedField1 &partfun_data, const Vector &vmrs, const Numeric &self_vmr, const Numeric &isot_ratio, const Numeric &P, const Numeric &T, const Numeric &H, const Numeric &sparse_lim, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization, const Options::LblSpeedup speedup_type) ARTS_NOEXCEPT
Compute the line shape in its entirety.
Index sparse_f_grid_red (const Vector &f_grid, const Numeric &sparse_df) noexcept
Vector linear_sparse_f_grid (const Vector &f_grid, const Numeric &sparse_df) ARTS_NOEXCEPT
bool good_linear_sparse_f_grid (const Vector &f_grid_dense, const Vector &f_grid_sparse) noexcept
Vector triple_sparse_f_grid (const Vector &f_grid, const Numeric &sparse_df) noexcept
Numeric & SingleModelParameter (ModelParameters &mp, const String &type)
Get a coefficient from ModelParameters by name.
std::ostream & operator<< (std::ostream &os, const ModelParameters &mp)
Output operator for ModelParameters.
std::istream & operator>> (std::istream &is, ModelParameters &mp)
Input operator for ModelParameters.
std::ostream & operator<< (std::ostream &os, const SingleSpeciesModel &ssm)
Output operator for SingleSpeciesModel.
std::istream & operator>> (std::istream &is, SingleSpeciesModel &ssm)
Input operator for SingleSpeciesModel.
std::ostream & operator<< (std::ostream &os, Output x)
Type of line shape to compute.
Model hitran_model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf)
Model lblrtm_model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf, std::array< Numeric, 12 > aer_interp)
ENUMCLASS (TemperatureModel, char, None, T0, T1, T2, T3, T4, T5, LM_AER, DPL) ENUMCLASS(Variable
Temperature models.
String modelparameters2metadata (const ModelParameters mp, const Numeric T0)
constexpr bool modelparameterEmpty (const ModelParameters mp) noexcept
constexpr Numeric modelparameterFirstExponent (const ModelParameters mp) noexcept
constexpr Output mirroredOutput (Output x) noexcept
Output to be used by mirroring calls.
constexpr Output negativeOutput (Output x) noexcept
Output turned negative.
constexpr Output si2cgs (Output x) noexcept
Output turned from SI to CGS units.
constexpr Output differenceOutput (Output y, Output x) noexcept
Diff of two output.
Vector vmrs (const ConstVectorView &atmospheric_vmrs, const ArrayOfArrayOfSpeciesTag &atmospheric_species, const QuantumIdentifier &self, const ArrayOfSpeciesTag &lineshape_species, bool self_in_list, bool bath_in_list, Type type)
Returns a VMR vector for this model's main calculations.
Vector mass (const ConstVectorView &atmospheric_vmrs, const ArrayOfArrayOfSpeciesTag &atmospheric_species, const QuantumIdentifier &self, const ArrayOfSpeciesTag &lineshape_species, bool self_in_list, bool bath_in_list)
Returns a mass vector for this model's main calculations.
std::ostream & operator<< (std::ostream &, const Model &)
std::istream & operator>> (std::istream &, Model &)
String ModelShape2MetaData (const Model &m)
Model MetaData2ModelShape (const String &s)
ArrayOfString ModelMetaDataArray (const Model &m, const bool self, const bool bath, const ArrayOfSpeciesTag &sts, const Numeric T0)
std::istream & from_artscat4 (std::istream &is, Type &type, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species, const QuantumIdentifier &qid)
std::istream & from_linefunctiondata (std::istream &data, Type &type, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species)
std::istream & from_linemixingdata (std::istream &data, Model &lsc)
Legacy reading of old deprecated LineMixingData class.
std::istream & from_pressurebroadeningdata (std::istream &data, LineShape::Type &type, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species, const QuantumIdentifier &qid)
Legacy reading of old deprecated PressureBroadeningData class.
Variables
char
G0
D0
G2
D2
FVC
ETA
Y
G
constexpr Index nmaxTempModelParams = 4
Current max number of coefficients.
constexpr Index nVars = Index(Variable::FINAL)
Current max number of line shape variables.
Detailed Description
Computations of line shape derived parameters.
Defines many classes and IO routines for line shape parameters to comply with everything from no line mixing Doppler to coefficient-based line mixing Hartman-Tran profiles
Typedef Documentation
ArrayOfDerivatives
typedef Array<Derivatives> LineShape::ArrayOfDerivatives
Helper to keep function signature clean.
Definition at line 2240 of file lineshape.cc.
Calculator
typedef std::variant<Noshape, Doppler, Lorentz, Voigt, SpeedDependentVoigt, HartmannTran> LineShape::Calculator
Definition at line 511 of file lineshape.h.
IntensityCalculator
typedef std::variant<Nostrength, LocalThermodynamicEquilibrium, FullNonLocalThermodynamicEquilibrium, VibrationalTemperaturesNonLocalThermodynamicEquilibrium> LineShape::IntensityCalculator
Definition at line 520 of file lineshape.h.
Normalizer
typedef std::variant<Nonorm, VanVleckHuber, VanVleckWeisskopf, RosenkranzQuadratic> LineShape::Normalizer
Definition at line 515 of file lineshape.h.
Function Documentation
abs_squared()
constexpr Numeric LineShape::abs_squared (Complex z) constexpr noexcept
Definition at line 408 of file lineshape.cc.
References Constant::pow2().
Referenced by LineShape::SpeedDependentVoigt::init(), and LineShape::HartmannTran::init().
compute()
void LineShape::compute (ComputeData & com, ComputeData & sparse_com, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities, const EnergyLevelMap & nlte, const SpeciesAuxData::AuxType & partfun_type, const ArrayOfGriddedField1 & partfun_data, const Vector & vmrs, const Numeric & self_vmr, const Numeric & isot_ratio, const Numeric & P, const Numeric & T, const Numeric & H, const Numeric & sparse_lim, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization, const Options::LblSpeedup speedup_type)
Compute the line shape in its entirety.
For a single line the line shape is
\[ F_i = S_{z_i} S_{n_i} S_i LM_i F_i(\cdots), \]
where \(S_{z_i} \) is the Zeeman scaling, \(S_{n_i} \) is the normalization scaling, \(S_i \) is the line strength scaling, \(LM_i \) is the line mixing scaling, and \(F_i(\cdots)\) is the shape.
and the derivatives are
\[ \frac{\partial F_l}{\partial t} = S_{z_i} \left(\frac{\partial S_{n_i}}{\partial t} S_i LM_i F_i(\cdots) + S_{n_i} \frac{\partial S_i}{\partial t} LM_i F_i(\cdots) + S_{n_i} S_i \frac{\partial LM_i}{\partial t} F_i(\cdots) + S_{n_i} S_i LM_i \frac{\partial F_i(\cdots)}{\partial t} \right), \]
where \(t \) is some arbitrary variable.
Definition at line 2967 of file lineshape.cc.
References ARTS_ASSERT, dnumber_density_dt(), dsingle_partition_function_dT(), ARTS::Species::H, ARTS::Var::jacobian_quantities(), line_loop(), number_density(), Absorption::relaxationtype_relmat(), single_partition_function(), and vmrs().
Referenced by propmat_clearskyAddLines(), test_ls(), test_sparse(), and zeeman_on_the_fly().
cutoff_loop()
void LineShape::cutoff_loop (ComputeData & com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfDerivatives & derivs, const Output X, const Numeric & T, const Numeric & H, const Numeric & f_mean, const Numeric & DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization)
Cutoff considerations of the line shape.
This function takes care of setting up cutoff and line shape considerations for the frequency loop function it wraps. Internally, the cutoff is calculated from the band information and a view of the correct data is sent on.
The Zeeman effect is also considered internally if applicable (or ignored otherwise)
This function is not possible to run on multiple cores. Such parallelisms must happen at a much higher level.
Parameters
[in,out] F The cross-section. \(F \)
[in,out] dF The cross-section's derivatives. \(\partial F / \partial x \)
[in,out] N The cross-section ratio of the NLTE source. \(N \)
[in,out] dN The cross-section ratio of the NLTE source's derivatives. \(\partial N / \partial x \)
[in] f_grid The frequency grid. \(\left[ f_0, \cdots, f_n \right] \)
[in] band The absorption band
[in] jacobian_quantities As WSV
[in] T The atmospheric temperature
[in] do_nlte Flag for whether or not NLTE will be computed
[in] H The magnetic field magnitude
[in] do_zeeman Flag for whether this is part of some Zeeman calculations
[in] zeeman_polarization The type of Zeeman polarization to consider (if any)
[in] f_mean The mean frequency of the absorption band
[in] DC The Doppler broadening constant of the band
[in] i The line index
[in] X The line shape model parameters of the atmosphere
[in] LM The line mixing scaling. \(S_{lm} \)
[in] ls_str The line strength calculator. \(S_i \)
[in] ls_norm The normalization calculator. \(S_n \)
[in] derivs A list of pre-computed derivative values and keys
Definition at line 2767 of file lineshape.cc.
References frequency_loop(), ARTS::Species::H, ARTS::Var::jacobian_quantities(), limited_range(), line_shape_selection(), mirror_line_shape_selection(), and Options::None.
Referenced by line_loop().
cutoff_loop_sparse_linear()
void LineShape::cutoff_loop_sparse_linear (ComputeData & com, ComputeData & sparse_com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfDerivatives & derivs, const Output X, const Numeric & T, const Numeric & H, const Numeric & sparse_lim, const Numeric & f_mean, const Numeric & DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization)
Cutoff considerations of the line shape.
This function takes care of setting up cutoff and line shape considerations for the frequency loop function it wraps. Internally, the cutoff is calculated from the band information and a view of the correct data is sent on.
The Zeeman effect is also considered internally if applicable (or ignored otherwise)
This function is not possible to run on multiple cores. Such parallelisms must happen at a much higher level.
Parameters
[in,out] F The cross-section. \(F \)
[in,out] dF The cross-section's derivatives. \(\partial F / \partial x \)
[in,out] N The cross-section ratio of the NLTE source. \(N \)
[in,out] dN The cross-section ratio of the NLTE source's derivatives. \(\partial N / \partial x \)
[in] f_grid The frequency grid. \(\left[ f_0, \cdots, f_n \right] \)
[in] band The absorption band
[in] jacobian_quantities As WSV
[in] T The atmospheric temperature
[in] do_nlte Flag for whether or not NLTE will be computed
[in] H The magnetic field magnitude
[in] do_zeeman Flag for whether this is part of some Zeeman calculations
[in] zeeman_polarization The type of Zeeman polarization to consider (if any)
[in] f_mean The mean frequency of the absorption band
[in] DC The Doppler broadening constant of the band
[in] i The line index
[in] X The line shape model parameters of the atmosphere
[in] LM The line mixing scaling. \(S_{lm} \)
[in] ls_str The line strength calculator. \(S_i \)
[in] ls_norm The normalization calculator. \(S_n \)
[in] derivs A list of pre-computed derivative values and keys
Definition at line 2557 of file lineshape.cc.
References frequency_loop(), ARTS::Species::H, ARTS::Var::jacobian_quantities(), line_shape_selection(), linear_sparse_limited_range(), mirror_line_shape_selection(), and Options::None.
Referenced by line_loop().
cutoff_loop_sparse_triple()
void LineShape::cutoff_loop_sparse_triple (ComputeData & com, ComputeData & sparse_com, Normalizer ls_norm, const IntensityCalculator ls_str, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfDerivatives & derivs, const Output X, const Numeric & T, const Numeric & H, const Numeric & sparse_lim, const Numeric & f_mean, const Numeric & DC, const Index i, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization)
Definition at line 2643 of file lineshape.cc.
References frequency_loop(), ARTS::Species::H, ARTS::Var::jacobian_quantities(), line_shape_selection(), mirror_line_shape_selection(), Options::None, and quad_sparse_limited_range().
Referenced by line_loop().
differenceOutput()
constexpr Output LineShape::differenceOutput (Output y, Output x) constexpr noexcept
Diff of two output.
Definition at line 555 of file lineshapemodel.h.
References ARTS::Var::x(), and ARTS::Var::y().
ENUMCLASS()
LineShape::ENUMCLASS (TemperatureModel , char , None , T0 , T1 , T2 , T3 , T4 , T5 , LM_AER , DPL)
Temperature models.
Each input here should correspond to a method of how to compute the variable given the coefficients and Interpolation data available to SingleSpeciesModel
FIXME: The python API breaks if this is a char type even though it can be???? List of possible shape variables
Should correspond to strings in AllLineShapeVars()
frequency_loop()
void LineShape::frequency_loop (ComputeValues & com, Calculator & ls, Calculator & ls_mirr, Normalizer & ls_norm, const IntensityCalculator & ls_str, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfDerivatives & derivs, const Complex LM, const Numeric & T, const Numeric & dfdH, const Numeric & Sz, const Index self_species)
Frequency loop of the line shape call.
This simply adds to the four output vectors/matrices for each frequency grid.
The equation solved is the inner part of
\[ F(f) = \sum_i S_{lm} S_n(f) S_z S_i \left[F_i\left(f\right) + F^M_i\left(f\right)\right], \]
where \(f \) is the frequency, \(i \) is the line index, \(S_{lm} \) is the line mixing scaling, \(S_n(f) \) is the line normalization at \(f \), \(S_z \) is the Zeeman line strength scaling, \(S_i \) is the line strength, \(F_i\left(f\right) \) is the line shape at \(f \), and \(F^M_i\left(f\right) \) is the mirrored line shape at \(f \).
Each of \(S_n \), \(S_i \), \(F_i\left(f\right) \), and \(F^M_i\left(f\right) \) are setup to work as functional classes. They each define a set of possible derivatives and these possible derivatives are used to setup the chain rules required to computed \(\partial F(f) / \partial x \). Also, \(S_i \) is setup so to return the NLTE ratios required for computing
\[ N(f) = \sum_i S_{lm} S_n(f) S_z N_i \left[F_i\left(f\right) + F^M_i\left(f\right)\right], \]
with the same rules applied to \(\partial N(f) / \partial x \) as on \(\partial F(f) / \partial x \).
Note that even though not directly implied by this notation, most of the variables used in these two equations depends on some line parameters. Also note that the idea is to add full cross-section at once so as to limit the number of allocations in nested runs, so the calculations must happen in the inner most loop.
This function is not possible to run on multiple cores. Such parallelisms must happen at a much higher level.
Parameters
[in] jacobian_quantities As WSV
[in] T The atmospheric temperature
[in] do_nlte Flag for whether or not NLTE will be computed
[in] LM The line mixing scaling. \(S_{lm} \)
[in] ls_str The line strength calculator. \(S_i \)
[in,out] ls_norm The normalization calculator. \(S_n \)
[in] derivs A list of pre-computed derivative values and keys
[in,out] F The cross-section. \(F \)
[in,out] dF The cross-section's derivatives. \(\partial F / \partial x \)
[in,out] N The cross-section ratio of the NLTE source. \(N \)
[in,out] dN The cross-section ratio of the NLTE source's derivatives. \(\partial N / \partial x \)
[in] f_grid The frequency grid. \(\left[ f_0, \cdots, f_n \right] \)
[in] dfdH The derivative of the change of frequency w.r.t. magnetic field strength
[in] Sz The relative Zeeman strength. \(S_z \)
[in] ls The line shape calculator. \(F_i \)
[in] ls_mirr The mirrored line shape calculator. \(F^M_i \)
Definition at line 2360 of file lineshape.cc.
References conj(), d, D0, D2, ETA, FVC, G0, G2, InternalDerivatives, InternalDerivativesG, InternalDerivativesY, is_magnetic_parameter(), is_wind_parameter(), ARTS::Var::jacobian_quantities(), mirroredOutput(), propmattype(), Jacobian::Temperature, and ARTS::Var::ArrayOfRetrievalQuantity::value().
Referenced by cutoff_loop(), cutoff_loop_sparse_linear(), and cutoff_loop_sparse_triple().
from_artscat4()
std::istream & LineShape::from_artscat4 (std::istream & is, Type & type, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species, const QuantumIdentifier & qid)
Definition at line 81 of file lineshapemodel.cc.
References LineShape::Model::mdata, and v.
Referenced by Absorption::ReadFromArtscat4Stream().
from_linefunctiondata()
std::istream & LineShape::from_linefunctiondata (std::istream & data, Type & type, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species)
Definition at line 141 of file lineshapemodel.cc.
References ARTS_USER_ERROR_IF, check_enum_error(), data, LineShape::LegacyLineFunctionData::linemixingtag2variablesvector(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), and LineShape::Model::mdata.
Referenced by Absorption::ReadFromArtscat5Stream().
from_linemixingdata()
std::istream & LineShape::from_linemixingdata (std::istream & data, LineShape::Model & lsc)
Legacy reading of old deprecated LineMixingData class.
Definition at line 281 of file lineshapemodel.cc.
References data, LineShape::LegacyLineMixingData::string2typelm(), Hitran::type, LineShape::LegacyLineMixingData::typelm2nelem(), LineShape::LegacyLineMixingData::vector2modellm(), and ARTS::Var::x().
Referenced by Absorption::ReadFromArtscat5Stream().
from_pressurebroadeningdata()
std::istream & LineShape::from_pressurebroadeningdata (std::istream & data, LineShape::Type & type, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species, const QuantumIdentifier & qid)
Legacy reading of old deprecated PressureBroadeningData class.
Definition at line 250 of file lineshapemodel.cc.
References data, LineShape::LegacyPressureBroadeningData::self_listed(), LineShape::LegacyPressureBroadeningData::string2typepb(), Hitran::type, LineShape::LegacyPressureBroadeningData::typepb2nelem(), LineShape::LegacyPressureBroadeningData::vector2modelpb(), and ARTS::Var::x().
Referenced by Absorption::ReadFromArtscat5Stream().
good_linear_sparse_f_grid()
bool LineShape::good_linear_sparse_f_grid (const Vector & f_grid_dense, const Vector & f_grid_sparse) noexcept
Definition at line 3050 of file lineshape.cc.
Referenced by sparse_f_gridFromFrequencyGrid().
hitran_model()
Model LineShape::hitran_model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf)
Definition at line 1030 of file lineshapemodel.cc.
References LineShape::Model::Data().
lblrtm_model()
Model LineShape::lblrtm_model (Numeric sgam, Numeric nself, Numeric agam, Numeric nair, Numeric psf, std::array< Numeric, 12 > aer_interp)
Definition at line 1046 of file lineshapemodel.cc.
References LineShape::Model::Data().
limited_range()
CutoffRange LineShape::limited_range (const Numeric fl, const Numeric fu, const Vector & f_grid)
Gets the start and size of a range such that.
\[ fl \leq f_grid[i] \leq fu \]
for i such that all fl <= f_grid[Range(out.first, out.second, 1)] <= fu
Parameters
[in] fl Lower frequency limit
[in] fu Upper frequency limit
[in] f_grid As WSV, must be sorted
Returns
out so that the Range above can be formed
Definition at line 2094 of file lineshape.cc.
References ARTS_ASSERT, and ARTS::Var::f_grid().
Referenced by cutoff_loop().
line_loop()
void LineShape::line_loop (ComputeData & com, ComputeData & sparse_com, const AbsorptionLines & band, const ArrayOfRetrievalQuantity & jacobian_quantities, const EnergyLevelMap & nlte, const Vector & vmrs, const Numeric & P, const Numeric & T, const Numeric & H, const Numeric & sparse_lim, const Numeric QT, const Numeric QT0, const Numeric dQTdT, const Numeric r, const Numeric drdSELFVMR, const Numeric drdT, const bool do_zeeman, const Zeeman::Polarization zeeman_polarization, const Options::LblSpeedup speedup_type)
Loop all the lines of the band.
This function is not possible to run on multiple cores. Such parallelisms must happen at a much higher level.
Parameters
[in,out] F The cross-section. \(F \)
[in,out] dF The cross-section's derivatives. \(\partial F / \partial x \)
[in,out] N The cross-section ratio of the NLTE source. \(N \)
[in,out] dN The cross-section ratio of the NLTE source's derivatives. \(\partial N / \partial x \)
[in] f_grid The frequency grid. \(\left[ f_0, \cdots, f_n \right] \)
[in] band The absorption band
[in] jacobian_quantities As WSV
[in] nlte A map of NLTE data
[in] vmrs The band volume mixing ratio
[in] isot_ratio The isotopic ratio of the isotopologue
[in] P The atmospheric pressure
[in] T The atmospheric temperature
[in] do_nlte Flag for whether or not NLTE will be computed
[in] H The magnetic field magnitude
[in] do_zeeman Flag for whether this is part of some Zeeman calculations
[in] zeeman_polarization The type of Zeeman polarization to consider (if any)
[in] f_mean The mean frequency of the absorption band
[in] QT The partition function at the temperature
[in] QT0 The partition function at the reference temperature
[in] dQTdT The derivative of the partition function at the temperature wrt temperature
Definition at line 2854 of file lineshape.cc.
References cutoff_loop(), cutoff_loop_sparse_linear(), cutoff_loop_sparse_triple(), D0, D2, ETA, FVC, G, G0, G2, ARTS::Species::H, InternalDerivativesSetup, ARTS::Var::jacobian_quantities(), linestrength_selection(), Options::None, normalizer_selection(), propmattype(), Options::QuadraticIndependent, Jacobian::Temperature, vmrs(), and Y.
Referenced by compute().
line_shape_selection()
Calculator LineShape::line_shape_selection (const Type type, const Numeric F0, const Output & X, const Numeric DC, const Numeric DZ)
Definition at line 1926 of file lineshape.cc.
References F0, and Hitran::type.
Referenced by cutoff_loop(), cutoff_loop_sparse_linear(), cutoff_loop_sparse_triple(), and mirror_line_shape_selection().
linear_sparse_f_grid()
Vector LineShape::linear_sparse_f_grid (const Vector & f_grid, const Numeric & sparse_df)
Definition at line 3027 of file lineshape.cc.
References ARTS::Var::f_grid(), and sparse_f_grid_red().
Referenced by sparse_f_gridFromFrequencyGrid(), and test_sparse().
linear_sparse_limited_range()
SparseLimitRange LineShape::linear_sparse_limited_range (const Numeric flc, const Numeric fuc, const Numeric fls, const Numeric fus, const Vector & f_grid, const Vector & sparse_f_grid)
Definition at line 2109 of file lineshape.cc.
References ARTS_ASSERT, and ARTS::Var::f_grid().
Referenced by cutoff_loop_sparse_linear().
linestrength_selection()
IntensityCalculator LineShape::linestrength_selection (const Numeric T, const Numeric QT, const Numeric QT0, const Numeric dQTdT, const Numeric r, const Numeric drdSELFVMR, const Numeric drdT, const EnergyLevelMap & nlte, const Absorption::Lines & band, const Index line_index)
Definition at line 1985 of file lineshape.cc.
References EnergyLevelMap::get_ratio_params(), EnergyLevelMap::get_vibtemp_params(), Absorption::Lines::Line(), Absorption::Lines::Population(), and Absorption::Lines::T0().
Referenced by line_loop().
mass()
Vector LineShape::mass (const ConstVectorView & atmospheric_vmrs, const ArrayOfArrayOfSpeciesTag & atmospheric_species, const QuantumIdentifier & self, const ArrayOfSpeciesTag & lineshape_species, bool self_in_list, bool bath_in_list)
Returns a mass vector for this model's main calculations.
Sets a vector that matches the mdata size of VMRs based on atmospheric species and VMRs
Only checks the first species in inner atmosphere
Renormalizes the values to unity. If this renormalization is impossible then it throws an error
Parameters
[in] atmospheric_vmrs VMRS in atmosphere
[in] atmospheric_species Species in atmosphere
[in] self An ID of whichever species is self
[in] lineshape_species Species affecting lineshape
[in] self_in_list Affects lineshape by itself?
[in] bath_in_list Affected lineshape by environment?
[in] type The type of line shape
Definition at line 500 of file lineshapemodel.cc.
References ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), Species, and ConstVectorView::sum().
Referenced by Absorption::Lines::BroadeningSpeciesMass(), derive_scat_species_a_and_b(), Linefunctions::DopplerConstant(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::LineMixing::ecs_rosenkranz_approximation(), particle_massesFromMetaData(), particle_massesFromMetaDataSingleCategory(), ScatSpeciesSizeMassInfo(), and xml_read_from_stream().
MetaData2ModelShape()
LineShape::Model LineShape::MetaData2ModelShape (const String & s)
Definition at line 587 of file lineshapemodel.cc.
References ETA, my_basic_string< charT >::nelem(), Options::None, Raw::Average::var(), and ARTS::Var::x().
Referenced by main().
mirror_line_shape_selection()
Calculator LineShape::mirror_line_shape_selection (const Absorption::MirroringType mirror, const Type type, const Numeric F0, const Output & X, const Numeric DC, const Numeric DZ)
Definition at line 1947 of file lineshape.cc.
References F0, line_shape_selection(), mirroredOutput(), Options::None, and Hitran::type.
Referenced by cutoff_loop(), cutoff_loop_sparse_linear(), and cutoff_loop_sparse_triple().
mirroredOutput()
constexpr Output LineShape::mirroredOutput (Output x) constexpr noexcept
Output to be used by mirroring calls.
Definition at line 531 of file lineshapemodel.h.
References ARTS::Var::x().
Referenced by frequency_loop(), mirror_line_shape_selection(), Linefunctions::set_cross_section_of_band(), and Linefunctions::set_lineshape().
ModelMetaDataArray()
ArrayOfString LineShape::ModelMetaDataArray (const Model & m, const bool self, const bool bath, const ArrayOfSpeciesTag & sts, const Numeric T0)
Definition at line 666 of file lineshapemodel.cc.
Referenced by Absorption::Lines::MetaData().
modelparameterEmpty()
constexpr bool LineShape::modelparameterEmpty (const ModelParameters mp) constexpr noexcept
Definition at line 132 of file lineshapemodel.h.
References Options::None.
Referenced by abs_linesSetEmptyBroadeningParametersToEmpty().
modelparameterFirstExponent()
constexpr Numeric LineShape::modelparameterFirstExponent (const ModelParameters mp) constexpr noexcept
Definition at line 158 of file lineshapemodel.h.
References Options::None.
Referenced by Absorption::LineMixing::ecs_rosenkranz_adaptation().
modelparameters2metadata()
String LineShape::modelparameters2metadata (const ModelParameters mp, const Numeric T0)
Definition at line 629 of file lineshapemodel.cc.
ModelShape2MetaData()
String LineShape::ModelShape2MetaData (const Model & m)
Definition at line 566 of file lineshapemodel.cc.
References LineShape::Model::Data(), Raw::Average::var(), and ARTS::Var::x().
Referenced by Absorption::Lines::LineShapeMetaData().
negativeOutput()
constexpr Output LineShape::negativeOutput (Output x) constexpr noexcept
Output turned negative.
Definition at line 536 of file lineshapemodel.h.
References ARTS::Var::x().
normalizer_selection()
Normalizer LineShape::normalizer_selection (const Absorption::NormalizationType type, const Numeric F0, const Numeric T)
Definition at line 1967 of file lineshape.cc.
References F0, Options::None, and Hitran::type.
Referenced by line_loop().
operator<<() [1/4]
std::ostream & LineShape::operator<< (std::ostream & os, const Model & m)
Definition at line 551 of file lineshapemodel.cc.
References data, and LineShape::Model::Data().
operator<<() [2/4]
std::ostream & LineShape::operator<< (std::ostream & os, const ModelParameters & mp)
Output operator for ModelParameters.
Definition at line 725 of file lineshapemodel.cc.
References LineShape::ModelParameters::type, LineShape::ModelParameters::X0, LineShape::ModelParameters::X1, LineShape::ModelParameters::X2, and LineShape::ModelParameters::X3.
operator<<() [3/4]
std::ostream & LineShape::operator<< (std::ostream & os, const SingleSpeciesModel & ssm)
Output operator for SingleSpeciesModel.
Definition at line 973 of file lineshapemodel.cc.
References LineShape::SingleSpeciesModel::Data(), and Options::None.
operator<<() [4/4]
std::ostream& LineShape::operator<< (std::ostream & os, Output x)
Type of line shape to compute.
Turns selected Type into a human readable string
This function takes the input Type and returns it as a string
Parameters
[in] type The Type
Returns
std::string_view of Type Main output of Model Output operator for LineShape::Output
Definition at line 987 of file lineshapemodel.cc.
References ARTS::Var::x().
operator>>() [1/3]
std::istream & LineShape::operator>> (std::istream & is, Model & m)
Definition at line 558 of file lineshapemodel.cc.
References data, and LineShape::Model::Data().
operator>>() [2/3]
std::istream & LineShape::operator>> (std::istream & is, ModelParameters & mp)
Input operator for ModelParameters.
Definition at line 731 of file lineshapemodel.cc.
References LineShape::ModelParameters::type, LineShape::ModelParameters::X0, LineShape::ModelParameters::X1, LineShape::ModelParameters::X2, and LineShape::ModelParameters::X3.
operator>>() [3/3]
std::istream & LineShape::operator>> (std::istream & is, SingleSpeciesModel & ssm)
Input operator for SingleSpeciesModel.
Definition at line 980 of file lineshapemodel.cc.
References LineShape::SingleSpeciesModel::Data(), and Options::None.
quad_sparse_limited_range()
SparseLimitRange LineShape::quad_sparse_limited_range (const Numeric flc, const Numeric fuc, const Numeric fls, const Numeric fus, const Vector & f_grid, const Vector & sparse_f_grid)
Definition at line 2158 of file lineshape.cc.
References ARTS_ASSERT, and ARTS::Var::f_grid().
Referenced by cutoff_loop_sparse_triple().
si2cgs()
constexpr Output LineShape::si2cgs (Output x) constexpr noexcept
Output turned from SI to CGS units.
Definition at line 541 of file lineshapemodel.h.
References Conversion::freq2kaycm(), and ARTS::Var::x().
SingleModelParameter()
Numeric & LineShape::SingleModelParameter (ModelParameters & mp, const String & type)
Get a coefficient from ModelParameters by name.
Will throw a runtime_error if type is bad
Parameters
[in] mp The model parameters
[in] type The coefficient by name
Returns
a reference to the coefficient
Definition at line 708 of file lineshapemodel.cc.
References ARTS_USER_ERROR, Hitran::type, LineShape::ModelParameters::X0, LineShape::ModelParameters::X1, LineShape::ModelParameters::X2, and LineShape::ModelParameters::X3.
sparse_f_grid_red()
Index LineShape::sparse_f_grid_red (const Vector & f_grid, const Numeric & sparse_df) noexcept
Definition at line 3019 of file lineshape.cc.
References abs, and ARTS::Var::f_grid().
Referenced by linear_sparse_f_grid(), and triple_sparse_f_grid().
triple_sparse_f_grid()
Vector LineShape::triple_sparse_f_grid (const Vector & f_grid, const Numeric & sparse_df) noexcept
Definition at line 3064 of file lineshape.cc.
References ARTS::Var::f_grid(), and sparse_f_grid_red().
Referenced by sparse_f_gridFromFrequencyGrid(), and test_sparse().
vmrs()
Vector LineShape::vmrs (const ConstVectorView & atmospheric_vmrs, const ArrayOfArrayOfSpeciesTag & atmospheric_species, const QuantumIdentifier & self, const ArrayOfSpeciesTag & lineshape_species, bool self_in_list, bool bath_in_list, Type type)
Returns a VMR vector for this model's main calculations.
Sets a vector that matches the mdata size of VMRs based on atmospheric species and VMRs
Only checks the first species in inner atmosphere
Renormalizes the values to unity. If this renormalization is impossible then it throws an error
Returns 0s if type is Doppler line shape
Parameters
[in] atmospheric_vmrs VMRS in atmosphere
[in] atmospheric_species Species in atmosphere
[in] self An ID of whichever species is self
[in] lineshape_species Species affecting lineshape
[in] self_in_list Affects lineshape by itself?
[in] bath_in_list Affected lineshape by environment?
[in] type The type of line shape
Definition at line 451 of file lineshapemodel.cc.
References ARTS_USER_ERROR_IF, Array< base >::nelem(), ConstVectorView::nelem(), Species, ConstVectorView::sum(), and Hitran::type.
Referenced by Linefunctions::apply_lineshapemodel_jacobian_scaling(), atm_fields_compactAddConstant(), Absorption::Lines::BroadeningSpeciesVMR(), lm_hitran_2017::compabs(), compute(), lm_hitran_2017::compute(), lm_hitran_2017::convtp(), Absorption::LineMixing::ecs_absorption(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), Absorption::LineMixing::ecs_relaxation_matrix(), line_loop(), propmat_clearskyAddHitranLineMixingLines(), Linefunctions::set_cross_section_of_band(), and test_hitran2017().
Variable Documentation
char
LineShape::char
Definition at line 89 of file lineshapemodel.h.
D0
LineShape::D0
Definition at line 91 of file lineshapemodel.h.
Referenced by LineShape::HartmannTran::dFdETA(), LineShape::HartmannTran::dFdT(), LineShape::HartmannTran::dFdVMR(), Absorption::LineMixing::ENUMCLASS(), frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), lm_hitran_2017::read(), select_derivativeLineShape(), and LineShape::SingleSpeciesModel::Set().
D2
LineShape::D2
Definition at line 93 of file lineshapemodel.h.
Referenced by LineShape::HartmannTran::dFdD0(), LineShape::HartmannTran::dFdD2(), LineShape::HartmannTran::dFdETA(), LineShape::HartmannTran::dFdFVC(), LineShape::HartmannTran::dFdG0(), LineShape::HartmannTran::dFdG2(), LineShape::HartmannTran::dFdH(), LineShape::HartmannTran::dFdT(), LineShape::HartmannTran::dFdVMR(), frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), LineShape::HartmannTran::operator()(), select_derivativeLineShape(), and LineShape::SingleSpeciesModel::Set().
ETA
LineShape::ETA
Definition at line 95 of file lineshapemodel.h.
Referenced by LineShape::HartmannTran::dFdD0(), LineShape::HartmannTran::dFdD2(), LineShape::HartmannTran::dFdETA(), LineShape::HartmannTran::dFdFVC(), LineShape::HartmannTran::dFdG0(), LineShape::HartmannTran::dFdG2(), LineShape::HartmannTran::dFdH(), LineShape::HartmannTran::dFdT(), LineShape::HartmannTran::dFdVMR(), frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), MetaData2ModelShape(), LineShape::HartmannTran::operator()(), select_derivativeLineShape(), and LineShape::SingleSpeciesModel::Set().
FVC
LineShape::FVC
Definition at line 94 of file lineshapemodel.h.
Referenced by frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), select_derivativeLineShape(), and LineShape::SingleSpeciesModel::Set().
G
LineShape::G
Definition at line 97 of file lineshapemodel.h.
Referenced by Minimize::T4::df(), Minimize::DPL::df(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::LineMixing::ecs_rosenkranz_approximation(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::linemixingtag2variablesvector(), Minimize::T4::operator()(), Minimize::DPL::operator()(), Absorption::LineMixing::RosenkranzG(), run_oem_matlab(), select_derivativeLineShape(), LineShape::SingleSpeciesModel::Set(), and Absorption::SingleLine::SetLineMixing2AER().
G0
LineShape::G0
Definition at line 90 of file lineshapemodel.h.
Referenced by LineShape::HartmannTran::dFdETA(), LineShape::HartmannTran::dFdVMR(), frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), MPM85O2AbsModel(), MPM87O2AbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93O2AbsModel(), Rosenkranz_O2_continuum(), select_derivativeLineShape(), LineShape::SingleSpeciesModel::Set(), Standard_O2_continuum(), and TRE05O2AbsModel().
G2
LineShape::G2
Definition at line 92 of file lineshapemodel.h.
Referenced by LineShape::HartmannTran::dFdD0(), LineShape::HartmannTran::dFdD2(), LineShape::HartmannTran::dFdETA(), LineShape::HartmannTran::dFdFVC(), LineShape::HartmannTran::dFdG0(), LineShape::HartmannTran::dFdG2(), LineShape::HartmannTran::dFdH(), LineShape::HartmannTran::dFdVMR(), frequency_loop(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::lineshapetag2variablesvector(), LineShape::HartmannTran::operator()(), select_derivativeLineShape(), and LineShape::SingleSpeciesModel::Set().
nmaxTempModelParams
constexpr Index LineShape::nmaxTempModelParams = 4 constexpr
Current max number of coefficients.
Definition at line 191 of file lineshapemodel.h.
Referenced by abs_linesSetLineShapeModelParametersForMatchingLines().
nVars
constexpr Index LineShape::nVars = Index(Variable::FINAL) constexpr
Current max number of line shape variables.
Definition at line 194 of file lineshapemodel.h.
Referenced by abs_linesSetEmptyBroadeningParametersToEmpty().
Y
LineShape::Y
Definition at line 96 of file lineshapemodel.h.
Referenced by lm_hitran_2017::calcw(), Minimize::curve_fit(), Absorption::LineMixing::ecs_rosenkranz_adaptation(), Absorption::LineMixing::ecs_rosenkranz_approximation(), LineShape::SingleSpeciesModel::Get(), is_lineshape_parameter_X0(), is_lineshape_parameter_X1(), is_lineshape_parameter_X2(), is_lineshape_parameter_X3(), line_loop(), LineShape::LegacyLineFunctionData::linemixingtag2variablesvector(), MatrixMatrixMultiply(), MatrixVectorMultiply(), PWR93O2AbsModel(), Absorption::LineMixing::RosenkranzY(), rtmethods_jacobian_finalisation(), select_derivativeLineShape(), LineShape::SingleSpeciesModel::Set(), Absorption::SingleLine::SetLineMixing2AER(), and SparseSparseMultiply().