ARTS: LineShape::LegacyPressureBroadeningData Namespace Reference
LineShape::LegacyPressureBroadeningData Namespace Reference
Legacy dealing with reading old PressureBroadeningData.
Enumerations
enum class TypePB { PB_NONE , PB_AIR_BROADENING , PB_AIR_AND_WATER_BROADENING , PB_PLANETARY_BROADENING }
Pressure broadening types that used to exist.
Functions
LegacyPressureBroadeningData::TypePB string2typepb (String type)
Pressure broadening types from string.
Index self_listed (const QuantumIdentifier &qid, LegacyPressureBroadeningData::TypePB t)
Pressure broadening if self exist.
constexpr Index typepb2nelem (LegacyPressureBroadeningData::TypePB type)
Pressure broadening types to number of elements.
void vector2modelpb (LineShape::Type &mtype, bool &self, bool &bath, Model &m, ArrayOfSpeciesTag &species, Vector x, LegacyPressureBroadeningData::TypePB type, bool self_in_list)
LineShape::Model from legacy input vector.
Detailed Description
Legacy dealing with reading old PressureBroadeningData.
Enumeration Type Documentation
TypePB
enum LineShape::LegacyPressureBroadeningData::TypePB strong
Pressure broadening types that used to exist.
Enumerator
PB_NONE
PB_AIR_BROADENING
PB_AIR_AND_WATER_BROADENING
PB_PLANETARY_BROADENING
Definition at line 995 of file lineshapemodel.h.
Function Documentation
self_listed()
Index LineShape::LegacyPressureBroadeningData::self_listed (const QuantumIdentifier & qid, LegacyPressureBroadeningData::TypePB t)
Pressure broadening if self exist.
Definition at line 1416 of file lineshapemodel.cc.
References PB_AIR_AND_WATER_BROADENING, PB_PLANETARY_BROADENING, Species, and QuantumIdentifier::Species().
Referenced by LineShape::from_pressurebroadeningdata().
string2typepb()
LegacyPressureBroadeningData::TypePB LineShape::LegacyPressureBroadeningData::string2typepb (String type)
Pressure broadening types from string.
Definition at line 1399 of file lineshapemodel.cc.
References PB_AIR_AND_WATER_BROADENING, PB_AIR_BROADENING, PB_NONE, and PB_PLANETARY_BROADENING.
Referenced by LineShape::from_pressurebroadeningdata().
typepb2nelem()
constexpr Index LineShape::LegacyPressureBroadeningData::typepb2nelem (LegacyPressureBroadeningData::TypePB type) constexpr
Pressure broadening types to number of elements.
Definition at line 1017 of file lineshapemodel.h.
References PB_AIR_AND_WATER_BROADENING, PB_AIR_BROADENING, PB_NONE, and PB_PLANETARY_BROADENING.
Referenced by LineShape::from_pressurebroadeningdata().
vector2modelpb()
void LineShape::LegacyPressureBroadeningData::vector2modelpb (LineShape::Type & mtype, bool & self, bool & bath, Model & m, ArrayOfSpeciesTag & species, Vector x, LegacyPressureBroadeningData::TypePB type, bool self_in_list)
LineShape::Model from legacy input vector.
Definition at line 324 of file lineshapemodel.cc.
References LineShape::Model::Data(), and x.
Referenced by LineShape::from_pressurebroadeningdata().