ARTS: Absorption::LineMixing::Makarov2020etal Namespace Reference
Absorption::LineMixing::Makarov2020etal Namespace Reference
Functions
Numeric reduced_dipole (const Rational Ju, const Rational Jl, const Rational N)
template<bool rescale_pure_rotational = true>
constexpr Numeric erot (const Rational N, const Rational j=-1)
void relaxation_matrix_offdiagonal (MatrixView W, const AbsorptionLines &band, const ArrayOfIndex &sorting, const SpeciesErrorCorrectedSuddenData &rovib_data, const Numeric T)
Function Documentation
erot()
template<bool rescale_pure_rotational = true> constexpr Numeric Absorption::LineMixing::Makarov2020etal::erot (const Rational N, const Rational j = -1) constexpr
Compute the rotational energy of ground-state O2 at N and J
If the template argument evaluates true, the erot<false>(1, 0) energy is removed from the output of erot<false>(N, J).
Parameters
[in] N Main rotational number
[in] j Main rotational number plus spin (if j < 0 then J=N)
Returns
Rotational energy in Joule
Definition at line 271 of file linemixing.cc.
References LineShape::D0, Conversion::mhz2joule(), N, Constant::pow2(), Constant::pow3(), and sqrt().
reduced_dipole()
Numeric Absorption::LineMixing::Makarov2020etal::reduced_dipole (const Rational Ju, const Rational Jl, const Rational N)
Returns the reduced dipole
Parameters
[in] Ju Main rotational number with spin of the upper level
[in] Jl Main rotational number with spin of the lower level
[in] N Main rotational number of both levels
Returns
The reduced dipole
Definition at line 124 of file linemixing.cc.
References iseven(), N, sqrt(), and wigner6j().
Referenced by Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole(), and relaxation_matrix_offdiagonal().
relaxation_matrix_offdiagonal()
void Absorption::LineMixing::Makarov2020etal::relaxation_matrix_offdiagonal (MatrixView W, const AbsorptionLines & band, const ArrayOfIndex & sorting, const SpeciesErrorCorrectedSuddenData & rovib_data, const Numeric T)
Computes the off-diagonal elements of the relaxation matrix following Makarov etal 2020.
Parameters
[in,out] W The imaginary part of the relaxation matrix
[in] T The temperature
[in] band The absorption band
[in] sorting The sorting of the band
[in] mass_self The mass of the self-species
[in] mass_other The mass of the colliding species
Definition at line 321 of file linemixing.cc.
References Absorption::Lines::E0(), Conversion::kelvin2joule(), Absorption::Lines::LowerQuantumNumber(), N, Absorption::Lines::NumLines(), reduced_dipole(), sqrt(), and Absorption::Lines::UpperQuantumNumber().
Referenced by Absorption::LineMixing::single_species_ecs_relaxation_matrix().