ARTS: nonstd Namespace Reference
nonstd Namespace Reference
Functions
template<class T >
constexpr T abs (T x) noexcept
constexpr int isdigit (int ch) noexcept
constexpr bool isnan (double d) noexcept
constexpr bool isnan (long double d) noexcept
constexpr bool isnan (float d) noexcept
Detailed Description
For std functions that are changed somehow
Function Documentation
abs()
template<class T > constexpr T nonstd::abs (T x) constexpr noexcept
abs(x) returns |x| using -x if x < 0 or x otherwise
Reason to re-implement: std::abs(x) is not officially constexpr
Parameters
[in] x Any real value type
Returns
|x|
Definition at line 13 of file nonstd.h.
References ARTS::Var::x().
Referenced by Interpolation::min_cyclic().
isdigit()
constexpr int nonstd::isdigit (int ch) constexpr noexcept
Checks if the given character in 0123456789.
Reason to re-implement: std::isdigit(ch) is not officially constexpr
The int-interface is kept from the standard
Parameters
[in] ch A character
Returns
int from a simple boolean.
Definition at line 24 of file nonstd.h.
Referenced by Species::is_predefined_model(), ArtsParser::parse_intvector_from_string(), ArtsParser::parse_numvector_from_string(), ArtsParser::read_integer(), and ArtsParser::read_numeric().
isnan() [1/3]
constexpr bool nonstd::isnan (double d) constexpr noexcept
Checks if the given value is nan
Reason to re-implement: std::isnan(d) is not officially constexpr
Only the three basic interfaces are implemented
Parameters
[in] d A value
Returns
int from a simple boolean.
Definition at line 39 of file nonstd.h.
References d.
Referenced by _complex_operations_(), Species::all_have_ratio(), Species::IsotopologueRatios::all_isotopes_have_a_value(), cart2poslos(), cart2poslos_plain(), checkIsotopologueRatios(), chk_atm_field(), cloudbox_field_monoIterate(), cloudbox_field_ngAcceleration(), derive_scat_species_a_and_b(), doit_scat_fieldNormalize(), Absorption::LineMixing::ecs_absorption_impl(), Absorption::LineMixing::ecs_absorption_zeeman_impl(), Zeeman::Model::empty(), find_cloudlimits(), iyCalc(), main(), MCGeneral(), Species::mean_mass(), particle_massesFromMetaData(), particle_massesFromMetaDataSingleCategory(), pha_mat_labCalc(), ppathFromRtePos2(), psd_mgd_mass_and_something(), psdModifiedGamma(), psdModifiedGammaMass(), CIARecord::ReadFromCIA(), scat_dataCheck(), oem::ArtsLog< type >::step(), and yCalc_mblock_loop_body().
isnan() [2/3]
constexpr bool nonstd::isnan (float d) constexpr noexcept
Definition at line 41 of file nonstd.h.
References d.
isnan() [3/3]
constexpr bool nonstd::isnan (long double d) constexpr noexcept
Definition at line 40 of file nonstd.h.
References d.