ARTS: Species Namespace Reference
Species Namespace Reference
Classes
struct IsotopeRecord
Struct containing all information needed about one isotope.
struct IsotopologueRatios
Functions
ArrayOfIsotopeRecord isotopologues (Species spec)
String isotopologues_names (Species spec)
String predefined_model_names () noexcept
String update_isot_name (const String &old_name)
Updates the name of the isotopologue based on updates of the isotopologues.
std::pair< ArrayOfString, ArrayOfString > names_of_have_and_havenot_ratio (const Species spec, const IsotopologueRatios &ir) noexcept
constexpr std::array< std::size_t, std::size_t(Species::FINAL)+1 > start_positions () noexcept
template<Species spec>
constexpr std::size_t count_isotopologues () noexcept
template<Species spec>
constexpr std::array< IsotopeRecord, count_isotopologues< spec >)> isotopologues () noexcept
constexpr Index find_species_index (const Species spec, const std::string_view isot) noexcept
constexpr Index find_species_index (const IsotopeRecord ir) noexcept
constexpr Index find_species_index (const std::string_view spec, const std::string_view isot) noexcept
constexpr const IsotopeRecord & select (Species spec, const std::string_view isotname) noexcept
constexpr const IsotopeRecord & select_joker (Species spec) noexcept
constexpr const IsotopeRecord & select_joker (std::string_view spec) noexcept
constexpr bool is_predefined_model (const IsotopeRecord &ir) noexcept
constexpr bool same_or_joker (const IsotopeRecord &ir1, const IsotopeRecord &ir2) noexcept
constexpr IsotopologueRatios isotopologue_ratiosInitFromBuiltin ()
constexpr Numeric mean_mass (Species spec, const IsotopologueRatios &ir) noexcept
constexpr bool all_have_ratio (const Species spec, const IsotopologueRatios &ir) noexcept
ENUMCLASS (TagType, unsigned char, Plain, Zeeman, Predefined, Cia, FreeElectrons, Particles, HitranXsec, NoLines) struct Tag
Variables
constexpr std::string_view Joker = "*"
constexpr std::array Isotopologues
constexpr auto IsotopologuesStart = start_positions()
Function Documentation
all_have_ratio()
constexpr bool Species::all_have_ratio (const Species spec, const IsotopologueRatios & ir) constexpr noexcept
Definition at line 1116 of file isotopologues.h.
References is_predefined_model(), nonstd::isnan(), Isotopologues, IsotopologuesStart, and joker.
count_isotopologues()
template<Species spec> constexpr std::size_t Species::count_isotopologues () constexpr noexcept
Definition at line 611 of file isotopologues.h.
References IsotopologuesStart.
ENUMCLASS()
Species::ENUMCLASS (TagType , unsigned char , Plain , Zeeman , Predefined , Cia , FreeElectrons , Particles , HitranXsec , NoLines)
Molecular species index in Species::Isotopologues
The lower limit line center frequency in Hz.
If this is < 0 it means no lower limit.
The upper line center frequency in Hz.
If this is < 0 it means no upper limit.
Flag for the type
2nd CIA species index.
Contains the second CIA species that should be used for this tag.
CIA dataset index.
A CIA file contains several datasets. This index specifies which one we want.
Definition at line 12 of file species_tags.h.
References ARTS_ASSERT, ARTS_NOEXCEPT, PartitionFunctions::dQdT(), find_species_index(), Isotopologues, operator!=(), operator<<(), operator==(), PartitionFunctions::Q(), Type, and Hitran::type.
find_species_index() [1/3]
constexpr Index Species::find_species_index (const IsotopeRecord ir) constexpr noexcept
Definition at line 638 of file isotopologues.h.
References find_species_index().
find_species_index() [2/3]
constexpr Index Species::find_species_index (const Species spec, const std::string_view isot) constexpr noexcept
Definition at line 627 of file isotopologues.h.
References isot, Isotopologues, and IsotopologuesStart.
Referenced by Quantum::ENUMCLASS(), ENUMCLASS(), find_species_index(), getIndexSpeciesIsotopeRecordFromData(), Species::IsotopologueRatios::operator[](), select(), and xml_read_from_stream().
find_species_index() [3/3]
constexpr Index Species::find_species_index (const std::string_view spec, const std::string_view isot) constexpr noexcept
Definition at line 642 of file isotopologues.h.
References find_species_index(), and isot.
is_predefined_model()
constexpr bool Species::is_predefined_model (const IsotopeRecord & ir) constexpr noexcept
Definition at line 661 of file isotopologues.h.
References nonstd::isdigit().
Referenced by all_have_ratio(), Species::IsotopologueRatios::all_isotopes_have_a_value(), Quantum::ENUMCLASS(), main(), nonexistentPartfun(), and predefined_model_names().
isotopologue_ratiosInitFromBuiltin()
constexpr IsotopologueRatios Species::isotopologue_ratiosInitFromBuiltin () constexpr
Definition at line 712 of file isotopologues.h.
References Hitran::isotopologue_ratios(), and set_isot_val.
Referenced by isotopologue_ratiosInitFromBuiltin(), isotopologue_ratiosInitFromBuiltin_g(), and main().
isotopologues() [1/2]
template<Species spec> constexpr std::array<IsotopeRecord, count_isotopologues<spec>)> Species::isotopologues () constexpr noexcept
Definition at line 616 of file isotopologues.h.
References Isotopologues, and IsotopologuesStart.
isotopologues() [2/2]
Array< IsotopeRecord > Species::isotopologues (Species spec)
Definition at line 6 of file isotopologues.cc.
References ARTS_USER_ERROR, and deal_with_spec.
Referenced by abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), and isotopologues_names().
isotopologues_names()
String Species::isotopologues_names (Species spec)
Definition at line 128 of file isotopologues.cc.
References isotopologues(), and ARTS::Var::x().
mean_mass()
constexpr Numeric Species::mean_mass (Species spec, const IsotopologueRatios & ir) constexpr noexcept
Computes the mean mass for all defined isotopes of the species with mass and isotopologue ratio
\[ m = \frac{ \sum_i r_i m_i }{ \sum_i r_i } \]
Parameters
[in] spec A species
[in] ir All isotopologue ratios
Returns
mean mass
Definition at line 1092 of file isotopologues.h.
References nonstd::isnan(), Isotopologues, IsotopologuesStart, and LineShape::mass().
Referenced by ecs_dataSetSpeciesData(), and LineShape::mass().
names_of_have_and_havenot_ratio()
std::pair< ArrayOfString, ArrayOfString > Species::names_of_have_and_havenot_ratio (const Species spec, const IsotopologueRatios & ir) noexcept
Definition at line 164 of file isotopologues.cc.
predefined_model_names()
String Species::predefined_model_names () noexcept
Definition at line 135 of file isotopologues.cc.
References is_predefined_model(), Isotopologues, and ARTS::Var::x().
same_or_joker()
constexpr bool Species::same_or_joker (const IsotopeRecord & ir1, const IsotopeRecord & ir2) constexpr noexcept
Definition at line 667 of file isotopologues.h.
Referenced by abs_lines_per_speciesCreateFromLines().
select()
constexpr const IsotopeRecord& Species::select (Species spec, const std::string_view isotname) constexpr noexcept
Definition at line 647 of file isotopologues.h.
References find_species_index(), and Isotopologues.
Referenced by init_mpm2020_qid(), and select_joker().
select_joker() [1/2]
constexpr const IsotopeRecord& Species::select_joker (Species spec) constexpr noexcept
Definition at line 651 of file isotopologues.h.
References select().
select_joker() [2/2]
constexpr const IsotopeRecord& Species::select_joker (std::string_view spec) constexpr noexcept
Definition at line 655 of file isotopologues.h.
References select().
start_positions()
constexpr std::array<std::size_t, std::size_t(Species::FINAL)+1> Species::start_positions () constexpr noexcept
Definition at line 591 of file isotopologues.h.
References Isotopologues, and ARTS::Var::x().
update_isot_name()
String Species::update_isot_name (const String & old_name)
Updates the name of the isotopologue based on updates of the isotopologues.
This should only be invoked by versioned code as it is not very efficient.
Parameters
[in] old_name A valid isotopologue name in any version of ARTS
Returns
A name that is valid and equivalent in ARTS today (or a copy of old_name)
Definition at line 145 of file isotopologues.cc.
Referenced by Absorption::ReadFromArtscat3Stream(), Absorption::ReadFromArtscat4Stream(), Absorption::ReadFromArtscat5Stream(), and xml_read_from_stream().
Variable Documentation
Isotopologues
constexpr std::array Species::Isotopologues constexpr
Definition at line 50 of file isotopologues.h.
Referenced by abs_linesReadSpeciesSplitCatalog(), all_have_ratio(), Species::IsotopologueRatios::all_isotopes_have_a_value(), Quantum::ENUMCLASS(), ENUMCLASS(), find_species_index(), isotopologues(), main(), mean_mass(), nelemSpeciesIsotopeRecordDefined(), nonexistentPartfun(), predefined_model_names(), select(), setSpeciesIsotopeRecordToIndex(), start_positions(), test_ls(), CompileTimeTests::testIsotopologuesAllValid(), testIsotopologuesIncreasing(), testSpeciesIncreasing(), Hitran::to_species_map(), and WriteBuiltinPartitionFunctionsXML().
IsotopologuesStart
constexpr auto Species::IsotopologuesStart = start_positions() constexpr
Definition at line 608 of file isotopologues.h.
Referenced by all_have_ratio(), count_isotopologues(), find_species_index(), isotopologues(), and mean_mass().
Joker
constexpr std::string_view Species::Joker = "*" constexpr
Definition at line 11 of file isotopologues.h.
Referenced by QuadraticModel::evaluate(), QuadraticModel::Jacobian(), Species::IsotopeRecord::joker(), species_iso_match(), species_match(), and test_diagonal().