ARTS: Absorption::PredefinedModel Namespace Reference
Absorption::PredefinedModel Namespace Reference
Functions
void makarov2020_o2_lines_mpm (Matrix &xsec, ArrayOfMatrix &dxsec, const Vector &f, const Vector &p, const Vector &t, const Vector &water_vmr, const ArrayOfRetrievalQuantity &jacs, const ArrayOfIndex &jacs_pos)
Adds Makarov MPM2020 O2 absorption lines to the absorption matrix.
Function Documentation
makarov2020_o2_lines_mpm()
void Absorption::PredefinedModel::makarov2020_o2_lines_mpm (Matrix & xsec, ArrayOfMatrix & dxsec, const Vector & f, const Vector & p, const Vector & t, const Vector & water_vmr, const ArrayOfRetrievalQuantity & jacs, const ArrayOfIndex & jacs_pos)
Adds Makarov MPM2020 O2 absorption lines to the absorption matrix.
Adds negative values outside of bounds. Works for Earth only
Water is 10% more effective at broadening than dry air so must be included. Does not deal with Zeeman effect and ignores negative absorption far from the line center (this can be fixed but requires clear-cut motivation)
Parameters
[in,out] xsec Cross-section of oxygen (size: [f x p])
[in,out] dxsec Cross-section derivatives of oxygen (size: [jacs_pos][f x p])
[in] f Frequency grid of computations (size: [f])
[in] p Pressure grid of computations (size: [p])
[in] t Temperature grid of computations (size: [p])
[in] water_vmr Water volume mixing ratio (size: [p])
[in] jacs The Jacobian descriptions (size: [greater than max(jacs_pos)])
[in] jacs_pos The Jacobian matrix positions in dxsec (size: [jacs_pos])
Definition at line 282 of file predefined_absorption_models.cc.
References a2, do_temperature_jacobian(), Linefunctions::DopplerConstant(), fac(), init_mpm2020_lsm(), init_mpm2020_qids(), ConstVectorView::nelem(), nlines_mpm2020, Constant::pow2(), and Constant::pow3().
Referenced by test_mpm20().