ARTS: Quantum Namespace Reference
Quantum Namespace Reference
Functions
ENUMCLASS (IdentifierType, unsigned char, None, All, Transition, EnergyLevel) struct Identifier
Class to identify and match lines by their quantum numbers.
Function Documentation
ENUMCLASS()
Quantum::ENUMCLASS (IdentifierType , unsigned char , None , All , Transition , EnergyLevel)
Class to identify and match lines by their quantum numbers.
Describes a transition, an energy level, all numbers or none as matchable. Useful to match to line energy levels and to identify lines themselves.
For transitions, the QI contains upper and lower quantum numbers. For energy levels, it only holds one set of quantum numbers which are then matched against the upper and lower qns of the lines. For all and none no quantum numbers are considered
File format: Transition: SPECIES_NAME-ISOTOPE TR UP QUANTUMNUMBERS LO QUANTUMNUMBERS Energy level: SPECIES_NAME-ISOTOPE EN QUANTUMNUMBERS All lines: SPECIES_NAME-ISOTOPE ALL No lines: SPECIES_NAME-ISOTOPE NONE
Example written out: H2O-161 TR UP J 0/1 v1 2/3 LO J 1/1 v2 1/2 H2O-161 EN J 0/1 v1 2/3 H2O-161 ALL H2O-161 NONE
Default to nothing
Return a quantum identifer as if it wants to match to lower energy level
Return a quantum identifer as if it wants to match to lower energy level
Definition at line 291 of file quantum.h.
References ARTS_ASSERT, ARTS_NOEXCEPT, Species::find_species_index(), Species::is_predefined_model(), Species::Isotopologues, Options::None, operator!=(), operator<<(), operator==(), str, Hitran::type, and ARTS::Var::x().