ARTS: ARTS::Agenda Namespace Reference
ARTS::Agenda Namespace Reference
Namespaces
Define
Execute
Method
Functions
Workspace & iy_main_agenda_emission (Workspace &ws)
Workspace & iy_main_agenda_transmission (Workspace &ws)
Workspace & iy_space_agenda_cosmic_background (Workspace &ws)
Workspace & iy_surface_agenda_use_surface_property (Workspace &ws)
Workspace & ppath_agenda_follow_sensor_los (Workspace &ws)
Workspace & ppath_agenda_plane_parallel (Workspace &ws)
Workspace & ppath_step_agenda_geometric_path (Workspace &ws)
Workspace & ppath_step_agenda_refracted_path (Workspace &ws)
Workspace & propmat_clearsky_agenda_xsec_agenda (Workspace &ws)
Workspace & propmat_clearsky_agenda_on_the_fly_zeeman (Workspace &ws)
Workspace & abs_xsec_agenda_standard (Workspace &ws)
Workspace & abs_xsec_agenda_standard_with_cia (Workspace &ws)
Workspace & surface_rtprop_agenda_blackbody_from_surface (Workspace &ws)
Workspace & surface_rtprop_agenda_blackbody_from_atmosphere (Workspace &ws)
Workspace & geo_pos_agenda_empty (Workspace &ws)
Workspace & water_p_eq_agenda_default (Workspace &ws)
Detailed Description
ARTS Agenda interaction namespace
Will only be populated by namespaces. Users of the API can define their Agendas in the Agenda namespace
Function Documentation
abs_xsec_agenda_standard()
Workspace& ARTS::Agenda::abs_xsec_agenda_standard (Workspace & ws)
Definition at line 89 of file test_cpp_api.cc.
References ARTS::Var::abs_xsec_agenda(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddLines(), and abs_xsec_per_speciesInit().
Referenced by main().
abs_xsec_agenda_standard_with_cia()
Workspace& ARTS::Agenda::abs_xsec_agenda_standard_with_cia (Workspace & ws)
Definition at line 98 of file test_cpp_api.cc.
References ARTS::Var::abs_xsec_agenda(), abs_xsec_per_speciesAddCIA(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddLines(), and abs_xsec_per_speciesInit().
geo_pos_agenda_empty()
Workspace& ARTS::Agenda::geo_pos_agenda_empty (Workspace & ws)
Definition at line 127 of file test_cpp_api.cc.
References ARTS::Var::geo_pos(), ARTS::Var::geo_pos_agenda(), Ignore(), ARTS::Var::ppath(), VectorCreate(), and VectorSet().
Referenced by main().
iy_main_agenda_emission()
Workspace& ARTS::Agenda::iy_main_agenda_emission (Workspace & ws)
Definition at line 4 of file test_cpp_api.cc.
References ARTS::Var::iy_main_agenda(), iyEmissionStandard(), and ppathCalc().
Referenced by main().
iy_main_agenda_transmission()
Workspace& ARTS::Agenda::iy_main_agenda_transmission (Workspace & ws)
Definition at line 11 of file test_cpp_api.cc.
References Ignore(), ARTS::Var::iy_id(), ARTS::Var::iy_main_agenda(), ARTS::Var::iy_unit(), iyTransmissionStandard(), and ppathCalc().
iy_space_agenda_cosmic_background()
Workspace& ARTS::Agenda::iy_space_agenda_cosmic_background (Workspace & ws)
Definition at line 20 of file test_cpp_api.cc.
References ARTS::Var::f_grid(), Ignore(), ARTS::Var::iy(), ARTS::Var::iy_space_agenda(), MatrixCBR(), ARTS::Var::rtp_los(), and ARTS::Var::rtp_pos().
Referenced by main().
iy_surface_agenda_use_surface_property()
Workspace& ARTS::Agenda::iy_surface_agenda_use_surface_property (Workspace & ws)
Definition at line 29 of file test_cpp_api.cc.
References ARTS::Var::iy_surface_agenda(), iySurfaceRtpropAgenda(), and SurfaceDummy().
Referenced by main().
ppath_agenda_follow_sensor_los()
Workspace& ARTS::Agenda::ppath_agenda_follow_sensor_los (Workspace & ws)
Definition at line 36 of file test_cpp_api.cc.
References Ignore(), ARTS::Var::ppath_agenda(), ppathStepByStep(), and ARTS::Var::rte_pos2().
Referenced by main().
ppath_agenda_plane_parallel()
Workspace& ARTS::Agenda::ppath_agenda_plane_parallel (Workspace & ws)
Definition at line 44 of file test_cpp_api.cc.
References ARTS::Var::f_grid(), Ignore(), ARTS::Var::ppath_agenda(), ARTS::Var::ppath_lraytrace(), ppathPlaneParallel(), ARTS::Var::rte_pos2(), ARTS::Var::t_field(), and ARTS::Var::vmr_field().
ppath_step_agenda_geometric_path()
Workspace& ARTS::Agenda::ppath_step_agenda_geometric_path (Workspace & ws)
Definition at line 54 of file test_cpp_api.cc.
References ARTS::Var::f_grid(), Ignore(), ARTS::Var::ppath_lraytrace(), ARTS::Var::ppath_step_agenda(), and ppath_stepGeometric().
Referenced by main().
ppath_step_agenda_refracted_path()
Workspace& ARTS::Agenda::ppath_step_agenda_refracted_path (Workspace & ws)
Definition at line 63 of file test_cpp_api.cc.
References ARTS::Var::ppath_step_agenda(), and ppath_stepRefractionBasic().
propmat_clearsky_agenda_on_the_fly_zeeman()
Workspace& ARTS::Agenda::propmat_clearsky_agenda_on_the_fly_zeeman (Workspace & ws)
Definition at line 80 of file test_cpp_api.cc.
References ARTS::Var::propmat_clearsky_agenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyAddZeeman(), and propmat_clearskyInit().
propmat_clearsky_agenda_xsec_agenda()
Workspace& ARTS::Agenda::propmat_clearsky_agenda_xsec_agenda (Workspace & ws)
Definition at line 70 of file test_cpp_api.cc.
References Ignore(), ARTS::Var::propmat_clearsky_agenda(), propmat_clearskyAddXsecAgenda(), propmat_clearskyInit(), ARTS::Var::rtp_los(), and ARTS::Var::rtp_mag().
Referenced by main().
surface_rtprop_agenda_blackbody_from_atmosphere()
Workspace& ARTS::Agenda::surface_rtprop_agenda_blackbody_from_atmosphere (Workspace & ws)
Definition at line 117 of file test_cpp_api.cc.
References InterpAtmFieldToPosition(), ARTS::Var::surface_rtprop_agenda(), ARTS::Var::surface_skin_t(), surfaceBlackbody(), and ARTS::Var::t_field().
surface_rtprop_agenda_blackbody_from_surface()
Workspace& ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface (Workspace & ws)
Definition at line 107 of file test_cpp_api.cc.
References InterpSurfaceFieldToPosition(), ARTS::Var::surface_rtprop_agenda(), ARTS::Var::surface_skin_t(), surfaceBlackbody(), and ARTS::Var::t_surface().
Referenced by main().
water_p_eq_agenda_default()
Workspace& ARTS::Agenda::water_p_eq_agenda_default (Workspace & ws)
Definition at line 136 of file test_cpp_api.cc.
References ARTS::Var::water_p_eq_agenda(), and water_p_eq_fieldMK05().
Referenced by main().