ARTS: nc_io_array_types.cc File Reference
nc_io_array_types.cc File Reference
This file contains functions to handle NetCDF data files.
#include "arts.h"
#include "nc_io.h"
#include "nc_io_types.h"
Macros
#define TMPL_NC_READ_WRITE_FILE_DUMMY(what)
Functions
void nca_read_from_file (const int ncid, ArrayOfMatrix &aom, const Verbosity &)
Reads an ArrayOfMatrix from a NetCDF file.
void nca_write_to_file (const int ncid, const ArrayOfMatrix &aom, const Verbosity &)
Writes an ArrayOfMatrix to a NetCDF file.
void nca_read_from_file (const int ncid, ArrayOfVector &aov, const Verbosity &)
Reads an ArrayOfVector from a NetCDF file.
void nca_write_to_file (const int ncid, const ArrayOfVector &aov, const Verbosity &)
Writes an ArrayOfVector to a NetCDF file.
Detailed Description
This file contains functions to handle NetCDF data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2008-10-01
Definition in file nc_io_array_types.cc.
Macro Definition Documentation
TMPL_NC_READ_WRITE_FILE_DUMMY
#define TMPL_NC_READ_WRITE_FILE_DUMMY (what)
Value:
  void nca_write_to_file(const int, const what&, const Verbosity&) {          \
    throw runtime_error("NetCDF support not yet implemented for this type!"); \
  }                                                                           \
  void nca_read_from_file(const int, what&, const Verbosity&) {               \
    throw runtime_error("NetCDF support not yet implemented for this type!"); \
  }
Definition at line 200 of file nc_io_array_types.cc.
Function Documentation
nca_read_from_file() [1/2]
void nca_read_from_file (const int ncid, ArrayOfMatrix & aom, const Verbosity &)
Reads an ArrayOfMatrix from a NetCDF file.
Parameters
ncid NetCDF file descriptor
aom ArrayOfMatrix
Definition at line 44 of file nc_io_array_types.cc.
References nc_get_dim(), nca_get_data_long(), nca_get_dataa_double(), and Absorption::nelem().
nca_read_from_file() [2/2]
void nca_read_from_file (const int ncid, ArrayOfVector & aov, const Verbosity &)
Reads an ArrayOfVector from a NetCDF file.
Parameters
ncid NetCDF file descriptor
aov ArrayOfVector
Definition at line 130 of file nc_io_array_types.cc.
References nc_get_dim(), nca_get_data_long(), nca_get_dataa_double(), and Absorption::nelem().
nca_write_to_file() [1/2]
void nca_write_to_file (const int ncid, const ArrayOfMatrix & aom, const Verbosity &)
Writes an ArrayOfMatrix to a NetCDF file.
Parameters
ncf NetCDF file descriptor
aom ArrayOfMatrix
Definition at line 73 of file nc_io_array_types.cc.
References nca_error(), and Array< base >::nelem().
nca_write_to_file() [2/2]
void nca_write_to_file (const int ncid, const ArrayOfVector & aov, const Verbosity &)
Writes an ArrayOfVector to a NetCDF file.
Parameters
ncid NetCDF file descriptor
aov ArrayOfVector
Definition at line 153 of file nc_io_array_types.cc.
References nca_error(), and Array< base >::nelem().