ARTS: nc_io_compound_types.cc File Reference
nc_io_compound_types.cc File Reference
#include "config.h"
#include <cstring>
#include "arts.h"
#include "nc_io.h"
#include "nc_io_types.h"
Macros
#define TMPL_NC_READ_WRITE_FILE_DUMMY(what)
Functions
void nca_read_from_file (const int ncid, GasAbsLookup &gal, const Verbosity &)
Reads a GasAbsLookup table from a NetCDF file.
void nca_write_to_file (const int ncid, const GasAbsLookup &gal, const Verbosity &)
Writes a GasAbsLookup table to a NetCDF file.
Macro Definition Documentation
TMPL_NC_READ_WRITE_FILE_DUMMY
#define TMPL_NC_READ_WRITE_FILE_DUMMY (what)
Value:
  void nca_write_to_file(const int, const what&, const Verbosity&) {          \
    throw runtime_error("NetCDF support not yet implemented for this type!"); \
  }                                                                           \
  void nca_read_from_file(const int, what&, const Verbosity&) {               \
    throw runtime_error("NetCDF support not yet implemented for this type!"); \
  }
Definition at line 177 of file nc_io_compound_types.cc.
Function Documentation
nca_read_from_file()
void nca_read_from_file (const int ncid, GasAbsLookup & gal, const Verbosity &)
Reads a GasAbsLookup table from a NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] gal GasAbsLookup
Author
Oliver Lemke
Definition at line 49 of file nc_io_compound_types.cc.
References GasAbsLookup::f_grid, nca_get_data_ArrayOfArrayOfSpeciesTag(), nca_get_data_ArrayOfIndex(), nca_get_data_Matrix(), nca_get_data_Tensor4(), nca_get_data_Vector(), Array< base >::nelem(), GasAbsLookup::nls_pert, GasAbsLookup::nonlinear_species, GasAbsLookup::p_grid, GasAbsLookup::species, GasAbsLookup::t_pert, GasAbsLookup::t_ref, GasAbsLookup::vmrs_ref, and GasAbsLookup::xsec.
nca_write_to_file()
void nca_write_to_file (const int ncid, const GasAbsLookup & gal, const Verbosity &)
Writes a GasAbsLookup table to a NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[out] gal GasAbsLookup
Author
Oliver Lemke
Definition at line 72 of file nc_io_compound_types.cc.
References GasAbsLookup::f_grid, nca_def_ArrayOfIndex(), nca_def_dim(), nca_def_Matrix(), nca_def_Tensor4(), nca_def_var(), nca_def_Vector(), nca_error(), nca_put_var_ArrayOfIndex(), nca_put_var_Matrix(), nca_put_var_Tensor4(), nca_put_var_Vector(), Array< base >::nelem(), GasAbsLookup::nls_pert, GasAbsLookup::nonlinear_species, GasAbsLookup::p_grid, GasAbsLookup::species, GasAbsLookup::t_pert, GasAbsLookup::t_ref, GasAbsLookup::vmrs_ref, and GasAbsLookup::xsec.