ARTS: nc_io.h File Reference
nc_io.h File Reference
This file contains basic functions to handle NetCDF data files.
#include "arts.h"
#include <netcdf.h>
#include "abs_species_tags.h"
#include "exceptions.h"
#include "messages.h"
#include "mystring.h"
Functions
void nca_filename (String &filename, const String &varname)
Gives the default filename for the NetCDF formats.
void nca_filename_with_index (String &filename, const Index &file_index, const String &varname)
Gives the default filename, with file index, for the NetCDF formats.
template<typename T >
void nca_read_from_file (const String &filename, T &type, const Verbosity &verbosity)
Reads a variable from a NetCDF file.
template<typename T >
void nca_write_to_file (const String &filename, const T &type, const Verbosity &verbosity)
Writes a variable to a NetCDF file.
void nca_def_dim (const int ncid, const String &name, const Index nelem, int *ncdim)
Define NetCDF dimension.
void nca_def_var (const int ncid, const String &name, const nc_type type, const int ndims, const int *dims, int *varid)
Define NetCDF variable.
int nca_def_ArrayOfIndex (const int ncid, const String &name, const ArrayOfIndex &a)
Define NetCDF dimensions and variable for an ArrayOfIndex.
int nca_def_Vector (const int ncid, const String &name, const Vector &v)
Define NetCDF dimensions and variable for a Vector.
int nca_def_Matrix (const int ncid, const String &name, const Matrix &m)
Define NetCDF dimensions and variable for a Matrix.
int nca_def_Tensor4 (const int ncid, const String &name, const Tensor4 &t)
Define NetCDF dimensions and variable for a Tensor4.
Index nc_get_dim (const int ncid, const String &name, const bool noerror=false)
Read a dimension from NetCDF file.
void nca_get_data_int (const int ncid, const String &name, int *data)
Read variable of type int from NetCDF file.
void nca_get_data_long (const int ncid, const String &name, long *data)
Read variable of type long from NetCDF file.
void nca_get_data_double (const int ncid, const String &name, Numeric *data)
Read variable of type double from NetCDF file.
void nca_get_dataa_double (const int ncid, const String &name, size_t start, size_t count, Numeric *data)
Read variable of type array of double from NetCDF file.
void nca_get_data_text (const int ncid, const String &name, char *data)
Read variable of type array of char from NetCDF file.
void nca_get_data_ArrayOfIndex (const int ncid, const String &name, ArrayOfIndex &aoi, const bool noerror)
Read variable of type ArrayOfIndex from NetCDF file.
void nca_get_data_ArrayOfArrayOfSpeciesTag (const int ncid, const String &name, ArrayOfArrayOfSpeciesTag &aast, const bool noerror)
Read variable of type ArrayOfArrayOfSpeciesTag from NetCDF file.
void nca_get_data_Vector (const int ncid, const String &name, Vector &v, const bool noerror=false)
Read variable of type Vector from NetCDF file.
void nca_get_data_Matrix (const int ncid, const String &name, Matrix &m, const bool noerror=false)
Read variable of type Matrix from NetCDF file.
void nca_get_data_Tensor4 (const int ncid, const String &name, Tensor4 &m, const bool noerror=false)
Read variable of type Tensor4 from NetCDF file.
bool nca_put_var_ArrayOfIndex (const int ncid, const int varid, const ArrayOfIndex &a)
Write variable of type ArrayOfIndex to NetCDF file.
bool nca_put_var_Vector (const int ncid, const int varid, const Vector &v)
Write variable of type Vector to NetCDF file.
bool nca_put_var_Matrix (const int ncid, const int varid, const Matrix &m)
Write variable of type Matrix to NetCDF file.
bool nca_put_var_Tensor4 (const int ncid, const int varid, const Tensor4 &t)
Write variable of type Tensor4 to NetCDF file.
void nca_error (const int err, const String msg)
Throws a runtime error for the given NetCDF error code.
Detailed Description
This file contains basic functions to handle NetCDF data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2008-09-12
Definition in file nc_io.h.
Function Documentation
nc_get_dim()
Index nc_get_dim (const int ncid, const String & name, const bool noerror)
Read a dimension from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Dimension name in NetCDF file
[in] noerror Return 0 instead of throwing an exception if dimension does not exist in file
Returns
Dimension size
Author
Oliver Lemke
Definition at line 300 of file nc_io.cc.
References nca_error().
Referenced by nca_get_data_ArrayOfArrayOfSpeciesTag(), nca_get_data_ArrayOfIndex(), nca_get_data_Matrix(), nca_get_data_Tensor4(), nca_get_data_Vector(), and nca_read_from_file().
nca_def_ArrayOfIndex()
int nca_def_ArrayOfIndex (const int ncid, const String & name, const ArrayOfIndex & a)
Define NetCDF dimensions and variable for an ArrayOfIndex.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] a ArrayOfIndex
Returns
Variable handle
Author
Oliver Lemke
Definition at line 214 of file nc_io.cc.
References nca_def_dim(), nca_def_var(), and Array< base >::nelem().
Referenced by nca_write_to_file().
nca_def_dim()
void nca_def_dim (const int ncid, const String & name, const Index nelem, int * ncdim)
Define NetCDF dimension.
Parameters
[in] ncid NetCDF file descriptor
[in] name Dimension name
[in] nelem Dimension size
[out] ncdim NetCDF dimension handle
Author
Oliver Lemke
Definition at line 174 of file nc_io.cc.
References nca_error(), and Absorption::nelem().
Referenced by nca_def_ArrayOfIndex(), nca_def_Matrix(), nca_def_Tensor4(), nca_def_Vector(), and nca_write_to_file().
nca_def_Matrix()
int nca_def_Matrix (const int ncid, const String & name, const Matrix & m)
Define NetCDF dimensions and variable for a Matrix.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] m Matrix
Returns
Variable handle
Author
Oliver Lemke
Definition at line 256 of file nc_io.cc.
References nca_def_dim(), nca_def_var(), ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by nca_write_to_file().
nca_def_Tensor4()
int nca_def_Tensor4 (const int ncid, const String & name, const Tensor4 & t)
Define NetCDF dimensions and variable for a Tensor4.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] t Tensor4
Returns
Variable handle
Author
Oliver Lemke
Definition at line 277 of file nc_io.cc.
References ConstTensor4View::nbooks(), nca_def_dim(), nca_def_var(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Referenced by nca_write_to_file().
nca_def_var()
void nca_def_var (const int ncid, const String & name, const nc_type type, const int ndims, const int * dims, int * varid)
Define NetCDF variable.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] type NetCDF type
[in] ndims Number of dimensions
[in] dims Pointer to dimensions
[out] varid NetCDF variable handle
Author
Oliver Lemke
Definition at line 194 of file nc_io.cc.
References nca_error().
Referenced by nca_def_ArrayOfIndex(), nca_def_Matrix(), nca_def_Tensor4(), nca_def_Vector(), and nca_write_to_file().
nca_def_Vector()
int nca_def_Vector (const int ncid, const String & name, const Vector & v)
Define NetCDF dimensions and variable for a Vector.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] v Vector
Returns
Variable handle
Author
Oliver Lemke
Definition at line 236 of file nc_io.cc.
References nca_def_dim(), nca_def_var(), and ConstVectorView::nelem().
Referenced by nca_write_to_file().
nca_error()
void nca_error (const int e, const String s)
Throws a runtime error for the given NetCDF error code.
Parameters
[in] e NetCDF error code
[in] s Error message string
Author
Oliver Lemke
Definition at line 622 of file nc_io.cc.
Referenced by nc_get_dim(), nca_def_dim(), nca_def_var(), nca_get_data_double(), nca_get_data_int(), nca_get_data_long(), nca_get_data_text(), nca_get_dataa_double(), nca_put_var_ArrayOfIndex(), nca_put_var_Matrix(), nca_put_var_Tensor4(), nca_put_var_Vector(), nca_write_to_file(), and WriteMolTau().
nca_filename()
void nca_filename (String & filename, const String & varname)
Gives the default filename for the NetCDF formats.
The default name is only used if the filename is empty.
Parameters
filename filename
varname variable name
Author
Oliver Lemke
Definition at line 53 of file nc_io.cc.
References out_basename.
Referenced by WriteNetCDF().
nca_filename_with_index()
void nca_filename_with_index (String & filename, const Index & file_index, const String & varname)
Gives the default filename, with file index, for the NetCDF formats.
The default name is only used if the filename is empty.
Parameters
[out] filename filename
[in] file_index Index appended to the filename
[in] varname variable name
Author
Oliver Lemke
Definition at line 70 of file nc_io.cc.
References out_basename.
Referenced by WriteNetCDFIndexed().
nca_get_data_ArrayOfArrayOfSpeciesTag()
void nca_get_data_ArrayOfArrayOfSpeciesTag (const int ncid, const String & name, ArrayOfArrayOfSpeciesTag & aast, const bool noerror)
Read variable of type ArrayOfArrayOfSpeciesTag from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] aast Data read from file
[in] noerror Return empty variable instead of throwing an exception if variable does not exist in file
Author
Oliver Lemke
Definition at line 438 of file nc_io.cc.
References nc_get_dim(), nca_get_data_ArrayOfIndex(), nca_get_data_text(), and Array< base >::nelem().
Referenced by nca_read_from_file().
nca_get_data_ArrayOfIndex()
void nca_get_data_ArrayOfIndex (const int ncid, const String & name, ArrayOfIndex & aoi, const bool noerror)
Read variable of type ArrayOfIndex from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] aoi Data read from file
[in] noerror Return empty variable instead of throwing an exception if variable does not exist in file
Author
Oliver Lemke
Definition at line 413 of file nc_io.cc.
References nc_get_dim(), nca_get_data_long(), and Absorption::nelem().
Referenced by nca_get_data_ArrayOfArrayOfSpeciesTag(), and nca_read_from_file().
nca_get_data_double()
void nca_get_data_double (const int ncid, const String & name, Numeric * data)
Read variable of type double from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] data Data read from file
Author
Oliver Lemke
Definition at line 359 of file nc_io.cc.
References data, and nca_error().
Referenced by nca_get_data_Matrix(), nca_get_data_Tensor4(), nca_get_data_Vector(), and nca_read_from_file().
nca_get_data_int()
void nca_get_data_int (const int ncid, const String & name, int * data)
Read variable of type int from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] data Data read from file
Author
Oliver Lemke
Definition at line 327 of file nc_io.cc.
References data, and nca_error().
nca_get_data_long()
void nca_get_data_long (const int ncid, const String & name, long * data)
Read variable of type long from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] data Data read from file
Author
Oliver Lemke
Definition at line 343 of file nc_io.cc.
References data, and nca_error().
Referenced by nca_get_data_ArrayOfIndex(), and nca_read_from_file().
nca_get_data_Matrix()
void nca_get_data_Matrix (const int ncid, const String & name, Matrix & m, const bool noerror)
Read variable of type Matrix from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] m Data read from file
[in] noerror Return empty variable instead of throwing an exception if variable does not exist in file
Author
Oliver Lemke
Definition at line 497 of file nc_io.cc.
References MatrixView::get_c_array(), nc_get_dim(), nca_get_data_double(), and Matrix::resize().
Referenced by nca_read_from_file().
nca_get_data_Tensor4()
void nca_get_data_Tensor4 (const int ncid, const String & name, Tensor4 & t, const bool noerror)
Read variable of type Tensor4 from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] t Data read from file
[in] noerror Return empty variable instead of throwing an exception if variable does not exist in file
Author
Oliver Lemke
Definition at line 517 of file nc_io.cc.
References Tensor4View::get_c_array(), nc_get_dim(), nca_get_data_double(), and Tensor4::resize().
Referenced by nca_read_from_file().
nca_get_data_text()
void nca_get_data_text (const int ncid, const String & name, char * data)
Read variable of type array of char from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] data Data read from file
Author
Oliver Lemke
Definition at line 395 of file nc_io.cc.
References data, and nca_error().
Referenced by nca_get_data_ArrayOfArrayOfSpeciesTag().
nca_get_data_Vector()
void nca_get_data_Vector (const int ncid, const String & name, Vector & v, const bool noerror)
Read variable of type Vector from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] v Data read from file
[in] noerror Return empty variable instead of throwing an exception if variable does not exist in file
Author
Oliver Lemke
Definition at line 478 of file nc_io.cc.
References VectorView::get_c_array(), nc_get_dim(), nca_get_data_double(), Absorption::nelem(), and Vector::resize().
Referenced by nca_read_from_file().
nca_get_dataa_double()
void nca_get_dataa_double (const int ncid, const String & name, size_t start, size_t count, Numeric * data)
Read variable of type array of double from NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[out] data Data read from file
Author
Oliver Lemke
Definition at line 375 of file nc_io.cc.
References data, nca_error(), and Zeeman::start().
Referenced by nca_read_from_file().
nca_put_var_ArrayOfIndex()
bool nca_put_var_ArrayOfIndex (const int ncid, const int varid, const ArrayOfIndex & a)
Write variable of type ArrayOfIndex to NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] a Data to be written
Returns
True if variable was not empty
Author
Oliver Lemke
Definition at line 539 of file nc_io.cc.
References nca_error(), and Array< base >::nelem().
Referenced by nca_write_to_file().
nca_put_var_Matrix()
bool nca_put_var_Matrix (const int ncid, const int varid, const Matrix & m)
Write variable of type Matrix to NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] m Data to be written
Returns
True if variable was not empty
Author
Oliver Lemke
Definition at line 585 of file nc_io.cc.
References MatrixView::get_c_array(), nca_error(), ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by nca_write_to_file().
nca_put_var_Tensor4()
bool nca_put_var_Tensor4 (const int ncid, const int varid, const Tensor4 & t)
Write variable of type Tensor4 to NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] t Data to be written
Returns
True if variable was not empty
Author
Oliver Lemke
Definition at line 604 of file nc_io.cc.
References Tensor4View::get_c_array(), ConstTensor4View::nbooks(), nca_error(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
Referenced by nca_write_to_file().
nca_put_var_Vector()
bool nca_put_var_Vector (const int ncid, const int varid, const Vector & v)
Write variable of type Vector to NetCDF file.
Parameters
[in] ncid NetCDF file descriptor
[in] name Variable name in NetCDF file
[in] v Data to be written
Returns
True if variable was not empty
Author
Oliver Lemke
Definition at line 566 of file nc_io.cc.
References VectorView::get_c_array(), nca_error(), and ConstVectorView::nelem().
Referenced by nca_write_to_file().
nca_read_from_file()
template<typename T > void nca_read_from_file (const String & filename, T & type, const Verbosity & verbosity)
Reads a variable from a NetCDF file.
Parameters
[in] filename NetCDF filename
[out] type Input variable
[in] verbosity Verbosity
Author
Oliver Lemke
Definition at line 94 of file nc_io.cc.
References CREATE_OUT2, expand_path(), and nca_read_from_file().
Referenced by nca_read_from_file(), and ReadNetCDF().
nca_write_to_file()
template<typename T > void nca_write_to_file (const String & filename, const T & type, const Verbosity & verbosity)
Writes a variable to a NetCDF file.
Parameters
[in] filename NetCDF filename
[in] type Output variable
[in] verbosity Verbosity
Author
Oliver Lemke
Definition at line 134 of file nc_io.cc.
References add_basedir(), CREATE_OUT2, and nca_write_to_file().
Referenced by nca_write_to_file(), and WriteNetCDF().