ARTS: nlte.cc File Reference
nlte.cc File Reference
#include "nlte.h"
#include "interpolation_lagrange.h"
Functions
void statistical_equilibrium_equation (MatrixView A, ConstVectorView Aij, ConstVectorView Bij, ConstVectorView Bji, ConstVectorView Cij, ConstVectorView Cji, ConstVectorView Jij, const ArrayOfIndex &upper, const ArrayOfIndex &lower)
Sets up the solution matrix for linear statistical equilibrium equation.
void dampened_statistical_equilibrium_equation (MatrixView A, ConstVectorView x, ConstVectorView Aij, ConstVectorView Bij, ConstVectorView Bji, ConstVectorView Cij, ConstVectorView Cji, ConstVectorView Jij, ConstVectorView Lambda, const ArrayOfIndex &upper, const ArrayOfIndex &lower, const Numeric &total_number_count)
Sets up the solution matrix for linear dampened statistical equilibrium equation.
void set_constant_statistical_equilibrium_matrix (MatrixView A, VectorView x, const Numeric &sem_ratio, const Index row)
Set a row of the SEE matrix and level distribution vector to constant.
Vector createAij (const ArrayOfArrayOfAbsorptionLines &abs_lines)
Create a Aij object.
Vector createBij (const ArrayOfArrayOfAbsorptionLines &abs_lines)
Create a Bij object.
Vector createBji (const Vector &Bij, const ArrayOfArrayOfAbsorptionLines &abs_lines)
Create a Bji object.
Vector createCji (const Vector &Cij, const ArrayOfArrayOfAbsorptionLines &abs_lines, const Numeric &T)
Create a Cji object.
void setCji (Vector &Cji, const Vector &Cij, const ArrayOfArrayOfAbsorptionLines &abs_lines, const Numeric &T)
Set the Cji object.
void nlte_collision_factorsCalcFromCoeffs (Vector &Cij, Vector &Cji, const ArrayOfArrayOfAbsorptionLines &abs_lines, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfArrayOfGriddedField1 &collision_coefficients, const ArrayOfQuantumIdentifier &collision_line_identifiers, const SpeciesAuxData &isotopologue_ratios, const ConstVectorView vmr, const Numeric &T, const Numeric &P)
Gets collisional factors from coefficients.
void nlte_positions_in_statistical_equilibrium_matrix (ArrayOfIndex &upper, ArrayOfIndex &lower, const ArrayOfArrayOfAbsorptionLines &abs_lines, const EnergyLevelMap &nlte_field)
Finds upper and lower states in SEE Matrix.
Index find_first_unique_in_lower (const ArrayOfIndex &upper, const ArrayOfIndex &lower) noexcept
Finds a unique lower state if one exists or returns index to last element.
void check_collision_line_identifiers (const ArrayOfQuantumIdentifier &collision_line_identifiers)
Checks that a WSV is OK or throws a run-time error.
Function Documentation
check_collision_line_identifiers()
void check_collision_line_identifiers (const ArrayOfQuantumIdentifier & collision_line_identifiers)
Checks that a WSV is OK or throws a run-time error.
Parameters
[in] collision_line_identifiers As WSV
Definition at line 284 of file nlte.cc.
References ARTS::Var::collision_line_identifiers(), and x.
Referenced by collision_coefficientsFromSplitFiles().
createAij()
Vector createAij (const ArrayOfArrayOfAbsorptionLines & abs_lines)
Create a Aij object.
Parameters
[in] abs_lines All lines of interest
Returns
Vector Einstein coefficient for spontaneuos emission of all lines
Definition at line 96 of file nlte.cc.
References ARTS::Var::abs_lines(), and Absorption::nelem().
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
createBij()
Vector createBij (const ArrayOfArrayOfAbsorptionLines & abs_lines)
Create a Bij object.
Parameters
[in] abs_lines All lines of interest
Returns
Vector Einstein coefficient for induced emission of all lines
Definition at line 113 of file nlte.cc.
References ARTS::Var::abs_lines(), Absorption::nelem(), PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
createBji()
Vector createBji (const Vector & Bij, const ArrayOfArrayOfAbsorptionLines & abs_lines)
Create a Bji object.
Parameters
[in] Bij Einstein coefficient for induced emission of all lines
[in] abs_lines All lines of interest
Returns
Vector Einstein coefficient for induced absorption of all lines
Definition at line 135 of file nlte.cc.
References ARTS::Var::abs_lines(), and ConstVectorView::nelem().
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
createCji()
Vector createCji (const Vector & Cij, const ArrayOfArrayOfAbsorptionLines & abs_lines, const Numeric & T)
Create a Cji object.
Parameters
[in] Cij Collisional rate of change from upper to lower state level
[in] abs_lines All lines of interest
[in] T Temperature
Returns
Vector Collisional rate of change from lower to upper state level
Definition at line 153 of file nlte.cc.
References ARTS::Var::abs_lines(), Absorption::nelem(), and setCji().
dampened_statistical_equilibrium_equation()
void dampened_statistical_equilibrium_equation (MatrixView A, ConstVectorView x, ConstVectorView Aij, ConstVectorView Bij, ConstVectorView Bji, ConstVectorView Cij, ConstVectorView Cji, ConstVectorView Jij, ConstVectorView Lambda, const ArrayOfIndex & upper, const ArrayOfIndex & lower, const Numeric & total_number_count = 1.0)
Sets up the solution matrix for linear dampened statistical equilibrium equation.
Parameters
[in,out] A Matrix to solve SEE
[in] x Ratio of molecules for each state
[in] Aij Einstein coefficient for spontaneuos emission of all lines
[in] Bij Einstein coefficient for induced emission of all lines
[in] Bji Einstein coefficient for induced absorption of all lines
[in] Cij Collisional rate of change from upper to lower state level
[in] Cji Collisional rate of change from lower to upper state level
[in] Jij Radiation field for the upper to lower transition for each line
[in] Lambda Transmission for the upper to lower transition for each line
[in] upper Index list for upper state levels for each line
[in] lower Index list for lower state levels for each line
Definition at line 54 of file nlte.cc.
References ConstVectorView::nelem(), nlines, and x.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
find_first_unique_in_lower()
Index find_first_unique_in_lower (const ArrayOfIndex & upper, const ArrayOfIndex & lower) noexcept
Finds a unique lower state if one exists or returns index to last element.
Parameters
[in] upper Index list for upper state levels for each line
[in] lower Index list for lower state levels for each line
Returns
Index Pos of unique element or len-1
Definition at line 275 of file nlte.cc.
References Interpolation::l().
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
nlte_collision_factorsCalcFromCoeffs()
void nlte_collision_factorsCalcFromCoeffs (Vector & Cij, Vector & Cji, const ArrayOfArrayOfAbsorptionLines & abs_lines, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfArrayOfGriddedField1 & collision_coefficients, const ArrayOfQuantumIdentifier & collision_line_identifiers, const SpeciesAuxData & isotopologue_ratios, const ConstVectorView vmr, const Numeric & T, const Numeric & P)
Gets collisional factors from coefficients.
Parameters
[in,out] Cij Collisional rate of change from upper to lower state level
[in,out] Cji Collisional rate of change from lower to upper state level
[in] abs_lines All lines of interest
[in] abs_species All absorption species
[in] collision_coefficients As WSV
[in] collision_line_identifiers As WSV
[in] isotopologue_ratios As WSV
[in] vmr Volume mixing ratios of absoprtion species
[in] T Temperature
[in] P Pressure
Definition at line 182 of file nlte.cc.
References ARTS::Var::abs_lines(), ARTS::Var::abs_species(), BOLTZMAN_CONST, ARTS::Var::collision_line_identifiers(), and ARTS::Var::isotopologue_ratios().
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
nlte_positions_in_statistical_equilibrium_matrix()
void nlte_positions_in_statistical_equilibrium_matrix (ArrayOfIndex & upper, ArrayOfIndex & lower, const ArrayOfArrayOfAbsorptionLines & abs_lines, const EnergyLevelMap & nlte_field)
Finds upper and lower states in SEE Matrix.
Parameters
[in,out] upper Index list for upper state levels for each line
[in,out] lower Index list for lower state levels for each line
[in] abs_lines All lines of interest
[in] nlte_quantum_identifiers As WSV
Definition at line 242 of file nlte.cc.
References ARTS::Var::abs_lines(), Absorption::nelem(), and ARTS::Var::nlte_field().
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
set_constant_statistical_equilibrium_matrix()
void set_constant_statistical_equilibrium_matrix (MatrixView A, VectorView x, const Numeric & sem_ratio, const Index row)
Set a row of the SEE matrix and level distribution vector to constant.
Parameters
[in] A Matrix to solve SEE
[in] x Ratio of molecules for each state
[in] sem_ratio Largest ratio possible
[in] row Row of SEE Matrix being zero
Definition at line 88 of file nlte.cc.
References joker, and x.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().
setCji()
void setCji (Vector & Cji, const Vector & Cij, const ArrayOfArrayOfAbsorptionLines & abs_lines, const Numeric & T)
Set the Cji object.
Parameters
[in,out] Cji Collisional rate of change from lower to upper state level
[in] Cij Collisional rate of change from upper to lower state level
[in] abs_lines All lines of interest
[in] T Temperature
[in] n Size of Cij
Definition at line 162 of file nlte.cc.
References ARTS::Var::abs_lines(), BOLTZMAN_CONST, and PLANCK_CONST.
Referenced by createCji().
statistical_equilibrium_equation()
void statistical_equilibrium_equation (MatrixView A, ConstVectorView Aij, ConstVectorView Bij, ConstVectorView Bji, ConstVectorView Cij, ConstVectorView Cji, ConstVectorView Jij, const ArrayOfIndex & upper, const ArrayOfIndex & lower)
Sets up the solution matrix for linear statistical equilibrium equation.
Parameters
[in,out] A Matrix to solve SEE
[in] Aij Einstein coefficient for spontaneuos emission of all lines
[in] Bij Einstein coefficient for induced emission of all lines
[in] Bji Einstein coefficient for induced absorption of all lines
[in] Cij Collisional rate of change from upper to lower state level
[in] Cji Collisional rate of change from lower to upper state level
[in] Jij Radiation field for the upper to lower transition for each line
[in] upper Index list for upper state levels for each line
[in] lower Index list for lower state levels for each line
Definition at line 30 of file nlte.cc.
References ConstVectorView::nelem(), and nlines.
Referenced by nlte_fieldForSingleSpeciesNonOverlappingLines().