ARTS: optproperties.cc File Reference
optproperties.cc File Reference
This file contains definitions and functions related to the optical properties of particles.
#include "optproperties.h"
#include <cfloat>
#include <cmath>
#include <stdexcept>
#include "array.h"
#include "arts.h"
#include "check_input.h"
#include "interpolation.h"
#include "interpolation_lagrange.h"
#include "logic.h"
#include "math_funcs.h"
#include "matpackVII.h"
#include "messages.h"
#include "xml_io.h"
Macros
#define F11 pha_mat_int[0]
#define F12 pha_mat_int[1]
#define F22 pha_mat_int[2]
#define F33 pha_mat_int[3]
#define F34 pha_mat_int[4]
#define F44 pha_mat_int[5]
Functions
void opt_prop_Bulk (Tensor5 &ext_mat, Tensor4 &abs_vec, Index &ptype, const ArrayOfTensor5 &ext_mat_ss, const ArrayOfTensor4 &abs_vec_ss, const ArrayOfIndex &ptypes_ss)
one-line descript
void opt_prop_ScatSpecBulk (ArrayOfTensor5 &ext_mat, ArrayOfTensor4 &abs_vec, ArrayOfIndex &ptype, const ArrayOfArrayOfTensor5 &ext_mat_se, const ArrayOfArrayOfTensor4 &abs_vec_se, const ArrayOfArrayOfIndex &ptypes_se, ConstMatrixView pnds, ConstMatrixView t_ok)
Scattering species bulk extinction and absorption.
void opt_prop_NScatElems (ArrayOfArrayOfTensor5 &ext_mat, ArrayOfArrayOfTensor4 &abs_vec, ArrayOfArrayOfIndex &ptypes, Matrix &t_ok, const ArrayOfArrayOfSingleScatteringData &scat_data, const Index &stokes_dim, const Vector &T_array, const Matrix &dir_array, const Index &f_index, const Index &t_interp_order)
Extinction and absorption from all scattering elements.
ArrayOfLagrangeInterpolation ssd_tinterp_parameters (VectorView t_ok, Index &this_T_interp_order, ConstVectorView T_grid, const Vector &T_array, const Index &t_interp_order)
Determine T-interpol parameters for a specific scattering element.
void opt_prop_1ScatElem (Tensor5View ext_mat, Tensor4View abs_vec, Index &ptype, VectorView t_ok, const SingleScatteringData &ssd, const Vector &T_array, const Matrix &dir_array, const Index &f_start, const Index &t_interp_order)
Preparing extinction and absorption from one scattering element.
void ext_mat_SSD2Stokes (MatrixView ext_mat_stokes, ConstVectorView ext_mat_ssd, const Index &stokes_dim, const Index &ptype)
Extinction matrix scat_data to stokes format conversion.
void abs_vec_SSD2Stokes (VectorView abs_vec_stokes, ConstVectorView abs_vec_ssd, const Index &stokes_dim, const Index &ptype)
Absorption vector scat_data to stokes format conversion.
void pha_mat_Bulk (Tensor6 &pha_mat, Index &ptype, const ArrayOfTensor6 &pha_mat_ss, const ArrayOfIndex &ptypes_ss)
Scattering species bulk phase matrix.
void pha_mat_ScatSpecBulk (ArrayOfTensor6 &pha_mat, ArrayOfIndex &ptype, const ArrayOfArrayOfTensor6 &pha_mat_se, const ArrayOfArrayOfIndex &ptypes_se, ConstMatrixView pnds, ConstMatrixView t_ok)
Scattering species bulk phase matrices.
void pha_mat_NScatElems (ArrayOfArrayOfTensor6 &pha_mat, ArrayOfArrayOfIndex &ptypes, Matrix &t_ok, const ArrayOfArrayOfSingleScatteringData &scat_data, const Index &stokes_dim, const Vector &T_array, const Matrix &pdir_array, const Matrix &idir_array, const Index &f_index, const Index &t_interp_order)
Phase matrices from all scattering elements.
void pha_mat_1ScatElem (Tensor6View pha_mat, Index &ptype, VectorView t_ok, const SingleScatteringData &ssd, const Vector &T_array, const Matrix &pdir_array, const Matrix &idir_array, const Index &f_start, const Index &t_interp_order)
Preparing phase matrix from one scattering element.
void FouComp_1ScatElem (Tensor7View pha_mat_fou, Index &ptype, VectorView t_ok, const SingleScatteringData &ssd, const Vector &T_array, const Vector &pdir_array, const Vector &idir_array, const Index &f_start, const Index &t_interp_order, const Index &naa_totran)
Preparing phase matrix fourier series components for one scattering element.
void abs_vecTransform (StokesVector &abs_vec_lab, ConstTensor3View abs_vec_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType &ptype, const Numeric &za_sca, const Numeric &aa_sca, const Verbosity &verbosity)
Transformation of absorption vector.
void ext_matTransform (PropagationMatrix &ext_mat_lab, ConstTensor3View ext_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType &ptype, const Numeric &za_sca, const Numeric &aa_sca, const Verbosity &verbosity)
Transformation of extinction matrix.
void pha_matTransform (MatrixView pha_mat_lab, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType &ptype, const Index &za_sca_idx, const Index &aa_sca_idx, const Index &za_inc_idx, const Index &aa_inc_idx, ConstVectorView za_grid, ConstVectorView aa_grid, const Verbosity &verbosity)
Transformation of phase matrix.
void ext_matFromabs_vec (MatrixView ext_mat, ConstVectorView abs_vec, const Index &stokes_dim)
Derive extinction matrix from absorption vector.
Numeric scat_angle (const Numeric &za_sca, const Numeric &aa_sca, const Numeric &za_inc, const Numeric &aa_inc)
Calculates the scattering angle.
void interpolate_scat_angle (VectorView pha_mat_int, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, const Numeric theta)
Interpolate data on the scattering angle.
void pha_mat_labCalc (MatrixView pha_mat_lab, ConstVectorView pha_mat_int, const Numeric &za_sca, const Numeric &aa_sca, const Numeric &za_inc, const Numeric &aa_inc, const Numeric &theta_rad)
Calculate phase matrix in laboratory coordinate system.
ostream & operator<< (ostream &os, const SingleScatteringData &)
ostream & operator<< (ostream &os, const ArrayOfSingleScatteringData &)
ostream & operator<< (ostream &os, const ScatteringMetaData &)
ostream & operator<< (ostream &os, const ArrayOfScatteringMetaData &)
void opt_prop_sum_propmat_clearsky (PropagationMatrix &ext_mat, StokesVector &abs_vec, const PropagationMatrix &propmat_clearsky)
Get optical properties from propmat_clearsky.
PType PTypeFromString (const String &ptype_string)
Convert ptype name to enum value.
PType PType2FromString (const String &ptype_string)
Convert ptype name to enum value.
String PTypeToString (const PType &ptype)
Convert particle type enum value to String.
void ConvertAzimuthallyRandomSingleScatteringData (SingleScatteringData &ssd)
Convert azimuthally-random oriented SingleScatteringData to latest version.
ParticleSSDMethod ParticleSSDMethodFromString (const String &particle_ssdmethod_string)
Convert particle ssd method name to enum value.
String PTypeToString (const ParticleSSDMethod &particle_ssdmethod)
Convert particle type enum value to String.
Variables
const Numeric DEG2RAD
const Numeric RAD2DEG
const Numeric PI
Detailed Description
This file contains definitions and functions related to the optical properties of particles.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@d.nosp@m.lr.d.nosp@m.e
Date
Thu Mar 6 11:29:59 2003
Definition in file optproperties.cc.
Macro Definition Documentation
F11
#define F11 pha_mat_int[0]
Definition at line 56 of file optproperties.cc.
F12
#define F12 pha_mat_int[1]
Definition at line 57 of file optproperties.cc.
F22
#define F22 pha_mat_int[2]
Definition at line 58 of file optproperties.cc.
F33
#define F33 pha_mat_int[3]
Definition at line 59 of file optproperties.cc.
F34
#define F34 pha_mat_int[4]
Definition at line 60 of file optproperties.cc.
F44
#define F44 pha_mat_int[5]
Definition at line 61 of file optproperties.cc.
Function Documentation
abs_vec_SSD2Stokes()
void abs_vec_SSD2Stokes (VectorView abs_vec_stokes, ConstVectorView abs_vec_ssd, const Index & stokes_dim, const Index & ptype)
Absorption vector scat_data to stokes format conversion.
Converts absorption vector from scat_data ptype-dependent compact format to Stokes-notation matrix.
Parameters
[out] abs_vec_stokes absvec in stokes notation (stokes_dim).
[in] abs_vec_ssd absvec at 1f, 1T, 1dir in scat_data compact (vector) format.
[in] stokes_dim as the WSM.
[in] ptype Type of scattering element.
Author
Jana Mendrok
Date
2018-01-15
Definition at line 720 of file optproperties.cc.
References ARTS_ASSERT, PTYPE_AZIMUTH_RND, PTYPE_TOTAL_RND, and ARTS::Var::stokes_dim().
Referenced by opt_prop_1ScatElem().
abs_vecTransform()
void abs_vecTransform (StokesVector & abs_vec_lab, ConstTensor3View abs_vec_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType & ptype, const Numeric & za_sca, const Numeric & aa_sca, const Verbosity & verbosity)
Transformation of absorption vector.
In the single scattering database the data of the absorption vector is stored in different coordinate systems, depending on the type (ptype) of the scattering particle (scattering element).
See AUG for information about the different classifications of the scattering elements.
Output and Input:
Parameters
abs_vec_lab Absorption vector in Laboratory frame. Input:
abs_vec_data Absorption vector in database.
za_datagrid Zenith angle grid in the database.
aa_datagrid Zenith angle grid in the database.
ptype Type of scattering element.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
Author
Claudia Emde
Date
2003-05-24
Definition at line 1551 of file optproperties.cc.
References ARTS_ASSERT, ARTS_USER_ERROR_IF, CREATE_OUT0, gridpos(), interp(), interpweights(), joker, PropagationMatrix::K12(), PropagationMatrix::Kjj(), ConstTensor3View::ncols(), PropagationMatrix::NumberOfFrequencies(), PTYPE_AZIMUTH_RND, PTYPE_GENERAL, PTYPE_TOTAL_RND, PropagationMatrix::SetZero(), ARTS::Var::stokes_dim(), and PropagationMatrix::StokesDimensions().
Referenced by opt_prop_sptFromData(), opt_prop_sptFromMonoData(), and opt_prop_sptFromScat_data().
ConvertAzimuthallyRandomSingleScatteringData()
void ConvertAzimuthallyRandomSingleScatteringData (SingleScatteringData & ssd)
Convert azimuthally-random oriented SingleScatteringData to latest version.
Converts SingleScatteringData to version 3.
Parameters
[in,out] ssd SingleScatteringData
Author
Jana Mendrok
Definition at line 2508 of file optproperties.cc.
References SingleScatteringData::aa_grid, SingleScatteringData::abs_vec_data, ARTS_USER_ERROR_IF, chk_size(), SingleScatteringData::ext_mat_data, SingleScatteringData::f_grid, is_same_within_epsilon(), joker, ConstTensor5View::nbooks(), ConstTensor7View::nbooks(), ConstTensor5View::ncols(), ConstTensor7View::ncols(), ConstVectorView::nelem(), ConstTensor7View::nlibraries(), ConstTensor5View::nrows(), ConstTensor7View::nrows(), ConstTensor5View::nshelves(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), SingleScatteringData::pha_mat_data, Tensor7::resize(), Tensor5::resize(), SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by xml_read_from_stream().
ext_mat_SSD2Stokes()
void ext_mat_SSD2Stokes (MatrixView ext_mat_stokes, ConstVectorView ext_mat_ssd, const Index & stokes_dim, const Index & ptype)
Extinction matrix scat_data to stokes format conversion.
Converts extinction matrix from scat_data ptype-dependent compact format to Stokes-notation matrix.
Parameters
[out] ext_mat_stokes extmat in stokes notation (stokes_dim,stokes_dim).
[in] ext_mat_ssd extmat at 1f, 1T, 1dir in scat_data compact (vector) format.
[in] stokes_dim as the WSM.
[in] ptype type of scattering element.
Author
Jana Mendrok
Date
2018-01-15
Definition at line 672 of file optproperties.cc.
References ARTS_ASSERT, PTYPE_AZIMUTH_RND, PTYPE_TOTAL_RND, and ARTS::Var::stokes_dim().
Referenced by opt_prop_1ScatElem().
ext_matFromabs_vec()
void ext_matFromabs_vec (MatrixView ext_mat, ConstVectorView abs_vec, const Index & stokes_dim)
Derive extinction matrix from absorption vector.
In case, when only absorption of a scattering element shall be considered, and the scattering is neglected, the extinction matrix is set from the absorption vector only.
Extinction matrix is set the following way:
K11 = K22 = K33 = K44 = a1 K12 = K21 = a2 K13 = K31 = a3 K14 = K41 = a4
Other elements remain 0. However, note that the other elements might be supposed to contain non-zero values as well. We couldn't find an appropriate solution yet, though, and these elements are expected to be rather small. Also, using the absorption part only is anyway only a rough approximation. Hence, we deem the assumption of setting the remaining elements to zero reasonable.
Output and Input:
Parameters
ext_mat Extinction matrix. Input:
abs_vec Absorption vector.
stokes_dim as the WSV.
Author
Jana Mendrok
Date
2013-04-30
Definition at line 2040 of file optproperties.cc.
References ARTS::Var::abs_vec(), ARTS_ASSERT, ARTS::Var::ext_mat(), and ARTS::Var::stokes_dim().
ext_matTransform()
void ext_matTransform (PropagationMatrix & ext_mat_lab, ConstTensor3View ext_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType & ptype, const Numeric & za_sca, const Numeric & aa_sca, const Verbosity & verbosity)
Transformation of extinction matrix.
In the single scattering database the data of the extinction matrix is stored in different coordinate systems, depending on the type (ptype) of the scattering particle (scattering element).
See AUG for information about the different classifications of the scattering elements.
Output and Input:
Parameters
ext_mat_lab Extinction matrix in Laboratory frame. Input:
ext_mat_data Extinction matrix in database.
za_datagrid Zenith angle grid in the database.
aa_datagrid Zenith angle grid in the database.
ptype Type of scattering element.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
Author
Claudia Emde
Date
2003-05-24
Definition at line 1647 of file optproperties.cc.
References ARTS_ASSERT, ARTS_USER_ERROR_IF, CREATE_OUT0, gridpos(), interp(), interpweights(), joker, PropagationMatrix::K12(), PropagationMatrix::K34(), PropagationMatrix::Kjj(), ConstTensor3View::ncols(), PropagationMatrix::NumberOfFrequencies(), PTYPE_AZIMUTH_RND, PTYPE_GENERAL, PTYPE_TOTAL_RND, PropagationMatrix::SetZero(), ARTS::Var::stokes_dim(), and PropagationMatrix::StokesDimensions().
Referenced by opt_prop_sptFromData(), opt_prop_sptFromMonoData(), and opt_prop_sptFromScat_data().
FouComp_1ScatElem()
void FouComp_1ScatElem (Tensor7View pha_mat_fou, Index & ptype, VectorView t_ok, const SingleScatteringData & ssd, const Vector & T_array, const Vector & pdir_array, const Vector & idir_array, const Index & f_start, const Index & t_interp_order, const Index & naa_totran)
Preparing phase matrix fourier series components for one scattering element.
Calculates phase matrix fourier series components (currently only mode 0) for one scattering element for one or all frequencies from the single scattering data. Includes interpolation in temperature as well as in incident and scattered stream directions. Handles multiple output temperatures, propagation and incident directions at a time. Temperature interpolation order can be chosen.
Parameters
[out] pha_mat_fou 1-scattering element phase matrix Fourier components (over freq, temp, propagation dir, incident dir).
[out] ptype Type of scattering element.
[out] t_ok Flag whether T-interpol valid (length of T_array).
[in] ssd Single scattering data of one scattering element.
[in] T_array Temperatures to extract pha for.
[in] pdir_array Propagation directions (polar only) to extract Fourier components for.
[in] idir_array Incident directions (polar only) to extract Fourier components for.
[in] f_start Start index of frequency/ies to extract.
[in] t_interp_order Temperature interpolation order.
[in] naa_totran Number of (equidistant) azimuth directions to consider in calculation of Fourier series for totally random orientation elements.
Author
Jana Mendrok
Date
2018-05-01
Definition at line 1301 of file optproperties.cc.
References ARTS::Var::aa_grid(), SingleScatteringData::aa_grid, ARTS_ASSERT, ARTS_USER_ERROR_IF, SingleScatteringData::f_grid, gridpos(), interp(), interpweights(), joker, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstVectorView::nelem(), ConstTensor7View::nlibraries(), nlinspace(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), ARTS::Var::pha_mat(), SingleScatteringData::pha_mat_data, pha_mat_labCalc(), SingleScatteringData::ptype, PTYPE_AZIMUTH_RND, PTYPE_TOTAL_RND, RAD2DEG, Interpolation::reinterp(), scat_angle(), ssd_tinterp_parameters(), ARTS::Var::stokes_dim(), SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
interpolate_scat_angle()
void interpolate_scat_angle (VectorView pha_mat_int, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, const Numeric theta)
Interpolate data on the scattering angle.
This function is used for the transformation of the phase matrix from scattering frame to the laboratory frame for randomly oriented scattering media (case PTYPE_TOTAL_RND).
The scattering angle is calculated from the angles defining the directions of the incoming and scattered radiation. After that the data (which is stored in the data files as a function of the scattering angle) is interpolated on the calculated scattering angle.
Parameters
[out] pha_mat_int Interpolated phase matrix.
[out] theta_rad Scattering angle [rad].
[in] pha_mat_data Phase matrix in database.
[in] za_datagrid Zenith angle grid in the database.
[in] za_sca Zenith angle of scattered direction [rad].
[in] aa_sca Azimuth angle of scattered direction [rad].
[in] za_inc Zenith angle of incoming direction [rad].
[in] aa_inc Azimuth angle of incoming direction [rad].
Author
Claudia Emde
Date
2003-08-19
Definition at line 2134 of file optproperties.cc.
References ARTS_ASSERT, gridpos(), interp(), interpweights(), joker, and ConstTensor5View::ncols().
Referenced by pha_matTransform().
operator<<() [1/4]
ostream& operator<< (ostream & os, const ArrayOfScatteringMetaData & assd)
Definition at line 2369 of file optproperties.cc.
operator<<() [2/4]
ostream& operator<< (ostream & os, const ArrayOfSingleScatteringData & assd)
Definition at line 2359 of file optproperties.cc.
operator<<() [3/4]
ostream& operator<< (ostream & os, const ScatteringMetaData & ssd)
Definition at line 2364 of file optproperties.cc.
operator<<() [4/4]
ostream& operator<< (ostream & os, const SingleScatteringData & ssd)
Definition at line 2354 of file optproperties.cc.
opt_prop_1ScatElem()
void opt_prop_1ScatElem (Tensor5View ext_mat, Tensor4View abs_vec, Index & ptype, VectorView t_ok, const SingleScatteringData & ssd, const Vector & T_array, const Matrix & dir_array, const Index & f_start, const Index & t_interp_order)
Preparing extinction and absorption from one scattering element.
Extracts and prepares extinction matrix and absorption vector data for one scattering element for one or all frequencies from the single scattering data. Includes interpolation in temperature and to propagation direction. Handles multiple output temperatures and propagation directions at a time. Temperature interpolation order can be chosen.
Parameters
[out] ext_mat 1-scattering element extinction matrix (over freq, temp, propagation direction).
[out] abs_vec 1-scattering element absorption vector (over freq, temp, propagation direction).
[out] ptype Type of scattering element.
[out] t_ok Flag whether T-interpol valid (length of T_array).
[in] ssd Single scattering data of one scattering element.
[in] T_array Temperatures to extract ext/abs for.
[in] dir_array Propagation directions to extract ext/abs for (as pairs of zenith and azimuth angle per direction).
[in] f_start Start index of frequency/ies to extract.
[in] t_interp_order Temperature interpolation order.
Author
Jana Mendrok
Date
2018-01-15
Definition at line 422 of file optproperties.cc.
References ARTS::Var::abs_vec(), SingleScatteringData::abs_vec_data, abs_vec_SSD2Stokes(), ARTS_ASSERT, ARTS::Var::ext_mat(), SingleScatteringData::ext_mat_data, ext_mat_SSD2Stokes(), SingleScatteringData::f_grid, gridpos(), interp(), interpweights(), joker, ConstTensor5View::ncols(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), SingleScatteringData::ptype, PTYPE_AZIMUTH_RND, PTYPE_TOTAL_RND, Interpolation::reinterp(), ssd_tinterp_parameters(), ARTS::Var::stokes_dim(), SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by opt_prop_NScatElems().
opt_prop_Bulk()
void opt_prop_Bulk (Tensor5 & ext_mat, Tensor4 & abs_vec, Index & ptype, const ArrayOfTensor5 & ext_mat_ss, const ArrayOfTensor4 & abs_vec_ss, const ArrayOfIndex & ptypes_ss)
one-line descript
Descript/Doc
Parameters
[out] name desc.
[in] name desc.
Author
Jana Mendrok
Date
2018-01-15 Scattering species bulk extinction and absorption.
Derives bulk properties from per-scat-species bulk properties.
Ptype is defined by the most complex ptype of the individual scattering elements.
Parameters
[out] ext_mat Bulk extinction matrix (over freq, temp/location, propagation direction).
[out] abs_vec Bulk absorption vector (over freq, temp/location, propagation direction).
[out] ptype Bulk ptype.
[in] ext_mat_ss Bulk extinction matrix per scattering species (over freq, temp/location, propagation direction).
[in] abs_vec_ss Bulk absorption vector per scattering species (over freq, temp/location, propagation direction).
[in] ptypes_ss Scattering species ptypes.
Author
Jana Mendrok
Date
2018-01-16
Definition at line 103 of file optproperties.cc.
References ARTS::Var::abs_vec(), ARTS_ASSERT, ARTS::Var::ext_mat(), max, and Array< base >::nelem().
Referenced by cloudy_rt_vars_at_gp(), get_paroptprop(), and get_stepwise_scattersky_propmat().
opt_prop_NScatElems()
void opt_prop_NScatElems (ArrayOfArrayOfTensor5 & ext_mat, ArrayOfArrayOfTensor4 & abs_vec, ArrayOfArrayOfIndex & ptypes, Matrix & t_ok, const ArrayOfArrayOfSingleScatteringData & scat_data, const Index & stokes_dim, const Vector & T_array, const Matrix & dir_array, const Index & f_index, const Index & t_interp_order)
Extinction and absorption from all scattering elements.
Derives temperature and direction interpolated extinction matrices and absorption vectors for all scattering elements present in scat_data.
ATTENTION: If scat_data has only one freq point, f_index=-1 (i.e. all) extracts only this one freq point. To duplicate that as needed if f_grid has more freqs is TASK of the CALLING METHOD!
Loops over opt_prop_1ScatElem and packs its output into all-scat-elements containers.
Parameters
[out] ext_mat Extinction matrix (over scat elements, freq, temp, propagation direction).
[out] abs_vec Absorption vector (over scat elements, freq, temp, propagation direction).
[out] ptypes Scattering element types.
[out] t_ok Flag whether T-interpol valid (over scat elements, temp).
[in] scat_data as the WSV.
[in] stokes_dim as the WSV.
[in] T_array Temperatures to extract ext/abs for.
[in] dir_array Propagation directions to extract ext/abs for (as pairs of zenith and azimuth angle per direction).
[in] f_index Index of frequency to extract. -1 extracts data for all freqs available in ssd.
[in] t_interp_order Temperature interpolation order.
Author
Jana Mendrok
Date
2018-01-16
Definition at line 248 of file optproperties.cc.
References ARTS::Var::abs_vec(), ARTS_ASSERT, ARTS::Var::ext_mat(), ARTS::Var::f_index(), joker, ConstVectorView::nelem(), ConstMatrixView::nrows(), opt_prop_1ScatElem(), Matrix::resize(), ARTS::Var::scat_data(), ARTS::Var::stokes_dim(), and TotalNumberOfElements().
Referenced by cloudy_rt_vars_at_gp(), get_paroptprop(), get_stepwise_scattersky_propmat(), and propmat_clearskyAddParticles().
opt_prop_ScatSpecBulk()
void opt_prop_ScatSpecBulk (ArrayOfTensor5 & ext_mat, ArrayOfTensor4 & abs_vec, ArrayOfIndex & ptype, const ArrayOfArrayOfTensor5 & ext_mat_se, const ArrayOfArrayOfTensor4 & abs_vec_se, const ArrayOfArrayOfIndex & ptypes_se, ConstMatrixView pnds, ConstMatrixView t_ok)
Scattering species bulk extinction and absorption.
Derives bulk properties separately per scattering species from (input) per-scattering-elements extinction and absorption given over frequency, temperature and propagation direction.
Temperature dimension in per-scattering-element properties is assumed to correspond to column dimension of pnds (leading dimension, i.e. row, corresponds to scattering elements).
Ptype of each scattering species is defined by the most complex ptype of the individual scattering elements within this species.
Parameters
[out] ext_mat Bulk extinction matrix per scattering species (over freq, temp/location, propagation direction).
[out] abs_vec Bulk absorption vector per scattering species (over freq, temp/location, propagation direction).
[out] ptype Scattering species ptypes.
[in] ext_mat_se Extinction matrix per scattering element.
[in] abs_vec_se Absorption vector per scattering element.
[in] ptypes_se Scattering element types.
[in] pnds Particle number density vectors (multiple locations).
Author
Jana Mendrok
Date
2018-01-16
Definition at line 149 of file optproperties.cc.
References ARTS::Var::abs_vec(), ARTS_ASSERT, ARTS_USER_ERROR, ARTS::Var::ext_mat(), joker, max, ARTS::Var::nbooks(), ConstMatrixView::ncols(), Array< base >::nelem(), Absorption::nelem(), ARTS::Var::npages(), ConstMatrixView::nrows(), ARTS::Var::stokes_dim(), and TotalNumberOfElements().
Referenced by cloudy_rt_vars_at_gp(), get_paroptprop(), and get_stepwise_scattersky_propmat().
opt_prop_sum_propmat_clearsky()
void opt_prop_sum_propmat_clearsky (PropagationMatrix & ext_mat, StokesVector & abs_vec, const PropagationMatrix & propmat_clearsky)
Get optical properties from propmat_clearsky.
This turns propmat_clearsky into the extinction matrix and absorption vector for use when these are important.
Internal function to replace the old opt_prop_gas_agenda.
Output and Input:
Parameters
ext_mat Extinction matrix.
abs_vec Absorption vector. Input:
propmat_clearsky as the WSV.
Author
Richard Larsson
Date
2012-07-24
Definition at line 2390 of file optproperties.cc.
References ARTS::Var::abs_vec(), ARTS::Var::ext_mat(), ARTS::Var::propmat_clearsky(), and ARTS::Var::stokes_dim().
Referenced by clear_rt_vars_at_gp(), and cloudy_rt_vars_at_gp().
ParticleSSDMethodFromString()
ParticleSSDMethod ParticleSSDMethodFromString (const String & particle_ssdmethod_string)
Convert particle ssd method name to enum value.
Returns the ParticleSSDMethod enum value for the given String.
Parameters
[in] particle_ssdmethod_string Particle SSD method name
Returns
ParticleSSDMethod enum value
Author
Oliver Lemke
Definition at line 2616 of file optproperties.cc.
References ARTS_USER_ERROR, and PARTICLE_SSDMETHOD_TMATRIX.
pha_mat_1ScatElem()
void pha_mat_1ScatElem (Tensor6View pha_mat, Index & ptype, VectorView t_ok, const SingleScatteringData & ssd, const Vector & T_array, const Matrix & pdir_array, const Matrix & idir_array, const Index & f_start, const Index & t_interp_order)
Preparing phase matrix from one scattering element.
Extracts and prepares phase matrix data for one scattering element for one or all frequencies from the single scattering data. Includes interpolation in temperature as well as in incident and to propagation direction. Handles multiple output temperatures, propagation and incident directions at a time. Temperature interpolation order can be chosen.
Parameters
[out] pha_mat 1-scattering element phase matrix (over freq, temp, propagation dir, incident dir).
[out] ptype Type of scattering element.
[out] t_ok Flag whether T-interpol valid (length of T_array).
[in] ssd Single scattering data of one scattering element.
[in] T_array Temperatures to extract pha for.
[in] pdir_array Propagation directions to extract pha for (as pairs of zenith and azimuth angle per direction).
[in] idir_array Inident directions to extract pha for (as pairs of zenith and azimuth angle per direction).
[in] f_start Start index of frequency/ies to extract.
[in] t_interp_order Temperature interpolation order.
Author
Jana Mendrok
Date
2018-03-22
Definition at line 967 of file optproperties.cc.
References SingleScatteringData::aa_grid, abs, ARTS_ASSERT, SingleScatteringData::f_grid, gridpos(), interp(), interpweights(), joker, ConstVectorView::nelem(), ConstMatrixView::nrows(), ARTS::Var::pha_mat(), SingleScatteringData::pha_mat_data, pha_mat_labCalc(), SingleScatteringData::ptype, PTYPE_AZIMUTH_RND, PTYPE_TOTAL_RND, RAD2DEG, Interpolation::reinterp(), scat_angle(), ssd_tinterp_parameters(), ARTS::Var::stokes_dim(), SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by get_stepwise_scattersky_source(), and pha_mat_NScatElems().
pha_mat_Bulk()
void pha_mat_Bulk (Tensor6 & pha_mat, Index & ptype, const ArrayOfTensor6 & pha_mat_ss, const ArrayOfIndex & ptypes_ss)
Scattering species bulk phase matrix.
Derives bulk properties from per-scat-species bulk properties.
Ptype is defined by the most complex ptype of the individual scattering elements.
Parameters
[out] pha_mat Bulk phase matrix (over freq, temp/location, propagation direction, incident direction).
[out] ptype Bulk ptype.
[in] pha_mat_ss Bulk phase matrix per scattering species (over freq, temp/location, propagation direction, incident direction).
[in] ptypes_ss Scattering species ptypes.
Author
Jana Mendrok
Date
2018-03-24
Definition at line 757 of file optproperties.cc.
References max, Array< base >::nelem(), and ARTS::Var::pha_mat().
Referenced by get_parZ(), and Sample_los().
pha_mat_labCalc()
void pha_mat_labCalc (MatrixView pha_mat_lab, ConstVectorView pha_mat_int, const Numeric & za_sca, const Numeric & aa_sca, const Numeric & za_inc, const Numeric & aa_inc, const Numeric & theta_rad)
Calculate phase matrix in laboratory coordinate system.
Transformation function for the phase matrix for the case of randomly oriented particles (case PTYPE_TOTAL_RND).
Some of the formulas can be found in
Mishchenkho: "Scattering, Absorption and Emission of Light by Small Particles", Cambridge University Press, 2002 Capter 4
The full set of formulas will be documented in AUG.
Output and Input:
Parameters
pha_mat_lab Phase matrix in laboratory frame. Input:
pha_mat_int Interpolated phase matrix.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
za_inc Zenith angle of incoming direction.
aa_inc Azimuth angle of incoming direction.
theta_rad Scattering angle [rad].
Author
Claudia Emde
Date
2003-05-13
Definition at line 2178 of file optproperties.cc.
References ARTS_USER_ERROR_IF, DEG2RAD, F11, ConstMatrixView::ncols(), and ARTS::Var::stokes_dim().
Referenced by FouComp_1ScatElem(), pha_mat_1ScatElem(), and pha_matTransform().
pha_mat_NScatElems()
void pha_mat_NScatElems (ArrayOfArrayOfTensor6 & pha_mat, ArrayOfArrayOfIndex & ptypes, Matrix & t_ok, const ArrayOfArrayOfSingleScatteringData & scat_data, const Index & stokes_dim, const Vector & T_array, const Matrix & pdir_array, const Matrix & idir_array, const Index & f_index, const Index & t_interp_order)
Phase matrices from all scattering elements.
Derives temperature and direction interpolated phase matrices for all scattering elements present in scat_data.
ATTENTION: If scat_data has only one freq point, f_index=-1 (i.e. all) extracts only this one freq point. To duplicate that as needed if f_grid has more freqs is TASK of the CALLING METHOD!
Loops over pha_mat_1ScatElem and packs its output into all-scat-elements containers.
Parameters
[out] pha_mat Phase matrix (over scat elements, freq, temp, propagation direction, incident direction).
[out] ptypes Scattering element types.
[out] t_ok Flag whether T-interpol valid (over scat elements, temp).
[in] scat_data as the WSV.
[in] stokes_dim as the WSV.
[in] T_array Temperatures to extract pha for.
[in] pdir_array Propagation directions to extract pha for (as pairs of zenith and azimuth angle per direction).
[in] idir_array Incident directions to extract pha for (as pairs of zenith and azimuth angle per direction).
[in] f_index Index of frequency to extract. -1 extracts data for all freqs available in ssd.
[in] t_interp_order Temperature interpolation order.
Author
Jana Mendrok
Date
2018-03-24
Definition at line 882 of file optproperties.cc.
References ARTS_ASSERT, ARTS::Var::f_index(), joker, ConstVectorView::nelem(), ConstMatrixView::nrows(), ARTS::Var::pha_mat(), pha_mat_1ScatElem(), Matrix::resize(), ARTS::Var::scat_data(), ARTS::Var::stokes_dim(), and TotalNumberOfElements().
Referenced by get_parZ(), and Sample_los().
pha_mat_ScatSpecBulk()
void pha_mat_ScatSpecBulk (ArrayOfTensor6 & pha_mat, ArrayOfIndex & ptype, const ArrayOfArrayOfTensor6 & pha_mat_se, const ArrayOfArrayOfIndex & ptypes_se, ConstMatrixView pnds, ConstMatrixView t_ok)
Scattering species bulk phase matrices.
Derives bulk properties separately per scattering species from (input) per-scattering-elements phase matrices given over frequency, temperature and propagation direction.
Temperature dimension in per-scattering-element properties is assumed to correspond to column dimension of pnds (leading dimension, i.e. row, corresponds to scattering elements).
Ptype of each scattering species is defined by the most complex ptype of the individual scattering elements within this species.
Parameters
[out] pha_mat Bulk phase matrix per scattering species (over freq, temp/location, propagation direction, incident direction).
[out] ptype Scattering species ptypes.
[in] pha_mat_se Phase matrix per scattering element.
[in] ptypes_se Scattering element types.
[in] pnds Particle number density vectors (multiple locations).
Author
Jana Mendrok
Date
2018-03-24
Definition at line 795 of file optproperties.cc.
References ARTS_ASSERT, ARTS_USER_ERROR, joker, max, ConstMatrixView::ncols(), Array< base >::nelem(), ConstMatrixView::nrows(), ARTS::Var::nshelves(), ARTS::Var::pha_mat(), ARTS::Var::stokes_dim(), and TotalNumberOfElements().
Referenced by get_parZ(), and Sample_los().
pha_matTransform()
void pha_matTransform (MatrixView pha_mat_lab, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const PType & ptype, const Index & za_sca_idx, const Index & aa_sca_idx, const Index & za_inc_idx, const Index & aa_inc_idx, ConstVectorView za_grid, ConstVectorView aa_grid, const Verbosity & verbosity)
Transformation of phase matrix.
In the single scattering database the data of the phase matrix is stored in different coordinate systems, depending on the type (ptype) of the scattering particle (scattering element).
See AUG for information about the different classifications of the scattering elements.
Parameters
[in,out] pha_mat_lab Phase matrix in Laboratory frame.
[in] pha_mat_data Phase matrix in database.
[in] za_datagrid Zenith angle grid in the database.
[in] aa_datagrid Zenith angle grid in the database.
[in] ptype Type of scattering element.
[in] za_sca_idx Index of zenith angle of scattered direction within za_grid.
[in] aa_sca_idx Index of azimuth angle of scattered direction within aa_grid.
[in] za_inc_idx Index of zenith angle of incoming direction within za_grid.
[in] aa_inc_idx Index of azimuth angle of incoming direction within aa_grid.
[in] za_grid Grid of zenith angles to extract pha_mat for.
[in] aa_grid Grid of azimuth angles to extract pha_mat for.
Author
Claudia Emde
Date
2003-08-19
Definition at line 1765 of file optproperties.cc.
References ARTS::Var::aa_grid(), abs, ARTS_ASSERT, ARTS_USER_ERROR_IF, CREATE_OUT0, gridpos(), interp(), interpolate_scat_angle(), interpweights(), joker, ConstTensor5View::ncols(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstTensor5View::npages(), pha_mat_labCalc(), PTYPE_AZIMUTH_RND, PTYPE_GENERAL, PTYPE_TOTAL_RND, RAD2DEG, scat_angle(), ARTS::Var::stokes_dim(), and ARTS::Var::za_grid().
Referenced by DoitScatteringDataPrepare(), pha_mat_sptFromData(), pha_mat_sptFromMonoData(), and pha_mat_sptFromScat_data().
PType2FromString()
PType PType2FromString (const String & ptype_string)
Convert ptype name to enum value.
Returns the PType enum value for the given String.
This is the conversion for SingleScatteringData version 2.
Parameters
[in] ptype_string Particle type name
Returns
PType enum value
Author
Oliver Lemke
Definition at line 2450 of file optproperties.cc.
References ARTS_USER_ERROR, PTYPE_AZIMUTH_RND, PTYPE_GENERAL, and PTYPE_TOTAL_RND.
Referenced by xml_read_from_stream().
PTypeFromString()
PType PTypeFromString (const String & ptype_string)
Convert ptype name to enum value.
Returns the PType enum value for the given String.
This is the conversion for SingleScatteringData version 2.
Parameters
[in] ptype_string Particle type name
Returns
PType enum value
Author
Oliver Lemke
Definition at line 2421 of file optproperties.cc.
References ARTS_USER_ERROR, PTYPE_AZIMUTH_RND, PTYPE_GENERAL, and PTYPE_TOTAL_RND.
Referenced by scat_data_singleTmatrix(), and xml_read_from_stream().
PTypeToString() [1/2]
String PTypeToString (const ParticleSSDMethod & particle_ssdmethod)
Convert particle type enum value to String.
Returns the PType enum value for the given String.
Parameters
[in] ptype Particle type
Returns
String representation of ParticleSSDMethod
Author
Oliver Lemke
Definition at line 2640 of file optproperties.cc.
References ARTS_USER_ERROR, and PARTICLE_SSDMETHOD_TMATRIX.
PTypeToString() [2/2]
String PTypeToString (const PType & ptype)
Convert particle type enum value to String.
Returns the PType enum value for the given String.
Parameters
[in] ptype Particle type
Returns
String representation of PType
Author
Oliver Lemke
Definition at line 2477 of file optproperties.cc.
References ARTS_USER_ERROR, PTYPE_AZIMUTH_RND, PTYPE_GENERAL, and PTYPE_TOTAL_RND.
Referenced by check_disort_input(), and xml_write_to_stream().
scat_angle()
Numeric scat_angle (const Numeric & za_sca, const Numeric & aa_sca, const Numeric & za_inc, const Numeric & aa_inc)
Calculates the scattering angle.
The scattering angle is calculated from the angles defining the directions of the incoming and scattered radiation.
Parameters
[out] theta_rad Scattering angle [rad].
[in] za_sca Zenith angle of scattered direction [rad].
[in] aa_sca Azimuth angle of scattered direction [rad].
[in] za_inc Zenith angle of incoming direction [rad].
[in] aa_inc Azimuth angle of incoming direction [rad].
Author
Jana Mendrok (moved out from interpolate_scat_angle by C.Emde)
Date
2018-03-23
Definition at line 2075 of file optproperties.cc.
Referenced by FouComp_1ScatElem(), pha_mat_1ScatElem(), and pha_matTransform().
ssd_tinterp_parameters()
ArrayOfLagrangeInterpolation ssd_tinterp_parameters (VectorView t_ok, Index & this_T_interp_order, ConstVectorView T_grid, const Vector & T_array, const Index & t_interp_order)
Determine T-interpol parameters for a specific scattering element.
Determine T-interpol order as well as interpol positions and weights (they are the same for all directions (and freqs), ie it is sufficient to calculate them once).
Parameters
[out] t_ok Flag whether T-interpol valid (length of T_array).
[out] this_T_interp_order Temperature interpolation order adjusted according to data availability.
[out] T_lag GridPos data for temperature interpolation.
[out] T_itw Interpolation weights for temperature interpolation.
[in] T_grid Single scattering data temperature grid.
[in] T_array Temperatures to extract single scattering data for.
[in] t_interp_order Requested temperature interpolation order.
Author
Jana Mendrok
Date
2018-05-01
Definition at line 329 of file optproperties.cc.
References chk_interpolation_grids(), Interpolation::LagrangeVector(), min, and ConstVectorView::nelem().
Referenced by FouComp_1ScatElem(), opt_prop_1ScatElem(), and pha_mat_1ScatElem().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by pha_mat_labCalc().
PI
const Numeric PI extern
RAD2DEG
const Numeric RAD2DEG extern
Referenced by FouComp_1ScatElem(), pha_mat_1ScatElem(), and pha_matTransform().