ARTS: parameters.h File Reference
parameters.h File Reference
This file contains header information for the dealing with command line parameters.
#include "array.h"
#include "mystring.h"
Classes
class Parameters
Structure to hold all command line Parameters.
Functions
bool get_parameters (int argc, char **argv)
Get the command line parameters.
Detailed Description
This file contains header information for the dealing with command line parameters.
Author
Stefan Buehler
Date
2001-07-24
Definition in file parameters.h.
Function Documentation
get_parameters()
bool get_parameters (int argc, char ** argv)
Get the command line parameters.
They are stored in the global variable parameters which is a structure of type Parameters. If needed, this variable should be declared like this:
extern const Parameters parameters
Returns
false=ok, true=error
Parameters
argc Number of command line parameters
argv Values of command line parameters
Author
Stefan Buehler
Version
1
Definition at line 71 of file parameters.cc.
References ARTS_DEFAULT_INCLUDE_DIR, arts_exit(), Parameters::basename, Parameters::baseurl, c, Options::char, Parameters::check_docs, Parameters::controlfiles, Parameters::daemon, Parameters::datapath, Parameters::describe, Parameters::docserver, get_dirname(), getopt_long(), Parameters::groups, Parameters::gui, option::has_arg, Parameters::help, Parameters::helptext, Parameters::includepath, Parameters::input, Parameters::methods, option::name, my_basic_string< charT >::nelem(), Array< base >::nelem(), no_argument, my_basic_string< char >::npos, Parameters::numthreads, optarg, optind, optional_argument, Parameters::outdir, parameters, parse_path_from_environment(), Parameters::plain, Parameters::reporting, required_argument, Parameters::usage, option::val, Parameters::version, and Parameters::workspacevariables.
Referenced by main().