ARTS: parameters.cc File Reference
parameters.cc File Reference
This file contains the function get_parameters, which reads command line parameters.
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include "arts.h"
#include <arts_getopt.h>
#include "file.h"
#include "parameters.h"
Functions
void parse_path_from_environment (String envvar, ArrayOfString &paths)
Parse path environment variable.
bool get_parameters (int argc, char **argv)
Get the command line parameters.
Variables
Parameters parameters
Holds the command line parameters.
Detailed Description
This file contains the function get_parameters, which reads command line parameters.
Standard GNU functions are used for this.
Author
Stefan Buehler
Date
2001-07-24
Definition in file parameters.cc.
Function Documentation
get_parameters()
bool get_parameters (int argc, char ** argv)
Get the command line parameters.
They are stored in the global variable parameters which is a structure of type Parameters. If needed, this variable should be declared like this:
extern const Parameters parameters
Returns
false=ok, true=error
Parameters
argc Number of command line parameters
argv Values of command line parameters
Author
Stefan Buehler
Version
1
Definition at line 71 of file parameters.cc.
References ARTS_DEFAULT_INCLUDE_DIR, arts_exit(), Parameters::basename, Parameters::baseurl, c, Options::char, Parameters::check_docs, Parameters::controlfiles, Parameters::daemon, Parameters::datapath, Parameters::describe, Parameters::docserver, get_dirname(), getopt_long(), Parameters::groups, Parameters::gui, option::has_arg, Parameters::help, Parameters::helptext, Parameters::includepath, Parameters::input, Parameters::methods, option::name, my_basic_string< charT >::nelem(), Array< base >::nelem(), no_argument, my_basic_string< char >::npos, Parameters::numthreads, optarg, optind, optional_argument, Parameters::outdir, parameters, parse_path_from_environment(), Parameters::plain, Parameters::reporting, required_argument, Parameters::usage, option::val, Parameters::version, and Parameters::workspacevariables.
Referenced by main().
parse_path_from_environment()
void parse_path_from_environment (String envvar, ArrayOfString & paths)
Parse path environment variable.
Parse a colon separated list of paths from the given environment variable into an ArrayOfString.
Parameters
[in] envvar Name of environment variable.
[out] paths ArrayOfString of paths.
Author
Oliver Lemke
Definition at line 53 of file parameters.cc.
References my_basic_string< char >::npos.
Referenced by get_parameters().
Variable Documentation
parameters
Parameters parameters
Holds the command line parameters.
Definition at line 41 of file parameters.cc.
Referenced by add_basedir(), data_path_pop(), data_path_push(), find_xml_file(), find_xml_file_existence(), get_parameters(), include_path_pop(), include_path_push(), main(), open_input_file(), option_methods(), option_workspacevariables(), ArtsParser::parse_agenda(), and xsec_continuum_tag().