ARTS: partition_function_data.cc File Reference
partition_function_data.cc File Reference
Coefficients for 3rd order polynomial of partition function in temperature, plus safety check.
#include "absorption.h"
#include "arts.h"
Namespaces
global_data
Some #defines for better readability
#define Qcoeff(...) { __VA_ARGS__ }
void next_species (Array< SpeciesRecord >::iterator &is, Array< IsotopologueRecord >::iterator &ii, String name)
Define partition function coefficients lookup data.
void iso (Array< IsotopologueRecord >::iterator &ii, String name, const ArrayOfNumeric &coeff, const ArrayOfNumeric &temp_range, const Index &coefftype)
Initialize isotopologue and move iterator to next one.
void define_partition_species_data ()
Detailed Description
Coefficients for 3rd order polynomial of partition function in temperature, plus safety check.
This file contains the definition of this function and a safety check of the input. You have to add the coefficients of new species here, along with the new entry into the species_data (file species_data.cc) record, if you want to extend the capability of ARTS. These entries have to be in the same order, which is assured by check_q_data.
This is the file from arts-1-0, back-ported to arts-1-1.
Author
Axel von Engeln, C. Verdes,
Date
2000-08-21
Definition in file partition_function_data.cc.
Macro Definition Documentation
Qcoeff
#define Qcoeff (...) { __VA_ARGS__ }
Definition at line 68 of file partition_function_data.cc.
Function Documentation
define_partition_species_data()
void define_partition_species_data ()
Definition at line 188 of file partition_function_data.cc.
References ARTS_ASSERT, iso(), next_species(), IsotopologueRecord::PF_FROMCOEFF, Qcoeff, and global_data::species_data.
Referenced by define_species_data().
iso()
void iso (Array< IsotopologueRecord >::iterator & ii, String name, const ArrayOfNumeric & coeff, const ArrayOfNumeric & temp_range, const Index & coefftype)
Initialize isotopologue and move iterator to next one.
Definition at line 1797 of file partition_function_data.cc.
References ARTS_ASSERT.
Referenced by abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), all_species(), checkIsotopologueRatios(), define_partition_species_data(), SpeciesAuxData::InitFromSpeciesData(), ARTS::Species::isAr_8(), ARTS::Species::isBrO_16(), ARTS::Species::isBrO_96(), ARTS::Species::isC2H2_1221(), ARTS::Species::isC2H2_1222(), ARTS::Species::isC2H2_1231(), ARTS::Species::isC2H4_221(), ARTS::Species::isC2H4_231(), ARTS::Species::isC2H6_1221(), ARTS::Species::isC2H6_1231(), ARTS::Species::isC2N2_4224(), ARTS::Species::isC3H8_21(), ARTS::Species::isC4H2_2211(), ARTS::Species::isCF4_29(), ARTS::Species::isCH3Br_211(), ARTS::Species::isCH3Br_219(), ARTS::Species::isCH3Cl_215(), ARTS::Species::isCH3Cl_217(), ARTS::Species::isCH3CN_211124(), ARTS::Species::isCH3CN_211125(), ARTS::Species::isCH3CN_211134(), ARTS::Species::isCH3CN_211224(), ARTS::Species::isCH3CN_311124(), ARTS::Species::isCH3OH_2161(), ARTS::Species::isCH4_211(), ARTS::Species::isCH4_212(), ARTS::Species::isCH4_311(), ARTS::Species::isCH4_312(), ARTS::Species::isCl2O2_565(), ARTS::Species::isCl2O2_765(), ARTS::Species::isClO_56(), ARTS::Species::isClO_76(), ARTS::Species::isClONO2_5646(), ARTS::Species::isClONO2_7646(), ARTS::Species::isCO2_626(), ARTS::Species::isCO2_627(), ARTS::Species::isCO2_628(), ARTS::Species::isCO2_636(), ARTS::Species::isCO2_637(), ARTS::Species::isCO2_638(), ARTS::Species::isCO2_727(), ARTS::Species::isCO2_728(), ARTS::Species::isCO2_737(), ARTS::Species::isCO2_828(), ARTS::Species::isCO2_837(), ARTS::Species::isCO2_838(), ARTS::Species::isCO2_CKD241(), ARTS::Species::isCO2_CKDMT100(), ARTS::Species::isCO2_CKDMT252(), ARTS::Species::isCO2_ForeignContHo66(), ARTS::Species::isCO2_ForeignContPWR93(), ARTS::Species::isCO2_SelfContHo66(), ARTS::Species::isCO2_SelfContPWR93(), ARTS::Species::isCO_26(), ARTS::Species::isCO_27(), ARTS::Species::isCO_28(), ARTS::Species::isCO_36(), ARTS::Species::isCO_37(), ARTS::Species::isCO_38(), ARTS::Species::isCOCl2_2655(), ARTS::Species::isCOCl2_2657(), ARTS::Species::isCOF2_269(), ARTS::Species::isCOF2_369(), ARTS::Species::isCS2_222(), ARTS::Species::isCS2_223(), ARTS::Species::isCS2_224(), ARTS::Species::isCS2_232(), ARTS::Species::isCS_22(), ARTS::Species::isCS_23(), ARTS::Species::isCS_24(), ARTS::Species::isCS_32(), ARTS::Species::isH2_11(), ARTS::Species::isH2_12(), ARTS::Species::isH2CO_1126(), ARTS::Species::isH2CO_1128(), ARTS::Species::isH2CO_1136(), ARTS::Species::isH2CO_1226(), ARTS::Species::isH2CO_2226(), ARTS::Species::isH2O2_1661(), ARTS::Species::isH2O_161(), ARTS::Species::isH2O_162(), ARTS::Species::isH2O_171(), ARTS::Species::isH2O_172(), ARTS::Species::isH2O_181(), ARTS::Species::isH2O_182(), ARTS::Species::isH2O_262(), ARTS::Species::isH2O_ContMPM93(), ARTS::Species::isH2O_CP98(), ARTS::Species::isH2O_ForeignContATM01(), ARTS::Species::isH2O_ForeignContCKD222(), ARTS::Species::isH2O_ForeignContCKD24(), ARTS::Species::isH2O_ForeignContCKD242(), ARTS::Species::isH2O_ForeignContCKDMT100(), ARTS::Species::isH2O_ForeignContCKDMT252(), ARTS::Species::isH2O_ForeignContCKDMT320(), ARTS::Species::isH2O_ForeignContMaTippingType(), ARTS::Species::isH2O_ForeignContStandardType(), ARTS::Species::isH2O_MPM87(), ARTS::Species::isH2O_MPM89(), ARTS::Species::isH2O_MPM93(), ARTS::Species::isH2O_PWR98(), ARTS::Species::isH2O_SelfContCKD222(), ARTS::Species::isH2O_SelfContCKD24(), ARTS::Species::isH2O_SelfContCKD242(), ARTS::Species::isH2O_SelfContCKDMT100(), ARTS::Species::isH2O_SelfContCKDMT252(), ARTS::Species::isH2O_SelfContCKDMT320(), ARTS::Species::isH2O_SelfContStandardType(), ARTS::Species::isH2S_121(), ARTS::Species::isH2S_122(), ARTS::Species::isH2S_131(), ARTS::Species::isH2S_141(), ARTS::Species::isH2SO4_126(), ARTS::Species::isH_1(), ARTS::Species::isHBr_11(), ARTS::Species::isHBr_19(), ARTS::Species::isHBr_21(), ARTS::Species::isHBr_29(), ARTS::Species::isHC3N_12224(), ARTS::Species::isHC3N_12225(), ARTS::Species::isHC3N_12234(), ARTS::Species::isHC3N_12324(), ARTS::Species::isHC3N_13224(), ARTS::Species::isHC3N_22224(), ARTS::Species::isHCl_15(), ARTS::Species::isHCl_17(), ARTS::Species::isHCl_25(), ARTS::Species::isHCl_27(), ARTS::Species::isHCN_124(), ARTS::Species::isHCN_125(), ARTS::Species::isHCN_134(), ARTS::Species::isHCN_224(), ARTS::Species::isHCOOH_1261(), ARTS::Species::isHCOOH_1262(), ARTS::Species::isHCOOH_1361(), ARTS::Species::isHCOOH_2261(), ARTS::Species::isHe_4(), ARTS::Species::isHF_19(), ARTS::Species::isHF_29(), ARTS::Species::isHI_17(), ARTS::Species::isHI_27(), ARTS::Species::isHNC_142(), ARTS::Species::isHNC_143(), ARTS::Species::isHNC_152(), ARTS::Species::isHNC_242(), ARTS::Species::isHNO3_146(), ARTS::Species::isHNO3_156(), ARTS::Species::isHO2_166(), ARTS::Species::isHOBr_161(), ARTS::Species::isHOBr_169(), ARTS::Species::isHOCl_165(), ARTS::Species::isHOCl_167(), ARTS::Species::isicecloud_MPM93(), ARTS::Species::isliquidcloud_ELL07(), ARTS::Species::isliquidcloud_MPM93(), ARTS::Species::isN2_44(), ARTS::Species::isN2_45(), ARTS::Species::isN2_CIAfunCKDMT100(), ARTS::Species::isN2_CIAfunCKDMT252(), ARTS::Species::isN2_CIArotCKDMT100(), ARTS::Species::isN2_CIArotCKDMT252(), ARTS::Species::isN2_DryContATM01(), ARTS::Species::isN2_SelfContBorysow(), ARTS::Species::isN2_SelfContMPM93(), ARTS::Species::isN2_SelfContPWR93(), ARTS::Species::isN2_SelfContStandardType(), ARTS::Species::isN2O_446(), ARTS::Species::isN2O_447(), ARTS::Species::isN2O_448(), ARTS::Species::isN2O_456(), ARTS::Species::isN2O_546(), ARTS::Species::isNH3_4111(), ARTS::Species::isNH3_4112(), ARTS::Species::isNH3_5111(), ARTS::Species::isNO2_646(), ARTS::Species::isNO2_656(), ARTS::Species::isNO_46(), ARTS::Species::isNO_48(), ARTS::Species::isNO_56(), ARTS::Species::isNO_plus_46(), ARTS::Species::isO2_66(), ARTS::Species::isO2_67(), ARTS::Species::isO2_68(), ARTS::Species::isO2_CIAfunCKDMT100(), ARTS::Species::isO2_MPM2020(), ARTS::Species::isO2_MPM85(), ARTS::Species::isO2_MPM87(), ARTS::Species::isO2_MPM89(), ARTS::Species::isO2_MPM92(), ARTS::Species::isO2_MPM93(), ARTS::Species::isO2_PWR88(), ARTS::Species::isO2_PWR93(), ARTS::Species::isO2_PWR98(), ARTS::Species::isO2_SelfContMPM93(), ARTS::Species::isO2_SelfContPWR93(), ARTS::Species::isO2_SelfContStandardType(), ARTS::Species::isO2_TRE05(), ARTS::Species::isO2_v0v0CKDMT100(), ARTS::Species::isO2_v1v0CKDMT100(), ARTS::Species::isO2_visCKDMT252(), ARTS::Species::isO3_666(), ARTS::Species::isO3_667(), ARTS::Species::isO3_668(), ARTS::Species::isO3_676(), ARTS::Species::isO3_686(), ARTS::Species::isO_6(), ARTS::Species::isOClO_656(), ARTS::Species::isOClO_676(), ARTS::Species::isOCS_622(), ARTS::Species::isOCS_623(), ARTS::Species::isOCS_624(), ARTS::Species::isOCS_632(), ARTS::Species::isOCS_634(), ARTS::Species::isOCS_822(), ARTS::Species::isOH_61(), ARTS::Species::isOH_62(), ARTS::Species::isOH_81(), QuantumIdentifier::Isotopologue(), ARTS::Species::isPH3_1111(), ARTS::Species::israin_MPM93(), ARTS::Species::isSF6_29(), ARTS::Species::isSO2_626(), ARTS::Species::isSO2_628(), ARTS::Species::isSO2_636(), ARTS::Species::isSO2_646(), ARTS::Species::isSO3_26(), ARTS::Species::isSO_26(), ARTS::Species::isSO_28(), ARTS::Species::isSO_46(), operator<<(), print_species_identification(), lm_hitran_2017::qt_co2(), Absorption::ReadFromHitran2001Stream(), Absorption::ReadFromHitran2004Stream(), Absorption::ReadFromHitran2012Stream(), Absorption::ReadFromHitranOnlineStream(), Absorption::ReadFromLBLRTMStream(), Absorption::ReadFromMytran2Stream(), QuantumIdentifier::SetFromStringForCO2Band(), species_iso_match(), SpeciesTag::SpeciesMass(), test001(), and xml_write_to_stream().
next_species()
void next_species (Array< SpeciesRecord >::iterator & is, Array< IsotopologueRecord >::iterator & ii, String name)
Define partition function coefficients lookup data.
General Remarks
Advance iterators to first isotopologue of next species.
Definition at line 1787 of file partition_function_data.cc.
References ARTS_ASSERT.
Referenced by define_partition_species_data().