ARTS: physics_funcs.cc File Reference
physics_funcs.cc File Reference
This file contains the code of functions of physical character.
#include "physics_funcs.h"
#include <cmath>
#include <stdexcept>
#include "messages.h"
#include "mystring.h"
Functions
Numeric barometric_heightformula (const Numeric &p, const Numeric &dh)
barometric_heightformula
Numeric dinvplanckdI (const Numeric &i, const Numeric &f)
dinvplanckdI
void fresnel (Complex &Rv, Complex &Rh, const Complex &n1, const Complex &n2, const Numeric &theta)
fresnel
Numeric invplanck (const Numeric &i, const Numeric &f)
invplanck
Numeric invrayjean (const Numeric &i, const Numeric &f)
invrayjean
Numeric planck (const Numeric &f, const Numeric &t)
planck
void planck (VectorView b, ConstVectorView f, const Numeric &t)
planck
Vector planck (ConstVectorView f, const Numeric &t)
planck
Numeric dplanck_dt (const Numeric &f, const Numeric &t)
dplanck_dt
void dplanck_dt (VectorView dbdt, ConstVectorView f, const Numeric &t)
dplanck_dt
Vector dplanck_dt (ConstVectorView f, const Numeric &t)
dplanck_dt
Numeric dplanck_df (const Numeric &f, const Numeric &t)
dplanck_df
Vector dplanck_df (const ConstVectorView f, const Numeric &t)
dplanck_df
Numeric rayjean (const Numeric &f, const Numeric &tb)
rayjean
Variables
const Numeric BOLTZMAN_CONST
const Numeric DEG2RAD
const Numeric PLANCK_CONST
const Numeric SPEED_OF_LIGHT
Detailed Description
This file contains the code of functions of physical character.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-08
Modified by Claudia Emde (2002-05-28).
Definition in file physics_funcs.cc.
Function Documentation
barometric_heightformula()
Numeric barometric_heightformula (const Numeric & p, const Numeric & dh)
barometric_heightformula
Barometric heightformula for isothermal earth atmosphere.
Parameters
[in] p Atmospheric pressure at starting level [Pa].
[in] dh Vertical displacement to starting pressure level [m].
Returns
p1 Pressure in displacement level [Pa].
Author
Daniel Kreyling
Date
2011-01-20
Definition at line 62 of file physics_funcs.cc.
References M.
Referenced by cloudboxSetAutomatically().
dinvplanckdI()
Numeric dinvplanckdI (const Numeric & i, const Numeric & f)
dinvplanckdI
Calculates the derivative of inverse-Planck with respect to intensity.
Parameters
[in] i Radiance.
[in] f Frequency.
Returns
The derivative.
Author
Patrick Eriksson
Date
2010-10-26
Definition at line 98 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, b, BOLTZMAN_CONST, d, PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit2().
dplanck_df() [1/2]
Vector dplanck_df (const ConstVectorView f, const Numeric & t)
dplanck_df
Calculates the frequency derivative of the Planck function for a single temperature and frequency.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation frequency derivative.
Author
Richard Larsson
Date
2015-09-15
Definition at line 360 of file physics_funcs.cc.
References dplanck_df(), and ConstVectorView::nelem().
dplanck_df() [2/2]
Numeric dplanck_df (const Numeric & f, const Numeric & t)
dplanck_df
Calculates the frequency derivative of the Planck function for a single temperature and frequency.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation frequency derivative.
Author
Richard Larsson
Date
2015-09-15
Definition at line 335 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, b, and Constant::pow2().
Referenced by dplanck_df(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), and zeeman_on_the_fly().
dplanck_dt() [1/3]
Numeric dplanck_dt (const Numeric & f, const Numeric & t)
dplanck_dt
Calculates the temperature derivative of the Planck function for a single temperature and frequency.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation temperature derivative.
Author
Richard Larsson
Date
2015-09-15
Definition at line 271 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, b, Constant::pow2(), and Constant::pow4().
Referenced by dplanck_dt(), get_stepwise_blackbody_radiation(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), and zeeman_on_the_fly().
dplanck_dt() [2/3]
Vector dplanck_dt (ConstVectorView f, const Numeric & t)
dplanck_dt
Calculates the Planck function temperature derivative for a single temperature and a vector of frequencies.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation temperature derivative.
Author
Richard Larsson
Date
2019-10-11
Definition at line 316 of file physics_funcs.cc.
References dplanck_dt(), and ConstVectorView::nelem().
dplanck_dt() [3/3]
void dplanck_dt (VectorView dbdt, ConstVectorView f, const Numeric & t)
dplanck_dt
Calculates the Planck function temperature derivative for a single temperature and a vector of frequencies.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation temperature derivative.
Author
Richard Larsson
Date
2019-10-11
Definition at line 297 of file physics_funcs.cc.
References ARTS_USER_ERROR_IF, dplanck_dt(), and ConstVectorView::nelem().
fresnel()
void fresnel (Complex & Rv, Complex & Rh, const Complex & n1, const Complex & n2, const Numeric & theta)
fresnel
Calculates complex AMPLITUDE reflection coeffcients for a specular reflection.
The properties of the two involved media are given as the complex refractive index, n. A dielectric constant, eps, is converted as n = sqrt(eps). The power reflection coefficient, r, for one polarisation is r = abs(R)^2.
Parameters
[out] Rv Reflection coefficient for vertical polarisation.
[out] Rh Reflection coefficient for vertical polarisation.
[in] n1 Refractive index of medium where radiation propagates.
[in] n2 Refractive index of reflecting medium.
[in] theta Propagation angle from normal of radiation to be. reflected
Author
Patrick Eriksson
Date
2004-09-21
Definition at line 130 of file physics_funcs.cc.
References a, b, and DEG2RAD.
Referenced by surfaceFlatRefractiveIndex().
invplanck()
Numeric invplanck (const Numeric & i, const Numeric & f)
invplanck
Converts a radiance to Planck brightness temperature.
Parameters
[in] i Radiance.
[in] f Frequency.
Returns
Planck brightness temperature.
Author
Patrick Eriksson
Date
2002-08-11
Definition at line 160 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, b, BOLTZMAN_CONST, PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit().
invrayjean()
Numeric invrayjean (const Numeric & i, const Numeric & f)
invrayjean
Converts a radiance to Rayleigh-Jean brightness temperature.
Parameters
[in] i Radiance.
[in] f Frequency.
Returns
RJ brightness temperature.
Author
Patrick Eriksson
Date
2000-09-28
Definition at line 182 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, BOLTZMAN_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit(), apply_iy_unit2(), cloudbox_fieldUpdateSeq1D(), doit_conv_flagAbsBT(), and doit_conv_flagLsq().
planck() [1/3]
Numeric planck (const Numeric & f, const Numeric & t)
planck
Calculates the Planck function for a single temperature.
Note that this expression gives the intensity for both polarisations.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation.
Author
Patrick Eriksson
Date
2000-04-08
Definition at line 206 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, b, Constant::pow2(), and Constant::pow3().
Referenced by get_stepwise_blackbody_radiation(), MatrixCBR(), MatrixPlanck(), MCGeneral(), nlte_sourceFromTemperatureAndSrcCoefPerSpecies(), planck(), surface_specular_R_and_b(), surfaceBlackbody(), surfaceFastem(), surfaceFlatRvRh(), surfaceFlatScalarReflectivity(), surfaceLambertianSimple(), and zeeman_on_the_fly().
planck() [2/3]
Vector planck (ConstVectorView f, const Numeric & t)
planck
Calculates the Planck function for a single temperature and a vector of frequencies.
Note that this expression gives the intensity for both polarisations.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation.
Author
Patrick Eriksson
Date
2015-12-15
Definition at line 252 of file physics_funcs.cc.
References b, ConstVectorView::nelem(), and planck().
planck() [3/3]
void planck (VectorView b, ConstVectorView f, const Numeric & t)
planck
Calculates the Planck function for a single temperature and a vector of frequencies.
Note that this expression gives the intensity for both polarisations.
Parameters
[in] f Frequency.
[in] t Temperature.
Returns
Blackbody radiation.
Author
Patrick Eriksson
Date
2015-12-15
Definition at line 231 of file physics_funcs.cc.
References ARTS_USER_ERROR_IF, b, ConstVectorView::nelem(), and planck().
rayjean()
Numeric rayjean (const Numeric & f, const Numeric & tb)
rayjean
Converts a Rayleigh-Jean brightness temperature to radiance
Parameters
[in] tb RJ brightness temperature.
[in] f Frequency.
Returns
Radiance.
Author
Patrick Eriksson
Date
2011-07-13
Definition at line 378 of file physics_funcs.cc.
References a, ARTS_USER_ERROR_IF, BOLTZMAN_CONST, and SPEED_OF_LIGHT.
Variable Documentation
BOLTZMAN_CONST
const Numeric BOLTZMAN_CONST extern
Referenced by dinvplanckdI(), invplanck(), invrayjean(), and rayjean().
DEG2RAD
const Numeric DEG2RAD extern
Referenced by fresnel().
PLANCK_CONST
const Numeric PLANCK_CONST extern
Referenced by dinvplanckdI(), and invplanck().
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by dinvplanckdI(), invplanck(), invrayjean(), and rayjean().