ARTS: ppath.h File Reference
ppath.h File Reference
Propagation path structure and functions.
#include "agenda_class.h"
#include "array.h"
#include "arts.h"
#include "interpolation.h"
#include "matpackI.h"
#include "mystring.h"
Classes
struct Ppath
The structure to describe a propagation path and releated quantities.
Typedefs
typedef Array< Ppath > ArrayOfPpath
An array of propagation paths.
Functions
void add_za_aa (Numeric &za, Numeric &aa, const Numeric &za0, const Numeric &aa0, const Numeric &dza, const Numeric &daa)
Adds up zenith and azimuth angles.
void cart2zaaa (Numeric &za, Numeric &aa, const Numeric &dx, const Numeric &dy, const Numeric &dz)
Converts a cartesian directional vector to zenith and azimuth.
void zaaa2cart (Numeric &dx, Numeric &dy, Numeric &dz, const Numeric &za, const Numeric &aa)
Converts zenith and azimuth angles to a cartesian unit vector.
void enu2zaaa (Numeric &za, Numeric &aa, const Numeric &de, const Numeric &dn, const Numeric &du)
Converts ENU unit vector vector to zenith and azimuth.
void zaaa2enu (Numeric &de, Numeric &dn, Numeric &du, const Numeric &za, const Numeric &aa)
Converts zenith and azimuth angles to ENU unit vector.
void diff_za_aa (Numeric &dza, Numeric &daa, const Numeric &za0, const Numeric &aa0, const Numeric &za, const Numeric &aa)
Takes the difference of zenith and azimuth angles.
void error_if_limb_ppath (const Ppath &ppath)
Throws an error if ppath altitudes not are strictly increasing or decreasing.
void find_tanpoint (Index &it, const Ppath &ppath)
Identifies the tangent point of a propagation path.
Index first_pos_before_altitude (const Ppath &p, const Numeric &alt)
Determines ppath position just below an altitude.
Numeric geometrical_ppc (const Numeric &r, const Numeric &za)
Calculates the propagation path constant for pure geometrical calculations.
Numeric geompath_lat_at_za (const Numeric &za0, const Numeric &lat0, const Numeric &za)
Calculates the latitude for a given zenith angle along a geometrical propagation path.
Numeric geompath_l_at_r (const Numeric &ppc, const Numeric &r)
Calculates the length from the tangent point for the given radius.
Numeric geompath_r_at_l (const Numeric &ppc, const Numeric &l)
Calculates the radius for a distance from the tangent point.
Numeric geompath_za_at_r (const Numeric &ppc, const Numeric &a_za, const Numeric &r)
Calculates the zenith angle for a given radius along a geometrical propagation path.
bool is_los_downwards (const Numeric &za, const Numeric &tilt)
Determines if a line-of-sight is downwards compared to the angular tilt of the surface or a pressure level.
Numeric plevel_angletilt (const Numeric &r, const Numeric &c)
Calculates the angular tilt of the surface or a pressure level.
void plevel_slope_2d (Numeric &c1, ConstVectorView lat_grid, ConstVectorView refellipsoid, ConstVectorView z_surf, const GridPos &gp, const Numeric &za)
Calculates the radial slope of the surface or a pressure level for 2D.
void plevel_slope_3d (Numeric &c1, Numeric &c2, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstVectorView refellipsoid, ConstMatrixView z_surf, const GridPos &gp_lat, const GridPos &gp_lon, const Numeric &aa)
Calculates the radial slope of the surface or a pressure level for 3D.
void ppath_calc (Workspace &ws, Ppath &ppath, const Agenda &ppath_step_agenda, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Vector &f_grid, const Vector &refellipsoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Vector &rte_pos, const Vector &rte_los, const Numeric &ppath_lmax, const Numeric &ppath_lraytrace, const bool &ppath_inside_cloudbox_do, const Verbosity &verbosity)
This is the core for the WSM ppathStepByStep.
void ppath_copy (Ppath &ppath1, const Ppath &ppath2, const Index &ncopy)
Copy the content in ppath2 to ppath1.
void ppath_init_structure (Ppath &ppath, const Index &atmosphere_dim, const Index &np)
Initiates a Ppath structure to hold the given number of points.
void ppath_set_background (Ppath &ppath, const Index &case_nr)
Sets the background field of a Ppath structure.
void ppath_start_stepping (Ppath &ppath, const Index &atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const bool &outside_cloudbox, ConstVectorView rte_pos, ConstVectorView rte_los, const Verbosity &verbosity)
Initiates a Ppath structure for calculation of a path with ppath_step.
void ppath_step_geom_1d (Ppath &ppath, ConstVectorView z_field, ConstVectorView refellipsoid, const Numeric &z_surface, const Numeric &lmax)
Calculates 1D geometrical propagation path steps.
void ppath_step_geom_2d (Ppath &ppath, ConstVectorView lat_grid, ConstMatrixView z_field, ConstVectorView refellipsoid, ConstVectorView z_surface, const Numeric &lmax)
Calculates 2D geometrical propagation path steps.
void ppath_step_geom_3d (Ppath &ppath, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Numeric &lmax)
Calculates 3D geometrical propagation path steps.
void ppath_step_refr_1d (Workspace &ws, Ppath &ppath, ConstVectorView p_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, const Numeric &z_surface, const Numeric &lmax, const Agenda &refr_index_agenda, const String &rtrace_method, const Numeric &lraytrace)
Calculates 1D propagation path steps including effects of refraction.
void ppath_step_refr_2d (Workspace &ws, Ppath &ppath, ConstVectorView p_grid, ConstVectorView lat_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, ConstVectorView z_surface, const Numeric &lmax, const Agenda &refr_index_agenda, const String &rtrace_method, const Numeric &lraytrace)
Calculates 2D propagation path steps, with refraction, using a simple and fast ray tracing scheme.
void ppath_step_refr_3d (Workspace &ws, Ppath &ppath, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Numeric &lmax, const Agenda &refr_index_agenda, const String &rtrace_method, const Numeric &lraytrace)
Calculates 3D propagation path steps, with refraction, using a simple and fast ray tracing scheme.
Index ppath_what_background (const Ppath &ppath)
Returns the case number for the radiative background.
void resolve_lon (Numeric &lon, const Numeric &lon5, const Numeric &lon6)
Resolves which longitude angle that shall be used.
Variables
const Numeric POLELAT = 90 - 1e-8
Size of north and south poles.
const Numeric ANGTOL = 1e-6
Width of zenith and nadir directions.
Detailed Description
Propagation path structure and functions.
Author
Patrick Eriksson patri.nosp@m.ck.e.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-02
This file contains the definition of the Ppath structure and the functions in ppath.cc that are of interest elsewhere.
Definition in file ppath.h.
Typedef Documentation
ArrayOfPpath
typedef Array<Ppath> ArrayOfPpath
An array of propagation paths.
Definition at line 90 of file ppath.h.
Function Documentation
add_za_aa()
void add_za_aa (Numeric & za, Numeric & aa, const Numeric & za0, const Numeric & aa0, const Numeric & dza, const Numeric & daa)
Adds up zenith and azimuth angles.
Adds (dza,daa) to (za0,aa0), assuming that a unit changes in za and aa are equal where (dza,daa)=(0,0).
Parameters
[out] za End zenith angle
[out] aa End azimuth angle
[in] za0 Start zenith angle
[in] aa0 Start azimuth angle
[in] dza Change in zenith angle
[in] daa Change in azimuth angle
Author
Patrick Eriksson
Date
2018-12-19
Definition at line 391 of file ppath.cc.
References zaaa2cart().
Referenced by AddZaAa(), iyb_calc_body(), and Test().
cart2zaaa()
void cart2zaaa (Numeric & za, Numeric & aa, const Numeric & dx, const Numeric & dy, const Numeric & dz)
Converts a cartesian directional vector to zenith and azimuth.
This function and the sister function cart2zaaa handle transformation of line-of-sights. This in contrast to the sph/poslos functions that handles positions, or combinations of positions and line-of-sight.
The cartesian coordinate system used for these two functions can be defined as z : za = 0 x : za=90, aa=0 y : za=90, aa=90
Parameters
[out] za LOS zenith angle at observation position.
[out] aa LOS azimuth angle at observation position.
[in] dx x-part of LOS unit vector.
[in] dy y-part of LOS unit vector.
[in] dz z-part of LOS unit vector.
Author
Patrick Eriksson
Date
2009-10-02
Definition at line 299 of file ppath.cc.
References dx, RAD2DEG, and sqrt().
Referenced by adjust_los(), and specular_losCalc().
diff_za_aa()
void diff_za_aa (Numeric & dza, Numeric & daa, const Numeric & za0, const Numeric & aa0, const Numeric & za, const Numeric & aa)
Takes the difference of zenith and azimuth angles.
Takes the difference between a set of angles (za,aa) and a reference direction (za0,aa0). That is, this function is the "inverse" of add_za_aa.
Parameters
[out] dza Change in zenith angle
[out] daa Change in azimuth angle
[in] za0 Zenith angle of reference direction
[in] aa0 Azimuth angle of reference direction
[in] za Zenith angle of second direction
[in] aa Azimuth angle of second direction
Author
Patrick Eriksson
Date
2018-12-19
Definition at line 429 of file ppath.cc.
References zaaa2cart().
Referenced by DiffZaAa(), and Test().
enu2zaaa()
void enu2zaaa (Numeric & za, Numeric & aa, const Numeric & de, const Numeric & dn, const Numeric & du)
Converts ENU unit vector vector to zenith and azimuth.
This function and the sister function enu2zaaa handles transformation of line-of-sights, from and to ENU (east-north-up). The ENU vector is normalised to have length 1.
Parameters
[out] za LOS zenith angle at observation position.
[out] aa LOS azimuth angle at observation position.
[in] de e-part of LOS unit vector.
[in] dn n-part of LOS unit vector.
[in] du u-part of LOS unit vector.
Author
Patrick Eriksson
Date
2020-09-17
Definition at line 326 of file ppath.cc.
References RAD2DEG.
error_if_limb_ppath()
void error_if_limb_ppath (const Ppath & ppath)
Throws an error if ppath altitudes not are strictly increasing or decreasing.
Parameters
[in] ppath Propagation path structure.
Author
Patrick Eriksson
Date
2018-03-07
Definition at line 540 of file ppath.cc.
References ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), and sign().
Referenced by iyIndependentBeamApproximation(), and yActive().
find_tanpoint()
void find_tanpoint (Index & it, const Ppath & ppath)
Identifies the tangent point of a propagation path.
The tangent points is defined as the point with the lowest altitude.
The index of the tangent point is determined. If no tangent point is found, the index is set to -1.
Parameters
[out] it Index of tangent point
[in] ppath Propagation path structure.
Author
Patrick Eriksson
Date
2012-04-07
Definition at line 510 of file ppath.cc.
References ARTS::Var::Ppath::pos(), and ARTS::Var::ppath().
Referenced by defocusing_sat2sat(), TangentPointExtract(), and TangentPointPrint().
first_pos_before_altitude()
Index first_pos_before_altitude (const Ppath & p, const Numeric & alt)
Determines ppath position just below an altitude.
Returns -1 if the selected altitude is not passed.
Parameters
[in] ppath Propagation path structure.
[in] alt Altitude
Returns
Index of found altitude
Author
Richard Larsson
Date
20??-??-??
Definition at line 522 of file ppath.cc.
References Ppath::np, and Ppath::pos.
Referenced by ppathCalcFromAltitude().
geometrical_ppc()
Numeric geometrical_ppc (const Numeric & r, const Numeric & za)
Calculates the propagation path constant for pure geometrical calculations.
Both positive and negative zenith angles are handled.
Parameters
[in] r Radius of the sensor position.
[in] za Zenith angle of the sensor line-of-sight.
Returns
Path constant.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 96 of file ppath.cc.
References abs, and DEG2RAD.
Referenced by ppath_start_stepping(), ppath_step_geom_1d(), ppath_step_geom_2d(), ppath_step_geom_3d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), and raytrace_3d_linear_basic().
geompath_l_at_r()
Numeric geompath_l_at_r (const Numeric & ppc, const Numeric & r)
Calculates the length from the tangent point for the given radius.
The tangent point is either real or imaginary depending on the zenith angle of the sensor. See geometrical_tangent_radius.
Parameters
[in] ppc Propagation path constant.
[in] r Radius of the point of concern.
Returns
Length along the path from the tangent point. Always >= 0.
Author
Patrick Eriksson
Date
2002-05-20
Definition at line 158 of file ppath.cc.
References RTOL, and sqrt().
Referenced by cart2poslos(), geompath_from_r1_to_r2(), ppath_start_stepping(), r_crossing_2d(), raytrace_1d_linear_basic(), and raytrace_2d_linear_basic().
geompath_lat_at_za()
Numeric geompath_lat_at_za (const Numeric & za0, const Numeric & lat0, const Numeric & za)
Calculates the latitude for a given zenith angle along a geometrical propagation path.
Positive and negative zenith angles are handled. A positive zenith angle means a movement towards higher latitudes.
Parameters
[in] za0 The zenith angle of the starting point.
[in] lat0 The latitude of the starting point.
[in] za The zenith angle of the second point.
Returns
The latitude of the second point.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 148 of file ppath.cc.
References abs.
Referenced by geompath_from_r1_to_r2(), ppath_start_stepping(), r_crossing_2d(), raytrace_1d_linear_basic(), and raytrace_2d_linear_basic().
geompath_r_at_l()
Numeric geompath_r_at_l (const Numeric & ppc, const Numeric & l)
Calculates the radius for a distance from the tangent point.
The tangent point is either real or imaginary depending on the zenith angle of the sensor. See geometrical_tangent_radius.
Parameters
[in] ppc Propagation path constant.
[in] l Length from the tangent point (positive or negative).
Returns
Radius.
Author
Patrick Eriksson
Date
2002-05-20
Definition at line 169 of file ppath.cc.
References sqrt().
Referenced by geompath_from_r1_to_r2(), raytrace_1d_linear_basic(), and raytrace_2d_linear_basic().
geompath_za_at_r()
Numeric geompath_za_at_r (const Numeric & ppc, const Numeric & a_za, const Numeric & r)
Calculates the zenith angle for a given radius along a geometrical propagation path.
For downlooking cases, the two points must be on the same side of the tangent point.
Both positive and negative zenith angles are handled.
Parameters
[in] ppc Propagation path constant.
[in] a_za A zenith angle along the path on the same side of the tangent point as the point of interest.
[in] r Radius of the point of interest.
Returns
Zenith angle at the point of interest.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 103 of file ppath.cc.
References abs, RAD2DEG, and RTOL.
Referenced by geompath_from_r1_to_r2(), ppath_start_stepping(), r_crossing_2d(), raytrace_1d_linear_basic(), raytrace_2d_linear_basic(), and VectorZtanToZa1D().
is_los_downwards()
bool is_los_downwards (const Numeric & za, const Numeric & tilt)
Determines if a line-of-sight is downwards compared to the angular tilt of the surface or a pressure level.
For example, this function can be used to determine if the line-of-sight goes into the surface for a starting point exactly on the surface radius.
As the radius of the surface and pressure levels varies as a function of latitude, it is not clear if a zenith angle of 90 is above or below e.g. the surface.
Parameters
[in] za Zenith angle of line-of-sight.
[in] tilt Angular tilt of the surface or the pressure level (as returned by plevel_angletilt)
Returns
Boolean that is true if LOS is downwards.
Author
Patrick Eriksson
Date
2002-06-03
Definition at line 623 of file ppath.cc.
References abs.
Referenced by ppath_start_2d(), and ppath_start_stepping().
plevel_angletilt()
Numeric plevel_angletilt (const Numeric & r, const Numeric & c)
Calculates the angular tilt of the surface or a pressure level.
Note that the tilt value is a local value. The tilt for a constant slope value, is different for different radii.
Parameters
[in] r The radius for the level at the point of interest.
[in] c1 The radial slope, as returned by e.g. plevel_slope_2d.
Returns
The angular tilt.
Author
Patrick Eriksson
Date
2002-06-03
Definition at line 617 of file ppath.cc.
References RAD2DEG.
Referenced by ppath_start_2d(), ppath_start_3d(), ppath_start_stepping(), and specular_losCalc().
plevel_slope_2d()
void plevel_slope_2d (Numeric & c1, ConstVectorView lat_grid, ConstVectorView refellipsoid, ConstVectorView z_surf, const GridPos & gp, const Numeric & za)
Calculates the radial slope of the surface or a pressure level for 2D.
The radial slope is here the derivative of the radius with respect to the latitude. The unit is accordingly m/degree.
Note that the radius is defined to change linearly between grid points, and the slope is constant between to points of the latitude grid. The radius can inside the grid range be expressed as r = r0(lat0) + c1*(lat-lat0) .
Note also that the slope is always calculated with respect to increasing latitudes, independently of the zenith angle. The zenith angle is only used to determine which grid range that is of interest when the position is exactly on top of a grid point.
Parameters
[out] c1 The radial slope [m/degree]
[in] lat_grid The latitude grid.
[in] refellipsoid As the WSV with the same name.
[in] z_surf Geometrical altitude of the surface, or the pressure level of interest, for the latitide dimension
[in] gp Latitude grid position for the position of interest
[in] za LOS zenith angle.
Author
Patrick Eriksson
Date
2002-06-03
Definition at line 580 of file ppath.cc.
References gridpos2gridrange(), ARTS::Var::lat_grid(), refell2r(), and ARTS::Var::refellipsoid().
Referenced by ppath_start_2d(), ppath_start_stepping(), and specular_losCalc().
plevel_slope_3d()
void plevel_slope_3d (Numeric & c1, Numeric & c2, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstVectorView refellipsoid, ConstMatrixView z_surf, const GridPos & gp_lat, const GridPos & gp_lon, const Numeric & aa)
Calculates the radial slope of the surface or a pressure level for 3D.
For 2D the radius can be expressed as r = r0 + c1*dalpha, where alpha is the latitude. The radius is here for 3D expressed as a second order polynomial: r = r0 + c1*dalpha + c2*dalpha^2, where alpha is the angular change (in degrees) along the great circle along the given azimuth angle.
Parameters
[out] c1 See above. Unit is m/degree.
[out] c2 See above. Unit is m/degree^2.
[in] lat1 Lower latitude of grid cell.
[in] lat3 Upper latitude of grid cell.
[in] lon5 Lower longitude of grid cell.
[in] lon6 Upper longitude of grid cell.
[in] r15 Radius at crossing of lat1 and lon5.
[in] r35 Radius at crossing of lat3 and lon5.
[in] r36 Radius at crossing of lat3 and lon6.
[in] r16 Radius at crossing of lat1 and lon6.
[in] lat Latitude for which slope shall be determined.
[in] lon Longitude for which slope shall be determined.
[in] aa Azimuth angle for which slope shall be determined.
Author
Patrick Eriksson
Date
2002-12-30
For 2D where the radius can be expressed as r = r0 + c1*dalpha, where alpha is the latitude. The radius is here for 3D expressed as a second order polynomial: r = r0 + c1*dalpha + c2*dalpha^2, where alpha is the angular change (in degrees) along the great circle along the given azimuth angle.
For a point exactly on a grid value it is not clear if it is the range below or above that is of interest. The azimuth angle is used to resolve such cases.
Parameters
[out] c1 See above. Unit is m/degree.
[out] c2 See above. Unit is m/degree^2.
[in] lat_grid The latitude grid.
[in] lon_grid The longitude grid.
[in] refellipsoid As the WSV with the same name.
[in] z_surf Geometrical altitude of the surface, or the pressure level of interest.
[in] gp_lat Latitude grid position for the position of interest.
[in] gp_lon Longitude grid position for the position of interest.
[in] aa Azimuth angle.
Author
Patrick Eriksson
Date
2002-06-03
Definition at line 1147 of file ppath.cc.
References abs, gridpos2gridrange(), interp(), interpweights(), is_lon_cyclic(), ARTS::Var::lat(), ARTS::Var::lat_grid(), ARTS::Var::lon(), ARTS::Var::lon_grid(), plevel_slope_3d(), POLELAT, refell2r(), and ARTS::Var::refellipsoid().
ppath_calc()
void ppath_calc (Workspace & ws, Ppath & ppath, const Agenda & ppath_step_agenda, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Vector & f_grid, const Vector & refellipsoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Vector & rte_pos, const Vector & rte_los, const Numeric & ppath_lmax, const Numeric & ppath_lraytrace, const bool & ppath_inside_cloudbox_do, const Verbosity & verbosity)
This is the core for the WSM ppathStepByStep.
This function takes mainly the same input as ppathStepByStep (that is, those input arguments are the WSV with the same name).
Parameters
[in] ws Current Workspace
[in] ppath Output: A Ppath structure
[in] ppath_step_agenda As the WSM with the same name.
[in] atmosphere_dim The atmospheric dimensionality.
[in] p_grid The pressure grid.
[in] lat_grid The latitude grid.
[in] lon_grid The longitude grid.
[in] z_field As the WSM with the same name.
[in] f_grid As the WSM with the same name.
[in] refellipsoid As the WSM with the same name.
[in] z_surface Surface altitude.
[in] cloudbox_on Flag to activate the cloud box.
[in] cloudbox_limits Index limits of the cloud box.
[in] rte_pos The position of the sensor.
[in] rte_los The line-of-sight of the sensor.
[in] ppath_lmax As the WSM with the same name.
[in] ppath_lraytrace As the WSM with the same name.
[in] ppath_inside_cloudbox_do As the WSM with the same name.
Author
Patrick Eriksson
Date
2003-01-08
Definition at line 5191 of file ppath.cc.
References abs, ARTS::Var::atmosphere_dim(), chk_rte_los(), chk_rte_pos(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), ARTS::Var::f_grid(), fractional_gp(), gridpos(), is_gridpos_at_index_i(), joker, ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), Array< base >::nelem(), ARTS::Var::p_grid(), ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), ppath_copy(), ppath_init_structure(), ARTS::Var::ppath_inside_cloudbox_do(), ARTS::Var::ppath_lmax(), ARTS::Var::ppath_lraytrace(), ppath_set_background(), ppath_start_stepping(), ARTS::Var::ppath_step(), ARTS::Var::ppath_step_agenda(), ppath_step_agendaExecute(), ppath_what_background(), ARTS::Var::refellipsoid(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), ARTS::Var::verbosity(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by defocusing_general_sub(), defocusing_sat2sat(), ppathFromRtePos2(), and ppathStepByStep().
ppath_copy()
void ppath_copy (Ppath & ppath1, const Ppath & ppath2, const Index & ncopy)
Copy the content in ppath2 to ppath1.
The ppath1 structure must be allocated before calling the function. The structure can be allocated to hold more points than found in ppath2. The data of ppath2 is placed in the first positions of ppath1.
Parameters
[in] ppath1 Output: Ppath structure.
[in] ppath2 The ppath structure to be copied.
[in] ncopy Number of points in ppath2 to copy. If set to negative, the number is set to ppath2.np.
Author
Patrick Eriksson
Date
2002-07-03
Definition at line 1500 of file ppath.cc.
References Ppath::background, Ppath::constant, Ppath::dim, Ppath::end_los, Ppath::end_lstep, Ppath::end_pos, Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, gridpos_copy(), joker, Ppath::los, Ppath::lstep, Ppath::ngroup, Ppath::np, Ppath::nreal, Ppath::pos, Ppath::r, Ppath::start_los, Ppath::start_lstep, and Ppath::start_pos.
Referenced by ppath_append(), ppath_calc(), and ppathFromRtePos2().
ppath_init_structure()
void ppath_init_structure (Ppath & ppath, const Index & atmosphere_dim, const Index & np)
Initiates a Ppath structure to hold the given number of points.
The background field is set to background case 0. The constant field is set to -1. The refraction field is set to 0.
The length of the lstep field is set to np-1.
Parameters
[in] ppath Output: A Ppath structure.
[in] atmosphere_dim The atmospheric dimensionality.
[in] np Number of points of the path.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 1411 of file ppath.cc.
References ARTS::Var::atmosphere_dim(), max, ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), and ppath_set_background().
Referenced by cloud_ppath_update1D(), cloud_ppath_update1D_noseq(), cloud_ppath_update3D(), ppath_append(), ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_start_stepping(), ppathFromRtePos2(), and ppathPlaneParallel().
ppath_set_background()
void ppath_set_background (Ppath & ppath, const Index & case_nr)
Sets the background field of a Ppath structure.
The different background cases have a number coding to simplify a possible change of the strings and checking of the what case that is valid.
The case numbers are:
0. Unvalid.
Space.
The surface.
The cloud box boundary.
The interior of the cloud box.
Parameters
[in] ppath Output: A Ppath structure.
[in] case_nr Case number (see above)
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 1452 of file ppath.cc.
References ARTS::Var::ppath().
Referenced by ppath_calc(), ppath_end_1d(), ppath_end_2d(), ppath_end_3d(), ppath_init_structure(), ppath_start_stepping(), ppathFromRtePos2(), and ppathPlaneParallel().
ppath_start_stepping()
void ppath_start_stepping (Ppath & ppath, const Index & atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const bool & outside_cloudbox, ConstVectorView rte_pos, ConstVectorView rte_los, const Verbosity & verbosity)
Initiates a Ppath structure for calculation of a path with ppath_step.
The function performs two main tasks. As mentioned above, it initiates a Ppath structure (a), but it also checks that the end point of the path is at an allowed location (b).
(a): The Ppath structure is set to hold the position and LOS of the last point of the path inside the atmosphere. This point is either the sensor position, or the point where the path leaves the model atmosphere. If the path is totally outside the atmosphere, no point is put into the structure. If the (practical) end and start points are identical, such as when the sensor is inside the cloud box, the background field is set.
(b): If it is found that the end point of the path is at an illegal position a detailed error message is given. Not allowed cases are:
The sensor is placed below surface level.
For 2D and 3D, the path leaves the model atmosphere at a latitude or longitude end face.
For 2D and 3D, the path is totally outside the atmosphere and the latitude and longitude of the tangent point is outside the range of the corresponding grids.
All input variables are identical with the WSV with the same name. The output variable is here called ppath for simplicity, but is in fact ppath_step.
Parameters
[in] ppath Output: A Ppath structure.
[in] atmosphere_dim The atmospheric dimensionality.
[in] p_grid The pressure grid.
[in] lat_grid The latitude grid.
[in] lon_grid The longitude grid.
[in] z_field The field of geometrical altitudes.
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitude.
[in] cloudbox_on Flag to activate the cloud box.
[in] cloudbox_limits Index limits of the cloud box.
[in] ppath_inside_cloudbox_do As the WSV with the same name.
[in] rte_pos The position of the sensor.
[in] rte_los The line-of-sight of the sensor.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 4480 of file ppath.cc.
References abs, ARTS::Var::atmosphere_dim(), cart2poslos(), ARTS::Var::cloudbox_limits(), ARTS::Var::cloudbox_on(), CREATE_OUT1, DEBUG_ONLY, dx, fractional_gp(), geometrical_ppc(), geompath_l_at_r(), geompath_lat_at_za(), geompath_za_at_r(), gridpos(), gridpos_check_fd(), gridpos_copy(), interp(), interpweights(), is_los_downwards(), joker, L_NOT_FOUND, LACC, ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), ARTS::Var::p_grid(), plevel_angletilt(), plevel_slope_2d(), plevel_slope_3d(), ARTS::Var::Ppath::pos(), poslos2cart(), ARTS::Var::ppath(), ppath_init_structure(), ARTS::Var::ppath_inside_cloudbox_do(), ppath_set_background(), r_crossing_2d(), r_crossing_3d(), refell2d(), refell2r(), ARTS::Var::refellipsoid(), resolve_lon(), ARTS::Var::rte_los(), ARTS::Var::rte_pos(), rte_pos2gridpos(), RTOL, ARTS::Var::x(), ARTS::Var::y(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by mcPathTraceRadar(), and ppath_calc().
ppath_step_geom_1d()
void ppath_step_geom_1d (Ppath & ppath, ConstVectorView z_field, ConstVectorView refellipsoid, const Numeric & z_surface, const Numeric & lmax)
Calculates 1D geometrical propagation path steps.
This is the core function to determine 1D propagation path steps by pure geometrical calculations. Path points are included for crossings with the grids, tangent points and points of intersection with the surface. In addition, points are included in the propgation path to ensure that the distance along the path between the points does not exceed the selected maximum length (lmax). If lmax is <= 0, this means that no length criterion shall be applied.
Note that the input variables are here compressed to only hold data for a 1D atmosphere. For example, z_field is z_field(:,0,0).
For more information read the chapter on propagation paths in AUG.
Parameters
[in] ppath Output: A Ppath structure.
[in] z_field Geometrical altitudes corresponding to p_grid.
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitude.
[in] lmax Maximum allowed length between the path points.
Author
Patrick Eriksson
Date
2002-05-20
Definition at line 2357 of file ppath.cc.
References do_gridrange_1d(), geometrical_ppc(), ConstVectorView::nelem(), ARTS::Var::ppath(), ppath_end_1d(), ppath_start_1d(), ARTS::Var::refellipsoid(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepGeometric().
ppath_step_geom_2d()
void ppath_step_geom_2d (Ppath & ppath, ConstVectorView lat_grid, ConstMatrixView z_field, ConstVectorView refellipsoid, ConstVectorView z_surface, const Numeric & lmax)
Calculates 2D geometrical propagation path steps.
Works as the same function for 1D, despite that some input arguments are of different type.
Parameters
[in] ppath Output: A Ppath structure.
[in] lat_grid Latitude grid.
[in] z_field Geometrical altitudes
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitudes.
[in] lmax Maximum allowed length between the path points.
Author
Patrick Eriksson
Date
2002-07-03
Definition at line 2721 of file ppath.cc.
References do_gridcell_2d_byltest(), geometrical_ppc(), ARTS::Var::lat_grid(), ConstVectorView::nelem(), ARTS::Var::ppath(), ppath_end_2d(), ppath_start_2d(), ARTS::Var::refellipsoid(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepGeometric().
ppath_step_geom_3d()
void ppath_step_geom_3d (Ppath & ppath, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Numeric & lmax)
Calculates 3D geometrical propagation path steps.
Works as the same function for 1D despite that some input arguments are of different type.
Parameters
[in] ppath Output: A Ppath structure.
[in] lat_grid Latitude grid.
[in] lon_grid Longitude grid.
[in] z_field Geometrical altitudes
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitudes.
[in] lmax Maximum allowed length between the path points.
Author
Patrick Eriksson
Date
2002-12-30
Definition at line 3255 of file ppath.cc.
References do_gridcell_3d_byltest(), geometrical_ppc(), ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), ConstVectorView::nelem(), ARTS::Var::ppath(), ppath_end_3d(), ppath_start_3d(), ARTS::Var::refellipsoid(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepGeometric().
ppath_step_refr_1d()
void ppath_step_refr_1d (Workspace & ws, Ppath & ppath, ConstVectorView p_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, const Numeric & z_surface, const Numeric & lmax, const Agenda & refr_index_agenda, const String & rtrace_method, const Numeric & lraytrace)
Calculates 1D propagation path steps including effects of refraction.
This function works as the function ppath_step_geom_1d but considers also refraction. The upper length of the ray tracing steps is set by the argument lraytrace. This argument controls only the internal calculations. The maximum distance between the path points is still determined by lmax.
Parameters
[in,out] ws Current Workspace
[out] ppath A Ppath structure.
[in] p_grid Pressure grid.
[in] z_field As the WSV with the same name.
[in] t_field As the WSV with the same name.
[in] vmr_field As the WSV with the same name.
[in] f_grid As the WSV with the same name.
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitude (1D).
[in] lmax Maximum allowed length between the path points.
[in] refr_index_air_agenda The WSV with the same name.
[in] rtrace_method String giving which ray tracing method to use. See the function for options.
[in] lraytrace Maximum allowed length for ray tracing steps.
Author
Patrick Eriksson
Date
2002-11-26
Definition at line 3561 of file ppath.cc.
References ARTS::Var::f_grid(), get_refr_index_1d(), joker, Array< base >::nelem(), ARTS::Var::p_grid(), ARTS::Var::ppath(), ppath_end_1d(), ppath_start_1d(), raytrace_1d_linear_basic(), ARTS::Var::refellipsoid(), ARTS::Var::refr_index_air(), ARTS::Var::refr_index_air_agenda(), ARTS::Var::refr_index_air_group(), refraction_ppc(), ARTS::Var::t_field(), ARTS::Var::vmr_field(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepRefractionBasic().
ppath_step_refr_2d()
void ppath_step_refr_2d (Workspace & ws, Ppath & ppath, ConstVectorView p_grid, ConstVectorView lat_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, ConstVectorView z_surface, const Numeric & lmax, const Agenda & refr_index_agenda, const String & rtrace_method, const Numeric & lraytrace)
Calculates 2D propagation path steps, with refraction, using a simple and fast ray tracing scheme.
Works as the same function for 1D despite that some input arguments are of different type.
Parameters
[in,out] ws Current Workspace
[out] ppath A Ppath structure.
[in] p_grid Pressure grid.
[in] lat_grid Latitude grid.
[in] z_field As the WSV with the same name.
[in] t_field As the WSV with the same name.
[in] vmr_field As the WSV with the same name.
[in] f_grid As the WSV with the same name.
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitudes.
[in] lmax Maximum allowed length between the path points.
[in] refr_index_air_agenda The WSV with the same name.
[in] rtrace_method String giving which ray tracing method to use. See the function for options.
[in] lraytrace Maximum allowed length for ray tracing steps.
Author
Patrick Eriksson
Date
2002-12-02
Definition at line 3905 of file ppath.cc.
References ARTS::Var::f_grid(), joker, ARTS::Var::lat_grid(), Array< base >::nelem(), ARTS::Var::p_grid(), ARTS::Var::ppath(), ppath_end_2d(), ppath_start_2d(), raytrace_2d_linear_basic(), ARTS::Var::refellipsoid(), ARTS::Var::refr_index_air_agenda(), ARTS::Var::t_field(), ARTS::Var::vmr_field(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepRefractionBasic().
ppath_step_refr_3d()
void ppath_step_refr_3d (Workspace & ws, Ppath & ppath, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View z_field, ConstTensor3View t_field, ConstTensor4View vmr_field, ConstVectorView f_grid, ConstVectorView refellipsoid, ConstMatrixView z_surface, const Numeric & lmax, const Agenda & refr_index_agenda, const String & rtrace_method, const Numeric & lraytrace)
Calculates 3D propagation path steps, with refraction, using a simple and fast ray tracing scheme.
Works as the same function for 1D despite that some input arguments are of different type.
Parameters
[in,out] ws Current Workspace
[out] ppath A Ppath structure.
[in] p_grid Pressure grid.
[in] lat_grid Latitude grid.
[in] lon_grid Longitude grid.
[in] z_field Geometrical altitudes.
[in] t_field Atmospheric temperatures.
[in] vmr_field VMR values.
[in] f_grid As the WSV with the same name.
[in] refellipsoid As the WSV with the same name.
[in] z_surface Surface altitudes.
[in] lmax Maximum allowed length between the path points.
[in] refr_index_air_agenda The WSV with the same name.
[in] rtrace_method String giving which ray tracing method to use. See the function for options.
[in] lraytrace Maximum allowed length for ray tracing steps.
Author
Patrick Eriksson
Date
2003-01-08
Definition at line 4320 of file ppath.cc.
References ARTS::Var::f_grid(), ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), Array< base >::nelem(), ARTS::Var::p_grid(), ARTS::Var::ppath(), ppath_end_3d(), ppath_start_3d(), raytrace_3d_linear_basic(), ARTS::Var::refellipsoid(), ARTS::Var::refr_index_air_agenda(), ARTS::Var::t_field(), ARTS::Var::vmr_field(), ARTS::Var::z_field(), and ARTS::Var::z_surface().
Referenced by ppath_stepRefractionBasic().
ppath_what_background()
Index ppath_what_background (const Ppath & ppath)
Returns the case number for the radiative background.
See further the function ppath_set_background.
Parameters
[in] ppath A Ppath structure.
Returns
The case number.
Author
Patrick Eriksson
Date
2002-05-17
Definition at line 1479 of file ppath.cc.
References ARTS::Var::ppath().
Referenced by defocusing_general_sub(), defocusing_sat2sat(), get_iy_of_background(), iyActiveSingleScat(), iyActiveSingleScat2(), iyEmissionStandard(), iyHybrid(), iyHybrid2(), iyTransmissionStandard(), mcPathTraceRadar(), ppath_append(), ppath_calc(), ppath_stepGeometric(), ppath_stepRefractionBasic(), and ppathFromRtePos2().
resolve_lon()
void resolve_lon (Numeric & lon, const Numeric & lon5, const Numeric & lon6)
Resolves which longitude angle that shall be used.
Longitudes are allowed to vary between -360 and 360 degress, while the inverse trigonomtric functions returns values between -180 and 180. This function determines if the longitude shall be shifted -360 or +360 to fit the longitudes set by the user.
The argument lon as input is a value calculated by some inverse trigonometric function. The arguments lon5 and lon6 are the lower and upper limit for the probable range for lon. The longitude lon* will be shifted with -360 or +360 degrees if lon is significantly outside lon5 and lon6. No error is given if it is not possible to obtain a value between lon5 and lon6.
Parameters
[in,out] lon Longitude, possible shifted when returned.
[in] lon5 Lower limit of probable range for lon.
[in] lon6 Upper limit of probable range for lon
Author
Patrick Eriksson
Date
2003-01-05
Definition at line 500 of file ppath.cc.
References ARTS::Var::lon().
Referenced by do_gridcell_3d_byltest(), ppath_start_stepping(), raytrace_3d_linear_basic(), surf_radius_at_l(), and surfaceFastem().
zaaa2cart()
void zaaa2cart (Numeric & dx, Numeric & dy, Numeric & dz, const Numeric & za, const Numeric & aa)
Converts zenith and azimuth angles to a cartesian unit vector.
This function and the sister function cart2zaaa handles transformation of line-of-sights. This in contrast to the sph/poslos functions that handles positions, or combinations of positions and line-of-sight.
The cartesian coordinate system used for these two functions can be defined as z : za = 0 x : za=90, aa=0 y : za=90, aa=90
Parameters
[out] dx x-part of LOS unit vector.
[out] dy y-part of LOS unit vector.
[out] dz z-part of LOS unit vector.
[in] za LOS zenith angle at observation position.
[in] aa LOS azimuth angle at observation position.
Author
Patrick Eriksson
Date
2009-10-02
Definition at line 312 of file ppath.cc.
References DEG2RAD, and dx.
Referenced by add_za_aa(), adjust_los(), diff_za_aa(), and specular_losCalc().
zaaa2enu()
void zaaa2enu (Numeric & de, Numeric & dn, Numeric & du, const Numeric & za, const Numeric & aa)
Converts zenith and azimuth angles to ENU unit vector.
This function and the sister function enu2zaaa handles transformation of line-of-sights, from and to ENU (east-north-up). The ENU vector is normalised to have length 1.
Parameters
[out] de e-part of LOS unit vector.
[out] dn n-part of LOS unit vector.
[out] du u-part of LOS unit vector.
[in] za LOS zenith angle at observation position.
[in] aa LOS azimuth angle at observation position.
Author
Patrick Eriksson
Date
2020-09-17
Definition at line 335 of file ppath.cc.
References DEG2RAD.
Variable Documentation
ANGTOL
const Numeric ANGTOL = 1e-6
Width of zenith and nadir directions.
This variable defines how much zenith and azimuth angles can deviate from 0, 90 and 180 degrees, but still be treated to be 0, 90 or 180. For example, an azimuth angle of 180-0.999*ANGTOL will be treated as a strictly southward observation. However, the angles are not allowed to go outside their defined range. This means, for example, that values above 180 are never allowed.
Definition at line 108 of file ppath.h.
Referenced by cart2pol(), cart2poslos(), cart2sph(), do_gridcell_2d_byltest(), do_gridcell_3d_byltest(), geompath_from_r1_to_r2(), plevel_crossing_2d(), r_crossing_3d(), and raytrace_3d_linear_basic().
POLELAT
const Numeric POLELAT = 90 - 1e-8
Size of north and south poles.
Latitudes with an absolute value > POLELAT are considered to be on the south or north pole for 3D.
Definition at line 97 of file ppath.h.
Referenced by cart2poslos(), cart2sph(), do_gridcell_3d_byltest(), plevel_slope_3d(), poslos2cart(), and ppath_end_3d().