ARTS: predefined_absorption_models.cc File Reference
predefined_absorption_models.cc File Reference
Full absorption models of various kinds.
#include "predefined_absorption_models.h"
#include "lin_alg.h"
#include "linescaling.h"
#include "wigner_functions.h"
Functions
constexpr LineShape::SingleSpeciesModel init_mpm2020_slsm (Numeric g00, Numeric y0, Numeric y1, Numeric g0, Numeric g1, Numeric dv0, Numeric dv1, Numeric x)
constexpr std::array< LineShape::SingleSpeciesModel, nlines_mpm2020 > init_mpm2020_lsm ()
constexpr QuantumIdentifier init_mpm2020_qid (Index species, Index isot, Rational Jup, Rational Jlow, Rational Nup, Rational Nlow)
constexpr std::array< QuantumIdentifier, nlines_mpm2020 > init_mpm2020_qids (const Index &species, const Index &isot)
void normalize_relaxation_matrix (Eigen::Ref< Eigen::MatrixXcd > W, const Eigen::Ref< Eigen::ArrayXd > rho, const Eigen::Ref< Eigen::ArrayXd > d)
Variables
constexpr auto necs2020 = 38
constexpr auto nlines_mpm2020 = necs2020 + 6
Detailed Description
Full absorption models of various kinds.
Author
Richard Larsson
Date
2020-01-29
Definition in file predefined_absorption_models.cc.
Function Documentation
init_mpm2020_lsm()
constexpr std::array<LineShape::SingleSpeciesModel, nlines_mpm2020> init_mpm2020_lsm () constexpr
Definition at line 59 of file predefined_absorption_models.cc.
References ARTS::Var::g0(), init_mpm2020_slsm(), and ARTS::Var::x().
Referenced by Absorption::PredefinedModel::makarov2020_o2_lines_ecs(), and Absorption::PredefinedModel::makarov2020_o2_lines_mpm().
init_mpm2020_qid()
constexpr QuantumIdentifier init_mpm2020_qid (Index species, Index isot, Rational Jup, Rational Jlow, Rational Nup, Rational Nlow) constexpr
Definition at line 195 of file predefined_absorption_models.cc.
init_mpm2020_qids()
constexpr std::array<QuantumIdentifier, nlines_mpm2020> init_mpm2020_qids (const Index & species, const Index & isot) constexpr
Definition at line 201 of file predefined_absorption_models.cc.
Referenced by Absorption::PredefinedModel::makarov2020_o2_lines_ecs(), and Absorption::PredefinedModel::makarov2020_o2_lines_mpm().
init_mpm2020_slsm()
constexpr LineShape::SingleSpeciesModel init_mpm2020_slsm (Numeric g00, Numeric y0, Numeric y1, Numeric g0, Numeric g1, Numeric dv0, Numeric dv1, Numeric x) constexpr
Definition at line 37 of file predefined_absorption_models.cc.
References ARTS::Var::g0(), LineShape::T1, LineShape::T4, and ARTS::Var::x().
Referenced by init_mpm2020_lsm().
normalize_relaxation_matrix()
void normalize_relaxation_matrix (Eigen::Ref< Eigen::MatrixXcd > W, const Eigen::Ref< Eigen::ArrayXd > rho, const Eigen::Ref< Eigen::ArrayXd > d)
Definition at line 510 of file predefined_absorption_models.cc.
References abs, and necs2020.
Variable Documentation
necs2020
constexpr auto necs2020 = 38 constexpr
Definition at line 33 of file predefined_absorption_models.cc.
Referenced by normalize_relaxation_matrix().
nlines_mpm2020
constexpr auto nlines_mpm2020 = necs2020 + 6 constexpr
Definition at line 34 of file predefined_absorption_models.cc.
Referenced by Absorption::PredefinedModel::makarov2020_o2_lines_mpm().