ARTS: propagationmatrix.h File Reference
propagationmatrix.h File Reference
Stuff related to the propagation matrix.
#include "complex.h"
#include "matpackIV.h"
Classes
class LazyScale< base >
Class to help with hidden temporary variables for operations of type Numeric times Class.
class PropagationMatrix
class StokesVector
Stokes vector is as Propagation matrix but only has 4 possible values.
Typedefs
typedef Array< PropagationMatrix > ArrayOfPropagationMatrix
typedef Array< ArrayOfPropagationMatrix > ArrayOfArrayOfPropagationMatrix
typedef Array< StokesVector > ArrayOfStokesVector
typedef Array< ArrayOfStokesVector > ArrayOfArrayOfStokesVector
typedef Array< ArrayOfArrayOfStokesVector > ArrayOfArrayOfArrayOfStokesVector
Functions
Eigen::Matrix< double, 1, 1 > matrix1 (const Numeric &a) noexcept
Eigen::Matrix2d matrix2 (const Numeric &a, const Numeric &b) noexcept
Eigen::Matrix3d matrix3 (const Numeric &a, const Numeric &b, const Numeric &c, const Numeric &u) noexcept
Eigen::Matrix4d matrix4 (const Numeric &a, const Numeric &b, const Numeric &c, const Numeric &d, const Numeric &u, const Numeric &v, const Numeric &w) noexcept
template<int N>
Eigen::Matrix< double, N, N > matrix_from_vectorview (const ConstVectorView vec)
Eigen::Matrix< double, 1, 1 > matrix1 (const ConstMatrixView m) noexcept
Eigen::Matrix2d matrix2 (const ConstMatrixView m) noexcept
Eigen::Matrix3d matrix3 (const ConstMatrixView m) noexcept
Eigen::Matrix4d matrix4 (const ConstMatrixView m) noexcept
Eigen::Matrix< double, 1, 1 > inv1 (const Numeric &a) noexcept
Eigen::Matrix2d inv2 (const Numeric &a, const Numeric &b) noexcept
Eigen::Matrix3d inv3 (const Numeric &a, const Numeric &b, const Numeric &c, const Numeric &u) noexcept
Eigen::Matrix4d inv4 (const Numeric &a, const Numeric &b, const Numeric &c, const Numeric &d, const Numeric &u, const Numeric &v, const Numeric &w) noexcept
void compute_transmission_matrix (Tensor3View T, const Numeric &r, const PropagationMatrix &upper_level, const PropagationMatrix &lower_level, const Index iz=0, const Index ia=0)
Compute the matrix exponent as the transmission matrix of this propagation matrix.
void compute_transmission_matrix_from_averaged_matrix_at_frequency (MatrixView T, const Numeric &r, const PropagationMatrix &averaged_propagation_matrix, const Index iv, const Index iz=0, const Index ia=0)
Compute the matrix exponent as the transmission matrix of this propagation matrix.
void compute_transmission_matrix_and_derivative (Tensor3View T, Tensor4View dT_upper_level, Tensor4View dT_lower_level, const Numeric &r, const PropagationMatrix &upper_level, const PropagationMatrix &lower_level, const Array< PropagationMatrix > &dprop_mat_upper_level, const Array< PropagationMatrix > &dprop_mat_lower_level, const Numeric &dr_dTu=0.0, const Numeric &dr_dTl=0.0, const Index it=-1, const Index iz=0, const Index ia=0)
std::ostream & operator<< (std::ostream &os, const PropagationMatrix &pm)
output operator
std::ostream & operator<< (std::ostream &os, const ArrayOfPropagationMatrix &apm)
output operator
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfPropagationMatrix &aapm)
output operator
std::ostream & operator<< (std::ostream &os, const StokesVector &pm)
std::ostream & operator<< (std::ostream &os, const ArrayOfStokesVector &apm)
std::ostream & operator<< (std::ostream &os, const ArrayOfArrayOfStokesVector &aapm)
LazyScale< PropagationMatrix > operator* (const PropagationMatrix &pm, const Numeric &x)
Returns a lazy multiplier.
LazyScale< PropagationMatrix > operator* (const Numeric &x, const PropagationMatrix &pm)
Returns a lazy multiplier.
Detailed Description
Stuff related to the propagation matrix.
Author
Richard Larsson
Date
2017-06-23
This implementation takes advantage of symmetries to lower memory and computational costs
Some standard functions applied on the propagation matrix have been included but far from all.
Present support is for stokes dim 1-4 however please take note that circular polarization delay variable's position in the internal mdata structure moves depending on if stokes_dim is 3 or 4. It is not present elsewhere...
Definition in file propagationmatrix.h.
Typedef Documentation
ArrayOfArrayOfArrayOfStokesVector
typedef Array<ArrayOfArrayOfStokesVector> ArrayOfArrayOfArrayOfStokesVector
Definition at line 1516 of file propagationmatrix.h.
ArrayOfArrayOfPropagationMatrix
typedef Array<ArrayOfPropagationMatrix> ArrayOfArrayOfPropagationMatrix
Definition at line 1139 of file propagationmatrix.h.
ArrayOfArrayOfStokesVector
typedef Array<ArrayOfStokesVector> ArrayOfArrayOfStokesVector
Definition at line 1515 of file propagationmatrix.h.
ArrayOfPropagationMatrix
typedef Array<PropagationMatrix> ArrayOfPropagationMatrix
Definition at line 1138 of file propagationmatrix.h.
ArrayOfStokesVector
typedef Array<StokesVector> ArrayOfStokesVector
Definition at line 1514 of file propagationmatrix.h.
Function Documentation
compute_transmission_matrix()
void compute_transmission_matrix (Tensor3View T, const Numeric & r, const PropagationMatrix & upper_level, const PropagationMatrix & lower_level, const Index iz = 0, const Index ia = 0)
Compute the matrix exponent as the transmission matrix of this propagation matrix.
The propagation matrix is multiplied by -r and level-averaged before exponent is applied.
upper_level and lower_level propagation matrices should thus be the level matrices and r the distance between these levels. The same is true for the derivative matrices.
Stokes dim 1 and 4 have been tested more. Stokes dim 2 and 3 have been found to work but could still have hidden errors for uncommon cases
Parameters
[in,out] T transmission tensor with outmost dimension being frequency
[in] r the distance over which the propagation matrix causes the transmission
[in] upper_level The upper level propagation matrix
[in] lower_level The lower level propagation matrix
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 33 of file propagationmatrix.cc.
References joker, PropagationMatrix::K12(), PropagationMatrix::Kjj(), PropagationMatrix::NumberOfFrequencies(), and PropagationMatrix::StokesDimensions().
Referenced by get_stepwise_transmission_matrix().
compute_transmission_matrix_and_derivative()
void compute_transmission_matrix_and_derivative (Tensor3View T, Tensor4View dT_upper_level, Tensor4View dT_lower_level, const Numeric & r, const PropagationMatrix & upper_level, const PropagationMatrix & lower_level, const Array< PropagationMatrix > & dprop_mat_upper_level, const Array< PropagationMatrix > & dprop_mat_lower_level, const Numeric & dr_dTu = 0.0, const Numeric & dr_dTl = 0.0, const Index it = -1, const Index iz = 0, const Index ia = 0)
Compute the matrix exponent as the transmission matrix of this propagation matrix
The propagation matrix is multiplied by -r and level-averaged before exponent is applied.
upper_level and lower_level propagation matrices should thus be the level matrices and r the distance between these levels. The same is true for the derivative matrices.
Stokes dim 1 and 4 have been tested more. Stokes dim 2 and 3 have been found to work but could still have hidden errors for uncommon cases
Parameters
[in,out] T transmission tensor with outmost dimension being frequency
[in,out] dT_upp transmission tensors derivative with respect to derivatives of the propagation matrix for upper level
[in,out] dT_low transmission tensors derivative with respect to derivatives of the propagation matrix for lower level
[in] r the distance over which the propagation matrix causes the transmission
[in] upper_level The upper level propagation matrix
[in] lower_level The lower level propagation matrix
[in] dprop_mat_upp derivatives of the upper propagation matrix with respect to some parameter (is multiplied by -0.5 r)
[in] dprop_mat_low derivatives of the lower propagation matrix with respect to some parameter (is multiplied by -0.5 r)
[in] dr_dTu Distance temperature derivative for upper level
[in] dr_dTl Distance temperature derivative for lower level
[in] it Position of temperature derivative (ignored at -1)
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 478 of file propagationmatrix.cc.
References joker, PropagationMatrix::K12(), PropagationMatrix::Kjj(), Array< base >::nelem(), PropagationMatrix::NumberOfFrequencies(), and PropagationMatrix::StokesDimensions().
Referenced by get_stepwise_transmission_matrix().
compute_transmission_matrix_from_averaged_matrix_at_frequency()
void compute_transmission_matrix_from_averaged_matrix_at_frequency (MatrixView T, const Numeric & r, const PropagationMatrix & averaged_propagation_matrix, const Index iv, const Index iz = 0, const Index ia = 0)
Compute the matrix exponent as the transmission matrix of this propagation matrix.
The propagation matrix is multiplied by -r and level-averaged before exponent is applied.
Stokes dim 1 and 4 have been tested more. Stokes dim 2 and 3 have been found to work but could still have hidden errors for uncommon cases
Parameters
[in,out] T transmission matrix at the position
[in] r the distance over which the propagation matrix causes the transmission
[in] averaged_propagation_matrix The propagation matrix
[in] iv Frequency index
[in] iz Zenith index
[in] ia Azimuth index
Definition at line 272 of file propagationmatrix.cc.
References PropagationMatrix::K12(), PropagationMatrix::Kjj(), sqrt(), and PropagationMatrix::StokesDimensions().
Referenced by rte_step_doit_replacement().
inv1()
Eigen::Matrix<double, 1, 1> inv1 (const Numeric & a) inline noexcept
Definition at line 136 of file propagationmatrix.h.
inv2()
Eigen::Matrix2d inv2 (const Numeric & a, const Numeric & b) inline noexcept
Definition at line 140 of file propagationmatrix.h.
Referenced by stepwise_source().
inv3()
Eigen::Matrix3d inv3 (const Numeric & a, const Numeric & b, const Numeric & c, const Numeric & u) inline noexcept
Definition at line 144 of file propagationmatrix.h.
Referenced by stepwise_source().
inv4()
Eigen::Matrix4d inv4 (const Numeric & a, const Numeric & b, const Numeric & c, const Numeric & d, const Numeric & u, const Numeric & v, const Numeric & w) inline noexcept
Definition at line 161 of file propagationmatrix.h.
Referenced by stepwise_source().
matrix1() [1/2]
Eigen::Matrix<double, 1, 1> matrix1 (const ConstMatrixView m) inline noexcept
Definition at line 95 of file propagationmatrix.h.
matrix1() [2/2]
Eigen::Matrix<double, 1, 1> matrix1 (const Numeric & a) inline noexcept
Definition at line 40 of file propagationmatrix.h.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), and matrix_from_vectorview().
matrix2() [1/2]
Eigen::Matrix2d matrix2 (const ConstMatrixView m) inline noexcept
Definition at line 99 of file propagationmatrix.h.
matrix2() [2/2]
Eigen::Matrix2d matrix2 (const Numeric & a, const Numeric & b) inline noexcept
Definition at line 44 of file propagationmatrix.h.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), matrix_from_vectorview(), and stepwise_source().
matrix3() [1/2]
Eigen::Matrix3d matrix3 (const ConstMatrixView m) inline noexcept
Definition at line 103 of file propagationmatrix.h.
matrix3() [2/2]
Eigen::Matrix3d matrix3 (const Numeric & a, const Numeric & b, const Numeric & c, const Numeric & u) inline noexcept
Definition at line 48 of file propagationmatrix.h.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), matrix_from_vectorview(), and stepwise_source().
matrix4() [1/2]
Eigen::Matrix4d matrix4 (const ConstMatrixView m) inline noexcept
Definition at line 116 of file propagationmatrix.h.
matrix4() [2/2]
Eigen::Matrix4d matrix4 (const Numeric & a, const Numeric & b, const Numeric & c, const Numeric & d, const Numeric & u, const Numeric & v, const Numeric & w) inline noexcept
Definition at line 55 of file propagationmatrix.h.
Referenced by bulk_backscatter(), bulk_backscatter_derivative(), matrix_from_vectorview(), and stepwise_source().
matrix_from_vectorview()
template<int N> Eigen::Matrix<double, N, N> matrix_from_vectorview (const ConstVectorView vec)
Definition at line 82 of file propagationmatrix.h.
References matrix1(), matrix2(), matrix3(), matrix4(), and N.
operator*() [1/2]
LazyScale<PropagationMatrix> operator* (const Numeric & x, const PropagationMatrix & pm) inline
Returns a lazy multiplier.
Parameters
[in] x Scale
[in] pm Propagation matrix
Returns
LazyScale<PropagationMatrix> A lazy multiplier
Definition at line 1540 of file propagationmatrix.h.
References x.
operator*() [2/2]
LazyScale<PropagationMatrix> operator* (const PropagationMatrix & pm, const Numeric & x) inline
Returns a lazy multiplier.
Parameters
[in] pm Propagation matrix
[in] x Scale
Returns
LazyScale<PropagationMatrix> A lazy multiplier
Definition at line 1529 of file propagationmatrix.h.
References x.
operator<<() [1/6]
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfPropagationMatrix & aapm)
output operator
Definition at line 2047 of file propagationmatrix.cc.
operator<<() [2/6]
std::ostream& operator<< (std::ostream & os, const ArrayOfArrayOfStokesVector & aapm)
Definition at line 2064 of file propagationmatrix.cc.
operator<<() [3/6]
std::ostream& operator<< (std::ostream & os, const ArrayOfPropagationMatrix & apm)
output operator
Definition at line 2041 of file propagationmatrix.cc.
operator<<() [4/6]
std::ostream& operator<< (std::ostream & os, const ArrayOfStokesVector & apm)
Definition at line 2059 of file propagationmatrix.cc.
operator<<() [5/6]
std::ostream& operator<< (std::ostream & os, const PropagationMatrix & pm)
output operator
Definition at line 2036 of file propagationmatrix.cc.
References PropagationMatrix::Data().
operator<<() [6/6]
std::ostream& operator<< (std::ostream & os, const StokesVector & pm)
Definition at line 2054 of file propagationmatrix.cc.
References PropagationMatrix::Data().