ARTS: propmat_field.cc File Reference
propmat_field.cc File Reference
#include "propmat_field.h"
#include "rte.h"
#include "special_interp.h"
#include "transmissionmatrix.h"
Functions
void field_of_propagation (Workspace &ws, FieldOfPropagationMatrix &propmat_field, FieldOfStokesVector &absorption_field, FieldOfStokesVector &additional_source_field, const Index &stokes_dim, const Vector &f_grid, const Vector &p_grid, const Tensor3 &z_field, const Tensor3 &t_field, const EnergyLevelMap &nlte_field, const Tensor4 &vmr_field, const ArrayOfRetrievalQuantity &jacobian_quantities, const Agenda &propmat_clearsky_agenda)
Creates a field of propagation matrices, absorption vectors, and source vectors.
FieldOfTransmissionMatrix transmat_field_calc_from_propmat_field (const FieldOfPropagationMatrix &propmat_field, const Numeric &r)
Get a field of transmission matrices from the propagation matrix field.
void emission_from_propmat_field (Workspace &ws, ArrayOfRadiationVector &lvl_rad, ArrayOfRadiationVector &src_rad, ArrayOfTransmissionMatrix &lyr_tra, ArrayOfTransmissionMatrix &tot_tra, const FieldOfPropagationMatrix &propmat_field, const FieldOfStokesVector &absorption_field, const FieldOfStokesVector &additional_source_field, const Vector &f_grid, const Tensor3 &t_field, const EnergyLevelMap &nlte_field, const Ppath &ppath, const Agenda &iy_main_agenda, const Agenda &iy_space_agenda, const Agenda &iy_surface_agenda, const Agenda &iy_cloudbox_agenda, const Tensor3 &surface_props_data, const Verbosity &verbosity)
Computes the radiation and transmission from fields of atmospheric propagation.
Function Documentation
emission_from_propmat_field()
void emission_from_propmat_field (Workspace & ws, ArrayOfRadiationVector & lvl_rad, ArrayOfRadiationVector & src_rad, ArrayOfTransmissionMatrix & lyr_tra, ArrayOfTransmissionMatrix & tot_tra, const FieldOfPropagationMatrix & propmat_field, const FieldOfStokesVector & absorption_field, const FieldOfStokesVector & additional_source_field, const Vector & f_grid, const Tensor3 & t_field, const EnergyLevelMap & nlte_field, const Ppath & ppath, const Agenda & iy_main_agenda, const Agenda & iy_space_agenda, const Agenda & iy_surface_agenda, const Agenda & iy_cloudbox_agenda, const Tensor3 & surface_props_data, const Verbosity & verbosity)
Computes the radiation and transmission from fields of atmospheric propagation.
Only for 1D atmospheres for now.
Computes The forward simulations by interpolating the fields of radiative properties to the selected propagation path.
Not well-tested.
Parameters
[in] ws A workspace
[out] lvl_rad Level by level radiation
[out] src_rad Level by level source function
[out] lyr_tra Layered transmission
[out] tot_tra Total transmission from layer to background
[in] propmat_field 3D field of propagation matrices
[in] absorption_field A 3D field of absorption vectors
[in] additional_source_field A 3D field of source vectors
[in] f_grid As WSV
[in] t_field As WSV
[in] nlte_field As WSV
[in] ppath As WSV
[in] iy_main_agenda As WSA
[in] iy_space_agenda As WSA
[in] iy_surface_agenda As WSA
[in] iy_cloudbox_agenda As WSA
[in] surface_props_data As WSV
[in] verbosity Level of verbosity in underlying calls
Definition at line 119 of file propmat_field.cc.
References a, ARTS_USER_ERROR_IF, cumulative_transmission(), Emission, ARTS::Var::f_grid(), Forward, get_iy_of_background(), get_stepwise_blackbody_radiation(), interp_atmfield_by_gp(), ARTS::Var::iy(), ARTS::Var::iy_cloudbox_agenda(), ARTS::Var::iy_main_agenda(), ARTS::Var::iy_space_agenda(), ARTS::Var::iy_surface_agenda(), ARTS::Var::nlte_field(), ns, ARTS::Var::ppath(), stepwise_source(), stepwise_transmission(), ARTS::Var::surface_props_data(), swap(), ARTS::Var::t_field(), update_radiation_vector(), and ARTS::Var::verbosity().
field_of_propagation()
void field_of_propagation (Workspace & ws, FieldOfPropagationMatrix & propmat_field, FieldOfStokesVector & absorption_field, FieldOfStokesVector & additional_source_field, const Index & stokes_dim, const Vector & f_grid, const Vector & p_grid, const Tensor3 & z_field, const Tensor3 & t_field, const EnergyLevelMap & nlte_field, const Tensor4 & vmr_field, const ArrayOfRetrievalQuantity & jacobian_quantities, const Agenda & propmat_clearsky_agenda)
Creates a field of propagation matrices, absorption vectors, and source vectors.
Parameters
[in] ws A workspace
[out] propmat_field A 3D field of propagation matrices
[out] absorption_field A 3D field of absorption vectors
[out] additional_source_field A 3D field of source vectors
[in] stokes_dim As WSV
[in] f_grid As WSV
[in] p_grid As WSV
[in] z_field As WSV
[in] t_field As WSV
[in] nlte_field As WSV
[in] vmr_field As WSV
[in] jacobian_quantities As WSV
[in] propmat_clearsky_agenda As WSA
Definition at line 35 of file propmat_field.cc.
References ARTS_USER_ERROR_IF, ARTS::Var::f_grid(), ARTS::Var::jacobian_quantities(), ARTS::Var::propmat_clearsky_agenda(), ARTS::Var::stokes_dim(), and ARTS::Var::z_field().
transmat_field_calc_from_propmat_field()
FieldOfTransmissionMatrix transmat_field_calc_from_propmat_field (const FieldOfPropagationMatrix & propmat_field, const Numeric & r = 1.0)
Get a field of transmission matrices from the propagation matrix field.
Parameters
[in] propmat_field A 3D field of propagation matrices
[in] r The distance
Returns
FieldOfTransmissionMatrix
Definition at line 106 of file propmat_field.cc.
References Field3D< base >::ncols(), Field3D< base >::npages(), and Field3D< base >::nrows().