ARTS: psd.h File Reference
psd.h File Reference
Internal functions associated with size distributions.
#include "array.h"
#include "gridded_fields.h"
#include "interpolation.h"
#include "matpackVII.h"
#include "messages.h"
#include "optproperties.h"
#include "ppath.h"
Macros
#define START_OF_PSD_METHODS()
Functions
void psd_cloudice_MH97 (Vector &psd, const Vector &diameter, const Numeric &iwc, const Numeric &t, const bool noisy)
The MH97 cloud ice PSD.
void psd_mgd_mass_and_something (Matrix &psd_data, Tensor3 &dpsd_data_dx, const String &something, const Vector &psd_size_grid, const Vector &pnd_agenda_input_t, const Matrix &pnd_agenda_input, const ArrayOfString &pnd_agenda_input_names, const ArrayOfString &dpnd_data_dx_names, const Numeric &scat_species_a, const Numeric &scat_species_b, const Numeric &n0, const Numeric &mu, const Numeric &la, const Numeric &ga, const Numeric &t_min, const Numeric &t_max, const Index &picky, const Verbosity &)
Code common to MGD PSD involving the integrated mass.
void psd_mono_common (Matrix &psd_data, Tensor3 &dpsd_data_dx, const String &type, const Vector &pnd_agenda_input_t, const Matrix &pnd_agenda_input, const ArrayOfString &pnd_agenda_input_names, const ArrayOfString &dpnd_data_dx_names, const ArrayOfArrayOfScatteringMetaData &scat_meta, const Index &species_index, const Numeric &t_min, const Numeric &t_max, const Index &picky, const Verbosity &)
Code common to PSDs of mono type.
void psd_rain_W16 (Vector &psd, const Vector &diameter, const Numeric &rwc)
The Wang16 rain DSD DEPRECATED BY NEW MGD_SMM_COMMON Only included for compatibility with "old" pnd_fieldCalcFromscat_speciesField.
void psd_mgd_smm_common (Matrix &psd_data, Tensor3 &dpsd_data_dx, const String &psd_name, const Vector &psd_size_grid, const Vector &pnd_agenda_input_t, const Matrix &pnd_agenda_input, const ArrayOfString &pnd_agenda_input_names, const ArrayOfString &dpnd_data_dx_names, const Numeric &scat_species_a, const Numeric &scat_species_b, const Numeric &n_alpha_in, const Numeric &n_b_in, const Numeric &mu_in, const Numeric &gamma_in, const Numeric &t_min, const Numeric &t_max, const Index &picky, const Verbosity &)
Code common to a number of modified gamma PSDs used with single-moment mass schemes.
void psd_snow_F07 (Vector &psd, const Vector &diameter, const Numeric &swc, const Numeric &t, const Numeric alpha, const Numeric beta, const String &regime)
The F07 snow PSD.
void psd_SB06 (Vector &psd, Matrix &dpsd, const Vector &mass, const Numeric &N_tot, const Numeric &WC, const String &hydrometeor_type)
void psd_MY05 (Vector &psd, Matrix &dpsd, const Vector &diameter_max, const Numeric N_tot, const Numeric WC, const String psd_type)
Numeric dm_from_iwc_n0 (Numeric iwc, Numeric n0, Numeric rho)
Derives Dm from IWC and N0star.
Numeric n0_from_iwc_dm (Numeric iwc, Numeric dm, Numeric rho)
Derives N0star from IWC and Dm.
Numeric n0_from_t (Numeric t)
Sets N0star based on temperature.
Detailed Description
Internal functions associated with size distributions.
Author
Jana Mendrok Patrick Eriksson
Date
2017-11-05
Definition in file psd.h.
Macro Definition Documentation
START_OF_PSD_METHODS
#define START_OF_PSD_METHODS ()
Definition at line 45 of file psd.h.
Function Documentation
dm_from_iwc_n0()
Numeric dm_from_iwc_n0 (Numeric iwc, Numeric n0, Numeric rho)
Derives Dm from IWC and N0star.
For definition of Dm and N0star follows the DARDAR PSD.
Parameters
[in] iwc IWC-value
[in] n0 N0star value
[in] rho Density (of water or ice)
Returns
Derived Dm-value
Author
Simon Pfreundschuh
Date
20??-??-??
Definition at line 1249 of file psd.cc.
n0_from_iwc_dm()
Numeric n0_from_iwc_dm (Numeric iwc, Numeric dm, Numeric rho)
Derives N0star from IWC and Dm.
For definition of Dm and N0star follows the DARDAR PSD.
Parameters
[in] iwc IWC-value
[in] dm Dm-value
[in] rho Density (of water or ice)
Returns
Derived N0star-value
Author
Simon Pfreundschuh
Date
20??-??-??
Definition at line 1257 of file psd.cc.
n0_from_t()
Numeric n0_from_t (Numeric t)
Sets N0star based on temperature.
For definition of N0star follows the DARDAR PSD.
This a priori parameterisation is taken from Table 5 in "Normalized particle size distribution for remote sensing application" by Delanoë et al., JGR, 2014.
Parameters
[in] t temperature
Returns
Derived N0star-value
Author
Simon Pfreundschuh
Date
20??-??-??
Definition at line 1265 of file psd.cc.
psd_cloudice_MH97()
void psd_cloudice_MH97 (Vector & psd, const Vector & diameter, const Numeric & iwc, const Numeric & t, const bool noisy)
The MH97 cloud ice PSD.
Handles a vector of sizes at a time. Implicitly assumes particles of water ice. Strictly requires IWC and T to be positive, i.e. calling method needs to ensure this.
Parameters
[out] psd particle number density per size interval [#/m3*m]
[in] diameter size of the scattering elements (supposed to be mass (aka volume) equivalent diameter of pure ice particle) [m]
[in] iwc atmospheric ice water content [kg/m3]
t atmospheric temperature [K]
noisy flag whether to add noise onto PSD parameters according to their reported error statistics
Author
Jana Mendrok, Daniel Kreyling
Date
2017-06-07
Definition at line 58 of file psd.cc.
References a, a1, ARTS_ASSERT, b1, b2, DENSITY_OF_ICE, ARTS::Var::mc_seed(), min, ConstVectorView::nelem(), PI, pow(), ran_gaussian(), Vector::resize(), Rng::seed(), sqrt(), and ARTS::Var::time().
Referenced by psdMcFarquaharHeymsfield97().
psd_mgd_mass_and_something()
void psd_mgd_mass_and_something (Matrix & psd_data, Tensor3 & dpsd_data_dx, const String & something, const Vector & psd_size_grid, const Vector & pnd_agenda_input_t, const Matrix & pnd_agenda_input, const ArrayOfString & pnd_agenda_input_names, const ArrayOfString & dpnd_data_dx_names, const Numeric & scat_species_a, const Numeric & scat_species_b, const Numeric & n0, const Numeric & mu, const Numeric & la, const Numeric & ga, const Numeric & t_min, const Numeric & t_max, const Index & picky, const Verbosity &)
Code common to MGD PSD involving the integrated mass.
Valid choices for something is "mean size", "median size", "mean particle mass" and "Ntot".
Parameters
[out] psd_data As the WSV wih same name
[out] dpsd_data_dx As the WSV wih same name
[in] something Text string gving the second moment
[in] psd_size_grid As the WSV wih same name
[in] pnd_agenda_input_t As the WSV wih same name
[in] pnd_agenda_input As the WSV wih same name
[in] pnd_agenda_input_names As the WSV wih same name
[in] dpnd_data_dx_names As the WSV wih same name
[in] scat_species_a As the WSV wih same name
[in] scat_species_b As the WSV wih same name
[in] n0 Selection for N0 parameter
[in] mu Selection for mu parameter
[in] la Selection for lambda parameter
[in] ga Selection for gamma parameter
[in] t_min PSD set to zero below this temperature
[in] t_max PSD set to zero above this temperature
[in] picky Triggers more check of input
Author
Patrick Eriksson
Date
2017-11-05
Definition at line 195 of file psd.cc.
References ARTS_ASSERT, ARTS::Var::dpsd_data_dx(), joker, mgd_with_derivatives(), ARTS::Var::pnd_agenda_input(), ARTS::Var::pnd_agenda_input_t(), pow(), ARTS::Var::psd_data(), ARTS::Var::psd_size_grid(), ARTS::Var::scat_species_a(), ARTS::Var::scat_species_b(), and START_OF_PSD_METHODS.
Referenced by psdModifiedGammaMassMeanParticleMass(), psdModifiedGammaMassNtot(), psdModifiedGammaMassXmean(), and psdModifiedGammaMassXmedian().
psd_mgd_smm_common()
void psd_mgd_smm_common (Matrix & psd_data, Tensor3 & dpsd_data_dx, const String & psd_name, const Vector & psd_size_grid, const Vector & pnd_agenda_input_t, const Matrix & pnd_agenda_input, const ArrayOfString & pnd_agenda_input_names, const ArrayOfString & dpnd_data_dx_names, const Numeric & scat_species_a, const Numeric & scat_species_b, const Numeric & n_alpha_in, const Numeric & n_b_in, const Numeric & mu_in, const Numeric & gamma_in, const Numeric & t_min, const Numeric & t_max, const Index & picky, const Verbosity &)
Code common to a number of modified gamma PSDs used with single-moment mass schemes.
All PSDs take the form n(D) = n_alpha lam^n_b D^mu exp(-lam*D^gamma).
Parameters
[out] psd_data As the WSV wih same name
[out] dpsd_data_dx As the WSV wih same name
[in] psd_name Name of selected PSD
[in] psd_size_grid As the WSV wih same name
[in] pnd_agenda_input_t As the WSV wih same name
[in] pnd_agenda_input As the WSV wih same name
[in] pnd_agenda_input_names As the WSV wih same name
[in] dpnd_data_dx_names As the WSV wih same name
[in] scat_species_a As the WSV wih same name
[in] scat_species_b As the WSV wih same name
[in] t_min PSD set to zero below this temperature
[in] t_max PSD set to zero above this temperature
[in] n_alpha_in Value of n_alpha for psd_name "generic"
[in] n_b_in Value of n_b for psd_name "generic"
[in] mu_in Value of mu for psd_name "generic"
[in] gamma_in Value of gamma for psd_name "generic"
[in] picky Triggers more check of input
Author
Stuart Fox
Date
2019-10-02
Definition at line 735 of file psd.cc.
References ARTS_ASSERT, ARTS::Var::pnd_agenda_input(), ARTS::Var::pnd_agenda_input_t(), ARTS::Var::scat_species_a(), ARTS::Var::scat_species_b(), and START_OF_PSD_METHODS.
Referenced by psdAbelBoutle12(), psdFieldEtAl19(), psdModifiedGammaMassSingleMoment(), and psdWangEtAl16().
psd_mono_common()
void psd_mono_common (Matrix & psd_data, Tensor3 & dpsd_data_dx, const String & type, const Vector & pnd_agenda_input_t, const Matrix & pnd_agenda_input, const ArrayOfString & pnd_agenda_input_names, const ArrayOfString & dpnd_data_dx_names, const ArrayOfArrayOfScatteringMetaData & scat_meta, const Index & species_index, const Numeric & t_min, const Numeric & t_max, const Index & picky, const Verbosity &)
Code common to PSDs of mono type.
Parameters
[out] psd_data As the WSV wih same name
[out] dpsd_data_dx As the WSV wih same name
[in] pnd_agenda_input_t As the WSV wih same name
[in] pnd_agenda_input As the WSV wih same name
[in] pnd_agenda_input_names As the WSV wih same name
[in] dpnd_data_dx_names As the WSV wih same name
[in] scat_meta As the WSV wih same name
[in] species_index Index of the scattering species of concern
[in] t_min PSD set to zero below this temperature
[in] t_max PSD set to zero above this temperature
[in] picky Triggers more check of input
Author
Patrick Eriksson
Date
2017-11-05
Definition at line 614 of file psd.cc.
References ARTS_ASSERT, ARTS::Var::dpsd_data_dx(), Absorption::nelem(), ARTS::Var::pnd_agenda_input(), ARTS::Var::pnd_agenda_input_t(), ARTS::Var::psd_data(), ARTS::Var::psd_size_grid(), ARTS::Var::scat_meta(), START_OF_PSD_METHODS, Hitran::type, and ARTS::Var::x().
Referenced by psdMonoDispersive(), and psdMonoMass().
psd_MY05()
void psd_MY05 (Vector & psd, Matrix & dpsd, const Vector & diameter_max, const Numeric N_tot, const Numeric WC, const String psd_type)
Calculates the particle number density field according to the Milbrandt and Yau two moment scheme, which is used in the GEM model. See also milbrandt and yau, 2005. One call of this function calculates one particle number density.
Returns
dN particle number density per diameter interval [#/m3/m]
Parameters
mass Mass of scattering particle [kg]
N_tot Total number of particles (0th moment) [#/m3/m/kg^mu]
M Total mass concentration of Particles (1st moment) [kg/m^3]
psd_type string with a tag defining the (hydrometeor) scheme
Author
Manfred Brath
Date
2017-08-01
Definition at line 1126 of file psd.cc.
References temp.
Referenced by psdMilbrandtYau05().
psd_rain_W16()
void psd_rain_W16 (Vector & psd, const Vector & diameter, const Numeric & rwc)
The Wang16 rain DSD DEPRECATED BY NEW MGD_SMM_COMMON Only included for compatibility with "old" pnd_fieldCalcFromscat_speciesField.
Uses rain water water content. PSD follows an exponential distribution. Handles a vector of sizes at a time.
Reference: Wang et al., 2016, "Investigation of liquid cloud microphysical properties of deep convective systems: 1. Parameterization raindrop size distribution and its application for stratiform rain estimation". Ported from CloudArts matlab implementation.
Parameters
[out] psd particle number density per size interval [#/m3*m]
[in] diameter size of the scattering elements (volume equivalent diameter) [m]
[in] rwc atmospheric rain water content [kg/m3]
Author
Jana Mendrok, Bengt Rydberg
Date
2017-06-07
Definition at line 707 of file psd.cc.
References a, ARTS_ASSERT, b, DENSITY_OF_WATER, ConstVectorView::nelem(), PI, pow(), and Vector::resize().
psd_SB06()
void psd_SB06 (Vector & psd, Matrix & dpsd, const Vector & mass, const Numeric & N_tot, const Numeric & WC, const String & hydrometeor_type)
Calculates the particle number density field according to the two moment scheme of Seifert and Beheng, 2006b,a that is used in the ICON model. One call of this function calculates one particle number density.
Returns
dN particle number density per diameter interval [#/m3/m]
Parameters
mass Mass of scattering particle [kg]
N_tot Total number of particles (0th moment) [#/m3/m/kg^mu]
M Total mass concentration of Particles (1st moment) [kg/m^3]
psd_type string with a tag defining the (hydrometeor) scheme
Author
Manfred Brath
Date
2015-01-19
Definition at line 985 of file psd.cc.
Referenced by psdSeifertBeheng06().
psd_snow_F07()
void psd_snow_F07 (Vector & psd, const Vector & diameter, const Numeric & swc, const Numeric & t, const Numeric alpha, const Numeric beta, const String & regime)
The F07 snow PSD.
Handles a vector of sizes at a time. Strictly requires SWC and T to be positive and regime to be either "TR" or "ML", i.e. calling methods need to ensure these. No further limitations on the allowed temperatures here. Strictly valid it's only within -60<=t<=0C, the measured t-range the parametrization is based on. However, this is left to be handled by the calling methods.
Parameters
[out] psd particle number density per size interval [#/m3*m]
[in] diameter size of the scattering elements (supposed to be maximum diameter of the ice particles) [m]
[in] swc atmospheric snow water content [kg/m^3]
[in] t atmospheric temperature [K]
[in] alpha mass-dimension relationship scaling factor (m=alpha*(Dmax/D0)^beta) [kg]
[in] beta mass-dimension relationship exponent [-]
[in] regime parametrization regime to apply (TR=tropical, ML=midlatitude)
Author
Manfred Brath, Jana Mendrok
Date
2017-06-13
Definition at line 894 of file psd.cc.