ARTS: quantum_parser_hitran.cc File Reference
quantum_parser_hitran.cc File Reference
Parser for quantum numbers from spectroscopic catalogs.
#include "quantum_parser_hitran.h"
#include "absorption.h"
#include "global_data.h"
#include "messages.h"
Macros
#define SKIP_X_SPACES(container, nspaces)
Functions
void parse_space (Rational &qn, String &s, const Index)
Parsing functions.
void parse_a1_br_hitran (Rational &qn, String &s, const Index species)
void parse_a1_pm_hitran (Rational &qn, String &s, const Index species)
void parse_a1_sym_hitran (Rational &qn, String &s, const Index species)
void parse_a1_s_hitran (Rational &qn, String &s, const Index species)
void parse_a1_x_hitran (Rational &qn, String &s, const Index species)
void parse_a2_hitran (Rational &qn, String &s, const Index species)
void parse_a3_hitran (Rational &qn, String &s, const Index species)
void parse_a4_hitran (Rational &qn, String &s, const Index species)
void parse_a5_hitran (Rational &qn, String &s, const Index species)
void parse_i1_hitran (Rational &qn, String &s, const Index species)
void parse_i2_hitran (Rational &qn, String &s, const Index species)
void parse_i3_hitran (Rational &qn, String &s, const Index species)
void parse_f51_hitran (Rational &qn, String &s, const Index species)
void postprocess_group1_hitran (QuantumIdentifier &qid)
Post-processing functions.
void postprocess_group2_hitran (QuantumIdentifier &qnr)
void postprocess_group5_hitran (QuantumIdentifier &qnr)
void postprocess_group6_hitran (QuantumIdentifier &qnr)
void postprocess_group6oh_hitran (QuantumIdentifier &qnr)
Detailed Description
Parser for quantum numbers from spectroscopic catalogs.
Author
Oliver Lemke
Definition in file quantum_parser_hitran.cc.
Macro Definition Documentation
SKIP_X_SPACES
#define SKIP_X_SPACES (container, nspaces)
Value:
  container.push_back_n(                                                    \
      QuantumFieldDescription(QuantumNumberType::FINAL_ENTRY, parse_space), \
      nspaces)
Function Documentation
parse_a1_br_hitran()
void parse_a1_br_hitran (Rational & qn, String & s, const Index species)
Definition at line 486 of file quantum_parser_hitran.cc.
References abs, and RATIONAL_UNDEFINED.
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a1_pm_hitran()
void parse_a1_pm_hitran (Rational & qn, String & s, const Index species)
Definition at line 492 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED.
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a1_s_hitran()
void parse_a1_s_hitran (Rational & qn, String & s, const Index species)
Definition at line 527 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED.
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a1_sym_hitran()
void parse_a1_sym_hitran (Rational & qn, String & s, const Index species)
Definition at line 498 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED, and species_index_from_species_name().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a1_x_hitran()
void parse_a1_x_hitran (Rational & qn, String & s, const Index species)
Definition at line 533 of file quantum_parser_hitran.cc.
References O2_X_is_X, RATIONAL_UNDEFINED, and species_index_from_species_name().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a2_hitran()
void parse_a2_hitran (Rational & qn, String & s, const Index species)
Definition at line 571 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED.
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a3_hitran()
void parse_a3_hitran (Rational & qn, String & s, const Index species)
Definition at line 577 of file quantum_parser_hitran.cc.
References extract().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_a4_hitran()
void parse_a4_hitran (Rational & qn, String & s, const Index species)
Definition at line 581 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED.
parse_a5_hitran()
void parse_a5_hitran (Rational & qn, String & s, const Index species)
Definition at line 587 of file quantum_parser_hitran.cc.
References Array< base >::nelem(), my_basic_string< charT >::nelem(), Absorption::nelem(), RATIONAL_UNDEFINED, my_basic_string< charT >::split(), and my_basic_string< charT >::trim().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_f51_hitran()
void parse_f51_hitran (Rational & qn, String & s, const Index species)
Definition at line 634 of file quantum_parser_hitran.cc.
References extract(), Array< base >::nelem(), my_basic_string< charT >::nelem(), Absorption::nelem(), q, RATIONAL_UNDEFINED, my_basic_string< charT >::split(), and my_basic_string< charT >::trim().
parse_i1_hitran()
void parse_i1_hitran (Rational & qn, String & s, const Index species)
Definition at line 616 of file quantum_parser_hitran.cc.
References extract().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_i2_hitran()
void parse_i2_hitran (Rational & qn, String & s, const Index species)
Definition at line 622 of file quantum_parser_hitran.cc.
References extract().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_i3_hitran()
void parse_i3_hitran (Rational & qn, String & s, const Index species)
Definition at line 628 of file quantum_parser_hitran.cc.
References extract().
Referenced by QuantumParserHITRAN2004::QuantumParserHITRAN2004().
parse_space()
void parse_space (Rational & qn, String & s, const Index species)
Parsing functions.
Definition at line 481 of file quantum_parser_hitran.cc.
References RATIONAL_UNDEFINED.
postprocess_group1_hitran()
void postprocess_group1_hitran (QuantumIdentifier & qnr)
Post-processing functions.
Definition at line 676 of file quantum_parser_hitran.cc.
References J, QuantumIdentifier::LowerQuantumNumber(), QuantumIdentifier::LowerQuantumNumbers(), N, RATIONAL_UNDEFINED, QuantumNumbers::Set(), QuantumIdentifier::Species(), species_index_from_species_name(), QuantumIdentifier::UpperQuantumNumber(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by QuantumParserHITRAN2004::Parse().
postprocess_group2_hitran()
void postprocess_group2_hitran (QuantumIdentifier & qnr)
Definition at line 703 of file quantum_parser_hitran.cc.
References J, QuantumIdentifier::LowerQuantumNumber(), QuantumIdentifier::LowerQuantumNumbers(), RATIONAL_UNDEFINED, QuantumNumbers::Set(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by QuantumParserHITRAN2004::Parse().
postprocess_group5_hitran()
void postprocess_group5_hitran (QuantumIdentifier & qnr)
Definition at line 713 of file quantum_parser_hitran.cc.
References CaseA, dN, J, QuantumIdentifier::LowerQuantumNumber(), QuantumIdentifier::LowerQuantumNumbers(), N, RATIONAL_UNDEFINED, QuantumNumbers::Set(), QuantumIdentifier::Species(), species_index_from_species_name(), Rational::toIndex(), QuantumIdentifier::UpperQuantumNumber(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by QuantumParserHITRAN2004::Parse().
postprocess_group6_hitran()
void postprocess_group6_hitran (QuantumIdentifier & qnr)
Definition at line 766 of file quantum_parser_hitran.cc.
References J, QuantumIdentifier::LowerQuantumNumber(), QuantumIdentifier::LowerQuantumNumbers(), O2_X_is_X, RATIONAL_UNDEFINED, QuantumNumbers::Set(), QuantumIdentifier::Species(), species_index_from_species_name(), Rational::toIndex(), QuantumIdentifier::UpperQuantumNumber(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by QuantumParserHITRAN2004::Parse().
postprocess_group6oh_hitran()
void postprocess_group6oh_hitran (QuantumIdentifier & qnr)
Definition at line 822 of file quantum_parser_hitran.cc.
References CaseA, dN, J, QuantumIdentifier::LowerQuantumNumber(), QuantumIdentifier::LowerQuantumNumbers(), N, RATIONAL_UNDEFINED, QuantumNumbers::Set(), QuantumIdentifier::Species(), species_index_from_species_name(), Rational::toIndex(), QuantumIdentifier::UpperQuantumNumber(), and QuantumIdentifier::UpperQuantumNumbers().
Referenced by QuantumParserHITRAN2004::Parse().