ARTS: quantum.h File Reference
quantum.h File Reference
#include <array>
#include <iostream>
#include <map>
#include <numeric>
#include <stdexcept>
#include "array.h"
#include "interpolation.h"
#include "matpack.h"
#include "mystring.h"
#include "rational.h"
Classes
class QuantumNumbers
Container class for Quantum Numbers.
class QuantumIdentifier
Class to identify and match lines by their quantum numbers.
Macros
#define INPUT_QUANTUM(ID) if (s == #ID) return QuantumNumberType::ID
#define INPUT_QUANTUM(ID) if (s == QuantumNumberType::ID) return #ID
Typedefs
typedef Array< QuantumNumbers > ArrayOfQuantumNumbers
typedef Array< QuantumIdentifier > ArrayOfQuantumIdentifier
Enumerations
enum QuantumNumberType : Index {
QuantumNumberType::J = 0, QuantumNumberType::dJ, QuantumNumberType::M, QuantumNumberType::N,
QuantumNumberType::dN, QuantumNumberType::S, QuantumNumberType::tau, QuantumNumberType::n,
QuantumNumberType::F, QuantumNumberType::Ka, QuantumNumberType::Kc, QuantumNumberType::Omega,
QuantumNumberType::i, QuantumNumberType::Lambda, QuantumNumberType::alpha, QuantumNumberType::Sym,
QuantumNumberType::parity, QuantumNumberType::kronigParity, QuantumNumberType::v1, QuantumNumberType::v2,
QuantumNumberType::v3, QuantumNumberType::v4, QuantumNumberType::v5, QuantumNumberType::v6,
QuantumNumberType::v7, QuantumNumberType::v8, QuantumNumberType::v9, QuantumNumberType::v10,
QuantumNumberType::v11, QuantumNumberType::v12, QuantumNumberType::l1, QuantumNumberType::l2,
QuantumNumberType::l3, QuantumNumberType::l4, QuantumNumberType::l5, QuantumNumberType::l6,
QuantumNumberType::l7, QuantumNumberType::l8, QuantumNumberType::l9, QuantumNumberType::l10,
QuantumNumberType::l11, QuantumNumberType::l12, QuantumNumberType::pm, QuantumNumberType::r,
QuantumNumberType::S_global, QuantumNumberType::ElectronState, QuantumNumberType::n_global, QuantumNumberType::C,
QuantumNumberType::Hund, QuantumNumberType::FINAL_ENTRY
}
Enum for Quantum Numbers used for indexing.
enum Hund : Index { Hund::CaseA = int('a'), Hund::CaseB = int('b') }
Enum for Hund cases.
Functions
QuantumNumberType string2quantumnumbertype (const String &s)
String quantumnumbertype2string (QuantumNumberType s)
bool operator== (const QuantumIdentifier &a, const QuantumIdentifier &b)
Is everything the same between the identifiers.
bool operator!= (const QuantumIdentifier &a, const QuantumIdentifier &b)
Is anything different between the identifiers.
bool operator== (const QuantumNumbers &a, const QuantumNumbers &b)
Check if all quantum numbers are the same between a and b.
bool IsValidQuantumNumberName (String name)
Check for valid quantum number name.
void ThrowIfQuantumNumberNameInvalid (String name)
Check for valid quantum number name and throws if it is invalid.
std::istream & operator>> (std::istream &is, QuantumNumbers &qn)
Input operator.
std::ostream & operator<< (std::ostream &os, const QuantumNumbers &qn)
Output operator.
std::ostream & operator<< (std::ostream &os, const QuantumIdentifier &qi)
Output operator.
std::ostream & operator<< (std::ostream &os, QuantumNumberType t)
void update_id (QuantumIdentifier &qid, const std::vector< std::array< String, 2 > > &upper_list, const std::vector< std::array< String, 2 > > &lower_list)
Updates the quantum identifier based on a lists of strings.
Macro Definition Documentation
INPUT_QUANTUM [1/2]
#define INPUT_QUANTUM (ID) if (s == #ID) return QuantumNumberType::ID
INPUT_QUANTUM [2/2]
#define INPUT_QUANTUM (ID) if (s == QuantumNumberType::ID) return #ID
Typedef Documentation
ArrayOfQuantumIdentifier
typedef Array<QuantumIdentifier> ArrayOfQuantumIdentifier
Definition at line 750 of file quantum.h.
ArrayOfQuantumNumbers
typedef Array<QuantumNumbers> ArrayOfQuantumNumbers
Definition at line 368 of file quantum.h.
Enumeration Type Documentation
Hund
enum Hund : Index strong
Enum for Hund cases.
Enumerator
CaseA
CaseB
Definition at line 219 of file quantum.h.
QuantumNumberType
enum QuantumNumberType : Index strong
Enum for Quantum Numbers used for indexing.
If you add anything here, remember to also adapt operator<<(ostream&, const QuantumNumbers&) and operator>>(istream&, QuantumNumbers&) to handle the added numbers.
Enumerator
J
dJ
M
N
dN
S
tau
n
F
Ka
Kc
Omega
i
Lambda
alpha
Sym
parity
kronigParity
v1
v2
v3
v4
v5
v6
v7
v8
v9
v10
v11
v12
l1
l2
l3
l4
l5
l6
l7
l8
l9
l10
l11
l12
pm
r
S_global
ElectronState
n_global
C
Hund
FINAL_ENTRY
Definition at line 48 of file quantum.h.
Function Documentation
IsValidQuantumNumberName()
bool IsValidQuantumNumberName (String name)
Check for valid quantum number name.
Parameters
[in] name Parameter
Returns
true If the parameter exist
false Otherwise
Definition at line 164 of file quantum.cc.
References J, and string2quantumnumbertype().
Referenced by string2vecqn(), and ThrowIfQuantumNumberNameInvalid().
operator!=()
bool operator!= (const QuantumIdentifier & a, const QuantumIdentifier & b) inline
Is anything different between the identifiers.
May throw if different Qtypes are compared.
Parameters
[in] a One identifier
[in] b Another identifier
Returns
true If some quantum numbers mismatch
false Otherwise
Definition at line 735 of file quantum.h.
References operator==().
operator<<() [1/3]
std::ostream& operator<< (std::ostream & os, const QuantumIdentifier & qi)
Output operator.
Definition at line 369 of file quantum.cc.
References QuantumIdentifier::ALL, QuantumIdentifier::ENERGY_LEVEL, QuantumIdentifier::ENERGY_LEVEL_INDEX, QuantumIdentifier::Isotopologue(), QuantumIdentifier::NONE, QuantumIdentifier::QuantumMatch(), QuantumIdentifier::Species(), global_data::species_data, QuantumIdentifier::SpeciesName(), QuantumIdentifier::TRANSITION, QuantumIdentifier::TRANSITION_LOWER_INDEX, QuantumIdentifier::TRANSITION_UPPER_INDEX, and QuantumIdentifier::Type().
operator<<() [2/3]
std::ostream& operator<< (std::ostream & os, const QuantumNumbers & qn)
Output operator.
Definition at line 187 of file quantum.cc.
References J, and quantumnumbertype2string().
operator<<() [3/3]
std::ostream& operator<< (std::ostream & os, QuantumNumberType t)
Definition at line 410 of file quantum.cc.
References quantumnumbertype2string().
operator==() [1/2]
bool operator== (const QuantumIdentifier & a, const QuantumIdentifier & b) inline
Is everything the same between the identifiers.
May throw if different Qtypes are compared.
Parameters
[in] a One identifier
[in] b Another identifier
Returns
true If all quantum numbers match
false Otherwise
Definition at line 705 of file quantum.h.
References QuantumIdentifier::ALL, QuantumIdentifier::ENERGY_LEVEL, QuantumIdentifier::ENERGY_LEVEL_INDEX, QuantumIdentifier::Isotopologue(), QuantumIdentifier::NONE, QuantumIdentifier::QuantumMatch(), QuantumIdentifier::Species(), QuantumIdentifier::TRANSITION, QuantumIdentifier::TRANSITION_LOWER_INDEX, QuantumIdentifier::TRANSITION_UPPER_INDEX, and QuantumIdentifier::Type().
Referenced by Jacobian::ENUMARTS(), and operator!=().
operator==() [2/2]
bool operator== (const QuantumNumbers & a, const QuantumNumbers & b) inline
Check if all quantum numbers are the same between a and b.
Parameters
[in] a One set of quantum numbers
[in] b Another set of quantum numbers
Returns
true If all quantum numbers match
false Otherwise
Definition at line 746 of file quantum.h.
References QuantumNumbers::Compare().
operator>>()
std::istream& operator>> (std::istream & is, QuantumNumbers & qn)
Input operator.
Definition at line 176 of file quantum.cc.
References QuantumNumbers::Set().
quantumnumbertype2string()
String quantumnumbertype2string (QuantumNumberType s) inline
Definition at line 162 of file quantum.h.
References INPUT_QUANTUM, M, and N.
Referenced by abs_linesPrintDefinedQuantumNumbers(), ArtsXMLTag::add_attribute(), Absorption::Lines::MetaData(), and operator<<().
string2quantumnumbertype()
QuantumNumberType string2quantumnumbertype (const String & s) inline
Definition at line 101 of file quantum.h.
References F, INPUT_QUANTUM, M, and N.
Referenced by abs_linesDeleteLinesWithQuantumNumberAbove(), abs_linesSetQuantumNumberForMatch(), ArtsXMLTag::get_attribute_value(), IsValidQuantumNumberName(), QuantumNumbers::Set(), string2quantumnumbersindex(), string2vecqn(), and update_id().
ThrowIfQuantumNumberNameInvalid()
void ThrowIfQuantumNumberNameInvalid (String name)
Check for valid quantum number name and throws if it is invalid.
Parameters
[in] name Parameter
Definition at line 168 of file quantum.cc.
References IsValidQuantumNumberName().
Referenced by QuantumIdentifier::SetFromString().
update_id()
void update_id (QuantumIdentifier & qid, const std::vector< std::array< String, 2 > > & upper_list, const std::vector< std::array< String, 2 > > & lower_list)
Updates the quantum identifier based on a lists of strings.
The input lists of strings should be paired as {key, value}
Parameters
[in,out] qid Identifier to update
[in] upper_list List of strings to update upper state
[in] lower_list List of strings to update lower state
Definition at line 436 of file quantum.cc.
References interpret_stringdata(), J, QuantumIdentifier::LowerQuantumNumber(), RATIONAL_UNDEFINED, string2quantumnumbertype(), and QuantumIdentifier::UpperQuantumNumber().