ARTS: rational.h File Reference
rational.h File Reference
Contains the rational class definition.
#include <ostream>
#include "array.h"
#include "bifstream.h"
#include "bofstream.h"
#include "math_funcs.h"
#include "matpack.h"
Classes
class Rational
Implements rational numbers to work with other ARTS types.
Macros
#define RATIONAL_UNDEFINED Rational(0, 0)
Typedefs
typedef Array< Rational > ArrayOfRational
Functions
constexpr Index gcd (Index a, Index b) noexcept
Returns the greatest common denominator of two numbers.
constexpr Rational reduce_by_gcd (const Rational a) noexcept
Returns the rational reduced by the greates.
constexpr Rational numeric2rational (Numeric x, size_t maxdec=4) noexcept
Rational from Numeric.
constexpr Rational operator- (const Rational a) noexcept
Negative.
constexpr Rational operator+ (const Rational a) noexcept
Positive.
constexpr Rational operator+ (const Rational a, const Rational b) noexcept
Addition.
constexpr Rational operator+ (const Rational a, Index b) noexcept
Addition.
constexpr Rational operator+ (const Rational a, int b) noexcept
Addition.
constexpr Rational operator+ (Index b, const Rational a) noexcept
Addition.
constexpr Rational operator+ (int b, const Rational a) noexcept
Addition.
constexpr Rational operator- (const Rational a, const Rational b) noexcept
Subtraction.
constexpr Rational operator- (const Rational a, Index b) noexcept
Subtraction.
constexpr Rational operator- (const Rational a, int b) noexcept
Subtraction.
constexpr Rational operator- (Index b, const Rational a) noexcept
Subtraction.
constexpr Rational operator- (int b, const Rational a) noexcept
Subtraction.
constexpr Rational operator/ (const Rational a, const Rational b) noexcept
Division.
constexpr Rational operator/ (const Rational a, Index b) noexcept
Division.
constexpr Rational operator/ (const Rational a, int b) noexcept
Division.
constexpr Rational operator/ (Index b, const Rational a) noexcept
Division.
constexpr Rational operator/ (int b, const Rational a) noexcept
Division.
constexpr Rational operator* (const Rational a, const Rational b) noexcept
Multiplication.
constexpr Rational operator* (const Rational a, Index b) noexcept
Multiplication.
constexpr Rational operator* (const Rational a, int b) noexcept
Multiplication.
constexpr Rational operator* (Index b, const Rational a) noexcept
Multiplication.
constexpr Rational operator* (int b, const Rational a) noexcept
Multiplication.
constexpr Rational operator% (const Rational a, const Rational b) noexcept
Remainder.
constexpr Rational operator% (const Rational a, Index b) noexcept
Remainder.
constexpr Rational operator% (const Rational a, int b) noexcept
Remainder.
constexpr Rational operator% (Index b, const Rational a) noexcept
Remainder.
constexpr Rational operator% (int b, const Rational a) noexcept
Remainder.
constexpr bool operator== (const Rational a, const Rational b) noexcept
Equality.
constexpr bool operator!= (const Rational a, const Rational b) noexcept
Inequality.
constexpr bool operator< (const Rational a, const Rational b) noexcept
Less than.
constexpr bool operator> (const Rational a, const Rational b) noexcept
More than.
constexpr bool operator<= (const Rational a, const Rational b) noexcept
Less than or equal to.
constexpr bool operator>= (const Rational a, const Rational b) noexcept
More than or equal to.
constexpr bool operator! (const Rational a) noexcept
Not.
Numeric sqrt (const Rational r)
Square root.
Numeric pow (const Rational base, Numeric exp)
Power of.
Numeric pow (Numeric base, const Rational exp)
Power of.
Numeric pow (const Rational base, const Rational exp)
Power of.
std::ostream & operator<< (std::ostream &os, const Rational &a)
Output operator.
std::istream & operator>> (std::istream &is, Rational &a)
Input operator.
constexpr bool operator< (const Index a, const Rational b) noexcept
less
constexpr bool operator< (const int a, const Rational b) noexcept
less
constexpr bool operator< (const Rational a, const Index b) noexcept
less
constexpr bool operator< (const Rational a, const int b) noexcept
less
constexpr bool operator> (const Index a, const Rational b) noexcept
more
constexpr bool operator> (const int a, const Rational b) noexcept
more
constexpr bool operator> (const Rational a, const Index b) noexcept
more
constexpr bool operator> (const Rational a, const int b) noexcept
more
constexpr bool operator== (const Rational a, const Index b) noexcept
equal
constexpr bool operator== (const Rational a, const int b) noexcept
equal
constexpr bool operator!= (const Rational a, const Index b) noexcept
not equal
constexpr bool operator!= (const Rational a, const int b) noexcept
not equal
constexpr Rational abs (const Rational a) noexcept
Absolute.
constexpr Rational max (const Rational a, const Rational b) noexcept
Maximum.
constexpr Rational min (const Rational a, const Rational b) noexcept
Minimum.
constexpr Rational operator""_2 (unsigned long long int n) noexcept
Returns common operator n/2.
constexpr Rational operator""_rat (unsigned long long int n) noexcept
Returns common operator n/1.
constexpr bool iseven (const Rational r) noexcept
Returns true if even integer.
Detailed Description
Contains the rational class definition.
Author
Richard Larsson
Date
2012-10-31
Definition in file rational.h.
Macro Definition Documentation
RATIONAL_UNDEFINED
#define RATIONAL_UNDEFINED Rational(0, 0)
Definition at line 394 of file rational.h.
Typedef Documentation
ArrayOfRational
typedef Array<Rational> ArrayOfRational
Definition at line 929 of file rational.h.
Function Documentation
abs()
constexpr Rational abs (const Rational a) constexpr noexcept
Absolute.
Parameters
[in] a Any Rational
Returns
constexpr Rational Absolute value of the Rational
Definition at line 905 of file rational.h.
References a.
gcd()
constexpr Index gcd (Index a, Index b) constexpr noexcept
Returns the greatest common denominator of two numbers.
Parameters
[in] a number a
[in] b number b
Returns
num such that Rational(a/num, b/num) is the same as Rational(a, b)
Definition at line 44 of file rational.h.
References a, and b.
Referenced by Rational::Rational(), and reduce_by_gcd().
iseven()
constexpr bool iseven (const Rational r) constexpr noexcept
Returns true if even integer.
Parameters
[in] r Any rational
Returns
true if r is even, otherwise false
Definition at line 954 of file rational.h.
Referenced by Absorption::reduced_magnetic_quadrapole().
max()
constexpr Rational max (const Rational a, const Rational b) constexpr noexcept
Maximum.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational Largest of a and b
Definition at line 915 of file rational.h.
References a, and b.
min()
constexpr Rational min (const Rational a, const Rational b) constexpr noexcept
Minimum.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational Smallest of a and b
Definition at line 925 of file rational.h.
References a, and b.
numeric2rational()
constexpr Rational numeric2rational (Numeric x, size_t maxdec = 4) constexpr noexcept
Rational from Numeric.
Performs basic rounding
Parameters
[in] x Numeric value
[in] maxdec Maximum number of decimals
Definition at line 363 of file rational.h.
References ARTS::Var::x().
Referenced by Rational::Rational(), and test_numeric2rational().
operator!()
constexpr bool operator! (const Rational a) constexpr noexcept
Not.
Parameters
[in] a Any Rational
Returns
true If a.Nom() and a.isDefined()
false Otherwise
Definition at line 735 of file rational.h.
References a.
operator!=() [1/3]
constexpr bool operator!= (const Rational a, const Index b) constexpr noexcept
not equal
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is not equal to b
Definition at line 886 of file rational.h.
References a, and b.
operator!=() [2/3]
constexpr bool operator!= (const Rational a, const int b) constexpr noexcept
not equal
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is not equal to b
Definition at line 896 of file rational.h.
References a, and b.
operator!=() [3/3]
constexpr bool operator!= (const Rational a, const Rational b) constexpr noexcept
Inequality.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If not equal
false Otherwise
Definition at line 682 of file rational.h.
References a, b, and operator==().
operator""_2()
constexpr Rational operator""_2 (unsigned long long int n) constexpr noexcept
Returns common operator n/2.
Parameters
[in] n Any positive integer
Returns
Rational(n, 2)
Definition at line 936 of file rational.h.
operator""_rat()
constexpr Rational operator""_rat (unsigned long long int n) constexpr noexcept
Returns common operator n/1.
Parameters
[in] n Any positive integer
Returns
Rational(n, 1)
Definition at line 945 of file rational.h.
operator%() [1/5]
constexpr Rational operator% (const Rational a, const Rational b) constexpr noexcept
Remainder.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational a % b
Definition at line 616 of file rational.h.
References a, and b.
operator%() [2/5]
constexpr Rational operator% (const Rational a, Index b) constexpr noexcept
Remainder.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a % b
Definition at line 629 of file rational.h.
References a, and b.
operator%() [3/5]
constexpr Rational operator% (const Rational a, int b) constexpr noexcept
Remainder.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a % b
Definition at line 639 of file rational.h.
References a, and b.
operator%() [4/5]
constexpr Rational operator% (Index b, const Rational a) constexpr noexcept
Remainder.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b % a
Definition at line 649 of file rational.h.
References a, and b.
operator%() [5/5]
constexpr Rational operator% (int b, const Rational a) constexpr noexcept
Remainder.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b % a
Definition at line 659 of file rational.h.
References a, and b.
operator*() [1/5]
constexpr Rational operator* (const Rational a, const Rational b) constexpr noexcept
Multiplication.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational a * b
Definition at line 570 of file rational.h.
References a, and b.
Referenced by operator*().
operator*() [2/5]
constexpr Rational operator* (const Rational a, Index b) constexpr noexcept
Multiplication.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a * b
Definition at line 580 of file rational.h.
References a, and b.
operator*() [3/5]
constexpr Rational operator* (const Rational a, int b) constexpr noexcept
Multiplication.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a * b
Definition at line 590 of file rational.h.
References a, and b.
operator*() [4/5]
constexpr Rational operator* (Index b, const Rational a) constexpr noexcept
Multiplication.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational a * b
Definition at line 600 of file rational.h.
References a, b, and operator*().
operator*() [5/5]
constexpr Rational operator* (int b, const Rational a) constexpr noexcept
Multiplication.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational a * b
Definition at line 608 of file rational.h.
References a, b, and operator*().
operator+() [1/6]
constexpr Rational operator+ (const Rational a) constexpr noexcept
Positive.
Parameters
[in] a Any Rational
Returns
constexpr Rational a
Definition at line 410 of file rational.h.
References a.
Referenced by operator+().
operator+() [2/6]
constexpr Rational operator+ (const Rational a, const Rational b) constexpr noexcept
Addition.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational a + b
Definition at line 418 of file rational.h.
References a, and b.
operator+() [3/6]
constexpr Rational operator+ (const Rational a, Index b) constexpr noexcept
Addition.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a + b
Definition at line 431 of file rational.h.
References a, and b.
operator+() [4/6]
constexpr Rational operator+ (const Rational a, int b) constexpr noexcept
Addition.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a + b
Definition at line 441 of file rational.h.
References a, and b.
operator+() [5/6]
constexpr Rational operator+ (Index b, const Rational a) constexpr noexcept
Addition.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational a + b
Definition at line 451 of file rational.h.
References a, b, and operator+().
operator+() [6/6]
constexpr Rational operator+ (int b, const Rational a) constexpr noexcept
Addition.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational a + b
Definition at line 459 of file rational.h.
References a, b, and operator+().
operator-() [1/6]
constexpr Rational operator- (const Rational a) constexpr noexcept
Negative.
Parameters
[in] a Any Rational
Returns
constexpr Rational Negative a
Definition at line 401 of file rational.h.
References a.
operator-() [2/6]
constexpr Rational operator- (const Rational a, const Rational b) constexpr noexcept
Subtraction.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational a - b
Definition at line 467 of file rational.h.
References a, and b.
operator-() [3/6]
constexpr Rational operator- (const Rational a, Index b) constexpr noexcept
Subtraction.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a - b
Definition at line 480 of file rational.h.
References a, and b.
operator-() [4/6]
constexpr Rational operator- (const Rational a, int b) constexpr noexcept
Subtraction.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a - b
Definition at line 490 of file rational.h.
References a, and b.
operator-() [5/6]
constexpr Rational operator- (Index b, const Rational a) constexpr noexcept
Subtraction.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b - a
Definition at line 500 of file rational.h.
References a, and b.
operator-() [6/6]
constexpr Rational operator- (int b, const Rational a) constexpr noexcept
Subtraction.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b - a
Definition at line 510 of file rational.h.
References a, and b.
operator/() [1/5]
constexpr Rational operator/ (const Rational a, const Rational b) constexpr noexcept
Division.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
constexpr Rational a / b
Definition at line 520 of file rational.h.
References a, and b.
operator/() [2/5]
constexpr Rational operator/ (const Rational a, Index b) constexpr noexcept
Division.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a / b
Definition at line 530 of file rational.h.
References a, and b.
operator/() [3/5]
constexpr Rational operator/ (const Rational a, int b) constexpr noexcept
Division.
Parameters
[in] a Any Rational
[in] b Any Index
Returns
constexpr Rational a / b
Definition at line 540 of file rational.h.
References a, and b.
operator/() [4/5]
constexpr Rational operator/ (Index b, const Rational a) constexpr noexcept
Division.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b / a
Definition at line 550 of file rational.h.
References a, and b.
operator/() [5/5]
constexpr Rational operator/ (int b, const Rational a) constexpr noexcept
Division.
Parameters
[in] b Any Index
[in] a Any Rational
Returns
constexpr Rational b / a
Definition at line 560 of file rational.h.
References a, and b.
operator<() [1/5]
constexpr bool operator< (const Index a, const Rational b) constexpr noexcept
less
Parameters
[in] a Any Index
[in] b Any Rational
Returns
True if a is less than b
Definition at line 786 of file rational.h.
References a, and b.
operator<() [2/5]
constexpr bool operator< (const int a, const Rational b) constexpr noexcept
less
Parameters
[in] a Any Index
[in] b Any Rational
Returns
True if a is less than b
Definition at line 796 of file rational.h.
References a, and b.
operator<() [3/5]
constexpr bool operator< (const Rational a, const Index b) constexpr noexcept
less
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is less than b
Definition at line 806 of file rational.h.
References a, and b.
operator<() [4/5]
constexpr bool operator< (const Rational a, const int b) constexpr noexcept
less
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is less than b
Definition at line 816 of file rational.h.
References a, and b.
operator<() [5/5]
constexpr bool operator< (const Rational a, const Rational b) constexpr noexcept
Less than.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If a < b
false Otherwise
Definition at line 693 of file rational.h.
References a, and b.
Referenced by operator>(), and operator>=().
operator<<()
std::ostream& operator<< (std::ostream & os, const Rational & a)
Output operator.
Definition at line 33 of file rational.cc.
References a, Rational::Denom(), Rational::fixSign(), Rational::Nom(), and reduce_by_gcd().
operator<=()
constexpr bool operator<= (const Rational a, const Rational b) constexpr noexcept
Less than or equal to.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If a <= b
false Otherwise
Definition at line 714 of file rational.h.
References a, b, and operator>().
operator==() [1/3]
constexpr bool operator== (const Rational a, const Index b) constexpr noexcept
equal
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is equal to b
Definition at line 866 of file rational.h.
References a, and b.
operator==() [2/3]
constexpr bool operator== (const Rational a, const int b) constexpr noexcept
equal
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is equal to b
Definition at line 876 of file rational.h.
References a, and b.
operator==() [3/3]
constexpr bool operator== (const Rational a, const Rational b) constexpr noexcept
Equality.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If equal
false Otherwise
Definition at line 670 of file rational.h.
References a, and b.
Referenced by operator!=().
operator>() [1/5]
constexpr bool operator> (const Index a, const Rational b) constexpr noexcept
more
Parameters
[in] a Any Index
[in] b Any Rational
Returns
True if a is more than b
Definition at line 826 of file rational.h.
References a, and b.
operator>() [2/5]
constexpr bool operator> (const int a, const Rational b) constexpr noexcept
more
Parameters
[in] a Any Index
[in] b Any Rational
Returns
True if a is more than b
Definition at line 836 of file rational.h.
References a, and b.
operator>() [3/5]
constexpr bool operator> (const Rational a, const Index b) constexpr noexcept
more
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is more than b
Definition at line 846 of file rational.h.
References a, and b.
operator>() [4/5]
constexpr bool operator> (const Rational a, const int b) constexpr noexcept
more
Parameters
[in] a Any Rational
[in] b Any Index
Returns
True if a is more than b
Definition at line 856 of file rational.h.
References a, and b.
operator>() [5/5]
constexpr bool operator> (const Rational a, const Rational b) constexpr noexcept
More than.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If a > b
false Otherwise
Definition at line 705 of file rational.h.
References a, b, and operator<().
Referenced by operator<=().
operator>=()
constexpr bool operator>= (const Rational a, const Rational b) constexpr noexcept
More than or equal to.
Parameters
[in] a Any Rational
[in] b Any Rational
Returns
true If a >= b
false Otherwise
Definition at line 725 of file rational.h.
References a, b, and operator<().
operator>>()
std::istream& operator>> (std::istream & is, Rational & a)
Input operator.
Definition at line 44 of file rational.cc.
References a, ARTS_USER_ERROR, ARTS_USER_ERROR_IF, my_basic_string< charT >::nelem(), Array< base >::nelem(), Absorption::nelem(), and my_basic_string< charT >::split().
pow() [1/3]
Numeric pow (const Rational base, const Rational exp) inline
Power of.
Parameters
[in] base Any Rational
[in] exp Any Rational
Returns
Numeric base to the power of exp
Definition at line 770 of file rational.h.
References pow(), and Rational::toNumeric().
pow() [2/3]
Numeric pow (const Rational base, Numeric exp) inline
Power of.
Parameters
[in] base Any Rational
[in] exp Any Numeric
Returns
Numeric base to the power of exp
Definition at line 750 of file rational.h.
References Rational::toNumeric().
Referenced by abs_lookupSetup(), abs_lookupSetupBatch(), abs_lookupSetupWide(), antenna_responseGaussian(), antenna_responseVaryingGaussian(), BF86_CIA_N2(), cart2poslos(), CKD_mt_250_o2_vis(), CKD_mt_v1v0_o2(), lm_hitran_2017::compabs(), conti_n2__(), lm_hitran_2017::convtp(), CP98H2OAbsModel(), Minimize::T4::df(), Minimize::DPL::df(), diameter_maxFromDiameter_volume_equ(), diameter_volume_equFromDiameter_max(), doit_conv_flagLsq(), ELL07WaterDropletAbs(), TelsemAtlas::emis_interp(), fctl_(), g0Earth(), gaussian_response(), get_ppath_cloudvars(), Ho66_CO2_foreign_continuum(), Ho66_CO2_self_continuum(), binistream::ieee_double2float(), binistream::ieee_single2float(), iyIndependentBeamApproximation(), MaTipping_H2O_foreign_continuum(), matrix_exp(), mgd(), mgd_with_derivatives(), mod_gamma_dist(), MPM02H2OAbsModel(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), Minimize::T4::operator()(), Minimize::DPL::operator()(), Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), particle_bulkpropRadarOnionPeeling(), PFromZSimple(), polynomial_basis_func(), pow(), psd_cloudice_MH97(), psd_mgd_mass_and_something(), psd_rain_W16(), psdModifiedGammaMass(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Absorption::ReadFromArtscat3Stream(), refellipsoidForAzimuth(), refellipsoidOrbitPlane(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), rtmethods_jacobian_finalisation(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), Standard_O2_continuum(), surface_specular_R_and_b(), swv_mpmf87s93__(), transform_jacobian(), transform_x_back(), TRE05O2AbsModel(), yCalc(), and yRadar().
pow() [3/3]
Numeric pow (Numeric base, const Rational exp) inline
Power of.
Parameters
[in] base Any Numeric
[in] exp Any Rational
Returns
Numeric base to the power of exp
Definition at line 760 of file rational.h.
References pow(), and Rational::toNumeric().
reduce_by_gcd()
constexpr Rational reduce_by_gcd (const Rational a) constexpr noexcept
Returns the rational reduced by the greates.
Parameters
[in] a Any Rational
Returns
a / gcd(a)
Definition at line 348 of file rational.h.
References a, and gcd().
Referenced by operator<<(), and Rational::simplify_in_place().
sqrt()
Numeric sqrt (const Rational r) inline
Square root.
Parameters
[in] r Any Rational
Returns
Numeric Square root of the Rational
Definition at line 742 of file rational.h.
References Rational::toNumeric().
Referenced by antenna_responseGaussian(), antenna_responseVaryingGaussian(), LineShape::SpeedDependentVoigt::calc(), cart2pol(), cart2poslos(), cart2sph(), cart2sph_plain(), cart2zaaa(), case_b_g_coefficient_o2(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__eigen(), cayley_hamilton_fitted_method_4x4_propmat_to_transmat__explicit(), chk_atm_vecfield_lat90(), lm_hitran_2017::compabs(), complex_n_ice_matzler06(), complex_n_water_liebe93(), compute_transmission_matrix(), compute_transmission_matrix_and_derivative(), compute_transmission_matrix_from_averaged_matrix_at_frequency(), lm_hitran_2017::convtp(), covmat_sxExtractSqrtDiagonal(), distance2D(), distance3D(), doit_conv_flagLsq(), Absorption::Lines::DopplerConstant(), Linefunctions::DopplerConstant(), dotprod_with_los(), MCAntenna::draw_los(), dtransmat3(), Absorption::LineMixing::ENUMCLASS(), Zeeman::FromGrids(), g_legendre_poly(), g_legendre_poly_deriv(), g_legendre_poly_norm_schmidt(), g_legendre_poly_norm_schmidt_deriv(), g_legendre_poly_norm_schmidt_deriv1(), g_legendre_poly_norm_schmidt_deriv2(), g_legendre_poly_norm_schmidt_deriv3(), g_legendre_poly_norm_schmidt_deriv4(), gaussian_response(), gaussian_response_autogrid(), geompath_l_at_r(), geompath_r_at_l(), geompath_tanpos_3d(), legendre_poly(), legendre_poly_deriv(), legendre_poly_norm_schmidt(), legendre_poly_norm_schmidt_deriv(), los2xyz(), MCGeneral(), LineShape::HartmannTran::operator()(), Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole(), psd_cloudice_MH97(), r_crossing_3d(), ran_gaussian(), TelsemAtlas::read(), lm_hitran_2017::readlines(), Absorption::reduced_magnetic_quadrapole(), refellipsoidForAzimuth(), refellipsoidOrbitPlane(), refr_index_airInfraredEarth(), retrievalErrorsExtract(), Linefunctions::set_htp(), sphdist(), surf_radius_at_l(), test2(), transmat3(), unitl(), vector_angle(), and yCalc().