ARTS: rational.cc File Reference
rational.cc File Reference
Contains the rational class implmentations.
#include "rational.h"
#include <ostream>
#include <stdexcept>
#include "mystring.h"
Functions
std::ostream & operator<< (std::ostream &os, const Rational &a)
Output operator.
std::istream & operator>> (std::istream &is, Rational &a)
Input operator.
Detailed Description
Contains the rational class implmentations.
Author
Richard Larsson
Date
2012-10-31
Definition in file rational.cc.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const Rational & a)
Output operator.
Definition at line 33 of file rational.cc.
References a, Rational::Denom(), Rational::fixSign(), Rational::Nom(), and reduce_by_gcd().
operator>>()
std::istream& operator>> (std::istream & is, Rational & a)
Input operator.
Definition at line 44 of file rational.cc.
References a, ARTS_USER_ERROR, ARTS_USER_ERROR_IF, my_basic_string< charT >::nelem(), Array< base >::nelem(), Absorption::nelem(), and my_basic_string< charT >::split().