ARTS: sorting.h File Reference
sorting.h File Reference
Contains sorting routines.
#include <algorithm>
#include <functional>
#include "array.h"
#include "matpack.h"
Classes
class IndexComp< T >
IndexComp.
Functions
template<typename T >
void get_sorted_indexes (ArrayOfIndex &sorted, const T &data)
get_sorted_indexes
Detailed Description
Contains sorting routines.
Author
Oliver Lemke
Date
2003-08-20
Definition in file sorting.h.
Function Documentation
get_sorted_indexes()
template<typename T > void get_sorted_indexes (ArrayOfIndex & sorted, const T & data)
get_sorted_indexes
The output array contains the sorted indexes of the input data.
The following member functions must be defined for the input data type: T.begin, T.end, T.operator[], T.operator<
Furthermore, it must provide the type T::const_iterator.
Parameters
sorted Output array with sorted indexes
data Data to sort
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-08-20
Definition at line 73 of file sorting.h.
References data.
Referenced by derive_scat_species_a_and_b(), find_effective_channel_boundaries(), pndFromPsd(), pndFromPsdBasic(), sorted_index_of_ppath_field(), testVector(), TimeSortTemplate(), VectorInsertGridPoints(), and za_gridOpt().