ARTS: species_info.cc File Reference
species_info.cc File Reference
Some molecular constants.
#include "species_info.h"
#include "absorption.h"
#include "wigner_functions.h"
Functions
Numeric get_lande_spin_constant (const Index species) noexcept
Get the Lande spin constant.
Numeric get_lande_lambda_constant () noexcept
Get the Lande Lambda constant.
Detailed Description
Some molecular constants.
Author
Richard Larsson
Date
2018-03-29
Definition in file species_info.cc.
Function Documentation
get_lande_lambda_constant()
Numeric get_lande_lambda_constant () noexcept
Get the Lande Lambda constant.
Returns
Numeric Lande Lambda constant
Definition at line 45 of file species_info.cc.
Referenced by Zeeman::GetSimpleModel().
get_lande_spin_constant()
Numeric get_lande_spin_constant (const Index species) noexcept
Get the Lande spin constant.
H. Christensen, and L. Veseth, On the High-Precision Zeeman Effect in 02 and SO. Journal of Molecular Spectroscopy 72, 438-444, 1978.
L. Veseth, Relativistic Corrections to the Zeeman Effect in Diatomic Molecules. Journal of Molecular Spectroscopy 66, 259-271, 1977.
Parameters
species Index-mapped specie
Returns
Numeric Lande spin constant
Definition at line 30 of file species_info.cc.
References species_index_from_species_name().
Referenced by Zeeman::GetSimpleModel().