ARTS: species_data.cc File Reference
species_data.cc File Reference
Implementation of function define_species_data().
#include "absorption.h"
#include "arts.h"
Namespaces
global_data
Some #defines for better readability
#define NAME(x) x
#define DEGFR(x) x
#define ISOTOPOLOGUES(...) { __VA_ARGS__ }
#define REC IsotopologueRecord
#define TAGS(...) { __VA_ARGS__ }
void define_basic_species_data ()
Define species lookup data.
void define_partition_species_data ()
void define_species_data ()
void define_species_map ()
Detailed Description
Implementation of function define_species_data().
This file contains the definition of this function and nothing else. You can add new records here if you want to extend the capability of ARTS.
This is the file from arts-1-0, back-ported to arts-1-1. NOTE that adding new data here (new species or new isotopologues) requires equivalent additions in partition_function_data.cc. Also, equivalent data should be added to the isotopratio.xml for other planets residing in the planets/ folders of arts-xml-data should be done.
Author
Stefan Buehler, Axel von Engeln
Date
2000-08-10
Definition in file species_data.cc.
Macro Definition Documentation
DEGFR
#define DEGFR (x) x
Definition at line 52 of file species_data.cc.
ISOTOPOLOGUES
#define ISOTOPOLOGUES (...) { __VA_ARGS__ }
Definition at line 53 of file species_data.cc.
NAME
#define NAME (x) x
Definition at line 51 of file species_data.cc.
REC
#define REC IsotopologueRecord
Definition at line 55 of file species_data.cc.
TAGS
#define TAGS (...) { __VA_ARGS__ }
Definition at line 56 of file species_data.cc.
Function Documentation
define_basic_species_data()
void define_basic_species_data ()
Define species lookup data.
Author
Stefan Buehler, Axel von Engeln
Source for entries
mass as given in file MOLPARAM.TXT of HITRAN2000. If tag is not present in HITRAN, the rounded value is stated. Note that the mass is given in units of [g/mol].
MY-tags: Extracted from file glob_def.c.
HI-tags: According to HITRAN's molparams.txt (order of isotopologues determines isotopologue number) found in ftp://cfa-ftp.harvard.edu/pub/HITRAN-XXXX/Global_Data/, where XXXX stands for the respective HITRAN version.
JPL-tags: From JPL species list documented on http://spec.jpl.nasa.gov/ftp/pub/catalog/catdir.html.
Some more information can be found at svn:arts/branches/ARTS-1-0/misc/abundances/, where the idl script that reads/converts the isotopologue ratios is located.
Author
Axel von Engeln, Jana Mendrok
Date
2000-08-08
Definition at line 163 of file species_data.cc.
References DEGFR, ISOTOPOLOGUES, NAME, REC, global_data::species_data, and TAGS.
Referenced by define_species_data().
define_partition_species_data()
void define_partition_species_data ()
Definition at line 188 of file partition_function_data.cc.
References ARTS_ASSERT, iso(), next_species(), IsotopologueRecord::PF_FROMCOEFF, Qcoeff, and global_data::species_data.
Referenced by define_species_data().
define_species_data()
void define_species_data ()
Definition at line 158 of file species_data.cc.
References define_basic_species_data(), and define_partition_species_data().
Referenced by ARTS::init(), InteractiveWorkspace::initialize(), main(), test001(), test_hitran2017(), test_mpm20(), and test_zeeman().
define_species_map()
void define_species_map ()
Define the species data map.
Author
Stefan Buehler
Definition at line 1093 of file species_data.cc.
References global_data::species_data, and global_data::SpeciesMap.
Referenced by ARTS::init(), InteractiveWorkspace::initialize(), main(), test001(), test_hitran2017(), test_mpm20(), and test_zeeman().