ARTS: species_tags.cc File Reference
species_tags.cc File Reference
#include <cfloat>
#include "species_tags.h"
Namespaces
Species
Functions
Index find_next_species (const ArrayOfArrayOfSpeciesTag &specs, Species::Species spec, Index i) noexcept
Index find_first_species (const ArrayOfArrayOfSpeciesTag &specs, Species::Species spec) noexcept
Index find_first_species_tag (const ArrayOfArrayOfSpeciesTag &specs, const SpeciesTag &tag) noexcept
void check_abs_species (const ArrayOfArrayOfSpeciesTag &abs_species)
std::set< Species::Species > lbl_species (const ArrayOfArrayOfSpeciesTag &abs_species) noexcept
Function Documentation
check_abs_species()
void check_abs_species (const ArrayOfArrayOfSpeciesTag & abs_species)
Checks on the correctness of the tags will be performed, e.g. free_electrons and particles species are only allowed once in abs_species.
Parameters
tags Array of Array of SpeciesTag.
Author
Oliver Lemke
Date
2013-04-23
Definition at line 368 of file species_tags.cc.
References ARTS::Var::abs_species(), ARTS_USER_ERROR_IF, Absorption::nelem(), and Type.
Referenced by abs_speciesAdd(), abs_speciesAdd2(), abs_speciesSet(), propmat_clearskyAddLines(), and zeeman_on_the_fly().
find_first_species()
Index find_first_species (const ArrayOfArrayOfSpeciesTag & specs, Species::Species spec) noexcept
Definition at line 355 of file species_tags.cc.
References find_next_species().
Referenced by abs_lookupSetup(), abs_lookupSetupBatch(), abs_xsec_per_speciesAddCIA(), GasAbsLookup::Extract(), refr_index_airMicrowavesEarth(), and set_vmr_from_first_species().
find_first_species_tag()
Index find_first_species_tag (const ArrayOfArrayOfSpeciesTag & specs, const SpeciesTag & tag) noexcept
Definition at line 359 of file species_tags.cc.
Referenced by abs_xsec_agenda_checkedCalc().
find_next_species()
Index find_next_species (const ArrayOfArrayOfSpeciesTag & specs, Species::Species spec, Index i) noexcept
Definition at line 349 of file species_tags.cc.
Referenced by choose_abs_nls(), and find_first_species().
lbl_species()
std::set<Species::Species> lbl_species (const ArrayOfArrayOfSpeciesTag & abs_species) noexcept
Find species that requires line-by-line calculations
Parameters
abs_species As WSV
Returns
The set of unique species that requires line-by-line calculations
Definition at line 418 of file species_tags.cc.
References ARTS::Var::abs_species().
Referenced by abs_lines_per_speciesReadSpeciesSplitCatalog(), abs_lines_per_speciesReadSplitCatalog(), and ReadSplitARTSCAT().