ARTS: NameMaps Struct Reference
NameMaps Struct Reference
Public Member Functions
NameMaps ()
Public Attributes
std::map< std::string, AgendaData > agendaname_agenda
std::vector< Method > methodname_method
std::map< std::string, Group > varname_group
std::map< std::string, std::size_t > group
Detailed Description
Definition at line 346 of file make_autoarts_h.cc.
Constructor & Destructor Documentation
NameMaps()
NameMaps::NameMaps () inline
Definition at line 352 of file make_autoarts_h.cc.
References agendaname_agenda, agendas(), group, groups(), methodname_method, methods(), varname_group, and global_data::WsvGroupMap.
Member Data Documentation
agendaname_agenda
std::map<std::string, AgendaData> NameMaps::agendaname_agenda
Definition at line 347 of file make_autoarts_h.cc.
Referenced by NameMaps().
group
std::map<std::string, std::size_t> NameMaps::group
Definition at line 350 of file make_autoarts_h.cc.
Referenced by NameMaps().
methodname_method
std::vector<Method> NameMaps::methodname_method
Definition at line 348 of file make_autoarts_h.cc.
Referenced by NameMaps().
varname_group
std::map<std::string, Group> NameMaps::varname_group
Definition at line 349 of file make_autoarts_h.cc.
Referenced by NameMaps().
The documentation for this struct was generated from the following file:
make_autoarts_h.cc