ARTS: LineShape::HartmannTran Struct Reference
LineShape::HartmannTran Struct Reference
#include <lineshape.h>
Public Types
enum class CalcType : char {
Noc2tLowZ , Noc2tHighZ , LowXandHighY , LowYandLowX ,
LowYandHighX , Full
}
Public Member Functions
HartmannTran (Numeric F0_noshift, const Output &ls, Numeric GD_div_F0, Numeric dZ) noexcept
Complex dFdf () const noexcept
Complex dFdF0 () const noexcept
Complex dFdD0 (Numeric dD0) const noexcept
Complex dFdG0 (Numeric dG0) const noexcept
Complex dFdD2 (Numeric dD2) const noexcept
Complex dFdG2 (Numeric dG2) const noexcept
Complex dFdFVC (Numeric dFVC) const noexcept
Complex dFdETA (Numeric dETA) const noexcept
Complex dFdH (Numeric dZ) const noexcept
Complex dFdVMR (const Output &d) const noexcept
Complex dFdT (const Output &d, Numeric T) const noexcept
Complex operator() (Numeric f) noexcept
CalcType init (const Complex c2t) const noexcept
void update_calcs () noexcept
void calc () noexcept
Static Public Member Functions
static constexpr Complex dFdDV (Numeric) noexcept
Public Attributes
Complex F
Numeric G0
Numeric D0
Numeric G2
Numeric D2
Numeric FVC
Numeric ETA
Numeric mF0
Numeric invGD
Complex deltax
Complex sqrty
CalcType calcs
Complex x
Complex sqrtxy
Complex sqrtx
Complex z1
Complex z2
Complex w1
Complex w2
Complex A
Complex B
Complex K
Complex dw1
Complex dw2
Detailed Description
Definition at line 180 of file lineshape.h.
Member Enumeration Documentation
CalcType
enum LineShape::HartmannTran::CalcType : char strong
Enumerator
Noc2tLowZ
Noc2tHighZ
LowXandHighY
LowYandLowX
LowYandHighX
Full
Definition at line 181 of file lineshape.h.
Constructor & Destructor Documentation
HartmannTran()
LineShape::HartmannTran::HartmannTran (Numeric F0_noshift, const Output & ls, Numeric GD_div_F0, Numeric dZ) noexcept
Definition at line 470 of file lineshape.cc.
Member Function Documentation
calc()
void LineShape::HartmannTran::calc () noexcept
Definition at line 1709 of file lineshape.cc.
References A, calcs, Full, sqrtxy, sqrty, w(), w1, w2, z1, and z2.
dFdD0()
Complex LineShape::HartmannTran::dFdD0 (Numeric dD0) const noexcept
Definition at line 655 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, LineShape::G2, and Constant::pow2().
dFdD2()
Complex LineShape::HartmannTran::dFdD2 (Numeric dD2) const noexcept
Definition at line 831 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, LineShape::G2, and Constant::pow2().
dFdDV()
static constexpr Complex LineShape::HartmannTran::dFdDV (Numeric) inline static constexpr noexcept
Definition at line 232 of file lineshape.h.
dFdETA()
Complex LineShape::HartmannTran::dFdETA (Numeric dETA) const noexcept
Definition at line 1145 of file lineshape.cc.
References LineShape::D0, LineShape::D2, dx, LineShape::ETA, LineShape::G0, LineShape::G2, and Constant::pow2().
dFdf()
Complex LineShape::HartmannTran::dFdf () const noexcept
Definition at line 480 of file lineshape.cc.
References calcs, D2, dx, ETA, Full, G2, and sqrtxy.
dFdF0()
Complex LineShape::HartmannTran::dFdF0 () const noexcept
Definition at line 560 of file lineshape.cc.
References calcs, D2, dx, ETA, Full, G2, invGD, mF0, Constant::pow2(), sqrtxy, and sqrty.
dFdFVC()
Complex LineShape::HartmannTran::dFdFVC (Numeric dFVC) const noexcept
Definition at line 1059 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, and LineShape::G2.
dFdG0()
Complex LineShape::HartmannTran::dFdG0 (Numeric dG0) const noexcept
Definition at line 751 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, and LineShape::G2.
dFdG2()
Complex LineShape::HartmannTran::dFdG2 (Numeric dG2) const noexcept
Definition at line 954 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, LineShape::G2, and Constant::pow2().
dFdH()
Complex LineShape::HartmannTran::dFdH (Numeric dZ) const noexcept
Definition at line 1264 of file lineshape.cc.
References LineShape::D2, dx, LineShape::ETA, LineShape::G2, and Constant::pow2().
dFdT()
Complex LineShape::HartmannTran::dFdT (const Output & d, Numeric T) const noexcept
Definition at line 1521 of file lineshape.cc.
References d, LineShape::D0, LineShape::D2, and LineShape::ETA.
dFdVMR()
Complex LineShape::HartmannTran::dFdVMR (const Output & d) const noexcept
Definition at line 1360 of file lineshape.cc.
References d, LineShape::D0, LineShape::D2, dx, LineShape::ETA, LineShape::G0, LineShape::G2, and Constant::pow2().
init()
HartmannTran::CalcType LineShape::HartmannTran::init (const Complex c2t) const noexcept
Definition at line 1691 of file lineshape.cc.
References LineShape::abs_squared(), and ARTS::Var::x().
Referenced by update_calcs().
operator()()
Complex LineShape::HartmannTran::operator() (Numeric f) noexcept
Definition at line 1682 of file lineshape.cc.
References LineShape::D2, LineShape::ETA, LineShape::G2, imag_val(), sqrt(), and ARTS::Var::x().
update_calcs()
void LineShape::HartmannTran::update_calcs () noexcept
Definition at line 1705 of file lineshape.cc.
References calcs, D2, ETA, G2, and init().
Member Data Documentation
A
Complex LineShape::HartmannTran::A
Definition at line 212 of file lineshape.h.
Referenced by calc().
B
Complex LineShape::HartmannTran::B
Definition at line 213 of file lineshape.h.
calcs
CalcType LineShape::HartmannTran::calcs
Definition at line 203 of file lineshape.h.
Referenced by calc(), dFdf(), dFdF0(), and update_calcs().
D0
Numeric LineShape::HartmannTran::D0
Definition at line 193 of file lineshape.h.
D2
Numeric LineShape::HartmannTran::D2
Definition at line 195 of file lineshape.h.
Referenced by dFdf(), dFdF0(), and update_calcs().
deltax
Complex LineShape::HartmannTran::deltax
Definition at line 200 of file lineshape.h.
dw1
Complex LineShape::HartmannTran::dw1
Definition at line 215 of file lineshape.h.
dw2
Complex LineShape::HartmannTran::dw2
Definition at line 216 of file lineshape.h.
ETA
Numeric LineShape::HartmannTran::ETA
Definition at line 197 of file lineshape.h.
Referenced by dFdf(), dFdF0(), and update_calcs().
F
Complex LineShape::HartmannTran::F
Definition at line 190 of file lineshape.h.
FVC
Numeric LineShape::HartmannTran::FVC
Definition at line 196 of file lineshape.h.
G0
Numeric LineShape::HartmannTran::G0
Definition at line 192 of file lineshape.h.
G2
Numeric LineShape::HartmannTran::G2
Definition at line 194 of file lineshape.h.
Referenced by dFdf(), dFdF0(), and update_calcs().
invGD
Numeric LineShape::HartmannTran::invGD
Definition at line 199 of file lineshape.h.
Referenced by dFdF0().
K
Complex LineShape::HartmannTran::K
Definition at line 214 of file lineshape.h.
mF0
Numeric LineShape::HartmannTran::mF0
Definition at line 198 of file lineshape.h.
Referenced by dFdF0().
sqrtx
Complex LineShape::HartmannTran::sqrtx
Definition at line 207 of file lineshape.h.
sqrtxy
Complex LineShape::HartmannTran::sqrtxy
Definition at line 206 of file lineshape.h.
Referenced by calc(), dFdf(), and dFdF0().
sqrty
Complex LineShape::HartmannTran::sqrty
Definition at line 201 of file lineshape.h.
Referenced by calc(), and dFdF0().
w1
Complex LineShape::HartmannTran::w1
Definition at line 210 of file lineshape.h.
Referenced by calc().
w2
Complex LineShape::HartmannTran::w2
Definition at line 211 of file lineshape.h.
Referenced by calc().
x
Complex LineShape::HartmannTran::x
Definition at line 205 of file lineshape.h.
z1
Complex LineShape::HartmannTran::z1
Definition at line 208 of file lineshape.h.
Referenced by calc().
z2
Complex LineShape::HartmannTran::z2
Definition at line 209 of file lineshape.h.
Referenced by calc().
The documentation for this struct was generated from the following files:
lineshape.h
lineshape.cc