ARTS: lapack_help::Inverse< T > Struct Template Reference
lapack_help::Inverse< T > Struct Template Reference
Struct cannot be const, but can be passed as const to allow defaults.
#include <lapack.h>
Public Member Functions
Inverse (Index N) noexcept
bool resize_if_smaller (Index N) const
int * size () const noexcept
int * lsize () const noexcept
T * workdata () const noexcept
int * ipivdata () const noexcept
Public Attributes
int n
int lwork
std::vector< T > work
std::vector< int > ipiv
Detailed Description
template<typename T>
struct lapack_help::Inverse< T >
Struct cannot be const, but can be passed as const to allow defaults.
Definition at line 23 of file lapack.h.
Constructor & Destructor Documentation
Inverse()
template<typename T > lapack_help::Inverse< T >::Inverse (Index N) inline explicit noexcept
Definition at line 29 of file lapack.h.
Member Function Documentation
ipivdata()
template<typename T > int* lapack_help::Inverse< T >::ipivdata () const inline noexcept
Definition at line 46 of file lapack.h.
References lapack_help::Inverse< T >::ipiv.
Referenced by ComplexMatrix::inv().
lsize()
template<typename T > int* lapack_help::Inverse< T >::lsize () const inline noexcept
Definition at line 44 of file lapack.h.
References lapack_help::Inverse< T >::lwork.
Referenced by ComplexMatrix::inv().
resize_if_smaller()
template<typename T > bool lapack_help::Inverse< T >::resize_if_smaller (Index N) const inline
Definition at line 31 of file lapack.h.
References lapack_help::Inverse< T >::ipiv, lapack_help::Inverse< T >::lwork, lapack_help::Inverse< T >::n, N, and lapack_help::Inverse< T >::work.
Referenced by ComplexMatrix::inv().
size()
template<typename T > int* lapack_help::Inverse< T >::size () const inline noexcept
Definition at line 43 of file lapack.h.
References lapack_help::Inverse< T >::n.
Referenced by ComplexMatrix::inv().
workdata()
template<typename T > T* lapack_help::Inverse< T >::workdata () const inline noexcept
Definition at line 45 of file lapack.h.
References lapack_help::Inverse< T >::work.
Referenced by ComplexMatrix::inv().
Member Data Documentation
ipiv
template<typename T > std::vector<int> lapack_help::Inverse< T >::ipiv mutable
Definition at line 27 of file lapack.h.
Referenced by lapack_help::Inverse< T >::ipivdata(), and lapack_help::Inverse< T >::resize_if_smaller().
lwork
template<typename T > int lapack_help::Inverse< T >::lwork mutable
Definition at line 25 of file lapack.h.
Referenced by lapack_help::Inverse< T >::lsize(), and lapack_help::Inverse< T >::resize_if_smaller().
n
template<typename T > int lapack_help::Inverse< T >::n mutable
Definition at line 24 of file lapack.h.
Referenced by lapack_help::Inverse< T >::resize_if_smaller(), and lapack_help::Inverse< T >::size().
work
template<typename T > std::vector<T> lapack_help::Inverse< T >::work mutable
Definition at line 26 of file lapack.h.
Referenced by lapack_help::Inverse< T >::resize_if_smaller(), and lapack_help::Inverse< T >::workdata().
The documentation for this struct was generated from the following file:
lapack.h