ARTS: LineShape::VanVleckHuber Struct Reference
LineShape::VanVleckHuber Struct Reference
#include <lineshape.h>
Public Member Functions
VanVleckHuber (Numeric F0, Numeric T) noexcept
Numeric dNdT (Numeric T, Numeric f) const noexcept
Numeric dNdf (Numeric f) const noexcept
Numeric dNdF0 () const noexcept
Numeric operator() (Numeric f) noexcept
Public Attributes
Numeric N
Numeric c1
Numeric tanh_c1f0
Numeric inv_denom
Numeric tanh_c1f
Detailed Description
Definition at line 253 of file lineshape.h.
Constructor & Destructor Documentation
VanVleckHuber()
LineShape::VanVleckHuber::VanVleckHuber (Numeric F0, Numeric T) noexcept
Definition at line 1771 of file lineshape.cc.
Member Function Documentation
dNdf()
Numeric LineShape::VanVleckHuber::dNdf (Numeric f) const noexcept
Definition at line 1782 of file lineshape.cc.
References Constant::pow2().
dNdF0()
Numeric LineShape::VanVleckHuber::dNdF0 () const noexcept
Definition at line 1788 of file lineshape.cc.
References c1, inv_denom, N, Constant::pow2(), and tanh_c1f0.
dNdT()
Numeric LineShape::VanVleckHuber::dNdT (Numeric T, Numeric f) const noexcept
Definition at line 1775 of file lineshape.cc.
References Constant::pow2().
operator()()
Numeric LineShape::VanVleckHuber::operator() (Numeric f) noexcept
Definition at line 1794 of file lineshape.cc.
References N.
Member Data Documentation
c1
Numeric LineShape::VanVleckHuber::c1
Definition at line 256 of file lineshape.h.
Referenced by dNdF0().
inv_denom
Numeric LineShape::VanVleckHuber::inv_denom
Definition at line 258 of file lineshape.h.
Referenced by dNdF0().
N
Numeric LineShape::VanVleckHuber::N
Definition at line 254 of file lineshape.h.
Referenced by dNdF0().
tanh_c1f
Numeric LineShape::VanVleckHuber::tanh_c1f
Definition at line 259 of file lineshape.h.
tanh_c1f0
Numeric LineShape::VanVleckHuber::tanh_c1f0
Definition at line 257 of file lineshape.h.
Referenced by dNdF0().
The documentation for this struct was generated from the following files:
lineshape.h
lineshape.cc