ARTS: Absorption::LineMixing::MapOfErrorCorrectedSuddenData Struct Reference
Absorption::LineMixing::MapOfErrorCorrectedSuddenData Struct Reference
#include <linemixing.h>
Public Member Functions
ErrorCorrectedSuddenData & operator[] (const Quantum::Identifier &id) noexcept
const ErrorCorrectedSuddenData & operator[] (const Quantum::Identifier &id) const
const ErrorCorrectedSuddenData & operator[] (Index i) const ARTS_NOEXCEPT
ErrorCorrectedSuddenData & operator[] (Index i) ARTS_NOEXCEPT
Public Member Functions inherited from Array< ErrorCorrectedSuddenData >
Array ()
Array (Index n)
Array (Index n, const ErrorCorrectedSuddenData &fillvalue)
Constructor filling with constant value.
Array (const Array< ErrorCorrectedSuddenData > &A)
Array (Array< ErrorCorrectedSuddenData > &&A) noexcept
Array (std::initializer_list< ErrorCorrectedSuddenData > init)
Array (const std::array< base2, N > &input)
Array & operator= (ErrorCorrectedSuddenData x)
Assignment from base type (fill entire Array with this value).
Array & operator= (const Array< ErrorCorrectedSuddenData > &A)
Assignment from another Array.
Array & operator= (Array< ErrorCorrectedSuddenData > &&A) noexcept
Index nelem () const ARTS_NOEXCEPT
Number of elements.
const ErrorCorrectedSuddenData & operator[] (const Index n) const
Constant index operator.
ErrorCorrectedSuddenData & operator[] (const Index n)
Non-constant index operator.
void push_back_n (const ErrorCorrectedSuddenData &elem, const Index n)
Append element n times.
virtual ~Array ()=default
Friends
std::ostream & operator<< (std::ostream &os, const MapOfErrorCorrectedSuddenData &m)
Detailed Description
Definition at line 177 of file linemixing.h.
Member Function Documentation
operator[]() [1/4]
const ErrorCorrectedSuddenData& Absorption::LineMixing::MapOfErrorCorrectedSuddenData::operator[] (const Quantum::Identifier & id) const inline
Definition at line 186 of file linemixing.h.
References ARTS_USER_ERROR.
operator[]() [2/4]
ErrorCorrectedSuddenData& Absorption::LineMixing::MapOfErrorCorrectedSuddenData::operator[] (const Quantum::Identifier & id) inline noexcept
Definition at line 178 of file linemixing.h.
References Zeeman::end().
operator[]() [3/4]
ErrorCorrectedSuddenData& Absorption::LineMixing::MapOfErrorCorrectedSuddenData::operator[] (Index i) inline
Definition at line 200 of file linemixing.h.
References ARTS_ASSERT, and Array< ErrorCorrectedSuddenData >::nelem().
operator[]() [4/4]
const ErrorCorrectedSuddenData& Absorption::LineMixing::MapOfErrorCorrectedSuddenData::operator[] (Index i) const inline
Definition at line 195 of file linemixing.h.
References ARTS_ASSERT, and Array< ErrorCorrectedSuddenData >::nelem().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const MapOfErrorCorrectedSuddenData & m) friend
Definition at line 205 of file linemixing.h.
The documentation for this struct was generated from the following file:
linemixing.h