ARTS: LineShape::ComputeData Struct Reference
LineShape::ComputeData Struct Reference
#include <lineshape.h>
Public Member Functions
ComputeData (const Vector &f, const ArrayOfRetrievalQuantity &jacobian_quantities, const bool nlte) noexcept
void reset () noexcept
void interp_add_even (const ComputeData &sparse) ARTS_NOEXCEPT
void interp_add_triplequad (const ComputeData &sparse) ARTS_NOEXCEPT
Public Attributes
ComplexVector F
ComplexVector N
ComplexMatrix dF
ComplexMatrix dN
const Vector & f_grid
const bool do_nlte
Detailed Description
Definition at line 547 of file lineshape.h.
Constructor & Destructor Documentation
ComputeData()
LineShape::ComputeData::ComputeData (const Vector & f, const ArrayOfRetrievalQuantity & jacobian_quantities, const bool nlte) inline noexcept
Definition at line 553 of file lineshape.h.
Member Function Documentation
interp_add_even()
void LineShape::ComputeData::interp_add_even (const ComputeData & sparse)
Definition at line 3368 of file lineshape.cc.
References ARTS_ASSERT, ARTS::Var::f_grid(), inv(), and N.
Referenced by propmat_clearskyAddLines().
interp_add_triplequad()
void LineShape::ComputeData::interp_add_triplequad (const ComputeData & sparse)
Definition at line 3409 of file lineshape.cc.
References ARTS_ASSERT, ARTS::Var::f_grid(), inv(), N, and Constant::pow2().
Referenced by propmat_clearskyAddLines().
reset()
void LineShape::ComputeData::reset () inline noexcept
Definition at line 561 of file lineshape.h.
References LineShape::SpeedDependentVoigt::F, and N.
Referenced by propmat_clearskyAddLines(), and zeeman_on_the_fly().
Member Data Documentation
dF
ComplexMatrix LineShape::ComputeData::dF
Definition at line 549 of file lineshape.h.
Referenced by propmat_clearskyAddLines(), test_ls(), and zeeman_on_the_fly().
dN
ComplexMatrix LineShape::ComputeData::dN
Definition at line 549 of file lineshape.h.
Referenced by propmat_clearskyAddLines(), test_ls(), and zeeman_on_the_fly().
do_nlte
const bool LineShape::ComputeData::do_nlte
Definition at line 551 of file lineshape.h.
F
ComplexVector LineShape::ComputeData::F
Definition at line 548 of file lineshape.h.
Referenced by propmat_clearskyAddLines(), test_ls(), and zeeman_on_the_fly().
f_grid
const Vector& LineShape::ComputeData::f_grid
Definition at line 550 of file lineshape.h.
N
ComplexVector LineShape::ComputeData::N
Definition at line 548 of file lineshape.h.
Referenced by propmat_clearskyAddLines(), test_ls(), and zeeman_on_the_fly().
The documentation for this struct was generated from the following files:
lineshape.h
lineshape.cc