ARTS: Interpolation::Lagrange Struct Reference
Interpolation::Lagrange Struct Reference
A Lagrange interpolation computer.
#include <interpolation_lagrange.h>
Public Member Functions
Index size () const noexcept
Lagrange (Lagrange &&l) noexcept
Ensure that the move constructor exists.
Lagrange (const Lagrange &l) noexcept
Ensure that the copy constructor exists.
Lagrange & operator= (Lagrange &&l) noexcept
Ensure that the move operator exists.
Lagrange & operator= (const Lagrange &l) noexcept
Ensure that the copy operator exists.
template<class SortedVectorType >
Lagrange (const Index pos0, const Numeric x, const SortedVectorType &xi, const Index polyorder=1, const bool do_derivs=false, const GridType type=GridType::Standard, const std::pair< Numeric, Numeric > cycle={-180, 180}) noexcept
Lagrange () noexcept
Default constructor for zero-length elements.
Public Attributes
Index pos
Array< Numeric > lx
Array< Numeric > dlx
Static Private Member Functions
template<class SortedVectorType >
static Array< Numeric > lx_finder (const Index p0, const Index n, const Numeric x, const SortedVectorType &xi, const GridType type, const std::pair< Numeric, Numeric > cycle) noexcept
template<class SortedVectorType >
static Array< Numeric > dlx_finder (const Index p0, const Index n, const Numeric x, const SortedVectorType &xi, const Array< Numeric > &li, const GridType type, const std::pair< Numeric, Numeric > cycle) noexcept
Friends
std::ostream & operator<< (std::ostream &os, const Lagrange &l)
Detailed Description
A Lagrange interpolation computer.
Definition at line 668 of file interpolation_lagrange.h.
Constructor & Destructor Documentation
Lagrange() [1/4]
Interpolation::Lagrange::Lagrange (Lagrange && l) inline noexcept
Ensure that the move constructor exists.
Definition at line 682 of file interpolation_lagrange.h.
Lagrange() [2/4]
Interpolation::Lagrange::Lagrange (const Lagrange & l) inline noexcept
Ensure that the copy constructor exists.
Definition at line 685 of file interpolation_lagrange.h.
Lagrange() [3/4]
template<class SortedVectorType > Interpolation::Lagrange::Lagrange (const Index pos0, const Numeric x, const SortedVectorType & xi, const Index polyorder = 1, const bool do_derivs = false, const GridType type = GridType::Standard, const std::pair< Numeric, Numeric > cycle = {-180, 180}) inline noexcept
Standard initializer, assumes sorted xi
Parameters
[in] pos0 Estimation of original position, must be [0, xi.size())
[in] x New grid position
[in] xi Old grid positions
[in] polyorder Polynominal degree
[in] do_derivs Compute derivatives?
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 714 of file interpolation_lagrange.h.
Lagrange() [4/4]
Interpolation::Lagrange::Lagrange () inline noexcept
Default constructor for zero-length elements.
Definition at line 735 of file interpolation_lagrange.h.
Member Function Documentation
dlx_finder()
template<class SortedVectorType > static Array<Numeric> Interpolation::Lagrange::dlx_finder (const Index p0, const Index n, const Numeric x, const SortedVectorType & xi, const Array< Numeric > & li, const GridType type, const std::pair< Numeric, Numeric > cycle) inline static private noexcept
Finds dlx
Parameters
[in] p0 Estimation of original position, must be [0, xi.size())
[in] n The number of lx to find
[in] x New grid position
[in] xi Old grid positions
[in] li The lx produced by lx_finder
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 816 of file interpolation_lagrange.h.
References x.
lx_finder()
template<class SortedVectorType > static Array<Numeric> Interpolation::Lagrange::lx_finder (const Index p0, const Index n, const Numeric x, const SortedVectorType & xi, const GridType type, const std::pair< Numeric, Numeric > cycle) inline static private noexcept
Finds lx
Parameters
[in] p0 Estimation of original position, must be [0, xi.size())
[in] n The number of lx to find
[in] x New grid position
[in] xi Old grid positions
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 757 of file interpolation_lagrange.h.
References x.
operator=() [1/2]
Lagrange& Interpolation::Lagrange::operator= (const Lagrange & l) inline noexcept
Ensure that the copy operator exists.
Definition at line 696 of file interpolation_lagrange.h.
References dlx, Interpolation::l(), lx, and pos.
operator=() [2/2]
Lagrange& Interpolation::Lagrange::operator= (Lagrange && l) inline noexcept
Ensure that the move operator exists.
Definition at line 688 of file interpolation_lagrange.h.
References dlx, Interpolation::l(), lx, and pos.
size()
Index Interpolation::Lagrange::size () const inline noexcept
Definition at line 679 of file interpolation_lagrange.h.
References lx.
Referenced by Interpolation::dinterpweights(), Interpolation::interp(), and Interpolation::interpweights().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Lagrange & l) friend
Friendly stream operator
Definition at line 738 of file interpolation_lagrange.h.
Member Data Documentation
dlx
Array<Numeric> Interpolation::Lagrange::dlx
The Lagrange interpolation weights derivatives at each point
Definition at line 676 of file interpolation_lagrange.h.
Referenced by Interpolation::dinterpweights(), and operator=().
lx
Array<Numeric> Interpolation::Lagrange::lx
The Lagrange interpolation weights at each point
Definition at line 673 of file interpolation_lagrange.h.
Referenced by Interpolation::dinterpweights(), Interpolation::interpweights(), operator=(), and size().
pos
Index Interpolation::Lagrange::pos
The first position of the Lagrange interpolation grid
Definition at line 670 of file interpolation_lagrange.h.
Referenced by Interpolation::interp(), and operator=().
The documentation for this struct was generated from the following file:
interpolation_lagrange.h