ARTS: LineShape::Lorentz Struct Reference
LineShape::Lorentz Struct Reference
#include <lineshape.h>
Public Member Functions
constexpr Lorentz (Numeric F0_noshift, const Output &ls) noexcept
constexpr Complex dFdVMR (const Output &d) const noexcept
constexpr Complex dFdT (const Output &d, Numeric) const noexcept
constexpr Complex dFdf () const noexcept
constexpr Complex dFdF0 () const noexcept
constexpr Complex dFdDV (Numeric d) const noexcept
constexpr Complex dFdD0 (Numeric d) const noexcept
constexpr Complex dFdG0 (Numeric d) const noexcept
constexpr Complex operator() (Numeric f) noexcept
Static Public Member Functions
static constexpr Complex dFdH (Numeric) noexcept
static constexpr Complex dFdD2 (Numeric) noexcept
static constexpr Complex dFdG2 (Numeric)
static constexpr Complex dFdETA (Numeric) noexcept
static constexpr Complex dFdFVC (Numeric) noexcept
Public Attributes
Complex F
Complex dF
Numeric mF0
Numeric G0
Detailed Description
Definition at line 63 of file lineshape.h.
Constructor & Destructor Documentation
Lorentz()
constexpr LineShape::Lorentz::Lorentz (Numeric F0_noshift, const Output & ls) inline constexpr noexcept
Definition at line 70 of file lineshape.h.
Member Function Documentation
dFdD0()
constexpr Complex LineShape::Lorentz::dFdD0 (Numeric d) const inline constexpr noexcept
Definition at line 82 of file lineshape.h.
References d, and dFdF0().
dFdD2()
static constexpr Complex LineShape::Lorentz::dFdD2 (Numeric) inline static constexpr noexcept
Definition at line 85 of file lineshape.h.
dFdDV()
constexpr Complex LineShape::Lorentz::dFdDV (Numeric d) const inline constexpr noexcept
Definition at line 81 of file lineshape.h.
References d, and dFdF0().
dFdETA()
static constexpr Complex LineShape::Lorentz::dFdETA (Numeric) inline static constexpr noexcept
Definition at line 87 of file lineshape.h.
dFdf()
constexpr Complex LineShape::Lorentz::dFdf () const inline constexpr noexcept
Definition at line 79 of file lineshape.h.
References dF.
dFdF0()
constexpr Complex LineShape::Lorentz::dFdF0 () const inline constexpr noexcept
Definition at line 80 of file lineshape.h.
References dF.
Referenced by dFdD0(), and dFdDV().
dFdFVC()
static constexpr Complex LineShape::Lorentz::dFdFVC (Numeric) inline static constexpr noexcept
Definition at line 88 of file lineshape.h.
dFdG0()
constexpr Complex LineShape::Lorentz::dFdG0 (Numeric d) const inline constexpr noexcept
Definition at line 84 of file lineshape.h.
References d, and dF.
dFdG2()
static constexpr Complex LineShape::Lorentz::dFdG2 (Numeric) inline static constexpr
Definition at line 86 of file lineshape.h.
dFdH()
static constexpr Complex LineShape::Lorentz::dFdH (Numeric) inline static constexpr noexcept
Definition at line 83 of file lineshape.h.
dFdT()
constexpr Complex LineShape::Lorentz::dFdT (const Output & d, Numeric) const inline constexpr noexcept
Definition at line 76 of file lineshape.h.
References d, and dFdVMR().
dFdVMR()
constexpr Complex LineShape::Lorentz::dFdVMR (const Output & d) const inline constexpr noexcept
Definition at line 73 of file lineshape.h.
References d, and dF.
Referenced by dFdT().
operator()()
constexpr Complex LineShape::Lorentz::operator() (Numeric f) inline constexpr noexcept
Definition at line 90 of file lineshape.h.
References dF, F, G0, mF0, and Constant::pow2().
Member Data Documentation
dF
Complex LineShape::Lorentz::dF
Definition at line 65 of file lineshape.h.
Referenced by dFdf(), dFdF0(), dFdG0(), dFdVMR(), and operator()().
F
Complex LineShape::Lorentz::F
Definition at line 64 of file lineshape.h.
Referenced by operator()().
G0
Numeric LineShape::Lorentz::G0
Definition at line 68 of file lineshape.h.
Referenced by operator()().
mF0
Numeric LineShape::Lorentz::mF0
Definition at line 67 of file lineshape.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
lineshape.h