ARTS: Species::IsotopologueRatios Struct Reference
Species::IsotopologueRatios Struct Reference
#include <isotopologues.h>
Public Member Functions
constexpr IsotopologueRatios () noexcept
constexpr Numeric operator[] (const Index spec_ind) const ARTS_NOEXCEPT
constexpr Numeric operator[] (const IsotopeRecord &ir) const
constexpr bool all_isotopes_have_a_value () const noexcept
Public Attributes
std::array< Numeric, maxsize > data
Static Public Attributes
static constexpr Index maxsize = Index(Isotopologues.size())
Friends
std::ostream & operator<< (std::ostream &os, const IsotopologueRatios &iso_rat)
Detailed Description
Definition at line 673 of file isotopologues.h.
Constructor & Destructor Documentation
IsotopologueRatios()
constexpr Species::IsotopologueRatios::IsotopologueRatios () inline constexpr noexcept
Definition at line 677 of file isotopologues.h.
References data, and ARTS::Var::x().
Member Function Documentation
all_isotopes_have_a_value()
constexpr bool Species::IsotopologueRatios::all_isotopes_have_a_value () const inline constexpr noexcept
Definition at line 702 of file isotopologues.h.
References data, Species::is_predefined_model(), nonstd::isnan(), Species::Isotopologues, joker, and maxsize.
operator[]() [1/2]
constexpr Numeric Species::IsotopologueRatios::operator[] (const Index spec_ind) const inline constexpr
Definition at line 681 of file isotopologues.h.
References ARTS_ASSERT, and data.
operator[]() [2/2]
constexpr Numeric Species::IsotopologueRatios::operator[] (const IsotopeRecord & ir) const inline constexpr
Definition at line 686 of file isotopologues.h.
References ARTS_USER_ERROR_IF, data, Species::find_species_index(), Species::IsotopeRecord::FullName(), and maxsize.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const IsotopologueRatios & iso_rat) friend
Definition at line 693 of file isotopologues.h.
Member Data Documentation
data
std::array<Numeric, maxsize> Species::IsotopologueRatios::data
Definition at line 675 of file isotopologues.h.
Referenced by all_isotopes_have_a_value(), Hitran::isotopologue_ratios_impl(), IsotopologueRatios(), operator[](), and xml_read_from_stream().
maxsize
constexpr Index Species::IsotopologueRatios::maxsize = Index(Isotopologues.size()) static constexpr
Definition at line 674 of file isotopologues.h.
Referenced by all_isotopes_have_a_value(), operator[](), xml_read_from_stream(), and xml_write_to_stream().
The documentation for this struct was generated from the following file:
isotopologues.h