ARTS: Interpolation::FixedLagrange< PolyOrder > Struct Template Reference
Interpolation::FixedLagrange< PolyOrder > Struct Template Reference
#include <interpolation_lagrange.h>
Public Member Functions
constexpr FixedLagrange (FixedLagrange &&l) noexcept
Enusre that the move constructor exists.
constexpr FixedLagrange & operator= (FixedLagrange &&l) noexcept
Enusre that the move operator exists.
template<class SortedVectorType >
constexpr FixedLagrange (const Index p0, const Numeric x, const SortedVectorType &xi, const bool do_derivs=false, const GridType type=GridType::Standard, const std::pair< Numeric, Numeric > cycle={-180, 180}) noexcept
Static Public Member Functions
static constexpr Index size () noexcept
Public Attributes
Index pos
std::array< Numeric, PolyOrder+1 > lx
std::array< Numeric, PolyOrder+1 > dlx
Static Private Member Functions
template<class SortedVectorType >
static constexpr std::array< Numeric, PolyOrder+1 > lx_finder (const Index p0, const Numeric x, const SortedVectorType &xi, const GridType type, const std::pair< Numeric, Numeric > cycle) noexcept
template<class SortedVectorType >
static constexpr std::array< Numeric, PolyOrder+1 > dlx_finder (const Index p0, const Numeric x, const SortedVectorType &xi, const std::array< Numeric, PolyOrder+1 > &li, const GridType type, const std::pair< Numeric, Numeric > cycle) noexcept
Friends
std::ostream & operator<< (std::ostream &os, const FixedLagrange &l)
Detailed Description
template<std::size_t PolyOrder>
struct Interpolation::FixedLagrange< PolyOrder >
A Fixed Lagrange interpolation computer
Definition at line 863 of file interpolation_lagrange.h.
Constructor & Destructor Documentation
FixedLagrange() [1/2]
template<std::size_t PolyOrder> constexpr Interpolation::FixedLagrange< PolyOrder >::FixedLagrange (FixedLagrange< PolyOrder > && l) inline constexpr noexcept
Enusre that the move constructor exists.
Definition at line 877 of file interpolation_lagrange.h.
FixedLagrange() [2/2]
template<std::size_t PolyOrder> template<class SortedVectorType > constexpr Interpolation::FixedLagrange< PolyOrder >::FixedLagrange (const Index p0, const Numeric x, const SortedVectorType & xi, const bool do_derivs = false, const GridType type = GridType::Standard, const std::pair< Numeric, Numeric > cycle = {-180, 180}) inline constexpr noexcept
Standard initializer from Vector-types
Parameters
[in] pos0 Estimation of original position, must be [0, xi.size())
[in] x New grid position
[in] xi Old grid positions
[in] do_derivs Compute derivatives?
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 897 of file interpolation_lagrange.h.
Member Function Documentation
dlx_finder()
template<std::size_t PolyOrder> template<class SortedVectorType > static constexpr std::array<Numeric, PolyOrder + 1> Interpolation::FixedLagrange< PolyOrder >::dlx_finder (const Index p0, const Numeric x, const SortedVectorType & xi, const std::array< Numeric, PolyOrder+1 > & li, const GridType type, const std::pair< Numeric, Numeric > cycle) inline static constexpr private noexcept
Finds dlx
Parameters
[in] p0 Estimation of original position, must be [0, xi.size())
[in] x New grid position
[in] xi Old grid positions
[in] li The lx produced by lx_finder
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 987 of file interpolation_lagrange.h.
References Hitran::type, and ARTS::Var::x().
lx_finder()
template<std::size_t PolyOrder> template<class SortedVectorType > static constexpr std::array<Numeric, PolyOrder + 1> Interpolation::FixedLagrange< PolyOrder >::lx_finder (const Index p0, const Numeric x, const SortedVectorType & xi, const GridType type, const std::pair< Numeric, Numeric > cycle) inline static constexpr private noexcept
Finds lx
Parameters
[in] p0 Estimation of original position, must be [0, xi.size())
[in] x New grid position
[in] xi Old grid positions
[in] type Type of Lagrange
[in] cycle Size of a cycle if Cyclic type
Definition at line 928 of file interpolation_lagrange.h.
References Hitran::type, and ARTS::Var::x().
operator=()
template<std::size_t PolyOrder> constexpr FixedLagrange& Interpolation::FixedLagrange< PolyOrder >::operator= (FixedLagrange< PolyOrder > && l) inline constexpr noexcept
Enusre that the move operator exists.
Definition at line 880 of file interpolation_lagrange.h.
References Interpolation::FixedLagrange< PolyOrder >::dlx, Interpolation::l(), Interpolation::FixedLagrange< PolyOrder >::lx, and Interpolation::FixedLagrange< PolyOrder >::pos.
size()
template<std::size_t PolyOrder> static constexpr Index Interpolation::FixedLagrange< PolyOrder >::size () inline static constexpr noexcept
Definition at line 874 of file interpolation_lagrange.h.
Referenced by Interpolation::dinterpweights(), Interpolation::interp(), Interpolation::interpweights(), and Interpolation::reinterp().
Friends And Related Function Documentation
operator<<
template<std::size_t PolyOrder> std::ostream& operator<< (std::ostream & os, const FixedLagrange< PolyOrder > & l) friend
Friendly stream operator
Definition at line 910 of file interpolation_lagrange.h.
Member Data Documentation
dlx
template<std::size_t PolyOrder> std::array<Numeric, PolyOrder + 1> Interpolation::FixedLagrange< PolyOrder >::dlx
The Lagrange interpolation weights derivatives at each point
Definition at line 871 of file interpolation_lagrange.h.
Referenced by Interpolation::dinterpweights(), and Interpolation::FixedLagrange< PolyOrder >::operator=().
lx
template<std::size_t PolyOrder> std::array<Numeric, PolyOrder + 1> Interpolation::FixedLagrange< PolyOrder >::lx
The Lagrange interpolation weights at each point
Definition at line 868 of file interpolation_lagrange.h.
Referenced by Interpolation::dinterpweights(), Interpolation::interpweights(), and Interpolation::FixedLagrange< PolyOrder >::operator=().
pos
template<std::size_t PolyOrder> Index Interpolation::FixedLagrange< PolyOrder >::pos
The first position of the Lagrange interpolation grid
Definition at line 865 of file interpolation_lagrange.h.
Referenced by Interpolation::interp(), and Interpolation::FixedLagrange< PolyOrder >::operator=().
The documentation for this struct was generated from the following file:
interpolation_lagrange.h