ARTS: Absorption::LineMixing::PopulationAndDipole Struct Reference
Absorption::LineMixing::PopulationAndDipole Struct Reference
Contains the population distribution and dipole.
#include <linemixing.h>
Public Member Functions
PopulationAndDipole (const Numeric T, const AbsorptionLines &band, const SpeciesAuxData::AuxType &partition_type, const ArrayOfGriddedField1 &partition_data) noexcept
ArrayOfIndex sort (const AbsorptionLines &band) noexcept
void sort (const ArrayOfIndex &presorting) noexcept
Public Attributes
Vector pop
Vector dip
Detailed Description
Contains the population distribution and dipole.
Definition at line 47 of file linemixing.h.
Constructor & Destructor Documentation
PopulationAndDipole()
Absorption::LineMixing::PopulationAndDipole::PopulationAndDipole (const Numeric T, const AbsorptionLines & band, const SpeciesAuxData::AuxType & partition_type, const ArrayOfGriddedField1 & partition_data) noexcept
Construct from known parameters
Parameters
[in] T The temperature
[in] band The absorption band
[in] partition_type The type of partition function data
[in] partition_data The partition function data
Definition at line 61 of file linemixing.cc.
References boltzman_factor(), boltzman_ratio(), N, single_partition_function(), sqrt(), and stimulated_emission().
Member Function Documentation
sort() [1/2]
ArrayOfIndex Absorption::LineMixing::PopulationAndDipole::sort (const AbsorptionLines & band) noexcept
Sort self by f0*pop*dip^2 and returns positions of sorted values in the original
Parameters
[in] band The absorption band
Returns
Reshuffling of positions from [0 ... N-1] to new positions
Definition at line 80 of file linemixing.cc.
References N, Constant::pow2(), and swap().
Referenced by Absorption::LineMixing::presorted_population_and_dipole(), and Absorption::LineMixing::sorted_population_and_dipole().
sort() [2/2]
void Absorption::LineMixing::PopulationAndDipole::sort (const ArrayOfIndex & presorting) noexcept
Sort self by pre-sorted sorting mechanism
Parameters
[in] presorting Changes positions from [0 ... N-1] to presorting positions
Definition at line 109 of file linemixing.cc.
References N.
Member Data Documentation
dip
Vector Absorption::LineMixing::PopulationAndDipole::dip
Definition at line 49 of file linemixing.h.
pop
Vector Absorption::LineMixing::PopulationAndDipole::pop
Definition at line 48 of file linemixing.h.
The documentation for this struct was generated from the following files:
linemixing.h
linemixing.cc