ARTS: LineShape::SpeedDependentVoigt Struct Reference
LineShape::SpeedDependentVoigt Struct Reference
#include <lineshape.h>
Public Types
enum class CalcType : char {
Voigt , LowXandHighY , LowYandLowX , LowYandHighX ,
Full
}
Public Member Functions
SpeedDependentVoigt (Numeric F0_noshift, const Output &ls, Numeric GD_div_F0, Numeric dZ) noexcept
Complex dFdf () const noexcept
Complex dFdF0 () const noexcept
Complex dFdD0 (Numeric dD0dD0) const noexcept
Complex dFdG0 (Numeric dG0dG0) const noexcept
Complex dFdD2 (Numeric dD2dD2) const noexcept
Complex dFdG2 (Numeric dG2dG2) const noexcept
Complex dFdH (Numeric dZ) const noexcept
Complex dFdVMR (const Output &d) const noexcept
Complex dFdT (const Output &d, Numeric T) const noexcept
Complex operator() (Numeric f) noexcept
CalcType init (const Complex c2) const noexcept
void update_calcs () noexcept
void calc () noexcept
Static Public Member Functions
static constexpr Complex dFdETA (Numeric) noexcept
static constexpr Complex dFdFVC (Numeric) noexcept
static constexpr Complex dFdDV (Numeric) noexcept
Public Attributes
Complex F
Numeric mF0
Numeric invGD
Complex invc2
Complex dx
Complex x
Complex sqrty
CalcType calcs
Complex sq
Complex w1
Complex w2
Complex dw1
Complex dw2
Detailed Description
Definition at line 133 of file lineshape.h.
Member Enumeration Documentation
CalcType
enum LineShape::SpeedDependentVoigt::CalcType : char strong
Enumerator
Voigt
LowXandHighY
LowYandLowX
LowYandHighX
Full
Definition at line 134 of file lineshape.h.
Constructor & Destructor Documentation
SpeedDependentVoigt()
LineShape::SpeedDependentVoigt::SpeedDependentVoigt (Numeric F0_noshift, const Output & ls, Numeric GD_div_F0, Numeric dZ) noexcept
Definition at line 34 of file lineshape.cc.
Member Function Documentation
calc()
void LineShape::SpeedDependentVoigt::calc () noexcept
Definition at line 432 of file lineshape.cc.
References calcs, F, Full, sq, sqrt(), sqrty, w(), w1, w2, and x.
dFdD0()
Complex LineShape::SpeedDependentVoigt::dFdD0 (Numeric dD0dD0) const noexcept
Definition at line 89 of file lineshape.cc.
References Constant::pow2().
dFdD2()
Complex LineShape::SpeedDependentVoigt::dFdD2 (Numeric dD2dD2) const noexcept
Definition at line 138 of file lineshape.cc.
References Constant::pow2().
dFdDV()
static constexpr Complex LineShape::SpeedDependentVoigt::dFdDV (Numeric) inline static constexpr noexcept
Definition at line 171 of file lineshape.h.
dFdETA()
static constexpr Complex LineShape::SpeedDependentVoigt::dFdETA (Numeric) inline static constexpr noexcept
Definition at line 169 of file lineshape.h.
dFdf()
Complex LineShape::SpeedDependentVoigt::dFdf () const noexcept
Definition at line 44 of file lineshape.cc.
References calcs, dw1, dw2, Full, invc2, and invGD.
dFdF0()
Complex LineShape::SpeedDependentVoigt::dFdF0 () const noexcept
Definition at line 61 of file lineshape.cc.
References calcs, dw1, dw2, Full, invc2, invGD, mF0, Constant::pow2(), sq, w1, and w2.
dFdFVC()
static constexpr Complex LineShape::SpeedDependentVoigt::dFdFVC (Numeric) inline static constexpr noexcept
Definition at line 170 of file lineshape.h.
dFdG0()
Complex LineShape::SpeedDependentVoigt::dFdG0 (Numeric dG0dG0) const noexcept
Definition at line 120 of file lineshape.cc.
dFdG2()
Complex LineShape::SpeedDependentVoigt::dFdG2 (Numeric dG2dG2) const noexcept
Definition at line 183 of file lineshape.cc.
References dx, and Constant::pow2().
dFdH()
Complex LineShape::SpeedDependentVoigt::dFdH (Numeric dZ) const noexcept
Definition at line 214 of file lineshape.cc.
References Constant::pow2().
dFdT()
Complex LineShape::SpeedDependentVoigt::dFdT (const Output & d, Numeric T) const noexcept
Definition at line 304 of file lineshape.cc.
References Constant::pow2().
dFdVMR()
Complex LineShape::SpeedDependentVoigt::dFdVMR (const Output & d) const noexcept
Definition at line 245 of file lineshape.cc.
References d, and Constant::pow2().
init()
SpeedDependentVoigt::CalcType LineShape::SpeedDependentVoigt::init (const Complex c2) const noexcept
Definition at line 413 of file lineshape.cc.
References LineShape::abs_squared(), and ARTS::Var::x().
Referenced by update_calcs().
operator()()
Complex LineShape::SpeedDependentVoigt::operator() (Numeric f) noexcept
Definition at line 400 of file lineshape.cc.
References dx, imag_val(), and ARTS::Var::x().
update_calcs()
void LineShape::SpeedDependentVoigt::update_calcs () noexcept
Definition at line 427 of file lineshape.cc.
References calcs, init(), and Voigt.
Member Data Documentation
calcs
CalcType LineShape::SpeedDependentVoigt::calcs
Definition at line 150 of file lineshape.h.
Referenced by calc(), dFdf(), dFdF0(), and update_calcs().
dw1
Complex LineShape::SpeedDependentVoigt::dw1
Definition at line 154 of file lineshape.h.
Referenced by dFdf(), and dFdF0().
dw2
Complex LineShape::SpeedDependentVoigt::dw2
Definition at line 155 of file lineshape.h.
Referenced by dFdf(), and dFdF0().
dx
Complex LineShape::SpeedDependentVoigt::dx
Definition at line 147 of file lineshape.h.
F
Complex LineShape::SpeedDependentVoigt::F
Definition at line 142 of file lineshape.h.
Referenced by calc(), and LineShape::ComputeData::reset().
invc2
Complex LineShape::SpeedDependentVoigt::invc2
Definition at line 146 of file lineshape.h.
Referenced by dFdf(), and dFdF0().
invGD
Numeric LineShape::SpeedDependentVoigt::invGD
Definition at line 145 of file lineshape.h.
Referenced by dFdf(), and dFdF0().
mF0
Numeric LineShape::SpeedDependentVoigt::mF0
Definition at line 144 of file lineshape.h.
Referenced by dFdF0().
sq
Complex LineShape::SpeedDependentVoigt::sq
Definition at line 151 of file lineshape.h.
Referenced by calc(), and dFdF0().
sqrty
Complex LineShape::SpeedDependentVoigt::sqrty
Definition at line 149 of file lineshape.h.
Referenced by calc().
w1
Complex LineShape::SpeedDependentVoigt::w1
Definition at line 152 of file lineshape.h.
Referenced by calc(), and dFdF0().
w2
Complex LineShape::SpeedDependentVoigt::w2
Definition at line 153 of file lineshape.h.
Referenced by calc(), and dFdF0().
x
Complex LineShape::SpeedDependentVoigt::x
Definition at line 148 of file lineshape.h.
Referenced by calc().
The documentation for this struct was generated from the following files:
lineshape.h
lineshape.cc