ARTS: surface.h File Reference
surface.h File Reference
#include "complex.h"
#include "matpackIV.h"
#include "mystring.h"
#include "ppath.h"
Functions
Numeric calc_incang (ConstVectorView rte_los, ConstVectorView specular_los)
Calculates the incidence angle for a flat surface, based on rte_los and specular_los.
Index index_of_zsurface (const Numeric &z_surface, ConstVectorView z_profile)
Lccates the surface with respect to pressure levels.
void surface_calc (Matrix &iy, ConstTensor3View I, ConstMatrixView surface_los, ConstTensor4View surface_rmatrix, ConstMatrixView surface_emission)
Weights together downwelling radiation and surface emission.
void surface_specular_R_and_b (MatrixView surface_rmatrix, VectorView surface_emission, const Complex &Rv, const Complex &Rh, const Numeric &f, const Index &stokes_dim, const Numeric &surface_skin_t)
Sets up the surface reflection matrix and emission vector for the case of specular reflection.
void surface_props_check (const Index &atmosphere_dim, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &surface_props_data, const ArrayOfString &surface_props_names)
Peforms basic checks of surface_props_data and surface_props_names
void surface_props_interp (Vector &v, const String &vname, const Index &atmosphere_dim, const ArrayOfGridPos &gp_lat, const ArrayOfGridPos &gp_lon, const Matrix &itw, const Tensor3 &surface_props_data, const ArrayOfString &surface_props_names)
Peforms an interpolation of surface_props_data
void dsurface_check (const ArrayOfString &surface_props_names, const ArrayOfString &dsurface_names, const ArrayOfTensor4 dsurface_rmatrix_dx, const ArrayOfMatrix &dsurface_emission_dx)
Peforms basic checks of the dsurface variables.
Detailed Description
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2012-02-06
This file contains definitions of internal functions associated with the surface.
Definition in file surface.h.
Function Documentation
calc_incang()
Numeric calc_incang (ConstVectorView rte_los, ConstVectorView specular_los)
Calculates the incidence angle for a flat surface, based on rte_los and specular_los.
Returns
Incidence angle.
Parameters
[in] rte_los As the WSV with the same name.
[in] specular_los As the WSV with the same name.
Author
Patrick Eriksson
Date
2012-11-15
Definition at line 51 of file surface.cc.
References abs, ARTS::Var::rte_los(), and ARTS::Var::specular_los().
Referenced by surfaceFlatRefractiveIndex(), and surfaceTelsem().
dsurface_check()
void dsurface_check (const ArrayOfString & surface_props_names, const ArrayOfString & dsurface_names, const ArrayOfTensor4 dsurface_rmatrix_dx, const ArrayOfMatrix & dsurface_emission_dx)
Peforms basic checks of the dsurface variables.
No calculaions, just checks
Parameters
[in] surface_props_data As the WVS with the same name.
[in] surface_props_names As the WVS with the same name.
[in] dsurface_names As the WVS with the same name.
[in] dsurface_ratrix_dx As the WVS with the same name.
[in] dsurface_emission_dx As the WVS with the same name.
Author
Patrick Eriksson
Date
2018-09-01
Definition at line 203 of file surface.cc.
References ARTS_USER_ERROR_IF, ARTS::Var::dsurface_emission_dx(), ARTS::Var::dsurface_names(), ARTS::Var::dsurface_rmatrix_dx(), and ARTS::Var::surface_props_names().
Referenced by SurfaceBlackbody(), SurfaceDummy(), SurfaceFastem(), SurfaceFlatScalarReflectivity(), and SurfaceTessem().
index_of_zsurface()
Index index_of_zsurface (const Numeric & z_surface, ConstVectorView z_profile)
Lccates the surface with respect to pressure levels.
The function returns the index of the pressure level at or just below the surface.
Returns
The found index.
Parameters
[in] z_surface A surface value (probably a value from WSV z_surface)
[in] z_profile A profile of geometrical altitudes (probably a page of z_field)
Author
Patrick Eriksson
Date
2019-10-26
Definition at line 55 of file surface.cc.
References ARTS::Var::z_surface().
Referenced by spectral_radiance_fieldClearskyPlaneParallel().
surface_calc()
void surface_calc (Matrix & iy, ConstTensor3View I, ConstMatrixView surface_los, ConstTensor4View surface_rmatrix, ConstMatrixView surface_emission)
Weights together downwelling radiation and surface emission.
iy* must have correct size when function is called.
Parameters
[out] iy Radiation matrix, amtching the WSV with the same name.
[in] I Downwelling radiation, with dimensions (surface_los, f_grid, stokes_dim)
[in] surface_los As the WSV with the same name.
[in] surface_rmatrix As the WSV with the same name.
[in] surface_emission As the WSV with the same name.
Author
Patrick Eriksson
Date
2005-04-07
Definition at line 64 of file surface.cc.
References ARTS::Var::iy(), joker, mult(), ConstTensor3View::ncols(), ConstTensor3View::nrows(), ARTS::Var::stokes_dim(), ARTS::Var::surface_emission(), ARTS::Var::surface_los(), and ARTS::Var::surface_rmatrix().
Referenced by iySurfaceFastem(), iySurfaceRtpropAgenda(), and iySurfaceRtpropCalc().
surface_props_check()
void surface_props_check (const Index & atmosphere_dim, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & surface_props_data, const ArrayOfString & surface_props_names)
Peforms basic checks of surface_props_data and surface_props_names
No calculaions, just checks
Parameters
[in] atmosphere_dim As the WVS with the same name.
[in] lat_grid As the WVS with the same name.
[in] lon_grid As the WVS with the same name.
[in] surface_props_data As the WVS with the same name.
[in] surface_props_names As the WVS with the same name.
Author
Patrick Eriksson
Date
2018-09-01
Definition at line 140 of file surface.cc.
References ARTS_USER_ERROR_IF, ARTS::Var::atmosphere_dim(), ARTS::Var::lat_grid(), ARTS::Var::lon_grid(), Absorption::nelem(), ARTS::Var::surface_props_data(), and ARTS::Var::surface_props_names().
Referenced by SurfaceBlackbody(), SurfaceDummy(), SurfaceFastem(), SurfaceFlatScalarReflectivity(), and SurfaceTessem().
surface_props_interp()
void surface_props_interp (Vector & v, const String & vname, const Index & atmosphere_dim, const ArrayOfGridPos & gp_lat, const ArrayOfGridPos & gp_lon, const Matrix & itw, const Tensor3 & surface_props_data, const ArrayOfString & surface_props_names)
Peforms an interpolation of surface_props_data
The function assumes that the intrpolatin gives a single value. The vector v* must have lenght 1.
Parameters
[in] v Interpolated value
[in] vname Name of surface variable to interpolate
[in] atmosphere_dim As the WVS with the same name.
[in] gp_lat Pre-calculatd latitude grid positions
[in] gp_lon Pre-calculatd longitude grid positions
[in] itw Pre-calculatd interpolation weight
[in] surface_props_data As the WVS with the same name.
[in] surface_props_names As the WVS with the same name.
Author
Patrick Eriksson
Date
2018-09-01
Definition at line 174 of file surface.cc.
References ARTS_ASSERT, ARTS_USER_ERROR, ARTS::Var::atmosphere_dim(), interp_atmsurface_by_itw(), joker, ARTS::Var::surface_props_data(), ARTS::Var::surface_props_names(), and v.
Referenced by SurfaceBlackbody(), SurfaceFastem(), SurfaceFlatScalarReflectivity(), and SurfaceTessem().
surface_specular_R_and_b()
void surface_specular_R_and_b (MatrixView surface_rmatrix, VectorView surface_emission, const Complex & Rv, const Complex & Rh, const Numeric & f, const Index & stokes_dim, const Numeric & surface_skin_t)
Sets up the surface reflection matrix and emission vector for the case of specular reflection.
The function handles only one frequency at the time.
See further the surface chapter in the user guide.
Parameters
[out] surface_rmatrix As the WSV with the same name, but slice for one direction and one frequency.
[out] surface_emission As the WSV with the same name, but slice for one direction and one frequency.
[in] Rv Complex amplitude relection coefficient vertical polarisation.
[in] Rh Complex amplitude relection coefficient horisontal polarisation.
[in] f Frequency (a scalar).
[in] stokes_dim As the WSV with the same name.
[in] surface_skin_t As the WSV with the same name.
Author
Patrick Eriksson
Date
2004-09-24
Definition at line 89 of file surface.cc.
References a, abs, ARTS_ASSERT, b, c, conj(), d, imag(), planck(), pow(), real(), ARTS::Var::stokes_dim(), ARTS::Var::surface_emission(), ARTS::Var::surface_rmatrix(), and ARTS::Var::surface_skin_t().
Referenced by surfaceFlatRefractiveIndex().