ARTS: tessem.h File Reference
tessem.h File Reference
This file contains functions that are adapted from TESSEM code which is used to calculate surface emissivity.
#include <fstream>
#include "matpackI.h"
Classes
struct TessemNN
Functions
void tessem_read_ascii (std::ifstream &is, TessemNN &net)
void tessem_prop_nn (VectorView &ny, const TessemNN &net, ConstVectorView nx)
Detailed Description
This file contains functions that are adapted from TESSEM code which is used to calculate surface emissivity.
Definition in file tessem.h.
Function Documentation
tessem_prop_nn()
void tessem_prop_nn (VectorView & ny, const TessemNN & net, ConstVectorView nx)
Tessem emissivity calculation
When using the default neural network parameter files from the Tessem 2 distribution, the input Vector should contain 5 elements:
Frequency (10e9-700e9) in Hz
Theta (0-90) Incidence angle in degrees
Windspeed (0-25) at 10m in m/s. Higher wind speed can be used but without garantee
Surface skin temperature (270-310) in K
Salinity (0.0-0.04) in kg/kg
Parameters
[out] ny Calculated emissivity.
[in] net Neural network parameters.
[in] nx Input data.
Definition at line 87 of file tessem.cc.
References TessemNN::nb_inputs, TessemNN::nb_outputs, and ConstVectorView::nelem().
Referenced by surfaceTessem(), and TestTessem().
tessem_read_ascii()
void tessem_read_ascii (std::ifstream & is, TessemNN & net)
Read TESSEM2 neural network parameters
Parameters
[in,out] is Input file stream
[out] net Neural network parameters
Definition at line 41 of file tessem.cc.
References TessemNN::b1, TessemNN::b2, is, TessemNN::nb_cache, TessemNN::nb_inputs, TessemNN::nb_outputs, Vector::resize(), Matrix::resize(), TessemNN::w1, TessemNN::w2, TessemNN::x_max, TessemNN::x_min, TessemNN::y_max, and TessemNN::y_min.
Referenced by TessemNNReadAscii().