ARTS: test_complex.cc File Reference
test_complex.cc File Reference
Test the complex numbers.
#include <iostream>
#include "complex.h"
Functions
void test01 ()
void test02 ()
void test03 ()
int main ()
Detailed Description
Test the complex numbers.
Author
sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Sat Dec 14 19:42:25 2002
Definition in file test_complex.cc.
Function Documentation
main()
int main (void)
Definition at line 335 of file test_complex.cc.
References test03().
test01()
void test01 ()
Definition at line 31 of file test_complex.cc.
References a, abs, b, c, and d.
test02()
void test02 ()
Definition at line 112 of file test_complex.cc.
References a, abs2(), b, and c.
test03()
void test03 ()
Definition at line 165 of file test_complex.cc.
References imag(), joker, M, MapToEigen(), IGRF::r0, real(), and transpose().
Referenced by main().