ARTS: test_cia.cc File Reference
test_cia.cc File Reference
Test Collission Induced Absorption (CIA) functions.
#include "cia.h"
Functions
void test01 ()
int main ()
Detailed Description
Test Collission Induced Absorption (CIA) functions.
Author
sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
2012-11-30
Definition in file test_cia.cc.
Function Documentation
main()
int main (void)
Definition at line 53 of file test_cia.cc.
References test01().
test01()
void test01 ()
Definition at line 28 of file test_cia.cc.
References cia_interpolation(), GriddedField2::data, and GriddedField::set_grid().
Referenced by main().