ARTS: test_raw.cc File Reference
test_raw.cc File Reference
#include <autoarts.h>
#include "artstime.h"
#include "gui/plot.h"
#include "raw.h"
#include "test_utils.h"
#include <Faddeeva/Faddeeva.hh>
Classes
struct MockData
Functions
Numeric time_sign (const Time t)
Numeric time_srcs (const Time t)
MockData mock_data (const Vector &f, const Time &t, const Numeric f0, const Numeric g, const Numeric gd)
int main ()
Function Documentation
main()
int main (void)
Definition at line 52 of file test_raw.cc.
References F0, ARTS::Var::f_grid(), ARTS::init(), ARTS::Var::level0_data(), ARTS::Var::level0_time(), mock_data(), Absorption::nelem(), Time::seconds_into_day(), ARTS::Var::ArrayOfTime::value(), ARTS::Var::ArrayOfVector::value(), ARTS::Method::VectorSet(), ARTS::Var::ybatch(), ARTS::Method::ybatchColdAtmHotAtmCycle(), ARTS::Method::ybatchDoublingMeanFocus(), ARTS::Method::ybatchTimeAveraging(), and ARTS::Method::ybatchTroposphericCorrectionNaiveMedianForward().
mock_data()
MockData mock_data (const Vector & f, const Time & t, const Numeric f0, const Numeric g, const Numeric gd)
Definition at line 26 of file test_raw.cc.
References add_noise(), MockData::cold, MockData::hot, MockData::meas, ConstVectorView::nelem(), MockData::tc, MockData::th, time_sign(), and time_srcs().
Referenced by main().
time_sign()
Numeric time_sign (const Time t)
Definition at line 10 of file test_raw.cc.
References Time::Seconds().
Referenced by mock_data().
time_srcs()
Numeric time_srcs (const Time t)
Definition at line 14 of file test_raw.cc.
References Time::Seconds().
Referenced by mock_data().