ARTS: test_interpolation.cc File Reference
test_interpolation.cc File Reference
#include <cmath>
#include <iostream>
#include "array.h"
#include "auto_md.h"
#include "constants.h"
#include "interpolation.h"
#include "interpolation_lagrange.h"
#include "math_funcs.h"
#include "matpackVII.h"
#include "xml_io.h"
Functions
void test01 ()
void test02 (Index n)
void test03 (Index n)
void test04 ()
void test05 ()
void test06 ()
void test09 ()
void test11 ()
constexpr bool is_around (Numeric x, Numeric x0, Numeric e=1e-12)
void test12 ()
void test13 ()
void test14 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
void test25 ()
void test26 ()
void test27 ()
void test28 ()
int main ()
Function Documentation
is_around()
constexpr bool is_around (Numeric x, Numeric x0, Numeric e = 1e-12) constexpr
Definition at line 501 of file test_interpolation.cc.
Referenced by test12().
main()
int main (void)
Definition at line 1014 of file test_interpolation.cc.
References test09().
test01()
void test01 ()
Definition at line 30 of file test_interpolation.cc.
References gridpos(), interp(), interpweights(), joker, ConstTensor3View::ncols(), Array< base >::nelem(), and ConstVectorView::nelem().
test02()
void test02 (Index n)
Definition at line 168 of file test_interpolation.cc.
References a.
test03()
void test03 (Index n)
Definition at line 177 of file test_interpolation.cc.
References a.
test04()
void test04 ()
Definition at line 192 of file test_interpolation.cc.
References a, gridpos(), interp(), interpweights(), joker, ConstVectorView::nelem(), and ConstTensor3View::npages().
test05()
void test05 ()
Definition at line 248 of file test_interpolation.cc.
References gridpos(), interp(), interpweights(), Array< base >::nelem(), and ConstVectorView::nelem().
test06()
void test06 ()
Definition at line 283 of file test_interpolation.cc.
References gridpos(), interp(), interpweights(), joker, ConstTensor3View::ncols(), Array< base >::nelem(), and ConstVectorView::nelem().
test09()
void test09 ()
Definition at line 422 of file test_interpolation.cc.
References gridpos(), interp(), interpweights(), Interpolation::LagrangeVector(), Array< base >::nelem(), ConstVectorView::nelem(), Interpolation::reinterp(), and x.
Referenced by main().
test11()
void test11 ()
Definition at line 471 of file test_interpolation.cc.
References interpweights(), Interpolation::LagrangeVector(), N, nlinspace(), Interpolation::reinterp(), x0, and x1.
test12()
void test12 ()
Definition at line 505 of file test_interpolation.cc.
References interp(), interpweights(), is_around(), N, and x.
test13()
void test13 ()
Definition at line 550 of file test_interpolation.cc.
References dx, N, and x.
test14()
void test14 ()
Definition at line 615 of file test_interpolation.cc.
References Interpolation::dinterpweights(), interpweights(), Interpolation::reinterp(), and x.
test16()
void test16 ()
Definition at line 652 of file test_interpolation.cc.
References Interpolation::LagrangeVector(), and x.
test17()
void test17 ()
Definition at line 678 of file test_interpolation.cc.
References Interpolation::dinterpweights(), interp(), interpweights(), N, VectorNLinSpace(), verbosity, and x.
test18()
void test18 ()
Definition at line 703 of file test_interpolation.cc.
References Conversion::cosd(), Interpolation::dinterpweights(), interp(), interpweights(), N, Conversion::sind(), VectorNLinSpace(), verbosity, and x.
test19()
void test19 ()
Definition at line 727 of file test_interpolation.cc.
References Conversion::cosd(), Interpolation::dinterpweights(), interp(), interpweights(), N, Conversion::sind(), VectorNLinSpace(), verbosity, and x.
test20()
void test20 ()
Definition at line 752 of file test_interpolation.cc.
References Conversion::cosd(), Interpolation::dinterpweights(), interp(), interpweights(), N, Conversion::sind(), VectorNLinSpace(), verbosity, and x.
test21()
void test21 ()
Definition at line 777 of file test_interpolation.cc.
References Conversion::cosd(), Interpolation::dinterpweights(), interp(), interpweights(), N, Conversion::sind(), VectorNLinSpace(), verbosity, and x.
test22()
void test22 ()
Definition at line 802 of file test_interpolation.cc.
References Interpolation::dinterpweights(), interp(), interpweights(), N, VectorNLinSpace(), verbosity, and x.
test23()
void test23 ()
Definition at line 827 of file test_interpolation.cc.
References Conversion::cosd(), Interpolation::dinterpweights(), interp(), interpweights(), N, Conversion::sind(), VectorNLinSpace(), verbosity, and x.
test25()
void test25 ()
Definition at line 852 of file test_interpolation.cc.
References Interpolation::dinterpweights(), interp(), interpweights(), N, VectorNLinSpace(), verbosity, and x.
test26()
void test26 ()
Definition at line 866 of file test_interpolation.cc.
References Interpolation::cyclic_clamp(), Interpolation::dinterpweights(), interp(), interpweights(), N, Constant::pow2(), and x.
test27()
void test27 ()
Definition at line 953 of file test_interpolation.cc.
References a, and Jacobian::toString().
test28()
void test28 ()
Definition at line 964 of file test_interpolation.cc.
References Conversion::cosd(), Constant::pow2(), Constant::pow3(), Conversion::sind(), and VectorNLogSpace().