ARTS: test_isotope.cc File Reference
test_isotope.cc File Reference
#include "isotopologues.h"
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 3 of file test_isotope.cc.
References a, b, c, good_enum(), Species::is_predefined_model(), nonstd::isnan(), Species::isotopologue_ratiosInitFromBuiltin(), Species::Isotopologues, joker, and ARTS::Var::x().