ARTS: test_lineshape.cc File Reference
test_lineshape.cc File Reference
#include "absorption.h"
#include "artstime.h"
#include "lineshape.h"
#include "gui/plot.h"
Classes
struct InternalData
Functions
ENUMCLASS (ModificationInternal, char, None, T, f, H, F0, I0, SelfG0, SelfD0, SelfG2, SelfD2, SelfETA, SelfFVC, SelfY, SelfG, SelfDV, AirG0, AirD0, AirG2, AirD2, AirETA, AirFVC, AirY, AirG, AirDV, SelfVMR, AirVMR) template< ModificationInternal mod > LineShape
template<ModificationInternal mod, LineShape::Type ls_type>
InternalData line_model ()
template<LineShape::Type ls_type>
void test_ls ()
void test_norm ()
void test_lte_strength ()
void test_sparse ()
int main ()
Function Documentation
ENUMCLASS()
ENUMCLASS (ModificationInternal , char , None , T , f , H , F0 , I0 , SelfG0 , SelfD0 , SelfG2 , SelfD2 , SelfETA , SelfFVC , SelfY , SelfG , SelfDV , AirG0 , AirD0 , AirG2 , AirD2 , AirETA , AirFVC , AirY , AirG , AirDV , SelfVMR , AirVMR)
Definition at line 27 of file test_lineshape.cc.
line_model()
template<ModificationInternal mod, LineShape::Type ls_type> InternalData line_model ()
Definition at line 115 of file test_lineshape.cc.
main()
int main (void)
Definition at line 708 of file test_lineshape.cc.
References define_species_data(), define_species_map(), make_wigner_ready(), and test_sparse().
test_ls()
template<LineShape::Type ls_type> void test_ls ()
Definition at line 150 of file test_lineshape.cc.
References QuantumIdentifier::ALL, LineShape::compute(), LineShape::ComputeData::dF, LineShape::ComputeData::dN, LineShape::ComputeData::F, ARTS::Var::f_grid(), fillSpeciesAuxDataWithPartitionFunctionsFromSpeciesData(), ARTS::Species::H, imag(), ARTS::Var::jacobian_quantities(), joker, M, Jacobian::MagneticMagnitude, max, mean(), median(), LineShape::ComputeData::N, N, Options::None, ARTS::Var::partition_functions(), Zeeman::Pi, real(), Zeeman::start(), Jacobian::Temperature, and Jacobian::WindMagnitude.
test_lte_strength()
void test_lte_strength ()
Definition at line 600 of file test_lineshape.cc.
References fillSpeciesAuxDataWithPartitionFunctionsFromSpeciesData(), and ARTS::Var::partition_functions().
test_norm()
void test_norm ()
Definition at line 495 of file test_lineshape.cc.
References ARTS::Var::f_grid(), ARTS::Species::H, max, min, and N.
test_sparse()
void test_sparse ()
Definition at line 628 of file test_lineshape.cc.
References LineShape::compute(), fillSpeciesAuxDataWithPartitionFunctionsFromSpeciesData(), ARTS::Species::H, LineShape::linear_sparse_f_grid(), ConstVectorView::nelem(), Options::None, ARTS::Var::partition_functions(), Zeeman::Pi, Options::QuadraticIndependent, and LineShape::triple_sparse_f_grid().
Referenced by main().