ARTS: test_readpp.cc File Reference
test_readpp.cc File Reference
#include <cstdlib>
#include <iostream>
#include "bifstream.h"
#include "matpackI.h"
Typedefs
typedef long PPHeader[65]
Functions
void readppheader (bifstream &is, PPHeader &pph)
void readppdata (bifstream &is, PPHeader &pph, Vector &v)
int main (int argc, char *argv[])
Typedef Documentation
PPHeader
typedef long PPHeader[65]
Definition at line 25 of file test_readpp.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 52 of file test_readpp.cc.
References binio::BigEndian, and binio::setFlag().
readppdata()
void readppdata (bifstream & is, PPHeader & pph, Vector & v)
Definition at line 39 of file test_readpp.cc.
References binio::error(), binistream::readFloat(), Vector::resize(), and binio::Single.
readppheader()
void readppheader (bifstream & is, PPHeader & pph)
Definition at line 30 of file test_readpp.cc.
References binio::error(), and binistream::readInt().