ARTS: test_telsem.cc File Reference
test_telsem.cc File Reference
Tests for TELSEM2 interface.
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include "arts.h"
#include "telsem.h"
Functions
Numeric test_telsem_interpolate (std::string atlas_file, std::string result_path, Numeric resolution, Numeric theta, Vector frequencies)
Test reading of TELSEM emissivity interpolation.
Numeric test_telsem_read (String atlas_file, String result_path, Numeric resolution)
Test reading of TELSEM emissivities.
int main (int argc, const char **argv)
Detailed Description
Tests for TELSEM2 interface.
Author
Simon Pfreundschuh simon.nosp@m..pfr.nosp@m.eunds.nosp@m.chuh.nosp@m.@chal.nosp@m.mers.nosp@m..se
Date
Mon February 12 12:34:56 2018
Definition in file test_telsem.cc.
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 203 of file test_telsem.cc.
References test_telsem_interpolate(), and test_telsem_read().
test_telsem_interpolate()
Numeric test_telsem_interpolate (std::string atlas_file, std::string result_path, Numeric resolution, Numeric theta, Vector frequencies)
Test reading of TELSEM emissivity interpolation.
This function tests the interpolation of TELSEM emissivities by comparison with the results from the test that is included in the fortran module.
Parameters
atlas_file The path to the atlas file which was used in the FORTRAN module tests
result_path The folder containing the results of the FORTRAN module tests
resolution The resolution to use for the lat/lon map.
theta The incidence angle to which to interpolate the frequencies.
frequencies The frequencies [GHz] (!!!) for which to interpolate the emissivities
Definition at line 49 of file test_telsem.cc.
References TelsemAtlas::calc_cellnum(), and ConstVectorView::nelem().
Referenced by main().
test_telsem_read()
Numeric test_telsem_read (String atlas_file, String result_path, Numeric resolution)
Test reading of TELSEM emissivities.
This function tests the reading of the telsem atlas by creating a lat/lon map of emissivities in the atlas and comparing with the results from the test that is included in the fortran module.
Parameters
atlas_file The path to the atlas file which was used in the FORTRAN module tests
result_path The folder containing the results of the FORTRAN module tests
resolution The resolution used to generate the lat/lon map.
Definition at line 139 of file test_telsem.cc.
References TelsemAtlas::calc_cellnum().
Referenced by main().