ARTS: test_tensor.cc File Reference
test_tensor.cc File Reference
#include <cmath>
#include <iostream>
#include "array.h"
#include "matpackVII.h"
Functions
Tensor4 fill_tensor4 (Index b, Index p, Index r, Index c, Index start=1)
Tensor5 fill_tensor5 (Index s, Index b, Index p, Index r, Index c, Index start=1)
void test1 ()
void test2 ()
void test3 ()
void test4 ()
void test5 ()
void fill_tensor6 (Tensor6 &x, Index v, Index s, Index b, Index p, Index r, Index c)
void test6 ()
void fill_tensor7 (Tensor7 &x, Index l, Index v, Index s, Index b, Index p, Index r, Index c)
void test7 ()
void test8 ()
void test9 ()
int main ()
Function Documentation
fill_tensor4()
Tensor4 fill_tensor4 (Index b, Index p, Index r, Index c, Index start = 1)
Definition at line 34 of file test_tensor.cc.
Referenced by test1(), and test2().
fill_tensor5()
Tensor5 fill_tensor5 (Index s, Index b, Index p, Index r, Index c, Index start = 1)
Definition at line 47 of file test_tensor.cc.
Referenced by test4(), and test5().
fill_tensor6()
void fill_tensor6 (Tensor6 & x, Index v, Index s, Index b, Index p, Index r, Index c)
Definition at line 190 of file test_tensor.cc.
Referenced by test6().
fill_tensor7()
void fill_tensor7 (Tensor7 & x, Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Definition at line 237 of file test_tensor.cc.
Referenced by test7(), and test8().
main()
int main (void)
Definition at line 572 of file test_tensor.cc.
References test9().
test1()
void test1 ()
Definition at line 66 of file test_tensor.cc.
References fill_tensor4(), joker, max, min, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
test2()
void test2 ()
Definition at line 99 of file test_tensor.cc.
References fill_tensor4(), sqrt(), and transform().
test3()
void test3 ()
Definition at line 110 of file test_tensor.cc.
test4()
void test4 ()
Definition at line 125 of file test_tensor.cc.
References fill_tensor5(), joker, max, min, ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
test5()
void test5 ()
Definition at line 172 of file test_tensor.cc.
References fill_tensor5().
test6()
void test6 ()
Definition at line 211 of file test_tensor.cc.
References fill_tensor6(), joker, ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
test7()
void test7 ()
Definition at line 259 of file test_tensor.cc.
References fill_tensor7(), joker, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
test8()
void test8 ()
Definition at line 284 of file test_tensor.cc.
References fill_tensor7().
test9()
void test9 ()
Definition at line 427 of file test_tensor.cc.
Referenced by main().