ARTS: test_cpp_api.cc File Reference
test_cpp_api.cc File Reference
#include <autoarts.h>
Namespaces
ARTS
ARTS::Agenda
ARTS::Continua
Functions
Workspace & ARTS::Agenda::iy_main_agenda_emission (Workspace &ws)
Workspace & ARTS::Agenda::iy_main_agenda_transmission (Workspace &ws)
Workspace & ARTS::Agenda::iy_space_agenda_cosmic_background (Workspace &ws)
Workspace & ARTS::Agenda::iy_surface_agenda_use_surface_property (Workspace &ws)
Workspace & ARTS::Agenda::ppath_agenda_follow_sensor_los (Workspace &ws)
Workspace & ARTS::Agenda::ppath_agenda_plane_parallel (Workspace &ws)
Workspace & ARTS::Agenda::ppath_step_agenda_geometric_path (Workspace &ws)
Workspace & ARTS::Agenda::ppath_step_agenda_refracted_path (Workspace &ws)
Workspace & ARTS::Agenda::propmat_clearsky_agenda_on_the_fly (Workspace &ws)
Workspace & ARTS::Agenda::propmat_clearsky_agenda_on_the_fly_zeeman (Workspace &ws)
Workspace & ARTS::Agenda::abs_xsec_agenda_standard (Workspace &ws)
Workspace & ARTS::Agenda::abs_xsec_agenda_standard_with_cia (Workspace &ws)
Workspace & ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface (Workspace &ws)
Workspace & ARTS::Agenda::surface_rtprop_agenda_blackbody_from_atmosphere (Workspace &ws)
Workspace & ARTS::Agenda::geo_pos_agenda_empty (Workspace &ws)
Workspace & ARTS::Agenda::water_p_eq_agenda_default (Workspace &ws)
Workspace & ARTS::Continua::init (Workspace &ws)
Workspace & ARTS::Continua::addH2OPWR98 (Workspace &ws)
Workspace & ARTS::Continua::addO2PWR98 (Workspace &ws)
int main ()
Function Documentation
main()
int main (void)
Definition at line 152 of file test_cpp_api.cc.
References abs_speciesSet(), ARTS::Agenda::abs_xsec_agenda_standard(), ARTS::Continua::addH2OPWR98(), ARTS::Continua::addO2PWR98(), ARTS::Agenda::geo_pos_agenda_empty(), ARTS::Continua::init(), isotopologue_ratiosInitFromBuiltin(), ARTS::Agenda::iy_main_agenda_emission(), ARTS::Agenda::iy_space_agenda_cosmic_background(), ARTS::Agenda::iy_surface_agenda_use_surface_property(), jacobianOff(), Absorption::nelem(), nlteOff(), partition_functionsInitFromBuiltin(), ARTS::Agenda::ppath_agenda_follow_sensor_los(), ARTS::Agenda::ppath_step_agenda_geometric_path(), ARTS::Agenda::propmat_clearsky_agenda_on_the_fly(), ARTS::Agenda::surface_rtprop_agenda_blackbody_from_surface(), Touch(), VectorNLogSpace(), and ARTS::Agenda::water_p_eq_agenda_default().