ARTS: test_omp.cc File Reference
test_omp.cc File Reference
#include <iostream>
#include "arts_omp.h"
#include "matpackIV.h"
#include "rte.h"
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 23 of file test_omp.cc.
References ext2trans(), ARTS::Var::ext_mat(), joker, mult(), and ARTS::Var::stokes_dim().