ARTS: test_propagationmatrix.cc File Reference
test_propagationmatrix.cc File Reference
Test Propagation Matrix Internal Partial Derivatives and PropagationMatrix.
#include <random>
#include "absorption.h"
#include "arts.h"
#include "global_data.h"
#include "lineshapemodel.h"
#include "linefunctions.h"
#include "linescaling.h"
#include "transmissionmatrix.h"
#include "zeeman.h"
#include "zeemandata.h"
#include <Faddeeva/Faddeeva.hh>
#include "legacy_continua.h"
#include "predefined_absorption_models.h"
#include "wigner_functions.h"
#include "linemixing_hitran.h"
#include <auto_md.h>
Functions
void test_matrix_buildup ()
void test_transmissionmatrix ()
void test_r_deriv_propagationmatrix ()
void test_transmat_from_propmat ()
void test_transmat_to_cumulativetransmat ()
void test_sinc_likes_0limit ()
void test_zeeman ()
constexpr bool test_quantum_numbers (const QuantumNumbers qns, const Index i)
void test_quantum ()
void test_mpm20 ()
void test_hitran2017 (bool newtest=true)
int main (int n, char **argc)
Detailed Description
Test Propagation Matrix Internal Partial Derivatives and PropagationMatrix.
Author
ric.l.nosp@m.arss.nosp@m.on@gm.nosp@m.ail..nosp@m.com
Date
2015-10-20
Definition in file test_propagationmatrix.cc.
Function Documentation
main()
int main (int n, char ** argc)
Definition at line 643 of file test_propagationmatrix.cc.
References test_hitran2017().
test_hitran2017()
void test_hitran2017 (bool newtest = true)
Definition at line 583 of file test_propagationmatrix.cc.
References Conversion::atm2pa(), lm_hitran_2017::compute(), define_species_data(), define_species_map(), ARTS::Var::f_grid(), lm_hitran_2017::FullW, Conversion::kaycm2freq(), Conversion::kaycm_per_cmsquared2hz_per_msquared(), make_wigner_ready(), lm_hitran_2017::NoneRosenkranz, lm_hitran_2017::NoneVP, ARTS::Var::partition_functions(), partition_functionsInitFromBuiltin(), lm_hitran_2017::read(), lm_hitran_2017::SDRosenkranz, lm_hitran_2017::SDVP, lm_hitran_2017::SDVP_Y, Hitran::type, LineShape::vmrs(), lm_hitran_2017::VP, lm_hitran_2017::VP_W, and lm_hitran_2017::VP_Y.
Referenced by main().
test_matrix_buildup()
void test_matrix_buildup ()
Definition at line 44 of file test_propagationmatrix.cc.
References a, b, b2, c, d, u, v, and w().
test_mpm20()
void test_mpm20 ()
Definition at line 535 of file test_propagationmatrix.cc.
References define_species_data(), define_species_map(), Absorption::PredefinedModel::makarov2020_o2_lines_mpm(), nlinspace(), PWR93O2AbsModel(), Jacobian::Temperature, and Jacobian::WindU.
test_quantum()
void test_quantum ()
Definition at line 528 of file test_propagationmatrix.cc.
References test_quantum_numbers().
test_quantum_numbers()
constexpr bool test_quantum_numbers (const QuantumNumbers qns, const Index i) constexpr
Definition at line 523 of file test_propagationmatrix.cc.
Referenced by test_quantum().
test_r_deriv_propagationmatrix()
void test_r_deriv_propagationmatrix ()
Definition at line 183 of file test_propagationmatrix.cc.
References a, ARTS::Var::x(), x1, and x2.
test_sinc_likes_0limit()
void test_sinc_likes_0limit ()
Definition at line 419 of file test_propagationmatrix.cc.
References Zeeman::end(), and Zeeman::start().
test_transmat_from_propmat()
void test_transmat_from_propmat ()
Definition at line 275 of file test_propagationmatrix.cc.
References a, b, c, d, stepwise_transmission(), test1(), test2(), test3(), test4(), u, v, and w().
test_transmat_to_cumulativetransmat()
void test_transmat_to_cumulativetransmat ()
Definition at line 369 of file test_propagationmatrix.cc.
test_transmissionmatrix()
void test_transmissionmatrix ()
Definition at line 142 of file test_propagationmatrix.cc.
References a, and b.
test_zeeman()
void test_zeeman ()
Definition at line 447 of file test_propagationmatrix.cc.
References CaseB, define_species_data(), define_species_map(), Zeeman::GetAdvancedModel(), Zeeman::GetSimpleModel(), Zeeman::Model::gl(), N, and QuantumNumbers::Set().