ARTS: wigner_functions.h File Reference
wigner_functions.h File Reference
Wigner symbol interactions.
#include <wigner/wigxjpf/inc/wigxjpf.h>
#include "rational.h"
Macros
#define DO_FAST_WIGNER 0
Functions
std::pair< Rational, Rational > wigner_limits (std::pair< Rational, Rational > a, std::pair< Rational, Rational > b)
template<Index pos>
constexpr std::pair< Rational, Rational > wigner3j_limits ([[maybe_unused]] const Rational a=0, [[maybe_unused]] const Rational b=0, [[maybe_unused]] const Rational c=0, [[maybe_unused]] const Rational d=0, [[maybe_unused]] const Rational e=0)
Numeric wigner3j (const Rational j1, const Rational j2, const Rational j3, const Rational m1, const Rational m2, const Rational m3)
Wigner 3J symbol.
Numeric wigner6j (const Rational j1, const Rational j2, const Rational j3, const Rational l1, const Rational l2, const Rational l3)
Wigner 6J symbol.
Index make_wigner_ready (int largest, int fastest, int size)
Ready Wigner.
bool is_wigner_ready (int j)
Tells if the function can deal with the input integer.
bool is_wigner3_ready (const Rational &J)
Tells if the function is ready for Wigner 3J calculations.
bool is_wigner6_ready (const Rational &J)
Tells if the function is ready for Wigner 6J calculations.
Detailed Description
Wigner symbol interactions.
Author
Richard Larsson
Date
2013-06-19
Definition in file wigner_functions.h.
Macro Definition Documentation
DO_FAST_WIGNER
#define DO_FAST_WIGNER 0
Definition at line 37 of file wigner_functions.h.
Function Documentation
is_wigner3_ready()
bool is_wigner3_ready (const Rational & J)
Tells if the function is ready for Wigner 3J calculations.
Parameters
[in] J Largest input into a Wigner 3J function call
Returns
true If is_wigner_ready(3J + 1) does
false Otherwise
Definition at line 144 of file wigner_functions.cc.
References is_wigner_ready(), and Rational::toInt().
is_wigner6_ready()
bool is_wigner6_ready (const Rational & J)
Tells if the function is ready for Wigner 6J calculations.
Parameters
[in] J Largest input into a Wigner 6J function call
Returns
true If is_wigner_ready(4J + 1)
false Otherwise
Definition at line 150 of file wigner_functions.cc.
References is_wigner_ready(), and Rational::toInt().
is_wigner_ready()
bool is_wigner_ready (int j)
Tells if the function can deal with the input integer.
Parameters
[in] j
Returns
true If j is less than max allowed j
false Otherwise
Definition at line 138 of file wigner_functions.cc.
Referenced by is_wigner3_ready(), and is_wigner6_ready().
make_wigner_ready()
Index make_wigner_ready (int largest, int fastest, int size)
Ready Wigner.
Parameters
[in] largest
[in] fastest
[in] size [3 or 6]
Returns
largest if successful
wigner3j()
Numeric wigner3j (const Rational j1, const Rational j2, const Rational j3, const Rational m1, const Rational m2, const Rational m3)
Wigner 3J symbol.
Run wigxjpf wig3jj for Rational symbol
/ \
j1 j2 j3
m1 m2 m3
\ /
See for definition: http://dlmf.nist.gov/34.2
Parameters
[in] j1 as above
[in] j2 as above
[in] j3 as above
[in] m1 as above
[in] m2 as above
[in] m3 as above
Returns
Numeric Symbol value
Definition at line 40 of file wigner_functions.cc.
References a, b, c, and d.
Referenced by Zeeman::Model::Strength().
wigner3j_limits()
template<Index pos> constexpr std::pair<Rational, Rational> wigner3j_limits ([[maybe_unused] ] const Rational a = 0, [[maybe_unused] ] const Rational b = 0, [[maybe_unused] ] const Rational c = 0, [[maybe_unused] ] const Rational d = 0, [[maybe_unused] ] const Rational e = 0) constexpr
Return the limits where a wigner3j symbol can be non-zero
The values a-e are as in a call to wigner3j with pos determining the offset. The output is the range of valid values at the offset position given the relevant triangle equaility |x - y| <= z <= x + y and that the m1 + m2 = -m3 condition for the lower row values
Positional information: pos == 1: wigner3j(X, a, b, c, d, e): b <= X + a -> X <= b - a, and |X - a| <= b -> a - b <= X <= a + b pos == 2: wigner3j(a, X, b, c, d, e): b <= a + X -> X <= b - a, and |a - X| <= b -> a + b <= X <= a - b pos == 3: wigner3j(a, b, X, c, d, e): |a - b| <= X <= a + b -> X <= b - a pos == 4: wigner3j(a, b, c, X, d, e): -|a| <= X <= |a|, and X + d = - e -> X = - e - d pos == 5: wigner3j(a, b, c, d, X, e): -|b| <= X <= |b|, and d + X = - e -> X = - e - d pos == 6: wigner3j(a, b, c, d, e, X): -|c| <= X <= |c|, and d + e = - X -> X = - e - d
If there is no valid range, the function returns {RATIONAL_UNDEFINED, RATIONAL_UNDEFINED}
Parameters
[in] pos Position of value
[in] a An input
[in] b An input
[in] c An input
[in] d An input
[in] e An input
Returns
A valid range where both start and end are valid, or invalid numbers
Definition at line 94 of file wigner_functions.h.
wigner6j()
Numeric wigner6j (const Rational j1, const Rational j2, const Rational j3, const Rational l1, const Rational l2, const Rational l3)
Wigner 6J symbol.
Run wigxjpf wig6jj for Rational symbol
/ \ | j1 j2 j3 | < > | l1 l2 l3 | \ /
See for definition: http://dlmf.nist.gov/34.4
Parameters
[in] j1 as above
[in] j2 as above
[in] j3 as above
[in] l1 as above
[in] l2 as above
[in] l3 as above
Returns
Numeric Symbol value
Definition at line 65 of file wigner_functions.cc.
References a, b, c, and d.
Referenced by Absorption::reduced_magnetic_quadrapole().
wigner_limits()
std::pair<Rational, Rational> wigner_limits (std::pair< Rational, Rational > a, std::pair< Rational, Rational > b)
Refine limits from multiple inputs
Parameters
[in] a A limit
[in] a Another limit
Returns
[low, high] for valid ranges of numbers or two undefined rationals
Definition at line 89 of file wigner_functions.cc.
References a, b, max, min, and RATIONAL_UNDEFINED.