ARTS: workspace_ng.h File Reference
workspace_ng.h File Reference
This file contains the Workspace class.
#include <map>
#include <stack>
#include "array.h"
#include "wsv_aux.h"
Classes
class Workspace
Workspace class.
struct Workspace::WsvStruct
Functions
template<typename OutputStream >
void PrintWsvName (OutputStream &outstream, Index i)
Print WSV name to output stream.
template<typename OutputStream , typename Container >
void PrintWsvNames (OutputStream &outstream, const Container &container)
Print list of WSV names to output stream.
Detailed Description
This file contains the Workspace class.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2004-11-05
Definition in file workspace_ng.h.
Function Documentation
PrintWsvName()
template<typename OutputStream > void PrintWsvName (OutputStream & outstream, Index i)
Print WSV name to output stream.
Looks up the name of the WSV with index i and prints it to the given output stream.
Parameters
[in,out] outstream OutputStream
[in] i Index of WSV
Definition at line 180 of file workspace_ng.h.
References Workspace::wsv_data.
Referenced by PrintWorkspace(), and PrintWsvNames().
PrintWsvNames()
template<typename OutputStream , typename Container > void PrintWsvNames (OutputStream & outstream, const Container & container)
Print list of WSV names to output stream.
Runs through the list of WSV indexes and print all names to the given output stream. The list of indexes can be any STL container such as Array, vector...
Parameters
outstream OutputStream
container List of WSV indexes
Definition at line 193 of file workspace_ng.h.
References PrintWsvName().
Referenced by Agenda::set_outputs_to_push_and_dup().