ARTS: workspace.cc File Reference
workspace.cc File Reference
Definition of function wsv_data.
#include "workspace_ng.h"
Macros
#define NAME(x) x
#define DESCRIPTION(x) x
#define GROUP(x) x
Functions
Index get_wsv_id (const String &name)
Get index of WSV.
Index get_wsv_id (const char *name)
Get index of WSV.
Detailed Description
Definition of function wsv_data.
This file contains the function define_wsv_data, which sets the WSV group names and the lookup data for the WSVs. You have to edit this function whenever you add a new workspace variable.
Author
Stefan Buehler
Date
2000-06-10
Definition in file workspace.cc.
Macro Definition Documentation
DESCRIPTION
#define DESCRIPTION (x) x
Definition at line 36 of file workspace.cc.
GROUP
#define GROUP (x) x
Definition at line 37 of file workspace.cc.
NAME
#define NAME (x) x
Definition at line 35 of file workspace.cc.
Function Documentation
get_wsv_id() [1/2]
Index get_wsv_id (const char * name)
Get index of WSV.
Returns the index the Workspace of the given WSV.
Convenience function which can be called from within the debugger because it takes a plain char pointer instead of a String object as input.
Parameters
[in] name WSV name
Returns
Index in Workspace
Author
Oliver Lemke
Definition at line 5801 of file workspace.cc.
References get_wsv_id().
Referenced by InteractiveWorkspace::execute_workspace_method().
get_wsv_id() [2/2]
Index get_wsv_id (const String & name)
Get index of WSV.
Returns the index the Workspace of the given WSV.
Parameters
[in] name WSV name
Returns
Index in Workspace
Author
Oliver Lemke
Definition at line 5781 of file workspace.cc.
References Zeeman::end(), and Workspace::WsvMap.
Referenced by AgRecord::AgRecord(), Arts2(), Agenda::execute(), get_wsv_id(), main(), and MdRecord::MdRecord().