ARTS: workspace_memory_handler.cc File Reference
workspace_memory_handler.cc File Reference
Defines global workspace_handler_objects and its dispatch functions.
#include "workspace_memory_handler.h"
#include <iostream>
#include "matpackII.h"
#include "m_general.h"
#include "supergeneric.h"
#include "artstime.h"
#include "ppath.h"
#include "gas_abs_lookup.h"
#include "linemixing_hitran.h"
#include "optproperties.h"
#include "gridded_fields.h"
#include "jacobian.h"
#include "agenda_class.h"
#include "mc_interp.h"
#include "mc_antenna.h"
#include "cia.h"
#include "propagationmatrix.h"
#include "transmissionmatrix.h"
#include "covariance_matrix.h"
#include "telsem.h"
#include "tessem.h"
#include "hitran_xsec.h"
#include "absorptionlines.h"
Functions
void * allocate_wsvg_AbsorptionLines ()
void deallocate_wsvg_AbsorptionLines (void *vp)
void * duplicate_wsvg_AbsorptionLines (void *vp)
void * allocate_wsvg_Agenda ()
void deallocate_wsvg_Agenda (void *vp)
void * duplicate_wsvg_Agenda (void *vp)
void * allocate_wsvg_Any ()
void deallocate_wsvg_Any (void *vp)
void * duplicate_wsvg_Any (void *vp)
void * allocate_wsvg_ArrayOfAbsorptionLines ()
void deallocate_wsvg_ArrayOfAbsorptionLines (void *vp)
void * duplicate_wsvg_ArrayOfAbsorptionLines (void *vp)
void * allocate_wsvg_ArrayOfArrayOfAbsorptionLines ()
void deallocate_wsvg_ArrayOfArrayOfAbsorptionLines (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfAbsorptionLines (void *vp)
void * allocate_wsvg_ArrayOfAgenda ()
void deallocate_wsvg_ArrayOfAgenda (void *vp)
void * duplicate_wsvg_ArrayOfAgenda (void *vp)
void * allocate_wsvg_ArrayOfArrayOfGriddedField1 ()
void deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
void * allocate_wsvg_ArrayOfArrayOfGriddedField2 ()
void deallocate_wsvg_ArrayOfArrayOfGriddedField2 (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfGriddedField2 (void *vp)
void * allocate_wsvg_ArrayOfArrayOfGriddedField3 ()
void deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
void * allocate_wsvg_ArrayOfArrayOfIndex ()
void deallocate_wsvg_ArrayOfArrayOfIndex (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfIndex (void *vp)
void * allocate_wsvg_ArrayOfArrayOfMatrix ()
void deallocate_wsvg_ArrayOfArrayOfMatrix (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfMatrix (void *vp)
void * allocate_wsvg_ArrayOfPpath ()
void deallocate_wsvg_ArrayOfPpath (void *vp)
void * duplicate_wsvg_ArrayOfPpath (void *vp)
void * allocate_wsvg_ArrayOfArrayOfPropagationMatrix ()
void deallocate_wsvg_ArrayOfArrayOfPropagationMatrix (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfPropagationMatrix (void *vp)
void * allocate_wsvg_ArrayOfArrayOfRadiationVector ()
void deallocate_wsvg_ArrayOfArrayOfRadiationVector (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfRadiationVector (void *vp)
void * allocate_wsvg_ArrayOfArrayOfScatteringMetaData ()
void deallocate_wsvg_ArrayOfArrayOfScatteringMetaData (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfScatteringMetaData (void *vp)
void * allocate_wsvg_ArrayOfArrayOfSingleScatteringData ()
void deallocate_wsvg_ArrayOfArrayOfSingleScatteringData (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfSingleScatteringData (void *vp)
void * allocate_wsvg_ArrayOfArrayOfSpeciesTag ()
void deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
void * allocate_wsvg_ArrayOfArrayOfStokesVector ()
void deallocate_wsvg_ArrayOfArrayOfStokesVector (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfStokesVector (void *vp)
void * allocate_wsvg_ArrayOfArrayOfString ()
void deallocate_wsvg_ArrayOfArrayOfString (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfString (void *vp)
void * allocate_wsvg_ArrayOfArrayOfTensor3 ()
void deallocate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
void * allocate_wsvg_ArrayOfArrayOfTensor6 ()
void deallocate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
void * allocate_wsvg_ArrayOfArrayOfTime ()
void deallocate_wsvg_ArrayOfArrayOfTime (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfTime (void *vp)
void * allocate_wsvg_ArrayOfArrayOfTransmissionMatrix ()
void deallocate_wsvg_ArrayOfArrayOfTransmissionMatrix (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfTransmissionMatrix (void *vp)
void * allocate_wsvg_ArrayOfArrayOfVector ()
void deallocate_wsvg_ArrayOfArrayOfVector (void *vp)
void * duplicate_wsvg_ArrayOfArrayOfVector (void *vp)
void * allocate_wsvg_ArrayOfCIARecord ()
void deallocate_wsvg_ArrayOfCIARecord (void *vp)
void * duplicate_wsvg_ArrayOfCIARecord (void *vp)
void * allocate_wsvg_ArrayOfGriddedField1 ()
void deallocate_wsvg_ArrayOfGriddedField1 (void *vp)
void * duplicate_wsvg_ArrayOfGriddedField1 (void *vp)
void * allocate_wsvg_ArrayOfGriddedField2 ()
void deallocate_wsvg_ArrayOfGriddedField2 (void *vp)
void * duplicate_wsvg_ArrayOfGriddedField2 (void *vp)
void * allocate_wsvg_ArrayOfGriddedField3 ()
void deallocate_wsvg_ArrayOfGriddedField3 (void *vp)
void * duplicate_wsvg_ArrayOfGriddedField3 (void *vp)
void * allocate_wsvg_ArrayOfGriddedField4 ()
void deallocate_wsvg_ArrayOfGriddedField4 (void *vp)
void * duplicate_wsvg_ArrayOfGriddedField4 (void *vp)
void * allocate_wsvg_ArrayOfIndex ()
void deallocate_wsvg_ArrayOfIndex (void *vp)
void * duplicate_wsvg_ArrayOfIndex (void *vp)
void * allocate_wsvg_ArrayOfJacobianTarget ()
void deallocate_wsvg_ArrayOfJacobianTarget (void *vp)
void * duplicate_wsvg_ArrayOfJacobianTarget (void *vp)
void * allocate_wsvg_ArrayOfMatrix ()
void deallocate_wsvg_ArrayOfMatrix (void *vp)
void * duplicate_wsvg_ArrayOfMatrix (void *vp)
void * allocate_wsvg_ArrayOfPropagationMatrix ()
void deallocate_wsvg_ArrayOfPropagationMatrix (void *vp)
void * duplicate_wsvg_ArrayOfPropagationMatrix (void *vp)
void * allocate_wsvg_ArrayOfQuantumIdentifier ()
void deallocate_wsvg_ArrayOfQuantumIdentifier (void *vp)
void * duplicate_wsvg_ArrayOfQuantumIdentifier (void *vp)
void * allocate_wsvg_ArrayOfRadiationVector ()
void deallocate_wsvg_ArrayOfRadiationVector (void *vp)
void * duplicate_wsvg_ArrayOfRadiationVector (void *vp)
void * allocate_wsvg_ArrayOfRetrievalQuantity ()
void deallocate_wsvg_ArrayOfRetrievalQuantity (void *vp)
void * duplicate_wsvg_ArrayOfRetrievalQuantity (void *vp)
void * allocate_wsvg_ArrayOfScatteringMetaData ()
void deallocate_wsvg_ArrayOfScatteringMetaData (void *vp)
void * duplicate_wsvg_ArrayOfScatteringMetaData (void *vp)
void * allocate_wsvg_ArrayOfSingleScatteringData ()
void deallocate_wsvg_ArrayOfSingleScatteringData (void *vp)
void * duplicate_wsvg_ArrayOfSingleScatteringData (void *vp)
void * allocate_wsvg_ArrayOfSparse ()
void deallocate_wsvg_ArrayOfSparse (void *vp)
void * duplicate_wsvg_ArrayOfSparse (void *vp)
void * allocate_wsvg_ArrayOfStokesVector ()
void deallocate_wsvg_ArrayOfStokesVector (void *vp)
void * duplicate_wsvg_ArrayOfStokesVector (void *vp)
void * allocate_wsvg_ArrayOfString ()
void deallocate_wsvg_ArrayOfString (void *vp)
void * duplicate_wsvg_ArrayOfString (void *vp)
void * allocate_wsvg_ArrayOfTelsemAtlas ()
void deallocate_wsvg_ArrayOfTelsemAtlas (void *vp)
void * duplicate_wsvg_ArrayOfTelsemAtlas (void *vp)
void * allocate_wsvg_ArrayOfTensor3 ()
void deallocate_wsvg_ArrayOfTensor3 (void *vp)
void * duplicate_wsvg_ArrayOfTensor3 (void *vp)
void * allocate_wsvg_ArrayOfTensor4 ()
void deallocate_wsvg_ArrayOfTensor4 (void *vp)
void * duplicate_wsvg_ArrayOfTensor4 (void *vp)
void * allocate_wsvg_ArrayOfTensor5 ()
void deallocate_wsvg_ArrayOfTensor5 (void *vp)
void * duplicate_wsvg_ArrayOfTensor5 (void *vp)
void * allocate_wsvg_ArrayOfTensor6 ()
void deallocate_wsvg_ArrayOfTensor6 (void *vp)
void * duplicate_wsvg_ArrayOfTensor6 (void *vp)
void * allocate_wsvg_ArrayOfTensor7 ()
void deallocate_wsvg_ArrayOfTensor7 (void *vp)
void * duplicate_wsvg_ArrayOfTensor7 (void *vp)
void * allocate_wsvg_ArrayOfTime ()
void deallocate_wsvg_ArrayOfTime (void *vp)
void * duplicate_wsvg_ArrayOfTime (void *vp)
void * allocate_wsvg_ArrayOfTransmissionMatrix ()
void deallocate_wsvg_ArrayOfTransmissionMatrix (void *vp)
void * duplicate_wsvg_ArrayOfTransmissionMatrix (void *vp)
void * allocate_wsvg_ArrayOfVector ()
void deallocate_wsvg_ArrayOfVector (void *vp)
void * duplicate_wsvg_ArrayOfVector (void *vp)
void * allocate_wsvg_ArrayOfXsecRecord ()
void deallocate_wsvg_ArrayOfXsecRecord (void *vp)
void * duplicate_wsvg_ArrayOfXsecRecord (void *vp)
void * allocate_wsvg_CIARecord ()
void deallocate_wsvg_CIARecord (void *vp)
void * duplicate_wsvg_CIARecord (void *vp)
void * allocate_wsvg_CovarianceMatrix ()
void deallocate_wsvg_CovarianceMatrix (void *vp)
void * duplicate_wsvg_CovarianceMatrix (void *vp)
void * allocate_wsvg_EnergyLevelMap ()
void deallocate_wsvg_EnergyLevelMap (void *vp)
void * duplicate_wsvg_EnergyLevelMap (void *vp)
void * allocate_wsvg_GasAbsLookup ()
void deallocate_wsvg_GasAbsLookup (void *vp)
void * duplicate_wsvg_GasAbsLookup (void *vp)
void * allocate_wsvg_GridPos ()
void deallocate_wsvg_GridPos (void *vp)
void * duplicate_wsvg_GridPos (void *vp)
void * allocate_wsvg_GriddedField1 ()
void deallocate_wsvg_GriddedField1 (void *vp)
void * duplicate_wsvg_GriddedField1 (void *vp)
void * allocate_wsvg_GriddedField2 ()
void deallocate_wsvg_GriddedField2 (void *vp)
void * duplicate_wsvg_GriddedField2 (void *vp)
void * allocate_wsvg_GriddedField3 ()
void deallocate_wsvg_GriddedField3 (void *vp)
void * duplicate_wsvg_GriddedField3 (void *vp)
void * allocate_wsvg_GriddedField4 ()
void deallocate_wsvg_GriddedField4 (void *vp)
void * duplicate_wsvg_GriddedField4 (void *vp)
void * allocate_wsvg_GriddedField5 ()
void deallocate_wsvg_GriddedField5 (void *vp)
void * duplicate_wsvg_GriddedField5 (void *vp)
void * allocate_wsvg_GriddedField6 ()
void deallocate_wsvg_GriddedField6 (void *vp)
void * duplicate_wsvg_GriddedField6 (void *vp)
void * allocate_wsvg_HitranRelaxationMatrixData ()
void deallocate_wsvg_HitranRelaxationMatrixData (void *vp)
void * duplicate_wsvg_HitranRelaxationMatrixData (void *vp)
void * allocate_wsvg_Index ()
void deallocate_wsvg_Index (void *vp)
void * duplicate_wsvg_Index (void *vp)
void * allocate_wsvg_JacobianTarget ()
void deallocate_wsvg_JacobianTarget (void *vp)
void * duplicate_wsvg_JacobianTarget (void *vp)
void * allocate_wsvg_MCAntenna ()
void deallocate_wsvg_MCAntenna (void *vp)
void * duplicate_wsvg_MCAntenna (void *vp)
void * allocate_wsvg_Matrix ()
void deallocate_wsvg_Matrix (void *vp)
void * duplicate_wsvg_Matrix (void *vp)
void * allocate_wsvg_Numeric ()
void deallocate_wsvg_Numeric (void *vp)
void * duplicate_wsvg_Numeric (void *vp)
void * allocate_wsvg_Ppath ()
void deallocate_wsvg_Ppath (void *vp)
void * duplicate_wsvg_Ppath (void *vp)
void * allocate_wsvg_PropagationMatrix ()
void deallocate_wsvg_PropagationMatrix (void *vp)
void * duplicate_wsvg_PropagationMatrix (void *vp)
void * allocate_wsvg_QuantumIdentifier ()
void deallocate_wsvg_QuantumIdentifier (void *vp)
void * duplicate_wsvg_QuantumIdentifier (void *vp)
void * allocate_wsvg_RadiationVector ()
void deallocate_wsvg_RadiationVector (void *vp)
void * duplicate_wsvg_RadiationVector (void *vp)
void * allocate_wsvg_Rational ()
void deallocate_wsvg_Rational (void *vp)
void * duplicate_wsvg_Rational (void *vp)
void * allocate_wsvg_ScatteringMetaData ()
void deallocate_wsvg_ScatteringMetaData (void *vp)
void * duplicate_wsvg_ScatteringMetaData (void *vp)
void * allocate_wsvg_SingleScatteringData ()
void deallocate_wsvg_SingleScatteringData (void *vp)
void * duplicate_wsvg_SingleScatteringData (void *vp)
void * allocate_wsvg_Sparse ()
void deallocate_wsvg_Sparse (void *vp)
void * duplicate_wsvg_Sparse (void *vp)
void * allocate_wsvg_SpeciesAuxData ()
void deallocate_wsvg_SpeciesAuxData (void *vp)
void * duplicate_wsvg_SpeciesAuxData (void *vp)
void * allocate_wsvg_StokesVector ()
void deallocate_wsvg_StokesVector (void *vp)
void * duplicate_wsvg_StokesVector (void *vp)
void * allocate_wsvg_String ()
void deallocate_wsvg_String (void *vp)
void * duplicate_wsvg_String (void *vp)
void * allocate_wsvg_TelsemAtlas ()
void deallocate_wsvg_TelsemAtlas (void *vp)
void * duplicate_wsvg_TelsemAtlas (void *vp)
void * allocate_wsvg_Tensor3 ()
void deallocate_wsvg_Tensor3 (void *vp)
void * duplicate_wsvg_Tensor3 (void *vp)
void * allocate_wsvg_Tensor4 ()
void deallocate_wsvg_Tensor4 (void *vp)
void * duplicate_wsvg_Tensor4 (void *vp)
void * allocate_wsvg_Tensor5 ()
void deallocate_wsvg_Tensor5 (void *vp)
void * duplicate_wsvg_Tensor5 (void *vp)
void * allocate_wsvg_Tensor6 ()
void deallocate_wsvg_Tensor6 (void *vp)
void * duplicate_wsvg_Tensor6 (void *vp)
void * allocate_wsvg_Tensor7 ()
void deallocate_wsvg_Tensor7 (void *vp)
void * duplicate_wsvg_Tensor7 (void *vp)
void * allocate_wsvg_Timer ()
void deallocate_wsvg_Timer (void *vp)
void * duplicate_wsvg_Timer (void *vp)
void * allocate_wsvg_Time ()
void deallocate_wsvg_Time (void *vp)
void * duplicate_wsvg_Time (void *vp)
void * allocate_wsvg_TessemNN ()
void deallocate_wsvg_TessemNN (void *vp)
void * duplicate_wsvg_TessemNN (void *vp)
void * allocate_wsvg_TransmissionMatrix ()
void deallocate_wsvg_TransmissionMatrix (void *vp)
void * duplicate_wsvg_TransmissionMatrix (void *vp)
void * allocate_wsvg_Vector ()
void deallocate_wsvg_Vector (void *vp)
void * duplicate_wsvg_Vector (void *vp)
void * allocate_wsvg_Verbosity ()
void deallocate_wsvg_Verbosity (void *vp)
void * duplicate_wsvg_Verbosity (void *vp)
Detailed Description
Defines global workspace_handler_objects and its dispatch functions.
DO NOT EDIT!
Date
Oct 22 2020, 10:51:21
Definition in file workspace_memory_handler.cc.
Function Documentation
allocate_wsvg_AbsorptionLines()
void* allocate_wsvg_AbsorptionLines ()
Definition at line 36 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Agenda()
void* allocate_wsvg_Agenda ()
Definition at line 45 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Any()
void* allocate_wsvg_Any ()
Definition at line 54 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfAbsorptionLines()
void* allocate_wsvg_ArrayOfAbsorptionLines ()
Definition at line 63 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfAgenda()
void* allocate_wsvg_ArrayOfAgenda ()
Definition at line 81 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfAbsorptionLines()
void* allocate_wsvg_ArrayOfArrayOfAbsorptionLines ()
Definition at line 72 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfGriddedField1()
void* allocate_wsvg_ArrayOfArrayOfGriddedField1 ()
Definition at line 90 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfGriddedField2()
void* allocate_wsvg_ArrayOfArrayOfGriddedField2 ()
Definition at line 99 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfGriddedField3()
void* allocate_wsvg_ArrayOfArrayOfGriddedField3 ()
Definition at line 108 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfIndex()
void* allocate_wsvg_ArrayOfArrayOfIndex ()
Definition at line 117 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfMatrix()
void* allocate_wsvg_ArrayOfArrayOfMatrix ()
Definition at line 126 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfPropagationMatrix()
void* allocate_wsvg_ArrayOfArrayOfPropagationMatrix ()
Definition at line 144 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfRadiationVector()
void* allocate_wsvg_ArrayOfArrayOfRadiationVector ()
Definition at line 153 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfScatteringMetaData()
void* allocate_wsvg_ArrayOfArrayOfScatteringMetaData ()
Definition at line 162 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfSingleScatteringData()
void* allocate_wsvg_ArrayOfArrayOfSingleScatteringData ()
Definition at line 171 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfSpeciesTag()
void* allocate_wsvg_ArrayOfArrayOfSpeciesTag ()
Definition at line 180 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfStokesVector()
void* allocate_wsvg_ArrayOfArrayOfStokesVector ()
Definition at line 189 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfString()
void* allocate_wsvg_ArrayOfArrayOfString ()
Definition at line 198 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfTensor3()
void* allocate_wsvg_ArrayOfArrayOfTensor3 ()
Definition at line 207 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfTensor6()
void* allocate_wsvg_ArrayOfArrayOfTensor6 ()
Definition at line 216 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfTime()
void* allocate_wsvg_ArrayOfArrayOfTime ()
Definition at line 225 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfTransmissionMatrix()
void* allocate_wsvg_ArrayOfArrayOfTransmissionMatrix ()
Definition at line 234 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfArrayOfVector()
void* allocate_wsvg_ArrayOfArrayOfVector ()
Definition at line 243 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfCIARecord()
void* allocate_wsvg_ArrayOfCIARecord ()
Definition at line 252 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfGriddedField1()
void* allocate_wsvg_ArrayOfGriddedField1 ()
Definition at line 261 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfGriddedField2()
void* allocate_wsvg_ArrayOfGriddedField2 ()
Definition at line 270 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfGriddedField3()
void* allocate_wsvg_ArrayOfGriddedField3 ()
Definition at line 279 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfGriddedField4()
void* allocate_wsvg_ArrayOfGriddedField4 ()
Definition at line 288 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfIndex()
void* allocate_wsvg_ArrayOfIndex ()
Definition at line 297 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfJacobianTarget()
void* allocate_wsvg_ArrayOfJacobianTarget ()
Definition at line 306 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfMatrix()
void* allocate_wsvg_ArrayOfMatrix ()
Definition at line 315 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfPpath()
void* allocate_wsvg_ArrayOfPpath ()
Definition at line 135 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfPropagationMatrix()
void* allocate_wsvg_ArrayOfPropagationMatrix ()
Definition at line 324 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfQuantumIdentifier()
void* allocate_wsvg_ArrayOfQuantumIdentifier ()
Definition at line 333 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfRadiationVector()
void* allocate_wsvg_ArrayOfRadiationVector ()
Definition at line 342 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfRetrievalQuantity()
void* allocate_wsvg_ArrayOfRetrievalQuantity ()
Definition at line 351 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfScatteringMetaData()
void* allocate_wsvg_ArrayOfScatteringMetaData ()
Definition at line 360 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfSingleScatteringData()
void* allocate_wsvg_ArrayOfSingleScatteringData ()
Definition at line 369 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfSparse()
void* allocate_wsvg_ArrayOfSparse ()
Definition at line 378 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfStokesVector()
void* allocate_wsvg_ArrayOfStokesVector ()
Definition at line 387 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfString()
void* allocate_wsvg_ArrayOfString ()
Definition at line 396 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTelsemAtlas()
void* allocate_wsvg_ArrayOfTelsemAtlas ()
Definition at line 405 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTensor3()
void* allocate_wsvg_ArrayOfTensor3 ()
Definition at line 414 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTensor4()
void* allocate_wsvg_ArrayOfTensor4 ()
Definition at line 423 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTensor5()
void* allocate_wsvg_ArrayOfTensor5 ()
Definition at line 432 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTensor6()
void* allocate_wsvg_ArrayOfTensor6 ()
Definition at line 441 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTensor7()
void* allocate_wsvg_ArrayOfTensor7 ()
Definition at line 450 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTime()
void* allocate_wsvg_ArrayOfTime ()
Definition at line 459 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfTransmissionMatrix()
void* allocate_wsvg_ArrayOfTransmissionMatrix ()
Definition at line 468 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfVector()
void* allocate_wsvg_ArrayOfVector ()
Definition at line 477 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ArrayOfXsecRecord()
void* allocate_wsvg_ArrayOfXsecRecord ()
Definition at line 486 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_CIARecord()
void* allocate_wsvg_CIARecord ()
Definition at line 495 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_CovarianceMatrix()
void* allocate_wsvg_CovarianceMatrix ()
Definition at line 504 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_EnergyLevelMap()
void* allocate_wsvg_EnergyLevelMap ()
Definition at line 513 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GasAbsLookup()
void* allocate_wsvg_GasAbsLookup ()
Definition at line 522 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField1()
void* allocate_wsvg_GriddedField1 ()
Definition at line 540 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField2()
void* allocate_wsvg_GriddedField2 ()
Definition at line 549 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField3()
void* allocate_wsvg_GriddedField3 ()
Definition at line 558 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField4()
void* allocate_wsvg_GriddedField4 ()
Definition at line 567 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField5()
void* allocate_wsvg_GriddedField5 ()
Definition at line 576 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GriddedField6()
void* allocate_wsvg_GriddedField6 ()
Definition at line 585 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_GridPos()
void* allocate_wsvg_GridPos ()
Definition at line 531 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_HitranRelaxationMatrixData()
void* allocate_wsvg_HitranRelaxationMatrixData ()
Definition at line 594 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Index()
void* allocate_wsvg_Index ()
Definition at line 603 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_JacobianTarget()
void* allocate_wsvg_JacobianTarget ()
Definition at line 612 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Matrix()
void* allocate_wsvg_Matrix ()
Definition at line 630 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_MCAntenna()
void* allocate_wsvg_MCAntenna ()
Definition at line 621 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Numeric()
void* allocate_wsvg_Numeric ()
Definition at line 639 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Ppath()
void* allocate_wsvg_Ppath ()
Definition at line 648 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_PropagationMatrix()
void* allocate_wsvg_PropagationMatrix ()
Definition at line 657 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_QuantumIdentifier()
void* allocate_wsvg_QuantumIdentifier ()
Definition at line 666 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_RadiationVector()
void* allocate_wsvg_RadiationVector ()
Definition at line 675 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Rational()
void* allocate_wsvg_Rational ()
Definition at line 684 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_ScatteringMetaData()
void* allocate_wsvg_ScatteringMetaData ()
Definition at line 693 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_SingleScatteringData()
void* allocate_wsvg_SingleScatteringData ()
Definition at line 702 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Sparse()
void* allocate_wsvg_Sparse ()
Definition at line 711 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_SpeciesAuxData()
void* allocate_wsvg_SpeciesAuxData ()
Definition at line 720 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_StokesVector()
void* allocate_wsvg_StokesVector ()
Definition at line 729 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_String()
void* allocate_wsvg_String ()
Definition at line 738 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_TelsemAtlas()
void* allocate_wsvg_TelsemAtlas ()
Definition at line 747 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Tensor3()
void* allocate_wsvg_Tensor3 ()
Definition at line 756 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Tensor4()
void* allocate_wsvg_Tensor4 ()
Definition at line 765 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Tensor5()
void* allocate_wsvg_Tensor5 ()
Definition at line 774 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Tensor6()
void* allocate_wsvg_Tensor6 ()
Definition at line 783 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Tensor7()
void* allocate_wsvg_Tensor7 ()
Definition at line 792 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_TessemNN()
void* allocate_wsvg_TessemNN ()
Definition at line 819 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Time()
void* allocate_wsvg_Time ()
Definition at line 810 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Timer()
void* allocate_wsvg_Timer ()
Definition at line 801 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_TransmissionMatrix()
void* allocate_wsvg_TransmissionMatrix ()
Definition at line 828 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Vector()
void* allocate_wsvg_Vector ()
Definition at line 837 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
allocate_wsvg_Verbosity()
void* allocate_wsvg_Verbosity ()
Definition at line 846 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_AbsorptionLines()
void deallocate_wsvg_AbsorptionLines (void * vp)
Definition at line 39 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Agenda()
void deallocate_wsvg_Agenda (void * vp)
Definition at line 48 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Any()
void deallocate_wsvg_Any (void * vp)
Definition at line 57 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfAbsorptionLines()
void deallocate_wsvg_ArrayOfAbsorptionLines (void * vp)
Definition at line 66 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfAgenda()
void deallocate_wsvg_ArrayOfAgenda (void * vp)
Definition at line 84 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfAbsorptionLines()
void deallocate_wsvg_ArrayOfArrayOfAbsorptionLines (void * vp)
Definition at line 75 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfGriddedField1()
void deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp)
Definition at line 93 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfGriddedField2()
void deallocate_wsvg_ArrayOfArrayOfGriddedField2 (void * vp)
Definition at line 102 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfGriddedField3()
void deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp)
Definition at line 111 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfIndex()
void deallocate_wsvg_ArrayOfArrayOfIndex (void * vp)
Definition at line 120 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfMatrix()
void deallocate_wsvg_ArrayOfArrayOfMatrix (void * vp)
Definition at line 129 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfPropagationMatrix()
void deallocate_wsvg_ArrayOfArrayOfPropagationMatrix (void * vp)
Definition at line 147 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfRadiationVector()
void deallocate_wsvg_ArrayOfArrayOfRadiationVector (void * vp)
Definition at line 156 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfScatteringMetaData()
void deallocate_wsvg_ArrayOfArrayOfScatteringMetaData (void * vp)
Definition at line 165 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfSingleScatteringData()
void deallocate_wsvg_ArrayOfArrayOfSingleScatteringData (void * vp)
Definition at line 174 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfSpeciesTag()
void deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp)
Definition at line 183 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfStokesVector()
void deallocate_wsvg_ArrayOfArrayOfStokesVector (void * vp)
Definition at line 192 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfString()
void deallocate_wsvg_ArrayOfArrayOfString (void * vp)
Definition at line 201 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfTensor3()
void deallocate_wsvg_ArrayOfArrayOfTensor3 (void * vp)
Definition at line 210 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfTensor6()
void deallocate_wsvg_ArrayOfArrayOfTensor6 (void * vp)
Definition at line 219 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfTime()
void deallocate_wsvg_ArrayOfArrayOfTime (void * vp)
Definition at line 228 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfTransmissionMatrix()
void deallocate_wsvg_ArrayOfArrayOfTransmissionMatrix (void * vp)
Definition at line 237 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfArrayOfVector()
void deallocate_wsvg_ArrayOfArrayOfVector (void * vp)
Definition at line 246 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfCIARecord()
void deallocate_wsvg_ArrayOfCIARecord (void * vp)
Definition at line 255 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfGriddedField1()
void deallocate_wsvg_ArrayOfGriddedField1 (void * vp)
Definition at line 264 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfGriddedField2()
void deallocate_wsvg_ArrayOfGriddedField2 (void * vp)
Definition at line 273 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfGriddedField3()
void deallocate_wsvg_ArrayOfGriddedField3 (void * vp)
Definition at line 282 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfGriddedField4()
void deallocate_wsvg_ArrayOfGriddedField4 (void * vp)
Definition at line 291 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfIndex()
void deallocate_wsvg_ArrayOfIndex (void * vp)
Definition at line 300 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfJacobianTarget()
void deallocate_wsvg_ArrayOfJacobianTarget (void * vp)
Definition at line 309 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfMatrix()
void deallocate_wsvg_ArrayOfMatrix (void * vp)
Definition at line 318 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfPpath()
void deallocate_wsvg_ArrayOfPpath (void * vp)
Definition at line 138 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfPropagationMatrix()
void deallocate_wsvg_ArrayOfPropagationMatrix (void * vp)
Definition at line 327 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfQuantumIdentifier()
void deallocate_wsvg_ArrayOfQuantumIdentifier (void * vp)
Definition at line 336 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfRadiationVector()
void deallocate_wsvg_ArrayOfRadiationVector (void * vp)
Definition at line 345 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfRetrievalQuantity()
void deallocate_wsvg_ArrayOfRetrievalQuantity (void * vp)
Definition at line 354 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfScatteringMetaData()
void deallocate_wsvg_ArrayOfScatteringMetaData (void * vp)
Definition at line 363 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfSingleScatteringData()
void deallocate_wsvg_ArrayOfSingleScatteringData (void * vp)
Definition at line 372 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfSparse()
void deallocate_wsvg_ArrayOfSparse (void * vp)
Definition at line 381 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfStokesVector()
void deallocate_wsvg_ArrayOfStokesVector (void * vp)
Definition at line 390 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfString()
void deallocate_wsvg_ArrayOfString (void * vp)
Definition at line 399 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTelsemAtlas()
void deallocate_wsvg_ArrayOfTelsemAtlas (void * vp)
Definition at line 408 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTensor3()
void deallocate_wsvg_ArrayOfTensor3 (void * vp)
Definition at line 417 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTensor4()
void deallocate_wsvg_ArrayOfTensor4 (void * vp)
Definition at line 426 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTensor5()
void deallocate_wsvg_ArrayOfTensor5 (void * vp)
Definition at line 435 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTensor6()
void deallocate_wsvg_ArrayOfTensor6 (void * vp)
Definition at line 444 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTensor7()
void deallocate_wsvg_ArrayOfTensor7 (void * vp)
Definition at line 453 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTime()
void deallocate_wsvg_ArrayOfTime (void * vp)
Definition at line 462 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfTransmissionMatrix()
void deallocate_wsvg_ArrayOfTransmissionMatrix (void * vp)
Definition at line 471 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfVector()
void deallocate_wsvg_ArrayOfVector (void * vp)
Definition at line 480 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ArrayOfXsecRecord()
void deallocate_wsvg_ArrayOfXsecRecord (void * vp)
Definition at line 489 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_CIARecord()
void deallocate_wsvg_CIARecord (void * vp)
Definition at line 498 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_CovarianceMatrix()
void deallocate_wsvg_CovarianceMatrix (void * vp)
Definition at line 507 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_EnergyLevelMap()
void deallocate_wsvg_EnergyLevelMap (void * vp)
Definition at line 516 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GasAbsLookup()
void deallocate_wsvg_GasAbsLookup (void * vp)
Definition at line 525 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField1()
void deallocate_wsvg_GriddedField1 (void * vp)
Definition at line 543 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField2()
void deallocate_wsvg_GriddedField2 (void * vp)
Definition at line 552 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField3()
void deallocate_wsvg_GriddedField3 (void * vp)
Definition at line 561 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField4()
void deallocate_wsvg_GriddedField4 (void * vp)
Definition at line 570 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField5()
void deallocate_wsvg_GriddedField5 (void * vp)
Definition at line 579 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GriddedField6()
void deallocate_wsvg_GriddedField6 (void * vp)
Definition at line 588 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_GridPos()
void deallocate_wsvg_GridPos (void * vp)
Definition at line 534 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_HitranRelaxationMatrixData()
void deallocate_wsvg_HitranRelaxationMatrixData (void * vp)
Definition at line 597 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Index()
void deallocate_wsvg_Index (void * vp)
Definition at line 606 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_JacobianTarget()
void deallocate_wsvg_JacobianTarget (void * vp)
Definition at line 615 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Matrix()
void deallocate_wsvg_Matrix (void * vp)
Definition at line 633 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_MCAntenna()
void deallocate_wsvg_MCAntenna (void * vp)
Definition at line 624 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Numeric()
void deallocate_wsvg_Numeric (void * vp)
Definition at line 642 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Ppath()
void deallocate_wsvg_Ppath (void * vp)
Definition at line 651 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_PropagationMatrix()
void deallocate_wsvg_PropagationMatrix (void * vp)
Definition at line 660 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_QuantumIdentifier()
void deallocate_wsvg_QuantumIdentifier (void * vp)
Definition at line 669 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_RadiationVector()
void deallocate_wsvg_RadiationVector (void * vp)
Definition at line 678 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Rational()
void deallocate_wsvg_Rational (void * vp)
Definition at line 687 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_ScatteringMetaData()
void deallocate_wsvg_ScatteringMetaData (void * vp)
Definition at line 696 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_SingleScatteringData()
void deallocate_wsvg_SingleScatteringData (void * vp)
Definition at line 705 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Sparse()
void deallocate_wsvg_Sparse (void * vp)
Definition at line 714 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_SpeciesAuxData()
void deallocate_wsvg_SpeciesAuxData (void * vp)
Definition at line 723 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_StokesVector()
void deallocate_wsvg_StokesVector (void * vp)
Definition at line 732 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_String()
void deallocate_wsvg_String (void * vp)
Definition at line 741 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_TelsemAtlas()
void deallocate_wsvg_TelsemAtlas (void * vp)
Definition at line 750 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Tensor3()
void deallocate_wsvg_Tensor3 (void * vp)
Definition at line 759 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Tensor4()
void deallocate_wsvg_Tensor4 (void * vp)
Definition at line 768 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Tensor5()
void deallocate_wsvg_Tensor5 (void * vp)
Definition at line 777 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Tensor6()
void deallocate_wsvg_Tensor6 (void * vp)
Definition at line 786 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Tensor7()
void deallocate_wsvg_Tensor7 (void * vp)
Definition at line 795 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_TessemNN()
void deallocate_wsvg_TessemNN (void * vp)
Definition at line 822 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Time()
void deallocate_wsvg_Time (void * vp)
Definition at line 813 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Timer()
void deallocate_wsvg_Timer (void * vp)
Definition at line 804 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_TransmissionMatrix()
void deallocate_wsvg_TransmissionMatrix (void * vp)
Definition at line 831 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Vector()
void deallocate_wsvg_Vector (void * vp)
Definition at line 840 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
deallocate_wsvg_Verbosity()
void deallocate_wsvg_Verbosity (void * vp)
Definition at line 849 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_AbsorptionLines()
void* duplicate_wsvg_AbsorptionLines (void * vp)
Definition at line 42 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Agenda()
void* duplicate_wsvg_Agenda (void * vp)
Definition at line 51 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Any()
void* duplicate_wsvg_Any (void * vp)
Definition at line 60 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfAbsorptionLines()
void* duplicate_wsvg_ArrayOfAbsorptionLines (void * vp)
Definition at line 69 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfAgenda()
void* duplicate_wsvg_ArrayOfAgenda (void * vp)
Definition at line 87 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfAbsorptionLines()
void* duplicate_wsvg_ArrayOfArrayOfAbsorptionLines (void * vp)
Definition at line 78 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfGriddedField1()
void* duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp)
Definition at line 96 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfGriddedField2()
void* duplicate_wsvg_ArrayOfArrayOfGriddedField2 (void * vp)
Definition at line 105 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfGriddedField3()
void* duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp)
Definition at line 114 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfIndex()
void* duplicate_wsvg_ArrayOfArrayOfIndex (void * vp)
Definition at line 123 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfMatrix()
void* duplicate_wsvg_ArrayOfArrayOfMatrix (void * vp)
Definition at line 132 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfPropagationMatrix()
void* duplicate_wsvg_ArrayOfArrayOfPropagationMatrix (void * vp)
Definition at line 150 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfRadiationVector()
void* duplicate_wsvg_ArrayOfArrayOfRadiationVector (void * vp)
Definition at line 159 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfScatteringMetaData()
void* duplicate_wsvg_ArrayOfArrayOfScatteringMetaData (void * vp)
Definition at line 168 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfSingleScatteringData()
void* duplicate_wsvg_ArrayOfArrayOfSingleScatteringData (void * vp)
Definition at line 177 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfSpeciesTag()
void* duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp)
Definition at line 186 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfStokesVector()
void* duplicate_wsvg_ArrayOfArrayOfStokesVector (void * vp)
Definition at line 195 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfString()
void* duplicate_wsvg_ArrayOfArrayOfString (void * vp)
Definition at line 204 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfTensor3()
void* duplicate_wsvg_ArrayOfArrayOfTensor3 (void * vp)
Definition at line 213 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfTensor6()
void* duplicate_wsvg_ArrayOfArrayOfTensor6 (void * vp)
Definition at line 222 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfTime()
void* duplicate_wsvg_ArrayOfArrayOfTime (void * vp)
Definition at line 231 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfTransmissionMatrix()
void* duplicate_wsvg_ArrayOfArrayOfTransmissionMatrix (void * vp)
Definition at line 240 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfArrayOfVector()
void* duplicate_wsvg_ArrayOfArrayOfVector (void * vp)
Definition at line 249 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfCIARecord()
void* duplicate_wsvg_ArrayOfCIARecord (void * vp)
Definition at line 258 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfGriddedField1()
void* duplicate_wsvg_ArrayOfGriddedField1 (void * vp)
Definition at line 267 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfGriddedField2()
void* duplicate_wsvg_ArrayOfGriddedField2 (void * vp)
Definition at line 276 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfGriddedField3()
void* duplicate_wsvg_ArrayOfGriddedField3 (void * vp)
Definition at line 285 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfGriddedField4()
void* duplicate_wsvg_ArrayOfGriddedField4 (void * vp)
Definition at line 294 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfIndex()
void* duplicate_wsvg_ArrayOfIndex (void * vp)
Definition at line 303 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfJacobianTarget()
void* duplicate_wsvg_ArrayOfJacobianTarget (void * vp)
Definition at line 312 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfMatrix()
void* duplicate_wsvg_ArrayOfMatrix (void * vp)
Definition at line 321 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfPpath()
void* duplicate_wsvg_ArrayOfPpath (void * vp)
Definition at line 141 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfPropagationMatrix()
void* duplicate_wsvg_ArrayOfPropagationMatrix (void * vp)
Definition at line 330 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfQuantumIdentifier()
void* duplicate_wsvg_ArrayOfQuantumIdentifier (void * vp)
Definition at line 339 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfRadiationVector()
void* duplicate_wsvg_ArrayOfRadiationVector (void * vp)
Definition at line 348 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfRetrievalQuantity()
void* duplicate_wsvg_ArrayOfRetrievalQuantity (void * vp)
Definition at line 357 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfScatteringMetaData()
void* duplicate_wsvg_ArrayOfScatteringMetaData (void * vp)
Definition at line 366 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfSingleScatteringData()
void* duplicate_wsvg_ArrayOfSingleScatteringData (void * vp)
Definition at line 375 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfSparse()
void* duplicate_wsvg_ArrayOfSparse (void * vp)
Definition at line 384 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfStokesVector()
void* duplicate_wsvg_ArrayOfStokesVector (void * vp)
Definition at line 393 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfString()
void* duplicate_wsvg_ArrayOfString (void * vp)
Definition at line 402 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTelsemAtlas()
void* duplicate_wsvg_ArrayOfTelsemAtlas (void * vp)
Definition at line 411 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTensor3()
void* duplicate_wsvg_ArrayOfTensor3 (void * vp)
Definition at line 420 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTensor4()
void* duplicate_wsvg_ArrayOfTensor4 (void * vp)
Definition at line 429 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTensor5()
void* duplicate_wsvg_ArrayOfTensor5 (void * vp)
Definition at line 438 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTensor6()
void* duplicate_wsvg_ArrayOfTensor6 (void * vp)
Definition at line 447 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTensor7()
void* duplicate_wsvg_ArrayOfTensor7 (void * vp)
Definition at line 456 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTime()
void* duplicate_wsvg_ArrayOfTime (void * vp)
Definition at line 465 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfTransmissionMatrix()
void* duplicate_wsvg_ArrayOfTransmissionMatrix (void * vp)
Definition at line 474 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfVector()
void* duplicate_wsvg_ArrayOfVector (void * vp)
Definition at line 483 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ArrayOfXsecRecord()
void* duplicate_wsvg_ArrayOfXsecRecord (void * vp)
Definition at line 492 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_CIARecord()
void* duplicate_wsvg_CIARecord (void * vp)
Definition at line 501 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_CovarianceMatrix()
void* duplicate_wsvg_CovarianceMatrix (void * vp)
Definition at line 510 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_EnergyLevelMap()
void* duplicate_wsvg_EnergyLevelMap (void * vp)
Definition at line 519 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GasAbsLookup()
void* duplicate_wsvg_GasAbsLookup (void * vp)
Definition at line 528 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField1()
void* duplicate_wsvg_GriddedField1 (void * vp)
Definition at line 546 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField2()
void* duplicate_wsvg_GriddedField2 (void * vp)
Definition at line 555 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField3()
void* duplicate_wsvg_GriddedField3 (void * vp)
Definition at line 564 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField4()
void* duplicate_wsvg_GriddedField4 (void * vp)
Definition at line 573 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField5()
void* duplicate_wsvg_GriddedField5 (void * vp)
Definition at line 582 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GriddedField6()
void* duplicate_wsvg_GriddedField6 (void * vp)
Definition at line 591 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_GridPos()
void* duplicate_wsvg_GridPos (void * vp)
Definition at line 537 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_HitranRelaxationMatrixData()
void* duplicate_wsvg_HitranRelaxationMatrixData (void * vp)
Definition at line 600 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Index()
void* duplicate_wsvg_Index (void * vp)
Definition at line 609 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_JacobianTarget()
void* duplicate_wsvg_JacobianTarget (void * vp)
Definition at line 618 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Matrix()
void* duplicate_wsvg_Matrix (void * vp)
Definition at line 636 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_MCAntenna()
void* duplicate_wsvg_MCAntenna (void * vp)
Definition at line 627 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Numeric()
void* duplicate_wsvg_Numeric (void * vp)
Definition at line 645 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Ppath()
void* duplicate_wsvg_Ppath (void * vp)
Definition at line 654 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_PropagationMatrix()
void* duplicate_wsvg_PropagationMatrix (void * vp)
Definition at line 663 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_QuantumIdentifier()
void* duplicate_wsvg_QuantumIdentifier (void * vp)
Definition at line 672 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_RadiationVector()
void* duplicate_wsvg_RadiationVector (void * vp)
Definition at line 681 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Rational()
void* duplicate_wsvg_Rational (void * vp)
Definition at line 690 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_ScatteringMetaData()
void* duplicate_wsvg_ScatteringMetaData (void * vp)
Definition at line 699 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_SingleScatteringData()
void* duplicate_wsvg_SingleScatteringData (void * vp)
Definition at line 708 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Sparse()
void* duplicate_wsvg_Sparse (void * vp)
Definition at line 717 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_SpeciesAuxData()
void* duplicate_wsvg_SpeciesAuxData (void * vp)
Definition at line 726 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_StokesVector()
void* duplicate_wsvg_StokesVector (void * vp)
Definition at line 735 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_String()
void* duplicate_wsvg_String (void * vp)
Definition at line 744 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_TelsemAtlas()
void* duplicate_wsvg_TelsemAtlas (void * vp)
Definition at line 753 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Tensor3()
void* duplicate_wsvg_Tensor3 (void * vp)
Definition at line 762 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Tensor4()
void* duplicate_wsvg_Tensor4 (void * vp)
Definition at line 771 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Tensor5()
void* duplicate_wsvg_Tensor5 (void * vp)
Definition at line 780 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Tensor6()
void* duplicate_wsvg_Tensor6 (void * vp)
Definition at line 789 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Tensor7()
void* duplicate_wsvg_Tensor7 (void * vp)
Definition at line 798 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_TessemNN()
void* duplicate_wsvg_TessemNN (void * vp)
Definition at line 825 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Time()
void* duplicate_wsvg_Time (void * vp)
Definition at line 816 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Timer()
void* duplicate_wsvg_Timer (void * vp)
Definition at line 807 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_TransmissionMatrix()
void* duplicate_wsvg_TransmissionMatrix (void * vp)
Definition at line 834 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Vector()
void* duplicate_wsvg_Vector (void * vp)
Definition at line 843 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().
duplicate_wsvg_Verbosity()
void* duplicate_wsvg_Verbosity (void * vp)
Definition at line 852 of file workspace_memory_handler.cc.
Referenced by WorkspaceMemoryHandler::initialize().