ARTS: wsv_aux.h File Reference
wsv_aux.h File Reference
Auxiliary header stuff related to workspace variable groups.
#include "array.h"
#include "arts.h"
#include "exceptions.h"
Classes
class WsvRecord
This class contains all static information for one workspace variable.
Functions
void get_wsv_group_ids (ArrayOfIndex &ids, String name)
Returns list of ids of the given group names.
bool is_agenda_group_id (const Index group_id)
Check if group is an agenda group.
Index get_wsv_group_id (const String &name)
Returns the id of the given group.
String get_array_groups_as_string (bool basetype_is_group=false, bool return_basetype_only=false)
Return string list of array types.
ostream & operator<< (ostream &os, const WsvRecord &wr)
Output operator for WsvRecord.
Detailed Description
Auxiliary header stuff related to workspace variable groups.
Normally you should not need to edit this file.
Author
Stefan Buehler
Date
2000-06-10
Definition in file wsv_aux.h.
Function Documentation
get_array_groups_as_string()
String get_array_groups_as_string (bool basetype_is_group = false, bool return_basetype_only = false)
Return string list of array types.
Definition at line 234 of file groups.cc.
References get_wsv_group_id(), Array< base >::nelem(), and global_data::wsv_group_names.
Referenced by define_md_data_raw().
get_wsv_group_id()
Index get_wsv_group_id (const String & name)
Returns the id of the given group.
Definition at line 225 of file groups.cc.
References global_data::WsvGroupMap.
Referenced by define_valid_keyword_groups(), expand_md_data_raw_to_md_data(), get_array_groups_as_string(), get_wsv_group_ids(), is_agenda_group_id(), main(), MdRecord::MdRecord(), operator<<(), option_input(), option_methods(), ArtsParser::parse_agenda(), ArtsParser::parse_generic_input(), ArtsParser::parse_generic_output(), ArtsParser::read_name_or_value(), ArtsParser::set_gin_to_default(), MdRecord::subst_any_with_group(), MdRecord::subst_any_with_specific_group(), ArtsParser::tasklist_insert_set_delete(), and WsvRecord::WsvRecord().
get_wsv_group_ids()
void get_wsv_group_ids (ArrayOfIndex & ids, String name)
Returns list of ids of the given group names.
Definition at line 188 of file groups.cc.
References get_wsv_group_id(), and my_basic_string< charT >::nelem().
Referenced by MdRecord::MdRecord().
is_agenda_group_id()
bool is_agenda_group_id (const Index group_id)
Check if group is an agenda group.
Definition at line 220 of file groups.cc.
References get_wsv_group_id().
Referenced by main(), write_method_header(), and write_method_header_documentation().
operator<<()
ostream& operator<< (ostream & os, const WsvRecord & wr)
Output operator for WsvRecord.
Author
Stefan Buehler
This has to be here rather than with workspace.cc or workspace_aux.cc, because it uses agenda_data and AgendaMap.
Parameters
os Output stream.
wr Workspace variable record.
Returns
Output stream.
Definition at line 229 of file agenda_record.cc.
References global_data::agenda_data, global_data::AgendaMap, ARTS_ASSERT, WsvRecord::Description(), get_wsv_group_id(), WsvRecord::Group(), WsvRecord::Name(), and global_data::wsv_group_names.