ARTS: xml_io_general_types.cc File Reference
xml_io_general_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "xml_io_base.h"
#include "double_imanip.h"
Functions
void xml_read_from_stream (istream &is_xml, Index &index, bifstream *pbifs, const Verbosity &verbosity)
Reads Index from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Index &index, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Index to XML output stream.
void xml_read_from_stream (istream &is_xml, Matrix &matrix, bifstream *pbifs, const Verbosity &verbosity)
Reads Matrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Matrix &matrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Matrix to XML output stream.
void xml_read_from_stream (istream &is_xml, Numeric &numeric, bifstream *pbifs, const Verbosity &verbosity)
Reads Numeric from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Numeric &numeric, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Numeric to XML output stream.
void xml_read_from_stream (istream &is_xml, Sparse &sparse, bifstream *pbifs, const Verbosity &verbosity)
Reads Sparse from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Sparse &sparse, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Sparse to XML output stream.
void xml_read_from_stream (istream &is_xml, String &str, bifstream *, const Verbosity &verbosity)
Reads String from XML input stream.
void xml_write_to_stream (ostream &os_xml, const String &str, bofstream *, const String &name, const Verbosity &verbosity)
Writes String to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor3 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor3 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor4 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor4 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor4 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor5 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor5 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor5 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor5 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor6 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor6 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor7 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor7 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor7 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor7 to XML output stream.
void xml_parse_from_stream (istream &is_xml, Vector &vector, bifstream *pbifs, XMLTag &tag, const Verbosity &)
Parses Vector from XML input stream.
void xml_read_from_stream (istream &is_xml, Vector &vector, bifstream *pbifs, const Verbosity &verbosity)
Reads Vector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Vector &vector, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Vector to XML output stream.
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_general_types.cc.
Function Documentation
xml_parse_from_stream()
void xml_parse_from_stream (istream & is_xml, Vector & vector, bifstream * pbifs, XMLTag & tag, const Verbosity & verbosity)
Parses Vector from XML input stream.
Parameters
is_xml XML Input stream
vector Vector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 1139 of file xml_io_general_types.cc.
References XMLTag::get_attribute_value(), Absorption::nelem(), Vector::resize(), and xml_data_parse_error().
Referenced by xml_read_from_stream().
xml_read_from_stream() [1/11]
void xml_read_from_stream (istream & is_xml, Index & index, bifstream * pbifs, const Verbosity & verbosity)
Reads Index from XML input stream.
Parameters
is_xml XML Input stream
index Index return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 46 of file xml_io_general_types.cc.
References XMLTag::check_name(), XMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [2/11]
void xml_read_from_stream (istream & is_xml, Matrix & matrix, bifstream * pbifs, const Verbosity & verbosity)
Reads Matrix from XML input stream.
Parameters
is_xml XML Input stream
matrix Matrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 109 of file xml_io_general_types.cc.
References c, XMLTag::check_name(), XMLTag::get_attribute_value(), IGRF::matrix(), ncols, nrows, XMLTag::read_from_stream(), Matrix::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [3/11]
void xml_read_from_stream (istream & is_xml, Numeric & numeric, bifstream * pbifs, const Verbosity & verbosity)
Reads Numeric from XML input stream.
Parameters
is_xml XML Input stream
numeric Numeric return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 205 of file xml_io_general_types.cc.
References XMLTag::check_name(), XMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [4/11]
void xml_read_from_stream (istream & is_xml, Sparse & sparse, bifstream * pbifs, const Verbosity & verbosity)
Reads Sparse from XML input stream.
Parameters
is_xml XML Input stream
sparse Sparse return value
pbifs Pointer to binary input stream, NULL in case of ASCII file.
Definition at line 270 of file xml_io_general_types.cc.
References XMLTag::check_name(), data, XMLTag::get_attribute_value(), Sparse::insert_elements(), ncols, nrows, XMLTag::read_from_stream(), Sparse::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [5/11]
void xml_read_from_stream (istream & is_xml, String & str, bifstream * , const Verbosity & verbosity)
Reads String from XML input stream.
Parameters
is_xml XML Input stream
str String return value
Definition at line 472 of file xml_io_general_types.cc.
References Options::char, XMLTag::check_name(), XMLTag::read_from_stream(), str, ARTS::Var::verbosity(), and xml_parse_error().
xml_read_from_stream() [6/11]
void xml_read_from_stream (istream & is_xml, Tensor3 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor3 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 560 of file xml_io_general_types.cc.
References c, XMLTag::check_name(), XMLTag::get_attribute_value(), ncols, npages, nrows, XMLTag::read_from_stream(), Tensor3::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [7/11]
void xml_read_from_stream (istream & is_xml, Tensor4 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor4 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 662 of file xml_io_general_types.cc.
References b, c, XMLTag::check_name(), XMLTag::get_attribute_value(), nbooks, ncols, npages, nrows, XMLTag::read_from_stream(), Tensor4::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [8/11]
void xml_read_from_stream (istream & is_xml, Tensor5 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor5 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 770 of file xml_io_general_types.cc.
References b, c, XMLTag::check_name(), XMLTag::get_attribute_value(), nbooks, ncols, npages, nrows, nshelves, XMLTag::read_from_stream(), Tensor5::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [9/11]
void xml_read_from_stream (istream & is_xml, Tensor6 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor6 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 886 of file xml_io_general_types.cc.
References b, c, XMLTag::check_name(), XMLTag::get_attribute_value(), nbooks, ncols, npages, nrows, nshelves, nvitrines, XMLTag::read_from_stream(), Tensor6::resize(), v, ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [10/11]
void xml_read_from_stream (istream & is_xml, Tensor7 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor7 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1008 of file xml_io_general_types.cc.
References b, c, XMLTag::check_name(), XMLTag::get_attribute_value(), Interpolation::l(), nbooks, ncols, ARTS::Var::nlibraries(), npages, nrows, nshelves, nvitrines, XMLTag::read_from_stream(), Tensor7::resize(), v, ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [11/11]
void xml_read_from_stream (istream & is_xml, Vector & vector, bifstream * pbifs, const Verbosity & verbosity)
Reads Vector from XML input stream.
Parameters
is_xml XML Input stream
vector Vector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1176 of file xml_io_general_types.cc.
References XMLTag::check_name(), XMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_from_stream().
xml_write_to_stream() [1/11]
void xml_write_to_stream (ostream & os_xml, const Index & index, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Index to XML output stream.
Parameters
os_xml XML Output stream
index Index value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 78 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), XMLTag::set_name(), ARTS::Var::verbosity(), and XMLTag::write_to_stream().
xml_write_to_stream() [2/11]
void xml_write_to_stream (ostream & os_xml, const Matrix & matrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Matrix to XML output stream.
Parameters
os_xml XML Output stream
matrix Matrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 156 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), c, IGRF::matrix(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [3/11]
void xml_write_to_stream (ostream & os_xml, const Numeric & numeric, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Numeric to XML output stream.
Parameters
os_xml XML Output stream
numeric Numeric value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 237 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [4/11]
void xml_write_to_stream (ostream & os_xml, const Sparse & sparse, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Sparse to XML output stream.
Parameters
os_xml XML Output stream
sparse Sparse
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 376 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), data, Sparse::list_elements(), Sparse::ncols(), Sparse::nnz(), Sparse::nrows(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [5/11]
void xml_write_to_stream (ostream & os_xml, const String & str, bofstream * , const String & name, const Verbosity & verbosity)
Writes String to XML output stream.
Parameters
os_xml XML Output stream
str String value
name Optional name attribute
Definition at line 532 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), XMLTag::set_name(), str, ARTS::Var::verbosity(), and XMLTag::write_to_stream().
xml_write_to_stream() [6/11]
void xml_write_to_stream (ostream & os_xml, const Tensor3 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor3 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 612 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), c, ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [7/11]
void xml_write_to_stream (ostream & os_xml, const Tensor4 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor4 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 717 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), b, c, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [8/11]
void xml_write_to_stream (ostream & os_xml, const Tensor5 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor5 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 830 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), b, c, ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), XMLTag::set_name(), ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [9/11]
void xml_write_to_stream (ostream & os_xml, const Tensor6 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor6 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 949 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), b, c, ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), XMLTag::set_name(), v, ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [10/11]
void xml_write_to_stream (ostream & os_xml, const Tensor7 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor7 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1076 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), b, c, Interpolation::l(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), XMLTag::set_name(), v, ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [11/11]
void xml_write_to_stream (ostream & os_xml, const Vector & vector, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Vector to XML output stream.
Parameters
os_xml XML Output stream
vector Vector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1198 of file xml_io_general_types.cc.
References XMLTag::add_attribute(), ConstVectorView::nelem(), XMLTag::set_name(), v, ARTS::Var::verbosity(), XMLTag::write_to_stream(), and xml_set_stream_precision().