ARTS: xml_io_private.h File Reference
xml_io_private.h File Reference
This file contains private function declarations and template instantiation to handle XML data files.
#include <cfloat>
#include <memory>
#include <stdexcept>
#include "absorption.h"
#include "agenda_class.h"
#include "array.h"
#include "bifstream.h"
#include "bofstream.h"
#include "gas_abs_lookup.h"
#include "matpackVII.h"
#include "messages.h"
#include "optproperties.h"
#include "ppath.h"
#include "xml_io.h"
Classes
class XMLAttribute
XML attribute class.
class ArtsXMLTag
The ARTS XML tag class.
Functions
void xml_open_output_file (ostream &file, const String &name)
void xml_open_input_file (ifstream &file, const String &name, const Verbosity &verbosity)
Open file for XML input.
void xml_find_and_open_input_file (std::shared_ptr< istream > &ifs, const String &filename, const Verbosity &verbosity)
Open plain or zipped xml file.
void xml_parse_error (const String &str_error)
Throws XML parser runtime error.
void xml_data_parse_error (ArtsXMLTag &tag, String str_error)
Throws XML parser runtime error.
void xml_read_header_from_stream (istream &is, FileType &ftype, NumericType &ntype, EndianType &etype, const Verbosity &verbosity)
Reads XML header and root tag.
void xml_read_footer_from_stream (istream &is, const Verbosity &verbosity)
Reads closing root tag.
void xml_write_header_to_stream (ostream &os, FileType ftype, const Verbosity &verbosity)
Writes XML header and root tag.
void xml_write_footer_to_stream (ostream &os, const Verbosity &verbosity)
Write closing root tag.
void xml_set_stream_precision (ostream &os)
void parse_xml_tag_content_as_string (std::istream &is_xml, String &content)
Get the content of an xml tag as a string.
Detailed Description
This file contains private function declarations and template instantiation to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2002-11-06
Definition in file xml_io_private.h.
Function Documentation
parse_xml_tag_content_as_string()
void parse_xml_tag_content_as_string (std::istream & is_xml, String & content)
Get the content of an xml tag as a string.
Definition at line 874 of file xml_io.cc.
Referenced by xml_read_from_stream().
xml_data_parse_error()
void xml_data_parse_error (ArtsXMLTag & tag, String str_error)
Throws XML parser runtime error.
This is used quite often inside the data parsing routines so it's a function for itself.
Parameters
tag ArtsXMLTag
str_error Error description
Definition at line 705 of file xml_io.cc.
References ArtsXMLTag::write_to_stream().
Referenced by xml_parse_from_stream(), and xml_read_from_stream().
xml_find_and_open_input_file()
void xml_find_and_open_input_file (std::shared_ptr< istream > & ifs, const String & filename, const Verbosity & verbosity)
Open plain or zipped xml file.
Searches the include and data paths for the given filename.
Parameters
[out] ifs Pointer to input file stream
[in] filename Input filename
[in] verbosity Verbosity
Definition at line 648 of file xml_io.cc.
References CREATE_OUT2, find_xml_file(), ARTS::Var::verbosity(), and xml_open_input_file().
Referenced by ReadArrayOfARTSCAT(), and ReadARTSCAT().
xml_open_input_file()
void xml_open_input_file (ifstream & ifs, const String & name, const Verbosity & verbosity)
Open file for XML input.
This function opens an XML file for reading.
Parameters
ifs Input filestream
name Filename
Definition at line 569 of file xml_io.cc.
References CREATE_OUT3.
Referenced by xml_find_and_open_input_file(), and xml_read_from_file().
xml_open_output_file()
void xml_open_output_file (ostream & file, const String & name)
xml_parse_error()
void xml_parse_error (const String & str_error)
Throws XML parser runtime error.
This is used quite often inside the parsing routines so it's a function for itself.
Parameters
str_error Error description
Definition at line 690 of file xml_io.cc.
Referenced by ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), xml_read_from_stream(), and xml_read_header_from_stream().
xml_read_footer_from_stream()
void xml_read_footer_from_stream (istream & is, const Verbosity & verbosity)
Reads closing root tag.
Checks whether XML file ends correctly with </arts>.
Parameters
is Input stream
Definition at line 806 of file xml_io.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and ARTS::Var::verbosity().
Referenced by xml_read_from_file().
xml_read_header_from_stream()
void xml_read_header_from_stream (istream & is, FileType & ftype, NumericType & ntype, EndianType & etype, const Verbosity & verbosity)
Reads XML header and root tag.
Check whether XML file has correct version tag and reads arts root tag information.
Parameters
is Input stream
ftype File type
ntype Numeric type
etype Endian type
Definition at line 725 of file xml_io.cc.
References ArtsXMLTag::check_name(), ENDIAN_TYPE_BIG, ENDIAN_TYPE_LITTLE, FILE_TYPE_ASCII, FILE_TYPE_BINARY, ArtsXMLTag::get_attribute_value(), NUMERIC_TYPE_DOUBLE, NUMERIC_TYPE_FLOAT, ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_error().
Referenced by xml_read_from_file().
xml_set_stream_precision()
void xml_set_stream_precision (ostream & os)
Definition at line 856 of file xml_io.cc.
References precision.
Referenced by xml_write_to_stream().
xml_write_footer_to_stream()
void xml_write_footer_to_stream (ostream & os, const Verbosity & verbosity)
Write closing root tag.
Parameters
os Output stream
Definition at line 847 of file xml_io.cc.
References ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
Referenced by xml_write_to_file().
xml_write_header_to_stream()
void xml_write_header_to_stream (ostream & os, FileType ftype, const Verbosity & verbosity)
Writes XML header and root tag.
Parameters
os Output stream
ftype File type
Definition at line 818 of file xml_io.cc.
References ArtsXMLTag::add_attribute(), FILE_TYPE_ASCII, FILE_TYPE_BINARY, FILE_TYPE_ZIPPED_ASCII, ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
Referenced by xml_write_to_file().