ARTS: xml_io_types.h File Reference
xml_io_types.h File Reference
This file contains private function declarations and template instantiation to handle XML data files.
#include <cfloat>
#include <stdexcept>
#include "absorption.h"
#include "agenda_class.h"
#include "array.h"
#include "artstime.h"
#include "bifstream.h"
#include "bofstream.h"
#include "cia.h"
#include "covariance_matrix.h"
#include "gas_abs_lookup.h"
#include "gridded_fields.h"
#include "hitran_xsec.h"
#include "jacobian.h"
#include "linemixing_hitran.h"
#include "m_general.h"
#include "matpackII.h"
#include "matpackVII.h"
#include "mc_antenna.h"
#include "mc_interp.h"
#include "messages.h"
#include "optproperties.h"
#include "ppath.h"
#include "propagationmatrix.h"
#include "telsem.h"
#include "tessem.h"
#include "transmissionmatrix.h"
#include "xml_io_private.h"
#include "absorptionlines.h"
Macros
#define TMPL_XML_READ_WRITE_STREAM(what)
Functions
void xml_parse_from_stream (istream &, Vector &, bifstream *, ArtsXMLTag &, const Verbosity &verbosity)
Parses Vector from XML input stream.
void xml_parse_from_stream (istream &, ArrayOfString &, bifstream *, ArtsXMLTag &, const Verbosity &)
Parse ArrayOfString from XML input stream.
Detailed Description
This file contains private function declarations and template instantiation to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_types.h.
Macro Definition Documentation
TMPL_XML_READ_WRITE_STREAM
#define TMPL_XML_READ_WRITE_STREAM (what)
Value:
  void xml_read_from_stream(                              \
      istream &, what &, bifstream *, const Verbosity &); \
  void xml_write_to_stream(ostream &,                     \
                           const what &,                  \
                           bofstream *,                   \
                           const String &,                \
                           const Verbosity &);
Definition at line 64 of file xml_io_types.h.
Function Documentation
xml_parse_from_stream() [1/2]
void xml_parse_from_stream (istream & is_xml, ArrayOfString & astring, bifstream * pbifs, ArtsXMLTag & tag, const Verbosity & verbosity)
Parse ArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
astring ArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 2861 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), verbosity, and xml_read_from_stream().
Referenced by xml_read_from_stream().
xml_parse_from_stream() [2/2]
void xml_parse_from_stream (istream & is_xml, Vector & vector, bifstream * pbifs, ArtsXMLTag & tag, const Verbosity & verbosity)
Parses Vector from XML input stream.
Parameters
is_xml XML Input stream
vector Vector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 1319 of file xml_io_basic_types.cc.
References ArtsXMLTag::get_attribute_value(), Absorption::nelem(), Vector::resize(), and xml_data_parse_error().
Referenced by xml_read_from_stream().