ARTS: xml_io_partfun.cc File Reference
xml_io_partfun.cc File Reference
#include "debug.h"
#include "xml_io_partfun.h"
#include "xml_io_base.h"
Namespaces
PartitionFunctions
Functions
void xml_read_from_stream (std::istream &is_xml, PartitionFunctions::Data &data, bifstream *pbifs, const Verbosity &verbosity)
Reads Data from XML input stream.
void xml_write_to_stream (std::ostream &os_xml, const PartitionFunctions::Data &data, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes PartitionFunctions::Data to XML output stream.
Data PartitionFunctions::data_read_file (const std::filesystem::path &path)
Function Documentation
xml_read_from_stream()
void xml_read_from_stream (std::istream & is_xml, PartitionFunctions::Data & data, bifstream * pbifs, const Verbosity & verbosity)
Reads Data from XML input stream.
Parameters
is_xml XML Input stream
data PartitionFunctions::Data return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 12 of file xml_io_partfun.cc.
References XMLTag::check_name(), data, XMLTag::get_attribute_value(), XMLTag::read_from_stream(), Hitran::type, and ARTS::Var::verbosity().
xml_write_to_stream()
void xml_write_to_stream (std::ostream & os_xml, const PartitionFunctions::Data & data, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes PartitionFunctions::Data to XML output stream.
Parameters
os_xml XML Output stream
data PartitionFunctions::Data
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 38 of file xml_io_partfun.cc.
References XMLTag::add_attribute(), data, XMLTag::set_name(), v, ARTS::Var::verbosity(), and XMLTag::write_to_stream().