ARTS: xml_io_basic_types.cc File Reference
xml_io_basic_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "xml_io.h"
Functions
void xml_read_from_stream (istream &is_xml, Index &index, bifstream *pbifs, const Verbosity &verbosity)
Reads Index from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Index &index, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Index to XML output stream.
void xml_read_from_stream (istream &is_xml, JacobianTarget &jt, bifstream *pbifs, const Verbosity &verbosity)
Reads JacobianTarget from XML input stream.
void xml_write_to_stream (ostream &os_xml, const JacobianTarget &jt, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes JacobianTarget to XML output stream.
void xml_read_from_stream (istream &is_xml, Matrix &matrix, bifstream *pbifs, const Verbosity &verbosity)
Reads Matrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Matrix &matrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Matrix to XML output stream.
void xml_read_from_stream (istream &is_xml, Numeric &numeric, bifstream *pbifs, const Verbosity &verbosity)
Reads Numeric from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Numeric &numeric, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Numeric to XML output stream.
void xml_read_from_stream (istream &is_xml, Rational &rational, bifstream *pbifs, const Verbosity &verbosity)
Reads Rational from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Rational &rational, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Rational to XML output stream.
void xml_read_from_stream (istream &is_xml, Sparse &sparse, bifstream *pbifs, const Verbosity &verbosity)
Reads Sparse from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Sparse &sparse, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Sparse to XML output stream.
void xml_read_from_stream (istream &is_xml, String &str, bifstream *, const Verbosity &verbosity)
Reads String from XML input stream.
void xml_write_to_stream (ostream &os_xml, const String &str, bofstream *, const String &name, const Verbosity &verbosity)
Writes String to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor3 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor3 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor4 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor4 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor4 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor5 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor5 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor5 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor5 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor6 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor6 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, Tensor7 &tensor, bifstream *pbifs, const Verbosity &verbosity)
Reads Tensor7 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Tensor7 &tensor, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Tensor7 to XML output stream.
void xml_parse_from_stream (istream &is_xml, Vector &vector, bifstream *pbifs, ArtsXMLTag &tag, const Verbosity &)
Parses Vector from XML input stream.
void xml_read_from_stream (istream &is_xml, Vector &vector, bifstream *pbifs, const Verbosity &verbosity)
Reads Vector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Vector &vector, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Vector to XML output stream.
void xml_read_from_stream (istream &is_xml, TransmissionMatrix &tm, bifstream *pbifs, const Verbosity &verbosity)
Reads TransmissionMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const TransmissionMatrix &tm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes RadiationVector to XML output stream.
void xml_read_from_stream (istream &is_xml, RadiationVector &rv, bifstream *pbifs, const Verbosity &verbosity)
Reads RadiationVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const RadiationVector &rv, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes RadiationVector to XML output stream.
void xml_read_from_stream (istream &is_xml, Time &t, bifstream *pbifs[[maybe_unused]], const Verbosity &verbosity)
Reads Time from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Time &t, bofstream *pbofs[[maybe_unused]], const String &, const Verbosity &verbosity)
Writes Time to XML output stream.
void xml_read_from_stream (istream &is_xml, AbsorptionLines &al, bifstream *pbifs, const Verbosity &verbosity)
Reads AbsorptionLines from XML input stream.
void xml_write_to_stream (ostream &os_xml, const AbsorptionLines &al, bofstream *pbofs, const String &, const Verbosity &verbosity)
Writes AbsorptionLines to XML output stream.
void xml_read_from_stream (istream &, Timer &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const Timer &, bofstream *, const String &, const Verbosity &)
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_basic_types.cc.
Function Documentation
xml_parse_from_stream()
void xml_parse_from_stream (istream & is_xml, Vector & vector, bifstream * pbifs, ArtsXMLTag & tag, const Verbosity & verbosity)
Parses Vector from XML input stream.
Parameters
is_xml XML Input stream
vector Vector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 1332 of file xml_io_basic_types.cc.
References ArtsXMLTag::get_attribute_value(), Absorption::nelem(), Vector::resize(), and xml_data_parse_error().
Referenced by xml_read_from_stream().
xml_read_from_stream() [1/18]
void xml_read_from_stream (istream & , Timer & , bifstream * , const Verbosity &)
Definition at line 1809 of file xml_io_basic_types.cc.
References ARTS_USER_ERROR_IF.
xml_read_from_stream() [2/18]
void xml_read_from_stream (istream & is_xml, AbsorptionLines & al, bifstream * pbifs, const Verbosity & verbosity)
Reads AbsorptionLines from XML input stream.
Parameters
is_xml XML Input stream
al AbsorptionLines return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Reference temperature for all parameters of the lines
cutoff frequency
linemixing limit
List of local quantum numbers, these must be defined
Catalog ID
A list of broadening species
Definition at line 1644 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), Absorption::cutoff, ArtsXMLTag::get_attribute_value(), nlines, ArtsXMLTag::read_from_stream(), Type, and ARTS::Var::verbosity().
xml_read_from_stream() [3/18]
void xml_read_from_stream (istream & is_xml, Index & index, bifstream * pbifs, const Verbosity & verbosity)
Reads Index from XML input stream.
Parameters
is_xml XML Input stream
index Index return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 45 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [4/18]
void xml_read_from_stream (istream & is_xml, JacobianTarget & jt, bifstream * pbifs, const Verbosity & verbosity)
Reads JacobianTarget from XML input stream.
Parameters
is_xml XML Input stream
jt JacobianTarget return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Catalog ID
Definition at line 108 of file xml_io_basic_types.cc.
References array_species_tag_from_string(), ARTS_USER_ERROR_IF, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), SpeciesTag::Isotopologue(), ArtsXMLTag::read_from_stream(), SpeciesTag::Species(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [5/18]
void xml_read_from_stream (istream & is_xml, Matrix & matrix, bifstream * pbifs, const Verbosity & verbosity)
Reads Matrix from XML input stream.
Parameters
is_xml XML Input stream
matrix Matrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 239 of file xml_io_basic_types.cc.
References c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ARTS::Var::ncols(), ARTS::Var::nrows(), ArtsXMLTag::read_from_stream(), Matrix::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [6/18]
void xml_read_from_stream (istream & is_xml, Numeric & numeric, bifstream * pbifs, const Verbosity & verbosity)
Reads Numeric from XML input stream.
Parameters
is_xml XML Input stream
numeric Numeric return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 335 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [7/18]
void xml_read_from_stream (istream & is_xml, RadiationVector & rv, bifstream * pbifs, const Verbosity & verbosity)
Reads RadiationVector from XML input stream.
Parameters
is_xml XML Input stream
rv RadiationVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1509 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), ARTS::Var::stokes_dim(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [8/18]
void xml_read_from_stream (istream & is_xml, Rational & rational, bifstream * pbifs, const Verbosity & verbosity)
Reads Rational from XML input stream.
Parameters
is_xml XML Input stream
rational Rational return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 400 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [9/18]
void xml_read_from_stream (istream & is_xml, Sparse & sparse, bifstream * pbifs, const Verbosity & verbosity)
Reads Sparse from XML input stream.
Parameters
is_xml XML Input stream
sparse Sparse return value
pbifs Pointer to binary input stream, NULL in case of ASCII file.
Definition at line 463 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), data, ArtsXMLTag::get_attribute_value(), Sparse::insert_elements(), ARTS::Var::ncols(), ARTS::Var::nrows(), ArtsXMLTag::read_from_stream(), Sparse::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [10/18]
void xml_read_from_stream (istream & is_xml, String & str, bifstream * , const Verbosity & verbosity)
Reads String from XML input stream.
Parameters
is_xml XML Input stream
str String return value
Definition at line 665 of file xml_io_basic_types.cc.
References Options::char, ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_error().
xml_read_from_stream() [11/18]
void xml_read_from_stream (istream & is_xml, Tensor3 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor3 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 753 of file xml_io_basic_types.cc.
References c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ARTS::Var::ncols(), ARTS::Var::npages(), ARTS::Var::nrows(), ArtsXMLTag::read_from_stream(), Tensor3::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [12/18]
void xml_read_from_stream (istream & is_xml, Tensor4 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor4 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 855 of file xml_io_basic_types.cc.
References b, c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ARTS::Var::nbooks(), ARTS::Var::ncols(), ARTS::Var::npages(), ARTS::Var::nrows(), ArtsXMLTag::read_from_stream(), Tensor4::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [13/18]
void xml_read_from_stream (istream & is_xml, Tensor5 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor5 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 963 of file xml_io_basic_types.cc.
References b, c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ARTS::Var::nbooks(), ARTS::Var::ncols(), ARTS::Var::npages(), ARTS::Var::nrows(), ARTS::Var::nshelves(), ArtsXMLTag::read_from_stream(), Tensor5::resize(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [14/18]
void xml_read_from_stream (istream & is_xml, Tensor6 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor6 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1079 of file xml_io_basic_types.cc.
References b, c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ARTS::Var::nbooks(), ARTS::Var::ncols(), ARTS::Var::npages(), ARTS::Var::nrows(), ARTS::Var::nshelves(), ARTS::Var::nvitrines(), ArtsXMLTag::read_from_stream(), Tensor6::resize(), v, ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [15/18]
void xml_read_from_stream (istream & is_xml, Tensor7 & tensor, bifstream * pbifs, const Verbosity & verbosity)
Reads Tensor7 from XML input stream.
Parameters
is_xml XML Input stream
tensor Tensor return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1201 of file xml_io_basic_types.cc.
References b, c, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Interpolation::l(), ARTS::Var::nbooks(), ARTS::Var::ncols(), ARTS::Var::nlibraries(), ARTS::Var::npages(), ARTS::Var::nrows(), ARTS::Var::nshelves(), ARTS::Var::nvitrines(), ArtsXMLTag::read_from_stream(), Tensor7::resize(), v, ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [16/18]
void xml_read_from_stream (istream & is_xml, Time & t, bifstream *pbifs] [[maybe_unused], const Verbosity & verbosity)
Reads Time from XML input stream.
Parameters
is_xml XML Input stream
t Time return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1585 of file xml_io_basic_types.cc.
References ARTS_USER_ERROR_IF, ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [17/18]
void xml_read_from_stream (istream & is_xml, TransmissionMatrix & tm, bifstream * pbifs, const Verbosity & verbosity)
Reads TransmissionMatrix from XML input stream.
Parameters
is_xml XML Input stream
tm TransmissionMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1433 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), ARTS::Var::stokes_dim(), ARTS::Var::verbosity(), and xml_data_parse_error().
xml_read_from_stream() [18/18]
void xml_read_from_stream (istream & is_xml, Vector & vector, bifstream * pbifs, const Verbosity & verbosity)
Reads Vector from XML input stream.
Parameters
is_xml XML Input stream
vector Vector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1369 of file xml_io_basic_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_from_stream().
xml_write_to_stream() [1/18]
void xml_write_to_stream (ostream & , const Timer & , bofstream * , const String & , const Verbosity &)
Definition at line 1816 of file xml_io_basic_types.cc.
References ARTS_USER_ERROR_IF.
xml_write_to_stream() [2/18]
void xml_write_to_stream (ostream & os_xml, const AbsorptionLines & al, bofstream * pbofs, const String & , const Verbosity & verbosity)
Writes AbsorptionLines to XML output stream.
Parameters
os_xml XML Output stream
al AbsorptionLines
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute (ignored)
Definition at line 1753 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), Absorption::Lines::Bath(), Absorption::Lines::BroadeningSpecies(), Absorption::Lines::Cutoff(), Absorption::Lines::CutoffFreqValue(), Absorption::Lines::LinemixingLimit(), Absorption::Lines::LineShapeMetaData(), Absorption::Lines::LineShapeType(), Absorption::Lines::LocalQuanta(), Absorption::Lines::LowerQuantumNumbers(), Absorption::Lines::MetaData(), Absorption::Lines::Mirroring(), Absorption::Lines::Normalization(), Absorption::Lines::NumLines(), Absorption::Lines::Population(), Absorption::Lines::Self(), ArtsXMLTag::set_name(), Absorption::Lines::SpeciesName(), Absorption::Lines::T0(), Absorption::Lines::UpperQuantumNumbers(), ARTS::Var::verbosity(), Absorption::Lines::write(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [3/18]
void xml_write_to_stream (ostream & os_xml, const Index & index, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Index to XML output stream.
Parameters
os_xml XML Output stream
index Index value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 77 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [4/18]
void xml_write_to_stream (ostream & os_xml, const JacobianTarget & jt, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes JacobianTarget to XML output stream.
Parameters
os_xml XML Output stream
jt JacobianTarget value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Catalog ID
Definition at line 183 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), get_tag_group_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [5/18]
void xml_write_to_stream (ostream & os_xml, const Matrix & matrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Matrix to XML output stream.
Parameters
os_xml XML Output stream
matrix Matrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 286 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), c, ConstMatrixView::ncols(), ConstMatrixView::nrows(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [6/18]
void xml_write_to_stream (ostream & os_xml, const Numeric & numeric, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Numeric to XML output stream.
Parameters
os_xml XML Output stream
numeric Numeric value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 367 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [7/18]
void xml_write_to_stream (ostream & os_xml, const RadiationVector & rv, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes RadiationVector to XML output stream.
Parameters
os_xml XML Output stream
rv RadiationVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1549 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), RadiationVector::Frequencies(), ArtsXMLTag::set_name(), RadiationVector::StokesDim(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [8/18]
void xml_write_to_stream (ostream & os_xml, const Rational & rational, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Rational to XML output stream.
Parameters
os_xml XML Output stream
rational Rational value
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 432 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [9/18]
void xml_write_to_stream (ostream & os_xml, const Sparse & sparse, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Sparse to XML output stream.
Parameters
os_xml XML Output stream
sparse Sparse
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 569 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), data, Sparse::list_elements(), Sparse::ncols(), Sparse::nnz(), Sparse::nrows(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [10/18]
void xml_write_to_stream (ostream & os_xml, const String & str, bofstream * , const String & name, const Verbosity & verbosity)
Writes String to XML output stream.
Parameters
os_xml XML Output stream
str String value
name Optional name attribute
Definition at line 725 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [11/18]
void xml_write_to_stream (ostream & os_xml, const Tensor3 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor3 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 805 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), c, ConstTensor3View::ncols(), ConstTensor3View::npages(), ConstTensor3View::nrows(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [12/18]
void xml_write_to_stream (ostream & os_xml, const Tensor4 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor4 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 910 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), b, c, ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [13/18]
void xml_write_to_stream (ostream & os_xml, const Tensor5 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor5 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1023 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), b, c, ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), ConstTensor5View::nshelves(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [14/18]
void xml_write_to_stream (ostream & os_xml, const Tensor6 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor6 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1142 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), b, c, ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), ConstTensor6View::nvitrines(), ArtsXMLTag::set_name(), v, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [15/18]
void xml_write_to_stream (ostream & os_xml, const Tensor7 & tensor, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Tensor7 to XML output stream.
Parameters
os_xml XML Output stream
tensor Tensor
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1269 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), b, c, Interpolation::l(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), ArtsXMLTag::set_name(), v, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [16/18]
void xml_write_to_stream (ostream & os_xml, const Time & t, bofstream *pbofs] [[maybe_unused], const String & , const Verbosity & verbosity)
Writes Time to XML output stream.
Parameters
os_xml XML Output stream
t Time
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute (ignored)
Definition at line 1615 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), Time::Version(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [17/18]
void xml_write_to_stream (ostream & os_xml, const TransmissionMatrix & tm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes RadiationVector to XML output stream.
Parameters
os_xml XML Output stream
tm TransmissionMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1473 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), TransmissionMatrix::Frequencies(), ArtsXMLTag::set_name(), TransmissionMatrix::StokesDim(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().
xml_write_to_stream() [18/18]
void xml_write_to_stream (ostream & os_xml, const Vector & vector, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Vector to XML output stream.
Parameters
os_xml XML Output stream
vector Vector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1391 of file xml_io_basic_types.cc.
References ArtsXMLTag::add_attribute(), ConstVectorView::nelem(), ArtsXMLTag::set_name(), v, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_set_stream_precision().