ARTS: xml_io_compound_types.cc File Reference
xml_io_compound_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "cloudbox.h"
#include "xml_io.h"
#include "global_data.h"
Functions
void xml_read_from_stream (istream &is_xml, CIARecord &cr, bifstream *pbifs, const Verbosity &verbosity)
Reads CIARecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const CIARecord &cr, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes CIARecord to XML output stream.
void xml_read_from_stream (istream &is_xml, CovarianceMatrix &covmat, bifstream *pbifs, const Verbosity &verbosity)
Reads CovarianceMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const CovarianceMatrix &covmat, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Write CovarianceMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, EnergyLevelMap &elm, bifstream *pbifs, const Verbosity &verbosity)
Reads EnergyLevelMap from XML input stream.
void xml_write_to_stream (ostream &os_xml, const EnergyLevelMap &elm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes EnergyLevelMap to XML output stream.
void xml_read_from_stream (istream &is_xml, GasAbsLookup &gal, bifstream *pbifs, const Verbosity &verbosity)
Reads GasAbsLookup from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GasAbsLookup &gal, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GasAbsLookup to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads the grids for gridded fields from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField &gfield, bofstream *pbofs, const String &, const Verbosity &verbosity)
Writes the grids for gridded fields to an XML input stream.
void xml_read_from_stream (istream &is_xml, GriddedField1 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField1 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField2 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField2 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField2 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField3 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField3 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField4 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField4 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField4 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField5 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField5 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField5 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField5 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField6 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField6 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField6 to XML output stream.
void xml_read_from_stream (istream &is_xml, GridPos &gpos, bifstream *pbifs, const Verbosity &verbosity)
Reads GridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GridPos &gpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, HitranRelaxationMatrixData &hitran, bifstream *pbifs, const Verbosity &verbosity)
Reads HitranRelaxationMatrixData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const HitranRelaxationMatrixData &hitran, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes HitranRelaxationMatrixData to XML output stream.
void xml_read_from_stream (istream &is_xml, IsotopologueRecord &irecord, bifstream *pbifs, const Verbosity &verbosity)
Reads IsotopologueRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const IsotopologueRecord &irecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes IsotopologueRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, Ppath &ppath, bifstream *pbifs, const Verbosity &verbosity)
Reads Ppath from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Ppath &ppath, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Ppath to XML output stream.
void xml_read_from_stream (istream &is_xml, PropagationMatrix &pm, bifstream *pbifs, const Verbosity &verbosity)
Reads PropagationMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const PropagationMatrix &pm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes PropagationMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, QuantumIdentifier &qi, bifstream *pbifs, const Verbosity &verbosity)
Reads QuantumIdentifier from XML input stream.
void xml_write_to_stream (ostream &os_xml, const QuantumIdentifier &qi, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes QuantumIdentifier to XML output stream.
void xml_read_from_stream (istream &is_xml, QuantumNumbers &qn, bifstream *pbifs, const Verbosity &verbosity)
Reads QuantumNumbers from XML input stream.
void xml_write_to_stream (ostream &os_xml, const QuantumNumbers &qn, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes QuantumNumbers to XML output stream.
void xml_read_from_stream (istream &is_xml, RetrievalQuantity &rq, bifstream *pbifs, const Verbosity &verbosity)
Reads RetrievalQuantity from XML input stream.
void xml_write_to_stream (ostream &os_xml, const RetrievalQuantity &rq, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes RetrievalQuantity to XML output stream.
void xml_read_from_stream (istream &is_xml, SingleScatteringData &ssdata, bifstream *pbifs, const Verbosity &verbosity)
Reads SingleScatteringData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SingleScatteringData &ssdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SingleScatteringData to XML output stream.
void xml_read_from_stream (istream &is_xml, ScatteringMetaData &smdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ScatteringMetaData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ScatteringMetaData &smdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ScatteringMetaData to XML output stream.
void xml_read_from_stream (istream &is_xml, SLIData2 &slidata, bifstream *pbifs, const Verbosity &verbosity)
Reads SLIData2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SLIData2 &slidata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
void xml_read_from_stream (istream &is_xml, SpeciesAuxData &sad, bifstream *pbifs, const Verbosity &verbosity)
Reads SpeciesAuxData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SpeciesAuxData &sad, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SpeciesAuxData to XML output stream.
void xml_read_from_stream (istream &is_xml, SpeciesRecord &srecord, bifstream *pbifs, const Verbosity &verbosity)
Reads SpeciesRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SpeciesRecord &srecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SpeciesRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, SpeciesTag &stag, bifstream *, const Verbosity &verbosity)
Reads SpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SpeciesTag &stag, bofstream *, const String &name, const Verbosity &verbosity)
Writes SpeciesTag to XML output stream.
void xml_read_from_stream (istream &is_xml, StokesVector &sv, bifstream *pbifs, const Verbosity &verbosity)
Reads StokesVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const StokesVector &sv, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes StokesVector to XML output stream.
void xml_read_from_stream (istream &is_xml, TelsemAtlas &ta, bifstream *pbifs, const Verbosity &verbosity)
Reads TelsemAtlas from XML input stream.
void xml_write_to_stream (ostream &os_xml, const TelsemAtlas &ta, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes TelsemAtlas to XML output stream.
void xml_read_from_stream (istream &is_xml, XsecRecord &xd, bifstream *pbifs, const Verbosity &verbosity)
Reads XsecData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const XsecRecord &xd, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes XsecData to XML output stream.
void xml_read_from_stream (istream &, Agenda &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const Agenda &, bofstream *, const String &, const Verbosity &)
void xml_read_from_stream (istream &, MCAntenna &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const MCAntenna &, bofstream *, const String &, const Verbosity &)
void xml_read_from_stream (istream &, TessemNN &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const TessemNN &, bofstream *, const String &, const Verbosity &)
void xml_read_from_stream (istream &, Verbosity &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const Verbosity &, bofstream *, const String &, const Verbosity &)
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_compound_types.cc.
Function Documentation
xml_read_from_stream() [1/32]
void xml_read_from_stream (istream & , Agenda & , bifstream * , const Verbosity &)
Definition at line 2241 of file xml_io_compound_types.cc.
xml_read_from_stream() [2/32]
void xml_read_from_stream (istream & , MCAntenna & , bifstream * , const Verbosity &)
Definition at line 2258 of file xml_io_compound_types.cc.
xml_read_from_stream() [3/32]
void xml_read_from_stream (istream & , TessemNN & , bifstream * , const Verbosity &)
Definition at line 2275 of file xml_io_compound_types.cc.
xml_read_from_stream() [4/32]
void xml_read_from_stream (istream & , Verbosity & , bifstream * , const Verbosity &)
Definition at line 2292 of file xml_io_compound_types.cc.
xml_read_from_stream() [5/32]
void xml_read_from_stream (istream & is_xml, CIARecord & cr, bifstream * pbifs, const Verbosity & verbosity)
Reads CIARecord from XML input stream.
Parameters
is_xml XML Input stream
irecord SpeciesRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 46 of file xml_io_compound_types.cc.
Referenced by xml_read_from_stream().
xml_read_from_stream() [6/32]
void xml_read_from_stream (istream & is_xml, CovarianceMatrix & covmat, bifstream * pbifs, const Verbosity & verbosity)
Reads CovarianceMatrix from XML input stream.
Parameters
is_xml XML Input stream
covmat CovarianceMatrix
pbifs Pointer to binary file stream. NULL for ASCII output.
verbosity
Definition at line 119 of file xml_io_compound_types.cc.
xml_read_from_stream() [7/32]
void xml_read_from_stream (istream & is_xml, EnergyLevelMap & elm, bifstream * pbifs, const Verbosity & verbosity)
Reads EnergyLevelMap from XML input stream.
Parameters
is_xml XML Input stream
gal EnergyLevelMap return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 286 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), EnergyLevelMap::Data(), EnergyLevelMap::Energies(), ArtsXMLTag::get_attribute_value(), EnergyLevelMap::Levels(), ArtsXMLTag::read_from_stream(), string2energylevelmaptype(), EnergyLevelMap::ThrowIfNotOK(), EnergyLevelMap::Type(), Hitran::type, ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [8/32]
void xml_read_from_stream (istream & is_xml, GasAbsLookup & gal, bifstream * pbifs, const Verbosity & verbosity)
Reads GasAbsLookup from XML input stream.
Parameters
is_xml XML Input stream
gal GasAbsLookup return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 346 of file xml_io_compound_types.cc.
xml_read_from_stream() [9/32]
void xml_read_from_stream (istream & is_xml, GriddedField & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads the grids for gridded fields from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 420 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), GriddedField::get_dim(), ArtsXMLTag::get_name(), ArtsXMLTag::read_from_stream(), GriddedField::set_grid(), GriddedField::set_grid_name(), v, ARTS::Var::verbosity(), xml_parse_error(), and xml_parse_from_stream().
xml_read_from_stream() [10/32]
void xml_read_from_stream (istream & is_xml, GriddedField1 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 507 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField1::checksize_strict(), GriddedField1::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [11/32]
void xml_read_from_stream (istream & is_xml, GriddedField2 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField2 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField2 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 569 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField2::checksize_strict(), GriddedField2::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [12/32]
void xml_read_from_stream (istream & is_xml, GriddedField3 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 631 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField3::checksize_strict(), GriddedField3::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [13/32]
void xml_read_from_stream (istream & is_xml, GriddedField4 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField4 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 693 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField4::checksize_strict(), GriddedField4::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [14/32]
void xml_read_from_stream (istream & is_xml, GriddedField5 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField5 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField5 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 755 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField5::checksize_strict(), GriddedField5::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [15/32]
void xml_read_from_stream (istream & is_xml, GriddedField6 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField6 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 817 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField6::checksize_strict(), GriddedField6::data, ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [16/32]
void xml_read_from_stream (istream & is_xml, GridPos & gpos, bifstream * pbifs, const Verbosity & verbosity)
Reads GridPos from XML input stream.
Parameters
is_xml XML Input stream
gpos GridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 879 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GridPos::fd, GridPos::idx, ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [17/32]
void xml_read_from_stream (istream & is_xml, HitranRelaxationMatrixData & hitran, bifstream * pbifs, const Verbosity & verbosity)
Reads HitranRelaxationMatrixData from XML input stream.
Parameters
is_xml XML Input stream
hitran HitranRelaxationMatrixData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 938 of file xml_io_compound_types.cc.
References HitranRelaxationMatrixData::B0pp, HitranRelaxationMatrixData::B0pq, HitranRelaxationMatrixData::B0pr, HitranRelaxationMatrixData::B0qp, HitranRelaxationMatrixData::B0qq, HitranRelaxationMatrixData::B0qr, HitranRelaxationMatrixData::B0rp, HitranRelaxationMatrixData::B0rq, HitranRelaxationMatrixData::B0rr, ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), HitranRelaxationMatrixData::W0pp, HitranRelaxationMatrixData::W0pq, HitranRelaxationMatrixData::W0pr, HitranRelaxationMatrixData::W0qp, HitranRelaxationMatrixData::W0qq, HitranRelaxationMatrixData::W0qr, HitranRelaxationMatrixData::W0rp, HitranRelaxationMatrixData::W0rq, HitranRelaxationMatrixData::W0rr, and xml_read_from_stream().
xml_read_from_stream() [18/32]
void xml_read_from_stream (istream & is_xml, IsotopologueRecord & irecord, bifstream * pbifs, const Verbosity & verbosity)
Reads IsotopologueRecord from XML input stream.
Parameters
is_xml XML Input stream
irecord SpeciesRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1022 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), LineShape::mass(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [19/32]
void xml_read_from_stream (istream & is_xml, Ppath & ppath, bifstream * pbifs, const Verbosity & verbosity)
Reads Ppath from XML input stream.
Parameters
is_xml XML Input stream
ppath Ppath return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1090 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [20/32]
void xml_read_from_stream (istream & is_xml, PropagationMatrix & pm, bifstream * pbifs, const Verbosity & verbosity)
Reads PropagationMatrix from XML input stream.
Parameters
is_xml XML Input stream
pm PropagationMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1199 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), d, PropagationMatrix::Data(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [21/32]
void xml_read_from_stream (istream & is_xml, QuantumIdentifier & qi, bifstream * pbifs, const Verbosity & verbosity)
Reads QuantumIdentifier from XML input stream.
Parameters
is_xml XML Input stream
qi QuantumIdentifier return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1266 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), parse_xml_tag_content_as_string(), ArtsXMLTag::read_from_stream(), QuantumIdentifier::SetFromString(), and ARTS::Var::verbosity().
xml_read_from_stream() [22/32]
void xml_read_from_stream (istream & is_xml, QuantumNumbers & qn, bifstream * pbifs, const Verbosity & verbosity)
Reads QuantumNumbers from XML input stream.
Parameters
is_xml XML Input stream
qn QuantumNumbers return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1325 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), and ARTS::Var::verbosity().
xml_read_from_stream() [23/32]
void xml_read_from_stream (istream & is_xml, RetrievalQuantity & rq, bifstream * pbifs, const Verbosity & verbosity)
Reads RetrievalQuantity from XML input stream.
Parameters
is_xml XML Input stream
rq RetrievalQuantity return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1386 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [24/32]
void xml_read_from_stream (istream & is_xml, ScatteringMetaData & smdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ScatteringMetaData from XML input stream.
Parameters
is_xml XML Input stream
smdata ScatteringMetaData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1566 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ScatteringMetaData::description, ScatteringMetaData::diameter_area_equ_aerodynamical, ScatteringMetaData::diameter_max, ScatteringMetaData::diameter_volume_equ, ArtsXMLTag::get_attribute_value(), ScatteringMetaData::mass, ArtsXMLTag::read_from_stream(), ScatteringMetaData::refr_index, ScatteringMetaData::source, ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [25/32]
void xml_read_from_stream (istream & is_xml, SingleScatteringData & ssdata, bifstream * pbifs, const Verbosity & verbosity)
Reads SingleScatteringData from XML input stream.
Parameters
is_xml XML Input stream
ssdata SingleScatteringData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1451 of file xml_io_compound_types.cc.
References SingleScatteringData::aa_grid, SingleScatteringData::abs_vec_data, ArtsXMLTag::check_name(), chk_scat_data(), ConvertAzimuthallyRandomSingleScatteringData(), SingleScatteringData::description, SingleScatteringData::ext_mat_data, SingleScatteringData::f_grid, ArtsXMLTag::get_attribute_value(), ConstVectorView::nelem(), ConstTensor7View::nlibraries(), SingleScatteringData::pha_mat_data, SingleScatteringData::ptype, PType2FromString(), PTYPE_AZIMUTH_RND, PTYPE_GENERAL, PTYPE_TOTAL_RND, PTypeFromString(), ArtsXMLTag::read_from_stream(), SingleScatteringData::T_grid, ARTS::Var::verbosity(), xml_read_from_stream(), and SingleScatteringData::za_grid.
xml_read_from_stream() [26/32]
void xml_read_from_stream (istream & is_xml, SLIData2 & slidata, bifstream * pbifs, const Verbosity & verbosity)
Reads SLIData2 from XML input stream.
Parameters
is_xml XML Input stream
slidata SLIData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1639 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), SLIData2::x1a, SLIData2::x2a, xml_read_from_stream(), and SLIData2::ya.
xml_read_from_stream() [27/32]
void xml_read_from_stream (istream & is_xml, SpeciesAuxData & sad, bifstream * pbifs, const Verbosity & verbosity)
Reads SpeciesAuxData from XML input stream.
Parameters
is_xml XML Input stream
sap SpeciesAuxData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1685 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), CREATE_OUT2, find_first(), ArtsXMLTag::get_attribute_value(), SpeciesAuxData::InitFromSpeciesData(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), SpeciesAuxData::ReadFromStream(), and ARTS::Var::verbosity().
xml_read_from_stream() [28/32]
void xml_read_from_stream (istream & is_xml, SpeciesRecord & srecord, bifstream * pbifs, const Verbosity & verbosity)
Reads SpeciesRecord from XML input stream.
Parameters
is_xml XML Input stream
srecord SpeciesRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1838 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [29/32]
void xml_read_from_stream (istream & is_xml, SpeciesTag & stag, bifstream * , const Verbosity & verbosity)
Reads SpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
stag SpeciesTag return value
Definition at line 1898 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_error().
xml_read_from_stream() [30/32]
void xml_read_from_stream (istream & is_xml, StokesVector & sv, bifstream * pbifs, const Verbosity & verbosity)
Reads StokesVector from XML input stream.
Parameters
is_xml XML Input stream
sv StokesVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1979 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), d, PropagationMatrix::Data(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [31/32]
void xml_read_from_stream (istream & is_xml, TelsemAtlas & ta, bifstream * pbifs, const Verbosity & verbosity)
Reads TelsemAtlas from XML input stream.
Parameters
is_xml XML Input stream
pm TelsemAtlas return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2046 of file xml_io_compound_types.cc.
xml_read_from_stream() [32/32]
void xml_read_from_stream (istream & is_xml, XsecRecord & xd, bifstream * pbifs, const Verbosity & verbosity)
Reads XsecData from XML input stream.
Parameters
is_xml XML Input stream
xd XsecData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2116 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), CREATE_OUT2, XsecRecord::mcoeffs, XsecRecord::mfgrids, XsecRecord::mrefpressure, XsecRecord::mreftemperature, XsecRecord::mspecies, XsecRecord::mtintersect, XsecRecord::mtslope, XsecRecord::mxsecs, Array< base >::nelem(), nlinspace(), ArtsXMLTag::read_from_stream(), species_index_from_species_name(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_write_to_stream() [1/32]
void xml_write_to_stream (ostream & , const Agenda & , bofstream * , const String & , const Verbosity &)
Definition at line 2248 of file xml_io_compound_types.cc.
xml_write_to_stream() [2/32]
void xml_write_to_stream (ostream & , const MCAntenna & , bofstream * , const String & , const Verbosity &)
Definition at line 2265 of file xml_io_compound_types.cc.
xml_write_to_stream() [3/32]
void xml_write_to_stream (ostream & , const TessemNN & , bofstream * , const String & , const Verbosity &)
Definition at line 2282 of file xml_io_compound_types.cc.
xml_write_to_stream() [4/32]
void xml_write_to_stream (ostream & , const Verbosity & , bofstream * , const String & , const Verbosity &)
Definition at line 2299 of file xml_io_compound_types.cc.
xml_write_to_stream() [5/32]
void xml_write_to_stream (ostream & os_xml, const CIARecord & cr, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes CIARecord to XML output stream.
Parameters
os_xml XML Output stream
irecord CIARecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 91 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), CIARecord::Data(), CIARecord::MoleculeName(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
Referenced by xml_write_to_stream().
xml_write_to_stream() [6/32]
void xml_write_to_stream (ostream & os_xml, const CovarianceMatrix & covmat, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Write CovarianceMatrix to XML output stream.
Parameters
os_xml XML output stream
covmat CovarianceMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Unused
verbosity
Definition at line 198 of file xml_io_compound_types.cc.
xml_write_to_stream() [7/32]
void xml_write_to_stream (ostream & os_xml, const EnergyLevelMap & elm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes EnergyLevelMap to XML output stream.
Parameters
os_xml XML Output stream
gal EnergyLevelMap
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 316 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), EnergyLevelMap::Data(), EnergyLevelMap::Energies(), energylevelmaptype2string(), EnergyLevelMap::Levels(), ArtsXMLTag::set_name(), EnergyLevelMap::Type(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [8/32]
void xml_write_to_stream (ostream & os_xml, const GasAbsLookup & gal, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GasAbsLookup to XML output stream.
Parameters
os_xml XML Output stream
gal GasAbsLookup
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 376 of file xml_io_compound_types.cc.
xml_write_to_stream() [9/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField & gfield, bofstream * pbofs, const String & , const Verbosity & verbosity)
Writes the grids for gridded fields to an XML input stream.
Parameters
os_xml XML output stream
gfield GriddedField with the grids
pbofs Pointer to binary output stream. NULL in case of ASCII file.
Definition at line 474 of file xml_io_compound_types.cc.
References GriddedField::get_dim(), GriddedField::get_grid_name(), GriddedField::get_grid_type(), GriddedField::get_numeric_grid(), GriddedField::get_string_grid(), GRID_TYPE_NUMERIC, GRID_TYPE_STRING, ARTS::Var::verbosity(), and xml_write_to_stream().
xml_write_to_stream() [10/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField1 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 536 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField1::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [11/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField2 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField2 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField2
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 598 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField2::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [12/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField3 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 660 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField3::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [13/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField4 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField4 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 722 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField4::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [14/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField5 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField5 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField5
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 784 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField5::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [15/32]
void xml_write_to_stream (ostream & os_xml, const GriddedField6 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField6 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField6
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 846 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField6::data, GriddedField::get_name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [16/32]
void xml_write_to_stream (ostream & os_xml, const GridPos & gpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GridPos to XML output stream.
Parameters
os_xml XML Output stream
gpos GridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 903 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GridPos::fd, GridPos::idx, ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [17/32]
void xml_write_to_stream (ostream & os_xml, const HitranRelaxationMatrixData & hitran, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes HitranRelaxationMatrixData to XML output stream.
Parameters
os_xml XML Output stream
hitran HitranRelaxationMatrixData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 977 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), HitranRelaxationMatrixData::B0pp, HitranRelaxationMatrixData::B0pq, HitranRelaxationMatrixData::B0pr, HitranRelaxationMatrixData::B0qp, HitranRelaxationMatrixData::B0qq, HitranRelaxationMatrixData::B0qr, HitranRelaxationMatrixData::B0rp, HitranRelaxationMatrixData::B0rq, HitranRelaxationMatrixData::B0rr, ArtsXMLTag::set_name(), ARTS::Var::verbosity(), HitranRelaxationMatrixData::W0pp, HitranRelaxationMatrixData::W0pq, HitranRelaxationMatrixData::W0pr, HitranRelaxationMatrixData::W0qp, HitranRelaxationMatrixData::W0qq, HitranRelaxationMatrixData::W0qr, HitranRelaxationMatrixData::W0rp, HitranRelaxationMatrixData::W0rq, HitranRelaxationMatrixData::W0rr, ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [18/32]
void xml_write_to_stream (ostream & os_xml, const IsotopologueRecord & irecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes IsotopologueRecord to XML output stream.
Parameters
os_xml XML Output stream
irecord IsotopologueRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1056 of file xml_io_compound_types.cc.
References IsotopologueRecord::Abundance(), ArtsXMLTag::add_attribute(), IsotopologueRecord::JplTags(), IsotopologueRecord::Mass(), IsotopologueRecord::MytranTag(), IsotopologueRecord::Name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [19/32]
void xml_write_to_stream (ostream & os_xml, const Ppath & ppath, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Ppath to XML output stream.
Parameters
os_xml XML Output stream
ppath Ppath
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1130 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), ARTS::Var::Ppath::pos(), ARTS::Var::ppath(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [20/32]
void xml_write_to_stream (ostream & os_xml, const PropagationMatrix & pm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes PropagationMatrix to XML output stream.
Parameters
os_xml XML Output stream
pm PropagationMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1236 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), PropagationMatrix::Data(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [21/32]
void xml_write_to_stream (ostream & os_xml, const QuantumIdentifier & qi, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes QuantumIdentifier to XML output stream.
Parameters
os_xml XML Output stream
qi QuantumIdentifier
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1298 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [22/32]
void xml_write_to_stream (ostream & os_xml, const QuantumNumbers & qn, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes QuantumNumbers to XML output stream.
Parameters
os_xml XML Output stream
qn QuantumNumbers
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1359 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), QuantumNumbers::GetNumbers(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [23/32]
void xml_write_to_stream (ostream & os_xml, const RetrievalQuantity & rq, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes RetrievalQuantity to XML output stream.
Parameters
os_xml XML Output stream
rq RetrievalQuantity
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1420 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), RetrievalQuantity::Grids(), RetrievalQuantity::Mode(), ArtsXMLTag::set_name(), RetrievalQuantity::SubSubtag(), RetrievalQuantity::Subtag(), RetrievalQuantity::Target(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [24/32]
void xml_write_to_stream (ostream & os_xml, const ScatteringMetaData & smdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ScatteringMetaData to XML output stream.
Parameters
os_xml XML Output stream
smdata ScatteringMetaData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1604 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), ScatteringMetaData::description, ScatteringMetaData::diameter_area_equ_aerodynamical, ScatteringMetaData::diameter_max, ScatteringMetaData::diameter_volume_equ, ScatteringMetaData::mass, ScatteringMetaData::refr_index, ArtsXMLTag::set_name(), ScatteringMetaData::source, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [25/32]
void xml_write_to_stream (ostream & os_xml, const SingleScatteringData & ssdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SingleScatteringData to XML output stream.
Parameters
os_xml XML Output stream
ssdata SingleScatteringData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1528 of file xml_io_compound_types.cc.
References SingleScatteringData::aa_grid, SingleScatteringData::abs_vec_data, ArtsXMLTag::add_attribute(), SingleScatteringData::description, SingleScatteringData::ext_mat_data, SingleScatteringData::f_grid, SingleScatteringData::pha_mat_data, SingleScatteringData::ptype, PTypeToString(), ArtsXMLTag::set_name(), SingleScatteringData::T_grid, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), xml_write_to_stream(), and SingleScatteringData::za_grid.
xml_write_to_stream() [26/32]
void xml_write_to_stream (ostream & os_xml, const SLIData2 & slidata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Definition at line 1656 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), SLIData2::x1a, SLIData2::x2a, xml_write_to_stream(), and SLIData2::ya.
xml_write_to_stream() [27/32]
void xml_write_to_stream (ostream & os_xml, const SpeciesAuxData & sad, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SpeciesAuxData to XML output stream.
Parameters
os_xml XML Output stream
sap SpeciesAuxData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1780 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), SpeciesAuxData::getParam(), SpeciesAuxData::getTypeString(), iso(), Array< base >::nelem(), Absorption::nelem(), SpeciesAuxData::nisotopologues(), SpeciesAuxData::nspecies(), ArtsXMLTag::set_name(), global_data::species_data, ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), xml_set_stream_precision(), and xml_write_to_stream().
xml_write_to_stream() [28/32]
void xml_write_to_stream (ostream & os_xml, const SpeciesRecord & srecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SpeciesRecord to XML output stream.
Parameters
os_xml XML Output stream
srecord SpeciesRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1867 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), SpeciesRecord::Degfr(), SpeciesRecord::Isotopologue(), SpeciesRecord::Name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [29/32]
void xml_write_to_stream (ostream & os_xml, const SpeciesTag & stag, bofstream * , const String & name, const Verbosity & verbosity)
Writes SpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
stag SpeciesTag
name Optional name attribute
Definition at line 1952 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), SpeciesTag::Name(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [30/32]
void xml_write_to_stream (ostream & os_xml, const StokesVector & sv, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes StokesVector to XML output stream.
Parameters
os_xml XML Output stream
sv StokesVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2016 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), PropagationMatrix::Data(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [31/32]
void xml_write_to_stream (ostream & os_xml, const TelsemAtlas & ta, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes TelsemAtlas to XML output stream.
Parameters
os_xml XML Output stream
pm TelsemAtlas
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2078 of file xml_io_compound_types.cc.
xml_write_to_stream() [32/32]
void xml_write_to_stream (ostream & os_xml, const XsecRecord & xd, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes XsecData to XML output stream.
Parameters
os_xml XML Output stream
xd XsecData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2196 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), XsecRecord::Coeffs(), XsecRecord::Fgrids(), Array< base >::nelem(), ConstVectorView::nelem(), XsecRecord::RefPressure(), XsecRecord::RefTemperature(), ArtsXMLTag::set_name(), XsecRecord::SpeciesName(), XsecRecord::TemperatureIntersect(), XsecRecord::TemperatureSlope(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), xml_write_to_stream(), and XsecRecord::Xsecs().