ARTS: xml_io_array_types.cc File Reference
xml_io_array_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "xml_io.h"
Functions
void xml_read_from_stream (istream &is_xml, ArrayOfAgenda &aa, bifstream *pbifs, const Verbosity &)
Reads ArrayOfAgenda from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfAgenda &aa, bofstream *pbofs, const String &name, const Verbosity &)
Writes ArrayOfAgenda to XML output stream.
void xml_read_from_stream (istream &is_xml, Array< SpeciesRecord > &asrecord, bifstream *pbifs, const Verbosity &verbosity)
Reads SpeciesData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Array< SpeciesRecord > &asrecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SpeciesData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfSpeciesTag &aastag, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfSpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfSpeciesTag &aastag, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfSpeciesTag to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfString &aastring, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfString from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfString &aastring, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfString to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfPpath &appath, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfPpath from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfPpath &appath, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfPpath to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTensor3 &aatensor3, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTensor3 &aatensor3, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTensor6 &aatensor6, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTensor6 &aatensor6, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGridPos &agpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGridPos &agpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGridPos &aagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGridPos &aagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfArrayOfGridPos &aaagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfArrayOfGridPos &aaagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfArrayOfArrayOfGridPos &aaaagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfArrayOfArrayOfGridPos &aaaagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfJacobianTarget &ajt, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfJacobianTarget from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfJacobianTarget &ajt, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfJacobianTarget to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfIndex &aindex, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfIndex from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfIndex &aindex, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfIndex to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfIndex &aaindex, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfIndex from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfIndex &aaindex, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfIndex to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfCIARecord &acr, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfCIARecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfCIARecord &acr, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfCIARecord to XML output stream.
void xml_read_from_stream (istream &is_xml, Array< IsotopologueRecord > &airecord, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfIsotopologueRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Array< IsotopologueRecord > &airecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfIsotopologueRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfMatrix &amatrix, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfMatrix &amatrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfMatrix &aamatrix, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfMatrix &aamatrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfVector &aavector, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfVector &aaVector, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSparse &asparse, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSparse from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSparse &asparse, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSparse to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfQuantumIdentifier &aqtag, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfQuantumIdentifier from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfQuantumIdentifier &aqtag, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfQuantumIdentifier to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfRetrievalQuantity &arq, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfRetrievalQuantity from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfRetrievalQuantity &arq, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfRetrivalQuantity to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSpeciesTag &astag, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSpeciesTag &astag, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSpeciesTag to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSingleScatteringData &assdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSingleScatteringData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSingleScatteringData &assdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSingleScatteringData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfSingleScatteringData &assdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfSingleScatteringData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfSingleScatteringData &assdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfSingleScatteringData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfScatteringMetaData &asmdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfScatteringMetaData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfScatteringMetaData &asmdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfScatteringMetaData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfScatteringMetaData &asmdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfScatteringMetaData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfScatteringMetaData &asmdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfScatteringMetaData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField1 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField1 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField2 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField2 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField2 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField3 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField3 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGriddedField1 &aagfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGriddedField1 &aagfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGriddedField2 &aagfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGriddedField2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGriddedField2 &aagfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGriddedField2 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGriddedField3 &aagfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGriddedField3 &aagfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField4 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField4 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField4 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTelsemAtlas &arr_telsem, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTelsemAtlas from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTelsemAtlas &arr_telsem, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTelsemAtlas to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor3 &atensor3, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor3 &atensor3, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor4 &atensor4, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor4 &atensor4, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor4 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor5 &atensor5, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor5 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor5 &atensor5, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor5 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor6 &atensor6, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor6 &atensor6, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor7 &atensor7, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor7 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor7 &atensor7, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor6 to XML output stream.
void xml_parse_from_stream (istream &is_xml, ArrayOfString &astring, bifstream *pbifs, ArtsXMLTag &tag, const Verbosity &verbosity)
Parse ArrayOfString from XML input stream.
void xml_read_from_stream (istream &is_xml, ArrayOfString &astring, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfString from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfString &astring, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfString to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfVector &avector, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfVector &avector, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTransmissionMatrix &atm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTransmissionMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTransmissionMatrix &atm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTransmissionMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTransmissionMatrix &aatm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTransmissionMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTransmissionMatrix &aatm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTransmissionMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfRadiationVector &arv, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfRadiationVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfRadiationVector &arv, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfRadiationVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfRadiationVector &aarv, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfRadiationVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfRadiationVector &aarv, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfRadiationVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfPropagationMatrix &apm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfPropagationMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfPropagationMatrix &apm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfPropagationMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfAbsorptionLines &aal, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfAbsorptionLines from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfAbsorptionLines &aal, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfAbsorptionLines to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfAbsorptionLines &aal, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfAbsorptionLines from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfAbsorptionLines &aal, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfAbsorptionLines to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfPropagationMatrix &aapm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfPropagationMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfPropagationMatrix &aapm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfPropagationMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfStokesVector &apm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfStokesVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfStokesVector &apm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfStokesVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfStokesVector &aapm, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfStokesVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfStokesVector &aapm, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfStokesVector to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfXsecRecord &axd, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfXsecData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfXsecRecord &axd, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfXsecData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTime &at, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTime from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTime &at, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTime to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTime &at, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTime from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTime &at, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTime to XML output stream.
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_array_types.cc.
Function Documentation
xml_parse_from_stream()
void xml_parse_from_stream (istream & is_xml, ArrayOfString & astring, bifstream * pbifs, ArtsXMLTag & tag, const Verbosity & verbosity)
Parse ArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
astring ArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 2859 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ARTS::Var::verbosity(), and xml_read_from_stream().
Referenced by xml_read_from_stream().
xml_read_from_stream() [1/55]
void xml_read_from_stream (istream & is_xml, Array< IsotopologueRecord > & airecord, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfIsotopologueRecord from XML input stream.
Parameters
is_xml XML Input stream
airecord ArrayOfIsotopologueRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1081 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [2/55]
void xml_read_from_stream (istream & is_xml, Array< SpeciesRecord > & asrecord, bifstream * pbifs, const Verbosity & verbosity)
Reads SpeciesData from XML input stream.
Parameters
is_xml XML Input stream
asrecord SpeciesData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 77 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [3/55]
void xml_read_from_stream (istream & is_xml, ArrayOfAbsorptionLines & aal, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfAbsorptionLines from XML input stream.
Parameters
is_xml XML Input stream
aal ArrayOfAbsorptionLines return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3372 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [4/55]
void xml_read_from_stream (istream & is_xml, ArrayOfAgenda & aa, bifstream * pbifs, const Verbosity &)
Reads ArrayOfAgenda from XML input stream.
Parameters
is_xml XML Input stream
aa ArrayOfAgenda return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 45 of file xml_io_array_types.cc.
Referenced by xml_parse_from_stream(), xml_read_from_file(), and xml_read_from_stream().
xml_read_from_stream() [5/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfAbsorptionLines & aal, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfAbsorptionLines from XML input stream.
Parameters
is_xml XML Input stream
aal ArrayOfArrayOfAbsorptionLines return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3443 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [6/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfArrayOfArrayOfGridPos & aaaagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aaaagpos ArrayOfArrayOfArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 724 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [7/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfArrayOfGridPos & aaagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aaagpos ArrayOfArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 653 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [8/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGriddedField1 & aagfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
aagfield ArrayOfArrayOfGriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2148 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [9/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGriddedField2 & aagfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGriddedField2 from XML input stream.
Parameters
is_xml XML Input stream
aagfield ArrayOfArrayOfGriddedField2 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2219 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [10/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGriddedField3 & aagfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
aagfield ArrayOfArrayOfGriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2290 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [11/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGridPos & aagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aagpos ArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 582 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [12/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfIndex & aaindex, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfIndex from XML input stream.
Parameters
is_xml XML Input stream
aaindex ArrayOfArrayOfIndex return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 937 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [13/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfMatrix & aamatrix, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfMatrix from XML input stream.
Parameters
is_xml XML Input stream
aamatrix ArrayOfArrayOfMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1223 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [14/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfPropagationMatrix & aapm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfPropagationMatrix from XML input stream.
Parameters
is_xml XML Input stream
aapm ArrayOfArrayOfPropagationMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3514 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [15/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfRadiationVector & aarv, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfRadiationVector from XML input stream.
Parameters
is_xml XML Input stream
aaev ArrayOfArrayOfRadiationVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3230 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [16/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfScatteringMetaData & asmdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfScatteringMetaData from XML input stream.
Parameters
is_xml XML Input stream
asmdata ArrayOfArrayOfScatteringMetaData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1864 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [17/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfSingleScatteringData & assdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfSingleScatteringData from XML input stream.
Parameters
is_xml XML Input stream
assdata ArrayOfArrayOfSingleScatteringData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1722 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [18/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfSpeciesTag & aastag, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfSpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
aastag ArrayOfArrayOfSpeciesTag return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 150 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [19/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfStokesVector & aapm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfStokesVector from XML input stream.
Parameters
is_xml XML Input stream
aapm ArrayOfArrayOfStokesVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3656 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [20/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfString & aastring, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
aastring ArrayOfArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 223 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [21/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTensor3 & aatensor3, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTensor3 from XML input stream.
Parameters
is_xml XML Input stream
aatensor3 ArrayOfArrayOfTensor3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 368 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [22/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTensor6 & aatensor6, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTensor6 from XML input stream.
Parameters
is_xml XML Input stream
aatensor6 ArrayOfArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 440 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [23/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTime & at, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTime from XML input stream.
Parameters
is_xml XML Input stream
at ArrayOfArrayOfTime return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3869 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [24/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTransmissionMatrix & aatm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTransmissionMatrix from XML input stream.
Parameters
is_xml XML Input stream
aatm ArrayOfArrayOfTransmissionMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3088 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [25/55]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfVector & aavector, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfVector from XML input stream.
Parameters
is_xml XML Input stream
aaVector ArrayOfArrayOfVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1294 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [26/55]
void xml_read_from_stream (istream & is_xml, ArrayOfCIARecord & acr, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfCIARecord from XML input stream.
Parameters
is_xml XML Input stream
alspec ArrayOfCIARecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1008 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [27/55]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField1 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1935 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [28/55]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField2 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField2 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField2 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2006 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [29/55]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField3 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2077 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [30/55]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField4 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField4 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2361 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [31/55]
void xml_read_from_stream (istream & is_xml, ArrayOfGridPos & agpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
agpos ArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 511 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [32/55]
void xml_read_from_stream (istream & is_xml, ArrayOfIndex & aindex, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfIndex from XML input stream.
Parameters
is_xml XML Input stream
aindex ArrayOfIndex return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 866 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [33/55]
void xml_read_from_stream (istream & is_xml, ArrayOfJacobianTarget & ajt, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfJacobianTarget from XML input stream.
Parameters
is_xml XML Input stream
ajt ArrayOfJacobianTarget return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 795 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [34/55]
void xml_read_from_stream (istream & is_xml, ArrayOfMatrix & amatrix, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfMatrix from XML input stream.
Parameters
is_xml XML Input stream
amatrix ArrayOfMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1152 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [35/55]
void xml_read_from_stream (istream & is_xml, ArrayOfPpath & appath, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfPpath from XML input stream.
Parameters
is_xml XML Input stream
appath ArrayOfPpath return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 295 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [36/55]
void xml_read_from_stream (istream & is_xml, ArrayOfPropagationMatrix & apm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfPropagationMatrix from XML input stream.
Parameters
is_xml XML Input stream
apm ArrayOfPropagationMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3301 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [37/55]
void xml_read_from_stream (istream & is_xml, ArrayOfQuantumIdentifier & aqtag, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfQuantumIdentifier from XML input stream.
Parameters
is_xml XML Input stream
aqtag ArrayOfQuantumIdentifier return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1436 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [38/55]
void xml_read_from_stream (istream & is_xml, ArrayOfRadiationVector & arv, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfRadiationVector from XML input stream.
Parameters
is_xml XML Input stream
apm ArrayOfRadiationVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3159 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [39/55]
void xml_read_from_stream (istream & is_xml, ArrayOfRetrievalQuantity & arq, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfRetrievalQuantity from XML input stream.
Parameters
is_xml XML Input stream
arq ArrayOfRetrievalQuantity return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1509 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [40/55]
void xml_read_from_stream (istream & is_xml, ArrayOfScatteringMetaData & asmdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfScatteringMetaData from XML input stream.
Parameters
is_xml XML Input stream
asmdata ArrayOfScatteringMetaData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1793 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [41/55]
void xml_read_from_stream (istream & is_xml, ArrayOfSingleScatteringData & assdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSingleScatteringData from XML input stream.
Parameters
is_xml XML Input stream
assdata ArrayOfSingleScatteringData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1651 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [42/55]
void xml_read_from_stream (istream & is_xml, ArrayOfSparse & asparse, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSparse from XML input stream.
Parameters
is_xml XML Input stream
asparse ArrayOfSparse return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1365 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [43/55]
void xml_read_from_stream (istream & is_xml, ArrayOfSpeciesTag & astag, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
astag ArrayOfSpeciesTag return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1580 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [44/55]
void xml_read_from_stream (istream & is_xml, ArrayOfStokesVector & apm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfStokesVector from XML input stream.
Parameters
is_xml XML Input stream
apm ArrayOfStokesVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3585 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [45/55]
void xml_read_from_stream (istream & is_xml, ArrayOfString & astring, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
astring ArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2890 of file xml_io_array_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_parse_from_stream().
xml_read_from_stream() [46/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTelsemAtlas & arr_telsem, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTelsemAtlas from XML input stream.
Parameters
is_xml XML Input stream
arr_telsem ArrayOfTelsemAtlas return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2432 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [47/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor3 & atensor3, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor3 from XML input stream.
Parameters
is_xml XML Input stream
atensor3 ArrayOfTensor3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2503 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [48/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor4 & atensor4, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor4 from XML input stream.
Parameters
is_xml XML Input stream
atensor4 ArrayOfTensor4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2574 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [49/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor5 & atensor5, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor5 from XML input stream.
Parameters
is_xml XML Input stream
atensor5 ArrayOfTensor5 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2645 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [50/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor6 & atensor6, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor6 from XML input stream.
Parameters
is_xml XML Input stream
atensor6 ArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2716 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [51/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor7 & atensor7, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor7 from XML input stream.
Parameters
is_xml XML Input stream
atensor7 ArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2787 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [52/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTime & at, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTime from XML input stream.
Parameters
is_xml XML Input stream
at ArrayOfTime return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3798 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [53/55]
void xml_read_from_stream (istream & is_xml, ArrayOfTransmissionMatrix & atm, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTransmissionMatrix from XML input stream.
Parameters
is_xml XML Input stream
apm ArrayOfTransmissionMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3017 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [54/55]
void xml_read_from_stream (istream & is_xml, ArrayOfVector & avector, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfVector from XML input stream.
Parameters
is_xml XML Input stream
avector ArrayOfVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2946 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_read_from_stream() [55/55]
void xml_read_from_stream (istream & is_xml, ArrayOfXsecRecord & axd, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfXsecData from XML input stream.
Parameters
is_xml XML Input stream
axd ArrayOfXsecData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 3727 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), Absorption::nelem(), ArtsXMLTag::read_from_stream(), ARTS::Var::verbosity(), and xml_read_from_stream().
xml_write_to_stream() [1/55]
void xml_write_to_stream (ostream & os_xml, const Array< IsotopologueRecord > & airecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfIsotopologueRecord to XML output stream.
Parameters
os_xml XML Output stream
airecord ArrayOfIsotopologueRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1118 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [2/55]
void xml_write_to_stream (ostream & os_xml, const Array< SpeciesRecord > & asrecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SpeciesData to XML output stream.
Parameters
os_xml XML Output stream
asrecord SpeciesData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 115 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [3/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfAbsorptionLines & aal, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfAbsorptionLines to XML output stream.
Parameters
os_xml XML Output stream
aal ArrayOfAbsorptionLines
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3409 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [4/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfAgenda & aa, bofstream * pbofs, const String & name, const Verbosity &)
Writes ArrayOfAgenda to XML output stream.
Parameters
os_xml XML Output stream
aa ArrayOfAgenda
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 59 of file xml_io_array_types.cc.
Referenced by xml_write_to_file(), and xml_write_to_stream().
xml_write_to_stream() [5/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfAbsorptionLines & aal, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfAbsorptionLines to XML output stream.
Parameters
os_xml XML Output stream
aal ArrayOfArrayOfAbsorptionLines
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3480 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [6/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfArrayOfArrayOfGridPos & aaaagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aaaagpos ArrayOfArrayOfArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 761 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [7/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfArrayOfGridPos & aaagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aaagpos ArrayOfArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 690 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [8/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGriddedField1 & aagfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
aagfield ArrayOfArrayOfGriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2185 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [9/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGriddedField2 & aagfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGriddedField2 to XML output stream.
Parameters
os_xml XML Output stream
aagfield ArrayOfArrayOfGriddedField2
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2256 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [10/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGriddedField3 & aagfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
aagfield ArrayOfArrayOfGriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2327 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [11/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGridPos & aagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aagpos ArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 619 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [12/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfIndex & aaindex, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfIndex to XML output stream.
Parameters
os_xml XML Output stream
aaindex ArrayOfArrayOfIndex
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 974 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [13/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfMatrix & aamatrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfMatrix to XML output stream.
Parameters
os_xml XML Output stream
aamatrix ArrayOfArrayOfMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1260 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [14/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfPropagationMatrix & aapm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfPropagationMatrix to XML output stream.
Parameters
os_xml XML Output stream
aapm ArrayOfArrayOfPropagationMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3551 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [15/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfRadiationVector & aarv, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfRadiationVector to XML output stream.
Parameters
os_xml XML Output stream
aarv ArrayOfArrayOfRadiationVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3267 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [16/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfScatteringMetaData & asmdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfScatteringMetaData to XML output stream.
Parameters
os_xml XML Output stream
asmdata ArrayOfArrayOfScatteringMetaData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1901 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [17/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfSingleScatteringData & assdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfSingleScatteringData to XML output stream.
Parameters
os_xml XML Output stream
assdata ArrayOfArrayOfSingleScatteringData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1759 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [18/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfSpeciesTag & aastag, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfSpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
aastag ArrayOfArrayOfSpeciesTag
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 188 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [19/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfStokesVector & aapm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfStokesVector to XML output stream.
Parameters
os_xml XML Output stream
aapm ArrayOfArrayOfStokesVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3693 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [20/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfString & aastring, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfString to XML output stream.
Parameters
os_xml XML Output stream
aastring ArrayOfArrayOfString
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 261 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [21/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTensor3 & aatensor3, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTensor3 to XML output stream.
Parameters
os_xml XML Output stream
aatensor3 ArrayOfArrayOfTensor3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 405 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [22/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTensor6 & aatensor6, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
aatensor6 ArrayOfArrayOfTensor6
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 477 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [23/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTime & at, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTime to XML output stream.
Parameters
os_xml XML Output stream
at ArrayOfArrayOfTime
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3906 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [24/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTransmissionMatrix & aatm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTransmissionMatrix to XML output stream.
Parameters
os_xml XML Output stream
aatm ArrayOfArrayOfTransmissionMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3125 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [25/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfVector & aaVector, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfVector to XML output stream.
Parameters
os_xml XML Output stream
aaVector ArrayOfArrayOfVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1331 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [26/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfCIARecord & acr, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfCIARecord to XML output stream.
Parameters
os_xml XML Output stream
alspec ArrayOfCIARecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1045 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [27/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField1 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1972 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [28/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField2 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField2 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField2
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2043 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [29/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField3 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2114 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [30/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField4 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField4 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2398 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [31/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGridPos & agpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
agpos ArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 548 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [32/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfIndex & aindex, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfIndex to XML output stream.
Parameters
os_xml XML Output stream
aindex ArrayOfIndex
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 903 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [33/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfJacobianTarget & ajt, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfJacobianTarget to XML output stream.
Parameters
os_xml XML Output stream
ajt ArrayOfJacobianTarget
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 832 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [34/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfMatrix & amatrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfMatrix to XML output stream.
Parameters
os_xml XML Output stream
amatrix ArrayOfMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1189 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [35/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfPpath & appath, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfPpath to XML output stream.
Parameters
os_xml XML Output stream
appath ArrayOfPpath
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 333 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [36/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfPropagationMatrix & apm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfPropagationMatrix to XML output stream.
Parameters
os_xml XML Output stream
apm ArrayOfPropagationMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3338 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [37/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfQuantumIdentifier & aqtag, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfQuantumIdentifier to XML output stream.
Parameters
os_xml XML Output stream
aqtag ArrayOfQuantumIdentifier
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1475 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [38/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfRadiationVector & arv, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfRadiationVector to XML output stream.
Parameters
os_xml XML Output stream
arv ArrayOfRadiationVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3196 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [39/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfRetrievalQuantity & arq, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfRetrivalQuantity to XML output stream.
Parameters
os_xml XML Output stream
arq ArrayOfRetrievalQuantity
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1546 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [40/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfScatteringMetaData & asmdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfScatteringMetaData to XML output stream.
Parameters
os_xml XML Output stream
asmdata ArrayOfScatteringMetaData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1830 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [41/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSingleScatteringData & assdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSingleScatteringData to XML output stream.
Parameters
os_xml XML Output stream
assdata ArrayOfSingleScatteringData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1688 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [42/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSparse & asparse, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSparse to XML output stream.
Parameters
os_xml XML Output stream
asparse ArrayOfSparse
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1402 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [43/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSpeciesTag & astag, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
astag ArrayOfSpeciesTag
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1617 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [44/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfStokesVector & apm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfStokesVector to XML output stream.
Parameters
os_xml XML Output stream
apm ArrayOfStokesVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3622 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [45/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfString & astring, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfString to XML output stream.
Parameters
os_xml XML Output stream
astring ArrayOfString
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2912 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [46/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTelsemAtlas & arr_telsem, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTelsemAtlas to XML output stream.
Parameters
os_xml XML Output stream
atensor3 ArrayOfTelsemAtlas
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2469 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [47/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor3 & atensor3, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor3 to XML output stream.
Parameters
os_xml XML Output stream
atensor3 ArrayOfTensor3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2540 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [48/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor4 & atensor4, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor4 to XML output stream.
Parameters
os_xml XML Output stream
atensor4 ArrayOfTensor4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2611 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [49/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor5 & atensor5, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor5 to XML output stream.
Parameters
os_xml XML Output stream
atensor5 ArrayOfTensor5
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2682 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [50/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor6 & atensor6, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
atensor6 ArrayOfTensor6
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2753 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [51/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor7 & atensor7, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
atensor7 ArrayOfTensor7
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2824 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [52/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTime & at, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTime to XML output stream.
Parameters
os_xml XML Output stream
at ArrayOfTime
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3835 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [53/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTransmissionMatrix & atm, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTransmissionMatrix to XML output stream.
Parameters
os_xml XML Output stream
apm ArrayOfTransmissionMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3054 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [54/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfVector & avector, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfVector to XML output stream.
Parameters
os_xml XML Output stream
avector ArrayOfVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2983 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [55/55]
void xml_write_to_stream (ostream & os_xml, const ArrayOfXsecRecord & axd, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfXsecData to XML output stream.
Parameters
os_xml XML Output stream
axd ArrayOfXsecData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 3764 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ARTS::Var::verbosity(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().