ARTS: zeemandata.cc File Reference
zeemandata.cc File Reference
Implementations of Zeeman modeling.
#include "zeemandata.h"
#include "abs_species_tags.h"
#include "species_info.h"
Namespaces
Zeeman
Implements Zeeman modeling.
Functions
Numeric case_b_g_coefficient_o2 (Rational j, Rational n, Numeric GS, Numeric GR, Numeric GLE, Numeric B, Numeric D, Numeric H, Numeric gB, Numeric gD, Numeric gH, Numeric lB, Numeric lD, Numeric lH)
constexpr Numeric closed_shell_trilinear (Rational k, Rational j, Numeric gperp, Numeric gpara)
Eigen::Vector3d los_xyz_by_uvw_local (Numeric u, Numeric v, Numeric w)
Eigen::Vector3d los_xyz_by_za_local (Numeric z, Numeric a)
Eigen::Vector3d ev_xyz_by_za_local (Numeric z, Numeric a)
std::ostream & Zeeman::operator<< (std::ostream &os, const Model &m)
std::istream & Zeeman::operator>> (std::istream &is, Model &m)
std::ostream & Zeeman::operator<< (bofstream &bof, const Model &m)
std::istream & Zeeman::operator>> (bifstream &bif, Model &m)
AllPolarizationVectors Zeeman::AllPolarization (Numeric theta, Numeric eta) noexcept
Computes the polarization of each polarization type.
AllPolarizationVectors Zeeman::AllPolarization_dtheta (Numeric theta, const Numeric eta) noexcept
The derivative of AllPolarization wrt theta.
AllPolarizationVectors Zeeman::AllPolarization_deta (Numeric theta, Numeric eta) noexcept
The derivative of AllPolarization wrt eta.
const PolarizationVector & Zeeman::SelectPolarization (const AllPolarizationVectors &data, Polarization type) noexcept
Selects the polarization vector depending on polarization type.
void Zeeman::sum (PropagationMatrix &pm, const ComplexVectorView &abs, const PolarizationVector &polvec, const bool do_phase=true) ARTS_NOEXCEPT
Sums the Zeeman components into a propagation matrix.
void Zeeman::dsum (PropagationMatrix &dpm, const ComplexVectorView &abs, const ComplexVectorView &dabs, const PolarizationVector &polvec, const PolarizationVector &dpolvec_dtheta, const PolarizationVector &dpolvec_deta, const Numeric dH, const Numeric dtheta, const Numeric deta, const bool do_phase=true) ARTS_NOEXCEPT
Sums the Zeeman components derivatives into a propagation matrix.
Detailed Description
Implementations of Zeeman modeling.
Author
Richard Larsson <larsson (at) mps.mpg.de>
Date
2018-04-06
This file serves to implement Zeeman splitting using various up-to-speed methods
Definition in file zeemandata.cc.
Function Documentation
case_b_g_coefficient_o2()
Numeric case_b_g_coefficient_o2 (Rational j, Rational n, Numeric GS, Numeric GR, Numeric GLE, Numeric B, Numeric D, Numeric H, Numeric gB, Numeric gD, Numeric gH, Numeric lB, Numeric lD, Numeric lH)
Definition at line 41 of file zeemandata.cc.
References ARTS::Species::H, Rational::isUndefined(), Constant::pow2(), Constant::pow3(), sqrt(), and Rational::toNumeric().
closed_shell_trilinear()
constexpr Numeric closed_shell_trilinear (Rational k, Rational j, Numeric gperp, Numeric gpara) constexpr
Definition at line 94 of file zeemandata.cc.
ev_xyz_by_za_local()
Eigen::Vector3d ev_xyz_by_za_local (Numeric z, Numeric a)
Definition at line 222 of file zeemandata.cc.
References a.
Referenced by Zeeman::FromGrids().
los_xyz_by_uvw_local()
Eigen::Vector3d los_xyz_by_uvw_local (Numeric u, Numeric v, Numeric w)
Definition at line 210 of file zeemandata.cc.
References u, v, and w().
Referenced by Zeeman::FromGrids().
los_xyz_by_za_local()
Eigen::Vector3d los_xyz_by_za_local (Numeric z, Numeric a)
Definition at line 215 of file zeemandata.cc.
References a.
Referenced by Zeeman::FromGrids().