ARTS: zeeman.h File Reference
zeeman.h File Reference
#include "abs_species_tags.h"
#include "global_data.h"
#include "physics_funcs.h"
#include "quantum.h"
#include "rte.h"
Functions
void zeeman_on_the_fly (ArrayOfPropagationMatrix &propmat_clearsky, ArrayOfStokesVector &nlte_source, ArrayOfPropagationMatrix &dpropmat_clearsky_dx, ArrayOfStokesVector &dnlte_dx_source, ArrayOfStokesVector &nlte_dsource_dx, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const SpeciesAuxData &isotopologue_ratios, const SpeciesAuxData &partition_functions, const Vector &f_grid, const Vector &rtp_vmr, const EnergyLevelMap &rtp_nlte, const Vector &rtp_mag, const Vector &rtp_los, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const Index &manual_tag, const Numeric &H0, const Numeric &theta0, const Numeric &eta0)
Main and only way to compute Zeeman effect.
Function Documentation
zeeman_on_the_fly()
void zeeman_on_the_fly (ArrayOfPropagationMatrix & propmat_clearsky, ArrayOfStokesVector & nlte_source, ArrayOfPropagationMatrix & dpropmat_clearsky_dx, ArrayOfStokesVector & dnlte_dx_source, ArrayOfStokesVector & nlte_dsource_dx, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const SpeciesAuxData & isotopologue_ratios, const SpeciesAuxData & partition_functions, const Vector & f_grid, const Vector & rtp_vmr, const EnergyLevelMap & rtp_nlte, const Vector & rtp_mag, const Vector & rtp_los, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const Index & manual_tag, const Numeric & H0, const Numeric & theta0, const Numeric & eta0)
Main and only way to compute Zeeman effect.
Computes the effect and the derivatives.
Should work in NLTE settings but this is not well-tested
Parameters
[in,out] propmat_clearsky as WSV
[in,out] nlte_source as WSV
[in,out] dpropmat_clearsky_dx as WSV
[in,out] dnlte_dx_source as WSV
[in,out] nlte_dsource_dx as WSV
[in] abs_species as WSV
[in] jacobian_quantities as WSV
[in] abs_lines_per_species as WSV
[in] isotopologue_ratios as WSV
[in] partition_functions as WSV
[in] f_grid as WSV
[in] rtp_vmr as WSV
[in] rtp_nlte as WSV
[in] rtp_mag as WSV
[in] rtp_los as WSV
[in] rtp_pressure as WSV
[in] rtp_temperature as WSV
[in] manual_zeeman_tag Sets whether the the magnetic field is input manually
[in] manual_zeeman_magnetic_field_strength Magnetic field strength
[in] manual_zeeman_theta Magnetic field theta angle
[in] manual_zeeman_eta Magnetic field eta angle
Definition at line 85 of file zeeman.cc.
References abs, ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), Zeeman::AllPolarization(), Zeeman::AllPolarization_deta(), Zeeman::AllPolarization_dtheta(), any_negative(), bad_abs_species(), bad_propmat(), dabs, Linefunctions::dDopplerConstant_dT(), Conversion::deg2rad(), Linefunctions::InternalData::dF, Linefunctions::InternalData::dN, ARTS::Var::dnlte_dx_source(), dnumber_density_dt(), Linefunctions::DopplerConstant(), dplanck_dt(), ARTS::Var::dpropmat_clearsky_dx(), dsingle_partition_function_dT(), equivalent_propmattype_indexes(), Linefunctions::InternalData::F, ARTS::Var::f_grid(), Zeeman::FromGrids(), Zeeman::FromPreDerived(), is_zeeman(), ARTS::Var::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), joker, MapToEigen(), Linefunctions::InternalData::N, Array< base >::nelem(), Absorption::nelem(), ARTS::Var::nlte_dsource_dx(), ARTS::Var::nlte_source(), ns, number_density(), ARTS::Var::partition_functions(), planck(), ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_los(), ARTS::Var::rtp_mag(), ARTS::Var::rtp_nlte(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), ARTS::Var::rtp_vmr(), Zeeman::SelectPolarization(), Linefunctions::set_cross_section_of_band(), Zeeman::SigmaMinus, single_partition_function(), and temperature_perturbation().
Referenced by propmat_clearskyAddZeeman().