ARTS: zeeman.cc File Reference
zeeman.cc File Reference
Public methods of ARTS to compute Zeeman effects.
#include "zeeman.h"
#include "constants.h"
#include "linefunctions.h"
#include "linescaling.h"
#include "species_info.h"
Functions
template<class T >
bool bad_propmat (const Array< T > &main, const Vector &f_grid, const Index sd=4)
Checks if a Propagation Matrix or something similar has good grids.
bool bad_abs_species (const ArrayOfArrayOfSpeciesTag &abs_species)
Checks if abs_species is acceptable.
bool any_negative (const Vector &var)
Checks for negative values.
bool any_negative (const Tensor4 &var)
Checks for negative values.
void zeeman_on_the_fly (ArrayOfPropagationMatrix &propmat_clearsky, ArrayOfStokesVector &nlte_source, ArrayOfPropagationMatrix &dpropmat_clearsky_dx, ArrayOfStokesVector &dnlte_dx_source, ArrayOfStokesVector &nlte_dsource_dx, const ArrayOfArrayOfSpeciesTag &abs_species, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfAbsorptionLines &abs_lines_per_species, const SpeciesAuxData &isotopologue_ratios, const SpeciesAuxData &partition_functions, const Vector &f_grid, const Vector &rtp_vmr, const EnergyLevelMap &rtp_nlte, const Vector &rtp_mag, const Vector &rtp_los, const Numeric &rtp_pressure, const Numeric &rtp_temperature, const Index &manual_tag, const Numeric &H0, const Numeric &theta0, const Numeric &eta0)
Main and only way to compute Zeeman effect.
Detailed Description
Public methods of ARTS to compute Zeeman effects.
Header of Zeeman propagation matrix calculations.
Implementations of Zeeman propagation matrix calculations.
Author
Richard Larsson <larsson (at) mps.mpg.de>
Date
2012-08-14
Several methods to change and alter and in other way set up Zeeman effect calculations are implemented in this file
Author
Richard Larsson <larsson (at) mps.mpg.de>
Date
2014-10-14
This file implements Zeeman propagation matrix calculations while also computing the derivatives that might be interesting for later Jacobian deductions.
Author
Richard Larsson <larsson (at) mps.mpg.de>
Date
2014-10-14
Definition in file zeeman.cc.
Function Documentation
any_negative() [1/2]
bool any_negative (const Tensor4 & var)
Checks for negative values.
Definition at line 76 of file zeeman.cc.
References min, and linalg::var().
any_negative() [2/2]
bool any_negative (const Vector & var)
Checks for negative values.
Definition at line 66 of file zeeman.cc.
References min, and linalg::var().
Referenced by zeeman_on_the_fly().
bad_abs_species()
bool bad_abs_species (const ArrayOfArrayOfSpeciesTag & abs_species)
Checks if abs_species is acceptable.
Definition at line 51 of file zeeman.cc.
References ARTS::Var::abs_species(), and Species.
Referenced by zeeman_on_the_fly().
bad_propmat()
template<class T > bool bad_propmat (const Array< T > & main, const Vector & f_grid, const Index sd = 4)
Checks if a Propagation Matrix or something similar has good grids.
Definition at line 38 of file zeeman.cc.
References ARTS::Var::f_grid(), main(), and linalg::var().
Referenced by zeeman_on_the_fly().
zeeman_on_the_fly()
void zeeman_on_the_fly (ArrayOfPropagationMatrix & propmat_clearsky, ArrayOfStokesVector & nlte_source, ArrayOfPropagationMatrix & dpropmat_clearsky_dx, ArrayOfStokesVector & dnlte_dx_source, ArrayOfStokesVector & nlte_dsource_dx, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfAbsorptionLines & abs_lines_per_species, const SpeciesAuxData & isotopologue_ratios, const SpeciesAuxData & partition_functions, const Vector & f_grid, const Vector & rtp_vmr, const EnergyLevelMap & rtp_nlte, const Vector & rtp_mag, const Vector & rtp_los, const Numeric & rtp_pressure, const Numeric & rtp_temperature, const Index & manual_tag, const Numeric & H0, const Numeric & theta0, const Numeric & eta0)
Main and only way to compute Zeeman effect.
Computes the effect and the derivatives.
Should work in NLTE settings but this is not well-tested
Parameters
[in,out] propmat_clearsky as WSV
[in,out] nlte_source as WSV
[in,out] dpropmat_clearsky_dx as WSV
[in,out] dnlte_dx_source as WSV
[in,out] nlte_dsource_dx as WSV
[in] abs_species as WSV
[in] jacobian_quantities as WSV
[in] abs_lines_per_species as WSV
[in] isotopologue_ratios as WSV
[in] partition_functions as WSV
[in] f_grid as WSV
[in] rtp_vmr as WSV
[in] rtp_nlte as WSV
[in] rtp_mag as WSV
[in] rtp_los as WSV
[in] rtp_pressure as WSV
[in] rtp_temperature as WSV
[in] manual_zeeman_tag Sets whether the the magnetic field is input manually
[in] manual_zeeman_magnetic_field_strength Magnetic field strength
[in] manual_zeeman_theta Magnetic field theta angle
[in] manual_zeeman_eta Magnetic field eta angle
Definition at line 85 of file zeeman.cc.
References abs, ARTS::Var::abs_lines_per_species(), ARTS::Var::abs_species(), Zeeman::AllPolarization(), Zeeman::AllPolarization_deta(), Zeeman::AllPolarization_dtheta(), any_negative(), bad_abs_species(), bad_propmat(), dabs, Linefunctions::dDopplerConstant_dT(), Conversion::deg2rad(), Linefunctions::InternalData::dF, Linefunctions::InternalData::dN, ARTS::Var::dnlte_dx_source(), dnumber_density_dt(), Linefunctions::DopplerConstant(), dplanck_dt(), ARTS::Var::dpropmat_clearsky_dx(), dsingle_partition_function_dT(), equivalent_propmattype_indexes(), Linefunctions::InternalData::F, ARTS::Var::f_grid(), Zeeman::FromGrids(), Zeeman::FromPreDerived(), is_zeeman(), ARTS::Var::isotopologue_ratios(), ARTS::Var::jacobian_quantities(), joker, MapToEigen(), Linefunctions::InternalData::N, Array< base >::nelem(), Absorption::nelem(), ARTS::Var::nlte_dsource_dx(), ARTS::Var::nlte_source(), ns, number_density(), ARTS::Var::partition_functions(), planck(), ARTS::Var::propmat_clearsky(), ARTS::Var::rtp_los(), ARTS::Var::rtp_mag(), ARTS::Var::rtp_nlte(), ARTS::Var::rtp_pressure(), ARTS::Var::rtp_temperature(), ARTS::Var::rtp_vmr(), Zeeman::SelectPolarization(), Linefunctions::set_cross_section_of_band(), Zeeman::SigmaMinus, single_partition_function(), and temperature_perturbation().
Referenced by propmat_clearskyAddZeeman().